### ISSUE TITLE
Toolbar button `Show Ref Log` does not work on first click

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#10009]
### Environment

- Git Extensions 33.33.33
- Build 56f797126690cd72178c80ee41ec90437147f6e2
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.5
- DPI 96dpi (no scaling)

### Issue description

The button state seems to be correctly initialized.
Though when clicked, it does not really hide the Ref Log on first click.

### Steps to reproduce

- activate `Show Ref Log`
- restart GE
- try to hide the Ref Log by clicking the toolbar button

### Did this work in previous version of GitExtensions?

most likely in 3.5.4

**Comment by mstv** [comment]
@RussKie, is there a known issues in WinForms?

**Comment by RussKie** [comment]
I'm not observing any issues. An animation could help here.

https://user-images.githubusercontent.com/4403806/194703548-6884db8f-9926-4588-a84c-d5b623e2b4a6.mp4

**Comment by mstv** [comment]
I finally got it:

STR:
- activate RefLog
- close GE
- start two instances
- turn RefLog off in first instance
- try to turn off in second instance

This caused by reloading settings but not updating neither the toolbar nor the grid.
Anyway modifications to view settings should not affect other instances, i.e. they shall not be stored at once but on exit.

Workaround: deactivate RefLog in one instance, just refresh the others.

**Comment by RussKie** [comment]
Great job finding a repro.

I've been thinking about an unrelated use case which has the same
consequences, and I think we should make some settings "current session
only", i.e. do not persist those into the settings file.

These settings would include:
- branch option (all/current/etc)
- blame

**Comment by gerhardol** [comment]
Could be configurable too, like fileviewer options
(prefer not to, but just want to mention)
![image](https://user-images.githubusercontent.com/6248932/194773066-c185e1e1-9886-46a2-9e9b-ebef0f29e9a2.png)

**Comment by mstv** [comment]
BTW: Just noticed ![image](https://user-images.githubusercontent.com/36601201/194776444-ebc60d6a-91f8-47c2-ae29-26ae6cdaacee.png) does not work. It has been off all the time.

**Comment by mstv** [comment]
from https://github.com/gitextensions/gitextensions/issues/8006#issuecomment-1250862922

> Perhaps we must split the settings.
> Alternatively, we could ignore the "view settings" on reload during runtime. Though then the last change of the view settings will be used on restart but not those from the last instance closed. Unexpected UX as well.
>
> I prefer a set of default view settings for the DiffViewer and for the RevisionGrid. (Temporary) changes should not be stored. Rather store them on explicit request.

**Comment by RussKie** [comment]
@mstv yep, 💯.
