### ISSUE TITLE
hotkey conflict on Ctrl-O

### ISSUE THREAD

**Issue by jlinBE** [gitextensions/gitextensions#10004]
### Environment

- GitExtensions version: 3.5.4.12724

### Issue description

Both Start->Open and "Open working directory file with" are bound to Ctrl-O.  The latter is not usable through hotkey.

### Steps to reproduce

select file
press ctrl-O

**Comment by mstv** [comment]
Just focus the file list of the `Diff` (`Ctrl+3`) or of the `File tree` tab (`Ctrl+4`) and `Open working directory file with ...` "wins".

One can change the assignment of hotkeys in the Settings dialog.

**Comment by jlinBE** [comment]
For some reason this command can't be reassigned.  It's not in the settings dialog.
