### ISSUE TITLE
Crash in the commit dialogue with submodules whose path contain unicode characters and are not clean

### ISSUE THREAD

**Issue by ggnkua** [gitextensions/gitextensions#10010]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4510.0
- DPI 96dpi (no scaling)

### Issue description

This is not something I am 100% sure, but to the best of my understanding the crash happens when all the conditions in the subject are met

### Steps to reproduce

(Again, I haven't tried to repro these steps, I am just deducing from what I notice)

- Clone a repository
- Add a submodule whose path contains a unicode character (such as "ł")
- Change some of the submodule's files
- Open the commit dialog. There should appear a line with a submodule and a red exclamation mark, no other text
- Click on the line with the submodule
- Crash

**Comment by RussKie** [comment]
If you can provide a stable repro someone can look into it. Without a stable repro there isn't much we can do.
