### ISSUE TITLE
Uninstaller behaviour is unreasonable and buggy

### ISSUE THREAD

**Issue by Katharsas** [gitextensions/gitextensions#10017]
### Environment

- GitExtensions version: 3.4.3.9999-d4b0f48bb
- OS version: Win 10
- Don't know about other versions

### Issue description

Note that the version is a bit older, so maybe it has been fixed since/

So here is what happened when i uninstalled GitExtensions:
- A window popped up telling me that Firefox and Explorer need to be closed before uninstalling. Weird because i have no idea what Git Extensions has to do with Firefox, it should not ever need to care about my Firefox installation. Maybe because it is my standard browser? It also should not have to "restart" explorer, i have never seen a program that tries to restart explorer just to change some shell extensions.
- I manually closed Firefox (i always do this manually because Firefox takes a long time to close itself and a lot of programs cannot deal with that and i don't want FF to be just killed instantly). This caused FF to weirdly crashed on closing, which it usually doesn't, but who knows, i don't think GitExtensions had messed with it at that point in time.
- I manually closed my explorer windows (note that i am using the windows setting that creates separate explorer processes for each explorer window)
- I clicked the button that would continue the uninstall process (telling me that it will close open programs automatically)
- **The uninstaller closed my main desktop's explorer process, even though there was no explorer window open anymore!** This means that the Windows Taskbar and Desktop just disappears! It also didn't restart them.
- I manually restarted the explorer via TaskManager, and it didn't work properly, which is the first time this has happened to me in over 15 years of windows usage. It started, but apparently was hung in a loop restarting and killing itself over and over every half a second. So basically my Taskbar was blinking, constantly appearing and disappearing. Then i just killed any explorer process i could find in TaskManager and managed to recover to a normal state.

So all in all, it was not really bad for me because i know how to use the TaskManager and how to deal with explorer.exe hickups, but it would have been really bad for somebody not experienced with windows. GitExtensions should not mess with explorer (and certainly not Firefox) in the first place.

### Steps to reproduce

See description.

**Comment by vbjay** [comment]
It had to unload the shell extension that provides the git extensions menus
when right clicking a file or folder. That's why it restarted explorer.

**Comment by Katharsas** [comment]
I have a lot of other programs that modify the explorer shell: Git standalone, Notepad++, 7zip, WinMerge
I don't think any of these has ever required an explorer restart on either install or uninstall, does GitExtensions do something special?

**Comment by vbjay** [comment]
Shell extensions have to be unloaded. Do your research on it. Can't delete
a file that is loaded in a process.

**Comment by Katharsas** [comment]
You can tell explorer to load and unload shell extensions via registry (maybe it only works if it was registered). That way the process does not need to be restarted. You can try by installing and uninstalling 7-zip. The shell extension will be removed while explorer is running, without any problems and without restart.

I think yhis is how every other windows program deals with this problem gracefully and without baiscally making the users computer unusable unless the user knows how to fix explorer process.
