### ISSUE TITLE
Get "PI20.2" branch from the history for VesselDesign which is currently not present in the repository

### ISSUE THREAD

**Issue by H365975** [gitextensions/gitextensions#10023]
### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

Get "PI20.2" branch from the history for VesselDesign which is currently not present in the repository

### Steps to reproduce

-

### Did this work in previous version of GitExtensions?

-

### Diagnostics

-

**Comment by H365975** [comment]
Any action taken for this as I dont see this branch yet in the repository

**Comment by pmiossec** [comment]
@H365975 You're issue is absolutely not clear.
We don't have access to your repository : What is "PI20.2"? VesselDesign?

If that's a real issue, you should provide a lot more information, explanation and screenshots...

Or better a reproduction case on a public repository.

But it seems for me more a problem of understanding how git works and you have not created a local branch tracking a remote one...

Maybe try to checkout the remote and select "Create local branch with the name":
![image](https://user-images.githubusercontent.com/460196/171603770-82a4e73b-dfe8-4ebb-9292-c219e91adcba.png)

![image](https://user-images.githubusercontent.com/460196/171603723-21ecb526-2ae3-48c0-9453-6699db8f4273.png)

**Comment by H365975** [comment]
If you guys can help me with how to get old deleted branches only with branch name

**Comment by pmiossec** [comment]
It is not possible to find a deleted branch by it's name. Once the branch is deleted, it's gone.
But the last commit pointed by the branch should be still there and you should be able to recreate the branch.

2 possibilities to try to find the commit:
1. 
![image](https://user-images.githubusercontent.com/460196/171625707-8947ea3e-2be7-4b7f-98e1-4f4babccdf89.png)

2. 
![image](https://user-images.githubusercontent.com/460196/171625795-459f1c79-dc07-4bbd-b6f6-26418dbdbf29.png)


PS: If you don't spend some time to provide us meaningful information to try to help you (and 1 vague sentence each time is not enough), don't expect us to spend time trying to solve **YOUR** problem...
