### ISSUE TITLE
Using the `git blame` function can be very slow

### ISSUE THREAD

**Issue by XMuli** [gitextensions/gitextensions#10020]
### Environment

- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4510.0
- DPI 96dpi (no scaling)

### Issue description

**Gitextensions is Very good software, I like it a lot. **

But every time I use the `git blame` function, I get stuck for a long time, and clicking on it will often result in a grayed out UI waiting for a response. If you optimize this feature, you can give up using `TortoiseGit` altogether.

But not as fast as `TortoiseGitBlame.exe`, every time this feature, will be used with this software extra.

### Steps to reproduce

as shown：
![image](https://user-images.githubusercontent.com/33887845/171371640-2999dfc0-0b16-4182-b5f4-f2a74dae7b30.png)

![image](https://user-images.githubusercontent.com/33887845/171371662-da78b048-017c-4005-9c30-3527867a7d45.png)

### Did this work in previous version of GitExtensions?

OK, very slow too.

### Diagnostics

OK, but very slow.

**Comment by XMuli** [comment]
I wonder if it has anything to do with the size of my warehouse?

The same test with a large repository (10G), TortoiseGitBlame.exe is also able to be very fast.

Come on (ง -_-)ง

![20220127154637](https://user-images.githubusercontent.com/33887845/171372718-92d2c51d-b8ff-4b74-9457-20a69e928e09.gif)

**Comment by XMuli** [comment]
I usually look in the explorer's right-click menu to see its modification history (`blame`).

tool log should be this：?

![image](https://user-images.githubusercontent.com/33887845/171596687-78363644-a755-4b0d-83f5-41be6dd82a76.png)


thanks, friend

**Comment by RussKie** [comment]
No.
What's the experience when you run the same command from git cli?

**Comment by XMuli** [comment]
This picture is perhaps what I want to express:

![image](https://user-images.githubusercontent.com/33887845/171600552-bf81e34c-d15c-4870-af39-18f1a70c2e05.png)

**Comment by XMuli** [comment]
> What's the experience when you run the same command from git cli?

The speed is fast. But it is displayed in the terminal (pwsh7.2)

**Comment by pmiossec** [comment]
@XMuli 

I think that what @RussKie is asking you (and also me) is the time to run the blame command which should be a command like this one:

`git blame --porcelain -M -C -w -l "97a8c6a42118240b6b0f84a042359565b6928709" -- ".gitignore"`

In the image, is displayed the time to start a new instance of GitExtensions to display the blame information.
We would like to now if it's retrieving the information from git that is long (and so we can't get better) or if it's GE processing and display that is long...

@RussKie Correct me if I misunderstood you...

>This picture is perhaps what I want to express:

@XMuli With your last image, I'm lost and I don't understand where you think it's slow :(

1. Is it opening the new instance and before clicking on a revision which is slow?
2. or is it once you click which is slow?

**Comment by XMuli** [comment]
> With your last image, I'm lost and I don't understand where you think it's slow :(

@pmiossec It keeps showing **blank**(The UI of the child window is blank) in step3, **which causes me to think it's slow** (it actually requires an extra click on one of the items).

**Comment by RussKie** [comment]
The screenshot is showing that there is no commit is selected, hence the
bottom panel is blank. Once a selection is made the info for the selected
commit is loaded and shown.

Am I understanding this correctly?

**Comment by pmiossec** [comment]
@XMuli If I understand well, it is for you more a problem of user experience where no line is selected and that makes you think that the blame is slow.

If that's the case, the blame feature has been changed in the development version (as I told you in a previous message) and doesn't behave like that anymore.

So I think the problem doesn't exist anymore.

You would test the development version ( https://github.com/gitextensions/gitextensions#downloads ) and give your feedback on it...

**Comment by XMuli** [comment]
@RussKie  Yeah, that's about it.   ヾ(≧▽≦*)o

**Comment by RussKie** [comment]
@XMuli try the latest dev build and see if it works.

Thank you @pmiossec for your help.

**Comment by XMuli** [comment]
I was using this version of Git Extensions 3.5.4.12724, but because of #9998, I've temporarily fallen back to the previous version (Git Extensions 3.5.3.12551).

I'll try this development version later. Thank you both for your replies.

>  If I understand well, it is for you more a problem of user experience where no line is selected

I didn't know it was "designed that way". Hahahahahahahahahahahahaha

**Comment by XMuli** [comment]
> Oh and last question: Do you have the avatar displayed? And is it faster if not displayed?

And after setting not to display, the experience is great (obviously a lot faster)
