### ISSUE TITLE
Right click -> "Reset file or directory changes" does nothing

### ISSUE THREAD

**Issue by asfarley** [gitextensions/gitextensions#10022]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4510.0
- DPI 96dpi (no scaling)

### Issue description

I have a Git repository with one modified file. If I open the Commit window, right click the file and select "Reset file or directory changes", I see a "blink" but then the UI returns to the same state and the file is unchanged. 

Screen video:
[https://youtu.be/v0YIVIg1RLY](https://youtu.be/v0YIVIg1RLY)

### Steps to reproduce

Check out this repository:
https://github.com/asfarley/gplex

Open project in VS2022

Attempt to change .NET target framework

VS2022 crashes

Solution file is now modified, although I can't tell what the modification is by looking. Looks like maybe a white-space character has been modified or something. 

### Did this work in previous version of GitExtensions?

Not tested

### Diagnostics

I checked the Git Command Log, and surprisingly I don't see any commands which appear to be checking out or resetting files. The most recent command is just `git status` with a bunch of option flags.

**Comment by RussKie** [comment]
Is this reproducible? Is this happening with any other repositories? ...or
is this happening only when VS is involved?

Please try the latest dev build and see if it works,
https://github.com/gitextensions/gitextensions#downloads.

**Comment by mstv** [comment]
> Please try the latest dev build and see if it works,

👍 It will pop up error messages from the executed git command.
I could not find the git command in the video (log window too small, scrolled too quickly).

It looks like an line ending issue.

You can display whitespace using:

![image](https://user-images.githubusercontent.com/36601201/171683517-dbceb0a6-69b3-4d39-b00f-0a13725fdfb7.png)

Perhaps the line endings setting should be changed:

![image](https://user-images.githubusercontent.com/36601201/171683727-03c6e121-9466-4659-bc07-c83f1aa569d2.png)

**Comment by asfarley** [comment]
@RussKie It is reproducible for me: I can delete the entire repo, replay my steps and I end up at the same condition. I am not sure if I've seen this outside of VS involvement. I will try your dev build.

I turned on the "show non-printing characters" option, but both original and modified text still look the same to me:
![image](https://user-images.githubusercontent.com/1622578/171685888-b7c855cd-6f18-4b31-9c80-856072ad9adc.png)

My line-ending settings are set to "checkout as-is, commit as-is". Therefore, I expected that if there was any detectable difference between the committed line-endings and the working state line-endings, it would be eliminated by a file reset.

**Comment by asfarley** [comment]
@RussKie Looks like the dev build has failed, I see no installer or executable here:
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by asfarley** [comment]
Attached is a log file including the call-stack. The actions shown are: 
 * Clicking the 'commit' icon
 * Selecting the file to be reset
 * Right-click -> Reset File
 * Close commit window

[gitextensions log with call stack.txt](https://github.com/gitextensions/gitextensions/files/8826156/gitextensions.log.with.call.stack.txt)

The command which isn't working as I expect is at line 489:
git	checkout-index --index --force -- "GPLEXv1.sln"	C:\Vital-Sim\GardensPoint\gplex\

**Comment by asfarley** [comment]
Ok, I am testing by running these commands on the command-line and it appears that this is a Git issue, not a GitExtensions issue, because I am getting exactly the same results (checkout does nothing, file still shown as modified). I will close this issue and do some searching on Git.

**Comment by asfarley** [comment]
For future readers, the issue turns out to be that the repository had a .gitattributes file (which I've never used before) and inside, it was setting line-ends to 'auto'. I didn't realize there were multiple places to configure that behavior.

**Comment by pmiossec** [comment]
Git settings was the first way to manage end of line.
'.gitattributes' is the more recent and recommended one.
