### ISSUE TITLE
VS plugin: Make 'Show untracked files' configurable

### ISSUE THREAD

**Issue by jsmith911** [gitextensions/gitextensions#1005]
I'd ask to make 'Working dir changes/show untracked files' configurable in Vistual Studio plugin.

In my use case I'd turn off 'Working dir changes/show untracked files' by default to speedup plugin loading. In most cases I do not need to see untracked files and I believe that it is typical use case for everyone.

And thanks for great work - it is one of best VCS plugins for VS.

**Comment by RussKie** [comment]
Closing due to age.
