### ISSUE TITLE
Some local branches could not be deleted anymore due to the state of the remote

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#10122]
### Environment

- Git Extensions 33.33.33
- Build f312b6a1206faef9e42cb87cbaf2cf1ea714c223
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.6
- DPI 96dpi (no scaling)

### Issue description

Following redesign of FormDeleteBranch in #8956, local branches that are merged into HEAD but that have there remote not merged can't be deleted anymore (because the "force delete" checkbox has been removed.

![image](https://user-images.githubusercontent.com/460196/182158119-31f765b8-cf5a-4313-9fe9-f2d3a27bba06.png)

### Steps to reproduce

1. Having local branch merged into HEAD
2. Having remote of this branch ahead (because another dev has pushed new commits) or behind (because your merged it locally)
3. try to delete the local branch
4. Git refuse to delete it because it is not in sync with the remote (even if merged into HEAD). See screenshot above

### Did this work in previous version of GitExtensions?

Yes, in v<4.0

### Diagnostics

We can no more force delete (sometimes)

**Comment by RussKie** [comment]
We want to bring the checkbox back?

**Comment by mstv** [comment]
Yes, it weirdly depends on the current checkout or the like. *And* the dialog opens annoyingly slow.

> We want to bring the checkbox back?

No, I was too defensive when the dialog was reworked. Now I think the dialog is confirmation enough for force deletion - regardless of the merge state.

**Comment by RussKie** [comment]
Just to confirm, you're ok with dropping the "unmerged" check and pass `force: true`, right?
https://github.com/gitextensions/gitextensions/blob/bbf8bc5f10060f3518d01a27559fc25fd5a49b53/GitUI/CommandsDialogs/FormDeleteBranch.cs#L107

**Comment by mstv** [comment]
> Just to confirm, you're ok with dropping the "unmerged" check and pass `force: true`, right?

Yes, I have changed my mind since the review of the previous PR.
Furthermore, `hasUnmergedBranches` etc. should be removed (or be determined asynchronously).
