### ISSUE TITLE
GitExtensions is not friendly with vscode as merge tool

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#10133]
### Environment

- Git Extensions 33.33.33
- Build 6a4f9858bfa5d85227f18e0a848dc4259bea8f38
- Git 2.35.1.windows.2 (recommended: 2.37.1 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.6
- DPI 96dpi (no scaling)

### Issue description

When vscode is in the PATH , you could use:
* ✔`code` or "C:/Users/31594/AppData/Local/Programs/Microsoft VS Code/bin/code" in editor are working (because it resolves to "C:/Users/31594/AppData/Local/Programs/Microsoft VS Code/bin/code" which is a sh script launch by git using sh)
* ✔same values in diff tool are working (because it resolves to "C:/Users/31594/AppData/Local/Programs/Microsoft VS Code/bin/code" which is a sh script launch by git through the `git diff` command)
* ❌**same values in merge tool are NOT working. Because it resolves to "C:/Users/31594/AppData/Local/Programs/Microsoft VS Code/bin/code" which is a sh script that GitExtensions try to launch itself with a `Process.Start` )**

You will have the error:

![image](https://user-images.githubusercontent.com/460196/183094473-e9445a1e-8335-4743-a5f8-9c268e8748be.png)

and in the command logs the error:

>System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'C:\Users\31594\AppData\Local\Programs\Microsoft VS Code\bin\code' with working directory 'C:\Taliance\Dev\ArgusTaliance\'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String prefixArguments, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute, Boolean throwOnErrorExit) in C:\Perso\Dev\github\gitextensions\GitCommands\Git\Executable.cs:line 124

The command run looks like:

```
File name:   C:\Users\31594\AppData\Local\Programs\Microsoft VS Code\bin\code
Arguments:   "code" --wait --merge "C:\Folder\file.cs.REMOTE" "C:\Folder\file.cs.LOCAL" "C:\Folder\file.cs.BASE" "Folder/file.cs"
```

So, the suggested value by GitExtensions `code` is not working and we have 2 options (difficult to understand for a user --it took me long while debugging 😉 )

1. Set the full path toward the exe or the cmd files i.e "C:\Users\31594\AppData\Local\Programs\Microsoft VS Code\Code.exe" or "C:\Users\31594\AppData\Local\Programs\Microsoft VS Code\bin\code.cmd". Very difficult to find 😒
2. Set `code.cmd` in "Path to mergetool" but in this case, GE behave strangely and try to launch as command "Path to mergetool" with arguments "Merge tool command" (so the become misleading and it's no more the command but the arguments) and so if we want to have it woking, we should fill the field with `--wait --merge "$REMOTE" "$LOCAL" "$BASE" "$MERGED"` instead.

I think we will have an issue opened soon (so I created it for us 😁) now that VSCode could be run as a 3way merge tool:

https://code.visualstudio.com/updates/v1_70#_command-line-option-merge

### Steps to reproduce

1. install vscode as per user install and add it in the PATH
2. set `code` as path in merge tool
3. Try to resolve a merge conflict

### Did this work in previous version of GitExtensions?

Don't know.

**Comment by gerhardol** [comment]
Merge is special, GE has some special handling and the tools are started explicitly.
Difftool always started by Git. Git merge handling requires use of terminal.
![image](https://user-images.githubusercontent.com/6248932/183119961-2d216d37-3f54-454e-b034-973db80945f3.png)
So you should be able to use mergetool too...

**Comment by RussKie** [comment]
> The command run looks like:
> 
> ```
> File name:   C:\Users\31594\AppData\Local\Programs\Microsoft VS Code\bin\code
> Arguments:   "code" --wait --merge "C:\Folder\file.cs.REMOTE" "C:\Folder\file.cs.LOCAL" "C:\Folder\file.cs.BASE" "Folder/file.cs"
> ```

Could you clarify whether `C:\Users\31594\AppData\Local\Programs\Microsoft VS Code\bin\code` refers to a file or a folder. 



> So, the suggested value by GitExtensions `code` is not working and we have 2 options (difficult to understand for a user --it took me long while debugging 😉 )

The diff tools definitions are here: https://github.com/gitextensions/gitextensions/blob/master/GitCommands/DiffMergeTools/. The VS Code specific one is here: https://github.com/gitextensions/gitextensions/blob/master/GitCommands/DiffMergeTools/VsCode.cs. The manager is here: https://github.com/gitextensions/gitextensions/blob/master/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs.
Right now we only search for diff/merge tools under Program Files:
https://github.com/gitextensions/gitextensions/blob/6a4f9858bfa5d85227f18e0a848dc4259bea8f38/GitCommands/PathUtil.cs#L404-L447

**Comment by pmiossec** [comment]
> The command run looks like:
>
> File name:   C:\Users\31594\AppData\Local\Programs\Microsoft VS Code\bin\code
>
> Arguments:   "code" --wait --merge "C:\Folder\file.cs.REMOTE" "C:\Folder\file.cs.LOCAL" "C:\Folder\file.cs.BASE" "Folder/file.cs"
>
>
> Could you clarify whether C:\Users\31594\AppData\Local\Programs\Microsoft
> VS Code\bin\code refers to a file or a folder.
>
As I said above, when you set 'code' because it is in the PATH and are able
to run VScode just by typing that in the command line, in GitExtensions it
is not working because it is resolved to this path which point to vscode sh
script that can't be launched as a process. So it fails.


I have as much as possible with the time I got to be able to open an issue
but it requires more investigation to understand why sometimes the merge
command is run directly and sometimes it's taken just as arguments to the
executable...

It's still to be decided if it's the vscode config that we should fix or if
there is a bug in the way we build the strings to launch. It could also be
just a problem of UX. I still don't exactly know.

The only thing that I know is that no user in this case will be able to set
up vscode as a merge tool in GitExtensions 😕

>

**Comment by RussKie** [comment]
It has to be either one or another - i.e. either use the full path or use the executable name (if it's on the path). Here's you mix the two.
![image](https://user-images.githubusercontent.com/4403806/183247084-fa8bede8-fed0-4521-8c38-56b0fb0bbc0a.png)

Also, as I said above, we don't currently search the %user% path, and that's something to consider. Anyone who's using VS Code as diff/merge tool is welcome to suggest a fix.
