### ISSUE TITLE
Opens Branch listbox by unrelated actions

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#10143]
### Environment

- GitExtensions version: 4.0 (31f3c27)
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

Opens "Branch filter" listbox by unrelated actions

### Steps to reproduce

- Click inside of the Grid
- Click "Change working directory" listbox
- Both of "Change working directory" and "Branch filter" listboxes are opened

**Comment by gerhardol** [comment]
Fixed in #10140 
Waiting for reviews
