### ISSUE TITLE
Problem building solution using VS2019

### ISSUE THREAD

**Issue by geerligs** [gitextensions/gitextensions#10142]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.37.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0
- DPI 96dpi (no scaling)

### Issue description

When trying to build GitExtensions using VS2019 I am not able to load the projects.

### Steps to reproduce

I followed the steps as described in https://github.com/gitextensions/gitextensions/wiki/How-To%3A-build-instructions

1. clone the (forked) repo with initialize submodules
2. open VS 2019 CE and select the GitExtensions solution
3. After opening no project is loaded, When doing a reload I see in the output window the text below.

As a side note: when using VS2022 I am able to load the projects in the solution.
Might the MSBuild component in VS2019 be out of date?

D:\work\gitextensions\Externals\Git.hub\Git.hub\Git.hub.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\GitExtensions\GitExtensions.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\GitUI\GitUI.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\GitCommands\GitCommands.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\GitUIPluginInterfaces\GitUIPluginInterfaces.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\Statistics\GitStatistics\GitExtensions.Plugins.GitStatistics.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\ResourceManager\ResourceManager.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\Gource\GitExtensions.Plugins.Gource.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\DeleteUnusedBranches\GitExtensions.Plugins.DeleteUnusedBranches.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Externals\NetSpell.SpellChecker\SpellChecker.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\Statistics\GitImpact\GitExtensions.Plugins.GitImpact.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\CreateLocalBranches\GitExtensions.Plugins.CreateLocalBranches.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\FindLargeFiles\GitExtensions.Plugins.FindLargeFiles.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\GitHub3\GitExtensions.Plugins.GitHub3.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\ProxySwitcher\GitExtensions.Plugins.ProxySwitcher.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\ReleaseNotesGenerator\GitExtensions.Plugins.ReleaseNotesGenerator.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\TranslationApp\TranslationApp.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\BackgroundFetch\GitExtensions.Plugins.BackgroundFetch.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\AutoCompileSubmodules\GitExtensions.Plugins.AutoCompileSubmodules.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\GitFlow\GitExtensions.Plugins.GitFlow.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\BuildServerIntegration\TeamCityIntegration\TeamCityIntegration.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\Bitbucket\GitExtensions.Plugins.Bitbucket.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\BuildServerIntegration\JenkinsIntegration\JenkinsIntegration.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\GitExtUtils\GitExtUtils.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Externals\conemu-inside\ConEmuWinForms\ConEmuWinForms.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\BuildServerIntegration\AppVeyorIntegration\AppVeyorIntegration.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\GitCommands.Tests\GitCommands.Tests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\GitUI.Tests\GitUI.Tests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\Plugins\ReleaseNotesGenerator.Tests\ReleaseNotesGenerator.Tests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\ResourceManager.Tests\ResourceManager.Tests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\JiraCommitHintPlugin\GitExtensions.Plugins.JiraCommitHintPlugin.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\CommonTestUtils\CommonTestUtils.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Plugins\BuildServerIntegration\AzureDevOpsIntegration\AzureDevOpsIntegration.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\GitExtUtils.Tests\GitExtUtils.Tests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\Externals\ICSharpCode.TextEditor\Project\ICSharpCode.TextEditor.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\Plugins\GitUIPluginInterfaces.Tests\GitUIPluginInterfaces.Tests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\Plugins\BuildServerIntegration\AzureDevOpsIntegration.Tests\AzureDevOpsIntegration.Tests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\Plugins\BuildServerIntegration\AppVeyorIntegration.Tests\AppVeyorIntegration.Tests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\Plugins\DeleteUnusedBranches.Tests\DeleteUnusedBranches.Tests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\IntegrationTests\UI.IntegrationTests\UI.IntegrationTests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\BugReporter\BugReporter.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\UnitTests\BugReporter.Tests\BugReporter.Tests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

D:\work\gitextensions\IntegrationTests\BugReporter.IntegrationTests\BugReporter.IntegrationTests.csproj : error  : The project file cannot be opened. Version 6.0.302 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.11.2.50704. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available.

### Did this work in previous version of GitExtensions?

not applicable

**Comment by gerhardol** [comment]
VS2022 is required what I know. There may be some way to use an updated msbuild in 2019, but 2022 is what is supported. 
Vs code works in master.

**Comment by RussKie** [comment]
.NET 6 works with VS 2022, you can download it from https://visualstudio.microsoft.com/downloads/.

**Comment by pmiossec** [comment]
If you don't want to install the community version (for a reason that I
don't get), maybe the build tools will work...

https://visualstudio.microsoft.com/downloads/?q=build+tools#build-tools-for-visual-studio-2022

**Comment by gerhardol** [comment]
Wiki updated
https://github.com/gitextensions/gitextensions/wiki/How-To:-build-instructions

Someone with a need for VS2019 could update if it is possible with a separate build tool installation.

**Comment by geerligs** [comment]
Thanks all for the swift response!
