### ISSUE TITLE
Reword Commit in File History view rebases to the parent in the grid

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#10147]
### Environment

- GitExtensions version: 4.0
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

By clicking Reword Commit in File History view, Git Extensions rebases to the previous revision of the history item, not the parent revision.

### Steps to reproduce

1. Open the File History view.
2. Right-click a revision and select Reword.
3. Git Extensions rebases to the previous revision of the history item. (This is often an older revision than the parent revision.)

### Did this work in previous version of GitExtensions?

Yes. Git Extensions 3.5 does not have the functionality to Reword in the File History view.

**Comment by gerhardol** [comment]
Always copy the release details when reporting:
![image](https://user-images.githubusercontent.com/6248932/184097401-fbda95b0-9f7b-4987-811c-5aa8c540168f.png)

This is not a new problem, it occurred previously also when the revision grid was filtered for other reasons.
Reword (and Edit) commit is a rebase operation and the parent in the grid is not the parent to rebase on.
What is changed in 4.0 is that the separate FileHistory form is not used by default.

One way to avoid this is to disable the operation when the parents are rewritten (the grid is filtered).
It may be possible to change the commands to, will look at that.
