### ISSUE TITLE
Copy path from repository root

### ISSUE THREAD

**Issue by QuAzI** [gitextensions/gitextensions#10158]
### Feature description

Please add "Copy relative path" in the same way as it shown in Diff files list.
![image](https://user-images.githubusercontent.com/1897605/185578296-58fcdadc-e942-4727-838b-13b76cee3ea0.png)

As example JetBrains Rider has the same feature: File Menu -> Copy Path -> Path From Repository Root
and it's very useful

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.37.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.9035.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
The menu is quite crowded already, is this really that important to increase even further?
I believe editing is good enough when a relative path is needed.

**Comment by RussKie** [comment]
I've given this some thought, and I now wonder what value "Copy full path" has, as developers clone their repos in custom locations. I'm leaning towards suggesting the "Copy full path" should be replaced with "Copy relative path".
If a full path is truly necessary, a user can click "Show in folder" and copy the full path from there.

**Comment by gerhardol** [comment]
> I've given this some thought, and I now wonder what value "Copy full path" has, as developers clone their repos in custom locations. I'm leaning towards suggesting the "Copy full path" should be replaced with "Copy relative path". If a full path is truly necessary, a user can click "Show in folder" and copy the full path from there.

But it is easier to just remove the prefix then to restore it (to use explorer is something you have to think about).
MSVS has only full path, VS Code has both full and relative.

**Comment by pmiossec** [comment]
I wonder if we could do the same thing that has been done for the diff
tools.
The click on  the menu item does something by default (maybe full path as
now) and opening a sub-menu let the user choose between the 2 options.

**Comment by mstv** [comment]
Any objections?

![grafik](https://user-images.githubusercontent.com/36601201/206878065-a29c891f-dc95-4532-a285-47862c59111b.png)

**Comment by mstv** [comment]
For the default entry, one can click the parent item `Copy path(s)` directly. That's why the default entry is bold.
The alternative items need a little less mouse movement.

**Comment by RussKie** [comment]
Alright

**Comment by gerhardol** [comment]
Fine for me.

You know that there will be requests for Cygwin and WSL paths too?

> For the default entry, one can click the parent item Copy path(s) directly. That's why the default entry is bold.
The alternative items need a little less mouse movement if not below the default entry.

I still would prefer it in the top.

**Comment by mstv** [comment]
Do you still think the menu items should be ordered like

![image](https://user-images.githubusercontent.com/36601201/209887301-45983b97-434b-4652-a045-be97014cbbfb.png)

?

I find

![image](https://user-images.githubusercontent.com/36601201/209887056-6a2f5248-7e1c-4af4-9741-7801bc1934ae.png)

clearer and more efficient since relative paths are used more often - at least in chats and documentation.

I will implement the order with the most votes. It will not affect my workflow much because I will use `right click + p + p`.

**Comment by RussKie** [comment]
Thank you for asking. I don't have a strong preference either way.

**Comment by vbjay** [comment]
$0.02. If root menu copies full path then first sub menu should be relative copy.

**Comment by gerhardol** [comment]
Default (bold) first

**Comment by vbjay** [comment]
I disagree. Kinda silly to have the sub menu do the same as the root menu. Make the first menu do the other so root does default and first menu in sub does the relative. That 2ay it's simple slide over and click.
