### ISSUE TITLE
Console window appears on some Git commands

### ISSUE THREAD

**Issue by ulrichb** [gitextensions/gitextensions#10166]
### Environment

- Git Extensions 4.0.0.15025
- Build e8588e4c048e94d62054911fc09decb8139931f6
- Git 2.37.2.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.8
- DPI 96dpi (no scaling)

### Issue description

After updating to v4 alpha1, a console window appears (for a short time) on e.g. a Git Pull operation:

![image](https://user-images.githubusercontent.com/388796/186892793-640a5427-760f-42e9-aa97-9a49cf47e5a5.png)

... it also seems that it doesn't emit any output in this window.

Note that this only happens when _deselecting_ the option "Use Console Emulator for console output in command dialogs" (non default).

Note that I also _don't_ have enabled the other option "Show console window when executing git process" (left default here).

### Steps to reproduce

* Disable "Use Console Emulator for console output in command dialogs"
* Do a Git operation like pull or push
 * Note that it doesn't happen on e.g. commit or checkout

### Did this work in previous version of GitExtensions?

Yep, v3

**Comment by mstv** [comment]
Also reproducible with v3.5.4!

**Comment by mstv** [comment]
This has not changed since 2010.

**Comment by RussKie** [comment]
This has always behaved like this without the conemu.

**Comment by ulrichb** [comment]
Okay, this baffles me. I've always deactivated the conemu setting and never got the console window. Also it directly started appearing after the 4.0 alpha 1 update (from 3.5.4) ...

**Comment by ulrichb** [comment]
Oh, .... this is a consequence of "PuTTY binaries are no longer bundled with Git Extentions" .... 

After configuring the `AppSettings.SshPath` with a path to a `plink.exe` it behaves like before, due to logic in `UseSsh()` (which I don't really understand, but at least I heave a workaround now 😄).
