### ISSUE TITLE
Context menu on origin appears at top of screen

### ISSUE THREAD

**Issue by gregwinterstein** [gitextensions/gitextensions#10165]
### Environment

- GitExtensions version: 4.0.0.15025
- GIT version: 2.37.1.windows.1
- OS version: Microsoft Windows NT 10.0.19042.0
- .NET version: 6.0.8

### Issue description

The first time the Context menu on Remotes-->origin is invoked by right-clicking, the context menu appears at the top of the screen:
![image](https://user-images.githubusercontent.com/68340656/186781805-96f541a5-cd85-43e8-9e60-b92003112187.png)

Second and subsequent invocations of the Context menu on origin render the Context menu in the expected location:
![image](https://user-images.githubusercontent.com/68340656/186782317-7b2243c0-973d-4d4d-947c-d125874fe600.png)

### Steps to reproduce

1) Open GitExtensions
2) Select a repository
3) Right-click on origin under Remotes
4) Context menu is rendered at the top of the screen rather than near where the right-click was made.

### Did this work in previous version of GitExtensions?

Yes. Previous version of GitExtensions, v3.5.4.

**Comment by mstv** [comment]
most likely a regression from #9723, @h0lg

**Comment by gerhardol** [comment]
I tried to debug. The problem only occurs if no node is selected first.
The Location in GitUI\BranchTreePanel\RepoObjectsTree.cs:OnNodeClick() seem OK, but is changed in contextMenu_Opening() (the coordinates do not have the same base position, but is off by a lot).
Cannot see why.

**Comment by h0lg** [comment]
Thanks for having a look and sharing your findings @gerhardol . I will have a go at it tomorrow.

**Comment by RussKie** [comment]
It looks like a genuine Windows Forms bug. I've had a quick debug session, and on the first run the `Location` property of the context menu gets assigned incorrectly:
![image](https://user-images.githubusercontent.com/4403806/190946688-f3be9fc2-6664-4b91-8804-8f0aceb15bae.png)

...on the second run, it's correct:
![image](https://user-images.githubusercontent.com/4403806/190946710-03eaf8c7-4637-47ed-bd47-95a9ed28ded1.png)

**Comment by h0lg** [comment]
^^ that comment of RussKie relates to something I wrote in https://github.com/gitextensions/gitextensions/pull/10197
