### ISSUE TITLE
Cannot build after .NET update

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#10177]
### Environment

- .NET version: 6.0.8

### Issue description

The .NET SDK 6.0.400 seems to not match the requested version in `global.json`:
```
{
    "sdk": {
       "version": "6.0.201",
       "rollForward": "feature"
    }
}
```

### Steps to reproduce

- install .NET 6.0.8 (6.0.7 enforced by GE)
- build GE

**Comment by mstv** [comment]
Workaround: Remove `.201`.

**Comment by gerhardol** [comment]
I can build with 6.0.400
![image](https://user-images.githubusercontent.com/6248932/188302109-6fc8fada-3eaa-46f7-b601-a65d2399fa52.png)

6.0.7 should have been set to 6.0.8 in master (was set to 6.0.8 in release/4.0 07973db2e10331913fde6fadd84ac23958a3e1d4)

**Comment by RussKie** [comment]
> Workaround: Remove `.201`.

👍

**Comment by mstv** [comment]
I don't have installed a .NET SDK older than 6.0.400 as gerhardol (anymore).
I wonder why it does not match although "rollForward" is specified.
I am creating a PR.
