### ISSUE TITLE
Show First Parents does not hide unrelated branches

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#10187]
### Environment

- Git Extensions 33.33.33
- Build be7c1e7eaefd45a48f2f2926b04d318e29edd0a1
- Git 2.37.2.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.8
- DPI 96dpi (no scaling)

### Issue description

Show First Parents does not hide unrelated branches

### Steps to reproduce

- Click "Show first parents" in toolbar or menu

**Comment by gerhardol** [comment]
Intended change from https://github.com/gitextensions/gitextensions/pull/10172

The switch now behaves as described in https://git-scm.com/docs/git-log#Documentation/git-log.txt---first-parent
Set Current branch only to only see the current branch

**Comment by shirayuki** [comment]
Thank you for your prompt response.
I will try that next time.
