### ISSUE TITLE
Multiple line editing

### ISSUE THREAD

**Issue by racecrew** [gitextensions/gitextensions#10186]
### Feature description

Introduce a feature "multiple line editing" like in Notepad++ with "shift+crtl+down/up arrrow"

![image](https://user-images.githubusercontent.com/17234283/189094757-b1929196-60b6-4f0f-a847-c76664dc92d8.png)

### Environment

Git Extensions 3.5.4.12724
    Build https://github.com/gitextensions/gitextensions/commit/65f01f39982ccb121c4df7d4b00b506939553958
    Git 2.37.0.windows.1
    Microsoft Windows NT 10.0.19044.0
    .NET Framework 4.8.9035.0

**Comment by RussKie** [comment]
Thank you for the suggestion, however Git Extensions is not a text editor.
