### ISSUE TITLE
Error while opening Settings form (Tools>Settings)

### ISSUE THREAD

**Issue by imtiazahmeddahar** [gitextensions/gitextensions#10200]
### Environment

- GitExtensions version: ..5.4.12724
- GIT version: 2.30.1
- OS version: Windows 11
- .NET version: 4.8.4515.0

### Issue description

This error is occurred few months ago and I tried everything to resolve this issue by myself but could not succeed. I have deleted all directories of GitExtension from %appdata%\roaming and %appdata%\local including [WindowPositions.xml and GitExtensions.settings]. I have also uninstalled this previous all version and installed new version from scratch but still same error.

This version works perfectly in my laptop but unable to open in my other machine, however, I can not reinstall my operating system as there are hundreds of software which I have to install again including configurations.

### Steps to reproduce

1. Open GitExtension
2. Click on Tools in Menu bar
3. Click on Settings (or shortcut Ctrl+,).

4. you will see below error

![image](https://user-images.githubusercontent.com/10320924/190976571-c62a57fa-d6a7-4bdf-bab2-babdf6737295.png)

### Did this work in previous version of GitExtensions?

No.

**Comment by pmiossec** [comment]
It seems to be a problem with the paths of the diff or merge tools (in the `.gitconfig` file)
One of them must contains an illegal character (for windows) in the path.

Can you post the content of these paths here?
After that, could you edit the config file or use the git command line to remove it or set it again to see if it fix the issue?

**Comment by imtiazahmeddahar** [comment]
I am unable to open settings dialog, when I click okay button it shows below figure and close settings dialog automatically.

In this case, I could not get diff or merge tools settings. Furthermore, where can I find .gitconfig [directory?] file.

![image](https://user-images.githubusercontent.com/10320924/190983365-1211478f-6c4e-40f6-a8d8-2c8681c56f80.png)

**Comment by pmiossec** [comment]
The `.gitconfig` file (normally) is in your personal folder `%HOMEPATH%` (past it in file explorer address bar)

**Comment by imtiazahmeddahar** [comment]
.gitconfig file's content, however, I have changed my user name email to dummy while all other content as it is in file.

[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
[user]
	name = MyUserName
	email = MyEmailAddress@email.com
[core]
	editor = \"C:/Program Files (x86)/notepad++/notepad++.exe\" -multiInst -nosession
	compression = 0
[merge]
	guitool = vsdiffmerge
	tool = vsdiffmerge
[pull]
	rebase = false
[fetch]
	prune = false
[rebase]
	autoStash = false
[diff]
	tool = vsdiffmerge
	guitool = vsdiffmerge
[difftool]
	prompt = true
[difftool "vsdiffmerge"]
	keepBackup = false
[mergetool]
	prompt = true
[mergetool "vsdiffmerge"]
	cmd = \"\" /m \"$REMOTE\" \"$LOCAL\" \"$BASE\" \"$MERGED\"
	keepBackup = false
	trustExitCode = true
	path = \"C:/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/vsdiffmerge.exe\" \"$REMOTE\" \"$LOCAL\" \"$BASE\" \"$MERGED\" //m

**Comment by pmiossec** [comment]
Try replace the empty path in the `cmd` of `[mergetool "vsdiffmerge"]` section by a real existing path like (if it exists):
`"C:/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/vsdiffmerge.exe"` to have a line looking like:

     cmd = "C:/Program Files (x86)/Microsoft Visual Studio 12.0/Common7/IDE/vsdiffmerge.exe" /m "$REMOTE" "$LOCAL" "$BASE" "$MERGED"

**Comment by pmiossec** [comment]
You could also try (after a backup) to remove the whole `[mergetool "vsdiffmerge"]` section and try to set again the merge tool in GitExtensions settings

**Comment by imtiazahmeddahar** [comment]
Thank you very much, God bless you, above technique worked and I just deleted .gitconfig file.

I was worried for couple of months, you saved me.



You saved me.

**Comment by gerhardol** [comment]
This setting should raise a popup and ignore the current value, with a popup.

**Comment by imtiazahmeddahar** [comment]
It would be better if said option is added and raise a popup.
