### ISSUE TITLE
Update submodules after rebase

### ISSUE THREAD

**Issue by abruceTDK** [gitextensions/gitextensions#10202]
### Feature description

Currently, if you are rebasing commits in the main branch that contain changes to a submodule, the submodules do not get updated after the rebase, so it shows that there are changes to the submodule.

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.37.2.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.9082.0
- DPI 120dpi (125% scaling)

**Comment by RussKie** [comment]
Do you have this setting checked?
![image](https://user-images.githubusercontent.com/4403806/193456932-cda1e4c2-4b0d-4f2d-be2f-489c97e83bcf.png)

**Comment by abruceTDK** [comment]
Yes I do. It seems that we both expect that it would cover this case, but it doesn't seem to.

**Comment by jxr98** [comment]
I think this is a good practice for me. Can I have a try?

**Comment by RussKie** [comment]
Absolutely! Holler, if you have questions. Thanks

**Comment by jxr98** [comment]
Hi @abruceTDK. I am trying to reproduce the problem. I have tried the following two scenarios.

1. - checkout a new branch f from master
    - make some changes to the submodule and commit both in the submodule and the main project
    - checkout master
    - rebase master against f on gitextensions

2.  - checkout master
     - make some changes to the submodule and commit both in the submodule and the main project
     - make some changes to the submodule and commit both in the submodule and the main project
     - rebase the two commits on gitextensions
     
I ran `git status` after rebase, but it showed clean working tree. Could you please provide more details about how to reproduce the problem. That would be really helpful. Thanks.

**Comment by abruceTDK** [comment]
@jxr98 I'll try to reproduce again some point soon. I wonder if maybe having to solve merge conflicts during the rebase might have something to do with it.

**Comment by RussKie** [comment]
@abruceTDK please reopen, if the issue comes back.
