### ISSUE TITLE
Change current branch width in menu

### ISSUE THREAD

**Issue by yulObraz** [gitextensions/gitextensions#10201]
### Feature description

There must be possibility to set a minimal width for menu items. It is especially needed for "Change current branch". It may be some setting for the menu.

Task: Switch from a feature branch to the master branch and click to pull button.

Expected: Make pull.

The result: Commit window is opened because menu items changed positions. The master branch has a shorter name. So click on a previous position of the pull button results in click of the commit button.

![image](https://user-images.githubusercontent.com/8803586/190987383-cc189afd-37c3-4319-8246-34d18b9ef354.png)

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.37.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3752.0

**Comment by pmiossec** [comment]
> There must be possibility to set a minimal width for menu items. It is especially needed for "Change current branch". It may be some setting for the menu.

Adding a settings for that will be very strange. It's means that just for a problem of refresh that is temporary, you will waste  (a lot of) space in the toolbar? And if one day you have a longer branch name, the value won't be long enough. It really seems a hack.
GitExtensions already have a problem of too many settings that most users never changes and I really don't think we should add one for that.

A workaround is to hide the branch selector combobox in the toolbar ("View" menu -> Toolbars -> Standard -> "Change current branch") and use the left panel (right click or double click) to switch from branches.
