### ISSUE TITLE
fatal: This operation must be run in a work tree

### ISSUE THREAD

**Issue by TheObliterator** [gitextensions/gitextensions#1020]
Since updating to gitextensions 2.32 I now get an error whenever I try to commit my changes or checkout a branch:
"fatal: This operation must be run in a work tree"

At first I presumed it was a corrupt repo, but the problem affects all of my repos which used to work fine before I updated.
The 2.33 update doesn't help either.

I'm not working with a bare directory, so I don't understand the problem. I've even tried cloning the repo again - but the clone suffers from the same problem.
Any ideas how I resolve this?

**Comment by ealonwang** [comment]
Thanks @TheObliterator , I have googled and tried various solutions, and only yours perfectly works.

**Comment by vbjay** [comment]
You shouldn't be messing with the .git folder except for modifying hooks.
Otherwise, act like it doesn't exist.

**Comment by TheObliterator** [comment]
Well in my case I wasn't trying to do anything with the .git folder... I was simply using that as a method to launch git extensions.

Consider this example working dir structure with a one file and one folder in the repo:
MyRepoDir\.git\
MyRepoDir\MySubFile.txt
MyRepoDir\MySubFolder\

Historically I would right click on the .git subfolder and choose GitEx Browse from the context menu to launch GitEx for that repo. That seemed logical to me as I want to browse that repository. This worked fine until GitEx v2.32, then it stopped working. 2.32+ appears to open the repo as normal but any subsequent actions result in the 'operation must be run in work a tree' error.

If I right click on MySubFolder or MySubFile.txt and choose GitEx Browse - it works perfectly. But right clicking on the .git folder results in a different behaviour. I think the reason for the failure is it includes the .git subfolder in the repo path when it should be stripped.

I think this is actually a small bug in GitEx as the behaviour changed in 2.32 - hence me posting this issue back then - but maybe its by design as the issue was closed out.

Either way the workaround is easy - right click on any other file/folder in the working directory or on the working directory folder itself at the parent level. 

@ealonwang Glad my post helped! I found the same with lots of references to the error but none identifying this as a possible cause.

**Comment by vbjay** [comment]
Right. The problem is that the .git folder is the revised database. It us
not part of the repo. It is the repo. You don't act like it exists except
for hook modification. Your idea that you should be right clicking on it is
flawed. The point of the right click menu us to run a command and the
command finds and uses the .git folder inside of the folder being right
clicked. Now do you see the problem?

**Comment by ghanique** [comment]
You get to same result when opening a --shared repository (i.e.: a
repository without a working directory) in Git Extensions.

**Comment by TheObliterator** [comment]
Yes I do see where you are coming from.

However, I find it strange I can right click on the parent folder, or in subfolders, or on files/folders alongside .git. - GitEx Browse works perfectly in all these scenarios... traversing up, down or alongside for the .git folder. Yet when I identify the very repo folder itself - it fails. Maybe the GitEx browse context menu should simply be disabled for the actual .git folder in that case.

My logic possibly is flawed! ;) But it does make sense to me at least... .git folder is the repo - I want to Browse that repo - hence right click on it and choose GitEx Browse. Either way its a non issue and easy enough for me to simply avoid doing this! Feel free to close it out.

Thanks to the team for such a great tool by the way - its by far my preferred Git client.
