### ISSUE TITLE
Filter grid with Git options

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#10213]
### Feature description

The arguments to filter the revision grid does not have the full possibilities as is available in Git.
* Hide specific branches
* Show all stashes without reflog
* Certain regexp content searches
Especially https://git-scm.com/docs/git-log#_history_simplification has a lot of possibilities.

A GUI for this would be very complex, still not covering all possibilities.
One way is to allow the user to enter custom options in the revision fulter toolbar box (probably with a dropdown of the last used arguments).
A problem is that if the user is allowed to enter data here, it could cause the Git command to fail, blaming the program.
A possible implementation is to expect that the user add custom arg if the search string starts with a certain string, like "--not" which should be a common filter anyway (--not --not will allow normal filters).

### Environment

- Git Extensions 33.33.33
- Build a07f37895dd708033b88c5d9de2c6adcaff17587 (Dirty)
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
> * Hide specific branches

I think this what a lot of users would want, and I think there have been asks for this feature.
I also think it probably wouldn't be too difficult to implement using [ToolStripControlHost](https://learn.microsoft.com/dotnet/api/system.windows.forms.toolstripcontrolhost) using a custom filter control that would be based on a [CheckedListBox](https://learn.microsoft.com/dotnet/api/system.windows.forms.checkedlistbox) and a few buttons to select/deselect all. 
A little complication could be defining an algorithm to determine which branches to include/exclude depending on how many branches would be selected/deselected, as it would have the direct impact on the git command.

**Comment by gerhardol** [comment]
> > * Hide specific branches
> 
> I think this what a lot of users would want, and I think there have been asks for this feature. I also think it probably wouldn't be too difficult to implement using 

I want to filter out branches using wildcards, no point in excluding something if you have to do it every time there is a change
