### ISSUE TITLE
[NBug] Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#10219]
### Environment

- Git Extensions 4.0.0.15291
- Build 8b80e54f15e8923a85f5801cca033f932ced821f
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

### Issue description

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.VisualStudio.Composition.Reflection.ResolverExtensions.Resolve(ParameterRef parameterRef)
   at Microsoft.VisualStudio.Composition.Reflection.ParameterRef.get_ParameterInfo()
   at Microsoft.VisualStudio.Composition.ImportDefinitionBinding.get_ImportingParameter()
   at Microsoft.VisualStudio.Composition.ComposedPart.GetDiagnosticLocation(ImportDefinitionBinding import)
   at Microsoft.VisualStudio.Composition.ComposedPart.Validate(IReadOnlyDictionary`2 metadataViews)+MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.VisualStudio.Composition.CompositionConfiguration.Create(ComposableCatalog catalog)
   at GitUIPluginInterfaces.ManagedExtensibility.CreateExportProvider(String applicationDataFolder)
   at GitUIPluginInterfaces.ManagedExtensibility.<>c__DisplayClass7_0.<GetOrCreateLazyExportProvider>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitUIPluginInterfaces.ManagedExtensibility.GetExport[T]()
   at GitUI.CommitInfo.CommitInfo..ctor()
   at GitUI.CommandsDialogs.FormBrowse.InitializeComponent()
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands commands, BrowseArguments args)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, BrowseArguments args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

Got this error starting GitExtensions.

### Steps to reproduce

I got this error after installing the v4 beta version and trying to start it.

**Comment by asherber** [comment]
Note that this error is occurring on my personal desktop computer. The GitExt beta is working just fine on my very similarly configured personal laptop, as well as on my work computer.

**Comment by mstv** [comment]
I almost don't dare to ask whether you have restarted the PC after updating .NET.

How do you start GE?
Perhaps it works via the context menu of an existing repo clone in the Explorer.

**Comment by asherber** [comment]
I didn't need to restart, because I already had the desktop runtime installed, but I just restarted and I'm still getting the exception. Also, FWIW, I did need to install the desktop runtime on my work machine, but no reboot was necessary there -- GitExt worked just fine.

I start GitExt from the Start menu. (Actually from a launcher that reads Start menu entries, but even starting direct from the Start menu makes no difference.)

Using the context menu on a repo in Explorer gives the same exception.

**Comment by mstv** [comment]
Thank you for testing again, @asherber!
Could you try my wild guess of a fix, please?
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/44957059/artifacts

**Comment by asherber** [comment]
Well, the portable version works -- but the portable of 15291 works also. The MSI version gives the same error, even after a reboot.

Just for kicks, I tried deleting my settings file, but that didn't help.

**Comment by mstv** [comment]
The portable and the installed version *do* contain the same DLLs.
Could you install it again into a new / emptied folder, please?

**Comment by asherber** [comment]
Okay, I uninstalled GitExt, and I noticed that there were a whole bunch of files left behind in Program Files (x86)/GitExtensions. I zipped them up and removed them, then deleted the GitExtensions directory and reinstalled 15291 (original beta). Now everything works.

Are you interested in seeing the files that were left behind after uninstalling?

**Comment by RussKie** [comment]
Yes, please.

Did you install the beta over an existing installation? If, so what version
did you have installed? How was it installed originally?

**Comment by asherber** [comment]
You can grab the zip of the files left behind here: [https://app.box.com/s/277k2rspgqyxter34qlt4j715x7hypo9](https://app.box.com/s/277k2rspgqyxter34qlt4j715x7hypo9)

I installed the beta over my previous installation of 3.5.4, although I had several previous versions installed before that. The beta installation does make me uninstall the previous version, but as you can see it didn't clean out the whole folder. I have always installed GitExt from the MSI installer from GitHub, but during previous rounds of troubleshooting it's possible that I dropped in some files by hand.

My other 2 computers, where the beta worked fine, also had 3.5.4 installed, but they may not have had the same sequence of previous versions.

**Comment by RussKie** [comment]
> it's possible that I dropped in some files by hand.

This, if that happened indeed, could lead to failures, as the app loads all available assemblies in the folder scanning for plugins. Looking at the zip you kindly shared, I see that you had quite a bit of random assemblies all over the place - e.g., the Plugins folder contains a lot of assemblies that aren't meant to be there. E.g.,
![image](https://user-images.githubusercontent.com/4403806/193826047-6af037cb-8d03-41e8-9ba9-9bceb5c4f908.png)
![image](https://user-images.githubusercontent.com/4403806/193826126-9ba85e66-5114-4da5-8457-20f94420973b.png)

The installed only knows about the files it contained, and whenever a package gets uninstalled only the files that the installer knows about get removed. Likely all of those random assemblies got loaded by the host app, and MEF registrations from the rogue assemblies would stomp over the expected registrations.... 
¯\\_(ツ)\_/¯

**Comment by RussKie** [comment]
I'm going to close this since you got it all working. If we get any further tangible information that we can act upon - we can reopen.

Thanks again.

**Comment by mstv** [comment]
Could we clear the destination before installing?

**Comment by vbjay** [comment]
One key thing. Portable should never be copied into program files
anything.   If they do that, default permissions would cause issues.
Portable should be extracted to a folder that is writable and think of self
contained as much as possible. Installer should be installing to program
files folder.  Extracting portable to program files is not supported.

**Comment by vbjay** [comment]
Just making sure it was noted.
