### ISSUE TITLE
Loading submodules crashes the app

### ISSUE THREAD

**Issue by albrei** [gitextensions/gitextensions#10211]
### Environment

- GitExtensions version: 3.5.4.12724
- GIT version: 2.37.3.windows.1
- OS version: Windows 11 build 22000.978
- .NET version: 4.8.4515.0

### Issue description

I cloned a repository that contains submodules. After clone is performed, I can't see any submodule under the "submodules" header in the left side panel.
![image](https://user-images.githubusercontent.com/114576387/192753060-7968a1d3-8ce3-4701-91fe-7502a55e693e.png)

Clicking the yellow submarine button on the top bar shows a dropdown menu with the word "Loading..." only.
![image](https://user-images.githubusercontent.com/114576387/192753154-49e41ddf-0b29-4f99-ba72-57ec1bf421c1.png)

After a couple of minutes, the app closes, even with zero user interaction.

Sourcetree does show the submodules in the same local copy and does not crash nor close.
![image](https://user-images.githubusercontent.com/114576387/192755317-0827d8cb-5251-49be-9d7c-b1e0fffe15df.png)

I uninstalled Git Extensions and git --> deleted any traces in %USERPROFILE%\AppData and Windows registry --> rebooted --> installed git --> rebooted --> installed Git Extensions --> rebooted --> and problem still persists.

### Steps to reproduce

Clone a reponsitory with submodules. Open the repository in Git Extensions. Just wait for Git Extensions to hang and then close.

**Comment by vbjay** [comment]
When cloninf did you check the checkbox to handle submodules. If not you have to init them. You want to hit the update submodules menu.

**Comment by albrei** [comment]
Unfortunately I experience the same crash in the latest alpha.

**Comment by pmiossec** [comment]
For debugging purpose, if you open one of the submodule repo directly with GitExtensions, do you have an issue or does it open successfully?

**Comment by albrei** [comment]
Same issue. I can open the submodule repo with Git Extensions, but it after a few minutes it crashes and closes. It also shows "Loading..." in the top bar dropdown menu, though the button is now a blue arrow instead of a submarine.

**Comment by gerhardol** [comment]
Can you please list  what Git process that runs?
This could be a Git command that runs a very long time.
Please use the 4.0 alpha.

Open dashboard, open Git command log, open the repo or submodule.
Take snapshot before the crash (at least 10s after opening).

**Comment by mstv** [comment]
If the Git Command Log closes too quickly, you could let write it to file using #9227 (refer to its description how to enable the logging).

**Comment by RussKie** [comment]
Check the Windows EventViewer for stack traces

**Comment by vbjay** [comment]
Is the repo you are cloning, public?  If so provide URL.

**Comment by albrei** [comment]
This is what git command log shows before Git Extensions crashes.
![image](https://user-images.githubusercontent.com/114576387/193002838-955e92c5-f314-4c7f-9e19-88a7dac27a62.png)

About 3 minutes after that last command, Git Extensions closes unexpectedly (well, I was expecting it really).

**Comment by albrei** [comment]
> In addition, you could let write unhandled exceptions to a file using #9227 (refer to its description how to enable the logging).

I followed the steps but no log file is created in %TEMP% after the crash.

**Comment by RussKie** [comment]
There should be another event with the stack trace.

**Comment by albrei** [comment]
I also see this one
![image](https://user-images.githubusercontent.com/114576387/193047954-8ec25107-bf91-4d7d-9b3f-cafdf02088c2.png)

**Comment by albrei** [comment]
Is there any other sort of log that can be useful?

Btw, I realised this does not happen in all repos. Some repos with submodules load just fine. Others crash. And they all work fine in tools such as Sourcetree. Something suspicious that I can check in those repos?

**Comment by RussKie** [comment]
Without stack traces or a stable repro there isn't much we can do. If you can, pull down the source, [build](https://github.com/gitextensions/gitextensions/wiki/How-To%3A-build-instructions) and see what's failing.

**Comment by tnodir** [comment]
> Is the repo you are cloning, public?  If so provide URL.

Try to clone the [Qt](https://code.qt.io/qt/qt5.git) repo.

**Comment by albrei** [comment]
I think I found the issue. The file .gitmodules seemed to be wrong. This was its content:
```
[submodule "include/my_submodule"]
	path = include/my_submodule
	url = http://192.168.1.100/my_submodule.git
[submodule "my_submodule"]
	update = rebase
```
I think the problem is the header tags were different, so I deleted the last section and left "update = rebase" under the first section:
```
[submodule "include/my_submodule"]
	path = include/my_submodule
	url = http://192.168.1.100/my_submodule.git
	update = rebase
```
After this change, Git Extensions does not crash anymore. The interesting point is that both git in the command line nor Sourcetree had any issues with that .gitmodules file.

**Comment by RussKie** [comment]
Thank you for sharing the results of the investigation.

**Comment by gerhardol** [comment]
As path is not set, GE tries to parse the submodule with path "" in GetSubmodulePaths(), which adds the submodules again
