### ISSUE TITLE
Unable to close Settings dialog if opened in the Dashboard

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#10215]
### Environment

- Git Extensions 4.0.0.15291 (v4 beta)
- Build 8b80e54f15e8923a85f5801cca033f932ced821f
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

The same issue occurred for v4 alpha.

### Issue description

It's not possible to close the Settings dialog once it's opened in the Dashboard.

https://user-images.githubusercontent.com/4403806/193531707-91334276-4d98-4874-9345-aa0d500ae47e.mp4

### Steps to reproduce

* Start the app at the dashboard
* Open the Settings dialog
* Try closing it

### Did this work in previous version of GitExtensions?

Yes, in v3.5

**Comment by pmiossec** [comment]
Doesn't reproduce with (last `upstream/release/4.0`) :

- Git Extensions 33.33.33
- Build fe4d963dc68ca59c864f7d64b2e515554507c906
- Git 2.38.0.windows.1 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

**Comment by AdrianJSClark** [comment]
I'm seeing this with the 4.0 release version.

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 168dpi (175% scaling)

**Comment by anton-platzoeder** [comment]
I am also seeing this with version 4.0.0.15569

In addition to this, when the Settings dialog opens, no other pane opens when clicking on an item in the lefthand tree.

**Comment by richsidney** [comment]
- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 192dpi (200% scaling)

I've had the settings page work once. Most times it won't react to selecting different settings areas, and won't close.

**Comment by maxhouck** [comment]
I would like to clarify my behavior (and it seems the original poster's as well) - the settings dialog doesn't work only when opened from the "Dashboard" home page. It works fine for me when launched after I've selected a git repo.
