### ISSUE TITLE
The Console tab not shows GIT folder

### ISSUE THREAD

**Issue by petrf22** [gitextensions/gitextensions#10221]
### Environment

- Git Extensions 4.0.0.15291
- Build 8b80e54f15e8923a85f5801cca033f932ced821f
- Git 2.33.0.windows.2 (recommended: 2.37.1 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

### Issue description

In the Console tab with WSL shows the user's home folder instead of the GIT folder.

### Steps to reproduce

Open Git Extensions 4.0.0.15291, click The Console tab.

### Did this work in previous version of GitExtensions?

Yes, but version 3.x uses a different shell.

**Comment by gerhardol** [comment]
It shows the expected folder for me.
You can set the shell to use

![image](https://user-images.githubusercontent.com/6248932/193902368-d0bd7aa8-ef42-4563-a1c1-fbb69125faf6.png)

```
user@pc MSYS //wsl$/Ubuntu-20.04/home/user/gc/linux (master)
```

cmd and bash cannot be used with wsl paths

```
'\\wsl$\Ubuntu-20.04\home\user\gc\linux'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Microsoft Windows [Version 10.0.19044.2006]

user@pc C:\Windows
$
```

**Comment by petrf22** [comment]
I must have spelled it wrong, I'm sorry.
My problem is on the Console tab, the picture will tell you more.
In my case, the directory is displayed correctly after entering the command in the console tab "wsl --cd p:\okp".
Version 3 with MSYS:
![gitext-3-msys](https://user-images.githubusercontent.com/1553587/194492999-f296cc27-7876-401f-b17c-797539cfbfe9.png)
Version 4 with WSL:
![gitext-4-wsl](https://user-images.githubusercontent.com/1553587/194493164-50caeb1b-a9cd-4471-b94f-5eb4bfffee45.png)

**Comment by gerhardol** [comment]
> I must have spelled it wrong, I'm sorry. My problem is on the Console tab, the picture will tell you more. In my case, the 

Set the terminal as displayed
Also make sure you have set the Git Linux tools in GE settings Git-Config

**Comment by petrf22** [comment]
Thank you for your help.
The problem was of course on my side, because WSL does not support disk substitution.
I have mapped the P:\ disk to the C:\P\ directory and that's the whole problem.
Sorry for the delay.
