### ISSUE TITLE
v4 beta "Show current branch only" shows blank page

### ISSUE THREAD

**Issue by moso1** [gitextensions/gitextensions#10225]
### Environment

- GitExtensions version: 4.0.0.15291
- GIT version: 2.38.0
- OS version: Windows 10
- .NET version: .NET 6.0.9

### Issue description

From v4 beta, clone gitextensions repo itself, change to Show current branch only, then it shows a blank page.

### Steps to reproduce

View, Show current branch only

### Did this work in previous version of GitExtensions?

Yes.

**Comment by mstv** [comment]
Sorry, this went wrong in one of the last pull-requests before the beta.

**Comment by gerhardol** [comment]
Show Git Notes to see the current branch for now
