### ISSUE TITLE
Can't open more than one repository at once, in different tabs or windows??

### ISSUE THREAD

**Issue by php4fan** [gitextensions/gitextensions#10238]
### Environment

- GitExtensions version: 2.51.05
- GIT version: 
- OS version: Manjaro Linux
- .NET version: 

### Issue description

see below

### Steps to reproduce

- Go to Start / Open, choose a folder and click Open
- Repeat with another folder

Expected: should either open the second repository in another tab or window, OR ask me whether I want to open it to another tab or window or close the current one.

Observed: it closes the current one and opens the new one, as if you cannot have more than one repository open in separate tabs or windows at the same time.

**Comment by gerhardol** [comment]
Open a new instance of GE. Tabs are not feasible with WinForms, this is not planned for any GE version.
