### ISSUE TITLE
File browser (e.g. open repository) sorts files randomly

### ISSUE THREAD

**Issue by php4fan** [gitextensions/gitextensions#10237]
### Environment

- GitExtensions version: 2.51.05
- GIT version: 
- OS version: Manjaro Linux
- .NET version: 

### Issue description

I go to Open Local Repository and click Browse.

The ONLY acceptable way of sorting files and folders by default (or as the only option if you don't allow me to choose a sorting criteria) is alphabetically.

I don't know how the files are sorted, if by date of last modification, or utterly randomly, but it's definitely not alphabetical.

### Steps to reproduce

go to Start / Open and then click Browse.

![image](https://user-images.githubusercontent.com/13969584/194714593-597b379a-3a3b-4a4d-bce7-5ea76b3b88d5.png)

**Comment by RussKie** [comment]
This would likely be an issue with Mono Windows Forms. It definitely isn't something we control in the app.
I recommend raising the issue in https://github.com/mono/mono/labels/area-BCL%3A%20System.Windows.Forms.
