### ISSUE TITLE
Right click hidden node raises popup

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#10250]
### Environment

- Git Extensions 4.0.0.15025
- Build e8588e4c048e94d62054911fc09decb8139931f6
- Git 2.38.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

GE 4.0 has feedback when a branch etc in the side panel is not in the grid.
This prevents double clicking on a branch to check it out, but ctrl-select for multi is possible. This may be OK, you can still use the menu.
However, it is annoying that right clicking on the branch etc raises the popup. Fortunately, the menu is not closed so you can select from it.

### Steps to reproduce

* Filter branches, for instance Only current branch.
* Rightclick a hidden branch
![image](https://user-images.githubusercontent.com/6248932/195449221-c9280ede-4dd4-4268-9aed-a3f774680ac7.png)

### Did this work in previous version of GitExtensions?

3.5.4 without the popup

**Comment by gerhardol** [comment]
I expected checking for right mousebutton to be sufficient to suppress this, but `MouseButtons` is always None (also at callers).
Maybe related to the changes in #9723. Any input @h0lg ?

````c#
       protected void SelectRevision()
        {
            TreeViewNode.TreeView?.BeginInvoke(new Action(() =>
            {
                string branch = RelatedBranch is null || !RepoObjectsTree.ModifierKeys.HasFlag(Keys.Alt)
                    ? FullPath : RelatedBranch.Substring(startIndex: GitRefName.RefsRemotesPrefix.Length);
/* ->*/                bool showPopup = !RepoObjectsTree.MouseButtons.HasFlag(MouseButtons.Right);
                UICommands.BrowseGoToRef(branch, showNoRevisionMsg: showPopup, toggleSelection: RepoObjectsTree.ModifierKeys.HasFlag(Keys.Control));
                TreeViewNode.TreeView?.Focus();
            }));
        }
```

**Comment by gerhardol** [comment]
> @gerhardol I wasn't aware of the static `Control.MouseButtons` and didn't handle mouse buttons except for in `RepoObjectsTree.OnNodeClick()`. But wherever I find `Control.MouseButtons` used, it's compared to using `==` instead of `.HasFlag()`. Have you tried that?

I am pretty sure I tried that - no mouse flag was set at all.

**Comment by vbjay** [comment]
You don't want to use control.MouseButtons.  You want to use the value from event. https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.mouseeventargs?view=windowsdesktop-6.0#properties

**Comment by gerhardol** [comment]
The node is selected in OnNodeSelected(), no mouse info in TreeViewEventArgs.
At least for me, that is called before MouseSelect.
A hack would be to capture right mouse click in NativeTreeViewExplorerNavigationDecorator and ignore the node selection.

```
        private void OnNodeSelected(object sender, TreeViewEventArgs e)
        {
            Node.OnNode<Node>(e.Node, node => node.OnSelected());
        }

            _explorerNavigationDecorator.AfterSelect += OnNodeSelected;

        private void OnAfterSelect(object sender, TreeViewEventArgs e)
        {
            // If arrow key was used to navigate to this node, don't send OnSelected
            int delta = (int)_getCurrentTime().Subtract(_lastKeyNavigateTime).TotalMilliseconds;
            if (delta is (>= 0 and < 500))
            {
                return;
            }

            AfterSelect?.Invoke(sender, e);
        }

```

> You don't want to use control.MouseButtons. You want to use the value from event.

Of course I had checked the event for mouse information.

**Comment by mstv** [comment]
Why not suppress the `SelectRevision()` call in `StashNode.OnSelected()` if invisible?

**Comment by gerhardol** [comment]
> Why not suppress the `SelectRevision()` call in `StashNode.OnSelected()` if invisible?

You may still want to select it, for instance add filtered branches

**Comment by mstv** [comment]
`SelectRevision()` just calls `BrowseGoToRef`, doesn't it?

**Comment by gerhardol** [comment]
> `SelectRevision()` just calls `BrowseGoToRef`, doesn't it?

Yes
Right click selects the node. I did not see a clean way to suppress that.

**Comment by h0lg** [comment]
I've had a poke at it. The result is not pretty - it relies on the order of mouse handler registrations (see [GitUI/BranchTreePanel/RepoObjectsTree.cs](https://github.com/gitextensions/gitextensions/pull/10283/files#diff-30898bcfc538da9210d67dd18ba2b70a86fa054f3b353d0f45747dca0558d408) ). But it does the job if I understood correctly what @gerhardol wanted to achieve.
