### ISSUE TITLE
Fix annoying collapsing of dropdown menus from tool bar buttons

### ISSUE THREAD

**Issue by TanukiSharp** [gitextensions/gitextensions#10254]
### Feature description

Add an option to have the dropdown menus not to collapse when mouse cursor moves away from the open button.
This behavior is super annoying, so having it behind an option would let the user to choose which behavior to have.

This is related to issue #3832 it used to be fixed, but it is now back. I updated the closed issue but it remained unanswered. The fix done was a kind of a hack, so I will propose a better fix in another PR soon.

The behavior of the `ToolStripDropDownItem` is not a bug in `GitExtensions`, I created a vanilla WinForms application to test this behavior, and this is the default behavior, so technically speaking, it's a feature request.

### Environment

- Git Extensions 4.0.0.15025
- Build e8588e4c048e94d62054911fc09decb8139931f6
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The menu stays open for some seconds for me.

> Add an option to have the dropdown menus not to collapse when mouse cursor moves away from the open button. This behavior is super annoying, so having it behind an option would let the user to choose which behavior to have.

Try to make this so an option is not needed. GE has too many options already.

**Comment by TanukiSharp** [comment]
On my side they close immediately.
As you can see on the video below, menus close as soon as there is a mouse interaction with another item in the same ToolStrip container, but not with other controls, such as menu bar. This is clearly emphasized from 0:10' to 0:15' in the video.

https://user-images.githubusercontent.com/4018313/195963038-b278ad59-f244-49c4-bd52-ba9bf8c11af8.mp4

The only way I found to disable mouse interaction with other items in the ToolStrip container is to disable them. I couldn't find a way to just prevent mouse interaction like it's possible with WPF via HitTest or other mechanisms. Disabling and re-enabling controls produces a strange visual effect, personally I don't care to trade visual ugliness for comfortable functionality, but not everyone feels the same, hence I was thinking about an option.

I will make another video of my current prototype soon to show you.

**Comment by TanukiSharp** [comment]
Here is the video of what it looks when disabling all controls.
Note that this is per container, so clicking on the pull button does not disable controls in the filters tool bar, and vice versa.

https://user-images.githubusercontent.com/4018313/195964871-5475cafc-479f-419e-8410-fc4e20abf992.mp4

I'm not an expert with WinForms, just enough knowledge and experience to develop simple applications (long ago), so if you know a way to disable/re-enable controls input without changing their visual, that would be great.

**Comment by TanukiSharp** [comment]
Ohh I found a way. Actually it is, as I expected, the repaint of icons change that triggered the menu collapse.
So it works as expected with simply suspending and resuming the drawing of the owner ToolStrip.

I will cleanup my code and send a PR soon.

**Comment by gerhardol** [comment]
> On my side they close immediately.

Only when there are buttons, not for "All branches" dropdown.
I am used to just move the mouse within the menu, so this has not bothered me...
A video is good, I see what you mean.

**Comment by gerhardol** [comment]
Closed by #10260
