### ISSUE TITLE
illegal character ,wrong path to merge tool cant open settings app crashes

### ISSUE THREAD

**Issue by mohamedwael8440** [gitextensions/gitextensions#10276]
### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

illegal character ,wrong path to merge tool cant open settings app crashes

### Steps to reproduce

,wrong path to merge tool , now cant open settings app crashes

**Comment by pmiossec** [comment]
Some work has been done to handle that in the next version to be released.

So can you update your issue with the version where you found the issue to be sure of what we are talking about?

And can you also test the portable version of the beta (download link in the repository main page) to see if it is already fixed or if it needs more work?

**Comment by RussKie** [comment]
Unfortunately this isn't sufficient for us to triage the issue. Please provide steps to reproduce, stack traces, logs, etc.

**Comment by mohamedwael8440** [comment]
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0
- DPI 120dpi (125% scaling)
-
This is the latest i think,
I used the following path for merge tool
"C:/Program Files (x86)/KDiff3/kdiff3.exe" "$BASE" "$REMOTE" "$LOCAL" -m
as mentioned here [](uhttps://github.com/gitextensions/gitextensions/issues/4364rl)
![image](https://user-images.githubusercontent.com/81769415/196159244-38fe4299-7b50-4520-83c8-625f477e4259.png)

**Comment by gerhardol** [comment]
Please try the latest 4.0 beta that uses .NET6 that has changed implementation for these checks.
Check the actual content for the diff/merge tools in the related config files.
If you have setup the same home in GE as on the commandline:

```bash
git config -l --show-origin | grep tool
```

**Comment by mohamedwael8440** [comment]
solved thank you
used git config --global mergetool.kdiff3.path "C:/Program Files/KDiff3/bin/kdiff3.exe to configure new path
