### ISSUE TITLE
Implement Behaviour option to disable the "double click to stage" mechanic

### ISSUE THREAD

**Issue by Shocker** [gitextensions/gitextensions#10278]
### Feature description

Hello. I find the double click on files in the git commit window to be very frustrating, a lot of times I happen to double click accidentally on a file and have my changes staged. Problem is I often stage some changes then work on the same file (without committing) for extra temporary/test changes, and by accidentally staging the new changes too I lose my possible temporary/test changes diff. An option in the Behaviour settings tab to enable/disable this mechanic would be great

### Environment

- GitExtensions version: Version 2.44 [.Net 4]
- GIT version: 2.32.0.windows.2
- OS version: Windows 10

**Comment by vbjay** [comment]
Maybe adjust double click timing in windows settings?  Make it so you don't
accidently double click .

**Comment by RussKie** [comment]
While I can empathise, I don't see this happening. The app has already way too many settings and configuration. Also, this behaviour has been there for a very long time, and it's quite ubiquitous for Windows in general.

> Problem is I often stage some changes then work on the same file (without committing) for extra temporary/test changes, and by accidentally staging the new changes too I lose my possible temporary/test changes diff.

I think you may find that committing often could help reduce your frustration.
