### ISSUE TITLE
[feature request] Create a worktree from a tag

### ISSUE THREAD

**Issue by prime167** [gitextensions/gitextensions#10279]
### Feature description

Currently, GE only allow create a worktree from a branch. It will be good if GE allow create a worktree from a tag too.

I have to create a worktree from bash by
`git worktree add ../0.0.3_veryOldVersion 0.0.3`

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4515.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
You can add a script that creates a worktree, see Settings > Scripts.

A PR with an improvement is also welcome.

**Comment by mstv** [comment]
You could create a branch first - without checking it out. So your current worktree is not touched.

![image](https://user-images.githubusercontent.com/36601201/197056308-59cbaa0f-b3e0-44d9-9e5e-278496e1aea2.png)

**Comment by prime167** [comment]
OK, I will try. Thank you.
