### ISSUE TITLE
WSL Support for SSH key agent / interactive shells

### ISSUE THREAD

**Issue by Anyqax** [gitextensions/gitextensions#10274]
### Feature description

Currently when pushing or pulling via GitExtensions and from an SSH Git repository in a $wsl path you will be prompted for your SSH key password every time.
This is not neccessary when an ssh key agent is configured in the WSL (e.g. keychain as described here https://esc.sh/blog/ssh-agent-windows10-wsl2/) and pushing or pulling is done directly in the WSL.
The SSH key agent isn't used though when pushing or pulling via Git Extensions because WSL commands do not execute as an interactive shell by default, therefore .bashrc etc. aren't loaded and neither is keychain.
If Git Extensions either always executed WSL Commands with bash shells or alternatively had some means of configuring the WSL command, this would be possible.

The currently generated WSL command which doesn't allow SSH key agents:
`wsl -d <someWslDist> git pull --progress --jobs=0 "origin"`

The proposed WSL command which would allow SSH key agents:
`wsl -d <someWslDist> -e bash -li -c "git pull --progress --jobs=0 "origin""`

### Environment

- GitExtensions version: 4.0.0.15291
- GIT version: 2.37.1
- OS version: Windows 10
- .NET version: 6.0.10

**Comment by gerhardol** [comment]
You should be able to configure this by adding a "git" script in PATH before normal Git and start bash from there.
The "git" command is hardcoded right now, it could be made configurable (at least by editing the settings file), but the quoting will require more changes.

**Comment by gerhardol** [comment]
*wsl* uses the default shell for the default user so you should be able to customize the action here. 
There is no specific environment variable set that identifies GE. Maybe something can be set explicitly in WSLENV if that is needed (Similar to `SetEnvironmentVariables()` for Win executables.)

wsl git can probably be improved some, see for instance #10173. WSL is improving too. Maybe wsl-git is not needed with WSLg, maybe it works better.

> Could you explain the solution "adding a "git"-script?

Add a script called git that wraps the call to the real Git executable. 

> Right now I'm accessing the repos via HTTPS. But that's not a solution either, since I'm asked for my credentials every time

Use the Git Credential Manager installed with git-for-windows from WSL

**Comment by mariolorenz** [comment]
New situation: I could use in Windows 10 as WSL-Path now:
\\wsl.localhost\Ubuntu\home\user\mygitrepo
instead of
\\wsl$\Ubuntu\home\user\mygitrepo
In this case git from windows togehter with puttys SSH Agent works again correctly

**Comment by gerhardol** [comment]
@mariolorenz Then you always use Windows-git, which could be much slower.
You may add a drive letter to \\wsl$\... to use Windows Git, also if you cannot upgrade WSL.
