### ISSUE TITLE
Revision trees are empty when opening left sidebar for the first time

### ISSUE THREAD

**Issue by h0lg** [gitextensions/gitextensions#10284]
### Environment

- GitExtensions version: 4 / build from master
- GIT version: 2.36.1
- OS version: Windows 
- .NET version: 6

### Issue description

When starting GitExtensions **without having the left sidebar open**,
**the trees for Branches, Remotes and Tags are empty** when opening it for the first time.

Clicking the Refresh button **works around** this.

### Steps to reproduce

1. Open GitExtensions
2. Make sure the left sidebar is hidden
3. Close GitExtensions (to have those display settings saved)
4. Reopen GitExtensions
5. Open the left sidebar

### Did this work in previous version of GitExtensions?

This worked fine in version 3.5.4 .

**Comment by gerhardol** [comment]
In 3.5 many calculations were performed also if the side panel was not shown.
A refresh is needed when enabling the sidepanel.

If you hide side panel, switch repo, show side panel, the old branches are shown again.
(restart is not needed to see the problem)
