### ISSUE TITLE
[WSL2] Difftool doesn't work

### ISSUE THREAD

**Issue by klimentyev** [gitextensions/gitextensions#10299]
### Environment

- GitExtensions version: 4.0.0.15291
- GIT version: 2.38
- OS version: Windows 10 and WSL2 Ubuntu 20.04
- .NET version: 6.0.10

### Issue description

External difftools (meld, winmerge and tortoise) don't work for WSL. difftools aren't opened.

### Steps to reproduce

1. Select 2 commits
2. Compare them by difftool
3. Try to replace win path with wsl path in the Git Extensions settings: https://stackoverflow.com/a/56536372
No reaction. Difftool window isn't opened.

**Comment by gerhardol** [comment]
Difftool use windows definitions, set the tool paths there.
(You do not need to maintain tools in both Windows and WSL).

**Comment by gerhardol** [comment]
This is described in the documentation
https://git-extensions-documentation.readthedocs.io/en/release-4.0/settings.html?highlight=difftool#wsl-git-notes
