### ISSUE TITLE
[WSL2] Difftool is still running for a few minutes without any reaction

### ISSUE THREAD

**Issue by klimentyev** [gitextensions/gitextensions#10300]
### Environment

- GitExtensions version: 4.0.0.15291
- GIT version: 2.38
- OS version: Windows 10 and WSL2 Ubuntu 20.04
- .NET version: 6.0.10

### Issue description

External difftools (meld, winmerge and tortoise) don't work for WSL. difftools aren't opened.

### Steps to reproduce

1. Select 2 commits
2. Compare them by difftool
3. No reaction, the window isn't opened
4. See logs (F12)

```
2022-10-27T21:51:48.7387974+03:00  7748 UI  wsl -d Ubuntu git difftool --gui --find-renames --find-copies --no-prompt --dir-diff "fbd4b5bbfa904b7acb13c0940ea10ba3f5d71c6f" "a5eade438d07a714936fe6b606805aabf038d485" \\wsl$\Ubuntu\home\user\
2022-10-27T21:52:03.0424484+03:00 176 9164 UI 0 wsl -d Ubuntu git ls-files -z --unmerged \\wsl$\Ubuntu\home\user\
2022-10-27T21:52:35.9770957+03:00 288 14016 UI 0 wsl -d Ubuntu git --no-optional-locks -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files \\wsl$\Ubuntu\home\user\
2022-10-27T21:53:36.0680625+03:00 308 18952 UI 0 wsl -d Ubuntu git --no-optional-locks -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files \\wsl$\Ubuntu\home\user\
```

The meld settings in GIt Extensions are correct
`"C:/Program Files/Meld/meld.exe" "$LOCAL" "$REMOTE"`

**Comment by gerhardol** [comment]
What is the difference to the #10299 ? 
Windows --gui tools are used, the WSL paths are translated to windows paths.
wsl git is not involved in launching diff or mergetools

**Comment by klimentyev** [comment]
I want difftool to open from Git Extensions. What should I do for this?

**Comment by gerhardol** [comment]
Configure the tool in Windows, for instance in GE settings.

**Comment by klimentyev** [comment]
I've tried this, but tools don't work. I found a workaround. I configured Windows Meld in WSL and then it is called by wsl git from GE.
https://stackoverflow.com/questions/63810361/how-to-use-meld-as-git-mergetool-difftool-on-wsl2
Nothing works without WSL configuration with symlink and .gitignore.
P.S. I see in my log that wsl git gui is used in GE, not Win.
`wsl -d Ubuntu git difftool --gui`

**Comment by gerhardol** [comment]
Backtracking: The default WSL difftool is used by default in GE.
The tool must support UNC paths. The tools I have tested works.
Example of configuration

```
[diff]
        algorithm = histogram
        guitool = meld
        tool = tortoisediff
[mergetool "tortoisediff"]
        path = /mnt/c/Program Files/TortoiseGit/bin/TortoiseGitMerge.exe
        cmd = \"/mnt/c/Program Files/TortoiseGit/bin/TortoiseGitMerge.exe\" \"$LOCAL\" \"$REMOTE\"
        trustExitCode = true
[mergetool "tortoisemerge"]
        path = /mnt/c/Program Files/TortoiseGit/bin/TortoiseGitMerge.exe
        cmd = \"/mnt/c/Program Files/TortoiseGit/bin/TortoiseGitMerge.exe\" -base:\"$BASE\" -mine:\"$LOCAL\" -theirs:\"$REMOTE\"  -merged:\"$MERGED\"
        trustExitCode = true
[difftool "meld"]
        path = /mnt/c/Program Files (x86)/Meld/meld.exe
        cmd = \"/mnt/c/Program Files (x86)/Meld/meld.exe\" \"$LOCAL\" \"$REMOTE\"
```

If you can use the difftool in Windows, you should be able to use it in WSL
You may have to set safe.directory
git config --global --add safe.directory '%(prefix)///wsl$/Ubuntu-20.04/home/ejgo/gc/gitextensions'

Some tools. BeyondCompare works too

![image](https://user-images.githubusercontent.com/6248932/198410808-a3134f84-baa3-4bd8-8a7e-fdb672be3653.png)

**Comment by klimentyev** [comment]
@gerhardol thanks for your explanation!
I was wrong with paths for Win tools. I used to use Win native ones. I have understood the logic after your answer.
