### ISSUE TITLE
Support decorated HEAD

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#10317]
### Feature description

Since Git 2.38 (guessed), HEAD is decorated as "(HEAD detached at 13e9559ee)" in the output of some commands like
`git branch -a --contains 168acda6a7f6cfb62075557eb3d09b62058d3211`

The internal link to this "branch" in the CommitInfo does not work any longer - to be fixed.
HEAD shall be correctly recognized as itself everywhere.
The parantheses could be removed in the CommitInfo.

![grafik](https://user-images.githubusercontent.com/36601201/199469736-354e688e-8755-4693-988f-0730be6293f7.png)

### Environment

- Git Extensions 33.33.33
- Build cdc4767e25cdabda1cb9959e8b1633dfd24f367b
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
I see the same in WSL Git 2.25

> The parantheses could be removed in the CommitInfo.

Why display this link at all?

To exclude it the link has to be parsed. [core.abbrev](https://git-scm.com/docs/git-config#git-config-coreabbrev) need to be set for the command I assume.

**Comment by mstv** [comment]
> Why display this link at all?

I checkout remote `master` commits directly. I don't want to fiddle around with the local `master` branch, which could cause conflicts between worktrees.
But the information, whether the selected commit is contained in my copy, can be of great interest.

I don't need it as link. It is displayed as link and does not work. So perhaps just add the text without a link. But then we must detect it anyway. Then we can link it to `HEAD` right away.
