### ISSUE TITLE
Git notes aren't always displayed in the commit message

### ISSUE THREAD

**Issue by joepuresdk** [gitextensions/gitextensions#10313]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0

### Issue description

If a commit already has notes, when GitExtensions first displays that commit the commit message doesn't have a "Notes:" section.

If I get FileHistory for a file changed in that commit, "Notes:" is displayed in the "Commit" tab of the history window.
If I add notes to a commit that already has notes, but cancel without editing the existing notes, then notes will be displayed for this commit

### Steps to reproduce

Open a repo with a commit that is known to have notes.
Select that commit in the browser.
Notice that "Notes:" are not displayed in the commit message area.

### Did this work in previous version of GitExtensions?

I don't know.

**Comment by gerhardol** [comment]
I see Notes in FormBrowse by default. (regardless if it is the default commit or any other)
Git Command Log (F12) should show that Notes is fetched when selecting a commit.

Any repo where you see this with a detailed way to reproduce?
