### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ueffel** [gitextensions/gitextensions#10314]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.Blame.BlameControl.SelectedLineChanged(Object sender, SelectedLineEventArgs e)
   at GitUI.Editor.FileViewer.<.ctor>b__53_12(Object sender, SelectedLineEventArgs e)
   at GitUI.Editor.FileViewerInternal.<.ctor>b__31_10(Object s, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   at ICSharpCode.TextEditor.TextArea.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

Run `GitExtensions.exe blame <path>`
Click a line in the dialog

### Did this work in previous version of GitExtensions?

Yes, v3.5.4.

**Comment by mstv** [comment]
Thank you for reporting, @ueffel.

There are alternatives - I hope not only as a workaround:
1. Run `GitExtensions.exe filehistory <path>` and select the `Blame` tab
2. Rather enable the new settings for the integrated blame (which apply to 1.)
  ![image](https://user-images.githubusercontent.com/36601201/199343775-47db3f2b-8b11-40bb-ba1f-a7f35c38ac15.png)
3. Hit `B` on a selected file in the main form
4. Hit `F` on a selected file / folder in order to filter for the file's history in the main form (Hit ``Shift+Cltr+I` for resetting the filter)
  ![image](https://user-images.githubusercontent.com/36601201/199345027-fcd9e1b0-d795-4bcd-9f01-747036bf8d5f.png)

**Comment by mstv** [comment]
Does the fixed version work for you again?
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45248551/artifacts

**Comment by ueffel** [comment]
> Does the bugfixed version work for you again? https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45248551/artifacts

Well the NPE is gone, but the context menu isn't functional 
![image](https://user-images.githubusercontent.com/2247384/199363419-035eb92b-d053-4dd9-9562-ee2bd53fdc4c.png)
The "Blame this revision" and "Blame previous revision" entries are disabled.

-----

I mainly use the standalone blame dialog to start blaming from an IDE with on a specific line.
Is there any way to start blaming in a specific line in the alternatives?

`GitExtensions.exe filehistory <path> <line number>` does not seem to work.

**Comment by mstv** [comment]
> I mainly use the standalone blame dialog to start blaming from an IDE with a specific line. Is there any way to start blaming in a specific line in the alternatives?
> 
> `GitExtensions.exe filehistory <path> <line number>` does not seem to work.

It doesn't. But adding this argument should not be too difficult. (For `blame` this useful argument is not documented.)

---

> Well the NPE is gone, but the context menu isn't functional. The "Blame this revision" and "Blame previous revision" entries are disabled. 

That's the case since v3.2 (#6841).
I would consider this dialog as deprecated. It can be opened using the command line only - as far as I know.

**Comment by gerhardol** [comment]
> It doesn't. But adding this argument should not be too difficult. (For blame this useful argument is not documented.)

This has been added in many GUI operations in 4.0, available for formbrowse from command line?

>  I would consider this dialog as deprecated. It can be opened using the command line only - as far as I know.

I agree. There are too many separate forms with minor usefulness, hard to maintain. (Job openings as testers are available.)
