### ISSUE TITLE
性能问题：最新版gitextensions打开主窗口CPU占用率高

### ISSUE THREAD

**Issue by jianyuyanyu** [gitextensions/gitextensions#10311]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.10
- CPU: Intel i5-9300H 

### Issue description

性能问题：最新版gitextensions打开主窗口时CPU占用率高达17%。

### Steps to reproduce

打开gitextensions即可

### Did this work in previous version of GitExtensions?

无此情况

**Comment by gerhardol** [comment]
Please write the description in English. You probably need some diagnostics like Git Command Log too.

**Comment by RussKie** [comment]
Closing due to lack of the follow up.
