### ISSUE TITLE
Some usability enhancement

### ISSUE THREAD

**Issue by gimmi** [gitextensions/gitextensions#10325]
### Feature description

![image](https://user-images.githubusercontent.com/6589/199920292-a815c53a-d4d7-41b1-8a86-12261249a023.png)
![image](https://user-images.githubusercontent.com/6589/199920304-0c7a7bba-2239-4e48-88aa-fa4b49744adf.png)

### Environment

See images

**Comment by vbjay** [comment]
Open settings.  Search advanced. Find option saying show advanced options.
It's a checkbox.

**Comment by gimmi** [comment]
Thanks!

![image](https://user-images.githubusercontent.com/6589/200038081-2f5fa552-33c6-410b-8856-75a6bd5920f2.png)
