### ISSUE TITLE
In "Manage Remote Repositories" the option for loading a SSH key is hidden

### ISSUE THREAD

**Issue by enricodetoma** [gitextensions/gitextensions#10320]
### Environment

- GitExtensions version: 4.0.0
- GIT version: 2.38.1
- OS version: Windows 11
- .NET version: 6.0.10

### Issue description

I have updated one of my SSH keys, and I would like to change it, like I did before, in the "Remote repositories" window.

As you can see in the image below, the option for loading a different SSH key is hidden:
![image](https://user-images.githubusercontent.com/464156/199755608-3a15fe27-2f02-4b95-9ec7-0d6bb81e5fa9.png)

It appears for a fraction of second when the window opens, then disappears.

### Steps to reproduce

Right click on a `git@` remote repository.
Choose "Manage" from the context menu.

### Did this work in previous version of GitExtensions?

It worked in v3.5

**Comment by enricodetoma** [comment]
It seems that the problem is related to the fact that I can no longer choose PuTTY during installation of v4.0.0.

With 3.5 I choose PuTTY instead of OpenSSH and the options for loading a different key were available.

**Comment by gerhardol** [comment]
PuTTY is no longer bundled with GE, please install PuTTY separately.

**Comment by enricodetoma** [comment]
After installing PuTTY separately and choosing it in the settings, everything works as before.
