### ISSUE TITLE
Inconsistencies of Russian

### ISSUE THREAD

**Issue by Mercury13** [gitextensions/gitextensions#10333]
### Environment

No matter, just L10n problems

### Issue description

Commit → I don’t ever know. I dislike «коммит», and dislike «зафиксировать», but what to do? Strings are really inconsistent and incomplete in v4 (e.g. «коммит» in toolbar, untranslated in tooltip and «зафиксировать» in menu). Maybe «сделать коммит» in menu/tooltip, and «коммит» in toolbar, and leave «коммит» as a noun?
Undo last commit. Present: «отменить последний коммит». I suggest: «откатить последний коммит».
Cherry-pick. Present: «забрать коммит». IDK what to do, but I dislike this string.
Rebase. Present: «перенести». I suggest: «перебазировать».

### Steps to reproduce

No matter, just L10n problem

**Comment by pmiossec** [comment]
Please fix the error: there https://www.transifex.com/git-extensions/dashboard/all_resources/ru/?project=git-extensions-v4#1/?o=perc&d=desc
