### ISSUE TITLE
Cannot select 'Remember First for diff' for a new file

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#10354]
### Environment

- Git Extensions 33.33.33
- Build 4770ee31b9bd4c063f92d720c62bddbae0a6bc2e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

For a new file in a commit, I cannot select the _Open with difftool > Remember First for diff_ option. It can only be selected in a commit where an existing file is being changed.
![Remember first for diff](https://user-images.githubusercontent.com/11479798/200537172-10fe3dda-705e-41f7-b276-a8744d21c789.png)

### Steps to reproduce

Add a new file and commit. Right-click on the new file in the commit and expand the _Open with difftool_ submenu. The _Remember First for diff_ option is disabled.

### Did this work in previous version of GitExtensions?

I don't know.

**Comment by gerhardol** [comment]
Git limitation, you have to specify new files as the second file

**Comment by crypto-rsa** [comment]
Hmm, which git command is the limitation here?

**Comment by gerhardol** [comment]
worktree must be second

```bash
gitextensions (tmp/go9-7)$ cp appveyor.yml dummy.txt
gitextensions (tmp/go9-7)$ echo dummy >> dummy.txt
gitextensions (tmp/go9-7)$ git diff HEAD~5:appveyor.yml dummy.txt
diff --git a/appveyor.yml b/dummy.txt
index 5ccf95ab3..2098c1018 100644
--- a/appveyor.yml
+++ b/dummy.txt
@@ -138,3 +138,4 @@ on_failure:
                 Write-Host $errorMessage -ForegroundColor Red
             }
         }
+dummy
gitextensions (tmp/go9-7)$ git diff dummy.txt HEAD~5:appveyor.yml
fatal: HEAD~5:appveyor.yml: no such path in the working tree.
Use 'git <command> -- <path>...' to specify paths that do not exist locally.
gitextensions (tmp/go9-7)$
```

**Comment by crypto-rsa** [comment]
I guess that's because when the first argument (`dummy.txt`) has no revision prefix and thus is treated as `HEAD`, the second one is treated in the same way. But it works correctly when you use `git diff HEAD:dummy.txt HEAD~5:appveyor.yml`. So I think there is no real limitation from git, we just need to make sure the arguments are in the correct format.

**Comment by gerhardol** [comment]
HEAD:dummy.txt is not worktree but HEAD commit.
With GE artificial commits,worktree would be 1111111:dummy.txt, unfortunately not implemented like that in Git.
Worktree files (without sha) must be second

**Comment by crypto-rsa** [comment]
OK, I get that, but how does that limit the functionality I asked about in the first place? I want to select the _first revision_ of a file as the first argument and compare it to an arbitrary second one (in a different commit or even in the working directory). It's not like the file is newly created and not yet committed.

**Comment by crypto-rsa** [comment]
Perhaps my wording was a bit confusing. I want to select the _first revision_ of a file _in an existing commit_. That is perfectly possible for `git diff` but not allowed in GE.

**Comment by gerhardol** [comment]
> Perhaps my wording was a bit confusing. I want to select the _first revision_ of a file _in an existing commit_. That is perfectly possible for `git diff` but not allowed in GE.

I see now, that should be possible.
These rules are not so simple, the selection can be done "backwards" too.

(I should stop reading messages at breaks and wait until I get home late in the evening.)

**Comment by gerhardol** [comment]
Actually, this is correct: The first commit in the diff is null, the second commit is the new version.
The same as for a diff, the parent is the first commit and the selected the second.

**Comment by crypto-rsa** [comment]
Sorry, I don't quite understand what you are trying to say in your last comment.

**Comment by gerhardol** [comment]
![image](https://user-images.githubusercontent.com/6248932/200801442-5d30997f-4fde-482b-9ff6-1c9fbcafe81d.png)

**Comment by crypto-rsa** [comment]
Hmm, let's take a step back since I don't really understand the problem here.
Consider the following simple repository:
```
git init
echo "File A" > a.txt
git add --all
git commit --all -m "Creating file A"
echo "Another line in file A" >> a.txt
echo "File B" > b.txt
git add --all
git commit --all -m "Creating file B"
echo "Yet another line in A" >> a.txt
echo "Another line in B" >> b.txt
```
Now I can get all sorts of diffs with git:
`git diff HEAD^1:a.txt HEAD:a.txt`
`git diff HEAD^1:a.txt HEAD:b.txt`
`git diff HEAD^1:a.txt a.txt`
`git diff HEAD^1:a.txt b.txt`

The point is, _I can select the first revision of file a.txt as the first item regardless of what I pick as the second one_. I cannot do that in GE because the option is disabled precisely for the first revision of any file.

**Comment by gerhardol** [comment]
In diff tab, each file has a First/A revision (which is null for a new file) and Second/B (also Selected revision).
A revision can be a real commit or index/worktree.

In your examples HEAD^1 is First/A and HEAD/Worktree is Second/B/Selected.
Worktree revisions are not allowed here.
So there is no First/A commit to select for a new file.

The commits are hinted in the menu.

There is supposedly a commit for parent to first in Git, that is undocumented though and would not help you here...

**Comment by crypto-rsa** [comment]
Ooh, I get it now 🤦‍♂️ Both _Remember_ options are for selecting the _first comparison item_ for `diff`. I mistakenly assumed that _Remember Second_ means "remember this as the **second** item to compare" and I was thus confused why I can't select the initial version of a file as the **first** item to compare. Turns out I can - I just need to select _Remember Second for diff_ for that.

**Comment by gerhardol** [comment]
The menu item texts can be changed, if it helps. I do not think that `Remember B for diff`, `Remember second revision for diff` or `Remember B commit for diff` is better.
If there are not better suggestions, this will be closed.

**Comment by crypto-rsa** [comment]
Yeah, none of those seems to be significantly better than the current text. Thanks for your time.
