### ISSUE TITLE
Installer doesn't run after download, with no error message

### ISSUE THREAD

**Issue by ltrzesniewski** [gitextensions/gitextensions#10351]
### Environment

- GitExtensions version: GitExtensions-4.0.0-cba315df5
- GIT version: 2.38.1.windows.1
- OS version: Windows 11 22H2, build 22621.674
- .NET version:
```
.NET SDKs installed:
  3.1.424 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  5.0.405 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.203 [C:\Program Files\dotnet\sdk]
  6.0.305 [C:\Program Files\dotnet\sdk]
  6.0.401 [C:\Program Files\dotnet\sdk]
  7.0.100-rc.2.22477.23 [C:\Program Files\dotnet\sdk]
```

### Issue description

When trying to run GitExtensions-4.0.0-cba315df5.msi, a Windows Store window (or something similar) is briefly displayed, then it closes, and nothing else happens.

I couldn't find anything in the Event Viewer either (in the Application logs). The portable version works fine.

![GitExtensionsSetup](https://user-images.githubusercontent.com/7913492/200353582-ebbfa090-e412-4f2d-add8-08b15eee540d.gif)

I then found out this happens because the downloaded file is blocked:

![image](https://user-images.githubusercontent.com/7913492/200356825-82d24454-f085-4ed9-8bfa-607389fb745e.png)

Unblocking the file makes the installer work fine.

### Steps to reproduce

[Download GitExtensions-4.0.0-cba315df5.msi](https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-4.0.0-cba315df5.msi), then double-click on it. 🙂

### Did this work in previous version of GitExtensions?

I don't think I had this issue on the v3.5 version, but I installed it on Windows 10 in the past.

I tried the v3.5.4 installer on Windows 11 and it has the same problem.

### Diagnostics

I don't suppose that's something actionable (it looks like an issue in Windows), but I'm still reporting this issue just in case. I don't know much about msi installers.

I expected to get a message such as "are you sure you want to open this file" like for exe files, so I didn't immediately think to check the block status, and was surprised by this behavior on the msi file.

**Comment by RussKie** [comment]
Thank you for sharing and the analysis. 
Our msi is signed and is known to Windows SmartScreen. Perhaps there's some sort of a configuration on your workstation (e.g., like a GPO) that blocks downloaded files, or antivirus?

**Comment by RussKie** [comment]
E.g., something like this? https://www.bitwarsoft.com/windows-blocking-downloaded-files.html

**Comment by ltrzesniewski** [comment]
We don't have any GPO that would block downloads, that's just standard Chrome behavior. Windows is supposed to handle those files just fine.

I asked a few colleagues to try the installer, and they don't have this issue. So it seems there's something wrong on my machine. Sorry for the trouble.
