### ISSUE TITLE
Error "Installation directory must be on a local hard drive"

### ISSUE THREAD

**Issue by cschermerhorn** [gitextensions/gitextensions#10359]
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: 2.38.1.windows.1
- OS version: Windows 10 20H2 (19042.2130)
- .NET version: 6.0.10

### Issue description

It is possible that this may be a local issue on my machine, but the error from the GitExtensions installer msi is a bit misleading. Using the default path of "C:\Program Files (x86)\GitExtensions" yields an error that this path is not on a local hard drive. Modifying path (say C:\test\GitExt) yields same error.

Attached log from running msi with /log. I am not sure if this has any useful information since I cannot progress beyond error in image.
[log.log](https://github.com/gitextensions/gitextensions/files/9963789/log.log)

![Screenshot 2022-11-08 122536](https://user-images.githubusercontent.com/5767736/200633974-6d3f6479-7352-4571-8165-19bfaf310f16.png)

### Steps to reproduce

1. Run msi
2. Click next and accept defaults

A workaround is to simply run the installer in silent mode after installing .NET 6 prerequisite.

**Comment by RussKie** [comment]
Thanks for the report and the log. The log doesn't show anything that could shed light on the issue.
Looks like you've found a workaround and was able to get the app installed.
