### ISSUE TITLE
WSL git breaks access to docker desktop volumes

### ISSUE THREAD

**Issue by sabbaman** [gitextensions/gitextensions#10365]
### Environment

- GitExtensions version: 4.0.0
- GIT version: 2.36.1.windows.1
- OS version: Windows 10 Pro 19044
- .NET version: 6.0.402
- Docker version: 4.12.0

### Issue description

I'm using a development container installed directly from Windows, storing the projects files inside a docker volume.
The volumes are usually accessible from the path:
\\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\

When trying to start gitExtensions in that path, the following error appear
![image](https://user-images.githubusercontent.com/22242508/200807099-bc48dab3-153e-4577-bb48-3f46795c8da2.png)

the problem is that the distro docker-desktop-data is not accessible for the user and git is not available there.

Would it be possible to have a flag to disable the WSL git usage?

### Steps to reproduce

- Create a docker volume
- try to access it from gitExtensions through the wsl path (it should be under \\wsl$\docker-desktop-data\version-pack-data\community\docker\volumes\ or \\wsl$\docker-desktop-data\data\docker\volumes\)

### Did this work in previous version of GitExtensions?

Yes, since there was no WSL git usage

**Comment by gerhardol** [comment]
WSL git is always used for \\wsl$ paths, the performance is much better compared to Windows Git.
To use Windows git, map the path to a drive letter or use \\wsl.localhost (in newer Windows builds).

**Comment by sabbaman** [comment]
I would do that, but there is no way of adding the docker-desktop-data path do a drive letter, and I am stuck on windows 10 for now
![image](https://user-images.githubusercontent.com/22242508/200845116-1128ed58-03d5-43b3-b547-5b8bcf95deb4.png)

**Comment by gerhardol** [comment]
> Use with caution, as it will not use wsl git for any path, other wsl distros included.

Configuration of win-git and wsl-git as well as wsl-git to use (if some wrapper is needed) could be quite complex.
This may be considered as an initial implementation.
However, this hidden configuration could be added to the GE documentation.
