### ISSUE TITLE
Commit button displays incorrect number of changes

### ISSUE THREAD

**Issue by brunom** [gitextensions/gitextensions#1036]
Repro steps:
- Edit a file
- The commit button on the main windows reads "Commit (1)" in orange
- Change to another branch
- Commit
- The commit button still reads "Commit (1)"  (Incorrect)
- Restart Git Extensions
- The commit button is now green (Correct)

**Comment by ronbentata** [comment]
i get this issue only now after i'v upgraded git ext

**Comment by vbjay** [comment]
Search the issues next time. This has been explained many times.
