### ISSUE TITLE
v4: keyboard shortcut not working in commit dialog

### ISSUE THREAD

**Issue by chris-findlay** [gitextensions/gitextensions#10362]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.11
- DPI 144dpi (150% scaling)

### Issue description

Alt-L to enable Force-with-lease is not working.  Haven't tried others yet.

### Steps to reproduce

In my case, ^Up to open the Push dialog, then Alt+L to try to enable the force-with-lease checkbox.

Expected: checked checkbox
Actual: "invalid input" system beep; no checked box.

### Did this work in previous version of GitExtensions?

yes, 3.latest

**Comment by RussKie** [comment]
> In my case, ^Up to open the Push dialog, then Alt+L to try to enable the force-with-lease checkbox.

The shortcut is <kbd>ALT + F</kbd>

![image](https://user-images.githubusercontent.com/4403806/200731354-5d6522ce-4497-4507-9ee0-828991da538d.png)

**Comment by chris-findlay** [comment]
ah - dang muscle memory :-p
Thanks.

**Comment by RussKie** [comment]
I think a number of new shortcuts have been added throughout the app, and
some existing have been adjusted to accommodate.

**Comment by chris-findlay** [comment]
Alt-F makes more sense - the reason this used to be L was historical anyway so I prefer how it is now - just got to retrain my fingers slightly (c:

**Comment by chris-findlay** [comment]
I did find this tho:  Commit dialog has 2 things on Alt+T:
![image](https://user-images.githubusercontent.com/40373773/200984996-0f441e2e-bcee-4396-b670-b6762ccaf2af.png)

**Comment by chris-findlay** [comment]
> You can adapt the hotkeys in the regarding settings page. Mnemonics (`ALT+...`) could be tailored in the translation files (`&amp;` in `*.xlf`).

I can fix my current issue using this method, and was finally able to add one to the `Keep Dialog Open` checkbox, unfortunately I can't figure out how to move focus out of the terminal so that Alt-K works for me.  Once I manually click outside it, then it works as expected.

**Comment by mstv** [comment]
> I did find this tho: Commit dialog has 2 things on Alt+T:

Good catch. I will change it to `Stas&h staged changes`.
