### ISSUE TITLE
[NBug] git checkout-index: projects/vs2022/mk_num_tests/mk_num_tes...

### ISSUE THREAD

**Issue by MarekKnapek** [gitextensions/gitextensions#10374]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.37.1.windows.1 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.20348.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

Exit code: 1
Command: C:\Program Files\Git\bin\git.exe
Arguments: checkout-index --index --force -- "libs/mk_num_tests/projects/vs2022/.gitignore" "libs/mk_num_tests/projects/vs2022/mk_num_tests.vcxproj" "libs/mk_num_tests/projects/vs2022/mk_num_tests.vcxproj.filters" "libs/mk_num_tests/projects/vs2022/mk_num_tests.vcxproj.user" "projects/vs2022/mk_amalgam.sln" "projects/vs2022/mk_num_tests/mk_num_tests.cpp"
Working directory: C:\dev\repos\mk_amalgam\

```
GitExtUtils.ExternalOperationException: git checkout-index: projects/vs2022/mk_num_tests/mk_num_tests.cpp is not in the cache
 ---> System.Exception: git checkout-index: projects/vs2022/mk_num_tests/mk_num_tests.cpp is not in the cache
   --- End of inner exception stack trace ---
   at GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.GetBatchOutput(IExecutable executable, ICollection`1 batchArguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.ResetFiles(IReadOnlyList`1 files)
   at GitUI.CommandsDialogs.FormCommit.ResetSoftClick(Object sender, EventArgs e)
   at GitUI.CommandsDialogs.FormCommit.ResetSelectedFiles()
   at GitUI.CommandsDialogs.FormCommit.ExecuteCommand(Int32 cmd)
   at ResourceManager.GitExtensionsFormBase.ProcessHotkey(Keys keyData)
   at GitUI.CommandsDialogs.FormCommit.ProcessHotkey(Keys keyData)
   at ResourceManager.GitExtensionsFormBase.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

I did force branch to this commit. Then I opened commit window. Then I noticed there are some staged changes. Then I selected all staged changes and pressed revert. Then crash happened.

### Steps to reproduce

a

**Comment by mstv** [comment]
It is not a crash of Git Extensions. It is just telling you that Git returned the error "projects/vs2022/mk_num_tests/mk_num_tests.cpp is not in the cache".

**Comment by MarekKnapek** [comment]
Yeah, I know, that it is not a crash. Thank you for your explanation. But
in such a case GitExtensions should handle the return value from git
gracefully and do not display scarry looking crash dump dialogue and exit
itself. Marek.

**Comment by RussKie** [comment]
Thank you for the feedback.

> do not display scarry looking crash dump dialogue and exit
itself.

Could you please clarify these points?

**Comment by MarekKnapek** [comment]
Yes, GitExtensions displayed a (what I call, for lack for better term) crash dump dialogue, similar to Windows' DrWatson window. With message saying something like "A problem occurred, do you want to send a bug report?". I pressed the "yes, agree" button, web browser appeared with new GitHub issue and GitExtensions exited.

Yes, I know I messed with my files outside git / GitExtensions (just with my source files, not with files inside the .git directory), so I'm completely file with these tools reporting a inconsistency in my repo. What I'm not file with is GitExtensions exiting. It should maybe display some message box and then do a refresh display action or something similar, definitely not exiting.

If some file is not in cache and GitExtensions believes it should be there (whatever that means), maybe "just" cancel current operation and issue new one to refresh the state of things.

Overall, this incident is not big problem for me, just small little surprise; in contrast GitExtensions is very useful tool for me, using git without it would be very painful experience for me otherwise.

**Comment by RussKie** [comment]
There was a problem executing a git command, and we showed this error to you. The message contains what command was executed and the exit code. Do you have suggestions as to how it should be reported better?

**Comment by MarekKnapek** [comment]
- Prior executing any command decide
   - Whether failure to execute it is fatal not (program not found, program requires admin privileges for example).
   - Whether successfully executing it but the command returning failure is fatal (process returning negative exit code for example).
 - If it was indeed fatal, display message about bug and possibility to create GitHub issue. If it was not fatal, don't exit GitExtensions, assume command did something but (possibly) not everything what it was asked to do, refresh GUI.

Maybe I was just surprised and scared of that dialogue and I assumed something very bad happened, such as GitExtensions crash. Maybe there is no need to change/enhance current behavior. In future, I will pay more attention to that dialogue.

**Comment by mstv** [comment]
I think you (should) have seen a first popup like in the screenshot (with "your" error). If not, please holler back if you encounter it again.
The `Ignore` button comes first and is focused.
For GE _bugs_, the buttons are swapped.

![grafik](https://user-images.githubusercontent.com/36601201/201422458-505cff66-cf62-4dfc-b49e-2d4eb38c3de6.png)

**Comment by gerhardol** [comment]
Related to #10423
Not sure if the files can be specially handled in this situation.
