### ISSUE TITLE
[NBug] fatal: detected dubious ownership in repository at 'C:/Deve...

### ISSUE THREAD

**Issue by TomWaringIII** [gitextensions/gitextensions#10385]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.10
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: for-each-ref --sort="-taggerdate" --format="%(refname)" refs/tags/
Working directory: C:\Development\cei-setup-api\

```
GitExtUtils.ExternalOperationException: fatal: detected dubious ownership in repository at 'C:/Development/cei-setup-api'
'C:/Development/cei-setup-api' is owned by:
	'S-1-5-21-3928542207-2451314703-3051162723-2838'
but the current user is:
	'S-1-12-1-3209981019-1208057206-2008930448-369376378'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/Development/cei-setup-api
 ---> System.Exception: fatal: detected dubious ownership in repository at 'C:/Development/cei-setup-api'
'C:/Development/cei-setup-api' is owned by:
	'S-1-5-21-3928542207-2451314703-3051162723-2838'
but the current user is:
	'S-1-12-1-3209981019-1208057206-2008930448-369376378'
To add an exception for this directory, call:

	git config --global --add safe.directory C:/Development/cei-setup-api
   --- End of inner exception stack trace ---
   at async Task<string> GitCommands.ExecutableExtensions.GetOutputAsync(IExecutable executable, ArgumentString arguments, byte[] input, Encoding outputEncoding, CommandCache cache, bool stripAnsiEscapeCodes)
   at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
   at IDictionary<string, int> GitUI.CommitInfo.CommitInfo.GetSortedTags()
   at async Task GitUI.CommitInfo.CommitInfo.LoadSortedTagsAsync()
   at async void GitUI.CommitInfo.CommitInfo.RefreshSortedTags()+(?) => { }
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

This repository worked on previous version, no reason to believe it contains dubious ownership. I HAVE changed my login info since initially cloning it.

### Steps to reproduce

I navigated to a repository that I hadn't used in a few weeks. Once recloned I had no issue interacting with it in GitExtensions. I HAVE changed my login since I originally clone the repo a few years ago.

### Did this work in previous version of GitExtensions?

Yep! Had no issue with I think 3.5? Something recent for sure.

**Comment by RussKie** [comment]
Please read the error message, and act accordingly.

**Comment by mstv** [comment]
This message comes from Git since a security update in v2.35 (see also #9954).
