### ISSUE TITLE
Commit message is not displayed in the specified font

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#10382]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Commit message is not displayed in the specified font in commit message editor.

### Steps to reproduce

1. Press the Commit button on the toolbar.
1. Type something in the commit message box.

### Did this work in previous version of GitExtensions?

Yes, v3.5.4.

**Comment by shirayuki** [comment]
The existing commit message appears in the specified font, but newly entered text is not.
![image](https://user-images.githubusercontent.com/18039/201345005-be5d59ac-7580-46c2-9b51-6dabdea28194.png)

**Comment by mstv** [comment]
Works for me 🤔

**Comment by shirayuki** [comment]
Font settings.
ＭＳ ゴシック(MS Gothic)
![image](https://user-images.githubusercontent.com/18039/201436140-d038ac03-937f-4325-8d77-60bbcf467f9c.png)

**Comment by mstv** [comment]
I cannot reproduce it with "MS Gothic" neither.
I am not sure whether I can see the issue in your initial screenshot.
Could you demonstrate it with a larger font size?

**Comment by shirayuki** [comment]
**Steps to reproduce**
1. Reword commit
2. Click "Modify the commit message" button
3. Add some text to the commit message

![1](https://user-images.githubusercontent.com/18039/201516272-4e09dec1-f59f-4d21-a589-f33cc21aca20.png)
![30](https://user-images.githubusercontent.com/18039/201516307-c2f37ec8-1be1-4717-b5f0-4722615e783c.png)
![220](https://user-images.githubusercontent.com/18039/201516348-4c049391-3bf8-4668-bdf4-51fee4dc4587.png)

**Comment by mstv** [comment]
Might be a Windows-11-only issue. Cannot reproduce with Windows 10 (10.0.19045.0) and .NET 6.0.10.

---

Just for clarification: "Reword commit" has a different meaning in GE:

![grafik](https://user-images.githubusercontent.com/36601201/201518560-b412b016-ccbd-4c12-b39c-064433367620.png)

**Comment by shirayuki** [comment]
I can reproduce with Windows 10 as well.
By pasting the commit message into Wordpad, I identified the font as Calibri.
![image](https://user-images.githubusercontent.com/18039/201648932-22e70b0d-b8b3-4a33-97e2-d6cef6d4631c.png)

**Comment by mstv** [comment]
Do you type the message? Or do you copy & paste it from another program, which might add formatting to the clipboard.

Might it be related to switching input methods (which I don't know anything about).

**Comment by shirayuki** [comment]
I typed on the keyboard.
Input methods are not used to input Latin text. Input methods do not change formatting of text.

**Comment by mstv** [comment]
may be related to https://github.com/dotnet/winforms/issues/8902 "RichTextbox font family not applied to new text"

**Comment by Funbit** [comment]
This issue drives me crazy :( 
I hope this issue won't be closed without a fix :(

![スクリーンショット 2024-09-04 185106](https://github.com/user-attachments/assets/63c0d810-4aa8-47e3-8336-a62501414d90)
![スクリーンショット 2024-09-04 185707](https://github.com/user-attachments/assets/fe3dfd5c-5206-42d6-87cf-ace390118831)

**Comment by hinst** [comment]
The bug still exists in the latest release version of Git Extensions 6.0.5.18375
