### ISSUE TITLE
Getting Error: The installed version is not upgradeable to 4.0.0.15569

### ISSUE THREAD

**Issue by feslerj** [gitextensions/gitextensions#10383]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.36.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0

### Issue description

It appears that version 3.5.4 is the last major version released, so I don't think this is a legitimate error. Otherwise I'd like to know what the upgrade path is supposed to be. There is a possibility that it may be related to how my company handles new binary executables, but it is not failing in the typical way that would allow me to report it for scan and allow-listing.

### Steps to reproduce

1. Open Git Extensions
2. Help
3. Check for updates
4. Update Now

Also

1. Download gitextensions 4.0.0.15569
2. Execute

### Did this work in previous version of GitExtensions?

This is the first time I've had a problem upgrading GitExtensions.

**Comment by mstv** [comment]
You could download the installer or the portable archive manually from https://github.com/gitextensions/gitextensions/releases/tag/v4.
A screenshot of the error might help.

**Comment by feslerj** [comment]
I did download and I tried running GitExtensions-4.0.0-cba315df5.msi directly and got the same error.

![image](https://user-images.githubusercontent.com/4680182/201417603-4a0ab17f-0264-4a7d-b099-4d22448825fc.png)
![image](https://user-images.githubusercontent.com/4680182/201417686-7949bc5d-ce4a-42ac-9c38-7ce2677c6157.png)

**Comment by gerhardol** [comment]
Uninstall of 3.5.4 is required before installing 4.0. User settings are preserved.

**Comment by feslerj** [comment]
Thank you for letting me know the user settings are preserved.

**Comment by rgl** [comment]
@gerhardol, may I ask why doesn't the setup handle that internally/automatically? even more so, because the settings are preserved.

**Comment by gerhardol** [comment]
The migration to .NET6 required a lot of changes to the applicationfiles, so an update was not considered safe. (It was not me that did the migration, I do not have any details.)
The settings format was not changed.

**Comment by kamilvlcek** [comment]
I have the latest version before 4.0 installed (3.5.4.12724), but still, when trying to upgrade to 4.0.0, I get the message, that my version is not upgradeable. 
![obrazek](https://user-images.githubusercontent.com/11502219/210219666-f4009159-0563-46e4-9829-dd38e300f091.png)


My current version:
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
https://github.com/gitextensions/gitextensions/issues/10383#issuecomment-1312134517

> Uninstall of 3.5.4 is required before installing 4.0. User settings are preserved.
