### ISSUE TITLE
Push tags need list order by desc

### ISSUE THREAD

**Issue by godcong** [gitextensions/gitextensions#10399]
### Feature description

Generally speaking, new tags from users should be unuploaded. This part is more likely to be used.
Older tags have a lower probability of being used with Push tags.
It is better to put the higher probability tags at the top. :)

### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
![Screenshot_20221114-011029_Chrome.jpg](https://user-images.githubusercontent.com/3629489/201588687-901d2601-5a19-4f72-8107-35b67599c570.jpg)

Use hemp about to generate the version info.

**Comment by godcong** [comment]
@vbjay thanks. fixed it.

**Comment by RussKie** [comment]
@godcong could you please be more specific in your ask. What exactly you're asking for? Steps to reproduce? Screenshots? Logs?

**Comment by godcong** [comment]
The current order of arrangement is this:
![image](https://user-images.githubusercontent.com/2727298/201832778-5c025404-6676-46ae-b112-39716af9d498.png)

It would be better to sort the experience in this way
![image](https://user-images.githubusercontent.com/2727298/201833247-e934d5c9-fdf5-428e-8262-d48baf7ca8f3.png)

Found a small bug... :)
v0.15.1 is my latest version number, he is the largest.
But it is neither at the bottom nor at the top.

**Comment by vbjay** [comment]
It's sorted alphabetically. Since tags are character data. You can name your tag 'theBigOne' so it is not a version number at all. We do tag with v#.# and other similar formats all the time but it's not required. I could see the sort order being able to be switched from alphabetically to author date of commit that tte tag references. I think a sort config in settings and a switching ui to allow the user to pick which way to see it could be useful.

**Comment by godcong** [comment]
@vbjay It would be great if the user could customize it.

**Comment by RussKie** [comment]
Sorting is working as intended
![image](https://user-images.githubusercontent.com/4403806/201892308-c43c2b05-a666-4770-9c54-e038b84164d5.png)


![image](https://user-images.githubusercontent.com/4403806/201893020-b87610fd-c9d1-477a-aae4-aeba344ccca6.png)
