### ISSUE TITLE
Disable push when rebasing

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#10405]
### Feature description

When rebasing, "push" / "Commit & push" should be disabled.

Now, git fails with:

```
"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "origin" (no branch):refs/heads/(no branch)
error: src refspec (no does not match any
error: src refspec branch) does not match any
error: src refspec branch) does not match any
error: failed to push some refs to 'https://-----------------.git'
Done

Press Enter or Esc to exit...
```

Expected : Push button should be disabled everywhere in the app

![image](https://user-images.githubusercontent.com/9248729/201927068-dd1a66de-ddaa-444f-8b34-be328fabdaab.png)

### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
If there is no branch checked out, push should be disabled.
`(no branch)` is intended for display only, should not be used in commands.

**Comment by bansan85** [comment]
I just tried to commit&push without a branch checked out (and while not rebasing). Git Extensions opened a messagebox and asked to what to do : "Checkout branch", "Create branch" or "Continue". I think this popup should be kept (except that "Continue" should be "Cancel").

**Comment by RussKie** [comment]
> I just tried to commit&push without a branch checked out (and while not rebasing). Git Extensions opened a messagebox and asked to what to do : "Checkout branch", "Create branch" or "Continue". I think this popup should be kept (except that "Continue" should be "Cancel").

This sounds unrelated, and should be raised as independent issue. 
That said, a PR with a fix would be more welcome.

**Comment by gerhardol** [comment]
> > I just tried to commit&push without a branch checked out (and while not rebasing). Git Extensions opened a messagebox and asked to what to do : "Checkout branch", "Create branch" or "Continue". I think this popup should be kept (except that "Continue" should be "Cancel").
> 
> This sounds unrelated, and should be raised as independent issue. That said, a PR with a fix would be more welcome.

It is the same issue: If no branch is checked out, push should not be attempted.
The existing messagebox should be applied in some more situations.
In FormCommit, it appears at Commit&push but not Push right now.

If no checkout, the name is quite often changed to `(no branch)`, Form push should not be started if the current branch is called that.
![image](https://user-images.githubusercontent.com/6248932/210013636-0972b065-f47b-4893-b69e-e0019f45d42d.png)
