### ISSUE TITLE
Always shows "Derives from no tag" in commit summary

### ISSUE THREAD

**Issue by pmme** [gitextensions/gitextensions#10414]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

The bottom line of the commit summary always displays "Derives from no tag" when I know that there is a tag in the parents of the commit.
My tags are not signed, but that is not a requirement for the "Derives from tag" feature.

### Steps to reproduce

Select a commit in the log that has a tag in its first-parent history and view the commit details for that chosen commit.
The last line of the commit details should show the derivation from the most recent tag along with the number of commits since that tag.

### Did this work in previous version of GitExtensions?

Yes, in GitExtensions version 3.5.4.12724 I see text like `Derives from tag: 8.9.2.1 + 35 commits` where `8.9.2.1` is a valid tag in my repository.

### Diagnostics

Git log shows that it is running `git describe --tags --first-parent --abbrev=40`.
The output from that in Git command line in my repository is `8.9.2.1-35-gfb9c7614c36cfc3773e780249d7f7adbd5f0d1ba`.
String parsing in https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitDescribeProvider.cs looks to be still correct for that output from Git, so I don't see any immediate reason for the problem.

**Comment by vbjay** [comment]
Instead of typing the version info use help about.

![image](https://user-images.githubusercontent.com/3629489/202329657-3ea52519-66ff-420d-99ab-98976a391bc1.png)

**Comment by pmme** [comment]
![image](https://user-images.githubusercontent.com/1947040/202330905-33254c8b-46a3-4721-88bb-63e05945b2ba.png)

**Comment by vbjay** [comment]
Click the copy button and paste over your description.  

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)


Make sense now

**Comment by pmme** [comment]
Fixed the version info in the original report now. Thanks.

**Comment by vbjay** [comment]
Ok 

Run the following

```
git describe --tags --first-parent --abbrev=40 1>std 2>error
cat std
cat errror
```
and reply with the results.  Curious if it is doing some weir d output in the other stream.

**Comment by pmme** [comment]
```
paul@dev09 MINGW64 /d/EDS/Paul/Code/EDS (PowerMissingFromOnDrawingCables)
$ git describe --tags --first-parent --abbrev=40 1>std 2>error

paul@dev09 MINGW64 /d/EDS/Paul/Code/EDS (PowerMissingFromOnDrawingCables)
$ cat std
8.9.2.1-35-gfb9c7614c36cfc3773e780249d7f7adbd5f0d1ba

paul@dev09 MINGW64 /d/EDS/Paul/Code/EDS (PowerMissingFromOnDrawingCables)
$ cat error

paul@dev09 MINGW64 /d/EDS/Paul/Code/EDS (PowerMissingFromOnDrawingCables)
$
```

**Comment by vbjay** [comment]
Ok debugged. This is a good first bug fix.  Do you want to to fix?

https://github.com/gitextensions/gitextensions/blob/6f9591c6ad0d0d4ab6970fa1c837560a9e743e3c/GitCommands/Git/GitModule.cs#L4187-L4189

I would add a test that makes sure this doesn't happen again.

**Comment by pmme** [comment]
If you had not seen, the "Derives from tag" feature is my own contribution from a few years ago: #4837 to satisfy an old feature request issue that had languished. Now that it's there I find I refer to that info often, so I'm glad I added it.
If it's not time-critical to anyone to get fixed, I'm happy to work on it hopefully this weekend.
