### ISSUE TITLE
GitExtensions to control a remote Linux files from Windows

### ISSUE THREAD

**Issue by ronenw7** [gitextensions/gitextensions#10416]
### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

GitExtensions running on a Windows platform failed to control remote files located on a Linux machine.

### Steps to reproduce

Press Open repository and point on a Linux directory.
The application get failed to open the directory tree and yelled about merge conflicts.
![image](https://user-images.githubusercontent.com/32730648/202436120-c6396286-255c-4f81-956a-483edcb765d6.png)

**Comment by gerhardol** [comment]
It seems like you are using 3.5, with 4.0 you will get a popup with a Git command that fails.
This is likely a permission issue, explained in the Git message.

**Comment by ronenw7** [comment]
Thanks.
Can you pls elaborate on "permission issue"? is it related to a different file systems (windows vs linux) that requires a Samba protocol or alike?

**Comment by gerhardol** [comment]
See #10349
You should get a popup with a failed Git command. Check Git Command Log.
Also see https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1098375030

**Comment by ronenw7** [comment]
Thanks again.
It seems that "**git config --global --add safe.directory "*"**" from [https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1145116791](url) solved the security problem as you mentioned before.
