### ISSUE TITLE
Github merging Pull requests

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#10439]
> > I tend to rebase and merge this PR in order to keep the commits (although some are tiny). This merge strategy has the disadvantage that no reference to this PR is added.

> I can rebase and force push if you want.
> Should be able to just merge now. @mstv

There is no need to manually rebase. This can be done using ![grafik](https://user-images.githubusercontent.com/36601201/203432608-39710a4e-b348-40f6-8e13-b2acd3971507.png).

We want to avoid unnecessary merge commits. I want to discuss
- whether we should keep such commits
- how to merge including a reference to the PR
_Originally posted by @mstv in https://github.com/gitextensions/gitextensions/issues/10389#issuecomment-1324312459_
___

One detractor to the rebase is that I sign all my commits.  With you doing a rebase merge on website my signing was removed.  If you had merged locally and done a fast forward merge in master, Github would have detected the merge and my commits would still be signed.  

See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github  which says:

 
When using the Rebase and Merge option on a pull request, it's important to note that the commits in the head branch are added to the base branch without commit signature verification. When you use this option, GitHub creates a modified commit, using the data and content of the original commit. This means that GitHub didn't truly create this commit, and can't therefore sign it as a generic system user. GitHub doesn't have access to the committer's private signing keys, so it can't sign the commit on the user's behalf.

A workaround for this is to rebase and merge locally, and then push the changes to the pull request's base branch.

**Comment by gerhardol** [comment]
The core problem IMHO is that GitHub does not support fast forward merges. It makes updates to submodules cumbersome too.
There is a GH action though:
https://github.com/marketplace/actions/fast-forward-pr

**Comment by vbjay** [comment]
It does if you do it locally and push.  If I pull a pr branch and do a ff merge into master and then push, github will close pr.  I understand the issues.

1. Multiple prs and having to ff merge would mean havng to get authors to rebase again.  
2. Pulling locally and merging is a pain.

I get it.  I just wanted to expose the problems.

**Comment by vbjay** [comment]
Wish there was a way to provide private key to github that would only be used in pull request rebases.  But once given the trust can't be 100%.

**Comment by vbjay** [comment]
One thought is I could set up a github only private key that github would use and it would sign with that.  It would be a different key than what I use.  I could generate it and give github the key to still say my email address.  I could then trust that key with my key I use.  So it would be my github vbjay key.  So on a rebase it would still be signed by me sort of.  Just my github me and not my real personal key.  I just wish there was a way to trust the key once given away to a website. How do iI know github didn't leak it and someone is using my github private key?  I don't.

**Comment by gerhardol** [comment]
If /fastforward GH action works, request that and add a PR change for the PR template.
Personally, signing is not important as I believe the community has the responsibility anyway for the quality. If an issue occurs, those that has not reviewed has more responsibility than those that have reviewed and authored. But there are other communities and if you want to remove the uncertainity that someone has changed your commit, fine for me.

The core limitation is that GH lacks --fast-forward.

(I assume that squash-merge is removing the signing too and I do not consider merge commits that are not rebased not to be an alternative.)

**Comment by vbjay** [comment]
Yep. Pretty much sums it up.  Not too concerned.  Just wanted to point out
the issue. I'll close since I just wanted to hace this discussion and see
what needed to be done. Thanks.
