### ISSUE TITLE
4.0.0 setup fails requiring PS even though it already exists

### ISSUE THREAD

**Issue by jovanz-getbgd** [gitextensions/gitextensions#10437]
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: 2.37.1.windows.1
- OS version: Microsoft Windows 11 Pro 10.0.22621 Build 22621
- .NET version: SDK 6.0.403

### Issue description

When I try to install the latest GitExtensions version I'm getting the following error:
![image](https://user-images.githubusercontent.com/109612636/203335374-86b4d2f8-2522-4a58-abea-b043d59ef555.png)

However, PS is installed on my environment:
![image](https://user-images.githubusercontent.com/109612636/203335773-0e916816-e44e-4570-8627-3eddbf7d198d.png)

### Steps to reproduce

Run 4.0.0.15569 setup.

### Did this work in previous version of GitExtensions?

Yes, installing did work previously in 3.x

**Comment by RussKie** [comment]
This looks similar to https://github.com/gitextensions/gitextensions/issues/7524.

Try running the installer from command prompt with [log options](https://learn.microsoft.com/windows/win32/msi/command-line-options) and see if you can get any insights from it: `msiexec /i "GitExtensions-xyz.msi" /L*V "C:\log\install.log"`

**Comment by jovanz-getbgd** [comment]
Running the installer from an elevated terminal using the msiexec exe successfully completed the installation.
