### ISSUE TITLE
Exception error message on Dashboard

### ISSUE THREAD

**Issue by jirih** [gitextensions/gitextensions#10448]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.11

### Issue description

When Dashboard is open (after the start of the application, or after closing a current repo), Exception error message appears.
![image](https://user-images.githubusercontent.com/3437851/203789762-1c52695a-4203-4ef0-b639-03c6f4c288b2.png)

### Steps to reproduce

Open the dashboard.

I do not know if any specific settings for this is needed. I do not think I have set anything strange.

### Did this work in previous version of GitExtensions?

Yes, the last of branch 3.

**Comment by pmiossec** [comment]
Is it possible that one of the folder/repo you opened in the past (and so displayed in the dashboard), even if the folder still exists, is no more a git repository (`.git` folder deleted) or maybe is empty?

**Comment by VStark** [comment]
Hi Guys,
I have exactly same issue and it is really enjoying.
I can help you with the investigation, what do you need to know?
