### ISSUE TITLE
Checkout branch shortcut not working

### ISSUE THREAD

**Issue by zippermachine** [gitextensions/gitextensions#10465]
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: 2.38.1.windows.1
- OS version: Microsoft Windows NT 10.0.19045.0
- .NET version: .NET 6.0.11

### Issue description

As of version 4.0.0, the keyboard shortcut [Ctrl+.] for "checkout branch" stopped working.

### Steps to reproduce

Press [Ctrl+.], checkout branch dialog not displayed.

### Did this work in previous version of GitExtensions?

YES, in version 3 this shortcut works.

**Comment by mstv** [comment]
The default hotkey for `CheckoutBranch` is `Ctrl+Decimal` (the decimal key of the numeric keypad).
You could assign e.g. `Ctrl+OemPeriod` in the settings page `Hotkeys` for `Browse`.
