### ISSUE TITLE
File History of repo root items in \\wsl$ works, but fails for non-root items

### ISSUE THREAD

**Issue by pedrolamas** [gitextensions/gitextensions#10479]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22623.0
- .NET 6.0.11
- DPI 192dpi (200% scaling)

## File history working with `\\wsl.localhost`

![Animation](https://user-images.githubusercontent.com/85504/204907156-2e22b232-655f-40c9-991a-b45ff67f3639.gif)

## File history failing with `\\wsl$`

![Animation2](https://user-images.githubusercontent.com/85504/204907171-5ab03db7-505e-4112-a500-f59576013ef3.gif)

### Steps to reproduce

Just open a WSL repo file `\\wsl$` (so that the git in WSL is used)

**Comment by gerhardol** [comment]
It seems you have found the wsl Git notes:
https://git-extensions-documentation.readthedocs.io/en/release-4.0/settings.html?highlight=difftool#wsl-git-notes
Normally it is the other way around since win-git will require security configuration,

History for \\wsl$ works for me.

Git Command Log?
WSL Git version?

**Comment by pedrolamas** [comment]
> It seems you have found the wsl Git notes: [git-extensions-documentation.readthedocs.io/en/release-4.0/settings.html?highlight=difftool#wsl-git-notes](https://git-extensions-documentation.readthedocs.io/en/release-4.0/settings.html?highlight=difftool#wsl-git-notes) Normally it is the other way around since win-git will require security configuration,

I actually saw it on [v4 release notes here on github](https://github.com/gitextensions/gitextensions/releases/tag/v4)!

## Git Command Log:

![image](https://user-images.githubusercontent.com/85504/204925909-c5c796d7-77fb-4511-be92-a6f81fb0660d.png)

## Git Command Log from the new window (opened from History menu item):

![image](https://user-images.githubusercontent.com/85504/204925776-bc1aa388-2182-498a-9812-2e59b32ba73c.png)

## WSL Git Version

git version 2.25.1

**Comment by pedrolamas** [comment]
Seems the issue was with either my WSL git client being old, or the fact I was still using Ubuntu 20... I just upgraded my instance from 20 to Ubuntu 22 (which has git version 2.34.1) and now it works!

So closing as such!

**Comment by gerhardol** [comment]
Ubuntu 20.04 works for me on at least two separate PCs, both with Git 2.25
So the issue was something else.
All commands in the logs are successful too.

**Comment by pedrolamas** [comment]
Thanks for following up on this!

I'm not sure what was causing this, but I will keep an eye out and if it happens again, I'll try to get more information and reopen this ticket.

**Comment by pedrolamas** [comment]
Reopening this issue as I have just noticed it happening again!

However, I do have some new information... I think this only happened with non-root items!

If I ask for history for an item on the root of the repo, it works fine:

![image](https://user-images.githubusercontent.com/85504/222745496-888c223d-6694-4d6e-83a2-ad4afdee9cff.png)

but I point to an item under a subfolder, it will return a blank list instead, and I did notice this:

![image](https://user-images.githubusercontent.com/85504/222745710-3adae263-51b6-4512-a956-55bedd277fa2.png)

As you can see on the above picture, it is using `\` (backslash) as path separator, which I'd expect it not to work as I am asking this to WSL!

**Comment by pedrolamas** [comment]
This is the Gitex diff window startup params:

![image](https://user-images.githubusercontent.com/85504/222746424-83c43e5f-3654-4be6-bcf7-4bac47b700bf.png)

Seems to me we have found the culprit!
