### ISSUE TITLE
[NBug] Could not load type 'GitCommands.ArgumentString' from assem...

### ISSUE THREAD

**Issue by BBzzz** [gitextensions/gitextensions#10476]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.TypeLoadException: Could not load type 'GitCommands.ArgumentString' from assembly 'GitExtUtils, Version=4.0.0.15569, Culture=neutral, PublicKeyToken=null'.
   at GitExtensions.GerritPlugin.FormGerritPublish.PublishChange(IWin32Window owner)
   at GitExtensions.GerritPlugin.FormGerritPublish.PublishClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

Wanted to publish my review and this error occured
Pageant is running...

### Steps to reproduce

I installed the new Git Extensions 4.0 and the new git 2.38, (after removing the previously existing ones) and after that, I can't publish any new content to my review

**Comment by RussKie** [comment]
It appears you're using a 3rd party plugin. Please make sure it's updated
and is compatible with the latest version of the app.

**Comment by BBzzz** [comment]
Sorry, which plugin are you talking about?
The problem is not that: "PublicKeyToken=null'?

**Comment by pmiossec** [comment]
> Sorry, which plugin are you talking about?

The Gerrit feature is provided through  an external plugin and should be updated to v2.0.1 (using the plugin manager)
See https://github.com/gitextensions/GitExtensions.GerritPlugin/releases/tag/v2.0.1

**Comment by RussKie** [comment]
I stand corrected (thank you @pmiossec) - it's "our" plugin, but it's no longer maintained by the core team nor bundled with the app.

**Comment by BBzzz** [comment]
Unfortunately, it doesn't solve my problem @pmiossec , @RussKie ...
My GerritPlugin has already v2.0.1 version... :(

**Comment by pmiossec** [comment]
I don't know if @lekhmanrus can help on that?
@lekhmanrus Are you still using the plugin? Does it works well for you with the last version of GitExtensions released?
Maybe the plugin need to be updated to use the v0.3 of GitExtensions.Extensibility? https://www.nuget.org/packages/GitExtensions.Extensibility

**Comment by BBzzz** [comment]
Sorry, my bad: the GitExtensions.GerritPlugin helped! 
Thank you very much!

**Comment by lekhmanrus** [comment]
@pmiossec, yep we use Git Extensions v4 and Gerrit Plugin v2.0.1 in our company. Works well. 🙂
I'll try to fit some updates for the Gerrit plugin into my schedule.

**Comment by pmiossec** [comment]
> I'll try to fit some updates for the Gerrit plugin into my schedule.

No hurry. It was just because the first answer of @BBzzz said that he still has problem. But if I understand well, it's working now...
So the reason was **NOT** that the v2.0.1 is not compatible with v4..0 ...
