### ISSUE TITLE
high cpu usage

### ISSUE THREAD

**Issue by zhcy2050** [gitextensions/gitextensions#10489]
### Environment

- GitExtensions version: 4.0.0
- GIT version: 2.38.1
- OS version: windows 10 2H22
- .NET version: 6.0.403

### Issue description

high cpu usage at the recent repository page.

### Steps to reproduce

open git extensions and stay at the recent repository page.

### Did this work in previous version of GitExtensions?

3.5.xx has no this problem.

**Comment by mstv** [comment]
Fixed with #10455
