### ISSUE TITLE
`GitStatusMonitor` causes blank repos, if repo is not good

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#10488]
### Environment

- Git Extensions 33.33.33
- Build b764efbb05ec192bcd9f96f2d79a9f50d269a8ef (Dirty)
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Opening a repo that is not in a good state (e.g., dubious ownership or invalid git repo) _before_ a good repo is opened with very high degree of probability will result in blank repo, as reported https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1330556083

If the git command invoked here
https://github.com/gitextensions/gitextensions/blob/e8ef6e58b3ecfb1bb6dddcc01dcbb5c7b9af760d/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs#L428

...fails, it gets swallowed here:
https://github.com/gitextensions/gitextensions/blob/e8ef6e58b3ecfb1bb6dddcc01dcbb5c7b9af760d/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs#L440-L453

I kind of suspect the status monitor is turned on, and when switching repos it gets disabled. This could explain why it works correctly _after_ a user opened a good repo and then switches to a bad repo....
. . . 

I've tried adding a new catch clause, but it doesn't really improve the user experience:
```diff
diff --git a/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs b/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
index 23c87f36e..b82529903 100644
--- a/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
+++ b/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
@@ -437,6 +439,11 @@ private void Update()
                                 GitWorkingDirectoryStatusChanged?.Invoke(this, new GitWorkingDirectoryStatusEventArgs(changedFiles));
                             }
                         }
+                        catch (ExternalOperationException ex)
+                        {
+                            await ThreadHelper.JoinableTaskFactory.SwitchToMainThreadAsync();
+                            throw;
+                        }
                         catch
                         {
                             try
@@ -475,6 +482,7 @@ private void Update()
                                 }
                             }
                         }
```
I've done only a high-level investigation, and it appears there are competing git commands, and the first fails with "fatal" error, then this exception gets trumped by another exception with a blank message.

### Steps to reproduce

1. I have two broken repos - the first has .git folder but nothing else in it, and another has dubious ownership issue
2. start the app in the dashboard mode
3. open the the first repo - observe no errors and blank view
4. switch to the second repo and observe no errors and the same blank view

**Comment by RussKie** [comment]
@gerhardol could you please look into this one?

**Comment by mstv** [comment]
reproducible with
`GitExtensions.exe browse \\192.168.x.y\nas\testrepo\`
for a now-empty repo on a network share
Git Command Log with callstacks: [dubious_ownership.txt](https://github.com/gitextensions/gitextensions/files/10238938/dubious_ownership.txt)

**Comment by gerhardol** [comment]
GitStatusMonitor should be considered as a separate entity. Failures should not propagate and not be directly displayed to the user. The status in RevGrid for artificial commits should be "grey" after opening the repo as no status is updating.
Errors in GitStatusMonitor was previously thrown, which for instance caused crashes when users updated Git when GE was running.

The propagation of the error when loading is the correct solution.
Result code from the load is not updated in GitCommandLog, so this is easy to miss
