### ISSUE TITLE
SSH Agent authorisation no more works

### ISSUE THREAD

**Issue by MichaelEFlip** [gitextensions/gitextensions#10481]
### Environment

- GitExtensions version: 4.0.0.15569
- GIT version: 2.38.1.windows.1
- OS version: Windows 10.0.19044.0 / 21H2 Build 19044.2251
- .NET version: 6.0.10

### Issue description

I normally authenticate to git repos via ssh public key using an ssh agent (keeagent via keepass or pagent).
This seems to work no more directly from git extensions.

Git extensions asks for a password instead using the public key.

If I open Git bash from the git extensions menu and do a git pull manually it works properly.

To use the ssh agent the environment variable SSH_AUTH_SOCK="C:\\tmp\\cygwin-ssh.socket" is set via ~/.bashrc 
I have the feeling that the .bashrc file is not used when directly using from git extensions.

### Steps to reproduce

- Clone repository via SSH using SSH agent

### Did this work in previous version of GitExtensions?

yes

**Comment by MichaelEFlip** [comment]
Setting openssh path manually seems to be a workaround: #9646

**Comment by RussKie** [comment]
Great to hear you found a workaround.
