### ISSUE TITLE
View is not refreshed after periodic backgound fetch

### ISSUE THREAD

**Issue by Schweigst** [gitextensions/gitextensions#10491]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

I activated periodic background fetch every 120 seconds and also turned "Refresh view after fetch" on
It seems that the fetch is done in the background, but the view is not refreshed. After pressing F5, the view is updated with data that was fetched in the beckground.

### Steps to reproduce

Setup periodic beckground fetch:
Arguments of git command to rund: fetch --all
Fetch every (seconds): 120
Refresh view after fetch: On
Fetch all submodules: Off

Make sure that there is a change on the remote repository.
Wait for more than 120 seconds (e.g. 240s) to be sure that the background fetch happened.
Press F5, the grid now gets refreshed with the changes that had been fechted but not already displayed.

### Did this work in previous version of GitExtensions?

Worked as expected with 3.5.4.12724

### Diagnostics

![Git log](https://user-images.githubusercontent.com/44213946/205604190-0efa97ca-c798-47dc-8f45-4182e8002e57.png)

**Comment by mstv** [comment]
The plugins use the same `GitUICommands` instance as FormBrowse.
`F5` triggers `UICommands_PostRepositoryChanged`. The plugin does the same.
Since `git fetch --all` has succeeded (exit code 0), it should work (looking at the code).
To be debugged.
