### ISSUE TITLE
UI tests fail in JetBrains Rider

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#10492]
### Environment

- Git Extensions 33.33.33
- Build c88721e837772845907f7719c7677c7a3019e23d (Dirty)
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.11
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

### Issue description

Unit and integration tests for UI which uses theming fails in JetBrains Rider IDE. The reason is a failed assertion in `GetGitExtensionsFullPath` which expects only certain executable paths. Among them is the Visual Studio test host (`testhost.exe` and `testhost.x86.exe`) but not the Rider one (`ReSharperTestRunner.exe`). Is there a reason to restrict the executable paths like that? And if so, could we add the Rider test runner path?
I should note that there are still tests which are failing in Rider for some unknown reason but passing in Visual Studio - but the path restriction seems artificial to me.

### Steps to reproduce

Open the GE solution in JetBrains Rider, build and run unit tests.

### Did this work in previous version of GitExtensions?

I don't think so.

**Comment by pmiossec** [comment]
> Is there a reason to restrict the executable paths like that? 

Thanks for starting the discussion. I don't really get the idea behind the restriction 

> And if so, could we add the Rider test runner path?

I have a commit locally that add it (and was about to push it one or another). So I'm for adding it....

**Comment by pmiossec** [comment]
Closing: Fixed by #10515
