### ISSUE TITLE
Blame showing in File Tree tab

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#10511]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

As part of the change for "Show file history in the main window", blame info now appears along with file contents in the File Tree tab. I have this option turned off, because I strongly prefer the old history window. (I've seen comments indicating that this window might be deprecated; I hope that's not true.) However, blame info still displays in the File Tree tab in the main Browse window.

I would prefer that blame info never appear in the file tree in the main Browse window, but I definitely think it shouldn't be there if "Show file history in main window" is unchecked, since the intent of that is to preserve the v3 UI. When I click on an item in the file tree, I'm only interested in the file contents; the blame info is just clutter.

(I know that I can drag the splitter to the left to minimize the blame info, but the remaining avatars are still clutter.)

### Steps to reproduce

Browse any repository. Click on any file in the File Tree tab. Blame info appears next to the file contents.

**Comment by pmiossec** [comment]
>However, blame info still displays in the File Tree tab in the main Browse window.

I think it will be resolved by #10453 planned for v4.0.1

> I have this option turned off, because I strongly prefer the old history window. (I've seen comments indicating that this window might be deprecated; I hope that's not true.)

I think it's true. And I'm also afraid that I won't like that and that it could be difficult for me to use the blame feature...

**Comment by FFFirer** [comment]
I want a switch to turn off the blame feature. When open files in file tree tab it takes too much time and is even unresponsive.

**Comment by gerhardol** [comment]
> I want a switch to turn off the blame feature. When open files in file tree tab it takes too much time and is even unresponsive.

Context menu, unselect Blame or just B.
