### ISSUE TITLE
Restore support for Windows-1252 Encoding

### ISSUE THREAD

**Issue by jonathanp0** [gitextensions/gitextensions#10517]
### Feature description

Up until GitExtensions 4, Windows-1252 was supported as an encoding in diff/file display views, which was important to me as I work with a large code base which uses this encoding and contains non-ASCII compatible characters such as ä,ö,ß. I assume it was removed to do .NET dropping support for this encoding.

It appears that although it is not supported "out of the box" by .NET, it is possible to do so: https://stackoverflow.com/questions/37870084/net-core-doesnt-know-about-windows-1252-how-to-fix.

Since is described by Wikipedia as "the most-used single-byte character encoding in the world", I think it would be worth restoring.

### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.31.1.windows.1 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.9
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Windows-1252 is there. The application might need a restart after adding encodings.

![grafik](https://user-images.githubusercontent.com/36601201/207451570-be56476d-5e4a-44ee-b770-ea828d040c9d.png)
