### ISSUE TITLE
I cannot push my commint to the GitHub using SSH

### ISSUE THREAD

**Issue by Lopuch** [gitextensions/gitextensions#10522]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 120dpi (125% scaling)

### Issue description

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""C:\Program Files (x86)\GitExtensions\PuTTY\plink.exe" -T "git@github.com:Lopuch/outlook-add-in-prototype.git""

```
GitExtUtils.ExternalOperationException: Using username "git".
Hi nexti-cloud! You've successfully authenticated, but GitHub does not provide shell access.
 ---> System.Exception: Using username "git".
Hi nexti-cloud! You've successfully authenticated, but GitHub does not provide shell access.
   --- End of inner exception stack trace ---
   at async Task<bool> GitCommands.Plink.ConnectAsync(string host)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

I am unable tu push a commit to the Github using SSH private key. When I hit the "Load SSH key" nothing happens - no prompt to select its location. When I restart my computer things start to work again.

### Steps to reproduce

Unable to push the commit to the GitHub, Error: 

`"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "origin" refs/heads/master:refs/heads/master
fatal: Could not read from remote repository.

EPlease make sure you have the correct access rights
and the repository exists.
RROR: Repository not found.
Done

Press Enter or Esc to exit...`

When I try to "Manage remotes" and hit "Load SSH key" - nothing happens. No prompt is open.
When I hit "Test connection" it says: "Access granted. Press Return to begin session." When I close the command line the error which I am reporting right now appears.

So the main problem is: "**I cannot push my commint to the GitHub using SSH**."

**Comment by RussKie** [comment]
This looks like an issue with your local environment. Please make sure PuTTY is installed.
What happens if you run commands from command line?

**Comment by vbjay** [comment]
You have to configure the key file in the remote.  It will automatically start pagent if needed and start a session and will use the session. Show your remote config screen with anything masked as you desire.

**Comment by Lopuch** [comment]
![Remote config](https://user-images.githubusercontent.com/6599540/208117129-3aa4918b-1b16-471c-a5e2-78ca9e2ee8a8.png)
The strange thing is that after I restart the PC it works again. And the second strange thing is that it started to happen on my both PCs (work and home) at the same date. Even before the 4.x.x update. In fact I thought the update was made because of this bug.

**Comment by vbjay** [comment]
The change was made to give better feedback on what the problem was. You probably had pagent running. Reboot killed the process. Why I said just configure the path right and let ge start pagent for you.

**Comment by vbjay** [comment]
Load sshkey loads the path provided.

**Comment by ignarmezh** [comment]
I got the same error after updated today from 4.0.0 to 4.0.1

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12

GitUI.NBugReports.UserExternalOperationException: SSH key file could not be found
 ---> System.IO.FileNotFoundException: SSH key file could not be found
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.PuttyHelpers.ThrowIfFileNotFound(String filePath, String errorMessage, String heading)
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader)
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote)
   at GitUI.CommandsDialogs.FormPush.PushChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPush.PushClick(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

PuTTY installed correctly. Everything worked before update.

**Comment by RussKie** [comment]
@ignarmezh your error is a dup of #10530, and different from this.

**Comment by RussKie** [comment]
Does it work from a command line?

**Comment by RussKie** [comment]
Does this version fix he issue?
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45710122/artifacts

**Comment by vbjay** [comment]
> Does this version fix he issue?
> https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45710122/artifacts

Did you respond to him?

**Comment by jupsoleil** [comment]
Thanks @vbjay .  
@RussKie : your version fixes my problem: it's no longer required to specify a private key per repository.

Wonderful :-).

Since we distribute ge using chocolatey in our company, is there some idea about when the next official release will come?
