### ISSUE TITLE
Plugin manager disappeared after update to 4.0.1

### ISSUE THREAD

**Issue by mycroes** [gitextensions/gitextensions#10529]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

After update to 4.0.1 Plugin manager is no longer visible in Plugins menu. The Plugin manager is still present in `AppData\Local\GitExtensions\UserPlugins`. The Gerrit plugin that's in the same UserPlugins directory does still work.

### Steps to reproduce

Update to GitExtensions 4.0.1

### Did this work in previous version of GitExtensions?

Yes, 4.0.0.

**Comment by mstv** [comment]
Are we back in the DLL hell?
It works with the PluginManager shipped with [v4.0.0](https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-Portable-4.0.0-cba315df5.zip).

**Comment by maraf** [comment]
Do we have a log from plugin loading?

**Comment by mstv** [comment]
What kind of log do you mean, @maraf?

**Comment by maraf** [comment]
Kind of why the assembly wasn't loaded?

**Comment by mstv** [comment]
If I replace the GitExtensions.PluginManager.dll with an older version, it is loaded. So it is considered.
I cannot reproduce it with my locally built portable version of v4.0.1. I am out.
Where does the portable version search for the user plugins? Where in the code, does it switch from not searching in `%APPDATA%`?

BTW: Why `TryLoadAssembly` without any error logging. This ends in such debug sessions! I hate error-hiding.

**Comment by mycroes** [comment]
My GitExtensions.PluginManager.dll has version 2.0.0.184. I checked out GitExtensions, ran from VS, PluginManager is there. Initially I did this from release/4.0 branch, so I thought maybe there was something in the commits after 4.0.1 handling it, but I resetted to v4.0.1 tag and it still shows up... Not sure how I can debug installed GitExtensions; it doesn't enable breakpoints because no debugging symbols are loaded.

If there's anything I can check let me know, otherwise I'll see what I can figure out on my own.

**Comment by RussKie** [comment]
> GitExtensions.PluginManager.dll has version 2.0.0.184.

That's the correct version.

**Comment by RussKie** [comment]
Is there anything related in the error log (#9227)?

**Comment by mycroes** [comment]
> Is there anything related in the error log (#9227)?

No error log is created, but I also don't get any exceptions. It's just not there in the menu, while the Gerrit plugin is actually functioning (to some extent, but that's almost solved now). I'll have another go at it, will report back.

**Comment by mycroes** [comment]
Next attempt: I replaced `GitUIPluginInterfaces.dll` (in GitExtensions install location) with the one built locally, added the pdb. Had to also copy `GitExtUtils.dll` because different version was now referenced. Now I can debug from VS, which gives me the following:
![image](https://user-images.githubusercontent.com/122017/208051042-a08ad944-d9aa-4731-a788-ddaa490e3b46.png)

As you can see in the watch window it does find the `GitExtensions.PluginManager.dll` the catch in `TryLoadAssembly` is never hit, however the catalog doesn't seem to include the PluginManager. I never used any of the Microsoft.VisualStudio.Composition stuff and I'd rather not waste my time on diving into it's internals, but I don't mind testing anything in the context of the `ManagedExtensibility` class.

Side question, would it be possible to create a debug build (including symbols) of GE on release that would permit attaching without overwriting any of the GE files? Would make it easier to debug issues like these.

**Comment by RussKie** [comment]
You can build a debug version of an msi yourself. We have a link to build
instructions in the readme at the root. Or just follow the steps in
appveyor.yml (you can skip tests and the translations).

**Comment by maraf** [comment]
It happens also in portable version.

**Comment by maraf** [comment]
Can this package reference cause the problem? I don't know the difference between MEF and VS MEF

https://github.com/gitextensions/gitextensions.pluginmanager/blob/bbaafa6eda217877822d0993d1fbea57bc0239f1/src/GitExtensions.PluginManager/GitExtensions.PluginManager.csproj#L21

**Comment by RussKie** [comment]
Just FYI I locally built app run from VS is loading the PM without any issues.

**Comment by RussKie** [comment]
> Can this package reference cause the problem? I don't know the difference between MEF and VS MEF
> 
> [gitextensions/gitextensions.pluginmanager@`bbaafa6`/src/GitExtensions.PluginManager/GitExtensions.PluginManager.csproj#L21](https://github.com/gitextensions/gitextensions.pluginmanager/blob/bbaafa6eda217877822d0993d1fbea57bc0239f1/src/GitExtensions.PluginManager/GitExtensions.PluginManager.csproj#L21)

This looks like a good hypothesis, @maraf.
Attaching to the official v4.0.1 build I can see that the app is using 4.6 version:
![image](https://user-images.githubusercontent.com/4403806/208269433-4e08bbb5-6ee0-4ba4-917a-7edd2252a5fe.png)
