### ISSUE TITLE
Git Extensions v4.0.1 dont work

### ISSUE THREAD

**Issue by Felix1116** [gitextensions/gitextensions#10535]
### Environment

- GitExtensions version:v4.0.1
- GIT version: 2.39.0
- OS version: Windows 10 x64
- .NET version: 

### Issue description

This is my first time use Git Extensions. I have latest version v4.0.1 downloaded and installed.There is no Error Warming or any other Informatin, but i can't open Git Extensions. And there is no process in Task Manager. I have no idea how to solve the problem.
![GitExtensions](https://user-images.githubusercontent.com/23601789/208054751-8a54d235-3053-4a27-8f13-e690fbcb7d10.gif)

### Steps to reproduce

Just double click and don't work.

**Comment by Felix1116** [comment]
> Perhaps the event viewer has more information?

In event viewer i have no information about Git Extensions found. To what kind of informaton in event viewer should i pay attention?

**Comment by mycroes** [comment]
You might have errors like these, but related to GitExtensions:
![image](https://user-images.githubusercontent.com/122017/208066006-4047b534-c27a-4490-8082-0c9571ca16b2.png)

**Comment by Felix1116** [comment]
> You might have errors like these, but related to GitExtensions: ![image](https://user-images.githubusercontent.com/122017/208066006-4047b534-c27a-4490-8082-0c9571ca16b2.png)

Still no error related to Git Extensions.

**Comment by mycroes** [comment]
Do you have Microsoft Windows Desktop Runtime 6.0.12 installed?

**Comment by Felix1116** [comment]
> Do you have Microsoft Windows Desktop Runtime 6.0.12 installed?

You are right. I have Microsoft Windows Desktop Runtime 6.0.12(x86) installed but my system is x64. And there is no "C:\Program Files\dotnet\" in PATH. Now the problem is solved. Thank you!
