### ISSUE TITLE
Please add a switch to toggle the Windows ShellExt enable/disable

### ISSUE THREAD

**Issue by KaneGreen** [gitextensions/gitextensions#10531]
### Feature description

If there is no switch to turn off the Windows ShellExt, user must edit the Windows Registry to disable it.

Besides, the Windows ShellExt (`GitExtensionsShellEx64.dll`) cannot be deleted if the ShellExt in Registry are not deleted. This provents the version update of the Portable version.

### Environment

- GitExtensions version: 4.0.0
- GIT version: cba315df5366fca01240d93b6e5a5077fd5e6630
- OS version: Windows 10 64bit 22H2
- .NET version:

**Comment by pmiossec** [comment]
Done with #10421
Will be available in next major version (which is still not planned at the moment as we just released the v4.0)

**Comment by KaneGreen** [comment]
Major version? You mean 5.0?

**Comment by RussKie** [comment]
vNext, which we haven't decided the number for. There's no ETA for it just
yet, we're still stabilising v4.

**Comment by mstv** [comment]
@KaneGreen, you could use the installer or portable package of a recent development build: https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts.
We have not merged any risky modifications.

**Comment by KaneGreen** [comment]
@mstv Thank you. But now I begin my day off becase of COVID. Sad........
