### ISSUE TITLE
File History is empty after switching from version 3.5.4 to 4.0.1

### ISSUE THREAD

**Issue by hammurapi** [gitextensions/gitextensions#10537]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

### Issue description

With version 3.5.4 I could open the File History of a file, and it showed the tree of commits filtered down to that particular file. For example, the File History of gitextensions\GitUI\GitUI.csproj used to look like this:

![gitextension_3 5 4 12724](https://user-images.githubusercontent.com/3584715/208063752-7e8948ae-ec95-40bc-b0d0-7c5ed33e4982.png)

After switching to version 4.0.1 the tree view shows only to entries “Commit index” and “Working directory”, the actual history tree is missing:

![gitextension_4 0 1 15887](https://user-images.githubusercontent.com/3584715/208063661-aaeffd2d-7379-44ee-9d65-3840eab26ab8.png)

The tree of the older gitextension seem to be the correct one, it matches the output of the git log --graph --all GitUI\GitUI.csproj

![git_log](https://user-images.githubusercontent.com/3584715/208063772-d9e2dac9-e561-42f4-a16d-666810c5c4f8.png)

### Steps to reproduce

In the Windows File Explorer select a file in a repository, right click it to display the context menu and select the “Git Extensions/File History” item. The tree view shows only to entries “Commit index” and “Working directory”, the actual history tree is missing.

### Did this work in previous version of GitExtensions?

Yes, it did with this version:

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4515.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
It is discussed here (with a workaround) : https://github.com/gitextensions/gitextensions/pull/10438#issuecomment-1352773517

**Comment by hammurapi** [comment]
> It is discussed here (with a workaround) : [#10438 (comment)](https://github.com/gitextensions/gitextensions/pull/10438#issuecomment-1352773517)

Thanks for the hint. I was not aware that there were another Issue regarding the similar problem.

**Comment by pmiossec** [comment]
There was no issue, just a discussion on the PR that introduced the regression.
It's always better to open an issue for discussion so because yours is well written with a lot of details, I think we will keep it 😉

**Comment by mstv** [comment]
I cannot reproduce this with
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12

Could you try a recent development version, please: https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts.
It includes another modification in that area, which might resolve the issue or not.

**Comment by hammurapi** [comment]
> I cannot reproduce this with
> 
> * Microsoft Windows NT 10.0.19045.0
> * .NET 6.0.12
> 
> Could you try a recent development version, please: https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts. It includes another modification in that area, which might resolve the issue or not.

No change. It behaves (at least for me) as the release 4.0.1 before:

![gitextension_4 0 1 15926](https://user-images.githubusercontent.com/3584715/208208284-aaaf255b-6982-4b38-bf7f-90f3f6877860.png)


Environment:
- Git Extensions 4.1.0.15926
- Build 21345f29511f71fb1ca7cfd8ea128972b56863e4 (Dirty)
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.0.0-preview6-27804-01 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mstv** [comment]
Thank you, @hammurapi. Then we have to explicitly avoid double quoting.

**Comment by RussKie** [comment]
Regression was introduced in #10438

**Comment by filippoquaranta** [comment]
Hi everyone.

I have same boring issue 

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

![GitExtensions_20240105_111911_890_Friday](https://github.com/gitextensions/gitextensions/assets/231948/ef094cea-851a-462d-87ba-dd7725ad13df)

**Comment by gerhardol** [comment]
> Hi everyone.
> 
> I have same boring issue

Check other filters
Open a new issue, include the Git Command Log.
