### ISSUE TITLE
Branch protection rule: Restrict who can read matching branches

### ISSUE THREAD

**Issue by rezamalik** [gitextensions/gitextensions#10536]
### Feature description

Similar to "Restrict who can push to matching branches", add an additional branch protection rule to restrict read access to matching branches. For example:

```
**Restrict who can read matching branches**
Specify people, teams, or apps allowed to push to matching branches. Required status checks will still prevent these people, teams, and apps from merging if the checks fail.
```

Ticking the "Restrict who can read matching branches" checkbox displays an input field to search for people, teams, or apps who will be granted read access.

At bottom of the section display the people, teams, or apps that have read access to the matching branches.

### Environment

github.com

**Comment by pmiossec** [comment]
Not related to GitExtensions software so surely you are posting to the wrong repository.
And what you are asking seems not fitting well with how git is working (where you could have all the commits history locally) .
So unlikely that it will be done one day...
