### ISSUE TITLE
[NBug] SSH key file could not be found

### ISSUE THREAD

**Issue by oleopold** [gitextensions/gitextensions#10530]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

''

```
GitUI.NBugReports.UserExternalOperationException: SSH key file could not be found
 ---> System.IO.FileNotFoundException: SSH key file could not be found
   --- End of inner exception stack trace ---
   at GitUI.Infrastructure.PuttyHelpers.ThrowIfFileNotFound(String filePath, String errorMessage, String heading)
   at GitUI.Infrastructure.PuttyHelpers.StartPageantIfConfigured(Func`1 sshKeyFileLoader)
   at GitUI.CommandsDialogs.FormPush.StartPageant(String remote)
   at GitUI.CommandsDialogs.FormPush.PushChanges(IWin32Window owner)
   at GitUI.CommandsDialogs.FormPush.PushClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

I just tried to push to remote origin.
Pull work just fine.
I use key stored in putty session which I use for accessing remote repository.
So I do not have private key in remote repository configuration.

### Steps to reproduce

Try to push into remote configured without explicit ssh key(using putty).

### Did this work in previous version of GitExtensions?

Yes

**Comment by vbjay** [comment]
So fix your remote config to the correct key file path.

**Comment by SymbioticKilla** [comment]
Same problem

**Comment by RussKie** [comment]
Please remove the invalid key reference from your config.

**Comment by SymbioticKilla** [comment]
@RussKie there is no key. I have two remotes: One is DMZ with public key and one company inside without any key. If I switch to OpenSSH company remote works but I need both to work. It was warking in 3.5.1 and the author of this issue said that it worked in 4.0 too.

**Comment by oleopold** [comment]
I use paegant to manage keys and saved session in putty which tells the key which will be used. So if I have one server from which I clone repositories I do not have to fill key for each of them. It works for command line git and in all previous versions of GitExtensions. It stopped working in latest version.

**Comment by SymbioticKilla** [comment]
@RussKie  It is a bug. Just installed V4 and it works. In 4.0.1 doesn't work. In 3.5.4 was also working.

**Comment by RussKie** [comment]
Does this version fix he issue?
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45710122/artifacts

**Comment by SymbioticKilla** [comment]
Works! Thanks!

**Comment by oleopold** [comment]
Yes, the build works as expected. Thank you.

**Comment by gerhardol** [comment]
https://github.com/gitextensions/gitextensions/pull/10545#discussion_r1057637433

If a key is configured but not available, should the used be informed with a popup or this be ignored?

**Comment by oleopold** [comment]
> [#10545 (comment)](https://github.com/gitextensions/gitextensions/pull/10545#discussion_r1057637433)
> 
> If a key is configured but not available, should the used be informed with a popup or this be ignored?

I think that if key is configured than user should be informed when key is missing.

**Comment by RussKie** [comment]
Please try the latest version: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45814904/artifacts

**Comment by psivanov** [comment]
Exact same issue on

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

**Comment by CorneliusDaniell** [comment]
Switch ssh client to OpenSSH instead of PuTTY

**Comment by psivanov** [comment]
I use pageant like oleopold and it used to work with PuTTY, though...

**Comment by mstv** [comment]
> Exact same issue on
> 
>     * Git Extensions 4.0.2.15986

Yes, you are right because

> https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45814904/artifacts

is the build 15986 right before the integration of the fix. 

You could use https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45842693/artifacts.

**Comment by psivanov** [comment]
> > Exact same issue on
> > ```
> > * Git Extensions 4.0.2.15986
> > ```
> 
> Yes, you are right because
> 
> > https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45814904/artifacts
> 
> is the build 15986 right before the integration of the fix.
> 
> You could use https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45842693/artifacts.

Ah, thank you. It works now.
