### ISSUE TITLE
Checkout Branch Shortcut (Ctrl + .) no longer working

### ISSUE THREAD

**Issue by ericridgeway** [gitextensions/gitextensions#10541]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.36.1.windows.1 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Upgraded to 4.0 from an old Git Extensions version from last year. After upgrade, my most-used shortcut -- Checkout Branch (Ctrl + .) -- no longer works.

It IS still listed under Commands->Checkout Branch as that being the shortcut

### Steps to reproduce

Download newest Git Extensions version 4.0 as requested by annoying popup. Delete old version as requested by installer. Run installer. Open newly installed 4.0 version. Press (Ctrl+.) 

Nothing happens

### Did this work in previous version of GitExtensions?

I believe my previous version was 3.5 but I'm not sure. It was downloaded as recently as this year though, so it was a very recent version where this shortcut still worked fine

**Comment by mstv** [comment]
Please re-assign the hotkey. You will see the difference. (For details, search for duplicates.)

**Comment by ericridgeway** [comment]
This worked. The new key is listed as `(Ctrl+0emPeriod)` instead of `(Ctrl+.)`. Thank you
