### ISSUE TITLE
BUG: run-command.c:1521: you must provide a non-zero number of processes!

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#10540]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

"C:\Program Files\Git\bin\git.exe" pull --rebase --progress --jobs=0 "origin"
BUG: run-command.c:1521: you must provide a non-zero number of processes!

### Steps to reproduce

I ran pull with rebase. 

### Did this work in previous version of GitExtensions?

Yes. I think it's related to git version.

**Comment by tomasfejfar** [comment]
Caused by https://github.com/git/git/commit/51243f9f0f6a932ea579fd6f8014b348f8c2a523

**Comment by tomasfejfar** [comment]
Duplicate of #10514 (the actual error message was only in screenshot so I couldn't find it)

**Comment by pmiossec** [comment]
@tomasfejfar I don't know if you saw but the bugfix release v4.0.1 released yesterday fix this issue.

**Comment by tomasfejfar** [comment]
Yes, I noticed afterwards, thanks for pointing that out. 

I hit another hurdle though (that fortunately had a workaround) in https://github.com/gitextensions/gitextensions/issues/9588#issuecomment-1355049450
