### ISSUE TITLE
[NBug] Exit code: -1073741510 Using username "git".

### ISSUE THREAD

**Issue by mrveress** [gitextensions/gitextensions#10543]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

### Issue description

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""C:\Program Files\PuTTY\plink.exe" -T "git@github.com:mrveress/my-farming-grp.git""

```
GitExtUtils.ExternalOperationException: Using username "git".
 ---> System.Exception: Using username "git".
   --- End of inner exception stack trace ---
   at async Task<bool> GitUI.Infrastructure.Plink.ConnectAsync(string host)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

Well, it throws when you just use PuTTy SSH key to Github.
Reproducing:
- Load PuTTy .ppk key for Github.com
- Click "Load SSH Key" - ok
- Click "Test Connection" - Terminal opens with "Access Granted. Click Return..." blablabla. Click "Enter" key, then close terminal window
- TADA Exception (at least for me)

### Steps to reproduce

- Load PuTTy .ppk key for Github.com
- Click "Load SSH Key" - ok
- Click "Test Connection" - Terminal opens with "Access Granted. Click Return..." blablabla. Click "Enter" key, then close terminal window
- TADA Exception (at least for me)

### Did this work in previous version of GitExtensions?

Yes, but not sure about version

**Comment by RussKie** [comment]
Does it work from a command line?

**Comment by mrveress** [comment]
@RussKie yep, when you runs this from cmd it's okay.
And I checked for all my repos - the same issue everywhere, re-installed git/gitext/putty - no effect. 
Maybe new version of the git returning strange exit code? Not sure.

**Comment by RussKie** [comment]
Thank you for the confirmation.

**Comment by mstv** [comment]
Found at SO: Exit Code `0xC000013A` (`STATUS_CONTROL_C_EXIT`) means that the application terminated as a result of a `CTRL+C` or  closing command prompt window.
Do you still get the error if you close the command prompt by entering `exit`?

**Comment by mstv** [comment]
(The check of the exit code was added with #5315 in 2018.)

**Comment by mrveress** [comment]
Yes, maybe more details needed here, because maybe it's about Windows 11 & Terminal. So I'll post series of screenshots for you as I reproducing it:

1. Start window, clicking "Test Connection"
![image](https://user-images.githubusercontent.com/1701280/208485354-65512d50-23dd-4de9-8d26-86acc18a136b.png)
2. This window when I clicked "Test Connection". Just click "Enter"
![image](https://user-images.githubusercontent.com/1701280/208485585-61d9e7a2-2f76-41a2-9c14-fb109fcb60a8.png)
3. I clicked "Enter" but window still here. PROBABLY here is the pain, because console not closing automatically
![image](https://user-images.githubusercontent.com/1701280/208485648-b8a3db6e-1fd2-42bd-a3d8-0a7fd5f708b2.png)
4. So I see the console, and Access granted. I'm happy, but I need to close console right? Closing the console with right corner button by LMB.
5. And you getting this one, and exit code is 0xC000013A just because I should close console by myself.
![image](https://user-images.githubusercontent.com/1701280/208486036-1a914c0c-da23-4996-bd23-f1e9c446ab0e.png)

I hope screenshots was helpful

**Comment by mstv** [comment]
My question was whether you get a popup when type "exit<enter>" in step 4.

---

As the screenshots show, there already is a pause in step 2 - making the success visible.
So we could start `cmd.exe` with auto-close, i.e. with "/c" instead of "/k".
But "/k" might be necessary in case access is not granted.

**Comment by mstv** [comment]
> Does this version fix he issue?

It cannot. This issue is about how the command prompt (`cmd /k do_something_on_open`) is closed.

**Comment by mrveress** [comment]
Nope, the same:

- Git Extensions 4.0.2.15932
- Build c407b1481c37e1383a16f3efc366d6338b642355 (Dirty)
- Git 2.39.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 96dpi (no scaling)

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""C:\Program Files\PuTTY\plink.exe" -T "git@github.com:mrveress/my-farming-rpg.git""

```
GitExtUtils.ExternalOperationException: Using username "git".
Hi mrveress! You've successfully authenticated, but GitHub does not provide shell access.
 ---> System.Exception: Using username "git".
Hi mrveress! You've successfully authenticated, but GitHub does not provide shell access.
   --- End of inner exception stack trace ---
   at async Task<bool> GitUI.Infrastructure.Plink.ConnectAsync(string host)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

**Comment by mstv** [comment]
I guess you need to authenticate using a PAT. GH authentication "using web browser" stored in the Git Credential Manager works pretty smooth as well.

**Comment by vbjay** [comment]
No read the error message @mstv. The authenticion actually succeeded. 

See test 2 in https://github.com/gitextensions/gitextensions/pull/10357#issuecomment-1312771641

**Comment by mstv** [comment]
What about "but GitHub does not provide shell access"?

---

It looks like you are a console killer, too, Jay.

Before we ignore exit code `0xC000013A`, I want to know:
1. Is there a popup if the console is closed cleanly, i.e. by typing `<enter>`, `exit`, `<enter>`?
2. How does it look when access is denied?
I want to know this in order to distinguish which exit codes are to be considered a success.

**Comment by vbjay** [comment]
> What about "but GitHub does not provide shell access"?

That's standard with the type of shell being used on github side. They allow authentication but not shell access so you don't get a shell and run commands. That message is a success. 


> ---
> 
> It looks like you are a console killer, too, Jay.

:Grin

I'll generate a different key that doesn't have access to my GitHub and see what it generates.

**Comment by vbjay** [comment]
https://linuxopsys.com/topics/disable-shell-access-to-user-account. Same can be done for ssh.
