### ISSUE TITLE
Impossible to switch between branches if revision filter is set to "current branch"

### ISSUE THREAD

**Issue by esmantovichanna** [gitextensions/gitextensions#10558]
### Environment

- GitExtensions version: 4.0.1.15887
- GIT version: 2.38.1.windows.1
- OS version:  windows 10 pro
- .NET version: 6.0.12
![Screenshot 2022-12-20 151731](https://user-images.githubusercontent.com/121109803/208687908-08136d0c-2c7d-4ab0-a1a8-6d806b1c124d.png)
![Screenshot 2022-12-20 151752](https://user-images.githubusercontent.com/121109803/208687916-3a723e05-1481-4bd1-9fca-ab3430999f04.png)

### Issue description

Can't switch to other branch until set filter to "all branches". Previous versions it was available.

### Steps to reproduce

You need two different branches with different commits. 
Switch to the first branch and set filter to "current branch"
Then try to switch to the second branch through the tree on the left side of the screen - you should get the error from the attachments

### Did this work in previous version of GitExtensions?

Yes

**Comment by mstv** [comment]
For `Current branch only`, the left panel is *not* filtered as it is when `Filter for selected` has been activated. Checkout works for "invisible" branches.

![image](https://user-images.githubusercontent.com/36601201/208700270-1559ca38-1766-4a5a-af84-77fcc127aa91.png)

**Comment by gerhardol** [comment]
Doubleclicking need to be handled as for unreachable stashes, similar to the rightclicking

**Comment by mstv** [comment]
We should rather update visibility state of the branch leaf-nodes. Then the single-click handler omits the attempt to select in the RevisionGrid. Doubleclick works then.

**Comment by gerhardol** [comment]
In addition to right-clicking and selecting the branch, you may use the toolbar to select it
![image](https://user-images.githubusercontent.com/6248932/208717146-b07fef26-0b29-41d1-9aea-d423ded956ec.png)
