### ISSUE TITLE
Scroll wheel does not work anymore with branch selection.

### ISSUE THREAD

**Issue by andrewtite-webonise** [gitextensions/gitextensions#10564]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 144dpi (150% scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Normally I use my scroll wheel to scroll through my branches I want to checkout.
Since the last update, the scroll wheel doesn't work and I have to click either the up or down arrows over and over until I reach the desired branch.
Can you please bring this back?
It's really annoying having to 'click, click, click, click, etc.'.
Thanks. :)

### Steps to reproduce

Try to scroll! lol

### Did this work in previous version of GitExtensions?

Yes, all of them (as far as I'm aware).

**Comment by vbjay** [comment]
Might want to use the obsolete branch plugin and cleanup merged branches.

**Comment by mstv** [comment]
> Did this work in previous version of GitExtensions?
> Yes, all of them (as far as I'm aware).

If you mean the DropDown in the toolbar, the scrollwheel does not work neither in 3.0 nor in 3.5 nor in 4.x.
![image](https://user-images.githubusercontent.com/36601201/208981477-68a4258a-2c5d-4aba-97b0-586864944f3a.png)

**Comment by gerhardol** [comment]
Scrollwheel works in checkout branch dialog and in the sidepanel

**Comment by RussKie** [comment]
Closing due to unclear issue and lack of follow up.
