### ISSUE TITLE
fileeditor not present

### ISSUE THREAD

**Issue by CyrChudac** [gitextensions/gitextensions#10579]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 192dpi (200% scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When GitExtensions are installed on windows in other directory than C:/Program Files (x86) (in my case it even on D:/...), the fileeditor fails to open when necessary. And so I my rebase attempt failed too when conflicts were encountered.

### Steps to reproduce

1. Install git extensions on windows in directory other than Program Files (x86)
2. open it and run rebase with conflicts
3. when fileeditor should be opened this message pops up instead:

hint: Waiting for your editor to close the file... "C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor: line 1: C:/Program Files (x86)/GitExtensions/GitExtensions.exe: No such file or directory
error: There was a problem with the editor '"C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor'.
Please supply the message using either -m or -F option.
error: could not commit staged changes.
Done

Press Enter or Esc to exit...

### Did this work in previous version of GitExtensions?

In previous version, it was ok. I think it was 3.1xyz... but I am not sure.

**Comment by vbjay** [comment]
So edit the path..  it is editable.

**Comment by CyrChudac** [comment]
@vbjay oh, mb... 😂 ty anyways!

**Comment by gerhardol** [comment]
This is a Git setting, I believe it is set if not set before.
If you change your installation, you have to change it yourself.
(GE should normally not automatically change Git settings.)

![image](https://user-images.githubusercontent.com/6248932/209481762-6d1f95f8-cd7c-4e0c-9c44-7b59d893d329.png)
