### ISSUE TITLE
Git Extensions locks files, causing access denied errors

### ISSUE THREAD

**Issue by justanotheranonymoususer** [gitextensions/gitextensions#10580]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

Several times, while running scripts in the repo folder, I got errors such as `self._accessor.rename(self, target) PermissionError: [WinError 5] Access is denied`. Suspecting Windows Defender and other tools, I finally pinpointed this problem to Git Extensions, and I could come up with reproduction steps.

### Steps to reproduce

* Initialize a new repo
* Create this Python file: https://gist.github.com/justanotheranonymoususer/fa5dbcb4cea5f09a83c51bb14f1f0712
* Open Git Extensions to view the repo
* Run the script
* Wait for several seconds until you get this error:
```
C:\test>1.py         
Traceback (most recent call last):
  File "C:\test\1.py", line 14, in <module>
    p.rename(p2)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 1232, in rename
    self._accessor.rename(self, target)
PermissionError: [WinError 5] Access is denied: 'p' -> 'p2'
```

I get this constantly. The error doesn't happen if Git Extensions is minimized or closed.

**Comment by pmiossec** [comment]
> I finally pinpointed this problem to Git Extensions,

When you say that, have you a clear proof that it is the GitExtensions exe and not one of the subprocess (like git status which is launched only when GitExtensions is active. or another?) that lock the file?

Have you used a tool that show you explicitly that it is gitextensions?
(You have this feature in 'Process Explorer' to find out which process lock a file or folder. And it would be great if you could come back with this information... See doc https://superuser.com/a/399660/1277898 ).
Or you just noticed that you don't have the problem when gitextensions is not active?

**Comment by justanotheranonymoususer** [comment]
I'm not sure whether it's a Git Extensions process or a child process.
I haven't used such a tool, not sure how to do that since the lock is
very temporary. But I can tell that VSCode also monitors for git
changes and it never caused such issues for me while being constantly
open.

**Comment by RussKie** [comment]
You shouldn't run multiple git processes against the same repo. With that, either don't run Git Extensions while you're developing your code, or configure VS Code not to run git.

**Comment by mstv** [comment]
You could turn off the GitStatusMonitor by deactivating both AppSettings `ShowGitStatusInBrowseToolbar` and `ShowGitStatusForArtificialCommits`.

![image](https://user-images.githubusercontent.com/36601201/210890299-4a7174c1-43f6-4282-b654-c8ae60e89839.png)
