### ISSUE TITLE
"Path filter" is not right for the "file history" shell extension 

### ISSUE THREAD

**Issue by zhengdao** [gitextensions/gitextensions#10589]
### Environment

Latest release + Windows 10

### Issue description

With the latest release, selected a file, then click the "Git Extensions -> File History", the "Path filter" for the Advance filter always be escaped and re-wrapped as _"\"xxxx\xxxx\xxx.java\""_ . So that no file history can be shown. After changing it as _"xxxx\xxxx\xxx.java"_, it works right.

### Steps to reproduce

- select file
- Git Extensions -> File History
- Filter (Toolbar) -> Advanced Filter -> Path filter

**Comment by pmiossec** [comment]
Fixed by #10546. Will be in next bugfix release...
