### ISSUE TITLE
File history not displayed properly / not working

### ISSUE THREAD

**Issue by tykovec** [gitextensions/gitextensions#10595]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.11
    Microsoft.WindowsDesktop.App 6.0.12
    Microsoft.WindowsDesktop.App 7.0.0
```

### Issue description

File history explorer context menu command is not working properly, there are added quotes (\") on the begining and end of file path which is afterwards wrongly interpreted.

### Steps to reproduce

1) Right click on local file in windows file explorer for which we want to display history.

![image](https://user-images.githubusercontent.com/16893815/210245130-d310dfb6-d340-44cf-89ec-20f036c0a742.png)

2) Select file history

3) There is no history displayed
![image](https://user-images.githubusercontent.com/16893815/210245495-cdc42321-b230-40eb-b3b1-429ca90b3ef8.png)

This issue is also in visual studio gitextensions extension

### Did this work in previous version of GitExtensions?

Yes it was in all versions functional.

### Diagnostics

Problem are quotes (\"), this should be removed, as workaround i am removing these in Filter -> Path Filter
![image](https://user-images.githubusercontent.com/16893815/210245825-a6e11211-10d2-4a5c-be7a-7964f1a70783.png)

**Comment by pmiossec** [comment]
Fixed by  #10546. Waiting for next bug fix release.
