### ISSUE TITLE
Default remote to fetch is not origin

### ISSUE THREAD

**Issue by PeterMinin** [gitextensions/gitextensions#10603]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12

### Issue description

The manual on `git fetch` says:
"When no remote is specified, by default the `origin` remote will be used, unless there’s an upstream branch configured for the current branch."
However, GE chooses the default differently. Namely, it seems to choose based on the sorting order of the remotes' names.
I expect GE to either follow Git's behavior, or to allow me to choose the default remote.

### Steps to reproduce

- Have a repository with 2 remotes: `origin` and `a`. It's important that the other remote's name is alphabetically "less" than `origin`.
- Check out a local branch, one without any upstream.
- Click Fetch on the toolbar.
- Note the command executed.

Expected behavior: the command either doesn't include a remote, or it is `origin`.
Actual behavior: the command includes `"a"`.

**Comment by mstv** [comment]
Moreover, many of my repos do not have a remote named "origin". Some don't even have "upstream".
For a simple fetch, we could omit the remote.
More important is FormPush IMO.
Perhaps the settings - recently discussed in #8741 - could be used for fetch and pull, too.
The "Remote repositories" manager form might be a good place for the configuration of a separate default repo for fetch and push each.

As a workaround, you could use "fetch all" (parallelized in recent git).

**Comment by vbjay** [comment]
Look at the remote management dialog and switch to to the 2nd tab. Verify that a default remote for the branch you are on isn't set. This will control the remote that is used.

**Comment by mstv** [comment]
> Look at the remote management dialog and switch to to the 2nd tab. Verify that a default remote for the branch you are on isn't set. This will control the remote that is used.

I guess nobody wants to do this for every local branch... Unless I have got it wrong, this request is about the fallback / default behavior if no tracking branch is checked out.

**Comment by RussKie** [comment]
When you add a new remote the app asks whether the new remote becomes the default and runs some git command (I can't tell you what it is from the top of my head). This command makes that connection for git and drives the app afterwards.

**Comment by RussKie** [comment]
`origin` like `upstream`, `master`, `main`, etc., are just labels for refs (local or remote). Conventions. However, there's nothing stopping users to choose different labels - e.g., `fork`, `remote`, `dev`, etc. The app can't possible know your specific convention, nor it can parse human-readable output from git to extract some random peice of text. Conventions change, and what's an accepted value today can change tomorrow (e.g., `master` -> `main`). 
With that the app acts on the information it has - i.e., the more it has.

Whilst this is somewhat inconvenient and not perfect, I don't expect us to do any active work in this area. If you feel strongly about this, you're welcome to propose an enhancement.

**Comment by vbjay** [comment]
https://stackoverflow.com/questions/18801147/changing-the-git-remote-push-to-default
