### ISSUE TITLE
Changing branch  often don't change the directory of the console. 

### ISSUE THREAD

**Issue by Keerthikan** [gitextensions/gitextensions#10610]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4515.0
- DPI 96dpi (no scaling)

### Issue description

I have this issue with git extension which is quite annoying. 
Everytime i change from one repo to another, the console doesn't change to the according directory. 
![billede](https://user-images.githubusercontent.com/6702643/210778608-e8996fc2-ba0a-4041-a81f-b58285eab444.png)
Which a lot of times result in git commands being executed in the inccorect branch, and the outcome you expect is incorrect. 
I have multiple times git reset the incorrect branch because it either wanted me to commit something which were in a different repo. 

### Steps to reproduce

Change repo using this 
![billede](https://user-images.githubusercontent.com/6702643/210778976-4a626fe7-1b70-4229-bed5-816c77a9f314.png)

### Did this work in previous version of GitExtensions?

Yes, i don't know which version though. but quite some time ago. 

### Diagnostics

I guess some incorrect character has been added by mistake. 
'' is not recognized as an internal or external command,
operable program or batch file.

Not sure why the line is there -  but I assume removing it would resolve the issue 
[                    terminal.RunningSession.BeginGuiMacro("Keys").WithParam("^A").WithParam("^K").ExecuteSync();](https://github.com/gitextensions/gitextensions/blob/6eab7392839c4d103bad1581fba5eaf6f008d766/GitUI/Shells/ConEmuControlExtensions.cs#L19)

**Comment by mstv** [comment]
Do you use git-bash? You could consider updating git.
This issue is related to #9761

**Comment by Keerthikan** [comment]
I seem unable to update my git, but for now it seem to work for me just by  changing to powershell.

**Comment by pmiossec** [comment]
> Not sure why the line is there - but I assume removing it would resolve the issue
> [ terminal.RunningSession.BeginGuiMacro("Keys").WithParam("^A").WithParam("^K").ExecuteSync();](https://github.com/gitextensions/gitextensions/blob/6eab7392839c4d103bad1581fba5eaf6f008d766/GitUI/Shells/ConEmuControlExtensions.cs#L19)

The comment explaining this line has been lost in the refactoring but that was the solution found to clear the bash command line using conemu macro. It normally send a <key>A</key> and <key>K</key>.

It works for me.

Did you changed some conemu configuration that prevent it to run macros or something approching?

**Comment by Keerthikan** [comment]
Nope no configuration has been altered.

**Comment by RussKie** [comment]
I think this was fixed by #10613.
