### ISSUE TITLE
Enviroment vars "GIT_*" are propagated to child processes

### ISSUE THREAD

**Issue by veksha** [gitextensions/gitextensions#10636]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.12
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

I configured difftool in "Git Extensions" (GE), then launched it by pressing F3 in "Diff" tab.
GE launched this tool (created child process with same environment vars as GE process, i suppose)

they look like this:
```
{
    'GIT_DIFFTOOL_NO_PROMPT': 'true',
    'GIT_DIFFTOOL_TRUST_EXIT_CODE': 'false',
    'GIT_DIFF_PATH_COUNTER': '1',
    'GIT_DIFF_PATH_TOTAL': '1',
    'GIT_DIR': 'F:/MySSDPrograms/CudaText_up/src/CudaText/.git',
    'GIT_EXEC_PATH': 'C:/Program Files/Git/mingw64/libexec/git-core',
    'GIT_EXTERNAL_DIFF': 'git-difftool--helper',
    'GIT_MERGETOOL_GUI': 'true',
    'GIT_PAGER': '',
    'GIT_PREFIX': '.',
    'GIT_WORK_TREE': 'F:/MySSDPrograms/CudaText_up/src/CudaText'
}
```
maybe more..

the problem is my difftool (CudaText) is full featured text editor, not just little diff tool and it has a lot of plugins.
so these env vars above will pollute into CudaText process and break a lot of its plugins (they can launch git process too, for example).
I think it is important to not pollute environment and run difftool (and other tools?) with clean default environment.

### Steps to reproduce

1. configure difftool
2. launch difftool (press F3 in "Diff" tab)
3. observe that child process (difftool) is copied environment vars ("GIT_*") from parent process (GE)

for example: this will break `git_status` plugin in CudaText (used as difftool)

**Comment by RussKie** [comment]
A child process will inherit the parent's environment variables, this is
how it's supposed to work.

**Comment by veksha** [comment]
but they are for internal use. who should clean them? parent or child?

**Comment by veksha** [comment]
@RussKie, hm... maybe these env vars are used for `difftool` to resolve relative paths of passed files.
but don't you think it is better to pass absolute paths and do not pass env vars that may break `difftool`?

**Comment by veksha** [comment]
"current dir" is enough to resolve relative paths.

**Comment by RussKie** [comment]
When I press F3 and a diff opens, it's not owned by Git Extensions but by git process:
![image](https://user-images.githubusercontent.com/4403806/212235096-e2c72d7d-26fd-4c40-800e-9e498886de23.png)

When launching difftools the app run the following command `git difftool --gui --find-renames --find-copies --no-prompt ....` and git handles the rest
https://github.com/gitextensions/gitextensions/blob/91c131522cfeaa35f25d300b72cdc6b41f01a410/GitCommands/Git/GitModule.cs#L3662-L3707

> who should clean them? parent or child?

Whatever process is affected is responsible - e.g., if your app requires different values to those configured, then your app would need to configure itself correctly. We do just the same here - there are multiple git configurations that a user can set, and which would prevent the app from functioning correctly, and we configure those as the app requires.

**Comment by veksha** [comment]
@RussKie , thanks for info! so git process is responsible.
not a bug of `Git Extensions`.

**Comment by pmiossec** [comment]
> A child process will inherit the parent's environment variables, this is how it's supposed to work.

To add some little more information here, that's the operating system, when a sub-process is created, that inherits all the env vars of the parent process.

If it breaks the one of the child process, you need explicitly to clean/overwrite yourself the env vars.

Maybe you would like to create a wrapper script that has the only goal to clean some env vars before launching the diff tool...

**Comment by veksha** [comment]
@pmiossec thanks for your input.

I guess `difftool` (CudaText in my case) should detect if it is launched like a difftool (by looking at env vars) and warn user about this. something like "Warning: GIT environment variables detected. Child processes will inherit them and might not work as expected. Proceed with caution."

also the purpose of git difftool is to launch new process instance, then edit files if needed, then save and close process before doing another round. correct?
so user of CudaText must disable one-instance mode.
