### ISSUE TITLE
Ability to clear recent repositories.

### ISSUE THREAD

**Issue by lukebakken** [gitextensions/gitextensions#1064]
It would be great to be able to clear the recent repository list.

**Comment by brunocastello** [comment]
+1, its 2022 and still we dont have that?

**Comment by gerhardol** [comment]
> +1, its 2022 and still we dont have that?

Git extensions is a comunity project. Basicallv, the person that wants a feature implements it. Contributions are welcome.

**Comment by RussKie** [comment]
It's 2022, and some users are still rude, have attitude issues and can't follow the links.

@brunocastello this issue has been fixed 5 years ago. If you'd spend 30 seconds reading the issue and following the links - you'd surely see that this was implemented in #3678. Furthermore, the dashboard exposes all the same functionality too
![image](https://user-images.githubusercontent.com/4403806/180397189-1e7049a0-e8b0-4f29-a150-c96470143d62.png)

You're welcome.
