### ISSUE TITLE
Check for update: No updates found

### ISSUE THREAD

**Issue by 011V32** [gitextensions/gitextensions#10657]
### Environment

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.12
- DPI 168dpi (175% scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

If I select "Help" -> "Check for updates", I get the Information, that no updates are found. But I use V4.0.1 and V4.0.2 is since 4 days available.

### Steps to reproduce

Use V4.0.1 and go to "Help" -> "Check for updates"

### Did this work in previous version of GitExtensions?

Yes

**Comment by 011V32** [comment]
I have also tried it with different networks, but I hope that the error message is different when no connection is established at all.

**Comment by RussKie** [comment]
The auto update hasn't been updated, we need to push the ConfigData branch.
I forgot about it. Thank you for the reminder.

I'll try to do it tomorrow unless someone else from the team does it.

**Comment by pmiossec** [comment]
> I'll try to do it tomorrow unless someone else from the team does it.

It should be done.

@011V32 can you check it is working good?

**Comment by 011V32** [comment]
@pmiossec it works.
Thx.

**Comment by RussKie** [comment]
Thank you @pmiossec .
