### ISSUE TITLE
"File history" doesn't work anymore

### ISSUE THREAD

**Issue by jebisseySidel** [gitextensions/gitextensions#10653]
### Environment

- GitExtensions version: 4.0.1.15887
- GIT version: 2.39.0
- OS version: NT 10.0.19044.0
- .NET version: 6.0.12

### Issue description

From file explorer. A right click  on a file to select "Git Extensions/File history" option open the application. But no information is displayed.

### Steps to reproduce

See issue description

### Did this work in previous version of GitExtensions?

Yes

**Comment by pmiossec** [comment]
Fixed by #10546
Please update to last version
