### ISSUE TITLE
Available encodings in diff viewer changed 

### ISSUE THREAD

**Issue by MeikTranel** [gitextensions/gitextensions#10658]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.22623.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

#### Additional Environment Details

**OS Display Language**: en-US
**OS Keyboard Language**: de-DE

### Issue description

Some of the files we manage are Windows-1252 and sometimes VSCode or some other tool accidentally converts the file to UTF-8 or something similar. 
When diagnosing those issues we used to be able to switch from the default UTF-8 to `Windows-1252` or `iso-8859-1` (i dont remember exactly what the entry was called).

With 4.0.2 the options are these:
![image](https://user-images.githubusercontent.com/6466560/213421395-679a3813-9125-444a-8f65-6288949169ac.png)

### Steps to reproduce

- Open a file containing umlaut letters saved with Windows-1252: [Windows-1252Test.txt](https://github.com/gitextensions/gitextensions/files/10455992/Windows-1252Test.txt)
- Track in some repo
- Destroy encoding to your liking (partially stage & commit some chinese/russian alphabet letters is a classic)
- View diff in gitextensions
- Open dropdown for diff viewer encoding

### Did this work in previous version of GitExtensions?

Previous gitextensions versions allowed me to select `Windows-1252` or some other Umlaut-friendly encodings.

**Comment by pmiossec** [comment]
Please have a look at this comment https://github.com/gitextensions/gitextensions/issues/10517#issuecomment-1349805956

**Comment by MeikTranel** [comment]
Oh yeah did not expect the setting to be available under the git options since the button next to the encoding dropdown leads you to `Detailed > Diff Viewer` - looks like i should have gone digging a little longer. But yeah the selection suffices for me.
