### ISSUE TITLE
Delete obsolete branches plugin - deleting stuck

### ISSUE THREAD

**Issue by jaka-logar** [gitextensions/gitextensions#10662]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.13
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Delete obsolete branches is stuck on deleting branches. Loading is spinning all the time and all you can do is to close Delete obsolete branches window.

### Steps to reproduce

- Open Delete obsolete branches plugin
- Select branch
- Click delete and confirm.

### Did this work in previous version of GitExtensions?

Before v4

**Comment by matthiaslischka** [comment]
I was just writing the same issue at this moment 😅

It's stuck here:
![5ea5ed2e-18c2-473f-9f72-12786f3254d4](https://user-images.githubusercontent.com/12046115/213668114-8bc75dec-60bd-4a1d-bdd1-6bbba63c6190.gif)


But it seems to always delete exactly ONE branch - but not all. And even if only one is selected, it gets stuck.

Maybe we can fix this together with #9293. Likely related.

**Comment by pmiossec** [comment]
PR #10663 should fix the issue.

**Comment by jonnydee** [comment]
It seems like this bug made it back into newer versions. I am using

```
- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.1
```

and the progress indicator is (still) indicating progress forever.

**Comment by RussKie** [comment]
Please try 4.2
