### ISSUE TITLE
Updating GitEx brick the app due to not being self contained publish

### ISSUE THREAD

**Issue by tebeco** [gitextensions/gitextensions#10669]
### Environment

- GitExtensions version: can't start `gitex` to get accurate value
- GIT version: not relevant / latest 2.39.1
- OS version: not relevant / latest insider dev feed
- .NET version: 
```
❯ d --info
.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x64
  Commit:       d037e070eb

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.102 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

### Issue description

GitExtension is not self contained and update are subject to break the app

The artifact is built in a way that the rollover policy does not check for installed patch that could be older.
This means that if gitex is updated before the computer decides to update their SDK installation (because devs rarely instally the runtime only but rather have it installed through SDK)
Then `gitex` is unable to launch:
![image](https://user-images.githubusercontent.com/2266487/213994441-0402e58e-8e07-40f2-9cca-91b5c8138fc6.png)

### Steps to reproduce

* install an old version of `gitex`
* install `dotnet sdk 6.0.11`
* update to somehow the latest gitex
* it won't start again

Shipping self-contained app would make this bug disappear, for the cost of few mega byte on top of the existing one.

### Did this work in previous version of GitExtensions?

older `gitex` version not requiring that would work.

Shipping self-contained app would make this bug disappear, for the cost of few mega byte on top of the existing one.
I guess one could propose that and also a "lighter install that will require manual update of the SDK before updating gitext" (that seems weird to read)

**Comment by gerhardol** [comment]
GE is intentionally not including Deaktop Runtime x64, to benefit from platform updates without updating the app itself.
The app is bootstrapped, if the appropriate runtime is not found, the popup will prompt a download.

**Comment by tebeco** [comment]
so the app is bricked until someone does a manual install of the runtime after an update ?

yes that's the issue being open

**Comment by tebeco** [comment]
as mentioned above adding another installation being self contained could let the user choose the installation way

which would solve that specific issue and never rely on a manual instal AFTER a first manual update

**Comment by vbjay** [comment]
It is bootstrapped. As in it runs and says you need x version of the desktop runtime.  Meaning it will install all needed items by causing it to install the needed desktop runtime. When app is built it pulls latest ask and runtime to build the final output. 6.0.13 was that version with the 4.0.2 release. So if you installed the program or ran the portable and did not have 6.0.13 or later of the desktop runtime it would prompt you to install it. This supports both MSI and portable installs along with supporting the fixing if user decides to clean house and uninstall desktop runtime and .net runtime. 

Start the actual program gitextensions.exe and not the program used to launch in current repo. It will walk you through process.

**Comment by RussKie** [comment]
I think you're confusing the SDK and the runtime. The SDK is required to build apps (i.e., compile, debug, package, etc.), whist the runtime is needed to run apps. So, what SDKs you have installed is generally immaterial (though if you have an SDK of the same version of older that the app requires - it would _just work_) to the runtime requirements of the app. At the time of publish we target the latest .NET Desktop runtime available as it carries the latest security and bug fixes.

> I guess one could propose that and also a "lighter install that will require manual update of the SDK before updating gitext" (that seems weird to read)

This is exactly what we're doing. The app tells what version of the runtime you need to install if you don't have it already.

**Comment by tebeco** [comment]
> I think you're confusing the SDK and the runtime
I wish I was. The SDK does install the runtime.
Install VS update the SDK
Updating the SDK, also, uninstall older SDK
Uninstalling an SDK, also uninstall it paired runtime

so yes, updating VS will somehow lead to some runtime gets removed
and depending on which order is done before the result is:
* open terminal
* go to folder
* type in `gitex`
* get welcomed by an error message about `Desktop Runtime` missing (which is one of the runtime that was tied to that SDK that got uninstalled)

@RussKie 

Do you think the GitExtension artifacts could contains both "current way of shipping" and also `self-contained` ?

> > I guess one could propose that and also a "lighter install that will require manual update of the SDK before updating gitext" (that seems weird to read)
>
> This is exactly what we're doing. The app tells what version of the runtime you need to install if you don't have it already.

Well I was wondering about giving both as an alternative for what works best dependings on who use it get to choose what works best on their setup

**Comment by RussKie** [comment]
> so yes, updating VS will somehow lead to some runtime gets removed

It'd be great get more details on this. 

> Do you think the GitExtension artifacts could contains both "current way of shipping" and also `self-contained` ?

It seem like a good value proposition to bundle hundreds of megs of .NET runtime. With trimming and native AOT a self contained app becomes a much better offering, however neither of those are currently available for the .NET Desktop.

**Comment by vbjay** [comment]
Vs removing older runtimes and sdks are not a problem since it also installs the later version. So even if it uninstalls the one we are using the runtime that is is installed will run the app.

**Comment by tebeco** [comment]
You're right it's the opposite.
GitExtensions update before IDE team update the inner SDK/Runtime
I do not install net6.0 SDK or runtime manually, and let the IDE deploy / update it on it own

here is what happen:
* 15/01/2023 => GitExt update (.net 6.0.13)
* 31/01/2023 => Vs Update (still no bump of dotnet runtime)
* 07/02/2023 => Vs Update (still no bump of dotnet runtime)

Running GitEx from either CLI or shortcut will only show the error, and prompt to do a **manual installation**.

![image](https://user-images.githubusercontent.com/2266487/218031686-adecd4bf-0a1b-4ecb-9b42-0761249f5357.png)

**Comment by tebeco** [comment]
cc @RussKie 
I was wrong and inverted the order of updates above in my description.

The idea is that I want, as a developper to avoid having to install the runtime manually when the IDE already comes with the SDK, which install the runtime as part of it.
The biggest issue here is that the IDE does not seems to properly update the runtime ... and that's sad.

Idea:
* release by using the IDE patch version
* allow runtimeconfig.json to bump patch <== this is already the default behavior
* add a warning the user that there's an update if they want to install the runtime on their own

result: will not block the usage of gitextension if relying of Update IDE for dev tool with no additional manual install

please also note that the way the IDE install SDK is now done in a "different way" than the actual manually install (which could result in duplicated runtime installation ?)

![image](https://user-images.githubusercontent.com/2266487/218032980-87b76e03-e18a-4136-a468-20944a4fcf79.png)

I don't even see the Runtime installation from that IDE install due to that setup:
![image](https://user-images.githubusercontent.com/2266487/218033367-950112de-1b3c-4da2-bed7-4afa255f75b5.png)

![image](https://user-images.githubusercontent.com/2266487/218033489-b6b4584c-c19d-4066-ab05-fe098696d274.png)

**Comment by vbjay** [comment]
The latest security fixes from the later runtime will probably trump your wanting to stay in sync. Your confusion of sdk vs runtime is also playing a part. The sdk is what is used to build the output. It is tied to a runtime version but is not a you must have x runtime if compiled under y runtime thing. The runtime can move on. 

Vs deployments have to have a deploy x sdk version freeze to gather all the other dependencies. .net's release timing is a lot shorter. I think you need to adjust your thinking and be ok with bumping a non major version sdk and runtime to latest outside of vs release timing. 

I use the below to stay current. I'll even uninstall older versions after a while. There is even a tool for that https://learn.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows.  

```powershell
choco upgrade dotnet-6.0-sdk -y
choco upgrade dotnet-6.0-runtime -y
choco upgrade dotnet-6.0-windowshosting -y
```
Also sdks and runtimes are installed side by side. So if you have 6.0.12 installed and 6.0.13. Something compiled for 12 will still run on 12. If you removed 12 it would run on 13 or higher if installed.

**Comment by tebeco** [comment]
I might have not understood what you said but it look like you're suggesting a fix that is, as mentioned above, the exact thing this ticket is open for as it should not be asked to the user when you
* just install VS with the option above
* just install gitex
* follow normal Windows/IDE/GitEx update

=> I don't want, if possible, to be forced / go through manual update of the runtime which is a dependency of gitex.
We're sort of the same place as what peer-dependency of npm are. "if you use X version 1 you also need Y version 3423412, we just changed something"

the `runtime` json file have a rollforward policy for for that.
it will use what's installed on the computer, and rollforward the latest patch available on the computer

and as mentionned above, it's already the default value in the `dotnet publish` generated artifact

I also mentionned that I do not want a manually instal since it's supposdly already handled by
* Vs Team
* Windows Update team on LTS

I see 3 or 4 possible outcome here:
* stick to what it is today and continue to possibly force it on the user to update the runtime because windows update and VS update are out of synch, and this issue will persist.
* add a release in the pipeline to have a self-contained product, allowing users to install the same thing but self contained, and have updated
* being more lax on the `patch` part of the SemVer2 and rely on the already existing `rollforward` policy
* possibly add a message to the user informing them that there's a security vuln not patch and that running command X, Y, Z would be better and would continue to make that product work but not blocking the usage of it
![image](https://user-images.githubusercontent.com/2266487/218091789-b1b16720-089b-4cab-9d9e-3a1089ce4228.png)

**Comment by vbjay** [comment]
Sort of. I'm saying your desire will not work. I'm saying frankly that you should be ok with a tool you use installing the right dependency. As mentioned before we do the latest at time of build for a reason. We want latest security and otter reasons updates to be applied.  Embedding the framework bits is not a good idea.  There is nothing with having an older sdk and a newer runtime.

**Comment by RussKie** [comment]
@tebeco I think you're still missing the difference between the SDK and the
runtime.
Updating VS does not necessarily mean you are getting the latest runtime.
(Im not very familiar with the SDK/runtime update in VS. The GA version
definitely carries the latest version, but I'm not sure about "point"
releases.)

.NET is designed for SxS installs (unlike .NET Framework), and if an app
requires a specific version of runtime- you just install it.

We are requiring the specific version because a) it carries latest security
fixes and b) bug fixes in .NET runtime and .NET Desktop runtime.

You can downgrade the runtime version in runtimeconfig.json, however don't
expect us to provide you with support in event the app behaves in
unexpected manner.
