### ISSUE TITLE
Untranslated items in context menu of Tree view

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#10660]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

### Issue description

The context menu of the tree view contains untranslated items.
![image](https://user-images.githubusercontent.com/18039/213440128-2a1359f2-0c33-4495-b87b-a6589a52e65e.png)

### Steps to reproduce

Right-click on an item in the Tree view.

**Comment by gerhardol** [comment]
Try 4.0.2 there are translation updates. 

The translations are completely handled by the community on transifex 
https://explore.transifex.com/git-extensions/git-extensions/

**Comment by mstv** [comment]
A restart of GE might be necessary in order to affect this context menu, after switching the language.

**Comment by shirayuki** [comment]
Upgrading to version 4.0.2, overwriting new translation files, and restarting GE did not resolve this issue.

Translation into Japanese is 100% complete.

**Comment by shirayuki** [comment]
Could you please reopen this issue?
To know where translations came from, I created a dummy translation file and tried it out.
```xml
<trans-unit id="copyContextMenuItem.Text">
    <source>&amp;Copy to clipboard</source>
    <target>copyContextMenuItem.Text</target>
</trans-unit>
```
I have replaced all the target tags in the file, but the English menu items are still displayed.
![image](https://user-images.githubusercontent.com/18039/213830590-26dda27f-256d-4b50-b9d3-28d82ce006ab.png)

**Comment by mstv** [comment]
Could you test #10685 / https://ci.appveyor.com/project/gitextensions/gitextensions/builds/46066767/artifacts, please, @shirayuki?
I hope all translations are loaded now.
BTW: Some of these texts are being changed by #10673.

**Comment by shirayuki** [comment]
> I hope all translations are loaded now.

Most menu items are translated, but "Sort by..." menu items are still not translated.

**Comment by mstv** [comment]
> Most menu items are translated, but "Sort by..." menu items are still not translated.

Thank you for testing. The "Sort by..." values are not translated at all. If this is a matter, open another issue, please.
