### ISSUE TITLE
Version 4.0.2 doesn't run on Windows 11 ARM64

### ISSUE THREAD

**Issue by pcolemannxu** [gitextensions/gitextensions#10674]
### Environment

- GitExtensions version: 4.0.2
- GIT version: 2.38.1.windows.1
- OS version: Version 10.0.22623 Build 22623 **ARM64**
- .NET version: 6 and 7 are both installed

### Issue description

As of version 4.0.2 I can no longer run the gitexe.exe on Windows 11 ARM64. The previous version, 4.0.1 works (although it is noticeably slower than the previous version, and slower than on x64).

Immediately when starting the app I am prompted to install the .Net 6.0 Desktop runtime which is already installed.

### Steps to reproduce

0. Buy a Windows ARM Dev Kit PC
1. Install .NET 6.0 Desktop Runtime v6.0.13 ARM64 version
2. Install GitExtensions version 4.0.2
3. run gitex.exe

RESULT: Prompt appears to install .NET 6.0 Desktop Runtime v6.0.13
EXPECTED: No prompt.

### Did this work in previous version of GitExtensions?

It worked on version 4.0.1

**Comment by RussKie** [comment]
Which exact version  of .NET runtime do you have installed and which
version is the app asking for?

**Comment by pcolemannxu** [comment]
?
PS C:\> dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
PS C:\> dotnet --list-sdks
6.0.405 [C:\Program Files\dotnet\sdk]
7.0.200-preview.22628.1 [C:\Program Files\dotnet\sdk]
PS C:\> gitex browse

Error is: 
"You must install or update .NET to run this application.
Framework: 'Microsoft.WindowsDesktop.App', version '6.0.13' (x64)"

**Comment by RussKie** [comment]
Do you have the x64 or the arm runtime installed?

**Comment by pcolemannxu** [comment]
The arm runtime is installed. I just tried specifically installing the x64 one too and then it worked. I didn't realize it was possible to install both on Windows ARM. Shame it can't use the ARM one as I expect performance would be a lot better. Is it on the roadmap?

**Comment by gerhardol** [comment]
GE is currently x86 (Desktop Runtime x64 to be installed).
A PR exists for aarch64: https://github.com/gitextensions/gitextensions/pull/10649

**Comment by AArnott** [comment]
I'm running 4.0.2 on my Windows 11 arm64 device right now. No problems. Except I'd really like to see an arm64 process instead so that my battery isn't paying for emulation.

**Comment by RussKie** [comment]
We have an open PR that should address this - https://github.com/gitextensions/gitextensions/pull/10649.

**Comment by AArnott** [comment]
Although the PR has merged, per https://github.com/gitextensions/gitextensions/pull/10649#issuecomment-1556100430 it isn't actually _building_ and shipping. One has to build their own arm64 binaries from source. I plan to try adding this myself this week.
