### ISSUE TITLE
Console Tab blank in v4.0.0+

### ISSUE THREAD

**Issue by NZnick** [gitextensions/gitextensions#10678]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13

### Issue description

When switching to the Console tab in an open repository the tab displays a "Starting root process..." message and the keyboard  curser blinks once then disappears. The console tab is then blank and unusable it is as it the root process has failed to start but no error is displayed to indicate this.
![Git Ex Error](https://user-images.githubusercontent.com/29719223/214763683-625d8be2-d93c-4955-9137-c5540a14878d.gif)

Git still runs and text is properly displayed in Git process dialogs (for example when committing or pushing to the repo from the Commit window). 

### Steps to reproduce

1. Open a repository 
2. Open the Console Tab

### Did this work in previous version of GitExtensions?

Yes, it worked before I upgraded to v4

**Comment by mstv** [comment]
I cannot reproduce it with the portable build of v4.0.2. (I had to unblock the ConEmu executable using its popup.)

**Comment by vbjay** [comment]
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file

One idea is we could provide an unblock script to unblock all files in portable folder using $PSScriptRoot.

**Comment by RussKie** [comment]
> I had to unblock the ConEmu executable using its popup

I think I had to unblock ConEmu's binaries few times over the years but the reason why I had to so in some situations and not others was never clear. Unless we understand the root cause I don't think there's anything we can do apart from giving guidance.
