### ISSUE TITLE
[NBug] fatal: bad revision 'aster'

### ISSUE THREAD

**Issue by katrash** [gitextensions/gitextensions#10677]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.13
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --glob=refs/stas[h] aster --
Working directory: C:\Code\CorporateDomains\MsftDomains\

```
GitExtUtils.ExternalOperationException: fatal: bad revision 'aster'
 ---> System.Exception: fatal: bad revision 'aster'
   --- End of inner exception stack trace ---
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { }
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

Try adding a non-existing branch in the branches filter text box.

### Steps to reproduce

Enter a non-existing branch name in the branches filter text box and press the `Enter` key.

**Comment by mstv** [comment]
What do you expect?
Why not press "Ignore" and correct your mistake?

**Comment by katrash** [comment]
I can click ignore, but I expect a normal dialog telling me branch doesn't exist rather than the .NET error handler one

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
