### ISSUE TITLE
Visual glitches in the revision grid when scrolling many lines at a time with mouse wheel

### ISSUE THREAD

**Issue by MaxKoll** [gitextensions/gitextensions#10672]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.13
- DPI 134dpi (140% scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When scrolling the revision grid by 8 lines at a time with mouse wheel, visual glitches appear:
- Some rows are rendered out of place (shifted up or down), leading to duplicate rows and rows that are cut in half. All columns are affected.
- When selecting these out-of-place rows, they are instantly updated and rendered correctly.
- Tooltips don't seem to be affected.
- The glitch occurs nearly always (while scrolling up or down).

Please see this video in which I first scroll down, then select rows:

https://user-images.githubusercontent.com/39014485/214060645-6efe0b1b-dba9-44a5-ba13-5425d04e94c6.mp4

### Steps to reproduce

1. Configure your mouse wheel to scroll 8 lines at a time (Windows Settings > Devices > Mouse). I can reproduce the issue with any value between 6 and 20, but it becomes rare with bigger values and disappears with very big values (≳ 50).
2. With your mouse wheel scroll up or down in the revision grid.

### Did this work in previous version of GitExtensions?

The issue seems to be introduced by 02d5fdb0f57d5236c219f5460b2d7ea1ea56c0f1. I did not observe it with its parent fbb4000a648c9db317e29a344450a9dd672ac725.

**Comment by pmiossec** [comment]
@wischi-chr Any idea?

**Comment by mstv** [comment]
I have seen a similar glitch via a lagging rdesktop connection (WLAN). This was reported before. But I could not find the issue.

**Comment by wischi-chr** [comment]
> @wischi-chr Any idea?

Not from the top of my head, but I'll give it a look and try to set my mouse to scroll 8 lines at a time as @MaxKoll suggested. Maybe I can reproduce and fix it.
