### ISSUE TITLE
can not resume after minimize the main window

### ISSUE THREAD

**Issue by czhang-cpu1** [gitextensions/gitextensions#10689]
### Environment

- GitExtensions version: 4.0.1.15887-f2567dea2
- GIT version: 2.38.1.windows.1
- OS version: Windows 10 Home
- .NET version: 6.0.12

### Issue description

can not resume the windonw after minimize the main window

### Steps to reproduce

1. minimize git extensions
2. try to resume the windows

### Did this work in previous version of GitExtensions?

3.5.4.12724-65f01f399 work ok

**Comment by Pippen19** [comment]
I have the same problem. It occurs relatively rarely for me during normal operation, but as soon as I put the notebook to sleep and restart it later, the problem always occurs.

**Comment by pmiossec** [comment]
Please have a look at this comment: https://github.com/gitextensions/gitextensions/issues/10398#issuecomment-1313349802
