### ISSUE TITLE
Dark Mode Alternative Solutions

### ISSUE THREAD

**Issue by petdumit** [gitextensions/gitextensions#10696]
### Feature description

Since it seems that theming the application is technicaly difficult (see https://github.com/gitextensions/gitextensions/issues/5489),
would it be acceptable to create two separate builds, a light and a dark one? Odd releases light, even releases dark.

Alternatively, just have dark mode, it might be possible that this is the preferred way for most users (I have no hard data on this, but most of the devs I know, including me, use dark mode almost exclusively).

### Environment

- GitExtensions version: 4.x
- GIT version: any
- OS version: Windows 10 Pro
- .NET version: 6.x

**Comment by vbjay** [comment]
Don't think you understand. The hooking needed to skin all the controls does not work.

**Comment by petdumit** [comment]
So there is no way to create an application that looks dark in the new dotnet core? Ok.

**Comment by vbjay** [comment]
Think you need to read https://github.com/gitextensions/gitextensions/issues/9191.

**Comment by RussKie** [comment]
It is not technically possible, see https://github.com/gitextensions/gitextensions/issues/9191#issuecomment-1312614913.
