### ISSUE TITLE
[NBug] Failed to decode the error payloadD:\Program Files (x86)\...

### ISSUE THREAD

**Issue by zhousheng-zser** [gitextensions/gitextensions#10690]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.37.1.windows.1 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.13
- DPI 96dpi (no scaling)

### Issue description

```
System.Exception: Failed to decode the error payload
D:\Program Files (x86)\GitExtensions\BugReporter.dll
 ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at BugReporter.Program.Main()
   --- End of inner exception stack trace ---
```

Click "Submit" to crash directly

### Steps to reproduce

Click "Submit" to crash directly

**Comment by RussKie** [comment]
Did you start the bug reporter directly?

**Comment by gerhardol** [comment]
> Did you start the bug reporter directly?

Seem so. Keep this behavior even if issues like this pops up?

**Comment by RussKie** [comment]
The bug reported isn't meant to be run directly.
