### ISSUE TITLE
Filter with commit hash not working

### ISSUE THREAD

**Issue by amedhatreda** [gitextensions/gitextensions#10693]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.13
- DPI 120dpi (125% scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Previously it was working, but now after the latest updates it stopped working!
I usually search with a commit hash to do 'cherry-pick commit', but the search doesn't display any result now, even I am on the branch that contains the commit that I search with, also, I am displaying all branches.

### Steps to reproduce

Just copy any commit hash you have, and paste it into the search textbox.

### Did this work in previous version of GitExtensions?

Yes, it was working, but I am not sure in which version!

**Comment by pmiossec** [comment]
Already discussed here (You should prefer the "Go to commit' feature...): https://github.com/gitextensions/gitextensions/discussions/10608
