### ISSUE TITLE
File history from Contextual Menu in Windows Explorer shows Empty results 

### ISSUE THREAD

**Issue by olmobrutall** [gitextensions/gitextensions#10705]
### Environment

- GitExtensions version: 4.0.1.15887
- GIT version: 2.38.1.windows.1
- OS version: Windows 11
- .NET version: 6.0.13

### Issue description

This is the filter configuration when executed from a contextual menu in Windows explorer: 

![image](https://user-images.githubusercontent.com/720953/217778389-903e857d-6045-49ab-862b-02f7ed394afb.png)

While this is from the contextual menu in the Tree View inside Git Extensions: 

![image](https://user-images.githubusercontent.com/720953/217779065-01f95b71-ae2f-4e1d-bb93-d46753c85cd5.png)

Note how the Path filter is different

From Windows Explorer Context menu:

```"\"DAW.React/App/DAW/Notifications/NotificationDocument.tsx\""```

From Git Extensions Tree View Context menu:

```"DAW.React\App\DAW\Notifications\NotificationDocument.tsx"```

### Steps to reproduce

In Windows Explorer, right click in a file in a repository and select 

(Show more options ->) Git Extensiosn -> File history

### Did this work in previous version of GitExtensions?

In version 3 it worked.

**Comment by pmiossec** [comment]
Fixed. Please update to v4.0.2
