### ISSUE TITLE
Shift+Enter in a commit message adds vertical tabulator byte into the message

### ISSUE THREAD

**Issue by marbel82** [gitextensions/gitextensions#10724]
### Environment

- GitExtensions version: 4.0.2.16100
- GIT version: 2.39.1.windows.1
- OS version: Windows 11
- .NET version: .NET 6.0.13

### Issue description

When you press Shift+Enter in the Commit window and click Commit, the commit message will contain a vertical tabulator byte (ASCII 0xB).

"123456"

### Steps to reproduce

- Open the Commit window
- Write "123", press Shift+Enter, write "456"
- Commit

Your commit message will be: "123456"

**Comment by mstv** [comment]
I guess you mean 'Shift+Enter'. `Ctrl+Enter` is the hotkey for committing.
Is there anyone who wants to create a pull request for replacing `Shift+Enter` with just `Enter`?

**Comment by vbjay** [comment]
Umm don't hit shift enter. It is literally doing what you told it to.

**Comment by mstv** [comment]
But one does not see the difference in FormCommit.

**Comment by marbel82** [comment]
@mstv You're right, I meant Shift+Enter

**Comment by gerhardol** [comment]
See also discussion in #10409
