### ISSUE TITLE
Dark Theme is missing in Git Extensions 4.0.2.16100

### ISSUE THREAD

**Issue by car00ta** [gitextensions/gitextensions#10733]
### Environment

- GitExtensions version:4.0.2.16100
- GIT version: 2.39.2
- OS version: Win 10
- .NET version: 6.0.14

### Issue description

After updating Git Extensions I cannot set dark theme

### Steps to reproduce

update Git Extension to 4.0.2.16100

### Did this work in previous version of GitExtensions?

Yes

**Comment by gerhardol** [comment]
For technical reasons, dark themes are no more supported in GitExtensions v4. 
Duplicate of #10312

**Comment by car00ta** [comment]
I understand... but is it still a bug
