### ISSUE TITLE
Selecting commit runs `git rev-parse` for every `Co-authored-by` in a commit message

### ISSUE THREAD

**Issue by nickwalkmsft** [gitextensions/gitextensions#10736]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.2.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.14
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

### Issue description

In the GitHub repo I work in, merges often contain many commits, and merge commit messages can be large. These messages typically include a lot of [GitHub's `Co-authored-by` specifiers](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors). In many cases, when inserted by GitHub during certain GitHub actions, the email address in a `Co-authored-by` begins with a numeric GitHub ID. The full line looks like:

`Co-authored-by: Some Person <123456789+username@users.noreply.github.com>`

What I'm seeing is that when I select a commit in the UI, the Git Command Log shows an instance of `git rev-parse --verify --quiet 123456789^{commit}` being run for every such line in the commit message. They all run serially and take ~50-200 ms a piece as indicated by the log. Relatively large merge commit messages in the repo I work in thus hang the UI for a full minute or two every time I select them.

### Steps to reproduce

Select a commit in the UI with a message containing a large number of GitHub `Co-authored-by` lines with numeric-prefix email address values. The main window will become unresponsive for a long period of time.

### Did this work in previous version of GitExtensions?

Not sure.

**Comment by mstv** [comment]
Yes, the `Regex Sha1HashShortRegex = new(@"\b[a-f\d]{7,40}\b"` in `GitRevision.cs` is too generic. It should not match (hex) numbers in e-mail addresses.
It is used by the `CommitDataBodyRenderer.Render()` function only.

In addition, we should consider moving the `UpdateCommitMessage()` call to `StartAsyncDataLoad()`.

**Comment by vbjay** [comment]
Look at revision link settings.

**Comment by mstv** [comment]
@nickwalkmsft, you could use the https://ci.appveyor.com/project/gitextensions/gitextensions/builds/46312717/artifacts when the CI build will have finished.

**Comment by nickwalkmsft** [comment]
@mstv Confirmed no repro in the new build. This is fixed as far as I'm concerned, I'll let you all handle the state of this issue however you like.

Thank you for the quick fix and for the new build! To any of the maintainers who see this: *Thank you for Git Extensions!* It's been my primary interface to git for as long as I can remember, it's saved me so much time and has helped me learn about git as I use it. Sent a contribution your way.

**Comment by mstv** [comment]
Thank you very much, @nickwalkmsft.
