### ISSUE TITLE
[NBug] fatal: bad revision '142480'

### ISSUE THREAD

**Issue by zmaten** [gitextensions/gitextensions#10740]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

Exit code: 128
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=60000 --glob=refs/stas[h] 142480 --
Working directory: C:\src\cb5\

```
GitExtUtils.ExternalOperationException: fatal: bad revision '142480'
 ---> System.Exception: fatal: bad revision '142480'
   --- End of inner exception stack trace ---
   at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefresh)+() => { }
   at async Task GitUI.GitUIExtensions.InvokeAsync(Control control, Action action, CancellationToken token)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

Upon entering part of the branch name "142480" into filtering field and pressing Enter

### Steps to reproduce

Upon entering part of the branch§'s name "142480" into filtering field and pressing Enter

**Comment by RussKie** [comment]
Do you get the same by running the command from the command line?

**Comment by mstv** [comment]
If "142480" was a commit hash, switch to using `Go to commit` (`Ctrl+Shift+G`) or use the quick search (just start typing in the RevisionGrid).
Commit hash are not supported in the filter box any longer.

**Comment by gerhardol** [comment]
When GE sees any errors reported by Git where not expected, it raises this NBug popup.
In this case no error is really expected, the issue is due user information, this is not a valid reference.

In this case I would prefer to not validate the info before git-log: This would delay the showing of commits for every repo opening or refresh with up to several hundred ms (when there is info in the box).

The branch box is dropdown but there is no enforcement that the data is there.
The box can be used for any refs, including sha and tags.

**Comment by zmaten** [comment]
> If "142480" was a commit hash, switch to using `Go to commit` (`Ctrl+Shift+G`) or use the quick search (just start typing in the RevisionGrid). Commit hashes are not supported in the filter box any longer.

No, it's part of the branch name "bugfix/142480"

**Comment by gerhardol** [comment]
You have to select the complete branchname from the dropdown list, it cannot be a partial match.

**Comment by zmaten** [comment]
That's not what you'd expect though, since it it's a textbox you can prompt with 'enter'.  The UX could benefit if at least the user was shown a messagebox explaining how it works. Thus preventing the exception window being shown which people will report again and again

**Comment by RussKie** [comment]
That's a fair feedback, thank you.

A pull-request with improvements in this area are welcome ;)

**Comment by zmaten** [comment]
> That's a fair feedback, thank you. A pull-request with improvements in this area are welcome ;)

I will try to find some time and courage on the weekend :)

**Comment by RichardJFoster** [comment]
To add to @zmaten's comment, I keep on accidentally triggering the same root cause. If I have previously selected a branch from the drop-down, then go to reset the filter to empty (to see all branches), at least 30% of the time I end up accidentally deleting only part of the previous branch name thereby leaving an invalid one which triggers the error.

**Comment by mstv** [comment]
There's a shortcut `Ctr+Shift+i` for resetting the filter.

![image](https://user-images.githubusercontent.com/36601201/223208686-dc0b2359-a36d-464e-88fa-bc55e19f20f9.png)

**Comment by RichardJFoster** [comment]
Thanks for the suggestion @mastv, but that shortcut doesn't appear to be fully operating as expected in Git Extensions 4.0.2.16100. Hitting Ctrl-Shift-I does indeed set the view back to showing all branches, but still leaves the previously selected branch text in the branches drop-down, potentially leaving users with the impression that the filter is still active.

![image](https://user-images.githubusercontent.com/701557/223216196-c6751b17-37f7-400b-b6f9-ffc16ada0b1a.png)

**Comment by mstv** [comment]
Notice the different icon of the filter button, please.

**Comment by RichardJFoster** [comment]
Yes. I took that screenshot _after_ triggering the reset revision filters operation which is why I consider the continued visual presence of the previously selected branch as potentially confusing. If I get a chance  in the near future I'll see if I can provide a PR initialfor it. Also apologies for taking this case on a detour as this is only tangentially related to the underlying case's root cause.

**Comment by mstv** [comment]
The branch filter is kept on purpose: for quick reactivation in the filter dialog

![image](https://user-images.githubusercontent.com/36601201/223238985-a221f61f-3c65-4f4f-927e-31e7f164c80e.png)

**Comment by gerhardol** [comment]
A number of similar issues has occurred recently.
To avoid this exception, add a check that Git finds the revision (git rev-parse is successful) if it is set (it must not be a branch).
This will delay the refresh with a hundred ms or so, but may display a more explanatory popup instead.

**Comment by gerhardol** [comment]
Not sure how to handle this. A popup could be displayed when the data is entered or before git-log runs.

If refs are parsed when entering could use the refs to avoid the common situation that the branch was selected from the list. However, it will possibly add delays when leaving the checkboxes (main toolbar or advanced filter form).
If the refs are parsed when the grid is refreshed, a popup can be shown, but the grid will either have to be empty or the filtering ignored.

![image](https://user-images.githubusercontent.com/6248932/224572145-f20e9e53-dfc0-46d0-a0de-e70b62e044c9.png)

The occurrences where HEAD was referenced are maybe a separate issue with timing within Git. (HEAD must be supplied in a few situations related to ShowCurrentBranchOnly). That can maybe be separately handled. (The implementation use three cooperating threads to speed up the handling, this scenario will make this further complicated...)

**Comment by RussKie** [comment]
> A popup could be displayed when the data is entered or before git-log
runs.

Can we ignore issues if we don't have data (i.e., it's notloaded)?
