### ISSUE TITLE
[NBug] Using username "git".FATAL ERROR: Server refused to start...

### ISSUE THREAD

**Issue by vgary06** [gitextensions/gitextensions#10787]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""PUTTY_LOCATION\PuTTY\plink.exe" -T -P 7999 "TARGET.git""

```
GitExtUtils.ExternalOperationException: Using username "git".
FATAL ERROR: Server refused to start a shell/command
 ---> System.Exception: Using username "git".
FATAL ERROR: Server refused to start a shell/command
   --- End of inner exception stack trace ---
   at async Task<bool> GitUI.Infrastructure.Plink.ConnectAsync(string host)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

After test SSH connection, access has been granted to the repository and SSH works, just got this error message. But whether I load the .key or not, the message will reappear again with the attached error message.

### Steps to reproduce

Test SSH connection with or without the given .key's password. Whether the ssh repository's login has been granted as access or not the message still reappear.

### Did this work in previous version of GitExtensions?

It happens only when I try it in the v4.X GitExtensions program version.

**Comment by vbjay** [comment]
Did you press enter to finish process or close the window?

**Comment by vgary06** [comment]
Yes, of course. I got the access for the SSH, but after that the error appeared again.

**Comment by vbjay** [comment]
That error message is expected. They don't launch a shell on login or the shell they launch is no login or bin/false or something of that sort. Basically that error is not an actual error. So just ignore.

**Comment by vgary06** [comment]
I don't think so, because last time when I'd tested out the SSH connection of the repository, it worked and got the same "Access granted" message but no error popped out with the v3.X GitExtensions. I started happenning with version 4.X or above.

**Comment by vbjay** [comment]
Please just test again pressing enter in window that pops up. We now expose errors that were swallowed earlier.

**Comment by vgary06** [comment]
![image](https://user-images.githubusercontent.com/19833624/223704309-3e994f55-5303-42d0-ab21-4f06be895bd0.png)

I pressed enter again, it said Access Granted then closed the terminal, then this message popped out.

**Comment by vbjay** [comment]
Do you not understand that it is telling you that no sfell started which is correct. It is not an error. But the non zero result of the process is being exposed. It is an error that is a non error bjistvif orw the error.

**Comment by vbjay** [comment]
Do you not understand that it is telling you that no sfell started which is correct. It is not an error. But the non zero result of the process is being exposed. It is an error that is a non error bjistvif orw the error.

**Comment by vgary06** [comment]
Alright, then it's an error message of non-error... will close the issue then.
