### ISSUE TITLE
[NBug] Using username "gitolite".^C

### ISSUE THREAD

**Issue by lzh79** [gitextensions/gitextensions#10789]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.2.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.14
- DPI 96dpi (no scaling)

### Issue description

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""C:\Program Files\PuTTY\plink.exe" -T "gitolite@iizuna.rdd.soliton.co.jp:smartonid/smarton-log-client""

```
GitExtUtils.ExternalOperationException: Using username "gitolite".
^C
 ---> System.Exception: Using username "gitolite".
^C
   --- End of inner exception stack trace ---
   at async Task<bool> GitUI.Infrastructure.Plink.ConnectAsync(string host)
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { }
```

I can pull the source code by the same URL with SourceTree(V3.4.12) in the same environment.

### Steps to reproduce

I clicked "Open pull dialog..." in the Pull icon's popup menu, and clicked "Manage remotes" button, and clicked "Test connection". when I closed command prompt window, I got this issue.

When I pull the source code by clicking Pull icon, I got the following error.
"C:\Program Files\Git\bin\git.exe" -c fetch.parallel=0 -c submodule.fetchJobs=0 pull --progress "origin"
fatal: protocol error: bad line length character: gito
Done

I tried SoruceTree(V3.4.12). SourceTree can pull the source code from the same repository in the same environment.

**Comment by mstv** [comment]
"^C" indicates that you hit `Ctrl+C`.
What happens if you hit `Enter`, "exit", `Enter` instead?

**Comment by lzh79** [comment]
The prompt window showed and asked password. I used Putty and I have a pkk file, so I do not need to enter anything. I just closed the prompt window. Using username "gitolite".^C error message showed.

**Comment by vbjay** [comment]
Which results in a non zero exit code of that process. You need to point putty executables in settings if incorrect. Also adding key file in remote helps.

**Comment by lzh79** [comment]
I checked  the putty executables in settings. It is correct. I also added key file in the Pageant Key List. When I tried to pull source code from the repository, I got "fatal: protocol error: bad line length character: gito" error.

**Comment by vbjay** [comment]
Ge will drive pagent for you. Open remote settings and put key file path in it.  Stop pagent. Then do a fetch all and watch pagent start and load key.

**Comment by lzh79** [comment]
I have checked the 'Private key file' setting for PuTTY SSH in the 'Remote repositories' window, and it is correct. It loads the correct ppk file, and I can use this file to pull source code from the same repository using SourceTree. I have always used this ppk file in the past to pull source code from the same repository using Git Extensions, but now there is an error and I cannot pull it.

**Comment by vbjay** [comment]
Can you pull ge repo and debug it? I'm wondering if we have some stupid username check or some encoding issue. Since you are having the problem you are the best one to track down where the problem is.

**Comment by lzh79** [comment]
No, I don't know how to debug it, and I don't have time this month. If you could tell me how to debug it, I'm willing to give it a try next month.

**Comment by RussKie** [comment]
The build instructions are here: https://github.com/gitextensions/gitextensions/wiki/How-To%3A-build-instructions
