### ISSUE TITLE
uninstall seems to not have removed specific keys in .gitconfig

### ISSUE THREAD

**Issue by RedjV** [gitextensions/gitextensions#1079]
Hello,

maybe I am to blame for this bug, as I've installed / uninstalled in a short period of time a lot of git tools: TortoiseGit, GitHub for windows, Git Extensions (not necessarily in that exact order), to finally settle on the official Git for windows, so there may have been a mixup somewhere.

While using the official git, I encountered an error when trying to do a rebase -i. It failed to launch "C:/Program Files (x86)/GitExtensions/GitExtensions.exe" as the default editor. It couldn't work, as git extensions was uninstalled.

I then tried to list global options and saw a few lines that were created, I think, by Git Extensions:

``` merge.tool=kdiff3
mergetool.kdiff3.path=C:/Program Files (x86)/KDiff3/kdiff3.exe
diff.guitool=kdiff3
difftool.kdiff3.path=C:/Program Files (x86)/KDiff3/kdiff3.exe
core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
```

Maybe there were other lines, I didn't investigate further. My fix was to uninstall official Git, remove all .gitconfig\* files from my user folder, then re-install official Git.

I think the uninstall of G.E. should remove the specific lines from the conf files, or at least ask the user what to do with it.

My best regards
R.

**Comment by mithlesharya** [comment]
$ git config --global --list
merge.tool=kdiff3
diff.guitool=kdiff3
core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
user.email=you@example.com
