### ISSUE TITLE
Distinguish tags which are only local from the ones on the remote

### ISSUE THREAD

**Issue by andreaskakramer** [gitextensions/gitextensions#10790]
### Feature description

Hi,

it would be nice to be able to easily see whether a tag is local or whether it was already pushed.
Currently the color coding does not show this difference:
![image](https://user-images.githubusercontent.com/78435250/223374251-c872123c-1145-4c5a-a548-c16ca8e455e5.png)

A colorcoding similar to branches would be great. 
To distinguish it from branches tags could use the inversion of the filling and font color.

Same color coding should be used in the sidebar as well.

### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.13
- DPI 120dpi (125% scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by gerhardol** [comment]
For tags, there is no "remote" concept, you will have to query the remote, like `git ls-remote --tags` (or  `git push --tags --dry-run` to only find tags on local repo not pushed to the remote, seem to be slower too).
So this will require a query to all remotes, which will delay the refresh comparable to a git getch command. Of course, this could be done async and use some caching, but it will be quite complex. Some users will be annoyed be the extra network, so it should be off by default, so it would be a niche feature.
If implemented, it should probably handle branches on the remote (not the same as remote branches), too and inform about changes.

Unless someone really wants this, I suggest this request is closed, I do not see it as a reasonable feature.
