### ISSUE TITLE
dotnet tool install GitExtensions

### ISSUE THREAD

**Issue by hickford** [gitextensions/gitextensions#10800]
Hi. Consider packaging and publishing Git Extensions as a [.NET tool](https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools).  This is a convenient way for users to downlod and install software.

    dotnet tool install GitExtensions

Examples of .NET tools: https://www.nuget.org/packages?q=&frameworks=&tfms=&packagetype=dotnettool&prerel=true&sortby=relevance

**Comment by RussKie** [comment]
Could you please elaborate what experience this would facilitate?

**Comment by hickford** [comment]
@RussKie  it's just a convenient way to install and update .NET apps that works cross platform.

**Comment by RussKie** [comment]
I'm well aware what .NET tools are. I don't understand how those relate to
Git Extensions and what end-user experience they would offer.

**Comment by vbjay** [comment]
> @RussKie  it's just a convenient way to install and update .NET apps that works cross platform.

GE latest is not XPlat.
