### ISSUE TITLE
Application crash and close immediately after push tag to origin

### ISSUE THREAD

**Issue by ikomangmahendra** [gitextensions/gitextensions#10811]
### Environment

- GitExtensions version: 4.0.2.16100
- GIT version: 2.38.1.windows.1
- OS version: Windows 10 Microsoft Windows NT 10.0.22621.0
- .NET version: .NET 6.0.15

### Issue description

Application crash and close immediately after push tag to origin 

### Steps to reproduce

1. Create a new tag and fill out the tag name
2. Tick checkbox Push tag to 'origin'
3. Select dropdown 'Annotated tag'
4. Copy paste message from text editor e.g. Notepad++
`
Release 1.5.0

- some description
- some description
`

### Did this work in previous version of GitExtensions?

Absolutely yes, I just upgrade it to the latest version because of suggestion update popup from Git Extention application to download it

**Comment by RussKie** [comment]
I was unable to repro this:
![image](https://user-images.githubusercontent.com/4403806/226567357-e1309914-4f05-4f70-b67e-94b7475f14f0.png)
![image](https://user-images.githubusercontent.com/4403806/226567238-9f0bb31a-f6fd-4b6b-bd1e-06665a718b99.png)

Please check Event Viewer for any stack traces.
