### ISSUE TITLE
GitExtension BitBucket Plugin hyperlink not working since version 4

### ISSUE THREAD

**Issue by deedob** [gitextensions/gitextensions#10817]
### Environment

- GitExtensions version: 4+
- GIT version: 2.40.0
- OS version: Win 10

### Issue description

In the BitBucket Server Window from the Bitbucket plugin,

Clicking on the hyperlink for a Pull Request at the bottom of the screen used to open the default browser directly.
Left-clicking on it no longer does anything since version 4 (it worked up until 3.5.4 as far as I can tell).

Right-clicking the link still copies the link to the clipboard.

### Steps to reproduce

Left click on a Pull Request hyperlink in the BitBucket Server window.
The default browser used to open automatically.

### Did this work in previous version of GitExtensions?

3.5.4

**Comment by pmiossec** [comment]
I think it's fixed by  #10727.
could you test the portable dev build to verify?

**Comment by gerhardol** [comment]
Working in master
