### ISSUE TITLE
Use native WSL Git executables also for \\wsl.localhost as for \\wsl$

### ISSUE THREAD

**Issue by txdFabio** [gitextensions/gitextensions#10815]
### Feature description

With Windows 11 the `\\wsl$` path is automatically translated in `\\wsl.localhost` and that path change makes unusable this PR merged in the v4.0: [#9702](https://github.com/gitextensions/gitextensions/pull/9702)
It would be great to add the check also for the new path so that Gitext can use WSL executables in both versions

### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.15

**Comment by RussKie** [comment]
@txdFabio as a workaround you can change the path in Windows Explorer back to `\\wsl$\`. That's what I've been doing. 

@gerhardol that's the answer to your offline question ;)

**Comment by txdFabio** [comment]
> @txdFabio as a workaround you can change the path in Windows Explorer back to `\\wsl$\`. That's what I've been doing.
> 
> @gerhardol that's the answer to your offline question ;)

I tried but if I use the right-context-menu command "GitExt Open Repository" in the directory it still takes \\wsl.localhost (messing up alla files with permissions and poor performance)
The only workaround I've found is to open the repo from "GitExt -> start -> open" and then adjust the path in the form before opening.

**Comment by RussKie** [comment]
I double checked, and it's working for me as intended...

**Comment by RussKie** [comment]
I think we could intercept when a repo is opened from `\\wsl.localhost\` and modify the path to `\\wsl$\`. 
I observe the path change whenever I start VS Code from wsl2 (which starts with `\\wsl$\`) and then choose "Reveal in Explorer" - the Explorer will open a folder as `\\wsl.localhost\`.
