### ISSUE TITLE
'Show current branch only' no longer shows only the current branch

### ISSUE THREAD

**Issue by MattIans** [gitextensions/gitextensions#10872]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.15

### Issue description

When selecting to filter branches by using "Show current branch only" or by manually entering the branch name to filter it, the tree view no longer only shows this branch.  It now takes you to the last commit in the tree view.

This has made it nearly impossible to perform git actions on an individual branch because the tree view does not actively filter out other commits and provide a clear view of the branch that is targeted.

<img width="843" alt="git-extensions-bug-show-current-branch" src="https://user-images.githubusercontent.com/78673372/231302169-3b4ba2f0-5748-43eb-8ee1-1b564bc9f692.png">

### Steps to reproduce

Filtering
1. Open Git Extensions
2. In the Branches: dropdown box, enter the branch you want to filter
3. Observe this branch is not the only one shown.  It highlights the last commit on this branch.

Show this branch only
1. Right click on any branch and select "show this branch only"
2. Observe same as above.

### Did this work in previous version of GitExtensions?

Yes.  Unsure of the version I updated from.  This used to filter the tree view to show only the selected branch.

**Comment by gerhardol** [comment]
The branch filters will now (as before) show all commits that are seen from the selected head.
If you select the currently checked out branch in the branches box, that is the same as Current branch.

You probably used Only first parent before.

**Comment by MattIans** [comment]
Hey Gerhardol, my apologies you are right, that button was deselected and selecting it lets it behave as it was for me before.  Closing this now.

For anyone else reading, this is the button:

![image](https://user-images.githubusercontent.com/78673372/231305158-027f7951-9d35-47b6-b8a1-7c153fed024b.png)
