### ISSUE TITLE
English label fix

### ISSUE THREAD

**Issue by 1Jesper1** [gitextensions/gitextensions#10888]
### Environment

- Git Extensions 4.0.2.16100
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.16

### Issue description

![image](https://user-images.githubusercontent.com/4539406/232476874-2826726e-b3ac-44a2-b77f-c12e29183167.png)

### Steps to reproduce

Open Git Extensions

### Did this work in previous version of GitExtensions?

I think so.

**Comment by 1Jesper1** [comment]
PR https://github.com/gitextensions/gitextensions/pull/10889/commits/9abc779648e59af0fafef5f7bd765b375b87954e Could be more labels which need to be fixed.

**Comment by gerhardol** [comment]
Closed in #10890
