### ISSUE TITLE
Not all stashes shown in revision grid

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#10894]
### Environment

- Git Extensions 33.33.33
- Build 8b83cfe279dd8e299293a0a22c7b38d3a64e28c1
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

`-c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --exclude=refs/notes/commits --all --`
does not list stashes which are based on ref-log-only commits.

### Steps to reproduce

- checkout a commit as detached HEAD
- commit something
- change something
- stash the changes
- checkout a branch
- optionally create another stash
- see stash visibility state in left panel

**Comment by gerhardol** [comment]
That is as expected, reflog has to be shown.
(We discussed this at the implementation, explicitly showing latest stash only).

You can double click the hidden stashes to see the contents (as before, but you get right to them.)

All stashes could be shown, but this will affect the revision loading some.
