### ISSUE TITLE
Anytime I double click a file trying to enter the single file page, the page is frozen

### ISSUE THREAD

**Issue by renfengyue** [gitextensions/gitextensions#10895]
### Environment

- GitExtensions version: 4.0.2.16100
- GIT version: 2.38.1.windows.1
- OS version: Microsoft Windows NT 10.0.19044.0
- .NET version: 6.0.16

### Issue description

I double click on a file and try to go to the management page for a single file and then the page acts like it's frozen, no response from the page when I click on it.

### Steps to reproduce

I went into GitExtensions and opened any of the projects. I double clicked on any source file on the "File tree" page at the bottom right and I was taken to the management page for that file. I try to click on the file's history, but the page doesn't respond, it seems the page is frozen.

### Did this work in previous version of GitExtensions?

In version 3.x, it works well.

**Comment by vbjay** [comment]
https://www.screentogif.com/

Show us.

**Comment by pmiossec** [comment]
>Show us.

👍 

It could be a perf issue displaying the blame for file with big history (and loading avatars). Some things have been fixed on that. Test the dev version. If you could test it also and report if it improves/fixes the issue...
