### ISSUE TITLE
GitExtensions.exe fails silently on start

### ISSUE THREAD

**Issue by nforss** [gitextensions/gitextensions#10897]
### Environment

- GitExtensions version: 4.0.2.16100
- GIT version: 2.39.0.windows.2
- OS version: Windows 11
- .NET version: windowsdesktop-runtime-7.0.5 (x64 and x86)

### Issue description

Today, I am no longer able to start GitExtensions. It fails silently, and in Event Viewer the following error appears.

I've tried reinstalling GitExtensions, as well as every possible version of .NET runtime (desktop and otherwise), but no change.

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
    <System>
	<Provider Name=".NET Runtime" /> 
	<EventID Qualifiers="0">1023</EventID> 
	<Version>0</Version> 
	<Level>2</Level> 
	<Task>0</Task> 
	<Opcode>0</Opcode> 
	<Keywords>0x80000000000000</Keywords> 
	<TimeCreated SystemTime="2023-04-19T08:19:35.4492410Z" /> 
	<EventRecordID>26672</EventRecordID> 
	<Correlation /> 
	<Execution ProcessID="23964" ThreadID="0" /> 
	<Channel>Application</Channel> 
	<Computer>XXXXXXXX</Computer> 
	<Security /> 
    </System>
    <EventData>
	<Data>Description: A .NET application failed. Application: GitExtensions.exe Path: C:\Program Files (x86)\GitExtensions\GitExtensions.exe Message: Failed to create CoreCLR, HRESULT: 0x80004005</Data> 
    </EventData>
</Event>
```

### Steps to reproduce

-

### Did this work in previous version of GitExtensions?

It worked fine the day before yesterday, without any changes to my system that I know of. Maybe there was a Windows update in the background?

**Comment by RussKie** [comment]
Have you restarted your workstation?

**Comment by nforss** [comment]
Yes, twice.

**Comment by RussKie** [comment]
Do you have .NET 6 installed?

**Comment by nforss** [comment]
> dotnet --list-runtimes
Microsoft.AspNetCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by RussKie** [comment]
> `<Data>Description: A .NET application failed. Application: GitExtensions.exe Path: C:\Program Files (x86)\GitExtensions\GitExtensions.exe Message: Failed to create CoreCLR, HRESULT: 0x80004005</Data> `

This indicates there's some kind of environmental issue on your workstation. Are you using a portable version of GitExtensions or an installed from an msi? Does it work if you launch the app as administrator?

**Comment by nforss** [comment]
It's installed from an .msi, and as stated, it was working fine a few days ago. Same (non)result when I run as admin. 

I'm also guessing there's something that's changed in the environment because the GitExtensions install itself hasn't changed, but I have no idea what it could be. Hoping someone here might have some insights.

**Comment by RussKie** [comment]
Are you able to run other .NET Windows Desktop apps?

**Comment by vbjay** [comment]
Questions:

- other dotnet apps work still
- repairing .or uninstalling and reinstalling net and .net desktop runtime installers resolves issue after a reboot
- try to find .net 6 version of https://www.microsoft.com/en-us/download/details.aspx?id=30135. @RussKie any ideas on this one

**Comment by RussKie** [comment]
> * try to find .net 6 version of [microsoft.com/en-us/download/details.aspx?id=30135](https://www.microsoft.com/en-us/download/details.aspx?id=30135). @RussKie any ideas on this one

That looks like .NET Framework related. .NET is separate from.NET Framework, and generally can be just re-installed from https://dotnet.microsoft.com/download.

At this point I don't see any actions from our side, so closing.

**Comment by vbjay** [comment]
Thanks @RussKie wasn't sure if there wasn't a .net version of the tool or the installer did  fixup or what.  I knew that was framework. Why I said a .net 6 version of it. Good to know the installer should resolve issues.

**Comment by nforss** [comment]
Installing the newest [.NET 6 Desktop runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.16-windows-x64-installer) version seems like it fixed the problem, thanks for the tip! Not sure why the 7 version didn't work, or whatever happened to the old install, but at least I got it running. 👍

**Comment by vbjay** [comment]
> Not sure why the 7 version didn't work,

Brcause ge is compiled with .net 6 and not 7.

**Comment by gerhardol** [comment]
You had .NET 6 Desktop installed, which should have been sufficient.

> Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Maybe that install was corrupted?

**Comment by nforss** [comment]
> You had .NET 6 Desktop installed, which should have been sufficient.
> 
> > Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
> 
> Maybe that install was corrupted?

Must have been something like that. I also would have assumed .NET 7 was backwards compatible, but there you go... Live and learn, I guess!

**Comment by RussKie** [comment]
Whilst the .NET  team takes the backwards compatibility seriously there's
no any kind of guarantee against breaking changes in major versions.
