### ISSUE TITLE
AppVeyor test hang

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#10909]
### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

The issue is intermittent by is occurring often enough for builds to fail due to time out.
E.g.:
* https://ci.appveyor.com/project/gitextensions/gitextensions/builds/46860411
* https://ci.appveyor.com/project/gitextensions/gitextensions/builds/46848570
* https://ci.appveyor.com/project/gitextensions/gitextensions/builds/46843473

 I've logged on to the box and it appears the Commit dialog related tests hang:
![image](https://user-images.githubusercontent.com/4403806/233817543-e888b015-015c-4419-8dcb-1199d15b7d15.png)

### Steps to reproduce

N/A

**Comment by RussKie** [comment]
I was able to grab a memdump before the VM shutdown, and I _think_ I know what the issue is - we're attempting to update UI elements from a background thread:
![image](https://user-images.githubusercontent.com/4403806/233820415-0fb2a112-3b23-4910-9683-16c33e8af532.png)

**Comment by mstv** [comment]
Fixed by #10910

**Comment by RussKie** [comment]
Thank you @mstv. I totally forgot that the GitHub would autoclose if a fix was in the master branch.
