### ISSUE TITLE
Minimize the windows，and then try to click application，but it can't recover the window。

### ISSUE THREAD

**Issue by iwannajingjing** [gitextensions/gitextensions#10913]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Minimize the window，and then try to click application，but it can't recover the window。

### Steps to reproduce

Minimize the window，and then try to click application，but it can't recover the window。
![微信截图_20230425143110](https://user-images.githubusercontent.com/46618661/234193426-b8488b2a-bcf9-4cf4-9b1b-748c6917205f.png)

**Comment by pmiossec** [comment]
Fixed and will be released in v4.1
