### ISSUE TITLE
Git config setting "core.autocrlf" is not updated after selecting source "Effective" again

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#10917]
### Environment

- Git Extensions v4.0.2 / 33.33.33
- Build be087f852f799476badc2220bd86c64ad1c74c0b
- Git 2.40.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Git config setting "core.autocrlf" is not updated on switching settings sources since selecting source "Effective" again

![grafik](https://user-images.githubusercontent.com/36601201/234284646-0cf4ed67-6310-48df-8eae-e4596426d59f.png)

### Steps to reproduce

- configure "core.autocrlf" globally different from "Not set"
- apply
- configure "core.autocrlf" to "Not set" for local repo
- apply
- reopen Settings
- click "Local for current repository"
- click "Effective" -> wrong
- choose other sources -> no update

### Did this work in previous version of GitExtensions?

not checked

### Diagnostics

```
$ git config --show-origin core.autocrlf
file:%HOME%/.gitconfig    false
```

**Comment by mstv** [comment]
This is caused by `SetNullableEnum<T>()` saving `null` as an empty string in the `ConfigFileSettingsCache` instead of removing the entry (as it is correctly done by `ConfigSection.SetValue()`).

**Comment by RussKie** [comment]
Is this one resolved?

**Comment by mstv** [comment]
Yes, it is. But GH did not notice it although it has been merged to the main branch.
