### ISSUE TITLE
Cannot Alt-Tab back to the application

### ISSUE THREAD

**Issue by brianjlacy** [gitextensions/gitextensions#10921]
### Environment

- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.36.0.windows.1 (recommended: 2.38.1 or later)
- Microsoft Windows NT 10.0.22621.0 (Windows 11 Pro)
- .NET 6.0.16

### Issue description

Frequently, when the Git Extensions window loses focus in Windows (i.e., I switch to another app), and then I try to Alt-Tab back to it, I get the system "bing" sound that _usually_ means a dialog is open (but there's no dialog open), and I cannot get back to the app.

If I hover on the icon on the taskbar, the app comes into view, but as soon as I click the icon to switch to the window, it hides again. This happens even if nothing else is open on my desktop.

### Steps to reproduce

It's inconsistent, unfortunately. Sometimes, by hovering over the taskbar icon for a few seconds, it seems to start working again. But more often than not it doesn't help. Recently I've discovered that if I open a new instance of Git Extensions, sometimes the existing instance will start allowing me to switch back to it.

### Did this work in previous version of GitExtensions?

Yes, I don't recall this happening before the last time I upgraded. I do not recall which version I last had installed, however.

**Comment by pmiossec** [comment]
Seems another side effect of #10398. See the issue for a kind of configuration workaround
Mostlt fixed in #10802 to be included in next release
