### ISSUE TITLE
`CommitMessageManager` blocks UI thread

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#10926]
### Environment

- Git Extensions 4.2.0.16609
- Build 76f14e6c102e91355910b3e28a5b093d6add765e (Dirty)
- Git 2.39.2.windows.1 (recommended: 2.40.0 or later)
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0-preview.2.23128.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The issue is very prominent working with repos located in WSL. Various operations in the Commit dialog lock the dialog (and the app). I've taken various memdumps, and all of those seem to be blocked at the same line:
![image](https://user-images.githubusercontent.com/4403806/235292598-1566e99c-fec0-4e2d-992c-2f9c1e91fd18.png)
![image](https://user-images.githubusercontent.com/4403806/235292619-45bbc9cb-5e2b-4152-a303-c88edde85b81.png)

### Steps to reproduce

Try to commit in a WSL2 repo.

### Did this work in previous version of GitExtensions?

IDK

**Comment by gerhardol** [comment]
This is after Commit (possibly with push) is pressed. There are checks if you amend, that the commit is not empty etc that cannot be performed before and that may need user response. 
Do you want ConEmu that is cancellable here?

**Comment by RussKie** [comment]
The issue is observable in several forms/scenarios. I'm working on this.
