### ISSUE TITLE
"Current branch only" doesn't work for headless checkout

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#10939]
### Environment

- Git Extensions 4.1.0.16666
- Build dd6b150c547f815e8e0e9d74f252d2cf7416e3d5 (Dirty)
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0-preview.2.23128.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

https://user-images.githubusercontent.com/4403806/236095521-3a7b29b7-2acf-4355-99c3-d7a209dba0ed.mp4

Now we're always running:
```
git -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --exclude=refs/notes/commits --all --
```

### Steps to reproduce

1. Checkout headless (e.g., use "Checkout this commit only" from the context menu)
2. Try to filter to the current branch only.

### Did this work in previous version of GitExtensions?

Yes, it works in 4.0.x version:
![image](https://user-images.githubusercontent.com/4403806/236095722-4ddc2c8e-06a2-4ddc-8e91-339c5fd5d863.png)

```
git -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --max-count=100000 --glob=refs/stas[h] HEAD --
```

**Comment by RussKie** [comment]
@gerhardol this looks like a regression introduced in #10799.

**Comment by gerhardol** [comment]
If there is no branch checked out, there is no branch to filter so the behavior in master is correct.
HEAD is not set in bare repos, so the draft PR will fail occasionally.

**Comment by RussKie** [comment]
> If there is no branch checked out, there is no branch to filter so the behavior in master is correct. 

A branch is just a label, so if there's a commit one should be able to only see its history. So I disagree on the correctness assessment. It's also a regression.

**Comment by gerhardol** [comment]
> > If there is no branch checked out, there is no branch to filter so the behavior in master is correct.
> 
> A branch is just a label, so if there's a commit one should be able to only see its history. So I disagree on the correctness assessment. It's also a regression.

Still, there is no current branch so I believe the current handling is the correct.

If you need to have have something similar to the previous (that do not create exceptions), the current commit must be used, not HEAD.

**Comment by mstv** [comment]
> I believe the current handling is the correct.

It may be literally correct. But it is not what most of the users expect I guess.
 
> If you need to have have something similar to the previous (that do not create exceptions), the current commit must be used, not HEAD.

👍
