### ISSUE TITLE
VS Code should launch with --new-window

### ISSUE THREAD

**Issue by sharwell** [gitextensions/gitextensions#10942]
### Environment

- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.0-rc.1.21451.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.0-rc.2.21501.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0-preview.3.23178.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Currently the editor command to open VS Code is `code --wait`. If VS Code is already open with a workspace, this will attempt to reuse that workspace and the `--wait` may fail. Adding the `--new-window` argument to this will resolve the problem.

### Steps to reproduce

1. Open a workspace in VS Code
2. Set the Git editor option to "Visual Studio Code --wait"
3. Attempt to rebase interactively

Visual Studio Code will attempt to reuse the existing workspace. If the workspace is trusted but the temporary location used for the interactive rebase file is not trusted, Visual Studio Code will fail when attempting to re-launch the file in a new restricted editor window.

### Did this work in previous version of GitExtensions?

Not known.

**Comment by gerhardol** [comment]
The request is to change the defaults for Git editor.
The command can be changed manually, it is just a suggestion

I was struggling to realize where code was integrated (there is also some non default GE Scripts that use Code).

![image](https://user-images.githubusercontent.com/6248932/236259016-9e0ebee5-cf5d-44d5-9f40-1f4b54fbdc04.png)

**Comment by RussKie** [comment]
I believe, it's defined here:
https://github.com/gitextensions/gitextensions/blob/b119a06010332203a74ab8e08301a8fc32663322/GitUI/CommandsDialogs/SettingsDialog/EditorHelper.cs#L29-L32

@sharwell if you send a PR quickly, we could ship this in v4.1.
