### ISSUE TITLE
Update Links to SignPath

### ISSUE THREAD

**Issue by SabotageAndi** [gitextensions/gitextensions#10965]
### Environment

GitHub Readme.md

### Issue description

Hi!

I am the Developer Evangelist of SignPath.
Sorry if I am using the wrong issue template. This was the best match I found for my request.

Could you change the links to `signpath.io` to `https://signpath.io/?utm_source=foundation&utm_medium=github&utm_campaign=gitextension` in your Readme.md?

If you want, I can submit a PR for this.
Thanks!

### Steps to reproduce

-

**Comment by RussKie** [comment]
If you can send a PR, it'd be great. Thanks.
