### ISSUE TITLE
Cannot switch to another theme in version - Git Extensions 4.1.0.16698

### ISSUE THREAD

**Issue by std-oshchur** [gitextensions/gitextensions#10989]
### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

![image](https://github.com/gitextensions/gitextensions/assets/94523577/29ad7c4b-9b76-4583-aac8-03b2e510484a)

### Steps to reproduce

Windows 11

Go to Tools -> Settings -> Expand "Appearance" -> Colors:
In "Theme" section try to change the theme to another one
Restart the app
Note, that theme is not changed at all

### Did this work in previous version of GitExtensions?

It worked for me in version 4.0

**Comment by RussKie** [comment]
No, it couldn't have possibly worked for you in v4 since the theming
support was removed in that version due to technical limitations in .NET
Runtime.
This has been explicitly called out in the changelog
https://github.com/gitextensions/gitextensions/releases/tag/v4.
