### ISSUE TITLE
Squash merge returns fatal error

### ISSUE THREAD

**Issue by Irinabert** [gitextensions/gitextensions#10992]
### Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET Framework 4.8.4614.0

### Issue description

Hello!

I tried to do merge squash using Get Extensions and I run into the problem

![image](https://github.com/gitextensions/gitextensions/assets/74787163/c1f61be0-96b8-44cd-b82b-c95a6815154a)

### Steps to reproduce

- checkout the branch you would like to merge into
- right click on branch you would like to merge
- select merge option
- tick advanced options
- tick "Squash commits"
- click "Merge"
- you will see the error

### Did this work in previous version of GitExtensions?

Don't know

**Comment by vbjay** [comment]
So turn off no ff and do the merge. They are incompatible flags. 

https://stackoverflow.com/a/14322024

**Comment by Irinabert** [comment]
Thank you for replying. But I am confused. The link you sent explaining the difference, but I know that they are not compatible features. Problem is that there is no option to turn "no ff" off. Or at least I can't see it. Which is also can be improved from the usability point of view. 
![image](https://github.com/gitextensions/gitextensions/assets/74787163/a87474b4-14c7-44be-bb1f-c31b0b1f3b65)

**Comment by mstv** [comment]
The GE UX can be improved: We should disable "Always create a new merge commit" in case of squashing.

For the time being, just switch to "Keep a single branch line" manually, @Irinabert.

![image](https://github.com/gitextensions/gitextensions/assets/36601201/8b865553-99dc-41bc-bb6b-c6d3fa6966d1)

**Comment by IlijaQ** [comment]
Hi,
I have improved the user interface (UI) as @mstv  suggested. I have prepared a pull request for review.
