### ISSUE TITLE
Sometimes impossible to switch between multiple instances

### ISSUE THREAD

**Issue by matthiaslischka** [gitextensions/gitextensions#10990]
### Environment

- GitExtensions version: 4.0.2.16100

### Issue description

Quite often I have the problem that I can't switch between multiple instances of GitExtensions. The other instance would just not show and I only hear a Windows error sound (ping).

### Steps to reproduce

- Open two instances of GitExtensions.
- Open a repo in both instances.
- Press Win + D so show Desktop
- Use Group in Windows bar to try to switch between the instances
  - works for first
  - shows second on hover but does not open second on click...

I'm not sure if this is a local problem only for me or not. Reproduction steps are flaky.

Sometimes this works, most times it does not and I get an Windows error sound (ping) when I click on the second instance. Hope this gif helps to understand what I mean:

![d7e184d2-4802-4edf-ae23-0c2af1e8e8a5](https://github.com/gitextensions/gitextensions/assets/12046115/eb646bb9-1635-44e3-b653-f5b2101a3c26)

Curious if other have the same issue.

**Comment by pmiossec** [comment]
Normally fixed in v4.1. Please update.
