### ISSUE TITLE
warning: git-credential-manager-core was renamed to git-credential-manager

### ISSUE THREAD

**Issue by eng-marani** [gitextensions/gitextensions#11001]
### Environment

- GitExtensions version: 4.1.0.16698
- GIT version: 2.40.1
- OS version: Win10 22h2 latest
- .NET version: 6.0.16

### Issue description

I'm flooded by this warning messages into push/pull logs. How do i remove them ?

**warning: git-credential-manager-core was renamed to git-credential-manager
warning: see https://aka.ms/gcm/rename for more information**

I have found no clear indications anywhere on how to get rid of this warning, and gitextension options checker give me full green lights

### Steps to reproduce

Just pulling something

### Did this work in previous version of GitExtensions?

The warning appearedseveral month ago, probably due to a change into Git/credential manager

**Comment by pmiossec** [comment]
It's a git install issue and gitextensions has no action on that.
Everything is written in the link provided in the warning message.
But I think it could be sum up to uninstall then reinstall git.
