### ISSUE TITLE
Make integration test `SplitterPositionsShouldBeRestored` pass on AppVeypor

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11017]
### Environment

- GitExtensions version: 4.1.0

### Issue description

Since #10968, this test passes only when executed locally.

### Steps to reproduce

Enable `SplitterPositionsShouldBeRestored` and trigger an AppVeyor build.

### Diagnostics

`leftPanelVisible: false`: Expected ta.RevisionsSplitContainer.SplitterDistance to be 535, but found 525.
`leftPanelVisible: true`: Expected ta.RevisionsSplitContainer.SplitterDistance to be 787, but found 525.

**Comment by RussKie** [comment]
@mstv is this still relevant?

**Comment by mstv** [comment]
The testcase has not been disabled but reworked in the final #10968.
