### ISSUE TITLE
[Feature request] Natural sort order of branch and tag names 

### ISSUE THREAD

**Issue by prime167** [gitextensions/gitextensions#11028]
### Feature description

We have a lot of sustomized branches named with version, can GE natural order branches (and tags) ?
![image](https://github.com/gitextensions/gitextensions/assets/3722845/bba04cf8-5add-4893-821d-9bb3e74b580f)

Fork 1.85:

![image](https://github.com/gitextensions/gitextensions/assets/3722845/c5d8aa34-ad3a-4e81-973e-c8b71351effd)

Files in Windows Explorer (ordered by name):

![image](https://github.com/gitextensions/gitextensions/assets/3722845/d5d4f533-701d-4616-b760-0e7f75a35a11)

### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False

**Comment by gerhardol** [comment]
Sort is done by Git. You may ask for a semver sort order in core Git.

GE is in mostly a gui for Git, modified Git behavior is avoided.

**Comment by prime167** [comment]
I just found git support this by 
`git branch -a --sort=v:refname`
It can be put into config 
```

[tag]
	sort = v:refname
[branch]
	sort = v:refname
```

but GE GUI not read this config

**Comment by gerhardol** [comment]
Try Git default sorting

**Comment by gerhardol** [comment]
Branches and tags are retrieved with git-for-each-ref, so the key tag.sort is not used. I see no relevant config key for for-each-ref.

Actually, `version:refname` can be used as a sortkey. 
https://git-scm.com/docs/git-for-each-ref#Documentation/git-for-each-ref.txt-contentslinesN

However, it behaves differently and cannot be used as the secondary key to sort dereferenced tags. Maybe it is OK to sort these on `objecttype` instead.
I will try a private patch.

**Comment by gerhardol** [comment]
@prime167 Can you please test the portable in #11038?
