### ISSUE TITLE
GitExtensions really should not be taking over git commands without user consent

### ISSUE THREAD

**Issue by Maoni0** [gitextensions/gitextensions#11045]
### Environment

- GitExtensions version: I downloaded this zip - GitExtensions-Portable-4.1.0.16698-1fe52a137.zip
- GIT version: 2.41.0.windows.1
- OS version:  Windows 11
- .NET version: 6,0,1623,17311 @Commit: 1e620a42e71ca8c7efb033fd525f04be5fa701fe

### Issue description

I downloaded  GitExtensions-Portable-4.1.0.16698-1fe52a137.zip and used GitExtensions.exe from the unzipped dir. my intent was to just use the UI app that way. nothing more. I thought the way I'm using would achieve that. but apparently even running just that exe make GitExtensions take over the git commandlines itself so now if I do "git rebase" it becomes "GitExtensions.exe fileeditor c:;/myrepo/.git/rebase-merge/git-rebase-todo". so I deleted the unzipped dir and now rebase is giving me an error because it still tries to find GitExtensions -

```
hint: Waiting for your editor to close the file... "C:/GitExtensions/GitExtensions.exe" fileeditor: line 1: C:/GitExtensions/GitExtensions.exe: No such file or directory
error: There was a problem with the editor '"C:/GitExtensions/GitExtensions.exe" fileeditor'.
```

if I'm only using GitExtensions from an unzipped dir (instead of installing it with an .msi) it should never take over git commands like this and especially not in a way that it would actually break existing git commands if I deleted the directory. 

### Steps to reproduce

download .zip
unzip to a dir
use GitExtensions.exe from there - I clicked ok the first time GitExtensions UI came up. did NOT repair anything.
now in a cmd, try to do a git command and observe that it's running by GitExtensions.exe

### Did this work in previous version of GitExtensions?

didn't try

**Comment by pmiossec** [comment]
Git needs an editor to be configured to do some operations.
So the real question is: did you have a file editor configured before using GitExtensions?

Because if you had one, indeed gitextensions has no right to change the value.
But if you have none, gitextensions has the right to update the config to ensure everything will work fine.

And also I wonder if it's not you that changed the config by clicking on 'repair' on the settings form that is normally displayed the first time you run gitextensions...

Czn you confirm because I don't remember well how the portable version is working on that?

**Comment by Maoni0** [comment]
I was using notepad.exe as my editor for years. did I config it or did git just use the system editor? I honestly don't remember 'cause it's been so long. 

> I wonder if it's not you that changed the config by clicking on 'repair' on the settings form that is normally displayed the first time you run gitextensions

that I really can't say - I did click ok without reading as the person who asked me to install Gitextensions told me to click ok 😅 I did not think it would cause this kind of situation to happen or I would have refused to click on before reading what the page said.

assuming I didn't config the editor and did let gitextensions "repair' this option (it's quite misleading to call this a repair action because nothing is broken so it shouldn't be changed in the first place), what's the clean way to "uninstall" gitextensions in this case?

**Comment by Maoni0** [comment]
sorry I didn't read your msg very carefully . I can confirm that I **definitely** did NOT click on repair anything at all. I just clicked ok  when gitextensions started the first time.

**Comment by mstv** [comment]
eeeee

**Comment by mstv** [comment]
GE creates `C:\Users\%USER%\.gitconfig` with 
```
[core]
	editor = \"C:/the_path/GitExtensions-Portable-4.0.0.13607-42e4029da/GitExtensions.exe\" fileeditor
```
if ![check settings at startup](https://github.com/gitextensions/gitextensions/assets/36601201/9a17838e-c4da-4cb2-b215-62cc7b03ee4b) is set.

**Comment by Maoni0** [comment]
wonderful! I changed it back to notepad. thank you so much @mstv!
