### ISSUE TITLE
Add option to clean submodules

### ISSUE THREAD

**Issue by samwebster** [gitextensions/gitextensions#11054]
### Feature description

It would be very handy if you could clean (not reset) all submodules (recursively) from git extensions. It's just one more tick box on the Commands->Clean working directory (or two if you want to control whether it is recursive or not). I think the relevant script is `git submodule foreach --recursive git clean -xfd`

### Environment

All
![clean](https://github.com/gitextensions/gitextensions/assets/13457618/ceb18fe0-c021-44ec-9706-e3c33a7136e1)

**Comment by RussKie** [comment]
The option to update or reset submodules is available in the context menu
in the Commit form. If you select all submodules the requested operation
will be executed for all selected.

You can also write a custom script to do the same. Check under Settings >
Scripts.

**Comment by samwebster** [comment]
This isn't about reset but clean. It's just one more tick box on the Commands->Clean working directory (or two if you want to control whether it is recursive or not)

**Comment by RussKie** [comment]
That's the context that was missing from your origin post. Please update the post providing the full context of what you think is missing from the app. Screenshots can be helpful too.

**Comment by samwebster** [comment]
@RussKie  Done. Thanks

**Comment by RussKie** [comment]
Thank you.

Setting up for grabs. Pull requests are welcome.

**Comment by NatRavenhill** [comment]
I have been having a look at this, and have a question. Would the cleaning of submodules take place after the initial clean command, when the Cleanup button is pressed?

**Comment by vbjay** [comment]
Yes and it would be a simple `git submodule foreach --recursive  git clean <args>`. With args passed in like original clean args and recursive being optional. It is not hard to add a script that does this.

**Comment by RussKie** [comment]
> Yes and it would be a simple `git submodule foreach --recursive git clean <args>`. With args passed in like original clean args and recursive being optional. It is not hard to add a script that does this.
> 
> What about exclusions like all but x submodule? This is where a script in the repo folder that does the work for master repo and the subs with but I don't want x repo because... is handled.

I think for the purpose of this dialog executing `git submodule foreach --recursive  git clean <args>` should suffice. Anything more advanced could/should be handled by users themselves.

Personally, I've never used this dialog, typing `git clean -xdf [-e <path>]` is much faster for me.

**Comment by NatRavenhill** [comment]
I've had a go at implementing this - never worked on the repo before, so any feedback would be awesome! 🙂

**Comment by RussKie** [comment]
I'll have a look but it'll  probably be next week.
