### ISSUE TITLE
Cannot Find Revision

### ISSUE THREAD

**Issue by mmclemens** [gitextensions/gitextensions#11065]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.18
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions
```
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Not able to see latest commit (804a57ae0c8f54c). View is set to "Show all Branches" without using "Advance filter...".

![2023-06-20_163508](https://github.com/gitextensions/gitextensions/assets/25713310/bcd9c8eb-b453-4926-a3fd-7af15dc702cd)

![2023-06-20_160915](https://github.com/gitextensions/gitextensions/assets/25713310/99c9de83-08e2-4576-b67a-52723d706ab7)

Git Extensions version tree works fine in other repos. gitk and git log show the latest commit as well:
```
E:>git log --pretty=oneline --graph --decorate --all
*   804a57ae0c8f54c. (HEAD -> main, tag: v1.15, origin/main, origin/develop, manifest-rev)
|\
| * 5ffee2f520ce90e. (origin/feature/westimprove) add the zip execution variab
| * 9c538b883f00954. Update .current-measure-ci.yml: changed stage's and job's
:
| * 8b5458771a1e4a4. Update .integrationstests-ci.yml: add an other job "files
| *   0cef18224cd18dc. Merge branch 'feature/test_depend' into 'feature/westim
| |\
| | * d178a769be1c7ee. Feature/test depend
| |/
| * da5f3c6cbdf9f35. Update ROW_product_unit_test.bat
| * 6c0643a32a2e74d. Update NA_product_unit_test.bat
:
| * ce15dc2cd6602bb. Update CallFirmwareUpdate.bat
| * e42904a5299b2c1. Update GitlabBuildAndMeasureCurrent.bat: remove this vari
| *   98c89d00b7797fc. Merge branch 'feature/ggtest' into 'feature/westimprove
| |\
| | * 677e22c1b0e21ee. Feature/ggtest
| |/
| * 49179cc2ed29c39. remove unneccessary code
| * 7271db78b25b79e. remove the option "need", beacause the task-firmwareupdat
:
| * 6f3f5e86895c1b2. Update GitlabWestCache.bat
| * 0ee881621660a3f. add script so that if possible to check the current tag o
* | 7484f5266fb898a. (tag: v1.14) Build v1.14
|/
* dac3c3376987dd7. (tag: v1.13, origin/feature/autofirm) Update GitlabWestCach
*   4335d0f5c6f7f76. Merge branch 'feature/autofirmtest' into 'feature/autofir
|\
| * 195831e5e589d28. Feature/autofirmtest
|/
:
```

![2023-06-20_162526](https://github.com/gitextensions/gitextensions/assets/25713310/31ca047b-a369-47b9-a079-58ec4bd95bf9)

### Steps to reproduce

This is perplexing since Git Extensions is working fine in other project repo. Just selecting "Navigate" | "Go to commit...", and use latest commit (804a57ae0c8f54c). Result is a dialogue box "Cannot find revision", "Revision "804a57ae" is not visible in the revision grid. Remove the revision filter."

**Comment by mstv** [comment]
I have seen this, too, but not with already visible commits.
Workaround: Refresh (hit `F5`) and be patient until loading has progressed far enough or even finished.

**Comment by RussKie** [comment]
> 
> ![2023-06-20_163508](https://user-images.githubusercontent.com/25713310/247262430-bcd9c8eb-b453-4926-a3fd-7af15dc702cd.png)
> 
> ```
> E:>git log --pretty=oneline --graph --decorate --all
> *   804a57ae0c8f54c. (HEAD -> main, tag: v1.15, origin/main, origin/develop, manifest-rev)
> |\
> | * 5ffee2f520ce90e. (origin/feature/westimprove) add the zip execution variab
> | * 9c538b883f00954. Update .current-measure-ci.yml: changed stage's and job's
> :
> | * 8b5458771a1e4a4. Update .integrationstests-ci.yml: add an other job "files
> | *   0cef18224cd18dc. Merge branch 'feature/test_depend' into 'feature/westim
> | |\
> | | * d178a769be1c7ee. Feature/test depend
> | |/
> | * da5f3c6cbdf9f35. Update ROW_product_unit_test.bat
> | * 6c0643a32a2e74d. Update NA_product_unit_test.bat
> :
> | * ce15dc2cd6602bb. Update CallFirmwareUpdate.bat
> | * e42904a5299b2c1. Update GitlabBuildAndMeasureCurrent.bat: remove this vari
> | *   98c89d00b7797fc. Merge branch 'feature/ggtest' into 'feature/westimprove
> | |\
> | | * 677e22c1b0e21ee. Feature/ggtest
> | |/
> | * 49179cc2ed29c39. remove unneccessary code
> | * 7271db78b25b79e. remove the option "need", beacause the task-firmwareupdat
> :
> | * 6f3f5e86895c1b2. Update GitlabWestCache.bat
> | * 0ee881621660a3f. add script so that if possible to check the current tag o
> * | 7484f5266fb898a. (tag: v1.14) Build v1.14
> |/
> * dac3c3376987dd7. (tag: v1.13, origin/feature/autofirm) Update GitlabWestCach
> *   4335d0f5c6f7f76. Merge branch 'feature/autofirmtest' into 'feature/autofir
> |\
> | * 195831e5e589d28. Feature/autofirmtest
> |/
> :
> ```
> 
> ![2023-06-20_162526](https://user-images.githubusercontent.com/25713310/247251505-31ca047b-a369-47b9-a079-58ec4bd95bf9.png)
> 

The first screenshot doesn't look comparable to the git output and the second screenshot, so you _do_ have some kind of filtering enabled in the app. Something like "first parent"....

**Comment by mmclemens** [comment]
Below are snapshots of the Git Extensions "View" and "Advanced filter" configuration; nothing obvious preventing the view of the latest commit. Are there any git commands that could be executed to help identify what filter might be enabled that is causing this behavior?
 
![2023-06-21_074410](https://github.com/gitextensions/gitextensions/assets/25713310/22999748-7798-4fea-af2a-2b2918d69702)
![2023-06-21_074503](https://github.com/gitextensions/gitextensions/assets/25713310/55b69a49-2935-4b88-aa2d-9cbdc59c417d)

**Comment by pmiossec** [comment]
The default in "Branch filter" is to have "Merge commits" checked.
So  you are hiding merge commits and it your case, your commit (the last in main) is a merge commit.

**Comment by mmclemens** [comment]
@pmiossec thanks so much for the clarity of the solution you have provided.

**Comment by gerhardol** [comment]
Note: When "Merge commits" is unselected, the icon for the filter is changed:
![image](https://github.com/gitextensions/gitextensions/assets/6248932/0bc0df8e-55ee-4838-8023-eebcebff0db1)

`Merge commits` is the primary filter that is selected by default. This setting could be reversed to `No merge commits` instead, also to align with Git better.
 https://git-scm.com/docs/git-log#Documentation/git-log.txt---no-merges

Related settings:

`Show reflog` will add commits.
https://git-scm.com/docs/git-log#Documentation/git-log.txt---reflog

`Full history` and the dependent `Simplify merges` (should not be ticked by default) controls some simplification options. Slightly separate.
https://git-scm.com/docs/git-log#Documentation/git-log.txt---full-history
https://git-scm.com/docs/git-log#Documentation/git-log.txt---simplify-merges
