### ISSUE TITLE
File History window: last commit is hidden under action bar

### ISSUE THREAD

**Issue by radist-nt** [gitextensions/gitextensions#11071]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.39.0.windows.2 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.19
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions
```
    Microsoft.WindowsDesktop.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

File History window's action bar hides the very first commit in the commits area.

**Expected behavior:**
The last commit is showed on the first line below the action bar. User is able to select that commit with mouse click.

**Actual behavior:**
The last commit is hidden by the action bar. User can select that commit by clicking the previous commit and pressing UP key.
The selection is slightly visible, but it's not possible to read any data from that line.
![screenshot](https://github.com/gitextensions/gitextensions/assets/15953267/8049641c-5c79-4eec-b800-f87e2ea07066)

### Steps to reproduce

1. Settings: Git Extensions -> Detailed -> Browse repository; uncheck parameters "Show file history in the main window" and "Show blame in diff viewer"
2. Select any frequently modifier file from File Tree, press `H` or select "View history" from context menu
3. On commits area in File History window uncheck the following items in context menu -> View: "Show artificial commits", "Show stashes" (this is need to make the problem obvious)

### Did this work in previous version of GitExtensions?

I think, it worked in 3.5.x versions, 
The bug wa noticed after upgrading to 4.0.2

**Comment by mstv** [comment]
Nudging, advertising workaround: 😉

![image](https://github.com/gitextensions/gitextensions/assets/36601201/0c125e20-81b2-4e5b-85d4-9866cee95afc)

**Comment by radist-nt** [comment]
> Nudging, advertising workaround: 😉

Thank you, but NO! Convenient window splitter layout for brosing file history and for browsing repository history are completely different. Also, sometimes I need to open several history windows (and I want to distinguish them from the main window).
When developers will decide to remove File History window, I'll just stop updating.

**Comment by mstv** [comment]
> Convenient window splitter layout for brosing file history and for browsing repository history are completely different.

We might consider storing a separate set of splitter positions. Which layout do you prefer?

>  I need to open several history windows (and I want to distinguish them from the main window).

Just open multiple histories using the hotkey `H`.

The title bar is different, and the Left Panel is hidden automatically.

![image](https://github.com/gitextensions/gitextensions/assets/36601201/0961c169-8c15-4cf3-9843-1e8979096a5f)
