### ISSUE TITLE
git config file cant be loaded by eclipse eGit

### ISSUE THREAD

**Issue by mmoayyed** [gitextensions/gitextensions#1107]
Loading git projects that are previously managed by Git Extensions results in eGit throwing the error that it cant read the config file in the git directory of the project. I am not sure if this is an egit issue yet, but once I remove the config file, it's perfectly able to recognize the git project. 

Are there any inconsistencies in the way git extensions create the config file to manage branches, etc?

**Comment by mehdan** [comment]
For me the problem is resolved by changing encoding to UNIX UTF-8
