### ISSUE TITLE
Support for AWS git-remote-codecommit

### ISSUE THREAD

**Issue by dburtsev** [gitextensions/gitextensions#11079]
### Feature description

We are using AWS CodeCommit as our git server. For security reason we should use git-remote-codecommit on top of git.
https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-git-remote-codecommit.html
The new git clone command should look like this: git clone codecommit://MyDemoRepo my-demo-repo

### Environment

- GitExtensions version: latest
- GIT version: latest
- OS version: Windows 10
- .NET version: 6.x

**Comment by gerhardol** [comment]
So that would be to allow the protocol `codecommit:` in addition to https:/ssh:?

**Comment by dburtsev** [comment]
In replacement of https:/ssh:
This is a regular git call: git clone https://git-codecommit.us-east-1.amazonaws.com/xxx/repos/MyDemoRepo c:\local_repo
This should be a new git call using git-remote-codecommit: git clone codecommit://MyDemoRep c:\local_repo

**Comment by mstv** [comment]
GE is able to run such a command. But the called Git itself does not understand it:

![image](https://github.com/gitextensions/gitextensions/assets/36601201/a4ee19dc-9ae7-43d3-80b1-0624bd83f4dc)

```
"C:\Program Files\Git\bin\git.exe" clone -v --recurse-submodules --progress "codecommit://git-codecommit.us-east-1.amazonaws.com/xxx/repos/MyDemoRepo" "D:/Build/DemoRepo"
Cloning into 'D:/Build/DemoRepo'...
git: 'remote-codecommit' is not a git command. See 'git --help'.
```

So you should request support for this protocol on https://git-scm.com/community.
We can reopen this issue then if the support by GE should be improved.

**Comment by gerhardol** [comment]
> git: 'remote-codecommit' is not a git command. See 'git --help'.

The python script must be in the path Git uses (global PATH?)

**Comment by dburtsev** [comment]
Yes, in the path
In my case, it is:
C:\ProgramData\anaconda3\Lib\site-packages
C:\ProgramData\anaconda3\Scripts
C:\ProgramData\anaconda3
