### ISSUE TITLE
Windows Darkmode issues

### ISSUE THREAD

**Issue by dsk80004** [gitextensions/gitextensions#11073]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.39.2.windows.1 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When using window's built in dark mode along side the high contrast dark mode theme many visual effects break.
![image](https://github.com/gitextensions/gitextensions/assets/48543299/b48b9ce2-f1a1-4314-850e-5cb9f1127614)

![image](https://github.com/gitextensions/gitextensions/assets/48543299/1f5299f9-8ec0-4b58-85b5-e0183cc432d0)

### Steps to reproduce

turn on dark mode on both windows and Gitextensions.

**Comment by gerhardol** [comment]
Only with High Contrast setting

![image](https://github.com/gitextensions/gitextensions/assets/6248932/2bc19f14-d33b-444d-84a8-e17d9bb7c381)

**Comment by RussKie** [comment]
Theming is not supported in v4.x due to the underlying .NET limitations.
