### ISSUE TITLE
Feature Proposal better context menu in Edit control.

### ISSUE THREAD

**Issue by MarekKnapek** [gitextensions/gitextensions#11072]
### Feature description

When I'm creating new commit in GitExtensions, there is an Edit window control to type the commit message into.  Sometimes I write a word that is specific to the project I'm working on, but this word is not in dictionary, thus is underlined red. I don't want to make typo in this word next time I'm making a commit, so I would like to add it to the dictionary. Or, when I make a typo, I want to fix it.

 - Right mouse button click on the word displays pop-up menu with suggested fixes and with option to add the word to the dictionary.
 - Mousing over the word and pressing the menu key on keyboard (between right alt and right ctrl) will do the same action.
 - So far so good, but:
 - Having the mouse cursor somewhere in nowhere, navigating the text cursor into the middle of the word and pressing the menu key on keyboard will display different pop-up menu. In this menu there is no option to add this word into dictionary and there is no options to fix the word.

### Environment

- GitExtensions version: Latest at the time of writing this suggestion, 4.1.0.16698.
- GIT version: 2.40.1.windows.1.
- OS version: Microsoft Windows NT 10.0.20348.0.
- .NET version: 6.0.16

**Comment by mstv** [comment]
> Having the mouse cursor somewhere in nowhere, navigating the text cursor into the middle of the word and pressing the menu key on keyboard will display different pop-up menu. In this menu there is no option to add this word into dictionary and there is no options to fix the word.

The popup is opened at the mouse position, which is inexpedient.

---

Furthermore, the cursor is not set when right clicking.

**Comment by IlijaQ** [comment]
Hi,

I have prepared a draft pull request for review.
