### ISSUE TITLE
Current branch line not fully colored when overlapping with other branches

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#11098]
### Environment

- Git Extensions 33.33.33
- Build 8b5eab531dcc849d00110df6f9797a096e68b500
- Git 2.35.1.windows.2 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.19
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The line representing the current branch fails to get colored in certain circumstances when it overlaps with other branch lines.

Actual behavior
![image](https://github.com/gitextensions/gitextensions/assets/18039/7193c0e2-0c7c-4661-99ed-7d88865b01f7)

Expected behavior (version 4.1)
![image](https://github.com/gitextensions/gitextensions/assets/18039/f86e5267-b432-4fe2-8c46-835e64112df3)

~~I have prepared a screenshot for the "Expected behavior", but I couldn't provide a screenshot for the "Actual behavior" as the reconfiguration of the development environment is still pending. I apologize for the inconvenience. I will provide the "Actual behavior" screenshot at a later date.~~

### Steps to reproduce

1. Create multiple branches.
2. Commit to each branch in a specific order.
3. Encounter a scenario where the line representing the current branch overlaps with other branch lines, causing some parts of the current branch line to remain uncolored.

### Did this work in previous version of GitExtensions?

Yes, it was working correctly in version 4.1.

**Comment by gerhardol** [comment]
This is being changed, please add the exact commit that you are using.
(It is not even clear to see that this is a dev version for normal users.)

**Comment by shirayuki** [comment]
I have identified the specific revision where the bug was introduced.
The oldest revision that can reproduce the bug is e81679075b0d7fdb2ac48b4341a9692086a0987b.

**Comment by mstv** [comment]
Good catch! Thank you.
