### ISSUE TITLE
Add clickable URL support to console window

### ISSUE THREAD

**Issue by emtony** [gitextensions/gitextensions#11097]
### Feature description

When pushing from TortoiseGIT to a gitlab repo the server will reply with a URL that allows you to open a merge request. 

In the Git Extensions console window the URL appears but it's not clickable, it just appears as plain text. It would be nice if any URLs in the console window could be clickable.

### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.19
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.28 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by gerhardol** [comment]
left-ctrl shows url, then click opens the url

This is a feature in ConEmu: https://conemu.github.io/en/FileLineDetector.html

In ConEmu standalone, you can change left-ctrl to <no-mod> have this setting by default (not sure if changing the modifier can be done in the embedded ConEmu used in GE).

**Comment by emtony** [comment]
Thanks, that works really well. I couldn't find any settings to make it the default but it's not a big problem to just use left-ctrl when I need to do that.
