### ISSUE TITLE
Gitlab pipelines build plugin

### ISSUE THREAD

**Issue by e-stadnik** [gitextensions/gitextensions#11104]
### Feature description

I'd like to implement and contribute this plugin. At this moment I have a working prototype in my personal repo.
https://github.com/e-stadnik/gitextensions/tree/GitlabIntegration
Will be happy for any feedback and suggestions.

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET Framework 4.8.9167.0
- DPI 144dpi (150% scaling)

**Comment by vbjay** [comment]
Create a pull request from your repo's branch to gitextensions/gitextensions/master branch. Put this issue # in the fixes line.

**Comment by e-stadnik** [comment]
Pull request is attached and ready for review.
https://github.com/gitextensions/gitextensions/pull/11105
