### ISSUE TITLE
Provide "natural" sorting of tags in side panel

### ISSUE THREAD

**Issue by andreaskakramer** [gitextensions/gitextensions#11110]
### Feature description

Currently the sorting of tags is done in a alphabetical order:
![image](https://github.com/gitextensions/gitextensions/assets/78435250/0af7fb28-826f-48c0-a93a-3b3d3df09712)

This leads to a unintuitive order of the tags:
3.19.0
3.1.0
3.2.0

It would be nicer if it could be sorted more "natural" like this:
3.1.0
3.2.0
3.19.0

See https://en.wikipedia.org/wiki/Natural_sort_order

### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.20
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pmiossec** [comment]
Fixed by  #11038 (waiting to be released)
