### ISSUE TITLE
Add confirmation for checkout with double click

### ISSUE THREAD

**Issue by pascal-g-shift** [gitextensions/gitextensions#11116]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.20
- DPI 120dpi (125% scaling)
- Portable: False

### Issue description

By default double-clicking on a branch will check it out without warning.
I have found that it often happens when selecting a branch and double-clicking inadvertently.
If you have no uncommitted changes then you can wait for the checkout to complete and checkout back to the branch you were on or abort and clean up the mess in the files.
There should be a confirmation dialog.

### Steps to reproduce

Double-click a branch in the list

**Comment by gerhardol** [comment]
Personally, I would find it annoying to confirm this non destructive action.
There are too many configuration possibilities in GE already, so an added setting would be lost.

**Comment by pascal-g-shift** [comment]
> Personally, I would find it annoying to confirm this non destructive action. There are too many configuration possibilities in GE already, so an added setting would be lost.

Thank you for taking the time to review. Even if the action is "non-destructive" I have the choice of letting it run its course - my repo has hundreds of projects so checkout takes a while - or abort and clean up the mess. Then I have 2 or 3 instances of the IDE complaining and asking about reloading. It may be non destructive but still a pain... There is a search feature in the settings so that they don't get lost.

**Comment by RussKie** [comment]
I suppose, this can be considered an accessibility issue. 

A pull-request adding an opt-in configuration option is welcome.
![image](https://github.com/gitextensions/gitextensions/assets/4403806/759aac47-3e63-4657-a918-18f47881bcf5)

**Comment by IlijaQ** [comment]
Hi Team,

I have prepared a draft PR for your review.
