### ISSUE TITLE
[NBug] Exit code: -1073741510

### ISSUE THREAD

**Issue by eli-b** [gitextensions/gitextensions#11165]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 6.0.21
- DPI 192dpi (200% scaling)
- Portable: False

### Issue description

Exit code: -1073741510
Command: C:\Program Files\Git\cmd\git.exe
Arguments: add --patch "file_based_dynamic_parameters.h"
Working directory: D:\AT_Prj\AT_Src\FO, AnC\

```
GitExtUtils.ExternalOperationException
 ---> System.Exception
   --- End of inner exception stack trace ---
   at async Task<bool> GitCommands.GitModule.AddInteractiveAsync(GitItemStatus file) in C:/projects/gitextensions/GitCommands/Git/GitModule.cs:line 1907
   at async void GitUI.CommandsDialogs.FormCommit.interactiveAddToolStripMenuItem_Click(object sender, EventArgs e)+(?) => { } in C:/projects/gitextensions/GitUI/CommandsDialogs/FormCommit.cs:line 3351
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { } in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 41
```

I closed the window that was opened when I clicked "interactive add" and then received this error.

### Steps to reproduce

-Go to the commit window
-Right-click a file
-Choose "Interactive Add"
-Close the window that opens

**Comment by mstv** [comment]
Using the`X` button means killing the started git process. The window can silently be closed by entering `q` or even by hitting `Ctrl+C`.
In cases of opening interactive external commands, we should ignore exceptions with HRESULT -2146233088.

**Comment by RussKie** [comment]
Exit Code 0xC000013A (-1073741510) means that the application terminated as a result of a CTRL+C or closing command prompt window.

> In cases of opening interactive external commands, we should ignore exceptions with HRESULT -2146233088.

Yes, the suppression is desirable. Why -2146233088 though?

**Comment by mstv** [comment]
> Why -2146233088 though?

The process was killed by clicking the close button of the console host.
