### ISSUE TITLE
Wiki Application Dependencies page is out of date

### ISSUE THREAD

**Issue by jons-bakerhill** [gitextensions/gitextensions#11195]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.38.1.windows.1 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.20
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

https://github.com/gitextensions/gitextensions/wiki/Application-Dependencies#git still lists the recommended version as 2.23.0

### Steps to reproduce

None needed

**Comment by gerhardol** [comment]
updated

**Comment by jons-bakerhill** [comment]
Minimum was updated but just below that there is still a "Recommended Git version: 2.23.0" line.

**Comment by pmiossec** [comment]
> Minimum was updated but just below that there is still a "Recommended Git version: 2.23.0" line.

@gerhardol I would write 'Not too old. See "Settings" checklist inside the application to get the exact recommended version'

**Comment by gerhardol** [comment]
Rewrote the recommendations and minimum checks.

Recommended is what GE maintainers will work the best, which is at least the general available version available before a release.
Minimum version is when GE maintainers know that are not supported.
