### ISSUE TITLE
Encoding CRLF in commit messages

### ISSUE THREAD

**Issue by tbkvamme** [gitextensions/gitextensions#11209]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.21
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When I press SHIFT + ENTER when writing commit messages, then weird encoding happens. 
I aboslutely ❤️ GitExtensions, but this is causing me quite some frustration because it appears badly formatted when commit messages are shown in GitHub. So I need to take special care to check my commits, cause this is appearantly a habit of mine (to use SHIFT + ENTER). 

If it's working as intended, then maybe it could become a Setting to treat SHIFT + ENTER and only ENTER equally in the commit dialog?

GIF:
![responsiveness](https://github.com/gitextensions/gitextensions/assets/404164/fbeabb15-ecea-4960-acaf-7236916466d2)

### Steps to reproduce

Type message in commit dialog and use SHIFT + ENTER instead of only ENTER.

### Did this work in previous version of GitExtensions?

This wasn't an issue in GitExtension v3. I noticed it when i switched to v4

**Comment by pmiossec** [comment]
In next release: fixed by #11171 and #11020
