### ISSUE TITLE
FormCommit: Reset unstaged file resets the staged changes, too

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11216]
### Environment

- GitExtensions version: vNext since #10980 6434e770fa9d4389e66fcaa5b22d3fce204fa9c6

### Issue description

In FormCommit, resetting an unstaged file resets the staged changes of this file, too - as the confirmation dialog states.
This is unexpected though, particularly because it works well with the artificial commits in FormBrowse.

![image](https://github.com/gitextensions/gitextensions/assets/36601201/6c595f28-1d49-4c41-a8b3-b4b8baa44e71)

![image](https://github.com/gitextensions/gitextensions/assets/36601201/d11b8c1c-33df-4e0a-9536-b635bfe74e37)

### Steps to reproduce

- stage some of the changes to a file
- select this file in the unstaged area
- reset changes

### Did this work in previous version of GitExtensions?

yes
- Git Extensions 4.1.0.16654
- Build 6084cf43185d40298ccdb63dadbefdfe7165e274
- Git 2.42.0.windows.1

**Comment by RussKie** [comment]
We should definitely fix this before the next release.

**Comment by gerhardol** [comment]
The reset was changed to always reset when the handling was supported to reset files with special status (silently ignored before 4.0, after that raising exceptions). I recall something about special handling in RevDiff as the other status is not seen there.

**Comment by RussKie** [comment]
Is there something we can realistically fix?

**Comment by gerhardol** [comment]
Closed in #11307
