### ISSUE TITLE
[NBug] error: Could not read 57eb1d2165d47714f7428ffc66db2b7441285...

### ISSUE THREAD

**Issue by petrf22** [gitextensions/gitextensions#11212]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.16
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

```
System.Exception: error: Could not read 57eb1d2165d47714f7428ffc66db2b74412856c4
fatal: Failed to traverse parents of commit 4a53c2b7952ca3921aa778a29ed93b253e828b0b
```

Run from menu "Recovery lost objects ...". Wait for finsh "Process" window and click to button "OK.". After click program show this Error

### Steps to reproduce

Run from menu "Recovery lost objects ...".
Wait for finish "Process" window and click to button "OK.". After click program show this Error

**Comment by RussKie** [comment]
Thanks for reporting.

> ```
> System.Exception: error: Could not read 57eb1d2165d47714f7428ffc66db2b74412856c4
> fatal: Failed to traverse parents of commit 4a53c2b7952ca3921aa778a29ed93b253e828b0b
> ```

This is the output of the git command; you'd observe the same if you were to run the command from the command line.

The popup dialog should be changed, but other than that this is an issue with your git repo and not the app.

According to the telemetry this isn't a heavily used dialog, so I'm going to close this.
