### ISSUE TITLE
GitExtensions try to run wsl git difftool with repository inside \\wsl.localhost

### ISSUE THREAD

**Issue by xinfli** [gitextensions/gitextensions#11220]
### Environment

Environment:
```
- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.22
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

GitExtension can open git repositories in WSL file system, it's great, everything works fine except the difftool, it try to run difftool within WSL distro and the compare doesn't work.

### Steps to reproduce

1. Setup difftool and mergetool of GitExtensions to GUI tool, for example WinMerge or Beyond Compare
2. Clone a git repository within a WSL distro
3. Open file explorer of windows host, go to the repository from `Linux`
4. Open the repository with GitExtensions, view any change in workspace or select any existing commit
5. Press `F3` to open difftool

Expected result:
GUI difftool/mergetool opened to compare selected change.

Actual result:
Nothing happened.
Open menu `Tools`-->`Git command logs`, the command found below shows it try to run `git difftool` within wsl:
```
File name:   wsl -d Debian git
Arguments:   difftool --gui --find-renames --find-copies --no-prompt "5cec1a71da6b88662c4876171d66bfe6b5dc203a" "4de18cfab1bf8258f953ed39b8321f9940cb6127" -- "web/pnpm-lock.yaml"
Working dir: \\wsl$\Debian\home\xinfli\repos\memos\
Process ID:  16940
Started at:  2023-09-20T21:10:22.7085144+02:00
UI Thread?:  True
Duration:    still running
Exit code:   unknown
```

**Comment by xinfli** [comment]
In this case I think it will be better to use **windows git difftool** to view the difference with GUI, that's why I use GitExtensions for repositories in WSL, isn't it?

Even it's intentional, could you please add an option to make it possible to always use **windows git difftools** to view difference for WSL repositories?

Thanks!

**Comment by gerhardol** [comment]
The usage depends, some difftools do not work on network shares.
The configuration is to add the difftool in WSL. I doubt adding a setting here would be found by users - there are too many settings already.
