### ISSUE TITLE
Last line of annotated tag gets truncated if output of "git cat-file" does not end with an empty newline

### ISSUE THREAD

**Issue by toesus** [gitextensions/gitextensions#11241]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.22

### Issue description

The message of an annotated tag shown in the commit-tab does sometimes not include the last line.
I found that this happens if the message as returned by `git cat-file -p tagname` does not end in an empty newline.

The use of `git cat-file` was introduced by #9616 
The change specifically introduced a removal of the last line of the git output, claiming there to always be an empty line:
https://github.com/gitextensions/gitextensions/blob/c5fb38974ffffa0d24833f078b49fd9a3e583f54/GitCommands/Git/GitModule.cs#L3422-L3423

Maybe this could simply be removed, as it seems the complete message gets `.Trim()`-ed anyways afterwards.

### Steps to reproduce

The only way I was able to reproduce (and how I discovered this) is to create a multiline annotated tag on a GitLab Server using the GitLab REST-API.
(Maybe this is an issue with Gitlab too, not sure if the empty trailing line in a annotated tag would be mandatory?)

After fetching the tag on a local clone, GitExtensions would truncate the last line of the message.

Manually verifying using `git cat-file -p tagname` confirms that the Gitlab REST-Api created tags indeed miss a trailing newline.

**Comment by RussKie** [comment]
Would you be able to propose a fix?

**Comment by toesus** [comment]
I think I could give it a try. Seems straightforward enough...

In the meantime I found a better way to reproduce. The `git tag`  command has an argument `--cleanup=verbatim` which prevents it from doing various whitespace cleanups including adding an empty line at the end.
So a tag created with `git tag -a -m "Some Annotation" --cleanup=verbatim tagname` will show up in gitextensions as "tagname [...]" but in the commit tab it will not show the annotation message.
