### ISSUE TITLE
Sometimes when opening the history window of a file, the program is stuck

### ISSUE THREAD

**Issue by renfengyue** [gitextensions/gitextensions#11255]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.22
- DPI 96dpi (no scaling)
- OS version:  Windows 10 Pro Version 22H2 OS build 19045.3448
![ShowHistory](https://github.com/gitextensions/gitextensions/assets/3722555/81519770-f36a-4a8b-b0c0-a4ad42ec49c9)

### Issue description

Sometimes when trying to view the history of a file, the program is stuck.

### Steps to reproduce

Right click a file from file tree view, in the popup menu, click "View history", try to open the history of the file, then the newly opened window is stuck. The windows seems frozen, I only can close it manually.

### Did this work in previous version of GitExtensions?

It does not works in the previous version.

**Comment by RussKie** [comment]
It's likely that it's loading the blame information, which for a file with
a long history could take a while.
