### ISSUE TITLE
SetWindowsPos 0x001C030A invalid handler error after GitExt Commit command

### ISSUE THREAD

**Issue by filippoquaranta** [gitextensions/gitextensions#11257]
### Environment

- GitExtensions version: 4.1.0.16698
- GIT version: 2.42.0
- OS version: WINDOWS SERVER 2022
- .NET version: 6.0.22

### Issue description

![mstsc_20231009_205459_558_Monday](https://github.com/gitextensions/gitextensions/assets/231948/dddb60f4-8f2a-47ab-a17b-a483e947d0a5)

### Steps to reproduce

1) RIGHT MOUSE CLICK IN FILES FOLDER
2) GITEXT COMMIT...
3) PUSH COMMIT BUTTON ON GITEXT COMMIT WINDOW
4) ERROR MESSAGE: "SetWindowsPos 0x001C030A invalid handler" APPEARED

**Comment by RussKie** [comment]
The error dialog indicates that this is a git error and not from Git Extensions.

**Comment by filippoquaranta** [comment]
I understand

thanks
