### ISSUE TITLE
Bring back blame tag @file history feature

### ISSUE THREAD

**Issue by renatofsp** [gitextensions/gitextensions#11258]
### Feature description

when checking a specific file history gitextensions had a tab blame that was very usuful

### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.39.2.windows.1 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.22
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by gerhardol** [comment]
Context menu to switch to Blame view
Also in Diff
(B toggles as well)

This used to be the default when filtering, but feedback was that users preferred to switch to Blame when desired instead.

**Comment by RussKie** [comment]
It's possible to get the "old" history dialog:
![image](https://github.com/gitextensions/gitextensions/assets/4403806/c4c24e6d-2058-4901-b534-7263e0b2fa6e)
