### ISSUE TITLE
Make graph color customizable

### ISSUE THREAD

**Issue by mshtang** [gitextensions/gitextensions#11282]
### Feature description

I am wondering if the graph's colors can be customized somehow?

![image](https://github.com/gitextensions/gitextensions/assets/32868278/0cbf5569-061c-402a-94ca-a567fb5c07df)

By making the colors customizable would be of great convenience for people having a hard time distinguishing between certain colors, especially in the case when the color blind mode is turned on but not helping.

### Environment

- Git Extensions 4.1.0.16698
- Git 2.41.0.windows.3
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.23

**Comment by mstv** [comment]
We could add one setting with a list of color values.
