### ISSUE TITLE
Remember current directory when start git shell console

### ISSUE THREAD

**Issue by andry81** [gitextensions/gitextensions#11297]
### Feature description

If run the application as:

```bash
GitExtensions.exe browse "<path-inside-working-copy>"
```

The application forgets the `<path-inside-working-copy>` and if press `CTRL+G`, then opens the repository working copy root directory instead of `<path-inside-working-copy>`.

Can you change current directory back to the `<path-inside-working-copy>` before run git shell console?

### Environment

- Git Extensions 4.2.0.17539
- Build d3b383c77a3cda85b835c7e6325c0ebb146a8be9
- Git 2.42.0.windows.2
- Microsoft Windows NT 6.3.9600.0
- .NET 6.0.22
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by gerhardol** [comment]
This would be yet another state to remember. 
I expect the normal use case is to open repos from the app, then always the root is used.
It may seem to be random when opening the console what directory i used.
 
Maybe context menu in Diff/Tree tabs is a better way to open consoles? (similar to Show in folder)

Not sure we want this enhancement to be open forever, for me it has low priority and there are quite some enhancements already and useful ones are hard to find. (Prio is personal.)
But maybe keep open and close it if not someone has picked this up in a year or so?

**Comment by RussKie** [comment]
The app operates in a context of a git repo not an arbitrary folder within
a repo.

**Comment by andry81** [comment]
> The app operates in a context of a git repo not an arbitrary folder within a repo.

This is inconvenient to search the WC root before open the repo. And git console operates from arbitrary folder within a repo.

**Comment by RussKie** [comment]
You can start the app from any point in a valid git repo - from a root (i.e., the folder that contains .git folder) or any nested folder. The app will calculate the repo root and open the repo.

**Comment by andry81** [comment]
> You can start the app from any point in a valid git repo - from a root (i.e., the folder that contains .git folder) or any nested folder. The app will calculate the repo root and open the repo.

This feature request is not about opening the app, it is about opening the git console from the app.
