### ISSUE TITLE
Unstage Changes window doesn't scroll to the end properly with long file paths

### ISSUE THREAD

**Issue by BoydyBoydy** [gitextensions/gitextensions#11295]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.38.0.windows.1 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.19
- DPI 120dpi (125% scaling)
- Portable: True
- Microsoft.WindowsDesktop.App Versions
- Microsoft.WindowsDesktop.App 6.0.19 [path removed]

### Issue description

Within the Commit Window, Unstaged Changes & Staged Changes Scrollbars change sizes for wider 'textfields'/windows (depending on what you call them)
(I couldn't tell if this happens for all of the scrolling - so have stuck with just the commit window)

### Steps to reproduce

1. For Commits that happen with longer path and file names, Scrollbar works on the first time with mouse - click and hold. (OK)
2. Then I use my scroll wheel on mouse to go back to the start (from the end of the scrollbar), the size of the scrollbar is adjusted. (NOK)
3. Not knowing that the scrollbar has been adjusted, when I try to then view the end of the filepath again, I am unable to see the end of the filename

So far I am able to continually scroll with the mouse wheel and the scrollbar continues to go different sizes (although they are similar depending on which scroll you do, up or down, it isn't consistent enough to see the end properly).

Please tell me if you need pictures to validate, but seems okay to reproduce.

I am able to recover from this if I use the setting 'truncate long filenames' (if I really need to), based on the previous issue
https://github.com/gitextensions/gitextensions/issues/7867#issuecomment-599224998

### Did this work in previous version of GitExtensions?

I'm not sure.

**Comment by mstv** [comment]
> Please tell me if you need pictures to validate

Yes, please provide screenshot of what you think is wrong and a recording e.g. using [PSR](https://support.microsoft.com/en-us/windows/record-steps-to-reproduce-a-problem-46582a9b-620f-2e36-00c9-04e25d784e47) or [ScreenToGif](https://www.screentogif.com).

**Comment by BoydyBoydy** [comment]
Screenshots below in GIF

Needed to Reproduce:

- Horizontal scrollbar to be visible
- For items that are less than the height of the window
    - (But this can also be seen as you scroll down when you have more items than visible - the scrolls will go down the list, but the scrollbar will still be seen to adjust its size)
- No Visible Vertical Scrollbar

I have used the long filename example:
GitExtTest\common\src\desktopMain\kotlin\org\test\common

2 Steps:
1. Mouse - Hold and Click to the end - Yellow Dot
2. Mouse - Scroll Wheel Down - Multiple times until the end of the gif - Seems to be invisible, but you can see when it happens

Noticed Problems
- Scrollbar is removed after first scroll down
- Scrollbar reappears after next scroll down
- Scrollbar adjusts size after next continuous scroll downs
- Visibly cannot see the end of the filename after scroll downs

GIF Below:

![GitExt-11295](https://github.com/gitextensions/gitextensions/assets/6037703/9fc7ec71-75fe-4a9e-83f6-aa00d355fcce)

**Comment by mstv** [comment]
Thank you, I can reproduce the issue now:
Mousewheel down moves the horizontal scrollbar *right* and lets it disappear and reappear.
Then it is too short. So the end of the filename cannot be scrolled into view.
I guess this is a bug of the ListView control.

![image](https://github.com/gitextensions/gitextensions/assets/36601201/6142e0b6-ca1f-4323-be55-0c239346d5a8)

**Comment by RussKie** [comment]
This could be a bug with the Windows Forms or the underlying Windows control. In this case, the bug should be reported to https://github.com/dotnet/winforms. However, I can't see the Windows Forms team giving this any significant priority.
Likewise, I don't see the Git Extensions team prioritising this with the all the ongoing work, and the easy workaround available - resize the panel to see the whole path.

If you or someone else is willing to propose the fix - we will certainly consider it.
