### ISSUE TITLE
Use branch names instead of base/local/remote during conflict resolving

### ISSUE THREAD

**Issue by montoner0** [gitextensions/gitextensions#11318]
### Feature description

During a conflict resolving, different versions of files are suffixed with words "BASE", "LOCAL", and "REMOTE". And most of times it's not quite clear what these suffixes mean (even with clarifications "ours/theirs"). 
It would be much easier if names of branches were used instead of (or additionally to) these suffixes.

### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.40.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.23
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pmiossec** [comment]
>It would be much easier if names of branches were used instead of (or additionally to) these suffixes.

You mean you know that there is a possibility to override these words because for me it's not possible as these files are created by git and GitExtensions has no hand on that...

**Comment by montoner0** [comment]
> for me it's not possible as these files are created by git

From what I see its not quite so. According to the Git command log, GitExtensions manually creates these files and runs a merge tool.
```
git	checkout-index --temp --stage=1 -- "src/app/shared/shared.module.ts"
git	checkout-index --temp --stage=2 -- "src/app/shared/shared.module.ts"
git	checkout-index --temp --stage=3 -- "src/app/shared/shared.module.ts"
git	check-attr -z diff text crlf eol -- "src/app/shared/shared.module.ts"
C:\Program Files\KDiff3\kdiff3.exe	 "C:\Source\src/app/shared/shared.module.ts.BASE" "C:\Source\src/app/shared/shared.module.ts.LOCAL" "C:\Source\src/app/shared/primeng-shared.module.ts.REMOTE" -o "src/app/shared/primeng-shared.module.ts"
```
The commands `checkout-index` create files with random names (like `.merge_file_9MZncP`) and then automagically these files became properly named when kdiff3 is called. 
I haven't looked in the GE code but it seems plausible that GE renames these random names.

**Comment by gerhardol** [comment]
git uses ours/theirs in the merge command.
REMOTE/LOCAL/BASE is the name of the temporary files used by difftool
BASE and local are commits, may not have branchnames. ours/theirs is still needed
Some of the Git commands will still require the raw names.

From what I remember, it was a little complicated to handle more generic names in these dialoges,
