### ISSUE TITLE
[NBug] Unable to open connection:Host does not exist

### ISSUE THREAD

**Issue by YatinShah** [gitextensions/gitextensions#11315]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.24
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

Exit code: -1073741510
Command: cmd.exe
Arguments: /k ""C:\Program Files\PuTTY\plink.exe" -T "git@gitY72:YatinShah/Name2Phone.git""

```
GitExtUtils.ExternalOperationException: Unable to open connection:
Host does not exist
 ---> System.Exception: Unable to open connection:
Host does not exist
   --- End of inner exception stack trace ---
   at async Task<bool> GitUI.Infrastructure.Plink.ConnectAsync(string host) in C:/projects/gitextensions/GitUI/Infrastructure/Plink.cs:line 81
   at async void GitUI.TaskManager.FileAndForget(Task task, Func<Exception, bool> fileOnlyIf)+(?) => { } in C:/projects/gitextensions/GitExtUtils/GitUI/TaskManager.cs:line 41
```

Unable to push to git repo if using alias from .ssh config file.

gitY72 is an alias to git.com

### Steps to reproduce

create a .ssh/config file with an alias as below for example:
Host gitY72
    HostName github.com
    User <aUserNameHere>
	IdentityFile "C:\Users\User\.ssh\TheServerWinVsCode.pvt.key"
	IdentitiesOnly yes

### Did this work in previous version of GitExtensions?

not sure.

**Comment by mstv** [comment]
There have been added improvements to v4.2 RC1. Could you try this?

**Comment by YatinShah** [comment]
Yes tried 4.2 release .. it still gives same error.

**Comment by mstv** [comment]
What output do you get when you run the command in the command line?

"C:\Program Files\PuTTY\plink.exe" -T "git@gitY72:YatinShah/Name2Phone.git"

The exit code -1073741510 (`0xC000_013A`) indicates that the console window for `plink.exe` was closed using the "X" button or by pressing `Ctrl+C`.
