### ISSUE TITLE
The User Manual of version 4.1 tries to open the "4.0" document, which does not exist

### ISSUE THREAD

**Issue by scampsd** [gitextensions/gitextensions#11338]
### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.24
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Best regards

### Issue description

When I click on "User Manual", my GIT-Extensions tries to open the following document:
https://git-extensions-documentation.readthedocs.io/en/release-4.0/

This does not exist and it is also not in line with my "4.1" version.

### Steps to reproduce

Click on the "Help" menu, choose "User manual".

**Comment by mstv** [comment]
I wonder why we have
https://git-extensions-documentation.readthedocs.io/en/release-4.2/
and
https://git-extensions-documentation.readthedocs.io/en/release-4.1/
but no
https://git-extensions-documentation.readthedocs.io/en/release-4.0/

Anyway, we should rename the current release branch to `release/4.2` and could release v4.2 soon:

```
            string? docVersion = "en/main/";

            if (!string.IsNullOrWhiteSpace(currentGitBranch))
            {
                // We expect current branch to be something line "release/X.Y"
                Match match = Regex.Match(currentGitBranch, "release/\\d*\\.\\d*");
                if (match.Success)
                {
                    docVersion = $"en/{currentGitBranch.Replace("/", "-")}/";
                }
            }

            _documentationBaseUrl = $"https://git-extensions-documentation.readthedocs.org/{docVersion}";
```

**Comment by gerhardol** [comment]
The build is restored, I cleaned that up when creating release/4.2 a week ago. (Some new configurations was required due to read-the-docs changes, there could be some minimal display changes.)
The 4.1 documentation is refreshed, no changes in 4.2 (yet at least).
There are some possibilities to redirect requests in read-the-docs interface, but not for this case.
The version should be set when building to avoid this manual change.

**Comment by scampsd** [comment]
Thanks a lot for this quick action, I can confirm that it's working: the user manual refers to "https://git-extensions-documentation.readthedocs.io/en/release-4.0/" and this link is working fine.
