### ISSUE TITLE
Support for the rebase option --update-refs

### ISSUE THREAD

**Issue by quinmars** [gitextensions/gitextensions#11333]
### Feature description

I often work with a tree or chain of branches and want to rebase the whole tree or chain. Since git version 2.38 there is the rebase option `--update-refs`. It would be nice if there was a check box in the rebase dialog for this. Today I have to either switch to the command-line or to manual relocate the branches after the rebase.

### Environment

- Git Extensions 4.2.0.17539
- Build d3b383c77a3cda85b835c7e6325c0ebb146a8be9
- Git 2.41.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.22
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.22 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by crypto-rsa** [comment]
I also use this option. You can add it to your `.gitconfig` as
```
[rebase]
    updateRefs = true
```

and it will be used by default in each rebase.

**Comment by quinmars** [comment]
Thanks a lot! There is even a checkbox in the settings for that:

![grafik](https://github.com/gitextensions/gitextensions/assets/5264714/4f610939-4578-4829-9b9f-595a4dfdcc0d)

While I still think, it'd be nice addition to the rebase dialog, I can work with this configuration option.
