### ISSUE TITLE
Broken layout for Commit validation tab in Commit messsage settings window

### ISSUE THREAD

**Issue by slabstone** [gitextensions/gitextensions#11343]
### Environment

- GitExtensions version: 4.1.0.16698 Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- GIT version: Git 2.42.0.windows.2
- OS version: Microsoft Windows NT 10.0.19045.0
- .NET version: .NET 6.0.24

### Issue description

No elements are visible in default window size:
![commit-validation-1](https://github.com/gitextensions/gitextensions/assets/4430708/d9a30efb-1f0e-4b7d-9c74-4411493a3da1)

Some elements are visible after stretching the window:
![commit-validation-2](https://github.com/gitextensions/gitextensions/assets/4430708/f371c92c-f10d-4a74-93d9-1567481ced57)

### Steps to reproduce

Commit > Commit templates > Edit commit message templates and settings... > Commit validation

### Did this work in previous version of GitExtensions?

Yes, it was fine in 3.5.4.12724

**Comment by RussKie** [comment]
I don't observe the issue in either v4.1 or v4.2:

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.38.1.windows.1 (recommended: 2.40.1 or later)
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.22
- DPI 96dpi (no scaling)
- Portable: False

![image](https://github.com/gitextensions/gitextensions/assets/4403806/ef1520e8-ab29-4ee9-b149-649619f01b48)


What dpi are you running at?

**Comment by slabstone** [comment]
> What dpi are you running at?
- DPI 120dpi (125% scaling)

**Comment by Dexterte** [comment]
If I set the DPI to 120, I confirmed the issue with version 4.2.

・Git Extensions 4.2
・Git 2.45.0
・Microsoft Windows NT 10.0
・.NET 6.0.29
・DPI 120dpi (120% scaling)
・Portable: False

![スクリーンショット 2024-05-11 111139](https://github.com/gitextensions/gitextensions/assets/22099752/e4f9a000-23e4-40f6-93b9-feee4af444a0)
