### ISSUE TITLE
Add UI for editing remote fetch commands

### ISSUE THREAD

**Issue by SlugFiller** [gitextensions/gitextensions#11347]
### Feature description

When adding a new remote, GitExtensions automatically tries to fetch from that remote. If it succeeds, it adds, to `.git/config` a section like:
```
[remote "origin"]
	url = https://github.com/gitextensions/gitextensions.git
	fetch = +refs/heads/*:refs/remotes/origin/*
```
If the fetch fails, it only adds:
```
[remote "origin"]
	url = https://github.com/gitextensions/gitextensions.git
```

In `Remote repositories...`, the `Default pull behavior` tab only allows managing the `merge = ` operations in `[branch]` sections.

When working with PRs, I found it very useful to add lines such as:
```
	fetch = +refs/pull/1234/head:refs/remotes/origin/pull/1234/head
```
However, this currently requires manually editing `.git/config`. It's not particularly user friendly.

I suggest adding another tab to `Remote repositories...` called `Default fetch refs`, which would contain a table with columns `Remote repository`, `Remote reference`, `Local reference`, and would otherwise have a structure similar to `Default pull behavior`.

For extra convenience, to reduce the voodoo in adding new options, it should have a preset drop-down to auto-fill the ref options as so:
- Preset: `Default`. Remote reference: `+refs/heads/*`. Local reference: `refs/remotes/origin/*`
- Preset: `Single branch`. Remote reference: `+refs/heads/master`. Local reference: `refs/remotes/origin/master`
- Preset: `Pull request`. Remote reference: `+refs/pull/1234/head`. Local reference: `refs/remotes/origin/pull/1234/head`
(Not sure if the `+` is necessary, or can be implicit. Perhaps the `refs/` or even `refs/remotes/origin/` too)

### Environment

- Git Extensions 4.1.0.16698
- Build 1fe52a137acef1fbd2b653dea263b44ad5844177
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.24
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.21 [D:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.24 [D:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by RussKie** [comment]
> When adding a new remote, GitExtensions automatically tries to fetch from that remote. If it succeeds, it adds, to `.git/config` a section like:
> 
> ```
> [remote "origin"]
> 	url = https://github.com/gitextensions/gitextensions.git
> 	fetch = +refs/heads/*:refs/remotes/origin/*
> ```
> 
> If the fetch fails, it only adds:
> 
> ```
> [remote "origin"]
> 	url = https://github.com/gitextensions/gitextensions.git
> ```

Could you point to the actual code doing this?

**Comment by gerhardol** [comment]
> However, this currently requires manually editing .git/config. It's not particularly user friendly.

The handling is specific to the Git server:
https://www.atlassian.com/git/articles/pull-request-proficiency-fetching-abilities-unlocked

It can be set locally, then you do not need to change anything for a repo.

For GitHub, it is usable only for smaller projects. For GE, it is slowing down fetch a lot.
BitBucket server (that deletes old pr references) is OK.

This is extremely hard to configure, just adding options will not be easier for the user.
It could be a specific GitHub plugin option.

I propose this is done manually still.

> Could you point to the actual code doing this?

Git adds this

**Comment by SlugFiller** [comment]
Sorry for not responding here. My mail client was moving GitHub messages to spam for some reason.

> Could you point to the actual code doing this?

After more investigation, it seems like this is done in Git itself, not in GitExtensions. I need to do more investigation to see the correct way to manage fetch targets.

> Look at 2nd tab of remote dialog.

Doesn't cover it. I even mentioned it in the OP. It edits tracking, but not which branches are fetched.

> The handling is specific to the Git server

[Refspecs](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec) are a feature of Git, and exist regardless of the server.

> For GE, it is slowing down fetch a lot.

I need that explained. Are you talking about pulling all PR branches? Sure. But the current default: Pulling all "normal" branches and tags, is also a problem. Just from this repo, I had to configure the refspec to `fetch = +refs/heads/master:refs/remotes/origin/master` instead of `fetch = +refs/heads/*:refs/remotes/origin/*`, because it was pulling a lot of old branch tags (like 3.x releases) that I had no interest in.

> I propose this is done manually still.

"Done manually" is open to interpretation. There's "done manually" by editing an arcane text file with a red text above it, in a modal dialog that doesn't let you look at other things inside the repo while you edit. And there's "done manually" via an appropriate UI that lets you list, add, and delete refspecs per-remote.

**Comment by RussKie** [comment]
Git is immensely configurable tool, and the aim of Gi Extensions is not to
provide the 100% coverage of the git features, but rather make git more
approachable to average Joe developers (in a good sense) and automate the
most commonly used operations.
There are countless numbers of git configurations and commands that the app
doesn't support or expose, and those are left to the users to use manually.
Or to develop own plugins.

Whilst I appreciate this scenario is important and useful to you, it
doesn't sound very common. If it was more common I think we'd seen many
more requests for this feature (FWIW, the app has celebrated its 15 bday).

**Comment by gerhardol** [comment]
> Sorry for not responding here. My mail client was moving GitHub messages to spam for some reason.

Some more messages for maintainers...

> > The handling is specific to the Git server
> 
> [Refspecs](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec) are a feature of Git, and exist regardless of the server.
> 
> > For GE, it is slowing down fetch a lot.
> 
> I need that explained. Are you talking about pulling all PR branches? Sure. But the current default: Pulling all "normal" branches and tags, is also a problem. Just from this repo, I had to configure the refspec to `fetch = +refs/heads/master:refs/remotes/origin/master` instead of `fetch = +refs/heads/*:refs/remotes/origin/*`, because it was pulling a lot of old branch tags (like 3.x releases) that I had no interest in.

"Decoration" of PRs is server specific like:
git config --add remote.origin.fetch '+refs/pull-requests/*/from:refs/remotes/origin/pr/*'

Tha will make the fetch very slow for GE repo.
The about 25 branches in GE repo does not make a difference, most are old and not distracting.

> > I propose this is done manually still.
> 
> "Done manually" is open to interpretation. There's "done manually" by editing an arcane text file with a red text above it, in a modal dialog that doesn't let you look at other things inside the repo while you edit. And there's "done manually" via an appropriate UI that lets you list, add, and delete refspecs per-remote.

Your definition.
Generally, if someone implements a feature that makes some sense that can be maintained, it is accepted.
But it is something I personally do not see much need of.

**Comment by elevatorguy** [comment]
With `6.0.2.18262`, is it no longer possible for branch to have tracking reference of pull request(s)?

<img width="93" height="51" alt="Image" src="https://github.com/user-attachments/assets/05b775c3-27da-48a5-a1dc-8a0850d3d18c" />

**Comment by RussKie** [comment]
Please be more specific.

**Comment by vbjay** [comment]
<img width="1494" height="669" alt="Image" src="https://github.com/user-attachments/assets/63fa1a0c-6b54-46ee-811b-9f7a9fd8dee6" />

Would allow me to set a fetch url and a push url for a remote. 

<img width="1509" height="758" alt="Image" src="https://github.com/user-attachments/assets/0a1daab5-50db-476d-84bf-26580b2b8fc9" />

Would set up tracking with origin/IncludePDBs to my local AN_Comment

What exactly are you missing?
