### ISSUE TITLE
TranslationApp removes mandatory texts

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11353]
### Environment

- GitExtensions version: vNext

### Issue description

`<trans-unit id="$this.Text">` must not be removed.

### Steps to reproduce

https://github.com/gitextensions/gitextensions/pull/10637/commits/2408bef27f0a662dd0a1b941032ba2854d2d1fd3 is a must, but not accepted by the CI build.

**Comment by RussKie** [comment]
Are you sure it is truly needed?

In 09f289306b19685b8ea4fffd0862881bfe950fbf you've removed the `Text` assignment:
![image](https://github.com/gitextensions/gitextensions/assets/4403806/e701b54b-ea50-40c6-9989-9e35f992d807)

**Comment by mstv** [comment]
Otherwise

![image](https://github.com/gitextensions/gitextensions/assets/36601201/e3bc8eae-a98a-42a1-ab9f-6e1a99bd6110)

Thank you for the heads up, Igor. This was incorrectly resolved when rebasing.
I thought I had seen a similar removal in another PR recently - but could not find it.
