### ISSUE TITLE
Opening 'Commit to' window throws an exception

### ISSUE THREAD

**Issue by grzegorz-marciniak-cc** [gitextensions/gitextensions#11356]
### Environment

- GitExtensions version: 4.2.0.17591
- GIT version: 2.42.0.windows.1
- OS version: win10
- .NET version: 6.0.24

### Issue description

Clicking the `Commit` button throws an exception:

> Method not found: 'System.String GitUIPluginInterfaces.IGitModule.GetSelectedBranch()'

![obraz](https://github.com/gitextensions/gitextensions/assets/92423691/affc9f5d-38b8-4d27-ae16-424ad693c556)

After clicking OK, the `Commit to` window is displayed, which is ok :)

### Steps to reproduce

- Click the `Commit` button on the main window.

![gitext_error](https://github.com/gitextensions/gitextensions/assets/92423691/a589ca9b-d4e5-4a2a-a9c8-e94afc8e589e)

### Did this work in previous version of GitExtensions?

Yes, it was working.

**Comment by RussKie** [comment]
Are you using external plugins?

**Comment by grzegorz-marciniak-cc** [comment]
Oh, JiraCommitHintPlugin was a problem. Thanks. Can be closed.
