### ISSUE TITLE
Spawn child processes in a job

### ISSUE THREAD

**Issue by MarekKnapek** [gitextensions/gitextensions#11365]
### Feature description

I have encountered following situation: My computer's CPU was pegged at one process consuming one CPU core. I have 8 core machine, so 12.5 % CPU was consumed constantly. I figured out that the process was vim.exe. Investigating its command line parameters I learned that it was computing some kind of diff, or whatever. So I guess I accidently pressed some keyboard shortcut inside GitExtensions, or I otherwise asked for the diff to be computed. I might have abandoned waiting for the diff to be finished and continued doing other stuff. Later, I noticed the high CPU usage. I wanted to gracefully cancel the diff operation, so in order to do that I closed the GitExtensions program. To my surprise vim.exe continued running, consuming my CPU time.

Meaning, GitExtensions launched some child process and when closing it didn't kill the child. So I was left with some orphans still running after successfully closing GitExtensions. So in this issue I suggest to kill such still-in-progress unfinished child processes when closing GitExtensions, when switching to other repo (the diff would be useless at this point) and at similar events.

But, using Unix-style tools with their philosophy of each process doing just one thing and spawning many such child processes this would not be effective. So I propose, when starting new child worker process, to start it inside a job object. And to set up the job object in a such way that it terminates all processes inside it when closed. And closing the job when closing GitExtensions is obvious. This could be also useful in situation when cancelling operation that takes long time. Killing the child is not effective in cases the child is bash for example as the real work is dones in some grand-child. Closing the job would actually kill all the grand-children.

### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.20348.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: True
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mstv** [comment]
Killing child processes started on user request would be a very dangerous feature with high risk of data loss.
Rather let's find out why vim was using up one core.
Were other processes involved? git, git lfs or another git filter, e.g. pdf2text?
Wasn't there a native or a console window with the vim UI?
F.i. the Microsoft Sysinternals Process Explorer displays trees of which process which.

**Comment by MarekKnapek** [comment]
Yeah, if I knew that, I would post it here. I'm using Process Hacker / System Informer instead of Task Manager or Process Explorer. The vim process had no parent alive at the time I noticed it. No conhost window anywhere to be seen.

> Killing child processes started on user request would be a very dangerous feature with high risk of data loss.

Yeah, I don't mean child processes the user explicitly asked to be launched, such as cmd or bash window. I mean child processes the GitExtensions launched as necessity to complete some task. Like git fetch, show diff, git merge and similar. These tasks usually have status window / progress bar window. I mean: when the status window is closed I assume the task is done, either successfully, unsuccessfully or cancelled and no child process is left lingering around.

**Comment by gerhardol** [comment]
Most long running Git commands started by GE has cancel tokens and are killed.
git-difftool is started async, similar to terminals and is not killed. I assume that is what is starting vim here.
So I do not know any specific situation where GE may not behave as you ask.
But if there are situations, please report....

**Comment by mstv** [comment]
> Yeah, I don't mean child processes the user explicitly asked to be launched, such as cmd or bash window.

Opening a difftool is an explicit user action. You have (tried to) launch `vim`. It is an editor. (I use my preferred diff tool for some editing, too.) You and me will not be happy if these would be killed with unsaved changes.

> I mean child processes the GitExtensions launched as necessity to complete some task. Like git fetch, show diff, git merge and similar. These tasks usually have status window / progress bar window. I mean: when the status window is closed I assume the task is done, either successfully, unsuccessfully or cancelled and no child process is left lingering around.

I fully agree with @gerhardol. `show diff` is different from the other commands which are awaited or cancelled, because it opens an interactive window detached.
