### ISSUE TITLE
Git cannot connect to repository.

### ISSUE THREAD

**Issue by GlebBur** [gitextensions/gitextensions#11373]
### Environment

- Git Extensions 4.2.0.17591
- Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

### Issue description

Through webbrowser open git repository.
When try to push git extensions opens dialog "Connect to Git"
I tried both "Signin with your browser" and "Sign in with a code" - successfully.
I'm logged in.
Month ago there was no such problem.
Git version updated today.

Error message
"C:\Program Files\Git\bin\git.exe" push -u --recurse-submodules=check -
-progress "origin" refs/heads/feature/.....         
remote: Support for password authentication was removed on August 13, 2
021.                                                                   
remote: Please see https://docs.github.com/en/get-started/getting-start
ed-with-git/about-remote-repositories#cloning-with-https-urls for infor
mation on currently recommended modes of authentication.               
fatal: Authentication failed for 'https://github.com/....'  
Done                                                                   
                                                                       
Press Enter or Esc to exit...           "                               
                                                                       

### Steps to reproduce

Press push

### Did this work in previous version of GitExtensions?

Today was the same result. That's why I updated git - UPDATE works only through MANUAL UNINSTALL. Auto update didn't work ever!

**Comment by gerhardol** [comment]
Try pushing from command line, GE is not making any changes here.
Are you using Git credential manager?

**Comment by burikus** [comment]
Not sure about cred manager. 
Win credentials and login (web) ok. 
I logged out from allaccounts  now. Tried again and connected successfully.
Maybe I was signedin on other browser with other account.  Maybe that was the reason.
Thank you for reply!
