### ISSUE TITLE
Remove redundant GitUICommands.GitModule

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11386]
Since `GitUICommands.Module` has the same type now,
```
        public IGitModule GitModule => Module;
```
shall be removed.

_Originally posted by @mstv in https://github.com/gitextensions/gitextensions/pull/11269#discussion_r1403762118_

**Comment by mstv** [comment]
I guess we should rather keep `GitModule` in order to not break the plugin interface. 
So I would turn all usages of `Module` into `GitModule`.

**Comment by RussKie** [comment]
I wouldnt do that.

IGitModule and other abstractions will be moved into GE.Extensibility. And
all plugins will have to use that.
