### ISSUE TITLE
Resetting new file will spawn an error dialog "The following files are unmerged and will not be reset"

### ISSUE THREAD

**Issue by darius-iko** [gitextensions/gitextensions#11391]
### Environment

- GitExtensions version:
Git Extensions 4.2.0.17591 Build bf814d4f1c6f178eacef38d592b700f9f2519dcb
DPI 120dpi (125% scaling)
Portable: False
Microsoft.WindowsDesktop.App Versions

- GIT version: Git 2.43.0.windows.1
- OS version: Windows 10 Home 64-bit (Microsoft Windows NT 10.0.19045.0)
- .NET version: .NET 6.0.25

### Issue description

Resetting new file will spawn an error dialog "The following files are unmerged and will not be reset"

Video capture:

https://github.com/gitextensions/gitextensions/assets/8023913/f80ec84e-f9bb-4ba8-851c-348e2ba0c50f

### Steps to reproduce

1. Create a new repo
2. Add a new file or several files
3. Go to GitExtensions and click Commit to open Commit dialog
4. Reset the added file and error dialog will appear

### Did this work in previous version of GitExtensions?

Previous version does not have this issue.

**Comment by gerhardol** [comment]
You can just ignore this popup, it was added for statuses that need special handling like merge conflicts.
Proposal to include a change for a 4.2.1 release

**Comment by allsorts46** [comment]
Sorry if I'm misunderstanding, but it looks like #11393 was intended to stop the popup for this particular message, and that commit is included in the 4.2.1 release? I'm using 4.2.1.17611 and still seeing this message pop up when resetting a new file, is that intended?

**Comment by darius-iko** [comment]
> Sorry if I'm misunderstanding, but it looks like #11393 was intended to stop the popup for this particular message, and that commit is included in the 4.2.1 release? I'm using 4.2.1.17611 and still seeing this message pop up when resetting a new file, is that intended?

Yup, I also still see this message pop up, but I don't have the screen capture. This error message will pop up when multiple files (combination existing file changes and new files) get reset at the same time.

**Comment by dmasells** [comment]
This bug is still present in v5.1.1.17970 when you have a new file which gets staged, then make further changes to that new file which appear in the unstaged area. Attempting to reset the changes from the unstaged area throws the error.

I have worked around the issue by selecting the unstaged lines in the diff view on the right and resetting them there.

**Comment by vbjay** [comment]
Yes also try generating a ton of files. The genius of a messagebox and not thinking of vertical size of dialog being a limit. 

- A dialog with a scrollable list
- a CANCEL button to say wait nevermind.

**Comment by macchmie3** [comment]
> This bug is still present in v5.1.1.17970 when you have a new file which gets staged, then make further changes to that new file which appear in the unstaged area. Attempting to reset the changes from the unstaged area throws the error.
> 
> I have worked around the issue by selecting the unstaged lines in the diff view on the right and resetting them there.

I also find this very annoying that I cannot simply reset some unstaged changes in a new file. It's more than just an "ignorable" popup.

**Comment by mstv** [comment]
> when you have a new file which gets staged, then make further changes to that new file which appear in the unstaged area. Attempting to reset the changes from the unstaged area throws the error.

reproducible

> I have worked around the issue by selecting the unstaged lines in the diff view on the right and resetting them there.

👍

> It's more than just an "ignorable" popup.

I agree. Though this a volunteer project, which lives on contributions. A proposal of an appropriate git command line, at least, would be welcome. You can add it as a User Script for testing.
