### ISSUE TITLE
Impact Graph plugin painfully slow on larger repos

### ISSUE THREAD

**Issue by snelltheta** [gitextensions/gitextensions#11411]
### Environment

- GitExtensions version: 4.2.1.17611
- GIT version: Git 2.42.0.windows.2
- OS version: Windows 10 22H2
- .NET version: 6.0.25

### Issue description

It took roughly 4.5 minutes to get the full impact graph for the GitExtensions repo on my 10th gen i7 processor. It takes about 20 seconds to go from blank to it showing the graph on the screen. 

I noticed in my dev environment that I can speed up the painting of the graph by turning off anti-aliasing that is present. Beyond that, the profile of the program appears that most of the CPU% load is still from painting all of those lines in Windows Forms. There may be some speedups implemented elsewhere that can be applied here.

### Steps to reproduce

Open Impact Graph on this repo and observe.

**Comment by pmiossec** [comment]
@snelltheta you will be happy with #11447. With it, now it takes only around 25s, just the time to retrieve data from git, to display the impact graph.

**Comment by snelltheta** [comment]
> @snelltheta you will be happy with #11447. With it, now it takes only around 25s, just the time to retrieve data from git, to display the impact graph.

Much faster! Good stuff!
