### ISSUE TITLE
Behavior when selecting 'Create a fixup commit' and then 'Amend commit'

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#11426]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Selecting 'Create a fixup commit' followed by the option to 'Amend commit' is causing confusion.
It would be beneficial to limit the availability of 'Amend commit' to instances where the previous commit is being fixed up.
Additionally, if choosing 'Amend commit' results in the removal of the added "fixup!" from the commit message, it would be more convenient.

### Steps to reproduce

1. Select a single commit.
2. Choose 'Create a fixup commit.'
3. In the Commit dialog, check the 'Amend commit' checkbox.
4. Press the Commit button.
5. The previous commit gets amended, and the commit message includes the addition of "fixup!"

**Comment by vbjay** [comment]
Not confusing at all. A fixup commit is a commit that will when rebased interactively and auto squash is used will automatically move commit to after the commit you are fixing up along with making the work roll into that commit. You don't ever amend it. 

If you goof the fixup just do another one. They play in todo in order. So there is no need to amend ever. You are using the wrong features of git together.

**Comment by gerhardol** [comment]
Commit was more restricted at fixup! previously, that was changed after user feedback so only the first commit is restricted.
There are many ways to work with Git. I often amend to fixup! instead of waiting to the interactive rebase.
I do not think this should be changed.

**Comment by RussKie** [comment]
The only thing that annoys me and I'd change is that when the "amend"
button is clicked the message should be changed to the previous commit's.

**Comment by vbjay** [comment]
> The only thing that annoys me and I'd change is that when the "amend"
> button is clicked the message should be changed to the previous commit's.
> 

Amend allows you to reword along with altering the changes committed. Are you talking about specific case of amending a fixup?

**Comment by shirayuki** [comment]
### Expected behavior
After selecting 'Create a fixup commit'. It doesn't have to be the immediate previous commit.
![image](https://github.com/gitextensions/gitextensions/assets/18039/ee226147-5fe6-4552-a780-5812b8517ea1)
After checking the 'Amend commit' checkbox
![image](https://github.com/gitextensions/gitextensions/assets/18039/1f175e93-b915-4482-9778-1a532244826e)

**Comment by RussKie** [comment]
> > The only thing that annoys me and I'd change is that when the "amend"
> > button is clicked the message should be changed to the previous commit's.
> 
> Amend allows you to reword along with altering the changes committed. Are you talking about specific case of amending a fixup?

Since "Amend" only works for the immediate parent, I'd prefer the message to be automatically changed to the parent commit's message when the "amend" checkbox is ticked. Pretty much what @shirayuki showed in the images.

It's one of my pet peeves that I have no time for... Maybe one day...

**Comment by mstv** [comment]
> I'd prefer the message to be automatically changed to the parent commit's message when the "amend" checkbox is ticked.

Just cut out the existing commit message to the clipboard (if there is any), then tick `Amend`. You have written it for a reason and might need it after the amend. 😉
I do not want to loose my commit message by mistakenly clicking the checkbox. The `Commit message` dropdown is dangerous enough.
