### ISSUE TITLE
Cannot Interrupt/Override "Diff Contains" Filter

### ISSUE THREAD

**Issue by snelltheta** [gitextensions/gitextensions#11443]
### Environment

GitExtensions version: 4.2.1.17611
GIT version: 2.42.0.windows.2
OS version: Windows 10 22H2
.NET version: 6.0.25

### Issue description

Cannot Interrupt/Override "Diff Contains" Filter. It will continue searching until it completes the filtering process, even if new user input + ENTER key is pressed. Clearing the filter string + ENTER doesn't stop it, either.

### Steps to reproduce

Filter by a string using the "Diff contains (SLOW)" filter in a sufficiently large repo. While it loads, it is not interruptible.

**Comment by mstv** [comment]
duplicate of #9418, should be fixed by #11205
