### ISSUE TITLE
Old version GitExtensions under Linux

### ISSUE THREAD

**Issue by GermanAizek** [gitextensions/gitextensions#11475]
### Environment

- OS version: Debian 12

### Issue description

Why does run only very old version GitExtensions with a lot bugs under Linux?
https://github.com/gitextensions/gitextensions/wiki/How-To:-run-Git-Extensions-on-Linux

### Steps to reproduce

- install mono
- run binaries

**Comment by gerhardol** [comment]
GE 3.x was compatible with Mono/Winforms, a .NET with WinForms implementation for *nix that was stopped being developed around 2010. Eventually it was impossible to keep compatibility, there were no developers using Mono too.
GE 4.x uses .NET6 (and .NET8 in master) which MS has open sourced, but there is no Linux porting of WinForms.
It could be possible to change the GUI toolkit to be cross platform, but that will require several manyears.
It should be possible to have some hybrid implementation with "Linux awareness" similar to WSL support in GE 4.x with the GUI using Wine.

I doubt there will be a sponsor to support a rewrite GE but someone using native Linux could improve Wine support.

**Comment by GermanAizek** [comment]
I can only write interface in Qt QML, but I can imagine how long it will take to create all windows and I do not know how to full link Qt with C#. In my opinion, GitExtensions git client is most convenient and flexible all that I have used, u definitely need linux port. Most people use the old version, but there are too many bugs in it.
