### ISSUE TITLE
Commit info tab image transparency back-color is broken after update to .NET 8

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#11506]
### Environment

- OS version: Windows 11
- .NET version: 6/8

### Issue description

This could be a regression in WinForms in .NET 8 (or 7 since we skipped it) but the icons in Commit Info tab headers are no longer transparent.. or maybe they are but a white background is painted behind them.

Before
![image](https://github.com/gitextensions/gitextensions/assets/483659/4aaf854d-aca7-435d-9275-74dae4d7fd9c)

Now
![image](https://github.com/gitextensions/gitextensions/assets/483659/f4fd59b1-9f8a-4848-8ee0-f05207620c5d)

I've tried meddling with various properties on the `ImageList` and `TabPage` but to no avail.

### Steps to reproduce

Run eeaf3c13e644a15178686af70bf362547943daa6 and notice transparent icons
Run 291c6d1c3615e6bc67ea56bbe1beae78db823743 an notice white background color for the icons

### Did this work in previous version of GitExtensions?

Yes, in eeaf3c13e644a15178686af70bf362547943daa6

**Comment by mdonatas** [comment]
Yea, unfortunately this seems to be a .net 8 regression. I created a minimal repro and the only difference between these two runs is .net 7 VS .net 8
![image](https://github.com/gitextensions/gitextensions/assets/483659/82ca731f-cb4c-413e-841b-819660842773)
![image](https://github.com/gitextensions/gitextensions/assets/483659/4b628414-4433-42fc-b974-03ba6843eb70)

**Comment by gerhardol** [comment]
Mentioned here too: https://github.com/gitextensions/gitextensions/pull/11240#issuecomment-1788131337

Can you open an issue in WinForms if there is none already?

**Comment by mdonatas** [comment]
I've just found an issue https://github.com/dotnet/winforms/issues/10462

**Comment by mdonatas** [comment]
I've found the root cause and a workaround, will create a PR for GitExtensions later.
https://github.com/dotnet/winforms/issues/10462#issuecomment-1880068488
