### ISSUE TITLE
Per-User setup doesn't work properly

### ISSUE THREAD

**Issue by LinoBarreca** [gitextensions/gitextensions#11508]
### Environment

- GitExtensions version: all tried since 3
- GIT version: N/A
- OS version: Windows 11
- .NET version: N/A

### Issue description

The per-user install tries to install in the wrong folder AND always asks for admin privileges

### Steps to reproduce

Try to install per-user on a system where you do not have Admin privileges.

Even if you choose the per-user install, the destination folder will be the program files x86 folder instead of C:\Users\<username>\AppData\Local\Programs\GitExtensions

Also, is will still ask for Administrator user/password.

### Did this work in previous version of GitExtensions?

No.

**Comment by mstv** [comment]
Use the portable version, please - refer to https://github.com/gitextensions/gitextensions/issues/10463#issuecomment-1331690320.

**Comment by LinoBarreca** [comment]
I already do...but a setup which has a clear bug is really unprofessional. If it's know not to be working and you don't have time to fix it, just hide the option to setup per user.

**Comment by RussKie** [comment]
It's a long standing issue, you're welcome to send a pr with a fix.

**Comment by mstv** [comment]
This is a volunteer project. As already stated:

> If you really require a per-user installer you're welcome to champion the work and send a PR.

**Comment by LinoBarreca** [comment]
I wish this comment arrived before Christmas holidays.
I just returned to work and I don't have as much free time anymore.
If I find some time I'll fix it. I already did professional installations (for work) with MSI so it's gonna be easy.

**Comment by RussKie** [comment]
No rush at all :)

I think the sticking point was/is the Explorer extensions. In the per-user
installation those should be unavailable - as those require the admin
privileges to perform system registrations (entries in the registry).

The plugins discovery/installation is another thing to verify to work.
