### ISSUE TITLE
Viewing a file's history causes very high CPU usage

### ISSUE THREAD

**Issue by paulzip-dev** [gitextensions/gitextensions#11510]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.25
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

### Issue description

When I open a file's history, Git Extension's CPU usage rockets and stays high for as long as the file history dialog is open.  Usually 50% CPU usage or higher.

### Steps to reproduce

1. Open Task Manager
2. In local repo, select file in "File Tree" table. 
3. Double click the filename or use "H" to view file history
4. Watch CPU usage go high and remain high for as long as the file history dialog is open.

**Comment by RussKie** [comment]
Is this issue specific to a file or a repo?
The history retrieval is dependent on the size of the repo (that's history).

**Comment by pmiossec** [comment]
I will add that you can open the "command log" window (F12) before
launching the history and have a look at the git log command to see if that
is this one that is long and is eating your CPU. or if it is
post-processing.
In the 1st case, we can't do much (it means that your repository is big).

**Comment by GermanAizek** [comment]
@RussKie I do not notice such issues. I have a lot changes in android device-kernel, about 300 commits per file. But I have a powerful PC configuration, and I think it's wrong to test like this.
![image](https://github.com/gitextensions/gitextensions/assets/21138600/9253a231-728b-4671-890c-54c6e4577657)

![THREADS](https://github.com/gitextensions/gitextensions/assets/21138600/43f87ef4-9abe-4d36-ac3c-62a379c6f378)

**Comment by gerhardol** [comment]
You need to find if this is a Git or GE issue.
If Git, you need to open an issue in Git about the performance.

**Comment by BaronZemo** [comment]
Whenever right-click a file and select File History I will frequently get a non-responsive window with a "Loading" text near the upper right corner of the window. This non-responsive window persists until I kill it from the task manager.

**Comment by gerhardol** [comment]
Git filtering can take considerable CPU, that is why the Git command log is useful to see the output.
You will see the "Loading" message while GE waits for Git to provide data, that should not block all operations though (only those awaiting for the load to finish).
There are no fundamental changes from 4.2 to 5.0

**Comment by mstv** [comment]
Which window do you use for viewing the history? "File History" or a main window with filtering?

![Image](https://github.com/user-attachments/assets/7b1e28c9-f383-4d52-b633-d422948cf409)

How many revisions does "git log" show? Very few only or lots of? How long does it take to run "git log" with that filter.

**Comment by RussKie** [comment]
Closing as stale.
