### ISSUE TITLE
Consider git version of WSL

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11520]
### Feature description

We should call `git --version` again on open repo because the git version in WSL can be different than in native Windows.
Some options depend on a recent git version.

### Environment

GE: vNext

**Comment by gerhardol** [comment]
Checks for Git version should use the "executable" version in GitModule. That uses the "gitIdentifiable" which is "" for Windows and e.g. "Ubuntu-22.04" for WSL.
I do not see any incorrect usage at a quick look.

WSL version is not presented in the GUI or UserEnvironmentInformation though.

**Comment by mstv** [comment]
I had not looked at the code yet. I just checked the git command log - and did not see the calls because the results are properly cached.
