### ISSUE TITLE
Repository "Filter for selected" branch not working when a stash is present

### ISSUE THREAD

**Issue by pascal-g-shift** [gitextensions/gitextensions#11527]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.26
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.29 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

In the repository UI `Filter for selected` shows all the commit for all the branches once a stash is created instead of showing only the commits for the current branch

### Steps to reproduce

- Create two branches in an empty repo and add a couple of commits on each
- Check that Filter for selected shows only the commits of whatever branch it is applied to
- Stage some local changes and git stash from git bash to stash the changes - the stash appears on top of the list of commits
- Try applying Filter for selected, it will have no effect on the list of commit which always shows all the commits for all branches
- If you deactivate View stashes it works for one branch and not the other...

### Did this work in previous version of GitExtensions?

Probably not - I noticed that feature not working - and it really bothered me - in the past. I couldn't find what caused the issue then.

**Comment by mstv** [comment]
Could you add screenshot(s), please?

**Comment by pascal-g-shift** [comment]
> Could you add screenshot(s), please?

Sorry I deleted the repo I created to reproduce the issue. It is fairly easy to repro by creating an empty repo and following the steps above.

**Comment by mstv** [comment]
By luck, I found "Filter for selected" in the context menu of the Left Panel.

1. Stashes are also intended for moving work between branches.

2. GE relies on git for the filtering. If you know the git command line which filters for stashes based on the filtered branch, let us know.
Because of the above argument and for complexity reason, there is chance that we do not want to implement this.

I might be easier and a clearer UX to add "Show stashes" to the filter dialog somehow.

**Comment by pascal-g-shift** [comment]
Sorry I should have mentioned in what menu "Filter for selected" is located.
There is a "Show stashes" option in the View menu and it impacts the behavior of Filter for selected.
If activated, the case I originally described. The stashes and all the commits are listed for all the branches and Filter for selected has no effect.
If deactivated, the branch with no stashes is filtered, the branch with the stashes shows all the commits from all the branches.
So apparently two separate issues:
- There is no filtering possible on the current branch.
- With the "Show stashes" option active, "Filter for selected" has no effect - one has absolutely not clue why or how to solve the issue.
A quick fix for the second one might be to have a warning when applying "Filter for selected" if "Show stashes" is active.

**Comment by mstv** [comment]
> There is a "Show stashes" option in the View menu and it impacts the behavior of Filter for selected. If activated, the case I originally described. The stashes and all the commits are listed for all the branches and Filter for selected has no effect.

At least with the current development version, this is different: The branch filter *has* the intended effect. But the most recent stash is always displayed (unless no stashes are shown).
This is done on purpose - remember "Stashes are also intended for moving work between branches."

> If deactivated, the branch with no stashes is filtered, the branch with the stashes shows all the commits from all the branches. So apparently two separate issues:

cannot reproduce either

**Comment by pascal-g-shift** [comment]
I agree that the most recent stash being always displayed (unless no stashes are shown) makes sense.
If the issue has been solved with the current development version and filtering the commits per branch works in all the cases then you can close this issue. Thank you for investigating.
