### ISSUE TITLE
Diff for filtered file or folder between selected commits

### ISSUE THREAD

**Issue by nikolaosginos** [gitextensions/gitextensions#11548]
### Feature description

The goal is to provide a simple way to compare a file or a folder between two commits when viewing its history.

When viewing the history of a file or a folder, a new window is opened where the history in the graph is filtered. Since you specifically filtered for a path, it would be great if you could pick two commits and show the **diff for the file or folder that you filtered for**. Currently, you can only "`Open selected commits with diff tool`" (which compares the whole repository between those commits or "`Compare selected commits`" and then pick the file you are interested in in the Diff window.

Doing the latter is just a bit inconvenient. It would be great to have a button like "Open filtered file/folder in selected commits with diff tool". The name is rather long but I hope it is clear what I am talking about.

I could try to implement this myself. This would be my first contribution though.

### Environment

- Git Extensions 33.33.33
- Build 46222f1613ff21d96446884df286c439829824cf
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.1
- DPI 144dpi (150% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mstv** [comment]
For a single file, one can click and `Ctrl`-click the two revisions and hit `F3`.
A button would make it more discoverable. Though it should only be shown if two revisions are selected.
But rather wait for further comments.

**Comment by nikolaosginos** [comment]
Okay, looks like I missed something really important there. :)

The button for F3 is on the context menu for a file. I misunderstood the "First -> Second" label, thinking that it would show the diff of the selected changeset to its parent. But it shows the diff of the file between two commits, if two are selected.

Also, I noticed that when I am in a filtered history window and going through the commits, the focus in the Diff and File Tree panels is always on the file whose history i was filtering for (as long as I didn't focus another one in the meantime).

And it makes more sense for the button to be on the file context menu instead of my version on the revision grid since it's a comparison of files, not commits.

I will wait as you suggested, but with that knowledge, I think this issue and the pull request are not relevant anymore.

**Comment by nikolaosginos** [comment]
Closing this since what I tried to achieve with this can already be done in a similarly easy way (see previous comment)
