### ISSUE TITLE
Cannot start VSCode during interactive rebase

### ISSUE THREAD

**Issue by Smurfa** [gitextensions/gitextensions#11556]
### Environment

- GitExtensions version: 4.2.1.17611
- GIT version: 2.43.0.windows.1
- OS version: Windows NT 10.0.22621.0 (Windows 11 Enterprise, build 22621.3007)
- .NET version: .NET 6.0.26

```
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

VSCode settings:
- Editor: Visual Studio Code --new-window --wait
- Mergetool: vscode
- Path to mergetool: C:/Users/selupfnb/AppData/Local/Programs/Microsoft VS Code/Code.exe
Mergetool command: "C:/Users/selupfnb/AppData/Local/Programs/Microsoft VS Code/Code.exe" --new-window --wait --merge "$REMOTE" "$LOCAL" "$BASE" "$MERGED"
- Difftool: vscode
- Path to difftool: C:/Users/selupfnb/AppData/Local/Programs/Microsoft VS Code/Code.exe
- Difftool command: "C:/Users/selupfnb/AppData/Local/Programs/Microsoft VS Code/Code.exe" --new-window --wait --diff "$LOCAL" "$REMOTE"

### Issue description

Trying to do an interactive rebase encounters an error when I use VSCode as my editor.

```
"C:\Program Files\Git\bin\git.exe" -c rebase.autoSquash=false rebase -i --no-autosquash "8ca9970c4f094a1a2ec17e4859b4bb8e033572a3"
hint: Waiting for your editor to close the file... Visual Studio Code --new-window --wait: line 1: Visual: command not found
error: There was a problem with the editor 'Visual Studio Code --new-window --wait'.
Done
```

I can however still use VSCode as a merge tool and solve conflicts without any issues. It is just when doing interactive rebase this occurs. I also tried to run: `code --new-window --wait` in PowerShell and it works without any problems.

![Skärmbild 2024-02-01 090136](https://github.com/gitextensions/gitextensions/assets/5418115/edfecc45-2ade-4420-ae84-c18930f405da)

### Steps to reproduce

1) Right click the branch to rebase on.

2) "Rebase current branch on" -> "Selected commit interactively..."

### Did this work in previous version of GitExtensions?

Yes, but it could have been on another computer (in the process of setting up a new laptop and I do not remember which system I used last for this).

**Comment by pmiossec** [comment]
> VSCode settings:
> 
>     * Editor: Visual Studio Code --new-window --wait

This value is not good. The name of the tool ("Visual Studio Code") is put when the executable is not found (Maybe that's not the clever things GitExtensions is doing...)
Set the same path than you used for the "Path to mergetool/difftool" (i.e. `C:/Users/selupfnb/AppData/Local/Programs/Microsoft VS Code/Code.exe`)

**Comment by gerhardol** [comment]
Note it is Git that reports the error, not specific to GE

Example of settings below (also handling cygwin, that part can be ignored).
both .cmd and path is needed for mergetool, due to the GE "internal" handling

```
$ git config -l | grep difftool
difftool.prompt=false
difftool.bc.path=c:/Program Files/Beyond Compare 4/BComp.exe
difftool.bc.cmd="c:/Program Files/Beyond Compare 4/BComp.exe" "$(cygpath -am $LOCAL)" "$(cygpath -am $REMOTE)" "$(cygpath -am $BASE)" "$(cygpath -am $MERGED)"

$ git config -l | grep mergetool
mergetool.prompt=false
mergetool.bc.path=c:/Program Files/Beyond Compare 4/BComp.exe
mergetool.bc.trustexitcode=true
mergetool.bc.cmd="C:/Program Files/Beyond Compare 4/BComp.exe" "$LOCAL" "$REMOTE" "$BASE" "$MERGED"
```

**Comment by pmiossec** [comment]
@Smurfa You could eventually test #11557 to see if it improve editor detection in GitExtensions settings.
The test/dev portable build is available here: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/49085446/artifacts

**Comment by Smurfa** [comment]
> @Smurfa You could eventually test #11557 to see if it improve editor detection in GitExtensions settings (and give us feedback). The test/dev portable build is available here: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/49085446/artifacts

@pmiossec thank you, I tried to change the value in the dropdown for the editor from `Visual Studio Code --new-window --wait` to `code --new-window --wait` and that resolved the issue.
