### ISSUE TITLE
Diff tab doesn't remember "ignore" options

### ISSUE THREAD

**Issue by bhaeussermann** [gitextensions/gitextensions#11565]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 6.0.26
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When selecting a file in the Diff tab, the diff panel allows to select which white-space should be ignored. When I change the selected option and then close and reopen GitExtensions, the option resets back to the previous selection.
This happens despite the fact that I have all the "Remember the ... preference" options checked (see screenshot).

![2024-02-05_13h25_07](https://github.com/gitextensions/gitextensions/assets/7482216/31b37b9e-14ef-4dbf-b941-f27d1c356472)

### Steps to reproduce

- Change a file in your repo.
- Open the repo in GitExtensions.
- Select the changed file in the Diff tab.
- Change the "Ignore whitespace..." option.
![2024-02-05_13h28_00](https://github.com/gitextensions/gitextensions/assets/7482216/f18d51c0-618d-4d1f-bc83-2e5c0b208726)
- Close GitExtensions
- Open the repo in GitExtensions

The "Ignore whitespace..." option has reset to the original selection.

**Comment by mstv** [comment]
refer to https://github.com/gitextensions/gitextensions/issues/10851

![image](https://github.com/gitextensions/gitextensions/assets/36601201/fd333449-c16e-4b5c-a5e2-9b707b353ac0)

**Comment by mstv** [comment]
The checkboxes shown in the issue description control whether these view options are kept when opening / closing the Commit dialog.
