### ISSUE TITLE
Non-branched tags do not show up in tag view

### ISSUE THREAD

**Issue by lashVN** [gitextensions/gitextensions#11566]
### Environment

- GitExtensions version: 4.2.1
- GIT version:  2.37.2
- OS version: Windows 10
- .NET version:  

### Issue description

In my workflow, I create branches for releases, then upon release I tag the commit used and delete the release branch (to prevent branch clutter). I've now noticed that I'm not able to find the tagged commit after the branch has been deleted.

My coworker using lazyGit is still able to see the same tag via a "tags" view, which in GitExtensions does not contain the tag.

### Steps to reproduce

1. Create a branch, tag a commit on that branch, push to origin
2. Delete that branch on origin
3. Observe that in a fresh clone using git extensions, the tag created does not show up

### Did this work in previous version of GitExtensions?

Not that I know of.

**Comment by pmiossec** [comment]
> 3\. Observe that in a fresh clone using git extensions, the tag created does not show up

I'm not sure to understand so I would like some clarification.

Is it a "clone" problem i.e. the tag is pushed on the remote repository but the tag is not retrieved during the clone? Can you double check that the tag is pushed?

Or is it a problem that the tag is not created or not pushed? In this case, could you double check that the "Push tag to 'origin'" is checked and that "origin" is not another remote than the one you clone from (i.e. a personal fork. In this case, you will have to create the tag and in a 2nd action push the tag from the "push" form)?

**Comment by lashVN** [comment]
I don't believe there's any clone problem, because the same folder without any additional fetch shows the tag correctly in lazygit.

To clarify, the tag is correctly created and on origin (I'm actually tagging it using GitLab rather than GitExtensions because of release pipeline integration).

I know the tag is on origin because:
1. Tag shows up on gitLab which is tracking origin
2. Tag shows up on my PC when using lazygit (using the same repository). I didn't do any additional pull when opening lazygit.
3. When I use lazygit locally to checkout the tag then open the repository in GitExtensions, it appears in my GitExtensions branch view (and persists to show up)

Even after the tag shows up in my branch view, the tag fails to be displayed in my left pane under "tags"

**Comment by lashVN** [comment]
It looks like my issue was I was configured to "follow tagopt ... " instead of "fetch all tags". After switching tag options in pull dialogue to "fetch all tags" the tag shows up as expected.
