### ISSUE TITLE
russian chars in filenames looks like squares! 

### ISSUE THREAD

**Issue by alexeik** [gitextensions/gitextensions#1156]
![picture](http://gyazo.com/2147b0d733eee5925b6dfb574d59176b.png)
hi. this picture shows the problem.
i have latest verssion.

sometime ago i did a patch that resolves this thing, but spdr throw it later said that all be is ok) 
seems to be he was wrong.
and previous version has this bug too.

**Comment by ktaranov** [comment]
Hello, guys.

For me working solution find [here](https://tellary.wordpress.com/2009/07/27/how-to-configure-git-to-display-native-cyrillic-filenames-correctly/).

1. ```git config --global core.quotepath false```
2. Restart GE
