### ISSUE TITLE
Vulnerability in WIX nuget package breaks AppVeyor build

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#11574]
### Environment

AppVeyor build

### Build issue description

Starting from today, all the builds are breaking in AppVeyor because a vulnerability in WIX package v3 and due to build setting "Warning as error".
It seems that the vulnerability is fixed only in v4 (which is not an easy move).
Report: https://github.com/advisories/GHSA-7wh2-wxc7-9ph5
Nuget: https://www.nuget.org/packages/wix 

### Steps to reproduce

Build a PR.

### Did this work in previous version of GitExtensions?

N/A

**Comment by pmiossec** [comment]
Added link to vulnerability is description...

**Comment by gerhardol** [comment]
Vulnerability describes 3.14.0 as safe, but AppVeyor fails the build.

**Comment by pmiossec** [comment]
> Vulnerability describes 3.14.0 as safe, but AppVeyor fails the build.

It's strange because initially the report was talking only about v4.0.4 that was fixing the issue, nuget.org was showing a vulnerability for v3.14.0 and my quick local update test was still showing the issue.

I was about to ask you where you saw this information but just noticed the update in the report.

Either there is still an issue or maybe they will replace the version published (but if that's the case, it's not really a bad practice)...

If they intend to fix the issue also for v3, maybe we just have to wait... and temporarily disable "Warning as error"?

**Comment by RussKie** [comment]
Does `<NoWarn>$NoWarn;NU1903</NoWarn>` help?

**Comment by RussKie** [comment]
There you go https://ci.appveyor.com/project/gitextensions/gitextensions/builds/49156822
