### ISSUE TITLE
Pull Action: "Fetch and prune all" does not prune tags

### ISSUE THREAD

**Issue by th3ragex** [gitextensions/gitextensions#11571]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.26
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The pull action "Fetch and prune all" does not remove local tags that were deleted on the server.

![image](https://github.com/gitextensions/gitextensions/assets/15040273/ba1c553f-2d17-4d3c-a690-c2489719006c)

The pull dialog has a dedicated action for prune and prune-tags which works:

![image](https://github.com/gitextensions/gitextensions/assets/15040273/2da0fbf3-c484-4c3b-b62a-e00fdd551209)

### Steps to reproduce

Make sure auto prune tags is off:
git config fetch.pruneTags false

Create and push tag:
git tag test123
git push origin refs/tags/test123

Delete tag on the remote:
git push --delete origin refs/tags/test123

GitExtensions: 
Pull via "Fetch and prune all" 
![image](https://github.com/gitextensions/gitextensions/assets/15040273/dfa2b029-6eb7-4414-9810-8128023fcd86)

### Did this work in previous version of GitExtensions?

Based on https://stackoverflow.com/questions/1841341/remove-local-git-tags-that-are-no-longer-on-the-remote-repository
it worked from Git v1.7.8 to v1.8.5.6.

Then `--prune-tags` was introduced (i guess).

**Comment by mstv** [comment]
seems to be intended
found in https://github.com/gitextensions/gitextensions/blob/master/src/app/GitUI/Resources/ChangeLog.md:
> #8465 Prevent adding "--prune --prune-tags" when run from toolbar

**Comment by RussKie** [comment]
More information is provided by @pmiossec in https://github.com/gitextensions/gitextensions/pull/8433#issuecomment-691906686.

The current behaviour is by design.

**Comment by gerhardol** [comment]
The text in the form should be updated

**Comment by RussKie** [comment]
> The text in the form should be updated

To which effect?
