### ISSUE TITLE
Option rebase.updateRefs from Rebase dialog

### ISSUE THREAD

**Issue by nicomeunier** [gitextensions/gitextensions#11577]
### Feature description

There is a global option `rebase.updateRefs` that is really useful when we want to rebase a branch and its dependents branches in same time. But sometimes, it's not what we are expecting. Especially when we want keep a branch as a backup of a rebase for comparison.

So it could be nice to have an option from _"rebase with advanced options"_ dialog to enable/disable the feature `rebase.updateRefs` only for the **scope of current rebase**.

### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.40.1.windows.1 (recommended: 2.42.0 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.26
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions
   - Microsoft.WindowsDesktop.App 6.0.26
   - Microsoft.WindowsDesktop.App 7.0.15

**Comment by mstv** [comment]
#11335
