### ISSUE TITLE
Default pull/push behavior 

### ISSUE THREAD

**Issue by znorris** [gitextensions/gitextensions#1160]
Changing the default pull behavior also changes the default push behavior. Perhaps these could be separated? The UI implies that they are separate already.

Remotes -> Manage Remote Repositories
Default pull behavior (fetch & merge) -> Remote Repository

**Comment by gusarov** [comment]
Doesn't sounds like related. Just faced same issue... changed pull behavior to upstream remote, and now push suggests me upstream for push, but I need origin

**Comment by cauerego** [comment]
just a random comment on #bugs.

it amazes me how long some bugs can persist or rebirth after being dead for however many years!

thankfully, i don't use windows even at work for millennia now.

cheers! 😁😘
