### ISSUE TITLE
Rebase Form has multiple high-dpi scalling issues

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#11606]
### Environment

- GitExtensions version: master
- OS version: Windows 11
- .NET version: 8

### Issue description

When comparing Scaling of 100% and 200% several differences are clearly visible
1. The buttons seem to be scaled twice. i.e. they are enlarged 4x rather than 2x when going from 100% to 200%
2. The image explaining effects of rebase is not scaled. Just compare one of commit bubbles with a checkbox to the right, their proportions are clearly different between two scaling options.

100% scaling
![image](https://github.com/gitextensions/gitextensions/assets/483659/6cb9ff9f-9fb4-4ad6-a62c-cd5c9b6d8fb6)

200% scaling
![image](https://github.com/gitextensions/gitextensions/assets/483659/89c7bd34-d5a2-4ceb-a734-281e366ca37e)

### Steps to reproduce

Switch between low/high DPI and produce a merge conflict with interactive rebase. Compare the form visually.

**Comment by mdonatas** [comment]
Should it maybe be required for any GUI changes to include screenshots in both low/high DPI and require them to match for PR to get merged? At least at my workplace not a single person has a 100% scaling (most have a 4K external monitor and a laptop where at least 150% scaling is necessary) so everyone who is using GE is getting a subpar experience.

**Comment by RussKie** [comment]
> Should it maybe be required for any GUI changes to include screenshots in both low/high DPI and require them to match for PR to get merged? At least at my workplace not a single person has a 100% scaling (most have a 4K external monitor and a laptop where at least 150% scaling is necessary) so everyone who is using GE is getting a subpar experience.

This is how we reviewed incoming pull requests that changed UI, however, at some point we got less ...strict? 

I made the latest rounds of changes of this dialog, and since I work at 96dpi I completely sidestepped the dpi verification (I no longer have a second monitor, so such checks aren't exactly easy).
