### ISSUE TITLE
View no longer remembers the last view setting. It always defaults to All branches

### ISSUE THREAD

**Issue by jmvdkolk98** [gitextensions/gitextensions#11614]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.27
- DPI 144dpi (150% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

I always use the view set to "Show current branch only". Until sometime last year, the most recent setting was retained when next opening a repository. Unfortunately, the settings are no longer retained and Git Extensions always starts with the view set to "Show all branches". I have to press Ctrl+Shift+U every single time that I start Git Extensions.

Was it a conscious decision to remove the functionality to retain the setting? Or is something wrong with my laptop? Or ....?

### Steps to reproduce

Start Git Extensions.
Open any repository. 
The view defaults to "Show all branches"

### Did this work in previous version of GitExtensions?

It used to work in 2023. However, downgrading didn't help me. I believe that this still worked as I expect on version 4.1.0.16698

### Diagnostics

[gitextensions.log](https://github.com/gitextensions/gitextensions/files/14460169/gitextensions.log)

**Comment by pmiossec** [comment]
> Thank you very much. I feel stupid for not looking down that far in the menu.

No problem. Even me a contributor I was not aware of this feature and I had to look at the source code....

> For my learning, was this change in behavior included in the release notes, and did I not read them well enough?

It was, yes ("#10851 Store view settings on request only"). But real life users don't have the time to read and understand each line of changelog of all the software we use...
https://github.com/gitextensions/gitextensions/blob/v4.2/GitUI/Resources/ChangeLog.md#version-42-13-nov-2023

**Comment by jmvdkolk98** [comment]
> It was, yes ("https://github.com/gitextensions/gitextensions/pull/10851 Store view settings on request only"). But real life users don't have the time to read and understand each line of changelog of all the software we use...
You are absolutely right. I forgot that his is what the changelog looks like. I'm afraid that this is a changelog that is more for those who are contributing and are on top of things, and less for users. But it is hard to create the right content for users.
