### ISSUE TITLE
Migration of color settings creates "black" theme

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11629]
### Environment

- Git Extensions 33.33.33 with #11624 included
- Build 27a3b1e4eee462accae311e882443aeaf75e7110
- Git 2.42.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.0
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

The migration of color settings creates the following `migrated.css` if the user had not configured anything.

```
.OtherTag { color: #000000}
.AuthoredHighlight { color: #000000}
.HighlightAllOccurences { color: #000000}
.Tag { color: #000000}
.Graph { color: #000000}
.Branch { color: #000000}
.RemoteBranch { color: #000000}
.DiffSection { color: #000000}
.DiffRemoved { color: #000000}
.DiffRemovedExtra { color: #000000}
.DiffAdded { color: #000000}
.DiffAddedExtra { color: #000000}
```

### Steps to reproduce

run GE on a machine without prior GE settings

**Comment by berrs** [comment]
I've verified this on the current latest (2d8c855266e86840780b35435aaf9319180c410e) and I've identified the issue. I will provide a fix.
