### ISSUE TITLE
Revision is not visible in the revision grid error when a subfolder branch is active

### ISSUE THREAD

**Issue by mduszenko** [gitextensions/gitextensions#11633]
### Environment

- GitExtensions version: 4.2.1.17611
- GIT version: 2.44.0.windows.1
- OS version: Windows 10.0.19045.0
- .NET version: 6.0.27

### Issue description

Filtering a branch in a subfolder causes the "revision is not visible" error when selecting another branch.

![image](https://github.com/gitextensions/gitextensions/assets/48009920/a1df5eaf-95e7-4578-8496-cce8ece28e7a)

Previous issues which may be related:

https://github.com/gitextensions/gitextensions/issues/10558
https://github.com/gitextensions/gitextensions/issues/10630
https://github.com/gitextensions/gitextensions/issues/11065

### Steps to reproduce

Test repository: https://github.com/mduszenko/gitextensions-revision-filter-issue

1. Make sure all branches are available locally.
2. Switch to `subfolder/branch-2`.
3. Click on `subfolder/branch-2` and click on "Filter for selected".
4. Refresh the repository.
5. Click on `branch-1`.

[Video](https://github.com/gitextensions/gitextensions/assets/48009920/ee68bd1d-9ddb-4887-a988-549bf27389eb)

### Did this work in previous version of GitExtensions?

It worked in version 3.x.x where the "Filter for selected" option was named "Show this branch only".

### Diagnostics

[gitextensions-log.txt](https://github.com/gitextensions/gitextensions/files/14598442/gitextensions-log.txt)

**Comment by mduszenko** [comment]
Yeah, it looks like a weird edge case. If that makes any difference, I use the non-portable version of GitExtensions, installed in `Program Files (x86)`. I have only recently upgraded to 4.x.x.

I think "Current branch only" can work for most scenarios, however I sometimes inspect another branch without switching to it.

**Comment by mstv** [comment]
As you have created a repo for the demonstration of the bug, could you share the Git Command Log (`F12`), please?

**Comment by mduszenko** [comment]
Sure, added the log to the first message.

**Comment by mstv** [comment]
> Sure, added the log to the first message.

Thank you. The commands look the same as with my test repo. (The exit code 128 for "git describe --tags" is correct since there are no tags.)

I have watched the video again. Step "4. Refresh" is crucial!
Reproducible with v4.2.1.
Not reproducible with vNext. The code for updating the Left Panel has already been revised.
