### ISSUE TITLE
Checkbox to delete associated remote branch

### ISSUE THREAD

**Issue by Meisterzunge** [gitextensions/gitextensions#11640]
### Feature description

When deleting a local branch, the dialog should provide a checkbox "Also delete associated remote branch" and vice versa.

### Environment

- GitExtensions version: 4.2.1

**Comment by RussKie** [comment]
We explicitly sepearated branch deletion dialogs into "delete local" and "delete remote" branches. The first one is a losseless operation (i.e., deleted refs can be restored via reflogs), the latter though is a "dangerous" operation where data can be irreversibly lost. Whilst this is a little inconvinient to open two dialogs to delete local and remove branches, data safety is significantly more important in our opinion; and we will not be merging the two dialogs.

**Comment by pmiossec** [comment]
> We explicitly separated branch deletion dialogs into "delete local" and "delete remote" branches. The first one is a lossless operation (i.e., deleted refs can be restored via reflogs), the latter though is a "dangerous" operation where data can be irreversibly lost. Whilst this is a little inconvenient to open two dialogs to delete local and remove branches, data safety is significantly more important in our opinion; and we will not be merging the two dialogs.

I share this point of view (of not merging the 2 forms as it is 2 completely different actions)
But actually, I have made a development in my custom version where I have added a checkbox when you delete the remote (so the most "loose data" prone action) that allows the deletion of the tracking local branch easily.

![image](https://github.com/gitextensions/gitextensions/assets/460196/fff37b43-13e2-46ad-ab58-db474c25feeb)

It **just** open the "delete local" branch form when the deletion of the remote branch is a success. And, even if we could find the UX a little strange, I find it **very** convenient.

I can make a PR.

**Comment by RussKie** [comment]
> ![image](https://private-user-images.githubusercontent.com/460196/317655234-fff37b43-13e2-46ad-ab58-db474c25feeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2MjA1MzcsIm5iZiI6MTcxMTYyMDIzNywicGF0aCI6Ii80NjAxOTYvMzE3NjU1MjM0LWZmZjM3YjQzLTEzZTItNDZhZC1hYjU4LWRiNDc0YzI1ZmVlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyOFQxMDAzNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjAyMTYyNWM2M2RmNTU4YzAwMmI2Y2ViYjU0ZjEyOWIwMmFjYjhjODRiMDQwZTc4YzhjZTg0YWI3ZWRkZGFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n8cH03Q9AkVrtD9AwKiMtyzvVFYtx3BDbY7Q0wSSwOo)
> 
> It **just** open the "delete local" branch form when the deletion of the remote branch is a success. And, even if we could find the UX a little strange, I find it **very** convenient.

How does it handle multiple branches?



> I can make a PR.

Sure, though I still think it's a reversed flow... But users find creative ways to injure themselves with git since 2005...

**Comment by pmiossec** [comment]
> > It **just** open the "delete local" branch form when the deletion of the remote branch is a success. And, even if we could find the UX a little strange, I find it **very** convenient.
> 
> How does it handle multiple branches?

It pre-select the local tracking branches so you will have multiple local branches selected ready to be deleted.

We can continue the discussion in the newly created PR #11661
