### ISSUE TITLE
Avoid fragmented "Take only ..." messages

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#11651]
### Environment

- Git Extensions 33.33.33
- Build 3a7e5d8bc16c2ba2f65eac3867e64ad89b9002e8
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 8.0.3
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Translators were asked to translate "Take only" and "the changes from the branch you are rebasing onto" separately.
During execution, these translations are concatenated.
At least, when concatenating the Japanese translations, it results in unnatural Japanese, given the significant differences in word order between English and Japanese.
In Japanese sentences, the verb typically comes at the end.

![image](https://github.com/gitextensions/gitextensions/assets/18039/569e4afd-31a8-4dc6-9b3b-665a4a270fa8)

GitUI/CommandsDialogs/FormResolveConflicts.cs

```cs
ContextChooseLocal.ToolTipText = _takeOnly.Text + " " + _changesLocalRebaseTooltip.Text;
ContextChooseRemote.ToolTipText = _takeOnly.Text + " " + _changesRemoteRebaseTooltip.Text;
ContextChooseLocal.ToolTipText = _takeOnly.Text + " " + _changesLocalMergeTooltip.Text;
ContextChooseRemote.ToolTipText = _takeOnly.Text + " " + _changesRemoteMergeTooltip.Text;
```

### Steps to reproduce

1. Perform a rebase or merge operation to create a conflict.
2. Hover over the context menu items and observe the tooltips.

**Comment by pmiossec** [comment]
Thanks for the heads-up. I will do a PR to fix that.
