### ISSUE TITLE
Reset action not triggered when pressing Enter in "Reset branch" dialog

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#11671]
### Environment

- Git Extensions 33.33.33
- Build 112c87345e3ddf959aff6f3a412bf4312313ee7b
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 8.0.3
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Opening the "Reset branch" dialog and pressing the Enter key should trigger the reset action, but nothing happens.
Pressing the Escape key once and then pressing Enter allows the reset to be executed.

![screenshot](https://github.com/gitextensions/gitextensions/assets/18039/1c2df769-f378-45b4-8549-f7a7b6589401)

### Steps to reproduce

1. Right-click on a commit in the grid view.
2. Select "Reset another branch to here..." from the context menu.
3. Press the Enter key in the "Reset Branch" dialog that appears.

**Comment by shirayuki** [comment]
The root cause was identified as commit:
'Fixup FormResetAnotherBranch ComboBox handling (#11656)', hash: 87f489007a5b5a7211752629b5e3c9f9198544d4

**Comment by RussKie** [comment]
/cc: @mstv I guess the keyup handler change changed the behaviour somehow...

**Comment by mstv** [comment]
I just need to create a PR for 4d495b8bd55b89c48c4db4b0cdcdc21a25a6c1e3.
