### ISSUE TITLE
"Go To Commit" dialog is SLOW when there are many tags

### ISSUE THREAD

**Issue by cforbin1** [gitextensions/gitextensions#11683]
### Environment

- GitExtensions version: 4.2.1.17611
- GIT version: 2.44.0.windows.1
- OS version: Microsoft Windows NT 10.0.19045.0  (Windows 10 Enterprise 22H2 build 19045.4170)
- .NET version: 6.0.28

### Issue description

When there are many tags in the repo, using menu choice [Navigate] > [Go To Commit] (key default Cttrl+Shift+G), the dialog box appears quickly but takes a long time to be ready, due to loading all the tags into the "Go to tag" control.  If you want to simply enter a commit expression, you cannot rapidly go to it: clicking in the control just puts the dialog into "(Not Responding)" status.  The user must wait for the 45-95 seconds it takes to load the tag window.   If the user is in a hurry and already has a commit expression to enter, this is a counterproductive delay: the user doesn't need the control populated in order to enter their expression.

Possible Corrective Actions (in order of likely desireability):
- you could put the control loaders in separate threads so the dialog is immediately ready, and set the dialog up to enable the "Go" button as soon as a commit expression is entered
- you could preload a cache for the controls when a checkout is done (again, probably in a separate thread so you don't hold up other things)
- you could force the user to await the controls loading for the first visit, but cache the data at that time, which would at least mean all subsequent visits would be quick
- other solutions may be available and should be investigated

### Steps to reproduce

1. Open a repo that has a LOT of tags.   (Unfortunately, I can't tell you how many tags is "a lot."  It will require investigation.)
2. Find a commit hash somewhere else in the history than where you are.  Note the first 6-8 characters.
3. Go to menu choice [Navigate] > [Go To Commit] (or use the default key mapping of Ctrl+Shift+G if that is valid on your machine).
4. When the dialog appears, immediately click on the "Commit expression" control and try to enter your partial commit hash.
5. Observe the dialog goes into "(Not Responding)" state.
6. Further observe that you have to wait (potentially more than a minute!) for the dialog to become ready.  If you attempt to cancel the operation using the "X" in the dialog banner, in Windows you get the OS's warning dialog that the application is not responding and you can either kill the application or wait for the dialog to be ready.  Thus if you open this dialog in a hurry in a tag-rich repo, YOU ARE STUCK until it has loaded all the tags.

### Did this work in previous version of GitExtensions?

Don't know.

### Diagnostics

No diagnostics available.

**Comment by mstv** [comment]
as a workaround, the commit hash can be pasted directly into the revision grid in v5.0

**Comment by mstv** [comment]
Tags (and branches) _are_ loaded asynchronously.
The "Commit expression" control _is_ focused by default.

How long does the highlighted command run?

![image](https://github.com/user-attachments/assets/d2db346c-2a3d-4aa3-8140-fe69f4252bfc)

**Comment by cforbin1** [comment]
Apologies, prior timing was in error.

It is taking about 11-12 seconds for the command to run to completion.

Not great, but FAR better than 77 seconds!!

**Comment by cforbin1** [comment]
Also, you wrote:

>> Tags (and branches) *are* loaded asynchronously.

That may very well be (I can certainly edit the entry while it is loading),
*BUT* the "Go" button does not function until the tags control has been
fully loaded.  This part does require a wait of approximately 77 seconds
before I'm allowed to proceed.

Hope this helps!

**Comment by mstv** [comment]
Your repo must contain zillions of tags.
(The "Go" button _does_ work as long the git command is running.)
But afterwards, the UI gets blocked by the data binding of WinForms.
Furthermore, the data source is evaluated twice - with active event handlers.

**Comment by RussKie** [comment]
VS repo has zillions of tags too, and I've been thinking of allowing to
disable loading tags per repo.
But I've got around doing this

**Comment by cforbin1** [comment]
> Your repo must contain zillions of tags. (The "Go" button _does_ work as long the git command is running.) But afterwards, the UI gets blocked by the data binding of WinForms. Furthermore, the data source is evaluated twice - with active event handlers.

Yes, zillions, unfortunately.

I wish it weren't so, but there are several teams within my employer who contribute to this repo, so it contains a LOT of code and it has a high churn rate.  Unfotunately, I don't have the clout to enforce a re-org of the repo, which probably _really_ needs to occur!

**Comment by cforbin1** [comment]
I just saw the PR approved.

Thank you SO much, folks, for doing this enhancement, and for doing it relatively soon.
This will make a specific part of my work life MUCH easier and more pleasant!!

**Comment by gerhardol** [comment]
> I just saw the PR approved.
> 
> Thank you SO much, folks, for doing this enhancement, and for doing it relatively soon. This will make a specific part of my work life MUCH easier and more pleasant!!

A follow up could probably remove the 7s or so you still saw when opening the form too.
