### ISSUE TITLE
Automatic refresh in commit dialog

### ISSUE THREAD

**Issue by hoba87** [gitextensions/gitextensions#11689]
### Environment

- GitExtensions version: 4.2.1
- GIT version: 2.44
- OS version: Win 11
- .NET version: 6.0.29

### Issue description

Changes in Working directory are automatically recognized, when focusing Git Extensions window.
However if commit dialog is open, automatic refreshing is not working.

### Steps to reproduce

- Open commit dialog
- make some changes in repository
- go back to commit dialog
- changes are shown after manual pressing refresh button

**Comment by mstv** [comment]
Have you activated the refresh?

![image](https://github.com/gitextensions/gitextensions/assets/36601201/46725ec8-6ffe-4012-895b-74518e4e581d)

**Comment by hoba87** [comment]
Ah ok, thank you, so there is no bug. But perhaps it should be noted in the user manual somewhere. Actually, I cannot imagine a usecase where a refresh is not wanted, so a comment on that would also be helpful.
