### ISSUE TITLE
Git extension cloning with Azure Devops very slow

### ISSUE THREAD

**Issue by sampatwa** [gitextensions/gitextensions#11706]
### Environment

- GitExtensions version: 4.2.1.17611
- GIT version: 2.42
- OS version: Windows 11
- .NET version: 6.0

### Issue description

Cloning a repository from Azure Repo's taking very long to download.  Sometimes it says Authentication failed when it starts the cloning process, other times it actually starts pulling files but it takes over 30 minutes to clone...it used to take about a minute.  This issue started 4/25/2024.  It is showing 15kb/s to download.

Internet speed is not an issue for everything else.

### Steps to reproduce

Open Git extensions, select repository, Destination, subdirectory and branch.  Click Clone

**Comment by RussKie** [comment]
I'm regularly cloning repos from azdo (sizable too) and I haven't observed any issues like that.

Is it specific to a repository? Or is it happening on a specific workstation?

**Comment by gerhardol** [comment]
It is Git that clones, GE is not involved. So command line should be the same.

**Comment by vbjay** [comment]
Which protocol are you using, ssh, https....  If https, 2.0, 1.1?

**Comment by vbjay** [comment]
Also https://learn.microsoft.com/en-us/azure/devops/organizations/security/data-location?view=azure-devops

Maybe wrong region?

**Comment by sampatwa** [comment]
Hi all,
Thank you for your responses.  This morning cloning repository is back to working like it used to.  Nothing was changed to resolve the issue from my end other than asking my team to change their passwords.
