### ISSUE TITLE
Sytax highlighting also for diff view

### ISSUE THREAD

**Issue by Thorium** [gitextensions/gitextensions#11717]
### Feature description

There is already a nice syntax highlight of different filetypes in "File tree" if you open a file:

> ![image](https://github.com/gitextensions/gitextensions/assets/229355/ea44a6c3-2c97-4f80-9a2c-a32eead20083)

But if you open a Diff-view, there is no syntax highlight at all, just only change highlight:

> ![image](https://github.com/gitextensions/gitextensions/assets/229355/972d220a-42e6-4c14-8b9e-61053e938bc5)

I propose the Diff-view should have syntax highlight where:
- In non-changed code lines the syntax highlight would be used like in "File tree"
- In changed code there wouldn't be colours but maybe font boldness on known keywords.

This is how WinMerge does it and I think it's clear enough:

> ![image](https://github.com/gitextensions/gitextensions/assets/229355/316ae645-439a-443e-bb37-24fa73ca4e14)

### Environment

- GitExtensions version: 4.2.1.17611
- GIT version: 2.42.0
- OS version: Windows 11 10.0.22631
- .NET version: 8.0.204

**Comment by pmiossec** [comment]
It's available. I think it's only disabled by default.

See  #7343 for details.

**Comment by Thorium** [comment]
Thanks. It seems to be the `<div>` button in the upper menu:
![image](https://github.com/gitextensions/gitextensions/assets/229355/aa05bdcc-4b48-470b-96c9-fc70d134471e)
