### ISSUE TITLE
right click on the Contex menu->GetExt Add files, and nothing happens

### ISSUE THREAD

**Issue by asmwarrior** [gitextensions/gitextensions#11711]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: True
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

I would like to use the context menu to add new files to the git repo, but nothing happens when I use the context menu add file item.

### Steps to reproduce

1, in a git repo, add a new file, for example, a `a.txt` file
2, right click on the file, and press the context menu item "GitExt Add files"
3, nothing happens, no pop up dialog, actually no file is added to the git stage.

### Did this work in previous version of GitExtensions?

Not sure. If I remember correctly, in previous version, I can only add file one by one, I mean if I select multiple files, and click the context menu to add files, only the first file is added.

**Comment by mstv** [comment]
It works for me. Perhaps re-registering the shell extension helps (will ask for admin privileges):

![image](https://github.com/gitextensions/gitextensions/assets/36601201/7441d56e-878f-4787-9883-388aec515b6c)

**Comment by pmiossec** [comment]
2 ideas in mind:
1. Are the others contextual command working?
2. if yes, there is maybe a bug in the contextual menu dll. if no, maybe a configuration issue in the registry.

**Comment by pmiossec** [comment]
In the registry, you could check the values at `HKEY_CURRENT_USER\Software\GitExtensions` if you see any outstanding/wrong value...

Mines:
![image](https://github.com/gitextensions/gitextensions/assets/460196/134812a9-a3b0-402a-939b-0802d63097f5)

**Comment by asmwarrior** [comment]
> 2 ideas in mind:
> 
>     1. Are the others contextual command working?
> 
>     2. if yes, there is maybe a bug in the contextual menu dll. if no, maybe a configuration issue in the registry.
> 
> 
> Working well for me.

Thanks for the help.

I see none of the context menu command works.

I just checked the registry, it looks like the "InstallDir" point to the wrong folder, see image below:

![image](https://github.com/gitextensions/gitextensions/assets/561818/ae5713d0-057a-4052-88bc-71f3c67e147b)

I just remove the whole "GitExtensions" folder in the registry, and opened the gitextension/install shell extension several times, it looks like the registry get re-constructed, but still no context menu item works, see the new registry folder below:

![image](https://github.com/gitextensions/gitextensions/assets/561818/285cacbd-586b-4985-879f-82effe97558b)

It looks like the "installDir" field is missing?

**Comment by pmiossec** [comment]
> It looks like the "installDir" field is missing?

Yes, and I think it is mandatory so don't hesitate to create it with the good value to see if that's the root cause of the problem.

**Comment by asmwarrior** [comment]
> > It looks like the "installDir" field is missing?
> 
> Yes, and I think it is mandatory so don't hesitate to create it with the good value to see if that's the root cause of the problem.

Hi, thanks. 

After adding this "InstallDir" field, and set the correct path to the actual git extension folder, I can open the context menu, and those functions works now.

But one thing remains, if I right click on a single file, and context menu shows gitextension shell menu. if I select two files, and context menu does not show any gitextension shell menus. Is this by design? I mean if I would like to add two or more files to the git repo, how can I do that? Normally, the expected way was first select the files I needed, and the next is the right click on those files.

Any ideas?

**Comment by pmiossec** [comment]
Even if GitExtensions allows some actions form the contextual menu, we could admit that it is not it's biggest strength.

For me, GitExtensions is a lot better when you "browse" a repository and from there, you open the "Commit" windows.

But, if you like to use is from the contextual menu but want to stage multiple files, you'd better use the "GitExt Commit..." entry.
That way you can stage and unstage whatever files you want (and for each file, you can even review the changes and/or stage even only part of the changes) and then close the window without necessarily committing.

**Comment by asmwarrior** [comment]
> Even if GitExtensions allows some actions form the contextual menu, we could admit that it is not it's biggest strength.
> 
> For me, GitExtensions is a lot better when you "browse" a repository and from there, you open the "Commit" windows.
> 
> But, if you like to use is from the contextual menu but want to stage multiple files, you'd better use the "GitExt Commit..." entry. That way you can stage and unstage whatever files you want (and for each file, you can even review the changes and/or stage even only part of the changes) and then close the window without necessarily committing.

Hi, @pmiossec thanks for the reply. Let me explain my usage:

I normally use the "GitExt Commit..." to open a dialog to stage any changes I want. The good feature of GitExtensions is that I can do "partial stage" which means I can only select lines I want to stage. That's a really nice feature.

What I want to use the "Add Files" features is in the case that those files were not tracked by git before. I mean I would like to select some files and initially add those new files to the git repo. I know I can use the "GitExt Commit..." dialog, but I always have the option "show untracked files" off. Which means news files were not listed. But if I enable the option "show untracked files", I see a lot of files(those files includes all the changed files and untracked files), and I need some methods(basically I use the regular expression or wildcard) to filter the new files I need to add. This way takes me a lot of time if I have many untracked files in the working copy.

I hope you can understand my explanation. I mean "select multiple files, and context menu to add them to the git stage" is a good feature I would like to have in the GitExtensions. Currently, I can only "select one file, and context menu to add it", so it is tedious to add many files in such way.

Thanks.

**Comment by pmiossec** [comment]
I don't have game changing solution.
The 2 things I have in mind:
* Can't you `.gitignore` most of the files that prevent you to easily find the good files?
* Do you know that you can use '*' to add multiple files with similar names? (But I understand that if the names are not similar, it won't help).

**Comment by pmiossec** [comment]
>I mean "select multiple files, and context menu to add them to the git stage" is a good feature I would like to have in the GitExtensions.

Indeed but the code of the dll that handle the contextual menu is made to handle only one parameter and would require a big refactoring to handle this case :(

It's a part of the code that is in c++ so I let it to someone that have it's windows/c++ a lot more rusty than me...
The last time I touched it is was a pain for something easier than that...

**Comment by asmwarrior** [comment]
> I don't have game changing solution. The 2 things I have in mind:
> 
>     * Can't you `.gitignore` most of the files that prevent you to easily find the good files?

Yes, I use `.gitignore` files, but I have some situation which can't be handled by this method, for example, I just copy some configuration files, but those configuration files were already tracked by git. I mean there are always some files which are not tracked by git.

> 
>     * Do you know that you can use '*' to add multiple files with similar names? (But I understand that if the names are not similar, it won't help).

When in the "Commit" dialog, I use `*` (wildcast) to filter some files, but this does not work all time. For example, I have new files in a folder `abc/def/xyz.cpp`, If I wrote `*.cpp`, this file will be shown, but if I wrote `abc/def/*.cpp`, it won't shown that new file, I'm not sure why. I think it should show that file. Maybe this is a bug?

> > I mean "select multiple files, and context menu to add them to the git stage" is a good feature I would like to have in the GitExtensions.
> 
> Indeed but the code of the dll that handle the contextual menu is made to handle only one parameter and would require a big refactoring to handle this case :(
> 
> It's a part of the code that is in c++ so I let it to someone that have it's windows/c++ a lot more rusty than me... The last time I touched it is was a pain for something easier than that...

I hope some experts on this shell menu implementation could have a look on this issue, thanks.

**Comment by vbjay** [comment]
Skip worktree
Assume unchanged

Two things that can be done to deal with config files.

**Comment by RussKie** [comment]
The C++ projects in this repo predate me, and I'm kind of the oldest maintainer from the Core team... So, I'm doubtful we have the sufficient expertise in those (or significant interest to be honest).
If this issue is something that's blocking you then you're probably in the best position to investigate it and propose a fix.

**Comment by asmwarrior** [comment]
> Skip worktree Assume unchanged
> 
> Two things that can be done to deal with config files.

Thanks, I haven't heard those two options before, but it looks like it is still hard to maintain the files by using those options, I have to specify the files I needed to let git ignore the changes.



> The C++ projects in this repo predate me, and I'm kind of the oldest maintainer from the Core team... So, I'm doubtful we have the sufficient expertise in those (or significant interest to be honest). If this issue is something that's blocking you then you're probably in the best position to investigate it and propose a fix.

Thanks, I just have a glance on the source code here:

https://github.com/gitextensions/gitextensions/blob/master/GitExtensionsShellEx/GitExtensionsShellEx.cpp

But I'm not familiar how the menu item is popped in its source code, it looks like a menu is generated for a single file(for example `a.cpp`), but not for a multiply selection files (say I selected two files `a.cpp` and `a.h`)

I think I don't have the ability to handle such task.

**Comment by mstv** [comment]
Here you are. "Add files..." was misleading. So it had to be changed anyway.
https://ci.appveyor.com/api/buildjobs/6h7u737iow3d8fc0/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-4.3.0.17842-3ff09aa9d.zip

**Comment by asmwarrior** [comment]
> Here you are. "Add files..." was misleading. So it had to be changed anyway. https://ci.appveyor.com/api/buildjobs/6h7u737iow3d8fc0/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-4.3.0.17842-3ff09aa9d.zip

Hi, thanks. I just download this zip file, and unzip the file, and copy the configuration files from the old portable gitextension folder, install the 8.0.6 version of dotNet desktop runtime. I started the 4.3.0.17842 version, and enable/disable the shell integration several times, and it looks like this version, I can't use the "Add files..." context menu. When I clicked on this menu item, I got a message box and it said:

![image](https://github.com/gitextensions/gitextensions/assets/561818/a3dd4148-2bee-47d4-8afb-a603dab6cd8e)

Is it a bug? It happens in either in the git root folder(the folder has a .git file) or a sub-folder of the git local copy.

**Comment by vbjay** [comment]
Or just  Ctrl shift and right click on taskbar to close that explorer instance. Then later on use task manager to run a new instance

**Comment by asmwarrior** [comment]
@mstv @vbjay ,thanks for the help.  "The current directory is not a valid git repository" issue still happens when a restart the computer. I have checked the register editor, and the "InstallDir" path is correct pointing to the new Portable-4.3.0.17842 gitextension's path.

So, I'm not sure what cause this issue.

**Comment by vbjay** [comment]
> Not a git directory means you are doing this in a folder that is not a repo or a sub folder of a repo. You can't do git operations in a regular folder. Must be in a folder that is either a root repo folder or a sub folder of a root repo.

**Comment by asmwarrior** [comment]
> > Not a git directory means you are doing this in a folder that is not a repo or a sub folder of a repo. You can't do git operations in a regular folder. Must be in a folder that is either a root repo folder or a sub folder of a root repo.

Thanks for the help.
But I did do those operation in the git's local repo root folder or the sub folder of a repo.  I have tried several folders, either root folder or sub folders, they have the same problem.

**Comment by asmwarrior** [comment]
![image](https://github.com/gitextensions/gitextensions/assets/561818/87b1f250-603a-4fd0-908e-0620dd88f8b6)

and 

https://github.com/gitextensions/gitextensions/assets/561818/31515fbf-24c2-49fc-b66b-6930009be873

See the above image and screen cast.

The aaa.txt and bbb.txt can't be added to the git stage if I use the context menu item. But they exit in the commit window if I enable the "show untracked files" option.

**Comment by vbjay** [comment]
Ok. Can you stage them in the commit window?


Can you add a file that is an edit and not a new file using context menu?

**Comment by asmwarrior** [comment]
> Ok. Can you stage them in the commit window?

Yes, I can stage those two new files in the commit window.

> 
> Can you add a file that is an edit and not a new file using context menu?

No. I just did a test. I modify a file in the root folder named "README.md", and try to use the context menu to add this file to the stage field, but it still report that "The current directory is not a valid git repository" messagebox. Adding the modified file to the stage field works correctly in the commit window.

**Comment by mstv** [comment]
Thank you for testing and checking!
I use to test it with TotalCommander (because amongst others it is easier to restart without side effects like missing tray icons).
The Explorer behaves differently: There, the current directory always is `C:\Windows\System32\`.
Adapted in https://ci.appveyor.com/api/buildjobs/3uthpfpy6jx9igft/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-4.3.0.17843-e2c0cd755.zip

**Comment by asmwarrior** [comment]
> Thank you for testing and checking! I use to test it with TotalCommander (because amongst others it is easier to restart without side effects like missing tray icons). The Explorer behaves differently: There, the current directory always is `C:\Windows\System32\`. Adapted in https://ci.appveyor.com/api/buildjobs/3uthpfpy6jx9igft/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-4.3.0.17843-e2c0cd755.zip

Thanks for the quick response and fix. I just download this revision, and after setting the shell extension, I need to log off Windows user, and later log in again to let the shell integration take effect. And now, I see I can select one or two files, and right click on the context menu, and "add files" command can correctly open the dialog, and those selected files were correctly added to the stage field.

That's great, it works OK now. Thanks.
