### ISSUE TITLE
Distributed `GitExtensions.settings` not applied on change

### ISSUE THREAD

**Issue by astos-marcb** [gitextensions/gitextensions#11720]
### Environment

- GitExtensions version: 4.2.1.17611
- GIT version: 2.45.0.windows.1
- OS version: Microsoft Windows NT 10.0.19045.0
- .NET version: 6.0.29

### Issue description

When a distributed `GitExtensions.settings` at repo root is updated while `GitExtensions` is running, the changes are not applied.
This can be a fairly regular condition for branches with deviating build integrations.

Settings in working directory seem to only be applied during initial repo load (GitExtensions restart required).
Expectation would be to (at least) update settings from working directory after branch switch or on manual refresh.

### Steps to reproduce

Change to different branch with deviating distributed `GitExtensions.settings` in repo top level.

**Comment by mstv** [comment]
Which settings are affected?

**Comment by astos-marcb** [comment]
At least settings in:
- `Build server integration` (Jenkins) and
- `Revision links`.

Not that immediately apparent (but likely) in other settings that support this level (`GitExtensions/Detailed`, `Plugins`).
At least the setting for `Plugins/Plugin Manager` is affected as well (not sure if this level even makes sense there 😄).

**Comment by mstv** [comment]
> Revision links.

Not reproducible. These settings _are_ applied on repo switch.

> Plugins

... are not my specialty.

**Comment by astos-marcb** [comment]
This concerns different braches and file content in the **same** repository location.
Cached internal state seems to include distributed `GitExtensions.settings` file (per repo) and never refreshed during runtime.

Having a matching cached entry in `GitExtSettingsCache` is likely responsible for hiding content changes.
At least *distributed* settings would need to be invalidated on manual refresh or when a branch change is detected.

**Comment by mstv** [comment]
> GitExtensions restart required

This is not necessary. There are two workarounds:
- manual: Reopen the current repo, e.g. by selecting it again in the toolbar:

  ![image](https://github.com/gitextensions/gitextensions/assets/36601201/686f143a-1d4c-4dcc-8194-7f029d2a596e)
- event script: Create a **non**-background script (those trigger a refresh after their execution)

  ![image](https://github.com/gitextensions/gitextensions/assets/36601201/aac3ff36-52f1-4c6c-846c-70bac56ee587)

When testing this, I noticed that these workarounds are not necessary - at least for:
- revision links
- build server integration

So, which dedicated settings do you vary in different branches?
Do the workarounds help?

**Comment by astos-marcb** [comment]
I **do** switch configuration of revision links in branches. ☺

But the condition to reproduce an issue has turned out to be more tricky than I thought;
Only **one** of of my branches had a `GitExtensions.settings` file!

- When starting up (initial load) of the branch **without** a settings file, no updates are triggered for that repo  _ever_
- When started with **and** switching between branches that **both** have a settings file, _everything works as expected_
- When switching from a branch **with** a file to one **without**, the settings do **not** get cleared.

Thanks @mstv to getting back to me so I could get to the bottom of this. :smile: 
My guess is you tried variant *2*, while I always managed to trigger *1* and/or *3* (up to my latest trials).

While the workarounds do not make a difference in the pathological states/changes, they are (of course) also not required in condition 2 (_everythin is fine_) here.
Interestingly, in any condition the expected state is shown _correctly_ in `Settings`.
But it does **not** get applied in the commit graph or info views in the described problematic states and transitions.

**Comment by mstv** [comment]
Could you test please whether #11781 suffices?
https://ci.appveyor.com/api/buildjobs/njcx71af2ds04f4c/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-4.3.0.17846-4663b8621.zip

**Comment by astos-marcb** [comment]
The change seems to remedy condition _1)_, since now event handling is always registered as per the patch.
However, when going to a branch **without** a file in _3)_, the settings still do not get cleared.

It seems there is still further change required to handle a _disappearing_ file. :thinking:
