### ISSUE TITLE
Bug in translation

### ISSUE THREAD

**Issue by UserSergeyB** [gitextensions/gitextensions#11726]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

![1](https://github.com/gitextensions/gitextensions/assets/7785277/89e8ea66-3b18-4d37-a0cf-8fd557bd4fc0)
![2](https://github.com/gitextensions/gitextensions/assets/7785277/280afb1c-50ac-4f8c-a105-c5e9dae3fdb6)
The translation of the command "reset another branch to here..." contains an error.

### Steps to reproduce

Start the app with russian language and open context menu on any commit.

**Comment by pmiossec** [comment]
Please contribute the fix directly to transifex service: https://github.com/gitextensions/gitextensions/wiki/Translations#how-to-update-non-english-translations

**Comment by RussKie** [comment]
There's no set date for the next release but we'll be making it at some point in not-too-distant future; and we'll be pulling the translations then.
