### ISSUE TITLE
Plugin `Jira Commit Hint` - Can't use API Token

### ISSUE THREAD

**Issue by damien-r-evx** [gitextensions/gitextensions#11740]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.43.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.30
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Greetings,

I tried to set a PAT for plugin Jira Commit Hint. As I can't generate PAT for Jira cloud, I tried to use an API Token. However, I have the following error:

```
System.Security.Authentication.AuthenticationException: Response Content: {"error": "Failed to parse Connect Session Auth Token"}
   at Atlassian.Jira.Remote.JiraRestClient.GetValidJsonFromResponse(IRestRequest request, IRestResponse response)
   at Atlassian.Jira.Remote.JiraRestClient.ExecuteRequestAsync(Method method, String resource, Object requestBody, CancellationToken token)
   at Atlassian.Jira.Remote.IssueService.GetIssuesFromJqlAsync(IssueSearchOptions options, CancellationToken token)
   at GitExtensions.Plugins.JiraCommitHintPlugin.JiraCommitHintPlugin.GetMessageToCommitAsync(Jira jira, String query, String stringTemplate) in C:\projects\gitextensions\Plugins\JiraCommitHintPlugin\JiraCommitHintPlugin.cs:line 334
```

Is it normal that API tokens are not supported? Is Jira Cloud not supported through Token?

Thanks in advance.

### Steps to reproduce

Set your API token in Tools / Settings / Plugins / Jira Commit Hints / Personal access token

**Comment by gerhardol** [comment]
> Is Jira Cloud not supported through Token?

@beiifeng ?

**Comment by beiifeng** [comment]
@damien-r-evx  The Jira Cloud api reference show others clients use basic authentication https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#ad-hoc-api-calls .
The basic authentication details shows here https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/ 
So, I think your should try "User name and password", "User name" input your email, "Password" input your api-token.
Thank you ~

**Comment by beiifeng** [comment]
> @damien-r-evx The Jira Cloud api reference show others clients use basic authentication https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#ad-hoc-api-calls . The basic authentication details shows here https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/ So, I think your should try "User name and password", "User name" input your email, "Password" input your api-token. Thank you ~

The testing result base on Jira Cloud. 
![image](https://github.com/gitextensions/gitextensions/assets/18087934/babb11f9-4ba6-4fe3-950e-60fccac63771)

**Comment by damien-r-evx** [comment]
Thanks, it worked.
