### ISSUE TITLE
Auto-update feature should be able to update Gitextentions the correct way

### ISSUE THREAD

**Issue by enthusedcoder** [gitextensions/gitextensions#11742]
### Environment

- GitExtensions version: 4.0.2.16100
- GIT version: 2.45.1.windows.1
- OS version: Windows 11
- .NET version: 8.0.204

### Issue description

Sorry if the title is a bit vague, so allow me to elaborate.  When the Git extensions application detects that there is a new version that has been released, **regardless of whether the running instance is the portable version (zip) or installed version (msi)**, the auto-update feature will download and run the msi and install the latest version of git extensions.  Even if you select to direct download the updated package, git extensions will default to the msi package.  This is all well and good for the majority of people who have installed git extensions using the msi installer, but for those of us who specifically chose to use the portable version and don't want to install the application on our systems, the auto-update feature is, at best, useless, and at worst, an annoyance.  Git extensions should be able to tell which version of the application (installed or portable) is running, download the appropriate release package (msi or zip), and update the application accordingly (install msi or extract contents of zip to the directory in which git extensions is located and overwrite all files).  Or, at the very least, take users to the github releases page for the most up-to-date version and allow them to select which package they want to download.

### Steps to reproduce

![gitext](https://github.com/gitextensions/gitextensions/assets/127647168/12e98c43-e9e6-4327-b25d-21351a59015e)

1) Open an out-of-date, **portable version** of the git extensions application.
2) If not automatically prompted, go to "Help" > "Check for Updates"
3) When the update popup window appears, click the "direct download" button
4) The application will then automatically download the msi install file, even though you are running the portable version of the application.

### Did this work in previous version of GitExtensions?

No.  It has never worked.  I have noticed that this has been an issue for quite a long time, but never really cared enough to take the time to create a github issue for it, considering the amount of time it takes to do so. and considering the fact that I can just go manually download the appropriate package myself.

**Comment by gerhardol** [comment]
Please try the PR build
Note that portable distributions must always be unpacked in a new directory, move settings manually.

**Comment by RussKie** [comment]
> Please try the PR build 

I don't think it's possible to verify the change until we make a formal release (i.e., update the https://github.com/gitextensions/gitextensions/tree/configdata branch) as the current nightly verion is higher than the released version.
