### ISSUE TITLE
Offer autostash for merges

### ISSUE THREAD

**Issue by MisterAI** [gitextensions/gitextensions#11764]
### Feature description

When merging another branch into my current branch the merge often fails because it would overwrite local changes, suggesting me to stash them first. Then I need to close the merge dialogue, open the stashing dialogue, stash all changes, close the stashing dialogue again, open the merge dialogue again, merge and finally apply the latest stash again. So all in all a pretty cumbersome procedure is necessary. Instead it would be great if GitExtensions would offer an autostash option in this case which stashes all local changes, does the merge and afterwards applies the stashed changes again.

### Environment

- GitExtensions version: 4.2.0.17591
- GIT version: 2.44.0.windows.1
- OS version: Microsoft Windows NT 10.0.19045.0
- .NET version: 6.0.30

**Comment by mstv** [comment]
Does activating auto-stash solve your issue? If not, does it a similar manual `git config` for merge?

![Image](https://github.com/user-attachments/assets/f6c34b0e-fb72-45b4-9d73-12eb2950cbdf)

**Comment by MisterAI** [comment]
Thanks @mstv for your replay.
A `git config --global merge.autoStash true` actually worked. 🥳 I guess there's no GUI option for that in GitExtensions (yet)?

**Comment by gerhardol** [comment]
> Thanks [@mstv](https://github.com/mstv) for your replay. A `git config --global merge.autoStash true` actually worked. 🥳 I guess there's no GUI option for that in GitExtensions (yet)?
 
mstv show where to configure this. The functionality is in Git, not GE.
It would maybe be possible to add another checkbox before each rebase, but there are enough options already.
