### ISSUE TITLE
Replace tiles in dashboard?

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#11768]
### Environment

- GitExtensions version: vNext

### Issue description

Tiles use to result in arguable UX (except for pictures). This proves to be true once again in the dashboard:

![image](https://github.com/gitextensions/gitextensions/assets/36601201/48730130-0155-49d0-8334-5e31bd79fea1)

![image](https://github.com/gitextensions/gitextensions/assets/36601201/f5db570a-19eb-4e43-ae3d-e3c221fd10b3)

### Steps to reproduce

Fail to open a not trusted repo

### Did this work in previous version of GitExtensions?

don't know

**Comment by gerhardol** [comment]
What is the question?
The text label obviously need to be wider.

**Comment by RussKie** [comment]
Yeah, that probably makes sense as this view mode is very usable

**Comment by pmiossec** [comment]
As discovered in #11779 discussion, the reason of this not readable display is the setting "Combobox minimum width (0 = Autosize)" :

![image](https://github.com/gitextensions/gitextensions/assets/460196/7a92addd-edd4-4d21-81c0-4697450ab3f0)
