### ISSUE TITLE
Filter by tag name

### ISSUE THREAD

**Issue by goodlyduck** [gitextensions/gitextensions#11776]
### Feature description

As a user, I would like to see all tagged commits along with their respective branches. I would like to filter this list based on tag name with wildcard. 

Purpose: to find tagged commits and their relations (i.e. latest common parent). 

### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.29.2.windows.2 (recommended: 2.42.0 or later)
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.31
- DPI 168dpi (175% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by gerhardol** [comment]
You can add options to git-log: https://git-scm.com/docs/git-log

Something like `--tags="v4.*"` 
![image](https://github.com/gitextensions/gitextensions/assets/6248932/a0984a60-aa07-40c5-817b-d981b5a8ed46)

You can add `--simplify-by-decoration` to just see tags/branches (also in Advanced filter dialog.


If that does not fit your needs, the filtering should be added to Git.
