### ISSUE TITLE
Commit messagebox bug with arrow keys

### ISSUE THREAD

**Issue by Dakyz** [gitextensions/gitextensions#11784]
### Environment

- GitExtensions version: 4.2.1.17611
- GIT version: 2.42.0.windows.2
- OS version: Microsoft Windows NT 10.0.19045.0
- .NET version: 6.0.25

### Issue description

Using arrow keys with multiline commit message and changing gitextension window size, make it possible to see this bug:
![image](https://github.com/gitextensions/gitextensions/assets/79918091/41059a33-feda-489b-8fda-d98f652f4d29)

It prevents shifting cursor until you make any move to other free way (for example, use right arrow key), but visual bug still exists.

The most strange bug is preventing cursor shifting to previous line of commit message (if it can be called so, because it still 1 line). This is no way to return to previous line by using left arrow key or up arrow key:
![image](https://github.com/gitextensions/gitextensions/assets/79918091/626b8eb5-41e8-4a43-8e4a-947578702569)

I guess this bug or feature (don't know) produces above mentioned bug.

### Steps to reproduce

Set the cursor to 1 position of second line (or any below if such ones exist):
![image](https://github.com/gitextensions/gitextensions/assets/79918091/81a56e04-9ac0-4dbd-8c7a-3ddf59c7daf8)

Try to return to first line by using left arrow key or up arrow key (it is not possible).

Change size of gitextension commit window, so the cursor is shifting to first line:
![image](https://github.com/gitextensions/gitextensions/assets/79918091/c87f0ff2-5216-4d50-9610-7e7a73afed72)

Try shifting to left by using left arrow key (it is not possible).

Use right arrow key and see fake cursor and real one:
![image](https://github.com/gitextensions/gitextensions/assets/79918091/cf28f98f-9efa-464f-a984-fd0860afd4d4)

**Comment by mstv** [comment]
We should turn off "word-wrap".

**Comment by mstv** [comment]
Does https://ci.appveyor.com/api/buildjobs/xb5k402kqxrmo2yx/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-4.3.0.17846-442b1cde0.zip work for you, @Dakyz?

**Comment by Dakyz** [comment]
@mstv, yes. Cursor shifting prevention is not a problem now. Thanks!

Although fake cursor after window resize still exists, I guess that it is not critical problem (who cares).
