### ISSUE TITLE
Description for `dotnet run` not adjusted for repository restructure

### ISSUE THREAD

**Issue by astos-marcb** [gitextensions/gitextensions#11792]
### Environment

- GitExtensions version: 33.33.33

### Issue description

The developer HOWTO uses `dotnet run --project GitExtensions` as command to start `GitExtensions`.
Due to the repo restructure in 8863b8b, the project location should now refer to `src/app/GitExtensions`.

### Steps to reproduce

Try to run `dotnet run --project GitExtensions` as described in the [wiki](../wiki/How-To%3A-build-instructions#build-solution).

### Did this work in previous version of GitExtensions?

Developer versions **before** 8863b8b.

**Comment by pmiossec** [comment]
Thanks. Fixed
