### ISSUE TITLE
Value quoting behavior of {SelectedRelativePaths} doesn't match other parameters available through scripting

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#11794]
### Environment

- GitExtensions version: [master]

### Issue description

Script variables help says:
```
Use {option} for normal replacement.
Use {{option}} for quoted replacement.
```

but unlike other script variables `{SelectedRelativePaths}` quotes the path to selected commit blobs. This is due to this line https://github.com/gitextensions/gitextensions/blob/548902485d318d252c8d1d5a43b45d124be11bca/src/app/GitUI/CommandsDialogs/ScriptOptionsProvider.cs#L32
where the value is always quoted before even getting to the scripting engine.

### Steps to reproduce

Output taken from the Git Command Log dialog

Single file selected, configured script args: `{SelectedRelativePaths}; {sBranch}`
_Both variable values should be unquoted_
```
File name:   SelectedRelativePaths_demo
Arguments:   "src/app/GitUI/CommandsDialogs/FormCommit.cs"; gitextensions/master
Working dir: C:\Workplace\personal\gitextensions\
```

Multiple files selected, configured script args: `{SelectedRelativePaths}; {sBranch}`
_Both variable values should be unquoted_
```
File name:   SelectedRelativePaths_demo
Arguments:   "src/app/GitUI/CommandsDialogs/FormCommit.cs" "src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs"; gitextensions/master
Working dir: C:\Workplace\personal\gitextensions\
```

Single file selected, configured script args: `{{SelectedRelativePaths}}; {{sBranch}}`
_Actual blob path doesn't contain quotes in it, this value is incorrect_
```
File name:   SelectedRelativePaths_demo
Arguments:   "\"src/app/GitUI/CommandsDialogs/FormCommit.cs\""; "gitextensions/master"
Working dir: C:\Workplace\personal\gitextensions\
```

Multiple files selected, configured script args: `{{SelectedRelativePaths}}; {{sBranch}}`
_Actual blob path doesn't contain quotes in it, this value is incorrect_
```
File name:   SelectedRelativePaths_demo
Arguments:   "\"src/app/GitUI/CommandsDialogs/FormCommit.cs\" \"src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs\""; "gitextensions/master"
Working dir: C:\Workplace\personal\gitextensions\
```

### Did this work in previous version of GitExtensions?

No

**Comment by mdonatas** [comment]
### Suggested fix
- Use `|` to join the paths. This is an invalid path character in both Windows and Unix systems so it can be recognized and replaced/split-by by the receiving executable
- Don't pre-quote individual file paths, leave this to a double `{{` braced `}}` script variable syntax.

This would produce _(typing this myself, not an actual output)_
Multiple files selected, configured script args: `{SelectedRelativePaths}; {sBranch}`
```
File name:   SelectedRelativePaths_demo
Arguments:   src/app/GitUI/CommandsDialogs/FormCommit.cs|src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs; gitextensions/master
Working dir: C:\Workplace\personal\gitextensions\
```

Multiple files selected, configured script args: `{{SelectedRelativePaths}}; {{sBranch}}`
```
File name:   SelectedRelativePaths_demo
Arguments:   "src/app/GitUI/CommandsDialogs/FormCommit.cs|src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs"; "gitextensions/master"
Working dir: C:\Workplace\personal\gitextensions\
```


In addition to `{SelectedRelativePaths}` we could also add `{SelectedRelativePath}` or `{FirstSelectedRelativePath}` options to pick just the first/last? selected commit blob.

cc @mstv, you've been doing some work around scripts thus I am tagging you so you wouldn't miss it. In my build I've made changes laid out in the first part and it worked fine for my needs both when using script with just a single file selected and with multiple files.

I feel like this is an important discrepancy to fix. I don't thinks there is any other variable which represents multiple values at once. If GE were to support this, I think more thought should be put in figuring out how to do it consistently with existing script functionality.

**Comment by mstv** [comment]
> but unlike other script variables `{SelectedRelativePaths}` quotes the path to selected commit blobs.

Valid point. There ain't no such thing as a simple feature. 😠

I see that it is inconsistent and that the quotes make it difficult to prepend `{WorkingDir}`.
The quoting for `{{option}}` is done straight forward. The regarding code is not aware of multiple values which should be quoted each instead of the entire string.
I guess we need to extend the interface IScriptOptionsProvider to return a string array.
And `QuoteForCommandLine()` should still be used - but reduced to `EscapeForCommandLine`, which has already been prepared.

> Use `|` to join the paths.

The (mis-)use of the pipe symbol will cause unexpected script behavior if the user is not aware of it. Anyway, it might be hard to handle in shell scripts.

> We could also add `{SelectedRelativePath}` or `{FirstSelectedRelativePath}`

I do not think it is worth to document and to implement such special options.
