### ISSUE TITLE
Some .ico files aren't rendered

### ISSUE THREAD

**Issue by TymurGubayev** [gitextensions/gitextensions#11809]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.45.2.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.31
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

- GitExtensions version: 4.2.1.17611 (Build b0c0b284876b63c52c77195ada82a85bfadbb083)
- GIT version: 2.45.2.windows.1
- OS version: Windows 10
- .NET version: .NET 6.0.31

### Issue description

Some icon files aren't rendered:

![image](https://github.com/user-attachments/assets/0442200e-1094-4c4d-9a86-682a901d2762)

![image](https://github.com/user-attachments/assets/31e4ee8a-ac18-4a01-8d8c-5711193e6203)

compare to Windows Explorer:
![image](https://github.com/user-attachments/assets/06714773-f0cb-4e6e-aff1-197ad312cb9b)

Also, probably related, the ok.ico has 32x32 and 16x16 versions inside of it
![image](https://github.com/user-attachments/assets/277520a7-cc74-42fb-aad5-e00f2b9cd1b6)

And the not_ok.ico only the 32x32
![image](https://github.com/user-attachments/assets/d511131c-46be-4182-ad34-e37f9146e8c8)

It would be nice to preview all present versions at once, if possible.

### Steps to reproduce

unpack attached icons.zip to a repository

[icons.zip](https://github.com/user-attachments/files/16198571/icons.zip)

**Comment by mstv** [comment]
Beyond compare considers this file being no image, too.

![Image](https://github.com/user-attachments/assets/8bec8d83-e7ac-4f72-a06f-879ea242b9b7)

![Image](https://github.com/user-attachments/assets/341dc4ac-2298-4ae7-8dd1-ead815a2c3e1)

I.e. your `not_ok.ico` seems to be pretty special somehow although windows and IrfanView can display it.

Do you have a clue, what is the difference between your example files?

**Comment by TymurGubayev** [comment]
Only that ok.ico has a 16x16 version, and not_ok.ico doesn't. My guess is the viewer assumes 16x16 is always present in any ico file.

**Comment by mstv** [comment]
The file is not supported by the .NET 8 library class `System.Drawing.Icon`.
Even with explicit request of size 32x32, it throws
`System.ArgumentException: 'Argument 'picture' must be a picture that can be used as a Icon.'`
The `System.Drawing.Bitmap` class refuses to load that file, too.

Redirect your request to the .NET platform, please.
