### ISSUE TITLE
Certain files appear blank in File Tree viewer and also do not work in File History or Blame views

### ISSUE THREAD

**Issue by DanielStout5** [gitextensions/gitextensions#11815]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.42.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.30
- DPI 144dpi (150% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

File appears empty in the File tree view:
![image](https://github.com/user-attachments/assets/5d7d43ed-2de9-45ec-91f2-ecb835e681dc)

Same for the history view:
![image](https://github.com/user-attachments/assets/33c85db8-c092-4be3-9642-2d0cff1b9606)

I found some old issues about a similar problem, but the path to this file does not contain any spaces or special characters.

### Steps to reproduce

Seems to happen for most files in the repository.

Even for files in the same folder, some work, most do not.

TimeOnlyJsonConverter can be viewed:
![image](https://github.com/user-attachments/assets/89b9a913-82b0-4017-ac06-efc8f183f8a1)

But not SwapExpressionVisitor:
![image](https://github.com/user-attachments/assets/dc703245-485b-489f-a0d9-1b32e65da037)

### Did this work in previous version of GitExtensions?

Yes, but not sure which one.

**Comment by mstv** [comment]
Have you waited long enough? Calculating the blame view can take very long.

**Comment by DanielStout5** [comment]
Belated update on this - it seemed to be caused by a corrupt Git repository. Cloning a fresh copy fixed the issues I was seeing in Git Extensions.
