### ISSUE TITLE
Update dashboard logo

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#11810]
The current logo was a failed attempt at rebranding and it's been bothering me since the inception. Also I'd like to bring consistency back. 

Few quick proposals:

* Option 1: white
![image](https://github.com/user-attachments/assets/c6a3c580-8c16-4f43-83c2-0292d82ffd10)

* Option 2: black/white
![image](https://github.com/user-attachments/assets/d46fae1a-1287-489c-8944-1aee5c96bb59)

* Option 3: black
![image](https://github.com/user-attachments/assets/90e1aa35-37df-4739-a726-06a551dfb2b1)

I like the white version but the second one doesn't seem too bad either. Not too keen on the black.

**Comment by pmiossec** [comment]
> The current logo was a failed attempt at rebranding and it's been bothering me since the inception. Also I'd like to bring consistency back.

I nearly never had a look at the logo (but new users will probably do it first), so while you ask, I prefer "Option 1". Why not "Option 2". And don't really like "Option 3".

**Comment by mstv** [comment]
I prefer option 1.
