### ISSUE TITLE
[vNext] Version targets x64 but tries access x86 paths

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#11819]
### Environment

- Git Extensions 4.3.0.17872-mbjjveco
- Build 70184a4c7252b263427ed627f5004e288e51b4bb (Dirty)
- Git 2.45.2.windows.1

### Issue description

Since https://github.com/gitextensions/gitextensions/pull/11625 we now publish platform-specific artifacts. The app is now being installed under `C:\Program Files\GitExtensions` instead of `C:\Program Files (x86)\GitExtensions`.
The app also has baked in paths in configs that must be updated.

![image](https://github.com/user-attachments/assets/1d96fbc1-db1c-424f-804d-849d68717fdd)

```
"C:\Program Files\Git\bin\git.exe" -c rebase.autoSquash=false rebase -i --autosquash "7a328a52066bcee2f5396d3d01af3d189fe90a69"
hint: Waiting for your editor to close the file... "C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor: line 1: C:/Program Files (x86)/GitExtensions/GitExtensions.exe: No such file or directory
error: there was a problem with the editor '"C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor'
Done
```

### Steps to reproduce

1. Install **GitExtensions-x64-4.3.0.17872-70184a4c7.msi** from https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50328130/artifacts
2. Try to interactively rebase

**Comment by gerhardol** [comment]
This is the git-config setting for editor, should be migrated automatically if ge x86 path is used.

For wsl the path must be manually changed. 

The ge editor should be used by default unless set by git config for a smoother experience (also better for wsl). Such handling could also do the migration (as instruction?). But editor is used for more than rebase.

**Comment by RussKie** [comment]
> This is the git-config setting for editor, should be migrated automatically if ge x86 path is used.

👍

**Comment by gerhardol** [comment]
I propose this is migrated when GE is first started. Only the global path is updated, but it is only path GE updates.
Other paths (including WSL) may have been modified manually and it is confusing.

Draft, need to execute git-config  directly
https://github.com/gerhardol/gitextensions/pull/new/feature/i11819-core-editor-x86-path

**Comment by RussKie** [comment]
> Draft, need to execute git-config directly [gerhardol/gitextensions/pull/new/feature/i11819-core-editor-x86-path](https://github.com/gerhardol/gitextensions/pull/new/feature/i11819-core-editor-x86-path)

This looks good 👍 

Does `AppSettings.GetGitExtensionsFullPath()` return a POSIX path?
