### ISSUE TITLE
"fatal: bad config file line 16 in .git/config" after adding second remote repository

### ISSUE THREAD

**Issue by vygantas** [gitextensions/gitextensions#1182]
Steps to reproduce:
- Initialize repository "origin1" and commit a file
- Initialize repository "origin2" and leave it empty
- Clone repository "origin1" as "local"
- At the repository "local" add new remote repository "origin2" through Remotes->Manage Remote Repositories->New
- After button "Save" is pressed you'll see an error and repository is unusable

**Comment by raopipi** [comment]
Met the same problem， How to solve?

**Comment by jbialobr** [comment]
Can you provide some more data? What GitExetnsions version do you use? Which config file line causes the problem?
