### ISSUE TITLE
Ask for SSH-passwords every time on WSL2 located repositories with private remote repos, secured by Open-SSH keys with password.

### ISSUE THREAD

**Issue by mariolorenz** [gitextensions/gitextensions#11839]
### Environment

- GitExtensions version: 4.2.1
- GIT version: on Windows: 2.46.0, inside WSL2: 2.42.0
- OS version: Windows 10, WSL2 = Ubuntu 22.04.4 LTS
- .NET version: 6.0.33

### Issue description

My repository is on WSL2 \\wsl$\Ubuntu\home\ ... GE recognizes this WSL2 path and uses this hard-coded command: 

**"wsl" -d Ubuntu git  ....** 

The problem is that this call apparently ignores all settings from the .bashrc of my WSL2 environment.

Because I have configured my WSL2 like this: [Auto-launching ssh-agent on Git for Windows](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases#auto-launching-ssh-agent-on-git-for-windows)

When I start WSL2 for the first time, I would asked once for the SSH key password. I can then run "git pull" (or any other GIT action) several times without being asked for the password, because the SSH agent ensures that I do not have to enter the password again.

But GE apparently ignores my .bashrc with the above configuration. This ensures that I am asked for the password for all GIT actions from GE.

It would be correct if GE use the same configuration applied to the above-mentioned call as normal under WSL2.

### Steps to reproduce

Use GE on a WSL-Path with a Repository, that needs a SSH-Key for access. And the SSH-Key is generated with a password.

### Did this work in previous version of GitExtensions?

Unfortunately I don't know.

**Comment by vbjay** [comment]
Read up on ssh agent and or putty although I don't know if wsl and putty
work together.

**Comment by mariolorenz** [comment]
@vbjay : I use the solution via OpenSSH. But I also know the other option of providing the Putty agent to WSL: [wsl2-ssh-pageant](https://github.com/BlackReloaded/wsl2-ssh-pageant)
I used that successfully for a while (Putty bridge to WSL) but not in connection with GE and Repos on WSL-Paths at the time.

In the end, however, the solution there is also to provide the bridge using a .bashrc. That's why I think that GE will end up running into the same problem with Putty and OpenSSH.

**Comment by vbjay** [comment]
Possible. Look at openssh version of agent config. 

One of the articles I found through Google. 

https://interworks.com/blog/2021/09/15/setting-up-ssh-agent-in-windows-for-passwordless-git-authentication/

**Comment by vbjay** [comment]
And https://superuser.com/questions/1700021/passwordless-ssh-login-into-wsl2-failing may help.

**Comment by mariolorenz** [comment]
@vbjay : Yes, i know this stuff. What i try to explain is, all solutions works fine with WSL2 + WSL2-based repos and "commandline git".
I ´ve no problems with OpenSSH Agents and Putty Agents on WSL2: "Commandline Git" use the agents that I´ve provided via .bashhrc.
My problem is GE.
GE use the WSL-Git if GE recognize a WSL2-Path. This is a very nice feature, because the WSL-Git is logically faster then Win-GIT on WSL-Paths.
BUT GE runs the WSL-Git without the .bashrc. So the WSL-Git doesn't know about my agent and therefore asks for the passwords every time.
In my Opion it has something to do that this hardcoded call **"wsl" -d Ubuntu git ...**. It is a direct call of Git in the wsl-container, without using any .bashrc files etc.

**Comment by vbjay** [comment]
So two options I can think of. 

See if there is a config for the container to say use this  bashrc file

OR

Ask for ge to add a setting or read from a specific git config value to call git including that path to the cli command causing it to load that bashrc file.

**Comment by vbjay** [comment]
I'd even on second option add a file exists check avdcif not don't pass value. Just to prevent invalid config issues.

**Comment by gerhardol** [comment]
wsl.exe runs the command in the specified distro, should be in the default shell. Make sure your commands are in non-interactive setup.
There are a few ways to configure how wsl.exe opens the shell in wsl, no customizations right now.

You should be able to find out the command to use from Windows, if there is a need to change how GE calls WSL from Windows.
Setups like this are not really expected, improvements may be required by those that require them.

**Comment by mariolorenz** [comment]
When I write "change or make changeable", then i mean this part: **wsl -d Ubuntu git** -> **wsl -d Ubuntu bash -ic git**

**Comment by gerhardol** [comment]
You can add a script called "git" that is first in your path
There are some preparation to replace git, not exposed in the settings:
https://github.com/gitextensions/gitextensions/blob/master/src/app/GitCommands/Settings/AppSettings.cs#L381

**Comment by mariolorenz** [comment]
Sounds good. Could you explain it?
If I understand it correct, than the content of the script should be "bash -ic git" (as replace of "git").
Where is the correct place of this script (What do you mean with "first in your path")?
Could you give an example of the script-filename / script-place / script-content?

Thank you!

**Comment by gerhardol** [comment]
Either edit GitExtensions.settings and add the arguments that fit. There is no quoting available, the simple quoting would not work either, the commands will need to be escaped.
Or create a script called "git" that wraps the arguments and calls the real git executable.

None of this is tested, I have not any templates or more suggestions right now. This was added in case it was needed, may require changes.
Patches are welcome.

**Comment by mariolorenz** [comment]
Hello again.

I try and play with both variants. But without luck. When I enter a section for "WslGitPath" in the GitExtensions.settings and fill it e.g. with _bash -ic git_ or _bash -ic \"git_ i run into the error "External Program returned non-zero exit code."
The second idea with the script that wraps git arguments is also not the correct way. Because i didnt want add more arguments to git. I want change the arguments of the wsl call that calls git ...

For testing and better understanding we can use the powershell:

- Enter the powershell
- go to the repo in the wsl-path: e.g.: cd \\wsl.localhost\Ubuntu\home\YOUR_WSL_USER\YOUR_PATH_TO_THE_REPO
- then enter one of the Original Lines from GE:
wsl -d Ubuntu git -c fetch.parallel=0 -c submodule.fetchJobs=0 pull --progress "origin"
(I would ask for the password, because git runs in this WSL-Context not interactive)

- the next line is the correct version with the shell in interactive-mode (.bashrc is loaded)
wsl -d Ubuntu bash ic 'git -c fetch.parallel=0 -c submodule.fetchJobs=0 pull --progress "origin"'
(Now I dont need a password, because the .bashrc with my agent is loaded)
You see the fine difference. The git-command is wrapped by **wsl -d Ubuntu bash ic '**_here comes the dynamic git-command from GE_**'**
So i need not a  "WslGitPath". I need a wrapper.

**Comment by gerhardol** [comment]
Add options to wsl

For instance the following causes WSL to read the non-interactive part of .bashrc.
You could replace git with a script too.
But in the non-interactive part you could execute what you want.

```
  <item>
    <key>
      <string>WslGitPath</string>
    </key>
    <value>
      <string>--shell-type login git</string>
    </value>
  </item>
```

**Comment by mariolorenz** [comment]
Thank you for the GitExtensions.settings snippet.

Is it possible that this setting is not used on any time?

Actual situation: 

I open in GE the WSL-Path-Repo. No error is thrown. This is a good sign. If I did any mistake in the WslGitPath-Optionm then i run into a Error-PopUp "External Program returned non-zero exit code." So GE use on this point the option.

BUT

When I pull the repository, in the PopUp with the pull-command, I see the old Command without the param "--shell-type login git". So I would ask again for the password. So I´ve the feeling, that the WslGitPath is not used on any time.

Is it possible?

**Comment by mstv** [comment]
You can verify the executed commands in GE's Git Command Log (hotkey `F12`).
Activate the capturing of call stacks and re-run the pull, please.
Then we can we see how the command is chosen.

**Comment by mariolorenz** [comment]
Wow, GE's Git Command Log (hotkey F12) is nice!

Here the log:

[log.txt](https://github.com/user-attachments/files/16645355/log.txt)

You see, the normal "switchings" and "jumps" between the repo inside of GE are called with "wsl -d Ubuntu --shell-type login git". Thats fine. But the important "push" and "pull", that are started in the pop-up , only use pure "wsl".

**Comment by mstv** [comment]
The copy of the call stack of `wsl	-d Ubuntu git push ...` would help. It is not stored in the log file.

**Comment by mariolorenz** [comment]
Here the second log. In line 133 starts a git pull, in line 189 a git push, the first call in line 1 is one of the correct once:

[log2.txt](https://github.com/user-attachments/files/16645468/log2.txt)

**Comment by gerhardol** [comment]
The setting is always used for almost all commands if you have added it correctly in the GitExtensions.settings in the repo root or the user profile dir. This is visible in the log.
The only intended exception is some difftools from dropdown menu and maybe some merge related.

In this case the commands with the popup used a hardcoded "git" executable, the same as the default. Will change that.
You will be able to test the PR as a portable build.

You may be able to set env var in some system setup (I expected the WSL.exe command to use the shell as you can opt ot from it) or set WSLENV in Windows.
But using a wrapper should work too.

**Comment by mariolorenz** [comment]
Wonderful. This looks good. Is there any possibility to get installable Binaries after merge? I´ll test it again. If it works, then the solution with the option "--shell-type login git" in the WslGitPath-Option is extremly helpfull and should be part of the documentation etc.

**Comment by gerhardol** [comment]
merged PR to master.
A portable build is available in the Artifacts tab: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/50423769/artifacts, just unpack the zip.

WSL Git is still kind of a hack, running the GUI in Windows and commands to WSL. It is what I use mostly myself in my daily work. But I do not know all use cases, WslGitPath was something added as something that was maybe successful.

**Comment by mariolorenz** [comment]
Hello again,

I try the latest Artifacts.Your change works. The parameter WslGitPath from GitExtensions.settings now also works in the popup.

BUT

This parameter did not solve my problem. I would also ask again for the password. I try the new line also from PowerShell, and I´ve the same behavoir. For comparison, let's see again. This new variant does not work:
wsl -d Ubuntu --shell-type login git -c fetch.parallel=0 -c submodule.fetchJobs=0 pull --progress "origin"
This variant will work:
wsl -d Ubuntu bash -ic 'git -c fetch.parallel=0 -c submodule.fetchJobs=0 pull --progress "origin"'

If I had a suffix, for example WslGitPathSuffix, then I could write in WslGitPath: **bash -ic 'git** and in WslGitPathSuffix then **'**
Then it would work.

What do you think?

Or maybe a solution with placeholder: bash -ic 'git {{placeholder}}'. You would replace the placeholder with your dynamic Git commands...

**Comment by mariolorenz** [comment]
Finally, I tried to implement the idea with the wrapper Git script.

In WSL, I created a GIT script:

sudo nano /usr/local/bin/git

With the following content:
```
#!/bin/bash
# This script calls the real git with additional arguments
/bin/git "$@"
```

And given appropriate permissions:

sudo chmod +x /usr/local/bin/git

Then entered in GE in WslGitPath-Option: bash -ic git

Normally, the command generated by GE will not work:
wsl -d Ubuntu bash -ic git -c fetch.parallel=0 -c submodule.fetchJobs=0 pull --progress origin
Because everything after "-ic" has to be in either quotation marks or single quotes. But the idea of ​​the wrapper script is that all parameters after "git" are passed on to the original git.

But it failed. GE freezes. I can't even provide a log. I had to delete the "git" script and remove the WslGitPath-Option: "bash -ic git".

I think my only solution will be, if my suggestion from the [comment](https://github.com/gitextensions/gitextensions/issues/11839#issuecomment-2295170853) could be implemented.

**Comment by iveoles** [comment]
Is this still an issue? Adding this option doesn't appear to resolve the issue of asking for the password each time. Whereas using git directly from the WSL commandline has no issues remembering.

```
<item>
    <key>
      <string>WslGitPath</string>
    </key>
    <value>
      <string>--shell-type login git</string>
    </value>
  </item>
```

**Comment by josefsabl** [comment]
It is still an issue :-(

**Comment by mstv** [comment]
SSH is rarely used by the maintainers.
So, contributions are welcome: a PR or a description what needs to be setup.
Most likely, PuTTY's PageAnt cannot be used. It needs to be setup inside WSL.

**Comment by gerhardol** [comment]
> SSH is rarely used by the maintainers. So, contributions are welcome: a PR or a description what needs to be setup. Most likely, PuTTY's PageAnt cannot be used. It needs to be setup inside WSL.

SSH with passwords is not commonly used.

The PageAnt equivalent in WSL will not be handled by GE, must be started and controlled manually.
