### ISSUE TITLE
[vNext] Help links are incorrect

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#11844]
### Environment

- Git Extensions 5.0.0.17886
- Build 39bbb0b5cf9341dce6ee6b3496bc16232291ea79
- Git 2.46.0.windows.1

### Issue description

Clicking on any of the ℹ️ buttons opens up a browser, but all links look as follows:
```
https://git-extensions-documentation.readthedocs.io/en/release-4.2/en/release-5.0/settings.html#anchor
```

Feels like the relatives paths are missing the leading `/`. 🤔

### Steps to reproduce

* Open Settings
* Navigate to `Git Extensions > Detailed > Diff viewer`
* Click on any of  ℹ️ buttons

**Comment by RussKie** [comment]
💭  ...or is it the case of the app trying to open `https://git-extensions-documentation.readthedocs.io/en/release-5.0/settings.html#anchor` link, but because we're yet to publish "release-5.0" docs, the docs website is bouncing the user to the existing release (thus, creating the incorrect URL)?

**Comment by gerhardol** [comment]
release-4.3 exists as well as an updated master. 4.2 is default
If next version is to be 5.0, I will scrap the 4.3 branch and create a 5.0 instead

**Comment by gerhardol** [comment]
release-5.0 does now exist, 4.3 is hidden and will be removed

**Comment by RussKie** [comment]
Thank you @gerhardol
