### ISSUE TITLE
[Feature Request] Choose account for each repo

### ISSUE THREAD

**Issue by angeousta** [gitextensions/gitextensions#11852]
### Feature description

It would be nice to be able to set git credentials (user, email, psw/token) for each repo.

Very useful to people working on different projects with different github users

### Proposed solution

A new setting for each repo for choosing github account associated to that repo

**Comment by RussKie** [comment]
Could you please elaborate on your request?
I work in multiple repos with some being in different hosting tenants with different users and I can interact with the repos without any issues.

**Comment by gerhardol** [comment]
"Repo management" is handled by Git and the Git Credential Manager or PuTTY.
Git Extensions has some integration with PuTTY/pageant to start that app if needed but that is not related to any repo.

**Comment by mstv** [comment]
Are you looking for this:

![image](https://github.com/user-attachments/assets/63ed2d14-fdba-418f-ae1c-223143079fa2)

**Comment by astos-marcb** [comment]
@angeousta the only thing _not_ supported at the moment is selecting a repository-based SSH back end.
But this should not be an issue, credentials (private keys) can be [converted](https://www.simplified.guide/putty/convert-ssh-key-to-ppk).

Repo settings are linked to Git configuration for identity (`user.name`, `user.email`) and credentials via
- HTTP auth with [`http.extraheader`](https://stackoverflow.com/questions/64800010/why-does-http-basic-auth-works-using-git-c-http-extraheader-authorization-ba) or in remote URL
- SSH identity for [host alias](https://www.baeldung.com/linux/alias-hostname) in `remote.<origin>.url`

**Comment by vbjay** [comment]
You can run git config ... to set repo specific overrides. For example user.signingkey.
