### ISSUE TITLE
[BUG] when restoring (save as/reset) files from past commits, they get corrupted.

### ISSUE THREAD

**Issue by denis-art-hg** [gitextensions/gitextensions#11885]
### Environment

- Git Extensions 4.2.1.17611 (and a few past versions ones too)
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 6.0.25
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

### Issue description

I noticed it a long time ago, several versions ago, but still have not been corrected. 
I've always used it before.
any files when trying to save or restore from past commits turn out to be corrupted (pictures are black - empty, prefabs are broken, etc.)
I use other git clients, but I like gitextensions more.

### Steps to reproduce

open the file history, 
select the any last commit,
try to do save as
and to check the received file.
* it is convenient to do this with a picture, it is easy to check

### Did this work in previous version of GitExtensions?

yes, there was a problem a few previous versions ago. quite a while ago. I tolerate it )

**Comment by mstv** [comment]
I cannot reproduce the issue - neither with code files nor with a .png picture (tested with the pre-release 5.0).

**Comment by mstv** [comment]
no response from author
