### ISSUE TITLE
"Replace tracking reference" doesn't work on the Push dialog

### ISSUE THREAD

**Issue by patiqs** [gitextensions/gitextensions#11899]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False

### Issue description

The "Replace tracking reference" checkbox doesn't have any effect.
![image](https://github.com/user-attachments/assets/e5e488bc-a6f7-4446-82a3-7f80a3c806e1)

### Steps to reproduce

- Open the push dialog
- Check "Replace tracking reference"
- Modify the "to" branch to something else
- Push
- Open the push dialog again

The "to" branch returns to the original value instead of the modified one

### Did this work in previous version of GitExtensions?

Yes Version 4.2.1 

### Diagnostics

It creates the following command:
"C:\Program Files\Git\bin\git.exe" push -u --progress "origin" refs/heads/work1:refs/heads/other

**Comment by RussKie** [comment]
Check the "Default pull behaviour" tab of the "Remotes" dialog.

I would say the command is correct, however, the "to" combo isn't populated with the actual tracking branch.
![image](https://github.com/user-attachments/assets/fb3fa8d6-6dac-4a18-9338-24a1ee164ab1)

**Comment by patiqs** [comment]
> Check the "Default pull behaviour" tab of the "Remotes" dialog. 
The "Default pull behaviour" dialog shows the proper value.

> I would say the command is correct, however, the "to" combo isn't populated with the actual tracking branch. 
You are right. My bad. I'm not that familiar with the git cli. The command is good

However I noticed an other interesting behavior.
To reproduce:
1 - Let's say you have a setup like your comment: 'readme' -> 'origin/readme1'
2 - Open the pull dialog. The "to" will be 'readme' which seem to be copied from the left
3 - Navigate to "Push tags" or "Push multiple branches" tab
4 - Go back to "Push branches" tab
5 - The "to" gets modified to the expected "readme1"

**Comment by Tinister** [comment]
+1, GitExtensions also ignores the tracking branch when you press the "Push" button from the Commit window.

Which is particularly nasty since in that case there's no prompt to pick which branch to push to.
