### ISSUE TITLE
Simplified Chinese translation error.

### ISSUE THREAD

**Issue by transtone** [gitextensions/gitextensions#11890]
### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

Simplified Chinese translation not complete. but with many traditional Chinese words.

like: https://github.com/gitextensions/gitextensions/blob/master/src/app/GitUI/Translation/Simplified%20Chinese.xlf#L3363-L3368

### Steps to reproduce

fix Simplified Chinese translation with chatgpt?

**Comment by gerhardol** [comment]
Translation sources are in Transifex, done by the individuals that joins there.
See https://github.com/gitextensions/gitextensions for links.
