### ISSUE TITLE
Changelog for version 5.0 missing

### ISSUE THREAD

**Issue by deining** [gitextensions/gitextensions#11898]
### Environment

- Git Extensions 4.2.1.17611
- Build b0c0b284876b63c52c77195ada82a85bfadbb083
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.33
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When starting up GitExtensions, a popup appeared:

![grafik](https://github.com/user-attachments/assets/38d0ed92-9096-4bfa-af50-f79ae0d5760a)

Inside this popup, the link to the changelog is broken:

https://github.com/gitextensions/gitextensions/blob/master/GitUI/Resources/ChangeLog.md

404 - page not found
The `master` branch of `gitextensions` does not contain the path `GitUI/Resources/ChangeLog.md`.

### Steps to reproduce

Simply open the menu item `Help` - `Check for updates`.

### Did this work in previous version of GitExtensions?

There is a [changelog](https://github.com/gitextensions/gitextensions/blob/release/4.1/GitUI/Resources/ChangeLog.md) for version 4.2.1 (branch `release/4.1`), but none for branch `release/5.0` yet.

**Comment by gerhardol** [comment]
https://github.com/gitextensions/gitextensions/releases

**Comment by astos-marcb** [comment]
This is a (unfixable) victim of the [repo restructure](https://github.com/gitextensions/gitextensions/commit/8863b8b46fc42b416f7493eaad35138e8c80ce41) with (old) code still assuming unchanged location.

**Comment by RussKie** [comment]
The link should point to the GitHub release page. Maintaining the markdown file is burdensome, and it no longer delivers any value over the GitHub release page.

**Comment by drewnoakes** [comment]
Just hit this. As a major release, 5.0 promises big things, and getting a 404 looks bad. Can we just reinstate a file in that location with a link explaining that release details have moved to the GitHub releases page?

**Comment by drewnoakes** [comment]
Also, if we're not going to update it any longer then perhaps we can delete https://github.com/gitextensions/gitextensions/blob/master/src/app/GitUI/Resources/ChangeLog.md

Or at the very least, include a comment at the top explaining that this doc is no longer updated, and that the GitHub releases page should be used instead, with a link.

**Comment by RussKie** [comment]
It is an unfortunate situation, but once users update to v5 the link is working again. I don't want to pollute the repo with dummy folders.

> Also, if we're not going to update it any longer then perhaps we can delete [`master`/src/app/GitUI/Resources/ChangeLog.md](https://github.com/gitextensions/gitextensions/blob/master/src/app/GitUI/Resources/ChangeLog.md?rgh-link-date=2024-09-11T05%3A01%3A55Z)
> 
> Or at the very least, include a comment at the top explaining that this doc is no longer updated, and that the GitHub releases page should be used instead, with a link.

This is something to be done in the future.
