### ISSUE TITLE
Clone new Repository 'hangs' indefinitely

### ISSUE THREAD

**Issue by harrisonmeister** [gitextensions/gitextensions#1189]
After installing 2.40 gitextensions. when trying to clone a new github repository the process window 'hangs' and doesnt provide any feedback after the following

c:\Program Files (x86)\Git\bin\git.exe clone -v --recurse-submodules --progress "https://github.com/SomeRepoToClone.git" "D:/Git/SomeRepoToClone"
Cloning into 'D:/Git/SomeRepoToClone'...

**Comment by mikeschinkel** [comment]
@harrisonmeister Just to let you know, your message helped me solve a problem. I was using `git@` but I had mistyped `github.com` as `gihub.com` and just could not _"see"_ it.  Changing to the correct domain solved the problem, so thanks!

**Comment by dougbacelar** [comment]
My problem was that the following folder was missing:

`C:\Program Files\Git\mingw64\libexec\ssl`

Going one folder above (`C:\Program Files\Git\mingw64`), I realized the `ssl` folder was there, so I just copied it inside the `libexec` folder

Then I could successfully run the following:
1. `git init`
2. `git remote add origin https://github.com/dougbacelar/myrepo`
3. `git fetch`
