### ISSUE TITLE
Going on a hunger strike until dark mode theme is reimplemented 

### ISSUE THREAD

**Issue by morphtek** [gitextensions/gitextensions#11904]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Setting the theme to dark high contrast gives only darkened line on the commits bar , going on a hunger strike until fixed , MY LIFE IS IN YOUR HANDS 

### Steps to reproduce

open git extension > setting > appearance > color > high contrast dark theme > reset git extension

**Comment by gerhardol** [comment]
Duplicate of #9191

Windows high contrast dark Mode is required for the HE theme. (That is ugly.)

It is not technically possible to override colors in .net8 as it was in .net4. there are some experimental support in the upcoming .net9, but there seem to be issues so it is not known if it is possible.

**Comment by morphtek** [comment]
![image](https://github.com/user-attachments/assets/a4d82ed0-0f0d-48c2-8748-9f0fd25885d4)

**Comment by venom8898** [comment]
RIP brother. Absolutely insane that dark mode isn't becoming a STANDARD default in everything. I feel you. "That is ugly" Figure it out guys.

**Comment by gmcelhanon** [comment]
I'm still running this version. and will until Dark mode makes its return:

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.45.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET Framework 4.8.9277.0
- DPI 96dpi (no scaling)

**Comment by david-at-edlio** [comment]
This is my main git client and I won't update it until we get the long overdue dark mode implementation. I'm using OLED screens so dark mode it pretty much essential.

**Comment by mstv** [comment]
We are all volunteers. Have you ever considered contributing instead of moaning? As .NET 9 with some dark mode support has been released, there is a WIP PR. (I will not link this annoying thread to that PR.)

**Comment by morphtek** [comment]
> We are all volunteers. Have you ever considered contributing instead of moaning? As .NET 9 with some dark mode support has been released, there is a WIP PR. (I will not link this annoying thread to that PR.)

its my fetish to find software that doesnt have a dark mode settings and then to go moan on its support channels/forums/etc

**Comment by vbjay** [comment]
5 months... Call Guinness world records. That's a lonnnngggggg hunger strike.

**Comment by astepforward** [comment]
I regret updating from 3.xx to 5.xx. I'm leaving to another git client or reinstalling 3.xx until dark theme support is added.

**Comment by gerhardol** [comment]
.net9 support for dark mode is experimental with many visual issues. It is not intended to be general theming (which is fine for most users but limited ways to override). MS have set many reported issues to be fixed by the community. 
Microsoft could decide to remove Winforms darkmode, but it seems like it stays.

Some controls in GE have to be replaced to use dark mode with .net9, that is a work in process.

Winforms dark mode is quite gray, not so well looking and hard to get contrast for colors. It is very time consuming to do the color adjustments to be well balanced, a real designer that actually defines colors could help.
For someone that really want to use it, the PR publish builds.

**Comment by pmiossec** [comment]
> Time to eat!

Maybe it's even more the time, for all those that complained, to make a donation to the project so that @gerhardol will get a well deserved "slice of the cake".

**Comment by michaellavoie** [comment]
Great suggestion - I just donated - thanks you to the whole team, but extra thanks to @gerhardol !!!

**Comment by RussKie** [comment]
> > Time to eat!
> 
> Maybe it's even more the time, for all those that complained, to make a donation to the project so that [@gerhardol](https://github.com/gerhardol) will get a well deserved "slice of the cake".

Now I have to get Gerhard to eat 🎂 
🤣

**Comment by morphtek** [comment]
![Image](https://github.com/user-attachments/assets/a4326a7c-f187-4694-8908-25f3b413cb13) do we have dark theme again

**Comment by gmcelhanon** [comment]
> Great suggestion - I just donated - thank you to the whole team, but extra thanks to [@gerhardol](https://github.com/gerhardol) !!!

Been running the nightly build for a week or two, and the reimplemented dark mode looks great. Just matched the donation from @michaellavoie . Thanks a bunch @gerhardol. And my eyes thank you too...

**Comment by RussKie** [comment]
Thank you, that's very kind of you.

**Comment by brianjlacy** [comment]
Hey all, no hunger strikes (or complaints!) over here, just deeply curious 😁 any word yet on a target version for legit dark mode? As has been mentioned the high contrast dark is um... let's go with, "not ideal". 😅

(Although tbf, it would *almost* be an improvement over the default if the commit messages were readable. 🤷)

Anyhow... I'm running 5.2.1.18061, if anyone's curious. Love the app, 'tis my main git driver for 8+ yrs and going. Thanks for all the hard work. 🙏

*Now, to go find that Donate link and put my money where @morphtek's mouth is...*

**Comment by gerhardol** [comment]
There is a 6.0.0 Alpha in releases. A 6.0.1 with a few fixes is in the works, maybe a RC to prepare translations and a stable interface for plugins. So a number of weeks still.

**Comment by emirkilinc-exact** [comment]
I'm using the version of 5.2.1. So, how did you install the dark theme?
 
I tried those:
1- Use windows dark mode
2- Change appereance settings for GitExtensions (no settings about dark or dark+)
3- Configure GitExtensions.settings (no tags about <Theme>)

**Comment by gerhardol** [comment]
> I'm using the version of 5.2.1. So, how did you install the dark theme?

There is an 6.0.0 Alpha in Releases.
You can use that as a portable to try it out

**Comment by brianjlacy** [comment]
> I'm using the version of 5.2.1. So, how did you install the dark theme?

@emirkilinc-exact 
5.2.1 does not yet have a proper dark theme, but if you are wanting to try out the high contrast dark theme:

Under Appearance settings there's another section, Colors. It's on that screen. Just be aware, it's not all that useful as yet.

@gerhardol 
I'll try the 6.0.1 RC when it's ready, thanks again for your efforts!

**Comment by morphtek** [comment]
the hunger strike ends thank you all for participating

![Image](https://github.com/user-attachments/assets/2911770e-5e71-492c-afdc-93d7601ac075)

**Comment by ws-rob** [comment]
What a rollercoaster. Glad @morphtek survived
