### ISSUE TITLE
Pressing arrow keys with a menu open (either context or main) navigates the graph instead of menu items

### ISSUE THREAD

**Issue by xperiandri** [gitextensions/gitextensions#11910]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 240dpi (250% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 9.0.0-rc.1.24452.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Pressing arrow keys with a menu open (either context or main) navigates the graph instead of menu items

### Steps to reproduce

Select row in the graph
Open the context menu on any row
Press an arrow up or down key
See that the focus is on the graph and not on the menu

### Did this work in previous version of GitExtensions?

Worked in 4.x

**Comment by RussKie** [comment]
I can't repro. What am I missing?

https://github.com/user-attachments/assets/aff6e312-86e2-4347-8de6-e5f2f79af797

**Comment by xperiandri** [comment]
Looks like it was some glithc. Works now
