### ISSUE TITLE
Araxis difftool not work

### ISSUE THREAD

**Issue by SanteR1** [gitextensions/gitextensions#11926]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.45.2.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

If you select difftool "Araxis," a window opens with Araxis in which the error "path not found" is not created, the temporary folder "git-difftool.a01372" is not created.

![image](https://github.com/user-attachments/assets/f42d2b76-2c5d-4dec-a454-8906a1bff2a1)

![image](https://github.com/user-attachments/assets/a4a5127f-3226-43ae-a271-4ed53cfeeb8a)

![image](https://github.com/user-attachments/assets/ca8386f8-e9ea-4a00-891f-e062c5e08822)

If you change it to winmerge difftool, then a folder is created along this path and everything works.

![image](https://github.com/user-attachments/assets/b9f6bd7a-df4d-46b0-b02f-cd25180186bd)

### Steps to reproduce

in description error

### Did this work in previous version of GitExtensions?

yes

**Comment by RussKie** [comment]
If you open the Git command log (F12) you should see the command being executed (`git difftool --tool=araxis....`). You can check whether the command is correct.

**Comment by SanteR1** [comment]
Working dir is true.
`File name:   C:\Program Files\Git\cmd\git.exe
Arguments:   difftool --tool=araxis --find-renames --find-copies --no-prompt --dir-diff "203d750a094f0b7cb651ea7fd5dd77d3e0d1ccf4" "cd2b50383c7626a5493ac30bb51334184bdd8363"
Working dir: C:\Users\**dd**\source\repos\**nt**\Jackett\
Process ID:  5716
Started at:  2024-09-18T16:44:05.6285322+05:00
UI Thread?:  False
Duration:    1241,428 ms
Exit code:   0
`

**Comment by mstv** [comment]
Git has / expects two settings for each difftool. I have never seen it working without a configuration of the full command line.

![image](https://github.com/user-attachments/assets/797a2fc5-9900-4b5a-aec6-c0ebbc2f81e5)

**Comment by SanteR1** [comment]
i have two set up

![image](https://github.com/user-attachments/assets/4760df1a-7fa4-4f9e-890f-1bca47d6f0a6)

@RussKie this is from Command log (F12)

![image](https://github.com/user-attachments/assets/5c07db2d-7d9e-44a4-9837-01cad1b9164b)

**Comment by mstv** [comment]
Does Araxis support directory diffs? (I don't remember.)
Please try to open a diff on a _file_ (with actual changes) first, i.e. from the Diff tab.

RussKie meant that you should copy that command and run it from command prompt or git bash and verify whether that works.
GE cannot do more than calling git. _Git_, but not GE, starts the diff tool.

**Comment by SanteR1** [comment]
If you use the simple cmd command, it works

![image](https://github.com/user-attachments/assets/8ec60894-3b54-43e8-a48a-82bf304d7d97)

**Comment by SanteR1** [comment]
This option does not work

![image](https://github.com/user-attachments/assets/b5c940bf-988c-4ffc-9586-276eb87ef281)

**Comment by mstv** [comment]
This something between Git and Araxis. GE cannot help here.

**Comment by gerhardol** [comment]
GE tries to simplify adding diff tools, setting commands and paths.
However, GE does not really know the capabilities of a certain difftool. There are for instance some versions of kdiff3 that supports directory diff. So all difftools are added to the possible diff tools.

GE could exclude Araxis as a difftool, but that would be a guess based on the name only.

**Comment by pmiossec** [comment]
Yes, not clear if the diff is made on a file or a folder...

And I don't known how git behave on a folder diff.
