### ISSUE TITLE
Garbled characters in rebase branch interactively.

### ISSUE THREAD

**Issue by ooxxTaiwan** [gitextensions/gitextensions#11934]
### Environment

- GitExtensions version: Git Extensions 5.0.0.17897
- GIT version:  Git 2.43.0.windows.1
- OS version: Microsoft Windows NT 10 19045.0
- .NET version:  .NET 8.0.8

### Issue description

when using rebase with selected commit interactively, garbled characters appear.

<img width="497" alt="image" src="https://github.com/user-attachments/assets/284e15ff-5051-40a6-b8a1-614c93b1a7c1">

### Steps to reproduce

type chinese in commit message, than rebase with selected commit interactively.

### Did this work in previous version of GitExtensions?

it work fine in Git Extensions 4.0 (in the same git repository / the same system / diff .net core version).

**Comment by pmiossec** [comment]
Bisected to this line change: https://github.com/gitextensions/gitextensions/pull/11747/files#diff-1b2298746cee2e678b64811a64020c016440c0659efd4f143251229084d17da9L760

**Comment by mdonatas** [comment]
A bigger problem is that `Interactive Add` no longer works because of this. I'll create a PR with a potential fix.

**Comment by mdonatas** [comment]
Testing this case specifically by setting editor in Git Config to a local build `"C:/Workplace/personal/gitextensions/artifacts/Debug/bin/GitExtensions/net8.0-windows/GitExtensions.exe" fileeditor`

![Image](https://github.com/user-attachments/assets/fd2f3564-0fb4-4d9d-97b3-179cc3fc714c)
