### ISSUE TITLE
Commit option "Do not sign commit" commits with git's default setting which could force signing.

### ISSUE THREAD

**Issue by corbob** [gitextensions/gitextensions#11931]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When creating a commit, the Options drop down has 3 options for signing a commit `Do not sign commit`, `Sign with default GPG`, and `Sign with specific GPG`. The default option of `Do not sign commit` actually signs it if git is configured to sign commits by default.

### Steps to reproduce

1. Configure git to sign commits by default. In my configuration this is with `user.signingkey` set to my GPG key, and `commit.gpgsign` set to true.
2. Create a new commit.
3. Check the options and ensure that it is set to "Do not sign commit"
4. Note that the new commit ends up signed.

**Comment by gerhardol** [comment]
@corbob Please try #11963

**Comment by corbob** [comment]
@gerhardol can confirm that works as I would expect it to.
