### ISSUE TITLE
Branches filter is broken after update to 5.0.0

### ISSUE THREAD

**Issue by longdv0701** [gitextensions/gitextensions#11942]
Sorry if this issue is duplicate, i cannot find current open issues related to this, so i open one.

### Environment

- GitExtensions version:
  + Git Extensions 5.0.0.17897
  + Build `2a3b78b868e7757d986c49bbfc03406b38f1ffe9`
- GIT version: Git 2.46.2.windows.1
- OS version: Microsoft Windows NT 10.0.22631.0
- .NET version: .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

`Branches` filter in UI is kind of unusable after i update to version 5.0.1, autocomplete is kind of broken

![git_ex_bug_1](https://github.com/user-attachments/assets/ab4dc519-6b8f-4f1b-ba55-b50ca851c4f3)

### Steps to reproduce

Steps are like this:
- i have branches like this: `business-2/feature/location-status-management`
- i cannot filter by the `location-status-management` part anymore
- when typing `l` it will autofill to `local` (i do have branch named `local`)
- typing `o` next will replace all word to whatever was found, then `cation` will replace all word again

### Did this work in previous version of GitExtensions?

Filter does work in older version:
- i can type full word `location` in filter input, then choose branches from result dropdown

If i remember correctly, my version before updating was probably 4.2.1

**Comment by mstv** [comment]
I can reproduce this with HEAD but could not with 5.0.0 and the GE repo.
Bisected to #11864, which subtly made the bug occur more often: It moved `BranchDropDownMinWidth = 300;` to another file and decreased the value to `200`.
I think if `tscboBranchFilter.ComboBox.ResizeDropDownWidth` changes the size, it always closes the dropdown, which switches to the behavior complained about.
