### ISSUE TITLE
Trust this repository still not working

### ISSUE THREAD

**Issue by mrforsythexeter** [gitextensions/gitextensions#11958]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.46.2.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

![Image](https://github.com/user-attachments/assets/8d2ddb19-1a23-438a-acfd-9a17a896f598)

when pressing trust this repository, the software simply loops back to the repo's home screen and doesn't allow it to be opened.

Running as "admin" does allow it to be opened, however this doesn't feel like a solution, of if you require evaluation, you should request it.

### Steps to reproduce

Open a project from users home directory.

### Did this work in previous version of GitExtensions?

No, I have seen this issue for a while, over multiple versions and windows installs.

**Comment by mstv** [comment]
most likely broken by changed output from git.exe

**Comment by mrforsythexeter** [comment]
The folder is owned and controlled by me in my standard document location. However I do understand you don't control git, which is emitting the message.

I would love to have time to correct the issues and submit a PR, but I don't. I understand its a volunteer project, and its simple the best project. Also, not all developers work on all languages.

If the software can't perform the action correctly, it shouldn't offer a solution (button), or it should capture the error from git command being issued, are you telling me the exit code of the command is successful? If you believe it is logging the message, instruction on how to retrieve it would be great.

**Comment by mstv** [comment]
> If the software can't perform the action correctly, it shouldn't offer a solution (button), or it should capture the error from git command being issued, are you telling me the exit code of the command is successful? If you believe it is logging the message, instruction on how to retrieve it would be great.

I fully agree. At least the exit code is traced in the Git Command Log (`F12`).
Since this volunteer project has a few core developers only, we need contributions from users who encounter edge cases.

So, please manually run the command proposed by git on the command line, i.e.
```
git config --global --add safe.directory 'C:\Users\...........\Code\Ac....'
```

I guess, it will not work - as I said:

> Most likely, it will require double quotes.

So, please tell us whether the adapted command solves your issue:
```
git config --global --add safe.directory "C:\Users\...........\Code\Ac...."
```
Perhaps, git even expects forward slashes instead of the backslashes in the path to your repo.
