### ISSUE TITLE
Reset is onerous as confirmation is required repeatedly, as it needs 3 clicks

### ISSUE THREAD

**Issue by CJYate** [gitextensions/gitextensions#11967]
### Feature description

Suggestion: provide an option to remove the need for confirmation on Reset.  
Or maybe allow at least ENTER for confirm and ESCAPE for cancel.  Enter cancelling the action is odd.

I currently need to press R->Tab->Enter (or R->Tab->Space). 

### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.47.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by gerhardol** [comment]
Reset is destructive, so it is easy to loose data (you may recover lost objects, but not always?). It is easy to 'slip'...
GE has enough options already.
I will not vote against a setting for this though.
But there are quite some situations where reset is done.

**Comment by RussKie** [comment]
We had multiple complaints about users losing changes, and the "Reset" was made difficult on purpose to avoid the loss of data.

I don't think we should be accepting changes that would make this action easier.

> ...and ESCAPE for cancel. Enter cancelling the action is odd.

Could you please clarify?

**Comment by CJYate** [comment]
If you press Enter after R(eset), this actions the cancel, which has been
set as the default dialog action.   That's unusual behaviour.

I would have strongly expected the dialog to accept Enter for okay, and
Escape for cancel. Anything else seems jarring.

Reset is dangerous but I've decided to do it, so a single click
confirmation, without taking my hand from the keyboard, is appropriate.
Enter key is idiomatic for "are you sure?" -> "YES"

**Comment by vbjay** [comment]
Nope. It is made this way on purpose. Don't care that it is easier for you. It was done so you have to really try. Reflexive enter will bite you in the butt one way and you will be thankful it didn't work.

**Comment by RussKie** [comment]
> If you press Enter after R(eset), this actions the cancel, which has been set as the default dialog action. That's unusual behaviour. I would have strongly expected the dialog to accept Enter for okay, and Escape for cancel. Anything else seems jarring.
> Enter key is idiomatic for "are you sure?" -> "YES"

That's not true. Enter is idiomatic for confirming the selection. In our case, the default selection is "No" to avoid data loss.
