### ISSUE TITLE
[Winget] Public "privacy policy" required for new winget manifests

### ISSUE THREAD

**Issue by namtab00** [gitextensions/gitextensions#11966]
### Feature description

I've tried setting up [the PR for the 5.0 release](https://github.com/microsoft/winget-pkgs/pull/179184) with `winget`.

Their pipeline [validation fails](https://github.com/microsoft/winget-pkgs/pull/179184#issuecomment-2397337621) due to an invalid link to the "privacy policy" for the software.

![Image](https://github.com/user-attachments/assets/d6b20911-5d07-44ae-a439-3cea7079bc35)

I haven't seen such a file in sources, maybe the team should setup one?

Maybe something like [this one](https://gist.github.com/devver/380044) ?

### Environment

- GitExtensions version: 5.0
- GIT version: irrelevant
- OS version: irrelevant
- .NET version: irrelevant

**Comment by bdukes** [comment]
It looks like there's a privacy policy at https://raw.githubusercontent.com/gitextensions/gitextensions/refs/tags/v5.0/setup/assets/PrivacyPolicy.md

**Comment by namtab00** [comment]
@bdukes  oooh, thank you, I surely didn't know where to look.

Will modify the winget PR and if all is well will close this.

**Comment by namtab00** [comment]
I tried preparing the winget manifest for the 5.0 release, as seen in https://github.com/microsoft/winget-pkgs/pull/179204.

Automatic validation with their pipelines fails with an error I'm entirely unqualified to comprehend (see [here](https://github.com/microsoft/winget-pkgs/pull/179204#issuecomment-2405985785) the feedback provided by the winget team).

If no-one can / has time / whatever else reason to look into this, I'll just close that PR.

...I really tried to be of minimal help with this, but such is life..

@gerhardol , @RussKie  sorry for the pings, but I'm in way over my head on this and it's above my knowledge of GitExtensions.
I'm pinging you in particular because I couldn't tell who are the "main" maintainers and picked you based on amounts of commits and their relative recency.

**Comment by RussKie** [comment]
@namtab00 you could say we're the main maintainers, but we don't anything to do with winget, chocolatey or any other package/delivery mechanisms beyond this repository and certain NuGet packages on nuget.org.
I wouldn't know where to start with winget or its packaging/release procedures.

**Comment by RussKie** [comment]
> ![Image](https://github.com/user-attachments/assets/fcac95e0-939f-4339-bc8d-394303ea7ba0)

This doesn't look correct, the correct location of the PrivacyPolicy.md is https://github.com/gitextensions/gitextensions/blob/master/setup/assets/PrivacyPolicy.md

![Image](https://github.com/user-attachments/assets/1a313c8e-b3e3-4b76-bd94-ca54d2c0418e)

**Comment by namtab00** [comment]
@RussKie Yes, @bdukes pointed me to the correct privacy policy.

You'll notice I closed the first PR https://github.com/microsoft/winget-pkgs/pull/179184. 

I tried validating again with the correct link to the privacy policy via PR https://github.com/microsoft/winget-pkgs/pull/179204, which is now blocked by an installation issue I've already linked to, [here it is](https://github.com/microsoft/winget-pkgs/pull/179204#issuecomment-2405985785) again.

I have no idea how do diagnose that, so if there's no interest in maintaining a winget repo presence from GitExtensions v5 going forward, I'll close all of this and all is all. 

I personally use winget heavily, and tried to help with the preparing the 5.0 version of GitExtensions hoping it would be easy and of help to you maintainers...

**Comment by RussKie** [comment]
I appreciate you dedicating your time and efforts trying to help. I wouldn't know how to help with the winget issue though, sorry.

I personally don't use winget at all (sometimes chocolatey, if needed), so I don't have any feelings about the app being in winget or not. I guess, the more distribution channels - the better, but there's only so much I (or other maintainers) can do.

**Comment by mstv** [comment]
WinGet seems to be a popular package manager. I think the GE package should be updated there. (Otherwise, we should remove all versions.)
The [docs](https://learn.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minschema%2Cversion-example) mention that the installer is executed in quiet mode, i.e.
```
GitExtensions-x64-5.0.0.17897-2a3b78b86.msi /q
```
is called - most likely.
This does not install anything in my test VM.
Though the previous installer `GitExtensions-4.2.1.17611-b0c0b2848.msi` behaves the same. So, I wonder how WinGet was able to install the previous versions although the YAML files differ in version numbers only.

**Comment by mstv** [comment]
`GitExtensions-*.msi /q` works well if run in an elevated shell.
Do we need to tell WinGet that elevation is required?
Perhaps by adding:
```
  ElevationRequirement: elevationRequired
```
to the `Installer` section.

**Comment by namtab00** [comment]
@RussKie Yes, @bdukes pointed me to the correct privacy policy.

You'll notice I closed the first PR https://github.com/microsoft/winget-pkgs/pull/179184. 

I tried validating again with the correct link to the privacy policy via PR https://github.com/microsoft/winget-pkgs/pull/179204, which is now blocked by an installation issue I've already linked to, [here it is](https://github.com/microsoft/winget-pkgs/pull/179204#issuecomment-2405985785) again.

I have no idea how do diagnose that, so if there's no interest in maintaining a winget repo presence from GitExtensions v5 going forward, I'll close all of this and all is all. 

I personally use winget heavily, and tried to help with the preparing the 5.0 version of GitExtensions hoping it would be easy and of help to you maintainers... 

    @mstv thanks for inquiring, I'll try to set that flag in the manifest if I can figure out where exactly, on the last PR I've linked, and report back here with the outcome.

**Comment by namtab00** [comment]
> `GitExtensions-*.msi /q` works well if run in an elevated shell.
> Do we need to tell WinGet that elevation is required?
> Perhaps by adding:
> ```
>   ElevationRequirement: elevationRequired
> ```
> to the `Installer` section.

@mstv thanks for inquiring, I'll try to set that flag in the manifest if I can figure out where exactly, on the last PR I've linked, and report back here with the outcome.

**Comment by namtab00** [comment]
@mstv [My PR](https://github.com/microsoft/winget-pkgs/pull/179204) for the winget v5 update has been manually validated by the winget team.

The v5 for GitExtensions should now be available via winget.

I'm closing this issue.

**Comment by RussKie** [comment]
This is great to hear. Thank you
