### ISSUE TITLE
Broken symbols

### ISSUE THREAD

**Issue by semmaxim** [gitextensions/gitextensions#11972]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.47.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.10
- DPI 144dpi (150% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

Broken russian symbols:
![Image](https://github.com/user-attachments/assets/55bc034d-535b-422c-982c-f137fed705f7)

### Steps to reproduce

Create or change file by russian symbols and open UI.

### Did this work in previous version of GitExtensions?

No.

**Comment by seky16** [comment]
duplicate #11934 ?

**Comment by RussKie** [comment]
How's your encoding s configured?
![Image](https://github.com/user-attachments/assets/2ac9f3cc-cead-4a26-95a3-3b2ec4c39c76)

Does it work outside Git Extensions?

**Comment by evenkov** [comment]
I have the same issue with Cyrillic(Bulgarian) then make interactive rebase and must edit my commits. Here is my GitExtension environment:
- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.44.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET 8.0.10
- DPI 168dpi (175% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.26 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

Here is rebase winwod with problem Cyrillic:
![Image](https://github.com/user-attachments/assets/98a8a204-9382-47c5-91d8-2cc45a2127cc)

With previous version there was no problem with encoding. My settings are the same.
Can You told me from where the problem can be? If I try to change Fonts, but which ones?

**Comment by evenkov** [comment]
I can confirm than when I set to external Editor(Notepad++) unicode strings are **OK**. The disadvantage of Notepad++ is the lack of color formatting!

**Comment by mstv** [comment]
Cannot reproduce neither with current dev build nor with 5.0 portable with default settings.
Might it depend on the font used?

![Image](https://github.com/user-attachments/assets/76804b61-c65c-47c0-8d46-13aa71bb0cfc)

**Comment by pmiossec** [comment]
> I can confirm than when I set to external Editor(Notepad++) unicode strings are **OK**. The disadvantage of Notepad++ is the lack of color formatting!

VSCode is indeed better for that.

**Comment by evenkov** [comment]
> Cannot reproduce neither with current dev build nor with 5.0 portable with default settings. Might it depend on the font used?
> 
> ![Image](https://github.com/user-attachments/assets/76804b61-c65c-47c0-8d46-13aa71bb0cfc)

I have the same default configuration and there is problem with unicode strings on internal editor

**Comment by evenkov** [comment]
> > I can confirm than when I set to external Editor(Notepad++) unicode strings are **OK**. The disadvantage of Notepad++ is the lack of color formatting!
> 
> VSCode is indeed better for that.

Thanks! With VSCode maybe the best view for me!!!

**Comment by evenkov** [comment]
@pmiossec I can confirm fixing issue:
![Image](https://github.com/user-attachments/assets/a48adb82-283f-461b-ad3a-996b8ae3be93)

- Git Extensions 5.1.0.17951
- Build 55414f0e7a784c41f6d627c823d12e0c8bc61020 (Dirty)
- Git 2.47.0.windows.2
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.10
- DPI 144dpi (150% scaling)
- Portable: True
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pmiossec** [comment]
@evenkov I was pretty sure your bug was fixed because it seems the same one but I'm very interested by @semmaxim feedback because it could be a different one (even if 🤞 it is in fact the same also).

@semmaxim do you think you could spend some time testing it? It will be really appreciated.
