### ISSUE TITLE
"Branch to push" in Push-dialog is prefilled with HEAD instead the currently active branch

### ISSUE THREAD

**Issue by tih2010** [gitextensions/gitextensions#11970]
### Environment

- GitExtensions version: 5.0.0.1.17897
- GIT version: 2.47.0.windows.1
- OS version: Win10
- .NET version: several :-)

### Issue description

I just updated to GitExtensions 5.0.0.1.17897:

The "Branch to push"-field in the Push-dialog is always prefilled with HEAD when the dialog opens. Usually I want to push the branch I am currently working on and in my former version the  "Branch to push"-field was prefilled with the current branch.

I checked the "Manage remotes / Default pull behaviour", but that's fine (and it's about pulling, not about pushing :-) ). 

In the picture you can see the tree-view, the open Push-dialog and the "Manage remotes / Default pull behaviour" - dialog (which shouldnt matter here)

![Image](https://github.com/user-attachments/assets/d3ebe947-6931-4c28-8f44-0608366f69f2)

### Steps to reproduce

Press the push icon

### Did this work in previous version of GitExtensions?

Yes. (Unfortunately I don't know the former version)

**Comment by tih2010** [comment]
I just noticed something: The problem does not occur with all branches!

Maybe the problem it's related to the brakets (or are they named braces?) in my branch name 

BI-4114_DB-Timeout_untersuchen_in_Cmd_CreateAufgabeFromClearingPages_(ImageLink)

Could be a matching problem when trying to prefill the dialog field.

**Comment by pmiossec** [comment]
Can you check if  #11954 is fixing the issue?

**Comment by JeremiaAu** [comment]
I encountered the same bug: https://github.com/gitextensions/gitextensions/issues/11997

I tried the latest Canary build (5.1.0.17945-dhrirvrx) and the bug is still there.

**Comment by pmiossec** [comment]
Is your branch in the combobox when you open it ?

I tend to think that indeed it is due to the brackets...

**Comment by JeremiaAu** [comment]
I can select my branch from the combobox when I open it.
Doing that allows me to to push the branch. (I am doing that as a workaround)

**Comment by mstv** [comment]
fixed by #11999
