### ISSUE TITLE
Control+. does not work anymore as a shortcut for checkout branch

### ISSUE THREAD

**Issue by choas75** [gitextensions/gitextensions#11988]
### Environment

- GitExtensions version:- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.45.2.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.10
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

- GIT version: git version 2.45.2.windows.1
- OS version: Windows 10 Pro
- .NET version: 8

### Issue description

Control+. does not work anymore as a shortcut for checkout branch

### Steps to reproduce

Press control+.

### Did this work in previous version of GitExtensions?

No, earlier version (don't know which) lacked this too

**Comment by mstv** [comment]
Is the correct hotkey set?

![Image](https://github.com/user-attachments/assets/00bf25a7-227f-4a11-83e6-da4a84ed05f4)
