### ISSUE TITLE
Dark Theme missing (and not working when download from repositiory)

### ISSUE THREAD

**Issue by Tenebrosful** [gitextensions/gitextensions#12003]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.47.0.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 8.0.10
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

(I'm Windows 11, idk why the about of git extension says 10)

### Issue description

1) There is no dark theme installed, i had to take it from my own in [repository files](https://github.com/gitextensions/gitextensions/blob/master/src/app/GitUI/Themes/dark.css) 

2) It appear to doesn't work at all

dark.css
![Image](https://github.com/user-attachments/assets/c96bdff3-b76b-41f8-8689-d5512778e356)

darksilver.css
![Image](https://github.com/user-attachments/assets/e11b8644-6680-4074-89bb-668949c6369c)

highcontrast_dark.css (already have it)
![Image](https://github.com/user-attachments/assets/497f28bd-6d3f-4ee6-9b4b-52c1ad06a5aa)

### Steps to reproduce

- Download dark theme from repo because i don't have it
- Apply it

**Comment by gerhardol** [comment]
You need to use Dark High Contrast in Windows (it is extremely ugly).

.NET6, .NET8 does not support the workaround for theming that was used with .NET4, so theming is not possible.
