### ISSUE TITLE
Disable sound for modal dialogs

### ISSUE THREAD

**Issue by jabacrack** [gitextensions/gitextensions#12008]
### Feature description

Is it possible to add option to disable sound for modal dialogs like this one?
![Image](https://github.com/user-attachments/assets/ee375507-635a-4ea4-b924-784169538ea2)

### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.47.0.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.8
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pmiossec** [comment]
I don't think it is possible for the developpers in the application as it is an operating system behavior.

Try in the 'sound' section in windows control panel...

**Comment by pmiossec** [comment]
Using a modal has been made on purpose so I don't think it make sens to change the behavior and take the risk the user make a mistake only to avoid a sound...
