### ISSUE TITLE
Diff viewer fails when external diff command configured

### ISSUE THREAD

**Issue by bdukes** [gitextensions/gitextensions#12006]
### Environment

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.47.0.windows.1
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.10
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.35 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

When an external diff tool is registered (such as Difftastic), Git Extensions cannot parse the output and displays nothing. Git Extensions should, instead, force the output to bypass the external tool so that it can be parsed as expected, by passing the `--no-ext-diff` argument.

This was mentioned in #11618, but a different approach was taken to accommodate the external diff tool.

### Steps to reproduce

1. [Install Difftastic](https://difftastic.wilfred.me.uk/installation.html)
2. [Configure DIfftastic as your default diff tool](https://difftastic.wilfred.me.uk/git.html#difftastic-by-default) by setting the `diff.external` config to `difft`
3. View a diff in Git Extensions (either in the commit window or the diff tab of the history tree

**Comment by gerhardol** [comment]
difftastic can be used if the difftool is called difftastic, must not be default

But the default configuration should override difftool, ext diff and pager

**Comment by bdukes** [comment]
I'm not quite clear on what you're saying. Are you agreeing with me that the configuration that Git Extensions uses should override incompatible settings? Or are you saying the problem is my configuration and it's invalid to use Git Extensions while setting `diff.external`? Or something else?

**Comment by mstv** [comment]
Difftastic support has been added in #11677. Please see there for how to configure it.
The current development build runs stably and contains further improvements to this feature.

**Comment by bdukes** [comment]
I did find that feature, which is convenient. However, I still think that the diff viewer shouldn't break if I have configured `diff.external`.

**Comment by mstv** [comment]
Does https://ci.appveyor.com/api/buildjobs/q6cwh9nybo7acaas/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17952-0cb35a298.zip work for you?

**Comment by bdukes** [comment]
> Does https://ci.appveyor.com/api/buildjobs/q6cwh9nybo7acaas/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17952-0cb35a298.zip work for you?

The diff viewer is still blank using that version.

**Comment by mstv** [comment]
There are at least 6 "git diff" calls. I hope I have not missed any other.
https://ci.appveyor.com/api/buildjobs/wtmwrb1kj3c7s3x8/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17952-8604ca20a.zip works for me in a short test.

**Comment by bdukes** [comment]
> There are at least 6 "git diff" calls. I hope I have not missed any other. https://ci.appveyor.com/api/buildjobs/wtmwrb1kj3c7s3x8/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.1.0.17952-8604ca20a.zip works for me in a short test.

I can verify this build resolves my issue, thanks!
