### ISSUE TITLE
Start > Close (Repository)

### ISSUE THREAD

**Issue by vwheeler63** [gitextensions/gitextensions#12017]
### Feature description

While I am managing my repository categories in the Dashboard, I find myself having to close and re-open the full application in order to get back to the Dashboard.  Since the Windows UI for applications has almost always been in the flavor of opening and closing "documents", it would be really nice to consider a repository as a "document" or "thing that is open" and offer:

- ability to close it again, and
- return to the Dashboard display

where it is much easier to open another repository in some cases.

### Environment

- GitExtensions version:  5.0.0.17897
- GIT version:  2.46.2.windows.1
- OS version:  Microsoft Windows NT 10.0.19045.0
- .NET version: 8.0.10

**Comment by pmiossec** [comment]
It's in the bottom of the 2nd menu...

**Comment by vwheeler63** [comment]
Wow!  `**`rolling eyes at myself`**`  Well, I guess that handles that!  😄
