### ISSUE TITLE
The "Reset another branch to here..." option hangs in a large repo

### ISSUE THREAD

**Issue by TaoK** [gitextensions/gitextensions#12035]
### Environment

- GitExtensions version: 5.1.1.17970
- GIT version: Git 2.47.0.windows.2
- OS version: Microsoft Windows NT 10.0.22631.0
- .NET version: 8.0.10

### Issue description

Background: We have a multi-GB repo, and we typically use multiple worktrees, partial clone and sometimes shallow clone. As far as I know, the only relevant consideration to this issue is the *size* of the repo, which on clients is normally 5-10GB

When we use "Reset another branch to here..." in this repo, the `git push` command that Git Extensions uses internally hangs... possibly forever, or possibly just a really long time.

### Steps to reproduce

* Have a very large (multi-GB) repo
* In the commit list, right-click a commit, choose "Reset another branch to here...", select a branch, check the "Force reset for a non-fast-forward reset" checkbox, and hit "OK"
* In the resulting git command dialog, the push command hangs, seemingly forever.

### Did this work in previous version of GitExtensions?

(unknown)

### Diagnostics

The same `git push` command also hangs outside Git Extensions - the problem is not the Git Extensions environment, but rather the use of `git push` as a "strategy" to reset non-checked-out branches.

FWIW, with `GIT_TRACE=2` set, the trace looks something like this:

```
$ GIT_TRACE=2 "C:\Program Files\Git\bin\git.exe" push . "285b5c7faf1a1d136f8c2e05090686a9e9c48ee4:refs/heads/t/us/our-feature-branch" --force
10:29:29.973108 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:29:29.990476 git.c:479               trace: built-in: git push . 285b5c7faf1a1d136f8c2e05090686a9e9c48ee4:refs/heads/t/us/our-feature-branch --force
10:29:30.004591 run-command.c:667       trace: run_command: unset GIT_DIR GIT_PREFIX; 'git-receive-pack '\''.'\'''
10:29:30.004591 run-command.c:928       trace: start_command: 'C:/Program Files/Git/usr/bin/sh.exe' -c 'git-receive-pack '\''.'\''' 'git-receive-pack '\''.'\'''
10:29:30.114677 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:29:30.114677 git.c:479               trace: built-in: git receive-pack .
10:29:30.146019 run-command.c:667       trace: run_command: 'C:\myhooks\githooks/pre-push' . .
10:29:30.146019 run-command.c:928       trace: start_command: 'C:\myhooks\githooks/pre-push' . .
Some message from the hook.
10:29:30.209260 run-command.c:667       trace: run_command: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
10:29:30.209260 run-command.c:928       trace: start_command: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
10:29:30.226093 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:29:30.240649 git.c:479               trace: built-in: git pack-objects --all-progress-implied --revs --stdout --thin --delta-base-offset --progress
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
10:29:30.303687 run-command.c:667       trace: run_command: GIT_ALTERNATE_OBJECT_DIRECTORIES=C:/myrepo/objects GIT_OBJECT_DIRECTORY=C:/myrepo/objects/tmp_objdir-incoming-a48352 GIT_QUARANTINE_PATH=C:/myrepo/objects/tmp_objdir-incoming-a48352 git unpack-objects --pack_header=2,0
10:29:30.303687 run-command.c:928       trace: start_command: git unpack-objects --pack_header=2,0
remote: 10:29:30.335276 exec-cmd.c:266          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
remote: 10:29:30.335276 git.c:479               trace: built-in: git unpack-objects --pack_header=2,0
```

I'm not sure offhand what a better (better-scaling) strategy for performing this operation might be. The best I've come up with so far is a bash one-liner:
`target_branch=t/us/our-feature-branch new_hash=285b5c7faf1a1d136f8c2e05090686a9e9c48ee4; [[ $(git worktree list --porcelain) == *"refs/heads/$target_branch"* ]] && echo "Aborting; Branch checked out in a wortktree!" || git update-ref "refs/heads/$target_branch" $new_hash`

**Comment by mstv** [comment]
Thank you for proposing a quicker git command!
Though "`git update-ref`" lacks the check that it is just a fast-forward reset. I am not sure whether we should rely on reflog and remove the "Force" checkbox.
This is a git issue and should rather be fixed in git itself.
But I like the clearer command. Thoughts, @gitextensions/git-extensions-team?

As a workaround, you could add your one-liner as [User Script](https://git-extensions-documentation.readthedocs.io/en/release-5.1/settings.html#scripts).

**Comment by pmiossec** [comment]
> Though "`git update-ref`" lacks the check that it is just a fast-forward reset.

I also prefer to keep the check because in most of the repositories, the performance is not a problem.

> I am not sure whether we should rely on reflog and remove the "Force" checkbox.

I was thinking more about keeping the checkbox and using the `git update-ref` with improvement on performance when it is checked.

**Comment by mstv** [comment]
Improved feedback in https://ci.appveyor.com/api/buildjobs/kw2fb7ns7uogq9bv/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.2.0.17985-023c690f9.zip
