### ISSUE TITLE
Option for commit dialog behaviour after commit

### ISSUE THREAD

**Issue by namtab00** [gitextensions/gitextensions#12042]
### Feature description

I frequently prefer to segment my working directory changes in multiple commits.
Sadly, GitExtensions insists on closing the commit dialog on each commit operation.

I've looked for options / GH issues related to the commit dialog closing, found none.

I'd love an option "After commit":
- "don't close commit dialog" <-- this perhaps is impossible with the current architecture
- OR "re-open the commit dialog if working directory is not clean"

### Environment

- Git Extensions 5.1.0.17965
- Build f9e558c2f1645008b4c426f847cadbf10c92fcd0
- Git 2.47.0.windows.2
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.11
- DPI 120dpi (125% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.36 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 9.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by pmiossec** [comment]
>"don't close commit dialog" <-- this perhaps is impossible with the current architecture
It is possible 😉 

It's in the "Options" menu of the commit form.

![Image](https://github.com/user-attachments/assets/99f27e93-f7df-45d2-ada1-28fc6dce1132)

**Comment by namtab00** [comment]
@pmiossec doh!.. thanks.
