### ISSUE TITLE
Ability to create empty branch

### ISSUE THREAD

**Issue by andry81** [gitextensions/gitextensions#12054]
### Feature description

> git switch --orphan \<name>

Currently `Create new branch here...` menu item does not let to create an empty branch even with `orphan` option in case of untracked changes.

Details: https://stackoverflow.com/questions/34100048/create-empty-branch-on-github/34100189#34100189

### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.47.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET 8.0.10
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by mstv** [comment]
![1](https://github.com/user-attachments/assets/4079f25b-8f14-4956-a494-c8a53b5a6930)

![2](https://github.com/user-attachments/assets/6539c8a3-206c-4e2d-a748-ffc2b022fc42)

![result](https://github.com/user-attachments/assets/7b68fb9b-25b4-4232-85c0-72b061c40877)
