### ISSUE TITLE
[NBug] Unable to load DLL 'vcruntime140_cor3.dll' or one of its de...

### ISSUE THREAD

**Issue by RicjFonZ** [gitextensions/gitextensions#12052]
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.47.0.windows.2
- Microsoft Windows NT 10.0.26100.0
- .NET 8.0.11
- DPI 96dpi (no scaling)

### Issue description

```
System.DllNotFoundException: Unable to load DLL 'vcruntime140_cor3.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at __std_type_info_destroy_list(__type_info_node*)
   at __scrt_uninitialize_type_info()
   at _app_exit_callback()
   at <CrtImplementationDetails>.ModuleUninitializer.SingletonDomainUnload(Object source, EventArgs arguments)
```

I just close the app and this error happened

### Steps to reproduce

I just closed the application, and error happened 

### Did this work in previous version of GitExtensions?

N/A

**Comment by RussKie** [comment]
Whilst this is reported via nbug, it doesn't look like anything to do with the app itself...
