### ISSUE TITLE
Inconsistent Encoding inside diff

### ISSUE THREAD

**Issue by V0d01ey** [gitextensions/gitextensions#12066]
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.46.2.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET 8.0.11
- DPI 96dpi (no scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

![Image](https://github.com/user-attachments/assets/80f29b3c-2eb9-451c-9571-2b2d76138a39)
![Image](https://github.com/user-attachments/assets/60dc25bc-a72a-4778-86a4-19e3959205fa)

Lines deleted do not use Encoding setting of the diff viewer.

### Steps to reproduce

Change Encoding setting in Diff Viewer.

### Did this work in previous version of GitExtensions?

Yes.
Worked in [v4.2.1](https://github.com/gitextensions/gitextensions/releases/tag/v4.2.1)

**Comment by mstv** [comment]
What is the output from git on the command line?

You can copy the "git diff" command from the Git Command Log (`F12`).

**Comment by V0d01ey** [comment]
```
\x1b[36m@@·-28,5·+28,5·@@\x1b[m\n
·········(param·zondLength·'ÐÐ»Ð¸Ð½Ð°·Ð·Ð¾Ð½Ð´Ð°,·Ð¼'·Single·#referenced·#no_val)\x1b[m\r\n
\x1b[7;31m-········(param·hMin·'ÐÐ¸Ð½.·ÑÐ¾Ð»ÑÐ¸Ð½Ð°·Ð´Ð»Ñ·ÑÐ½ÑÑÐ¸Ñ·Ð¾ÑÑÑÐµÑÐ¾Ð²,·Ð¼'·Single·#no_val)\x1b[m\r\n
\x1b[7;31m-········(param·speed·'Ð¡ÐºÐ¾ÑÐ¾ÑÑÑ·Ð·Ð°Ð¿Ð¸ÑÐ¸,·Ð¼/Ñ'·Single·#no_val)\x1b[m\r\n
\x1b[7;31m-········(param·tConst·'ÐÐ¾ÑÑÐ¾ÑÐ½.·Ð²ÑÐµÐ¼ÐµÐ½Ð¸,·Ñ'·Single·#no_val)\x1b[m\r\n
\x1b[7;32m+\x1b[m\x1b[7;32m········(param·hMin·'ÐÐ¸Ð½.·ÑÐ¾Ð»ÑÐ¸Ð½Ð°·Ð´Ð»Ñ·ÑÐ½ÑÑÐ¸Ñ·Ð¾ÑÑÑÐµÑÐ¾Ð²,·Ð¼'·Single·#no_val·#referenced)\x1b[m\x1b[41m\r\x1b[m\n
\x1b[7;32m+\x1b[m\x1b[7;32m········(param·speed·'Ð¡ÐºÐ¾ÑÐ¾ÑÑÑ·Ð·Ð°Ð¿Ð¸ÑÐ¸,·Ð¼/Ñ'·Single·#no_val·#referenced)\x1b[m\x1b[41m\r\x1b[m\n
\x1b[7;32m+\x1b[m\x1b[7;32m········(param·tConst·'ÐÐ¾ÑÑÐ¾ÑÐ½.·Ð²ÑÐµÐ¼ÐµÐ½Ð¸,·Ñ'·Single·#no_val·#referenced)\x1b[m\x1b[41m\r\x1b[m\n
·········(param·alpha·'ÐÐ¾Ð¿ÑÑÑÐ¸Ð¼ÑÐ¹·ÑÐ°Ð·Ð±ÑÐ¾Ñ·ÑÐºÑÑÑ.Ð·Ð½Ð°Ñ,·%'·Integer·#default:·10·#no_val)\x1b[m\r\n

-------------------------------------

```

When changing Encoding for the Diff Viewer no `git diff` command is sent. (Only `git ls-files` command)

**Comment by mstv** [comment]
> When changing Encoding for the Diff Viewer no `git diff` command is sent.

@gerhardol, do we need to add the encoding to the command cache key?
Or does the EscapeSequenceParser get confused?

On the other hand, it might even have the same root cause as the not really understood #10382, #11106, etc.

**Comment by gerhardol** [comment]
> > When changing Encoding for the Diff Viewer no `git diff` command is sent.
> 
> [@gerhardol](https://github.com/gerhardol), do we need to add the encoding to the command cache key? Or does the EscapeSequenceParser get confused?
> 
> On the other hand, it might even have the same root cause as the not really understood [#10382](https://github.com/gitextensions/gitextensions/issues/10382), [#11106](https://github.com/gitextensions/gitextensions/issues/11106), etc.

The decoding is from system encoding, how data is reported by Git. The encoding when presenting is separate.

**Comment by V0d01ey** [comment]
Also it can be related:
"Files content encoding" do not used for viewing Added files
![Image](https://github.com/user-attachments/assets/333947bc-5dc2-4db6-9fd4-63869d606136)

**Comment by mstv** [comment]
`CreatePatchFromString` in `src\app\GitCommands\Patches\PatchProcessor.cs` calls `GitModule.ReEncodeStringFromLossless(line, encoding)`. 
The function `Encoding.GetString` seems to wrongly interpret the additional escape sequences after the `'+'` of added lines or the different one before the `'+'`.
I am afraid, we will need to split the line in order to not re-encode the escape sequences.

```
\x1b[7;31m-···foo
\x1b[7;32m+\x1b[m\x1b[7;32m···bar
```
