### ISSUE TITLE
Request: Add exception handling for specific comment blocks in diff analysis

### ISSUE THREAD

**Issue by mamuka-gepha** [gitextensions/gitextensions#12070]
### Feature description

In Git Extensions, it should be possible to define an exception for code comments, so that if a comment starts and ends with a specific pattern, changes within that comment block are ignored during the diff analysis. 

For example, if we define an exception with the pattern "auto-generated", the following comment block:

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.8000
'     Runtime Version:2.0.50727.9179
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

... should be ignored entirely during the diff analysis, regardless of any changes made to the text within the block.

This feature would be extremely useful for auto-generated code files, where changes within such blocks are not relevant for version control analysis.

Thank you!

### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by mstv** [comment]
GE just displays the diff output from the Git executable.
So, one needs to tell Git to ignore such lines.
You can copy the git command line from GE's Git Command Log (`F12`) and add further arguments (refer to `git help diff`).
Once you have an appropriate example command line, we can discuss how to integrate such a feature.

As an alternative, you could define a diff filter for such files in `.gitattributes`, e.g. like `"generated_files/*.c diff=strip-generator-noise"`.

(And there might be people who ask you why to manage generated files in Git at all. You will have your reasons. I know terribly slow code generators.)

**Comment by RussKie** [comment]
I'm going to close this because there's nothing the app can do. Feel free to reopen once you have a command which the app can run.
