### ISSUE TITLE
fileditor find+replace with selection replaces line after selection too

### ISSUE THREAD

**Issue by spicfrankly** [gitextensions/gitextensions#12084]
### Environment

- Git Extensions 5.1.1.17970
- Build 939c0edba68f0c15b8e5180ca06a92c5ce534501
- Git 2.46.1.windows.1
- Microsoft Windows NT 10.0.19045.0
- .NET 8.0.11
- DPI 192dpi (200% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 8.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Issue description

The find and replace feature of the built-in file editor replaces any match in the line after the end of the selection

### Steps to reproduce

In the builtin fileeditor, for instance during an interactive rebase:
1. Select a portion of lines in the text except the last 2 lines.
2. CTRL+H to open the find and replace dialog
3. Find "pick" and Replace all by "d"

Expected:
4. All "pick" matches in the selected lines and only these are replaced by "d".

Actual:
4. All "pick" matches in the selected lines are replaced by "d", but is also replaced in the line after the selection.

### Did this work in previous version of GitExtensions?

🤷‍♂️ I just started using the find and replace dialog.

**Comment by mstv** [comment]
Often replaces too many, sometimes too few. Weird! Yet another complaint about the integrated `TextEditorControl`.
