### ISSUE TITLE
GPG Commit Signing doesn't work; Key Id max length is too short

### ISSUE THREAD

**Issue by brianjlacy** [gitextensions/gitextensions#12099]
### Environment

Git Extensions info:

- Git Extensions 5.0.0.17897
- Build 2a3b78b868e7757d986c49bbfc03406b38f1ffe9
- Git 2.41.0.windows.1 (recommended: 2.42.0 or later)
- Microsoft Windows NT 10.0.22631.0
- .NET 8.0.11
- DPI 192dpi (200% scaling)
- Portable: False
- Microsoft.WindowsDesktop.App Versions

### Issue description

**I'm unable to sign commits with my GPG key because GE only supports 16 character Key Id's.**

My employer now requires me to sign commits using a GPG key. I can make signed commits from the command line just fine, but I haven't been able to commit from Git Extensions since the change. Today I finally discovered how it's SUPPOSED to work -- in the Commit dialog, under "Options" I can select a signing option.

**However, the maximum character length supported for the GPG Key Id is only 16 characters** and unfortunately, my generated Key Id is 40 characters long.

Regardless of whether I try to specify the key manually ("Sign with specific GPG...") or tell it to use the default user signing key ("Sign with specific GPG..."), GE will neither allow or use more than the first 16 characters of the Key Id.

For example, let's say my Key Id were:
3F4C654E628B4128AAB031AEA16E63CF496628A0

Then Git Extensions will only attempt to use:
3F4C654E628B4128

_...even_ if I've told it to use the default user signing key, which is definitely set to 3F4C654E628B4128AAB031AEA16E63CF496628A0.

![Image](https://github.com/user-attachments/assets/dd39ff74-82bf-4776-8aeb-db1f2b845d66)
![Image](https://github.com/user-attachments/assets/0a490796-dbe2-4ff6-942f-f03e09c8d830)
![Image](https://github.com/user-attachments/assets/f683ad16-1479-472c-a5f3-4dd88c027772)

### Steps to reproduce

1. `gpg --full-generate-key`
2. `gpg --list-secret-keys` *(Obtain Key_Id, where Key_Id > 16 chars)*
4. `git config --global commit.gpgsign true`
5. `git config --global user.signingkey {Key_Id}`
6. In Git Extensions, **Commit** > **Options** > **Sign with default GPG**
7. *Alternately: *Sign with specific GPG*; enter {Key_Id} *(Only allows entering 16 chars)*
 
-----

9. Attempt commit
10. ***(Commit fails; could not recognize key with only 16 chars!)***

### Did this work in previous version of GitExtensions?

unknown

**Comment by brianjlacy** [comment]
I was mistaken about a few critical facts. 🙄 It seems the issue may only apply to entering a SPECIFIC Key Id, NOT using the default. I think the problem is just that the text field only supports 16 characters.

Apologies for the mistake.

**Comment by mstv** [comment]
Does it work for with https://ci.appveyor.com/api/buildjobs/gas4smka2q23m80y/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.2.0.18004-3d079c899.zip?

**Comment by brianjlacy** [comment]
> Does it work for with https://ci.appveyor.com/api/buildjobs/gas4smka2q23m80y/artifacts/artifacts%2FRelease%2Fpublish%2FGitExtensions-Portable-x64-5.2.0.18004-3d079c899.zip?

Link isn't working for me..

**Comment by pmiossec** [comment]
It has been merged so you could test last master https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts
