### ISSUE TITLE
GE-Plugin for MS Access mdb,adp,accdb containers

### ISSUE THREAD

**Issue by IsNull** [gitextensions/gitextensions#1217]
Git is a great thing, and GitExtensions brought finally the tooling to use it in average developer teams.

Now, I face the following situation:
In one of our projects, we have a large ERP Application based upon **MS Access 2000** (jup, 2000!). There is code in some VB6 DLLs as well, but the main part is in the MS Access Forms and Modules. The old SourceSafe from MS is not available.

_Oh, and there is not any chance to switch off from this MS Access-Hell soon. Thus, in this project, we have to go along with it until it gets replaced._

Off course, for Git/GitExtensions, an MS Access **mdb/adp/accdb** is a big binary blob, thus very useless.  However, it is possible to export the Elements as plain text-files. Those Text-Files can be versioned.
There even exists a project (luckily written in C#) which is able to export and load to/from Text-Files. http://accesssvn.codeplex.com/

Now, my idea is as follows:
I write a **GE-Plugin**, which basically handles the **mdb/adp/accdb** files as special containers, and actually versions the extracted contents of it.
I currently haven’t looked deep at the source of GitExtensions, I’d like first to check if this project is realizable.

Can any of the core developers give a hand at this? What would be the best approach, how abstract is the handling of such files? Is it possible to write a plugin for GE to do this, or will I have to fork GE and internally extend it to add this functionality?

**Comment by RussKie** [comment]
Closing due to age.
Let me know if you still wish to proceed with this.
