### ISSUE TITLE
Git Extensions 2.40 Hangs Sometimes When Creating a Tag

### ISSUE THREAD

**Issue by OneEyedSi** [gitextensions/gitextensions#1223]
Steps to Reproduce:

In the Commit Log of the Git Extensions browse window, select a commit and press Ctrl+T to open the new Tag dialog;

Add the name for the tag (in my case "Forked_Version_0.55") and check the Push Tag checkbox;

Click OK.

Expected Results:

The new Tag dialog will close;

A progress dialog will open which, once the tag has been created, will display an OK button;

Clicking the OK button on the progress dialog will close the dialog;

The Commit Log of the browse window will be updated to show the new tag next to the selected commit.

Actual Results:

On Ok'ing the new Tag dialog a Windows command window or similar window with a black background will briefly flash on the screen (too fast to read any text, if there is any);

After the command window has appeared and disappeared the new Tag dialog will remain on the screen.  All its controls and the controls of the Git Extensions browse window in the background will be unresponsive; Git Extensions will be completely locked up.

The new tag dialog and Git Extensions will remain locked up until the Git Extensions process is killed via Windows Task Manager; it is not possible to close Git Extensions by right-clicking on the icon on the Wndows task bar and selecting Close window from the context menu.

Version Details:

Git Extensions: 2.40.0.0
Git for Windows: 1.7.10, installed from Git-1.7.10-preview20120409.exe
Windows: Windows 7 Professional SP 1

**Comment by mlamx** [comment]
I also have this issue. It also happens sometimes when deleting a branch.  The command is executed but the dialog hangs and I have to kill the git extensions process in Task Manager and restart the app to continue. version is 3.43.9999 and git is 2.30.0.windows 2

**Comment by pmiossec** [comment]
@mlamx this issue is on a too old version so I don't think that is the same problem (or it is more a problem with the environment: OS, git, anti-virus,...)

Could you please open a new issue.

And also could you try to find what is the process that hang? Is it GitExtensions or a sub process that is launched?
And so the command line of the subprocess?

Process Explorer is useful to find the subprocess command line easily.
