### ISSUE TITLE
git-rebase shows "line 54: !/fixup!: event not found"

### ISSUE THREAD

**Issue by craigpl** [gitextensions/gitextensions#1244]
Using Git Extensions version 2.40 [.Net 4].  Problem also occurred on version 2.33 (no .Net 4).

Error: Doing a git rebase shows error message during processing.
What should happen is that the command executes without displaying an error message.

Example:
craigpl@R9DC9Z7D /c/dev/workspaces/gitdev/modules/myCoreCode (cebeta/ticket/383132_t5)
$ git rebase origin/cebeta/restrictedShipping
C:\Tools\Git/libexec/git-core\git-rebase: line 54: !/fixup!: event not found
First, rewinding head to replay your work on top of it...
...

And the work continues.  I looked at the file ${myGitHome}/libexc/git-core/git-rebase.  It looks like this file is being executed but it contains raw text (line beginning "autosquash" is line 54 of the file):

Example:
# !/bin/sh
# 

# Copyright (c) 2005 Junio C Hamano.
# 

USAGE='[--interactive | -i] [-v] [--force-rebase | -f] [--no-ff] [--onto <newbase>] [<upstream>|--root] [<branch>] [--quiet | -q]'
LONG_USAGE='git-rebase replaces <branch> with a new branch of the
same name.  When the --onto option is provided the new branch starts
...
root!              rebase all reachable commits up to the root(s)
autosquash         move commits that begin with squash!/fixup! under -i
committer-date-is-author-date! passed to 'git am'
...

Hope I did this right.  I could not find this in the other issues listed.  Thanks for your time!
/craig

p.s. Using Windows 7 64-bit.
Brought up command shell from within Git Extensions (selecting recent repository and branch, then doing control-G)

**Comment by strobelight** [comment]
_I see this is very old, but anyway ..._

add `set +H` to your `.bashrc` file or `.bash_profile` file for future terminal sessions, and enter `set +H` in your current session and redo the pull rebase.
