### ISSUE TITLE
Automatically move pointer to the Default button problem

### ISSUE THREAD

**Issue by hhubschle** [gitextensions/gitextensions#1255]
Turn on the feature in Mouse Properties.
Stage a number of files using the "Stage one" button.
--> On every click a temporary window pops up just above the Start button. This window apparently has a Default button that pulls the mouse pointer to the bottom left of the screen. 
Expected behavior: the mouse stays on top of the Stage button.

**Comment by RussKie** [comment]
Closing as no longer relevant
