### ISSUE TITLE
Github plugin: Pull request management doesn't work for private repo forks

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#1271]
When I click on "Fetch to pr/ branch" I get this error: 

```
git.exe fetch --no-tags --progress git://github.com/someone/private_repo_fork.git session_db:pr/n44_someone
fatal: remote error: 
  Repository not found.
Done
```

It's because the url is different for github private repo - it's "git@github.com:someone/private_repo_fork.git" - the first slash is replaced with colon. 

I also get 404 errors for diffs (probably the same reason, but the message is unclear): 

```
Failed to load diff data!

Remote server returned error: (404) Not found. //I translated this as it was localized to czech in the actual message
```

**Comment by RussKie** [comment]
Is this still an issue in the current version?
