### ISSUE TITLE
Trying to clone a svn repo will fail if self-signed cert is used

### ISSUE THREAD

**Issue by KindDragon** [gitextensions/gitextensions#1283]
GitEx hang if you try clone something from self-signed SVN repository like on http://code.google.com

Same issue in TortoiseGit http://code.google.com/p/tortoisegit/issues/detail?id=318

**Comment by RussKie** [comment]
Is this still any issue?

**Comment by gerhardol** [comment]
SVN related. Should we rip out all SVN for 3.00?
If so, it should be handled in a separate issue.

**Comment by KindDragon** [comment]
> Is this still any issue?

I think this bug probably fixed in Git. We can close it

**Comment by RussKie** [comment]
We can probably do it eventually.
