### ISSUE TITLE
"open with difftool" doesn't do anything

### ISSUE THREAD

**Issue by CharlesB2** [gitextensions/gitextensions#1304]
I have a diff tool ran from a shell script wrapper. In .gitconfig it looks like

```
[difftool "lvdiff2012"]
    path = d:/charles/bin/lvdiff.sh
    cmd = sh /d/charles/bin/lvdiff.sh 2012 \"$LOCAL\" \"$REMOTE\"
```

The shell runs some exe, everything worked fine until 2.40

When run from Git Extensions, nothing happens. Pasting the line from the git command log into a terminal, the difftool launches correctly.

**Comment by saleemandy** [comment]
Hi Charles, I have the same problem. where can i check if my script is also sourcing a file by relative path?

**Comment by vbjay** [comment]
Check your settings.

**Comment by saleemandy** [comment]
I would appreciate if you can tell me where exactly in settings. alot of stuff in settings. scanned through everything, i cant see where anything that looks like sourcing a  file by relative path. I

**Comment by vbjay** [comment]
Look at merge tool and diff tool

**Comment by vbjay** [comment]
http://git-extensions-documentation.readthedocs.org/en/latest/settings.html

**Comment by saleemandy** [comment]
Thanks but I have an absolute path to my external diff tool defined in the diff tool yet "open with diff tool doesn't do anything".

**Comment by saleemandy** [comment]
Here is what my stuff looks like:

I have a diff tool ran from a shell script wrapper. In .gitconfig it looks like

[diff]
guitool = Compare
[difftool "Compare"]
path = \"C:/Users/salees/ivy/networkdesigner/lib/lib_datalink/sdlt/Compare/scripts/diff-extern.bat

my script looks like this:

@ECHO OFF
rem

rem
if "%~x1" EQU ".datalink" (
goto SYSARCH
)
else (
goto END
)

:SYSARCH
"C:\Users\salees\ivy\networkdesigner\lib\lib_datalink\sdlt\Compare\Compare.exe" %1 %2
goto END

:END
rem exit 0

**Comment by ghanique** [comment]
I, too, sometimes suffer from this problem in Windows. Haven't been able to
find the cause or fix it. The only way to get it working again if by
uninstalling Git extensions and then reinstalling it.

(When F3 doesn't work interactive rebasing doesn't work either. Instead of
opening the configured editor it tries to run Vim, which subsequently hangs
after which everything freezes until you terminate Vim. Both are fixed
after reinstalling Git Extensions)

**Comment by saleemandy** [comment]
Thanks let me see if that would help.

**Comment by vbjay** [comment]
Do you see the suggest button next to those settings? Select compare and
pit in the path to the compare exe and click suggest.

**Comment by saleemandy** [comment]
Thanks guy. your responses were really helpful. Problem solved!!! The problem was that I was assuming it's going to run the batch file through the path defined in the "path to difftool" but I was wrong. I then passed the path to my wrapper file as a string to "difftool command" and everything works fine now. If you using windows, use a shell script as your wrapper file and not a batch file.

**Comment by n1l** [comment]
I ran my gitextensions as admin, and all works fine, can be a solution.

**Comment by brent-ir** [comment]
For future googlers, I had bad settings in `.gitconfig`

Execute a command like this in your shell
``git difftool feature/ir-696 develop -- user.sql`

**Comment by neutmute** [comment]
For future googlers, I had bad settings in `.gitconfig`

To diagnose, execute a command like this in your shell - comparing two branches for a file in that folder:

`git difftool -y feature/ir-696 develop -- user.sql`

It printed an error which showed I had escaped the space in `Program Files` path incorrectly:

> /mingw64/libexec/git-core/git-mergetool--lib: line 124: C:/Program: No such file or directory

Fixing that, fixed the issue in gitextensions

**Comment by RussKie** [comment]
Thanks for sharing. 

Wonder if we can intercept the error and show it to the user. 🤔

**Comment by mcsilver** [comment]
> Works! Found the problem, my script was sourcing a file by relative path. Thanks a lot for your support

For me, I had some a repair install of Windows. Although GE had an absolute path for my diff tool (WinMerge), I think it kept its old location from my having done a repair install of Windows recently. WinMerge now lives in Program Files instead of Program Files (x86).

**Comment by gerhardol** [comment]
Note that GE invokes git-difftool here and Git returns error code 0 to indicate success.
To parse the actual command line string is possible, but that is error prone (it was like that for mergetool previously, it is hard to handle all situations).
