### ISSUE TITLE
File Tree Tab: enable "File History" also for folders

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1327]
Sometimes it would be good to know how a certain submodule (an abstract one, not a git submodule) of a project has changed over time. The submodule is usually placed in a subfolder.

Currently I see no way to do that with Git Extensions.

Suggestions:
- [x] Enable the "File History" context menu item in the File Tree Tab also for folders (which would lead to the need to enhance the File History dialog which currently cannot handle multiple files)
- [ ] Add a new context menu item "Filter revision grid to this folder" to the File Tree Tab. Alternatively add a new filter box to the main menu which lets the user filter for directories.

**Comment by gerhardol** [comment]
PR in #9445
