### ISSUE TITLE
LibGit2Sharp

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#1345]
In mono sln LibGit2Sharp.dll is copied, but directory NativeBinaries/\* is not copied to bin/debug.

**Comment by RussKie** [comment]
Is this still a problem?

**Comment by jbialobr** [comment]
Perhaps yes, but the LibGit2Sharp integration seems to be stale/dead. It has to be rethought from scratch. I would close the all issues related to LibGit2Sharp.
