### ISSUE TITLE
OpenSSH shows the black console window of git.exe

### ISSUE THREAD

**Issue by linquize** [gitextensions/gitextensions#1355]
Why not hide the black console window of git.exe?

**Comment by EbenZhang** [comment]
Any reason GitExtensions shows the console window for openssh? 
Removing the `!ssh` from `startInfo.CreateNoWindow = (!ssh && !AppSettings.ShowGitCommandLine);` to hide the console window for openssh works fine for me (fetch and push) on 

* Windows7 64bits.
* OpenSSH_4.6p1, OpenSSL 0.9.8e 23 Feb 2007
* git version 1.9.0.msysgit.0
* GitExtensions: Version 2.49a1

**Comment by Radrik5** [comment]
Maybe in that window ssh can ask you whether it can trust the remote if it's not in known_hosts.
Or ask you to enter password if the key doesn't work.

**Comment by vbjay** [comment]
There is a setting to turn it off or on.

On Sun, Apr 12, 2015 at 12:43 PM, Dmitry Oksenchuk <notifications@github.com
> wrote:

> Maybe in that window ssh can ask you whether it can trust the remote if
> it's not in known_hosts.
> Or ask you to enter password if the key doesn't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitextensions/gitextensions/issues/1355#issuecomment-92086114>
> .
>



-- 
*Jay Asbury*
PC Repair and custom programs $30/hr 1hr min
My Biking Blog <http://vbjaybiking.blogspot.com>

**Comment by EbenZhang** [comment]
The setting doesnt work for openssh Ifyou are refering to the 'show console When executing git' . But Radrik5's comment makes sense.

**Comment by vbjay** [comment]
Right. That is a special case to get the input it needs.

**Comment by KindDragon** [comment]
> Any reason GitExtensions shows the console window for openssh?

Because OpenSSH sometimes asks questions in console

**Comment by hypersw** [comment]
https://github.com/gitextensions/gitextensions/pull/3152 fixes this by running the interactive OpenSSH console in the embedded control. [Preview build.](https://github.com/JetBrains/gitextensions/releases/tag/2016-03-14)
