### ISSUE TITLE
Feature: Drag and drop from file explorer to main window --> Browse

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1358]
To switch to an existing repository I would find it convenient if drag and dropping a file or directory from the Windows explorer would behave like right click "Git Extensions" --> "Browse" except for that no second instance of GE is started (since the latter is slower) .

**Comment by RussKie** [comment]
The next will contain a redesigned dashboard and number of usability improvements for opening recent and favourite repositories.
DnD to switch a repo isn't planned for implementation.
