### ISSUE TITLE
Export difference between revisions

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#1361]
Ref: https://github.com/gitextensions/gitextensions/issues/1221#issuecomment-9741645

**Use case:**
You have a project still deployed using FTP or plainly too large to redeploy on every single change. You create couple of revisions and need to deploy them. 

**Current solition:**
- Hand-pick every changed file based on a diff between branch-base and branch-head
- Use TortoiseGit and Show Changes between revisions > Export
- create your own CLI script

**Proposed solution:**
Export changes with [ref]. That will create a summarised diff of files that were changed and export them into 
a) selected folder
b) some concrete folder
c) folder, possibly relative to repo
d) some concrete folder + repo_name subfolder

C or D seems to be the best solution for the use case as it's mostly repetitive activity and predictable folder would allow better user-land automation for FTP, lint or practically any build procedure. I'm little against displaying a "select folder" dialog every time (A), even though it may be useful from time to time, because it's flustrating for the repetitive scenario.

**Comment by pmiossec** [comment]
> This has been closed as completed, how to do that now? Do I need the git-ftp plugin to do so?

At the time the issue was closed, GitHub didn't had the "Close as not planned" feature that better describe the decision....

**Comment by gerhardol** [comment]
> We sometimes have old spike branches that we want to "modernize" and would be nice to get the full diff and then file-by-file re-introduce changes into the current state of the solution. Rebasing or merging is oftentimes very cumbersome due to all files being moved, etc. and I like the manual approach in that situations.

But you can compare any commit with another commit (and use git-range-diff for common commits), then cherry pick.

For the original question, you can use worktree to get additional "export" directories (if you do not want to checkout in the current sorking tree).
Then use an external difftool to compare directories.

**Comment by Itori** [comment]
Long time i've not used it so maybe it didn't work anymore, but there was a feature to export in a zip all the files modified between two revisions :
- Select the two commits you want (carefull I think order matter)
- Right click => Archive this commit

That's it, all files created or modified will be in the archive. Obviously if there is files to delete, you'll have to do it yourself.

**Comment by vbjay** [comment]
A long time ago I used a git deploy process. I wrote a hook that looked to see if x deploy branch had changea in a push. I set this repo up on a a AWS ec2 instance( before serverless stuff was learned).  So I set up a remote 5hay pointed to the remote and had it protected with an ssh push where I had the key. So if I merged work into the deploy branch and pushed to that remote, it would deploy the site. All it was a checkout of the branch so all was deployed all the time.

**Comment by pmiossec** [comment]
> There is a feature to export in a zip all the files modified between two revisions :
> 
>     * Select the two commits you want (carefull I think order matter)
> 
>     * Right click => Archive this commit
> 
> 
> That's it, all files created or modified will be in the archive. Obviously if there is files to delete, you'll have to do it yourself.

Indeed, it seems possible...

![image](https://github.com/gitextensions/gitextensions/assets/460196/47df8ffc-e96a-4448-847a-fcb17dde856f)

**Comment by drauch** [comment]
@Itori: Thank you, that works like a charm - great! 💯

**Comment by Itori** [comment]
Surprising it didn't work with a merge as it's a commit, I don't see any reason why it shouldn't work.
Have you verify you select in the right order ? I don't remember if it needs to select the oldest commit then the newest commit or the opposite, but I'm pretty sure it matters.

I develop this feature a while back to deploy differences between 2 versions in a php website but it doesn't seems usefull now with all the CI/CD process.
