### ISSUE TITLE
Disable Commit and File Tree Tab if more than one revision selected

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1379]
Scenario:
1. Select several revsions in the grid
2. View Commit and File tree Tab
3. Be not able to tell which of the selected revisions is shown in these tabs

Suggestion:
As long as there is no way of highlighting the currently displayed revision in the grid the user should get a message like "Operation not supported for more than one selected revision" in the File Tree and Commit Tab (similar to the Diff tab when more than two revisions are selected).

**Comment by RussKie** [comment]
In the current version the diff window shows "Operation not supported" if more than 2 revisions are selected.
The file tree shows the repository for the last selected commit.
