### ISSUE TITLE
Launching Git bash results in errors, unusable shell

### ISSUE THREAD

**Issue by patricktokeeffe** [gitextensions/gitextensions#1390]
I'm having issues launching the git bash shell from GitExtensions. Selecting Git > Git Bash launches a command window and starts a bash shell. Unfortunately, it has the following error:

`C:\WINDOWS\system32\cmd.exe`

```
c:\Program Files (x86)\Git\bin\bash.exe: *** fork: can't reserve memory for stack 0x490000 - 0x69000
0, Win32 error 0
      0 [main] bash" 3216 sync_with_child: child 4360(0x324) died before initialization with status
code 0x1
    140 [main] bash" 3216 sync_with_child: *** child state waiting for longjmp
bash": fork: Resource temporarily unavailable
bash"-3.1$
```

The bash shell is not usable either - entering any command causes a similar error to occur. (Well, except "exit" which does work...?) For example, "ls" caused the following text: 

`C:\WINDOWS\system32\cmd.exe`

```
c:\Program Files (x86)\Git\bin\bash.exe: *** fork: can't reserve memory for stack 0x490000 - 0x69000
0, Win32 error 0
2152982 [main] bash" 1680 sync_with_child: child 2108(0x31C) died before initialization with status
code 0x1
2153103 [main] bash" 1680 sync_with_child: *** child state waiting for longjmp
bash": fork: Resource temporarily unavailable
```

IDK if it matters but the stack location remains constant while the values preceding "[main]" change with each attempted command. 

I have the context handlers from Git for Windows installed too and if I navigate to my working directory in Windows Explorer and right-click > Git Bash, a (different) bash window launches successfully:

`MINGW32://<redacted>/pokeeffe/Desktop/Python/csifileio`

```
Run 'git help git' to display the help index.
Run 'git help <command>' to display help for specific commands.

pokeeffe@D216-REACCH //<redacted>/pokeeffe/Desktop/Python/csifileio (master|MERGING)
$
```

I'm using `Git-1.7.11-preview20120710`  and `GitExtensions 2.3.3` on a Windows XP SP2 x64 machine. Git is in my path so GitExtensions set itself up with:

```
Command used to run git: git
Path to linux tools (sh): c:\Program Files (x86)\Git\bin\
```

Any thoughts? Ideas? I'm personally betting it's the "x64" part.... that seems to throw a wrench in all my projects on this box.

**Comment by patricktokeeffe** [comment]
Confirming resolved as early as v2.49.03 :+1:

**Comment by RussKie** [comment]
Awesome

**Comment by PoojaGarg20** [comment]
I was facing some issue with GIT bash prompt with 2.10.x version on windows 10. I updated it to 2.16.2 version. Now I started getting error saying 'bash: fork: resource temporarily unavailable.' Please suggest some solution.

**Comment by gerhardol** [comment]
> I was facing some issue with GIT bash prompt

You likely have a PATH problem. The Git bash cmd should work.
https://stackoverflow.com/questions/45764253/error-starting-git-bash-in-windows-7
