### ISSUE TITLE
Refresh Git DAG after running a script

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#1445]
I use a lot Scripts permitted by GitExtension to use git-tfs.

But something annoys me is that the Git DAG (the history displayed in the browser) is not refresh after the use of a script command in the contextual menu when the command fails.

Is it possible to refresh it all the time...

PS : I don't know if it's the right place or if I must create issues :
- In the script table, there is 2 comuns "Confirmation" and "Context Menu", that correspond to no parameters in the command configuration fields (or they are not visible :( ). These columns perhaps should be removed or the fields added (the "Context menu" field was present in an older version...)
- It would be interesting to be able to import/export these scripts configuration (and/or all the gitExtension configuration)... Or perhaps, you know how to do that easily...

**Comment by RussKie** [comment]
Is this still an issue in the current version?

**Comment by pmiossec** [comment]
I don't think it changed but I don't use this feature anymore...
We can close and now that I know how to contribute to GitExtensions, I will add it if I need it in the future 😄

**Comment by RussKie** [comment]
Alright then :)
