### ISSUE TITLE
Undo rebase  

### ISSUE THREAD

**Issue by mhmoudr** [gitextensions/gitextensions#1448]
It is really nice to be able to undo last rebase process, or I would say if we could have access to show reflog and revert to a selected state.

**Comment by webmaster33** [comment]
+1 vote

**Comment by klorinczi** [comment]
Why was this closed? 
It was useful suggestion.

**Comment by RussKie** [comment]
Reflog window is available via menus. It has been implemented several years ago.

**Comment by klorinczi** [comment]
Reflog is hidden down in the menus. Also the Reflog is not a descriptive name.

Git Extensions should be usable for beginner git users, too. Descriptive menus like Undo would help this goal.

**Comment by RussKie** [comment]
The FR stated "..I would say if we could have access to show reflog and
revert to a selected state.".

Git reflog is available via menus. The FR is fulfilled.
We won't be adding more menus,  we already have plenty.
