### ISSUE TITLE
Add tracking branch dialog not working

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#1481]
Version 2.43

```
Push
---------------------------
The branch 2777-text-kvs2 does not have a tracking reference. 
Do you want to add a tracking reference to 2777-text-kvs2?
```

When pushing to remote, there is a dialog saying that the local branch is not tracking the remote. Well, that's great, it can create the reference for me! Well, it did not. This message is displayed every time I push. 

It should call the push with `-u` or `--upstream`  parameter, but the actual command is `"C:\Program Files\Git\bin\git.exe" push --progress "origin" 2777-text-kvs2:2777-text-kvs2`. My colleague @mhujer had the same problem, so it does not seem like a local issue.

**Comment by elevatorguy** [comment]
#7920 has a screenshot.

Pushing isn't the way as #11347 would be ideal; right - so, whatever general solution needs to indicate the pull-only nature of tracking.

`git config -e` and the subsequent editing of `.git\config` needs to be done correctly for indication; have I found a feature yet to exist in git itself?
