### ISSUE TITLE
Push looks for credential storage in wrong directory.

### ISSUE THREAD

**Issue by shalgrim** [gitextensions/gitextensions#1492]
I can no longer push because when I push it looks for git-credential-winstore.exe underneath C:\Program Files (x86)\, but I don't have that directory on my machine, I just have C:\Program Files.

This is what my window reads:

```
"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "CodeOrigin" master:master
"C:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe" get: C:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe: No such file or directory
```

EDIT:
Immediately after posting that, I found this in my .gitconfig

```
[credential]
    helper = !\"C:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe\"
```

However, removing the " (x86)" or removing the two lines altogether just causes push to hang completely

**Comment by increddibelly** [comment]
> The git-credential-winstore.exe file now only in Complete installer
funny that.

**Comment by 89z** [comment]
I just had this issue, turned out that in my environment `HOME` was not set. Setting that environment variable fixed it for me:

https://git-scm.com/docs/git-credential-store
