### ISSUE TITLE
Toolbar won't stay moved / hidden, always returns to second row on second Visual Studio launch

### ISSUE THREAD

**Issue by robrich** [gitextensions/gitextensions#1493]
1. On Visual Studio startup #1, CurrentSettings.vssettings doesn't contain these lines:

```
<add_toolbar Menu="{000D7B18-CDE4-49F0-B194-FE3E25BBF096}:00000009" Name="GitExtensions" MenuType="toolbar"/>
<modify_toolbar Menu="{000D7B18-CDE4-49F0-B194-FE3E25BBF096}:00000009" Name="GitExtensions" Visibility="show" FullScreen="hide" Dock="top" Row="1" FloatRectangle="0,0,208,26" DockRectangle="32,0,208,26"/>
```

GitExtensions, noting they don't exist, adds them to CurrentSettings.vssettings, and shows the toolbar on the far-left of row 2 of the toolbar buttons.  If I move the toolbar, hide it, etc, it gets saved.  (Personally, I prefer row 1.)
1. On Visual Studio startup #2, CurrentSettings.vssettings contains the toolbar details above, and the menu is correctly positioned where I put it.  Shortly after load, these two lines are removed from CurrentSettings.vssettings.  The custom position / hidden state is lost.
2. Goto 1.  The custom position / hidden state is lost.  Subsequent loads return the toolbar to visible and to row #2.

If CurrentSettings.vssettings wasn't cleared on startup #2, we'd be golden.

Git Extensions version 2.43, Visual Studio 2012 (Update 1), msysgit version 1.8.0

**Comment by zldrq** [comment]
looks like it finally works in 2.48.05 (wasn't in 2.48.05)
and also it remembers to display commit button with text now. at last! i'm so glad
(or may be just reinstallation have made it. or maybe the fact that installation was done "on top" of other installed extensions/add-ins)
the fact is: it works

**Comment by drewnoakes** [comment]
@zldrq what version are you referring to? You mention the same version twice, and it's failing for me in 2.48.05.

Is this issue closed as "By design"? This behaviour of Git Extensions is very annoying. Please don't re-add the toolbar at every restart of VS. If I turn it off, it's because I don't want it. Keep re-adding, and the only option is to uninstall.

**Comment by KindDragon** [comment]
Open only one VS instance, close toolbar, close VS, open it again.

> Please don't re-add the toolbar at every restart of VS.

We do not re-add it.

**Comment by drewnoakes** [comment]
@KindDragon I ran some more tests today and observed what you say to be true. However if you modify another extension, it seems that the toolbar is re-added. For example, I reinstalled the NuGet extension in VS2013 today and the toolbar appeared after restarting VS.

**Comment by vbjay** [comment]
That is because devenv /setup is being run.
