### ISSUE TITLE
Open with difftool don't work

### ISSUE THREAD

**Issue by miloja** [gitextensions/gitextensions#151]
Open with difftool don't work.

Steps:
1. Right-click on any file from any commit
2. Click on "Open with difftool"
3. Nothing happens.

Tested with Kdiff3 and Kompare.
gitextensions versions 1.98 and 2.01

**Comment by leaez** [comment]
I met the same error:" git: 'difftool' is not a git-command.  "
My problem is because of PATH variable redirect git version to git version 2.7.4(tow version installed) . 
It works normally after changing to git version 2.24.0.
