### ISSUE TITLE
Favorite Branches

### ISSUE THREAD

**Issue by ido-ran** [gitextensions/gitextensions#1511]
Hi,
It happens to me that I create a local branch and due to something I have to leave it and work on other things. With fast growing repository it is pretty easy to lose this branch behind.

It will be nice to have a list of favorite branches (In my case it will be 1 or 2 branches long) so I can quickly jump to those branches.

It's a nice to have for sure, not a must.

**Comment by RussKie** [comment]
The next major release will contain a branch panel introduced in #4499 that should provide a significant relief.
No further work related to the request is planned in foreseeable future.

**Comment by mlafleur** [comment]
@RussKie, could the decision to forgo this feature be revisited? I work with numerous repositories that contain dozens and in two cases hundreds, of root-level branches. Having to search for `master` every time is less than ideal. The ability to favorite the few branches I care about in a given repository would be extremely helpful.

**Comment by mstv** [comment]
If you have only a few **local** branches, there will be only a very short list of "Branches" in the Left Panel.
(Ahead/behind info can be added to these branches if they have been pushed.)

![image](https://user-images.githubusercontent.com/36601201/144919462-5212316b-6ce3-4254-b5e5-a4e497bf1dfd.png)

**Comment by gerhardol** [comment]
This has been discussed in other issues too.
While local branches can be renamed to sort well, remote branches are harder to find (use search).

My suggestion is that prio branches are configured with a regex that are sorted first in Local/Remote branches.

But GE is a community project, if someone wants it, they will implement it.
