### ISSUE TITLE
HelpImageDisplayUserControl: optionally separate the Show button

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1529]
Refering to https://github.com/gitextensions/gitextensions/pull/1526#issuecomment-11940719 :

To be able to place the "Show info" button at another location it has it be separated from the HelpImageDisplayUserControl.

Suggestion: On HelpImageDisplayUserControl create a new property AlternativeShowButton of type Button. If set (possible via Designer or code behind) the default Show button is not shown anymore and there is more space if HelpImageDisplayUserControl collapsed. Instead the alternative button control takes over the role of the default Show button.

**Comment by RussKie** [comment]
We won't be doing this.
