### ISSUE TITLE
Git Extensions 2.41 not working 

### ISSUE THREAD

**Issue by sabby62** [gitextensions/gitextensions#1530]
I tried to upgrade my installation of Git Extensions from version 2.33 to 2.41. After installing new version, I cannot start my Git Extensions. When I go back to 2.33, it just works fine. Tried uninstalling and installing the new version - nothing works. Checking the Windows Event Log, I get the following Application Error:

Application: GitExtensions.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
at GitExtensions.Program.Main()

Faulting application name: GitExtensions.exe, version: 2.43.0.0, time stamp: 0x509191b6
Faulting module name: KERNELBASE.dll, version: 6.2.9200.16451, time stamp: 0x50988aa6
Exception code: 0xe0434352
Fault offset: 0x000000000003811c
Faulting process id: 0xff0
Faulting application start time: 0x01cded199fe0da1d
Faulting application path: C:\Program Files (x86)\GitExtensions\GitExtensions.exe
Faulting module path: C:\WINDOWS\system32\KERNELBASE.dll
Report Id: dd92cc0a-590c-11e2-be80-20cf305c3f7a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by srinathrajappa** [comment]
Faulting application name: GitHub.exe, version: 2.7.0.24, time stamp: 0x54b6e999
Faulting module name: KERNELBASE.dll, version: 6.2.9200.16864, time stamp: 0x531d2be6
Exception code: 0xe0434352
Fault offset: 0x00010f22
Faulting process id: 0x4f0
Faulting application start time: 0x01d03adac8709060
Faulting application path: C:\Users\Srinath\AppData\Local\Apps\2.0\W3GHEWLQ.YWO\4829OCV8.HYJ\gith..tion_317444273a93ac29_0002.0007_cc7bcd60c65d01d4\GitHub.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: 066577be-a6ce-11e4-bfbb-d98e1dcbb30f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by srinathrajappa** [comment]
Faulting application name: GitHub.exe, version: 2.7.0.24, time stamp: 0x54b6e999
Faulting module name: KERNELBASE.dll, version: 6.2.9200.16864, time stamp: 0x531d2be6
Exception code: 0xe0434352
Fault offset: 0x00010f22
Faulting process id: 0x4f0
Faulting application start time: 0x01d03adac8709060
Faulting application path: C:\Users\Srinath\AppData\Local\Apps\2.0\W3GHEWLQ.YWO\4829OCV8.HYJ\gith..tion_317444273a93ac29_0002.0007_cc7bcd60c65d01d4\GitHub.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: 066577be-a6ce-11e4-bfbb-d98e1dcbb30f
Faulting package full name: 
Faulting package-relative application ID:

**Comment by srinathrajappa** [comment]
please do any help for me not install github windows 8 pro

**Comment by spdr870** [comment]
@srinathrajappa: Is seems that you are trying to install GitHub for windows. This is the issue tracker of GitExtensions.
