### ISSUE TITLE
DND from File tree tab (or Diff tab) drags working dir file

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1544]
When dragging a file from the File tree tab I would expect that the file is taken from the selected revision. Instead the current working dir file is copied. Is this the desired behaviour? If yes one could show a note to the user as soon as dragging begins to notify about this fact.

**Comment by jwfx** [comment]
I stumbled across this behavior today with version `3.5.1.12196`. I have to agree that this behavior is very much unexpected. As a user when I am looking at a commit in the past (with either the diff tab or the file tree) my assumption was that the drag&drop action would be in context of that past commit and not the current working dir or most recent commit.

As this issue has the "up-for-grabs" tag, does that mean this behavior could be changed via a pull request?

**Comment by gerhardol** [comment]
Duplicate of #9239 
Open later, but there is a discussion and a linked PR.
Please contribute to the discussion in the issue/PR there...
