### ISSUE TITLE
Context menu for commit with remote branch doesn't offer `Delete branch` option

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#1583]
Is there a reason why deleting remote branches aren't offered from the context menu? Or is it just the case that nobody did that :)

If it's the later I propose this as a UX improvement otherwise I'd like to hear the arguments against this.

**Comment by cyrilgandon** [comment]
+1

**Comment by cyrilgandon** [comment]
:+1:

**Comment by dirk-butze** [comment]
:hand: one more vote  :pray: :

**Comment by esride-mag** [comment]
Do it!

**Comment by tomasfejfar** [comment]
I would very much like it as well :) 
![selfie-2](http://i.imgur.com/tafpLdX.gif)

**Comment by Gua-naiko-che** [comment]
Hi,

Is anybody already working on this issue? I haven't seen any related PR. In case nobody is working on it, I will try to do it.

I would like to hear your opinions about this:
There is already a FormDeleteBranch which allows to pick several branches to delete them. 
**Should we re-use that form, adding the ability to delete also remote branches, or should we create a different form?** 

If we re-use the existing form, maybe we should add a confirmation dialog before deleting a remote branch for avoiding mistakes... although nobody reads confirmation messages.

**Comment by vbjay** [comment]
Deleting multiple remote branches is done in the push dialog.  Open the
push dialog.  Choose the right remote.  Switch to the multiple branches
view.  Note the actions that can be preformed.  One is delete the remote
branch.

**Comment by tomasfejfar** [comment]
Nevertheless having a context menu to delete branch as you have for local branches would be a great help.

**Comment by vbjay** [comment]
What could be done is setup of the push dialog to show the multiple branches view and focus the checkbox for the branch and remote.  You right click on origin/newFeature branch marker.  Click menu option delete remote branch...  It brings up the push dialog with multiple branch view, that remote and branch checkbox focused and unchecked.  Allow the user to check by pressing spacebar.

**Comment by vbjay** [comment]
Frankly, deleting remote branches, should be a little hard to do.  You shouldn't be able to right click and delete a remote branch.  There needs to be a process of confirming the selected remote/branch.  I don't mean a simple message box either.  I mean a selection of the branches to delete and remote to make it a clear and conscious effort.

**Comment by RussKie** [comment]
> Deleting multiple remote branches is done in the push dialog

Thanks Jay.
So whilst the functionality is provided it isn't intuitive not discoverable
at all. It is a poor UX and more can be done.

**Comment by RussKie** [comment]
Yes, I agree

**Comment by Gua-naiko-che** [comment]
Thanks for your comments.

I agree that it should be a little difficult to delete a remote branch, and that a confirmation message box is not the right solution.

I also agree that the existing functionality is hard to discover. Funnily I found it not in the UI, but while looking the code trying to decide how would I implement this feature!

In order to make it more discoverable, I like the solution you propose, @vbjay . I'm going to try to implement it.

**Comment by vbjay** [comment]
Great.  After the menu click the dialog would look like this.  Notice how I could press spacebar and the origin/master delete remote branch checkbox would be checked.  

![image](https://user-images.githubusercontent.com/3629489/32575230-7367e568-c4a1-11e7-8dc7-8aed127a5efd.png)

**Comment by RussKie** [comment]
An ideas for UI:
* extend the existing context menu "Delete branch" to have two submenus:
   - Local branch...
   - Remove branch...
Clicking the main menu or the "local" submenu invokes the existing code paths
Clicking the "remote" submenu shows a dialog to delete remote branches. It may look similar to the "delete local branch" dialog.

Thoughts?


(I am not familiar with the code at all) Keep an eye on what functionality relates to branch deletion and see if it can be extracted into its own class/set of classes following SOLID principles.

**Comment by Gua-naiko-che** [comment]
Hi @RussKie, thanks for your ideas. 

I think that we should use the existing PushForm, which already allows to delete remote branches, instead of creating a new dialog similar to the "delete local branch" one. I see two reasons for this: avoid having two different ways to perform the same action, and make the deletion of a remote branch "a little difficult", as exposed by @vbjay.

And in relation to splitting the context menu into two sub-menus... I don't see a lot of interest in making that differentiation, since you are already going to be directed to different forms depending on the type of the selected branch... but I would like to hear opinions from others.

**Comment by mdonatas** [comment]
Maybe I am missing something but what's with the "make it difficult" part? If you delete a remote branch by accident you can always push it back with the same name and in most cases no one would even know.

I suggest a variation of @RussKie 's suggestion: Have the same branch delete menu as it is now but add a separator to separate local and remote branches. Also remote branches will be displayed with a repository prefix i.g. origin/old_branch which will make it really clear that this is not a local branch we are talking about.

As for reusing that (sorry) ugly multi-push dialog - it gives me creeps. It's so confusing and scary that I resort to cmd: `git push origin :branch_to_delete` just to be sure that my actions will do only what I intended. I sugget to leave it for mass operations.

Several other Git GUI clients don't get in a users way for remote branch deletion. GitExtensions shouldn't either.

**Comment by RussKie** [comment]
> If you delete a remote branch by accident you can always push it back
with the same name and in most cases no one would even know.

That's assuming you have a local ref for that branch....

**Comment by vbjay** [comment]
AMEN. EXACTLY. Local branches aren't as bad and we have a guard against non
merged branches deletion. You also have the reflog. So local branches are
safer to delete. You don't have those protections with remotes. You do have
the reflog, but getting to a remote reflog isn't always possible.

**Comment by tomasfejfar** [comment]
Please note that usually the screenshots show the happy path. Here is a screenshot of my push dialog:

![image](https://user-images.githubusercontent.com/642928/32597506-377b8de8-c537-11e7-81e6-fd8ea54d8c5a.png)

Much less fun to find the correct branch and VERY error-prone game of "check checkbox in the correct line"

**Comment by mdonatas** [comment]
Given that it would be relatively hard to delete a remote branch by accident and not have it covered by a local branch or find it in a reflog OR find it in `Tools > Gitcommand Log` (I assume there'd be a SHA of branches' commit mentioned) there is still a way to list dangling commits and fish it out from there: https://stackoverflow.com/questions/3640764/can-i-recover-a-branch-after-its-deletion-in-git/22303923#22303923 - yes, this process is not very pleasant but on the other hand deleting remote branch by accident is not something that happens often.

What's more, if remote branch didn't have a local branch covering it, most probably that branch belonged to someone else and then it's just a chat/email away from asking that person to re-push it.

All this to say that it's not worth creating artificial roadblocks for remote branch deletion.

**Comment by vbjay** [comment]
I disagree. It should be not ever be a 1 click operation even with a
confirm box. It should be a concious effort to delete a remote branch. It's
too easy to click the wrong context menu option. The push dialog require
you to pick a branch to delete. It highlights the row you are manipulating.
It prevents mistakes.

**Comment by mdonatas** [comment]
I've checked how other GUI clients do it.
GitKraken just lets you right-click and delete:
![image](https://user-images.githubusercontent.com/483659/32612399-1d6433be-c560-11e7-92ee-f1960c7758cd.png)

SourceTree also lets you easily delete a remote branch albeit remotes are under separate tree node in branches list:
![image](https://user-images.githubusercontent.com/483659/32612634-ab0c2eba-c560-11e7-8536-e2e33dff60a9.png)

I am pretty sure if they had a significant number of users deleting remotes by accident, they'd change that based on feedback.

The main reason I am against using that multi-push form is because it is a UI/UX disaster. You want to do 1 thing only - delete a remote, but you'll be anxious about hundreds of other check boxes thinking if you won't screw other branches by accident. Doesn't matter if they are all unchecked by default, users will still scroll to double-check and won't feel confident **being afraid of the tool and not their own intentions**.

**Comment by vbjay** [comment]
I didn't say we couldn't create a dialog that only let you delete branches.
I'm saying I am dead set against a menu that screws with a remote branch
without me specifically checking the branch and I can verify which ones
will be deleted. Frankly a push dialog makes sense because that's what you
are doing.

**Comment by Gua-naiko-che** [comment]
Hi,

IMHO the fact that the git command used for deleting a remote branch is "push" could be considered an "implementation detail", and should not necessarily impose the utilization of the Push Form.

Maybe a solution that provides a better UX and avoid accidental deletes is to create a dialog similar to the "Delete local branch" one, but in which the remote branch is not automatically selected, as has to be selected manually from the drop-down. 
The only thing that bothers me is that it may be a bit surprising for the user to select a branch in the context menu and then arrive to the dialog without the branch selected.

What do you think about this solution?

**Comment by vbjay** [comment]
The added step of selecting the branch is the protection of "I am deleting
what branch?".  Can you imagine the freak-out of opening a folder in
explorer and being able to hit delete and delete files?  We could even have
a checkedlistbox to allow the users to select multiple branches.  It is
still an affirmative conscious action and not a mis-click on a context
menu.  We could even have a confirm box on ok that says, you are about to
delete the following branches from the {remote name} branch:
{branch name}
{branch name}
{branch name} .....
Are you sure, you want to delete?

**Comment by Gua-naiko-che** [comment]
I agree with you, but in relation to this

> Can you imagine the freak-out of opening a folder in explorer and being able to hit delete and delete files?

You should know that this is the default behaviour in Windows 8, 8.1 and 10:
http://techdows.com/2015/02/make-windows-10-display-delete-confirmation-dialog.html

**Comment by vbjay** [comment]
I have had personal experience with a UI screwing up and it clicking on the
other menu option.  Why I am so insistent on the affirmative conscious
action being there.    A simple messagebox is NOT enough.

**Comment by vbjay** [comment]
My example with the explorer wasn't talking about that.


   1. Open a new explorer window
   2. Navigate to a folder
   3. Press delete key

Nothing happens as it should.  You HAVE to select a file to delete.

**Comment by vbjay** [comment]
Not to mention, we have the recycle bin.  It always confirms on remote
drives without a recycle bin.

**Comment by mdonatas** [comment]
How about a drop-down with a pre-selected remote branch but also somewhere around it a checkbox with a label "[  ] Delete origin/master remote branch". And until it is checked submit button is not enabled.

**Comment by vbjay** [comment]
I think we would want the option of multiple branch select for one remote.
A dropdown for the remote and a checkedlistbox for the selection of which
branches to delete.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/32627137-77546b2e-c55f-11e7-827f-4ad23d0ddf79.png)

**Comment by vbjay** [comment]
We would need a check for is the [default] branch is able to be selected?  The default branch is not always master.  Can we get the default branch name from a remote?

**Comment by vbjay** [comment]
My suggestion is that the menu could say delete remote branches and a sub menu option for each remote that could init the form with the right remote selected.

**Comment by mdonatas** [comment]
Since we already have a UI to perform multiple operations, I image a workflow when right-clicking on a concrete commit to be a lot closer to regular branch delete but with an added safety (the chekbox):
![image](https://user-images.githubusercontent.com/483659/32631608-a35cf716-c598-11e7-8d6e-d322deec71e0.png)

The checkbox label could also reflect selected branch.

**Comment by vbjay** [comment]
I disagree. I like the idea of multiple branches. There are times when you
want to cleanup multiple branches. I would want to pick branch x, y, z from
selected remote.

**Comment by mdonatas** [comment]
How is that different from a multi action push dialog then except that it's
cleaner?

**Comment by vbjay** [comment]
That's the whole point. Geez. He gets it now. It would not lose any
functionality.

**Comment by vbjay** [comment]
The push dialog makes sense. However, people complained that it is a gui
nightmare. Well frankly I as a git user would understand that deleting
remote branches would take a push. Fine. Then we create a separate dialog
to select branches and delete them from the remote.

**Comment by RussKie** [comment]
I go to bed and this happens... :D

There are few constructive points from both sides.

How about the following?
As per my original suggestion to have a similar to "delete local branch" dialog for deletion of remotes. The dialog will have a list with checkboxes to facilitate multi value selection.
Under the list there will be a checkbox to confirm the selection (similar to the "delete local branch" dialog) which enables the OK button once checked.

**Comment by vbjay** [comment]
Sounds great.

**Comment by XopherThomas** [comment]
I continue to desire this functionality, so much that I have manually added it to git with a script add on.  

Script:
Name: Delete Remote Branch
Command: bash
OnEvent: None
Confirmation: unchecked, it doesn't confirm if checked anyway
Arguments: -c "git push origin --delete $(echo {sRemoteBranch} | sed 's/origin\///')"
Add to revision grid context menu: checked

This implementation allows me to right click on a commit with a remote branch.  If multiple remote branches exist at the point, a crude little dialog pops up to select which one.

It's easy to use to delete specific remote branches that are on the currently clicked commit.  My need to delete integration and personal branches from the remote are on a near daily basis.  This method is risky without any confirmation, but the exiting functionality is so completely cumbersome (see tomasfejfar's push dialog above) that there had to be some better way.

The best way should be GitExtensions providing the support directly, which supporting confirmation.  If there is so much concern that GitExtensions users are incapable of handling the power and risk, then why not provide the option for those who find the risk acceptable, but disable the dialog by default.

**Comment by vbjay** [comment]
It's not that.  The fact that a remote is being manipulated care needs to
be taken.  I have had the timing of a right click release and move select a
menu option and click it.  All I am insistent on is the action of selecting
the remotes and then hitting a button somewhere away from the selection.  I
like the idea of the extra checkbox confirming these branches making the ok
button enabled.  I'm not against a separate dialog.  I am against the menu
doing the work with a confirm messagebox.

**Comment by XopherThomas** [comment]
![image](https://user-images.githubusercontent.com/24945415/32665040-dcd54828-c5e7-11e7-9d62-5b6469abce04.png)
This is a window capture of the existing dialog I see by using {sRemoteBranch}.
A nicer window which gave you a list of the currently clicked commit remote branches, each with a checkbox and none selected by default.

I would think the Delete Remote Branch should not even list the branches available, like Delete Branch does, it should only end in ... indicating a forthcoming dialog.

The dialog could look non-unlike the Push Multiple branches, but by default Nothing should be selected and only the remote branches from the selected commit would even show up.

**Comment by vbjay** [comment]
I want the selecting of multiple branches.  Yes.  It should list them.

**Comment by Gua-naiko-che** [comment]
It seems that we are getting close, hehehe.

@RussKie , you say

> Under the list there will be a checkbox to confirm the selection (similar to the "delete local branch" dialog) which enables the OK button once checked.

I want to be sure to understand you. You propose to have an additional checkbox to confirm the operation we are about to perform? Like "Confirm deletion of remote branch(es)". Is that it?

**Comment by vbjay** [comment]
Yes. A checkbox that enables the ok button. It says something like

Delete the selected branches from above.

**Comment by Gua-naiko-che** [comment]
Ok, I will try to recap some kind of "specification":

1. If the selected commit has one or more remote branches associated, we will add an option in the sub-menu for "Delete branch" with the text "Remote branches..."
2. When this option is clicked, a dialog similar to the "Delete local branch" will be opened, containing a list with checkboxes for all the remote branches associated with the commit, without any of them being selected by default.
3. Under the list there will be a checkbox with the text "Delete the selected remote branches from above".
4. The "Delete" button will be enabled only if there is at least one selected remote branch and the confirmation checkbox is checked.

Is that it?

I think I can start working on it, even if there are some minor changes.

**Comment by vbjay** [comment]
Add a drop-down that picks which remote. Be aware of inactive vs active
remotes.

**Comment by tomasfejfar** [comment]
Ideally (not sure if possible) the checkbox would read: 

"Delete branches **tf-my-branch**, **other-brach** from **upstream** remote"

**Comment by vbjay** [comment]
Even better. As you select branches, the text changes.

**Comment by mdonatas** [comment]
We can add safety option to a dialog which would be very similar to a "delete local branch" dialog. The mentioned checkbox which would enable confirmation button should do the trick.
Since conceptually deleting a ref on local and remote repository is very similar I am voting for keeping the dialogs similar too (except for the safety checkbox).
I think this is a clean and clear solution, thoughts?

1. Select a branch you want to delete
![image](https://user-images.githubusercontent.com/483659/32682823-21c3a524-c66f-11e7-9693-bf39626eb03e.png)

2. Review the changes; check the checkbox and delete (not all labels are correct, it's a WIP)
![image](https://user-images.githubusercontent.com/483659/32682838-33557f56-c66f-11e7-8ee8-fae2c8016785.png)

**Comment by vbjay** [comment]
Nope. You really aren't getting the point of MULTIPLE branches being
selected in one dialog.

Do you get it?  Of course there wiujd be other controls but this is the
idea.

**Comment by mdonatas** [comment]
Why do you keep bringing "multiple" in to a conversation about deleting a single branch? For "multiple" operations there is a "Push multiple branches" tab in the Push dialog.

**Comment by vbjay** [comment]
Because the complaint was that push is a nightmare. So I say rip out of
push and make a dialog that allows the user to pick remote/branches.   It
is an idiotic menu system to list every branch for every remote. The dialog
should allow the user to pick it

**Comment by mdonatas** [comment]
1. This issue is **not** about the push dialog, it is about deleting remote branch from a context menu on a commit (read the the top post)
2. _It is an idiotic menu system to list every branch for every remote._ You are correct, that is why nobody is suggesting that. The submenu for "Delete branch" only lists branches on a commit which for majority of the cases is few (see my screenshot).
3. If you still feel that Push dialog needs improvement, please create a separate issue

**Comment by vbjay** [comment]
I'm aware of push not being this issue. I'm saying yank the functionality
from push and move it over to this proposed dialog.

**Comment by vbjay** [comment]
The remote/ branch limiting works till you have merged into master and you
end up listing 99% of remotes/ branches. Do not use the menu to pick the
branch. Use a menu to pick the remote. Let the user pick the branches in
the dialog.

**Comment by mdonatas** [comment]
Please elaborate on "you end up listing 99% of remotes/ branches". After merging if you list the branches on a commit with master it will probably just be `master; origin/master` and if you list the branches on a feature branch which was just merged into master it would probably just be `someremote/feature-123`

Your suggestion for "use menu to pick remote..." is more suitable not for a context menu on a commit but for a menu item under Commands > Delete remote branch > origin; upstream; etc i.e. what you describe doesn't sound specific to a commit and this whole issue is about specific commits context menu.

**Comment by vbjay** [comment]
Not all repos have only a few branches. If you right click on head in
master or below, then you'll get all remote/ branches merged into master.
What if that entails 10 remotes all containing 30 branches?

**Comment by mdonatas** [comment]
Either way, if you are still dead set on a generic remote branch deletion dialog which is not context specific for a given commit - I am against that, so then we should probably put forth our proposals and have a vote as we are going in circles.

**Comment by vbjay** [comment]
The point is you can use the context of the menu to pick which remote to
init the dialog. Then pick the branches.

**Comment by vbjay** [comment]
Still allow the user to switch it if they picked the wrong one.

**Comment by mdonatas** [comment]
_If you right click on head in master or below, then you'll get all remote/ branches merged into master._ Where did that come from? A menu lists only the branches currently pointing to that one specific commit. Do you have any example in any repo where there are many branches pointing to a single commit?

**Comment by mdonatas** [comment]
_Still allow the user to switch it if they picked the wrong one._ In my screenshot the user can do that from a drop-down, just like with the local delete.

**Comment by RussKie** [comment]
@mdonatas I like you proposal in https://github.com/gitextensions/gitextensions/issues/1583#issuecomment-343614880.
It makes sense. 
In unlikely event a user has several remotes for the same commit they can repeat the operation few times.

**Comment by mdonatas** [comment]
Please have a look at proposed solution in this PR #4146
Waiting for comments :)
