### ISSUE TITLE
Show file diff between two branches?

### ISSUE THREAD

**Issue by Stoffe** [gitextensions/gitextensions#1596]
Ok, maybe Im missing something but...
I have a file, file1.txt
I have two branches: master and development
ok, HOW??? Do I do from git extensions to select this file, and see the diff between this file in the two branches???

I mean, in the commit in master (wich is the released version) and the commit in development version, wich is the up to date version, How, Do I do a diff witch shows what has happened to this specific file in theese two branches??
Either in difftool or kdiff... (preferably from git extensions) ??

**Comment by ntea** [comment]
And when we do not the diff because of :
"Sorry, we could not display the changes to this file because there were too many other changes to display."

**Comment by anton6** [comment]
@jbialobr Where is this "revision grid" found?

**Comment by vbjay** [comment]
Revision Grid is the view of the commits in the main window.

**Comment by vivainio** [comment]
I know this is closed, but it would be handy to expose this feature in "file tree" (e.g. "compare this file (or directory) between version in other branch"). It's quite unwieldy to try to find the right branch in revision grid.

**Comment by RussKie** [comment]
@vivainio please open a new issue for your feature request.

**Comment by vivainio** [comment]
@RussKie done: https://github.com/gitextensions/gitextensions/issues/3913
