### ISSUE TITLE
PLink hangs on pull from Gerrit

### ISSUE THREAD

**Issue by pvginkel** [gitextensions/gitextensions#1613]
We use Gerrit as our git repository and PLink hangs on pull on some repositories. This happens only on some repositories, but it happens every time for these repositories.

When I replace the PLink.exe of GitExtensions with the latest version from http://www.chiark.greenend.org.uk/~sgtatham/putty/download.html, the problem goes away. Is it possible that PLink is updated to its latest version?

**Comment by phillijw** [comment]
Not sure if anyone ever figured this out, but I did a long time ago... I ended up having to downgrade Plink for it to work. I think I went down to 0.62 from 0.63 or something like that.

**Comment by pvginkel** [comment]
I went to beta, but that was a while ago. Anyhow, we've moved to gitlab by
now, so the whole problem doesn't apply for us anymore.

**Comment by KindDragon** [comment]
We update Plink to version 0.67
