### ISSUE TITLE
Installer: Close open applications closes Windows Explorer including desktop

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1624]
[Minor] This is an older and rather minor issue but it just occured to my colleage. The installer shows this message when trying to install the Windows Explorer shell extension:

![2013-02-18_18-45-22_Git Extensions 2 44 Setup](https://f.cloud.github.com/assets/368412/168206/a1b882ea-79f3-11e2-83f1-9492fa62359d.jpg)

Click OK causes the setup to close the explorer including the desktop. This leaves the user without desktop. I don't know if this can be fixed (e. g. by using another installer #1079). Or should it be seen as Windows specific problem?

**Comment by d07RiV** [comment]
It doesn't restart explorer after finishing, though, you're left with an empty PC screen.

**Comment by RussKie** [comment]
This happened to me few times.

When I looked at the list of processes there were few other Explorer.exe
processes running that wouldn't close, asked politely. As a result a
request to close would either expire or hang, and that would lead to the
reported issue.

Few times I would run a PowerShell script to kill offending Explorer.exe
instances (writing from memory):

    Kill-Process -Name Explorer.exe

and the installer would immediately continue and finish successfully.

Not sure how easy it is, perhaps we could update the installer to run the
script as well.... 🤔

**Comment by gerhardol** [comment]
Killing Explorer.exe and not restarting occurs in many installers.
I would prefer to exclude Explorer.exe here and inform that changes to the shell integration will require a restart instead.

**Comment by vbjay** [comment]
FYI

User can close explorer windows and hit Ctrl shift right click on taskbar
to get exit explorer menu. Then user can use Ctrl alt del to run task
manager to run explorer to get taskbar to come back.
