### ISSUE TITLE
fatal: Out of memory, malloc failed (tried to allocate 272520209 bytes)

### ISSUE THREAD

**Issue by alexeik** [gitextensions/gitextensions#1632]
"C:\Program Files\Git\cmd\git.cmd" push -u --recurse-submodules=check --progress "np4" master:master
Counting objects: 9007, done.
Delta compression using up to 2 threads.
fatal: Out of memory, malloc failed (tried to allocate 272520209 bytes)
fatal: The remote end hung up unexpectedly
error: failed to push some refs to 'git@np4:tftpboot'
Done

hi every1

i got some problem.

i push about 13 Gb size folder about 9007 files.
and got these error.

help please.
i dont know what to do .

**Comment by pramock4bs** [comment]
Im getting same issue, and I changed the gitconfig values also. Still same , but when restart its fine. After sometime again will get same issue. Please help

**Comment by KindDragon** [comment]
You should ask there https://github.com/git-for-windows/git/issues

**Comment by ozzpy** [comment]
add limit into your .gitconfig
[core]
  packedGitLimit = 128m
  packedGitWindowSize = 128m

[pack]
  deltaCacheSize = 128m
  packSizeLimit = 128m
  windowMemory = 128m

**Comment by Kos-M** [comment]
i got similar issue in my gogs server.
i had gogs server behind nginx reverse proxy.
 i changed ```client_max_body_size 1m;``` default to ```client_max_body_size 20m;```
may help you.
source : https://confluence.atlassian.com/bitbucketserverkb/git-push-fails-fatal-the-remote-end-hung-up-unexpectedly-779171796.html

**Comment by AzizOzenir** [comment]
removing and reinstalling git fixed for me
