### ISSUE TITLE
Installation of VS-Plugins fails

### ISSUE THREAD

**Issue by tacker66** [gitextensions/gitextensions#1634]
Setup of 2.44 fails, when it cannot install VS plugins. Even when all VS plugins are
deselected in the option dialog, setup fails because it still tries to access the 
(not needed) addin path. (I am using VS2010.)
(1) This case imho should only cause a warning (as it did up to 2.43).
(2) Where does the path come from which is queried during setup?
This path is faulty on my machine and of course should be corrected
to get the VS plugins installed.

**Comment by RussKie** [comment]
Is this still an issue with the current version?

**Comment by tacker66** [comment]
No, thanks!
--
----
Thomas Sonntag, 27 August 2017, 00:25Nachm. +02:00 von RussKie  notifications@github.com :
