### ISSUE TITLE
Remove font limitation for source code.

### ISSUE THREAD

**Issue by ChameleonRed** [gitextensions/gitextensions#1642]
--- GitExtensions2.44, 1.8.1.3, Microsoft Windows NT 5.1.2600 Service Pack 3

Allow to choose Source Pro font - what currently is not possible for sources.

http://blogs.adobe.com/typblography/2012/09/source-code-pro.html

**Comment by RussKie** [comment]
I know it has been awhile since the request.
If it is still relevant, please provide more clarity on your request.
