### ISSUE TITLE
Collect all GIT Repos of a VS Solution in one place

### ISSUE THREAD

**Issue by bernhardberger** [gitextensions/gitextensions#1644]
I love GIT Extensions so far. Works flawlessly and the Commit and Push-Button is a blessing comming from AnkhSVN.

BUT:
we have several projects in our solutions, spread across different projects - each with it's own repository.

It would be really awesome if there would be one interface to collect all pending changes across those projects - so you don't have to click on each single project first to see if there are pending changes (we are in the middle of a big refactoring process which leads to changes across all of them)

**Comment by RussKie** [comment]
Closing due to age and vague requirements.
