### ISSUE TITLE
Bad config file causes GitExt to show "unresolved merge conflicts"

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1653]
If there is an error in .gitconfig GitExt shows the following error screen (There are unresolved merge conflicts): 

![2013-02-23_20-40-38_rc master - Git Extensions -_ DEBUG _-](https://f.cloud.github.com/assets/368412/188498/f56516fa-7df0-11e2-829f-33ff7259116f.jpg)

Only the command line shows the real cause of the problem:

```
$ git status
fatal: bad config file line 3 in .git/config
```

Maybe there is a way to show the error output of git status on the GUI.

**Comment by kamlekar** [comment]
Seeing similar error:
![image](https://user-images.githubusercontent.com/2201186/164914156-65b6dd14-b1a2-4f93-b529-308255b321c4.png)

I think it is because of switching between WSL and windows repos. Not sure.

**Comment by mstv** [comment]
Perhaps related to git update this time: #9954.

**Comment by mstv** [comment]
Could you share the environment info, please?

![image](https://user-images.githubusercontent.com/36601201/164979424-139583dc-fcbc-4f31-8f99-3d9b34edc71b.png)

and the Git Command Log (`F12`)

or rather which misconfiguration has caused the misleading banner.

**Comment by kamlekar** [comment]
@mstv here it is:

```
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.36.0.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4470.0
- DPI 96dpi (no scaling)
```

**Comment by kamlekar** [comment]
And for all windows repos, showing as follows:

![image](https://user-images.githubusercontent.com/2201186/164983816-fcfdd75e-aa37-4d82-ac87-35dc084b9a5a.png)

**Comment by mstv** [comment]
For WSL, it is https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1104212187.

**Comment by mstv** [comment]
I guess the dev version will display the git error message.
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by kamlekar** [comment]
> For WSL, it is https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1104212187.

Thanks @mstv I already tried that after getting the issue in WSL. Seems to be no use.

**Comment by MartinLechner-TD** [comment]
That's a good improvement, but I think the git command shows only a warning and throws no error and works as expected. So I think git Extension misinterprets this hint as error. Other git GUI's like TortoiseGit and Fork works with the same git configuration as expected,

**Comment by gerhardol** [comment]
GE in master throws if the Git command exit code is not 0.
In 3.5 the output is parsed, which is the error here

**Comment by kamlekar** [comment]
Updated above comment: https://github.com/gitextensions/gitextensions/issues/1653#issuecomment-1107863363

**Comment by kamlekar** [comment]
Hey, this worked for me:

```
git config --global --add safe.directory *
```

Ref: https://github.com/gitextensions/gitextensions/issues/9954#issuecomment-1117208958

**Comment by twhitmorenz** [comment]
Same as [MartinLechner-TD](https://github.com/MartinLechner-TD) -- I upgraded to Git 2.36 and accepted the "experimental FS monitor" option. From the command-line Git now says the config parameter has changed, and wants 'core.fsmonitor' instead. Configuring that resolved the GE issue.

**Comment by dsimat** [comment]
Same here but

`git config --global --add safe.directory *`

did not work. I had to add each repository directory individually.
