### ISSUE TITLE
Large fonts

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#1659]
GitExt doesn't display properly UI components when large font is set.

**Comment by RussKie** [comment]
2.50 is generally usable with large fonts
![image](https://user-images.githubusercontent.com/4403806/34428832-b1cfd024-eca4-11e7-8b03-41a809095a31.png)

Of course there are artifacts (typically buttons are squashed) but I wouldn't call the app unusable.

This is not something we can fix without a major re-write.
