### ISSUE TITLE
Globals vs. Local Settings: common user control to use in both dialogs?

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1684]
Currently on the GlobalSettingsPage and the LocalSettingsPage there are almost the same controls for editing the .gitconfig (or .git/config) file. Do you think it makes sense to create a common UserControl which is used in both dialogs to get identical GUI layout and same loading and saving logic and to be able to add further settings (like proxy settings) easier?

(This UserControl should be able to hide settings that we don't want to show on the local (or global) settings page.)

**Comment by jbialobr** [comment]
Obsolete.
