### ISSUE TITLE
Option to hide stashes in log

### ISSUE THREAD

**Issue by doxxx** [gitextensions/gitextensions#1686]
Stashes can clutter up the log tree view, so it would be nice to have an option to hide them.

--- GitExtensions2.44, 1.8.0.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by timabell** [comment]
I've seen a couple of times inexperienced git users not understanding what the stash commits are and merging them in to the main branch. With a less experienced team these rather odd "wip" commits have become part of the long-term history; which is less than ideal.

I'd suggest that if this feature is implemented, it becomes the default to hide the stash, and advanced users can re-enable it. I'm starting to see more teams moving from TFS-VC to TFS-git hosting, and a lot of them find the whole journey more than a little overwhelming so anything we can do to make that a little less harsh would be appreciated.

**Comment by Kableado** [comment]
@RussKie Does closing this mean that this feature will not be considered?

**Comment by vovodroid** [comment]
> explaining why it is useful

As topic starter said, 

> Stashes can clutter up the log tree view

**Comment by mstv** [comment]
![image](https://user-images.githubusercontent.com/36601201/233843821-4398ad24-73e4-4ca2-aca2-28f9e1fcc4ed.png)
