### ISSUE TITLE
Starting window doesn't show entries under headers on Linux

### ISSUE THREAD

**Issue by mycroes** [gitextensions/gitextensions#1713]
On Ubuntu 12.10 when running GitExtensions the main window doesn't show any entries under 'Common Actions', 'Recent Repositories' and 'Contribute'. The 'Recent Repositories' menu does list my recent repositories and they open fine. Please see the attached screenshot for a sample. GitExtensions used is 2.44.
![GitExtensions_start_empty](https://f.cloud.github.com/assets/122017/252812/c25000c2-8bb5-11e2-8276-644bdbc24e4f.png)

**Comment by UncleVasya** [comment]
Checked old versions of GitExt: issue was introduced in 2.44.
Can't find specific commit cause I have troubles building such old revisions for mono.

**Comment by UncleVasya** [comment]
Found out how to build for Mono old GitExt versions. Traversed commits and localized the breaking one: https://github.com/feinstaub/gitextensions/commit/e615039922f152e174f35f7a1d41fe2bf7b9a641

Investigating changes.

**Comment by fraga** [comment]
Good job! What's your current mono version @UncleVasya?

**Comment by UncleVasya** [comment]
@fraga, I compile on WinXP with mono 3.2.3 and test on virtual Ubuntu 14.04 with mono 3.2.8.
