### ISSUE TITLE
Warning when ammending a commit

### ISSUE THREAD

**Issue by pvginkel** [gitextensions/gitextensions#1732]
When I amend a commit I get a warning about published commits. This warning should not be shown when I haven't published the commit yet.

**Comment by RussKie** [comment]
Is this still an issue with the current version?

**Comment by karyon** [comment]
with 2.50.01, yes.

**Comment by RussKie** [comment]
Can you please provide more info and steps to reproduce.
Screenshots will also help.
Thanks

**Comment by karyon** [comment]
well, you commit something, don't push it, then you open the commit dialog again, stage some changes, check the "amend commit" checkbox, and press the commit button. then the warning shows up although it doesn't need to since the first commit wasn't pushed.

**Comment by vbjay** [comment]
The issue is determining if the amended commit would overwrite ANY pushed
commit. Say you have 3 remotes. The problem is the way git branches. It's
just a pointer to a commit. You could reset the branch to another commit
and then run amnend.  There really isn't a good test for was this commit
pushed. We know what branches would contain it.

**Comment by pvginkel** [comment]
The problem I think it's that the message is pretty intrusive and since it
appears every time, it gets ignored. If you could find a way to only show
it when it's actually applicable, it would cut down own false positives.

However, an alternative approach could be to change the warning. What if
you check the amend box, a yellow bar appears above the commit message with
the text of the message box. That way it's directly apparent you see the
thing because you checked the amend button, and you don't get the pop-up
anymore. Something like this:
http://udine3d.uniud.it/venzone/images/iemsg.gif.
