### ISSUE TITLE
BitBucket.org support

### ISSUE THREAD

**Issue by phileo** [gitextensions/gitextensions#1733]
I've started using bitbucket.org to host some of my git projects.
It would be very nice for GitExtensions to support bitbucket hosted repos in a similar manner to how it currently supports GitHub
https://confluence.atlassian.com/display/BITBUCKET/OAuth+on+Bitbucket

![bitbucket_OAuth_diagram](https://f.cloud.github.com/assets/484797/282123/cdd57e26-9188-11e2-967d-7219b0911907.png)

**Comment by odie2** [comment]
Hey, any news?
I would be nice to have BitBucket support as plugin.

**Comment by vbjay** [comment]
What support do you want?  If it is repo support, it is already there.
Just use the repo url.  If you are talking about issues and such then write
a detailed issue that describes what support you want.

**Comment by odie2** [comment]
Like GitHub, on BitBucket are my repositories and additionaly team repositories.
Also there are Pull requests.

However maybe it's not enought.

**Comment by Copro** [comment]
It is an older request but Atlassian Stash was renamed to Bitbucket. There is a Plugin for Stash / Bitbucket Pull Requests in 2.48.05 named "Create Stash Pull Request".
Parameters are:
- Stash Username
- Stash Password
- Specify the base URL to Stash
- Disable SSL verificatiobn [ ]

This should be changed to now support Bitbucket.

**Comment by RussKie** [comment]
Fixed in #3526
