### ISSUE TITLE
Red windows 7 taskbar bar icon

### ISSUE THREAD

**Issue by phillijw** [gitextensions/gitextensions#1735]
It seems that occasionally the status bar icon will turn red and stay that way. In this particular instance, it happened after I aborted a pull.

I aborted the pull because gitext wouldn't finish the pull for some reason (I don't have any hooks set up).

After this happened, the taskbar icon stayed red until I restarted the app.

**Comment by RussKie** [comment]
Closing due to the age.
Please re-open if this still is an issue with the current version
