### ISSUE TITLE
Add option for repository browser to show all commits like 'gitk --all'

### ISSUE THREAD

**Issue by Mellbourn** [gitextensions/gitextensions#1737]
The repository browser in Git Extensions lacks the functionality to display all commits, like "gitk --all" can. In particular commits that are not even reachable by any branch or tag. 

Seeing those commits would help in understanding the actual workings of commands like rebase, reset and "commit --amend". It would also make it easier to reverse such actions (by easily allowing the user to reset to otherwise unreachable commits).

See http://stackoverflow.com/questions/15590226/how-to-make-git-extensions-browser-show-all-commits-like-gitk-all

![gitk --all](https://f.cloud.github.com/assets/1785727/295143/b1edcd74-945a-11e2-872c-185233ad07f5.PNG)

**Comment by KindDragon** [comment]
It requires the showing of unreachable commits from `git fsck --unreachable`

**Comment by Radrik5** [comment]
You can type `--reflog` in the Branches filter and get what you want (almost).

**Comment by Radrik5** [comment]
There are some technical limitations for displaying reflog references in the commit graph: https://github.com/gitextensions/gitextensions/issues/2303#issuecomment-97492934

**Comment by drewnoakes** [comment]
`gitk --all` doesn't show unreachable commits in my experience. However if you move branches about and press <kbd>F5</kbd>, gitk keeps any commits that were reachable before pressing <kbd>F5</kbd> in the graph. You can press <kbd>Shift</kbd>+<kbd>F5</kbd> to force a full refresh to show only reachable commits again.

GE has this option:

![image](https://user-images.githubusercontent.com/350947/43459320-105e2d7a-94c5-11e8-930c-72cfb12b87ef.png)

Which shows commits from the reflog in the graph.
