### ISSUE TITLE
Reduce number of parameters in GitModule methods

### ISSUE THREAD

**Issue by KindDragon** [gitextensions/gitextensions#1748]
Discussion how to do that http://stackoverflow.com/questions/6239373/how-to-avoid-too-many-parameters-problem-in-api-design

**Comment by RussKie** [comment]
GitModule specifically and the whole codebase in general... 
Mark Seemann summed it nicely - https://stackoverflow.com/a/6239493

This is also somewhat related to our discussions at https://github.com/gitextensions/gitextensions/pull/3898
