### ISSUE TITLE
Fails to checkout url "ssh://user@server:port/path"

### ISSUE THREAD

**Issue by Vyga** [gitextensions/gitextensions#1775]
Git Extensions 2.44. When using putty generated ssh key with the URL "ssh://user@server:port/path" it fails to checkout repository. When PLink command window is shown after an error the following lines are written:

Using username "ssh://user".
ssh://user@server's password:

It seems that it is using "ssh://user" as username instead of only the "user" part. 

When using shell generated ssh key and running manualy "git clone ssh://user@server:port/path" everything works as expected.

**Comment by benjumanji** [comment]
Just wanted to chime in with the fact that I have users of my phabricator install running into exactly this issue. Everything but clone works.

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/releases

**Comment by benjumanji** [comment]
Win 7 / GitExt 2.48.05 / Git 1.9.7
