### ISSUE TITLE
Make "OK" to auto focus button for "Reset current branch" dialog

### ISSUE THREAD

**Issue by FichteFoll** [gitextensions/gitextensions#1831]
I often find myself pressing enter instead of searching with my mouse pointer for the OK button in the "Reset current branch" dialog but the dialog won't close because the button is probably not the auto focus button (or however that worked again). While I want to be able to switch the radio buttons with the arrow keys I also want to be able to confirm the dialog immediately which is not possible at the moment.

I think that this is doable (with Windows) but I might be wrong because that was a long time ago.

**Comment by RussKie** [comment]
Closing as it is not longer an issue in the current version.
