### ISSUE TITLE
Crash when lunched from ObjectBrowser (Visual Studio plugin)

### ISSUE THREAD

**Issue by 0xddr** [gitextensions/gitextensions#1834]
--- GitExtensions2.44, 1.8.1.msysgit.1, Microsoft Windows NT 6.1.7601 Service Pack 1

I use GitExtensions's plugin with VS 2012. 
I have an opened project. When I try to launch it (button "Browse repository"  from plugin's toolbar), when "Object Browser" was an active tab it crashes. It's deterministic.

**Comment by RussKie** [comment]
Closing due to the age.
Please re-open if this still is an issue with the current version
