### ISSUE TITLE
push to seperate url bug: url is replaced by newly typed url in other combobox

### ISSUE THREAD

**Issue by RoSchvisual4** [gitextensions/gitextensions#1835]
I am using Windows 8. If checking push to seperate url in "manage remote" a second combobox is shown. So far, so good.

But, when typing in a new url in this second combobox,  both comboboxes show same value after clicking, pressing return or loosing focus.

For example:
Combobox1: http://192.168.0.1/Repo1
Combobox2: http://192.168.0.1/Repo1_Mine

Now press return, click away or tab.

Result:
Combobox1: http://192.168.0.1/Repo1_Mine
Combobox2: http://192.168.0.1/Repo1_Mine

If you press save now, push to seperate url is unchecked (because both urls are identical now)

**Comment by RussKie** [comment]
Fixed in 613335552bf0735080e442629da1b71b99551d53
