### ISSUE TITLE
"Open with difftool" does nothing if there are no changes

### ISSUE THREAD

**Issue by vitalybe** [gitextensions/gitextensions#1842]
When I press "Open with difftool" it usually opens my diff client.
However, if there are no changes, then nothing happens. I just keep waiting.

I understand that it stems from the behavior of `git difftool` command, however, it would be nice to have SOME feedback from the GUI since right now the user just has no idea what happened.

**Comment by mstv** [comment]
Unfortunately, the `git difftool` command does not return anything, neither console output nor exit code.
The only difference I noticed is that it does not return until the external difftool is closed.
I.e. we could display a message if the command returns quickly. Though this depends on the PC.
Possible actions:
1. MessageBox which must be closed manually.
2. MessageBox which closes automatically after how many? seconds
3. Overlay window similar to a tooltip which will be hidden after how many? seconds
4. Query whether to edit the working file or to compare it with the first or the selected version of the selected commit

Thoughts?

**Comment by gerhardol** [comment]
Some status message to indicate that difftool is opened?

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
