### ISSUE TITLE
allow multi-select in resolve conflict window

### ISSUE THREAD

**Issue by boxerab** [gitextensions/gitextensions#1845]
It would be nice to select many entries, and click "use local(ours)" for all of these entries.
This would be useful for large merges.

**Comment by webmaster33** [comment]
+1
I also agree to allow multi-select in resolve conflict window.

Please consider implementing it ASAP.

**Comment by rasane** [comment]
I am not certain if this feature-request got any further traction. I created an update here: https://github.com/rasane/gitextensions/tree/multi-select_in_resolve_conflict_window.. Please let me know if there is interest. Should I create a pull request?

(This is a first time, so I read your documentation https://github.com/gitextensions/gitextensions/blob/master/CONTRIBUTING.md, Please let me know if you need me to do anything else.)

Thanks, rasane

**Comment by KindDragon** [comment]
@rasane Hi. You should also show progress when resolving conflicts for multiple files.

**Comment by rasane** [comment]
FYI, referencing the pull request for interested parties to review https://github.com/gitextensions/gitextensions/pull/2832
