### ISSUE TITLE
stuck to fork when cloning a project with submodules

### ISSUE THREAD

**Issue by jinserk** [gitextensions/gitextensions#1855]
Hello,

I've used GitExtensions for a long time, but recently I use submodule features of Git.
However, when I clone the project with any submodules, GitExtension sometimes is stuck to fork new sh or git to clone the submodules after the main project cloned.

I don't know exactly this issue is the problem of GitExtension itself, or the problem of msysGit.

Please check this. Thank you.

**Comment by RussKie** [comment]
You can always open submodules form (_Repository > Submodules..._) and update them from there.
