### ISSUE TITLE
Optionally show number of submodules in toolbar

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1857]
similar to the "saved stashes" or "Commit" button:

![2013-05-20_14-50-27_gitextensions master - git extensions -_ debug _-](https://f.cloud.github.com/assets/368412/535581/e79c0d00-c14b-11e2-91d1-0bff8ba4dcef.jpg)

**Comment by markashleybell** [comment]
I'll take this one, if no one else is working on it?

**Comment by RussKie** [comment]
Go for it. Thanks

**Comment by gerhardol** [comment]
I do not see a reason to see this static information. @markashleybell can you motivate?

**Comment by RussKie** [comment]
The onus is on us to explain why we have this ticket open.
If there is a (collective) feeling this FR is not really useful, then we
should close it.

**Comment by markashleybell** [comment]
Yeah, I'm just picking small things up to try and get used to the codebase; I assumed that if an issue exists then it's already been discussed. Anyway, please let me know if this should be done or not, before I dive into the horrors of the form designer... 😨

**Comment by RussKie** [comment]
@feinstaub could you please explain why this feature may be useful. Thank you

**Comment by feinstaub** [comment]
The motivation was to make it obvious if the repository uses submodules or not. I am currently not sure if the button is visible at all or disabled if there are 0 submodules. The number of submodules represents a kind of dependency aspect of the repo has got, it can vary from commit to commit and therefore can be useful for people who only occasionally work on the repository.
Adding an option for this (default would be 'on') is a nice to have feature for people new to git. Nothing mission critical.

**Comment by RussKie** [comment]
If you open the dropdown you can see all submodules a given repository has
![image](https://user-images.githubusercontent.com/4403806/46408957-37f9cc80-c757-11e8-9289-11a8276a9081.png)

The button is always visible; and shows no submodules, if they are absent:
![image](https://user-images.githubusercontent.com/4403806/46409102-a63e8f00-c757-11e8-8cc1-d5ab68465e4d.png)

**Comment by RussKie** [comment]
At this stage, we will not be implementing this feature, sorry.

**Comment by gerhardol** [comment]
> The motivation was to make it obvious if the repository uses submodules or not. I am currently not sure if the button is visible at all or disabled if there are 0 submodules. The number of submodules represents a kind of dependency aspect of the repo has got, it can vary from commit to commit and therefore can be useful for people who only occasionally work on the repository.
Adding an option for this (default would be 'on') is a nice to have feature for people new to git. Nothing mission critical.

A related suggestion in #5451, the icon could be changed if there are no submodules at all.
Git is not handling removing submodules well, so for instance switching between two branches with different submodules will show removed submodules as worktree files.
