### ISSUE TITLE
Repair/reinstall does not restore github-windows protocol registration

### ISSUE THREAD

**Issue by jsahol** [gitextensions/gitextensions#1862]
Initially installed GitExtensions 2.44, and checked both of the options to handle git: and github-windows: URLs, and it was working. 

Installed, then removed GitHub for Windows, which registered itself for the same protocols. After removing GitHub for Windows and doing a "repair" installation on gitextensions, the git: protocol setting was correct, but now the github-windows: setting was missing the "command" key (HKEY_CLASSES_ROOT\github-windows\shell\open\command).

**Comment by leewisestamp** [comment]
To resolve this on Windows 7, I uninstalled GitHub, removed any "github-windows" keys from the Windows Registry, and removed any Application Data from any "C:\Users\<username>\AppData" subdirectory called "GitHub". I then reinstalled "GitHub for Windows" as normal and the github-windows protocol was successfully registered.

**Comment by MCMainiac** [comment]
I tried this on windows 8.1 but it didn't help.When I click on "Open this file on Windows GitHub", windows tells, that there are no apps installed that open github-windows (the only option I have is to search one in the windows store).
