### ISSUE TITLE
Bug: Main form: Branches-Combobox closes automatically on opening

### ISSUE THREAD

**Issue by shivan** [gitextensions/gitextensions#1891]
**Current behaviour:**
The combobox to select the branches closes automatically.

![image](https://f.cloud.github.com/assets/1827692/610098/c6c062ac-cda8-11e2-8cb9-aa7cb8194d9b.png)

**Expected behaviour:**
Combobox should not automatically close when opening.

**Details:**
Problem exists only, when "Remote" is checked in the settings behind the combobox:
![image](https://f.cloud.github.com/assets/1827692/610106/fd073318-cda8-11e2-9151-934f57546186.png)

Can always be reproduced in V2.44

**Comment by RussKie** [comment]
I can't reproduce it in the latest version.
