### ISSUE TITLE
Disable unsupported commands for bare repositories

### ISSUE THREAD

**Issue by KindDragon** [gitextensions/gitextensions#1896]
- [x] Submodules
- [x] Edit ...
- [x] Commit
- [ ] Git Pull (only fetch work)
- [x] Git Pull auto stash
- [x] Git Push - remove message "The branch you are about to push..." and "The branch does not have a tracking reverence..."
- [x] Auto Pull on reject
- [x] Stash
- [x] Reset changes
- [x] Clean working tree
- [ ] Checkbox "Checkout after create" in Create branch
- [ ] Checkbox "Create orphan" in Create branch
- [x] Checkout branch
- [x] Merge branches
- [x] Rebase
- [x] Resolve merge conflicts
- [x] Cherry pick commit
- [x] Checkout revision
- [x] Bisect
- [x] Apply patch
- [x] Svn rebase
- [x] Svn DCommit
- [ ] Disable "Create local tracking branches" plugin
- [ ] Disable gource plugin
- [x] Git GUI
- [ ] Edit working dir file, Open this revision and Open containing folder
- [ ] Open with diff tool ... <---> working dir, Reset files to
- [x] No branch highlighted in revision grid

**Comment by RussKie** [comment]
Do ticks mean those commands are taken care of?

**Comment by KindDragon** [comment]
Yes

**Comment by gerhardol** [comment]
Most remaining issues were addressed in 2.51, a few more tweaks in 3.00 branch
