### ISSUE TITLE
Commit dialog steals focus

### ISSUE THREAD

**Issue by pvginkel** [gitextensions/gitextensions#1899]
Sometimes, it takes some time for the file list (upper left list view) in the commit dialog to load (e.g. when the Git repository is on a network share). When the file list finishes loading, focus is set to the file list. This is very irritating when I'm entering a commit message while the file list is loaded.

Is it possible to prevent the file list from stealing focus away from the commit message text box when it finishes loading?

**Comment by vbjay** [comment]
It's better to have a local repo and push to the remote repo using a remote.

**Comment by Piedone** [comment]
@jbialobr I'm not sure if this is exactly the same thing that you fixed but this still happens:

1. Start a commit.
2. Go to a different app's window.
3. Once the commit finishes and the history window loads the focus is stolen by it, i.e. you jump back from the other app, there is no way to let the commit finish in the background.

If you commit and push then the focus will get stolen once the push dialog opens.

**Comment by gerhardol** [comment]
All known situations where focus is incorrectly handled is related to ConEmu.
Tracked by a milestone (should probably be a label).
https://github.com/gitextensions/gitextensions/milestone/27

Disable ConEmu and the embedded console. if not resolved open a new issue.

**Comment by Piedone** [comment]
Fantastic, disabling ConEmu fixes this! I'll watch the other issues.
