### ISSUE TITLE
Hotkeys: customize "open with difftool" F3

### ISSUE THREAD

**Issue by RSly** [gitextensions/gitextensions#1903]
I cant find how to change the F3 key (open with difftool) to a new key (example Ctrl+D). 

Can you add this feature in Hotkeys please? 

thanks

**Comment by iNineTailedFox** [comment]
I would like this too, and if even possible when this is getting done, please allow mouse clicks as a hotkey too so I can assign double left mouse click as a hotkey.

**Comment by mstv** [comment]
Most of the hotkeys including the one for `Open with difftool` can be changed in the settings dialog in the meantime.

> please allow mouse clicks as a hotkey so I can assign double left mouse click as a hotkey

Double clicks are handled differently. Where do you want to double click to open the difftool, @iNineTailedFox? I guess in the FileStatusList. Currently double clicking there opens the FormFileHistory. This function has an hotkey, too. I want to be able to use both. Though assigning two hotkeys, I mean real keys, to the same function does not make much sense to me. The more generic approach would be to choose which hotkey-assignable function shall be triggered by a double click.
I think this would still be overkill for most of the hotkey domains, i.e. it would be enough to have a single setting for the double click behavior in the FileStatusList.

I suggest to close this feature request and to open a new one more elaborated for the double click.

**Comment by GintasS** [comment]
This was fixed, you can change the hotkey in settings.
