### ISSUE TITLE
Diff viewer does not work properly with Macintosh line endings

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1905]
With current and dev GitExt version the built-in Diff viewer does not properly show diffs with Mac line endings:

![2013-06-12_22-53-33_d__data2_projects_gitextensions_gitui_commandsdialogs_settingsdialog_pages_revis](https://f.cloud.github.com/assets/368412/645341/47fca0ac-d3a2-11e2-8bac-72d40a189e95.jpg)

KDiff3:
![2013-06-12_22-57-46_commit to gitextensions_jb_revisionlinks 1582_2 d__data2_projects_gitextensions](https://f.cloud.github.com/assets/368412/645364/c7e9e662-d3a2-11e2-812f-b72bdc03d79a.jpg)

GitExt:
![2013-06-12_22-58-22_commit to gitextensions_jb_revisionlinks 1582_2 d__data2_projects_gitextensions](https://f.cloud.github.com/assets/368412/645369/df8e2dd2-d3a2-11e2-854b-01f653fd956c.jpg)

I don't need the MAC line endings (thanks to this GitExt bug I saw that some files in my project had wrong line endings). So lowest prio for me.

**Comment by GrahamTheCoder** [comment]
I just wasted a couple of hours confused by line endings and this bug. If Git Extensions made me aware of mixed line endings actively it'd be great. But at minimum, highlighting lines which have changed in a diff (even if they come after a CR) seems like a good idea.
