### ISSUE TITLE
(Option to) show committer in the revision grid

### ISSUE THREAD

**Issue by AndreKR** [gitextensions/gitextensions#1926]
Apparently since 1.89 gitextensions shows the committer **in the commit tab** when they differ. There is also an option to show the commit **date** in the revision grid.

However, there is neither an option to show the committer in the revision grid, nor is it shown automatically when it differs.

**Comment by RussKie** [comment]
Is this still relevant?

**Comment by AndreKR** [comment]
Yes, you can still only switch off "Show author date", which then shows the Author's name but the Committer's date. There doesn't seem to b a way to show the Committer's name or even both at the same time when they differ.

**Comment by RussKie** [comment]
The revision graph can display only so much of information. Extended information is displayed on the Commit tab. 
What is the use case to show the committer?

**Comment by AndreKR** [comment]
Well, it's not a deal breaker, but TortoiseGit does it and I do use it from time to time.

![image](https://user-images.githubusercontent.com/1188538/29937429-d01e8c6e-8e85-11e7-848f-cb3f49337dd9.png)

There are two typical use cases:
- Who was the last person to rebase this branch?
- Production is broken, who put this commit in the deployment branch (and when)? Even if they cherry-picked it.

**Comment by RussKie** [comment]
Can you not get this info from the commit info tab?

Either way, you're welcome to submit a PR for this feature.

**Comment by RussKie** [comment]
/cc: @drewnoakes I think this is being addressed by your grid uplift
