### ISSUE TITLE
Commit tab: show more information for parent and child commits

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1929]
When there are several children and the graph is rather complex like in the following screenshot...

![2013-06-24_21-06-52_gitextensions z_vbjay_commituser - git extensions -_ debug _-](https://f.cloud.github.com/assets/368412/697489/5feb2c98-dd01-11e2-81ab-abbb740f6f2e.jpg)

...it would be nice if there were more information to be seen for each link except for the commit hash. For example relative date, author, part of commit message etc.

**Comment by drewnoakes** [comment]
Would be good to see a mock-up of how this might look.

The whole commit info area could do with an overhaul at some point.

**Comment by RussKie** [comment]
In the following release 😏

**Comment by GintasS** [comment]
@RussKie what is the status on this, maybe we can close it?
