### ISSUE TITLE
Move stash button more to the right?

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1931]
Suggest to move the stash button next to the Pull button in the main toolbar because:

1) see screenshots:
![2013-06-24_23-14-46_rc topic_convert_office_file - git extensions -_ debug _-](https://f.cloud.github.com/assets/368412/698341/f66f178a-dd13-11e2-895e-03a9e9423c58.jpg)

![2013-06-24_23-15-13_rc topic_convert_office_file - git extensions -_ debug _-](https://f.cloud.github.com/assets/368412/698343/0852e6fc-dd14-11e2-9530-ba40f2daca66.jpg)

2) the suggested order would be consistent with the order in the Commands menu

**Comment by drewnoakes** [comment]
I don't see "0 saved stashes" or similar text any more. Has that feature been removed, or is it optional? If it's gone, is this issue still valid?

**Comment by RussKie** [comment]
I believe it is
![image](https://user-images.githubusercontent.com/4403806/43458725-9f7bc550-950e-11e8-8285-a6c033b37f94.png)

I don't use stash at all so I have that setting off...

**Comment by RussKie** [comment]
We have the same issue (or feature) with the commit button, please see #3550

**Comment by gerhardol** [comment]
Move commit too if changed:
pull/push - Commit - Stash

**Comment by gerhardol** [comment]
Changed in #5351
