### ISSUE TITLE
Arrow keys in Resolve Merge Conflicts window don't work as expected

### ISSUE THREAD

**Issue by mouseas** [gitextensions/gitextensions#1933]
Expected behavior:
The up arrow should select the previous file, and the down arrow should select the next file.

Actual behavior:
If the user actually clicked on a file in the list, and then uses the arrow keys, they function as expected. But if the focus is not already in the file list, the up arrow key does nothing, and the down arrow key selects the second item in the list (as if going down from the first item) and gives the focus to the file select list.

Steps to reproduce:
(1) Merge two branches with several conflicts (10+ makes this easy to test)
(2) right-click an item in the middle of the list and choose "Choose local (ours)" from the context menu.
(3) press the up arrow key to select the previous file. Nothing happens.
(4) press the down arrow key to select the next file. The 2nd file in the list is selected, and afterwards the arrow keys function as one would expect.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
