### ISSUE TITLE
git svn geotrust certificate problem

### ISSUE THREAD

**Issue by holinov** [gitextensions/gitextensions#1936]
I have svn repository on https singned with GeoTrust issued certificate.
Every time i try to access tis repository i have message :

Error validating server certificate for 'https://svn.egspace.ru:443':
- The certificate is not issued by a trusted authority. Use the
  fingerprint to validate the certificate manually!
  Certificate information:
- Hostname: *.egspace.ru
- Valid: from Apr 28 01:38:17 2013 GMT until Apr 30 12:00:40 2014 GMT
- Issuer: GeoTrust, Inc., US
- Fingerprint: b2:8d:f8:3b:7c:d2:a2:36:e2:1d:c3:5c:56:ec:87:6f:22:3e:4b:a8
  Certificate problem.
  (R)eject, accept (t)emporarily or accept (p)ermanently?

Even if i choose permanently every next attempt to acces in i have same issue. But if i use TortoiseSVN i have no problem with checking that cert.

P.S.: Im using Windows 8 x64.

**Comment by RussKie** [comment]
Closing due to age
