### ISSUE TITLE
Auto Fast Forward 

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#1937]
http://stackoverflow.com/questions/620650/can-i-easily-update-all-local-git-branches-from-remote-branches-simultaneously

Using something like this or other technique, it would be nice to have a way to select a remote and not only create any non tracked branches but merge from the selected remote any branches that can be fast forwarded. After it did that show the status of each branch and whether it was fast forwarded or not.

Along with that idea, have some simple toast or other status show when the user switches to another branch of where the current head is compared to all the remotes and to show the order(which remote or local has the latest commit).  Have a quick way to merge to that commit.

**Comment by RussKie** [comment]
Closing due to age.
If someone really wanted it we would probably see a PR by now. And this can be achieved via scripts.
