### ISSUE TITLE
Git Extensions has started crashing on start-up - Windows 7 Professional

### ISSUE THREAD

**Issue by turtletennis** [gitextensions/gitextensions#1949]
Last Thursday I went from a Windows server 2008 OS on an HDD to a Windows 7 OS on the same machine on an SSD. I had installed Git Extensions on Server 2008 about a year ago or so, never had any problems. I installed Git Extensions 246 on Windows 7 between last Thursday and yesterday, it was working fine. 

Today when I tried to commit using the Explorer GitEx Commit entry in the right-click menu I got the standard "GitExtensions has stopped working" Windows error message and GitExtensions did not start. Running GitExtensions from the start menu has the same effect. I've tried repairing the installation, uninstalling and reinstalling, restarting my machine, all to no avail. Unsurprisingly, all of the right-click GitExtensions options do the same thing, crash on start-up.

I'm happy to give any more information if required.

**Comment by joelthedrummer** [comment]
This might help someone having this issue, so I'll post the solution I found here.

There were two (probably malware of some kind) programs installed called "AnySend" and "moters."  Once I uninstalled these using the Programs and Features control panel, this error went away for the person I was helping that received this error message (albeit in a different .NET application).
