### ISSUE TITLE
Error fetching remote branch list before clone the first time connecting to host

### ISSUE THREAD

**Issue by szantnerb** [gitextensions/gitextensions#1954]
I am trying to clone a repository from a server (via SSH) to which my computer has never connected before. (The server's fingerprints are not cached)

The Clone window does not present me a dialog where I could confirm the remote computer's identity (as e.g. putty shows a dialog in this case).

Instead it will populate the branches dropdown with jibberish, as seen on the picture attached:
![ge_clone](https://f.cloud.github.com/assets/2652078/751481/c1bc610a-e4fc-11e2-8fc4-ad4cb9e506b5.png)

The actual string returned by the git command trying to populate the dropdown is:

"The server's host key is not cached in the registry. You
have no guarantee that the server is the computer you
think it is.
The server's rsa2 key fingerprint is:
&lt;fingerprint removed&gt;
Connection abandoned.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

Note: GE is set up to use putty as SSH client. If I make a connection to the host manually via putty and let it cache the server's fingerprint, the Clone window is able to fetch the remote branches.

**Comment by GintasS** [comment]
Abandoning this because of age.
