### ISSUE TITLE
Save file from tree crashes git extensions

### ISSUE THREAD

**Issue by SamTShaw** [gitextensions/gitextensions#1961]
Not sure if this one is Linux specific.

When saving a file from the file tree, it crashes with this error:
System.NullReferenceException: Object reference not set to an instance of an object
  at GitCommands.GitModule.SaveBlobAs (System.String saveAs, System.String blob) [0x00000] in <filename unknown>:0

Full stack trace, https://gist.github.com/Moustacha/5989003

Git Extensions 2.4.3
Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-1ubuntu2.2)
Ubuntu 12.04.2

**Comment by RussKie** [comment]
Is this still a problem with the current version?

**Comment by SamTShaw** [comment]
It's fixed in 2.50.01
