### ISSUE TITLE
Goto commit feature: "hash1;hash2" selects two commits to view diff

### ISSUE THREAD

**Issue by feinstaub** [gitextensions/gitextensions#1966]
What do you think about implementing the possibility for the Goto Commit dialog to be able to specify two commits in the commit expression box?

![2013-07-16_22-00-58_go to commit](https://f.cloud.github.com/assets/368412/807676/7562dfdc-ee52-11e2-8c2d-4449aa65f613.jpg)

Would semicolon (;) be a good separator? Or better space or two dots (..)?

Clicking the Go button would select the two commits in the given order and the user would see the diff. (I experimented a bit with the current revision grid but I was not able to select two commits programmatically).

The complementary feature to the one described above would be:
If two commits are selected in the revision grid then Ctrl+C copies "commithash1;commithash2" to the clipboard for later use. Especially when dealing with diffs across many commits this would be helpful to quickly restore the diff after investigating some other commits.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
