### ISSUE TITLE
Inconsistent State of VS Solution File and Contained Projects 

### ISSUE THREAD

**Issue by gravidThoughts** [gitextensions/gitextensions#1977]
Hi,

This is a logical bug I encountered right after installing the VS 2010 plugin. 

Created new solution with a WinForm project. Immediately added a class library project and added several files and did a little coding. 

I did not save solution, committed all to the main branch, and created a new branch. Later when checking out main branch and reloading the solution, the class library was missing (because it had not been persisted to solution file when commit occured).

I can just re add the already existing project, save, and it behaves as expected with the only changes revealed by a git status in bash are to the csproj and solution files.

Just thought I would let you know.  Not a huge deal, but could really confuse less experienced developers.

Thanks for the great work!

**Comment by RussKie** [comment]
It is VS issue, not GE.
