### ISSUE TITLE
Add a checkbox to enable the --no-verify flag on commit

### ISSUE THREAD

**Issue by Zoubi** [gitextensions/gitextensions#1982]
It is sometimes useful to bypass the hooks on commit

**Comment by arenaq** [comment]
+1

**Comment by weslley39** [comment]
+1

**Comment by pmiossec** [comment]
@weslley39 Gitextensions has this feature since years. Look at the menu just on the top right of the commit message textarea in the commit form.

**Comment by raghav-khunger** [comment]
This is where "No Verify" option can be found:
![image](https://user-images.githubusercontent.com/904902/104830200-707b3100-58a2-11eb-84f5-162eb19aee94.png)
