### ISSUE TITLE
Cant launch open with difftool from git extentions after some time.

### ISSUE THREAD

**Issue by rluiten** [gitextensions/gitextensions#1983]
This has been happening for many weeks if not months.
I can remember installing the most recent update hoping it would be fixed.

After some time, I havn't made progress figuring out what it is, after a few hours it seems F3, or right click 'open with difftool' no longer launches kdiff3.
I cant find any errors.
A system reboot fixes it.
My diff tool is kdiff3, and it works fine stand alone and with right click compare in windows explorer menu.

OTE: this is recent no more than 3-4 months ish....
I am on windows 7 64bit with up to date windows patches.
Using git extensions primarily stand alone launched from explorer or start menu.
Quitting everything on desktop and starting them again doesn't fix it.

I am happy enough to do some exploring to help figure it out, but have no idea where to start at the moment.

**Comment by RussKie** [comment]
Closing due to the age.
Please re-open if this still is an issue with the current version
