### ISSUE TITLE
Access to .gitconfig is denied

### ISSUE THREAD

**Issue by evanlarsen** [gitextensions/gitextensions#1984]
--- GitExtensions2.46, 1.8.3.msysgit.0, Microsoft Windows NT 5.1.2600 Service Pack 3

Hello,

My %HOMEDRIVE%%HOMEPATH% is set to a network drive which I do not have write access too.  The above environment variables are set in my coporations AD settings and I have no way of changing them.  

Because of this. GitExtensions does not work for me because when I want to set the settings it just throws the above error.

Are there any work arounds to changing where the .gitconfig settings are saved?

**Comment by RussKie** [comment]
In the current version you can set new home location
![image](https://user-images.githubusercontent.com/4403806/34453900-ca4a2456-edb2-11e7-8cbe-f0bff2225194.png)
