### ISSUE TITLE
Duplicate context menu items for shared folder

### ISSUE THREAD

**Issue by brunom** [gitextensions/gitextensions#1987]
- Go to \\localhost\Users with File Explorer
- Right click Users
- The GitEx optiones are shown twice, as in the image

![menu](https://f.cloud.github.com/assets/299372/878580/fe48b186-f916-11e2-9527-d8ddd94dcef4.png)

**Comment by mat-m** [comment]
Same issue here with GitExt 2.49.
I have a local E: drive with a viewable share (with no $ at the end). ON this drive and all its folders, I have two GitExtensions entries.
My C: drive and my mounted drives do not have this issue.
