### ISSUE TITLE
Mark ill formed lines has non-adjustable hard coded length

### ISSUE THREAD

**Issue by netddd** [gitextensions/gitextensions#1995]
It would be nice if the "Mark ill formed lines" in the commit dialog had an adjustable length limit.  It is currently hard coded to 72.  A forced value of 72 is very short, especially with the majority of screens being wide screens and higher res ones at that.  

The template has separate limits for first line and following lines.  It would be good to have settings for those values as well for this feature.  One cannot simply use a template in the case of amending a message.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.

**Comment by RussKie** [comment]
I thought we had a PR that was meant to address this... Maybe it was
abandoned by it's author?

**Comment by GintasS** [comment]
I guess this one is wrong? #5037
