### ISSUE TITLE
Won't Open in Windows 8.1

### ISSUE THREAD

**Issue by adamhewitt627** [gitextensions/gitextensions#2006]
It was working fine until yesterday, but 2.46 suddenly won't open in the Windows 8.1 Preview. (I realize I deserve any problems with preview software, but it seemed odd to suddenly not open without system changes.)

I tried reinstalling both 2.43 and 2.44 (they were successful) but it once again broke after updating to 2.46. I'll be back on 2.44 for the time being I guess.

**Comment by plawley** [comment]
same issue

**Comment by whitewhim2718** [comment]
I am experiencing this issue as well.

**Comment by englishextra** [comment]
Same stuff / have to clone repos the same old way — via CMD.exe

**Comment by spockmonster** [comment]
This is happening on my Windows 8.1 Pro machine running Github for Windows version 2.13.2.4 .  It worked for an hour, but then stopped working completely.

**Comment by KindDragon** [comment]
Sorry, but `Github for Windows` is not our product

**Comment by bora47** [comment]
cant launch git bash on windows 8.1,shit wont work
