### ISSUE TITLE
Hard Reset does not remove newly-added files.

### ISSUE THREAD

**Issue by isaacabraham** [gitextensions/gitextensions#2017]
Using GitExtensions 2.46, if I create a new file in my repository and then try to reset to a specific revision using the "Reset current branch to here" context menu option, even if I select Hard reset, the newly-added file survives the operation i.e. I still have a single pending file to Commit. I'm sure that the behaviour was different on older versions of GE.

Conversely, if I use the Reset Changes option from the Commands menu, this does correctly remove the newly-added file.

**Comment by EbenZhang** [comment]
`git reset --hard SHA` won't delete the new files. 
The `Reset Changes option from the Commands menu` removes the new files and directories by
performing an extra step `git clean -df`.

May be we should add an option (checkbox) for HARD reset to delete files and directories?

**Comment by vbjay** [comment]
Clean should not be that easy to do.  You want the user to do it when they
mean to.

**Comment by saifurrehman065** [comment]
**jjjjjjjjjjj
**
