### ISSUE TITLE
Autolinks from commit hashes

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#2033]
Hi.
Is it harder to make a hyperlinks from commit hashes referenced at commit message?
It would be used to easy navigate between them.

--- GitExtensions2.46, 1.7.10.msysgit.1, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by pravic** [comment]
The main problem that in doesn't want to work with short hashes (10+ characters) :(

**Comment by osevoso** [comment]
Hello. 
Commit's hashes are highlighted at commit message as hyperlink, but jumping to revision by click was broken compared to the previous releases

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
@osevoso could you please raise a new issue for us to look at. Thank you
