### ISSUE TITLE
integration of labview merge tool

### ISSUE THREAD

**Issue by yuvaforlife** [gitextensions/gitextensions#2053]
I am using git extensions 2.44 and labview 2012.
I was able to successfully configure Labview Compare tool with git extensions.
I am having trouble merging labview merge tool with git extensions?
Any help is greatly appreciated.

**Comment by JonathanLindsey** [comment]
@yuvaforlife you might checkout https://bitbucket.org/JonathanLindsey/lv-merge-and-diff-wrapper/src/master/
It allows git to work with LabVIEW's merge and diff tools from the command line level. This means that GitExtensions will work with LabVIEW's merge and diff tools.

When doing merges, please be careful to use the button indicated below. The others don't work for some reason that I haven't figured out yet.
![Annotation 2020-09-16 020642](https://user-images.githubusercontent.com/18510187/93303857-b378ab00-f7c1-11ea-8452-83a1e90fbef9.png)

**Comment by gerhardol** [comment]
> When doing merges, please be careful to use the button indicated below. The others don't work for some reason that I haven't figured out yet.

GE requires both that cmd and path is set, as path is used in some manipulations.
(For Git built-in tools meone is needed, but it is hard to both have a good check and full freedom.)
