### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#2067]
I encounter random crashes [at this line](https://github.com/libgit2/libgit2sharp/blob/vNext/LibGit2Sharp/Core/Proxy.cs#L1992) - Access violation exception is thrown.

@nulltoken Is lg2s.Repository thread-safe by design? My first thought is it can be related to thread-safety since crashes occurs randomly and source of crashes is a call to index.RetrieveStatus() from a backgroud thread.

/cc @ethomson

**Comment by orao** [comment]
Is there any interest in restarting the LibGit2Sharp integration?

**Comment by jbialobr** [comment]
@orao Yes there is, but I think it should not be based on the LibGit2Sharp branch. The integration should be done from scratch. Though we can cherry pick some work from the LibGit2Sharp branch. Here are the reasons why I would start from scratch:
1. In the LibGit2Sharp branch the `LibGit2Sharp.Repository` was accessed crossthreaded, which should not be the case since the LibGit2Sharp.Repository is not a thread safe class. I think we should create a new Repository when needed and dispose it immediately after it becomes not needed. We should try to reuse a Repository instance only when we prove there exists a real performance issue related to that. 
2. I would start with one or two commands replaced with a LibGit2Sharp implementation and wait for a while to see how it works, what code patterns should we use, how LibGit2Sharp iteracts with CLI of git. The first candidate could be unstaging files - as it is very slow for a large number of files (see #3280). 
3. Reimplementing new commands into the LibGit2Sharp should be an opportunity to cover these commands by automated tests on both windows and linux.

Note: The LibGit2Sharp project should go under the Externals folder.

**Comment by Radrik5** [comment]
There is a performance issue in blame in libgit2: https://github.com/libgit2/libgit2/issues/3027. Maybe it's not the only performance issue, so I'd prefer to have an option: use LibGit2Sharp or use regular Git.

**Comment by orao** [comment]
@Radrik5 I would think that choosing one backend rather than increasing the costs of maintenance would be the preferred option. However, this is a decision for the core team _(which I'm not a part of)_. What would probably be a good compromise is to use LibGit2Sharp.Repository where it provides a performance improvement and use Git itself for the parts where it does not, which as you point out would be the blame functionality.

This lines up with point 2. from @jbialobr's comment above, but would mean we stop before full replacement.

I agree with @jbialobr's proposal and will keep you posted as to progress. Currently, I don't have the time but I expect that I might get an opportunity to do it over Xmas.

**Comment by nulltoken** [comment]
> LibGit2Sharp.Repository where it provides a performance improvement and use Git itself for the parts where it does not,

LiGit2Sharp doesn't directly or indirectly delegate to Git.

**Comment by nulltoken** [comment]
>> LibGit2Sharp.Repository where it provides a performance improvement and use Git itself for the parts where it does not,
>
> LiGit2Sharp doesn't directly or indirectly delegate to Git.

I may has misread this. If your intent was to have gitextensions interact with both LibGit2Sharp and Git, then sorry for the noise :wink:

**Comment by jbialobr** [comment]
> I would think that choosing one backend rather than increasing the costs of maintenance would be the preferred option.

Yes, that's right, and AFAIK LibGit2Sharp does not cover all the commands that GitExtensions uses.

**Comment by RussKie** [comment]
Is this still relevant?
