### ISSUE TITLE
Add support for replacement variables in the commit templates

### ISSUE THREAD

**Issue by pvginkel** [gitextensions/gitextensions#2069]
The way we work the name of the branch is always the same as the ticket we're working on. It would be very easy for us if we could put a replacement variable in the commit template that is replaced with the name of the current branch to generate the Bug: line. The template could e.g. look as follows:

```
Bug: {currentBranch}
```

**Comment by minidfx** [comment]
Nice feature, is there something in the current version?

**Comment by matkoch** [comment]
:+1:

**Comment by fschmied** [comment]
+1

**Comment by deltreey** [comment]
:+1:  I could definitely use this

**Comment by bensewellmojo** [comment]
👍  I'd like this too

**Comment by kh2net** [comment]
@pvginkel; i will dot it.
