### ISSUE TITLE
Title bar doesn't work when gitextensions is on the left monitor

### ISSUE THREAD

**Issue by killerkalamari** [gitextensions/gitextensions#2121]
Recently I reorganized my desk, and moved my 2nd monitor to the left, where it had previously been on the right. Now, when any of the gitextensions windows are windowed (not maximized), I cannot move them (it gives an "upper left to lower right" resizing arrow cursor) using the title bar (and also the title bar is compeltely unusable, I also can't close, maximize, minimize, etc. Dragging the other edges of the window allowing resizing, and for the most part gitextensions is usable (but many of the dialogs are a pain because I cannot easily close them once they have opened). I tried restarting the computer and it didn't help. Maybe there is simply a configuration file or registry entry I need to clean out, but I don't know how to configure gitextensions outside the gui. 

The only way I can affect the window in this mode is to right click and choose move, then click the window and move it. Or right click, maximize, close, etc.

When the program is moved to my other monitor, there is no problem. So my current workaround is just to keep it on the right side monitor.

**Comment by RussKie** [comment]
Is this still a problem with the current version?

**Comment by RussKie** [comment]
Closing due to age. Reopen if it is still an issue in the current version.
