### ISSUE TITLE
Simplify calling "Prune remote branches"

### ISSUE THREAD

**Issue by vishalgupta1988** [gitextensions/gitextensions#2141]
hi

Scenario--
I am having multiple remote personal branch which we use for personal backup but post our task finished we need to delete those personal branch but I am not able to delete those.

What I am doing?
I am using some commands to delete those branch
git push origin :refs/origin/personal/SSOID/branch_Name
git push --force origin :refs/origin/personal/SSOID/branch_Name1

What is happening?
The above command are showing success but when I check from another git instance those command are present means not deleted from remote.

**Comment by ChrisFindlay** [comment]
Related to this would be an easy means to set `--prune` during `git fetch`, e.g. for comparison, SourceTree's fetch dialog has a checkbox for it.  I find GitExtensions more efficient to use for almost everything, but `git fetch --prune` is one notable exception to that.
