### ISSUE TITLE
Confirmation when checking out another branch while having uncommitted changes

### ISSUE THREAD

**Issue by frank-freihube-rmcan-com** [gitextensions/gitextensions#2143]
--- GitExtensions2.47, Git 1.8.3.msysgit.0, Microsoft Windows NT 5.1.2600 Service Pack 3

This moment i deletet some changes because i wanted to check out the branch, and didn't recognice there are some changes. Also some time before i WANTED to reset the changes and Git Extensions saved my decission and just deletet the changes this time too. I would say eigther to not save the last decision and assume the user wants to "Don't change" anything or to add an dialog to ask for permission to reset. Also a notification when wanting to check out a branch with uncommitted changes would be fine. At the moment it just don't work and you have to find why by your own.

**Comment by RussKie** [comment]
The checkout dialog has a number of options
![image](https://user-images.githubusercontent.com/4403806/39366693-ff529b3e-4a77-11e8-9b7a-2c935294b07b.png)
