### ISSUE TITLE
Add to .gitignore for folders in context menu

### ISSUE THREAD

**Issue by nlacombe42** [gitextensions/gitextensions#2151]
I would love to have the option to add a folder recursively to .gitignore on the context menu.

**Comment by MrChriZ** [comment]
This item has been marked as complete - it maybe my ignorance  but I can't see this feature anywhere in the latest build?

**Comment by mstv** [comment]
It is not that difficult to remove the filename manually. The function can be found in the Commit window.

![image](https://github.com/gitextensions/gitextensions/assets/36601201/db29ab94-9c8d-42f1-a043-184f3419c470)   ![image](https://github.com/gitextensions/gitextensions/assets/36601201/af2f33ef-5c52-498b-a2fc-2a14d947f12e)
