### ISSUE TITLE
Tools/GitK menu item does nothing

### ISSUE THREAD

**Issue by petergolde** [gitextensions/gitextensions#2162]
--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.3.9600.0

Choosing "GitK" from the Tools menu appears to do nothing. 

If I do Git bash and then type "gitk" at the command line it does work, so gitk does seem to work on my machine, it just isn't started from the GitK menu item in Git Extensions.

**Comment by gerhardol** [comment]
Handled in #4510
