### ISSUE TITLE
Please remove or allow block 'stage and commit all unstaged files'.

### ISSUE THREAD

**Issue by ChameleonRed** [gitextensions/gitextensions#2164]
This feature leads to serious problems and unwanted commits please allow to block it or remove. 

There is very often that you have some files which you not want commit and which cannot be ignored. For example security files, database files, environment configurations.

**Comment by shachar-i** [comment]
+1 to explicitly requiring stage all be clicked and disabling auto-stage-all and commit behavior.
IMHO, a good UI does not cause such unintended consequences so often.

**Comment by RussKie** [comment]
It has been 4 years since the original request.
I side with @pmme - if it is committed you can reverse it. If you pushed it you can typically reverse it too (although it is a little bit harder). 
If you really want this change in - please send a PR.
