### ISSUE TITLE
Can not identificate ".scs"(C Sharp Script) file.

### ISSUE THREAD

**Issue by RoyburnsPeng** [gitextensions/gitextensions#2169]
--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

Can not identificate ".scs"(C Sharp Script) file.

**Comment by RussKie** [comment]
Closing as the issue makes no sense.
You're welcome to provide meaningful information to have it re-open.
