### ISSUE TITLE
git pull merge does rebase

### ISSUE THREAD

**Issue by kasal** [gitextensions/gitextensions#2173]
The "Pull" dialog allows user to switch whether merge or rebase is to be performed.
The latter calls pull with --rebase, the former without it.

In our workflow, the branch is set to rebase by default (branch.master.rebase=true), so even "git pull" ("merge" in the dialog) does rebase.  This is incorrect.
I believe this one should call --no-rebase.

Moreover, these should be some support for the mentioned setting.
Perhaps a third option should be added:
"Branch default (Merge or Rebase)"

Alternatively, the pre-selected variant should be set according to the value of branch.<branchname>.rebase

What do you think?

Stepan Kasal

**Comment by jbialobr** [comment]
I think that adding --no-rebase to the pull merge option is enough.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
