### ISSUE TITLE
Settings "SSH:OpenSSH" reset to "SSH:Other ssh client" after restart program

### ISSUE THREAD

**Issue by Belerafon** [gitextensions/gitextensions#2187]
I have install Git Extensions with "Putty" SSH connection. After this I go to OpenSSH metod and I have change radio button "Settings->SSH->Other ssh client" to "Settings->SSH->Open SSH". This is works but then I do restart Git Extensions this settings have reset back to "Settings->SSH->Other ssh client". I try to reinstall with "Open SSH" method selected in install dialog but after install has finished I have got "Settings->SSH->Other ssh client" too.

Windows 7 x64, gitextensions version 2.47.3

**Comment by benermafield** [comment]
This is also happening to me, i have putty setup on the machine, and pagent set up to startup on windows startup with a key, but i want GitExt to use OpenSSH, and every time I restart my machine it has reverted the SSH settings back to putty.

I have also removed the GIT_SSH environment variable and this hasn't resolved the issue.

**Comment by radieter** [comment]
removing GIT_SSH worked for me. thanks.
