### ISSUE TITLE
Expose the "repository excludes" file for configuration

### ISSUE THREAD

**Issue by sharwell** [gitextensions/gitextensions#2194]
It would be helpful if Git Extensions offered improved support for [`$GIT_DIR/info/exclude`](http://git-scm.com/docs/gitignore).
- [ ] Currently the Repository menu contains an option **Edit .gitignore**. It would be helpful if the menu contained an additional option **Edit .git/info/exclude**.
- [ ] The context menu for unstaged files in the Commit dialog includes an option **Add file to .gitignore**. It would be helpful if the menu contained an additional option **Add file to .git/info/exclude (ignore locally)**.

**Comment by jrfnl** [comment]
Thank you @sharwell ! I'm looking forward to being able to use this feature :heart_eyes_cat:
