### ISSUE TITLE
Display colors in terminal output in comit/push/etc. windows

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#2198]
It would be really nice, because you can easily see green/red for hooks and the window does not need to be left open. 

--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.3.9600.0

**Comment by jazzzz** [comment]
Would be really nice for push to things like heroku or dokku.

**Comment by vbjay** [comment]
Just add a remote.

**Comment by jazzzz** [comment]
> Just add a remote.

I have a remote, but I don't understand how it would fix this. If I push from a terminal, I have the colors, it's inside GitExtensions that i would like to have colors.
