### ISSUE TITLE
No Pause for Passphrase Entry Before Failure

### ISSUE THREAD

**Issue by Faedelity** [gitextensions/gitextensions#2199]
--- GitExtensions2.47.3, Git 1.8.4.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

I have an SSH Key with a passphrase, and am using OpenSSH. The GUI for a failed Push access comes up before the command line window in which I would enter the passphrase is even done rendering, let alone my having any chance to enter the passphrase and continue.

It should either be specified that keys with a passphrase are not merely unnecessary, but will not function for this purpose, or a delay for user input should be added to the process (possibly if a particular setting is toggled to indicate that this is needed, off by default).

**Comment by hypersw** [comment]
https://github.com/gitextensions/gitextensions/pull/3152 might be also improving this area.
