### ISSUE TITLE
Simplify dialog "Create branch"

### ISSUE THREAD

**Issue by kasal** [gitextensions/gitextensions#2209]
When Create branch is run from the browse window, the preset branching point is the position of the highlighted commit.
But it is quite rare to create branch at an arbitrary branch point; in most cases it is the commit currently checkout, or perhaps the tip of another branch.

I suggest to Change the dialog this way:
At the beginning, it would offer only the field for new branch name and the checkbox to check it out immediately (preselected).

The upper part ("...at this revision") would move below and would be displayed only on request (link "More options"), together with the other exotic options.

Moreover, the field for branching point would be a combo box, where the list would offer local branch names. The button for selecting individual commit would stay next to it.

What do you think?

**Comment by RussKie** [comment]
Closing due to age. 
We aren't going to change the dialog's layout.
