### ISSUE TITLE
Simplify Rebase in context menu

### ISSUE THREAD

**Issue by kasal** [gitextensions/gitextensions#2211]
When merge or rebase is initiated from right-click menu in GitExt browser, then one can select one of the branches pointing to the commit in question.

The selected branch name is filled to the field in the merge/rebase dialog, but has no influence on the operation.
Consequently, I suggest to remove the branch submenu and just use the first symbolic name available.
(Or, to be extra kind to the user, the symbolic name could be selected depending on the exact position of the right-click, bot that really is not necessary.)

Note that this is very different from the Delete/Rename branch: these apply to the branch name, so they need their submenus.

**Comment by RussKie** [comment]
Done in current master (v3)
