### ISSUE TITLE
Add core.filemode to preferences

### ISSUE THREAD

**Issue by patricktokeeffe** [gitextensions/gitextensions#2219]
In some instances, the list of "changed" files will include files whose content has not actually changed but the file permissions have. The diff screen will state:

    <...>
    old mode 100755 
    new mode 100644

This is not a problem with GitExtensions per se, but it does make GE unusable. The "changed" files cannot be stashed, for instance, so any action requiring a clean working directory cannot be performed. 

This seems to manifest when working with a repo from different platforms and it can be solved by telling Git to ignore filemodes. Some links with more information:

- http://www.f15ijp.com/2012/08/git-diff-old-mode-100755-new-mode-100644/
- http://stackoverflow.com/questions/1257592/how-do-i-remove-files-saying-old-mode-100755-new-mode-100644-from-unstaged-cha
- http://code.google.com/p/msysgit/issues/detail?id=164

I'd like to see the option to set 'core.filemode' added to the "Global settings" and "Local settings" preferences pages much like the 'core.autocrlf' option.

**Comment by patricktokeeffe** [comment]
OK, I see that option under Repository > Git Maintenance. It'd be nice to have one-click access to ~/.gitconfig too but that's a pretty popular, easy-to-find file.

**Comment by Joshua698** [comment]
- 11:07 0  30  and.com Ch  文 简体中文  ENGLISH  G  ARGUL LIS source  People also view  git diff提示filemode发生改变(old mode 100644、new mode 10075)_Ixw1844912514的技术...  , git diff提示filemode发生改变(old mode 100644、[[[[]()]()]()]()new mode 10075) 今天clone 代码,gitstatus显示修改了大量文件,gitdiff 提示filemode变化,如下: diff--gita/Andr...  51 51CTO Jul 5, 2021  如何从Git 中的未暂存更改中删除说 “旧模式![image](https://user-images.githubusercontent.com/71152899/223000797-75019fa7-11bc-4086-9903-48b7cc95287f.png)100755新模式100644”的 文件?  Windows 上从另一个磁盘把git目录复制到本 地, no@@@_****_******@patricktokeeffe
