### ISSUE TITLE
move or change path of submodules

### ISSUE THREAD

**Issue by zoghal** [gitextensions/gitextensions#2222]
hello,
please add this feature: Ability to move or change path of submodules in repository.
thanks

**Comment by RussKie** [comment]
If you were to make an update from a cli how would you have made an update? Would you just update .gitmodules file, or would you need to execute some other commands?


> Might be worth an explanatory sentence in the documentation.

The docs are located at https://github.com/gitextensions/GitExtensionsDoc. A PR with an update is welcome 😉 

> This is a great tool. Thanks to all contributors.

👍 Thank you
