### ISSUE TITLE
Submodule local path

### ISSUE THREAD

**Issue by MarcoNovaro** [gitextensions/gitextensions#2233]
I'm trying to use submodules with GitExtensions v2.47.3
I noticed that if I create the submodule in a "local path" that is _one_ level deep only (i.e. one subdirectory), everything works fine. Double clicking on the submodule opens a new window, with the whole hystory tree of the submodule itself.

If the submodule local path is a "second level" directory (e.g. /kernel/subA), double clicking it will open a new "empty" window (i.e. showing the dashboard, with no project open).

Can you please consider fixing this?
Thank you

**Comment by jbialobr** [comment]
Works fine. Please, reopen this issue if it does not work for you in the 2.49.03 version.
