### ISSUE TITLE
Delay with getting the tag names for the commit leads to UI focusing oddities

### ISSUE THREAD

**Issue by iafan** [gitextensions/gitextensions#2234]
When the commit row is selected in the list, it takes some time (2-3 seconds) to populate the information pane (most likely, the branch name tags, since it is the two lines "Contained in branches: xxx / Contained in no tag" that get displayed after the delay).

This delay is not a big of a problem per se, but it causes some more serious UI problems: imagine the line with the commit (A)  is initially selected (on e.g. app start or refresh), I then right-click on the other line (B) and select some action on it. However, in this very moment the missing information about branch/tags is being loaded into the commit (A), and the focus jumps to line (A). So pretty much often the action becomes performed on the wrong commit, which leads to all sorts of problems.

Here I see two potential fixes that could improve the situation:
1) Do not automatically change the focus from one commit to another. If I selected some commit, this is for a reason.
2) When a context menu is opened for a particular commit, remember the commit it attributes to before, and do not determine it after the context menu is closed.

--- GitExtensions2.47.3, Git 1.8.1.msysgit.1, Microsoft Windows NT 6.3.9600.0

**Comment by jbialobr** [comment]
It is more likely related to restoring selected revision after reloading the commit log. When the commit log wasn't completely loaded, the selection was restored after the commit log was completely loaded. It is fixed in 2.50.
