### ISSUE TITLE
Browse for Folder auto scroll

### ISSUE THREAD

**Issue by luissanchezsanchez** [gitextensions/gitextensions#2239]
--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

In "Browse for Folder" form. When I click a folder the scroll is going down, then I have to scroll always to see the sub-folder I am looking for. Why not to automatically scroll UP... The sub-folders are always below the clicked one.

Thanks for this great software.

**Comment by RussKie** [comment]
Is this still an issue in the current version?
