### ISSUE TITLE
FInd large files plugin does not handle spaces in names

### ISSUE THREAD

**Issue by patricktokeeffe** [gitextensions/gitextensions#2245]
The 'File large files' plugin does not remove files which contain spaces in their paths. There is no feedback to indicate why the file is still present the next time the plugin is launched. It (silently) fails because the file name searched against is not quoted: 

``` bash
>"git" filter-branch --index-filter "git rm -r -f --cached --ignore-unmatch doc/datasheets/file to remove.txt" --prune-empty -- --all 
                                                                            ^----   should be quoted    ----^
```

This will remove the file as expected:

``` bash
>git filter-branch --index-filter 'git rm -r -f --cached --ignore-unmatch "doc/datasheets/file to remove.txt"' --prune-empty -- --all
```

--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 5.1.2600 Service Pack 3

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
