### ISSUE TITLE
Feature request: Improved access to favorites

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#2246]
Hiya,

Let me first say that I absolutely **love** GitExtensions!

One thing I run into though is that I regularly switch between quite a few different repos. So quite often the repo I want to switch to is no longer in the recent list and I either have to Start -> Open or Close current repo -> use my favorites list on the dashboard.

I only recently discovered the favorites list and am very happy to have found it, but it would be great if it could be opened while in a repo.

I'm thinking either:
- As a menu item - either a top-level menu item like between Start and Repositories or a sub-menu within Start, positioned just under the 'recent repos' item with a fold-out for non-RSS each category.
- As a fold-out submenu at the bottom of the recent repo list in the toolbar

Would be great to hear if other people would like this too.

Smile,
Juliette

**Comment by RussKie** [comment]
Done in the current master (v3)
