### ISSUE TITLE
"Putty SSH" section is missing

### ISSUE THREAD

**Issue by dvdnhm** [gitextensions/gitextensions#2251]
The "Putty SSH" section is missing on "Manage Remote" section

From documentation: 
![image](https://f.cloud.github.com/assets/6667615/2196580/414c8a2c-98b1-11e3-83b9-0a9d8bdf4132.png)

What I see: 
![image](https://f.cloud.github.com/assets/6667615/2196608/c7f508d8-98b1-11e3-9447-df80ac0af05b.png)

Either this was moved to somewhere else and documentation is not updated or this is an issue/bug.

**Comment by RussKie** [comment]
The remotes management dialog shows putty section only if putty is selected as the preferred transport.
