### ISSUE TITLE
Remove 5MB limit

### ISSUE THREAD

**Issue by midda2** [gitextensions/gitextensions#2253]
Please remove 5BM limit that arises when doing commit. The message says "This file is over 5MB. Click to show preview".
Otherwise could you extend that limit to, say, 10MB either could you make the limit adjustable somewhere in .ini file?
Thank you for considering my request.
![unbenannt](https://f.cloud.github.com/assets/6734382/2215635/a08e59f6-99f7-11e3-9a17-37bd3e9af2a6.png)

**Comment by drewnoakes** [comment]
Do you view such large files so often that it's inconvenient to click to show the diff in such cases?

**Comment by RussKie** [comment]
Every user will have a different definition for a "large" file. For some it may be anything above 100KB, for others, like yourself, 16MB may not be enough. We have to draw a line in a sand and set limit somewhere, 5MB seems reasonable for the majority of users. 
Afterall git is a _source control management_ system, and it is atypical for source code files to size in megabytes... That's not to say you can't use it for storing sizable artifacts, it is a question of whether it is a good thing.

If we allow display of very large files (say 10MB+) we may be degrading the app's responsiveness and performance and consuming a lot of memory. There may also be a memory leaks beyond our control. This may make a lot of users unhappy.

You are still able to see large files, you just need to click to show the content.
