### ISSUE TITLE
Add 5MB limit to previews in diff pane

### ISSUE THREAD

**Issue by blerner** [gitextensions/gitextensions#2272]
In repositories that have a few huge generated files, the diffs for those files completely lock up the UI.  Can you add a "This file is larger than 5MB; click to preview diff" option to the diff preview pane to avoid this?  (This is sort of the opposite of #2253, though both this issue and that could benefit from a configurable 5MB limit.)

**Comment by drewnoakes** [comment]
@blerner, sorry but I am a bit confused. How is what you're asking for different to the currently behaviour shown in the screenshot in #2253?

**Comment by blerner** [comment]
There are plenty of other places that show diffs (https://git-extensions-documentation.readthedocs.io/en/latest/browse_repository.html shows several).  #2253 is just showing the commit window's diff view.

**Comment by drewnoakes** [comment]
Thanks for clarifying. You're right -- the 5MB limit is part of `FormCommit`. We might move it to `FileViewer` instead.
