### ISSUE TITLE
Pending commit count wrong

### ISSUE THREAD

**Issue by tlhackque** [gitextensions/gitextensions#2288]
I run git extensions on Windoze, with a repository on a samba share.

All's well, except: the pending commit count (in the 'commit' button on the toolbar) is often stale.  It's not critical - but it can be disconcerting.

For example: if I click on the Commit button, it will show 5 files with changes, which is correct.  But the button will have a different number.  If I commit the files and exit the commit dialog, the commit works - but the count in the button does not decrease.

Clicking 'Refresh' - on the toolbar or in the Commit dialog - does not update the count in the button.  But if I wait long enough (many minutes) after a commit, the count eventually syncs.

I can believe that an smb share might not be providing timely change notifications - but I find it surprising that 'refresh' doesn't cause the count to be corrected.  I expect clicking 'Refresh' to synchronize the GUI with the disk.

Git Extensions 2.47.3, Windoze 7

**Comment by kimitop** [comment]
This problem also happens in 2.48.05 and not use samba.It happened not regularly and reopen gitextensions the count will wrong either. You must reboot the computer to solve the count problem.

**Comment by vbjay** [comment]
You don't need to reboot. You just need to wait for the git processes to quit or kill them.

**Comment by RussKie** [comment]
Is this still an issue?
