### ISSUE TITLE
Two cherry pick in row with conflict

### ISSUE THREAD

**Issue by ZoltanV** [gitextensions/gitextensions#2314]
--- GitExtensions2.46, 1.8.3.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1
When I try to resolve the second conflict with kdiff then kdiff will stop and I have to close the kdiff task in task explorer.
The issue appears all the time, when I try to resolve commit second time (first time it is working fine). So if I abort the merge and try again the cherry pick and conflict resolving, the kdiff tool will stop.
Workaround: I need to restart the git extensions and after that I can resolve 1 commit.
If I have to deal with an other commit (with conflict), then I need to restart the git extensions again. :(

**Comment by johndog** [comment]
Can we close this on the heels of #3471?

**Comment by GintasS** [comment]
Abandoning this because of age. Also, seems a PR was merged related to this (see comment above).
