### ISSUE TITLE
Settings window checklist is illegible on a high DPI screens

### ISSUE THREAD

**Issue by mfloryan** [gitextensions/gitextensions#2330]
version 2.47.3 on Windows 8 (in Bootcamp on Mac Book Pro with retina display)

In the main settings window the checklist texts are all cropped (font large but the frame is not extended).

![image](https://cloud.githubusercontent.com/assets/448107/2798558/f3327422-cc50-11e3-8a8e-e567db0d729c.png)

**Comment by RussKie** [comment]
This is how the current version looks on 4K with 200% scaling:
![image](https://user-images.githubusercontent.com/4403806/36144842-83efecce-1103-11e8-9afd-22f5115c8a7c.png)
