### ISSUE TITLE
Issue with Proxy configuration

### ISSUE THREAD

**Issue by alpesh-shah** [gitextensions/gitextensions#2343]
--- GitExtensions2.46, 1.8.3.msysgit.0, Microsoft Windows NT 6.1.7600.0

I am using Git extension behind the proxy. I set my proxy with Proxy Switcher plugin but it still gives below error

fatal: unable to access 'https://github.com/awltech/resources.git/': Failed connect to github.com:443; No error

My team confirmed that its not hitting proxy as no request in proxy server log but when I use same tool outside of proxy network, everything works fine. Not able to understand where is the issue.

**Comment by Katiyman** [comment]
I am also facing same issue. i Have set proxy for git and also is http swithcer but still its giving me timout error
