### ISSUE TITLE
Wring default branch for pushing when "Default merge with" is selected

### ISSUE THREAD

**Issue by KunzeAndreas** [gitextensions/gitextensions#2350]
--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.2.9200.0

I select a branch under Repository / Remote Repositories,,, / Default pull behavior "Default merge with". When I pull, this branch merges to my branch.

But when I push, I don't expect the selected branch to be the default branch for pushing.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
