### ISSUE TITLE
Option to hide fully merged branch commits (like --first-parent)

### ISSUE THREAD

**Issue by ajilani** [gitextensions/gitextensions#2351]
I would like to be able to filter out history from merged branches, just like when I type "git log --first-parent" in the command line.  For example, my history looks like this:

![all-parents](https://cloud.githubusercontent.com/assets/7442704/3126489/5387ae6a-e7a3-11e3-98f2-0f12beebc1da.png)

but I would like to see this instead:

![first-parent](https://cloud.githubusercontent.com/assets/7442704/3126490/5d2c9f0c-e7a3-11e3-8d8d-39feeddef957.png)

The faded-out branch and merge lines would be nice, but not necessary.  Is there some way I can have Git Extensions use the --first-parent argument when it runs "git log"?

**Comment by tadeu** [comment]
:+1:

**Comment by KindDragon** [comment]
I think they shouldn't be hided. Instead better show fake node:
"X commit hidden" and diff tab will show changes for that commits

**Comment by max630** [comment]
If you write "--first-parent" into the branch selector it will print only the first-parent chain. Gird though will be broken. Looks like unexpected feature

**Comment by ajilani** [comment]
Neat! This is actually very useful, even with the infinite octopus legs.

**Comment by jbialobr** [comment]
Implemented in #3250.

**Comment by max630** [comment]
Having installed v2.49.03 I still can see broken graph with the "first parent" enables. It somehow depends on path, but if I refresh with graph on then it reproduces quite reliably.

![image](https://cloud.githubusercontent.com/assets/381560/26816212/326367e0-4a99-11e7-82ee-9a71e9e46d4e.png)

**Comment by jbialobr** [comment]
It only works when `Show current branch only` is enabled.
![gitext](https://cloud.githubusercontent.com/assets/1003909/26818314/741cea8e-4a9a-11e7-80b2-b9a8ed8d1c5b.png)
