### ISSUE TITLE
File history may show excess commits

### ISSUE THREAD

**Issue by mnaoumov** [gitextensions/gitextensions#2363]
Sometimes GitExtensions shows many irrelevant history commits

After some investigation I found the root cause. GitExtensions may handle renames incorrectly.

I prepared a test repository https://github.com/mnaoumov/gitextensions-filehistory-issue-example

That repository had file **old.txt** which was renamed to **new.txt**. And later file **old.txt** was recreated again.

If we take a look on history for **new.txt**, we get excess commits that correspond to recovered **old.txt**.

![history-issue](https://cloud.githubusercontent.com/assets/735878/3247044/a2672eac-f180-11e3-817d-cc0d05c5f64e.png)

If we run

    git log --oneline --follow new.txt

it shows correct commits without these excess commits

    775c983 new.txt - Line 5
    9e2f681 new.txt - Line 3
    98a7d04 rename old.txt -> new.txt
    d758af2 old.txt - Line 2
    a336b6f old.txt - Line 1

I found the GitExtensions commit that causes the issue: https://github.com/gitextensions/gitextensions/commit/bf88dd5a24fc46f416da656a0ec01e003b03232f

It refers to some mail thread  http://kerneltrap.org/mailarchive/git/2009/1/30/4856404/thread which is unfortunately unavailable anymore.

I don't know if that fix is still relevant for current git version.

So maybe you can just revert the commit **bf88dd5a24fc46f416da656a0ec01e003b03232f**

NOTE: If we just need to see file history and don't care about renames we can disable it from context menu in history window.

![context-menu](https://cloud.githubusercontent.com/assets/735878/3247381/bd758934-f183-11e3-8a8b-acfb30cce8d6.png)

**Comment by jbialobr** [comment]
Yes it is fixed in #2512. @mnaoumov thank you for the detailed report and the test repo.
