### ISSUE TITLE
"View Pull Requests" always gives an error saying "Failed to load diff data!"

### ISSUE THREAD

**Issue by AdamSturtridge** [gitextensions/gitextensions#2366]
Also says "The remote server returned an error: (404) Not Found"

It shows pull request items, but does not show any details of selected item.

--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by jrfnl** [comment]
I just encountered the same, though in my case, this only seems to happen on `private` repos. - Git Extensions 3.2.1.6628

**Comment by RussKie** [comment]
@jrfnl please raise a new issue and provide as much info as possible

**Comment by jrfnl** [comment]
@RussKie Will do next time I encounter the issue. I've been playing around with the `View pull requests` option lately, hadn't used it until now.

**Comment by jrfnl** [comment]
Follow up issue #7336
