### ISSUE TITLE
Issue when pushing branch with different names between local and remote repositories

### ISSUE THREAD

**Issue by qsrdavid** [gitextensions/gitextensions#2370]
--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 5.1.2600 Service Pack 3

Good Morning,

My name is David Arnold and with the newer version of Git Extensions, I am experiencing a problem when pushing the local branch to the Remote Branch when the branch names are different.  Before this update, I was able to push this branch without having a warning show up.  Attached is the screenshot of the warning.  Also, I have noticed that the "Remote" drop down list is not showing the branches from the "Remote" Repository.  Instead, it is showing them from the "Local" Repository.  The changes are still being pushed to the correct branch, but can this warning be fixed, so I don't have to rename the "Local" branch to match the "Remote" branch name, just to keep this warning from showing.  I do like the newer look of the pushing window and how the pushing will allow us to pull the changes right then, if there are changes needed to be merged.  Thank you for your time, and hopefully, this warning can be fixed with the next update. 

![git_issue_when_pushing_changes]
(https://cloud.githubusercontent.com/assets/7966444/3359937/a938ac08-faed-11e3-9f9a-e848ff2b6929.png)

Thanks,

David Arnold

**Comment by jbialobr** [comment]
The warning is shown according to the knowledge from the git's local database. To synchronize the database with the remote server perform `git fetch` for the remote.  I checked that if the remote branch is known to git locally, GitExt does not show this warning.
