### ISSUE TITLE
Show non-printing characters in commit dialog: Differentiate between LF and CRLF end-of-lines

### ISSUE THREAD

**Issue by carleeto** [gitextensions/gitextensions#2373]
I have version 2.47.3 on Windows 7.

When I am in the commit window, I always have "show non-printing characters" on.
The problem is that, regardless of whether the file has DOS or UNIX line endings, I see the same symbol (http://www.fileformat.info/info/unicode/char/b6/index.htm) at the end of the line.

This means that when the only change in a file is the end of line character, show non-printing characters is not helpful.

Solution:
There needs to be different symbols for different line endings. 
Perhaps something from this page: http://www.fileformat.info/info/unicode/block/control_pictures/images.htm

**Comment by CoperNick8** [comment]
See also image on this page https://visualstudiogallery.msdn.microsoft.com/545e56a7-98d7-47f9-9d84-4681f2903060

**Comment by Kryptos-FR** [comment]
Recently realized I needed that feature.

For working copy files, I can just open it in an editor supporting that feature (such has Notepad++) but for files in other commits, I need to go to the file tree and do "open this revision with... (temp file)" which is time consuming.

Would you mind assigning a milestone to that issue (and maybe the "up for grab" tag)?
Thanks.

**Comment by RussKie** [comment]
@Kryptos-FR assigning a milestone means the core team commits to implementing a feature/fix a bug by the due date.

PRs implementing the feature are welcome.

**Comment by Kryptos-FR** [comment]
@russKie understood.

**Comment by mstv** [comment]
Done with #9620
