### ISSUE TITLE
Cherry picking multiple commits at a time

### ISSUE THREAD

**Issue by mmoayyed** [gitextensions/gitextensions#2396]
Right now, on the latest release, cherry picking is limited to picking one commit at a time. Would be nice if multi-selection was enabled, so that a batch of commits would go into a given branch. I believe CLI allows for ranges, and the UI should as well.

**Comment by iKahvedzic** [comment]
Bump.

**Comment by vbjay** [comment]
Do not bump issues. We can see all the issues just fine.

**Comment by iKahvedzic** [comment]
Well, that's a terse response. Have I offended you? Or is it generally frowned upon to do such things around here?

**Comment by vbjay** [comment]
generally frowned upon.

**Comment by webmaster33** [comment]
Unfortunately the "Cherry picking multiple file changes in Diff tab" feature is still not implemented.

I just would have been need it to batch add changes from one branch to another, but I sadly noticed, it is not yet possible.

I would really welcome this feature.

**Comment by jbialobr** [comment]
Cherry picking multiple commits is supported since v2.40.

@webmaster33 this issue is about cherry pickinkg multiple commits. Please raise a new issue.

**Comment by crypto-rsa** [comment]
> Cherry picking multiple commits is supported since v2.40.

Can you point to the commit which allows this? I have just checked it in 2.49.03: when I select multiple revisions and click Commands - Cherry pick..., I get a message saying *Select exactly one revision*.

**Comment by jbialobr** [comment]
b3e79447928051cfb3494c9c0ef1a1d0ecde56a8 - It was enabled for cherry-picking from the context menu.
It should be enabled from the toolbar menu as well.

**Comment by jasselin** [comment]
Is the feature still present in 3.x?

**Comment by gerhardol** [comment]
By right clicking, not in toolbar menu (probably changed when impossible combinations was disabled)

**Comment by zwcloud** [comment]
Where? I cannot find it.
![image](https://user-images.githubusercontent.com/6965758/110058576-8636ae00-7d9d-11eb-9f39-eb23eb1c9a80.png)

**Comment by RussKie** [comment]
The context menu can probably be reworded. Commits are cherrypicked in sequence, hence it is "this commit".

**Comment by zwcloud** [comment]
> 
> 
> The context menu can probably be reworded. Commits are cherrypicked in sequence, hence it is "this commit".

TortoiseGit:
single commit selected:
![image](https://user-images.githubusercontent.com/6965758/110074995-0ddfe500-7dbd-11eb-9a3e-eaac91801271.png)

multiple commit selected:
![image](https://user-images.githubusercontent.com/6965758/110074895-e852db80-7dbc-11eb-994f-844d3f45307f.png)

**Comment by vbjay** [comment]
Just do an interactive rebase and alter the todo list.
