### ISSUE TITLE
Process window never finishes, must be aborted, but task is completed

### ISSUE THREAD

**Issue by patricktokeeffe** [gitextensions/gitextensions#2404]
I've resisted reporting this behavior because I haven't been able to replicate it... but it happens frequently enough I've decided to report it anyway. 

--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 5.2.3790 Service Pack 2

Most Git-tasks and their output are shown in a dialog window titled "Process (*repo path*)". Such windows usually have a 'Keep dialog open' checkbox. Sometimes the windows just sits there with the progress bar churning, churning, churning. I see this most often with the Commit and Checkout branch dialogs. 

After a few minutes I just press the 'Abort' button and whatever task was trying to be completed, always is. Of course I do wait several minutes to make sure the window has actually hung and the task is probably complete. The waiting is the annoying part. 

What kind of information would be useful to troubleshoot this? Should I pause the process and copy the stack using Process Explorer? There doesn't appear to be any subprocesses of GitExtensions.exe open when this occurs.

**Comment by patricktokeeffe** [comment]
I haven't seen this for quite a while and not at all with 2.48 so closing.

**Comment by Lavinski** [comment]
I'm quite regularly get the same issue.
![image](https://cloud.githubusercontent.com/assets/1761789/6344727/54331f3c-bc48-11e4-9012-e9e695591125.png)
