### ISSUE TITLE
Option to ignore line ending change warning

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#2406]
Hi all,

Small feature request from one of your dedicated fans ;-)
GitExtensions version v2.47.3

I'm working on Windows, though quite often work with files using Unix line endings or even actively change the line ending style for files to Unix-LF in my editor.

When I stage these files, I get this warning for each of the files. Also if all that's changed is the line ending, they won't show up in the stage area (Ref: #458).
![warning screenshot](http://snag.gy/jHsSy.jpg)

While the message is actually confusing and incorrect (Ref #134) as my global settings mean that the commit line-ending style will be LF (which it already is for these files), while the warning gives the impression they will be changed to CRLF, it's also really annoying to have to click through this message for each and every file (if staged individually).
![screenshot global settings](http://snag.gy/7Pufs.jpg)

I'd like to suggest adding an option to ignore these warnings to the Settings page - with a checkbox at the bottom of the warning message to enable the ignore feature as well. Would that be possible ?
![settings dialog screenshot](http://snag.gy/i2KQ1.jpg)

Thanks in advance for considering this feature request & keep up the good work!

Smile,
Juliette

**Comment by swoobie** [comment]
I am also very interested in adding this!

**Comment by jbialobr** [comment]
There is an option to disable showing errors when staging files https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#commit-dialog (Show errors when staging files).

**Comment by jrfnl** [comment]
@jbialobr Thank you for your response. Doesn't that disable more than just the line ending message though ? It's only the line ending message I'd like to disable.

**Comment by jbialobr** [comment]
> Doesn't that disable more than just the line ending message though?

It disables all warnings and errors. But it is very uncommon to see there any other warning/error, so I thought you can disable it right now, since you get a lot of these related to LF. I also left the issue open for you requested to only ignore LF related warnings.

**Comment by jrfnl** [comment]
Appreciated! Thank you.

**Comment by jbialobr** [comment]
There is an option `core.safecrlf` that can be set to false to disable this particular warning to be emited by git. The preferred solution of this issue should expose this option on the Git Config settings page.

**Comment by jrfnl** [comment]
@jbialobr That sounds perfect!

**Comment by RussKie** [comment]
Closing due to the age.
Re-open if you still have issues.

**Comment by KurzedMetal** [comment]
I think Git Extensions could do better than it currently does about these CRLF conversion *warnings* when staging. And I think the original guy that opened this issue had the right idea.

The most annoying part is that it opens an extra popup every time I want to stage a file from the Commit window.

I know I can "fix" this with `core.safecrlf = false`. But I shouldn't need to disable this git feature only to avoid a Git Extension popup spam. It's a minor warning anyways, not an error.

I know I can disable "Show errors when staging files". But this isn't an error, it's a minor warning, the command-line `git add` that generates this warning still have a success exit code (0). I should need to ignore all types of errors just to avoid a popup spam for a minor warning.

For some reason, even git if ends up with a exit code of 0 (no error), Git Extensions still shows this message as an error. I think the popup should only appear if git returns non zero exit code (error) and the user have enabled "Show errors when staging files" and maybe add another option (like "Show warnings when staging files") in Git Extension to control whether to show/hide warnings when stderr have lines but git exit status is till zero.

**Comment by vbjay** [comment]
It is a warning. The warning should be shown. I do agree with that the UI could show success with warnings UI instead. Having it show a warning icon instead of a red x would be useful.

**Comment by KurzedMetal** [comment]
I still think the better approach is to have an option to ignore warnings. Why having one to ignore errors but not warnings? Errors are arguably more important.

**Comment by vbjay** [comment]
We are trying to not hide things. If you ran the command in bash you would
see the warnings. We are not trying to hide them. Yes they are minor but
with the different options of autocrlf/gitattributes and other options we
want the person to know the line feeds were altered. Depending on the
autocrlf setting you can get corrupted files when checking out. It's good
to know file x had it's line endings replaced. It gives you a chance to
handheld the issue if it is an issue. It's up to tree developer to
determine if it is an issue or not.

**Comment by vbjay** [comment]
I do think a warning instead of critical exception UI could tell the user, hey it worked but here is some info for you.

**Comment by KurzedMetal** [comment]
I'm not saying that it should be hidden by default, I'm saying it should have an option to hide only warnings.
