### ISSUE TITLE
Auto-close line-ending warning dialog

### ISSUE THREAD

**Issue by mmoayyed** [gitextensions/gitextensions#2412]
At times when I am attempting to stage and commit files, I get the following error/warning:

```
Stage 2 files
warning: LF will be replaced by CRLF in development/protocol/CAS-Protocol.md.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in development/protocol/CAS-Protocol-Specification.html.
The file will have its original line endings in your working directory.
Done
```

How can I ignore this warning automatically? I'd rather not change my line ending settings, and simply be provided a way for this dialog to go away on its own, or not even pop up.

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/41882986-69944a48-792f-11e8-997a-fa8bc5928818.png)
