### ISSUE TITLE
Installer claims Administrative privileges are not needed for current user install. 

### ISSUE THREAD

**Issue by rubberduck203** [gitextensions/gitextensions#2434]
Installer has an option to "Install just for you" and claims that this option does not need local Administrative privileges. This does not seem to be true. No matter what options I try, I am prompted for an administrative logon. 

I also tried installing to a different directory knowing that I cannot write to C:\Program Files (x86)\ and disabled "Add installation directory to PATH".

**Comment by leak** [comment]
Selected "Just for you" and got the following error on 2.49 RC1:

![image](https://cloud.githubusercontent.com/assets/530056/19349395/1127edda-9153-11e6-903b-1cb75be5325e.png)
