### ISSUE TITLE
The folder path 'My Documents' contains an invalid character

### ISSUE THREAD

**Issue by EifX** [gitextensions/gitextensions#2439]
Hello,

we use in our company the new GitExtensions 2.48. The normal Setup-File doesn't work for us, because the error-message 'The folder path 'My Documents' contains an invalid character' appears.
Our Userhomes are located on a network-share, maybe this will be the issue.

Can you fix this in the setup routines? Our workaround is using the Mono-Zip and installing the included tools separately (KDiff3, msysgit)

Edit: This error is not a new error. In the old versions of GitExtensions (2.47.3 and earlier), the error was there, too.

**Comment by KindDragon** [comment]
Please try this https://support.techsmith.com/entries/22900767-Jing-During-the-Installation-process-I-receive-Error-1324-The-Folder-Path-Contains-an-Invalid-Charac
