### ISSUE TITLE
Commit selected is a random commit after deleting a branch

### ISSUE THREAD

**Issue by jeffqc** [gitextensions/gitextensions#2446]
After a local branch is deleted by using the right-click action "Delete branch", GitExtensions will select a commit somewhere else in the repository. I think it should select the commit pointed by the current branch, which is more interesting for me than a commit in the middle of nowhere.

**Comment by jrfnl** [comment]
Just came across this one in the changelog, nice! I've wondered about the logic behind this before as well. I look forward to the improved usability :+1:
