### ISSUE TITLE
Freeze while commit many files with warnings.

### ISSUE THREAD

**Issue by SetoKaiba** [gitextensions/gitextensions#2448]
It freezes while I commit many files. If I commit them separately with some and some. It won't freeze.
I find it freezes because the git.exe process is not terminated. I use promon to check what it exactly executes. Here's the command
 "C:\Program Files (x86)\Git\bin\git.exe" update-index --add --stdin
Then it freezes and never return. The previous 
"C:\Program Files (x86)\Git\bin\git.exe" check-attr -z diff text crlf eol -- [xxx file]
won't freeze. 
My computer is win 8.1 enterprise x64.

**Comment by kwaclaw** [comment]
This is still not fixed in 2.48.03.

**Comment by webmaster33** [comment]
I also have this problem with Git Extensions v2.48.03.
It hangs when I want to commit more thousand files.

**Comment by lodici** [comment]
I was having the same problem with 2.48.03 when staging 7000+ files - the progress bar goes to halfway then stops and the titlebar says "not responding". This is on Windows 7, 64-Bit.

To fix (although not sure _why_ it works) -
* Tools -> Settings.
* Select the Git Config page.
* Check Line Endings setting
  * Mine was set to _Checkout as-is, commit Unix-style line endings..._ (this was hanging).
  * Changed to _Checkout as-is, commit as-is..._ (**works!**).

**Comment by TheYves** [comment]
Thanks lodici! I had exactly the same problem!

**Comment by elyahueaton** [comment]
Have same issue. with all the above same phenomenon and problem details. Also using 2.48

But, for me none of the setting suggested helped :-(. Only opening BASH and running "git add ." made it.

It doesn't matter the number of files, the first time it freezes it will never work. Until you delete the index.lock and then it will freezes again when trying to do stage for even more the 4-5 files.

**Comment by jbialobr** [comment]
Fixed in #1643.
Will be released in 2.48.04 https://github.com/gitextensions/gitextensions/commit/f0a530e736ace6373953a4b4f67711a163ab0e4a
