### ISSUE TITLE
better ordering of branch names in "checkout branch" dialog

### ISSUE THREAD

**Issue by githubkusi** [gitextensions/gitextensions#2455]
Assume you have a branch you use often _featureNew_ and several branches you haven't used in a while, like _featureA_ & _featureB_

Assume you use the keyboard to for changing branches. You're in _master_ and want to change to _featureNew_
1. press Ctrl + point  (checkout branch dialog pops up)
2. press f (now a drop-down appears with _featureA, featureB, featureNew_
3. press twice arrow down till _featureNew_ is selected (->this shouldn't be necessary)
4. press enter

I was never interested in _featureA_ and _featureB_, and GitExtension could have known it since I've used _featureNew_ more recently.

When using the keyboard, it makes more sense to order the branch names by its timestamp rather than alphabetically. The current behavior forces me to rename currently unused branches to begin with a _z_

**Comment by bmeverett** [comment]
Branches are currently being displayed using `git show-ref --dereference --heads`.  The command `git for-each-ref --sort=-committerdate refs/heads/` will list the branches in order of latest commit. Should this be changed to support date ordering by default, or be configured by a setting?

**Comment by KindDragon** [comment]
I think we can try to use new order if someone would against we can then add option

**Comment by githubkusi** [comment]
branches in order of latest commit looks like a good solution! I don't think an option between alphabetical/date ordering is necessary, but I cannot speak for others

**Comment by KindDragon** [comment]
I think someone may need to sort alphabetically if he's looking for the old branch that does not fully remember the name. I do not know how often this scenario is required.

**Comment by bmeverett** [comment]
@KindDragon is there a target for when this will get implemented?

**Comment by jrfnl** [comment]
Ok, here's that someone that needs alphabetic order or at least any form of logical ordering.
Given that there are projects where I have over 50 active branches being worked on, I'm having a lot of trouble findings some of the branches I'm looking for - or rather I can't effing find anything at all anymore except for recent branches....

Alternatively, a way to fold out based on the branch names would be helpful as well.

As an example of what I mean by that, for certain projects, there are a couple of different forks I contribute to, so I generally prefix a branch with the fork name:
- forkA/feature/feature-name
- forkB/feature/feature-name

And I often add `/PR/` to the branch name to know which branches have been pulled and which are still WIP.

So being collecting all branches with a certain prefix and showing those as a sub-menu of the branch pull-down, could be helpful too.

**Comment by jbialobr** [comment]
@jrfnl Please, raise an issue for that - otherwise your comment will get forgotten.

**Comment by jrfnl** [comment]
@jbialobr Thanks for the heads-up. Done: https://github.com/gitextensions/gitextensions/issues/3907
