### ISSUE TITLE
WIX# Tool

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#2456]
I found this https://wixsharp.codeplex.com/ resource today.  I thought it might be a good tool to create custom UI for the installer.

**Comment by RussKie** [comment]
Just come across it. This is pretty cool.
It may possibly be simpler than mastering arcane wix syntax

**Comment by Johno-ACSLive** [comment]
While it's great Wix is free and there are many tools out there to help manage Wix installers and create nice UI.

Couple of questions:

Would you be open to changing packaging tools completely?

and

Do we also want to look at MSIX?

**Comment by RussKie** [comment]
> Would you be open to changing packaging tools completely?

Possibly, certainly open to a discussion.

> Do we also want to look at MSIX?

Sure.


Currently no-one in the core team has a good understanding of the wix, it happened historically.
So if there is an alternative tech that is easier/simpler to master and to use and extend - we're happy to discuss and consider options.

**Comment by pmiossec** [comment]
>Do we also want to look at MSIX?

We should be just aware that's only supported by some specific builds of windows 10 (so that requires to be up to date). And installing a MSIX on other than win10 requires the installation of a software not yet released. 
https://github.com/microsoft/msix-packaging/tree/master/preview/MsixCore

**Comment by Johno-ACSLive** [comment]
> > Do we also want to look at MSIX?
> 
> We should be just aware that's only supported by some specific builds of windows 10 (so that requires to be up to date). And installing a MSIX on other than win10 requires the installation of a software not yet released.
> https://github.com/microsoft/msix-packaging/tree/master/preview/MsixCore

True, but MSIX can be produced along side MSI.

We could also bootstrap things, I haven't checked what other packaging tools can do in this regard but we can manually bootstrap MSIX for earlier versions of Windows that don't officially support MSIX.

The tooling I use is Advanced Installer. They have an extension for Visual Studio as well as a full UI for packaging / repackaging etc. Advanced Installer has many editions including a free edition.

If the free edition can cover all the features currently utilised then it's a great alternative. If not, I'll look at other packaging tools.

I'll come back with something 😃

**Comment by RussKie** [comment]
One thing I'd really love to have is a simplification of variable asset management, such as translations.
We only include translations that are 95% complete, and we need to modify product.wxs every time we release.

**Comment by RussKie** [comment]
Another important consideration is support of the chosen packaging format by our signing service - SignPath.
AFAIK they do not currently support MSIX (https://about.signpath.io/documentation/artifact-configuration/)

**Comment by Johno-ACSLive** [comment]
> One thing I'd really love to have is a simplification of variable asset management, such as translations.
> We only include translations that are 95% complete, and we need to modify product.wxs every time we release.

Could we move asset management to GitExtensions rather than the installer to manage? Or perhaps the installer includes the current and GitExtensions can manage updates or new ones and they can be on a per user basis. In either case, this means users won't need to have all assets if users are not using them.

**Comment by Johno-ACSLive** [comment]
> Another important consideration is support of the chosen packaging format by our signing service - SignPath.
> AFAIK they do not currently support MSIX (https://about.signpath.io/documentation/artifact-configuration/)

Advanced Installer supports MSIX, code signing source files and the installer. The build pipeline just needs the certificate and the advanced installer project can use it.

In any case I think there are many options to support what is needed, just depends on what is acceptable by the core team for the project.

**Comment by gerhardol** [comment]
> just depends on what is acceptable by the core team for the project.

Basically, everything that improves GE is accepted.
RussKie listed a few of the problem we see right now.
For signing, that is done by SignPath, we do not have the certificate ourself, so there are alternatives. But SignPath do evolve over time.

**Comment by RussKie** [comment]
> Could we move asset management to GitExtensions rather than the installer to manage?

Translations and dictionaries are not build time, but deploy time assets. 
So they fall into the installer domain, they need to be packaged and delivered to clients.

**Comment by Johno-ACSLive** [comment]
> > Could we move asset management to GitExtensions rather than the installer to manage?
> 
> Translations and dictionaries are not build time, but deploy time assets.
> So they fall into the installer domain, they need to be packaged and delivered to clients.

What I mean is, we can tackle this in different ways. Typically the packaging project only needs to know about new / removed files. If it's based on a Visual Studio project then the integration should allow the assets to be dynamic (I've not looked at how these assets are pulled in, could be that a post build action is needed or something).

In any case, my thought's were that we could make variable assets be downloadable by GitExtensions post install. On first launch, GitExtensions could in the background download / update the variable assets.

Alternatively, we can update the deploy time assets in the installer periodically but have an update mechanism on launch that will update / add / remove these assets in the background. The installer assets (depending on their nature) would sit in either program files with GitExtensions or in ProgramData (similarly if we were to support user installs, then these would of course sit in the user profile anyway). Any updates would sit in the users profile in AppData.

Food for thought 😃

**Comment by Johno-ACSLive** [comment]
> > just depends on what is acceptable by the core team for the project.
> 
> Basically, everything that improves GE is accepted.
> RussKie listed a few of the problem we see right now.
> For signing, that is done by SignPath, we do not have the certificate ourself, so there are alternatives. But SignPath do evolve over time.

I see and yes there are many options. I have a code signing certificate and access to Azure DevOps (which includes Pipelines / Artefacts etc.) as I have a Microsoft Action Pack subscription.

Happy to help provide anything that could be useful. I can't provide a copy of my code signing certificate etc. but could set something up to allow it's use specifically for GitExtensions.

**Comment by RussKie** [comment]
> What I mean is, we can tackle this in different ways. Typically the packaging project only needs to know about new / removed files. If it's based on a Visual Studio project then the integration should allow the assets to be dynamic (I've not looked at how these assets are pulled in, could be that a post build action is needed or something).

This is already configured as build action: 
https://github.com/gitextensions/gitextensions/blob/master/GitExtensions/GitExtensions.csproj#L133-L138

> we could make variable assets be downloadable by GitExtensions post install. On first launch, GitExtensions could in the background download / update the variable assets.

This will not work for users behind corporate firewalls and corporate security policies (the exact reason why @gerhardol may not be able to use the automatic upgrade).
I spent years working for a bank where GitHub was off limits (amongst many other developer-must-have resources).
The application installation should be as self-contained as possible.



> I have a code signing certificate and access to Azure DevOps (which includes Pipelines / Artefacts etc.) as I have a Microsoft Action Pack subscription.

Thank you for the offer. Will this necessitate us moving our CI/CD pipelines to AzDO?
Whilst I don't particularly care whether the project is built on AzDO, AppVeyor or <insert build platform here>, we are currently configured and integrated with AppVeyor and SignPath. 
Unless there are significant gains to be had I can't justify dedicate the team's efforts to a migration. There are many other issues/features that provide higher returns.

**Comment by Johno-ACSLive** [comment]
> This is already configured as build action:

Cool, so then it's just a matter of ensuring the pipeline for the installer can handle those dynamic updates (wouldn't be too much of a bother if Wix was easier to manage).

> This will not work for users behind corporate firewalls and corporate security policies (the exact reason why @gerhardol may not be able to use the automatic upgrade).
I spent years working for a bank where GitHub was off limits (amongst many other developer-must-have resources).
The application installation should be as self-contained as possible.

Agree'd, just wanted to check what kind of policies you had RE distribution and scenarios you wanted to cater to.

> Thank you for the offer. Will this necessitate us moving our CI/CD pipelines to AzDO?
Whilst I don't particularly care whether the project is built on AzDO, AppVeyor or , we are currently configured and integrated with AppVeyor and SignPath.

It depends, the AzDO would house the certificate and could be triggered by AppVeyor to perform a similar service as SignPath. I don't think we would need to replace AppVeyor and SignPath with AzDO (although it would make the CI/CD pipeline simpler and potentially more flexible).

> Unless there are significant gains to be had I can't justify dedicating the team's efforts to a migration. There are many other issues/features that provide higher returns.

Totally agree!

**Comment by vbjay** [comment]
Eventually my wix tool I am working on when time allows will allow for
exactly that kind of management.

**Comment by GintasS** [comment]
I think we should close this because:
- we already using Wix
- This issue is very old.
