### ISSUE TITLE
Can't run GitExtensions on Mac OS X 10.9.4

### ISSUE THREAD

**Issue by gillyb** [gitextensions/gitextensions#2457]
I downloaded and installed the latest version of mono (3.4.0)
And im running on a mac book pro with OS X 10.9.4

I downloaded the package GitExtensions-2.48-Mono.zip
When i tried running `mono GitExtensions.exe` I get an error - DllNotFoundException regarding `System.Drawing.GDIPlus.dll : libgdiplus.dylib`

**Comment by KindDragon** [comment]
Duplicate of #2508
