### ISSUE TITLE
2.48 git-credential-winstore installation issue

### ISSUE THREAD

**Issue by drauch** [gitextensions/gitextensions#2472]
I'm not 100% sure if this is a duplicate of #2467 but a friend of mine made some interesting observations when installting GitExtensions on a clean VM (no other GitExtensions version installed before).

git-credential-winstore does not work after the installation because of:

* The installer installs git-credential-winstore *before* MSysGit  -> git-credential-winstore cannot find the git.exe!
* Furthermore it looks for git.exe in the PATH variable -> if the user chooses to not put git.exe into the PATH during instalaltion, it will never find git.exe, even if installed after MSysGit

**Comment by KindDragon** [comment]
git-credential-winstore will be replace in 2.49
