### ISSUE TITLE
Statistics: IgnoreDirectories filtering fix/improvement

### ISSUE THREAD

**Issue by lggomez** [gitextensions/gitextensions#2476]
The current filtering only applies an .EndsWIth() operation, which doesn't work correctly in most cases. I'll give the following example: the packages directories include a lot of content (mostly xml) which may be irrelevant to the project. Excluding it via the settings dialog won't work, since the packages folder contains subdirectories per package (rendering the filtering useless).

Some examples (from this solution):
...gitextensions\gitextensions\packages\Microsoft.Bcl.1.0.19\lib\net40\ensureRedirect.xml
...gitextensions\gitextensions\packages\Microsoft.Bcl.1.0.19\lib\net40\System.Runtime.xml
...gitextensions\gitextensions\packages\Microsoft.Bcl.1.0.19\lib\net40\System.Threading.Tasks.xml
...and so on

The biggest issue is the huge number of false positives we get (especially on xml code, adding over 200 kloc). Exluding the file extension is a workaround, but it still affects the accuracy of the statistics.

The plugin settings and directory filtering need some rework, from both ui (remove the endswith restraint and change it to "contains", or maybe adding more filtering options) and the LineCounter current filtering

**Comment by jbialobr** [comment]
>The plugin settings and directory filtering need some rework, from both ui (remove the endswith restraint and change it to "contains", or maybe adding more filtering options) and the LineCounter current filtering

There should be a regex for excluding directories.

**Comment by oriash93** [comment]
Speaking of Statistics, I also suggest the window should be scrollable (see the Commits per contributor tab).
