### ISSUE TITLE
git extensions crashes very often

### ISSUE THREAD

**Issue by eddrog** [gitextensions/gitextensions#2477]
--- GitExtensions2.48, Git 1.9.4.msysgit.0, Microsoft Windows NT 6.1.7600.0

![image](https://cloud.githubusercontent.com/assets/1674106/4556110/9b749286-4ec5-11e4-8e72-f2eac8d0ad17.png)

![image](https://cloud.githubusercontent.com/assets/1674106/4556119/b4fd42fc-4ec5-11e4-8e9b-54a01c191652.png)

**Comment by RussKie** [comment]
Is this still an issue with the current version?

**Comment by eddrog** [comment]
Nope. I Think you can close the ticket
