### ISSUE TITLE
GitExtensions hangs when staging a lot of files

### ISSUE THREAD

**Issue by erik-kallen** [gitextensions/gitextensions#2478]
When I stage a lot of files using the stage all button (for example after updating a lot of nuget packages), GitExtensions tends to hang. However, if I manually run `git add -all`, that command completes (successfully) immediately

**Comment by webmaster33** [comment]
I also have this problem with Git Extensions v2.48.03.
It hangs when I want to commit more thousand files.

**Comment by jeroen-es** [comment]
Using the latest version of git extensions (3.00.00.4433 with git 2.19.1.windows.1) I still experience this problem: yesterday I tried to stage over 12000 files which made git extensions hang on a non-responsive commit window. After leaving it running for over 20 hours (!) I terminated git extensions and tried to do the same on the commandline using 'gitt add -A', which  completed in less than 10 minutes. So this issue still isn't resolved.

**Comment by vbjay** [comment]
Submodules are a great thing.

**Comment by jeroen-es** [comment]
Submodules are not usable in this case and also this isn't a solution to the problem that git extensions is having.

**Comment by vbjay** [comment]
No. My point is if you are getting updates from a separate project then use submodules to contain the changes.

**Comment by jeroen-es** [comment]
I get your point but submodules is not a solution in this case, as the external project is not a git project.

**Comment by vbjay** [comment]
Look I know this. It was an aside to help you out.

**Comment by jeroen-es** [comment]
Right, ok, no need to elaborate on that further then, as using the commandline is a working alternative solution.
I was just mentioning this since a search on this issue reveals a lot of closed topics about the same thing but the issue still exists.

**Comment by rboisvert-zmd** [comment]
Commited 1650 files, same issue.

**Comment by mstv** [comment]
Spawning Git.exe 1647 times takes *some* time... To combine these into less or even one Git command(s) might exceed the possible length of the command line. Perhaps the affected files could be written to a temporary list file which is can be read by Git.exe. A pull request would be welcome.

**Comment by Rob-bb** [comment]
> Right, ok, no need to elaborate on that further then, as using the commandline is a working alternative solution.
> I was just mentioning this since a search on this issue reveals a lot of closed topics about the same thing but the issue still exists.

One Year Later...  Yep, still a problem.  5 years and no fix in sight

**Comment by RussKie** [comment]
You're welcome to propose a solution

**Comment by Rob-bb** [comment]
> You're welcome to propose a solution

Sourcetree is what I came up with about half an hour ago. Do you have any other solutions?

The alternative is wondering if gitkracken has crashed or is actually still working. A progress bar or some other counter would help, a spinner could be spinning forever and not actually doing anything, how do you tell?

**Comment by RussKie** [comment]
If another app is doing a better job - great.

How many files are you staging?
How do you stage files?
Steps to reproduce?

You haven't provided any meaningful information other than "it is not
working".
