### ISSUE TITLE
GitExtensions apparently ignoring script failure

### ISSUE THREAD

**Issue by CyberiaResurrection** [gitextensions/gitextensions#2479]
Had a bit of a look through previous issues, didn't find anything similar.  I apologise if I've missed something.

I've been trying to add a pre-commit hook to lint php files before committing - the idea being if at least one file has a syntax error, abort the commit, don't hit the repo, and I avoid embarrassing myself by letting my co-devs see that I've let them see such a simple error.

On its own, the php lint file (see below) ran fine.

However, integration doesn't seem to work so well - when the hook fires and fails (nonzero return value), I first get a dialog with the output (telling me what file blew up) and a red cross in circle, which lead me to expect that, since the hook failed, nothing further would happen.  Nope.

After clicking 'OK', another dialog comes up telling me that, despite the earlier failure, it's busily committing the change that contains a syntax error.

I'm using GitExtensions 2.47.3 on a Windows Server 2012 box (don't ask).  I've probably missed something - does anyone have an idea _what_?  What's the bet it's something quite simple?

Script details, via Tools > Settings > Git Extensions > Scripts:
Name: PHP Lint
Command: php
Arguments: -d safe_mode=Off "C:\stuff\phplint_precommit.php"
Event: BeforeCommit

php file I'm using for the precommit hook:

``` php
<?php

$output = array();
$return = 0;
$php = 'c:/php/php.exe';

exec('git rev-parse --verify HEAD', $output, $return);
$against = $return == 0 ? 'HEAD' : '4b825dc642cb6eb9a060e54bf8d69288fbee4904';

exec("git diff-index --name-only {$against}", $output);

$filename_pattern = '/\.php$/';
$exit_status = 0;

foreach ($output as $file) {

    if (!preg_match($filename_pattern, $file)) {
        // don't check files that aren't PHP
        continue;
    }

    $lint_output = array();
    exec("{$php} -lf " . escapeshellarg($file), $lint_output, $return);
    if ($return == 0) {
        continue;
    }
    echo implode("\n", $lint_output), "\n";
    $exit_status = 1;
}

exit($exit_status);
```

**Comment by JuPrgn** [comment]
Same problem here with a script I am using to check the syntax of the code with clang-format before each commit. I have not found other way to stop the commit if the script returns an error.

I am surprised no one else asked for something similar since this original post. Is there a better trick to run pre-commit checks ? Should I use git hook isntead trying to achieve this with GitExtensions ?

**Comment by RussKie** [comment]
What version are using? How are you hooking up your script?

**Comment by JuPrgn** [comment]
I am using GitExtensions 3.1.1:6049.

The script is configured in `Repository `> `Repository settings` > `Git Extensions` > `Script` : 
Name : `Clang-format`
Command : `cmd`
Arguments : `/k FORMAT_AND_STAGE_BEFORE_COMMIT.bat`
On event : `BeforeCommit`

The script is working and well executed but when the first window (script output) returns a failure (`exit 1`) the commit is still done. I would expect a commit abort when the script returns a failure.

**Comment by RussKie** [comment]
3.1.1 is several years old. Please update.

**Comment by JuPrgn** [comment]
Sorry I didn't think my version was so old !

Same result with 3.4.3.9999.

**Comment by JuPrgn** [comment]
https://github.com/gitextensions/gitextensions/blob/e721aadada0ed6c0df8435c36df7357d2c8e957c/GitUI/CommandsDialogs/FormCommit.cs#L1323

Does not have return type to check script failure. Seems to be a simple fix I could propose a PR for this.

**Comment by RussKie** [comment]
If you provide a simple repro someone maybe able to investigate.
And you're welcome to propose a fix.

**Comment by JuPrgn** [comment]
Ok I will propose something in next days.

If someone want to repro this you have to add a script : 

Name : `Test`
Command : `cmd`
Arguments : `/k test.bat`
On event : `BeforeCommit`

With test.bat : `exit 1`

And commit something on your test repo.

You will see the script output with failure : 
![image](https://user-images.githubusercontent.com/20264907/111300353-49966c80-8651-11eb-852c-32553938195d.png)

Followed by the commit : 
![image](https://user-images.githubusercontent.com/20264907/111300414-57e48880-8651-11eb-9532-fbb76295afc7.png)
