### ISSUE TITLE
VS-Plugin not deinstalled correctly

### ISSUE THREAD

**Issue by Niko-O** [gitextensions/gitextensions#2481]
I have deinstalled GitExtensions and GitBash via the "Deinstall Programs"-dialog in the controlpanel, but there are still at least some remnants in VisualStudio.
In my case it's context menu entries:
GitExt: Diff
GitExt: File history
GitExt: Reset file changes
http://puu.sh/c8HN7.png

**Comment by gerhardol** [comment]
The VS addin for VS2013 and earlier is removed from master and this is not planned to be fixed in 2.5x branch
