### ISSUE TITLE
Copying text from diff copies with LF line ending

### ISSUE THREAD

**Issue by justanotheranonymoususer** [gitextensions/gitextensions#2488]
Hi, 

All my projects use CRLF line endings, which are the default in Windows. The issue I'm having is that when copying code from gitextensions edit boxes (e.g. when viewing diff or history), it's being copied with LF line endings. This causes VS to show a message when the file is opened. Also, it causes gitextensions itself to show a warning when committing this file.

**Comment by justanotheranonymoususer** [comment]
Sorry for nagging, but... any news on this?
Seems like a trivial bug, but I encounter it quite often, and it's a pain in the ass to fix these line endings every time.

**Comment by justanotheranonymoususer** [comment]
Excellent, thanks! Now, if only a new version was available for downloading... :)

**Comment by vbjay** [comment]
You can build from source and install the MSI. Just install wix toolset.
