### ISSUE TITLE
Filtering by git notes doesn't work even if ShowGitNotes is enabled

### ISSUE THREAD

**Issue by Radrik5** [gitextensions/gitextensions#2494]
When ShowGitNotes is disabled, Git Extensions adds "--not --glob=notes --not" to "git log" command line.

When ShowGitNotes is enabled, Git Extensions doesn't add "--not --glob=notes --not" to "git log" command line, but it's not enough to enable filtering by git notes.

Git Extensions should also add "--notes" to the command line.

test.git.notes $ git log --format="%H" --all --grep="0403"
test.git.notes $ git log --format="%H" --all --notes --grep="0403"
3d5fd5d0ce86cf2e02ca84fdd2239a8332f47cd0

**Comment by matyasbach** [comment]
This can be closed, it works well. Probably fixed by #10129
