### ISSUE TITLE
2.47 cannot launch git-credential-winstore.exe correctly

### ISSUE THREAD

**Issue by dafeifei** [gitextensions/gitextensions#2497]
The default setting has a problem:
![git issue1](https://cloud.githubusercontent.com/assets/9149824/4764427/d84314e2-5b24-11e4-9d16-cfebea8aaa18.JPG)
Change it to:
`helper = !\"C:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe\"`
then it works correctly.

**Comment by koppor** [comment]
(Hint for all googlers hitting this issue when switching from 32bit git to 64bit git)

Open [.gitconfig](http://stackoverflow.com/questions/2114111/where-does-git-config-global-get-written-to) by [git config --global -e](http://stackoverflow.com/a/17619024/873282) and change the path accordingly.
