### ISSUE TITLE
Feature Request: Repo Removal

### ISSUE THREAD

**Issue by MilesInsanity** [gitextensions/gitextensions#2502]
I would like to delete a repository from my system using the GUI but have thus far failed to find this function within any of the menus. Proposition seen in attached photos.

I didn't want to post this on the issue tracker but couldn't find a contact method.
![delete repo](https://cloud.githubusercontent.com/assets/8846839/4793072/40322db8-5deb-11e4-99a0-7ff1d8716383.jpg)

![delete repo 2](https://cloud.githubusercontent.com/assets/8846839/4793074/443fa264-5deb-11e4-9c51-bd6bc057a47e.jpg)

I'm thinking there is a method, there has to be. The only thing I can think to do is manually delete the folder I've downloaded the repo in. ( I can, but then I'd have nothing to do :P)

Thank you for any assistance.
Miles

**Comment by jackbatzner** [comment]
I think there are two options to delete the Git repo for this feature request. In my experience with the tool I've run into two scenarios where this would be helpful to have:
1. When I want to delete the repo itself, remove the ".git" folder and just keep the files
2. When I want to delete the whole folder including the files.

So maybe there could be two options listed above or the "Remove" option would provide a GUI that allowed the user to "Remove selected repository" with an option to "Delete folder containing repository".

**Comment by RussKie** [comment]
You can open the folder and delete the folder or files as necessary.
