### ISSUE TITLE
Add Visual Studio (vsdiffmerge) as a Mergetool and Difftool

### ISSUE THREAD

**Issue by adamvoss** [gitextensions/gitextensions#2505]
I am not sure what caused it, but somehow my git settings were changed from what I configured in GitExtensions to using Visual Studio.  I will be changing my setting back, but if I did not already have an external tool I do think VS can be a good option and think it should be in the list provided by GitExtensions.

Here are the settings (from `git config --list`) for vsdiffmerge

```
diff.tool=vsdiffmerge
difftool.prompt=true
difftool.vsdiffmerge.cmd="C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\vsdiffmerge.exe" "$LOCAL" "$REMOTE" //t
difftool.vsdiffmerge.keepbackup=false
difftool.vsdiffmerge.trustexistcode=true
merge.tool=vsdiffmerge
mergetool.prompt=true
mergetool.vsdiffmerge.cmd="C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\vsdiffmerge.exe" "$REMOTE" "$LOCAL" "$BASE" "$MERGED" //m
mergetool.vsdiffmerge.keepbackup=false
mergetool.vsdiffmerge.trustexistcode=true
```

**Comment by Dark-Water** [comment]
Hello,  

The parameters are not correct (but always in the first search results :-( )

It should be:

For the merge
`/m /t "$LOCAL" "$REMOTE" "$BASE" "$MERGED"`

For the diff
`/t "$LOCAL" "$REMOTE"`

* LOCAL (source) is left
* REMOTE (target) is right
* BASE (and MERGED) are below

t = open in a provisional tab
m = merge operation

It works on 2010, 2012, 2013, 2015

**Comment by RussKie** [comment]
This is available in the current version.

**Comment by aaron-ni** [comment]
As a warning, setting `diff.tool` causes issues in **Visual Studio 2017 Update 9.7** and **Visual Studio 2019 Preview 4/RC** (like merges outputting a blank file rather than the merged content). It is much safer not to modify diff.tool and instead invoke this via `git difftool --tool vsdiffmerge`.
