### ISSUE TITLE
Abort rebase in "Resolve merge conflicts" does not work

### ISSUE THREAD

**Issue by kasal** [gitextensions/gitextensions#2510]
Reproducer:
1) create a branch with one commit
2) rebase the branch elswhere, so that a conflict appears
3) in dialog "Rebase" hit "Solve conflicts"
4) in dialog "Resolve merge conflicts", hit "Abort rebase"
5) say Yes to both warnings

Bug:
the rebase has not been aborted

Expected:
should abort the rebase

**Comment by itsho** [comment]
1. this is a very old issue and I want to hope that the Author got it resolved.
2. I suspect that the source of the issue was an environment issue (index.lock etc.)
3. to make it clear - it does not reproduce on Git Ext 3.4.2.9737 (Windows 10 1809 17763.1282).

**Comment by gerhardol** [comment]
Thanks @itsho, there are too many open issues...

**Comment by kasal** [comment]
Thanks for closing this, I'm the OP.
I'm currently using 3.0 pre-release with git 2.27 and I can no longer reporduce the bug.
