### ISSUE TITLE
asp.net project not working

### ISSUE THREAD

**Issue by Johan1974** [gitextensions/gitextensions#2511]
Hello,

I have a simple asp.net wen project on one machine and pushed this to a central repository. Now when i clone this project to a different machine there is no problem. Only when i try to open the sln project file  i get the message 

"One or more projects in the solution were not loaded correctly"

"http://localhost:60612 : error  : Error opening web http://localhost:60612. The Web site 'http://localhost:60612' could not be found."

![image](https://cloud.githubusercontent.com/assets/8274075/4907440/f76d0b34-6461-11e4-9af6-18672675590c.png)

I know with a normal c# application i can do this with no problem. Are there some settings in git i need to consider when working with asp.net projects?

--- Visual Studio 2013 c# , GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.3.9600.0

**Comment by RussKie** [comment]
This is nothing to do with GE.
Closing due to age.
