### ISSUE TITLE
Pure C# backend for GitExtensions (with NGit)

### ISSUE THREAD

**Issue by ArsenShnurkov** [gitextensions/gitextensions#2516]
I know 3 types of backends:
1) external command line tool (which is called with environment variables and streams redirection)
2) native library wrapper (libgit2 - https://github.com/libgit2/libgit2sharp)
3) pure C# code (NGit - https://github.com/mono/ngit , which is newer than frozen GitSharp project)

What is the state of implementation of the third way?

**Comment by jbialobr** [comment]
Closing as NGit seems to be dead.

**Comment by ArsenShnurkov** [comment]
awww! anyway we have this place to continue discussion and can reopen it later

**Comment by DanRigby** [comment]
It should be noted that Visual Studio itself started with a combination of #1 and #2 but has recently moved to just using the stand alone git executable. https://blogs.msdn.microsoft.com/visualstudioalm/2017/03/06/new-git-features-in-visual-studio-2017/

**Comment by KindDragon** [comment]
We can use libgit2 for some tasks like revision graph in the future
