### ISSUE TITLE
Sorting files in Commit screen

### ISSUE THREAD

**Issue by mgmagi** [gitextensions/gitextensions#2518]
--- GitExtensions2.48, Git 1.9.4.msysgit.0, Microsoft Windows NT 6.3.9600.0

Files in "Unstage"d portion of the "Commit to..." dialog (upper left corner panel) are sorted alphabetically. Is there way to sort them by date? If not, it's a major issue (for me at least) which sends me back to flat file view of the old WinCVS application where most recently modified files are clearly shown in red, significantly easing the version control management.

**Comment by eli-b** [comment]
I'd also appreciate an option to sort by status (untracked/modified/added/...) and by file name (not the full path) like the sort options in Atlassian's SourceTree.

**Comment by glen-nicol** [comment]
One of the first things I noticed being different in 3.0 is a different sort on this screen. I personally much prefer alphabetically(the old way) over by status (seems to be the new way). Not sure if that is considered a bug/oversight or a feature of 3.0. If it is a feature that is not planned to be changed back I would gladly do work to add the sorting functionality requested in this issue.

**Comment by gerhardol** [comment]
The change was not really planned, but seen as a feature. Could be changed. I suggest you open a new issue about this.

**Comment by glen-nicol** [comment]
A new issue for what exactly?

Putting the previous default(alpha) back? 
Or for implementing sorting options?

**Comment by RussKie** [comment]
Please put your proposals forward and we can discuss them

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
