### ISSUE TITLE
gitext.sh file is in DOS format.

### ISSUE THREAD

**Issue by JerryLumpkins** [gitextensions/gitextensions#2532]
The file gitext.sh bundled in the mono.zip version has 2 issues with it:
1. The user has to run chmod u+x gitext.sh to set it to an executable.
2. (More important) The script fails unless you run dos2unix on it because the file has DOS style new lines in it. (carriage return + line feed instead of the unix line feed only)

Thanks for your efforts!

**Comment by JerryLumpkins** [comment]
It seems like changing the newline on the .sh file should be a very easy thing to fix so that it works in linux without the user having to fix the file.

**Comment by tonyeung** [comment]
for posterity's sake:
```
$ head -1 gitext.sh | od -c 
0000000   #   !   /   b   i   n   /   b   a   s   h  \r  \n
0000015
$ cp gitext.sh _p4 && tr -d '\r' < _p4 > gitext.sh && rm _p4
$ head -1 gitext.sh | od -c
0000000   #   !   /   b   i   n   /   b   a   s   h  \n
0000014
```
notice second run has no \r
