### ISSUE TITLE
Merge diff silently switches to diff to 2nd parent when 1st is the same

### ISSUE THREAD

**Issue by max630** [gitextensions/gitextensions#2535]
When 1st parent of merge commit happens to be the same as the commit (strategy-ours or already existing change), the GitExtensions shows difference to the second one, with almost no indication that it does so (there is note "Diff with parent....", but it is not informative at all). Probably there have been some reasons to do so, but it is very confusing.

**Comment by gerhardol** [comment]
Empty diff are not shown, but the first revision in the diff is always visible in merge commits.
(The first selected for non-merge commits is listed also in #4569)
