### ISSUE TITLE
Git Extension crashes when pasting from clipboard

### ISSUE THREAD

**Issue by mbostwick** [gitextensions/gitextensions#2537]
The text was just a small text being copied and pasted(I could have had other objects in my clipboard..) 
Restarting and selecting other things in my clipboard.

![pasting_clipboard_error](https://cloud.githubusercontent.com/assets/547590/5306989/cd7e211c-7bce-11e4-971f-f3a9586ced65.png)
![pasting_clipboard_error2](https://cloud.githubusercontent.com/assets/547590/5306990/cd7fd318-7bce-11e4-8b7e-e39b4d5c2a46.png)

**Comment by mrexodia** [comment]
Not releated to rich text, I also tried with plain text from notepad. Same problem.

**Comment by mbostwick** [comment]
Didn't do much research but if you look at the exception the error says its from set data object (inside git extension) . Doing a quick search of the code-https://github.com/gitextensions/gitextensions/search?utf8=%E2%9C%93&q=SetDataObject there is only one place in git extensions where that system method is called. Which is the CopyToClipboard in the ReleaseNotesGenerator ..now I it may be a good idea to put an exception catch there(just in case there is an issue setting the clipboard on the system..) (which I think would stop this bug, and the other bug which I think wasn't because of a pull request but because of a location clicked..) ...

However, going one step further, and looking at whats calling CopyToClipBoard in ReleaseNotesGenerator -https://github.com/gitextensions/gitextensions/search?utf8=%E2%9C%93&q=CopyToClipboard&type=Code ... I would guess its the click to handler on menu items..https://github.com/gitextensions/gitextensions/blob/cb5f00c228590d5fefad2fffe741e1d684d6eb0a/GitUI/UserControls/RevisionGridClasses/CopyToClipboardMenuHelper.cs#L38 ...keep in mind I dont know this code very much at all though, and this was all of 10 minutes of research (so its mostly just guessing..) ..

**Comment by ghanique** [comment]
Did the first line exceed 50 characters, so that Git Extensions will make
the remaining characters red?

**Comment by mrexodia** [comment]
@ghanique it also crashes when pasting 3 characters on an empty line

**Comment by vbjay** [comment]
Why don't we do a debug build and try to make it crash?

**Comment by mrexodia** [comment]
In debug mode it works fine. The problem is in the 'fix' of issue #139.

https://github.com/gitextensions/gitextensions/blob/master/GitUI/SpellChecker/EditNetSpell.cs#L665

You cannot access clipboard data from a non-STA thread it seems: http://stackoverflow.com/questions/518701/clipboard-gettext-returns-null-empty-string

I'm working on a fix right now.

**Comment by mrexodia** [comment]
Alright, I cannot fix it. Here is a sample program that reproduces the crash on Windows 8.1 x64 for someone to continue. For now I just recommend adding a try/catch block around the clipboard functions:

https://gist.github.com/mrexodia/d5853552677f16ad0253

**Comment by linquize** [comment]
Methods in `Clipboard` class may throw exception.
It is better to add a try-catch block around it.
If failed, retry the operation later, say delay 1 second.

**Comment by mrexodia** [comment]
@linquize The methods don't throw an exception, the GetText method always returns null. Try my example.

**Comment by linquize** [comment]
http://msdn.microsoft.com/en-us/library/kz40084e%28v=vs.110%29.aspx
The method `Clipboard.GetText()` has Exceptions

**Comment by mrexodia** [comment]
I read the documentation, but the GetText method is simply not returning any values when not debugging

**Comment by ghanique** [comment]
Then if GetText returns null, then wouldn't SetText(null) cause the
exception? If that is true, wouldn't it be sufficient to assert that text
!= null before you call SetText(text)?

**Comment by mrexodia** [comment]
Yea.. that's indeed the problem. But adding exception handlers will break pasting completely :)

**Comment by mbostwick** [comment]
full stack trace.. 
![full_stack_trace_of_bug](https://cloud.githubusercontent.com/assets/547590/5837898/e14bba16-a148-11e4-8237-32c4248ebfeb.png)

**Comment by ghanique** [comment]
Why do we get the data from the clipboard and instantly put it back?

**Comment by mrexodia** [comment]
@ghanique To remove images copies from OneNote from the clipboard or something (see issue #139)

**Comment by mbostwick** [comment]
So to reproduce the bug, copy an image(from something like google image search in firefox), then copy text using cntl+v, this made it happen for me every time(however it would only happen once, so if I hit x it wouldnt happen again) .

**Comment by vbjay** [comment]
Why don't we use
https://msdn.microsoft.com/en-us/library/system.windows.forms.clipboard.containstext(v=vs.110).aspx
  and
https://msdn.microsoft.com/en-us/library/system.windows.forms.clipboard.gettext(v=vs.110).aspx

**Comment by mrexodia** [comment]
vbjay: 'we' use those....

**Comment by vbjay** [comment]
Sorry. Was on phone. Couldn't look at code then. The image issue doesn't
make sense. It shouldn't crash if there is image data also.

**Comment by mbostwick** [comment]
So an additional note, I think the reason there is an issue setting my clipboard actually relates to virtualbox. There is still a bug with git extension, in that if there is an issue with setting the clipboard it sends a fatal exception. However the setting operation failure actually relates to git extension clearing the image clipboard, which to me it should be leaving the clipboard alone, and just use the get text..

**Comment by jamesjrg** [comment]
As wtih mbostwick, copy/paste doesn't work for me in git extensions as long as I have VirtualBox running with copy/paste support enabled

**Comment by EbenZhang** [comment]
Seems #2847 has fixed the settext issue.

**Comment by ranshalit** [comment]
Is this issue fixed ? I get this crash in 2.50.02

**Comment by mrexodia** [comment]
I didn’t get it in quite a long time, but I also didn’t try too hard to
reproduce it.

**Comment by RussKie** [comment]
@ranshalit: if you have an issue please provide tangible information for us to investigate

**Comment by masko23** [comment]
I always has this issue when trying to copy to clipboard the name of a branch. I didn't look the source of gitextension yet but many of my coworkers have the same issue with this function. The name of the branch is copied to the clipboard though but gitextension crashes.
