### ISSUE TITLE
see which files changed

### ISSUE THREAD

**Issue by BeSt1979** [gitextensions/gitextensions#2541]
Perhaps I just didn´t find it...

It would be qonderful to have a possibility to see, what files have changed since last commit / push. In the GitExtensions the "Commit-Button" change from green icon to red icon with number of changed files in brackets. That would be nice.

Much more perfect would be to see a special mark near changed files in the project explorer.

If there is a possibility to do one of these things, I would appreciate every help....

**Comment by vbjay** [comment]
Visual studio 2017 solution explorer has a filter for changed files.
