### ISSUE TITLE
Crash when entering an unexisting branch in the branch filter edit box in 2.48.02

### ISSUE THREAD

**Issue by jeffqc** [gitextensions/gitextensions#2544]
Reproduction:

- Open any repository with GitExtensions
- Enter "asdf" in the branch filter edit box (note: any unexisting branch name will do)
- Press "Enter"

Crash "System.ArgumentNullException" in Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d

**Comment by webmaster33** [comment]
I really need the fix for "Crash when entering an unexisting branch in the branch filter edit box" bug.

When will be 2.48.04 released?
