### ISSUE TITLE
Pushing a tag should allow the credentials window to be opened

### ISSUE THREAD

**Issue by armstnp-einc** [gitextensions/gitextensions#2551]
--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

**Issue:**
My local SSH private key credentials had not yet been entered in.  Normally, pushing new objects to a remote repository automatically triggers display of the Pageant credentials dialogue.  However, pushing a new tag simply requests the SSH key without opening the credentials window, forcing the user to cancel the operation and enter in the credentials externally.

**Repro:**
Push a tag to a remote server with an SSH key that you have credentials to, but have not yet authorized for use in your current computing session.

**Unknowns:**
  * This may not be applicable to all auth formats; it may be SSH only, or it may include HTTPS as well.
  * This may not be applicable to all SSH clients; I am currently using an unknown version of PuTTY / pageant to manage my private keys locally.
  * This may not have been a feature of Git Extensions in the first place, but rather a happy side-effect of using the above applications.  If so, close now.

Let me know if there's any other aspects or details I should fill in.

**Comment by KindDragon** [comment]
Cannot reproduce
