### ISSUE TITLE
Please find a new host for the compiled binaries

### ISSUE THREAD

**Issue by DaveVdE** [gitextensions/gitextensions#2552]
Today I wanted to update to the latest version of Git Extensions through the "check updates" function in the menu. This redirected me to the official download page on SourfeForge.net.

What I saw there was baffling. An entire page filled with sponsored download buttons ready to consume my soul. By the time I figured which buttons were ads and which were not my browser fortunately started downloading the installer automatically. 

While downloading, I cared to investigate why a link to 7zip would be marked as "sponsored", only to find out that someone had taken the 7zip source and turned it into malware and offers it for download at http://7zip.tv! I was disgusted that SourceForge would even allow such an inexcusable ad. 

When the download was finished, I remembered hearing stories on how CNET would modify installers to add their own malware. At that time I was fearful of what the "official installer" might do.

People suggested I use Chocolatey. While I applaud such a project, I'm sure there's a great deal of developers who are unaware or unaccustomed to it. Besides, this page is what the software itself guides the user to.

So please, try to find a more credible host for your binaries.

**Comment by KyleSanderson** [comment]
SourceForge actually supports and sponsors malware, FileZilla takes full advantage of this unfortunately. Please find a new host that isn't the exact same as CNet.

**Comment by pmiossec** [comment]
>Once all the users are used that we have the official page for download on SourceForge . There users wrote to us good recommendations that are useful for new users.

Perhaps you're right that you can't leave **now** sourceforge but surely, we should begin the process to move away. Perhaps stopping to make it the number one of the download places and removing all the links toward it and pointing somewhere else. 


>Also, SourceForge provides statistics of downloads which is not available at GitHub

Even if I admit that is surely not as simple as with sourceforge and I don't know which statistics you want but you could have the download count using the github api... 
I could look for the url if you are interested.

**Comment by pmiossec** [comment]
Here: https://developer.github.com/v3/repos/releases/#get-a-single-release

**Comment by KyleSanderson** [comment]
http://seclists.org/nmap-dev/2015/q2/194

Now would be a very good time to leave SourceForge...

**Comment by KindDragon** [comment]
I uploaded the latest release on GitHub for start https://github.com/gitextensions/gitextensions/releases

**Comment by vbjay** [comment]
FYI.http://arstechnica.com/information-technology/2015/06/sourceforge-locked-in-projects-of-fleeing-users-cashed-in-on-malvertising/

**Comment by drewberes** [comment]
I am glad that I found this thread and the alternative download links provided by KindDragon. SourceForge has bankrupted the trust of the developer community.

**Comment by DaveVdE** [comment]
It appears that the official downloads have moved, so I suppose this issue can be closed. How to deal with SF's ranking in Google is another matter.

**Comment by vbjay** [comment]
Too bad we can't make it do a http 301.  Google would catch that in a
heartbeat.
