### ISSUE TITLE
App hangs for a while with large repo

### ISSUE THREAD

**Issue by ablam** [gitextensions/gitextensions#2555]
Each time gitext window gets focus (even if nothing has changed), CPU usage jumps to 100% and app hangs for about 10s. I'm working with large project ~7GB. All performance related options are already disabled.

**Comment by tnodir** [comment]
QtBase git opens very slow with 2.48.03: https://git.gitorious.org/qt/qtbase.git

**Comment by ablam** [comment]
I've commented out UpdateSubmoduleList() call from FormBrowse.cs:OnActivate() and it works with lightspeed :)

**Comment by KindDragon** [comment]
This should be fixed in 2.48.04

**Comment by Olivloliv** [comment]
I'm experiencing the same issue with 2.49a1. Is it still an opened issue ?

**Comment by KindDragon** [comment]
> Check Tools > Gitcommand log, it should display how much each command take time.

Try that

**Comment by Olivloliv** [comment]
The logs tells me that git diff on every submodules is taking much time (up to 18s for one submodule). Since it is done on every call to  FormBrowse.cs:OnActivate() the UI becomes unresponsive.
Commenting out UpdateSubmoduleList() in OnActivate() solves the problem for now.
