### ISSUE TITLE
Visual Studio toolbar always disabled

### ISSUE THREAD

**Issue by strice** [gitextensions/gitextensions#2558]
I just updated to 2.48.03 and now the GitExtensions toolbar in both Visual Studio 2012 and 2013 is grayed out/disabled. The GitExt menu works as expected. I've tried re-adding the toolbar but it's always disabled.

**Comment by NIA** [comment]
> removing all of the GitExtension files from the **Addins** folder, launch VS, then re-adding the files, and relaunching VS

This is `My Documents\Visual Studio 20XX\Addins` folder, to be specific. Worked for me.

**Comment by hamparawa** [comment]
That worked for me too. Guess this needs to be added to the FAQ section. :)
