### ISSUE TITLE
Travis CI is not reliable

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#2561]
- Fails to connect to the nuget feed.
-  /home/travis/build/gitextensions/gitextensions/Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityIntegration.csproj:  warning : Could not find project file /home/travis/build/gitextensions//.nuget/NuGet.targets, to import. Ignoring. 

several more like this where the solution directory is wrong.

**Comment by KindDragon** [comment]
Maybe try build scripts from https://github.com/libgit2/libgit2sharp/blob/vNext/.travis.yml ?
They, as I understand it, try to download latest version of mono from mono-project.com.

**Comment by fraga** [comment]
Interesting, will look into that

**Comment by fraga** [comment]
@KindDragon I have merged master branch and travis built successfully
https://travis-ci.org/fraga/gitextensions/builds/55383471

Can you please issue a 'rebuild' command to travis?

**Comment by m08pvv** [comment]
Is this issue related to [PR#3623](https://github.com/gitextensions/gitextensions/pull/3623) ?

**Comment by jbialobr** [comment]
No, it is rather the other way around
