### ISSUE TITLE
Feature request: allow for search in the commit dialog

### ISSUE THREAD

**Issue by mmoayyed** [gitextensions/gitextensions#2569]
Sometimes, when you have made a sweeping change (via search and replace for instance) to the entire codebase, the commit dialog shows X number of changed files. It's useful to be able to search for a particular file in the list that is modified and review what's changed.

**Comment by vbjay** [comment]
![image](https://cloud.githubusercontent.com/assets/3629489/5604714/b7b3563c-939c-11e4-8f67-da37b04889bb.png)
![image](https://cloud.githubusercontent.com/assets/3629489/5604716/eeee32d4-939c-11e4-87ff-7eb41c8fa9fd.png)
If you are looking for text in the file press ctrl+f
