### ISSUE TITLE
Git Extensions won't restore from minimized state sporadically

### ISSUE THREAD

**Issue by temp4746** [gitextensions/gitextensions#2570]
I somtimes seem to encounter an issue where Git Extensions won't restore from a minmized state (mostly when having more than one Git Extenions window open).

This means that I click it's thumbnail in the taskbar and it won't restore, instead remaining minimized.

This started happening after installing Git Extensions v2.48.03. I tried reinstalling the older version but it still seems to be happening.

Windows 7 SP1 x64.
Git Extensions v2.48.03
Git 1.9.4 preview20140929
KDiff3 as 0.9.98 as installed by Git Extensions.
 git-credential-winstore 1.4 as installed by Git Extensions.
Using Pageant/Plink bundled with Git Extensions for Git SSH access.

**Comment by leekelleher** [comment]
I am experiencing the same issue with v2.48.03. Same as @tverett, I only experience this when I have more than 1 GitExt window open. (Thanks to @sharwell for your tip on restoring focus)

Steps to reproduce:

1. Open multiple instances of GitExt (at least 2 windows)
2. Minimise all windows
3. Try to view any of the GitExt instances (either by restore or maximise)
4. Windows 8 will play a beep/ping sound in the background and the GitExt instance remains minimised.

Windows 8.0 x64
Git Extensions v2.48.03

**Comment by ghanique** [comment]
Could it be, by any chance, that one of those windows has a modal window
open, like a commit window?

**Comment by aslater** [comment]
I just verified that this happens with no modal windows open

**Comment by johanvanr** [comment]
Reproduces here too:
GitExtensions: v2.48.03
OS: Win7 64bit.
Misc: 2 window instances open; no open modal windows; occurs when using 1 monitor or 2 monitors.

**Comment by bplatypus** [comment]
Still no fix or workaround for this? Thanks

**Comment by EbenZhang** [comment]
@bplatypus pull request #2862 fixes it, but hasn't been merged.

**Comment by bplatypus** [comment]
@EbenZhang ok, thanks ;-). Will wait for it.

**Comment by mitcht** [comment]
Still a problem.

**Comment by EbenZhang** [comment]
@mitcht
Which version of gitextensions and operating system are you using?

**Comment by mitcht** [comment]
I'm running Windows 10 Pro with Version 2.48.05 of git extensions.

**Comment by EbenZhang** [comment]
It is fixed in 2.49 which hasnt been released.
If it really bothers, you can try my unofficial [release](https://github.com/ebenzhang/gitextensions/releases/latest)

**Comment by mitcht** [comment]
I may do that.  I work on 4 or 5 repos at once usually, representing different angular directives.  Switching between the instances of git extensions can be surprising sometimes.  I have learned to double check that the correct one is maximized by hovering, right clicking, and restoring. :)

**Comment by bbrandt** [comment]
I've found that after this occurs, this will bring the GitExtensions window to the front:

1. Click the icon for GitExtensions in the windows task bar (the window will not appear)
2. Press <kbd>![Windows Key][newwinlogo]</kbd>+<kbd>Up Arrow</kbd>

One less key press than the previous workaround, if your on Windows.

[newwinlogo]: http://i.stack.imgur.com/B8Zit.png

**Comment by MaxKot** [comment]
This bug has reappeared between v3.3.1 and v3.4 RC1. Please reopen the issue.

**Comment by RussKie** [comment]
Please raise a new issue and provide a detailed report. Thanks.

**Comment by pgarbo** [comment]
I'm having this issue in Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
See #10398 for a recent discussion and a kind of workaround

**Comment by gnordlan** [comment]
I see it too.
Windows 11.

One GE window. Open a repo. Minimize GE.
Click on the empty desktop to put focus there.
Click on the GE icon on the taskbar.
**Expected**: GE window restores, **Actual**: "do-de-do" noise, and GE does not restore

Click on the empty desktop to put focus there.
Click on the GE icon on the taskbar.
**Expected**: GE window restores, **Actual**: "do-de-do" noise, and GE does not restore
Click on the GE icon on the taskbar again, while the focus is on that button. GE restores.

Minimize GE.
Click on the GE icon on the taskbar.
**Expected**: GE window restores, **Actual**: "do-de-do" noise, and GE does not restore
Click on an empty area of the taskbar. Click on the GE icon on the taskbar.
**Expected**: GE window restores, **Actual**: "do-de-do" noise, and GE does not restore
Wait any amount of time, but keep the "focus" on the GE taskbar button.
Click on the GE icon on the taskbar. GE Restores.

Minimize GE.
Hover over the GE icon on the taskbar, don't click. See the preview window of the GE window.
Move your mouse up and click the preview hover.
**Expected**: GE window restores, **Actual**: "do-de-do" noise, and GE does not restore

My best guess is that GE can't restore from the taskbar unless it already has focus on the taskbar for some reason.
Alt-tab works, without the focus issue.
Task Manager "Bring to Front" and "Switch To" both work.
If you right click the preview window, it puts the taskbar focus on the GE icon, and selecting "Restore" from the popped-up menu works. (I think it's that focus change from the RClick that makes it work)

**Comment by gerhardol** [comment]
Take the discussion in #10398.
From the application perspective, there are Windows messages that are not received (NativeMethods.WM_ACTIVATEAPP).
