### ISSUE TITLE
Is this project vulnerable to http://article.gmane.org/gmane.linux.kernel/1853266

### ISSUE THREAD

**Issue by wizzyrea** [gitextensions/gitextensions#2574]
Just wondering if this project is vulnerable to http://article.gmane.org/gmane.linux.kernel/1853266.

If it is, you may want to update the internal git client.

Cheers,
Liz

**Comment by cniweb** [comment]
When there is a new release with this fix?

**Comment by blackbirdui** [comment]
I think my team would feel more confident installing MSysGit 1.9.5 if it was packaged with a new version of Git Extensions (which would imply that you guys built and tested Git Extensions with the updated MSysGit, etc.)  Do you guys plan to put out an update any time soon?

Thanks a bunch!
BC
