### ISSUE TITLE
GitExtensions -> File History shell plugin returns commits for the wrong file

### ISSUE THREAD

**Issue by aregier** [gitextensions/gitextensions#2589]
I noticed an issue today where the GitExtensions -> File History command returns commits for a different file than the one that was invoked using the right mouse button on the Windows platform.  I have not tested this on a linux os yet.  The two files are very similar, and no rename operations exist between these two file names for their history.

This same behavior exists when invoking GitExt: File History from inside Visual Studio 2013

Note that verification using 'git log' on the commandline returns the correct history/commits for each of the two files, so it appears this is specific to Git Extensions.

![inupdatescriptwithcontentexecutor_git_history](https://cloud.githubusercontent.com/assets/8008315/5579817/480183f2-9006-11e4-9ff1-94afa17ab801.png)
![inupdatescriptwithcontentexecutor_gitext_filehistory incorrectcommitsforthisfile](https://cloud.githubusercontent.com/assets/8008315/5579818/48026f06-9006-11e4-9e08-125098c65170.png)
![inaddscriptwithcontentexecutor_git_history](https://cloud.githubusercontent.com/assets/8008315/5579819/4803aede-9006-11e4-8ba1-2caa5bd077f1.png)
![inaddscriptwithcontentexecutor_gitext_filehistory](https://cloud.githubusercontent.com/assets/8008315/5579816/47ffd34a-9006-11e4-8851-e0d475c36882.png)

**Comment by KindDragon** [comment]
Done in PR #2512
