### ISSUE TITLE
Visual studio SSIS Integration not working

### ISSUE THREAD

**Issue by MalcJ** [gitextensions/gitextensions#2590]
I have installed Extensions 2.48.03 and cloned an existing MS SSIS project (integration services) - this works fine.

When I open the project in VS 2010 I cannot use the browse repository function unless all files are closed (.dtsx). When I can browse it does not open the repository directly, I have to open manually.  None of the other buttons work (commit/push/pull). 

The changes are recorded and can be pushed using the standalone extensions GUI but not from within VS. Am I doing something wrong?

**Comment by azarkevich** [comment]
Can you provide more details about  MS SSIS projects? I can try debug it, but not found such project type in my VS 2010.

**Comment by MalcJ** [comment]
I have tested with a different file type so I don't think it's SSIS related.

-Created new repository using Git Extensions in d:\test
-Create new solution and add a text file, save to d:\test

Changes are recorded but I can only browse the repository when the the file is open and selected in the solution explorer but all other icons are grayed out. If I select the top level i.e solution, all buttons are active but do not work. 

[Screenshot 1](http://f0re.co.uk/1.jpg)
[Screenshot 2](http://f0re.co.uk/1.jpg)

I can only commit from within GitExtensions itself.

**Comment by azarkevich** [comment]
I known this problem ant it is easy to fix.
For some reason buttons (Commit, Pull, Push ... ) disabled when selected solution item of specific type Folder, ...

I commit fix soon, though I do not sure it this behavior is not by design.
