### ISSUE TITLE
Performance of navigating far back in history after refresh for large repo

### ISSUE THREAD

**Issue by vzabavnov** [gitextensions/gitextensions#2594]
I have huge repository (35K+ items). I have two branches: main and mnt. When I switch from main to mnt I am not able to navigate to mnt – the commit’s lists does not show that branch and does not allow scrolling. Only when I do Context Menu->View->Show Current branch only I am able to see that branch.
![image](https://cloud.githubusercontent.com/assets/2672340/5597852/0c6fa70a-9278-11e4-9ae2-83b524ca7ba1.png)

**Comment by spdr870** [comment]
Gitextensions starts loading the first page tot show quick results. Then it
continues tot load the remaining commits. It think you should wait longer
untill all is loaded. I work on a large repo myself, many commits andere
over 1500 branches. Memory usages climbs to around 550mb.

Please try tot wait a few minuten. You can watch the memory usageto ensure
it is still loading. It woulb be interesting tot know hoe long it takes.

Henk

Op 2 jan. 2015 18:08 schreef "Vadim Zabavnov" <notifications@github.com>:
>
> I have huge repository (35K+ items). I have two branches: main and mnt.
When I switch from main to mnt I am not able to navigate to mnt – the
commit’s lists does not show that branch and does not allow scrolling. Only
when I do Context Menu->View->Show Current branch only I am able to see
that branch.

**Comment by vzabavnov** [comment]
Hi Henk,

I loaded up… took 10+ minutes, memory usage 200+ mb

 

I think what need to be added – the some kind of notification that it still loading and additionally when do navigation via “Navigate->Go to commit->Go to branch” it should stuck until it loads, with notification message.

 

 

 

 

 

With Best Regards

 <mailto:zabavnov@gmail.com> Vadim Zabavnov

**Comment by vzabavnov** [comment]
Hi Guys,
No, I don't the idea to load in background more and more. it should be implemented different way. 
Check it out: I checkout branch and want to go to particular tag. I can not do it now I still need to wait, but!!!! now I need to monitor when the tree is completed to upload and only after that I can navigate to my label

**Comment by drewnoakes** [comment]
@vzabavnov if you're still working with this repository, could you try the latest master code and see if there's any improvement? We've done quite a lot of performance work. The underlying process Henk described above hasn't changed, but things have been sped up quite a bit.

**Comment by RussKie** [comment]
Closing due to age and lack of follow up.
