### ISSUE TITLE
Git Extensions Failing to Start

### ISSUE THREAD

**Issue by flipd-d-mon** [gitextensions/gitextensions#2595]
Hi,

I've tried to install & use Git Extensions on my Windows 8.1 machine - but as yet, I am unable to successfully start the application.

I click the application icon to run it, though receive an error message:

![gitextensions_error](https://cloud.githubusercontent.com/assets/8641503/5614251/f115773e-94e6-11e4-8fe4-e72b1401557c.PNG)

![gitextensions_error_exception](https://cloud.githubusercontent.com/assets/8641503/5614253/f6d4a74e-94e6-11e4-9c3a-fa863b89e818.PNG)

I have uninstalled & reinstalled Git Extensions a couple of times now, but still the problem persists.

Any help with this would be appreciated - thanks.

**Comment by ghanique** [comment]
Somewhere in your %appdata% directory there is an XML file containing Git
Extension's configuration. That file probably contains some data that makes
the XML invalid. Most likely it is the field that stores the last commit
message.

**Comment by flipd-d-mon** [comment]
Thanks - I'll give this a go.
