### ISSUE TITLE
GitExtensions gets confused in FileHistory/Blame if two files have the same name and similar path

### ISSUE THREAD

**Issue by mouseas** [gitextensions/gitextensions#2596]
--- GitExtensions2.48.03, Git 1.9.4.msysgit.2, Microsoft Windows NT 6.1.7601 Service Pack 1

I have two files, `/web/contact/newContact.jsp` and `/web/contact/org/newContact.jsp`. When I look up the latter in File Tree, and select "Blame" or "File History" from the right-click context menu, GitExtensions thinks I am requesting the Blame/File History on the former.

![git-ext-bug-img-a](https://cloud.githubusercontent.com/assets/1171633/5618420/26e60ccc-94d6-11e4-9a70-ab24a098515d.png)

The second file, `/web/contact/org/newContact.jsp` was originally copy/pasted from the first file, so that may be the source of the problem.

![git-ext-bug-img-b](https://cloud.githubusercontent.com/assets/1171633/5618424/3322d65a-94d6-11e4-9f9b-bfb9fc6dffa7.png)

Upon digging a little further, it looks like four commits before HEAD, it is looking at the correct file.

![git-ext-bug-img-c](https://cloud.githubusercontent.com/assets/1171633/5618442/55c157ea-94d6-11e4-8fab-57a79c4e9513.png)

Going down through the file history list a ways, about half of the entries are looking at the wrong file.

**Comment by KindDragon** [comment]
Fixed in PR #2512
