### ISSUE TITLE
GitUIPluginInterfaces error.

### ISSUE THREAD

**Issue by ecin1resp1** [gitextensions/gitextensions#2603]
Just upgraded to the latest version (2.48.3).  When I hit the Commit button below the dropdown I get the following error.  After clicking OK I get the commit screen.

Let me know what other information I can add.

![image](https://cloud.githubusercontent.com/assets/1794260/5670746/9e22571a-9737-11e4-9b4a-bf208d0f20bf.png)

--- GitExtensions2.48.03, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by KindDragon** [comment]
I think something wrong with you GitExt folder. Try uninstall it, remove folder from program files and install it again,
