### ISSUE TITLE
Add support for the "rename-threshold" option in the merge dialog

### ISSUE THREAD

**Issue by ulrichb** [gitextensions/gitextensions#2609]
Due to rename detection during a merge operation, Git potentially produces wrongly matched files (false positives), respectively misses matches (false negatives).

Therefore, it would be cool to be able to adapt the `rename-threshold=<n>` option (see http://git-scm.com/docs/git-merge#_merge_strategies) in the merge dialog, probably in the "Show advanced options" section.

**Comment by brookjordan** [comment]
I'd love to have this.

**Comment by abhilashmurthy** [comment]
Me too 💯
