### ISSUE TITLE
branch name is changing case on pull/push

### ISSUE THREAD

**Issue by randomDev44** [gitextensions/gitextensions#2612]
on Win7
1) there is branch on server: "Story/story1"
2) user checks out this branch: local branch "story/story1" is created (**with changed case!**)
3) user creates commit1 and pushes branch: server creates NEW branch "story/story1"
4) other users using "Story/story1" will never see new commit1.

Mind you: command line git works ok

And I see this linger on from 2011?
http://www.lpaneque.com/2011/11/git-git-extensions-and-case-sensitive.html

DaFuQ?

**Comment by jzylkin** [comment]
please someone fix this! The branches at my work have upper case names just like this, and so I can't use git extensions!

**Comment by RussKie** [comment]
I am really unclear as to what needs fixing.
Every develop is responsible for their actions. GE works correctly:
![image](https://user-images.githubusercontent.com/4403806/37554093-ee96d9e2-2a27-11e8-85d4-89adac7f7b67.png)
