### ISSUE TITLE
Translation migrate

### ISSUE THREAD

**Issue by odie2** [gitextensions/gitextensions#2613]
Hi,
December 28 I wrote to KindDragon on Transifex, still with no response.

I updated from 2.47.3 to 2.48.03. But in 2.47.3 I had some Polish translation.

Could you update XML to XLF?
http://maciej.kuzniczysko.pl/files/Polish.xml

Also I reported Polish request on Transifex and also still no response.

Greetings, Maciej

**Comment by KindDragon** [comment]
Done
