### ISSUE TITLE
Ctrl+W shortcut for close repository not displayed

### ISSUE THREAD

**Issue by mariusschulz** [gitextensions/gitextensions#2618]
I've noticed that after the last update, the currently opened repository isn't being closed anymore when pressing the `ESC` key (running Windows 8.1). Before, it had the same effect as clicking the *Repository | Close (go to Dashboard)* menu item.

Is that a bug or a feature? ;)

**Comment by vbjay** [comment]
Look at the menu option.  It has a new shortcut.

**Comment by mariusschulz** [comment]
And which one would that be? The menu doesn't show any shortcut:

![go_to_dashboard](https://cloud.githubusercontent.com/assets/947523/5788626/06d67618-9e42-11e4-8101-67a648e5081e.png)

**Comment by vbjay** [comment]
Oops. It did. Ctrl w

**Comment by mariusschulz** [comment]
Thank you!

**Comment by damiensawyer** [comment]
Thanks :-)
... I didn't realise how much I used this until it was gone!
