### ISSUE TITLE
GitHub plugin "Action Cancelled" XP

### ISSUE THREAD

**Issue by rn10950** [gitextensions/gitextensions#2621]
When I try to log into GitHub in XP I get an Action Cancelled dialog.
![gitext_act_cancelled](https://cloud.githubusercontent.com/assets/8262801/5795741/fcae7dd8-9f64-11e4-9531-0728e202f2dc.PNG)

**Comment by ghanique** [comment]
Looks like an IE 6 problem. Looks like GitHub doesn't support IE6 anymore...
A workaround may be to do the same thing on a higher version of windows and
copy the OAuth token in Settings / Plugins / GitHub and paste that in XP?
