### ISSUE TITLE
Method not found: 'GitUIPluginInterfaces.IGitPluginSettingsContainer GitUIPluginInterfaces.GitPluginBase.get_Settings()'.

### ISSUE THREAD

**Issue by mparkuk** [gitextensions/gitextensions#2623]
I'm getting the following error with the latest update:

Method not found: 'GitUIPluginInterfaces.IGitPluginSettingsContainer GitUIPluginInterfaces.GitPluginBase.get_Settings()'.

--- GitExtensions2.48.03, Git 1.9.4.msysgit.2, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by KindDragon** [comment]
Try uninstall GitExt, remove folder in program files and install it again

**Comment by jafin** [comment]
Same error.  Removing AutoCheckForUpdates.dll from the GitExtensions\Plugins folder fixed it for me.  It had a date of 27/6/2013, everything else was dated 09/12/2014

**Comment by mparkuk** [comment]
Thank you both for replying.

Removing AutoCheckForUpdates.dll from the GitExtensions\Plugins folder fixed it for me too.
