### ISSUE TITLE
Typing into the "Branches" filter moves the cursor to the end after every keystroke

### ISSUE THREAD

**Issue by mouseas** [gitextensions/gitextensions#2625]
When typing one or more branch names into the "Branches" filter, if the user attempts to type from, for example, the beginning of the input field, the cursor is automatically moved to the end of the field after their first keystroke.

For example, I'm trying to type "TASK_4114 TASK_4114b", but I accidentally type "TK_4114 TASK_4114b". If I go back to correct the first branch name, I'd put the cursor at "T|K_4114" and then type "AS". I would expect the field to now read "TAS|K_4114 TASK_4114b", but instead it reads "TAK_4114 TASK_4114bS|" ('|' marking the cursor position).

The expected behavior for a text field is to match that of text fields in most every program, but this text field behaves in a non-standard, usability-breaking manner, that is, the cursor is automatically moved to the end of the field every time the user types a character into it.

I have not tested any of the other filter fields throughout the app, but if they behave the same way then they will all need to be corrected.

**Comment by jeffqc** [comment]
There is a fix for this on master, check for commit 78965e1175437312b0c846e9338ed9621b6ad1dd.

**Comment by GintasS** [comment]
This issue seems to be fixed.
