### ISSUE TITLE
'Documents' is not a valid short file name

### ISSUE THREAD

**Issue by dontsovcmc** [gitextensions/gitextensions#2629]
Windows 7 x32
I have a problem with "My documents" folder: I don't have this folder... 

When run GitExtensions-2.48.03-SetupComplete.msi
I have an error window:
"'Documents' is not a valid short file name"

**Comment by dlidstrom** [comment]
Related to #2622?

**Comment by KindDragon** [comment]
Check this http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=2005087

**Comment by KindDragon** [comment]
Try disable all VS plugins in installer
