### ISSUE TITLE
Commit graph in File History is not linear when "Detect and follow renames" is disabled

### ISSUE THREAD

**Issue by Radrik5** [gitextensions/gitextensions#2632]
Git Extensions, GitUI/FilterBranchHelper.cs file

"Detect and follow renames" is disabled:
![image](https://cloud.githubusercontent.com/assets/9339459/5973012/03856f00-a874-11e4-94db-ba83264047cc.png)

"Detect and follow renames" is enabled:
![image](https://cloud.githubusercontent.com/assets/9339459/5973019/185a6480-a874-11e4-91ad-04a532a0bac5.png)

**Comment by qgppl** [comment]
Yes, a4c7f4be4114ed395573e4954ecdcf927f037feb does.
