### ISSUE TITLE
Translating Plugins

### ISSUE THREAD

**Issue by odie2** [gitextensions/gitextensions#2633]
Hi,
It's possible add possibility to translate Plugins on Transifex
or they are external libraries so this is not possible?
Greetings

![gitext](https://cloud.githubusercontent.com/assets/9401878/5982645/6ac0adf0-a8c5-11e4-84f3-9032436c4af3.jpg)

**Comment by KindDragon** [comment]
Hi. It should already work for plugins that implement it correctly.
