### ISSUE TITLE
Shell extension translation

### ISSUE THREAD

**Issue by odie2** [gitextensions/gitextensions#2634]
Hello,
as I saw - for example with ExtremeCopy - it's possible to give user translated shell extension.
Could you check it?
Greetings

**Comment by KindDragon** [comment]
Better use chat https://gitter.im/gitextensions/gitextensions for such questions.
Yes, it's possible if plugin author implement it correctly.

**Comment by KindDragon** [comment]
Sorry, I misunderstood. We do not support it
