### ISSUE TITLE
FormOpenDirectory "Open in Explorer"

### ISSUE THREAD

**Issue by odie2** [gitextensions/gitextensions#2635]
Hello,
I would suggest adding "Open in Explorer" button for FormOpenDirectory (Ctrl+O when repository opened).
I very often open working directory paths with GitExtensions. It would be nice to have button that when clicked opens Explorer window with this path (I saw few times that it is possible).

Thanks in advance,
Greetings, Maciej

![git5](https://cloud.githubusercontent.com/assets/9401878/5984122/5de08b88-a8d3-11e4-8095-28b5ce5d44d1.jpg)

**Comment by vbjay** [comment]
ctrl + shift + O

**Comment by odie2** [comment]
Thanks nice, I didn't saw it earlier and additionally I badly translated it :)
