### ISSUE TITLE
Turn "Delete file" remove files to recycle bin

### ISSUE THREAD

**Issue by rexpan** [gitextensions/gitextensions#2636]
Can you make the  _Delete file_ action in _Commit_ dialog to remove the file(s) to recycle bin instead of delete it completely.
So we can recover the file(s) if we accidently delete the incorrect file(s).
Thanks.

**Comment by vbjay** [comment]
The tool is running git rm which as you can see is a linux made tool.  It
has no idea the recycle bin exists.  http://git-scm.com/docs/git-rm

**Comment by linquize** [comment]
Run `git clean -nxd` (dry run),

Capture the output lines to get a list of file names:

Would remove abc.txt
Would remove def.txt

Then delete the list of files to recycle bin.

**Comment by ghanique** [comment]
Before Git Extensions invoked "git rm", can it not first delete the file on
the file system (so that it goes to the recycle bin) and then invoke "git
rm"? Or do we then get a problem because it should also run in mono on
linux?
