### ISSUE TITLE
Cannot read file C:\Users\(myname)\.gitconfig

### ISSUE THREAD

**Issue by ChrisEngineer** [gitextensions/gitextensions#2638]
I get this error every time I go to Git > Configuration 

Cannot read file C:\Users(myname).gitconfig    (in the view details panel it just repeats this message x2)
org.eclipse.jgit.errors.ConfigInvalidException

What exactly is going on besides Git not working correctly? and is there a way to fix it?

**Comment by KindDragon** [comment]
__(myname)__ contains non-English characters?

**Comment by ChrisEngineer** [comment]
no, sorry for that confusion the (myname) part is my actual name its like the file path name... I just put that on there just for security of myself.

**Comment by jbialobr** [comment]
It seems you should report this issue to eclipse plugin project
