### ISSUE TITLE
Only ancestor commits of current branch are shown in commit history

### ISSUE THREAD

**Issue by RickMohr** [gitextensions/gitextensions#2639]
Since upgrading from 2.47.03 to 2.48.03 the commit history shows only ancestor commits of my current branch. For example, if I make a branch `B` off of `master` and add a commit, both `B` and `master` are shown in the commit history. But if I then switch the current branch to `master`, `B` (and my commit) are not shown in the history. In 2.47.03, `B` was shown in the history.

Was this change made on purpose? If so I prefer the previous behavior.

Is there a setting that controls this? If so I was unable to find it.

**Comment by KindDragon** [comment]
Check View > Show all branches is selected

**Comment by RickMohr** [comment]
Thanks.
