### ISSUE TITLE
GitExtensions breaks Visual Studio 2013

### ISSUE THREAD

**Issue by hhubschle** [gitextensions/gitextensions#2641]
Install version 2.48.03 with VS2013 integration
Start VS2013
Disable the GitExtensions toolbar
Close VS2013 and restart it: 
->"Microsoft Visual Studio 2013 has stopped working"
VS2013 is dead.

You can recover by removing VS2013 integration.

**Comment by KindDragon** [comment]
Duplicate of #2587
