### ISSUE TITLE
Usability suggestion: option to save .git to alternate folder

### ISSUE THREAD

**Issue by Paul47** [gitextensions/gitextensions#2643]
As a relatively new user to gitextensions I have been told that .git folders can only be created in the project/code folder. It seems risky to me to store .git commits to the same folder as the project code. If the project drive or the project folder is lost, so are all the .git versions.  Allowing .git saves to a different drive\folder would allow projects to be reconstructed in the event of data or drive loss. 

A data loss or a drive crash will always occur just after extensive edits are made and just before they are pushed to github!  There can never be too many backup processes.

If this is not relevant then feel free to close this 'issue'

**Comment by KindDragon** [comment]
I think git-way to do that:
1. Create Cental (bare) repository on different drive
2. Add this repository as remote repository to your current
3. Push all changes to central repository
4. Push changes to github if needed

Set your central repository as default remote repository for your branch and always use Commit and push button.

.git folder should always be with your repository (this how Git works), but you can create multiple local copies.

**Comment by KindDragon** [comment]
You also can try `git clone --local` command

**Comment by KindDragon** [comment]
Also, you can use `--separate-git-dir=<git dir>` but I not recommend it http://git-scm.com/docs/git-clone

**Comment by Radrik5** [comment]
Moving .git folder away is not a backup: if you loose the drive with the .git folder, you loose all the history! And all you have after that is the last revision of files in your working copy. So the right thing to do is to create a clone (bare or not) of your repository.

**Comment by KindDragon** [comment]
> So the right thing to do is to create a clone (bare or not) of your repository.

:+1:
