### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by cniweb** [gitextensions/gitextensions#2644]
When will there be a new release?

**Comment by KindDragon** [comment]
Yes, but we need more testing https://www.dropbox.com/s/64sjr1d7v585z5a/GitExtensions-2.48.04-SetupComplete.msi?dl=0 . We need to make sure that all errors reported that fixed - really fixed.

BTW better use chat for such questions https://gitter.im/gitextensions/gitextensions

**Comment by cniweb** [comment]
Is the new version 2.49 ?

**Comment by KindDragon** [comment]
No, 2.48.04
