### ISSUE TITLE
Commit message not retained if commit window opened by Advanced > Fixup/Squash

### ISSUE THREAD

**Issue by patricktokeeffe** [gitextensions/gitextensions#2648]
Just noticed this change with 2.48: if the commit window is opened via context menu Advanced > Fixup commit or Squash commit, and the commit window is then closed, the auto-generated commit message is removed. Actually any commit message, even if you replace all the text, will be discarded. 

Was this changed for a technical reason? It seems like such a trivial time-saver. I find it disruptive since the commit dialog is modal and I can't refer to nearby commits without closing it. Then I have to relocate the fixup target commit since the message was discarded.

**Comment by patricktokeeffe** [comment]
A better candidate for this type of behavior would be the amend checkbox. Currently, text added when amend is enabled will remain after amend is disabled. There's no reason that should be the case but it's probably easier to just leave the message than to verify it wasn't altered before discarding.

**Comment by mstv** [comment]
This was by design. The handling has been improved in 3.3.0 coming soon.
