### ISSUE TITLE
ChildProcess "git ls-files -o -i --exclude-standard" = High CPU on large Project

### ISSUE THREAD

**Issue by MichiShyGuy** [gitextensions/gitextensions#2649]
Hey there,

as soon as I open GitExtension with a rather large project 100.000+ (maybe even more) Files, where like 95.000+ are excluded by a directory-match in .gitignore, GitExt creates multiple child processes, performing "C:\Program Files (x86)\Git\bin\git.exe" ls-files -o -i --exclude-standard"

![issue_cpuload](https://cloud.githubusercontent.com/assets/3170031/6163274/228d9546-b290-11e4-8742-99369ae28f8f.png)

Each of these Processes takes a whole cpu core. This problem makes my System extremely slow. Also Even when closing GitExtension, the processes remain.

So, is there any option to disable the scanning of ignored files?

Best Regards,
Michael

**Comment by KindDragon** [comment]
Hi. All git processes is git ls-files?

**Comment by KindDragon** [comment]
Tools > Settings > Git Extensions > Show repository status in browser dialog

**Comment by MichiShyGuy** [comment]
1. Yes, all processes are "ls-files"

2. Disabling that option, also disables the scanning of actual repository-files. So the commit-button doesn't indicate any changes on files .

**Comment by KindDragon** [comment]
2. Yes. We can't determinate is changed file ignored without "git ls-files" ATM

**Comment by MichiShyGuy** [comment]
Without knowing too many details about the Implementation:
Why not use "git status" as alternative and parse the output?
In my case it takes a maximum of 5 seconds and does only scan the GIT-Files which are not git-ignored.

Or did you already consider this?

**Comment by KindDragon** [comment]
We call git status after we check that some of not-ignored files are changed https://github.com/gitextensions/gitextensions/blob/b524ffd9e108bd735847f8f90debfccc5f266b06/GitUI/UserControls/ToolStripGitStatus.cs#L254-L257

**Comment by jbialobr** [comment]
I think that we could increase the scan for ignored files interval to 10 minutes or even one hour:
https://github.com/gitextensions/gitextensions/blob/master/GitUI/UserControls/ToolStripGitStatus.Designer.cs#L43

**Comment by KindDragon** [comment]
BTW Libgit2sharp had API that check is path ignored

**Comment by MichiShyGuy** [comment]
@jbialobr 
Why not make it configurable :)

**Comment by KindDragon** [comment]
Almost all users don't use this settings, but new settings hard to mantain.
It should works by default.

**Comment by MichiShyGuy** [comment]
Regarding the default setting:
- .gitignore is often used to exclude garbage and temp-folders resulting in many ignored files
- a high default-setting may be a good thing
- the possibility to change the default should be given

I agree that "Git status also works slow if you have a lot of changes". But having lots of ignores seems more common to me. Especially because the number of ignores potentially increases on long project-cycles, while  changes should stay on a low level.

**Comment by jbialobr** [comment]
> BTW Libgit2sharp had API that check is path ignored

Yes, but it reads all .gitignore files each time you call it, so it doesn't look like a good solution either.
I changed the interval to 10 minutes.

**Comment by vbjay** [comment]
Filesystem watcher on the .gitignore files?

**Comment by jbialobr** [comment]
> Filesystem watcher on the .gitignore files?

Yes, but you have to implement parsing .gitignore and matching ignored files.
