### ISSUE TITLE
Jenkins plugin: Incorrectly detects Internet Explorer 'Document Mode'

### ISSUE THREAD

**Issue by laurin1** [gitextensions/gitextensions#2654]
All the developers on my team experience this issue. When we enable the Jenkins plugin, we get this message when loading the repo:

````
WARNING: Your Internet Explorer appears to be set to a non-default 'Document Mode' (see Developer Tools - press F12).

Jenkins may not display properly in this browser.
````

![capture](https://cloud.githubusercontent.com/assets/75857/6192883/f5155c4c-b37b-11e4-9e24-511e59431bfd.JPG)

First of all, why is it using IE for this at all? Secondly, I've checked the open Windows I have, and that is not correct (but I suspect this has nothing to do with my IE UI):

![capture](https://cloud.githubusercontent.com/assets/75857/6192918/3734c8f6-b37c-11e4-909e-d9722f6ad6d2.JPG)

**Comment by KindDragon** [comment]
Web control that we use is standard IE engine

**Comment by laurin1** [comment]
Ok, I thought that might be the case, but I wasn't going to assume. So why is that Web Control reporting a non-default Document Mode?

**Comment by KindDragon** [comment]
I found this issue https://issues.jenkins-ci.org/browse/JENKINS-23921

**Comment by laurin1** [comment]
Yea, it appears that https://issues.jenkins-ci.org/browse/JENKINS-24550 was caused by the "fix" applied for https://issues.jenkins-ci.org/browse/JENKINS-23921. Thanks for finding that - I did not know bugs were tracked in Jira.

**Comment by laurin1** [comment]
Wait, is it just me, or are these comments off-base?

https://issues.jenkins-ci.org/browse/JENKINS-24550

If this is due to the version of the Web Control being used, then it doesn't matter what browser I'm using, correct?

**Comment by KindDragon** [comment]
You can try update IE to latest version. This may help

**Comment by laurin1** [comment]
I'm using the latest version of IE.
