### ISSUE TITLE
Pull Dialog wrong params preselection

### ISSUE THREAD

**Issue by AndreasWeste** [gitextensions/gitextensions#2663]
--- GitExtensions2.48.03, Git 1.9.4.msysgit.2, Microsoft Windows NT 6.1.7601 Service Pack 1

My Pull Dialog dont save the Remote Branch or the Merge-Option that i use every time.

This can cause great trouble by selecting accidently the wrong params. See attached Screenshot.

![git extensions pull problem](https://cloud.githubusercontent.com/assets/4381709/6227812/adfedc6c-b6a4-11e4-9d18-00097b0fe27d.png)

**Comment by ghanique** [comment]
Could it be that the branch isn't a tracking branch?

**Comment by RussKie** [comment]
Please install v3, open a new issue if it is still a problem
