### ISSUE TITLE
Merging with new directory source 

### ISSUE THREAD

**Issue by alexxx537** [gitextensions/gitextensions#2664]
I tried to merge old source (location \Project\) with new source (location: \Project\Source\). Git showed me that source files were removed from project. New source  is in deeper location and if there is no such folder then git assumes that files was removed after merge. Why git does not create re nest source code?

**Comment by vbjay** [comment]
That isn't how you do it. Just overwrite the files at the same folder. Git will tell you which files are new and modified. If you need to replace a clean source then delete all work files and then copy new work files from new source.
