### ISSUE TITLE
Add local/remote branch lists to script arguments

### ISSUE THREAD

**Issue by hotn** [gitextensions/gitextensions#2665]
The script arguments include options for the current branch and options for the currently selected revision. It would be useful to also be able to choose a branch, whether local or remote, that isn't the current branch and is not on the selected revision. For example, "All Branches" options like {aBranch}, {aLocalBranch}, {aRemoteBranch}

Similarly, {aRemote} that would list out all known remotes would be useful.

**Comment by GintasS** [comment]
Abandoning this because of age.
