### ISSUE TITLE
Toolbar buttons in VS2012 not doing anything

### ISSUE THREAD

**Issue by GiorgiStoynev** [gitextensions/gitextensions#2673]
Hi,
After updating to v. 2.48.03, VS toolbar buttons sometimes get into a state where they are not doing anything when clicked. The issue goes away, I suspect, after changing current file in Solution Explorer or by some other tracked event. I can't establish a pattern as to what causes the toolbar buttons to go into that mode, nor what makes them work again.
Visual Studio Ultimate 2012 (11.0.61030.00 Update 4)

**Comment by fernando-takeshi** [comment]
I've also observed this, but in my case it seemed that nothing made any of the buttons work. I wound up rolling back to 2.47.3 - which I think is the one available through the VS Extensions as well.

**Comment by GiorgiStoynev** [comment]
Upgraded to 2.48.05 and issue is gone. Closing the issue
