### ISSUE TITLE
Stash got corrupted

### ISSUE THREAD

**Issue by distinctdan** [gitextensions/gitextensions#2676]
I stashed a few changes, and had the option checked to stash new files, but the stash doesn't even show up in the stashes list. And when I try to apply the stash on the command line using `git stash apply`, it says "refs/stash@{0} is not a valid reference".  I've also tried `git stash apply stash@{0}`, but it says: "fatal: Log .git/logs/refs/stash is corrupt."

I'm not too worried about recovering the work, but I'd like to figure out how this happened. Thanks.

**Comment by KindDragon** [comment]
Your repository is corrupt. Try restore it `git fsck --full`

**Comment by distinctdan** [comment]
Hmm, I ran it, and it listed a lot of dangling blobs and a few dangling commits. From my googling, those don't appear to be harmful. I've since dropped the stashes, and the repo appears to be working fine, it's just I've never had a problem stashing before, so thought I'd bring it up in case it had something to do with git extensions.
