### ISSUE TITLE
Fix "copy new version" and "old version" in diff view - nothing copied!

### ISSUE THREAD

**Issue by ChameleonRed** [gitextensions/gitextensions#2678]
--- GitExtensions2.48.03, Git 2.1.4, Microsoft Windows NT 6.1.7601 Service Pack 1

Sometime is need to copy some changes from diff between two versions but it not works as it should - see screen - there is two option "copy new version" and "copy old version" both not working.

https://www.dropbox.com/s/0s4vraq74h3on3h/Zrzut%20ekranu%202015-02-25%2011.40.21.png?dl=0

Personally I prefer to just replace file with new version - whatever copy is not bad option.

**Comment by jbialobr** [comment]
They are intended to copy the selected text including new version and excluding old version for copy new version and the other way round for copy old version.
Could you explain what do you want to do, as I don't understand it from your description.

**Comment by ChameleonRed** [comment]
No matter what I want to do - sometimes this sometimes that :)
I want merge changes manually to save life time.

1. action 'copy new version' -> clipboard == ''
2. same with 'copy old version' -> clipboard == ''

I want before to copy text into winmerge to merge but it was not possible so I just replace with A than with B and merge with winmerge. I do not think so that it explains you more but you can feel more confused that is why I not write this before to save your time for analysis :)

**Comment by ChameleonRed** [comment]
I need option to copy single file from repository and do something with this ... depend on mood and need.

**Comment by jbialobr** [comment]
Fixed in 4e0a2cd4bde11936b1e7323761c7d0e1307b7287

**Comment by jbialobr** [comment]
>I just replace with A than with B and merge with winmerge

Wouldn't it be the same as:

![2015-03-02 11_58_42-gitext master - git extensions -_ debug _-](https://cloud.githubusercontent.com/assets/1003909/6439503/918d5de0-c0d3-11e4-8e93-00af628427ea.png)

**Comment by ChameleonRed** [comment]
Waiting for update :)
