### ISSUE TITLE
"Unsupported file" error with submodules

### ISSUE THREAD

**Issue by pickettSKF** [gitextensions/gitextensions#2679]
When working with submodules, I always get this issue (screenshot below). It used to show the commit hashes and the change, but not any more.

Additionally, the submodule is shown with a 'file' icon, and not a submodule icon (the screenshot is showing changes to two submodules, not files).

![screenshot 2015-02-25 10 33 39](https://cloud.githubusercontent.com/assets/744039/6376271/1ec145d0-bcda-11e4-9fa2-4c1d4d8f625c.png)

**Comment by KindDragon** [comment]
Maybe something missed in .gitmodules?

**Comment by pickettSKF** [comment]
My git modules is pretty basic...  (attached)
Could it be that the 'path' for the sub-module has spaces? I haven't tested a path without a space.

![gitmodules](https://cloud.githubusercontent.com/assets/744039/6783841/ad58df80-d141-11e4-8399-34fe5fdb20b9.png)

**Comment by EdyJ** [comment]
I also have this problem. How should I report it as bug so it could be taken a look at?

**Comment by EdyJ** [comment]
Ok, I've nailed down the issue to GitCommandHelpers.GetSubmoduleStatus line 916:

    var match = Regex.Match(line, @"diff --git a/(\S+) b/(\S+)");

This regular expression tries to get the submodule names out of a diff command. However, when the submodule path contain spaces, the regular expression fails. For example, this is the content of my _line_ variable:

    diff --git a/Assets/Core/Vehicle Physics core b/Assets/Core/Vehicle Physics core

The name of the submodule is "Assets/Core/Vehicle Physics core". But the match just extracts a single empty string.

Can anyone advise on a proper regular expression to extract the submodule names properly out of the previous line? I'm not an expert on regular expressions, but will try to find a proper matching expression in the meantime.

**Comment by EdyJ** [comment]
I've fixed the issue by replacing the two regular expressions in the mentioned method.

Originals:

    var match = Regex.Match(line, @"diff --git a/(\S+) b/(\S+)");
    match = Regex.Match(line, @"diff --cc (\S+)");

Fixed:

    var match = Regex.Match(line, @"diff --git a/(.+) b/(.+)");
    match = Regex.Match(line, @"diff --cc (.+)");

Tested with submodules with and without spaces in the name, working perfectly.
