### ISSUE TITLE
Side by side diff view

### ISSUE THREAD

**Issue by njdj** [gitextensions/gitextensions#2680]
Not sure if i'm missing something obvious, but how can I get a side by side view when diffing files?
I guess its not down to the external diff tool itself, since the following run inside of git extensions gives the +- view:
"C:/Program Files (x86)/WinMerge/winmergeu.exe" -e -u "$LOCAL" "$REMOTE"

While the following run outside of git extensions gives me a side by side view.
"C:/Program Files (x86)/WinMerge/winmergeu.exe" -e -u tmp1.txt tmp2.txt

Thanks

**Comment by ghanique** [comment]
I don't understand your question. I, too, have winmerge installed instant
and configured as a diff tool. When I press f3 I get a very nice side by
side view.

**Comment by njdj** [comment]
Ah, thanks - that's it. Just discovered the 'open with difftool' command. Not sure how I missed that.

It was the default view I was trying to change, but it looks like there's no need.

**Comment by shootdaj** [comment]
Actually, is it possible to change the git diff in the commit window to be side-by-side? I'm not talking about when the "Open with difftool" menu item is clicked. I'm talking about directly in the window to the right side where the diff is displayed by default. Thanks

**Comment by pmiossec** [comment]
> Actually, is it possible to change the git diff in the commit window to be side-by-side?

No, it is not possible in GitExtensions at the moment...
