### ISSUE TITLE
Scrollbar goes missing sometimes

### ISSUE THREAD

**Issue by ChrisFindlay** [gitextensions/gitextensions#2682]
--- GitExtensions2.48.03, Git 2.1.4, Microsoft Windows NT 6.1.7601 Service Pack 1
Sometimes when loading a repo with lots of history, GitExtensions only loads enough entries to fill the visible size of the list - there is no scrollbar.  I have to resize the (initially maximised) window to get the scrollbar to appear and then everything works correctly again.
I'm unsure of the trigger, but this time it was changing branch to one that would have been several screenfulls down.

**Comment by christianrondeau** [comment]
Got the same issue, though I'd add more details: it's not that the scroll bar doesn't show up, it's rather that the commit listing "stops" (not necessarily starting from the top commit). Using the key or resizing the window didn't solve the issue (though it looks like time did). Maybe simply an async process that takes time? Is it possible that GitExtensions draws the visible portion first, and the rest asynchronously? If it's the same, the solution could be as simple as adding a "preloading" row or icon somewhere.

**Comment by TacticalDan** [comment]
I've been having this problem with resetting to really old commits. Seems to work after a really long async loading period?
