### ISSUE TITLE
Toolbar buttons disabled in VS2013

### ISSUE THREAD

**Issue by Steve887** [gitextensions/gitextensions#2683]
I just updated GitExtensions from 2.47.3 to 2.48.03 and am having an issue where the buttons in the Visual Studio toolbar are disabled and unclickable.

I have tried disabling and re-enabling the toolbar and restarting VS. If I use the add-in manager to disable the toolbar, the buttons enable but clicking any of them cause nothing to happen, and all the buttons disable again.

![image](https://cloud.githubusercontent.com/assets/129719/6453624/a5eb6256-c18b-11e4-905b-a6ca5e73e4db.png)

**Comment by NIA** [comment]
The workaround by @strice from his comment to issue #2558 worked for me (for VS2012).

**Comment by Steve887** [comment]
That worked.
