### ISSUE TITLE
Branch selection control changes

### ISSUE THREAD

**Issue by qgppl** [gitextensions/gitextensions#2684]
Hi, I'd like to propose some changes to the branch selection combo:
![branchcombo](https://cloud.githubusercontent.com/assets/339002/6473762/c6a2ad9a-c1fb-11e4-8fbe-8c64483b7735.png)
The idea is to show selected refs (branches, tags) beside the combobox, and to not use its text as placeholder for multiple selected items. This adresses some reported issues: branch can contain any character in its name and still be selected (#2645, #2154), tags can be selected for merging (#2458), even raw commit id's (typed into). #2458 will probably need some additional work on RevisionGrid to add tags to the popup menu.
I'd be grateful for any comments and also ask for double-check by someone using LTR locale, since I'm unable to verify this in such environment.
Not posting as pull request yet, however mostly ready code is in deb3961699dc7327af7d003c1d87a99d6a03143e

**Comment by Radrik5** [comment]
Cannot we just fix the problem with comma in a branch name?
Why there are 3 refs in your example? Octopus merges are rarely used. Maybe it's better to replace the ref when user selects another one?

**Comment by qgppl** [comment]
These issues have been around for some time, so I see them as an opportunity to try out and suggest something different - that's the reason this is not a PR. I agree that simply removing the comma from Split argument in GetSelectedBranches would suffice (spaces are valid branches separators). As for octopus merges - removal of multiple branch selection would surely result in an issue opened by someone sooner or later.
