### ISSUE TITLE
can't get rid of warning after uninstalling git extensions

### ISSUE THREAD

**Issue by grozamorei** [gitextensions/gitextensions#2687]
I completely deleted extensions, but I keep getting this warning in git bash(mingw32) on pull:

"c:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe" get: -c: line 0: syntax error near unexpected token `('
"c:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe" get: -c: line 0: "c:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe" get

that is utterly frustrating, and I cannot make this warnings disappear.

**Comment by tomasdeml** [comment]
Duplicate of #2354? Seems to a bug in one of older versions of Credentials provider.

**Comment by grozamorei** [comment]
I swear i did a ticket search before.

many thanks for advice!
