### ISSUE TITLE
Add --log option to merge window

### ISSUE THREAD

**Issue by jorisvergeer** [gitextensions/gitextensions#2688]
We use git svn and locally I work with feature branches. When I merge my feature branches into the trunk all commit messages are lost. When merged with the --log option the commit messages are preserved. (first line per commit only but it is something)

It would be helpful if an option is added to the merge window where I can select a checkbox that adds "--log" and maybe "--log=X" the the git merge command.

**Comment by jbialobr** [comment]
Done in #2997
