### ISSUE TITLE
Allow setting authored date for commit

### ISSUE THREAD

**Issue by jnahmias** [gitextensions/gitextensions#2690]
It would be helpful for my workflow if it were possible to override the authored date when I commit within GitExtensions.  I would be fine with something tucked under the options menu, perhaps right next to where you can override the Author.

Thanks,
--Joe

**Comment by drewnoakes** [comment]
Duplicate of #4918.

(While this issue was filed a few years earlier, the other has more discussion and this has none, so I elected to close this issue. Please subscribe to the other issue if you wish to receive updates.)
