### ISSUE TITLE
[mono] Unexpected XML declaration

### ISSUE THREAD

**Issue by ArsenShnurkov** [gitextensions/gitextensions#2697]
Call stack:
https://gist.github.com/ArsenShnurkov/d3c29df6d79c15171ea6

when run under monodevelop' debug:
"Stream is not a valid .resources file!  It was possibly truncated."
in <a href="https://github.com/gitextensions/gitextensions/blob/master/GitUI/FormSplash.cs#L51">FormSplash</a>:
https://gist.github.com/ArsenShnurkov/e855fd090c9d49f9f2b1

in main form:
https://gist.github.com/ArsenShnurkov/8031312a1f4a39cff6c0

Sometimes there is the build error:

    Tool /usr/lib64/mono/4.5/resgen.exe execution started with arguments: /useSourcePath /compile "Properties/Resources.resx,obj/Debug/GitUI.Properties.Resources.resources" 
    /var/calculate/remote/distfiles/egit-src/gitextensions.git/GitUI/GitUI.csproj (Build) ->
    /usr/lib64/mono/4.5/Microsoft.Common.targets (GenerateResources target) ->
    	/usr/lib64/mono/4.5/Microsoft.Common.targets: error : Tool exited with code: 139. Output: 

You can see the same here:
https://travis-ci.org/gitextensions/gitextensions/builds/41911581#L1294

**Comment by ArsenShnurkov** [comment]
# pwd
    /var/calculate/remote/distfiles/egit-src/gitextensions.git/GitUI
    # /usr/bin/resgen2 /useSourcePath /compile "Properties/Resources.resx,obj/Debug/GitUI.Properties.Resources.resources"
    Error: Invalid ResX input.
    Position: Line 123, Column 5.
    Inner exception: Could not find file "/var/calculate/remote/distfiles/egit-src/gitextensions.git/GitUI/Properties/..\Resources\Icons\error.png".

**Comment by ArsenShnurkov** [comment]
https://github.com/mono/mono/blob/master/mcs/tools/resgen/resgen.csproj
monodevelop gives an error when i am trying to open it:
"Load operation failed. Project file doesn't have a valid ProjectGuid"
I fixed .csproj file locally (almost recreate it).

sometimes resgen compile resources normally (almost):

    Loaded assembly: /var/calculate/remote/distfiles/egit-src/mono.git/mcs/class/lib/net_2_0_bootstrap/resgen.exe
    Loaded assembly: /usr/lib64/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll
    Loaded assembly: /usr/lib64/mono/gac/System.Windows.Forms/4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
    Loaded assembly: /usr/lib64/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll
    Loaded assembly: /usr/lib64/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
    Loaded assembly: /usr/lib64/mono/gac/System.Configuration/4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
    Loaded assembly: /usr/lib64/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll
    Loaded assembly: /usr/lib64/mono/gac/I18N/4.0.0.0__0738eb9f132ed756/I18N.dll
    Loaded assembly: /usr/lib64/mono/gac/I18N.West/4.0.0.0__0738eb9f132ed756/I18N.West.dll
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    libpng warning: iCCP: known incorrect sRGB profile
    Read in 178 resources from '/var/calculate/remote/distfiles/egit-src/gitextensions.git/GitUI/Properties/Resources.resx'
    Loaded assembly: __MetadataTypes
    Writing resource file...  Done.

and sometimes give different errors:

    Loaded assembly: /usr/lib64/mono/gac/I18N.West/4.0.0.0__0738eb9f132ed756/I18N.West.dll
    Stacktrace:
    
      at <unknown> <0xffffffff>
    *** Error in `/usr/bin/mono': malloc(): memory corruption: 0x0000000001fcf5c0 ***

**Comment by KindDragon** [comment]
Hi
@fraga Do you know anything about this issue?

**Comment by jbialobr** [comment]
I was able to successfully compile and run GitExt with mono 4.2.1 under ubuntu.
It looks pretty good, but crashes when it comes across a path with backslashes.
