### ISSUE TITLE
ampersand interpreted as hotkey in recent commit message dropdown

### ISSUE THREAD

**Issue by timabell** [gitextensions/gitextensions#2698]
Same effect as issue #619 but in the commit window. The little "Commit message" drop-down is hiding ampersands (&) in the list of messages and underlining the next letter.

v 2.47.3

**Comment by timabell** [comment]
tested again in latest (v2.48.03) and it no longer underlines the next char, but the ampersand is still missing

**Comment by KindDragon** [comment]
Should be fixed in PR#2525
