### ISSUE TITLE
'GitExtensions init' just brings up Commandline usage.

### ISSUE THREAD

**Issue by jedediahfrey** [gitextensions/gitextensions#2701]
When calling ```GitExtensions init``` from the command prompt it just brings up the "Commandline usage" dialog box. Other functions that I've tested (```GitExtensions about```, ```GitExtensions clone```) bring up the appropriate dialog box.

I believe this is a regression from 2.47.3 which worked correctly.

**Comment by Radrik5** [comment]
Probably duplicate of #2564

**Comment by jedediahfrey** [comment]
Yep.
