### ISSUE TITLE
Preview doesn't show diff for .rc files. It recognize them as binary files

### ISSUE THREAD

**Issue by MiltSaint** [gitextensions/gitextensions#2702]
Way to reproduce:
1. Add to repo .rc files
2. Open "commit to" window
3. Select .rc files from unstaged list.

Actual result:
Preview doesn't show diff for .rc files. It recognize them as binary files

Git Extension version: 2.48

**Comment by KindDragon** [comment]
Git doesn't support UTF8 with BOM or UTF-16 encodings.
Please check file enconding

**Comment by RussKie** [comment]
Re-open if it is still a problem with the current version.
