### ISSUE TITLE
Crashes when filtering the main view by Committer

### ISSUE THREAD

**Issue by distinctdan** [gitextensions/gitextensions#2705]
Steps to reproduce:
1) From the filter dropdown, select "Committer"
2) Type a person's name into the box

Git extensions then crashes and continues to crash when you open the repo, until you delete the GitExtensions.settings file located in C:\Users\your_username\AppData\Roaming\GitExtensions\GitExtensions.

**Comment by KindDragon** [comment]
Duplicate of #2653
