### ISSUE TITLE
[mono] An exception was thrown by the type initializer for GitCommands.AppSettings

### ISSUE THREAD

**Issue by ArsenShnurkov** [gitextensions/gitextensions#2710]
https://gist.github.com/ArsenShnurkov/d3c29df6d79c15171ea6

System.TypeInitializationException: An exception was thrown by the type initializer for GitCommands.AppSettings ---> System.Xml.XmlException: Unexpected XML declaration. The XML declaration must be the first node in the document, and no white space characters are allowed to appear before it. Line 104, position 9.

**Comment by ArsenShnurkov** [comment]
The problem was in the file
/home/user/.local/share/GitExtensions/GitExtensions.exe_Url_fc9221118986807f24034ab13ad4e7143ae90814/user.config 

which contained malformed XML.

I removed the file, and problem gone. But what was the reason of this bug?

**Comment by Olmer1st** [comment]
+1 have same problem, every time after  i close the GE, next i can't open it.
Removing /home/user/.local/share/GitExtensions/GitExtensions.exe_Url_fc9221118986807f24034ab13ad4e7143ae90814/user.config fix the the problem

**Comment by McBen** [comment]
```
....
<setting name="WindowPositions" serializeAs="Xml">
    <value>
      <?xml version="1.0" encoding="utf-16"?>
<WindowPositionList>
  <window>
    <name>FormBrowse</name>
    <state>Normal</state>
    <position>44; 44; 931; 600</position>
  </window>
</WindowPositionList></value>
  </setting>
....
```
WindowPositions -Value is a XML string.

**Comment by ArsenShnurkov** [comment]
cool observation. Now we need to find someone who will fix it

**Comment by EbenZhang** [comment]
Will gitextensions load properly if you manually change the `;` to `,`? Which culture is your system using? If it's a special culture that uses `;` as `,`, then we can use `InvariantCulture` when converting the position info. 

For escaping we can use the `writestring`(if dont remember wrong) instead of `writeelementstring`.

**Comment by ArsenShnurkov** [comment]
It's not a problem of ';' and ','. The whole <value>...</value> content should be escaped (this includes internal XML starting line)

**Comment by EbenZhang** [comment]
OK, I see.

But it seems the `<?xml version="1.0" encoding="utf-16"?>` shouldn't be there, are we writing nested xml into the settings file. For me, I guess, the file looks like overlapped by two threads that were writing to the xml file at the same time.

**Comment by McBen** [comment]
it should look like the 'hotkey' value:
```
...
<setting name="Hotkeys" serializeAs="String">
                <value>&lt;?xml version="1.0" encoding="utf-16"?&gt;
...
```

**Comment by ArsenShnurkov** [comment]
http://stackoverflow.com/questions/1132494/string-escape-into-xml

**Comment by KindDragon** [comment]
We use WebUtility.HtmlEncode for that

**Comment by ArsenShnurkov** [comment]
https://github.com/mono/referencesource/blob/1b3505f8d77d3173cbaa7232b3c721efeb954f68/System/net/System/Net/WebUtility.cs#L47-L157

**Comment by ArsenShnurkov** [comment]
So, we need a true hero, who will stop talking around, will take the debugger into hands, and will find the location of this bug in the code.

**Comment by EbenZhang** [comment]
The place to escape is easy to find. It might be a bug of a specific version of Mono, the Windows version of ApplicationSettingsBase.Save seems already escapes the xml.

Anyway, I don't like the idea to embed xml into another xml, a separate config for hotkeys is preferred so don't have to escape.

**Comment by ArsenShnurkov** [comment]
> "the Windows version of ApplicationSettingsBase.Save seems already escapes the xml."
I have no windows to check.

> It might be a bug of a specific version of Mono. The place to escape is easy to find.
The resolution then is to find the place in Mono, which should be fixed in upstream (or patched in distribution).

**Comment by EbenZhang** [comment]
Which version of mono are you guys using?

It escapes correctly in the follow env 

- Mint:  kernel 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:44:48 UTC 2015 i686 GNU/Linux
- mono-complete: version 3.2.8+dfsg-4ubuntu1.1, Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
- monodevelop: Version: 4.0.12+dfsg-2
- GitExtension: 2.49.x.x

Here is the config file in /home/<username>/.local/shared/GitExtensions/GitExte..../user.config

```
<setting name="Hotkeys" serializeAs="String">
    <value>&lt;?xml version="1.0" encoding="utf-16"?&gt;
&lt;ArrayOfHotkeySettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
  &lt;HotkeySettings Name="Commit"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="0" Name="AddToGitIgnore" KeyData="None" /&gt;
      .....
```

**Comment by EbenZhang** [comment]
To escape, you can add the `HtmlEncode` in `HotkeySettingsManager.cs`, at line 117 in method `SaveSettings` 

```C#
Properties.Settings.Default.Hotkeys = WebUtility.HtmlEncode(strBuilder.ToString());
```

and also need to decode at line 161, in method `LoadSerializedSettings`

```C#
using (StringReader reader = new StringReader(WebUtility.HtmlDecode(Properties.Settings.Default.Hotkeys)))
```

**Comment by McBen** [comment]
@EbenZhang hotkeys are working fine.
"WindowPositions" fails.

**Comment by EbenZhang** [comment]
My windowspositions do not have a nested xml for both windows and mono. The only change made recently is the [iseriliazable]. 2.48 doesnt have this attribute.

One of The difference between hotkeys and windowspositions is that the hotkeys converts itself to xml before saving to applicationsettings while windowspositionlist saves itself to application as an object. Maybe we should convert it as hotkeys does. Or just save it to a separate xml file.

**Comment by ArsenShnurkov** [comment]
Is it so difficult to add links to things? It's hypertext, why do you use it like wooden book page, while referring to file and line by filename and line number?

The attribute added was <a href="https://github.com/gitextensions/gitextensions/commit/49a1a04d77f5178afb009a4074d12bbea8b6d8e5#diff-648d16515c7f2d7962ee0df48164fb1eR34">Serializable</a>, not **I**Serializable

hotkeys <a href="https://github.com/gitextensions/gitextensions/blob/fe4bb94ca2a74dbbe14348dc41e96284fecdbe06/GitUI/Hotkey/HotkeySettingsManager.cs#L112-L118">converts itself to xml in method SaveSettings</a>, with a <a href="https://github.com/gitextensions/gitextensions/blob/fe4bb94ca2a74dbbe14348dc41e96284fecdbe06/GitUI/Hotkey/HotkeySettingsManager.cs#L17-L27">XmlSerializer object</a>

XmlSerializer can serialize objects of the specified type into XML documents, and deserialize XML documents into object of a specified type. If a property or field returns an <a href="https://msdn.microsoft.com/en-us/library/system.xml.serialization.xmlserializer.xmlserializer%28v=vs.110%29.aspx">array</a>, the extraTypes parameter specifies objects that can be inserted into the array.

XmlSerializer <a href="http://stackoverflow.com/a/12461510/1709408">don't care</a> about SerializableAttribute

The usage of XmlSerializer explains, thy we see XML, but <b>doesn't explain why that fragment (for hotkeys) is escaped</b>.

and I see a difference in the value of serializeAs attribute for 
<a href="https://github.com/gitextensions/gitextensions/blob/fe4bb94ca2a74dbbe14348dc41e96284fecdbe06/GitUI/app.config#L13">Hotkeys</a> (String) and
**WindowsPositions** (Xml):

    <setting name="Hotkeys" serializeAs="String">
    <setting name="WindowPositions" serializeAs="Xml">

**Comment by ArsenShnurkov** [comment]
Do anyone want to implement short (minimal) test example for this case? My mono version is "Stable 4.2.1.60/804ddbc Fri Nov 20 04:34:39 MSK 2015"

**Comment by EbenZhang** [comment]
> Is it so difficult to add links to things? It's hypertext, why do you use it like a wooden book page, while referring to file and line by filename and line number?

My message was written on a mobile phone.

I will upgrade my mono and try if I can reproduce the problem.

**Comment by EbenZhang** [comment]
I got the same error after upgraded to 4.x.x. it was working fine with 3.x.x

Will have a try to see if i can fix it.

**Comment by ArsenShnurkov** [comment]
the bug is in the code from the beginning - https://github.com/mono/mono/commit/495ce06e9e92e6edc7dbe36b86ce82277b3a1009#diff-b2d4f4179a5800410716180928ec2fefR117
May be some other bug in 3.x.x was compensating it...

**Comment by axiac** [comment]
GitExtensions version 2.48.05-Mono running on Ubuntu 14.04.1/Mono JIT compiler version 4.2.3

The problem is still there.

**Comment by EbenZhang** [comment]
the fix is in master branch, not for 2.48.05

**Comment by NevRA** [comment]
Why you can't release new build with that fix?

**Comment by KindDragon** [comment]
@NevRA because master branch contain other changes and bugs

**Comment by tiagolr** [comment]
This issue haunted me for a while, solved it by installing Mono from the website (instead of package manager), current version 4.6.2.7, using gitextensions again, yay.
