### ISSUE TITLE
new automcomplete is annoying

### ISSUE THREAD

**Issue by timabell** [gitextensions/gitextensions#2717]
I've recently upgraded to v2.48.03 and have discovered the new autocomplete feature in the commit box. I'm afraid it's driving me up the wall. If you want to start a new line and it's decided to suggest something you don't want it is impossible to get onto the then next line without it changing what you just wrote.

Infuriating to use I'm afraid.

**Comment by timabell** [comment]
workaround: hit escape

okay so it's not impossible but I'd never have guessed that

**Comment by jbialobr** [comment]
Autocompletion can be disabled in the settings.
