### ISSUE TITLE
Bad KDiff3 version

### ISSUE THREAD

**Issue by pmatas** [gitextensions/gitextensions#2723]
The Git Extensions 2.48.03 Setup installs the 64-bit version of KDiff3 0.9.98, which does not work on Windows 7 32-bit.

**Comment by KindDragon** [comment]
KDiff 32-bit doesn't work on many computers

**Comment by pmatas** [comment]
On the other hand, KDiff 64-bit doesn't work on any 32-bit system, does it? Maybe the Setup will have to contain both versions. Or at least say: "The KDiff version suitable for your system is not included in the Setup. Please download KDiff 32-bit from ..." You can't produce a broken installation and say "setup completed successfully."

**Comment by patricktokeeffe** [comment]
> You can't produce a broken installation and say "setup completed successfully."

Right. It's better to not install anything than to install a version which is guaranteed to not work.

**Comment by KindDragon** [comment]
Reverted back to 32-bit. May cause some issue on some platforms
