### ISSUE TITLE
Crash when trying to fetch for the first time.

### ISSUE THREAD

**Issue by fingolfin500** [gitextensions/gitextensions#2724]
Not had this issue myself, but it has happened to two other people I know.

1. Create a new local repository.
2. Configure the remote repository.
3. Attempt to fetch for the first time.
4. Crash.

See attached screen shots of error messages:

![error02](https://cloud.githubusercontent.com/assets/5487401/6822838/97f26d9c-d2da-11e4-9656-6c795cbd2291.png)
![error01](https://cloud.githubusercontent.com/assets/5487401/6822837/97eb0fac-d2da-11e4-92dd-4060371a82c0.png)

Problem only started when using the newest version of GE I believe.

**Comment by fingolfin500** [comment]
Update:

If we populate the local repository by pulling from the remote via other means (command line, another client etc...), then start using GE, it works fine. It just seems to be when trying to populate the local repository for the first time that trips it up.

**Comment by vbjay** [comment]
Try cloning instead of creating local repo and then fetching.  It will
create the local repo and setup the remote.

**Comment by KindDragon** [comment]
Similar bug fixed in 2.48.04
