### ISSUE TITLE
Move wix project to the separate solution

### ISSUE THREAD

**Issue by mnaoumov** [gitextensions/gitextensions#2729]
Currently default solutions include WIX project that is showing annoying warning if you don't have WIX installed. For debug purposes it is definitely not needed

**Comment by vbjay** [comment]
It's not needed.  You can build and debug just fine.  If you need to build
the setup run the correct script.

On Thu, Mar 26, 2015 at 7:05 PM, Michael Naumov <notifications@github.com>
wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitextensions/gitextensions/issues/2729>.
>



-- 
*Jay Asbury*
PC Repair and custom programs $30/hr 1hr min
My Biking Blog <http://vbjaybiking.blogspot.com>

**Comment by mnaoumov** [comment]
Well, it is a matter of taste. Personally I prefer to work without annoying warnings

**Comment by sharwell** [comment]
Why not just install WiX?

**Comment by mnaoumov** [comment]
Yeah, that's another approach. I will leave it up to the maintainer if he accepts my pull request or not. Personally I think that the Setup project is not needed in 99% of cases so why would we bother to have it in the main solution?

**Comment by vbjay** [comment]
Maintaining another setup solution is foolish. The scripts build the other
projects and the wix project.  If you debug, wix project does not build.

On Thu, Mar 26, 2015 at 7:35 PM, Michael Naumov <notifications@github.com>
wrote:

> Yeah, that's another approach. I will leave it up to the maintainer if he
> accepts my pull request or not. Personally I think that the Setup project
> is not needed in 99% of cases so why would we bother to have it in the main
> solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gitextensions/gitextensions/issues/2729#issuecomment-86754149>
> .
>



-- 
*Jay Asbury*
PC Repair and custom programs $30/hr 1hr min
My Biking Blog <http://vbjaybiking.blogspot.com>

**Comment by mnaoumov** [comment]
It is a valid point, I can't object. Let's see what maintainer decides

**Comment by sharwell** [comment]
I agree with the conclusion from @vbjay, but not the presentation. :wink:

One thing that I do like about having everything in one solution are the following:

1. It improves the accuracy of certain Find In Files operations
2. It encourages users to build the "true" entire solution more frequently, which improves the chances that certain types of mistakes will be caught earlier in the development process, and thus be less costly (it applies in the open source world as time even if money isn't changing hands)

**Comment by mnaoumov** [comment]
Well, I installed WiX and see other problems with this project.

1. It relies on the existence of bin\Release folders that don't contain the desired files if you build in Debug configuration. So at least configuration project should not be compiling in Debug configuration

2. Setup projects relies on the existence of external installers. The system cannot find the file '..\Bin\KDiff3-64bit-Setup_0.9.98-2.exe' and those are downloaded by **DownloadExternals.cmd** which should be added as a prebuild step to the Setup project

**Comment by mnaoumov** [comment]
@vbjay @sharwell I wonder how this Setup project ever worked for you. It had implicit dependencies of external installers and also on some other solutions. So the following scenario was never working:

1. Pull sources from the repository into a clean folder
2. Open solution in Visual Studio
3. Build

To make this working you have to run something like **BuildInstallers.VS2013.cmd** first at least once.

All of this makes participation in the project a bit harder for the newcomers.

I think everyone benefits if the compilation process is as simple as poosible. That was the reason I made the suggestion in this issue.

And BTW, I fixed all those dependencies in my pr #2746

**Comment by vbjay** [comment]
Look at the build scripts.

**Comment by KindDragon** [comment]
Sorry, I don't like maintaining separate solution for the installer.
