### ISSUE TITLE
Move Microsoft.TeamFoundation.Client references from GAC to NuGet

### ISSUE THREAD

**Issue by mnaoumov** [gitextensions/gitextensions#2731]
This would allow to build even if you don't have VS2012 installed

**Comment by KindDragon** [comment]
I think MS doesn't provide it on NuGet

**Comment by mnaoumov** [comment]
Yes, that's true. But there are some non-official packages. I am going to create the missing ones.

**Comment by KindDragon** [comment]
Microsoft may be unhappy with this :-)

**Comment by mnaoumov** [comment]
Probably, but since there are so many unofficial packages already, I don't think they would object
