### ISSUE TITLE
git-tfs?

### ISSUE THREAD

**Issue by MarkDHarris** [gitextensions/gitextensions#2735]
I would like to update the git-tfs plugin but I cannot find any documentation explaining how a plugin is expected to work.  

Can anyone point me to documentation for GitExtensions plugin development?

Thanks,
Mark

**Comment by KindDragon** [comment]
GitExt doesn't have git-tfs plugin. We only have plugin that show results tfs build server.

**Comment by MarkDHarris** [comment]
I am referring to https://github.com/git-tfs/git-tfs-gitextensions-plugin.  I would really like that plugin to work with the latest version of GitExt.  Right now, I use GitExt for almost everything and then have to drop into the cmd line to use git-tfs.  If GitExt had this plugin, I could use GitExt for all my work.

**Comment by pmiossec** [comment]
@MarkDHarris I was a heavy user of git-tfs (and end up as one of biggest contributor of git-tfs) and I can assure you that this plugin is not really needed to use git-tfs with GitExtensions.
I highly prefer to use the "script" feature of GitExtensions (that you will find in "Settings" => "Scripts").
You just have to add 2 or 3 scripts for the git-tfs commands that you use in your workflow (supposely `git tfs fetch`, `git tfs pull -r` and `git tfs rcheckin`) and that's all you need.
You could even add this command in the toolbar and you will end up winning a lot click and it will be more pleasant to use...

PS: But if you fix the plugin, it will be welcome ;)

**Comment by pmiossec** [comment]
@MarkDHarris I have fixed (and tested) the git-tfs plugin. See https://github.com/git-tfs/git-tfs-gitextensions-plugin/pull/17

**Comment by pmiossec** [comment]
@kinddragon this issue could be closed...

**Comment by KindDragon** [comment]
Would be cool if we find somewhere free nuget feed storage. So we could publish plugins there and support downloading plugins from nuget like in Resharper

**Comment by IDisposable** [comment]
I use mygit as my CI build and prerelease hosting, and publish to nuGet only on releases.
