### ISSUE TITLE
Don't warn about not being on a branch in the middle of a rebase

### ISSUE THREAD

**Issue by erik-kallen** [gitextensions/gitextensions#2760]
When working during a rebase (for example when using the "edit" action for a commit), GitExtensions will warn when amending the commit that
1. I am about to rewrite history (which is why I chose "edit"), and
2. That I am not on a branch, and I am asked to create one (or Continue).

At least question 2 should IMO not be asked during a rebase, and probably 1 should be supressed as well since I am already rewriting history.

**Comment by jbialobr** [comment]
Duplicates #3231
