### ISSUE TITLE
git v2.3.5 is released - When will it be supported by Git Extensions?

### ISSUE THREAD

**Issue by webmaster33** [gitextensions/gitextensions#2765]
git v2.3.5 is released - When will it be supported by Git Extensions?

**Comment by Radrik5** [comment]
Probably when msysgit releases it. Let's see what they answer to your question in msysgit issue tracker.

**Comment by webmaster33** [comment]
Strange answer: "Never, we are switching to CVS as it is fastly superior."
This must be a joke.

**Comment by KindDragon** [comment]
When they fix this issues: https://github.com/git-for-windows/git/milestones/First%20release%20of%20Git%20for%20Windows%20generated%20using%20the%20new%20SDK
