### ISSUE TITLE
Bad Error/Dialog Issue when cloning GitHub Repo 

### ISSUE THREAD

**Issue by TBRX103** [gitextensions/gitextensions#2767]
1. With GitExtensions configured to handle "github-windows:\\", click the Clone in Desktop button on a repository.

2. Configure the clone as needed, then hit clone.
![image](https://cloud.githubusercontent.com/assets/2601492/6991852/49edac5e-da61-11e4-800a-375fb953754c.png)

3. Once the clone is done, hit OK
![image](https://cloud.githubusercontent.com/assets/2601492/6991855/58ad1acc-da61-11e4-95be-7d9db6fdaa29.png)

4. Answer yes to the prompt to open the directory.
![image](https://cloud.githubusercontent.com/assets/2601492/6991856/612d8dd0-da61-11e4-9189-c293c39c6797.png)

5. "Clone failed" dialog appears.
![image](https://cloud.githubusercontent.com/assets/2601492/6991858/752f4b20-da61-11e4-8f37-e151fb58ce80.png)

I've tested this with multiple repositories, and this is occurring on a fresh new Windows 8.1 install.

**Comment by vbjay** [comment]
see #2493

**Comment by KindDragon** [comment]
Check version 2.48.04
