### ISSUE TITLE
[Feature request] Improve usability for "revision links" feature

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#2768]
Hi all,

I just started playing with the revision links feature and I really like the idea. Thanks for adding this in!

I do however see a major usability issue for people who are involved with a lot of different projects like me.

I work on a lot of different projects, mostly GitHub based ones, so it would be really useful to link the typical `#123` issue references to the relevant GitHub page.

Now if I want to set this up, I can't use "global" rules as the typical GitHub issue URI contains the `user` and `repository` name which would be different for each repo.

Using the local or distributed option would be fine, however, I would then need to set this up individually for each and every repository which gets really tedious really quickly.

If would be awesome if we could use more variables/placeholders like `%GITHUB_USER%` / `%GITHUB_REPO%` in the global rules, but I somehow think that will not be the solution as the info on the remote repo does not contain the specific variables we need - well it does, but would need to be regex filtered from the remote fetch URL, so is not directly usable -. Also, if there is more than one remote defined, it would be difficult to figure out which remote to use for the variables.

Alternatively using local rules with a way to copy rules would be an option, but then we would have to have access to all other repos to provide a list of potential rules to copy, which I can imagine is not practical either.
#### Proposed solution

So what I'm currently thinking is this:
Let the user define a global rule with arbitrary placeholders in them.

**Current behaviour**: if the user would then edit that rule in the "effective" screen, the global rule is changed.

**Desired behaviour**: if the user would edit the global rule in the "effective" screen, **_the global rule is copied to local rules and the edit is saved to the local rule only_**.

**End result**:
User can have a (non-effective) global rule and would just need to edit that rule for each repo to make it effective, rather than manually copy 5 text strings for each and every repo.

Does that make sense ? Opinions anyone ?

Smile,
Juliette

**_Related issues:_**
- https://github.com/gitextensions/gitextensions/issues/1582
- https://github.com/gitextensions/gitextensions/issues/2714
- https://github.com/gitextensions/gitextensions/issues/2753

**_Related docs which might need adjusting:_**
- https://github.com/gitextensions/GitExtensionsDoc/blob/master/source/settings.rst

**_Relevant screen:_**
![screenshot](http://snag.gy/BCDND.jpg)

**Comment by jbialobr** [comment]
Instead of placeholders I added ability to use data from remotes. 
1. Define which remotes to use. Leave blank to use all.
2. You can say to use only the first matching remote. If full names of remotes are given in 1) then matching remotes are sorted by its position in 1)
3. URL and PushURL can be used.
4. Regex to match details from remote's URLs.
5. Matches from Remote data go before matches from Revision data. You can capture server address in a separate matching group and create a common link for GitHub and GitLab.

![gitext](https://cloud.githubusercontent.com/assets/1003909/25234285/eb300738-25e1-11e7-942a-ae27b3ca6c0c.png)

**Comment by jrfnl** [comment]
@jbialobr Sounds awesome! I'm looking forward to trying it out in the next version of GitExtensions! Thank you so much for implementing this.

**Comment by eric-wieser** [comment]
@jbialobr: This doesn't work for me, as it seems to make the matched part of the remote lowercase before using it - URLs are case sensitive, and I need to preserve that case

**Comment by vbjay** [comment]
URLs are not case sensitive.

**Comment by vbjay** [comment]
Well actually the host or domain is not case sensitive. The path to the
endpoint can be but is not always date srnsutive. Depends on what is
hosting the resource.

**Comment by RussKie** [comment]
https://stackoverflow.com/questions/7996919/should-url-be-case-sensitive/7996997

**Comment by eric-wieser** [comment]
> The path to the endpoint can be but is not always case sensitive

That may be true, but my endpoint _is_ case-sensitive, so I'd consider this a bug

**Comment by jbialobr** [comment]
Please, report it as a separate issue.

**Comment by eric-wieser** [comment]
#5409
