### ISSUE TITLE
GitExtensions slow with many Submodules

### ISSUE THREAD

**Issue by mkjo** [gitextensions/gitextensions#2769]
Hello,

I have some repositories with a lot of submodules (some more than 100). For these repos GitExtensions behaves very slow when opening a repository in this context. It freezes up to 5 Seconds.

By profiling the software, I found out that the submodule status acqusition is the main reason for this.
To show the impact see the return null which improves the opening time:

```c#
        private Task GetSubmoduleStatusImageAsync(ToolStripMenuItem mi, GitModule module, string submodulePath)
        {
            return null; // Hides my problem :-)
            if (String.IsNullOrEmpty(submodulePath))
            {
                mi.Image = Resources.IconFolderSubmodule;
                return null;
            }
            var token = _submodulesStatusImagesCTS.Token;
            return Task.Factory.StartNew(() => .........
```
https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/FormBrowse.cs#L3089

I think a good solution could be that the submodule status acqusition is a configurable option. Some other idea would be that the acquistition can be put even "more" into background. I'm not sure if the task factory for >100 Tasks/Submodules is the blocker. (Btw, the GitExtensions 2.48 behaved even slower there, I see that there have been some changes already on this part of the code).

Can anyone give me some tips/hints and further information how to deal with this. I like to contribute the changes, though I'm not so familar with the code structure in GitExtensions.

Thanks in advance already for any help.

**Comment by ghanique** [comment]
I can imagine opening the repository is slow with that many submodules. But
isn't Git slow in general with that many submodules? I.e.: if you'd switch
branches and update the submodules, wouldn't you have to wait a long time
as well?

(Having a repository with sometimes more than 100 submodules *sounds* like
a very bad design, so I'd be interesting to know the use case here).

**Comment by mkjo** [comment]
The top level project master is just a "collector" of all the submodules, therefore we switch it not very often. Imagine a submodule is a driver, the branch/revision addresses different features. This design scheme is very common in atomotive industry, where a over-all covering api for different driver functionallity is too much overhead for the productive system.

Beside this, yes, a submodules are generally slow in windows, mainly because threads, forks/joins etc. makes heavy overhead in windows compared to linux. Submodule updating is about 10x faster in linux than in windows here.
(See for example:
http://git.661346.n2.nabble.com/Why-is-git-submodule-slow-under-windows-td7615390.html
http://stackoverflow.com/questions/6811435/why-does-cygwin-execute-shell-commands-very-slowly
)

Back to my main question, I like to improve the responsiveness of gitextensions there, so do you think my proposal is a good idea?

**Comment by ghanique** [comment]
Interesting :-)

I don't think I can comment on what the impact is if you don't query the
submodule status...

**Comment by KindDragon** [comment]
I think we should limit number of parallel called GetSubmoduleStatusImageAsync()
