### ISSUE TITLE
A crash with Unicode characters (e.g. 中国)

### ISSUE THREAD

**Issue by justanotheranonymoususer** [gitextensions/gitextensions#2771]
1. Have a commit message with the text "中国".
2. Try to use the filter.
3. Observe the crash.

The bug report in pictures:

* http://i.imgur.com/pFy6yOb.png
* http://i.imgur.com/EJdhYlP.png
* http://i.imgur.com/kphGJcp.png
* http://i.imgur.com/u5CWwO4.png

**Comment by Radrik5** [comment]
Can it be related to #2653?
Do you use TeamCity integration?

**Comment by justanotheranonymoususer** [comment]
> Can it be related to #2653?

It looks similar, but I can't say much more as I'm not familiar with the code internals.

> Do you use TeamCity integration?

I don't.

**Comment by KindDragon** [comment]
Can you try with latest version?

**Comment by justanotheranonymoususer** [comment]
It doesn't crash anymore. Thanks!
