### ISSUE TITLE
Can't use Github private repos anymore / Github Plugin API Keys ?

### ISSUE THREAD

**Issue by sebastienros** [gitextensions/gitextensions#2774]
Since last month I have not been able to use GE to manage Github private repositories. It worked for years then stopped. A simple check would be to ensure the current Api key and secrets for the github's plugin are still valid. I see that they haven't changed for a long time, and it might be expired, or blocked.

**Comment by ghanique** [comment]
Could be anything... Can you still push and pull using Plain Old Git (i.e.:
command line)?

**Comment by sebastienros** [comment]
Sorry, after trying wth my own keys it still didn't work, the I realized that I needed to use my oauth token as the password :/
