### ISSUE TITLE
VS2013 plugin commit plus branch name

### ISSUE THREAD

**Issue by neilx** [gitextensions/gitextensions#2775]
I keep losing the branch name from the GE toolbar. I reset it to take the image and text, but next time I open VS it has gone.

Before with branch name: http://screencast.com/t/gOEr9m7rF

Pull, then
After without Branch name: http://screencast.com/t/4FwIx3ZAPMP

Thi must be something that is being stored in the repository, but I have no idea what or where.

**Comment by RussKie** [comment]
Closing due to age
