### ISSUE TITLE
Uninstalling breaks VS2013

### ISSUE THREAD

**Issue by mkesper** [gitextensions/gitextensions#2776]
After uninstalling, I always get the following error when accessing a Form/Class:
No EditorOptionDefinition export found for the given option name
Adornments/HighlightCurrentLinelEnable
Parameter name: optionid
![screenshot 505](https://cloud.githubusercontent.com/assets/3063558/7084416/6fbcd926-df6d-11e4-8d23-f1ff7c216c21.png)

**Comment by mkesper** [comment]
Addendum: Wasn't able to cure this by re-installing, yet.

**Comment by mkesper** [comment]
Fix: http://stackoverflow.com/questions/23893497/no-editoroptiondefinition-export-found-error/23894744
After renaming that folder, I#m able to open .cs files again.

**Comment by KindDragon** [comment]
I think this isn't related to our plugin
