### ISSUE TITLE
Filtering crashes with ArgumentNullException

### ISSUE THREAD

**Issue by FlatlinerDOA** [gitextensions/gitextensions#2777]
--- GitExtensions2.48.03, Git 1.9.4.msysgit.0, Microsoft Windows NT 6.3.9600.0

**Comment by FlatlinerDOA** [comment]
Value cannot be null.
Parameter name: key

GitExtensions.exe [2.48.03]

Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d
1.1.2.0

   at GitUI.RevisionGrid.<>c__DisplayClass1d.<_revisionGraphCommand_Error>b__1c()

**Comment by EbenZhang** [comment]
Pretty sure it was fixed in #2598.
