### ISSUE TITLE
Новая висячая ветка

### ISSUE THREAD

**Issue by maxsmal** [gitextensions/gitextensions#2780]
Привет.
Возникает проблема с созданием новой висячей ветки. Приложение показывает, что всё выполняет, а после окончания просто вываливается с System.ArgumentNullException.

Taget site: Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d

Пробовал на нескольких репозиториях - всё одинакого.
P.S. If your are not understand russian language, say it, I'll translate it to english.

--- GitExtensions2.48.03, Git 1.9.4.msysgit.2, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by KindDragon** [comment]
Попробуйте версию 2.48.04, там исправлена похожая проблема
