### ISSUE TITLE
Ability to disable autocomplete functionality introduced by #2333

### ISSUE THREAD

**Issue by patricktokeeffe** [gitextensions/gitextensions#2789]
I just can't appreciate the changes made by #2333 ...in particular, the file name auto-completion. I dislike repeating myself in the commit message and find that file name suggestions are supremely distracting. 

RFE: Expose the ability to disable autocomplete in the commit message under 'Settings - Commit dialog'.

**Comment by chrischu** [comment]
Created a pull request (https://github.com/gitextensions/gitextensions/pull/2799). 

Sadly I cannot test the changes myself since I can't get the build to work where I'm at currently. I also suspect that translation has to be done for the new settings checkbox.

**Comment by corelgott** [comment]
+1

**Comment by jbialobr** [comment]
Closed by #2799

**Comment by mcsilver** [comment]
+1

**Comment by patricktokeeffe** [comment]
Kinda forgot about this one sorry.. nice work though!

**Comment by mcsilver** [comment]
Per #2799, it looks like an option to disable autocompletion is now released. Did I read that correctly? If so, where is that setting, please? I looked in Settings | Commit dialog and didn't see it.

Not sure how to check my version from the GUI but my gitextension.exe file version is 2.48.05. Do I need to update?

Thanks.

**Comment by RussKie** [comment]
You can find the version number via Help > About menu.

You can disable the auto complete via Settings:
http://git-extensions-documentation.readthedocs.io/en/latest/settings.html#commit-dialog-behaviour-provide-auto-completion-in-commit-dialog

![image](https://user-images.githubusercontent.com/4403806/34699789-650feb10-f533-11e7-82e1-862f4953b927.png)

**Comment by mcsilver** [comment]
Ah, I didn't think to launch the main .exe. Looks like the overall product version matches the .exe's file version.

..and now I see the note above it having been added to 2.49. Downloading now :)

Thanks.

**Comment by RussKie** [comment]
The current version is 2.50.03.

2.51 is about to be released shortly, with 2.51.RC1 is currently available
as well.
Check out the front page for the links

**Comment by mcsilver** [comment]
Looks like v2.50.02 is the "latest release"--at least before the RC. I'm good with that for now and maybe I'll check for 2.51 once it passes RC. Thanks.

**Comment by RussKie** [comment]
My bad, indeed .02

**Comment by mcsilver** [comment]
No worries!
