### ISSUE TITLE
Can not assign null value to UICommandsSource

### ISSUE THREAD

**Issue by ArsenShnurkov** [gitextensions/gitextensions#2790]
steps to reproduce:
1) start GitExtensions
2) open repository
3) stop git extensions

the console output is following:

https://gist.github.com/ArsenShnurkov/574063587aabeef77ad6

Mono-4.0.0

**Comment by ArsenShnurkov** [comment]
reproduced on mono 4.2.1.91/8862921

**Comment by EbenZhang** [comment]
Maybe check if the form was disposed in `RevisionsSelectionChanged`.

**Comment by ArsenShnurkov** [comment]
usually nobody checks IsDisposed in event handlers. They should not be called in such situation at all.
http://thatextramile.be/blog/2008/08/why-you-should-always-unscubscribe-event-handlers/

**Comment by EbenZhang** [comment]
Will unsubscribing the `RevisionsSelectionChanged` in the `Dispose` work in this case?

Checking the parent doesn't express the intention of code very well, you may need to put some comments.

**Comment by ArsenShnurkov** [comment]
Yes, this is possible, to unsubscribe in Dispose:
http://stackoverflow.com/questions/91778/how-to-remove-all-event-handlers-from-a-control

**Comment by karyon** [comment]
this particular bug is fixed so this can be closed right?
