### ISSUE TITLE
Usability: Commit Window has "Reset all changes" next to "Commit and push"

### ISSUE THREAD

**Issue by mouseas** [gitextensions/gitextensions#2792]
The `Reset all changes` and `Reset unstaged changes` buttons should not be near the `Commit` and `Commit & push` buttons.

The commit buttons preserve data against loss. The reset buttons destroy data. As a user, I have clicked the `Reset all changes` button by mistake when trying to click the `Commit and push` button. With a new branch, both buttons bring up a confirmation dialog, and it's too easy to mistakenly delete hours worth of work when you're instead trying to preserve it. While it is possible in many cases to recover from this loss, a small UI change would prevent the problem in the first place.

At the very least, some whitespace should be added between these pairs of buttons. It would also be a good idea to put the `Amend Commit` checkbox with the commit buttons, since amending a commit is not relevant to resetting changes.

Ideally, the reset buttons should be in an entirely different location on the window, such as underneath the Staged Files list.

**Comment by ghanique** [comment]
What about removing those buttons? If you want to reset something you can
do that on the top left of the commit window. Those are much more explicit
actions and less likely to be triggered by mistake.

**Comment by Radrik5** [comment]
This is configurable. See Settings - Commit dialog.

![image](https://cloud.githubusercontent.com/assets/9339459/7491838/5f6c651c-f3f6-11e4-80fd-7799aa1d9d09.png)

**Comment by ghanique** [comment]
Great! I'll disable it right away! :-)
Thanks!

**Comment by mouseas** [comment]
@Radrik5 I will remove them as well, though I stand by what I said about putting some space between the two or moving the reset buttons to an entirely different location on that window.

**Comment by austinbowen** [comment]
Yeah, hours of work lost, just like that.  Accidentally clicked "Reset All Changes" while trying to commit.

IMO, change resets do not belong in the Commit dialogue in the first place.

If you've got to have them there, then at LEAST move them away from the Commit buttons, AND add a confirmation dialogue, rather than wiping all changes with a single click.

Yes, I have now disabled the buttons under settings.  Maybe they should be disabled by default?  Hmm...

I am trying to contain my frustration.

**Comment by mouseas** [comment]
@austinbowen there are ways to recover lost changes from a reset if this just happened. The more you do since losing it, the harder it gets.

Also worth noting, the Reset buttons **do** have confirmations, but so do the commit buttons in some cases, so it's easy to click through them without reading them.

**Comment by austinbowen** [comment]
@mouseas yep I tried file recovery, but didn't get anywhere.

As for the confirmation, I must not have noticed it.  I'm not going to go back and check, though ;) I'll take your word for it.  I've edited my original comment, thanks.

**Comment by mouseas** [comment]
@austinbowen Some IDEs have recovery options as well. Eclipse, for example, can recover files from the current session. Steps [here](http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-87b.htm). If you're not using Eclipse, which IDE are you using?

**Comment by austinbowen** [comment]
Visual Studio.  I've already rewritten what I was working on, but if you
know of instructions for that, then they would still be good to have for
reference.

--
Austin Bowen
austin.bowen.314@gmail.com  |  (843) 801-3618  |  saltyhash.noip.me

**Comment by mouseas** [comment]
@austinbowen It looks like VS's options are limited. [This SO answer](http://stackoverflow.com/questions/897956/recovering-file-from-the-visual-studio-document-cache) covers how to manually access doc recovery if VS crashes, which isn't what you're dealing with. [This article](https://msdn.microsoft.com/en-us/library/ms245463.aspx#restore_client_vs) covers restoring deleted files, but it doesn't seem to apply to recover changes to a file.

Your best bet sounds like git, and it depends entirely on whether you did `git reset` with `--hard` or without `--hard`. See [here](http://stackoverflow.com/questions/12765204/undo-git-reset-merge) if you didn't use `--hard`. If you did, you're out of luck.

**Comment by Radrik5** [comment]
It's possible to recover staged revisions if you use "stage" (git add) before commit. See `git fsck` and `git update-index --cacheinfo`.

**Comment by gerhardol** [comment]
![image](https://user-images.githubusercontent.com/6248932/35773152-1fbd03f6-094a-11e8-8b52-8965023674a5.png)

This was changed in 2.51. The reset buttons are not at the button due to Mono limitations.
