### ISSUE TITLE
Unable To Change Branches (System.ArgumentNullException)

### ISSUE THREAD

**Issue by laurin1** [gitextensions/gitextensions#2793]
Value cannot be null.
Parameter name: item

Target Site: Int32 AddInternal(System.Object) @ System.Windows.Forms.ComboBox+ObjectCollection
Application: GitExtensions.exe [2.48.03]
NBug: 1.1.2.0
CLR: 4.0.30319.34209

I don't know what is causing this, but it happens when I change branches in a particular repo. I also have a bunch of blank entries in my branch drop-down menu.

![capture](https://cloud.githubusercontent.com/assets/75857/7501275/73e39914-f3f8-11e4-8a8f-a8ff85dc11d6.JPG)

**Comment by Radrik5** [comment]
@laurin1, could you please attach the output of `git show-ref` command?

**Comment by RussKie** [comment]
Is this still an issue with the current version?

**Comment by laurin1** [comment]
I don't even remember this issue or what repo that was, so I guess the issue is obsolete.
