### ISSUE TITLE
Put "edit committ" in the context menu

### ISSUE THREAD

**Issue by mortb** [gitextensions/gitextensions#2794]
I think it would be nice to have an "edit commit" command in the context menu.
We use gerrit and we tend to some edits to my commits before they are merged in to the repository.
We mostly do my edits by using interactive rebase with either "edit" or "fixup" commits. This is somewhat error prone as errors do occur when moving lines in the commit list.

Having an option in the context menu to edit the commit without having to interactive rebase would really be a killer feature for us.

**Comment by Radrik5** [comment]
@mortb, in the context menu for the commit you want to edit try "Advanced - Fixup commit". Then run interactive rebase with Autosquash option.

**Comment by mortb** [comment]
@Radrik5, many thanks for your reply. 
That is good. but what if we could do it all in one step with no need for interactive rebase?
I also have to click "show options" in rebase dialog to check the "interactive rebase" checkbox which makes it many clicks

I do this quite a lot so having this in the context menu would be a good feature for me.

**Comment by Radrik5** [comment]
Anyway, behind the scenes there will be interactive rebase. Git doesn't have an "edit commit" command and Git Extensions is just a wrapper over Git commands. In addition, merge conflicts are possible and you will have to resolve them manually and then click the "Continue rebase" button. Without merge conflicts you can edit only the most recent commit, but for that there is "Amend Commit" option.

What do you think about adding "Commit & Autosquash" button to the "Fixup commit" window? It will call interactive rebase with the parent of the selected commit and "Autosquash" option.

**Comment by mortb** [comment]
Yeah, that would seem to be a nice solution.
To summarize you mean that the command:
"context menu" -> Advanced -> Fixup
would bring up the commit dialog. The commit dialog would be like the "ordinary" commit dialog but there would be a "Commit & auto squash" button. (maybe some ordinary buttons needs to be disabled / invisible)

Pressing the "commit & auto squash" would (behind the scenes) lead to 
1. the files being committed 
2. an interactive rebase being run which would fixup (meld) the commit into the selected commit

Yes that would be nice :+1: 
Only that for me this would not be in the "advanced" sub menu as I do it a lot, but I could live with that....
