### ISSUE TITLE
Option to disable 'Commands' -> 'Create branch' in menu bar

### ISSUE THREAD

**Issue by valpa** [gitextensions/gitextensions#2800]
We are using Git-extension in our company with git-flow plugin installed and enabled.

Everyone shall use git-flow to create feature/hotfix branches. But sometime people misused 'Commands' -> 'Create branch' to create branch.

Is there a way to disable the 'Commands' -> 'Create branch' (mark it gray) to avoid the above accident?

**Comment by KindDragon** [comment]
Now we do not have such feature

**Comment by ghanique** [comment]
We, too, work extensively with Git Flow. But there many reasons why you'd
want to create branches. Creating a feature is just one of them. I would
never disable it.

**Comment by valpa** [comment]
We are not asking to disable it. Just the option/configuration able to disable it if needed.
