### ISSUE TITLE
Search by the author does not work

### ISSUE THREAD

**Issue by vzabavnov** [gitextensions/gitextensions#2804]
In the tree view do right click on any commit -> Copy to clipboard->Author
Past what was copied to Filter entry field and select "Author" in the drop down box. 
Hit Enter
Result: all commits filtered out
Expected result: Show commits with Authors from Filter box

**Comment by KindDragon** [comment]
Select only Author and it should work

**Comment by vzabavnov** [comment]
Thanks, it works that way.

I still think it should work in combination with the other options

 

 

With Best Regards

 <mailto:zabavnov@gmail.com> Vadim Zabavnov

**Comment by KindDragon** [comment]
Yes, we have issue about that

**Comment by mamidon** [comment]
+1 to changing this filter UX, I wasn't expecting checkbox functionality here.  The vast majority of combinations of the filter options will hide everything, there's not much point that I can see in keeping it like this.  Perhaps switching the filter options to behave like radio buttons would be much more clear.

That's just my 2 cents.

**Comment by RussKie** [comment]
Is this still an issue for you in the current version?

![image](https://user-images.githubusercontent.com/4403806/29599610-58daed90-8814-11e7-91a6-506e54164fda.png)

**Comment by vzabavnov** [comment]
Just checked with the latest source code – still an issue

 

Just to clarify, the steps:

1.	Make sure nothing is filtered and filter options selected only “Commit”
2.	Right click at any commit where author’s name contains two or more parts and “Copy to clipboard”->Author
3.	Past to the filter entry field
4.	Select filter option Author. Now to options selected Commit and Author. 

Result – all records disappears

 

If selected only one option – Author – works
