### ISSUE TITLE
Consider replacing (or augmenting) DownloadExternals.cmd with a custom build target

### ISSUE THREAD

**Issue by sharwell** [gitextensions/gitextensions#2805]
~~The following code shows a clean way to download external dependencies using PowerShell:~~

~~https://github.com/rackerlabs/dotnet-collections/blob/9e835d7b7d41067b9823b935ecf952789b739c7e/build/build.ps1#L32-L39~~

Pull request #2746 invokes the **DownloadExternals.cmd** script as a pre-build step. It would be better to create a **.targets** file containing targets with declared inputs and outputs rather than rely on executing an arbitrary pre-build step.

@KindDragon I am aware this is a poorly-worded issue report. :disappointed:

**Comment by sharwell** [comment]
This might work

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <SetupDependency Include="../bin/Git-1.9.5-preview20141217.exe">
      <Source>https://github.com/msysgit/msysgit/releases/download/Git-1.9.5-preview20141217/Git-1.9.5-preview20141217.exe</Source>
    </SetupDependency>
    <SetupDependency Include="../bin/KDiff3-64bit-Setup_0.9.98-2.exe">
      <Source>https://downloads.sourceforge.net/project/kdiff3/kdiff3/0.9.98/KDiff3-64bit-Setup_0.9.98-2.exe</Source>
    </SetupDependency>
  </ItemGroup>

  <PropertyGroup>
    <ResolveReferencesDependsOn>
      $(ResolveReferencesDependsOn);
      DownloadSetupDependencies
    </ResolveReferencesDependsOn>
  </PropertyGroup>

  <UsingTask TaskName="DownloadFile" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
    <ParameterGroup>
      <Source ParameterType="System.String" Required="True"/>
      <Destination ParameterType="System.String" Required="True"/>
    </ParameterGroup>
    <Task>
      <Reference Include="System"/>
      <Code Type="Fragment" Language="cs">
        <![CDATA[
        new System.Net.WebClient().DownloadFile(Source, Destination);
        ]]>
      </Code>
    </Task>
  </UsingTask>

  <Target Name="DownloadSetupDependencies"
          BeforeTargets=""
          Outputs="@(SetupDependency)">

    <DownloadFile Condition="!Exists(%(SetupDependency.Identity))"
                  Source="%(SetupDependency.Source)"
                  Destination="%(SetupDependency.Identity)"/>

  </Target>
</Project>
```

**Comment by KindDragon** [comment]
I don't like about PowerShell that it doesn't work without changing execution policy (http://superuser.com/a/106363/64719). We'll have to tell every new developer how to do it.

**Comment by sharwell** [comment]
@KindDragon Everyone eventually needs to do that anyway, and it's a one-time thing. :smile: 

Regardless, I've now transformed this issue into a replacement using an MSBuild target.

**Comment by mnaoumov** [comment]
@KindDragon, actually you don't have to change execution policy globally to execute PowerShell scripts. You can always run the following command from the command prompt or even include it as an Exec step in your MSBuild script.

    PowerShell.exe -ExecutionPolicy Bypass -Command path\to\script.ps1

I used this approach for my build scripts and it works perfectly fine everywhere. I would really encourage to switch to PowerShell from cmd scripts as PowerShell syntax is much simpler and powerful

**Comment by RussKie** [comment]
Related work #2746 #3906
