### ISSUE TITLE
have exception FileLoadException on System.Net.Http

### ISSUE THREAD

**Issue by vzabavnov** [gitextensions/gitextensions#2806]
The exception happened after fresh install. if run under debugger - it works. I guess some installed components is missing.

p.s. I see in my GAC System.Net.Http version 4.0 but the application has referenced 2.2.29.0.

**Comment by vzabavnov** [comment]
As I found the solution has two version of System.Net.Http. Also some packages exists with different version for different project in the solution. For instance there are two version of Microsoft.Bcl.Build - 1.0.14 and 1.0.7. the same is for Microsoft HTTP Client Libraries - 2.1.10 and 2.2.29

**Comment by KindDragon** [comment]
Thank you. I will check it. What GitExt version you using?

**Comment by vzabavnov** [comment]
The latest: 3771d9d95500549d5d8963ef083ebdb1336f205b

 

 

With Best Regards

 <mailto:zabavnov@gmail.com> Vadim Zabavnov
