### ISSUE TITLE
Add an option to keep the Commit dialog open after committing changes

### ISSUE THREAD

**Issue by behrangsa** [gitextensions/gitextensions#2808]
I usually split my changes into multiple small commits. At the moment after committing the current staged changes, the dialog closes.

It would be nice if it was possible to keep it open (and let the user close it explicitly).

**Comment by Radrik5** [comment]
There is such option in the commit dialog:
![image](https://cloud.githubusercontent.com/assets/9339459/7765894/3566f656-006c-11e5-945d-fd20a9398378.png)
