### ISSUE TITLE
Linker error in GitExtSshAskPass

### ISSUE THREAD

**Issue by danielmenzel** [gitextensions/gitextensions#2811]
I got the error
`LINK : fatal error LNK1104: cannot open file ',5.01'`
when building GitExtSshAskPass.sln in VS2012, but it can be easily fixed:

> In the project properties, under Linker -> System, make sure that you set the SubSystem property    (either to Console for console applications, or to Windows for DLLs and non-console applications).

(see http://stackoverflow.com/questions/24012154/linker-error-when-using-v110-xp-cannot-open-file-5-01)

**Comment by KindDragon** [comment]
Fixed in 11db767
