### ISSUE TITLE
Bisect labels size problems on french version

### ISSUE THREAD

**Issue by Delavy** [gitextensions/gitextensions#2813]
In the french version, when doing Bisect, the popup with the buttons is to wide enough to see the end of the text, which is the most important part. 
The 2nd and 3rd buttons have the same text, which is "Marquer la révision courante comme" ( "mark the current revision as"). The ending of the labels  ("good" and "bad") are missing, making this function unusable (the popup is not resizable).
![bissect](https://cloud.githubusercontent.com/assets/1388970/7787323/24575dc4-0206-11e5-8c63-b40d2065fe2a.PNG)

**Comment by KindDragon** [comment]
Hi, thank you for reporting.

You can try come up with a shorter name for the button https://www.transifex.com/projects/p/git-extensions/translate/#fr/ui-master/22113687

**Comment by Delavy** [comment]
Hi. Thank you for the tip, I have created an comment/issue on the translation, but unfortunately this name is probably the most explicit.

**Comment by MichaelPereira** [comment]
@Delavy What about skipping "Marquer"? It looks like it would fit in the box without needing to resize it:

> Marquer la révision courante comme mauvaise
> La révision courante est mauvaise

> Marquer la révision courante comme bonne
> La révision courante est bonne

If you agree I can try to change it on the translation website (I'm not sure how the workflow works to integrate it in the next versions)
