### ISSUE TITLE
Update Visual Studio Gallery Download Link 

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#2814]
When a release is made, the download link on https://visualstudiogallery.msdn.microsoft.com/8f594baa-e44e-4114-8381-e175ace0fe97?SRC=VSIDE  needs to be updated.

**Comment by KindDragon** [comment]
@spdr870 Can you do that? Or it's better to change to https://sourceforge.net/projects/gitextensions/

**Comment by phillijw** [comment]
Before changing to sourceforge, see #2818

**Comment by RussKie** [comment]
Is this still relevant?
