### ISSUE TITLE
VS 2015 support

### ISSUE THREAD

**Issue by remcoros** [gitextensions/gitextensions#2815]
It seems VS 2015 doesn't support addins (.Addin) anymore and only uses vsix style extensions.

I didn't find an issue for it here yet, so here it is.

Probably have to package the VS addin as a vsix extension and change the installer.

**Comment by BraveNewMath** [comment]
I was looking for this as well.  Once you get used to git extensions buttons within visual studio, it's hard to go back to not having them.

**Comment by gbreeze** [comment]
Would be great if this vs-plugin is soon available.

**Comment by juanchavezlive** [comment]
The RTM version of VS 2015 is about to be released. Does anyone knows if there is VSIX extension on the way ?

**Comment by KindDragon** [comment]
for information https://msdn.microsoft.com/en-us/library/dn246938.aspx?f=255&MSPPError=-2147217396

**Comment by david-poirier-csn** [comment]
Please do, missing it already in VS2015.

**Comment by lanfeust69** [comment]
I just created #2885

**Comment by juanchavezlive** [comment]
great, thank you very much @lanfeust69 for begin the solution that nobody did before

**Comment by remcoros** [comment]
There is a VS2015 extension for Git Extensions here: https://visualstudiogallery.msdn.microsoft.com/35c2f314-a6ab-479a-b4a3-cff99103d32f?SRC=VSIDE

It works pretty good, full menu's, working commit button with branch name, etc.

I wonder why the developer is not contributing it here though.

**Comment by gbreeze** [comment]
@remcoros Works fine, thanks for the hint!

**Comment by Aleksanderis** [comment]
Looks like there is no context actions available yet with VS2015 extension.
I mean like calling context menu in a editor - there is no quick action to check history/differences about the file. Same about Solution Explorer.. So for now there is not much help from it, but it's a good start and hope it will be added pretty soon.;)

**Comment by tofutim** [comment]
will this get incorporated into the main branch? what is the scoop?

**Comment by rloveless** [comment]
@remcoros, The github you mentioned here:
https://github.com/tasadar2/gitextensions/tree/Plugin
says it only supports VS 2015.  Were you able to build it to work with 2015?  

Has anyone had any luck with getting gitExtension working with VS 2015?  I'm really missing the feature to pull the file history.

**Comment by SeanFeldman** [comment]
I'm using https://visualstudiogallery.msdn.microsoft.com/35c2f314-a6ab-479a-b4a3-cff99103d32f?SRC=VSIDE with 2015

**Comment by vbjay** [comment]
Not made by us.
https://visualstudiogallery.msdn.microsoft.com/site/search?f%5B0%5D.Type=User&f%5B0%5D.Value=Joshua%20Cherry
.
Vs

https://visualstudiogallery.msdn.microsoft.com/8f594baa-e44e-4114-8381-e175ace0fe97

**Comment by programcsharp** [comment]
Joshua Cherry's version works for me as well. Looks like it's just the shell buttons in VS, and it calls out to an already installed gitextensions.

**Comment by l3m** [comment]
Is there any progress on this? I really miss the great integration of Git Extensions with the previous Visual Studio versions in VS2015...

**Comment by linquize** [comment]
@l3m  Have you look at #2885?

**Comment by l3m** [comment]
@linquize Oh, great. And already merged. :)

**Comment by senzacionale** [comment]
any new infos about integration with VS 2015?

**Comment by vbjay** [comment]
I just run the program beside visual studio.  Gitextensions is not the
github extension.  Github extension is used to hook into github projects.
Gitextensions has a LOT more features.  I do wish someone would get visix
extension going.

https://msdn.microsoft.com/en-us/library/bb166030.aspx

**Comment by KindDragon** [comment]
> any new infos about integration with VS 2015?

Now we need to figure out how to add installation VSIX package and update it using WIX

**Comment by vbjay** [comment]
https://msdn.microsoft.com/en-us/library/dn246938.aspx

**Comment by KindDragon** [comment]
http://blog.majcica.com/2015/02/04/installing-vsix-package-via-wix-installer/

**Comment by willemodendaal** [comment]
I'm confused... should the Solution-Explorer context menus be there or not? I don't see them in VS2015, even with the GITEXT installed (and top menu item visible).

**Comment by willemodendaal** [comment]
Cool, thanks KindDragon :+1:

**Comment by vbjay** [comment]
They stopped supporting com addins and only support visix addins.

**Comment by lanierhall-doubleline** [comment]
Literally the most useful thing needed is View file history in visual studio.

**Comment by fschmied** [comment]
If context menus are not supported in the new extension, I'd propose moving the file history command to the toolbar instead. I'm currently also working with Joshua Cherry's extension, and this is the only feature I miss.

**Comment by jacekrud** [comment]
While we are waiting for resolution of this issue, there is a workaround. 

Context menu can be altered manually:
1) add external tool: Tools -> External Tools -> Add
     title: GitExt History command
     command: C:\Program Files (x86)\GitExtensions\gitex.cmd
     arguments: filehistory $(ItemPath)
2) add context menu: Tools -> Customize...
     select 'Commands' tab
     select 'Context menu' radio button
     pick 'Project and Solution Context Menus | Item'
     click 'Add command', select 'Tools' category then select 'External Command X' (where X is 1-based index of extenal tool added in step 1)

**Comment by nul800sebastiaan** [comment]
Any reason the `GitExtensionsVSIX` project is not included in the `GitExtensions.VS2015.sln`? It builds fine in VS2015.. and the VSIX works great by the way. I've PRed it if it's an oversight, unless there's a good reason not to include it?
https://github.com/gitextensions/gitextensions/pull/3288

**Comment by jj30** [comment]
Not a single thing worked for me. I suppose I must use regular git, without VS extensions.

**Comment by vbjay** [comment]
Remove any git extensions from the addin folder. Uninstall git extensions.
Reinstall.

**Comment by jj30** [comment]
This comment is for people who have read this whole thread and think it STILL DIDN'T work, as I did. The plugin you need for VS2015 is by Henk Westhuis -- none of the other ones work. It won't produce the menu you saw in the VS toolbar that the other plugins did (even though those menu items weren't functional).

You'll need to reclone your git project with the new plugin installed before you notice any plugin stuff to Visual Studio.

(And even then you won't notice "plugin stuff" until you make a change to a file.)
