### ISSUE TITLE
Moving away from sourceforge

### ISSUE THREAD

**Issue by remcoros** [gitextensions/gitextensions#2818]
Did you guys see the fuzz around this: http://arstechnica.com/information-technology/2015/05/sourceforge-grabs-gimp-for-windows-account-wraps-installer-in-bundle-pushing-adware/

You might want to consider moving to a different mirror.

**Comment by phillijw** [comment]
Came here to post the same issue!

**Comment by KindDragon** [comment]
Hi. We already have issue for that #2552
