### ISSUE TITLE
Leaving sourceforge for download place?

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#2820]
I read some unpleasant things about sourceforge these last days...

For example, http://helb.github.io/goodbye-sourceforge/

Don't you think it is time to move completly from sourceforge and use the [release feature](https://github.com/blog/1547-release-your-software) of github [that your partly use](https://github.com/gitextensions/gitextensions/releases) to upload the binaries?

**Comment by remcoros** [comment]
duplicate of #2818

But yes, looks like sourceforge is going down the same road as e.g. cnet, tucows and experts-exchange. so sad

**Comment by KindDragon** [comment]
Hi. We already have issue for that #2552

**Comment by pmiossec** [comment]
Very sorry for the duplicate!

**Comment by KindDragon** [comment]
No problem
