### ISSUE TITLE
System.NullReferenceException on load

### ISSUE THREAD

**Issue by killerkalamari** [gitextensions/gitextensions#2825]
Installed 2.48 on a coworker's machine (Windows 7, 64-bit). The install process went fine, but after selecting the language, a System.NullReferenceException was thrown. Screenshots:

![nre1](https://cloud.githubusercontent.com/assets/5439104/7971564/75af9dc0-09fa-11e5-97d6-1cb39cc1bde4.png)
![nre2](https://cloud.githubusercontent.com/assets/5439104/7971565/75b1d3c4-09fa-11e5-8d0b-ee976ec2b829.png)

I had him uninstall 2.48 and gave him 2.48.5, and he got the same exception. I had him uninstall and delete the .gitextensions files in his user folder, same results (screenshots made at this later point). None of my other coworkers have had these exceptions, so I suspect a problem on his machine, but what might be different, I have no idea.

He also can no longer use Visual Studio 2012, because he gets this exception:

![vs2012](https://cloud.githubusercontent.com/assets/5439104/7971566/75b5b638-09fa-11e5-9bcc-34e11496c90a.png)

However, Visual Studio 2010 seems to still work fine, and the GitExtensions toolbar shows up.

**Comment by killerkalamari** [comment]
He rebooted his machine and the exceptions went away.

**Comment by KindDragon** [comment]
Cool, nice
