### ISSUE TITLE
2nd line of long Commit messages shows just a few pixels

### ISSUE THREAD

**Issue by vanandel** [gitextensions/gitextensions#2826]
--- GitExtensions2.48.05, Git 1.8.3.1, Unix 3.10.0.229, Mono 4.0.1 (tarball Sun May 17 07:06:24 UTC 2015)
Commit messages that are too long for the display area show just a few pixels of the remaining text, as shown in the screen shot.

The only way to show the entire message is to widen the GitExtensions window, which may not work on a small laptop screen.  I'd suggest showing the entire commit message at the top of the Commit info window

![gitexensions_screenshot](https://cloud.githubusercontent.com/assets/1000153/7972634/8b53d77a-0a3d-11e5-8a68-0d233752469b.png)

**Comment by GintasS** [comment]
Abandoning this because of age.

**Comment by gerhardol** [comment]
Commit messages can be viewed in tooltips if too long for the subject
