### ISSUE TITLE
Multiple Projects with seperate respositories under same VS solution issue

### ISSUE THREAD

**Issue by clemsontiger** [gitextensions/gitextensions#2833]
So recently updated to version 2.48.05. I have a Visual Studio solution that contains 2 VS projects, each with its own git repository. When I select one or the other in the Solution Explorer window, my gitext toolbar text for Commit shows the appropriate repositories branch, however if I select my 2nd project in Solution Explorer and then actually open the commit dialog, pull or push dialogs, every dialog acts like my 2nd project's repository is the same as the first project's repository. Previously I was on version 2.47.X of gitext and did not have this issue. I've already tried removing the second project and adding it back, but it has not helped. Additionally it acts like my 2nd project's remote branch is the same as the first.... With the exception of the Commit area of the toolbar, all of gitext is acting like my 2nd project repository is not there and that both projects are part of the same repository... 

Any help is appreciated?

**Comment by clemsontiger** [comment]
had to drop back to gitext version 2.47.3 and it's working correctly again....

**Comment by vbjay** [comment]
You should have the git repo in the root folder and if you want a seperate
git repo, use submodules.

**Comment by clemsontiger** [comment]
what this a change since version 2.47.3 ?

**Comment by Radrik5** [comment]
Often submodules is a bad choice because they are too static.
http://somethingsinistral.net/blog/git-submodules-are-probably-not-the-answer/

**Comment by vbjay** [comment]
Fine. Use subtree.

**Comment by Radrik5** [comment]
Subtree duplicates history of sub repo in root repo. Usually you need to share a common repo among projects, not to copy it into each of them.

**Comment by vbjay** [comment]
Having separate repos in the same solution is a bad idea.  Look at how
gitextensions does it. We have a few submodules. It is the best way to do
it. Create a new root folder and clone the master project repo. Then add a
submodule of the other project.

**Comment by clemsontiger** [comment]
What git extensions version made this change? Apparently all this time all the way up to version 247.3 they've thought it's been fine, now it's a bad idea? Why? We've had zero issues with solutions containing multiple projects with their own repos, and GIT Extensions has worked perfectly fine for us. I guess we'll just stay on git extensions 2.47.3 for the time being.

**Comment by Radrik5** [comment]
We also have two separate repos in the same solution. The approach has its advantages and disadvantages but all in all in our case it's better that submodules, subtrees, android repo, or Gitslave.

**Comment by clemsontiger** [comment]
Still disappointed that I can't use separate repositories under the same solution. We have a common project that we use with multiple other projects. Now I'll have to open the common project separately every time I need to commit a change to it.  Just a hassle and disappointing considering past versions of gitextensions allow for this.

@vbjay you originally said "Having separate repos in the same solution is a bad idea.". Why? Any supportive links? Trying to understand why it's a bad idea. We've not had any issues with it.

**Comment by clemsontiger** [comment]
Still disappointed that I can't use separate repositories under the same solution. We have a common project that we use with multiple other projects. Now I'll have to open the common project separately every time I need to commit a change to it.  Just a hassle and disappointing considering past versions of gitextensions allow for this.

@vbjay you originally said "Having separate repos in the same solution is a bad idea.". Why? Any supportive links? Trying to understand why it's a bad idea. We've not had any issues with it.

**Comment by niwrA** [comment]
Would it make sense in this scenario to branch (one of the) the two projects to a shared repository?

**Comment by clemsontiger** [comment]
@niwrA not sure what you mean. both repositories are already shared among the team. Let me better explain our scenario: say we have 3 projects:

Project 1 
Project 2 
Project C ("C" for the common project)

We then have 2 Visual Studio Solutions:
Solution 1 (contains Project 1 and Project C)
Solution 2 (contains Project 2 and Project C)

when we build either solutions, the built files from Project C get outputted into the relative Project 1 or Project 2 to be used. Our issue is that as we're developing Projects 1 and 2 via their Solution 1 or 2, we may want to add to Project C, but we can't directly commit to Project C's repository from within Solution 1 or Solution 2 because of GitExtensions -- when we go to commit to Project C, GitExtensions only sees Project 1 or Project 2's repository, not Project C's. Ironically, the gitextensions toolbar actually shows the correct branch for Project C, but doesn't when the commit window is open. Go figure. Hope this better explains things...

**Comment by vbjay** [comment]
Use submodules.

**Comment by clemsontiger** [comment]
@vbjay  Again, "Having separate repos in the same solution is a bad idea." Why?

**Comment by vbjay** [comment]
Git uses the idea of a root folder. It doesn't work that way. Submodules is
the git feature designed for this problem.

**Comment by clemsontiger** [comment]
That doesn't really explain why it's "a bad idea", but obviously I'm not going to get that out of you nor change your mind about supporting multiple repos in a solution again, so I'll just drop it and look more into submodules or find another git tool for Visual Studio that meets our needs.

**Comment by vbjay** [comment]
How does git work?  It examines files from root and bellow. If you have
project c in the path of the root git repo then it will be tracked in the
parent repo. Get it.

**Comment by vbjay** [comment]
http://octonator.com/git-submodule-explained/

**Comment by vbjay** [comment]
I recommend this issue be closed because it is not a gitextensions issue
but a git work flow understanding issue.

**Comment by clemsontiger** [comment]
None of what you said directly explains why 2 repositories in the solution, is, in your words, "a bad idea".  regardless, I do understand submodules can be an alternative to this, as such, I'll look into it or find another git extension that can still do what I was asking originally. thanks.

**Comment by mikelyncheski** [comment]
@clemsontiger  You are totally accurate in describing the need for this above.  We have the same situation (and I am sure many others do as well).  How did you end up solving this?    Thanks in advance.

**Comment by vbjay** [comment]
Freaking idiots. Submodules or subtree are the solutions. Take a look at
the .git folder in this repo after you gave it cloned and all submodules
are initialized. It's not the gui wrapper's problem. This is how git works.
If you want to keep separate project commits like our nbug repo, you either
use subtrees which out in the hot seat of making sure you don't pollute one
repo with the other's commits. Submodules insulate you from these. You do
have to do some things to keep the code up to date. Git extensions has
automated that for you. Either understand how git works or go away.

**Comment by vbjay** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by vbjay** [comment]
https://git-scm.com/book/en/v1/Git-Tools-Subtree-Merging

**Comment by vbjay** [comment]
https://git.wiki.kernel.org/index.php/SubprojectSupport

**Comment by mikelyncheski** [comment]
@vbjay Thanks for the links and the explanation (seriously). 

Jay Michael, it is easy to act like a tough guy/asshole over the internet.   I am guessing that you do not make a habit of talking to strangers like that face to face.

**Comment by vbjay** [comment]
Since nobody listened. I had to get loud, as it were.

**Comment by RussKie** [comment]
Jay, let's stay respectful and polite. 
Everyone has a different level of experience, skills and understanding. Yelling or abusing people isn't helpful in any way.

**Comment by clemsontiger** [comment]
@mikelyncheski no, never resolved it, instead we've just been managing commits directly through gitextensions, instead of doing it through the plugin in VS. Not great, but still worked.

Currently I'm just now looking into changing to using submodules, but hardly started and I think I've already run into an issue based on how we compile our solution. 

We've got 2 solutions (let's call them mom and dad) ,3 projects and similarly 3 repositories: mom, dad, and child.

solution mom contains mom project and child project, solution dad contains dad project and child project. Right now when the solution is compiled, we use build events to copy files from child project into a subfolder called child under project folders mom and dad (c:/mom/child, c:/dad/child).

One of the first things it says when setting up submodules is that it will create a local folder within the parent repository; so if I'm understanding this correctly, it'll try create a subfolder for repository child called child which will conflict as we already have such folders within the mom and dad repositories.

My question is if we tell it to create the sub folder for the submodule with a different name, say "child_git" will it harm anything? and how should the sub_module folder be handled in terms of inclusion into the project ?

After reading some of your links, submodules still sound more complicated then simply keeping our repositories as they are now.

Switching to submodules is overkill and unnecessary for us since our "parent" projects only use compiled files from the shared project when it is compiled.

I am simply asking that the VS gitexentions plugin be able to switch between repositories based on what repository the working file is from and/or switch based on which project is currently selected in solution explorer. This is how it used to work. I don't see how having it do this again would be an issue.

if someone other than @vbjay could respond with some input that'd be beneficial in terms of me understanding why this behavior can't be brought back, I'd be very appreciative.

**Comment by vbjay** [comment]
Tell you what. Create a dummy project that is the mom project. Add a
submodule, without updating or init, of any repo to the master repo. Look
at the folder structure in the repo. Now update and init submodule. Look at
folder structure. Also look at the Auto Compile submodules plugin.  Learn
how they work.  Yes..  Switching from a non submodule to a submodule would
mean you would need to move your submodule part of the project out to a new
place and commit those files to another repo.  Then go back to the original
repo and add a submodule pointing to the new repo.  Updating/init that
submodule.  Then copying back any of the files you need in the moved
location.

**Comment by RussKie** [comment]
> Switching to submodules is overkill and unnecessary for us since our
"parent" projects only use compiled files from the shared project when it
is compiled.

Is it worth considering including your child project via nuget packages?

There's so many ways to skin a cat.... I would restructure your repo either
with nuget dependencies (if the child project doesn't change often) or with
submodules.
