### ISSUE TITLE
libravatar support

### ISSUE THREAD

**Issue by Matthias84** [gitextensions/gitextensions#2837]
Hi, I really appreciate the Gravatar support on git extensions, sadly this services comes with a lot of privacy issues.  
The [libravatar project](http://www.libravatar.org) is an selfhosting alternativ, by hosting your own service and announce it via DNS. Even if there is [no official java library](http://wiki.libravatar.org/libraries/) there seem to exist some solutions, so I like to ask if you could add it please?

**Comment by ghanique** [comment]
+1

**Comment by linquize** [comment]
#1352 but it was based on an old version of gitextensions
