### ISSUE TITLE
Not able to issue "git flow release publish" in git-flow plugin 

### ISSUE THREAD

**Issue by valpa** [gitextensions/gitextensions#2838]
Using the git flow plugin GUI
Select release and click publish
In the below command section, it shows "git flow feature publish" instead of "git flow release publish"
failure error log:

cannot find the feature XXX

**Comment by valpa** [comment]
The problem is that the “feature” argument is hardcoded. I believe the fix should be to change GitFlowForm.cs, Line 208. https://github.com/gitextensions/gitextensions/blob/master/Plugins/GitFlow/GitFlowForm.cs#L208

from
RunCommand("flow feature publish " + cbBranches.SelectedValue); 
to
RunCommand("flow " + cbManageType.SelectedValue  + " publish " + cbBranches.SelectedValue);

**Comment by jmazurpl** [comment]
+1 for that

**Comment by gerhardol** [comment]
Fixed in #3812
