### ISSUE TITLE
Visual Studio 2008: File history/blame shows the current line 

### ISSUE THREAD

**Issue by lukastvrdy** [gitextensions/gitextensions#2839]
Hello,

I'd like to request feature in VS plug-in for showing git blame.

Currently when I want to see the blame, I do this:
1. Right-click on line in the source code (e.g. line 385)
2. Select "GitExt: File history"
3. Click on the blame tab
4. Scroll to the line 385

Expected behaviour:
1. Right-click on line in the source code (e.g. line 385)
2. Select "GitExt: Blame"
4. File history/Blame tab is shown and showing line 385

**Comment by vbjay** [comment]
That menu option is referring to the file not the line. However, that is
not s bad idea to go to the line.

**Comment by ajilani** [comment]
I still don't see the new option in VS. Tried modifying the installation to include all VS integration, but still don't GitExt:Blame in the right-click menu for a line of code, just the three old options.

- GitExtensions 2.50
- Windows 10 Pro 1703 build 15063.413
- VS Professional 2013 12.0.40629.00 Update 5 (with ReSharper)

**Comment by lukastvrdy** [comment]
I tried it in MSVC 2013, but I don't see it there. Could you, please provide steps how to get into GitExt: Blame as was requested in this ticket?

**Comment by jbialobr** [comment]
![gitext](https://user-images.githubusercontent.com/1003909/28956979-ff81352a-78ef-11e7-9db0-bd9ebbfa9005.png)
It is in the GitExt menu, but it is not in the context menu - as requested.

**Comment by crypto-rsa** [comment]
I am using VS 2015 and I was able to add it through
_Tools - Customize - Commands - Context menu: Editor Context Menus | Code Window - Add Command_

![Adding GitBlame command](https://user-images.githubusercontent.com/11479798/28957532-82ce20f8-78f2-11e7-9973-ddbc9237dc69.png)

Does it not work in VS 2013?

**Comment by ajilani** [comment]
I could not get this to work in VS 2013:

![image](https://user-images.githubusercontent.com/7442704/28973241-b5f32ee8-7900-11e7-9616-dac26379a853.png)

**Comment by jbialobr** [comment]
It looks like you have an old version of the extension installed.

**Comment by lukastvrdy** [comment]
Works for me in MSVC2015. FYI I don't see it in MSVC2013 though.

**Comment by RussKie** [comment]
I suppose we can close it.
The feature is available, albeit it may not work in older versions of VS. 
We won't be back-patching any old versions.
