### ISSUE TITLE
Git for Windows 2.x - Rebase AutoSquash no longer persists

### ISSUE THREAD

**Issue by mindw** [gitextensions/gitextensions#2850]
Git for windows places its global config in `c:\ProgramData\Git\config` and not in etc - GetExtensions looks for the etc one

**Comment by linquize** [comment]
This is not called "global config". "Global" means `$HOME/gitconfig`.
`c:\ProgramData\Git\config` is "Windows-wide config" (similar to system config), which should be read by all git clients.

**Comment by mindw** [comment]
It was previously located in ``/etc/gitconfig`` - which is pretty system wide. GitExtensions used it as input for the above.

**Comment by linquize** [comment]
But now there are 2 levels of system-wide config.
The more complicated thing is that the location to the original `/etc/gitconfig` has been changed (differ from 1.x, 2.x 32-bit, 2.x 64-bit). 1.x: `C:\Program Files (x86)\Git\etc` vs 2.x 32-bit: `C:\Program Files (x86)\Git\mingw32\etc` vs 2.x 64-bit: `C:\Program Files\Git\mingw64\etc`

**Comment by mindw** [comment]
The issue is opened for the regression - GitExtensions fails to find the system wide config in the above case. 

I some digging and it seems that the state of this check box is read in from `GitCommands.Settings` which in turn reads it from the system one `ConfigFileSettings::CreateSystemWide`. 

```
        public static ConfigFileSettings CreateSystemWide(bool allowCache = true)
        {
            string configPath = Path.Combine(AppSettings.GitBinDir, "..", "etc", "gitconfig");
            if (!File.Exists(configPath))
                return null;

            return new ConfigFileSettings(null,
                ConfigFileSettingsCache.Create(configPath, false, allowCache));
        }
```

**Comment by KindDragon** [comment]
JFI https://github.com/libgit2/libgit2/pull/3040 and https://github.com/TortoiseGit/TortoiseGit/pull/191

**Comment by linquize** [comment]
FYI https://github.com/git-for-windows/git/pull/104

**Comment by mindw** [comment]
I created this issue for tracking the AutoSquash state inconsistency. Not to dictate how it is implemented. I reworded the issue accordingly.
