### ISSUE TITLE
Show combined diff for merge commits in Diff tab

### ISSUE THREAD

**Issue by Radrik5** [gitextensions/gitextensions#2851]
Combined diff lists only files modified from both parents and shows diffs from both parents in one place. It's much more informative for merge commits than two diffs with parents. It's default for `git show`.

Example from documentation:

    diff --combined describe.c
    index fabadb8,cc95eb0..4866510
    --- a/describe.c
    +++ b/describe.c
    @@@ -98,20 -98,12 +98,20 @@@
    - static void describe(char *arg)
     -static void describe(struct commit *cmit, int last_one)
    ++static void describe(char *arg, int last_one)
      {
     +	unsigned char sha1[20];
     +	struct commit *cmit;

It would be great if Git Extensions showed combined diff in the Diff tab in addition to diffs with parents (three sections: combined diff, diff with first parent, diff with second parent).

**Comment by EbenZhang** [comment]
I did [some basic work](https://github.com/EbenZhang/gitextensions/pull/7/files) on this feature, but haven't fully tested it and the `Show diff in external tool` hasn't been implemented.
