### ISSUE TITLE
Linux Merge conflict resolved in KDiff3 fails to pass the event to gitExtensions the first time.

### ISSUE THREAD

**Issue by JerryLumpkins** [gitextensions/gitextensions#2852]
Whenever a merge conflict is solved using KDiff3, when I save the merged file, and close the KDiff3 window, the "Resolve merge conflicts" dialog in gitExtensions doesn't accept any mouse or keyboard events.

I have to execute a ps -ef | grep mono, and then kill gitExtensions. When I reopen gitExtensions, and go the repository, the flashing alert at the bottom tells me there are unresolved conflicts. If I then click on that, and go through the conflicts using KDiff3, and solve them, from then on, the event is getting passed back to gitExtensions, and everything works fine until I quit out of gitExtensions.

I haven't had time to investigate, but it has to be some value not getting properly initialized.

There are no error messages displayed in the console. It's just that the dialog "Resolve merge conflicts" accepts no events, and you're dead in the water with no option but to kill the process. I've become used to it, and simply choose a file that's easy to fix, and the second time I fix it, I'm good to go until I quit gitExtensions.

I switch back and forth between using Linux (Centos 7, Ubuntu 15.04, and Fedora 22) and using Windows 8.1. It always happens in Linux, and it never happens in Windows.

**Comment by JerryLumpkins** [comment]
![resolvemergeconflicts](https://cloud.githubusercontent.com/assets/5314886/8364056/48c46184-1b51-11e5-85f8-7b565c79923c.png)

**Comment by ricjac** [comment]
+1 I'm experiencing this issue also
