### ISSUE TITLE
Fails to reset selected lines on new files

### ISSUE THREAD

**Issue by MichalisN** [gitextensions/gitextensions#2857]
It fails to reset selected lines on newly added files. If the file is staged, reset selected lines is working as expected.

**Steps to reproduce:**
- Add a new file
- On commit window try to reset selected line(s)

**Expected result:**
Selected lines are removed

**Actual result:**
An error window starting with errors
error: patch failed: GitExtensions/Program - Copy.cs:0
error: GitExtensions/Program - Copy.cs: patch does not apply

and followed by the patch

**Comment by MichalisN** [comment]
I pulled the latest code and tested, it is still replicable.

**Comment by MichalisN** [comment]
**Testing results:**
Resetting now works if the file doesn't contain crlf. If autocrlf is false and the file contains crlf it is still failing.

**Extra information:**
Staging the file shows an error/warning (icon is error, message says warning) "CRLF will be replaced by LF ". Unstage has the original file (with crlf). Stage/Unstage looks correct.

**Comment by MichalisN** [comment]
Why this is closed?
If you have a file with Dos/Windows UTF-8 encoding the same issue exists (because of different line endings).

**Comment by piotr-cz** [comment]
- Resetting files inside commit doesn't work when using `R` shortcut when inside selection are added and removed or changed files.
- Resetting just added files works
- Resetting removed, changed or removed and changed works.

There is no error message, just nothing happens

**Comment by sbergot** [comment]
I reproduced it on v2.48.05

I fixed it by :
- going to tools -> settings -> git extension -> git config
- setting Line endings from "Not set" to "Checkout as-is, Commit as-is"

**Comment by jbialobr** [comment]
Can someone create a repository, configure it to a state that this issue is reproducible and then zip the repo and send it to me? I have tried to reproduce it from your descriptions but I am unable to.

**Comment by ghanique** [comment]
I'm using version 2.49.99.8 (some intermediate build that contains the
branches and tags on the left side, but does not have the conEmu
integration.

Steps to reproduce

   - Take any repository
   - Create a **NEW** file. Add some content.
   - In the commit window stage that file
   [image: pasted1]
   - On the top right select any line, right click and choose "Unstage
   selected lines"
   [image: pasted3]
   - On the latest release (2.48) I used to get an error now.
   - In the version I'm using you can get unexpected behavior by: On the
   left click "Unstage" or "Unstage All". The file does not get unstaged.
   (Closing and reopening the commit window helps).

**Comment by KindDragon** [comment]
Try latest build https://drive.google.com/drive/folders/0B8UPsaxEuQgqWnA3X2tmMjMwNzA?usp=sharing

**Comment by ghanique** [comment]
Will the left sidebar with the local and remote branches and tags not be a
part of the next release :'(?

If you stage a new file and then unstage all the lines, the file still
appears in the Staged section of the commit window. (Not that I consider
this an issue that must be fixed. At least you're no longer getting an
exception that closes Git Extensions if you forget to click the X instead
of the OK button).

**Comment by KindDragon** [comment]
> Will the left sidebar with the local and remote branches and tags not be a
> part of the next release :'(?

Sorry, but that big feature and we shouldn't push it to this release

**Comment by ghanique** [comment]
Can anyone tell me where to find that branch so that I can include it in my
custom build?

**Comment by KindDragon** [comment]
You mean PR #3038?

**Comment by ghanique** [comment]
That's it. Thx!
