### ISSUE TITLE
Keeps creating .gitattributes file

### ISSUE THREAD

**Issue by killerkalamari** [gitextensions/gitextensions#2869]
All the sudden a .gitattributes file was created. I am not sure of the steps to recreate (sorry), but I looked in the log and saw this:

2015-07-09T08:19:50.1206510-07:00    "C:\Program Files (x86)\Git\bin\git.exe" check-attr -z diff text crlf eol -- .gitattributes    #(took 63 ms)

I attempted to search the source to find out where this was coming from (to hopefully understand the logic behind it), but had no luck.

Can this command be taken out, or at least have it prompt me with an explanation? I'd prefer that Git Extensions not create any files without asking me first.

--- GitExtensions2.48.05, Git 1.9.5.msysgit.1, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by JerryLumpkins** [comment]
There is a menu option Repository->Edit .gitattributes.
Is it possible that someone on your computer actually executed that menu option, and then saved the file?

git help gitattributes

https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes

http://stackoverflow.com/questions/9933004/best-way-to-disable-git-end-of-line-normalization-crlf-to-lf-across-all-clones

https://coderwall.com/p/buf0rq/use-gitattributes-to-normalize-line-endings

**Comment by KindDragon** [comment]
Can you try remove file and run `"C:\Program Files (x86)\Git\bin\git.exe" check-attr -z diff text crlf eol -- .gitattributes` manually?

**Comment by killerkalamari** [comment]
The .gitattributes file came back again today. I know for sure I didn't edit .gitattributes. Running the above command gives the following output:

.gitattributes diff unspecified .gitattributes text unspecified .gitattributes c
rlf unspecified .gitattributes eol unspecified

In case it's useful: on the Git Config page, I have it set to "Checkout as-is, commit as-is", because we want to preserve CRLF line endings.
