### ISSUE TITLE
Format patch creates a file with a lower case p in .patch. Filter uses upper case p in .Patch

### ISSUE THREAD

**Issue by JerryLumpkins** [gitextensions/gitextensions#2870]
The primary file systems in Linux are all case sensitive. When you create a patch, the file created has a suffix of .patch.

When you go to apply a patch, it filters on .Patch.

The work around is after I format a patch, I have to go in, and modify the suffix before I can apply it.

**Comment by JerryLumpkins** [comment]
From 0435160dba176ae7d11aaa7e864d6f48e61fbc9a Mon Sep 17 00:00:00 2001
From: jlumpkins <jerry.lumpkins@gmail.com>
Date: Thu, 9 Jul 2015 18:25:06 -0400
Subject: [PATCH] Changed the patch file suffix to a lower case p

---
 GitUI/CommandsDialogs/FormViewPatch.cs | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/GitUI/CommandsDialogs/FormViewPatch.cs b/GitUI/CommandsDialogs/FormViewPatch.cs
index ddc03cc..1010212 100644
--- a/GitUI/CommandsDialogs/FormViewPatch.cs
+++ b/GitUI/CommandsDialogs/FormViewPatch.cs
@@ -46,7 +46,7 @@ private string SelectPatchFile(string initialDirectory)
         {
             using (var dialog = new OpenFileDialog
                              {
-                                 Filter = _patchFileFilterString.Text + "|*.Patch",
+                                 Filter = _patchFileFilterString.Text + "|*.patch",
                                  InitialDirectory = initialDirectory,
                                  Title = _patchFileFilterTitle.Text
                              })
-- 
2.1.4

**Comment by JerryLumpkins** [comment]
I tried pasting in the patch, and it doesn't look right, so I'll email it to you.

**Comment by RussKie** [comment]
Fixed in #3867
