### ISSUE TITLE
Git Extensions keeps files open even if they are ignored in .gitignore

### ISSUE THREAD

**Issue by carlTLR** [gitextensions/gitextensions#2871]
Specific example is Visual Studio's BuildLog.htm

Steps:
1) Open a Visual Studio code base (preferrably C++) that is versioned by Git.
2) Browse the repository using Git Extensions.
2) Make sure that the Debug and Release folders are part of .gitignore
3) Build the solution without closing Git Extensions.
4) Using Process Explorer, verify that GitExtensions.exe has BuildLog.htm open.

This becomes a significant problem when doing Test Driven Development. Because the build log is open by GitExtensions, Visual Studio is unable to open it.

**Comment by KindDragon** [comment]
I have not encountered such a problem. GitExt only open files for diff view.

**Comment by carlTLR** [comment]
I've specified the steps to reproduce the problem. It's extremely consistent.


Sent from Samsung Mobile


-------- Original message --------
From: Arkady Shapkin
Date:10/07/2015 9:40 PM (GMT+12:00)
To: gitextensions/gitextensions
Cc: Carl Menezes
Subject: Re: [gitextensions] Git Extensions keeps files open even if they are ignored in .gitignore (#2871)


I have not encountered such a problem. GitExt only open files for diff view.

�
