### ISSUE TITLE
FetureRequest: Dock a console window

### ISSUE THREAD

**Issue by mynkow** [gitextensions/gitextensions#2877]
Hello,

1) my dream is to click the button which opens the console and automatically dock it on the right. I am using the UI/console 30%/70%.
2) Also I want to create a button which opens conemu.exe and I can do this with the current GitExtensions but how to get the current path?

Bit short and not much details but I hope you get my point. 10x

---------------------------------------------------------------------------------------------------------

Jesse 	
Apr 17

I've contemplated the benefits of a something like this as well. It could be an especially good teaching tool for Git if it was able to automatically refresh the graph as Git commands are executed.

Something like this might be a starting point: http://www.codeproject.com/Articles/335909/Embedding-a-Console-in-a-C-Application

------------------

https://groups.google.com/forum/#!searchin/gitextensions/mynkow/gitextensions/_V0zydBVg50/sl60bxMbo9MJ

**Comment by mynkow** [comment]
Here is the perfect candidate 
- http://conemu.github.io/en/InsideParent.html
- https://github.com/Maximus5/conemu-inside

**Comment by jbialobr** [comment]
Does #3152 satisfy your need?

**Comment by mynkow** [comment]
This is really nice. Is it officially available or still in dev?
