### ISSUE TITLE
Vertical scroll pushes commit messages left and right

### ISSUE THREAD

**Issue by daveheq** [gitextensions/gitextensions#2880]
--- GitExtensions2.48.03, Git 1.9.4.msysgit.2, Microsoft Windows NT 6.1.7601 Service Pack 1

If I scroll, the commit messages move left or right depending on how far right the tree nodes are, making it disorienting. Please just flush left the messages so they're consistent all the time. Thanks

**Comment by RussKie** [comment]
If it is still an problem in 2.50 please raise a new issue
Thank you

**Comment by daveheq** [comment]
I'll use 2.50 if it doesn't have the duplicate taskbar icon and self-defeating "Wish" issue: 
https://github.com/gitextensions/gitextensions/issues/3021
https://www.bountysource.com/issues/33130348-git-gui-pinned-to-taskbar-appears-as-wish-application
