### ISSUE TITLE
Issue on shared drive with submodules

### ISSUE THREAD

**Issue by libesz** [gitextensions/gitextensions#2881]
Hi,

I have some problem with GitExtensions when I use it on a git repo, which is on a samba share, served by a virtualbox linux guest.

Background:
 The samba share is mounted on the host as a drive.
 The repo has submodules (actually a lot, around 100).
 GitExtensions version: 2.48.05 (was wrong also on 2.48.03)
 Host is Windows 7 Professional

If I try to browse the superproject, or even a submodule, GitExtensions is very slow, but the real problem is that it starts dozens of git.exe subprocesses which are doing something in the repo very hard, causing the smbd to consume 100% CPU in the guest machine.
Usually it is hard to recover from this state, GitExtensions start to hang sooner or later, but at least when I want to close the browser window. When I close or forceclose the window, it will leave the git.exe subprocesses alive and they have to be closed one-by-one to recover.

Cloning the same repo on the host Win7 machine directly causes no issue when browsing with the same installation of GitExtensions.
Browsing a submodule-less repo causes no issue over the same samba share.

Thanks!

**Comment by ghanique** [comment]
Why would you have a git repository on a samba share?!?
The whole idea is that you clone it locally so that it is really fast. One
should never work in a repository on a shared drive.

The fact that your repository *is* on a network drive explains the 100% cpu
for the samba daemon. Git can do a LOT of file operations in a very short
time that samba probably will not be able to cope with.

**Comment by libesz** [comment]
Okay, let's say it is really a constraint to have such an environment. Developers have to use the company provided win7, even if they really develop things under linux. That's why a linux is running in a VM, where we can compile/test our code. It is really painful in many ways but as I see, many people out there use it as there is not so much better way.

I know it is possible to reverse the share so that the repo will be cloned onto the host and shared into the VM with some virtualbox magic. That caused alot other problems around symlinks, file permissions, not to mention the compilation time in case of large codebases like we have in this repo. That really didn't work, instead we ended up with an environment like this, where the repo is on the VM side, where it is really used. So that it is now host OS and host FS agnostic and really fast to compile. Almost the only reason to have any samba share towards the host is to view and manage the stuff, so for example to handle it with GitExtensions.

**Comment by vbjay** [comment]
OMG!!!! AHHHHHHHH!!!  So the whole point of remotes is to handle this.
Each developer's machine has it's own repo copy.  They make their commits
and do what they need to do.  Then when they are ready to share, they push
the the shared repo that all developers have a remote linked too.  It i the
official repo.  If the business want's to protect their stuff then have the
devs work in a vm hosted on a server.

**Comment by RussKie** [comment]
I am not sure this is something we can address. 
This is a problem with your development setup/process...
