### ISSUE TITLE
Feature Suggestion: Collapse Commits

### ISSUE THREAD

**Issue by Inspyro** [gitextensions/gitextensions#2883]
Hi,
In the last time I often had to deal with commits that included the same changes (in the same files) across multiple (C#)-projects . A good example would be the _packages.config_ for each project: This file stores all currently required nuget packages and their version for each project. 
Say you update from NUnit 2.6 to 3.0 you will see a series of the same changes (e.g. 10 package.config files changed - but everywhere the same change).
In order to improve the workflow it would be cool to add a new feature to GitExtensions: 

**Collapsing commits (feature)**:
You could include some sort of button in the _commit window_ (and ideally also in the _Diff Views_) in order to collapse commits to only show unique commits. Say I made the same change to 10 files (10 package files / 10 csproj / ...)  the change is only shown as one change or parented to a root node for each unique change.

**So instead of:** 
_ProjectA/packages.config
ProjectB/packages.config
ProjectC/packages.config_

**Show:**
_packages.config (multiple)_

**Or Show:**

_packages.config_
- _ProjectA/packages.config_
- _ProjectB/packages.config_
- _ProjectC/packages.config_

When the same file is changed in various ways you can show it multiple times (but still collapsed/grouped).

This feature would make it much easier to reset, stage and review groups of changes that semantically belong together and afaik it would make your product stand out against it's competitors. 

Thanks for considering my suggestion.

**Comment by vbjay** [comment]
When committing, don't do it per file. Do the nuget update and add all
package config files, project files, and repository config files that
changed. Then make a nuget update commit message.

Also read up on squashing commits.

**Comment by Inspyro** [comment]
@vbjay I guess I have to clarify: I'm doing it all in one commit, but I want files that have the same changes like the packages.config to be shown under one common root node, because else the stage area / unstaged area / diff view can get quite "messy" because usually the files are sorted by full path, which means that the packages files etc are mixed up with other changed files (like the csproj files), and it's harder to spot changes that were mistakenly commited. ;)

**Comment by vbjay** [comment]
Ok. You want it by file type or filename?

**Comment by Inspyro** [comment]
By file name is more important. But in the long run GitExt should support both scenarios. :)
