### ISSUE TITLE
add a "Pull all" to include a pull of all submodules

### ISSUE THREAD

**Issue by sminjard** [gitextensions/gitextensions#2891]
This way, a repository can be pulled as well as all sub-modules the repository contains, and that recursively.

**Comment by vbjay** [comment]
Just add a script that calls git submodule for each --recursive git fetch
--all

**Comment by sminjard** [comment]
I could but some people in our project are not programmers and a button that will do the trick is way better. It is a common use I think, especially for those migrating from svn to git. 
It could also be an option during the pull process (per repository maybe).

**Comment by vbjay** [comment]
Git extensions let's you add script commands that show up on toolbar or
context menu.

**Comment by sminjard** [comment]
Ok thank you. It seems the command does exist but is disabled by default. I did not know this part of the soft.
