### ISSUE TITLE
Checkout branch create new branch

### ISSUE THREAD

**Issue by daveheq** [gitextensions/gitextensions#2895]
--- GitExtensions2.48.03, Git 1.9.4.msysgit.2, Microsoft Windows NT 6.1.7601 Service Pack 1

Not sure how to make a feature request but I thought Create new branch would allow me to type in a new branch name and create it from there; the actual Create feature has less options even though they would useful. These two options don't need to be separate as "git checkout -b" and "git checkout" use the same keyword and one is just an option of the other.

**Comment by RussKie** [comment]
Closing due to age.
