### ISSUE TITLE
Clone: Support "no-checkout" Option

### ISSUE THREAD

**Issue by hypersw** [gitextensions/gitextensions#2897]
Allow cloning in the `--no-checkout` (`-n`) mode, when a revision is not checked out into the working copy. This is not the same as a bare repo, the working copy is just empty, but can be checked out to any revision just as usual, at any time.

This is mainly needed if you want a sparse checkout, because you need to set up the filter _after_ you clone but _before_ you checkout. This only matters for large repos of course (with either many gigs of data or lots of smaller files).

THG got this option in its checkout dialog, so I'd consider it to be fair enough to ask for.

-----

*Proposed impl 1*: Checkout dialog has a label "Branch" and a combo box for choosing the checkout branch. The label could be turned into a checkbox, checked initially. Turning off the checkbox disables the combo box and means that the working copy won't be checked out on clone.

Pros: very straightforward
Cons: steals the keyboard accelerator from the combo box. Currently you'd jump into the combo on Alt+B, and with a checkbox, you would disable the combo instead.

*Proposed impl 2*: Add a synthetic item to the combo box, reading something like `(Do not checkout working copy)`

**Comment by ghanique** [comment]
+1. I like implementation 1. Stealing can be prevented, I think.

**Comment by hypersw** [comment]
Aw, impl 1 has to change the implementation text of course a bit to be straightforward. "Checkout branch" maybe. Otherwise just an unchecked "Branch" checkbox does not tell much.
