### ISSUE TITLE
Stash dialog throws ArgumentOutOfRangeException when there are autostashes

### ISSUE THREAD

**Issue by mycroes** [gitextensions/gitextensions#2901]
The stash dialog assumes there's only two naming conventions for stashes: 'WIP on...' and 'On...', but with autostashing enabled there might be stashes called 'autostash'. The FindBranch method tries to find match 'WIP on ...' and 'On ...', but if those are not matched it'll end up with an exception.

**Comment by spider312** [comment]
I have the same issue, while having only stashes with "WIP on ..." name format, and it's a very big issue for me as 95% of my use of gitextension is the stash window (if not 100% now)
