### ISSUE TITLE
Extreme slow operation on Windows 10

### ISSUE THREAD

**Issue by depth453** [gitextensions/gitextensions#2907]
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.3.9600.0

The git operation on windows 10 is extremely slow.

**Comment by sharwell** [comment]
I haven't noticed any difference on Windows 10.

**Comment by linquize** [comment]
msysgit's problem?

**Comment by MitchesD** [comment]
I have the same problem, it happens for all operations, even for local, e.g for me it takes about 50secs to get stash list, even when trying it in command line.

**Comment by MitchesD** [comment]
I found out, that its caused by anti-virus app, so not related to git extensions directly.

**Comment by djsmith** [comment]
@MitchesD what AV app was causing the problem and what did you do to get around it? I'm having a similar problem.

**Comment by linquize** [comment]
Anti-virus program can cause `git.exe`, `sh.exe` to start very very slowly.

**Comment by MitchesD** [comment]
@djsmith my avast anti-virus caused that, I added exceptions for git related things and everything is fine

**Comment by vbjay** [comment]
Just be careful. I'd much rather have slow runs and know there isn't some
virus being pulled or shell script doing something nasty.

**Comment by Mastergalen** [comment]
I'm using Git Bash on Windows 10 and I simply had to add a Read, Write, Execute exception in Avast for the path `C:\Program Files\Git\*` to get Git Bash to run back at normal speed again.

**Comment by rcdmk** [comment]
In my case it was Comodo Internet Security.

I was experiencing extremly slow operations in git bash.

What solved for me was to add the git install path to comodo antivirus exceptions and to shell code detection exceptions on the HIPs module.

**Comment by DravitLochan** [comment]
I have removed anti virus from my machine, but still git bash is slow.

**Comment by Cruze** [comment]
i have the same problems with Windows 10 default setup (Windows Defender)

**Comment by RussKie** [comment]
Can you temporarily disable windows defender and see if performance improves?
Also check that your repo or profiles not on disconnected network drives

**Comment by vware** [comment]
Trend Micro AV solutions caused similar slowdowns for me - haven't had time to look into it further though.

**Comment by v-karbovnichy** [comment]
I have McAfee on my machine. Starting git mingw64 terminal with real-time protection varies like 5-15 seconds, but when protection is off, it is about 1 second.

**Comment by blackcloud2333** [comment]
i have the same problem ,but i am sure that there is any anti virus in my pc. Besides, the windows definer is baned by myself .Since i open the git bash to i got the prompt ,it cost  20-30 seconds.
how can i solve the problem?

**Comment by ackvf** [comment]
Adding `bash.exe`, `cmd.exe` and `conhost.exe` into Windows Defender Exclusions list apparently solved the issue for me.

**Comment by k00k** [comment]
I followed @ackvf's advice, but as I'm using Tower for Windows as my Git client, I also excluded `C:\Program Files (x86)\fournova\Tower\Tower.exe` as well which seemed to help.

**Comment by Fl4v10** [comment]
I followed all the answers above an none of them worked to me, anyone has another idea?

**Comment by pmiossec** [comment]
I don't have a solution, but because that was not said before, there is a little advice...
**Using an up to date git bring most of the times a better performance, especially on windows**.
So check that you have the last version and update.

Git was at the origin built with a lot of shell scripts that create a lot of processes when run and where Windows is not very efficient at.

Each new version of git brings some of the scripts to be converted to C code that is much more efficient (one of the last feature converted is `rebase` which is now much quicker)

**Comment by tmilar** [comment]
Solution that worked immediately for me:

> Disabling AMD Radeon graphics driver in the Windows device manager and switching to integrated Intel HD graphics worked for me - for whatever reason.

(credits: https://stackoverflow.com/a/43762587/6279385)

**Comment by jrbytes** [comment]
> Can you temporarily disable windows defender and see if performance improves?

### Work! And now?

**Comment by ackvf** [comment]
If disabling windows defender worked for you, then you might try whitelisting some processes in defender so that you can turn it back on https://github.com/gitextensions/gitextensions/issues/2907#issuecomment-370013322

**Comment by jrbytes** [comment]
> @jrbytes If disabling windows defender worked for you, then you might try whitelisting some processes in defender so that you can turn it back on [#2907 (comment)](https://github.com/gitextensions/gitextensions/issues/2907#issuecomment-370013322)

Thank you.
I had to add it as a process to work. In the field I just typed `bash.exe`
All commands work on one second or less.
