### ISSUE TITLE
keep gitext commit dialog open

### ISSUE THREAD

**Issue by slymz** [gitextensions/gitextensions#2909]
Once the (commit) Process dialog is  okayed, it'd be nice if there was an option to drop back to Commit window (and not back to Desktop or else).  That'd allow for subsequent staging and committing of working directory piecemeal. kind of like  git gui.

thanks

**Comment by pmiossec** [comment]
I think that there is 2 options for that in the commit dialog "option" listbox just below the commit message field named "close dialog after each commit" and "close dialog when all changes are committed". Uncheck them and it should do the trick...

**Comment by slymz** [comment]
ah yes indeed missed that one. Thanks
