### ISSUE TITLE
Use ConEmu for Consoles

### ISSUE THREAD

**Issue by hypersw** [gitextensions/gitextensions#2919]
Employ [ConEmu](https://github.com/Maximus5/ConEmu) for running the child consoles.

ConEmu allows to embed a fully-functional console window as a GUI control in a dialog.

By fully-functional I mean that it would have all the terminal capabilities, like colors, positional drawing, escape sequences for erasing the current line and "updating progress", keyboard input, and so on.

We can then display the true Git command output in the progress window, allow for interactivity as necessary, show ssh cmd window inside rather than as a separate window, and so on.

Can have a real interactive Git shell control right in the GUI, which is also nice.

(this applies to WinNT platform only)

**Comment by karyon** [comment]
fixed by #3152 isn't it?
