### ISSUE TITLE
Visual Studio 2010 Add-in appears not to work when the addin folder is on a network location

### ISSUE THREAD

**Issue by frosty840** [gitextensions/gitextensions#292]
My Visual Git plugin is located at:
'\myFileServer\home\myUserName\Visual Studio 2010\Addins\GitPlugin.AddIn"

This raises an error of type 80131515, which appears to be related to the network location.

I'm not sure whether this is the usual problem with Visual Studio whereby it freaks out if something in on a network path until that path has been listed as a trusted location or whether it's a problem with the plugin itself.

VS2008 version seems to work fine.

**Comment by RussKie** [comment]
VS2010 no longer supported
