### ISSUE TITLE
Unable to install latest version

### ISSUE THREAD

**Issue by MLourensMoog** [gitextensions/gitextensions#2923]
When tryinh to install the latest version (I currently have 2.48.03 installed and try to install 2.48.05)  I get the following error message, saying that I have to select the folder containing "GitExtensions-2.48.03-SetupComplete.msi" (see screenshot):
![image](https://cloud.githubusercontent.com/assets/8565407/9332110/655b0112-45c3-11e5-9b4e-c323debee947.png)

**Comment by remcoros** [comment]
You (or some software) probably messed with the 'InstallerCache' or $PatchCache (or something) folder in C:\Windows\

You know, that folder that grows and grows and grows.

Fix it by downloading the exact mentioned .msi (you can still find those files here or on sourceforge) and select it when the installer asks for it.
