### ISSUE TITLE
"Illegal Characters in Path" if %PATH% Contains Quotes

### ISSUE THREAD

**Issue by hypersw** [gitextensions/gitextensions#2924]
If `%PATH%` env var has quotes in it, GitExtensions has exceptions on illegal chars in path in various places around the code, e.g. in Settings here:

```
        public static bool CheckIfFileIsInPath(string fileName)
        {
            string path = Environment.GetEnvironmentVariable("PATH");

            return path.Split(';').Any(dir => File.Exists(dir + " \\" + fileName) || File.Exists(Path.Combine(dir, fileName)));
        }
```

Example repro: in a console, run
```
set path=%path%;"c:\Program Files (x86)\Git\cmd"
```
then start GitExtensions from that same console.

The console consumes this `PATH` just well (`git` is located OK), but GE gets errors.

**Comment by Radrik5** [comment]
Can just remove the quotes?

**Comment by hypersw** [comment]
Hard to tell, takes some research. Like formatting a string for passing in a command line arg — might seem as simple as quoting, but then there comes handling of backslashes, circumflexes, and other mess. So my bet is that just removing quotes fixes the exception and works for 90% cases, but isn't totally correct. Better do than not do, anyway.
