### ISSUE TITLE
Cannot paste into commit window

### ISSUE THREAD

**Issue by AdamSturtridge** [gitextensions/gitextensions#2926]
Do control-space, after making copy of some text. In bottom left window Crtl-V does not paste. Nor does it work by right-click and choosing 'paste'

--- GitExtensions2.48.05, Git 1.9.4.msysgit.0, Microsoft Windows NT 6.3.9600.0

**Comment by markpizz** [comment]
I'm seeing this on Windows 10 with the same GitExtensions and Git 1.9.5.msysgit.0.  

I thought it might have something to do with where the clipboard had been populated from or what it contained, but the simple case of typing into the commit message box, cutting that (Ctrl-A, Ctrl-C and space to delete it) followed by any paste attempt (Ctrl-V or Right Click Paste) only produces a beeping error sound!

**Comment by vbjay** [comment]
I have seen it crash the program.

**Comment by johanvanr** [comment]
Behavior confirmed (Cannot paste into commit window).
Pasting into notepad++ worked fine.
GitExtensions v2.48.05 @ Win7x64

**Comment by markpizz** [comment]
This problem is VERY WEIRD.  It comes and goes.

Sometimes I can successfully paste if I attempt to do it more than once.  Sometimes pasting doesn't work at all.  Sometimes it just works normally.

**Comment by drauch** [comment]
I can confirm the weird behavior as well (GitExt 2.48.05 @ Win8.1 x64). Appeared "mysteriously" (no update or something like that) about two weeks ago, a colleague of mine experiences the problem even longer.

Sometimes it helps to press CTRL+V a few times to paste, sometimes it doesn't help at all. Pasting into other applications works fine, so the clipboard seems alright.

**Comment by jamesjrg** [comment]
Same problem here in Windows 10, maybe related to #2537?

**Comment by KindDragon** [comment]
Maybe fixed after #2847

**Comment by drauch** [comment]
@KindDragon : if I CTRL+V into another application it works, so it is not a problem with empty clipboards.

**Comment by AdamSturtridge** [comment]
By the way I am using Windows 8.1. 
One interesting thing I have noticed: 
I see the problem if I have VirtualBox machine running (regardless of the VB machines' clipboard config).
When I close VB machine, the problem goes away.
