### ISSUE TITLE
Unable to dismiss cloning dialog where access rights were insufficient

### ISSUE THREAD

**Issue by Jodes81** [gitextensions/gitextensions#2930]
When I try to clone a private repository from bitbucket without having made any attempt to provide necessary credentials to access it, the dialog who's title is "Process ()", which has the abort button cannot be dismissed, and I am forced to Ctrl-Alt-Del and close Git Extensions. Screenshot attached

![untitled](https://cloud.githubusercontent.com/assets/7270551/9429559/25622b28-49cc-11e5-9d2f-c6c6e19a06d0.png)

**Comment by KindDragon** [comment]
Should be fixed in 2.49
