### ISSUE TITLE
with git 2.5,  git bash open from git extensions not working,

### ISSUE THREAD

**Issue by longjxchina** [gitextensions/gitextensions#2931]
bash: git: command not found

**Comment by rexpan** [comment]
Hi @longjxchina 

In the settings, update
- Command used to run git `C:\Program Files\Git\bin\git.exe`
- Path to linux tools (sh) `C:\Program Files\Git\bin\`.

**Comment by longjxchina** [comment]
my git location: `D:\ProgramFiles\Git`


- Command used to run git:`D:\ProgramFiles\Git\bin\git.exe`


- Path to linux tools (sh):`D:\ProgramFiles\Git\usr\bin\`

it didn't work

**Comment by rexpan** [comment]
Hi @longjxchina,
try to set the *Path to linux tools (sh)* to `D:\ProgramFiles\Git\bin\`.

**Comment by longjxchina** [comment]
it worked, thanks

set the Path to linux tools (sh) to D:\ProgramFiles\Git\bin\.

**Comment by DemetriouJohn** [comment]
Similar issue, I set both paths, didn't work. The error I get is
Failed to run shell "bash". Reason: Cannot start process because a file name has not been provided.

**Comment by vbjay** [comment]
Wrong path. It's usr\bin where git is installed.
