### ISSUE TITLE
User Input Prompts don't work with OpenSSH and Git 2.5

### ISSUE THREAD

**Issue by krische** [gitextensions/gitextensions#2932]
### Description
It looks like user prompts for host verification and entering passphrases do not work with Git 2.5 and Git Extensions configured to use OpenSSH. The command dialog appears, but there is never any of the prompts for input like their used to be with Git 1.x.

### Steps to reproduce:
1. Install Git 2.5
    * 32-bit or 64-bit doesn't make a difference
    * MinTTY or cmd.exe doesn't make a difference
2. Install Git Extensions
    * Be sure to specify OpenSSH as your SSH option
3. Make sure you don't have a `known_hosts` file in your `.ssh` folder **OR** use a private key with a passphrase. We need to create a reason for a required user input.
4. In Git Extensions, push/pull to/from a remote repo. You will see the command window that normally appears, however instead of prompting for user input it closes and the operation fails.

### Expected Behavior
1. The user should be prompted to enter the required information. This is the behavior when Git 1.x is installed and Git Extensions is using OpenSSH.

**Comment by CharlesB2** [comment]
Same problem here. Command prompt window (which should be used to prompt SSH password) flashes, and message is 

    Permission denied (publickey,keyboard-interactive).
    fatal: Could not read from remote repository.

Fetching from Git bash command line goes well

**Comment by hypersw** [comment]
We've also ran into this issue.

@KindDragon : how were SSH interactivity handled in the prev version of Git? Some magic might have gotten broken, what to look for?

**Comment by hypersw** [comment]
Okay, this looks like the new Git.exe changed its behavior against 1.x: now redirecting stderr suppresses this query.
GE would capture stdout and stderr, ssh feels that and skips the interactive confirmation.

**Comment by hypersw** [comment]
Seems like there's no special GE magic involved, simple repro without GE:

```
git clone -v --recurse-submodules --progress "ssh://some.srv/repo.git" "C:/Users/Public/Projects/some-repo" >1 2>3
```
This silently denies using the host key.

What's interesting is that if you look at the `ssh` command it calls,

```
ssh.exe" some.srv "git-upload-pack '/repo.git'"
```

and run it with the same output redirects,

```
ssh.exe" some.srv "git-upload-pack '/repo.git'" >1 2>3
```

then `ssh` prompts for using the host key as expected. There seem to be no related cmdline options or env variables possibly affecting this behavior.

How does going thru `git` change this behavior?..

**Comment by shalupov** [comment]
I've added debug option to .ssh/config file and got:
```
debug1: Server host key: ssh-rsa SHA256:XXX
debug1: read_passphrase: can't open /dev/tty: No such device or address
Host key verification failed.
fatal: Could not read from remote repository.
```

**Comment by shalupov** [comment]
Probably related to https://github.com/git-for-windows/git/issues/327

**Comment by CharlesB2** [comment]
So from issue https://github.com/git-for-windows/git/issues/327 it looks like the bug doesn't happen if the console is Git Bash, this could be a simple workaround if Git Bash isn't already used to display the dialog.

**Comment by hypersw** [comment]
I'm currently working in this direction:

![untitled20151212171625](https://cloud.githubusercontent.com/assets/2332070/11762336/24c93150-a0f4-11e5-9d07-18553f4b9777.png)

**Comment by hypersw** [comment]
Fixed in https://github.com/gitextensions/gitextensions/pull/3152.

A preview build available at https://github.com/JetBrains/gitextensions/releases/tag/2016-03-14.

**Comment by CharlesB2** [comment]
Looks like credentials manager in Git 2.8 can handle remember SSH authentication, according to https://github.com/git-for-windows/git/issues/327#issuecomment-204708561. However I tried it and still it doesn't ask for password

**Comment by Radrik5** [comment]
I suspect credential manager works only with http(s) protocol, not with ssh because ssh itself asks you for private key's passphrase and git cannot use its credential subsystem here. You can avoid ssh prompts if you have the key without passphrase or using ssh-agent (I don't know if it works on Windows).

**Comment by hypersw** [comment]
… and might just work with the abovementioned PR.
