### ISSUE TITLE
Upgraded to Git 2.5, Crash on startup

### ISSUE THREAD

**Issue by lucibranc** [gitextensions/gitextensions#2934]
System.ComponentModel.Win32Exception

The system cannot find the file specified

TargetSite: Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d

StackTrace:    at GitUI.RevisionGrid.<>c__DisplayClass1d.<_revisionGraphCommand_Error>b__1c()

**Comment by vmuriart** [comment]
Reinstalling/Repair worked for me. Then it allowed me to set the settings to the new Git path since it changed during with the upgrade.

**Comment by lucibranc** [comment]
Thank you, that works.

**Comment by vmuriart** [comment]
Awesome, glad to hear. Not sure if the issue should be closed at this point or not. 
Doesn't really fix the root of the problem, but fixes the problem :)

**Comment by pmiossec** [comment]
Thanks for the information, that permit to fix the problem even without reinstalling.

Steps to fix, if it could helps:
1. Close the crash popup by the "close red cross" in the upper right (that will not close GitExtensions)
2. Go to settings and you will see that GitExtensions couldn't locate "git.exe"
3. Click on "Repair".
4. Done!

**Comment by james-poulose** [comment]
I just go this error in v2.48.05. Work arround by @pmiossec worked! - Thanks
