### ISSUE TITLE
Unattended installation: Allow configuration

### ISSUE THREAD

**Issue by dhilgarth** [gitextensions/gitextensions#2939]
I am a huge fan of chocolatey and I would like to install git extensions using chocolatey. But the problem here is, that the configuration is not supported, so after the installation, I am left with a system with all kinds of stuff that I don't need, like the VS plugin or the Shell extensions.

Feature Request: allow configuration of the installed features for unattended installations.

**Comment by KindDragon** [comment]
We don't have official chocolatey package

**Comment by dhilgarth** [comment]
My feature request is valid without considering chocolatey. It is a request for an unattended installation which is relevant in many scenarios.

**Comment by KindDragon** [comment]
You can select what to install from command line already http://stackoverflow.com/a/463875/61505

**Comment by dtwarnick** [comment]
So, for a silent/unattended install of GitExtensions, the command line would look something like this:

`msiexec /i GitExtensions-2.49-SetupComplete.msi ADDLOCAL=Feature1,Feature2,... /quiet /norestart`

Where _Feature#_ is one or more of...
AutoCompileSubmodules "Auto compile submodules"
BackgroundFetch "Periodic background fetch"
CreateLocalBranches "Create local branches"
DeleteUnusedBranches "Delete unused branches"
FindLargeFiles "Find large files"
Gerrit "Gerrit code review"
Github "Github integration"
GitFlow "GitFlow"
Gource "Gource visualization"
Impact "Impact Graph"
Statistics "Statistics"
ProxySwitcher "Proxy switcher"
ReleaseNotesGenerator "Release notes generator"
Stash "Atlassian Stash integration"
TeamCityIntegration "TeamCity integration"
JenkinsIntegration "Jenkins integration"
TfsIntegration "Tfs integration"
GitExtensions.desktop "Desktop shortcut"
Icons "Extra application icons"
DiffScripts "Custom merge scripts"
Dictionaries "Spelling dictionaries"
deDE "de-DE"
enAU "en-AU"
enCA "en-CA"
enGB "en-GB"
enUS "en-US"
esES "es-ES"
esMX "es-MX"
frFR "fr-FR"
itIT "it-IT"
nlNL "nl-NL"
ruRU "ru-RU"
plPL "pl-PL"
Translation "Translations"
Czech "Czech"
Dutch "Dutch"
French "French"
German "German"
Japanese "Japanese"
Polish "Polish"
Russian "Russian"
SimplifiedChinese "Simplified Chinese"
Spanish "Spanish"
TraditionalChinese "Traditional Chinese"
ShellExtension "Windows Explorer integration"
AddToPath "Add installation directory to PATH"
VS2005FeatureId
VS2008FeatureId
VS2010FeatureId
VS2012FeatureId
VS2013FeatureId
VS2015FeatureId
Protocol.git "Assign with git://-links"
Protocol.github_windows "Assign with github-windows://-links"

**Comment by Johno-ACSLive** [comment]
If you need to customise many features, you are best to create an MSP with the feaure customisation and add it as a parameter to be applied ontop of the MSI.

**Comment by RussKie** [comment]
Git Extensions can be installed with choco
https://chocolatey.org/packages/gitextensions
