### ISSUE TITLE
git extension 2.48.05 doesn't detect code changes

### ISSUE THREAD

**Issue by atjshop** [gitextensions/gitextensions#2940]
After upgraded to 2.48.05, in the left side of the "commit" button always showing green check mark no matter there is code change or not. 

screenshot of the "commit" button and check mark, it shows no change. But there is change when you click the commit button to bring up the commit window.

![sshot-2015-09-06- 12-06-03](https://cloud.githubusercontent.com/assets/14037447/9705624/0bbe2112-5490-11e5-8d93-c6aa032f7b9f.jpg)

![sshot-2015-09-06- 12-06-15](https://cloud.githubusercontent.com/assets/14037447/9705622/0139831c-5490-11e5-96c0-dfd3d86941c2.jpg)

**Comment by atjshop** [comment]
screenshot of the "commit" button and check mark, it shows no change. But there is change when you click the commit button to bring up the commit window.

![sshot-2015-09-06- 12-06-15](https://cloud.githubusercontent.com/assets/14037447/9705622/0139831c-5490-11e5-96c0-dfd3d86941c2.jpg)

![sshot-2015-09-06- 12-06-03](https://cloud.githubusercontent.com/assets/14037447/9705624/0bbe2112-5490-11e5-8d93-c6aa032f7b9f.jpg)

**Comment by ghanique** [comment]
Quite often this is caused by git processes running in the back end. Stop
Git Extensions, kill everything related to git and try again. Restarting
your computer should do the job as well.

**Comment by atjshop** [comment]
Thanks, this works!
