### ISSUE TITLE
Interactive Rebase failed with warning: "Vim: Warning: Output is not to a terminal"

### ISSUE THREAD

**Issue by narcotics726** [gitextensions/gitextensions#2944]
--- GitExtensions2.48.05, Git 2.5.0.windows.1, Microsoft Windows NT 6.3.9600.0

>"C:\Program Files\Git\bin\git.exe" rebase  -i --no-autosquash "master"
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal

Is there anything I can try?

**Comment by vbjay** [comment]
Use something else than vim. Vim doesn't create a console window.

**Comment by narcotics726** [comment]
@vbjay Worked! Thanks a lot.
