### ISSUE TITLE
Allow /qn install via MSI

### ISSUE THREAD

**Issue by bob-devereux-zocdoc** [gitextensions/gitextensions#2945]
It would be great if the quiet mode install on windows worked correctly so we could script the installation on new developer builds.

Passive works...
c:\windows\system32\msiexec.exe /i GitExtensions.msi /passive

But /qn (quite?) doesn't seem to do anything
c:\windows\system32\msiexec.exe /i GitExtensions.msi /qn

**Comment by RussKie** [comment]
Have you looked at https://github.com/gitextensions/gitextensions/issues/2939?

**Comment by Johno-ACSLive** [comment]
This is rather old issue, however, /qb means the installation will be quiet and display a basic UI (install with default options and show a basic progress).

/qn is for quiet and no UI. You will not see anything. You can check the msiexec process but that won't tell you much. You could enable logging to see what is happening.

If you wait some time, does GitExtensions show up in Programs and Features or Apps and Features?

**Comment by RussKie** [comment]
@Johno-ACSLive is there something we can fix?

**Comment by Johno-ACSLive** [comment]
@RussKie MSI natively supports /qn and /qb. I've used /qb (used during the new update mechanism) and it worked fine which means /qn should work the same (it just doesn't show any progress).

Unless the installer is not doing anything at all during install or upgrade (although based on the config i don't believe this to be the case). We really need more info on this particular use case.

I'll fire up a VM in the next couple days and see what the current MSI does. Based on what I find (i believe the only issues are during upgrade which prompts for settings that it shouldn't e.g. items from the SSH discussion and #3407), /qn should just use default options for both fresh install and upgrade as it does when i tested /qb.

**Comment by RussKie** [comment]
Thank you. Standing by waiting for your feedback

**Comment by Johno-ACSLive** [comment]
I ran the following commands and got the following results:

msiexec.exe /i GitExtensions-3.1.1.6049.msi /qn

This installed on a clean machine within 10 seconds, I didn't launch GE but the shortcut showed up on the desktop. No UI present, completely silent.

msiexec.exe /x GitExtensions-3.1.1.6049.msi /qn

This uninstalled on the machine within 10 seconds, no UI present and completely silent.

msiexec.exe /i GitExtensions-3.1.1.6049.msi /qb

This installed on a clean machine within 10 seconds, I didn't launch GE but the shortcut showed up on the desktop. MSI Progress UI present, no prompts.

msiexec.exe /x GitExtensions-3.1.1.6049.msi /qb

This uninstalled on the machine within 10 seconds, MSI Progress UI present and no prompts.

**Comment by RussKie** [comment]
Awesome, thanks heaps for testing it!
