### ISSUE TITLE
Deleting the branch selected in the branch filter causes crash

### ISSUE THREAD

**Issue by holstebroe** [gitextensions/gitextensions#2949]
To reproduce:
Select some branch in the "Branches:" text box. 
Delete that branch.
NullReferenceException

**Comment by linquize** [comment]
What is your GitExtensions version?
What is your Msysgit version?

Where to "Select some branch in the "Branches:" text box"? Main Toolbar or Delete Branch dialog?

**Comment by EbenZhang** [comment]
Pretty sure it has been fixed in 2.49 (Probably by @Radrik5), not sure if it was ported back to 2.48.
And it seems there's no plan to release 2.49. @KindDragon
