### ISSUE TITLE
[GitExtension v2.48.05] [Windows 7 pro] [1.9.5.msysgit.1] Crash while openning repo

### ISSUE THREAD

**Issue by PierrickG12** [gitextensions/gitextensions#2951]
Hi,

I have a problem with the last Git Extension version 2.48.05.
I'm using it, with 1.9.5.msysgit.1 and I'm unable to open my repo.

In attached files,  screens of the Exception message : 
![crash_gitextension_1](https://cloud.githubusercontent.com/assets/11858423/9960210/899b9a14-5e19-11e5-983c-35c65bdc49d8.png)
![crash_gitextension_2](https://cloud.githubusercontent.com/assets/11858423/9960213/8e51f0a8-5e19-11e5-803e-e2d4ed441551.png)

Before investige the problem, my question is : 
according to the release date Git is moving faster than Git Extension (and it's normal), so what is the better versions combination between Git (for windows or msysgit) and git extension ?

Thanks in advance

**Comment by Radrik5** [comment]
Please open Tools -> Settings. Is everything green?
Git 2 is still not tested enough with Git Extensions, so it's better to use Git 1.9.5 for a while.

**Comment by PierrickG12** [comment]
Thanks Radrik5 for your quick answer !

I've spend the all morning testing Git for windows 1.x and 2.x before going back to the 1.9.5.msysgit.1.
And so I haven't even check the main settings on my Git Extension after those install/uninstall.

The link with bin/sh was missing. Thanks again.

For information, while installing Git Extension, a msysGit is given as optional installation. So here are the best matching versions between GitExtension et Git : 

GitExtension v 2.48.05 <---> 1.9.5.msysgit.1
GitExtension v 2.48.03 <---> 1.9.4.msysgit.1
