### ISSUE TITLE
Add --force-with-lease as an option 

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#2955]
Currently it will do '-f' if  the check box ticked, while the force push button in the popup dialog will push using the '--force-with-lease'. 

Can we add the force with lease  as an option  explicitly?

**Comment by Radrik5** [comment]
I think `--force-with-lease` should be used with Force check-box instead of `-f`.
It's safe and it's available since Git 1.8.5.

**Comment by EbenZhang** [comment]
But sometimes you want to do a -f.

**Comment by Radrik5** [comment]
But it's unsafe. It's better to always use `--force-with-lease` to be sure you know what you overwrite.

**Comment by vbjay** [comment]
I agree. There should be both. Allow the user to do it. However, make it
warn that -f is destructive. With lease, it gives you a safety net. Default
to lease and make the user check a check box or something to run -f.

**Comment by Radrik5** [comment]
@EbenZhang @vbjay could you give an example where you need `--force`?

**Comment by linquize** [comment]
Note: you cannot use `--force-with-lease` to force push a tag. You have to use `--force` instead.

**Comment by vbjay** [comment]
I have a password or key that was in the repo. I use filter tree to remove
it and rewrite the repository.

**Comment by Radrik5** [comment]
@linquize @vbjay good points. Now I vote for having both options.

**Comment by vbjay** [comment]
We could even detect an error with lease and suggest using force of an
error occurred warning the user what it will do.

**Comment by johnddx** [comment]
> I have a password or key that was in the repo. I use filter tree to remove
it and rewrite the repository.

@vbjay, What is unique about this scenario such that --force-with-lease isn't good enough?  Do you not need to incorporate the latest update so that you can rewrite the repository without losing changes you didn't have when you ran filter-tree?

**Comment by vbjay** [comment]
Lease can and will fail if it is not at an expected state.  It is the
better way to go but we could tell them that it failed and ask them do you
want to force or cancel or fetch.
https://developer.atlassian.com/blog/2015/04/force-with-lease/

**Comment by KindDragon** [comment]
`--force-with-lease` already supported https://github.com/gitextensions/gitextensions/blob/8f130666f105d25ad9011ff65f46767ea7435306/GitUI/CommandsDialogs/FormPush.cs#L447-L450

**Comment by EbenZhang** [comment]
That commit is for the button if rejected. This pull request is to add an adv option.

**Comment by KindDragon** [comment]
Sorry, you already mention this in your issue.

> the force push button in the popup dialog will push using the '--force-with-lease'.

I thought that would be enough

**Comment by KindDragon** [comment]
I am voting only for one option :smile:
Maybe auto fallback to `--force` if we try push tag

**Comment by johnddx** [comment]
I don't understand the fallback --force-with-lease option... when you click 'push', doesn't it fetch the new branch state on the remote so that it can decide whether to present the pop-up?  If so, then --force-with-lease would pretty much always succeed at that point, defeating the purpose.

**Comment by KindDragon** [comment]
> doesn't it fetch the new branch state on the remote so that it can decide whether to present the pop-up?

We don't call fetch at push, you mean `git push` fetch changes?

**Comment by johnddx** [comment]
> We don't call fetch at push, you mean  git push  fetch changes? 

No, I was just referring to the actions taken by gitex when doing 'push'.  If gitex doesn't fetch when you push, then I was mistaken.  As long as the user had a chance to review the state of remote/branch at some point, we are fine.

However, I do think the UI should make it clearer what they are choosing by displaying "Force Push (with lease)" instead of simply "Force Push", because I was not inclined to trust it otherwise; I would continue doing it from the command-line as a result.  I wish I could think of a better phrase than "with lease" .

**Comment by EbenZhang** [comment]
Agree that we should rename it and drop the support for earlier version of git.

**Comment by KindDragon** [comment]
Currently minimal supported Git version is 1.7

I don't think we should drop the support for earlier version of git, just dynamically replace text and git arguments if "Force Push with lease" not supported.

**Comment by ulrichb** [comment]
> However, I do think the UI should make it clearer what they are choosing by displaying "Force Push (with lease)" instead of simply "Force Push".

+1

Does this already happen?
