### ISSUE TITLE
Revisiongrid doesnt keep the selection

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#2956]
I'm using  the master branch of git extensions.
- use the branch filter to find a branch
- scroll down and select one commit of that branch 
- clear the  branch filter
- the revision grid will select another commit randomly

~~It used to keep the selected commit in 2.48 but no longer in the master branch.~~
This feature is quite handy when trying to compare your latest change to another branch.

**Comment by Radrik5** [comment]
For me it works sometines. Are you sure it always works in 2.48?

**Comment by EbenZhang** [comment]
Well, I thought it was introduced recently, but, in fact, it doesn't work in 2.48.05 either. It seems just doesn't work for certain commits. For example:

* Check out the master branch (at this moment the commit is fe4bb94ca2a74dbbe14348dc41e96284fecdbe06, commit msg is : `Thanks to JetBRAINS added`)
* Select the v2.48 tag from the branch filter list
* Press `Ctrl + Home` to navigate to the top of the revision grid, so the v2.48 commit 80add61cebe4db85d525c5f871d52f67a55de827 (commit msg: `Submodule GitExtensionsDoc updated`) gets selected.
* Remove the v2.48 from the branch filter
* The revision grid will select commit 8b0ac9c3d9af2b2ca4a863b1916a18b5310ece55 (commit msg: `Fix warning: 'DeleteUnusedBranches......`)

**Comment by EbenZhang** [comment]
Well, seems I just need a feature to compare two branches and optionally compare to their merge base

**Comment by Radrik5** [comment]
You can try entering `branch1...branch2` in the Branch filter. It goes directly to the `git log` command line.

**Comment by EbenZhang** [comment]
close by #3039

**Comment by Radrik5** [comment]
Please reopen. This hasn't been fixed yet.
