### ISSUE TITLE
Blows up when I open a repo

### ISSUE THREAD

**Issue by RrnR** [gitextensions/gitextensions#2964]
![image](https://cloud.githubusercontent.com/assets/14882434/10153526/a0f697e2-66b9-11e5-8c7c-200f4fc1001c.png)

![image](https://cloud.githubusercontent.com/assets/14882434/10153639/d16bacc2-66ba-11e5-91c8-6c608ab4f56e.png)

![image](https://cloud.githubusercontent.com/assets/14882434/10153622/ae6df6b2-66ba-11e5-8365-54babba0cd4e.png)

I get this exception whenever I try to open a local repo.  When I exit the dialog the application closes.  At the moment it is happening every time, though in the past sometimes I have been able to get past it by just trying again - at the moment nothing works so I'm dead in the water.

Has anybody else seen this?

Windows 8.1 64 bit.  Plenty of RAM

**Comment by RussKie** [comment]
Please re-open if it is still a problem with 2.50
