### ISSUE TITLE
Config Settings written with upper case True and False

### ISSUE THREAD

**Issue by rarevans** [gitextensions/gitextensions#2965]
When changing either a repository or global user setting through the settings form, the values of True and False are written with capitalised values. This results in calls to 'git config ... ' returning values that may match expected values.
The convention for setting values seems to have always been all lowercase true and false values.
I believe this problem is due to converting your enumeration AutoCRLFType declared in CommonSettingsTypes.cs to a string.

To repoduce:
1) Open git Extensions.
2) Open Settings form
3) Expand to Git Extensions -> Git Config
4) Select global Settings source
5) Change the line endings value to Checkout as-is, Commit as-is 
6) Apply settings
7) Examine the global user gitconfig

.gitconfig
[core]
	autocrlf = False

Version: 2.48.05

Thanks for the great git client.

**Comment by linquize** [comment]
should be lowercase
