### ISSUE TITLE
Checkout branch not clearing Submodule folders

### ISSUE THREAD

**Issue by AaronLayton** [gitextensions/gitextensions#2966]
I have the below (simplified) branch structure

/Master
    readme.md

/develop
    readme.md
    folder1/
        sub-module initialized into this folder

I would expect that when I switch between the 2 branches the submodule folder is removed aswell. I am on Windows 10 using version 2.48.05

The actual message I am getting is
```
"C:\Program Files (x86)\Git\bin\git.exe" checkout "master"
Your branch is up-to-date with 'origin/master'.
warning: unable to rmdir Daedalus.Web/Areas/blog: Directory not empty
warning: unable to rmdir Daedalus.Web/Areas/emails: Directory not empty
Switched to branch 'master'
Done
```

Could anyone shed any light on why this could be happening or how I can get around it. My project is private but if need be I will try and recreate the issue on a public Git to demo the issue

**Comment by Radrik5** [comment]
Could you try running `git checkout master` in Git Bash?
What are the files in `blog` and `email` folders? Are they in .gitignore?

**Comment by AaronLayton** [comment]
Hi @Radrik5,

I have just tried this in Git Bash and I get the same message as above. Directories now empty etc

You mentioned the `.gitignore` - should the sub-modules folder be named in the Main repos .gitignore?

In the `sub-modules` folders there are some `folders`, `.html`, `.cs` files etc

**Comment by Radrik5** [comment]
It seems that this is a well-known issue with submodules. See https://git-scm.com/book/en/v2/Git-Tools-Submodules#Issues-with-Submodules.

**Comment by Rylan12** [comment]
For anyone looking for a solution: (sorry I'm 4 years late...)

> Newer Git versions (Git >= 2.13) simplify all this by adding the --recurse-submodules flag to the git checkout command, which takes care of placing the submodules in the right state for the branch we are switching to.

Use `git checkout --recurse-submodules master`

Use `git config submodule.recurse true` to tell git to always use `--recurse-submodules` (only in git versions 2.14+)

[Source](https://git-scm.com/book/en/v2/Git-Tools-Submodules#Issues-with-Submodules) is from @Radrik5's post above

**Comment by danieliniguezv** [comment]
This post is gold @Rylan12 appreciate it!

**Comment by Nikhilesh-Saggere** [comment]
The **saviour command**
In my repository i have a branch with submodule and without a submodule
This command works like a charm. (even on the latest version of git)
Else i always use to witness the warning: unable to rmdir 'my-application': Directory not empty

From here on, whenever i switch branches, i always use git checkout --recurse-submodules <branch-name>

**Comment by ScarletPixie** [comment]
@Rylan12 finally, git can be so problematic. You can set the global config to always use --recurse-submodules ```git config --global submodule.recurse true``` i don't know if that has some weird side effect though.
