### ISSUE TITLE
Virus alert from virus total: Trojan.Win32.Rozena.dvlzqa 

### ISSUE THREAD

**Issue by MaksimSimkin** [gitextensions/gitextensions#2973]
Hi i just scanned  setup of GitExtension before installing it nad i get virus warnings:

Antivirus 	Ergebnis 	Aktualisierung
NANO-Antivirus 	Trojan.Win32.Rozena.dvlzqa 	20151008 

https://www.virustotal.com/de/file/7c34cba71e8d867545b4312ee14583cd8254c5219e808038d7f6244ed3bb14a8/analysis/1444304451/

**Comment by vbjay** [comment]
Looks like it might be a false positive. It may be detecting an msi
installer. Try scanning another msi.

**Comment by MaksimSimkin** [comment]
Just for Example:
Anothe msi, no warnings

https://www.virustotal.com/de/file/be6288737ea9691f29a17202eccbc0a2e3e1b1b4bacc090ceee2436970aec240/analysis/1444308433/

**Comment by jeffqc** [comment]
Tried with the url instead, it seems fine:

https://www.virustotal.com/en/url/d6894523698479843c155c99eced6efddfd32f19c62f82bcb93064a87eef328a/analysis//
https://www.virustotal.com/en/url/9bd6e17181e5f6f7319f2ecdb40ce256f535d0ed702fc913685146abcab4cd49/analysis/
