### ISSUE TITLE
Additional command button on explorer extension "Add files". Label of this buttons

### ISSUE THREAD

**Issue by trojanobelix** [gitextensions/gitextensions#2980]
Brilliant work. Thanks a lot!

On W7-64, git 2.5.3.windows.1 and GitExtentions 2.48.05 I have a suspicious "Add files" windows with two command button and the same German labels "Dateien" (engl.: "Files"). Pressing the button on the left seems to do nothing. The right one does what I expect (add the files).

I have expected just one button with the label "Add" or "Ok".

![image](https://cloud.githubusercontent.com/assets/15106425/10454881/186ee29e-71b8-11e5-933e-12f43b56dd7c.png)

[EDIT]: Seems just to be the command button labels (an my misinterpretation what they do).
First button is an "add --dry-run" and should be labelled as "Vorschau" in German (engl.:"Preview"). 
Second button is the "add" and should be labelled as "Hinzufügen" in German (engl.:"Add").

BTW: Might it be more consistent to use "Add.." in the context menu instead off "Add files" like "GitExt Commit..." and "GitExt Push..."?

BTW2: The context menu entries are not localized, but the windows that opens when using it! Is that expected?

**Comment by KindDragon** [comment]
> BTW2: The context menu entries are not localized, but the windows that opens when using it! Is that expected?

Yes, we not support Shell Extension menu localization

**Comment by KindDragon** [comment]
> Seems just to be the command button labels (an my misinterpretation what they do).
> First button is an "add --dry-run" and should be labelled as "Vorschau" in German (engl.:"Preview").
> Second button is the "add" and should be labelled as "Hinzufügen" in German (engl.:"Add").

You can change localized text here https://www.transifex.com/git-extensions/git-extensions/
