### ISSUE TITLE
'Show repository status' with Git for Windows 2.6.1 does not work

### ISSUE THREAD

**Issue by Andreone** [gitextensions/gitextensions#2982]
The 'Commit' button stays green and never display change count. Everything else seems to work but this.

**Comment by linquize** [comment]
what is the output of `git status`? before and after 2.6.1

**Comment by Andreone** [comment]
They are the same:

> On branch xxx
Your branch is up-to-date with 'origin/xxx'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
>
>        modified:   src/xxx.cpp
>        modified:   src/xxx.h

**Comment by vbjay** [comment]
Next time it happens use task manager, look for a git process. Git uses a lacking system to prevent multiple transactions. If it is doing something, the count can't be refreshed.

**Comment by Andreone** [comment]
I indeed found few git processes running in the background that seems zombified. I killed them and the count reappeared. Thanks.
