### ISSUE TITLE
Remote branches seem to be out of sync on local 

### ISSUE THREAD

**Issue by attilabertok** [gitextensions/gitextensions#2983]
A team member recently cloned our repo and saw stuff that seems quite different than what we see. I don't know what the reason might be, but simple fetches don't seem to solve this.

Here's what we see on our git server:
![ss_03](https://cloud.githubusercontent.com/assets/15122684/10481828/ba8c7d82-7273-11e5-8f3b-519171063cf8.png)

And here are the two screenshots on the clients, differences marked:
![ss_01](https://cloud.githubusercontent.com/assets/15122684/10481840/cfc55b2e-7273-11e5-9323-ac7e8b996a10.png)
![ss_02](https://cloud.githubusercontent.com/assets/15122684/10481842/d563a522-7273-11e5-9d01-8f9b4b4edb62.png)

It might be just us mis-using something, but certainly looks strange.

Any ideas on what might be happening?

**Comment by ghanique** [comment]
Execute "git remote prune origin"?

**Comment by attilabertok** [comment]
@ghanique -- you are totally right, seems like we did delete the branches but not the refs. Not a bug then, just plain old git incompetence. Thanks for pointing us in the right direction. :)
