### ISSUE TITLE
Failed to load buildserver adapters

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#2984]
Using the latest master branch fe4bb94ca2a74dbbe14348dc41e96284fecdbe06 (The `Thanks to JetBRAINS added` commit):

Steps to reproduce:
- Empty the debug folder
- Rebuild the solution
- Open GitExtensions
- Go to the tools -> settings -> build server settings page
- The build server type dropdown list is empty
- Consequently, the build results are not retrieved and showing in the revision grid

There's an exception when trying to `GetBuildServerAdapter` in the `buildserverwatcher.cs` saying that `System.Http.Format.dll` cannot find the `Newtonsoft.Json.dll version 4.5.0.0`

**Comment by vbjay** [comment]
Restore your nuget packages.

**Comment by EbenZhang** [comment]
I have three Newtonsoft.json in the packages folder: Newtonsoft.Json.4.5.11, Newtonsoft.Json.5.0.8, Newtonsoft.Json.6.0.8

Will try delete and restore to see if helps.

**Comment by EbenZhang** [comment]
After deleted the above mentioned folders and then rebuilt, only one `Newtonsoft.Json.6.0.8` gets restored. The problem still exists.

**Comment by EbenZhang** [comment]
anyway, figured out myself, adding a bindingredirect solves the problem.
