### ISSUE TITLE
Git process detection

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#2986]
In the main window, when the commit button status is out of sync, detect if a git process is running. If a process is running, show a gentle warning that a git process is running.  We could even show the command arguments. 

Even better, check the run time of the process and if it is a long running process ask if they would like to close it with a dire warning if they do end the process.

**Comment by Radrik5** [comment]
We don't need to examine running Git processes if Git 2.x is installed.
Please read the following comments: https://github.com/gitextensions/gitextensions/commit/8b47b8c76ec1#commitcomment-7674932
