### ISSUE TITLE
Allow --force for branch checkouts

### ISSUE THREAD

**Issue by mmoayyed** [gitextensions/gitextensions#2992]
Title says all.

**Comment by vbjay** [comment]
Why would reset not work?

**Comment by mmoayyed** [comment]
What I do is, right click on a branch name, attempt to check out. It then tells me certain files will be overwritten and the process is aborted. What I want is to ignore that message, and force a checkout in the UI. Is that possible?

**Comment by Radrik5** [comment]
Please check that "Use last chosen action" is disabled in Settings -> Advanced:
![image](https://cloud.githubusercontent.com/assets/9339459/10649152/17117ab2-784b-11e5-9e25-87a937efcb40.png)

Then, if there are uncommitted changes, Git Extensions should show you the "Checkout branch" dialog and you'll be able to choose what to do with local changes:
![image](https://cloud.githubusercontent.com/assets/9339459/10649129/00541a3c-784b-11e5-9109-3eb47b86ae4a.png)

You can also open the dialog from Commands -> Checkout branch... (Ctrl+.).

**Comment by mmoayyed** [comment]
>Please check that "Use last chosen action" is disabled in Settings -> Advanced:

This is unchecked.

>Then, if there are uncommitted changes

There is none. The issue is, branch X has a file called HelloWorld. Branch Y has a file called HELLOWORLD. When attempting to checkout branch X, I am told that HelloWorld will be overwritten and must be removed first. If do a --force checkout, it does what I want which is: disregard the file and overwrite it automatically.

**Comment by mmoayyed** [comment]
I am on the latest released version btw.

**Comment by mmoayyed** [comment]
I could have the tool always show the checkout dialog, but that would also be an extra step in majority of cases. Ideally, it would be best if an option came up and said: Do you want to force this checkout? 

Or maybe a key combination.

**Comment by Radrik5** [comment]
You should be able to switch from branch with `HELLOWORLD` to branch with `HelloWorld` without `--force`.

I created a test repo to verify that:
```
~ $ git clone git@github.com:Radrik5/test-checkout.git
Cloning into 'test-checkout'...
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 9 (delta 0), reused 9 (delta 0), pack-reused 0
Receiving objects: 100% (9/9), done.
Checking connectivity... done.

~ $ cd test-checkout/

test-checkout $ ls
HELLOWORLD  README.md

test-checkout $ git checkout X
Branch X set up to track remote branch X from origin.
Switched to a new branch 'X'

test-checkout $ ls
HelloWorld  README.md

test-checkout $ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.

test-checkout $ ls
HELLOWORLD  README.md

test-checkout $ git --version
git version 2.6.2.windows.1
```

Isn't one of your "HelloWorld" a submodule? See issue #2966.

**Comment by mmoayyed** [comment]
This is what I see:

![image](https://cloud.githubusercontent.com/assets/1205228/10666839/ed6baa0a-7888-11e5-8eed-d82bd00cf873.png)

Next:

![image](https://cloud.githubusercontent.com/assets/1205228/10666851/020e2334-7889-11e5-9e28-e9588f695b6f.png)

The files that have issues are renamed in the destination branch. They are part of various maven modules in a multi-module maven project.

**Comment by Radrik5** [comment]
The files are not tracked in the current branch (ignored by some pattern in .gitignore) and tracked in the destination branch. Git should automatically overwrite ignored files with tracked ones, but in your case it fails to do so because (a) the file names differ in letter case only, (b) this happens on a case-insensitive file system, and (c) core.ignorecase is set to false in your git config.

Please set core.ignorecase to true: `git config core.ignorecase true`
Or globally: `git config --global core.ignorecase true`

**Comment by mmoayyed** [comment]
Thanks. That seems to have done the trick.
