### ISSUE TITLE
Allow user to customize command used to launch git bash

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#2995]
I would like to be able to change the command used to launch git bash from the Browse window, so that I can, for example, launch it within ConEmu instead of as a standalone cmd window.

**Comment by asherber** [comment]
Related to https://github.com/gitextensions/gitextensions/issues/1393 and https://github.com/gitextensions/gitextensions/issues/2216

**Comment by KindDragon** [comment]
Closing it, because same as #1393
