### ISSUE TITLE
Git credentials saving.

### ISSUE THREAD

**Issue by takinosaji** [gitextensions/gitextensions#3005]
Program asks for login and password every time I query remote repository,

--- GitExtensions2.48.05, Git 2.5.2.windows.1, Microsoft Windows NT 6.3.9600.0

**Comment by linquize** [comment]
Did you set credential helper?
Settings -> GitExtensions -> SSH -> Configure Git credential helper

**Comment by TakinosaJi** [comment]
No i haven't. Do I have to press "Suggest" button? The following pass is proposed:
"...\GitExtensions\GitCredentialWinStore\git-credential-winstore.exe"

**Comment by Rychard** [comment]
I've always manually modified my `.gitconfig` file by hand, as the default values for the credential helper (in my experience) have always been set incorrectly.

Open your local user `.gitconfig` file (Located here:`%UserProfile%\.gitconfig`)

Find the `[credential]` section, and modify it the values below.  If your file doesn't have this section, you should be able to directly copy/paste the below configuration.

```ini
[credential]
  helper = wincred
```

Here's a link to the documentation that mentions the `wincred` helper in-passing: [7.14 Git Tools - Credential Storage](https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage) 

> Note: As mentioned in the link above, you can also set it via the command prompt:
>
>     git config --global credential.helper wincred

It may be worth mentioning that [Github Desktop](https://desktop.github.com/) has always modified this configuration value on my machine (to an erroneous value, no less), which causes the same issue that you're mentioning.
