### ISSUE TITLE
System.Security.Cryptography.CryptographicException

### ISSUE THREAD

**Issue by asfarley** [gitextensions/gitextensions#3006]
I'm getting this exception when attempting to open a repository:
System.Security.Cryptography.CryptographicException
Key not valid for use in specified state.

The repo in question is a submodule in a larger project. The repo also has submodules of its own. I'm not sure if that's related to the crash. 

Opening the super-project, or submodules of the crashing repo, works fine. It's only the one repo which throws the exception. 

This is using the latest GitExtensions (GitExtensions.exe [2.48.05]) on Windows Server 2008. Everything worked up until recently when I pulled a new commit on the repo, then GitExtensions started crashing. The submodule in question has worked fine in the past. 

Git from command-line seems fine - it's possible to check out, check in, etc without errors. 

Associated info:
NBug: 1.1.2.0
CLR: 4.0.30319.34209
Target Size:Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d
Application: GitExtensions.exe [2.48.05]

Any idea what could be happening?

**Comment by asfarley** [comment]
A bit more information: if I manually check out a much earlier commit in the repo, I'm able to open it in GitExtensions. When I check out the latest, GitExtensions crashes. So this issue is at least partially related to which commit is currently checked out.

**Comment by UncleVasya** [comment]
There is another issue like this: https://github.com/gitextensions/gitextensions/issues/99

Maybe latest commit in your submodule was made by a guy who uses gravatar and GitExt crashes while trying to get or process this picture... And this could explain why older commits open up fine.

But it's a complete guess, I don't really think there's a big chance for this.

**Comment by asfarley** [comment]
Should have mentioned this earlier: I'm also able to open the same branch, on the same version of GitExtensions, using a different computer (Win8). So checking out a particular commit crashes on Win Server 2008, but doesn't crash on Win8. There could be other relevant differences between the computers but I don't know what to look for. 

I have a personal Gravatar account (associated with this Github account), but I wasn't doing the commits from this account, so I don't think that's the issue. How would git or GitExtensions find out about my Gravatar, anyway?

**Comment by asfarley** [comment]
Nm, just saw your note about the "Get author images" setting. It was checked, but unchecking it didn't fix the issue.

**Comment by EbenZhang** [comment]
Can you post the detailed exception info with stacktrace included. 


You may also want to try something as suggested [here](http://answers.microsoft.com/en-us/windows/forum/windows8_1-winapps/key-not-valid-for-use-in-specified-state/b7edbb7d-0d8c-4ac7-bfb8-93805caed4ef): move the rsa folder, run sfc scan, uninstall a windows update.

**Comment by asfarley** [comment]
Exception: System.Security.Cryptography.CryptographicException
Message: Key not valid for use in specified state.
Target Site: Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d
Source: GitUI
Stack Trace: at GitUI.RevisionGrid.<>c__DisplayClass1d.<_revisionGraphCommand_Error>b__1c()
Data["StackTrace0"]:    
   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at GitUI.BuildServerIntegration.BuildServerWatcher.GetBuildServerCredentials(IBuildServerAdapter buildServerAdapter, Boolean useStoredCredentialsIfExisting)
   at TeamCityIntegration.TeamCityAdapter.Initialize(IBuildServerWatcher buildServerWatcher, ISettingsSource config)
   at GitUI.BuildServerIntegration.BuildServerWatcher.GetBuildServerAdapter()
   at GitUI.BuildServerIntegration.BuildServerWatcher.LaunchBuildServerInfoFetchOperation()
   at GitUI.GitUIExtensions.<>c__DisplayClass18.<InvokeSync>b__17(Object s)
HResult: -2146893813

**Comment by asfarley** [comment]
Following up on EbenZhang's suggestions:
-tried moving the RSA folder, no effect
-ran sfc scan, nothing found
-the relevant Windows update doesn't appear to have been installed

**Comment by EbenZhang** [comment]
As MSDN says the `unprotect` method is per user,  it will throw the exception if the current user is not   the one who protected the data. 

Did you switch to another windows user? For example,
- logged in windows as User A, 
- provided the credential to view TeamcityBuildReport in gitextensions,
- now login as another windows user

**Comment by EbenZhang** [comment]
You can try catch the exception and set the `useStoredCredentialsIfExisting` to false if Unable to unprotect the data.

**Comment by asfarley** [comment]
Thanks, the issue was the TeamCity integration server settings (the server IP changed). I logged in as the user who originally set up the TeamCity integration, fixed the settings, then logged back in as my original user and the exception no longer occurs. Thanks for the help!

**Comment by EbenZhang** [comment]
Can you reopen this issue, as we still need to add code to handle this scenario, so the user can know he needs to renew the credential.
