### ISSUE TITLE
Linux: Diff panel lines not erased when switching to a different commit

### ISSUE THREAD

**Issue by RickMohr** [gitextensions/gitextensions#3008]
Select a commit with many lines of changes:

![image](https://cloud.githubusercontent.com/assets/2162993/10910544/edb0eb7c-820d-11e5-8fa5-02e133bef9b5.png)

Now select a commit with fewer lines:

![image](https://cloud.githubusercontent.com/assets/2162993/10910598/3c059b42-820e-11e5-873a-24d76122e549.png)

Bottom lines from the first commit are not erased.

**Comment by ricjac** [comment]
+1
