### ISSUE TITLE
Blows up when I click on Help in Branch dialog

### ISSUE THREAD

**Issue by RrnR** [gitextensions/gitextensions#3011]
Steps to reproduce:
- open GitExtensions
- open a repo
- Right-click on a commit to open the create branch dialog
- click on the "help" link at the bottom LH corner of the dialog

```
Exception: .ComponentModel.Win32Exception - the system cannot find the file specified
Target site: Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo) @ System.Diagnostics.Process
Application: GitExtensions.exe [2.48.05]
NBug: 1.1.2.0
CLR: 4.0.30319.42000

Traceback:   
  at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at GitUI.OsShellUtil.OpenUrlInDefaultBrowser(String url)
   at GitUI.UserControls.GotoUserManualControl.linkLabelHelp_LinkClicked(Object sender, LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnLinkClicked(LinkLabelLinkClickedEventArgs e)
   at System.Windows.Forms.LinkLabel.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by pmiossec** [comment]
Not be able to reproduce it...

**Comment by jbialobr** [comment]
Can you tell us what is the default value on your machine of the registry key: `HKEY_CLASSES_ROOT\http\shell\open\command`?

**Comment by pmiossec** [comment]
"C:\Program Files\Mozilla Firefox\firefox.exe" -osint -url "%1"

**Comment by jbialobr** [comment]
@pmiossec I'd rather want to see @RrnR's value of the registry key as he can't open the url.
I think GitExt should ensure that the path specified in the registry is a valid path and if not, GitExt try to find IE browser and when there is no IE it should open the url by starting a new process.

**Comment by vbjay** [comment]
I hate defaulting to IE.  Starting the process with a url should work.
Might need to use or not use shellexecute functionality.

**Comment by RrnR** [comment]
Hi,

Value data for that key is:

 "C:\Program Files (x86)\Opera\launcher.exe" -noautoupdate -- "%1"

Now I might have had Opera installed at one time - I can't remember, but
I certainly wouldn't have specified it as the default application to open
anything.  I tried changing it to:

  "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
--profile-directory="Default"

and voila - success!.  Maybe you need to handle that "file not found"
exception ;-).

Actually, the online browser-based help is pretty slick.  What are the
chances of rolling out context-sensitive help for all the menu items - i.e.
I select Commands to open that menu, hover the cursor over the branch entry
and hit F1?.

Anyway, all good.  Thanks for the pointer to the problem.

R

**Comment by RussKie** [comment]
The current implementation is no longer appropriate since Vista
https://stackoverflow.com/questions/12358432/setting-default-browser-on-vista-win7

However since Win8 MS has started hashing the value and we can't programmatically detect what the user's browser of choice is...

I've tried on W10 and Ubuntu 17.04 and `Process.Start(url)` opens the user's browser of choice and navigates to the URL observing anchors.

I'm guessing earlier versions of OS and/or browsers may have had issues opening anchors. 

I recommend simplifying the implementations to `Process.Start(url)`.
It certainly is an inconvenience to the user not scroll to the anchor, however it is much bigger inconvenience if the app crashes...
