### ISSUE TITLE
SVN repositories and externals

### ISSUE THREAD

**Issue by johnfidel** [gitextensions/gitextensions#3019]
There seems to be no possibility to checkout SVN repositories which include SVN externals. This would be a nice feature for the full port of SVN repo into GIT.

**Comment by ghanique** [comment]
I wasted a lot of time on this some time ago. This is not related to Git
Extensions, but to MSysGit which is lagging behind big time on the svn
stuff. So basically this will never work on a Windows machine.

I finally resolved this myself using a Linux VM. (Nowadays I'd probably use
a docker container, but that's a completely different story).

**Comment by johnfidel** [comment]
Hello ghanique
Thanx for the answer. In this case, I will close this issue
