### ISSUE TITLE
No recent repositories on home screen

### ISSUE THREAD

**Issue by Olmer1st** [gitextensions/gitextensions#3025]
--- GitExtensions2.48.05, Git 2.5.0, Unix 4.2.0.18, Mono 4.0.4 (Stable 4.0.4.1/5ab4c0d Tue Aug 25 23:11:51 UTC 2015)
Home screen:
![image](https://cloud.githubusercontent.com/assets/14262067/11112967/01d50088-8921-11e5-85c6-241134d98e9f.png)
Menu:
![image](https://cloud.githubusercontent.com/assets/14262067/11113004/704f3a92-8921-11e5-88a8-e845fe7dd773.png)

**Comment by UncleVasya** [comment]
Hi. This is fixed in current master.

You have 2 options:

1) Compile by yourself:

- `monodevelop`
- Open `gitextensions/GitExtensionsMono.sln`
- Build > Build All
    - For each project producing "Warning as Error", turn off that option:
    - Right-click project, go to Options > Build > Compiler
    - Uncheck "Treat warnings as errors"

--
2) Get my unofficial build:
https://github.com/UncleVasya/gitextensions/releases/tag/v2.49a.Linux.v2

**Comment by Olmer1st** [comment]
Hi,

Thank you.
1st problem fixed in your release.

Now I have new problem:
![image](https://cloud.githubusercontent.com/assets/14262067/11167870/cb2642b8-8b7d-11e5-90e7-0ff0626daf80.png)

And git extensions crashes .
Can't open  any  repository.

**Comment by Olmer1st** [comment]
I did clean install from your version everything work OK.
Thanks
