### ISSUE TITLE
UI Engine

### ISSUE THREAD

**Issue by JPomichael** [gitextensions/gitextensions#3026]
I feel the need to UI Engine.
:+1:

**Comment by vbjay** [comment]
Please add detail. What does this mean?

**Comment by JPomichael** [comment]
just beautify UI

**Comment by JPomichael** [comment]
@vbjay just beautify UI

**Comment by KindDragon** [comment]
We have no objections to that :-)

**Comment by GintasS** [comment]
The UI was improved a lot, we should close this.
