### ISSUE TITLE
How do I decide whether to use ...Setup.msi or ...SetupComplete.msi?

### ISSUE THREAD

**Issue by Perry888** [gitextensions/gitextensions#3028]
The online manual says there is a single-click installer: https://git-extensions-documentation.readthedocs.org/en/latest/getting_started.html#installation

However, there are actually two setup programs (Setup.msi and SetupComplete.msi)

Which setup program should I use? How do I decide which is appropriate?

Or is there a more up-to-date installation page I should read?

**Comment by vbjay** [comment]
One installs 3rd party things like kdiff msysgit..  the other one installs
just the program.

**Comment by hypersw** [comment]
Maybe the installer should work this way:
* There's an installer which just installs GitExt.
* Then, when OOBE dialog to check if the options are correct finds that Git and KDiff are missing (or outdated), there're buttons to install them from that dialog.

This would prevent from nested installations, which are a bit of a puzzle for users.
Also this would be a clear and step-by-step experience.
The only issue might be with administrative installs, which I'm not sure if are a point for GitExt.

**Comment by hypersw** [comment]
I mean this list:

![untitled20160419014555](https://cloud.githubusercontent.com/assets/2332070/14622122/db9548f8-05d8-11e6-9057-25fa259b8a18.png)

**Comment by KindDragon** [comment]
Good idea

**Comment by dhinged** [comment]
There's actually 3 installations now... Mono, Setup, and SetupComplete... not seeing where it describes what does what exactly:

GitExtensions-2.50.02-Mono.zip - 11.7MB
GitExtensions-2.50.02-Setup.msi - 14.9MB
GitExtensions-2.50.02-SetupComplete.msi - 60.6MB

(from the /latest link) https://github.com/gitextensions/gitextensions/releases/tag/v2.50.02

**Comment by vbjay** [comment]
Mono = portable build that can be run in mono or .net framework
Setup= MSI for program only
Setup complete = program + git+kdiff

**Comment by dhinged** [comment]
Can that be listed on the download page or another webpage it links to? I rarely see a download page with multiple versions of the install file that either isn't obvious what the differences are or doesn't explain it.

**Comment by vbjay** [comment]
This is a tool for developers written by developers.  Mono in the .net
world is pretty clear.  The documentation is pretty clear too.
https://git-extensions-documentation.readthedocs.io/en/latest/getting_started.html#installation

**Comment by dhinged** [comment]
I don't code in .NET, Sorry. Maybe it would be still be better to just post the differences on the download page for everyone to see to begin with instead of leaving it to people to guess or find these Github comments in a web search (at least the difference between Setup and SetupComplete, as people may not want all the extra berries).
