### ISSUE TITLE
After using filter, branch window remains empty

### ISSUE THREAD

**Issue by TamaHobbit** [gitextensions/gitextensions#3029]
--- GitExtensions2.48.05, Git 1.9.4.msysgit.2, Microsoft Windows NT 6.1.7601 Service Pack 1

After doing a search with the Filter:, if the search returns no results, then when you remove the text in the Filter field and press enter, this occasionally leaves the branch window empty. In such cases, even doing a new search and then clearing it again will not restore the branch window. The only solutions are to either switch branch or restart GitExtensions. It happens to me about once every 20 searches, but I am unable to reproduce it consistently.

It looks like issue #114 is back after fixing issue #2777. (GitExtensions used to crash when your search returns no results)

**Comment by EbenZhang** [comment]
I'm using the master branch on Windows7, clearing the branch filter brings the branch window back.

**Comment by jbialobr** [comment]
I cleared the 2.49 milestone as this bug is not reproducible.

**Comment by RussKie** [comment]
Re-open if this still an issue with the current version
