### ISSUE TITLE
No function print a list of commits

### ISSUE THREAD

**Issue by andrey-helldar** [gitextensions/gitextensions#3030]
--- GitExtensions 2.48.05, Git 2.5.0.windows.1, Microsoft Windows NT 6.3.9600.0

Necessary function print a list of commits.
It is advisable including detailed comments to each commit.

**Comment by ghanique** [comment]
"Print"?!? The last time I printed something it was a photo I needed to
glue in my daughters friendship booklet :-)
But export could be nice...
(I suspect, though, that there is plenty of ways to achieve this using the
command line).

**Comment by andrey-helldar** [comment]
Здравствуйте!

Ваше письмо принято в обработку. Вам постараются ответить в кратчайшие сроки.

С уважением
     автоответчик
