### ISSUE TITLE
Reset individual files in the working tree

### ISSUE THREAD

**Issue by LaughingJohn** [gitextensions/gitextensions#3031]
This is a feature request, please ignore if it's a duplicate, I did check but couldn't find it. It's also entirely possible it's already in the product but I haven't found it!

Something I and my team would find handy is an easy way to reset individual files in the working tree back to the last commit. Basically the same thing that Reset All Changes does but being able to select the changed files to reset. It would be nice to be able to select them from the working directory (we always have show current working directory changes in working tree on) and have a right click menu option. I tried reset file(s) to A or B which is already there, but that didn't seem to do anything (what are A and B?).

To do this at the moment I usually go to the last commit and do file/save as on each file, but it's a bit of  a drag and not entirely obvious to anyone new to git/git extensions.

Thank you!

**Comment by vbjay** [comment]
Go to the commit window. Right click the file.

**Comment by LaughingJohn** [comment]
OK, now I feel stupid! Thanks. Still quite like it in the diff window though ;)
