### ISSUE TITLE
Modified submodule shows strange status icon in super-project Commit window

### ISSUE THREAD

**Issue by asfarley** [gitextensions/gitextensions#3032]
I have a parent project with several submodules. Most of the submodules seem fine, but a few of the more recently added submodules are behaving oddly. 

When commits/changes are made to the correctly
-functioning submodules, I see the green up-arrow for new commits and the red exclamation point for uncommited changes. 

When commits/changes are made to the malfunctioning submodules, the submodule icon is the pencil to indicate 'changed file' instead of the submodule up-arrow/exclamation point. 

Additionally, the pencil icon appears to have been drawn twice at slightly different locations:
![bad icon](https://cloud.githubusercontent.com/assets/1622578/11251409/1dbd7388-8dff-11e5-929d-2882bf56fae9.png)

The submodule configuration looks correct everywhere I've seen. Viewing Repository->Submodules lists all of the submodules, both working and malfunctioning. Opening up the submodule repository in question looks fine, too - it's in a dirty state, but there's no obvious reason to be displaying the pencil icon.

**Comment by jbialobr** [comment]
Can you provide the output of these commands executed on your repo when you experience the problem?
```
  git status -s    
  git ls-files -z --unmerged    
  git diff -M -C -z --cached --name-status  
```

**Comment by p3d-eng** [comment]
I'm observing the same behavior on one of my projects. Hopefully this is helpful.

Basically when I open the commit dialog I see this:
![01](https://cloud.githubusercontent.com/assets/29197741/26781165/676e3e44-49ed-11e7-8e88-db899cefd157.png)
The submodule has 1 more commit but I don't want to stage that. 

As soon as I stage one of the files, the progress bar always hangs at 50% and at that point I can click on unstaged files but the diff won't change.
![02](https://cloud.githubusercontent.com/assets/29197741/26781167/6b8f80be-49ed-11e7-831c-2443404af70d.png)

Here a peek output of the above mentioned commands:
![03](https://cloud.githubusercontent.com/assets/29197741/26781408/9c09fe44-49ee-11e7-986c-a12c1526a434.png)

Sorry about the censored parts but I'm unsure of company policies.
The filenames don't have spaces of any special characters excluding the dash '-' and underscore '_' characters

**Comment by asfarley** [comment]
jbialobr: Sorry, I just saw your reply now. I'm no longer with the same company so I don't have access to the repo to reproduce the issue. Thanks for looking into this anyway.

**Comment by marlonjames** [comment]
I've been seeing this issue with 2.49.03 after I updated from Git version 1.9.5 to 2.12.2.windows.2.
I tried updating to 2.50.00 and I no longer see the weird icon, but I still get the progress bar freeze at 50% and the Unstaged window doesn't get updated after the file is added to the Staged window.
I also noticed in the bottom right the "Staged 0/<y>" count changes to "Staged 1/<y+1>".

In file GitUI/CommandsDialogs/FormCommit.cs:

1324: private void Stage(IList<GitItemStatus> gitItemStatuses)
....
there is a try/catch block which prints the exception message with Trace.WriteLine.
Using microsofts DebugView I see this: (PID 4384 is GitExtensions.exe)

[4384] Translation: Skip field FormStatus.ProcessCallback [] 
[4384] Translation: Skip field FormStatus.AbortCallback [] 
[4384] Translation: Skip field FormStatus.ProcessCallback [] 
[4384] Translation: Skip field FormStatus.AbortCallback [] 
[4384] Object reference not set to an instance of an object. 

I think theres an exception happening somewhere before it's able to cleanup and hide the progress bar.

**Comment by marlonjames** [comment]
This seems related:
When I try to see the diff for a commit that updated a submodule pointer, I see this:
![gitextensions_error](https://user-images.githubusercontent.com/14855711/27703329-db5ab20c-5cbb-11e7-8e4d-a9376ca466e9.png)

GitExtensions v 2.50.00
Git 1.9.5.msysgit.1

**Comment by marlonjames** [comment]
My problem resolved itself when I uninstalled Git and GitExtensions, then re-installed 2.50.00 and checked the "Install Git" box, rather than installing Git for Windows separately.

git bash $ git version
git version 2.12.2.windows.1

GitExtensions Tools > Settings shows "Git 2.12.2 is found on your computer"

**Comment by vbjay** [comment]
You didn't need to uninstall. All you had to do was fix the git paths in
settings.

**Comment by marlonjames** [comment]
Sorry but I don't think so.
The settings in Tools > Settings > Git Extensions > Git are **exactly the same paths** as what I had before, but now the submodule issue is gone.

**Comment by p3d-eng** [comment]
I've updated to 2.50.01 (git 2.13.2) and the behavior changed:
- The diff on the submodule still shows the error
- staging the submodule still hangs the progress bar at 50% and locks the diff pane
- staging other files works correctly but after staging the first file the submodule disappears from the unstaged list (if it wasn't staged before)
- the diff pane works correctly unless the submodule gets staged, closing and reopening the commit window makes it work again
