### ISSUE TITLE
Add preset for VisualStudio Diff Tool

### ISSUE THREAD

**Issue by KSemenenko** [gitextensions/gitextensions#3033]
I would like to have a preset to select vsdiffmerge for diff and merge

**Comment by KSemenenko** [comment]
Hi, I've decided to add a template (present) to use visual studio as a diff and merge tool. I think it's necessary for the project as it integrates to visual studio and it would be gerat to use it to the full extent. Personally I always use vsdiffmerge for work.

**Comment by RussKie** [comment]
This was merged ages ago.
