### ISSUE TITLE
"Mark" feature or other mean to compare distant commits

### ISSUE THREAD

**Issue by max630** [gitextensions/gitextensions#3036]
I would like to be able to compare distant commits conveniently. A usual case is when a want to compare a feature branch against its base (which is somewhere in mainline). Clicking on "parent" in the first commit brings me many commits away. Then I would like to compare the found parent with head of the feature branch. I could press "Back" and select it manually, but I would lose then selection of the base. All I could do is to manually scroll the view trying to locate locate the commit. Or try to limit the output with "Branches:" selector, hoping the interesting commits will be close.

The `gitk` program has a feature called "mark" - I can run "Mark this commit" command on a commit, and the mark stays on that commit however I navigate the history. Then I can compare a commit with the mark.

I'm not requesting that exact feature, but it would be nice to be able to navigate commits without losing selection, or otherwise compare commits which are far from each other

**Comment by EbenZhang** [comment]
It was my concern as well #2956, the revision grid doesnt remember the selection sometimes(The internal reason is the limitation on the number of commit the revision grid caches)

I've made a pull request to implement the functionality of comparing to another commit or branch which also includes the ability to mark a commit as a BASE and then compare another commit to it. See #3039

**Comment by max630** [comment]
Thank you. Hope you make it to merging.
