### ISSUE TITLE
Right Click Open GitExt Browse Problem

### ISSUE THREAD

**Issue by exleyd** [gitextensions/gitextensions#3037]
When opening a GitExtension window from windows explorer using the right click context menu on the repository folder and then clicking GitExt Browser I noticed a problem. If I open two or more windows this way and then minimize both of them, I am not then able to reopen either.

GitExtension 2.48.05
Windows 7

**Comment by Radrik5** [comment]
Could you please test this pull request: https://github.com/gitextensions/gitextensions/pull/2862?
You can build it using `Setup/BuildInstallers.VS2013.cmd` (there can be problem with Newtonsoft.Json.dll fixed here: https://github.com/gitextensions/gitextensions/pull/3023) or you can try my release that includes this PR: [v2.49z1](https://github.com/Radrik5/gitextensions/releases/tag/v2.49z1).

**Comment by exleyd** [comment]
Thanks very much. It worked perfectly.

**Comment by KindDragon** [comment]
Fixed by #2862
