### ISSUE TITLE
Should TFS dlls be CopyLocal? Mysterie Newtonsoft.Json v4.5

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#3041]
When `Microsoft.TeamFoundation.Build.Client.dll`(or `Microsoft.TeamFoundation.Build.Common.dll`) referenced by the TFS plugin is set to `CopyLocal`(or `Private`), the builder will copy all its dependencies to the plugins folder, such as 

- Microsoft.TeamFoundation.Diff.dll
- Microsoft.TeamFoundation.VersionControl.Client.dll
- Microsoft.TeamFoundation.WorkItemTracking.Proxy.dll
- and **Newtonsoft.Json.dll version 4.5.0**

## Two problems:

- When my TFS dlls are not in the GAC, the builder wouldn't copy `Microsoft.ServiceBus.dll` as this dll seems to be an implicit dependency of TFS, therefore the fragile `GetExports<IBuildServerSettingsUserControl, IBuildServerTypeMetadata>()` fails to load the plugins. This is relatively simple to fix by adding the `Microsoft.ServiceBus.Dll` to GAC.
- Another problem is the TFS (not sure v11 or v12) is referencing an old version (4.5.x.x) of `Newtonsoft.Json.dll` while we are using 6.0.x.x(see #2984, which added a bindredirect from 4.5 to 6.0), so each time we build the TFS plugin, the builder will copy the old version to the plugin folder, as a result GitExtension will not able to load the build server plugins.

## Fix?

The TFS dlls were not `Private`/`CopyLocal` initially when @pmiossec added the plugin. But @mnaoumov changed it for some reason I don't know (probably inadvertently).

If the TFS dlls are supposed to be in the developers'/users' GAC, then we can just set the CopyLocal property to false.
Otherwise, we should add the dlls as part of the installer.

**Comment by DanielTheCoder** [comment]
TFS dlls are part of [client object model](https://msdn.microsoft.com/en-us/library/bb130146(v=vs.120).aspx) and should be available in the GAC, either installed by visual studio or if the user installed them [manually](https://visualstudiogallery.msdn.microsoft.com/3278bfa7-64a7-4a75-b0da-ec4ccb8d21b6).
