### ISSUE TITLE
Crash on latest "master" when trying to enter a commit message

### ISSUE THREAD

**Issue by wplpgr** [gitextensions/gitextensions#3042]
I am currently running a development build (master commit 5a7c26a2ed2f498efa42c5b6a08bf82c184e2f18) of gitextentsions on Windows 8 (Visual Studio 2013) and stumbled across a crash when entering the commit message.

The code that results in the crash is in GitUI/AutoCompletion/CommitAutoCompleteProvider.cs: GetChangedFileText(...)
Basically, File.ReadAllText(...) can, and is, throwing System.IO.IOException, and this is not being handled, resulting in termination.

I can reproduce the case relatively easily: open a (new) file for writing in the root of the tree, keep it open, and then use the commit dialog. As soon as any auto-complete tries to read the contents of this new (changed) file it fails "because it is being used by another process".

(I was actually trying to debug my own code, which had partially written a file and was stopped at a break-point - I decided to commit some of the changes I had already made whilst in the break-point, and then experienced repeated crashes before I got round to putting GitExtensions into another debugger...)

**Comment by Radrik5** [comment]
Probably GitExtensions should just ignore that exception. Could you prepare a pull request?

**Comment by KindDragon** [comment]
Fixed by PR #3048
