### ISSUE TITLE
bad signature

### ISSUE THREAD

**Issue by GaoChuan1115** [gitextensions/gitextensions#3043]
在提交分支的过程中电脑蓝屏了，重新打开后，无法推送分支，无法拉取最新分支，提交画面有bad signature，我该怎么处理?

**Comment by EbenZhang** [comment]
Not sure, but delete the index file will probably fix the corruption.

- Backup  your repository
- Delete the `index` file in the `.git` folder.

**Comment by linquize** [comment]
Run `git fsck` to see what is wrong
