### ISSUE TITLE
Bug Report : "File history" confuses file extensions

### ISSUE THREAD

**Issue by wip-** [gitextensions/gitextensions#3044]
Hi, I would like to report this behavior.

In my git repository, I have the two following files:
- MyFile.fx.tt
- MyFile.fx

When I try to show the history of "MyFile.fx.tt", GitExtensions seems confused by the extension and shows me the contents of "MyFile.fx" instead.

This is a bug.

**Comment by Radrik5** [comment]
I cannot reproduce it.

```
gitextensions $ echo MyFile.fx.tt > MyFile.fx.tt
gitextensions $ echo MyFile.fx > MyFile.fx
gitextensions $ git add MyFile.fx*
warning: LF will be replaced by CRLF in MyFile.fx.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in MyFile.fx.tt.
The file will have its original line endings in your working directory.
gitextensions $ git commit -m "Test commit"
[release_z d4062a6] Test commit
warning: LF will be replaced by CRLF in MyFile.fx.
The file will have its original line endings in your working directory.
warning: LF will be replaced by CRLF in MyFile.fx.tt.
The file will have its original line endings in your working directory.
 2 files changed, 2 insertions(+)
 create mode 100644 MyFile.fx
 create mode 100644 MyFile.fx.tt
```
![image](https://cloud.githubusercontent.com/assets/9339459/11438620/1b050b1a-9507-11e5-920d-3b9c5ad2f5d4.png)
![image](https://cloud.githubusercontent.com/assets/9339459/11438621/2000492c-9507-11e5-8e36-0f492e585cd1.png)

**Comment by Radrik5** [comment]
Could you find a git command line that GitExtensions uses for MyFile.fx.tt in your case? You can use [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) for that.

**Comment by qgppl** [comment]
@wip please specify GitExtensions' version and which "Follow renames" (right click on file history graph) option are active.
Also, does your history show only commits touching one wrong file, or does it show commits touching both files?
If a file is created initially as a copy/rename of the other one, there are some workarounds in place to show correct history.
![gitex](https://cloud.githubusercontent.com/assets/339002/11446347/b859fe42-9535-11e5-8c11-4ae3500ad3f8.png)
