### ISSUE TITLE
2.49 a1 UI with black view

### ISSUE THREAD

**Issue by bygreencn** [gitextensions/gitextensions#3045]
![1111](https://cloud.githubusercontent.com/assets/22853/11439356/c2ae972c-9535-11e5-885c-dc436de67bae.png)

**Comment by EbenZhang** [comment]
Intermittent? or happens every time? Does restarting your computer help? How is other programs in the system?

Looks like running out of GDI handles(15,000 or 10, 000 system wide) or running out of memory?

**Comment by ghanique** [comment]
Are you using a window manager like Dexpot?

**Comment by bygreencn** [comment]
happens every time on win7x64, restart it is same. no  running out of memory.
I compile the code with vs2013 on master branch.
But 2.48 branch is ok.

**Comment by Huck** [comment]
maybe the answer is a bit late, but I had the same problem on my build. I was missing the Gravatar.dll in my executable folder. Once the dll is added, the black screen renders fine.

**Comment by bygreencn** [comment]
I will try it later and give the response, thanks huck, hope it would be, maybe the issue is cause the build script not copy Gravatar.dll into build package.

**Comment by bygreencn** [comment]
the result is still, so it could not be closed.
![1](https://cloud.githubusercontent.com/assets/22853/18773816/5fb9067e-8185-11e6-8bbd-17f5743fc910.PNG)

**Comment by KindDragon** [comment]
Try debug it

**Comment by Huck** [comment]
ok, my build is for VS2015 x64, so there could be differences. Running it in debug will surely raise a handled exception which causes the drawing routine to fail. Turn on breaking on handled common runtime exceptions, this will tell you what's missing.
