### ISSUE TITLE
[Mono] Error: The 'ResXFileCodeGenerator' code generator crashed: Invalid ResX input.

### ISSUE THREAD

**Issue by ArsenShnurkov** [gitextensions/gitextensions#3049]
/var/calculate/remote/distfiles/egit-src/gitextensions.git/GitUI/Properties/Resources.resx:
Error: The 'ResXFileCodeGenerator' code generator crashed: Invalid ResX input. (GitExtensionsMono)

when i remove all elements with "System.Resources.ResXFileRef" code generates normally during file save.

mono version is 4.2.1.60

Related links
2011-01-12, Joe Philllips, http://stackoverflow.com/questions/4665327
"I do not think this issue has anything to do with the resx file itself. This issue <b>recently started happening</b> on a project that has had the same resx file for over a year. The problem is likely stemming from elsewhere in the code "

https://fredreh.wordpress.com/2008/03/17/from-net-to-mono-in-a-weekend/
"I did a search and <b>replace searching for \\</b>Resources\\ and replacing <b>with /</b>Resources/ and built again this time I go a actual window."

(that works for me too - replacing \\ for / in all paths)

Probably the sources of resgen classes in mono should be updated to support another slash

**Comment by Carbenium** [comment]
Ref #3051

**Comment by Carbenium** [comment]
Builds just fine for me with Mono 4.2.1.102

**Comment by Carbenium** [comment]
I guess this can be closed since the PR is merged.

**Comment by ArsenShnurkov** [comment]
ok, i can reopen if it will not work
