### ISSUE TITLE
Changes to global gitignore do not properly propagate to the Commit button

### ISSUE THREAD

**Issue by mouseas** [gitextensions/gitextensions#3054]
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.3.9600.0

This is only a minor bug, not urgent by any measure.

Changes to a global gitignore file do not propagate to the main window's Commit button until the repository is closed and re-opened. This varies from changing the repository's .gitignore file, which updates the Commit button almost immediately after changing the .gitignore file.

Steps to reproduce:

1. Create a new file in the git repo currently open in Git Extensions. The "Commit" button should indicate that there's (at least) 1 file to commit.
1. Open Git Bash.
1. Specify a global gitignore file, eg `git config --global core.excludesfile ~/.gitignore_global`
1. Create/modify the global gitignore file, adding a definition that covers the new file from step 1.
1. Return to Git Extensions. The Commit button still indicates there's a new file to commit.
1. Click the Commit button, pulling up the commit window.
1. The new file correctly does not appear in either the unstaged or staged files lists on the left.
1. Try refreshing. Still does not appear in the file lists. Good.
1. Close the commit window. The Commit button still incorrectly indicates there is a file to commit.
1. Try refreshing the main window. The Commit button still indicates there is a file to commit.
1. Change the currently-viewed repository (or close the repo, returning to the start screen), then go back into the repo again. The Commit button now correctly indicates the number of files to commit.

I've tried some variations, and it looks like other changes which trigger an update to the Commit button will take changes in the global gitignore into account. The bug is that changes to the global gitignore do not trigger an update to the Commit button.

I also restarted Git Extensions after defining a global gitignore, in case that made any difference. It did not; the bug persists even after restarting Git Extensions.

**Comment by jbialobr** [comment]
Fixed by #3259.
