### ISSUE TITLE
"Don't set as default" option in Pull menu is ignored for three of the five items in the Pull menu.

### ISSUE THREAD

**Issue by mouseas** [gitextensions/gitextensions#3055]
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.3.9600.0

Steps to reproduce:

1. In the Pull menu (dropdown menu accessible from the Pull button, to the right of the Commit button), make sure "Don't set as default" is unchecked.
1. Choose "Pull" from the Pull menu, which should set it as the default for the Pull button and open the Pull window.
1. Close the Pull window.
1. Check "Don't set as default" in the Pull menu.
1. Choose "Fetch All" from the pull menu. It does not become the default for the Pull button, as expected.
1. Choose any of "Merge", "Rebase", or "Fetch" from the Pull menu. This becomes the default for the Pull button, against expecations.
1. Choose "Pull" from the Pull menu. It does not become the default, as expected.

Expected behavior: The "Don't set as default" option should apply to all items in the Pull menu, so that no matter which Pull option is used from the menu, the default for the Pull button remains the same.

Actual behavior: The "Don't set as default" option only applies to "Pull" and "Fetch All"; it is ignored if "Merge", "Rebase", or "Fetch" is chosen, causing that option to become the Pull button's default.

Side note: Having a boolean setting with a negative name ("Don't ...") can be confusing. Perhaps find a name which expresses the option without needing to mentally parse a double negative (e.g. "Lock default" or "Preserve default"), or invert the option (e.g. to "Set as default"), with the default remaining unchanged when the option is unchecked rather than checked.

**Comment by jbialobr** [comment]
PR 3238 is reverted.
