### ISSUE TITLE
Git cmd opening instead of git bash.

### ISSUE THREAD

**Issue by thakyZ** [gitextensions/gitextensions#3057]
I don't know if this is a problem with your program or git. But when I click on the GUI "Git Bash" it opens git in a command window and not git bash and I cannot use git from git command for some reason.

**Comment by NoAnyLove** [comment]
Have the same issue. Wish there will be a setting so that we can choose which to run, the git cmd or git bash.

**Comment by jbialobr** [comment]
>it opens git in a command window and not git bash

Can you provide some screenshots and additional description? I don't know what does it mean.
