### ISSUE TITLE
Switch to new Git Credential Manager

### ISSUE THREAD

**Issue by chrischu** [gitextensions/gitextensions#3058]
git-credential-winstore is no longer actively maintained so it might be a good idea to switch to the new Git Credential Manager (see http://blogs.msdn.com/b/visualstudioalm/archive/2015/12/08/announcing-the-git-credential-manager-for-windows-1-0.aspx).

**Comment by linquize** [comment]
Agree . It extends winstore

**Comment by karyon** [comment]
since 2.8, git for windows includes the credential manager by default. maybe we can simply remove anything related to that...?

**Comment by IDisposable** [comment]
Yes, please
