### ISSUE TITLE
Multiscreen setup: close wrong window

### ISSUE THREAD

**Issue by PavelA85** [gitextensions/gitextensions#3060]
Hi,
I have 3 display setup. one 1080p and two 4k
When I maximize GitExtension window (commit or main window) and try to close it, by moving mouse to up right corner, I get switch to other window and close it. GitExtension window stays opened.
This happens only on 4k screens (200% zoom)
Steps:
- open and maximize GE window
- open and maximize notepad.exe on the same screen
- move mouse cursor top right corner
  - expected to highlight close button
  - actual nothing is highlighted

GE version 2.49a1 (from latest source) and latest stable 2.48.05

**Comment by vbjay** [comment]
OS?

**Comment by PavelAgejkin** [comment]
Windows 10 64x

**Comment by GintasS** [comment]
Abandoning this because of age.
