### ISSUE TITLE
Preserve merges option in Git config is ignored when pulling with rebase

### ISSUE THREAD

**Issue by jjcole** [gitextensions/gitextensions#3061]
--- GitExtensions2.48.05, Git 2.6.2.windows.1, Microsoft Windows NT 6.3.9600.0

My Git config has this option:

[pull]
    rebase = preserve

When I run "git pull" in command line it successfully rebases and preserves merges.

When I pull from GitExtensions, this option appears to be ignored. Sometimes if I push and my branch is not up to date with the remote, it will automatically pull, rebase, flatten my merge commits and push, after which it's too late for me to change.

I see issues #696 and #697 for at least adding a checkbox to preserve merges, both were closed in 2011 but 4 years later I don't even see that checkbox anywhere.

**Comment by KindDragon** [comment]
> I see issues #696 and #697 for at least adding a checkbox to preserve merges, both were closed in 2011 but 4 years later I don't even see that checkbox anywhere.

Rebase form still have it in advanced options

**Comment by KindDragon** [comment]
> When I run "git pull" in command line it successfully rebases and preserves merges.

GitExt just run `git pull` with additional parameters

**Comment by jjcole** [comment]
I see it uses "git pull --rebase" which apparently does not respect the pull.rebase setting in my Git config. If there was a way to tell GitExt to just always use "git pull", like having a "use config" option next to "Merge" and "Rebase" in the Pull button dropdown, that would respect the defaults in my Git config.

I'm just revisiting this now and I cannot recreate the issue. I now get the error message below when I try to get this to happen:

"Can not perform auto pull, when merge option is set to rebase and one of the commits that are about to be rebased is a merge."

So it's still ignoring my default Git config options but at least it's safer that way, and I won't get my branches messed up and pushed to origin. I'm assuming this behaviour was introduced since I posted this bug in December.

Aside from that though, I see that if I go to Commands > Rebase there's an advanced options section that lets me preserve merges, but that option is not available if I right-click on a commit and Rebase, or in the Pull menu.

The Pull menu lets you select Rebase but says it will create a linear history so use with caution. This would be a great place to have a preserve merges button, though it would only be worthwhile if it saved my preference, since I would always want to preserve merges when rebasing a merge commit.

Clicking the Pull button (once it's showing Rebase as my preferred action) seems to have the same behaviour, it shows a warning popup asking if I really want to rebase a merge commit, but does not offer an option to preserve merges.

**Comment by GintasS** [comment]
Abandoning this because of age.
