### ISSUE TITLE
application crash caused by hotkey CTRL+P

### ISSUE THREAD

**Issue by ConnorWeng** [gitextensions/gitextensions#3063]
Whenever the RevisionGrid is not focused, pressing CTRL+P will throw a NullReferenceException. The whole application will crash after that.

For example, you can reproduce the error via pressing CTRL+P on the first window without any repositories selected.

**Comment by cgKwon** [comment]
2.48.05 is raise crash.
but, current master branch(ver. 2.49) that is no problem. 
I think it was already fixed.
