### ISSUE TITLE
GitExtensions crashes when opening repository

### ISSUE THREAD

**Issue by dolot3** [gitextensions/gitextensions#3066]
Everything was working fine with GitExtensions until I installed a newer version of GitHub for VS2015.  Now, when I start GitExtensions and try to open a repository, I get an error message:

The application has crashed and will now be dismissed.

Exception Type:  System.ComponentModel.Win32Exception

The system cannot find the specified file.

Target Site: Void <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d

Application: GitExtensions.exe 2.48.05

NBug: 1.1.2.0

CLR:4.0.30319.42000

**Comment by Karadox** [comment]
i've got exactly the same problem, same version etc...

stacktrace:
   bij GitUI.RevisionGrid.<>c__DisplayClass1d.<_revisionGraphCommand_Error>b__1c()
   bij GitUI.GitUIExtensions.<>c__DisplayClass12.<InvokeAsync>b__11(Object s)

**Comment by EbenZhang** [comment]
Maybe the same problm #2934

**Comment by Karadox** [comment]
Yes it is thx. Going to tools->settings and pressing repair fixed it.

**Comment by cmjchrisjones** [comment]
+1 for both the issue and the fix. Thank you

**Comment by dolot3** [comment]
Yep, that seems to have fixed it - good job, Zhang.
