### ISSUE TITLE
Diff for the root commit is broken in master branch

### ISSUE THREAD

**Issue by Radrik5** [gitextensions/gitextensions#3067]
The diff pane shows error: "ambiguous argument: '': unknown revision or path not in the working tree".

![image](https://cloud.githubusercontent.com/assets/9339459/11955018/ba42c86e-a8be-11e5-8e9f-1a0230d4b43b.png)

**Comment by phillijw** [comment]
This issue was introduced as part of commit de91d1366728dd4604442ccaf1478269b411651b

PR #1477 which closed #2840

**Comment by Radrik5** [comment]
@phillijw thanks, I'll fix it today.

**Comment by Radrik5** [comment]
Fixed in #3191. Sorry for inconvenience.

**Comment by KindDragon** [comment]
@phillijw @Radrik5 Thanks for debugging and fix
