### ISSUE TITLE
Option to suppress line endings warning?

### ISSUE THREAD

**Issue by mmoayyed** [gitextensions/gitextensions#3068]
```
Stage 1 files
warning: LF will be replaced by CRLF in README.md.
The file will have its original line endings in your working directory.

Done
```

Is it possible to suppress this warning via an option and just proceed?

**Comment by remcoros** [comment]
This is a message from git, you can disable it in your .gitconfig:

  git config --global safecrlf false

This disables the warning. Other values are: true (block when this happens) or the default: warn

**Comment by mmoayyed** [comment]
That tells me:

```
> git config --global safecrlf false
error: key does not contain a section: safecrlf
```

and

```
> git --version
git version 2.6.3.windows.1
```

**Comment by mmoayyed** [comment]
This works: `git config --global core.safecrlf false`
Thanks.
