### ISSUE TITLE
With New Git 2.6+, ReEncodeCommitMessage Is Not Needed?

### ISSUE THREAD

**Issue by hypersw** [gitextensions/gitextensions#3071]
In `ReEncodeCommitMessage`, there's code like this:

```
                if (isABug)
                {
                    if (toEncodingName.IsNullOrEmpty())
                        encoding = Encoding.UTF8;
                    else if (toEncodingName.Equals(LosslessEncoding.HeaderName, StringComparison.InvariantCultureIgnoreCase))
                        encoding = null; //no recoding is needed
                    else
                        encoding = Encoding.GetEncoding(toEncodingName);
                }
                else//if bug will be fixed, git should recode commit message to LogOutputEncoding
                    encoding = LogOutputEncoding;
```

It has `isABug` set to `true` and goes into recoding the messages.

As of the fresh msysgit version 2.6+, it appears to be doubly-recoded (both by git and by GE), so probably the bug has been fixed and `isABug` should be put to `false`.

**Comment by hypersw** [comment]
How do you check it for sure? 

There's a repo at https://github.com/Maximus5/conemu which demonstrates double-recoding, but might be that the repo format is incorrect (states 1251 but actually holds 65001 for example). 

How to get the raw byte content of the stored title?

**Comment by jbialobr** [comment]
Tested with git 2.9.0. The bug is still there.
