### ISSUE TITLE
Fatal exception prevents start-up on Linux Mint

### ISSUE THREAD

**Issue by patricktokeeffe** [gitextensions/gitextensions#3078]
I receive the following fatal exception at start-up on my Linux Mint 17.3 machine, while using `GitExtensions-2.48.05-Mono.zip` and following [the instructions](http://www.youtube.com/watch?v=zk2MMUQuW4s). 

Is it saying I need mono runtime version >=4.0.0.0? The current _Getting Started_ docs describe installation of mono 3.8.0 on Mac so that shouldn't be true, right? I can't find the minimum reqs in the documentation or changelog.

![screenshot from 2016-01-04 22 06 30](https://cloud.githubusercontent.com/assets/1348834/12108747/e27bbf40-b32f-11e5-9b51-e45cc690e661.png)

[text excerpt]:

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not lo
ad file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, Pub
licKeyToken=b77a5c561934e089' or one of its dependencies.
```

**Comment by KindDragon** [comment]
Sorry, we don't test on Linux Mint

**Comment by RussKie** [comment]
Please re-open if it is still an issue

**Comment by patricktokeeffe** [comment]
👍 just launched 2.50.01 without problem. I've got `mono-complete` installed fwiw
