### ISSUE TITLE
Hidden expandable column between message and author.

### ISSUE THREAD

**Issue by dale2507** [gitextensions/gitextensions#3079]
There appears to be a hidden column between message and author in the revision graph which can be resized causing lots of whitespace.

To reproduce, hover over the author in the revision graph, moving the mouse slowly to the left until the cursor changes to the resize cursor. Then click and drag to the right. In addition to the author column moving to the right, the width of the message column also shrinks causing a whitespace gap between both columns. For best results use a small window.

Looking at the code, this may be due to the IsMessageMultilineDataGridViewColumn in gitextensions/GitUI/UserControls/RevisionGrid.Designer.cs

GitExtensions version 2.48.05

**Comment by phillijw** [comment]
I'm not able to reproduce this behavior (although the columns can sometimes behave in other weird ways).

**Comment by dale2507** [comment]
Sorry it's a really awkward bug to describe. I tried to record the steps to reproduce using windows problem steps recorder but the file wouldn't upload because it is not supported. One thing it did highlight is that when I am resizing the column to produce the gap, it is the IsMessageMultiline field which I am clicking on.

I'll try to be more clear with the steps to reproduce:

1. Resize the git extensions window so that one of the commit messages is truncated with an ellipsis (...)
2. Hover between the commit message and author fields so that the mouse cursor changes to the column resize pointer (Note that there are two resizers here, I assume one is for the commit message column and the other is for the multiline commit message indicator. You must grab the one on the right).
3. Click and drag to the right.

This should result in the commit message column being truncated further and a gap appearing between the commit message and author. To remove the gap:

1. Hover at the beginning of the autho column so that the mouse cursor changes to the column resize pointer.
2. Click and drag as far left as possible.

The commit message field should now be back to normal.
