### ISSUE TITLE
Newer Versions don't work with mono twice

### ISSUE THREAD

**Issue by viper12091** [gitextensions/gitextensions#3081]
When starting GitExtensions with mono the first time everything works fine. The Second time I get an error. (see file [error.txt](https://github.com/gitextensions/gitextensions/files/79886/error.txt))
Once I delete the file user.config (see file [user.config](https://github.com/gitextensions/gitextensions/files/79892/user.config.txt)) it works again one time.
In Line 29 there is another XML-Declaration which is not supposed to be there (and is not there in the user.config created on windows). Therefore the XML-parser throws an exception.

Tested with v2.48.03 & v2.48.05

**Comment by Carbenium** [comment]
Closed by https://github.com/gitextensions/gitextensions/pull/3052
