### ISSUE TITLE
Add support for --exec=<cmd> during a rebase

### ISSUE THREAD

**Issue by carlTLR** [gitextensions/gitextensions#3088]
From:
https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.12.txt#L62

You can specify a command that must be run on each commit to verify it is good. If the command fails, the rebase stops and you can fix the commit. 

This is useful in ensuring that rebased commits can still build and pass all tests.

**Comment by GintasS** [comment]
I think we should close this, no one is working on it/no one expressed interested in this.

**Comment by vbjay** [comment]
It's already supported. Do an interactive rebase.
