### ISSUE TITLE
Blame showing incorrect file

### ISSUE THREAD

**Issue by sybblow** [gitextensions/gitextensions#3089]
--- GitExtensions2.48.05, Git 2.6.2.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

When right click "Blame" on a file at "File tree" tab, it got blame information of another file.

**Comment by vbjay** [comment]
If follow renames is set, it will do this.

**Comment by sybblow** [comment]
Indeed that problem! I see follow renames is a too smart job for a software to handle.
