### ISSUE TITLE
Add OpenType font support

### ISSUE THREAD

**Issue by cobrabr** [gitextensions/gitextensions#3092]
Hello, 

This is just a quick request to add support to OpenType (OTF) fonts in GitExt. Currently, only TrueType (TTF) fonts are supported, which makes us unable to use a couple of very good fonts ([Hermit](https://pcaro.es/p/hermit/), [Code New Roman](https://smallapp.wordpress.com/code-new-roman/) and [monoOne](https://github.com/madmalik/mononoki), among others).

Thanks,
Luciano.

**Comment by EbenZhang** [comment]
Your request is quick but not possible as far as I know because GitExtensions is using Winforms which doesn't support OpenType.  Also, converting the OTF to TTF usually results in some other issues for example aliasing.

**Comment by KindDragon** [comment]
We can't implement this

**Comment by cobrabr** [comment]
Why not?

**Comment by EbenZhang** [comment]
As i mentioned in my prevoius comment, it is a limitation of the winforms UI  framework.
