### ISSUE TITLE
git extensions has crashed and it will be dismissed error

### ISSUE THREAD

**Issue by Azteker** [gitextensions/gitextensions#3098]
When I open a repository and click commit, it reports this error. System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\GitExtensions\configscmepm-commit-msg-template'.

I tried to reinstall it and it doesn't work. All repair is finished. I am have no idea how to fix it.

**Comment by Nochdarus** [comment]
This file is also not present in my installation path and it causes no problem.
