### ISSUE TITLE
Subsitute colon style Emoji in git comments

### ISSUE THREAD

**Issue by williamdenton** [gitextensions/gitextensions#3107]
Substitute longform/colon based text style emoji for better display of commit messages.

For example replace the string literal `:lipstick:` with the relevant unicode character (💄). 

Github supports this in commit messages and markdown, however their solution is to inline a small image rather than using the default OS font. (github style :lipstick: )

:+1:

**Comment by jrmessias** [comment]
Maybe can use the styleguide for commit messages commented here https://github.com/slashsBin/styleguide-git-commit-message

**Comment by drewnoakes** [comment]
Fun idea.

Seems it mightn't be the easiest thing to implement unfortunately. Least not in colour.

https://github.com/samhocevar/emoji.wpf

Also saw some code for working with RichTextBox that did something like:

```c#
var index = textBox.Text.IndexOf(":smile:");
if (index != -1)
{
    textBox.Select(index, ":smile:".Length);
    Clipboard.SetImage(emojiImages[":smile:"]);
    textBox.Paste();
}
```

An interesting approach, but requires images (which are DPI dependent, unlike fonts) and it blows away the user's clipboard (we may be able to preserve/restore it in some cases).

For other areas of the UI, such as the grid/graph of revisions, we'd need custom render logic.

Segoe UI apparently has colour emoji.

**Comment by KvanTTT** [comment]
There is a related issue about Markdown rendering inside commit messages: https://github.com/gitextensions/gitextensions/issues/6509

**Comment by RussKie** [comment]
If we replace the richtextbox with a web bases control we can go wild with
rendering.

There's a WebView2 control for chromium based browsers (Chrome and Edge)
which we could consider.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
