### ISSUE TITLE
Prune remote branches applies to remote selected in the other tab?

### ISSUE THREAD

**Issue by dictoon** [gitextensions/gitextensions#3108]
That's pretty confusing; I'm a long time user of Git Extensions, but it took me ages to realize that `Prune remote branches` applied to the remote selected in the other tab.

I would suggest to either move the Prune button to the other tab, or add a Remotes combo next to the Prune button.

**Comment by ChrisFindlay** [comment]
Or simply a means to set the `--prune` flag during a `git fetch`.  For comparison, SourceTree's fetch dialog has a checkbox for this.  I prefer the more immediate execution of GitExtensions, but so far I haven't found a nice way of expressing prune quickly.

**Comment by KindDragon** [comment]
Related to #2141

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
