### ISSUE TITLE
New Git for Windows (2.7) compatibility?

### ISSUE THREAD

**Issue by gregsohl** [gitextensions/gitextensions#3109]
Is GitExtensions currently compatible with the new Git for Windows (currently at v2.7)?

**Comment by Radrik5** [comment]
Short answer is yes but you'll need to change paths to Git in configuration. For details see #2931, #2950 and my release [2.49z1](https://github.com/Radrik5/gitextensions/releases/tag/v2.49z1).

**Comment by EbenZhang** [comment]
Or just use the 32bits Git which will be installed to c:/programfiles(x86)

**Comment by gregsohl** [comment]
Thanks Dmitry. Looking forward to upgrading. Have a couple pull requests brewing for small functionality enhancements that I hope to have to you early this year. Haven't contributed in a couple years so want to be sure I'm doing my part. Thanks again for the great tool.
