### ISSUE TITLE
System.ComponentModel.Win32Exception after upgrade to Windows 10

### ISSUE THREAD

**Issue by traffic-camera** [gitextensions/gitextensions#3110]
After upgrading to Windows 10, I'm getting Win32Exception when opening repos that were fine previously.

"The system cannot find the file specified"

Target Site: oid <_revisionGraphCommand_Error>b__1c() @ GitUI.RevisionGrid+<>c__DisplayClass1d
GitExtensions.exe [2.48.05]
NBug: 1.1.2.0
Application: GitExtensions.exe [2.48.05]
CLR: 4.0.30319.42000

**Comment by vbjay** [comment]
Go to settings.  Check git and linux paths.

**Comment by traffic-camera** [comment]
That was it! Thank you.

**Comment by KindDragon** [comment]
Duplicate of #2934
