### ISSUE TITLE
When pulling could not read Username error

### ISSUE THREAD

**Issue by ghost** [gitextensions/gitextensions#3112]
"C:\Program Files\Git\bin\git.exe" pull --rebase --progress "origin" 
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://repo.visualstudio.com': Invalid argument
Done

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion. Also this bug requires more information.
