### ISSUE TITLE
Excluded files partially stay excluded after undo

### ISSUE THREAD

**Issue by mvdcorput** [gitextensions/gitextensions#3113]
If you change a git controlled file and exclude it in the git extension team explorer (included section) under the changes page then it is added to \.git\mspersist.xml ExcludedItems section.

If you undo that change in the excluded items section of git team explorer changes page the changes to the file are undone, but the file remains mentioned in the \.git\mspersist.xml ExcludedItems section.

If you (directly) again change the file then it is shown under the included files under the git extension team explorer changes section, however in MsPersist.xml it is still under the ExcludedItems section. If you restart visual studio at this point, the file will show up under the excluded items of the git team explorer changes page.

I suggest removing the file from ExcludedItems in MsPersist.xml when the file is undone in the git team explorer changes page excluded items section.

**Comment by EbenZhang** [comment]
Are you posting the above issue to the wrong project? If I'm not wrong that team-explorer functionality is provided by Microsoft hence nothing to do with GitExtensions.

**Comment by mvdcorput** [comment]
I'm sorry i guess you are right. I thought my Visual Studio Team Explorer 2015 Git windows were added by this extension, but they are not as i see now! This issue/bug can be closed.
