### ISSUE TITLE
Show selected branches only

### ISSUE THREAD

**Issue by webmaster33** [gitextensions/gitextensions#3114]
--- GitExtensions2.48.05, Git 2.6.3.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

I would need to display only a few of all branches. 
Suggestion: Add "Show selected branches only" feature under View menu.

SmartGit has the feature to display only the selected branches, but I prefer to use Git Extensions, so I would like to have the "Show selected branches only" feature implemented.

Thanks!

**Comment by Radrik5** [comment]
In the branches filter just enter all the branch names you want delimited by spase: `branch1 branch2`
You can also use more complex expressions there like `--remotes=origin` or `--reflog` or `@{-1}`.
This works because the entered string goes directly to the `git log` command line.
See `git help log` and `git help revisions` for details.

**Comment by webmaster33** [comment]
I tried and filtering really works. 

But my suggestion was about implementing this feature into
the GUI. It would be useful if I could select using checkboxes, which branches or tags to be displayed.

**Comment by jeffqc** [comment]
I often use the branch filter and would find very useful if it could be done with multiple checkboxes. That would be way more fast than typing a bunch of branch names inside a small textbox. Adding / removing branches from the filter would also be prettty easy.

**Comment by vbjay** [comment]
All you need is something like this control.
https://documentation.devexpress.com/#WindowsForms/clsDevExpressXtraEditorsCheckedComboBoxEdittopic

**Comment by jeffqc** [comment]
Yes exactly! We need a control like that!

**Comment by webmaster33** [comment]
Any news about this?

**Comment by webmaster33** [comment]
Could be difficult to implement a CheckedComboBoxEdit selection of branches?

I would accept this GUI solution to select only a few branches to show (in case, when "Show filtered branches" is selected in View menu):
![helpresource ashx](https://cloud.githubusercontent.com/assets/9215780/25289820/7a6c54c6-26cb-11e7-8670-655c2408f110.png)
This way we would get selectable branches feature, while we could be still keep the possibility to enter wildcard based filtering of branches.

I see there is "select branches to show" feature in SmartGit, which is very useful.
I would welcome this feature in Git Extensions, too.

**Comment by PierrotG** [comment]
Hello all,

I've been looking for this feature too, I think it could be implemented using the existing branch tree on the left. (version 3.0.2). What I had in mind was:

GUI changes:
- Replace the little branch icon with a tick box -or- have a two-state icon to indicate selection
- Add a right click menu item which reads "Add this branch to filter" when the tickbox is not checked and "Remove this branch from filter" when the tickbox is checked (next to "Delete" and "Show this branch only") which ticks the box (same effect as clicking the box directly)
- Add a right click menu item "Remove all branches from filter" which clears all selections, which would also be available when clicking in a blank area (like "Collapse All" and "Expand All")

On graph update/redraw:
- Apply the selected branches to the filter when the view is set to "Show Filtered Branches"

Special note:
- To avoid clutter and to allow adding user wildcard to the filter, the filter textbox would not be populated with the list of selected branches, instead, its content would be added to the list of selected branches

Do you think this makes sense?
I'll see if I can make a prototype for it, I still have to figure out how to build the whole thing.

**Comment by RussKie** [comment]
It is a very interesting proposal, and it has merits. We just need to work through UI and UX.

I'm a little unsure about showing checkboxes all the time though.
I have nearly a hundred of branches in Git Extensions alone, I think checkboxes will create a lot of visual noise
![image](https://user-images.githubusercontent.com/4403806/59731817-03995280-928b-11e9-9ed5-76dacaadcfb6.png)

If we could perhaps do it like Windows Explorer does - show a checkbox on hover:
![image](https://user-images.githubusercontent.com/4403806/59731762-d056c380-928a-11e9-85ed-71214b82a4c9.png)


> I still have to figure out how to build the whole thing.

It should be straight forward - fork, pull down, update submodules, compile, run.
If you get stuck shout on gitter, someone will lend you a hand

**Comment by PierrotG** [comment]
Thanks, I didn't try it yet, just forked, pulled and I had a quick look at the code. I'll check it out this week-end.
For the UI the hover checkbox would work I guess, as long as there is some visual feedback that a branch is selected for viewing (different icon).

**Comment by RussKie** [comment]
It will be checked

**Comment by NN---** [comment]
Is there a way to do it from the commits view and not only from branches tree ?

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion. Also, it seems that no one has checked it out.

**Comment by RussKie** [comment]
This is still relevant.

**Comment by h0lg** [comment]
Love the idea of implementing the selection of multiple branches (and the ability to only show the selected in the revision grid) into the left branch tree panel. At that point I wouldn't even need the branch filter in the top toolbar any more.
