### ISSUE TITLE
Add UNC path (network share) support in GUI

### ISSUE THREAD

**Issue by carlin-q-scott** [gitextensions/gitextensions#3116]
I tried adding a repo using a network share path (ie. //hostname/share-name/repo-name) but it failed to detect the repo. I then dropped down into git-bash and ran this command succesffully to add the remote:
git remote add remote-name //hostname/share-name/repo-name

After running that command I was able to use the remote with the GUI.

**Comment by pmiossec** [comment]
Like I described in my pull request, I think that since a new version of git, now it works well with UNC path and do not work anymore with windows network share.
The PR fix that...

**Comment by vbjay** [comment]
Might want to detect git version.  We support back to git 1.7.  Does the format change between 1.7 and 2.9?

**Comment by pmiossec** [comment]
Don't know :(

**Comment by KindDragon** [comment]
> I tried adding a repo using a network share path (ie. //hostname/share-name/repo-name) but it failed

It's incorrect format, you should use this backslash instead
https://en.wikipedia.org/wiki/Path_(computing)

> Like I described in my pull request, I think that since a new version of git, now it works well with UNC path and do not work anymore with windows network share.

I think all git version not support forward slash for UNC path. I do not know whether we need to fix it

**Comment by jbialobr** [comment]
> I do not know whether we need to fix it

I suggest to lable it as a feature request and remove it from the 2.49 milestone.
