### ISSUE TITLE
"stash save" corrupts NetBeans project

### ISSUE THREAD

**Issue by Wirone** [gitextensions/gitextensions#3118]
GitExtensions 2.48.05
Git 2.7.0.windows.1 (the same behaviour was with 2.6.3.windows.1)

Every time I do `stash save` using GitExtensions GUI, I get my NetBeans project (related with this repo and opened while stashing) corrupted. "Source Files" section is empty, previously opened files doesn't work properly (for example ctrl+click does not navigate to class/method).

It is annoying because every time I lose my project's configuration (sorce/web dirs, ApiGen config etc.). I keep copies ob `nbproject` dir (if I remember), but this is not a solution.

PS. Thanks for awesome tool!

**Comment by vbjay** [comment]
Stash saves a couple of fake commits for 5he state and then resets t9 the
last commit before the stash commits. I would try closing NetBeans and then
opening it back up after stashing.

**Comment by Radrik5** [comment]
There could also be a problem with `dir/*` pattern in .gitignore. Please check that you use `dir/` instead of `dir/*`.

**Comment by Wirone** [comment]
@Radrik5 Thanks, that's it! I had `/nbproject/*` in `.gitignore.`. After removing `*` stashing does not corrupt NetBeans project.
