### ISSUE TITLE
Github cloning has authentication issues

### ISSUE THREAD

**Issue by urbanhop** [gitextensions/gitextensions#3120]
When I clone a github repo with Git Extensions, I get this error message:

```
"C:\Program Files\Git\bin\git.exe" clone -v --progress "git@github.com:corsis/XParsec.git" "m:XParsec"
Cloning into 'm:XParsec'...
**FATAL ERROR: Disconnected: No supported authentication methods available (server sent: publickey)
fatal: Could not read from remote repository.**

Please make sure you have the correct access rights
and the repository exists.
Done
```

With the command line I can clone very easily:

git clone https://github.com/... reponame

without any authentication issus involved. Why is this the case?

**Comment by jbialobr** [comment]
Please read https://help.github.com/articles/which-remote-url-should-i-use/
You used a ssh url in GitExt and https url in command line.
