### ISSUE TITLE
Checkbox "Force" in the Dialog: Add Submodule 

### ISSUE THREAD

**Issue by khalie** [gitextensions/gitextensions#3123]
Hello,

I am looking for information about the "Force" Checkbox in the Dialog Add Submodule. 
Can someone tell me what the checkbox does?

These are the Places I already searched for an answer:

The checkbox isn't part of the documentation on this website. I assume it was added at some point after that. The Documentation Repository on GitHub has the same version. I think the Website is based on the Documentation Repository.
http://git-extensions-documentation.readthedocs.org/en/latest/submodules.html

Thank you for your time and effort on this,

Peter Henniger

**Comment by KindDragon** [comment]
Check `--force` argument here https://git-scm.com/docs/git-submodule
