### ISSUE TITLE
Useability suggestion; Navigate to common parent

### ISSUE THREAD

**Issue by TamaMcGlinn** [gitextensions/gitextensions#3124]
Cntrl-P, or right-click > Navigate > Go to parent commit
should have this additional feature; if more than one commit is selected, instead of grabbing the last commit selected, it should go to the common parent. It would be nice if the dialog name also changed to "Go to common parent".

**Comment by linquize** [comment]
:+1:

**Comment by MpDzik** [comment]
:+1:

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.

**Comment by TamaMcGlinn** [comment]
I don't think that's really correct though - the status was 'open' reflecting that anyone can pick this up if they want. Adding 'abandoned' would suggest that it was abandoned - i.e. someone picked it up but then stopped working on it.

**Comment by RussKie** [comment]
No one had any interest or inclination to implement this in 5 years, so it is technically abandoned.
