### ISSUE TITLE
git status origin/branch

### ISSUE THREAD

**Issue by tlhackque** [gitextensions/gitextensions#3126]
There doesn't seem to be a way to do the equivalent of

``` bash
# git status origin/<current branch>
```

in git extensions.

There should be - it's useful to be able to get status like:

``` bash
# git status origin/master
On branch master
Your branch is ahead of 'origin/master' by 4 commits.
  (use "git push" to publish your local commits)

nothing to commit, working directory clean
```

**Comment by ghanique** [comment]
Doesn't the graph provide the very same information graphically after a
Fetch All?

**Comment by crypto-rsa** [comment]
How exactly does the graph provide that information? SourceTree's solution is quite nice - next to the branch name there is a little box with the number of ahead/behind commits. Could GE show something similar? 
![obrazek](https://cloud.githubusercontent.com/assets/11479798/22205553/a0fc6796-e177-11e6-8594-a81a3839bb09.png)

**Comment by RussKie** [comment]
Could you clarify why this information is useful to display?

**Comment by vbjay** [comment]
The console is there. Also we have to know which branch to base off of,
master, develop....

**Comment by gerhardol** [comment]
It would be useful to see this in the GUI when you have not pushed (or merged) changes  yet.
Right now you will have to do this visually by looking at the arrows for current local and current remote branch.

Low prio for me

**Comment by vbjay** [comment]
So your saying the branch that would be used, is the branch that would be pushed if using defaults?  

Local develop would use origin/develop  but if I had it set to use upstream/develop, that would be used?
![image](https://user-images.githubusercontent.com/3629489/41872685-a966f408-7890-11e8-823a-b8c2944032be.png)

**Comment by gerhardol** [comment]
The same as for the arrow in Browse: The default

**Comment by vbjay** [comment]
I'd start with that but abstract it to allow the user to set the other branch to use till reload. 

Let me see what origin/develop is compared to upstream/develop for example.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion. Console exists, @gerhardol has mentioned that it's a low priority, no one else is interested with this.

**Comment by vbjay** [comment]
Doing a fetch vs pull is one way.

**Comment by gerhardol** [comment]
Ahead/behind is available in Push button for current branch and in the side panel
