### ISSUE TITLE
Delete selected, poor usability = lost changes

### ISSUE THREAD

**Issue by aweintraut** [gitextensions/gitextensions#3127]
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

![capture](https://cloud.githubusercontent.com/assets/13574789/13113205/1120a1e6-d55c-11e5-869f-86a59fe726f9.JPG)

Just learned the very hard way that the "Delete Selected" option in the Stash window, does not "delete selected" from the list it's directly below, it "deletes selected" from the combobox drop-down at the top, essentially deleting all of my changes.

Can you PLEASE name this something like "Delete Stash"?  vs "Delete change from stash"?

**Comment by vcpp** [comment]
By the way changes could survive in the “recycle bin” (aka reflog).
