### ISSUE TITLE
Multiple push dialogs are opened if push called from taskBar

### ISSUE THREAD

**Issue by mike-hmelov** [gitextensions/gitextensions#3128]
On mouse hover GitExtention intask bar preview appears with commit,pull and push buttons. If you press push button multiple times, multiple push dialogs are opened.

Please see attached screenshot
Environment:
Windows 7 SP1
.Net 4.5
![push-bug](https://cloud.githubusercontent.com/assets/5302590/13139003/f401a2e0-d632-11e5-8519-5df80ad3a67b.png)

**Comment by KindDragon** [comment]
Don't press it multiple times :)

**Comment by GintasS** [comment]
This bug is still here, on Git Extensions 3.5.2.
