### ISSUE TITLE
Full diff in visual diff window.

### ISSUE THREAD

**Issue by Thuffir** [gitextensions/gitextensions#3129]
It would be nice if GitExtensions could show a visual diff over multiple files (not just one) in the diff window. (For example if someone selects multiple files in the left file window.)

Use case:
Some web based code review tools request diffs to upload or to paste. Users could cut'n'paste easily diffs this way.

**Comment by mika76** [comment]
:+1:

**Comment by drewnoakes** [comment]
Relates to #3600.

**Comment by GintasS** [comment]
A duplicate of #3600, this should be closed.

**Comment by gerhardol** [comment]
#3600 allows to continuously scroll between the files. Compare to gitk where all diffs are sequenced.
The solution in #7900 what was reasonable.
