### ISSUE TITLE
Full date or configurable date in the browse window

### ISSUE THREAD

**Issue by TheCycoONE** [gitextensions/gitextensions#3133]
I find the ```14 days ago``` view unhelpful, particularly when I want to quickly find commits from a particular date range. It would be nice to see the full date (that we see in the commit) instead.

If some people find ```14 days ago``` helpful perhaps it could be an appearance setting.

**Comment by EbenZhang** [comment]
Dont have gitextensions on hand, but It is definitely configurable. Try the context menu. Just right click the grid and select the last item (it is **view**, if i remember correctly), the show relative date is a sub menu. Or maybe in the settings.

**Comment by TheCycoONE** [comment]
Thanks @EbenZhang , it was Show Relative Date in the view menu. I had looked for something and didn't stumble into it.
