### ISSUE TITLE
Keep Commit window open after commit

### ISSUE THREAD

**Issue by Zabanya** [gitextensions/gitextensions#3138]
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.3.9600.0

if there is still an uncommitted, or until i close it manually?.
it is actually pain when i had a lot to commit.

**Comment by EbenZhang** [comment]
There is an option on the right top corner of the commit message editor to NOT close the dialog if still any uncommited. 

By the way we should change to make it default.

**Comment by Zabanya** [comment]
:+1: Thanks, i found it, i though it was a button near minimize, maximize, close

**Comment by vbjay** [comment]
Can't please everyone. The option exists. Switching value is not hard.

**Comment by QuestGamer7** [comment]
> Can't please everyone. The option exists. Switching value is not hard. So having user check or uncheck an item is good enough.

Lets agree to disagree. I understand your point, although was just pointing something out that I thought was misinterpreted and seemed very clear to me that the wrong option was selected. But I understand other people might have a different opinion on this. Nothing more to add to this.
