### ISSUE TITLE
Visual C++ Runtime Error R6016

### ISSUE THREAD

**Issue by kaotik4266** [gitextensions/gitextensions#3139]
Occurs intermittently in release build of the latest commit a251b0f974 on Windows 8.1. I've seen this three times in the past two days (with GitExtensions open for most of the day).

It does not seem to be correlated with any user action and generally occurs while GitExtensions is minimised or in the background. 

![untitled](https://cloud.githubusercontent.com/assets/4526480/13413896/1e6add9e-dfa2-11e5-8075-a147e5f9c80f.png)

**Comment by vbjay** [comment]
When it happens check the memory status.  Use
https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx  I am
wondering if you are running out of memory or getting too low.

**Comment by kaotik4266** [comment]
Will do, but this desktop has enough spare RAM that it would have to be hitting x86 limits, and it's currently sitting around ~350MB.

**Comment by kaotik4266** [comment]
I haven't seen this error in the ~4 full days I've used GitExtensions since your reply. I suspect, then, that this was caused by some temporary system condition rather than an actual bug. If the situation changes I'll reopen this issue.

**Comment by kaotik4266** [comment]
And then, naturally, it happens only a couple of hours after closing the issue. Here is the Process Explorer memory info immediately after the error message being displayed:

![untitled](https://cloud.githubusercontent.com/assets/4526480/13560246/1f8734ec-e471-11e5-82cf-4a2cb2da5113.png)

![untitled2](https://cloud.githubusercontent.com/assets/4526480/13560247/20e1386a-e471-11e5-8021-6b5cb11b750d.png)

**Comment by kaotik4266** [comment]
That whole `git.exe` sub-tree disappears after clicking `Ok` on the error message, so it may be something to do with the periodic background fetch?

**Comment by KindDragon** [comment]
I think it's git issue. What git version you use?
Try update it

**Comment by kaotik4266** [comment]
I was already using 2.7.2, but I've reinstalled it. (Version 2.7.3 has been released, but the git website is still only giving me an installer for 2.7.2.)

**Comment by RussKie** [comment]
Please re-open if it is still an issue.
