### ISSUE TITLE
How to fix the Windows Git Extensions to save https git username and password

### ISSUE THREAD

**Issue by bjevans** [gitextensions/gitextensions#3140]
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1
I've looked at a number of sites to try to figure out how to have git store my https git username and password.  

[credential]
	helper = wincred
OR
[credential]
	helper = !'C:\\Users\\<<username>>\\AppData\\Roaming\\GitCredStore\\git-credential-winstore.exe'

When I put either of the following in my .gitconfig file, I get the error
fatal:  repository'https://github.com/<<repository>>" not found

Any ideas?

**Comment by KvantVS** [comment]
so... can you, somebody, just answer that question?)

**Comment by KindDragon** [comment]
GitExt doesn't contain git-credential-winstore animore. Install latest Git that include Git Credential Manager
