### ISSUE TITLE
Why not IDE itself convert spaces to underscore while creating a branch for example? Is it so hard?

### ISSUE THREAD

**Issue by qasims** [gitextensions/gitextensions#3141]
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by qasims** [comment]
I want to contribute to it.

**Comment by linquize** [comment]
You mean branch name has underscore?

**Comment by qasims** [comment]
I can't do like this it should conver itself to "this_is_my_branch"
![image](https://cloud.githubusercontent.com/assets/3830639/13602329/67d5e368-e536-11e5-882e-ee948d7383e0.png)

**Comment by RussKie** [comment]
There https://github.com/gitextensions/gitextensions/pull/3233
