### ISSUE TITLE
Option to take theirs everywhere

### ISSUE THREAD

**Issue by lanierhall-doubleline** [gitextensions/gitextensions#3143]
Make an option to take theirs or ours in all files in a merge or rebase conflict scenario

**Comment by vbjay** [comment]
https://www.perforce.com/product/components/perforce-visual-merge-and-diff-tools

**Comment by jbialobr** [comment]
Done in #2834

**Comment by webmaster33** [comment]
I also missed the ability to take theirs or ours in all files in a merge or rebase conflict scenario. 
I welcome this feature!
