### ISSUE TITLE
Cannot Clone Repositories with Filenames Containing Colons

### ISSUE THREAD

**Issue by NOYB** [gitextensions/gitextensions#3145]
Is there a way to clone a repository that has filenames containing colons?

NTFS does not support colon in filenames.  It does however support %3A (colon).  Maybe gitextensions could do colon substitution.

Same goes for question mark:  %3F

**Comment by ghanique** [comment]
I don't think this has anything to do with Git Extensions. Git Extensions
is "merely" a Git Wrapper. Git Extensions doesn't checkout files (that have
colons), so there is nothing that Git Extensions can do here.

Having colons in filenames is bad practice to begin with, but this was
probably out of your scope of influence. That leaves you with two choices:
clone on a filesystem that does support filenames with colons or rewrite
history to rename files with colons throughout the repository. (The latter
is quite complex, but it can be done).
