### ISSUE TITLE
Allow "Diff contains" search to specify begin and endpoint

### ISSUE THREAD

**Issue by TamaMcGlinn** [gitextensions/gitextensions#3149]
git diff commitHashA..commitHashB -G "expression" is not a slow operation. The trouble is though, the GitExtensions interface does not allow us to specify the begin and endpoint commits.

See also: #1691

**Comment by ghanique** [comment]
Doesn't it? Select one commit, hold Ctrl, select the other commit. Examine
the diff-window on the bottom right. Or am I mistunderstanding what you're
looking for?

**Comment by TamaHobbit** [comment]
I'm talking about the search functionality; "Filter: " and then selecting: "Diff contains (SLOW)"
This doesn't seem to work in combination with diffing using cntrl as you described.

**Comment by azarkevich** [comment]
You can use next steps:

1. Insert begin..end into Branches filter
2. Insert filter and perform search

![2017-03-10 18_25_59-gitextensions r2 49-plus - git extensions](https://cloud.githubusercontent.com/assets/703544/23800981/705fa712-05bf-11e7-86fc-8f7c9d7f5cbb.png)
