### ISSUE TITLE
The commit info panel does not auto resize

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#3150]
It always shows the scroll bar, for example:

![commitinfoscrollbar](https://cloud.githubusercontent.com/assets/596334/13781664/149501d8-eaff-11e5-8ac6-df73f7a07a94.png)

We have something in the code to resize the panel, but seems not working: 

``` C#
_RevisionHeader.Height = _RevisionHeader.GetPreferredSize(new System.Drawing.Size(0, 0)).Height;
```

**Comment by jbialobr** [comment]
Duplicates #2670.
