### ISSUE TITLE
Saving new remote clears URL entry

### ISSUE THREAD

**Issue by patricktokeeffe** [gitextensions/gitextensions#3154]
1. Open the 'Remote repositories' dialog and press the "New" button. 
2. Enter details into 'Name' field and 'Url' field. 
3. Press "Save changes" button.
4. Observe 'Url' field has been cleared (entry was not saved).

Using 2.48.05 on Windows 7 x86

**Comment by RussKie** [comment]
That form is all messed up and the whole remotes management is too... :(

**Comment by vbjay** [comment]
I agree.  The urls stick around and get replaced with old values all the
time.

**Comment by RussKie** [comment]
I did some work in that area, but the PR went stale (https://github.com/gitextensions/gitextensions/pull/2747).
I'll dig it up and re-submit when get some time.
