### ISSUE TITLE
[Feature Request] Add push-mode to Git Settings options window

### ISSUE THREAD

**Issue by Meligy** [gitextensions/gitextensions#3156]
I often use the git terminal and GitExtensions interchangeably. The terminal button in the main window is awesome for that too.

Would it be possible to add a setting for default push mode in the Git? It's not something people would use everyday, but nice to have instead of looking up the confusing thing to set it.

**Comment by KindDragon** [comment]
JFI http://stackoverflow.com/a/21865319/61505

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
