### ISSUE TITLE
--fixup

### ISSUE THREAD

**Issue by tibmeister** [gitextensions/gitextensions#3157]
I don't see anyway of using the --fixup feature when committing changes.  Can this be added?

**Comment by vbjay** [comment]
![image](https://cloud.githubusercontent.com/assets/3629489/14129622/9b4967a0-f5f9-11e5-99c7-4b8b67ca5da1.png)

Right click commit.  Then perform a rebase. Use auto squash in the rebase.

**Comment by tibmeister** [comment]
Oh interesting, not quite where I would've expected it to be but then again that works!
