### ISSUE TITLE
Git extensions very slow during network problems

### ISSUE THREAD

**Issue by kamilvlcek** [gitextensions/gitextensions#3158]
I use wifi internet connection and when there is no signal - so there is no network connection- GiExtensions starts to be really slow. Just getting response (commit message) after a click to another commit in the local history lasts many seconds, get Diff listed may be half minute. And checkout lasts more than ten minutes. It's not using processor time, so it seems to wait for something. 
When the internet connection is working, GitExtensions respond quickly. 

--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by RussKie** [comment]
I often work during commute with limited or no network connection and I have no problems.
Re-open if it is still a problem with the current version.

**Comment by vbjay** [comment]
Are you using a unc path for anything?  Git repo, diff tool....
