### ISSUE TITLE
Support signing commits via GPG

### ISSUE THREAD

**Issue by mmoayyed** [gitextensions/gitextensions#3161]
Similar to https://confluence.atlassian.com/sourcetreekb/setup-gpg-to-sign-commits-within-sourcetree-765397791.html?continue=https%3A%2F%2Fconfluence.atlassian.com%2Fsourcetreekb%2Fsetup-gpg-to-sign-commits-within-sourcetree-765397791.html&application=cac

**Comment by drauch** [comment]
I would love to see that feature soon, as GitHub is now supporting GPG signing as well!

**Comment by chrischu** [comment]
Oh yes, that would be tremendously useful (especially saving the Passphrase so I don't have to enter it every time).

**Comment by mrexodia** [comment]
I wrote a [blog post](http://mrexodia.cf/guide/2016/05/30/Github-Gpg) that explains how to combine GPG and Git Extensions. If you configure the caching times like I did you will only have to enter your GPG passphrase once per coding session.

**Comment by ZoltanTakacs** [comment]
It was useful! Thank you @mrexodia!

**Comment by mmoayyed** [comment]
Based on the blog post, now I keep getting this: 

![image](https://cloud.githubusercontent.com/assets/1205228/15659593/d5563668-2681-11e6-9b3e-d85e55913038.png)

I can commit just fine via the command prompt.

**Comment by mrexodia** [comment]
@mmoayyed You did not configure GPG correctly, probably you forgot to run:

`git config --global gpg.program "C:/Program Files (x86)/GNU/GnuPG/gpg2.exe"`

This should be the location where you installed gpg, per default git uses a gpg version that has different configuration files (and doesn't show this popup).

**Comment by mmoayyed** [comment]
No. I have:

```
> git config --global gpg.program
C:/Program Files (x86)/GNU/GnuPG/gpg2.exe
```

and 

```
> git config --global user.signingkey
6A2EF9AA
```

and also had to set:
 
```
> echo %GNUPGHOME%
C:\Users\misagh\.gnupg
```

Still get that message, though I can commit from the command-prompt. Not sure if I need to restart.

**Comment by mrexodia** [comment]
Try removing the GNUPGHOME variable, it will override the correct directory
(%appdata%\GNUPGHOME)

**Comment by mmoayyed** [comment]
Will try again. I had it removed originally and then kept error messages that said "can't find key". 

Based on this blog post in fact:
http://www.thomasmuntaner.com/blog/gpg-with-git-on-windows-secret-key-not-available/

With that set, I can commit from the command line.

**Comment by mmoayyed** [comment]
Restart did help :) Works now as advertised. Thanks @mrexodia

**Comment by frakman1** [comment]
> I wrote a [blog post](http://mrexodia.cf/guide/2016/05/30/Github-Gpg) that explains how to combine GPG and Git Extensions. If you configure the caching times like I did you will only have to enter your GPG passphrase once per coding session.

This page is no longer available.

**Comment by jrfnl** [comment]
Looks like you can still read the article via Wayback Machine: https://web.archive.org/web/20180906085226/http://www.mrexodia.cf/guide/2016/05/30/Github-Gpg

**Comment by vbjay** [comment]
I'm working on a feature to do the following:

- drop-down lists for the secret key selection in tag and commit areas
- show default key and show by default of gpgSign config values are set
https://github.com/gitextensions/gitextensions/pull/10308

- configure gpg signing config options -later pull request.

**Comment by vbjay** [comment]
I'd like to share the presentation “'Git Signing'” with you. Please click the link to view it. 
https://prezi.com/view/ZFnp8AA9z96Bk4uHFdS9

**Comment by Bluscream** [comment]
Can you just make this an extension?
