### ISSUE TITLE
"Add to gitignore" should include "/" prefix

### ISSUE THREAD

**Issue by TamaHobbit** [gitextensions/gitextensions#3162]
By default, you want to ignore specifically just that file you right-clicked in your changes; therefore, it should start with / so that it doesn't match any file or folder in your project that happens to have that name.

**Comment by vbjay** [comment]
Not just /.  / means root of working tree.  If you put /myfile it will
match /myfile and not /other/myfile but what about /other2/myfile?  We just
need a checkbox that alters it to generate a full path from / of working
directory.

**Comment by KindDragon** [comment]
I think it should add full path with / or only filename without path and /
