### ISSUE TITLE
WinMerge is not supported as a mergetool (only as difftool)

### ISSUE THREAD

**Issue by kyanha** [gitextensions/gitextensions#3163]
See title.  Is this intentional?  Is there something about WinMerge that makes it not work as a mergetool?

**Comment by KindDragon** [comment]
WinMerge doesn't support 3 way merge

**Comment by vbjay** [comment]
Use this.
https://www.perforce.com/product/components/perforce-visual-merge-and-diff-tools

**Comment by kyanha** [comment]
Thanks for the pointer, @vbjay.

**Comment by regs01** [comment]
WinMerge JP does support 3-way merge.

Parameters 
 -e -ub -fr -ar -wl -wm -dl base -dm remote -dr local "$BASE" "$REMOTE" "$LOCAL" -o "$MERGED"

https://translate.googleusercontent.com/translate_c?depth=1&hl=en&rurl=translate.google.com&sl=auto&sp=nmt4&u=http://www.geocities.co.jp/SiliconValley-SanJose/8165/winmerge.html&usg=ALkJrhiXMCTSkmzJTR5MH3raXBAO8MCjPg#3way-merge

**Comment by KindDragon** [comment]
We don't support `WinMerge JP`, you can setup it manually http://git-extensions-documentation.readthedocs.io/en/release-2.49/settings.html#git-config

**Comment by RussKie** [comment]
It requires code changes.
The quickest way is to send a PR with a change, else wait until someone else sends a PR.
Given that this issue is closed, I suggest you open a new issue. A good idea to back-reference this one too.

**Comment by hansfn** [comment]
Thx for the quick reply. I'll create a new issue and provide an initial patch. Not sure I have the tool chain installed to build the complete thing.

**Comment by RussKie** [comment]
#5090 can be used as some guidance

**Comment by RussKie** [comment]
In the commit message for your PR you should write `Fixes #3163`, even though it is already closed we'll get x-references
