### ISSUE TITLE
Allow change the order in the "View changes" Diff window

### ISSUE THREAD

**Issue by MaDill** [gitextensions/gitextensions#3164]
At the moment the order of the three areas is fix and can be adjusted by size. For me it would be nice to arrange also the order. At the moment it looks like this
![original](https://cloud.githubusercontent.com/assets/7298934/14377549/83c9266e-fd70-11e5-8ad9-18574d3f347a.png)

I prefer for example a order with a bigger area to check the file content like this
![request](https://cloud.githubusercontent.com/assets/7298934/14377573/a82f8b6a-fd70-11e5-8589-3eb3c316362b.png)

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
