### ISSUE TITLE
Option to hide certain branches

### ISSUE THREAD

**Issue by onno74** [gitextensions/gitextensions#3165]
I would like an option to hide certain branches. If a branch is hidden, no commits from that branch should be shown, even if they are part of the history of the current branch.

This would be especially useful if there are multiple subtree branches where other repositories are tracked and occasionally merged. By hiding them I could avoid cluttering my project history, but I would be able to unhide them if needed.

This might be related to #2351

**Comment by PierrotG** [comment]
While git can't know which commits are from which branch (as a branch in git is only a pointer to a specific commit), it's certainly possible to display a more linear history by only showing the first parents and maybe hiding the merge commit as an additional option.
I already had tried to do something similar using grafts (git rev-list --first-parent --merges --parents HEAD | cut -d' ' -f1,2 > "$gitdir"/info/grafts) but a built-in solution would be much easier to use.

**Comment by onno74** [comment]
Thanks for your reply. But maybe I wasn't clear enough about the feature I am looking for.

First, though a branch is a pointer to a specific commit, git does know which commits contributed to that state. These are the commits that I see when I check out that branch and select "show only current branch". I know that when you merge branch A into branch B, git does not know if a commit that is now part of the history of branch B belonged to that branch B when it was initially committed. But that's no problem.

For example: start with commit M1. Create Branch A. Do commit A1 in A. Do commit M1 in master. Merge master into A. Do commit A2 in A. Do commit M2 in master. Merge Branch A into master. Now look at master, hiding branch A (which points to A2). You would see the merge commit and M2. You would NOT see M1, because it has become part of the history of A. That might not be what a naïve user expects. But it's OK for my purpose.

I would like to use the feature to work with git subtrees. The master never gets merged into subtrees, you only merge the subtree into the master or split the master into the subtree. Therefore, if you display the master and hide the subtree, you get a useful display of the history of the master which is not cluttered with the history of the subtree.

grafts does not help be.The command you suggested does not show any branches that have been merged. I only want to hide the subtree branch.

**Comment by Radrik5** [comment]
The "Branches:" filter in Git Extensions is very powerful. Everything you enter there goes directly to the git log command line. So, you can enter "master ^subtree" to see all the commits from the master branch excluding commits from the subtree branch.

**Comment by PierrotG** [comment]
@Radrik5: Very good suggestion, it is very powerful indeed. 
I have one big issue with it, when I use it I get branch lines that come out of every merge commit, just like if it is a merge with another, unique branch that is not visible on the graph, visually branch lines are piling up on the right of the graph.
My repository has two branches, dev and import. import is often merged into dev (other direction never happens). I tried filter "dev ^import"

**Comment by PierrotG** [comment]
From my previous comment, using "--first-parent" works (which is great) but the visual issue with branches piling up remains.
Using --first-parent is very useful in my opinion as ^ needs to be repeated for every branch to be excluded, and doesn't work when branches were deleted or when a fast forward occurred.

It gitextensions could avoid drawing the full branch line (or at least avoid piling them up by only showing a stub line) when one the parent commit is not visible, that'd solve the issue nicely.

**Comment by bmikolaj** [comment]
I too would like to see this feature implemented.

**Comment by webmaster33** [comment]
I would invert the suggestion. 
I would like to select those branches with checkboxes, which I need to show. 

If there are "Select all" and "Select none" buttons available, then this would satisfy both requirements of select to hide or select to show.

**Comment by digitalbanana** [comment]
this would help us also - we have github coding tests that we ask prospective candidates to branch and complete. It would be massively helpful if we could hide previous applications (without deleting them)

**Comment by deggertsen** [comment]
For many of the same reasons mentioned above, this would be a helpful feature.

**Comment by GintasS** [comment]
A similar issue (if not a duplicate) exists: #3114.

**Comment by onno74** [comment]
> A similar issue (if not a duplicate) exists: #3114.

Certainly not a duplicate.

#3114 asks to show all commits that are in a branch from a selected set of branches. (Currently you can only select one branch or all branches.)
#3165 asks to show all commits that are in a selected branch but not in a branch from a selected set of hidden branches

Unlike #3114, #3165 enables you to hide some commits even if they are part of the current branch.

**Comment by RussKie** [comment]
You're welcome to propose a solution followed by a PR.

**Comment by h0lg** [comment]
> Unlike #3114, #3165 enables you to hide some commits even if they are part of the current branch.

I can't think of a scenario in which I'd need that much control. Can you? I'd prefer selecting branches from the left branch tree panel as suggested in https://github.com/gitextensions/gitextensions/issues/3114#issuecomment-503377888 https://github.com/gitextensions/gitextensions/issues/3114#issuecomment-503317476 because that's less scrolling https://github.com/gitextensions/gitextensions/discussions/9495#discussioncomment-1606019

**Comment by onno74** [comment]
> I can't think of a scenario in which I'd need that much control. Can you?

Yes, of course ;-)

More precisely, our products' repositories contain 5-10 library repositories. We have added each of them by git subtree. (The more common submodules suck.)

From time to time we merge the libraries subtrees into the product master. Even if we add the --squash option to "git subtree merge", the branch that belongs to the library repository gets merged into the master with a merge commit, making the library subtree part of the master history. 5-10 of these libraries bloat the history.

As a workaround, after each subtree merge, we permanently cut off the library branches by rewriting history with git filter-branch. However, this is cumbersome and error-prone.

**Comment by RussKie** [comment]
It is possible today to only show selected branches. Perhaps it is not as obvious or as fluent as it could have been, but it is relatively straight forward - use the Advanced filter.

Here's a screenshot from the dev build (in v3.x it is not as refined) - I'm filtering only to three branches: "msi", "test" and "fix_nre":
![image](https://user-images.githubusercontent.com/4403806/140912144-c8c20eb2-a3e7-4c3b-8222-2802ade48110.png)
It is worth noting that the dev version has a bug where the toolbar branch filter combo isn't updated with the filter, but it would have the same filter value as well.

**Comment by RussKie** [comment]
With regards to hiding selected branches - it depends on two things:
1. Does git support a negative filter?
2. Is it a common enough scenario that warrant the work and added complexity in the app? 

Given that most of users refuse to opt in to the telemetry, we don't have enough data to make data-driven decisions, and I generally have to make a call based purely on technical merits - i.e. if the code looks too complex there's a chance we won't accept it because the team will have accept responsibility and maintain it.

**Comment by onno74** [comment]
1. Does that mean that GitExtensions relies on git for existing filtering operations?
2. Well, after I submitted the feature request, we have set up the workaround with filter-branch. Today, five years later, we have learned to live with the workaround. I still think that the feature would be very useful for anyone who starts using git-subtree, but as we have the workaround, it would be hardly useful for us.

**Comment by gerhardol** [comment]
> 1. Does that mean that GitExtensions relies on git for existing filtering operations?

yes

**Comment by h0lg** [comment]
> 1. Does git support a negative filter?

Isn't a "negative filter" just "all except selected"? I.e. If you had a branch selection - no matter where - couldn't you 1) select all and the 2) de-select the ones to hide

**Comment by h0lg** [comment]
> We have added each of them by git subtree.

@onno74 Woah, sounds complicated and I'm pretty sure I don't fully understand your scenario - especially not why it requires hiding selected commits - which was what I meant when saying I don't need that much control.

**Comment by RussKie** [comment]
> > 1. Does git support a negative filter?
> 
> Isn't a "negative filter" just "all except selected"? I.e. If you had a branch selection - no matter where - couldn't you 1) select all and the 2) de-select the ones to hide

We dont hide anything in the graph manually, we run git commands and display output.

**Comment by h0lg** [comment]
> > > 1. Does git support a negative filter?
> > 
> > 
> > Isn't a "negative filter" just "all except selected"? I.e. If you had a branch selection - no matter where - couldn't you 1) select all and the 2) de-select the ones to hide
> 
> We dont hide anything in the graph manually, we run git commands and display output.

@RussKie I don't understand the issue. Let me explain what I mean using an example:

Given branches b1, b2, ... b10
And I select to hide b2 and b3 (by de-selecting them from the branches to show)
I would like Git Extensions to display b1, b4, ... b10

I.e. a "negative filter" can be translated into a "positive filter" by constructing the difference to the collection of all branches.
Is that not possible?

**Comment by gerhardol** [comment]
You can use --not in the query
https://git-scm.com/docs/git-log#Documentation/git-log.txt---not

**Comment by RussKie** [comment]
If a user has dozens or hundreds of branches with reasonable lengths
creating a positive filter can result in excessively long command.

**Comment by h0lg** [comment]
> You can use --not in the query
> https://git-scm.com/docs/git-log#Documentation/git-log.txt---not

@gerhardol Interesting. In a multi-selection scenario, that would translate into either

- selecting branches into an `Included` and `Excluded` list or
- tracking a more complex selection state that `Selected | Deselected` for each branch, i.e. something like `Included | Excluded | Ignored`

But the respective filter interfaces would probably have to be able to handle exclusions. I'm not sure they can?

**Comment by h0lg** [comment]
> If a user has dozens or hundreds of branches with reasonable lengths creating a positive filter can result in excessively long command.

@RussKie That's true. I'm just not convinced that filtering for hundreds of branches is a valid use case. I can't think of a scenario in which I'd want that.

**Comment by RussKie** [comment]
> I'm just not convinced that filtering for hundreds of branches is a valid use case. I can't think of a scenario in which I'd want that.

Being a maintainer of several projects (including Windows Forms SDK) I've witnessed various ways users find to abuse seemingly innocent functionality 😃. So if we want to further advance this feature I'd try to minimise ways to abuse it.

**Comment by crossan007** [comment]
You can also use `--exclude` in the "Branches" text box:  https://strdr4605.com/git-hide-specific-branch-when-doing-git-log-all

**Comment by gerhardol** [comment]
With 4.0 you can add this to the filter combo box, that has history, see #10239

**Comment by ajilani** [comment]
> The "Branches:" filter in Git Extensions is very powerful. Everything you enter there goes directly to the git log command line. So, you can enter "master ^subtree" to see all the commits from the master branch excluding commits from the subtree branch.

Is this still possible? I am using Git Extensions 5.0.0.17897, and when I enter "tmp-feature ^tmp-dev" (replacing with branches in my repo), I get an error message:
![image](https://github.com/user-attachments/assets/d729bf23-b125-4b9a-8ec4-27cdca0cc55f)

I am not seeing any way in the current Git Extensions UI to _exclude_ a branch in a filter.

**Comment by gerhardol** [comment]
v5 even have an example added by default:
--exclude=refs/remotes/EXCLUDE_REMOTE_REGEX_PATTERN

e.g.
--exclude=refs/heads/tmp/*

**Comment by ajilani** [comment]
> v5 even have an example added by default: --exclude=refs/remotes/EXCLUDE_REMOTE_REGEX_PATTERN
> 
> e.g. --exclude=refs/heads/tmp/*

Oh neat; where does one find this example and the documentation for it? Unfortunately I've not been able to get it to work.

These all result in no commits being shown:

- --exclude=refs/heads/tmp/*
- --exclude=refs/heads/tmp-dev
- --exclude=tmp-dev

These all show the commits of tmp-feature, including those that are in tmp-dev:

- tmp-feature --exclude=refs/heads/tmp/*
- tmp-feature --exclude=refs/heads/tmp-dev
- tmp-feature --exclude=tmp-dev

What I am trying to do is document a merge commit, and for that I want to see all commits that the merge brought in. So I labelled the first parent tmp-dev and the second parent tmp-feature, and I hoped to see all commits that are in the history of tmp-feature but NOT in tmp-dev. I believe this is what GitHub does in the "Commits" tab of a pull request.

**Comment by gerhardol** [comment]
Some info in the help, no details about the searchbox though
https://git-extensions-documentation.readthedocs.io/en/release-5.0/browse_repository.html#filter-history

If the box start with --, the parameters are added as git-log options, see git doc for details
Something like the following in filter
--exclude=refs/remotes/origin/* --exclude=refs/heads/featuxre/*

**Comment by gerhardol** [comment]
@ajilani You should be able to write the pattern as "tmp-featur[e] ^tmp-de[v] to avoid that the contents is evaluated as a git-ref to avoid Git execution failures for the actual git-log command
