### ISSUE TITLE
Git Extensions install removes right-click Git Bash in Windows

### ISSUE THREAD

**Issue by daveheq** [gitextensions/gitextensions#3169]
When I had Git Bash, I could right-click a folder (or inside an open folder) and get the Git Bash option, but now I have to click Git Browse then Tools then Git Bash.

The problem is on a bigger repo or one where it takes a while to scan, it just adds unnecessary time.

Any way to get this option back or am I missing something?

**Comment by KindDragon** [comment]
If I understand correctly it is Git for Windows feature, just install it and select in installer option that menu

**Comment by daveheq** [comment]
Thanks, that did bring back the right-click options, but seems to have destroyed Git GUI, which I used in my Git Extensions > Tools menu (which is now grayed out, and the Windows 7 taskbar pinned shortcut is dead). I had msysgit be what Git Extensions used, and now it appears to be uninstalled. No way to have all three?

**Comment by daveheq** [comment]
OK I installed Git for Windows and the right-click options came back, but the shell doesn't recognize backlashes in pathnames, even if they're copied and pasted from Windows Explorer. Why? It's Git for Windows.

**Comment by KindDragon** [comment]
You can ask about that there https://gitter.im/git-for-windows/git?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge or on @dscho issue tracker https://github.com/git-for-windows/git

**Comment by dscho** [comment]
Correction: This is not *my* issue tracker.

**Comment by KindDragon** [comment]
:smile:

**Comment by JAP22** [comment]
Reinstall, when installing once more select the option "Use Git From git bash only" and do not tick the "use Git from the windows command prompt", it worked for me.
