### ISSUE TITLE
Try different colors for ConEmu

### ISSUE THREAD

**Issue by karyon** [gitextensions/gitextensions#3171]
Right now, the colors of ConEmu look out of place in my opinion. @hypersw said he might try inverting the luminance.

**Comment by hypersw** [comment]
What I want is to remap colors so that the hue were kept but the luminance went the other way, with the former black being white, bright green (= contrasted) getting dark green, former dark green (= lower contrast) getting pale green, and so on.

@Maximus5: could you recommend any of the standard schemes for that? There're very few for light-color GUI, and of them only `<Tomorrow>` looks unstylized and general-purpose. Does its idea agree to what I want? Or should I want something else? :)

**Comment by Maximus5** [comment]
[`<ConEmu>` default scheme](https://conemu.github.io/en/SolarizedColors.html) has slightly modified [Solarized colors](http://ethanschoonover.com/solarized). Solarized was developer in two variants: Light and Dark. And there is a `<Solarized Light>` in ConEmu which I'm using personally for some Tasks. But `<ConEmu>` scheme is my favourite at the moment.

All others are too acid for my eyes.

**Comment by hypersw** [comment]
Solarized is nice for `git` and general cmdline, but FAR looks queer in it to my eye, as if in fog. So the default scheme is used in conemu-inside and gitext, but for FAR I'd use the stock OS colors.
Solarized-light is nice, but it's yellowish and I'm afraid won't solve the original issue — for it to match the overall GUI theme of the default Windows application. I'll give it a try.

**Comment by Maximus5** [comment]
I believe that oversaturated schemes (as `<Default Windows scheme>`) are not good. But they exists in ConEmu's defaults because users may prefer them.

**Comment by forbjok** [comment]
To me, it's mostly the fact that the scroll bar looks like part of the dialog while the status bar with mismatching colors continues below it that makes it look off.
I think adding a 1 pixel black border around the embedded ConEmu control to more clearly separate it from the rest of the dialog looks better.

Quick example:
![conemu-border](https://cloud.githubusercontent.com/assets/4687674/15208945/ae5f59e2-182e-11e6-9b08-021e416b5b51.png)

**Comment by KindDragon** [comment]
Depend on https://github.com/Maximus5/conemu-inside/issues/17

**Comment by vbjay** [comment]
Looks like we need to allow for the user to choose what they want.

**Comment by KindDragon** [comment]
We can't ATM. Moved this to next milestone

**Comment by vbjay** [comment]
I figured.

**Comment by Maximus5** [comment]
I'm not quite sure, what blocks you from giving users ability to select palettes? ConEmu has a lot of predefined palettes, which may be selected via -new_console switch.

**Comment by KindDragon** [comment]
I can't find how to pass command line parameters to ConEmu.exe through ConEmu.WinForms control

**Comment by Maximus5** [comment]
Append it to sConsoleProcessCommandLine.

**Comment by KindDragon** [comment]
@Maximus5 It possible to hide status bar?

**Comment by KindDragon** [comment]
Theme changed in commit 57dc6ee

**Comment by Maximus5** [comment]
> It possible to hide status bar?

@KindDragon Perhaps this is a feature request for conemu-inside. You may hide StatusBar in ConEmu.xml but I'm not sure if it's possible with current control.

**Comment by KindDragon** [comment]
Ok, thank you. Can I set my ConEmu.xml using a command line?

**Comment by hypersw** [comment]
@KindDragon: hiding the Status Bar is in the ConEmuInside API, but I liked it more this way with the Status Bar visible, for one thing, it shows the currently running process which changes for `git` even if there is no output and lets you know it's not dead. Some psychological thing.

**Comment by KindDragon** [comment]
With new color scheme status bar very dark. I don't know how to change it.

**Comment by hypersw** [comment]
Wellll I must admit it's not that useful. Could just hide it.

**Comment by vbjay** [comment]
We just need a conemu settings section somewhere. We can keep adding
customizations to it. Show taskbar, theme, ...  Why don't we set up a
template conemu settings page and just let people pull request the
customizations they want. No two developers are going to be happy with the
console. Start with a good generic theme.  Could even have a gear icon on
the console control that takes you to the settings page.

**Comment by vbjay** [comment]
If we really wanted to get snazzy, we could have a conemu theme builder
that lets us design the custom theme values.
