### ISSUE TITLE
Commit selection history:  Ability to navigate to previous/next selection

### ISSUE THREAD

**Issue by johnddx** [gitextensions/gitextensions#3180]
If I use "goto commit..." and put in any arbitrary commit hash, it can warp me to a distant time.  It would be great if I could "Alt+<Left>" to go back to the commit I was previously looking at, and then "Alt+<Right>" to return to the commit I had jumped to again, much as with web browser history.

**Comment by RussKie** [comment]
This functionality is available `alt + <-` (forward) and `alt + ->` (backwards).
However it could be made more obvious
