### ISSUE TITLE
Invalid Character in FormBrowse.Designer.cs

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#3185]
In the current master branch, there's an invisible char in `this.menuitemSparse.Text = "Sparse Working Copy";`, which causes a build failure.

**Comment by hypersw** [comment]
Originally, that were an ellipsis.
Wonder at what point it has gotten spoilt.
![untitled20160422015722](https://cloud.githubusercontent.com/assets/2332070/14726795/fe00bc88-0835-11e6-9f46-24da97cc2266.png)
