### ISSUE TITLE
when merge ms-office-word file,it opened two local version.

### ISSUE THREAD

**Issue by ovjust** [gitextensions/gitextensions#3192]
when I try to solve word file conflict and I choose "use merge-word.js script",ms-word-soft shows it merging two local version files. It should be merging local and remote version.
gitextensions version：2.85
ms-office version:2007.
the remote version:
![image](https://cloud.githubusercontent.com/assets/12697538/15009106/27ee778e-1217-11e6-9bb2-762fd109af85.png)
the local version:
![image](https://cloud.githubusercontent.com/assets/12697538/15009142/525c5ad6-1217-11e6-9471-67e06c99057a.png)

the error:
![image](https://cloud.githubusercontent.com/assets/12697538/15009082/02e058cc-1217-11e6-8f8a-355b9d47f102.png)

**Comment by vbjay** [comment]
A merge has three files.

Base:Common base commit between the two commits being merged.
Local and remote: the two commits being merged.

**Comment by jbialobr** [comment]
Probably fixed in https://github.com/gitextensions/gitextensions/commit/0d1eb4cebb31526ee6f2321056eb4356e3ce1fe1
