### ISSUE TITLE
How can i search the tags

### ISSUE THREAD

**Issue by elait** [gitextensions/gitextensions#3194]
a few days ago,i create a tag named myProject,now,I want to reset it,how can i search myProject on gitextensions?

**Comment by vbjay** [comment]
Use navigate menu.

**Comment by KindDragon** [comment]
Navigate > Go to commit and select there tag

**Comment by elait** [comment]
Thank you.

**Comment by CoolMind** [comment]
@KindDragon, thanks!

In recent versions tags have been hidden. Show them with View > Show tags.
