### ISSUE TITLE
In case of .git/index.lock problem during staging error message is empty

### ISSUE THREAD

**Issue by Nochdarus** [gitextensions/gitextensions#3204]
![image](https://cloud.githubusercontent.com/assets/16781381/15269866/dd71c69a-1a0c-11e6-929b-ea86409b0e9d.png)

Debugging showed that in GitModuel.cs ExitCode of git process was 128 in here:
```
            if (processReader.IsValueCreated)
            {
                processReader.Value.Process.StandardInput.Close();
                processReader.Value.WaitForExit();
                output = output.Combine(Environment.NewLine, processReader.Value.OutputString(SystemEncoding));
                error = error.Combine(Environment.NewLine, processReader.Value.ErrorString(SystemEncoding));
                wereErrors = wereErrors || processReader.Value.Process.ExitCode != 0;
            }
```

Variable "error" had the message about gitlock.

We need at least to forward this message to "Stage Details" pop-up window.

**Comment by KindDragon** [comment]
We have bug about empty "Stage Details" window.

**Comment by Nochdarus** [comment]
I looked through open issues using key word "stage". Couldn't find it quickly.

 Could you please provide a link to that bug? Then I'll name my branch for that fix accordingly.

**Comment by KindDragon** [comment]
Bug #3189, I think it appear after ConEmu PR merge

**Comment by Nochdarus** [comment]
Duplicate of https://github.com/gitextensions/gitextensions/issues/3189 as @KindDragon  mentioned.
Thus closing.
