### ISSUE TITLE
Plans for more regular releases?

### ISSUE THREAD

**Issue by peppy** [gitextensions/gitextensions#3205]
I've noticed there are milestones for 2.49 and "next version" but these still seem quite far away. It's been a year with no new release; any plans for one any time soon?

I've been building from source but it would be quite handy to have a newer version officially released! It would even be a step forward if you started teamcity generating artifacts for each of its builds and offering them as nightly test releases or similar.

**Comment by MpDzik** [comment]
+1 I've been waiting quite long for version 2.49 and also decided to build the latest source code on my own. However, it would be a lot easier to grab the latest nightly build from the build server. This would probably have the addition benefit of more testers and therefore more bugs discovered before the stable release.

**Comment by hypersw** [comment]
I've updated the installer build code so that it could make an MSI on a machine which does not have WiX installed, by using it from a nuget, so the TC build could be updated with it.

**Comment by KindDragon** [comment]
> I've noticed there are milestones for 2.49 and "next version" but these still seem quite far away. It's been a year with no new release; any plans for one any time soon?

We have [gitter](https://gitter.im/gitextensions/gitextensions) chat for such questions.
When we fix these bugs https://github.com/gitextensions/gitextensions/milestones/2.49
