### ISSUE TITLE
Change or Uninstall results in Error Code 2330

### ISSUE THREAD

**Issue by thedigitalman** [gitextensions/gitextensions#3206]
I cannot Change or Uninstall Git Extensions (v2.48.05). I get a dialog that states, "The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2330."

I also get a similar message when trying to uninstall from the Control Panel.

OS: Windows 7 Enterprise SP 1

**Comment by vbjay** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/aa372835(v=vs.85).aspx

**Comment by markzama** [comment]
I have the exact same problem. Can someone please post a solution so I can upgrade to 2.49?
OS: Windows 7 Enterprise, SP1

**Comment by KindDragon** [comment]
IDK, try install 2.48.05 again and then remove it

**Comment by markzama** [comment]
Thanks for the idea. I tried various installer options: change, repair, and remove.
For Repair, it complained it could not create 
...\<myusername>$\cached\my documents\Visual Studio 2010\Addins
plus other Addins directories for many other VS versions.
I took my computer off the network and manually created the Addins folder and en-US 
folder until I got a "good" repair with no error code.
Then I tried to Remove and it failed with same error code as before.
Is there a manual method to uninstall?

**Comment by vbjay** [comment]
Last resort is to use msizap.

**Comment by mageos** [comment]
I was able to work around the issue by looking at the log file:

msiexec /i GitExtensions-2.51.05.msi /lv* gitextension.install.log

And creating the Addins and Addins\en-US folders under Documents\Visual Studio 2013\ and putting empty files in them to keep the installer from installing to them.  I also skipped installing those extensions during the upgrade.

**Comment by RussKie** [comment]
Thank you for the heads up.

**Comment by RussKie** [comment]
Given this concerns old versions of GE, I'm going to close it.

**Comment by slodge** [comment]
I'm encountering this issue currently while trying to upgrade a 2.x install to a 3.x install.

The installer is failing with 2330. When I run with msiexec and check the logs it's because there's a problem removing the "Error 4350 attempting to delete file GitPlugin.AddIn" in "Documents\Visual Studio 2012\Addins\" - that file doesn't exist.

I can't get uninstall to run on the old version... and I can't get install to work on the new version....

Is the only workaround still to create empty Addins files so that the installer deletes them?

(Sorry for asking on a closed issue - but this seemed the best place...)

**Comment by gerhardol** [comment]
> Is the only workaround still to create empty Addins files so that the installer deletes them?

From the info in this thread, yes

**Comment by safik222** [comment]
I solved this problem on Windows 10 by download this Microsoft Troubleshooter.  :-)
https://support.microsoft.com/cs-cz/help/17588/windows-fix-problems-that-block-programs-being-installed-or-removed

**Comment by RussKie** [comment]
Thank you for sharing
