### ISSUE TITLE
Checkout branch dialog

### ISSUE THREAD

**Issue by Norrehnen** [gitextensions/gitextensions#3207]
Hi,
The drop down box in the _Checkout branch_ dialog is too narrow. A branch name like:
`origin/feature/16.3/epic/messagehandler/asa/eg-7889`
is not displayed entirely. You only see:
`origin/feature/16.3/epic/messagehandler`
which is really annoying.

**Comment by DanielTheCoder** [comment]
I've the same problem in the project I'm currently working on.
Have already an idea how this can be fixed, will have a look at it in the afternoon.

**Comment by Norrehnen** [comment]
Great, I am looking forward to seeing the result :)

**Comment by DanielTheCoder** [comment]
I've updated the PR with some screenshots ...

**Comment by jbialobr** [comment]
Fixed in #3207.
