### ISSUE TITLE
Improve UI in 'merge branches' 

### ISSUE THREAD

**Issue by miparnisari** [gitextensions/gitextensions#3208]
When you go to **Commands > Merge branches** and see this:

![merge](https://cloud.githubusercontent.com/assets/5374887/15757402/c546b64c-28db-11e6-8b0e-28f71639a75a.png)

I'm always confused as to what the end result will be. 

I think it would be clearer to show something like

```
Merge branch [master]

into currrent branch [origin/ux-redesign]
```

**Comment by vbjay** [comment]
There is a help ui on the left.

**Comment by miparnisari** [comment]
Why should I have to click the help button if we can make it clear in the UI? I never click on help buttons.

**Comment by miparnisari** [comment]
I never look at that :stuck_out_tongue:

**Comment by hypersw** [comment]
@vbjay: the help UI is a bit schizophrenic, sorry :) does not make things simpler as it should.
@miparnisari: I think replacing `Merge with` with `Merge from` would totally do the thing, wouldn't it?

**Comment by vbjay** [comment]
@hypersw LOL!  

Take the changes in the selected branch and put them in the current branch.  Notice the into current branch label.  So in this case spreadsheet commits would go into dev.  
![image](https://cloud.githubusercontent.com/assets/3629489/15762990/e72388cc-28ee-11e6-9137-807c1e1bc3c2.png)

**Comment by miparnisari** [comment]
@hypersw no, I don't think so. Actually that would make it more unclear. I never heard of the phrase "merge from".

Think about the way I propose. It reads like a sentence.

![mockup](https://cloud.githubusercontent.com/assets/5374887/15767486/c7110e44-291e-11e6-93f5-0351ce6380ce.png)

**Comment by ghanique** [comment]
I'm never confused about what will happen because I know what branch is
currently checked out and as soon as I right click the branch I want to
merge it into, I know what will happen and I pretty much ignore the Merge
screen (with the exception of the "Always create a commit checkbox").
That said: simply rewording and reordering the merge window would indeed
clarify things. I like the sketch.
(Personally the pictures on the left of the current Merge window never were
that helpful and neither are the ones on the Rebase window).

**Comment by jeffqc** [comment]
I support this change. Merge X into Y is way more clear than "Current branch: Y, merge with X"

**Comment by orao** [comment]
@ghanique 
> ... and as soon as I right click the branch I want to **merge it into**...

I believe you mean _"merge from"_

**Comment by jbialobr** [comment]
@miparnisari I agree, 'merge into' better describes the direction of the merge.

**Comment by phillijw** [comment]
Another vote. It's easy but a huge improvement

**Comment by spencercrissman** [comment]
Took a stab at this.

#3349
