### ISSUE TITLE
Always missing tracking reference when pushing from an additional worktree

### ISSUE THREAD

**Issue by Jofreeze** [gitextensions/gitextensions#3212]
Hi,
I tried to use the worktrees (git add worktree), but every time I want to push from a worktree, GitExtensions asks me that:

> Push
> The branch mybranch does not have a tracking reference. Do you want to add a tracking reference to mybranch?
> Yes   No   Cancel   

If I answer "Yes", the next time I push, it asks me again the same question.

After investigation, it seems to read the wrong config file.

Git repository:
C:_repos\master\
C:_repos\master\.git\

Git worktree, created with:

```
C:\_repos\master>git worktree add -b mybranch ..\mybranch origin/mybranch
```

C:_repos\mybranch\
C:_repos\mybranch\.git -> file containing "gitdir: C:/_repos/master/.git/worktrees/mybranch"

It seems GitExtensions reads inexistant
C:_repos\master\.git\worktrees\mybranch\config
instead of
C:_repos\master\.git\config
when checking the tracking reference.
When pulling or pushing (after answering Yes), I think it reads the good one because it doesn't fail.

**Comment by jjcole** [comment]
I'm getting this too, it definitely seems like there's is not full support for worktrees yet. Another minor example is that the "Refresh" button always shows the "!" symbol as if there is changes, and doesn't go away after refreshing.
