### ISSUE TITLE
Add possibility to "mark" files in diffs

### ISSUE THREAD

**Issue by drauch** [gitextensions/gitextensions#3213]
We use branch diffing in GitExtensions during our code reviews. It would be a nice feature to add a checkbox to the file list of the diff where you can mark all files which you've already reviewed.

**Comment by ghanique** [comment]
-1

I think it would make the ui more complicated than it needs to be. Wouldn't everyone wonder what the check boxes are for? And then it turns out it serves no purpose whatsoever besides a visual indication of what your did or did not review.

Imho if you need check boxes to review there is too much in the commit you're reviewing. It would make more sense to look at the different commits in a branch than to look at the difference between branches. If there are that many differences that you need check boxes you probably wouldn't see the wood for the trees anyway.

**Comment by drauch** [comment]
I'm not reviewing a single commit (also I could use the staging area for pushing things into a commit peace by peace).

I'm comparing whole branches before merging them, most pull-request tools support this kind of "has been reviewed"-checkbox (e.g., Atlassian BitBucket Server).

**Comment by vbjay** [comment]
Use the right tool for the job.  https://www.gerritcodereview.com/

**Comment by drauch** [comment]
Gerrit & Co (also Atlassian BitBucket Server) are great for asynchronous reviewing. They're not so great for pair programming reviews.

**Comment by sharwell** [comment]
Conceptually I'm not opposed to having code review functionality in the project. However, I am opposed to pretending we have code review functionality by adding a dummy checkbox to a user interface that already confounds new users (more Git's fault than this project, but it still dominates the experience for many users).

:memo: I find that the staging area UI can be a great place for exactly this type of review without any changes needed to the current UI. "Checked" items are the staged code, and "Unchecked" items are unstaged code.

**Comment by drauch** [comment]
@sharwell : Yep, for single commits the staging area is perfect. When diffing branches, there is no similar concept unfortunately :-)

**Comment by sharwell** [comment]
@drauch 

> When diffing branches, there is no similar concept unfortunately :-)

If you are planning to merge branch A &rarr; B and want to review it first:

1. Make sure your working copy is clean
1. Perform the merge but do not commit
1. Move all staged files out of the staging area
1. Move items back into the staging area as they are reviewed

If you are not planning to merge branch A &rarr; B, but want to review them:

1. Make sure your working copy is clean
1. Create a new temporary branch at A
1. Do a mixed reset to B
1. Move files into the staging area as you complete your review
