### ISSUE TITLE
No public release in the latest year

### ISSUE THREAD

**Issue by FallenGameR** [gitextensions/gitextensions#3214]
I see that there are tons of commits and pull requests in the repository, but the latest release is dated May 2015. How come?

Btw, tried to build from sources - studio complains about missing namespaces on freshly cloned repository.

**Comment by djryan** [comment]
👍 for this

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/wiki/Build-Instructions

**Comment by FallenGameR** [comment]
Thanks, I've managed to build =)
Still, no recent release...

**Comment by Xhanti** [comment]
+1

**Comment by Briksins** [comment]
Hello

The latest Release is v2.48.05 dated to May 29, 2015
Since that time were:
* Opened: 404 Issues
* Closed: 214
* Still Open: 190

I'm wondering if you could organise new release which will not be outdated for a year+

**Comment by KindDragon** [comment]
We will appreciate any help with bugs https://github.com/gitextensions/gitextensions/milestones/2.49

**Comment by pmiossec** [comment]
>We will appreciate any help with bugs

I hope that with the bunch of fixes I made, we will be able to release one soon ;)

**Comment by FallenGameR** [comment]
Yay!

Could you please include this PR into the release? https://github.com/gitextensions/gitextensions/pull/3250 I've released private build of GitExtensions with this patch internally, but official version would be better =)

**Comment by jbialobr** [comment]
@pmiossec Great job! Only 12 issues left.

**Comment by jeffqc** [comment]
2.49 is out, I think we can close this issue!
