### ISSUE TITLE
Checkout branch and reset local changes warning

### ISSUE THREAD

**Issue by jonathancloudshare** [gitextensions/gitextensions#3217]
--- GitExtensions2.48.05, Git 2.5.1.windows.1, Microsoft Windows NT 6.3.9600.0

Action:
Checking out a branch and choosing the "reset" option to local changes.

Expected:
A warning telling the user he might lose work.

Actual:
The checkout resets local changes without warning.

Note:
The thing is, when selecting the "reset" option for local changes, the user might be aware of what he is doing. But that choice sticks for the next time the user might checkout a branch, and then the user might not notice that option is selected.

**Comment by vbjay** [comment]
If reset is the chosen value, it should not remember it.  The process
should make them HAVE to click reset.

**Comment by EbenZhang** [comment]
You may want to vote for #2927 which added a checkbox to remember the choice.

**Comment by vbjay** [comment]
That is one thing.  Great that it is there.  However, reset should NEVER be
remembered.
