### ISSUE TITLE
There is no way to get to favorite repositories, other than start page.

### ISSUE THREAD

**Issue by sadastronaut** [gitextensions/gitextensions#3220]
I think it would be very helpful to have favorite (or favourite) repositories accessible from somewhere other than the main page. In my work flow, I usually keep Git Extensions GUI open for a long time, and I frequently switch between various repositories. 
--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by berrs** [comment]
What about Start menu -> Recent repositories? Does that help you?

**Comment by sadastronaut** [comment]
That does help some, and it's something I've been using quite a bit, but I also like the idea of the favorites, as there are about 3 or 4 repositories I switch between quite often.
