### ISSUE TITLE
Checkout dialog proposes completely random local branch names

### ISSUE THREAD

**Issue by Amelek** [gitextensions/gitextensions#3227]
Version 2.48.05, Windows 7 x64, git version 2.9.0.windows.1

I had updated git extensions recently, from unknown ancient version, and the new build suffers from extremely annoying issue, as seen in the picture:

![gitexts](https://cloud.githubusercontent.com/assets/5755692/16373301/d65438e0-3c51-11e6-9fd2-ed5778f830c3.png)

When attempting to checkout remote branch, very commonly another completely random local branch will be assigned. I can't really tell what's the root cause :( I even have a repository when checking out "origin/prerelease" proposes to create "yprerelease" branch (!!) even if local prerelease branch is deleted. What is this about?

**Comment by Amelek** [comment]
For now, I had downgraded to 2.47.3 which does not suffer from this issue

**Comment by Amelek** [comment]
Ok, I had found the root issue. It is due to remote branch tracking fix introduced in the 2.48: "Checkout remote branch dialog try find tracking branch first". It seem that I have multiple tracking references for the broken branches, In fact, in one repo, I have 8 references for the broken "origin/prerelease" branch.

Would it be possible to change the checkout branch so that it's possible to choose which tracking reference should be used? Or maybe some kind of tracking reference editor could be introduced so that bogus entries could be removed?

**Comment by vbjay** [comment]
![image](https://cloud.githubusercontent.com/assets/3629489/16380733/c382d380-3c46-11e6-99e6-9de9e2adf76a.png)


![image](https://cloud.githubusercontent.com/assets/3629489/16380759/eab15e18-3c46-11e6-9cfb-c45c24158fd9.png)

**Comment by Amelek** [comment]
That's not quite what issue is about. The problem is that I (used to) have wrong entries in the config file of git repository. I literally had:

```
[branch "split_detection"]
	remote = origin
	merge = refs/heads/master
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

As far as I can tell, this happens when you rename the local branch (I likely did it due to some obscure conflict resolution) and re-create it from remote. In old git extensions, it would create a new local branch, thus duplicating the remote tracking reference.

I had nuked all bogus references from my repository configurations manually, now everything works properly.

Default gui behavior can be confusing. Maybe if there exists a remote tracking reference, gui should contain "Reset local branch with the name: (tracking reference name)" and something like "Discard tracking reference and reset local branch with name: (autogenerated name)"

**Comment by vbjay** [comment]
Well one quick way is to delete the remotes and re add them and do a 
```
git remote update 
```

**Comment by Amelek** [comment]
I guess it also works, as heavyweight as it may be
