### ISSUE TITLE
In diff view, enabling "ignore whitespace" causes lines to be colored as moves instead of adds or deletes

### ISSUE THREAD

**Issue by johnddx** [gitextensions/gitextensions#3229]
Look at a diff.

If "Ignore Whitespace" is disabled, a deleted line might show as light-red over the whitespace and dark-red for the rest of the line.  This would occur because the whitespace part matches another line in the file, so it winds up looking like only a partial delete.

When "Ignore Whitespace" is enabled, the same line described above will show as light-red, as if it was a move rather than a delete.  **These lines should show up 100% dark red,** to indicate the line was deleted.

Lines where the detected moved code includes non-whitespace are still colored correctly, with the light-red connoting a move and dark-red indicating full deletion.

**Comment by jbialobr** [comment]
Please, provide a screenshot.
