### ISSUE TITLE
Status of Project?

### ISSUE THREAD

**Issue by jsheely** [gitextensions/gitextensions#3230]
There has been a health set of commits but no release has been created since early last year. Is there a projected timeline when a bundled release will be made? Or should we just clone and build from source from now on?

Thank you and still my favorite Git GUI tool.

**Comment by Radrik5** [comment]
See these issues: https://github.com/gitextensions/gitextensions/issues/3205 https://github.com/gitextensions/gitextensions/issues/3214.

**Comment by jsheely** [comment]
Great. Thanks
