### ISSUE TITLE
DiffViewerLineNumberCtrl throws concurrent modification exception

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#3255]
The exception is thrown at this line https://github.com/gitextensions/gitextensions/blob/191b04ef9929cc229eb2cbe8b15e679d871c5966/GitUI/Editor/Diff/DiffViewerLineNumberCtrl.cs#L28

I think that `DiffLines` shouldn't be accessed before `_diffLineNumAnalyzer` finishes its job.

**Comment by jbialobr** [comment]
I would make 'DiffLines' immutable. `_diffLineNumAnalyzer ` should have its own list of difflines and when completed it should pass it to the DiffViewerLineNumberCtrl there is no need to pass line by line.

**Comment by EbenZhang** [comment]
> when completed it should pass it to the DiffViewerLineNumberCtrl there is no need to pass line by line.

I don't want the ui thread to update too many lines in one go which reduces the responsiveness especically for large files.

I will change the `Dictionary` to `ConcurrentDictionary` and will do more testing before creating a pull request.

**Comment by jbialobr** [comment]
You can create a dictionary in the background thread, fill it in the background thread and when all lines are procesed pass the filled up dictionary to main thread.

**Comment by jbialobr** [comment]
I would use the [AsyncLoader](https://github.com/gitextensions/gitextensions/blob/414923876075214c80846bd8514661d169bacc44/GitCommands/AsyncLoader.cs) class. It is used widely in GitExt. For example in [SearchWindow](https://github.com/gitextensions/gitextensions/blob/b512d3b235b6f84f8bfcd3efd0f111e2d1c1c8ba/GitUI/CommandsDialogs/SearchWindow.cs#L93)

**Comment by EbenZhang** [comment]
You will be waiting longer to see the file numbers if post the result at the end. Usually the diff just contains small hunks of code, but be aware there is also an option to show the whole file.

**Comment by vbjay** [comment]
You can use invoke to update the gui when needed.

**Comment by EbenZhang** [comment]
@vbjay we are talking more about when not how to update the ui

**Comment by jbialobr** [comment]
After https://github.com/gitextensions/gitextensions/commit/3892f8d5b0ba3516b0bed3468d67ce4143a8ac3d there is no noticeable delay in displaying line numbers (even when displaying on the completion). I would even consider moving it to the main thread or to the PatchProcessor.CreatePatchFromString.

**Comment by jbialobr** [comment]
The concurrent modification exception doesn't appear anymore after replacing DiffLines.Any() by DiffLines.Count > 0.
