### ISSUE TITLE
Discuss ergonomic concern on 'Fixup' and 'Squash' commit feature

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#3256]
A workmate had a problem with using for the first time this feature. And because he don't understand how git works and what it did under the hood was never able to use it conveniently :(

I think we could help a little more the users. Don't you think that if we change:
- "Fixup commit" to "Create a fixup commit"
- "Squash commit" to "Create a squash commit"
it is more helpfull and more clear on the intention to create a specific commit (and not to modify the one selected!) ?

I think that's a change we could to improve things and let this feature more ergonomic and self discoverable without using the documentation (because anyway, users never read it, myself included ;)) ... even if in this special case, a doc is needed! (I could do it too ;) )

What do you think?

If you're ok, I will do the PR.

**Comment by jbialobr** [comment]
You are right, the current names are very misleading. Your PR will be very welcome.
