### ISSUE TITLE
ConEmu windows asks me if I want to allow this program to make changes on my computer

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#3263]
After I press `Allow` then I get the following error:
```
"C:\Program Files (x86)\Git\bin\git.exe" push --recurse-submodules=on-demand --progress "origin" refs/heads/master:refs/heads/master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Done

Press Enter or Esc to close console...
```

When I close the dialog and press push again it pushes with no error.
My OS is win8.

The problem does not exist when I turn off the conemu in the settings.

**Comment by jbialobr** [comment]
@Maximus5 any hint on this?

**Comment by Maximus5** [comment]
Without exact text of the UAC query I can't say anything. The issue even hasn't described what user starts.

There are too many possibilities: user starts elevated tab, or the command calls smth which requires elevation, or some app/tool was configured, by OS or user, to be executed in compatible mode, or....

**Comment by hypersw** [comment]
Check `Zone.Identifier` Alternate Data Stream on all the exe/dll files in gitext?

**Comment by jbialobr** [comment]
After I made a clean build I am no longer able to reproduce this issue.

**Comment by jbialobr** [comment]
I got it again. It might be related to running a process as ADMIN.

![2016-07-22 05_47_08-conemu 160310 32](https://cloud.githubusercontent.com/assets/1003909/17046104/2651eec8-4fd0-11e6-848f-f31c63a4f001.png)

![2016-07-22 05_49_13-gitextensions master - git extensions -_ debug _-](https://cloud.githubusercontent.com/assets/1003909/17046106/2c348f8a-4fd0-11e6-9c6b-b2715852cba0.png)

**Comment by jbialobr** [comment]
ConEmu showed me a dialog to rerun the command and I unchecked Run as Admin checkbox. The push command completed successfully then. @hypersw Why is the `/ADMIN' switch needed there?

**Comment by jbialobr** [comment]
@Maximus5 Why there is used the /ADMIN switch? I can't find anything saying to use such a switch when [creating a conemu control](https://github.com/gitextensions/gitextensions/blob/8f130666f105d25ad9011ff65f46767ea7435306/GitUI/UserControls/ConsoleEmulatorOutputControl.cs#L74)

**Comment by Maximus5** [comment]
The switch `/ADMIN` is just a signal to [ConEmuC.exe](https://conemu.github.io/en/ConEmuC.html) which means the console was requested elevation state.

I have no idea why it's there because I do not know exact command producing the console. Is that GuiMacro? Or it's a `ConEmu.exe -run ...` switch? Anyway, [-new_console:a](https://conemu.github.io/en/NewConsole.html#syntax) is post possible reason for elevation request.

**Comment by jbialobr** [comment]
>Is that GuiMacro?

It is started as a conemu-inside control. Here is how it is created: https://github.com/gitextensions/gitextensions/blob/8f130666f105d25ad9011ff65f46767ea7435306/GitUI/UserControls/ConsoleEmulatorOutputControl.cs#L74

The strange thing is that it does not always ask for permission. But I can not see any pattern.

**Comment by jbialobr** [comment]
@Maximus5 
The [ConEmuSession](https://github.com/Maximus5/conemu-inside/blob/7b315301c060ad71f4c8152960ba2c9c37fb262e/ConEmuWinForms/ConEmuSession.cs#L441) is started with arguments as below:
`-InsideWnd 0x50802 -NoKeyHooks -LoadCfgFile C:\Users\jbial_000\AppData\Local\Temp\ConEmu\2016-08-30T02-15-14.00002834.02145259\Config.Xml -Dir C:\d\projekty\gitextensions\ -AnsiLog C:\Users\jbial_000\AppData\Local\Temp\ConEmu\2016-08-30T02-15-14.00002834.02145259 -cmd -cur_console:c "C:\Program Files (x86)\Git\bin\git.exe" push --recurse-submodules=on-demand --progress "origin" refs/heads/master:refs/heads/master`

and with this [Config.xml](https://github.com/gitextensions/gitextensions/files/443944/Config.txt)

The important thing is that it sometimes asks about the permission and sometimes does not.

**Comment by jbialobr** [comment]
I found where the problem stems from:
I push to a remote repo using the `ctrl+shift+up` shortcut. It occurs that ConEmu seeks for the Shift key being pressed when it runs in `INSIDE` mode and when it finds that the Shift key is pressed it runs as Admin. 
https://github.com/Maximus5/ConEmu/blob/9b4a1252236a383bd2d31c6187a55c685dc02596/src/ConEmu/ConEmuStart.cpp#L1101

/cc @Maximus5 @hypersw

**Comment by jbialobr** [comment]
When I am logged in as Admin on my PC and pushing with ctrl+shift+up I get the following error:
```
"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=on-demand --progress "origin" refs/heads/master:refs/heads/master
fatal: Not a git repository (or any of the parent directories): .git
Done

Press Enter or Esc to close console...
```

**Comment by Wirone** [comment]
@jbialobr How can I configure GitExtensions to use ConEmu? I didn't know it's possible :-)

**Comment by Maximus5** [comment]
@jbialobr Unfortunately, git doesn't print full path on error, but on the moment of error (Press Enter or Esc to close console...) you may run ProcessExplorer, search for "ConEmuC64.exe" and look into its properties. On the "Environment" tab you may find the variable "ConEmuWorkDir", that's the directory where the command was issued.

Anyway, words "logged in as Admin on my PC" are ambiguous: login=Admin? Elevated account? UAC enabled/disabled? What OS you are using at last?

**Comment by jbialobr** [comment]
@Maximus5 
Here are screenshots for ConEmuC and ConEmu processes, both when run with Shift pressed and without. In both cases the same command is executed.

ConEmuC, shift pressed
![conemucerr](https://cloud.githubusercontent.com/assets/1003909/18121488/0f4222b6-6f65-11e6-9032-f92bddabb12b.png)

ConEmu, shift pressed
![conemuerr](https://cloud.githubusercontent.com/assets/1003909/18121494/15f1a154-6f65-11e6-87e8-cf3fa3a80f8b.png)

ConEmuC, shift not pressed
![conemucok](https://cloud.githubusercontent.com/assets/1003909/18121496/1a0254fa-6f65-11e6-9a65-be70d31bd3e1.png)
ConEmu, shift not pressed
![conemuok](https://cloud.githubusercontent.com/assets/1003909/18121501/1cf75246-6f65-11e6-87a2-7bb2493fa0d3.png)

**Comment by Maximus5** [comment]
Both cases? And what was the difference between them?

**Comment by jbialobr** [comment]
The first case (the first two images) is for running ConEmuInside with the shift key pressed (using shortcut). The second case (the last two images) is for running ConEmuInside when not shift key is pressed (using a button from the toolbar). In the second case the command executes successfully, but in the first case does not.

>Anyway, words "logged in as Admin on my PC" are ambiguous: login=Admin? Elevated account? UAC enabled/disabled? What OS you are using at last?

I am logged in into account with Admin rights on windows 10.

**Comment by Maximus5** [comment]
Is your drive D: network or local?

**Comment by jbialobr** [comment]
It is local, but made with the `subst d: g:\d` command.

**Comment by jbialobr** [comment]
When I run directly from the g: drive, the command is executed but it fails to connect over ssh.
It is because ConEmuC is missing the GIT_SSH environment variable. ConEmu has the GIT_SSH variable set correctly. This for the case when the shift key is pressed and ConEmu is run as Admin.

When shift is not pressed ConEmuC is not missing the GIT_SSH variable.
The GIT_SSH is set for GitExtensions process [here](https://github.com/gitextensions/gitextensions/blob/5e24353fcd16d9c97e98f04f10963945ff57c8f0/GitCommands/Git/GitCommandHelpers.cs#L599)

```
"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=on-demand --progress "origin" refs/heads/master:refs/heads/master
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Done

Press Enter or Esc to close console...
```

**Comment by jbialobr** [comment]
@Wirone ConEmu integration was added recently and will be shipped with the next version.

**Comment by ArsenShnurkov** [comment]
@jbialobr please advise what to do with https://github.com/Maximus5/conemu-inside/commit/857eb7c45f0ded41eab214faa36d13fe7c9960d2#commitcomment-18974700

**Comment by Wirone** [comment]
@jbialobr Ah, thanks. I'm waiting for new release then :-)
