### ISSUE TITLE
Remove `if !__MonoCS__ || Mono212Released` from designer.cs files

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#3265]
I compiled and successfully run GitExt using the latest mono.

**Comment by KindDragon** [comment]
What will be the minimum supported version of Mono?

**Comment by jbialobr** [comment]
@ArsenShnurkov had problems with mono-4.2.0.179: https://github.com/gitextensions/gitextensions/issues/2697
I was able to build with mono-4.2.1 and it worked pretty stable as opposite to previous versions which crashed regulary.

**Comment by ArsenShnurkov** [comment]
4.3.2 is minimal version of mono where the bug #2697 was fixed, see
https://github.com/mono/mono/pull/2618/commits
but gitextensions was changed earlier to avoid this bug in mono
