### ISSUE TITLE
[ConEmu] Mono compilation errors

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#3266]
The integration of the ConEmu does not compile with mono. 
I have to remove some lines to be able to compile the mono project. See the details here: 
https://github.com/gitextensions/gitextensions/commit/146f40bf1e6ca88c89ed0dfe8ddeeaad60be3803

**Comment by ArsenShnurkov** [comment]
see also https://github.com/Maximus5/conemu-inside/issues/29

**Comment by KindDragon** [comment]
Current master compile (07345e4) for me on Ubuntu 16.04 LTS using MonoDevelop 5.10
