### ISSUE TITLE
JPG preview not available for staged files

### ISSUE THREAD

**Issue by miparnisari** [gitextensions/gitextensions#3279]
You can see PNG but for JPGs I get "Binary files /dev/null and b/img/name.jpeg differ"

**Comment by jbialobr** [comment]
I can see JPGs as well. What is your OS and GitExt version?

**Comment by miparnisari** [comment]
Ah, I made a mistake. The message shows after you've staged the file. The preview works well.

I'm using Windows 10 and GitExt 2.48.05.

**Comment by GintasS** [comment]
The preview works both in change and stage windows. The message that this user receives (if any) is not related (AFIK) to the preview being not available (I guess "preview not being available" still exists for large files, both size and dimension wise)?

**Comment by gerhardol** [comment]
Images can be previewed, I do not think this is an issue any more (change some time ago, maybe also in 3.5)
