### ISSUE TITLE
Unstaging many files from Commit dialog freezes UI for a long time

### ISSUE THREAD

**Issue by shift-evgeny** [gitextensions/gitextensions#3280]
If I open the Commit dialog with hundreds of files staged and try to unstaging most of them (but not all of them) the UI appears to be frozen. I can see in Process Hacker that Git Extensions is running "git.exe reset HEAD -- some/file" over and over for each file. This is a poor user experience. With enough files I would have no choice but to kill the Git Extensions process.

If there is no way to reset multiple files quickly Git Extensions should not freeze while this runs and should allow the process to be cancelled at any time.

**Comment by vbjay** [comment]
We could use something like the process dialog.  If the count is greater
than X then show the dialog with lines saying <file path> unstaged.

**Comment by Radrik5** [comment]
Usually it's much faster to run single git process with a set of files then to start separate git processes for each file. But there is a command line length limit, so in general we cannot put all the selected files into a single command.

**Comment by vbjay** [comment]
Why I suggested the process dialog.  After each unstage we add a line
saying x was unstaged.

**Comment by jbialobr** [comment]
@vbjay the problem is not a lack of progress, but poor performance caused by executing a git command for each file.

@Radrik5 We could split the file list into smaller hunks and execute fewer git processes. Other option is to use Libgit2Sharp library for unstaging files.

**Comment by vbjay** [comment]
@jbialobr <https://github.com/jbialobr> I was thinking if it will take a
while run the commands in a background thread and show the status if the
file count is above a minimum value.  This would eliminate the freezing and
let the user know it is processing.

**Comment by shift-evgeny** [comment]
>the problem is not a lack of progress, but poor performance caused by executing a git command for each file

I think both of these are problems. Obviously if Git Extensions can do this much faster - it should. But there could be thousands of files instead of hundreds. Unless the command can *always* execute within a second or so the UI will still appear to freeze.

**Comment by jbialobr** [comment]
There is a progres bar on the top of the commit dialog.

**Comment by shift-evgeny** [comment]
That's true. So perhaps if it freezes for up to 5-10 seconds or so it's not so bad. But any more than that and there should still be an option to cancel rather than having to kill GitExtensions.exe.

**Comment by nsartor** [comment]
In the case of pressing the "unstage all" button, the app still calls git on each file 1 at a time. Could it just call "git reset" in this case instead?
