### ISSUE TITLE
Resizing the Push dialog scatters the text

### ISSUE THREAD

**Issue by phillijw** [gitextensions/gitextensions#3282]
![image](https://cloud.githubusercontent.com/assets/467889/17232958/aa06b638-54f1-11e6-8c0b-20ec1de84ab9.png)

As you can see the text is spaced out strange because I resized the window. Is there a way to reset the layout of text by telling the console how many characters wide it should be or do we need to disable resizing?

**Comment by jbialobr** [comment]
Can not reproduce it. Can you check if the problem exists in the current master?

**Comment by KindDragon** [comment]
Git bash shows:
![image](https://cloud.githubusercontent.com/assets/224272/18837911/3821e3e8-840e-11e6-9f3d-032a7a021f57.png)
ConEmu shows:
![image](https://cloud.githubusercontent.com/assets/224272/18837891/25e638a0-840e-11e6-8d7a-4763f37ed47d.png)

**Comment by KindDragon** [comment]
It's not related to the window size. Somehow, first output string begins with a large indentation.
BTW console window often shows up scrolled to the second line.

**Comment by jbialobr** [comment]
> It's not related to the window size.

This why I can not reproduce it. Here is how it looks on PC:
![gitext](https://cloud.githubusercontent.com/assets/1003909/18838289/37df8298-8407-11e6-8ccb-a4118c6138fe.png)

**Comment by KindDragon** [comment]
/cc @hypersw 
BTW I can't update to latest ConEmu package, because `CommandLineBuilder` class now internal

**Comment by jbialobr** [comment]
>BTW I can't update to latest ConEmu package, because CommandLineBuilder class now internal

There is an issue raised for this: https://github.com/Maximus5/conemu-inside/issues/29

**Comment by phillijw** [comment]
Do we need to update to the latest ConEmu package to close this one out? Not sure this issue is worth holding up 2.49 for

**Comment by KindDragon** [comment]
I've already updated to latest, but now ConEmu doesn't print executed command

**Comment by jbialobr** [comment]
@KindDragon Can you debug and see what are the extra characters at FormProcess.DataReceivedCore?

**Comment by larshg** [comment]
I see odd behavior too when resizing - but only during the console is actually outputting. If you resize during text is written in the console, the layout is way off.

![image](https://cloud.githubusercontent.com/assets/1165340/19161253/5eb30b58-8bf3-11e6-90b4-e99d569c35e9.png)


Using windows 10, latest master.

**Comment by jbialobr** [comment]
It is a minor issue if it only occurs when the dialog is resized while git is outputing. It should not block the 2.49 release.

**Comment by KindDragon** [comment]
Перевести
It behaves strangely, even without resizing
