### ISSUE TITLE
git program start automatically

### ISSUE THREAD

**Issue by sola634** [gitextensions/gitextensions#3289]
Hi, I have a situation the git.exe program start automatically when I open my repository. And the git.exe is not only start for one , about three and more the same git.exe program will be started. every one for them will occupy the 15%-30% CPU. it will make the extensions very slow...

**Comment by vbjay** [comment]
Use [Procexp](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx) to find out the comandline arguments being used.

**Comment by sola634** [comment]
I check with Progress Explorer, and the result as below

![2016-08-08 15_01_21-process explorer - sysinternals_ www sysinternals com oocldm_maiso](https://cloud.githubusercontent.com/assets/17744729/17471849/9c78dfba-5d79-11e6-9dd7-f7e045c81d53.png)

**Comment by sola634** [comment]
I check with Progress Explorer , and I find there are four git program, as below

![2016-08-08 15_01_21-process explorer - sysinternals_ www sysinternals com oocldm_maiso](https://cloud.githubusercontent.com/assets/17744729/17471875/eb84d118-5d79-11e6-8b2e-a79d6d80c067.png)

**Comment by jbialobr** [comment]
How long does it take to run the same command from git bash?
