### ISSUE TITLE
System Exception Crash during install

### ISSUE THREAD

**Issue by ulrieth** [gitextensions/gitextensions#3290]
during install i get the following:
![capture2](https://cloud.githubusercontent.com/assets/20745765/17499703/1d8b4250-5d9d-11e6-95ae-4add126b229f.JPG)
![capture](https://cloud.githubusercontent.com/assets/20745765/17499724/376ba1ba-5d9d-11e6-875e-db1b2e0fb8ad.JPG)
![capture1](https://cloud.githubusercontent.com/assets/20745765/17499732/3d562104-5d9d-11e6-8e61-c17c56006257.JPG)

**Comment by Nochdarus** [comment]
Says that git extensions got a problem when trying to load your .gitconfig.
Do you have something unusual in there?
In your C:\Users\Jason\.gitconfig I mean.

Thanks in advance for providing the info!

**Comment by ulrieth** [comment]
.gitconfig is not in the folder.

**Comment by jbialobr** [comment]
Are you sure, perhaps it is hidden? When the file is missing I get a FileNotFoundException here.

**Comment by RussKie** [comment]
Please reopen if this still is a problem with the current version
