### ISSUE TITLE
Performance problems when Windows 10 Speech recognition enabled

### ISSUE THREAD

**Issue by Ian1971** [gitextensions/gitextensions#3292]
I have just upgraded to Windows 10 anniversary, and thought I'd try out the speech stuff. One thing I have found is that git extensions becomes unusably slow (even if I am not speaking). It returns to normal if I exit and turn listening off.

**Comment by RussKie** [comment]
Is this still a problem with the current version?

**Comment by vbjay** [comment]
I think that would be because the listing system is taxing your system. I'm
sure it's not just git extensions.

**Comment by Ian1971** [comment]
I gave it a retest. The current version seems to have the same problem.  I haven't noticed it in other applications, but I usually don't have speech enabled because I need to use git extensions.
