### ISSUE TITLE
Feature: Support multi Selection in diff tab

### ISSUE THREAD

**Issue by chirazChiraz** [gitextensions/gitextensions#3293]
support opening Beyond compare for more than one file selected at the same time
steps:
select diff tab
select 3 files modified
click on F3
==> beyond compare ( which is defined as default compare tool ) opened with 3 tabs, one tab for each file

**Comment by chirazChiraz** [comment]
Currently, when you right click one file in the diff tab you get the "Open with diff tool" enabled as the first item in the context menu.

However, if you select multiple files in the diff tab the "Open with diff tool" item is disabled.

I would like to enable this option so multiple files can be opened at the same time by selecting multiple files and using F3 key or the right click menu.

**Comment by vbjay** [comment]
Not all diff tools support this.

**Comment by chirazChiraz** [comment]
@vbjay Git allows you to select one then diff, then another one then diff... so this can be done in a loop when multiple files are selected

**Comment by KindDragon** [comment]
Sorry, but this can cause horrible user experience.
User can select all files and aссidently open dozens of compare tools

**Comment by ghanique** [comment]
Maybe give a warning if the user selects more than, say, 10? Windows
Explorer does the same if you select more than x jpg-s for example and then
press enter.

**Comment by chirazChiraz** [comment]
@KindDragon supporting multi selection is a feature that I'm missing from other tools I've used in the past, e.g. Atlassian SourceTree and p4v. It saves me time when reviewing code and hasn't caused me any issues.

@ghanique I like the idea of giving a warning. Seems a good compromise to me!

**Comment by vbjay** [comment]
Add a setting to adjust warning level.  Default it to something reasonable.

**Comment by KindDragon** [comment]
> Maybe give a warning if the user selects more than, say, 10?

Better, if you select more than 5 files

**Comment by vbjay** [comment]
^ is exactly why I suggested the setting.

**Comment by ghanique** [comment]
Or make a checkbox "Don't ever warn me again."
There are of those in Git Extensions, aren't there?

**Comment by chirazChiraz** [comment]
Hi,

@hkouki thank you for the pull request :)
Any update please?

Thank you

**Comment by jbialobr** [comment]
Implemented in #3556

**Comment by webmaster33** [comment]
I really miss the feature (v2.49.03) to select two branches, and while the changes are listed in the Diff tab, I would like to select a several files, and Cherry pick them together. 
If I select 2 or more files, the Cherry pick files's changes is grayed out.

Does this new "multi Selection in diff tab" feature also allow "Cherry picking multiple file changes"?
