### ISSUE TITLE
display the total number of modified files

### ISSUE THREAD

**Issue by chirazChiraz** [gitextensions/gitextensions#3294]
dislay the total count of modified files in diff tab

**Comment by chirazChiraz** [comment]
Currently, in the commit window (staged/unstaged areas) and diff tab you cannot easily find out how many files are listed. I would like to have a count of files that exists in the list.

**Comment by jbialobr** [comment]
How is this knowledge usuefull to you?

**Comment by vbjay** [comment]
That would be a trivial task.  Why don't you make it happen.  Do the work
and make a pull request.

**Comment by chirazChiraz** [comment]
@jbialobr  This will help to easily find out the number of changed files when reviewing the code.
@vbjay  I'm new with Git. I can help with testing

**Comment by vbjay** [comment]
Good time to start.  Pull down the source code and create a branch for this
feature.  Make the changes needed.  Commit your changes.  Push your changes
to your fork.  Create a pull request between your branch and gitextensions
repo.   See
https://github.com/gitextensions/gitextensions/wiki/Project-Workflow

**Comment by chirazChiraz** [comment]
@vbjay I'm new with Git and also I'm not familiar with C++ , otherwise, I would be happy to do it

**Comment by vbjay** [comment]
It's C# not C++.

**Comment by jbialobr** [comment]
The part concerning the Commit window is done.
![gitext](https://cloud.githubusercontent.com/assets/1003909/24137529/715e8a90-0e14-11e7-95ff-26bef0b8211f.png)
