### ISSUE TITLE
No Response in VS2015 Extension

### ISSUE THREAD

**Issue by anti1234** [gitextensions/gitextensions#3296]
I install git extension from Extension Gallery to my vs2015. The menu *GITEXT* is showed. But it has no any response while I click the command item  on the GITEXT list.

**Comment by vbjay** [comment]
See #2885

**Comment by vbjay** [comment]
Our official extension is here.  https://visualstudiogallery.msdn.microsoft.com/8f594baa-e44e-4114-8381-e175ace0fe97  We haven't released the version with the 2015 extension.  See #2815 #2885

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/milestone/16
