### ISSUE TITLE
Unable to use '/' or '.' in branch name when creating a new branch?

### ISSUE THREAD

**Issue by wangzq** [gitextensions/gitextensions#3297]
I am using latest code on master branch, and found the "Create new branch" dialog has changed a lot, and it disallows `/` and converts `.` to `_` automatically. Why is that?

**Comment by vbjay** [comment]
see #3233

**Comment by wangzq** [comment]
Thanks, I can turn it off in settings - advanced.

**Comment by jbialobr** [comment]
@RussKie '/' and '.' are not invalid characters

**Comment by RussKie** [comment]
The normaliser works correctly - you can paste a branch name with `.` and `/` and it would work
The problems seems to be in the UI part where it replaces incorrect symbols on `TextChanged` event. 

Perhaps the fix may be not to normalise while the user is typing and do it on focus leave event...

**Comment by jbialobr** [comment]
> Perhaps the fix may be not to normalise while the user is typing and do it on focus leave event...

Sounds good.
