### ISSUE TITLE
Use Zenhub in Repo

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#3305]
This [extension](https://www.zenhub.com/ ) looks like it could help manage things for this project.

![image](https://cloud.githubusercontent.com/assets/3629489/17983463/aed7ac04-6ada-11e6-9157-98f4bddd6a69.png)

**Comment by KindDragon** [comment]
Thanks, I tried it but my browser began work slower.
It similar to https://waffle.io/ that I use, but Kanbab board not so useful without constantly working team. If I have free time, I can just grab any issue with the label prio:highor with most comments (most reactions).

**Comment by vbjay** [comment]
Cool thanks.

**Comment by vbjay** [comment]
The thing with waffle is that we can't add this repo to waffle.  Zenhub shows a readonly view even though I am not a member of your organization.  

I understand the slow down on the browser.

**Comment by KindDragon** [comment]
You have readonly access to waffle too https://waffle.io/gitextensions/gitextensions
