### ISSUE TITLE
GitBranchNameOptionsTest failed due to localized exception message

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#3306]
> The exception message is localized and the tests don't pass:
> Expected: "Replacement token invalid: ' '\r\nParameter name: replacementToken"
> Actual: "Replacement token invalid: ' '\r\nNazwa parametru: replacementToken"

**Comment by RussKie** [comment]
@jbialobr, I'm not quite sure how to emulate that though....
Do you have localised version of OS, VS and/or .NET Fx?

If you amend the test as follows would it pass?

```
        [TestCase(" ", ' ')]
        [TestCase("~", '~')]
        [TestCase("^", '^')]
        [TestCase("~", '~')]
        [TestCase(":", ':')]
        public void ReplacementToken_cant_be_invalid(string token, char expected)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.InvariantCulture;

            ((Action)(() => new GitBranchNameOptions(token))).ShouldThrow<ArgumentOutOfRangeException>()
                .WithMessage(string.Format("Replacement token invalid: '{0}'\r\nParameter name: replacementToken", expected));
        }
```

**Comment by jbialobr** [comment]
My OS locale is pl_PL.

Adding this line did the trick:
`Thread.CurrentThread.CurrentUICulture = CultureInfo.InvariantCulture;`

**Comment by RussKie** [comment]
Awesome, I'll update the tests

**Comment by RussKie** [comment]
NUnit seems to have attributes to set culture: [SetUICultureAttribute](http://nunit.org/index.php?p=setUICulture&r=2.6.4) and [SetCultureAttribute](http://nunit.org/index.php?p=setCulture&r=2.6.4)

Could you please see if decorating the class will solve the issue for you?

```
    [SetCulture("")]
    [SetUICulture("")]
    //[SetCulture("en-US")]
    //[SetUICulture("en-US")]
    [TestFixture]
    public class GitBranchNameOptionsTest
    {
        ....
    }

```

The `""` versions should work according to the [MSDN](https://msdn.microsoft.com/en-au/library/system.globalization.cultureinfo.invariantculture(v=vs.110).aspx#Anchor_1), if not - the `en-US` variant should do the trick.

**Comment by jbialobr** [comment]
`[SetUICulture("")]` works fine. Thanks for digging up the solution.
