### ISSUE TITLE
Execute multiple commands in scripts

### ISSUE THREAD

**Issue by Sharuru** [gitextensions/gitextensions#3314]
Hi, some member of my team usually using SVN before, they would like to checkout only one file from the server.

In Git, we can use something like `git fetch | git checkout origin/master -- file/to/path` instead.

So, I am willing to build a script in settings and let them to just input the file path and get the file from the server.

But it seems some mistake? It throws me such error:

> 
fatal: '|' does not appear to be a git repository
fatal: Could not read from remote repository.

I didn't find any information about scripts on homepage.

Here is my script:
![20160829152118](https://cloud.githubusercontent.com/assets/3275627/18042513/be91e2fc-6dfc-11e6-94f9-6b1216903eac.png)

Please help me, thank you.

**Comment by vbjay** [comment]
The scripts use processes.  Pipes start a new process and send the output
as input to the next process.  I don't think this is a good idea to try to
create using git cmd.  Instead we could add a bash script runner option.
Check a checkbox that says this script is a bash script.  When it is a bash
script, just run the script in a bash shell. captured by our process
window.

**Comment by Sharuru** [comment]
Hi, 
> Check a checkbox that says this script is a bash script.

I didn't find this checkbox in setting menu, where is it?

Thank you

**Comment by vbjay** [comment]
It was a feature suggestion.

**Comment by jbialobr** [comment]
You don't have to write a script. You can select a file and reset it to a desired revision (origin/master in your case). See the screenshot below:
![gitext](https://cloud.githubusercontent.com/assets/1003909/18061372/cd30fb1a-6e22-11e6-8208-04fe5ce2a7b6.png)

**Comment by Sharuru** [comment]
Thanks for your help!
The problem is solved.

FYI, in version 2.48.05, this menu shows 'Reset file(s) to A' and 'Reset file(s) to B'

**Comment by Piedone** [comment]
I'd just add that with a bit of tricks you can execute multiple commands when piped after each other but you need to use Powershell. E.g. to add a submodule-inclusive clean:

1. As the command use powershell (just the string "powershell", nothing else needed, you don't need to browser to powershell.exe).
2. Add the following as Arguments: git clean -fxd | git submodule foreach git clean -fxd
