### ISSUE TITLE
Exception if I press ok on setting page (gitExtensions)

### ISSUE THREAD

**Issue by Bernie07** [gitextensions/gitextensions#3318]
Hello,
I've get the following exception if I'm pressing the ok Button of the Settings Dialog

System.IO.IOException
Die Datei oder das Verzeichnis ist beschädigt und nicht lesbar.
Application : GitExtensions.exe [2.48.05]
NBug : 1.1.2.0

Stack Trace
  bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   bei GitCommands.Settings.FileSettingsCache.SaveImpl()
   bei GitCommands.SettingsCache.<>c__DisplayClass1.<LockedAction>b__0()
   bei GitCommands.SettingsCache.LockedAction[T](Func`1 action)
   bei GitCommands.Settings.SettingsContainer`2.Save()
   bei GitCommands.Settings.SettingsContainer`2.Save()
   bei GitCommands.Settings.SettingsContainer`2.Save()
   bei GitUI.CommandsDialogs.FormSettings.Save()
   bei GitUI.CommandsDialogs.FormSettings.Ok_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Can please someone explain why this error happens. It worked fine since yesterday. And suddenly (without installing a new Version) this error happens each time I starting the Settings Dialog and press OK or I starten the Browse Dialog.

Best wishes
Bernhard

**Comment by vbjay** [comment]
Doesn't look like it is our problem.  
![image](https://cloud.githubusercontent.com/assets/3629489/18202817/94d54152-70e0-11e6-8724-1f9de7d66ea8.png)

**Comment by Bernie07** [comment]
Which Problem is it then? git?
I think it is your Problem. git has an update since 31 August and I think it is not compatible with git Extension. The Update to the Version git 2.9.3 was suddently on my Computer and since then it don't works.

**Comment by jbialobr** [comment]
I think that vbjay suggested you that your hard disk can be damaged and showed you a command to verify that: `chkdsk C: /r`
