### ISSUE TITLE
Plugin loading phase

### ISSUE THREAD

**Issue by maraf** [gitextensions/gitextensions#3320]
Hi there,
I have recently tried to develop plugin for dynamically providing message template based on the id of currently processing issue. I am using `IGitUICommands.PreCommit` to augment my template. It is working fine, but when I use VS extension command that directly opens commit dialog, plugins aren't loaded and so my code is not executed.

I have found that plugins are loaded when `FormBrowse` is opened. It is by design or can my issue be considered as "bug"?

Thanks for reply.

**Comment by vbjay** [comment]
You raise a good point but frankly you should be using [Git Hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks).  Your code would only run with git extensions.  What if you run a shell one time and commit or go to another machine?

**Comment by jbialobr** [comment]
I think it can be considered as a bug. See on my comment to a similar PR 
https://github.com/gitextensions/gitextensions/pull/2495#issuecomment-237376795

**Comment by vbjay** [comment]
I agree.  I was just pointing out that git hooks would be better in the long run.

**Comment by Radrik5** [comment]
Regarding git hooks: for example, I want to insert title of one of the issues assigned to me into the commit message. Which hook should be used? How to select the required issue from the UI perspective?

**Comment by vbjay** [comment]
I like that idea.  Couple of problems

1.  Would need to create a generic issue gathering functionality and allow for github provider, JIRA, codeplex, visual studio online.....
2.  If we used a REST api to get it, how do we not run into limits of requests?

**Comment by maraf** [comment]
@vbjay Thanks, you are right. We are using GitExtensions and only GitExtensions. Also, I have some buttons to the FormCommit UI to support our issue provider. So the solution is just fine for us, except this little thing.

**Comment by maraf** [comment]
Does anything changed with this issue in the upcoming v3?

**Comment by gerhardol** [comment]
> Does anything changed with this issue in the upcoming v3?

no
