### ISSUE TITLE
When expanding the "working directory changes" frame, the list of files changed is shown empty

### ISSUE THREAD

**Issue by miparnisari** [gitextensions/gitextensions#3323]
This only seems to happen when the list of files that have changed is big enough to require a vertical scroll bar.

![bug](https://cloud.githubusercontent.com/assets/5374887/18514782/4873e466-7a69-11e6-835e-3f5032cddce3.gif)

I'm using Git Extensions 2.48.05 in Windows 10.

**Comment by RussKie** [comment]
Please re-open if it is still a problem in the current version.
