### ISSUE TITLE
"Add file to .gitignore" feature not working as expected

### ISSUE THREAD

**Issue by hiteshdholaria** [gitextensions/gitextensions#3330]
--- GitExtensions2.44, 1.8.1.msysgit.1, Microsoft Windows NT 6.2.9200.0

Even after adding certain files to ignore list, they are showing up in Commit window.

**Comment by ghanique** [comment]
Please be more specific.
What is the content of the gitignore file and what files still appear in
the commit window?

**Comment by vbjay** [comment]
If the file has been committed, ignore won't work. You have to add it to
assume unchanged.

**Comment by hiteshdholaria** [comment]
@vbjay How do I add it to "assume unchanged"? I don't see such option on Commit window.

**Comment by hiteshdholaria** [comment]
@vbjay Thanks, below command did it.
git update-index --assume-unchanged
