### ISSUE TITLE
Fix translation issues

### ISSUE THREAD

**Issue by KindDragon** [gitextensions/gitextensions#3333]
https://www.transifex.com/git-extensions/git-extensions/translate/#issues

**Comment by KindDragon** [comment]
Issue 3333 😄

**Comment by pmiossec** [comment]
Good job all :clap:  I hope the v2.49 will be released soon ;)

**Comment by KindDragon** [comment]
We too 😃

**Comment by miparnisari** [comment]
What languages need to be translated before 2.49 can be released?

**Comment by pmiossec** [comment]
If you follow the link, there is your answer ;-)
Less than 5% for the already supported languages except Spanish that need 9% and Chinese and Japanese that need around 12%.

**Comment by jbialobr** [comment]
After the Release cycle wiki page https://github.com/gitextensions/gitextensions/wiki/Release-cycle#2-preparing-to-release
>Announce on Transifex that new version is ready to ship in two(?) weeks and only the language in which the "User Interface (master)" translated 95% or more will be added in the installer.

**Comment by jbialobr** [comment]
I fixed the issues that didn't require to change a source text.

**Comment by KindDragon** [comment]
/cc @ghanique @fraga @bleis-tift @bygreencn @ferow2k @Pavuucek  @spdr870
Please help us with translation if you can
https://www.transifex.com/git-extensions/git-extensions/dashboard/

**Comment by pmiossec** [comment]
Translation completed for french ;) Not always perfect but I have at least fix some old bad translations ! :D

**Comment by ghanique** [comment]
Finished the Dutch translation. I looked at everything once and nothing is
reviewed.
(Personally I don't think it makes sense to translate it to Dutch, because
all the technical terms remain English anyway. I never use Dutch
translations as terminology quickly becomes confusing).

**Comment by jbialobr** [comment]
>Personally I don't think it makes sense to translate it to Dutch, because
all the technical terms remain English anyway. I never use Dutch
translations as terminology quickly becomes confusing

So do I. And if you learn a foreign language, you should use it as often as possible.

**Comment by miparnisari** [comment]
@pmiossec, I'm doing Spanish, the UI is at 97%, is that enough? (I'm new with Transifex)

**Comment by KindDragon** [comment]
@miparnisari It is enough for release, but from the user's point of view is better to have 100% or him will see in random places text in English
