### ISSUE TITLE
Atlassian Stash is now called Bitbucket Server

### ISSUE THREAD

**Issue by Copro** [gitextensions/gitextensions#3334]
Atlassian Stash was renamed to Bitbucket. There is a Plugin for Stash / Bitbucket Pull Requests in 2.48.05 named "Create Stash Pull Request".
Parameters are:
- Stash Username
- Stash Password
- Specify the base URL to Stash
- Disable SSL verificatiobn [ ]

This should be changed to now support Bitbucket.
URL: [Atlassian Stash is now called Bitbucket Server](https://www.atlassian.com/software/bitbucket/server)

Also commented on the Atlassian Bitbucket Support [Issue 1733](https://github.com/gitextensions/gitextensions/issues/1733)

**Comment by crypto-rsa** [comment]
Anything else to do before this issue can be closed?
