### ISSUE TITLE
Build fails on linux

### ISSUE THREAD

**Issue by Shauren** [gitextensions/gitextensions#3335]
Building GitUI fails on case sensitive filesystems
Running `nuget restore GitExtensionsMono.sln` creates `packages\ConEmu.Core.16.9.14.0\Build` directory (Build starts with uppercase) but GitUI.csproj references the path with lowercase `build`

**Comment by jbialobr** [comment]
Do you use GitExt on linux? Have you noticed [this issue](https://github.com/gitextensions/gitextensions/issues/3287) using GitExt?

**Comment by Shauren** [comment]
Not yet, only built it first time for now (been using it only on windows so far). Will report back if I see it.
