### ISSUE TITLE
Move ConEmu Pallete parameter to ConsoleProcessExtraArgs

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#3337]
After the PR https://github.com/Maximus5/conemu-inside/pull/31 get merged.

**Comment by jbialobr** [comment]
@KindDragon What do you think about making the ConEmu-inside a submodule of GitExtensions?

**Comment by KindDragon** [comment]
IDK. I prefer NuGet if it contains all the necessary features for us.

**Comment by KindDragon** [comment]
Fixed bee6701009c6661d6a156b5646ded609c314c81b
