### ISSUE TITLE
In the root directory of the disk gitext clone, quoted error path contains illegal characters.

### ISSUE THREAD

**Issue by yemadu** [gitextensions/gitextensions#3338]
--- GitExtensions2.48.02, Git 2.10.0.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

在磁盘根目录进行 gitext clone 的时候, 报出路径中含有非法字符错误.
In the root directory of the disk gitext clone, quoted error path contains illegal characters.

![image](https://cloud.githubusercontent.com/assets/8444073/18965912/b629f726-86b1-11e6-818d-a3e3497bb24f.png)

![image](https://cloud.githubusercontent.com/assets/8444073/18965922/c3e4a37a-86b1-11e6-9cd5-17320d8989c2.png)

**Comment by MisayaJj** [comment]
![image](https://cloud.githubusercontent.com/assets/8444073/18966017/2fa06568-86b2-11e6-85e5-d7f8feef5a30.png)

**Comment by RussKie** [comment]
Please re-open if it is still a problem in the current version.
