### ISSUE TITLE
My GITHUB Account is suspended

### ISSUE THREAD

**Issue by navyapal** [gitextensions/gitextensions#3339]
Hello,

Looks like my account has been suspended and I get below error message.

git pull --rebase --progress "origin" 
ERROR: Your account is suspended. Please check with your installation administrator.
fatal: Could not read from remote repository.
 
Please make sure you have the correct access rights
and the repository exists.

Thanks,
Navya

**Comment by vbjay** [comment]
Just curious in how you expect the members of this repository to help you in that. Maybe you could contact GitHub support.
