### ISSUE TITLE
Thank you share your good program.

### ISSUE THREAD

**Issue by daniel00** [gitextensions/gitextensions#3340]
--- GitExtensions2.47.3, Git 1.8.3.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1
Thank you to sharing your good program
I want to check revision by using tag number .  In bash console I using "git describe --tag --long"
And then the result is Ver-1, Ver-2, Ver-3 and so on.
How can I display the tag number in commit history window?
Thank you to reading.

**Comment by KindDragon** [comment]
We have feature request about that #84
