### ISSUE TITLE
gource cannot be started on Windows

### ISSUE THREAD

**Issue by Copro** [gitextensions/gitextensions#3345]
gource cannot be started or downloaded from Git Extensions 2.48.05 in Windows from the Plugins menu.
gource installed per default and the gource.exe is on the local %PATH%
The default installation and the binaries went into %LOCALAPPDATA%\Gource

It does not matter if I configure the path correctly in the Plugins settings - the error message cannot find gource in the configured path is always displayed.
Also if I leave the path empty and click "Yes" to download gource this does not work.

OS: Windows 7 64 Bit
Git Extensions: 2.48.05
Git: 2.6.4.windows.1
Gource: 0.42

**Comment by KindDragon** [comment]
Try remove `--user-image-dir "$(AVATARS)"`, it sometimes consumes a lot of time

**Comment by KindDragon** [comment]
Works in 2.49RC1
