### ISSUE TITLE
Readability of "Merge branches" dialog

### ISSUE THREAD

**Issue by phillijw** [gitextensions/gitextensions#3346]
![image](https://cloud.githubusercontent.com/assets/467889/19130417/ac93a9d8-8b10-11e6-9d12-865222bdb9a3.png)

The text at the top says "Merge branch into current branch" and I think the following branches should follow that same order instead of being backwards. For instance it should look like this:

    Merge branch into current branch
    
    Branch: [origin/feature/spellchecker]
    into current branch: master

...or something like that. It's a subtle change but makes it easier to explain to new people what's merging into what.

**Comment by KindDragon** [comment]
Duplicate of #3208?

**Comment by phillijw** [comment]
Wow, almost an exact duplicate! My search foo is weak
