### ISSUE TITLE
branch naming bug

### ISSUE THREAD

**Issue by aishelm** [gitextensions/gitextensions#3352]
--- GitExtensions2.48.05, Git 2.5.2.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

I had a branch ending in ;
From the UI I couldn't delete it, due to message "branch is not selectable"
I then rename it from the UI
Then I was able to delete it just fine.

**Comment by RussKie** [comment]
Is this still a problem in the current version?

**Comment by RussKie** [comment]
Closing due to age.
Re-open if it is still an issue in the current version.
