### ISSUE TITLE
Not Getting option for Restore Credential

### ISSUE THREAD

**Issue by bvachanizc** [gitextensions/gitextensions#3355]
![gitoptionissue](https://cloud.githubusercontent.com/assets/14109052/19345907/573079e0-915e-11e6-8bba-8f12a598afa2.png) 
Need like this 
![gitoption](https://cloud.githubusercontent.com/assets/14109052/19345982/b7af7802-915e-11e6-9d43-f2dd04407203.png)

Also in Visual Studio not getting GIT Option and Not getting PULL PUSH and COMMIT option in Toolbar.

--- GitExtensions2.48.05, Git 1.9.5.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by KindDragon** [comment]
This option is now removed since it is integrated into Git 2.xx

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
