### ISSUE TITLE
Can't input to ConEmu console

### ISSUE THREAD

**Issue by larshg** [gitextensions/gitextensions#3356]
![image](https://cloud.githubusercontent.com/assets/1165340/19348978/f7e2e87c-9150-11e6-84eb-a1c98b5eaac0.png)

When it ask for adding ssh-rsa key to putty...

**Comment by jbialobr** [comment]
I reported the issue to the conEmu project https://github.com/Maximus5/ConEmu/issues/913

**Comment by KindDragon** [comment]
It's error with new Git 😞 
It's work fine if I start plink directly `"C:\Program Files (x86)\GitExtensions\PuTTY\plink.exe" git@github.com "git-upload-pack 'gitextensions/gitextensions.git'"`

**Comment by KindDragon** [comment]
I tried even with Git 2.5.0, same result. Maybe it plink bug, IDK

**Comment by KindDragon** [comment]
User can 'Test connection` button in [Remote repositories](http://git-extensions-documentation.readthedocs.io/en/latest/remote_feature.html?highlight=Remote%20repositories) windows to work around this issue

**Comment by jbialobr** [comment]
There is an issue https://github.com/git-for-windows/git/issues/482 about this. The issue is closed but not resolved. This problem is listed in the [know issues](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues)

**Comment by phillijw** [comment]
FYI there are a few other scenarios (at least one that I found and forgot yesteday) in which it asks for user input

**Comment by jbialobr** [comment]
Yes, we know there are other scenarios, but this is the first one we are not able to enter an input data. Were you able to do it there?

**Comment by phillijw** [comment]
I don't think I was able to input on the other screen either but if I can remember what it was, I'll check and make a separate issue
