### ISSUE TITLE
setup text is cut off on right side (version 2.49 rc-1)

### ISSUE THREAD

**Issue by danmcmanus** [gitextensions/gitextensions#3359]
![image](https://cloud.githubusercontent.com/assets/18675487/19393330/eb70e324-91f9-11e6-910a-328c3a2d4d8a.png)

*Not sure if this is a git installer issue or git extensions installer issue?

**Comment by jbialobr** [comment]
This is a git installer issue. Try to report there: https://github.com/git-for-windows/git/issues
