### ISSUE TITLE
Can no longer build in VS2013?

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#3362]
I pulled down the latest and found I can no longer build the solution under VS2013 due to dependencies on \Externals\conemu-inside\ConEmuWinForms\ConEmuWinForms.csproj which is C# 6 (VS2015) project...

The resolution may include the following options:
1. mandate VS2015 and remove support for older version of VS, or
2. include the dependencies via submodules but check-in and create project references to compiled artifacts only, or
3. create external dependencies via nuget feeds only

Thoughts?

PS: I heard one can install C#6-support in VS2013 but it isn't a workable long-term solution.

**Comment by KindDragon** [comment]
I think we should remove old solutions and only support VS2015

**Comment by jbialobr** [comment]
I agree, VS2015 community edition is free for open source projects. It will simplify the project maintenance. Does anyone see any drawbacks?

**Comment by phillijw** [comment]
Is Linux a factor still?

**Comment by KindDragon** [comment]
We have different solution for Mono

**Comment by gerhardol** [comment]
I will miss VS2013 support at work, cannot update VS2013 Pro there.

**Comment by KindDragon** [comment]
Can't you install VS2015 Community also there?

**Comment by vbjay** [comment]
Community edition is not licensed like that. If he is installing it at his
work.

Usage

For individuals

Any individual developer can use Visual Studio Community to create their
own free or paid apps.

For organizations

An unlimited number of users within an organization can use Visual Studio
Community for the following scenarios: in a classroom learning environment,
for academic research, or for contributing to open source projects.

For all other usage scenarios:
In non-enterprise organizations, up to five users can use Visual Studio
Community. In enterprise organizations (meaning those with >250 PCs or >$1
Million US Dollars in annual revenue), no use is permitted beyond the open
source, academic research, and classroom learning environment scenarios
described above.

https://www.visualstudio.com/support/legal/mt171547

**Comment by vbjay** [comment]
It does fall under open source for this project but they will say but we
don't have just open source projects at the company.

**Comment by KindDragon** [comment]
Ok, thanks

**Comment by gerhardol** [comment]
Just saying that there may be disappointed users by dropping older VS.

Many of my colleagues are forced to use VS2010 as some tools tie hard to the VS version. (IT department is ahead there as an exception.) 

My vote share is very low (and I am fine with that) and I understand why this may be done anyway.
I will miss the support, the built in VS is not much to cheer. There are alternatives that I have not evaluated (will report back) them much and I can still use Git Extensions from Explorer.

I wish it was possible to buy a license for Git Extensions and that I could convince the IT suppliers (now overseas) to get licenses. Several (informal) evaluations ranks Git Extensions as the best client.

**Comment by vbjay** [comment]
Gitextensions is free. No cost to have a license.

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/blob/master/LICENSE.md

**Comment by KindDragon** [comment]
It will support VS2010 extension BTW, but GitExt will be compile with VS2015

**Comment by RussKie** [comment]
I think the conversation spirals into a wrong direction.

The discussion is _not_ about whether GE needs to support old versions of
VS. It is about whether GE _can be built_ with anything but VS2015 and
whether the repo should have solutions for older versions.

**Comment by KindDragon** [comment]
Yes, I just though maybe @gerhardol misunderstand us

**Comment by gerhardol** [comment]
@KindDragon Correct, I misunderstood
So this is just amatter of contributing, then it should be possible to do something. Either getting a real 2015Pro license or work from home.
(I wish we could contribute more, but it seems like it is not more patches that are needed...)

**Comment by RussKie** [comment]
One should be careful when contributing from work (inc. but not limited
work hours, equipment and internet connection provided by your employer) as
you may be in breach of your contractual obligations and jeopardising this
project as you may be introducing a 3rd party IP.
Make sure you consult with and get clearance from your employer.

**Comment by vcpp** [comment]
While GE itself doesn't need VS2015, i think there is no point to force using it just for building third-party dependencies. Referencing third-party binaries is not bad practice in the .Net world (comparing to Gentoo-way), NuGet is suitable for that.
So, the question for me is whether GE is ready to switch to C# 6.

**Comment by KindDragon** [comment]
> So, the question for me is whether GE is ready to switch to C# 6.

I think only Mono can create problems in that

**Comment by RussKie** [comment]
...add .Net 4.6+ to that :)

**Comment by RussKie** [comment]
@KindDragon @jbialobr @vbjay  Any plans to move on this one?

**Comment by vbjay** [comment]
Nope. We have moved to vs 2015 because a dependency requires it. Also vs
2015 is free.

**Comment by RussKie** [comment]
I sense my question was misinterpreted - are we going ahead and removing pre-VS2015 solutions?

**Comment by vbjay** [comment]
Do it and submit a pull request.

**Comment by RussKie** [comment]
I already have, scroll up

**Comment by jbialobr** [comment]
Thank you @RussKie!

**Comment by jbialobr** [comment]
@gerhardol 
>(I wish we could contribute more, but it seems like it is not more patches that are needed...)

Reviewing and testing existing PRs are welcomed as well.
