### ISSUE TITLE
2.49RC1 VS2013 plugin is grayed out

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#3363]
![image](https://cloud.githubusercontent.com/assets/4403806/19438361/41669bc0-94c5-11e6-86aa-4c42fb50a33b.png)

VS2015's plugin is working fine, though it doesn't show the branch name:
![image](https://cloud.githubusercontent.com/assets/4403806/19438417/9756a502-94c5-11e6-8612-7612007445f5.png)

**Comment by KindDragon** [comment]
Try reset addin `VS2013\devenv.exe /resetaddin GitPlugin.Connect`

**Comment by phillijw** [comment]
It seems to be working fine for me in 2013.

![image](https://cloud.githubusercontent.com/assets/467889/19442284/71d92416-944e-11e6-93ae-897d4956d2c5.png)

**Comment by RussKie** [comment]
Thank you, resetting worked.
