### ISSUE TITLE
ConEmu broken in latest master, making Git Extensions completely useless.

### ISSUE THREAD

**Issue by remcoros** [gitextensions/gitextensions#3367]
Since (around) this merge: https://github.com/gitextensions/gitextensions/commit/4e5c21b21124b03587f4d613d73afe5b4e519385

ConEmu is completely broken (see screenshot), I cannot do anything with GitEx anymore:

![no_conemu](https://cloud.githubusercontent.com/assets/130373/19484348/95557fca-9557-11e6-9f9a-6ea5926aa9a1.PNG)

No messages, no (visible) exceptions or anything, just an empty window with no result.

On a side-note: why is conemu used for these windows/messages? I can understand the integrated terminal tab. But why use it for message logging? Looking at the commits/issues, It looks like ConEmu is a major pain point holding back the 2.49 release.

**Comment by jbialobr** [comment]
Please make sure that the compiled conemu dll got into your bin folder, preferably clean and rebuild the solution. I noticed that when incremental build is performed then the VS does not copy the conemu dll into the bin folder.

**Comment by jbialobr** [comment]
> On a side-note: why is conemu used for these windows/messages?

It enables users to interact with git directly like when user has to enter a password.

**Comment by KindDragon** [comment]
also Git can now display colored output

**Comment by EbenZhang** [comment]
> why is conemu used for these windows/messages

you can disable it in the advance settings.

**Comment by remcoros** [comment]
@jbialobr @KindDragon I understand, didn't know there was an option. that's fair.

@jbialobr I use the BuildXXX.bat files to compile/build and make an installer. I guess that is missing the clean/compile step for the ConEmu submodule then?

I will try if this is actually the issue and report back.

**Comment by remcoros** [comment]
I think I found what's causing this.

After running the latest setup (build from master), the contents of ~/Program Files/GitExtensions/ConEmu/ is:

CmdInit.cmd
GitShowBranch.cmd
settings

But the contents of ~/root_git_repo/Setup/GitExtensions/ConEmu is:

ConEmu.exe
ConEmu64.exe
ConEmuC.exe
ConEmuC64.exe
ConEmuCD.dll
ConEmuCD64.dll
ConEmuHk.dll
ConEmuHk64.dll

So it is missing the ConEmu* exe/dll's.

When I manually copy them over to Program Files, everything starts working again.

I suppose they are missing from the WiX installer.

**Comment by KindDragon** [comment]
No, Wix perfectly installs ConEmu for me and others users. Something else causing your issue

**Comment by jbialobr** [comment]
I created a setup file from freshly cloned repo and no files are missing.
