### ISSUE TITLE
The "Repository to clone" field could have better default value

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#3371]
When cloning it's typical to have the URL of the repository in clipboard. When the dialog opens the "Repository to clone" field is pre-filled with the current directory. I'd argue that it's not very probable that the user wants to clone current directory. Therefore I think it would be better to:
- leave the field empty
- preselect the field's value so that user can paste straight from keyboard without selecting the current value

**Comment by OmicronPersei** [comment]
Considering you mention that many users may have the target git repo URL already in the clipboard, would it make more sense to have the default value be text in the clipboard?

**Comment by tomasfejfar** [comment]
For me clipboard would be the ideal value. Preselecting it may help in some cases as well.

**Comment by OmicronPersei** [comment]
Could do both, should be easy enough.

**Comment by OmicronPersei** [comment]
Will probably have to do things like check that the clipboard is text, doesn't have new lines, etc.  Is there a "standard" git URL syntax?

**Comment by tomasfejfar** [comment]
I'm afraid there is not. 

In most github/bitbucket/etc cases it would be `git@github.com:tomasfejfar/pehapkari.cz.git`. But here are also local repositories `c:\git\my-repo` or web repos `http://github.com/tomasfejfar/pehapkari.cz.git` and ssh repos and maybe even some other flavours I have no idea about. But because this is not a crucial functionality and more of a user-experience issue, I think it makes sense to target the most prominent cases. 

I think that starting with `git@*` pattern would be a safe bet. `*.git` also seems to be safe. The rest is possible, I guess, but more prone to false positives. Any other patterns can be added gradually as use-cases emerge. What do you think?

**Comment by jbialobr** [comment]
Isn't it already implemented here https://github.com/gitextensions/gitextensions/blob/e2741f95da5a5860393751b2f1711be4193457b9/GitUI/CommandsDialogs/FormClone.cs#L76?

Have you tried the latest RC https://github.com/gitextensions/gitextensions/releases/tag/v2.49RC2?

**Comment by tomasfejfar** [comment]
Nope I had no idea. I'll give it a try.

**Comment by nul800sebastiaan** [comment]
Unfortunately that feature doesn't seem to work for me, I definitely have a URL on the clipboard starting with http, but it doesn't paste that automatically when the clone window opens. 
Luckily it's just a quick `CTRL+V` because the text is selected.
