### ISSUE TITLE
2.49RC2 crashes when opening settings dialog

### ISSUE THREAD

**Issue by maliayas** [gitextensions/gitextensions#3375]
Whenever I open settings dialog, it opens and then program immediately crashes giving this error: "0 is not valid for SelectedIndex". Here is the screenshot of the error dialog:

![ekran goruntusu 2016 10 24 00_05_43](https://cloud.githubusercontent.com/assets/844008/19629452/8a5a0a0c-997e-11e6-926c-a18e199bebd3.png)

I'm using 2.49RC2. 
Thanks in advance.

**Comment by ghanique** [comment]
I just installed RC2 on Windows 7. I cannot reproduce the error.

**Comment by KindDragon** [comment]
It only happens if you set spell checker dictionary to "none"

**Comment by maliayas** [comment]
Hmm. I've set the dictionary to en-us in the commit window menu but the
crash still occurs. I'll test again if you release a RC3 or sth. Thanks
for the help.

2016-10-25 23:37 tarihinde Arkady Shapkin yazdı:

**Comment by KindDragon** [comment]
Try this build https://drive.google.com/file/d/0B8UPsaxEuQgqZXNuc2dTdnBxakU/view?usp=sharing

**Comment by maliayas** [comment]
Thanks for the demo. Currently I'm away from my original PC. However, the bug doesn't occur in a fresh install, whether using a dictionary or not. Probably it's fixed.

**Comment by maliayas** [comment]
Yep, it's fixed in v2.49. Thanks very much!
