### ISSUE TITLE
"Commit" window. One button zooms in on another.

### ISSUE THREAD

**Issue by glebmtb** [gitextensions/gitextensions#3379]
[install for instruction](https://github.com/gitextensions/gitextensions/wiki/Git-Extensions-on-Linux)
Ubunutu 16.04 amd64 
Mono 4.6.1.5/ef43c15
Git 2.7.4
GitExctensions 2.49RC2

I click on button "Commit" and open "Commit" window.
In "Commit window" one button zooms in on another.

![Commit window](http://joxi.ru/Drldb5h4LMPNrP.jpg)

**Comment by RussKie** [comment]
Is this still a problem with 2.50?
