### ISSUE TITLE
Settings -> Advanced, not all settings can be seen

### ISSUE THREAD

**Issue by glebmtb** [gitextensions/gitextensions#3380]
[install for instruction](https://github.com/gitextensions/gitextensions/wiki/Git-Extensions-on-Linux)
Ubunutu 16.04 amd64 
Mono 4.6.1.5/ef43c15
Git 2.7.4
GitExctensions 2.49RC2

I open settings (Tools -> Settings) and select "Advanced". Some settings I can be seen.
![Settings - Advanced](http://joxi.ru/gmvxbJsxkp99Aa.jpg)

After an increase in window, more settings can be seen
![Settings - Advanced](http://joxi.ru/EA4lX7SD3dgdAb.jpg)

In Settings-> Detailed as issue
![Settings - Detailed ](http://joxi.ru/YmEw9RfZ8ngZA6.jpg)

**Comment by ricjac** [comment]
+1
