### ISSUE TITLE
2.49RC2 Clean working directory single line log 

### ISSUE THREAD

**Issue by yesgrey** [gitextensions/gitextensions#3383]
Hi,
When doing a 'Clean working directory' command (both preview or the real command execution), the log is one single line. It seems the newline characters are not being added at the end of each line. See the image below:
![gitext_bug1](https://cloud.githubusercontent.com/assets/23011691/19693329/6732cee8-9adb-11e6-9914-41e0cc8bb47e.png)

Regards.

**Comment by ulrichb** [comment]
As of GitExt 2.49.03 and Git 2.12.0 this is broken again.

**Comment by KindDragon** [comment]
Cannot reproduce

**Comment by ulrichb** [comment]
Just had a look at the code. It only happens when deactivating the "Use Console Emulator for console output in command dialogs" setting.

(I had to disable the setting due to performance issues.)

**Comment by jbialobr** [comment]
>(I had to disable the setting due to performance issues.)

Could you report an issue describing the problems?
