### ISSUE TITLE
2.49RC2 History view weird column resizing

### ISSUE THREAD

**Issue by yesgrey** [gitextensions/gitextensions#3384]
Hi,
When I tried to resize the columns in the normal history view, something weird happens... If I try to resize any of the right columns (with the commit time, or the commit user Id) I get kind of a reverse behavior... If I resize the column to the right, the column increases to the letf, and the other way around.

This is odd, because with some combinations I end up not seeing any of the two columns, they completely disappear to the right... If I restart Git extensions then the columns show up again, so, at least it can be reverted, but it would be good to have the resizing working in the right way...
Here is an image after resizing the two columns:
![gitext_bug2](https://cloud.githubusercontent.com/assets/23011691/19693808/32b4adce-9add-11e6-84ab-3dd3282e95ed.png)

**Comment by asherber** [comment]
It would be nice if customizations were sticky, so that I can size the columns the way I want and not have them reset.

It would also be nice if there were a little space between the left edge and the commit graph, and between the right edge and the date or hash.

**Comment by RussKie** [comment]
Dup of #3447 #3580 #3603
