### ISSUE TITLE
Setup project fails to load

### ISSUE THREAD

**Issue by OmicronPersei** [gitextensions/gitextensions#3388]
In Visual Studio Community 2015, the Setup project fails to load when loading the solution.  I have Wix installed, but when I try to load the project, it says

> The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length. C:\GitRepos\gitextensions\Setup\Setup.wixproj

I'm on the master branch, commit `c040448890e24f9bb39f62b84a7b3bad64ffd7b8`.  I have pulled all submodules, and pulled all NuGet packages.  When I go to Manage Nuget Packages for Solution..., Wix is not listed.  Nor is wix one of the folders in .\packages\

The solution builds otherwise.

**Comment by KindDragon** [comment]
Install Wix Toolset http://wixtoolset.org/releases/

**Comment by OmicronPersei** [comment]
I already have v3.10 installed.

**Comment by OmicronPersei** [comment]
It appears that running GitExtensions.VS2015.build.cmd has done something to allow the setup project to load.  I have no idea what as no tracked files changed.  Is it worth investigating this for other users?

**Comment by vbjay** [comment]
You need to install wix toolset.

**Comment by OmicronPersei** [comment]
Didn't know that, thanks, lol.

**Comment by KindDragon** [comment]
Something with Wix from Nuget package. I don't know how help you, works fine for us.
Try restore it using commandline nuget maybe
