### ISSUE TITLE
Feature request: support 'git lfs <command>' for better LFS performance

### ISSUE THREAD

**Issue by amaiorano** [gitextensions/gitextensions#3389]
Git LFS works transparently by taking advantage of the attributes filter system to scrub/clean pointer files to retrieve the larger files from a separate store. The problem is that by default, this is slow because the attributes filter system only processes one file at a time, and is even slower on Windows due to process creation being long.

In Git LFS 1.2, they mitigated some of these performance issues by adding forwarding commands: git lfs checkout/clone/fetch/pull/push/status which forward to the usual git command, except it overrides the default filter system and does its own faster LFS work (parallel, single process).

Atlassian has a nice [writeup about it here](https://developer.atlassian.com/blog/2016/04/git-lfs-12-clone-faster/) and they are planning to integrate these commands in SourceTree so that it seamlessly uses the 'git lfs' versions of the aforementioned commands when it detects that the repo is using Git LFS. It would be great if Git Extensions could also do the same.

**Comment by KindDragon** [comment]
We have request #2968 about. Please add there this information
