### ISSUE TITLE
ConEmu settings

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#3392]
Using 2.49RC2

Is it possible to change somewhere the settings that the embedded ConEmu uses? I'd like to be able to change the font size to something smaller. Looking at other threads, it appears that this is not yet possible but may come in a later release; I'd just like to confirm that.

Thanks.

**Comment by OmicronPersei** [comment]
A small set of settings already appears to exist (essentially).  After launching the ConEmu, right click on the icon on the title bar, and click "Defaults".  The settings set there are saved as default.  Did you wish for more than this?

(Tested on a Windows 10 machine).

**Comment by asherber** [comment]
It sounds like you are launching the Git bash console, which opens by default in a Cmd window, and changing settings there. I'm talking about the embedded console tab in GitEx Browse:

![image](https://cloud.githubusercontent.com/assets/5248041/19991482/0a80abe2-a20c-11e6-969f-4553a164f478.png)

**Comment by OmicronPersei** [comment]
How exactly do you display the console there?  I can't find it anywhere.

**Comment by asherber** [comment]
Which version are you running? It's in the latest release candidates, as specified in my original post.

**Comment by OmicronPersei** [comment]
Apologies, I was looking at last installer (2.48.05).

Did you have anything in mind outside of just font?  Could start by using the `FontDialog` class.

**Comment by pmiossec** [comment]
Could you test or code review #3403 that is done to fix this issue and add some other settings.
That way it could be merged quicker...

**Comment by asherber** [comment]
Thanks, I'll take a look.

**Comment by asherber** [comment]
I played around with it, and it seemed to work fine. 

One small item: When I first opened the Details preference page, the font size field was not populated. It would be nice if it picked up the current font size, so that if I want to make it a little smaller or a little larger, I know where I'm starting from.

**Comment by asherber** [comment]
Is there a way to clear out the saved settings, so that I can try it again from scratch? I think when I started it the first time, the 'console style' said Default, but it was actually still using Solarized Light. I'd like to see if this is true, or if I'm misremembering.

**Comment by pmiossec** [comment]
>One small item: When I first opened the Details preference page, the font size field was not populated.

I have fixed that by setting the current v2.49 as the default values...

>Is there a way to clear out the saved settings

Settings are stored:
- "Global for all repositories" in `%userprofile%\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings`
- "Distributed with current repository" in `GitExtensions.settings` in the repository
- "Local for current repository"  in `.git\GitExtensions.settings`

**Comment by pmiossec** [comment]
For other comments about the PR, I think that's better to do it in the PR comment thread #3403 ....
