### ISSUE TITLE
Gitext Clone in Explorer Context Menu try to clone in the wrong folder

### ISSUE THREAD

**Issue by anrichter** [gitextensions/gitextensions#3394]
When i call the context menu "Gitext Clone" in a folder from within the Windows Explorer, the clone dialog try to create the new folder in the parent directory.

![gitextcloneinwrongdirectory](https://cloud.githubusercontent.com/assets/72196/19819761/73ca3038-9d56-11e6-9613-72d1c76728fd.png)

In my example i called clone from within the directory "C:\Users\anrichter\Src\3rdParty" and try to clone for example the gitextensions who should cloned into "C:\Users\anrichter\Src\3rdParty\gitextensions" and not into C:\Users\anrichter\Src\gitextensions"

I use version 2.49RC2 on Windows 10

Update: I don't have configured the Default clone destiation in the settings.
Maybe it's a good idea to clone the fill the From field with the URL in Clipboard. Just like when the clone dialog is called from the Gitextension UI.

**Comment by anrichter** [comment]
What about the fix in the PR? Is it not appropriate? Or do you have very little time?

Greetings, 
Andreas

**Comment by KindDragon** [comment]
@anrichter I asked question in that PR

**Comment by anrichter** [comment]
@KindDragon Hm. Your code review is 5 days ago but your question arrived me only last night. Strange...

**Comment by nul800sebastiaan** [comment]
@KindDragon What needs to be done to move this one along? The code is good, I've used it full time for 10 days now, very happy.

**Comment by KindDragon** [comment]
I am on business trip right now. I will try to build it and test upon return

**Comment by rexdf** [comment]
Is there a nightly build?  I need this patch but I don't want to clone this 500+M source code.

Or when the next release?
