### ISSUE TITLE
Merge command always add full branch name to commit message

### ISSUE THREAD

**Issue by KindDragon** [gitextensions/gitextensions#3400]
This happened after commit 89b3cf86d5cabed9858bca7a4eb99be7e4415faf
Example:

    Merge remote-tracking branch 'refs/remotes/origin/mono'

@jbialobr Maybe use full branch name only when refname conflict exist?
Also, I don't like that Merge and Rebase windows now always display branch name with `refs/`

**Comment by yesgrey** [comment]
If you change this, it would also be a good opportunity to do a simple cosmetic fix to give consistency to the comments...

Right now only the name of the branch that will be merged has '' surrounding the name. For example:
`Merge remote-tracking branch 'refs/remotes/origin/mono' into master`
and for consistency I would suggest:
`Merge remote-tracking branch 'refs/remotes/origin/mono' into 'master'`

**Comment by yesgrey** [comment]
ok, I will do it, thanks!
