### ISSUE TITLE
Commit message not Show !!!!

### ISSUE THREAD

**Issue by prachyanee** [gitextensions/gitextensions#3418]
--- GitExtensions2.49, Git 1.8.0.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

I was update to 2.49 then commit message are not show.
info
-I use Windows 7 Professional SP1

![image](https://cloud.githubusercontent.com/assets/13240480/20374657/a4f09fde-acac-11e6-9cd1-9426c7ae6fad.png)

**Comment by Radrik5** [comment]
Please try updating Git, 1.8.0 is very old version.

**Comment by prachyanee** [comment]
![image](https://cloud.githubusercontent.com/assets/13240480/20417250/b2e60212-ad76-11e6-9478-785590947bdf.png)

**Comment by prachyanee** [comment]
@Radrik5 Thank you, the solution was work for me.
