### ISSUE TITLE
The filter does not see the Russian text

### ISSUE THREAD

**Issue by andrey-helldar** [gitextensions/gitextensions#3419]
--- GitExtensions2.49, Git 2.10.1.windows.1, Microsoft Windows NT 6.3.9600.0

See [**Screenshot**](http://savepic.ru/12272124.png)

**Comment by andrey-helldar** [comment]
The same problem was in the version 2.48.

**Comment by RussKie** [comment]
Is this still a problem in the current version?

**Comment by andrey-helldar** [comment]
@RussKie No. The problem has been fixed since version 2.49.
