### ISSUE TITLE
Visibility of current branch in commit window

### ISSUE THREAD

**Issue by wsw70** [gitextensions/gitextensions#3420]
The commit window does not show the current branch we are about to commit to (which often leads to horrendous mistakes and hours of googling to revert that :))

I believe this should be prominently displayed next to the commit message, for instance

![Imgur](http://i.imgur.com/wjPiqWE.png)

**Comment by KindDragon** [comment]
Branch showed in dialog title

**Comment by mstv** [comment]
The branch is displayed in both the dialog title and the status bar in the meantime.
