### ISSUE TITLE
Linux: Remote repositories modal: 'Save changes' button not visible or disappears

### ISSUE THREAD

**Issue by ricjac** [gitextensions/gitextensions#3422]
To reproduce (this only occurs in Linux):
1) Start from the repository view
2) Menu: Repository -> Remote repositories...
3) "Save changes" button is not visible

The default size of the window seems to hide the "Save changes" and "Close" buttons. Then when I resize the window I still don't see the buttons.
But if I resize the windows large enough, close the window, then open it again, the two button are then visible.

[screenshot of the missing buttons](http://storage6.static.itmages.com/i/16/1118/h_1479432600_6187295_a5b7264e2e.png)

[screenshot of buttons reappearing](http://storage2.static.itmages.com/i/16/1118/h_1479450849_7127549_a7ad83ab70.png)

**Comment by RussKie** [comment]
Is this still a problem with 2.50?

**Comment by ricjac** [comment]
The issue might have been with the scaling I had on.
I'm using 2.50.01 now, and the "save changes" button is no visible, but doesn't lock to the edge of the window (when resizing)

**Comment by RussKie** [comment]
The form has been reworked and redesigned.

This is how it looks on Windows (putty disabled)
![image](https://user-images.githubusercontent.com/4403806/29444800-d780f100-8425-11e7-96e9-c08a1f7b8f9a.png)
