### ISSUE TITLE
Visual Studio 2008 AddIn isn't working anymore

### ISSUE THREAD

**Issue by TymurGubayev** [gitextensions/gitextensions#3423]
Visual Studio 2008 AddIn isn't working anymore, the one provided with previous version of GitExtension did.

**Comment by vbjay** [comment]
If you're still using 2008, that is your problem.

**Comment by KindDragon** [comment]
I'll try check this issue when I find where get VS2008

**Comment by vbjay** [comment]
https://www.visualstudio.com/vs/community/

**Comment by vbjay** [comment]
If you read the description of this repo it is pretty clear that it supports 2010 and up.

**Comment by TymurGubayev** [comment]
@KindDragon Here are some still working (amazingly) links to VS2008: http://stackoverflow.com/questions/17108102/download-and-install-visual-studio-2008

@vbjay 
![gitext_2 49_installer](https://cloud.githubusercontent.com/assets/348150/20443682/22b63786-adce-11e6-959b-d70cb587cf4c.jpg)

(BTW, still using VS2008 isn't where the real fun is. The real fun is still using Visual SourceSafe)

**Comment by vbjay** [comment]
Yuck. I feel for you. So we need to adjust the installer to not do a vs 2008 option for the plugin.
