### ISSUE TITLE
Branch rename does not autonormalise

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#3424]
Whenever a new branch is created its name is automatically normalised, if enabled (see #3233). 
However branch renaming does not normalise the branch name, which leads to an inconsistent UX.

**Comment by jbialobr** [comment]
Would you also be interested in adding the branch name normaliser to GitUI/CommandsDialogs/FormCheckoutBranch?

**Comment by RussKie** [comment]
sure thing, I'll have a look

On 25 November 2016 at 19:49, Janusz Białobrzewski <notifications@github.com

**Comment by vbjay** [comment]
What if the branch they want to checkout isn't normalized?

**Comment by RussKie** [comment]
@jbialobr do I understand it correctly that the auto normalisation should only be applied if a user chooses to create a local branch with a custom name?
![image](https://cloud.githubusercontent.com/assets/4403806/20640040/d08b3608-b428-11e6-8ecb-647d1be0bda3.png)

Any local or remote branches available in the dropdown already have valid names and there is no reason to normalise them again. Is that correct?

**Comment by jbialobr** [comment]
>@jbialobr do I understand it correctly that the auto normalisation should only be applied if a user chooses to create a local branch with a custom name?

Yes, it should be applied to that field.
