### ISSUE TITLE
2.49 Pushing to a different remote wrongly ask about new branch

### ISSUE THREAD

**Issue by Kryptos-FR** [gitextensions/gitextensions#3427]
Since 2.49, pushing to a different remote always ask to create the branch even though it does exist on the remote. This is a bit annoying that pushing cannot be done with a few clicks anymore.

![image](https://cloud.githubusercontent.com/assets/3006525/20472877/394fe8b4-b000-11e6-8d28-7eb51b86bad7.png)

Here is a summary of my git environment if that can help:
```
$ git lfs env
git-lfs/1.5.0 (GitHub; windows amd64; go 1.7.3; git 13fda8da)
git version 2.10.2.windows.1
```

**Comment by EbenZhang** [comment]
Probably introduced in #3403 

https://github.com/gitextensions/gitextensions/commit/613335552bf0735080e442629da1b71b99551d53#diff-5739d3c55c4406b36ad680719c7fc5f8R122 the remote.Push is empty in my case

**Comment by EbenZhang** [comment]
@jbialobr any reason in 75364f269a6646ddf59a27f205ed8d7fdbcb8da4 the `Module.GetRefs(tags: true, branches: true);` got changed to `Module.GetRefs(tags: false, branches: true)`. 
The former one returns the only local branches whereas the latter one returns tags, local branches and remote branches (the parameter names of `GetRefs` ars misleading).

**Comment by jbialobr** [comment]
Just did not need tags and got mislead...
