### ISSUE TITLE
Pressing the Windows key in Open or Clone dialog boxes crashes Git Extensions (KDE Neon + Mono)

### ISSUE THREAD

**Issue by eitland** [gitextensions/gitextensions#3428]
![screenshot_20161121_123414](https://cloud.githubusercontent.com/assets/83264/20481337/e8526360-afe6-11e6-9656-b7e1fa26585f.png)

Pressing the Windows key (to open the application launcher or as part of shortcut to take a screenshot) reliably crashes git extensions when either Open repository or Clone repository dialogs are open.

Haven't tested with other dialogs.

Output of mono --version:
Mono JIT compiler version 4.6.2 (Stable 4.6.2.7/08fd525 Mon Nov 14 12:30:00 UTC 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen

**Comment by eitland** [comment]
Update: Happens in clone Github repository dialog, Clone svn repository dialog and  Translate dialog as well. Might affect every dialog, I haven't tested more.

**Comment by RussKie** [comment]
Is this still a problem with the latest version?

**Comment by RussKie** [comment]
Closing due to age. Reopen if it is still an issue in the current version.

**Comment by eitland** [comment]
> Is this still a problem with the latest version?

Sorry I didn't see this. 

FWIW I can confirm that problem is gone now. Thanks!
