### ISSUE TITLE
Donate link doesn't work, PayPal says: "Sorry — your last action could not be completed"

### ISSUE THREAD

**Issue by eitland** [gitextensions/gitextensions#3429]
When trying out the donate link in the bottom left of the start screen:
![screenshot_20161121_124818](https://cloud.githubusercontent.com/assets/83264/20481704/d15978d6-afe8-11e6-9c3e-468f674e2a28.png)

I get this message from the PayPal website:
![screenshot_20161121_124543](https://cloud.githubusercontent.com/assets/83264/20481656/820ceba0-afe8-11e6-9460-ef583eb0b184.png)

**Comment by RussKie** [comment]
Please re-open if it is still an issue in the latest version
