### ISSUE TITLE
GitExtensions 2.49 much slower than 2.48.x

### ISSUE THREAD

**Issue by drauch** [gitextensions/gitextensions#3431]
Our company updated to GitExt 2.49 this week and we all realize heavy performance degradation. Dialogs are much slower, the UI semms to hang for a short time, especially after committing or after checking out a new branch (the progress modal dialog, which shows the git commands executed, seems to have gotten a lot slower).

Any ideas?

**Comment by Tankatronic** [comment]
I just wanted to say that I also experience the issue with the progress modal. That is the only noticeable slowdown that I have experienced, but every time I push a commit it hangs for ~30 seconds. It gets to this point

> "C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "origin" refs/heads/master:refs/heads/master
> Counting objects: 8, done.
> Delta compression using up to 8 threads.
> Compressing objects: 100% (8/8), done.
> Writing objects: 100% (8/8), 1.42 KiB | 0 bytes/s, done.
> Total 8 (delta 6), reused 0 (delta 0)

Then hangs there for 30 seconds, and then finally finishes with

> To http://[redacted].git
>    3d61cfb..2f7d173  master -> master
> Done
> 
> Press Enter or Esc to close console...

**Comment by KindDragon** [comment]
Try disable option "Use Console Emulator..." on Advanced page (Settings dialog)

**Comment by drauch** [comment]
@Tankatronic : that is also an issue, but different to mine. Unfortunately, the overall experience slowed down by a huge margin.

**Comment by drauch** [comment]
@KindDragon : This looks like it brings back the performance. Do you know what kind of downsides this setting has?

**Comment by miparnisari** [comment]
Mine looks like it hangs the first time I open it. It gets stuck executing `where.exe` for a few seconds.

**Comment by Tankatronic** [comment]
@KindDragon I'll create another issue since this seems to be unrelated, but disabling the Use Console Emulator option did not fix my issue

**Comment by jbialobr** [comment]
@Tankatronic Can you perform push from git bash to see how long it takes outside of the GitExtensions?

**Comment by KindDragon** [comment]
> Do you know what kind of downsides this setting has?

Check PR #3152

**Comment by Kuba15** [comment]
Hi,
I just updated to 2.49 and I confirm that it became extremely slow compared to 2.48.
I disabled the "Use Console Emulator..." and "Show repository status" as mentioned in #3433, but it remains very slow.
I noticed that when selecting a commit, the UI often freezes, which was not the case in 2.48. 
Especially when selecting it for the first time. The same goes when displaying the Diff, file tree, etc.

**Comment by RussKie** [comment]
Is this still an issue with 2.50?

**Comment by OvestLabs** [comment]
@RussKie, I have 2.50.01 and it works fine for me.

**Comment by VsevolodGolovanov** [comment]
> every time I push a commit it hangs for ~30 seconds.

With GitExt 2.50.02 pushes take 65-68 seconds for me - measured when the branches were up-to-update.
I tried closing GitExt, made sure that there weren't any git processses left, started the same push command like what GitExt does from a simple command line - same thing, 65-68 sec.
Tried without the `--recurse-submodules=check --progress` part - no difference.
So it seems the problem is in Git itself. `git version` reports 2.13.2.windows.1.

**Comment by RussKie** [comment]
@VsevolodGolovanov so do you think it is the git issue?

**Comment by VsevolodGolovanov** [comment]
@RussKie, yes.

**Comment by vbjay** [comment]
Try upgrading git.

**Comment by VsevolodGolovanov** [comment]
@vbjay, I did:
> Git for Windows 2.14.2(3): the problem remains.

**Comment by vbjay** [comment]
OK. Well gitextensions has moved on to a newer version.
