### ISSUE TITLE
Hotkeys lost in 2.49

### ISSUE THREAD

**Issue by chrischu** [gitextensions/gitextensions#3432]
Unfortunately it seems as if (at least) some hotkeys (e.g. hotkeys for scripts) were lost after upgrading from 2.48 to 2.49. 

That is probably not something that can be fixed retroactively, but it would be good if future version upgrades would not lose hotkeys again.

**Comment by jbialobr** [comment]
It seems that hotkeys are lost every time the default configuration changes. That means every time a new hotkey is added!
https://github.com/gitextensions/gitextensions/blob/44e8fbbb0d8dc13ed1be32b4d97f413feba7fc01/GitUI/Hotkey/HotkeySettingsManager.cs#L83
That needs to be corrected before 2.50 is released.
