### ISSUE TITLE
GitExtensions slow loading commit history

### ISSUE THREAD

**Issue by toddwz** [gitextensions/gitextensions#3433]
![gitext](https://cloud.githubusercontent.com/assets/23662789/20536130/e38370b6-b0b5-11e6-948d-242abd4435c1.jpg)

Git Extensions is very slow loading commit history of large repo. Looking at log, it does many things except running git log. Is it possible to speedup by removing unnecessary operations if any? Thanks.

**Comment by KindDragon** [comment]
Try disable "Show repository status" in Settings dialog (Git Extensions page)

**Comment by RussKie** [comment]
Please install v3.
