### ISSUE TITLE
Filtering commits by unicode search text fails

### ISSUE THREAD

**Issue by maliayas** [gitextensions/gitextensions#3434]
This happens both with the toolbar filter and the filter window.

1. Use, for example, the Turkish word `sayfası` in a commit message (note the last character, which is not "i")
2. Filter by `sayfası` using the 2 filter methods.
3. Filtering lists irrelevant results.

If I delete the last character from the search text (`sayfas`), everything works fine. Using characters such as "üğişçöı" in search string breaks filtering.

This maybe related to #2771

Thanks in advance.

GitExtensions version: 2.49

**Comment by jbialobr** [comment]
What is your git version?

**Comment by maliayas** [comment]
It's 2.9.2.windows.1

**Comment by KindDragon** [comment]
Related to #3419

**Comment by KindDragon** [comment]
Will it work from command line http://stackoverflow.com/a/7124949 ?

**Comment by maliayas** [comment]
Yep, works fine from the command line.

**Comment by maliayas** [comment]
Confirmed it works in the new release v2.49.01. Thanks!
