### ISSUE TITLE
Pushing commits causes the progress window to hang in version 2.49

### ISSUE THREAD

**Issue by Tankatronic** [gitextensions/gitextensions#3435]
This issue popped up with the new update for me. I have tried disabling the "Use Console Emulator" option but the behavior is the same. If I just commit, fetch, pull, merge, or stash the issue does not occur. It only occurs when pushing. Below is text from the progress window:

>     "C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "origin" refs/heads/master:refs/heads/master
>     Counting objects: 8, done.
>     Delta compression using up to 8 threads.
>     Compressing objects: 100% (8/8), done.
>     Writing objects: 100% (8/8), 1.42 KiB | 0 bytes/s, done.
>     Total 8 (delta 6), reused 0 (delta 0)

Then hangs there for 30 seconds, and then finally finishes with

>     To http://[redacted].git
>     3d61cfb..2f7d173 master -> master
>     Done
>     Press Enter or Esc to close console...

**Comment by jbialobr** [comment]
@Tankatronic Can you perform push from git bash to see how long it takes outside of the GitExtensions?

**Comment by Tankatronic** [comment]
It is happening as well outside of git extensions. Might be something going on in our network here.
