### ISSUE TITLE
Version 2.49 - Text in history tree not shown

### ISSUE THREAD

**Issue by Isgam** [gitextensions/gitextensions#3436]
Hi,

I installed new release 2.49 on Windows 10, 64Bit, anniversary update. 

But now the history tree commit text is not shown or has a white color on white background. But the commit user and date are shown.

And I didn't find any option to Change the text color.

Exists any solution or workaround for?

![image](https://cloud.githubusercontent.com/assets/3491875/20573195/f7634ea4-b1ae-11e6-8c99-8cffc3e2fedd.png)

Best regards
Isgam

**Comment by Isgam** [comment]
Update: 
 - Version 2.48.05 ok
 - Version 2.49RC1 not ok
 - Version 2.49RC2 not ok

**Comment by Radrik5** [comment]
See #3418

**Comment by KindDragon** [comment]
Which git version are you using?

**Comment by Isgam** [comment]
Hi, Radrik5 ticket solved the issue. I'm using a too old version of git.
Thanks a lot for your help!

**Comment by FrancisCoulombe** [comment]
I have this same issue as described here, and I am using the latest version of git. The history tree view shows none of the commit messages.

**Comment by RussKie** [comment]
What is your git version?

**Comment by FrancisCoulombe** [comment]
Oh dang, never mind, just realized people were asking about the git version, not the gitextensions version! It works fine now, thanks!
