### ISSUE TITLE
ConEmu Exception 0xC0000005

### ISSUE THREAD

**Issue by blackbirdui** [gitextensions/gitextensions#3444]
I see this error message any time I perform any Git Extensions operation (commit, push, pull, merge, etc).  Version 2.49.  The operations appear to be completing successfully, and this message box pops up for a few moments then dismisses itself.

MESSAGE:
-------------------------------
Exception 0xC0000005 (DEP x064574AC) was occurred (ConEmuC.exe, PID=7968)
ConEmu build 161009a 

Memory dump was saved to
C:\[...]\ConEmuTrap\Trap-161009a-7968.dmp

Please Zip it and send to developer (via DropBox etc.)
https://conemu.github.io/en/Issues.html

Press <Yes> to copy this text to clipboard
and open project web page

INFO FROM DUMP:
-------------------------------
Process Name: ConEmuC.exe: C:\Program Files (x86)\GitExtensions\ConEmu\ConEmuC.exe
Process Architecture: x86
Exception Code: 0xC0000005
Exception Information: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

**Comment by KindDragon** [comment]
You can disable ConEnu integration in GitExt settings.
Pls report this issue to ConEmu as described in https://conemu.github.io/en/Issues.html or attach memory dump here

**Comment by blackbirdui** [comment]
Got it.  Thanks.
