### ISSUE TITLE
Kdiff3 Replacement.

### ISSUE THREAD

**Issue by agustinbcu01** [gitextensions/gitextensions#3446]
I Love your this project but. Look like Kdiff3 project is dead or almost dead. I having issues merging conflicts, because Kdiff3 changes my end Lines from Windows to Linux style. We spend a lot of time changing the end lines back.

Regards

**Comment by marazt** [comment]
Little off-topic from me. It is really almost dead project? Because after years of using various diff/merge tools, Kdiff3 became my favorite one.

**Comment by vbjay** [comment]
Check p4 merge.

**Comment by KindDragon** [comment]
You can use any diff/merge tool you want with GitExt, but I think KDiff3 is safe and free default merge tool for GitExt.

**Comment by RussKie** [comment]
P4merge is free too https://www.perforce.com/product/components/perforce-visual-merge-and-diff-tools

**Comment by ghanique** [comment]
The main difference between KDiff3 and P4 is that KDiff keeps differences
side by side (by introducing gray-space) and P4 doesn't. P4 has this bar
between the left and right side that you have to visually track to figure
out what lines on the left belong to what lines on the right, which to me
completely obfuscates exactly what changed, defeating its purpose.

But if you like P4 install it yourself. Git Extensions lets you select P4
as your favorite diff viewer in its settings with a simple drop down box.

The idea is that Git Extension provides at least one diff viewer. I
wouldn't put in any effort replacing it with another one if the user can
select another one after installation. (The user can even opt to install
KDiff, but doesn't have to).

**Comment by RussKie** [comment]
As @sharwell found and discussed in https://github.com/gitextensions/gitextensions/issues/2745#issuecomment-322458078 KDiff3 makes it harder to simplify and streamline setting up the Setup project.
However P4merge is available in chocolatey feed.

@KindDragon @jbialobr should we consider replacing KDiff3 with P4merge?

**Comment by vbjay** [comment]
Amen. I use p4merge.

**Comment by KindDragon** [comment]
> @KindDragon @jbialobr should we consider replacing KDiff3 with P4merge?

As I mentioned here https://github.com/gitextensions/gitextensions/issues/3446#issuecomment-263678408 and here https://github.com/gitextensions/gitextensions/pull/3353#issuecomment-254644329 I prefer KDiff3

**Comment by RussKie** [comment]
@vbjay we have to revolt now! 😀 

on a serious note, should we create a separate setup package which packages p4merge?
it is a problem for our users - none of them like kdiff3. unfortunately most of users don't have ability to install anything themselves and their installs are managed by the corporate IT. 
it is significantly easier to request a single application packages (GE) then manage multiple requests for packaging and then direct users to request correct apps in correct order...

**Comment by vbjay** [comment]
We could have a page in the setup that picks p4Merge or kDiff. We could
even preconfigure the diff and merge tools in Git Extensions.

**Comment by RussKie** [comment]
I think if we start bundling both kdiff3 and p4merge the size of the setup file will double... which won't be a good thing

**Comment by vbjay** [comment]
I think if we have a download feature, it would be fine. Pick p4merge and
it downloads p4merge and installs it. Same for kDiff. We could have a file
in the repo that points to the location to download from.

**Comment by RussKie** [comment]
It won't for user behind corporate proxies with limited rights

**Comment by vbjay** [comment]
Is there a portable p4Merge and kDiff?  We could do the same thing we did
with gource.
