### ISSUE TITLE
unable to expand columns in commit view layout

### ISSUE THREAD

**Issue by planetbrett** [gitextensions/gitextensions#3447]
--- GitExtensions2.49, Git 2.10.1.windows.1, Microsoft Windows NT 6.3.9600.0

I can shorten the column width but am not able to make them larger.  The SHA column is cut off.  see attached img.

![image](https://cloud.githubusercontent.com/assets/3485009/20727054/f93c42b2-b645-11e6-8a13-86431d0baf9d.png)

**Comment by pmiossec** [comment]
Managing columns width in an ergonomic way has never been very good...
But I think that you should reduce the comment column (which is not dsiplayed in your printscreen) to give more width to the last column.

**Comment by RussKie** [comment]
dup of #3580 #3603

**Comment by RussKie** [comment]
Can you please verify if it is still an issue in the latest version?

**Comment by KindDragon** [comment]
Duplicate of #3580 #3603

**Comment by pmiossec** [comment]
Still there in 2.50.1 but as I said **the solution is to reduce the size of the 'comment' column**.
