### ISSUE TITLE
Merging issue

### ISSUE THREAD

**Issue by swethakini** [gitextensions/gitextensions#3448]
--- GitExtensions2.47.3, Git 1.9.4.msysgit.0, Microsoft Windows NT 6.1.7601 Service Pack 1

I am working on wpf C# project, Today when I was trying to merging from two separate branches into new branch, I could see Git merged duplicate lines of code.

**Comment by EbenZhang** [comment]
I believe it is something to do with git itself. Can you try the command line directly and see if any difference?

**Comment by jbialobr** [comment]
Please update git to the latest version.
