### ISSUE TITLE
Different environments and color schemes between Console tab and Git Bash

### ISSUE THREAD

**Issue by KrzysFR** [gitextensions/gitextensions#3449]
After upgrading to 2.49, I'm getting a weird ugly pale brown color (#EEE8D5) as the background color of the Console tab (and conemu embedded in popups when git is working), but regular colors when launching the git bash.

Also, I noticed that I get either MINGW32 for the Console tab, and MINGW64 for the git bash. Also, "git --version" return different values (GitExtension has 2.10.1 but I also have VS2017RC that redist 2.9.0.windows.1)

Does anyone have an idea of what setting can revert the colors to regular (black background), and why am I getting to different environments? (MINGW 32 vs 64, difference in PATHs, ...?)

When opening the Console tab (same look with the conemu embedded in popups btw)
![image](https://cloud.githubusercontent.com/assets/1662235/20837534/c9045ad8-b8a4-11e6-8e37-be868aff05a7.png)
_here it uses the git installed by git-extension in `C:\Program Files (x86)\Git`_

When pressing CTRL-G (or clicking on the "git bash" icon in the toolbar)
![image](https://cloud.githubusercontent.com/assets/1662235/20837544/d71fb7fc-b8a4-11e6-9edd-197886586489.png)
_(this time, it uses the git installed by VS 2017 RC which is in `C:\Program Files\Git`)_

Git settings:
![image](https://cloud.githubusercontent.com/assets/1662235/20837762/cd1a2458-b8a5-11e6-81e8-676fa77db98f.png)

![image](https://cloud.githubusercontent.com/assets/1662235/20837771/dccd113a-b8a5-11e6-9a14-bf94c2b3096e.png)

**Comment by Radrik5** [comment]
Similar to #3392.
As for different versions, probably the Git Bash button launches bash.exe without specifying full path. And the system uses one that goes first in PATH. Anyway, I'd suggest to uninstall one of them.

**Comment by pmiossec** [comment]
For the color scheme problem, that's explained by the fact that GitExtensions is using ConEmu, which use its own styles, whereas the the "open a console" feature just launch the `bash` console installed by git and which come with there own style.

The both are distincts and won't be able to share or mimic the settings of the other. So we have to play with the ConEu settings...

The default ConEmu settings is a dark blue but the clearer ConEmu theme (that I'm not very fond of, too...) has been explicitely choosen for all the opened console in GitExtensions...

If you want to be able to choose a dark theme, feel free to test #3403, even do a code review and push to merge it...

**Comment by KrzysFR** [comment]
Thanks for the explanation.

I don't really care that much about the difference in environment: if they both work fine, then it's probably not that big a deal.

I prefer having a separate place for git so that Visual Studio and git-extensions can be isolated from each other. I've had issues in the past (most recently with the VS 15 previews) where I had to repair or reinstall git-extensions that stopped working after updating VS.

But I'll definitely try the PR you linked, because I'm not a big fan of the "Solarize Light" theme, and my first reaction was that some settings were probably corrupted somewhere... :)
