### ISSUE TITLE
Mono: Commit window loading does not finish 

### ISSUE THREAD

**Issue by thorade** [gitextensions/gitextensions#3455]
On Xubuntu 16.04 with GitExtensions 2.49, when I changed some files the main window shows the correct number of changed files, but when I open the commit window, it only says "Loading" forever.

![Image of Commit Window](http://imgur.com/ioRXkcFl.png)

**Comment by thorade** [comment]
Closing, because there are ~650 open issues.
For now, I switched to GitKraken on Linux, using GitExtensions on Win10 only.

**Comment by navisjayaseelan** [comment]
Solution:
It is old mono version error.

Follow the steps to upgrade

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/mono-official.list
sudo apt-get update
sudo apt-get install mono-devel

And run the gitextensions with mono you will not get any error.
