### ISSUE TITLE
Hidden button on the Checkout branch modal window

### ISSUE THREAD

**Issue by denis-pujdak** [gitextensions/gitextensions#3461]
--- GitExtensions2.49, Git 2.8.1.windows.1, Microsoft Windows NT 6.3.9600.0

![2016-12-14 2](https://cloud.githubusercontent.com/assets/12826797/21188146/484b38f4-c212-11e6-9cf4-042c5562f366.png)

**Comment by RussKie** [comment]
Please install latest GE and try again.
Re-open if you still experience the issue.
