### ISSUE TITLE
Background fetch plugin - Not working

### ISSUE THREAD

**Issue by tomlaf** [gitextensions/gitextensions#3464]
Good day

I have it setup and the command work manually, but I does not trigger automaticlly.

We just compteled update to 2.47 from 2.44. (It was working fine on 2.44)

![image](https://cloud.githubusercontent.com/assets/8548490/21326073/2911de3c-c5f7-11e6-91ed-7d9bdb134042.png)

--- GitExtensions2.49, Git 2.10.2.windows.1, Microsoft Windows NT 6.3.9600.0

**Comment by azarkevich** [comment]
I found, that in my case background fetch was blocked by hung git.exe process. If background fetch detect running git process or index locked - it skip interval.
