### ISSUE TITLE
Usability improvements to "Compare with current branch"

### ISSUE THREAD

**Issue by shift-evgeny** [gitextensions/gitextensions#3465]
The "Compare with current branch" function in 2.49 is very useful, but the results confused me at first, because the two branches were the "wrong" way around, i.e. the base branch was not the one I expected.  I had a "feature_x" branch created from the "develop" branch. While on "develop" I selected the latest commit in origin/feature_x and chose "Compare with current branch". Since "feature_x" was branched from "develop" I naturally expected "develop" to be the base branch, but in fact "feature_x" was chosen as the base. Part of the problem was that the text shown under "BASE" is the commit message and not the name of the branch, so it wasn't immediately clear which branch was the base.

I suggest 3 usability improvements to this feature:

1) Automatically detect if one of the two branches was branched from the other and, if so, choose the "parent" branch as "BASE".
2) Show the branch name as well as the commit message in the branch description, e.g. "develop: this is the commit we branched from" and "feature_x: current commit in on feature X".
3) Remember the state of the "Compare to merge base" checkbox.

**Comment by Radrik5** [comment]
I don't think there is a way to implement (1) in a reliable way.

**Comment by shift-evgeny** [comment]
What about simply running `git merge-base --is-ancestor BRANCH1 BRANCH2` ? If it returns 1 then BRANCH1 is the base, if it returns 0 then BRANCH2 is the base.

**Comment by Radrik5** [comment]
> What about simply running git merge-base --is-ancestor BRANCH1 BRANCH2 ? If it returns 1 then BRANCH1 is the base, if it returns 0 then BRANCH2 is the base.

This works until you have new commit in BRANCH1. It's not the same as "one of the two branches **was** branched from the other" or I misunderstood your point.

**Comment by shift-evgeny** [comment]
Of course, I have new commits in both branches and it seems to work. Git Extensions already uses `git merge-base` when I check "Compare to merge base", right? This just re-uses the same command to figure out which of the two branches is the base.

**Comment by vbjay** [comment]
It's not that simple. What if a branch has already been merged and has
other commits.

**Comment by shift-evgeny** [comment]
Indeed, in that case ` git merge-base --is-ancestor` returns 1 both for "BRANCH1 BRANCH2" and for "BRANCH2 BRANCH1". :( As http://stackoverflow.com/questions/17581026/where-does-a-git-branch-start-and-what-is-its-length explains, git doesn't actually record where a branch was created from, so I have to conclude that @Radrik5 is right and there is no reliable way to do this. I guess Git Extensions could still make some effort to do this where it can, so if `merge-base --is-ancestor` returns 1 one way and 0 the other way then it knows which is the BASE.

It could also remember which of the two branches the user chose as BASE last time and automatically select that one the next time. (I often compare the same feature branch many times as changes are made in a code review and it gets annoying having to swap them every time.) That would work nicely with point 3.
