### ISSUE TITLE
Suporting Visual Studio 2017

### ISSUE THREAD

**Issue by itsho** [gitextensions/gitextensions#3466]
Hi.

I really love this tool. keep up the good work.

Are you planning to support VS2017?

thanks!

**Comment by pmiossec** [comment]
I think there is  a pull request for that... #3439
If you are able to test it and give feedback, it will help...

**Comment by itsho** [comment]
I've installed it but I couldn't find the toolbar.
![2016-12-24 20_12_08-microsoft visual studio 2017rc](https://cloud.githubusercontent.com/assets/1774797/21468349/5645ffc4-ca15-11e6-8121-e06df75fc14a.png)

**Comment by iamwyza** [comment]
@itsho Check out the most recent post on #3439.  For some reason when I installed the VSIX it defaulted to "Disabled".  That post lets you know where to enable it.

**Comment by TomGui** [comment]
I also have this question.

**Comment by phillijw** [comment]
Welp. VS2017 released today. Time to start testing this change

**Comment by sabby62** [comment]
How can I install Git Extensions for VS2017 ? Will 2.49 setup automatically installs it for VS2017 ?

**Comment by patton88** [comment]
I really love this tool. keep up the good work.
When are you planning to support VS2017?

**Comment by phillijw** [comment]
Just updated #3439

**Comment by patton88** [comment]
Thanks phillijw. I has success installed with GitExtensions-2.49.02 and  GitExtensionsVSIX-3439.vsix.
