### ISSUE TITLE
Feature proposal (possibly as plugin): Autocomplete / "find as you type" issue tracker lookup in commit message editor

### ISSUE THREAD

**Issue by paranoidandroid522** [gitextensions/gitextensions#3468]
It would be cool if I could somehow easily search for issues in my issue tracker (e.g. Redmine) while typing a commit message, so that I can add a ticket number (e.g.` #1234`) to the message without having to open the browser, navigate to my issue tracker, search for the ticket and copy/paste the issue number to the message. 

For example, if I type a hashtag ("#") in the commit message (which in my workflow is almost always followed by an issue number), I would love to see an autocomplete-type dialog, which will search the text I enter after the "#" in my issue tracker and offer to replace the text by a ticket number.

I think most issue trackers provide an HTTP API for searching tickets to facilitate something like this. It would probably make sense to implement this feature as a plugin hook so that adapters for various issue tracking systems can be added. A configuration UI for each plugin (for base URL, authentication etc.) would also be required. 

I know this is a big one, but it would be a HUGE timesaver and make GitExt even cooler than it already is :-).

**Comment by Radrik5** [comment]
Go ahead, it's open source :)
