### ISSUE TITLE
when installing Gitextension  2.49 setup_complete instalation error

### ISSUE THREAD

**Issue by dugler1990** [gitextensions/gitextensions#3469]
when installing Gitextension  2.49 setup_complete,  I get an error saying "There is a problem with the Windows installer package, A program run as part of the setup did not finish as expected. Contact youñre support personel or package vendor” .

I have tried With both Git and Kdif uninstalled prior, installing new versions from the wizard and have also tried having them installed and going straight to the instalation of git extensions.

has anyone encountered this? any help is much appreciated.

**Comment by anguiano** [comment]
I have the same problem with both installer (GitExtensions-2.49-Setup, GitExtensions-2.49-SetupComplete).  My SO Windows 7 Home premium 64bits

My solution: 
I had to install the version 2.48.05-Setup

**Comment by scorpeeon** [comment]
Same here.

**Comment by dugler1990** [comment]
Awesome, worked for me too. 
thanks anguiano

**Comment by Memnarch** [comment]
Try disabling the VisualStudio plugins in the setup! That was my problem

**Comment by pobrob** [comment]
That worked for me as well

**Comment by jbialobr** [comment]
Can you run the following command and upload the generated log file?

`msiexec /i GitExtensions-2.49.03-Setup.msi /l*v MyLogFile.txt`
