### ISSUE TITLE
Cannot push to UNC path. 

### ISSUE THREAD

**Issue by rlholland** [gitextensions/gitextensions#3474]
--- GitExtensions2.49, Git 2.11.0.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

Is there a way to have GitExtensions recognize the UNC path that is listed as the URL in the .git/config file?

**The URL line of my .git/config file**:
**_This does not work_**.
        url = //bhs/groups/BCC_1/cerner/Millennium/mpage/gitrepositories/azb_custom_components.git

**_This works_**.
        url = B:/Millennium/mpage/gitrepositories/azb_custom_components.git

I don't have a Git web server setup so I have all of my repositories on a Windows share and I push to them using the UNC path instead of SSH:// or some other method. 

![image](https://cloud.githubusercontent.com/assets/7946572/21532333/6845309c-cd0c-11e6-9d6a-b34d06c7eb2d.png)

I have a work-around for pushing to the network share by mapping a drive letter to the repository then I am able to push. I currently have 185 repositories that I will have to change to use the mapped drive letter instead of using the UNC path if GitExtesions is unable to recognize UNC paths.

![image](https://cloud.githubusercontent.com/assets/7946572/21532355/94ddc038-cd0c-11e6-81dc-2743835eb0e5.png)

**Comment by vbjay** [comment]
Did you try the full file:// protocol.

**Comment by rlholland** [comment]
The URL line in my .git/config file now looks like this:
	url = file://bhs/groups/BCC_1/cerner/Millennium/mpage/gitrepositories/azb_custom_components.git

When I attempted to push it failed, showing this:
![image](https://cloud.githubusercontent.com/assets/7946572/21534495/2d22c47a-cd25-11e6-98df-51deb231282e.png)

Am I using file:// correctly?

**Comment by vbjay** [comment]
Why are you storing git repos in program files?  NTFS doesn't allow non
admins to write to those files.

**Comment by rlholland** [comment]
I 'm not storing any repositories in "Program Files". That "Program Files" in my screenshot showed up when I put "file://" in the URL like you suggested (I noted that in the red bubble on the screenshot). I think "file://" means the same thing as "C:/Program Files" or at least it defaulted to that path. The repositories are still out on the network share and it seems the only way I can write to them is by using a mapped drive letter. By the way, I am also an admin on my computer.

**Comment by rlholland** [comment]
Found this comment on [StackOverflow](http://stackoverflow.com/questions/20992616/git-push-fail-to-a-windows-share). It links to [this line of code of mingw.c](https://github.com/git/git/blob/35f6318d44379452d8d33e880d8df0267b4a0cd0/compat/mingw.c#L2018).
**With the next Git 2.12 (Q1 2017)**, you should be able to use a path (without having to use the IP address for referencing the server)

See commit 7814fbe (14 Dec 2016) by Johannes Sixt (j6t). (Merged by Junio C Hamano -- gitster -- in commit 4833b7e, 19 Dec 2016)

normalize_path_copy(): fix pushing to //server/share/dir on Windows

normalize_path_copy() is not prepared to keep the double-slash of a  //server/share/dir kind of path, but treats it like a regular POSIX style path and transforms it to /server/share/dir.

The bug manifests when 'git push //server/share/dir master' is run, because tmp_objdir_add_as_alternate() uses the path in normalized form when it registers the quarantine object database via  link_alt_odb_entries(). Needless to say that the directory cannot be accessed using the wrongly normalized path.

Fix it by skipping all of the root part, not just a potential drive prefix. offset_1st_component takes care of this, see the implementation in compat/mingw.c::mingw_offset_1st_component().

**Comment by rlholland** [comment]
I think I partially solved the inability to push to a UNC path by installing the GitHub Desktop application. I can now push to a UNC path from the command line and Github client but still not from GitExtensions.

**Comment by vbjay** [comment]
Git is a.posix system. You must use /. If you use \ in the path you have to
escape it with another.

**Comment by vbjay** [comment]
http://stackoverflow.com/questions/4998549/git-on-unc-path

**Comment by rlholland** [comment]
vbjay, I am not sure if you are actually reading my posts but you are proposing solutions that I have already tried. I am using the "/" and if you escape it with "\" in the config file you will get errors. You can try it if you like. 

Your link to the Stackoverflow post about "git-on-unc-path" suggests using a mapped drive letter. I have already mentioned that I was successfully using a mapped drive letter in my very first post. Take a look at the second screenshot. 

Finally, I realized that out of all of this troubleshooting I failed to reboot my computer after installing Git Extensions and GitHub Desktop. The problem is completely solved and I can now push to a UNC path. I just had to reboot.
