### ISSUE TITLE
pull dropdown and dialog should have a --ff-only choice

### ISSUE THREAD

**Issue by bughit** [gitextensions/gitextensions#3475]
If you've forgotten you have local commits its good to be reminded on pull, making --ff-only a good pull default.

**Comment by Radrik5** [comment]
What do you do with local commits? Merge or rebase? Git Extensions has both options in the pull dialog.

**Comment by bughit** [comment]
When I know I have them an I intend to push them then I will choose one of those.  But when I am not cognizant of local commits and just want to get latest, I always do --ff-only and so get reminded.

**Comment by alexDevBR** [comment]
I think this would be a great feature! I'd leave this as the default option. You don't have to stop and think  in order to keep your repository up to date, just click. If it's a FF it's automatically merged. If not, it just gets fetched and you can see the graph and decide if you want to merge, rebase or something else.

**Comment by vbjay** [comment]
Just an fyi. That is what fetch is for.  You fetch and look at the grid and figure out if you want to merge.  Then you do the merge/rebase locally.

**Comment by bughit** [comment]
periodic background fetch has nothing to do with this issue, the operation being discussed is the on-demand updating of the current branch

The manual fetch is not adequate because AFAICT it just fetches and closes. The behavior one is looking for from --ff-only pull feature as @alexDevBR pointed out is to ff and if it can't, prompt, which will remind you that you have commits which you can then interactively choose to merge, rebase, or abort.

**Comment by vbjay** [comment]
Result after a fetch, minus the origin push.  
![image](https://user-images.githubusercontent.com/3629489/45503653-73573b80-b755-11e8-81a1-6d82f7677ed6.png)

I agree.  However.  My point is that let's say I hadn't pushed origin yet and it was where master is now.  I would see upstream/master had commits I did not merge in yet and could compare the work and when ready, right click upstream/master and merge into my local master.  
![image](https://user-images.githubusercontent.com/3629489/45503613-5c184e00-b755-11e8-8d8f-754fd0ed8c90.png)


I NEVER pull.  I always fetch and verify the commits and then merge locally.  A pull is just a fetch and merge/rebase(depends on which option you chose.) together.

**Comment by vbjay** [comment]
Not to mention you can rebase your branch on top of the remote branch.  Then you will never lose a commit from your local work.

**Comment by bughit** [comment]
> I NEVER pull

So why are you flooding an issue for enhancing pull functionality? This isn't a "never pull" advocacy forum.

**Comment by vbjay** [comment]
Pointing out that if you want to be mindful and not lose your local work
then do a fetch and then rebase on the remote branch head.  Your work will
get replayed on top of the existing work in the remote.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/45512136-df916980-b76c-11e8-95f3-9473ca67c66c.png)
![image](https://user-images.githubusercontent.com/3629489/45512153-f041df80-b76c-11e8-8333-c278156eea91.png)
![image](https://user-images.githubusercontent.com/3629489/45512171-fcc63800-b76c-11e8-97ec-5117ddec3e22.png)
![image](https://user-images.githubusercontent.com/3629489/45512208-1e272400-b76d-11e8-84f7-a7845cb2bbb3.png)
See how that works?

**Comment by gerhardol** [comment]
This is a reasonable feature request, you can work in many ways with Git.
However, GE has many options already, overwhelming some users already.
I would not vote against a PR even if I am not enthusiastic.

fetch is easier to explain and therefore a more reasonable recommended workflow.

**Comment by vbjay** [comment]
In not disagreeing with you. In pointing out a workflow that makes sure you
are in control of it all. The other benefit is you can do this for offline
work
git fetch --all
git submodule foreach --recursive git fetch --all

Then you can merge rebase....whatever even if you don't have internet
access.

**Comment by alexDevBR** [comment]
I will be submitting a PR for this soon. Ideally I wanted to add an "FF Only" checkbox next to the Merge menuItem, but in keeping with the existing layout I thought it was easier to just add another menuItem:
![image](https://user-images.githubusercontent.com/4670339/47239031-7e3b6680-d3ba-11e8-9cad-c4660a896f85.png)

**Comment by drewnoakes** [comment]
@alexDevBR even though it's lengthier, consider adding "fast-forward only" in the menu item text, in full. It's more likely to help people unfamiliar with the feature.

FF != Firefox :)

**Comment by alexDevBR** [comment]
@drewnoakes I updated the screenshot with you suggestion. I also though it might me useful for beginners to add in the pull dialog (and maybe in the tool strip) a comment such as (safest) for fetch, and (Fast-Forward only, safe) for the FF merge.

**Comment by RussKie** [comment]
Please keep it "_Sentence cased_"

**Comment by alexDevBR** [comment]
@RussKie I updated the screenshots. Is that what you meant?

**Comment by RussKie** [comment]
Yes, thanks

**Comment by GintasS** [comment]
The PR is closed, so I guess we should close the issue as well.
