### ISSUE TITLE
Checkbox for ignore case in source

### ISSUE THREAD

**Issue by goranbo** [gitextensions/gitextensions#3480]
In Windows IDE:s, especially older versions, case is not significant in the sourcecode. It would be nice to have the possibility to ignore case when displaying differences.

**Comment by pmiossec** [comment]
It seems to me more a feature request on diff tools more than a GitExtensions issue, no?

**Comment by vbjay** [comment]
Depends on the language not ide. C# vs vb for example.

**Comment by goranbo** [comment]
Yes, I forgot to mark it as a feature.
Maybe it could be implemented like "ignore whitespaces" in the file diff
view with a new button.

Den 4 jan 2017 23:51 skrev "Philippe Miossec" <notifications@github.com>:
