### ISSUE TITLE
Clone destination should be current folder as in previous version

### ISSUE THREAD

**Issue by ltvan** [gitextensions/gitextensions#3482]
--- GitExtensions2.49, Git 2.11.0.windows.1, Microsoft Windows NT 6.3.9600.0

When I used 2.48, the clone destination is the folder which I press right click on, and the subfolder to be created is from the name of the git url, that was fine.

Now when I upgraded to 2.49, the clone destination is the parent folder and the subfolder to be created is default to the current folder name, but when I paste the url in, the subfolder changes to that url name, which is not expected and inconvenient.

For example I right click on `c:\workspace\projects`, the destination is `c:\workspace` and the subfolder is `projects`, then I paste the git url and the subfolder become the repos name, the whole path is now `c:\workspace\repos-name`, while actually I want to clone into the projects folder.

**Comment by Vilmir** [comment]
It took me quite some time to realize that this behavior changed. Pretty disturbing.

**Comment by jbialobr** [comment]
Duplicates #3394.

**Comment by emilsteen** [comment]
This bug is back in 2.51.01!

**Comment by RussKie** [comment]
Relates to #4855
