### ISSUE TITLE
Open with difftool, A <-->B (F3) silently fails when comparing with current branch

### ISSUE THREAD

**Issue by shift-evgeny** [gitextensions/gitextensions#3483]
Git Extensions 2.49 on Windows 10 x64

I open the Diff dialog in using "Compare with current branch" and check "Compare to merge base". After selecting a file I press F3 (open with difftool) and nothing whatsoever happens. The diff tool doesn't run and there is no error or other feedback. If I select "A <--> Working directory" or any of the other diff menu items the diff tool opens as expected.

Also, if I open the Diff dialog by selecting one revision as BASE (Ctrl+L) then Compare To BASE (Ctrl+R) difftool A<-->B works - for the same file, same two branches.

**Comment by loop-evgeny** [comment]
Still happens on 2.51

**Comment by mstv** [comment]
It works for me in 2.51.05 and 3.x. Though sometimes, there seems to be an issue that the hotkeys do not work right after opening a window.
Could you test it again, please, @loop-evgeny?

**Comment by GintasS** [comment]
Since @mstv has mentioned, this seems to fix (or perhaps you can check it again, I can't find these "Compare with current branch" and "Compare to merge base" options).

**Comment by loop-evgeny** [comment]
I cannot check now, because this only happened when comparing certain git revisions and unfortunately I didn't write down which revisions I reproduced it with on 2.51. I'll add another comment here if I see it again. I'm on 3.4.3 now.

**Comment by gerhardol** [comment]
Is this a duplicate of #1842 ?
If the file is not changed, git-difftool just aborts without information (error code, message etc). So this is not possible to detect

**Comment by loop-evgeny** [comment]
No, I don't believe so. I believe there were changes in my case, but can't be 100% sure now.

**Comment by RussKie** [comment]
Please open a new issue if this is still an issue in the latest version.
