### ISSUE TITLE
Exception "Illegal characters in path" when invoking "browse" via comman line parameter

### ISSUE THREAD

**Issue by gimmi** [gitextensions/gitextensions#3489]
Hi, with version `2.49` the following command:

```
GitExtensions.exe browse "C:\path\to\dir\"
```

fail with the error

```
System.ArgumentException: Illegal characters in path.
```

work as expected if i remove the trailing `\` or add trailing `.`

```
GitExtensions.exe browse "C:\path\to\dir"
GitExtensions.exe browse "C:\path\to\dir\."
```

Not a big issue, but little annoying and possibly an easy fix.

**Comment by b3rnhard** [comment]
This makes it difficult to invoke from Visual Studio when using "External Tools" with $(SolutionDir), which always adds a trailing backslash.

**Comment by RussKie** [comment]
Is this still a problem?

**Comment by b3rnhard** [comment]
Yes, it is.

**Comment by RussKie** [comment]
In which version?

I've just tried it in 2.50.01. Running `>gitextensions browse C:\Development\test1` or `>gitextensions browse C:\Development\test1\` results in the same thing - the repo is opened and with a trailing slash appended if it is missing
Running `>>gitextensions browse C:\Development\test1\.` opens the repo, though the path is `>gitextensions browse C:\Development\test1\.\`

**Comment by b3rnhard** [comment]
Calling 
```
"C:\Program Files (x86)\GitExtensions\GitExtensions.exe" browse "C:\Users\jahn\workspace\_Product\Prd-MIP\"
```
immediately crashes with Target Site 
```
Void CheckInvalidPathChars(System.String, Boolean) @ System.IO.Path
```
If I leave out the trailing backslash, everything works. If I remove the quotations like this but keep the trailing backslahs, it also works:
```
"C:\Program Files (x86)\GitExtensions\GitExtensions.exe" browse C:\Users\jahn\workspace\_Product\Prd-MIP\
```

**Comment by RussKie** [comment]
Could you please post the full stack trace

**Comment by RussKie** [comment]
I think in the first case it treats the trailing `\"` not as quoted `\` but as an escaped `"` - this leads to the path being `C:\Users\jahn\workspace\_Product\Prd-MIP"`...

**Comment by b3rnhard** [comment]
Stacktrace for the version with quotation marks:
```
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at GitExtensions.Program.GetWorkingDir(String[] args)
   at GitExtensions.Program.Main()
```

**Comment by jbialobr** [comment]
There is a bug in .net http://www.mobzystems.com/code/bugingetcommandlineargs/

**Comment by RussKie** [comment]
Nasty...

**Comment by vbjay** [comment]
Why couldn't we generate args from Environment.CommandLine?  
![image](https://user-images.githubusercontent.com/3629489/30083255-c8d7966a-925b-11e7-9d54-817865dd88c7.png)

**Comment by jbialobr** [comment]
No one said we could not.
