### ISSUE TITLE
Checkout branch window doesn't rescale

### ISSUE THREAD

**Issue by Fr4ns** [gitextensions/gitextensions#3490]
Version 2.49

When selecting a long branch name in the "Checkout branch" window, the button "Checkout" moves to the right and the screen doesn't resize. This results in the checkout button almost to disappear from the window.

Reproduce steps:
- Open a repository
- Click: Commands -> Checkout branch
- Select Remote branch
- Select a branch from the remote with a long name. In my case it is 57 characters long in total.
- See that everything moves to the right due to the long branch name and the button almost moves out of sight.

![image](https://cloud.githubusercontent.com/assets/3653278/21898654/cece7566-d8ed-11e6-83c9-037d88964606.png)

**Comment by vbjay** [comment]
That should be an easy fix with the anchor property.
