### ISSUE TITLE
'Enter commit message' does not disappear when you start typing your message

### ISSUE THREAD

**Issue by mnaoumov** [gitextensions/gitextensions#3491]
![commit](https://cloud.githubusercontent.com/assets/735878/21928598/7833cec0-d994-11e6-9bf1-2644666c3d58.png)

**Comment by crypto-rsa** [comment]
I can confirm this.
Steps to reproduce:

1. Make some changes in the repository
2. Go to the Commit dialog and make sure the *Close dialog after each commit* option is off
3. Stage some, but not all changes
4. Enter a commit message and click Commit
5. After the commit is performed, dismiss the Process window

The commit message window is now focused, the cursor is at the beginning but the "watermark" text is again displayed. If you now start typing, the text will be drawn in gray and it won't be registered as the true message text (ie. when you now try to commit the rest of the changes, a message box will appear saying *Please enter commit message*).

**Comment by dhilgarth** [comment]
I am using version 2.51 and I am seeing this. Is this a regression?

**Comment by DmitryZhelnin** [comment]
I'm experiencing this issue too. Version 2.51.01. Sometimes the watermark text is displayed as regular text. Sometimes when I start to type my commit message it has watermark style and appends to existing watermark text.

**Comment by RussKie** [comment]
OS? .NET version? under what circumstances?
