### ISSUE TITLE
gitflow plugin "feature finish" parameters

### ISSUE THREAD

**Issue by sergiomcalzada** [gitextensions/gitextensions#3495]
I want to keep "feature" branches, but can't use the [option](https://github.com/nvie/gitflow/wiki/Command-Line-Arguments) -D when finish button is clicked.

### git flow feature finish [-rFkDS] \<name|nameprefix>
**-r** rebase instead of merge

**-F** fetch from $ORIGIN before performing finish

**-k** keep branch after performing finish

**-D** force delete feature branch after finish

**-S** squash feature during merge

**Comment by gpongelli** [comment]
There's no flag to be checked when finish a branch on GitFlow dialog.

If you want this "-D" flag **every time** you finish a feature in your repository, you can configure git with
`git config --local feature.finish.force-delete true`

If you wish to use this flag for **ALL** your git repository in your pc you can configure git with
`git config --global feature.finish.force-delete true`

PS
this flag will **remove** the feature branch you finish. 
By default git flow keeps branches after finish ("-D" is false).

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
