### ISSUE TITLE
EUC-JP support?

### ISSUE THREAD

**Issue by simonced** [gitextensions/gitextensions#3496]
Hi,

I am a big fan of Gitextensions. We are a japanese company and use Git everyday.

The problem we encountered recently, is that one of our projects is encoded in EUC-JP, and the only display of content options we can use are SHIFT_JIS or UTF-8 in the options (global or local to repo).

Commits messages are fine, and file content is not damaged or anything, but we can't see the japanese characters in the diff windows. We can do so with an external Diff for now (KDiff can do it).

I know it's a very limited use case, but it would be awesome to have more encoding options regarding project file contents.

**Comment by jbialobr** [comment]
Done in #3647.
