### ISSUE TITLE
Unable to get local issuer certificate

### ISSUE THREAD

**Issue by cniweb** [gitextensions/gitextensions#3497]
fatal: unable to access 'https://tfs-server.local.domain.de/...': SSL certificate problem: unable to get local issuer certificate

**Comment by ghanique** [comment]
Would this be a solution?

http://stackoverflow.com/questions/11621768/how-can-i-make-git-accept-a-self-signed-certificate

**Comment by cniweb** [comment]
Thanks, this helps:
https://blogs.msdn.microsoft.com/phkelley/2014/01/20/adding-a-corporate-or-self-signed-certificate-authority-to-git-exes-store/

**Comment by erkutyildiz** [comment]
git -c http.sslVerify=false clone https://yourpath
