### ISSUE TITLE
Checkout button out of range

### ISSUE THREAD

**Issue by JarlAlexLupu** [gitextensions/gitextensions#3498]
--- GitExtensions2.49, Git 2.9.2.windows.1, Microsoft Windows NT 6.3.9600.0

When selecting a remote branch that has a max name length the checkout window content resizes and the checkout button is pushed outside the visible area.

![image](https://cloud.githubusercontent.com/assets/25192698/22051717/cd77f994-dd4d-11e6-801b-17328f87bf66.png)

**Comment by vbjay** [comment]
Duplicate #3490
