### ISSUE TITLE
A setting refers to the "browse dialog" but it's not clear what it is

### ISSUE THREAD

**Issue by eli-b** [gitextensions/gitextensions#3499]
A setting refers to the "browse dialog":
![image](https://cloud.githubusercontent.com/assets/834999/22062425/48cc6ca4-dd82-11e6-81e5-27a736350169.png)
but the browse dialog isn't labelled as such anywhere else so it isn't clear what it is.

I'm assuming it's the commit log window because the "browse repository" [documentation page](https://testgitext.readthedocs.io/en/latest/browse_repository.html) shows it.

If I understand this setting correctly, I suggest changing its description to "Show number of changes on commit button (restart required)".

**Comment by vbjay** [comment]
Main window is the browse dialog when a repo is open.

**Comment by eli-b** [comment]
Thanks for the explanation, but how is a user supposed to know that?
The documentation doesn't mention the name "browse dialog" anywhere else, and the main window isn't titled "browse dialog" when a repo is open.

Also, if I understand correctly, the setting enables showing the number of changes on the commit button, like so: ![image](https://cloud.githubusercontent.com/assets/834999/22065350/8cb989d4-dd90-11e6-97a2-61a53f44ef3f.png), so its description can be improved.

**Comment by pmiossec** [comment]
>so its description can be improved.

Good idea! What do you propose? 
I think it's also easy to do a pull request for this proposition...

**Comment by eli-b** [comment]
Thanks!
I'll open a PR, I just wanted to make sure I really understand the meaning
correctly myself first.

בתאריך יום ה׳, 19 בינו׳ 2017, 20:07, מאת Philippe Miossec ‏<
notifications@github.com>:
