### ISSUE TITLE
[feature request] single-instance only configuration

### ISSUE THREAD

**Issue by wsw70** [gitextensions/gitextensions#3500]
--- GitExtensions2.49, Git 2.10.1.windows.1, Microsoft Windows NT 6.3.9600.0

Would it be possible to add a configuration option to force  GitExtensions to run only once and reuse an existing instance when started twice? 

Jumping between projets, I often end up with several GitExtension instances started when a single one would be perfect using the 'Change working directory' feature.

**Comment by ghanique** [comment]
Sounds useless to me... I don't understand the use case for wanting to have
only one instance.

**Comment by wsw70** [comment]
@ghanique: your workflow may be different from mine, it does not make it "useless". 

As a matter of fact, I  work on several projects at the same time and having several gitextention instances open is a pain. I switch from project to project via the "directory" drop-down, which is easier because more predictable (no need to guess which instance holds which project)

**Comment by marazt** [comment]
Ok, but what about possible problems, e.g.,

- You are in the middle of rebase
- You are in the middle of merge conflict
- ...

How the app should behave?

**Comment by ghanique** [comment]
I didn't say it was useless :-), just that it sounded useless to me and
that I don't understand the use case.

Would a tabbed interface where each tab contains its own repository be a
Single Instance implementation that would meet your requirements?

In my workflow I use Dexpot and multiple desktops. Every project has its
own desktop with its own windows (Git Extensions, Windows Explorer, VS
Code, etc).

**Comment by wsw70** [comment]
@ghanique : yes the tabbed interface would be a perfect solution so that there is only one instance (visually at least)
