### ISSUE TITLE
Commit "Author" text box has incorrect descriptive text

### ISSUE THREAD

**Issue by markpizz** [gitextensions/gitextensions#3501]
In the commit dialog box, the Options dropdown has a text area with text above it that says:

Author: (Format: "name \<email\>")

This suggests to me that I should put quotes around the whole expression.  For example:

  "Joe Blow \<joe@blow.org\>"

The resulting git command fails since when the command is constructed an additional set of quotes is added.

Maybe the descriptive text should be not have the quotes.
Maybe, the data validation logic should remove any leading and trailing quotes in case someone actually provides them....

**Comment by vbjay** [comment]
Format is being delimited by the quotes. How do you make that mistake?

**Comment by markpizz** [comment]
I'm not an idiot, and I read it that way.  It wasn't clear to me.

In any case, the second suggestion I made would allow folks as stupid as me to have a useful experience how ever they read the descriptive text.  This is as opposed to having to interpret the completely unclear failure message in the git execution box.
