### ISSUE TITLE
Feature request: assign F2 key to "Rename branch"

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#3503]
I often rename branches to keep track of work in progress / PR / waiting for.... etc. and I noticed myself intuitively using the F2 key to do this - which doesn't work -.
F2 seems to make sense as it is used in a lot of other programs for "edit name" type functionality and I was wondering whether it could be added or alternatively, whether the "Rename branch" command could be added to the list of commands you can assign a hotkey to.

**Comment by marazt** [comment]
It is a good idea. But there is one problem. If you have multiple branches on the same line, the shortcut does not know which branch you want to rename. So for this situation there must be some option how to specify a branch to be renamed (probably some dialog).

**Comment by jrfnl** [comment]
Just thinking out loud: what about automatically assuming the branch to rename is the one selected on the screen if the selected commit is the head of a branch (is that the right term?).

![screenshot](https://cloud.githubusercontent.com/assets/663378/22217390/26a5ea40-e1a3-11e6-8cf5-22528ef23289.png)


If a commit is selected without a branch head or if no commit is selected, show a dialogue ?

**Comment by mdonatas** [comment]
@jrfnl I think the point of previous comment was regarding situation when there are multiple branches pointing at the same commit. Then you'd need a dialog to make a selection.

**Comment by jrfnl** [comment]
@mdonatas Sorry, I read it too quickly. Still a (minimalistic) dialogue for multiple branches pointing to the same commit and for a selected commit not being the head of a branch, sounds good.

**Comment by vbjay** [comment]
Think. If the head is pointing to master and upstream/master and featurex
and featurey branch which branch do you want to rename?  Some logic like
not master and not remote branches but do we rename featurex or featurey?

**Comment by marazt** [comment]
@vbjay That is exactly what I pointed in my previous post.

**Comment by vbjay** [comment]
I know. He didn't seem to get it

**Comment by vbjay** [comment]
It doesn't matter if it is head or not.

**Comment by jrfnl** [comment]
@vbjay No need to get all wound up over some terminology confusion. I already pointed out myself in my second comment that I wasn't sure if I was using the right terms to express what I meant.

All the same I *did* get the point. *You* clearly didn't.

> I know. He didn't seem to get it

Oh dear... misogyny or just professional deformation ?

**Comment by jrfnl** [comment]
Thank you @RussKie for adding this in!
