### ISSUE TITLE
Add a quick way to copy the current commit hash to the clipboard

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#3505]
When working with other git-related software one has to frequently copy commit hashes. It would be useful if there was a quick way to copy the hash of the current commit - either using a hotkey or a button in the commit info window (or preferably, both).

**Comment by marazt** [comment]
+1

**Comment by vbjay** [comment]
Right click on commit details area.

**Comment by crypto-rsa** [comment]
> Right click on commit details area.

And? There is just a command *Copy commit info* which is not what I asked for.

**Comment by vbjay** [comment]
Did you see the right arrow on that command.

**Comment by crypto-rsa** [comment]
> Did you see the right arrow on that command.

What exactly do you mean? This is the context menu for the commit details:
![obrazek](https://cloud.githubusercontent.com/assets/11479798/22238068/a56fd1a8-e20f-11e6-87dc-9b4c21004dbb.png)

**Comment by ghanique** [comment]
I think you can just select a commit in the graph and press Ctrl-C. Is that
what you're looking for?

**Comment by crypto-rsa** [comment]
> I think you can just select a commit in the graph and press Ctrl-C.

This works if the revision grid is focused. So when working for example in the Diff panel I need to focus the revision grid and press Ctrl-C. So while it is a good workaround, it still not as smooth as having a dedicated hotkey.

**Comment by vbjay** [comment]
Woops. It used to have a sub menu to pick author name, commit hash...

**Comment by marazt** [comment]
Some small button or "copy" text next the Commit hash seems good.

**Comment by mdonatas** [comment]
How about double-clicking the hash to select it and pressing ctrl+c? That whole header is a RichTextBoxControl it copies selected text on ctrl+c

**Comment by ghanique** [comment]
IMHO there are plenty of easy ways to copying the hash. I don't copy hashes
that often that the available ways to do it are annoying. I think other
issues are more important.

**Comment by crypto-rsa** [comment]
Ctrl-1, Ctrl-C is fast enough for quick keyboard access. However, for quick mouse access, there could still be some *Copy* button next to the hash in the *Commit* tab, as @marazt notes.

**Comment by jbialobr** [comment]
Maybe instead of a button, there could be added a link:

`Commit hash: 527be51116d0dd3e3e9eb8050b540e6fbd03495d` [(Copy Ctrl+h)](527be51116d0dd3e3e9eb8050b540e6fbd03495d)

Link could also display the current associated shortcut key for copying the hash.

**Comment by crypto-rsa** [comment]
That was actually my original idea but I don't know how to set up the link in the `RichTextBox` so that it can be handled in a custom way.
There are currently two types of links in the `CommitInfo` window - the `mailto:` of the author (handled by the operating system through the `Process` class) and `gitext` links to other commits. The "copy commit hash" link falls into neither category.

**Comment by jbialobr** [comment]
Maybe add a support for: `gitext://copy/?text=527be51116d0dd3e3e9eb8050b540e6fbd03495d`
