### ISSUE TITLE
Branch normalization strips valid characters from the branch name

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#3507]
Branch names are normalized according to [git-check-ref-format](https://www.git-scm.com/docs/git-check-ref-format/1.8.2). It states that characters below *\040* and also *\177* are not valid. However, these are **octal** values. In the original implementation of `GitBranchNameNormaliser` these were incorrectly treated as **decimal** values. The \177 value was fixed in #3301 but the \040 was not. As a consequence, GitExtensions doesn't allow characters with decimal values between 32 and 39 to be included in the branch name.

**Comment by RussKie** [comment]
Yes, you're correct, and I screwed up :(
I'll get a fix up in near future.

**Comment by crypto-rsa** [comment]
> I'll get a fix up in near future.

Well I already added pull request #3508 which fixes the issue but I haven't received any feedback so far.

**Comment by KindDragon** [comment]
We should just use  libgit2sharp Reference.IsValidName()
