### ISSUE TITLE
Duplicate context menu items on a folder in tree pane

### ISSUE THREAD

**Issue by mat-m** [gitextensions/gitextensions#3509]
GitExt 2.49 on Win 7 64-bit

If you right-click on a folder **in the tree pane** of an explorer window, you have two context menu entries (which was #1987)
![image](https://cloud.githubusercontent.com/assets/1039753/22246754/9932e5b6-e236-11e6-92c7-37bd2ef373ef.png)
If you right-click on the same folder in the files pane, then only the upper one is visible.

**Comment by RussKie** [comment]
Do they both work?

**Comment by mat-m** [comment]
Yes, they work both.

I do not know how to check, but I suppose we declare the context menu for various object types, and a folder encompasses two object types, thus getting a double entry.

**Comment by vbjay** [comment]
Check local folder vs network folder. Check unc path vs mapped drive.

**Comment by mat-m** [comment]
One menu item on local drives and mapped drives.
Two menu items on folders (whatever their parent) and network shares.

**Comment by RussKie** [comment]
did you have older versions installed which you upgraded?

**Comment by vbjay** [comment]
Screenshot?

**Comment by vbjay** [comment]
Nevermind.  Email apparently doesn't  pull down images in issue.

**Comment by RussKie** [comment]
Closing due to age and lack of follow up.

**Comment by mat-m** [comment]
@RussKie : I find it strange that you close the issue just because nobody could take care of it.

I will check if last version still has the issue.

**Comment by vbjay** [comment]
Did you read what he said?  How many releases have we had?  Does this still
happen currently in master?

**Comment by mat-m** [comment]
@vbjay : I was suprised it was not closed as Fixed.
But it is, actually.
So this is good news, and thanks to whoever fixed it.

**Comment by illfated** [comment]
For what it is worth, I guess it could have been fixed as early as in 2.51.05 or any 2.5x version (seeing that you reported it on 2.49) and no updates between then and now (purely based on the fact that I have mostly used 2.5x versions and not noticed your issue).
