### ISSUE TITLE
File diff window always shows the top most file in a multiple selection

### ISSUE THREAD

**Issue by safield** [gitextensions/gitextensions#3510]
GitExt version 2.49.
On Windows 7 service pack 1.

**Observed Behavior**
While in the diff window, if the user uses the ctrl or shift key to select multiple files in the left file pane, the right file diff pane will always show the top most selected file. This leads to inconsistent and undesirable behavior.

If you select a file and then hold shift or ctrl, and then add another file to the selection, AND the other file is below the first file in ordering, the right file diff view will remain on the previous file.

If you select a file and then add a file to selection that is above it in the file view, the file diff view will now change to the second selected file.

**Expected Behavior**
The more desirable behavior is that the last clicked file will always be the file that is shown in the right diff view pane.

The use case where this behavior is desirable is when selecting multiple files to apply the "Reset File to" command to.

A user could then click a file and inspect it in the right pane and decide if this files changes should be reverted. Then the user could ctrl click another file to add it to the selection, and because the diff view on the right updated to it, determine if its changes are to be tossed out ( in which case the user could ctrl click to unselect). The user would then be able to add to selection and inspect until all the files have been assessed, and the batch selection is ready to be "reset files to".

In the current observed behavior, you must either assess all the files you want to revert, then remember them, then batch select them all once they have been assessed. Or you can select from the bottom up, which is an un-intuitive workaround.

**Comment by safield** [comment]
This issue is not properly fixed in 2.50.02. The diff window will only update right hand file diff window with the next ctrl+mouse1 added file to the current selection if the newly click file is lower than the last selected file in the left hand commit diff window list. The expected behaviour would be that the right hand diff window will update to show the latest added file to the current selection, regardless of its order in the commit diff window. This issue is also observed in the commit window staging area lists.

Should this be a new issue, or should this be reopened?

**Comment by RussKie** [comment]
@jbialobr is this something you're planning to look at?

**Comment by gerhardol** [comment]
I have taken a look at this. A solution will be very hacky.
The control used (NativeListView) does not seem to have a way to notify of the latest selected item, just when there is a change (I hope someone knows better). (Not sure if it reports on every change either.) It may be possible to implement this by comparing the last known list with the new selection.

It would be nice to have this working, but I do not plan to do anything right now.

**Comment by RussKie** [comment]
@NikolayXHD is our current Windows controls jedi master 😎 Perhaps he can think of a not-so-hacky solution?

**Comment by NikolayXHD** [comment]
The first thing that comes to mind is 
- handle ListView.MouseClick event
- find the clicked item by coordinate, which I remember is possible, I saw it somwhere in gitextensions code
- display the diff for the file corresponding to the clicked item

**Comment by NikolayXHD** [comment]
The second thing that comes to mind is [`ListView.FocusedItem`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.listview.focuseditem?view=netframework-4.7.2)

**Comment by gerhardol** [comment]
> What if the last click was removing the file from selection. Should diff view still show the last clicked file or not?

The handling need to be refined for FileStatusList SelectedItems (or possibly just SelectedItem). No logic change elsewhere.

The FileStatusList currently uses the underlying Selected property. If the notification for a selected file is used instead, the SelectedItems can use a kind of stack (where the middle items can be removed).
It would be mostly OK too if just the last selected item is remembered and a check if the file is still selected when accessing the SelectedItem.

**Comment by NikolayXHD** [comment]
Stack seems an overkill for the use case we are trying to enable which is
> the last clicked file will always be the file that is shown in the right diff

considering that
- the list allows multiselect
- the right diff can only show 1 item from the list
- there can be only 1 focused item,

the most logical way to go, is to show the focused file in the right diff.

If for some reason it's important to keep looking at selected item to choose what file is displayed on the right diff, then I would suggest allways 
- show the focused item if it is selected
- show any other selected item otherwise
- show no diff if selection is empty

**Comment by gerhardol** [comment]
@NikolayXHD 
The limitations you propose are very reasonable. 
If SelectedItem (and SelectedItemParent) are renamed to FocusedItem* the change is maybe clearer.
