### ISSUE TITLE
Install Hook crashes git extensions when .git/hooks directory is absent

### ISSUE THREAD

**Issue by mbirtwistle** [gitextensions/gitextensions#3512]
We use the Gerrit Code Review system, and git extensions because of the excellent gerrit support.  The first time a user connects to a repository containing a .gitreview file, the 'Install Hook' button appears as expected on the toolbar. Clicking 'Install Hook' raises a fatal exception and closes git extensions.  
The reason is because the .git/hooks directory does not exist on our repos when they are cloned.
Manually creating a .git/hooks folder resolves the issue and the Install Hook button then works as expected,  however, Git Extensions should be able to do handle this situation gracefully.

**Comment by vbjay** [comment]
I agree. We should just create the folder. Now if the folder creation fails then let user know and halt the hook creation process.

**Comment by RussKie** [comment]
How can this be replicated?
I don't have  Gerrit Code Review system...

Alternatively please provide full exception details.

**Comment by vbjay** [comment]
Just add a create directory step to the actions before the hook is created
if the directory does not exist.

Michael. I say you are welcome to fix it and put in a pull request.

**Comment by panteamihai** [comment]
I gave it a shot :)
