### ISSUE TITLE
Feature Request: Remove file from repo

### ISSUE THREAD

**Issue by safield** [gitextensions/gitextensions#3513]
Git-extensions currently lacks the ability to select a file in the repo, and to remove it, without deleting it on the local file system.

When browsing the repo in the "File Tree" view, if you right click on a file, the subsequent context menu should contain a "Remove file".

**Comment by vbjay** [comment]
Go to commit window. Right click file.

**Comment by safield** [comment]
Are you referring to "Delete" in commit window? 

If so... 

The "Delete" behaviour differs from the proposed "Remove" behaviour in two ways...

1. I might want to remove an unchanged file. So this "remove" feature should really exist in the "File Tree" view instead of the "Commit Window", since only changed files exist in the commit window.

2. The "Delete" action removes the file from the local file system, where remove leaves it.

**Comment by vbjay** [comment]
https://git-scm.com/docs/git-rm

**Comment by safield** [comment]
Delete -> Commit removed the file from my local directory.

**Comment by vbjay** [comment]
So my point with git rm is that even straight git rm removes the working
file and marks in index to remove file in repo. This is how git works. The
index stages changes made in the working directory, not staging is
replicated in working directory. If you want to remove a file from the repo
because you meant to never include it, then you will rewrite history.

**Comment by safield** [comment]
In the linked git docs it says

> will not remove a file from just your working directory

But maybe it will upon commit?

> If you want to remove a file from the repo
because you meant to never include it, then you will rewrite history.

Yes...this.

Maybe my case is not a common one and stems from my naivety with git.

But I think my second point that delete feature should probably be in the "File Tree" view, since the operation is valid on any file, and not just changed files.

**Comment by vbjay** [comment]
I don't see a problem with adding a delete file option but everybody would
expect it to delete the working file too.

You also have two states of deleting a file.

1.  New file never been committed. Deleting just removes the working file
and if the file was staged, remove it from the index.

2.  File has been committed.  Delete working file and mark action in index
to delete file.

**Comment by pmiossec** [comment]
I think that @safield ask for a 'git rm --cached' feature and it makes sense to put it in the context menu of the file tree view. 

That will add a delete change on the file directly to the stage area without touching the workspace file... 

Could make sense even if rarely used...

**Comment by vbjay** [comment]
Sure. The GUI would need to be clear on the difference.
