### ISSUE TITLE
WBEM_E_NOT_FOUND when clicking on matched Revision link

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#3515]
GitEx 2.49, win7x64, Opera browser.

Search pattern: #(\d+)
Uri: Issue: #{0}	http://redmine.local/issues/{0}

It parsed successfully, but if I click on it, GitEx shows an error 0x80041002. What's wrong?

**Comment by pmiossec** [comment]
It seems to be the problem that I try to circumvent in the pull request #3471.

**Comment by pravic** [comment]
Exactly. Thanks, at least I got a workaround.
