### ISSUE TITLE
Focus of current window is lost on commit

### ISSUE THREAD

**Issue by Denitz** [gitextensions/gitextensions#3521]
Occurs again in 2.49, see #1899

**Comment by AleXKarasev** [comment]
I have this problem after I click "Commit templates" button on the commit windows. To find this windows again I use ctrt+tab twice. I have the same behavior after click on "commit message" and "Options" button as well.
Version 2.49.03

**Comment by jbialobr** [comment]
From yours description I don't know what the issue is. Could you provide more details on what happens, what goes wrong and how it should go?

@AleXKarasev it seems that your issue is more like the #3593.

**Comment by AleXKarasev** [comment]
@jbialobr Yes, you are right. I will move my comment to #3593
