### ISSUE TITLE
Mono doesn't have installed WebBrowser

### ISSUE THREAD

**Issue by HappyNTH** [gitextensions/gitextensions#3523]
I'm trying to use GitExtensions through Mono, as I have been instructed through the manual. However, when I try to like to my Github, it says `Mono doesn't have installed WebBrowser` in the GitExtensions client, and opens a blank window. I get the error `libgluezilla not found. To have webbrowser support, you need libgluezilla installed` in the Terminal. Please help!

**Comment by KindDragon** [comment]
Check this http://askubuntu.com/a/465593/579410

**Comment by HappyNTH** [comment]
I'm using Mac, so this is not a possibility. I manually entered an OAuth key, and now it shows my personal repositories. However, when I try to clone anything at all, I get the error:
`Permission denied (public key)
fatal: Could not read from remote repository

Please make sure you have the correct access rights and the repository exists`

I am certain of both of these, and the OAuth has full rights.

**Comment by maphew** [comment]
I get this same error on Linux Mint 18.2 and I do have libgluezilla installed:

```
matt@dell-xps ~/ $ cat `which gitext`
#!/bin/bash
mono ~/.local/opt/GitExtensions/GitExtensions.exe "$@" &
matt@dell-xps ~/ $ gitext 

    # in app use Menu: Plugins >> Github

matt@dell-xps ~/ $ libgluezilla not found. To have webbrowser support, you need libgluezilla installed

matt@dell-xps ~/ $ apt-cache search libgluezilla
libmono-webbrowser2.0-cil - Mono Web Browser library (for CLI 2.0)
libmono-webbrowser4.0-cil - Mono Web Browser library (for CLI 4.0)

matt@dell-xps ~/ $ sudo apt install libmono-webbrowser4.0-cil
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libmono-webbrowser4.0-cil is already the newest version (5.10.1.20-0xamarin1+debian7b1).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.

matt@dell-xps ~/ $
```

**Comment by GintasS** [comment]
Since Workaround available, I'm voting to close this because of age and lack of discussion.
