### ISSUE TITLE
"Checkout Branch"

### ISSUE THREAD

**Issue by tseanard** [gitextensions/gitextensions#3529]
--- GitExtensions2.49, Git 2.10.2.windows.1, Microsoft Windows NT 6.3.9600.0

Hello.  It is my understanding that with the GIT repository models, there is not a "Checkout".  In GIT Extensions, there is an option to "Check out branch", but I believe that this should be "Switch to Branch".  How do I change the word "Checkout" to "Switch" in the UI?

**Comment by vbjay** [comment]
Everyone follows the same terminology. https://git-scm.com/docs/git-checkout.
Makes more sense to use checkout.

**Comment by jbialobr** [comment]
You can go to <instalation folder>\Translation\ and edit desired translation file.
Since 2.49.01 also English translation is included.
