### ISSUE TITLE
Console window cannot be closed with the Escape key

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#3531]
When a command in the console window finishes, a message *Press Enter or Esc to close console...* is displayed. However, the focus is then passed to the OK button (in `FormStatus.Done` method) which prevents the form to handle the Escape key. Shouldn't the focus stay within the console control? It can be closed with both Enter and Escape keys.

**Comment by cristianst85** [comment]
It seems that the easiest/cleanest way to fix this would be to remove this line:
https://github.com/gitextensions/gitextensions/blob/e3795076a05d8ef621d172d3092a1da6b67197db/GitUI/FormStatus.cs#L151

**Comment by jbialobr** [comment]
That will change the behavior for those who don't use conEmu.
