### ISSUE TITLE
Some issues, feedback and requests.

### ISSUE THREAD

**Issue by NOYB** [gitextensions/gitextensions#3536]
--- GitExtensions2.49, Git 2.11.1.windows.1, Microsoft Windows NT 6.3.9600.0

Commands - Pull - Branch - Remote branch drop down
1) Would like it to default to the current selected local branch i.e. same as Local branch.
2) Would like the ability to have the list be trimmed to only include matching local branches.

Process dialog box
1) Don't like the background color changing dark when finished.  Contrast is too low and have to click in box to return to the "normal" background color.  The icon indicators are sufficient.
2) The content area is not touch screen scrollable.  Have to grab the scroll bar.  Not a touch friendly user experience.

Like the branch committer/author highlighting.  But would like to say highlight my commits without having to find and select one of them.

Inclusion of sparse checkout settings option is nice to have.

Would like the shallow clone feature to provide more choice that all or one.  Would be nice to specify by date.

**Comment by drewnoakes** [comment]
Please split this up into separate issues so they can be discussed and tracked individually.

**Comment by RussKie** [comment]
Please install v3 and report any issues on their own.
Closing due to age and lack of follow up.
