### ISSUE TITLE
No way to cancel FormRunScriptSpecify 

### ISSUE THREAD

**Issue by m35** [gitextensions/gitextensions#3544]
### Steps to reproduce

* Tools -> Settings -> Scripts
* Add a new script
	* Name: "Test"
	* Enabled: Checked
	* Add to revision grid context menu: Checked
	* Command: `echo`
	* Arguments: `"{sBranch}"`
* Click OK
* Right-click a commit that contains more than one branch (e.g. `master` and `origin/master`)
* Select "Test"

### Expected behavior

The dialog offers a way to cleanly cancel the operation.

### Actual behavior

The dialog offers an OK button and the corner X (close) button.
The X button does not cancel the operation, but instead returns `null` to the caller of the dialog, which is not the desired result either.

**Comment by GintasS** [comment]
Now we have an "Abort" button to stop the script. Closing this.
