### ISSUE TITLE
What about starting a Slack community?

### ISSUE THREAD

**Issue by ghanique-prorail** [gitextensions/gitextensions#3545]
Hi, 

I see gitextensions having a lot of issues, many of which are not really issues with Git Extensions, but that are related to how to use Git Extensions or related to Git itself. What about starting a Slack community and/or a Slack channel where we can have discussions on "Issues", so that in GitHub one only has to create an issue if there is actually something in the code that needs to be changed?

Kind regards, 

Guillaume

**Comment by KindDragon** [comment]
Hi, we have Gitter channel for that https://gitter.im/gitextensions/gitextensions and StackOverflow tag http://stackoverflow.com/questions/tagged/git-extensions
