### ISSUE TITLE
Commit button changes width (after you changed a file the number of changes will be displayed)

### ISSUE THREAD

**Issue by bernd-herzog** [gitextensions/gitextensions#3550]
This always happens a moment before you want to click on the pull button on the right and the commit button gets misclicked.

Solution: Place the commit button to the right.

Also: The buttons in the pull menu strip could easily fit into the menu bar for increased productivity.

**Comment by gerhardol** [comment]
I suggest this is closed as a duplicate of #1931

**Comment by RussKie** [comment]
Duplicate of #1931
