### ISSUE TITLE
Diff window: "Unsupported file: Input string was not in a correct format."

### ISSUE THREAD

**Issue by zAlbee** [gitextensions/gitextensions#3552]
--- GitExtensions2.49, Git 2.10.1.windows.1, Microsoft Windows NT 6.3.9600.0

I was working in Git Extensions (the last thing I did was amend a commit) and when I returned to commit list, the "diff" window suddenly started to show this error message

![image](https://cloud.githubusercontent.com/assets/5141316/23323299/015787d6-fab6-11e6-84ce-71094939d9a4.png)

Interesting to note that the same thing shows no matter what commit I select. When I select any commit, I can see a very brief flash of the familiar red/green diff text in the window, before it's replaced entirely by this message in black text on white background.

This is the first time I've seen this problem and I suspect it will go away once I restart the program. Let me know if there's any more info I can give.

**Comment by zAlbee** [comment]
I also took a look at Gitcommand log, in Command Cache tab, I can see 2 `diff` commands being generated every time I select a new commit. One of them looks like `diff -M -C -z --name-status "<SHA1>" "<SHA2>"` . The other one looks like `diff  --ignore-space-change --unified=3 -M -C "<SHA1>" "<SHA2>" -- "<path>/<file>"`. The second command appears to be returning normal-looking diffs as far as I can tell.

**Comment by EbenZhang** [comment]
It looks the application failed to convert a string to a number.

You can change the `_internalFileViewer.SetText("Unsupported file: \n\n" + args.Exception.Message);` in `FileViewer.cs` to `_internalFileViewer.SetText("Unsupported file: \n\n" + args.Exception.ToString());`  to see the detailed exception.
`
Hi GitExtensions writers @jbialobr @KindDragon, do you think we should change to show the entire exception message? As a developer using GitExtensions, I don't mind seeing the Stacktrace.

**Comment by RussKie** [comment]
Is this still an issue in the current version?

**Comment by zAlbee** [comment]
I haven't seen this issue happen since I opened the ticket.
