### ISSUE TITLE
System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by VladPetrovici** [gitextensions/gitextensions#3553]
This is what is happening when trying to fetch/pull:

```
Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))

System.Object CoCreateInstance(System.Guid ByRef, System.Object, Int32, System.Guid ByRef) @ System.Windows.Forms.UnsafeNativeMethods

   at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at System.Windows.Forms.StringSource..ctor(String[] strings)
   at System.Windows.Forms.ComboBox.SetAutoComplete(Boolean reset, Boolean recreate)
   at System.Windows.Forms.ComboBox.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by EbenZhang** [comment]
This issue looks the same problem in #1690. don't know why it was closed.

Digging into the source code of `StringSource`, we can see it requires an `IAutoComplete2` COM class (CLSID: `EAC04BC0-3791-11d2-BB95-0060977B464C`) but found it's not registered on your system. 

According to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776288(v=vs.85).aspx), the IAutocomplete2 is defined in `Shell32.dll (version 5.0 or later)`, minimal system requirement is `Windows 2000 Professional, Windows XP [desktop apps only]`.

I guess there's no auto completion support for the `Run`(Win+R) dialog on your system.

You can probably try register `shell32.dll`
- Run `cmd` as administrator
- At the command prompt type `regsvr32 shell32.dll` and then press enter.

**Comment by VladPetrovici** [comment]
I did this but the same thing happens.

   at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at System.Windows.Forms.StringSource..ctor(String[] strings)
   at System.Windows.Forms.ComboBox.SetAutoComplete(Boolean reset, Boolean recreate)
   at System.Windows.Forms.ComboBox.OnHandleCreated(EventArgs e)
   at System.Windows.Forms.Control.WmCreate(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Let me know if there should be anything else I should try.

Thanks,
Vlad
--------------------------------------------
On Sat, 2/25/17, EbenZhang <notifications@github.com> wrote:

 Subject: Re: [gitextensions/gitextensions] System.Runtime.InteropServices.COMException (#3553)
 To: "gitextensions/gitextensions" <gitextensions@noreply.github.com>
 Cc: "VladPetrovici" <petrovici_vlad@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Saturday, February 25, 2017, 1:37 PM
 
 This issue looks the same problem
 in #1690. don't know why it
 was closed.
 Digging into the source code of
 StringSource, we can see it requires an
 IAutoComplete2 COM class (CLSID:
 EAC04BC0-3791-11d2-BB95-0060977B464C) but found
 it's not registered on your system.
 According to MSDN,
 the IAutocomplete2 is defined in Shell32.dll (version
 5.0 or later), minimal system requirement is
 Windows 2000 Professional, Windows XP [desktop apps
 only].
 I guess there's no auto completion support for the
 Run(Win+R) dialog on your system.
 You can probably try register
 shell32.dll
 
 Run cmd as administrator
 At the command prompt type regsvr32
 shell32.dll and then press enter.
 
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by VladPetrovici** [comment]
Unfortunately the command did not solved the crash issue. Let me know if you have any other thoughts. Thanks

**Comment by RussKie** [comment]
Please update to latest versions of git and GE and try again.
Please re-open if you still experience the issue.

**Comment by Diademe** [comment]
I have the same issue. Please re-open.

I tried both 
```cmd
C:\Windows\System32\regsvr32.exe /i shell32.dll
C:\Windows\SysWOW64\regsvr32.exe /i shell32.dll  
```
and reinstall, but the problem persist.

# work around

Compile the gitextensions project with Platform target x64 (in gitextensions project property > build)

# Error Details
```
System.Runtime.InteropServices.COMException (0x80040154): Classe non enregistrée (Exception de HRESULT : 0x80040154 (REGDB_E_CLASSNOTREG))
   à System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   à System.Windows.Forms.StringSource..ctor(String[] strings)
   à System.Windows.Forms.ComboBox.SetAutoComplete(Boolean reset, Boolean recreate)
   à System.Windows.Forms.ComboBox.OnHandleCreated(EventArgs e)
   à System.Windows.Forms.Control.WmCreate(Message& m)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ComboBox.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Why do you expect to register x64 with x32 tools?

**Comment by Diademe** [comment]
I don't understand what those commands are supposed to do.
I tried to execute the command `regsvr32 shell32.dll` given in this post: https://github.com/gitextensions/gitextensions/issues/3553#issuecomment-282478431
It didn't solve my problem. then I saw this [answer in stackoverflow](https://stackoverflow.com/questions/3439845/register-32-bit-com-dll-to-64-bit-windows-7/3440419#answer-3440419). This answer is why I tried to run `C:\Windows\SysWOW64\regsvr32.exe /i shell32.dll` (and `C:\Windows\System32\regsvr32.exe /i shell32.dll` because I don't know where `regsvr32` is seek by `cmd`)

> Why do you expect to register x64 with x32 tools?

I don't understand: `shell32.dll` and `regsvr32.exe` both seems to be 32 dll or tools. What do you mean by _register x64_
