### ISSUE TITLE
Can not view commit message in main window

### ISSUE THREAD

**Issue by maxifly** [gitextensions/gitextensions#3557]
--- GitExtensions2.49, Git 1.7.11.msysgit.1, Microsoft Windows NT 6.1.7601 Service Pack 1

![git_ext](https://cloud.githubusercontent.com/assets/2596114/23363698/02308dd4-fd0d-11e6-9e26-379c17a46342.jpg)

In main window disappear commit messages

**Comment by maxifly** [comment]
in 
--- GitExtensions2.48.05, Git 1.7.11.msysgit.1, Microsoft Windows NT 6.1.7601 Service Pack 1
work well

**Comment by Radrik5** [comment]
Please update Git to 2.x.

**Comment by jbialobr** [comment]
Duplicates #3436
