### ISSUE TITLE
Last character of SHA-1 column not fully visible 

### ISSUE THREAD

**Issue by butscher** [gitextensions/gitextensions#3559]
Just a small nuisance: When showing the SHA-1 column the last character  ist partly cut off by the scroll bar (on Win 7 Professional SP1 64bit):

![sha1cutcharacter](https://cloud.githubusercontent.com/assets/3160774/23405000/4131a90e-fdb8-11e6-8c76-7c5ea84371ba.png)

**Comment by EbenZhang** [comment]
A lot of characters are cropped, not just the last char.

@ugumba, @jbialobr

- Should we display ellipsis if the text is too long? 
- Any reason the SHA column has a different font `consolas`?

**Comment by vbjay** [comment]
Consolas is a fixed width font.

**Comment by Radrik5** [comment]
The SHA1 column was made resizable: https://github.com/gitextensions/gitextensions/pull/2660

**Comment by butscher** [comment]
@Radrik5, I can only manage to make the column smaller but not larger. Additionally this change is lost when closing and reopening the program.
