### ISSUE TITLE
Help wanted: How to restore settings from registry

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#3562]
Hi.

Accidentelly I lost GitEx settings in APPDATA, but I have a backup in registry format from/for older versions. I tried to restore it, but GitEx does not want to read registry settings, it seems - it relies only on *.settings file.

Is there easy way to tell GitEx to read settings from registry? Because it is quiet tricky to convert *.reg to *.settings manually.

**Comment by vbjay** [comment]
There is a backup file in the same folder.

**Comment by pravic** [comment]
Nah. Original settings file was empty, so after opening GitEx cleared backup as well.

However, I just converted reg file to the xml one.

**Comment by vbjay** [comment]
I think an import/export settings functionality would be a good idea.
Allow the users to back up their settings.  I'll suggest it.  I already
made it portable by adding a config option in the config file, it will
store settings in a file in the same folder as the application.

**Comment by vbjay** [comment]
#3563
