### ISSUE TITLE
Make the diff options persistent

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#3566]
It would be useful to store the diff options in the settings file. Currently they have the default values each time the diff window is created (for example when the commit dialog is opened).

The options include:
- number of visible lines
- show entire file
- show nonprinting characters
- ignore whitespace

**Comment by EbenZhang** [comment]
There's an option to remember the `ignore whitespace` in advanced settings.

**Comment by crypto-rsa** [comment]
Ah, thanks for the tip! But anyway, what about the other options? Should there be similar "remember" settings for them? Or should we store the most recently used value automatically?

**Comment by EbenZhang** [comment]
We can do the same thing as I did in #2844. Didn't persist other options as I found they are not very useful. Especially `show entire file` will slow down the application.

**Comment by crypto-rsa** [comment]
OK, the `Show entire file` options is perhaps not used that often. But IMHO remembering the state of the `Show nonprinting characters` option would be useful.

**Comment by jbialobr** [comment]
I am pretty sure there are users that want to remember this option (and others) as well as there are users that don't want to remember these options or just don't care. There is a dedicated settings page for such cases: Detailed Settings. I suggest to create a new sub page of the Detailed page and name it Diff Viewer. Then, move the existing settings from the Advanced -> Diff Viewer group to the new page. This will also be a great place for new options like  those you would like to have.
