### ISSUE TITLE
"There is a problem with this Windows Installer package."

### ISSUE THREAD

**Issue by catb0t** [gitextensions/gitextensions#3574]
![msiexec_2017-03-04_08-33-50](https://cloud.githubusercontent.com/assets/3238748/23584048/a54d14fa-0123-11e7-9621-e62cccaf2e7d.png)

When running the `SetupComplete` release 2.49 `.msi` installer.

"A program required for this install to complete could not be run..."

I haven't the Visual Studio-fu to know how to debug the MSI package, but this was after the installations of Git for Windows and KDiff has completed.

I selected `putty` and "Entire feature will be installed on local hard drive".

This is Windows 7 Ultimate x64 SP1 build 7601. The .NET framework version is at least 4.0.

Let me know if I can provide more information.

**Comment by lmf-mx** [comment]
Did you change any of the detected Visual Studio plugins? I had this error when enabling ones beyond what it selected automatically.

**Comment by scorpeeon** [comment]
@lmf-mx thanks for the tip, the installation went through when deselecting all Visual Studio plugins (which I wouldn't really use anyway)

**Comment by boxerab** [comment]
Thanks! That worked for me - de-selecting plugins

**Comment by jbialobr** [comment]
Duplicates #3469
