### ISSUE TITLE
changes to Categories on the Dashboard are not saved when the PC is shutdown or reset

### ISSUE THREAD

**Issue by 62mkv** [gitextensions/gitextensions#3576]
I've noticed this a lot of times ! And somehow I still forget that one MUST close GE explicitly whenever she does ANY changes at all to the list or contents of Categories on the Dashboard

Because when the PC is shut down or reset while GE still open (which is the most common case for me), NONE changes are saved! 

I would suggest saving these changes every time they are made in the UI, rather than batching them until onClose processing

Is it feasible ?

--- GitExtensions2.49, Git 2.10.1.windows.1, Microsoft Windows NT 6.3.9600.0

**Comment by EbenZhang** [comment]
I don't get what is the ` Categories on the Dashboard`.

**Comment by 62mkv** [comment]
when you open GE, it opens "Dashboard" by default. On the right pane, there's list of "pinned" repos, arranged by "Category"

You can assign repo to category by right-clicking on it and choosing "Move to category"

**Comment by 62mkv** [comment]
frankly, not only "Categories" content gets lost on reboot/shutdown, same happens with Recent Repositories list, for example

**Comment by EbenZhang** [comment]
Thanks, it's good to know that feature. never used it before.

**Comment by EbenZhang** [comment]
Made a fix to this issue. the fix should work most of time except interruption of power supply.
