### ISSUE TITLE
File history and blame not show when path to file contain cyrilic chars

### ISSUE THREAD

**Issue by Dumsik** [gitextensions/gitextensions#3578]
File history and blame not show when path to file contain cyrilic chars.
![cyrilic file name bug1](https://cloud.githubusercontent.com/assets/24560572/23594023/25d8e54c-0262-11e7-88e8-9398cbf0c7a6.png)

**Comment by jbialobr** [comment]
Can you prepare and upload a repository, that we could clone it and reproduce the issue?

**Comment by Dumsik** [comment]
@jbialobr Yes, tomorrow.

**Comment by Dumsik** [comment]
@jbialobr Repository with this issue https://github.com/Dumsik/ruschars.git

**Comment by jbialobr** [comment]
Thank you.
