### ISSUE TITLE
bad uninstall behavior / no true silent uninstall

### ISSUE THREAD

**Issue by Nightreaver** [gitextensions/gitextensions#3581]
Hello

I'm currently struggeling with silent uninstall of gitextension for remote deployment.
I've downloaded the msi version of gitextensions 2.49

The install works fine, but upon removal, even though i'm calling msiexec /x {..} /quit /norestart
The msi installer simply runs 
`"C:\Program Files (x86)\GitExtensions\GitExtensions.exe" uninstall` which either does nothing or is stuck with "language select screen"

__Is there a way to define language with a command before running into this annoying screen just because system user has not set a language yet?!__

**Comment by KindDragon** [comment]
Related to #2939

**Comment by Nightreaver** [comment]
I had no more issues with that on version 3.1.1.6049 - so i think it can be closed

**Comment by RussKie** [comment]
Thank you for the follow up.
