### ISSUE TITLE
Git Worktree Support (Git 2.5)

### ISSUE THREAD

**Issue by pankajazad** [gitextensions/gitextensions#3590]
A new worktree command has been introduced in Git 2.5. It allows you to maintain multiple checked out work trees of the same root repository. It's fantastic. The support for worktree in git extensions will be greatly appriciated.

**Comment by vbjay** [comment]
#3249

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/issues?utf8=✓&q=Worktree

**Comment by pmiossec** [comment]
@pankajazad 
I have updated the pull request and it should now works.
Feel free to test and give feedback...

**Comment by pankajazad** [comment]
@pmiossec 
Thanks a lot.

**Comment by pankajazad** [comment]
installed the recently released 2.48.02 version but couldn't find any menu/button for git worktree. How should I use worktree feature using gitextensions.

**Comment by jbialobr** [comment]
This issue is tagged with the 2.50 milestone. That means that it will be available in the 2.50 version.

**Comment by pankajazad** [comment]
That's true for #3590. But #3249, which actually implements the worktree support is already integrated in master branch and 2.49.02 tagged version actually contains the corresponding source code. Maybe it's not exposed via GUI yet.

**Comment by pmiossec** [comment]
@pankajazad it seems that you have some difficulties reading the history. 
Yes #3249 is merged in master (that will be the next to release 2.50)but no, that's not in 2.49.2.
What you see is just that the 2.49.2 branch has been merged into master. 

PS: and that's always funny someone outside of a project that try to explain to the maintainer of a project what he did himself ;-)

**Comment by jbialobr** [comment]
![gitext](https://cloud.githubusercontent.com/assets/1003909/24248346/4b916b2c-0fcf-11e7-8f60-ae7ed698e470.png)

**Comment by pankajazad** [comment]
@pmiossec, @jbialobr
Thanks for explaining. I have understood now. Apologies for the trouble caused.

**Comment by jbialobr** [comment]
No problem.

**Comment by jbialobr** [comment]
@pmiossec Thank you for implementing this - it is very nice feature.
