### ISSUE TITLE
Commit dialog diff panel resizes inconsistently

### ISSUE THREAD

**Issue by bookman25** [gitextensions/gitextensions#3592]
GitExt version 2.49/2.49.01
Windows 10 Enterprise/Pro (latest patches/versions)

Running git extensions without being maximized causes the commit dialog diff panel to resize each time the dialog is opened.  The diff panel of the commit dialog shrinks on each open regardless of the size of the previous open.

This started happening on 2.49 and is still happening on 2.49.01

![commit-dialog](https://cloud.githubusercontent.com/assets/7157036/23996594/528b880a-0a24-11e7-8df7-8c0ae575a142.gif)

**Comment by markpizz** [comment]
Oddly, I did not see this with 2.49 or 2.49.01, but I updated to 2.49.03 and it is certainly a problem now.

**Comment by jbialobr** [comment]
Fixed in https://github.com/gitextensions/gitextensions/commit/cf28d541c9a010e639cfeee5068bfb2258fe16f0

**Comment by jrfnl** [comment]
Thanks for fixing this! I'm looking forward to not having to resize the commit msg box each time ;-)
