### ISSUE TITLE
Commit Screen disapears after clicking on the drop down buttons on it

### ISSUE THREAD

**Issue by g-rusev** [gitextensions/gitextensions#3593]
--- GitExtensions2.49.01, Git 2.12.0.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

I am using GitExtensions for years. 3 days ago I installed the latest version.
Unfortunatelly, when I click somewhere on the dropdown buttons on the COMMIT screen, the commit screen disapears and becomes invisible. This is kinda frustrating, because, actially, it is working on a background, but is invisible. Sending a video to demonstrate the issue. If not visible enought, can upload HD version.

[20170316_145530.zip](https://github.com/gitextensions/gitextensions/files/847750/20170316_145530.zip)

**Comment by RussKie** [comment]
I've noticed this bug too...

**Comment by jbialobr** [comment]
Can not reproduce

**Comment by RussKie** [comment]
It is intermittent

**Comment by RussKie** [comment]
It seems to be happening quite regularly for me now in **2.49.03**

![image](https://cloud.githubusercontent.com/assets/4403806/25645654/62a844c2-2ff3-11e7-82cb-b2b6cf9dc4fe.png)


Click to expand "Commit message" dropdown - the commit window disappears
![image](https://cloud.githubusercontent.com/assets/4403806/25645639/3f16f2e2-2ff3-11e7-9f12-5c872d85512d.png)


Right click on any file - the commit window disappears again
![image](https://cloud.githubusercontent.com/assets/4403806/25645673/b0507fc8-2ff3-11e7-9501-a648948b19de.png)

**Comment by AleXKarasev** [comment]
I have this problem after I click "Commit templates" button on the commit windows. To find this windows again I use ctrt+tab twice. I have the same behavior after click on "commit message" and "Options" button as well.
Version 2.49.03

**Comment by AleXKarasev** [comment]
To solve this problem you can do next. Go to Settings-> Detailed and switch off "Show the Console tab" checkbox and restart Git Extensions.

**Comment by pspraveenkr** [comment]
I've run into this problem as well. I'm using version 2.50.01 on Windows 7 Enterprise Service Pack 1.

The problem went away once I switched off the Console tab in Settings.

**Comment by RussKie** [comment]
The issue seems to occur if
* console is enabled
* console is activated (the user switched to the console at least once)

When the console is visible or not is immaterial.

Feels like the console monitors right click events...

**Comment by RussKie** [comment]
Please try this build
https://ci.appveyor.com/api/buildjobs/tb8kjpyr04sf8l4o/artifacts/GitExtensions-Portable-3.00.00.1599.zip

**Comment by RussKie** [comment]
I haven't seen the issue for some time now.
I presume it resolved.
