### ISSUE TITLE
Newlines In Commit Message Are Doubled

### ISSUE THREAD

**Issue by petercrabtree** [gitextensions/gitextensions#3604]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a single newline is entered between lines for a commit, two lines show up in the commit.
For example, this:

> Fix bug in Foo.
> IssueTrackingId: 1234

Becomes this:

> Fix bug in Foo.
> 
> IssueTrackingId:

Which then causes the git line collapse behavior to ignore the IssueTrackingId, i.e. git would show the first example as:

> Fix bug in Foo. IssueTrackingId: 1234

But the second example as:

> Fix bug in Foo.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

As above.

**What is the expected behavior?**

Self-evident.

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**

This behavior is new, but I'm not sure when it was introduced. I'm on 2.49.01 of git ext, and git version 2.10.2.windows.1.

**Comment by Radrik5** [comment]
Does the issue relate to viewing existing commits or to creating a new commit? Please provide detailed steps to reproduce.

**Comment by petercrabtree** [comment]
To creating a new commit.

* Open git extensions
* Open a repository
* Click "commit"
* Stage a file
* Write two lines of commit message (i.e. one newline)
* Click "commit"
* Read commit message via any method, it will have two newlines instead of one

**Comment by jbialobr** [comment]
It is done according to this setting:
![gitext](https://cloud.githubusercontent.com/assets/1003909/24265125/b9195244-1002-11e7-88a3-0e5d94a085ef.png)
