### ISSUE TITLE
push.default option does not seem to work in Git extensions

### ISSUE THREAD

**Issue by Gouri-Sankar** [gitextensions/gitextensions#3606]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Consider, there are two local branches ML and RC tracking their remote branches with the same names origin/ML and origin/RC respectively. My goal here is to stop devs if they try to push changes from local branch ML to remote branch origin/RC. They should only push changes to their tracking branches ML->ML or RC->RC. So, I set push.default to 'simple' in Git bash using the command "git config --global push.default simple" hoping to stop devs to push changes to a different branch name, but I can still push to remote branch origin/RC from local branch ML even after this setting.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Have two local branches ML, RC tracking their remote branches with same names.
2. Run this command "git config --global push.default simple" in git bash ( I don't think I can set this directly using Git Extensions tool)
3. Try to push any simple change from local ML to remote RC using Git Extensions 
4. Push will be successful which shouldn't be the case.

**What is the expected behavior?**
push from local ML to remote RC should be refused after setting push.default to 'simple'. Git bash seems to honor this setting. Even though it does not give any 'refused to push ' warning as such, at least it will not push changes if I issue a command like 'git push origin RC' from local ML branch.

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
git version 2.10.1.windows.1. Nope, It's the same behavior with the previous version of the tool.
Git Ext: 2.49.01

Do not hesitate to contact me if you have trouble re-creating this scenario. Thanks for looking into it.

-Gouri Sankar

**Comment by jbialobr** [comment]
`PUSH.DEFAULT
Defines the action git push should take if no refspec is explicitly given.`

This setting only applies when `git push` command is executed. GitExtensions executes this command only if you manually clear the source and destination branch names. Otherwise GitExtensions gives refspec explicitly.

**Comment by Gouri-Sankar** [comment]
Thanks for your clarification. Is there anyway to restrict devs to push their changes only to the respective tracking branches and not across the branches using Git extensions?

**Comment by jbialobr** [comment]
Perhaps you can write a script fired before push. The script should fail when the local and remote branches names do not match. See Settings -> Scripts.
