### ISSUE TITLE
visual studio 2008 can not load getextensions?

### ISSUE THREAD

**Issue by mogudeng** [gitextensions/gitextensions#3607]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
visual studio 2008 can not load getextensions
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When I open visual studio 2008,it show can not load gitextensions,the error number is 8013101b.
**What is the expected behavior?**

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
git version is 2.12.0.Previous versions is not test.But visual studio 2010、2015 can right load gitextensions.

**Comment by vbjay** [comment]
It is 2017. VS 2010, 2012, 2013, 2015, and 2017 have all been released.
About time you got current.

**Comment by jbialobr** [comment]
VS 2008 is not supported.

**Comment by nikess** [comment]
"About time you got current".  Embedded device development is forced to be on 2008 - no choice.

**Comment by RussKie** [comment]
@vbjay different users have different constraints, so some users may be forced to use very old tech...

@nikess I feel sorry for your predicament but it is unreasonable to expect us support to some 10+ year old technology. 
hopefully you can run git extensions alongside visual studio

**Comment by nikess** [comment]
@vbjay WinCE, .NET 3.5, compact framework.. support stopped at 2008.

@RussKie Totally agree.  Was just trying to correct the idea that there are easy options. For anyone else reading this thread, version 2.32 still works in 2008, and the installer can be found on sourceforge.   Many thanks for this great tool.
