### ISSUE TITLE
[Mono - Ubuntu 16.04] Git Extensions Commit and Stash Windows hang

### ISSUE THREAD

**Issue by rkatzmann** [gitextensions/gitextensions#3609]
Description:
Since 2.43 (first usable Ubuntu release for me, previous ones too unstable) I am not able to commit my changes or inspect my stashed files.

Behaviour:
The dialog is shown and "Loading..." freezes. I can close the dialog and continue working with gitextensions. 

Expected Behaviour.
The dialog is shown and shows me the files to commit or the files that are in the stash.

Platform:
This behaviour does not occur on Windows, so it is related to the Mono version only (I did not check with Mono on Windows but only on Ubuntu 16.04).

Steps to reproduce:
1.) Start Git, Open repository (note that the repository has submodules)
2.) Make changes to one (or more) files (subfolder)
3.) Add one or more new files in (subfolder)
4.) Stash some of the files
5.) Press Commit 
6.) After close Press Stash Changes -> View Stash 

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**

It is not a Windows issue at all. I don't know if it worked on any previous releases.

A similar bug was reported 2012: https://github.com/gitextensions/gitextensions/issues/1357 but the behaviour here is different.

**Comment by alright** [comment]
Caught this issue. Resolved by upgrading mono from 4.2 to 4.8.
 
Use this instruction http://www.mono-project.com/docs/getting-started/install/linux/ to install it properly and then do sudo apt-get upgrade && sudo apt-get dist-upgrade

**Comment by rkatzmann** [comment]
Thank you for the hint. This might be a possible solution for me, but still 16.04 is an LTS and it's not always possible to upgrade packages due to dependencies. Also for me as developer I might be tied to version 4.2 until the end of this project (have to test it). 

Any workarounds if this is the official project opinion ?

**Comment by rkatzmann** [comment]
I was able to convice the team that the new mono version is of benefit not only for this tool.
