### ISSUE TITLE
[feature request] commit history on the leftside/details on the rightside

### ISSUE THREAD

**Issue by geanv** [gitextensions/gitextensions#3610]
**Do you want to request a *feature* or report a *bug*?**
A *feature*.

**What are the details of the feature?**
As most of our monitors are wide screen with 16:9 width-to-height ratio, can you provide an option on the UI, which supports to split the main window vertically. The leftside shows the commit history (like the upper part of current UI), and the righside show the details of a commit (like lower port of current UI).

**Why we need this feature?**
By vertically splitting the window, we can have more information on the screen. Thanks!

**Comment by jbialobr** [comment]
I couldn't find your issue so I created a new one #3660.
