### ISSUE TITLE
Upgrade to .NET 4.6.x?

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#3611]
Are there any plans to move off .NET Framework 4 Client Profile?
I don't know much about non-Windows platforms, but latest Mono is [compatible with 4.6 and C# 6](http://www.mono-project.com/docs/about-mono/compatibility/)...

**Comment by pmiossec** [comment]
Can you give us more info. What are the advantages of moving?

**Comment by crypto-rsa** [comment]
C# 6 introduced several language constructs which IMHO make the code more readable and less error-prone. See [the list](https://docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-6). For me the most important ones are [null-conditional operators](https://docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-6#null-conditional-operators) and [string interpolation](https://docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-6#string-interpolation).

**Comment by pmiossec** [comment]
Oh. My question was more about the framework. 

Because I know the advantages of updating the C# language version but it requires to have a more recent version of Visual studio (here 2015 for v6) and it's always difficult for an open source project to require the last version (that reduces the number of people that could contribute). 

But that's something that we should think about because there is community versions that are free...

**Comment by RussKie** [comment]
You can't open the solution in anything less than VS2015 (#3411)

**Comment by jbialobr** [comment]
I think the main concern here is how many end-users have installed older versions of net framework. I remember a user complaining that it is an issue in big companies, because they are not allowed to install a newer version of net framework by themselves.

**Comment by RussKie** [comment]
Those who is unable to install newer versions of .Net will still be able to
install any of the released versions of GE.
In the end of the day GE is a glorified UI over git cli.

At some point you need to make a cut and move on to the newer versions and
innovate.
Else we would still be writing in VB6 and designing websites for IE6
because that's what some enterprises still use ;)

**Comment by jbialobr** [comment]
OK, so let's release the 2.50 version and after that move to the latest .net framework.

**Comment by vbjay** [comment]
Curious how this will affect mono clients?

On Tue, Mar 28, 2017, 12:14 AM Janusz Białobrzewski <
notifications@github.com> wrote:

OK, so let's release the 2.50 version and after that move to the latest
.net framework.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/3611#issuecomment-289658082>,
or mute the thread

**Comment by RussKie** [comment]
Mono supports .net 4.6
Again, thise who unable to update can continue to use existing versions

**Comment by vbjay** [comment]
Awesome. I don't use it but knew it might be a problem.

**Comment by RussKie** [comment]
Sooooo, are we upgrading? 😉

**Comment by jbialobr** [comment]
I still see in bug reports that many users use .net 4.0.
We can use C# 6 syntax while still targeting .net 4.0. We can not use new types introduced in the later runtimes. Do we need any of these new types?

**Comment by RussKie** [comment]
Async/await

**Comment by RussKie** [comment]
.net 4.0 was released in 2010, today is mid 2017... isn't it is time to move on?
Those using .net 4.0 - will continue to use 2.50, why do the rest of us has to be stuck in 2010?

**Comment by vbjay** [comment]
Amen.

**Comment by jbialobr** [comment]
Ok, let's move on.

**Comment by RussKie** [comment]
I don't suppose 4.7 is a good option, since it is new and unlikely to be installed by the majority of our users.
Should we target 4.6.2?

**Comment by vbjay** [comment]
If we can bootstrap the download of 4.7 then I don't see a problem using
it.

**Comment by vbjay** [comment]
Along with the bootstrapping we could put a link on the releases page.
Saying 4.7 is required.

**Comment by RussKie** [comment]
I've deleted my earlier comment because mono is an ongoing concern.
Mono supports .NET 4.6, still trying to figure whether it is 4.6.0 or 4.6.1 or 4.6.2.
I will need to try it first

**Comment by vbjay** [comment]
http://wixtoolset.org/documentation/manual/v3/howtos/redistributables_and_install_checks/install_dotnet.html

**Comment by pmiossec** [comment]
At least, 4.5.2 :  For Windows Forms applications, improvements were made
for high DPI scenarios.

Why not 4.7? Support for High-DPI awareness support in Windows Forms ;-)

**Comment by RussKie** [comment]
If we ditch support for Mono (which I'm all for) then we can go in guns blazing and target 4.7.

**Comment by vbjay** [comment]
Yep. Mono winforms support is iffy and not being developed.  We have core
coming. I say we point towards .net standard equal to .net 4.7.

**Comment by RussKie** [comment]
Mono winforms hasnt been touched for like 10 years. It's pretty broken, and
makes it insanely hard to build good usable UI and provide good UX.

I don't believe .net core will help with problems on mono winforms in
anyway...

Perhaps we need to start looking at alternatives to mono winforms,
something like gtk#....

**Comment by vbjay** [comment]
Yep. I haven't messed with it or even done much research. What about wpf
with .net standard?  Not exactly sure where the support is on that.

**Comment by RussKie** [comment]
Neither have i. I didn't install Mono + Visual Studio for Mac until had to deal with Mono's rendering idiosyncrasies for my dashboard uplift.

WPF doesn't look like a strategic platform for xplat (http://www.mono-project.com/docs/gui/wpf/), neither does Xamarin.

There are few possible contenders for truly xplat solution:
- http://www.mono-project.com/docs/gui/gtksharp/
- https://github.com/AvaloniaUI/Avalonia
- https://github.com/mono/xwt

But any of the above will mean that the whole UI will need to be re-engineered, which is a monumental task.
Damned if we stay with Mono and damned if we ditch it...

Either way it is up to the captains (@jbialobr @KindDragon et al) have to decide which way to steer the ship....

**Comment by KindDragon** [comment]
> Why not 4.7? Support for High-DPI awareness support in Windows Forms ;-)

We already support 4.7 high-DPI improvements, but minimal required version I think should be 4.7. User can update .Net Runtime manually

**Comment by RussKie** [comment]
What about the Mono?

**Comment by KindDragon** [comment]
> but minimal required version I think should be 4.7

Typo, 4.6

**Comment by RussKie** [comment]
Done
