### ISSUE TITLE
KDiff3 is not installed?

### ISSUE THREAD

**Issue by neslekkim** [gitextensions/gitextensions#3612]
Have been installing gitextensions v2.49.03, but KDiff3 is not installed, thus I get the settingscreen everytime I try to do anything.
Have tried to repair the install, but still it does not install.

On my harddrive, for another program, there is an copy of kdiff3.exe for some reason, is that the reason kdiff3 is not installed? this version is not included in any path..

**Comment by pmiossec** [comment]
Kdiff3 is not installed because you you downloaded the "Setup" and not the "SetupComplete" that contains and install some extra tools (git and Kdiff3).

"Repair" is just to try to find a diff tool, not install one. (because we do not know which one you want!) 

You will have the settings screen until you fix it yourself, by installing Kdiff3 or another diff/merge tool yourself. No miracles here...

**Comment by neslekkim** [comment]
well, it didn't say on the downloadpage that you needed that one, I thought the complete was including git, but didn't think about kdiff there. I have installed git separately, so I didn't see any point in using the complete version.
Will the complete version skip installing git if it is already installed? (or can one choose?)

**Comment by vbjay** [comment]
Do you not understand how multi feature installers work?  They give you the main product, and optional features.  Try it.  You will get what you need.

**Comment by neslekkim** [comment]
How can you know if it is an multifeature installer or not, before you download and try it?, document the shit, and I won't ask such questions.

**Comment by vbjay** [comment]
https://git-extensions-documentation.readthedocs.io/en/latest/getting_started.html#installation

**Comment by vbjay** [comment]
http://gitextensions.github.io/

**Comment by neslekkim** [comment]
Thanks, I was on the last link there, didn't find the docs, but clearly there are good docs..

**Comment by vbjay** [comment]
![image](https://cloud.githubusercontent.com/assets/3629489/24366049/eb52b620-12e5-11e7-8614-06a3d7cebe1c.png)
