### ISSUE TITLE
Shortcut key for "Create fixup commit"

### ISSUE THREAD

**Issue by webmaster33** [gitextensions/gitextensions#3616]
**Do you want to request a *feature* or report a *bug*?**
feature, GUI

**What is the current behavior?**
Can't find any shortcut key for "Create fixup commit"

**What is the expected behavior?**
Add a shortcut key for "Create fixup commit", which can be changed in Settings/Hotkeys

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
Git Extensions v2.49
OS: Windows 7

**Comment by webmaster33** [comment]
Thanks very much for implementing it! 

Couldn't be possible to target 2.49.04?

**Comment by crypto-rsa** [comment]
@webmaster33: No problem, I find the feature very useful myself so I was happy to implement the hotkey :-)

**Comment by jbialobr** [comment]
>Couldn't be possible to target 2.49.04?

New features go to the next major release. Minor releases are only for small bug fixes.
https://github.com/gitextensions/gitextensions/wiki/Project-Workflow
