### ISSUE TITLE
Unable to push to remote location with SSH

### ISSUE THREAD

**Issue by cova-sa** [gitextensions/gitextensions#3618]
I'm trying to connect to a git repo provided by WP Engine. I was trying to follow the directions using the guide https://carriedils.com/git-push-wp-engine/ but because I'm using the Git Extensions GUI it didn't make a lot of sense. The error I get when I attempt to push to the repo (git@git.wpengine.com:production/githubinstall.git) is below:

> "C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "githubinstall" refs/heads/v1.0:refs/heads/v1.0
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> Done
> 
> Press Enter or Esc to close console...
> 

At this point I tried connecting using Git Bash, and I was able to connect without issue. I talked with the support team at WP Engine and they stated that if I'm able to connect via Git Bash then there must be a configuration problem in Git Extensions. 

I initially created the SSH key using the putty generate key function in Git Extensions, but I wasn't able to add that key to GitHub or to WP Engine for verification so I used https. That worked fine for GitHub, but then I realized the WP Engine only uses SSH verification. So I then created another SSH using Git Bash and that uploaded to GitHub and WP Engine just fine. However, whenever I try import this key to Git Extensions there's no save button so I don't know if it is using the new correct SSH key. I also don't know if I'm handling the whole process properly.

Any insight would be helpful and greatly appreciated.

**Comment by jbialobr** [comment]
Read this http://git-extensions-documentation.readthedocs.io/en/latest/remote_feature.html#create-ssh-key.
Probably you have configured it to work with openSSH and set GitExtensions to use putty.

**Comment by cova-sa** [comment]
Thanks, this ended up being exactly what I needed.
