### ISSUE TITLE
Add menu item to solution and project nodes 

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#3620]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
No option to browse the solution's folder, or selected project's folder in GE.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Be able to browse to solution/project folders in GE by right clicking the project or solution node in solution explorer.  Also add dropdown to browse button in toolbar to be able to select current project, or solution options.  
**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
N/A

**Comment by RussKie** [comment]
The request wording allows quite a bit of room for various interpretations. 
Could you please provide clarity and, maybe, visualise what is that you wish.

**Comment by vbjay** [comment]
I think the idea is he wants this feature
![image](https://user-images.githubusercontent.com/3629489/34417186-2442d1dc-ebc5-11e7-9ba3-1c132ec3b8cc.png)
in GE.  

So I right click on *.*proj or *.sln files and pick browse to folder.  Explorer opens folder that contains that file.  I say why not do this with all files and folders in file tree and diff tab.

**Comment by RussKie** [comment]
We already have it

[image: Inline images 1]


Or am I missing something?

**Comment by GintasS** [comment]
I think we have this already, as per @RussKie comment, and me checking that:
1. File explorer toolbar item exists
![image](https://user-images.githubusercontent.com/20372363/130214186-ccad5418-4baf-4065-9d39-7bbfab2782e2.png)

2.  In Diff view, we have this option.
![image](https://user-images.githubusercontent.com/20372363/130214341-3af00dd7-3204-497a-a8d6-0919be4ff8f7.png)

3. File tree
![image](https://user-images.githubusercontent.com/20372363/130214547-58cd46e6-560a-4727-b7cb-47e4c1c52c2b.png)

Closing this.

**Comment by RussKie** [comment]
I believe this is a VS/VSIX related query.
