### ISSUE TITLE
add WM_CLASS in application (feature, linux)

### ISSUE THREAD

**Issue by glebmtb** [gitextensions/gitextensions#3621]
Modern Linux desktop environments (Gnome 3, Ubuntu Unity, Docky) use the WMClass property to associate windows with the owning application. Many Java-based applications have the problem where the windows created by the application are not associated with the shortcut used to start the application (so the dock contains multiple copies of the same icon).

So the field called StartupWMClass is a string that defines in which class the application is grouped in the Unity Launcher at startup.

You can find out which WM_CLASS your window has got when you type in a terminal:

xprop WM_CLASS
and then click at the window. In case of the gnome terminal the output is as follows:

WM_CLASS(STRING) = "gnome-terminal", "Gnome-terminal"
So all windows with WM_CLASS "gnome-terminal" and "Gnome-terminal" are grouped together.

Git Extension does not have this option
run "xprop WM_CLASS"
I get "WM_CLASS:  not found."

**For Git Extension WM_CLASS not set**

By default, Mono application windows do not have a WM_CLASS property.
This causes problems with Linux/X11 window managers, such as not being able to add the application's icon to docks

**Please add support for the WM_CLASS property.**
I have found some sample code that looks useful:
http://stackoverflow.com/questions/11453687/how-can-i-change-wm-class-for-a-winforms-application-on-linux

**Comment by Timk90** [comment]
+1

**Comment by apetrovs** [comment]
+1

**Comment by ssfivy** [comment]
+1

**Comment by RussKie** [comment]
Pull requests are welcome to 2.51 branch

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
