### ISSUE TITLE
Multi column Start Page

### ISSUE THREAD

**Issue by francoas** [gitextensions/gitextensions#3624]
New Feature

The Start page, on the right side present a single column list of repositories.
If you work with many of them you have to use the vertical scroll bar, while it would be useful a multi column (vertical wrap) layout, especially because there is a lot of unused free space on the right

**Comment by RussKie** [comment]
I've been tinckering with few ideas...
Will something like this work?

Floating window:
![image](https://cloud.githubusercontent.com/assets/4403806/24695779/6c3170f6-1a2a-11e7-922c-eb1e141fe79a.png)

Full-screen (1900x1200)
![image](https://cloud.githubusercontent.com/assets/4403806/24695856/c9bdb2e8-1a2a-11e7-8bf0-9082401de35e.png)

**Comment by francoas** [comment]
Actually I was thinking of something like this

![image](https://cloud.githubusercontent.com/assets/3007941/25889066/d17b357e-3568-11e7-8c94-588db6a450e6.png)
