### ISSUE TITLE
Primary buttons for certain dialogs are hidden when running under Mono

### ISSUE THREAD

**Issue by codygray** [gitextensions/gitextensions#3625]
There is a serious user-interface bug in GitExtensions when running under Mono on Linux (specifically, Mint 18.1 Cinnamon). It manifests as the buttons in certain dialogs being clipped or entirely invisible. Resizing the window doesn't help; the buttons stay invisible. It seems that the auto-scaling code is incorrect.

You can see this clearly in the Remote Repositories dialog (or, *not* see it, as the case may be):

![screenshot of the Remote Repositories dialog, showing the problem](https://cloud.githubusercontent.com/assets/5993051/24559432/44d4b614-1604-11e7-9fa4-5da4378128ba.png)

Reproducing it is dead-simple. Just install the application on Linux using Mono, and then open the Remote Repositories dialog.

The same bug is present in the Create Tag, Delete Tag, Create Branch, Delete Branch, Checkout Branch, Rebase, and Resolve Merge Conflicts dialogs:

![screenshot of the Create Tags dialog](https://cloud.githubusercontent.com/assets/5993051/24559686/323e4ee2-1605-11e7-937a-f9ec76d3215b.png)

...and possibly others that I haven't tried to use yet.

This is a serious usability problem. Even for users who *know* that the buttons are there because they've used the app on Windows, it isn't clear how to invoke them. The Esc key usually works well enough to trigger the Cancel button, but OK is more difficult, since controls/widgets sometimes eat Enter key presses.

This bug is still there in the current version of GitExtensions (2.49.03), and it was there in the previous version. I don't know how far back it goes, but I suspect it's been there a long time.

**Comment by RussKie** [comment]
The remotes management screen has been redesigned and the new one is expected to come out in the next release.
I don't have a mac/nix box to test a mono version, so unable to tell whether the woes with this screen have been fixed.

**Comment by RussKie** [comment]
@jbialobr could assign this issue to me so I don't forget about it?

**Comment by jbialobr** [comment]
Unfortunately GitHub does not let me do so.

**Comment by RussKie** [comment]
I think it would if you make me a contributor *hint hint*

**Comment by jbialobr** [comment]
It is GitHub that marks users as contributors. I believe you are not marked as a one because of your fake email address. The only ones GitHub allows to be assignees are: members and the issue author.

**Comment by RussKie** [comment]
Thank you for clarifying.
Damn... there go all my commit history.

**Comment by jbialobr** [comment]
Perhaps you can fix it with .mailmap

**Comment by RussKie** [comment]
Github doesn't seem to support it - https://github.com/holman/ama/issues/551#issuecomment-46129792

**Comment by RussKie** [comment]
The remotes management form has some layouts imperfections but it is usable
![image](https://user-images.githubusercontent.com/4403806/33654455-49f3900e-dac4-11e7-891c-0f123ea0d446.png)

It has resize issues where save button moves to the right and doesn't come back left, but if close-open form it layouts correctly again. 
This is certainly a bug, but it is not a blocker. I am not planning to fix it any time soon. PRs are welcome.

. . .

Create tag dialog lays out correctly:
Win 10
![image](https://user-images.githubusercontent.com/4403806/33654639-d604615e-dac4-11e7-9812-7fbb4c35f4d2.png)

Ubuntu
![image](https://user-images.githubusercontent.com/4403806/33654655-e158b604-dac4-11e7-8e98-997066c905f1.png)

. . .

So does the delete tag dialog
Win 10
![image](https://user-images.githubusercontent.com/4403806/33654823-6ae1d608-dac5-11e7-9541-38f781040a97.png)

Ubuntu
![image](https://user-images.githubusercontent.com/4403806/33654832-7393c054-dac5-11e7-9a4b-961fedcc110d.png)

Feel free to raise an issue(s) for specific dialogs if you have dramas with the current version.
