### ISSUE TITLE
origin url not updated when switching between repos

### ISSUE THREAD

**Issue by Gouri-Sankar** [gitextensions/gitextensions#3626]
**Do you want to request a *feature* or report a *bug*?**
bug (if you can re-create, please consider as high priority)

**What is the current behavior?**
If we switch between two different repos, the origin url is pointing to previous repo when we toggle between Remote and Url radio buttons in Pull dialog.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Clone two different repos - repoA and repoB
2. Open Git Extensions and click on Open Repository and choose reopA and open it.
3. Open Pull dialog, and toggle between **Remote** and **Url** radio buttons on the 'Pull from' section. Verify if the url is still pointing to the correct repo.
4. Hit X to close pull dialog and now open repoB.
5. Now, click on the Pull dialog and initially you will notice the correct origin url , but when you click on Url radio button, it changes to the previous repoA url **(bug)**. 
6. After that, even if you toggle between those two radio buttons, it will still reflect previous origin url which is bad if the devs don't notice the url very carefully (every time) and start pulling changes from one repo in to a completely different repo.
7. This issue happens only for one of the repos between the two. If you switch back to repoA, the issue will not happen. But, if you go back to repoB again the origin Url points to old one when you toggle between those two radio buttons.

**What is the expected behavior?**
If we switch between two different repos, the origin url should reflect the corresponding repo url even when we toggle between Remote and Url radio buttons onPull dialog.

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
Git Extensions - Version 2.49.03
git version 2.10.1.windows.1
Yes, this issue was there in previous version of Git Extensions as well.

Thanks for taking a look!
-Gouri

**Comment by RussKie** [comment]
Without looking at the code, it looks like whenever you switch to the 'Url' it picks the very first option from the url dropdown.

**Comment by jbialobr** [comment]
>After that, even if you toggle between those two radio buttons, it will still reflect previous origin url which is bad if the devs don't notice the url very carefully (every time) and start pulling changes from one repo in to a completely different repo.

Why does the user change to pull from URL and want to pull from the same URL?

**Comment by vbjay** [comment]
I have noticed the same issue. It is a problem. The remote URL for pull and
push need work. It should not fill in a value unless I pick it or it grabs
the value from clipboard. Also if there is already a value in the remote
for that URL, don't change it.

**Comment by Gouri-Sankar** [comment]
@jbialobr - That is the only easy for the devs to verify the remote url (making sure that they pull from or push to the correct repo) before they pull/push their code from/to remote repo.

**Comment by Gouri-Sankar** [comment]
Thanks for fixing it. When is it going to be released to public?

**Comment by vbjay** [comment]
Let me introduce you to
https://github.com/gitextensions/gitextensions/milestones

**Comment by vbjay** [comment]
The other thing you can do is build the build script to create a current
installer and install it for yourself.
