### ISSUE TITLE
During installation, getting error 1722

### ISSUE THREAD

**Issue by dwainew** [gitextensions/gitextensions#3634]
during the install of git extensions, I'm getting the following error, this is reproducible and occurs even after a fresh reboot with nothing else running.  however, when I launch extensions and look at help, it shows this version is installed!?  I don't know if it's a stable/complete installation... :

Product: Git Extensions 2.49.03 -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action vim3F5A3BF994315E3D892BA2D2A42C9C92, location: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\VSIXInstaller.exe, command: /q  /skuName:community /skuVersion:14.0 "C:\Program Files (x86)\GitExtensions\GitExtensionsVSIX.vsix" /admin

**Comment by vbjay** [comment]
Please search​ issues before posting your own.

**Comment by dwainew** [comment]
Thanks for the suggestion.  I did.  the closest I found was https://github.com/gitextensions/gitextensions/issues/3469, which doesn't mention 1722.  One answer states "install 2.48" another to "disable install of VS extensions" neither of which do I want to do or seem reasonable.  Also, I plainly stated in my post that, despite the installation failing, and the installer claiming to have successfully rolled back all changes, that 2.49.03 is the version actually showing up in the help About!  I would think THAT would bother the developers of the installer and warrant some investigation, don't you?  What posts are you referring to that I missed?  To be helpful, could you referenced a few for my edification?

**Comment by vbjay** [comment]
The one that mentions vs extensions is the one. The error number is not
mentioned, however it is the same error message.

**Comment by RussKie** [comment]
Is this still an issue with 2.50?

**Comment by RussKie** [comment]
Please reopen if it is still an issue in the current version
