### ISSUE TITLE
File history incorrect filtering

### ISSUE THREAD

**Issue by diegotrsl** [gitextensions/gitextensions#3636]
--- GitExtensions2.49.03, Git 2.8.1.windows.1, Microsoft Windows NT 10.0.14393.0

When i select the "File History" menu at the "File Tree" tab, the window opened is not filtering commit that changes only the file selected.

First commit appearing:
![image](https://cloud.githubusercontent.com/assets/22968310/24727799/bd0049be-1a2d-11e7-99fd-69014e88b3f1.png)

Observe that the diff tab is blank, cause the commit don't changed the file selected:
And that file don't have so many frequent changes like shown there...

![image](https://cloud.githubusercontent.com/assets/22968310/24727721/76a4ea10-1a2d-11e7-9062-23c6ae0ad7be.png)

When i execute "git log filename" in the git bash, another commits are returned.

**Comment by jbialobr** [comment]
Do you have the "Full history" option checked?
To see that, open the context menu for revision list.
![gitext](https://cloud.githubusercontent.com/assets/1003909/24741104/d6c4a260-1aa4-11e7-83eb-e8276004fba4.png)

**Comment by diegotrsl** [comment]
Yes, it was checked. Now it worked as I expected. I don't remember to check it, so i think i checked accidentally.

Thanks for the answer and sorry to take your time.
