### ISSUE TITLE
[Feature Request] Build Server Integration - Visual Studio Online

### ISSUE THREAD

**Issue by FizzBuzz791** [gitextensions/gitextensions#3639]
Is there the possibility of including this in the Build Server Integration menu? Visual Studio Online is a bit different to TFS unfortunately, so I don't think I can use the TFS option and try to configure/butcher for VSO.

**Comment by pmiossec** [comment]
>Visual Studio Online is a bit different to TFS unfortunately

Can you give some information about that because in my mind it was the same thing in terms of API?
Is it since they revamp the builds or the authentication that is different?
Or because we now must to use the rest API?
I don't know because that's a long time I look at it...

**Comment by FizzBuzz791** [comment]
Ah, I've looked into specifics, but we have two related projects that are hosted slightly differently, one uses git source control, the other uses the built-in source control, the URL's are massively different, I don't think the `default collection` is the right usage.

`https://me.visualstudio.com/Project1/_git/MainBranch`
vs.
`https://me.visualstudio.com/Project2/_versionControl?path=%24%2FProject2%2FMainBranch&version=T&_a=contents`

**Comment by vbjay** [comment]
They have a git to TFS bridge.

**Comment by FizzBuzz791** [comment]
OK, could you maybe assist with a setup guide or something then, because I'm at a loss as to how to do it. As far as I can tell, the `Team collection name` and the `Project name` are essentially the same thing for VSO. Plus, I don't think there's the option to login as guest, so I'm not sure which credentials it's pulling? I guess it's using the git config ones? In any case, the configurations I've tried are not working.

**Comment by vbjay** [comment]
https://www.visualstudio.com/en-us/docs/git/share-your-code-in-git-vs
