### ISSUE TITLE
MINGW32 called by extension reports dll is already in memory at location

### ISSUE THREAD

**Issue by armplinker** [gitextensions/gitextensions#3640]
I had a vexing issue trying to use git svn to clone a subversion repo.  It endlessly reported that mysqlite.dll was already in a given memory location and it could not fork (fork being the operative verb I believe).   The command line in the mingw32 terminal window was something like **"C:\Program Files (x86)\git\git.exe" svn clone** .....  anyway the git **exe** was wrapped in d-quotes.  So I scraped out the command and changed the command part to just say  
 **svn** git clone  ..... and MAGIC - it runs.  So apparently the use of the fully qualified EXE name in the shell was invoking a second copy of git.exe that attempted to lay itself into the same memory area or some-such rather than running in its own space

This was with the latest extension version and the version of git it installs, as of this morning.

**
Extensions 2.49.03
git version 2.10.1.windows.1
Windows 10 Home
64-bit**

**Comment by vbjay** [comment]
OS version details, git --version.

**Comment by cristianst85** [comment]
Similar problem here. Trying to clone a SVN repository from UI.

![image](https://cloud.githubusercontent.com/assets/12585988/26748946/bde6b082-480b-11e7-8993-9502016a2019.png)

GitExtensions 2.49.03 (built from latest commit 852fa657 from master branch)
Windows 7 x64, Windows 10 x64 (only tested with Git version 2.12.2.windows.1 (32-bit))

|           Git Version            |   Reproducible   |
---------------------------|------------------
|2.10.1.windows.1 (64-bit) | No                     |
|2.12.2.windows.1 (32-bit) | Yes                    |
|2.12.2.windows.1 (64-bit) | No                     |
|2.13.0.windows.1 (32-bit) | Yes                    |
|2.13.0.windows.1 (64-bit) | No                     |

It seems that this is occurring only when using the 32-bit version of Git.

**Comment by cristianst85** [comment]
This is a bug in the 32-bit version of Git-SDK.

[Investigate why t9164 fails in the 32-bit SDK, but not in the 64-bit SDK](https://github.com/git-for-windows/git/issues/362)

**Comment by arnadan** [comment]
I am quite new to git and this is my first post to this forum. I see that this issue has been closed and hope to not offend anyone by still writing to this thread. But I have that exact same issue on the 64bit version of git and can not find help for it anywhere. (Yes, I have used Google but no sucess...)

Here are the details of my git installation:

```
$ git --version --build-options
git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

When issuing a git svn fetch the fetch runs for a few hours and I can see the progress. But then "address space needed" error as described above shows up again.

Is this a bug in the latest git version or am I missing something?

**Comment by pmiossec** [comment]
@arnadan 
The problem is with git and here it is the project for a GUI using git. So we are not the best placed to answer your questions.
Maybe you should ask your question in a new issue here: https://github.com/git-for-windows/git/issues

**Comment by pmiossec** [comment]
@arnadan But you still can test a previous version of git (because 2.35 changed the version of Cygwin) to see if you have not discovered a new regression...
Test for example https://github.com/git-for-windows/git/releases/tag/v2.34.1.windows.1

**Comment by arnadan** [comment]
@pmiossec Thank you for your answer. I have not tested with git version 2.34.1.windwos.1 : still same problem. After running the git svn fetch for about 12 hours I get

```
Can't fork, trying again in 5 seconds at C:/Program Files/Git/mingw64/share/perl5/Git.pm line 1647.
      1 [main] perl 591 child_info_fork::abort: address space needed by 'msys-svn_wc-1-0.dll' (0x82A2C0000) is already occupied

```

Will try it again later on some other PC.
