### ISSUE TITLE
Remote repositories, option to add two or more url to same remote

### ISSUE THREAD

**Issue by lucianotres** [gitextensions/gitextensions#3641]
**Feature**

In "Push" window we can add remote repositories for easily do the task. The git command line allow add many push url to the same name. 
For example:
`git remote add -m --mirror=push all e:/someplace/repo.git`
`git remote set-url --add --push all e:/otherplace/repo.git`
`git remote set-url --add --push all e:/anotherplace/repo.git`

With that I have now a remote push called "all" that I can push to all three at same time.
It would be great if had a option in "Remote repositories" window for do this and manage all urls at the same name.

**Comment by jasonsparc** [comment]
I would like to have this feature too :)

Right now, I have a repo with a remote `origin` with multiple `pushurl`'s but the `gitex` UI would simply list the last `pushurl`

**Comment by GintasS** [comment]
You could have this, but with different names or slightly different. @RussKie what do you think, should we keep this issue?

**Comment by RussKie** [comment]
This can be achieved, though somewhat indirectly - i.e. one can set multiple remotes, and then push to multiple remotes.

Given the request hasn't sparked any interest from the author or the community it doesn't look like a high value feature. Proposals how the remotes dialog can be enhanced to accommodate the requested functionality is welcome, followed by PRs with implementations.
