### ISSUE TITLE
[Feature Request] Ability to export / import Categories (favorites)

### ISSUE THREAD

**Issue by Shepdog87** [gitextensions/gitextensions#3648]
I use GitExtensions daily and have spent a considerable amount of time setting up the "Categories" to quickly access repositories.  These are displayed on the start page, and the list of them can be viewed by going to Tools > Settings > Git Extensions > Start Page.  

I recently decided to upgrade my version of Git Extensions and all of my categories were gone.  I tried looking in the install path of Git Extensions, but could not find any files related to categories.  I am now hesitant to update my version fearing that the same thing will happen.

It would be extremely useful if the categories can be exported and imported.

I am currently using Git Extensions version 2.49 on Windows 7.

**Comment by RussKie** [comment]
Worth noting https://github.com/gitextensions/gitextensions/issues/3624

**Comment by webmaster33** [comment]
+1 agree
