### ISSUE TITLE
Add Visual Studio Code to the editor list

### ISSUE THREAD

**Issue by otbutz** [gitextensions/gitextensions#3652]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the expected behavior?**
Visual Studio Code being displayed in the "Git Config > Editor" dropdown menu

The following command seems to do the job:
`Code.exe --wait`

**Comment by pmiossec** [comment]
That seems not very difficult to do. 
Perhaps you could do the pull request?

Have a look here: https://github.com/gitextensions/gitextensions/blob/2d15fc1a68f999d56f08326e759becb35fdbb1f9/GitUI/CommandsDialogs/SettingsDialog/EditorHelper.cs

**Comment by RussKie** [comment]
Fixed in https://github.com/gitextensions/gitextensions/pull/3919
