### ISSUE TITLE
Checkout branch dialog size calculation broken in master

### ISSUE THREAD

**Issue by KindDragon** [gitextensions/gitextensions#3654]
![image](https://cloud.githubusercontent.com/assets/224272/25049682/b7c1f8d8-214b-11e7-968c-36ae618ccdfe.png)
Every time I open it gets bigger
/cc @jbialobr

**Comment by KindDragon** [comment]
BTW `maximize form` button should be disabled for this dialog

**Comment by jbialobr** [comment]
Can not reproduce. Can you try with this chaneg https://github.com/gitextensions/gitextensions/commit/12e5b631d1ae26c1099b44d4640490d39bf74d3c ?
Are you able to debug the place where the width is increased?

**Comment by KindDragon** [comment]
Can you open FormCheckoutBranch in WinForms designer?

**Comment by RussKie** [comment]
Running latest I can't repro the issue. Tried with few different branch names, both long and short

**Comment by KindDragon** [comment]
Maybe only with latest .Net 4.7 or high dpi monitor

**Comment by KindDragon** [comment]
This error is caused by the fact that `AutoScaleMode` was missing
https://github.com/gitextensions/gitextensions/commit/fdd3d1789b42d63984fca74cebfd9f9072e01068#diff-d0ad69a809cade55aeb889d0087e0c10
