### ISSUE TITLE
Radio button selections on Pull dialog box

### ISSUE THREAD

**Issue by Gouri-Sankar** [gitextensions/gitextensions#3655]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Random click on the text of the radio button is selecting the radio button on the Pull dialog box

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
On the Pull dialog box, there are a bunch of radio buttons and second one under Merge options has a long verbiage. The problem here is, after done with the selection of Remote branch and to just exit out of the dropdown, we tend to click somewhere on the form and it's very possible (and it is happening) that the click can land on the lengthier second radio button verbiage which is a rebase option and not the one we want to select. Unless devs notice they un-intentionally selected the second radio button, they will be doing a re-base on their local and mess up things.

**What is the expected behavior?**
Please do not select the radio button on click of text. Select the radio button only when we click on radio button circle.

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
Git Extensions 2.49.03

**Comment by RussKie** [comment]
That's how Windows radiobutton control work - you can either click the radio button or its text.

> after done with the selection of Remote branch and to just exit out of the dropdown

Why don't you just click "Pull" button?
Other than that - don't click the text and you won't have the problem

**Comment by jbialobr** [comment]
Just press the TAB key.
