### ISSUE TITLE
Only root gitignore is used when there's multiple repository with gitignore

### ISSUE THREAD

**Issue by golddragon007** [gitextensions/gitextensions#3659]
**Do you want to request a *feature* or report a *bug*?**
Bug.
**What is the current behavior?**
If you have a root with a gitignore, and inside the root you have another repository with a gitignore, the just the root gitignore is used, the other gitignore is not used. (however, the git console use both!)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create a root repository with gitignore.
2. Create some hierarchy and then inside that create a repository with gitignore. (possibly you don't need repository only gitignore to do this, but in my case this was the scenario)
3. Use both gitignore to ignore something inside the same directory.
4. The 2. gitignore won't work inside gitextension's commit dialog.

**What is the expected behavior?**
It's need to read all the gitignore files and use them, like the 'git status' does.
**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
I did this with windows 10 and the newest git extension, but I find this inside an older version too. Possibly all versions has this problem in all system.

**Comment by vbjay** [comment]
Read up on what submodules are.

**Comment by vbjay** [comment]
https://git-scm.com/docs/git-submodule

**Comment by jbialobr** [comment]
It works for me. Can you create an example repo, zip it and upload somewhere?

**Comment by golddragon007** [comment]
OK. this was a false alarm, the console just show folder_name/ when the ui list all the items in the folder_name which cause this fake feeling. (also I put a dir somewhere under git but I don't know why I did it... lol)
