### ISSUE TITLE
Option to show revision details netx to the revision list

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#3660]
On large srceens thaere is enough place to show revision details next to the revision list.
I think it could be a default layout and could be switched back to the old one in the settings.
In the new layout the Diff tab should be selected on app start (Perhaps it should be added as the first tab).
I will post four screenshots with different combinations of locations of revision info and gravatar.
Please react with +1 on the post that shows the layout you like the best.

**Comment by jbialobr** [comment]
![arightright](https://cloud.githubusercontent.com/assets/1003909/25271935/1e7728fc-2686-11e7-98d5-3c354e10744e.png)

**Comment by jbialobr** [comment]
![arightleft](https://cloud.githubusercontent.com/assets/1003909/25271933/1e76c77c-2686-11e7-9f98-116b269200d1.png)

**Comment by jbialobr** [comment]
![aleftleft](https://cloud.githubusercontent.com/assets/1003909/25271936/1e777be0-2686-11e7-8fef-b1ab617b6ec5.png)

**Comment by jbialobr** [comment]
![aleftright](https://cloud.githubusercontent.com/assets/1003909/25271934/1e76e2c0-2686-11e7-92f4-5c2d73c5cf91.png)

**Comment by jbialobr** [comment]
Duplicates #3610.

**Comment by pmiossec** [comment]
Great!

Is that needed to keep the vertical white margin when the avatar is displayed on the left?
It's lost space to display commit message for me (and that make me prefer one over the other if we can't remove it....)

**Comment by jbialobr** [comment]
It can be removed, but I don't know why it was introduced in the first place, but I know it was done on purpose, so I just left it untouched.

**Comment by pmiossec** [comment]
I think it was there to align the commit message with the other commit metadata. But it make less sense when place is constrained...
