### ISSUE TITLE
Filtering by status in Diff tab

### ISSUE THREAD

**Issue by webmaster33** [gitextensions/gitextensions#3663]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
In Diff tab, you can filter the files, but can not reorder the file list.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
SUGGESTION: 
In Diff tab, you should be able to FILTER files
- by status (added, modified, renamed, etc), 
- by permission change (for example permission change from old mode 100644 to new mode 100755), 
- by name or path (already implemented through textbox), 
- by git creation date interval (earlier/later than 2016 or between >2011 <2013), 
- by git last modification interval (earlier/later than 2016 or between 2016.03.01-2016.04.01 or modified within last 30 days).

**Example use case 1:**
This could make possible to filter the newly added files and cherry pick them in one step.

**Example use case 2:**
This could make possible to filter the files which only had just permission change (for example from old mode 100644 to new mode 100755) and cherry pick them in one step.

**Example use case 3:**
I think having this feature would highly help the preparing phase of merges, especially those merges in big projects, which contain more thousand files (and a big merge can be a pain).
This way you could filter down the filelist to similar files, which can be cherry picked together.
Finally the differences would be narrowed down to a smaller set of files, where merging and conflict handling would be easier.

**Depends on feature:**
This feature would depend on "Cherry picking multiple commits at a time" #2396 issue. 

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
<2.49.03

**Comment by gerhardol** [comment]
Since 3.1 (?) it is possible to sort by extension, path and status, which gives much of what was requested
