### ISSUE TITLE
Commit message is not updated immidiatly when using a commit template.

### ISSUE THREAD

**Issue by elyahueaton** [gitextensions/gitextensions#3669]
Hi,

  An automated refresh needs to be done before showing the commit dialog window if a commit message template is define.

  Consider the following scenario -

  Using a commit message template that contains only the branch name and is changed every checkout using the "post-checkout" hook.

  Commit template is defined as follows -
git config --global commit.template $commitTemplateFile

  When trying to commit and opening the GitExtention commit dialog, The previous branch name is seen in the commit message and only clicking the "refresh" button on the upper left cornet, updates the commit message with the correct and current branch as written in the commit-template file ($commitTemplateFile)

  Can a refresh to the message can be done some how before opening the commit dialog window ? We use GitExtention on Windows, version 2.48.04

Thanks,
Elyahu
---

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
