### ISSUE TITLE
Issues with 4k @ 150% scaling

### ISSUE THREAD

**Issue by mscrivo** [gitextensions/gitextensions#3673]
I'm testing out the current master branch (screenshots were taken with commit f5ee5eb71be063f5c1e2e8497907631363dcce1e) and while the main window looks great in 4k, several of the other forms do not.  Many open with larger dimensions than the screen itself, and have several rendering issues.  See screenshots below.

**Comment by mscrivo** [comment]
<img width="1433" alt="screenshot 2017-04-25 08 57 49" src="https://cloud.githubusercontent.com/assets/275524/25386552/bff5e4a4-2995-11e7-8a41-ca8ba4ff18e1.png">
<img width="1326" alt="screenshot 2017-04-25 08 58 09" src="https://cloud.githubusercontent.com/assets/275524/25386554/bff84dca-2995-11e7-82ac-0bfe7c96e406.png">
<img width="1433" alt="screenshot 2017-04-25 08 57 45" src="https://cloud.githubusercontent.com/assets/275524/25386553/bff5d608-2995-11e7-99ff-146be4ce79b9.png">

**Comment by RussKie** [comment]
Some issues are addressed as part of #3711

**Comment by mscrivo** [comment]
awesome, thank you!

**Comment by RussKie** [comment]
You can also try a workaround as suggested in https://github.com/gitextensions/gitextensions/issues/4099#issuecomment-349899698

**Comment by drewnoakes** [comment]
We are tracking specific high DPI issues in #4775. As this issue is general in nature, I'm closing it.
