### ISSUE TITLE
 The console tab doesn't escape special symbols in the path to repository

### ISSUE THREAD

**Issue by sys27** [gitextensions/gitextensions#3675]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

The console tab doesn't escape special symbols in the path to repository (eg. '!').

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open any 'normal' repository.
2. Ctrl+O and open repository which contain '!' in the path (eg.: D:\\!aaa\\).
3. The repository is opened, but console still has the previous path.

Is not reproducible if you open the repository from recent list .

**What is the expected behavior?**

Console should point to the right folder.

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**

Git - 2.11.0.windows.3
GitExtensions - 2.49.03
Windows 10

**Comment by ghanique** [comment]
There are many standards and patterns of how to do things. One of those is
that you do not use special characters in path or file names. Shouldn't one
just stick to the standards?
