### ISSUE TITLE
AOOR exception with branch name contains ']' symbol

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#3682]
Renaming a branch I accidentally typed ']' in the branch name.
Now GE crashes with AOOR exception:
![image](https://cloud.githubusercontent.com/assets/4403806/25516214/82f696c2-2c2c-11e7-8148-4ae74a0efbca.png)

![image](https://cloud.githubusercontent.com/assets/4403806/25516072/ac489c92-2c2b-11e7-9fb0-6cf7bd0a724e.png)
![image](https://cloud.githubusercontent.com/assets/4403806/25516137/1069cb6a-2c2c-11e7-9b17-3765e2c855c1.png)

Git bash works without a hiccup

```
$ git status
On branch APP]_refactor_context_app_management
Your branch and 'fork/my_fork' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
nothing to commit, working tree clean
```

**Comment by jbialobr** [comment]
Duplicates #3532.
