### ISSUE TITLE
Crash on copying commit data to clipboard

### ISSUE THREAD

**Issue by jacricelli** [gitextensions/gitextensions#3684]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
![gitextensions](https://cloud.githubusercontent.com/assets/574017/25557972/6e4df8ba-2cf3-11e7-9e6d-de30fee07a9c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Browse a repository
- Right click on selected row and copy commit message to clipboard

**What is the expected behavior?**
No crash.

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
Not sure.

**Comment by RussKie** [comment]
@jacricelli: I can't replicate this in neither 2.49.03 nor in canary version.
Could you please provide full stack trace. 

Does it happen for all commits or just selected? Could it be something to do with the commit message itself?

More info and screenshots would help.

**Comment by jacricelli** [comment]
It's been a while and I completely forgot about this. I can't reproduce it right now, but I did send the bug report when this happend.

**Comment by RussKie** [comment]
perhaps this can be closed then, and if you see it happen again either re-open it or raise another one with more information.

@jbialobr fyi
