### ISSUE TITLE
Multiple push repositories progress status shows wrong

### ISSUE THREAD

**Issue by golddragon007** [gitextensions/gitextensions#3685]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
If there's set more than one push repositories and you push, the progress bar will just show the first push status. (after the first, it will be full all the time)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a local repository and set multiple remote repositories with:
git remote set-url --add --push origin repo1
git remote set-url --add --push origin repo2
**What is the expected behavior?**
Show each remote repository upload status somehow.
Sol 1:
If there's 2 repos, devide the loading bar with 2, the first half will be for the first repo, the secound half will be for the secound.
Sol 2:
Put a label field above/under the loading bar with the current repository name and/or the current repo number/total repo count and the loading bar starts again from the begining for every upload.
**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
Probably all.

**Comment by vbjay** [comment]
Push only pushes to the chosen remote.

**Comment by golddragon007** [comment]
Yes and no.
Yes, because if you say push origin, it will push only to origin.
No, because I set multiple repository under the same name "origin" so it will push BOTH places, as the console shows this fact too.

**Comment by Latency** [comment]
Any change you can add something to the UI for something like featured [here](https://stackoverflow.com/questions/4255865/git-push-to-multiple-repositories-simultaneously)?

**Comment by vbjay** [comment]
Did you look at the push dialog?  It's already there.

**Comment by gerhardol** [comment]
GE has limited support for multiple push destinations. I believe you may see all destinations in a tooltip in the sidepanel, the rest is just presenting the first destination and pushing to the remote name. So multiple push destinations for one remote likelly need a lot more support.

**Comment by GintasS** [comment]
Abandoning this because of age and because of @gerhardol comment.
