### ISSUE TITLE
Seeing a lot of files modified by others being staged after resolving the merge conflicts manually

### ISSUE THREAD

**Issue by Gouri-Sankar** [gitextensions/gitextensions#3692]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
It's pretty tough to explain this process. But, once we resolve the merge conflicts manually there are lot of files being staged along with the file that had merge conflicts and people are committing and pushing all those files to remote repo. We don't understand this behavior on why is it staging so many files that the developer did not even touch.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I think this happens for a repo where a team of developers makes changes to lot of files constantly. Let's say File_A has been modified locally and committed. Then I pull the changes from remote and run into merge conflicts on that file. I resolve the merge conflicts (using KDiff3) and then it will ask me to commit again. At this time, when the commit dialog box pull up, I see a ton of files already being staged along with the file that had merge conflicts. Some developers un-stage the files that are not modified by them and commit only the ones they modified. But, some devs just hit commit and push button as they see their file being staged and don't bother about other files. Why does it stage all those un-related files which are not even modified by that person in first place after resolving a merge conflict? 

**What is the expected behavior?**
Stage and show only the file that had merge conflicts or that was changed by that dev.

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
GIT -  2.10.1.windows.1
Windows 7 32 bit
GIT Extensions - 2.49.03
No, it was same prob in previous version as well

**Comment by pmiossec** [comment]
I don't think that it's a GitExtensions problem. But to be sure, you need to investigate a little more. 

>Some developers un-stage the files that are not modified by them and commit only the ones they modified.

They are modified. With git, you could be 100% sure that if a file is not modified, it won't be committed. 

It looks to me more of end of line problem that should be solved using a '.gitattributes' strategy.

**Comment by Gouri-Sankar** [comment]
Thanks for your reply. Other files are certainly modified, but not by **me**. So, why will they show up in my commit window if someone else modified them. I am providing a screenshot with file names here because it happened today, in fact it seems to be happening every time we resolve merge conflicts manually. In the screen shot, I have modified only the first two files (AcordxlateInHelper.cs, AutoQuotetranMgr.cs) and I had to resolve some merge conflicts on both of them and when I go to commit them, all these other files showed up. First question, why these files are being staged if I did not modify them. Even though, I un-staged all of them, they still remain in the commit history as shown in the picture. 
Appreciate your help!
![manual merge commit history](https://cloud.githubusercontent.com/assets/26680870/25764516/05180ecc-319d-11e7-8566-2f0b5ba8db8c.JPG)

**Comment by Gouri-Sankar** [comment]
This is another merge conflict that I had to resolve similar to the above one. This is the actual commit window after resolving merge conflict on just one file (settings.xml), it showed a lot of other files which were modified by devs in the team but not by me.
![commit dialog after resolving merge conflict](https://cloud.githubusercontent.com/assets/26680870/25765191/92bf732a-31a0-11e7-8b48-9329ef73c6ec.jpg)

**Comment by vbjay** [comment]
I don't think you understand what a merge is. It merges two commits into 1.
Look at the other commits on the other side.

**Comment by pmiossec** [comment]
Oh, I see, that's completely normal and there's nothing wrong.

That's just that you don't understand how GitExtensions show you the content of the commit.

You must understand that from the git point of view, a commit contains all the files in a certain state (and not a diff). 

From this state of fact, what GitExtensions show you is what we expect the better way to understand what the commit introduce as changes.

The way to do is in fact showing the diff with the previous commit (and we ask to git this diff). 

But in your special case, you are seeing the changes introduced by a merge commit that have 2 "previous commits" (also called parents). 

So gitextensions is here very helpful because it show you the diff with its 2 parents (see the text "Diff with parent xxxxx". That way you could see easily the changes introduced by each of the branches merged (here "RC" and "ML")

**Comment by pmiossec** [comment]
Could be closed, FMHO...

**Comment by RussKie** [comment]
Like the other guys explained, it doesn't seem like a problem with git or git extensions, but more so with the way you use these tools. Git may seem quite confusing at the start and I've seen a lot of developers doing strange things (myself included).

There are so many way to skin a cat, and you need to find a pattern/routine which you are understand and comfortable with.

For example, here's my routine:
- do my work on a branch, 
- commit it (I commit often),
- fetch all
- rebase on top of the remote master (or whatever other branch needed)
- resolve any conflicts
Rinse and repeat until I'm all done then
- squash
- push
