### ISSUE TITLE
Stage selected line(s) problem with extended ASCII characters

### ISSUE THREAD

**Issue by escherstair** [gitextensions/gitextensions#3700]
I found a (possible) bug with "Stage selected line(s)" when I try to stage lines following a line which contains one or more extended ASCII characters (as an example: à, ò, è, é, ...)

If I select the lines to stage in "commit" window, and I press "S" key or select "Stage selected line(s)" I get an error
`error: patch failed: <filename>:<line_number>`
`error: <filename>: patch does not apply`
`...`
If the lines to stage contain these characters, I can stage them. The problem seems to be if the line immediately before them contains à, è, ò, ...

Everything works fine if I stage the whole file, pressing the "Stage" button.

The same issue happens with previous versions of GitExtensions and git.

GitExtensions 2.49.03
Git 2.12.2

**Comment by jbialobr** [comment]
Can you create, zip and upload a sample repository with such a file to be ready to stage it? 
What value is set for core.autocrlf in your global and local git config files?

**Comment by ghanique** [comment]
I experienced this behavior more often, but haven't been able to reproduce it consistently. 
I created a file with lines with extended ASCII characters, lines with unicode characters (€) and lines without any special characters. I could stage every line individually. Perhaps it has to do with a combination of extended characters and the file encoding:

* UTF-8: ok
* UTF-8 BOM: ok
* Western (Windows 1252): Weird stuff happens (but no error)!
* CP 852: Same weirdness as 1252.


[StageLineWithExtendedCharacters.zip](https://github.com/gitextensions/gitextensions/files/1000353/StageLineWithExtendedCharacters.zip)

**Comment by escherstair** [comment]
I attach the sample repository.
You can reproduce the error trying to stage only the line modified (not the whole file).
I work on Win 7 and core.autocrlf is set to false
[stage.zip](https://github.com/gitextensions/gitextensions/files/1000727/stage.zip)

**Comment by jbialobr** [comment]
What encoding do you have set up in the diff view window?
It does not work when there is UTF8 selected, because the file you stage is not UTF8 encoded and the non ascii characters got replaced by the replacement char. 
If a proper encoding is set, then there is no problem with staging the line.

**Comment by escherstair** [comment]
Ops...
If I set the encoding to 'default' everything works fine

**Comment by jbialobr** [comment]
You can set the files encoding per repository:
http://gitextdoco.readthedocs.io/en/latest/settings.html#git-config-files-content-encoding
