### ISSUE TITLE
Error when launching Visual Studio: The Add-in 'Git Extensions' failed to load or caused an exception. Error number: 8013101b

### ISSUE THREAD

**Issue by randyes** [gitextensions/gitextensions#3705]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Error when launching Visual Studio: The Add-in 'Git Extensions' failed to load or caused an exception. Error number: 8013101b

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Install Get Extensions. Launch Visual Studio

**What is the expected behavior?**
No error. The extension should load and function normally.

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
Git version 2.10.1 as installed by GitExtensions-2.49.03-SetupComplete.msi on Windows Server 2008 Build 6002 Service Pack 2
I've never installed the tool before, so I don't know.

ADDITIONAL BACKGROUND
According to http://gitextensions.github.io/ this extension should work with Visual Studio 2008. The information provided there appears to be incorrect. I would suggest contacting GitHub and letting them know how annoyed your clients are that they're being lied to about your product.

**Comment by vbjay** [comment]
That page is managed by the gitextensions organization.
https://github.com/gitextensions/gitextensions.github.io

**Comment by jbialobr** [comment]
Nobody wanted to lie to you. The inforamtion simply got stale. Fixed.
