### ISSUE TITLE
conemu 161009a fast configuration - pull/merge log window blank

### ISSUE THREAD

**Issue by andwan0** [gitextensions/gitextensions#3706]
report a bug

I updated to latest version of GIT Extensions.
Now everytime when I do a pull/merge, the process/status window dialog is blank.
I was getting errors with conemu 161009a fast configuration previously.
Unwanted value of 'LoadConIme' registry parameter!
Something about HKEY_CURRENT_USER/Console has invalid entry LoadConIme 0x00000000
but my registry shows it has entry 0x00000001

Why was this changed and how do I get to see my pull/merge log status window text again?

**Comment by pmiossec** [comment]
There is a setting to disable it. If I remember we'll it's in the 'advanced' panel.

**Comment by webmaster33** [comment]
May this related to the
Problem with interactive rebase & fixup. It is not working in Git Extensions 2.49 #3537
issue?

**Comment by jbialobr** [comment]
You can either set the LoadConIme value to `0` (https://conemu.github.io/en/FAQ-8.html#q-8-2)
or disable ConEmu in Git Extensions 
![commands](https://cloud.githubusercontent.com/assets/1003909/26192967/e7d64f42-3bb3-11e7-9773-7d30c0644f86.png)

**Comment by RussKie** [comment]
Is it still an issue with the current version?
Could you also please try this build
https://ci.appveyor.com/api/buildjobs/tb8kjpyr04sf8l4o/artifacts/GitExtensions-Portable-3.00.00.1599.zip

**Comment by RussKie** [comment]
Closing due to lack of follow up
