### ISSUE TITLE
Visual Git does not install in VS2010 if default directory is Visual Studio 10 and not Visual Studio 2010 in My Documents

### ISSUE THREAD

**Issue by eoinomeara** [gitextensions/gitextensions#371]
When Visual Studio 2010 RTM is installed on a machine that had a pre-release version of 2010 sometimes two folders exist in My Documents:
Visual Studio 10 --> The old and new default folder where almost everything went and now goes
Visual Studio 2010 --> An almost dummy folder created by RTM which would have been the new default folder if the old default folder did not exist

Visual Git files are always installed in the 2010 folder even though they should always be installed in the default folder (sometimes 10, often 2010)

Workaround: Copy Addins folder from 2010 to 10 and repair the GitExtensions install.
This means that when GitExtensions tells VS to register the addin it looks in 10 and finds the copied files. Without the wokaround VS will not find any files to register.

Sound like an easy fix to the installer to help the small number of people with the problem.

**Comment by RussKie** [comment]
Closing due to age.
If someone still using VS 2010 wishes to pursue this - PRs are welcome.
