### ISSUE TITLE
creating a branch with brackets in the name will crash gitextensions

### ISSUE THREAD

**Issue by miterosan** [gitextensions/gitextensions#3716]
--- GitExtensions2.49.03, Git 2.13.0.windows.1, Microsoft Windows NT 10.0.14393.0

**Comment by miterosan** [comment]
it seems like it is  a parsing error of the config file in the .git folder 

    [branch "reporting_bad_behavour"]
        remote = origin
        merge = refs/heads/[en]reporting_bad_behavour

^will crash

**Comment by RussKie** [comment]
It seems it is a dup of #3682 and #3532
