### ISSUE TITLE
Feature Request: Higlight my commits

### ISSUE THREAD

**Issue by megafanat** [gitextensions/gitextensions#3718]
There are a lots of commiters in our project. My commits are only 1% of all commits. Periodically I need to merge my branches to main branch. And it is hard to find my commits in huge list. If I apply filter then I do not see main branch. Also filter application is not convenient - I should change checkboxes in filter menu by mouse and then move hangs to keyboard and type my name.

I suggest to highlight commits of current user in list to find them easily. For example such commits can be displayed in bold font or their background can be yellow.
Similar feature implemented in Firefox: if your press Ctrl-F, type some word and click button "Highlight All" all these words on page will be highlighted.

**Comment by pmiossec** [comment]
>I suggest to highlight commits of current user in list to find them easily. For example such commits can be displayed in bold font or their background can be yellow.

In the current version, all the commits done by the author of the selected commit are highlighted with a yellow background. So selecting one of your commits is doing it. 

Are you asking for more?

**Comment by RussKie** [comment]
You can locate your commits by just typing your name in the revision graph.
Once you located any of your commits the rest will be highlighted, if you have "highlight by author" option enabled
