### ISSUE TITLE
(almost) Permanent lock of repository

### ISSUE THREAD

**Issue by TouDick** [gitextensions/gitextensions#3720]
After upgrading to 2.49.03 my repository is almost all the time locked by GitEx and no operations can be performed from command line. After exiting GitEx everything is back to normal. It does not depend what (if at all) operation is currently done in GitEx - Browse/commit/console view/diff.
--- GitExtensions2.49.03, Git 2.8.1.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by RussKie** [comment]
Can you please upgrade to the latest git and GE and see if you still experience the problem?
