### ISSUE TITLE
Add an option to the installer to install VS2017 plugin.

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#3722]

**Comment by jbialobr** [comment]
As for now there are problems in WIX and VSIXInstaller that have to be resolved.

https://github.com/wixtoolset/issues/issues/5566
https://github.com/wixtoolset/issues/issues/5597
https://developercommunity.visualstudio.com/content/problem/32018/vsixinstallerexe-cant-install-extensions-when-visu.html

**Comment by ofirc** [comment]
@jbialobr Have you considered implementing a work-around such as a "Custom Action" to deploy the VSIX manually? or perhaps the WiX/MSFT has an ETA for when it will be officially supported via WiX?

**Comment by jbialobr** [comment]
> Have you considered implementing a work-around such as a "Custom Action" to deploy the VSIX manually?

Yes, I have, but did not decide to.

**Comment by vbjay** [comment]
Frankly. I don't think the extension should be in the installer as a
feature at all. It should be in the marketplace. Have some ci to update
visix on marketplace. Have a feature in the program that takes them to
marketplace page for extension.

Add some code in extension that detects git extensions is not installed and
point to latest release page.

**Comment by phillijw** [comment]
Market place link: https://marketplace.visualstudio.com/items?itemName=HenkWesthuis.GitExtensions

I agree, market place makes the most sense to me. I'm just not sure how technically feasible it is to achieve.

**Comment by vbjay** [comment]
It wouldn't be that hard

- [ ] In extension detect if application is installed and get path to exe.  If not installed, provide dialog providing them a way to get the application.
- [ ] In extension detect version of application and prevent new features from working till they upgrade application to a version that supports that feature.  
- [ ] In application add option to install extension which would take them to marketplace or download visix from marketplace.

No matter what they installed, the other piece could be retrieved.

**Comment by RussKie** [comment]
> https://developercommunity.visualstudio.com/content/problem/32018/vsixinstallerexe-cant-install-extensions-when-visu.html

is allegedly fixed few days ago...

**Comment by BOBJohnson** [comment]
![nobranch](https://user-images.githubusercontent.com/5168739/30819173-868604da-a1e3-11e7-876d-3bc3194a3e9a.png)

The no branch name displaying is back in this latest version. I've tried uninstalling/reinstalling. I've tried resetting the toolbar. I've tried deleting the commit button and adding a new one. I've tried turning the setting off and then on again.

Not sure if this needs to go into its own issue. It's only happening with the VSIX and VS 2017. VS 2015 and the normal installer has no problem with displaying the branch name.

**Comment by vbjay** [comment]
Create a separate issue.  This issue is about installing 2017 visix.

**Comment by forbjok** [comment]
IMHO it would be better to just make the official VSIX extension publicly available in the Visual Studio Marketplace and leave it out of the setup, at least for the modern VSIX-supporting Visual Studio versions.

That way it'd be quicker and easier to just update the extension any time a new Visual Studio version comes out, instead of having to wait years for a new GitExtensions version with built-in support to come out or use a manually-downloaded unofficial extension. (as is currently the case)

**Comment by jbialobr** [comment]
Please create a separate issue for adding VSIX to marketplace. We can discuss there if we should discontinue packaging VSIX into installer. If yes then this issue should be closed as obsolete.

**Comment by RussKie** [comment]
You are now able to get a VSIX for VS 2017 from the VS Market Place https://marketplace.visualstudio.com/items?itemName=HenkWesthuis.GitExtensions
Thanks to @spdr870 for publishing
