### ISSUE TITLE
Multiple GUI regressions on mono

### ISSUE THREAD

**Issue by l-inc** [gitextensions/gitextensions#3725]
This bugreport is related to #3625 , but meanwhile things became worse (I was compiling from master on 19.11.16 before). I'm currently running GitExtensions on mono 5.0.1.1 in Cinnamon, Fedora 25.

The dashboard now looks like this:
![dashboard regr](https://cloud.githubusercontent.com/assets/20503346/26522889/ca134f24-430a-11e7-9302-adf84288c5d8.png)
The "common actions" is completely away, the "recent repositories" and "contribute" are always empty. This can be improved by merging #3693, but it has a multitude of its own problems, which render it hardly usable on mono.

The "merge branches" dialog looks like this:
![merge_branches regr](https://cloud.githubusercontent.com/assets/20503346/26522907/22165324-430b-11e7-8796-3577de98c040.png)
The "Merge" button is either away or goes away as soon as the window is attempted to be resized, the "merge branch" dropdown is completely away (previously the only problem was that the dropdown button and the "Select multiple branches" buttons overlapped).

The "checkout branch" looked like this before:
![checkout good](https://cloud.githubusercontent.com/assets/20503346/26522942/d978a0ee-430b-11e7-9cb5-2e00d146e549.png)
Now it may look like this:
![checkout regr3](https://cloud.githubusercontent.com/assets/20503346/26522980/5c381ef6-430c-11e7-9589-640d574a0fbe.png)
Or like this:
![checkout regr1](https://cloud.githubusercontent.com/assets/20503346/26522951/ef9f520a-430b-11e7-9ae8-966bc2d375a9.png)
Or even like this:
![checkout regr2](https://cloud.githubusercontent.com/assets/20503346/26522965/230cdebe-430c-11e7-9430-6f8ecee63113.png)

These are just in addition to numerous other GUI problems in various dialogs including branch creation, settings, remote repositories etc., which already persisted before and were partially described in #3625.

**Comment by RussKie** [comment]
@l-inc I'm still working on getting my version of the dashboard to work on mono, I've made a significant progress but there are still things to do.
I'm guessing most of these issues are caused by mono's inability to properly dock and dynamically resize controls.

I will put aside some time time and try to get your issues fixed.

**Comment by jbialobr** [comment]
#3754 Fixes it only partially

**Comment by RussKie** [comment]
I've started looking at fixing "merge branches" form... it is a beast 😒

**Comment by l-inc** [comment]
@RussKie
Did you have any more progress on the "merge branches"?

**Comment by RussKie** [comment]
I had, but nothing I can share - the layout is just too complex for mono... 
it is on my todo list

**Comment by glebmtb** [comment]
+1

**Comment by Timk90** [comment]
+1

**Comment by RussKie** [comment]
Gents, if you can - pull my branch and test the layout fix

**Comment by l-inc** [comment]
@RussKie 
I've just tested it and noticed only two little problems:

- The text box with the merge message goes a few characters beyond the form, so the last few characters at each line are not visible when typing a long single line message.
![merge_msg](https://user-images.githubusercontent.com/20503346/31103123-bb77b81c-a7d5-11e7-8564-322bd7cfb674.png)

- Any attempt to resize the form leads to the form quickly escaping into the left upper corner of the screen.

The rest seems normal, so the dialog is at least usable. Thank you.

**Comment by RussKie** [comment]
The textbox on your screenshot is clipped, that's why you're not seeing
some characters.
The dialog auto-sizes to accommodate all elements.
Do you run a different size font in GE?

**Comment by RussKie** [comment]
that's how it looks on my ubuntu 17.04 / mono 5.2.0

![image](https://user-images.githubusercontent.com/4403806/31126827-a545cb10-a898-11e7-98e1-98e9919552e9.png)

here's my font settings (which are defaults):

![image](https://user-images.githubusercontent.com/4403806/31126856-c89b67c8-a898-11e7-9dd8-692fbde11edf.png)

**Comment by l-inc** [comment]
You're right. I do have "DejaVu Sans, 11" set as "Application font". The merge dialog looks as yours when setting the 8.

**Comment by RussKie** [comment]
I take it back about the defaults (it was very late when I've written
that). It is possible that I may have changed it when worked on the
dashboard.
I don't know what the defaults are, and where the config is stored on Linux
to check it...
