### ISSUE TITLE
mono: freezing in "Resolve merge conflicts" after closing kdiff3

### ISSUE THREAD

**Issue by l-inc** [gitextensions/gitextensions#3726]
This bug was there for 1.5 years at least. My current setup includes current GitExtensions' master, mono 5.0.1.1, Cinnamon, Fedora 25, where it is also reproducible.
![kdiff3 freeze](https://cloud.githubusercontent.com/assets/20503346/26523100/feb13246-430f-11e7-953a-fcdf75a5c3e4.png)
After clicking "Open in kdiff3", (not necessarily) resolving the conflicts, and then closing kdiff3 GitExtensions freezes. If GitExtensions is killed, restarted and the conflict resolving procedure is repeated, no freeze is experienced anymore (possibly until system restart).

**Comment by Pekafu** [comment]
I'm not sure if my freeze is connected to this issue, but in my case the whole thing (GitExtensions, kdiff and webbrowser) all freeze when I click "Open in kdiff3" after second time "resolve merge conflicts"-windows is opened in on the one run of GitExtensions. If I reset GitExtensions after each resolve merge conflicts intance the freeze wont happen, but I tend to forget to do the reset every time I know there will be conflicts.

**Comment by Apivan** [comment]
I am using ubuntu 18.04. I can reproduce the problem.
It's because kdiff3 can't be run with sudo.

Just run ./gitext.sh without sudo solve the problem. This link described it in detail. [gksu-replacement-ubuntu](https://itsfoss.com/gksu-replacement-ubuntu/)
```
sudo ./gitext.sh
```

![screenshot_20190130_144835](https://user-images.githubusercontent.com/8325019/51966515-4b1b6f80-249f-11e9-80ca-e08c9cf23f44.png)

```
./gitext.sh
```

![screenshot_20190130_144946](https://user-images.githubusercontent.com/8325019/51966528-566e9b00-249f-11e9-8b5c-bc1bfe071198.png)

**Comment by RussKie** [comment]
Thank you for sharing

**Comment by l-inc** [comment]
Sorry, guys, the problem @Apivan describes has nothing to do with what I reported. I reported the freeze of GitExtensions with kdiff3 being perfectly functional. And after the restart of GitExtensions no freezes were experienced until system restart. If I were to run GitExtensions with sudo (which, I, of course, never did), the issue wouldn't have disappeared after restarting GitExtensions.

Meanwhile I'm on Fedora 29 with mono 5.18.0.240 and kdiff3 1.7.90. The problem disappeared some months ago. However I can't say if it still persists on the current "release/2.51". I'm running a very customized version of GitExtensions, which includes pull-requests #3693, #4499 among others as well as many cherry-picked commits from the master. It's a pity that none of these are in the mainline supporting mono.

**Comment by l-inc** [comment]
P.S. I've put my version [here](https://github.com/l-inc/gitextensions/releases) just in case someone finds it useful.

**Comment by RussKie** [comment]
> I'm running a very customized version of GitExtensions, which includes pull-requests #3693, #4499 among others as well as many cherry-picked commits from the master.

If this something we could re-apply to 2.5x branch for everyone's benefit?
I don't believe anyone on the core team is using Linux as their daily driver, and our knowledge is this area is pretty weak.

**Comment by l-inc** [comment]
As you can infer from the link I posted above, the set of commits is based on a master state that is close to the head of `release/2.50`. Trying to apply the changes as is onto the current 2.5x would possibly be harder than reviving mono support on 3.x, which I'd assume wouldn't be too hard. I'd wish somebody would drive that support. I've been customizing GitExtensions for mono by applying small fixes and merging outstanding pull-requests locally since 2016, but unfortunately I don't have capacity to create and support pull-requests, and .net is not even close to my area of expertise.

**Comment by vbjay** [comment]
@russkie Might be worth putting a link in the readme about his work on being unsupported but a kudo.

**Comment by gerhardol** [comment]
> than reviving mono support on 3.x, which I'd assume wouldn't be too hard

Unfortunately, it is. WinForms in Mono is very limited compared to the native Win version, this was the major part holding back GE development. There were very little feedback or involvement from mono users, it was not possible to maintain mono.
Another is that GE now uses that latest C# versions, much are not supported by the mono compiler.

If WinForms is ported, .NET Core 3 is a better way forward.

**Comment by l-inc** [comment]
> If WinForms is ported, .NET Core 3 is a better way forward.

Little googling tells me that there are no plans to support WinForms in .NET Core 3 for Linux and probably there will never be any. So it rather seems not a way at all. Linux users (me, unfortunately, among them) seem to be stuck with mono for good.

**Comment by RussKie** [comment]
Yes, v3 won't run on Linux - we use the latest C# feature set and a number of Windows-only packages. I think we may have also removed some Mono-specific code paths.

v2.5x is still available and we intend to keep it alive for our Mono users. However for the reasons above, we don't work or add new features to that branch. 

If you have anything to share with other Mono users by sending PRs in to the branch, it would be great.

**Comment by itsho** [comment]
I believe this can be closed because of this:
https://github.com/gitextensions/gitextensions/issues/6971#issuecomment-516770269

**Comment by RussKie** [comment]
Thank you @itsho. I think we can close this but due to the age of the issue and lack of activity.

We still have 2.5x branch which is working on Mono, and can be patched, if desired by the Mono community.
Besides there are reports that Windows Forms Core \*_maybe_* working on Mono, see: https://github.com/dotnet/winforms/issues/3610#issue-662232712.
