### ISSUE TITLE
'Show remote branches' check state does not toggle after click

### ISSUE THREAD

**Issue by chenop** [gitextensions/gitextensions#3730]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
checking the 'Show remote branches' does not toggle the check

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
View --> 'Show remote branches'

**What is the expected behavior?**
In case the 'Show remote branches' is false --> After clicking 'Show remote branches' I expect the check to be displayed - Note that after refresh it appears.

Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
Windows 10.
Git Extensions 2.49.03

**Comment by RussKie** [comment]
I get the same - the remote branches are being toggled on and off, however the menu stays checked or unchecked until refreshed

![image](https://user-images.githubusercontent.com/4403806/27260448-037813a0-5470-11e7-80b7-3da948c83c01.png)

![image](https://user-images.githubusercontent.com/4403806/27260455-194003be-5470-11e7-9346-56184979e172.png)
