### ISSUE TITLE
git-credential-winstore.exe missing

### ISSUE THREAD

**Issue by wsw70** [gitextensions/gitextensions#3732]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

When pushing I get an error message about missing `git-credential-winstore.exe`:

```
"C:\Program Files\Git\bin\git.exe" push -u --recurse-submodules=check --progress "origin" refs/heads/master:refs/heads/master
Counting objects: 4, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 423 bytes | 0 bytes/s, done.
Total 4 (delta 3), reused 0 (delta 0)
"C:\Program Files (x86)\GitExtensions\GitCredentialWinStore\git-credential-winstore.exe" erase: C:\Program Files (x86)\GitExtensions\GitCredentialWinStore\git-credential-winstore.exe: No such file or directory
featal: The remote end hung up unexpectedly
fatal: The remote end hung up unexpectedly
rror: RPC failed; HTTP 401 curl 22 The requested URL returned error: 401
Everything up-to-date
```

The Windows Credential pop-up does appears, enabling me to input my credentials, then I get the error above.

**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**

This bug has been reported previously (for instance https://github.com/ferventcoder/chocolatey-packages/issues/31) but still happens with fresh installs.

- My Git Extensions install is 2.49.03, "Complete" install package with all features enabled. 
- I do not have any entries in my git config file (`.git/config`) which would point to the path referenced in the error log above.

**Comment by mortb** [comment]
I use gitextensions 2.49.03
I have a reference to git-credential-winstore.exe in the .gitconfig file which is placed in the "my documents" (%homedrive%homepath%) folder. I have no problems  pushing, but we do not use http, we use ssh or git protocol

**Comment by RussKie** [comment]
does this relate to #3511?

afaik, git-credential-winstore.exe is needed for http

**Comment by pmme** [comment]
You can execute `git config --global --get credential.helper` to check if you have a setting in your global config file. Mine returns `!"C:/Program Files (x86)/GitExtensions/GitCredentialWinStore/git-credential-winstore.exe"`. In my case this comes from having installed older versions of GitExtensions that included their own copy of git-credentials-winstore.exe. You say it still happens with fresh installs, so perhaps it is still a default setting written by even the latest GitExtensions installer.

git-credentials-winstore.exe has been discontinued. It is replaced by [Git Credential Manager for Windows](https://github.com/Microsoft/Git-Credential-Manager-for-Windows).
From what I've read on that page, Git Credential Manager for Windows differs from and is more secure or has more features than "wincred", which is included with the Git installer for Windows.

More information on credential helpers is here: https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage

If you want to remove the credential helper and just enter your username and password, you can execute `git config --global --unset credential.helper`.

You could install Git Credential Manager for Windows, then execute `git config --global credential.helper '!"c:/path to new credential helper exe"'`
Note the single quotes surrounding the path and exclamation at the start. I don't know all of the options for entering windows paths into Git but that works for me to replicate what GitExtensions set originally.

**Comment by increddibelly** [comment]
still here in 2.50.02. and I upgrade so few times that I forget the fix every time. C'mon guys...

**Comment by RussKie** [comment]
What do you expect us to do?

**Comment by increddibelly** [comment]
when you search for 'git credential winstore' it seems clear that gitextensions assumes defaults that aren't valid for many users. these issues date back to 2012 at least.
out of the top of my head, you could assume a safer default / verify the assumed value works BEFORE using it / add a check in the checklist?

**Comment by increddibelly** [comment]
actually, I've found it. again.
C:\users\.gitconfig contains the following snippet:
`helper = !\"C:\\Program Files (x86)\\GitExtensions\\GitCredentialWinStore\\git-credential-winstore.exe\"`
but instead, this should be 
`helper = \"C:\\Program Files (x86)\\GitExtensions\\GitCredentialWinStore\\git-credential-winstore.exe\"`

**Comment by vbjay** [comment]
! Means something. https://git-scm.com/docs/git-config. Search the page for
!

**Comment by RussKie** [comment]
I think in this context, leading bang means "treat it as a shell command (executable)".... though I may be wrong

**Comment by RussKie** [comment]
I've searched the codebase and I can't find anything installs git-credential-winstore.exe or configures it.
I can only speculate that it is done by git for windows installation.

In https://github.com/gitextensions/gitextensions/issues/3511 there are suggested workarounds to replace it with `wincred` or `manager`.

**Comment by pmme** [comment]
The problem is not what GitExtensions 2.49 and later are doing, instead it's that earlier versions of GitExtensions created a setting (at a time when it was appropriate) and that setting now remains. In #3511 I wrote the command to remove the setting or change it to an alternative.

I have a suggestion: #4179
