### ISSUE TITLE
File history opens wrong file

### ISSUE THREAD

**Issue by d4e666** [gitextensions/gitextensions#3735]
--- GitExtensions2.49.03, Git 2.11.0.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

1. Open a commit (double click)
2. select any random file (in my case file 'ProductCurves/Overview.html) and double click
3. The file history editor opens a different file, I guess the first file it finds instead of the clicked file
![bug report](https://cloud.githubusercontent.com/assets/7936919/26580089/e0290136-4536-11e7-83fe-cfcdfdd30ce0.png)

**Comment by jbialobr** [comment]
Please, see the comment: https://github.com/gitextensions/gitextensions/issues/3044#issuecomment-160180832 and answer if it is your case.
