### ISSUE TITLE
Remote branch name is incorrectly displayed for SVN repository in Pull dialog.

### ISSUE THREAD

**Issue by cristianst85** [gitextensions/gitextensions#3738]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
In Pull dialog the first letter of the Remote branch name (SVN repository) is cut off.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Open _GitExtensions_ and clone a SVN repository: from _Start_ menu > _Clone SVN repository..._

_For example:_
![image](https://cloud.githubusercontent.com/assets/12585988/26746666/af3c0896-47f9-11e7-98ad-8c7701c66b3e.png)

2) After the repository is cloned, open the _Pull Dialog_ and click into _Remote Branch_ drop-down list. The first letter of the remote branch name is cut off.

![image](https://cloud.githubusercontent.com/assets/12585988/26746716/f4f696da-47f9-11e7-9c84-b9a24fbf2568.png)

**What is the expected behavior?**
Remote branch name should be correctly displayed.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions 2.49.03
git version 2.10.1.windows.1
Windows 7 x64

**Additional testing**
I've build from latest commit ([852fa657](https://github.com/gitextensions/gitextensions/commit/852fa65719c1d714227a9e976539f7e3fd603ae8)) on the master branch, but now the _Remote Branch_ drop-down list in _Pull Dialog_ is empty.

If I open the _Checkout branch_ dialog the remote branch name is displayed correctly.
![image](https://cloud.githubusercontent.com/assets/12585988/26748452/8ca2f904-4806-11e7-8e5a-da3d6cf17d0a.png)

**Comment by gerhardol** [comment]
Closing, SVN support was removed from master/3.00 branch in #4592
