### ISSUE TITLE
Missing statically-bound call to a function in a kernel32.dll

### ISSUE THREAD

**Issue by Bleach665** [gitextensions/gitextensions#3742]
GitExtensions version 2.49.03. Windows XP SP3.
During installation and some operation received error "The procedure entry point <function name> could not be located in the dynamic link library KERNEL32.dll." All of function <function name> has minimum supported client Windows Vista...
As example when doing make stash - "The procedure entry point CancelSynchronousIo could not be located in the dynamic link library KERNEL32.dll." was received.

PS. Sorry. Look like it a Git 2.10.1 version problem.

**Comment by vbjay** [comment]
https://www.microsoft.com/en-us/windowsforbusiness/end-of-xp-support  Why
would the maintainers of any project support an ancient os version that is
not even supported by the manufacturer?
