### ISSUE TITLE
Tooltips are not translated

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#3745]
2 questions about the translation in GitExtensions...

1. Should we add (or replace ? ) the link to translate GitExtensions to open the transifex website instead of open the tranlation application now that the translation is done through the website?

2. I see that none of the tooltip texts are translated in the application nor proposed to the translation in the 'xlf' files. Is someone know if something has already been done to support tooltips?

**Comment by jbialobr** [comment]
1. Yes, we should direct uers to the Transifex website..
2. Can you list them? Perhaps it is a bug. I can see:

`<trans-unit id="DecreaseNumberOfLines.ToolTipText">`

![gitext](https://cloud.githubusercontent.com/assets/1003909/26815692/f21e92e6-4a8d-11e7-9e9a-b00a2c2c9684.png)

**Comment by pmiossec** [comment]
1. I will do a PR to fix that
2.  Indeed, that works for control that have a `ToolTipText` but the one that rely on a `System.Windows.Forms.ToolTip` control and call `SetToolTip()` seems to be not translated (like in the `FormPull`). Do you confirm?

**Comment by jbialobr** [comment]
>Do you confirm?

Yes, that is true.

**Comment by RussKie** [comment]
Can this be closed?

**Comment by pmiossec** [comment]
The first point has been solved by a PR.

The second is still not fixed.
So, I don't know. Perhaps opening a clearer issue.

Anyway, do what you want...

**Comment by RussKie** [comment]
I can see tooltips being translated.
As per @jbialobr's recommendation, if you see any tooltips not translated please raise a new issue.
