### ISSUE TITLE
About Pending changes window vs2010

### ISSUE THREAD

**Issue by mgo-scavetta** [gitextensions/gitextensions#3747]
**Do you want to request a *feature* or report a *bug*?**
Just a question actually..

**What is the current behavior?**
The pending changes window shows pending changes in master branch after switching from new branch where the changes were made.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Create new branch.
2) Switch to new branch
3) Make change, save file
4) View that change is pending in Pending Changes(new branch name) window
5) Switch back to master branch
6) The pending changes from the new branch are showing for the master branch

**What is the expected behavior?**
I would expect the master branch pending changes window to be empty as the changed were made on a different branch

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
Windows 7
IDE: VS2010 Version 10.0.40219.1 SP1Rel
Extensions version : 2.47.3

This might just be the correct behavior, I'm not sure.  But it is confusing.

The source files actually do show the correct code in the editor when switching branches.

- rock

**Comment by vbjay** [comment]
A branch is only a pointer to a commit chain. It has nothing to do with the
working directory.  Now if particular branch has changed those files, you
might see different diffs.

**Comment by vbjay** [comment]
http://www.vogella.com/tutorials/Git/article.html#using-branches

**Comment by mgo-scavetta** [comment]
Thanks Jay.
