### ISSUE TITLE
Pressing Ctrl+R crashes Gitextensions

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#3749]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Press Ctrl + R, application crashes with System.NullReferenceException (Object reference not set to an instance of an object.) Void compareToBaseToolStripMenuItem_Click(System.Object, System.EventArgs) @ GitUI.RevisionGrid

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Problem is, that <kbd>Ctrl+G</kbd> → <kbd>Ctrl+R</kbd> is common hotkey to search for some command in git history. If I get too fast and press the second before GitBash is opened, GitExtensions crash. It's quite annoying as it happens to me few times a day. 

**What is the expected behavior?**
If it's mapped to something, it should fail gracefully. With error dialog "can't do this thing, because you XY". But it should not crash. 

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions.exe [2.49.03] (latest stable)
Never worked. 

I think I've already seen the issue somewhere, but I searched issues and PRs and could not find it, so I'm adding a new one. It's related to #3699.

**Comment by vbjay** [comment]
Next time search issues before posting your own.

**Comment by RussKie** [comment]
This has been fixed in #3534

**Comment by tomasfejfar** [comment]
Yes! #3535 is the one I've seen. I probably couldn't find it because i searched the full exception name (incl. `System.`). Thanks. 

Is there a planned date for the next release?

**Comment by RussKie** [comment]
this can be closed now

@jbialobr fyi

**Comment by jbialobr** [comment]
>Is there a planned date for the next release?

Released today.
