### ISSUE TITLE
Hotkey for "Stage All" button

### ISSUE THREAD

**Issue by webmaster33** [gitextensions/gitextensions#3756]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
No hotkey

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
ALT+A should be hotkey for Stage All

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
Git Extensions v2.50RC1 or earlier
Windows 7 Pro

**Comment by vbjay** [comment]
Did you not see the hotkey settings.
http://git-extensions-documentation.readthedocs.io/en/latest/settings.html#hotkeys
