### ISSUE TITLE
DragDrop registration did not suceed.

### ISSUE THREAD

**Issue by miladamirzadeh** [gitextensions/gitextensions#3758]
**Do you want to request a *feature* or report a *bug*?** 
bug

**What is the current behavior?**
After pushing an unhandled exception appeares.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Completely random. First time happened to me.

**What is the expected behavior?**
Handling exception and not showing .NET unhandled exception window.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
2.49.03
First time ever 
![gitext](https://user-images.githubusercontent.com/7044707/27028997-d1a4b12e-4f7b-11e7-87bb-46cd3c959095.png)
![gitext2](https://user-images.githubusercontent.com/7044707/27028998-d1a6ccde-4f7b-11e7-888b-ed716ccd33bb.png)

**Comment by RussKie** [comment]
Please provide steps to reproduce and full stack trace

**Comment by miladamirzadeh** [comment]
I just pushed a repository. After that this happened. I had lots of windows opened,  maybe a wrong click caused this.

**Comment by RussKie** [comment]
Please report back/reopen if the issue is present in the current version
