### ISSUE TITLE
2.5.0RC1 System.ArgumentException on start

### ISSUE THREAD

**Issue by SailorMax** [gitextensions/gitextensions#3761]
When I trying to start fresh installed app I have System.ArgumentException:

1 is not a supported code page.
Parameter name: codepage

Target Site: System.Text.Encoding GetEncoding(Int32) @ System.Text.Encoding
NBug: 1.2.0.0
CLR: 4.0.30319.42000

Source: mscorlib
HResult: -2147024809
Stack Trace:
   at System.Text.Encoding.GetEncoding(Int32 codepage)
   at GitCommands.AppSettings.LoadEncodings()
   at GitCommands.AppSettings.LoadSettings()
   at GitExtensions.Program.Main()

--
Tested on Windows 10x64 1703

Installed only 2 Translations: English and Russian

**Comment by jbialobr** [comment]
Fixed version is available: https://github.com/gitextensions/gitextensions/releases/tag/v2.50RC2

**Comment by SailorMax** [comment]
Thanks!

Can you explain for me, what the difference between "-Setup" and "-Mono" files? "-Mono" = "Portable"?

**Comment by EbenZhang** [comment]
IMO, mono is for Linux/MacOS

**Comment by SailorMax** [comment]
> IMO, mono is for Linux/MacOS

I thought so too. But it has ".exe" files and I can run it on Windows :)
