### ISSUE TITLE
Win32Exception when clicking on Revision Link

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#3763]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
> System.ComponentModel.Win32Exception
Unknown error (0x80041002)
Boolean StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo) @ System.Diagnostics.Process
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at GitUI.CommitInfo.CommitInfo.HandleLink(String link, Object sender)
   at System.Windows.Forms.RichTextBox.OnLinkClicked(LinkClickedEventArgs e)
   at System.Windows.Forms.RichTextBox.EnLinkMsgHandler(Message& m)
   at System.Windows.Forms.RichTextBox.WmReflectNotify(Message& m)
   at System.Windows.Forms.RichTextBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
http://c2n.me/3LlMeBR.png 
http://c2n.me/3LlMl1B.png

Even if URI is "http://httpbin.org", an exception is raised anyway.

**What is the expected behavior?**
Guess, opening a web browser with the specified URL.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions.exe [2.50RC2]
git version 2.13.0.windows.1 (amd64)
Windows 7 x64 SP1

**Comment by jbialobr** [comment]
Works fine on my PC. 
It could be a permission problem: 
https://stackoverflow.com/questions/23554929/unknown-error-0x80041002-when-starting-process-on-asp-net-server

**Comment by pravic** [comment]
Apparently it is not related to ASP.NET service.

Also it happened once already: #3515. And there is #2579. But I don't use # inside link or its caption.

**Comment by pravic** [comment]
Well.
NBug have messed an original exception, it was "System.ComponentModel.Win32Exception (0x80004005): Unknown error (0x80041002)".
And this is because of GitEx is trying to open an `issue:%203763#https://github.com/gitextensions/gitextensions/issues/3763` URI — caption and link fields are glued together.

**Comment by jbialobr** [comment]
This time it was the colon :) after `Issue:`

**Comment by pravic** [comment]
Nice.
