### ISSUE TITLE
Get message 'userid' is not a valid short file name

### ISSUE THREAD

**Issue by fvittoria** [gitextensions/gitextensions#3764]
I downloaded GitExtensions-2.49.03-Setup.msi to my workstation.  When I run it I will get the message:

'fvittoria' is not a valid short file name 

And then the installation fails to continue. 

Note that 'fvittoria' is my userid logging into my workstation.

**Comment by fvittoria** [comment]
Wanted to add that I've also tried GitExtensions-2.49.03-SetupComplete.msi with the same results.

**Comment by RussKie** [comment]
Any stack traces or screenshots?

**Comment by jbialobr** [comment]
Can you provide a log from an installation process invoked like that:
`msiexec /i GitExtensions-2.49.03-Setup.msi /l*v MyLogFile.txt`

**Comment by fvittoria** [comment]
See attached log file.

Felice Vittoria |  Lead System Developer
Automated Voice & Data Solutions
Tel:  713.963.0900 Option 1   |   Main:  1.800.308.6423   |   AVDS Support<http://support.avds.com/avdstickets/>   |  AVDS Sales<mailto:solutions@avds.com>

**Comment by jbialobr** [comment]
It can be related to #292.

**Comment by fvittoria** [comment]
So are you noting for me to modify the registry so that I change the VS*INSTFOLDER lookups to point to a folder on computer instead of a network location?

Felice Vittoria |  Lead System Developer
Automated Voice & Data Solutions
Tel:  713.963.0900 Option 1   |   Main:  1.800.308.6423   |   AVDS Support<http://support.avds.com/avdstickets/>   |  AVDS Sales<mailto:solutions@avds.com>
