### ISSUE TITLE
Feature request: use GH API for avatar retrieval when GH private email address is used

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#3770]
**What is the current behavior?**

In Settings -> Appearance -> Author images, it is possible to enable retrieval of a user avatar based on the email address used in the commit via gravatar.com.

GitHub offers users the ability to keep their email address private and recommends using this option:
https://help.github.com/articles/keeping-your-email-address-private/
https://help.github.com/articles/setting-your-email-in-git/

This means that in my case, I would be using `jrfnl@users.noreply.github.com` as the email address in my commits.

However, as gravatar needs you to confirm your email address before allowing you to assign an avatar to it and as this GH private email address does not forward emails to your *real* email address, this in effect means that the "Author Images" feature is broken for all commits made by people using this GH feature.

**Suggested feature:**

GitHub offers an API to retrieve user data, including the user avatar. This request is based on the user name.

I'd like to suggest before making the API call to gravatar, to check if the email address used has `users.noreply.github.com` as the domain and in those cases, make an API call to the GH API instead to retrieve the user avatar.

https://developer.github.com/v3/users/#get-a-single-user

**Comment by thomaslevesque** [comment]
This would be very nice, and probably not very hard to implement.
