### ISSUE TITLE
opening git extensions  will  occupy 30%+ cpu

### ISSUE THREAD

**Issue by xiemms** [gitextensions/gitextensions#3774]
--- GitExtensions2.49, Git 2.10.1.windows.1, Microsoft Windows NT 6.3.9600.0

windows 10
Intel i5-4590 CPU @3.30GHz 
12G memory
![image](https://user-images.githubusercontent.com/16432738/27272853-fecef884-54fe-11e7-9f8a-afc0f05f5b33.png)

**Comment by jbialobr** [comment]
Can you use [processexplorer(]https://technet.microsoft.com/pl-pl/sysinternals/processexplorer) and investigate what command is being run for this process?

**Comment by xiemms** [comment]
![image](https://user-images.githubusercontent.com/16432738/27273541-15c6f5f2-5502-11e7-8f9f-0632acf10246.png)
seems that  the vs code results in the situation ?

**Comment by jbialobr** [comment]
Can you right click on the `git.exe` process and click on the Properties menu?
On the Image tab where is a Command line shown. It would be helpful to see the Environment tab as well.

![gitext](https://user-images.githubusercontent.com/1003909/27273869-2f293cd4-54d1-11e7-9983-76a0bb286d20.png)

**Comment by xiemms** [comment]
![image](https://user-images.githubusercontent.com/16432738/27274138-bef8c252-5504-11e7-83ea-ff8fa242df85.png)
![image](https://user-images.githubusercontent.com/16432738/27274152-cb4660d2-5504-11e7-83a4-d46d6fcb4f6d.png)
i find that  much cpu will be occupied when opened by   GitExt Browse if the project has many files ,even though i closed the vs code. while it's getting much better if the git project has less files

![image](https://user-images.githubusercontent.com/16432738/27274406-b8ac4c1a-5505-11e7-8537-8bc8b83c54aa.png)
Folder  27537
file 178634
node_modules  has been added to .gitignore

**Comment by jbialobr** [comment]
It is caused by the [Show number of changed files on commit button](https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#git-extensions-performance-changes-no) being turned on.

Can you tell how long it takes to run 
`git ls-files -o -i --exclude-standard` 
and
 `git status --porcelain -z --untracked-files`
 from the command line (close GitExtensions before running them)?
How many files do these commands return?

**Comment by xiemms** [comment]
![image](https://user-images.githubusercontent.com/16432738/27276693-87941208-550e-11e7-8229-877c9517f7a9.png)


![image](https://user-images.githubusercontent.com/16432738/27276670-7ad4eefc-550e-11e7-8fa9-1efc8e2183c0.png)
the first command doesn't work while waiting for 5 minutes and have tried it twice。
by the way， the cpu was occupied 30%+

**Comment by xiemms** [comment]
i try to disable "Tools > Settings > Git Extensions > Show repository status in browser dialog"   option , processes  will be ok

**Comment by jbialobr** [comment]
>the first command doesn't work while waiting for 5 minutes and have tried it twice

Perhaps there is a bug in git (looks like an infinite loop), consider reporting it to the git community.

**Comment by xiemms** [comment]
thanks

**Comment by jbialobr** [comment]
Try the [latest git release](https://git-scm.com/download/), there were some changes made to the `ls-files` command.
