### ISSUE TITLE
"Recover lost object" sometime doesn't show result

### ISSUE THREAD

**Issue by ltvan** [gitextensions/gitextensions#3777]
"Recover lost object" doesn't show result most of the time although there are dangling commits found in the log messages. Sometime, in some situation, the result show, but I cann't detect the pattern of the situation yet. 

However, for some repositories, this feature works well all the time. The easiest way to reproduce is creating new repos, add some commits, then amend the last one, try to "Recover lost object". 

I'm using v2.49.3 and Git v2.11 on Windows 10, tried update Git to v2.13 and still the same. The v2.48.x works well with the same repos and Git.

**Comment by vbjay** [comment]
Compare your options in 2.48 vs 2.49.

**Comment by ltvan** [comment]
I use the same config for both.

**Comment by jbialobr** [comment]
Can you test if this bug is in https://github.com/gitextensions/gitextensions/releases/tag/v2.50RC2?

>The easiest way to reproduce is creating new repos, add some commits, then amend the last one, try to "Recover lost object".

Do you have such a repository? Can you zip it and upload here?

**Comment by ltvan** [comment]
This is the repos. I tried to create it with 2.48 and open it with 2.49 and the bug is still there.
[sample-git.zip](https://github.com/gitextensions/gitextensions/files/1091216/sample-git.zip)

I tested with your release and the bug is still there.

**Comment by jbialobr** [comment]
Thank you.

**Comment by ltvan** [comment]
Worked on 2.5 now, thank much.
