### ISSUE TITLE
[Discussion] Recent repositories / categories overhaul

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#3780]
@jbialobr: bringing the discussions from https://github.com/gitextensions/gitextensions/pull/3769#issuecomment-309803415 here.

Right now the Git Extensions offers a very confusing, fragmented and disjointed UX around repositories management - the recent repository list is completely separate from categorised repositories.
Rendering of the recent repositories dropdown list on the main view can be configured via the "Recent Repositories" form. The same rendering isn't applied to the dashboard.
Categorised repositories can be configured via the Settings.

The new dashboard PR #3693 makes an attempt to bridge the gap by deprecating categories in the current sense as well as removing 'Start Page' settings page.
All repositories will be rendered from "recent repositories" list and the rendering for the dashboard and for the dropdown will be controlled via the "Recent Repositories" form. Ideally this should be moved to Settings.
Each repository will have a property "category" and a category will exist for as long as at least one repository has that category.

The dropdown rendering can be uplifted once #3693 is merged to include categories and the user-preferred order.
Also a category management will need be added once #3693 is merged - this should allow to delete, rename and reorder categories, move repositories between them etc (this hasn't been finalised).

My proposal goes further - **_can we consider dropping "most recent" / "less recent" and anchor attributes completely_**? 
Each repository can be pinned (or made favourite) which will ensure that repo stays at the top of the user list and won't disappear if it hasn't been used for long time.

Also @francoas [expressed dislike for term "category"](https://github.com/gitextensions/gitextensions/pull/3693#issuecomment-310126674). Can it be renamed to "group" perhaps?

Discuss?

**Comment by francoas** [comment]
About categories or whatever... can't they be called "folders" and managed as folders with subfolders etc exactly as SourceTree 1.x does ?

**Comment by francoas** [comment]
Here is a picture from SourceTree

As you can see repositories have a simbolic name followed by the full local path and the status 
and they are grouped in folders and in subfolders (as many level you like)
and you can organize them just dragging them into a folder as it happens with files...

![image](https://user-images.githubusercontent.com/3007941/27441711-a608b100-576e-11e7-9262-f9ee6d2c1b2d.png)
