### ISSUE TITLE
Color highlighted lines remain on some commit that I have not checked out

### ISSUE THREAD

**Issue by mpopdam** [gitextensions/gitextensions#3781]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Even though I have checked out the _develop_ branch, it does not get color highlighted. The colored branch lines seem to indicate that some other commit is checked out. It looks a bit as if I had highlighted that commit with Ctrl-Shift-B, but I did not do that. And even when I do use Ctrl-Shift-B to highlight the checked out _develop_ branch, it still resets the highlight back to the other commit after a refresh.

![image](https://user-images.githubusercontent.com/2325309/27469068-de9d7058-57ed-11e7-9c39-58eab9ec5daf.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not sure exactly what I did, but I think I just checked out the remote _develop_ branch, resetting my local branch with the same name. Before that I had another branch checked out, but definitely not that specific commit that is now color highlighted.

**What is the expected behavior?**
I would expect the current checked out branch to be color highlighted as it was before.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
I have Git 2.10.2 installed on my Windows 10 machine. In GitExtension version 2.49 this behavior never happened. I have installed 2.50 RC2 yesterday and noticed this issue today.

**Comment by jbialobr** [comment]
What does `git rev-parse HEAD` return? Can you point the returned hash on your image?

**Comment by mpopdam** [comment]
That returns the hash of the branch that I have checked out (_develop_).

**Comment by jbialobr** [comment]
Can you reproduce the bug after restarting GitExtensions?

**Comment by mpopdam** [comment]
Yes, the problem remains after a restart. If I check out any of the later branches that have been pushed today the coloring works fine. But if I checkout a revision from earlier today the coloring keeps indicating that one commit from the screenshot.

**Comment by jbialobr** [comment]
Can you switch back to 2.49 to see if the problem occurs?

**Comment by mpopdam** [comment]
I just checked. It occurs on 2.49.2 and 2.49.3 as well.
