### ISSUE TITLE
Maybe bundle KDiff3 0.9.98 32-bit?

### ISSUE THREAD

**Issue by segevfiner** [gitextensions/gitextensions#3784]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
KDiff3 0.9.97 32-bit is bundled

**What is the expected behavior?**
I would expect the latest version. Unless there is something broken in 0.9.98 that I don't know about.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
KDiff3 0.9.97 is bundled in 2.50. I remember a version where a newer KDiff3 version was bundled but that was reverted due to bundling a 64-bit install which wouldn't work on 32-bit Windows. But there is a 32-bit version of KDiff3 0.9.98 available: https://sourceforge.net/projects/kdiff3/files/kdiff3/0.9.98/KDiff3-32bit-Setup_0.9.98-3.exe/download. Bundling both 32 and 64 bit versions is also an option with the trade off of increased installer size and complexity of selecting the right version.

**Comment by pmiossec** [comment]
That is something that you could easily propose as a pull request...
There is only 3 files to update (`Setup/UI/RequiredSoftwareDlg.wxs`, `Setup/Product.wxs` and `Setup/DownloadExternals.cmd`).

Feel free to do it.

**Comment by KindDragon** [comment]
KDiff3 0.9.98-3 32-Bit failing to start on some computers
