### ISSUE TITLE
Amend Commit is not working in Version 2.5

### ISSUE THREAD

**Issue by miladamirzadeh** [gitextensions/gitextensions#3786]
**Do you want to request a *feature* or report a *bug*?** 
Bug
**What is the current behavior?**
When you want to Amend a commit, you check the *Amend Commit* check box. The commit dialog shows the last commit message in the commit message box, when you press *Commit* it  shows you a confirm that you are about to rewrite the history. When you press *Yes* it clears the commit message and says *please enter commit message*
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. In a repository add a file or make change
2. Right-Click in repository and select commit.
3. Stage files.
4. Click on Amend Commit check box
5. Previous commit message will appear, edit it or leave it as is.
6. Press Commit
7. It asks you if you are aware of what you are doing.
8. Press yes
9. It should tell you *please enter commit message*

**What is the expected behavior?**
A successful commit.
**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions 2.50.00 on Windows 10
It was working in previous versions.

**Comment by pmiossec** [comment]
I can't reproduce the bug and it works well each time.

I also use GitExtensions 2.50.00 on Windows 10.

I have successfully done:

- amend without a change (only reworing)
- amend with a change

Does it happen everytime?

**Comment by miladamirzadeh** [comment]
Sorry, I don't have access to my workstation. There are two things which I think are related to this issue. 
First, commit message templates in .gitconfig and message templates in git extensions itself.

I try to reproduce this issue from scratch on another machine.

**Comment by miladamirzadeh** [comment]
Sorry for being late. Add the line below to the .gitconfig.
```
[commit]
	template = c:/users/user/gitmessage.txt
```
