### ISSUE TITLE
feature-request: Save size of build status summary column if build server integration is activated

### ISSUE THREAD

**Issue by johnfidel** [gitextensions/gitextensions#3790]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
If build server integration is activated, the column of build status summary is resized every time git extensions is reopened. It is possible to resize it by cursor but this is not saved permanently

**What is the expected behavior?**
In my oppition it would be nice, if the size of the columns would be saved as the size of mainwindow is too.

**Comment by EbenZhang** [comment]
Can you reword you issue title to include more information instead of just `feature`?
