### ISSUE TITLE
"Change Working Directory" Dropdown does not persist list correclty

### ISSUE THREAD

**Issue by jaijitendra** [gitextensions/gitextensions#3791]
I deleted the item from the dropdown list but it still appears in the list when I open app next time.

**Comment by RussKie** [comment]
Please use the issue template next time, it is there for a reason.

Now please provide more details on your issue, what version you're using, how to reproduce your issue and what is the expected behavior.

Without this your issue is unlikely to be looked at, and quite likely will be closed.

**Comment by RussKie** [comment]
Closing due to lack of clarity and inactivity
