### ISSUE TITLE
No Simplified Chinese language in GitEx 2.50.00

### ISSUE THREAD

**Issue by Fsu0413** [gitextensions/gitextensions#3793]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Same as title
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open Tools→Settings
Click "The configured language is xxxxxxx"
There is no Chinese translation anymore.

**What is the expected behavior?**
Chinese is not missing in later versions.
**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitEx 2.50.00 Git 2.13.2 Win7SP1
GitEx 2.49.03 works

**Comment by jbialobr** [comment]
The Simplified Chinese language was translated below 95% therefore it was removed from the installer.
See https://github.com/gitextensions/gitextensions/wiki/Release-cycle#2-preparing-to-release.
