### ISSUE TITLE
NRE when attempting to push with no remote configured

### ISSUE THREAD

**Issue by matthewtylerwood** [gitextensions/gitextensions#3794]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When no remote is configured for a new repository, an attempt to push results in a NRE.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a new repository, commit some changes, and try to push with no remote configured.

**What is the expected behavior?**
Open the push dialog with no remote populated.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions 2.50.00, GIT 2.12.2, and Windows 7.
Yes, it worked in previous versions.

**Comment by EbenZhang** [comment]
So #3547 is back? i will double check later.

**Comment by matthewtylerwood** [comment]
Yes, this looks like the same behavior.
