### ISSUE TITLE
Font selection lets you select font style but then ignores it

### ISSUE THREAD

**Issue by GufNZ** [gitextensions/gitextensions#3795]
**Minor *bug***

**Current behavior?**
Selecting a font for code or commit message etc uses the standard dialog that lets you select the font name, style and size.
However, GitExtensions ignores the selected style, reverting to Normal every time.
I.e. I pick a font for code but select Bold, and I don't get Bold.

**Expected behavior?**
Style applied as well as size and font face.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
2.5 affected - don't know what it used to do in previous versions but the ones that I had used previously also had this issue as far as I can remember.

**Comment by gerhardol** [comment]
Similar for effects (underline, overstricken), that can be hidden though
Bold/italic is just ignored, similar to characterset

GitUI\CommandsDialogs\SettingsDialog\Pages\AppearanceSettingsPage.cs commitFontChangeButton_Click()
Italics/bold is not stored in Plugins\GitUIPluginInterfaces\ISettingsSource.cs
and not restored when reading

I suggest this kept as a known bug unless the

**Comment by RussKie** [comment]
> I suggest this kept as a known bug unless the

Unless what? Have you run out of spare characters? :)

**Comment by GufNZ** [comment]
The reason I logged this is I have a hand-tuned font that I code in, and like to use everywhere, but I only tuned the bold version.  I can select the bold version, but it uses the normal version instead.

**Comment by RussKie** [comment]
I hacked it for a bit, the change to enable persistence and read of chosen fonts is trivial:

```diff
diff --git a/Plugins/GitUIPluginInterfaces/ISettingsSource.cs b/Plugins/GitUIPluginInterfaces/ISettingsSource.cs
index 97522b1ef..2d33e4138 100644
--- a/Plugins/GitUIPluginInterfaces/ISettingsSource.cs
+++ b/Plugins/GitUIPluginInterfaces/ISettingsSource.cs
@@ -191,7 +191,7 @@ public static class FontParser
         public static string AsString(this Font value)
         {
             return string.Format(CultureInfo.InvariantCulture,
-                "{0};{1};{2}", value.FontFamily.Name, value.Size, InvariantCultureId);
+                "{0};{1};{2};{3};{4}", value.FontFamily.Name, value.Size, InvariantCultureId, value.Bold ? 1 : 0, value.Italic ? 1 : 0);
         }
 
         public static Font Parse(this string value, Font defaultValue)
@@ -221,7 +221,10 @@ public static Font Parse(this string value, Font defaultValue)
                     fontSize = fontSize.Replace(".", CultureInfo.InvariantCulture.NumberFormat.NumberDecimalSeparator);
                 }
 
-                return new Font(parts[0], float.Parse(fontSize, CultureInfo.InvariantCulture));
+                var fontStyle = parts.Length > 3 && parts[3] == "1" ? FontStyle.Bold : FontStyle.Regular;
+                fontStyle |= parts.Length > 4 && parts[4] == "1" ? FontStyle.Italic : FontStyle.Regular;
+
+                return new Font(parts[0], float.Parse(fontSize, CultureInfo.InvariantCulture), fontStyle);
             }
             catch
             {
```

However the `FileViewControl` needs a tweak.


@GufNZ is something like this you have in mind?
![image](https://user-images.githubusercontent.com/4403806/45688475-cb969f00-bb94-11e8-9091-612a10c7559f.png)

**Comment by chris-findlay** [comment]
That looks like what I'm after, tho in particular for the code font.

**Comment by RussKie** [comment]
I couldn't get the `ICSharpCode.TextEditor` to display bold/italics fonts.
I think it is driven by [the language definitions](https://github.com/gitextensions/ICSharpCode.TextEditor/tree/a2111678abf145e7ae898c085534a93b635fe1b2/Project/Resources).

@KindDragon @drewnoakes any ideas?
