### ISSUE TITLE
Committing fails: could not read log file, Invalid argument

### ISSUE THREAD

**Issue by Dimitri0xff** [gitextensions/gitextensions#3800]
**Do you want to request a *feature* or report a *bug?***
bug
**What is the current behavior?**
When I try to commit, I get the following error message:

```
"git" commit -F "C:\Users\p\Documents\projects\teamplay\.git\COMMITMESSAGE"
fatal: could not read log file 'C:\Users\p\Documents\projects\teamplay\.git\COMMITMESSAGE"': Invalid argument
```

(notice the missing " on the left side of the error message)
If I execute exactly the same git commit command in Git Bash, it creates the commit just fine.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. In a repository add a file or make change
2. Open the Commit dialog
3. Stage files (staging works fine)
4. Write a commit message
5. Click Commit

**What is the expected behavior?**
A successful commit.
**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions 2.50.00 on Windows 10

**Comment by Tinsus** [comment]
since the last update to 2.50.00 I have this same error. Currently GitExtensions is useless for me.

**Comment by dogancelik** [comment]
Same error here, 2.50 final

**Comment by jbialobr** [comment]
What is the content of the `C:\Users\p\Documents\projects\teamplay.git` file?

**Comment by Dimitri0xff** [comment]
It should be projects\teamplay\.git
The COMMITMESSAGE file is there with the correct message.

**Comment by jbialobr** [comment]
Can you disable [ConEmu](https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#advanced-general-use-console-emulator-for-console-output-in-command-dialogs) and see if the problem still occurs?

**Comment by pysco68** [comment]
Hi there,

I just ran into the same issue, disabling ConEmu as @jbialobr suggested fixed the issue. 

NOTE: if you need additional debugging info just tell me what to try.

**Comment by Dimitri0xff** [comment]
Disabling ConEmu works for me too. Thank you.

**Comment by VsevolodGolovanov** [comment]
I use 2.50.01 on 2 PCs (both Win7). On one commit works fine, but on the other this issue happens consistently:

```
"git" commit -F "F:\rep\TechService-3.20\.git\COMMITMESSAGE"
fatal: could not read log file 'F:\rep\TechService-3.20\.git\COMMITMESSAGE"': Invalid argument
Done
```

**Comment by bastianeicher** [comment]
Also encountered this with Git Extensions 2.50.01 on multiple Windows 10 machines. Disabling ConEmu also "fixes" the issue for me.

**Comment by Bikeman868** [comment]
Can someone add instructions on how to "disable ConEmu" I have no idea what this is.

**Comment by bastianeicher** [comment]
@Bikeman868: Take a look at the link @jbialobr posted above:
https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#advanced-general-use-console-emulator-for-console-output-in-command-dialogs

**Comment by givanse** [comment]
Has the linked page been updated or changed? I look at the text in there and have no idea what to do with the info there. How do you disable ConEmu?

**Comment by RussKie** [comment]
No the link above is still pointing to the correct location.

Here's how to find settings:
![image](https://user-images.githubusercontent.com/4403806/40750949-796201a0-64ac-11e8-9b6a-093286619c0a.png)
