### ISSUE TITLE
SEG FAULT on every git operation.

### ISSUE THREAD

**Issue by kuehlriegecom** [gitextensions/gitextensions#3804]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
after updating to GitExtensions-2.50.00-SetupComplete, every git operation (i.e. git status) shows an error: SEG FAULT 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
open git console, git status
**What is the expected behavior?**
kuehl@KUEHL2014 MINGW64 /C/git/******** (********)
$ git status
On branch ********
nothing to commit, working tree clean

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions-2.50.00-SetupComplete, 
Windows 7 (x64) fully patched, 
Earlier i used GitExtensions-2.49.03-SetupComplete.
I was able to fix the problem: upgrade to the latest version of git for windows (Git-2.13.2-64-bit).

**Comment by kuehlriegecom** [comment]
Not even a reply? :(

**Comment by jbialobr** [comment]
Sorry. There is nothing we can help, it does not look like a GitExtensions issue.

**Comment by jbialobr** [comment]
There is an issue for  that in git repo https://github.com/git-for-windows/git/issues/1111
We have to distribute the newer version.
