### ISSUE TITLE
Selected item after staging a file

### ISSUE THREAD

**Issue by dushkin** [gitextensions/gitextensions#3805]
Hi, I want to report an issue that bothering me. I don't know if it is a bug or behavior by design.

The current behavior is that when staging a file for commit, the selection is moved to the next file in the upper list.

For me it is a huge drawback, because I do not always notice or remember that, and then, when I start to examine the file modifications in order to summarize them in the commit message, I actually don't see the changes of the staged file, but of the next un-staged file in the upper list.
I think that the normal behavior should have been auto selecting the staged file, because usually what I would have liked to do next thing is to write a commit message and commit the file to the server.

I currently use Git Extensions version 2.48.05, Window 7.

Thanks!
![screenhunter_227 jul 03 15 05](https://user-images.githubusercontent.com/17315325/27792165-1a434af4-6001-11e7-8995-03c1f8edfda6.jpg)

**Comment by pmiossec** [comment]
I think that it is expected and I like this behaviour (and so don't want to be changed!). 

That's, IMHO, because it is pretty rare that you want to commit only one file. 
And if you do that, that's a good practice to review each file change before staging it. 

With the current behavior, you could easily review the next file to stage (and do it with the 's' shortcut) or go to the next file using the bottom arrow.

I'm not sure (and can't verify) but I think you can achieve to do what you want by using the 'tab' shortcut. It's just something you should be accustomed to ;-)

**Comment by pmiossec** [comment]
>I'm not sure (and can't verify) but I think you can achieve to do what you want by using the 'tab' shortcut. It's just something you should be accustomed to ;-)

What I said is wrong, there is no way to pass from the upper list to down list with the 'tab' shortcut.
I think we have to fix that....

**Comment by jbialobr** [comment]
There is a shortcut to [FocusStagedFiles](https://github.com/gitextensions/gitextensions/blob/54a95c776cc8319dd6d024901598fa683b0dbe59/GitUI/CommandsDialogs/FormCommit.cs#L304)
GitExtensions could automatically select the first file from the staged list when the commit message box has gained focus.

**Comment by dushkin** [comment]
@jbialobr Please pardon me for lack of knowledge, but what is the way I can check this feature? Is it in the app options?

Thank you

**Comment by dushkin** [comment]
@pmiossec Thank you. You know, during time and experience I get to be convinced that as many as times I will commit files, it will let me remember better the intention of the changes, But if you disagree with me, I will gladly hear your reasons.

**Comment by RussKie** [comment]
I personally wouldn't want to have the focus switched from "unstaged" windows to "staged" after I stage a file. I  often go through unstaged files one by one and stage them manually, so for me the automatic switch would be a great detriment.

That's said, a good UX could be "*if I staged a file then pressed tab the focus goes to the 'staged' window selecting the files I staged last*".

**Comment by dushkin** [comment]
@RussKie Well, I would have appreciate a setting for that at least :)

**Comment by jbialobr** [comment]
>@jbialobr Please pardon me for lack of knowledge, but what is the way I can check this feature? Is it in the app options?

![gitext](https://user-images.githubusercontent.com/1003909/28262587-d04e0770-6ae3-11e7-81b2-f0ab14209c70.png)

**Comment by dushkin** [comment]
Thank you jbialobr. I wanted the staged file get the focus right after I stage it, so I will not loose the diff view of this file and be able to write the commit message safely.
This hotkey just moves the focus to the staged files list.
But if this is the situation - so this is the situation... :)

**Comment by pmiossec** [comment]
@dushkin I have worked on that some days ago to improve the workflow in the commit form.

That needs more work before doing a pull request but you could have a look... 
https://github.com/pmiossec/gitextensions/tree/form_commit_workflow_improvements?files=1

But I don't know when I will be able to find time to continue on that...
