### ISSUE TITLE
Refresh on startup regression

### ISSUE THREAD

**Issue by rgl** [gitextensions/gitextensions#3808]
On Ubuntu, GitExtensions 2.50, does not automatically refresh the repository commits list anymore, it just shows this loading indicator (NB I don't see any error messages on the application output):

![image](https://user-images.githubusercontent.com/43356/27840170-cbfaf150-60ee-11e7-8053-7cfdfd9b0ced.png)

If I manually refresh (e.g. F5) it works fine. It also works fine when I use the combobox to switch the repository.

**Comment by ltvan** [comment]
I've also seen this symptom on Windows 10, GitExt 2.5, only when the repos have few commits.

**Comment by RussKie** [comment]
I believe it is caused by this line: https://github.com/gitextensions/gitextensions/blob/master/GitUI/UserControls/ToolStripGitStatus.cs#L176
