### ISSUE TITLE
Turn off zebra striping in 2.50 browser?

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#3810]
How can I turn off the new gray/white zebra striping in the repository browser? I don't see anything in the View menu or in Tools, Settings, Colors.

**Comment by asherber** [comment]
From the code, it looks like this is not currently configurable. 

Please consider this a feature request to make this feature configurable. I'll have to go back to 2.49.03 in the meantime because there's just too much visual noise in this dialog currently.

**Comment by vbjay** [comment]
Try ctrl + shift + L.

**Comment by asherber** [comment]
That cycles me through a bunch of different layouts, some of which are completely unreadable, but it does not get rid of the zebra striping.

**Comment by vbjay** [comment]
I know. Wasn't sure if one would help you out.

**Comment by RussKie** [comment]
Could you please post a screenshot of what your issue?

**Comment by asherber** [comment]
![image](https://user-images.githubusercontent.com/5248041/27887220-949d07b0-61ad-11e7-9acd-144d9ac7fba4.png)

Alternate light and dark zebra striping in the revision grid.

The code is here: https://github.com/gitextensions/gitextensions/blob/master/GitUI/UserControls/RevisionGrid.cs#L1501
