### ISSUE TITLE
[Bug / Regression] It is not possible to run an external difftool (F3) in the diff view of "Commit index / Current unstaged changes"

### ISSUE THREAD

**Issue by Radioactive-Man** [gitextensions/gitextensions#3814]
If the setting "Show current working directory changes in revision graph" is enabled it is not possible to execute the difftool in the Diff view for a selected file which is either in Commit index or Current unstaged changes. This was working in 2.49 and earlier and stopped working with 2.50

I have the feeling that this commit has introduced the regression but I am not an C# expert

Author:		Antonio Maiorano <amaiorano@gmail.com>
Author date:	6 months ago (01.01.2017 19:12:20)
Commit date:	4 months ago (05.03.2017 04:16:44)
Commit hash:	62f3eea8d9162e692acfa987ec6c35c803a57011
Parent(s):	ccd0f8dc5d

Allow opening difftool on multiple selected files in Commit, Browse, and Diff forms

**Comment by dzintaras** [comment]
Still same bug v2.50.01 when trying to use F3 in diff window: in main window click on some commit -> opens diff window of that commit; then pick any file in the commit -> pressing F3 should open external diff toll but does nothing

**Comment by gerhardol** [comment]
Corrected in 2.51, many changes in #4031 
Note: Most external difftool will do nothing if there is no changes. Some "diff to local" cannot be disabled in the menu
