### ISSUE TITLE
[Bug] after 2.50 unable to use "Revert selected lines" from commit window

### ISSUE THREAD

**Issue by erikleo** [gitextensions/gitextensions#3819]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
getting error:

---------------------------

---------------------------
error: app/index.js: does not match index

diff --git a/app/index.js b/app/index.js
index cb12d37..605d9c3 100644
--- a/app/index.js
+++ b/app/index.js
@@ -8,7 +8,6 @@
 
 initDependencyContainer();
 
-//test change
 
 ReactDOM.render(<App />, document.getElementById('root'));
 // registerServiceWorker();
--
GitExtensions 2.50.00
---------------------------
OK   
---------------------------

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Make a change, press commit, then right click on a changed line and choose "Revert selected lines"

I have tried and get the same error on multiple machines and multiple repositories

**What is the expected behavior?**
changes should be reverted instead of error

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
was working on previous version

**Comment by jbialobr** [comment]
You probably want to Reset selected lines (the menu item at the botom of the context menu). The revert item is enabled by mistake, it is only for a commited diff.

**Comment by erikleo** [comment]
Yes, that was it. Thanks Janusz!
