### ISSUE TITLE
Height of bottom tab control (Commit-Info, File-Tree, Diff) gets smaller on GitExtensions start

### ISSUE THREAD

**Issue by slaut** [gitextensions/gitextensions#3822]
Hi,

Every time you restart GitExtensions the bottom tab control is getting smaller and smaller.
Please see attached image for details

![grafik](https://user-images.githubusercontent.com/1819233/27959746-f25ba2e0-6328-11e7-8cc3-08dd42a0ba95.png)

Version is 2.50

**Comment by jbialobr** [comment]
This issue is addressed in #3681.

**Comment by RussKie** [comment]
If you click "Toggle split view layout" button twice it resets the layout. 
![image](https://user-images.githubusercontent.com/4403806/27985101-07a572f2-6428-11e7-86aa-a9f32d9e92d0.png)

It is not a fix, a mere work around for now...

**Comment by jbialobr** [comment]
Fixed in #3681
