### ISSUE TITLE
Add "Revert file's changes" to diff windows, file context menu

### ISSUE THREAD

**Issue by PierrotG** [gitextensions/gitextensions#3824]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
In the Diff window, right click on a file, there is an option to "Cherry pick file's changes" but there is no option to "Revert file's changes".

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not a bug.

**What is the expected behavior?**
In the diff windows, on the file contextual menu, have an option "Revert file's changes" next to the "Cherry pick file's changes", the same way we get "Revert Commit" for commits and "Revert selected lines" for individual chunks.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
This is present from the beginning. Version 2.50 has introduced the ability to revert chunks, I thought it would be nice to have this option also for file changes.

Thanks!

**Comment by RussKie** [comment]
"Reset file(s)..." allows you to revert to the previous commit.

**Comment by gerhardol** [comment]
Reset is not exactly the same
The workaround is to select the revisions in the reverse order before cherry picking
