### ISSUE TITLE
"Clean working directory" form layout broken at high DPI

### ISSUE THREAD

**Issue by xlfdll** [gitextensions/gitextensions#3828]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
The "Clean working directory" form looks like this:
![gitextensions1](https://user-images.githubusercontent.com/3493871/27997926-d899e94a-64b6-11e7-8eb4-72e84df182d1.PNG)
Every time when I use it, the form is always big like this. Sometimes the buttons are shown, but most of times they are not. It really depends on pure luck.
I tried to change the location of the main form, and tried to changed the size of the "Clean working directory" form, no help. I have to reopen all these forms several times (sometimes 10+ times) to get the buttons out

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
0. Use MacBook Pro Retina (Mid 2014) and Windows 10 Enterprise, set up display settings using default 2880 x 1800 resolution and 175% scaling
1. Right-click a folder that is a Git repository, and choose "GitExt Browse"
2. Click "Commands" menu, and choose "Clean working directory" menu item
The form 

**What is the expected behavior?**
The form should be correctly shown as
1. All the controls, including buttons, are shown in correct positions on the form
2. The form's size should be (physically) 1/4 of the screen, instead of filling the whole

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
The version of GitExtensions I am using is 2.50.01, and the Git version is 2.11.1.windows.1.
The Windows version I am using is Windows 10 Enterprise Version 1703 (Build 15063.413), x64 edition

Also, the machine I am using is MacBook Pro Retina (Mid 2014), using 2880x1800 resolution and 175% scaling in Windows Display Settings.
The display adapter is NVIDIA GeForce GT 750M, and the driver version is 382.05.

A side note: My system UI is in Japanese, and non-Unicode setting is in Chinese (PRC) (should not affect this, but I just listed here for reference)

This issue did not exist until GitExtensions 2.49 releases (scaled incorrectly but still usable), and started to get worse on 2.50 releases (the buttons will disappear most of the time).

**Comment by realityexists** [comment]
I'm experiencing this also on Windows 7 Pro, Git Extensions 2.50.02. I have a laptop with two external monitors at 2560x1440 resolution and Git Extensions is on one of these. Each time I open the Clean Working Directory window it's bigger than before! It just keeps growing, so I have to resize it all the time. Very annoying!

**Comment by RussKie** [comment]
@electronicdreamer has kindly posted a workaround for hdpi issue https://github.com/gitextensions/gitextensions/issues/4099#issuecomment-349899698.
See if it helps in any way

**Comment by loop-evgeny** [comment]
I just tried this (created the manifest file and added the registry entry), but it doesn't help with the "Clean working directory" dialog growing.

**Comment by electronicdreamer** [comment]
Just tried this on my version of GE that has the manifest + registry key and the dialog is normal sized.

**Comment by RussKie** [comment]
Could you please test and confirm the fix: https://ci.appveyor.com/api/buildjobs/ws847oed1v5q3tjb/artifacts/GitExtensions-2.51.01.2515-Mono.zip

**Comment by loop-evgeny** [comment]
Seems to be fixed, thanks!

**Comment by RussKie** [comment]
Thank you
