### ISSUE TITLE
help picture disappeared when opening pull dialog

### ISSUE THREAD

**Issue by zero2lin** [gitextensions/gitextensions#3829]
Here is a bug at v2.50.01.
When I open pull dialog, the help picture on the left doesn't show.

**Comment by nsartor** [comment]
I'm seeing this too. If you toggle the "Merge Options" radio buttons the help picture re-appears, but only while the dialog is open.

Running on Windows 
![git extensions](https://user-images.githubusercontent.com/6578903/28024198-fddaace2-655d-11e7-8b24-d3e47147e00d.png)

**Comment by RussKie** [comment]
I witnessed it too on for a brand new installation of GitExtensions-2.50RC2-Setup.msi on Win8.1.
It wasn't my computer so I had no chance to debug it... 😞

**Comment by RussKie** [comment]
Happened to me today while debugging other issues... 

It looks like images aren't getting loaded and the panel gets the default dimensions
![image](https://user-images.githubusercontent.com/4403806/29483382-5940f204-84e8-11e7-887e-590518039595.png)

I will see if I can find out why...
