### ISSUE TITLE
Annoying closing of menu from tool bar buttons

### ISSUE THREAD

**Issue by TanukiSharp** [gitextensions/gitextensions#3832]
This is a **bug** report, with a fix proposal.

The current behavior is when I click the small black arrow of tool bar buttons and a contextual menu opens, the menu closes if the mouse leave the control. It happens with all `ToolStripSplitButton` controls. (Superproject, Stash and Pull ones)

![_gitextensions_pr](https://user-images.githubusercontent.com/4018313/28027169-1d6f6cd0-65d3-11e7-81c6-c12d20f15399.png)

I figured out this happens in a certain `Focus` configuration, when mouse overs the buttons and they render an emboss, this bug happens, however if the branch drop down or the filter text box is focused, the tool bar buttons do not render their emboss on mouse over, and in this focus configuration, the menu does not closes when the mouse exit its area.

I implemented a fix based on this workaround.

This issue is of course not related to Git but purely UI and happens even in `2.50.01`. So far I always encountered this issue, which really drives me nuts.

That said, I wonder if I'm the only one pissed off by this issue because I couldn't find any report of it.

I've read the contribution guidelines a bit too late and already implemented a fix, the commit can be reviewed here: https://github.com/TanukiSharp/gitextensions/commit/f4d2e5bd41660493392f227c15a817cb5b3c380f

The way I fixed it is by enforcing the focus to a control that prevent menu to close (branch drop down), only if it is not already focused (and if the filter text box is not focused either). I store the focused control in the button's `Tag` property in order to restore the focus when the `ToolStripSplitButton` closes. This may break something if the `Tag` property can be used for another feature.

This fix looks like a hack, but I couldn't find any other way around.

I implemented a solution based on constraining the mouse position (screen space) in order to ensure the mouse can only leave the control from top, left and bottom but never from the right. This works, but looks even more cheesy. We can talk about it.

Another solution would be to re-implement the `ToolStripSplitButton` based on a regular `Button` with a `ContextMenu` attach to it, but this is quite a lot of work.

**Comment by RussKie** [comment]
> That said, I wonder if I'm the only one pissed off by this issue because I couldn't find any report of it.

I reproduced the behaviour you describe, but I must be more dexterous - I move my mouse down and rarely have the menu closing on me.

> Another solution would be to re-implement the ToolStripSplitButton based on a regular Button with a ContextMenu attach to it, but this is quite a lot of work.

No. We're not reimplementing default Windows controls. 
No offense, but if MS couldn't get it right it is very unlikely anyone of us will be able to reimplement them correctly to work across different platforms (Windows, Linux, Mac), styles and themes, DPI scaling etc.

> I've read the contribution guidelines a bit too late and already implemented a fix, the commit can be reviewed here: TanukiSharp/gitextensions@f4d2e5b

Please create a branch on your fork, then make a pull request from your branch on your fork to the main repo.

**Comment by RussKie** [comment]
Also, what happens in the following scenario?

> The user clicked on the little arrow, the dropdown appeared. The user moves the mouse away. 

Does the dropdown stay opened? If so, how does it get closed?

**Comment by TanukiSharp** [comment]
Thanks for the response, I will do as you said, create a branch and submit a pull request to master.

> Does the dropdown stay opened? If so, how does it get closed?

If you are talking about after the fix applied? Then:
- Yes the dropdown stay open
- Any click closes the menu (whether one if its context menu or anywhere else)

**Comment by TanukiSharp** [comment]
PR #3833 created.

**Comment by TanukiSharp** [comment]
Updated the branch.

**Comment by TanukiSharp** [comment]
Seems like I can't reopen closed issues, but this problem is back in the latest version.
```
- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)
```
