### ISSUE TITLE
how to uncommit git ignored files when added to tracked files

### ISSUE THREAD

**Issue by eljie092690** [gitextensions/gitextensions#3837]
--- GitExtensions2.47.3, Git 1.8.0.msysgit.0, Microsoft Windows NT 6.3.9600.0

Good morning,
I just want to ask something regarding on how to uncommit certain files when added to track files on the git repository

**Comment by vbjay** [comment]
Have they been committed before?  Read up on gitignore and assume
unchanged. Then understand that git is designed to never forget.

**Comment by RussKie** [comment]
You can still delete them from the repo, though these files will be available in the existing history

**Comment by eljie092690** [comment]
My solution sir is to create a stable master branch, delete the git version control system and reinitialize the repo to clear the history and start over. I think, this will be the best solution and still im trying to find more ways to solve this problem.. tnx for the help :)

**Comment by vbjay** [comment]
If you want to clear out a file from a repo you don't need to be that
drastic. Just know you will be rewriting history.

https://stackoverflow.com/questions/872565/remove-sensitive-files-and-their-commits-from-git-history

**Comment by eljie092690** [comment]
ok sir @vbjay  but in my situation, the problem was the main branch master is already been affected by the ignored files. Everytime we do reset's or merging, we  need to be cautious because it the tracked ignored files might cause problems on the production.

**Comment by vbjay** [comment]
That's were assume unchanged comes into play. Using git filter-branch with
the right arguments will erase the file from your history. Which will in
turn create new commits in place of the ones that had the files. If you
then have everyone reset to the head that is the new head after the
filter-branch call, you will have erased the file from history. The next
thing is to add the path to .gitignore. Then resets will not affect the
file.

**Comment by eljie092690** [comment]
Ahh i see, i could just filter the master branch. After when everything is in place, i could just do a rebase to make my changes the new master and the flow of commit history is still intact. tnx @vbjay
