### ISSUE TITLE
Anyone build and debug on Linux?

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#3838]
I run on:
* Ubuntu 16.04
* Mono 5.0.1.1 
* MonoDevelop IDE (tried it both from flatpack and Software center)

I can run the app via `mono GitExtensions.exe` fine:
![image](https://user-images.githubusercontent.com/4403806/28110199-f0a52510-6734-11e7-9de3-d78f5697668e.png)

But I'm having dramas debugging it from MonoDevelop - when started GE tells me it can't find git:
![image](https://user-images.githubusercontent.com/4403806/28110087-95dde41e-6734-11e7-8341-61a7cc30a475.png)

Without debugging I'm having a huge drama fixing UI bugs....
Any help or guidance is highly appreciated.

**Comment by JerryLumpkins** [comment]
I downloaded the latest mono release of git extensions, and am running it. 
There's a problem with merging. The merge dialog doesn't have a pull down for the user to select the branch to be merged in. Everything else seems to be working.

I'll try to build later today. I don't have time right now. I'm running Ubuntu 17.04

**Comment by RussKie** [comment]
Do you use MonoDevelop to build?

**Comment by JerryLumpkins** [comment]
The last time I actually built I did. I'm starting over, and deleted everything I had saved previously.
What branch are you using? (master or mono)?

**Comment by JerryLumpkins** [comment]
Has the mono branch been abandoned? I don't see any commits since mid-2016.

**Comment by RussKie** [comment]
I've been running the GitExtensionsMono.sln off master. 
I didn't know there was a dedicated mono branch.
