### ISSUE TITLE
GitFlow plugin is missing since GitExtensions v2.49.03

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#3839]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
missing GitFlow plugin from menu

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See the Plugins menu

**What is the expected behavior?**
Show the GitFlow menu.
The GitFlow.dll is missing from Plugins directory of GitExtensions-2.50.01-Mono.zip

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
Windows 7 Pro
GitExtensions v2.50.01
GitFlow plugin was last available in the GitExtensions v2.49.03. Never seen after that.

**Comment by escherstair** [comment]
I upgraded from v2.49.03 to v2.50, and then to v2.50.01 through GitExtensions-X.XX.XX-SetupComplete.msi and GitFlow plugin is available.
I don't know if this is because it was originally installed on my PC, or because the issue refers to Mono.zip package only.

**Comment by klorinczi** [comment]
1) Because the issue refers to Mono.zip package only.
2) While upgrading, I think the installed plugin DLL-s are kept.

**Comment by RussKie** [comment]
You can try https://ci.appveyor.com/api/buildjobs/a5444bf5ml684m1l/artifacts/GitExtensions-2.50.02.1167-Mono.zip

**Comment by webmaster33** [comment]
Great! Thanks!
