### ISSUE TITLE
Unable to open UNC repo in root of network share

### ISSUE THREAD

**Issue by laurin1** [gitextensions/gitextensions#3840]
Opening a repo here does not work:

\\\\fileserver.pridedallas.com\\ScriptsPublic

![image](https://user-images.githubusercontent.com/75857/28117876-b46d8d54-66d4-11e7-8f3e-96961af9e077.png)

But this works:

\\\\fileserver.pridedallas.com\\ScriptsPublic\\Repo

![image](https://user-images.githubusercontent.com/75857/28117894-c3a42454-66d4-11e7-9441-e20ee98b4d31.png)

GitExtensions 2.49.03 & 2.50.01
Git 2.13.2.windows.1
Windows 10 Pro x64 1703

**Comment by RussKie** [comment]
in which folder do you have .git folder?

**Comment by laurin1** [comment]
\\fileserver.pridedallas.com\ScriptsPublic\.git

**Comment by vbjay** [comment]
I wouldn't do it this way. I would host a bare repo on the site and add a
local remote. Also. I would not put it at the root. I would have repos
share\repo folder.

**Comment by vbjay** [comment]
http://www.vogella.com/tutorials/Git/article.html#remotes

**Comment by laurin1** [comment]
Well, I appreciate your guidance, but this is not for remote repos - if we have a remote repo, we do put a bare repo as you suggest. But regardless, why should we have to have a subfolder on a share for one repo?

Why  does this not work in the root?

**Comment by vbjay** [comment]
It is remote. It is on a unc share. Each computer should have its own copy
of the repo. Each copy has a remote to the unc one.

The reason I suggest a subfolder is so you can do this

...\repos\repo 1
...\repos\repo 2
...

You may have 1 repo now. Plan for the future.

**Comment by laurin1** [comment]
I understand why you think that, **but that's assuming that each user uses only one machine** - I manage a dozen **local** machines (it's not remote, it's just not the machine I am directly logged into, and I don't want to remote (RDP or such) into them to access these repos just to do maintenance, etc..) Plan for the future? Seriously, I'm reporting a bug. If you don't like my methodology, that's fine. But can we focus on the issue and not "best practices". Are you are saying this won't be fixed because it's not a good idea?

**Comment by vbjay** [comment]
That's fine. Workflow:

Machine x not unc repo machine

Pull from unc
Do local work.
Commit as many times as needed
Push to unc

Machine y
Same process.

Just make sure you push.

The other thing you can do is add remotes to each machine to the unc repo.
Fetch and pull all you want.

**Comment by RussKie** [comment]
Perhaps related to https://github.com/gitextensions/gitextensions/issues/3489

@laurin1 could you try running `GitExtensions.exe browse \\fileserver.pridedallas.com\ScriptsPublic\.`?

**Comment by RussKie** [comment]
I can't replicate the problem. I tried 2.49.03 and 2.50.01 on Win10 git 2.12.2
I copied an existing git repo to a local server, shared it then tried opening from my local machine. No errors.

**Comment by laurin1** [comment]
bare or personal? bare repos works, but personal do not for me.

**Comment by laurin1** [comment]
> @laurin1 could you try running GitExtensions.exe browse \\fileserver.pridedallas.com\ScriptsPublic\.?

Same result.

![image](https://user-images.githubusercontent.com/75857/28724031-59d585b6-737e-11e7-8ccc-6df9e80ff137.png)

**Comment by laurin1** [comment]
I just tested this and right now, the issue is no longer happening.

**Comment by RussKie** [comment]
Thank you for letting us know.
