### ISSUE TITLE
DirectoryNotFoundException in Remote Repositories dialog

### ISSUE THREAD

**Issue by danlyons-softek** [gitextensions/gitextensions#3844]
When I first attempted to push a branch after the update to 2.50.01, it prompted me to say that there was no tracking reference.  This was odd, as I have been working in it for a while now, and have pushed many times before now.

Since it was an unexpected prompt, I cancelled the push and opened up the Remote Repositories dialog.  All the information about my remote repositories (aside from their names) had been wiped clean, and all tracking references to branches in the pull behavior tab was similarly gone.

Upon filling in the information for my remote repository, testing to make sure everything was correct, and clicking the save button, I was greeted with the following error dialog:
![image](https://user-images.githubusercontent.com/3289668/28125802-502f8054-66ed-11e7-8ad5-183d6ceee0c1.png)

Oddly, it appears the values are set anyway, as closing and re-opening the dialog reveals the information is still there.  However, it does not appear to persist the information to disk, since the information is gone again upon re-opening the application.

The same dialog appears when I attempt to modify tracking references in the pull behavior tab, and the values similarly are saved to memory but not to disk.

I'm not aware of it happening in 2.50.00, since I do not have to mess with the remote repositories much, but it wasn't a problem in the version I had before that (2.49.01)

**Comment by jbialobr** [comment]
What is your git version?

**Comment by cacaocake** [comment]
I have same issue.
My git version is 2.50.01
![image](https://user-images.githubusercontent.com/1390264/28650601-dde281f0-72b7-11e7-8d2e-27ddfce2a2a4.png)

**Comment by vbjay** [comment]
That's gitextensions version, not git version.

**Comment by cacaocake** [comment]
Git version is 1.9.4

**Comment by vbjay** [comment]
You did see that this issue was closed with a fix right?

**Comment by cacaocake** [comment]
Yes, I knew

**Comment by jbialobr** [comment]
@cacaocake Upgrade your git to the latest version to not having to wait for the patched GitExtensions.

**Comment by cacaocake** [comment]
Thank you! It works on me.
