### ISSUE TITLE
Application crashing on startup after upgrading to 2.50.01

### ISSUE THREAD

**Issue by mgressman-marketvision** [gitextensions/gitextensions#3845]
After upgrading to 2.50.01 from 2.49.03 on Windows 10 machine, the application crashes on startup with the following exception happens:

![image](https://user-images.githubusercontent.com/19785506/28134232-f4e8eda0-6707-11e7-979f-5ecdce98389b.png)

Uninstalling and reinstalling 2.50.01 does not help.

Reinstalling 2.49.03 works.

**Comment by RussKie** [comment]
Can you share your `SerializedHotkeys` setting value?

Open up C:\Users\<username>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings and look for the setting.

It looks like:

```
  <item>
    <key>
      <string>SerializedHotkeys</string>
    </key>
    <value>
      <string>&lt;?xml version="1.0" encoding="utf-16"?&gt;
&lt;ArrayOfHotkeySettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"&gt;
 ....
</string>
    </value>
  </item>
```

**Comment by mgressman-marketvision** [comment]
<item>
    <key>
      <string>SerializedHotkeys</string>
    </key>
    <value>
      <string>&lt;?xml version="1.0" encoding="utf-16"?&gt;
&lt;ArrayOfHotkeySettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"&gt;
  &lt;HotkeySettings Name="Commit"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="0" Name="AddToGitIgnore" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="1" Name="DeleteSelectedFiles" KeyData="Delete" /&gt;
      &lt;HotkeyCommand CommandCode="2" Name="FocusUnstagedFiles" KeyData="LButton ShiftKey ControlKey Space Prior PageUp D0 D1 Control" /&gt;
      &lt;HotkeyCommand CommandCode="3" Name="FocusSelectedDiff" KeyData="RButton ShiftKey Menu Space Next PageDown D0 D2 Control" /&gt;
      &lt;HotkeyCommand CommandCode="4" Name="FocusStagedFiles" KeyData="LButton RButton Cancel ShiftKey ControlKey Menu Pause Space Prior PageUp Next PageDown End D0 D1 D2 D3 Control" /&gt;
      &lt;HotkeyCommand CommandCode="5" Name="FocusCommitMessage" KeyData="MButton ShiftKey Capital CapsLock Space Home D0 D4 Control" /&gt;
      &lt;HotkeyCommand CommandCode="6" Name="ResetSelectedFiles" KeyData="R" /&gt;
      &lt;HotkeyCommand CommandCode="7" Name="StageSelectedFile" KeyData="S" /&gt;
      &lt;HotkeyCommand CommandCode="8" Name="UnStageSelectedFile" KeyData="U" /&gt;
      &lt;HotkeyCommand CommandCode="9" Name="ShowHistory" KeyData="H" /&gt;
      &lt;HotkeyCommand CommandCode="10" Name="ToggleSelectionFilter" KeyData="RButton MButton XButton2 B D F Control" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
  &lt;HotkeySettings Name="Browse"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="0" Name="GitBash" KeyData="LButton RButton Cancel MButton XButton1 XButton2 A B C D E F G Control" /&gt;
      &lt;HotkeyCommand CommandCode="1" Name="GitGui" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="2" Name="GitGitK" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="3" Name="FocusRevisionGrid" KeyData="LButton ShiftKey ControlKey Space Prior PageUp D0 D1 Control" /&gt;
      &lt;HotkeyCommand CommandCode="4" Name="FocusCommitInfo" KeyData="RButton ShiftKey Menu Space Next PageDown D0 D2 Control" /&gt;
      &lt;HotkeyCommand CommandCode="5" Name="FocusFileTree" KeyData="LButton RButton Cancel ShiftKey ControlKey Menu Pause Space Prior PageUp Next PageDown End D0 D1 D2 D3 Control" /&gt;
      &lt;HotkeyCommand CommandCode="6" Name="FocusDiff" KeyData="MButton ShiftKey Capital CapsLock Space Home D0 D4 Control" /&gt;
      &lt;HotkeyCommand CommandCode="7" Name="Commit" KeyData="Space Control" /&gt;
      &lt;HotkeyCommand CommandCode="8" Name="AddNotes" KeyData="RButton MButton XButton2 Back LineFeed Clear B D F H J L N Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="9" Name="FindFileInSelectedCommit" KeyData="RButton MButton XButton2 B D F Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="10" Name="CheckoutBranch" KeyData="RButton MButton XButton2 Back LineFeed Clear Space Next PageDown Home Up Down Print Snapshot PrintScreen Delete B D F H J L N NumPad0 NumPad2 NumPad4 NumPad6 NumPad8 Multiply Separator Decimal Control" /&gt;
      &lt;HotkeyCommand CommandCode="11" Name="QuickFetch" KeyData="Back Space Down Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="12" Name="QuickPull" KeyData="ShiftKey P Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="13" Name="QuickPush" KeyData="RButton MButton XButton2 Space Next PageDown Home Up Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="15" Name="CloseRepositry" KeyData="LButton RButton Cancel MButton XButton1 XButton2 ShiftKey ControlKey Menu Pause Capital CapsLock KanaMode HanguelMode HangulMode JunjaMode A B C D E F G P Q R S T U V W Control" /&gt;
      &lt;HotkeyCommand CommandCode="14" Name="RotateApplicationIcon" KeyData="LButton Back Tab A H I Shift Control" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
  &lt;HotkeySettings Name="RevisionGrid"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="1" Name="RevisionFilter" KeyData="RButton MButton XButton2 B D F Control" /&gt;
      &lt;HotkeyCommand CommandCode="0" Name="ToggleRevisionGraph" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="2" Name="ToggleAuthorDateCommitDate" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="3" Name="ToggleOrderRevisionsByDate" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="4" Name="ToggleShowRelativeDate" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="5" Name="ToggleDrawNonRelativesGray" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="6" Name="ToggleShowGitNotes" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="7" Name="ToggleRevisionCardLayout" KeyData="MButton Back Clear D H L Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="8" Name="ToggleShowMergeCommits" KeyData="LButton MButton XButton1 Back Tab Clear Return Enter A D E H I L M Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="9" Name="ShowAllBranches" KeyData="LButton A Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="10" Name="ShowCurrentBranchOnly" KeyData="LButton MButton XButton1 ShiftKey ControlKey Capital CapsLock KanaMode HanguelMode HangulMode A D E P Q T U Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="11" Name="ShowFilteredBranches" KeyData="MButton ShiftKey Capital CapsLock D P T Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="12" Name="ShowRemoteBranches" KeyData="RButton ShiftKey Menu B P R Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="13" Name="ShowFirstParent" KeyData="LButton RButton Cancel ShiftKey ControlKey Menu Pause A B C P Q R S Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="14" Name="GoToParent" KeyData="ShiftKey P Control" /&gt;
      &lt;HotkeyCommand CommandCode="15" Name="GoToChild" KeyData="RButton MButton XButton2 Back LineFeed Clear B D F H J L N Control" /&gt;
      &lt;HotkeyCommand CommandCode="16" Name="ToggleHighlightSelectedBranch" KeyData="RButton B Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="17" Name="NextQuickSearch" KeyData="Back Space Down Alt" /&gt;
      &lt;HotkeyCommand CommandCode="18" Name="PrevQuickSearch" KeyData="RButton MButton XButton2 Space Next PageDown Home Up Alt" /&gt;
      &lt;HotkeyCommand CommandCode="19" Name="SelectCurrentRevision" KeyData="LButton RButton Cancel A B C Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="23" Name="SelectAsBaseToCompare" KeyData="MButton Back Clear D H L Control" /&gt;
      &lt;HotkeyCommand CommandCode="24" Name="CompareToBase" KeyData="RButton ShiftKey Menu B P R Control" /&gt;
      &lt;HotkeyCommand CommandCode="20" Name="GoToCommit" KeyData="LButton RButton Cancel MButton XButton1 XButton2 A B C D E F G Shift Control" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
  &lt;HotkeySettings Name="FileViewer"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="0" Name="Find" KeyData="RButton MButton XButton2 B D F Control" /&gt;
      &lt;HotkeyCommand CommandCode="1" Name="GoToLine" KeyData="LButton RButton Cancel MButton XButton1 XButton2 A B C D E F G Control" /&gt;
      &lt;HotkeyCommand CommandCode="2" Name="IncreaseNumberOfVisibleLines" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="3" Name="DecreaseNumberOfVisibleLines" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="4" Name="ShowEntireFile" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="5" Name="TreatFileAsText" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="6" Name="NextChange" KeyData="Back Space Down Alt" /&gt;
      &lt;HotkeyCommand CommandCode="7" Name="PreviousChange" KeyData="RButton MButton XButton2 Space Next PageDown Home Up Alt" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
  &lt;HotkeySettings Name="FormMergeConflicts"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="4" Name="ChooseBase" KeyData="B" /&gt;
      &lt;HotkeyCommand CommandCode="3" Name="ChooseLocal" KeyData="L" /&gt;
      &lt;HotkeyCommand CommandCode="2" Name="ChooseRemote" KeyData="R" /&gt;
      &lt;HotkeyCommand CommandCode="0" Name="Merge" KeyData="M" /&gt;
      &lt;HotkeyCommand CommandCode="1" Name="Rescan" KeyData="F5" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
  &lt;HotkeySettings Name="Scripts"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="9000" Name="Fetch changes after commit" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="9001" Name="Update submodules after pull" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="9002" Name="Example" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="9003" Name="Open on GitHub" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="9004" Name="Fetch All Submodules" KeyData="None" /&gt;
      &lt;HotkeyCommand xsi:nil="true" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
&lt;/ArrayOfHotkeySettings&gt;</string>
    </value>
  </item>

**Comment by RussKie** [comment]
I can't replicate the issue neither in 2.50.01 nor in the latest master... Your settings look normal.

Can you try to clear the value for `SerializedHotkeys` value in the config and try again?

**Comment by jbialobr** [comment]
Can you also share your `Hotkeys` element value from `c:\Users\username\AppData\Local\GitExtensions\*\2.49.3.0\user.config` file?

**Comment by mgressman-marketvision** [comment]
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" >
            <section name="GitUI.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <GitUI.Properties.Settings>
            <setting name="Dashboard_MainSplitContainer_SplitterDistance"
                serializeAs="String">
                <value>401</value>
            </setting>
            <setting name="Dashboard_CommonSplitContainer_SplitterDistance"
                serializeAs="String">
                <value>202</value>
            </setting>
            <setting name="Hotkeys" serializeAs="String">
                <value>&lt;?xml version="1.0" encoding="utf-16"?&gt;
&lt;ArrayOfHotkeySettings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"&gt;
  &lt;HotkeySettings Name="Commit"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="0" Name="AddToGitIgnore" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="1" Name="DeleteSelectedFiles" KeyData="Delete" /&gt;
      &lt;HotkeyCommand CommandCode="2" Name="FocusUnstagedFiles" KeyData="LButton ShiftKey ControlKey Space Prior PageUp D0 D1 Control" /&gt;
      &lt;HotkeyCommand CommandCode="3" Name="FocusSelectedDiff" KeyData="RButton ShiftKey Menu Space Next PageDown D0 D2 Control" /&gt;
      &lt;HotkeyCommand CommandCode="4" Name="FocusStagedFiles" KeyData="LButton RButton Cancel ShiftKey ControlKey Menu Pause Space Prior PageUp Next PageDown End D0 D1 D2 D3 Control" /&gt;
      &lt;HotkeyCommand CommandCode="5" Name="FocusCommitMessage" KeyData="MButton ShiftKey Capital CapsLock Space Home D0 D4 Control" /&gt;
      &lt;HotkeyCommand CommandCode="6" Name="ResetSelectedFiles" KeyData="R" /&gt;
      &lt;HotkeyCommand CommandCode="7" Name="StageSelectedFile" KeyData="S" /&gt;
      &lt;HotkeyCommand CommandCode="8" Name="UnStageSelectedFile" KeyData="U" /&gt;
      &lt;HotkeyCommand CommandCode="9" Name="ShowHistory" KeyData="H" /&gt;
      &lt;HotkeyCommand CommandCode="10" Name="ToggleSelectionFilter" KeyData="RButton MButton XButton2 B D F Control" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
  &lt;HotkeySettings Name="Browse"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="0" Name="GitBash" KeyData="LButton RButton Cancel MButton XButton1 XButton2 A B C D E F G Control" /&gt;
      &lt;HotkeyCommand CommandCode="1" Name="GitGui" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="2" Name="GitGitK" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="3" Name="FocusRevisionGrid" KeyData="LButton ShiftKey ControlKey Space Prior PageUp D0 D1 Control" /&gt;
      &lt;HotkeyCommand CommandCode="4" Name="FocusCommitInfo" KeyData="RButton ShiftKey Menu Space Next PageDown D0 D2 Control" /&gt;
      &lt;HotkeyCommand CommandCode="5" Name="FocusFileTree" KeyData="LButton RButton Cancel ShiftKey ControlKey Menu Pause Space Prior PageUp Next PageDown End D0 D1 D2 D3 Control" /&gt;
      &lt;HotkeyCommand CommandCode="6" Name="FocusDiff" KeyData="MButton ShiftKey Capital CapsLock Space Home D0 D4 Control" /&gt;
      &lt;HotkeyCommand CommandCode="7" Name="Commit" KeyData="Space Control" /&gt;
      &lt;HotkeyCommand CommandCode="8" Name="AddNotes" KeyData="RButton MButton XButton2 Back LineFeed Clear B D F H J L N Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="9" Name="FindFileInSelectedCommit" KeyData="RButton MButton XButton2 B D F Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="10" Name="CheckoutBranch" KeyData="RButton MButton XButton2 Back LineFeed Clear Space Next PageDown Home Up Down Print Snapshot PrintScreen Delete B D F H J L N NumPad0 NumPad2 NumPad4 NumPad6 NumPad8 Multiply Separator Decimal Control" /&gt;
      &lt;HotkeyCommand CommandCode="11" Name="QuickFetch" KeyData="Back Space Down Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="12" Name="QuickPull" KeyData="ShiftKey P Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="13" Name="QuickPush" KeyData="RButton MButton XButton2 Space Next PageDown Home Up Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="15" Name="CloseRepositry" KeyData="LButton RButton Cancel MButton XButton1 XButton2 ShiftKey ControlKey Menu Pause Capital CapsLock KanaMode HanguelMode HangulMode JunjaMode A B C D E F G P Q R S T U V W Control" /&gt;
      &lt;HotkeyCommand CommandCode="14" Name="RotateApplicationIcon" KeyData="LButton Back Tab A H I Shift Control" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
  &lt;HotkeySettings Name="RevisionGrid"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="1" Name="RevisionFilter" KeyData="RButton MButton XButton2 B D F Control" /&gt;
      &lt;HotkeyCommand CommandCode="0" Name="ToggleRevisionGraph" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="2" Name="ToggleAuthorDateCommitDate" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="3" Name="ToggleOrderRevisionsByDate" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="4" Name="ToggleShowRelativeDate" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="5" Name="ToggleDrawNonRelativesGray" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="6" Name="ToggleShowGitNotes" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="7" Name="ToggleRevisionCardLayout" KeyData="MButton Back Clear D H L Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="8" Name="ToggleShowMergeCommits" KeyData="LButton MButton XButton1 Back Tab Clear Return Enter A D E H I L M Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="9" Name="ShowAllBranches" KeyData="LButton A Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="10" Name="ShowCurrentBranchOnly" KeyData="LButton MButton XButton1 ShiftKey ControlKey Capital CapsLock KanaMode HanguelMode HangulMode A D E P Q T U Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="11" Name="ShowFilteredBranches" KeyData="MButton ShiftKey Capital CapsLock D P T Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="12" Name="ShowRemoteBranches" KeyData="RButton ShiftKey Menu B P R Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="13" Name="ShowFirstParent" KeyData="LButton RButton Cancel ShiftKey ControlKey Menu Pause A B C P Q R S Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="14" Name="GoToParent" KeyData="ShiftKey P Control" /&gt;
      &lt;HotkeyCommand CommandCode="15" Name="GoToChild" KeyData="RButton MButton XButton2 Back LineFeed Clear B D F H J L N Control" /&gt;
      &lt;HotkeyCommand CommandCode="16" Name="ToggleHighlightSelectedBranch" KeyData="RButton B Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="17" Name="NextQuickSearch" KeyData="Back Space Down Alt" /&gt;
      &lt;HotkeyCommand CommandCode="18" Name="PrevQuickSearch" KeyData="RButton MButton XButton2 Space Next PageDown Home Up Alt" /&gt;
      &lt;HotkeyCommand CommandCode="19" Name="SelectCurrentRevision" KeyData="LButton RButton Cancel A B C Shift Control" /&gt;
      &lt;HotkeyCommand CommandCode="23" Name="SelectAsBaseToCompare" KeyData="MButton Back Clear D H L Control" /&gt;
      &lt;HotkeyCommand CommandCode="24" Name="CompareToBase" KeyData="RButton ShiftKey Menu B P R Control" /&gt;
      &lt;HotkeyCommand CommandCode="20" Name="GoToCommit" KeyData="LButton RButton Cancel MButton XButton1 XButton2 A B C D E F G Shift Control" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
  &lt;HotkeySettings Name="FileViewer"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="0" Name="Find" KeyData="RButton MButton XButton2 B D F Control" /&gt;
      &lt;HotkeyCommand CommandCode="1" Name="GoToLine" KeyData="LButton RButton Cancel MButton XButton1 XButton2 A B C D E F G Control" /&gt;
      &lt;HotkeyCommand CommandCode="2" Name="IncreaseNumberOfVisibleLines" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="3" Name="DecreaseNumberOfVisibleLines" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="4" Name="ShowEntireFile" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="5" Name="TreatFileAsText" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="6" Name="NextChange" KeyData="Back Space Down Alt" /&gt;
      &lt;HotkeyCommand CommandCode="7" Name="PreviousChange" KeyData="RButton MButton XButton2 Space Next PageDown Home Up Alt" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
  &lt;HotkeySettings Name="FormMergeConflicts"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="4" Name="ChooseBase" KeyData="B" /&gt;
      &lt;HotkeyCommand CommandCode="3" Name="ChooseLocal" KeyData="L" /&gt;
      &lt;HotkeyCommand CommandCode="2" Name="ChooseRemote" KeyData="R" /&gt;
      &lt;HotkeyCommand CommandCode="0" Name="Merge" KeyData="M" /&gt;
      &lt;HotkeyCommand CommandCode="1" Name="Rescan" KeyData="F5" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
  &lt;HotkeySettings Name="Scripts"&gt;
    &lt;Commands&gt;
      &lt;HotkeyCommand CommandCode="9000" Name="Fetch changes after commit" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="9001" Name="Update submodules after pull" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="9002" Name="Example" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="9003" Name="Open on GitHub" KeyData="None" /&gt;
      &lt;HotkeyCommand CommandCode="9004" Name="Fetch All Submodules" KeyData="None" /&gt;
    &lt;/Commands&gt;
  &lt;/HotkeySettings&gt;
&lt;/ArrayOfHotkeySettings&gt;</value>
            </setting>
            <setting name="FormBrowse_FileTreeSplitContainer_SplitterDistance"
                serializeAs="String">
                <value>301</value>
            </setting>
            <setting name="FormBrowse_DiffSplitContainer_SplitterDistance"
                serializeAs="String">
                <value>500</value>
            </setting>
        </GitUI.Properties.Settings>
    </userSettings>
</configuration>

**Comment by mgressman-marketvision** [comment]
Clearing SerializedHotkeys works.
