### ISSUE TITLE
Git Bash not opened with default rights

### ISSUE THREAD

**Issue by Janjuks** [gitextensions/gitextensions#3847]
**Do you want to request a *feature* or report a *bug*?**
Report bug
**What is the current behavior?**
Git Bash is not opened with default rights (administrator rights in my case)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Using Windows 10.
1. Set git-bash.exe to be opened with administrator right by default.
2. Open git bash from start menu and from Git Extensions
3. Instance opened from start menu will have administrator rights, second instance won't.

**What is the expected behavior?**
Git Bash is opened with default rights
**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions - 2.48.05
Git - 2.9.0.windows.1

Since Windows 10 update KB4025342, I can't complete git actions from git bash if it's not opened with administrator rights. Tested on two machines.  Error message:
```
$ git pull
FATAL ERROR: Disconnected: No supported authentication methods available (server sent: publickey)
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by vbjay** [comment]
That has nothing to do with running as administrator.

**Comment by vbjay** [comment]
http://bfy.tw/Cobs

**Comment by Janjuks** [comment]
Wow. Such humor. My keys are fine. 
Then why does it work fine while running it as administrator?
In both cases the ssh key is found and accepted, but commands like pull, fetch, etc. don't work if not ran with administrator rights. Keep in mind that this started immediately after windows update mentioned. Before that it didn't matter if it's ran as administrator or not.

**Comment by vbjay** [comment]
They changed their animation. It got a lot more snarky. I was using it so
you could replicate my search.
Check NTFS permission of your ssh utility. Whether it be putty or openssh.

**Comment by RussKie** [comment]
Have you resolved your issue?
Have you followed @vbjay's suggestions to get your issue resolved? Google has plenty of questions and answers about this problem

**Comment by Janjuks** [comment]
Problem has resolved itself. If I had to guess, it was because of Windows update I mentioned. Issue appeared right after it on multiple machines and now it's gone.
