### ISSUE TITLE
No silent install if including Git or KDiff3

### ISSUE THREAD

**Issue by ihavenoideawhatsgoingon** [gitextensions/gitextensions#3850]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Cannot silently install with Git and/or KDiff3

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In an administrative command window, run:
>GitExtensions-2.50.01-SetupComplete.msi /qn INSTALLGIT=1 INSTALLKDIFF3=1

Git Extensions installs silently, but the GUI is presented for Git and KDiff3

**What is the expected behavior?**
Silently install Git and KDiff3

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
This has never worked in any version of GitExtensions. Just tried with the latest version (2.50.01) and it still does not work.

**Comment by RussKie** [comment]
As of 2.51.02 we no longer bundle git or kdiff3
