### ISSUE TITLE
Menu to rebase interactively

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#3853]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently, the rebase context menu contains one or more sub menu items which are the branches of the current commit
![image](https://user-images.githubusercontent.com/596334/28235793-27aa8518-6948-11e7-99f3-3f99ad080985.png)

**What is the problem?**

- When rebasing, unlike merging, which branch is selected doesn't matter as long as the branches are pointing to the same commit.
- A lot of people don't know there is interactive rebase feature in GitExtensions as the option is an advanced option which is hidden by default.
- The popup dialog is not necessary, usually can be skipped.

**What is proposed?**

- Remove the branches from the sub context menu
- Add a rebase menu item (rebase straightway without the rebase dialog popup)
- Add an interactive rebase menu item(rebase straightway without the rebase dialog popup)
- Add a rebase with advanced options menu item(rebase with the rebase dialog popup)

![image](https://user-images.githubusercontent.com/596334/28239069-7bbfb568-6995-11e7-9c2a-7c9478a51cca.png)

And in the Rebase dialog, we display one of the branch name if the current commit is pointing to a branch, otherwise just commit SHA.

**Comment by RussKie** [comment]
For me personally the proposal is a significant step back in usability. I use this menu on a regular basis and I don't want to use the rebase form as it would slow me down.
So **NO** vote from me.

That said, if you want to make the interactive rebase functionality more prominent then add a separator after the list of the available branches and add the menu "Rebase interactively".
Something like:
![image](https://user-images.githubusercontent.com/4403806/28236470-b22e691c-696a-11e7-8c81-505588a020cc.png)

**Comment by EbenZhang** [comment]
Maybe what I said was not clear enough.

I am not going to change anything on the rebase form, when rebase menu is selected the rebase form will be popup with  DummyBranch as the base.

In your image, clicking the DummyBranch or the upstream/master results in the same, so why bother select one?

**Comment by RussKie** [comment]
I don't want to use the form because it takes extra time and effort. GE is built to make life simpler and requiring me to do extra steps is a move in the opposite direction

**Comment by EbenZhang** [comment]
What are the extra steps?

**Comment by RussKie** [comment]
Is opening the form not an extra step? Will it not require me to move mouse
and make at least one extra click?

**Comment by EbenZhang** [comment]
currently, you have to open the form anyway. I'm proposing to change this step.

**Comment by EbenZhang** [comment]
But I do agree with you the form is not necessary. I would propose to have three sub menu items:
 - Rebase: rebase straightway without popping up the form 
 - Rebase Interactively: rebase interactively straightway without popping up the form 
 - Advanced Rebase: after this menu clicked, we pop up the rebase form and the advanced options should be visible.

**Comment by RussKie** [comment]
Ah, I got it now, thank you.
One of the things thrown me off, I guess, was "Rebase > Rebase". It is tautological and confusing. 
Perhaps if we retained the existing wording for the top level menu and it reworded the second level, e.g. "Rebase current branch on... > Selected".
And then add "Rebase current branch on... > Selected interactively".

**Comment by pmiossec** [comment]
I think it is a good improvement. 
Indeed displaying refs names and letting the user select one make no sense because all end with the same result (and is confusing for the user because he thinks that if there is a choice, that is because that is different.) 

If I remember well, you could at the moment click directly on the menu (and not on one of the proposed branch names and it does the job...)


>Rebase Interactively: rebase interactively straightway without popping up the form

With `--autosquash` enabled? And `--autostash`?
I think it should...

**Comment by EbenZhang** [comment]
> With --autosquash enabled? And --autostash?

Yes, agree.

**Comment by EbenZhang** [comment]
We could still popup the form, but automatically click the `rebase` button.

**Comment by EbenZhang** [comment]
@RussKie in terms of the wording. I am OK with either

- Rebase
   - Rebase
   - Rebase interactively
   - Rebase with advanced options

Or 

- Rebase current branch on
   - Selected commit
   - Selected commit interactively
   - Selected commit with advanced options 

![image](https://user-images.githubusercontent.com/596334/28239069-7bbfb568-6995-11e7-9c2a-7c9478a51cca.png)

Let's wait for others' input.

**Comment by RussKie** [comment]
How about?

Rebase current branch on selected > 
   -> Go!
   -> Interactively
   -> With advanced options

**Comment by EbenZhang** [comment]
I have updated the proposal to include the skipping of the popup dialog.

in terms of the menu wording. we have three options now.

Option A
- Rebase
   - Rebase
   - Rebase interactively
   - Rebase with advanced options

Option B
- Rebase current branch on
   - Selected commit
   - Selected commit interactively
   - Selected commit with advanced options 

Option C
- Rebase current branch on selected
  - Go! 
  - Interactively
  - With advanced options

**Comment by EbenZhang** [comment]
@vbjay 

> Autosquash autostash...  I always use the dialog. I like setting up the options each time.

The `autosquash` and `autostash` are ticked by default. Once this proposal is implemented, for me I have no reason to use that dialog as the only reason I needed it was to tick the `interactive`. But it's good to have third menu item for advanced users who want to `Preserve merges` or `Specific range`.

**Comment by vbjay** [comment]
Right. I think if we do this I think we should have options for the
defaults so the user can control exactly what happens in immediate rebase.
Basically duplicate the advanced settings in the settings window. Then the
dialog would load these as well as the immediate rebase. That way the user
would expect their options to be used.

**Comment by klorinczi** [comment]
I would choose Option B, but... 

But I'm always afraid, that I click on bad menu item. 
If I click on rebase selected instead of rebase selected interactively, then there will be no confirmation dialog, and will do an accidental action, what I did not want. 

So I prefer key shortcuts. 
I would prefer key shortcut for rebase interactively (using default options, what the user did set previously). 
This way repeatedly occuring actions are highly made faster (saving at least 3 clicks and having safety).
Aggree with @vbjay 

Personally, I use a lot git fixup actions.
Submitting my fixup is very fast now with key shortcuts. 
CTRL+X, CTRL+S, ALT+O, and fixup is deployed on the server, ready for testing.

**Comment by RussKie** [comment]
Add shortcuts is a good idea.

The only difference between B and C is wording. In B case it is lots more verbose.

**Comment by klorinczi** [comment]
B wording seems to be more clear to me. 
Also in B, the text of menu level first & second is more evenly divided. 
IMHO, in C, the first level text is too long.

**Comment by jbialobr** [comment]
What about:
- Rebase current branch on here
  - Automatically
  - Interactively
  - With custom options...

Using `here` is consistent with `Reset current branch to here`, but I don't know if it is a valid use in such a context (natives - please give your opinion).
Adding `...` to the last item suggest that it will open the Rebase dialog.

**Comment by RussKie** [comment]
To me `Rebase current branch on here` sound awkward

I like the three options :+1:

**Comment by klorinczi** [comment]
Automatically sounds like it will do rebase completely automatically, including the rebase.

Personally I prefer the "selected" word, because "here"  is relative.

**Comment by jbialobr** [comment]
A
- Rebase current branch
  - Automatically on selected commit
  - Interactively on selected commit
  - With custom options...

B
- Rebase current branch
  - Automatically on `refname`
  - Interactively on `refname`
  - With custom options...

C
- Rebase current branch on selected commit
  - Automatically
  - Interactively
  - With custom options...

**Comment by vbjay** [comment]
A

**Comment by RussKie** [comment]
I'm fine with A, though options look long

**Comment by paulroho** [comment]
I vote for C.

**ad A**:  
Mentioning "selected commit" sounds superfluous to me as we are already in a context menu and the context is exactly the selected commit.

**ad B**:  
Mentioning the `refname` is IMHO confusing. Seeing this would make me double check if it's correct, what shouldn't be necessary.
