### ISSUE TITLE
Avatar different size - is it useful?

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#3854]
Going through the code I found that there is a whole avatar context menu and it is possible to change the avatar size...

![image](https://user-images.githubusercontent.com/4403806/28239233-9032d70e-69aa-11e7-8bf1-444f4ee0eafd.png)

I am genuinely curious - does anyone use non-default avatar size?
I like avatar feature, but I couldn't think of a reason why I would want someone else's avatar take valuable space on my screen...

The reason I ask - I am tinkering with possible UI uplift of the commit details panel and the avatar size functionality is something I would deprecate and remove.

**Comment by EbenZhang** [comment]
FYI: I'm using the default size and never changed the image size.

**Comment by pmiossec** [comment]
I don't find it useful, too. 
Perhaps to reduce the size it would have been useful by the proposed sized are only to display it too big...

**Comment by jrfnl** [comment]
Same here. I use the default `small` size and never felt the need for the avatar to be bigger than that.

**Comment by RussKie** [comment]
Thank you for the feedback.
