### ISSUE TITLE
GitExtensions 2.50.01 gives System.NullReferenceException at start

### ISSUE THREAD

**Issue by TutConner** [gitextensions/gitextensions#3855]
**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**

The problem I have is somewhat similar to closed issue 3806, but it is happening to me with GitExtensions version 2.50.01 which fixed 3806.

Every time I start GitExtensions, I get the System.NullReferenceException error shown in the attached screen captures. This error only allows me to Quit or Quit and Send (which I have done), so I can't use GitExtensions unless I downgrade to 2.49.03.

![gitextensions error](https://user-images.githubusercontent.com/30197108/28239589-8501de92-693d-11e7-83ce-b4d1f5e96b4b.png)

![gitextensions error 2](https://user-images.githubusercontent.com/30197108/28239601-d8447f2e-693d-11e7-9bf2-0a2a42a661ba.png)

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**

GitExtensions version 2.50.01; GIT version 2.13.2 and 2.13.3 (the only ones I have tried); Windows 10; Visual Studio 2017 (if that matters).

This started happening when I upgraded GitExtensions to version 2.50.01. It did not happen with version 2.49.03. If I uninstall 2.50.01 and install 2.49.03, everything works fine. If I then upgrade to 2.50.01, the problem returns.

**Comment by RussKie** [comment]
Please post the full stack trace

**Comment by TutConner** [comment]
How do I create a stack trace?

FYI, the problem occurs immediately on program start, before showing the user interface.

**Comment by RussKie** [comment]
The stack trace can be copied form "Stack trace" field (2nd from the bottom on your screenshot)

**Comment by RussKie** [comment]
Have you had any previous versions installed or it is a brand new fresh install of GE?

**Comment by RussKie** [comment]
@TutConner try deleting `SerializedHotkeys` value from your config file and see if it helps.
https://github.com/gitextensions/gitextensions/issues/3845#issuecomment-315344116
https://github.com/gitextensions/gitextensions/issues/3845#issuecomment-316392650

**Comment by TutConner** [comment]
I previously had version 2.49.03, which worked fine.

I'm not sure what file is supposed to contain SerializedHotkeys. I did not see it in my user.config file or in GitExtensions.exe.config.

The Stack Trace is:
   at GitUI.Hotkey.HotkeySettingsManager.AssignKotkeysFromLoaded(Dictionary`2 defaultCommands, HotkeySettings[] loadedSettings)
   at GitUI.Hotkey.HotkeySettingsManager.LoadSettings()
   at GitUI.Hotkey.HotkeySettingsManager.LoadHotkeys(String name)
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands aCommands, String filter)
   at GitUI.CommandsDialogs.FormBrowse..ctor(GitUICommands aCommands, String filter, String selectCommit)
   at GitUI.GitUICommands.StartBrowseDialog(IWin32Window owner, String filter, String selectedCommit)
   at GitUI.GitUICommands.StartBrowseDialog()
   at GitExtensions.Program.Main()

**Comment by RussKie** [comment]
@TutConner does it happen when you are opening via the shortcut (i.e. not opening a particular repository) or for a specific repository?

**Comment by TutConner** [comment]
I was able to get it working by uninstalling GitExtensions, deleting the GitExtensions folders in AppData\Local and AppData\Roaming, installing GitExtensions 2.50.01, and configuring GitExtensions the way it was before.

**Comment by RussKie** [comment]
Good to know you got it sorted.
Pity we could not learn and fix the cause of the problem.
