### ISSUE TITLE
Issue with install from command line

### ISSUE THREAD

**Issue by pgilmorepf** [gitextensions/gitextensions#3857]
Feature Request

I am using GitExtensions-2.50.01-Setup.msi installer.
I want to write a script to install to many machines via command line.
Adding "/passive" does the expected thing, as that's part of the MSI specification.
I have found that adding "SSHClient=asdf" will cause the installer to de-select PuTTY as the default option for SSH Client in the installer, but I cannot find the right value for "asdf" to make it default to OpenSSH.  As a consequence, I can't make the silent command line install using OpenSSH.

Repro:
Contrast the installer steps when run from the command line with different command line inputs:
1) GitExtensions-2.50.01-Setup.msi SSHClient=asdf
vs
2) GitExtensions-2.50.01-Setup.msi

1 will have neither OpenSSH nor PuTTY selected in the "Select SSH Client" (the installer allows you to proceed with no selection)
2 is the default behavior which selects PuTTY by default.
(I cannot figure out the correct value for "asdf" to make it select OpenSSH)
(I have attempted: ssh, openssh, OpenSSH, 0, 1)

Please reply with the correct value of "asdf" which makes the installer default to OpenSSH, and/or add an option to the installer which parses the SSHClient=_ parameter, and parses obvious values to select/use OpenSSH. Also, selecting one of those two options should be mandatory, and the installer shouldn't proceed if they're both unset.

I've only tested this with the latest installer.

**Comment by jbialobr** [comment]
`GitExtensions-2.50.01-Setup.msi SSHCLIENT="OpenSSH"` does the job.

**Comment by RussKie** [comment]
@pgilmorepf has your issue been resolved?

**Comment by RussKie** [comment]
This may also come handy https://github.com/gitextensions/gitextensions/issues/2939#issuecomment-282445872.

Closing now.
