### ISSUE TITLE
Push to remote keep asking me to add tracking reference

### ISSUE THREAD

**Issue by nicofari** [gitextensions/gitextensions#3858]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
when pushing a local branch to a remote it asks me to add a "tracking reference"
I answer "yes" but it does not store my answer

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
it should save the tracking reference and don't ask anymore

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
the problem appeared to me at the first push after installing the 2.50.01 version of GitExtensions, on Windows 10 Pro

**Comment by numaroth** [comment]
The same thing is happening with me except it started when I installed GitExtensions 2.50 and I'm using Windows 7 Enterprise.

**Comment by jbialobr** [comment]
Can not reproduce it. Does it happen for a regular repository or for a submodule or working tree?
What is your git version?

**Comment by numaroth** [comment]
It was happening on a regular repository. I was using Git version 1.8.3. 
Upgrading to Git 2.14.0 seems to have fixed the issue.

**Comment by RussKie** [comment]
Good to hear the problem is fixed.
Please re-open or raise a new issue if issue re-occur.

**Comment by loop-evgeny** [comment]
I keep getting this prompt using Git Extensions 2.50.02, git 2.15.0.windows.1 on Windows 7 Pro N SP1.

**Comment by RussKie** [comment]
You can turn the confirmations off
![image](https://user-images.githubusercontent.com/4403806/33714934-ef673fd2-dba4-11e7-885b-cbdee537ed55.png)

**Comment by loop-evgeny** [comment]
That works, thanks a lot! I didn't find that option under "Advanced". It would be great if the dialog itself provided that option, e.g. had a checkbox like "Remember my choice and don't ask again" or the buttons could be "Yes", "No", "Always", "Never" - whatever is easier.

**Comment by RussKie** [comment]
A PR is welcome :)
