### ISSUE TITLE
Text strings for `.git/info/exclude` modals need adjusting

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#3860]
Related to PR #3260 / GitExtensions 2.50.0+.

Love the fact that I can now edit the `.git/info/exclude` file straight from the GitExtensions interface.

While using it, I ran into two minor usability issues which are cause for confusion:
* The links in the `Edit .git/info/exclude` modal refer to `gitignore` not to the `exclude` file:
* Similarly, the `Save changes?` modal which sometimes pops up, also refers to `.gitignore` not `.git/info/exclude` which is misleading.

![screenshot](https://snag.gy/4HEszy.jpg)

**Comment by Drake103** [comment]
I have some questions.
1. What links are expected?
2. Should `Add default ignores` and `Specify file patterns you want git to ignore` also be changed?
3. Same behavior is for `Add pattern` dialog, do you want it to be changed also?

**Comment by vbjay** [comment]
So that file is the same thing as .gitignore.  The only difference is that
it is local to the current repo and will not travel, nor will it be
committed.  It is a .gitignore file.

**Comment by jrfnl** [comment]
> What links are expected?

I have no opinion on that. For all I know, the links could stay the same and only the link text might need adjusting and could possibly be made slightly more generic so it can be used in both dialogs.

> Should Add default ignores and Specify file patterns you want git to ignore also be changed?

In my opinion "Add default ignores" and "Specify file patterns you want git to ignore" are both fine.

> Same behavior is for Add pattern dialog, do you want it to be changed also?

Again, in my opinion, I see nothing in that dialog which needs changing.


The issue is just when there is a text string referring directly to `(.)gitignore` as that causes confusion over which file is being edited.

> So that file is the same thing as .gitignore.

I agree that both files do essentially the same in a different matter, and that makes it all the more relevant to make sure you're editing/saving the correct file.

**Comment by jbialobr** [comment]
To sum it up, we need to change:
1. Save confirmation dialog: Save changes to .gitignore? -> Save changes to .git/info/exclude? (depending on edited file)
And optionally (as the existing naming is consistent with the git documentation https://git-scm.com/docs/gitignore):
2. Link: Generate a custom gitignore -> Generate a custom ignores/ignoring file
3. LInk: More gitignore patterns -> More ignores/ignoring patterns

**Comment by jbialobr** [comment]
@Drake103 Thanks for the PR. 
By writing `ignores/ignoring` I meant to chose one: either `ignores` or `ignoring` - I am sorry I forgot to write it explicitly. Can any native English speaker help with this decision? 
/cc @vbjay

**Comment by jrfnl** [comment]
I'm not a native English speaker either, but have lived there.
To be grammatically correct I'd say:
2. `Generate a custom ignore file` and if there would be enough space: `Generate a custom ignore file for git`
3. `More ignore patterns` or maybe even better: `Example ignore patterns`
