### ISSUE TITLE
Remote repositories modal defaults to inactive repo

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#3861]
**Do you want to request a *feature* or report a *bug*?**
Bug related to the awesome new "inactive remotes" feature (I love it!). See #3615

**What is the current behavior?**
Given a repository with multiple remotes, some of which are disabled, when you open the `Remote repositories` window, it automatically selects the first remote based on alphabetical order - independently or whether this remote is active or disabled.

**What is the expected behavior?**
That the selected repository would be the first alphabetically of the `Active` repository list.

**Steps to reproduce the problem.**
* Repository -> Manage Remotes
* Add a couple of remotes to a repository.
* Disable the one which is alphabetically first in the list
* Close the window
* Repository -> Manage Remotes
* See the disabled repository being selected

![screenshot](https://snag.gy/LlrjEp.jpg)

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
V 2.50.01 on Windows 7

**Comment by jbialobr** [comment]
Should not we prefer `origin` if present and active?

**Comment by jrfnl** [comment]
> Should not we prefer origin if present and active?

I'd be perfectly fine with that too. The main point here is that it should always be a repository on the `active` list, never on the `disabled` list.

**Comment by jrfnl** [comment]
Thanks @RussKie !
