### ISSUE TITLE
Apply patch / Select patch file should filter for lowercase *.patch

### ISSUE THREAD

**Issue by rgl** [gitextensions/gitextensions#3867]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/43356/28493665-7460f0d4-6f12-11e7-866e-56335b3f30b8.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. open a repository
1. select the `Commands` menu then `Apply patch...`
1. see that the filter is `*.Patch` and it should be a lowercase `*.patch`

**What is the expected behavior?**
filter should be a lowercase `*.patch` by default.

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
Git Extensions 2.50.01 running on Ubuntu 17.04

**Comment by pmiossec** [comment]
Thanks for head up.

That's a very simple bug to fix. Perhaps you could take 5 minutes to create the pull request fixing it. 
The fix should be made in this file:

https://github.com/gitextensions/gitextensions/blob/2d15fc1a68f999d56f08326e759becb35fdbb1f9/GitUI/CommandsDialogs/FormApplyPatch.cs

**Comment by rgl** [comment]
@pmiossec should I also modify all the UI translations?

**Comment by RussKie** [comment]
Generally translations are done via the translation app.
In this case you can probably do "find/replace" with match case/whole word since `(*.Patch)` string is unique and language agnostic.
@jbialobr what do you think?

**Comment by pmiossec** [comment]
In fact, the translation is now made through the transiflex website, so there is no way to update all the translations easily. 

So, for me, that's OK for now. 
You did a great job.

**Comment by jbialobr** [comment]
If we want to include this fix in 2.50.02 then the translation should be updated manually in the 2.50 branch. But ideally the extension should not be a part of the translation string.
