### ISSUE TITLE
The submodule url / password won't update if you change your branch

### ISSUE THREAD

**Issue by ghost** [gitextensions/gitextensions#3872]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

currently, if you have a remote submodule in a repository with a different password per branch, gitextensions will still use the password / path from master (in the form it's correctly displayed, but git receives a wrong command)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

create one repo with a remote submodule
the submodule must be only accessable with a password
change the password of the remote submodule
create a branch and change the password to the new password of the submodule

clone the repo
switch to the branch with the right password
try to update the submodule

**What is the expected behavior?**

gitextensions should give git the correct password to use (the one from the branch you did checkout)

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**

win 10
2.50.01 and 2.50.00 are affected

**Comment by jbialobr** [comment]
Where the password is being stored?

**Comment by miterosan** [comment]
The password is in the url string in the .gitmodules file
example:

[submodule "somesubmodule"]
	path = somesubmodule
	url = https://miterosanGuest:crazyPASSWORrD@bitbucket.org/miterosan/somesubmodule.git

**Comment by SoerenDaenekas** [comment]
can somebody confirm this?

**Comment by RussKie** [comment]
@SoerenDaenekas what sort of confirmation are you looking for?
