### ISSUE TITLE
File tree no longer working

### ISSUE THREAD

**Issue by srudin** [gitextensions/gitextensions#3875]
Bug: Using the latest version 2.50.01 I cannot display the file tree anymore. Tried with several repos and always get a blank area when switching the tab.

**Comment by MarkJ74** [comment]
I get this too with 2.50.01 on Windows 10.

**Comment by pmiossec** [comment]
What is the problem exactly? Could you provide a screenshot? 

I also have the last version in Windows 10 and I don't have this problem... 

The only not optimal behavior is that the directory file tree has sometimes a very small width and resizing it solve the problem...

**Comment by MarkJ74** [comment]
Ah you're right I didn't realise that - the problem is the tree control on the left has zero width, I resized it and now it's remembered the width and I can see the file tree on the left. This hasn't happened before with previous versions, I've only noticed it with 2.50.01.

**Comment by RussKie** [comment]
I think it relates to https://github.com/gitextensions/gitextensions/pull/3681

**Comment by pantosh** [comment]
I had the same problem (running Win 7). A minimum width on the file tree panel large enough to always show at least part of the tree should solve this.

**Comment by RussKie** [comment]
The width of the file tree is persisted in user.config.
But user.config is created under C:\Users\<user>\AppData\Local\GitExtensions\ path in generated folders like 'GitExtensions.vshost.exe_Url_en4rgprd4qxsucpiokiljkbzgdtmkj5l'
I think the folder gets generated for each new version and the settings get reset...

I wonder whether user.config should be stored under C:\Users\<user>\AppData\Roaming\GitExtensions\GitExtensions\ so the settings are carried over from one version to the next

**Comment by vbjay** [comment]
That's not how settings should be upgraded.  What you do is add a
NeedsUpgrade setting that is set to true in the designer.  When an upgrade
is required call the settings.upgrade method and then set the setting to
false.


If(settings.NeedsUpgrade)

{
settings.Upgrade();
settings.NeedsUpgrade=false;
settings.Save();

}
