### ISSUE TITLE
Tools -> Git Bash opens bash in home directory instead of the current directory

### ISSUE THREAD

**Issue by shankarswamy** [gitextensions/gitextensions#3876]
From Tools --> Git Bash or Control-G open the Bash window and I get the home directory.  Not the current directory that the repository is open in.

The installation is set to fork the cygwin bash.

I am ALMOST certain this was not the case before my upgrade to 2.50.01 two days ago. 
Is there anything I can do to have the shell automatically switch to the repository directory.

Thanks for your time.

Cheers; 'best,
shankar swamy

**Comment by RussKie** [comment]
Does it happen for all repos or for a specific repo only?

**Comment by shankarswamy** [comment]
It happens on all repositories.
Thanks!

**Comment by jbialobr** [comment]
I can not reproduce it. It can be sth specific to your configuration. Here is the method that runs bash: https://github.com/gitextensions/gitextensions/blob/0df679e39be79d325b7781ad7f28dd9b3c88b02c/GitCommands/Git/GitModule.cs#L1062
Maybe it will help you to find the cause.

**Comment by shankarswamy** [comment]
So far I have established that it is not any of my bash settings.  I am now looking at the code at the above link - hopefully, it will give some clue.

Is there a way I can force the Extensions to open its version of bash rather than the cygwin version?
Thanks!
