### ISSUE TITLE
Missing Newtonsoft.Json on startup exception

### ISSUE THREAD

**Issue by ardonjr** [gitextensions/gitextensions#3879]
![gitext_error](https://user-images.githubusercontent.com/3910372/28814930-d622100c-769f-11e7-9078-dbe877b9c836.png)
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
On startup I get the exception that Newtonsoft.Json is missing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just open GitExtensions. Version 2.50.01

**What is the expected behavior?**

**Which versions of GitExtensions, GIT and Windows are affected by this issue? Did this work in previous versions of our tool?**
GitExtensions: 2.50.01
GIT: git version 2.13.1.windows.1
Windows 10 Pro - 10.0.15063 Build 15063

**Comment by RussKie** [comment]
Can you please check the content of your Plugins folder (usually something like `C:\Program Files (x86)\GitExtensions\Plugins`) - Newtonsoft.Json.dll should be there. 
The version shipped with GE 2.50.01 is **10.0.2.20802**

In GitExtensions.exe.config you should also have the following:

```
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <probing privatePath="plugins" />
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by ardonjr** [comment]
Thanks for the fast reply. I found the settings as mentioned to be correct however I do not have the Newtonsoft.Json.dll in the Plugins folder.
![gitext_error_002](https://user-images.githubusercontent.com/3910372/28823290-1ea0c5d6-76bd-11e7-9a04-253ecb17874e.png)

**Comment by ardonjr** [comment]
Nice. I "fixed" the issue by pulling a Newtonsoft.Json nuget package into an existing project and copied the DLL file into the _C:\Program Files (x86)\GitExtensions\Plugins_ folder.
For now the exception is gone. But its strange that the dll isn't in place in the first place right?

**Comment by jbialobr** [comment]
Newtonsoft is only installed when either AppVeyorIntegration or Gerrit plugin is installed. We have to fix setup and include it also for the Stash plugin (and check if any other plugin requires Newtonsoft).
