### ISSUE TITLE
Feature Req.: Commit button should indicate if file in repos. changed

### ISSUE THREAD

**Issue by butscher** [gitextensions/gitextensions#3887]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If there are files in working copy which are not in repository (untracked) and no change in index, the commit button is orange regardless if a tracked file was changed or not.

**What is the expected behavior?**

The commit button (or alternatively the stash button) should look differently if no tracked file is modified compared to if tracked files are modified. This is helpful to know if checking out a different branch or hard resetting current branch to a particular commit can be done without hassle and loosing changes in the working copy.

**Which versions of GitExtensions, GIT and Windows are affected by this issue?**

GitExtensions 2.50.01

**Comment by vbjay** [comment]
I suggest updating the documentation with what each color means, and adding configuration settings for user to specify each color.

**Comment by jbialobr** [comment]
> I suggest updating the documentation with what each color means

Yes, we should do that.

>and adding configuration settings for user to specify each color.

I think it will unnecessarily overload the settings.

**Comment by RussKie** [comment]
I agree, there are already way too many settings which are hidden away and unlikely to be modified by the vast majority of users
