### ISSUE TITLE
Make "Prune remote branches" option on Pull dialog "sticky".

### ISSUE THREAD

**Issue by yusirui** [gitextensions/gitextensions#3891]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
An option was added to the 2.50.01 Pull dialog to "Prune remote branches". If set to "checked", it is reset to unchecked after the pull or fetch.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
 Please make it a persistent setting, like the Merge options, or add a sub-option to make it persistent.

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by vbjay** [comment]
Bad idea. I wouldn't want this. It's a destructive action. It should be
opted in.

**Comment by moshesafran** [comment]
Maybe then add an option to make "Prune" sticky in the "Settings->Advanced" dialog?

**Comment by DaveWut** [comment]
Yes please, add this feature. Like @moshesafran said, add an advanced option to allow the user to make it "sticky".

**Comment by RussKie** [comment]
As @vbjay said enabling this feature may serious consequences.
When a user types a git command they are (significantly more) explicit about requested operations. However when those commands are abstracted by a UI away from the user, these command become part of the "black box".

Imagine the settings gets sets and the user is unaware or forgets about it, and then loses his/her work.
That is not the risk we are willing to accept.

If you indeed need this feature, write a custom script (Settings > Scripts) and hook it up to `AfterPull` event (or `AfterFetch` once #4909 gets implemented) and run the prune command.
