### ISSUE TITLE
On "Commit dialog" configuration page, raise the "previous messages" limit

### ISSUE THREAD

**Issue by yusirui** [gitextensions/gitextensions#3892]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
On "Commit dialog" configuration page, the number of "previous messages in commit dialog" is limited to 10. For people working on a number of projects in shared repositories, this low number is hardly useful.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Please raise the limit to at least 100. Additionally, make the "Commit message" drop-down that lists the messages (on the Commit dialog) scrollable.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.3
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by yusirui** [comment]
If you are able to implement this request, consider adding a filter option to the message list that will list only messages containing a user-supplied text string.

**Comment by jrfnl** [comment]
Nice one! A welcome surprise in the new version.
