### ISSUE TITLE
windows 10 start menu shortcut stopped working 2.5.01

### ISSUE THREAD

**Issue by erikleo** [gitextensions/gitextensions#3895]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
After installing 2.5.01 on both my desktop win 10 machine and laptop win 10 machine i see that the start menu icon does not launch the program.  both machines have the creators update installed.

to reproduce
install on win 10 machine
in start menu type GIT, then click on the Git Extensions icon --> the program does not launch, nothing happens after repeated clicks.

I did not have this problem on my win 7 machine

**Comment by RussKie** [comment]
Can you please check what path the shortcut points to and whether the path exist
Thank you

**Comment by erikleo** [comment]
Its very odd, I can't right click on it either to get this info.  Also i can't find the shortcut in either of the below locations:

%ProgramData%\Microsoft\Windows\Start Menu\Programs
%AppData%\Microsoft\Windows\Start Menu\Programs

it seems almost as if the install process deleted the shortcut but something was left in the windows 10 search cache.  As i said before the exact same thing happened on both my win 10 machines.

**Comment by RussKie** [comment]
Which of the msi did you install - the minimal or the complete one?
Did you have any of the previous versions installed?

**Comment by erikleo** [comment]
had previous version installed (2.50)
installed using complete, 
left Kdiff, GIT unchecked

**Comment by RussKie** [comment]
I've tried it on my W10 installation having completely uninstalled the existing git and GE.
All worked fine....

Are you full administrator on both your devices?

Can you provide a log from an installation process invoked like that:
`msiexec /i GitExtensions-2.50.01-SetupComplete.msi /l*v MyLogFile.txt`

**Comment by erikleo** [comment]
It looks like the root cause of this issue has to do with windows privacy settings and is affecting other applications as well.  Closing because it does seem to be git extensions specific.
