### ISSUE TITLE
Bug gitext 2.50.01: File tree tab is entirely blank.

### ISSUE THREAD

**Issue by eyng** [gitextensions/gitextensions#3903]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
File tree tab is entirely blank.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Start or restart Git Extensions > go to any branch or commit > File tree tab is entirely empty.
The other 3 tabs work fine: Commt, Diff, Console.

**What is the expected behavior?**
I normally see all files here.

**Environment you encounter the issue:**
Windows 10.

- GitExtensions version:
- GIT version: git version 2.7.1.windows.1
- OS version: Windows 10 with latest updates.

**Did this work in previous version of GitExtensions (which)?**
It did work recently. I am not sure since when it doesn't work, nor when was the last GitExt update.

**Comment by RussKie** [comment]
Please search next time, there is an existing issue opened for this problem - https://github.com/gitextensions/gitextensions/issues/3875.

The file tree is somehow gets set to 0 width, you can resize it back.

**Comment by eyng** [comment]
Search first: I will do that.
Resize: i've done that, it works fine now, thanks.

**Comment by RussKie** [comment]
Good stuff
