### ISSUE TITLE
Feature request: Add option to choose branch name ordering preference

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#3907]
Issue #2455 / PR #3413 introduced ordering the branch drop-down menu by "recent use".

At the time, the question was raised whether the order of the drop-down should be configurable.

My feature request is: Yes, please add this as the current ordering is seriously hampering my productivity.

From [my earlier feedback in the original issue](https://github.com/gitextensions/gitextensions/issues/2455#issuecomment-320447539):

> Ok, here's that someone that needs alphabetic order or at least any form of logical ordering.
> Given that there are projects where I have over 50 active branches being worked on, I'm having a lot of trouble findings some of the branches I'm looking for - or rather I can't effing find anything at all anymore except for recent branches....
>
> Alternatively, a way to fold out based on the branch names would be helpful as well.
>
> As an example of what I mean by that, for certain projects, there are a couple of different forks I contribute to, so I generally prefix a branch with the fork name:
>
>   * forkA/feature/feature-name
>   * forkB/feature/feature-name
>
> And I often add /PR/ to the branch name to know which branches have been pulled and which are still WIP.
>
> So collecting all branches with a certain prefix and showing those as a sub-menu of the branch pull-down, could be helpful too.

Just to give you some idea, this is an example in one of the repos I work on - note the arrow at the bottom, not even all branches can display in the current dropdown:
![ge screenshot](https://user-images.githubusercontent.com/663378/29341498-ee5e208a-8224-11e7-84bf-996d3cbbfe07.png)

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version:  2.14.1.windows,1
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**

Well, alphabetic ordering which was available pre-2.50 at least made it slightly easier for me to find things :wink:

**Comment by pmiossec** [comment]
Even if this bug must be tackled, I'm pretty sure that you've got a problem in your development workflow... 

If you have so much local branches (and that you have deleted and pruned merged ones), you have too much work not delivered and **a lot** of value wasted. 

And how do you manage cognitively to work on so many branches? 

Surely that you will have a lot of benefits to use 'trunk base development' and 'feature toggle/flipping'. Or at least short life branches.

**Comment by pmiossec** [comment]
If I show your screenshot to a colleague, he will jump accross the windows 😅

**Comment by jrfnl** [comment]
> Even if this bug must be tackled, I'm pretty sure that you've got a problem in your development workflow...

I work on a lot of open source projects and as nearly all of them are volunteer based, getting things merged is often a slow process.

* About one third of the branches you see are open PRs.
* There are a number of branches with a "WAIT" status. Either because they are waiting for an open PR in the repo to be merged first as the changes build onto each other (or would conflict) or because they are waiting for an open PR in a vendor/upstream project to be merged.
    I find it easier to create the branch when I've done the work for upstream and the impact on the downstream project is fresh in my mind, than to leave that until the upstream PR has been merged - which may take several months.
* There are a number of branches for open issues where I've been testing things and either couldn't reproduce the issue or need more info. In that case, those are waiting on the OP to respond. I commit the test code I've used in a separate branch so I can continue when they do. Those branches either get turned into a PR at some point or deleted after a while (when the issue is closed/turns out not to be an issue/etc).
* There are a couple of branches where I've been testing open PRs from other contributors adding extra unit tests and such. I leave feedback in the PR for them, but want to keep my own test code somewhere to make sure it is included in the PR if/when the OP updates it. So another type of branch "waiting" for something. These get deleted once the PR has been updated and contains sufficient unit tests covering what I pointed out.
* And then there are some work in progress branches of course. Sometimes a few for the same issue, trying different approaches. Once I've decided which one is best, I turn that into a PR and remove the other branches.

> If you have so much local branches (and that you have deleted and pruned merged ones)

The list does not contain any merged branches (yes, I prune/delete those).

> you have too much work not delivered and a lot of value wasted.

While the process is sometimes slow, over 90% of my PRs get merged, so no, I don't think I'm wasting my time :wink: 

> And how do you manage cognitively to work on so many branches?

By being highly organized. As I mentioned in the original topic, I prefix branches based on status and on the fork for which the work is being done.


> Surely that you will have a lot of benefits to use 'trunk base development' and 'feature toggle/flipping'. Or at least short life branches.

I branch a lot to keep PRs as small as possible and contained to solving one issue and solving it well.
My workflow is actually very close to what you call "trunk base development"/ "GitHub flow". Branches are intended to be short-lived and most are - one of the forks for this project generally merges within 24 hours, the other fork I work on has had a merge hiatus for the last 5 months... which explains the amount of open PR branches.

**Comment by pmiossec** [comment]
@jrfnl I understand your point of view because indeed, merging some PR in an open source project takes more time than in a enterprise project. 

But reading all that, I really think that you deserve a lot of kudos! :fireworks:

**Comment by jrfnl** [comment]
@pmiossec :blush: Appreciated!

**Comment by pmiossec** [comment]
I hoped to help and tried to give some hints but not needed 😉

**Comment by laurin1** [comment]
+1

Our branches are prefixed by Ticket #'s, so we look for them by number, not by name, since everything we work is by Ticket. I have about 30+ open right now in this repo. I was shocked to find them no longer alpha in this version!  👎

**Comment by Gua-naiko-che** [comment]
Hi,

I've never contributed to an open source project and I think this small feature is a good way to start. However, I have one general question and two specific ones:

- GENERAL: How can I know if somebody is already working on this (or other) issue? Do I have to assign the issue to myself if I intend to implement it?
- SPECIFIC 1: Where should I create the option to order the branches alphabetically? I think that it should be a checkbox in Settings>GitExtensions, inside the "Behaviour" group. What do you think?
![imagen](https://user-images.githubusercontent.com/6260564/32352458-999d580a-c021-11e7-8154-388c25b6ebba.png)
- SPECIFIC 2: How does the translation work? Do I have to create an empty block corresponding to the checkbox text in each *.xlf file? Is this done automatically by some tool?

**Comment by pmiossec** [comment]
>I've never contributed to an open source project and I think this small feature is a good way to start. 

Great! 👍 

>GENERAL: How can I know if somebody is already working on this (or other) issue?

There is **no absolute rule**.
Most of the time, a message, like you just did is enough. If someone is interested by this issue/feature, he will read the thread and see your message.

You could also quickly open a pull request (with some progress) mentionning this issue.
You just have to prefix the title with "[WIP]" if that's a work in progress.
That way, you could:

* gather some feedback
* show the progress
* show that you are working on it

>Do I have to assign the issue to myself if I intend to implement it?

Only the maintainer of the project could assign issue to someone. You could ask to do it but that's not the usual practice...

>SPECIFIC 1: Where should I create the option to order the branches alphabetically? I think that it should be a checkbox in Settings>GitExtensions, inside the "Behaviour" group. What do you think?

Maybe. But if you do it here, don't put it in the right free place. Add another line, there is some place.

Another solution could be in the the "View" Menu of the browser form. Something like 
"Sort branch by:"
   ->Date
   ->Name (alphabetically)

We will wait the point of view of others...


>SPECIFIC 2: How does the translation work? Do I have to create an empty block corresponding to the checkbox text in each *.xlf file? Is this done automatically by some tool?

There is no need to add the block for most of the graphical controls. They will be added automatically.
You only have to use `TranslationString` for string that should be translated but that are use in the source code ( for example: https://github.com/gitextensions/gitextensions/blob/2d15fc1a68f999d56f08326e759becb35fdbb1f9/GitUI/CommandsDialogs/FormInit.cs )

Happy coding!!!

**Comment by RussKie** [comment]
> Do I have to assign the issue to myself if I intend to implement it?

An issue can be assigned only to a member/collaborator or the original author of the issue. So if you raise an issue you can assign it to yourself.
But like @pmiossec said it is not a requirement. Just open a PR and everyone will know that someone is working on this.

> I think that it should be a checkbox in Settings>GitExtensions, inside the "Behaviour" group. What do you think?

I don't think "GitExtensions" tab is appropriate for this configuration. It is neither a performance- or behaviour-related.
Is is probably more appearance-related, but the "Appearance" tab looks pretty full as is.
So I am leaning towards creating a new tab under "Detailed" node. Not quite how to best call it though... "Branch settings" maybe?

**Comment by Gua-naiko-che** [comment]
Hi!

Thanks a lot for your responses!

The discussion about where to place this configuration brought to me another two related questions: 
1. How should I let the community share their views about how to implement a feature? Should I ask upfront for opinions in a message? Should I try to make a prototype in a Pull Request?
2. If there are several opinions, how does the community pick one of them? Is it up to me? Do we vote?
Maybe there are no general guidelines or "it depends" but I would like to 

For the current feature, I prefer the idea of placing the configuration in a new node under "Detailed". It could maybe be called "Toolbar settings". What do you think?

**Comment by RussKie** [comment]
> How should I let the community share their views about how to implement a feature? 

You open an issue where you discuss your proposal. Everyone then has a chance to chime in. 
You may also not get any feedback, in which case you assume that it is what people want or do not care. So you go and implement your proposal.
This a second round for people to express their opinions.
And once the new functionality is merged in and published it will likely to generate the most feedback, if at all. The feedback would generally be in a form of bug reports :) ...but you may receive some kudos as well.

> If there are several opinions, how does the community pick one of them? 

That's a tricky question. If a proposal were to generate an upheaval in the community than it is definitely a no go (like proposing to rewrite everything in VB). If there are opinions that something could/should be done differently than it is up to you to engage with the community and work out the best solution.
And, of course, members of the core team have the final say in everything.

If you want to make your PRs go faster make sure your implementations are SOLID and tested. :)

**Comment by jrfnl** [comment]
Thank you all for making this happen. Happy to say I can find branches again now 2.51 is out ;-)
