### ISSUE TITLE
Bug: Recent repositories settings / max number not respected

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#3908]
**What is the current behavior?**

Bug report: when setting the _"Maximum number of most recent repositories"_ to a high number, that number is not respected. Instead a maximum of 30 (?) repositories are remembered.

![ge screenshot recent repos](https://user-images.githubusercontent.com/663378/29341856-6882498e-8227-11e7-838b-d9cb86dc9c56.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* Open the repository dropdown and click on "Configure this menu"
* Set the max number of recent repos to 100
* Open a number of repos to make sure you go over thirty recently opened repos.

**What is the expected behavior?**

That the number would be respected.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 2.14.1.windows,1
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**
No, the bug has been around for as long as I remember.

Loosely related to #3769 / #3780

**Comment by RussKie** [comment]
Do you actually have more than 30 repositories in your history?

This value controls how many repositories are kept and persisted in the config. If you change the value you won't see any more repositories unless you accumulate them in your history.

**Comment by jrfnl** [comment]
> Do you actually have more than 30 repositories in your history?

Well, yes and no.
Yes: I have opened/used well over thirty repositories.
No: by all appearances GitExtensions does not save more than thirty in the history and removes older repos when adding a new one or something of the kind as it is not displaying them.

Could it be that this number is somehow tied to the Windows native "max recent documents" setting used for the jumplists in the taskbar instead of being native to GitExtensions ?

**Comment by vbjay** [comment]
The jumplists and the mru in the app are separate things.

**Comment by jrfnl** [comment]
> The jumplists and the mru in the app are separate things.

Good to know. It was just a thought as my max there is 30 and the 30 cut-off seemed so arbitrary that I thought it might be related.

**Comment by RussKie** [comment]
We'll need to investigate it

**Comment by jrfnl** [comment]
@RussKie That would be much appreciated. Please let me know if you need more info from me at some point.

**Comment by RussKie** [comment]
In the current implementation the repository history size and the maximum number of recent repositories (highlighted in red) are two different settings.
The former can't be set anywhere in the UI, and the latter can be set but does not control anything...

I have a rough working prototype, I will publish it once it is finalised.

**Comment by jrfnl** [comment]
@RussKie Thanks for working on this and the update! Let me know if there's anything I can do to help.

**Comment by jbialobr** [comment]
>and the latter can be set but does not control anything...

It controls how many repositories at most can be shown as the most recent repositories, the other repos as categorized as the less recent repos. They are separated by a ToolStripSeparator

**Comment by jrfnl** [comment]
Very happy to see this feature now working in 2.51 ! Kudos for getting it sorted.
