### ISSUE TITLE
Fatal error on fetch or pull after upgrade to 2.50.01

### ISSUE THREAD

**Issue by kmilos** [gitextensions/gitextensions#3911]
**Bug**

**What is the current behavior?**

When clicking "Fetch all", the following is displayed in the dialog window:

```
"git" fetch --progress "--all"
fatal: fetch --all does not take a repository argument
```

On "Fetch" or "Pull - merge" I get asked for OpenSSH authentication, but still fails:

```
"git" pull --progress "origin"
Enter passphrase for key...
fatal: Couldn't find remote ref HEAD
```

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 2.14.0 (Cygwin)
- OS version:  Windows 7

**Did this work in previous version of GitExtensions (which)?**

Worked w/ GitExtensions 2.49.03 and Cygwin git 2.13.2

Both `"git" fetch --progress "--all"` and `"git" pull --progress "origin"` also work ok from Cygwin bash w/ git 2.14.0

**Comment by RussKie** [comment]
Do you have [ConEmu](https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#advanced-general-use-console-emulator-for-console-output-in-command-dialogs) enabled?
If so, can you disable ConEmu and see if the problem still occurs?

**Comment by kmilos** [comment]
ConEmu was indeed enabled (guess it was as well and working in 2.49), but disabling leads to another problem:

git fetch --progress "--all"
Fetching origin
Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by RussKie** [comment]
This looks like credentials issue

**Comment by kmilos** [comment]
Went back to 2.49.03 where everything still works ootb

**Comment by RussKie** [comment]
It would still be good to find out what was causing the problem....
So we could fix it once and for all

**Comment by kmilos** [comment]
FYI, looks like 2.50.02 solved these errors

**Comment by RussKie** [comment]
Good. Thanks for letting us know
