### ISSUE TITLE
Feature request: compare files with files from different branch

### ISSUE THREAD

**Issue by vivainio** [gitextensions/gitextensions#3913]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

Currently, if you want to compare across branches, you need to ctrl+click revision in the revision grid. It's very hard to find the right branch (that may not have any commits in a long time) there, and the feature is badly discoverable (found it by googling).

Intuitive place for this would be the File Tree. Right click on directory or file, select "Compare with branch..." and select the branch to compare against. It would show diffs vs. that branch similar to "Diff (A: first --> B: second)" tab next to the File tab.

**Comment by LightCC** [comment]
This should not be closed. The referenced #1596 actually requested that this enhancement request be created.

I had trouble figuring out how to do this, whereas the requested enhancement would make it easy from an intuitive, context sensitive menu in the exact spot you can find individual files/folders in Git Extensions.

With the revision grid, it doesn't filter out just the files you want to look at, so the result isn't even the same.

i.e. at the command line, you can tell git specific files/folders to include in the diff.

**Comment by RussKie** [comment]
Pull requests are welcome

**Comment by GintasS** [comment]
Abandoning this because a duplicate issue was closed, no one is working on it.

**Comment by RussKie** [comment]
This is useful to add to the left panel. There is some activity related to the left panel improvements, so this would be good to keep open, and actually get done.

**Comment by drtingli** [comment]
Vote for this!
