### ISSUE TITLE
Worktree Remote Repositories - URL Missing

### ISSUE THREAD

**Issue by laurin1** [gitextensions/gitextensions#3922]
My additional repos (worktrees?) all seem to work fine, but the URL is missing in the UI and so it appears to to be broken (but again, they work fine e.g, I can "fetch --all" and the all update).

![image](https://user-images.githubusercontent.com/75857/29532844-c33f61bc-8674-11e7-80b3-1b35ea314c92.png)

**Comment by jbialobr** [comment]
Please update to the latest version.
