### ISSUE TITLE
Split up the pull/fetch/rebase/merge button into separate buttons

### ISSUE THREAD

**Issue by mikechamberlain** [gitextensions/gitextensions#3923]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

All fetching and merging from the toolbar has to be done through a fiddly split button that requires an unnecessarily high degree of dexterity for succeess.

![git-extensions-pull](https://user-images.githubusercontent.com/1414303/29545246-648796d2-8717-11e7-936e-9f1a5edbb8e1.png)

**What is the expected behavior?**

Remove the split button, together with the unintuitive and highly idiosyncratic "Set the next selection as the default" option. Introduce separate buttons for Merge, Rebase, Fetch, Fetch All and Open Pull Dialog.

**Motivation**

The vast majority of developers have high resolution monitors. We have plenty of empty space on the toolbar for more buttons. Pulling/merging/fetching is one of the most common operations. But we are currently forced to target a ~10 pixel-wide dropdown arrow to access the "non-default" actions.

This is made even more frustrating by the context menu's dismissal on mouse-out. It's too easy to slip off the edge and have to fiddle with the button again.

Lastly, the idea of setting the default action of a button from a menu on the button itself seems to be a completely random interaction, the likes of which I've only ever seen in GitExtensions.

All these issues are solved by breaking this weird and frustrating split button into regular top-level buttons.

**Comment by NikolayXHD** [comment]
I suggest this feature to be implemented as optional.

When the dropdown is replaced by 4 (or 5) separate buttons, then whenever user fetches
he has to carefully pick one button from a group of 5 with similarly looking blue arrow icons.

I find the current look and behavior convenient, because I don't use fetch options others than the one selected as default. I also think this is true for many people, there is even a feature request #4159 which depends on current behavior.

**Comment by RussKie** [comment]
I agree that the metaphor for selecting the default option is somewhat odd. This would be much better expressed with a Ribbon, if we had one.

However I also agree with @NikolayXHD that having several similarly looking buttons in the toolbar would have a high  degree of probability of creating confusion.
In my day-to-day job I see a lot with engineers who work on laptops, that do not provide have hi-res screens. Other engineers that have laptops with hi-res screens, often scale their Windows (150%, 200% etc).

Whilst I appreciate that the current UX is somewhat imperfect and it may cause some discomfort to some of our users, I am not entirely convinced the proposal would makes it universally better for everyone.

**Comment by jbialobr** [comment]
I have never been 100% happy with the split button. The idea I had to fix that, but never have had enough motivation to do it, is to make it configurable which button is the default button, which buttons should go next to the default button in the tool bar. The other buttons should go to drop down menu as it is now. All that configurations should take place in the settings dialog that we could remove the odd menu item to set the default action.

**Comment by NikolayXHD** [comment]
> All that configurations should take place in the settings dialog

We could also replace "Set the next selection as the default" checkbox with "Pull menu configuration" button that would lead to the corresponding settings page

**Comment by RussKie** [comment]
I'm happy for this discussion to be revisited when we ship v3

**Comment by gregsohl** [comment]
I like the way it is in the current v3.2.1 build with the options broken out on the drop down. Very useful and a great incremental improvement over v2.x

**Comment by GintasS** [comment]
Voting to close this, no one is working on this. Also, as @gregsohl has mentioned (me included) the setup is quite nice now, if someone still has an issue, should open a new ticket/create a PR with suggested improvements,

**Comment by RussKie** [comment]
We have made a number of improvements in this area. There are no plans to split the buttons.
If you really want buttons split you can add custom scripts to the toolbar.
