### ISSUE TITLE
Branch name is lost. 

### ISSUE THREAD

**Issue by igor-2016** [gitextensions/gitextensions#3925]
**Do you want to request a *feature* or report a *bug*?** SOLUTION

**What is the current behavior?**  I cannot see my branch name (I have created it, other people can see it now). 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** I commit my code to local repository, then tried to push code to remote repository, then I got Windows BLUE screen. After restarting I cannot see my branch name in dropdown of branches. I see my local changes  and extension offers to me commit ALL my local code (it cannot see my current state, it cannot see my previous branch).  

**What is the expected behavior?** I hope, I would like to see my branch  )

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?** unknown (I don't know the cause of the windows blue screen).

**Comment by RussKie** [comment]
do you see your branch if you run `git branch`?

**Comment by igor-2016** [comment]
.git\refs\heads\MY_BRANCH_NAME   I can see NULL NULL NULL NULL.....  so push to remote repository is physically broken. I have replaced NULL with valid number (from git) but got error that there are difficults on unpack data with this hash code... The solution is just creating other clone of repository.

**Comment by RussKie** [comment]
It looks like the git's database got corrupted. I had a similar problem happened to me once - I had to re-clone and then copy files over from the forks I had the corrupt repo...
I don't think there is anything we can do to help.

**Comment by vbjay** [comment]
This is why you use remotes.
