### ISSUE TITLE
fatal: Not a git repository on version 2.50.01

### ISSUE THREAD

**Issue by kismert** [gitextensions/gitextensions#3931]
Today, I went to check in changes, and when I clicked the 'File Tree' tab, I saw either:

- Error "fatal: Not a git repository (or any of the parent directories): .git"
- A blank window
- The contents of .gitignore

This behavior is consistent no matter what repository I open. 

However the 'Diff' tab always shows the correct commits.

I tried viewing the repositories in GitHub Desktop and SourceTree, and both seemed to show the correct commits (but neither has an analog to the 'File Tree' tab).

I have 18 repositories, the largest of which has almost 2600 files, and takes up about 350Mb of space.

This feels like a bug:

- All the repositories are affected
- Other Git clients seem to work OK
- It happened after 2.50.01 was installed (but not immediately after)
- I don't recall any earlier error messages, or taking any unusual actions in Git Extensions

Environment:

- GitExtensions version: 2.50.01
- GIT version: 2.13.2.windows.1
- OS version: Windows 10 Pro 64-bit

What should I do? I am not brave enough right now to check in changes, regardless of client.

Thanks, 
Ken

**Comment by jbialobr** [comment]
Can you install the https://github.com/gitextensions/gitextensions/releases/tag/v2.49.03 to see if it worked before the 2.50?

**Comment by kismert** [comment]
The problem sorted itself.

- The blank window was caused by the moving the vertical divider all the way left, hiding the File Tree list.
- The fatal error went away at about the same time. Not sure if this is related to above.

I'm closing this issue.
