### ISSUE TITLE
Start page race condition bug when saving settings

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#3932]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
If two Git Extensions are open, only the settings of the last closed one is kept. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- open two Git Extensions 
- in first GE, move a repo from Recent to a category 
- close first GE
- close second GE
- open a new GE
- see the missing repo, which should be in the category, we saved. 

**What is the expected behavior?**
Should save each setting change immediately to the config file, not when the GE is closed. 

**Environment you encounter the issue:**
Windows 7, Git Extensions v2.50.1. 

- GitExtensions version: v2.50.1
- GIT version: not relevant 
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**
Always.

**Comment by RussKie** [comment]
This will be obsolete as soon as #3693 will get in (which is planned for the next release).

**Comment by klorinczi** [comment]
Great!

I was not aware, that Start page redesign solves setting saving race condition problem, too.
Does it?

**Comment by jbialobr** [comment]
>This will be obsolete as soon as #3693 will get in (which is planned for the next release).

Can you elaborate why?
