### ISSUE TITLE
Convert user-supplied relative path to absolute path

### ISSUE THREAD

**Issue by lexarchik** [gitextensions/gitextensions#3947]
It's cosmetic but annoying issue.
When run from command line with `browse <path>` GitExtensions add path even if it's relative. 
Relative path can be meaningless, e.g. something like `.\..\..\..\` or `.`

I think better way is convert path to absolute path.

**Comment by jjmartin** [comment]
i'd love for a release with this fixed issue to be send out - but until then i found that `gitex browse pwd` works in place of `gitex browse .`  (at least in powershell - i'm not sure the mechanism for it working) for anyone looking for a work-around.
