### ISSUE TITLE
Commit dialog shows unsupported file for sub-modules with diff.mnemonicprefix=true

### ISSUE THREAD

**Issue by mserfli** [gitextensions/gitextensions#3948]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I have a repository with sub-modules. Everything works apart from the commit dialog. The diff view shows this error message for each sub-module

```
Unsupported file: 

System.ArgumentNullException: Value cannot be null.
Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2)
   at GitCommands.GitModule.GetSubmoduleFullPath(String localPath)
   at ResourceManager.LocalizationHelpers.ProcessSubmoduleStatus(GitModule module, GitSubmoduleStatus status)
   at GitUI.Editor.FileViewer.<>c__DisplayClass91_0.<ViewCurrentChanges>b__1()
   at GitCommands.AsyncLoader.<>c__DisplayClass21_0`1.<Load>b__0(CancellationToken token)
   at GitCommands.AsyncLoader.<>c__DisplayClass22_0`1.<Load>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

![gitext_submodules](https://user-images.githubusercontent.com/25421792/29748359-af6dffea-8b15-11e7-922d-ce8120cd1ad0.jpg)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It behaves on all machines of our project the same. 

Probably that helps

```
[submodule "tools/git-config"]
                path = tools/git-config
                url = https://<mydomain>/stash/scm/<myproj>/git-hooks-config.git
[submodule "busy"]
                path = busy
                url = https://<mydomain>/stash/scm/<myproj>/bsw-busy-zw.git
```

**What is the expected behavior?**
No error message should appear

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 2.13.3.windows.1 (PortableGit separately provided and set full paths in GitExt)
- OS version: Windows 7 Enterprise SP1

**Did this work in previous version of GitExtensions (which)?**
I didn't tested it.

**Comment by mserfli** [comment]
I started debugging on my own based on the tag v.2.50.01
Who should set the attribute status.Result.name before calling LocalizationHelpers.ProcessSubmoduleStatus in line 392 of ViewCurrentChanges

In my case status.Result.name is Null ...

If more debugging details would help I can provide it.

**Comment by RussKie** [comment]
As per the signature ` public void ViewCurrentChanges(..., Task<GitSubmoduleStatus> status)` the status is a result of an async operation. You need to walk up the stack and see where the status comes from...

Looking at the code on the GH it looks like `SubmoduleStatus` property contains the result of an async operation
https://github.com/gitextensions/gitextensions/blob/2d15fc1a68f999d56f08326e759becb35fdbb1f9/GitCommands/Git/GitItemStatus.cs#L54

Find where this property is assigned and put a breakpoint. You should be able to see what is causing the issue.

**Comment by mserfli** [comment]
Found the reason in git config diff.mnemonicprefix true

This is not checked in GitCommandHelpers::GetSubmoduleStatus. The regex in line 916 works only for 
diff.mnemonicprefix=false producing a diff with a/... b/...

But using diff.mnemonicprefix=true the diff output uses different prefixes (see also [Git doc](https://git-scm.com/docs/diff-config))

A workaround is not using diff.mnemonicprefix=true

A fast and simple fix would be to replace the regex by:
`var match = Regex.Match(line, @"diff --git ./(.+)\s./(.+)");`
One could precise the regex only to the allowed prefix characters.

Can this fix be provided in the next release?

**Comment by RussKie** [comment]
The fastest way to get it fixed is to submit a pr with a fix.

**Comment by mserfli** [comment]
Okay, but note this is my first pr on GitHub. Are there any policies (e.g. fork vs. branch), Git settings (e.g. autocrlf) I have to follow? I have some settings in the global Git config lilke autocrlf=false.

So please provide some instructions or a link to instructions for this project if I have anything to consider.

**Comment by RussKie** [comment]
https://github.com/gitextensions/gitextensions/wiki/Coding-Style

**Comment by RussKie** [comment]
* [General Microsoft .NET guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/) 
* https://github.com/gitextensions/gitextensions/wiki/Coding-Style
* fork

Do the best you can, submit PR, and if there are any issues those will be brought up to your attention.
