### ISSUE TITLE
Commit message field in merge dialog does not escape commit message properly

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#3954]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Merge with message `Test "messsage text" test` will fail with 

```
"C:\Program Files\Git\bin\git.exe" merge --no-ff -m "test "message text" test" origin/mh-service-label
merge: text test - not something we can merge
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Fill in a merge commit message that has two words in quotes surrounded by other words. 

**What is the expected behavior?**
Commit message `test "message text" test`

**Environment you encounter the issue:**
- GitExtensions version: 2.50.01
- GIT version: 2.14.1.windows.1, 
- OS version: Win 10

**Did this work in previous version of GitExtensions (which)?**
No

**Comment by RussKie** [comment]
How do I reproduce this in GE? Screenshots? Stack trace?

**Comment by tomasfejfar** [comment]
Sorry that I did not describe it precisely enough. 

![image](https://user-images.githubusercontent.com/642928/29937070-9decc36a-8e84-11e7-8f65-a24217799870.png)
