### ISSUE TITLE
business license?

### ISSUE THREAD

**Issue by RPeschke** [gitextensions/gitextensions#3958]
Hello,

I have a quick question to your Software, especially the license. Can I use the Software in a business environment as freeware or do I need to buy a business license?

Cheers,
Richard Peschke

PS: awesome software!!!

**Comment by RussKie** [comment]
Git Extensions are licensed under GPL-3
https://github.com/gitextensions/gitextensions/blob/master/LICENSE.md

You're free to use it in personal or commercial environments.

**Comment by RPeschke** [comment]
Thank you!

**Comment by vbjay** [comment]
You're welcome to throw money our way. :D
