### ISSUE TITLE
GitExtension show empty repository while in subfolder

### ISSUE THREAD

**Issue by Marimout** [gitextensions/gitextensions#3961]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I open Git Extension (right click => GitExt Browse) from a subfolder of a repository, GitExt show me an empty repository : "There is no commits made to this repository yet"
But not all subfolders produce this bug. For some, the repository is displayed correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The repository should be displayed correctly no matter the subfolder

**Environment you encounter the issue:**

- GitExtensions version: 2.48.05
- GIT version: git version 2.9.2.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**

**Comment by RussKie** [comment]
Please update to the latest version of GE and try again.

If it is still an issue we need more information - e.g. if it happens to
some subfolders and not the others then we need to know what so special
about those folders

**Comment by Marimout** [comment]
I think I figured out what the issue is. It seems that in folders where GE doesn't show correctly the repo, there is a .git folder which contains wrong information. By deleting this folder, GE shows the repo correctly again.

Thanks.
