### ISSUE TITLE
Panel layouts are unstable now

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#3966]
**Do you want to request a *feature* or report a *bug*?**
I want to report about a bug.

**What is the current behavior?**
From time to time GitEx resets layout of main window: commit info panel moves to the bottom, diff panel is narrowed (so file list is invisible almost)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I can't reproduce it. It happens from time to time. I open repository - and panels are broken. I relayout them. Then some time and again.

**What is the expected behavior?**
I want layout to be persistent.

**Environment you encounter the issue:**

- I use **portable** settings (`IsPortable` option is `True` in GitExtensions.exe.config file).
- GitExtensions version: 2.50.01
- GIT version: 2.13.0
- OS version: Windows 7 SP1 x64

**Did this work in previous version of GitExtensions (which)?**

Yes, previous versions (2.49 and lower) were stable in this case.

**Comment by jbialobr** [comment]
This is likely fixed in #3681

**Comment by pravic** [comment]
Yes, looks like it. Thanks.

**Comment by pravic** [comment]
Looks like not. From time to time (I can't say when and why) it resets splitter of the File Tree.

It does not remember its position even for the same repositories. Just resets from time to time (which is not a problem itself if we would have a proper default size).

![splitter](https://user-images.githubusercontent.com/724639/33655661-c2c79114-da84-11e7-99cf-6f7ae7fc1edc.png)

**Comment by pravic** [comment]
May be someone can tell where I can find its position in stored settings and I will catch when it gets reset.

**Comment by jbialobr** [comment]
The #3681fix will be included in 2.51

**Comment by pravic** [comment]
Cool, big thanks!
