### ISSUE TITLE
Very bad performance after Windows 10 reinstall

### ISSUE THREAD

**Issue by davidgiga1993** [gitextensions/gitextensions#3968]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When opening a repository the UI freezes. At this point, no git process has been spawned yet.
After a couple of minutes the first git processes are being spawned.
All git commands executed by GitExtensions takes for ever (5sec-5min)
Running the exact same commands via regular bash/cmd takes a fraction of the time. Even when executing them while GitExtensions is still waiting for the commands to complete.
This worked fine on the same machine with Windows 7 using the same git and GitExtensions version. I did a reinstall to Windows 10 and it went slow.
Also the same behavior cannot be reproduced on my private windows 10 machine.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The git processes should take the same time as if they are beeing executed manualy.

**Environment you encounter the issue:**
- GitExtensions version: Tried 2.49 and  2.50.01
- GIT version: 2.14.1.windows.1
- OS version: Windows 10 Enterprise

**Did this work in previous version of GitExtensions (which)?**
Yes, with the same version on another windows 10 machine.
Stopped working after doing a fresh of windows 10 (had 7 before)

I know that this issue might not be 100% related to GitExtensions itself but any help would be appreciated.

**Comment by RussKie** [comment]
Do you have console emulator enabled? If so, try disabling it and see if it
makes any difference

**Comment by davidgiga1993** [comment]
After downloading the sources and debugging it I found the root cause:
It seems like git extensions is trying to access the paths defined in `core.excludesfile`.
In there was an old path to a network share which does not exist anymore. Therefore git extensions locked up until a network timeout occurred.

**Comment by RussKie** [comment]
Well done!

Can you share in which files/methods that happens? Perhaps we can add more checks around it...

**Comment by davidgiga1993** [comment]
Sure. The issue was in [ToolStripGitStatus.cs:210](https://github.com/gitextensions/gitextensions/blob/2d15fc1a68f999d56f08326e759becb35fdbb1f9/GitUI/UserControls/ToolStripGitStatus.cs#L210) which blocked the client until a timeout from the share occurred.

**Comment by RussKie** [comment]
We may probably need to do something like described here
https://stackoverflow.com/questions/5152647/how-to-quickly-check-if-unc-path-is-available
