### ISSUE TITLE
2.50.01 Quoting issues on git checkout command

### ISSUE THREAD

**Issue by leak** [gitextensions/gitextensions#3969]
**Do you want to request a *feature* or report a *bug*?**
Potential bug but could also be misconfiguration, in the latter case I'd be thankful for pointers.

**What is the current behavior?**

When switching branches via toolbar the git checkout command is failing 
````
"git" checkout "dashboard"
error: pathspec 'dashboard"' did not match any file(s) known to git.
Done

Press Enter or Esc to close console...
```` 

Notice the trailing double quote on the error line.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Problem is that I cannot reproduce the issue properly, currently it is occurring on two machines (all running same versions and OS) and one where it doesn't occure. 
I have already reinstalled gitext, reset the configs or compared the configs between the working and non-working machines.
Additionally I have checked the PATH variable if there are any quoted paths, but I could not find any.

When running the command inside the console tab in gitext, it is completing properly.

**What is the expected behavior?**

The checkout command should complete without error as it does on command line.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 2.14.1.windows.1
- OS version: Win10 x64

**Did this work in previous version of GitExtensions (which)?**
2.49.* seems to be fine

**Comment by RussKie** [comment]
Are there any logs or stack traces available? Or screenshots?

**Comment by leak** [comment]
The git command itself doesn't appear in the command log, i supposed because it is failing?

Also a screenshot doesn't provide more information, as it just contains the error i posted above:

![image](https://user-images.githubusercontent.com/530056/30057756-52fcc118-9238-11e7-93c7-25e4aba83c4f.png)

**Comment by leak** [comment]
As it turns out the console emulator is breaking the git command.

Thanks to @DDuarte

**Comment by DDuarte** [comment]
Seems to be related to #3864 and #3800
