### ISSUE TITLE
Incorrect diff for force-updated ignored submodules

### ISSUE THREAD

**Issue by sharwell** [gitextensions/gitextensions#3972]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Commit diff shows as empty.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Add a submodule (and commit)
2. Update .gitmodules to set `ignore = all` for the added submodule (and commit)
3. In the submodule, commit a change
4. Use `git add [submodule-path] -f` to force-stage the changes to the submodule
5. Commit the change
6. Click on the commit in the history view

**What is the expected behavior?**

1. In the dialog for step 5, the staged change should appear as an update to the submodule, *not* a conflict
2. After step 6, the diff view should show the submodule changes

**Environment you encounter the issue:**

- GitExtensions version: 2.49.02
- GIT version: 2.14.1
- OS version: 10

**Did this work in previous version of GitExtensions (which)?**

Unknown.

**Comment by gerhardol** [comment]
Candidate to be fixed with #4760

**Comment by RussKie** [comment]
@sharwell can you please confirm it is fixed?

**Comment by RussKie** [comment]
@gerhardol do you think we can close this one?

**Comment by gerhardol** [comment]
I have read this a couple of times, need to take a closer look and test.
But I have a feeling that I would like to close this too.

**Comment by RussKie** [comment]
Please re-open if it still an issue.
