### ISSUE TITLE
File tree sometimes does not refresh

### ISSUE THREAD

**Issue by arnonuem** [gitextensions/gitextensions#3973]
bug

When i change a folder name in my filesystem GitExtensions (sometimes?) does not recognize this.
I expected to see an immediate change to the file tree.
I currently am working on Win10.

GitExtensions version 2.50.01
Git Version 2.13.1

Another context menu entry "Refresh" would be sufficient for me.

**Comment by RussKie** [comment]
If it is a bug please quatify what is "sometimes" and provide steps to
reproduce.

**Comment by pmiossec** [comment]
>When i change a folder name in my filesystem GitExtensions (sometimes?) does not recognize this.
>I expected to see an immediate change to the file tree.

Can you explain better what you call the file tree?
Because, what **I** call the file tree in GitExtensions, show the files and directories for the commit selected (not the working directory). 

You have to commit to see the changes in the file tree. So that can't be immediate.

**Comment by arnonuem** [comment]
The file tree is by default the second tab of the section on the bottom if a git project is opened in GitExtensions. It shows you all directories and files. I guess its the working directory then.
I thought the working directory reflects the state on my harddisk. So when i change a folder name on the harddisk (e.g. in windows explorer) shouldn´t this be in sync with what i see in the workingcopy?

**Comment by vbjay** [comment]
Wrong.  It does not represent the working directory.  It represents ALL
files/folders in git repo at selected commit.

**Comment by vbjay** [comment]
Click first commit in your repo.  Look at file tree.  Now click later
commit.  Look at file tree.

**Comment by pmiossec** [comment]
It's what I understood. So, you are wrong.
The file tree reflects the state of files and folders of the current commit selected (and not the state of the working directory).

**Comment by RussKie** [comment]
@arnonuem as @vbjay  and @pmiossec explained the File Tree tab displays the _working folder for the selected commit_ and **not** the current working folder on your hard drive.
This behavior is by design.

Any changes to your working folder can be seen via the Commit dialog (NB: git does not track empty folders so you won't see changes to these).
