### ISSUE TITLE
NRE / HandleConfigurationException on Startup

### ISSUE THREAD

**Issue by buddybubble** [gitextensions/gitextensions#3974]
I am experiencing a weird bug with GitExtensions on Win 7 64 bit, tested 2.5.0.1, 2.50.2 and 2.4.9.3.
Whenever I try to start GitExtensions, the application crashes before I even see the usual splash screen.
I checked the windows event log and the only thing I could find was an exception with source .net from GitExtensions with a stacktrace like this:

Frameworkversion: v.4.0.30319
System.NullReferenceException
GitExtensions.Program.HandleConfigurationException(System.Configuration.ConfigurationException)
GitExtensions.Program.Main()

What am I doing wrong? The computer has no antivirus etc running that could interfere, it's a clean developer machine without internet access.

Another thing I don't understand: I am unable to uninstall git extensions via the msi after that happens. The MSI aborts during uninstall with a nonsensical error message ("unable to uninstall etc. contact administrator"). Had to remove all files and clean the registry by hand to completely remove everything, which is very inconvenient.

**Comment by jbialobr** [comment]
Perhaps it is related to #2262

**Comment by buddybubble** [comment]
I don't think so, I don't even have the GitExtensions folder in my %appdata% mentioned in this bug yet, I guess it crashes before GitExtensions can create the folder and contents

**Comment by jbialobr** [comment]
Can you try this version? https://ci.appveyor.com/api/buildjobs/8ba3qkem2uab2dy7/artifacts/GitExtensions-2.50.01.682-Mono.zip

**Comment by vbjay** [comment]
Also find your settings file and delete it.  It is in %appdata%\..\local,
if I remember correctly.  Look for git extensions folder.

**Comment by jbialobr** [comment]
> Also find your settings file and delete it.  It is in %appdata%\..\local,

He did not get as far.

**Comment by vbjay** [comment]
%appdata% puts you in roaming by default.  I doubt he checked local.

**Comment by buddybubble** [comment]
@vbjay I did check all 3 appdata folders ;)

**Comment by buddybubble** [comment]
@jbialobr This version still crashes but gives a message box with a few more info:

System.Configuration.ConfigurationErrorsException : Unknown Invariant Attribute (C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config line 151)

then a lot of stacktrace stuff and at the bottom:

at NBug.Properties.Settings.get_UIMode() [..]
at NBug.Settings.LoadAppconfigSettings() at [..]Externals\NBug\Settings.cs

**Comment by jbialobr** [comment]
Could you also share the `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config` file?

**Comment by buddybubble** [comment]
sure (renamed to .txt)
[machine.config.txt](https://github.com/gitextensions/gitextensions/files/1284866/machine.config.txt)

**Comment by jbialobr** [comment]
It seems like the `invariant` attribute is not allowed under connectionStrings element.
https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/connection-strings-and-configuration-files
