### ISSUE TITLE
The 2.50.02 release is not signed

### ISSUE THREAD

**Issue by eric-wieser** [gitextensions/gitextensions#3979]
Upon downloading either msi installer, I'm presented with this dialog:

![image](https://user-images.githubusercontent.com/425260/30186605-1ed241f2-93db-11e7-82a6-505eb13dc533.png)

As far as I remember, previous releases have been code-signed

**Comment by KindDragon** [comment]
We don't have money for signature

**Comment by eric-wieser** [comment]
I definitely get a different dialog for 2.49.03. It says "unverified", but is at least self-signed

**Comment by jbialobr** [comment]
>We don't have money for signature

I remember @spdr870 talking there are some funds from donations.
Perhaps we should consider more open donation system like https://opencollective.com/learn-more

**Comment by boldwade** [comment]
What is the cost to get this signed?

**Comment by vbjay** [comment]
https://www.instantssl.com/code-signing-certificate.html.  We would also
want an ssl for something like gitextensions.org and have the code signing
match that domain.  This would cost hosting/ssl cert/static ip/ costs on
top.

**Comment by jbialobr** [comment]
It is around $100 a year.

**Comment by vbjay** [comment]
Where did you find $100 per year?

**Comment by jbialobr** [comment]
Here: https://www.startcomca.com

And here I just found a realy cheap one https://en.sklep.certum.pl/data-safety/code-signing-certificates/open-source-code-signing-929.html
86EUR for starter pack (card reader), then 28EUR a year.

**Comment by vbjay** [comment]
So they send you a smart card?

**Comment by vbjay** [comment]
I like that.  No need to worry about passwords or such.  You just have to
have physical security of the card.

**Comment by jbialobr** [comment]
The card is secured with PIN code.

**Comment by vbjay** [comment]
Cool.  I get it.

**Comment by stefan-wenig** [comment]
pls contact me at stefan.wenig@signpath.io if you want to save the intial cost.

**Comment by RussKie** [comment]
> pls contact me...

In the current form your message very much looks like a spam.
Could you please introduce yourself and clarify what exactly you are offering.
Thanks

**Comment by stefan-wenig** [comment]
Hey Russ, that would be some very specific spam if I may say so. 
I'd like to offer you access to a private beta of a service that saves you the trouble of spending "86EUR for starter pack (card reader)" and gives you more control over your signing process. Anything beyond that, I'd rather discuss privately at this point.
Best, Stefan

**Comment by RussKie** [comment]
Thank you, I will get in touch in coming days.

**Comment by GintasS** [comment]
@RussKie, is this fixed? Anyways, I think this should be closed, because it references an old release.

**Comment by RussKie** [comment]
Yes, we've been signing out artifacts for a while now.
