### ISSUE TITLE
Update the screenshots used on the website

### ISSUE THREAD

**Issue by otbutz** [gitextensions/gitextensions#3984]
The current screenshots which are used for https://gitextensions.github.io/ might be repellent for new users. The Windows 2000 style conveys that gitextensions is not actively developed.

![commitlog205 1](https://gitextensions.github.io/images/commitlog205.png)

The screenshots used on [readthedocs.io](https://git-extensions-documentation.readthedocs.io/en/latest/) should probably be prefered:

![readthedocs](https://git-extensions-documentation.readthedocs.io/en/latest/_images/commit_diff_view.png)

**Comment by gregsohl** [comment]
The screenshot on the website looks exactly like Git Extensions on my desktop - since I use the Windows Classic Theme :) The appearance of a window's adornments (in GE) is based on the current theme.

**Comment by otbutz** [comment]
> The appearance of a window's adornments (in GE) is based on the current theme.

I'm aware of that but visitors of the website might not know this and think that the application would be dated.
