### ISSUE TITLE
Git Extensions running commands in .git folder? 

### ISSUE THREAD

**Issue by jjmartin** [gitextensions/gitextensions#3985]
**What is the issue kind?**
- bug report

**What is the current behavior?**
When i go to check out a branch using git-extensions, (and other actions, like commit) I get an error:
```
fatal: Not a git repository (or any of the parent directories): .git
Done
```
This started happening when I upgraded to 2.50.01

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
That gitextensions runs the behavior successfully.

I can run the commandline given in my local directory and it works fine.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version:  git version 2.9.2.windows.1
- OS version: 
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.15063 N/A Build 15063

**Did this work in previous version of GitExtensions (which)?**
2.49

![image](https://user-images.githubusercontent.com/607183/30286083-ffef13ec-96e5-11e7-9813-775d00fbd898.png)

![image](https://user-images.githubusercontent.com/607183/30286121-16163a88-96e6-11e7-8e98-398e32be728a.png)

![image](https://user-images.githubusercontent.com/607183/30286141-226bd680-96e6-11e7-9117-e8110b87bc55.png)

using the same generated statement on my commandline:
![image](https://user-images.githubusercontent.com/607183/30286240-86d968a8-96e6-11e7-9c80-73b7fc1809a3.png)

**Comment by jbialobr** [comment]
Please check if you can reproduce it using 2.50.02 version.

**Comment by jjmartin** [comment]
yes... same issue in 2.50.02

**Comment by RussKie** [comment]
I wonder if it is something to do with the `-` in  the path.

Could you please rename the repo removing the dash and try again?

**Comment by jbialobr** [comment]
The process dialog shows that the current working dir is `.\`. How did you start GitExtensions? It looks like it could be the same issue as https://github.com/gitextensions/gitextensions/issues/3947

**Comment by jjmartin** [comment]
i've certainly had other paths with a `-` in it (after looking for one without, most of them have it in fact... ) 

i did just try in a path w/o the `-` and it still has the same issue.

i started it using `gitex browse .`  (been starting it this way for some time) 

i started it again after closing all the windows and navigated to the repo using the Start->Open  (which looks terrible on my surfacebook as of 2.5 btw (see image below))
and the git commands now work...  so it seems it doesn't like how i was starting it.


![image](https://user-images.githubusercontent.com/607183/30343015-774e657e-97c1-11e7-91e3-6435ff79c9af.png)

**Comment by jbialobr** [comment]
Duplicates #3947

**Comment by KindDragon** [comment]
Duplicate of #3947
