### ISSUE TITLE
Wildcard filter for tags

### ISSUE THREAD

**Issue by arisliang** [gitextensions/gitextensions#3986]
It'll be useful to have wildcard works for tags as well as a feature request, so we could create local tags on some repository, and filter based on those tags of interest.

Related to https://github.com/gitextensions/gitextensions/issues/614

**Comment by RussKie** [comment]
Please use the template provided when filing bugs or requesting features.

**Comment by RussKie** [comment]
Please use the template provided when filing bugs or requesting features.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion. Also, the template was not filled, so if someone still has an issue, please reopen this with the issue template.
