### ISSUE TITLE
F-Secure virus alert from 2.50.02 MSI

### ISSUE THREAD

**Issue by kurkku** [gitextensions/gitextensions#3987]
For your information that F-Secure Client Security Premium reports that GitExtensions-2.50.02-SetupComplete.msi installer contains a _Gen:Variant.Razy.158435_ in GitExtSshAskPass.exe executable.

Here's a VirusTotal report: https://www.virustotal.com/#/file/1321116c5998a4ce6b87a6c3e7dd7396bd1109d55ef26a3e62d73dd5a3484dce/detection

**Comment by RussKie** [comment]
Seeing that all other major antiviruses don't have any issues, I'd say it
is quite likely that F-Secure is reporting a false positive

**Comment by christofferTP** [comment]
Actually, 17 Vendors report some kind of malware within the file:
McAfee,
AegisLab,
MicroWorld-eScan,
ALYac,
BitDefender
Ad-Aware
F-Secure
GData
Emsisoft
CAT-QUICKHeal,
Rising,
TrendMicro-Housecall
Arcabit
Qihoo-360,
Paloalto
MAX.

Please look into why this might be the case. Most of them are Razy as mentioned above, and some are Heuristic detections..

**Comment by vbjay** [comment]
Source code is available. They are not viruses. Frankly, the ones finding things are pretty crappy av. I don't know where you are looking. 

CAT-QuickHeal
Genvariant.Razy
F-Secure
Gen:Variant.Razy.158435
McAfee
Artemis!CB223D0484A5
McAfee-GW-Edition
May differ from commercial off-the-shelf product. The company decides the particular settings with which the engine should run in VirusTotal.
Artemis!CB223D0484A5
TrendMicro-HouseCall are detected.

**Comment by vbjay** [comment]
https://www.av-comparatives.org/comparatives-reviews/

**Comment by jbialobr** [comment]
Related to/duplicate of https://github.com/gitextensions/gitextensions/issues/3724

**Comment by vbjay** [comment]
Even better way to see the data. http://chart.av-comparatives.org/chart1.php

**Comment by RussKie** [comment]
I don't think there is anything we can do further.
Closing.

**Comment by marco-cordeiro** [comment]
FYI Symantec is also reporting it as Virus.

**Comment by vbjay** [comment]
https://www.virustotal.com/#/url/cb79a60d2d04837fb1141a7c97cdb2c1c5ad2ac2008c437f16339fe38b62388d/detection
