### ISSUE TITLE
Weird tab field order

### ISSUE THREAD

**Issue by GufNZ** [gitextensions/gitextensions#3990]
**What is the issue kind?**

- bug report

**What is the current behavior?**

E.g. Push dialog with advanced settings open; press `tab` to cycle fields, but they are not in the expected order.  Most are in fact backwards.

**What is the expected behavior?**

In general, one expects `tab` to move focus to the next in logical visual order.

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 2.50.02
- OS version: Win10x84

**Did this work in previous version of GitExtensions (which)?**
Only just noticed it so not sure.

**Comment by GufNZ** [comment]
Cheers, much appreciated (c:

**Comment by RussKie** [comment]
Could you please test https://ci.appveyor.com/api/buildjobs/w7m24lh83jfym8tj/artifacts/GitExtensions-2.50.02.707-Mono.zip to confirm it works as expected

**Comment by GufNZ** [comment]
Looks good to me (c:
