### ISSUE TITLE
BUG: Gitextensions fileeditor crashes when a file named `Config` exists 

### ISSUE THREAD

**Issue by eric-wieser** [gitextensions/gitextensions#3991]
Simplest testcase I can construct to reproduce this:

```bash
git init
git config core.editor # gives "C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
echo "this is bad" > Config
git add -A && git commit -m "test"
git rebase -i master
```

giving the following dialog:

![image](https://user-images.githubusercontent.com/425260/30354021-dd15185e-97de-11e7-8955-777162b5a75f.png)

After selecting it, attempting to copy that error message gives

![image](https://user-images.githubusercontent.com/425260/30354028-e7d25842-97de-11e7-90ad-b39e57a7ad47.png)

- GitExtensions version: 2.50.02
- GIT version: 2.14.1.windows.1
- OS version: Windows 10 x64, 1703

**Comment by RussKie** [comment]
I can't seems to reproduce it, it works for me
![image](https://user-images.githubusercontent.com/4403806/30378690-5c8515dc-98d7-11e7-9236-c45731783b8b.png)
