### ISSUE TITLE
Virus warning in download install

### ISSUE THREAD

**Issue by mvhconsult** [gitextensions/gitextensions#3995]
**What is the issue kind?**

During install current version, F-secure virus scanner reports harmful file.

**What is the current behavior?**

Harmful file "GitExtSshAskPass.exe" removed
Reason: Gen:Variant.Razy.158435, location: C:\Program Files (x86)\GitExtensions\GitExtSshAskPass.exe

**What is the expected behavior?**
Would be nice to be able to install.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 
- OS version: Win10, 64bit

**Did this work in previous version of GitExtensions (which)?**
No problems whatsoever.

**Comment by vbjay** [comment]
Dupe #3987
