### ISSUE TITLE
[Bug] Scrollbar missing on Commit Tab (below history)

### ISSUE THREAD

**Issue by rkatzmann** [gitextensions/gitextensions#3998]
**What is the issue kind?**
Bug report 
**What is the current behavior?**
Since 2.50.02 the scrollbar is missing on the first tab (commit) of the three below the history. It works on the Diff tab. Switching or resizing does not bring it back. It worked in 2.50.01

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Start GitExtensions
- Open a repository with more history than fit on one screen page (like this one)

**What is the expected behavior?**
Scrollbar are shown on all three tabs Commit, File Tree, Diff as in the previos versions.

**Environment you encounter the issue:**
Ubuntu 16.04, Mono 5.2.0.215 (latest stable)

- GitExtensions version: 2.50.02
- GIT version: 2.7.4
- OS version: 16.04.3 LTS

**Did this work in previous version of GitExtensions (which)?**
yes, all of them as far as I remember

**Comment by RussKie** [comment]
Please provide a screenshot

**Comment by rkatzmann** [comment]
![gitextensions-missing-scrollbar](https://user-images.githubusercontent.com/8982023/30469544-473dc9da-99e0-11e7-9770-117aa9c46595.png)

**Comment by RussKie** [comment]
I just realised that under Mono the commit info panel is resizable too - you can make it taller, if necessary.
Granted it still may not be tall enough to accommodate a long commit info, but, in general should alleviate the issue.
