### ISSUE TITLE
Lockup during install win-7 after closing IE

### ISSUE THREAD

**Issue by gertvanloo** [gitextensions/gitextensions#4000]
**What is the issue kind?**
The install program would no longer respond. ctrl+alt+delete no longer worked, Explorer (normal windows explorer, NOT Internet Explorer) still responded to mouse but no actions. Had to force (button) power down computer.

- feature request
- bug report

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have never used Microsoft Internet Explorer. During install gitextension IE suddenly popped up on an gitextension issues page but also asking question about IE install 'features'. I tried to close IE using standard top-right cross. IE went unresponsive (faded) and gitextension install halted too. I tried to kill IE but ctrl+alt+delete did no longer work. Computer said 'program was not responding' (as if I had not noticed that!) Some other installs where still running (e.g. Kdiff) they finished after some mouse clicks. But unresponsive IE (faded) and gitextension install remained on screen with no changes (halted). I tried standard system-shutdown command: Start->shutdown but that only stopped the normal windows explorer. 
At that moment only thing visible on the screen was IE and gitextension install progress, both totally frozen.  Computer would NOT shut down. As final resort had to push and hold the power button.
I suspect this may not be so much gitextensions as IE locking up my computer. However that could have been avoided if the default browser (Firefox) was used.

**What is the expected behavior?**
Not to lock-up my computer :-)

**Environment you encounter the issue:**
Windows-7 
- GitExtensions version: GitExtensions-2.50.02-SetupComplete.msi
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
I have never installed it before.
On second try GitExtensions install finished.

**Comment by RussKie** [comment]
I do not believe the setup requires any browser or internet connectivity for that matter.
During past few weeks I had numerous installations on GE 2.50.02 (small and complete) on various computers (W8 and W10) and I have never seen anything like this.

Can you please try again?

**Comment by RussKie** [comment]
Closing due to lack of follow up
