### ISSUE TITLE
Select the two commits after opening submodule from difflist

### ISSUE THREAD

**Issue by maliayas** [gitextensions/gitextensions#4002]
P.S. Discussion continued from https://github.com/gitextensions/gitextensions/issues/2706#issuecomment-329881223

**What is the issue kind?**

- feature request

**What is the current behavior?**

When a submodule is opened from a difflist, user automatically jumps to the relevant commit (to-commit)

**What is the expected behavior?**

It would be better if the user automatically jumped to the 2 commits, from-commit and to-commit so that he/she could know the total changes in that submodule by the commit in the super-repo.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 1.8.5.2.msysgit.0
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**

Nope.

**Comment by vbjay** [comment]
I don't think automatically it should happen. I do think a context menu
option would be a good idea.

**Comment by maliayas** [comment]
I think we mean the same thing: right click on a submodule in a difflist and click "Open with Git Extensions" Currenty this action opens the submodule at the to-commit.

**Comment by vbjay** [comment]
Right. And it should stay that way. What I mean is have a menu active when
in a submodule, that does what you ask.

**Comment by maliayas** [comment]
Yeah but I mean using the already existing context menu item ("Open with Git Extensions"). Instead of opening the submodule at the to-commit, I propose to open the submodule both at from-commit and to-commit so that the diff tab will show the aggregated diff between the 2 commits.

**Comment by vbjay** [comment]
I understand what you mean. I also disagree. I wouldn't mind a menu option
IN the submodule that performed that action. I would want to have it just
select the current commit when navigating to it.

**Comment by maliayas** [comment]
OK, got your point. Thanks for the discussion.

**Comment by vbjay** [comment]
Sorry. I missed the context of the diff window. I get it now. Haven't had
my coffee. In the context of the diff it is fine. I thought you were
talking about current commit pointed by super repo and latest in submodule.

**Comment by maliayas** [comment]
Oh, that's a very different thing :) OK, glad it's clear now. Thanks again.

**Comment by jbialobr** [comment]
To sum it up:
1. Context menu for diff list - select `from` and `to` commits.
2. Context menu for file tree list - select `to` commit.
3. Context menu for staged/unstaged list in the commit window - select `from` and `to` commits.
4. Navigating from toolbar to submodule - select the current branch of the submodule.

**Comment by maliayas** [comment]
Great sum up.

* 1, 2, 3: Agreed.
* 4: I want to add a small note. Submodules don't necessarily have a branch checked out. So let's say "current revision" instead of "current branch"? And that "current revision" is the revision that current branch in the super-repo points at.

**Comment by jbialobr** [comment]
4. I'm ok with that.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.

**Comment by maliayas** [comment]
Hi. This was a perfect feature request. Maybe some developer would pick it in the future. Do we need further discussion regarding implementation?

**Comment by gerhardol** [comment]
The original request was implemented in 3.5: When you open a submodule in the sidepanel or diff tab, the current checkout and the "committed commit" is selected

**Comment by maliayas** [comment]
Oh, I didn't notice that. Thanks for the PR. Regards.
