### ISSUE TITLE
Procedure entry point curl_global_sslset could not be located in the dynamic link library +  git-remote-https.exe + version 2.50.2.0

### ISSUE THREAD

**Issue by prasannawin143** [gitextensions/gitextensions#4005]
**What is the issue kind?**
Procedure entry point curl_global_sslset could not be located in the dynamic link library + git-remote-https.exe + version 2.50.2.0

**What is the current behavior?**
- Unable to Clone/pull/fetch

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Updated the version to 2.50.2.0

**What is the expected behavior?**
Able t clone /pull / fetch

**Environment you encounter the issue:**
Windows 10

- GitExtensions version:
- GIT version:  2.50.2.0
- OS version:  windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes, Version - 2.50.1.0

**Comment by RussKie** [comment]
Your git install is probably stuffed... 
Can you git clone/fetch from bash? If not, reinstall git and try again

**Comment by KSemenenko** [comment]
All works on 32-bit versions

**Comment by LoungeFlyZ** [comment]
I have the exact same behavior.  Win 10 x64 (15063.540), Git 2.50.2.

I uninstalled and went back to 2.49.03 and don't experience the issue.

**Comment by osQar** [comment]
I have the same problem with Win 10 x64, Git Extensions 2.50.02, Git 2.14.1.windows.1. Everything seems to work fine with git version 2.13.2.windows.1 though.

**Comment by palver123** [comment]
Today I have updated from GitExtension 2.50.01 to 2.50.02. Simultaneously I updated my Git For Windows to 2.14.1 (from 2.12.? or 2.13.? IDK) and have experienced the same issue.

My solution was to downgrade Git For Windows to 2.13.2 as this is the version packed with GitExtensions 2.50.02. It works fine now.

Judging from Git For Windows release notes they've upgraded their cURL library recently. I believe something has changed in cURL DLLs, which either GitExtensions or Git For Windows has not yet integrated. Does GitExt call any cURL methods? If not, the only remaining source of error is GFW.

**Comment by jbialobr** [comment]
Off the top of my head, we don't call cURL directly.

**Comment by cocytus** [comment]
I got the same problem after installing a VS 2017 update. Reinstalling git 64 bit itself resolved the problem. Seems to be a problem/conflict with the version VS installs.

**Comment by martinamorris** [comment]
Having the same problem after updating to Git 2.14.1 from the default site -- https://git-scm.com/download/win.  De- and re-installed, but that doesn't solve the problem.

Installed 2.13.3 from .exe file from https://github.com/git-for-windows/git/releases.  That works.

**Comment by ArienHartgers** [comment]
I have same problem too

**Comment by cob999** [comment]
Same issue for me right after updating VS2017 to version 15.3.5

**Comment by ArienHartgers** [comment]
After reinstalling Git for Windows https://git-for-windows.github.io/ every works again. 
Reinstalling Git Extensions did not help for me.

**Comment by jbialobr** [comment]
This issue was reported to the git for windows. See [the issue](https://github.com/git-for-windows/git/issues/1268) for troubleshooting.
