### ISSUE TITLE
Scripts with On event setting "AfterCheckout" or "BeforeCheckout" do not activate on revision checkout

### ISSUE THREAD

**Issue by richardboone** [gitextensions/gitextensions#4006]
I needed to edit the way git extensions updates submodules on checkout because some of my submodules have been moved to a different location and I don't have the ability to edit .gitmodules on older commits of the repositories.  I turned off the update submodules on checkout setting and inserted two scripts to update submodules the way I needed and set one to activate AfterCheckout and the other to activate BeforeCheckout.  While these scripts activate the way they should when checking out a branch or when pulling, they do not activate at all when checking out a revision.

Using Git Extensions version 2.50.01.    
Using Windows 7 Enterprise.

**Comment by RussKie** [comment]
could you share scripts, so I could try to repro the issue?

**Comment by richardboone** [comment]
Triggering on BeforeCheckout:
git submodule init

Triggering on AfterCheckout:
git submodule update --recursive

**Comment by RussKie** [comment]
@richardboone do you want to try https://ci.appveyor.com/api/buildjobs/q9hxhjxl5hb6ybbg/artifacts/GitExtensions-2.50.02.1205-Mono.zip to see whether your issue is fixed?

**Comment by richardboone** [comment]
Scripts run as expected.  Issue is fixed.  Thanks.
