### ISSUE TITLE
Opening diff window crashes gitextensions

### ISSUE THREAD

**Issue by bhavanin29** [gitextensions/gitextensions#4007]
I had gitextensions 2.50.01 installed which was working fine,
I did update it to 2.50.02, since then when I open diff window git extension crashes with the message

```
Method not found: 'System.IObservable`1<System.Reactive.EventPattern`1<System.EventArgs>> System.Reactive.Linq.Observable.FromEventPattern(System.Action`1<System.EventHandler>, System.Action`1<System.EventHandler>)'.
```

and when I click on commit window nothing is shown.

Reverted my version to2.50.01 still getting the same error.

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/10469122/30585284-0871f3d6-9d35-11e7-82e6-8993406fe49f.png)

What installation Iam missing on my computer?
Any idea about what could be the problem?

- GitExtensions version: 2.50.01
- GIT version: 2.13.2
- OS version: 

Thank you,
Br,Bhavani

**Comment by jmecosta** [comment]
this is the relevant problem: https://github.com/Reactive-Extensions/Rx.NET/issues/99 its seems related how gitextensions is compiled. im not sure if this helps but we cant get this to work

**Comment by bhavanin29** [comment]
Thank Jorge, we compiled gitextensions on visual studio 2015 and got it working.

**Comment by bhavanin29** [comment]
Can you please provide the gitextensions installer compiled with VS2015
