### ISSUE TITLE
Inconsistencies in how path to plink.exe is obtained

### ISSUE THREAD

**Issue by CookiePLMonster** [gitextensions/gitextensions#4011]
**Do you want to request a *feature* or report a *bug*?**

Most likely a bug, or at least a design issue.

**What is the current behavior?**

There are two places Git Extensions stores paths to plink.exe (as well as other SSH-related tools, but those might be non-issue) - Windows Registry and GitExt Settings.  Different functionalities of the tool use different paths, so in case of desyncs incosistencies can occur. Therefore, it **is** possible to desync registry and GitExt Settings without modifying registry and/or settings manually.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Make sure path to plink.exe in **SSH -> Settings** is set to a non-default path.
2. Uninstall Git Extensions.
3. Install Git Extensions again (in my tests, I used 2.50.02).
4. Open regedit and navigate to `HKEY_CURRENT_USER\Software\GitExtensions` - notice `gitssh` is set to a default path, ie. plink.exe shipped with GitExt.
5. Run Git Extensions. **DO NOT CLICK APPLY NOR OK - click Cancel** - it is explicitly said that "Clicking Cancel will NOT revert any changes made", so it feels like a perfectly valid course of action.
6. Notice paths in registry did not change, but Settings -> SSH still contains custom paths - **these will not be placed in registry until you press Apply**
7. To make testing easier, navigate to GitExt install directory and remove PuTTY from there (so it's obvious when registry path is used).
8. Open any git repo with GitExt, navigate to Remote repositories and click Test Connection on any SSH-based remote - notice test succeeds, and therefore **Test Connection does not use `gitssh` registry entry**.
9. Try to Pull from any SSH-based remote - notice it fails (because it tries to run an inexistant plink.exe), and therefore **Git Pull ignores settings from SSH -> Configure PuTTY and only relies on registry entry**.

Additionally:
Even after applying settings in GitExt, notice that **only** `gitssh` registry entry gets updated - entries `pageant`, `plink`  and `puttygen` still point to default paths no matter what.

**What is the expected behavior?**

It's either not possible to desync registry and GitExt settings **or** registry entries are removed and all functionalities rely solely on GitExt Settings.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02, however a quick check with a self-compiled GitExt proves this is still an issue
- GIT version: 2.14.1 (64-bit version)
- OS version: Windows 10 Pro 1703 64-bit

**Did this work in previous version of GitExtensions (which)?**

Did not test.

**Comment by 13xforever** [comment]
Related issue: if you have custom putty paths, after upgrading git extension you'll still have your custom paths, but defaults will be used for all operations regardless (probably reset by the installer).

**Comment by vbjay** [comment]
Can we just yank the registry settings. Let's store them in the user profile and only if they are empty and registry has value then read them from registry.

**Comment by vbjay** [comment]
If not user profile at least set the setting to be machine level.

**Comment by 0x022b** [comment]
I also encountered this issue while I was troubleshooting why GitExtensions refused to connect to GitHub after they dropped TLS 1.0 and 1.1 support. See https://github.com/desktop/desktop/issues/4105#issuecomment-373363816 for more information.

**Comment by CookiePLMonster** [comment]
Note - this is still an issue in 3.5.1, I just hit it again after an upgrade, according to the UI plink.exe from `C:\Program Files\PuTTY` was used but in reality, the ones inside the Git Extensions directory did. I had to re-apply these settings to fix it.

**Comment by CookiePLMonster** [comment]
Since v4 doesn't ship PuTTY anymore, this is potentially not an issue anymore? Depends on how `SSH` default paths are handled now.

**Comment by CookiePLMonster** [comment]
I verified that due to v4 defaulting to `OpenSSH` after an upgrade, this is not an issue anymore. Changing back to `PuTTY` after an upgrade gets me my custom paths as expected.

I believe this resolves the issue 😅
