### ISSUE TITLE
NRE on open gitextensions

### ISSUE THREAD

**Issue by zxxc** [gitextensions/gitextensions#4012]
*bug*

**Seems i added custom icon for tollbar and now gitextensions is completely broken**

**I was trying to add new button to tollbar with icon**

**What is the expected behavior?**
GE should work

**Environment you encounter the issue:**

- GitExtensions version:2.50.02
- OS version: windows

**Did this work in previous version of GitExtensions (which)?**
issue was found on 2.50.01 
i tried to install 2.50,02 but issue still persists

http://prntscr.com/gnd2h6
p.s. Send and Quit seems is not working (maybe due to it's not using proxy?)

**Comment by zxxc** [comment]
http://prntscr.com/gnd8a0 config

**Comment by zxxc** [comment]
after deleting this http://prntscr.com/gnd8rv GE is working as usual

**Comment by RussKie** [comment]
You can paste the images in the GH textbox and they will be uploaded and shown on the ticket
