### ISSUE TITLE
Opening up the search dropdown list on focus

### ISSUE THREAD

**Issue by joshia89** [gitextensions/gitextensions#4016]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Minor UX improvement - On selecting the searchbox, the dropdown should open automatically.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
![expected behaviour](http://g.recordit.co/zAlJxLaFzz.gif)

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: NA
- OS version: NA

**Did this work in previous version of GitExtensions (which)?**
NA

**Comment by RussKie** [comment]
You need to apply the same behavior to `FormFileHistory`
![image](https://user-images.githubusercontent.com/4403806/30768519-c65f78f0-a04b-11e7-94b5-b19b67f5f9a9.png)
