### ISSUE TITLE
Github > View pull requests... > Close throws "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by harshdeep21** [gitextensions/gitextensions#4024]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Menu : Github > View pull requests... opens a window wherein after data loading straight a way closing the window throws "Object reference not set to an instance of an object." exception.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Menu : Github > View pull requests... opens a window wherein after data loading straight a way closing  the window throws "Object reference not set to an instance of an object." exception.

**What is the expected behavior?**
View Pull Requests is expected to be closed without throwing error.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.13.3
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**
I guess, Yes.

**Comment by harshdeep21** [comment]
Here are error window screenshots.

![generaltab](https://user-images.githubusercontent.com/2269560/30855911-3280be2e-a2d4-11e7-91c7-d454b9d9d8d5.PNG)

![exceptiontab](https://user-images.githubusercontent.com/2269560/30855909-327eca1a-a2d4-11e7-8002-b9156d377004.PNG)

![stacktrace](https://user-images.githubusercontent.com/2269560/30855910-3280cf0e-a2d4-11e7-9981-544d1d63b50f.PNG)

**Comment by RussKie** [comment]
I can repro it in 2.50.02 but not from master...

**Comment by jbialobr** [comment]
Fixed in 9a2d3b8cb9ce11f6ee969c7d77c1f0698c2eac8e
