### ISSUE TITLE
Not able to read TAGMESSAGE file

### ISSUE THREAD

**Issue by peterkft** [gitextensions/gitextensions#4025]
When creating a tag with an commit message.

An error occurred:
fatal: could not open or read '.../.git/\TAGMESSAGE': No such file or directory.

Looks like a mixed up between backslash and forwardslash in linux package.

**Comment by RussKie** [comment]
Please use the provided issue template when raising issues, it is there for a reason.

How should the correct path look?

**Comment by peterkft** [comment]
Do you want to request a feature or report a bug?
Bug report

What is the current behavior?
Under linux, when creating a tag with an commit message, an error occurred:
fatal: could not open or read '.../.git/\TAGMESSAGE': No such file or directory.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
- Create a tag on a particular commit.
- A new windows pop up and ask for tag label, and it is required to fill in a tag message.
- After pressing ok - a windows pop up and saying fatal: could not open or read '.../.git/\TAGMESSAGE': No such file or directory.

What is the expected behavior?
It should create a tag with no issues.

Environment you encounter the issue:
GitExtensions version: 2.50.02, 
GIT version: 2.14.1 (64-bit version)
OS version: Linux ubuntu 64 bit

Did this work in previous version of GitExtensions (which)?
Yes.

I have created an issue again with the template.

**Comment by jbialobr** [comment]
@RussKie https://github.com/gitextensions/gitextensions/pull/3898#issuecomment-326885447

**Comment by RussKie** [comment]
Duly noted.
However even if we had integration tests (which we should) I doubt we would
have caught it as we don't run tests for mono (which we also should).

**Comment by jbialobr** [comment]
Fixed in a0253f905ab783c6700a11c40197b973e43daecf
