### ISSUE TITLE
Submodule: display superproject local branches without waiting for remote branches load

### ISSUE THREAD

**Issue by XopherThomas** [gitextensions/gitextensions#4027]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**
When viewing a submodule, View -> "Show superproject branches" only works if "Show superprojct remote branches" is not selected.
View -> "Show superproject remote branches" does not function to show the expected superproject items.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Enter submodule.
2. Select View->Show superproject branches, but not "Show superproject remote branches"
3. See superproject local branches
4.  Select View -> "Show superproject remote branches".  Notice that superproject local branches are no longer shown as well as no superproject remote branches are shown.
6.  Unselecting "Show superproject remote branches" and leaving "Show superproject branches" selected immediately restores the local superproject branch names to the view.

Workaround Note: Cycling through Ctrl-Shift-L views will display proper behavior when you come back around, but then no longer honors the changes again until cycling through again.

**What is the expected behavior?**
Selecting View -> "Show superproject branches" should let you view as expected.
Selecting View -> "Show superproject remote branches" should let you view as expected.

**Environment you encounter the issue:**
- GitExtensions version: 2.50.02
- GIT version: git version 2.13.2.windows.1
- OS version:  Windows 7

**Did this work in previous version of GitExtensions (which)?**
Unknown, did not have ready access to try on previous versions.

**Comment by XopherThomas** [comment]
Apparently I am just impatient.  This functionality does work as intended, it is just slow.  I now recommend closing this As Designed.  One minor possible fix that could come out of this is to display superproject "local" branches sooner as they are available and not wait until superproject remote branches are also available, but I don't feel like that sort of change is crucial.

**Comment by RussKie** [comment]
We can keep it open if you reword the original issue as a feature request
to have local branches shown sooner

**Comment by XopherThomas** [comment]
Re-opening issue as a feature request for displaying local superproject branches when available before waiting for slower remote superproject branch information to be available when both are selected.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.

**Comment by gerhardol** [comment]
In 3.6 the number of superproject references is limited to 100, to speedup loading
