### ISSUE TITLE
Shortcut key "a" does not work in the "Create Branch" dialog

### ISSUE THREAD

**Issue by fan-jiang** [gitextensions/gitextensions#4040]
**Do you want to request a *feature* or report a *bug*?**

Report a *bug*.

**What is the current behavior?**

Shortcut key "a" does not work in the "Create Branch" dialog.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Highlight a revision and press the "Control + B" key to initiate the "Create branch" dialog.
- Press the "Alt" key to make the shortcut characters to be underlined.
- The phrase "Checkout after create" has "a" character underlined.
- Pressing the "a" key does not toggle the check box status.

**What is the expected behavior?**

Pressing the "a" key toggles the check box status.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.14.1.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**

Not sure.

**Comment by RussKie** [comment]
It all works as intended.

All Windows shortcuts (i.e. those use can see pressing `ALT`) are triggered only with `ALT+<key>` combination. If you press `ALT+a` the focus is set to the checkbox, and the check can be toggled with the space.

The checkbox doesn't have a label attached to it (unlike "Create orphan") so the OS isn't rendering the selection rectangle.

**Comment by fan-jiang** [comment]
@RussKie Yes, you are right. Pressing ALT+a bring the focus to the checkbox, and the check can be toggled with the spacebar.

I think, however, this is not user friendly because:

- Using the spacebar to toggle checkbox is an extra key stoke which is inconvenient.
- The check boxes in the same dialog behaves inconsistently. "Create orphan" check fox does not require pressing spacebar.

Why we could not associate "Checkout after create" to the checkbox? 

Another suggestion is that the term "Checkout after create" is not grammatically correct. It is better to change it, for example "Checkout branch after creation".

**Comment by RussKie** [comment]
You're right, it is inconsistent behavior.
