### ISSUE TITLE
Console paste bug

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4048]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
Unhandled exception at 0x000000006F7CFFC4 (ConEmuCD64.dll) in ConEmuC64.exe: Stack cookie instrumentation code detected a stack-based buffer overrun. occurred
![image](https://user-images.githubusercontent.com/3629489/31325310-9a4ca324-ac89-11e7-83b4-d8af6fb1dc31.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Copy text to clipboard.
2. Click in console in Git Extensions
3. repeat right clicking till buffer overrun

**What is the expected behavior?**
Prevent stack overrun.  Maybe limit how many characters can be pasted.  
**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.14.1.windows.1
- OS version: 
![image](https://user-images.githubusercontent.com/3629489/31325257-f9babd4c-ac88-11e7-9710-8ee42dfaec8b.png)

**Did this work in previous version of GitExtensions (which)?**
Not sure if it is new.

**Comment by RussKie** [comment]
Seems to work fine on my W8 machine...

![image](https://user-images.githubusercontent.com/4403806/31334796-7dde969a-ad3b-11e7-99f9-61cbdd5b85aa.png)

**Comment by vbjay** [comment]
X64?  It may be a win 10 only bug?  Curious. Try spacing and then pasting
so it is

Test testtest like I had it.

**Comment by vbjay** [comment]
I'll replicate it and attach a dump.

**Comment by RussKie** [comment]
yep, x64
![image](https://user-images.githubusercontent.com/4403806/31338752-4202f45c-ad4c-11e7-984d-5be04b39de6f.png)

I'll try on another machine tomorrow

**Comment by Maximus5** [comment]
1. What ConEmu version is used? I'm quite sure it is rather old. So, what if you update it?
2. I don't see the crash dump here, but it would be helpful.

**Comment by vbjay** [comment]
Ok.  It's odd.  I am going to try turning off avast.  I was able to pase
crazy length in the console at work.  On my laptop it does what I
demonstrated.  Will let you know.

**Comment by RussKie** [comment]
Any updates?

**Comment by vbjay** [comment]
Woops. I'll try at work and home today.

**Comment by vbjay** [comment]
Looks like it works at work.  
![image](https://user-images.githubusercontent.com/3629489/35683635-9a3ca894-0732-11e8-8b57-3ef50685c39c.png)

![image](https://user-images.githubusercontent.com/3629489/35683655-a8cbb6fc-0732-11e8-8b8e-30fd94b9711c.png)


Will check at home and let you know.

**Comment by vbjay** [comment]
Looks like we are good.  
![image](https://user-images.githubusercontent.com/3629489/35713137-be1dacca-0793-11e8-88e0-d131e220297b.png)

**Comment by RussKie** [comment]
Good to hear
