### ISSUE TITLE
DiffMerge should be sgdm.exe

### ISSUE THREAD

**Issue by vvnurmi** [gitextensions/gitextensions#4049]
I have the latest 64-bit DiffMerge (4.2.0) installed and I'm trying to configure Git Extensions 2.50.02 to use it as the merge tool. As I choose DiffMerge as "Mergetool" in the "Settings - Git Config" dialog, I expect Git Extensions to fill in the "Path to mergetool" but it doesn't happen. When I click on "Browse" and browse to "C:\Program Files\SourceGear\Common\DiffMerge" which is the default install location of DiffMerge and where I have sgdm.exe, I expect to see the executable but can't because Git Extension's file filter is fixed to DiffMerge.exe. I can work around this by typing in "sgdm.exe" in the file selection dialog.

All in all, setting up DiffMerge is much harder than it needs to be.

There already was issue #2454 about this but looks like it was resolved incorrectly (https://github.com/gitextensions/gitextensions/commit/36d116d41dc93a28d393cf8f802abcbd5d444dcf). I believe that

    exeName = "sgdm.exe";

is still missing from the fix to be complete.

Note: DiffMerge's executable changed from DiffMerge.exe to sgdm.exe in release 3.3.1 in July 2011:  https://sourcegear.com/diffmerge/webhelp/sec__release__3_3_1.html

**Comment by RussKie** [comment]
As a workaround you could specify it manually

for diff:
https://github.com/gitextensions/gitextensions/blob/7d9b8a21fc04eb0c74e71feb09f8ebef1e69ba0d/GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs#L208

for merge:
https://github.com/gitextensions/gitextensions/blob/7d9b8a21fc04eb0c74e71feb09f8ebef1e69ba0d/GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs#L320
