### ISSUE TITLE
Git extension is not displaying the commits separately, rather they are merged under one commit

### ISSUE THREAD

**Issue by kaushalgajjar** [gitextensions/gitextensions#4055]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Git extension displays all the commits under 1 single commit. The only way to view all the commits is to use the command "git log", else there is no way to figure out the commits that have been hidden from the listing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Referring to 2 snapshots attached below, on running "git log" from the console window, we can see that there are so many commits available between the first commit and the last commit.

However, looking at the listing in the top section of Git Extension, there is only single commit displayed between the first commit and the last commit.

(Where the first commit being " BUILDFIX : Ignoring test in 17e4 as no fix needed here." and the last commit being "FT201706040844 -  INC000013147459 - DE Specific Self Balancing cannot")

![snapshot_1](https://user-images.githubusercontent.com/3389655/31417193-c65f3d4a-ae79-11e7-8e77-c540cb8c2d8e.jpg)

![snapshot_2](https://user-images.githubusercontent.com/3389655/31417268-0a771b7e-ae7a-11e7-9f8d-43a4d0f5941b.jpg)

As you can see in the 3rd snapshot below, all the files changed (under all the commits which are hidden) are displayed inside 1 single commit "Revert "CS00098082 - Desktop - Addressing the issue of pop up blocker for the Insurance products"

![snapshot_3](https://user-images.githubusercontent.com/3389655/31417491-7d1c655c-ae7b-11e7-92e1-ea4e2e8ac494.jpg)

**What is the expected behavior?**

Git extension should list all the commits separately, i.e. there should be a single entry for each commit.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
Yes, it has been on-going issues.

**Comment by RussKie** [comment]
Steps to reproduce?

**Comment by kaushalgajjar** [comment]
Unfortunately, I dont have any steps to replicate. In my machine, Git extensions has been merging all the commits under one single commit recently only like from last 4-6 months. 

I can share the logs from some location if it's what you want.

**Comment by RussKie** [comment]
Does this happen to all repos on your machine, or is this problem specifc
to a particular repo?
Do you have another computer to try on the same repo?

**Comment by kaushalgajjar** [comment]
I've tried to setup the repository on E drive now, the other repository is in C drive. and both are having the same issue of commits being merged into one single commit. Attaching the screenshot for your reference,

![image](https://user-images.githubusercontent.com/3389655/31477514-1498b322-af58-11e7-985f-7e3c52321494.png)


Thinking that this issue could have something to with Git installation, so I did remove and install again. But it hasnt worked either. 

My guess is there some config file which is not having the correct setting to display the commits individually.

Do you have any suggestions ?

**Comment by RussKie** [comment]
Maybe something you accidentally unticked in View menu?
For instance I don't see you showing "merge commits"...

![image](https://user-images.githubusercontent.com/4403806/31478714-09b3ce78-af5e-11e7-9cbc-3d7b9e08e591.png)

**Comment by RussKie** [comment]
If you want to reset al settings you need to delete your configs
They are located at:
* C:\Users\\<user\>\AppData\Local\GitExtensions\\*
* C:\Users\\<user\>\AppData\Roaming\GitExtensions\\*

**Comment by kaushalgajjar** [comment]
![image](https://user-images.githubusercontent.com/3389655/31478811-b4ba5aee-af5e-11e7-9338-3c0a81b12f63.png)

**Comment by kaushalgajjar** [comment]
That's my view menu as of now, I ticked and unticked the "show merge commits", but still the same .. trying to delete the configs and let you know.

**Comment by RussKie** [comment]
"Show first parents" changes the graph:

![image](https://user-images.githubusercontent.com/4403806/31478897-4d08ac9c-af5f-11e7-9eeb-dad9a7b90b13.png)

![image](https://user-images.githubusercontent.com/4403806/31478918-6e3a60cc-af5f-11e7-9be2-6da6a61772d4.png)

http://git-extensions-documentation.readthedocs.io/en/latest/settings.html?highlight=parents#detailed-diff-viewer-show-file-differences-for-all-parents-in-browse-dialog

**Comment by kaushalgajjar** [comment]
I've updated my view menu as well as delete the config files as well.

My view menu:

![image](https://user-images.githubusercontent.com/3389655/31479375-79e30cd2-af62-11e7-9d88-6de4493e47d7.png)

But, still the commits are merged and displayed inside this one commit called "Revert "CS00098082 - Desktop - Addressing the issue of pop up blocker for the Insurance products"

![image](https://user-images.githubusercontent.com/3389655/31479400-a36624cc-af62-11e7-93ee-b71bfca6aaf8.png)

See, the Diff window above, the file "createpayee.vm.js" and "account-setupcardautopay.css.less" belong to two different commits which can be verified by running git log.

On running the git log, it displays the commits correctly, by showing each commit individually between the first commit and the last commit.

(Where the first commit being " BUILDFIX : Ignoring test in 17e4 as no fix needed here." and the last commit being "FT201706040844 - INC000013147459 - DE Specific Self Balancing cannot")

![image](https://user-images.githubusercontent.com/3389655/31479655-625027e2-af64-11e7-86fe-dc9a1ad8592f.png)

**Comment by jbialobr** [comment]
Can you go to the `Tools-> Gitcommand log` and find an entry like this:
```
"C:\Program Files\Git\bin\git.exe" log -z  --pretty=format:"<(__BEGIN_COMMIT__)>%n%H%n%P%n%T%n%aN%n%aE%n%at%n%cN%n%cE%n%ct%n%e%x00%s%x00%B%x00"  --date-order --all --boundary --not --glob=notes --not  --max-count="30000" --     #(took 1245 ms)
```
Can you paste it here? Can you also attach the output of the git command you found?

**Comment by kaushalgajjar** [comment]
I found 2 entries for "log" from GitCommand log, pasting it for reference


2017-10-13T08:49:29.2485236+11:00    "C:\Program Files (x86)\Git\bin\git.exe" log -z  --pretty=format:"<(__BEGIN_COMMIT__)>%n%H%n%P%n%T%n%aN%n%aE%n%at%n%cN%n%cE%n%ct%n%e%x00%s%x00%B%x00"  --date-order --simplify-by-decoration  --max-count="100" --     #(took 12395 ms)

2017-10-13T08:49:41.9712720+11:00    "C:\Program Files (x86)\Git\bin\git.exe" log -1 --pretty="format:%H%n%e%n%B%nNotes:%n%-N" e5cab0c58b225f33511135d2c4611c1b850d0c84    #(took 381 ms)

**Comment by jbialobr** [comment]
You have to go to `View->Set advanced filter` and uncheck the `Simplify by decoration` option.
![gitext](https://user-images.githubusercontent.com/1003909/31527138-a0d1250e-afcb-11e7-9769-af80b5404e5d.png)

**Comment by kaushalgajjar** [comment]
Thank you so much ! Finally, it worked !

**Comment by RussKie** [comment]
What does this filter do?
Obviously it changes the graph, but if you could explain the mechanics
behind it - it would be great.

**Comment by jbialobr** [comment]
See https://git-scm.com/docs/git-log#_history_simplification

**Comment by RussKie** [comment]
Thank you

**Comment by kaushalgajjar** [comment]
Yesterday, as RussKie suggested, I deleted all the config files from the above location, shouldn't that have deselected "Simplify by Decoration" and resolved the problem ?

**Comment by jeroendv** [comment]
![image](https://user-images.githubusercontent.com/1921532/37514982-b784e7e2-2909-11e8-8d8e-8e4e332eed5a.png)

the option `simplify by decoration` seems to be a suboption of the `branches` option.
Visually, because it is indented, but also logically because it is greyed out if `branches` is not checked.

This feels odd however, because the ` simplify by decoration` has effect independent of the `Branches` checkbox state.
