### ISSUE TITLE
Git Extension File History - How to view the commit ?

### ISSUE THREAD

**Issue by kaushalgajjar** [gitextensions/gitextensions#4056]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

We open the file history and then navigate to the Blame window, where you will find the author name listed next to each line. Now, we try to double click on any line to view all the other changes that the author has done, but the double click to view the commit doesn't work.

![snapshot_4](https://user-images.githubusercontent.com/3389655/31417906-4d2eedda-ae7e-11e7-9709-93d2bf24570a.jpg)

**What is the expected behavior?**

Inside the blame window, if we double click on the line, we should be able to view the commit under which the author of the line has done the changes. Even on doing a right click, there is no option to view the commit.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
In the earlier versions, it used to work, i.e. if we double click on the line, it opened the commit under the author has done the changes. It's stopped working since the recent releases.

**Comment by RussKie** [comment]
Agree, the UI is somewhat confusing but the functionality you seek it there.

You need to right click on the author on the left panel to see the commit in the new window
![image](https://user-images.githubusercontent.com/4403806/31422297-7030c582-ae98-11e7-9cda-b13ea597a080.png)
Or you can double click there and you will be taken to the actual commit

**Comment by kaushalgajjar** [comment]
Even if I right click on the author, there is no option to view the changes. 

Later, I will share the screen shot of what it looks like after right clicking on the author. But there is no option to view the changes.

**Comment by kaushalgajjar** [comment]
Apologies. I've the option to show changes after right-clicking on the author.

We can close this ticket.

![image](https://user-images.githubusercontent.com/3389655/31471257-b213cd50-af33-11e7-9356-8cc213cf6585.png)
