### ISSUE TITLE
Unable to view the following tabs while you start Git Extensions (Commit, File-Tree, Diff) 

### ISSUE THREAD

**Issue by rakini2** [gitextensions/gitextensions#4060]
What is the current behavior?
Initially when I open my GitExtensions along with my commits I usually see the Commit-Info, File-Tree, Diff tabs at the bottom and it was quite useful. But past two days I'm unable to view it, its not popping up. How to enable them again? I have attached a sample image below for reference. Please do guide me. Thanks in advance.

- GitExtensions version:2.50.01

![eg how screen appears](https://user-images.githubusercontent.com/21163255/31501878-157326fa-af31-11e7-9060-40b5ed3176af.PNG)

**Comment by pmiossec** [comment]
The button to toggle the display of tabs is the one at the far right in the toolbar just above the revision grid

**Comment by rakini2** [comment]
Thank you so much! It really helped!
