### ISSUE TITLE
Unable to filter file in the commit dialog

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#4062]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Unable to filter file in the commit dialog if file name contains hotkey such as `r` and `s`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Open the commit dialog
- Focus on the unstaged file filter textbox(combobox)
- Type `r` or `s`
- It will reset(`r`) or stage(`s`) the file instead of filtering file list

**What is the expected behavior?**
Should filter the file list

**Environment you encounter the issue:**

- GitExtensions version: master branch
- GIT version: 2.13.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Introduced by the file list filtering

**Comment by RussKie** [comment]
That's nasty, especially the reset bit

**Comment by RussKie** [comment]
Fixed in #4115
