### ISSUE TITLE
Too much latency in doing any operation on Windows XP

### ISSUE THREAD

**Issue by pankajazad** [gitextensions/gitextensions#4067]
BUG

Any git operation like commit, push, pull etc takes almost a minute on windows XP (during that time the GUI hangs). Once in a while it does behave as expected and takes a fraction of second but that's only 5-10 % of the operations.

To reproduce, Do multiple operations one after the other on windows xp. commit, push, pull etc.

Since git is known fast VCS any operation shouldn't take any perceptible delay.

**Environment:**

- GitExtensions version:
- GIT version: 2.50.02
- OS version: 2.10.windows-1

It worked properly in 2.48

**Comment by jbialobr** [comment]
https://github.com/gitextensions/gitextensions#os-support
