### ISSUE TITLE
Merging does not enable OK button when complete.

### ISSUE THREAD

**Issue by tulkjay** [gitextensions/gitextensions#4072]
**Do you want to request a *feature* or report a *bug*?**
  Bug

**What is the current behavior?**
After merging a branch into my current working branch, the popup that is logging the status of the request says done, but does not disable the Abort button and enable the OK button. Clicking the Abort button and reattempting the merge reports that the branch is already up to date. At this point Abort is disabled and OK is enabled.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Merge another branch into the current working branch(see image).

![image](https://user-images.githubusercontent.com/14252956/31829496-0d67be00-b583-11e7-872d-0529af11e338.png)

* Click Abort and reattempt the merge(see behavior)

![image](https://user-images.githubusercontent.com/14252956/31829324-87c12034-b582-11e7-81c2-2434fb838162.png)

**What is the expected behavior?**
Upon success, the Abort button should disable and the OK button should enable.

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 2.5.02
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes, cannot confirm version.

**Comment by RussKie** [comment]
Your first screenshot does not show that the operation has completed. And that is why the "OK" button is disabled.

**Comment by tulkjay** [comment]
The operation does not complete(or at least show that it completed), and
never enables the OK button. It leaves the OK button disabled indefinitely.
If I click Abort and try the operation again, it registers that it is up to
date, and acts like usual. It is just a UI bug, as far as I can see. I took
the first screenshot after about a minute and a half, when the merge
operation usually takes about 7 seconds or so. This has happened repeatedly.

**Comment by RussKie** [comment]
Please update git to latest version and try again
