### ISSUE TITLE
custom port dropping character on test connection and remote repo function not working with extra subdomain and custom port

### ISSUE THREAD

**Issue by gjutras** [gitextensions/gitextensions#4073]
Bug

when using the following connection:
ssh://git@bitbucket.subdomain.localserver.com:7999/appdev/myrepo.git

The plink command line shown that is tried to be tested is:
"c:\tools\PuTTY\plink.exe" -T -P 7999 "git@bitbucket.subdomain.localserver.com:appdev/emoney.git"

notice the / missing from in front of appdev and the extra? : in front of appdev.

I'm guessing it's the regular expression not dealing with an extra subdomain server and custom port.

**Comment by RussKie** [comment]
What does the correct command look like?

**Comment by GintasS** [comment]
Abandoning this because it needs more information.
