### ISSUE TITLE
Changing working directory fails if name contains spaces

### ISSUE THREAD

**Issue by icvanee** [gitextensions/gitextensions#4097]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Error message: bash: cd: too many arguments

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I have multiple Repositories in the change working directory list.
When I want to change it to a directory containing a space I get an error.

**What is the expected behavior?**
Changed to the correct working directory.

**Environment you encounter the issue:**
Console is displaying the error.

- GitExtensions version: 2.50.02

**Comment by RussKie** [comment]
Could you please share screenshots or steps to reproduce, thanks

**Comment by RussKie** [comment]
I don't seem to have any problems on W8 with 2.50.02

![image](https://user-images.githubusercontent.com/4403806/32049765-0a23afd0-ba9a-11e7-8a4e-7d6a99401cbd.png)

**Comment by icvanee** [comment]
I am not behind my computer where that happens but can you switch Git in the menu where you see your folder. Its when switching.

**Comment by icvanee** [comment]
![screen shot 2017-10-26 at 13 23 09](https://user-images.githubusercontent.com/5706988/32050377-e5d67bce-ba50-11e7-9ea0-39a0a2251971.png)
Just create two folders init git and switch folders.

**Comment by RussKie** [comment]
I don't think it is GE's issue - you're attempting to run an invalid command in bash...

![image](https://user-images.githubusercontent.com/4403806/32051856-f6fa7cec-baa1-11e7-8b86-113afb6583f3.png)

**Comment by vbjay** [comment]
Yep.  You have to escape the space.

cd /d/program\ files/

**Comment by icvanee** [comment]
I know that the space must be escaped.
But this 'cd' command is placed in console by GE if I switch a repository from the menu. I don't type it in myself ;) 
![screen shot 2017-10-26 at 13 23 09](https://user-images.githubusercontent.com/5706988/32088702-b5166a86-bae5-11e7-88fe-a084b14cc11d.png)

**Comment by RussKie** [comment]
With a big of mucking around I managed to repro it

1. Open any repository
2. Switch to conemu tab - it will set to the working directory
3. Switch to a repo with spaces in path
4. Click on conemu (nothing should happen)
5. Click off - conemu will attempt to change the path to the new working directory and fail with the described above error

**Comment by vbjay** [comment]
That shouldn't be too hard to fix.  Just alter the command text to be

commandText=$"{commandtext before arguments} {commandText.substring(get
arguments part).Replace(" ", "\ ")}" when it is a cd command.

**Comment by RussKie** [comment]
@vbjay would you like to send a PR?

**Comment by vbjay** [comment]
Sure assign me.

**Comment by RussKie** [comment]
GH doesn't let me, sorry....  But it is yours :)

**Comment by vbjay** [comment]
V 3 does not exhibit.  

![image](https://user-images.githubusercontent.com/3629489/48555410-1e4bb900-e8af-11e8-9b71-a80ebaf96996.png)

Fixing 2.51.

**Comment by vbjay** [comment]
This was a bigger issue than just cd.  

![image](https://user-images.githubusercontent.com/3629489/48556944-5ce37280-e8b3-11e8-9389-53f086b7817f.png)

**Comment by drewnoakes** [comment]
@vbjay that approach will fail if the path is quoted.

```bash
$ mkdir "with space"
$ cd with\ space
$ cd ..
$ cd "with\ space"
bash: cd: with\ space: No such file or directory
```

Probably safest just to quote the string.

Or in other words, think of escaping as something about the representation of the path in the context of the shell, not the path itself. We need to fix that representation. Quoting achieves that.

**Comment by vbjay** [comment]
Ok. So to make sure we don't double quote

- replace " with empty string then quote so if a path is already quoted we
don't get ""Folder 1/folder2/""

**Comment by drewnoakes** [comment]
I don't see an issue with double quoting. At the point we emit the cd command, if the path contains whitespace, quote it.

We already have a Quote extension method for string. We could add QuoteIfContainsWhiteSpace

**Comment by vbjay** [comment]
I do.

![image](https://user-images.githubusercontent.com/3629489/48594710-c00aee80-e91f-11e8-8129-b45be7f50ba2.png)

**Comment by vbjay** [comment]
I have it fixed but I am just making sure there aren't any needed quoting at other paths when posix paths are being used.

**Comment by GintasS** [comment]
Voting to close this, all PRs are either merged or closed.
