### ISSUE TITLE
Some commands throws NullReferenceException for a new empty repo (2.50.02)

### ISSUE THREAD

**Issue by seoriy** [gitextensions/gitextensions#4098]
1. Create new repo
2. Context menu commands "Open containing folder" and "Edit file" in Commit window and commands "Open containing folder" and "Clean working directory" in File tree throws a NullReferenceException

Expected behavior: all unallowed commands are disabled.

--- 
GitExtensions version: 2.50.02
OS version: Windows 7

**Comment by RussKie** [comment]
@gerhardol since you're currently reworking and cleaning up context menus, would you mind taking this one on?

**Comment by gerhardol** [comment]
ok

**Comment by gerhardol** [comment]
There are a number of menu items that should be disabled when no files are selected. A few are handled with #4084 (pending PR).
This issue will have to wait until #4084 and related PRs are handled as well as some of @RussKie refactoring is done.
