### ISSUE TITLE
setting to work with github via https

### ISSUE THREAD

**Issue by SailorMax** [gitextensions/gitextensions#4102]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
When trying to clone repository, GitExtensions trying to work with github.com via address like "git@github.com:username/repo.git"

**What is the expected behavior?**
I need option to use address like "https://github.com/username/repo.git". I set up access to git in Windows Credentials and to use it in GitExtensions also.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.14.1
- OS version: Windows 10 1709

**Did this work in previous version of GitExtensions (which)?**
Don't know.

**Comment by RussKie** [comment]
Could you please provide screenshots or steps to follow

**Comment by SailorMax** [comment]
screenshot: https://ibb.co/mkiMRR
Steps:

1. Menu "GitHub / Fork/Clone Repository..."
2. Choose required repository
3. Press "Clone" button

**Comment by RussKie** [comment]
Thanks
You could also just paste the image in here and it will get uploaded
