### ISSUE TITLE
Weird commit icon in VS2017

### ISSUE THREAD

**Issue by hacklex** [gitextensions/gitextensions#4113]
**The commit icon in VS17 is somewhat weird**

Am I the only one experiencing this?
![Am I the only one experiencing this?](https://i.imgur.com/pSSeL3Q.png)

- GitExtensions/GIT versions: both from the latest (checked Oct 30, 2017) available installer 
- OS version: win7 pro. Classic theme, in case it, for some mystic reason, matters.

Everything worked fine for years, up to the day I moved to VS17...

**Comment by RussKie** [comment]
Try resetting the GE's toolbar icons

**Comment by justanotheranonymoususer** [comment]
@hacklex can you please publish the compiled extension installer? Thanks

**Comment by hacklex** [comment]
This one, I believe. The only change I did to it was altering the manifest so that it could start installing for VS2017.
[GitExtensionsVSIX.zip](https://github.com/gitextensions/gitextensions/files/1441765/GitExtensionsVSIX.zip)

**Comment by justanotheranonymoususer** [comment]
It doesn't work, unfortunately.

![image](https://user-images.githubusercontent.com/5781692/32391311-3bac9ca6-c0da-11e7-86f2-782c4e22a624.png)

**Comment by hacklex** [comment]
oh, right. I edited the manifest by hand in order to install it at all.

**Comment by RussKie** [comment]
You can build a vsix which installs fine in vs2017 from the source. No
hacking is required.

The same vsix is also shipped with the installation, but it is available
only if you have/chose to install vs2015 integration.
It is an ommission on our part.

We are currently looking at how we can publish the vsix on its own.
It is a frustratingly painfully slow process, please bear with us.

**Comment by justanotheranonymoususer** [comment]
Thanks. I ended up extracting all the files from the msi, and installing the vsix manually. It worked.

**Comment by hacklex** [comment]
I just built the addin in VS2017, then installed it. That is even better to me, as I'll now finally be able to change all the toolbar icons to my liking, and apply proper color/alpha replace where it is desperately needed.

I'm not sure if it's possible to even repeat the issue for VS2017 (I mean, the corrupted commit icon) – without knee-deep hacking into VS2015 vsix, – so I guess it's okay to close it.

**Comment by RussKie** [comment]
Good stuff, closing then.

Btw, when you installed the plugin did you have problems like #4117? It seems to be plaguing my installations....

**Comment by justanotheranonymoususer** [comment]
@RussKie Yes, I had duplicates just as you describe. I fixed it simply by clicking on the arrow and unchecking the items. The "original" items were grayed/disabled (impossible to uncheck), and the duplicates weren't disabled.
