### ISSUE TITLE
Graph shows undefined lines

### ISSUE THREAD

**Issue by KarolisMil** [gitextensions/gitextensions#4122]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Git brach graph is incorrect and overloaded with unreal lines. In first attached picture is of the very bottom of the graph. Other two pictures show current graph. In reality there are not that many branches.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I do not know how to reproduce it. I have been using it like this for couple months now.

**What is the expected behavior?**
Correct graph...

**Environment you encounter the issue:**
Windows 7 64 bit

- GitExtensions version: 2.50.02
- GIT version: 2.13.2.windows.1
- OS version: Windows 7 64 bit Service pack 1

**Did this work in previous version of GitExtensions (which)?**
I am not completely sure, but I think this bug occur before GitExtensions update and did not reocer after update.

![2017-11-06 4](https://user-images.githubusercontent.com/13799557/32432226-66e9cbe4-c2df-11e7-9bb8-654f3acdae50.png)
![2017-11-06](https://user-images.githubusercontent.com/13799557/32432086-d2315706-c2de-11e7-8baf-5090402ab423.png)
![2017-11-06 2](https://user-images.githubusercontent.com/13799557/32432087-d25c70c6-c2de-11e7-9993-b2f4f75dd49a.png)

**Comment by vbjay** [comment]
Run git branch -a

**Comment by KarolisMil** [comment]
Ok, I get the list of my branches, but is there anything I can do to fix GitExtensions GUI view by myself?
BR.

**Comment by vbjay** [comment]
Kind of wanted to see the results.

**Comment by fmikulu** [comment]
Hi,
see attached my test repo and a screenshot with gitextension an tortoisegit.
 I hope it helps to replicate the problem and solve this issue.
[gitextTest.zip](https://github.com/gitextensions/gitextensions/files/1551242/gitextTest.zip)
![2017-12-12 11_45_56-c__projects_gitexttest - log messages - tortoisegit](https://user-images.githubusercontent.com/17859927/33880795-0c4f74e8-df33-11e7-8c7f-720e47f0fed5.png)

**Comment by vbjay** [comment]
There is nothing wrong. It shows the common parent commit. It then shows b1
and b2 by commit time. Then I shows a merge commit merging the two
branches.

**Comment by fmikulu** [comment]
I think this is wrong. This is the simplest example of strange behavior described above by @KarolisMil 
Correct graph is presented by TortoiseGit. Compare these two pictures. They show the same repo. Commits c2, c3 are not shown by GitExtensions at all. Graphs of more complex repos are then full of strange lines beginning at nowhere.

TortoiseGit shows the same as `git log --graph` correctly, but GitExtension doesn't. You can try it with attached repo.

**Comment by vbjay** [comment]
Then he has a filter set. It will show them unless he has an option set

**Comment by fmikulu** [comment]
Disabling "Show first parent" view option returns it to normal. I didn't realize it was switched on.
@KarolisMil  I guess it is the solution of this issue.
Thanks.

**Comment by RussKie** [comment]
That setting has bitten many, even those with GE experience....

**Comment by vbjay** [comment]
Maybe we could add another warning like the one that says  in the middle of
rebase that says commits are filtered.

**Comment by RussKie** [comment]
Yes, I've been thinking the same
