### ISSUE TITLE
[Build Error] The referenced component 'Microsoft.VisualStudio.CommandBars' could not be found.

### ISSUE THREAD

**Issue by CDAGaming** [gitextensions/gitextensions#4123]
Does anyone know what i need to get/add to my visual Studio Enviroment to Supply this Missing Component?

Thanks in advance.

**Comment by vbjay** [comment]
https://www.visualstudio.com/vs/visual-studio-workloads/  

![image](https://user-images.githubusercontent.com/3629489/32448190-38451878-c2dc-11e7-98b8-32c8b7332878.png)

**Comment by CDAGaming** [comment]
![capture](https://user-images.githubusercontent.com/16328918/32451298-1fd31b28-c2dc-11e7-9d0d-87981e22b950.PNG)
Do i perhaps need VS2015 installed for this Issue (At this time i only have VS2017)

**Comment by vbjay** [comment]
Woops.  Right.  https://msdn.microsoft.com/en-us/library/mt683786.aspx

**Comment by CDAGaming** [comment]
Closed as Solved. Thanks Again 👍

**Comment by RussKie** [comment]
Selecting a workload doesn't mean you have all the components in that workload installed.
It is well worth switching to "Individual components" tab and ensure all that you needs is selected

**Comment by vbjay** [comment]
True.  It sets the recommended options for that workoad.

**Comment by CDAGaming** [comment]
Yea, the fix was with the last link vbjay sent, for VS2015. I had other Errors with the Setup project but that was related to other missing components and are fixed

**Comment by vbjay** [comment]
Yes. You have to install wixtoolset.

**Comment by CDAGaming** [comment]
No I meant it was from other Missing VS2017/VS2015 Components, which i have now fixed
