### ISSUE TITLE
Inaccurate context menu text for reset operation

### ISSUE THREAD

**Issue by safield** [gitextensions/gitextensions#4125]
Observed Behavior:
When in commit window and viewing staging area...
If you right click on a file you are given the option of "Reset file or directory changes".

Expected Behavior:
This language should be changed to say "Reset file" when a file is clicked, and "Reset directory" when a directory is clicked.

This prevents the need for the user to make the assumption (however obvious) that this operation applies to the type of object that was clicked on.

As a new user to git, I can tell you that when I initially read this language, I was apprehensive, because I definitely did not want to reset any directory.

**Comment by gerhardol** [comment]
If this is to be changed, then it should be changed to "Reset selected files" because directories are not really stored in git.
However, the work required for a change like this is quite high (everything including translations is), so priority is low for me.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
