### ISSUE TITLE
Simple Git Extensions Plugin for Visual Studio Code

### ISSUE THREAD

**Issue by erikleo** [gitextensions/gitextensions#4128]
Feature request for a simple Visual studio code plugin

Really we only need 1 main feature to start with .. a single button that will open the active repository of VS code in Git Extensions.

This would be great time saver.

I have found that it can be accomplished by typing"gitextensions browse" in the terminal, but it locks up the command line and may not be that easy to remember.

Anyone willing to take this on?

**Comment by vbjay** [comment]
https://code.visualstudio.com/docs/editor/versioncontrol

**Comment by erikleo** [comment]
yes, VS Code has built in version control but the point of the plugin would be to launch git extensions since it has features that are not available in VS Code nativity.

**Comment by vbjay** [comment]
Sure. Just making sure it was known.

**Comment by RussKie** [comment]
I don't use vscode often, but when I do I disable built in git as it interferes with git extensions by constantly locking the index.

**Comment by vbjay** [comment]
Well that makes sense.  Can't have two tigers in the same pit.

**Comment by mrexodia** [comment]
There is a similar extension for Sublime text, perhaps it could be useful as a starting point? https://github.com/mrexodia/sublime-gitextensions (my fork with some small fixes). Probably the warning about disabling the built-in version control would be appropriate.

**Comment by pmiossec** [comment]
I did a first try here ( https://github.com/pmiossec/vscode-gitextensions ).
Everything supported by the sublime extension is done.

It needs more work to better support the newly introduced "workspace" feature of VS Code.
Also need publishing...

**Comment by pmiossec** [comment]
@erikleo I have packaged a preview version that you could find here: https://github.com/pmiossec/vscode-gitextensions/releases

Download the vsix file and install it using: `code --install-extension vscode-gitextensions-0.0.1.vsix`

Feel free to report problems or if it's ok.

**Comment by erikleo** [comment]
Thanks @pmiossec .. i'm currently getting "Error: certificate has expired".  Not sure if it because of my local setup, i can try later on another machine.

**Comment by pmiossec** [comment]
@erikleo yes, try on another machine. Because it works for me on 2 different ones. I just checked.

FYI, it requires vscode 1.18

**Comment by pmiossec** [comment]
@erikleo In fact, there is perhaps an easier and more reliable way to install the extension than the command line I gave you.

Try to install it through the "command palette" with "Extensions : Install from VSIX...".

I hope it will work this time.

**Comment by erikleo** [comment]
@pmiossec That did it, I was able to install using the above method.  Looks good, I am able to successfully run the git extensions commands from the command pallet.

It would be really nice however to have quicker access to the Gitextensions browse command.   Is there a way you you know of to make this command an icon? (either in the left side or maybe bottom task bar)

**Comment by RussKie** [comment]
Well done @pmiossec.

Since this conversation isn't directly related to GE it may be prudent to move further discussions about Philippe's plugin into his repo.
I am more than happy to mention the plugin and link to the repo in our readme.

**Comment by pmiossec** [comment]
@erikleo I have updated the extension adding 2 commands in the status bar. Have a try....

We could continue the discussion here: https://github.com/pmiossec/vscode-gitextensions/issues/1

**Comment by pmiossec** [comment]
I have published in the marketplace a first version of the extension.

**Comment by RussKie** [comment]
good stuff!
if you give a link, i will add it to our readme

**Comment by pmiossec** [comment]
https://marketplace.visualstudio.com/items?itemName=pmiossec.vscode-gitextensions

But just mentionning that the extension exists should be enough because that could be easily found from the extensions search inside VS Code...

**Comment by pmiossec** [comment]
I will change the not so good purple color if I release a new version...

**Comment by RussKie** [comment]
@pmiossec are you ok with this?

![image](https://user-images.githubusercontent.com/4403806/32974890-36915ca2-cc56-11e7-8d45-41fb733e4f9c.png)

**Comment by pmiossec** [comment]
Yes. I don't know if we should also add to install it through Vscode
marketplace.

**Comment by pmiossec** [comment]
I mean the one inside VS Code...

**Comment by RussKie** [comment]
you mean like this?

![image](https://user-images.githubusercontent.com/4403806/32975039-75725ad8-cc57-11e7-813c-0a7e73aa8940.png)

**Comment by pmiossec** [comment]
Perfect!

**Comment by RussKie** [comment]
I suppose we can close the issue now.
