### ISSUE TITLE
Not able to see commits merged from other branch when showing current branch only

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#4145]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Steps:
- Right click any commit in the revision graph
- Select the `view` context menu
- Select the `show current branch only` sub menu

The graph is like below
- The graph column is very narrow, you can expand the column, but will be reverted back if you scroll the mouse
- The commits merged from other branches are not showing.

![image](https://user-images.githubusercontent.com/596334/32699274-b9e25c9a-c7ed-11e7-9da2-e1b4749de2ef.png)

**What is the expected behavior?**

In v2.48.05, you can see the commits merged from other branches
![image](https://user-images.githubusercontent.com/596334/32699260-9960b8cc-c7ed-11e7-867e-52349793467c.png)

**Environment you encounter the issue:**

- GitExtensions version: any version >= 2.50
- GIT version: 2.15
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Worked in 2.48.05

**Comment by EbenZhang** [comment]
I guess I pressed `CTRL + SHIFT + S` which enabled the `Show First Parent` view option. Press the keys again or goto View->ShowFirstParent will fix it.

**Comment by RussKie** [comment]
Some options we have are quite confusing even to the experienced users....
