### ISSUE TITLE
Add branch labels for (especially, merge) commits on Diff tab of Commit Details pane

### ISSUE THREAD

**Issue by 62mkv** [gitextensions/gitextensions#4148]
**Do you want to request a *feature* or report a *bug*?**

This is a *feature* request.

**What is the current behavior?**

Currently, the Diff tab of Commit Details pane, has (collapsable) sections titled like the follows:
`Diff with parent 27eb5b86`, `Diff with parent 217e12eb`

**What is the expected behavior?**

Would be much easier for comprehension to have sections titled as follows: 
`Diff with parent 27eb5b86 (origin/develop)`, `Diff with parent 217e12eb (release/120712, origin/release/120712)`

I mean - to add HEAD names, that ARE CURRENTLY pointing at the respective commits (if there're any), to a Diff tab sections 

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: does not matter
- OS version: Win10 x64

**Did this work in previous version of GitExtensions (which)?**

I don't think so

**Comment by RussKie** [comment]
It is a probably not a bad idea, however it may lead to a very long tab title...

**Comment by 62mkv** [comment]
no problem to chop it off at, say, 20 characters or so (with a floating hint displaying the full version)

**Comment by 62mkv** [comment]
>  it may lead to a very long tab title...

I did not actually mean "tab title", I mean the collapsable section heading (or how do you call it) where it now says "Diff with parent ABABABAB"

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/32720873-e91ef3c6-c8b8-11e7-81ed-0fc98e21102f.png)

**Comment by jbialobr** [comment]
It seems to be a dup of #3709
![gitext](https://user-images.githubusercontent.com/1003909/32721907-6551d4f0-c868-11e7-9fdd-cf4300cd7bc8.png)

**Comment by gerhardol** [comment]
Implemented, see #3709
