### ISSUE TITLE
File tree tab has no content

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4151]
**Do you want to request a *feature* or report a *bug*?**
Bug

![gitext](https://user-images.githubusercontent.com/1003909/32722695-fbb783de-c86a-11e7-9908-bb4f89bfb7fe.png)

**Environment you encounter the issue:**

- GitExtensions version: cd032fd48a6693b080f38d87388bc0f601db4e02

**Comment by RussKie** [comment]
I've noticed it too today.

**Comment by RussKie** [comment]
@gerhardol reported it earlier in https://github.com/gitextensions/gitextensions/pull/4138
