### ISSUE TITLE
Git Bash ssh-keygen throwing Permission Denied error in Windows

### ISSUE THREAD

**Issue by mccreeker** [gitextensions/gitextensions#4158]
**Do you want to request a *feature* or report a *bug*?** 
bug

**What is the current behavior?**
`bash: /usr/bin/ssh-keygen: Permission denied`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open up Git Bash for Windows
2. type ssh-keygen with or without any options
3. Also you could try opening Git GUI, clicking Help > Show SSH Key > Generate to get the same error.

**What is the expected behavior?**
Show key-generation output as specified here: https://git-scm.com/book/en/v2/Git-on-the-Server-Generating-Your-SSH-Public-Key

**Environment you encounter the issue:**
Windows 10 any version

- GitExtensions version: 
- GIT version: 2.13.2.1 (from Git Extensions 2.50.02)
- OS version: Windows 10 Enterprise 2016 LTSB 64-bit

**Did this work in previous version of GitExtensions (which)?**
Yah, back when Git was 1.9.4

**Comment by mccreeker** [comment]
Also, if we try to just double-clicking the file in Explorer, it shows a Windows pop-up error saying it can't access the file... any other file I've clicked so far just runs.

![image](https://user-images.githubusercontent.com/33667567/32863922-6f6eee9c-ca1a-11e7-8841-a56b48f0ebac.png)

**Comment by vbjay** [comment]
This has nothing to do with git extensions. Git extensions uses puttygen to
generate keys or import openssl keys and convert to putty. You need to run
that program in s cmd promt in a folder that you have write access to. You
don't have write access to program files folders.

**Comment by mccreeker** [comment]
How does Git Extensions use puttygen to generate keys?

I've run ssh-keygen in Git Bash for Windows (which Git Extensions installs), Windows CLI, in various folders which I have access to (again, I can run the other .exe files in the Program Files folder) such as C:\Users\[me]\.ssh or C:\Users\[me] or C:\Users\[me]\Documents... all of which I can write to (and I had to manually create the .ssh folder in Git Bash though I also tried it in Windows CLI as my own user or Administrator).

The fact that trying to open the file directly shows that screenshot error while other files will open indicates a problem with ssh-keygen.exe that was installed by Git Extensions... and the permissions look exactly the same as the other .exe files, our IT Desk guys know our permissions better and said everything looks correct. Please, I shouldn't have to repeat several things I stated in the OP.

Please make any other suggestions, I've already tried what you said. Have you tried this yourself? Does it work after installing GitExtensions-2.50.02-SetupComplete.msi? Please reply with at least a Yes or No.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/32865473-4ff7a0e2-ca31-11e7-9a7d-34f2c23c7f0d.png)

![image](https://user-images.githubusercontent.com/3629489/32865509-732f28d2-ca31-11e7-8475-c554618eed51.png)

![image](https://user-images.githubusercontent.com/3629489/32865593-c27acd38-ca31-11e7-892a-9fb10f89b416.png)

You CANNOT write to a folder in program files.  ONLY admin users have access to those folders.  You have to run it in a folder you have write access to.  Do you get it now?

**Comment by RussKie** [comment]
I don't think it has anything to do with GE. 
ssh-keygen is part of git, which GE simply installs for you. There is no magic to it. You can install git yourself just as well.

Running the file directly is working for me:

![image](https://user-images.githubusercontent.com/4403806/32865731-7b5ff8ba-cab8-11e7-858f-94e4904df5ef.png)

**Comment by vbjay** [comment]
@russkie. I guarantee it is a permission issue. Running the file by double
clicking starts the program with the current directory as a subfolder of
program files for 32 bit. Both program files and program files(x86) have
ntfs permissions that only allow admins write access.

**Comment by mccreeker** [comment]
vbjay, I was never trying to write to Program Files, I never ran the bash command from that folder, and I never stated I was trying to do anything in that folder except test what would happen if I clicked the ssh-keygen.exe (as our IT Desk guy did just to see how Windows treated it).

I tried your manual way and it lets me generate a key, but the problem with that is I have to do a bunch of other steps manually which are already done by ssh-keygen according to git's own documentation: https://git-scm.com/book/en/v2/Git-on-the-Server-Generating-Your-SSH-Public-Key

The problem may not be Git Extensions, but it does install Git Bash and who knows what modifications GE has done to the system if any to cause ssh-keygen to fail? I can't tell yet.

Here's a more explicit description of what I did:

- Installed the latest Git Extensions, which installed Git Bash and Git GUI
- clicked Start > Git > Git Bash which opens in my user folder, which I have read/write access to
- typing ssh-keygen (with or without any options) and hitting Enter shows `bash: /usr/bin/ssh-keygen: Permission denied`
- trying to open the ssh-keygen.exe from within Windows Explorer (just to test if it could be opened outside of Git Bash) showed that screenshot error I uploaded... that doesn't mean I was trying to write to Program Files.

Anyways, I was able to create the keys manually and submit the public key to our server, but I still have to manually do the other things git says ssh-keygen just does automatically to get it to work with my git and the server.

If it's a permissions issue, then what else do we look at besides permissions if they're all the same as the other .exe files that are working in the bin folder? By the way, our IT Desk guy recommended I use TortoiseGit...

**Comment by vbjay** [comment]
Git extensions just embeds git msi.

**Comment by RussKie** [comment]
> The problem may not be Git Extensions, but it does install Git Bash and who knows what modifications GE has done to the system if any to cause ssh-keygen to fail? I can't tell yet.

As I said before, there is no magic to how GE installs git.
The setup has an embedded installer for git, which it runs if you direct it to do so. 
https://github.com/gitextensions/gitextensions/blob/master/Setup/DownloadExternals.cmd#L7-L10
https://github.com/gitextensions/gitextensions/blob/master/Setup/Product.wxs#L914-L915
The setup does not set or modify any permissions on your file system.

You can choose to not to install git as part of GE installation and install it yourself.

> trying to open the ssh-keygen.exe from within Windows Explorer (just to test if it could be opened outside of Git Bash) showed that screenshot error I uploaded... that doesn't mean I was trying to write to Program Files.

I fail to see any link to GE at this point. It is clearly a permission issue.
It could be your antivirus that is blocking it.

> By the way, our IT Desk guy recommended I use TortoiseGit...

It is up to you and your IT Desk guy to choose the tools of your trade.

**Comment by vbjay** [comment]
Try upgrading git. https://git-scm.com/download/win

**Comment by mccreeker** [comment]
I noticed after re-installing Git Extensions that it installs an older version of Git for Windows than is on that git-scm link vbjay posted... is there a reason for that?

Also that git-scm link prompts to download the 64-bit version, but could there be restrictions or incompatibilities in that with Windows 10 or Git Extensions or anything else? Should I be using the 32-bit version of anything here?

**Comment by vbjay** [comment]
Git has been updating rather frequently. When a release is made, we grab
the current version. Use the one that matches your platform.

**Comment by RussKie** [comment]
You can run 32- or 64-bit.
We bundle 32-bit since our users can be running either, and it is impractical to create several different installers.
I run GE on W8, W8.1, W10 and Ubuntu with different git bitness  without any dramas.

**Comment by mccreeker** [comment]
Well I randomly discovered that the LTSB version of Windows 10 (which is what is installed on our computers by default) is apparently blocking ssh-keygen and a bunch of other things, including not having Edge or the Microsoft Store installed, and not letting me install those things without a PowerShell script that someone else already tried and had problems with.

Thanks Satya

**Comment by RussKie** [comment]
That sucks. W10 is coming in our enterprise, now you made me worried...

**Comment by ToNyOyO** [comment]
I'm on Windows 10 Enterprise and getting **this same problem**. 

Our IT Admin logged directly into my computer, and even he can't get around this permissions issue no matter where `ssh-keygen` is called from... 

![Screenshot (3)](https://user-images.githubusercontent.com/12072670/61444874-28452080-a944-11e9-9792-6165398a6e6f.png)
![Screenshot (4)](https://user-images.githubusercontent.com/12072670/61444957-50cd1a80-a944-11e9-9672-daba4f699e50.png)

**Comment by RussKie** [comment]
Can you run under `su`?

**Comment by ToNyOyO** [comment]
> Can you run under `su`?

What's `su`?

**Comment by RussKie** [comment]
su = super user

Looking at your screenshot, why is your path `/usr/bin/`? That path doesn't exist on Windows, it is a Unix path.
