### ISSUE TITLE
Keep pull/fetch default for all repositories, not just one

### ISSUE THREAD

**Issue by BaronZemo** [gitextensions/gitextensions#4159]
This is a feature request to change how the pull/fetch default behavior works.

Currently, I can click the drop down arrow next to the blue down arrow button for fetch and pull and choose "Set the next selection as default". This default only holds true for that current repository. 
![image](https://user-images.githubusercontent.com/24639954/32897376-0633c9a2-caab-11e7-847b-b1585050d32e.png)

I would like for this behavior to hold true for all repositories I visit, as I work in 20 to 40 repositories throughout the week.

I'm running on Windows 7, 64:
GitExtensions 2.50.02
git version 2.12.2.windows.2

**Comment by RussKie** [comment]
Fixed in #5324
