### ISSUE TITLE
Getting the error frequently ;  when i am trying to start using TORTOISE GIT

### ISSUE THREAD

**Issue by shaktiuhc** [gitextensions/gitextensions#4169]
![error](https://user-images.githubusercontent.com/33784789/33127284-d6ec3140-cfad-11e7-8593-f55542413bda.PNG)

**Comment by shaktiuhc** [comment]
What can be the solution to start the Tortoise Git.

**Comment by RussKie** [comment]
The solution would be uninstall Tortoise Git and install Git Extensions.
Then open .gitconfig and fix line 7
