### ISSUE TITLE
Updated .NET to 4.6 but still can't login

### ISSUE THREAD

**Issue by GwapongGamer1997** [gitextensions/gitextensions#4170]
I can't login on github desktop. Everyone says that you need to update your .NET framework to 4.5 to solve this issue. But my .NET framework is already 4.6 but still I can't login. Can somebody please help me. I already tried reinstalling the app. Already tried the whitelisting of the app in the firewall. I also already tried the sfc /scannow but still nothing works. Please help me. T_T

**Comment by vbjay** [comment]
How is this repo related to GitHub desktop?  This is a totally different
product.

**Comment by GwapongGamer1997** [comment]
sorry, i'm still new to github. so where i'm suppose to post this. can you please guide me.

**Comment by vbjay** [comment]
GitHub is a girl hosting site.  When I go https://desktop.github.com and
follow the link to the repo, I am taken to
https://github.com/desktop/desktop.

**Comment by vbjay** [comment]
Please close this issue and create one on that repo after you read their documentation.

**Comment by GwapongGamer1997** [comment]
Ah. ok. Thank you..
