### ISSUE TITLE
Not able to pull or push

### ISSUE THREAD

**Issue by sankar-auditmanager** [gitextensions/gitextensions#4171]
![capture](https://user-images.githubusercontent.com/20434672/33203784-3cb955fa-d127-11e7-8c4d-1f9b780b357d.PNG)
--- GitExtensions2.49.03, Git 2.9.2.windows.1, Microsoft Windows NT 6.1.7601 Service Pack 1

**Comment by gerhardol** [comment]
Seem to be a repo problem or Git setup problem.
The error is reported by Git, not Git Extensions so you should get the same error message with all Git clients

**Comment by RussKie** [comment]
If you run the same command from git bash do you get the same result?

**Comment by sankar-auditmanager** [comment]
Let me explain the scenario.
Actually i was in one repository and changed to another repository and did some changes. Again i swtiched to old repository, this time i am not able to pull/push the changes.

Then i did git clone https://username:password@github.com/username/repository.git in command prompt and solved. Thanks to @gerhardol and @RussKie
