### ISSUE TITLE
Display opening popup in the middle of the screen

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#4172]
**Do you want to request a *feature* or report a *bug*?**
I`m not sure if it is an bug

**What is the current behavior?**
if I click on pull the opening window is over the current window, but often I moved this to a corner and the new window is covert 
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

Maybe the new window can be in the middle of the screen.

**Environment you encounter the issue:**

Win10 Education

- GitExtensions version: latest
- GIT version: latest
- OS version: win10

**Did this work in previous version of GitExtensions (which)?**
nope

Attached pic:

![image](https://user-images.githubusercontent.com/7715216/33222099-d970e21e-d154-11e7-8572-7cb03caf96fa.png)

**Comment by RussKie** [comment]
New opened windows are centered over parents.
Some users have very large monitors, opening windows at the center of the
screen will be an inconsistent UX.
I think it may be against Windows design guidelines too.
