### ISSUE TITLE
"Open local repository" layout broken at high DPI

### ISSUE THREAD

**Issue by Calabonga** [gitextensions/gitextensions#4174]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Wrong windows size

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Set 4k monitor resolution. 
2. Open dialog "Open local repository"

**What is the expected behavior?**
Button [Open] should be visible

**Environment you encounter the issue:**
Windows 10 Pro

- GitExtensions version: 2.50.02
- GIT version: 2.15.0
- OS version: Windows 10 Pro

**Did this work in previous version of GitExtensions (which)?**
I don't know.

![2017-11-25_1216](https://user-images.githubusercontent.com/346209/33227661-7533c704-d1da-11e7-9699-f141054c8872.png)

current resolution 3840 x 2160 (200%)

**Comment by gerhardol** [comment]
Reported in #4099 already (other issues too)

**Comment by RussKie** [comment]
@electronicdreamer has kindly posted a workaround https://github.com/gitextensions/gitextensions/issues/4099#issuecomment-349899698.

**Comment by RussKie** [comment]
Could you please test and confirm the fix: https://ci.appveyor.com/api/buildjobs/4os4712l6lkgakmq/artifacts/GitExtensions-Portable-3.00.00.2511.zip

**Comment by Calabonga** [comment]
Great! I have check some windows, dialogs and buttons, everything looks fine!
https://www.screencast.com/t/URl5rRGDhi

**Comment by Calabonga** [comment]
Thanks

**Comment by RussKie** [comment]
Awesome, thanks

**Comment by RussKie** [comment]
btw, you can post images directly at GH - just paste them alongside the text

**Comment by Calabonga** [comment]
I known about that, and I tried, but some error occurred

**Comment by Calabonga** [comment]
![2018-05-03_1955](https://user-images.githubusercontent.com/346209/39577668-28b0486c-4f0c-11e8-95a1-54b70ccbf78c.png)
New Issue in the new Version
