### ISSUE TITLE
UI doesn't rescale when moving between monitors with different DPI

### ISSUE THREAD

**Issue by enzy** [gitextensions/gitextensions#4176]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

UI scales up to the highest DPI (scale factor) across connected monitors but doesn't rescale to the active monitor where a UI window is present. Windows detects that and rescales the window itself resulting in a whole UI blurred and not very readable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Have 2 monitors with different scaling for ex. 100% and 150%. Open the app and move it between monitors and observe the UI.

**What is the expected behavior?**

When moved to another monitor, respects its scale factor and rescale UI accordingly.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: -
- OS version: Window 10 1709 x64 (17040.1000)

**Did this work in previous version of GitExtensions (which)?**

Don't know.

        

Thanks ❤️

**Comment by drewnoakes** [comment]
Closing in favour of #4822
