### ISSUE TITLE
Can't find merge/diff tool I used to use

### ISSUE THREAD

**Issue by mccreeker** [gitextensions/gitextensions#4177]
**Do you want to request a *feature* or report a *bug*?**
can't find a feature I used to use

**What is the current behavior?**
The buttons "Start mergetool" and "Merge" both just open KDiff. I know this is in Settings but I'm unable to find the tool that "Merge" used which would let me select Local, Base, or Remote versions.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
When I get a merge conflict, the Resolve merge conflicts box pops up; every button there just goes to KDiff.

**What is the expected behavior?**
Clicking the "Merge" button would open another dialog asking to select from Local, Base, or Remote. This was useful when we knew the fix would just be to pick a side and not try to fix the conflicts in KDiff which is cumbersome.

**Environment you encounter the issue:**
Windows 10 64-bit

- GitExtensions version: 2.5.02
- GIT version: 2.13.2.windows.1
- OS version: Windows 10 Enterprise 2016 LTSB

**Did this work in previous version of GitExtensions (which)?**
Yes, 1.9 or 2.2 maybe, don't remember exactly

**Comment by gerhardol** [comment]
It is hard for Git Extension maintainers to remember what tool you used to use.
GE supports many tools in the GUI and any tool can be added. You will have to try different tools to find what you prefer...

You can rightclick on the file in the merge dialog to select local/remote/base.

**Comment by mccreeker** [comment]
Git Extension maintainers don't remember a tool from the Merge button that lets the user click to select Local, Base, or Remote? I'd think they'd be more familiar with a feature from that button, as I know I didn't select a specific tool to use for that.

Can someone please suggest which tool they think that did what I'm asking about? I can try every tool the drop-down suggest, but I'd rather at least hear some suggestions of tools that people here are already familiar with. Thank you.

**Comment by mccreeker** [comment]
OK I'll try right-clicking each file next time, I just thought there was a tool from the Merge button that let me easily do that, as the default KDiff3 still seems less easy than I was using before.

**Comment by RussKie** [comment]
You don't have to use kdiff, you can install a different diffmerge tool. I prefer Perforce p4merge, for example.

**Comment by vbjay** [comment]
We even auto suggest the command line args fir several tools.
