### ISSUE TITLE
Feature: Remove or change old credential.helper setting

### ISSUE THREAD

**Issue by pmme** [gitextensions/gitextensions#4179]
Feature request.

This feature would have GitExtensions offer to fix or undo an old setting that confuses many users and causes issues to be logged on this repo.

Old versions of GitExtensions installed their own copy of GitCredentialWinstore in a sub-folder of the GitExtensions installation and created the global setting `credential.helper` to use that credential helper.

GitExtensions 2.49 and later do not install a credential helper and therefore do not set the global setting `credential.helper`.

The problem then is that the old setting refers to a program that no longer exists and we get #3511 and #3732.

I suggest that GitExtensions could detect when `credential.helper` is set to its previous own copy of GitCredentialWinstore:
`!\"C:\\Program Files (x86)\\GitExtensions\\GitCredentialWinStore\\git-credential-winstore.exe\"`.

The GitExtensions installer could either 
* Offer to remove that setting. Removing that setting would return the user to entering a username and password when pushing.
* Change it to use git's credential helper, wincred.

This is automating the workaround that I wrote in #3511.

GitExtensions version: 2.49 to current, 2.50.02
GIT version: 2.13.3.windows.1
OS version: Windows 7

**Comment by GreenReaper** [comment]
This was confusing - I upgraded Git Extensions and suddenly pushing didn't work! Ended up reinstalling everything git and credential related, which fixed it, but it would have been nice if that hadn't happened.
