### ISSUE TITLE
[bug] how to turn on bottom layout bar?

### ISSUE THREAD

**Issue by huinalam** [gitextensions/gitextensions#4180]
![image](https://user-images.githubusercontent.com/4952867/33367159-e56dc7e6-d530-11e7-9069-45514679e882.png)

Turn off the bottom layout bar.
how to turn on bottom layout bar?

- GitExtensions version: 2.50.02
- GIT version: git version 2.10.2.windows.1
- OS version: windows 10

**Comment by RussKie** [comment]
Click on the right-most button on the toolbar

**Comment by huinalam** [comment]
Thx!

![image](https://user-images.githubusercontent.com/4952867/33420800-4b477c5c-d5f3-11e7-95cb-53d3059a3464.png)
