### ISSUE TITLE
Can not clone or update respositories on github

### ISSUE THREAD

**Issue by mjs513** [gitextensions/gitextensions#4182]
I downloaded and updated to the latest version of git extensions from the help dropdown.  Running 2.50.02 on a windows 10 64 bit pc.  Happened in the previous version as well.  Keep getting the following error:
```
git-remote-https.exe - Entry Point Not Found
The procedure entry point curl-global_sslset could not be located in the dynamic link library C:\Program Files\Git\mingw64\git-core\git-remote-https.exe.
```

Any help would be appreciated.  Thanks
mike

**Comment by mjs513** [comment]
Ok I found a few other issues identified with this same problem and based on that I went ahead and updated git extensions to 2.15.1 and now it works.  

I am going to go ahead and close this

**Comment by RussKie** [comment]
> updated git extensions to 2.15.1 

were you meant to say "updated git to 2.15.1"?
