### ISSUE TITLE
[feature] content diff only between 2 branches with different parents

### ISSUE THREAD

**Issue by nicomeunier** [gitextensions/gitextensions#4184]
**Do you want to request a *feature* or report a *bug*?**  
feature

**Description:**  
How to compare diff of two branches together that have different parents?  
For example:
```
 --A-------B---->
    \       \  
     C---D   E----F
```
I have a branch D and another branch F. I would like to compare only the delta change C..D with E..F without taking in account the delta change A..B. Is it possible to do that easily from UI?

Currently, I have only find the way see delta change D..F (clicking on D, and after on F with Ctrl modifier) but this is including the delta change A..B too.

Thanks for your help if this is already implemented,
Nico

**Comment by vbjay** [comment]
Click first commit. Ctrl click second commit. Look at diff tab.

**Comment by nicomeunier** [comment]
Thanks for your answer @vbjay but it's not exactly what I mean, because this diff is also showing unrelated changes because parents are not common. Hard to explain, so I put an example of what I'm looking for ;)

**Comment by gerhardol** [comment]
This is not possible. I cannot see how it can be implemented at all. You will have make an example how you would select the different revisions, with git commands and maybe even mockups. (just comparing c..d to e..f will not work as I see it, this is not how git-diff compares).

**Comment by jbialobr** [comment]
The best you can do is to create a temp barnch X pointing to D, then rebase X on B and compare X with F.
Notice that rebasing may require resolving conflicts manually and this the main reason why the whole process can not be done automagically.
