### ISSUE TITLE
First parent view graph

### ISSUE THREAD

**Issue by jeroenlandheer** [gitextensions/gitextensions#4187]
I think this doesn't look like it should... 

![image](https://user-images.githubusercontent.com/3246548/33516897-6f3e1fac-d77a-11e7-9803-ac6508c4e985.png)

(**Update:** Note that this is a 'first-parent' view)

**Comment by jbialobr** [comment]
Would you like us to guess how you think it should look like?

**Comment by jeroenlandheer** [comment]
@jbialobr Something like this: (Screenshot from TFS)

![image](https://user-images.githubusercontent.com/3246548/33518573-3865178e-d797-11e7-9525-df3a25416805.png)

Basically, it is just a straight line, without all the lines on the side.

**Comment by vbjay** [comment]
I would like Git commit handling for $400.
Jay. Your answer.  A way to put commits on top of another branch.

Alex, What is git rebase?

**Comment by gerhardol** [comment]
The graph seem to present the git information correctly: The commit you show have two parents but one of them is missing. TFS just not draws the line if the parent revision is missing in the repository. ((The merged branches are deleted I assume, a squashed commit should not add a parent?)

The "non-existing" parents could be hidden in GE too I assume.

**Comment by RussKie** [comment]
what do you get when you run `git log --graph --abbrev-commit --decorate --oneline`?

**Comment by jeroenlandheer** [comment]
@vbjay If you think this git repo looks like a railroad yard, you're mistaken. The idea of a 'show first parents' view is that you only see the first parent of a commit, which in this case leads to a straight line. All those lines right of that main line are irrelevant and shouldn't be shown. 

@RussKie that would be this:  (with --first-parent) 

* 292cf1e (HEAD -> features/artikelen, origin/features/artikelen) Merge branch 'master' into features/artikelen
* 7c663ae technieken en artikel groepen
* 701bca4 Artikel referenties
* 0577045 #2080
* e2223be Guid.Empty bij het toevoegen van telefoonnummers
* 5014b76 Aanpassingen IndexModel Artikel controller Wijzigingen Gulp
* 9ae2c93 Merged PR 306: Merge features/kunstenaars to master
* cebc594 Merged PR 305: Merge features/kunstenaars to master
* d44fa0b Merged PR 304: Debiteuren en crediteuren
* 982d523 Merged PR 303: Merge features/kunstenaars to master
* da6d48b Merged PR 302: Error feedback
* f8bba27 Merged PR 301: Steuntabellen
* 01ab779 Merged PR 294: Merge wijzigingen/ronald to master
* d5413bf Merged PR 291: Merge features/webapi to master
* 050a702 Merged PR 273: Merge features/webapi to master
* 9e598c5 Merged PR 271: Merge features/webapi to master
* 64463fc Merged PR 270: Merge features/repositories to master
* a78bd4b Merged PR 265: Merge features/repositories to master
* 950699a Merged PR 264: ArtInfo Data Repositories
* 2d27541 Merged PR 263: Merge features/repositories to master
* addb677 Merged PR 262: Merge features/businesslogic to master
* b21291e Merged PR 261: Merge features/businesslogic to master
* c76a7aa Merged PR 260: Opzet voor Repo's
* 7e385c2 Merged PR 254: Merge features/repositories to master
* 099ccec Merged PR 248: Merge setup/solution to master
* 04361f6 Initial Commit

**Comment by Akarachudra** [comment]
I do not remember this bug in older versions. The problem occurred after updating to 2.50. In 2.48.05 it looks correctly.

**Comment by RussKie** [comment]
The bug isn't present in v3. Haven't checked v2.51.
