### ISSUE TITLE
Fetch (and, possibly, pull) from a set of repositories with a single action

### ISSUE THREAD

**Issue by ignacioerrico** [gitextensions/gitextensions#4201]
**Feature request**: provide a way to fetch (and, possibly, pull) from a set of repositories with a single action. (By single action I mean clicking a single button or by means of a single keystroke.)

**Current behavior**: it is only possible to fetch/pull from the repository you have open. If your project consists of a number of interrelated repositories, you have to update (i.e., fetch/pull from) one by one.

**Current workaround**: it is possible to achieve the effect of the desired feature from the command line [as explained here](https://stackoverflow.com/a/12495234).

(For what it's worth, I'm using version 2.50.02 on Windows 7 and Windows 10.)

**Comment by vbjay** [comment]
Are you using submodules?

**Comment by vbjay** [comment]
You can go to settings and create a script. We even support powershell
scripts. You can make it a menu option on the revision grid.

**Comment by pmiossec** [comment]
>You can make it a menu option on the revision grid.

Yes, script is your solution.
Creating a git alias that you will call in GitExtensions is even better. 
 You can even make it a button with its own icon in the toolbar. That should solve your problem.

As a non standard request, I don't think that it should be implemented in GitExtensions...

**Comment by RussKie** [comment]
I feel that the suggestions above should satisfy the request and provide required behavior.
Closing now.

**Comment by ignacioerrico** [comment]
Thanks for the prompt reply and for explaining how to implement it with the existing functionality. I like that!

I guess it doesn't matter now, but just to reply to @vbjay: no, I'm not using submodules. Your suggestion is exactly what I wanted. I just hadn't thought of that. Thanks!
