### ISSUE TITLE
Jenkins build server integration: support for multi pipeline and wildcards 

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4202]
Feature request

Jenkins integration currently works for one or more fixed name configurations. The names have to be matching completely.
This is inconvenient when there are many jobs (I have over 100), there should be some wildcard possibility. This of course depends on Jenkins support. The repo name is often used, just a <repo> variable would be an improvement.
Edit: Jenkins job names can be queried using XPath so wildcards will require an additional step to query available jobs.

Another problem is that multi pipeline builds are not supported. They have a path like
/job/name/job/branch/
The branch need to be supported as a variable here too, so similar to above
(just hardcoding master does not work, is there a check for '/'?)

Nice additions by @jbialobr lately though

- GitExtensions version: 2.50.02, master

**Comment by gerhardol** [comment]
Will submit a patch that allows variables, something like the following:
 * REPO_SHORTNAME: the name of the git project (gitextensions.git would be gitextensions). This allows for a global configuration
 * activebranch: certain named can be hardcoded like "%REPO%/job/master, this would allow for the status of the current checkedout branch too. Long term, there should be an option to use the name of the tracked branch

I have some stability problems with the Jenkins integration though, looking into those exceptions first.

**Comment by RussKie** [comment]
Good idea
I would only ask for consistency in variable names across multiple plugins
we have.

On 13/12/2017 12:54 PM, "Gerhard Olsson" <notifications@github.com> wrote:

Will submit a patch that allows variables, something like the following:

   - REPO_SHORTNAME: the name of the git project (gitextensions.git would
   be gitextensions). This allows for a global configuration
   - activebranch: certain named can be hardcoded like "%REPO%/job/master,
   this would allow for the status of the current checkedout branch too. Long
   term, there should be an option to use the name of the tracked branch

I have some stability problems with the Jenkins integration though, looking
into those exceptions first.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4202#issuecomment-351234408>,
or mute the thread

**Comment by dalee-bis** [comment]
+1 for multi-branch pipeline support.

**Comment by gerhardol** [comment]
I have something that works OK. It turned out that multi-branch pipeline was the smallest problem (so activebranch variable is not needed), the stability in the plugin itself has been the biggest issue. There is also a question how to handle the variable. I would like to add RepoShortname() support to GitModule(), but maybe githob user (or project key in Bitbucket) should be handled in a similar way (used by AppVeyor).

**Comment by RussKie** [comment]
@gerhardol  before you spend to much time and effort, could you write down a proposal for the new functionality and variables you want to use. So we can discuss and align with existing variable schemas we have.

**Comment by gerhardol** [comment]
Variables are the simple part. A commit here (that I would submit as a PR if it was not that 2.51 should have a release branch first).
https://github.com/gerhardol/gitextensions/tree/feature/n4202-buildserver-variables

This adds the variables %REPO_SHORTNAME_U% and %REPO_SHORTNAME% as described above.
(This will avoid configuring about 20 (sub) projects manually in the 1-5 clones I have of each of them. OK, I do not care about all.) 
The active branch variable is not needed in itself.

--
Possible enhancements related to variables:
 * Shorten the name, long command line. But REPO_NAME could be misleading
 * Variable for github user in remote url (like gerhardol in github.com/gerhardol/gitextensions.git)
 * Variable for "last part of local directory"
 * Set the variable as default in settings?

--
For Jenkins, some attribute is needed to mark multipipeline support. This could be detected automatically, but this will cause an additional network access (one of the problem with the plugin now).

--
Jenkins plugin has stability problems now. By design it generates exceptions when for instance a project is not found. It creates one task to fetch the builds, one each for each build. This gives problems with hundreds of builds (as multibranch pipeline can give). This can be done with one optimized call instead. (Need to figure out how to best handle ongoing builds.)

--
It would be nice to show several build resuls for one commit, like both windows/mono status (at least if they were on the same build server). A completely different enhancement.

**Comment by dalee-bis** [comment]
So I was looking into this for a while because I couldn't get it to work but I've managed to figure it out. For anyone who comes across this, multibranch pipelines require a `?m` suffix on the project name in GitExtensions.

**Comment by gerhardol** [comment]
Yes, this needs to be documented somewhere. I had planned to do that together with #4280, but that will not be included in 2.51.

Probably adding a note to http://git-extensions-documentation.readthedocs.io/en/latest/settings.html?highlight=jenkins#build-server-integration-jenkins-project-name

**Comment by dalee-bis** [comment]
So I've been using this for a day or so now. So far it seems to be working well. The only issue seems to be that the "Build Report" tab is empty (No content at all, not even a failed to load page).

Not sure if you want to create a separate issue for this or track it here.

**Comment by gerhardol** [comment]
> Not sure if you want to create a separate issue for this or track it here.

That would be a separate issue. This feature has not (intentionally) changed anything on how the build tab is displayed (well, a correction for an exception was included).

As the build report uses the .NET WebBrowser control, one possibility is that it is outdated and cannot show the build report. On Win7 I get warnings but not on Win10.

**Comment by vbjay** [comment]
Thoughts?  http://cefsharp.github.io/

**Comment by gerhardol** [comment]
> Thoughts?

I have not looked at this solution, but major external dependencies can cause migration problems - like the mono compatibility has been slowing down development (I like the idea though).

The tab is not so important for me, the status in the grid is. I was thinking more to provide a link to the build, for instance double clicking the column.

I will check feedback from colleagues when 2.51 is out before deciding if I want to take this further myself.

**Comment by vbjay** [comment]
My thoughts are that mono is going to get dumped. This runs chromium out of
process. If we ever did go cross platform and chromium is supported on that
environment, then we are set. I frankly hate hosting it in my process.

**Comment by RussKie** [comment]
I wouldn't want to introduce any more dependencies unless it is absolutely
essential. We already have a bucket load....

**Comment by RussKie** [comment]
> As the build report uses the .NET WebBrowser control, one possibility is
that it is outdated and cannot show the build report. On Win7 I get
warnings but not on Win10.

What kind of warnings?

**Comment by gerhardol** [comment]
> What kind of warnings?

Document mode something. Not in front of a Win7 computer for some days

**Comment by gerhardol** [comment]
![image](https://user-images.githubusercontent.com/6248932/35522307-3db7e498-051c-11e8-9948-ed25ea036fec.png)

I have looked at this without finding anything obvious.

**Comment by vbjay** [comment]
https://msdn.microsoft.com/en-us/library/jj676915(v=vs.85).aspx

**Comment by vbjay** [comment]
https://blogs.msdn.microsoft.com/patricka/2015/01/12/controlling-webbrowser-control-compatibility/

**Comment by RussKie** [comment]
So it is working on W10 but not W7?
What about W8?

Can we say this is Win7 specific issue?
If so, I don't feel it is completely justified adding overhead for an OS
which reaching its EOL. Perhaps we can add a warning and a link to the post
about the registry tweaks....
Build server integration is not a core but a nice-to-have feature.

**Comment by gerhardol** [comment]
I have tried some of the workarounds (time consuming, as I have to build on other machines that I can test on, every new test adds a day). No test on Win8.

Someone with Win8 can test with the public Jenkins servers listed in #4279 
This can of course be related to Jenkins version too

I do not find the tab very important, but really apreciates the column. I would prefer an easy way to copy the URL instead of the tab.

**Comment by RussKie** [comment]
I'll try to find some time to test it on W8

**Comment by MikeDimmickMnetics** [comment]
@gerhardol Could the Intranet Zone be involved here?

If Internet Explorer detects that your site is in the Intranet Zone, and the 'Turn on Compatibility Mode for Intranet Sites' option is enabled (which it is by default), then it will emulate IE7. Since IE7, the Intranet Zone is enabled by default only if it thinks you're on a managed network - see [The Intranet Zone - IEInternals Blog](https://blogs.msdn.microsoft.com/ieinternals/2012/06/05/the-intranet-zone/) for more details. Usually, the Intranet Zone is detected for URLs that contain no dots in the host part.

It may be that your Windows 10 machine is somehow configured differently from your Windows 7 machine, or that you're using a different URL (host-only versus fully-qualified domain name) between the two machines. It's probably best to use the FQDN for the Jenkins server to ensure that you're not hitting the Intranet Zone.

**Comment by gerhardol** [comment]
@MikeDimmickMnetics
Yes, Intranet Zone could be the problem too, it is enabled for the Jenkins URL.

The Win10 PC is at home without zones, the Win7 is not home, they are completely differently setup. The Internet settings are disabled for me.

The Win7 PC is supposed to be migrated to Win10 soon, I would like to try this on one of the migration machines but have not priority for that.
