### ISSUE TITLE
BitBucket plugin is broken

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4204]
Bug in the BitBucket server plugin.

The data is always empty also if a BB server is configured.
(I did not see outgoing requests in a quick test)
Pressing Create causes null exceptions.

**What is the expected behavior?**
If not BB configured, no exception or plugin grayed out
If BB configured, managing PRs from GE should be working. Unless someone got it working, the plugin should be disabled.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.2, master

**Did this work in previous version of GitExtensions (which)?**
Not that I know of.

**Comment by gerhardol** [comment]
I have a patch for getting the plugin working too, awaiting merge of #4210 first

**Comment by gerhardol** [comment]
The submitted and merged patches makes it possible to submitt PRs (but not setting reviewers) and to view open PRs (I get XCSR error for merge/approve).

The following improvements could be done:
* Display a link to Bitbucker server for submitting as well as viewing PRs. This makes it easy to go from the code to the PRs
* Switch order of view and create tabs (view should be more common)
* Check that the Bitbucket server is http (that the user has not entered the ssh address)

* Fix XCSR error to approve and merge
* Offer the different merge/squash/rebase strategies as available in Bitbucket as well as delete source branch
* Offer rebase PR branch, as available in Gerrit
* Retrieve default reviewers and all users (maybe on request only, cache information between runs too?)
* Comment on PRs

* Per line code commenting as in the web ui (not likely, not sure if it is possible)

The first group is relative simple and should be done, the second has parts that are doable but I do not know if they are worth it, the  third is overkill.

@RussKie As the submitted PRs are merged, I suggest that this issue is tagged 2.51 and closed. (The first group will then be done in a separate issue.)

**Comment by RussKie** [comment]
What is "XCSR"?

**Comment by gerhardol** [comment]
> What is "XCSR"?

Some kind of security check, I have not looked into the details.

**Comment by RussKie** [comment]
Do you mean cross site scripting (xss)?

On 20/12/2017 12:48 AM, "Gerhard Olsson" <notifications@github.com> wrote:

What is "XCSR"?

Some kind of security check, I have not looked into the details.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4204#issuecomment-352755739>,
or mute the thread

**Comment by gerhardol** [comment]
Probably certificate signing request - it was just the message I got when trying to execute. Maybe this is related to the server where I tested.

**Comment by gerhardol** [comment]
@RussKie 
I suggest tagging with 2.51RC1 and closing

**Comment by gerhardol** [comment]
The error is XSRF and I will submit a patch.
https://confluence.atlassian.com/cloudkb/xsrf-check-failed-when-calling-cloud-apis-826874382.html
