### ISSUE TITLE
"Do you want to add a tracking reference?" dialog appears on different screen

### ISSUE THREAD

**Issue by loop-evgeny** [gitextensions/gitextensions#4205]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** When I have Git Extensions open on my secondary screen and push a new branch the dialog asking "The branch ... does not haev a tracking reference.  Do you want to add a tracking reference to ...?" appears on my primary screen, which is annoying. (The previous dialog asking "The branch you are about to push seems to be a new branch for the remote. Are you sure you want to push this branch?" appears on the same screen as the main Git Extensions window, as expected.)

This happens most of the time, but not all the time. For example, If I minimise all windows with WinKey+D and then restore Git Extensions this doesn't happen - the dialog then appears on the secondary screen, as expected.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

In a dual monitor setup have Git Extensions open and maximised on the secondary screen. Create a new branch and push it. Say "Yes" to creating a new branch in the remote.

**What is the expected behavior?** All dialogs appear on the same screen as the main Git Extensions window.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.15.0.windows.1
- OS version: Windows 7 Pro N SP1

**Did this work in previous version of GitExtensions (which)?** Don't know.

**Comment by RussKie** [comment]
Unfortunately I am unable to reproduce it on Win8. I will try few other machines to see if I can repro it there...

Besides I normally have the confirmation dialog turned off anyway.

**Comment by eviltobz** [comment]
I'm getting a similar problem and it happens with any form that i open away from the main window, including the commit page, and I think that the positioning of the screens is important for this. I have 4 displays in a T shape. my laptop's display is at the bottom, and then 3 displays in a line above it. The laptop is my primary display and has the windows taskbar jobby on it. If i have the main program on the lappy and open a commit window it opens up approximately centred over the top. If i move the main window up to the central top monitor (which is configured directly above the lappy) and open the commit window it comes up on the lappy's display, approximately centred on the X axis to the main page.

This really becomes a problem when i have my git window on one of the side screens. I'll open the commit page (just as a note, the commit is an easy one to do, but it's similar with pretty much all other windows opening up too) and again it'll try to open it up centred on the X axis, but vertically as if on the primary screen. This means that forms are being opened up entirely off the display. The commit window isn't toooooo bad in this situation as it is at least possible to do the "Alt+space, m, cursor-keys" combo to move it back into the visible area. However, I think that some of the lesser dialogs that pop-up don't have this option (for example, the main pull form has the Alt+space menu, but the Process window that it opens when doing the pull doesn't), at which point it is very difficult to do anything as there is a modal window that you can't interact with.

**Comment by RussKie** [comment]
As a thought, does Shift+Win key+Left/Right Arrow help?

**Comment by eviltobz** [comment]
Hmmm, that does seem to work, provided you have the windows snapping stuff turned on. Personally, I have that turned off as i find it utterly detestable when i'm trying to drag a window to the side of my screen and windows decides to resize it underneath me. Grrrr! With the setting disabled, it stops that key combo from working. I've been using a different app called WinLister that'll let you recentre windows as a workaround to get it visible again, so there are other approaches, but obviously it's not ideal to have to do any of them.

**Comment by RussKie** [comment]
It is a mere workaround.
Unfortunately we don't a coherent support for multi screen setups
