### ISSUE TITLE
Github plugin 'View Pull Requests' screen errors

### ISSUE THREAD

**Issue by CDAGaming** [gitextensions/gitextensions#4212]
**Do you want to request a *feature* or report a *bug*?**
Reporting Bug.

**What is the current behavior?**
On a Fork of a Repo, when going to the 'View Pull Requests' Menu, it doesn't allow me to change the Repository (In this case to target the upstream Repo and gives 2 errors):
Error 1: Failed to Fetch Pull Data. Object Reference not set to an instance of an object.
Error 2: On exiting, it displays a System.NullReferenceException Error with the same message as above.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
To Reproduce, Create a Fork of a Repo, clone it then use the 'View Pull Requests' Option in git Extensions.

**What is the expected behavior?**
To be able to view the Pull Requests and Change the Repository.

**Environment you encounter the issue:**
Windows 10 x64
- GitExtensions version: 2.50.02
- GIT version: 2.15.1
- OS version: windows 10 x64 Build 17040

**Did this work in previous version of GitExtensions (which)?**
No, this issue has shown up at times in earlier releases.

**Comment by RussKie** [comment]
Just to confirm this is to do with Github extension

**Comment by CDAGaming** [comment]
Yes, this is the Menu accessible by Clicking Github>View Pull Requests via the Top Bar.

**Comment by gerhardol** [comment]
Occurs for me too (both source and 2.50.02). Git.hub.dll does not seem to get loaded so 'repo' is null which causes the issues.

**Comment by RussKie** [comment]
Check that necessary binding redirects are configured. For example, an assembly maybe expecting Json.Net v6.0.0 but we are building against v10. Few other things failed because of similar issues....

**Comment by CDAGaming** [comment]
Oddly for me, this issue seems to have stopped occurring for me for now
 (Made a private build with Updating all dependencies which may have fixed it somehow but can't verify)

**Comment by M1chaelTran** [comment]
Okay, I think I have figured out why or at least it works for me now.
Here's what I did to get it to work.
1. Go into Settings > Plugins > Github
2. Delete the existing OAuth Token > OK to save change (If it isn't set then that's also an issue.)
3. Now select Github from the Plugins menu (next to the Github menu)
![image](https://user-images.githubusercontent.com/30276/38163680-e556ca32-3543-11e8-84a4-1507a31a166d.png)
4. It should says "You already have an OAth token..."
![image](https://user-images.githubusercontent.com/30276/38163664-9c10cbd4-3543-11e8-951e-2e9347d79994.png)
5. Now try opening the "View Pull Requests" from the Github menu again.

Hoped that works for you too.

**Comment by RussKie** [comment]
Thank you
Obviously there is a significant room for improvement here in terms of usability.

**Comment by Ian1971** [comment]
I have the same above issue, but the workaround does not work.

**Comment by CDAGaming** [comment]
Bumped as Issue is still present, though occurring less often

**Comment by RussKie** [comment]
Pull requests are welcome

**Comment by CDAGaming** [comment]
Closing as inactive.
