### ISSUE TITLE
Commands are duplicated in GE Gitcommand log

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4213]
A bug, seen in the latest versions, probably appears in all versions.
Some commands appear twice in the log, same start time but occasionally a longer run time.

From what I have seen, the issue is in the logging adding the command twice, GE is only executing it once.

This is discussed in #4069 https://github.com/gitextensions/gitextensions/issues/4069#issuecomment-348831453
This issue is opened to track a patch to improve the logging.

- GitExtensions version: 2.50.02, master
- GIT version: 2.15.1
- OS version: Win10, Win7

**Did this work in previous version of GitExtensions (which)?**
I have not looked for this in earlier versions, the code in question is not changed for a long time though.

**Comment by gerhardol** [comment]
I tried to debug why the same command seem to be logged two times. It does not seem to be called twice, it seems to be that the logger in GitCommandHelpers.cs StartProcess fires Exited twice, with the same information.

I cannot separate the "second" call to logging in a safe way and will submit a PR to mark the "likely duplicate" only. In best scenario, the issue/PR will trigger someone to find a solution.
If not accepted, there is still some documentation. If accepted, there is a link to this issue for next person to investigating.

**Comment by vbjay** [comment]
Could you use a cache of the process the id?

**Comment by gerhardol** [comment]
> Could you use a cache of the process the id?

No, Id is not defined for Exited: System.InvalidOperationException
