### ISSUE TITLE
Bitbucket Server plugin enhancements

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4229]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Bitbucket Server plugin in 2.50.02 is not working at all. #4204 with related PRs restores the implemented functionality (unsure when it was lost), but it could be improved.

**What is the expected behavior?**

Some possible enhancements:

Relative simple and useful:
 * Display a link to Bitbucker server for submitting as well as viewing PRs. This makes it easy to go from the code to the PRs
 * Select branches in PRs to merge in the GUI, open FormDiff?
 * Switch order of view and create tabs (view should be more common)
 * Check that the Bitbucket server is http (that the user has not entered the ssh address)
 * Fix XSRF error to approve and merge
 * Offer the different merge/squash/rebase strategies as available in Bitbucket as well as delete source branch

More work required:
 *   Offer rebase PR branch, as available in Gerrit
 *   Retrieve default reviewers and all users (maybe on request only, cache information between runs too?  All users may require downloading, could be heavy)
 *   Comment on PRs
 *   Per line code commenting as in the web ui (not likely, not sure if it is possible)

**Comment by RussKie** [comment]
> All users may require downloading, could be heavy

This could be configurable. Bonus, if users could do it from the same screen rather than going to settings screens.

**Comment by gerhardol** [comment]
The current REST API implementation is incomplete and are to some extent using depreciated APIs (for instance GetHeadCommitRequest() uses refs/heads references).
I have looked into replacing the REST API implementation with a standard implementation.
The best candidate I found is https://github.com/jlouros/StashApiCSharp
Available as nuget package or submodule.
However, the implementation misses some capabilities used in the current implementation, so it is not a quick replacement.

I plan to submit a few changes, then probably put this on hold. Just be able to view PRs, compare, approve and get the web URL to them is probably what I will use anyway.

**Comment by RussKie** [comment]
It would be good, if we can get away without adding extra dependencies

**Comment by gerhardol** [comment]
> It would be good, if we can get away without adding extra dependencies

Adding dependencies: Problems to step versions for the complete program.
However, there are higher probability that the depreciated functionality is fixed in the external package...

But to be clear, I do not plan to make bigger changes, just writing down findings.

**Comment by gerhardol** [comment]
Removing 3.0 milestone - no changes currently planned
