### ISSUE TITLE
Command Log: logs may be lost

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4231]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Seen in discussion of #4214 
When entering a counter to track if GE logs duplicates, it seems like some commands are not logged at all.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Reproducing requires code modifications

**What is the expected behavior?**
All commands logged
Maybe the sequence number should be added to the log.

**Environment you encounter the issue:**

- GitExtensions version: current master
- GIT version: 2.15.1
- OS version: Win 7/10

**Did this work in previous version of GitExtensions (which)?**
Not tested, likely the same

**Comment by drewnoakes** [comment]
Once a few PRs are cleared up I'll submit some work that should address this. Ultimately all git process executions will pass through one gateway and the logging will be consolidated at that point.

We can capture a bit more information for the log too.

**Comment by gerhardol** [comment]
This was likely due to commands commands were logged when they were finished, not when they were started. Closing due to enhancements in #4756.
