### ISSUE TITLE
[macOS] Try to compile GE on Sierra

### ISSUE THREAD

**Issue by gpongelli** [gitextensions/gitextensions#4232]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Xamarin cannot compile GE.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- install MonoFramework-MDK-5.4.1.6.macos10.xamarin.universal.pkg package
- install Xamarin IDE
- open GitExtensionsMono.sln
- update NuGEt packages (only the first time)
- try to build

Seven error of this kind
![immagine](https://user-images.githubusercontent.com/842026/33967765-21105586-e065-11e7-845b-37d8ab77c6c1.png)

Another error is on ConEmuWinForm.csproj: 

> ConEmuWinForm.csproj could not import "$(SolutionDir).nuget\NuGet.targets"

**What is the expected behavior?**
Xamarin builds GE 

**Environment you encounter the issue:**
- GitExtensions version: HEAD master
- GIT version: 2.13.1
- OS version: macOs Sierra

**Did this work in previous version of GitExtensions (which)?**
Not known

**Comment by RussKie** [comment]
I can compile everything (including the GPG changes) on Ubuntu in Jetbrains Rider.
I think both issues are IDE-related.

PS: I feel sorry for you needing to do it on a Mac... I tried developing and running GE on a Mac but it was such a painful experience that I just installed Parallels, Windows and Ubuntu.
Mono Winforms on Mac is horribly slow and unstable, significantly less stable than on *nix.

**Comment by RussKie** [comment]
Also this isn't something I will be able to help you with, as it isn't on our strategic roadmap.
In future versions we will be winding down support for Mono, as we have no active contribution from non-Windows users and Mono Winform is a dead tech from 2004....

**Comment by RussKie** [comment]
Btw on Mac I was compiling in VS for Mac

**Comment by gpongelli** [comment]
It was just a try :)

I didn’t know about VS for Mac, maybe I’ll give it a try.

I do not follow Mono development, personally I prefer other multiplatform framework and GUI (boost and QT above all).

Knowing the roadmap, we can forget this issue.

**Comment by RussKie** [comment]
https://www.visualstudio.com/vs/visual-studio-mac/
It is a re-badged Xamarin Studio, which is itself a re-badged version of Monodevelop... Same ugly thing.
I found Jetbrains Rider much more usable, still nowhere near as good as VS, but good enough.

**Comment by gpongelli** [comment]
I'll give VS for Mac a try.
Jetbrains Rider is 30 day trial, then requires a paid license.

**Comment by gpongelli** [comment]
Same errors on VS for Mac.
It's sad to say, but GE on Mac cannot work.
I've tried on Ubuntu with free Mono IDE (not JetBrain) but GE is not as usable as in Windows.

Will Mono code be removed from GE ?

**Comment by RussKie** [comment]
I wouldn't use GE on Mac, on Linux it is usable, though not as smooth as on
Windows. We pretty much need to rewrite GE to provide a good x-plat UX.....

In coming days I will post my proposal/vision for V3, so we can discuss
what future holds.

**Comment by gpongelli** [comment]
It’s not only a UX / UI problem when trying to build a cross platform app ;)

**Comment by RussKie** [comment]
Is there a particular reason you're trying to compile on a mac?
Have you tried installing mono and just running GE? Just grab the latest dev artifact and run https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by gpongelli** [comment]
No particular reason. 
It was only an attempt.

I have not tried to run it because this was not what I wanted to do.
