### ISSUE TITLE
puttykeyfile option is not written to config during clone

### ISSUE THREAD

**Issue by leak** [gitextensions/gitextensions#4235]
**Do you want to request a *feature* or report a *bug*?**

Feature?

**What is the current behavior?**

When using the "GitExt Clone" context menu function from Explorer and loading a SSH key, the path to the key is not saved in the git config. Instead you have to go to the "Remote repository" settings, browse for the key again and save it as a second step.

**What is the expected behavior?**

The "puttykeyfile" setting should be persistet in git config during intial clone.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.14.1.windows.1
- OS version: win10 x64 1709

**Did this work in previous version of GitExtensions (which)?**

Not that i know.

**Comment by vbjay** [comment]
It is not a git but git extensions feature to use putty. That's how it
works. When you set up the remote, you specify the putty key. When you
save, the path is stored.  If you attempt to push or pull or other actions
that require the key to be loaded, a dialog cones up and gas the option to
load the key and then retry.

**Comment by vbjay** [comment]
Sorry. Missed the clone part. So if putty was used in cloning, you want the remote that is generated to have the file path of the key used in the clone.

**Comment by leak** [comment]
@vbjay Exactly

**Comment by vbjay** [comment]
Pull Requests are welcome.
