### ISSUE TITLE
Lost all my files

### ISSUE THREAD

**Issue by ShwetaKhera** [gitextensions/gitextensions#4240]
I staged my files , then unstaged them, hit cancel,hit refresh changes and I lost all my files. Please tell me how I can get my files back.

**Comment by vbjay** [comment]
Staging/unstaging doesn't affect the working directory. Your files are
still there unless you reset the files.
http://www.vogella.com/tutorials/Git/article.html

**Comment by ShwetaKhera** [comment]
Yes but i did reset the changes. And there are no files in the folder.

**Comment by pmiossec** [comment]
That could help you:

https://stackoverflow.com/questions/11094968/in-git-how-can-i-recover-a-staged-file-that-was-reverted-prior-to-committing

https://edwardthomson.com/blog/introducing_git_recover.html

**Comment by ShwetaKhera** [comment]
My android studio files were deleted and i recovered them from android studio's local history. Thank you for you suggestions @pmiossec @vbjay
