### ISSUE TITLE
Diff tab selected when GE starts up

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4242]
**Do you want to request a *feature* or report a *bug*?**
regression in master

**What is the current behavior?**
Whenever GE starts up, it consistently selects "Diff" tab instead of "Commit"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- set the head to origin/master
- build and launch in VS
- observe the Diff tab selected

![image](https://user-images.githubusercontent.com/4403806/34077121-fa6008e0-e34e-11e7-8323-53513e8d2782.png)

**What is the expected behavior?**
- Commit tab is selected

**Environment you encounter the issue:**
Current master branch

**Did this work in previous version of GitExtensions (which)?**
Yes

@gerhardol could you have a look please

**Comment by gerhardol** [comment]
This occurs due to the RevisionGrid is updated by a timer and the timer is firing while the form is loading before a revision is changed. When RevisionGridSelectionChanged first runs, there is no revision and the CommitTab is hidden.
Similar will happen if you select normal-artificial-normal. 

This is the way I want it to work. It is the diff that I find important per selection. The behavior is also consistent for normal vs artificial commits.

To have the functionality back to 2.50.02 and still not see an empty tab for artificial commits, I see no simple solution. The timer handling in RevisionGrid is hard to get rid of. 

If not switching back to Commit after artificial is OK, then going back to something similar to before a correction for empty repositories #4208, hiding the ugly empty commit tab.

![image](https://user-images.githubusercontent.com/6248932/34080808-1dba416c-e344-11e7-8b65-7bfbbc0245f4.png)

**Comment by RussKie** [comment]
I understand the mechanics but I still think it provides an unexpected UX. I can foresee issues raised about this.
Can we perhaps devise some sort of a flag which prevents from switching the first time we open the app?

**Comment by RussKie** [comment]
Maybe don't bind `CommitInfoTabControl.SelectedIndexChanged` until the first non-artificial revision is selected...

**Comment by jbialobr** [comment]
Perhaps the commit info tab should not be hidden at all.

**Comment by gerhardol** [comment]
The GPG tab is now the default (if enabled). It seems like it mess up the Diff tab layout too.
That I consider to be a bug (even if the Diff is a feature!)

> Perhaps the commit info tab should not be hidden at all.

Then the artificial commits will be empty. Can be done better than in 2.51 for sure.
Similar solution should be done for Tree tab (also for artificial commits), build info etc.
I have not seen any way to 'disable' tabs, which would be a natural solution.

Maybe setting the active tab when creating the Browse form is sufficient. normal-artificial-normal will still select Diff tab
 
A 'complete' solution would be to remember the last manually selected tab and select that if it is available when selecting commits.

**Comment by RussKie** [comment]
> The GPG tab is now the default (if enabled). It seems like it mess up the
Diff tab layout too.

What do you mean?

**Comment by vbjay** [comment]
Ok. The real problem is that artificial commits should still display commit info.  Fake some things. Put an icon/label saying, this is an artificial commit. or something like it.  Stop trying to monkey with the tabs and make artificial commits show what is needed.

**Comment by RussKie** [comment]
I had the same thought occur to me, you beat me to it

**Comment by gerhardol** [comment]
> What do you mean?

Yesterday, I got some weird offset in Diff tab after viewing the gpg tab. Not so today.

I will submit something to remember the last selected tab. That is less work than setting up special handling for filling the tabs.

**Comment by vbjay** [comment]
Do the extra work.  They may be artificial commits. However, they are still
commits.  Make the gui show that it is not a real commit.  Then don't worry
about the tabs.  You won't be hiding or showing them after you make it show
commit info.

**Comment by RussKie** [comment]
How about we stop hiding tabs?

**Comment by gerhardol** [comment]
There is no visual clue that the tabs have no useful data. The tab contents can be disabled, but no simple way for the tab "header".

**Comment by vbjay** [comment]
Not yet.  Build it.  

''' c#
If(isArtificial)
{...}
else
{...}
'''
Make it show useful data.  Make the commit author the current info as if a commit were to happen.  Make the commit date, Now.  Get it?

**Comment by RussKie** [comment]
Like Jay said, we can show some info

`CommitInformation.Header` will container author and date (now), and `CommitInformation.Body` will have something like "Pending changes"

**Comment by gerhardol** [comment]
I have submitted a PR. Feel free to reject it and do something different. But I really suggest the tabs are rendered differently too, to see that the tabs have no info.
(noticed a regression with _commitInformationProvider was null, will open a new issue.)

**Comment by gerhardol** [comment]
I mean the visual in the tabs:
![image](https://user-images.githubusercontent.com/6248932/34183377-da514d16-e51a-11e7-909d-62198859fe30.png)

If #4254 is accepted, I will look into where similar handling is needed. 
Regardless if #4254 is rejected I may look into showing all tabs later, but it will not be high on my prio list.

**Comment by RussKie** [comment]
Interesting idea... Though it may need further refinement especially from usability angle.
I wonder if it possible to grey out tab headers

**Comment by gerhardol** [comment]
> I wonder if it possible to grey out tab headers

Anything can be overridden. May be easy, may be difficult, it usually takes more time than one think (at least for me, not an UI designer). But I say that is later, #4254 should be acceptable for now.

**Comment by RussKie** [comment]
Dynamic hiding/adding of tabs has caused regression on Mono - when app starts the commit information is invisible unless another tab is selected first...

![ge mono regression](https://user-images.githubusercontent.com/4403806/34337989-36d20b56-e9b8-11e7-85a7-7b6d6c609cb6.gif)

**Comment by RussKie** [comment]
The same behavior is exhibited when selecting the artificial commit when it removes all tabs except for the diff - the tab's content is invisible unless the tab was previously selected...
It looks like another Mono's idiosyncrasy when it comes to dynamic content. *sigh*

**Comment by gerhardol** [comment]
Suggestion (for now): Not removing/adding the tabs in Mono, keeping the empty ugly tabs.

**Comment by RussKie** [comment]
I have a work around for the Mono, will push a PR shortly.
Must verify it works for Windows now lol

**Comment by vbjay** [comment]
If you showed artificial commit info, it wouldn't be an ugly tab.

**Comment by RussKie** [comment]
Please have a look at #4275 

"File tree" is the only tab that is absolutely blank for the artificial commits... It kind of begs for some content.

**Comment by gerhardol** [comment]
I prefer to hide the tabs, as the contents for an artificial "commit" is undefined. Showing current user for Commit and GPG is confusing, it creates information that do not exist (yet). The ugly empty rendering were better from that aspect, just hiding author and avatar would have been better..
I can live with this though.

similar for viewing the revision grid (collapsed previously).
![image](https://user-images.githubusercontent.com/6248932/34355427-83ec307e-ea35-11e7-92a7-e4f7a483f8df.png)

Note: FormFileHistory handles the Blame tab in a similar way for artificial commits (and submodules, that could be static). 
![image](https://user-images.githubusercontent.com/6248932/34355513-26312240-ea36-11e7-82a0-4d95e68656d8.png)
Commenting in the PR.

> "File tree" is the only tab that is absolutely blank for the artificial commits... It kind of begs for some content.

For the "File tree" there is a different motivation: This is something I feel the resources would be wasted in implementing.

Normal commits fill the File tab with ls-tree.
It could be possible to implement a ls-tree substitute by overlay for the staged and unstaged files by "overlaying" the current commit (or use ls-files for staged), but I do not feel that it is worth it. At least, some very smart caching of file system changes is needed first. Just use the file explorer.

**Comment by vbjay** [comment]
I frankly think that's the lazy way out. I think artificial commits should
act like commits. Show the files with an icon showing unstaged/staged. Gpg
tab could say it is unavailable because of this being a fake commit. The
commit info tab would show some info and could say this is not a real
commit, somehow.

**Comment by gerhardol** [comment]
> Show the files with an icon showing unstaged/staged.

I do not think that is as easy as it sounds. A static "FileBrowser" will not be so difficult, but the rules to update it will. Just the commit button with count is a resource hog.

> The commit info tab would show some info and could say this is not a real commit, somehow.

There are a lot of open questions for that "somehow".
Please make a better implementation or at least mockup that is not misleading for users.
My preferred way is still to hide the tab - there is no commit info for artificial.

**Comment by vbjay** [comment]
Think about it.  The commit info would be

Author: the current commit info as if you were to commit right now.  Look
at commit dialog.
Date:  NOW() when the artificial commit was built.
Parent: HEAD
Diff: staged files
File tree list all files in working directory.  If changed and staged show
one icon.  If changed and unstaged show another icon. If unchanged, show no
icon.

**Comment by vbjay** [comment]
Somehow=Some gui that hows in commit info panel and maybe an icon in the
revision list that also shows in commit info panel.

**Comment by vbjay** [comment]
Oh. The diff tab would also show deleted files with some kind of formatting
like delete icon and red strikethrough.  The filetree tab would show the
working directory as is with the deleted files, gone.

**Comment by vbjay** [comment]
Sorry.  Ideas are hitting me.  We could even have a before/after switch on
the file tree tab.  Before=head files, after=apply changes.

**Comment by vbjay** [comment]
With the icons, we could use solid/outline shapes to show staged vs unstaged.  

Added A green plus (Solid for staged, outline only for unstaged).  Do the same for the pencil and red x for edited and deleted.  

For partially staged files, halfway between solid and outline.

**Comment by RussKie** [comment]
> I prefer to hide the tabs, as the contents for an artificial "commit" is
undefined. Showing current user for Commit and GPG is confusing, it creates
information that do not exist (yet). The ugly empty rendering were better
from that aspect, just hiding author and avatar would have been better..

> Author: the current commit info as if you were to commit right now. Look
at commit dialog.
Date: NOW() when the artificial commit was built.

Disagree. The author **is** defined - it is whoever is making changes.
The date and hash are unknown, hence I have hidden these details from the
commit tab.
Granted we could probably add few other visuals to the commit tab for the
artificial commit, but to me this is a nice-to-have than a must-have.

> I frankly think that's the lazy way out. I think artificial commits
should act like commits.

I'm unsure whether it is in reply to my post or Gerhards.
My proposed implementation reduces the difference between artificial and
normal commits. It is probably a lesser or two (or more) evils in terms of
added implementation complexity. The UX add-on value for other
implementations is probably marginal. I don't want to delay the release
chasing the perfection (which we won't attain).

> RE: File tree

Keep the ideas coming, we can possibly implement something in the next
version.
