### ISSUE TITLE
Option to ignore all whitespaces

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4248]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the expected behavior?**

Expose https://git-scm.com/docs/git-diff#git-diff---ignore-all-space through the GUI.

**Comment by RussKie** [comment]
I'm a bit confused, I would appreciate it if you could clarify.

We have a setting: _Settings > Detailed > Diff Viewer: Remeber the 'Ignore whitespaces' preferences_, which I presume controls this button
![qr](https://user-images.githubusercontent.com/1003909/34125325-348d89c4-e436-11e7-8930-dca040cad4e8.png). 
I'm guessing this whitespace difference has nothing to do with git, but more to do with the viewer, right?

The proposal is to add another button to the toolstrip to control how git serves us with the data (subject to the "ignore whitespaces" preference enabled).

Do I understand it correctly?

**Comment by jbialobr** [comment]
The _Settings > Detailed > Diff Viewer: Remeber the 'Ignore whitespaces' preferences_ makes the _Ignore whitespaces changes_ setting persistent across multiple Diff viewer instances and GitExtensions sessions.
If the setting is off then the _Ignore whitespaces_ state is remembered only in the Diff Viewer object instance and is lost after its disposal.

The existing _Ignore whitespaces_ setting tells git to not consider differences in whitespaces at the both borders of the line as changes. See https://git-scm.com/docs/git-diff#git-diff---ignore-space-change

The requested _Ignore all whitespaces_ setting tells git to not consider differences in whitespaces as changes regardless of their occurrences in the line. See https://git-scm.com/docs/git-diff#git-diff---ignore-all-space

**Comment by RussKie** [comment]
Cool, thank you.
