### ISSUE TITLE
memory leak & high CPU usage on windows 10

### ISSUE THREAD

**Issue by 0xffff00** [gitextensions/gitextensions#4256]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
A memory leak & high CPU usage always happens to me. it causes nearly 100% memory usage & 100% single-thread CPU usage.

I have closed console window, it happens also.
I have tryed an older version - 2.49, it happens also.

![snipaste_20171220_104610](https://user-images.githubusercontent.com/18182738/34188900-bb241a3c-e573-11e7-83d2-cbb38b572fb7.png)
![snipaste_20171220_104544](https://user-images.githubusercontent.com/18182738/34188904-bf14c10a-e573-11e7-9b0b-4a34cfbecf07.png)
I am sure that git bash has no problem. If I only use git bash, it works fine and memory used will never exceed 2M.
 **Here is a comparation:**
  * processes of git.exe launched by gitextensions:
![snipaste_20171220_111031](https://user-images.githubusercontent.com/18182738/34189687-ac22dc0e-e577-11e7-8f03-2580804a1964.png)
  * a process of plain git bash:
![snipaste_20171220_111907](https://user-images.githubusercontent.com/18182738/34189691-af2d74d6-e577-11e7-8f40-ef5359d78a47.png)

**20171221 Updated**
A error dialog will be displayed in v2.49(may be fixed already ,i don't know) :
![snipaste_20171221_110456](https://user-images.githubusercontent.com/18182738/34238882-15240986-e63f-11e7-855d-5c53cb387221.png)

> Message:
>    Exception of type 'System.OutOfMemoryException' was thrown.
>
> Target Site:
>    Byte[] ReadByte(System.IO.Stream) @ GitCommands.SynchronizedProcessReader
>
> Stacktrace:   
>    at GitCommands.SynchronizedProcessReader.ReadByte(Stream stream)
>    at GitCommands.SynchronizedProcessReader.<>c__DisplayClass19_0.<ReadBytes>b__0(Object _)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.ThreadHelper.ThreadStart(Object obj)
>
> HResult:
>     -2147024882

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1.  open gitextensions with an existed git repository.
2.  after 10 minutes, it causes 100% memory usage & 100% single-thread CPU usage

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02/2.49
- GIT version: 2.15.1.windows.2
- OS version: windows 10 x64 professional edition (zh-CN language)
- hardware: Intel i5-6200U(2core,4threads), 8GB memory

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by RussKie** [comment]
I'm very much inclined to think this is an environmental or git issue than GE-specific.
I'm running GE on several machines if not 24x7 but very close to that.
The command log doesn't show anything unexpected or out of the norm...

We've had a number of issues of slowness on W10 but most were related to either W10 components (like speech recognition #3292) or some antivirus (#2907) or bad configs (#3968).

**Comment by gerhardol** [comment]
Also related to #4069 (I have a patch for that, awaiting #4209). The workaround for that is deactivating counter in Commit button.

What is the longest running command in the log?

**Comment by 0xffff00** [comment]
@RussKie 
I found this problem may be related to huge file amount of local git repo.
Now I have a git repo of a front-end web project using NodeJS.
It contains <100 files and 'node_modules/*' is written in `.gitignore`
But after running `npm install`, the file amount will increased to 19000+ files.
Here is my actions:
1. clone a git repository to local by git bash.
2. run command in git bash: `npm install`. 
  when done you can see a directory `node_modules` with about 20000 files is created and `git status` is clean since they are all git-igonored.
3. open this local repo by gitextenstions.
4. open Windows Task Manager, watch for several minutes.

If I skip step 2, gitextenstions works fine. no any 'git.exe' will be stuck and leaks memory.
However, if no above steps skipped, this problem will be reproduced.

Besides, I tried to all issues you mentioned.
I have disabled speech reocgnition ,disabled firewall and windows defender, run 'net use * /delete' to clear remote share folder links. All these do not work.

**Comment by 0xffff00** [comment]
@gerhardo you mean the command log taking longest time?
all logs take < 200ms, here is the longest:
`
2017-12-21T11:19:20.3845810+08:00    "C:\Program Files\Git\bin\git.exe" log -z  --pretty=format:"<(__BEGIN_COMMIT__)>%n%H%n%P%n%T%n%aN%n%aE%n%at%n%cN%n%cE%n%ct%n%e%x00%s%x00%B%x00"  --date-order --all --boundary --not --glob=notes --not  --max-count="100000" --     #(took 171 ms)
`

**Comment by RussKie** [comment]
Thank you for the follow up and the info. This may be useful when attemp to
repro.

Can you share your npm install script?
I presume the npm packages all in a public domain....

**Comment by 0xffff00** [comment]
@RussKie 
Yes, all npm packages are public. Here is a demo git repo.
just run:
> cd gitextensions-issues-4256-reprod
> npm install

[gitextensions-issues-4256-reprod.zip](https://github.com/gitextensions/gitextensions/files/1577921/gitextensions-issues-4256-reprod.zip)

**Comment by RussKie** [comment]
Cool thanks.
Are there any tools you run on the background which are watching for
changes?

I can't promise anything soon though with the end of the year, xmas and the
new release demanding attention.

**Comment by 0xffff00** [comment]
@RussKie xmas
no, just GitExt, Window Task Manager, git bash

**Comment by gerhardol** [comment]
As there were no other long running commands, this should be a git command that is started but never finished. Check the command line argument to the running git processes.

https://superuser.com/questions/415360/how-do-i-find-out-command-line-arguments-of-a-running-program

**Comment by 0xffff00** [comment]
@gerhardol thanks for help
With Process Explorer, I found the stucking command :
`
git.exe ls-files -o -i --exclude-standard
`

**Comment by gerhardol** [comment]
Turn of update of commit button to get rid of this:
![image](https://user-images.githubusercontent.com/6248932/34307223-4d9b6ae4-e747-11e7-80fa-255279dd5a23.png)

related to the issues I mentioned. This case with these long running times will not solve the issue though.
If you want the count, the command must execute...
It will be a little complex to warn the user if the scanning take too long time.

**Comment by 0xffff00** [comment]
@gerhardol thanks for your suggestion to avoid this issue.
I tried more commands. 
There will be stuck for long running time:
```sh
git ls-files -o -i --exclude-standard
git ls-files -o
```
But these are quite fast, may be useful to fetch count for commit button:
```sh
#list some ignored files
git ls-files -i --exclude-standard 
#list untracked files
git ls-files -o --exclude-standard
```

**Comment by RussKie** [comment]
@0xffff00 could you please share what settings you have set/unset under
Settings > Git Extensions tab (similar to Gerhard's screenshot above).

**Comment by 0xffff00** [comment]
@RussKie 
![snipaste_20171223_212118](https://user-images.githubusercontent.com/18182738/34319866-4a6b4e94-e827-11e7-8826-702ed21dca46.png)

**Comment by gerhardol** [comment]
I assume the settings were changed after the problem was reported?

GE uses the list of ignored files to ignore changes that the file system reports.
The list is updated at startup and when the global ignore file is changed.
So normally, the load is only a one time shot, not requiring much resources.

Without the filtering "git status" would run more often that normally would give a lot more load.
Maybe there can be some other way to do the filtering.

**Comment by gerhardol** [comment]
I still propose no change, but summarize some more findings.

The current "ignore files" detection is insufficient in this situation. But I see no better solution than to deactivate commit count.

A consequence of the current detection of ignored files is that GE may be slower if starting up in a clean repo (without ignored), then building. When ignored is refreshed after 10 min, the number of git status decreases too.

Parsing the git ignore rules is probably not an option, there are too many specific rules.

Instead of using "ls-files -o -i --exclude-standard" to detect all ignored files, "git status --ignored" could be used to detect directories, so new ignored files can be ignored and memory usage decreases. The parsing of a file the OS reports is changed will have to be redone, but the list will be smaller as directories are listed. But the "startup" problem remains, as well as a part of git exclusion rules in git ignore (this last part can probably be ignored).

I also have to mention "git check-ignore -v", to check each and every file (not realistic).

@0xffff00  Can you try git status --ignored?
 For me, "ls-files -o -i --exclude-standard" is faster than git status, but it seem to hang. Can you try again?

**Comment by 0xffff00** [comment]
@gerhardol  
`git ls-files -o -i --exclude-standard` will hang.
`git status --ignored` will be fine & instantaneous.
commands above were tested under a git repo containing 20,000+ ignored files

**Comment by gerhardol** [comment]
Please test that changes I propose is working better
https://ci.appveyor.com/api/buildjobs/ijckfmmxxvndi3sa/artifacts/GitExtensions-2.50.90.1384-Mono.zip

**Comment by dzmitry-lahoda** [comment]
I have similar issue on:
```
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET Framework 4.8.4470.0
- DPI 144dpi (150% scaling)
```
i feel like issues happens when i have this issue https://stackoverflow.com/questions/26046698/git-refname-origin-master-is-ambiguous/26047558  . and I have seen it first time ever at same time I start getting above.

not sure if that is enough to create new issue. so I see status  `[status: more info requested](https://github.com/gitextensions/gitextensions/labels/status%3A%20more%20info%20requested) l`

**Comment by RussKie** [comment]
Please open a new issue with a repro. Though if it's something user-originated via the command line (like the referenced SO issue) I'm not sure what we can do...

**Comment by gerhardol** [comment]
This is updated in master, in some situations where git-status was slow several parallel instances could start running. You would see several running git processes.

**Comment by dzmitry-lahoda** [comment]
yes, i did weird things with cli before trying to fix these with gitext. will try to get repro. i have seen enough gits running slowing down my PC with 16 physical theads.
