### ISSUE TITLE
Choose theirs / ours is inverted in rebase?

### ISSUE THREAD

**Issue by Nitaym** [gitextensions/gitextensions#4261]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
When rebasing a branch over another branch the "Choose local (theirs)" and "Choose remote (ours)" does exactly the opposite from what git would do if you would call
`git checkout --theirs codefile` or `git checkout --ours codefile`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Rebase a branch with a conflict, then try using both the "Solve Conflicts" dialog box which has "Choose theirs / ours" context menus, then try using `git checkout --theirs / --ours codefile` instead.
In git, `ours` mean the branch we are rebasing on and `theirs` means the branch we are rebasing.

**What is the expected behavior?**
Choose Ours  / Theirs should be consistent with the git tool. It's very confusing.

**Environment you encounter the issue:**
Windows 10

- GitExtensions version:
- GIT version:  version 2.12.2.windows.1
- OS version:  Windows 10 16299.125

**Did this work in previous version of GitExtensions (which)?**
I'm not sure

`git merge` is consistent with git-extensions theirs / ours

**Comment by vbjay** [comment]
https://git-scm.com/docs/git-rebase#git-rebase---merge

**Comment by RussKie** [comment]
It is confusing indeed, but it is normal git behavior.
When you think it through it makes complete sense. When you're rebasing the commit you're rebasing on top of becomes your local, and the commit you're rebasing becomes the remote.

**Comment by Nitaym** [comment]
The message is relating to merge strategies - But the text says "Choose ours" in relation to a single file. I though it's a bug as I assumed when you choose ours / theirs on a file it correlates to `git checkout`.

Maybe change the text? 
Or even better - Put the branch name instead of local / remote / ours / theirs?

**Comment by RussKie** [comment]
You don't always have branches, you can rebase on top of a commit.
Displaying sha1 will be even more confusing

**Comment by Nitaym** [comment]
Okay, thanks
