### ISSUE TITLE
Amend commit: commit message is not retained

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4262]
**Do you want to request a *feature* or report a *bug*?**
regression in master in the last week

**What is the current behavior?**
When amending a commit, the existing commit messageis no longer the dafault

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
amend a commit

**What is the expected behavior?**
The existing message is set as default

**Environment you encounter the issue:**

- GitExtensions version: master
- OS version: win7/10

**Did this work in previous version of GitExtensions (which)?**
a week ago or so

**Comment by vbjay** [comment]
Can you run a bisect?

**Comment by gerhardol** [comment]
> Can you run a bisect?

Yes, as well as commit. It is just that the existing message is not the default when amending

**Comment by EbenZhang** [comment]
you may  want to try the latest master branch to see if 4a3d0d70 fixed it

**Comment by gerhardol** [comment]
I am on latest master (plus some patches that has nothing to with it).
(and removing that patch opens the exception I plugged with that, should be done differently)

**Comment by EbenZhang** [comment]
I checked out the commit a8348732ffb00775d9c527c7c4f4b274de06605d (` Merge...#4257...commitInfo...Provider_is_null`)



It works as I expected: 

![messagewhenamendcommit](https://user-images.githubusercontent.com/596334/34240541-ce79f3fa-e649-11e7-96fc-e349f9508eab.gif)

**Comment by gerhardol** [comment]
I sometimes get the problem, sometimes not. Have not figured out what differs.

**Comment by vbjay** [comment]
If it had content it doesn't replace the content. Empty the textbox and
check amend. Uncheck and clear textbox and then type. Check again.

**Comment by gerhardol** [comment]
Closing this until I find how to reproduce
