### ISSUE TITLE
"View Stash" triggers System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by otbutz** [gitextensions/gitextensions#4263]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The dialog crashes if there's a named stash which was created by Eclipse.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- create a named stash with Eclipse git tooling
- try to view existing stashes within Git Extensions

**What is the expected behavior?**
Don't crash

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.14.2.windows.2
- OS version:  Windows 10 x64

**Did this work in previous version of GitExtensions (which)?**
Not that i know of

According to [GitStash.cs](https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitStash.cs#L59-L61) it seems that gitextensions is only able to deal with the following stash naming schemas:
```
stash@{0}: On master: config changes
stash@{1}: WIP on feature/noAnsiLogging: 7d7730c12aa Disable ANSI escape codes for all appenders
```
The problem is that Eclipse is not enforcing this schema:
```
stash@{2}: classpathModify
```

Git has no problem with the created stash and therefore gitextensions should support it too.

**Comment by RussKie** [comment]
Can you please provide the results of `git stash list` command and the full exception stack trace.
Thanks

**Comment by RussKie** [comment]
Can you please try https://ci.appveyor.com/api/buildjobs/ya7jv4j763evgjo1/artifacts/GitExtensions-2.50.02.1303-Mono.zip to see whether your issue is addressed.
Thanks

**Comment by otbutz** [comment]
Works flawlessly!
