### ISSUE TITLE
Displaying commit count in the commit detail form

### ISSUE THREAD

**Issue by alb3ric** [gitextensions/gitextensions#4267]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the expected behavior?**
Would it be possible to display the revision count in the commit details (under commit hash for example). This revision number would be calculate like this : git rev-list --count --first-parent COMMITSHA1

Best regards,

**Comment by RussKie** [comment]
Could you please explain a use-case where it is useful and how? Thanks

**Comment by alb3ric** [comment]
Hello and Happy new year,

Sorry for the late answer. I was away on holidays.

We use this number to generate a more human readable version number. When we want to build a release we trigger a gitlab-ci pipeline that generate an archive and set the version number based on this revision number (git rev-list --count --first-parent COMMITSHA1), at the end of the pipeline a tag is created with this revision number too.
Our QA team want to have this revision number displayed and the developper need it too as after they push there modification they report this number in the corresponding ticket filled in our issue tracker.

Hope my answer is clear enough :)

Thanks

**Comment by gpongelli** [comment]
Hi @alb3ric ,
I think this use case that can be better solved in other way.

If you trigger the gitlab pipeline through a POST call, for example, you can setup a git hook that execute the command and do the POST call after a git event (e.g. [post commit hook](https://git-scm.com/docs/githooks#_post_commit) checking if you're on a branch with a particular name like "release/..." or "master") without affecting GE.


My 2 cents.

**Comment by alb3ric** [comment]
Thanks for your answers and I agree...
But to simplify, the problem is that the Q/A team wants a readable revision number (not a sha1). We migrated from SVN and they were use to this number.
In tortoisegit you can display this revision number, that why I asked if it was possible to do same is GE, because GE is far faster than TortoiseGIT.

**Comment by gpongelli** [comment]
I've understood that your Q/A team prefer having a human readable revision number instead of a sha1.
I don't remember where Tortoisegit put this number.
Anyway, if human users have to get this number, it's possible to run a [script](http://git-extensions-documentation.readthedocs.io/en/latest/settings.html#scripts) (bounded to an icon) that shows this info.
BTW, I don't know if this can be really done because I don't use scripts too much.

**Comment by vbjay** [comment]
Please correct me but, wouldn't c1->B1:c2->c3 get the same count as
c1->B2:c4->c5?

**Comment by gpongelli** [comment]
@vbjay what do you mean with this notation ?
is it related to the `git rev-list` command or about my script hint ?

**Comment by vbjay** [comment]
Think of c1 being a base commit.  B1 could have 2 commits, c2,c3.  Same for
B2, c4,c5.  Wouldn't both branches have the same count?

**Comment by gpongelli** [comment]
@vbjay  you're right, just tested.

```
$ git init .
Initialized empty Git repository 
$ touch first.txt
$ git add .
$ git commit -m "first cmt on master"
[master (root-commit) 8ea9fd8] first cmt on master
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 fist.txt
$ git checkout -b b2
Switched to a new branch 'b2'
$ touch 2.txt
$ git add .
$ git commit -m "2"
[b2 bd07fa1] 2
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 2.txt
$ touch 3.txt
$ git add .
$ git commit -m "3"
[b2 70be30c] 3
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 3.txt
$ git checkout master
Switched to branch 'master'
$ touch 4.txt
$ git add .
$ git commit -m "4"
[master 2180cf2] 4
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 4.txt
$ touch 5.txt
$ git add .
$ git commit -m "5"
[master b6b444a] 5
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 5.txt
$ git rev-list --count --first-parent master
3
$ git checkout b2
Switched to branch 'b2'
$ git rev-list --count --first-parent b2
3
$ 
```

**Comment by vbjay** [comment]
As a unique counter, this number you are generating, is useless.  The sha1
is the unique identifier.  If they don't like it, automate a build script
to generate a unique number.

**Comment by vbjay** [comment]
Although, thinking on that, if you do add an ignored file, I think
gitextensions should offer to remove that ignore line if that ignore line
doesn't have other files, not added.

Example:

/ignoreme.txt    would be removed if you added that file.
/*.txt    would not be removed if there are some *.txt files not being
tracked.

**Comment by alb3ric** [comment]
Yes, the number is not unique. But we use this number only for the revision number. It is prefixed by a version number (major.minor) stored in a script.  .builds are only made from the master branch. Like this our version number is unique.

I tried the script and it s working (thx) but not sure would be sufficient for the users. I guess there is no point I suggest a pull request for this feature? :cry:

**Comment by vbjay** [comment]
Correct.  That is a specific use script.  You could add a pull request to
add the script in our scripts we provide as samples..

**Comment by RussKie** [comment]
Thank you all.

@alb3ric: at the moment is seems there is at least one workaround to achieve the required.
Given that GE is a general purpose tool baking in a specific implementation to address a unique use-case is undesirable.
I hope you understand.
