### ISSUE TITLE
Incorrect building dependencies

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4269]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
* GitExtensions (cs project) has References to the plugin .dll which should not occur (no direct access to the .dll)
* Build dependencies do not include all subprojects. So for instance when debugging, a clean was required first (partly hidden by the previous issue).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Clean the solution. Some .dll must be removed manually.
* The AppVeyor plugin is not loaded

**What is the expected behavior?**
Correct dependencies

**Environment you encounter the issue:**

- GitExtensions version: master
- OS version: Win10

**Did this work in previous version of GitExtensions (which)?**
Does not seem so from the file history

**Comment by RussKie** [comment]
I haven't experienced the issue on any machines I build (w8, w8.1, w10,
ubuntu). I can clean and rebuild without manual intervention.
Could you please provide more details on yhe issue?

**Comment by gerhardol** [comment]
The PR has some more verification info, will continue there.

**Comment by RussKie** [comment]
Sure. I don't have access to a proper computer for next 48 hours though.
Only mobile.

**Comment by gerhardol** [comment]
Have a well earned rest!

**Comment by RussKie** [comment]
Hah, no rest, no sleep... looking after two little hurricanes while my
better half is away.

**Comment by gerhardol** [comment]
Issue included in master
