### ISSUE TITLE
View summary of changes in revision grid

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4281]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The number of changes can be shown in the Commit button, together with some color coding to show the type of changes. It would be nice to see some more details, especially for artificial commits (#4209 adds support for the count for artificial commits). I would be most interested in submodule status, update needed or dirty, but also modified, new and deleted files.

The information can be presented in several ways:
 * New RevisionGrid column, available for all commits, so you can see simple/massive changes at a glance. Variable size though. the changes should be to the first parent only. This will have performance implications, calculating for all commits and should probably not be implemented.
 * First part of Subject column for artificial commits. Only for artificial commits then, can icons easily be blended with the text?
 * In toolbar, replacing the dynamic behavior of the Commit button. (Showing the aggregated status of unstaged/staged?)

One example. If the current unstaged changes look like this:
![image](https://user-images.githubusercontent.com/6248932/34367219-03115646-eaa8-11e7-8ac0-b32b895954f1.png)

The column/entry to the unstaged message could be:
![image](https://user-images.githubusercontent.com/6248932/34367230-28baf53c-eaa8-11e7-9f4c-782ac1508237.png):2 ![image](https://user-images.githubusercontent.com/6248932/34367238-40764a28-eaa8-11e7-9ff6-d8d14c54cd2e.png):1 ![image](https://user-images.githubusercontent.com/6248932/34367245-55f9656a-eaa8-11e7-90ff-a771555537a3.png): 1 ![image](https://user-images.githubusercontent.com/6248932/34367252-7c1833c0-eaa8-11e7-8b99-e02ea52499f2.png): 1

**Comment by RussKie** [comment]
> especially for artificial commits (#4247 adds support for the count for artificial commits but )

Do you mean #4209?
#4247 is about enabling them by default...


My apologies, but I've re-read the proposal several times and I am still unclear on the details (may be I need more sleep...I do actually)
You would like to visualise and provide more information on type of changes to submodules.
But I can't understand what this means:
![image](https://user-images.githubusercontent.com/4403806/34371506-eff5420a-eb21-11e7-8102-951d24e9535a.png)

**Comment by gerhardol** [comment]
> Do you mean #4209?

Yes...

> But I can't understand what this means:

A separate column or information merged to the Subject.

**Comment by gpongelli** [comment]
What should appear on merge commit ?

**Comment by gerhardol** [comment]
@gpongelli 
> What should appear on merge commit ?

The changes to the first master.
However, the performance implications are too high, a column available for all should probably not be implemented.

**Comment by gpongelli** [comment]
> However, the performance implications are too high

I think so.

**Comment by gerhardol** [comment]
What I want to see are no of changed tracked files, untracked files (just for worktree) and changed submodules.
It would be nice to see the submodule status to see submodules that need to be updated, but that require calculations.

**Comment by gerhardol** [comment]
Included as part of #5087
