### ISSUE TITLE
Commit's window vertical margin line setup

### ISSUE THREAD

**Issue by iwaddington** [gitextensions/gitextensions#4282]
**Do you want to request a *feature* or report a *bug*?**
_Feature_
**What is the current behavior?**
In the commit window the vertical margin line seems to be hard coded to 80 characters, but I would like to set it to 100.
![image](https://user-images.githubusercontent.com/34887184/34381348-26b7860a-eaef-11e7-9a8d-a6232cb61540.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**
Windows 10 Pro.
- GitExtensions version: 2.50.02
- GIT version: 2.14.1.windows.1
- OS version: 10.0.16299 Build 16299

**Did this work in previous version of GitExtensions (which)?**
I don't know.

**Comment by RussKie** [comment]
It is already implemented (https://github.com/gitextensions/gitextensions/pull/4095) and is coming out in the next release.
