### ISSUE TITLE
Question: How to configure for use with 2FA ?

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#4286]
Is it possible to use GitExtensions with 2FA enabled in GitHub ?

I remember trying this a year or so ago and not being able to push anything anymore, so I disabled it again.

Just wondering if it was me doing something wrong or if the feature was not (yet) supported, whether it is supported now and if so, how to set things up to get it working.

I couldn't find anything about it in the [Manual](http://git-extensions-documentation.readthedocs.io/en/latest/git_extensions.html)

**Do you want to request a *feature* or report a *bug*?**

If it's not supported, then this would of course be a feature request.

**Currently using:**
- GitExtensions version: 2.50.02
- GIT version: 2.14.1.windows.1
- OS version: Windows 7

**Comment by vbjay** [comment]
I have 2fa. We use open auth tokens. It doesn't matter.

**Comment by RussKie** [comment]
Jay, is there anything to configure?

**Comment by vbjay** [comment]
Yes. The token. Click to GitHub plug-in menu option. It will have you login
if no token is set up.

**Comment by jrfnl** [comment]
Ok, will try again over the next few days & report back. I've had a token setup for a s long as I can remember, so that is not the issue.

**Comment by vbjay** [comment]
You might need to clear the token in plug-in settings and set it up again.

**Comment by jrfnl** [comment]
@vbjay @RussKie Thanks for your responses. I've set things up and tested it on one repo for now and am happy to report that it all seems to work fine. Will keep an eye on things for the next few days.

I'll close this issue for now. If I'd run into things I'll re-open.

Side-note: it might be worth it to add a note about GitExtensions supporting GitHub 2FA out of the box somewhere in the manual :smile:

**Comment by jrfnl** [comment]
A few days and a dozen or so PRs later, things still seem to work fine. Thanks for the quick replies!

**Comment by daflame76** [comment]
I have OAuth token setup as per the instructions and it still prompts me to login when I try to push changes.  I enter credentials and it asks me to login again at the console prompt, then that fails also.

**Comment by daflame76** [comment]
Thanks.  Got it working.
