### ISSUE TITLE
Number of changed files isn't displayed in Commit button

### ISSUE THREAD

**Issue by KosMos-pv** [gitextensions/gitextensions#4295]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If there is some changed files in working directory there is no count for them on Commit button.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just make any changes in working directory.

**What is the expected behavior?**
I should see number of changed files on Commit button.

**Environment you encounter the issue:**

- GitExtensions version: 2.51 RC1
- GIT version: .15.1.windows.2 (x64)
- OS version:  Windows 7 x64

**Did this work in previous version of GitExtensions (which)?**
Yes, in 2.50.02.

**Comment by RussKie** [comment]
Do you have the feature enabled?
![image](https://user-images.githubusercontent.com/4403806/34484514-40746296-f019-11e7-9cb3-ccb1c8d6d1aa.png)

**Comment by KosMos-pv** [comment]
Yes, this feature is enabled.

**Comment by RussKie** [comment]
Hmm, I get the same if I open the app without any repo and then select a
repo from a dashboard - then the file count isn't working. If I open an app
going straight to a repo - it is working...

@gerhardol any thoughts?

**Comment by EbenZhang** [comment]
Experienced the same. The bug was introduced in #4208 https://github.com/gitextensions/gitextensions/pull/4208/files#diff-6d931ecb996aeb8676180da98e3f6861R185

**Comment by gpongelli** [comment]
Just a thought...
Considering that "show number of changed files on commit button" setting and related feature are raising bugs recently (here and in #4256), is reasonable to keep them ?

Sincerely, from my experience the number I see in commit button is not related to the file or the changes already staged or unstaged in my project (or maybe I don't know what this number is related to).

My 2c.

**Comment by vbjay** [comment]
It shows how many modified files are in working directory-ignored files.
It has nothing to do with staged/unstaged.

**Comment by gpongelli** [comment]
why also the ignored files ?
if I choose to ignore a file, it's useless to know that it's changed also because I cannot commit it.

**Comment by vbjay** [comment]
OMG what part of - do you not understand

**Comment by vbjay** [comment]
Actually you can commit an ignored file.  You have to be explicit on adding
it.  Also gitextensions won't show it by default.  You can however, show
ignored files and add it if you wanted to.

**Comment by gerhardol** [comment]
@gpongelli  @vbjay 
The count is the staged+unstaged. If a file is staged and then modified again it will be counted twice.
Ignored files are not counted.
This count is calculated with "git status --porcelain -z --untracked-files" after changes in the file system (filtering out ignored files) or every  fifth minute.

The performance can be improved, I have made a patch for #4069, awaiting #4209 to be merged first. For #4256 it is harder. To just have a periodic check, it should not be a problem.

When starting in the debugger, a repo is always opened for me, most normally when starting separately too, so I do not see this problem. (Separate issue.)

The workaround should be to just open the last directory on startup. I will submit a PR, it is what @EbenZhang pointed at.

**Comment by vbjay** [comment]
Actually.  That is a horrible workaround.  The right way is to fix the
issue.  Opening the last one is not a good idea.

**Comment by gerhardol** [comment]
> Actually. That is a horrible workaround. The right way is to fix the issue. Opening the last one is not a good idea.

Of course it will be fixed (#4298) and should be included in RC2. 
A workaround is needed for RC1 users will not run from unmerged PRs or even master.

**Comment by vbjay** [comment]
I see.

**Comment by RussKie** [comment]
Could you please give this a go to see whether the bug is fixed:
https://ci.appveyor.com/api/buildjobs/smgb4wxns53kd25q/artifacts/GitExtensions-2.50.90.1357-Mono.zip

**Comment by KosMos-pv** [comment]
Yes, bug is fixed in this build. Started GitEx, selected favorite repo and number of changed files is shown.
