### ISSUE TITLE
Add version to the main title

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4299]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Across a number of computers I have a number of different versions of GE installed (including develop versions).
Without constantly checking Help->About, it makes it difficult to know which version I am running.
Proposing to add the information version to the title like so: `repository (branch) - Git Extensions v2.51.RC1`

**Comment by gerhardol** [comment]
This should maybe be limited to Debug builds.
For normal users, the version is not of that importance

For Debug builds on the other hand, I want more information like build time, number of commits since last label or something. The version has stayed as 2.50.02 for several months until now.

**Comment by RussKie** [comment]
I had several versions installed 2.49.x, 2.50.y, 2.50.z, develop... now add 2.51 to the mix

**Comment by gerhardol** [comment]
But normal users do not have more than one version.
Since the normal installer omly have one version, also your installations (as well as mine) are special. I often want to debug anyway, then I have an own build anyway.

I have more problem to differ the current branches "close to master" than regular releases, so that is what I want to see.

**Comment by RussKie** [comment]
@jbialobr @KindDragon what do you think?

**Comment by pravic** [comment]
> For normal users, the version is not of that importance

I agree with that. It would just pollute the window title. 

Debug builds are better. Or a special setting at least.

**Comment by jbialobr** [comment]
I like the idea (perhaps I am biased). When my colleagues show me that sth does not work or they miss a feature I always ask them about the version they use - having this feature I could only glance at the title bar.
Seeing that an user has older version you can advice him to install a newer one and seeing that someone has a newer version I know that my version is stale and I can install a newer one.

**Comment by RussKie** [comment]
I do find myself in the same situation every now and then too - our devs
ask or complain about GE getting them to find the version is a hassle...

**Comment by vbjay** [comment]
I understand and do agree that the version would be good. I don't
understand how help-> about is a hassle.

**Comment by gerhardol** [comment]
Displaying version (and maybe release date) on the dashboard would be a start. Displaying the latest version there too would be good (avoid extra popup).
At work, we have a separate tool check where GE is included as optional. (If someone has an issue they have no right to complain unless the recommended versions are used.)

But for Debug, I want more information than version.

**Comment by RussKie** [comment]
After the dashboard is refactored - the version can be displayed there. and probably some more - I take inspiration from VS in that.

**Comment by RussKie** [comment]
Alright, I'm going to put this on hold

**Comment by RussKie** [comment]
Here's an example where version displayed more prominently could have helped - https://github.com/gitextensions/gitextensions/issues/2789#issuecomment-356083543
