### ISSUE TITLE
Show number of changed files does not work in 2.51 RC1

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#4303]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
Commit button on GitEx toolbar does not track modified files count anymore.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Open repository
* Change something
* Take a look on commit button

**What is the expected behavior?**
A red button with modified files number in 2.50.02.
Green button without anything in 2.51 RC1.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.RC1
- GIT version: git version 2.15.1.windows.2
- OS version: Windows 7 SP1 x64

**Did this work in previous version of GitExtensions (which)?**
It works in 2.50.02 and older.

**Comment by pravic** [comment]
May be I am not the first who reported about this, I haven't checked opened issues.

**Comment by gerhardol** [comment]
See #4295, workaround exists

**Comment by pravic** [comment]
I would not call it _workaround", but this is definitely a duplicate. Closing.
