### ISSUE TITLE
connect to https without certificate

### ISSUE THREAD

**Issue by talregev** [gitextensions/gitextensions#4306]
**Do you want to request a *feature* or report a *bug*?**
I am not sure if it feature or bug.
**What is the current behavior?**
There is no option on gui that will be able gitextensions to git clone (or any operation of git) on https without certificate.
example in command line:
git -c http.sslVerify=false clone https://example.com/path/to/git

  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

git clone to https site without certificate. error on git clone.

**What is the expected behavior?**
to be able to turn option in gui turn on "connect without certificate" default value is off. that if turn on it will connect to https without certificate:
git -c http.sslVerify=false clone https://example.com/path/to/git
**Environment you encounter the issue:**

- GitExtensions version:
latest (2.50.02)
- GIT version: 
latest (2.15.1)
- OS version: 
windows 7. 
**Did this work in previous version of GitExtensions (which)?**
I don't know

**Comment by RussKie** [comment]
I can play this game forever and close the issue again.

![image](https://user-images.githubusercontent.com/4403806/34554636-f2389542-f181-11e7-8671-0bbc7cb38536.png)

**Comment by talregev** [comment]
updated.

**Comment by RussKie** [comment]
thank you

**Comment by gerhardol** [comment]
The workaround is to set the option globally before cloning

git config --global http.sslVerify "false"

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion. Also, a workaround is available.
