### ISSUE TITLE
Visual Studio 2017 as default

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4311]
**Do you want to request a *feature* or report a *bug*?**
building problems, not functionality

**What is the current behavior?**
GE promotes VS2015, but VS2017 works too, also in AppVeyor.
Microsoft is quick to depreciate older Community versions. It is not possible to download VS2015 from Microsoft. I just found out that I have 14.1, but cannot upgrade to 14.3 (installer fails).

To be clear, I see no reason right now to depreciate VS2015 for building.
Also, this is not about the VS2010-2013 plugin (should be renamed to distinguish from GE plugins...). (I misunderstood that myself in #3362)

This is related to #4269, the build scripts can be simplified but this can cause VS2017 msbuild be selected before VS2015.

**Environment you encounter the issue:**

- GitExtensions version: master
- OS version: Win10

**Did this work in previous version of GitExtensions (which)?**
Continuously updating...

**Comment by RussKie** [comment]
I agree
