### ISSUE TITLE
Git update to 2.16.1

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4312]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
2.51RC1 contains git 2.13. The latest version is 2.15.1. 2.16.RC0 exists too, 2.16 should be released in a couple of weeks.

I have used 2.15 since it was released, have not seen any problems.
There are to my knowledge no critical issues in 2.13 compared to 2.15. There are some submodule and LFS enhancements, currently only used from the command line.

GE should follow the Git releases when possible. Also stated in the documentation
https://github.com/gitextensions/gitextensions/wiki/Release-cycle

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.15.1
- OS version: Win7/10

**Did this work in previous version of GitExtensions (which)?**
2.50 included the latest Git release at the time

**Comment by vbjay** [comment]
Not to mention 2.15 added an option to check daily for git version updates.

**Comment by RussKie** [comment]
Perhaps we just need to enhance our build/setup scripts to download the latest version available at the time of build.

**Comment by gerhardol** [comment]
Should probably be manual, we do not know what is stable.
I plan to submit a PR for 2.15.1 after a build script update with a few simplifications (there should be a bigger take on the release process it seems)

**Comment by RussKie** [comment]
Yes, the release process is a labour intensive exercise. No wonder we had
one version per year...

**Comment by gerhardol** [comment]
2.16.1 is working well for me (some fixes to reset since initial release)
I would prefer to not bundle Git with GE and just recommend the Git version on the home page...

**Comment by RussKie** [comment]
I suppose we can modify the setup to check whether git is installed on the user's computer and prompt them to install it, if it is missing.

Probably do something like that for diff tools too, though at run time - if no diff tool is configured - prompt to configure/install?

**Comment by gerhardol** [comment]
Submitted a PR for 2.16.1. Not a big deal also if we update later or select a better solution.

Downloading if not detected by the installer would be preferred, but the installer is supposedly difficult to modify in this way.
Ceck at startup is easier to implement. Separate issue?

**Comment by RussKie** [comment]
Can it be closed?
If you use [keywords](https://help.github.com/articles/closing-issues-using-keywords/), it'd happen automagically

**Comment by RussKie** [comment]
> Downloading if not detected by the installer would be preferred, but the installer is supposedly difficult to modify in this way.
Ceck at startup is easier to implement. Separate issue?

Yes, this issue is for the update.
Installer rework is a separate issue.
