### ISSUE TITLE
Create branch modal buttons under linux/mono

### ISSUE THREAD

**Issue by IlyaMokin** [gitextensions/gitextensions#4319]
I can't see any buttons under create branch modal with GitExtensions 2.51.RC1. 
Just for info: Most of other modals issues are fixed with the release. It's cool! 

![image](https://user-images.githubusercontent.com/5592397/34613641-813faefc-f23f-11e7-9de5-c21953377e07.png)

**Comment by RussKie** [comment]
Could you please run this version and confirm if the issue is fixed
https://ci.appveyor.com/api/buildjobs/2e71hod9193lwnii/artifacts/GitExtensions-2.50.90.1429-Mono.zip
