### ISSUE TITLE
Move with drag & drop selected commits of a branch to another branch

### ISSUE THREAD

**Issue by webmaster33** [gitextensions/gitextensions#4326]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Move commit feature is missing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
We have two branches.
I would like to select a few commits and move the to another branch.

Example:
A - B - C
   \ 
      D - E - F

I would like to have the result:
A -B -C -D - E
    \ 
      F

The example above can be reached with the following git commands:

1. checkout C
2. cherry pick D
3. cherry pick E
4. checkout F
5. rebase from A, while deleting D and E
6. checkout E

I often find myself, that I need to do several git actions: checkouts, cherry picks, rebases, hard resets to reach the fast forward state, and avoid merge commit. I think this could be simplified with such "move with drag&drop" feature.

What do you think?

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.9.3
- OS version: Windows 7 Pro

**Did this work in previous version of GitExtensions (which)?**

**Comment by gerhardol** [comment]
You can cherry-pick several commits at one time.

The error handling including merge conflicts and command confirmation is very complex here so this will be complex. 
Documentation too, many users do not understand the implications of rebases.

**Comment by RussKie** [comment]
As much as I'd love this feature implemented I think it will be a nightmare to implement, like @gerhardol said.

I think it is much more feasible to attempt to copy the whole branch from the selected commit to the target - i.e. if you attempt to d'n'd E to C, then the result would be:

A - B - C - E - F
\
D - E - F

You could probably add "delete original" toggle too to delete original commits once they were copied:

A - B - C - E - F
\
D

**Comment by klorinczi** [comment]
I think we have all the atomic commands we need to do a higher level command. 
Just do a command queue, and current functions will do, what currently do. The only "nightmare" would be only the rebase, delete and conflict handling. But this is already implemented, so current functions would handle it. 

Would be really comfortable to have such feature.
It could save a lot of work and time currently I spend using git.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion. No one is working on this.
