### ISSUE TITLE
High Dpi Scaling - UI too small in latest 2.51.RC1

### ISSUE THREAD

**Issue by tompollok** [gitextensions/gitextensions#4329]
**Do you want to request a *feature* or report a *bug*?**

UX related problem

**What is the current behavior?**

When I open GitExtensions on my Mac, the whole Git extensions is scaled too small. Id say about 25% too small. Its quite hard to concentrate when everything os scaled so small.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Reproducible with latest MacBook Pro and Windows 10 VM (I use Parallels)
**What is the expected behavior?**

The UI scaling should be slightly bigger.

**Environment you encounter the issue:**

- GitExtensions version: Version 2.51.RC1

**Did this work in previous version of GitExtensions (which)?**

I didn't test this, but I did not have any problems with the latest Version before Version 2.51.RC1.

**Comment by RussKie** [comment]
The app is scaled by the OS.
I do all my dev on W10 in Parallels (MBP 2014 retina) and have no issues.

Please confirm how v2.50 behaves and check Win settings.

**Comment by tompollok** [comment]
Alright, ill check it later.

**Comment by tompollok** [comment]
I checked it. 2.51 and 2.50 have the same behaviour on my screen. So I was wrong. Sorry for the wasted time.

My VM is configured as Retina Resolution -> Best for Retina display. It seems that i cant tweak the Scaling Factor in windows settings when this is set. When i set it to Scaled, then i can scale the UI so that its better readable but the whole OS looks/all text labels become pixelish.

I guess there is nothing you could do about this, so the Issue can be closed.

**Comment by RussKie** [comment]
W10 does a reasonably good job scaling things up. W7 and W8 were pretty lousy at that.
