### ISSUE TITLE
Remote repositories modal linux/mono

### ISSUE THREAD

**Issue by IlyaMokin** [gitextensions/gitextensions#4337]
I can't see bottom buttons under remote repositories modal with GitExtensions 2.51.RC1.
Can be related to [#4319](https://github.com/gitextensions/gitextensions/issues/4319)
- click commit button
- click manage remotes
Result:
![image](https://user-images.githubusercontent.com/5592397/34670293-ac917470-f486-11e7-8ed5-e8ba871caccd.png)

**Comment by IlyaMokin** [comment]
Sorry, my bad. it is not an issue

**Comment by RussKie** [comment]
There are no buttons like it used to be in earlier versions.

The groupbox is clipped though, which gives an impression that something may be beyond the visible area. The issue is purely cosmetic.

Unfortunately Mono Winforms is pretty difficult to deal with when it comes to dynamic layouts...
