### ISSUE TITLE
[Bug] GitExt is not showing all commits

### ISSUE THREAD

**Issue by mcenderdragon** [gitextensions/gitextensions#4347]
All new fetched merge commits are broken and only the first parent is visible and not the second one, this results in a large amount of branch lines pointing into void.

- GitExtensions version: 2.50.02
- GIT version: 2.13.2.windows.1
- OS version: win 10

**Did this work in previous version of GitExtensions (which)?**
it worked fine wich this version but it just broke when I commited a stash from another computer.

**Comment by mcenderdragon** [comment]
https://imgur.com/Hw2Tesl
https://imgur.com/JdxZNKH

**Comment by vbjay** [comment]
git log --oneline | wc -l

Create a git repo that has this issue.  Run the above command in the
console and count how many commits are in the gui.

**Comment by vbjay** [comment]
Is 
![image](https://user-images.githubusercontent.com/3629489/34788761-920c1ebe-f609-11e7-9d59-132c2fcbd07f.png)
 checked like this?

**Comment by mcenderdragon** [comment]
the command responds 4213, and in the 

It is checked but after I clicked the button it was fixed. What mode was that and is it suppoed to work like that (and should it also be so hard to tell if its aktive or not) ?

**Comment by vbjay** [comment]
https://git-scm.com/docs/git-log#git-log---first-parent

Create an issue describing the UI issue.

**Comment by mcenderdragon** [comment]
ok, I think this can get closet
