### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by mcenderdragon** [gitextensions/gitextensions#4348]
It is currently (version 2.50.02) hard to tell if the "first parent mode" is active or not.

![image](https://user-images.githubusercontent.com/350947/41558020-7cbcf488-7337-11e8-99be-f668e5e79bab.png)

See #4347.

**Comment by vbjay** [comment]
Just making you aware.  You can paste images in github issues.

**Comment by vbjay** [comment]
You do need to use the issue templates.

**Comment by RussKie** [comment]
If it is clicked it is enabled, not otherwise.

Please use the template provided, if you wish to continue this discussion.

**Comment by vbjay** [comment]
> If it is clicked it is enabled, not otherwise.

Not checked:
![image](https://user-images.githubusercontent.com/3629489/34798197-151ed08e-f629-11e7-9cdd-05e99024bf13.png)

Checked:
![image](https://user-images.githubusercontent.com/3629489/34798227-38334226-f629-11e7-9177-101480fcf753.png)

Mouse Hover:  
![image](https://user-images.githubusercontent.com/3629489/34798248-4cb4f442-f629-11e7-8fbe-41362962e18c.png)

I do see his point.  I think a greyscale icon for not checked would help.

**Comment by RussKie** [comment]
We should probably remove it, since it is not the first time this issue is
reported.
IIRC @EbenZhang had the same issue not too long ago

**Comment by vbjay** [comment]
What are your thoughts on making it act like highlight selected branch.  On
refresh, remove it.

**Comment by vbjay** [comment]
If that is the route we want to go, I'd be happy to do that work tonight.

**Comment by RussKie** [comment]
To be honest I'm not sure I understand the proposal.

I'm on holidays and my wife denies me my laptop, lol

**Comment by vbjay** [comment]
Lol. The menu highlight current branch in the view menu refreshes and hides
the branches that are not the current one. When the revision list is
refreshed, it shows the normal view. I propose that we do the same thing
for first parent.

**Comment by RussKie** [comment]
Yep, sounds sensible

**Comment by RussKie** [comment]
The colour scheme has been tweaked in v3, so the state should be more obvious now
![image](https://user-images.githubusercontent.com/4403806/48483036-68f51300-e866-11e8-8f39-fd0457e5ab06.png)
