### ISSUE TITLE
Git extension does not detect the changes

### ISSUE THREAD

**Issue by Babu1976** [gitextensions/gitextensions#4353]
I installed git extension version:2.51.RC1
IT does not detect the code changes. But when I click on commit button on the tool bar, the commit window shows changed files.
The issue is very similar to [https://github.com/gitextensions/gitextensions/issues/2940](url)

I killed Git extension and restarted the system also.But it does not detect.

**Comment by Babu1976** [comment]
I checked and there is no git process running.

**Comment by vbjay** [comment]
Then check your settings. 

![image](https://user-images.githubusercontent.com/3629489/34844343-1fc45fac-f6df-11e7-9f15-68e2a72e5e74.png)

**Comment by Babu1976** [comment]
YEs both are checked ON. I didnt understand "restarted required". Do I have to restart the git or system?

**Comment by vbjay** [comment]
GE

**Comment by Babu1976** [comment]
GE? Didnt understand?

**Comment by vbjay** [comment]
Our product is called Git Extensions.  GE.  Get it?

**Comment by Babu1976** [comment]
Yes. Both the check boxes are ON.

**Comment by gerhardol** [comment]
Is this #4303, then there is kind of a workaround. Fixed in #4303 
@vbjay Are you using the RC?

**Comment by RussKie** [comment]
This a dup of #4295

**Comment by vbjay** [comment]
Not at work.

**Comment by RussKie** [comment]
Duplicate of #4295
