### ISSUE TITLE
Delete remote branch's local descriptor

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4356]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Deletion of remote branches was introduced in #4146. However if the remote branch was deleted on the remote server (e.g. via GitHub or Bitbucket UI), the local descriptor is retained by the local repo and it is now impossible to delete using the GE UI.

**What is the expected behavior?**
The "delete remote branch" functionality should remote the local descriptor if the remote branch no longer exists.

**Environment you encounter the issue:**
master, 2.51+

**Comment by vbjay** [comment]
Look at the plugins menu.

**Comment by RussKie** [comment]
I have, what should I be expecting to see?

**Comment by RussKie** [comment]
This can be achieved with "Fetch and prune all"
![image](https://user-images.githubusercontent.com/4403806/48320196-ca509280-e66a-11e8-89f9-ff6fcef9fed8.png)

**Comment by eqqe** [comment]
> In v3 this can be achieved with "Fetch and prune all"
> ![image](https://user-images.githubusercontent.com/4403806/48320196-ca509280-e66a-11e8-89f9-ff6fcef9fed8.png)

Does this delete the local descriptor?

**Comment by RussKie** [comment]
No, only the local remote refs. Local refs can be deleted with the plugin.

**Comment by eqqe** [comment]
Okay thank you.
FYI, the plugin name is "Delete Obsolete Branches".
