### ISSUE TITLE
Reverting multiple commits must process from newest to oldest

### ISSUE THREAD

**Issue by butscher** [gitextensions/gitextensions#4360]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When selecting multiple commits and let Git Extensions create revert commits it begins with the oldest in the list. Example:

Three commits A, B, C happened in this order, are now selected and should be reverted at once. The program now tries to revert A first which means that any merge conflicts introduced by B or C must be handled first and may create additional work and some confusion because of unnecessary changes.

**What is the expected behavior?**
The program should revert the newest commit first. In the example: if reverting C first, then B, any possible merge conflicts introduced by these commits are already gone when A is reverted then.

**Comment by gerhardol** [comment]
Reverting commits is only done to the last selected commit.
So the bug there is now is that reverting should not be enabled at multi-selections.

Multiselection could be supported though. 
The question is the order of reverting. It may be better to revert the commits in the order (or reverse order) selected instead.
Cherry-picking can be done to several commits, then the commits are sorted descending.

**Comment by butscher** [comment]
@gerhardol
It is currently possible to revert a commit which isn't the last one (which is very helpful, by the way) so why shouldn't it be possible to revert multiple commits from a multi-selection?

Reverting is a kind of opposite of cherry-picking so it should work in the same way (but in the opposite order).

Reverting in the order the commits were selected would be even more flexible but harder to implement, I guess.

**Comment by gerhardol** [comment]
> so why shouldn't it be possible to revert multiple commits from a multi-selection?

Because it is not implemented right now. The current bug is that the menu item should be disabled, enabling multiple is an enhancement. But a bugfix and enhncement has a similar complexity.

> Reverting in the order the commits were selected would be even more flexible but harder to implement, I guess.

Enforcing a certain order is adding a line of code so order of selection is simpler...
In this issue the order of selection was obviously C B A, so the behaviour is not obvious.
Will users understand what is happening?

Cherry-pick and revert should work in a similar way.
