### ISSUE TITLE
Navigate - Go to Commit, doesn't find some commits

### ISSUE THREAD

**Issue by DanSear** [gitextensions/gitextensions#4363]
It appears that when the commit hash gets too short, nagivate to commit just puts up the "No revision found" dialog. Example: repo contains a node with commit hash c25085a22fa61f966761def96f6ac2de505294bb.

Navigate / Go to Commit... with the full hash works, but when only "c250" is entered, the "No revision found" dialog is presented instead.

- GitExtensions version:
- GIT version:  2.50.02
- OS version: Git extensions - Visual Studio and Shell Explorer Extensions for Git

**Comment by vbjay** [comment]
See #4310

**Comment by gerhardol** [comment]
See the help in the popup
If the commit is not unique, git-rev-parse returns the same error code as if the hash is garbage, so the GE error message cannot explain that the hash is ambigous
