### ISSUE TITLE
GitExtensions ignores "Mergetool command" setting for KDiff3

### ISSUE THREAD

**Issue by Egor92** [gitextensions/gitextensions#4364]
**Do you want to request a *feature* or report a *bug*?**
Hello. I want report about a bug.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1) Go Menu -> Tools -> Settings -> Git Extensions -> Git Config
2) Set "Mergettol"="KDiff3"
3) Set "Mergetool command"=
"C:/Program Files (x86)/KDiff3/kdiff3.exe" "$BASE" "$REMOTE" "$LOCAL" -m
4) Press OK
5) Start any merge with conflict
6) Select file to resolve conflict in KDiff3

**What is the current behavior?**
KDiff3 displays:
1) BASE as A (in left)
2) **LOCAL** as B (in center)
3) **REMOTE** as C (in right)

**What is the expected behavior?**
KDiff3 displays:
1) BASE as A (in left)
2) **REMOTE** as B (in center)
3) **LOCAL** as C (in right)

If I run KDiff3 in command line with arguments:
kdiff3.exe  BASE_FILE  REMOTE_FILE  LOCAL_FILE  -m
where BASE_FILE, REMOTE_FILE, LOCAL_FILE are paths to files then I see what I wrote in _expected behavior_

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.15.1
- OS version: Windows 7 Pro
- KDiff3 version: 0.9.97

**Did this work in previous version of GitExtensions (which)?**
2.50.01

============================
May be I just write incorrect "Mergetool command"?

**Comment by RussKie** [comment]
AFAIK kdiff3 doesn't take any parameters in our implementation.
@KindDragon are you able to chime in?

**Comment by Egor92** [comment]
I have found [arguments pass in FormResolveConflict class](https://github.com/gitextensions/gitextensions/blob/c133bf68944be5e68fcdc66dc7dcdc4c792c222e/GitUI/CommandsDialogs/FormResolveConflicts.cs#L457). Unfortunately I cannot debug it at the moment. But I'll try later.

**Comment by Egor92** [comment]
I have removed `_mergetool == "kdiff3"` condition [here](https://github.com/gitextensions/gitextensions/blob/c133bf68944be5e68fcdc66dc7dcdc4c792c222e/GitUI/CommandsDialogs/FormResolveConflicts.cs#L523) and have changed mergetool command to `"$BASE" "$REMOTE" "$LOCAL" -o "$MERGED"`. And it has begun to work as I wanted.

I would like to know why "mergetool command" settings is ignored by GitExtensions when mergetool is  KDiff3? Could it be fixed?

**Comment by gerhardol** [comment]
GE supplies default git arguments for KDiff3. MergeToolHelper.cs MergeToolcmdSuggest()
It seems from this issue that KDiff3 internal is not what the tool describes in its documentation so default should be changed.
It makes sense that the parameters are configurable, if only to avoid questions like this.

**Comment by gerhardol** [comment]
Hardcodings for kdiff3 was removed in #7009, possible to change the suggested options in #7044, corrected arguments in #7548.

**Comment by RussKie** [comment]
Fixed in #7549

**Comment by mohamedwael8440** [comment]
solved thank you 
used git config --global mergetool.kdiff3.path "C:/Program Files/KDiff3/bin/kdiff3.exe to configure new path
