### ISSUE TITLE
Submodules dialog gets out-of-sync

### ISSUE THREAD

**Issue by hsattler** [gitextensions/gitextensions#4365]
**Do you want to request a *feature* or report a *bug*?**

-> Bug.

**What is the current behavior?**

Whenever the list on the left side of the Submodules dialog updates, the last selected item is selected again but the right side of the dialog stays at the first item.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Open "Repository->Submodule..." from the menu. Select a different submodule than the first (you obviously need more than one!).  Click the "Synchronize" or "Update" button and wait until it finished.
-> Now the two parts of the dialog do not match anymore.

**What is the expected behavior?**

The two parts of the dialog shall always match.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.2
- GIT version: 2.15.1.windows.2
- OS version: Windows 7 Pro 64bit

**Did this work in previous version of GitExtensions (which)?**

(unknown).

**Comment by GintasS** [comment]
I'm not sure where the problem is, tried to reproduce it, everything seems normal. But apart from that, it is an old issue, no one working on this, we should close it.
