### ISSUE TITLE
Submodules dialog: list is too narrow

### ISSUE THREAD

**Issue by hsattler** [gitextensions/gitextensions#4366]
**Do you want to request a *feature* or report a *bug*?**

-> Bug

**What is the current behavior?**

When the dialog is show, the entry in the submodules list on the left side to not fit the table. For some, I can on see the elided prefix like "submodules/ABCD/..." multiple times. This makes the list rather useless.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

You need a repository with submodules that have a longer path.

**What is the expected behavior?**

Adapt the table to the widht of the content or at least save the state so the user can arrange it as needed and it stays like that even when the user opens the dialog again.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.2
- GIT version: 2.15.1.windows.2
- OS version: Windows 7 Pro 64bit

**Did this work in previous version of GitExtensions (which)?**

(unknown)

**Comment by RussKie** [comment]
Some screenshots would be nice, thanks

**Comment by gerhardol** [comment]
You can change the size of the left panel (and the form), the size of the Name column will then be expanded.
The support for mono makes these interfaces hard to implement in a good way, no dynamic support in mono.

**Comment by hsattler** [comment]
Sure, here is a dummy example:
![2018-01-18 14_05_50-submodules](https://user-images.githubusercontent.com/28525744/35099630-02d80a04-fc59-11e7-96aa-5b3c468553a0.png)

@gerhardol Sure I can resize it but next time I open the dialog, it is back to old size.

**Comment by RussKie** [comment]
Saving and restoring the size is pretty trivial fix.
The rest is a bit more involved, especially so if we account for Mono and
4K displays.
