### ISSUE TITLE
Branch filtering not working

### ISSUE THREAD

**Issue by yesgrey** [gitextensions/gitextensions#4370]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The "Branches" drop down combo box does not work when more than one branch is listed (separated with spaces)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
If you write the name of one branch, the view is filtered to only show that branch. If you write more than one branch, only the first branch is shown. It also crashes when you try to edit the box with more than one branch names written on it.

**What is the expected behavior?**
Filter the history view showing all the written branches. Do not crash when editing the field.

**Environment you encounter the issue:**
- GitExtensions version: 2.51.RC2
- GIT version: 2.15.1.2
- OS version: Both Win7 x64 and Win10 1703

**Did this work in previous version of GitExtensions (which)?**
Yes. 2.50.02

**Comment by vbjay** [comment]
https://git-scm.com/docs/git-rev-parse

**Comment by RussKie** [comment]
System.ArgumentOutOfRangeException

```
InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at System.Windows.Forms.ComboBox.get_Text()
   at GitUI.FilterBranchHelper.UpdateBranchFilterItems()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ComboBox.OnTextUpdate(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by yesgrey** [comment]
I'm not sure, but maybe this is related with non-letter characters... I tried with two branches whose names only have letters, and it worked fine, both branches were shown. However, when one of the branches had numbers and/or dashes/dots (- or .) I got the error.

**Comment by vbjay** [comment]
That makes more sense.  - means something in rev-parse.  Frankly, I
wouldn't use

:
-
.

and others in branch names.

**Comment by RussKie** [comment]
`:` is an invalid char, others are quite legal - https://www.git-scm.com/docs/git-check-ref-format/1.8.2
These rules are implemented in https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitBranchNameNormaliser.cs

**Comment by RussKie** [comment]
It is somewhat strange the code hasn't changed in over 2 years, yet the same thing is working in 2.50 and not in 2.51...
Anyway, please try this build and let us know if the problem is fixed: https://ci.appveyor.com/api/buildjobs/e901ki208fnxal0d/artifacts/GitExtensions-2.50.90.1470-Mono.zip

**Comment by yesgrey** [comment]
Yes, the test build works fine again. You can include it in the next 2.51 release.

Thanks a lot for the fix! :)

**Comment by yesgrey** [comment]
Thanks for re-opening the Issue.
 
Still not working fine...

I have a reference remote repository for which I use the alias: Ref
I have several branches, like development, maintenance, maint-7.5.x, maint-7.4.x 

1) If I type in the box (without the quotes) "Ref/development Ref/maintenance" it works fine. Only these two remote branches are shown

2) If I type in the box (without the quotes) "ref/development ref/maintenance" it does not work. I still see all branches, and, when editing the box, sometimes an exception is thrown:
![image](https://user-images.githubusercontent.com/23011691/37557413-7ef5a5dc-2a04-11e8-85b0-c4dcb00ebdaa.png)

3) f I type in the box (without the quotes) "Ref/development Ref/maint-7.5.x" it does not work. I still see all branches, and, when editing the box, sometimes I get the same exception as in 2)

From 2) and 3), it seems that it does not work properly when the case does not match exactly, and when  dashes or dots are used in branch names. Could this be related to #4014?

**Comment by yesgrey** [comment]
Hi, any news on this bug?
I'm pretty much stuck at 2.50.02 because of this... I have tried the latest 3.0 beta and the branch filtering is also now working there.

**Comment by RussKie** [comment]
No news. PRs are welcome.
v3 is still few months away.

**Comment by IEVin** [comment]
When I was investigating this problem i found [same issue](https://social.msdn.microsoft.com/Forums/windows/en-US/83601a49-8f93-4b61-be91-853e1e7ccf41/systemargumentoutofrangeexception-when-trying-to-assign-text-property-of-combobox?forum=winforms).

> With combo boxes if the property DropDownStyle is set to DropDownList then the text will not be editable by the user. Also if you try to change the text programatically it will try to select an item already existing in the drop down with the same text as the text you are trying to set it to. If the text you are trying to set it to does not exist in the list then you will get your invalid index exception.

How to reproduce :
1. Run GE without VS debugger;
2. Create new or open repo with branch "master";
3. Select branch filter and write text that not contains in all branch names (for example "masP" if you have only branch "master");
4. Press enter to apply filter;
5. Select another commit in revision grid;
6. Select branch filter.

Check items collection is empty fix this crash but branch filter continue work incorrect sometimes.

P.S.: When VS debugger is attached NBug.Handler.ThreadException do nothing. Without debugger it crash application and show send report dialog. I think it's bad behaviour because hide real problem from a developer.

**Comment by vbjay** [comment]
NBug doesn't work when you have a debugger attached.  Nbug is there to
catch the unhandled exceptions so we can find out what is going on and fix
it.

**Comment by IEVin** [comment]
> NBug doesn't work when you have a debugger attached. Nbug is there to catch the unhandled exceptions so we can find out what is going on and fix it.

Thread exception doesn't crash application. But if NBug is works it's just close application after send report (invoke Environment.Exit(0)). Developer doesn't see problem but for users it's look like a crash.

**Comment by vbjay** [comment]
What do you think send report does?

**Comment by vbjay** [comment]
It is an unhandled exception.  That IS a crash.

**Comment by IEVin** [comment]
>What do you think send report does?

Send crash report to developers for they know about problem. It's very usefull feature and I have no objections about it.

>It is an unhandled exception.  That IS a crash.

Yes you are right but not in all cases.

If WinForms application have thread exception handler (`Application.ThreadException += OnThreadException;`) before Application.Run it doesn't crash application on unhandled exception in UI thread.

Just add throw `new Exception( "!!!" );` in Click event handler for any control on main form and click on it under debugger and without it. 

For example I add `throw new Exception("!!!");` in `toolStripBranchFilterComboBox_Click(object sender, EventArgs e)` GitUI/CommandsDialogs/FormBrowse.cs: 3029. After it run GE and click on branch filter combobox.

**Comment by RussKie** [comment]
Unfortunately it doesn't. The zip file it creates doesn't leave the user's
machine...

On Sep 26, 2018 11:17 PM, "Ivan Vinogradov" <notifications@github.com>
wrote:

What do you think send report does?

Send crash report to developers for they know about problem. It's very
usefull feature and I have no objections about it.

It is an unhandled exception. That IS a crash.

Yes you are right but not in all cases.

If WinForms application have thread exception handler
(Application.ThreadException
+= OnThreadException;) before Application.Run it doesn't crash application
on unhandled exception in UI thread.

Just add throw new Exception( "!!!" ); in Click event handler for any
control on main form and click on it under debugger and without it.

For example I add throw new Exception("!!!"); in
toolStripBranchFilterComboBox_Click(object
sender, EventArgs e) GitUI/CommandsDialogs/FormBrowse.cs: 3029. After it
run GE and click on branch filter combobox.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4370#issuecomment-424711034>,
or mute the thread

**Comment by vbjay** [comment]
Then it's the developer's job to add try catch and handle the exception.

**Comment by vbjay** [comment]
> Unfortunately it doesn't. The zip file it creates doesn't leave the user's
machine...

It should.  The user has the choice to not send.  We could even add info saying it will be sent to ...

**Comment by IEVin** [comment]
>Then it's the developer's job to add try catch and handle the exception.

Yes of course.
But we can't start all WinForms controls event handlers with try { } catch { }. Furthermore this exception was thrown from the system code.

For this case is usually used `Application.ThreadException`. In GE - `Application.ThreadException += NBug.Handler.ThreadException;`
But, as I said NBug doesn't work with VS debugger.

**Comment by vbjay** [comment]
Here's how you should understand things.  

If you debug and get a ThreadException then that is the same as nbug showing.  Nbug is in place of a debugger.  Technically we should be wrapping those handlers in 

```c#
if(!Debugger.IsAttached)
{
...
}

**Comment by vbjay** [comment]
https://github.com/soygul/NBug/blob/857a5beb500dce4ad334b9afe27ccdc55ec57bcd/NBug/Settings.cs#L259

**Comment by IEVin** [comment]
If we wrapping with `!Debugger.IsAttached` subscription (`Application.ThreadException += NBug.Handler.ThreadException;`) it would resolve this problem.

**Comment by vbjay** [comment]
Send in a pull request to fix it.  

Create an issue linking to this one describing the issue.  

Then create a pull request modifying this  https://github.com/gitextensions/gitextensions/blob/b210331fb67b2362cc1c666ad49911d4666d85e0/GitExtensions/Program.cs#L39

Look for other similar lines and do the same.  ( hint other program.cs files)

**Comment by NN---** [comment]
Still crashing in 3.1RC

**Comment by illfated** [comment]
Git Extensions 3.1.0.5877 Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294 has been released, so I presume it will be necessary to open a new issue ticket and at least have 3.1.0.5877 available for testing before reporting new or remaining issues.

**Comment by RussKie** [comment]
Please raise a new issue with as much information as possible.
