### ISSUE TITLE
Rename "Current branch" to "Checked-out branch" 

### ISSUE THREAD

**Issue by yesgrey** [gitextensions/gitextensions#4371]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
All the menus refer the currently checked-out branch as Current. This is very confusing, because whenever we right click on a certain commit to merge into the checked-out branch the menu option says only Current, and that's very misleading because there is the tendency to consider current as the place we are pointing out at the moment.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
N/A

**What is the expected behavior?**
Ideally the expression "Current branch" should be replaced with one that does not bring any confusion when selecting it on a different commit/branch than the one currently checked out. I suggest "Checked-out branch", but I'm open to other suggestions. ;)

**Environment you encounter the issue:**
- GitExtensions version: All
- GIT version: -
- OS version: -

**Did this work in previous version of GitExtensions (which)?**
No

**Comment by vbjay** [comment]
Based on the action and wording, could replace current branch with {current
branch name}. Here is the problem. You can check out a commit. Not be in a
branch at all. This is why we say current. If your on a branch, we will use
that. I don't think you want a Sha in the menu.

**Comment by pmiossec** [comment]
I agree with this request. Because I think that "Current branch" is in fact an ellipsis for  "Currently checked-out branch"...

**Comment by vbjay** [comment]
https://www.git-tower.com/learn/git/faq/detached-head-when-checkout-commit.
Not exactly.

**Comment by pmiossec** [comment]
@vbjay Why do you talk about about detached head state or checked out commit?
We are talking about "Checked-out **branch**" (not about commit)!

**Comment by vbjay** [comment]
Current doesn't mean current branch always. It can mean current commit in a
detached head. The whole freaking reason I'm saying this idea is not a good
one. Do you want a SHA in the menu?

**Comment by vbjay** [comment]
I'd rather say keep current and mention selected to clarify the current selected commit.

**Comment by pmiossec** [comment]
>clarify the current selected commit.

I'm not sure that's a good thing to either use "current" and "selected" because that has no meaning in git.
"Checked-out" has a real meaining in git.

That's even a really important notion that beginner have difficulties to understand (I have to say it a lot) so displaying/speaking again and again about it could be a good thing.

**Comment by vbjay** [comment]
Current = git rev-parse --verify HEAD
Selected = the commit selected in the GUI.
Checked out branch or checked out commit = wordy.

I would think saying selected in the context menus and other menus to mean
the commit in the GUI while current = HEAD.

**Comment by RussKie** [comment]
>  This is very confusing, because whenever we right click on a certain commit to merge into the checked-out branch the menu option says only Current, and that's very misleading because there is the tendency to consider current as the place we are pointing out at the moment.

Everywhere I see it says "current branch". Unless you are referring to something else - in this case please provide screenshots.

. . .

> Current = git rev-parse --verify HEAD
Selected = the commit selected in the GUI.
Checked out branch or checked out commit = wordy.

I'm with with Jay on this one, I _personally_ see no confusion
![image](https://user-images.githubusercontent.com/4403806/35179716-dc2fad0c-fdf3-11e7-89c0-0e28d6c481d5.png)


However I think we need to improve/fix the wording for detached head:
![image](https://user-images.githubusercontent.com/4403806/35179743-4610c77e-fdf4-11e7-9c25-7b6fbd42ae60.png)

**Comment by yesgrey** [comment]
Hi,

Yes, it always says "Current Branch", and I know that after thinking about it we understand it, but it's not very intuitive... I've shortened "Current branch" to "Current" in some places while typing, sorry for that. ;)

The problem I'm referring is more related with the way the brain works, by paying more attention to stronger words. The dominant word is "Current", and in my experience the brain has a natural tendency to link "Current" with what is being pointed by the cursor/arrow (and later by the branch you select, in case you have more than one branch on the same commit), and it ignores the word branch. Everybody here in our development team (around 30 people) always make this confusion, considering that "Current Branch" relates to the commit/branch that is being selected, and not to the one that is "Currently checked-out". Even I, being perfectly aware of what it means, need to "fight" with my brain regularly. :)

If so many people make this same mistake, I think we could at least agree that it might not be as clear as it could be, but I can accept that for some people this is crystal clear, and so no change is required...

I feel that even by simply removing the word "Current" from all those three options would make it more clear than keeping it, even though I would prefer replacing "current" with "checked-out". Another option could be using the words "active", "work" or "working", since "checked-out" is quite long and a composite word...

Suggested options:
1) Merge into branch; Rebase branch on; Reset branch to here
or
2) Merge into checked-out branch; Rebase checked-out branch on; Reset checked-out branch to here
or
3) Merge into active branch; Rebase active branch on; Reset active branch to here
or
4) Merge into work branch; Rebase work branch on; Reset work branch to here
or
5) Merge into working branch; Rebase working branch on; Reset working branch to here

Regarding the detached head case, since it's not exactly the most common use in Git, I would say that keeping it like it is for the most common case would be fine... but some possible "fit all" solutions could be:
6) Merge; Rebase on; Reset to here
or
7) Merge into checked-out; Rebase checked-out on; Reset checked-out to here
or
8) Merge into active; Rebase active on; Reset active to here

**Comment by yesgrey** [comment]
Sorry, closed this by mistake... newbie mistake ;)

**Comment by yesgrey** [comment]
To add a few more points to the discussion...

If we look at all available options when we right click on a commit, we have options that refer specifically to the selected commit/branch:
-Checkout branch
-Rename branch
-Delete branch

So, the word "current", instead of taking us to a branch in another place, acts as a kind of reinforcement... ;)

**Comment by gerhardol** [comment]
> If we look at all available options when we right click on a commit, we have options that refer specifically to the selected commit/branch:

The options are related to the selected commit, the branches with HEAD on that commit. There is a drop down for the branches.
I see no clarification for these actions.

Maybe "checked-out branch" is better than "current branch" but then the menu need to be updated when no branch is checked out. "Merge into HEAD" maybe?
Not important for me.

**Comment by RussKie** [comment]
Thank you for the good selection list :)
I would probably go for option 7: _Merge into checked-out; Rebase checked-out on; Reset checked-out to here_

Does anyone else have any thoughts or preferences?

**Comment by yesgrey** [comment]
I'm fine with that. As pmiossec referred, "checked-out" has a real meaning in Git, so, it's probably the safest solution. ;)

**Comment by vbjay** [comment]
checked-out is a lot better  and adding commit or branch is superfluous.
Selected could be used in the case of working with the current commit
selected in the gui.

**Comment by yesgrey** [comment]
Would it be asking too much if this could be included in 2.51?... ;)

**Comment by pmiossec** [comment]
@yesgrey that's not me that decide but as far as I can tell, there is few chances because there is the translation to do and above all, there is no pull request to fix that.

Perhaps if you do it quickly...

**Comment by RussKie** [comment]
Sorry folks because there are translations that need changing this won't be
included in 2.51.
It can/will be included in a following release.

**Comment by yesgrey** [comment]
I can take a look and see if I can do it, but the translation part is what worries me most... I'll check and see.

**Comment by vbjay** [comment]
We use https://www.transifex.com/

**Comment by pmiossec** [comment]
I think that you have nothing special to do to manage the translation
(because the only things that you have to do is update existing strings) .

That's just that the file containing the strings to translate for the
version soon to be released has already been put to transiflex. And already
translated by translaters.

We can't ask again to do it because it will add some more delay before the
release (and the release perimeter has already been defined).

I hope that the next releases will be more frequent, so it should not be a
big deal...

On 25 Jan 2018 19:43, "yesgrey" <notifications@github.com> wrote:

I can take a look and see if I can do it, but the translation part is what
worries me most... I'll check and see.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4371#issuecomment-360560393>,
or mute the thread

**Comment by yesgrey** [comment]
Ah, ok, didn't know that the translations were done like that! Anyway, I took a quick look and the words "current branch" show up multiple times and in 141 files, so, no way it could be done so quick, unless we assume that it would be acceptable to replace it in all places, which I think might not be the case... on the right-click drop down menu only, it could be quick, but if we agree that "checked-out" would be preferable to "current branch", then maybe we should make a consistent change on the entire application.

What do you think?

**Comment by RussKie** [comment]
Ignore *.xlf files - these are auto-generated. 
You will need to change strings in *.cs files - those defined in `new TranslationString("...")` or assigned in *.Designer.cs

**Comment by yesgrey** [comment]
Thanks for the info, that makes the task much easier to implement. I will see if I can start working on it.

I guess the "pull request only" tag means that this new feature will be implemented only if someone wants to implement it, right?

**Comment by RussKie** [comment]
> I guess the "pull request only" tag means that this new feature will be implemented only if someone wants to implement it, right?

Yes :)

**Comment by RussKie** [comment]
We are not going to do this.
