### ISSUE TITLE
Show detailed push information

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4372]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
The help diagram in the push dialog shows a diagram of what would happen if pushed..  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Use git rev-parse with ``@push`` to show exactly what would happen.  Show a revison graph of the changes.  https://git-scm.com/docs/git-rev-parse#git-rev-parse-emltbranchnamegtpushemegemmasterpushemempushem

Add a fetch button to allow the local tracking branch to be updated.  
**Environment you encounter the issue:**

- GitExtensions version:NA
- GIT version: NA
- OS version: NA

**Did this work in previous version of GitExtensions (which)?**
No.

**Comment by vbjay** [comment]
Example command

```
git log master...$(git rev-parse --symbolic-full-name master@{push})
```

**Comment by RussKie** [comment]
Are you able to explain further?

**Comment by vbjay** [comment]
So instead of a static help diagram, I was thinking a limited revision graph showing the commits that would be pushed. The command I showed does this. The fetch button would allow you to update the tracking branch to get an updated view. 

Is there such an animal as get the last date I pulled or fetched the x branch in git?

**Comment by gerhardol** [comment]
> Is there such an animal as get the last date I pulled or fetched the x branch in git?

Kind of. Git writes to .git/FETCH_HEAD when fetching (used at pull to merge)
Note that if using worktrees, each worktree has a separate file like .git/worktrees/gitextensions_4/FETCH_HEAD

https://stackoverflow.com/questions/29091536/how-can-i-see-the-time-of-my-last-git-pull

Interesting feature, find it more "fun" than useful though, at first look

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.

**Comment by RussKie** [comment]
The help is being moved from individual forms to the online docs.
