### ISSUE TITLE
Wrong diff for stashed untracked files

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4373]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
![gitext](https://user-images.githubusercontent.com/1003909/35109851-bdb388d0-fc77-11e7-9c10-efa016084454.png)
1. There is a new file in file list, but the diff window shows it as it was deleted. Seems like arguments order for diff command are inverted.
2. The diff tab title says that it is not supported - don't know what is not supported here.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create a new file and add some content.
2. Stash including untracked files.
3. Go to the stash untracked commit and see the diff for the newly created file.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.RC2
- GIT version: 2.15.1
- OS version: win10

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.50

**Comment by vbjay** [comment]
Does it look different when viewing the stash in the stash dialog?

**Comment by gerhardol** [comment]
The untracked "commit" in a stash does not have a parent, it is the third parent of "the working dir commit" in a stash. So should there be a diff here?

**Comment by gerhardol** [comment]
Diff for files without a parent will have to be specially handled. 
In addition to Browse-stash-untracked, this should occur for the initial and detached commits.
The diff is to the working directory, if the file exists there, otherwise empty

In 2.50, there were a lot of special handling, I tried to simplify the handling, but this case remains.
null has been used for untracked, so it may not be trivial to change.

**Comment by gerhardol** [comment]
A test build is here
https://ci.appveyor.com/api/buildjobs/b4w2wu6lu17drok7/artifacts/GitExtensions-2.50.90.42-Mono.zip
for changes
https://github.com/gerhardol/gitextensions/tree/bugfix/n4373-browse-stash-untracked

Will look at this again tomorrow after work (will be a long day though)

**Comment by jbialobr** [comment]
Test build works well, thank you.

**Comment by gerhardol** [comment]
I created PRs
1. Setting the tab title to "Parent -> Selection" even if there is no parent in this case, to avoid a tricky special case. I want to remove the dynamic title and put this info in the tab instead some time
2a. Commits without parents (like the stash-untracked) did not get IsTracked set, so wrong paths were taken in some situations. FormStash had an incorrect check for IsTracked
2b. Stash form reversed the diff

![image](https://user-images.githubusercontent.com/6248932/35176493-ba668238-fd79-11e7-951d-adb039d0c679.png)

**Comment by gerhardol** [comment]
> I presume #4384 is for 1 and #4385 is for 2. Is that correct?

Correct

**Comment by RussKie** [comment]
if all could do a round of tests to verify it is fixed - that'd be great.

**Comment by RussKie** [comment]
I've pulled the latest master and diffs and stashes look good to me
@jbialobr are you happy with the fix?
