### ISSUE TITLE
Commit view shows inverted diff output

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#4374]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
Commit view shows inverted diff. Added files are shown as removed, the same with changed lines.

For example, in revision graph (commit history):

```diff
diff --git a/ports/sdl2-mixer/CONTROL b/ports/sdl2-mixer/CONTROL
index 978b87d1..e66081fc 100644
--- a/ports/sdl2-mixer/CONTROL
+++ b/ports/sdl2-mixer/CONTROL
@@ -1,4 +1,4 @@
 Source: sdl2-mixer
-Version: 2.0.2-1
+Version: 2.0.2-2
 Description: Multi-channel audio mixer library for SDL.
```

In commit view:

```diff
diff --git a/ports/sdl2-mixer/CONTROL b/ports/sdl2-mixer/CONTROL
index e66081fc..978b87d1 100644
--- a/ports/sdl2-mixer/CONTROL
+++ b/ports/sdl2-mixer/CONTROL
@@ -1,4 +1,4 @@
 Source: sdl2-mixer
-Version: 2.0.2-2
+Version: 2.0.2-1
 Description: Multi-channel audio mixer library for SDL.
```
In particular, **revision graph** shows `index 978b87d1..e66081fc`, but **commit view** `index e66081fc..978b87d1`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* Open repository
* Select any commit, look on its diff
* Open commit (double click on it), check its diff

**What is the expected behavior?**
Diff must be the same.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.RC2
- GIT version: git version 2.15.1.windows.2
- OS version: Windows 7 x64

**Did this work in previous version of GitExtensions (which)?**
Sure. I guess, 2.50 worked fine.

**Comment by pravic** [comment]
This issue is related to #4373.

**Comment by vbjay** [comment]
Think we need to take a step back and create a master issue that details all the reversed diff locations( commit window, stash, diff tab, commit details window...)

Create a list like this

- [x] commit window
- [ ] stash
...

**Comment by RussKie** [comment]
@gerhardol has a fix 
Could you please try https://ci.appveyor.com/api/buildjobs/dpkc0yggxl4rji40/artifacts/GitExtensions-2.50.90.1451-Mono.zip
