### ISSUE TITLE
Dialog for selecting branches to view

### ISSUE THREAD

**Issue by yesgrey** [gitextensions/gitextensions#4381]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Manually typing the branches names in the Branches box to select which branches to view. For more than two branches, or for branches with long names is not good enough, because sometimes there are some typos.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Opening a dialog listing all branches with a check box on each so it could be selected which branches should be visible. This dialog already exists for the "Push multiple branches dialog", so, maybe that code could be reused for this...

**Environment you encounter the issue:**
- GitExtensions version: All
- GIT version: -
- OS version: -

**Did this work in previous version of GitExtensions (which)?**
No

**Comment by RussKie** [comment]
v3 introduced a panel on the left that lists all available branches:
![image](https://user-images.githubusercontent.com/4403806/48320844-ef94cf00-e671-11e8-82fa-bc99f60c58ef.png)
