### ISSUE TITLE
Select order of branches drawing on history view

### ISSUE THREAD

**Issue by yesgrey** [gitextensions/gitextensions#4382]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Branches are drawn in a certain order that changes with time

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
N/A

**What is the expected behavior?**
It would be good to be able to define the order of branch drawing on the history window. When we have a certain defined branching strategy, it is good to have the so called "reference" branches drawn always in the same order, which makes it simpler to follow the relations between these branches and the "working" branches. 

**Environment you encounter the issue:**
- GitExtensions version: All
- GIT version: -
- OS version: -

**Did this work in previous version of GitExtensions (which)?**
No

**Comment by vbjay** [comment]
Can you use screenshots and describe in more detail?

**Comment by gerhardol** [comment]
To do something like this, the description must be described in much more details.
For example, how to define the reference branches
These type of requests have a great potential to be very complicated to implement and still adding no value

**Comment by drewnoakes** [comment]
@yesgrey the order was codified and made stable by @jbialobr in #5077.

If that change doesn't achieve what you want, please give a concrete example to clarify.

**Comment by RussKie** [comment]
Closing due to lack of follow up
