### ISSUE TITLE
Browse Diff Reset: Multiple parents are not handled

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4387]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Browse Menu reset has incorrect handling for multiple parents (merge commits, as multi selection of more than 2 is ignored). The first parent is always used.

The label in the drop down menu is always describing the first parent too.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
 * Select merge commit
 * Select a file in the second group
 * The reset drop down menu contains correct "B" revision but the first "A" revision

**What is the expected behavior?**
The selected parent is used, not the first parent

**Environment you encounter the issue:**
- GitExtensions version: all

**Did this work in previous version of GitExtensions (which)?**
no

![image](https://user-images.githubusercontent.com/6248932/35198844-0d6b42b2-fef5-11e7-965d-254f908a4e63.png)

**Comment by gerhardol** [comment]
The selected revision (commit) is really global and could be visualized in some way common for all tabs.

There are a number of ways this can be solved:
 * Get the labels from the selected items to get the first/parents. The problem is what to do for multi selections where the items have different parents, just display <multiple>?
 * Use the parent "groups", the "Diff with: <branch>". This will then have to be displayed also for single parents. The "selected" could always be displayed too, either in the diff list or in the menu. The dropdown would then just be Selected and Parent, no extra information.

Similar problem for the Difftool menu, but there the alternatives are displayed as A and B, so this display is correct (just confusing).
 
I would like to use this solution in other situations:
 * Provide better descriptions also for difftool (which is A and B? which did I select first and second?)
 * "Save as (B)" is confusing.
 * Remove the "dynamic" tab title (like "A: First --> B: Second") as it is confusing and is lost when selecting another tab
 * Display multi selections for diff tab (similar as for merge commits)

**Comment by RussKie** [comment]
I like the current presentation. 
Perhaps we need to fix the parent issue

**Comment by gerhardol** [comment]
> I like the current presentation.

How to handle multi selections, "multiple" or something?

How to handle Difftool?

Do you want to keep the changing tab title?

**Comment by RussKie** [comment]
I meant this:
![image](https://user-images.githubusercontent.com/6248932/35198844-0d6b42b2-fef5-11e7-965d-254f908a4e63.png). There is a lot of correlating information which IMO makes it easier to use.

From pure usability perspective I find he second lot of screenshots (with "Parent A, Current B") less meaningful.

> How to handle multi selections, "multiple" or something?

Is that for multiple files selected in the diff list? If they are from the same parent - then parent, if they are from multiple parents - then yes, "multiple" may be justified.

> Do you want to keep the changing tab title?

I personally find it annoying that the tab constantly changes its width. So I don't mind it we fix its title.

> How to handle Difftool?

I am afraid I don't understand the question. Please elaborate.

**Comment by gerhardol** [comment]
thanks for the feedback

If tab title is changed, there is no explanation of A and B
The "Save (B) as" could be renamed to "Save selected as"
For reset, you prefer the description if single A revision and <multiple> for multi-selection

For difftool, the version is named as A and B as below, there we do not want the full description for every A and B (and A is not static as for reset). 

![image](https://user-images.githubusercontent.com/6248932/35246921-c67eeed8-ffc8-11e7-97ba-0dc5a9089411.png)

The difftool could be presented as follows, where A presented as for Reset
("A" can be always be displayed in the filelist, but nothing there now that informs that it is A). 

![image](https://user-images.githubusercontent.com/6248932/35247826-198f499e-ffcc-11e7-8023-0ca2d5b92053.png)

**Comment by gerhardol** [comment]
Will open a separate issues for:
 * Browse Diff should allow comparison of multiple selected versions.
 * Remove the "dynamic" title for the Diff tab. Explain A and B in difftool dropdown (similar to reset)

Reset will always have Selected and Parent (First and second does not make sense with multiselection)
The "from"/first/parent commit will always be displayed (this is not a strict requirement, but it simplifies).

I will probably submit only one PR for all changes, as they are related. The PR will be separated in several commits tough. (More code is removed than was what added.)

Proposal of how this will look like in a few scenarios.

![image](https://user-images.githubusercontent.com/6248932/35464547-bf437d74-02f6-11e8-83c3-98d1a753bd7c.png)

![image](https://user-images.githubusercontent.com/6248932/35464621-2e56fb50-02f7-11e8-973f-077826c38621.png)

![image](https://user-images.githubusercontent.com/6248932/35464647-534867be-02f7-11e8-9a53-490c272381e6.png)
