### ISSUE TITLE
Provide feedback for build server connection issues.

### ISSUE THREAD

**Issue by dalee-bis** [gitextensions/gitextensions#4388]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

When the there is an issue with build server integration (e.g. configuration error), it is difficult to diagnose as there is no feedback to the user.

**What is the expected behavior?**

There should be some feedback. Perhaps the build tab should always be present in the lower pane? If the build server isn't configured, display a button to open the option to the build server config page. If the build server is configured, but cannot be contacted, display error information here and if everything is working fine, display the usual build page.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.RC2
- GIT version: 2.13.2.windows.1
- OS version: Windows 8.1 (64-bit)

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
