### ISSUE TITLE
Multiple Git Bash consoles, taskbar pinning issues (Windows 7 & 10)

### ISSUE THREAD

**Issue by mccreeker** [gitextensions/gitextensions#4391]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Opening from Git Extensions Terminal button opens a colorized Windows console window from path `C:\Windows\System32\cmd.exe` (in the title bar) with its own look and configuration; opening the Git Bash program (installed through Git Extensions) opens its own other look and configuration showing path (in the title bar) `/usr/bin/bash --login -i`. Trying to pin the one from the Git Ext button pins it as a Windows console program when I'd rather use that for just Windows CLI. If I pin the Git Bash program window, re-opening it opens a new box in the taskbar rather than using the icon's box.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Install the latest Git Extensions (2.50) onto Windows (7 or 10, it behaves the same) along with its suggested Git Bash install, then open Git Ext and click the Terminal button. Try Git Bash (installed with it) instead and notice the difference.

**What is the expected behavior?**
To open the Git Bash console window in its own program and not Windows CLI, leaving Windows CLI to have its own taskbar pin box.

**Environment you encounter the issue:**
Windows 7, 10

- GitExtensions version:
- GIT version: 2.50
- OS version: W10Pro

**Did this work in previous version of GitExtensions (which)?**
1.x

**Comment by RussKie** [comment]
Here's what I get on Win 8.1:
![image](https://user-images.githubusercontent.com/4403806/35316769-70019820-0127-11e8-8afb-bac9fd6cf522.png)

I'll check W10 tonight

**Comment by GintasS** [comment]
@RussKie should we close this?
