### ISSUE TITLE
Git config diff.noprefix true option breaks most of GitExtensions functionality

### ISSUE THREAD

**Issue by ashumkin** [gitextensions/gitextensions#4392]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
> Unsupported file:
> System.FormatException: Old filename not parsed correct --- ...<filename>
> ....

error is shown in any diff view window.
Diff in commit window is broken.
"Generate a list of changes in submodules" functionality is broken.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Take any repository working copy.
1. Execute `git config diff.noprefix true` in it (Or set this option globally `git config -global diff.noprefix true`).
1. Open GitExtensions for this repository.
1. View `Diff` tab to see a patch of a commit. Observe a bug

**What is the expected behavior?**
Any diff is shown with no error.

**Environment you encounter the issue:**
- GitExtensions version: 2.51RC2
- GIT version: 2.5.1 (custom Cygwin build)
- OS version: Windows 7 SP1
- `git config --global diff.noprefix true`

**Did this work in previous version of GitExtensions (which)?**
I do not know. (*2.48.05 and 2.51RC2 are broken*)

**Comment by RussKie** [comment]
Is there a particular reason you require this setting?
Thinking out loud and having not looked at the code, what if GE would set `diff.noprefix false` upon opening a repository?

**Comment by ashumkin** [comment]
> Is there a particular reason you require this setting?

*Actually, I do not use GUI (GE) full time (I prefer CLI). So, this issue I discovered accidently when I've discussed some issues with my colleague, who does use GE.*
*Explaining further: I prefer this setting because it is convenient to quick copy-paste filenames from `diff`s (mouse double left click in terminal, mouse middle click - voi-la) rather then to select a filename without a prefix or to erase a prefix after paste...*

> what if GE would set diff.noprefix false upon opening a repository?

Change repository setting? I cannot agree with that.
My quick solution woud be `git -c diff.noprefix=false ...` ;)

**Comment by gerhardol** [comment]
The easiest workaround should be to use a separate Git home for GE. You may need to make certain settings twice.

It is hard to prevent all user settings that may break GE.
Possible ways to handle this in GE:
 * Warn at startup about invalid settings
 * Add an "override level" with settings that cannot be changed (not sure if that can be done)
 * Change all affected calls, overriding the known illegal values like ashumkin suggests (already done for another diff settings). I believe diff is "centralized", other commands are not so this is not a simple genral solution.

**Comment by RussKie** [comment]
I'm curious if other tools (like sourcetree etc) work with that setting

On 25/01/2018 3:24 AM, "Gerhard Olsson" <notifications@github.com> wrote:

The easiest workaround should be to use a separate Git home for GE. You may
need to make certain settings twice.

It is hard to prevent all user settings that may break GE.
Possible ways to handle this in GE:

   - Warn at startup about invalid settings
   - Add an "override level" with settings that cannot be changed (not sure
   if that can be done)
   - Change all affected calls, overriding the known illegal values like
   ashumkin suggests (already done for another diff settings). I believe diff
   is "centralized", other commands are not so this is not a simple genral
   solution.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4392#issuecomment-360189780>,
or mute the thread

**Comment by jbialobr** [comment]
>GE requires i18n.logoutputencoding = UTF-8 (and i18n.commitencoding = UTF-8?) 

That should not be true. GE takes into account these settings.

I would not call this issue a Bug. It is more like known limitation. GE expects that git cli returns its outputs in a defined way. I propose to label this issue as a `feature request` and `pull request only`

**Comment by ashumkin** [comment]
> That should not be true. GE takes into account these settings.

Currently, when I change these settings (to non-UTF-8 encoding) globally or in a project, GE shows "corrupted" log messages. That means GE **requires** `i18n.logoutputencoding` to be set to `UTF-8` (or not set to non-UTF-8 encoding, at least)

**Comment by ashumkin** [comment]
> GE expects that git cli returns its outputs in a defined way

I consider this as a bug when a software fails unexpectedly with an unobvious way of a solution. *Fortunately, I've faced the same problem with GitLab tests [recently](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/15472), so I have not spent too much time to investigate the reasons.*

**Comment by jbialobr** [comment]
>Currently, when I change these settings (to non-UTF-8 encoding) globally or in a project, GE shows "corrupted" log messages. That means GE requires i18n.logoutputencoding to be set to UTF-8 (or not set to non-UTF-8 encoding, at least)

Did the test and it works fine. Could you create a minimal repository (with locally modified gitconfig) that we can reproduce the issue, zip it and upload here?

**Comment by ashumkin** [comment]
Sure, but I've discovered that it is not so simple. There's some combination of circumstances to reproduce the bug...

Here is the repo [ge-commit-messages-bug-demo.zip](https://github.com/gitextensions/gitextensions/files/1664583/ge-commit-messages-bug-demo.zip) but I still investigating the combination.

**Comment by gerhardol** [comment]
I see a number of possible solutions for this issue (more than one can be implemented):
 1. Document known incompatible settings and describe a workaround (change home).
 2. Warn at startup 
 3. Override known bad issues (parameters when invoking git or specific commands like git-diff)

**Comment by vbjay** [comment]
I like 1 and 2.  3. Stinks of "Heyyyy I expected X.  Stupid application..."

**Comment by gerhardol** [comment]
3. is the easiest for this problem and is reasonable for common settings.
I added one in 2.51
https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitModule.cs#L99

But a standard solution would be good, everything cannot be handled.

**Comment by ashumkin** [comment]
> I added one in 2.51
> https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitModule.cs#L99

IMHO, #4131 has the same reasons to be reproduced: unexpected output of `git diff` (because of uncontrolled (by GE) Git settings). So, to be consistent, or THIS issue must be solved by the same way as #4131 (so, there is nothing to discuss) or both issues must be solved in the way of controlled Git settings = different HOME.

**Comment by ashumkin** [comment]
> 3. Stinks of "Heyyyy I expected X.  Stupid application..."

I think, it's not quite right statement. I'd said "*Give me exactly what I want regardless your configuration is*"...

**Comment by ashumkin** [comment]
I've taken a look at GE settings and have found that it is an ability to redefine HOME in there (also, there is a note there "Change the default only if you experience problems"), so, the issue can be easily solved this way.

**Comment by ashumkin** [comment]
> Did the test and it works fine.

@jbialobr, I'm sorry, it seems I've observed the encoding bug on v2.49 that have no fix for #3707 (I have two machines: one of them has GE updated to v2.51RC2, another one had v2.49). So, there was an already fixed bug.

**Comment by RussKie** [comment]
So how do we want to tackle this one? 

Show a warning to the user that settings may render GE unusable and offer to change the settings?

**Comment by ashumkin** [comment]
I'd solve this as #4131 resoves #4130 (to be consistent) ))

**Comment by gerhardol** [comment]
> I'd solve this as #4131 resolves #4130 (to be consistent) ))

That is the easiest right now. 
But I do not want to come in to a situation where every possible setting has to be overridden
The use of git-diff has to be reviewed, there may be a few other places the command is called (may not be of importance for this issue).
