### ISSUE TITLE
Folder history / Filter on folder name

### ISSUE THREAD

**Issue by jeroendv** [gitextensions/gitextensions#4393]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
At the moment the git history can be filtered by file
* Ctrl+f > 'FileFilter'
* choose 'File History' from context menu when right clicking on a file in the File Tree 
* others?

**What is the expected behavior?**

However I would like the ability to filter  the git history by folder.
i.e. show all commits in the GUI that are listed by `$ git log <path>`

Ideally this can be done
* though context menu from folder in file tree
* filter box in toolbar
* Ctrl+f filter menu
* ...

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.15.1.windows.2
- OS version:  Windows 7 Pro

**Did this work in previous version of GitExtensions (which)?**

**Comment by jnnnnn** [comment]
I want this too!

**Comment by RussKie** [comment]
Send a pr :)

**Comment by pavlexander** [comment]
3 years later - this feature is not yet implemented.. Does anybody know if it's possible to write an extension for git extensions to show the change history in folder?

**Comment by pmiossec** [comment]
>3 years later - this feature is not yet implemented.. 

I think no one wished it enough to develop it. You still can send a PR

>Does anybody know if it's possible to write an extension for git extensions to show the change history in folder?

I think it will be easier if you develop it in GitEtxensions and send a PR.

**Comment by pavlexander** [comment]
@pmiossec 
Normally we would use the `git log .` command to see the commits related to the folder. This functionality natively supported by Git. Unfortunately I don't have the necessary time and technical knowledge to use the command's output and implement the necessary changes in `gitextensions`. I will leave up to devs :)

For now - easy workaround is by using `gitk` utility:

```sh
gitk.exe -- some_path_here
```

The UI is not the prettiest but it does it's job fine..

In my scenario, however, I wanted to use the functionality in `VisualStudio` for checking the folder history. So I ended up creating an external tool. The script I have written is avoiding using `GitExtensions` altogether. It's based on `gitk` tool and `powershell`.

First define a new tool in `VS`:

![image](https://user-images.githubusercontent.com/20644772/109800492-e9053980-7c25-11eb-9cb0-407d4b1a8f37.png)

![image](https://user-images.githubusercontent.com/20644772/109800073-6b412e00-7c25-11eb-9d22-05bad33e2b0b.png)

```text
name=Git Folder History
exe=C:\windows\system32\windowspowershell\v1.0\powershell.exe
args=-file SOMEPATH\extCommandItemHistory.ps1 $(ItemDir)
workingDir=$(SolutionDir)
```

`extCommandItemHistory.ps1`
```powershell
Param(
  [Parameter(Position = 0)][String]$TargetPath
)

Write-Host "TargetPath:'${TargetPath}'"
#Convert-Path $TargetPath

$PathIsFolder = Test-Path -Path $TargetPath -PathType Container
if ($PathIsFolder) {
	Write-Host "Ok. Valid path"

	# OPTIONAL: check ignore white spaces option when program loads
	# Add-Content "C:\Users\CHANGE_WITH_YOUR_USER\.config\git\gitk" "set ignorespace 1`n"

	#& gitk.exe -- $TargetPath
	Start-Process "gitk.exe" -ArgumentList "--", $TargetPath -PassThru -Wait
}
else {
	Write-Host "Not a valid path"
}
```

then bind the command to some hotkey. ex. `ctrl + num1`

![image](https://user-images.githubusercontent.com/20644772/109800743-400b0e80-7c26-11eb-93a5-29ca28dd03f6.png)

**p.s. index of command matters!**

To use - select an item in solution explorer, click on hotkey and enjoy.

Anyways, this post is just an example of how you can build workarounds while waiting for a proper fix :)

**Comment by pmiossec** [comment]
In fact, thinking about it again, what is different in this feature request than what we can already do by right clicking on one file tree folder? 

![image](https://user-images.githubusercontent.com/460196/109802066-9de82800-7c1f-11eb-92ac-f10a6892fd1b.png)

**Comment by pavlexander** [comment]
I agree.. It looks what was asked in original ticket, but works in a different way than I would expect..

**Despite finding all the commits associated with the folder - the window does not present an option to only display the patched files.** So basically every single file is shown in commit section:

![image](https://user-images.githubusercontent.com/20644772/109808968-6e8de700-7c30-11eb-8ec5-177a1e2c88e6.png)

command: `gitex filehistory XXX\Server`

## in comparison

If you check the `gitk` tool diff window you will see the following:

![image](https://user-images.githubusercontent.com/20644772/109808306-99c40680-7c2f-11eb-95c6-0f41f6940248.png)

Only the files that are in target folder presented ("server" folder).. See on the right.

## side note

Also, I don't know if this is correct place to report this issue, but IF the **"patch-view"** functionality gets implemented in the program, it would be nice to have this functionality also available in VS extension :) Currently if you select a project/solution and click on "File history":

![image](https://user-images.githubusercontent.com/20644772/109809264-c75d7f80-7c30-11eb-9161-278649454988.png)

![image](https://user-images.githubusercontent.com/20644772/109809806-671b0d80-7c31-11eb-8331-5f8b192083d3.png)

![image](https://user-images.githubusercontent.com/20644772/109809334-d9d7b900-7c30-11eb-9bd3-2f00775f967d.png)

It will actually present you with the commit associated for the `sln` file, not the "folder" of the project:

![image](https://user-images.githubusercontent.com/20644772/109809767-5ec2d280-7c31-11eb-9044-82f90b3e835b.png)

When selecting the folder - file history option is not even available:

![image](https://user-images.githubusercontent.com/20644772/109809989-a2b5d780-7c31-11eb-8143-95e23d62e408.png)

![image](https://user-images.githubusercontent.com/20644772/109810011-ab0e1280-7c31-11eb-8740-07af28d48633.png)

It should be able to possible to view the history of changes for all the "folder" type of entities in `visual studio`..

## summary

1. Maybe I should be creating another "feature request" issue for adding "patch-view" option to file changes window?
2. do you know if the same team is also responsible for VS extension? I.e. would it be OK if I included info from "side note" in the same ticket?

**Comment by pmiossec** [comment]
>Despite finding all the commits associated with the folder - the window does not present an option to only display the patched files

It could be seen as an added value ;)
Otherwise, the workaround is to put the folder path in "Filter path using a regex" filterbox.
Perhaps, yes, there is room for improvement by adding an option to enable/disable that and by filtering by default...

>side note

>Also, I don't know if this is correct place to report this issue, but IF the "patch-view" functionality gets implemented in the program, it would be nice to have this functionality also available in VS extension :) 

This feature request must be created in the [vsix repository](https://github.com/gitextensions/gitextensions.vsix/issues).

But I don't think it will be easy to do (that's why you don't already have it) because all the commands you get from inside Visual Studio that requires a parameter get this parameter interpolated from the current file opened in Visual Studio. And so, that can't work for this feature.

We have to do it from another way that requires more work...

**Comment by pavlexander** [comment]
> But I don't think it will be easy to do (that's why you don't already have it) because all the commands you get from inside Visual Studio that requires a parameter get this parameter interpolated from the current file opened in Visual Studio. And so, that can't work for this feature.

I don't think that is true. 

Firstly this does not explain why `.sln` file history is showed, when `.csproj` file is "active" in editor window:

![image](https://user-images.githubusercontent.com/20644772/109815813-bb75bb80-7c38-11eb-86ad-2f45ea3dcd8d.png)

Secondly, when creating external tool in `VS` we are given several [variables](https://docs.microsoft.com/en-us/visualstudio/ide/managing-external-tools?view=vs-2019) to chose from:

> Item Path | $(ItemPath) | The complete file name of the current file (drive + path + file name).
> Item Directory | $(ItemDir) | The directory of the current file (drive + path).

Using these 2 - we can bind 2 different commands - one for opening the history of file, second is for viewing the history of folder. That's what I used in external tool.  :) However, I agree that these might not be available in `vsix` context, in that case we have some solutions posted on the internet [here](https://social.msdn.microsoft.com/Forums/en-US/499dd480-6fb3-4b56-bc8e-b1920c3e8dde/vs-package-how-to-access-current-selected-item-in-solution-explorer?forum=vsx) and [here](https://stackoverflow.com/questions/13194880/how-to-get-the-details-of-the-selected-item-in-solution-explorer-using-vs-packag)..

**Comment by pavlexander** [comment]
request created for `vsix`: https://github.com/gitextensions/gitextensions.vsix/issues/17

**Comment by pavlexander** [comment]
feature request created for `git extensions` stand-alone app: https://github.com/gitextensions/gitextensions/issues/8916

**Comment by pavlexander** [comment]
as was mentioned by mr @pmiossec I think the original issue is irrelevant anymore. The ticket could be closed.

> **What is the expected behavior?**
> 
> However I would like the ability to filter the git history by folder.
> i.e. show all commits in the GUI that are listed by `$ git log <path>`

The functionality of viewing commits belonging to folder is achieved by selecting the folder and clicking `view changes` from the context menu.

The view is not very useful without the `patch` view, but that's another story ;) see my feature request above.

**Comment by GintasS** [comment]
As per @pavlexander comment, we should close this.
