### ISSUE TITLE
Support GitHub co-authors

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4403]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
We support using git authors in commits.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Add co-author GUI to commit window that adds the correct trailer to the commit message. 

Probably add this to the plug-in and add plug-in access to the commit message. 

https://github.com/blog/2496-commit-together-with-co-authors
**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: na
- OS version: na

**Did this work in previous version of GitExtensions (which)?**
Sort of with author in commit.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
