### ISSUE TITLE
Feature Proposal: Git command learning mode

### ISSUE THREAD

**Issue by erikleo** [gitextensions/gitextensions#4408]
The purpose of the feature is to allow GitExtensions users to be become more familiar with git command line commands, and allow Git extensions to be used as a tool to learn commands that are needed when GitExtensions is not available.

Git command learning mode would be a setting defaulted to off that can be turned on via the settings menu.

When the setting is turned on then for every button that would result in a git command being executed, there would be a tooltip that displayed the actual git command that is about to be run.

For example in the commit window if you click on the "Reset all changes" button you get a confirmation window asking if you are sure you want to reset your changes.  If you were to mouse over the Reset button then you would see a tooltip that displays "git reset --hard".

Additionally this will provide extra info for people already familiar with git commands but not sure exactly how GitExensions is going to perform a complicated task.

While we all love git extensions here, I think we can also recognize that sometimes we need to use the command line.  What better way to get the details for complicated commands than using the tool that we are already familiar with.

**Comment by RussKie** [comment]
Whilst the request has merits it is a monumental task and it isn't
something we can easily implement.

A user can see what git is doing in the progress console window (unless it
is set to autoclose) and in git log window (i think it is under Commands
menu).

**Comment by RussKie** [comment]
Correction: full git log is available via _Tools > Gitcommand log_

![image](https://user-images.githubusercontent.com/4403806/35619164-375de154-06d1-11e8-8da8-95fc33df851f.png)

**Comment by erikleo** [comment]
Hi Russ, thanks for the info.  While useful, the log and status window don't really address the goal.  Given the difficulty of reversing most commands it is not practical to execute commands just so you can see the command that was run.  The value of this feature would be a preview without actual execution.

**Comment by RussKie** [comment]
One can always create a test repo to practice and to learn commands. Seeing what GE executes under the cover helps in that process.

**Comment by joshia89** [comment]
Hey erikleo,

I agree with RussKie here. Whole point of a Git GUI is to obfuscate the command line so that the users do not have to deal with complex commands.

**Comment by erikleo** [comment]
Hi joshia, thanks for the reply.  I don’t think it is fair to say that the point of a Git Gui is to obfuscate the command line.  If that were the case, GitExtensions would never put a command line interface as the 4th tab on the main window.  What GitExtensions does well is empower the user to best take full advantage of the underlying power of Git itself.    Often this is best done visually but there is no reason to hide the fact that it is extending, not replacing a command line tool.

I do understand that Russ’ comments about the work required though.  It seems all the logic to create the git command(s) is done after a button press, not before so pre calculating it could require a major refactor, so the work may not be worth the benefit.

I tried taking a look at the git command log as suggested by @RussKie,  but unfortunately there is a lot of noise in there and it is pretty difficult to see the actual commands run.  Maybe we could put a filter on it for commands that actually affect the repo, vrs commands that git extensions uses for state updates.

**Comment by vbjay** [comment]
Just filter out the git log and git status messages, and any ls-files call.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
