### ISSUE TITLE
Clone error

### ISSUE THREAD

**Issue by RSV-SVS** [gitextensions/gitextensions#4410]
"C:\Program Files\Git\bin\git.exe" clone -v --recurse-submodules --progress --no-checkout "ssh://gizgit@192.168.0.54/home/csgit/git/gi.git" "C:/svs/repo3/GPI"
Cloning into 'C:/svs/repo3/GPI'...
**fatal: protocol error: bad line length character: gizg**
Done

Press Enter or Esc to close console...

**Comment by pmiossec** [comment]
And if you remove `ssh://`?

**Comment by RussKie** [comment]
Does the same command run from bash?

**Comment by RSV-SVS** [comment]
remove ssh did not help

run from bash executed fine

**Comment by RSV-SVS** [comment]
afraid that the problem with ssh on the server

**Comment by RussKie** [comment]
> afraid that the problem with ssh on the server

so the problem is not with the app, is it?
