### ISSUE TITLE
Depreciation of Mono

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4415]
**Do you want to request a *feature* or report a *bug*?**
"feature"
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
#4308 proposes removal of Mono target for GitExtensions
This issue is opened to track removal/disabling of Mono that is in the way.

**What is the expected behavior?**
No Mono slowing down GE development

**Environment you encounter the issue:**

- GitExtensions version: master
- OS version:  Windows

**Did this work in previous version of GitExtensions (which)?**
Mono WinForms have been dead for almost 10 years, so support has deteriorated...

**Comment by gerhardol** [comment]
For discussions about Mono removal, see #4308 
This is to discuss what to remove and when
A separate mono maintenance branch is for sure possible, if there is a maintainer for it

Build environment
 * travis build
 * Rename MakeMonoArchive to PortableArchive, or just zip GitExtensions/bin/<configuration> ?
 * Remove BuildInstallers.Mono.cmd
 * Remove GitExtensionsMono.sln
 * Update documentation, wiki; set Mono as depreciated

Remove all Mono #ifdef in one clean cut
Keeping ifdef is possible but the support will 'rot' quickly and cherry picking to a Mono is not much affected.

**Comment by gerhardol** [comment]
For MakePortableArchive:
I considered just zipping the required files, to get rid of the need to manually update the script.
Not doing this to avoid including old files as well as requiring some funky renaming of files in the archive (the directory structure is not the same in Git as in the portable archive).

**Comment by RussKie** [comment]
Including the lot may have undesirable effects like including unnecessary files.
Let's park it for now, until all other things are complete

**Comment by gerhardol** [comment]
https://github.com/gerhardol/gitextensions/commits/test/n4415-mono-removal

Plan to submit two PRs:
 * One for build scripts
 * One for code and tests

Will probably leave RunningOnWindows() (as well as MacOS, Unix) for now.
Those could be useful in the future.
Some tests were targetting Win/not-Win but I removed those as the tests had mono in the name.
