### ISSUE TITLE
Missing commit in Doc submodule

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4418]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I pulled latest master and updated submodules.  I got the following error

"C:\Program Files\Git\bin\git.exe" submodule update --init --recursive
error: Server does not allow request for unadvertised object 87b529a4022023d53c17d36fa92f3228fdf12ca1
Fetched in submodule path 'GitExtensionsDoc', but it did not contain 87b529a4022023d53c17d36fa92f3228fdf12ca1. Direct fetching of that commit failed.
Done

I ran a ``` git submodule foreach --recursive git fetch --all``` and still got the same error message after trying to update submodules

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
A successful submodule update. 
**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.14.1.windows.1
- OS version: Win 10

**Did this work in previous version of GitExtensions (which)?**
yes

**Comment by RussKie** [comment]
Yes, I think it is due to my screw-up... I had to force push, so your copy has probably got out of sync
You need to resync submodules in gitextensions

**Comment by vbjay** [comment]
That fixed it.  Please don't rewrite history unless it is unavoidable.  Had to reconfigure remotes.

**Comment by RussKie** [comment]
It was a bad judgement call on my part...
