### ISSUE TITLE
Provide warning when "Show first parent" enabled

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4419]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
"Show first parent" setting has cause a bit of dramas to the users when it got enabled (often unknown to the user).
For example:  #4055 #4122 #4145

**What is the expected behavior?**
Warn or somehow else notify the user that the setting is enabled. 
Perhaps in a similar fashion to "in the middle of rebase".

**Comment by vbjay** [comment]
I'm trying to also make it reset on refresh. The codebase has changed a
lot. Figuring out how to do it.

**Comment by RussKie** [comment]
Im thinking we probably need to investigate pubsub model for communication
between components - this way we can decouple functionality.
Take `ExecuteCommand` (found in out custom forms and usercontrols) to a new
level.
In that model things like this feature would be almost trivial.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
