### ISSUE TITLE
Dynamically calculate SHA length

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4420]
**Do you want to request a *feature* or report a *bug*?**
feature, enhance #4310

**What is the current behavior?**
Now GE can either show full commit SHA or shorten those to 10 characters. This is rather inflexible as for small repos 10 chars is an overkill, and for some large repos ([like Linux kernel](https://lkml.org/lkml/2010/10/28/287)) 10 is not enough.

**What is the expected behavior?**
SHA abbreviation must be dynamically calculated for each repository.
Fomr: https://github.com/gitextensions/gitextensions/pull/4310#discussion_r159726082

See the following:
https://blog.cuviper.com/2013/11/10/how-short-can-git-abbreviate/

For GE:

```
git rev-list --all --abbrev=0 --abbrev-commit | awk '{ a[length] += 1 } END { for (len in a) print len, a[len] }'
4 4218
5 11700
6 1390
7 89
8 1
```

Use `core.abbrev` instead of hardcoding the length.

**Environment you encounter the issue:**
master

**Comment by drewnoakes** [comment]
@RussKie did we decide against doing anything with this for perf reasons, if nothing else?

**Comment by RussKie** [comment]
Yes, I think this can be closed in light of your refactor.
