### ISSUE TITLE
GitHub HTTPS push behind proxy - API auth fails (connection not using proxy)

### ISSUE THREAD

**Issue by Nu11u5** [gitextensions/gitextensions#4422]
I have successfully configured GitExtensions to Pull from GitHub repos through our HTTP proxy.  This only required that I have set:

- Git URL using HTTPS
- Git http.proxy set using the Proxy Switcher extension

When I try to perform a Push, I get the GitHub authentication window as expected, but on submitting my credentials the Push dialog reports:

    fatal: HttpRequestException encountered.
       An error occurred while sending the request.
    Username for 'https://github.com':
    

If I run a WireShark capture I can see the git Pull traffic using HTTP CONNECT through our proxy, however, **the call to api.github.com for GitHub authentication is not proxied!**

I have tried modifying GitExtensions.exe.config as mentioned in #613 and the [official MS .Net documentation](https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/network/defaultproxy-element-network-settings) with no success.

Currently, my GitExtensions.exe.config has these lines:

    <system.net>
      <defaultProxy enabled="true" useDefaultCredentials="true">
        <proxy usesystemdefaults="true"
               bypassonlocal="true"
               proxyaddress="http://my-proxy-ip:80"/>
      </defaultProxy>
    </system.net>

**This is probably related to the Git.hub library and Issue restsharp/RestSharp#1043.**

Windows 10 1703
GitExtensions v2.50.02

**Comment by RussKie** [comment]
Looks like Restsharp 106.2 has the issue addressed, so we need to update the reference.
You can probably try to drop the latest Restsharp assembly into C:\Program Files (x86)\GitExtensions and see if it fixes the issue.

**Comment by RussKie** [comment]
Please try this build and see if the problem is fixed
https://ci.appveyor.com/api/buildjobs/tb8kjpyr04sf8l4o/artifacts/GitExtensions-Portable-3.00.00.1599.zip

**Comment by matthewckarges** [comment]
I tried using the build from the link above and still received the same message

`fatal: HttpRequestException encountered.
   An error occurred while sending the request.
Username for 'https://github.com':`

**Comment by RussKie** [comment]
Do you have latest git 2.16+?
Just to confirm, are you aware of latest github's breaking changes (#4523)?

**Comment by matthewckarges** [comment]
Updating the Git Credential Manager fixed the issue for me.
