### ISSUE TITLE
Windows user .git folder preventing right-click Git Clone 

### ISSUE THREAD

**Issue by mccreeker** [gitextensions/gitextensions#4423]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Right-clicking in/on the C:\Users\user folder or any sub-folders shows Git Browse rather than Git Clone, whether any of those sub-folders have a repo in them or not. 

There's a .git folder in the user folder that I'm assuming is for global settings, but it shouldn't be considered a repo in the user folder and every sub-folder. If I use Git Browse accidentally, it scans everything in my user folder down and adds it to the unstaged list.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Install Git Extensions with Git Bash and right-click menu.
2. Right-click in any folder under Documents or the top-level user folder or anything under it that does not have a repo in it.
3. Always get the Git Browse option.

Right-clicking in any folder outside of the user folder that doesn't have a repo in it gives the Git Clone option.

**What is the expected behavior?**
Get the Git Clone option instead

**Environment you encounter the issue:**
Windows 10 LTSB

- GitExtensions version: 2.50
- GIT version: 2.13.2.windows.1
- OS version: Windows 10 LTSB

**Did this work in previous version of GitExtensions (which)?** don't remember

**Comment by vbjay** [comment]
Do a search for a ".git" folder in that folder chain and find the top most
one.  I'll bet you created a git repo in the user folder.

**Comment by mccreeker** [comment]
@vbjay I already knew where the top-level .git folder was that was causing the problem... no point in searching for it. It was in my C:\Users\user folder (where `user` is my username) as I mentioned in the original post.

I couldn't see anything in the contents of the folder that indicated it needed to be there or was global, and my Git Extensions settings didn't point to it, so I just renamed it and everything's working fine.

If Git Extensions doesn't create a folder like that in the top-level user folder, then I guess I just accidentally clicked Git Init there sometime.
