### ISSUE TITLE
Submodule update functionality.

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4424]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
We can have GE update submodules automatically after pull.  When this is done the commit is checked out and puts the submodule into a headless state.  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I propose that the submodules ui allow a custom value to hold a specified branchname.  This branch is suggested to not be pushed.  Before an update call, we autostash.  After the update we checkout the branch specified in the submodule settings and reset hard to the commit the update pointed to.  Then apply the autostash.  This will make it so the user can then create commits without being in a headless state and preserve any uncommitted work.

**Environment you encounter the issue:**

- GitExtensions version:NA
- GIT version: NA
- OS version: NA

**Did this work in previous version of GitExtensions (which)?**
No.

**Comment by gerhardol** [comment]
Related to #4368 
The request there is to use "submodule remote" to track the branch in the configuration, i.e. the workflow intended for submodules
(submodules are really useful but I cannot understand how the designers intention was with the commands)

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
