### ISSUE TITLE
Update references latest available versions

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4426]
The application has a number of dependencies, some of which are now out-dated.

**Expected**: all dependencies are current

- [x] ConEmu (used by ConEmuWinForms project) #4427 
- [x] RestSharp (used by Git.hub project) #4428

**Comment by gerhardol** [comment]
There are 16 nuget packages with updates. Maybe it is a good time to update them all?
(For instance 7zip has possibility to rename inside archives to avoid copying.)

What about the 3 submodules?
Do the ConEmu subrepo have to be in sync with the nuget package?

**Comment by RussKie** [comment]
The submodules are tracked under respective issues (please scroll up).

**Comment by RussKie** [comment]
@jbialobr I am hesitant to update packages for TFS-related projects, given I have no access to TFS servers nor use this plugin.
![image](https://user-images.githubusercontent.com/4403806/35774630-3cbc62a6-09c9-11e8-9956-66de8c03b695.png)

Is it ok to update them?

**Comment by RussKie** [comment]
Looks like SmartFormat.NET has a breaking change in 2.1.0
https://github.com/scottrippey/SmartFormat.NET/wiki/Character-Literals-in-Format-Strings
We need to ensure it doesn't cause regressions

**Comment by RussKie** [comment]
System.IO.Abstractions has regressed in 2.1.0 as well https://github.com/tathamoddie/System.IO.Abstractions/pull/225#issuecomment-362884018
