### ISSUE TITLE
Fail to amend when "Refresh dialog on form focus" enabled

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#4429]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

If the commit form option "Refresh dialog on form focus" is enabled,
When you try to amend a commit, you've got a confirmation message that steal the focus to the commit form.
So, when the popup is closed and the commit form is refreshed, it launch a git command in async to get the git status.
The git command launch enter in conflict with the git commit command if it takes some times, env 500ms (a lot of files in the working directory).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* Enable the feature
* Amend the last commit

**What is the expected behavior?**

Be able to amend the commit.

**Environment you encounter the issue:**

- GitExtensions version: all ( I think)
- GIT version: -
- OS version: -

**Did this work in previous version of GitExtensions (which)?**

I think, no...

**Comment by pmiossec** [comment]
Some logs: https://github.com/gitextensions/gitextensions/issues/4417#issuecomment-362857492

**Comment by gerhardol** [comment]
> If the browse form option "Refresh dialog on form focus" is enabled,

Which?

**Comment by pmiossec** [comment]
Sorry, I fixed the bug report. That was not the 'browse' form but the 'commit' form.

**Comment by gerhardol** [comment]
This option should be removed. It will cause the described problem if not git-status is very fast.
A workaround should be to activate the form by not activating very close to Commit, like select/unselect amend and wait a second before committing.

A similar problem occurs in Browse window, submodules and stash are listed at every activation.

A solution could be to not make a new call to git-status but to implement a listener for GitStatusMonitor to know when the command is required as well as to centralize the call.

**Comment by RussKie** [comment]
From the architecture perspective all git commands should be executed by a single component/service - this way we can ensure only one git process is run at any point of time.
Right now git commands are executed left, right and centre by various components.

**Comment by gerhardol** [comment]
> From the architecture perspective all git commands should be executed by a single component/service

GitStatusMonitor is a way getting closer for this specific command, this should be the major problem. I have a plan to improve this but have to take it step by step.

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.

**Comment by RussKie** [comment]
We should fix this
