### ISSUE TITLE
Option to set language in - Dictionary For Spelling Check - not working

### ISSUE THREAD

**Issue by coldspark** [gitextensions/gitextensions#4443]
**Do you want to request a *feature* or report a *bug*?**

> Bug

**What is the current behavior?**

> When using version 2.50RC1 and above, option to set language in _Dictionary For Spelling Check_ does not work. See the picture below.
> 
> ![image](https://user-images.githubusercontent.com/7758686/35959224-b78e0ee0-0cca-11e8-9794-6fa21d205eb1.png)
> 

**Environment you encounter the issue:**

- GitExtensions version: **2.50RC1 and above**
- GIT version: **2.14.1**
- OS version: **Windows 10**

**Did this work in previous version of GitExtensions (which)?**
>Yes | 2.49.03

**My observation**
> I may have been caused by this commit : https://github.com/gitextensions/gitextensions/commit/af00b7644c526318d32a7548c17c99d7de20cddc

**Comment by gerhardol** [comment]
Language can be set in the commit dialog. The setting does not seem to change selected dictionary.
(I tried with setting Italian and it seemed to work, my Italian is limited.)

Should the setting be removed?

![image](https://user-images.githubusercontent.com/6248932/36000074-186d8ed2-0d22-11e8-8a66-99ecbf82229f.png)

**Comment by RussKie** [comment]
> My observation
I may have been caused by this commit : af00b76

Perhaps you meant some other commit, because the referenced one doesn't have anything to do with the referred settings page.

**Comment by edsky** [comment]
I read the code and found that this option is not selected by default, I hope this option is read from git config by default, rather than not selected by default.
