### ISSUE TITLE
Release Note Generator - Validation Bug

### ISSUE THREAD

**Issue by LaughingJohn** [gitextensions/gitextensions#4444]
I think this is a bug.

In Git Extensions V2.50.02 there was no validation on the release note generator "From" and "To" fields. This meant you could put something in the "From" fields but leave the "To" field blank and it would show commit history up to head.
In V2.51 validation has been added so that both fields have to be filled. in. This means that to replicate the same report you have to enter "head" in the "To" field.

Can we remove validation on the "To" field please.

Whilst on the surface this seems a minor irritation, in my particular use case I manually go through dozens of git repositories running this to get release notes and it is a major slow down for me.

**Comment by gerhardol** [comment]
Maybe To could accept "" as HEAD.

**Comment by LaughingJohn** [comment]
@RussKie, you're probably right it's probably not strictly a bug. 
I don't think you have to explicitly supply a "HEAD" value. From the Git documentation on revision ranges: "you can omit one end and let it default to HEAD. For example, origin.. is a shorthand for origin..HEAD".
Thanks for looking at this, much appreciated!
