### ISSUE TITLE
Commit Index

### ISSUE THREAD

**Issue by LaughingJohn** [gitextensions/gitextensions#4445]
Feature Request.

In the latest release you have added the commit index/staging area as an additional line in the repo history along with "current working directory changes". Whilst I have used "show current working directory changes" since I've been using Git Extensions, personally I have no need for the commit index line.

So my request is can we have separate setting options for showing the "commit index" and "working directory changes" lines as I would like to remove the latter.

Also I think renaming "commit index" to "staging area" would make it clearly to newbies (and me) what it actually is.

Thank you.

**Comment by gerhardol** [comment]
In 2.50 and previous, the "current unstaged" and "commit index" were dynamic, they appeared when refreshing only. So if you had no changed files when refreshing, the "working dir changes" were never shown.

In 2.51 both artificial commits are always visible.  The functionality has been tweaked to allow comparing to commits and to stage/unstage, modify submodules etc. The previous handling was quite buggy too. To have commit index dynamic again or hidden will make this handling even more complicated than it is now, I propose no change.

**Comment by RussKie** [comment]
You can disable artificial commits completely, if you are not finding them
useful

**Comment by LaughingJohn** [comment]
Thanks @gerhardol, the dynamic thing makes sense. So the commit index was always there but I never saw it because of my particular workflow. I don't really want to disable artificial commits as I find the working directory changes useful. I've just downgraded for now. Thanks for considering!

**Comment by RussKie** [comment]
We won't be doing this.
