### ISSUE TITLE
Jira Commit Hint plugin settings missing

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4446]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The settings page for the plugin shows full set of settings only for "Effective" settings.
Selecting any other type of settings removes JIRA fields and default values.

![image](https://user-images.githubusercontent.com/4403806/36006928-f036aa12-0d93-11e8-8fe5-a4b42c952e41.png)
![image](https://user-images.githubusercontent.com/4403806/36006934-f6a751a8-0d93-11e8-863e-557d40d9fc5b.png)
![image](https://user-images.githubusercontent.com/4403806/36006944-02134f56-0d94-11e8-8f2a-57adfb9e9039.png)

**What is the expected behavior?**
All defaults and hints are available across all settings sources.

**Environment you encounter the issue:**
2.51 / master

/cc: @ierof @pmiossec

**Comment by GintasS** [comment]
This was fixed, the default values are there for version 3.5.3.
