### ISSUE TITLE
Jira Commit Hint plugin credentials stored in plain text

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4447]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Credentials are stored in plain text

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Choose to persist the settings into "Distributed with current repository" settings source (it doesn't matter which layer it is stored, this layer makes it easier to see)
![image](https://user-images.githubusercontent.com/4403806/36007065-c07fc104-0d94-11e8-9221-9c4df747ab57.png)

Open the GitExtensions.settings file:
![image](https://user-images.githubusercontent.com/4403806/36007035-9e95eece-0d94-11e8-8868-985f4799d821.png)

**What is the expected behavior?**
Password isn't stored at all.

The issue may not be a big deal for home users who rarely change passwords and do not share their computers with anyone. However in a corporate environments storing passwords in plain text, especially in settings, which may be committed into a public repository, is a massive security issue.
The username must not be persisted into a configuration file either. Credentials must be persisted into Windows Vault (credential store).
Few links to start with:
* https://msdn.microsoft.com/en-us/library/aa480470.aspx
* https://stackoverflow.com/questions/17741424/retrieve-credentials-from-windows-credentials-store-using-c-sharp

**Environment you encounter the issue:**
2.51 / master

/cc: @ierof @pmiossec

**Comment by stivx0** [comment]
I think it is not bad solution, but there is a issue with current settings architecture and Credential manager. I am really needed this fix for our company and I can dot it, but I am not sure about my vision of the fix. I have the questions:
1. Should I save old logic to store credentials as plain text in gitextensions.config (it requres to add new checkbox)?
2. Can I disable distributed settings logic for credentials? I can save credentials using Credential manager, but they cannot be distributed and saved inside repository, because we cannot share credentials from credential manager.

**Comment by RussKie** [comment]
I would deprecate the old insecure storage mechanism and replace it with a secure store. It may be a little inconvenient for a user to re-enter username/password, but it is a small price to pay for security.

It is a good idea to lock username/password persistence to the local config only to prevent accidental sharing of secrets.

**Comment by stivx0** [comment]
Philippe, thanks. My prototype is the same :-). I will try to find free time to end the fix.

**Comment by pmiossec** [comment]
>My prototype is the same :-). I will try to find free time to end the fix.

If you planned to fix it, you surely should create the pull request now.
Just prefix the title with "WIP:" until it's not finished.
