### ISSUE TITLE
Jira Commit Hint plugin multiline settings problem

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4448]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Multiline message template isn't restored correctly

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* Create settings with multiline template:
![image](https://user-images.githubusercontent.com/4403806/36007446-94c42f44-0d96-11e8-9424-8e66c412cbac.png)

* Close settings dialog 
* Settings are persisted incorrectly - there are additional LFs:
![image](https://user-images.githubusercontent.com/4403806/36007465-aa6e8ae2-0d96-11e8-9d9e-f100fdeee71e.png)
* Re-open it again - multiline formatting is lost
![image](https://user-images.githubusercontent.com/4403806/36007478-be2f0822-0d96-11e8-8d3d-18e57f776f84.png)

**What is the expected behavior?**
Multiline settings are rendered correctly

**Environment you encounter the issue:**
2.51 / master

/cc: @ierof @pmiossec

**Comment by pmiossec** [comment]
Is it with the commit 0ee0d86b5b3ddc4d406a3973c2cc8bc7fd772a6f ( or 7fa0eccc9f007cfe8fe277b210fc44af0ad1e6ba )?

Because it works well with it for me...

**Comment by RussKie** [comment]
I realised that you may have already fixed it, but hadn't had a chance to
test it.

**Comment by GintasS** [comment]
This was fixed too. Tested on GE 3.5.3.
