### ISSUE TITLE
Commit branch name in commits list

### ISSUE THREAD

**Issue by SailorMax** [gitextensions/gitextensions#4450]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
"Revision graph" doesn't show hint in which branch we have "Dot" (commit). Commits list also doesn't show this information. User have to use Details panel / Commit tab, or double click on commit.

**What is the expected behavior?**
One or few from next list:
- On mouse hover on graph line, output hint about branch name
- On mouse hover on graph commit dot, output hint about commit hash AND branch name
- Possibility to turn on commits list column where user can see branch name

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.16.1
- OS version: Windows 10 1709 b16299.214

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by RussKie** [comment]
Could you please visualise what you are requesting? Thank you

**Comment by vbjay** [comment]
He's saying he wants hit test functionality on the different parts of the
revision grid. When he hovers on a branch line, a GUI shows like a tooltip
type thing showing the name of the branch and other such behaviour based on
the thing being hovered over at the time.

**Comment by SailorMax** [comment]
![commits_branch_name](https://user-images.githubusercontent.com/6195377/36087677-48e46998-0fdc-11e8-8cce-97bdbfd4ea11.png)

**Comment by RussKie** [comment]
As an example there is a commit that exists in dozens of branches and tags, e.g.:
![image](https://user-images.githubusercontent.com/4403806/45955051-41e24800-c052-11e8-814e-d06f591f0718.png)

@SailorMax could you clarify as to what your expect the tooltip to show? What usefulness in showing all of the above information?
