### ISSUE TITLE
GitRemoteManager calls GetRefs multiple times

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4453]
**Do you want to request a *feature* or report a *bug*?**
deficiency, noticed in https://github.com/gitextensions/gitextensions/pull/4442#issuecomment-364269586

**What is the current behavior?**
https://github.com/gitextensions/gitextensions/blob/37f5e13951196f1302b935f7eaf1c8c2ed85e8d3/GitCommands/Remote/GitRemoteManager.cs#L79-L81

**What is the expected behavior?**
optimised

**Environment you encounter the issue:**
master

**Comment by NickPolyder** [comment]
Hello,
Could i start with this one ?

Thanks,

**Comment by gerhardol** [comment]
> Could i start with this one ?

Yes please!
The current behavior is that it can take several minutes when adding a new remote when there are some already.
The workaround is to deactivate all existing remotes when adding a new

**Comment by NickPolyder** [comment]
@gerhardol  should i use master branch or the latest release ?
Thanks,

**Comment by gerhardol** [comment]
Create a branch from master. If this is reasonable in a maintenance branch it will be cherry picked to the 2.51 branch later.

**Comment by NickPolyder** [comment]
@gerhardol @RussKie trying to test this code. But it does not do anything. It always gets inside the if that continues the foreach.
What i mean by that is that it never gets to execute the lines below 

    localHead.TrackingRemote = remoteName; // Line:94
    localHead.MergeWith = localHead.Name;   // Line:95
