### ISSUE TITLE
Pressing ctrl-Enter in the commit dialog inserts a line break before committing

### ISSUE THREAD

**Issue by eitland** [gitextensions/gitextensions#4456]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In Linux Neon (KDE) when I press ctrl-Enter to commit and the cursor is in the middle of a line  it inserts a line break, then commits.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1.    Open commit dialog
2.    Select something
3.    Write a commit message, move cursor back into the middle of the commit message
4.    Press ctrl- Enter to commit.
5.    Notice that a line break will be inserted into the message before commiting

**What is the expected behavior?**

The commit is saved as it was before I pressed ctrl - Enter

**Environment you encounter the issue:**

    GitExtensions version: 2.51
    GIT version: 2.7.4
    OS version: KDE 5.42.2, Linux 4.4.0-112-generic #135-Ubuntu SMP

**Did this work in previous version of GitExtensions (which)?**

Not sure.

**Comment by gerhardol** [comment]
No newline inserted in Windows
