### ISSUE TITLE
No updates found

### ISSUE THREAD

**Issue by andrey-helldar** [gitextensions/gitextensions#4457]
When I click the update check button, the program does not find new versions.

- GitExtensions version: 2.50.02
- GIT version: 2.15.1.windows.2
- OS version: Windows 10 Pro

![2018-02-10 19-50-16 about](https://user-images.githubusercontent.com/10347617/36064438-33bfed3a-0e9c-11e8-83ca-de9a996c4b5a.png)
![2018-02-10 19-50-05 check for update](https://user-images.githubusercontent.com/10347617/36064439-33de44a6-0e9c-11e8-9e67-37d50c5c387f.png)

**Comment by RussKie** [comment]
Yes, we still haven't pushed it.
I'll update it later today.

**Comment by andrey-helldar** [comment]
@RussKie But version 2.51 was released 15 days ago. Long that.
I downloaded the new version yesterday and installed it manually.

**Comment by RussKie** [comment]
We publish new versions to the general public few weeks after official releases to ensure the stability.
Anyway, it is truly official now.
Thank you for the timely reminder.

**Comment by andrey-helldar** [comment]
@RussKie I understood. Thank you for the clarification. Good luck with business!
