### ISSUE TITLE
Unable to solution build in VS2017

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4458]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Unable to build current master in VS2017 on a computer which has **only** VS2017 installed.
![image](https://user-images.githubusercontent.com/4403806/36072055-08e90ab6-0f6d-11e8-9237-307ef29e2eab.png)

It looks like a breaking change in VS2017 - a large number of Visual Studio assemblies are no-longer installed in the GAC and which, in absence of previous versions of VS installed, must be referenced in a different manner.
Further reading: https://developercommunity.visualstudio.com/content/problem/15434/cannot-find-wrapper-assembly-for-type-library-envd.html

**Comment by gerhardol** [comment]
Not fully working for me after all:
CS1752  C# Interop type 'constants' cannot be embedded. Use the applicable interface instead.

**Comment by RussKie** [comment]
What versions of VS do you have installed on your computer?

**Comment by gerhardol** [comment]
VS2017, VS2015 at least. Maybe some older version too.
The PR worked for me, but more tweaks may be required...

**Comment by RussKie** [comment]
Hmm, on the computer with just VS2017 everything builds from clean and all tests pass.
I'll try it on two other computers I have...

**Comment by RussKie** [comment]
I've run it on two other machines - W8.1 with VS2010, 2012, 2017 and W10
with VS2015, 2017 - builds and tests without problems.

**Comment by gerhardol** [comment]
On a Win7 with 2017, 2013, 2012, 2010 I can use both master and #4467. However, #4467 raises warnings, if you fix them the build fails again on the Win10 PC
There are updated custom wrappers available for the following referenced components: EnvDTE ,EnvDTE100 ,EnvDTE80 ,EnvDTE90.	GitPluginShared

**Comment by RussKie** [comment]
So if the master is good for you, do we need #4467?

**Comment by gerhardol** [comment]
master was OK for me on another PC (those are Professional)
On my home PC the VS plugins fails.

> VS2017, VS2015 at least. Maybe some older version too.

2012, 2013 Express too.
2017, 2015 is community

So I need #4467 or something similar, but probably not in its current state

**Comment by RussKie** [comment]
Righto, so just to clarify it fails for express/community versions?

**Comment by gerhardol** [comment]
> Righto, so just to clarify it fails for express/community versions?

Yes, but I doubt that is the core problem

**Comment by RussKie** [comment]
@gerhardol assigning to you, please see if you can find more information.

**Comment by RussKie** [comment]
We are permanently switching to VS2017.

**Comment by drewnoakes** [comment]
@gerhardol the issue you linked to mentions a release candidate version of 2017. Did you once have an RC build of 2017 on your PC? Perhaps the problem is related to that.

**Comment by gerhardol** [comment]
@drewnoakes 
I do not think I had 2017RC installed
The current message is
Severity	Code	Description	Project	File	Line	Suppression State
Warning		There are updated custom wrappers available for the following referenced components: EnvDTE90a ,Microsoft.VisualStudio.CommandBars.	GitPluginShared			

If I solve the warning I get the following error:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1752	Interop type 'Constants' cannot be embedded. Use the applicable interface instead.	GitPluginShared	F:\dev\gc\gitextensions_4\GitPluginShared\Commands\ItemCommandBase.cs	142	Active

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/37171743-dcde35c6-22dc-11e8-9803-3dcf02f56e3c.png)
https://www.visualstudio.com/vs/visual-studio-workloads/

**Comment by gerhardol** [comment]
I just got rid of the problem after updating to latest 15.6.1 (from 15.5).

**Comment by gerhardol** [comment]
@pmme
Gitplugin has just been removed in master. Is it working better?

**Comment by pmme** [comment]
Slightly better. I mentioned the latest commit I built from above and in that GitPluginShared problem remains but no longer GitPlugin.

**Comment by RussKie** [comment]
Have you run "restore packages"?
It is available in the context menu for the solution

**Comment by pmme** [comment]
I tried "Restore NuGet Packages". VS informed me that everything was already installed and nothing needed to be restored. It did not help with the build error.

However in further playing around I found a resolution, as per PR #4494.
