### ISSUE TITLE
Check for updates => NullReferenceException

### ISSUE THREAD

**Issue by Balinski** [gitextensions/gitextensions#4469]
bug

Click 'Help' -> 'Check for updates' => Error

![image](https://user-images.githubusercontent.com/16400052/36087328-e80952a8-0fe2-11e8-9c2c-3339b97fb387.png)

- GitExtensions version: 2.51
- GIT version: 2.14.1.windows.1
- OS version: Windows 10 Enterprise, version 1703, OS Build 15063.877

**Comment by gerhardol** [comment]
For a repo in GitHub, can you view pull requests?
(For me Git.hub.dll will not load, giving similar problems.)

**Comment by RussKie** [comment]
I'm currently looking at the code and I can't see how it can be null at all...
Today I've seen a number of successful updates, so I'm confident it is working correctly. Yet something is failing...

**Comment by RussKie** [comment]
Can you enable [Assembly Binding Log Viewer](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) and see if you are getting any problem loading assemblies?

**Comment by RussKie** [comment]
Closing due to lack of follow up

**Comment by chris-findlay** [comment]
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

Same issue.

**Comment by palver123** [comment]
- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3221.0
- DPI X:100.00% Y:100.00%

Same issue.
