### ISSUE TITLE
Make blame options -w -M -C switchable

### ISSUE THREAD

**Issue by IEVin** [gitextensions/gitextensions#4473]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Blame options -w and -M hardcoded.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Create and commit file with this content:
`1`
`#if (defined(WIN32) || defined(WIN64)) && defined(RELEASE)`
`2`
`#endif`
`3`
`#if (defined(WIN32) || defined(WIN64)) && (defined(RELEASE) || !defined(DEBUG))`
`4`
`#endif`
`5`
2. Modify file to this:
`1`
`#if (defined(WIN32) || defined(WIN64)) && (defined(RELEASE) || !defined(DEBUG))`
`2`
`#endif`
`3`
`#if (defined(WIN32) || defined(WIN64)) && (defined(RELEASE) || !defined(DEBUG))`
`4`
`#endif`
`5`
3. Show blame.

**What is the expected behavior?**
Can disable -w and -M options

**Environment you encounter the issue:**

- GitExtensions version: All
- GIT version: All
- OS version: Windows 7, 10

**Did this work in previous version of GitExtensions (which)?**
No

**Comment by IEVin** [comment]
Duplicate #2342

**Comment by RussKie** [comment]
Please reference #2342 in your PR commit message
Thank you
