### ISSUE TITLE
Dashboard view empty on Mono

### ISSUE THREAD

**Issue by GlennCoombs** [gitextensions/gitextensions#4477]
I'd like to report what seems to be a regression of behaviour that was fixed in item #2904 (linux dashboard fix) and described in issue #1713 (Starting window doesn't show entries under headers on Linux).

I am seeing the exact same behaviour as described in issue #1713.  When I start GitExtensions the Dashboard view has no entries under the Common Actions, Recent Repositories and Contribute sections.

I am running GitExtensions under mono on Ubuntu 16.04.  If I run mono --version it reports: Mono JIT compiler version 5.0.1.1 (2017-02/5077205 Thu May 25 09:16:53 UTC 2017).

This issue is not present for me in GitExtensions 2.49.03 but is present in both 2.50.02 and 2.51.

**Comment by wolfen351** [comment]
I'd be happy to test any test builds to help fix this issue
