### ISSUE TITLE
RevisionDiffProvider.GetInternal assertion failed

### ISSUE THREAD

**Issue by RandScullard** [gitextensions/gitextensions#4484]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the Debug build, this assertion fails in RevisionDiffProvider.GetInternal:

    Debug.Assert(!(firstRevision == secondRevision && (firstRevision.IsNullOrEmpty() || firstRevision == StagedOpt)),
        "Unexpectedly two identical artificial revisions to diff: " + firstRevision +
        ". This will be displayed as diff to HEAD, not an identical diff.")

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Make sure you have unstaged changes in more than one file, and that the "Current unstaged changes" item is selected in the main list of commits.
2. Go to the Diff tab in the bottom pane of the main window and make sure you can see all of your unstaged changes.
3. Right-click in the diff and choose Find to bring up the Find dialog.
4. Search for a string that appears in more than one of the changed files.
4. Keep hitting Find Next. As soon as the search jumps to the next file, the assertion occurs.

**What is the expected behavior?**
The Find feature searches through all of the unstaged modified files and selects all occurrences of the search text without an assertion.

(Note that in the Release build, this operation seems to work. Maybe the assertion itself is coded incorrectly?)

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.15.1.windows.2 
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes, in version 2.50.

**Comment by EbenZhang** [comment]
the reason you don't see it in release is because assert is designed to work for only debug mode.

**Comment by RandScullard** [comment]
@EbenZhang Totally understood. My point in that comment was that the feature appears to work despite the assertion, so I wonder whether the assertion itself is correct.

**Comment by gerhardol** [comment]
Asserts are just occurring in Debug builds, the assert code is removed in Release builds.

git-diff cannot display the cases mentioned in the assert. In most situations, the diff is what you want anyway.
Thanks for reporting.

I have corrected this in my development version already. It will take some time before I can submit a correction, to much time to just respond to issues right now and the correction will likely not be accepted unless I make a test case.

**Comment by gerhardol** [comment]
This should be fixed
