### ISSUE TITLE
Find in the Diff tab fails to find text

### ISSUE THREAD

**Issue by RandScullard** [gitextensions/gitextensions#4485]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the Diff tab of the lower pane, the Find feature (searching across files) fails to find text that definitely exists in the diffs.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Select a commit where multiple changed files contain the same text.
2. Go to the Diff tab in the bottom pane of the main window and make sure you can see the changes.
3. Right-click in the diff and choose Find to bring up the Find dialog.
4. Search for text that appears in more than one of the changed files.
5. Keep hitting Find Next. It will skip over many of the occurrences of the search text.

**What is the expected behavior?**
It finds every occurrence of the text in the diffs.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.15.1.windows.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes, in version 2.50.02.

**Comment by gerhardol** [comment]
I cannot reproduce
Do you have an example with a commit and a string to search for in a public repo?

**Comment by RandScullard** [comment]
Yes, please use this repo: https://github.com/RandScullard/photo-screen-saver

When I do the steps described above, using the latest commit (c974acd443) and the search text `flickr`:

- In 2.50.02, it finds the text in the diffs for readme.md, api-keys.ts, flickr.ts, and index.ts.
- In 2.51, it doesn't find it at all - I get "text not found".

I am starting my search with the first file (.gitignore) selected in the Diff panel.

**Comment by gerhardol** [comment]
Find in one file is OK, it is switching to the next that fails.
This works in my internal version, similar to #4484 
(I have to stop either to investigating issues or stop having a life to finish that).

**Comment by RussKie** [comment]
In the current master we preparing the following command for execution

```
-c diff.submodule=short diff --no-color  --unified=3 -M -C "c974acd443fd7546333b2608149e6d63624299e7"  -- "src/flickr.ts"
```

Running it both in GE (master) and in bash yields no result

**Comment by RussKie** [comment]
@gerhardol it looks like we regressed in #4157 
https://github.com/gitextensions/gitextensions/pull/4157/files#diff-95349e407fef1a99246ba82fa6aa7ba0L186

previously, if the 2nd commit was null or empty we would set it to first commit + `^`.

**Comment by gerhardol** [comment]
This is working in my work branch. I have done bigger cleanup for that handling in RevisionDiff (removing more code than adding), but have been stuck on writing test cases for some weeks (rewriting the test setup several times, but the tests are still meaningless).

**Comment by RussKie** [comment]
Let me know if you need help

**Comment by gerhardol** [comment]
@RussKie  See commit for the proposed solution. But that may not be apropriate for 2.51 if that is needed. But a comment if this is acceptable as a PR would be nice. If I split it up, it will not compile or not have tests until last commit.

first/second revision were previously mixed up, the parent handling is updated in 2.151. The problem is in RevisionDiff, I have not tried to debug.

**Comment by RussKie** [comment]
I presume it is all fixed
