### ISSUE TITLE
[Request] Search for commit hash

### ISSUE THREAD

**Issue by GregariousJB** [gitextensions/gitextensions#449]
Github is certainly no help here, and Git Extensions would be a huge advantage over Github with this feature.

**Comment by NDuma** [comment]
@VladimirRychlitskiy thank you for that solution :: Google search ended up here - do you have another one / forked or cloned/ - That one seems to be gone.
--
@vbjay wherever knowledge is found and discussed, there is a fountain spring for those needing refreshing; thank you for your tolerance on our journey's.
--
@mockobject Not sure about the ctrl+shft+g & doesn't help if you don't have the hash - w/ the hash you can add it to the end of the URL from my search.
