### ISSUE TITLE
Use native ListView and TreeView styles 

### ISSUE THREAD

**Issue by Quppa** [gitextensions/gitextensions#4490]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
ListView and TreeView controls use the pre-Windows Vista style (solid blue background for selected items).

**What is the expected behavior?**
ListView and TreeView controls should use 'native' Windows style.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.16.1.4
- OS version: Windows 10 1709 16299.248

**Did this work in previous version of GitExtensions (which)?**
No

**Old vs new style example:**
![Example](https://i.stack.imgur.com/QJ5b8.png)

**Comment by vbjay** [comment]
We did support mono. We have work in process of yanking it. I don't think
we can do this till mono support is yanked.

**Comment by Quppa** [comment]
Happy to make it conditional, but what's the recommended approach given that #4431 is already merged?

**Comment by vbjay** [comment]
Woops. Missed that.

**Comment by RussKie** [comment]
We no longer support Mono going forward (v3.x).
