### ISSUE TITLE
Create new worktree button should not be disabled

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#4494]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Can not checkout to a specific folder/directory (except using worktree feature, which will result to have the directory assumed submodule). But submodules have a lot issues, so I will have to avoid them.
It is possible in git as showed here:
https://stackoverflow.com/questions/4479960/git-checkout-to-a-specific-folder

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Just checkout selected branch to a specific folder/directory (just copy the files to target directory).

**Environment you encounter the issue:**

- GitExtensions version: v2.51
- GIT version: v2.12
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**

**Comment by gerhardol** [comment]
Archive?

![image](https://user-images.githubusercontent.com/6248932/36335591-5d8f4f4a-1381-11e8-82eb-3098a8434834.png)

**Comment by vbjay** [comment]
Work trees are not submodules.

**Comment by klorinczi** [comment]
@gerhardol Archive will create a compressed archive, not a checkout.

**Comment by klorinczi** [comment]
@vbjay: you are right, work trees are not submodules. However, if I add to repo1 a new worktree repo2/newdir, and the selected directory is under repo2, then opening repo2 will show repo2/newdir as submodule.

**Comment by klorinczi** [comment]
I think "Create a new worktree" feature would be fine for me.
However the "Create new worktree" button is disabled in some rare cases.

Steps to reproduce:
1) Create a new, empty directory somewhere in the filesystem. For example: W:\Dev\test-empty
2) Create a new, empty directory somewhere in the filesystem. For example: W:\Dev\test-full
3) Create a new file in W:\Dev\test-full named aaa.txt
4) Menu/Repository/Worktrees/Create a new worktree
5) Select "Create a new branch (from current commit)", type: mynewbranch
6) In "New worktree directory:" line click Browse, and select "W:\Dev\test-empty" directory.
7) The "Create new worktree" button becomes active
8) In "New worktree directory:" line click Browse, and select "W:\Dev\test-full" directory.
9) The "Create new worktree" button becomes disabled.

It is a good idea to warn user, that a target worktree is not empty, has content.
But currently user has no idea, what is wrong, just sees, that the create button is disabled.

I would better drop a pop-up dialog, that target directory is not empty, but will be overwritten, content of it will be lost: 
"Target worktree directory is not empty, but will be overwritten, content of it will be lost. Are you sure to empty the 'W:\Dev\test-full' directory?". 
Perhaps a second warning should be acceptable before deleting:  
"Are you sure to delete all files in 'W:\Dev\test-full' directory???". 
If user clicks YES button, then we can clear the directory.

What do you think?

**Comment by RussKie** [comment]
I think your proposal is sensible, but I don't use worktrees and have no experience with them.

**Comment by drewnoakes** [comment]
It sounds like we can phrase this issue as a bug with title: Create new worktree item should not be disabled

@klorinczi it's your issue. Would you agree with that title?

**Comment by klorinczi** [comment]
I changed issue title to "[Bug] Create new worktree button should not be disabled"

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.
