### ISSUE TITLE
GitEx selects the top revision after creating a new tag

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#4495]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
GitEx selects the most top revision after creating a new tag. Which is somewhat inconvenient, especially if you were a few screens below.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* Open any repository
* Select any revision below the top 
* Create a new tag for it
* After "Create Tag" dialog was closed, GitEx selects the top revision.

**What is the expected behavior?**
The previously selected revision must remain the same after create tag dialog was closed.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.15.1.windows.2
- OS version: Windows 7 x64

**Did this work in previous version of GitExtensions (which)?**

I think, 2.50 worked correctly.

**Comment by gerhardol** [comment]
GE selects HEAD after tagging

**Comment by pmme** [comment]
I did some investigating by single stepping in VS last night but got stumped. 

What I found:
Creating a tag updates the Index, therefore after creating the tag, RevisionGrid::RefreshRevisions will call ForceRefreshRevisions. 
ForceRefreshRevisions will set RevisionGrid::LastSelectedRows correctly, in that it will contain the revision that was current prior to creating the tag. So at this point everything has worked correctly.
However, when RevisionGrid::GitGetCommitsCommandExited calls RevisionGrid::SelectInitialRevision, RevisionGrid::LastSelectedRows has been reset to null.

Perhaps someone with more experience in GE could help me understand further...

**Comment by pravic** [comment]
May be it's easier to check what was changed since 2.50?

**Comment by pmme** [comment]
@pravic I found the problem :)

**Comment by pravic** [comment]
Cool, thank you!
