### ISSUE TITLE
Adding UWP wrapper project for deploying GitExtension to Microsoft Store

### ISSUE THREAD

**Issue by Jammer77** [gitextensions/gitextensions#4498]
I think we need to upload this application to Microsoft Store. For this issue we have to make  wrapper app  in solution, what adapted WinForms apps for Store.

**Comment by vbjay** [comment]
https://developer.microsoft.com/en-us/windows/bridges/desktop

**Comment by Jammer77** [comment]
https://github.com/gitextensions/gitextensions/pull/4497

**Comment by KindDragon** [comment]
I think that it's a fun task, but it does not make much sense 😄 . Especially because GitExt requires Git and KDiff3.

**Comment by RussKie** [comment]
@Jammer77 are git and kdiff3 (or any other diff tool for that matter) available in the Store?
If not, then you work is for naught.

**Comment by gerhardol** [comment]
If #4515 is done, Git and KDiff3 is removed from the installation package. Also if they are kept, the installer without Git/Kdiff3 could be added.

**Comment by RussKie** [comment]
GE won't function without git installed, and if it isn't available in the Store it makes no sense to make GE available there.

**Comment by gerhardol** [comment]
_Git for Windows_ does not seem to be available in _Microsoft Store_ so Win10s users will not benefit.
But this may simplify for other lockdown scenarios?

For diff, there are few options, (baysync (payed app) could work).

If Win10s for some unknown reason takes off, there should be alternatives, eventually. 
(I hope I never will be forced to use the Microsoft Store, lock-in is not not something I appreciate).
