### ISSUE TITLE
Theres a translationbug in checkout dialog

### ISSUE THREAD

**Issue by mstrewe** [gitextensions/gitextensions#4503]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Translation issue

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Check out a branch to get the following dialog
![image](https://user-images.githubusercontent.com/15155589/36380685-776f0bf4-1583-11e8-9ac9-cb657169698f.png)

**What is the expected behavior?**

The word in  the red circle should be "Auschecken"

**Environment you encounter the issue:**

Windows 

- GitExtensions version:  2.51
- GIT version: doesnt matter
- OS version:  Windows 8

**Did this work in previous version of GitExtensions (which)?**

**Comment by gerhardol** [comment]
Someone speaking German fix it in https://www.transifex.com/projects/p/git-extensions

**Comment by RussKie** [comment]
Are we sure tbe button is showing the full word?
