### ISSUE TITLE
Feature Request: Add Push to Commit dialog

### ISSUE THREAD

**Issue by ericnewton76** [gitextensions/gitextensions#4505]
**Do you want to request a *feature* or report a *bug*?**
Feature request, to add Push to the Commit dialog box.  I usually keep the Commit dialog box open for long periods of time, and sometimes (rarely) use the Commit and Push, I typically commit, commit, commit, then give it a rest period so I can consider if I need to squash commits, etc before pushing.  It would be awesome to have a Push button that could initiate a push wihtout a commit first.

**What is the current behavior?**
Theres Commit and Push, but requires a commit to push...

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
New button, maybe next to "Create Branch", that either does functionality similar to Commit and Push (without the commit) or brings up the Push dialog box.

**Comment by gerhardol** [comment]
Why not drop back to Browse to Push?
The Commit dialog is quite busy already.

**Comment by RussKie** [comment]
I agree I wouldn't want to add any more functionality to the Commit dialog.

As the name suggests its purpose is to facilitate the ability to commit.
There are many variables to "push" functionality which are configured in
the Push dialog.

Adding an ability to launch the Push dialog from the Commit dialog doesn't
sound sensible to me either, as it does not represent a common behaviour.

We won't be doing this, sorry

**Comment by ericnewton76** [comment]
If one has the commit dialog open, and the original explorer window used to launch the commit dialog is gone, whats the fastest way for one to push using gitextensions?

A simple toolbox icon to invoke Push on the Commit dialog it allows for this.
