### ISSUE TITLE
Use GitHub project management tools

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4508]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Mini pull requests go see x discussion over here...  Pain in the rear to know where things are.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Use https://github.com/features/project-management
**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by gerhardol** [comment]
What changes do you propose?

It is hard to control where a discussion takes place. Some belong to issues, other to PRs

**Comment by vbjay** [comment]
If we added a project for multi issue/pull request items and allowed
readonly access to everyone to the projects. That way things like move to
async could go through all repos. It would be a better oralganized view of
the fifty issues that all fall under x project

Example v3.0 could be its own project with all the yank mono and GUI
overhauls.

**Comment by GintasS** [comment]
Abandoning this because of the age and since this was marked as a discussion, but no discussion is active.

**Comment by gerhardol** [comment]
We could use projects for some development, do not need to have a separate issue for the process change
