### ISSUE TITLE
GitK is not launched with newer Git

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4510]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If you have a newer Git installed, GitK is not launched from GE.
The reason is that GitK is now distributed as gitk.exe instead of gitk.cmd which GE assumes.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Try to launch gitk from the Tools menu

**What is the expected behavior?**
Start GitK or remove the option.
It is easy enough to start gitk from git-bash, but flags are not obvious.
Git-GUI works, but if gitk is removed, git-gui should be removed too.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.16.2
- OS version: Win10

**Did this work in previous version of GitExtensions (which)?**
Older Git versions

**Comment by RussKie** [comment]
I vaguely remember seeing constants for git versions, so showing the option
based on git version may be an option.

Other option could be launching different file based on git version.

Or remove it completely - is an option too.

I have no opinion as I have no idea what gitk is :)

**Comment by gerhardol** [comment]
Useful to review massive updates as pointed out in https://github.com/gitextensions/gitextensions/pull/4481#issuecomment-366368367

A  simple solution would be to see what gitk is installed.
The simplest would be to remove the support from within GE.

**Comment by vbjay** [comment]
I don't think it should be removed. Just do a check for gitk.cmd and if not gitk.exe

**Comment by pmme** [comment]
GE runs gitk by replacing "git.exe" with "gitk.cmd" in the AppSettings.GitCommand string (unless it detects RunningOnUnix, in which case it uses different code).
From a quick test on Windows 7, if we replaced "git.exe" with "gitk" (no extension) then Windows will run either "gitk.exe" or "gitk.cmd", whichever is present.

**Comment by gerhardol** [comment]
> From a quick test on Windows 7, if we replaced "git.exe" with "gitk" (no extension) then Windows will run either "gitk.exe" or "gitk.cmd", whichever is present.

Something like that could work, since Mono is not supported.
But we stilldo not know what directory, so detection should probably search for a complete match.

**Comment by pmme** [comment]
> But we stilldo not know what directory
The code is making use of the fact that AppSettings.GitCommand contains the directory. It does a string replacement of "git.exe" so that it runs gitk from the same directory as git.exe.

**Comment by pmme** [comment]
Actually, what I wrote isn't entirely clear.
From AppSettings.GitCommand, it replaces "bin\\git.exe" with "cmd\\gitk.cmd", so we could replace with "cmd\\gitk".

**Comment by pmme** [comment]
I see github noticed the commit in my fork. 
That's a minimal fix that works on my Windows 7, GE 2.51, git 2.13.2.windows.1

**Comment by RussKie** [comment]
Please raise a PR so we can see the diff

**Comment by pmme** [comment]
@RussKie, in my view of this conversation github has automatically created a comment linking my commit from my fork. Clicking that link shows the diff. Does this show for everyone, or just for me because I'm logged in and my fork references this issue?

**Comment by RussKie** [comment]
Yes, indeed I could see the diff. 
I often look at issues and PRs on a small factor screen, so some things are much harder to do...
