### ISSUE TITLE
Stash pop with conflict issue

### ISSUE THREAD

**Issue by TamilarsanS** [gitextensions/gitextensions#4514]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Stash pop after resolving the conflict, update the code to stashed code. But stash entry not removed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Stash a branch with the conflict code
2. Perform some branch related operations like checkout or merge with other branch
3. Perform stash pop

**What is the expected behavior?**
Need stash entry removed 

**Environment you encounter the issue:**
Window 7 64 bit

- GitExtensions version:
- GIT version: 2.50.2
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
Don't know

**Comment by RussKie** [comment]
Please install the latest version and test

**Comment by pmiossec** [comment]
I think that what you call a bug is in fact a feature of git to save your ass in some occasions and that there is no interest in changing this behaviour (that's not the job of GitExtensions).

This behavior is here for you to be able to reapply the stash (after resetting the changes) if you mess around when doing the merge.

If you're happy with your merge, you just have to delete the stash...

**Comment by vbjay** [comment]
Completely agree.  After a non merge conflict, a pop will delete the
stash.
https://git-scm.com/docs/git-stash#git-stash-pop--index-q--quietltstashgt
