### ISSUE TITLE
Is there a bug in RevisionGraph.ProccessGitLog?

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4516]
On current `master` see `RevisionGraph.ProccessGitLog` line 169:

https://github.com/gitextensions/gitextensions/blob/master/GitCommands/RevisionGraph.cs#L169

It appears as though the string assignment should be a string append. That is,

```c#
// before
logParam = " --branches";

// after
logParam += " --branches";
```

If this is intentional, let's add some documentation to that effect.

**Comment by gerhardol** [comment]
That is a bug that has been around since 2013 it seems.

The effect is thar git-log --branches cannot be used with date order or showing reflogs, so no catastrophe.

**Comment by drewnoakes** [comment]
Cheers for confirming. Will put up a PR. Might also change it to use `StringBuilder` in the process to reduce allocations.
