### ISSUE TITLE
Github OAuth authorization is broken

### ISSUE THREAD

**Issue by achan1989** [gitextensions/gitextensions#4529]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

In GitExtensions clicking Plugins -> Github opens a "Github Authorization" window, but the webpage fails to load ("navigation to the webpage was canceled").  Therefore I can't get an OAuth token from GitHub.

**What is the expected behavior?**

Website loads, I put in details, get OAuth token.  GitExtensions can work with GitHub.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: git for windows 2.16.2.windows.1
- OS version: win7

**Did this work in previous version of GitExtensions (which)?**

unknown

**Comment by achan1989** [comment]
Wireshark shows three attempts made to connect to github.com -- two with TLS 1.0 and one with SSL 3.0.
All failed with protocol version alerts (handshake failure in the case of SSL 3).

**Comment by NickPolyder** [comment]
Hello, I had the same issue. 
I solved it by reinstalling the git for windows (version: 2.16.2 x64)
and it worked. 

I think that this may be problem of the update to GitExtensions version 2.51 something messes up with git maybe?

I would suggest to try and re-install as a short term solution.

Thanks.

**Comment by achan1989** [comment]
It doesn't help.

The plugin is just using the .NET WebBrowser component to access a web page.  Git for Windows is not involved yet.

I found a fix though.  Windows internet options (control panel -> internet options -> advanced) had somehow been set so that TLS wasn't enabled :s
