### ISSUE TITLE
"Restore to selected version" function is removed from 2.51

### ISSUE THREAD

**Issue by koreyba** [gitextensions/gitextensions#4535]
One of the most amazing features of Git extensions is removed from 2.51 version!

Previously in file tree I was able to do a right click on a folder and the first option was "Restore to selected version". For now there is no such feature.

I was urged to roll down to 2.50.2

**Comment by RussKie** [comment]
we regressed here - https://github.com/gitextensions/gitextensions/commit/2ef5a655f410bf2a30dd05a8781b4974d45bf29b

I guess the original implementation's wording was misleading and suggested the operation applied to files only

**Comment by RussKie** [comment]
@koreyba please check https://ci.appveyor.com/api/buildjobs/f25fcep4ebjq5d0b/artifacts/GitExtensions-Portable-3.00.00.1718.zip to see whether it is fixed
Thanks

**Comment by koreyba** [comment]
@RussKie thanks, it is fixed in the portable version. Are you gonna push it to 2.51.x ?

**Comment by RussKie** [comment]
Yes, once we have finalised the fix (which we haven't) it will get pushed
to 2.51 branch.
We are planning to do a 2.51.01 release in coming weeks.

**Comment by RussKie** [comment]
@koreyba please check https://ci.appveyor.com/api/buildjobs/o83va1lg6pxr6i5u/artifacts/GitExtensions-2.51.01.1754-Mono.zip
to see whether it is fixed
Thanks
