### ISSUE TITLE
Git toolbar - Add reset all button - Shorten saved stashes to stashes 

### ISSUE THREAD

**Issue by erikleo** [gitextensions/gitextensions#4537]
I find that doing a reset all is a very common task, and would like to propose adding this button to the toolbar to left of the commit button. (no text needed)  This is for the times you don't need to see what the actual changes are and just want to revert without having to open the commit window to get to the reset all button.

Also I really like having the number of stashes up there but but I think we can remove the word "saved" to save toolbar space.

**Comment by RussKie** [comment]
I understand the convenience aspect, but I don't believe that making an irreversible action easy to access is a good thing.

**Comment by erikleo** [comment]
Hi RussKie,  I am not proposing a irreversible action.  The proposal would be for there to be a reset button with the icon ![image](https://user-images.githubusercontent.com/17444748/48483240-eaa25d80-e7e0-11e8-8373-76c77f0ff547.png) to be put to the left of the commit button, to reset all changes.

It would then bring up the same confirmation box that you get get when pressing the button from the commit window, therefor the user would be able to cancel if they clicked by accident.

![image](https://user-images.githubusercontent.com/17444748/48483371-4371f600-e7e1-11e8-8071-9a73329fd07b.png)

This is something i do all the time, and i think it deserves a button on the toolbar as it seems tedious to have to go thorough the commit window or the commands menu every time.

**Comment by vbjay** [comment]
The point is with the commit dialog, you see the changes you are resetting.
This is a bad idea because you can reset something you didn't mean to
reset. Still able to do so with the commit dialog but at least you had the
info in your face to have you check.

**Comment by vbjay** [comment]
You can add a script to the grid menu and even add confirmation to it.
Settungs->scripts.

**Comment by erikleo** [comment]
Thanks vbjay, I did not know about adding scripts to the right click context menu.  That is an interesting feature, but it still requires and extra click.

I understand what you are saying about visually seeing the changes before you reset them from the commit window so as not to make a mistake you regret, but this logic does not hold for the reset command from the Commands menu where you can reset the changes without seeing the preview.

I am simply proposing making a more frequently used command which is already in the command menu to be more accessible which is the whole point of the toolbar.

Maybe the best thing for me to do is create a new issue proposing a customizable toolbar.  This way people can add their most frequently used commands and remove some of them that they don't use.

**Comment by vbjay** [comment]
The difference is the fact that you can't easily hit it instead of the
commit button. Yes we have confirmation. But you pulled the menu down. You
went to that specific menu. The confirmation is there just in case you
didn't mean to hit that menu. I never use the menu. I always use the commit
dialog.

**Comment by gerhardol** [comment]
> Maybe the best thing for me to do is create a new issue proposing a customizable toolbar. 

That would be the best but it will not be easy to implement something like a FluentUI (Ribbon) interface.
This is not easy to do in WinForms and rewriting the complete UI will not be simple. There has been many suggestions of what to use instead...

Personally, I want to see (diff) what to reset first, if I am in hurry I stash (one click, move to first in the menu).
I see your point, but until the UI is customizable, everything cannot be added.
