### ISSUE TITLE
Geometry problems on high-res laptop display

### ISSUE THREAD

**Issue by armplinker** [gitextensions/gitextensions#4544]
**Do you want to request a *feature* or report a *bug*?**
**Annoyance**

**What is the current behavior?**
See attached picture.  Screen geometry is wrong on high-res laptop
If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.
Run the program, go to options/config, go to appearance for obvious manifestation.  Appears elsewhere

**What is the expected behavior?**
Screen is readable, not all screwed up and tiled on top of itself

**Environment you encounter the issue:**
Wndows 10, Dell laptop at highest resolution
- GitExtensions version:
2.51 (installed yesterday)
- GIT version: 
2.16.2.windows.1 (installed yesterday)
- OS version: 
Windows 10
OS Name	Microsoft Windows 10 Home
Version	10.0.16299 Build 16299
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	 
System Manufacturer	Dell Inc.
System Model	**Inspiron 7548**
System Type	x64-based PC
System SKU	066F
Processor	Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz, 2401 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Dell Inc. A08, 2/2/2018
SMBIOS Version	2.8
Embedded Controller Version	0.08
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	On
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.16299.248"
User Name	
Time Zone	
Installed Physical Memory (RAM)	16.0 GB
Total Physical Memory	15.9 GB
Available Physical Memory	8.86 GB
Total Virtual Memory	31.9 GB
Available Virtual Memory	23.7 GB
Page File Space	16.0 GB

**Display characteristics**
Name	AMD Radeon R7 M270
PNP Device ID	PCI\VEN_1002&DEV_6604&SUBSYS_066F1028&REV_00\4&578B5E8&0&00E4
Adapter Type	AMD Radeon Graphics Processor (0x6604), Advanced Micro Devices, Inc. compatible
Adapter Description	AMD Radeon R7 M270
Adapter RAM	(1,048,576) bytes
Installed Drivers	aticfx64.dll,aticfx64.dll,aticfx64.dll,amdxc64.dll
Driver Version	15.201.1101.0
INF File	oem36.inf (ati2mtag_R502 section)
Color Planes	Not Available
Color Table Entries	Not Available
Resolution	Not Available
Bits/Pixel	Not Available
Memory Address	0xE0000000-0xEFFFFFFF
Memory Address	0xF70C0000-0xF70FFFFF
I/O Port	0x0000EF00-0x0000EFFF
IRQ Channel	IRQ 4294967290
Driver	c:\windows\system32\drivers\atikmpag.sys (8.14.1.6463, 678.53 KB (694,816 bytes), 10/7/2015 5:30 PM)
	
Name	Intel(R) HD Graphics 5500
PNP Device ID	PCI\VEN_8086&DEV_1616&SUBSYS_066F1028&REV_09\3&11583659&0&10
Adapter Type	Intel(R) HD Graphics Family, Intel Corporation compatible
Adapter Description	Intel(R) HD Graphics 5500
Adapter RAM	1.00 GB (1,073,741,824 bytes)
Installed Drivers	igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igd12umd64.dll
Driver Version	20.19.15.4531
INF File	oem10.inf (iBDWM_w10 section)
Color Planes	Not Available
Color Table Entries	4294967296
Resolution	3840 x 2160 x 60 hertz
Bits/Pixel	32
Memory Address	0xF6000000-0xF6FFFFFF
Memory Address	0xD0000000-0xDFFFFFFF
I/O Port	0x0000F000-0x0000F03F
IRQ Channel	IRQ 4294967291
Driver	c:\windows\system32\drivers\igdkmd64.sys (20.19.15.4531, 7.61 MB (7,974,896 bytes), 2/16/2017 12:23 AM)

**Did this work in previous version of GitExtensions (which)?**
**No.  was the same since forever.  Lived with it.  Time to fix it, please.**
![image](https://user-images.githubusercontent.com/5722201/36788735-042e93ea-1c5d-11e8-86b8-81bcbb92fa3a.png)

**Comment by armplinker** [comment]
Yes.  Chicken — egg — screen resolution — chicken

**Comment by armplinker** [comment]
Actually now that I am running the latest the problem seems to have spread further into other dialogs.  So perhaps the display processing is now standardized but to the detriment of hi-res laptops.
To be fair, lots of applications seem to blow off this issue, such as the Microsoft Visual Studio database server explorer (past versions...)

**Comment by RussKie** [comment]
Please refer to https://github.com/gitextensions/gitextensions/issues/4099#issuecomment-349899698 for a fix

Relates to #2252 #3673 #4099

**Comment by vbjay** [comment]
Let's at least add the correct manifest to the repo.

**Comment by armplinker** [comment]
Yes.  This solution is not for the faint of heart.

**Comment by vbjay** [comment]
It's not that hard. Someone could take the fix and apply it and test. When
it's good, submit a pull request with the fixed manifest.

**Comment by drewnoakes** [comment]
You didn't state what your scaling percentage was. I can replicate some vertical compression of settings at 200% (the highest Windows 10 lets me go) but nothing that severe.

Trying to consolidate and track all DPI related issues in one place. Hence I'm closing this in favour of #4775. There is work going on to fix these DPI issues. If you wish to report specific screens with issues, please see the notes at #4775. Thanks.

**Comment by jhoneyperker** [comment]
I can not understand this solution.I am going to [Mac customer support](https://appletechsupportnumber.net/mac-support/) to resolve it, you can also check this out.
