### ISSUE TITLE
Powerful "Branches" filter is broken in 2.51

### ISSUE THREAD

**Issue by Radrik5** [gitextensions/gitextensions#4545]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Steps to reproduce:
1. Enter `@` in Branches filter
2. Press Enter
Nothing happens.

As workaround I can use Advanced Filter but it's much less convenient.

What worked well in Git Extensions 2.49 in "Branches" filter:
* `@ @{u}` - current branch and its upstream branch (hide unimportant branches);
* `--reflog` - recent unreferenced commits to restore your work;
* `branch1 origin/branch2 tag3` - history of important references.

Nothing of this works in Git Extensions 2.51.

![image](https://user-images.githubusercontent.com/9339459/36835324-e4300930-1d46-11e8-8864-7ba7e6a738b3.png)

When I move focus back to the Branches filter, I get exception: InvalidArgument=Value of '0' is not valid for 'index'.

```
   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at System.Windows.Forms.ComboBox.get_Text()
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**What is the expected behavior?**
Git Extensions displays history for the current branch only.

**Environment you encounter the issue:**
- GitExtensions version: 2.51
- GIT version: git version 2.13.0.windows.1
- OS version: Windows 7 64bit

**Did this work in previous version of GitExtensions (which)?**
2.49

**Comment by Radrik5** [comment]
@drewnoakes could you take a look at this?

**Comment by drewnoakes** [comment]
Sure. However that PR was merged after 2.51 was released. Are you running from `master` or the 2.51 release?

**Comment by Radrik5** [comment]
@drewnoakes I'm using the 2.51 release. Seems like I'm wrong in blaming your PR. Sorry.

**Comment by drewnoakes** [comment]
No problem. Seems this PR changed the logic you're having trouble with. Hopefully it fixed it. Could you build the current `master` branch and see if the problem persists?

**Comment by drewnoakes** [comment]
`@ @{u}` seems to work on `master` for me. Please try your other variants.

**Comment by Radrik5** [comment]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Steps to reproduce:
1. Enter `@` in Branches filter
2. Press Enter
Nothing happens.

![image](https://user-images.githubusercontent.com/9339459/36835324-e4300930-1d46-11e8-8864-7ba7e6a738b3.png)

When I move focus back to the Branches filter, I get exception: InvalidArgument=Value of '0' is not valid for 'index'.

   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at System.Windows.Forms.ComboBox.get_Text()
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**What is the expected behavior?**

Git Extensions displays history for the current branch only.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: git version 2.13.0.windows.1
- OS version: Windows 7 64bit

**Did this work in previous version of GitExtensions (which)?**

2.49

As workaround I can use Advanced Filter but it's much less convenient.

**Comment by Radrik5** [comment]
@drewnoakes I will try `master` sometime later. I have an urgent project at work currently.

**Comment by RussKie** [comment]
@Radrik5  I've moved your report to the top

**Comment by RussKie** [comment]
Can this be related to #4370?

**Comment by yesgrey** [comment]
#4370 is still not working fine... I tried to re-open the issue but don't know how to do it... It works fine with some branch names, but not with all. I'm wondering if these problems could be related with any changes introduced with #4014?...

**Comment by RussKie** [comment]
So what is not working exactly?
Steps to reproduce?

**Comment by yesgrey** [comment]
I've updated #4370 with the latest problems found.
