### ISSUE TITLE
Find in the Diff tab shows differences reversed after wrapping around the files

### ISSUE THREAD

**Issue by pmme** [gitextensions/gitextensions#4546]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`Find` in the Diff tab switches the representation of added and removed lines when executing `Find` from the last occurrence and the feature wraps around to start finding from the first file again.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Using the gitextensions repository, select commits 315f89d0 then 5da4c625e on the origin/release/2.51 branch. 
2. Take note of which text is marked as added and removed (green and red) to show the difference. At this point this should correctly represent which lines were added and which were removed.
3. Starting from the first file, Setup/DownloadExternals.cmd, `Find` the text "kdiff3".
4. Repeat finding the text "kdiff3" until it wraps back to DownloadExternals.cmd.
5. You should see that the difference is reversed in that the lines that were marked as added are now marked as removed and vice versa.

**What is the expected behavior?**
When the `Find` command wraps around to the first file, the difference highlighting will show the same as when the first file was selected at the start of the operation.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.13.3.windows.1
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**
I know that this did previously work as I expected until recently but I do not know precisely when the behaviour changed.

I believe that this may be related to issue #4485 and may simply be a different manifestation of the problem. In this case, different from #4485, the Diff view is for two selected commits.

**Comment by RussKie** [comment]
I believe the issue has been fixed in #4541
Please try this build - https://ci.appveyor.com/api/buildjobs/7tnmx36fxak6md6e/artifacts/GitExtensions-Portable-3.00.00.1727.zip

**Comment by RussKie** [comment]
Thanks @jbialobr, beat me to it :+1:

**Comment by pmme** [comment]
Works correctly in that build. Excellent work as always.

**Comment by RussKie** [comment]
Would like to try this build as well?
https://ci.appveyor.com/api/buildjobs/mp3gay02ropeiqqa/artifacts/GitExtensions-2.51.01.1743-Mono.zip

**Comment by pmme** [comment]
I find myself unable to run GitExtensions on the latest mono on my MacBook. I'm probably missing something simple but I have very little experience doing anything useful on a mac. Unfortunately I'll have to defer to someone else to test the mono build.

**Comment by gerhardol** [comment]
@pmme The "2.51 Mono" package is similar to "3.00 portable", can run in Windows too.
In master (will be 3.0) Mono is disabled so the package has a better name (for Windows).
The patch in that package may be replaced with a simpler patch that just restores the 2.50 behavior (the current patch makes more, but it may be too much for a correction release).

**Comment by RussKie** [comment]
Yes, it's the same portable build. Run it under Windows as you normally
would.

**Comment by pmme** [comment]
@RussKie, 
It works correctly in that mono build.

Environment of this computer:
    GitExtensions version: GitExtensions-2.51.01.1743-Mono.zip
    GIT version: 2.16.2.windows.1
    OS version: Windows 10

I double checked also that the current version 2.51 from the download link still exhibits the problem on this, my home computer since it has Git version and OS version differences.
