### ISSUE TITLE
Use wip GitHub app

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4560]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Pull requests can be merged before user is done.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Prevent merges when the user has wip in the title of the pull request.

https://github.com/apps/wip
**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by vbjay** [comment]
I was thinking this could be in our repos too.  
![image](https://user-images.githubusercontent.com/3629489/38828485-40cd91ec-4184-11e8-85f5-eab5c39aa221.png)

**Comment by gerhardol** [comment]
OK for me. Just using wip in the title has improved the visibility of issues that should not be merged

**Comment by vbjay** [comment]
Closing because it was implemented.

**Comment by vbjay** [comment]
Closing because it was implemented.
