### ISSUE TITLE
Confused about handling submodules.

### ISSUE THREAD

**Issue by a-einstein** [gitextensions/gitextensions#4576]
**Do you want to request a *feature* or report a *bug*?**
Not sure.
I noticed there are some more issues about this topic going on .

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
**What is the expected behavior?**

I am totally confused by the basic functionality, which does not seem to work, but suggests otherwise. Or works in an unexpected and unpractical way after all.
- I have got a repository as a submodule in a second one. I use a project of the first in the solution of the second.
- I changed, committed and pushed files in the first. I get no sign whatsoever in the second. Both are on the master branch.
- I opened GitExtensions to see what is going on, and how I can synchronize. Simply pull has no effect.
- There is a dialog Submodules in which the submodule is listed, but which shows status Up-to-date.
- Pushing button 'Synchronize' or 'Update' have no effect.
- Then I noticed a separate Pull button next to the branch field. I tried that and got a synchronization. But now that appears as a change in the second repository, which I apparently should commit too. The status in GitExtensions has changed to Modified. Is this supposed to be? 
- Oh wait, now that change (that I saw at least in VisualStudio as some mention about a submodule) has disappeared again. And GitExtensions shows 'status 'Up-to-date again. And the changed files  are displayed correctly in Visual Studio now. So I thought. No, the changes have disappeared too. I do not know how all that happened.
- I repeated the Pull and got into the 'Modified' state again. I committed in the second repository and now it all seems synchronized.
- I notice the buttons 'Update all submodules' and 'Synchronize all submodules' which I had not tried yet. What is the difference? Would this have done what I wanted? Why didn't they work in the dialog?

I am confused.
How is all this supposed to work, and be used?
Does it work as supposed?

I am looking for a practical way to get notified and/or to synchronize easily and methodically. And preferably in GitExtensions or VisualStudio, I did not touch Git directly so far.

**Environment you encounter the issue:**
- GitExtensions version: 2.51.
- GIT version: 2.16.1.4.
- OS version: Windows 10 professional 10.0.16299.248.

**Did this work in previous version of GitExtensions (which)?**
Had not tried yet.

**Comment by gerhardol** [comment]
Submodules solves the problem they are intended to solve, but you need to see the problem as the designers did, especially the names of commands can be confusing. A submodule are not intended to be updated to latest version from the super project. (The --remote option exists, but that option is making submodules even more confusing.) You have to go to the submodule, select a commit and then commit in the superproject.

GE tries to support submodules in a standard Git way, but with better visibility/control compared to other Git GUI I have tried. But GE will not help you understand how the designers was thinking when designing.

So I do not believe anything can be done here.

**Comment by vbjay** [comment]
Think of submodules as pointers to a commit in another repo. When the
history in your submodule changes to a different commit, the master repo
will see that the submodule repo is currently at a different commit. When
you stage and commit that change in the master repo, you are marking the
current commit in the the submodule as the commit that gets checked out
when git submodule update is run in the master repo.
