### ISSUE TITLE
Git Fetch

### ISSUE THREAD

**Issue by MgSam** [gitextensions/gitextensions#4583]
We have many branches and need to often use `git fetch` to update our view of the remote repository. Related to this, two questions:

- Why isn't there a button in Git Extensions to do a fetch? We have to drop to the bash shell to do this (and then click the GUI refresh button) and it's an annoying workflow.
- Other Git clients provide an auto-fetch feature where the client is periodically running `fetch` by itself to keep the GUI updated. Would this make sense for Git Extensions? I think this would make for a much nicer UX.

**Comment by RussKie** [comment]
All functionality is there:
![image](https://user-images.githubusercontent.com/4403806/37059500-be48f4ee-21e1-11e8-8e08-0daca539ea52.png)

**Comment by gerhardol** [comment]
Periodic fetch

![image](https://user-images.githubusercontent.com/6248932/37059671-530a3a4c-218e-11e8-9c02-b31cf759f661.png)

**Comment by MgSam** [comment]
Thanks very much!! I tried Googling extensively first but was unable to find this information.

**Comment by RussKie** [comment]
For these sorts of things the repo is much better place than google
