### ISSUE TITLE
Create pull request - local branches not populated

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4589]
**Do you want to request a *feature* or report a *bug*?**

bug 

**What is the current behavior?**
![gitext](https://user-images.githubusercontent.com/1003909/37084351-8d777532-21f2-11e8-9b2f-6b4f5c02bd9d.png)

**What is the expected behavior?**
![gitext05](https://user-images.githubusercontent.com/1003909/37084358-908ca9a4-21f2-11e8-9432-a805a10c13d8.png)

**Environment you encounter the issue:**

- GitExtensions version: 3273f088634a71d29aa2ceac5ca0e86c0ef300bf

**Did this work in previous version of GitExtensions (which)?**
Yes: 2.51

**Comment by vbjay** [comment]
Did you make sure you have a valid token set up?

**Comment by jbialobr** [comment]
Yes, I did. The "expected" screenshot shows the 2.51 version working correctly and used to create a PR a minute later.

**Comment by vbjay** [comment]
Weird. Oh. Local not remote. That is very odd.

**Comment by jbialobr** [comment]
Wanted to solve it but can not reproduce it any more.
