### ISSUE TITLE
Feature: Compare remote git with working git?

### ISSUE THREAD

**Issue by scascalesp** [gitextensions/gitextensions#4591]
Hello
Is posible to compare remote git with local git?

I read this: https://github.com/gitextensions/gitextensions/issues/1596 but oi don't know what's the 'revision grid '?

I search manuals to investigate it:
http://gitextdoco.readthedocs.io/en/latest/settings.html
https://github.com/gitextensions/gitextensions/wiki

thakns!

**Comment by RussKie** [comment]
Do you mean _remote branch_ and _local branch_?

![image](https://user-images.githubusercontent.com/4403806/37148179-98f04610-231d-11e8-98f9-4b28fb16d880.png)

**Comment by vbjay** [comment]
I suggest you go through these two links.

http://www.vogella.com/tutorials/Git/article.html

https://git-extensions-documentation.readthedocs.io/en/latest/

**Comment by scascalesp** [comment]
Thanks! I try
