### ISSUE TITLE
Remove SVN support

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4592]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
GitExtensions has support for SVN

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The very limited support for SVN is likely not of use for anyone, a dedicated client should be used.
SVN is slightly confusing in the interface.
It may not be a major maintenance issue, but still something to cleanup for 3.00

**Environment you encounter the issue:**

- GitExtensions version: master

**Comment by juliankopkalarsen** [comment]
I do not have the right to complain since I did not keep up with the issues and provide feedback So I only noticed it when updating because it is critical to my workflow.
But here is my feedback none the less.
I use git-svn to do local vcs before committing to the company svn server.
I have been trying for years to get everybody on board  the switch to git with limited success.
Could it be possible to have svn functionality as a plugin?

**Comment by gerhardol** [comment]
Could be possible, it was not a deep integration. 
Of course it is possible to use command line still.

**Comment by RussKie** [comment]
Pull requests are welcome, as no one in the core team and none of our
active contributors use SVN, and thus unlikely to have any interest/ability
to build it.

If a plugin were to be built, I suggest to develop it as a separate
standalone project and utilise @maraf's Plugin Manager.

v2.51 supports SVN and is still available.

**Comment by maraf** [comment]
In [GitExtensions.EmptyPlugin](https://github.com/maraf/GitExtensions.EmptyPlugin) I'm slowly baking an how-to create GE plugin distributed as NuGet package.

**Comment by abluett** [comment]
Yeah we noticed it missing at our workplace as well, we have worked around it by creating script commands for the common actions. I would be keen to help out with a plugin if one is being created. Not sure if the new branches tree is assessable for plugin injection as it would be good to have SVN remote branches in there like source tree does.

**Comment by vbjay** [comment]
You got it.  We have plans on removing existing plugins from our repo and making them stand on their own.  So we will be dogfooding along with you when that happens.  So don't feel like we will just drop the ball.  We like our plugins.  But they are more ancillary projects and mot true plugins as they stand now.

**Comment by gerhardol** [comment]
> Is my understanding correct or am I missing some important piece of information?

I believe so

**Comment by RussKie** [comment]
@mast-eu you captured it quite nicely.
Yes, it is a good time to shape the future of plugins, what contracts we want to put in place, and how we want to have them built.
I don't expect this road to be smooth or quick, but together we should be able to get there.

**Comment by mast-eu** [comment]
> I don't expect this road to be smooth or quick ...

Me neither, but that's no problem. I expect it to be interesting and an occasion for learning new things.

Just to leave a breadcrumb for anyone stumbling across this issue: Work on the SVN plugin will take place here https://github.com/mast-eu/GitExtensions.SVN
Comments, questions, suggestions or help of any type are always appreciated.

**Comment by gerhardol** [comment]
For fetch etc you may use scripts as wee:
https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#git-extensions-scripts

(Not for clone, maybe not for dcommit)
