### ISSUE TITLE
Excess rebase command being performed when opening the Rebase dialog

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#4593]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
In the middle of a rebase operation, clicking on the status bar button (_You are in the middle of a rebase_) runs the rebase command again.
@EbenZhang, I believe this was introduced in commit 0ad00e7ebce38be762c314187ddc93c3714643e4.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open the attached [repository](https://github.com/gitextensions/gitextensions/files/1793551/RebaseTest.zip)
1. Right-click on the `master` branch and select _Rebase current branch on →  Selected commit_
1. A merge conflict occurs
1. If the Rebase dialog opens, close it
1. Click on the _You are in the middle of a rebase_ status bar button
1. a `git rebase --autostash "master"` command is performed (and obviously fails) before the dialog opens

**What is the expected behavior?**
No extra rebase command is performed when a rebase operation is already underway.

**Environment you encounter the issue:**

- GitExtensions version: (current master)
- Git version: 2.16.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.51.

**Comment by EbenZhang** [comment]
will look into it later
