### ISSUE TITLE
Bug: File tree does not respect numeric ordering, it shows File1 then File10 then File2 ...

### ISSUE THREAD

**Issue by s7jones** [gitextensions/gitextensions#4597]
**What is the current behavior?**
File tree lists File10 before File 2

**What is the expected behavior?**
File1 then File 2 then .... File10

**Environment you encounter the issue:**

- GitExtensions version: 2.5.1
- GIT version: 2.16.1
- OS version: Windows 10

**Comment by gerhardol** [comment]
GE orders the files as Git displays them, so this is as expected

**Comment by vbjay** [comment]
Filenames are text.  Comparing characters '1' and '2' means '1' wins.  So
file1 then file10 is correct because it is text and not numbers.
