### ISSUE TITLE
Setting names are not adjusting in dark mode.

### ISSUE THREAD

**Issue by dretta** [gitextensions/gitextensions#4604]
![image](https://user-images.githubusercontent.com/2917655/37232519-91aa8df4-23ac-11e8-8611-0885a0bbbfc9.png)

If you look on the left side the setting names are still using Black font with the PC using a High Contrast Black theme, White font is excepted. This doesn't seem to be an issue for the rest of the application.

- GitExtensions version: 2.51
- GIT version: 2.14.1
- OS version: Windows Server 2012 Standard

I'm new to GitExtensions  so I can't say if this is new or not :)

**Comment by RussKie** [comment]
We are aware of a range of issues related to dark themes...
Unfortunately there is nothing we can offer as a quick fix at this stage.

**Comment by digitalcoyote** [comment]
I'd like to take a crack at this one using what was done for the dashboard as a template.

`void ApplyTheme()
            {
                _selectedTheme = SystemColors.ControlText.IsLightColor() ? DashboardTheme.Dark : DashboardTheme.Light;

                BackColor = _selectedTheme.Primary;
                pnlLogo.BackColor = _selectedTheme.PrimaryVeryDark;
                flpnlStart.BackColor = _selectedTheme.PrimaryLight;
                flpnlContribute.BackColor = _selectedTheme.PrimaryVeryLight;
                lblContribute.ForeColor = _selectedTheme.SecondaryHeadingText;
                userRepositoriesList.BranchNameColor = _selectedTheme.SecondaryText;
                userRepositoriesList.FavouriteColor = _selectedTheme.AccentedText;
                userRepositoriesList.ForeColor = _selectedTheme.PrimaryText;
                userRepositoriesList.HeaderColor = _selectedTheme.SecondaryHeadingText;
                userRepositoriesList.HeaderBackColor = _selectedTheme.PrimaryDark;
                userRepositoriesList.HoverColor = _selectedTheme.PrimaryLight;
                userRepositoriesList.MainBackColor = _selectedTheme.Primary;
                BackgroundImage = _selectedTheme.BackgroundImage;

                foreach (var item in flpnlContribute.Controls.OfType<LinkLabel>().Union(flpnlStart.Controls.OfType<LinkLabel>()))
                {
                    item.LinkColor = _selectedTheme.PrimaryText;
                }`

**Comment by RussKie** [comment]
I suggest to continue the discussion in #5489.
