### ISSUE TITLE
Multiple terminals opened

### ISSUE THREAD

**Issue by Mikilll94** [gitextensions/gitextensions#4606]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
You can have only one opened terminal in Git Extensions.

**What is the expected behavior?**
The embedded terminal in Git Extensions is a very nice feature but in many cases one terminal is insufficient. There should a possibility to open new console like in JetBrains products, i. e. WebStorm. I showed that on the screen. 

![image](https://user-images.githubusercontent.com/17653648/37244751-c99b138c-248d-11e8-8f52-584a7642c1a8.png)

**Comment by gerhardol** [comment]
You can use a separate terminal window for this

**Comment by Mikilll94** [comment]
I know that I can i.e. open cmd in Windows but it would be nice if I could manage many terminals in Git Extensions. That is more comfortable than having X terminals opened in different windows.

**Comment by GintasS** [comment]
Abandoning this because of the age and lack of discussion.

**Comment by gerhardol** [comment]
The Console tab supports a few more consoles since 3.3 or so.
These need to be implemented, more could be added by a PR.
