### ISSUE TITLE
Revision grid branches should sort current branch first

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4607]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Branches/tags are sorted from branch/tag, local/remote, name
![image](https://user-images.githubusercontent.com/6248932/37245490-e4466bea-2498-11e8-8255-74762a55afff.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Sort branch/tag, local/remote, current, name
![image](https://user-images.githubusercontent.com/6248932/37245477-b41c20d6-2498-11e8-83cb-fbea2aaf6abb.png)

**Environment you encounter the issue:**

- GitExtensions version: all
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by vbjay** [comment]
I would use https://msdn.microsoft.com/en-us/library/8ehhxeaf(v=vs.110).aspx.
That way we can alter how by adding other comparers that inherit from the
generic interface.

**Comment by gerhardol** [comment]
IComparer is already used. The code could have been rewritten with Linq too.

**Comment by vbjay** [comment]
Yes. The comparers would be better. That way we could have other ways
defined and just use them. Heck with di we could let the user say they want
it sorted x way and we would just say hey get me the branch or ref compare
the user defined.

**Comment by RussKie** [comment]
Yes, DI would be nice, that's one of many reasons to SOLIDify the codebase.... 
Though we are still a long way away form it.
