### ISSUE TITLE
Feature request: Rename Branch

### ISSUE THREAD

**Issue by Bootta11** [gitextensions/gitextensions#4632]
No option for renaming branch? Its so simple git command : git branch -m old_branch_name new_branch_name 

I'm using Git Extensions version 2.51

**Comment by jbialobr** [comment]
![gitext](https://user-images.githubusercontent.com/1003909/37389033-fa7ca4ca-2762-11e8-8e4a-ac749bef0cf8.png)

**Comment by Bootta11** [comment]
Thx for help.

**Comment by phillijw** [comment]
I thought this used to exist in the Commands menu but maybe I'm misremembering. Was that the case?
