### ISSUE TITLE
incorrect nesting of `simplify by decoration`

### ISSUE THREAD

**Issue by jeroendv** [gitextensions/gitextensions#4642]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/1921532/37514982-b784e7e2-2909-11e8-8d8e-8e4e332eed5a.png)

the option `simplify by decoration` seems to be a suboption of the `branches` option.
Visually, because it is indented, but also logically because it is greyed out if `branches` is not checked.

**What is the expected behavior?**

This feels odd however, because the `simplify by decoration` has effect independent of the `Branches` checkbox state. Indeed it is well defined independent of whether one is showing all branches, just the active branch or a set of filtered branches. So the `simplify by decoration` option should be be nested under `branches`.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: git version 2.15.1.windows.2
- OS version: Windows 7

**Comment by GintasS** [comment]
Abandoning this because of the age and lack of discussion. The issue is still there, but no one discussion here/no one picked this up.
