### ISSUE TITLE
Displaying information about GPG signature in commit's summary

### ISSUE THREAD

**Issue by Wirone** [gitextensions/gitextensions#4644]
I would like to ask for new feature: displaying (in "Commit" tab) information about commit's GPG signature. As of now (2.51) I can't see option for displaying it and I don't know if my commit done with GitExtensions was signed (I have `gpg-agent` and global Git config for auto-signing commits and tags).

In order to check if commit was signed I need to do `git log --show-signature -1`.

- GitExtensions version: 2.51
- GIT version: 2.16.2
- OS version: Kubuntu 16.04

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/37550959-eadcf49a-29ea-11e8-9f3a-d28cabaacef0.png)

![image](https://user-images.githubusercontent.com/4403806/37550969-3f8674ee-29eb-11e8-8d99-55e02f446fe3.png)

**Comment by Wirone** [comment]
Whoa, I missed that config somehow, thanks!
