### ISSUE TITLE
Questions about GitCommandHelpers.SetEnvironmentVariable

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4664]
Looking at `GitCommandHelpers.SetEnvironmentVariable` (as part of research into #4643), I have some questions about potential issues. At the very least if the code's fine as is, I will document it based on responses here.

### Question 1 (fixed in #4668) 

If `AppSettings.CustomHomeDir` or `AppSettings.UserProfileHomeDir` are set, the `HOME` environment variable is set accordingly, but then the method returns, skipping any attempt to set `SSH_ASKPASS`. Is that right?

### Question 2 (fixed in #4668)

If `reload` is `true`, `HOME` is set to `UserHomeDir`, but then immediately overwritten with `GetDefaultHomeDir()`. Should there be an `else` here? Is the `reload` parameter even needed if it's not functioning?

### Question 3

If you're running on Windows, but `GitExtSshAskPass.exe` doesn't exist for whatever reason, the `SSH_ASKPASS` env variable is not set at all. Is that right?

### Question 4

These variables are generally set on the GE process's environment which is then inherited by child processes (if I understand correctly). Would it make more sense to set these variables directly on the child process when creating it via `process.StartInfo.EnvironmentVariables`?

**Comment by vbjay** [comment]
On 4, yes that's a good idea. However, we still need to set the variables
the normal way so that other process trees get the same setting. I'd e pect
configuration in GE to configure my system and not just GE processes.

**Comment by jbialobr** [comment]
Q1: It is a bug. There is also TERM variable omitted in such a case.

Q2: See the implementation of GetDefaultHomeDir - it queries for HOME in the first place.

Q3: @KindDragon  Could you help with that?

Q4: Perhpas yes (exploratory tests needed), but not all cases are for inheriting by child processes.

**Comment by drewnoakes** [comment]
@jbialobr thanks for your insight. I'll put a PR together that addresses 1/2 for now, and add some docs.

**Comment by drewnoakes** [comment]
Another potential (unlikely) but in that method is that if the user doesn't have a `PATH` variable, there'll be a NRE on the second line via the `path` local.

I've attempted to fix both in #4668 and tried to make the code a bit easier to read (subjective, I know).

**Comment by drewnoakes** [comment]
On #4668 I wrote:

> None of this tests whether the paths exist. Is there any use in doing so?

Perhaps the current logic could provide a sequence of options based upon configuration, and we take the first that actually has a value. For example:

```c#
string ComputeHomeLocation()
{
    return GetLocationOptions().FirstOrDefault(Directory.Exists);

    IEnumerable<string> GetLocationOptions()
    {
        yield return AppSettings.CustomHomeDir;

        if (AppSettings.UserProfileHomeDir)
        {
            yield return Env.GetEnvironmentVariable("USERPROFILE");
        }

        yield return GetDefaultHomeDir();
    }
}
```

Would be a change in behaviour, but would also increase the likelihood of the home directory existing on disk.

**Comment by jbialobr** [comment]
If I set `CustomHomeDir` and it does not exist then I would expect to be notified about that rather than silently using the default home dir.

**Comment by RussKie** [comment]
But we should do it nicely without crashing the app

**Comment by KindDragon** [comment]
> If you're running on Windows, but GitExtSshAskPass.exe doesn't exist for whatever reason...

It's always installed with the app.

> the SSH_ASKPASS env variable is not set at all. Is that right?

We can't do anything else in this situation

**Comment by RussKie** [comment]
Bump. Is this something we wish to pursue?

**Comment by gerhardol** [comment]
I suggest to keep 3&4 as-is and close this issue.

**Comment by drewnoakes** [comment]
Happy to close.
