### ISSUE TITLE
Installer should default to current OpenSSH/PuTTY decision

### ISSUE THREAD

**Issue by otbutz** [gitextensions/gitextensions#4679]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The installer defaults to PuTTY even if the existing installation is configured to use OpenSSH.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Install git extensions and select OpenSSH as the SSH client
2. Update the installation by executing the installer again
3. The installer will default to PuTTY if it's installed

**What is the expected behavior?**
If an already existing installation is updated, the previous choice should be the default.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.16.0.windows.2
- OS version: Win10 x64

**Did this work in previous version of GitExtensions (which)?**
No.

**Comment by freza-tm** [comment]
duplicate  of #6286

**Comment by freza-tm** [comment]
closed by #6286

**Comment by gerhardol** [comment]
Changed in 3.3.1
