### ISSUE TITLE
Filter text is covered 

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4683]
**Do you want to request a *feature* or report a *bug*?**

bug 

**What is the current behavior?**
There is `json` typed in the filter box:
![gitext](https://user-images.githubusercontent.com/1003909/37700256-107219ee-2ceb-11e8-8307-7ee9b4bd40a3.png)

**What is the expected behavior?**

`Filter files...` should not be visible after typing a text

**Environment you encounter the issue:**

- GitExtensions version: 5b9df7db6e6bc2fefaaceb5adb0e4cbb6bc283d4

**Did this work in previous version of GitExtensions (which)?**
Yes: 2.51

**Comment by gerhardol** [comment]
In addition, when you click the `Filter files...` , the control is not selected, you cannot type in it.
