### ISSUE TITLE
List of submodule changes in CommitForm broken

### ISSUE THREAD

**Issue by minj** [gitextensions/gitextensions#4684]
https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/FormCommit.cs#L2095

This assumes `diff.submodule` is set to "short".

Please make it explicit by calling `diff --submodule=short` in the line above

**Comment by RussKie** [comment]
Thank you for the submission.
However please use the template provided, it is there for a reason.

**Comment by sharwell** [comment]
@minj The file has changed since the time you submitted this issue. I would recommend you use the following feature of GitHub to ensure the context is not lost in references to code:

![image](https://user-images.githubusercontent.com/1408396/38030065-336643b8-325d-11e8-836d-5e5b7f741a92.png)

**Comment by minj** [comment]
Not really, it hasn't.. that much:

https://github.com/gitextensions/gitextensions/blob/fb7b987690ff80d21e048a0eadea22d67d661728/GitUI/CommandsDialogs/FormCommit.cs#L2099

**Comment by RussKie** [comment]
@gerhardol @vbjay is this something quick to fix?

**Comment by RussKie** [comment]
Ignore this, it has been fixed.
