### ISSUE TITLE
file history will highlight wrong revision

### ISSUE THREAD

**Issue by qianyilan** [gitextensions/gitextensions#4685]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
 met the same bug #4440 too, modified '1.txt' in two different branches,and then merged them.
![image 1](https://user-images.githubusercontent.com/26076536/37702843-ca3d88fc-2d2e-11e8-8e7f-04e6c3eea552.jpeg)

when double click the file in file history,file history will highlight wrong revision.
![image](https://user-images.githubusercontent.com/26076536/37702852-d225921c-2d2e-11e8-8469-091e1e32dffd.jpeg)

git log -1 --filename,the result is different from highlighted revision.
![image 2](https://user-images.githubusercontent.com/26076536/37702868-ddf3db4e-2d2e-11e8-8c3a-72ef4934460e.jpeg)

**Environment you encounter the issue:**
GitExtensions version: 2.51
GIT version: 2.13.2
OS version: WIN7

**Comment by jbialobr** [comment]
It seems to work correctly. Could you elaborate on why you think it is wrong?

**Comment by qianyilan** [comment]
i think it should highlight the "1708_B" revision,like the command "git log -1 1.txt' shows

**Comment by jbialobr** [comment]
>i think it should highlight the "1708_B" revision,like the command "git log -1 1.txt' shows

Yes, you already have told that. I am asking for a reason. Is there any reason you expect it to be selected other than git log -1 shows it as as a first entry in its output?

**Comment by qianyilan** [comment]
To my knowledge, git log -1 shows the latest file history,so I think it was a bug.
