### ISSUE TITLE
Multi-monitor environment - pop-up's should stays at the same monitor as opened application

### ISSUE THREAD

**Issue by Bryksin** [gitextensions/gitextensions#4686]
**Do you want to request a *feature* or report a *bug*?**

It is usability Improvement

**What is the current behavior?**

Pre-condition: <br/>
Multi-monitors environment<br/>
Authentication through HTTPS<br/>
If application opened on any other monitor but not default, authentication pop-up window with login/pass fields appears on default monitor, but not the same as the application opened

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1) Open application
2) Open Project
3) Move application to another monitor
4) Try to pull from https, so it will ask your credentials
5) Pop-up Auth window will appear on default monitor, but not the same as the application

**What is the expected behavior?**

Auth pop-up window would appear on the same monitor as the application

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: Doesnt realy matter in this case
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**

Don't think so, but can't be sure for 100%

**Comment by Briksins** [comment]
Just to add more comments: 
This UI problem is not only related to authentication window, but also to some others

It is expected that wherever I have the main window opened - any pop-up windows should open as an overlay of the main window at the same monitor
But sometimes some pop-ups go to default Monitor instead of the Monitor where the main window opened

From now on I will start noting which exactly pop-ups are disconnected from the main application screen, there was more than just auth pop-up, but I forgot what exactly.... Will add more details in the future

**Comment by vbjay** [comment]
The auth window is a separate process.

**Comment by Briksins** [comment]
it doesn't matter if its separate process or not, the UI should appear at the monitor you are working on (where main application is opened)

Imagine my case, I have 3 monitors:
![Alt Text](https://i.gyazo.com/aa4e1ba4c8860a2121879107a2660f39.jpg)

Sometimes I don't even notice that new pop-up appeared on another monitor (especially if there are other windowses are open), so I'm just sitting and waiting for `pull` action to complete... but the process might ask me to re-enter credentials time to time so it waiting for my input and it takes ages before I realise that might be auth pop-up was opened on another monitor... small thing, but very annoying and not right from user usability point of view

**Comment by vbjay** [comment]
I guess you didn't catch my point. That separate process is in control of
it's windows.

**Comment by drewnoakes** [comment]
It may be possible to access the main window handle of the child process and use P/Invoke (`MoveWindow` in `user32.dll` IIRC) to position it explicitly after it is shown.

The `Process` class has a `MainWindowHandle` property. Might need to use `Process.WaitForInputIdle` as well.

**Comment by gerhardol** [comment]
Opening popups is a Windows "feature" done by many applications like Visual Studio. 
I have to disable the TV output to avoid lost popups.

**Comment by RussKie** [comment]
I believe this is fixed in #5671, available in [RC2](https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00-rc2)
