### ISSUE TITLE
Failed to load plugin Atlassian.Jira.dll

### ISSUE THREAD

**Issue by escherstair** [gitextensions/gitextensions#4689]
Bug

I upgraded GitExtensions from 2.51 to 2.51.01 on Win 7 64 bit

Steps to reproduce:
1. Open GitExtensions
2. After a couple of seconds a popup appears (see attached image capture.png ![capture](https://user-images.githubusercontent.com/22594460/37760746-da7e6d42-2db7-11e8-9668-33e60dd8c874.PNG))
3. Press Ok in the popup
4. Another popup appears (see attached image capture01.png
![capture01](https://user-images.githubusercontent.com/22594460/37760760-e475eb22-2db7-11e8-9ec0-a3140d73d3a1.PNG)
)

- GitExtensions version: 2.51.01
- GIT version: 2.16.2
- OS version: Win 7 SP1 64 bit

In version 2.51 the popup didn't appear.

**Comment by RussKie** [comment]
Thanks
Hmm I thought it was my messed up install only... appears it was not.

Could you try renaming C:\Program Files (x86)\GitExtensions\ to something
else (or move files to another folder) and run the installed again to see
whether the problem goes away

**Comment by RussKie** [comment]
What installer did you use - Setup or SetupComplete?

**Comment by escherstair** [comment]
Renaming and installing doesn't fix the issue.

I used SetupComplete.

**Comment by RussKie** [comment]
It looks like the SetupComplete didn't build correctly.
I have rebuilt it and uploaded an updated version. I've done a clean
install locally and it seems to have worked.
Could you please try downloading the new SetupComplete and install it?

**Comment by escherstair** [comment]
I confirm that the new installer fixes the issue but **it's necessary to delete or rename C:\Program Files (x86)\GitExtensions\ before installation**.

Installing over the previous C:\Program Files (x86)\GitExtensions\ doesn't solve.

**Comment by RussKie** [comment]
Correct, installing over the corrupt install doesn't solve the issue.

**Comment by drewnoakes** [comment]
Is `RestSharp.dll` in the `C:\Program Files (x86)\GitExtensions` folder?

If so, and you have VS or any .NET SDK installed, you can get more information from Fusion Log Viewer (`fuslogvw.exe`).

```cmd
C:\Program Files (x86)>dir /s fuslogvw.exe
```

This tool will allow you to add more information to the error report.

- Run as administrator
- Open settings
- Select "Log bind failures to disk" and press OK
- Start GitExtensions
- Click refresh in the log viewer
- Select the RestSharp row and click 'View Log'
- It opens an HTML file, which you can copy/paste the content of to this issue

#### Log for successful RestSharp.dll binding on my PC (GE 2.51)

```
*** Assembly Binder Log Entry  (22/03/2018 @ 12:55:11) ***

The operation was successful.
Bind result: hr = 0x0. The operation completed successfully.

Assembly manager loaded from:  C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Running under executable  C:\Program Files (x86)\GitExtensions\GitExtensions.exe
--- A detailed error log follows. 

=== Pre-bind state information ===
LOG: DisplayName = RestSharp, Version=105.2.3.0, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/GitExtensions/
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = GitExtensions.exe
Calling assembly : Atlassian.Jira, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files (x86)\GitExtensions\GitExtensions.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Binding succeeds. Returns assembly from C:\Program Files (x86)\GitExtensions\RestSharp.dll.
LOG: Assembly is loaded in default load context.
```

**Comment by drewnoakes** [comment]
Oops, didn't refresh the page for the last few hours. Glad you got it sorted.
