### ISSUE TITLE
Escape key should dismiss the file deletion confirmation dialog

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4691]
Usability bug.

**What is the current behavior?**

Pressing <kbd>Escape</kbd> has no effect. It does dismiss other dialogs such as for 'reset changes'.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Select an unstaged file and press the <kbd>Del</kbd> key. This dialog appears:

![image](https://user-images.githubusercontent.com/350947/37778763-aa1f684c-2de2-11e8-8d1f-c918c210f9c0.png)

Press <kbd>Escape</kbd> and nothing happens.

**What is the expected behavior?**

Dialog should disappear and nothing should be deleted.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 2.60
- OS version: Windows 10

**Comment by drewnoakes** [comment]
This is a limitation of `MessageBox.Show`. Unless the `MessageBoxButtons` contains a cancel option, <kbd>Escape</kbd> doesn't work.

Options are to use `YesNoCancel` (which would be strange for the user) or to implement a custom message box. Neither seem like a good fit so I'm going to close this. No doubt it applies to 64 other usages of `MessageBoxButtons.YesNo` in the solution equally.

There's a missing word in the dialog though, which I'll add.

**Comment by sharwell** [comment]
@drewnoakes did you mean to close this? The commits referencing this issue appear unrelated.
