### ISSUE TITLE
Locale based absolute date

### ISSUE THREAD

**Issue by tpb261** [gitextensions/gitextensions#4692]
Feature request.

The absolute date is of the format mm/dd/yyyy. It should be configurable (for people not using this format, it's quite confusing - esp since I use dd/mm/yyyy).

Windows (and possible other platforms as well).

- GitExtensions version: 2.50.02
- GIT version: 2.13.2.windows.1
- OS version: windows 7

Check the red marked rectangle in attached image (removed all other content).
![gitdates](https://user-images.githubusercontent.com/263006/37814660-1d9f4180-2e91-11e8-8d35-1e3fc88e2ee8.png)

**Comment by drewnoakes** [comment]
These dates appear as dd/MM/yyyy on my PC. I expect the code uses a computer-level setting here.

Can you review the setting, as described here: https://superuser.com/q/23875/31787

**Comment by tpb261** [comment]
Oh, yes. That's right. Thanks for the quick reply!!
