### ISSUE TITLE
Selection in DiffFiles not working

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4693]
**Do you want to request a *feature* or report a *bug*?**

bug related to #4601
/cc @sharwell 

**What is the current behavior?**

![gitext](https://user-images.githubusercontent.com/1003909/37824832-33d9020e-2e8e-11e8-92ce-1584b4a11818.png)

It is most likely related to this line https://github.com/gitextensions/gitextensions/pull/4601/files#diff-7aca6c90354549c4c40587e6d82baf10R129

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Choose two files and select the first one then the second one then the first one and so on until the diff
does not get refreshed.

**What is the expected behavior?**

Diff for the selected file should be shown.

**Environment you encounter the issue:**

- GitExtensions version: ea4c75d54af2f90ff4db2c651fec132c7078c362

**Comment by sharwell** [comment]
Thanks for the report. I have now resolved this in my branch.

The interaction between RX and vs-threading is interesting.

**Comment by jbialobr** [comment]
Thank you! Yeah, threading in general is interesting.
