### ISSUE TITLE
Plugin loading performance at startup

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4694]
Following #4689 I took a bit of a look at plugin loading.

In current (Git Extensions 2.51) code, plugins are discovered by scanning assemblies as follows:

- for every file in the `Plugins` folder
- if that file doesn't start with `System.`, `Microsoft.` or `ICSharpCode.`
  - load the assembly into memory
  - check for any concrete types that implement `IGitPlugin`
  - instantiate and register them

Running this a bunch of times on my computer shows it takes about 845 ms to complete this (debug build, modified `Main` to just load plugins and stop).

Actually this process loads quite a few files that don't contain any plugins. Without the current prefix exclusions it takes closer to 10 seconds. But we can do better still.

The first thing I tried was to add an assembly attribute that details the exact types to load from an assembly. This cut the time down to 702 ms, saving about 17%.

The next thing I tried was to whitelist the plugin assemblies. This brought the time down to 505ms, saving a further 28% (or saving 40% in total).

White-listing like this introduces a coupling we probably don't want. Instead I would introduce a convention requiring plugin assembly file names to start `GitExtensions.Plugins.`. Then we can get rid of any white/black-listing but still get the same perf improvement.

These timings were all averaged over 5-10 runs, depending upon volatility. Note that my machine is pretty snappy and doesn't have heavy security/virus software like many corporate machines do. The savings could be greater in different contexts.

We'd likely allocate less memory at startup with this approach as well.

Any challenges with renaming the plugin assemblies, beyond updating the installer?

**Comment by drewnoakes** [comment]
> Go for it

I'll hold off until #4601 is merged to avoid conflicts.

**Comment by sharwell** [comment]
We should consider adopting vs-mef, which would allow the startup sequence to be cached after the first run and avoid delays in subsequent launches.

**Comment by vbjay** [comment]
NICE find.  What's cool is if a user desired to add their own plugin, we could let them. Haven't looked at the plugin code but exposing 
- dynamic menu creation in plugins menu
- settings ui
- dialog ui
- repo info
    - selected commit
    - current repo path
    - ....

Good to know:  https://github.com/Microsoft/vs-mef/blob/master/doc/mef_library_differences.md

**Comment by drewnoakes** [comment]
Looks like MEF is currently only used by build server integration. 

The `GitUIPluginInterfaces.ManagedExtensibility` class does yet another scan of DLLs in the `Plugins` directory. It's also the source of plenty of type load exceptions (look at trace output during debugging). Perhaps there's a better way of targetting what files it should be scanning. I suspect it's not the same list as GitExtension's own plugins.

Scanning the 32 DLLs in the installation `Plugins` folder produces 4 exports for `GitUIPluginInterfaces.BuildServerIntegration.IBuildServerAdapter` in 1,188.58 ms on the thread pool.

> What's cool is if a user desired to add their own plugin, we could let them

If an assembly contains a type that implements `IGitPlugin` in the `Plugins` directory today, it'll get picked up and can register commands. There's more that could be done here, for sure.

> avoid delays in subsequent launches

Should point out that neither of these plugin scans are directly blocking the UI from showing. However they contribute to general activity during startup which will impact responsiveness.

**Comment by vbjay** [comment]
Right.  We should make all plugins vs-mef.  The caching would help with that.  If you notice, vs shows that writing cache progress dialog when it updates the mef content.

**Comment by RussKie** [comment]
Nice work. 

We had some discussions about MEF and plugins in general. 
Unfortunately I haven't used MEF at all to say one way or the other (outside GE I haven't done any serious Windows development since 2007). I've done some reading, it sounds interesting, and looking at VS it seems to be quite a powerful thing.

Ideally plugins shouldn't be part of the main repo and be separate projects, maybe even maintained by others. This approach has its drawbacks - like lack of discoverability and ability to install - a plugin store, in a nutshell.

**Comment by sharwell** [comment]
> What's cool is if a user desired to add their own plugin, we could let them. Haven't looked at the plugin code but exposing these and more would be a good idea

This is not a path I would recommend at this time. MEF is low-risk for composing an application that has many parts (like this one does), but you quickly get into pitfalls when you try to expand past the main repository. We can get into the details, but it should be a separate discussion since it would quickly derail the main topic of this issue.

**Comment by gerhardol** [comment]
I suggest we go for the easy route right now: Name pattern for the plugins
If MEF usage is obvious we can consider that too

The need for plugins not following the core app should be low. We should rather optimize releases instead.
For users that build their own plugins, they can build (and potentially distribute) a custom version of GE too.

**Comment by vbjay** [comment]
Actually. You don't. The point is that you make the plug-in architecture
the the same. You provide the same functionality to all external plugins
and ours that provide the side functionality. The point is that of someone
comes along and says I'd like to add a _____ plug-in to GE. If we provided
the interfaces, and exports then they could. MEF is all about
discoverability.

**Comment by drewnoakes** [comment]
Another potential option is to load assemblies in a reflection-only context to look for plugins, before doing a full load. This might be faster.

I tried this and hit problems because plugins reference assemblies that are already loaded into the primary context. You also have to do some messing about with separate AppDomains. Still it might work given some more effort.

Only mentioning it here in case someone knows the problem I'm referring to and how to solve it, and also to capture this gist on the issue:

https://gist.github.com/Shazwazza/7147978

**Comment by vbjay** [comment]
Drew. That's the whole reason to use mef. Mef or vs-mef will handle loading
the plugins. The control of what is loaded can be controlled.
Appdomain.AssemblyResolve can be used to look in plugin folder too and if
we desired, we could use a plugin folder to hold just the plugin assemblies
and a refs folder in plugin folder that contained the dependencies per
plugin.  Mef gives us the control of handling it however we want.

**Comment by vbjay** [comment]
Interesting article on using a shadow cache.
https://www.codeproject.com/Articles/633140/MEF-and-AppDomain-Remove-Assemblies-On-The-Fly

**Comment by RussKie** [comment]
I think this is done.
