### ISSUE TITLE
No longer avatar picture after 2.51.01 update

### ISSUE THREAD

**Issue by francoas** [gitextensions/gitextensions#4696]
**Do you want to request a *feature* or report a *bug*?**

Bug 

**What is the current behavior?**

In the main window, commiter's avatar picture is no longer shown 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just open the main repos windows

**What is the expected behavior?**

Show the committer avatar picture

**Environment you encounter the issue:**

- GitExtensions version: 2.51.01
- GIT version: 2.16.2
- OS version: Windows 8.1

**Did this work in previous version of GitExtensions (which)?**

Yep
2.51

**Comment by RussKie** [comment]
I am unable to repro it...

![image](https://user-images.githubusercontent.com/4403806/37857708-8e0492fc-2f51-11e8-98b9-df46e0ac1077.png)

![4696](https://user-images.githubusercontent.com/4403806/37857699-79bc763e-2f51-11e8-81a6-2a339d6a75db.gif)

**Comment by francoas** [comment]
Dunno what to say... 
I'll try a new install from scratch

**Comment by RussKie** [comment]
Images are stored in C:\Users\<your user>\AppData\Roaming\GitExtensions\GitExtensions\Images folder.
Please check that folder is accessible... 
Maybe run fiddler and see if web requests are attempted to gravatar and github

**Comment by drewnoakes** [comment]
Can you post a screenshot please?

**Comment by francoas** [comment]
The folder exists and is accessible but is EMPTY. 
My settings are configured to use gravatar

Anyway. I accessed gravatar and checked for my image
Then I used fiddler and saw taht the connection to gravatar and the images downloaded

After that images appeared again 

Can't explain how and why. But now it looks solved
