### ISSUE TITLE
"Revision" field of "Create Branch" dialog clipped on hdpi

### ISSUE THREAD

**Issue by tomlogic** [gitextensions/gitextensions#4702]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
field too short on hdpi display (see attached screenshot)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
open Create Branch dialog

**What is the expected behavior?**
should be able to read commit sha in field

**Environment you encounter the issue:**
Windows 7

- GitExtensions version:
- GIT version: 2.51
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
I don't think so.

<img width="478" alt="screenshot 2018-02-28 17 45 33" src="https://user-images.githubusercontent.com/1102448/37870706-f8f61aba-2f90-11e8-8a59-08d3a636a5c0.png">

**Comment by RussKie** [comment]
Fixed in #4889 and 268fa27d759241aac59e3045268b9fb05a31abe9
