### ISSUE TITLE
"Open Local Repository" window too short on hdpi display

### ISSUE THREAD

**Issue by tomlogic** [gitextensions/gitextensions#4704]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
See screen shot.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Can thankfully still click on the button, but not sure what it actually says (maybe OK?).

**What is the expected behavior?**
Window should appear similar to non-hdpi display.

**Environment you encounter the issue:**

- GitExtensions version: 2.51
- GIT version: 
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**
No

<img width="607" alt="screenshot 2018-03-08 13 38 59" src="https://user-images.githubusercontent.com/1102448/37870752-ea4f499a-2f91-11e8-918f-55b90403ae1f.png">

**Comment by vbjay** [comment]
Would you please take the time to search issues before posting your own?

**Comment by tomlogic** [comment]
Duplicate of #4174.
