### ISSUE TITLE
Items in Visual Studio "GitExt" menu have no effect

### ISSUE THREAD

**Issue by peterremote1980** [gitextensions/gitextensions#4708]
whatever i click on the menu (any of them), no effect at all

1. Win server 2016
2. VS 2017 with all latest patch

thanks

**Comment by gerhardol** [comment]
What ge version? 
What menu, is it ge?

**Comment by kwints** [comment]
Same issue when using the menu in Visual Studio.  Menu opens fine then selecting any option does nothing. 
 VS 2017
getExt 2.50.2

other Git tools installed 
Git for Windows 2.16.2
visual studio 2017  extensions  : Gitflow 1.2.2.0 & GitHub 2.4.3.1737

**Comment by gerhardol** [comment]
![image](https://user-images.githubusercontent.com/6248932/37994376-a2cd5314-3211-11e8-8070-3b39327af6c2.png)

**Comment by RussKie** [comment]
What happens when you click GE toolbar buttons?

**Comment by sharwell** [comment]
Interesting. I never use this extension inside VS but I can check to see if anything is registered in a problematic way.

**Comment by RussKie** [comment]
Sam,  is there anything you could check #4117?

**Comment by tranquilChaos** [comment]
Same. Menu displays, but clicking any option does nothing (doesn't open a window, nothing).

Visual Studio Professional 2017, 15.6.1
ReSharper Ultimate 2017.3
HPE Security Fortify

Everything else is just standard default stuff.

**Comment by drewnoakes** [comment]
@tranquilChaos @kwints, what version of Windows are you on?

@tranquilChaos @peterremote1980 are you referring to the menu in Visual Studio or the menu in the standalone application?

**Comment by tranquilChaos** [comment]
@drewnoakes I'm on Windows 10 Enterprise 10.0.16299 Build 16299

I'm referring to the Visual Studio menu "GitExt" (installed through Extensions and Updates...)

I've tried uninstalling, reinstalling, restarting several times with the same behavior.

**Comment by gerhardol** [comment]
Note: the latest version for stand alone is 2.51.01, but the VS installer is still using 2.50.02
(Note that version in GitExtensionsVSIX\source.extension.cs is not updated)

For me it works with either version.
To be clear, it just the "GitExt" entry in the toolbar that is related to GE, the entry in the statusbar is the current directory and opens TeamExplorer:
![image](https://user-images.githubusercontent.com/6248932/38152149-9a17052e-3466-11e8-9031-0210692da576.png)

**Comment by RussKie** [comment]
I have both the toolbar and menus working for me in VS2017 on W10 (I use the toolbar only, but I checked the menus to confirm).

@tranquilChaos @kwints @peterremote1980 Can you run a [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and see whether there is anything useful can be deduced from its logs?

**Comment by tranquilChaos** [comment]
I ran Process Monitor and filtered only to events from devenv.exe. Clear filter, click on GE menu, check PM log. Repeat. Several times returned the exact same dump to PM. It looks like a ReSharper issue before and after, but the latest ReSharper version is throwing errors all over the place, so no surprise. It was consistent in this case though.
[Logfile.zip](https://github.com/gitextensions/gitextensions/files/1865598/Logfile.zip)

**Comment by drewnoakes** [comment]
Are you on the ReSharper EAP channel?

**Comment by RussKie** [comment]
I wouldn't filter on IDE events only, I would want to know if any attempts
are made to invoke GE and see failures, if any.

**Comment by Executus** [comment]
Just installed this (version 2.50.2) and I have the same problem. None of the options in the GitExt menu do anything. None of the buttons on the GitExtensions toolbar do anything. 

If I right click in a code file, the context options 'GitExt : Diff' and 'File history' don't do anything. 

Visual Studio 2017 Enterprise, Windows 10.

**Comment by pcalin** [comment]
I have the same problem. It seems to be related to the folder of gitextensions application. I used one of the 3.0 builds and gitext in VS switched to that version. Once I removed the gitextensions folder VS plugin no longer works. I cannot remember where that folder was to put it back. 

How does the VS extension find gitextensions application folder?

**Comment by pcalin** [comment]
I found the problem.

GitExtensions v3 updated registry "Computer\HKEY_CURRENT_USER\Software\GitExtensions\InstallDir" and once I removed that folder it left the VS extension broken.

I think the portable package should not update install dir...

To fix VS, write the correct value in the registry and all is good again.

Cheers,
Calin

**Comment by vbjay** [comment]
Read the ispirtable config value. Read app.config.

**Comment by GeoffHilton** [comment]
Fresh install of latest GitExtensions as of this writing (first-time user), same problem as others are having. Windows 10, Visual Studio 2017 Enterprise, ReSharper has never been installed on this system.

**Comment by RussKie** [comment]
> Fresh install of latest GitExtensions

How did you install the VSIX? From the installer or from the [VS Market Place](https://marketplace.visualstudio.com/items?itemName=HenkWesthuis.GitExtensions)?

Can you run something like [ProcMon](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) and see if anything is silently failing?

**Comment by shranade** [comment]
After re-installing Git Extension from 
https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00
It worked for me. VS restart was required

**Comment by RussKie** [comment]
Thank you for sharing.

**Comment by alessandro-gentilini** [comment]
@RussKie 
> > Fresh install of latest GitExtensions
> 
> How did you install the VSIX? From the installer or from the [VS Market Place](https://marketplace.visualstudio.com/items?itemName=HenkWesthuis.GitExtensions)?
> 


I have the same problem as described here https://github.com/gitextensions/gitextensions/issues/4708#issuecomment-445504810

I installed GitExtensions from the "Tools - Extensions and updates" menu command in Visual Studio 15.9.2.

As you can see the GitExtesions version is 2.50.2

![vs1](https://user-images.githubusercontent.com/2438459/52572297-ceca4a00-2e17-11e9-9f17-b95e04d67ac7.PNG)

**Comment by alessandro-gentilini** [comment]
OK, to me it is not at all intuitive: once you click on "More Information"
![vs1](https://user-images.githubusercontent.com/2438459/52573372-4b5e2800-2e1a-11e9-810f-0d02cc22d79b.PNG)

you are redirected to the following web pages

![vs3](https://user-images.githubusercontent.com/2438459/52573254-0934e680-2e1a-11e9-907b-6fbf39ab6ca1.PNG)

which tells you that "This plugin requires Git Extensions to be installed".

My suggestion is to write it below the GitExtesions descriptions.

Thank you.

**Comment by gerhardol** [comment]
There should probably be popup if GE is not installed in the expected path

**Comment by alessandro-gentilini** [comment]
@gerhardol I did not see any popup.

**Comment by vbjay** [comment]
He did say should.

**Comment by alessandro-gentilini** [comment]
@vbjay ok, thank you, my English is not so good.

**Comment by RussKie** [comment]
I just tested it by uninstalling GE app, and attempting to invoke it from VS. 
It is working as expected.

![image](https://user-images.githubusercontent.com/4403806/52949249-df5a6180-33cf-11e9-9e4d-2d5e3812f100.png)

Please provide more information.
