### ISSUE TITLE
Revisiting CLS compliance

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4710]
In #1100 a PR was merged that made several assemblies CLS compliant. This introduces several restrictions upon what C# features can be used in such assemblies (and their dependencies).

CLS is "Common Language Specification". In the [words of Jared Par](https://stackoverflow.com/a/570477/24874) from the :

> CLS compliant is a subset of the full language spectrum allowed by the CLR. It restricts it to subsets that are likely available by the majority of languages that target the CLR. This increases, but does not guarantee, that your library can be used by all languages targeting the CLR.

A few times now I've tried to write code that threw up compile errors due to CLS compliance.

Do we need/want this? Is it useful in practice?

**Comment by sharwell** [comment]
I would encourage using `[assembly: CLSCompliant(false)]`. Strict CLS compliance offers some benefits in certain widely-used library scenarios (e.g. Json.NET might want it), but for individual applications only serves to slow down the build.

**Comment by drewnoakes** [comment]
> only serves to slow down the build

I hadn't even considered the impact on build times.

I'll put together a PR.

**Comment by RussKie** [comment]
I think we may now be able to update System.IO.Abstractions to the latest -
#4426
