### ISSUE TITLE
Diff of UTF16-files doesn't show anything

### ISSUE THREAD

**Issue by TymurGubayev** [gitextensions/gitextensions#4715]
Currently the diff view of an utf16 encoded file don't show anything, just
> Binary files a/test.txt and b/test.txt differ

I'd like to actually see what's different.

The simplest possible solution would be something like following.
```
diff -u <(iconv -f utf-16LE -t utf-8 <(git show :./test.txt))  <(iconv -f utf-16LE -t utf-8 ./test.txt)
```

Also, note it's `diff`, not `git diff` -- for some reason, latter wouldn't work (I get `fatal: Invalid path '/proc': No such file or directory`).

- GitExtensions version: 2.51.01
- GIT version: 2.13.0.windows.1
- OS version: Windows 10

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/37916036-d87313c0-30e8-11e8-9201-f91e6bd1b358.png)

Mouse over diff.

**Comment by TymurGubayev** [comment]
@vbjay try it with a utf**16**-encoded file.

**Comment by gerhardol** [comment]
External difftool works

**Comment by gerhardol** [comment]
> I think calling git diff --text

Did not work for me from command line, so it will not work in GE.
There is no magic in git to detect the type of file, so nothing available in GE
Using .gitattributes is the solution here (the "GUI support" in GE could be improved, but that is a different issue).

**Comment by TymurGubayev** [comment]
What do You mean, "did not work from command line"?

This is how it looks like for me:
![image](https://user-images.githubusercontent.com/348150/38032440-ed682192-329d-11e8-9e5b-dcab8754618d.png)

Note, the output from `git diff --text` is in UTF16.

So, my guess is, if I fit this output as is (the actual bytes, not the console representation of them, like `^@` for `0x00`) in the diff-preview of GE and choose "Unicode" as encoding, it would just work.

**Comment by vbjay** [comment]
On Wed, Mar 28, 2018, 9:33 AM Gerhard Olsson <notifications@github.com> w

**Comment by vbjay** [comment]
Are you required to have them utf16?  Would converting them to utf8 be a bad thing?

**Comment by gerhardol** [comment]
> This is how it looks like for me:

Similar for me
Hardcoding --text gives this:

![image](https://user-images.githubusercontent.com/6248932/38060590-a7ef58e4-32eb-11e8-9e16-b280e2a90cd0.png)

So not everything.
Still, there is a need to have this working automatically somehow, otherwise you can as well use an external difftool

I am setting the status to "pull request only", no work is planned but if someone has a good idea, submit a PR.

**Comment by TymurGubayev** [comment]
@gerhardol well, it looks like this because of the line endings: they are single bytes `0x0A` while should be 2 bytes `0x0A 0x00`. That's unfortunate. One way to solve this would be following "hack": just insert a `0x00` after a `0x0A`, if the latter is at an odd position in the bytestream (this is not guaranteed to work in every possible situation).

Proper way would be to do the converting, like in my original post.

**Comment by RussKie** [comment]
Closing, as it is not something we'll be doing.

**Comment by vbjay** [comment]
https://stackoverflow.com/a/21020607. This worked for me. I got a repo with utf 16 flles. 
Attributes file :

*.strings diff=localizablestrings 


Add the following to your ~/.gitconfig file:

[diff "localizablestrings"]
 textconv = "iconv -f utf-16 -t utf-8"

**Comment by vbjay** [comment]
Each copy of the repo has its own config. You could put the config changes in a distributed git config but be careful. Only put what is needed in repo to pass along to all clones. You can have a repo specific config in .git folder called config while repo file is.gitconfig.

**Comment by MxPie200** [comment]
I've been searching for a solution, too.
And I found a really working solution:

1. Create a file named “.gitattributes_global” in C:\Users\<UserName>\
2. Enter the following in the file: ".sql diff=utf16le"
3. Execute the following command in Git Bash:
  `git config --global core.attributesfile “C:/Users/<UserName>/.gitattributes_global”`
4. Define filter:
   `git config --global diff.utf16le.textconv “iconv -f UTF-16LE -t UTF-8”`
