### ISSUE TITLE
Changing the repository while loading messes up the commit tree.

### ISSUE THREAD

**Issue by rebsi** [gitextensions/gitextensions#4725]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Changing the repository while loading is in progress messes up the commit tree.
e.g. duplicated commit entries, additional branches (sometimes detached), ...

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Click on Refresh
1. While "Loading..." is displayed use the repository drop down to switch to another repository. 
(You need a repository that takes at least a few seconds to load. E.g. repository on a network drive.)

I had a copy of the local repository on a network drive and switched between them.
It's a concurrency problem, you may need a few tries.

**What is the expected behavior?**
A consistent view (commit tree) of the selected repository.

**Environment you encounter the issue:**
- GitExtensions version: 2.51.01
- GIT version: 2.15.0.windows.1
- OS version: Win 7 SP1

**Comment by RussKie** [comment]
Please try [RC2](https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00-rc2)

**Comment by RussKie** [comment]
Closing due to age and lack of follow up.

**Comment by rebsi** [comment]
Sorry for the delayed response.

The issues is fixed with RC2.

**Comment by RussKie** [comment]
Thank you
