### ISSUE TITLE
Portable package missing Microsoft.VisualStudio.Threading

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4732]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
GE in portable package (AppVeyor artifact) cannot be executed, exception at startup
Det går inte att läsa in filen eller sammansättningen Microsoft.VisualStudio.Threading, Version=15.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a eller ett av dess beroenden. Det går inte att hitta filen.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Run the package created with Setup/MakePortableArchive.cmd

**What is the expected behavior?**
Normal GE behavior
Similar change as in V

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
Yes before threading change

**Comment by RussKie** [comment]
It must have fallen off the radar in #4730.

/cc: @sharwell @jbialobr
