### ISSUE TITLE
Replacing packages.config with PackageReference 

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4733]
The current `packages.config` approach to listing package dependencies is outdated. Nowadays we could use `PackageReference` instead which comes with a few benefits. From [this page](https://github.com/twsouthwick/NuGetPackageConfigConverter/):

- Transitive dependencies are automatically included - you only need to include the dependencies you need
- install.ps1/uninstal.ps1 is not run so arbitrary code is not run on install and uninstall from untrusted packages
- Doesn't rewrite your project file
- Doesn't add extra files to the project

`PackageReference` would have prevented the error that failed [this build](https://ci.appveyor.com/project/gitextensions/gitextensions/build/3.00.00.2204). In that case a project took an assembly reference with `<HintPath>..\..\..\packages\` which only existed because other projects referenced the package. Once no packages referenced that assembly version any more, the assembly was not available.

I ran that tool over the solution a week ago and it seemed to work, though required a few manual fixes afterwards. I'll try it again now that #4601 is merged.

Does anyone have any experience or thoughts about this?

**Comment by sharwell** [comment]
Can you assign this one to me? I'll check with the project team and either implement the change or explain why it can't be implemented at this time.

**Comment by gerhardol** [comment]
> I personally can't assign you to it, though

You need to be a collaborator to be able to be assigned to
(I would like to see sharwell as an collaborator)

**Comment by sharwell** [comment]
In Roslyn, we assign a collaborator who knows who the "real" assignee is.

**Comment by drewnoakes** [comment]
I thought @RussKie assigned an issue to me before I was a collaborator.

Also think the project would be lucky to have you as a collaborator.

In this instance though I don't think anyone else is going to jump in without saying so on this thread. I'll assign myself for now.

**Comment by gerhardol** [comment]
> The maintainers understand and agree that work on the 2.x branch needs to be in a separate local directory

OK
It should be OK to have a separate worktree for 2.51 (and older 3.0 branches)

**Comment by drewnoakes** [comment]
Nice. How did you do the conversion? Was that tool useful? Might do this on some other solutions.

Is it possible to remove transitive dependencies automatically somehow? When I ran that tool it didn't do so, meaning there was possibility of a manual clean up pass after.

**Comment by sharwell** [comment]
I converted it by hand. I've converted so many projects to the new project system and/or PackageReference it's pretty much autopilot now.

**Comment by RussKie** [comment]
i can live with that
