### ISSUE TITLE
GE skips dashboard if started from a Git repo

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4739]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
This is in reality just a behavior that affectes starting GE from Visual Studio.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The startup code starts latest dir if AppSettings.StartWithRecentWorkingDir is set
If this setting is not set or latest directory do not exist, GE checks the current directory.
This masks issues in the dashboard and makes changes like PR #3693 harder to test

The working directory does not seem to be used in other situations, like when started from the command line

**What is the expected behavior?**
Follow the setting also in Debug

**Environment you encounter the issue:**

- GitExtensions version: all

**Did this work in previous version of GitExtensions (which)?**
same at least since 2012

**Comment by drewnoakes** [comment]
Aside: I usually launch GE from the task bar, right-clicking and choosing a repo. It would be nice to launch it from the command line. Is there an option in the installer that adds it to the PATH? If this sounds like a sensible idea we can create a new issue to track it.

**Comment by gerhardol** [comment]
> Is there an option in the installer that adds it to the PATH? 

The installer has a reputation to be hard to work with
If you work from the command line, it is not so hard to add the path yourself...

**Comment by vbjay** [comment]
It's not that hard. http://wixtoolset.org/documentation/.
http://robmensching.com/blog/posts/2007/11/20/wix-editors/.

https://github.com/gitextensions/gitextensions/blob/2d15fc1a68f999d56f08326e759becb35fdbb1f9/Bin/gitex.cmd

**Comment by RussKie** [comment]
> This masks issues in the dashboard and makes changes like PR #3693 harder to test

Yes, but it would make it harder to test other changes :) So I'm on a fence with this one...
But is possible to pass the current working folder from the command line, so one can set the the working folder for the Debug

**Comment by sharwell** [comment]
Hmm. I may have a way to fix this that works for everyone...
