### ISSUE TITLE
Support 4K Resolution

### ISSUE THREAD

**Issue by MatthiasThoemel** [gitextensions/gitextensions#4741]
**Do you want to request a *feature* or report a *bug*?**
feature (bug)

**What is the current behavior?**
Some Icons are displayed very much too small and some headers of tabs do not show the complete text when using the software with a 4K resolution / monitor

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
correct display also on 4K

**Environment you encounter the issue:**

- GitExtensions version: 2.50.01
- GIT version: 
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**

**Comment by RussKie** [comment]
Unfortunately we can't read your mind or see your screen.
What exactly is the problem?

**Comment by RussKie** [comment]
none of the images come through

**Comment by MatthiasThoemel** [comment]
Von: RussKie <notifications@github.com> 
Gesendet: Samstag, 31. März 2018 08:06
An: gitextensions/gitextensions <gitextensions@noreply.github.com>
Cc: MatthiasThoemel <matthias@thoemel.info>; Author <author@noreply.github.com>
Betreff: Re: [gitextensions/gitextensions] Support 4K Resolution (#4741)

 

none of the images come through

**Comment by RussKie** [comment]
please post your images on github,  they don't come through via emails

**Comment by MatthiasThoemel** [comment]
![icons](https://user-images.githubusercontent.com/30053023/38160616-19886a3c-34c1-11e8-8443-940a81750b7b.jpg)
![tabs](https://user-images.githubusercontent.com/30053023/38160618-19a02afa-34c1-11e8-9ac7-710117dfd974.jpg)

**Comment by MatthiasThoemel** [comment]
done

 

Von: RussKie <notifications@github.com> 
Gesendet: Samstag, 31. März 2018 08:52
An: gitextensions/gitextensions <gitextensions@noreply.github.com>
Cc: MatthiasThoemel <matthias@thoemel.info>; Author <author@noreply.github.com>
Betreff: Re: [gitextensions/gitextensions] Support 4K Resolution (#4741)

 

please post your images on github, they don't come through via emails

**Comment by RussKie** [comment]
Please check #4099 - it has few possible workarounds.

**Comment by drewnoakes** [comment]
We're tracking DPI issues in #4775, so I'll close this in favour of that. Thanks.
