### ISSUE TITLE
Diff on commit not treated as diff to local when possible

### ISSUE THREAD

**Issue by sharwell** [gitextensions/gitextensions#4748]
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**

The diff tool opens with two temporary files in the comparison.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Make a change to a file
2. Commit the change
3. Select the commit in the revisions grid
4. Select the file in the Diff tab
5. Press <kbd>F3</kbd> to open the diff

**What is the expected behavior?**

The diff tool opens with a temporary file in the left view, and the current working directory file on the right.

**Environment you encounter the issue:**

- GitExtensions version: 2.51 and current master branch (b9bddf14d14e9a2b319ca8eb54134d18c2de4c72)
- GIT version: 2.16.2.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**

Yes, it's "always" worked but "recently" stopped. Unfortunately I don't know which specific update triggered it.

**Comment by sharwell** [comment]
I've lost work on multiple occasions because when this issue combines with #4749, the change was a silent breaking change.

**Comment by gerhardol** [comment]
I do not think this has behavior is changed. GE shows the diff first(parent) to the selected (last clicked) revision. So with normal commits, the working directory is not compared.
If you show artificial commands, F3 on Working directory "commit" diffs the change to Commit index which is about what you want.

**Comment by gerhardol** [comment]
I consider the behavor to be as expected. Select the artificial comm Working dir to see the didifference fro the parent to current directory.

There could be a separate shortcut (Shift-F3 ?) to show diff from selected to Working dir.

**Comment by sharwell** [comment]
> There could be a separate shortcut (Shift-F3 ?) to show diff from selected to Working dir.

This is not the command I am attempting to execute. I am attempting to view the changes in the selected commit only, but if the latest changes already match the working directory then I would like it to open the working directory copy instead of creating a temporary copy of the same content.

**Comment by gerhardol** [comment]
> if the latest changes already match the working directory then I would like it to open the working directory copy instead of creating a temporary copy of the same content

I have not seen something like this working, tried with 2.50.02 and 2.49.03, together with TortoiseGitMerge. There are no such options in git-difftool

For this to work "automatically", GE would need to check if the "B" file (in HEAD in this example) is identical to the working directory version, then modify the arguments to difftool. Possible, but will delay the difftool startup and add complexity.

**Comment by jbialobr** [comment]
You both kind of are correct. It is git that has changed the way the difftool command works. 
git v2.10 works as @sharwell says it should
git v2.15 works as the issue describes 
Did not bisecting to find the exact version which introduced the change.

**Comment by m35** [comment]
git for windows v2.14.3 does not exhibit the issue described above.
git for windows v2.15.0 does exhibit the issue.

**Comment by GintasS** [comment]
git version 2.32.0.windows.2
GE 3.5.3 
Seems that F3 works and the expected behavior is here. Closing this one.

**Comment by ZulfinZ** [comment]
Using the following:
Git Extensions 3.5.4.12724
Git 2.33.0.windows.2

The issue still exists
