### ISSUE TITLE
Support tree diff with folder compare in Beyond Compare

### ISSUE THREAD

**Issue by sharwell** [gitextensions/gitextensions#4750]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

N/A

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Select a commit
2. With focus set to the revisions grid, press <kbd>F3</kbd> to open a diff

**What is the expected behavior?**

Beyond Compare 4 opens with a folder diff showing changed files in the commit.

**Environment you encounter the issue:**

- GitExtensions version: 2.51 and current master (b9bddf14d14e9a2b319ca8eb54134d18c2de4c72)
- GIT version: 2.16.2.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**

N/A

**Comment by gerhardol** [comment]
Not sure if this is possible.
When used as a difftool, bc gets the contents of the blobs, not the blob sha I believe
This would mean that to compare git trees, the contents have to be extracted to a local directory before being compared. The diff will have to be done by bc. Is this what you expect?

It could be possible to launch difftool on the difference between first and selected. This would be the same as selecting all in diff tab and pressing F3, the difftool would be opened sequentially

**Comment by sharwell** [comment]
> This would mean that to compare git trees, the contents have to be extracted to a local directory before being compared. The diff will have to be done by bc. Is this what you expect?

Yes, I believe this would be the closest that may actually work.

**Comment by gerhardol** [comment]
Kind of workaround workflow: Archive the revisions to compare to a temp directory, then compare

I set the status to "pull request only" as this is a change/enhancement to how Git works and _I_ do not consider this to be a prioritized feature.
You are in the core team, please remove...

**Comment by RussKie** [comment]
I don't suppose this is an "F3" experience, however this maybe an additional feature to show "folder diff".
Certainly a backlog item but not a top priority.

**Comment by GintasS** [comment]
Abandoning this because of the age and lack of discussion.

**Comment by gerhardol** [comment]
Diff is implemented in 3.2 or s, multiple difftools in 3.5
(all difftools do not support dir diff, GE is not aware which that does)

![Uploading image.png…]()
