### ISSUE TITLE
Remove support for VS addin prior to .vsix

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4752]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
GE supports building VS addin. In 2015/2017 the .vsix format is used primarily, but older MSVS can only use the old plugins.

The VS addins are ditributed in the installer.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Drop support for addin format (remove the GitPlugin project, not related to the GE plugins).

Considered but dropping from the issue:
The .vsix build should be published on AppVeyor and for GitHub releases too, currently it is only updated occasionally to Microsoft for users that do not build the vsix plugin explicitly. (Current version is 2.50.02)

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
unknown status for the addin

**Comment by sharwell** [comment]
> In 2015/2017 the .vsix format is used primarily, but older MSVS can only use the old plugins.

The VSIX can be modified to work with 2012+.

**Comment by gerhardol** [comment]
I have added the vsix as an artifact for AppVeyor in my private build, but the size differs between the local build (220KB) and in AppVeyor (15MB). The AppVeyor build seem to include the complete GE binaries which should not be necessary as the VSIX uses the GE installation.
Hints?

**Comment by RussKie** [comment]
Personally I don't see a great value publishing the VSIX for every build. It isn't changed very often.

**Comment by sharwell** [comment]
@gerhardol my vsix publishing update PR fixes it

**Comment by RussKie** [comment]
> The VSIX can be modified to work with 2012+ (if necessary).

👍 
I don't see any compelling reason to support anything older than VS2015.

**Comment by RussKie** [comment]
Bugger... Enjoy your break from us 😄
