### ISSUE TITLE
Commit button hidden

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4754]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
"Commit" button is hidden and not accessible

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Run the current master @ b9bddf14d14e9a2b319ca8eb54134d18c2de4c72

![image](https://user-images.githubusercontent.com/4403806/38182908-f9aedee2-367f-11e8-9f32-1e0e3cfd2aad.png)

**What is the expected behavior?**
"Commit" button is available

**Environment you encounter the issue:**
Run the current master @ b9bddf14d14e9a2b319ca8eb54134d18c2de4c72

**Comment by RussKie** [comment]
It looks like the regression occurred in #4662.
6c3185726cf29e95f5dfdfddee4a0f19c2534feb shows the "Commit" button as expected, in 64d84a7f588a8761f64bd5a0025727f8c3acfd10 the button is missing...

**Comment by drewnoakes** [comment]
Reproduced. Will fix asap.

Back when I was looking at #4501 I noticed that adding asynchrony somewhere caused this button to disappear. I can't think what in the `ArgumentBuilder` should cause this, but I'll find out and report back.

I'm glad the PR wasn't completely squashed as bisecting will narrow down the problem to a smaller changeset.

**Comment by drewnoakes** [comment]
Fixed in #4758.
