### ISSUE TITLE
Unsafe code

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4769]
Is there a reason we cannot use `unsafe` code in GitExtensions?

There is a scenario I am optimising where I believe `fixed` and some pointer arithmetic will be faster than any alternative API available.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/unsafe-code

Specifically, I would like to enable unsafe code on at least one project (`GitCommands`).

**Comment by RussKie** [comment]
I have no problems with unsafe code, if it is used sparingly.

**Comment by jbialobr** [comment]
How much faster will it be?

**Comment by drewnoakes** [comment]
> if it is used sparingly

Agreed.

> How much faster will it be?

I will report back with numbers once I have them. I didn't want to progress with the work if there was some blocker against unsafe code.

It can be much faster if it eliminates bounds checking, though the JIT is pretty good at that for normal loops.

I've spent some time looking at how data gets pumped into the revision grid. There's a lot of opportunity here and I'm already seeing some good gains, especially in the reduction of memory allocations.

This is the command that pulls data for the revision grid:

```
$ time git log -z  --pretty=format:"<(__BEGIN_COMMIT__)>%n%H%n%P%n%T%n%aN%n%aE%n%at%ncN%n%cE%n%ct%n%e%x00%s%x00%B%x00"  --d
ate-order --all --boundary --not --glob=notes --not  --max-count="100000"  | wc
 129065  313353 4223628

real    0m0.334s
user    0m0.125s
sys     0m0.076s
```

That's 4,223,628 bytes to scan through. I want to find out if unsafe code can help here.

Pump them to `wc` like this and the job is done in 0.3s. In GE I see numbers closer to 1.4s.

I've tweaked the format string which brings the number of bytes down by about 1MB. The parsing code now does a lot less allocation of temp strings too.

There are lots of common strings, such as author/committer name/email & encoding. Pooling them makes sense if efficient to do so. For the GE repo this cuts 98.7% of such strings in memory! But it comes with a CPU cost which I would like to try and bring down, probably through some unsafe code too.

Anyway I'll put together a PR with these changes soon. Hopefully it should make `FormBrowse` feel snappier.

**Comment by sharwell** [comment]
@drewnoakes C# 7.2 added a bunch of features in support of your goal without using `unsafe`. C# 7.3 will add several more. I'll wait to see what the PR looks like and then we can rewrite it if appropriate to use the new features.

**Comment by drewnoakes** [comment]
@sharwell thanks, yes I've only had a chance to play with these new toys a few times so I'll appreciate your review. I've enjoyed seeing their application in some of the dotnet org repos. Powerful and safe. Still, it's good to know I can bust out `unsafe` if need be.
