### ISSUE TITLE
Tab control header is too small under high DPI

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4777]
When running under high DPI, tab control headers are squashed and hard to see/use.

They should look the same, regardless of DPI/scaling setting.

Icons in tab control buttons appear too small as well.

It's likely that we fix all of these in one go.

- GitExtensions version: `master`
- OS version: Windows 10
- Scaling: 200%

![image](https://user-images.githubusercontent.com/350947/38333646-1df636d8-3851-11e8-9cd5-98b5376eb37b.png)

![image](https://user-images.githubusercontent.com/350947/38333778-76608cc4-3851-11e8-8cae-f6ec2f6b869c.png)

![image](https://user-images.githubusercontent.com/350947/38333711-4317708a-3851-11e8-9b3b-a51c67a871ec.png)

![image](https://user-images.githubusercontent.com/350947/38333804-89416fac-3851-11e8-9baa-2c05c5abeea7.png)

![image](https://user-images.githubusercontent.com/350947/38333848-a7c4296a-3851-11e8-804a-1f547db14637.png)

**Comment by RussKie** [comment]
Push dialog:
![image](https://user-images.githubusercontent.com/4403806/38675670-d06213f0-3e9b-11e8-90dc-adc82820cbfe.png)

**Comment by drewnoakes** [comment]
Going to close this as it's covered for any form that uses `AdjustForDpiScaling`.
