### ISSUE TITLE
Icons in buttons are too small under high DPI 

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4778]
Under high DPI scaling, images/icons in buttons appear too small.

See https://stackoverflow.com/a/26907311/24874 for a possible way to fix this.

- GitExtensions version: `master`
- OS version: Windows 10

100% scaling

![image](https://user-images.githubusercontent.com/350947/38334143-8157e1c6-3852-11e8-913a-1a59d996fbd5.png)

150% scaling

![image](https://user-images.githubusercontent.com/350947/38334236-b12df890-3852-11e8-8ade-50920951fd3f.png)

---

200% scaling

![image](https://user-images.githubusercontent.com/350947/38335277-bb2312b0-3855-11e8-843b-b18651aa482f.png)

**Comment by drewnoakes** [comment]
Played with this a bit and have something that works reasonably well. Will get a PR together soon.

![image](https://user-images.githubusercontent.com/350947/38338818-1e8807d6-3863-11e8-8607-067095b0134e.png)

**Comment by RussKie** [comment]
from what I've read about multiple resolutions and scales - it looks like
having multiple images in different sizes is the right solution.
perhaps we should consider this avenue.

**Comment by drewnoakes** [comment]
Adding 32x32 or higher images would definitely look better on high-DPI.

For now I'm happy to make the icons the right size, partly because that "unbreaks" the screens, and partly because I assume finding higher resolution images will be involved. Are there some ready to go?

**Comment by RussKie** [comment]
Alas, no ready to go images. I've been looking around for some icon collection we could purchase, however I haven't found one I feel completely happy with.

In the past we've had a proposal from @seralexeev to reuse VS 2015 icon pack - #3343, however it got knocked back then. My personal view that this proposal has merits and I still keep it in mind.
VS 2017 icon pack is available now too (https://github.com/gitextensions/gitextensions/pull/4499#discussion_r172039972). Though IIRC it has only 16x16 png and SVGs. 
I briefly looked at Winforms SVG-support and it seemed almost non-existent...

So back to the topic - let's scale them until we have a better solution.

**Comment by drewnoakes** [comment]
> I briefly looked at Winforms SVG-support and it seemed almost non-existent...

SVG works well on high DPI at small sizes, but at 96 DPI they tend to look blurry without manual tweaks. The pixel grid is just too coarse. Good icon sets with 16x16px sizes tend to be hand edited.

Back when WPF came out I excitedly tried out using path data for icons and discovered they looked terrible when reduced to icon sizes.
