### ISSUE TITLE
File history/blame is blank for all files

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4793]
**Do you want to request a *feature* or report a *bug*?**
regression in master

**What is the current behavior?**
File history/blame is blank for all files

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Select any file either from the "File tree" or from "Diff" and show the history or blame.
The result is:
![image](https://user-images.githubusercontent.com/4403806/38421549-da721cc4-39ea-11e8-8c0b-75d47dd5653b.png)

It seems that certain commands aren't being run
![image](https://user-images.githubusercontent.com/4403806/38421696-5ec58f74-39eb-11e8-8eb6-58bfd6c9b8c5.png)

**What is the expected behavior?**
File history/blame are shown
![image](https://user-images.githubusercontent.com/4403806/38421595-fda92f0c-39ea-11e8-924e-14ee3188b951.png)

**Environment you encounter the issue:**
master @ 40ae2ea38b92f64f71ed88fa15aab680d1f121a9

**Comment by RussKie** [comment]
It works correctly in 22709a79dc2f63aeed67870c2f2dae31b9cceaad and doesn't in 64d84a7f588a8761f64bd5a0025727f8c3acfd10, looks like the problem have been introduced in #4662.

**Comment by drewnoakes** [comment]
Bug was introduced in 64bf988e579dff2d4250bb2465da1cb4127e92f5 when we changed `UnescapeOctalCodePoints` to promote `null` to `""`. I've reverted that change in #4794 and all is well again.
