### ISSUE TITLE
CodeCov Report always includes GitModuleTestHelper.cs

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4802]
I was not able to find an [open](https://github.com/gitextensions/gitextensions/issues?q=is%3Aopen) or [closed](https://github.com/gitextensions/gitextensions/issues?q=is%3Aclosed) issue matching what I'm seeing
Yes 

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
CodeCov report for pull requests always list UnitTests/CommonTestUtils/GitModuleTestHelper.cs as changed.
This is regardless if code has been removed #4799 a README changed #4786 or other files being changed #4796 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Only see relevant files in the summary
Low oriority...

**Environment you encounter the issue:**

GitHub pull request presentation

**Did this work in previous version of GitExtensions (which)?**
No

**Comment by sharwell** [comment]
It's often impossible to completely eliminate churn from code coverage reports (e.g. uncontrollable race conditions in concurrent code).

For lines that frequently change, this is typically an indication that the class is indirectly covered by tests, and not always covered in the same manner. Additional tests targeting the impacted situations will typically resolve this by ensuring the code is always covered during test runs.
