### ISSUE TITLE
Error on VS add on installation. "Cannot find setup engine instance"

### ISSUE THREAD

**Issue by IgnacioJPM** [gitextensions/gitextensions#4811]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
GE Plugin is not working on VS community after VS update to last version.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Update VS community, try to install GE from "Extensions and Update" 
![image](https://user-images.githubusercontent.com/33660466/38507956-4ca2e64c-3bf4-11e8-9093-b609930995c4.png)

**What is the expected behavior?**
Correct install

**Environment you encounter the issue:**

- GitExtensions version: Latest
- GIT version: 
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
This worked with previous VS version.

**Comment by gerhardol** [comment]
The GE addin is not supported in VS2017 (it is included in the installer for VS earlier than 2015).
The VSIX is in the Microsoft gallery (not updated from 2.50 version).

Which version is it you are using,, have you built it from master?
What VS plugin are you installing and how?

**Comment by RussKie** [comment]
Closing due to lack of follow up
