### ISSUE TITLE
Remote repo dialog does not appear when main window on second screen.

### ISSUE THREAD

**Issue by VinSgro** [gitextensions/gitextensions#4812]
**Do you want to request a *feature* or report a *bug*?**

Report bug.

**What is the current behavior?**

I have a Lenovo laptop with an external monitor attached.  I am using the monitor in "extended" mode where the monitor is *not* a mirror of the laptop screen, but an independent extension of the desktop.

Attempting to open the "remote repositories" when the main application window is open on the external monitor causes gitextensions to hang.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

0) Set up a laptop with an external monitor in extended desktop mode.
1) Open Gitextensions
2) If necessary, drag the application window to the external monitor.
3) Open an existing repo.
4) Select "Repository... -> Remote repositories...".

Git Extensions hangs.

**What is the expected behavior?**

The remote repository dialog should appear no matter the screen on which gitextensions resides.

The dialog does open if I open the dialog with the main git extensions window on the display with the primary desktop.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.01
- GIT version: 2.14.1.windows.1
- OS version: Windows 10 Pro

**Did this work in previous version of GitExtensions (which)?**

It did. I can't be sure of the version but it was 2.x.y where 40 < x < 50.

Some additional information:

The problem seemed to progress.  That is, the first time I used the repositories dialog, it appeared and I was able to perform and complete an update. After updating, I attempted a "prune" operation and that dialog did not appear at all with the application freezing. From then on, I was not able to make even the initial remote repositories dialog appear without freezing the application.

This version seems to have gitbash embedded in it. That is, the lower pane has the console tab and the command exec dialogs appear to have a console window in them that shows the console output as the command is executed.  In the previous installation, there was no console tab and the exec dialogs seemed to have a simple text area where the console output appeared.

After the remote update that succeeded, I followed the prompt in the console window which read "hit enter or esc to ...".  I believe I clicked in the dialog's console area and hit enter rather than dismissing the dialog by clicking on the close button.

**Comment by RussKie** [comment]
I'm pretty sure the dialog is shown but it is off the screen.
Try Win+Left/Right arrow to get the dialog to the main screen.

**Comment by drewnoakes** [comment]
Another weird combo that can help if Win+Left/Right doesn't help.

- <kbd>Alt</kbd>+<kbd>Space</kbd>
- <kbd>M</kbd>
- Press any arrow key once
- Move the mouse to drag the window

Don't click at any point through this.

---

GE remembers window positions. Is it possible there's a bug in that logic that restores windows into invisible locations?

**Comment by VinSgro** [comment]
This is exactly what is happening.  I was not aware of the Win+Left/Right
combination so I’ll try that. But I did something else that helped me
understand what is going on.

I had set the external display to be diagonally up and to the left of my
laptop screen.  (That’s where it is, after all.)

When I experienced the problem, I changed the screen setting so that the
external display was immediately to the left.  When the displays
reconfigured, the hidden dialog appeared.

The problem with the diagonal configuration is that the universal desktop
space is non-rectangular.  There are large areas of the global desktop
rectangle that are not mapped to a display.  (If you do a print screen
grab, these areas appear grey outside that actual displayed areas.)

Should these dialogs be appearing center of their parent window rather than
walking all over (and off) the desktop?  Is there some reason it is the way
it is? Even when things are working,  I frequently need so move the mouse
large distances to interact with dialogs that pop up on distant displays.

-Vince

**Comment by nwayve** [comment]
I'm also running into this bug.  When I open the Commit dialog, it is always opening below and to the right of the gitextensions window, so if I have gitextensions on my right most monitor, the dialog always opens off-screen and I have to do the `alt+m & spacebar` trick to get it back on screen.

I've tried uninstalling and reinstalling gitextensions, changing monitor resolutions, repositioning the monitor positions, and toggled the settings `Git Extensions > Appearance > General > Auto scale user interface when high DPI is used` setting.  On or off, that made no difference.  Nothing I do seems to change this odd behavior.

**Comment by nwayve** [comment]
It appears that gitextensions only wants to open dialogs on whichever display is set as the "main display".  I have two external monitors and my laptop monitor with the two external monitors being relatively to the top left and top right of my "main display" (laptop screen).  If the main gitextensions isn't on the main display, it opens it at the same y-coordinate but at the top or bottom most x-coordinate on the main display, and as VinSgro pointed out, if the relative position of the external display overhangs the main display, the new window opens up off screen.

If the external monitor is marked as the main display, then things work as expected.

**Comment by drewnoakes** [comment]
@Shilohe I don't think any of the maintainers see this issue locally. It sounds like you're well set up to reproduce it. Could you debug it and submit a pull request?

**Comment by Shilohe** [comment]
@drewnoakes I'll try but honestly I've never (so embarrassed ;) ) actually downloaded a project from GitHub (at least not a big one, maybe something small ) and debugged it. I'll have to make sure I have the tools to do it... I'm assuming that it wasn't written in c# and developed in VS 2017, but I might be wrong about that. I'll give it a try but it might be bigger bite than I'm prepared to chew right now.

**Comment by Shilohe** [comment]
@drewnoakes  well guess I was wrong about that ...it looks to be c# piece of software and developed in visual studio, at least from my quick look at it... I guess to me it looked so different from other native windows apps that I thought it must have been written in some other language or framework. Guess I should get out of my comfort zone more often.

**Comment by drewnoakes** [comment]
@Shilohe never a better time to start than right now. If you hit any barriers, speak up and someone will do their best to help.

**Comment by RussKie** [comment]
I believe this should be fixed in [RC2](https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00-rc2)
