### ISSUE TITLE
Lingering git processes on rapid refresh

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4813]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Many `git.exe` processes lingering on the computer as children of `GitExtensions.exe`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Press the 'refresh' button in the browse form about once a second, for five to ten seconds.

![image](https://user-images.githubusercontent.com/350947/38529610-c4b8388a-3c5d-11e8-9ef7-ae823fc80f99.png)

![image](https://user-images.githubusercontent.com/350947/38529613-cb52a5fe-3c5d-11e8-9604-667dafa54a27.png)

**What is the expected behavior?**
These processes should not linger.

**Environment you encounter the issue:**

- GitExtensions version: `master` and `2.51.01`
- GIT version: 2.16.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
I don't know.

**Comment by NickPolyder** [comment]
Hello @drewnoakes,
I don't know if you have found the exact location of the bug. 
I was able to find it and fix it. 
But i think it would be better to put more thought on this because i can imagine there will be other incidents in other parts of code.

Thanks,

**Comment by RussKie** [comment]
There is a plan to centralise all git processing in a single component so there wouldn't be uncontrolled git spawning.
There is a discussion related to the subject in #4643

**Comment by drewnoakes** [comment]
Hi Nick,

Yes, the process needs to be disposed in the case of cancellation. There are few cases of this issue. I have the good in a branch which I'll file as a PR soon, along with other changes.

As @RussKie says I'm working towards consolidating all git process execution.

**Comment by NickPolyder** [comment]
@drewnoakes  Cool.
i will check the issue given by @RussKie i think i will have a lot of things to learn from this refactoring process and the steps taken towards to a better structure.

Thanks

**Comment by RussKie** [comment]
Nick, it is very exciting time for all of us - the project is again alive and kicking, there is a lot of new work and refactors happening.
v3 is looking to be a very exciting release

**Comment by NickPolyder** [comment]
@RussKie that's great to hear. I'm looking forward to learn and contribute more to this project.

**Comment by drewnoakes** [comment]
> I have the fix in a branch which I'll file as a PR soon

That PR is #4988.
