### ISSUE TITLE
Errors loading TeamFoundation assemblies

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4817]
**What is the current behavior?**

When GE (master) is launched, the output window receives around 10,000 lines due assembly binding errors. As the program continues, more and more binding failures are logged here.

Some of these come from `GitUIPluginInterfaces.ManagedExtensibility.GetExports<...>()` overloads.

These continue to be logged as the program continues.

This makes using `Trace.WriteLine` as a debugging aid practically impossible.

It might also suggest a performance problem, though I haven't measured this. 

Here's an example of what is logged:

```text
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.TeamFoundation.Common, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.TeamFoundation.Common, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.TeamFoundation.Common, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Users/Drew/Dev/tools/gitextensions/GitExtensions/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : Microsoft.TeamFoundation.Build.Client, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\Drew\Dev\tools\gitextensions\GitExtensions\bin\Debug\GitExtensions.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.TeamFoundation.Common, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: Attempting download of new URL file:///C:/Users/Drew/Dev/tools/gitextensions/GitExtensions/bin/Debug/Microsoft.TeamFoundation.Common.DLL.
LOG: Attempting download of new URL file:///C:/Users/Drew/Dev/tools/gitextensions/GitExtensions/bin/Debug/Microsoft.TeamFoundation.Common/Microsoft.TeamFoundation.Common.DLL.
LOG: Attempting download of new URL file:///C:/Users/Drew/Dev/tools/gitextensions/GitExtensions/bin/Debug/plugins/Microsoft.TeamFoundation.Common.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

Assemblies mentioned include `Microsoft.TeamFoundation.Common`, `System.Net.Http.Formatting`, `Microsoft.IdentityModel.Clients.ActiveDirectory`, `Microsoft.VisualStudio.Services.Common` and others.

`GitUIPluginInterfaces.ManagedExtensibility.GetExports<T,TMetadataView>()` also logs many `ReflectionTypeLoadException`s while the program is executing. Refreshing `FormBrowse` will trigger this, for example.

**What is the expected behavior?**

The trace output is free from error reports during normal program execution.

**Environment you encounter the issue:**

- GitExtensions version: `master`
- GIT version: 2.16.2
- OS version: Windows 10

I've verified binding logs are disabled via fuslogvw.

**Did this work in previous version of GitExtensions (which)?**

Not sure.

**Comment by pmiossec** [comment]
The  best fix to solve this problem (and the other one that will appear on this plug-in) is to rewrite it using the rest api now provided by tfs... (and no more use the tfs assemblies)

**Comment by RussKie** [comment]
Totally support the notion.
I don't use or have access to tfs though

On 17 Apr 2018 9:53 pm, "Philippe Miossec" <notifications@github.com> wrote:

The best fix to solve this problem (and the other one that will appear on
this plug-in) is to rewrite it using the rest api now provided by tfs...
(and no more use the tfs assemblies)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/4817#issuecomment-381963966>,
or mute the thread
