### ISSUE TITLE
Per-monitor DPI awareness

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4822]
The current DPI awareness setting assumes a single DPI across all monitors. This is often not the case, and we can add support for this such that the application rescales itself as it moves across desktops.

First step is to use `<dpiAware>true/PM</dpiAware>` in `app.manifest`.

The larger task is determining how to trigger re-laying out the various tweaks we have as DPI changes.

And of course we need lots of testing.

**Comment by BenjaminCo** [comment]
I have this problem, here are some screenshots:

Capture on main monitor 150% zoom:
<img width="690" alt="CaptureMainMonitor150percentZoom" src="https://user-images.githubusercontent.com/9527731/59512156-6c15b780-8eb8-11e9-90ba-8b825dea819d.PNG">

Capture on second monitor 100% zoom:
<img width="460" alt="CaptureSecondMonitor100percentZoom" src="https://user-images.githubusercontent.com/9527731/59512155-6c15b780-8eb8-11e9-947c-9b74148643aa.PNG">

As you can see the second one is blurred.

**Comment by RussKie** [comment]
I don't believe PMA is supported in 4.6.x. It came in 4.7, and i think it
got further enhanced in 4.8.

**Comment by BenjaminCo** [comment]
This is my settings:
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.15063.0
- .NET Framework 4.7.3362.0
- DPI 144dpi (150% scaling)

**Comment by RussKie** [comment]
The app is still compiled against NET 4.6.1 though.
4.7 and 4.8 have quirks that enable PMA, but you'd have to search for them.

**Comment by drauch** [comment]
Please fix this :-) Is it really necessary to stay on .NET 4.6.1?

**Comment by RussKie** [comment]
No, it isn't. 
And we are moving to .NET Core https://github.com/gitextensions/gitextensions/pull/7162

**Comment by RussKie** [comment]
However whilst there are some advancements in the area, full PMA HDPI support is currently slated for .NET 5.0

**Comment by RussKie** [comment]
Windows Forms doesn't have full PMA support.

**Comment by PeterMinin** [comment]
Windows Forms added full support in .NET Framework 4.7. And a quick search didn't show that it was ever removed in .NET 5.0+. So I guess it's available now?
https://learn.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8

**Comment by RussKie** [comment]
No, unfortunately Windows Forms _still_ doesn't have full PMv2 support even in .NET 7. Even some of the SystemAware scenarios are still incomplete.
For more information you can monitor https://github.com/dotnet/winforms/issues?q=is%3Aissue+label%3A%22area%3A+HDPI+PMv2%22 and https://github.com/dotnet/winforms/issues?q=is%3Aissue+label%3A%22area%3A+HDPI+SA%22

**Comment by Mart-Bogdan** [comment]
Links provided are broken.
Looks like correct links are:
* https://github.com/dotnet/winforms/issues?q=is%3Aissue%20label%3Aarea-HDPI-PMv2
* https://github.com/dotnet/winforms/issues?q=is%3Aissue%20label%3Aarea-HDPI-SA
* https://github.com/dotnet/winforms/issues?q=is%3Aissue%20label%3Aarea-HDPI

And I think this should be reopened, as it is still borked.
