### ISSUE TITLE
BitBucket plugin always "Your repository is not hosted in Bitbucket."

### ISSUE THREAD

**Issue by kwaclaw** [gitextensions/gitextensions#4836]
Calling the Bitbucket Server plugin always returns "Your repository is not hosted in Bitbucket." for my Bitbucket repos.

From running GitExtensions in the debugger it looks like the BitbucketHttpRegex regular expression
( see file ..Plugins\Bitbucket\Settings.cs) does not recognize my remote repository URL as a Bitbucket Url.

The Url is of the form https://bitbucket.org/myaccount/myrepo

- GitExtensions version: 2.51.01
- GIT version:  2.16.1.windows.4
- OS version:  Windows 20 Pro

**Comment by gerhardol** [comment]
The plugin is for Bickbucket Server (previously called Stash), private installation hosted at enterprises
Atlassian has two separate products with similar names but completely different APIs
