### ISSUE TITLE
Appveyor: Build Artifacts Missing?

### ISSUE THREAD

**Issue by CDAGaming** [gitextensions/gitextensions#4838]
**Do you want to request a *feature* or report a *bug*?** Reporting a Bug

**What is the current behavior?** Appveyor isn't uploading any Build Artifacts

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Not Applicable besides just going to the Appveyor Artifacts page.

**What is the expected behavior?** Appveyor usually uploads a Portable ZIP Build Artifact

**Environment you encounter the issue:** Not Applicable

- GitExtensions version: Master - Latest (Appveyor)
- GIT version: N/A
- OS version: N/A

**Did this work in previous version of GitExtensions (which)?** Appveyor Artifacts has shown in previous Builds

**Comment by RussKie** [comment]
Indeed... https://ci.appveyor.com/project/gitextensions/gitextensions/build/3.00.00.2451#L440

**Comment by RussKie** [comment]
Fixed, thank you for alerting
