### ISSUE TITLE
Diff inverted for stash created with untracked files

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4849]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/350947/38836524-5e465b40-41c6-11e8-9906-85e8e754d901.png)

I created a stash using `--include-untracked` which ends up with three parents. Clicking the stash shows a diff where existing files are considered new, and the stashed untracked files appear deleted (in this case the `Benchmarks` folder). i.e. they are in reversed states.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

```
$ touch deleteme
$ git stash -u
```

Then click on the stash node.

**What is the expected behavior?**

The diff should show something sensible.

**Environment you encounter the issue:**

- GitExtensions version: 25.1.01
- GIT version: 2.16.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions?**

I don't know.

This issue might be related to #2851.

**Comment by gerhardol** [comment]
The diff is correct
The new files are not included in the Untracked "parent" and the untracked are not in the stash "commit"

This is a visual presentation problem, there are possibilities for improvements
The behavior when selecting the untracked itself is as expected, you see the new files.
Similar with changes from commit and index to the stash. For untracked, the diff is meaningless, it would have been better to not show any diff at all or the diff seen for untracked, with the added files directly.
But this would have introduced special handling in GE, not following Git standard behavior
Similar with having Untracked as a child to the stash.

One thing could be to implement collapsing in the diff viewer and hide the third parent by default (stash is not detected right now as a special commit. I have played around with placing the 'stash list' output in the revision tree as normal commits but too many hacks are needed, compare to artificial commits).
![image](https://user-images.githubusercontent.com/6248932/38838738-f21dac18-41d7-11e8-9b98-f2ddfa8b9163.png)

**Comment by gerhardol** [comment]
Closing, as the behavior is correct
