### ISSUE TITLE
Init wrong folder

### ISSUE THREAD

**Issue by lvhkhanh** [gitextensions/gitextensions#4855]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**
![image](https://user-images.githubusercontent.com/919300/38880460-fcc8100a-428f-11e8-9a66-8414e3c7e9a6.png)

**Comment by drewnoakes** [comment]
Please explain more about what you did to get into this state, and what you expected to happen differently.

**Comment by lvhkhanh** [comment]
When I right click on c:\dev\20180417 select GitExt clone, I want Destination will be the current folder c:\dev\20180417 not c:\dev\

**Comment by RussKie** [comment]
I suspect this is caused by #4406

/cc: @loop-evgeny

**Comment by RussKie** [comment]
Could you please test and confirm the fix: https://ci.appveyor.com/api/buildjobs/shtkdcpl14ae6gsr/artifacts/GitExtensions-2.51.01.2532-Mono.zip

**Comment by asherber** [comment]
Is there a Setup package so this can be installed and tested?

**Comment by RussKie** [comment]
Please scroll up

**Comment by asherber** [comment]
I see the Mono zip file, but not a setup.msi. Can I just copy files from the zip into my installation directory?

**Comment by vbjay** [comment]
You can even extract the zip and run it.

**Comment by vbjay** [comment]
Your options are

Extract the zip and test and then respond with the results.

Build from source and test.

You can make the setup on your own by following the build instructions
linked in the readme.

**Comment by RussKie** [comment]
We only ship msi for official releases. Test builds are available in a form
of portable builds as zip archives. V2.5x can be run on both Windows and
Linux under Mono; v3 builds only work on Windows.
Portable builds can be unzipped to any folder and run from there. You can
replace files in your official installation folder, but I would caution
against it.

**Comment by asherber** [comment]
Since the behavior described here occurs when launching GitExt from an Explorer context menu, I don't see how the fix can be tested without properly installing GitExt.

**Comment by gerhardol** [comment]
Put the ffiles in the .zip wher you have installedGit.
The Explorer extension is just a wrapper, the change was done in core GE

**Comment by RussKie** [comment]
Apologies, it was very late when I replied.
When I did my tests, I renamed `C:\Program Files (x86)\GitExtensions` folder, then extracted the portable into the `C:\Program Files (x86)\GitExtensions` folder and tested it.
Once I concluded my tests, I returned everything back.

**Comment by asherber** [comment]
I can confirm that the fix works as expected.
