### ISSUE TITLE
Remove embedded NuGet.exe from the repository

### ISSUE THREAD

**Issue by sharwell** [gitextensions/gitextensions#4857]
The repository currently includes a copy of the NuGet executable. This should be removed, with one of the following approaches used instead:

1. Modify the build script to download NuGet on demand
1. Use MSBuild instead
1. Use the dotnet tool instead

The first option is likely the most compatible with the existing repository structure and scripts.

**Comment by RussKie** [comment]
NuGet was removed in https://github.com/gitextensions/gitextensions/pull/7649
