### ISSUE TITLE
Open GE from GE context menu opens empty Browse

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#4860]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Open GE for a submodule from GE will not open the submodule repo.
Open can be done by double clicking in Tree window or menu in Diff (it is a bug that double clicking opens File History when double clicking in Diff though).

![image](https://user-images.githubusercontent.com/6248932/38959964-ec8078bc-4362-11e8-82a2-808362a46a37.png)
![image](https://user-images.githubusercontent.com/6248932/38959974-f6e9caf6-4362-11e8-986b-12105a2c3999.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/6248932/38959989-07caaf8e-4363-11e8-984b-0ffb1a4ab5c3.png)

**Environment you encounter the issue:**

- GitExtensions version: master, maybe #3693 was the cause
- GIT version: n/a
- OS version: win10

**Did this work in previous version of GitExtensions (which)?**
all before some week(s) ago

**Comment by RussKie** [comment]
the dashboard is not working in the current master.
i am currently working on getting on repository history management refactor
and then i will fix up the dashboard

**Comment by RussKie** [comment]
Thanks for pointing, indeed there is a regression.

**Comment by RussKie** [comment]
Bisecting I arrived at #4740... 🤣

**Comment by gerhardol** [comment]
I would have started looking at #4860 myself!
After your comment and a computer breakdown I have not had much time to loook into this. 
It is mine regardless.

**Comment by RussKie** [comment]
The code in `Program.cs` is confusing at best. Arguments checking and parsing is scattered across several files... No wonder we had a number of changes and reverts.
