### ISSUE TITLE
CommitPickerSmallControl broken under high DPI

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#4862]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Under high DPI settings any form's layout that uses the CommitPickerSmallControl is broken, e.g FormCreateBranch and FormCreateTag forms. Specifically the revision text box is too small to be usable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Try to create a tag with UI scaling above 100%.

**What is the expected behavior?**

The form lays out correctly and is usable.

**Environment you encounter the issue:**

- GitExtensions version: `master`
- OS version: Windows 10

![image](https://user-images.githubusercontent.com/4403806/39360633-5e15ea9c-4a62-11e8-8b9c-4246df799d7f.png)

![image](https://user-images.githubusercontent.com/350947/39059310-0e476934-44b6-11e8-9354-6716b2f71954.png)

**Comment by RussKie** [comment]
in master @ a8dd6cf99a6615173e31eaf09ac1c22bc8ab1669 at 150% scale it looks fine:

![image](https://user-images.githubusercontent.com/4403806/39360115-3e5eb654-4a60-11e8-9e72-ad27eeeb8bbf.png)
