### ISSUE TITLE
"The mergetool is not correctly configured" error while Araxis chosen as merge/diff tool

### ISSUE THREAD

**Issue by evil-shrike** [gitextensions/gitextensions#4864]
Click on "!There are unresolved merge conflicts" on status bar shows the error:
```
The mergetool is not correctly configured. Please go to settings and configure the mergetool!
```

Git config:
![image](https://user-images.githubusercontent.com/1203230/39064774-4fd79276-44d8-11e8-847f-0992788e6e14.png)

Windows 10
GitExtensions v2.51.01
Git: 2.13.3.windows.1

`.gitconfig`:
```
[merge]
	tool = araxis
[diff]
	tool = araxis
	guitool = araxis
[mergetool "araxis"]
	path = C:/Program Files/Araxis/Araxis Merge/Compare.exe
[difftool "araxis"]
	path = C:/Program Files/Araxis/Araxis Merge/Compare.exe
```

If I run `git mergetool` in that repository then git open Araxis Merge as expected. So the problem is only with GitExtensions (not git).

**Comment by DCFerg** [comment]
It does the same with Windows 7.

See here...
https://stackoverflow.com/questions/22168243/how-to-configure-araxis-merge-with-git-extensions

After filling in the Mergetool command by hand, Araxis tried to run. My trial license is expired so I can't verify the actual command options but Git Ext did execute Araxis at that point.

**Comment by werwolfby** [comment]
I'm using CodeCompare and it works when i run from cmd:
```cmd
git mergetool --tool=codecompare
```

But doesn't run from git extensions 😞

**Comment by gerhardol** [comment]
Set guitool from commandline to use any tool - you cannot change in the GUI though

**Comment by werwolfby** [comment]
`guitool` was set as well, but it doesn't help.

I did it by this manual: https://www.devart.com/codecompare/integration_git.html
It has guitool, but GitEx doesn't work mergetool, but work with difftool.

And it still works from command line.

**Comment by kevingosse** [comment]
Same problem with vsdiffmerge. Rollbacking to Git Extensions 2.x for now.

**Comment by mbeilste** [comment]
![image](https://user-images.githubusercontent.com/4382383/57797873-6d1cc300-7719-11e9-8286-afa95711b758.png)

**Comment by mbeilste** [comment]
^^  These commands work fine for me.

**Comment by mbeilste** [comment]
For those that like copy paste...

-merge -max -wait -a2 -3 "$LOCAL" "$BASE" "$REMOTE" "$MERGED"

-max -2 -wait "$LOCAL" "$REMOTE"

**Comment by TamaHobbit** [comment]
The same thing happens when Neovim-qt is used as the mergetool. With the following in your .gitconfig, executing `git mergetool` from git bash works fine, but GitExtensions refuses to start it, saying that the mergetool is incorrectly configured. Even though in Settings on startup, the vimdiff mergetool is marked green.

```
[merge]
	tool = vimdiff
[mergetool]
	prompt = false
[mergetool "vimdiff"]
	cmd = 'C:/Program Files/Neovim/bin/nvim-qt.exe' -- -d $LOCAL $REMOTE $MERGED -c '$wincmd w' -c 'wincmd J'
[difftool]
	prompt = false
[diff]
	tool = vimdiff
	guitool = vimdiff
```

**Comment by gerhardol** [comment]
You need to set both path and cmd at the moment
