### ISSUE TITLE
[2.51] No updates found of 2.51.01 version

### ISSUE THREAD

**Issue by andrey-helldar** [gitextensions/gitextensions#4873]
- GitExtensions version: 2.51
- OS version: win10

![2018-04-23 17-24-54 check for update](https://user-images.githubusercontent.com/10347617/39132903-9a933b22-471b-11e8-83fb-5d3b6cf87a68.png)
![2018-04-23 17-25-03 about](https://user-images.githubusercontent.com/10347617/39132904-9ab6a4fe-471b-11e8-9fff-3b722ba6549a.png)

@RussKie, [you said](https://github.com/gitextensions/gitextensions/issues/4457#issuecomment-364730048) that you are publishing a stable version a few weeks after the release. Tell me, is 6 weeks of sufficient time?

Thanks for u job!

**Comment by RussKie** [comment]
Thank you for alerting me. I completely forgotten about it amongst myriad of other things.
I have pushed the update to the notification branch, hope the updater picks it up.

**Comment by andrey-helldar** [comment]
@RussKie, yes, the program found an update. Thank you!)

![2018-04-24 20-10-58 check for update](https://user-images.githubusercontent.com/10347617/39202799-ae9d456e-47fb-11e8-98cc-cff5dce5358d.png)

**Comment by gerhardol** [comment]
@RussKie You need to quit your job, neglect your family and life only handling GE. The vast number of hours you spend is not enough.

**Comment by RussKie** [comment]
Hahah, I wish this project paid my bills.
In the past few months my family and work loads increased significantly, finding time for GE is a massive challenge.
