### ISSUE TITLE
GitExtensions v3 Soft-Crash (See Attached Image)

### ISSUE THREAD

**Issue by CDAGaming** [gitextensions/gitextensions#4874]
**Do you want to request a *feature* or report a *bug*?** Report a Bug

**What is the current behavior?** GitExtensions shows an System.ArgumentException Error of 'repositoryPath' at Target Site "Void MoveNext() @ GitCommands.UserRepositoryHistory.LocalRepositoryManager+<AddAsMostRecentAsync>d__3"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Just Launch GitExtensions.exe

**What is the expected behavior?** App should launch without a Crash Error

**Environment you encounter the issue:**

- GitExtensions version: 3.00.00.2485-Portable (Is present in earlier versions)
- GIT version: 2.17.0
- OS version: Windows 10 x64

**Did this work in previous version of GitExtensions (which)?** Yes, in v2 and earlier v3 builds, this crash is not present.

Screenshots:

![2018-04-23 1](https://user-images.githubusercontent.com/16328918/39155963-dab58f40-4719-11e8-98ca-60eff17bf010.png)
![2018-04-23](https://user-images.githubusercontent.com/16328918/39155964-db218f9c-4719-11e8-968a-b75e13533ade.png)

**Comment by drewnoakes** [comment]
I've been seeing this too.

**Comment by CDAGaming** [comment]
Im surprised noone else reported it, since it occurs straightaway on launch.

**Comment by RussKie** [comment]
hmm... I'm not getting it on my main computer. I'll try on another shortly

**Comment by RussKie** [comment]
Is there an attached image? The title says there's supposed to be one...

**Comment by CDAGaming** [comment]
Oh oops, one sec

**Comment by RussKie** [comment]
It seems to be quite intermittent, at least under a debugger
I'm getting this:

![image](https://user-images.githubusercontent.com/4403806/39156638-6d336e5c-479a-11e8-995c-7e464ea99578.png)
![image](https://user-images.githubusercontent.com/4403806/39156658-819164bc-479a-11e8-8f4c-e7e4c4967366.png)

This is somewhat a surprise...

As a fix, I think instead of throwing the exception we can silently return.
