### ISSUE TITLE
Convert to AsyncPackage with background load

### ISSUE THREAD

**Issue by madskristensen** [gitextensions/gitextensions#4875]
For performance reasons all extensions targeting VS2015+ should convert the Package class to AsyncPackage. See more here https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-use-asyncpackage-to-load-vspackages-in-the-background

It's as easy as doing exactly what your current `Package.Initialize` method does, but in the `Package.InitializeAsync` method, make the first line `await JoinableTaskFactory.SwitchToMainThreadAsync();`

**Comment by RussKie** [comment]
@sharwell is this something you have experience with?
