### ISSUE TITLE
Unable to schedule Git for Windows updater

### ISSUE THREAD

**Issue by davelogear** [gitextensions/gitextensions#4881]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** During Git 2.16.2 setup on Windows 7, a little box popped up saying:

![image](https://user-images.githubusercontent.com/32692076/39259736-7eb6d10c-4874-11e8-9dd0-1861f24f8b2a.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.** Install the latest Git Extensions Complete msi and let it install Git.

**What is the expected behavior?** Not have this error?

**Environment you encounter the issue:** Windows 7 Pro latest

- GitExtensions version: 2.51
- GIT version: 2.16.2
- OS version: Windows 7 Pro latest...

**Did this work in previous version of GitExtensions (which)?** Yah

**Comment by gerhardol** [comment]
This is in the Git installer that is bundled with GE.
Please open an issue to Git-for-Windows

GE should solve this with by not bundling the installer

**Comment by vbjay** [comment]
I agree.  I think the best way to handle it is to react to git not being
detected at path in settings and asking the user if they would like to find
git on their system(maybe they moved it) or install git?  If they say they
want to install git.  Download the file found at
https://git-scm.com/download/win.  Install that file and then try to
autodetect git again after a successful install.
