### ISSUE TITLE
Plugin distribution

### ISSUE THREAD

**Issue by maraf** [gitextensions/gitextensions#4885]
Hi there,
Do GitExtensions have any kind of plugin distribution?
If not, do you have toughs or future plans on this topic?
I was thinking about using NuGet packages for delivering plugins. 
What do you think?

[EDIT]
Link to the PluginManager repository: https://github.com/maraf/GitExtensions.PluginManager/

**Comment by sharwell** [comment]
It was discussed briefly in things like #4694, but currently the API is not treated as stable so every new build would require all plugins be recompiled.

**Comment by maraf** [comment]
Ok. 
So GitExtensions don't have any public plugins right now?

Currently I'm writing a second one and I'm looking for a way to distribute it, as sending dll via email (experience from the first one) is "hard".

My tough is to distribute plugins via NuGet feed. 
Make them dependent on `GitUIPluginInterfaces` (and if there is version incompatibility don't load them). 
There could be standalone "Plugin Manager GUI" tool responsible for finding NuGet packages (in configured feeds) depending on `GitUIPluginInterfaces` and extracting them in plugins folder.

Will be such tool interesting for you?

**Comment by drewnoakes** [comment]
What are your plugins? If they're of general interest then it may make sense to add them to this repo. Pros and cons both ways.

**Comment by vbjay** [comment]
I think having a plugin feed/manager would improve things.  Another
thought.  We could allow user to add custom feeds.  That way, if someone
developed in house plugins, they could have plugins for company use.
Adding a feedbuilder would facilitate that.

**Comment by vbjay** [comment]
See https://github.com/vbjay/NAppUpdate/tree/feedbuilderFix to get an idea of what I mean by feedbuilder.

**Comment by vbjay** [comment]
You might want to look at revision links.  http://git-extensions-documentation.readthedocs.io/en/latest/settings.html#revision-links

**Comment by maraf** [comment]
This looks great, but you still need to manually place an issue number to a commit message, am I right?
If so, than this is what our plugin does. We have a  small windows tool which tracks time on issues. The plugin than takes the issue number from this tool and adds it to the commit message when GitExtensions are opening a commit dialog.

**Comment by vbjay** [comment]
Yes.  It uses regex.  
![image](https://user-images.githubusercontent.com/3629489/39326555-65f16bc4-4963-11e8-8858-bce8cc36529a.png)

**Comment by RussKie** [comment]
The screenshot alone looks awesome!

**Comment by maraf** [comment]
I have published [second preview](https://github.com/maraf/GitExtensions.PluginManager/releases/tag/v0.2.0) containing integration with GitExtensions.

Any suggestions on future roadmap?

I would be very happy to make this happen, as current way of emailing newer versions of plugins is quite hard.

Some discussion can be found [here](https://github.com/maraf/GitExtensions.PluginManager/issues/21). I don't want to add any extra load on GitExtensions team (in form of more strict API definition etc). 

I think that when we strictly bind concrete version of plugin to concrete version of GitExtensions (which PluginManager on the side of installation currently does), we don't need any extra effort. Installed plugins for older version will simply not be loaded and when the plugin author provides updated version, PluginManager will (manually by user or automatically) do the update and plugin will be back.

Also, I would be happy to do the PR if you would be interested.

**Comment by RussKie** [comment]
I'm currently away and will definitely check it out when back in few weeks.

**Comment by vbjay** [comment]
https://www.visualstudio.com/services/live-share/. If you don't have a hdpi
display. You could remote debug with someone that does.
https://www.visualstudio.com/services/live-share/

**Comment by RussKie** [comment]
Hi @maraf I haven't forgotten about your work, we're currently stabilising and prep'ing for a v3 release, and that takes all our energy and attention. 
Once things quiet down a little I plan to dedicate more time to leveraging your manager capabilities and separating plugins from the main repo.

**Comment by maraf** [comment]
Ok. Glad to hear that.

**Comment by RussKie** [comment]
@maraf would you be able to update build scripts to include your PluginManager into our release artifacts?
I'd like to include it in the next release.

**Comment by RussKie** [comment]
@maraf would you be able to update build scripts to include your PluginManager into our release artifacts?
I'd like to include it in the next release.

I expect updates to the following files:
* \Setup\Product.wxs 
* \Setup\MakePortableArchive.cmd
* \Setup\Prepare-Release.ps1 - before running builds, pull down the latest release version from your repo into \Plugins\GitExtensions.PluginManager folder, if it does not exists.

**Comment by maraf** [comment]
I'm going to try today.

**Comment by maraf** [comment]
I don't see any direct reference to .NET standard from plugin.
I'm going to investigate and let you know asap.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/49344376-2c862d00-f644-11e8-8ec8-f4922d381f99.png)

**Comment by maraf** [comment]
Yes. PackageManager is targeted againts .NET standard, but that is not loaded into GE process.

**Comment by maraf** [comment]
It seems the problem is caused by reference on Neptuo (which targets .NET standard). 
I'm already going to remove it in https://github.com/maraf/GitExtensions.PluginManager/issues/55.

.NET standard dll is by default in GAC, but I'm not sure if its not added with .NET framework v4.7.

Also, PluginManager now targets .NET framework v4.7, but GitExtensions targets v4.6.1. 
Guess it should match.

**Comment by RussKie** [comment]
I have tried it on a brand new VM running W10. 
We can't expect all users to have .NET 4.7 or .NET Core installed.

**Comment by maraf** [comment]
"Downgrade" tracked in https://github.com/maraf/GitExtensions.PluginManager/issues/57.
Later today I will publish the update working with .NET framework v4.6.1.

**Comment by maraf** [comment]
@RussKie Can you try to build PM from current master branch? Or I can share you a build.
It seems that only problem was with https://github.com/maraf/GitExtensions.PluginManager/issues/55.
I'm testing it on fresh Windows 7 and 10 VMs.

**Comment by RussKie** [comment]
If you can share a build, it would be faster. Thank you

**Comment by maraf** [comment]
[GitExtensions.PluginManager-v0.7.2-beta1.zip](https://github.com/gitextensions/gitextensions/files/2641271/GitExtensions.PluginManager-v0.7.2-beta1.zip)

**Comment by RussKie** [comment]
The app no longer throws plugin related errors, but the PM crashes on start.
I found an exception in the Windows Event Viewer:

```
Application: PackageManager.UI.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentNullException
   at System.Windows.Interop.WindowInteropHelper..ctor(System.Windows.Window)
   at System.Windows.MessageBox.Show(System.Windows.Window, System.String, System.String, System.Windows.MessageBoxButton, System.Windows.MessageBoxImage)
   at PackageManager.Exceptions.MessageExceptionHandler.Handle(Neptuo.Exceptions.Handlers.IExceptionHandlerContext`1<System.Exception>)
   at Neptuo.Exceptions.Handlers.ExceptionHandlerBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Handle(System.Exception, Neptuo.Collections.Specialized.IKeyValueCollection)
   at Neptuo.Exceptions.Handlers.ExceptionHandlerBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Neptuo.Exceptions.Handlers.IExceptionHandler<Neptuo.Exceptions.Handlers.IExceptionHandlerContext>.Handle(Neptuo.Exceptions.Handlers.IExceptionHandlerContext)
   at Neptuo.Exceptions.Handlers.ExceptionHandlerBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Handle(System.Exception, Neptuo.Collections.Specialized.IKeyValueCollection)
   at Neptuo.Exceptions.Handlers.ExceptionHandlerBuilder`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Neptuo.Exceptions.Handlers.IExceptionHandler.Handle(System.Exception)
   at PackageManager.App.OnDispatcherUnhandledException(System.Object, System.Windows.Threading.DispatcherUnhandledExceptionEventArgs)
   at System.Windows.Threading.Dispatcher.CatchException(System.Exception)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(System.Object, System.Exception)
   at System.Windows.Threading.ExceptionWrapper.CatchException(System.Object, System.Exception, System.Delegate)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at PackageManager.App.Main()
```

It looks there are still dependencies on Neptuo library

**Comment by maraf** [comment]
This is caused by https://github.com/maraf/GitExtensions.PluginManager/issues/58. I'm throwing there message box, but app main windows is null, which causes exception during exception processing.

About Neptuo libraries, I'm using them in standalone `PackageManager.UI.exe` and it would be hard to remove them, but this executable has il-merged `netstandard.dll` inside and it seems to work.

I'm going to fix message box issue and would ask you for one more round.

**Comment by maraf** [comment]
[GitExtensions.PluginManager-v0.7.2-beta2.zip](https://github.com/gitextensions/gitextensions/files/2646045/GitExtensions.PluginManager-v0.7.2-beta2.zip)
Second round...

**Comment by RussKie** [comment]
Getting close :) Is nuget.config supposed to be shipped with the zip?

[image: image.png]

**Comment by RussKie** [comment]
No pressure, but the v3 release is pretty much blocked by this. :)
If we can't fix it today, I will have to exclude the PM from the release
and add it in a subsequent one.

**Comment by maraf** [comment]
No, it is not. PM creates one when first started.

**Comment by RussKie** [comment]
Running from under ProgramFiles the app doesn't have permissions to write
files, and that causes the UAE.

**Comment by maraf** [comment]
It tries to restart itself as administrator. I'm not sure what else I can do. Ideas?

**Comment by RussKie** [comment]
Ship a default nuget.config?

**Comment by vbjay** [comment]
Store nuget config in programdata and not program files.

**Comment by maraf** [comment]
Both nuget.config and packages.config are created when first needed.

**Comment by maraf** [comment]
I can relocate these files, but PM would need write access to Program Files to extract plugin.
The only other option I see is to configure second folder for plugins in GE.

**Comment by vbjay** [comment]
This is why we have CommonApplicationData with
https://docs.microsoft.com/en-us/dotnet/api/system.environment.getfolderpath.

We could use that if not portable. If portable use plugins folder in exe
path.

**Comment by maraf** [comment]
Do plugins load from this location?

**Comment by RussKie** [comment]
Right now we need to get plugin manager to start, for this we need to PM to write nuget.config and packages.config. 

As @vbjay pointed, `%CommonApplicationData%` may be a good option to store the data, or `%UserAppData%` (that's where we store all other user-related configs).
Perhaps we should write plugins there as well...

This work seems to be adding a lot of unnecessary stress on everyone, so I'm starting to considering pulling the PM from the current release.
This will give us time to re-group and design a better integration.
Thoughts?

**Comment by maraf** [comment]
I'm ok with it. Glad that this discussion exists and looking forward to not sending new dlls via email :-)

**Comment by RussKie** [comment]
I'd like to continue this work after the release.

**Comment by vbjay** [comment]
Yes.  Plugins should be loaded from there too.  I'm sure we can configure the mef stuff to load from a %CommonApplicationData%\GitExtensions\plugins folder if not portable and if portable  {GE folder}\plugins if it is.
