### ISSUE TITLE
Can't collapse diff with parent in diff panel

### ISSUE THREAD

**Issue by R0nd** [gitextensions/gitextensions#4886]
*bug*

When viewing the diff panel on a merge commit, can't collapse diff with parent.
Clicking the collapse button has no effect.

![clipboard01](https://user-images.githubusercontent.com/12497155/39352873-b6d6c6e6-4a0e-11e8-80c2-919480a843f5.png)

- GitExtensions version: 2.51.01
- GIT version: 2.12.2.windows.2
- OS version: Windows 10 1607 Build 14393.1198

**Comment by RussKie** [comment]
Try double click on the divider to the left of the button
