### ISSUE TITLE
GitExtensions reports v2.51.1 available but points to old ChangeLog

### ISSUE THREAD

**Issue by tomlogic** [gitextensions/gitextensions#4896]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Yesterday GitExtensions 2.51.0 reported that 2.51.1 was available.  I wanted to see what's changed before downloading, but clicking on Show ChangeLog doesn't show anything past the 2.51.0 release.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In GitExtensions 2.51.0, "Check for updates" from the "Help" menu.   Click on "Show ChangeLog".

**What is the expected behavior?**
Link should take you to a ChangeLog describing the 2.51.1 release.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.0
- GIT version: 
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**
Not sure -- seems like just an issue of linking to the correct ChangeLog on GitHub.

**Comment by RussKie** [comment]
fixed, thank you
