### ISSUE TITLE
Column widths not adjustable

### ISSUE THREAD

**Issue by RaymondDeen** [gitextensions/gitextensions#4902]
**Do you want to request a *feature* or report a *bug*?**
Reporting a bug

**What is the current behavior?**
In the commits view, I can't change all column widths correctly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Widen the columns "commit message" and "committer"; the field "commit date" will become smaller. Then try to make those fields smaller again; you'll see that the field "commit date" can't be made wider.

**What is the expected behavior?**
I expect all field widths in the view to be adjustable to both sides.

**Environment you encounter the issue:**
Windows

- GitExtensions version: 2.51.01
- GIT version: git version 2.16.2.windows.1
- OS version: Windows 10 pro 10.0.16299.371

**Did this work in previous version of GitExtensions (which)?**
It did work, not sure till which version exactly.

PS thanks Russkie for your comment

**Comment by RussKie** [comment]
Please use the provided issue template, it is there for a reason.

**Comment by drewnoakes** [comment]
In #5807 the columns no longer stretch to fill the available space. I think this will achieve what you want.

![image](https://user-images.githubusercontent.com/350947/41551742-b3c41640-7324-11e8-8496-f031f83e4ffd.png)

**Comment by RaymondDeen** [comment]
Hi Drew,

thanks for the reply and fix!
Any expectations when the v3 final will be out?

TIA Raymond

2018-06-18 19:23 GMT+02:00 Drew Noakes <notifications@github.com>:

**Comment by drewnoakes** [comment]
> Any expectations when the v3 final will be out?

No guarantees, but we're hoping to get a RC together within a month.

For now you can test out a build from that PR here:

https://ci.appveyor.com/api/buildjobs/6v811digbroiu9ra/artifacts/GitExtensions-Portable-3.00.00.2827.zip
