### ISSUE TITLE
Add scripts for BeforeFetch and AfterFetch

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4909]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
There are a number of script injection points, such as `BeforeCommit`, `AfterCommit` etc however there is no injection points for fetch-related events.
Pull events the closest it comes, however pull and fetch are quite different - pull performs fetch followed by merge. So in a nutshell fetch is a subset of pull.

**What is the expected behavior?**
* New script events `BeforeFetch` and `AfterFetch` are added to `ScriptEvent` enum.
* Script events are raised where appropriate (e.g. `FormPull` and `FormBrowse` handling toolstip buttons)

- GitExtensions version: v2.5x and master

**Comment by lipkau** [comment]
I think you meant the other way around:
> So in a nutshell fetch is a subset of pull.

**Comment by RussKie** [comment]
`pull` is a superset - `fetch+merge`, so `fetch` is a subset of `pull`. right?

**Comment by lipkau** [comment]
yes... I will shut up now... :embarrassed:
