### ISSUE TITLE
FeatureRequest: filter branches by check-marks

### ISSUE THREAD

**Issue by deischi** [gitextensions/gitextensions#491]
The request is to have a more comfortable way to select multiple branches.
Now: drop-downlist to select one branch, or enter multiple branches manually.

Idea: also offer a list-view of all branches, and select by check-mark if the branch should be shown or not.

**Comment by h0lg** [comment]
How about selecting branches from the left branch tree panel?
https://github.com/gitextensions/gitextensions/issues/3114#issuecomment-503377888
https://github.com/gitextensions/gitextensions/discussions/9495#discussioncomment-1606019
https://github.com/gitextensions/gitextensions/issues/3114#issuecomment-503317476
