### ISSUE TITLE
Search in repository (enhanced UI for git grep)

### ISSUE THREAD

**Issue by diaconesq** [gitextensions/gitextensions#4912]
Feature proposal
-----
A user interface for searching the repository (i.e. `git grep`)

The speed of git grep is incredible (helped by git's indexing and by the fact that it only searches checked-in files). It would be great to have a companion user interface, that would enhance the search.
Once the matching text/files are displayed, I'd like to get features similar to those found in [GrepWin](https://tools.stefankueng.com/grepWin.html):
- Open file (at matching line) in editor of choice
- Open path in Explorer
- Blame
- File history
- ...

**Comment by gerhardol** [comment]
Git 2.24 also adds --recurse-submodules
https://github.com/git/git --recurse-submodules/blob/v2.24.0/Documentation/RelNotes/2.24.0.txt#L153

This could be implemented in the File tre (or even grid context menu) showing results in the File tree.
More than one revision could be searched (to find where a specific change was done without using blame?)
Options in the form could be quite basic as long as a link to the man page is available: 
https://git-scm.com/docs/git-grep

**Comment by cniweb** [comment]
Add support for "--recurse-submodules" for newest version 2.24 of git

**Comment by GintasS** [comment]
Abandoning this because of the age and lack of discussion.

**Comment by gerhardol** [comment]
Reopenening this as a a GUI would be good to have.

One way to implement this is to add both a file filter (#10157) _and_ a searchbox in Tree tab. 
This does not handle artificial commits though. Either display Tree for worktree/index (would need to query file system to get worktree, ls-files can be used for index) or only show the grep results. (For worktree the artificial commit results could be added to diff tab too, this would be separate group and a little confusing but could be used in a test).

Searches to be done with `--files-with-matches`. If something similar to diff section is added, then `--line-number` to add such matches (some extra structures to handle this).
