### ISSUE TITLE
Empty Dashboard on Windows

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#4913]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Dashboard shows nothing

![image](https://user-images.githubusercontent.com/596334/39577348-b7223a90-4f13-11e8-9150-12dcf7c18c42.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just open GitExtensions

**What is the expected behavior?**
not sure, maybe need to show something

**Environment you encounter the issue:**

- GitExtensions version: Master branch commit 66e20b0a3a5d9f1407ac0d68643af61a70788a5d
- GIT version: 2.16.1.windows.1
- OS version: Windows 10 64 bits

**Did this work in previous version of GitExtensions (which)?**
Yes.

**Comment by RussKie** [comment]
Yes, as of #4766 the existing dashboard is no longer operable until #3693 is finalised and merged.
