### ISSUE TITLE
Feature: ignore whitespace in Blame

### ISSUE THREAD

**Issue by mnocenti** [gitextensions/gitextensions#4915]
In the Blame window, it would be nice to have a button to ignore whitespace (using git blame -w).

This makes it easier to find the commit that actually modified a line, and didn't just re-indent it.

**Comment by pmme** [comment]
Using GitExtensions 2.51.01 in my git command log it appears that GE already uses -w on git blame.

``2018-05-11T13:32:53.2768103+12:00    "C:\Program Files\Git\bin\git.exe" blame --porcelain -M -w -l "c068e9b3b096749d042bb0001057abf762549377" -- "xxxxxxxx.xxx"    #(took 757 ms)``

**Comment by jbialobr** [comment]
Thank you @pmme! Indeed there is such an option:)

![gitext](https://user-images.githubusercontent.com/1003909/39905671-d8a00172-54de-11e8-9ff1-e30ae2a93ef1.png)

**Comment by nicoddemus** [comment]
👍 

(nice choice of avatar btw @pmme 😁)
