### ISSUE TITLE
Set author date when committing

### ISSUE THREAD

**Issue by hellojianqun** [gitextensions/gitextensions#4918]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Unable to set the author date when committing, which can be achieved through the 'git commit --date' command.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
It would be nice to provide an option in the commit options to make it possible to set the author date, with a precision to second. Also, the current date and time can be provided as the default setting.

**Environment you encounter the issue:**

- GitExtensions version: Version 2.51.01
- GIT version: 
- OS version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by RussKie** [comment]
Please use the issue template, it is there for a reason.

**Comment by vbjay** [comment]
Probably did a rebase and saw the difference between the commit date and
the author date.

**Comment by hellojianqun** [comment]
It may not be considered 'important', but it's useful, that's why the 'git commit' command provide the '--date' argument. I'm looking farward to it because I'm not using git the "native" way, so I tend to conceal my use case. But, since git contains this option, it's not unconvincing that it's useful for "native" users too, is it?
So, if you contributors kindly add this feature to Git Extensions, it is exiting news and Git Extensions becomes more powerful. If you don't, Git Extensions is still an excellent git UI tool for me.

**Comment by drewnoakes** [comment]
When I started the [metadata-extractor](https://github.com/drewnoakes/metadata-extractor) project in 2002, I had no version control in place. Just zip files 😊 Later, I started using Subversion, but lost that early history. When I migrated to Git, I was able to recreate those [early source code snapshots](https://github.com/drewnoakes/metadata-extractor/commits/master?after=156ba9fa346448317cdea6aef140f9913fb906bd+1070) using `commit --date` from those source archives.

I'm not sure GE needs this, as the command line was adequate for my needs. Maybe others have more compelling use cases.

**Comment by hellojianqun** [comment]
@drewnoakes Exactly the same situation as what I was facing with :) And I think people come to Git Extensions because they prefer GUI operations and views over command lines and echos, and therefore would be grateful if they don't need to return to command lines when doing basic git operations like committing.

**Comment by deathstar1** [comment]
I am also in need for this feature too to set my commit dates .
Do let me know if you want a pull from me . Willing to contribute :)

**Comment by gerhardol** [comment]
> I am also in need for this feature too to set my commit dates .
> Do let me know if you want a pull from me . Willing to contribute :)

Contributions are welcome!

**Comment by pmiossec** [comment]
This is the kind of feature where a good UX is difficult to achieve so before starting, perhaps you should tell us how you see it done so that there is a discussion about it.

To prevent doing things that will never be merged because that's not how we see it done....

**Comment by pmiossec** [comment]
And for my information, I'm also interested by knowing the use case for this feature?

**Comment by vbjay** [comment]
For now you can stage files in ge and then go to console and run git commit
with the right arguments. You can also write a script in ge settings to ask
for user input to accept the date.

**Comment by RussKie** [comment]
@hellojianqun your request feels very niche, and isn't something a general user would require on a day to day basis. The aim of the app is to make git more approachable and automate certain used workflows, we have no intention to expose every nuanced functionality git has.

As pointed above you can use the app's script functionality to automate the task.
