### ISSUE TITLE
TranslationString broken [3.0 branch]

### ISSUE THREAD

**Issue by szaliszali** [gitextensions/gitextensions#4922]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
translations using TranslationString are broken since commit ed2ae7bdcfa09029a4ce75166f65371c201a3f2c because the Text property setter was removed

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- select a non-English language
- strings in commit info will be shown in English
![image](https://user-images.githubusercontent.com/1851369/39670262-cd9696ba-5100-11e8-8c29-9eed1725eeb0.png)

**What is the expected behavior?**
- select a non-English language
- strings in commit info will be shown in the selected language
![image](https://user-images.githubusercontent.com/1851369/39670270-de489800-5100-11e8-9e9b-04fdac6daa1f.png)

**Environment you encounter the issue:**

- GitExtensions version: 3.0 5e58f92b5dbdb73e3519babcc8987b4c17446d71
- GIT version: 2.16.1
- OS version: Windows 8.1

**Did this work in previous version of GitExtensions (which)?**
yes, v2.51.01

**Comment by RussKie** [comment]
I doubt it is the correct conclusion. The removal of private setters has no
bearing on public API.

The most likely reason is that TranslationString fields in CommitInfo have
been renamed. Until we re-run translations the translations probably won't
work.

**Comment by RussKie** [comment]
I take my words back, indeed without the private setter it doesn't work...

**Comment by RussKie** [comment]
The reason why it doesn't work when the setter is removed is that it uses reflection to set the localised strings to the `TranslationString` objects
https://github.com/gitextensions/gitextensions/blob/be4ad89a3b6b86906fc111050205b91e2068989a/ResourceManager/Xliff/TranslationUtl.cs#L171-L182
