### ISSUE TITLE
Context menu for listview groups in Dashboard

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#4948]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the expected behavior?**
A user must be able to right click on a dashboard category (represented by a listview group) and be able to
* clear all recent repositories
* rename a favourite category (reusing `FormDashboardCategoryTitle`)
* delete a favourite category along with its content

The right click event is facilitated by #4945.

**Environment you encounter the issue:**

- GitExtensions version: current master

**Comment by NikolayXHD** [comment]
I am going to do it, if I may )
