### ISSUE TITLE
Feature Request : Allow searching for branch by keywords in "Checkout Branch" window

### ISSUE THREAD

**Issue by aakashbhowmick** [gitextensions/gitextensions#4951]
While working with remote branches, there may be hundreds of branches on my server. To select the right branch, currently everytime I need to scroll through the long list to find the branch that I want.

I would like the ability to be able to search for a branch by keywords, and a drop-down should show the remote branches that match my keywords, like the one we have in GitHub.

![image](https://user-images.githubusercontent.com/577837/40065924-969d16d0-586b-11e8-9358-9d5f7d4c9443.png)

**Comment by vbjay** [comment]
What would the keyword match against?  The remotes don't give keyword info
back.  What would searching for "cat" give back if the remotes had ... in
... info for the remote branch.  Basically what would it filter against?

**Comment by aakashbhowmick** [comment]
Sorry... I'm new to GitExtensions. I did not realize this search-box is already there.

Please close this issue.
