### ISSUE TITLE
Committer value in commit window not showing correct value

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#4953]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
configured a different email address for the local repo and the global email address still shows in the commit window.  When I commit, the correct email address is used.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/3629489/40094005-a8ecfd42-5892-11e8-8049-f095bb16280b.png)

![image](https://user-images.githubusercontent.com/3629489/40094025-bc046e2e-5892-11e8-845e-a96d0ecc6404.png)
![image](https://user-images.githubusercontent.com/3629489/40094092-fc244dd0-5892-11e8-908d-20a1f2e33691.png)

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/3629489/40094096-012cc244-5893-11e8-90a7-b47827a9f47d.png) should say 123@123.com and if I changed the user name it should use the value provided in the local config.
 
**Environment you encounter the issue:**

- GitExtensions version:2.51.01
- GIT version: git version 2.16.1.windows.4   
- OS version: 
![image](https://user-images.githubusercontent.com/3629489/40093900-2d68610c-5892-11e8-8564-dea4a481fa99.png)

**Did this work in previous version of GitExtensions (which)?**
Yes

**Comment by pmme** [comment]
I was going to have a go at this but was unable to reproduce this problem. I tested on a GE debug build and a release build from the current top commit on the master branch at this time, 083eef2e2c5030354bb33cefd14e233c58f72e41.

I used the GE repository for my test. I made the appropriate change: setting an email with the settings radio set to local. 
In separate tests I tried:
* Accessing settings both from the toolbar.
* Accessing settings from the pull-down menu. 
* Restarting GE before going to the commit window. 

In all cases the commit window showed the "effective" setting for email: the local email (and name when I tried that) when it was set and the global email when I removed the local setting.

**Comment by RussKie** [comment]
You could try 2.51 as well, if necessary.
Master has undergone a significant change from 2.51 codebase.

**Comment by pmme** [comment]
I see now that Jay stated the environment as 2.51.01. I should read more carefully.
However, I was still unable to reproduce the problem in 2.51.01 either.

**Comment by RussKie** [comment]
@vbjay?

**Comment by vbjay** [comment]
I'll run master tonight and see if it is only in 2.51 or both on my machine. I'll check both work and home machines.

**Comment by vbjay** [comment]
Looks like 2.51.02 doesn't have this issue.  I'm closing as already fixed or just a weird setup issue.
