### ISSUE TITLE
There is no Diff tab

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#4955]
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**

There is no Diff tab
![gitext](https://user-images.githubusercontent.com/1003909/40117036-fb44137c-5915-11e8-9fc2-319700a0fbd3.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Enable https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#detailed-browse-repository-window-show-revision-details-next-to-the-revision-list
2. Close GE
3. Open GE

**What is the expected behavior?**

Diff tab should be visible

**Environment you encounter the issue:**

- GitExtensions version: b3f168d30fc9cdc20e880db7d7eb0b269c03757a

**Did this work in previous version of GitExtensions (which)?**
Yes. 2.51

**Comment by gerhardol** [comment]
This is something I reported to @RussKie for the Dashboard PR, but he did not see the problem, the Commit change should be the difference.
