### ISSUE TITLE
Crash when you click on the Commit tab

### ISSUE THREAD

**Issue by jeanlibera** [gitextensions/gitextensions#4956]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

Using the Steps To Reproduce, gitextensions will open a crash dialog with the following information:

Exception Type: System.ArgumentOutOfRangeException

Message: The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset

Stack Trace:

    at System.DateTimeOffset.ValidateDate(DateTime dateTime, TimeSpan offset)
    at System.DateTimeOffset..ctor(DateTime dateTime)
    at GitCommands.CommitDataManager.CreateFromRevision(GitRevision revision)
    at GitUI.CommitInfo.CommitInfo.ReloadCommitInfo()
    at GitUI.CommandsDialogs.FormBrowse.CommitInfoTabControl_SelectedIndexChanged(Object sender, EventArgs e)
    at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
    at System.Windows.Forms.TabControl.WmSelChange()
    at System.Windows.Forms.TabControl.WndProc(Message& m)
    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Setup:
In Settings > Git Extensions, check the box "Show current working directory changes as an artificial commit"

Steps to Reproduce:
1. In the main window, select a changeset which has changes, and then click on the Diff tab
2. In the main pane, select the line for the Working Directory changes or the Staged changes.
3. Click on the Commit tab

**What is the expected behavior?**

The Commit tab should be empty or indicate that there are no changes. GitExceptions should not crash.

**Environment you encounter the issue:**

Windows 10

- GitExtensions version: 2.51.01
- GIT version: 2.17.0.windows.1
- OS version: Windows 10, version 1709

**Did this work in previous version of GitExtensions (which)?**

**Comment by EbenZhang** [comment]
literally, and just from my memory, it seems a datetime.minvalue or most probably the default value assigned to datetimeoffset. This will give an exception when in an east timezone e.g.+4. the datetimeoffset will try -4 of the datetime thus a result less than the min value

**Comment by RussKie** [comment]
Thank you, that's a good hypothesis. Definitely worth checking.

**Comment by RussKie** [comment]
@jeanlibera could you please test https://ci.appveyor.com/api/buildjobs/c7w1g33lsjjly2de/artifacts/GitExtensions-2.51.01.2638-Mono.zip and confirm the fix

**Comment by jeanlibera** [comment]
I tested, and the problem is fixed in your zip.

**Comment by RussKie** [comment]
Thank you
