### ISSUE TITLE
FYI: Fix for scaling issues introduced by recent Windows Updates

### ISSUE THREAD

**Issue by plioi** [gitextensions/gitextensions#4957]
Not a bug, but information that might be useful to you in the coming days if people report it as a bug: recent Windows Updates caused the entire UI to look blurry, with incorrect control sizes and overlapping controls.  After a short time, Windows gave me a notification which suggested enabling a new system setting: "Advanced scaling settings" \ "Fix scaling for apps".  It claimed it would help with the blurriness, but actually helped with *all* of the display glitches.

**Comment by RussKie** [comment]
Is this on W10?

**Comment by plioi** [comment]
Windows 10 Pro, version 1803, OS Build 17134.48

**Comment by RussKie** [comment]
v3 has a number of improvements in hidpi/scaling areas.
