### ISSUE TITLE
Show artificial refs in different color

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#4963]
Instead of artificial refs having default branch color:
![image](https://user-images.githubusercontent.com/483659/40221972-adaa1f22-5a86-11e8-9d68-0de68e9c0117.png)

I suggest to add additional color setting and have it gray by default:
![image](https://user-images.githubusercontent.com/483659/40222030-d743b618-5a86-11e8-95e1-c10a39888ef3.png)

If you think it's worth doing, I'll create a PR.

**Comment by RussKie** [comment]
I like the idea.
Please be mindful of the dark themes when creating a PR.
Thank you
