### ISSUE TITLE
crash on copy to clippboard operation if repo history is still loading

### ISSUE THREAD

**Issue by liedtkeInTUM** [gitextensions/gitextensions#4966]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Exception is thrown during copy to clippboard operation (ctrl+c) if the git history is still loading (no git commit is selected).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- open GitExtension
- press ctrl+c before your repo is loaded completly
![image](https://user-images.githubusercontent.com/15230134/40233858-dddee236-5aa4-11e8-881f-08c87ca13259.png)

**What is the expected behavior?**
- No exception
- A warning
- or just nothing

**Environment you encounter the issue:**

- GitExtensions version: 2.51.01
- GIT version: 2.15.1.windows.2
- OS version: Win10 1803

**Did this work in previous version of GitExtensions 
(which)?**
don't know

**Comment by drewnoakes** [comment]
I can no longer reproduce this on master. I believe it may have been fixed in #4988 as revisions are now sent back to the grid via an observable that's observed from the UI thread. But this is just a guess.

It's definitely reproducible on 2.51.02, but not on master. I think we can close this.
