### ISSUE TITLE
Install a template for Revision Links

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#4970]
**Feature Request**

**What is the current behavior?**
no Revision Links configured

**What is the expected behavior?**
A sample *global* Revision Links configuration should be created by the installer.
I've prepared a template GitExtensions.settings file which detects GitHub links:
[GitExtensions.settings.zip](https://github.com/gitextensions/gitextensions/files/2020370/GitExtensions.settings.zip)

**Environment you encounter the issue:**
- GitExtensions version: 2.51
- GIT version: N/A
- OS version: Windows

![grafik](https://user-images.githubusercontent.com/36601201/40279659-9022e2d8-5c46-11e8-856c-ec129b24d2da.png)
![grafik](https://user-images.githubusercontent.com/36601201/40279664-9dc04ac0-5c46-11e8-8ad7-ae53686cea10.png)
![grafik](https://user-images.githubusercontent.com/36601201/40279667-a96170fc-5c46-11e8-81e2-c95cbb30beef.png)

**Comment by RussKie** [comment]
Thank you, but to be honest I'm not sure it is a "_should be_". Whilst some of our users certainly use GH on a daily basis, a lot of users (especially enterprise) do not.
Revisions links are typically (though not always) created per project and stored in the project's repository (like we have in ours).

**Comment by vbjay** [comment]
You can create the revision links the way you like for one repo.  Copy the settings file to a desired location.  Then create a powershell script that copies that file's revision link section to a local copy in the current repo. Then open the revision links settings and alter to fit the current repo needs.  We do provide powershell script functionality.  

![image](https://user-images.githubusercontent.com/3629489/40389125-85cd55d0-5ddf-11e8-917f-768aba18b591.png)

![image](https://user-images.githubusercontent.com/3629489/40389267-e990172e-5ddf-11e8-9951-be405233b41b.png)

**Comment by mstv** [comment]
In my opinion it is much easier
to adapt the defaults or to disable them if they really do not suit
than to figure out that GE has this feature and how to configure it.
That's why I suggested to show the above quite generic Revision Links by default.
If the URL doesn't match, nothing will be shown.

> Whilst some of our users certainly use GH on a daily basis, a lot of users (especially enterprise) do not.

Understood, URLs ending with ".git" are not sufficient to know that it *is* a GH server. And non-working links would result in bug reports.

I know some enterprises that run their own private GitHub servers.
If they do not support GE officially, they might not accept a `GitExtensions.settings` file, especially not from subcontractors.

Thank you for pointing to scripts, vbjay. Such a script might even run automatically and detect whether GH links would work and then activate them.

For the meantime until such a script or plugin is created and gets mature: Can the above file be added as another example to the documention of [Revision Links](https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#revision-links)?
The documentation could just link to the file in the source of the documentation on GH, couldn't it?

**Comment by vbjay** [comment]
Create a pull request. https://github.com/gitextensions/GitExtensionsDoc

**Comment by GintasS** [comment]
Abandoning this because of the age and lack of discussion. PR was merged.

**Comment by RussKie** [comment]
> Fixed by #6785?

Nice! I was oblivious to these. Thank you
