### ISSUE TITLE
StackOverflowException when highlighting a branch

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#4971]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
A `StackOverflowException` is thrown when trying to highlight a branch in the revision grid.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* clone the [Roslyn](https://github.com/dotnet/roslyn) repository
* select commit dotnet/roslyn@7434a5fb86a3b45e3a47a6d9c0bf43fcd41abef9 (_Merge pull request #26965 from dotnet/merges/master-to-features/editorconfig-in-compiler_, currently the tip of of branch `origin/features/editorconfig-in-compiler`)
* press Ctrl+Shift+B or select _View - Highlight selected branch (until refresh)_

**What is the expected behavior?**
* the selected branch is highlighted

**Environment you encounter the issue:**

- GitExtensions version: 2.51 (`master` at b3335f8ab3d80b058fad339cc5947c511f5a4da3)
- GIT version: 2.17.0.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Don't know.

**Comment by gerhardol** [comment]
I do not see a way to rewrite GitUI\UserControls\RevisionGridClasses\DvcsGraph.Graph.cs HighlightBranchRecursive(string id) to not be recursive.
Limit highlighting to a certain number of steps will be a very coarse protection. A warning before launching would be annoying.

**Comment by RussKie** [comment]
I haven't looked at code. Could you please point to it.

There's always a way to convert recursion to an iteration over a queue.

**Comment by gerhardol** [comment]
https://github.com/gitextensions/gitextensions/blob/master/GitUI/UserControls/RevisionGridClasses/DvcsGraph.Graph.cs#L122
Sure, a queue will not use the stack

**Comment by drewnoakes** [comment]
Actually I fixed this back in April in one of my branches. I'll make a PR now.

**Comment by RussKie** [comment]
@crypto-rsa could you please test  and confirm the fix https://ci.appveyor.com/api/buildjobs/2ip50whgjfgmvur1/artifacts/GitExtensions-Portable-3.00.00.2668.zip

**Comment by crypto-rsa** [comment]
Works perfectly and instantly! 👍

**Comment by RussKie** [comment]
In which build?

**Comment by crypto-rsa** [comment]
The issue is now fixed in `master`, too.
