### ISSUE TITLE
Shell start script failing if run from a different directory

### ISSUE THREAD

**Issue by CharlesB2** [gitextensions/gitextensions#4975]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
```
$ ~/bin/GitExtensions/gitext.sh
Cannot open assembly 'GitExtensions.exe': No such file or directory.
```
**Environment you encounter the issue:**
- GitExtensions version: 2.51.01
- GIT version: 2.7.4
- OS version: Ubuntu 16.04 LTS

**Comment by RussKie** [comment]
We still patching 2.51 branch, please send the PR to it instead of master
