### ISSUE TITLE
Find Large Files unable to select file

### ISSUE THREAD

**Issue by mkbel** [gitextensions/gitextensions#4977]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

It is impossible to select any file with check box in plugin Find Large Files.

Also pushing button delete leads to error:

cmd.exe /C "/tmp/tmp30259e6a.cmd"

System.ComponentModel.Win32Exception (0x80004005): ApplicationName='cmd.exe', CommandLine='/C "/tmp/tmp30259e6a.cmd"', CurrentDirectory='/home/user/workspace/some_repository/', Native error= Cannot find the specified file
  at System.Diagnostics.Process.StartWithCreateProcess (System.Diagnostics.ProcessStartInfo startInfo) [0x002dc] in <8a8abae728c244359683ef777047ab9e>:0 
  at System.Diagnostics.Process.Start () [0x0003a] in <8a8abae728c244359683ef777047ab9e>:0 
  at (wrapper remoting-invoke-with-check) System.Diagnostics.Process:Start ()
  at GitUI.UserControls.EditboxBasedConsoleOutputControl.StartProcess (System.String command, System.String arguments, System.String workdir, System.Collections.Generic.Dictionary`2[TKey,TValue] envVariables) [0x0017e] in <b6afc2842a104f2792e5040382287caa>:0 
  at GitUI.FormProcess.processStart (GitUI.FormStatus form) [0x00048] in <b6afc2842a104f2792e5040382287caa>:0 

command = cmd.exe
arguments = /C "/tmp/tmp30259e6a.cmd"

Done

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

Being able to select file with checkbox.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.01
- GIT version: 1:2.17.0-1
- OS version: GNU/Linux Debian Sid

**Did this work in previous version of GitExtensions (which)?**

Don't know. But on Windows it was definitely in some moment working.

**Comment by mkbel** [comment]
Updating libmono-2.0-1
from: 5.4.0.201-0xamarin10+debian9b1
to: 5.12.0.226-0xamarin3+debian9b1
won't help.

**Comment by gerhardol** [comment]
Delete will call cmd.exe so it will only work in Windows
(this specific part is calling StartBatchFileProcessDialog(), there are other situations too).

mono is no longer supported in master, so no change planned there.
If someone want to address the problem (or disable the plugin outside windows) address the correction to release/2.51 branch

**Comment by RussKie** [comment]
> It is impossible to select any file with check box in plugin Find Large Files.

Why? Is it rendering issue?
Any screenshots?

**Comment by RussKie** [comment]
@CharlesB2 would it be a quick fix to replace cmd.exe with Linux counterpart?

**Comment by gerhardol** [comment]
The delete file seem to be the only situation where cmd is used in Linux. It is easy to handle windows specially here.

The selection is harder to say anything about.
