### ISSUE TITLE
Diff view options are positioned wrong, cannot be selected

### ISSUE THREAD

**Issue by mkbel** [gitextensions/gitextensions#4978]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
In diff tab options previous change, increase number of visible lines, decrease number of visible lines and show entire file buttons are not rendered.

![image](https://user-images.githubusercontent.com/35807926/40382416-b41b7d80-5dfe-11e8-86b6-3d38bbacb012.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Click on diff tab.
Hover mouse somewhere inside diff tab.

**What is the expected behavior?**

![image](https://user-images.githubusercontent.com/35807926/40382607-14ff9668-5dff-11e8-8a82-34ebaab68cd9.png)

**Environment you encounter the issue:**

- GitExtensions version: 2.50-Mono, 2.51.RC1-Mono, 2.51.01-Mono
- GIT version: 
- OS version: GNU/Linux Debian Sid

**Did this work in previous version of GitExtensions (which)?**
Yes, GitExtensions-2.50.02-Mono

**Comment by NikolayXHD** [comment]
ok
