### ISSUE TITLE
gitk should open "External diff" with double click

### ISSUE THREAD

**Issue by bupthebroker** [gitextensions/gitextensions#4981]
Hi,
gitk shows a list of changed files. When right clicking on a file there is a possibility to do "External diff". This right clicking is really bothersome.

"External diff" should be the default double click action. Currently double click does not do anything.

Take a look at TortoiseGit for comparison, it is a super user friendly and great tool, unfortunately not available for Linux.

Thanks in advance

**Comment by gerhardol** [comment]
gitk is not a part of GE, the program is just started from GE.
Please open an issue for Git, as gitk is a part of your git distribution (or maybe a part of your Linux distro).
