### ISSUE TITLE
Revision graph is truncated

### ISSUE THREAD

**Issue by FelixDombek** [gitextensions/gitextensions#4982]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
The graph is truncated after ~1000 lines.

![screenshot from 2018-05-25 16-50-41](https://user-images.githubusercontent.com/552001/40551312-cf249180-603c-11e8-89e1-d25cdaa15780.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In a very big repository, scroll down a bit

**What is the expected behavior?**
The graph is not truncated.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.01
- GIT version: 2.17.0
- OS version: Ubuntu 16.04 LTS

**Did this work in previous version of GitExtensions (which)?**
I don't know.

**Comment by vbjay** [comment]
Scroll down so that goes off screen and then scroll back. Does it stay that
way?  Does the limit number of commits that will be loaded at startup
setting in git extensions tab of settings dialog affect this?

**Comment by FelixDombek** [comment]
Yes, it stays that way. 
The "limit number of commits" that are loaded seems to affect the total number of lines shown, but not how far the graph reaches down if more lines are shown.
Actually, I set this number down to a very small amount and now it seems to stays that way ... I put it back to 1,000,000 but still only see 10 lines after restart. :(

**Comment by drewnoakes** [comment]
@FelixDombek is there a public repo you can reproduce this issue in? I'm not seeing in in the few I checked against.

I'm interested to know if this happens on Ubuntu only.

**Comment by RussKie** [comment]
I am actually observing that if I set a number of commits to be loaded to 100, then close-open 2.51.x version I can't see past certain point...

![scroll issue](https://user-images.githubusercontent.com/4403806/40586691-1f518136-6209-11e8-8c17-68d9a3df1592.gif)

**Comment by FelixDombek** [comment]
@drewnoakes  I get the exact same effect when I view the hadoop repo 
https://github.com/apache/hadoop.git

The graph is only shown up to 12 days back.

**Comment by drewnoakes** [comment]
@FelixDombek could you please try a build of the `v3-ux` branch? It has a bunch of changes to the graph. I cloned the hadoop repo and don't observe the issue you're seeing.

From @RussKie's comments, it might also be a configuration issue.

**Comment by RussKie** [comment]
@drewnoakes I just realised the issue is raised against Ubuntu which is not supported in v3.
I believe the issue is universal and is a bug in our codebase.
