### ISSUE TITLE
RevisionFileTree: "Open with difftool" does nothing if file is unchanged

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#4987]
**Do you want to request a *feature* or report a *bug*?**

bug/inconsistency

**What is the current behavior?**

Opening the difftool for an unchanged file in the RevisionFileTree (or hitting the assigned hotkey "F3") executes "git difftool ..." but nothing happens.
(This context menu item was added with pull request #4848 recently.)

**What is the expected behavior?**

1. I'd prefer to force Git to always open the difftool. But I couldn't figure out how.

2. If it was impossible to force Git, the menu item should be disabled for unchanged files I guess.
I don't like this because it depends on the version of Git or it would be too restrictive when the behavior of "git difftool" would be changed again.

3. Or else the difftool could be started "manually" by parsing the regarding settings, i.e. re-inventing the wheel in GE.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.0, 2.13.0
- OS version: Windows 7

**Did this work in previous version of GitExtensions (which)?**

It worked with the current GE and Git 2.10.1 (from the installation of GE 2.49.03): The difftool popped up with "no differences". (I don't have binaries of Git 2.11 and 2.12.)

**Comment by RussKie** [comment]
Given it is a git issue, I'm not sure there is anything we can/should do. Closing.
