### ISSUE TITLE
Discussion: Remove StyleCop Analysis rule SA1005 (Single line comment should begin with a space)

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#4997]
Are you ok to remove the remove StyleCop Analysis rule SA1005 (Single line comment should begin with a space)?

This rule cause that cause the build to fail (like all the rules, which is a good point) is not very useful and is a big pain because it doesn't comply with the comments done by VisualStudio when commenting lines.

So, if you want to comment a big chunk of code to test something and use Visual Studio to do it, you need to edit **all** the lines to add a space.

What do you think?

**Comment by gerhardol** [comment]
Not decided on what should be done, but use //// for code

**Comment by pmiossec** [comment]
Thanks for the tip.
That's not straight forward for every one but I will use it in the future...

**Comment by drewnoakes** [comment]
VS offers:
- <kbd>Ctrl</kbd>+<kbd>K</kbd>,<kbd>C</kbd>,<kbd>K</kbd>,<kbd>C</kbd> to add a prefix of `////`
- <kbd>Ctrl</kbd>+<kbd>K</kbd>,<kbd>U</kbd>,<kbd>K</kbd>,<kbd>U</kbd> to remove it

I only worked this out today and haven't tried it in practice. Till now I used more `/* */` quotes more often. I use ReSharper via <kbd>Ctrl</kbd>+<kbd>/</kbd> to comment lines which injects `//` at column zero, and I haven't worked out if it can inject `////` conveniently. I will try using the above key trickery from now on, though it's fighting some hard muscle memory.

As for the rule: I'm happy enough with it but don't feel strongly either way. I do like the fact that the code looks consistent throughout. It is definitely a bit less convenient at times.

**Comment by sharwell** [comment]
We generally shouldn't be sending commented-out code in pull requests. I typically do not observe problems related to this warning, which suggests it could be a project-specific workflow issue related to https://github.com/gitextensions/gitextensions/pull/4587#discussion_r172829692.

**Comment by sharwell** [comment]
> I agree ans that's not the problem here....

Yes, we are totally on the same page. My comment was supporting evidence to a conclusion that the error you experienced was a *local* error, not a *pull request* error. The comment I linked to is a previous comment I made suggesting that this could be a problem with a proposed mitigation.

Commenting code is one of the primary scenarios that I don't like to see blocked by this flag.

> Now that I know that I could live with that. But I still wonder of the real usefulness of such rules just to have one space character in comments.

The rule is meant to help prevent commented out code from going unnoticed. In that sense, it's serving exactly the purpose we would want it to serve. If the editor inserted a space automatically during the commenting process, it would somewhat defeat the benefit of this style rule.

**Comment by pmiossec** [comment]
Oh, I better understand the initial goal.
So, my point of view is that for this specific rule, that don't worth the burden ;)

**Comment by RussKie** [comment]
Yes, unfortunately VS doesn't make it easy, but the double comment (`////`) does the trick.
A space after a `//` significantly improves readability and I would be reluctant dropping the rule.

**Comment by pmiossec** [comment]
OK. Thanks, I learn something...

**Comment by vbjay** [comment]
Curious if editorconfig has an option or could get one?

**Comment by RussKie** [comment]
I don't remember seeing anything like this in .editorconfig
