### ISSUE TITLE
Renaming with gitextensions

### ISSUE THREAD

**Issue by yorah** [gitextensions/gitextensions#5]
On the user manual, on page 14:
"When you rename or move a file Git will notice that this file has been moved, but currently Git
Extensions does not show this in the commit dialog. Occasionally you will need to undo the file
change. This can be done in the context menu of any unstaged file."

When I'm renaming a class (file being renamed to match the class name), i can only get Git to do a delete and an add. Rename doesn't seem to work.

Eventually, what do you mean by "Occasionally you will need to undo the file change" ?

**Comment by OvidiuCaba** [comment]
I think this would be a great feature. TortoiseGit has this feature and I really liked it. Also, it seems that Git does not always detects when a file is renamed.

Would it be that hard to implement this feature?

"**it’s good practice to use git mv** so you don’t need to wait for a git add or git commit for Git to be aware of the move and so you have consistent behavior across different versions of Git (which may have differing move auto-detection behavior)."

Source: https://koukia.ca/rename-or-move-files-in-git-e7259bf5a0b7

**Comment by mstv** [comment]
How would you trigger the rename, @OvidiuCaba? Using a context menu item, of course. Though where?

GE does _not_ display a complete file tree of the working directory. So only for modified unstaged files?

And/or in the Explorer?

**Comment by gerhardol** [comment]
Rename is more to present patches than something that is used internally
I have not heard that this has changed the last 10 years

https://marc.info/?l=git&m=119638337122721&w=2

**Comment by OvidiuCaba** [comment]
@mstv , Explorer would be best I think. But if this is hard to achieve, then the context menu in the File Tree tab would be also a good option from a user perspective.

![image](https://user-images.githubusercontent.com/6516996/87157085-572b7380-c2c6-11ea-85d1-456961d3f65b.png)

**Comment by gerhardol** [comment]
Note renaming will be done on the file system items and GE has no view of the file system.
Renaming from File tree or Diff will be limited to the files that also exist on the file system, just like _Show in folder_. But it can be confusing for users if they expect the rename to be done on the selected revision.

**Comment by mstv** [comment]
#671 for the Explorer context menu is on my list, @OvidiuCaba.
