### ISSUE TITLE
Menus cannot be opened on 3rd screen

### ISSUE THREAD

**Issue by FelixDombek** [gitextensions/gitextensions#5000]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
I have three full hd screens next to each other. When Git Extensions is on the rightmost screen, and I open a menu, the menu will appear on the middle screen, aligned all the way to the right.
The menus work as expected when the main window is on one of the other two screens.
When the main window is located the middle of the two screens, so that the menu would be split between screens, it is also moved to be completely on the second screen.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Menus are always opened underneath their respective menu button.

**Environment you encounter the issue:**

 - GitExtensions version: 2.51.01
 - GIT version: 2.17.0
 - OS version: Ubuntu 16.04 LTS

**Did this work in previous version of GitExtensions (which)?**
Don't know.

**Comment by RussKie** [comment]
Some screenshots would go a long way

**Comment by FelixDombek** [comment]
![screenshot from 2018-05-30 18-29-24](https://user-images.githubusercontent.com/552001/40775822-531ce74a-64c9-11e8-92a1-da63c911a095.png)
This shows the screen boundary between 2nd/3rd screen.

**Comment by RussKie** [comment]
Menus and toolbars we use are standard WinForms components, so I would
think this is a Mono-related issue....

I very occasionally run Ubuntu under Parallels on a MBP, so I can't even
try to replicate it.
