### ISSUE TITLE
UnauthorizedAccessException when git-rebase-todo is open at the end of interactive rebase

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#5001]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
During an interactive rebase, if the file `git-rebase-todo` is open in another editor, GitExtensions crashes at the end of the rebase operation with `System.UnauthorizedAccessException`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Run an interactive rebase on any branch and set the first commit operation to `edit`. When rebase stops at it, open file `.git/git-rebase-todo` in a separate editor. Continue the rebase.

**What is the expected behavior?**
GE should handle the exception gracefully.

**Environment you encounter the issue:**

- GitExtensions version: master at 2aaf1d572b776509b79fe6ddc94e55dd40fad84c
- GIT version: 2.17.1.windows.2
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Don't know.

**Comment by RussKie** [comment]
Is there a stack trace available to inspect?

**Comment by crypto-rsa** [comment]
Unfortunately I didn't save it when the exception first occurred and now I am having troubles reproducing the issue (it seems it depends on other circumstances, too). I will try to get it.

**Comment by crypto-rsa** [comment]
```
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at GitCommands.GitModule.GetRebasePatchFiles() in C:\Users\Pavel\Projects\GitExtensions\GitCommands\Git\GitModule.cs:line 2106
   at GitUI.PatchGrid.Initialize() in C:\Users\Pavel\Projects\GitExtensions\GitUI\UserControls\PatchGrid.cs:line 37
   at GitUI.CommandsDialogs.FormRebase.ResolvedClick(Object sender, EventArgs e) in C:\Users\Pavel\Projects\GitExtensions\GitUI\CommandsDialogs\FormRebase.cs:line 189
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.PerformClick()
   at System.Windows.Forms.Form.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

**Comment by crypto-rsa** [comment]
Steps to reproduce:

1. Open this [repository](https://github.com/gitextensions/gitextensions/files/2057944/RebaseTest.zip)
2. Rebase branch `source` onto `master` interactively
3. When the merge conflict appears, open `.git/git-rebase-todo` in a separate editor
4. Solve the conflict(s) and continue rebasing

**Comment by drewnoakes** [comment]
Are you on Linux/OSX? Are you editing the file as the same user GE runs as? What file permissions does the file have?

The exception implies that `GitModule.GetRebasePatchFiles` is attempting to open a file it does not have access to one of the files in the "git rebase" directory (`.git/rebase-merge`, `.git/rebase-apply` or `.git/rebase`).

I think API quirk was fixed in .NET Core (i.e. returns what you _can_ actually read). For full framework we might be able to use [`Directory.EnumerateFiles`](https://docs.microsoft.com/en-us/dotnet/api/system.io.directory.enumeratefiles?view=netframework-4.7.1) instead, though I haven't tried it.

**Comment by crypto-rsa** [comment]
I am on Windows 10, as stated in the issue description.
However, I opened the file from a file manager application which runs as _Administrator_ while GE is running as a normal user.

**Comment by drewnoakes** [comment]
> I am on Windows 10, as stated in the issue description.

Apologies, I overlooked that.

> opened the file from a file manager application which runs as Administrator

Then I suspect that's the problem, and I don't think there's a workaround or that this is a bug. GE running as the user cannot read files it does not have permission to read.

Can you see anything that GE could reasonably be doing in this situation?

**Comment by vbjay** [comment]
Run GE as administrator.

**Comment by drewnoakes** [comment]
> Run GE as administrator

This might work, but may also make further problems. In general I think it's bad policy to have files in the `.git` folder with different accessibilities/ownerships.

**Comment by vbjay** [comment]
Fully agree. More of a diagnostic. If it works, then it's his problem, not
ours.

**Comment by drewnoakes** [comment]
@crypto-rsa please say if you see a reason this issue shouldn't be closed. Thanks.

**Comment by crypto-rsa** [comment]
Hmm, I am not sure whether _"not our problem"_ is the correct approach here. There is a reliable way to crash the application. Shouldn't we attempt to handle it? Like putting the `Directory.GetFiles` call in a `try` block and just return an empty list from `GetRebasePatchFiles` if an exception is thrown? Would this create problems further down the call stack?

**Comment by RussKie** [comment]
Perhaps I'm missing something, what is the use case where a user needs to open open `.git/git-rebase-todo` in a separate editor while rebase is in progress?

**Comment by crypto-rsa** [comment]
I think I did it because I was solving some merge conflict in fixup commits and I wanted to check the contents of the commits still to be applied. So I needed to get their hashes. And doing it from a file manager which I had already open was faster than opening the `git` console and running `git rebase --edit-todo`.

**Comment by RussKie** [comment]
Right, sounds like not so common use case everybody be doing.
As you proposed earlier we can add a try..catch to account for this.
Would you like to volunteer? 😉

**Comment by crypto-rsa** [comment]
Yes, I'll give it a `try` :-) I was just under the impression that the other commenters don't want GE to take _any_ action to mitigate the issue which kind of surprised me.

**Comment by vbjay** [comment]
Not what I was saying. What I meant was if he was using it in a way that
was obviously not going to work. It is a file that shouldn't be open
because git will modify it and need to read it. It's like having a code
file open in notepad and trying to delete it in file explorer.

**Comment by crypto-rsa** [comment]
> obviously not going to work

In hindsight, yes - but not until I realized that the file manager is running as Administrator. Anyway, I think a bit of defensive code wouldn't hurt. Hope we can agree on that.

**Comment by drewnoakes** [comment]
For my taste I'd just wrap the exception at an appropriate place in the stack and wrap it with a new exception that explains what's going on. Right now the user would only have a vague hint from the exception type.

**Comment by RussKie** [comment]
Agree

**Comment by crypto-rsa** [comment]
Do you mean just letting GE show the exception form with an explanatory message? Any suggestions about the wording?

**Comment by RussKie** [comment]
If I read it correctly, Drew meant the following:

```
catch (UnauthorizedAccessException ex)
{
    thrown new FileLoadException("Unable to open .git/git-rebase-todo. Please unlock the file and restart the app.", ex)
}
```

This will still crash the app, but at least the error would be more meaningful. 

@drewnoakes can you please confirm?


PS: The error would need to be translatable.

**Comment by crypto-rsa** [comment]
Yes, will do so shortly (but probably not today).
