### ISSUE TITLE
missing Mono installer for 2.51.02

### ISSUE THREAD

**Issue by strotz** [gitextensions/gitextensions#5006]
could not find  GitExtensions-2.51.02-Mono.zip

**Comment by vbjay** [comment]
See #4415

**Comment by vbjay** [comment]
You can build from source and edit GitExtensions.exe.config and change isportable to true.

**Comment by strotz** [comment]
would be nice to mention in release notes

**Comment by RussKie** [comment]
Jay: 2.51 branch support Mono.

Aexei: the Mono version is available, it has been renamed to
GitExtensions-2.51.02-portable.zip
