### ISSUE TITLE
Customized window size is not kept

### ISSUE THREAD

**Issue by Bartizan** [gitextensions/gitextensions#5021]
It seems there is a **bug**.

**What is the current behavior?**
A size of windows are not kept. The windows: dashboard, repository, commit (maybe more).

**Steps to reproduce**
_Scenario 1_
- open Git Extension (click by "Git Extensions" shortcut in menu);
- resize the window and exit the app.;
- open again and check if the chosen size is kept.

_Scenario 2_
- open the commit dialogue, resize it, close it either way;
- open the commit dialogue again and check if the your size is kept.

**What is the expected behavior?**
The customized window size should be kept.

**Environment you encounter the issue:**

- GitExtensions version: **2.51.02**
- GIT version: 2.17.1
- OS version: Microsoft Windows [Version 10.0.16299.431]

**Did this work in previous version of GitExtensions (which)?**
It worked fine in the previous version 2.51.01

Thanks in advance
AA

**Comment by Danand** [comment]
Experiencing the same problem there. Commit dialog size is resetting everytime in 2.51.02.
Good job with removing unnecessary installation parts! But new bug is very annoying.

**Comment by RussKie** [comment]
Indeed, it appears the regression was introduced in cbb66f4a739642f47bc26d63a378fcee72126ce4 (#3828).

**Comment by RussKie** [comment]
Can you please test this build and confirm the fix https://ci.appveyor.com/api/buildjobs/mqe0ejmitah6fc6s/artifacts/GitExtensions-2.51.01.2748-Mono.zip

**Comment by pmme** [comment]
> Can you please test this build and confirm the fix https://ci.appveyor.com/api/buildjobs/mqe0ejmitah6fc6s/artifacts/GitExtensions-2.51.01.2748-Mono.zip

2.51.01.2748 worked correctly for me. 
(Also the "Clean working directory" form did not grow.)
This was on Windows 7 sp1 with 2 x normal 96DPI displays.

**Comment by Bartizan** [comment]
>Can you please test this build and confirm the fix https://ci.appveyor.com/api/buildjobs/mqe0ejmitah6fc6s/artifacts/GitExtensions-2.51.01.2748-Mono.zip
It is fixed for me. 
Tested on Win10, no custom scaling.
With regards to "Clean working directory" dialogue, like pmme mentioned, it did not grow. However I also does not use it that much so never faced such a problem. Thanks.

**Comment by RussKie** [comment]
Thanks fellows

**Comment by mycroes** [comment]
Any ETA on a release that incorporates this fix?

**Comment by RussKie** [comment]
I will try to get 2.51.03 out within few weeks.

**Comment by drewnoakes** [comment]
In the meantime you can always try out a CI build:

https://github.com/gitextensions/gitextensions/wiki/CI-Builds
