### ISSUE TITLE
Remove support for RevisionGrid layouts

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5026]
The `RevisionGrid` control supports multiple layouts.

I strongly suspect that most users don't know this, and use the default layout.

I kinda wonder whether _anyone_ uses a non-default layout. Does anyone reading this do so?

### Layouts

Many of the layouts look completely broken. Here's what they look like in 2.51.02, and they look much the same on `master`.

You can cycle layouts by pressing <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>L</kbd>, or via the "View" menu.

![image](https://user-images.githubusercontent.com/350947/40947413-747d7960-685a-11e8-93eb-20ab707bf20a.png)

![image](https://user-images.githubusercontent.com/350947/40947425-7e6e72f8-685a-11e8-9db3-6a878902efb8.png)

![image](https://user-images.githubusercontent.com/350947/40947430-8b27da8e-685a-11e8-9b76-7729fa9dacb1.png)

![image](https://user-images.githubusercontent.com/350947/40947434-928f6e04-685a-11e8-8d3b-b289e940d0ba.png)

![image](https://user-images.githubusercontent.com/350947/40947443-9da8473e-685a-11e8-9ed9-1b025125fa0f.png)

![image](https://user-images.githubusercontent.com/350947/40947456-a8c31d4c-685a-11e8-8c65-284604d4ee56.png)

![image](https://user-images.githubusercontent.com/350947/40947463-b2dcdc5a-685a-11e8-8c0e-a0e8dfc48035.png)

![image](https://user-images.githubusercontent.com/350947/40947470-ba34cf4e-685a-11e8-897b-75e49c258eb8.png)

### Proposal

Remove the ability to change the layout. Have one good layout. Reduce the volume of code considerably. No one will notice :)

I've got a branch going with some tidying of `RevisionGrid`. That's such a huge class, with over 300 members (excluding the designer file). If this proposal gains support, I will do the necessary surgery on that branch and create a PR.

---

### Environment

GitExtensions version: 2.51.02, `master`
OS version: Windows 10

**Comment by vbjay** [comment]
I do.

**Comment by vbjay** [comment]
Instead. Make it more visible.

**Comment by drewnoakes** [comment]
Which layout do you use? Do they look this broken for you? To me the non-broken layouts look pretty much the same.

**Comment by vbjay** [comment]
Some of them you have to force a refresh before it looks right.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/40948743-2ddf8d80-6838-11e8-8c6c-4f9851a9ea34.png)

**Comment by RussKie** [comment]
I second the removal motion.
I have started extraction of the  rendering logic from the grid, but it was
a slow and very difficult process...
I'd rather have a single working good looking layout with a clean
separation of concerns, and then add new layouts later.

**Comment by jbialobr** [comment]
I also support single layout, especially taking into account switching from WinForms to sth else.

**Comment by gerhardol** [comment]
Single layout. 
A colleague got one of the semi-broken layouts somehow and did not know how to get it back. This can of course occur for any customization, but there is not much point in delivering broken layouts.

**Comment by drewnoakes** [comment]
I should have time today to experiment with this. Will report back with findings.

**Comment by drewnoakes** [comment]
@vbjay could you explain some more about what the tile view gives you? Then we can explore whether there's a way of bringing some of that into a single layout. To me it looks nice enough aesthetically, but I wouldn't use it due to its low information density.

**Comment by vbjay** [comment]
I like it because it does give me less commits. It lets me focus on each
commit instead of seeing a ton of them. I have a scroll wheel.

**Comment by pmiossec** [comment]
I'm Ok to remove too.
Also, under high dpi all others are either:
* completely broken
* nearly the same than the default one
* display not clear data and could induce comprehension errors

For example, this all flat layout :

![image](https://user-images.githubusercontent.com/460196/40971485-15063c9c-68be-11e8-9c3d-5418da7218e4.png)
We can't understand which commit belong to which branch. Using the option "Show current branch only" make a lot more sense...

**Comment by vbjay** [comment]
There are multiple layouts. Cycle through each one and then hit refresh.

**Comment by pmiossec** [comment]
@vbjay I did it once I read your previous comment and that don't change a lot of things.
There are mostly broken even after a refresh under high dpi screen :(

**Comment by vbjay** [comment]
Well the high dpi could be the issue. The layouts may not work well like a
lot of things with high dpi.  I don't have a high dpi display. The only
issue I face with the layouts is the selected commit font color. White
against that gradient causes the commit text to disappear.

**Comment by drewnoakes** [comment]
@pmiossec thanks for pointing out that we would remove a large bunch of high DPI bugs.

@vbjay

> It lets me focus on each commit instead of seeing a ton of them. 

Perhaps we can introduce a density setting to let the user choose how visually dense the revision grid is. Would that help achieve what you're after.

In a similar spirit, moving to a single grid presentation style allows us to focus on making it as great to use as possible, while resisting adding too many user options. This will be easier to realise if we have less code to consider.

I have some progress on this but it's blocked a bit behind #5029. I'll fix that first.

**Comment by drewnoakes** [comment]
> The only issue I face with the layouts is the selected commit font color. White against that gradient causes the commit text to disappear.

This is a problem with many of the non-default layouts. The default layout works well with selections.

**Comment by vbjay** [comment]
I also like the gravatar image on the commits.  If we can maybe have 2.
One with the commit lines, and the commit lines with gravatar on commits.

**Comment by drewnoakes** [comment]
> I also like the gravatar image on the commits

We could add it as a column to the grid, and still have only one layout. There are existing settings that toggle column visibilities, so we can add one more.

Such a column would probably only look decent if the density was turned down.

**Comment by pmiossec** [comment]
>>I also like the gravatar image on the commits

>We could add it as a column to the grid

I also think that it should be a column displayed for example just before the Author column...

**Comment by drewnoakes** [comment]
Thinking longer term we could add a column chooser, where you can control which columns are visible and their order in the grid.

**Comment by vbjay** [comment]
Those suggestions together
- Density control
- Gravatar column
- Column chooser, and position
would make it work.

**Comment by RussKie** [comment]
Alright, it looks like we are all mostly on the same page. Let's deprecate
all layouts except the default one until such time when we are happy with
it, then we can revisit the desire to add more layouts.
As discussed earlier, the default layout can be enhanced, if desired.
Please be mindful of the feature-creep though.
Timeline-wise I propose the deprecation to target v3.0, everything else to
target v3.x


>  The only issue I face with the layouts is the selected commit
> font color. White against that gradient causes the commit
> text to disappear.

This bug needs to be fixed one way or another. I believe there is an issue
in the backlog.
