### ISSUE TITLE
NRE at launch on master after updating Windows 10

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5029]
### Category

Bug?

### Summary

Browse form fails to load with a NRE on dereferencing `BuildServerWatcher` in `RevisionGrid.ForceRefreshRevisions`:

https://github.com/gitextensions/gitextensions/blob/9cd7479535e57779769d0c2dd9cbbe51a944f581/GitUI/UserControls/RevisionGrid.cs#L1139

### Steps to Reproduce

Just run GitExtensions and the exception happens right away.

### Details

I thought this was something I'd done on my branch so tried to bisect. I observe it in current `master` and earlier. Then I realised I updated my PC overnight.

It's also possible that there's a problem with GE config, so I will try moving them out too to see if it helps.

`BuildServerWatcher` is initialised in the control's override of `OnCreateControl`, so possibly something changed in the underlying framework with regards to event ordering. By contrast, `ForceRefreshRevisions` is called in `Load`

### Environment

- GitExtensions version: `master` (observed as far back as 2ec99c701)
- GIT version: 2.17.1.windows.2
- OS version: Windows 10  1803 (OS build 17134.81)

**Comment by drewnoakes** [comment]
Has anyone else on Windows 10 also updated to the same version?

**Comment by RussKie** [comment]
One of mine is still at 1709, I'll check the other one later and let you
know.

May need to create a new label "W10 1803" :D

**Comment by arnaud-fabre** [comment]
I just updated my box to that version, and did not hit the issue. It might depend on the way the build integration is setup?
