### ISSUE TITLE
Some default settings should be changed

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#5030]
There are some settings that I think that the default value is not well chosen.
And to improve the discoverability and because that's easier to disable a feature than enabling it because we don't know it exists, I think that the default value should be changed.

I could think about 3 at the moment.

- "Mark ill formed lines" in the commit form (commit message field) to turn it on by default. To enforce good git convention message (very few are aware of the good convention)
- "Show SHA-1" in the revision grid (I show it multiple times and devs found it very convenient once they know it ;) )
- "Show indicator for multiline message" in the revision grid

What do you think about?
Are there others?

**Comment by drewnoakes** [comment]
I like all of these proposals and will keep an eye out for other defaults we may like to change.

Can you move the idea about abbreviated SHA-1 in the grid to a new issue please? It would likely be a separate PR to one about default settings.

What's required to reset my settings to factory defaults? I'd like to share the unboxing experience.

**Comment by drewnoakes** [comment]
"Show relative date" seems quite nice.

**Comment by gerhardol** [comment]
> What do you think about displaying only the abbreviated sha1 in the revision grid?
> Show SHA-1" in the revision grid (I show it multiple times and devs found it very convenient once they know it ;) )

Show abrivated in list, copy full?

> "Show relative date" seems quite nice.

No, you loose the precision

**Comment by pmiossec** [comment]
>Doesn't git already give you the shortest it can tray is unique. Shortest is still variable length.

No. there is an option of the `git log` command to get the abbreviated sha1

**Comment by vbjay** [comment]
I know. What I mean is that option still provides uniqueness.

**Comment by vbjay** [comment]
https://stackoverflow.com/questions/18134627/how-much-of-a-git-sha-is-generally-considered-necessary-to-uniquely-identify-a

**Comment by RussKie** [comment]
I believe "relative dates" is on by default. I don't mind it personally.
Sha1 in the grid? I never had it on, don't care either way. I think the
font for Sha1 is different from the rest and needs to be aligned.

**Comment by pmiossec** [comment]
let's continue the discussion about the short sha1 in #5032

**Comment by pmiossec** [comment]
>I believe "relative dates" is on by default. I don't mind it personally. 

same for me...

**Comment by WildBamboo** [comment]
I'm not sure if this is considered a "default setting" or not, but I would very much appreciate it if after every upgrade Git Extensions does NOT adjust or add a default editor to my `.gitconfig` file.

**Comment by RussKie** [comment]
Please raise a separate  issue for this.

**Comment by drewnoakes** [comment]
Can we close this?
