### ISSUE TITLE
Displaying only the abbreviated sha1 in the revision grid

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#5032]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

There is an option to display the sha1 in the revision grid but that display the complete sha1.
Which is not absolutely needed to display 

**What is the expected behavior?**

Display the abbreviated sha1 to use less width in the grid.
But still keep the full sha1 when using the copy feature

**Comment by drewnoakes** [comment]
There's rarely a need to see the whole hash.

Note that #5017 (which I'm reviewing now) adds tooltips for any grid cell that is truncated when drawn. This means that you can 'abbreviate' the SHA-1 column by resizing it, and still see the full hash in a tooltip on hover. Copy still places the whole hash in the clipboard too.

**Comment by RussKie** [comment]
Do you mean this - #4420?

**Comment by pmiossec** [comment]
>There's rarely a need to see the whole hash.

That's the point. If we need it, we could click on the commit line.

> This means that you can 'abbreviate' the SHA-1 column by resizing it

The point is that, as human, I don't know what is the good size (and it is here provided by git). And there are the trailing useless "..." displayed.

> Copy still places the whole hash in the clipboard too.

We should keep that...

>Do you mean this - #4420?

More or less. The `git log` has an option to return the abbreviated commit hash (%h: abbreviated commit hash) so we don't need to calculate the good length ourselves.

So, for #4420, surely that we should ask for an abbreviated sha1 at the start of the application and keep the length for all other displays (and not dynamically calculate ourselves).

**Comment by pmiossec** [comment]
>I believe "relative dates" is on by default. I don't mind it personally. 

same for me...

@RussKie 
> I think the font for Sha1 is different from the rest and needs to be aligned.

It's a monospace font. I imagine it's to have all sha1 with the same length.
I won't fight for that but I like it like that. And I find that this font give a meaning of "technical" data (surely because that we are used to in source code...)

**Comment by RussKie** [comment]
It just looks inconsistent.

**Comment by gerhardol** [comment]
While it is possible to change the width of the column, the setting will change when resizing the form.
So this will be nice.

Full sha still available in copy, tooltip and committab.

**Comment by pmiossec** [comment]
@vbjay Not sure to understand the meaning of your comment...

`git log` return abbreviated sha1 of the same length for all the commits and that's what we want. No need to have abbreviated sha1 of different length...

**Comment by vbjay** [comment]
My point is that short is NOT a constant length.  Your config value just happens to be a size that makes it the same length.  

Try this:
```bash
git log --pretty=format:%h>beforemod.txt
git config core.abbrev 4
git log --pretty=format:%h>aftermod.txt
git config --unset core.abbrev
```
https://git-scm.com/docs/git-config#git-config-coreabbrev

**Comment by vbjay** [comment]
Git will expand the short length to be unique upon generation per sha.

**Comment by vbjay** [comment]
You can't know if the user has modified that config value.  Do you get it now?

**Comment by pmiossec** [comment]
>You can't know if the user has modified that config value. Do you get it now?

And? Should we really care? 

If the setting is not set (which should be nearly 100% of the gitextensions users) , git calculate a length and all the values are displayed with the same length. 

And if the user set the setting, we follow it, just for display purpose, in the revision grid. 

What is wrong?

**Comment by vbjay** [comment]
I'm thinking of the column being too short for the longer values.

**Comment by RussKie** [comment]
That depends on a monitor :) on hidpi ones there's plenty of space

**Comment by RussKie** [comment]
As much as love consistency, in this particular case I don't really care if some hashes are 4- or 6-long, if they are given to me by git automatically.
I don't think I know a single developer who set `core.abbrev` explicitly

**Comment by vbjay** [comment]
Yes the short value is short but it can be dynamic. It depends on how many commits are in the repo. Try https://github.com/dotnet/docs. My point is that it should autofit based on the current longest sha in the column or show an ellipsis.  Just making sure that nobody assumes that the length is the same.

**Comment by pmiossec** [comment]
There is already an ellipsis displayed automatically (but I find that it don't work perfectly and could have been displayed earlier)

**Comment by vbjay** [comment]
That config value isn't the only thing.
https://public-inbox.org/git/CA+55aFy0_pwtFOYS1Tmnxipw9ZkRNCQHmoYyegO00pjMiZQfbg@mail.gmail.com/

**Comment by vbjay** [comment]
The ellipsis is fine. What I didn't want to happen is someone note the
short sha and it be a conflict because they only referenced the part of the
sha they could see. Also, I wanted to orefent the assuming that was going
on.

**Comment by RussKie** [comment]
Related #4420
Related #4271
