### ISSUE TITLE
GitHub Issues: Label for regression

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5035]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Hard to differ between new and existing issues

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Yet another label, to mark a regression (since last release or maybe a recent release

**Environment you encounter the issue:**

- GitExtensions version: all

**Comment by RussKie** [comment]
You can just create it 😉
