### ISSUE TITLE
Jenkins: build info sha for other repos are not filtered

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5038]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Jenkins build info contains the sha of the repo triggering the build, but may also contain other related commits for other URLs. For instance, for multi branch pipeline builds the build script can be specified in a shared library, just referenced with a branch name. The commit of the related library is therefore included in the buildinfo.

The plugin currently tries to add all sha in the build info to GE. This is a waste of resources as these commits will never be found in the current repo.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
You need a repo with multi branch pipeline and sharedlib. No known public repo with this setup.

**What is the expected behavior?**
Limit wasted resources.

**Environment you encounter the issue:**

- GitExtensions version: all

**Did this work in previous version of GitExtensions (which)?**
Multibranch pipeline since 2.51

**Comment by gerhardol** [comment]
A patch for the problem, checking the URL. However, I am not too happy with the solution, the solution probably need to be configurable. Either to opt-in or to specify the URLs to ignore. Both of these solutions are too hard to explain and document why I am not pursuing a PR. The solution I have used for some time enclosed, if someone has better ideas.

[0001-Jenkins-Ignore-sha-for-URL-not-matching-the-current-.patch.txt](https://github.com/gitextensions/gitextensions/files/2075870/0001-Jenkins-Ignore-sha-for-URL-not-matching-the-current-.patch.txt)

I will submit a PR with some minor changes though.

**Comment by RussKie** [comment]
I think @jbialobr uses Jenkins, perhaps he can chime in.
