### ISSUE TITLE
.NET 4.7.2 upgrade

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5039]
Given that we no longer tied to Mono, I propose we upgrade to the latest .NET framework.
Thoughts?

Related: #3611

**Comment by drewnoakes** [comment]
Do we have any metrics on framework usage via the crash reporter?

**Comment by RussKie** [comment]
Not that I am aware of.
Accordinh to docs 4.7.2 is included in W10.1803 and can be installed as far
as W7.

**Comment by drewnoakes** [comment]
We will lose some percentage of users that are required to install a newer version of .NET just to use Git Extensions.

The question is what are those two percentages?

Many GE users will not be .NET developers.

Metrics would be useful.

What happens when someone sends an error report from the UI?

**Comment by sharwell** [comment]
The bigger question for me is why?

**Comment by drewnoakes** [comment]
Haha, yes that's a good question to ask. RussKie, was there some part of the framework you wanted to use?

There were some [high DPI fixes](https://github.com/Microsoft/dotnet/issues/374) in 4.6.2 and 4.7. They won't benefit all users and if I understand correctly don't require targetting, just installation.

We might consider holding off until later in the year for .NET Core 3.0, which is slated to have WinForms/WPF support. .NET Core supports stand alone deployment (basically bundling .NET Core with the application) too, so we can stop requiring users to have a specific framework installed (at least in one installer version). .NET Core seems to be quite a bit snappier in some benchmarks, though it's unclear whether that'd apply to GE.

**Comment by RussKie** [comment]
Yes, hidpi support.
