### ISSUE TITLE
Commit dialogue shows international filenames in incorrect encoding

### ISSUE THREAD

**Issue by AntonD-mobilmir** [gitextensions/gitextensions#5048]
bug

Commit dialogue shows international filenames in incorrect encoding, and cannot open them (neither show diff, nor "Open folder" or "Open in diff tool" via context menu).

**Environment you encounter the issue:**

- GitExtensions version: 2.51.02
- GIT version: 2.17.1.2
- OS version: 10.0.17134.81

Did this work in previous version of GitExtensions (which)? yes, 2.51.01

**Comment by palver123** [comment]
It seems to be working on my computer:
![image](https://user-images.githubusercontent.com/12460850/41564347-cdd347f8-7352-11e8-950b-ee2cca68d735.png)

- GitExtensions version: 2.51.02
- GIT version: 2.17.1.2
- OS version: Windows 10 Enterprise ( 10.16299)

**Comment by AntonD-mobilmir** [comment]
After some investigating, it seems it's more complex issue that I first thought.

Here's how it should look (screenshot from my Explorer):
![image](https://user-images.githubusercontent.com/7845465/41581311-ccebbf42-73a6-11e8-8ca0-e6a2bef6187a.png)

*GIT GUI* shows filename correctly, but garbles file contents:
![image](https://user-images.githubusercontent.com/7845465/41581739-2d089476-73a8-11e8-9763-a8fe3be40f12.png)

git status shows backslash-encoded filename:

```
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        test.txt
        "\320\277\321\200\320\276\320\262\320\265\321\200\320\272\320\260.txt"

nothing added to commit but untracked files present (use "git add" to track)
```

no `.gitattributes` in git or repo dir.

`git config -l`

```
core.symlinks=true
core.autocrlf=false
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=C:/Program Files (x86)/Git/mingw32/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
core.editor=nano.exe
merge.tool=kdiff3
mergetool.kdiff3.path=C:/Program Files (x86)/KDiff3/kdiff3.exe
diff.guitool=kdiff3
difftool.kdiff3.path=C:/Program Files (x86)/KDiff3/kdiff3.exe
core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
user.name=AntonD-mobilmir
user.email=*****mir.ru
winupdater.recentlyseenversion=2.17.1.windows.2
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
```

`git config --global -l`

```
merge.tool=kdiff3
mergetool.kdiff3.path=C:/Program Files (x86)/KDiff3/kdiff3.exe
diff.guitool=kdiff3
difftool.kdiff3.path=C:/Program Files (x86)/KDiff3/kdiff3.exe
core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
user.name=AntonD-mobilmir
user.email=*******lmir.ru
winupdater.recentlyseenversion=2.17.1.windows.2
```

> My system locale and input language is Hungarian, but my display language is English US.

same, but with ru/en
![image](https://user-images.githubusercontent.com/7845465/41581889-c35d4c14-73a8-11e8-8953-6203f3050749.png)

locale for non-unicode programs may also play it's role, and it's Russian in my case (meaning ANSI CP1251 / OEM CP 866)
![image](https://user-images.githubusercontent.com/7845465/41582028-211e0b54-73a9-11e8-8dc9-afb3e1ffdf18.png)

**Comment by AntonD-mobilmir** [comment]
well,

```
git config --global core.quotepath off
```

fixed that.

Thanks everyone :)

**Comment by jbialobr** [comment]
@AntonD-mobilmir Could you show the output for the following command:

`git status --porcelain -z --untracked-files`

**Comment by AntonD-mobilmir** [comment]
```
MINGW64 ~/Git/test (master)
$ git status --porcelain -z --untracked-files
?? test.txt?? проверка.txt
```

**Comment by jbialobr** [comment]
Thank you! It is not about unescaping octal codes. It is about determining the encoding that git produces output in.

**Comment by RussKie** [comment]
@Janusz: is there anything we can do to mitigate the problem?

**Comment by AntonD-mobilmir** [comment]
strange. I set `gui.encoding=utf-8` before setting `core.quotepath=off`, but it didn't do anything at first. But now GitExtensions shows filename correctly even with `core.quotepath=on`.
I'm not sure what is happening.
