### ISSUE TITLE
Regression: Ctrl+C on the revision grid no longer copy the hash of the commit

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#5049]
**Do you want to request a *feature* or report a *bug*?**
bug.

**What is the current behavior?**

- Ctrl+C on the revision grid no longer copy the hash of the commit (Introduced by #4925).
Instead, it copies all the data of the selected line

**What is the expected behavior?**
Ctrl+C on the revision grid no longer copy the hash

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
Yes, ~~v2.52~~ v2.51.02

**Comment by pmiossec** [comment]
//cc @szaliszali ?

**Comment by szaliszali** [comment]
thanks for notification, I can check this in the weekend

**Comment by pmiossec** [comment]
> thanks for notification, I can check this in the weekend

👍
