### ISSUE TITLE
Github Plugin Unable to Create Pull Request

### ISSUE THREAD

**Issue by ELJIE** [gitextensions/gitextensions#5051]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
the `your branch` drop down is empty and everytime I create a pull request, the errors occur

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
able to create pull request using github plugin

**Environment you encounter the issue:**

- GitExtensions version: 2.52.02
- GIT version: 2.17.1
- OS version:  windows 10 1803

**Did this work in previous version of GitExtensions (which)?**

![image](https://user-images.githubusercontent.com/21689260/41109188-f5f20dc6-6aa8-11e8-9b5a-32521ff0a624.png)
#

**Comment by vbjay** [comment]
Make sure you have  valid token in the settings of the github plugin.

**Comment by ELJIE** [comment]
thanks :)
