### ISSUE TITLE
"Commit template settings" popup is broken under high dpi

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#5059]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

We can't see the bottom controls and we must resize vertically (if we get what's wrong! It takes me some times to understand because I knew the popup...) to see all of them

Actual:
![image](https://user-images.githubusercontent.com/460196/41235848-f97cf46c-6d8f-11e8-82c5-8171ad7fd883.png)

**What is the expected behavior?**

Something like:
![image](https://user-images.githubusercontent.com/460196/41236005-536c31e0-6d90-11e8-9611-7414275db99f.png)

**Environment you encounter the issue:**

- GitExtensions version: master
- OS version: Win10

**Did this work in previous version of GitExtensions (which)?**
I don't think so...

**Comment by RussKie** [comment]
I think this issue is related to #5098.

Would you like to try to fix it? I think it may be a matter of applying `AdjustForDpiScaling()` to the form...

**Comment by drewnoakes** [comment]
This was fixed as part of #5087, where we apply DPI scaling to all GE form/control subtypes.

![image](https://user-images.githubusercontent.com/350947/43224707-e8092d5e-904e-11e8-8f83-3b54765dacc5.png)
