### ISSUE TITLE
Git-status in the background should use --no-optional-locks

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5066]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Git-status also running in the background can conflict with interactive commands.
The best solution would be to run git-status in only the background, but that will require some tweaking to the rules, so that interactive git-status can use the background status without too much delay.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not easy to reproduce, requires that git-status is slow and interactive git-status is started while background command is running.

**What is the expected behavior?**
git-status in the background should not block interactive commands.
Git 2.15.2 adds support for --no-optional-locks

**Environment you encounter the issue:**

- GitExtensions version: all

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by RussKie** [comment]
Waiting for v2.51 fix
