### ISSUE TITLE
Bug Since 2.51.02 Git Extension no longer remembers size of main or commit window.

### ISSUE THREAD

**Issue by rluiten** [gitextensions/gitextensions#5069]
Thanks for git extensions its a good tool.

**What is the current behavior?**

If I change size of main git extension window or the commit window and close git extensions the size of both windows reverts to the default.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

As above.

**What is the expected behavior?**

That quitting and starting Git Extensions will restore its previous two window locations and sizes.
The commit window has never remembered its previous location but it used to remember its size.
The main window has always remembered its previous location and size.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.02
- GIT version: git version 2.17.1.windows.2 
- OS version: Windows 10 Enterprise 1709

**Did this work in previous version of GitExtensions (which)?**

Yes it worked fine in 2.51.01, I have reverted to 2.51.01 for now as having to resize windows every launch isn't helping my work flow.

**Comment by vbjay** [comment]
Search issues before posting your own.

**Comment by rluiten** [comment]
Sorry @vbjay , logged this after the other one, and plain forgot to look for related issues on this one.

**Comment by RussKie** [comment]
Duplicate of #5021
