### ISSUE TITLE
Very sluggish response when changing focus between panels for large repository

### ISSUE THREAD

**Issue by wplpgr** [gitextensions/gitextensions#5074]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Moving the mouse between commit tree panel and branch tree panel of the UI has very poor response. The mouse pointer moves quickly, but actions when moving into a new panel are sluggish (in my case, delays of 4 seconds or more before clicks seem to register).

Looking at ProcessExplorer, each time I move between those panels (without clicking on anything), it appears to launch "git branch -a--contains", which suggests that GitModule.GetAllBranchesWhichContainGivenCommit() is being fired on entry events.

On my machine, with a recently "git gc"'d repository, "git branch -a --contains" takes about 4.5 seconds.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

We have a large-ish repository (around 2GiB), with many 10's of thousand first-parent commits on master, and multiple release branches, and multiple feature branches.
This problem is not apparent on (for example) the gitextensions repository, where "git branch -a --contains" is quick.

1. Open the repository.
2. Hover over a commit in the commit tree view panel.
3. Move into the branch tree view panel.
4. Click on a branch.
5. Go back to the commit tree view panel.
6. Click on a commit.

I don't think that the "click on ..." is actually required - I can see the "git" command being triggered without it.

The same problem seems to when the branch tree panel is turned off when moving between bottom panel and the commit tree panel, but it's a little bit more temperamental.

**What is the expected behavior?**

Not being slow.

**Environment you encounter the issue:**

- GitExtensions version: master fa860cdfda35d663a90d0a9955a6f95854191ba6
- GIT version: git-for-windows 2.17.1.windows.2
- OS version: Windows 10 (1703)

**Did this work in previous version of GitExtensions (which)?**

It did in 2.50.01 (yes, I know it's an old version - I've been building the master version since that was installed :smile:)

**Comment by drewnoakes** [comment]
EOD here and logging off, but I suspect this is related to recent tool tip changes in #5017 that trigger actions on every mouse move. Specifically I think it's only when you move the mouse over the graph.

I have a pending fix as part of larger work around the revision grid and hope to get a PR in soon.
