### ISSUE TITLE
GE hangs when moving mouse over the commits graph

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5075]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

GetAllBranchesWhichContainGivenCommit takes 8 secs to complete, which causes UI to freeze.

10:52:35.5061910  8387ms git.exe branch -a --contains 5db8673997e29c051d925b82a424b20de39a04b7

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open a big repo.
2. Move mouse over the commits graph.

**What is the expected behavior?**

No freeze.

**Environment you encounter the issue:**

- GitExtensions version: fa860cdfda35d663a90d0a9955a6f95854191ba6

**Did this work in previous version of GitExtensions (which)?**
Yes, beofre https://github.com/gitextensions/gitextensions/pull/5017

**Comment by vbjay** [comment]
See #5074

**Comment by jbialobr** [comment]
Duplicate of #5074
