### ISSUE TITLE
Change the order of revision's refs shown in the revisions grid

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5076]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Tags are shown before branches.

**What is the expected behavior?**

I propose the following order of the refs:
1. bisect info
2. local branches
3. remote branches
4. other refs

Before:
![gitext](https://user-images.githubusercontent.com/1003909/41345772-de31c64e-6f04-11e8-9a81-123805a4d440.png)
After:
![gitext](https://user-images.githubusercontent.com/1003909/41345794-e94377c6-6f04-11e8-8fa9-5721331b912d.png)

**Comment by gerhardol** [comment]
I would prefer:
1. bisect info
2. checked out local branch
3. tracked remote branch
4. local branches
5. remote branches
6. other refs

Really 3 that is the difference. Another way to see if remote is synced would be another symbol than filled/open arrow (double arrow?)

**Comment by vbjay** [comment]
Allow user to specify the order.

**Comment by RussKie** [comment]
I don't really have an opinion.
Though I would avoid more configurations, unless absolutely necessary - we
already have too many of them.

**Comment by vbjay** [comment]
What's the problem?  Just the two of you have different views on what it
should be.  I'm sure others have different orderings.  Add a listbox and
move up/down functionality to the settings.  When rendering, use the order
of the items in settings.  Provide a sensible default.

**Comment by RussKie** [comment]
The problem is implementation that looks good and works well for different
dpi

**Comment by gerhardol** [comment]
I do not want to have a configuration here, it is not above my threshold (it is nice to be able to configure, but also intimidates users).
Just had an opinion,, we should select something and go with it.

**Comment by jbialobr** [comment]
>Just the two of you have different views on what it should be. 

I wouldn't say so. The order @gerhardol proposed makes sense for me. Mine is decent for my needs, @gerhardol's one is even better, but the difference would be noticeable only occasionally, hence I don't want to put the additional effort into this.
