### ISSUE TITLE
NRE on 'b' or 'h' in FileStatusList filtered to no items

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5083]
**Do you want to request a *feature* or report a *bug*?**

Bug.

Relates to #5065.

**What is the current behavior?**

Typing `b` or `h` into the _Diff_ tab's file list when no items exist in the list (due to filtering) causes a NRE 

> Void fileHistoryDiffToolstripMenuItem_Click(System.Object, System.EventArgs) @ GitUI.CommandsDialogs.RevisionDiff

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

![image](https://user-images.githubusercontent.com/350947/41458379-5c122f20-707e-11e8-909b-5a345f14613e.png)

In the browse form, select a commit, then the diff tab, enter filter text until no files are shown, give the list focus, press 'h' or 'b'.

**What is the expected behavior?**

No exception. Nothing else should happen.

**Environment you encounter the issue:**

- GitExtensions version: master a3695217a2671cafec9043f083e57ec47224f3b1

**Did this work in previous version of GitExtensions (which)?**

Don't know.

**Comment by wplpgr** [comment]
I don't think that is just after filtering - if the diff window has files listed in it, and you deselect them all (with nothing in the filter box), it will crash.
