### ISSUE TITLE
Dashboard refinements 

### ISSUE THREAD

**Issue by francoas** [gitextensions/gitextensions#5084]
**Do you want to request a *feature* or report a *bug*?**

Both

As stated in #3693

1. ~In the picture below (from a real case) I noticed that some categories can be collapsed (red arrows) while other can't (purple arrows)~ #5093 

2. ~When hovering with the mouse, if I quickly move the mouse from a focused repo (blu background) to the left bar, the repo doesn't lose the focus and it continues to show the blue background, even if I hover onto another. In the image I managed to make blue-backgrounded the repos pointed by the orange arrows~ #5531

3. Each repo in a category has a third line with a gray label (green light arrow) repeating the category name (green thick arrow). One "clear" example in the last category (gt). This is redudant, it doesn't add information and it is space consuming.

![image](https://user-images.githubusercontent.com/3007941/41476087-cb778c88-70c0-11e8-9d71-79b3a0f36b73.png)

- GitExtensions version: 

3.0

**Comment by RussKie** [comment]
@francoas could you please test and confirm the fix for non-collapsible categories
https://ci.appveyor.com/api/buildjobs/fri5m6e4gj2bvij5/artifacts/GitExtensions-Portable-3.00.00.2826.zip
thank you

**Comment by francoas** [comment]
@RussKie I confirm: non collapsable issue fixed! thank you

**Comment by RussKie** [comment]
@NikolayXHD if you have capacity and inclination, would you mind having a go at the point 2 - mouse hover artifacts?

**Comment by NikolayXHD** [comment]
@RussKie I wouldn't mind at all :)

**Comment by RussKie** [comment]
Sold!

**Comment by NikolayXHD** [comment]
As to 3. maybe we should paint category in Recent repositories list where it's not a duplicate information?

**Comment by RussKie** [comment]
@francoas: @NikolayXHD has made a fix for the 2nd issue; could you test https://ci.appveyor.com/api/buildjobs/istahys3tfrmobnk/artifacts/GitExtensions-Portable-3.00.00.3608.zip

**Comment by RussKie** [comment]
For the 3rd item:

> As to 3. maybe we should paint category in Recent repositories list where it's not a duplicate information?

I like the suggestion.

Open to other suggestions as to what may be useful info to display as the last row.

/cc: @gitextensions/git-extensions-source

**Comment by francoas** [comment]
> @francoas: @NikolayXHD has made a fix for the 2nd issue; could you test https://ci.appveyor.com/api/buildjobs/istahys3tfrmobnk/artifacts/GitExtensions-Portable-3.00.00.3608.zip

Tested. Thumb up.

**Comment by francoas** [comment]
> For the 3rd item:
> 
> > As to 3. maybe we should paint category in Recent repositories list where it's not a duplicate information?
> 
> I like the suggestion.
> 
> Open to other suggestions as to what may be useful info to display as the last row.
> 

Two rows is ok and makes the list more readable.
About useful suggestions... you already know my wish: to show pending commit. pending push and pending pull (sourcetree like), but you have already explained me it's a time-expensive task

**Comment by RussKie** [comment]
Ok, let's have two items for now.
We can revisit the 3rd row after v3 is released.

**Comment by francoas** [comment]
> Ok, let's have two items for now.
> We can revisit the 3rd row after v3 is released.

thumb up

**Comment by RussKie** [comment]
@francoas are you happy with this?
https://ci.appveyor.com/api/buildjobs/r681pas5mmkq8df6/artifacts/GitExtensions-Portable-3.00.00.3636.zip

**Comment by francoas** [comment]
> @francoas are you happy with this?
> https://ci.appveyor.com/api/buildjobs/r681pas5mmkq8df6/artifacts/GitExtensions-Portable-3.00.00.3636.zip

Yes... much better for the eye
