### ISSUE TITLE
Cannot see GitExt menu in VS2017

### ISSUE THREAD

**Issue by palver123** [gitextensions/gitextensions#5089]
Hi!

I've recently updated from Visual Studio 2015 to VS2017 and was very sad to realize the GitExtensions VS integration is not available. I have tried installing and reinstalling GitExtensions multiple times but no luck. The installer suggests that GitExt is available for VS2017.

**Do you want to request a *feature* or report a *bug*?**
It depends... is this a bug or a missing feature?

**What is the current behavior?**
There is no _GitExt_ in Visual Studio 2017 menu. Only in Visual Studio 2015's menu.
![image](https://user-images.githubusercontent.com/12460850/41549934-a143830e-7327-11e8-8fa9-7aad138a76c7.png)

**What is the expected behavior?**
The menu should show up in both Visual Studio versions

**Environment you encounter the issue:**
- GitExtensions version: 2.51.02
- GIT version: 2.17.1.2
- OS version: Windows 10 Enterprise ( 10.16299)
- .NET version: 4.7.02556
- VS2017 version: 15.7.3

**Comment by vbjay** [comment]
It's in the marketplace.

**Comment by RussKie** [comment]
Please see the repo's front page for all the links.

**Comment by palver123** [comment]
My bad, sorry!
