### ISSUE TITLE
Increase minimum Git version to 2.11

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5106]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
GE has a minimum Git version of 2.9 (release June 2016). This limit is set in both 2.51 and 3.0.
The limit is a "soft limit", older versions should work too.

**What is the expected behavior?**
Git 2.11 (Jan 2017) adds further information to git-status (--porcelain v2) that can improve for instance the status display (see #5104 ). Using 2.11 as minimum version will however be a hard limit or the porcelain=1 parsing must be maintained too.

**Environment you encounter the issue:**
- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by RussKie** [comment]
Last night I started prep'ing 2.51.03 release, please merge asap

**Comment by gerhardol** [comment]
I intend this for 3.0 branch, keep 2.9 as minimum for 2.51 as there is no specific reason to update there
For 3.0 we need to have a way forward, hard limit (cut old code), soft limit (silent compatibility) or not raise the limit.

**Comment by RussKie** [comment]
Sounds good

**Comment by vbjay** [comment]
Frankly, with the security issue, I say it should be 2.17.2

**Comment by gerhardol** [comment]
> Frankly, with the security issue, I say it should be 2.17.2. See #5110

Latest 2.17 is 2.17.1 (2)
https://github.com/git-for-windows/git/releases
2.18.0 has a new credential manager, no listed security issues so no obvious reason yet.
We should wait some days to use 2.18 (for instance 2.16 was not stable until after over a month)

**Comment by vbjay** [comment]
That's what I meant. Goofed on the version number.

**Comment by gerhardol** [comment]
Increasing the Git version with a hard limit of 2.11 will simplify tests, but compatibility can be kept also with #5104

**Comment by RussKie** [comment]
Gerhard let's proceed.

**Comment by gerhardol** [comment]
Raised #5226 to increase soft limit, not removing older support.
@RussKie  Do you want that too?

Wiki updated

**Comment by RussKie** [comment]
Thank you
