### ISSUE TITLE
Select the master branch by default in Github plugin

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#5109]
**Do you want to request a *feature* or report a *bug*?**
Feature request. Or an improvement, to be precise.

**What is the current behavior?**
Currently, when creating a new Pull request via Github plugin, it select the first branch (from alphabetically sorted branches, I guess) which is not useful because almost always you'd want to create a PR against the master branch.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* Fork a repository that contains multiple branches
* Open it in GitEx
* Commit something to your fork 
* Open _Github_ -> _Create pull requests..._ dialog
* All fields will be substituted correctly except the _Target branch_ field will be filled with a first branch of the original repository

**What is the expected behavior?**
I believe that it would be more useful and convenient to pre-select the "master" branch by default.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.02
- GIT version:  2.17.1.windows.2
- OS version: Microsoft Windows [Version 6.1.7601]
- .NET version: no idea

**Did this work in previous version of GitExtensions (which)?**
No, all previous versions behave in the same way, apparently.

**Comment by vbjay** [comment]
Actually.  Github has the idea of a default branch.  It is not required to
be master.  The better idea would be to select what github says, is the
default branch.
