### ISSUE TITLE
plugin menu entries are repeated many times

### ISSUE THREAD

**Issue by francoas** [gitextensions/gitextensions#5112]
**Do you want to request a *feature* or report a *bug*?**

bug 

**What is the current behavior?**

every time I open the plugin menu its  menu entry voices are added again, over and over, ending up in a very long menu with the same voices repeated many times 
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Just cal git extensions and open the plugin menu... many times

- GitExtensions version: 3.0
- OS version: Windows 8.1

![image](https://user-images.githubusercontent.com/3007941/41779403-ffab75d4-7631-11e8-95df-71b36d9318e6.png)

**Comment by RussKie** [comment]
LOL indeed :) Thank you Franco

**Comment by vbjay** [comment]
Git bisect

**Comment by RussKie** [comment]
If it isn't observed in the master I won't be spending time digging through
the stale commits...

**Comment by drewnoakes** [comment]
Actually I do see this on the v3-ux branch, though it only occurs occasionally, and when it does the list of plugins repeats twice. Further opening/closing of the menu does not add more items.

> Git bisect

This would be very hard to bisect, as it's non-deterministic.

This is likely a race condition.

**Comment by drewnoakes** [comment]
Looks like it's not a race condition. It appears to happen when changing the repo in the browse form. Therefore the problem can be easily bisected.

**Comment by RussKie** [comment]
Thanks Drew, the bug can be observed at 11f9ea38ce78af526c1e93e25c5e1421941689bb

**Comment by drewnoakes** [comment]
Ran a bisect while watching a film. The behaviour was introduced in 05d4bcdb3ea1c76654e11ccdf77b495f877525a6.

**Comment by RussKie** [comment]
I had a quick look during the commute, I don't think we should be
reinitialising plugins on repo change.
I think the fix would be pretty trivial.

**Comment by vbjay** [comment]
As long as not reinitializing doesn't make the plugins use the old repo
info.

**Comment by RussKie** [comment]
I don't believe it does. Have a look at #5130
