### ISSUE TITLE
Commit dialog inconsistently renders its dropdowns

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5115]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
The "commit message" dropdown icons have significantly different dimensions than items in the other dropdowns on the form.

![issue](https://user-images.githubusercontent.com/4403806/41811612-3aaf8592-7756-11e8-8fa4-1a2293eceb77.gif)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Scale Windows to 200%. 
For example, my scaling configuration:
![image](https://user-images.githubusercontent.com/4403806/41658222-12006000-74d9-11e8-8044-578e27a678a1.png)

**What is the expected behavior?**
All elements across all dropdowns have consistent dimensions

**Environment you encounter the issue:** 
- GitExtensions version: master @ 9bee0c34d72ec38fe1eb514e09c8bb00a7bc38f0
- OS version: W10 scaled

**Comment by drewnoakes** [comment]
I see this excessive padding on the "commit message" drop down too, at 200% scaling, though only occasionally.

Sometimes it works:

![image](https://user-images.githubusercontent.com/350947/43224274-b31e4d14-904d-11e8-8873-720068d02ce4.png)

In fact I can't repro it at the moment. But I believe the problem still exists. Next time I see it I'll post a screen shot and we can try to work out if there's a pattern.
