### ISSUE TITLE
Inconsistent "GitExt Browse" icon

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5117]
**Do you want to request a *feature* or report a *bug*?**

inconsistency

**What is the current behavior?**

The icon for "GitExt Browse" in the Explorer context menu is different from the one of the dialog it will open.
![grafik](https://user-images.githubusercontent.com/36601201/41824384-6adc9e08-780f-11e8-9f37-0a6a9d64e253.png)
![grafik](https://user-images.githubusercontent.com/36601201/41824389-80ec4982-780f-11e8-8584-a69409bb6469.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

right click a folder with a repository in the Explorer

**What is the expected behavior?**

I'd prefer the "browse" icon instead of the "folder" symbol in the Explorer context menu.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.windows.2
- OS version: Windows 7
- .NET version: N/A

**Did this work in previous version of GitExtensions (which)?**

no

**Comment by RussKie** [comment]
There is one more inconsistency:

![image](https://user-images.githubusercontent.com/4403806/42153298-0d670f8e-7e26-11e8-8162-1dbf051c2be4.png)

**Comment by mstv** [comment]
Sorry, I'm a little bit confused now.
The current master revision seems to use the icon Bin\Logo\git-extensions-logo-final_**mixed**.ico.
I see on Windows 7 with "small icons" for the Windows Task Bar:
* attached to the Task Bar, not running: ![grafik](https://user-images.githubusercontent.com/36601201/42186735-05d781cc-7e4e-11e8-8f20-3d851aeecfc7.png); running: ![grafik](https://user-images.githubusercontent.com/36601201/42186773-261af05e-7e4e-11e8-8a2c-837d1c082334.png)
* commit dialog: ![grafik](https://user-images.githubusercontent.com/36601201/42186900-8a53d18a-7e4e-11e8-8377-586cba8ca0df.png)

(With version 2.49.03 which was the last version I installed using the installer, it was opposite:
![grafik](https://user-images.githubusercontent.com/36601201/42188919-3d115372-7e56-11e8-9e67-e0fe34c45fa1.png) ![grafik](https://user-images.githubusercontent.com/36601201/42188977-6dc45686-7e56-11e8-93e0-f7ea45368440.png) ![grafik](https://user-images.githubusercontent.com/36601201/42189023-a9c51f08-7e56-11e8-849a-d63eb4306e89.png).)

Which icons do you expect?
1. small Task Bar icon: ![grafik](https://user-images.githubusercontent.com/36601201/42188919-3d115372-7e56-11e8-9e67-e0fe34c45fa1.png)?
1. shell context menu: ![grafik](https://user-images.githubusercontent.com/36601201/42189514-d26c7346-7e58-11e8-92bb-5a7ddd0d36d0.png)?
This is **not perfect** because the same icon appears twice.
1. submodule context menu of File Tree: ![grafik](https://user-images.githubusercontent.com/36601201/42189619-6b5e7950-7e59-11e8-8372-2d28064c3723.png)?

This would mean to use the non-mixed icon Bin\Logo\git-extensions-logo-final.ico for all these three occurrences, wouldn't it?

**Comment by drewnoakes** [comment]
I think your taskbar is caching an old icon when nothing is running, and using the application's icon when is is running.

The ability to customise the application icon was removed recently.

The simpler X-like icon was my favourite, especially at small sizes. It looks a lot more polished and professional than the full logo, for icons at least. I would vote for an altogether new icon for the 3.0 release, even if heavily inspired by the current logo.

**Comment by RussKie** [comment]
Icon customisation was removed in https://github.com/gitextensions/gitextensions/pull/5081/commits/62826652d258c85c6d1e9e0c59754d9ece422e1e.
I don't have problems with replacing the icon

**Comment by gerhardol** [comment]
Just remove the usages of git-extensions-logo* (png/ico) and git-extensions-icon.ico?
cow icons are no longer used too...

**Comment by mstv** [comment]
I take to the X-like icon, too.
What kind of changes to the icon are you thinking of, @drewnoakes? Who will create it?

**Comment by drewnoakes** [comment]
I played around with the SVG logo a little in InkScape. I didn't actually change anything significant, just moved things around a bit.

Since doing this I've come to prefer the simple X arrow for use across board. It's much stronger.

### Before

![image](https://user-images.githubusercontent.com/350947/42295620-431c1312-7fe4-11e8-8edd-f125e111b444.png)

### After

![image](https://user-images.githubusercontent.com/350947/42295607-12b83c64-7fe4-11e8-8c95-7cb1fb5b1f5c.png)

---

Some of the G glyphs I considered.

![image](https://user-images.githubusercontent.com/350947/42295710-19e2b93c-7fe5-11e8-8995-02135441e5b8.png)

---

I prefer the X icon now. For everything. I'll make some tweaks to it.

We can probably keep the current 16px version however.

I'm happy to change the icon in #5087 to avoid conflicts. I've organised the resources a bit.

**Comment by drewnoakes** [comment]
As mentioned above, I think I prefer the X icon. What do people think?

Here are some variations on the theme.

![image](https://user-images.githubusercontent.com/350947/42296407-86f78770-7fed-11e8-95f2-6ae4dd18c1d3.png)

![image](https://user-images.githubusercontent.com/350947/42296446-0079a01a-7fee-11e8-8e96-c3dabb23b1e8.png)

**Comment by gerhardol** [comment]
6a
Just considering green over red (primary a column), as that gives a sense of going forward.

**Comment by RussKie** [comment]
3A or 2B for me

**Comment by drewnoakes** [comment]
Given two votes for gapless icons (I prefer also), I've put together a .ico file with several resolutions and added it to the project in #5087. I've removed a bunch of unused logo stuff and tested that the icon looks consistent in many places.

The distinction between shadowed and non-shadowed icons is lost at most usual resolutions. It's only visible large on the about form and the README.

@RussKie do you want to use this logo on the dashboard? The space allotted has a letterbox aspect which might be tricky with a square icon. Maybe we pop some text to the side (quick mockup):

![image](https://user-images.githubusercontent.com/350947/42408668-7ec6226a-81c7-11e8-831e-8305d32614ed.png)


Some screenshots:

![image](https://user-images.githubusercontent.com/350947/42408672-9dfcad20-81c7-11e8-851e-df44d57e7b5c.png)

![image](https://user-images.githubusercontent.com/350947/42408908-14849834-81ca-11e8-93e4-965385b35245.png)

![image](https://user-images.githubusercontent.com/350947/42408678-c08ccb22-81c7-11e8-86fa-8e28763f7b48.png)

![image](https://user-images.githubusercontent.com/350947/42408691-e2864abe-81c7-11e8-84f3-44fcb9f2de4d.png)

**Comment by gerhardol** [comment]
@spdr870 @KindDragon @jbialobr @sharwell @pmiossec @EbenZhang @vbjay 
Other maintainers, top contributors and top posters:
Any opinions on using one (slightly updated) icon?

**Comment by mstv** [comment]
Regarding the initial question about the shell extension menu (context menu in the Explorer):
How shall it look like?

old | A | B | C
-- | - | - | -
![grafik](https://user-images.githubusercontent.com/36601201/41824384-6adc9e08-780f-11e8-9f37-0a6a9d64e253.png) | ![grafik](https://user-images.githubusercontent.com/36601201/42419899-a69c2608-82bd-11e8-8dfd-df4940f2e352.png) | ![grafik](https://user-images.githubusercontent.com/36601201/42419905-cb2506ca-82bd-11e8-8c22-b2b11088e4f9.png) | ?

Variant B is most consistent with the (identical) icons of the Browse window and of the application.
But I'd like to avoid the duplicate icon. Thoughts?

**Comment by drewnoakes** [comment]
@mstv you're right that #5087 doesn't fix this issue. I've removed the reference so that this will stay open.

Not sure what icon is best. I don't use the shell extension. Can you post a screenshot showing the "Git Extensions" submenu items too please? That might help understand what icon would be best suited there, or if we can change the text/semantics.

**Comment by mstv** [comment]
After changing the text, the inconsistency would remain for me:
> The icon for "GitExt Browse" in the Explorer context menu is different from the one of the dialog it will open.

I use this menu item quite often when switching between multiple copies of the same repository with different build configuration options. I always must look twice whether it's the correct item. It distracts me from what I really intend to do.
IMO it's the most important menu item because it opens the main view of GE. That's why it should have the same icon, particularly considering that the icon symbolizes the graph of branches now.

**Comment by RussKie** [comment]
With the UI uplift merged in, let's resume the discussion.
May be we can have a combined icon of a folder with the helix for 'GitEx Browse, will it work for you?

Writing from a phone, can't offer a mock

**Comment by mstv** [comment]
(Sorry for the delay due to vacation and toolchain issues.)

I agree with your proposals regarding both text and icon. How do you like ![grafik](https://user-images.githubusercontent.com/36601201/44313467-c1ed1080-a409-11e8-9a1f-e93e35534941.png)?

**Comment by RussKie** [comment]
Works for me

**Comment by drewnoakes** [comment]
We have a similar icon on the dashboard, showing a folder and the GE logo. Would be nice to keep them consistent.

**Comment by drewnoakes** [comment]
Check out `folder-open` or `folder-horizontal-open` from the fugue icon set (we use it in many places now):

https://raw.githubusercontent.com/yusukekamiyamane/fugue-icons/master/all-shadowless.png

It could have a small version of the GE logo embedded within the folder.

**Comment by mrexodia** [comment]
Please restore the original folder icon for 'Browse' in the shell extension. The current one is inconsistent with the visual studio extension and it is not better in any way than the previous one in my opinion.

**Comment by gerhardol** [comment]
The VSIX icons are updated too.
The plugin is included with GE but not yet on market place (there may by minor changes in the release).

**Comment by mrexodia** [comment]
I installed with the setup and the extension was not update in visual
studio, perhaps that’s another bug then...

**Comment by gerhardol** [comment]
I do not think the extensions installs automatically (should probably be removed from the installer)
