### ISSUE TITLE
Allow the removal of cached files after they have been added to the gitIgnore file

### ISSUE THREAD

**Issue by DesHorsley** [gitextensions/gitextensions#5118]
**Do you want to request a *feature* or report a *bug*?**
Feature 

**What is the current behavior?**
It doesn't seem like there is a way to remove cached items when ignoring a file that has already been committed. To do this the console needs to be opened and the following needs to be run:
`git rm -cached <fileName>`
or 
`git rm -r --cached <folderName>`

Further reading on [rm --cached](https://git-scm.com/docs/git-rm)

This is convenient if a file has mistakenly been added to the repo that should not be tracked.

**What is the expected behavior?**
It would be great if there was a context menu in the commit dialog to remove a file from the cache if its currently being ignored.
This could utilize a similar dialog to "Add file(s) to .gitignore". 
It could present a command to remove that particular file from the cache, and allow the user to modify the command to remove the entire folder if they wish. The preview from that dialog is great, and I think would fit will with this feature.

**Environment you encounter the issue:**

- GitExtensions version: 2.50.02
- GIT version: 2.15.1.windows.2

**Did this work in previous version of GitExtensions (which)?**
No

**Comment by vbjay** [comment]
Click the drop-down above the unstaged section.

**Comment by vbjay** [comment]
Try show ignored files.

**Comment by gerhardol** [comment]
rm --cached is moving a file from index(staged) to work tree (unstaged).

**Comment by pmiossec** [comment]
I have added this feature some time ago so this could be done from the 'filetree' in the browse form.

**Comment by pmiossec** [comment]
I don't have access to a computer but, from what I remember, it should be "stop tracking this file" that you get from the contextual menu of the file you want to ignore (and this is the feature you ask for ;-))

**Comment by pmiossec** [comment]
But perhaps you should update your version of gitextensions (that is not the last one released)

**Comment by DesHorsley** [comment]
UH! Fantastic, thanks @pmiossec, `assume unchanged` seems to be the ticket, in the context menu in the commit dialog.

Awesome, thanks very much.

**Comment by vbjay** [comment]
Assume unchanged is not what you want. It is temporary.

**Comment by vbjay** [comment]
https://stackoverflow.com/questions/13630849/git-difference-between-assume-unchanged-and-skip-worktree

**Comment by pmiossec** [comment]
>assume unchanged seems to be the ticket, in the context menu in the commit dialog.

This feature should not be used and I already asked to remove it.

Once again, update Gitextensions!

You will find the 2 features that could solve your problem.

Either "stop tracking" (from the filetree) or "skip-work tree" (from the commit form if you want to still track the file even if modified, but it seems not the one you originally ask for)

**Comment by vbjay** [comment]
We shouldn't remove assume unchanged. We just need to provide information
on the difference.

**Comment by pmiossec** [comment]
I already explained that once (and added the information as tooltip in Gitextensions hoping that user never used it) but if you see a file in the commit form, that is that you should **not** use 'assume-unchanged' but prefer 'skip-worktree'.

So, yes, if we want to do well or stuff, we must remove the context menu item "assume unchanged this file" (and only that one. I don't remember exactly the label).

And I have already put 'assume-unchanged' in the right place where it should be used, which is the file tree (for use on file that has not changed, so that can't appear in the commit dialog and that are costly to get status, the real goal of this feature).

You could read the first answer of the link you provide on the subject ;-)

**Comment by pmiossec** [comment]
Great!
So, if it's solved, please close the issue.
