### ISSUE TITLE
Error on push deleting a remote branch when a tag with the same name exists

### ISSUE THREAD

**Issue by alekseysshubin** [gitextensions/gitextensions#5119]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you have a remote branch and a tag with the same name, and you try to delete the remote branch using right-click menu, the operation fails with the following console output:
```
"C:\Program Files\Git\bin\git.exe" push origin  :"branch-name"
error: dst refspec branchname matches more than one.
error: failed to push some refs to 'https://remote-url'
Done
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Have a remote branch and a remote tag with exactly the same names.
2. Right-click on the branch in the main (commits) view.
3. Select Delete branch - remote/branch-name
4. Observe the error in the console output window.

**What is the expected behavior?**
The remote branch should be deleted without an error. The git command should include the full path: `"C:\Program Files\Git\bin\git.exe" push origin  :"refs/heads/branch-name"`.

**Environment you encounter the issue:**
- GitExtensions version: 2.51.02
- GIT version: 2.17.1
- OS version: Windows 10 Pro x64 version 1803
- .NET version: 4.7.2

**Did this work in previous version of GitExtensions (which)?**
I haven't tried it. There is the same bug closed a few years ago [#1551](https://github.com/gitextensions/gitextensions/issues/1551), but the problem reproduces on the latest version. A slight difference is that on 1551 it was reproduced using Push > Push multiple branches.
UPD: the problem doesn't reproduce when using Push multiple branches dialog.

**Comment by drewnoakes** [comment]
Seems like you know the fix here. Can you make a PR?

**Comment by RussKie** [comment]
Just to check, is there the same problem with deleting tags?

**Comment by RussKie** [comment]
Could you please send the same PR to the master branch as well? Thanks
