### ISSUE TITLE
RevisionGrid Graph: Show more informative tooltips

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5125]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

tooltip with commit hash of wrong lane
![grafik](https://user-images.githubusercontent.com/36601201/40630849-a62fc5f0-62d6-11e8-905a-5e22c63a6a0a.png)

**What is the expected behavior?**

commit hash, [*later:* branches contained in / being at] and commit heading of lane under mouse
![grafik](https://user-images.githubusercontent.com/36601201/40631074-140b5f92-62d9-11e8-9258-9e25ab6c45a8.png)
![grafik](https://user-images.githubusercontent.com/36601201/40631122-8c268902-62d9-11e8-9dfc-86fdbdf50da5.png)
![grafik](https://user-images.githubusercontent.com/36601201/40631154-0ca97e22-62da-11e8-8cdd-ddbdf7a8f3fc.png)

**Environment you encounter the issue:**

- GitExtensions version: v3-ux, master
- GIT version: N/A (2.17.windows.2)
- OS version: N/A (Windows 7)
- .NET version: N/A

**Did this work in previous version of GitExtensions (which)?**

PR #5017 but with high load by firing git.exe for display of branch info

**Comment by gerhardol** [comment]
When hovering the branches, I expect to see branch information, probably tags too. (not like this in v3-ux branch)

When hovering the commit headline I expect to get a tooltip also when there is a one line message (especially when branch tags are replacing the message).

**Comment by mstv** [comment]
> When hovering the branches, I expect to see branch information, probably tags too. (not like this in v3-ux branch)

I agree, the whole commit message seems to be too much.
I would prefer "committed to branch xy". But Git does not store this information by design.
Retrieving the same branch information as for the Commit Info, proved to be too expensive (causing too much load by firing git.exe).
The information on branches (and tags) can be extracted from the graph's nodes and junctions (without firing git.exe). But this will take a while to implement. That's why I wrote "*later*" above.
Which branches should be selected for display in the tooltip? In which order should they be listed?

> When hovering the commit headline I expect to get a tooltip also when there is a one line message (especially when branch tags are replacing the message).

I get such a tooltip when the message is truncated.

**Comment by pmme** [comment]
I believe the resolution for this issue will resolve https://github.com/gitextensions/gitextensions/issues/4450

**Comment by gerhardol** [comment]
Branch lane is low prio and later as you wrote. Just a clean view with commit is OK for me.
I would like to have this as the overflow area for all branch heads and tags, as some may not be visible on the message line. Other than that, the info in the commit tab would be good. But do not slow down normal operation.

For commit message, I suggest the message is displayed for consistency. Otherwise you might wonder why youget tool tip for some lines and not for others.
