### ISSUE TITLE
A number of changed files on Commit button is always '2'

### ISSUE THREAD

**Issue by yegor-mialyk** [gitextensions/gitextensions#5127]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

A number of changed files on Commit button is always '2' irrespective whether you have them or not.

![commit](https://user-images.githubusercontent.com/16239726/42113848-a95fd57e-7ba1-11e8-9abf-d077392a54fe.jpg)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

In my case it reproduces in every repository I have. I tried to reset settings by deleting C:\Users\<User>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings but the issue is still there.

**What is the expected behavior?**

A number of changed files on Commit button should reflect an actual number of changed files in repository.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.03
- GIT version: 2.18
- OS version: Windows 10 x64
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

2.51.02

**Comment by gerhardol** [comment]
Corrected in #5126

**Comment by gerhardol** [comment]
See the PR for a test build.

**Comment by RussKie** [comment]
The test build https://ci.appveyor.com/api/buildjobs/m4nmwfcjscrmxo8v/artifacts/GitExtensions-2.51.01.2909-Mono.zip
