### ISSUE TITLE
Files with question mark after cloning repositorie

### ISSUE THREAD

**Issue by kalvis84** [gitextensions/gitextensions#5131]
**Do you want to request a *feature* or report a *bug*?**
Bug.
**What is the current behavior?**
After cloning some repositories, I have exclamation mark on it without doing any changes. Thee are some files with question marks. Git extension does not see any changes and there is no option to find out why it behaves like this.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It happens on some repositories in my work. I can not provide them. I only clone this repositories using "clone repositories" menu in git extension.
**What is the expected behavior?**
If there is really something wrong with repositories, than git extension should have some status dialogue that shows why it marks those files (question marks) after cloning.
**Environment you encounter the issue:**
Git extension version: 2.50.02
git version 2.12.2.windows.1
windows 7 64.

- GitExtensions version: 2.50.02
- GIT version:  2.12.2.windows.1
- OS version:  windows 7 64 sp1
- .NET version: 4.0

**Did this work in previous version of GitExtensions (which)?**
I do not know.

SCREENSHOTS:
![clipboard3](https://user-images.githubusercontent.com/28363614/42161789-a0e2eaa0-7dfc-11e8-8a1f-01422209caba.png)
![clipboard02](https://user-images.githubusercontent.com/28363614/42161791-a597d736-7dfc-11e8-9743-9138a643127d.png)

**Comment by RussKie** [comment]
Screenshots?

**Comment by kalvis84** [comment]
I have added Screenshots.

**Comment by RussKie** [comment]
> ![clipboard3](https://user-images.githubusercontent.com/28363614/42161789-a0e2eaa0-7dfc-11e8-8a1f-01422209caba.png)

Where is this screenshot from?

**Comment by kalvis84** [comment]
it is from windows explorer. ITEMS is the main repository folder. Files with questionmarks are from the inside of this folder.

**Comment by RussKie** [comment]
I don't think it is anything to do with GE, we don't install or use Windows Explorer overlays.
Do you have any other git client installed (like TortoiseGit)?

**Comment by kalvis84** [comment]
Yes, I have tortoise. After removing it, all marks gone. I thought it was GE. Thanks for  your help. I can close this issue now.
