### ISSUE TITLE
Delete obsolete branches UI layout bug

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5146]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Layout of `DeleteUnusedBranchesForm` (from the Delete Obsolete Branches plugin) is broken.

![image](https://user-images.githubusercontent.com/350947/42423371-f300856a-82f0-11e8-9511-67d3627c9e54.png)

**Environment you encounter the issue:**

- GitExtensions version: v3-ux (probably on master too)
- GIT version: N/A
- OS version: Win 10
- .NET version: 4.7.2
- Scaling: 200%

**Comment by RussKie** [comment]
I believe this bug directly relates to #5098

**Comment by hieuxlu** [comment]
@RussKie I can reproduce this at 250% scale. If you can assign me, I could look into it while I'm working on improving this plugin's performance. Thanks.
