### ISSUE TITLE
Proposal: Delete "Commits per user" feature

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5148]
Idea.

![image](https://user-images.githubusercontent.com/350947/42423443-1e310754-82f2-11e8-87e3-860116660fa3.png)

The functionality of this "Commits by user" feature is duplicated in the "Statistics" plugin.

![image](https://user-images.githubusercontent.com/350947/42423456-703c2d26-82f2-11e8-998e-ebf3432eeb1b.png)

Can we delete the tool? It looks a bit out of place here anyway.

**Comment by gerhardol** [comment]
Agree

**Comment by RussKie** [comment]
+1
