### ISSUE TITLE
Repo object tree icons

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5149]
**Do you want to request a *feature* or report a *bug*?**

Discussion

**What is the current behavior?**

The repo objects tree has monochrome icons that look very different to the rest of GE's icons.

![image](https://user-images.githubusercontent.com/350947/42441139-7825a810-835f-11e8-97f8-22dcbb5d8d6c.png)

The fugue icon set does not really have a good icon for a git branch. But it has some bits and pieces that can be re-appropriated.

Here is a potential change:

![image](https://user-images.githubusercontent.com/350947/42441026-2b36d40c-835f-11e8-83ab-d5ad09612166.png)

What do people think?

**Comment by RussKie** [comment]
Nice!

**Comment by drewnoakes** [comment]
There is also a little more spacing between the rows. What do you think of that?

WinForms is so hacky. To get that spacing we have to add padding to the ImageList images by redrawing them at runtime. So hacky.

`ListView` icons don't render their transparency properly when their tree item is selected.

Potential candidate for #4972 in future.

**Comment by RussKie** [comment]
I think it is fine

**Comment by drewnoakes** [comment]
Spent some time in Gimp and put together a few groups:

![image](https://user-images.githubusercontent.com/350947/42450013-b8d6a614-837a-11e8-8d10-6e09fb3fa330.png)

![image](https://user-images.githubusercontent.com/350947/42450386-dd3ed2c8-837b-11e8-8344-0b55b559420f.png)

---

In action:

![image](https://user-images.githubusercontent.com/350947/42450895-860b4fac-837d-11e8-9e14-2498201f93cf.png)

**Comment by RussKie** [comment]
Awesome work

**Comment by drewnoakes** [comment]
Changed the "Show this branch only" icon:

![image](https://user-images.githubusercontent.com/350947/42453996-47e0ca8c-8386-11e8-9be5-a4cd3e2999b7.png)
