### ISSUE TITLE
Icon of changed files shows 2 all the time

### ISSUE THREAD

**Issue by KSemenenko** [gitextensions/gitextensions#5158]
Icon of changed files - shows that there are 2 modified files. but the file window is empty.
Also shows 2 files if the changed files are much larger.

- GitExtensions version: 2.51.03
- GIT version: git version 2.17.1.windows.1
- OS version: Windows 10
- .NET version: 4.7

**Comment by drewnoakes** [comment]
https://github.com/gitextensions/gitextensions/releases/tag/v2.51.04

#5127

**Comment by RussKie** [comment]
Duplicate of #5127
