### ISSUE TITLE
Disable auto resolve conflicts

### ISSUE THREAD

**Issue by GLeBaTi** [gitextensions/gitextensions#5160]
Hello. Can i disable auto resolve conflicts in gitextensions? I want manualy control conflict resolving

**Comment by vbjay** [comment]
We have an issue template for a reason.  You need to be a bit more clear.  It already shows a dialog controlling what happens per file.

**Comment by GLeBaTi** [comment]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
i was not found "disable auto resolve conflicts" setting in ui

**Environment you encounter the issue:**
- GitExtensions version: 2.51
- GIT version: 2.14.2
- OS version: Windows 8
- .NET version: All

**Did this work in previous version of GitExtensions (which)?**
Not

**Comment by pmme** [comment]
I don't know if this will help, but ensure the following setting is not ticked:

![ge confirm resolve conflicts](https://user-images.githubusercontent.com/1947040/42670135-a1d9e388-8648-11e8-8979-df16686b4e54.png)
