### ISSUE TITLE
Dialog size is not saved

### ISSUE THREAD

**Issue by DasTestament** [gitextensions/gitextensions#5163]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Dialog size is not saved

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. resize window & close it
2. reopen window

**What is the expected behavior?**
Dialog size is saved upon dialog close

**Environment you encounter the issue:**
- GitExtensions version: 2.51.02
- GIT version: 2.13.02
- OS version: Win 8.1 b9600 x64
- .NET version: 4.5

**Did this work in previous version of GitExtensions (which)?**
yes, in 2.51.01

**Comment by vbjay** [comment]
Search issues. Update to .03 or even test out .04.

**Comment by RussKie** [comment]
Please upgrade to the latest version.
