### ISSUE TITLE
Changelog is missing 2.51.3 and 2.51.4

### ISSUE THREAD

**Issue by adamralph** [gitextensions/gitextensions#5170]
**Do you want to request a *feature* or report a *bug*?**

🤔 ...bug?

**What is the current behavior?**

When I click "View changelog" in this dialog:

![image](https://user-images.githubusercontent.com/677704/42749346-a50eac58-88e3-11e8-9bda-2c27022a91af.png)

I see the changelog up to version 2.51.2 only.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See last point.

**What is the expected behavior?**

I see the change log up to and including 2.51.4.

**Environment you encounter the issue:**

- GitExtensions n/a
- GIT version: n/a
- OS version: n/a
- .NET version: n/a

**Did this work in previous version of GitExtensions (which)?**

n/a

**Comment by RussKie** [comment]
Thank you gents. I had a niggling feeling I was forgetting something.

**Comment by BobbyCannon-Quantros** [comment]
It's also missing the publisher details. 
![image](https://user-images.githubusercontent.com/28310412/42756477-49b34918-88ca-11e8-864c-4e51fb696216.png)

**Comment by drewnoakes** [comment]
> Defender doesn't want to allow the installer to run

I did a little digging on this and found an [MSDN blog post](https://blogs.msdn.microsoft.com/ie/2012/08/14/microsoft-smartscreen-extended-validation-ev-code-signing-certificates/) from 2012 that says:

> The deeper integration of SmartScreen Application Reputation also means that desktop app developers have an additional motivation to sign their code and establish reputation.

> **SmartScreen builds reputation for both individual programs and for the certificate used to sign that code**. Code signing is important to our reputation intelligence because this higher level identity allows us to build reputation across multiple programs signed by a publisher. It is also important for publishers because signed programs inherit the reputation of the certificate with which they are signed; this means every program a publisher distributes doesn’t need to build reputation individually.

> Detractors may claim that SmartScreen is “forcing” developers to spend money on certificates. It should be stressed that **EV code signing certificates are not required to build or maintain reputation with SmartScreen**. Files signed with standard code signing certificates and even unsigned files continue to build reputation as they have since Application Reputation was introduced in IE9 last year. However, the presence of an EV code signing certificate is a strong indicator that the file was signed by an entity that has passed a rigorous validation process and was signed with hardware which allows our systems to establish reputation for that entity more quickly than unsigned or non-EV code signed programs.

My initial thoughts are:

- We are not realistically going to get an EV cert.
- This dialog will only bother the first N users, until such a time as the system learns to trust the binary.

Would be nice to know what the value of N is though.

**Comment by BobbyCannon-Quantros** [comment]
I was concerned that something has changed because "GitExtensions-2.51.02.msi" works fine but "GitExtensions-2.51.04.msi" does not. 

I guess I saw this because I was one of the first "X" users?

**Comment by drewnoakes** [comment]
Yes I assume that's the case.

Just ran the installer myself and saw the same:

![image](https://user-images.githubusercontent.com/350947/42782468-f582e6d8-8940-11e8-8bc6-07b222a3cd6b.png)

**Comment by RussKie** [comment]
> We are not realistically going to get an EV cert.

We have actually discussed it sometime ago in #3979, and @jbialobr found a relatively cheap option (https://github.com/gitextensions/gitextensions/issues/3979#issuecomment-328141745).
We have a little cash in our bank, and we need it we need to get @spdr870 to buy it and send it over to me (or whoever else wants to be in charge of releases).

**Comment by adamralph** [comment]
Thank you!
