### ISSUE TITLE
Git config log.showSignature breaks revision grid

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5179]
**Do you want to request a *feature* or report a *bug*?**
BUG
**What is the current behavior?**
```git config log.showSignature true``` breaks the listing of all branches.  I have a few branches in my repo and when I set it, only master showed.  This is because develop had signed commits.  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- ```git config log.showSignature true```
- Load repo in GE

**What is the expected behavior?**
Signed commits should still show in GE.
**Environment you encounter the issue:**

- GitExtensions version:2.51.04
- GIT version: git version 2.18.0.windows.1
- OS version: Microsoft Windows [Version 6.3.9600]
- .NET version: mscorlib	DomainNeutral, Native	C:\Windows\assembly\NativeImages_v4.0.30319_64\mscorlib\be2b233163fe3b9af2d68b10d4798ef2\mscorlib.ni.dll

**Did this work in previous version of GitExtensions (which)?**
Probably not

**Comment by gerhardol** [comment]
Is  git log --no-show-signature showing normal output?
If so, is it OK in older Git versions too?

The no- option is not documented so it is not sure that this option should be used.
The alternative is git -c log.showSignature=false

Will you make a PR?

**Comment by vbjay** [comment]
Yes.  I plan on making a pull request tonight.  At work now.

**Comment by vbjay** [comment]
So in the console it shows just fine.  It's the revision grid getting output like 

![image](https://user-images.githubusercontent.com/3629489/42966703-0ddcb826-8b6c-11e8-9e96-e151167c371e.png)

**Comment by vbjay** [comment]
The fix is to include --no-show-signature in the log calls.

**Comment by gerhardol** [comment]
Third alternative would be to ignore lines starting with gpg. That will be microseconds faster for repos without commit but many milliseconds slower for users with signed commits.

> The fix is to include --no-show-signature in the log calls.

Since that option is not documented, someone must check the Git source history or test with older Git versions.

**Comment by vbjay** [comment]
The --no-* idea is standard in git.  
![image](https://user-images.githubusercontent.com/3629489/42967191-7c5ea84e-8b6d-11e8-86dd-821c11186efc.png)

**Comment by vbjay** [comment]
https://github.com/git/git/commit/aa3799996c310da756c7845950def4f6d51cccf3  I think we are good considering it's in 2.10

**Comment by vbjay** [comment]
I'll create two pull requests, one for master and one for 2.51.

**Comment by sharwell** [comment]
> Third alternative would be to ignore lines starting with gpg. That will be microseconds faster for repos without commit but many milliseconds slower for users with signed commits.

After seeing the scope of the pull request, I lean towards this approach instead. It's much more robust and doesn't require future users to know to include a special flag "just in case".

The performance issue(s), if any, would likely be addressed by a goal of moving from `git log` down to the low-level commands that have stable/machine-readable outputs.

**Comment by vbjay** [comment]
Considering that changing to lower level commands would mean altering all parsing from git, I didn't go that route. Raise another issue for that.

**Comment by sharwell** [comment]
> Considering that changing to lower level commands would mean altering all parsing from git, I didn't go that route. Raise another issue for that.

That was a side note. What about the main part where we update the `git log` parsing output so we don't have to maintain the additional flag everywhere?

**Comment by RussKie** [comment]
> > Third alternative would be to ignore lines starting with gpg. That will be microseconds faster for repos without commit but many milliseconds slower for users with signed commits.
>
> After seeing the scope of the pull request, I lean towards this approach instead. It's a much more robust solution and doesn't require future users to know to include a special flag "just in case".

I agree.

**Comment by vbjay** [comment]
Switching to using git -c command instead.

**Comment by RussKie** [comment]
After some high level investigation it looks like various `git log` calls are routed via different processors. 
Some via:
https://github.com/gitextensions/gitextensions/blob/cf0fabcf55840416abefb40618b05ace8a33e736/GitCommands/Git/GitModule.cs#L667
Some via:
https://github.com/gitextensions/gitextensions/blob/cf0fabcf55840416abefb40618b05ace8a33e736/GitCommands/Git/GitModule.cs#L647
And there are probably few other code paths...

Pretty messy... 😒

**Comment by vbjay** [comment]
Do you want me to apply the -c fix to that pull request or leave it as is
for 2.51?

**Comment by vbjay** [comment]
I have updated #5182.  You can see what I mean by -c solution.  This way, any caller can override the defaults and add their own config values when needed.

**Comment by vbjay** [comment]
Both pull requests are ready for review and complete.  I have squashed the release/2.251 pull request.  They provide the capability to generate -c calls.
```c#
string args= "log --oneline"
IEnumerable<KeyValuePair<string,string>> configs=new KeyValuePair<string,string>[]
{
    new KeyValuePair<string,string>("log.abbrevCommit","true")//describe why we are setting this here
}
RunGitCmd(args,configs,...)
```
The command generated would be 

```git -c log.ShowSignature=false -c log.abbrevCommit=true log --oneline```
