### ISSUE TITLE
Commit window not showing commit message changes made by a 'prepare-commit-msg' hook.

### ISSUE THREAD

**Issue by WilbertOnGithub** [gitextensions/gitextensions#518]
I've written a program that lets me select workitems from Team Foundation Server. I call this program in a 'prepare-commit-message' hook.

When using the CLI or git gui this works flawlessly. I commit, my program pops up, I select some workitems and the workitem ID's get injected in the commit message. I can review the commit message before I actually commit anything.

When testing this with GitExtensions 2.21, this does work. The hook fires, launches my program and allows me to select things. However, the changes made to the commit message are not visible in the gitextensions commit window. When commiting, the message IS actually modified, but I would like to review the commit message in the gitextensions commit window before actually committing.

I think it is simply a case of re-reading the commit message after the hook has been triggered. I'll have a look in the source code to see If I can supply a patch.

**Comment by brunoAlmeida-sky** [comment]
@WilbertOnGithub I know it's been almost a decade but... Were there any developments?

**Comment by WilbertOnGithub** [comment]
> @WilbertOnGithub I know it's been almost a decade but... Were there any developments?

I have no idea. I stopped using GitExtensions so I no longer have any need for these changes .

**Comment by pmiossec** [comment]
GitExtensions has an integration with Jira through the "Jira commit hint" plugin and there is a PR for the same thing for "Azure DevOps" in #7060 (maybe work with TFS >=2015).

For other support that's not too difficult to add as a new plugin...
@brunoAlmeida-sky what issue tracker support you want?
