### ISSUE TITLE
Feature request: Support TypeScript in Statistics plugin

### ISSUE THREAD

**Issue by rhegner** [gitextensions/gitextensions#5190]
The Statistics plugin of version 2.51.04 does not support counting the lines of TypeScript code (*.ts files).

**Comment by vbjay** [comment]
How about we add a custom extension list that allowed multiple file
extensions. User could add their own extension groupings. Also. Do this
against master. They aren't going to update 2.51.

Web forms:*.ascx;*.aspx;

**Comment by rhegner** [comment]
The problem with such a generic approach might be the handling of comment lines which is not the same for all file types. But I'm just guessing here, I haven't looked at the sources in detail yet.

**Comment by drewnoakes** [comment]
Here's the code that defines the default supported extensions:

https://github.com/gitextensions/gitextensions/blob/f68cacc0b2e3adf5997d9543c6a3afb326662f50/Plugins/Statistics/GitStatistics/GitStatisticsPlugin.cs#L16-L18

This is a setting. A workaround is to add the extension yourself:

![image](https://user-images.githubusercontent.com/350947/43079802-fe67f262-8e85-11e8-92ae-42b583e572f5.png)

Agree that TypeScript deserves built-in support however. It's probably worth separating out `.d.ts` and .`ts` files if that doesn't create too many woes.

**Comment by drewnoakes** [comment]
> The problem with such a generic approach might be the handling of comment lines which is not the same for all file types. But I'm just guessing here, I haven't looked at the sources in detail yet.

Comment lines are handled for many languages already. I believe TS's `/* */` and `//` style comments will work out of the box.
