### ISSUE TITLE
Restore revision grid highlighting of commits by author

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5197]
**Do you want to request a *feature* or report a *bug*?**
Regression from #5087 

**What is the current behavior?**
The highlighting for commits from the same author has been removed as part of the uplift, and replaced with author column highlighting.

**What is the expected behavior?**
Highlighting should be configurable.

**Environment you encounter the issue:**

- GitExtensions version: b210331fb67b2362cc1c666ad49911d4666d85e0

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.51

**Comment by drewnoakes** [comment]
As discussed in #5087 I like the idea of a general approach to revision highlighting in the grid.

To that end, I would vote for highlighting a given author's commits when the author's name cell is clicked. Shift+Ctrl click to highlight more revisions.

Another form of highlighting I'd like to see is the ability to highlight commits that modify a given file/folder.

There are probably other kinds of highlighting we could add.

@RussKie if you feel this would be appropriate, perhaps we could avoid adding another setting. I don't really use author highlighting so can't tell whether this would scratch your itch.

**Comment by gerhardol** [comment]
I use author highlightning, but actually come to prefer the bold text over the row coloring.
So this is no regression for me. But this is to agree on! (RussKie has most votes anyway.)

Configurability is a new feature, I like to track a certain file.

**Comment by pmiossec** [comment]
I also would like this feature reintroduced. 

I don't use it a lot but the first time I used it with the new commiter highlight in bold, I found it less usable (you have to look at 2 columns at the same time : commiter and commit message.)

But if we end up with an even better highlight of commit, I take it 😁

I particularly love the idea to be able to highlight commits with changes on a specific file. It would be great 👍

**Comment by RussKie** [comment]
@drewnoakes yes, the highlighting makes my life significantly easier, especially on large monitors.
I like your other proposals, I think they are great.

> RussKie has most votes anyway

I'd like to think of us as a "republic", so we're all have the same weight.

**Comment by mdonatas** [comment]
I so +1 this! Devs in our team use this feature when billing hours. You click one of your commits and read commit messages under yellow background to remind yourself of what you worked on.
Or, to quickly see what say a front-end designer did, etc. Having to look at two columns with a BIG gap between them is totally unworkable.

Can we limit this issue to first bringing the background highlight back?

Also, @drewnoakes these highlight options, where would they be chosen? When say right-clicking a revision grid?

**Comment by crypto-rsa** [comment]
> Devs in our team use this feature when billing hours.

@mdonatas to this end I have a simple git alias:
```
[alias]
	week = log --author=\"Pavel\" --since=\"last Sunday\" --all --reverse --oneline --no-merges
```

So at the end of the week I just run `git week` 😄 Of course that doesn't mean a highlighting feature in GE would not be useful.

**Comment by RussKie** [comment]
> To that end, I would vote for highlighting a given author's commits when the author's name cell is clicked. Ctrl+click to highlight additional authors.
> 
> Other forms of highlighting:
> 
> * Commits that modify a given file/folder (`gitk` does this and it's great)
> * Commits on a given branch (parallel to current greying out of graph nodes/lines not on a given branch currently available via menus or Ctrl+Shift+B)
> * Others?

I'm restoring the highlight as we had it in 2.5x, as for me it is a UX regression.
That said, I quite like the above proposals and I'm quite interested to discuss how we can implement these.

**Comment by mdonatas** [comment]
😍😍😍❤❤💕💕💕💖💖💖✔
