### ISSUE TITLE
Revisit logo in dashboard

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5198]
**Do you want to request a *feature* or report a *bug*?**

UI defect

**What is the current behavior?**

#5087 introduced a standard icon across the project:

![](https://camo.githubusercontent.com/b84cf97f7183a8c566d21358965af6ad2a01cf6f/68747470733a2f2f63646e2e7261776769742e636f6d2f676974657874656e73696f6e732f676974657874656e73696f6e732f6d61737465722f4c6f676f2f6769742d657874656e73696f6e732d6c6f676f2e737667)

This square form didn't work on the dashboard so I attempted an alternative that shows the words "Git Extensions" alongside. I'm not happy with the result.

The image itself looks passable:

![](https://raw.githubusercontent.com/gitextensions/gitextensions/05b7bde8737c57c86e63074668ad606a626112fb/Logo/GitExtensionsLogoWide.png)

It just looks rubbish _in situ_:

![image](https://user-images.githubusercontent.com/350947/43143030-bfdbf710-8f51-11e8-9537-6adb59ee8254.png)

**What is the expected behavior?**

Doesn't look terrible.

More specifically I think the left padding of icons beneath should match the left/right padding of the logo within it's dark blue rectangle.

The green is also hard to see against that particular shade of blue. Might just be my screen.

**Environment you encounter the issue:**

- GitExtensions version: master

**Comment by RussKie** [comment]
And I'm guessing the text won't be readable in dark theme at all... 😆

**Comment by RussKie** [comment]
One of my good friends is a designer and he was kind enough to help us with the dashboard colour tweaks.
Here's what an updated dashboard will look like:

100% at 2862x1654
![image](https://user-images.githubusercontent.com/4403806/48329259-05b78500-e69c-11e8-8c6b-12865b051b8c.png)

150% at 2862x1654
![image](https://user-images.githubusercontent.com/4403806/48329303-3b5c6e00-e69c-11e8-8e03-b3554bb763e6.png)

200% at 2862x1654
![image](https://user-images.githubusercontent.com/4403806/48329340-6777ef00-e69c-11e8-8ba8-38e9d4d42962.png)


A keen eye would notice few changes:
* the background now tiles seamlessly without rough edges
* theme colours tweaked
* and of course, the logo has lost its colours and become white. 
I was told that from the design and colour science perspective red and green are the two worst companion colours. 
As we currently have, the logo is lost on the blue background. The background has to be significantly lighter or darker and then it leads further into a rabbit hole...

What my friend has suggested is to reconsider the current logo colours.
Few examples:
![image](https://user-images.githubusercontent.com/4403806/48329559-73b07c00-e69d-11e8-8bd3-58bfa0261f83.png)
![image](https://user-images.githubusercontent.com/4403806/48329575-7d39e400-e69d-11e8-9be6-ae210c6ed128.png)
![image](https://user-images.githubusercontent.com/4403806/48329584-8925a600-e69d-11e8-994e-5a9c02429a48.png)

@spdr870 what do you think?
/cc: @gitextensions/git-extensions-source

**Comment by spdr870** [comment]
I like that it is readable. Not sure about the font, the letters are very close. The I en T have a slight offset at the top, but that is maybe not intended.

I like the cleaner colors. The white logo against a black background is very nice. The black against white also. Not sure about the blue background with the white logo. It might take some getting used to. But its look way better then the current one. Its clean.

Having that said, I am not the best person to ask about logo design. You remember the cow icon?

**Comment by RussKie** [comment]
> Having that said, I am not the best person to ask about logo design. You remember the cow icon?

🤣 
I was curious whether red/green had any special meaning/purpose.
My friend said, that _white on black_ and _black on white_ are important to get right from the brand perspective. 
I agree the look good. When we'll be working through the support for a dark theme we can certainly use these.

Right now I'm somewhat struggling with the light theme colour scheme.,,
I'm not 100% sold on _white on blue_, I'd like to get more colour in it. 

> Maybe an idea to use the colors in the different colored logo's in the graph?

Sorry, you've lost me here...

**Comment by gerhardol** [comment]
No real preference on the color schemes, maybe the green version as it differs the least. But blue fits better to the current theme.

> Maybe an idea to use the colors in the different colored logo's in the graph?

The old logos have already been removed

**Comment by francoas** [comment]
Everything looks nice. My favourite are the bluish versions

![image](https://user-images.githubusercontent.com/3007941/48699884-cf718c80-ebea-11e8-88f4-ef206a5c66f0.png)
![image](https://user-images.githubusercontent.com/3007941/48699895-d7313100-ebea-11e8-9875-9bcd16960215.png)

The only thing I would object is the double arrow pointing UP and DOWN
If the logo refers to a detail on a graph, the arrow should point only upward
