### ISSUE TITLE
About form - clipped text

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5201]
**Do you want to request a *feature* or report a *bug*?**
:bug:

**What is the current behavior?**
![gitext](https://user-images.githubusercontent.com/1003909/43148450-94936778-8f65-11e8-88c7-c61b06e93ae6.png)

**Environment you encounter the issue:**

- GitExtensions version: 0776ec9

**Comment by drewnoakes** [comment]
Is this at 100% scaling?

**Comment by jbialobr** [comment]
Yes, it is 100%, but the AppFont is 10.

**Comment by pmme** [comment]
Also the multi-line warranty statement is truncated.

In 2.51.02 it reads:

>This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY of FITNESS FOR A PARTICULAR PURPOSE.
