### ISSUE TITLE
FileList: Space between path and file

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5206]
**Do you want to request a *feature* or report a *bug*?**
bug - regression in #5087, minor

**What is the current behavior?**
Spaces is added between directory and filename if the path is long
![image](https://user-images.githubusercontent.com/6248932/43192863-d5bad8c8-8ffe-11e8-8148-9fd34437228a.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Make a dummy change to a filer deeper in the directory
(I get this when running unit tests in the following file (but that is a separate issue)UnitTests\GitCommandsTests\UserRepositoryHistory\Legacy\RepositoryCategorySerialiserTests.Verify_backwards_compatibility_of_object_graph.approved.xml)

**What is the expected behavior?**
See path without sopace

**Environment you encounter the issue:**

- GitExtensions version: 0776ec902ca743811a7e75d92a02e52fb31090a0

**Did this work in previous version of GitExtensions (which)?**
pre #5087

**Comment by drewnoakes** [comment]
Reproduced at 20% scaling:

![image](https://user-images.githubusercontent.com/350947/43193479-084a94a6-8ff8-11e8-84ba-2e1d386005e2.png)

Measuring text reliably with GDI is hard. The relevant code is here:

https://github.com/gitextensions/gitextensions/blob/7df016dfe3fada5a93c304c5eff7ff72c861da62/GitUI/UserControls/FileStatusList.cs#L330-L364

I tried several approaches before ending up with this solution which, until now, I thought worked reliably. `MeasureText`/`MeasureString` were consistently worse than `MeasureCharacterRanges`, never in fact appearing correctly. This requires more investigation.

This would be a non-issue with WPF, for what it's worth.

**Comment by gerhardol** [comment]
Why not render path+file together?

**Comment by drewnoakes** [comment]
#5087 introduced this change. The file name and its path appear with differing colours. The goal was to make lists of files easier to read.

![image](https://user-images.githubusercontent.com/350947/43195149-18387d66-8ffc-11e8-8577-3a8b72350d36.png)

The effect is subtle and generally looks better in my opinion.

**Comment by gerhardol** [comment]
Low prio, we should try to make it look better.
But if I have to choose between "occasional spaces" and "less good looking file names", I choose the latter.

**Comment by drewnoakes** [comment]
Whether there's a gap seems conditional upon the length of the file name. The magnitude of that gap seems dependent upon the path length.

![image](https://user-images.githubusercontent.com/350947/43229328-4950bd72-905c-11e8-9933-0b5283aa1210.png)

Note the last line has a small gap, but `foo.xml` in the same folder is fine.

**Comment by drewnoakes** [comment]
My docking station is working again so I'm back to regularly running at 96dpi/100% scaling. I see this issue more regularly now, even on shorter strings. Until now I'd only ever seen it once, in the case @gerhardol identified.

![image](https://user-images.githubusercontent.com/350947/44254715-8aa91480-a1fb-11e8-982d-30c0e808bbec.png)

If we can't find a resolution I accept that we should back this feature out for 3.0.

**Comment by NikolayXHD** [comment]
> This requires more investigation.

Maybe using `System.Windows.Forms.TextRenderer` would help.
Example: https://github.com/NikolayXHD/Mtgdb/blob/master/Mtgdb.Core.Controls/Bitmap/TextDrawingHelper.cs
