### ISSUE TITLE
Remote tracking branch not visible by default?

### ISSUE THREAD

**Issue by afarley-tangent** [gitextensions/gitextensions#5211]
I'm confused by the fact that the remote tracking branch is not displayed after pushing an initial commit to Github. I only see the red 'master' branch on my local PC in the GitExtensions UI.

Steps to reproduce:
1. Create a project
2. Create a repo on Github
3. Initial local commit (shows local master branch in GitExtensions)
4. Push repository (did I miss a checkbox for "create local tracking branch" at this step?)
5. At this point, the push works (I see my files on Github) but when I view in GitExtensions, it only shows one local master branch, not the remote/master tracking branch that I would expect as well.

- GitExtensions version: 2.51.04
- GIT version: 2.18.0.windows.1
- OS version: Windows 10 Pro x64
- .NET version:  4.7.2 (I think)

I believe this worked as expected in all previous version. Only noticed this issue recently, but I had to reinstall everything/rebuild my development environment so there were many potential changes.

Even more strange: I've created/pushed a few repos lately, and one of them *does* show the remote tracking branch (in green) next to the local branch (in red). I've examined the remote repository configuration for that repo and compared it to the ones where the remote branch isn't displayed, but I don't see any differences.

**Comment by RussKie** [comment]
Please share some screenshots to visualise the issue

**Comment by afarley-tangent** [comment]
Ah, sorry - I checked again and it looks like I was simply hitting 'No' by accident when the dialog-box popped up asking to create a remote tracking branch. 

When I went through the process again and selected 'Yes' for remote-tracking branch, everything looks the way I expect. I will close this issue.
