### ISSUE TITLE
User script icons disappeared and no longer selectable in in v. 3

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#5219]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
After updating to version 3 (master at b0666e53e584d29146e0ca6c53e9d564e5de6e58), the icons for custom scripts shown in my taskbar and context menu have disappeared. In the settings dialog, the Icon combo shows just the _Select icon_ text instead of the actual icon selected before and nothing happens upon clicking it (ie. the combo does not expand).

![obrazek](https://user-images.githubusercontent.com/11479798/43246453-f83c6dcc-90b1-11e8-910a-ac765cb04167.png)

![obrazek](https://user-images.githubusercontent.com/11479798/43246480-0fd7b8b0-90b2-11e8-8536-57bc547660c5.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. In GE 2.x define some custom scripts with icons and add them to the taskbar or context menu
2. Update to GE 3

**What is the expected behavior?**
The icons should still be visible in GE 3.

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: master at b0666e53e584d29146e0ca6c53e9d564e5de6e58
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.x.

**Comment by RussKie** [comment]
Please test and confirm the fix https://ci.appveyor.com/api/buildjobs/ehoe52awp18nwjl1/artifacts/GitExtensions-Portable-3.00.00.3066.zip
Thank you

**Comment by crypto-rsa** [comment]
Wow, that was quick. In the linked build, not all of my original icons were recovered but I suspect that's because some of them have changed names (they are a lot more descriptive now). But anyway, I was able to easily select new icons for the scripts so I declare the fix as working 😄

**Comment by pmiossec** [comment]
>Wow, that was quick. 

That was because I made the fix before you opened the issue ;)
