### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5224]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/3629489/43259513-79e8aab0-90a4-11e8-9a96-eb37eda12e03.png)
release/2.51 is at 106e75808694bfabe3607c062afe0b381383908c I am trying to reimplimenting my changes in #5182 to #5181 but this is preventing me from working. 
![image](https://user-images.githubusercontent.com/3629489/43259658-f46230ae-90a4-11e8-8b4a-0e75677564a1.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
No red squiggles.  
**Environment you encounter the issue:**
vs 2017 15.7.5
- GitExtensions version:release/2.51
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by vbjay** [comment]
Yes.  I did a git clean to check for master branch contamination.  

![image](https://user-images.githubusercontent.com/3629489/43260540-d74b0b8c-90a7-11e8-83a2-c00decc71db4.png)

**Comment by sharwell** [comment]
@vbjay Which branch are you in? The use of `PackageReference` (master branch) interferes with the use of **packages.config** (2.5x branch), so you'll need to either have two independent directories for the branches or use a `git clean` after switching from master to 2.5x.

**Comment by vbjay** [comment]
In showsig which is at the current release/2.51 commit. I'll do one better
and delete all files but .git folder and do a reset just to make sure.
Thanks. I'll let you know how it goes.

**Comment by vbjay** [comment]
That solved it.

**Comment by sharwell** [comment]
Duplicate of https://github.com/gitextensions/gitextensions/issues/4733#issuecomment-377561941
