### ISSUE TITLE
Rebase dialog displayed unnecessarily

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#5225]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When clicking _Rebase current branch on - Selected commit interactively_ the rebase dialog is displayed and it requires an extra click to actually start the rebase operation. There is a separate context menu item for rebasing with advanced options.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Click the command for interactive rebase

**What is the expected behavior?**
Rebase should start immediately without showing the dialog.

**Environment you encounter the issue:**

- GitExtensions version: master at 6e38cf4d18540469c3c52679b7619a1fde0443e6
- GIT version: 2.18.0.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes, prior to merging #5087.

**Comment by gerhardol** [comment]
Intentional #4559, to not rebase accidentally

![image](https://user-images.githubusercontent.com/6248932/43268374-c2cdf202-90f0-11e8-83d4-08da06c2fdfd.png)

**Comment by gerhardol** [comment]
> The lack of a context-sensitive "..." (as per jbialobr's comment on #4559) on the menu item was definitely a part of my confusion.

A PR to add ellipsis if there is a dialog will be welcome

**Comment by crypto-rsa** [comment]
This seems to be made obsolete by #5413. The dialog is now never displayed for the first two rebase options (_Selected commit_ and _Selected commit interactively_). Only the small confirmation dialog is displayed (unless that confirmation is switched off in the settings). The ellipsis is only shown for the third option (_Selected commit with advanced options..._) which is correct. So I think this issue can be closed. @mdonatas, as the author of the PR-which-made-this-obsolete, do you agree? :-)

**Comment by mdonatas** [comment]
@crypto-rsa absolutely ;)

**Comment by RussKie** [comment]
Thank you for the follow up.

**Comment by RussKie** [comment]
> my last comment in #5001 was actually a question for you 😉

Thank you for the reminder, I missed it.
