### ISSUE TITLE
Cleanup: WorkTree/Index should be used rather than Unstaged/Staged

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5230]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Code has inconsistent use of WorkTree and Index "artificial" commits.
Unstaged/Staged are are used too.
The most common combination is Unstaged/Index

The Git documentation has been cleaned up to consistently use WorkTree/Index, the is what should be used in the code too

Note: Stage/Unstage can still be used as the action to move files to/from WorkTree/Index

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
n/a

**What is the expected behavior?**
Consistency with Git documentation

**Environment you encounter the issue:**

- GitExtensions version: all

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by drewnoakes** [comment]
I find "Workspace" a bit friendlier than "WorkTree", though don't feel strongly about it. Consistency with the docs is good.

**Comment by gerhardol** [comment]
> EDIT: I see from your PR that you mean to use WorkTree in code, at least for now. My comment about friendliness related to user-facing terminology.

No change towards users right now
(But _Working directory_ should have been _Working tree directory_ if that was not much longer than _Commit index_)

**Comment by gerhardol** [comment]
Unstaged/staged consistency will be a GE specific consistency, not aligned with git. 

This can be dismissed with it creating noise
