### ISSUE TITLE
Incorrect layout of revision grid

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5247]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The revision grid is not taking all available space
![image](https://user-images.githubusercontent.com/4403806/43396177-1736e26c-9444-11e8-9bb5-ae025a041d89.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Build 8f80b287cfcf6731161775861b7bbaeb2ea2bd06
* Load an app with the commit info panel located at the bottom

**What is the expected behavior?**
The revision grid takes all the space available

**Environment you encounter the issue:**

- GitExtensions version: 8f80b287cfcf6731161775861b7bbaeb2ea2bd06

**Comment by drewnoakes** [comment]
Did you do anything in particular to get into this state? I haven't seen this before.

**Comment by RussKie** [comment]
Not really, it just happened several times in a row...
Leave it with me, I'll see whether I can fix it.

**Comment by pmme** [comment]
This may be relevant: 
Toggling the branch panel on the left on my computer causes a visible shift of the revision grid that leaves a grey space like you have seen but only briefly. The function completes on my computer and the revision grid is resized to fit the window with or without the branch panel as appropriate.

**Comment by vbjay** [comment]
Try commit window on side or below and side panel off or on.

**Comment by RussKie** [comment]
I think this is a new regression I introduced fixing #5244 regression, hehe...
Toggling the side panel on and off lays out the grid correctly

**Comment by RussKie** [comment]
Yes, having changed the order of execution in `InitialiseInternal` it messed up things.
