### ISSUE TITLE
FileTree tab doesn't apply to artificial commits

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5252]
**Do you want to request a *feature* or report a *bug*?**

Opportunity to avoid confusion.

**What is the current behavior?**

When selecting either the "Working directory" or "Commit index" artificial commits, the "File Tree" tab is empty.

![image](https://user-images.githubusercontent.com/350947/43471723-9448d4f0-94e3-11e8-9d7c-781ce187e509.png)

![image](https://user-images.githubusercontent.com/350947/43471733-9b49abd0-94e3-11e8-8aab-336fed55487c.png)

**What is the expected behavior?**

The tab should not be visible for such commits.

**Environment you encounter the issue:**

- GitExtensions version: master (b4fc548f65133241e7ed8034fe07a46693130c93)

**Comment by gerhardol** [comment]
This was changed in 2.51, previously FileTree and Commit tab was removed for artificial commits.
https://github.com/gitextensions/gitextensions/issues/4242
This bugs me quite often

I see the following solution, in my prio order:

1. Hide the tabs as it was before 
2a. Provide an Explorer link for WorkTree-FileTree and explanation for Index-FileTrre (no change for Commit. 
2b. If any of the tab is selected when selecting an artificial commit, select Diff automatically
99. Implement an explorer for WorkTree and implement ls-tree from ls-files (or git-status, git-diff-files) for Index. SHA for blobs may not be available, handled async.
