### ISSUE TITLE
Plugin: Octopus Deploy

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5254]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
We support build servers.  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
I would like to also support deployment servers.  We have set up a teamcity build server and octopus deploy system to deploy microservice APIs where I work. It would be great to see deployment statuses and such from deployment servers like Octopus.  Octopus Deploy allows for API keys.  

**Did this work in previous version of GitExtensions (which)?**
No.

**Comment by vbjay** [comment]
https://octopus.com/docs/api-and-integration/api

**Comment by RussKie** [comment]
Create a plugin using https://github.com/gitextensions/gitextensions.plugintemplate. 
There are few examples: https://github.com/search?q=topic%3Agitextensions-plugin+org%3Agitextensions&type=Repositories
