### ISSUE TITLE
Pull dialog get closed automatically whenever pull from GiExtensions but pull working fine in git bash

### ISSUE THREAD

**Issue by kkhaserao** [gitextensions/gitextensions#5261]
In the Git extension while pulling the branch through the UI (using pull dialog), It get closed automatically without giving error, However When I pull from GitBash the pull is successful with no error.

- GitExtensions version: 2.51.04
- GIT version: 2.18.0.windows.1
- OS version: Windows 10 (1709 (OS Build 16299.492))
- .NET version: 4.7.02556

Before upgrading the git extension I was working on GitExtension version : 2.51.01

**Comment by RussKie** [comment]
Could you please provide more information (e.g. steps to reproduce, screenshots, logs etc) as it is not particularly obvious what the problem is.

**Comment by RussKie** [comment]
> Clone remote repository from UI as well as git bash not working

This a concern I'd start first, you must be able to clone from git without troubles.

If you downgrade to 2.51.01, is it working?

**Comment by vbjay** [comment]
What folder path are you cloning to?  Sounds like you might not have access
unless you have administrator rights.

**Comment by RussKie** [comment]
You can also run [process monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to see whether you get access issues

**Comment by kkhaserao** [comment]
@vbjay I have access because this same thing is working on my desktop but not on laptop.
@RussKie I have worked on 2.49 version it is working fine in same machine

**Comment by RussKie** [comment]
Could that be permissions on your laptop differ from your desktop?

**Comment by kkhaserao** [comment]
Yes it is permitted to do so.

**Comment by kkhaserao** [comment]
Is there any solution?

**Comment by RussKie** [comment]
This looks like https://github.com/Maximus5/ConEmu/issues/1308.

You can try disabling the ConEmu and see if it helps
![image](https://user-images.githubusercontent.com/4403806/44334774-cec73e00-a4b5-11e8-80b6-f0869b705132.png)

**Comment by kkhaserao** [comment]
Ohh.. Great.. my problem is solved.. Thank You So much.. :)
closing this issue.

**Comment by RussKie** [comment]
Good to hear, ConEmu can be very temperamental
