### ISSUE TITLE
Missing items in the main menu

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5262]
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**
![gitext](https://user-images.githubusercontent.com/1003909/43507242-d41fc6ae-956c-11e8-8a16-d56da6145113.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open GitExt repo
2. Go to the File Tree tab
3. Right click on the GitExtensionsDoc submodule and choose Open with Git Extensions

**Environment you encounter the issue:**

- GitExtensions version: 68ecad2ca3dde3db4a2644afcb0780894e666167

**Comment by RussKie** [comment]
I'm pretty sure it is related to #5247

**Comment by RussKie** [comment]
May I get you to verify it is fixed?
https://ci.appveyor.com/api/buildjobs/1hpt34xcw6fbs19t/artifacts/GitExtensions-Portable-3.00.00.3147.zip

**Comment by jbialobr** [comment]
I confirm it is fixed in the attached version. Thanks!
