### ISSUE TITLE
Unable to stage in empty repository

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5263]
**Do you want to request a *feature* or report a *bug*?**
regression

**What is the current behavior?**
Unable to see or stage files in a new empty repository

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Create a new repository
* Create a new file
* Open a commit dialog

![cant_see_unstaged](https://user-images.githubusercontent.com/4403806/43508552-961736a2-95b3-11e8-8f80-33d15f4dd564.gif)

**What is the expected behavior?**
Able to see and stage files as necessary

**Environment you encounter the issue:**

- GitExtensions version: 68ecad2ca3dde3db4a2644afcb0780894e666167

**Comment by RussKie** [comment]
More info:
It fails in `GitRevision.cs`:
![image](https://user-images.githubusercontent.com/4403806/43551413-460b00ae-962a-11e8-8e14-d292dad9b1f9.png)
Higher up the stack in `FormCommit.cs`:
![image](https://user-images.githubusercontent.com/4403806/43551480-7bd8ff7e-962a-11e8-8192-4a6c2dca7b37.png)

**Comment by drewnoakes** [comment]
Based on that squiggly, R# was aware of the potential issue here. Might be good to do a review of all these nullability warnings and squash invalid warnings and fix valid ones.

Really looking forward to a possible future version of C# that codifies this in the language with compiler diagnostics.

**Comment by vbjay** [comment]
Read up on c# 8.

**Comment by RussKie** [comment]
> Might be good to do a review of all these nullability warnings and squash invalid warnings and fix valid ones.

Will do so separately

**Comment by drewnoakes** [comment]
@vbjay thanks. I've been following the LDM meeting notes since they started publishing them on GitHub. It's good to see how the sausage is made.
