### ISSUE TITLE
Exception viewing file history

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5277]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Viewing a file's history results in an exception.

> System.ArgumentException: 'Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.'

```
ArraySegment<byte>.ctor
GitUIPluginInterfaces.ObjectId.TryParseAsciiHexBytes(ArraySegment<byte>, int, out ObjectId) Line 276
GitCommands.RevisionReader.TryParseRevision(GitModule, ArraySegment<byte>, StringPool, Encoding, out GitRevision) Line 230 
GitCommands.RevisionReader.ExecuteAsync(GitModule, IReadOnlyList<IGitRef>, IObserver<GitRevision>, RefFilterOptions, string , string revisionFilter, string pathFilter, Func<GitRevision, bool> 
```

The UI appears as:

![image](https://user-images.githubusercontent.com/350947/43602160-0d603406-9687-11e8-8b97-2fc40c42d4e7.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Select a file in the diff tab and press <kbd>H</kbd> to view the history.

**What is the expected behavior?**

No exception.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.18
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**

Yes.

**Comment by drewnoakes** [comment]
This doesn't seem to happen for all files.

I can repro it at b7c9b12988f01d39ae5f78c834a79a97830113f0 with this file:

![image](https://user-images.githubusercontent.com/350947/43603660-819c8e74-968b-11e8-9690-9f75483cf4a9.png)

It might depend upon whether the file changed its name at some point in the history.

**Comment by RussKie** [comment]
Can this be closed now?
