### ISSUE TITLE
Cannot install GitExtensions 2.51.04

### ISSUE THREAD

**Issue by simontom** [gitextensions/gitextensions#5289]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug during installation.

**What is the current behavior?**
When I want to install currently last version of GitExtensions (2.51.04).

![image](https://user-images.githubusercontent.com/350947/43688791-899970a2-98e7-11e8-88ef-fe932a81381f.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I just ran the instasllation after I've downloaded it from this site.

**What is the expected behavior?**
To be able to install the last version without problems.

**Environment you encounter the issue:**
Windows 10 Pro x64

- GitExtensions version:
- GIT version: git version 2.18.0.windows.1
- OS version: Windows 10 Pro - 1803 - 06/24/2018 - 17134.165
- .NET version: 461808 (it should be .NET Framework 4.7.2)

**Did this work in previous version of GitExtensions (which)?**
Yes, it did.

**Note**
Not sure if that is just me because I haven't seen any thread about this kind of problem during installation of this new version.

**Comment by vbjay** [comment]
Download 2.51.02 installer and run it. It will allow you to uninstall it.

**Comment by drewnoakes** [comment]
To elaborate on @vbjay's comment, it seems as though the installer for 2.51.04 is trying to run the installer for earlier version 2.51.02 in order to uninstall that older version first. If you download the installer for that older version, you should be able to uninstall it that way.

**Comment by drewnoakes** [comment]
Please report back once you've tried that:

https://github.com/gitextensions/gitextensions/releases/tag/v2.51.02

**Comment by simontom** [comment]
Hello, thanks for advices.
I haven't tried this because I was in hurry in the evening. :-D So, I just created an issue to let you know about this.
I'll try when I get home.

**Comment by simontom** [comment]
Huh, I downloaded 02 together with the latest 04. Put into the same folder. And everything worked like a charm. The 04 installer was able to uninstall 02 version.
Interesting.
Maybe there is just some bad reference. :-D

Thanks and have fun guys.

**Comment by vbjay** [comment]
https://stackoverflow.com/questions/15610599/msipackage-meaning-of-attribute-cache

**Comment by simontom** [comment]
Thanks
