### ISSUE TITLE
Russian translate bug

### ISSUE THREAD

**Issue by avissian** [gitextensions/gitextensions#5292]
In Russian.xlf this unit have a error:

```
      </trans-unit>
      <trans-unit id="mergeBranchToolStripMenuItem.Text">
        <source>Merge into current branch</source>
        <target>Слить текущую ветку в</target> 
```

It's Russian text like as English "Merge current branch into"
need:

```
        <target>Слить в текущую ветку</target> 
```

**Comment by RussKie** [comment]
All translations are managed via https://www.transifex.com/git-extensions/, please raise an issue there.
You'll kudos if you fix it there :)
