### ISSUE TITLE
StashForm: Incorrect icon sizes

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5305]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Incorrect sizze for icons

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
![image](https://user-images.githubusercontent.com/6248932/43802868-6060fc3a-9a97-11e8-9818-47452e3526c1.png)

**What is the expected behavior?**
Normal icon sizes as in 2.51 (this is not #5087 though)

**Environment you encounter the issue:**
100% scaling

- GitExtensions version:
- GIT version: 5375e07070c363603a85f2b2b0c0b3e9011b606d
- OS version: Win10
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**
2.51.04

**Comment by drewnoakes** [comment]
Might be this line:

https://github.com/gitextensions/gitextensions/blob/5b02ba172defc2f6312fde0194456ffcdcc36f42/GitUI/CommandsDialogs/FormStash.Designer.cs#L280

Looks like we only set the `ImageScalingSize` property in two places throughout the whole codebase, the other being in `FormRefLog`:

https://github.com/gitextensions/gitextensions/blob/5b02ba172defc2f6312fde0194456ffcdcc36f42/GitUI/CommandsDialogs/FormReflog.Designer.cs#L211

Maybe we can remove both setters. I think all our icon images are 16x16 now.
