### ISSUE TITLE
Codefactor

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5308]
I accidentally set up codefactor.io to report on this repo. I thought it was just going to show me details on their site, but it is reporting status on PRs it seems. See #5307 for an example.

I'm not sure how much value it brings. I'm happy to remove it.

**Comment by vbjay** [comment]
They have been going on for a while.  I don't think it's a problem.

**Comment by RussKie** [comment]
Let's leave it, it seems harmless (so far), yet gives some food for thought.
