### ISSUE TITLE
Cannot get latest on run push  request

### ISSUE THREAD

**Issue by vanthao** [gitextensions/gitextensions#5313]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**

- GitExtensions version: 2.5.02
- GIT version: 2.3
- OS version: windows10
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**

**Comment by vbjay** [comment]
A.  Get current on bot GIT abd Git Extensions
GE: 2.51.04 is out
Git: 2.18.0 is out

B.  We have an issue template for a reason.  Your lack of details = not much we can do.

C. Getting latest revisions from a remote is a git fetch or git pull(just a fetch and merge together).  I recommend you look at http://www.vogella.com/tutorials/Git/article.html

**Comment by RussKie** [comment]
Closing due to unclear statement of the problem.
Please update the issue as per our template and re-open, if you're still having a problem. Please also note we do no provide support for general git-related queries.
