### ISSUE TITLE
Terribly slow on Windows 10

### ISSUE THREAD

**Issue by seantack** [gitextensions/gitextensions#5314]
I've installed Git (and tools) on my laptop for the first time.  I've been having terrible slowness using Git and moving around in GitExtensions.  I also tried GitHub Desktop and it was also terribly slow.  I read thru similar issues, ie. related to anti-virus.  I added a few folders and processes to my exclusions list for Windows Defender.  Git (via command line) then worked well.  However, GitExtensions (and GitHub Desktop) is still horribly slow.  I disabled 'real-time protection' in Windows Defender altogether and this made no difference for GitExtensions (or GitHub Desktop).

A couple notes.
* I have 3 brand new repositories (my only ones thus far).  None of them are large.  I started with blank repos in GitHub and added solutions from within Visual Studio 2017 using the plug-in.
* I deleted the repos and started from scratch, adding via git/GitExtensions.  Still slow, thus now something Visual Studio did that may have confused things.
* When I launch GitExtensions it takes several seconds before the app appears.
* Once it is shown, when I click on a repository I see the following:
![image](https://user-images.githubusercontent.com/6313169/44126630-3f70ce68-9fee-11e8-9811-311334250e37.png)

Then that disappears, followed by a long delay 'Loading...' for several seconds.
![image](https://user-images.githubusercontent.com/6313169/44126650-607ec6aa-9fee-11e8-94e9-b29f99402457.png)

I tried 'git init' since I saw the message in the first screenshot above.  That did not make a difference.

- GitExtensions version:  2.51.01
- GIT version:   2.18.0.windows.1
- OS version:  Windows 10 Home (64bit, 16GB RAM, i7, SSD)
- .NET version:  VS 2017

Looking for some guidance on where the issue lies and if there are some diagnostics I should provide.  Again, something slow and common between GitExtensions AND GitHub Desktop.  Both slow, but I uninstalled GitHub Desktop.  Things seem to be working fine, just God-awful slow.

Thanks!

**Comment by vbjay** [comment]
Try with a current version of gitextensions.

**Comment by RussKie** [comment]
Tools > gitcommand log

What sort of timings do you get?

**Comment by seantack** [comment]
@vbjay What do you consider 'current'?  That is the latest version from SourceForge.net... I just downloaded it yesterday.

**Comment by seantack** [comment]
@RussKie 
![image](https://user-images.githubusercontent.com/6313169/44128830-e9a59660-9ff9-11e8-8406-c457bb93e508.png)

**Comment by RussKie** [comment]
It is my understanding the latest at SF is 2.51.04.

Looking at the screenshot I see massive delays executing git commands - in
the order of tens of seconds (7s, 9s, 11s...).
This is certainly not normal, but it has nothing to do with git or
gitextensions.
I'd speculate it is something to do with you Windows configuration.

**Comment by seantack** [comment]
@RussKie   If you go to https://sourceforge.net/projects/gitextensions/ and mouse-over the big green button, that still has 2.51.01 attached to it.  The list of versions below it does say .04 is the latest.  But... I agree... this doesn't seem to be an issue with GitExtensions... saw the same thing with GitHub Desktop.  Can you point me in any direction with regards to Windows configuration?  I assume you guys don't want to get involved with this type of crap outside of the app, but any thoughts would be appreciated.  Best.

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/releases

**Comment by drewnoakes** [comment]
Can you you're the following into Git Bash, and let us know the output?

which git
time git --version

The fact that GE reports three seconds just to show the version of git on
your machine is worrying. It also suggests the issue is repo independent.
Is this a home PC, or a corporate one? Would you say the machine is
otherwise responsive? Have you tried uninstalling and reinstalling Git for
Windows?

**Comment by seantack** [comment]
Hey @drewnoakes - Thanks for the additional attention.  I did as you asked.  It seemed a little odd so I ran those commands a second time:
![image](https://user-images.githubusercontent.com/6313169/44186352-cfcf2880-a0cd-11e8-929c-5af4275372cd.png)

When I launched Bash there was a long delay (10 secs) before it displayed a $ prompt.  I could enter both commands, without rush, before they actually ran.  Yes, I've uninstalled and reinstalled Git and GitExt a few times.  I also updated from GitExt 2.51.01 to .04, but I don't see a difference.

This is a personal laptop that runs pretty crisp.  And, Git itself from the command line seems quick.  The apps surrounding it (GitExt and GitHub Desktop) are where I see slowness.  Thanks!

**Comment by seantack** [comment]
@RussKie @drewnoakes 
Gentlemen... I found something odd.  I was monitoring Task Manager while running GitExt and though I don't spend a lot of time in Task Manager, I've never seen behavior like this.  With GitExt running and showing as a running App, when I click something in GitExt it then drops from the App list in Task Manager... then later reappears and disappears... and stays appearing as an App once GitExt is idle again.  Not sure if that is a clue.

Jing screen capture video:  https://www.screencast.com/t/PdUcWoRu

It looks like it is fighting to run.  I turned-off Windows Defender real-time protection and it still didn't make a difference.

I'm looking closer at maybe some crap Lenovo may have installed.  Has anyone heard of Lenovo tools, like Lenovo Service Bridge, causing interference?

**Comment by RussKie** [comment]
Suggest running Process Monitor and see what's happening

**Comment by otbutz** [comment]
@seantack it sounds strange but it might be caused by your GPU driver: https://github.com/git-for-windows/git/issues/1070#issuecomment-283235173

**Comment by seantack** [comment]
@otbutz  Holy Santa Claus sh*t... that did the trick!  Thanks a million for the link to the other issue... totally made my day (week).  I will research updating the driver.  For the record, I have AMD Radeon R7 M460.
