### ISSUE TITLE
Option to show commit info to the left of graph

### ISSUE THREAD

**Issue by NikolayXHD** [gitextensions/gitextensions#5322]
**Feature request**

**What is the current behavior?**

![revision_list_position_present](https://user-images.githubusercontent.com/12046452/44292032-0f8f3f00-a28b-11e8-97b8-b476840a1e55.jpg)

**What is the expected behavior?**

![revision_list_position_suggested](https://user-images.githubusercontent.com/12046452/44291987-c50dc280-a28a-11e8-9d15-f343ccc541fe.jpg)

**Comment by gerhardol** [comment]
Merged to master in #5323
