### ISSUE TITLE
Branch Tree Panel initially empty

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5326]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The Branch Tree Panel is empty when it is shown the first time.
![grafik](https://user-images.githubusercontent.com/36601201/44313651-52c4eb80-a40c-11e8-8dba-c1191cf8eaef.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Show the Branch Tree Panel, close and open GE.
Or hide the Branch Tree Panel, close and open GE, show the Branch Tree Panel.

**What is the expected behavior?**
The branches are shown and if it applies, an indicator that loading is still progress.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
don't know

**Comment by RussKie** [comment]
```
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
Exception thrown: 'System.OperationCanceledException' in mscorlib.dll
```

**Comment by RussKie** [comment]
This looks like an out-of-order execution.
We obtain a cancellation token on line:156, then, while getting the selected branch, cancel the token...
![image](https://user-images.githubusercontent.com/4403806/44661357-c63eac80-aa4d-11e8-8fb5-95317bf9f42d.png)
