### ISSUE TITLE
Commit dialog: retain the view position when updating the diff

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5327]
**Do you want to request a *feature* or report a *bug*?**
incomplete new feature

**What is the current behavior?**
The commit dialog refreshes automatically when GE gets the focus again since v3-ux.
The cursor/scroll position is reset to the top of the diff.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the commit dialog with a diff (regardless staged or unstaged), scroll down the diff, switch to an other application, switch back to GE.

**What is the expected behavior?**
The view position shall be restored after reloading the diff.
This should be tried, too, when the display options are changed using ![grafik](https://user-images.githubusercontent.com/36601201/44313914-0334ee80-a411-11e8-9594-e5efcd916435.png).

If the cursor position was visible before, it should be restored.
If not, the previous top or the middle line shoud be restored.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
2.5

**Comment by vbjay** [comment]
Click options in the commit window.
