### ISSUE TITLE
Commit dialog: "Go to line" does not work sometimes

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5328]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Usually, the "Go to line" subdialog can be opened by pressing Ctrl+G.
This does not work if all lines of the diff are visible.
This does not work anymore after Ctrl+G was pressed for an image file or a binary file.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- open the commit dialog with a changed or new .png file and with a text file with several modifications
- select the .png file
- hit Ctrl+G 
- select the text file
- hit Ctrl+G

**What is the expected behavior?**
The shortcut key shall be displayed in the context menu.
The context menu text shall be "Go to line...   Ctrl+G", i.e. with dots "..." because it will open a subdialog.
The menu item shall be disabled if an image file or a binary diff is displayed.
The menu item and the shortcut shall work if a textual diff is displayed (regardless whether all lines are visible or not).

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
didn't check

**Comment by RussKie** [comment]
Fixed in #5563
