### ISSUE TITLE
Commit dialog: inconsistent display of new binary file

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5329]
**Do you want to request a *feature* or report a *bug*?**
inconsistency

**What is the current behavior?**
A new binary file is displayed with file contents if unstaged and without if staged.
![grafik](https://user-images.githubusercontent.com/36601201/44314342-4d6d9e00-a418-11e8-9296-52b5c62c0717.png)
![grafik](https://user-images.githubusercontent.com/36601201/44314351-6e35f380-a418-11e8-91ca-83ea5e7f9edc.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add a new binary file, open the commit dialog and select the file. Then stage the file.

**What is the expected behavior?**
The staged **new** file should not be compared with /dev/null.
It's contents should be displayed as it is done if it is unstaged.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
have not checked yet

**Comment by vbjay** [comment]
It's a new file not committed. Dev null is correct.

**Comment by mstv** [comment]
Yes, /dev/null is technically correct. But that's not the issue.
From user point of view there is no reason why the display of the file should depend on whether it's staged or not.

**Comment by gerhardol** [comment]
The current implementation tries to present the diff in the best way possible. Changing this will limit the functionality, I prefer to keep the "inconsistency".

In worktree (unstaged) you can only compare to files that is known by Git.
The contents are displayed for new files.

For Index (staged) files, git-diff can be used. If the file is new in Index, it will be presented to /dev/null. This allows for instance partial unstage of lines in the file.

**Comment by mstv** [comment]
This doesn't work well for a new **binary** file when it has been staged:
![grafik](https://user-images.githubusercontent.com/36601201/44314351-6e35f380-a418-11e8-91ca-83ea5e7f9edc.png)

As long as it is unstaged its contents *is* displayed:
![grafik](https://user-images.githubusercontent.com/36601201/44314342-4d6d9e00-a418-11e8-9296-52b5c62c0717.png)

**Comment by gerhardol** [comment]
If I remember correctly, the worktree (unstaged) binary detection is homegrown and not so reliable (should not be usedfor Index (staged) in my opinion).. There is also special handling for some image files so they are displayed. For other binary files we could just hide the output and avoid displaying them to give "consistency".
