### ISSUE TITLE
Find a better label for "Fetch all"

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#5330]
**Do you want to request a *feature* or report a *bug*?**
Improvement.

**What is the expected behavior?**

As discussed [here](https://github.com/gitextensions/gitextensions/pull/5324#issuecomment-414123588), I think that the "fetch all" label is too unclear because we don't know what are "all" the things that will be fetched (branches --what most of the new git users think-- or remote repositories?).

So I think we should find a better label.

Let's discuss about that!

I propose:

1. 'fetch from all remote repositories' (which I prefer)
1. 'fetch all remote repositories' 
1. 'fetch all repositories' 
1. 'fetch from all remotes'  (but i like it less because, by metonymy, is also used to talk about branch, no?)
1. 'fetch all remotes'

**Comment by RussKie** [comment]
Add to the mix `Fetch all from remotes`

**Comment by gerhardol** [comment]
'fetch all remotes'

**Comment by mstv** [comment]
'fetch all remote repositories' 
It could avoid misunderstandings because there are lots of hits for "fetch all remote branches" in the web.

**Comment by vbjay** [comment]
It's not that hard.
https://git-scm.com/docs/git-fetch#git-fetch---all

Fetch all is fine.

**Comment by RussKie** [comment]
@mstv _Fetch all_ doesn't only fetch branches, it also fetches tags.

**Comment by mstv** [comment]
I just wanted to express that if the label was changed, it should contain the word 'repositories' to avoid confusion for newbies, because the top 50 web search hits for "fetch all git" had been more related to branches than repositories.
Though I agree: 'pull/fetch' is such a basic concept of Git which every user should know.

**Comment by vbjay** [comment]
Exactly why the label doesn't need changing.

**Comment by gerhardol** [comment]
I have got questions about this also from users with ok git knowledge because they are just working with one remote. If you are coming from the centralized world you do not have need for multiple remotes. 

Fetch all remotes
Is still my proposal

**Comment by mdonatas** [comment]
I put my vote with @vbjay What I like most about GE is that labeling/menu options and the way interaction is done with git in general is very close to a command line (though I rarely use it). With this in mind `Fetch all` reflects the actual git command the closest.

**Comment by drewnoakes** [comment]
In general I also appreciate when the UI reflects the command line. It means I only need one mental model.

There is room for explanatory text in a tool tip however.

For example:

> Fetch all
>
> _Fetch branches and tags from all remote repositories_

**Comment by pmiossec** [comment]
I like the idea to explain in the tooltip (and keep the label unchanged, finally...)
