### ISSUE TITLE
FileStatusList: highlighted file name is too pale

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5331]
**Do you want to request a *feature* or report a *bug*?**
bad ux

**What is the current behavior?**
The file name of the highlighted file in the commit dialog is displayed too pale.
![grafik](https://user-images.githubusercontent.com/36601201/44314436-73e00900-a419-11e8-90ca-852c151c8dad.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the commit dialog and select a modified or new file.

**What is the expected behavior?**
The font color for the file name should be pure black.

I appreciate the new feature to display the file's path in gray.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
pre v3-ux

**Comment by NikolayXHD** [comment]
In Windows10 it's not pale, that may be the reason the problem was not noticed immediately.

**Comment by gerhardol** [comment]
The path and filename are separated since #5087, the path is supposed to be more gray than the filename.
However, not as pale as it seem to be in Win7 where it is hard to read.

This is somehow related to #5206 , there can be a space between path/filename.
