### ISSUE TITLE
Diff list: Collapse indicator of headings not clickable and can be invisible

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5332]
**Do you want to request a *feature* or report a *bug*?**
ux improvement

**What is the current behavior?**
The heading of a diff list can be double clicked what will collapse/expand the list.
But neither a single nor a double click on the collapse indicator have an effect.
![grafik](https://user-images.githubusercontent.com/36601201/44314678-b571b380-a41b-11e8-9354-bade4bf4cf14.png)
The collapse indicator can become invisible.
![grafik](https://user-images.githubusercontent.com/36601201/44314706-0da8b580-a41c-11e8-9910-11fe1fa9fa0c.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
The diff list should be collapsed/expanded by single clicking the collapse indicator.
The collapse indicator should always be visible.
![grafik](https://user-images.githubusercontent.com/36601201/44314689-dcc88080-a41b-11e8-925e-ff2aaba1fe4d.png)

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
have not checked yet

**Comment by RussKie** [comment]
The indicator was never clickable, the existing implementation doesn't handle this event. While it is an annoyance, it isn't a high priority issue right now. PRs are welcome though.

The fact that it may get invisible is a regression however.

**Comment by gerhardol** [comment]
You can double click the label to expand/collapse

**Comment by mstv** [comment]
I know, but it's not very intuitive to me. I don't use it every day. That's why it always takes some time until I remember / find out again how to do it. I agree that the additional event handler has low priority.

**Comment by mstv** [comment]
Today, I noticed that the indicator gets invisible when the scrollbar is activated due to long file names:
![grafik](https://user-images.githubusercontent.com/36601201/44491200-c3fcdc80-a660-11e8-8de0-4894bca55a53.png)
![grafik](https://user-images.githubusercontent.com/36601201/44491402-6026e380-a661-11e8-929b-272aad16454e.png)

**Comment by gerhardol** [comment]
So this is not a regression at least?

**Comment by mstv** [comment]
Yes, no regression -- especially because I cannot see the indicator in 2.51.02 at all:
![grafik](https://user-images.githubusercontent.com/36601201/44494559-8b630000-a66c-11e8-8ee5-44d108c27384.png)

**Comment by pmme** [comment]
Also in https://github.com/gitextensions/gitextensions/issues/4886
