### ISSUE TITLE
Improve overlay of Windows task bar icon

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5336]
**Do you want to request a *feature* or report a *bug*?**
discuss possible improvement of a recently added UX feature

**What is the current behavior?**
A small dot is displayed as an overlay on the Windows task bar icon in different colors indicating whether there are pending commits. (Only visible if large icons are shown in the task bar.)
![grafik](https://user-images.githubusercontent.com/36601201/44368596-9df60180-a4d3-11e8-8fac-6a68915c770e.png)

**What is the expected behavior?**
Especially the red dot merges almost with the GE icon.
Maybe the commit icon ![grafik](https://user-images.githubusercontent.com/36601201/44368914-b9add780-a4d4-11e8-86d2-aea0bea87c1b.png) and its colors could be used instead.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
new feature

**Comment by RussKie** [comment]
Would it help if the dot was more orangish/yellowish color?

**Comment by gerhardol** [comment]
The notification is not visible at all if using small taskbar icons. Color must be without red at all. 
Blue or white would work better.
