### ISSUE TITLE
Add setting that the commit message column fills the remaining width

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5337]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The browse window's column with the commit message has a fixed width.
The columns to the right can get scrolled out of the visible area when there are displayed many branches.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
scroll through commits where the number of parallel branches changes or
switch between "show all branches" and "show current branch only"

**What is the expected behavior?**
A setting should be added which resizes the message column automatically to fill the remaining width, similar to version 2.5. Then the columns to the right will be aligned to the right side, remain visible completely and will not jump around.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: (2.17.1.w.2-x64)
- OS version: (Windows 7)
- .NET version: (4.7)

**Did this work in previous version of GitExtensions (which)?**
2.5, though manual resizing of the rightmost column did not work well

**Comment by gerhardol** [comment]
Not clear of what you suggest. Align columns right of message to the right side and dynamic assign remaining to message?

**Comment by mstv** [comment]
Yes, that's my intention. I just want to get your comments before I start to implement it.

**Comment by vbjay** [comment]
Instead fix it to 50 character width for the first line limit based on the
font being used. Only show the subject. The indicator of a body will let
them know there is more info in the body. They can view the whole body in
the commit tab. If they have a longer than 50 character subject, ellipse
it.

**Comment by gerhardol** [comment]
Probably OK. The columns may stretch longer, so more difficult to see, but if the right columns are in a fix position it should be OK. A little more space for the message is welcome when there are branches.
