### ISSUE TITLE
Search settings should expand the whole tree

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5341]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
It seems that no setting has been found if the search string appears on nested pages only:
![grafik](https://user-images.githubusercontent.com/36601201/44491985-3969ac80-a663-11e8-9d6c-28564cdb2a2d.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- open `Tools` | `Settings`
- type "multi" as text to find

**What is the expected behavior?**
The whole settings tree should be expanded in order to see which pages contain the search string.
(This is important because the search string is cleared when the search field loses the focus.)
The first settings page containing the search string should be shown.
![grafik](https://user-images.githubusercontent.com/36601201/44492195-e8a68380-a663-11e8-8958-c251936b616b.png)

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: (2.17.1.w.2-x64)
- OS version: (Windows 7)
- .NET version: (4.7)

**Did this work in previous version of GitExtensions (which)?**
Not in 2.51.02 which shows the number of hits at least.

**Comment by RussKie** [comment]
> This is important because the search string is cleared when the search field loses the focus.

Perhaps we should be doing this
