### ISSUE TITLE
Check AppData\Local\Programs for editors and merge tools

### ISSUE THREAD

**Issue by otbutz** [gitextensions/gitextensions#5343]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
GitExtensions is not able to locate Visual Studio Code if it was installed only for the current user which is the new default as of version [1.26](https://code.visualstudio.com/updates/v1_26#_user-setup-for-windows). Gitextensions only recognizes installation folders right under `%LocalAppData%` judging from taking a look at [EditorHelper.cs](https://github.com/gitextensions/gitextensions/blob/c9b4e25536c8031ba761ba1d8a8c85d8157310bb/GitUI/CommandsDialogs/SettingsDialog/EditorHelper.cs#L52) and [MergeToolsHelper.cs](https://github.com/gitextensions/gitextensions/blob/c9b4e25536c8031ba761ba1d8a8c85d8157310bb/GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs#L61)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Install vscode using the new user installer
2. Select Visual Studio Code entry for `Settings`->`Git Extensions`->`Git Config`->`Editor`
3. Trigger the usage of the configured editor

**What is the expected behavior?**
GitExtension should check both `%LocalAppData%` and `%LocalAppData%/Programs`. The later one is used by vscode and a few other applications like eg Python.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.04
- GIT version: 2.18
- OS version: Windows 10 x64
- .NET version: ?

**Did this work in previous version of GitExtensions (which)?**
No.

**Comment by drewnoakes** [comment]
Can you create a PR?

**Comment by otbutz** [comment]
I'm gonna try ;)

**Comment by RussKie** [comment]
Don't try, just do it ;)

**Comment by drewnoakes** [comment]
Let us know if you need any help.
