### ISSUE TITLE
Jumplist for start menu shortcut breaks on upgrade

### ISSUE THREAD

**Issue by fsfod** [gitextensions/gitextensions#5344]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the GitExtensions start menu shortcut is pinned it shows a jump list for recently opened repositories. This all works correctly until GitExtensions is upgraded then it stops showing a jump list because the installer seems to be overwriting the existing shortcut with one that has no [AppUserModelID](https://docs.microsoft.com/en-us/windows/desktop/shell/appids) set in it. 

**If the current behaviour is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Freshly Install GitExtensions and pin it's start menu shortcut to the start menu and open a several repositories and then upgrade GitExtensions and pinned shortcut should stop showing a jump list of recent repositories. Sometimes windows weird heuristics will kick in and it might a show a simple entry in the jump list instead but the jump list will never update with recent repositories opened.
You can use the tool from this [blog post](https://emoacht.wordpress.com/2012/11/14/csharp-appusermodelid) to check the current AppUserModelID of the shortcut and update it to the correct value of "GitExtensions" to see jump list will start working again when the AppUserModelID is set.

**What is the expected behavior?**
The jump list for a pinned startmenu shortcut keeps working after GitExtensions is upgraded.

**Environment you encounter the issue:**

- GitExtensions version:
2.51.04
- OS version: 
Windows 10
- .NET version: 
4.7
**Did this work in previous version of GitExtensions (which)?**
no

**Comment by RussKie** [comment]
This seems related to #3021, @EbenZhang provided some insight in https://github.com/gitextensions/gitextensions/issues/3021#issuecomment-158752120

This may also be somewhat related to topic - https://github.com/gitextensions/gitextensions/pull/5310#issuecomment-412520562
