### ISSUE TITLE
Commit Dialog: "Show assumed-unchanged & skip-worktree files" without effect

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5346]
**Do you want to request a *feature* or report a *bug*?**
bug, regression

**What is the current behavior?**
The `Commit` dialog does not `Show assumed-unchanged files` anymore.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- change a file
- open the `Commit` dialog
- chose `Assume unchanged` from the modified file's context menu -> the files is not shown anymore
![grafik](https://user-images.githubusercontent.com/36601201/44596469-92a11f80-a7cc-11e8-9b32-b122ff9eaaed.png)
- chose `Show assumed-unchanged files`
- the file is still not shown
![grafik](https://user-images.githubusercontent.com/36601201/44596411-45bd4900-a7cc-11e8-9d96-00a488657344.png)

**What is the expected behavior?**
- assumed-unchanged files shall be listed if the option `Show assumed-unchanged files` is checked

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: 2.17.1.w.2-x64
- OS version: Windows 7
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
2.51.2:
![grafik](https://user-images.githubusercontent.com/36601201/44596303-f5de8200-a7cb-11e8-8e2e-7b9990a5e673.png)

**Comment by pmiossec** [comment]
And the behavior is the same with 'skip-worktree' (as it is the feature you should have used here)?

**Comment by mstv** [comment]
Could a member add labels, please?

**Comment by RussKie** [comment]
@pmiossec would you be able to have a look at this one?

**Comment by pmiossec** [comment]
I don't reproduce with last master and git version 2.16.1.windows.2...

**Comment by RussKie** [comment]
Thank you for checking.

**Comment by mstv** [comment]
Yes, it works again with the current master commit c2d183b (and Git 2.18.0.w.x64). It has worked at least since the master commit 6576050 of 2018-09-30 which was the base for my last build. In the weeks before, I must switch to 2.5x several times to view such files.
