### ISSUE TITLE
auto resize of tree view is problematic on projects with lot of branch

### ISSUE THREAD

**Issue by jlmxyz** [gitextensions/gitextensions#5363]
Hi,
The autoresize of columns is really annoying, just do some test on git's git repository, set a size for the tree view, then scroll... the column size is lost so it's annoying... and make the tree reading difficult... this option should be desactivable 
thanks and regards

**Comment by RussKie** [comment]
We have the issue template for a reason.
Please update your issue

**Comment by gerhardol** [comment]
In next version only the message column has dynamic sizing, the other have reasonable defaults.
So if you change size (for other than message), the size is preserved until you restart GE.

**Comment by RussKie** [comment]
Please try [RC2](https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00-rc2)
