### ISSUE TITLE
Colors settings get "squished" when opening settings with Colors node selected

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#5364]
Tested on `master` @`67f40897`

1. Open settings, go to `Colors`
2. Close
3. Open settings (`Colors` node is remembered) ->
![image](https://user-images.githubusercontent.com/483659/44783473-2a1ebd80-ab93-11e8-9cbb-b2e5f60ff05c.png)

**Comment by gerhardol** [comment]
Display scaling?

**Comment by mdonatas** [comment]
Umm, no. To be clear, this only happens when you open settings with Colors active. If you open settings dialog with any other node active and switch to Colors then everything is fine.

**Comment by gerhardol** [comment]
Reproduced at 100% scaling

**Comment by RussKie** [comment]
A quick review uncovered incorrect order of events - if the page isn't a landing page, then `SettingsToPage()` is called first, else `OnRuntimeLoad()` is called first.
The latter performs all necessary layouts, whilst the former assigns data to the page which is required for the correct layout....
