### ISSUE TITLE
VSIX icons are not updated for 3.0

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5368]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The GE icons have been updated for 3.0 (at least diff icon, other icons seem to be updated)
The vsix plugin is not updated though, in GitExtensionsVSIX\Resources
![commands](https://user-images.githubusercontent.com/6248932/44817518-f0c36d80-abe5-11e8-8995-f843a0bcc2bf.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Same icons as in GE

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
2.x

**Comment by RussKie** [comment]
I'd like to move VSIX to a separate repository as it doesn't need to be released with the same cadence as the app
