### ISSUE TITLE
Show repositories list in sidebar

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#5373]
TortoiseHG has a nice feature to show all repositories in sidebar.
GitExtensions has only dropdown list which is not enough.

https://tortoisehg.bitbucket.io/img/vt_history.png

**Comment by RussKie** [comment]
Why is it not enough?

**Comment by NN---** [comment]
I have more than 20 different repositories and in some of them I also use git worktree , which makes dropdown list not scalable enough.
Also it would be nice to have a folder structure tree for repositories and not list for all of them.
