### ISSUE TITLE
TaskCanceledException when selecting files in Commit dialog

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5376]
**Do you want to request a *feature* or report a *bug*?**
A major regression

**What is the current behavior?**
Attempts to select or deselect files in `FormCommit` take significant time (in order of seconds). At the same time `MainThreadScheduler` is choking on `System.Threading.Tasks.TaskCanceledException`

Here's the current master - here I click on single file, then do 'Select All' from keyboard and wait, and wait, and wait... it went on for about a minute after that VS crashed... The clip is much shorter, not to bore anyone:
![v3-current](https://user-images.githubusercontent.com/4403806/44945989-9c62fc80-ae36-11e8-8c4c-34827d4814a1.gif)

This is a tweaked version - it is still visibly slow, but much-much faster, on par with v2.5x.
Here I click on single file, then do 'Select All' from keyboard (do it three times):
![v3-updated](https://user-images.githubusercontent.com/4403806/44945901-198d7200-ae35-11e8-9665-89979be5df26.gif)

The tweak is pretty much a rollback to the v2.5x version of the code:
```diff
diff --git a/GitUI/UserControls/FileStatusList.cs b/GitUI/UserControls/FileStatusList.cs
index 4b07dc8ca..0b9f227e0 100644
--- a/GitUI/UserControls/FileStatusList.cs
+++ b/GitUI/UserControls/FileStatusList.cs
@@ -947,8 +947,8 @@ void EnsureSelectedIndexChangeSubscription()
                             h => FileStatusListView.SelectedIndexChanged += h,
                             h => FileStatusListView.SelectedIndexChanged -= h)
                         .Where(x => _enableSelectedIndexChangeEvent)
-                        .Throttle(SelectedIndexChangeThrottleDuration, MainThreadScheduler.Instance)
-                        .ObserveOn(MainThreadScheduler.Instance)
+                        .Throttle(SelectedIndexChangeThrottleDuration)
+                        .ObserveOn(SynchronizationContext.Current)
                         .Subscribe(_ => FileStatusListView_SelectedIndexChanged());
                 }
             }
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Open GE repository at 3d01d8af5efd896e6879d9175c29f7baa97a33c2
* Open `CommitDialog`
* Set to show ignored files
* Select multiple files (e.g. CTRL+A)

**What is the expected behavior?**
The selection should be quick, if not instantaneous. At least be on par with v2.5x.

**Environment you encounter the issue:**
Current master @ 3d01d8af5efd896e6879d9175c29f7baa97a33c2

**Comment by sharwell** [comment]
Thanks I'll take a look tomorrow or Monday

**Comment by sharwell** [comment]
I can reproduce this in both 2.51 and c61555fae2dfee8915bb469a442bc5e480b43f3f.

**Comment by RussKie** [comment]
Hmmm... I must admit I haven't run 2.5x code, just compared to an offical
installation I have.
Does 2.5x code choke with thread cancelled exceptions too?
Any idea why changing the scheduler makes such a dramatic difference?

**Comment by sharwell** [comment]
> just compared to an offical installation I have.

I was running with 2.51 from the regular installer, not building from source.

> Does 2.5x code choke with thread cancelled exceptions too?

The *debugger* chokes from cancellation exception, but they have almost no impact on normal usage. I'll submit a PR to address this either way.

**Comment by RussKie** [comment]
Thank you Sam.

Any other ideas what may be causing this horrendous lag?

**Comment by sharwell** [comment]
@RussKie I sent a pull request which should improve the experience considerably for cases where the exceptions can be observed (e.g. when a debugger or profiler is involved). It may fix things for you.
