### ISSUE TITLE
Feature request: branch tree view

### ISSUE THREAD

**Issue by miloja** [gitextensions/gitextensions#538]
It would be nice to have tree view of local and remote branches to be able to hide some of them. In our repository we have branches named like:
topic/[module_name]/[task_no], public/[user_id]/[whatever] and ability to hide or show some branches would be very helpful.
The tree configuration could be saved on .git subdirectory to be able to see different branches in different repositories.
The tree could have checkboxes to show/hide some branches and clicking on the leaf could jump to the selected branch on revision graph.

I've seen similar feature in some git UI for MAC and it was very helpful.

**Comment by sovaalexandr** [comment]
+1

**Comment by EbenZhang** [comment]
+1

**Comment by vbjay** [comment]
Look at the left-panel branch

**Comment by vbjay** [comment]
Sorry. Thought this was a new issue from my email.

**Comment by alexpop89** [comment]
+1

**Comment by jachymb** [comment]
+1

**Comment by magicyang25** [comment]
+1

**Comment by EbenZhang** [comment]
If someone wants to trial, [here](https://github.com/EbenZhang/gitextensions/releases/latest) I have a release for the left tree panel.

![image](https://user-images.githubusercontent.com/596334/31925301-6075d570-b8ba-11e7-9ed4-2d42ecfa7119.png)

**Comment by Nochdarus** [comment]
Tested (actually even worked) with version from @EbenZhang for some time already (my actual version is a merge between his and my own based on master). Left panel is pretty stable, totally recommend this implementation.
