### ISSUE TITLE
Create plugin to wrap git-ftp

### ISSUE THREAD

**Issue by SteveMcArthur** [gitextensions/gitextensions#5382]
git-ftp: https://github.com/git-ftp/git-ftp

**Use case:**
A project is still deployed via FTP. Most likely a website project. You either need to redeploy the entire project each time you want to update the deployment or try and just pick out the changes.

**git-ftp**
Git-ftp is a git addon that allows you to upload changes only to FTP servers.

I was wondering if it might be feasible to wrap git-ftp in a plugin for use within Gitextensions? I'm hoping that doing so might make adding the ftp facility relatively straightforward. At the moment I'm diving out of gitextensions and doing the ftp upload via the command line. Fine enough, but it would be better within gitextensions.

A couple of other issues (#1361, #1221) were raised around this situation and it seems nothing was done as this was a whole other project in itself. Now that the nuts and bolts have been done, this would hopefully only be a UI thing.

**Comment by RussKie** [comment]
There is a work slowly brewing on a back burner (so to speak) that will see all plugins moved out of the main repository, and have them hosted separately.
The process of installing and maintaining the plugin will likely be facilitated by https://github.com/maraf/GitExtensions.PluginManager by @maraf (#4885). Even in the absence of a plugin manager, a plugin is just an assembly (implementing certain interfaces with certain decorations) that lives under Plugins folder.

At this stage the core team has no spare capacity, and you're welcome to create your own plugin.

**Comment by vbjay** [comment]
https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks

You can use a hook to create a script that runs when commits are received.
I used this to create a git deploy script that deployed a website in an AWS
EC2 instance. All I had to do was push to a specific branch on the deploy
remote and the website would be live

**Comment by RussKie** [comment]
Jay is a master of GE scripts :)

**Comment by RussKie** [comment]
Create a plugin using https://github.com/gitextensions/gitextensions.plugintemplate. 
There are few examples: https://github.com/search?q=topic%3Agitextensions-plugin+org%3Agitextensions&type=Repositories
