### ISSUE TITLE
Submodule dropdown do not contain status

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5386]
**Do you want to request a *feature* or report a *bug*?**
bug, regression in master (before #5087)

**What is the current behavior?**
The submodule status is not updated in the dropdown

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The submodule status is constantly refreshed in the background to find changes to sub/super modules. Not just the current modules but the status should be updated.

Note: The handling is improved in #5375 

**What is the expected behavior?**
As in 2.x, status 
![image](https://user-images.githubusercontent.com/6248932/44960828-8c1a5280-af06-11e8-89b2-10c838e18723.png)

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
2.x

**Comment by gerhardol** [comment]
The list is updated before the status has been updated. (The occasional delay every 15s in 2.x when accessing the dropdown is much less noticeable in master).

In 2.x, the list was updated in UpdateSubmodulesList() using Task.Factory.StartNew(), in master ThreadHelper.JoinableTaskFactory.RunAsync() is used.

**Comment by RussKie** [comment]
Perhaps better to get all tasks and await them all with `Task.WhenAll`

**Comment by gerhardol** [comment]
To just await the submodule status will address the regression.
This will actually make the submodule menu list less responsive then it (accidentally) is in master compared to 2.x

If the status is updated async in the list instead, the status will improve instead, so that is what I will consider.

**Comment by gerhardol** [comment]
I implemented a hack that works reasonable for me, but is not ready to be merged: I do not know how to implement the async calls properly.

**Comment by jbialobr** [comment]
Do we need this detailed information about submodules status there? Perhaps it is enough to reuse the data we use to draw the status info in the revision grid?

**Comment by gerhardol** [comment]
> Do we need this detailed information about submodules status there? Perhaps it is enough to reuse the data we use to draw the status info in the revision grid?

Possibly, but it will limit the visible information.
The submodule status in the revision grid only have information for one level of submodules, so no recursive information. So if a submodule to a submodule has a changed checkout, the direct submodule is dirty. Of course no info for supermodules - we can maybe live with that.

I will miss the extra information, but believe that just requesting the submodule info for the changed submodules will be a good enough solution for performance reasons (maybe not for complexity). (I added some notes in the implementation about that.

@jbialobr Will look into your PR, thanks

**Comment by jbialobr** [comment]
I added async loading of the additional details in https://github.com/gitextensions/gitextensions/pull/5430/commits/c070592a6ea2f357c3246044c4fb2c29a1c516f5 so the menu opens fast and details are shown when loaded. Perhaps there could be an image indicating that the details are still being loaded.

**Comment by gerhardol** [comment]
> Perhaps there could be an image indicating that the details are still being loaded.

I suggest a separate PR for that, maybe including something similar to when we have requested update from GitStatusMonitor - more important in my opinion.
