### ISSUE TITLE
Not all languages are highlighted

### ISSUE THREAD

**Issue by pravic** [gitextensions/gitextensions#5395]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
GE does not highlight syntax of some languages whilst highlighting others.

Among those that [are supported](https://github.com/gitextensions/ICSharpCode.TextEditor/tree/master/Project/Resources), 

enabled are: Batch, C/C++, C#, HTML, Resource (rc)
disabled are: CSS, Delphi (.dpr), Pascal (.pas), JSON, Go, Rust

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

* Open any repository with code,
* Select any revision
* Click "File Tree"
* Select a file

**What is the expected behavior?**
Syntax highlighting for all supported languages.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.05
- GIT version: git version 2.18.0.windows.1
- OS version: Windows 7
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**
Don't know. Didn't work in the previous (2.51.04) for sure.

**Comment by drewnoakes** [comment]
Support for new types was added recently on the master branch and is not included in any of the 2.51 releases. Please hold out for 3.0. If you like, you could use one of the 3.0 CI builds. See the README for info.

**Comment by pravic** [comment]
I see. Unlike [master](https://github.com/gitextensions/gitextensions/tree/master/Externals), [the 2.51 version](https://github.com/gitextensions/gitextensions/tree/release/2.51/Externals) does not contain ICSharpCode.TextEditor.

**Comment by pravic** [comment]
3.0 works. Thanks.

**Comment by drewnoakes** [comment]
2.51 does include it, but a different build sourced via NuGet. In `master` we created a fork of the project and brought it in as a submodule to make it easier to make changes to the project, such as adding more language syntax, some high DPI fixes, hiding scrollbars when they're not needed, and other visual tweaks.

Thanks for verifying it works.
