### ISSUE TITLE
Cache cleanup plugin

### ISSUE THREAD

**Issue by Gutza** [gitextensions/gitextensions#5402]
I implemented a really simple cache cleanup plugin in [my fork](https://github.com/Gutza/gitextensions/commit/ba6e5c33e75d9f27feb45a1df1f8cb048f0b9deb) – it takes care of the issue [discussed here](https://stackoverflow.com/questions/1274057/how-to-make-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore#19095988) (removing files that now match the .gitignore, but were previously added in the repository).

The plugin is finished as far as I'm concerned (see above); I'm only opening this issue before submitting the PR per the procedure in [CONTRIBUTING.md](https://github.com/gitextensions/gitextensions/blob/c7209c422d3a819e11d4dd0d3555d18efdfc0687/CONTRIBUTING.md#pull-requests). Please let me know what you think.

**Comment by RussKie** [comment]
Thank you for the interest to contribute.

v2.51 is in maintenance mode and we won't be accepting anything beside
bugfixes into that branch.

For the upcoming v3 there is a work on a back burner (so to speak) that
will see all plugins moved out of the main repository, and have them hosted
separately. The process of installing and maintaining the plugin will
likely be facilitated by
https://github.com/maraf/GitExtensions.PluginManager by @maraf
<https://github.com/maraf> (#4885
<https://github.com/gitextensions/gitextensions/issues/4885>).
Until the plugin manager has materialised, a plugin can be manually
deployed into the Plugins folder.

We haven't fully explored where plugins would live (probably at nuget.org),
but I expect that we would maintain some sort of a list of plugins with
links to their repos/feeds to install.

**Comment by Gutza** [comment]
Fair enough, I get it – it can't be released, since 2.51 is in maintenance mode and v3 is in development. But are you telling me that it shouldn't get pulled into the main repo at all?

**Comment by RussKie** [comment]
Yes, I very much prefer that plugins lives separately from the app.

There are few reasons for that.
1. The codebase already has a number of plugins, which we assumed the
ownership of. However the core team doesn't have time (or inclination) to
fix or improve these plugins.
2. You, as a plugin author, may want to release new features or fixes to
your plugin, but being tied to the app's release schedule you are unable to
do so.
3. Bundled plugins make the compile-time experience more complicated
4. Bundled plugins make installer more complex and packaging process more
involved

My understanding @maraf is currently working on v3-compatible version, so
hopefully soon we may be able to experiment with it.

I hope this makes sense.

**Comment by Gutza** [comment]
I totally understand your position, and it makes complete sense. OTOH, you must understand that from my end it's rather frustrating to find you decided to freeze a process before you have something to replace it with. It's obviously your strategy and ultimately your call, and I understand it from a pragmatic point of view – it's disappointing and discouraging from a human perspective.

**Comment by RussKie** [comment]
Please don't take in wrong way - your work is not in vain, it is just there will be a different delivery mechanism. In mean time, it will need to be deployed manually.

In a similar fashion @pmiossec maintains his wonderful VSCode extension and we have a link to its repo on our front page.
