### ISSUE TITLE
Commit message are not visible

### ISSUE THREAD

**Issue by SachinMulimani** [gitextensions/gitextensions#5403]
**Do you want to request a *feature* or report a *bug*?**
-> A bug

**What is the current behavior?**
-> The commit messages are not visible and I am not able to find any option in the settings to enable this.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
-> Installed new version of Git extension 2.51.01
With older version this problem was not seen

**What is the expected behavior?**
-> Commit message of the users

**Environment you encounter the issue:**
-> Windows 7 OS

- GitExtensions version: 2.51.01
- GIT version: 2.18.0.windows.1
- OS version: WINDOWS 7
- .NET version: None

**Did this work in previous version of GitExtensions (which)?**
->Yes

**Comment by gerhardol** [comment]
screenshot?

**Comment by RussKie** [comment]
The current version is 2.51.05

**Comment by SachinMulimani** [comment]
[cid:image001.png@01D4469F.ABAA34F0]

Best regards,

S M Sachin
RBEI/EBA8

Tel. +91 80 6136-7553

**Comment by vbjay** [comment]
You have to attach the image on the actual github page.  Email attachments get stripped by github.

**Comment by RussKie** [comment]
@SachinMulimani we still can't see any images.
Please upgrade to the latest and try again. If your issues persist, please post some screenshots detailing your problems.

**Comment by vbjay** [comment]
Stop emailing attachments.  Github drops them.  Go here and paste or
drag/drop image into comment.

https://github.com/gitextensions/gitextensions/issues/5403

**Comment by SachinMulimani** [comment]
I am not able to add the image or screenshot, it says "Something went really wrong and we can't process that file. Try again"

**Comment by vbjay** [comment]
Take a screenshot using snipping tool or alt printscr. Follow the link to
the actual issue. Paste in the comment block.

**Comment by drewnoakes** [comment]
@SachinMulimani if you can't upload to github.com for some reason, please use a service like imgur.

**Comment by RussKie** [comment]
Please try [RC2 ](https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00-rc2)
