### ISSUE TITLE
TextView horizontal scrollbar causes content to jitter/jump

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#5404]
**Bug**
![](http://spurgius.com/interwebs/img/20180906222148_JumpingScrollbar.gif)

**What is the current behavior?**
Text view content jumping around when scrollbar auto-appears

**Suggestion**
I'd say either have a debounce/throttle for hiding the scrollbar or once it's shown don't hide it at all. Throttling might be better.

**Environment you encounter the issue:**
Master @ 58f3b6c1f44260f61095df165e9c0c7b50c9f91f

**Comment by drewnoakes** [comment]
This is an issue for https://github.com/gitextensions/ICSharpCode.TextEditor

**Comment by mdonatas** [comment]
That project doesn't have `Issues` enabled :)

**Comment by drewnoakes** [comment]
Good point! It does now.

**Comment by mdonatas** [comment]
Moved to https://github.com/gitextensions/ICSharpCode.TextEditor/issues/4
