### ISSUE TITLE
HELP! What is the latest version I could run on WindowsXP?

### ISSUE THREAD

**Issue by mynkow** [gitextensions/gitextensions#5417]
I am trying to figure out what is the latest version which could be installed on Windows XP.

PS: Please close this if it breaks any rules for which I am sorry

**Comment by vbjay** [comment]
https://www.microsoft.com/en-us/windowsforbusiness/end-of-xp-support

**Comment by mynkow** [comment]
I was able to install [v2.50.02](https://github.com/gitextensions/gitextensions/releases/tag/v2.50.02)

The only additional thing you have to do is to install `Consolas` font so that ConEmu stops breaking

**Comment by gerhardol** [comment]
.NET version was bumped in 2.51 so WinXP is not expected to work
The popup is related to a BuildServer plugin, so not core functionality

**Comment by cyberluke** [comment]
Perfect! This helps a lot. I'm fixing some opensource libraries and also support retrogaming (SlimDX, VJoy, FreePIE)
