### ISSUE TITLE
Github fork/clone dialog change protocol of remote

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5418]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/3629489/45300800-531d4780-b4dd-11e8-8732-6bb929adbf43.png)
The dialog only allows cloning using ssh protocol. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
To be able to switch to other protocols like https
**Environment you encounter the issue:**

- GitExtensions version:2.51.5  Probably master too
- GIT version: NA
- OS version: NA
- .NET version: NA

**Did this work in previous version of GitExtensions (which)?**
No

**Comment by digitalcoyote** [comment]
Looking into this.

**Comment by digitalcoyote** [comment]
I've got a plan to add this, but to prevent breaking other plugins, I've had to add an interface and use some minor reflection to determine if the option to select Https/Ssh is available for the plugin.

**Comment by digitalcoyote** [comment]
Sorry I mispoke it's not using reflection. I was doing this:
`repo.GetType().GetInterfaces().Contains(typeof(IHttpsOrSshCloneable))`

Then if it had that interface I was enabling the ability to specify the url used to be the ssh url or the https url instead of just using the CloneReadWriteUrl (which for github is the ssh url)

**Comment by digitalcoyote** [comment]
The clone command that is currently there can handle it as long as the IHostedRepository gives it the HTTPS URL.

I added 2 properties to the interface to allow checking if the IHostedRepository supports selecting a protocol. If it does, it will display the option to select one (and use the selected option when returning the CloneReadWriteUrl). Then the current clone method receives the correct URL and clones with the selected protocol.
