### ISSUE TITLE
About dialog Add system info 

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5419]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Have to run all over the place to get the current info for the environment section.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Add a feature that generates the following with filled in info in the about dialog.
```
- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 
```
**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**
No.

**Comment by Aceto1** [comment]
I would like to take this as my first ticket if it's not already taken. :)

**Comment by drewnoakes** [comment]
@Aceto1 go for it!

**Comment by vbjay** [comment]
Make sure the info can be coppied.

**Comment by Aceto1** [comment]
> Make sure the info can be coppied.

The whole block or each information individually?

**Comment by vbjay** [comment]
Whole block. Look at our issue environment block. I want to be able to hit
copy and paste over that block with the filled in info.

**Comment by drewnoakes** [comment]
+1 for the whole block. It should be easy for someone to copy/paste the info to the issue tracker.

Consider even adding a small clipboard icon button that copies it automatically. This way we can copy even more info than we display on screen.

**Comment by vbjay** [comment]
FYI.  the markedown is 

```
- GitExtensions version: {VALUE}
- GIT version: {VALUE} 
- OS version: {VALUE} 
- .NET version: {VALUE} 
```

Make sure you follow that format.  That way it looks like:

- GitExtensions version: {VALUE}
- GIT version: {VALUE} 
- OS version: {VALUE} 
- .NET version: {VALUE}

**Comment by RussKie** [comment]
Would be good (if possible) to append the same info when reporting an issue
from the app too

**Comment by vbjay** [comment]
Do you mean when the NBug window shows like this?  
![image](https://user-images.githubusercontent.com/3629489/45587801-ea690d00-b8d8-11e8-8aaf-c1b3ba988b69.png)
![image](https://user-images.githubusercontent.com/3629489/45587808-0c628f80-b8d9-11e8-9fc7-992d89207464.png)

**Comment by vbjay** [comment]
So copy the info to the clipboard and then navigate to the issues page.
Might want to show a toast saying environment info copied.

**Comment by RussKie** [comment]
Sure thing.  Though if we could automate it, why not.
Not as part of this PR, just thinking out loud.

**Comment by vbjay** [comment]
Taking this one over.  

Adding code to report issue and issues links to copy the block to the clipboard.

UI Changes:
![image](https://user-images.githubusercontent.com/3629489/47615975-08578f00-da8d-11e8-86d5-7766ceb16f5b.png)

**Comment by drewnoakes** [comment]
Good to see progress here.

Minor, but I think it'd look nicer on screen without the hyphens before each line. They're good in the copied text though.

Does the 'copy' button have a tooltip?

**Comment by RussKie** [comment]
Can we lay it out like this?

![image](https://user-images.githubusercontent.com/4403806/45788322-33480980-bcbd-11e8-8563-99b8a0729c7f.png)

**Comment by vbjay** [comment]
The table layout editing stinks. I fought with it to get it this far. I'll try to add the border lines but not wanting to battle the editor again.

**Comment by vbjay** [comment]
I can change the order like you ask. Border lines probably not.

**Comment by vbjay** [comment]
Got it.  
![image](https://user-images.githubusercontent.com/3629489/47617853-44491f00-daa2-11e8-8b85-739262207f7f.png)

**Comment by RussKie** [comment]
There is another library available called https://github.com/AArnott/Nerdbank.GitVersioning

**Comment by vbjay** [comment]
Not needed. This does the job.
