### ISSUE TITLE
Fetch menu item performs the default pull action

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5420]
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**

When clicking on Fetch menu item the default pull action is performed instead of fetch command.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Set rebase as the default pull action
2. Click on the Fetch menu item.

**What is the expected behavior?**

Fetch menu item should run git fetch command.

**Environment you encounter the issue:**

- GitExtensions version: f8946e9b9ea8449499ccb27fe5c97248de4bc3a6

**Comment by mstv** [comment]
A most likely related bug is described in #5407.

**Comment by amaiorano** [comment]
I'll take a look at this issue.

**Comment by RussKie** [comment]
No, please be my guest.
Shout if you need any assistance

**Comment by amaiorano** [comment]
Thanks, will do :)

**Comment by RussKie** [comment]
@jbialobr could you please confirm the fixhttps://ci.appveyor.com/api/buildjobs/njposwh2b900xr2t/artifacts/GitExtensions-Portable-3.00.00.3698.zip

**Comment by jbialobr** [comment]
It works as intended now. Thanks!
