### ISSUE TITLE
Portable builds

### ISSUE THREAD

**Issue by diggernet** [gitextensions/gitextensions#5431]
**Do you want to request a *feature* or report a *bug*?**

Neither. 

**What is the current behavior?**

The -portable build product only exists for v2.51.02.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

The -portable build product should be built for all releases.

**Environment you encounter the issue:**

- GitExtensions version: v2.51.03+
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

V2.51.02

**Comment by gerhardol** [comment]
The Mono build is the same as the portable.
The build was accidentally renamed in .02 which confused Mono users

In master (where Mono is not supported), the name is portable

**Comment by gerhardol** [comment]
The mono package can be used in linux
