### ISSUE TITLE
Use diff icon for revision grid context menu item "Compare"

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5432]
**Do you want to request a *feature* or report a *bug*?**

UI Improvement.

**What is the current behavior?**

The revision grid's context menu is missing an icon for _Compare_:

![image](https://user-images.githubusercontent.com/350947/45586356-f6ab9500-b8ed-11e8-93be-38d652807f1b.png)

We should use the diff icon there.

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: N/A
- OS version: N/A
- .NET version: N/A

**Did this work in previous version of GitExtensions (which)?**

No.

**Comment by markashleybell** [comment]
Hi, I'll pick this one up if that's OK? Will (hopefully!) be a nice simple one to get me up to speed with the project structure etc.

**Comment by drewnoakes** [comment]
Perfect! Go for it, and shout if you need any help.
