### ISSUE TITLE
Show keyboard shortcuts for all navigation menu items

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5433]
## Current behaviour

There are a few related menus that don't display their existing short cuts keys in the context menu.

Showing these is a great way to let users know that they exist.

I mention a few `RevisionGridControl.Commands` usages that don't have current short cuts defined. We can take this as an opportunity to consider whether we want to add any.

There are others I didn't write out. For the complete list, see `HotkeySettingsManager.CreateDefaultSettings`. I list out some here to show the scope and impact of this change. 

### Navigate menu

![image](https://user-images.githubusercontent.com/350947/45586250-961b5880-b8eb-11e8-90a7-46c64627f8f1.png)

There are short cuts for:

- [ ] Go to current revision (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>C</kbd>)
- [ ] Go to commit... (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>G</kbd>)
- [ ] Go to child commit (<kbd>Ctrl</kbd>+<kbd>N</kbd>)
- [ ] Go to parent commit (<kbd>Ctrl</kbd>+<kbd>P</kbd>)
- [x] Navigate backward (<kbd>Alt</kbd>+<kbd>Left</kbd>)
- [x] Navigate forward (<kbd>Alt</kbd>+<kbd>Right</kbd>)
- [ ] Quick search (no command, but could say "Type into grid" or similar)
- [ ] Next quick search (<kbd>Alt</kbd>+<kbd>Down</kbd>)
- [ ] Previous quick search (<kbd>Alt</kbd>+<kbd>Up</kbd>)

### Compare menu

![image](https://user-images.githubusercontent.com/350947/45586535-c7e2ee00-b8f0-11e8-8df8-ae32672d9cf1.png)

- [ ] Compare to branch... (no shortcut)
- [ ] Compare to current branch (no shortcut)
- [ ] Select as base to compare (<kbd>Ctrl</kbd>+<kbd>L</kbd>)
- [ ] Compare to base (<kbd>Ctrl</kbd>+<kbd>R</kbd>)
- [ ] Compare to working directory (<kbd>Ctrl</kbd>+<kbd>D</kbd>)
- [ ] Compare selected commits (no shortcut)

### View menu

![image](https://user-images.githubusercontent.com/350947/45586572-5a838d00-b8f1-11e8-8cda-0e26e8d26fe0.png)

- [ ] Show all branches (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd>)
- [ ] Show current branch only (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>U</kbd>)
- [ ] Show filtered branches (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>T</kbd>)
- [ ] Show remote branches (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>)

- [ ] Toggle show merge commits (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd>)
- [ ] Toggle show tags (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>T</kbd>)
- [ ] Highlight selected branch (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd>)
- [ ] Show first parents (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>S</kbd>)

### Advanced menu

![image](https://user-images.githubusercontent.com/350947/45586788-35444e00-b8f4-11e8-9478-bb65393151aa.png)

- [ ] Create fixup! commit... (<kbd>Ctrl</kbd>+<kbd>X</kbd>)

## Workaround

- Click on menu Tools, Settings, Hotkeys
- Click on the Apply button

Please note that this workaround will work until you exit from Gitextensions: as soon you restart it the shortcut are again missing from menuitems.

- Before
![gitextensions_navigate_menu_before](https://user-images.githubusercontent.com/31626/57353680-906bcf00-7169-11e9-9a62-fdaa8f9d4a5c.jpg)
- After
![gitextensions_navigate_menu_after](https://user-images.githubusercontent.com/31626/57353684-9497ec80-7169-11e9-8d27-1b27df12ba2e.jpg)

## Expected behaviour

I expect to see all defined shortcuts for menuitems

## Steps to reproduce

Simply start Gitextensions and for example click on the Navigate menu

## Environment

- Git Extensions 3.1.0.5766-RC1
- Build 497059b2205086d8a44a33dd29f2cae2b4bfffc2 (Dirty)
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.6.1055.0
- DPI 96dpi (no scaling)

## Did this work in previous version of GitExtensions

No.

**Comment by mstv** [comment]
All listed hotkeys *are shown* in the menus.
I.e. from this issue remains
* to check the other hotkeys from `HotkeySettingsManager.CreateDefaultSettings`,
* to consider whether and which shortcuts should be assigned to `Compare to branch...`, `Compare to current branch`, `Compare selected commits`.

**Comment by mstv** [comment]
I fully agree.

Maybe someone has added them in the meantime and didn't reference this issue:
![grafik](https://user-images.githubusercontent.com/36601201/45631784-f94bed00-ba9b-11e8-9a9e-ade4b91d1399.png)

**Comment by mstv** [comment]
![grafik](https://user-images.githubusercontent.com/36601201/45631894-4c25a480-ba9c-11e8-8c91-7ac0ec18baf7.png)

**Comment by drewnoakes** [comment]
Strange. I don't see them on my machine. Just tested in the 3.0-beta1 and they're missing from the context menus.

They're present for navigate backward/forward, but not elsewhere.

**Comment by RussKie** [comment]
I can see them 
![image](https://user-images.githubusercontent.com/4403806/45685638-5378ab00-bb8d-11e8-9846-ee6405089668.png)

**Comment by RussKie** [comment]
@drewnoakes would you be able to check against the actual code to confirm whether shortcuts are missing?

**Comment by mast-eu** [comment]
Found the pattern:
When opening the repo directly ( i.e. bypassing the dashboard), I see all shortcuts.
Instead, when opening the repo from the dashboard, I don't see the shortcuts.

**Comment by Otiel** [comment]
For me it's:
* Open GitExtensions
* Open a repository through the Dashboard
* Most shortcuts aren't displayed (i.e. `Navigate → Go to current revision`), either through the main menu or the context menu

A simple workaround is:
* Open `Tools → Settings`
* Close window (click `Cancel` or hit <kbd>Esc</kbd>)
* Shortcuts are now displayed
