### ISSUE TITLE
Diff tab: can't select file in the file list

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5438]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Unable to select files after resize events. The entries can't be clicked on, unless the listview is resized in a specific way and scrolled to the left
![diff-tab-bug-2](https://user-images.githubusercontent.com/4403806/45593383-dac8f180-b9c8-11e8-9489-5c1c465208e7.gif)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Courtesy of @NikolayXHD:
1. Set `truncate long filename` setting to `None`
2. resize file status panel to the size when horizontal scroll appears
3. move scroll to the right (not necessarily rightmost) position
4. [optional] double-click group header twice to collapse and re-expand the group
5. resize the panel in 1 large movement, larger than the missing width created on step 2. 

Note: step 4 is optional. collapse / expand does not have to do with the issues at all.
The problem is caused by resizing the panel while the scroll is not in leftmost position

**What is the expected behavior?**
Entries can be selected

**Environment you encounter the issue:**
Current master @ 7c4e8c5758c4d2a27703ad656973e3942ed128bb

**Did this work in previous version of GitExtensions (which)?**
No, 2.51 exhibits the same behavior

**Comment by slate-dk** [comment]
Just upgraded to 3.00.00.4433 and had this happen to me almost immediately.
Did not see it with the 2.5.** I used previously

Reopened client and problem was gone; not able to recreate immediately.

GitExtensions version: Version 3.00.00 4433
OS version: Windows 7
.NET version: 4.6.2
Machine specs:
Intel Core i5-6820HQ @ 2.70 GHz
32GB RAM

**Comment by gerhardol** [comment]
Please open a new issue, this specific issue has been fixed
