### ISSUE TITLE
Refreshing the repo status takes too long.

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5439]
**Do you want to request a *feature* or report a *bug*?**

It is more like a bug.

**What is the current behavior?**

Eagerly loading all the ignored files slows down the regular status query.
When you have tens of thousands of ignored files it can take up to a minute to get git status completed
when run with ignored files included. Since we base the working dir and commit index info on this, it is a poor experience to have to wait that long for seeing changes to be reflected in the revisions grid.

**What is the expected behavior?**

The state of the working dir and commit index should be refreshed almost immediately.
As discussed in https://github.com/gitextensions/gitextensions/pull/5429, perhaps the best solution would be to drop the ignored files handling at all.

**Environment you encounter the issue:**

- GitExtensions version: e5384d73c6396ff4ceef8651ef9e151dbc71a58c

**Did this work in previous version of GitExtensions (which)?**

I think it was, when the ignored files where loaded separately.

**Comment by gerhardol** [comment]
Background:
GE uses a FileStatusWatcher to detect when files have changed on the file system. Every file changed/created/etc will trigger a call. When there are changes, a quite heavy git-status is started. Before 2.51.04, these background runs could cause other commands to fail.

To avoid running the git-status constantly at for instance builds, the command tries to exclude ignored files. In 2.x, the ignored files are listed in the background with git-ls-files. This command can in some situation require a lot of cpu, see for instance #4256. In 2.x, the git-status command can run constantly at changes.
In 3.x, the ignored files are listed with git-status --ignored, as well as the git-status run interval is adaptive to decrease the cpu load: First change is listed after 1s, the following after 3s, more if git-status requires more than 3s. However, as the first invocation of git-status has --ignored, it will take longer to see first status when opening a repo which is a regression.

There are a few bugs in the current implementation in master:
* The check for new changes should return immediately when a new scheduling of git-status is done (currently the file system changes for the first second will try to schedule updates). (fix discussed in #5429)
* When changing a repo, the git-status could fail to update and run constantly
* Listing all ignored files could require a lot of RAM. This could be improved with primarily storing directories in ignored files, but that will instead increase CPU load when checking.

Some possible solutions discussed in https://github.com/gitextensions/gitextensions/pull/5429#issuecomment-421801456. That PR is a fine attempt to limit load, but unfortunately will not limit the git-status invocations much.
As listing, storing and checking ignored files has drawbacks, it may be better to let git-status run periodically without checking ignored files.

**Comment by gerhardol** [comment]
Some assumptions about the scenario the commit is used and how it should work.
5. is probably best in normal repos, but 2. should work somehow also  in extreme situations (many ignored directories and many updates).

* Changes in tracked (and new) files is done sporadic and normally a couple of handful at a time. 
* Ignored files are updated many at a time when building. There can be a very large number of ignored files but the directories they appear in is limited to hundreds. When building it is ok to wait a little longer to update the commit counter. Ideally, GE should detect ignored files to limit git-status invocations (and give fast response times for tracked files). 

Whatever is used, #5429 should be the basis for changes
(numbering from https://github.com/gitextensions/gitextensions/pull/5429#issuecomment-421801456)

 0.  As done in #5429 

Only some files were added to to ignore list so ignored files will have effect first after several builds.

 4.  #5429 but remove early return in WorkTreeChanged() if an update is detected (will have effect on CPU load to some extent)

While #5429 had very quick response times for git-status with few changes, the time will increase. The ignore list is still potentially big.

 1.    Use git-status --ignored without candidates to get a full ignored list quicker. --ignored will only run when there are new ignored files

The ignore list will be up to date after a build is done. The longer time for git-status --ignore will give slower commit count update for the first build.

 2.   Remove the ignored list, as it it is not used anyway

git-status will run in the background at every build (dynamically throttled still), increasing CPU load. Lower RAM usage though.

 3.    Simple hardcoded .gitignore parsing to filter obvious files and directories (rather not do this)

If the filter is quick, it would be ideal, but I doubt this is possible.

 5. git-status --ignored=matching

The ignore list should be reasonable short and as long as there are changes to new tracked or ignored files, the check for changes is quick. With only known ignored files the check can require CPU time. An example if 100 ignored files a second are changed and there are 100 ignored directories, there could be 100*100 StartsWith() checks. Probably OK. The git-status throttling will not kick in so changes will be detected quick.

**Comment by gerhardol** [comment]
#4327, #4328 limits how often GE checks for changes. This will also increase the initial time before changes are seen.
The scenario where "filesystem changes detected" could still have the increased time (1s) before running git-status, but "gitmodule changed" could have a lower delay (say 200ms). Testing a change.

I cannot really decide for 5. or 2. Will probably go for 2. as it is simpler and more predictable. Some further throttling will be needed for #5375 though, more important with 2. than 5. (just limit updates to at least 15s should be OK).

**Comment by RussKie** [comment]
Let's go with 2, as it sounds simpler.
We can iterate further after, if necessary.

**Comment by gerhardol** [comment]
Submitted a PR

If ignore handling is reintroduced, I suggest another alternative:
6. Calculate ignored only for updates triggered by file system changes when the interval is limited (i.e. the periodic, throttled updates, not the interactive or first updates). No more often than every 5th min still (?).

Related to this:
 * a refresh in Browse should trigger recalculation
 * GitStatus changes triggers Browse submodule status updates, should be throttled (every minute?)
If this is closed, a separate PR should be opened
