### ISSUE TITLE
Duplicate line breaks when copying from individual file history

### ISSUE THREAD

**Issue by Livven** [gitextensions/gitextensions#5440]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Copying file contents from the history of an individual file occasionally causes duplicate line breaks.

Seems to only happen in a specific repo and only in some files within it. Notably, it doesn't seem to happen in newer files, so it might be some kind of legacy issue. Nonetheless, the duplicate line breaks do not show up on checkout or in the UI, so I think there is definitely room for improvement here.

I experimented a bit with copying-and-pasting the contents into a hex editor (HxD) and found that sometimes the issue would fix itself. Also, it seems that the actual contents are `\r\r\n` when pasted into the hex editor. After pasting into a text editor and then the hex editor, it becomes `\r\n\r\n`.

Happens with `core.autocrlf` as `true` and unset.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open repo.
2. Switch to "file tree" tab.
3. Select text file.
   1. Alternatively double-click a text file and select the "view" tab in the file history window.
4. Select file contents and copy and paste into another text editor.
5. Every line break is duplicated in the pasted text.

**What is the expected behavior?**

No duplicate line breaks are introduced when copying, consistent with what is shown in the UI.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.05
- GIT version: 2.19.0.windows.1
- OS version: Windows 10
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

Not sure, since it seems to be specific to one repo.

**Comment by Livven** [comment]
Managed to create a minimal repro repo, [here it is](https://github.com/gitextensions/gitextensions/files/2388342/repro.zip).

**Comment by RussKie** [comment]
I've experienced the same, it drives me mad sometimes. But I never had enough time and there is always something of higher priority to look at it.
Thanks for the repro, hopefully someone may be able to look at it.

**Comment by vbjay** [comment]
Autocrlf
GitAttributes

The diff is showing the stored contents and not the content that would be
checked out.

**Comment by mstv** [comment]
In general, line breaks should be normalized when copied to the clipboard.

Especially, when pasted into the Visual Studio Editor, files will be saved with inconsistent line breaks.
Yes, it is a weakness or strange feature of a foreign tool. (I know the VS option "Check for consistent line endings *on load*" which deals with this issue much too late.)
