### ISSUE TITLE
Separator toolstrip ui

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5442]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/3629489/45628410-04822700-ba62-11e8-8f4f-092a4ea3f6a5.png)
Separators look odd with items that have dropdown arows.  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Make it clear that the dropdown arrow is part of the item.  
**Environment you encounter the issue:**

- GitExtensions version:3.0.0-beta1
- GIT version: NA
- OS version: NA
- .NET version: NA

**Did this work in previous version of GitExtensions (which)?**

**Comment by RussKie** [comment]
Here's how it looks on W10
![image](https://user-images.githubusercontent.com/4403806/45917047-dca42080-beb2-11e8-9d60-5fa31ab610dd.png)

What's your OS?

**Comment by vbjay** [comment]
I just noticed.  WIndows 10 at home looks fine.  Windows server 2012 at work doesn't.

**Comment by RussKie** [comment]
I think server OS have restricted UI rendering capabilities/styles, so I don't think we can do anything about this.
Suggest to close as I can't see anyone really spending time on this.

**Comment by vbjay** [comment]
Sure.  No problem.
