### ISSUE TITLE
Font scaling issues under Mono

### ISSUE THREAD

**Issue by KocsisV** [gitextensions/gitextensions#5445]
I'm experiencing some font scaling/rendering issues under Linux/Mono.

Seems like all the fonts on the opening screen (no repo opened) and the menu bars are using a larger font size than the available space.
This issue happened after upgrading to Mono 5.14.0.177. With 5.12.0.301 it works fine.

Old mono (xenial/snapshots/5.12.0.301):
![gitext_with_mono_old](https://user-images.githubusercontent.com/39518109/44254931-9fd67100-a204-11e8-8ff3-61bd8a8ea1c1.png)
New mono (5.14.0.177):
![gitext_mono_new](https://user-images.githubusercontent.com/39518109/44254939-a4028e80-a204-11e8-82b7-89ec250c7f38.png)

I saw no option to change the font size (of the menus). Also, some menu icons are missing from the toolbar as you can see on the screenshots (after the refresh/go to subproject icons). Ignore the missing recent repo/etc from the first (older mono) screenshot . That happened after lof of back and forward mono / gitext version change, it worked before. On the second the recent repos list are not correctly scaled, it cuts the repo locations in half.
Take a look at the "Branches" drob down box. It's larger than the available space.

xdpyinfo reports 96*96dpi.

- GitExtensions version: 2.51.05
- OS version: Ubuntu 16.04
- .NET version: Mono 5.14.0.177

**Comment by RussKie** [comment]
So would you say it is a Mono issue or a GE issue?

**Comment by KocsisV** [comment]
Both? I don't know. Maybe it would be worth to contact the Mono dev-s since this last update broke GitExt. I don't think this is an isolated issue to just GitExt, but since I do not use anything else that relies on Mono (and having the same issue), I can't tell.
If I open any modal window (eg settings), the left side recent list displays correctly. If I close it its back to the state you see in the original post.

![image](https://user-images.githubusercontent.com/39518109/45682326-45e90400-bb40-11e8-9846-b414f17d88bd.png)
