### ISSUE TITLE
Dropdown/combo box scroll bar displays wrongly under Mono/Linux

### ISSUE THREAD

**Issue by KocsisV** [gitextensions/gitextensions#5446]
In all combo box/dropdown box if its large enough a scroll bar appears, but on the wrong side.

See this image:
![image](https://user-images.githubusercontent.com/39518109/45676181-707f9080-bb31-11e8-80cb-cd33f19a8700.png)

xdpyinfo reports 96*96dpi.

- GitExtensions version: 2.51.05
- OS version: Ubuntu 16.04
- .NET version: Mono 5.14.0.177

I don't remember if was working in an older release of mono/gitext. Might be related to #5445 .

**Comment by RussKie** [comment]
This look wrong...

Here's how it looks under Mono 5.2
![image](https://user-images.githubusercontent.com/4403806/45682241-0ee81200-bb83-11e8-837d-3e8a5af7d020.png)

My VM with Mono 5.14 crashed so I can't test it right now

**Comment by KocsisV** [comment]
Seems like a newer mono version fixed this issue (5.16.0.179).

**Comment by RussKie** [comment]
Thank you for the update
