### ISSUE TITLE
Branch visualization stops after a number of commits.

### ISSUE THREAD

**Issue by KocsisV** [gitextensions/gitextensions#5447]
I'm working on a few repositories with high number of commits/branches in a short period of time.
If I open that repository and scroll down, then the branch visualization stops after around 300 commit.

Is this an intended behavior and is there a setting for this? Or is this a bug?

For example here is the opencv repository:
![image](https://user-images.githubusercontent.com/39518109/45677354-411e5300-bb34-11e8-95f3-021af0ee8286.png)

- GitExtensions version: 2.51.05
- OS version: Ubuntu 16.04
- .NET version: Mono 5.14.0.177
- GIT version:  2.18

**Comment by vbjay** [comment]
Look at your settings. We have a setting to limit tte number of commits. We
really need to make it virtual and load on demand. The issue is if we
proccessed all commits to the root, it would lag.

**Comment by KocsisV** [comment]
You mean the "Git Extensions/Git Extensions/Limit number of commits that will be loaded at startup" option? That is already set to 100000.

**Comment by RussKie** [comment]
The app limits number of commits via settings, but from your screenshot it is not it.

**Comment by RussKie** [comment]
did it work before under an older version of Mono? is it a repo specific? do you get the same behavior on a Windows machine?

**Comment by RussKie** [comment]
I think it may be a bug under Mono
It is happening in 2.51.04 under Mono 5.2. for me too:
![image](https://user-images.githubusercontent.com/4403806/45682352-68e8d780-bb83-11e8-84c0-9e818942db85.png)

**Comment by Wirone** [comment]
I have the same issue when I scroll down to some point in the past. It's not repo-specific.

![image](https://user-images.githubusercontent.com/600668/54994572-deb37d00-4fc4-11e9-9a51-ca11543adab8.png)

GitExtensions 2.51.05, Mono JIT compiler version 5.10.1.20
