### ISSUE TITLE
Submodule toolbar button suggestion

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5451]
**Do you want to request a *feature* or report a *bug*?**

UI suggestion.

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/350947/45696621-e26ccf80-bb5b-11e8-8e7d-02104ad800c1.png)

The icon's tooltip says "Go to superproject". Its drop down shows submodules.

This repo (gitextensions) does not have a super project.

Clicking the blue arrow icon causes the drop down to open.

**What is the expected behavior?**

I think this would be an improvement to clarity and ease of use:

- _Go to superproject_ becomes an item in the dropdown, hidden if not applicable
- The drop down button is retitled "Submodules" and its icon is `SubmodulesManage.png`

![image](https://user-images.githubusercontent.com/350947/45697331-7be8b100-bb5d-11e8-86d2-1a5ccae234da.png)

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: N/A
- OS version: N/A
- .NET version: N/A

**Did this work in previous version of GitExtensions (which)?**

I don't remember.

**Comment by gerhardol** [comment]
I definitely want to keep the option to press submodule button to go to super.
When working in a submodule, it is a quick way to go to the supermodule

But the icon can be changed, it could even have an aggregated status for the contained modules.
The tooltip could be changed when there are no supermodules though

**Comment by drewnoakes** [comment]
Maybe _Go to superproject_ is a sibling button to the submodule drop down list.

**Comment by gerhardol** [comment]
@drewnoakes Is the PR OK?
