### ISSUE TITLE
Cannot uninstall GitExtensions (Windows 10)

### ISSUE THREAD

**Issue by seahar** [gitextensions/gitextensions#5457]
*bug*

When attempting to uninstall on Windows 10 from "Control Panel > Programs > Programs and Features" I am prompted with the following.
"There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor."

The reason that I am trying to uninstall is because the program (GitExtensions) is requiring me to enter admin credentials every time I open the program. I have not been able to remove this requirement and therefore am trying to uninstall and reinstall the program.

I have also attempted to repair, reinstall, and uninstall using the installer program but this same message appears there also.

- GitExtensions version: 2.51.05
- GIT version: 2.18.0
- OS version: 10.0.17134 Build 17134
- .NET version: unknown

**Comment by gerhardol** [comment]
This does not seem to be a GE specific issue. The installer has no specific handling to request or disallow admin.

It seems like you installed GE with elevated privileges, you need to uninstall in a similar way before you can make a normal install.

**Comment by RussKie** [comment]
How did you install the app originally?

**Comment by seahar** [comment]
@gerhardol I agree this may not be a Git Extensions issue. I don't know of a way to explicitly attempt to uninstall with elevated privileges, however, I have had our IT department attempt to uninstall this as well without success as of yet. 

@RussKie I originally installed a couple years go with a much older version of Git Extensions while on Windows 7. I don't recall checking any admin requirement check boxes during install or anything like that but then again it was a couple years ago... I likely found the install package on GitHub or possibly SourceForge at that time.

I appreciate the input

**Comment by RussKie** [comment]
Are you able to rename/delete C:\Program Files (x86)\GitExtensions folder?
And then install a fresh copy?

**Comment by seahar** [comment]
I was able to get admin rights for this program, for now ill just leave close this out until it become a problem for me again...

@RussKie I don't know why I never thought to do that but if i have problems again, ill give it a shot. Thanks.
