### ISSUE TITLE
Show stashes tree in sidebar

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#5460]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
No tags and stahes in sidebar

- GitExtensions version:
3.0
- GIT version: 
2.9
- OS version: 
Windows
- .NET version: 
4.7

Is it possible to have something similar to SourceTree tags and stashes in sidebar ?
![](https://www.sourcetreeapp.com/dam/jcr:580c367b-c240-453d-aa18-c7ced44324f9/hero-mac-screenshot.png)

**Comment by pmiossec** [comment]
Tags are already there but you should enable it in the "gear" displayed near the search field.

I absolutely agree for stashes.

**Comment by NN---** [comment]
Cannot find it.
Shouldn't it be by default enabled ?

**Comment by NN---** [comment]
I don't see this in GitExtensions 3.0 Beta

**Comment by pmiossec** [comment]
Really strange. It should be there...
You don't have the gear displayed? Or it is empty?
I don't think there is a setting for that....

**Comment by NN---** [comment]
Oh sorry.
It is there, I just didn't notice this one.
Thanks !

**Comment by francoas** [comment]
I would suggest to enable it by default

**Comment by vbjay** [comment]
It should be enabled and remembered. I hate having to hit show tags each
time I load GE.

**Comment by francoas** [comment]
I agree with you: it should be enabled by default (no need for the gear, unless you want the ability to configure also Branches and Remotes nodes)
Now it looks like it is remembered, but it should also remember the "open" or "closed" of the node. 
I also suggest that tags could be "reverse" ordered (just see the gitextensions project tags to understand why)

**Comment by gerhardol** [comment]
For stashes in the sidebar to be meaningful, the stashes need to be displayed in the revision grid too.
This is handled in #5371.
