### ISSUE TITLE
Unable to launch git extension on Ubuntu

### ISSUE THREAD

**Issue by shridharkalagi** [gitextensions/gitextensions#5463]
I'm unable to launch the gitextension on Ubuntu machine (18.04). 

- GitExtensions version: 2.51.05
- GIT version:  2.17.1
- OS version:  Ubuntu machine (18.04) 
- .NET version: 
Mono JIT compiler version 4.6.2

Here is the [gist](https://gist.github.com/shridharkalagi/79db64e5c6ee338176b851dd51482912) of error

**Comment by RussKie** [comment]
You Mono is too old and not supported. Please update Mono to the latest

**Comment by vbjay** [comment]
![screenshot_20180921-063743](https://user-images.githubusercontent.com/3629489/45876592-0d783e80-bd69-11e8-911d-8bcebe371a58.png)
All in the readme.

**Comment by RussKie** [comment]
v3 only runs on Windows. v2.51.05 is the last one you can run on Linux/Mono.

**Comment by arisliang** [comment]
I had the same issue with supported versions of mono, gitextension, etc. After upgraded git from 2.17.1 to 2.19.1, git extension launched.

**Comment by arisliang** [comment]
I'm unable to launch the gitextension on Ubuntu machine (18.04).

GitExtensions version: 2.51.05
GIT version: 2.19.1
OS version: Ubuntu machine (18.04)
.NET version:
Mono JIT compiler version 5.16.0.179

Gist of the error message: [https://gist.github.com/arisliang/482ac974c2a326a90ebddd4adccadc6d](url)
