### ISSUE TITLE
I am using the git extensions from past 2 months on the same machine but all of sudden unable to launch git extensions, it keeps on crashing every time I try to launch. Its windows Machine. I get an exception popup which shows the exception type as "System.NotSupportedException" and "Vararg calling convention not supported"

### ISSUE THREAD

**Issue by KalyanAsula** [gitextensions/gitextensions#5465]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by KalyanAsula** [comment]
I am using 2.51.05 version

**Comment by vbjay** [comment]
We have an issue template for a reason.

**Comment by RussKie** [comment]
Please fill the report correctly, then we'll re-open it.
