### ISSUE TITLE
Issue Template enforcement

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5467]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
People seem to be ignoring the issue template.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
  I say we create a label like TemplateNotFilled and alter the issue template to say if this isn't filled out the label will be applied and the issue closed.  
**Environment you encounter the issue:**

- GitExtensions version:NA
- GIT version: NA
- OS version: NA
- .NET version: NA
Github repo area 

**Did this work in previous version of GitExtensions (which)?**
Somewhat.

**Comment by RussKie** [comment]
Support the motion

**Comment by pmiossec** [comment]
If we do that, we should update the template to manage other type of issues than bug and feature, like discussion (like this issue) or help,...
