### ISSUE TITLE
Submodules dialog and parenthesis in path

### ISSUE THREAD

**Issue by ggnkua** [gitextensions/gitextensions#5469]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have a [project ](https://github.com/ggnkua/Atari_ST_Sources)in which a few submodules contain open and close parentheses in the path. This results into something like the following screenshot:

![image](https://user-images.githubusercontent.com/5121492/45917104-2bcd5f80-be79-11e8-981a-27da5ccfaa8d.png)

"Name" field should contain `ASM/Various/Sascha Springer (Anima)/chorensha`but as you see is completely empty. Also, "Local path" seems to have spilled over to "Branch" field.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Clone the repository I linked above and init/update submodules or import a repository as a submodule into a repository with the name containing opening parenthesis character `(`.

**What is the expected behavior?**

"Name", "Local path", "Branch" fields in the submodules dialog should be filled out correctly

**Environment you encounter the issue:**

- GitExtensions version: 2.51.05
- GIT version: 2.18.0
- OS version: Windows 10
- .NET version: No idea. It doesn't appear on Windows 10 installed programs lists (under settings or control panel applet)

**Did this work in previous version of GitExtensions (which)?**

No

**Comment by ggnkua** [comment]
Hey, that's super cool! Is there any ETA on the next release by chance?

**Comment by gerhardol** [comment]
> Is there any ETA on the next release by chance?

Beta1 is released. A beta2 or RC1 is planned quite soon, there has been a stream of incoming PRs lately that has delayed the release...

**Comment by RussKie** [comment]
Thank you.
Closing presumed fixed.
