### ISSUE TITLE
Sublime Merge Merge/diff tool

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5470]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
new Diff/merge tool found.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Support this as a merge/diff tool.  Looks like it might be useful.  It doesn't seem to have all the goodies we have but being able to see your history and handle merge conflicts in one window and edit files could be a neat way to handle merge conflicts.

https://www.sublimemerge.com/
**Environment you encounter the issue:**

- GitExtensions version:Master
- GIT version: NA
- OS version: NA
- .NET version: NA

**Did this work in previous version of GitExtensions (which)?**
No

**Comment by pmiossec** [comment]
From what I understood, Sublime-merge is not a merge tool (what a good choice for a name!) but a Git GUI (like Gitextensions).

I don't know if there is a command line for only diff and merge... And I don't know if that's very useful to add support for other GUI tools.

For the (very?) few users that need it, they could add the config manually...

**Comment by RussKie** [comment]
I concur, it is a competing offering. Every man and his dog makes git UIs these days...

**Comment by karge-itestra** [comment]
@RussKie yes, it may be a competing product, but it comes with a good merge GUI. It can be called like this:
https://www.sublimemerge.com/docs/command_line

I think generally, it would be desirable if gitextensions would allow for 'custom' diff / merge tools in addition to the curated selection that you already made.

**Comment by gerhardol** [comment]
GE supports using all diff/mergetools that Git supports.
'smerge' is one of the tools Git knows about, what options to use etc.
Just type smerge as the name and browse for the path to the tool (not needed if the tool is included in the path).

Adding to GE is possible, the benefit would be that you see it in the GE dropdown and get hints where it is installed.

![image](https://user-images.githubusercontent.com/6248932/89276349-d7ce5d00-d643-11ea-926a-ba36c38a1a42.png)
