### ISSUE TITLE
Cant install on brand new win 10 64bit.

### ISSUE THREAD

**Issue by hackhat** [gitextensions/gitextensions#5471]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/11173732/45924251-e61e9e80-bf2d-11e8-9959-f36bba1af22d.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
will install

**Environment you encounter the issue:**

- GitExtensions version:GitExtensions-2.51.05.msi
- GIT version: no git
- OS version: win 10 64 bit brand new
- .NET version: ?

**Did this work in previous version of GitExtensions (which)?**

Didnt try, fresh install.

**Comment by hackhat** [comment]
just installed 2.49 full and worked fine.

**Comment by RussKie** [comment]
What version of W10 do you have?

**Comment by hackhat** [comment]
win 10, 64bit pro

**Comment by RussKie** [comment]
I just rolled a brand new VM with W10 and installed 2.51.05 without any problems.
I suspect the problem is either with your setup file (corrupted while download?) or something else in your OS.
Either way I don't think there is anything we can do.
