### ISSUE TITLE
Performance issue 

### ISSUE THREAD

**Issue by bgolla** [gitextensions/gitextensions#5477]
**Do you want to request a *feature* or report a *bug*?**
NO
**What is the current behavior?**
I have changed my environment from Win 10 1703 to 1803 and facing following issue.
Very slow loading on any action (eg. while changing commit and showing diffrences verry late on file click in diff tab).

**What is the expected behavior?**
Should be quick as before.
**Environment you encounter the issue:**
Winndows

- GitExtensions version:2.51.05
- GIT version: 2.19.0.windows.1
- OS version: Win 10 1803
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**
No, Its about windows version

**Comment by RussKie** [comment]
Please have a look at #5314

Please post git command timings.

**Comment by RussKie** [comment]
Closing due to age and lack of follow up
