### ISSUE TITLE
Blame options mismatch names and function

### ISSUE THREAD

**Issue by IEVin** [gitextensions/gitextensions#5485]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When user select blame option "Detect move and copy in **this** file" in fact will be used option "Detect move and copy in **all** files" and vice versa.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open blame window
2. Select options "Detect move and copy in **this** file"

Result will be shown with option "Detect move and copy in **all** file"

**What is the expected behavior?**
Result should be shown with option "Detect move and copy in **this** file"

**Environment you encounter the issue:**

- GitExtensions version: 3.0
- GIT version: 2.18
- OS version: Windows 10 x64

**Did this work in previous version of GitExtensions (which)?**
This functional was added only in 3.0 version

**Comment by gerhardol** [comment]
The option was introduced in 3.0, so this is not a regression, only in 3.0 beta1
