### ISSUE TITLE
There seems to be no way to turn on "Drop Stash Confirmation" once it's been turned off

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#5488]
It might be that I am missing something but on master @ 98e1c17 I couldn't find code or UI element which would set AppSettings.StashConfirmDropShow to true.

How does one uncheck this once checked?
![image](https://user-images.githubusercontent.com/483659/46155598-586de680-c280-11e8-8cd6-46ccab001e42.png)

**Comment by gerhardol** [comment]
> How does one uncheck this once checked?

Edit the preferences?

I suggest you change the title
