### ISSUE TITLE
Test "PathUtilTest.TryGetExactPathName()" fails

### ISSUE THREAD

**Issue by c3er** [gitextensions/gitextensions#5496]
- GitExtensions version: Current master (commit ID 96b7ed6ba385a698ce8547a0e62639a93a012910)
- OS version: Windows 10 1803 64 Bit
- .NET version: 4.6.1
- Visual Studio version: VS Community 2017 15.8.5

The test `PathUtilTest.TryGetExactPathName()` fails as only test (all other run green). It fails at the point when the path `..` is tested.

In this case, the path is determined as the parent directory of the current directory and in my environment, the current directory is `C:\WINDOWS\System32`. But this current directory has another casing as the existing `C:\Windows\System32` and the test fails because of that.

I suggest to set `Environment.CurrentDirectory` to a defined value as preparation.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by RussKie** [comment]
> I suggest to set `Environment.CurrentDirectory` to a defined value as preparation.

Set it to `TestContext.CurrentContext.TestDirectory` or `TestContext.CurrentContext.WorkDirectory`
