### ISSUE TITLE
Jira Commit Hint plugin doesn't work 3.00.00 beta1

### ISSUE THREAD

**Issue by IEVin** [gitextensions/gitextensions#5500]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Preview button in Jira commit hint plugin show error message

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Download and run GE Version 3.00.00 beta1
1. Open Tools/Settings/Plugins/Jira Commit Hint
1. Configurate it and press "Preview" button
1. Get error dialog:
![shot_181002_132349](https://user-images.githubusercontent.com/5438647/46357791-4c15cf00-c66e-11e8-85c7-a6d1f7f70dad.png)

**What is the expected behavior?**
Get title of first jira task.

**Environment you encounter the issue:**

- GitExtensions version: 3.00.00 beta portable
- GIT version:  2.18
- OS version: Windows 10 x64
- .NET version: 4.6+

**Did this work in previous version of GitExtensions (which)?**
No

I found that portable version have no System.Collections.Immutable.dll
Installable version have all necessary dependencies.
Previous portable version was 2.51.02. It have no jira commit hint plugin at all.

**Comment by IEVin** [comment]
Look like it works correct now. Thank you.

**Comment by IEVin** [comment]
But [releases page](https://github.com/gitextensions/gitextensions/releases) don't have link to portable installer, оnly normal.

**Comment by RussKie** [comment]
I've remove the portable installed from RC2 due to several issues.

**Comment by IEVin** [comment]
Will it be restored after fix these issues or will not be supported at all?

**Comment by RussKie** [comment]
It will certainly be available at the next release.
