### ISSUE TITLE
Could not access network location *:.

### ISSUE THREAD

**Issue by realdanielbyrne** [gitextensions/gitextensions#5509]
![image](https://user-images.githubusercontent.com/2242293/46419181-f6cfd100-c6f2-11e8-8068-305e3be29c8d.png)

Getting this error on installation 
    Could not access network location *:.

**Comment by vbjay** [comment]
Did you install your current gitextensions from an msi on a network drive?
Just download the installer from
https://github.com/gitextensions/gitextensions/releases that matches your
current version.  Uninstall it.  Then install the beta.

**Comment by realdanielbyrne** [comment]
No, it was a standard install from the local drive to the local drive.  

The first time I tried to install it locked up halfway through after it asked to kill explorer.exe.  The install failed at this point, but aI also had to restart Explorer from the Task Manager.  

When I tried the installation again, I began getting this error.  Then later, in an unrelated update, I tried to run visual studio installer to add some components.  The VS installer failed on installation and uninstallation of all ths vs packages as well with the same 1606 error.

I eventually surmised that something in the registry was broken and it took running this tool multiple times on a host of applications before the issue was resolved.

https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed 

So apparently there is an edge case in the installer, probably when it tries to install the explorer extensions, in which explorer.exe can be killed and the registry corrupted.

**Comment by drewnoakes** [comment]
Is there any chance your _prior_ version of GitExtensions was installed from a network drive? This is what @vbjay was asking. If so, perhaps the installer was attempting to access the prior installer's origin and failing on that.

**Comment by macmacy** [comment]
I have this problem when updating version 3.0.2.5232 to 3.1.0.5877.
This is the problem with old version being unable to uninstall. I'm attaching log of the command:

[unsetup.log](https://github.com/gitextensions/gitextensions/files/3231833/unsetup.log)

What I noticed is:

MSI (s) (04:B8) [11:51:24:183]: PROPERTY CHANGE: Adding TARGETDIR property. Its value is '*:'.

TARGETDIR cannot be set from msiexec command line. 
Do you maybe have some hint how to uninstall old package in such case? I know there is bunch of tools of "fix uninstall problems" category, but I don't have good experience with them.

**Comment by RussKie** [comment]
Try downloading the installer for  3.0.2.5232 and uninstall it

**Comment by macmacy** [comment]
Old installer did not work same way, but I solved it with tool from Microsoft mentioned by  @realdanielbyrne.  I choose to uninstall old GitExtensions and it did the job at first attempt. After that, I could install new GitExtensions. For me - it solves the problem.
