### ISSUE TITLE
error: unable to write symref for head: invalid argument

### ISSUE THREAD

**Issue by JimmyShep** [gitextensions/gitextensions#5521]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by JimmyShep** [comment]
I am getting this error when I am trying to create a bare repository

**Comment by JimmyShep** [comment]
Sorry the GIT version is 2.51.01

**Comment by drewnoakes** [comment]
That's a very old version of Git Extensions.

Please upgrade to a newer version.

https://github.com/gitextensions/gitextensions/releases

If you still see the error, please include more information in the error report by completing the template. It's impossible to tell what the problem you are experiencing is from the information you've provided.
