### ISSUE TITLE
Default GPG tab to show

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5527]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
The setting defaults to off.  Setting is kind of buried.  
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Show GPG tab by default.  Let user hide it if desired.
**Environment you encounter the issue:**

- GitExtensions version:master
- GIT version: NA
- OS version: NA
- .NET version: NA

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by oriash93** [comment]
I started to work on it, but then found a possible bug, and I need an approval.

The behavior of this setting is inconsistent.
I turned it on (via the checkbox) and the GPG tab didn't show. I even closed the repository and opened it again, or opened a different repository, but the tab wasn't there.

Weirdly enough, when I changed the default setting to `true`, here:

https://github.com/gitextensions/gitextensions/blob/765888954ef07ae64fbdbfa4596edc37a6dd5763/GitCommands/Settings/AppSettings.cs#L367

it was on by default and the tab was there. However, when I turned it off (via the checkbox) the tab was still showing.

**Comment by vbjay** [comment]
You habe to restart GE.

**Comment by oriash93** [comment]
In that case, it should be mentioned that a restart is required (as in other settings in GE).

**Comment by RussKie** [comment]
> In that case, it should be mentioned that a restart is required (as in other settings in GE).

This is good to fix, thanks for finding it
