### ISSUE TITLE
Fetch bug in 3.0 beta 1

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#5539]
**Do you want to request a *feature* or report a *bug*?**  Bug

**What is the current behavior?**  Repo is in detached head state. From the Pull button, I select Fetch. I get an error "You are not working on a branch. You cannot "pull" when git head detached." 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**  Branches should be fetched from origin. 

**Environment you encounter the issue:**  

- GitExtensions version: 3.0.0-beta1
- GIT version: 2.18.0.windows.1
- OS version: Win10 Enterprise version 1709
- .NET version: 4.7.2

**Did this work in previous version of GitExtensions (which)?**  Not sure. 'git fetch' works fine from the command line.

**Comment by pmiossec** [comment]
That's due to the (very annoying!) bug #5420. It is doing a "pull" instead of a "fetch".

**Comment by asherber** [comment]
Thanks -- I'll close this one, since the other describes the issue more clearly.
