### ISSUE TITLE
Linux - Mono version - Failed to load plugin /home/xxxxxxxxxx/bin/GitExtensions/Plugins/Bitbucket.dll

### ISSUE THREAD

**Issue by JerryLumpkins** [gitextensions/gitextensions#5541]
After running today's updates to Mono on Ubuntu 18.04, GitExtensions no longer runs.

The following error message is presented:
'Failed to load plugin /home/xxxxxxxxxx/bin/GitExtensions/Plugins/Bitbucket.dll'

![image](https://user-images.githubusercontent.com/5314886/46627909-f4fa7900-cb09-11e8-96a3-0cce5e2e3779.png)

**Comment by gerhardol** [comment]
The BitBucket plugin should not be fatal. You may be able the plugins.

**Comment by JerryLumpkins** [comment]
I'm sorry Gerhardol, I don't understand what you are suggesting.

The application hangs with a black screen, and I have to kill it with a -9 to exit the process.
Are you saying that I should be able to remove the plugin?

**Comment by JerryLumpkins** [comment]
I moved the file Gitextensions/Plugins/Bitbucket.dll out of the Plugins folder, and the program is now working.

Thanks!

**Comment by Wirone** [comment]
Happened to me after upgrading Ubuntu from 18.04 to 19.04. I did as @JerryLumpkins and moved Bitbucket plugin away from plugins directory.

On the other hand "recently used" repos on the dashboard works for me for the first time - I always had empty place there :sweat_smile:

**Comment by serefarikan** [comment]
Facing this exact same issue. The strange thing is, I have the exact same version of mono and gitextensions in two machines. One of them is Ubuntu 16.04 and the other is 18.04. I had this issue first in the 16.04 machine after updating mono to latest version (6.8.0.105) and I downloaded and extracted GitExtensions 2.51.05, ran it and it works. 
I have the exact same setup in the 18.04 machine, but I'm getting the Bitbucket.dll exception and nothing helps other than moving the dll out of Plugins folder. 
So the issue somehow appears to be related to an interaction between mono and underlying OS, but I have no idea what that is. This is one of the cases where I'm OK with a workaround even if I don't understand the exact nature of the problem.

**Comment by RussKie** [comment]
Updated the wiki noting to remove the plugin: https://github.com/gitextensions/gitextensions/wiki/How-To%3A-run-Git-Extensions-on-Linux
