### ISSUE TITLE
Bug: Diff Pane blank when Ignore Whitespace hides whitespace-only diffs

### ISSUE THREAD

**Issue by brianjlacy** [gitextensions/gitextensions#5547]
Problem:
When "Ignore...whitespace" options are enabled, and a file ONLY has whitespace changes that would be ignored by the rule, then the diff pane appears completely blank. Although hovering on the diff pane displays the buttons to disable the Ignore feature, it is not clear this is what is happening, and it may appear broken to the user.

Sidenote:
Oddly, neither of the Ignore Whitespace options seemed not to have ANY effect when I added TWO newlines to the end of a file that previously ended without a newline..

Suggested Resolution:
Add a message in the Diff Preview pane whenever the "Ignore...whitespace" options cause the pane to appear blank, indicating that whitespace-only changes are currently being ignored.

Environment:
Windows 10 v1709 (build 16299.665)
GitExtensions 2.51.05
GIT v2.18.0.windows.1

---

![gitextensions-bug-screenshot-20181010](https://user-images.githubusercontent.com/19938700/46756348-74ac5300-cc84-11e8-846d-ee4ca2da9e92.jpg)

**Comment by codenjs** [comment]
I have a similar problem on a different screen. The screenshot above shows the commit dialog. My issue is when I'm viewing commit history, using the Diff tab in the lower portion of the split view below the revision graph.

In my case, hovering on the diff pane does not display the buttons to disable the Ignore feature. I have to click on a different file which has non-whitespace changes, disable the Ignore feature, then go back to the first file.

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4220.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Yes, it is annoying. Pull requests are welcome.

**Comment by gerhardol** [comment]
> In my case, hovering on the diff pane does not display the buttons to disable the Ignore feature. I have to click on a different file which has non-whitespace changes, disable the Ignore feature, then go back to the first file.

Right click and use context menu to change diff

However, the toolbar should be visible for all files, including new to be able to set the encoding
