### ISSUE TITLE
Browse: Commands menu for artificial commits

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5557]
**Do you want to request a *feature* or report a *bug*?**
bug, regression

**What is the current behavior?**
The menu shows a number of commands not available, like rebase for commit index.
Some commands like reflog could be OK for artificial too (not visible for worktree).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
select artificial commit
Select Commands menu
Try the commands

**What is the expected behavior?**
Only show relevant commands in the menu

**Environment you encounter the issue:**

- GitExtensions version: master

**Did this work in previous version of GitExtensions (which)?**
This is incorrect in 2.51
This was fixed in earlier post 2.51 development. As usual, I suspect the otherwise great #5087 to be responsible

**Comment by RussKie** [comment]
Would you be able to look into this?

**Comment by gerhardol** [comment]
Planning to
