### ISSUE TITLE
Copy author should include email

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5558]
**Do you want to request a *feature* or report a *bug*?**

Feature?

**What is the current behavior?**

Copying author only includes name.

![image](https://user-images.githubusercontent.com/350947/46901115-6721e380-cea5-11e8-806d-094f7a027b05.png)

**What is the expected behavior?**

Copied string should have standard git format of `"Name <email>"`.

This should also apply to _committer_ when present.

My use case was needing to create a commit locally after massaging someone elses commits, and wanting to paste into the command line for `--author="|"`.

**Environment you encounter the issue:**

- GitExtensions version: 3.0 beta 1
- GIT version: N/A
- OS version: N/A
- .NET version: N/A

**Did this work in previous version of GitExtensions (which)?**

Don't think so.

**Comment by drewnoakes** [comment]
Note that coping from here doesn't work either:

![image](https://user-images.githubusercontent.com/350947/46901142-db5c8700-cea5-11e8-96c9-9f541af70c3a.png)

You end up with:

    Drew Noakes <git@drewnoakes.com>#mailto:git@drewnoakes.com

**Comment by rbares** [comment]
Picking this up

**Comment by gerhardol** [comment]
The copy in Commit tab contains the links also for branches tags etc. The plain text copy should not contain the links, should copy the text as displayed.
