### ISSUE TITLE
Crash on launch when git not installed

### ISSUE THREAD

**Issue by CDAGaming** [gitextensions/gitextensions#5562]
**Do you want to request a *feature* or report a *bug*?**
This is a bug.
**What is the current behavior?**
![capture](https://user-images.githubusercontent.com/16328918/46919001-6a4cca80-cf9e-11e8-8871-b864d0d0b5e2.PNG)
This Issue occurs on Launch, under a Fresh/New Start (Moved to new PC that didn't have GitExtensions on it before)
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Launch under First Start (Not Tested if it occurs on Existing Systems)
**What is the expected behavior?**
To Launch Properly
**Environment you encounter the issue:**

- GitExtensions version: 3.0.0.3621 - 3.0.03702
- GIT version: N/A - New System
- OS version: Windows 10 Update 1803
- .NET version: N/A - New System

**Comment by CDAGaming** [comment]
Closing. Issue was Patched by Installing Git. However, perhaps there should be a warning that you need Git to run this, instead of a crash (idk, just my two cents)

**Comment by drewnoakes** [comment]
Reopening as GE shouldn't crash when git's not installed.
