### ISSUE TITLE
Ctrl+T for Create tag form picks checked out revision rather than active one

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#5564]
**Do you want to request a *feature* or report a *bug*?**
Hard to tell.

**What is the current behavior?**
Ctrl+T opens `Create tag` form with revision set to currently checked revision.

**What is the expected behavior?**
Ctrl+B for `Create branch` form picks revision based on currently selected revision. I find this a lot more sensible. Suggestion is to do the same for `Create tag` form i.e. pick revision based on what's selected in revision grid.

**Comment by RussKie** [comment]
It sounds like a regression, in 2.5x the tag is being created at the selected commit, not at the checked out one

**Comment by mdonatas** [comment]
I'll fix it, this has bitten me in the rear far too many times in recent weeks.
