### ISSUE TITLE
Diff viewer not redrawing correctly

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#5568]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
In diff view, when switching from a file with a longer diff to one with a shorter diff, the rest of the diff of the previous file remains visible.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
In GE repo, select commit 1792cf9e116a03bd1a94f7241c82d0d4d73883db.
Diff for `FormCommit.cs`:
![obrazek](https://user-images.githubusercontent.com/11479798/47015104-665eab00-d14c-11e8-9eb8-775dc215b2f9.png)

After selecting the diff for `RevisionDiffControl.cs`:
![obrazek](https://user-images.githubusercontent.com/11479798/47015182-97d77680-d14c-11e8-9356-3d82741e44b9.png)

No diff lines except for the first one should be visible.

**What is the expected behavior?**
Diff view should be redrawn entirely.

**Environment you encounter the issue:**

- GitExtensions version: master at 1792cf9e116a03bd1a94f7241c82d0d4d73883db
- GIT version: 2.19.1.windows.1
- OS version: Windows 10
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**
Yes, before #5563 was merged.

**Comment by gerhardol** [comment]
Cannot reproduce with #5571

**Comment by RussKie** [comment]
Could you please confirm the fix
https://ci.appveyor.com/api/buildjobs/ktgpdywl74vpdb1w/artifacts/GitExtensions-Portable-3.00.00.3724.zip

Thanks

**Comment by RussKie** [comment]
After merging #5571 I can no longer reproduce the bug, could you please try the current master
https://ci.appveyor.com/api/buildjobs/ctga939ix556n24l/artifacts/GitExtensions-Portable-3.00.00.3723.zip

**Comment by RussKie** [comment]
Scratch the previous two, here's a test build with a fix
https://ci.appveyor.com/api/buildjobs/ppq8bl6ntix7m6j3/artifacts/GitExtensions-Portable-3.00.00.3728.zip
Please confirm the fix

**Comment by crypto-rsa** [comment]
The above build works correctly.
