### ISSUE TITLE
Add Submodules to the left pane

### ISSUE THREAD

**Issue by amaiorano** [gitextensions/gitextensions#5569]
Hi,

I started working on a feature to add a Submodules tree to the left pane. The idea is that this would effectively replace the Submodules menu, and perhaps even the Submodules form, combining all operations in one place.

At the moment, I've got it displaying the current module's submodules, along with its status, and double-clicking on a submodule switches the FormBrowse to browse it:

![image](https://user-images.githubusercontent.com/6893883/47018101-02bf8800-d122-11e8-8b24-edbd08cd9920.png)

There's still a lot to do, such as:
* Show the current modules parent module, if any, and make double-click switch to it.
* Context menu on "Submodules" parent node to "Update all submodules".
* Context menu on child node to "Update this submodule".
* Maybe a tooltip when hovering over a submodule that shows the info we currently show in Repository -> Submodules form.
* Maybe support multi-select so that specific submodules can be selected and updated.

My branch for this is here: https://github.com/amaiorano/gitextensions/tree/amaiorano/left-pane-submodules

Before I progress further, I just want to know if there's any real interest in this feature? Should I keep moving forward? Do you have any suggestions or ideas for improvements?

Thanks.

**Comment by gerhardol** [comment]
I prefer the Submodules menu. With the sidebar, the submodules may not be visible or expanded as I prefer.
But it will be nice for some users I guess.

If it is reasonable to keep both the sidepanel and the menu and no extra commands are needed (the submodule commands take some time), the submodule item is on the top I would even use the functionality.
The sidepanel could be separate panel too (probably not) or some faster way to expand the area you would like to see (submodules, tags or branches).

**Comment by RussKie** [comment]
Thank you for the initiative.
Could you please explain the reasoning/use-cases behind it?

**Comment by amaiorano** [comment]
> Thank you for the initiative.
> Could you please explain the reasoning/use-cases behind it?

Yes, of course. With submodules in the side panel, we get the following benefits:
* Being able to see the current state of all submodules immediately without having to click on the pull down menu.
* Being able to switch between submodules more easily, which is something I do a lot at work, and I find having to click on the pull down menu to select submodules each time is not as pleasant a user experience.
* It opens up potential workflows, such as multi-selecting submodules and performing actions on the selection.

In effect, the reasoning is similar to why we have the sidebar to display branches: at a glance info, and easy navigation.

We don't have to remove the menu bar, of course.

**Comment by amaiorano** [comment]
Hello again,

So I've continued working on this feature, and it's coming along quite well. Here's a screenshot of what it looks like right now:

![image](https://user-images.githubusercontent.com/6893883/47220419-bcfffb00-d37f-11e8-9398-05145a740942.png)

The current module is Git.hub to which I added a submodule "FSharpRipOff" (for testing). So you can see in the Submodules tree that I separate the nodes into three groups: Super, Child, and Sibling modules. Not sure if those names are great, but we can certainly bike shed about that :)

Right-clicking on the top "Submodules" node gives you the ability to update all submodules recursively:
![image](https://user-images.githubusercontent.com/6893883/47220515-018b9680-d380-11e8-8671-d7c9b5d7f55d.png)

Right-clicking on any other module node allows you to update only that module:
![image](https://user-images.githubusercontent.com/6893883/47220538-12d4a300-d380-11e8-849b-8ed88624574d.png)

Double-clicking on any submodule node will open that module, similar to how double-clicking a branch opens that branch.

You can also see that the icons for the modules reflect their current state. I'm reusing the exact same icons as the ones in the submodule pulldown menu. These icons get updated asynchronously after the left pane is enabled; I'm not sure if I did that properly since my C# async-fu isn't that strong, so I'd definitely appreciate feedback on that part, should we decide to move forward with this.

There are still a couple more features I'd like to implement:
* Add "Synchronize all submodules" to top Submodules node context menu
* Add "View submodules info" to top Submodules node context menu which will open the Submodules dialog currently available via Repository -> Submodules... menu
* Add "Add submodule" context menu to any submodule node (maybe)

If you'd like to try it out, add my fork as a remote and check out my feature branch:
remote: https://github.com/amaiorano/gitextensions.git
branch: amaiorano/left-pane-submodules
(Should I open a WIP PR? Would that be easier to get feedback?)

Cheers!

**Comment by gerhardol** [comment]
WIP PRs is OK, larger possibility to get approval

Quick comments:
* Put on top of the panel, if you use this, you want it at the top
* Present the submodule tree with the current module marked somehow, no need for Supermodule, Submodule naming (not Parent/Child).

**Comment by amaiorano** [comment]
> WIP PRs is OK, larger possibility to get approval

Thanks, will do asap.

> Quick comments:
> 
> * Put on top of the panel, if you use this, you want it at the top

I'm not sure this is true. Having the current branch view is also very useful. Maybe this could be made an setting.

> * Present the submodule tree with the current module marked somehow, no need for Supermodule, Submodule naming (not Parent/Child).

Again, not sure about that. Originally, this is what I had, and found that with many modules, it was confusing. I know that the Submodules menu does this, but since we have a tree, why not make use of it to better organize the nodes? I'd like to hear more feedback about this from others on the project to see what people think.

Thanks for the quick feedback.

**Comment by gerhardol** [comment]
I would prefer a full tree, like the following:

super1
 * repo1
  * sub1
  * sub2
 * repo2
  * sub3
   *sub4

**Comment by amaiorano** [comment]
> I would prefer a full tree, like the following:
> 
> super1
> 
> * repo1
>   
>   * sub1
>   * sub2
> * repo2
>   
>   * sub3
>     
>     * sub4
> 
> Expand all levels by default?

Yeah, so I actually tried that - I have a local branch with the changes to make this work. But, the thing is, when you do this, double-click behaviour no longer makes sense. Basically, I have it so that double-clicking a submodule opens it, which is like double-click to check out a branch. And this is really nice for navigation. But if a submodule node has children, then double-click expands/collapses the node by default. When I saw this, I disabled double-click to open, and just used the Open context menu action, but I felt like I lost useful functionality, _and_ it was no longer congruent with the behaviour of double-clicking on branches.

Thoughts?

**Comment by amaiorano** [comment]
Okay, I've done so more work on this, and have integrated some of your advice @gerhardol.

I got rid of those folders for "super", "child", and "sibling" modules. To go to the top or super project, I added these as context menu items on the root "Submodules" node:
![image](https://user-images.githubusercontent.com/6893883/47360731-35c3c780-d69e-11e8-827b-7335cf7ced2d.png)

As suggested, I now display the current submodule bolded, if we've opened one. As for displaying them, I've got two ways to display them, and am trying to figure out which one is best. The first is the simplest, I just show the nodes in the same way they are shown in the menu:
![image](https://user-images.githubusercontent.com/6893883/47360875-8affd900-d69e-11e8-9054-b07bc4509888.png)

The other way is as a folder tree:
![image](https://user-images.githubusercontent.com/6893883/47361672-850af780-d6a0-11e8-9804-2eb014651887.png)

You'll notice that for "Git.hub", because it's a submodule with a submodule, I show both a submodule node, "Git.hub [no branch]", and a folder, "Git.hub", with the "FSharpRipOff [no branch]" submodule child node. This is my current solution to allowing you to double-click on any submodule node to open it, but it means having both a folder and submodule node for these submodules. Is this okay? I'm really not sure. Ideally, as you suggested @gerhardol, we'd just have "FSharpRipOff [no branch]" as a child of "Git.hub [no branch]", but then we can't double-click to open the latter.

I'm open to suggestions. Perhaps @RussKie or @jbialobr have some thoughts on this?

**Comment by RussKie** [comment]
I very much appreciate your contribution but  between RL and the preparation of the v3 I have no sufficient time to review this piece of work. I will get back to it once a RC is out.

**Comment by RussKie** [comment]
I let @gerhardol drive this.

**Comment by amaiorano** [comment]
Hello again, I've been using my modified version of GE with submodules in the left pane, and although it works well, I'm really not happy with the way I render 2 nodes for inner submodules (submodules with child submodules) - one for the folder, and one for the submodule. I'm talking about this (image pasted from above):

![image](https://user-images.githubusercontent.com/6893883/50044252-defbbe00-004e-11e9-8f9f-b0b5d76c62ae.png)

I rewrote my tree building code to only show one node instead, so we now have something like this:

![image](https://user-images.githubusercontent.com/6893883/50044307-b88a5280-004f-11e9-8f9d-d2f94f501856.png)

The difference is there's no more folder node for Git.hub, just the submodule node as an inner node, with the FSharpRipOff submodule as its child.

Personally, I like this a lot better. It's especially nice when you have a lot more submodules, like this:

![image](https://user-images.githubusercontent.com/6893883/50044343-1c148000-0050-11e9-84a0-f06fabe323aa.png)

The only problem with this is double-clicking. Double-clicking a submodule node opens it, which is nice and consistent with how branches work. However, double-clicking an inner tree node expands/collapses it. So I have two possibilities here:

1. Disable double-click to open submodules, and rely on the user right-clicking the node and selecting Open (this is already implemented)

2. Disable double-click to open *only* on inner submodule nodes, so that they expand/collapse and would require right-click and select "Open" to open them, otherwise leaf submodule nodes can be double-clicked as usual.

Option 1 sucks because it's inconsistent with double-click to checkout branches. Option 2 sucks because double-clicking inner nodes is inconsistent with double-clicking leaf nodes.

Maybe I should just give up on this type of view and go back to having 2 nodes per inner (folder and submodule node). Do you have any thoughts? This is open to discussion with everyone, not just @gerhardol. I'll call out other core team members (that I know) who might have opinions: @RussKie @drewnoakes @spdr870 @jbialobr.

**Comment by vbjay** [comment]
Alter double click to handle different type of nodes.  If node is a branch
then check out.  If node is a submodule then pass to base treeview.

**Comment by amaiorano** [comment]
> Alter double click to handle different type of nodes. If node is a branch then check out. If node is a submodule then pass to base treeview.

I don't think you understood what I wrote. I already do handle double-click on a submodule node to open it. My question isn't about how to do that. It's about how to handle double-click for "inner" submodule nodes.

**Comment by gerhardol** [comment]
I also prefer the one folder approach visually (that was what I preferred initially), but for consistency the separate folder icon is better:
Less to explain is better, the functionality is easier to discover.

**Comment by drewnoakes** [comment]
I prefer the reduced number of nodes, as they more closely match my mental model of the project structure. Having the duplicated node is confusing. But I'm biased because I never double-click to expand/collapse tree nodes.

I'd consider making double click in the entire tree (not just submodules) only perform expand collapse and be a no-op on leaves. Actions could be driven from the context menu. I expect some would resist this idea, but it would be consistent and discoverable.

We have a similar discussion right now for SDK style projects in VS2019 regarding double-clicking a project node in Solution Explorer to edit the project file. It's very handy, compared with right-click edit, but will surprise some users. It's unclear what the best approach is for now.

**Comment by vbjay** [comment]
I agree.  Double click on a node in a treeview has an expected action.  Context menus are for Non default actions.

**Comment by gerhardol** [comment]
The standard action to double click a submodule (if you have enabled the setting) so double clicking will be inconsistent in the left panel vs FileViewer. If we choose this path, the icon should be separated at least.

**Comment by vbjay** [comment]
There is a difference between the submodule view in the file tree and the
left panel.  Left panel is an overview of the structure of the repo and
with your feature, sub repos also and so on.  Which means that the left
panel wold open and collapse with double clicks.  The file tree deals with
the details of the current repo.  It is not a hierarchy of repos.  So I
would expect double clicks in file tree of a submodule to open the
submodule like it does now.  While your submodule nodes in the left panel
are hierarchy nodes that possibly contain sub nodes.  Think on the
difference between double clicking a file in solution explorer and a folder
in solution explorer.

**Comment by gerhardol** [comment]
> Think on the difference between double clicking a file in solution explorer and a folder in solution explorer.

In the File tree all submodules are folders as only the direct submodules are included.
So no matter what, there will be inconsistencies with a combined folder and leaf.

**Comment by vbjay** [comment]
No. Submodules in the file tee are end nodes. They do not expand.

**Comment by vbjay** [comment]
Double clicking these open up the submodule in a new instance of GE.  

![image](https://user-images.githubusercontent.com/3629489/50047674-569a0f00-0088-11e9-8137-1076c9e0921c.png)

**Comment by amaiorano** [comment]
> Just like nested files in solution explorer why have one node be the Doc submodule and then a folder node that has its submodules. Add the Morelinq ( submodule\submodule node) to the same node instead of duplicating nodes.
> 
> Double click always opens and collapses node if it has sub nodes. Otherwise no action (in left panel) Context menu to perform actions

I'm having trouble parsing what you wrote, but I *think* what you're saying is what I already proposed above as option #2. Indeed, it looks like you've checked out my code, so you can already try this by setting "AddFolderNodeForInnerSubmodules = false;" in RepoObjectsTree.Nodes.Submodules.cs. You end up with one node per module, and double-clicking inner-nodes only expands/collapses them, while double-clicking lead nodes opens them. Personally, I find this weird and inconsistent, though.

**Comment by amaiorano** [comment]
Maybe, in the end, I should abandon the whole idea of showing the entire submodule hierarchy, and just show the current module's submodules. This would avoid the problem altogether, and perhaps would match more the spirit of that left panel, since it only shows the current module's branches, remotes, and tags. I liked showing the whole thing because it can be useful, but maybe it's the wrong idea altogether.

**Comment by vbjay** [comment]
That's exactly what I'm saying. What we are saying is double clicking on
any submodule does not open it in the left panel. The double clicking just
opens and collapses the nodes if there are sub nodes.

File tree only shows current repo submodules.  There isn't a hiarchy.
Double clicking there does open the submodule in GE just like double
clicking a file in solution explorer.

**Comment by vbjay** [comment]
The hierarchy is fine. It is helpful to see the structure. Also there is nothing wrong with a context menu providing actions.

**Comment by amaiorano** [comment]
> That's exactly what I'm saying. What we are saying is double clicking on any submodule does not open it in the left panel. The double clicking just opens and collapses the nodes if there are sub nodes. 

So basically option #1?

> File tree only shows current repo submodules. There isn't a hiarchy. Double clicking there does open the submodule in GE just like double clicking a file in solution explorer.

What File tree? You and @gerhardol have mentioned it a few times, but I'm not sure what you're talking about.

**Comment by vbjay** [comment]
File tree tab. The hierarchy is great and desired in left panel. I like it.
Just don't provide open functionality by double clicking.


Also don't create duplicate nodes like I demonstrated. Your option in the
code file covers this.

**Comment by gerhardol** [comment]
Double-clicking on a branch will check that out. So not open when double-clicking will be inconsistent to Branches and File tree. So I still believe that an icon for the folder and one for the leaf is the most consistent and easiest to understand.

Let us cool down the discussion and decide in some days.

**Comment by amaiorano** [comment]
> File tree tab. 

Ah, okay, thanks.

The hierarchy is great and desired in left panel. I like it. Just don't provide open functionality by double clicking. Also don't create duplicate nodes like I demonstrated. Your option in the code file covers this.

Almost. Setting "AddFolderNodeForInnerSubmodules = false" makes it so that we don't duplicate nodes, but double-clicking leaf nodes still opens that submodule.

Anyway, I understand. So far, @vbjay, @drewnoakes, and maybe @RussKie prefer single node per submodule, even if it means sacrificing double-click to open. While @gerhardol prefers two nodes per submodule (one for folder, one for node) so that we can keep the consistent double-click to open behaviour.

I'm on the fence myself. I love double-click to open. Having used it for the past few weeks at work, I find it quite useful and ergonomic. So I don't think we should give that up.

**Comment by amaiorano** [comment]
> Let us cool down the discussion and decide in some days.

Sure, though I'd love to hear from anyone else who hasn't shared their opinion yet :)

**Comment by drewnoakes** [comment]
@amaiorano in your early screenshots you showed supermodules as separate trees. I am wondering whether it's possible to show the supermodule as an ancestor node, as that's really what it is. Then the "Submodules" tree node would show (for example):

```
- root repo supermodule (grandparent)
  - supermodule
    - checked out module (in bold)
      - submodule 1
      - submodule 2
    - sibling
```

**Comment by gerhardol** [comment]
The repos I work with the most have the structure as seen below. There are more shared and apps than shown, I am involved in about 15 devices. Those that work with the application only clone the app repos, most that work with devices have only a few as well.

For the devices I work primarily with (about ) I use Git Worktree to share common clones (I really would like to share subrepos among separate worktrees but that is not something to discuss here.) The structure is very useful here, the dropdown is hard to navigate now. I jump around a lot among the configurations and submodules and doubleclicking submodules would be nice.

```
- device1
 - device shared1
 - device build
   - build shared app/device
 - application1
  - app common
  - app build
   - build shared app/device
 - application2
  - app common
  - app build
   - build shared app/device
```

(Will make some proposals to vote about tonight.)

**Comment by drewnoakes** [comment]
I look forward to your proposals!

For completeness, when I said a flat list I intended the full paths to maintain the structure (at the expense of more horizontal space).

```
+ Submodules
|-- Externals/conemu-inside
|-- Externals/Git.hub
|-- Externals/Git.hub/FSharpRifOff
|-- Externals/ICSharpCode.TextEditor
|-- Externals/NBug
|-- GitExtensionsDog
```

In your case that might be unwieldly.

**Comment by amaiorano** [comment]
This morning, I was thinking about the double-click issue, and how @drewnoakes mentioned solving a similar problem in VS2019, and I thought about how in VS's Solution Explorer, double-clicking C# .cs files that have "children" files doesn't actually expand/collapse them, unless you single click on the little arrow thing to the left. So I wondered about doing the same thing: basically, in the Submodule tree, if you double-click a submodule node, whether it's an inner node or leaf node, it would always open that submodule (make it the current module); and if you want to collapse/expand, you can single click on the little arrow (or use your keyboard with left/right arrow). I think this would work well. I started working on it this morning, and so far I've got it correctly detecting and disabling expand/collapse on node double-click. I'll continue working on it, and will provide an updated binary for you all to try (or you'd be able to just build from my branch if you prefer).

Stay tuned!

**Comment by drewnoakes** [comment]
> I'm a little bit confused by what you're suggesting because isn't that exactly what I'm doing?

Yes, I suppose it is. In one of your first screenshots you had supermodules in a sibling tree. Your newer screenshots look like what I expected.

> The only difference is that the root repo supermodule (grandparent) node is represented by the "Submodules" node

Agree. Seeing "Submodule" as the parent of a supermodule is a bit weird. Maybe the root node could just be "Modules". I don't know if that's better or worse :)

> you can simply set this one bool in RepoObjectsTree.Nodes.Submodules.cs to false

Fantastic. That might be a nice option on the root node's context menu. This would be a good option on repositories that only have one or two submodules, especially if they're buried a few levels deep. That could be a lot of clicking to get to what you're looking for, versus a flat list.

> doesn't take much advantage of the fact that this is a tree view and not a list view

Another idea would be to have a flat list for only direct submodules, and show their submodules as another flat list. So in the your most recent screenshot, all the ICSharpCode.TextEditor submodules would be children of their parent. Or in other words, there's one tree node per `.gitmodules` file. Every node would still be a submodule with that approach.

I think that approach would work nicely for the example @gerhardol shared too.

**Comment by gerhardol** [comment]
> Agree. Seeing "Submodule" as the parent of a supermodule is a bit weird. Maybe the root node could just be "Modules". I don't know if that's better or worse :)

Submodules is the name of the concept as well so keep that.
Git uses Superproject for "Supermodules", also used in our code (I should change what I use too).

I definitely want to see the tree structure, the flat list is too long, there are a number of build-util submodules for instance.

As @amaiorano is to post a new concept, I will only make a quick summary today of the options I see:

1a. Separate structure folders and submodule nodes.
+ Easy to discover what the icon is doing.
+ Consistent doubleclick behavior with branches as well as FileTree/Diff
- Can have extra folders, required when a submodule has submodules

1b. Expand/collapse only when clicking arrow part prepending the submodule icon
+ Should be fairly simple to understand, relative simple to understand
- Slightly different doubleclick behavior to branches

2. Only doubleclick to expand/collapse, open only from context menu (leafs could be opened, but that would be inconsistent)
+  Compact?
- Inconsistent doubleclicking from branches and FileTree/Diff
- Loss of functionality

3. Always flat list
+ Similar to current menu
+ Clear what the doubleclick action is
- Loss of functionality, missing structure (compare alphabetic branch list with left panel, much easier to find in the left panel)

Regardless of what is done, I want to collapse paths that are not needed.
So the structure for the example for proposal 1. would be:

```
+ Submodules
|-- Externals/conemu-inside
|-- Externals/Git.hub
 + Externals/Git.hub
 |-- FSharpRifOff
|-- Externals/ICSharpCode.TextEditor
|-- gitextensions
 + gitextensions
 |-- Externals/conemu-inside
 |-- Externals/Git.hub
 + Externals/Git.hub
  |-- FSharpRifOff
 |-- Externals/ICSharpCode.TextEditor
 |-- Externals/NBug
 |-- GitExtensionsDog
|-- Externals/NBug
|-- GitExtensionsDog
```

**Comment by amaiorano** [comment]
@gerhardol Thank you for the nice summary of options! I haven't fully understood option 1a, but I'll take a closer look soon.

Everyone else:  I've implemented the new solution (which @GardenTools  labeled "1b").  You can take a look at the commit on my fork here: https://github.com/amaiorano/gitextensions/commit/53f38400c35a7f345135ed15b1e4d0c51f3df7ac

And you can try it by downloading this zipped version: 
[amaiorano_GitExtensions_better_double_click_submodules.zip](https://github.com/gitextensions/gitextensions/files/2703002/amaiorano_GitExtensions_better_double_click_submodules.zip)

I must say, I think this is the best solution so far. I don't find it at all surprising that double-clicking inner submodule nodes open the submodule because the node looks just like the leaf nodes (icon, etc.).

Anyway, please try it out on a repo with recursive submodules. You can still expand/collapse the nodes by using the little arrow; otherwise, double-click the inner nodes to open them, just like the leaves.

Let me know what you think!

**Comment by gerhardol** [comment]
> I've implemented the new solution "1b"

OK for me, still I prefer 1a, more consistent with branches. (1b looks better and is more compact.)

And I still believe that paths within a repo should be collapsed, for instance "Externals/Git.hub". When looking at the repo it is easy to see the sublevel of changes, like all direct submodule repos is one step to the right.

1a is the examples first and last in https://github.com/gitextensions/gitextensions/issues/5569#issuecomment-447574845

And I still want submodules above branches or at least that branches do not expand when refreshing (the expanded state is preserved).

I would like to hear what at least @vbjay has to say too.

**Comment by gerhardol** [comment]
![image](https://user-images.githubusercontent.com/6248932/50351360-3237aa00-0542-11e9-87ed-aedca64741e6.png)
The second row should be 'util [feature/gradle-5-test]'

**Comment by amaiorano** [comment]
> OK for me, still I prefer 1a, more consistent with branches. (1b looks better and is more compact.)

Really? Man, I thought I had a clear winner with 1b :)

> And I still believe that paths within a repo should be collapsed, for instance "Externals/Git.hub". When looking at the repo it is easy to see the sublevel of changes, like all direct submodule repos is one step to the right.

So if I understand, rather than expand everything, only expand all up to the current module, but not its child modules? You also mentioned not expanding branches. I think maybe we need to add a separate feature to remember the expanded/collapsed state, which is not completely trivial.

> 1a is the examples first and last in [#5569 (comment)](https://github.com/gitextensions/gitextensions/issues/5569#issuecomment-447574845)

Ah right, so basically what I had before with the 2 nodes per inner module (folder node and submodule node).

> And I still want submodules above branches or at least that branches do not expand when refreshing (the expanded state is preserved).

Yeah, so I don't know how many people will agree with that. I think most people will be more interested in branches than submodules for the current repo. Maybe we can just make it an option.

**Comment by amaiorano** [comment]
> ![image](https://user-images.githubusercontent.com/6248932/50351360-3237aa00-0542-11e9-87ed-aedca64741e6.png)
> The second row should be 'util [feature/gradle-5-test]'

Ah, you found a bug. I'll fix it.

**Comment by gerhardol** [comment]
> > And I still believe that paths within a repo should be collapsed, for instance "Externals/Git.hub". When looking at the repo it is easy to see the sublevel of changes, like all direct submodule repos is one step to the right.
> 
> So if I understand, rather than expand everything, only expand all up to the current module, but not its child modules? 

See the example in my longer post: No structure within a submodule, only for submodules.
(With 1b the '+' lines would disappear though).

> You also mentioned not expanding branches. I think maybe we need to add a separate feature to remember the expanded/collapsed state, which is not completely trivial.

> > And I still want submodules above branches or at least that branches do not expand when refreshing (the expanded state is preserved).
> 
> Yeah, so I don't know how many people will agree with that. I think most people will be more interested in branches than submodules for the current repo. Maybe we can just make it an option.

Storing the expansion state is maybe the solution. This is a discussion for a reasonable good solution, not a requirement for everything that must be implemented. But it is something I would like to see in a usable solution.

**Comment by amaiorano** [comment]
> > ![image](https://user-images.githubusercontent.com/6248932/50351360-3237aa00-0542-11e9-87ed-aedca64741e6.png)
> > The second row should be 'util [feature/gradle-5-test]'
> 
> Ah, you found a bug. I'll fix it.
> EDIT: Tested at work and also got the bug. Basically I'm parsing until the last '/' which messes up if the branch name has a slash. Will fix :)

Fixed. Uploaded new version and edited my post above with the new link.

**Comment by amaiorano** [comment]
Closed by https://github.com/gitextensions/gitextensions/pull/5617
