### ISSUE TITLE
Commit graph continuity issue in 3.0

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#5593]
**Do you want to request a *feature* or report a *bug*?**
Bug

A view of GitExtensions 2.5 and 3.0 side by side
![image](https://user-images.githubusercontent.com/483659/47215418-0b29f400-d3aa-11e8-93a5-f0398c60ed91.png)

Notice the discontinuity in the graph line on the right.
Unfortunately this is a private repo and I can't share it. This is the first time I am seeing this so it's hard to repro. I am creating this issue to inform you of the investigation progress trying to find the root cause.

Turning on Reflog References in 3.0 fixes this. I'll keep you posted.

**Comment by spdr870** [comment]
For your info. The difference between turning on Reflog References (or Date Order) is that git.exe returns the log in an ordered way. I did some changes for the performance that change the behaviour when both settings are turned off. I would like to simulate this issue, so if you can simulate this on a reliable way, let me know.

Also, try the latest commit. I might have fixed this in:
Author:			Henk Westhuis <henk.westhuis@gmail.com>
Date:			4 hours ago (19-10-2018 09:46:09)
Committer:		GitHub <noreply@github.com>
Commit hash:	0540cddc5d71b217b68469cb2d1edf868609a29a
Child:			2b8fa240ea
Parents:		0a67a17399 f67ec3fcc0

Merge pull request #5591 from spdr870/feature/asynccrash

Clear revisiongrid before start reading log

Related links: View on GitHub, PR 5591

**Comment by mdonatas** [comment]
Thanks for the info. Still could repro with the latest master.

**Comment by spdr870** [comment]
Can you reproduce it on a repository reliable? Can you archive and send the .git folder?

**Comment by mdonatas** [comment]
This was a fun ride :)

![image](https://user-images.githubusercontent.com/483659/47229184-d16be400-d3cf-11e8-8a62-2cdb0c54d406.png)

Then noticing that:
`$ git -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b" --all --boundary --not --glob=notes --not --max-count=100000 --`
returns commits in a wrong order.

Finally bisect prooved useful yet again
![image](https://user-images.githubusercontent.com/483659/47229292-0d06ae00-d3d0-11e8-94dc-cbf6267c71da.png)

Creating PR..

**Comment by spdr870** [comment]
I expected this to be the problem. However, the performance loss for topo-order is huge. The order should be parent-child. Even without topo-order argument.

Are you using the latest git.exe? Does git gc solves the problem?

**Comment by mdonatas** [comment]
First answer here https://stackoverflow.com/questions/27036387/git-log-not-chronologically-ordered
Seems like `topo-order` is exactly for having the order where parents don't come before children.

```
PS C:\WINDOWS\system32> git version
git version 2.19.1.windows.1
```

`git gc` didn't help.

One caviat, this happens for me only when `Order revisions by date` is `off`.

**Comment by spdr870** [comment]
Could you maybe test how sublime-merge as a tool handles your repository? I know the do not use topo-order. Wonder is this tool works...

**Comment by spdr870** [comment]
Could you maybe test how sublime-merge as a tool handles your repository? I know the do not use topo-order. Wonder is this tool works...

**Comment by mdonatas** [comment]
Look at the screenshots here https://github.com/gitextensions/gitextensions/pull/5596, you can repro this in GE repo too.

**Comment by mdonatas** [comment]
Sublime Merge orders by date so it doesn't have this problem and I found no way to change the ordering it uses. (terrible client, I feel exhausted after 2 minute of using it)

Looking at
`$ git -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b" --all --boundary --not --glob=notes --not --max-count=100000 --`
With your comments in mind. There is no explicit ordering in this command and I suppose that is the problem.

**Comment by gerhardol** [comment]
The commits could be sorted/rearranged/visual clue after reading all logs if there are inconsistencies.

**Comment by spdr870** [comment]
@mdonatas Could you send me the .git folder archived of your gitextensions repository? I cannot reproduce the issue on my repo.

**Comment by mdonatas** [comment]
@spdr870 I've emailed you the link to my zipped repo to an email under your commits.

**Comment by drewnoakes** [comment]
I believe gitk reorders commits after reading them. I've seen the UI insert rows in between already visible rows while running. That's probably a more scalable (and more complex) approach.

@spdr870 how hard do you think it'd be to adapt to that?

**Comment by spdr870** [comment]
Ok, I am able to reproduce the issue.
Reordering runtime is possible, but the current graph logic is very complex. I will take a look at it.

**Comment by RussKie** [comment]
(Wishful thinking) Perhaps if we could refactor the graph in a way where it
deals with collections of (tree) data and doesn't have a tight relationship
with gitrevisions or gitmodule et al, it may become easier....

**Comment by spdr870** [comment]
I am working new graph code. Not sure if I will be able to get a better result then the existing code. The new code orders the revisions during the graph building. When finished, it should be a lot faster with a lot less code. Its already draws the graph correct. Including the repository in this issue. It will take some time to finish though!
![image](https://user-images.githubusercontent.com/38675/47266416-5e30b200-d536-11e8-93e4-32b9959ef609.png)

**Comment by mdonatas** [comment]
Thanks for the effort!
I understand this refactoring is in its early stage but still wanted to ask if you are aiming for a close to pixel perfect similarity to current graph? i.e. you don't have plans to sacrifice curves in the graph for performance, etc? If nothing else, rev graph must be visually appealing.

**Comment by spdr870** [comment]
I planned to use the same styling. Currently only working on the graph part...

**Comment by spdr870** [comment]
Getting closer. The ordering/straightening of the graph is difficult, this requires more work. Building the graph is a LOT faster.
![image](https://user-images.githubusercontent.com/38675/47268488-03a54f00-d552-11e8-8a7b-912a39d39544.png)

**Comment by spdr870** [comment]
Its off topic, but one more image to show the progress. Left is the new algorithm.
![image](https://user-images.githubusercontent.com/38675/47270506-0d887b80-d56d-11e8-941f-4bbe2a350778.png)

**Comment by gerhardol** [comment]
@spdr870 Make a wip PR when you want feedback

**Comment by spdr870** [comment]
@mdonatas Could you maybe test #5610 ? This should work on your repositories. Topo order and Date order are forced off in this PR.

**Comment by mdonatas** [comment]
Sure, I'll test a bit later today.
