### ISSUE TITLE
Setting order revisions by date has no effect

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5594]
**Do you want to request a *feature* or report a *bug*?**

:bug:

**What is the current behavior?**

3.0:
![image](https://user-images.githubusercontent.com/1003909/47218314-a2437b80-d3ab-11e8-8b76-4ad69f1a1475.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

2.51.04:
![image](https://user-images.githubusercontent.com/1003909/47218324-ae2f3d80-d3ab-11e8-99bb-f87206d0a6a7.png)

**Environment you encounter the issue:**

- GitExtensions version: 738ac6dfb89387751f1915d738ef1500ab5e46b7

**Did this work in previous version of GitExtensions (which)?**

2.51.04

**Comment by spdr870** [comment]
Strange. I do also notice some changed behaviour. But the commands to git.exe seem ok.

With date order enabled:
-c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b" --date-order --all --boundary --not --glob=notes --not --max-count=200000 --

Without date order enabled:
-c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b" --all --boundary --not --glob=notes --not --max-count=200000 --

**Comment by jbialobr** [comment]
The git.exe is the same.

**Comment by spdr870** [comment]
Is there a difference in the command used for date-order?

**Comment by jbialobr** [comment]
Perhaps it is because the command with date order has the `--topo-order` as well.

**Comment by jbialobr** [comment]
Here is a command from the 2.51:

log -z  --pretty=format:"<(__BEGIN_COMMIT__)>%n%H%n%P%n%T%n%aN%n%aE%n%at%n%cN%n%cE%n%ct%n%e%x00%s%x00%B%x00"  --date-order --reflog --all --boundary --not --glob=notes --not  --max-count="3000" --     

There is no `--topo-order` flag

**Comment by gerhardol** [comment]
The last of --topo-order of --date-order is used.
--topo-order was needed together with --reflog after the speedup by @spdr870 
But maybe it is OK to exclude --topo-order with --date-order

**Comment by spdr870** [comment]
Will fix this!

**Comment by RussKie** [comment]
It would be great if fixes like this could be accompanied by tests.
Otherwise this knowledge gets lost in history....

**Comment by gerhardol** [comment]
@RussKie The test that would have detected this is options to GUI rendering, and we have no such tests now
To test command options will give nothing here, it was an intended change, not replacing the implementation

**Comment by RussKie** [comment]
Respectfully disagree, if the `BuildArguments` method was extracted as
`GitLogCommand` class, then all its behaviors could be tested, and thus
documented.
