### ISSUE TITLE
Static analysis with PVS Studio

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5604]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
A number of issues seen in a static check with PVS Studio

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
As reported here:
https://www.viva64.com/en/b/0440/
(Unfortunately, no GE was not notified by this investigation).

An analysis on the current code basis shows similar issues. Some seem to be introduced since last major release too.
An example (PVS issue numbers):
 * V3083 null exception calling handlers
 * V3095 object used before null check
 * V3041 implicit int cast causes fractional loss
 * V3022 expression is always false
    - Check for Git running did ignore output
 * V3027 Variable used before null check

Except for the Git  running check, the issues should cause exceptions instead of proper error messages.
Most of the changes are just for unclear code, even removing duplicate checks.

**What is the expected behavior?**
Few ststic errors.

**Environment you encounter the issue:**

- GitExtensions version:
- GIT version: master

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by RussKie** [comment]
Top job, Gerhard!
