### ISSUE TITLE
Allow navigation to arbitrary commit through a script

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#5615]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
There is no way to navigate to a commit whose hash is returned from a user script.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
N/A

**What is the expected behavior?**
GE should allow creating user scripts through which it would be possible to navigate around the revision graph.
Here is my proposal for the implementation, though I am not sure if it would be that easy:
The script settings could support a new "keyword" (perhaps `{navigateTo}`, analogously to the existing `{openurl}`). It would take another script as an argument whose output would be interpreted as the commit hash to navigate to.

**Environment you encounter the issue:**

- GitExtensions version: master at `0a67a173999ff7a3177b0fdc3f5e51b6bd72e2ed`
- GIT version: 2.19.1.windows.1
- OS version: Windows 10
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**
No.

**Comment by vbjay** [comment]
Workaround.  Run script to get sha.  Copy sha.  Navigate menu-> Go to
Commit.
