### ISSUE TITLE
Git extensions crash when using the mouse wheel 

### ISSUE THREAD

**Issue by Noctis-** [gitextensions/gitextensions#5621]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Git extension will crash when using the mouse wheel

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Whenever i use the mouse wheel in 2.51 or 3.0 beta, it happens for me.

**What is the expected behavior?**
Git extensions scrolling without crashing :)

**Environment you encounter the issue:**

- GitExtensions version: GitExtensions.exe [2.51.05] (also happens on the 3 Beta)
- GIT version: 2.19.1.windows.1
- OS version: windows 10 Version 1709 (OS Build 16299.726) 
- .NET version: 4.7.2

** Extra Info / hardware details **
MSI GS65 laptop
currently using a Logitch Pro mouse (logitech gaming software Version 9.02.65 installed)
Other thoughts / variables: I've probably installed git and extensions via chocolatey.

**Did this work in previous version of GitExtensions (which)?**
Must have, because i've never had this problem before (reinstalled windows last week, seems to be happening since)

** Exception and stack trace:  **

```
System.OverflowException
Arithmetic operation resulted in an overflow.

   at GitUI.MouseWheelRedirector.PreFilterMessage(Message& m)
   at System.Windows.Forms.Application.ThreadContext.ProcessFilters(MSG& msg, Boolean& modified)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at GitUI.GitUICommands.<>c__DisplayClass332_0.<StartCommitDialog>b__0()
   at GitUI.GitUICommands.DoActionOnRepo(IWin32Window owner, Boolean requiresValidWorkingDir, Boolean changesRepo, GitUIEventHandler preEvent, GitUIPostActionEventHandler postEvent, Func`1 action)
   at GitUI.GitUICommands.StartCommitDialog(IWin32Window owner, Boolean showOnlyWhenChanges)
   at GitUI.GitUICommands.Commit(Dictionary`2 arguments)
   at GitExtensions.Program.Main()
```

**Comment by RussKie** [comment]
Is it happening in general or while you are doing something in particular?

**Comment by Noctis-** [comment]
Happened all the time today, whenever i've scrolled.
Open repository -> hover over the path, tried scrolling to get the next one -> crash
Open browse repo -> scrolled over commits -> crash
Open browse -> click to a diff , drag the scrollbar, works, use mouse scroll wheel -> crash

**Comment by Noctis-** [comment]
Talked to a guy on my team, took his mouse (steel series 110 i think), plugged it in ... no crashes with his mouse. 
Tried mine, no crashes.
unplugged his mouse, mine still is happy (in v 2.51). gonna try the 3 as well ... and maybe give the machine a restart to see how it behaves after one ...

**Comment by Noctis-** [comment]
worked in 3 beta as well ... restarted the machine ... seems to be working without a hitch now !?

I do have a 24 MB .dmp file in my crashdump if it's any help ... ?

**Comment by RussKie** [comment]
Glad to hear it is working now. I kind of suspect this may something to do
with the mouse drivers.

If I had more time available I'd stick my beak into your crash dump, but
right now I have to pass.

**Comment by drewnoakes** [comment]
@Noctis- what are the UI scaling settings in play here? Are you or your colleague running at other than 100% scaling?

**Comment by Noctis-** [comment]
Nope. No scaling applied.

Laptop screen 1920x1080 , 100% scale.
Dell runs 2560x1600, 100% scale

SSMS usually throws a fit as well ..had to disable hardware acceleration on it for it to look ok...

**Comment by vbjay** [comment]
Might be a graphics card issue.

**Comment by Noctis-** [comment]
@vbjay fair dinkum. I'll attach a screenshot of what SSMS used to do. it also had some flashy gradient color issues, but it seems it's a know issue with hi-res monitors (the dev who pointed me to the fix also has a big monitor).

I doubt the vid drivers are related TBH, but maybe. This is a new install of the machine, with all the latest drivers BTW. 

[When SSMS goes wild](https://imgur.com/a/oPoqxy6)

**Comment by RussKie** [comment]
FWIW we had reports (#5314) in the past that gpu drivers caused git issues.

**Comment by Noctis-** [comment]
Ah ha ! 

so, open GitExt , it fires on my laptop screen (1920x1080), i scroll happily ever after, no problem.
I then move it to the big screen (2560x1600), try to scroll -> exception + force closed.

It happens if i move it fullscreen (Windwos+right/left), or if i move it when it's in a window (so, same res/size).

Dunno if this helps much, but at least i have more info at least :)

**Comment by Noctis-** [comment]
More digging: 

Only happens with the Display Port cable. 

Connected display with HDMI , max resolution supported was 1920x1200. worked on both screens, no issues when scrolling.

Plugged back with DP cable, used same resolution 1920x1200 -> crash and burn.

So, it's not the resolution per se, but the fact that the nvidia graphic card is using the DP (mini DP tbh).

I've tried to see if i can use the external screen with the Intel gfx card, but it defaults to the nvidia one.

Here are the screen / graphic card details:

> Monitor 2
	Name	DELL 3008WFP on NVIDIA GeForce GTX 1070 with Max-Q Design
	Current Resolution	2560x1600 pixels
	Work Resolution	2560x1560 pixels
	State	Enabled
	Multiple displays	Extended, Secondary, Enabled
	Monitor Width	2560
	Monitor Height	1600
	Monitor BPP	32 bits per pixel
	Monitor Frequency	60 Hz
	Device	\\.\DISPLAY4\Monitor0

> NVIDIA GeForce GTX 1070 with Max-Q Design
	Manufacturer	NVIDIA
	Model	GeForce GTX 1070 with Max-Q Design
	Device ID	10DE-1BA1
	Revision	A2
	Subvendor	MSI (1462)
	Current Performance Level	Level 0
	Bus Interface	PCI Express x16
	Temperature	48 °C
	Driver version	25.21.14.1634
	BIOS Version	86.04.8a.00.88
	Memory	4095 MB
		Count of performance levels : 1
			Level 1 - "Perf Level 0"

Nvidia driver version: 416.34

Any point in contacting Nvidia ?

**Comment by Noctis-** [comment]
And here's a screenshot from the dmp file. Apparently it tries to read from a virtual address without the appropriate access

[dmp screenshot](https://i.imgur.com/5cD24Og.png)

**Comment by RussKie** [comment]
Thank you for following it up.

**Comment by RussKie** [comment]
> Any point in contacting Nvidia ?

I suppose it won't hurt.

**Comment by Noctis-** [comment]
Got in touch with Nvidia, basically said: Make sure you're using your laptop provider latest drivers ... which i thought might be 398, but apparently for my windows version are 391 ... so ... i'll need to go driver uninstalling / installing to see if it still happens ... might happen when i get some time ...

**Comment by Noctis-** [comment]
@RussKie my oh my ... It might not be nvidia after all ...

I didn't give it much thought since i've been busy and it's a bit of an end case, but it seems that it will only crash under the above conditions when [StrokesPlus](https://www.strokesplus.com/) is running. It's a mouse gesture application so, half makes sense to me in hindsight (the original issue suggested mouse). 

still no clue why it's only with git extensions, and only on second monitor, but I'll give the developer a ping see if he has any ideas :)

**Comment by RussKie** [comment]
Thank you for following it up and letting us know.

**Comment by roblarky** [comment]
Hi,

Developer of StrokesPlus here. I instructed Noctis to disable a preference that was intended for older versions of Windows before it would allow the mouse wheel to scroll over inactive windows. This resolved his issue.

For whatever it's worth, the (simplified) offending code in my app is below; it's just posting the mouse wheel message to the control below the mouse cursor.

```
MSLLHOOKSTRUCT *hookStruct = (MSLLHOOKSTRUCT*)lParam; //lParam as passed into the LowLevelMouseProc hook by Windows
CURSORINFO CursorInfo;
GetCursorInfo(&CursorInfo);
HWND hwndControlBelowMouse = WindowFromPoint(CursorInfo.ptScreenPos);
DWORD fwKeys = 0;
//The checks below are to ensure any keystates are sent along with the mouse message
if((GetKeyState(VK_CONTROL) & 0x8000) != 0){
	fwKeys = fwKeys | MK_CONTROL;
}
if((GetKeyState(VK_SHIFT) & 0x8000) != 0){
	fwKeys = fwKeys | MK_SHIFT;
}
if((GetKeyState(VK_LBUTTON) & 0x8000) != 0){
	fwKeys = fwKeys | MK_LBUTTON;
}
if((GetKeyState(VK_MBUTTON) & 0x8000) != 0){
	fwKeys = fwKeys | MK_MBUTTON;
}
if((GetKeyState(VK_RBUTTON) & 0x8000) != 0){
	fwKeys = fwKeys | MK_RBUTTON;
}		
if((GetKeyState(VK_XBUTTON1) & 0x8000) != 0){
	fwKeys = fwKeys | MK_XBUTTON1;
}
if((GetKeyState(VK_XBUTTON2) & 0x8000) != 0){
	fwKeys = fwKeys | MK_XBUTTON2;
}	
PostMessage(hwndControlBelowMouse, WM_MOUSEWHEEL, MAKEWPARAM(fwKeys,GET_WHEEL_DELTA_WPARAM(hookStruct->mouseData)), MAKELPARAM(CursorInfo.ptScreenPos.x,CursorInfo.ptScreenPos.y));
```

Based on the exception (Arithmetic operation resulted in an overflow) and glancing at the MouseWheelRedirector code, the only culprit I can think of is:

```var pos = new Point(m.LParam.ToInt32());```

I'm assuming he's running the 64-bit version of StrokesPlus and the LParam may be sent as such (I haven't tried to repro/debug, FYI). A quick search on the exception and ToInt32 leads to a [StackOverflow post about buffers and 32/64-bit process issues](https://stackoverflow.com/questions/36478303/arithmetic-operation-resulted-in-an-overflow-c-sharp). It may be that while Windows will ensure a 32-bit app only receives 32-bit mouse messages, my app is directly posting the message. Or perhaps your app also runs in 64-bit mode and it's really just a matter of improper casting to Int32.

Just some thoughts, I don't think this is really worth anyone spending their time on, nor am I even certain my assumptions are correct. But I figured I could at least bring closure to this and provide whatever extra info I have.

Rob

**Comment by RussKie** [comment]
Thank you Rob, much appreciated!

@NikolayXHD you're our WinAPI guru, thoughts?

**Comment by NikolayXHD** [comment]
@RussKie I conducted an NUnit test which proves @roblarky is right by pointing us at `.ToInt32()`

```csharp
[Test]
public void ArythmeticTest()
{
	var val = new IntPtr(0x00000000FFFFFFFF);
	Assert.Throws<OverflowException>(() => val.ToInt32());
}
```

The test passes which means we should improve the code where we convert LParam to Point like suggested [here](https://stackoverflow.com/questions/7913325/win-api-in-c-get-hi-and-low-word-from-intptr):

```csharp
//before
var pos = new Point(m.LParam.ToInt32());

//after
int x = unchecked((short)(long)m.LParam);
int y = unchecked((short)((long)m.LParam >> 16));
var pos = new Point(x, y);
```

**Comment by Noctis-** [comment]
Ya'll are legends … yep, i'm probably using the 64 one (though I cannot see
it in the app "about").
Thank you all for the help, and for the fact that now I don't need to
install old video drivers to prove it's not the problem :)

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/49125570-7eb6ff00-f28e-11e8-829a-0d07f4790efb.png)

**Comment by Noctis-** [comment]
You're correct @vbjay . both `GitExt` & `StorkesPlus` are running as 64.

**Comment by vbjay** [comment]
Yes.  So the issue is that intptr size varies on 64 vs 32 bit.  Someone assumed with ToInt32.

**Comment by RussKie** [comment]
Awesome team work!

@NikolayHD are you in a position to submit a fix?

**Comment by NikolayXHD** [comment]
yes, more or less by the weekend
