### ISSUE TITLE
Filter revision view for changes on different files/directories

### ISSUE THREAD

**Issue by tank09** [gitextensions/gitextensions#5623]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If specifying several patterns in "File filter" then nothing is displayed.

I checked the sources of git extensions and it seems that the code at line 100 (branch release/2.51) of FormRevisionFilter.cs prevents the usage of more than on search criteria, because it adds double quotes around the search pattern:
filter += string.Format(" \"{0}\"", FileFilter.Text.ToPosixPath());

**What is the expected behavior?**
We would like to use the "File filter" to specify different patters, e.g. to filter for all changes which are done in several directories or affected the specified files.
e.g. by specifying (without quotes in the dialog) "src/sub1 src/dir*", I would like to get all commits where files in the specified directories are changed.

I tested with a self compiled version where I don't add them at it seems to work.

Is there a special reason, why this double quotes are added ?

**Environment you encounter the issue:**
The code in FormRevisionFilter.cs is several years old, FileFilter introduced with commit fd4cb247039bf7d6ed0b7aea7c4103ae60ded181

**Comment by RussKie** [comment]
It looks like the master branch has changed, please check it
v2.5x is at the end of life, so it is unlikely to get patched.

**Comment by abluett** [comment]
The only thing issue i can see with it that it might break for people with spaces in their directories or file names e.g. "Source Code" as a root folder.

**Comment by tank09** [comment]
> 
> 
> It looks like the master branch has changed, please check it
> v2.5x is at the end of life, so it is unlikely to get patched.

I do not see any difference in handling, there is still the following line:
`return FileFilter.Text.ToPosixPath().Quote();`
in FormRevisionFilter.cs at line 122, which lead to the same git log command at the end.

**Comment by tank09** [comment]
> 
> 
> The only thing issue i can see with it that it might break for people with spaces in their directories or file names e.g. "Source Code" as a root folder.

This is true.
When we remove the quotes, then it would be necessary to escape the spaces, which we normally do with a backspace "\", but this is not working in this case, because of the call to ToPosixPath(), which replaces the backspace with forward slashes, because it thinks they are path separators.
The only quick solution was to use a "?" as placeholder for the space, which is not always correct.

I think the only way would be to change the way this filter is specified. If someone really needs to specify several files/directories, then the input needs to be a multi line field, where each line can be quoted by itself.

**Comment by tank09** [comment]
> > When we remove the quotes, then it would be necessary to escape the spaces...
> 
> ...or should we require users to wrap their paths in quotes, if paths contain spaces?

This would be the simplest solution without changing the UI, but it changes the current behavior. 
I have not found any examples for the advanced filters in the documentation (https://git-extensions-documentation.readthedocs.io/en/latest/browse_repository.html).

The question is if this change can be simply done and if it is sufficient to mention it in the changelog.

I think some filter samples should be added to the documentation, especially also for branch related filter, there seems to be some special values https://github.com/gitextensions/gitextensions/issues/3546.

**Comment by RussKie** [comment]
Would you like to have a go at it?

**Comment by tank09** [comment]
Do you expect to get a pull request for the code change (single line) or do you want to do it yourself ?

**Comment by RussKie** [comment]
Please submit a PR, if you can.
