### ISSUE TITLE
Commit Tab does not clear on init of new repo

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5624]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/3629489/47497748-1907cb00-d829-11e8-8375-b7ae8cc140ec.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open GE repo. 
2. Use start menu in GE to create a new repo
3. Notice the commit tab still has GE commit info

**What is the expected behavior?**
Commit tab to be empty on an empty repo.
**Environment you encounter the issue:**

- GitExtensions version:master
- GIT version: 2.19.1
- OS version: Microsoft Windows [Version 10.0.17763.55]
- .NET version: 4.7

**Did this work in previous version of GitExtensions (which)?**

**Comment by drewnoakes** [comment]
I'm pretty sure I reported this somewhere else.

It also happens if you just switch between repos.
