### ISSUE TITLE
Long branch name overflows in dashboard

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5625]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If a branch name is long, it overflows adjacent repositories in the dashboard:

![image](https://user-images.githubusercontent.com/350947/47501135-9a2c8580-d85c-11e8-9b28-a7c446fc6699.png)

**What is the expected behavior?**

Text is truncated with ellipsis or similar.

**Environment you encounter the issue:**

- GitExtensions version: beta1

**Comment by RussKie** [comment]
Ah yes, tiles width is calculated based on the longest repository path and
doesn't account for branch names.
Few possible options - truncate long branches (as you suggested) or account
for branch name when calculating tiles width. The former is probably
easier, and wouldn't have a significant effect on UX.

**Comment by anaplian** [comment]
I'll have a go at this if that's OK :slightly_smiling_face:
