### ISSUE TITLE
Rebase 'autosquash' shouldn't appear disabled

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5635]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Do an interactive rebase with `fixup!` commits.

Should be able to disable the `--autosquash` behaviour, but the checkbox is checked and disabled:

![image](https://user-images.githubusercontent.com/350947/47585338-e6f38780-d954-11e8-8263-453af38505f1.png)

**What is the expected behavior?**

Checkbox is enabled.

**Environment you encounter the issue:**

- GitExtensions version: 3.0 beta 1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**

Don't know.

**Comment by drewnoakes** [comment]
A workaround is to toggle "Preserve Merges". This enables "Autosquash".

**Comment by vbjay** [comment]
Already resolved by #5480.

**Comment by vbjay** [comment]
When it's interactive we always autosquash. It fixes the fixups and
squashes to be in the right order and have the right action in the Todo
list. Non interactive will not autosquash.


Nice. Check and uncheck interactive. Defenitly a bug.

**Comment by vbjay** [comment]
We need to run that code when the form loads so that based on the status of the ui, the checkboxes are correctly enabled or disabled.

**Comment by drewnoakes** [comment]
I don't see why this checkbox should ever be disabled. If we know there aren't any fixup/squash commits, we could hide it, but disabling makes no sense to me.

I explicitly don't want the fixups to be reordered, because they cause conflicts (in my scenario). By disabling it, I can manually apply them selectively.

**Comment by vbjay** [comment]
You can't autosquash and non interactive.

**Comment by vbjay** [comment]
https://git-scm.com/docs/git-rebase#_incompatible_options

**Comment by GintasS** [comment]
Is this still an issue, since autosquash gets enabled/disabled if you click on interactive rebase.
