### ISSUE TITLE
Delete dialog appears when pressing ctrl+alt+del on latest commit of a branch

### ISSUE THREAD

**Issue by dAnthonyB** [gitextensions/gitextensions#5636]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
If the latest commit of a non-checked out branch is highlighted, and the main Git Extensions window has focus, then when you press ctrl+alt+del, the delete dialog appears.

Edit: The Windows ctrl+alt+del screen comes up and you have to close it before the delete dialog appears.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Highlight the latest commit of a branch you do not have checked out.
2. Press ctrl+alt+del.

**What is the expected behavior?**
Delete key press should be ignored when pressing ctrl+alt+del.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.04
- GIT version: N/A
- OS version: Windows 7 SP1
- .NET version: N/A

**Did this work in previous version of GitExtensions (which)?**
Not sure.

**Comment by AbhiAgarwal192** [comment]
@dAnthonyB when i press ctrl+alt+del , it opens windows blue screen.

**Comment by RussKie** [comment]
I could replicate it in W10.

**Comment by AbhiAgarwal192** [comment]
@RussKie Is the repro steps same as what is given? 

Steps that i followed:-
1) Ran GitExtensions project.
2) On the non-checkout branch  in the ui , pressed ctrl+alt+del

**Comment by RussKie** [comment]
Yes, that's what I did to repro

**Comment by dAnthonyB** [comment]
@AbhiAgarwal192 It opens the Windows "ctrl+alt+del screen" like it's supposed to, but when I close the screen, the delete dialog will be active on GitExt.

**Comment by AbhiAgarwal192** [comment]
@dAnthonyB Got it. Thanks

**Comment by AbhiAgarwal192** [comment]
@dAnthonyB Issue fixed. Created a pull request for the same.
