### ISSUE TITLE
Performance issue when selecting large diff

### ISSUE THREAD

**Issue by spdr870** [gitextensions/gitextensions#5642]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Loading a large diff (22.000 changed files) for a commit takes forever. In the current master, loading selecting the diff tab in formbrowse is really slow. It took ~1 second before this commit:
https://github.com/gitextensions/gitextensions/commit/0655fc2e352ba80b62c00df60aa040413ad6c9a6
After this commit it takes over 1 minute. The application freezes and Windows asks to close the not responding application. Because merge commits often have large diff lists, the applications becomes unworkable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Select a commit with many changed files (e.g. 20.000). Select the diff tab. This performance hit is also very noticeable on smaller diffs.

To test this in a public repo:
In the linux repository, commit 589109df31843384f410ba09f6b8383464408d1e has 10.000 changed files. Takes ~10 seconds to load on my system. Before it was almost instant. It seems the length of the filenames have impact on the performance as well.

**What is the expected behavior?**
That is loads quickly. Browsing through commits should never hang the application.

**Environment you encounter the issue:**
Commit 0655fc2e352ba80b62c00df60aa040413ad6c9a6

- GitExtensions version: 3.00
- GIT version: 2.19
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Yes

**Comment by spdr870** [comment]
@NikolayXHD I am afraid a commit of yours caused some regression. Is this something you could easily fix? I used bisect to find the cause of the regressions, and do not fully understand the changes made.

**Comment by RussKie** [comment]
Which commit?
