### ISSUE TITLE
Commit Dialog: Commit button not as the default button

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5644]
**Do you want to request a *feature* or report a *bug*?**
unlucky UX, regression

**What is the current behavior?**
Hitting the `Enter`/`Return` in the Commit Dialog triggers the `Commit` button if the un/staged file lists have the keyboard focus.
This resulted in several incomplete commits. I do not want to amend commits (at least not for this reason).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- modify something
- open the Commit Dialog
- hit `Enter`/`Return`

**What is the expected behavior?**
The `Commit` action shall never be triggered by just hitting `Enter`/`Return` (unless the regarding button has the focus).
It can already be triggered by the existing hotkey `Ctrl`+`Enter`/`Return` (which should be displayed in the tooltip of the `Commit` button).

**Environment you encounter the issue:**

- GitExtensions version: master
- GIT version: (2.18.0.w.x64)
- OS version: (Windows 7)
- .NET version: (4.7)

**Did this work in previous version of GitExtensions (which)?**
2.5, older master

**Comment by RussKie** [comment]
This annoying behaviour exists in 2.51.04

**Comment by AbhiAgarwal192** [comment]
@mstv I dont think this is a bug because when you open the commit dialog , commit button by default has the focus and on pressing enter, the action triggers.

**Comment by mstv** [comment]
> This annoying behaviour exists in *2.51.04*

Yes, sorry, next time I will really check it with 2.5x. (I wonder why it didn't happen to me before, but several times last week.)
Thank you for fixing!

**Comment by RussKie** [comment]
Could you please give it a good run for the money - https://ci.appveyor.com/api/buildjobs/m5jw7hjxqcikl3h5/artifacts/Setup%2FGitExtensions-Portable-3.00.00.4000.zip

**Comment by mstv** [comment]
The Commit dialog works as expected.
But this portable build is missing a file in the About dialog:
![grafik](https://user-images.githubusercontent.com/36601201/47883878-0eec5a80-de2f-11e8-82e8-11384688ea21.png)
Not reproducible with 1f0f59c of your branch fix_5644_undo_FormCommit_default_button.
