### ISSUE TITLE
Git Notes don't show in beta 3.00.00.01

### ISSUE THREAD

**Issue by jdunne525** [gitextensions/gitextensions#5653]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Git Notes show just fine in v2.51.05, but don't show at all in the latest beta.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a git note.

**What is the expected behavior?**
The note should show as it does in the previous stable version.

**Environment you encounter the issue:**
Windows

The "Help-About Copy" or "Report an Issue" button doesn't seem to put anything into my clipboard either.

- GitExtensions version:
- GIT version:  git version 2.18.0.windows.1
- OS version:  Windows 10
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by vbjay** [comment]
> The "Help-About Copy" or "Report an Issue" button doesn't seem to put anything into my clipboard either.

That's because it was JUST added to master
![image](https://user-images.githubusercontent.com/3629489/47732413-84dca000-dc3c-11e8-9d4c-7b44366796d6.png)

**Comment by RussKie** [comment]
From what I could infer, the problem is that we initialise the body for each revision (L419):
https://github.com/gitextensions/gitextensions/blob/cfe0662fa8f05b5f8d3af5f9a13f654583381837/GitCommands/RevisionReader.cs#L407-L421

And when we display the revision we no longer attempt to load auxiliary information, such as notes:
https://github.com/gitextensions/gitextensions/blob/66380983451680c816d9a6c46797c37ed2507449/GitUI/CommitInfo/CommitInfo.cs#L195-L201

One way of fixing the issue is not to set the `Body` in the `RevisionReader`. 
I've run it locally and haven't observed any issues. However it kind of feels dirty to do this....

I've skimped through 2.5x codebase, and it looks like we didn't always read the body in `git log`. Hence we needed to hydrate this property on demand.

@spdr870 @drewnoakes @gerhardol: What's the best course of action?
@mstv: you rely on `revision.Body` property for #5643 to work, don't you?

**Comment by mstv** [comment]
> You rely on revision.Body property for #5643 to work?

No, I don't. `revision.Subject` is sufficient.
The `revision.Body` is not evaluated. It is just displayed in the tooltip, of the columns Graph and Message, if the `Body` is available. Else a -- meanwhile -- factored out, translatable hint is given.

**Comment by gerhardol** [comment]
Body is just read (or saved?) for commits not older than six months.
Drew made some investigations about it.
In GitModule.cs GetRevision() it seems like the intention is to fetch git notes if requested (and it should work in CommitInfo). 
So it may be a matter of requesting/keeping notes.

I suggest this is listed as a known error in beta2/rc1.

**Comment by RussKie** [comment]
Thanks, I'll downgrade it. Though we need to get it fixed for the official release.

**Comment by RussKie** [comment]
> In GitModule.cs GetRevision() it seems like the intention is to fetch git notes if requested (and it should work in CommitInfo).

I don't think this approach will work in the current use case. 
* we bulk load revisions into the revision grid, this is done without loading notes
* whenever a user clicks on a revision in a graph, the revision is passed on to the commit info control
* the commit info control loads notes only if the commit's body property is null

IIUC, we started loading the body of commits to show `[...]` in the grid.

Thinking out load, we can introduce `Notes` property, that can be loaded on demand, as oppose to tucking available notes to the body of a commit.
Thoughts?

**Comment by gerhardol** [comment]
> Thoughts?

Seem OK

**Comment by gerhardol** [comment]
This is worse than I saw in the first analysis. Notes can only be seen for commits older than 6 months that has multiline messages.

#6026 implements the handling similar to how it was done in 2.x, requesting the information if needed in CommitInfo. I.e. GE need to track if notes is included in the Body or if it should be loaded with a separate property. This limit processing and storage but adds some tenths of ms extra to open CommitInfo (not an issue). 
However, the "async loading" is required also in other situations, where the extra time may be too much:
 * The tooltip info includes the notes only if available, i.e. the CommitInfo has been shown (the info could be read async and tooltip being updated)
 * Copy similar to tooltip (the info should load here though), you need to click to copy

Another way could be to always load the notes or to separate notes and body in separate attributes.

**Comment by RussKie** [comment]
Let's patch it the way you've done it. We can rework it in the following releases.
