### ISSUE TITLE
RevisionGrid: Quick search is broken

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5658]
**Do you want to request a *feature* or report a *bug*?**
bug, regression

**What is the current behavior?**
quick search doesn't find commits anymore

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1.
  - check out master and select b7960d7
  - type `b` `c`
  - "bc" is displayed and the non-matching commit e4cd7e9 is selected

2.
  - select a newer commit from a different branch 
  - type `b` `c`
  - "bc" is displayed but the selection doesn't change

**What is the expected behavior?**
quick search finds the first matching commit seaching top down

**Environment you encounter the issue:**

- Git Extensions 3.00.a1
- b7960d79e0f1342064a18546108d21297398df64 
- Git 2.18.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0

**Did this work in previous version of GitExtensions (which)?**
yes, earlier master and 2.5

**Comment by spdr870** [comment]
I fixed this in #5648

**Comment by mstv** [comment]
Unfortunately, there are still regressions with #5648 (9fd101c):
1. `Quick search next/previous` (`Alt+Up`/`Alt+Down`) seems to search in the Message column first, then (sometimes?) in the Hash column.
2. There are "dead" search strings where the other matches are not found, especially with two characters.
E.g. `9``f`  will not find 9fd101c, but `9``f``d` does. Very strange!
With `b``c` no other commit might be found depending from which commit the search is started.
I guess the search iteration starts with the wrong row index -- at least sometimes.

**Comment by mstv** [comment]
Could you re-open this issue, please? I am not allowed to do it myself.

**Comment by spdr870** [comment]
@mstv Thats because the hash is only matched for strings longer then 2 characters. Look at this code fragment:

```
        public bool Matches(GitRevision revision, string criteria)
        {
            if (revision == null || string.IsNullOrWhiteSpace(criteria))
            {
                // don't throw exception for performance reasons
                return false;
            }

            if (revision.Refs.Where(gitHead => !string.IsNullOrWhiteSpace(gitHead.Name))
                             .Any(gitHead => gitHead.Name.IndexOf(criteria, StringComparison.OrdinalIgnoreCase) >= 0))
            {
                return true;
            }

            if (criteria.Length > 2 && revision.Guid.StartsWith(criteria, StringComparison.CurrentCultureIgnoreCase))
            {
                return true;
            }

            return revision.Author?.StartsWith(criteria, StringComparison.CurrentCultureIgnoreCase) == true ||
                   revision.Subject?.IndexOf(criteria, StringComparison.OrdinalIgnoreCase) >= 0;
        }
```

**Comment by mstv** [comment]
I still guess the search iteration starts with the wrong row index or uses the data of the wrong row -- at least sometimes.

Try searching for e.g. "tabcontrol" beginning starting from the current master commit 815491b. It "finds" the direct parent a2174bd, which doesn't contain the search string IMO. Then you're stuck: nothing happens on `Quick search next/previous` (`Alt+Up`/`Alt+Down`).

Of course, you're right that the hash is not matched unless the search string is longer than 2 characters. This is not too surprising for the user.
Though `revision.Author?.StartsWith(...)` is very irritating and surprising e.g. when searching for the author's last name. Nearly nobody will expect such a behavior.

Is somebody debugging this or shall I which might take some time?

**Comment by RussKie** [comment]
I'm not aware of anyone working on it.

**Comment by mstv** [comment]
@spdr870, the quick search uses the `RevisionGraph._orderedNodesCache` which is not filled completely. (The already available entries seem to be correctly mapped, i.e. my guess was wrong.)
Where from can we get reliable revision data?

**Comment by mstv** [comment]
How to call `BuildOrderedNodesCache()` without calling `BuildOrderedRowCache()`?
```C#
public void CacheTo(int currentRowIndex, int lastToCacheRowIndex)
{
    BuildOrderedNodesCache(currentRowIndex);

    BuildOrderedRowCache(currentRowIndex, lastToCacheRowIndex);
}
```
