### ISSUE TITLE
Commit info not sized correctly

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5665]
**Do you want to request a *feature* or report a *bug*?**
layout regression

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/4403806/47788639-6d013b00-dd66-11e8-9e6d-77d6ed79ff02.png)

**What is the expected behavior?**
The commit info is taking all available space

**Environment you encounter the issue:**
master @ 970ea53081a782f6c6dedbf5b146a51c80fa1c7c

- Git Extensions 3.00.a1
- 970ea53081a782f6c6dedbf5b146a51c80fa1c7c  (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3163.0

**Did this work in previous version of GitExtensions (which)?**
yes

/cc: @NikolayXHD

**Comment by mstv** [comment]
I appreciate the new split layout.
1. Now, the commit font can and should be applied only to the commit message (not to the links etc.)
2. Though I dislike the horizontal scrollbar. The combination of both word wrapping and horizontal scrollbar doesn't make much sense to me.
![grafik](https://user-images.githubusercontent.com/36601201/47821643-ac795880-dd61-11e8-9864-ab90a893266c.png)
3. The link section should have the same indentation as the above. I'd prefer thinner margins.

**Comment by vbjay** [comment]
2:  It only shows when the width is small enough.  Maximize window use vertical splitter till scrollbar hides.  

3:  Disagree.  The whole point is he has created a frame with the commit subject/body being attentioned by the slight indention.

**Comment by mstv** [comment]
2: My window _is_ maximized unless I take screenshots. The default width and splitter position are not compatible, need fine-tuning and/or should be restored after restart of the application.
But the main point is: Either use word wrapping, i.e no scrollbar, or resize the widget to the contained text.

3: Look at my screenshot without the avatar, please. Either the link section should be aligned or the spacer between the avatar and the commit data section should be hidden too if the avatar is hidden.

**Comment by NikolayXHD** [comment]
> 2: My window is maximized unless I take screenshots. The default width and splitter position are not compatible, need fine-tuning and/or should be restored after restart of the application.
But the main point is: Either use word wrapping, i.e no scrollbar, or resize the widget to the contained text.

working on it
