### ISSUE TITLE
FormAbout may clip text

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5666]
**Do you want to request a *feature* or report a *bug*?**
layout regression

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/4403806/47788812-ed27a080-dd66-11e8-98d7-43ebd0b4477f.png)

**What is the expected behavior?**
All text is shown without clipping

**Environment you encounter the issue:**
master @ 970ea53081a782f6c6dedbf5b146a51c80fa1c7c
- Git Extensions 3.00.a1
- 970ea53081a782f6c6dedbf5b146a51c80fa1c7c  (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3163.0

**Did this work in previous version of GitExtensions (which)?**
yes

/cc: @vbjay - I think we can make the form slightly larger

**Comment by vbjay** [comment]
On it.

**Comment by vbjay** [comment]
Found another bug I will fix with this issue.  

![image](https://user-images.githubusercontent.com/3629489/47789652-7f8a5e80-dceb-11e8-93fc-e1fe1f5d0f66.png)

**Comment by vbjay** [comment]
```c# if (!_alreadySet)
            {
                throw new InvalidOperationException($"{nameof(Initialise)} must be called first");
            }
```
I think I will return default info instead of exception.
