### ISSUE TITLE
Word wrap in commitinfo; body rendered small

### ISSUE THREAD

**Issue by spdr870** [gitextensions/gitextensions#5667]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Notice the commitinfo body in this screenprint:
![image](https://user-images.githubusercontent.com/38675/47789525-0d2e7400-dd15-11e8-867e-0fce1a1dd844.png)
Scrollings works btw!

**What is the expected behavior?**
That the body uses the full with that is available

**Environment you encounter the issue:**
Master (commit 9fd101c49d1dd8bb3545632c56cec6808a22edfb)

**Did this work in previous version of GitExtensions (which)?**
Yes

**Comment by RussKie** [comment]
Duplicate of #5665

**Comment by spdr870** [comment]
Oops... deleted
