### ISSUE TITLE
Revision graph distorted

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#5673]
**Do you want to request a *feature* or report a *bug*?**
Visual artifact

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/4403806/47831293-120e2900-dde4-11e8-82f1-e2489899845e.png)

**What is the expected behavior?**
Transitions are smooth

**Environment you encounter the issue:**

- Git Extensions 3.00.a1
- fdc76e3925cfaeed8f7ac6d93e663f0c60444344 
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3163.0

**Comment by spdr870** [comment]
I can work on this later today, when I get home.
A few questions since I cannot simulate this; 
- Do you use any scaling (hidpi)?
- Is this regressions? Did it also occur in 2.51? Did it occur in the 'old graph'?
- Can you send an screenshot in png? The jpg is too blurry.

**Comment by RussKie** [comment]
I observed this on work computer. It is an EOD here, won't be able to get
more info until tomorrow.

**Comment by spdr870** [comment]
Your tomorrow is probably my evening, so no problem..

**Comment by RussKie** [comment]
This is how it looks in **beta1 (official)** (left) vs **canary @ fdc76e3925cfaeed8f7ac6d93e663f0c60444344** (right)

![image](https://user-images.githubusercontent.com/4403806/47892610-cecbbd00-deac-11e8-8f5c-7a84e9fea0f6.png)

Resolution is 1920x1080 @ 100% scaling.

**Comment by vbjay** [comment]
Who was sitting on the washer while drawing?   LOL.

**Comment by RussKie** [comment]
@spdr870  I've run bisect between 970ea53081a782f6c6dedbf5b146a51c80fa1c7c and 278c963fb501cd6b3c141c0b3f92e6fb549d8021 - 9410cd6ea856fee4c3c99536150cee33f7de117e is the culprit.

Could you please have a look?

**Comment by spdr870** [comment]
I will try. But since I cannot simulate it, it will be hard.

Could you compare master against the last version before the new graph? I have an idea about the cause, this helps me verify.

The commit you found as the cause, is actually cherry picked. If it was wrong before, I think I know how to fix it.

**Comment by RussKie** [comment]
I tried the previous commit, it was fine.

I'm done for the week, won't have more info till next week.

On Nov 2, 2018 6:01 PM, "Henk Westhuis" <notifications@github.com> wrote:

I will try. But since I cannot simulate it, it will be hard.

Could you compare master against the last version before the new graph? I
have an idea about the cause, this helps me verify.

The commit you found as the cause, is actually cherry picked. If it was
wrong before, I think I know how to fix it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gitextensions/gitextensions/issues/5673#issuecomment-435289453>,
or mute the thread

**Comment by spdr870** [comment]
I pushed a possible fix to my fork:
Author:			Henk Westhuis <henk.westhuis@ultimo.com>
Date:			49 seconds ago (2-11-2018 08:29:13)
Commit hash:	b58feff3df215ec30c27f4adbf8a30ac845aa489
Parent:			49bfabd94d

Related links: View on GitHub

**Comment by RussKie** [comment]
Let's park it for now, this isn't a showstopper for beta2 (or whatever we
call it).

**Comment by RussKie** [comment]
Hey Henk, I tried your update and it seems to fix the issue:
![image](https://user-images.githubusercontent.com/4403806/47972434-450c3180-e0f0-11e8-8f4c-4a131946ebb5.png)

**Comment by serhii-kovalchuk-ideals** [comment]
I have same issue in version 4.x:

- Git Extensions 4.0.1.15887
- Build f2567dea28bbf0e2cbcd2a95d4c7200e47d0d671
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.22621.0
- .NET 6.0.12
- DPI 144dpi (150% scaling)
- Microsoft.WindowsDesktop.App Versions

```
    Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
    Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```


<img width="117" alt="image" src="https://user-images.githubusercontent.com/114428047/209935947-ceb7741e-8c2a-4de1-a8f4-65e13ddc4529.png">

**Comment by vbjay** [comment]
@serhii-kovalchuk-ideals you should create a new issue referencing this issue. This issue was closed.

**Comment by mstv** [comment]
@serhii-kovalchuk-ideals, can you reproduce this? Could you share the repo?
