### ISSUE TITLE
Exception: ReloadNodes must be called on the UI thread

### ISSUE THREAD

**Issue by schadin** [gitextensions/gitextensions#5674]
**Do you want to request a *feature* or report a *bug*?**
**bug**

**What is the current behavior?**
Exception window with message:
![image](https://user-images.githubusercontent.com/838185/47835919-43243480-ddb7-11e8-9028-ce4c533b14ef.png)

> Exception
> ReloadNodes must be called on the UI thread.
> ОК   

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add commit and push to remote.

**What is the expected behavior?**
No exception

**Environment you encounter the issue:**

- Git Extensions 3.00.00.3995Dev@427a0
- 427a0e9ecd91da4ebb34b56f9721e130b01baddb  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3163.0

**Did this work in previous version of GitExtensions (which)?**
Previous dev build.

**Comment by drewnoakes** [comment]
#5669 makes some changes around this. @amaiorano do you think you've fixed this?

**Comment by amaiorano** [comment]
@drewnoakes 

Was confused at first, but this actually *is* my change from #5669. I guess it got merged to some dev branch? I'm not seeing this merge commit anywhere, though...

In any case, this means there's a bug in my code. I thought clicking on UI menu items like "Reload" in the context menu always executed on the UI thread... is that not the case?

**Comment by drewnoakes** [comment]
Ah yes. @schadin is running your branch. Really this issue should have been opened against @amaiorano's repo, in that case.

**Comment by amaiorano** [comment]
Okay, I wasn't able to repro this, but I see that in FormBrowse, where it handles UICommands_PostRepositoryChanged, it makes sure to invoke RefreshRevisions async on the UI thread. I'll do the same and it should fix the problem.

**Comment by amaiorano** [comment]
Pushed a [fix for this](https://github.com/gitextensions/gitextensions/pull/5669/commits/61ed7da28f092a20a2905afa5796db043a242cbd). @schadin Can you test with the latest change? Thanks.

**Comment by spdr870** [comment]
> @amaiorano hi!
> Yeah, trouble is faded. But I see strange artifacts when drawing commit history.
> Just open repository:
> Cut image
> Press refresh
> Cut image 
> I'm not sure if your changes affect this functionality or a bug in something else.

This is fixed in #5675

**Comment by schadin** [comment]
> > @amaiorano hi!
> > Yeah, trouble is faded. But I see strange artifacts when drawing commit history.
> > Just open repository:
> > Cut image
> > Press refresh
> > Cut image
> > I'm not sure if your changes affect this functionality or a bug in something else.
> 
> This is fixed in #5675

@spdr870 thanks

**Comment by gerhardol** [comment]
Closing this issue as it was directed to PR #5669
