### ISSUE TITLE
Incorrect layout of the 'Specify branch' dialog

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#5676]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
The list of branches in the _Specify branch_ dialog scrolls horizontally instead of vertically and cannot be made larger.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Add a user script which uses the `{sBranch}` argument
2. Create several branches with long-ish names at a single revision
3. Run the script on that revision

**What is the expected behavior?**
The _Specify branch_ dialog allows an easy selection of a branch. Specifically:
1. The branch list should scroll vertically
2. When the dialog is resized, the list should be resized, too

The images below demonstrate the issues.

![obrazek](https://user-images.githubusercontent.com/11479798/47840106-79f94b00-ddb5-11e8-9199-614814f8eeed.png)

![obrazek](https://user-images.githubusercontent.com/11479798/47840116-8bdaee00-ddb5-11e8-9d3c-a90c5df3bc0c.png)

**Environment you encounter the issue:**
- Git Extensions 3.00.a1
- ca83a30227057fe263e9fe53656c165ca292247f 
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3132.0

**Did this work in previous version of GitExtensions (which)?**
I don't think so.

**Comment by spdr870** [comment]
Also, nice logo
