### ISSUE TITLE
File names in filestatuslist are rendered too narrow when full screen

### ISSUE THREAD

**Issue by spdr870** [gitextensions/gitextensions#5677]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the diff dialog, the filestatuslist is rendered too narrow when full screen. The problem disappears when scrolling, resizing or moving the splitter. Enlarge the screenshot to notice the problem. The filenames have ellipses.
![image](https://user-images.githubusercontent.com/38675/47840861-f8ef8300-ddb7-11e8-8945-af32c9a94e38.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Open the file history of any file
- Double click on a revision in the file history to open the diff dialog
- Make sure that the diff dialog is full screen, if not make it full screen and open again
- Notice the filestatuslist is not resized

**What is the expected behavior?**
- Use all available space

**Environment you encounter the issue:**

- Git Extensions 3.00.a1
- fdc76e3925cfaeed8f7ac6d93e663f0c60444344  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3110.0

**Did this work in previous version of GitExtensions (which)?**
Didn't notice this problem in the 2.5

**Comment by RussKie** [comment]
I am unable to reproduce it... I tried various shortening strategies (I typically don't truncate)

I'm @ cda113d52e967103be79c88697d24efd8ae88ab1

**Comment by spdr870** [comment]
I'm on the same revision. Maybe this helps. I needed to record full screen, that how it is reproduced.
![truncate](https://user-images.githubusercontent.com/38675/47856095-a1b4d700-dde6-11e8-84f6-82dba1f18cea.gif)

**Comment by RussKie** [comment]
Tried the canary build - https://ci.appveyor.com/api/buildjobs/lub99ets4uoig2kb/artifacts/Setup%2FGitExtensions-Portable-3.00.00.4066.zip
Works for me.
