### ISSUE TITLE
Revisions panel empties after double click in blame view

### ISSUE THREAD

**Issue by spdr870** [gitextensions/gitextensions#5678]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the blame dialog, when double clicking a revision in the left bar of the blame view, this panel becomes empty. Notice in the screenshot below.
![image](https://user-images.githubusercontent.com/38675/47841230-399bcc00-ddb9-11e8-918a-78e4d4c807ff.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Open filehistory on a file with enough lines to show a scrollbar in the blame view
- Go to blame tab
- Double click on an emty line in the left panel to go to that revision
- Notice that the entire empty line is selected, causing the commiter view scroll to the right.

**What is the expected behavior?**
- That that the panel content doesn't dissapear

**Environment you encounter the issue:**
- Git Extensions 3.00.a1
- fdc76e3925cfaeed8f7ac6d93e663f0c60444344  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3110.0

**Did this work in previous version of GitExtensions (which)?**
Didn't encounter this issue before.

**Comment by spdr870** [comment]
I think it has something to do with the (invisible) horizontal scroll. It scrolls to the right, causing the panel content not to be visible.

**Comment by RussKie** [comment]
I can repro it, but it feels more like it fails to render the text than a scroll.
I used https://github.com/cplotts/wfSpy to inspect the control, and the text is there, it just not rendering it. If you click off the revision in the top panel and click back, the text renders correctly...

**Comment by spdr870** [comment]
You can also simulating it when you scroll. That's why I think its a scrolling issue.
![scroll](https://user-images.githubusercontent.com/38675/47852974-a1fca480-dddd-11e8-8e85-bbfcfb99c9b2.gif)

**Comment by spdr870** [comment]
I investigated more. You have to double click on an empty line in the committer panel. That will cause the entire line to be selected.

**Comment by RussKie** [comment]
Fixed in #6399
