### ISSUE TITLE
RevisionDiff on merge: ArgumentException double clicking the diff header to collapse it

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5683]
**Do you want to request a *feature* or report a *bug*?**
bug, regression

**What is the current behavior?**
FileStatusListView contains an item without `Bounds`.
The function `FileStatusList.UpdateColumnWidth` throws a `System.ArgumentException` "value 1 is invalid for item" when determining the `contentWidth` although there are 133 items in the `FileStatusListView.Items`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- go to the GE revision d506e59
- click the `^` of the second diff heading or double click the heading
![grafik](https://user-images.githubusercontent.com/36601201/47942438-3b1cdf80-def2-11e8-8cc6-757bdceecd92.png)

**What is the expected behavior?**
the diff section gets collapsed

**Environment you encounter the issue:**
- Git Extensions 3.00.a1
- 815491b57d4f5bd3275eb06ca47fb8684276a7a4 
- Git 2.18.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0

**Did this work in previous version of GitExtensions (which)?**
don't know for master
cannot for 2.51.02 since not collapsible

**Comment by mstv** [comment]
Did somebody receive the e-mails I sent using the Exception dialog?

This dialog should have a third option (button) "Send and continue ignoring the exception".
Why should we terminate the application when some UI stuff throws an exception?
Yes, maybe it's the safest approach since one cannot lose much work if GE terminates.
(I know that I can close the Exception dialog using `Alt+F4` and the close button `x`. But then the exception is not sent.)

**Comment by RussKie** [comment]
No, NBug dialog doesn't send anything anywhere. It creates a zip archive in
your temp folder.
IIRC there is an open issue about it.

**Comment by gerhardol** [comment]
Raw fix...
![image](https://user-images.githubusercontent.com/6248932/47958321-5d356100-dfc9-11e8-92b9-97f6fb28f374.png)

**Comment by mstv** [comment]
Where can I download a *portable* build of the latest release 2.51.05? I only have one for 2.51.02.

**Comment by RussKie** [comment]
If you go to Appveyor build history, you'd be able to see 2.51 builds

**Comment by gerhardol** [comment]
The portable build is the Mono build (accidentally renamed in 2.51.02).

**Comment by RussKie** [comment]
> Raw fix...
> ![image](https://user-images.githubusercontent.com/6248932/47958321-5d356100-dfc9-11e8-92b9-97f6fb28f374.png)

Do you want to push it in? Right in time for the RC cut 😉

**Comment by RussKie** [comment]
Could you please test https://ci.appveyor.com/api/buildjobs/83hy62pen6dtt4k4/artifacts/Setup%2FGitExtensions-Portable-3.00.00.4310.zip
