### ISSUE TITLE
Commit dialog is not refreshing on form focus anymore

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5684]
**Do you want to request a *feature* or report a *bug*?**
bug, regression

potential **workaround:** switch the option off and on

**What is the current behavior?**
`Refresh dialog on form focus` seems to have no effect anymore

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- automatical refresh should have been activated using an earlier(!?!) build
![grafik](https://user-images.githubusercontent.com/36601201/47943650-55a58780-def7-11e8-9529-6b0ff1206476.png)
- switch away from GE
- modify something in the repo
- switch back to GE
--> the modification is not shown: neither the file list nor the file contents is updated

**What is the expected behavior?**
The Commit dialog is refreshed when it is focused again.

**Environment you encounter the issue:**
- Git Extensions 3.00.a1
- 815491b57d4f5bd3275eb06ca47fb8684276a7a4 
- Git 2.18.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0

**Did this work in previous version of GitExtensions (which)?**
earlier master
not availabe in 2.5x

**Comment by AbhiAgarwal192** [comment]
@mstv I tried reproducing the issue but its working fine for me. Here are the steps i tried:

1) Opened Commit dialog with "Refresh dialog on form focus" enabled.
2) Modified a file in notepad.
3) I could see the modified file getting displayed with the changes automatically.

Tried on latest version of gitextensions.

**Comment by crypto-rsa** [comment]
@drewnoakes I believe the regression happened in your commit a688346a21bd0ba9f22d0294c3547703e5a2ea20. The `_bypassActivatedEventHandler` is incorrectly set to `true` in the `finally` block of the `BypassFormActivatedEventHandler` method - it should be set to `false` there.

**Comment by crypto-rsa** [comment]
Steps to reproduce:
1. Open the Commit dialog
2. Commit some (but not all) of the changes
3. Make some more changes outside the Commit dialog (e.g. reset some changes files through the git console)
4. Go back to the Commit dialog

The changes should get rescanned but they don't.
