### ISSUE TITLE
Git version check is removed

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5695]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The Git version check is lost

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The settings have been split, separating GE and Git. The Git version check for minimum and recommended Git version was then removed.

In 2.x
![image](https://user-images.githubusercontent.com/6248932/47969256-1a30c780-e075-11e8-9c7c-cb5059891109.png)

3.0
![image](https://user-images.githubusercontent.com/6248932/47969260-36ccff80-e075-11e8-9f5b-83cf6c19b67c.png)

**What is the expected behavior?**
GE checks Git in the Settings

**Environment you encounter the issue:**
- Git Extensions 3.00.00.02-rc1
- 7990325547dd27e6a3fc1eaccee2607bbce66222  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3190.0

**Did this work in previous version of GitExtensions (which)?**
yes, master before split (in August?)

**Comment by RussKie** [comment]
Hmm, how did this happen?

**Comment by gerhardol** [comment]
This was changed in fd5122844bbbf9e2058674cc4d6dd3da94e40dfb #5132
When GitCredentialWinStire check was added, Git version was removed
(This was done in a refactor after reviews.)

GitUI\CommandsDialogs\SettingsDialog\Pages\ChecklistSettingsPage.cs
CheckSettings() does not call CheckGitCmdValid();

(I do not figure out why readding results in Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'bool' to 'System.Func<bool>'	GitUI	F:\dev\gc\gitextensions_4\GitUI\CommandsDialogs\SettingsDialog\Pages\ChecklistSettingsPage.cs	475	Active
)
