### ISSUE TITLE
Mono versions will check for upcoming 3.0 versions

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5697]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
GE/Mono will find 3.0 as updates but 3.0 has removed support for Mono.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not possible yet

**What is the expected behavior?**
Mono users only checks for 2.x updates

**Environment you encounter the issue:**
- GitExtensions version: 2.x

**Did this work in previous version of GitExtensions (which)?**
All versions works the same

**Comment by RussKie** [comment]
It has always been bothering me, but I don't think there is much we can do
on the app side. Users can be on an arbitrary old version...
However, the download link is to a msi file, which won't work on Linux, so
Linux users won't bother, a pull a zip file manually.

We should certainly add a warning to each release henceforth for Linux
users.

**Comment by Wirone** [comment]
I am Mono-based version user (2.51.05) and when I check for updates I got:

![image](https://user-images.githubusercontent.com/600668/49748552-4825af00-fca6-11e8-9470-f97c4e788f6c.png)

So probably it's not an issue?

Too bad 3.0 does not support Mono :(

**Comment by RussKie** [comment]
Thanks for checking, but we haven't updated the "update" branch yet.
I anticipate that you will get notifications to update, I'm not sure what would happen next.

**Comment by NamelessVoice** [comment]
Sad to see the Linux support dropped, I use Git Extensions every day at work, and it's just so nice compared to the other Git GUIs that I've seen.

But I guess 2.5 is still there and isn't going anywhere, so I can just continue to use that.

**Comment by RussKie** [comment]
We hope to bring back a xplat version in the future... Until then v2.5x is available.
