### ISSUE TITLE
Dirty status of 3.0RC1 release

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5698]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
rc1 has dirty status.  This is because files in the repo were modified from the current commit when the release was built.  

![image](https://user-images.githubusercontent.com/3629489/47970078-8f3cd680-e04e-11e8-9e12-fbc6eeecd537.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Build against a clean working directory.  
**Environment you encounter the issue:**

- Git Extensions 3.00.00.02-rc1
- 7990325547dd27e6a3fc1eaccee2607bbce66222  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0

**Did this work in previous version of GitExtensions (which)?**

**Comment by vbjay** [comment]
Ok. Cool. Good to know. At least it's documented now.

**Comment by gerhardol** [comment]
This will be fixed in next version (RC or final).
This issue can be open to notify others, but I propose it is closed.

**Comment by vbjay** [comment]
Either is good. It will show in searches but default search is open issues
only.

**Comment by gerhardol** [comment]
I added the 3.0 milestone to the release announcement to list what is fixed.
@RussKie No announcement on Transifex?
Will the HowTo be updated with signpath description?

**Comment by RussKie** [comment]
I've prepared base translations last night, will commit shortly. Transifex announcement would follow.
SignPath is somewhat complicated, and requires more time than I currently have. I hope to have some progress before long

**Comment by RussKie** [comment]
@gerhardol, I sent you an invite to our Transifex project

**Comment by RussKie** [comment]
This GitInfo addon is a major PITA... I spent countless hours making the git repo clean by assuming unchanged files, yet it would still mark the repo as dirty.
I'm going to delete .git folder when we build the release.

**Comment by spdr870** [comment]
I think we should be able to edit GitInfo.
https://github.com/kzu/GitInfo/blob/master/src/GitInfo/build/GitInfo.targets#L269

We might be able to change the git command used to check if the index is clean is executed. Or even set the property GitIsDirty to true manually.

**Comment by vbjay** [comment]
You can add an argument to prepare script that says create the commit or not.

**Comment by vbjay** [comment]
Why I included dirty.  If the running code was compiled and is different than HEAD then we need to know this.  If the code is at sha X and the code is different then we can say you weren't running X code.  Of course it will be dirty if you create a release and version numbers changed and the changes were not committed.

**Comment by gerhardol** [comment]
dirty flag should be there in my opinion. The build procedure should be changed, for instance to use the AppVeyor version if it exists, hardcoded otherwise. But that should not block the 3.0 release.

I suggest removing dirty flag for now, that is the easiest way forward.

**Comment by vbjay** [comment]
Instead.  Alter the prepare script.  

Add a switch param CommitVersionChange
when the value is $true

- create a version bump commit
- do other work in script ( build and such)
- push

**Comment by vbjay** [comment]
Heck.  In the version change portion stage each file after the version change is made to the file.  Then all you need is to call git commit -m "Formatted message like bump version from OldVersion to NewVersion.

**Comment by vbjay** [comment]
OMG! We do not run prepare release on appveyor.  Get it?

**Comment by vbjay** [comment]
I did say add a switch to the Prepare script.  It can be passed to the
version change script too.

**Comment by vbjay** [comment]
Something like this.  Just rough code.

![image](https://user-images.githubusercontent.com/3629489/49405045-56f8e880-f71f-11e8-914f-b6cdc786dcdf.png)

![image](https://user-images.githubusercontent.com/3629489/49405077-6c6e1280-f71f-11e8-9840-77e1e4829a94.png)

**Comment by RussKie** [comment]
In a 1,567,547th attempt to fix this, I started committing changes locally
on the build server.
The exe now is 'clean' however the version is now "3.00.00.455@dev"....

**Comment by vbjay** [comment]
I'll have a pull request ready in a few minutes.  Testing the solution now.
