### ISSUE TITLE
Graphical glitch on merge graph

### ISSUE THREAD

**Issue by tompollok** [gitextensions/gitextensions#5714]
- GitExtensions version: 3.0 RC

![grafik](https://user-images.githubusercontent.com/4457821/48080357-baa9f780-e1ed-11e8-915d-67f3cf5b5e58.png)

It seems like there is a 1 pixel shift on the graph when there are merges. My machine is Windows 10 with 4K displays.

**Comment by spdr870** [comment]
Fixed in #5673
