### ISSUE TITLE
BUG: opening gitextensions 3 changes something in settings that gitextensions 2.51.05 losses favourite directories list.

### ISSUE THREAD

**Issue by Aukstkalnis** [gitextensions/gitextensions#5718]
BUG:

**What is the current behavior?**
When I open gitextensions 3 and close it, then open gitextensiosn 2.51.05, all my favourite repositories are gone.
However, opening gitextensions 3, all marked repositories, that was lost in gitextensions 2.51.05, are visible.

**What is the expected behavior?**
That I do not lose my marked repositories.

**Environment you encounter the issue:**
- GitExtensions version: 2.51.05
- GIT version: 2.19.1.windows.1
- OS version: Windows 10

**Did this work in previous version of GitExtensions (which)?**
Have not tried.

**Comment by RussKie** [comment]
V3 has a different format for storing favourites. It migrates favourites
into new format.

**Comment by RussKie** [comment]
They are migrated into the new format.
If they weren't, users would be unhappy - "I had my favourites in the old
version, in the new version I haven't re-create them again".
If the settings were duplicated, then we'd have to reconcile what was
copied, what wasn't, and that is a significant overhead.

Could you please share the reasons for switching v3 to v2.5x and back?

**Comment by Aukstkalnis** [comment]
I don't think that it is a good idea to break older version just like that.
I am using version 3 just for testing because it is not quit usable for large repositories. And the other reason is that there is not yet stable release for v3.
Me suggestion for fixing this:
1)  add new favourite repositories format support from v3 to v2
2) v3 version works with both formats. When adding new favourite from v3, it will also add for v2. When loading v3, all v2 favourite repositories are checked and mismatch fixed in v3.
Personalty I would prefer first method. But this is only my opinion. Maybe you can think something more appropriate.

**Comment by gerhardol** [comment]
I suggest adding this as a known error and keep it like that.
Some users will switch back and forward in the RC phase, after that (when this can be implemented at the earliest), it is more stable.

**Comment by spdr870** [comment]
> I am using version 3 just for testing because it is not quit usable for large repositories.

@Aukstkalnis Could you explain why its not usable for large repositories? Maybe create another issue for this? I work with reasonable sized repositories myself (130K commits) and for me 3RC1 its a lot faster and more responsive. If there is any issue, I would like to work on this.

**Comment by Aukstkalnis** [comment]
There are some cases. One of them are that when starting gitextensions 3 after it was closed with open repo, it can't load previous repo and always shows loading.

**Comment by spdr870** [comment]
> There are some cases. One of them are that when starting gitextensions 3 after it was closed with open repo, it can't load previous repo and always shows loading.

I just tried this, but a cannot seem to spot any issue. I also tried with the option "Open last repository at startup" on and off. Please create issues including steps on how to reproduce for the cases that hold you back from using version 3.00RC. We are already at the release candidate state, so it is important for us to be aware of all issues left. You can be of great help if you report them.

**Comment by RussKie** [comment]
> And the other reason is that there is not yet stable release for v3.

RC1 is quite stable.

> it can't load previous repo and always shows loading.

I believe it is the same as reported in gitter channel and in #5629 (second part of it).
Please use refresh as a temporary workaround.


> 1. add new favourite repositories format support from v3 to v2

This is not going to happen.

**Comment by RussKie** [comment]
#5629 is fixed in [RC2](https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00-rc2), please give it a try

**Comment by Aukstkalnis** [comment]
Indeed it is fixed. I noticed that returning from opened repository to favourite list is slow and when I tried to clear recent opened repository list, gitextentions crashed.

**Comment by Aukstkalnis** [comment]
Since you will not fix it, then there is nothing to discuss. Case close.

**Comment by drewnoakes** [comment]
@Aukstkalnis since using v3 have you had any reason to go back to v2?

**Comment by Aukstkalnis** [comment]
No, I am using v3 for quite some time now.
