### ISSUE TITLE
GitExtensions 3.0 RC1 crashes with a System.UnauthorizedAccessException if the .gitconfig file is hidden.

### ISSUE THREAD

**Issue by Gyokur0** [gitextensions/gitextensions#5719]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
GitExtensions 3.0 RC1 crashes with a System.UnauthorizedAccessException if the .gitconfig file is hidden.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Navigate to your user folder and set the .gitconfig file hidden. 
(Right click on the file, select properties and set the checkmark to hidden)

**What is the expected behavior?**
No crash, like version 2 it should write the settings file without issues.

**Environment you encounter the issue:**
- GitExtensions version: 3.00 RC1
- GIT version: 2.19.1.windows.1
- OS version: Win 10 Pro 64
- .NET version: 4.7.3190

**Did this work in previous version of GitExtensions (which)?**
Yes in every 2.x

**Comment by RussKie** [comment]
Is there any particular reason for hiding the config?

**Comment by Gyokur0** [comment]
My user folder is quite cluttered with many dot files, so I hide many of them, which are not accessed regularly.

But the 3.0 should not crash, hidden or not.

**Comment by Gyokur0** [comment]
@RussKie Hi, I looked into the source, and suspected the problem in FileSettingsCache.cs
But while looking around I cannot recreate the issue.
I now works flawlessly with the hidden file.

I would suggest we close it for now.
Sorry for the false issue.

**Comment by RussKie** [comment]
No worries at all.
If you get it again, please capture the stack trace, it could help us
finding the root cause.
