### ISSUE TITLE
Feature Request: Github Plugin to add a My Organizations Repositories tab

### ISSUE THREAD

**Issue by CreepyGnome** [gitextensions/gitextensions#572]
It would be great if the Github plugin could show the user's repositories AND any of their Organizations they have repositories. Seems that another tab called My Organizations Repositories or something would make sense here.  It could be the same columns as My Repositories tab plus one called Organization to show which organization the repo is from.

This would be much more convenience right now the only way to get to one of the repositories for your organizations is to use the search tab.  It works, but would be much nicer to just have a tab that showed them.

**Comment by jrfnl** [comment]
+1
