### ISSUE TITLE
Push Multiple Branches hang if using OpenSSH for key mgmt

### ISSUE THREAD

**Issue by DmitriK** [gitextensions/gitextensions#573]
If using OpenSSH as the ssh client, the "Push Multiple Branches" tab in the push command causes Git Extensions to hang. Switching to putty fixes the issue.
Looking at the process tree, git extensions seems to be hanging when fetching remote branches:

* "C:\Program Files (x86)\GitExtensions\GitExtensions.exe" 
    * "c:\Program Files (x86)\Git\bin\git.exe" ls-remote --heads "origin"
        * ssh git@server.ip.here "git-upload-pack 'myProject.git'"

If I kill the stuck git/ssh process, git extensions restores itself, but only shows local branches in the push window.
I think ssh is waiting for the key password, but the prompt for the password doesn't show up for this particular feature.

**Comment by hypersw** [comment]
https://github.com/gitextensions/gitextensions/pull/3152 might fix this. [Here is a preview build.](https://github.com/JetBrains/gitextensions/releases/tag/2016-03-14)

**Comment by karyon** [comment]
it probably does not, because in this case, no console window shows up at all.

**Comment by karyon** [comment]
it probably does not, because in this case, no console window shows up at all.

**Comment by karyon** [comment]
@hypersw suggested opening a console window by timeout. this would fix this issue by making the password prompt available and also tell the user what's going on if the remote needs several seconds.

**Comment by hypersw** [comment]
The idea is that besides the push itself, which opens the regular git command window with the console and supports all the necessary prompts, there's a preliminary call to the server which happens in the background and does not show the command window — to learn which branches are on the server, probably. If that is actually the case, then possible options are (1) be able to proceed without this async info, as it's not critical (and kill the child processes); and the push window itself will be able to do the prompt; (2) show the invisible window of the background command after some delay.
