### ISSUE TITLE
CommitInfo alignment issue

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5730]
**Do you want to request a *feature* or report a *bug*?**

Layout bug

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/350947/48232584-00132400-e3aa-11e8-9916-04cdae82a603.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I'm not sure how to reproduce this. I haven't seen it before just now. If I work out how to do so, I'll comment.

**What is the expected behavior?**

Everything lines up properly.

**Environment you encounter the issue:**

- Git Extensions 3.00.00.02-rc1
- 7990325547dd27e6a3fc1eaccee2607bbce66222  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3190.0
- UI scaling at 150%

**Comment by RussKie** [comment]
I've seen this few times, but not consistently
