### ISSUE TITLE
About->Copy should include DPI scaling

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5732]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the expected behavior?**

The information copied to the clipboard should include DPI scaling information. This can be very useful when understanding a user's computer configuration.

These values are available via `DpiUtil`.

I'd suggest getting this in for 3.0, to help with issues that come in.

**Environment you encounter the issue:**

- Git Extensions 3.00.00.02-rc1
- 7990325547dd27e6a3fc1eaccee2607bbce66222  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3190.0

**Comment by vbjay** [comment]
Sure. I can get that in there. Great idea.

**Comment by vbjay** [comment]
Using another computer.  I'll get this in tonight.  My computer decided it wanted to forget it had a drive D.  :O

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/48302779-ffc07900-e4ce-11e8-87d7-50f819c098c5.png)

Formatting ok?
