### ISSUE TITLE
Broken AutoPull on rejected push

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#5734]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I have set an option to pull with the default pull action when push is rejected.
The pull is performed with fetch option. Since fetch did not modify the local state
GE goes into an infinite loop of push and fetch operations.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

AutoPull action should be performed with the default pull action.

**Environment you encounter the issue:**

- Git Extensions 3.00.a1
- 89897d085a60823f72ba5045fad6d84dd02bc58b 
- Git 2.18.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3190.0

**Did this work in previous version of GitExtensions (which)?**
2.5x

**Comment by vbjay** [comment]
Try with rc1 or master.

**Comment by RussKie** [comment]
@jbialobr are you able to fix it?

**Comment by jbialobr** [comment]
I will try to devote some time to it tomorrow.
