### ISSUE TITLE
Differentiate between identical rename and modified + renamed

### ISSUE THREAD

**Issue by hultqvist** [gitextensions/gitextensions#5744]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Files that are renamed and modified show with the rename icon, "Aa".
At a quick glance you can't see if there was a modification.

**What is the requested behavior?**

Make the icon indicate whether the file has been modified while renamed.
Renamed files with identical content keep the current icon, "Aa".
Renamed and modified files get the modified icon(pen).

Example how this could be implemented.
https://github.com/hultqvist/gitextensions/commit/f015f578e3efedaf06c7a94d6c3324e201ff417e

    if (gitItemStatus.IsRenamed)
    {
        if (gitItemStatus.RenameCopyPercentage == "100")
        {
            return 3; //Rename icon
        }
        else
        {
            return 2; //Modified icon
        }
    }

- GitExtensions version: master branch

**Comment by RussKie** [comment]
Thank you.
Are you in a position to send a PR in?
