### ISSUE TITLE
Exception opening About dialog (Missing System.Runtime.InteropServices.RuntimeInformation.dll)

### ISSUE THREAD

**Issue by sascfuel** [gitextensions/gitextensions#5750]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I want to open the About Dialog I get the following exception.
The same happens with Help - > Report an issue

> Could not load file or assembly 'System.Runtime.InteropServices.RuntimeInformation, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
 
(The system cannot find the file specified)

This assembly is included in NET Framework beginning with version 4.7.1 but Readme.md says GitExtensions 3.0 works with NET Framework 4.6.2+

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

I have extracted GitExtensions 3.00.00.02 RC2 to an directory opened it and clicked on Help --> About

**What is the expected behavior?**
No exception, or a check for the needed framework version.

**Environment you encounter the issue:**

- GitExtensions version: 3.00.00.02 RC2 portable
- GIT version:  2.19.1
- OS version:  Windows 7 SP1
- .NET version: 4.6.2

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.51.05

**Comment by RussKie** [comment]
I have decompiled the msi, and it looks the assembly in question is packaged:
![image](https://user-images.githubusercontent.com/4403806/48345569-7d9da380-e6cc-11e8-93a3-0f743236f737.png)

**Comment by RussKie** [comment]
I have a clean install and I can't reproduce the problem.

**Comment by sascfuel** [comment]
You're right. In the msi the file get's installed, but in the *portable* it is missing.

**Comment by RussKie** [comment]
Thank you for clarification

**Comment by vbjay** [comment]
Oops. I'll fix the portable.

**Comment by RussKie** [comment]
I have re-packaged and re-published the portable archive. Please give it a try.
