### ISSUE TITLE
Show cherry picked commits in the revision graph

### ISSUE THREAD

**Issue by stojy** [gitextensions/gitextensions#5761]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Cherry picked commits do not show in the revision graph column.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
n/a
**What is the expected behavior?**
In addition to the description shown in the commit, add a graphical indicator (e.g. dashed line) in the revision graph column showing the source of the cherry picked commit.  i.e. similar to the merged branch solid line.

This would be very useful as a tool to visually identify the source of a cherry picked commit at a glance without having to read through the commit description and manually locate the source commit with the matching hash.

**Environment you encounter the issue:**
n/a

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.15063.0
- .NET Framework 4.7.3163.0
- DPI X:100.00% Y:100.00%

**Did this work in previous version of GitExtensions (which)?**
n/a

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/48393587-31f3f580-e6de-11e8-9e66-facdaccbbab1.png)

How do you expect GE to know it is a cherry pick?  A cherry pick is just a new commit that has the same changes as another commit.  Cherry pick commits are not guaranteed to have a specific commit message either.

**Comment by drewnoakes** [comment]
@stojy can you provide a screenshot other app(s) that do this for reference, and/or your own mock up?

Are there other scenarios in which you think additional annotations on the graph would be useful?

**Comment by vbjay** [comment]
If we translate the cherry commit message then it could be interesting knowing a commit is a cherry pick. I really don't thino it is feasible or reliable if it is. I recommend we close this issue.

**Comment by gerhardol** [comment]
The idea itself is nice, but the functionality and realization is not reasonable.

There is no standard for "cherry-pick" marking so the feature would require configuration on how to find cherry-picking.
Parsing commit messages for this information will slow down the revision parsing.
In addition, modifying the graph code is complex.

I also suggest rejecting.

**Comment by stojy** [comment]
As requested, here is an example screenshot (taken from Tortise Hg) showing how a cherry picked commit could look as per my earlier description.  The dashed line represents the cherry picked commit.
![image](https://user-images.githubusercontent.com/11408611/48452406-f7777f00-e7e9-11e8-9af2-7428ad8a79a6.png)

@vbjay, regarding reliability, if the user checks the 'add commit reference to commit message' then that would be create a re-producible and consistent commit message (i.e. reliable)?

@gerhardol, I can't really comment on the processing time/effort needed to parse a commit message looking for the 'cherry picked section of the comment'.  Presumably though the commits that are the result of cherry picking could be tagged in some manner to make the lookup quicker.  Or if it's really too slow then this feature could be setup as 'opt out' by default.  At any rate, from a user perspective it'd be a lot quicker for GE to parse the commits instead of a user having to manually pick through the commit messages and then trying to locate their source commits.

Ultimately, this was a very useful feature in Tortoise Hg.  And it seems like if it were implemented in GE then it would be another one of those cool/useful features that sets it apart from it's competition.

**Comment by RussKie** [comment]
@spdr870 is this feasible?

**Comment by vbjay** [comment]
Here is the issue and why git will most likely not support it.  

A cherry pick is just a copy state from one commit.  It can even create the commit state and not commit so user can alter as desired and then commit.  A cherry picked commit does not have any link to where it came from.  It has a new parent of the current head,.  The commit you are cherry picking from is not even guaranteed to be pushed.  So I cherry pick commit x to create y.  X is a local only commit on another branch.  I push my current branch.  The only commits that are pushed are the current branch commits.  Not x.  The reference will be broken.  

So like I said.  Git does not have anyway for this to be known.  Parsing messages would be a poor way and not reliable.

**Comment by pcalin** [comment]
Hehe, I know and I'm not holding my breath for it.

However, the reference would not be broken in the sense that git database would be fully functional without the other branch. Somewhat useless though.

In mercurial and tortoiseHg it was a very nice feature, that's all.

**Comment by gerhardol** [comment]
mercurial has its strength too, the "James Bond" vs "McGyver".
We will not be doing this, in this way at least.

**Comment by drewnoakes** [comment]
@stojy thanks for the screenshot. It's an interesting idea but I agree it doesn't really fit with the git way of doing things. Not to mention it'd likely be quite hard to do for small/questionable benefit. It's always interesting to think how we can show more information in the UI though.

**Comment by stojy** [comment]
No problem.  I appreciate the reasons why it's preferable not to create this concept via GE UI constraints (as per my earlier description) and would prefer to only implement such a feature if it was natively supported by git.

@gerhardol, as you rightly point out.. git and hg are indeed different each with their pros and cons.

Thanks everyone for investing the time reviewing the request.
