### ISSUE TITLE
Help / Translate just shows a login screen

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5766]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**

Clicking the "Translate" item in the "Help" menu takes you to:

https://www.transifex.com/signin/?next=/git-extensions/git-extensions/translate/

Which looks like this:

![image](https://user-images.githubusercontent.com/350947/48409128-f20b2d80-e732-11e8-951b-162a7b2f34fd.png)

**What is the expected behavior?**

The user is taken to a friendlier page, increasing the chance they'll contribute to translations.

Perhaps a wiki page on this repo (doesn't look like one exists yet).

**Environment you encounter the issue:**

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3190.0
- DPI X:150.00% Y:150.00%

**Did this work in previous version of GitExtensions (which)?**

No.

**Comment by gerhardol** [comment]
Same on the Readme
Add a wiki page

**Comment by RussKie** [comment]
Good idea

**Comment by vbjay** [comment]
Could just put them here
https://www.transifex.com/git-extensions/git-extensions/

![image](https://user-images.githubusercontent.com/3629489/48532540-d442e300-e86e-11e8-91fe-ad9d6269032b.png)

**Comment by vbjay** [comment]
Not logged in to site user sees 

![image](https://user-images.githubusercontent.com/3629489/48532643-356ab680-e86f-11e8-83e7-d69a7d22e057.png)

**Comment by drewnoakes** [comment]
If this isn't so big to do, it might be good for 3.0, in case we drop some languages. People who upgrade may be motivated to help add translations, and we can make that process easier. @RussKie, your call for triage.

**Comment by RussKie** [comment]
I think wiki page may be a good option, aligns with every other outgoing link.
As a quick alternative - @vbjay's suggestion is good too

**Comment by drewnoakes** [comment]
A point in favour of the wiki page is that we can change it immediately with zero friction. The transifex experience we have no control over, and changing the target requires rolling out an update and users to upgrade. I vote for control over the experience.

**Comment by drewnoakes** [comment]
Even if the wiki page is a placeholder for now, I think it's worth it in the longer term.
