### ISSUE TITLE
Do not open autocomplete when moving in the commit message editor

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5770]
**Do you want to request a *feature* or report a *bug*?**
UX improvement

**What is the current behavior?**
The autocompletion list pops up and consumes further navigation key presses ([Page]Up/Down, Home/End) when moving through the commit message.

(I know that the list can be closed using Escape and that it can be switched off completely.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- type an identifier from a modified file into the Commit Message Editor
- use the Up/Down keys to position the caret outside and back in this identifier
- further navigation keys will change the autocomplete selection

**What is the expected behavior?**
The autocompletion list shall pop up only when typing a word or on request (Ctrl+Space).
Caret positioning shall work without interruption.

**Environment you encounter the issue:**
3.x, 2.51.05

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by RussKie** [comment]
Not a solution by any means, but as a workaround one can disable the auto-complete completely (I did).

**Comment by mstv** [comment]
> Not a solution by any means

Do you mean such a change would not be accepted?
Or do you expect it was nearly impossible to implement?

To clarify it: Once the auto-completion list is open, the navigation keys shall still be forwarded to it.
When a navigation key was pressed, the opening of the list should be suppressed, at least after vertical movement.

**Comment by RussKie** [comment]
> Do you mean such a change would not be accepted?

No, not at all.

If you or someone else wishes to tackle this issue - fire away. :)
