### ISSUE TITLE
Can't connect to build server of TFS 2017 on premise

### ISSUE THREAD

**Issue by Noguai** [gitextensions/gitextensions#5773]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When trying to use the build server integration plugin "VSTS and Team Foundation Server (since TFS2015)" with a on premise instance of TFS2017 the plugin can not connect to the build server when entering the build server data as requested by the configuration UI. Build results just won't be listed, as there is no other feedback that there was an connection issue.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
The URL of a TFS project is structured like:
`http://<url of tfs instance>/<team collection name>/<project name>/...`

For a TFS build server that makes the required api available under the following URL:
http://somehost:8080/tfs/DefaultCollection/MyProject/_apis/build/builds?api-version=2.0

The build server data one would enter for a on premise instance would be as followed:
Server Url: http://somehost:8080/tfs
Team collection name: DefaultCollection
Project name: MyProject
Build definition name (all if left empty): §leave empty§
Rest Api Token: §your token§

The connection fails, because:
1. Part of the server URL (in this case "tfs") is disregarded, when the server url misses a trailing slash
2. The plugin completely ignores any input into the team collection name field

**What is the expected behavior?**
Either the UI should be adjusted to request the correct information in the correct way, or the connection to the build server should succeed with the information entered like above. 

Reducing the inputs to the following would make things even easier to configure, as team collections don't exist in VSTS (now Azure DevOps) as far as I know:
Project Url: http://somehost:8080/tfs/DefaultCollection/MyProject
Build definition name (all if left empty): §leave empty§
Rest Api Token: §your token§

**Environment you encounter the issue:**
GitExtensions: 3.0RC1
TFS: TFS2017 on premise

**Workaround**
Enter build server data as followed:
Server Url: http://somehost:8080/tfs/DefaultCollection/
Team collection name: $leave empty$
Project name: MyProject
Build definition name (all if left empty): $leave empty$
Rest Api Token: §your token$

**Did this work in previous version of GitExtensions (which)?**
As far as I know that feature is not available in Version 2.x

**Comment by RussKie** [comment]
Are you in a position to send a PR with a fix?

**Comment by RussKie** [comment]
I don't use TFS/VSTS/ADO, and I don't think any of the core team members use them either (purely based on a fact that this issue hasn't been raised earlier).

If you think a UI change is the simplest and the most user-friendly way to achieve the goal - that is to connect to TFS - I have no problems with it.

IIRC @pmiossec has sent few PRs for TFS-related issues (relatively) recently. Philippe - any opinions?

**Comment by pmiossec** [comment]
>Part of the server URL (in this case "tfs") is disregarded, when the server url misses a trailing slash

Indeed, I verified, there is a bug in https://github.com/gitextensions/gitextensions/blob/master/Plugins/BuildServerIntegration/VstsAndTfsIntegration/TfsApiHelper.cs#L38 where a missing ending '/' is not handled.

>The plugin completely ignores any input into the team collection name field

Yes, I was just able to use it with VSTS and have not TFS on premise to test it. But looking at the code, that seems good. Perhaps also a bug 😢 

>I could do a fix, but first I would like to discuss which of the possible routes I should go. From a users perspective I would prefer the UI change (with a little trailing slash fix in the plugin).

So do I. what makes the configuration easier is good to take. What is here is a first version before I lost motivation to improve it much 😉 

> but I don't know the GE codebase well enough to be aware of all possible consequences. 

The code is pretty isolated so there will be very few consequences, so go, do it.
In the end,that should just still handle AzureDevops (and VSTS?) and TFS on premise >=2015.

>Especially (breaking) changes to GitExtensions settings.

This extension is still not released (will be only with v3), so consider that you don't have to handle backward compatibility because beta testers that use it on their own risk should be able to fix there settings...

PS: This extension need updates since the rebranding by Microsoft of VSTS as 'Azure Devops' (there are new git repositories urls https://github.com/gitextensions/gitextensions/blob/master/Plugins/BuildServerIntegration/VstsAndTfsIntegration/Settings/VstsAndTfsSettingsUserControl.cs#L20)

In the current version, I extracted the required data from the git repository remotes (but only for VSTS).
Perhaps what should be done is to handle TFS on premise urls.

What could also be done is what I did on TeamCity support, to extract the data from the build page url copied in the clipboard: 
![image](https://user-images.githubusercontent.com/460196/48481080-97460480-e80c-11e8-964c-35a0ff13bc3b.png)

I think these 2 things would be more user friendly...

I will be happy to test your PR on the VSTS (Azure Devops) builds I use...

**Comment by Noguai** [comment]
Alright, then I'll do the UI change. 

> In the current version, I extracted the required data from the git repository remotes (but only for VSTS).
> Perhaps what should be done is to handle TFS on premise urls.

I'll definitely extend that for Azure DevOps, but for TFS I would restrict the detection to Projects sitting in the DefaultCollection (default configuration of TFS), as otherwise there is pretty much nothing left to identify a TFS link other than maybe the "_git" segment which is not very unique on it's own.

>What could also be done is what I did on TeamCity support, to extract the data from the build page url copied in the clipboard:

That's a great idea, but there is a little catch, that can make the experience less seamless: The build url does not contain the build definition name, only a build id which forces me to make an api request. But that is only possible after an API token has been supplied, to which GitExtensions can guide the user only after a project url has been set.

I would implement it that way, that the link would fill both project url and build definition filter, if an api key exists and only the project url if not. That way the user can get at least some assistence, when the project url can not be derived from the url of a remote.


That url conversion and parsing sounds by the way like a perfect candidate for unit tests, for which i didn't find any for any build server integration plugin yet. @RussKie are there any special things to look for and do, when adding a new unit test project? Just asking, as I haven't seen the way GitExtensions copies plugins over to the plugin folder before and that custom msbuild target still looks a little magical to me. And still I always have to hit rebuild all, when doing changes to the plugin...

**Comment by RussKie** [comment]
> any special things to look for and do, when adding a new unit test project,

We have tests for few plugins, please have a look under \UnitTests\Plugins\.
I don't believe there is anything special - create a test project and it will be picked up automatically. If you wish, you can follow how `ReleaseNotesGeneratorTests` is setup.

The convention is that test projects have `Tests` suffix, all tests and leave under matching folder structure as the code they test.

Shout if you get stuck.

> And still I always have to hit rebuild all, when doing changes to the plugin...

Yes, that is a bit annoying but the app is assembled at the compile time. GitExtensions project is a bootstrap, so it needs all assemblies copied over. Try rebuilding just GitExtensions project, see if that helps.
If you have Re#, I suggest you turn "Re# Build" option as it saves build time significantly.

**Comment by Noguai** [comment]
Thanks, I'll just copy the `ReleaseNotesGeneratorTests` project then and strip out it's tests to insert my own.

> If you have Re#, I suggest you turn "Re# Build" option as it saves build time significantly.

Only at work and not on my private machine, as my time as a CS student is unfortunately over. 😔 I tried R# Build at work when it came out and couldn't notice a significant difference (noticeable, but not huge) but instead sometimes had the issue where single projects were not rebuild correctly when they should have been. But I guess I am drifting a litte too much into off-topic now...

**Comment by vbjay** [comment]
Just don't copy the project file.  Need to create a new project.

**Comment by RussKie** [comment]
> Just don't copy the project file. Need to create a new project.

Not that you necessary should, but you can, though you'll need to change bunch of guids and literals across several files.

**Comment by Noguai** [comment]
It's actually not that bad and faster than clicking through all those dialogs. There are just two files to change and almost everything can be done by simple search and replace. And I don't need to verify that I installed all necessary NuGet packages in the right version. 😁

**Comment by vbjay** [comment]
>And I don't need to verify that I installed all necessary NuGet packages
in the right version.

That's just a simple copy of the refs in the other project you are copying
from.
