### ISSUE TITLE
ROT remains blank when spamming refresh toolbar button

### ISSUE THREAD

**Issue by amaiorano** [gitextensions/gitextensions#5778]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you spam the Refresh toolbar button, after a while, the ROT (left panel) will remain blank.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Open a repo
* Start spamming the refresh button; maybe after 10 times or so, the ROT will remain blank.

**What is the expected behavior?**
The ROT refreshes and shows its nodes.

**Environment you encounter the issue:**
- GitExtensions version: 3.0 RC2

**Did this work in previous version of GitExtensions (which)?**
Not happening on 3.0 beta 1

**Comment by RussKie** [comment]
I have noticed it yesterday too... though I couldn't reproduce it

**Comment by RussKie** [comment]
Are you in a position to bisect/debug it?

**Comment by amaiorano** [comment]
Am pretty sure it's this change: cd68a511068cd2c0095793d27b2f4c50efb955a6

I saw this happen before. The BeginUpdate in the 'try' doesn't get its matching EndUpdate in the finally when an exception gets thrown. I will try reverting this commit and testing again. Standby.
