### ISSUE TITLE
ToroiseSVN/GIT bug tracking plug-ins support

### ISSUE THREAD

**Issue by KindDragon** [gitextensions/gitextensions#578]
Please support ToroiseSVN/GIT bug tracking plug-ins.

TortoiseSVN article http://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-dug-bugtracker.html
IBugtraqProvider/IBugtraqProvider2 interface http://tortoisesvn.net/docs/release/TortoiseSVN_en/tsvn-ibugtraqprovider.html

**Comment by AntaeusNar** [comment]
Bumping this, I am loving everything that is Git Extensions, but it would be really great to have an issue/bug tracker integrated.

**Comment by RussKie** [comment]
This is what **Revision links** are for
![image](https://user-images.githubusercontent.com/4403806/41786254-6503be18-7688-11e8-8b64-85e492a81f25.png)

![image](https://user-images.githubusercontent.com/4403806/41786140-08bedbe2-7688-11e8-938f-430a96aea760.png)
