### ISSUE TITLE
Bug: Console tab setting requires restart

### ISSUE THREAD

**Issue by MattLichter** [gitextensions/gitextensions#5787]
A very minor, benign bug.  Doesn't bother me at all, but just mentioning it because it's a release candidate and I expect you probably want to know these things.

- Git Extensions 3.00.a1
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa 
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3221.0
- DPI X:100.00% Y:100.00%

When I tick the "Show the Console tab" checkbox in the settings dialog, the result of my choice doesn't take effect until I restart GitExtensions.  I'm not sure if that's the expected behavior since this is a new feature in version 3 AFAIK.

![image](https://user-images.githubusercontent.com/8321199/48632584-4ca0c580-e98f-11e8-9144-c779655777cc.png)

**Comment by vbjay** [comment]
We have a few settings that are restart required.  This is known.

**Comment by drewnoakes** [comment]
Perhaps the comment "A restart is needed..." should move to the outer group box until fixed.
