### ISSUE TITLE
Can not reset some symlinked files

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#5789]
**Do you want to request a *feature* or report a *bug*?**
BUG.

**What is the current behavior?**
Can not reset some symlinked files.
They are always in shown as changed.
Like 
/etc/alternatives/aptitude 
or 
/etc/php/7.0/apache2/conf.d/20-gd.ini
I reset them with Reset file or directory changes, but they are always shown as changed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Should reset symlinked files.

**Environment you encounter the issue:**

- GitExtensions version: v2.51.05
- GIT version: v2.19.1.windows.1
- OS version: WIndows 7 Pro
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**
Don't know.

![20181116 19_11_29-commit to master - etc](https://user-images.githubusercontent.com/11757244/48639345-98755e00-e9d3-11e8-8825-0a01f9a7a189.png)

**Comment by klorinczi** [comment]
SOLUTION: 
1) Reinstalled Git for Windows with symlink feature turned OFF.
2) Used the following command in the local repo in Windows to disable symlink usage: 
`git config core.symlinks false`

**Comment by RussKie** [comment]
Thank you for sharing.
