### ISSUE TITLE
PluginSettings key names

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#5797]
**Do you want to request a *feature* or report a *bug*?**
Bug  related: #5793
**What is the current behavior?**
Plugin settings are stored with keys like this

```xml
<item>
    <key>
      <string>Periodic background fetchArguments of git command to run</string>
    </key>
    <value>
      <string>fetch --all</string>
    </value>
  </item>
```
The issue is someone could develop a plugin and name their plugin the same as another plugin that we don't know even exists. 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Use a unique value per plugin for the settings.  

I recommend each plugin use a guid that NEVER changes to retrieve its settings.  

```xml
<item>
    <key>
      <string>2ec6be62-d9e2-4b2b-a06b-e037b580e201_Arguments of git command to run</string>
    </key>
    <value>
      <string>fetch --all</string>
    </value>
  </item> 
```
**Environment you encounter the issue:**

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3221.0
- DPI X:100.00 % Y:100.00 %
**Did this work in previous version of GitExtensions (which)?**

**Comment by vbjay** [comment]
If needed, we can write the plugin ID and names so users can see that 2ec6be62-d9e2-4b2b-a06b-e037b580e201 or whatever the guid may be and a plugin name so it won't be hard finding out which settings are matched to which plugin and a human can match plugins and their settings if they are looking at the file.

**Comment by RussKie** [comment]
Ideally each plugin stores its settings in own config, this way there are less issues with name clashes of all kinds.
The name of the config can be plugin name + its hash/guid.

**Comment by RussKie** [comment]
Agree to a point, if a user needs to search for a settings file, it is easier to do if the file has a meaningful name. If you have a directory with several guid-named files, it is a difficult task finding the right one...

**Comment by vbjay** [comment]
They will have a key in the settings file. See sample xml above.

**Comment by pmiossec** [comment]
>Bug related: #5793

To be exact, the problem is that for continuous integration plugins, the settings are stored like that:

```xml
  <item>
    <key>
      <string>BuildServer.Azure DevOps and Team Foundation Server (since TFS2015).ProjectUrl</string>
    </key>
    <value>
      <string>https://taliance.visualstudio.com/Taliance</string>
    </value>
  </item>
```

Where the middle part (between the dots) is taken from the plugin name that is also used as a label in the settings dropdown.

If I have to choose, I will take as a plugin id, a human readable string that the developer must specify (and that should never change) instead of a GUID...

Dissociating the plugin name and id is enough for me...

**Comment by vbjay** [comment]
The guid is the correct type. It fits the need.  Like I said we can put the
name in too but the KEY of the setting should not be a name.

**Comment by RussKie** [comment]
I agree with the guid in this case.
