### ISSUE TITLE
Showing "Notes" in FormFileHistory and FormCommitDiff commit info when there are none

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5804]
**Do you want to request a *feature* or report a *bug*?**

UX bug.

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/350947/48913917-c6462100-ee71-11e8-8c82-07d910a678f0.png)

Double click a commit.

Notice there is a "Notes:" header even though the commit has no notes.

**Environment you encounter the issue:**

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI X:150.00% Y:150.00%

**Comment by gerhardol** [comment]
I do not see this in the release version, not sure what was changed.
See also #5653
