### ISSUE TITLE
Ability to prune remote directly from object tree

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5805]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/350947/48938865-60f23e80-ef0a-11e8-9975-db2d3b33a963.png)

![image](https://user-images.githubusercontent.com/350947/48938989-c0e8e500-ef0a-11e8-9b3c-c986ea047d17.png)

**What is the expected behavior?**

I'd like:

- [ ] a context menu option on a remote to prune it
- [ ] a context menu option on the "Remotes" node to prune all remotes
- [ ] a context menu option on the "Removes" node to fetch from all remotes

**Environment you encounter the issue:**

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI X:150.00% Y:150.00%

**Comment by amaiorano** [comment]
I'm fairly comfortable now with ROT, so I can take this at some point in the future.

**Comment by drewnoakes** [comment]
That'd be great.

**Comment by RussKie** [comment]
decided to join us yet? :D

**Comment by amaiorano** [comment]
Once #6073 is merged, I'll start working on this.

**Comment by RussKie** [comment]
I believe this is done.
