### ISSUE TITLE
Invalid SplitterDistance

### ISSUE THREAD

**Issue by LeeARichardson** [gitextensions/gitextensions#5806]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Throws on load and dies.
```
System.ArgumentOutOfRangeException: 'Value of '-9' is not valid for 'SplitterDistance'. 'SplitterDistance' must be greater than 0.
Parameter name: SplitterDistance'
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Start program. 

Not sure why this happens to me but hasn't been reported by anyone else yet.
The code for this is:
https://github.com/gitextensions/gitextensions/blob/1a258a2826a19d3139ff219a23318b7c1cfdc7a7/GitUI/CommandsDialogs/FormBrowse.cs#L3015

Where in my case `RevisionsSplitContainer.Width` = 498 and `width` = 507 resulting in the -9.

**What is the expected behavior?**
Not dying on load.

**Environment you encounter the issue:**

- Git Extensions 3.00.rc2
- Build 5cea7d454a5e3e4fb02f2721370aa2c1871f85cf
- Git 2.17.1.windows.2
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.2558.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Yes, 2.51.05

I'm not familiar enough with the code to know if there's a wider problem, but throwing a `Math.Max(0 ...` on there will sort it out. I have a branch ready if you want it.

**Comment by LeeARichardson** [comment]
By the way, if you want my PR with the simple Math.Max, could someone point me in the right direction for unit testing? I don't see any other tests for that object.

**Comment by RussKie** [comment]
A PR is welcome.
I suspect we don't have UT for this object.
