### ISSUE TITLE
GPG Commit form regression

### ISSUE THREAD

**Issue by gpongelli** [gitextensions/gitextensions#5807]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
Feature added in #4390 is disappear

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. enable GPG into settings (maybe not useful)
2. open commit window
3. Open the commit options menu 

![immagine](https://user-images.githubusercontent.com/842026/48948735-e808dc00-ef35-11e8-8cfe-ef810f199589.png)

**What is the expected behavior?**
As in referenced and merged PR, there should be the capability to choose the private key to sign the commit.
Actually there's no way to sign a commit.

**Environment you encounter the issue:**
- GitExtensions version: 2.51.05
- GIT version:  2.18.0
- OS version: Windows 10
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**
Yes.

**Comment by gpongelli** [comment]
For sake of completeness, v 3.00.rc2 from latest master commit has the capability to sign commits

![immagine](https://user-images.githubusercontent.com/842026/48950440-6d42bf80-ef3b-11e8-972c-80889b612e47.png)

**Comment by vbjay** [comment]
Most people set up signing in git config.

https://prezi.com/view/pHprUqzvjrsTxLBt4zfF

No matter which client, git will sign using the selected key. If you have a
different key for a repo then run a git config to set the right key. The
global config keeps the program path and the commit signing config.

**Comment by vbjay** [comment]
Sorry. Couldn't resist

In other words, when you choose to use git signing, you commit to using it.

**Comment by vbjay** [comment]
Our readme defines what the difference is. 2.51 and master have diverged.
We only provide bug fixes to 2.51.

**Comment by vbjay** [comment]
On another note, I raised an issue to support git signing config in settings.

**Comment by RussKie** [comment]
v3 is to be released shortly, we aren't going to fix v2.51.
