### ISSUE TITLE
Cannot fetch GitHub pull requests

### ISSUE THREAD

**Issue by apobekiaris** [gitextensions/gitextensions#5809]
I get this when I try any of the fetch PullRequest buttons

>unable to look up github.com (port 9418) (Either the application has not called WSAStartup, or WSAStartup failed. )

I am on Windows 10 latest version

**Comment by vbjay** [comment]
We have a n issue template for a reason.

**Comment by RussKie** [comment]
Please fill the report as per the template, otherwise it will get closed.

**Comment by gerhardol** [comment]
Issue in git 2.19.2 with links with git: pre fixes. I would expect a new vet ion to be released soon

**Comment by TamaHobbit** [comment]
This issue has nothing to do with GitExtensions. It was an issue in Git for windows 2.19.2 which I also reproduced, and which can be fixed by installing the [2.20 prerelease version](https://github.com/git-for-windows/git/releases/tag/v2.20.0-rc1.windows.1). I'd recommend to close this issue.
