### ISSUE TITLE
Commit graph: strange resize of the description column when selecting lines with mouse click

### ISSUE THREAD

**Issue by francoas** [gitextensions/gitextensions#5811]
**Do you want to request a *feature* or report a *bug*?**

bug 

**What is the current behavior?**

When I mouse-click-select commits lines in the graph window  
sometimes the commit description column unexpectedly shrinks

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See the attached video

**Environment you encounter the issue:**

- GitExtensions version:

3.x

- OS version: 

Windows 8.x

[gitex.zip](https://github.com/gitextensions/gitextensions/files/2616170/gitex.zip)

**Comment by vbjay** [comment]
We have an easy way to get the environment info into the template from Help-> About
![image](https://user-images.githubusercontent.com/3629489/49034900-3958db80-f181-11e8-9ce5-fe94fad79f02.png)

**Comment by spdr870** [comment]
I pushed a possible fix to #5821. Could you test if this fixes it? I can simulate the issue, but not sure if all situations are covered.

**Comment by francoas** [comment]
It works for me. Thanks

**Comment by spdr870** [comment]
Closed by #5821
