### ISSUE TITLE
Exception showing combined diff on merge commit

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#5815]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Double clicking a merge commit in the grid, then click the entry for 'combined diff'. The right hand side is populated with a stack trace:

```text
Unsupported file: 

System.ArgumentOutOfRangeException: CombinedDiff artificial commit cannot be explicitly compared: 3333333333333333333333333333333333333333, 16825d36221ab278d265ca4e2293a439074e14ba
Parameter name: firstRevision
Actual value was 3333333333333333333333333333333333333333.
   at GitCommands.Git.RevisionDiffProvider.GetInternal(String firstRevision, String secondRevision, String fileName, String oldFileName, Boolean isTracked)
   at GitCommands.GitModule.GetSingleDiff(String firstRevision, String secondRevision, String fileName, String oldFileName, String extraDiffArguments, Encoding encoding, Boolean cacheResult, Boolean isTracked)
   at GitUI.GitUIExtensions.GetItemPatch(GitModule module, GitItemStatus file, ObjectId firstRevision, ObjectId secondRevision, String diffArgs, Encoding encoding)
   at GitUI.GitUIExtensions.GetSelectedPatch(FileViewer diffViewer, ObjectId firstRevision, ObjectId secondRevision, GitItemStatus file)
   at GitUI.GitUIExtensions.<>c__DisplayClass3_0.<ViewChangesAsync>b__0()
   at GitCommands.AsyncLoader.<>c__DisplayClass11_0`1.<LoadAsync>b__0(CancellationToken token)
   at GitCommands.AsyncLoader.<LoadAsync>d__12`1.MoveNext()
```

This seems to happen for every merge commit. I just tested on 16825d36221ab278d265ca4e2293a439074e14ba and it happened:

![image](https://user-images.githubusercontent.com/350947/49052240-e283ee00-f1e2-11e8-9e16-9de72c5717f9.png)

**Environment you encounter the issue:**

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI X:150.00% Y:150.00%

**Did this work in previous version of GitExtensions (which)?**

Don't know.

**Comment by drewnoakes** [comment]
I can't reproduce this in 7931098b5468ff0bae5abed2767f47c11435c921. I think it must have been fixed.

**Comment by drewnoakes** [comment]
Actually yes I can. It only occurs in the diff form.

**Comment by drewnoakes** [comment]
`CommitDiff`'s `ViewSelectedDiffAsync` doesn't use the special handling for combined diffs that's in `RevisionDiffControl.ShowSelectedFileDiffAsync`.

**Comment by RussKie** [comment]
I'd like to revisit the whole "view" sequence, it is awfully complicated
with layers upon layers upon layers...

**Comment by KriNiTo** [comment]
Having the same issue with version 3.0.2.5232:

CombinedDiff artificial commit cannot be explicitly compared: 3333333333333333333333333333333333333333, 2297f674b4926dd2bbbe7abad4ec5a510b2e33f8
Parameter name: firstRevision
Actual value was 3333333333333333333333333333333333333333.

**Comment by RussKie** [comment]
@KriNiTo can you please provide steps to reproduce

**Comment by KriNiTo** [comment]
Sure. Steps to reproduce:
1) select a merge-commit in commit-browser-window
1) in "Diff"-Tab navigate to "Combined Diff" and select an file
1) press F3-key (starts normally KDiff3 and shows diff there)
1) Exception-Window with "ArgumentOutOfRangeException ...CombinedDiff artificial commit cannot be explicitly compared..." appears

F3-key (and KDiff3) are working in any other sections (Diff with: "...") with any files.

**Comment by gerhardol** [comment]
Try fb13fb2eb632ba4d6755bb4fea8c743863d229d1 to see the problem

The issue in the Diff-tab is new but similar
In DiffForm, the simple solution is to implement the same handling as in the DiffTab

Note: DiffForm do not have an option to view the diff in a GUI, should be added.

**Comment by bjarnesvanberg** [comment]
I see that a fix is on it's way from @gerhardol but will share this just as additional info; I see the same problem when viewing the combined diff of a stash in the Diff form. I open the diff form by double clicking on the line with the stash label. 
![Image 137](https://user-images.githubusercontent.com/7126217/55147973-a7210e00-5147-11e9-910e-c6e452793d1b.png)
