### ISSUE TITLE
v3 RC2 - branch list does not update if branch is added and changed outside of Git Extensions

### ISSUE THREAD

**Issue by mika76** [gitextensions/gitextensions#5827]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Branch List on left is blank and does not refresh when clicking the refresh button - stays blank

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I had git extensions open and Visual Studio open. In VS I created a new branch and checked it out. I then moved to the git extensions window and clicked the refresh button - only the log refreshed - the branch list on the left went blank and did not refresh any more. Closing the windows and opening again worked.

**What is the expected behavior?**
The list should update with current branch state

**Environment you encounter the issue:**
Windows 10 - Git Extensions 3 RC 2

- GitExtensions version: 3 RC 2
- GIT version: 2.18.0
- OS version: Windows 10
- .NET version: 4.7.3190

**Did this work in previous version of GitExtensions (which)?**
Branch list didn't exist in previous v2 git extensions and I never tried a previous RC or beta of 3

**Comment by amaiorano** [comment]
This was fixed after RC 2: https://github.com/gitextensions/gitextensions/commit/5a9522372084871077c04104f1b91f5274f2f517
