### ISSUE TITLE
UI performance on Version 3.00.00 RC2 is very slow

### ISSUE THREAD

**Issue by RupertAvery** [gitextensions/gitextensions#5836]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

General UI interaction is very slow.  

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

For example, clicking on Start > Recent Repositories takes 5 seconds, then causes the mouse to turn into a spinner for two seconds before actually displaying the recent files. Refreshing the view (F5) causes a spinner to show up for 5-6 seconds, application says Not Responding in the title bar for 2 seconds, then the view refreshes.

**What is the expected behavior?**

UI interactions for even simple Recent repositories should not take 7 seconds and cause the application to temporarily not respond.

I first uninstalled my current version, EbenZhangs GitExtensions Mod then installed 3 RC2 using the MSI. I noticed it was slow, so I tried uninstalling and reinstalled the Mod version.

To test it again, running Version 3.00.00 RC2 portable and EbenZhangs GitExtensions Mod side-by-side the differences are very noticeable.

**Environment you encounter the issue:**

- GitExtensions version:   Version 3.00.00 RC2
- GIT version: 2.17.1.windows.2
- OS version: Windows 10
- .NET version: 4.5.2

Machine specs:
Intel Core i5-7440HQ @ 2.80 GHz
32GB RAM

**Did this work in previous version of GitExtensions (which)?**

I am currently using EbenZhangs GitExtensions (Mod) 2.51

**Comment by spdr870** [comment]
I never experienced this, but is this issue simular to #5829?

**Comment by spdr870** [comment]
I did some profiling, but since I cannot simulate this I need some help. Could you try to disable this option and try again?
![image](https://user-images.githubusercontent.com/38675/49337863-6cd0b580-f61a-11e8-92c7-798c523f0c91.png)

**Comment by amaiorano** [comment]
@RupertAvery just to know, does your repository have a significant number of submodules (and/or recursive submodules)? @gerhardol has been working on performance problems related to submodules, specifically when opening repositories (see #5747 and #5777).

**Comment by mdonatas** [comment]
@RupertAvery do you have any repositories from network shares? I've noticed that querying those takes quite some time depending on host resolution, etc

**Comment by drewnoakes** [comment]
We shouldn't be doing slow IO on the UI thread.

The ideal would be to reproduce this in a debugger. @RupertAvery if you're familiar with .NET, are you able to launch `master` in Visual Studio and debug this?

**Comment by gerhardol** [comment]
Submodule status is disabled by default in 3.0. If many modules, the behavior can be like this.
(Work on improving the performance will start when 3.0 has been released.)

**Comment by RussKie** [comment]
I have the exactly same problem in this version:
```
- Git Extensions 3.00.00.4340Dev@aebb0
- Build aebb024313284d64993ffc747cdad4e47c7b29fa (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3163.0
- DPI 144dpi (150% scaling)
```

Start the app, click on a "change repo" dropdown, observe the hang...

![image](https://user-images.githubusercontent.com/4403806/49404505-bc8eb880-f7a3-11e8-8326-668bd5496118.png)

**Comment by RussKie** [comment]
It's somewhat hard to get a good snapshot...

This seems to come consistently:
![image](https://user-images.githubusercontent.com/4403806/49439198-81789d80-f814-11e8-87b0-765345b24572.png)

**Comment by RussKie** [comment]
Here's another one
![image](https://user-images.githubusercontent.com/4403806/49441648-5180c880-f81b-11e8-828e-e840407c4cb6.png)

**Comment by RussKie** [comment]
Actually I've just realised the issue I'm observing is more #5829 than this one... apologies

**Comment by RupertAvery** [comment]
Yes I'm familiar with .NET, I could try to repro it. This is just a local repository, no submodules. As I mentioned, just attempting to show recent repositories took  an astonishing (well, annoying) 7 seconds to load. I have not tried it after rebooting, I was just so shocked that I uninstalled and went back to my old version, which was fine. I tried the "portable" version 3.00 immediately after seeing that my old version was working just to make sure it wasn't a fluke,and it was still slow.

That said I haven"t tried it again but will do so soon.

**Comment by RupertAvery** [comment]
Seems like the slowdown is occuring in `RecentRepoSplitter.SplitRecentRepos` in this loop:

```
foreach (Repository repository in recentRepositories)
```

I actually do have network repositories in my recent list.

**Comment by RupertAvery** [comment]
So it looks like EbenZhangs latest code also has this issue.

**Comment by mdonatas** [comment]
I couldn't repro this in my build because I exclude all repo paths starting with `\\` for quite some time now 😂

**Comment by mdonatas** [comment]
Tried googling for a solution but it's either sockets or doing the check in a separate thread and aborting the operation if a timeout is reached. Really weird that there are no async options for network paths.

**Comment by RupertAvery** [comment]
Is it really that important to get the case-correct path names for recent files? Case doesn't matter in windows. Equally weird as that refreshing the recent files with what the user expects to be just the current repository tree.

**Comment by RussKie** [comment]
This code was written to support Linux where casing matters.

**Comment by amaiorano** [comment]
I think a good solution that I've seen before is not to bother checking that the recent paths are valid at all. Just list them. And when the user tries to open one, we can check if it exists then, and if it doesn't, ask the user if they want us to remove it.

**Comment by RupertAvery** [comment]
I'll throw in a PR
