### ISSUE TITLE
How to Git Extesnions with Visual studio 2013, 2010, 2012

### ISSUE THREAD

**Issue by Prash45** [gitextensions/gitextensions#5845]
Hi,

I have installed Git Extensions 2.51.05 on my PC. I was able to integrate git extension with visual studio using the plugin from https://marketplace.visualstudio.com/items?itemName=HenkWesthuis.GitExtensions . After installing VSIX file, I can see Git Ext button view in VS 2015, 2017. But how I can use git extensions with VS 2010,12,13? While downloading the installer it says it has addin for them but I don't how can I integrate git extensions with VS 2013,12,10.

Also, When I have installed Git Extensions 2.51.05, kDiff wasn't installed with it. Not sure why?

I appreciate everyone's input.

Thank you

**Comment by vbjay** [comment]
Did you check to see if the menu is able to be added?  Also try running
devenv /setup to get vs to reprocess addins.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/49394183-37eb5e00-f701-11e8-98eb-9bd22255e83f.png)
See if it shows up in 2013 or earlier.

**Comment by Prash45** [comment]
@vbjay 

While installing Git Extensions, I have checked integrations for VS 2010,12,13 . I don't see any menu button for Git Ext for Visual studio 2013.

**Comment by vbjay** [comment]
Did you try running devenv /setup?  Open developer command prompt for the
correct vs version.  run devenv /setup.  Then open visual studio same
version.

**Comment by drewnoakes** [comment]
@Prash45 the VSIX you linked to only supports VS2015 and VS2017.

You may be able to find an older GE version that supports earlier VS versions, but I don't know where to point you towards, sorry.

**Comment by RussKie** [comment]
> The addin is included in the GE installer

I don't believe it is. IIRC we have switched to VS 2015/17 vsix about a year ago and no longer build or ship VS 2010/12/13 addin.
We could extract the addin from one of the old installers and publish it on its own. Or @Prash45 you could build it from source from one of the old release branches.

**Comment by Prash45** [comment]
@drewnoakes @gerhardol @RussKie 

What should be the solution for me now? Our organization was looking for good git client, I have recommended Git Extensions. Now it seems they are limitations. I was expected KDiff as well in the installer itself, which is not available now. 

I am okay to download KDiff separately , But I want to make sure Git Extensions work with VS 2010, 2012, 2013 to recommend and start using the GUI client,

Please direct me.  I appreciate everyone's input

Thank you

**Comment by gerhardol** [comment]
The addin for older VS is included with the 2.51 installer. 
It is removed in 3.00 though

(Building GE itself requires 2017 for master and 2015/2017 for 2.x)

**Comment by RussKie** [comment]
> What should be the solution for me now? Our organization was looking for good git client, I have recommended Git Extensions. Now it seems there are limitations with the client. I was expecting KDiff as well in the installer itself, which is not available now

You and your team can use GE, it is a stand alone app. 
VS integration is a separate component, which is shipped along with the app, however it is not required.

You can extract the addin from one of the older releases. We will publish it on a VS market place or here in coming weeks.


> I am okay to download KDiff separately

Previously we used to bundle a number of dependencies and ship them as part of the installer, however more often then not we would do a disservice to our users - our release cadence is far slower than some of our dependencies (e.g. git).
Now users need to download and install the required software themselves. [Chocolatey](https://chocolatey.org/) is a good way of getting the software installed. 
Please see #5481 for a related discussion.

**Comment by RussKie** [comment]
[Visual Studio 2010 Addin.zip](https://github.com/gitextensions/gitextensions/files/2646204/Visual.Studio.2010.Addin.zip)
[Visual Studio 2012 Addin.zip](https://github.com/gitextensions/gitextensions/files/2646205/Visual.Studio.2012.Addin.zip)
[Visual Studio 2013 Addin.zip](https://github.com/gitextensions/gitextensions/files/2646203/Visual.Studio.2013.Addin.zip)

**Comment by Prash45** [comment]
Thank you all

**Comment by GitNinja777** [comment]
@
