### ISSUE TITLE
"Reset unstaged files" with "deleted added files" should not delete ignored files by default

### ISSUE THREAD

**Issue by johndog** [gitextensions/gitextensions#5849]
Probably a bug.  Other issues like #2204 suggest that ignored files were only deleted if the filter was changed to include them.

**What is the current behavior?**

1. Go to Commit UI with some unstaged changes
2. Click "Reset unstaged changes"
3. Click the checkbox to delete added files, then OK

Result:  "git reset -f -d -x" is run, with -x indicating that ignored files should be deleted.
Expect:  Don't include -x by default.

Environment:
- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.0.gvfs.1.34.gc7fb556
- Microsoft Windows NT 10.0.18290.0
- .NET Framework 4.8.3694.0
- DPI X:100.00% Y:100.00%

**Did this work in previous version of GitExtensions (which)?**
I believe we see the expected behavior in the release build of GitExtensions, this is the first RC build I've tried and the first time I've observed the behavior.

**Comment by gerhardol** [comment]
I do not expect this command to have changed since 2.51

Yes, git-clean -x is what is intended. Make the caption should be changed to "Also delete _untracked_ files and directories".

**Comment by johndog** [comment]
Untracked != ignored… ignored includes things like build artifacts, logs, and packages, which were added to the gitignore file.  Deleting those is not a common act.  Deleting untracked files IS common, though.

Sent from my Windows 10 device

________________________________

**Comment by MonkAlex** [comment]
So, how i know, who delete all my local configs

Good job =_=

**Comment by gerhardol** [comment]
Suggest text is changed to "Also delete ignored and untracked files and directories"

**Comment by vbjay** [comment]
We can do better. Create a dialog with check boxes for each option. Allow
the user to chose to delete which ones. Could even have a list of files
that will be affected when it is resset all changes/reset all unstaged vs
reset menu on selected files.

**Comment by johndog** [comment]
What Jay writes is what I thought at first, but changed my mind.

First principle:  No files should be deleted without the user first having opportunity to review them. Indeed, this is true of all permanent changes, not just deletions.

Proposal:  The feature should only permit deleting files visible in the staging UI.  It is already possible to change the view to display ignored files. ONLY if the user has done so should the message box offer to delete ignored files.

By default, it should only offer to delete untracked files.

Supporting observations:

1 - Deleting ignored files is a much lower frequency scenario (a claim based on intuition, not data), so there is no need to make it as easy to delete ignored files as it should be to delete untracked ones.
2 - File deletion is permanent.  If this property is coupled with hidden behavior, it becomes an easy opportunity to shoot one’s self in the foot.


________________________________

**Comment by vbjay** [comment]
git clean [options](https://git-scm.com/docs/git-clean#_options).  What we need is to run ```git clean -d``` if new files check box is checked.  Add another checkbox that asks about ignored files.  In the dialog add a listbox or listview that uses git clean with the -n option to list the files that would be cleaned along with what reset would do.  

2 cases:

1. User hits one of the reset ... changes buttons.  This case ignores file selection.  Dialog comes up with the new/untracked files and ignore checkboxes.  ```git clean -n is run and we union what git reset would reset.  If only unstaged files, we filter to exclude staged changes.  

2.  User selects files and hits r or right clicks selected files and .  We use -- option to only clean/reset specific files.  We still do what 1 would do but we only include files that were selected so if you didn't show ignored files and selected 2 files, the ignored files checkbox would not be checked and it would be disabled.  If no untracked files were selected then uncheck untracked files and disable it.  

Always include -f in clean arguments.  We update the list when user changes checkboxes.

**Comment by gerhardol** [comment]
The intention with this command was likely to only delete the not ignored files, this is why this option is grayed out if there are no untracked (not ignored files). The arguments are slightly conflicting.

I will submit a PR to only delete non ignored files.

A second step would be to add a second checkbox for ignored files too.
Compare to the clean catalog that has tree options: nonignored, ignored, nonignored+ignored. This dialog could be changed for consistency (but 'none' makes no sense here).

**Comment by vbjay** [comment]
None does make sense.  It woukld just be a git reset and no clean.

**Comment by vbjay** [comment]
Related: #5937

**Comment by johndog** [comment]
Is there a pointer somewhere to current builds of head of master ?

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/50610565-6e9fca00-0ea1-11e9-8076-a01116e32a80.png) Canary in readme.
