### ISSUE TITLE
Branch drop-down only shows first 100 branches

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#5850]
**Do you want to request a *feature* or report a *bug*?**

I consider this a bug.

**What is the current behavior?**

When you have more than 100 branches in a repo, the branch drop-down only shows the first 100.

And before someone says "_...but you shouldn't need to have that many branches_"... as I've said before in earlier issues, I work on a lot of open source projects and things don't always get merged quickly.

There is one repo, for example, where I currently have ~ 50 open PRs, some 10 branches which I cannot yet pull because they would cause merge conflicts with open PRs, some 10 WIP branches waiting on feedback on a question I asked (not yet pulled), and then 30 WIP/test branches.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Create a repo.
2. Create 101 different branches.
3. Scroll down the branch and note that you can't get to branch 101.

**What is the expected behavior?**

That there is no limit to the number of branches which are listed in the branch drop-down.

**Environment you encounter the issue:**

- GitExtensions version: 2.51.05
- GIT version: 2.17.1.windows.2
- OS version: Windows 7
- .NET version: no idea and unfortunately the _Help->About Copy button or Help->Report an issue_ trick did not work

**Did this work in previous version of GitExtensions (which)?**
Didn't notice it not working, but not sure I reached the 100 branches in any of my repos yet.

**Comment by RussKie** [comment]
Sorry we're not going to do this. 

The dropdown in question is for **recent** branches. One can't have 100 **recent** branches. 
It appears you have 100 "open" branches, but they are not _recent_.
Arguably, even the 100 we show is a lot, in VS you're limited to 24:
![image](https://user-images.githubusercontent.com/4403806/49495470-2c419800-f8b7-11e8-8bd2-a9051c4ceaf6.png)


In v3 you could leverage the left panel and namespace your branches for the ease of discovery and access:
![image](https://user-images.githubusercontent.com/4403806/49496059-ff8e8000-f8b8-11e8-9ac4-136e9f415b37.png)

**Comment by RussKie** [comment]
> if you say it's about "recent" branches, then an arbitrary number like `100` makes no sense.

We had to pick an arbitrary number, so we did - 100. 
We could as well have picked 24 like Microsoft or 30 like Notepad++... 😄 

@gerhardol @amaiorano you have been looking at the left panel recently, do you know/remember whether the left panel has a limit on branches it displays?
