### ISSUE TITLE
Incorrect horizontal scrolling in Commit dialog

### ISSUE THREAD

**Issue by jasonsparc** [gitextensions/gitextensions#5857]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In the *commit* dialog, the horizontal scrolling range is incorrect (even the horizontal scrollbar is not displaying correctly), causing parts of a very long line to be inaccessible. See screenshots:

![capture](https://user-images.githubusercontent.com/2899129/49575741-675ace80-f97e-11e8-9c2a-459353e9a95f.PNG)

![capture2](https://user-images.githubusercontent.com/2899129/49575737-645fde00-f97e-11e8-9784-f0abb8251071.PNG)

You could see from above that the horizontal scrolling range is already maxed out and because of that, you wouldn't be able to access the parts that are clipped.

Right now, the only way to access the parts that are clipped is through the text cursor, and manually moving the text cursor via the arrow keys.

**Environment you encounter the issue:**

- GitExtensions version: 3.00.00.03-RC2
- Git version: Git 2.19.1.windows.1
- OS version: Microsoft Windows NT 10.0.17134.0
- .NET version: .NET Framework 4.7.3221.0
- DPI X:100.00% Y:100.00%

**Did this work in previous version of GitExtensions (which)?**
Yes, at GitExtensions 2.51.05

**Comment by spdr870** [comment]
Please test #5856

**Comment by spdr870** [comment]
Closing this issue. The fix from #5856 should fix this.
Builds are testable here:
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/20815713/artifacts
