### ISSUE TITLE
Focus branch in revision graph when clicking in left panel even if already selected

### ISSUE THREAD

**Issue by iTob191** [gitextensions/gitextensions#5869]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
If I select a branch (by left clicking) in the left panel, it's commit does automatically get focused in the revision graph. However, if I click a branch that is already selected, nothing happens.

**What is the expected behavior?**
When clicking a branch in the left panel, it's commit should automatically get focused in the revision graph even if that branch was already selected before.
For example if you go to a branch's revision by selecting it, then scrolling through the history a bit and later want to return to that branch's revision, you cannot simply click the branch again, but instead you have to select another branch first and then select the original branch.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Reasonable change

**Comment by mdonatas** [comment]
If someone wants to take a stab at this, here is a starting point https://gist.github.com/mdonatas/6ba01070c1df982b12282f3f1d5e29d5
The part which forces selected commit to scroll into view when it's already selected is hacky but that's a start.
