### ISSUE TITLE
Commit message is editable in the main UI

### ISSUE THREAD

**Issue by ulrichb** [gitextensions/gitextensions#5870]
**Do you want to request a *feature* or report a *bug*?**
Bug (Cosmetics)

**What is the current behavior?**

The commit message is editable in the main UI:

![image](https://user-images.githubusercontent.com/388796/49687768-255d9400-fb08-11e8-8bb8-2aad740213a7.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

See above screen.

**What is the expected behavior?**

Not editable.

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI 120dpi (125% scaling)

**Comment by vbjay** [comment]
LOL!  Good bug find.
