### ISSUE TITLE
System.FormatException in diff of submodule add / update

### ISSUE THREAD

**Issue by iTob191** [gitextensions/gitextensions#5873]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Screenshot in GE 3.00.00.4433:
![grafik](https://user-images.githubusercontent.com/8921465/49689470-053ace80-fb22-11e8-9ded-6ed00560a03a.png)
```
Unsupported file: 

System.FormatException: Unable to parse object ID "".
   bei GitUIPluginInterfaces.ObjectId.Parse(String s)
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei GitCommands.CommitDataManager.CreateFromFormattedData(String data)
   bei GitCommands.CommitDataManager.GetCommitData(String sha1, String& error)
   bei ResourceManager.LocalizationHelpers.ProcessSubmoduleStatus(GitModule module, GitSubmoduleStatus status)
   bei GitUI.GitUIExtensions.GetSelectedPatch(FileViewer diffViewer, ObjectId firstRevision, ObjectId secondRevision, GitItemStatus file)
   bei GitUI.GitUIExtensions.<>c__DisplayClass3_0.<ViewChangesAsync>b__0()
   bei GitCommands.AsyncLoader.<>c__DisplayClass11_0`1.<LoadAsync>b__0(CancellationToken token)
   bei GitCommands.AsyncLoader.<LoadAsync>d__12`1.MoveNext()
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Add or update a submodule and view the diff of the submodule folder either in the commit dialogue or in the diff tab of the revision history's details.

**What is the expected behavior?**
Screenshot in GE 2.51.05:
![grafik](https://user-images.githubusercontent.com/8921465/49689465-f18f6800-fb21-11e8-9d57-22fef46b4cb0.png)

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
2.51.05

**Comment by gerhardol** [comment]
This works for me. 
What commit do you select to see this, normal or artificial?
Do you have any specific settings that can explain this?
Can you post the output of the git command for which the parsing fails?
