### ISSUE TITLE
"Show superproject branches" doesn't work reliably

### ISSUE THREAD

**Issue by iTob191** [gitextensions/gitextensions#5874]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
- <details><summary>The super-project branch doesn't show up until I click the revision it points to.</summary><img src="https://user-images.githubusercontent.com/8921465/49691026-3e7f3880-fb3a-11e8-8141-26611bc928d3.gif"></details>
- <details><summary>If the revision that the super-project branch points to is selected initially, it doesn't show up until I select any other revision or click somewhere outside the revision history (e.g. on the commit details view or on the task bar).</summary><img src="https://user-images.githubusercontent.com/8921465/49691617-e438a480-fb46-11e8-8ddf-e1afe4762dfe.gif"></details>
- <details><summary>If I press refresh, the super-project branch shows up for a very short time, but is invisible again after the refresh has finished.</summary><img src="https://user-images.githubusercontent.com/8921465/49691591-72605b00-fb46-11e8-89f3-4219969cf183.gif"></details>
- If I select "View > Highlight selected branch (until refresh)" on a commit different than the super-project's revision, the super-project's revision shows up, too.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open GitExtensions in a repository that is submodule of another one. Also occurs after refreshing.

**What is the expected behavior?**
The super-project branch shows up without further interaction once loaded.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Even though it took a short time, the super-project branch showed up without further interaction in 2.51.05.

**View settings**
<details>
<summary>Not sure whether this is important, but here they are.</summary>
<img src="https://user-images.githubusercontent.com/8921465/49691564-940d1280-fb45-11e8-94cd-4d30a754a4a2.png" />
</details>

**Comment by pmiossec** [comment]
I think that it is, like #5653, a consequence of the optimization to display the revision grid where only the strict necessary data is loaded.

**Comment by gerhardol** [comment]
The information about remote branches is queried but not displayed.

**Comment by gerhardol** [comment]
I believe that there is a workaround:
If you wait a little and click in the graph, the remote should show eventually.

The remote references must be queried separately. If you have some remote repos, this can take a long time.
You can see this in the GitLog, when no more messages after refreshing, the loading is done.

In 2.x, the revision graph was updated when the information was available. 
In 3.0, the repainting of the cell is not done until there is another event to trigger the repainting.

Completing the info retrieval should retrigger the repainting, as in 2.x.

@drewnoakes How should this be done, when GetSuperprojectCheckout() is done (or rather where it is called in ForceRefreshRevisions()) the repainting should be triggered.

This should not be critical for 3.0.1.

**Comment by gerhardol** [comment]
Included in 3.0.1, though not in release notes

**Comment by RussKie** [comment]
Thank you, added to the GH release notes
