### ISSUE TITLE
Revision graph starts from the wrong point

### ISSUE THREAD

**Issue by HoaFox** [gitextensions/gitextensions#5880]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The revision graph starts from a wrong point. 
![wrong graph](https://user-images.githubusercontent.com/28867989/49757064-c6d91700-fcbb-11e8-8e88-69cacc1e04f5.jpg)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
We use for our git repositories the 'rebase and merge' strategy to get the nice bubbles where we can easily see where our feature branches are starting and ending. We have a hudge history now and with the new Git Extensions at some specific point the revision graph will not be drawn properly anymore.
Example for nice bubbles:
![nice bubbles](https://user-images.githubusercontent.com/28867989/49757463-c7be7880-fcbc-11e8-9913-24c9c3504f4f.jpg)

**What is the expected behavior?**
The revision graph should start from the correct point/commit. If we filter the branch then the revision graph will be drawn correctly.
![correct graph](https://user-images.githubusercontent.com/28867989/49757671-46b3b100-fcbd-11e8-8564-379e7cd253e2.jpg)

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.2.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3133.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Git Extensions 2.51.05

**Comment by spdr870** [comment]
I probably know what the issue is. But to confirm, could you try RC2 and see if the issue is there or not?
https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00-rc2

**Comment by HoaFox** [comment]
> I probably know what the issue is....:( But to confirm, could you try RC2 and see if the issue is there or not?
> https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00-rc2
In RC2 it is working fine. I cannot see the issue there.

**Comment by spdr870** [comment]
Ok, thanks. I'm pretty sure what the issue is. I converted a recursive method to be not recursive. But the code is failing. It is commit c046f57c939be7ddab2da5b7d21c26a043e0792d and 9dbd14c0543c740fbf1a20a512b921c8365fd9ac.

**Comment by HoaFox** [comment]
Thanks a lot Henk for finding the root cause so fast. I am looking forward to get the fix.

Have a nice evening
André

**Comment by RussKie** [comment]
Do you think we can write some kind of test for this?

**Comment by spdr870** [comment]
> Do you think we can write some kind of test for this?

Done
