### ISSUE TITLE
3.0 Not need branch window which freeze the best super fast application

### ISSUE THREAD

**Issue by ChameleonRed** [gitextensions/gitextensions#5884]
**Do you want to request a *feature* or report a *bug*?**
bug/feature/usability

**What is the current behavior?**
Git Extensions open very slowly or refresh very slowly on project with large number of branches because of branch tile left on main window.

Previous I see changes in less 1s now is 30s what makes application not usable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create some large project with 50 branches

**What is the expected behavior?**
I want to disable/close search/branches window or auto close with something visible.
I want super fast refresh as it was previous and what makes this application the best.
Updates of branches should be done in background (windows can show that updating is started and update after background task finished should not block).
Personally I do not like branches window as default - it can be use rarely comparing to core actions.

**Environment you encounter the issue:**
Windows 10

- GitExtensions version: 3.x
- GIT version:  2.3
- OS version: Window 10
- .NET version: ?

**Did this work in previous version of GitExtensions (which)?**
Yes in 2.x

**Comment by RussKie** [comment]
Have you tried this?
![image](https://user-images.githubusercontent.com/4403806/49796234-42a49380-fd90-11e8-80ff-4649430a827c.png)

**Comment by spdr870** [comment]
Like @RussKie said, it can be disabled.

For just 50 branches, 30s is too slow. I have 3000+ branches and it loads in ~1 second. 
Could you give some more info?
- Do you have submodules? 
- Do you load from a network drive

**Comment by ChameleonRed** [comment]
Thanks for hint I found this button after 10 minute search :)

I will send now some repository information to you to study - wait a minute. It is very slow for me.

**Comment by ChameleonRed** [comment]
I tested that 3.0 is very slow in switching project too (repositories) it takes 30s to change project before it is invisible (combo click). That is same problem I think.

**Comment by spdr870** [comment]
A loading time of 30s is not acceptable. Do you have any repositories on a network share? In the issue you mention you use git version 2.3. This is a really old version, Git Extensions officially only supports git 2.11 or newer. It might be a good idea to update to the latest version (https://git-scm.com/).

**Comment by amaiorano** [comment]
Although he may be on an older Git version, @ChameleonRed says it's fast when the left panel is closed. The left panel is doing something with the UI thread that's locking it for the rest of the application, it seems. I'll try to take a look when I can.

**Comment by amaiorano** [comment]
@ChameleonRed When you say that it's slow to refresh, do you mean that the entire application is unusable? What I've noticed is that when I have a large number of branches, the left panel is slow to refresh, but the main repository graph refreshes quickly and I can interact with it.

**Comment by spdr870** [comment]
@ChameleonRed Since you mention that its the refresh that is very slow, could you try to disable the revision graph? Just to investigate what is causing this problem.
![image](https://user-images.githubusercontent.com/38675/49820601-a58a3080-fd78-11e8-875c-07ce567794a9.png)

If this helps, could you try RC2? Its older, but there is one change I want to rule out.
https://github.com/gitextensions/gitextensions/releases/tag/v3.00.00-rc2

**Comment by amaiorano** [comment]
Ah, now that we know it's not the left panel that's causing the slow refresh, then what @spdr870 said is definitely worth testing. Indeed, upgrading the version of Git for Windows you use would be very interesting as well. If we see that it performs much better with a more recent version of Git, perhaps we should consider warning the user if their version is too old.

**Comment by gerhardol** [comment]
--no-optional-locks was backported to 2.51.03 or so
It is the two first options (one of them enable the count, no more effect with two of them) that affect the performance, the third has no impact. Stash count has worse impact, should have --no-optional-locks too.

2.x will cause more background commands, 3.0 has tweaked the handling. But it could be something else that hangs the UI still.

We already report an error if Git is older than 2.11, and give a recommendation to update with older than 2.19.1. But old version is not stopping the application, there are no known errors, we trust the user to update. But there is no possibility for the GE core team to support something other than the latest Git version. (2.19.2 is broken but 2.20 that was just released seem to work well.)

What is in git log? (F12)

**Comment by ChameleonRed** [comment]
@amaiorano Closing left panel only reduce some refresh 30s lags types on main screen (not all) but in other places lags is not reduced at all:

1. push pull lag
2. application start
3. repository switching
4. maybe other which I not learned or remember.

It looks that refreshing algorithm is bad. 
Consider that long operation should asynchronous/background.
Of course better is to optimize it but if it not possible should be async to not show blocking "circle or waiting/freezing" for 30s.

I will test disable options but I want to see number of changed files but not want to see all my branches.

I have superstition that branch tags/scan is root cause but it is superstition/intuition judgement.

**Comment by amaiorano** [comment]
@ChameleonRed I did some profiling last night, and I made a change that's probably not acceptable, but I'm curious if it solves or helps your performance problem. Would you be willing to try this version?

[amaiorano_GitExtensions_faster_revision_graph.zip](https://github.com/gitextensions/gitextensions/files/2672075/amaiorano_GitExtensions_faster_revision_graph.zip)

If that doesn't seem to help, then please try upgrading Git to latest, and test again in your installed version of GitExtensions.

**Comment by spdr870** [comment]
@ChameleonRed It would really help if you give us some of this info we asked. I understand that your not happy with the performance, but repeating this without giving more info will not help. Maybe its not your intention, but calling our algorithms bad and the user experience terrible is not very nice.

Especially the output for F12 helps. Otherwise its a shot in the dark.
For example, this git command is used a lot:
`git show-ref --dereference`

This can be slow, if you do not do maintenance on the repository. You can fix this, for example, by running:
`git pack-refs --all --no-prune`

The log reveals a lot of those problems.

**Comment by gerhardol** [comment]
See #6357 for an alternative description of of what is likely the same problem

**Comment by gerhardol** [comment]
Please try the latest build in master, many performance related to loading with submodules
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by RussKie** [comment]
Presume fixed.
