### ISSUE TITLE
3.0 RC2 is not detecting 3.0 release

### ISSUE THREAD

**Issue by bughit** [gitextensions/gitextensions#5889]
- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3221.0
- DPI X:100.00 % Y:100.00 %

![image](https://user-images.githubusercontent.com/895588/49823603-17995000-fd4e-11e8-969b-52be1f315e92.png)

**Comment by spdr870** [comment]
Version 3.0 is not pushed yet for the auto update. We like to get some experience first. We already got some issues reported that need fixing.

**Comment by bughit** [comment]
that would make sense from a previous stable release, but a pre-release should update

**Comment by spdr870** [comment]
That's true. A stable and edge release channel might be nice. Reopened.

**Comment by RussKie** [comment]
I have updated `configdata` branch.
It is not impossible the update mechanism isn't working correctly when x.y.v parts are the same.
