### ISSUE TITLE
Parent Window of Commit window does not auto close after conflict resolution

### ISSUE THREAD

**Issue by krunalpala** [gitextensions/gitextensions#5895]
**Do you want to request a *feature* or report a *bug*?**
Possible Bug

**What is the current behavior?**
Parent window of commit dialog does not close if there is conflict and after your resolve the conflict.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Steps -
1. create a repo
2. add files - test.txt - add 3 lines and commit/push directly into Github or any repo
Line Number  text
1      hello
2       world
3       change

3. Clone into repo in the local machine by Git Extension
4. Create a conflict by following steps
    a. Go to Github and edit the file test.txt - Line number 2  to "world world"  
    b. Save this file and add the message to commit - Line 2 change remote - Do it directly on Github
    c. As we have not taken latest by pull/fetch command yet into our local machine, We are behind Remote.  Now Edit the file in the local machine test.txt with line number 2 as  " world good world" and save it. 
    d. Now, Commit and push this file from the Git Extensions
    e. As it is Stale (behind remote) - Remote will reject this commit and ask you to either PULL with Merge, Pull with Rebase , etc. Options
   f. Select Pull with Merge
   g. It will try to pull and show us now we have a conflict
   h. Resolve the conflit and then it asks you whether you want to commit  - Select Yes
   i. Commit and push this after resolution of conflict
   j. Successful push seen 
   k. Now, Old window of Step d is still open --- > This is the bug, Old window should close as Git Extension is prompting user to do multiple items and work gets done but the old window is still open.

**What is the expected behavior?**

**Environment you encounter the issue:**
  any environment , very simple test of conflicts as per above steps

- GitExtensions version: Newest version 3.X - also in older versions (Generic issue)
- GIT version: 2.19
- OS version: Windows
- .NET version: 

**Did this work in previous version of GitExtensions (which)?** No

**Comment by vbjay** [comment]
Look at the commit window options.
