### ISSUE TITLE
Stage hunk feature - Similar to sourcetree 

### ISSUE THREAD

**Issue by krunalpala** [gitextensions/gitextensions#5896]
**Do you want to request a *feature* or report a *bug*?**
Feature request - similar to source tree - Stage hunk of lines buttons
**What is the current behavior?**
it is driven by keyboard by key s

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
show button to stage the hunks - similar to sourcetree.

**Environment you encounter the issue:**
All

- GitExtensions version: 3.X
- GIT version: 2.19
- OS version: Windows 10
- .NET version: 

**Did this work in previous version of GitExtensions (which)?** no

**Comment by krunalpala** [comment]
Steps:
1. Please install sourcetree 
2. Clone any repo
3. Change any file at different places
4. Look at the UI - It shows selective staging hunk features  - 3 Sections on the bottom right side with buttons "Stage Hunk, Discard Hunk" - which is there in git extensions but it not the UI as sourcetree  so, you need to select lines in the git extensions and press s key to have selective hunk , Hence the user experience is not good, Instead, git extension should allow options - manual staging by keyboard or auto staging by buttons.

**Comment by Noguai** [comment]
What @krunalpala means is this:
![image](https://user-images.githubusercontent.com/10562439/49868368-88537180-fe0d-11e8-918f-e793357a1529.png)


I do not have a particular opinion on this, but what I do have an opinion on is SourceTree's particular implementation, which is bad. They decided to implement a custom header for each hunk to put their custom buttons in where GitExtensions basically shows just the diff output, but by doing so they made it much harder to scroll horizontally when the hunk you are viewing also vertically spans outside the visible space, as each hunk sits in it's own scrollviewer. Please don't do this.

**Comment by RussKie** [comment]
Thanks @Noguai.

@krunalpala we won't be doing this.

**Comment by vbjay** [comment]
It is also in the context menu. So it is discoverable.

**Comment by gerhardol** [comment]
In GE you can choose specific lines to stage (unstage) then use 's' or the context menu to stage them, so it is more flexible. This is possible in any diff view.

**Comment by crypto-rsa** [comment]
While staging individual lines is the most flexible approach, having _also_ a way to stage the entire (consecutive) block of added or removed lines would be a time-saver, IMHO. I don't know the internals but I guess it can be implemented without having to define a custom hunk header.

**Comment by vbjay** [comment]
Select them. It does work.

**Comment by crypto-rsa** [comment]
It does. That doesn't mean it's the fastest or easiest way to do so. If there is a 50-line hunk you either grab a mouse and select it (which is not the easiest thing when you have to scroll the diff window) or start hitting _S_ over and over again.

**Comment by vbjay** [comment]
Positioned cursor where i want selection to start.
![image](https://user-images.githubusercontent.com/3629489/49872806-33513480-fde8-11e8-85aa-f288a8a11e29.png)

Hit shift while clicking in line 5
![image](https://user-images.githubusercontent.com/3629489/49872839-4a902200-fde8-11e8-8f92-cfdbe07b6d32.png)

**Comment by crypto-rsa** [comment]
Yes, believe it or not, I know all these things. I just think it's another small feature which would make working with commits a bit easier. That's the point of any `git` UI, isn't it?
While talking about hunks, another useful thing for me would be to _copy_ a hunk to the clipboard (for example for comparing two pieces of code changed in a commit). _Yes_, I can select the lines in the diff viewer using the mouse but it would really make it easier if I could just right click anywhere within the hunk and click _Copy_.

**Comment by vbjay** [comment]
How the heck is it to know where a hunk starts and stops without a
selection?

**Comment by vbjay** [comment]
What if user selects so that multiple hunks are involved?

**Comment by vbjay** [comment]
What do you have against selecting?  It makes it quite clear what the user wants to deal with.  They can also copy.  

![image](https://user-images.githubusercontent.com/3629489/49874181-d3f52380-fdeb-11e8-83b1-fb282f5450b5.png)

**Comment by crypto-rsa** [comment]
Jay, I think we are going in circles. I have nothing again selecting. It's just that sometimes a different feature would be useful. I think GE has a very good track record of not forcing users to a _single right way of doing things™_. Why are you so opposed to this?

**Comment by vbjay** [comment]
Because We are not Source Tree.  Selection of the lines and staging or
other actions is actually why we are better.  The user gets visual feedback
of which lines are affected.  Want to stage a couple of lines from this
hunk, we can do this.  Want to stage a couple from hunk 1 and continue into
hunk 2, we got it.  Want to stage line 2 in hunk 1 and line 9 in hunk 2, we
got it.  The selection and S gives finer control over what is staged and is
actually why we are better.

**Comment by gerhardol** [comment]
If there is a feature request in this, it could be that if you have selected in a block, display a new context menu item "stage hunk". Alternatively that a button is visible.

Obviously, detection of "hunk" must be done, but it should not be so difficult.
I do not think it is needed, but if someone submits a well written PR I would not vote against it.

**Comment by Noguai** [comment]
Oh man, I guess I should have explained it a little more before everyone jumps on the "This is total shit" bandwagon. Because to be honest as a longterm SourceTree user myself: There is some usefulnes to that feature, it's just the implementation that could be... improved, as it totally interrupts any other workflow. I mean: How often do you work on two seperate things you want to split out into several commits at once that are so close in every file that almost all changes end up in the same hunk and how often are they seperate enough that most changes you want to split are also in seperate hunks? I find myself often in latter situation. And in that such a feature, if done well, can make things more efficient. Yes there are also shortcuts, but a lot of people don't want / can't remember / use them. And even if, that feature would still reduce: 
"Select File -> Select Hunk -> Stage -> Select Hunk -> Stage -> Select Hunk -> Stage -> Select Hunk -> Stage -> Select File -> Select Hunk -> Stage -> ... -> Commit" 
into 
"Select File -> Stage -> Stage -> Stage -> Stage -> Select File -> Stage -> ... -> Commit"

> why we are better

I actually don't like if people think this way.

> If there is a feature request in this, it could be that if you have selected in a block, display a new context menu item "stage hunk". Alternatively that a button is visible.

THAT sounds like a sensible idea.

**Comment by RussKie** [comment]
To give some perspective why I said we would not be to doing this.

* First of all, I don't like requests in a form "_I don't like something, there is <an app X> that does it better, go check it out and make the same there here_". If you think GE is lacking something - send a PR; or at least explain your request in a form that is a) not demanding and b) clearly explains added benefits and propose a way how it may be achieved.

* Secondly, the core team doesn't have sufficient resources. 
Pretty much all other git clients are backed by multi-billion dollars powerhouses, we on the other hand are all volunteers here without any financial backing or incentive of any kind. 

* Thirdly, we are coupled to ICSharpCode.TextEditor control, which was tweaked for our specific needs. For a number of reasons it is not easy to migrate off this control, even if there is a better alternative (which I am yet to see).

There may be some work done that involves uplifting/refactoring the text editor control if #3600 gets any progress, and that may pave some way for extra controls for hunks in diffs.

**Comment by drewnoakes** [comment]
Interesting ideas here. I personally think I would use a 'stage hunk' kind of feature, though I can't yet imagine having a UI list of hunks.

I can imagine a distinction between lower-case <kbd>s</kbd> to stage the selected line(s) and upper-case <kbd>S</kbd> to stage the selected hunk(s). I'd definitely use that.

My biggest beef with our current staging support is perf. The delay between staging and the UI refreshing is just a bit too long for my taste. I believe some other git clients improve perf here by predicting what the diff will look like after staging, allowing the UI to be updated instantly without waiting for the git process to complete. That sounds like a lot of work, but could be so nice to have.

**Comment by gerhardol** [comment]
Interactive add exists already, so staging hunks already exists in the workflow @Noguai mentioned

**Comment by drewnoakes** [comment]
@gerhardol I'm talking about extending our interactive add. It's probably my favourite feature in GE.

Currently I use the <kbd>s</kbd> key to add after selecting a range with the mouse. 

The idea was to add support for <kbd>Shift</kbd>+<kbd>s</kbd> to stage the hunk at the caret/selection. The difference is one of the required precision.

I'll try to imagine whether I'd use this over the next while. It's hard to say, honestly. I'm pretty used to selecting ranges with the mouse.

**Comment by vbjay** [comment]
I frankly like the precision selecting gives you.  Git hunks aren't always
what you expect.  Being able to select specific lines is a boon.  Our
interactive add beats   git add -p hands down.

**Comment by vbjay** [comment]
You can always run ```git add -p``` in the console.

**Comment by vbjay** [comment]
You can always run ```git add -p``` in the console or add a script with that command.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/49949059-bba40800-fec2-11e8-9126-0491d5f176d6.png)

I think it should work like this if we implement it.  See the hunk header lines?  If the user has selected only that line( or just put cursor in that line) then hitting s should stage that hunk.  I still think outside of that our staging lines should be the default.

Stage lines:
![image](https://user-images.githubusercontent.com/3629489/49949226-248b8000-fec3-11e8-90d1-1db2daa9fb19.png)
![image](https://user-images.githubusercontent.com/3629489/49949295-497ff300-fec3-11e8-8b8c-dd0fea20047a.png)
![image](https://user-images.githubusercontent.com/3629489/49949346-61f00d80-fec3-11e8-9125-132a9500dc79.png)

Stage hunk
text cursor on first @@ line
![image](https://user-images.githubusercontent.com/3629489/49949499-c1e6b400-fec3-11e8-86b7-0cadc6a15474.png)

selection ONLY contains hunk header
![image](https://user-images.githubusercontent.com/3629489/49949464-a8456c80-fec3-11e8-995b-f9c641141946.png)
