### ISSUE TITLE
Git lfs commands deprecated

### ISSUE THREAD

**Issue by spdr870** [gitextensions/gitextensions#5905]
**Do you want to request a *feature* or report a *bug*?**
Feature removal (opposite of #2968; but I would still llike to have some extra lfs features like lfs ls-files, lfs track and lfs install)

**What is the current behavior?**
When cloning a repository, with 'use lfs' enabled, this message appears. In recent versions of git, the lfs specific commands are not needed anymore.
![image](https://user-images.githubusercontent.com/38675/49926807-bc39a000-febc-11e8-8d5e-3a8f241f9ecb.png)

Without the checkbox enabled, the clone still works as expected.

**What is the expected behavior?**
I propose to remove the checkbox.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
We could alter our code to not issue git lfs clone command if the git
version is >= the deprecated version.
https://github.com/yudhajs/git-lfs.github/commit/6f5c9221f60bf1f58d8fcc77ed0afb4898667502#diff-d89d7ff21221243ec96f667828fce577R28

**Comment by drewnoakes** [comment]
Good point.

That was deprecated in 2.15.0. Our [last supported version](https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitVersion.cs#L21) is 2.11.0.

The git version could be used to determine the visibility of the checkbox. If not visible, it's not checked, and we emit the correct arguments.

**Comment by gerhardol** [comment]
Could add the check in GitModule.HasLfsSupport()

**Comment by vbjay** [comment]
Git lfs support and git lfs clone deprecation are two things.

**Comment by gerhardol** [comment]
> Git lfs support and git lfs clone deprecation are two things.

GE only supports lfs explicitly for "git lfs clone". With LFS 2.0 git lfs clone was dramatically faster than git clone if lfs was added.

This not a problem, normal usage is 'automatic'. It is "admins" or superusers that configure lfs and check status etc and they can probably use command line. (I do such tasks and GUI support is not on my wishlist.)

**Comment by RussKie** [comment]
> That was deprecated in 2.15.0. Our [last supported version](https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitVersion.cs#L21) is 2.11.0.

2.16 was release a year ago, should we bump up the min version?
