### ISSUE TITLE
Left Panel branches tree view with horizontal scroll defaults to scrolling to center instead of staying on the left

### ISSUE THREAD

**Issue by anupshah** [gitextensions/gitextensions#5907]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If the left panel tree view lists branches with long names you get a horizontal scroll bar (good)

But it defaults to centering the content instead of starting on the left (not good)

If you manually scroll to the left and do operations that cause the left panel to update it scrolls to the center again

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Open left panel
Resize so it is narrow enough to get a scroll bar (or create branches with long names)
Do an operation like Fetch - when completed it will refresh the UI
The left panel is horizontally scrolled to the middle as per screenshot:

![image](https://user-images.githubusercontent.com/2446665/49946758-8cec5880-fee7-11e8-9b58-c81966bdefcd.png)

Note, when you open Git Extensions it defaults to this behaviour too which can be a bit annoying (mostly because the tree looks cut off). Easy workaround is to manually scroll left but that is not remembered, so next operation (e.g. Fetch, etc) resets it to be centred.

**What is the expected behavior?**
The left panel remains left aligned in terms of horizontal scrolling

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.17.1.windows.2
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
N/A

As an aside, this 3.0 release is really awesome. Many thanks for it. I will donate shortly!

**Comment by drewnoakes** [comment]
> But it defaults to centering the content instead of starting on the left (not good)

I've seen this in tree views before. It scrolls the content right so that the selected node is aligned to the left of the viewport. It's not a great feature IMO.

**Comment by anupshah** [comment]
> I've seen this in tree views before. It scrolls the content right so that the selected node is aligned to the left of the viewport.

Interestingly I've not noticed it before elsewhere...

> It's not a great feature IMO.

Yeah, certainly not nice; it also feels so minor in some ways but it is quite in your face, and given the attention 3.0 would get because of the awesome UI changes it feels more noticeable. Hope its easy to solve.

**Comment by drewnoakes** [comment]
Agreed. I filed a very similar bug against a tree view in Visual Studio a few weeks ago.

BTW I confirmed this bug.

Before refresh:

![image](https://user-images.githubusercontent.com/350947/49953515-29b5f280-fef6-11e8-9dc3-dbb59d3f7086.png)

Then refresh:

![image](https://user-images.githubusercontent.com/350947/49953542-376b7800-fef6-11e8-8a30-1252311a8d1f.png)

Interestingly, if you already have `master` selected in the tree (when `master` is checked out) then it doesn't scroll sideways. 

This appears to happen in response to us setting the selected node in the treeview, probably in response to setting the selected revision in the grid (a guess).

@anupshah this would actually be a pretty introductory bug fix if you were keen!

**Comment by anupshah** [comment]
> @anupshah this would actually be a pretty introductory bug fix if you were keen!

Yes! Spare time is really lacking at the moment but I would like to try... barely done any WinForms stuff, but I'll see if I can do something next week and submit a pull request if so...

**Comment by drewnoakes** [comment]
Hopefully it's less about winforms and more about eventing between components.

**Comment by RussKie** [comment]
I speculate this may be because of `EnsureVisible` call, and if you have
branch names longer than the viewport, the treeview scrolls....
