### ISSUE TITLE
Commit message line endings modified by commit dialog

### ISSUE THREAD

**Issue by Deadlock39** [gitextensions/gitextensions#5908]
I am experiencing a bug/regression with 3.0

When I create a commit using the commit dialog, line endings appear to be getting removed, or converted from Windows (CRLF) to Unix (LF). I haven't been able to confirm which of these is the actual cause, but the result is that all the commit message lines appear to be squashed into one line in the commit message after the commit has completed.

This occasionally does not occur on my initial commit made from a commit template. It always seems to occur if I amend a commit by bringing up the previous commit message via the drop down menu.

**Environment**
- GitExtensions version: 3.00.00.4433
- GIT version: 2.12.2.windows.2
- OS version: Microsoft Windows NT 10.0.16299.0
- .NET version: 4.7.3221.0

This was not happening with version 2.51 prior to upgrading to 3.0.

**Comment by drewnoakes** [comment]
Can you share a screenshot of the problem that occurs after you commit? I am hoping this is just a presentation issue.

**Comment by Deadlock39** [comment]
The title and description appear squashed in the commit view of the main window after this occurs.

![git-extensions-commitmsg1](https://user-images.githubusercontent.com/2559153/49953758-6e289a80-fec4-11e8-8b33-01e8f0fa9fa4.png)

They also appear squashed in the commit dialog after bringing the message up from the history drop down.

![git-extensions-commitmsg2](https://user-images.githubusercontent.com/2559153/49953817-9adcb200-fec4-11e8-8bf8-aa5057b47a03.png)

My changes go through Gerrit for review as well, and the message appears less squashed there, but the blank line between the title and description is gone.

![git-extensions-commitmsg3](https://user-images.githubusercontent.com/2559153/49953877-c19ae880-fec4-11e8-803e-87adf620c041.png)

I have a commit hook that adds the Change-Id seen in these images, which is not affected by this issue, but the Change-Id line gets collapsed into the first line as well if I amend the commit.

**Comment by Deadlock39** [comment]
In some cases, it seems to work normally after my initial commit:

![git-extensions-commitmsg4](https://user-images.githubusercontent.com/2559153/49954496-3589c080-fec6-11e8-92f0-6fd92089954f.png)
Result:
![git-extensions-commitmsg5](https://user-images.githubusercontent.com/2559153/49954505-3a4e7480-fec6-11e8-8958-281b82ec3992.png)

After amending, it always seems to do this:
![git-extensions-commitmsg6](https://user-images.githubusercontent.com/2559153/49954525-46d2cd00-fec6-11e8-9efa-e8ffbb80f450.png)
Result:
![git-extensions-commitmsg7](https://user-images.githubusercontent.com/2559153/49954529-4a665400-fec6-11e8-88b9-057f42da2098.png)

**Comment by vbjay** [comment]
Provide the output of the following commands in git bash in the repo showing this issue
```bash
git config core.autocrlf
cat .gitattributes
```

**Comment by vbjay** [comment]
FYI.  https://help.github.com/articles/dealing-with-line-endings/

**Comment by Deadlock39** [comment]
git config core.autocrlf: true
cat .gitattributes: cat: .gitattributes: No such file or directory

This doesn't seem to be related to a git setting. The issue did not occur prior to my upgrade from 2.51 to 3.0 this morning. Also, disabling the "Compose commit messages in the Commit dialog"setting, and editing my commit messages external to git-extentsions prevents this issue from occurring.

**Comment by vbjay** [comment]
Does it happen without your hook?

**Comment by vbjay** [comment]
I would add debugging code to your hook that lets you see the difference between a regular commit and an amend.  Have it write out the message to a file in the .git folder that is regular_commit and regular_commitMOD and amend_commit and amend_commitMOD.  Look at the before and after your hook modifies.

**Comment by Deadlock39** [comment]
I'm attempting to disable the hook now to determine if it is contributing to the issue.

**Comment by Deadlock39** [comment]
I removed my commit hook, and was still able to reproduce the behavior when amending.

On initial commit there is also a commit template that I have configured. I have attempted to disable that, but have not succeeded yet.

After initial commit, the COMMIT_EDITMSG file looks like this:

test<LF>
<LF>
test<LF>
test<LF>

After amending the blank line is removed.

If I disable the Commit Dialog, the commit message is opened in word pad after clicking the commit button. After saving there, the COMMIT_EDITMSG file looks like this:

test<CR><LF>
<CR><LF>
test<CR><LF>
test<CR><LF>

**Comment by vbjay** [comment]
Initial commit
![image](https://user-images.githubusercontent.com/3629489/49957371-9076e400-fed5-11e8-8798-d6ba57d4e6a5.png)
```
    line 1

    line 3
    line 4

    line 6
```
Amend not changing the commit message
![image](https://user-images.githubusercontent.com/3629489/49957475-e8ade600-fed5-11e8-9f09-64ac481cec7e.png)
```
    line 1                                         
                                                   
    line 3                                         
    line 4                                         
                                                   
    line 6                                         
```

**Comment by drewnoakes** [comment]
Can you reproduce this from the command line?

If you construct a file with specific line endings for the message, then use 

```
git commit --file="commitmessage.txt"
```

Then you can print out the contents of the commit as git sees it directly using

```
git cat-file commit `git rev-parse HEAD`
```

If everything goes well there, you can compare what you see on the command line with what Git Extensions sees when it runs git commands using the Command Log in the Tools menu.

**Comment by Deadlock39** [comment]
I had not thought to check out the command dialog. I can see a bit more details on what is going on there.

I ran the amend here:
![git-extensions-commitmsg8](https://user-images.githubusercontent.com/2559153/49964010-1cd9d480-fedf-11e8-87b5-754039de88c9.png)

Prior to closing the console dialog, the COMMITMESSAGE file is still in the .git folder, and looks like this:
![git-extensions-commitmsg9](https://user-images.githubusercontent.com/2559153/49964050-2f540e00-fedf-11e8-8c1d-cd6ec6f13760.png)

The blank line appears to have been dropped from this temporary file (created by the Commit Dialog I assume?) prior to the commit being performed in git at all. As soon as I close the console, the temporary COMMITMESSAGE file is removed.

**Comment by drewnoakes** [comment]
Here's what happens on my PC:

![image](https://user-images.githubusercontent.com/350947/49966186-3860d180-ff17-11e8-88f4-c008fdf2fd82.png)

![image](https://user-images.githubusercontent.com/350947/49966202-40b90c80-ff17-11e8-8ab8-f3c13b9352aa.png)

![image](https://user-images.githubusercontent.com/350947/49966217-49114780-ff17-11e8-9163-dd4aeccad8f9.png)

It looks like I'm getting your newline 🤣 Why do I have an _extra_ one?

The amend setting doesn't seem to make a difference.

**Comment by vbjay** [comment]
Umm. What the heck?

**Comment by jamez613** [comment]
I'm seeing the exact same issue as @Deadlock39 since upgrading to 3.0

**Comment by RussKie** [comment]
What is your git version?
Have you configured git somehow special?

More info would be great...

**Comment by jamez613** [comment]
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

git config core.autocrlf: true

I also have a commit hook that adds the Change-Id, and I also push to Gerrit. I'm not sure how to disable the commit hook though..?

**Comment by vbjay** [comment]
Rename the hook file.

**Comment by jamez613** [comment]
Interesting, it does seem to be caused by some interaction with https://www.gerritcodereview.com/cmd-hook-commit-msg.html, if I disable the hook ammend works correctly.

I've been using this hook with GitExtensions for years though and it always worked prior to 3.0

**Comment by jamez613** [comment]
Hmm, I spoke too soon - just reproduced it again with the hook still disabled

**Comment by RussKie** [comment]
@jamez613 could you please grab the [portable build](https://github.com/gitextensions/gitextensions/releases/download/v2.51.05/GitExtensions-2.51.05-Mono.zip) from [v2.51.05](https://github.com/gitextensions/gitextensions/releases/tag/v2.51.05) and try it side by side?

**Comment by jamez613** [comment]
2.51.05 works fine for me

**Comment by RussKie** [comment]
That's just got more interesting... 😮

**Comment by jrhall-mchp** [comment]
I am also having the same issue with v3.00.  Tried the portable build from v2.51.05 and it does not exhibits the issue.

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Screenshot this window
![image](https://user-images.githubusercontent.com/3629489/50614049-95fc9400-0ead-11e9-9b44-14182cae37a8.png)

![image](https://user-images.githubusercontent.com/3629489/50614081-a6147380-0ead-11e9-9682-fc5bf9f4a5da.png)

**Comment by vbjay** [comment]
When you have validation rules set and try to commit

![image](https://user-images.githubusercontent.com/3629489/50614535-21c2f000-0eaf-11e9-8433-46e729ac44df.png)

**Comment by jrhall-mchp** [comment]
![image](https://user-images.githubusercontent.com/21690634/50616921-35228b00-0eb0-11e9-8394-897a621c3fb4.png)

**Comment by BaronZemo** [comment]
I have an issue that I think is related to this one.  My newlines get stripped completely from the commit message. It doesn't happen every time. I haven't quite figured out what the common factor is.  Here's my info:

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
If you could work out a pattern, it would help in tracing the issue down

**Comment by BaronZemo** [comment]
I've noticed two different patterns.
1) If I have to stage files during/after typing up my commit message.  There's two ways to make this happen.
1a) If I forget to stage my files before pressing the commit button. Git Extensions will tell me I don't have any staged files and asks if I want to stage them/it, then I say yes, then it commits. 
1b) I have a pre-commit hook that will scan the files I'm trying to merge for a copyright date. If my date is not current, the script will update the files, then I have to stage those changes. 
2) It appears that if I am amending a commit message, the newlines consistently get stripped. I select the previous message from a drop down list, modify message, then commit with the Amend box checked. This consistently removes thew newlines.

**Comment by bsruth** [comment]
I think there was a regression in this commit: https://github.com/gitextensions/gitextensions/commit/ababaff9f29864f4601e5a965b7f126358a0fce1

This change now skips all empty lines. I haven't found a root cause for the newlines being eaten (I think it has something to do with a post-processing script we run). But am planning on submitting a fix.

**Comment by RussKie** [comment]
Thanks, looking forward to it
