### ISSUE TITLE
[3.0] Commit status list is sorted by change type

### ISSUE THREAD

**Issue by glen-nicol** [gitextensions/gitextensions#5909]
**Do you want to request a *feature* or report a *bug*?**
I would call it a bug/oversight. The commit list still works but its behavior is inconsistent with the other default diff lists.

**What is the current behavior?**
In 3.0 The commit dialog sorts unstaged file changes by type (edit, new, deletion). In previous releases they were sorted alphabetically. The other diff lists in 3.0 (selected commit in Git graph and staged change list) are also sorted alphabetically.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open the commit dialog with multiple change types and multiple files of each type.

**What is the expected behavior?**
The files listed in the unstaged list should be sorted alphabetically by default like all the other diff lists.

If alternative sorting is desired I think we should implement that separately as described in #2518. Although sorting should be extended to all diff lists based on one setting.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.18.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3130.0
- DPI 96dpi (no scaling)
- Windows 7 64bit

**Did this work in previous version of GitExtensions (which)?**
<= 2.51.05

**Comment by drewnoakes** [comment]
I don't know that this was an intentional change. Someone may be able to speak to that.

Can you make a PR?

**Comment by gerhardol** [comment]
This discussion originated in #2518 
I have seen this as an unannounced feature, could be changed

**Comment by drewnoakes** [comment]
Seems reasonable that we could support multiple orderings: name, status, time, ...

**Comment by RussKie** [comment]
We need to provide some UI controls to facilitate that then

**Comment by glen-nicol** [comment]
Alright do we want them all sorted independently or should the control/setting apply to all of the diff lists?

**Comment by gerhardol** [comment]
> all sorted independently or should the control/setting apply to all of the diff lists?

I prefer all of the filelists handled the same way, if possible the setting is available in all FileViewer
The information is solved globally instead of for each instance.
(Less to change the behavior, but if someone want a different behavior in say Diff vs Commit, it will not be possible).

**Comment by glen-nicol** [comment]
I agree on all being controlled by a global setting and but also changeable via control on all/most of the lists. I think the first step is to revert the unstaged behavior back to 2.51 so they are consistent. Then look into creating the sorting setting and controls.

**Comment by drewnoakes** [comment]
> We need to provide some UI controls to facilitate that then

Maybe a new "Sort by" context menu with sub-items for each strategy. We would add this on all file lists.

**Comment by RussKie** [comment]
:+1: for the context menu

**Comment by glen-nicol** [comment]
Alrighty, sorry for the delay. Christmas and new years, steam sale and what not too my time. I have replaced that [same branch](https://github.com/glen-nicol/gitextensions/commits/default_commit_list) and it is much better than the first rough draft. 

Changing the sorting in any of the FileStatusLists will affect all the others via a shared service wrapped around the AppSettings class property used to store it.

I understand singletons are typically an anti-pattern but I didn't see a good way to share a single instance of that service through any other existing means. Didn't see any IOC container or references that I am aware of.

Things left to do: 
* Tests (would like to do those once I settle on names and locations for the files and classes)
* Images/Icons for Sorting menu item and Alpha / git change type. Needed? 
* location of the context menu item. I just put it at the bottom of the current list.
