### ISSUE TITLE
GitFlow - Finish not working

### ISSUE THREAD

**Issue by Toudahl** [gitextensions/gitextensions#5912]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
Git flow command is not executed correctly. It only runs: Git flow

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Make a git-flow branch, e.g. a feature branch. Commit some work, and try to finish this using the menus in git extensions
https://github.com/Toudahl/git-flow-bug

**What is the expected behavior?**
The finish button should do: git flow feature finish MYFEATURE
**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Yes. Every single one.

**Comment by gerhardol** [comment]
Should be fixed by someone that uses Git Flow (not added to any milestone)

**Comment by drewnoakes** [comment]
@Toudahl would you be able to debug this? None of the maintainers use git flow. You're in a great position to investigate the problem. If you need help, we'll be happy to give it.

**Comment by Toudahl** [comment]
Yes. But we have a Christmas party this weekend, so it will probably not be able to look at it anytime soon

**Comment by Toudahl** [comment]
This issue is already fixed in 2d664289b666ef6aba8b0812cc585886c8f16101 and merged into the master branch.

The version of gitextensions that gitext offers to download (currently the latest available), has the bug. But 3.01.00.0

Related issue: #5893

**Comment by Griiid** [comment]
Sorry, I'm new to git extensions, fount that git flow feature finish dosen't work, too, in version 3.00.00.4433.

I saw this issue was closed, and Toudahl said the bug was fixed in version 3.01.00.0.

I downloaded git extensions from `sourceforge.net`, and there's no update when I clicked `Check for updates`.

Also, I can't find the new version in [release](https://github.com/gitextensions/gitextensions/releases), can you tell me where can I get the new version?

**Comment by vbjay** [comment]
That's because it hasn't been released.

**Comment by illfated** [comment]
@Griiid : That also means you need either to download Git Extensions 3.01.00 from one of the artifacts produced by AppVeyor, or compile it yourself from the source code, if you want to use version 3.01.00 before it is released.
