### ISSUE TITLE
Feature request: option to hide the left panel completely

### ISSUE THREAD

**Issue by patgauvingeek** [gitextensions/gitextensions#5913]
Feature request: option to hide the left panel completely

I like to have the option to hide the left panel and get back to a view similar to 2.51. I can see what use I can make of the new left panel so having a way to show and hide it rapidly would allow quick access when needed without having it taking space that I was using for the diff area.

**Comment by amaiorano** [comment]
Hi @patgauvingeek, this option already exists:

![image](https://user-images.githubusercontent.com/6893883/50007445-f4a1b280-ff7e-11e8-984e-1189fca4cf54.png)

Click that toolbar button to toggle the left panel on or off. Is this what you're looking for?

**Comment by patgauvingeek** [comment]
Perfect ! Thank you very much !
