### ISSUE TITLE
Diffs are not displayed properly and cannot be scrolled

### ISSUE THREAD

**Issue by Robofolk** [gitextensions/gitextensions#5917]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Diffs  aren't displayed properly and you cannot scroll to see the full file names.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Open the tool
2. Select the repo
3. Click on a commit so that in bottom panel you get tabs for 'Commit', 'Diff', 'File Tree', 'Console'
4. The Diff tab shows a list of diffs but in far right of the tab, so that the entire file names aren't visible, also there is not scroll bar to scroll and see the full file names. Very frustrating actually.

![image](https://user-images.githubusercontent.com/14302406/50044531-b985a900-007c-11e9-8e61-d991212371c2.png)

**What is the expected behavior?**
File names and their full paths are visible and scroll-able in the 'Diffs' tab.

**Environment you encounter the issue:**
GitExtensions 3.0.0
(I encountered this issue in previous builds of GitExtensions also)

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.15063.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
No, as far as I remember this issue has been there in previous versions of GitExtensions.

**Comment by gerhardol** [comment]
I cannot reproduce.
However, this has occurred for other users too (@RussKie ?).

**Comment by RussKie** [comment]
I've seen this issue in one of the RCs, but I haven't observed anything like this in the final v3.
/cc: @NikolayXHD

**Comment by NikolayXHD** [comment]
My hypotesis on what's happened:
As the fix involves `await Task.Delay(TimeSpan.FromMilleseconds(10))` it's not reliable.
When loading v3 after v2 I can imagine some additional startup delays, e.g. due to renamed settings, detecting Git version and so on. In this circumstances the 10ms might have not been enough.

**Comment by RussKie** [comment]
@Robofolk is this happening consistently or was it a once off?

**Comment by Robofolk** [comment]
> @Robofolk is this happening consistently or was it a once off?

It's not a 'once-off' thing. It happens very frequently, but this is not happening all the time too. I have been trying to find a reliable reproduction steps for you, but I haven't found it yet.

**Comment by NikolayXHD** [comment]
I will submit an experimental fix this weekend with increased delay and throttling of column resizing. To see whether it helps.

**Comment by Robofolk** [comment]
I think I've got a reliable reproduction steps now (for this issue or an issue similar to this).

1. Have large diffs (files) so that you get both horizontal and vertical scrollbars on the diffs pane. The first file path in diffs should be small so that you can see it completely without a need for horizontal scrolling. The last file path in the diffs should be very long so that you would need to (a) scroll vertically to get to that row (b) and scroll horizontally to be able to see the full file name.

2. Click on the first file in diffs pane
![image](https://user-images.githubusercontent.com/14302406/50598543-f803cc00-0ea2-11e9-831b-8daab2929f91.png)

3. Scroll down to the bottom of the pane
![image](https://user-images.githubusercontent.com/14302406/50598607-25e91080-0ea3-11e9-9d43-785041676d9d.png)

4. Select the last file in the diffs 
![image](https://user-images.githubusercontent.com/14302406/50598630-37321d00-0ea3-11e9-9ba8-0f9cb6b3f15f.png)

5. Scroll to the right completely to be able to see the full file name of the last row
![image](https://user-images.githubusercontent.com/14302406/50598667-5b8df980-0ea3-11e9-894e-7fd37121b1dd.png)

6. Scroll up to the top row
![image](https://user-images.githubusercontent.com/14302406/50598692-72cce700-0ea3-11e9-8179-a2f1f0202fd9.png)

NOTE: you get that spurious whitespace before all file name in diffs pane. 

Move around to different rows and scroll left-right and up-down multiple times to get the situation even worse.

**Comment by RussKie** [comment]
Thank you @NikolayXHD 

@Robofolk  could you please test and confirm the fix: https://ci.appveyor.com/api/buildjobs/xy36b3wftrnh2xgl/artifacts/Setup%2FGitExtensions-Portable-3.01.00.4702.zip

**Comment by Robofolk** [comment]
> @Robofolk could you please test and confirm the fix: https://ci.appveyor.com/api/buildjobs/xy36b3wftrnh2xgl/artifacts/Setup%2FGitExtensions-Portable-3.01.00.4702.zip

Sorry, don't think I can find for testing this week. I will do as soon as I can.

**Comment by Robofolk** [comment]
> A newer build to test - https://ci.appveyor.com/api/buildjobs/grs9cssbvwp36s37/artifacts/Setup%2FGitExtensions-Portable-3.01.00.4713.zip

I tested it. I confirm the issue has been fixed in this build.
