### ISSUE TITLE
Format patch: Select more than two: path is outside repository

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5923]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If more than two commits are selected in Format patch form, the patches are not created.
![image](https://user-images.githubusercontent.com/6248932/50053217-42f6b300-0131-11e9-998d-841046e90d85.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
* Open Apply Patch
* Select three or more patches. 
* Create patch

**What is the expected behavior?**
Possible to create more than two patches at the same time

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
2.51

**Comment by vbjay** [comment]
It isn't the fact that you have multiple commits. It's the fact that the
output folder isn't in the repo path.

**Comment by vbjay** [comment]
I do see it do this if it is in the path.  Which results in no patches being created.  Yes. Select 1 or 2 commits
![image](https://user-images.githubusercontent.com/3629489/50053353-c3052480-0101-11e9-8b74-83058be4d0db.png) and it does not create any patches.  The other thing I noticed is it fails to create the folder to create the folder unless it actually creates patches.  

We shouldn't allow more than two commit selections.  The way this tool works is it creates patches from a range of commits.  
![image](https://user-images.githubusercontent.com/3629489/50053432-e8def900-0102-11e9-9f38-da6f4e4f6c17.png)

**Comment by gerhardol** [comment]
I do not use patch so my priority is low and maybe just change the error message is acceptable.

I would prefer to allow individual patches (as in 2.51) but from-to patch (similar to  what the diff in Browse would show) should be fairly consistent (then only two revisions can be selected to enable Create patches button).

**Comment by vbjay** [comment]
You can create an individual patch by selecting a commit.  Multiple selections = a range.  So you select the from and then to (like 4e936353e7add443f9513aa76fd0bc112761b9a1..3c2ac977b342f925f740a74957a5570afc58a20d) 

The command that is called is 

```bash
git format-patch -M -C -B "d269d99fed420ca1d0a7737f42996b1c78977d97".."3c2ac977b342f925f740a74957a5570afc58a20d" -o "D:/git/gitextensions/Patches"	D:\git\gitextensions\
```
Obviously with the paths and commit ref based on the state of the form.

**Comment by vbjay** [comment]
Prob should quote the second path.

**Comment by vbjay** [comment]
Huh?  This code is if the count of selection is >2.  It should do the job.  

```c#
                else
                {
                    int n = 0;
                    foreach (GitRevision revision in revisions)
                    {
                        n++;
                        var parents = revision.ParentIds;
                        rev1 = parents?.Count > 0 ? parents[0].ToString() : "";
                        rev2 = revision.Guid;
                        result += Module.FormatPatch(rev1, rev2, savePatchesToDir, n);
                    }
                }
```

Unless the parameters got switched.

**Comment by vbjay** [comment]
Nevermind on the second path.  That was the  path of the current repo and not a parameter in the command.

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/issues/6355#issuecomment-471215388

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/blob/d0ba1a57823f12cc1caec12026586bb9353d2771/GitCommands/Git/GitModule.cs#L1414

**Comment by RussKie** [comment]
We still need to write a test for it...
