### ISSUE TITLE
NRE in Check for updates

### ISSUE THREAD

**Issue by chris-findlay** [gitextensions/gitextensions#5928]
**Bug**

**What is the current behavior?**
Help > Check for updates
Does the check but also pops a NRE dialog that looks just like the one in #4469.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
See above.

**What is the expected behavior?**
No crash dialog.  It's not fatal, but it greatly lessens my confidence in the no-updates-available response.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
2.51

**Comment by vbjay** [comment]
Provide assembly binding logs.  No NRE for me.  

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by chris-findlay** [comment]
Where do I get them from?

**Comment by chris-findlay** [comment]
also, 
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- **Git 2.20.1.windows.1**
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Start a developer command line as administrator and run ```fuslogvw```.  Word of caution.  This can create a lot of log files.  Turn it off after getting the logs.  
![image](https://user-images.githubusercontent.com/3629489/50060091-1b1d4480-015d-11e9-9909-acdd4da59def.png)


https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer

**Comment by vbjay** [comment]
Use a custom log path.  The default path makes it tough to delete.

**Comment by RussKie** [comment]
To add to @vbjay's suggestion - run `fuslogvw` as administrator as some of the settings can't be changed otherwise.

**Comment by vbjay** [comment]
Running dev console as admin and then running fuslogvw in cmd runs fuslogvw as admin.

**Comment by RussKie** [comment]
> Running dev console as admin

Missed that on the screenshot, sorry

**Comment by vbjay** [comment]
No prob.

**Comment by chris-findlay** [comment]
Typical.
Dam heisenbug.  Ran fuslogvw as requested but got no NRE that time.  Closed the log and GitExt; reopened, and still no NRE.
[log.zip](https://github.com/gitextensions/gitextensions/files/2693069/log.zip)

**Comment by chris-findlay** [comment]
**update:** having left it open from before, I then clicked the Diff tab (away from the Commit tab) as I normally do first thing, then just for laughs did another check, and then I got the NRE.

Of course, now I try to turn that into repro steps, it fails again even if I don't do that...
I have it opening a large repo on startup, and I generally wait for that to finish before doing the check for updates.

**Comment by chris-findlay** [comment]
Got logs from when it did die.
[log2.zip](https://github.com/gitextensions/gitextensions/files/2693100/log2.zip)

The main difference that stands out is that it's loaded CSharp and Dynamic as well.

**Comment by vbjay** [comment]
https://github.com/vbjay/gitextensions/blob/b4b11be63f6d81597876e7535100d542eab52a6a/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs#L58

**Comment by RussKie** [comment]
> Download the pdbs https://github.com/gitextensions/gitextensions/releases.

The release doesn't have pdbs available, I ran out of time to configure the script that generates them...

**Comment by vbjay** [comment]
[GitExtensions-3.0.0-pdb.zip](https://github.com/gitextensions/gitextensions/files/2694767/GitExtensions-3.0.0-pdb.zip)

**Comment by RussKie** [comment]
How did you get these?
My understanding pdbs must be built at the same time as assemblies they are for, otherwise internal indices may not match...
I don't think it ever worked for me when I tried building pdbs for existing assemblies (from the same source).

**Comment by vbjay** [comment]
I have a branch adding them to appveyor.  What you can do is use
setup\prepare-release.ps1 to generate them locally.  Just check out the
right commit.

**Comment by jobook** [comment]
fwiw, I just got the NRE with the following stack trace:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Git.hub.Repository.GetRef(String refName)
   at GitUI.CommandsDialogs.BrowseDialog.FormUpdates.SearchForUpdates()
```

**Comment by RussKie** [comment]
any ideas how we can fix this?

**Comment by ruperthawkes** [comment]
I also would be interested to know how to resolve this.

**Comment by c3er** [comment]
I can reproduce this bug quiet reliably. I don't understand enough of the code yet to fix this but it seems that the property "Owner" in `Externals\Git.hub\Git.hub\Repository.cs` never gets a value.

![grafik](https://user-images.githubusercontent.com/24460532/71637179-432ef700-2c3d-11ea-9730-a8c24889e390.png)

**Comment by RussKie** [comment]
@c3er looks like you may be in a perfect position to debug it.

Can you trace how the `Repository` object instance gets constructed?
Looks like this is the only callsite for the method:
https://github.com/gitextensions/gitextensions/blob/a406395810f160ad4f445803a0ad1cedb9ad2bd1/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs#L77-L79

Can you inspect `gitExtRepo` instance?

**Comment by c3er** [comment]
@RussKie Maybe in the next days but I can nothing promise in this regard.

**Comment by c3er** [comment]
I managed to isolate the problem.

![Screenshot of VS debugger](https://user-images.githubusercontent.com/24460532/71776888-0d6d7380-2f99-11ea-8f2a-bb0ffdf1329d.png)

The update search can exceed the limit for GitHub API requests as shown in this response JSON I got calling the GitHub API via my browser:

https://api.github.com/repos/gitextensions/gitextensions

```json
{
  "message": "API rate limit exceeded for <my IP address>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

I observed in https://api.github.com/rate_limit that every click on "Check for updates" does use 5 requests, i.e. the NRE will occur after exactly 13 times checking for updates.

I suggest following changes:

1) This Github client class should have a proper error handling to not show the user exception messages.
2) It should be investigated, why every update check creates 5 GitHub API requests. I expect (naively) that it should only one request.

**Comment by RussKie** [comment]
Thank you!

I ran it with a Fiddler and here are the requests the app is making upon the start up:

* GET https://api.github.com/repos/gitextensions/gitextensions HTTP/1.1
* GET https://api.github.com/repos/gitextensions/gitextensions/git/refs/heads%2Fconfigdata HTTP/1.1
* GET https://api.github.com/repos/gitextensions/gitextensions/git/commits/b22e34f44c00c524c8e15f924d412fede94b0838 HTTP/1.1
* GET https://api.github.com/repos/gitextensions/gitextensions/git/trees/ba5dcb655d41fead42b88040240bcf906fc9c264 HTTP/1.1
* GET https://api.github.com/repos/gitextensions/gitextensions/git/blobs/cc83e4b4bf00454860df6796405d8d9d36fbc709 HTTP/1.1

I expect the 2nd call - it checks `configdata` branch that contains information about the latest version. From there it follows down the ref chain to get to the `GitExtensions.releases` file.

I wonder if we can replace the whole thing with just fetching and parsing https://raw.githubusercontent.com/gitextensions/gitextensions/configdata/GitExtensions.releases instead 🤔

**Comment by pmiossec** [comment]
>I wonder if we can replace the whole thing with just fetching and parsing https://raw.githubusercontent.com/gitextensions/gitextensions/configdata/GitExtensions.releases instead 🤔

The perfect solution 👍 as it reduces a lot the number of calls and also solve the api rate limit problem because that's not an api call 🤙
