### ISSUE TITLE
commit dialog esc

### ISSUE THREAD

**Issue by chris-findlay** [gitextensions/gitextensions#5929]
**Bug**

**What is the current behavior?**
`Esc` to close the commit dialog only works when the diff pane has focus, not when other panes do.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open commit dialog; attempt to close using `Esc` key when different parts of the dialog have focus.

**What is the expected behavior?**
Esc works everywhere.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)
**Did this work in previous version of GitExtensions (which)?**
2.51 - tho I'm not sure it worked everywhere then, it worked in more places than now.

**Comment by mstv** [comment]
The same applies to the File History / Blame dialog.

**Comment by RussKie** [comment]
@mstv are you having the same issue?

**Comment by mstv** [comment]
I cannot reproduce it in the Commit dialog neither with the portable build 3.00.00.4433 nor with my extended build.
Though Esc does not close the File History / Blame dialog if any of the file views has the focus.

**Comment by mstv** [comment]
Esc should close the Stash Manager, too.

**Comment by RussKie** [comment]
Please raise new issues for File History / Blame / Stash Manager dialogs.

@chris-findlay I guess this one is something you need to investigate yourself, since we can't replicate it.
