### ISSUE TITLE
Script: cDefaultRemotePathFromUrl returns bad information

### ISSUE THREAD

**Issue by malys** [gitextensions/gitextensions#5932]
Hi,
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug. 

**What is the current behavior?**
`{cDefaultRemotePathFromUrl}` script tag returns always "git"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a script `{openUrl} https://gitlab.com{cDefaultRemotePathFromUrl}/tree/{sBranch}`
The script should return: `https://gitlab.com/gitlabhq/gitlabhq/tree/master`
where `cDefaultRemotePathFromUrl=/gitlabhq/gitlabhq` and `sBranch=master`

After upgrading `cDefaultRemotePathFromUrl=git`

See your provided script "Open on GitHub", It doesn't work fine.

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
It works well with previous version.

**Comment by RussKie** [comment]
I believe the regression was introduced in https://github.com/gitextensions/gitextensions/commit/587af4f3bfcc509f124f128fb05b4cf1d36a031a#diff-062fb32fceffaf338389dbd4d17fddcbR87

**Comment by malys** [comment]
@RussKie Well done. The regression is fixed.
Thx for your help and reactivity.
