### ISSUE TITLE
Commit window left side splitter position not remembered

### ISSUE THREAD

**Issue by RSchwoerer** [gitextensions/gitextensions#5935]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Splitter location  of changed files and staged files ( `splitLeft` ) returns to default position every time Commit window is opened.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. open Commit window
2. move horizontal splitter on left side, move vertical splitter
3. close Commit window
4. open Commit window
5. ** horizontal splitter on left side is back to the middle **, vertical splitter is remembered

**What is the expected behavior?**
Remember splitter location.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3190.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
n/a

**Comment by RSchwoerer** [comment]
This looks like a fairly trivial fix.

Adding `_splitterManager.AddSplitter(splitLeft, "splitLeft");` at
https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/FormCommit.cs#L257

I cannot get the latest code to open/build, or I would submit a PR.

**Comment by vbjay** [comment]
Yes, you can get the code

1. Fork this repo ( repeat 1 and 2 for each submodule if desired.)
2. Clone either ssh or https ![image](https://user-images.githubusercontent.com/3629489/50110966-989e8e80-0209-11e9-94e6-cdefa9d5a7a5.png)
3. Update submodules
3. Modify remotes in submodules to have an origin remote pointing to your repo and upstream pointing to gitextension's repo if you forked the submodule repos.
4. Run setup\build in developer cmd prompt to check that building works.  If VS complains about c++ dependencies or other needed items, install them using vs installer.  
5. Open in VS
6. Ignore Setup project warnings if you do not have wix installed.
7. Build solution.

**Comment by RussKie** [comment]
> I cannot get the latest code to open/build, or I would submit a PR.

Could you please elaborate what is stopping you.
Please consult the [readme](https://github.com/gitextensions/gitextensions/blob/master/README.md) for the pre-reqs.
Shout if you need any help

**Comment by RSchwoerer** [comment]
OK, turns out it was a weird issue with VS2017. (somehow nuget package manager was corrupt or something).

I was able to reinstall it and add the PR.
