### ISSUE TITLE
Can no longer reset submodule changes in the super project's commit window.

### ISSUE THREAD

**Issue by Tagette** [gitextensions/gitextensions#5937]
When I try to reset submodule changes from the super projects commit window, it does not reset anything.

1) Make changes in a child submodule.
2) Go to the super project's commit window.
3) Right click the submodule change and click "Reset submodule changes".
4) Notice how the changes were not reset.

This bug may require that you only have "new file" changes in the submodule.

- GitExtensions version: 3.00.00
- GIT version: 2.20.1
- OS version: Windows 10
- .NET version: Windows 10

This works in git extensions 2.51.05.

**Comment by vbjay** [comment]
Works  ![image](https://user-images.githubusercontent.com/3629489/50114010-845e8f80-0211-11e9-8210-14178a5a0447.png)

Works ![image](https://user-images.githubusercontent.com/3629489/50114105-ba037880-0211-11e9-9ed7-3ca5d7ee0e53.png)

Fails to delete new files even if Also delete new files checked
![image](https://user-images.githubusercontent.com/3629489/50114208-fcc55080-0211-11e9-9f4b-ddf48080b68e.png)

**Comment by vbjay** [comment]
Workaround is to select commit submodule changes and then in the new dialog, reset in the current dialog and then close the dialog.  Then continue with main repo actions.

**Comment by gerhardol** [comment]
As vbjay showed, this only affects new files not being deleted. This occurred both in the Commit dialog and in revisiondiff (WorkingTree artificial commit).

Please test the updated build in https://ci.appveyor.com/project/gitextensions/gitextensions/builds/21261432

**Comment by gerhardol** [comment]
commit|reset|stash submodule changes
All are done in the context of the submodule, same as if you opened the submodule and applied the command there.

Update submodule is different, it is changing the commit from the current repo (superproject). 
A separator could be added in the context menus.

**Comment by RussKie** [comment]
Indeed, however when I see a dirty state of a repo due to submodules I have
to always think - do I need to update or reset or both?
And I never seem to get it right /facepalm

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/50520284-74ef0a00-0a8d-11e9-95f4-08959a2e55ac.png)

We could use ahead/back status to tell the user they are on the same commit and there are changes in the working directory (0 ahead, 0 back).  They can always get more details by right clicking and clicking commit submodule details.  That tells you if there are working directory changes.
