### ISSUE TITLE
Error and crash when using multiple remotes for a single branch

### ISSUE THREAD

**Issue by gsedlacz** [gitextensions/gitextensions#5943]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Our current git configuration causes an Error within GitExtensions.
GitExtensions throws an ERROR:
```
Type: System.Exception
Msg: Remote URLs should appear in pairs.
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
We have to push a certain branch of our product to a customers git server but we also need it on our default one.
Within .git/config we defined a remote as follows:
```
[remote "origin_and_customer"]
    url = OURGIT
    url = CUSTOMERGIT
    fetch = +refs/heads/*:refs/remotes/origin/*
    fetch = +refs/heads/*:refs/remotes/customer/*
```
This remote is used for a single branch:
```
[branch "customer_branch"]
	remote = origin_and_customer
	merge = refs/heads/customer_branch
```

**What is the expected behavior?**
This configuration used to pull from OURGIT und fetch metadata from CUSTOMERGIT.
It could also push to both sequentially even.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3190.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
It used work with GitExtensions 2.x. (the latest one before the new Remotes overview was introduced)

**Comment by gerhardol** [comment]
GE supports two separate remotes for situations like this.

**Comment by RussKie** [comment]
@gsedlacz the way you configure your remotes seems somewhat unusual.
In a situation like yours I'd configure two different remotes - one for each git repo. Then you can fetch all changes from all repos and push changes to a selected ones.

Please have a look under _Repositories > Remote repositories..._ menu.

**Comment by gsedlacz** [comment]
The neat advantage of this configuration is that you can push to two different repositories with a single action.

The problem is that GE crashes in such a situation.

In my opinion it should not crash as its a valid configuration for git via cli.

**Comment by gerhardol** [comment]
Duplicate of #6093
