### ISSUE TITLE
settings, arrow navigation in the tree

### ISSUE THREAD

**Issue by chris-findlay** [gitextensions/gitextensions#5946]
**minor bug**

**What is the current behavior?**
If I use the up/down arrows in the settings dialog when the tree has focus, I get stuck going up at the Git node, which forces the selection to its first child when it gets selected (which makes sense, until it got focus from an up key *from* its first child).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open settings; note that navigating down the tree with arrow keys works; note that navigating back up gets stuck.

**What is the expected behavior?**
Up from first child of Git would select the tree-previous or previous sibling of Git, rather than re-selecting the first child.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Dunno - never tried it before.

**Comment by gerhardol** [comment]
All other nodes have something to show, but top Git jumps directly to Paths (you cannot select Git node.)
(GitExtensions level has the overview and Plugins a summary.)

**Comment by chris-findlay** [comment]
I understand why it happens, I just figured I should record the fact that it does.  Edge-case handling for up-arrow seems harder than adding a summary page, but just off the top of my head I'm not sure what would go on it.  There's probably something useful tho that would work.

**Comment by gerhardol** [comment]
A summary page as for Plugins should be sufficient
