### ISSUE TITLE
Commit button shows 2 files even though there are no changes

### ISSUE THREAD

**Issue by dmjanssen** [gitextensions/gitextensions#5947]
I just updated to GitExtensions 3 and it says I have two files that need to be committed. However, the commit box is empty. Similar to #5126 and #5127. 

![image](https://user-images.githubusercontent.com/26991323/50184856-80934180-02d3-11e9-9fb5-5ce47f9e5dfc.png)

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.9.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Check for a stuck git process.

**Comment by gerhardol** [comment]
Too old Git, must be 2.11 or later (--porcelain=v2 was introduced in 2.11)

**Comment by vbjay** [comment]
Good catch.
