### ISSUE TITLE
Commit message in "commit" tab/panel is editable and commit links are not clickable

### ISSUE THREAD

**Issue by Kryptos-FR** [gitextensions/gitextensions#5950]
**Do you want to request a *feature* or report a *bug*?**
It's a bug.

**What is the current behavior?**
The commit message in the "commit" tab is editable and links (e.g. to cherry-picked commit id) are not clickable.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- Select any commit
- Commit message can be edited (looks like it is displayed in an editable RichTextBlock or something similar)
* If the commit message contains a commit id (e.g. after cherry picking), it is shown as a link but clicking as no effect.

**What is the expected behavior?**
- Commit message should not be editable
- Link to commit should work

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3133.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Yes. Any previous version I think, 2.x definitively.

**Comment by Kryptos-FR** [comment]
Partial duplicate of #5870 (fixed by #5871). Sorry IU did not find them before submitting.

**Comment by gerhardol** [comment]
commit id is reported in #5904 
Was there anything, can this be closed?

**Comment by Kryptos-FR** [comment]
Apparently not. Sorry for the duplicates.

While I'm here, should we expect a fix release soon? Asking because I'll ask my company to package it for internal deployment. Since that process takes time, if a release is planned before the second week of January, I can wait until then.

**Comment by gerhardol** [comment]
> While I'm here, should we expect a fix release soon?

I am not deciding this, but  there are in my view no real show stoppers that require a 3.0.1 release, but several larger annoyances that should be included in a 3.1.0 that at least will require an RC. If 3.1.0 is released in the beginning of February, that is early.

**Comment by Kryptos-FR** [comment]
Ok. Thanks. I'll package the current version then. It is such an improvement over the 2.x series that I can accept a few annoyances.

**Comment by RussKie** [comment]
We will likely do a maintenance release before the NY addressing a number
bugs identified in v3.0.0.
