### ISSUE TITLE
Git 3.0 slow on main project window (win 10)

### ISSUE THREAD

**Issue by gregmbi** [gitextensions/gitextensions#5954]
When I upgraded from GitExtensions 2.51 to 3.0, on it, every time the software returns to the main project interface, there is about a minute of unresponsiveness from the software. On 2.51 and previous version i didn't see this issue, this happens on all my projects, some are small with no SubModules.

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
2.51.05

**Comment by gregmbi** [comment]
I looked at those issues before opening this one. No they don't seem to be related. these are all local repos on the local storage. the slowdown is not on the opening recent repos page, but on the main page of an open repo, that is why its so painful, every time i do any action, when the software returns to this window it freezes for a long time.

**Comment by vbjay** [comment]
Try turning off antivirus temporarily.  AV and git have fought before.

Try this

Open GE
Press f12
Check call stack checkbox
Open repo
Wait for it to finish loading
Export log.

Attach log in a comment here.

**Comment by jtgo** [comment]
I had issues with remote repositories being really slow, and tried to open a local repository. The local repository opened very slowly as well (~2 minutes before UI loading completed). However, I cleared my recent repositories list, and now it opens very quickly (~5 seconds).

**Comment by vbjay** [comment]
> Do you have repositories located on a network share? This might be the same issue as #5836 and/or #5829, which is fixed in pr #5887.
> 
> This can be tested in this build:
> https://ci.appveyor.com/project/gitextensions/gitextensions/builds/20930494/artifacts

Did you try the build here?

**Comment by RussKie** [comment]
> I had issues with remote repositories being really slow, and tried to open a local repository. The local repository opened very slowly as well (~2 minutes before UI loading completed).

This is very interesting. 
Do you still have a backup of the list? 
It would be good to find out why it made a difference...

**Comment by gregmbi** [comment]
> > Do you have repositories located on a network share? This might be the same issue as #5836 and/or #5829, which is fixed in pr #5887.
> > This can be tested in this build:
> > https://ci.appveyor.com/project/gitextensions/gitextensions/builds/20930494/artifacts
> 
> Did you try the build here?

I did now, it solves the problem ! :) thanks guys

**Comment by RussKie** [comment]
Reopening since the referenced issues/PRs are still open.

**Comment by spdr870** [comment]
Closed by #5887.
