### ISSUE TITLE
Esc key to close the File History / Blame dialog from everywhere

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5957]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The Esc key does not close the File History / Blame dialog if any of the file views has the focus.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- open the history of a file
- open the Commit tab, focus the file view, hit Esc
- open the Diff tab, focus the diff view, hit Esc
- open the View tab, focus the file view, hit Esc
- open the Blame tab, focus the file view, hit Esc

**What is the expected behavior?**
Esc closes the dialog from everywhere.

**Environment you encounter the issue:**
- Git Extensions 3.01.00.0
- Build f8c5a8b8a04f478a94027636387303ae9d3cdc3b
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
don't know

**Comment by drewnoakes** [comment]
Similar to #5634.

**Comment by drewnoakes** [comment]
(Meta question: @RussKie do you or anyone else know why the build SHA in this issue report does not resolve to a known commit in this repo?)

**Comment by drewnoakes** [comment]
(@mstv is this your own local build, based on unmerged commits?)

**Comment by vbjay** [comment]
That's exactly what that means.

**Comment by mstv** [comment]
> Is this your own local build, based on unmerged commits?

Yes, it is.

**Comment by mstv** [comment]
I've prepared an implementation. Though the `ICSharpCode.TextEditor` throws a NRE.
Must I fork it and create a PR? Or can a member commit this missing `?`?
![grafik](https://user-images.githubusercontent.com/36601201/50296967-f1755d80-047b-11e9-9a3b-2227964bc569.png)

**Comment by drewnoakes** [comment]
@mstv that's great news.

In general it's best to file a PR directly against the submodule's repo and we will get it reviewed and merged quickly to unblock your work here.

In this case the change looks benign so I just made it directly for you. You should be able to update the submodule and continue your PR.

**Comment by mstv** [comment]
Thank you, Drew, for pointing to #5634 and for quickly adpating the ICSharpCode.TextEditor.
