### ISSUE TITLE
Crash when clicking on "Help translate" in appearance settings

### ISSUE THREAD

**Issue by Kryptos-FR** [gitextensions/gitextensions#5960]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
Clicking on "help translate" link in the **Appearance** section of the settings window crash the application.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. Open the settings window
2. Go to **Git Extensions** -> **Appearance** section
![image](https://user-images.githubusercontent.com/3006525/50264819-c3822000-045f-11e9-8991-6a645df8d9ed.png)
3. Click on "Help translate"
4. GitExtensions crashes
![image](https://user-images.githubusercontent.com/3006525/50264851-fa583600-045f-11e9-8ec9-38160c383bb3.png)

**What is the expected behavior?**
- When developing GitExtensions it could open the TranslationApp (crashes because application doesn't exists)
- In official releases, it should go to the wiki page (same as **Menu** -> **Help** -> **Translate**)
- Should be surrounded by a `try...catch` in any case.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3133.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Dunno. Never tried before.

**Comment by drewnoakes** [comment]
@Kryptos-FR thank you for the report!

I can reproduce this.

(We really need to replace that useless NBug dialog with something that makes it easy for people to include meaningful information in issues...)

**Comment by drewnoakes** [comment]
The code in question is here:

https://github.com/gitextensions/gitextensions/blob/72110738402fcd4111933d2e22743f40e574cf7f/GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs#L171-L174

Is this an omission of the installer? Are we supposed to be bundling `TranslationApp.exe`?

**Comment by gerhardol** [comment]
TranslationApp should not be included, only used by maintainers now. The link should be to the wiki page.

**Comment by RussKie** [comment]
> (We really need to replace that useless NBug dialog with something that makes it easy for people to include meaningful information in issues...)

Yes, related discussion in #5064

> Is this an omission of the installer? Are we supposed to be bundling `TranslationApp.exe`?

I suppose no one ever clicked the link until now... 🤦‍♂️ 

Instead of using the TranslationApp (which is only used for updating translations when prep'ing releases), this link should behave consistently with other "translate" links and navigate to https://github.com/gitextensions/gitextensions/wiki/Translations
