### ISSUE TITLE
Option to show tags not stored on restart

### ISSUE THREAD

**Issue by frank-freihube-rmcan-com** [gitextensions/gitextensions#5962]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
On closing Git Extensions the option to show tags in the new left hand side branch overview does not get stored and get's reset to not checked

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

1. open a repository which includes tags
1. check `Show tags` found in the gear menu on the left hand panel
1. close Git Extensions and open it again
1. open any repository containing tags (might be the same as in the first step or another one)

(see gif)

![gitexerror](https://user-images.githubusercontent.com/5540788/50280183-1f42ae00-044c-11e9-91e1-86e6d2ce6369.gif)

**What is the expected behavior?**

The check box should stay checked after restart

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
no, checkbox has been introduced in 3.x (as far as I know)

**Comment by pmiossec** [comment]
I don't know if it's so much costly to retrieve tags...

Because I don't really know why there is an option to display tags.
I think that will remove some code to remove this option (without a performance regression) and prevent to add some more code (by not implementing this one...)
