### ISSUE TITLE
Build report not in File History / Blame window

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5965]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
the build report is displayed in the File History / Blame window
![grafik](https://user-images.githubusercontent.com/36601201/50295566-9aba5480-0478-11e9-9175-549ed718c50a.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
just hit `H` on a file

**What is the expected behavior?**
the Build Report tab is shown only in FormBrowse

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433, at least since 3.00.00.4000
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.10.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
2.51.05

**Comment by drewnoakes** [comment]
I thought this tab only appeared if builds are found, suggesting there might be one in that revision grid.

**Comment by mstv** [comment]
Yes, you are right.
