### ISSUE TITLE
Overflow of superproject references

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5966]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
scrambled display and unclear `...` reference(s) after some time
3.00.00.4433:
![grafik](https://user-images.githubusercontent.com/36601201/50298727-1ec40a80-0480-11e9-8aa6-fcea2f9e1aa6.png)

current pre 3.01.00 master 7211073:
![grafik](https://user-images.githubusercontent.com/36601201/50299491-ffc67800-0481-11e9-854e-56b89cdd3349.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- open the GE repo
- go to the subproject "ICSharpCode.TextEditor"
- move the mouse around for about 30 seconds

**What is the expected behavior?**
The revision grid is invalidated/refreshed correctly when the background process has finished.
The omitted info behind ![grafik](https://user-images.githubusercontent.com/36601201/50299860-fc7fbc00-0482-11e9-9303-2c7a46262d23.png) should be displayed somewhere (if there is really something behind -- see the difference between the head commits in the screenshots).

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.10.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
new feature in 3.x

**Comment by gerhardol** [comment]
The first part (not updating superproject branches/tags automatically) is handled in #5981 

Do you believe the "scramble" part is OK in master?

The overflow is not handled, should this issue be a feature request for that?
Where to diplay, tooltip?

**Comment by mstv** [comment]
> Do you believe the "scramble" part is OK in master?

Yes, it is. Thank you.

> The overflow is not handled, should this issue be a feature request for that?

Yes.

> Where to diplay, tooltip?

It should be added to the Commit Info's "Contained in branches" IMO.
A tooltip when hovering the ![grafik](https://user-images.githubusercontent.com/36601201/50299860-fc7fbc00-0482-11e9-9303-2c7a46262d23.png) would be nice. Though currently, the tooltip is displayed only for commits with a multi-line commit message.
