### ISSUE TITLE
Commit button always visible

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#5968]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I can click the Commit button before it gets labeled on startup.
(When switching between repos the Commit button does not indicate that the displayed state might be outdated.)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
just click here while the first repo is loading
![grafik](https://user-images.githubusercontent.com/36601201/50314956-2354e700-04b1-11e9-9db2-67f5b88cc6f6.png)

**What is the expected behavior?**
The Commit button shall always be labeled. It is annoying to puzzle where it will appear finally.
The Commit button should have a different icon while the repo is loaded, maybe ![grafik](https://user-images.githubusercontent.com/36601201/50315196-0ff64b80-04b2-11e9-9657-51a976a172ed.png) in gray.

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433 and 2.51.05
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.10.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
maybe 2.49.3

**Comment by vbjay** [comment]
That's because it is still generating the info modified count and such. It
does not take long for it to show.

**Comment by mstv** [comment]
Believe me, it *does* take long! About 1-3 seconds for the GE repo.

**Comment by mstv** [comment]
If you really think, it should be invisible than it *must* be really invisible and disabled.
Though it does not make sense to me to hide a button which will always be applicable.

**Comment by gerhardol** [comment]
As the text is translated, it is probably later (maybe it could be updated twice, but then only English will be correct).
It is possible to deactivate commit count on the button and only have it in the revision grid. (to settle the discussion at least)

**Comment by mstv** [comment]
The translation is available much earlier than the loading will be finished. The labels "Branches" and "Filter" have already been translated when the window appears.
The commit count can be added when the proposed "refresh icon" will be replaced with the orange or green one.

**Comment by RussKie** [comment]
I agree it takes a while for a button to appear, several times I have
resorted to using a shortcut to open the commit dialog.
We should show the button and update it with info as it becomes available.

**Comment by mstv** [comment]
What is the benefit of replacing the button `toolStripButtonCommit` with the ToolStrip**MenuItem** `_toolStripGitStatus`?
I guess this is an unnecessary remainder of the previously removed `ToolStripGitStatus _toolStripGitStatus`.

FormBrowse.cs(268):
```C#
                // TODO: Replace with a status page?
                _toolStripGitStatus.Click += CommitToolStripMenuItemClick;
                ToolStrip.Items.Insert(ToolStrip.Items.IndexOf(toolStripButtonCommit), _toolStripGitStatus);
                ToolStrip.Items.Remove(toolStripButtonCommit);
```

**Comment by mstv** [comment]
Which tool do you use to create .png files with a color palette and an alpha mask?
I am trying to add a bitmap like ![grafik](https://user-images.githubusercontent.com/36601201/50548785-cac0df00-0c52-11e9-9535-87672ea3f988.png) which I want to display while a repository is (re)loaded.

**Comment by gerhardol** [comment]
> What is the benefit of replacing the button toolStripButtonCommit with the ToolStripMenuItem _toolStripGitStatus?
I guess this is an unnecessary remainder of the previously removed ToolStripGitStatus _toolStripGitStatus.

The status was built in to the button previously so this should be a reminder.

> Which tool do you use to create .png files with a color palette and an alpha mask?

If you are happy with any advise, Paint.NET will do the job.

> I am trying to add a bitmap like grafik which I want to display while a repository is (re)loaded.

Something I would like to see too. The loading phase is handled with the spinner, but someway mark until the status is actually updated would be nice.
(GitStatusMonitor is clearing status by sending out 0 changes when the repo changes, need to be changed too.)

**Comment by mstv** [comment]
Thank you, Gerhard.

Then I would remove `_toolStripGitStatus` and use the form's `toolStripButtonCommit`.

Paint.NET handles the alpha mask correctly. Though the resulting file is larger than the original (using a color palette) by up to factor 4 unless I chose 32 bits per pixel explicitely.

The hint to adapt the `GitStatusMonitor` will help to handle in the correct place.

**Comment by drewnoakes** [comment]
What about this?

- The commit button is always visible
  - While loading we use the gray version of the icon (I'm pretty sure it already exists)
  - If we need to prevent clicking it for any reason, it is disabled rather than hidden (reducing horizontal movement within the tool strip)
  - We need to ensure it is correctly translated
- If the user opts to see number of changes on the button, that information is added once it becomes available, however it is made interactive as early as possible

**Comment by drewnoakes** [comment]
> Paint.NET handles the alpha mask correctly. Though the resulting file is larger than the original 

The PNG files in this repo have been 'crushed'. This online tool can help: https://tinypng.com/

**Comment by drewnoakes** [comment]
Haha I just saw your PR which does pretty much what I suggested. Facepalm. Will review.

**Comment by mstv** [comment]
Unfortunately, it does still not work correctly in all cases, e.g. the button stays gray after committing.
Gerhard recommended a different place from where to invalidate the button.

**Comment by gerhardol** [comment]
Commit Button must not be visible/enabled in bare repos. (Prefer disabled)
For normal repos the button should always be visible and active.

With this change, it may be possible to remove the requirement to restart to activate/deactivate commit count. But that is probably a follow up.
