### ISSUE TITLE
Size dialog "Clone"

### ISSUE THREAD

**Issue by slvr9** [gitextensions/gitextensions#5972]
Inaccuracy in calculating the size of the "Сlone" dialog box or the location of its elements.
Occurs when using the "Russian" translation.
The screenshots, erroneous (marked in red) and normal view.

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.2.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.6.1055.0
- DPI 96dpi (no scaling)

The screenshots:
- Error (marked red)
   ![dialogclone_ru_er](https://user-images.githubusercontent.com/394362/50326558-d7d02680-050c-11e9-8eb5-7aa951ebeda4.png)
- Normal view
   ![dialogclone_en_ok](https://user-images.githubusercontent.com/394362/50326554-d6066300-050c-11e9-9052-1b897a6721c8.png)

**Comment by hankyulhyun** [comment]
Is it right way to fix? :: Just stretch clone box to horizontal?

**Comment by drewnoakes** [comment]
@slvr9 what DPI are you running at? Please include information from Help/About/Copy.

**Comment by RussKie** [comment]
Now we're talking! Good idea!
But (there is always a "but", isn't there) we need to get significantly
better at testing and write integration and UI tests.

**Comment by gerhardol** [comment]
One way to get this problem disappear is to remove lfs option where not needed (never git). I believe that there is an issue.

**Comment by vbjay** [comment]
No. I don't want it removed. I want lfs support to expand. Add am editor like gotignore that allows us to control tracking. Do a lfs pull. ....  I think your view of the problem is too nearsighted. It isn't just this window. All windows will have this problem with translation.

**Comment by RussKie** [comment]
#6041 pretty much renders this issue obsolete.
