### ISSUE TITLE
Remove VSIX from installer

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#5979]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The Visual Studio 2015-2017 vsix is included in the GE installer with an option to install.
The install option is copying the vsix to the GE installation dir. Installation can be done from the Program Files folder. This is not clear in the installer.
This option in the installer installed the old VS addin, the vsix was likely just added in a similar way

VSIX is officially distributed on VS Marketplace.

The vsix is a simple wrapper to call GE. It is visually updated in 3.0. In master VS2019 is enabled, that should be the official release.
 
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
 * Remove vsix from the installer.
 * Add vsix as an artifact in Appveyor builds
 * Possibly add vsix to downloads at release builds
 * Add the vsix in master to Marketplace

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by vbjay** [comment]
Amen.  I've been wanting this for a while.  I also anted the visix to
detect the program not being installed and launching a download of the
latest release.
