### ISSUE TITLE
git extesntions cann't save difftool(beyond compare 4) with custom path

### ISSUE THREAD

**Issue by godcong** [gitextensions/gitextensions#5980]
git extesntions cann't save difftool(beyond compare 4) with custom path

i changed the difftool on init to beyond compare 4 with my custom path:
"D:\Program Files\Beyond Compare4\BComp4.exe"
and save then reset.
it's not apply.

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by godcong** [comment]
then i reinstall the beyond compare 4 with default path.
it's runs correct

**Comment by gerhardol** [comment]
The path for known tools is fixed.
You can set a custom path from the commandline though.

**Comment by godcong** [comment]
i changed .gitconfig to fixed it.

[merge]
	tool = BeyondCompare4
[diff]
	guitool = beyondcompare4
[core]
	editor = \"D:/workspace/software/GitExtensions/GitExtensions.exe\" fileeditor
	autocrlf = input
[mergetool "BeyondCompare4"]
	path = D:/workspace/software/Beyond Compare 4/BComp.exe
	cmd = \"D:/workspace/software/Beyond Compare 4/BComp.exe\" \"$LOCAL\" \"$REMOTE\" \"$BASE\" \"$MERGED\"
[difftool "beyondcompare4"]
	path = D:/workspace/software/Beyond Compare 4/BComp.exe
	cmd = \"D:/workspace/software/Beyond Compare 4/BComp.exe\" \"$LOCAL\" \"$REMOTE\"

**Comment by gerhardol** [comment]
This behavior should be changed

**Comment by RussKie** [comment]
The whole diff tool handling must be rewritten.
I had a go at it ([a branch in my fork](https://github.com/RussKie/gitextensions/commits/add_and_refactor_diffmerge_tools), 8a8d481917ec7839021c2b5669c07998bc6d10c3 and 52abbc99def7e87dd7036cbea2e4768036abb28c)  but it got bumped down in priorities... I'm pretty sure I had a stab at the usability of the settings page as well, but can't find it.

**Comment by godcong** [comment]
I remember that in version 2.5, this feature is good.

**Comment by gerhardol** [comment]
This is the same in 2 as in 3: paths and arguments are fixed

**Comment by RussKie** [comment]
Hopefully I'll get to it in the future.
