### ISSUE TITLE
Can't create new virtual console!  - error in v3.00.00.4433

### ISSUE THREAD

**Issue by ev-mp** [gitextensions/gitextensions#5982]
Since this version is not marked as "Beta" I decided to submit this ticket

Environment:
- GitExtensions version: 3.0.0.4433
- GIT version:  2.20.1.windows.1
- OS version:  Win10 Build 1803 (RedStone4)
- .NET version: 

I've recently upgraded GitExtensions from 2.52 to 3.00 and  now, when I close and reopen any existing repo the following error pops-up when switching to the git console tab.
**Disclamer** -during the process I also had to upgrade git from 2.18 to 2.20.

![image](https://user-images.githubusercontent.com/17897861/50385220-9ab98f00-06da-11e9-9136-716df1d5f6c7.png)

And the only way for me to work with this repo is currently to run a detached console window (`Menu->Tools->GUI Bash`).

Is there any method I can do to try to clean GitExtension database cache/temp files ?
I tried to refresh the /.git directory by "git gc" but the error is persistent.

BTW, - The new UI arrangement beside from looking up-to-date, also makes it much easier to navigate and present a comprehensive repo status.  Kudos!!

Update: once appeared in a certain repo- now this error also hit the other repos as well.... :(

**Comment by vbjay** [comment]
You need to update all submodules.

**Comment by vbjay** [comment]
Also use our issue template it is there for a reason.

**Comment by vbjay** [comment]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**

**Environment you encounter the issue:**


- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

**Did this work in previous version of GitExtensions (which)?**

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/50385816-e3a51f80-06a9-11e9-9eb7-171418a32658.png)
Gives you a copy button that gives you environment info.

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/wiki/How-To:-build-instructions

**Comment by vbjay** [comment]
```bash
git clean -d -x -f
git submodule foreach --recursive git clean -d -x -f
```

**Comment by vbjay** [comment]
Please comment instead of editing so we get notifications on your edits.

**Comment by ev-mp** [comment]
@vbjay, thanks for the info - I'll try to stick to those in future.

The environment I run is similar (actually identical) to the posted one:
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

As for the provided rectification steps: I followed the instructions, cleaned up the repo but the error is persistent and the git console is still not accessible.

The version I run is from the published [msi installer](https://github.com/gitextensions/gitextensions/releases/download/v3.00.00/GitExtensions-3.00.00.4433.msi) . Is there a way to enable and collect application log to facilitate the issue reproduction?

**Comment by ev-mp** [comment]
Hello @RussKie, apparently I wrote my post simultaneously to you, so I hadn't had a chance to review the referred issue before posting mine. Thanks for the info - it seem related and I'll definitely follow it up.

While reading that discussion I was puzzled along this line by @Maximus
>When you set ConEmuStartInfo.IsLog to true ConEmu would write advanced..

This setting is not part of the `GitExtensions.exe.config`, and I could not find a dedicate config for that setting - does it mean that in order to activate ConEmu log I need to build it from sources, is that the reason @vbjay added a link to it ?
Can you clarify ?

**Comment by vbjay** [comment]
Correct. If you debug it and get the same issue we can get details. It may be an issue with your os version or many other issues. You can even set breakpoints in the conemu project. Let us know what you find out.

**Comment by gerhardol** [comment]
If you using any other language than English, can you try testing with English?

**Comment by erlis** [comment]
I had the same issue and I solved it like this: 

1 uninstall ConEmu
2 Go to gitextensions settings **Detailed\Browse repository window** and change **the shell to run** to **cmd** instead of **bash** 
3 restart gitextensions
4 Do step 2 but now select **bash**, restart again and after that it's working for me
5 Install ConEmu 

I noticed that after uninstalling ConEmu, without doing step 2, I was getting the same error, indicating that ConEmu failed by the way  I had exactly the same version of ConEmu you are displaying 180131. When I did step 5 I installed a new version 190108. 

One of the steps did something that fixed the issue, and I don't know what was... 

Let me know if this helps!

**Comment by RussKie** [comment]
Thank you for the follow up, much appreciated.

**Comment by RussKie** [comment]
The latest available NuGet package is 18.6.26
https://www.nuget.org/packages/ConEmu.Core/18.6.26

**Comment by erlis** [comment]
I don't know why a nuget package. I installed ConEmu using chocolatey 

https://chocolatey.org/packages/ConEmu

there I see version: ConEmu 19.1.8.0

**Comment by vbjay** [comment]
I think I know what the issue is. ConEmu stores settings in the registry.  We use conemu as a nuget package to provide the consoles in the app.  You had a different version installed and you uninstalled conemu and then ran our program.  It probably read in invalid settings that messed with our version of conemu.  @erlis's fix solves the problem by forcing the settings to be rewritten, is my guess.

**Comment by ev-mp** [comment]
@erlis ,thanks you very much for the workaround!
Finally it allowed me to work normally with the new version.

**Comment by erlis** [comment]
I'm glad it helps!

**Comment by mnoreen** [comment]
I am experiencing this exact same issue w/ Git Extensions

GitExtensions version:  3.02.5232
GIT version: 2.20.1.windows.1
OS version: Windows 10 (10.0.17134.0)
.NET version: 4.7.3324.0

Is there a fix?

**Comment by RussKie** [comment]
There is workaround provided above, please try that.
Alternatively you could disable the ConEmu completely: _Settings > Use Console Emulator..._

**Comment by mnoreen** [comment]
I'm not really sure what the "workaround provided" is... Uninstalling and reinstalling ConEmu?  Actually, I don't know where ConEmu exists.  Besides GitExtensions, is that something Visual Studio would have installed?  It doesn't exist in my Add/Remove Programs list.  Do you mean just wholesale uninstall GitExtensions and reinstall it?  As I mentioned, my current workaround is just to open a separate bash window.  It just struck me as odd to get an error dialog when I clicked the Console tab.  I just think that would be something that should be resolved.

**Comment by illfated** [comment]
Yes, like vbjay said, ConEmu is a NuGet package that you probably need to remove and add again. This is usually managed via NuGet Package Manager in Visual Studio, although there could be more than one way of doing it (I don't know).

**Comment by RussKie** [comment]
We use console emulator (aka ConEmu) in the progress dialog and in the integrated console, that is accessible via the "Console" tab.
When you click "git bash" in the toolbar we open the native git bash.

ConEmu is a 3rd party package that we don't control but depend on. For some reasons unknown to us it fails for some users.

A workaround is to either update ConEmu locally or disable it completely.

**Comment by gerhardol** [comment]
https://ci.appveyor.com/project/spdr870/gitextensions-f0pvf/builds/23163864/artifacts

Can someone with the problem try the portable package with the latest ConEmu version?
