### ISSUE TITLE
Empty/exception when reseting to a remote branch, complaining about the Commit Date < min UTC DateTime

### ISSUE THREAD

**Issue by EbenZhang** [gitextensions/gitextensions#5984]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When resetting to a remote branch, the dialog shows empty/incorrect commit detail in negative time zone, or exception positive time zone.

![image](https://user-images.githubusercontent.com/596334/50390088-896d9280-076d-11e9-8b09-2f27fcdd74e9.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Select a remote branch from the left branch tree panel
- Right click and select the `Reset` menu item

**What is the expected behavior?**

It should show the correct commit details and without exception.

**Environment you encounter the issue:**

Got from master branch build: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/21166113/artifacts

- Git Extensions 3.01.00.4553
- Build e5878bcf851745ccb52b8b6578d0794cbecda400 (Dirty)
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Updated: Checked release 3.0.x, it doesn't work either.

**Comment by EbenZhang** [comment]
The branch was chosen randomly. It happens to any branch.

**Comment by RussKie** [comment]
when I tried to reset on a remote branch, it crashed
![image](https://user-images.githubusercontent.com/4403806/50414146-ef3e4500-0867-11e9-92aa-0b2aaf087460.png)

**Comment by gerhardol** [comment]
corrected in f1a6f01205d99c630587a8180ecd79ec0e8c5c5b and #5985
