### ISSUE TITLE
Left Pane Submodules: show top module?

### ISSUE THREAD

**Issue by amaiorano** [gitextensions/gitextensions#5988]
Hello team,

I want to have another design discussion related to the Submodule left pane feature #5569, but since the aforementioned issue is rather long, and there's already a design discussion on that thread about double-click behavior, I decided to open a new issue for this one.

The design topic is whether to show the top-most module in the left pane or not. I have implemented this feature ([on my fork here](https://github.com/amaiorano/gitextensions/commits/amaiorano/left-pane-submodules-show-top-module)), and my own opinion is that we should show the top module, as it solves a lot of problems I was having without it. However, I will present the two here, and try to list the positives and negatives related.

For the purpose of this discussion, I will refer to the two solutions as:
1. Solution A: no top-most module shown in tree
2. Solution B: top-most module shown in tree

Let's start with screenshots:

Solution A (without top-most module):
![image](https://user-images.githubusercontent.com/6893883/50424696-a28e4600-0836-11e9-8552-6c8385615515.png)

Solution B (with top-most module):
![image](https://user-images.githubusercontent.com/6893883/50424707-dff2d380-0836-11e9-83e5-1a7a172b628b.png)

So the main difference is the addition of the node, "gitextension2 [master]", which is bolded because it's the active module. I also named the tree root node "Modules" instead of "Submodules", as I think it would make more sense in this context, but that's open to discussion as well.

Having this extra node solves a few problems I was having without it. Basically, it mainly revolves around the problem of allowing the user to perform actions on the top-most module. A's "Submodules" tree root node had a sort of double meaning: it was both the place for "actions on the current module", as well as for "actions on the top-most module". I will give examples:

Say you've opened a submodule's submodule (so 2 levels deep). If you would right-click the Submodules node before, you'd get:

![image](https://user-images.githubusercontent.com/6893883/50424845-57296700-0839-11e9-8be9-83989a75140a.png)

Things to note:

* You can open the Top-most or the Super project from this menu. These exist mainly because there was no easy way from the tree to open the top-most module (all other modules can be opened directly from the tree). In B, we can now open the top module like any other. Note that the "Open Super" is only useful when a direct child submodule of the top module is open.  Also note these two menu items could be made context actions of the currently selected module in A.

* Manage... : this only applies to the currently open module, as it opens the Manage Submodules dialog (also available from the menu: Repository -> Submodules...). I would have wanted this to be a context action only on the currently active module, but since in Solution A, we don't see the top module, I had to put it on the Submodules context menu. This is weird, and in Solution B, I made it a context action of the actively selected module (screenshots below).

* Update All and Synchronize All: Like "Manage", these also only apply to the current module. Again, there is weirdness here. In effect, "Update All" is completely redundant when a submodule is already open, since you can right-click that module and select "Update". The only reason this option is there on the Submodules node is so that when the top module is open, you can update it's submodules. We _could_ make it so that this option is only available when the top-most module is the active one, but it's still weird because we treat the Submodules node as representing the top-most module in this context. In Solution B, this problem is solved, again, because you can simply right-click the top-most module and select Update at any time. As for Synchronize, this is just like "Manage" in that in Solution B, it's only available by right-clicking the currently open module.

So in Solution B, the root node is named Modules, and right-clicking that node gives no special context actions:

![image](https://user-images.githubusercontent.com/6893883/50425363-7aa4df80-0842-11e9-82e9-ee48acb245a0.png)

Instead, right-clicking on the active module gives you the following:

![image](https://user-images.githubusercontent.com/6893883/50425366-99a37180-0842-11e9-9531-5163ca200e1d.png)

And right-clicking a non-active module gives (as in Solution A):

![image](https://user-images.githubusercontent.com/6893883/50425371-ade76e80-0842-11e9-8830-645860351104.png)

So here's a little breakdown of the positives/negatives of each option as I see it:

Solution A:
\+ Flatter tree
\- Inconsistency around actions on top module vs submodules
\- If top module is active, there's no bolded node

Solution B:
\+ No need for Open Top/Super project option
\+ No need for context menu on top-most Modules node
\+ Consistent module actions for top module vs submodules
\+ Easy to see which is the active module as there's always a bolded node
\- Extra node for top-most module makes the tree less flat

If you would like to try these out, you can checkout my branches on my fork, or if you like, I can provide two zips to compare the two right here. Let me know!

**Comment by RussKie** [comment]
From the description I prefer B

**Comment by vbjay** [comment]
B.

**Comment by amaiorano** [comment]
> (I want to flatten the tree by giving full internal references like "Externals/Git.hub", but that is mentioned separately in [#5569 (comment)](https://github.com/gitextensions/gitextensions/issues/5569#issuecomment-449157937)).

@gerhardol I think I finally understood what it is you would like. You would rather we don't have any "folder" nodes in the tree. So remove the highlighted node:

![image](https://user-images.githubusercontent.com/6893883/50453412-69290980-090e-11e9-9651-8bdd5b9899e4.png)

... and conemu-inside would display the name "Externals/conemu-inside [no branch]", right?

**Comment by amaiorano** [comment]
Great, so far everyone likes Solution B - adding the root module to the tree, and renaming it "Modules" rather than "Submodules". Haven't yet heard from @drewnoakes, but I believe he would want this option as well, having made a similar suggestion in #5569. I'll just wait for his thumbs up, and we can close this discussion.

**Comment by gerhardol** [comment]
> and conemu-inside would display the name "Externals/conemu-inside [no branch]", right?

correct

> and renaming it "Modules" 

I do not agree, the Git concept is called submodules as in a separate discussion. 
_Submodules and superprojects_ is too long

**Comment by vbjay** [comment]
With his view of parent and submodules, naming it modules is correct.

**Comment by gerhardol** [comment]
Missing:
_Submodules and superprojects_

"Module" would be a GE specific concept nothing mentioned in Git documentation. (The closest is the .gitmodules file). The concept is called submodules, superprojects are mentioned in the documentation.
A new name is not completely unthinkable, you never work with superprojects so the need in the official documentations is lower. I have seen a number of other names like containers and components.

I still propose _Submodules_, with the current repo in bold.

**Comment by RussKie** [comment]
I don't have a strong preference

**Comment by drewnoakes** [comment]
> Haven't yet heard from @drewnoakes, but I believe he would want this option as well

Sorry yes, I took some time off over the holidays. I prefer B as you say 👍 

I'm also in favour of the name "Modules" as it's simple, relevant and clear. The git source code uses this name for submodules in a few places (`submodule.c`, `submodule--helper.c`). Other ideas include "Projects" (a term used in the `git submodules` docs), "Structure", "Hierarchy", "Project structure"...

Can we use a different icon for the root module? The submarine makes it feel like it's a sub-something, but it's not. Perhaps use the general repo icon (folder with GE logo inside).

**Comment by amaiorano** [comment]
> @amaiorano have you had a look at icons provided by [Yusuke Kamiyamane](http://p.yusukekamiyamane.com/)? Perhaps you could find something we could use...

That is a nice collection of icons! Thing is, the real problem is that I'd need an icon for each of the submodule status states that we currently show. Like, this is the code in FormBrowse to set the submodule status icon:

```csharp
            Image GetSubmoduleItemImage(DetailedSubmoduleInfo details)
            {
                if (details.Status == null)
                {
                    return Images.FolderSubmodule;
                }

                if (details.Status == SubmoduleStatus.FastForward)
                {
                    return details.IsDirty ? Images.SubmoduleRevisionUpDirty : Images.SubmoduleRevisionUp;
                }

                if (details.Status == SubmoduleStatus.Rewind)
                {
                    return details.IsDirty ? Images.SubmoduleRevisionDownDirty : Images.SubmoduleRevisionDown;
                }

                if (details.Status == SubmoduleStatus.NewerTime)
                {
                    return details.IsDirty ? Images.SubmoduleRevisionSemiUpDirty : Images.SubmoduleRevisionSemiUp;
                }

                if (details.Status == SubmoduleStatus.OlderTime)
                {
                    return details.IsDirty ? Images.SubmoduleRevisionSemiDownDirty : Images.SubmoduleRevisionSemiDown;
                }

                return details.IsDirty ? Images.SubmoduleDirty : Images.FileStatusModified;
            }
```

So that's 11 icons. Basically, we'd need 11 similar icons, except for the top module only. Not sure that's a good idea...

**Comment by RussKie** [comment]
I back track on my suggestion... 😞

**Comment by drewnoakes** [comment]
We can programmatically synthesise icons, with a base and overlay. In such a case, you'd need one extra icon.

**Comment by amaiorano** [comment]
> We can programmatically synthesise icons, with a base and overlay. In such a case, you'd need one extra icon.

That makes sense. I foresee more photoshopping in my near future ;)

**Comment by drewnoakes** [comment]
> I foresee more photoshopping in my near future ;)

Sounds like you're the person for the job! It might come in useful in a few places. I think the icons @RussKie mentioned can provide some overlays (plus/minus/arrows/etc).

**Comment by amaiorano** [comment]
Don't get your hopes too high, though ;) I'm not an artist; but am fairly comfortable modifying and manipulating existing images. The extent of my Photoshop skills for the past 5 years has been limited to making Christmas cards to send out to family :)

**Comment by vbjay** [comment]
My girlfriend is a Digital Effects and Animation graduate. I could throw some design stuff her way if it is needed.

**Comment by RussKie** [comment]
Jay that would be great, if she is able and willing to help.
I'd like to get the dashboard design (the logo and colour palette)
finalised. I have some psds with mocks to share, if necessary.

**Comment by vbjay** [comment]
Yes.  Please send me the psd's and I can get them to her.  I'll let her start the convo and get ger setup on github soon.

**Comment by RussKie** [comment]
Awesome, will do it over the weekend
Thanks heaps!

**Comment by gerhardol** [comment]
Implemented
