### ISSUE TITLE
Not refreshing tree after push

### ISSUE THREAD

**Issue by AlexAtSpark** [gitextensions/gitextensions#5998]
Hello. Having issue with not refreshed tree after push to github. 

STR: 
1. commit some code
2. push it to gihub

AB: tree stays the same, remote branch is not on the same line with local line
EB: tree should be updated and remote branch should be in the same place with local branch

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I constantly push to GH and haven't observed the issue.

Is it happening to all repos or only a specific repo?
Is there anything unusual in the commands log (F12)?

**Comment by AlexAtSpark** [comment]
I don't know about the unusual things, but it happened again with new branch pushing
screening latest commands from F12

http://take.ms/mDr4f

**Comment by AlexAtSpark** [comment]
And it worked correctly on other repository
http://take.ms/hD8mrG

**Comment by amaiorano** [comment]
Hi @AlexAtSpark, can you answer a few questions to help us understand the issue?

* You said this happens with one of your repos, but not the other. Is it 100% reproducible on the former repo?

* When the tree doesn't refresh correctly, do you manually refresh (F5 or pressing the refresh button), and then it renders correctly?

* Would you mind sharing the output of "git config --local -l" for both repos (the one that fails to refresh, and the one that works).

* If you use Visual Studio, would you mind attaching it to GitExtensions.exe process and sending the output captured from it for both the repo that doesn't work, and for the one that does? If you don't have or want to use Visual Studio, you can also use [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) to capture debug output of all processes that are running.

The more info you can give us, the more likely we are able to understand and fix this problem. Thanks!

**Comment by RussKie** [comment]
Closing due lack of follow up
