### ISSUE TITLE
Decrease priority for background jobs

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#6000]
**Do you want to request a *feature* or report a *bug*?**
feature 

**What is the current behavior?**
"Background" commands run with the same priority as UI related commands

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Open/refresh a repo in  Browse could be quicker, occasional slowdowns.

**What is the expected behavior?**
The UI should be ready as soon as possible

The background Git processes started when a repo is opened is less important than the commands required for instance for the revision graph.

#5983 adds "--no-optional-locks"  to most background commands. Those are a candidate to decrease thread priorities (will that make a difference?) and the process priority for the Git process started. 
The following is a hack to decrease the priority. (A full change will affect IGitModule etc too).
https://github.com/gerhardol/gitextensions/commits/test/process-priority

I do not have any repos that will benefit much from this right now (GE repo is too small):
 * Big repos where git-status is slow
 * git-stash is slow
 * Many submodules
 * Many superprojects

**Environment you encounter the issue:**
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
no

**Comment by vbjay** [comment]
So the question is will the lower priority make it so the command is basically swallowed. I can see it possibly bringing back our friend the git commit button being out of sync from actual status just like if there is a stuck git process.

**Comment by gerhardol** [comment]
Before --no-optional-locks the commit count locked the index. #5983 adds this flag to most background commands (even if very likely nothing is changed). 

I have seen lock in form commit with git 2.19 though, believe that is caused by Git. 

This sets lower prio to what is not required to start working in browse so so the cursor busy time is reduced.
