### ISSUE TITLE
Left panel - show inactive remotes

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#6015]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

The left panel displays the currently configured remotes.
GE has a feature that allows to disable a remote but keep the information available to the app.
![image](https://user-images.githubusercontent.com/4403806/50547097-31f88680-0c87-11e9-94f3-df067793f635.png)

**What is the expected behavior?**

Display disabled remotes in the tree, if any.
The node that contains the inactive remotes should be collapsed by default.

It could look like:

```
+ Branches
- Remotes (active)
  |- upstream
  |- fork
- Remotes (inactive)
  |- john
  |- jim
  |- jack
```
or
```
+ Branches
- Remotes
  |- active
  |  |- upstream
  |  |- fork
  |- inactive
  |  |- john
  |  |- jim
  |  |- jack
```

A context menu should allow to 
* enable an inactive remote,
* disable an active remote

**Comment by gerhardol** [comment]
Useful for repo maintainers, but if this decreases the hurdle also for occasional developers to try out feature branches, much is gained.

An inactive remote can probably not list any branches. Should double click activate? Should double click of normal remotes deactivate then? If so should handling be as @amaiorano proposed for submodules?

The alternative to tabs is to be able to reorder in the left panel and keep the expansion state. For instance, I want submodules on the top.

Remotes should probably be on the same level as Branches (I would prefer to have inactive separate myself but have no good motivation).

**Comment by vbjay** [comment]
I wouldn't want double click to alter the active/inactive state of my remote.  That would drive me BONKERS.  Instead, open remote dialog with that remote selected.

Instead of separate nodes, Use different icons and maybe a tooltip to say active/inactive.

**Comment by amaiorano** [comment]
I didn't even know about this feature. Are disabled remotes a Git feature, or a GE feature?

In any case, given the current implementation, it would be easier to implement as:
```
- Remotes
  |- active
  |  |- upstream
  |  |- fork
  |- inactive
  |  |- john
  |  |- jim
  |  |- jack
```

Another option would be to not bother with "active", and have only the "inactive" parent node, so like:

```
- Remotes
  |- upstream
  |- fork
  |- inactive
  |  |- john
  |  |- jim
  |  |- jack
```

And as you said, in all cases, inactive would begin collapsed.

**Comment by gerhardol** [comment]
> I didn't even know about this feature. Are disabled remotes a Git feature, or a GE feature?

Really GE, inactive remotes are hidden in .git/config so Git do not care about them
So if I do not want to see your changes and deactivating them, I have a section like:

```
[-remote "amaiorano"]
        url = git://github.com/amaiorano/gitextensions.git
        fetch = +refs/heads/*:refs/remotes/amaiorano/*
```

> Another option would be to not bother with "active", and have only the "inactive" parent node, so like:

Better

**Comment by RussKie** [comment]
> Useful for repo maintainers, but if this decreases the hurdle also for occasional developers to try out feature branches, much is gained.

I use this feature in many repos, as a team lead I need to check other devs' work.

> I didn't even know about this feature. Are disabled remotes a Git feature, or a GE feature?

It is a GE-specific feature (#3615).

> I wouldn't want double click to alter the active/inactive state of my remote. That would drive me BONKERS. Instead, open remote dialog with that remote selected.

Agree, I wouldn't like it either. Personally I would like to have the following options:
* Manage remotes... (_default, double click_)
* Activate the remote (_if inactive_)
* Activate the remote and fetch (_if inactive_)
* Deactivate the remote (_if active_)

**Comment by amaiorano** [comment]
So I started looking into this, and trying out the disable/enable remotes feature, and the first thing I noticed is that removing a remote has the side effect of also removing all of its refs (.git/refs/remotes/<remote_name> is gone), but enabling it again does not fetch refs from the remote. As a result, after disable/enable, you cannot perform any actions on the remote until you've fetched from it (e.g. you can't check out a branch in the checkout pulldown, etc.).

Should I try to fix that? If we don't auto-fetch enabled remote refs, then after enabling a remote, you'd have to remember to fetch it for it to appear in the left panel.

**Comment by gerhardol** [comment]
> Should I try to fix that?

Leave it for now in this issue.
If you believe you have a solution, please discuss it.

**Comment by amaiorano** [comment]
Okay, I'll look into it some more. Having the left panel list remotes without branches isnt currently supported, so that's what needs to be added. Then we can provide the context actions you want, @RussKie. Also note that we'd want to show active remotes with no branches as well, and allow fetching on them. Should be doable.

**Comment by RussKie** [comment]
Worth noting, that I often enable/disable remotes in batches (e.g. reviewing several PRs from different contributors), so in my case I need both "activate" and "activate+fetch" options.

**Comment by amaiorano** [comment]
As I continue exploring, it looks like GitModule.GetRefs has a bug in it. If you pass in "tags: false, branches: true" to only retrieve branches, it will not return remote branches, only local ones. However, if you pass in "tags: true, branches: true", you'll get local and remote branches (and tags). It boils down to the fact that it uses different ways to get the refs:

```csharp
        public IReadOnlyList<IGitRef> GetRefs(bool tags = true, bool branches = true)
        {
            var refList = GetRefList();

            return ParseRefs(refList);

            string GetRefList()
            {
                if (tags && branches)
                {
                    return _gitExecutable.GetOutput("show-ref --dereference");
                }

                if (tags)
                {
                    return _gitExecutable.GetOutput("show-ref --tags");
                }

                if (branches)
                {
                    return _gitExecutable.GetOutput(@"for-each-ref --sort=-committerdate refs/heads/ --format=""%(objectname) %(refname)""");
                }

                return "";
            }
        }
```

When only branches is wanted, the function uses for-each-ref but specifies only the "refs/heads/" path, so we don't get the refs from "refs/remotes/". This is surprising, and should be fixed, but there are a few calls to this function that pass in "tags: false, branches: true" that we need to make sure work as expected. Or perhaps we need to extent the API to accept another bool parameter "remotes".

**Comment by gerhardol** [comment]
Check master for update GetRefs), changed just recently
But remotes: should be added too, it seems. (Maybe using a Mode as in https://github.com/gitextensions/gitextensions/pull/6002)

**Comment by RussKie** [comment]
> it looks like GitModule.GetRefs has a bug in it

Please open a new issue so we can track it separately.

**Comment by amaiorano** [comment]
Screenshot time! Here's the current progress:

Enabled remotes without branches, as well as disabled remotes are now displayed:

Initially "Disabled" is collapsed:
![image](https://user-images.githubusercontent.com/6893883/50719282-2d0d4b80-1068-11e9-9c8d-7469aa2fd3c1.png)

If you expand it:
![image](https://user-images.githubusercontent.com/6893883/50719290-34345980-1068-11e9-9f78-4d962c842681.png)

One thing to note, "fsharp" has no children. It is a remote with no fetched branches (yet). Also note that it's not positioned alphabetically -- normally it would be in between "amaiorano" and "origin". I will fix that soon.

Right-clicking an enabled remote:

![image](https://user-images.githubusercontent.com/6893883/50719316-69d94280-1068-11e9-876f-826d2b7f2353.png)

Right-clicking a disabled remote:

![image](https://user-images.githubusercontent.com/6893883/50719322-7493d780-1068-11e9-9a7f-c6242b38dc89.png)

I'm not sure what to do about icons. I can probably find something for Enable and Disable, but I'm not quite sure what to use for "Enable and fetch".

Performing "Enable", "Enable and fetch", and "Disable" all work as expected. Enable/Disable will refresh the UI. Enable and fetch shows the fetch dialog, and then the UI is refreshed. Works really well!

**Comment by amaiorano** [comment]
If you want to try my changes, check out the branch on my fork:
https://github.com/amaiorano/gitextensions/tree/amaiorano/left-panel-remotes-improvements

**Comment by RussKie** [comment]
Good stuff!

I suggest using the same terminology as we use in the Remotes dialog: "Activate" and "Deactivate" (or change the dialog to match the left panel).
Instead of "Disabled" - perhaps "Inactive"?
I also suggest use the same icons for the context menu as used in the dialog.
I don't particularly mind which way we chose to go as long as we are consistent.

As an observation - I think we need to rename "Manage remotes" to "Manage remotes..." to indicate this command opens a dialog

**Comment by RussKie** [comment]
Looks pretty cool, though inactive remotes aren't sorted:
![image](https://user-images.githubusercontent.com/4403806/50720165-e8cb8b00-10fb-11e9-92cc-679ae62c8470.png)

We could probably enhance the UX - when choosing to manage a remote, the dialog should pre-select the chosen remote

**Comment by amaiorano** [comment]
> I suggest using the same terminology as we use in the Remotes dialog: "Activate" and "Deactivate" (or change the dialog to match the left panel). Instead of "Disabled" - perhaps "Inactive"?

Done. In code, it's "enable/disable", but for the UI, it's "active/inactive". Decided to just remain consistent.

> I also suggest use the same icons for the context menu as used in the dialog. I don't particularly mind which way we chose to go as long as we are consistent.

Done, though I don't have a special icon for "Activate and fetch", so current using the eye open icon for both:

![image](https://user-images.githubusercontent.com/6893883/50729267-eb7eae00-1104-11e9-8ea3-07d0a2f56353.png)

Would probably need an eye open icon with the blue down arrow that we use for fetch.

> As an observation - I think we need to rename "Manage remotes" to "Manage remotes..." to indicate this command opens a dialog

Yep, had noticed that too. Fixed as well.

Branch has been updated if you want to try it now.

**Comment by amaiorano** [comment]
Can you tell me how to add icons in GE? I'll give it a shot as well.

**Comment by RussKie** [comment]
There are few ways
- you can do it via the VS Designer, or
- manually

I often do it manually, the designer tends to make "noisy" changes.

If you search for any referensed image you should be able to trace it all
the way through.
- drop a file into Icons folder
- add to resources files (2 places)
- reference the image
- celebrate 😎

**Comment by RussKie** [comment]
Please have a look at 4176d05efd3477e975340d864b8c728d3bda2908 as an example, that's pretty much the extent of changes when adding or modifying an image

**Comment by RussKie** [comment]
Found an annoyance: whenever deactivating or activating a remote the graph refreshes and the "Remotes/Inactive" node folds.
Is it difficult to retain the state across refreshes?

**Comment by amaiorano** [comment]
> Is it difficult to retain the state across refreshes?

I can easily special case it for the Inactive folder. Ideally, though, we'd remember the expanded state of the entire tree and attempt to reapply it. Need to think about the best way to do that. I want to wait, though, until my left panel pubsub change is merged, as it will affect how we approach this. But in the meantime, I'll special case this one.

**Comment by amaiorano** [comment]
> Please have a look at 4176d05 as an example, that's pretty much the extent of changes when adding or modifying an image

Thanks!

**Comment by RussKie** [comment]
Your icon looks way better than mine :+1:

**Comment by amaiorano** [comment]
> Your icon looks way better than mine 👍

Thanks :) Have a little photoshopping experience thanks to my game dev background ;)

**Comment by amaiorano** [comment]
Okay, I just pushed a commit that adds the ability for the left panel to remember and re-apply the expanded state of nodes. This change is generic, and not really required for this specific change (show inactive remotes and remotes without branches). If you want, I can split this out into its own PR. Let me know. If you want to see the commit: https://github.com/amaiorano/gitextensions/commit/e18b7d98eb5706fa9d2000078796e55a583776bc

**Comment by amaiorano** [comment]
> Most important is that it is consistent, I suggest you make a choice (it is likely the initial implementation that sticks).

Okay, I'm going to bring in the change to disable expand/collapse on double-clicking nodes in the left panel. This will apply to all nodes.

**Comment by RussKie** [comment]
Love it!

**Comment by amaiorano** [comment]
> Love it!

Great! Will create PR soon.
