### ISSUE TITLE
[Bug]  Custom stash names not working

### ISSUE THREAD

**Issue by thewholuver94** [gitextensions/gitextensions#6016]
**Do you want to request a *feature* or report a *bug*?**
Feature please

**What is the current behavior?**
Stashes are assigned automatic, human non-readable names.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Not a bug, but just create a new stash

**What is the expected behavior?**
I would love if upon creating & managing stashes, I could give my stashes custom human readable names. This would help me tremendously in managing my stashes so I can recall which stash I need at any moment without exploring the files & file changes.
 
**Environment you encounter the issue:**
GitExtensions v3 (latest release)

- GitExtensions version: 3.00.00.4433
- GIT version: 2.20.1.windows.1
- OS version: Windows NT 10.0.15063.0
- .NET version: 4.7.3260.0

**Did this work in previous version of GitExtensions (which)?**
Not that I'm aware of

**Comment by gerhardol** [comment]
Already exists

![image](https://user-images.githubusercontent.com/6248932/50547447-d81d9f80-0c39-11e9-9ca3-5a926aaf97a4.png)

A related feature is to view stashes in the revision graph 
![image](https://user-images.githubusercontent.com/6248932/50547459-16b35a00-0c3a-11e9-98bf-34d45fb8d71d.png)

**Comment by thewholuver94** [comment]
Hi, thanks for pointing this out to me. It looks like this isn't working as I expected. Why don't my changes stick?

![image](https://user-images.githubusercontent.com/19075463/50547596-44ea6700-0c45-11e9-93fd-fed98b2b86ce.png)

**Comment by thewholuver94** [comment]
Also, when the bug appears, the stashed files are not only not reverted, but they are staged for commit! So when a user stashes changes, and then goes to commit, those files he stashed are now staged...

**Comment by vbjay** [comment]
Here is the line that needs to be fixed.  
https://github.com/gitextensions/gitextensions/blob/7bfc7ae9d71bbf4cdf66cebb68c62ccf25bf873d/GitCommands/Git/GitCommandHelpers.cs#L324

Make it be -m MessageValueHere

**Comment by thewholuver94** [comment]
I'd be very happy to contribute the change, but I will need to do it in a couple hours & may need a bit more of a walkthrough since it's my first time pushing to a public project.

**Comment by RussKie** [comment]
Thank you Jay. This is why I want to see tests no matter how trivial a
piece of code is...

Noah, if you're going to fix it please make sure to add a test please.

**Comment by gerhardol** [comment]
...and change the title of the issue (no need to change the description).

**Comment by vbjay** [comment]
Hold up.  Only use -m if it is push

push [-p|--patch] [-k|--[no-]keep-index] [-u|--include-untracked] [-a|--all] [-q|--quiet] [-m|--message <message>] [--] [<pathspec>…​]

save [-p|--patch] [-k|--[no-]keep-index] [-u|--include-untracked] [-a|--all] [-q|--quiet] [<message>]

So here is what you do.  replace the message line with this

```c#
return new GitArgumentBuilder("stash")
            {
                { isPartialStash, "push", "save" },
                { untracked && GitVersion.Current.StashUntrackedFilesSupported, "-u" },
                { keepIndex, "--keep-index" },
                { isPartialStash, "-m" },
                message.QuoteNE(),
                { isPartialStash, "--" },
                { isPartialStash, selectedFiles }
            };
        }
```

**Comment by vbjay** [comment]
The staged files is only because the stash failed.  A stash is just a special type of commit.  So the commit failed because the args were wrong.  That will be fixed when the args are fixed.

**Comment by thewholuver94** [comment]
Thanks for all your help guys. 

I'm super interested in contributing this fix, and thanks for sending me to the right place to do it. I will have to do it after working hours here though.

**Comment by vbjay** [comment]
Even better

If message is empty don't include it.  

```c#
  { isPartialStash && !message.IsNullOrEmpty(), "-m" },
  { !message.IsNullOrEmpty(), message.Quote() },
```

**Comment by vbjay** [comment]
Glad you found it.  

@RussKie on the tests, we really need a faux repo that we can start from and run the commands.  Maybe we could use $temp% or a submodule called TestRepo or some other place.  We could have a GetRandomText function that just generates a small set of random text and write it to a specified file.  Then we could write a git init script that turns off signing for this repo so that tests aren't halted waiting for a signature.  (I have to open my gpg4win key every time I run tests and the key isn't open.)

**Comment by gerhardol** [comment]
> we really need a faux repo that we can start from and run the commands

That are tests that also I support (not just comply to), will test the behavior. But there are complications, for instance Git version dependencies.

**Comment by thewholuver94** [comment]
Hey guys I actually had a free few minutes so I tried to apply the fix.

I did my best to follow the contributers guidelines. I forked the project, committed the changes by me, initiated a pull request, made a second commit (add empty message check), and didn't create another pull request.

is there anything else I need to do? Can someone check that I did it correctly? Thanks

**Comment by vbjay** [comment]
WHat's the pull request #

**Comment by vbjay** [comment]
You should see something like this

![image](https://user-images.githubusercontent.com/3629489/50548036-e5279800-0c13-11e9-937b-54accc285036.png)

Although you will select your fork/branch.

**Comment by vbjay** [comment]
Make sure you alter the fixes line to point to this issue 6016

Fixes # 6016 without the space between the # and number.

**Comment by vbjay** [comment]
If you don't have an upstream remote, create one

![image](https://user-images.githubusercontent.com/3629489/50548193-65e79380-0c16-11e9-9cc8-69bf0129d2f1.png)
![image](https://user-images.githubusercontent.com/3629489/50548197-87e11600-0c16-11e9-95b1-cbdea08f18e1.png)

**Comment by thewholuver94** [comment]
Ok I think I did it correctly now. Thanks :-)

**Comment by vbjay** [comment]
👍   You got it.  When it gets merged, this issue will close because of that fixes line.

**Comment by thewholuver94** [comment]
I tremendously appreciate the guidance and opportunity you guys gave me! Thank you.

**Comment by RussKie** [comment]
> @RussKie on the tests, we really need a faux repo that we can start from and run the commands.

We have integration-style tests where we generate a git repo
https://github.com/gitextensions/gitextensions/blob/89897d085a60823f72ba5045fad6d84dd02bc58b/UnitTests/CommonTestUtils/GitModuleTestHelper.cs#L5-L12
