### ISSUE TITLE
Feature: Make installer source files that exist in Gitextensions\bin\release... to use Gitextensions\bin\release files

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#6019]
**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Installer sources from project output folders when a copy of the file exists in Gitextensions\bin\release folder.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**What is the expected behavior?**
Source files from Gitextensions\bin\release if at all possible.
**Environment you encounter the issue:**
Master

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**

Rename as html and open in browser.  
[Installer Script File sources.html.txt](https://github.com/gitextensions/gitextensions/files/2717598/Installer.Script.File.sources.html.txt)
Sample entries from this file.  
![image](https://user-images.githubusercontent.com/3629489/50552487-542bdd80-0c62-11e9-86bf-123f0e3ac3fb.png)

[linqpad ](https://www.linqpad.net/) script that generated the above output
```vb

Sub Main
	Dim doc = XElement.Load("D:\git\gitextensions\Setup\Product.wxs")

	Dim installerFiles = doc...<File>.Select(Function(nd) New With {.Node=nd,.Path=io.Path.GetFullPath(IO.Path.Combine("D:\git\gitextensions\Setup\",nd.@Source.Replace("$(var.Configuration)", "Release")))})
	'installerFiles.GroupBy(Function(f) io.Path.GetExtension(f.Path)).Dump("Installer files By extension")


	Dim installerDetails = installerFiles.Select(Function(f) New With {.Node=f.Node,.ParentNode=f.Node.Parent,.Info = New io.FileInfo(f.Path), .Hash = Sha512Hash(f.Path)})


	Dim releaseFiles = IO.Directory.EnumerateFiles("D:\git\gitextensions\gitextensions\bin\Release\", "*.*", searchOption.AllDirectories)
	'releaseFiles.GroupBy(Function(f) io.Path.GetExtension(f)).Dump("Release files By extension")

	Dim releaseDetails = releaseFiles.Select(Function(f) New With {.Info = New io.FileInfo(f), .Hash = Sha512Hash(f)})

Dim matched = From ReleaseFile In releaseDetails
Group Join InstallerFile In installerDetails On InstallerFile.Hash  Equals ReleaseFile.Hash Into MatchedInstallerFiles = Group
Where MatchedInstallerFiles.Any(Function(f) Not f.Info.FullName.StartsWith("D:\git\gitextensions\GitExtensions\bin\Release\",StringComparison.CurrentCultureIgnoreCase))

matched.Select(Function(f) New With {.ReleaseFile=f.ReleaseFile.Info.FullName, .ReleaseHash=f.ReleaseFile.Hash, .MatchedInstallerFiles=f.MatchedInstallerFiles}).Dump("Installer files that also exist in GitExtensions\bin\Release\")






End Sub

' Define other methods and classes here

Function Sha512Hash(path As String) As String
	Static sha As System.Security.Cryptography.SHA512 = System.Security.Cryptography.SHA512CryptoServiceProvider.Create()
	If Not file.Exists(path) Then Return String.Empty
	Using fstream As New IO.FileStream(path, FileMode.Open, FileAccess.Read)
		Return String.Join("",sha.ComputeHash(fstream).Select(Function(b) b.ToString("X2")))
	End Using

End Function

```
![image](https://user-images.githubusercontent.com/3629489/50552509-ba186500-0c62-11e9-81c9-54f2e936011e.png)

**Comment by gerhardol** [comment]
Closed in #6102 for release-3.00 that has been merged to master
