### ISSUE TITLE
Discussion: telemetry - what and how?

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#6021]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

We have literally no telemetry data besides that reported to us via issue reports on GH. We have no tangible data on OS distribution, most used or least used forms and controls.

**What is the expected behavior?**

I'd like to have an opt-in telemetry that would capture **anonymous** GE-specific data such as but not limited to:
* OS version/flavour/bitness
* number of app-launches since last report
* number of form/control launches since last report
* git version
* number of recent/favourite apps (just numbers no paths/names/etc)

This can be facilitated via cloud offerings which I think can be done in a very cost-effective manner.
The way I envisage it (with relatively limited knowledge of current tech offerings) could be: 
* setup an AWS or Azure account
* have a small database (rdb or nosql)
* have a lambda function that receives telemetry data and inserts into the database
* have a lambda function that would help dealing with possible abuse (e.g. dos attacks)
* setup a CloudFlare account that would limit requests by IP, similar to [what Troy Hunt did for his HIBP site](https://www.troyhunt.com/serverless-to-the-max-doing-big-things-for-small-dollars-with-cloudflare-workers-and-azure-functions/)

The same architecture can be used for bug reports as well - we could have a lambda function that could post a new issue on GH with stack traces and other relevant info.

Thoughts?

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/50563431-c21be780-0cea-11e9-9b66-c12335be2b0d.png)
![image](https://user-images.githubusercontent.com/3629489/50563444-dcee5c00-0cea-11e9-81bd-1cffe4f9e68a.png)

**Comment by RussKie** [comment]
Whilst I don't have experience with it, from what I read I don't think it offers what I'm after.
Looking at the [Azure Monitor pricing](https://azure.microsoft.com/en-au/pricing/details/monitor/) the data is only retained for 30 days, where as I'd like to have a longer retention.
