### ISSUE TITLE
Commit-window placed in background when "Commit message" or "Options" dropdown button is clicked

### ISSUE THREAD

**Issue by Bejoscha** [gitextensions/gitextensions#6028]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
In the commit-dialog, pressing either the "Commit message" or the "options" drop-down menu button will bring the dialog-window into the background. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

- Open commit dialog

- Click either of the buttons:
![x](https://user-images.githubusercontent.com/6987920/50596406-8167ce00-0ea4-11e9-93ab-934419eebc19.jpg)

- The dropdown shows, but on the parent-window, not the commit-dialog-window:
![x2](https://user-images.githubusercontent.com/6987920/50596544-f3401780-0ea4-11e9-822a-f0e0f219da1e.jpg)

**What is the expected behavior?**

Same dropdown, but don´t hide the commit-dialog window.

**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2650.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**

Yes, as far as I remember. (2.51)

**Comment by Bejoscha** [comment]
@RussKie ConEmu? Sorry, can't follow. In any case. Very much to my own disappointment, I can not fully reproduce the issue today anymore, and I'm not aware of what changes I might have made in the meantime. :c(

**Comment by gerhardol** [comment]
Such issues occasionally occurs after using the Console
![image](https://user-images.githubusercontent.com/6248932/50658780-beae8780-0f9a-11e9-968b-662be3abc879.png)

The Console is using a separate project that the GE maintainers do not have knowledge about the inner workings and since there are no reliable way to reproduce, it cannot be debugged.

It has been discussed if the Console should be removed due to these issues.

**Comment by RussKie** [comment]
E.g.
* https://github.com/gitextensions/gitextensions/issues/3570
* https://github.com/gitextensions/gitextensions/issues/4401
* https://github.com/gitextensions/gitextensions/issues/4859
* https://github.com/gitextensions/gitextensions/issues/5551

Try disabling the ConEmu and see if that helps - https://github.com/gitextensions/gitextensions/issues/3570#issuecomment-284229149

**Comment by Bejoscha** [comment]
Thanks.

Indeed this seems to have been my issue as well. Now that you’ve pointed it out to me, it is also what makes the difference between being able to reproduced the bug or not.

If the ConEmu is enabled (which it was by default) and after I clicked on the “Console” tab, the following commit-dialog exhibits the issue.

If I just start GITExtensions and go to commit directly (i.e. never clicking the console tab), I don’t get the issue.

 

Turning ConEmu off as suggested also gets rid of the issue.

Topic closed then?

 

Bernhard

**Comment by vbjay** [comment]
@Maximus5. Thoughts?

**Comment by hit1205** [comment]
I have the same problem, this issue happens after I clicked the "Console" tab.
But, my ConEmu is disabled.

The issue still been there, even I enable and disable ConEmu again.

**Environment:**
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
>But, my ConEmu is disabled.

Conemu is disabled for the pop-up dialog that run git commands.

But it is still used for the console tab because we don't have alternatives.
