### ISSUE TITLE
Commit Template Settings: Commit Template field one line only

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#6029]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/3629489/50607879-ca198a00-0e98-11e9-90e6-20e8899da6db.png)
Try pressing enter or shift enter in textbox to add lines.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- In commit window, open 
![image](https://user-images.githubusercontent.com/3629489/50607947-ffbe7300-0e98-11e9-8bd8-caf2a6201851.png)
- Try to type multiple lines

**What is the expected behavior?**
Be able to type multiple lines.
**Environment you encounter the issue:**

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Did this work in previous version of GitExtensions (which)?**
Not sure.

**Comment by vbjay** [comment]
Workaround.  Type info in text editor and copy.  Paste into textbox.

**Comment by gerhardol** [comment]
Same problem as #5975 (other forms too?)
I have not found the core problem.
(Only a very limited workaround)

**Comment by vbjay** [comment]
You know. I wonder if we are altering with win32 API?

**Comment by gerhardol** [comment]
> You know. I wonder if we are altering with win32 API?

I am not aware of such changes.

**Comment by RussKie** [comment]
@NikolayXHD any ideas?

**Comment by vbjay** [comment]
> I am not aware of such changes.

I bet it might be unintentionally done. Think I'll use spy++ and look at window styles of multiline textboxes.

**Comment by vbjay** [comment]
Commit Text Textbox
![image](https://user-images.githubusercontent.com/3629489/50617156-be8a8b00-0eb9-11e9-9d2a-34336a6aa465.png)

![image](https://user-images.githubusercontent.com/3629489/50617172-ccd8a700-0eb9-11e9-9f12-645b8218b35d.png)

![image](https://user-images.githubusercontent.com/3629489/50617207-fa255500-0eb9-11e9-820b-7fa49365cfb5.png)


![image](https://user-images.githubusercontent.com/3629489/50617349-bda62900-0eba-11e9-9bdb-804966e3b5e4.png)

![image](https://user-images.githubusercontent.com/3629489/50617352-c565cd80-0eba-11e9-9058-b91a4d509aa8.png)
![image](https://user-images.githubusercontent.com/3629489/50617362-d282bc80-0eba-11e9-85fc-ef45af6855e7.png)

**Comment by NikolayXHD** [comment]
It is win32 API indded, `ControlHotkeyExtensions.EnableRemoveWordHotkey(...)` called from `GitExtensionsFormBase.InitializeComplete()`
When I comment the call and run GitExtensions, Enter key works normally.

**Comment by vbjay** [comment]
LOL!  I was about to say when I press enter it selects the text instead of creating a new line. AWESOME.  we can fix both issues in  one fell swoop.

**Comment by RussKie** [comment]
Awesome team work! 👍

**Comment by vbjay** [comment]
> Awesome team work!

It was @gerhardol  link to the other issue that made me think inheritance or windows messages/ styles.

**Comment by gerhardol** [comment]
Should the 3.0.1 release be delayed and await the correction for this issue?

**Comment by NikolayXHD** [comment]
Ok. I suppose the solution would be to `.EnableRemoveWordHotkey(...)` only in single-line textboxes.
