### ISSUE TITLE
Suggestion: Add Codacy static code analysis

### ISSUE THREAD

**Issue by escherstair** [gitextensions/gitextensions#6030]
I'd like suggesting a new feature/improvement.

I think that it's important that GitExtensions (as every other project) has a high code quality.

I see that some projects on github use [Codacy](https://www.codacy.com/), which can be used free of charge [for open source projects](https://opensource.codacy.com/).
I see that C# is one of the Supported Language.

I have no experience but I think it should be "quite easy" to configure Codacy analysis over GitExtensions.
The reports can give hints on where to focus improvements and effort.

What the developers think on this suggestion?

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3130.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
An alternative (I don't know which one is the best): https://sonarcloud.io/about/sq

And we could see what it looks like: 
https://sonarcloud.io/organizations/sonarsource/projects?languages=cs

Could we see a usage of Codacy on an opensource project? Because except their beautiful website we can't see how it really look like.

Searching on the web for a review, I found this comparison: https://dzone.com/articles/codacy-a-new-easy-to-use-code-quality-and-review-a

And this review giving a good overview: https://sylvainleroy.com/2017/12/23/codacy-easy-use-code-quality-review-solution/

**Comment by escherstair** [comment]
[Here](https://app.codacy.com/project/kimkulling/assimp/dashboard) you can see the usage of Codacy for [assimp ](https://github.com/assimp/assimp)project.

I didn't know SonarQube and so I can't say which one is the best approach.
I see that some projects on github use a couple of tools.
Another one is [LGTM](https://lgtm.com/)

**Comment by gerhardol** [comment]
It would be interesting if someone set up the analysis on their fork. Then basically a pr will activate.

**Comment by pmiossec** [comment]
>Here you can see the usage of Codacy for assimp project.

@escherstair thanks.

**Comment by spdr870** [comment]
I use sonarqube at work and it is great. We also use it for coverage. You need to start small, with only a few rules. Otherwise it can be a real pain to cleanup all existing code. Also, it sometimes gives false-positives. But these can be suppressed with a pragma.

**Comment by RussKie** [comment]
One of my previous clients used SQ, but abandoned it pretty quickly... it
was just to cumbersome

**Comment by drewnoakes** [comment]
SQ requires changes to the build, so it a bit more effort to configure.

I've kicked off a Codacity build against my fork. It's still processing, but is publicly visible at https://app.codacy.com/project/drewnoakes/gitextensions/dashboard

**Comment by drewnoakes** [comment]
Looks like Codacy failed to clone. It says there are no commits.

**Comment by drewnoakes** [comment]
Results are in. There's possibly some value here, though I haven't dug deeply into it. 

It looks like it's using [SonarSource](https://github.com/SonarSource/sonar-dotnet) behind the scenes for C# analysis. It has other tools too, for other languages. It flagged a bunch of Powershell stuff, along with some JS stuff (mostly around no knowing wscript specific scripts). Take a look at [the report](https://app.codacy.com/project/drewnoakes/gitextensions/dashboard) and see what you think.

**Comment by gerhardol** [comment]
3000 issues of which 300 was critical, not so bad. 
Many rules will be deactivated, many occurrences will be suppressed and some changes done to satisfy the checks.
Will be useful, maybe there are a few actual bugs detected.

**Comment by vbjay** [comment]
I like the powershell analyzer.  That was good to know.

**Comment by RussKie** [comment]
Nice one! Thank you Drew

**Comment by wachulski** [comment]
As a big fan of code quality aid tools I'd like to bring this little summary to the table. Decide whatever best suits development of this great GIT tool (which I'm also a user of 🙂):

| Product | Live demo of this repo and remarks
|----------|-----------------------------------------|
| Codacy | https://app.codacy.com/project/wachulski/gitextensions/dashboard No coverage integrated |
| SonarQube | https://sonarcloud.io/dashboard?id=GitExtensions +coverage from OpenCover file, requires CI wiring, see: #6120 **This is my favourite** 😃  |
| Better Code Hub | https://bettercodehub.com/results/wachulski/gitextensions  just summary, nice coupling/dependency visualizations |
| LGTM | https://lgtm.com/projects/g/gitextensions/gitextensions/ Failed as JS and Python detected only |
| Code Factor | https://www.codefactor.io/repository/github/wachulski/gitextensions/trends historical analysis, interesting trends; but for this repo it misclassifies artifacts a bit |

I selected only the products available on GitHub Marketplace.

### Additional remarks on CodeCov

I see you make use of **CodeCov** (which is great too!). But it takes into account the unit tests projects (of ~ 90% coverage) which skews the overall project stats. SonarQube on the other hand excludes them (but adds some submodule loaded extension codebases).

**Comment by wachulski** [comment]
> Would ExcludeFromCodeCoverage attribute help?

@RussKie An easy fix is to exclude the directory at CodeCov level. https://github.com/gitextensions/gitextensions/pull/6129.

**Comment by wachulski** [comment]
I've been using SonarQube heavily for years now. Both commercial and OSS (https://sonarcloud.io/organizations/wachulski-github/projects?sort=-analysis_date).

The important fact is that Sonar has its origins in on-premise analysis family (only recently SonarCloud.io entered the stage) and for .NET you need to code analysis execution into your CI. It's different for other providers which rarely let you execute analysis on premises and push the results to the server/cloud (CodeCov allows for that, I know). Codacy can do, but it's tricky too (https://support.codacy.com/hc/en-us/articles/360008254833-Run-local-analysis-before-creating-a-commit). Instead you just integrate the provider in e.g. GH and select items to be analysed. But this has it's drawbacks (e.g. less options for tuning things). Consider LGTM https://lgtm.com/projects/g/gitextensions/gitextensions/ which failed in GitExtensions case or Codacy without code coverage https://app.codacy.com/project/wachulski/gitextensions/dashboard

What's more, it's considered insecure to analyse PRs (with auto commenting issues detected) in case of SonarCloud.io + GH for public projects (the PR analysis runs in CI and secure auth token would be exposed in AppVeyor, in case you care about securing it). On the other hand e.g. Codacy, which belongs to the family of seamless integration, can safely analyse PRs.

The advantage of seamless integration is that the preconfigured set of code quality tools is run against the project (e.g. Codacy brought PowerShell analysis to the table), but yet again, might be of low accuracy. IMO Codacy lacks filtering, drill downs and visualizations which SQ has.

Up to you guys 🙂 Great that you consider such free tools that are out there to serve OSS.

**Comment by gerhardol** [comment]
I have setup MISRA analyzers with PRQA/QAC and Klocwork but hope that we wiull not need the detailed reports here. (Caring more for static analysis than tests on artificial interfaces @RussKie ). I consider the PR analysis to be the most important, to avoid new issues. SonarQube estimates only 24days to fix all reported issues. There are likely a few actual bugs in these changes that we are not aware of in the currently 728 open issues. The 33 issues classified as bugs would require 5h, probably worth it.

After playing around with the interfaces I find SonarQube a little more complete than Codacy, the other alternatives do not seem to be options (thanks for including them @wachulski ).

The disadvantage with SQ  that the encrypted GH key is as @wachulski mentioned a risk that a hacker can decrypt the key:
https://www.appveyor.com/blog/2016/12/23/sonarqube/

However, it seems like the SQ GitHub app solves that, not tested:
https://www.appveyor.com/blog/2018/10/02/github-apps-integration/

@gitextensions/git-extensions-source @vbjay 
What about trying SonarCloud?

**Comment by vbjay** [comment]
Sounds cool.  Let's try it. We can always yank it if it doesn't fit.

**Comment by sharwell** [comment]
> MISRA

Short for MISRAble.

**Comment by escherstair** [comment]
Happy to know that there are a lot of alternatives.
I asked for Codacy because I didn't know the others.
If you think that SQ is a better option, for me it's ok

**Comment by RussKie** [comment]
> What about trying SonarCloud?

:+1:

**Comment by sharwell** [comment]
Given the lack of test coverage in the UI layers, I would argue that the most important such tool has already been incorporated (codecov.io). If we do try another tool _and_ it finds real issues, it may be worth investigating whether a Roslyn analyzer already provides similar functionality and/or file an issue on [DotNetAnalyzers/Proposals](https://github.com/DotNetAnalyzers/Proposals) to add an analyzer for it eventually.

**Comment by pmiossec** [comment]
> it may be worth investigating whether a Roslyn analyzer already provides similar functionality

There is a VS extension which provide SonarQube rules (based on Roslyn): https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2017

The downside, if I remember well, is that it breaks the build if you have a violated rule. So it is excellent to keep a high quality level but can't be used until all the violations has been fixed.

There is also an analyser provided as a nuget package (never used): https://www.nuget.org/packages/SonarAnalyzer.CSharp/

**Comment by crypto-rsa** [comment]
> There is a VS extension which provide SonarQube rules (based on Roslyn): https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2017
> 
> The downside, if I remember well, is that it breaks the build if you have a violated rule. So it is excellent to keep a high quality level but can't be used until all the violations has been fixed.

We use that extension in our company and (as with any other analyzer) you can specify the rules to check and their severity in a custom ruleset file.

**Comment by wachulski** [comment]
@sharwell Well, Sonar happened to help Roslyn and NuGet projects:
https://github.com/dotnet/roslyn/pull/2237
https://github.com/NuGetArchive/NuGet3/pull/41 😃 

The big advantages of server analysis are: history (trends), filtering (and drill-downs), incremental analysis (*New Code* delta). And PR review aid when eventually configured.

It may be of particular interest for you @sharwell that it should also seamlessly consume all the other Roslyn analyzers used in the build process (e.g. popular DotNetAnalyzers) - see: https://docs.sonarqube.org/pages/viewpage.action?pageId=11640944

When it comes to the analyzer nuget, as @crypto-rsa pointed out - you can enable only significant rules for this project. There are a few, but the case is you'll never know apriori. A rule of thumb is to turn off noisy ones after the first analysis.

**Comment by gerhardol** [comment]
Let us get started with SQ, basically #6120 but use GitHub app instead as it seem to solve the key problem.
(Not sure if I have the privileges to auth the app, probably @RussKie or @spdr870 that need to follow the migration steps.)

> Short for MISRAble.

(Do not get me started on ISO26262. The consequence of that is that everything that automated in the toolchain must be certified by external assessors but manual changes are OK. The standards board is in the best case persons actually developing 15 years ago when embedded industry was even further behind than it is now.)

**Comment by RussKie** [comment]
We have integrated with the CodeScene: https://codescene.io/projects/5326
Thank you for the efforts and suggestions.
