### ISSUE TITLE
git-ex command

### ISSUE THREAD

**Issue by mrexodia** [gitextensions/gitextensions#6043]
## Feature description

Currently there is a `gitex.cmd` in the installation directory. This is useful because you can type `gitex browse` or `gitex commit` to switch from your command line to a gui, similar to `gitk` or `git gui`. Unfortunately this does not allow for a git alias. I personally use `git c` and `git b` to commit/browse respectively. 

My proposal would be to add `git-ex.exe` to the installation directory, so you can use it as a git command (and thus also allow an alias):

```
git ex commit
git ex browse
git config --global alias.c "ex commit"
git config --global alias.b "ex browse"
```

I already wrote all the code (around 50 lines C#) and I can contribute it if you are interested.

**Comment by mrexodia** [comment]
Very nice, I didn't know that feature existed!

So yeah the following commands set up my aliases:

```
git config --global alias.c "!start GitExtensions.exe commit"
git config --global alias.b "!start GitExtensions.exe browse"
```

Or to be blocking like `git gui`:

```
git config --global alias.c "!GitExtensions.exe commit"
git config --global alias.b "!GitExtensions.exe browse"
```

Thanks a lot @pmiossec, this resolves the issue for me. Hopefully it will be useful for someone in the future.

**Comment by drewnoakes** [comment]
Interesting idea. Am now wondering if this would be useful as an option in the installer.
