### ISSUE TITLE
GitModule.GetRefs(tags: false, branches: true) does not return remote branches

### ISSUE THREAD

**Issue by amaiorano** [gitextensions/gitextensions#6044]
## Current behaviour

GitModules.GetRefs(tags: true, branches: true) returns tags, local branches, and remote branches; however, GitModules.GetRefs(tags: false, branches: true) will return only local branches.

## Expected behaviour

GitModules.GetRefs(tags: false, branches: true) should return both local and remote branches.

## Steps to reproduce

I'd like to write a unit test for this. I don't have time right now, but I wanted to make sure to create this issue before I forget.

## Did this work in previous version of GitExtensions

Not sure.

## Environment

Dev version of GE, at f3a610e33e2a436ec5e4b39309dd2d9055c80e79

**Comment by drewnoakes** [comment]
I never liked those two bools. I'd rather see a flags enum.

**Comment by amaiorano** [comment]
Yes, we should use a flags enum. This isn't a super trivial fix only in that there are a few places in the code that are passing in (false, true) and that might be relying on the fact that it doesn't return remote branches. So we need to make sure that these call sites don't break if it suddenly returns remotes. Or, we add an enum value to indicate that we want remote branches.

**Comment by RussKie** [comment]
> I never liked those two bools. I'd rather see a flags enum.

Working on https://github.com/gitextensions/gitextensions/pull/8427 I arrived to pretty much the same conclusion.
