### ISSUE TITLE
Fetching orgin from the remote branches on first load asks for the ssh key

### ISSUE THREAD

**Issue by bhcoder** [gitextensions/gitextensions#6047]
## Current behaviour
Trying to fetch the origin from the branches view asks to load the ssh key
(No supported authentication methods available (server sent: public key)

It seems that the key is not loaded, while fetching first the master from the commit list will load the key correctly making the following fetch from the remote tree to work

## Expected behaviour
The branch should be fetched.

## Steps to reproduce
1. close Git Extensions and Pageant
2. open a repository which uses ssh
3. fetch the origin from the remote branches tree on the left

## Screenshots
![Image](https://i.imgur.com/PqxyvAa.png)

**Comment by RussKie** [comment]
@vbjay has provided a number of detailed responses to the similar issues in #4916. Please read https://github.com/gitextensions/gitextensions/issues/4916#issuecomment-424304646 onwards and see if those resolve your issues.

**Comment by bhcoder** [comment]
The setup is the same and works if I pull/fetch from the commit list in the center:
doing that way the pageant is launched, the key is added and the fetch/pull works.
If I fetch the repo from the left tree after that it will work since the key is loaded.

However if I open the repo for the first time and try to fetch from the remote tree it will not work since the fetch command does not launch pageant and does not add the key from the repo settings asking you to manually load it


![Image](https://i.imgur.com/ayQhjW6.png)

**Comment by vbjay** [comment]
That context menu should be calling the same code as the fetch button on the toolbar.  We shouldn't be duplicating code and instead call a preformFetch method that gets called by the fetch menu option and if the button default is set to fetch.  Same with other context menus.

@amaiorano @EbenZhang

**Comment by amaiorano** [comment]
Yes, as @vbjay says, the fetch code for the Remote node in the left panel isn't the same as FormBrowse. Just tested a quick fix, and it seems to work. Will open an PR.

**Comment by RussKie** [comment]
Could you please try this build and confirm the fix
https://ci.appveyor.com/api/buildjobs/ree3ecpje36yo71d/artifacts/Setup%2FGitExtensions-Portable-3.01.00.4753.zip

**Comment by bhcoder** [comment]
> Could you please try this build and confirm the fix
> https://ci.appveyor.com/api/buildjobs/ree3ecpje36yo71d/artifacts/Setup%2FGitExtensions-Portable-3.01.00.4753.zip

When opening this version I get the following error:

> Could not load file or assembly 'Microsoft.VisualStudio.Composition, Version=15.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Besides that remotes > origin > fetch works now, but remotes > origin > [branch_name] > fetch/fetch & [commmand] have the same issue

**Comment by RussKie** [comment]
That issue is tracked in #5990 and is getting fixed in #6005
