### ISSUE TITLE
AppVeyor build is broken: netstandard is missing

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6055]
## Current behaviour

The AppVeyor build fails to start on my machine:

![grafik](https://user-images.githubusercontent.com/36601201/50786833-f5dfaa00-12b4-11e9-9a87-2c50cdb03826.png)

## Did this work in previous version of GitExtensions

Yes.

## Environment

- Git Extensions 3.01.00.4705, 3.01.00.4720
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Will be fixed by #5990

**Comment by gerhardol** [comment]
Duplicate of #5990
