### ISSUE TITLE
Artificial commits should appear immediately above checked out commit

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#6062]
## Current behaviour

Artificial commits are not appearing immediately above checked out revision.

## Expected behaviour

They appear immediately above the checked out revision.

## Steps to reproduce

- Check out a revision that's not the most recent in your history.
- Enable artificial commits.

I'm not sure that any special steps are required. If others cannot reproduce this, I will look further. I see it all the time.

## Screenshots

![image](https://user-images.githubusercontent.com/350947/50824768-5b707c80-132f-11e9-8f16-b1feb972bbb6.png)

## Did this work in previous version of GitExtensions

Yes. I think this might have been introduced by graph changes made soon before the 3.0 release.

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 144dpi (150% scaling)

**Comment by vbjay** [comment]
Should also fix stashes at the same time.

**Comment by gerhardol** [comment]
> Should also fix stashes at the same time.

Probably different.
Artificial commits are inserted while stashes are just like any reflog, so they will have to be very specially handled.

**Comment by gerhardol** [comment]
I saw something similar in one of @spdr870 builds related to #5782 and he fixed that.
Have not seen this with the master branch (which should be the same as in 3.0.0).

**Comment by gerhardol** [comment]
I have not seen this in some time, does not seem to be an issue any more.
If HEAD commit is filtered, 4.0 will try to add the commits above the nearest ancestor.
