### ISSUE TITLE
Ability to disable 'simplify-merges' option

### ISSUE THREAD

**Issue by OlegLevitsky** [gitextensions/gitextensions#6066]
Hello there!

## Current behaviour
History form does not show all merges even if 'Show Full History' option is toggled 'on'.

## Expected behaviour
'Show full history' displays all commits and merges that affects specified file

## Steps to reproduce
Create a branch 'B1'
Create a child branch 'B2' from the 'B1'
Make different changes in the same file from 'B1' and 'B2'
Merge 'B1' to 'B2'
Resolve conflict using change from 'B2'
Merge 'B2' to 'B1'
Now you can see that changes in 'B1' are lost and can't find how it happens

## Did this work in previous version of GitExtensions
Don't know exactly

## Environment
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

## Original description
I'm a participant in a huge project and it's really important for me to see full file history include all merges. I've downloaded the source code and found hardcoded option '--simplify-merges' in the 'FormFileHistory' class. This option makes GitExtensions useless for me and other developers on my project, so I beg you guys, create a button or anything else to disable it. Please, take attendance that 'Show Full History' button in the Visual Studio doesn't ignore merges.
Thanks in advance, I really appreciate your work

**Comment by drewnoakes** [comment]
There have been various issues around this in the past and no one has devoted the time to make this work reliably. Can you take a look at it?

**Comment by RussKie** [comment]
@OlegLevitsky could you please confirm that you saw a template when created this issue? We recently reconfigured our templates and I'm concerned people aren't seeing issue templates.

If you did see it and ignored it, please complete it.

**Comment by OlegLevitsky** [comment]
@RussKie Hello! made the update, sorry for the mess.

@drewnoakes Hi! could you please clarify: what do you mean?

**Comment by drewnoakes** [comment]
@OlegLevitsky can you do some research here and submit a PR with the necessary changes?

**Comment by OlegLevitsky** [comment]
@drewnoakes yes, sure. Do you mean a sample from the 'Steps to reproduce' or a PR with required changes in the source code which adds a button to the app?

**Comment by RussKie** [comment]
A PR that addresses the issue, if you can.

**Comment by RussKie** [comment]
Please fork, do your work on a feature branch and send a PR to the main
trunk

**Comment by OlegLevitsky** [comment]
@RussKie oh, got it! thanks, I am a newbie on the github

**Comment by drewnoakes** [comment]
@OlegLevitsky no worries. Feel free to ask for help if you hit any problems.

**Comment by RussKie** [comment]
With general/setup questions you can get help on our gitter channel as well, sometimes it is quicker - https://gitter.im/gitextensions/gitextensions
