### ISSUE TITLE
Delete All no longer works - "not selectable"

### ISSUE THREAD

**Issue by TamaHobbit** [gitextensions/gitextensions#6068]
## Current behaviour

When you have some branches that begin with the same prefix followed by a "/", such as "feature/abc" and "feature/cba", right clicking the directory icon in the branches pane and clicking "Delete all", the resulting command gives an error: "Branch "feature/cba," is not selectable, this branch has been removed from the selection. The command will only delete the last branch in the list. Removing all the commas from the text field before clicking Delete fixes the problem.

## Expected behaviour

The text field should not contain commas, so that the command succeeds without manual editing being necessary.

## Screenshots

![Delete All plus error message](https://i.imgur.com/n6dX3Nh.jpg)

## Did this work in previous version of GitExtensions

Yes, this worked in GitExtensions 2.51 using Git 1.9.4. I upgraded to Git 2.20 in order to use GitExtensions 3, and this introduced this problem for me.

## Environment

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.20.0.rc1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3130.0
- DPI X:100,00 % Y:100,00 %

**Comment by amaiorano** [comment]
I'll take care of this. I also noticed this bug with delete remote branch.

**Comment by gerhardol** [comment]
Note: Side-panel is new in 3.0.0, so it cannot have worked before...

**Comment by TamaHobbit** [comment]
@gerhardol Indeed, I was mistaken in which previous version I used. This works in GitExtensionsMod (2.53), a fork of GitExtensions which had merged that pane much earlier.
