### ISSUE TITLE
Endless staging in new 3.0 version

### ISSUE THREAD

**Issue by subzero911** [gitextensions/gitextensions#6069]
Hi there. In a previous version everything was okay, but now when I updated GitExtensions and decided to make a commit, I press "Stage all" icon in Commit dialogue, and a client hangs. I waited for 3 hours and it's still loading. Project is rather big (~1.8 Gb)
I tried it with another Git client, and it staged in about 2 minutes, so problem is in GitExtensions.

**Comment by vbjay** [comment]
We have an issue template for a reason.  

```
<!--
    ⚠️ Review existing issues to see whether someone else has already reported your issue.

    📖 Please also read CONTRIBUTING.md.
-->

## Current behaviour

<!-- Be as specific and detailed as possible to help us identify your issue. -->


## Expected behaviour



## Steps to reproduce

<!-- Take some time to try and reproduce the issue, then explain how to do so here. -->


## Screenshots

<!-- Screenshots can be very useful in helping to understand the issue you're facing. -->



## Did this work in previous version of GitExtensions

<!-- If so, which version? -->


## Environment

<!-- Use Help/About in Git Extensions to copy this information to the clipboard automatically. -->

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 


## Diagnostics

<!-- If relevant, as described at https://github.com/gitextensions/gitextensions/wiki/Diagnosing-problems -->



<!--
    ❤️ Git Extensions? Please consider supporting our collective:

    👉 https://opencollective.com/gitextensions
-->
```

**Comment by vbjay** [comment]
Show output of 

https://github.com/gitextensions/gitextensions/wiki/Diagnosing-problems#size-by-extension--suggestion-for-possible-git-lfs-usage 

Understand git is not designed for binary files.  It is designed for source code files.  Read up on git lfs.

**Comment by subzero911** [comment]
> Understand git is not designed for binary files. It is designed for source code files. Read up on git lfs.

I've played with LFS already. 1) I didn't notice any reasonable upload/download speed benefit. 2) It's not suitable for Mac computers. If I push a repo on Windows and pull on Mac, all the LFS content is omitted. That's why we don't use LFS in production.

**Comment by vbjay** [comment]
The whole point of lfs isn't download/upload speed.  It keeps your git repo from bloating.  It uses filters to push your new work to the lfs store and pull down to the lfs object folder teh needed binary files.  This way you don't have a file that is 10 MB change and cause your git repo to now be +10 MB.  Git will just store the hash in the repo. When you do a checkout or pull or push, the right thing just happens.  The fact that you have an almost 2GB repo screams that you have bloat and binary file issues.  



https://youtu.be/9gaTargV5BY
https://www.atlassian.com/git/tutorials/git-lfs

**Comment by vbjay** [comment]
Example:  Let's say cat=10MB binary and dog= 5MB binary.

You add a file with the contents of 

```
cat
```
You commit that file.  So the repo grows by 10MB.

You alter the file

```
cat
dog
```
It is now 15MB.  How big is the storage of those two commits?  25MB + size of git data objects (tree, commit...).  You have an object of 10MB holding the contents of the original file.  Then you added a 15MB file.  Git downloads the full history so you get ALL the copies of the files.  

What LFS does is store markers in the git repo that point to specific lfs files.  The filters do their job of when you modify in the working directory a file that is being managed by lfs and commit it, it stores the contents just like it would in git but an lfs object store instead of git object store.  When you push that commit the lfs object is pushed too.  

Watch the youtube video I linked.

**Comment by subzero911** [comment]
![image](https://user-images.githubusercontent.com/12999702/50881002-53791100-13f1-11e9-898c-7169d1c33907.png)
![image](https://user-images.githubusercontent.com/12999702/50881036-6db2ef00-13f1-11e9-9f16-23e18171197c.png)

**Comment by RussKie** [comment]
@subzero911  could you please confirm that you saw a template when created this issue? We recently reconfigured our templates and I'm concerned people aren't seeing issue templates.

If you did see it and ignored it, please complete it.

**Comment by drewnoakes** [comment]
@subzero911 there's not enough information in this issue to help you. It'd be great to understand why this is happening, but if we cannot reproduce it then we have no idea of the cause. Please see my comment above for some ideas on how to further diagnose.

**Comment by zamoldar** [comment]
I returned to v 2.51, this relase not stabil and very slow also current ui not handsome like v2

**Comment by gerhardol** [comment]
Handled in #6492 
(The handling for many files in 3.0 vs 2.51 should be the same though)
