### ISSUE TITLE
V3.0 of GitExtensions file editor no longer has 80 char ruler

### ISSUE THREAD

**Issue by glennsarti** [gitextensions/gitextensions#6074]
Without the ruler it makes it very difficult to keep commit messages within the "normal" 80char limit.

## Current behaviour

In version 3.x (3.00.00.4433) when the file editor is shown there is no 80 char ruler

![image](https://user-images.githubusercontent.com/5819622/50880984-2f322a00-141b-11e9-8fe1-b11ede52983b.png)

## Expected behaviour

Previously in version 2.x (e.g. 2.51.05) when the file editor is shown there was an 80 char ruler e.g.

![image](https://user-images.githubusercontent.com/5819622/50880929-014ce580-141b-11e9-90ad-30dd013119ac.png)

## Steps to reproduce

* Install v2.x of git extensions

* Configure git extensions so that it's the default editor

.gitconfig
``` text
...
[core]
        editor = \"c:/Program Files (x86)/GitExtensions/GitExtensions.exe\" fileeditor
```
* Create an empty directory
* Initialise the empty directory as a git repo (`git init`)
* Add a file and stage it (`git add --a`)
* Commit the file with `git commit`

This should start the GitExtensions file editor where the problem can be seen

## Did this work in previous version of GitExtensions

As per above v2.51.05

## Environment

Windows 10 1803 - 64bit
Using powershell.exe as the console (not conemu or cmd.exe)

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.17.1.windows.2
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3190.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Addressed in #5930

**Comment by glennsarti** [comment]
Thanks @RussKie .   I couldn't see an issue that related to this so apologies for the duplicate.

**Comment by RussKie** [comment]
This will come back in 3.0.1, which should be out pretty soon

**Comment by glennsarti** [comment]
Wohoo!  Just got the latest edition and the ruler is BACK!  Thankyou.
