### ISSUE TITLE
Broken issue templates

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#6075]
## Current behaviour

Since merging #5955 we're seeing issues created without templates.

@RussKie pointed out we likely need to update the app to use URL https://github.com/gitextensions/gitextensions/issues/new/choose

It may also be possible to reinstate the previous ISSUE_TEMPLATE file without reverting the choice feature. I haven't tested this.

## Expected behaviour

All users see a template.

**Comment by pmiossec** [comment]
>It may also be possible to reinstate the previous ISSUE_TEMPLATE file without reverting the choice feature. I haven't tested this.

I think we should try, at least until the lack of support of the mobile version of Github.
