### ISSUE TITLE
Corrupted Commit Log View after scrolling

### ISSUE THREAD

**Issue by igor84** [gitextensions/gitextensions#6082]
## Current behaviour

In some git repos when scrolling the commit log view up and down all text disappears and most of the lines become covered with black bars as can be seen in the attached screenshot bellow. This is not happening on every repo, but on those that it does it happens every time. Also all repos where this happens for me are submodule repos, but again not on all submodule repos so that could be a coincidence. The only workaround I found is scrolling, then selecting some row blindly and hitting refresh. That would refresh the view and show everything properly until I scroll again. This makes commit history unusable.

## Expected behaviour

Commit log view should always display properly.

## Steps to reproduce

I couldn't identify what is causing this. It seems it is only happening on submodule repos and of a bit larger history tree, but there are submodule's with larger trees where it is not happening too.

## Screenshots

![blackbarsgitextensions](https://user-images.githubusercontent.com/5306699/50961340-c3f26180-14c7-11e9-8605-ffdc21871709.png)

## Did this work in previous version of GitExtensions

Yes, it worked in all pre 3.0 versions of GitExtensions.

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

## Diagnostics

I didn't notice anything relevant in command log.

**Comment by drewnoakes** [comment]
Seems related to #6071 which also involved submodules.

@igor84 could you read that issue and see if anything looks familiar? Also could you describe the module structure of a repository that triggers this? Thanks.

It would also be useful to see what view options you have by screenshotting this:

![image](https://user-images.githubusercontent.com/350947/50967453-1f285200-14d0-11e9-9e21-514d38bcc10b.png)

**Comment by vbjay** [comment]
@drewnoakes   Your comment makes the think we need to show a PSTaskDIalog asking if they want to initialize the submodule at this time when they add a submodule.  In the dialog we can tell them they must do this before the files show.

**Comment by igor84** [comment]
I looked through #6071. The symptoms are the same: any interaction makes it black but I don't have any git repos within other git repos that are not submodules.

Here is my View settings:
![extview](https://user-images.githubusercontent.com/5306699/50980661-8ad2e500-14f9-11e9-9362-4e8ecefa9ca9.png)

**Comment by djcvijic** [comment]
I can confirm that this seems to happen specifically when browsing submodules and that this is not a coincidence. As described, it happens for me when browsing history of a few large submodules. But when I try to clone the submodule repositories separately as regular standalone repositories, I can then browse the standalone repository history normally without this bug occurring.

**Comment by vbjay** [comment]
In your main repo, navigate to a folder that is a submodule.  Look for a .git folder or file.  Is it a file or a folder?

**Comment by igor84** [comment]
Still present in 3.0.2.

**Comment by leorohr** [comment]
@igor84 I had this issue when working with a submodule path that contained spaces like yours in the screenshot above. PR #6318 will hopefully fix this.

**Comment by RussKie** [comment]
Fixed in #6318
