### ISSUE TITLE
Unified diff editor

### ISSUE THREAD

**Issue by rmsmani** [gitextensions/gitextensions#6083]
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3260.0

**Comment by rmsmani** [comment]
Its easy to have the diff editor to show the differences in the unified view rather than the split view

**Comment by drewnoakes** [comment]
Can you post a screenshot of what you mean? As far as I know GE only has a unified diff view!

**Comment by gerhardol** [comment]
(See for instance GitHub PRs to see one definition of split/unified.

GE uses only unified in the built-in diff views. Use an external difftool to get a unified diff (not easy to do).

**Comment by RussKie** [comment]
Please fill the feature request as per the templates provided.
The description of the issue should clearly explain what it is that you're requesting and provide screenshots that help others in understanding.

Once this is done please let us know and we will re-open your request.

**Comment by vbjay** [comment]
We don't support split diff.  We do support opening your difftool from ge.  I use p4Merge.  It shows a split diff.  
![image](https://user-images.githubusercontent.com/3629489/51011218-b2d83d80-1525-11e9-97dc-1bbd9dca4a20.png)
![image](https://user-images.githubusercontent.com/3629489/51011240-c8e5fe00-1525-11e9-9c4e-2afc95a53792.png)
