### ISSUE TITLE
View menu icons fail to update

### ISSUE THREAD

**Issue by DCFerg** [gitextensions/gitextensions#6086]
## Current behaviour

When the following options in the View menu are toggled, the action takes place (the view changes) but the icon in the View menu is not updated until Git Extensions is refreshed (by clicking the refresh button, executing a fetch, etc):
- Show remote branches
- Show author date
- Show relative date

## Expected behaviour
When clicked, the icon state should toggle.

## Steps to reproduce
Click the View dropdown menu.
See that the "Show remote branches" icon indicates that it is active.
Click "Show remote branches".
The View menu closes and remote branch names are no longer shown in the main view.

Click the View dropdown menu again. 
See that the "Show remote branches" icon incorrectly indicates that it is active.
Click "Show remote branches".
The View menu closes and remote branch names are again shown in the main view.

Now repeat but refresh in the middle:

Click the View dropdown menu.
See that the "Show remote branches" icon indicates that it is active.
Click "Show remote branches".
The View menu closes and remote branch names are no longer shown in the main view.

Refresh Git Extensions by clicking the refresh icon that is below "Start" at the upper left.

Click the View dropdown menu.
See that the "Show remote branches" icon has been updated and now correctly indicates that it is not active.

"Show author date" and "Show relative date" can be tested in the same way.
And the problem occurs in reverse - starting with the feature being inactive and making it active; the icon doesn't update until a refresh is done.

## Screenshots
Starting with this:
![image](https://user-images.githubusercontent.com/13531298/50989063-5e5ca000-14dc-11e9-9378-7f2eafa1c306.png)
...click "Show remote branches", "Show author date", and "Show relative date".

Resulting state is this:
![image](https://user-images.githubusercontent.com/13531298/50989199-b09dc100-14dc-11e9-96f9-7042961910f4.png)
All three still indicate they are active but the remote branches are not shown and the dates are shown as actual, not relative.

Click refresh and the state is then this:
![image](https://user-images.githubusercontent.com/13531298/50989645-eb542900-14dd-11e9-9439-0bdf8d04dc25.png)
The icons have been updated in the View menu.

## Did this work in previous version of GitExtensions

It was reported in #3730 and (#4367). Fix was merged for v2.51 in #4156.

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3221.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Adding to MS 3.1.0, but prio is low (probably easy to fix though).

**Comment by DCFerg** [comment]
I have the fix. I'll put a PR in soon. Fix should be based on the 3.0 release branch, right?
