### ISSUE TITLE
Copy links to clipboard

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6088]
## Feature description

Add a context menu item `Copy link` to the Commit Info which copies the link under the mouse to the Clipboard.

#### new
![grafik](https://user-images.githubusercontent.com/36601201/50998197-04cd9300-1527-11e9-9c3a-064627af0e08.png)

#### current
![grafik](https://user-images.githubusercontent.com/36601201/50998299-465e3e00-1527-11e9-882b-80e966713c31.png)

## Environment

- Git Extensions 3.01.00.0
- Build f7e97be0cc4190340516d86ab661f72a7e95f2b3 (Dirty)
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
OK for me, but Copy Commit Info should be on top

**Comment by mstv** [comment]
> OK for me, but Copy Commit Info should be on top

I avoid right-clicking a link when I want to open the context menu. Then `Copy commit info` is on top because `Copy link` is invisible.
If I right-click a link, then I want to do something with the link and expect the regarding menu item(s) on top.
Note: I have added menu shortcuts. So one can right-click and hit `C` to copy the commit info regardless of the item's position and without moving the mouse to click the item.

![grafik](https://user-images.githubusercontent.com/36601201/50999962-fafa5e80-152b-11e9-9290-4db90580f5d6.png)

How can one know whether the context menu was opened using the mouse or the keyboard (Shift+F10 or special key), especially in the event `ContextMenuStrip.Opening`?

Is there a benefit of having a dedicated issue for such a small feature, especially when it has already been implemented?

**Comment by gerhardol** [comment]
> If I right-click a link, then I want to do something with the link and expect the regarding menu item(s) on top.

OK

> How can one know whether the context menu was opened using the mouse or the keyboard (Shift+F10 or special key), especially in the event ContextMenuStrip.Opening?

Do not know

> Is there a benefit of having a dedicated issue for such a small feature, especially when it has already been implemented?

Is this related to submitting this issue first, then a PR?
If so, this controls how issues/PRs appear in the release notes.
It may also be good to separate the discussion on how to do with implementation details.
But @RussKie is not strict about it. 
In this case it should have been OK with a PR directly.

**Comment by RussKie** [comment]
> It may also be good to separate the discussion on how to do with implementation details.
> But @RussKie is not strict about it.

It is still good to have a discussion when fix isn't trivial 😏 

Should we show **only** "Copy link (...)" menu when right clicking on a link?

**Comment by mstv** [comment]
> Should we show only "Copy link (...)" menu when right clicking on a link?

Gerhard even wanted the `Copy commit info` before the `Copy link` initially.
I think having `Copy link` as the first item is the best compromise because then it doesn't matter where one right-clicks into the Commit Info and every available functionality is visible.
