### ISSUE TITLE
Side panel activate remotes: duplication

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#6106]
## Current behaviour
After #6015 
Activate&Fetch duplicated the remotes
(a second activation did not add a third)

## Expected behaviour

No duplication

## Steps to reproduce

Activate a remote

## Screenshots
![image](https://user-images.githubusercontent.com/6248932/51147183-9ad02900-1859-11e9-94ba-25dcfeb80f9f.png)

## Did this work in previous version of GitExtensions
no, new in master

## Environment

- Git Extensions 3.01.00.0
- Build 043c96c6ee00671091d55197f6a3512bdc5d9402 (#6105 )
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

## Diagnostics

n/a

**Comment by amaiorano** [comment]
Huh weird. Will check it out.

**Comment by amaiorano** [comment]
Not sure how to repro this. Can you send me your 'git remote -v' or something so I can try to reproduce your environment?

**Comment by amaiorano** [comment]
I keep trying, but cannot reproduce. When this happens, do you see an exception in the VS output?

**Comment by amaiorano** [comment]
Oh I repro'd it!

**Comment by amaiorano** [comment]
So I must have tried over 100 times, and it happened only twice. When it did, I couldn't see why.

**Comment by amaiorano** [comment]
I believe I got it. Putting the PR together.
