### ISSUE TITLE
Close window from the Taskbar context menu has no effect on modal dialogs

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6113]
## Current behaviour

`Close window` from the Taskbar context menu has no effect on GE's modal dialogs.
Sometimes, GE even stays in the background.

## Expected behaviour

GE should terminate unless there is user input which has not been saved yet (*).

If we cannot agree on this behavior, then at least the modal dialog should be brought into foreground and if it is in the foreground already, it should be closed as `Alt+F4` had been pressed.

(*) The commit message can be stored automatically as (nearly) always the Commit dialog is closed.

## Steps to reproduce

- open the Browse window
- open one of the modal dialogs (Commit, Push, Pull, Settings, etc.)
- optional: bring an other application into the foregroud
- right click GE's taskbar icon and select `Close window`

## Did this work in previous version of GitExtensions

Not that I know of.

## Environment

- Git Extensions 3.01.00.0
- Build 5a313988bf4ab8e0c37bdf1f2c658c9469e1e257
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
We should make all dialogs owned by getting main window so if they do click
main window the dialog is above GE window always. It's not modal but
prevents dialogs from hiding behind main window.

**Comment by ivangrek** [comment]
I managed to reproduce it several times.
Is there something that might affect the main thread of the application?

**Comment by RussKie** [comment]
May be you could record a TTD trace?
https://devblogs.microsoft.com/dotnet/debugging-net-apps-with-time-travel-debugging-ttd

**Comment by mstv** [comment]
Fixed in 4.0

**Comment by gerhardol** [comment]
4.1 #10796
