### ISSUE TITLE
Show push destination in commit dialog

### ISSUE THREAD

**Issue by LukeOwlclaw** [gitextensions/gitextensions#6118]
## Feature description

The commit window allows to click "Commit & push". Unfortunately one does not see to where the commit is pushed. One has to go to: Main windows -> Repository menu -> Remote repositories -> tab: Default pull behavior -> find concerning branch.

I would be much nicer if the push destination branch was shown directly next to the  "Commit & push" button. Being able to change the tracked remote branch there would also be most awesome.

## Environment

- Git Extensions 3.00.00.03-RC2
- 8cbcd2b25223c73fbe9f7dad08e498cf82734bfa  (Dirty)
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI X:100,00 % Y:100,00 %

**Comment by RussKie** [comment]
It is a good feature to have. I too sometime wonder where would the code go, if I pushed.

@LukeOwlclaw would you like to have a go at implementing the proposal?

**Comment by f-i-x-7** [comment]
The related PR was merged. I think that issue should be closed, shouldn't it?

**Comment by RussKie** [comment]
Aye, thank you
