### ISSUE TITLE
Under mono the Commit History context menu disappears

### ISSUE THREAD

**Issue by SimonAlfie** [gitextensions/gitextensions#612]
Using Git Extensions 2.24 under Mono 2.10.5 on Gentoo Linux.

Simple to reproduce:
Right click on a commit in the Commit History window.
When the context menu appears move over and down all the options.
The second time a sub-menu opens the context menu disappears.

Workaround:
You can work around this by moving the mouse down outside the context menu before moving into the option you want to select.

Other info:
Not sure if this makes a difference, but this was found when using XMing as the remote XServer for the Git Extensions window.

**Comment by RussKie** [comment]
Closing due to age.

**Comment by eric-wieser** [comment]
This issue still affects me

**Comment by eric-wieser** [comment]
More info: It doesn't actually dissappear - it just ends up in the background:

![image](https://user-images.githubusercontent.com/425260/42054188-91e8473e-7ac8-11e8-9ef8-33b781c21abd.png)

**Comment by RussKie** [comment]
I don't know if there is anything we can do...

**Comment by eric-wieser** [comment]
Perhaps not - if nothing else, right-clicking on the right edge of the window is perhaps an easier workaround than the one proposed above.
