### ISSUE TITLE
Gerrit plugin using deprecated features

### ISSUE THREAD

**Issue by nick-bulleid** [gitextensions/gitextensions#6127]
## Current behaviour

The Gerrit plugin is using deprecated features
 - draft change mentioned on the publish form, Gerrit now supports 'work in progress' and 'private' changes
 - commits are pushed to 'refs/publish' instead of 'ref/for'

## Expected behaviour

I presume we don't want to define a minimum version of Gerrit for the plugin, and there isn't an easy way of using a older version of the plugins, so I suspect we'll need to detect the version of Gerrit that the project is using and adapt the form/paths appropriately.

**Comment by RussKie** [comment]
The current version is 2.16, v2.15 has been release 1.5 years ago...
So I don't think it is too unreasonable to mandate a minimum version.

**Comment by veremenko-y** [comment]
@nick-bulleid Hi Nick. I created the PR for this issue (https://github.com/gitextensions/gitextensions/pull/6766) are you able to test it?

**Comment by nick-bulleid** [comment]
I've checked your PR and it all looks good. Thanks for making these changes.

**Comment by veremenko-y** [comment]
Cool, thank you for testing.
