### ISSUE TITLE
New feature : proxy

### ISSUE THREAD

**Issue by mikeSimonson** [gitextensions/gitextensions#613]
Hi,

I am behind a company firewall.
The only way to access github would be trough a proxy which i have been able to manage on a linux station but still not on a windows machine.
Is there any other way than implementing a proxy in git extension or is it the only option available ?

Thanks

**Comment by cawoodm** [comment]
Adding the corporate proxy to Proxy Switched is not working. Interestingly it knows there is an update but cannot download it. Could it be that you don't support unsigned or corporate CAs?

![image](https://user-images.githubusercontent.com/498834/84655606-8a6e2300-af11-11ea-937c-137a920da29b.png)

**Comment by RussKie** [comment]
> Could it be that you don't support unsigned or corporate CAs?

The code is fairly simple and naive, we don't handle proxies or CAs:
https://github.com/gitextensions/gitextensions/blob/103788acc53c5b2b5c458df0fd8fdc9c210be00f/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs#L193-L196

A PR with an enhancement is welcome.
