### ISSUE TITLE
Filter for tags

### ISSUE THREAD

**Issue by soerenrinne** [gitextensions/gitextensions#614]
I would like to have a feature to filter for available tags. It could be like the "Branches:" filter in the toolbar.

**Comment by kwaclaw** [comment]
This does not seem to allow for wild cards. Referring to version 2.48.05.
When I enter part of the tag, the list shows nothing (unless it matches a branch), when I enter a wild card at the end, it shows everything (which does not seem right either).

**Comment by Radrik5** [comment]
Wild cars work only for branches. See https://github.com/gitextensions/gitextensions/blob/374902464fad1900d1f4425646391d5ae3cac2a8/GitCommands/RevisionGraph.cs#L188

**Comment by arisliang** [comment]
It'll be useful to have wildcard works for tags as well as a feature request, so we could create local tags on some repository, and filter based on those tags of interest.

**Comment by RussKie** [comment]
Please open a new feature request for this.
Thank you
