### ISSUE TITLE
"There are no staged changes" is not hidden completely

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6149]
## Current behaviour

![grafik](https://user-images.githubusercontent.com/36601201/51504489-97044f80-1de1-11e9-8183-01e1defd3080.png)

When staging a file, the text "There are no staged changes" is hidden but not the gray box:

![grafik](https://user-images.githubusercontent.com/36601201/51504640-4c370780-1de2-11e9-9775-cd8690a93baa.png)

## Expected behaviour

The gray box should be hidden. It consumes space for nothing.

## Did this work in previous version of GitExtensions

Yes, at least in 3.0.0. Regression in one of the recent commits.

## Environment

- Git Extensions 3.01.00.0
- Build 087f23afc7288b7ded1bcafa0d8eec319ac0c52a
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Likely caused by #6037

**Comment by mdonatas** [comment]
Can confirm that this is caused by #6037 just went through a bisect to identify the cause.

**Comment by RussKie** [comment]
Gents, could you please confirm the fix?
https://ci.appveyor.com/api/buildjobs/xlprqvxlg4qx4d9k/artifacts/Setup%2FGitExtensions-Portable-3.1.0.4985.zip
