### ISSUE TITLE
Jira Commit Hint plugin doesn't work

### ISSUE THREAD

**Issue by IEVin** [gitextensions/gitextensions#6154]
## Current behaviour
Preview button in Jira commit hint plugin show dialog with error message.

## Expected behaviour
Preview button in Jira commit hint plugin show dialog with available jira tasks.

## Steps to reproduce

1. Open Tools/Settings/Plugins/Jira Commit Hint;
2. Configurate it and Press "Preview" button;
4. Get error dialog.

For reproduce this problem without correct configuration would be enought add `StringTemplate.Format("", null);` in  JiraCommitHintPlugin constructor and get TypeLoadException while plugin loading.

## Screenshots

![shot_190118_115728](https://user-images.githubusercontent.com/5438647/51537830-ae365200-1e60-11e9-8fd1-7ff5e2a2916e.png)

## Did this work in previous version of GitExtensions
Yes, it works correct on GE 3.00.00

## Environment

- Git Extensions 3.0.1.4933
- Build a269358b22a5dc1ea36928bb87f9e535de76a058
- Git 2.19.2.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

## Diagnostics
Look like problem in wrong version of System.Collections.Immutable.dll.

**Comment by vbjay** [comment]
Great. https://github.com/gitextensions/gitextensions/commit/c7e4f510bfe5ad68f5b56b19a95cfb0735b7a0c3

**Comment by vbjay** [comment]
Can you please open gitextensions.exe.config where you installed GE to and see if immutable is listed in the binding redirects and also find all *.immutable*.dll files and report on their version numbers.

**Comment by IEVin** [comment]
GitExtensions.exe.config have no any defenitions .immutable.dll files. Only System.Collections.Concurrent and System.Collections.

**Comment by vbjay** [comment]
Search the folder for *.Immu*.dll  Report on the versions of all files found, please.

**Comment by IEVin** [comment]
I found 2 files in root and in `Plugins` folder.
In root folder:
ProductVersion    : 4.6.26515.06 @BuiltBy: dlab-DDVSOWINAGE059 @Branch: release/2.1 @SrcCode: https://github.com/dotnet/corefx/tree/30ab651fcb4354552bd4891619a0
                    bdd81e0ebdbf

In 'Plugins' folder:
ProductVersion    : 4.6.24816.01. Commit Hash: 4d1af962ca0fede10beb01d197367c2f90e92c97

**Comment by vbjay** [comment]
Thank you.  That will help me pin down the issue.

**Comment by RussKie** [comment]
@vbjay is there a quick workaround/binding redirect users could apply to solve the issue?

**Comment by vbjay** [comment]
I'll look tonight.  I'll generate a dll analysys from 3.02 tag build and
report back to you then.

**Comment by vbjay** [comment]
How I generated this output:
1. Run these git commands
    - ```git clean -d -x -f```
    - ```git submodule foreach git clean -d -x -f```
1. run setup\build
1. Run provided linqpad script on the root folder where I have GE repo.  Adjust as needed

These are the dlls excluding *resources.dll that have different hashes.   The config file shows the current assembly binding redirects when built.
[GE 3.02 DLL analyze report.zip](https://github.com/gitextensions/gitextensions/files/2892387/GE.3.02.DLL.analyze.report.zip)

**Comment by PaulAdams-Conti** [comment]
FYI, I have downloaded the latest source and compiled but even though there is no exception any longer, the text pasted into the commit box is not correct:
![image](https://user-images.githubusercontent.com/20796832/53948751-d0122e00-40c8-11e9-86f3-f8eda2c491d4.png)
and then when it is pasted:
![image](https://user-images.githubusercontent.com/20796832/53948805-f2a44700-40c8-11e9-8e22-d7b8f50b07af.png)
The colon and space are missing and the commits are not linked in Jira.

**Comment by IEVin** [comment]
> FYI, I have downloaded the latest source and compiled but even though there is no exception any longer

This bug is only reproduced in the release/3.00 branch  for me.

>the text pasted into the commit box is not correct

The text template can be configured in the settings but it is not applied in the pop-up.

**Comment by PaulAdams-Conti** [comment]
Sorry for the confusion, my mistake. It had been working before so I assumed (wrongly) that I hadn't changed anything in the settings, but that was not the case. 🙄

**Comment by RussKie** [comment]
Is this still a problem in the latest master?
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by gerhardol** [comment]
The portable works fine, have not tested the installer

**Comment by RussKie** [comment]
Let's presume it is fixed, thank you.

**Comment by zroytman** [comment]
Hi, i'm using GitExtensions 3.1.1 and have a placeholder {CustomFields} in the Jira Hint Comment plugin definition. Using this placeholder as is returns me the message that this is a collection. How can i specify the custom field from this collection? The required custom field is "Application". Tried several ways like {CustomFields["Application"]}, {CustomFields("Application")}. {CustomFields.Application}, etc... getting error messages.
Please help.
Thanks.

**Comment by zroytman** [comment]
> Hi, i'm using GitExtensions 3.1.1 and have a placeholder {CustomFields} in the Jira Hint Comment plugin definition. Using this placeholder as is returns me the message that this is a collection. How can i specify the custom field from this collection? The required custom field is "Application". Tried several ways like {CustomFields["Application"]}, {CustomFields("Application")}. {CustomFields.Application}, etc... getting error messages.
> Please help.
> Thanks.

H! Any updates? Thanks.

**Comment by IEVin** [comment]
There is no way to get an array element now. GE using [NString](https://github.com/thomaslevesque/NString) for parsing jira issue object but NString can only get fields and properties from top level object.
In fact fields like AffectsVersions, CustomFields, FixVersions, Labels is useless now.
This is an NString restriction.

**Comment by zroytman** [comment]
> There is no way to get an array element now. GE using [NString](https://github.com/thomaslevesque/NString) for parsing jira issue object but NString can only get fields and properties from top level object.
> In fact fields like AffectsVersions, CustomFields, FixVersions, Labels is useless now.
> This is an NString restriction.

Thanks for the explanation. Is this functionality presented in the GE roadmap? If so, any expectation of the implementation of it? Thanks.

**Comment by pmiossec** [comment]
> Is this functionality presented in the GE roadmap?

There is no roadmap other than a list of bug that we'd like to see fixed. See https://github.com/gitextensions/gitextensions/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.2.0

But we live with contributions (we are all volunteers), so if you want to see something fixed or improved, please contribute.

**Comment by IEVin** [comment]
> Thanks for the explanation. Is this functionality presented in the GE roadmap? If so, any expectation of the implementation of it? Thanks.

I think no. You can add new issue about this. I think is a good idea add issue in [NString](https://github.com/thomaslevesque/NString) repository and just update it after implement this feature.

**Comment by RussKie** [comment]
I'm more than happy to see NString gone, if it'd help in fixing the issue.

**Comment by zroytman** [comment]
> > Thanks for the explanation. Is this functionality presented in the GE roadmap? If so, any expectation of the implementation of it? Thanks.
> 
> I think no. You can add new issue about this. I think it's a good idea add issue in [NString](https://github.com/thomaslevesque/NString) repository and just update it after implement this feature.

Opened a new issue in NString repository:
https://github.com/thomaslevesque/NString/issues/13#issue-460333737

**Comment by IEVin** [comment]
Now GE just getting jira issue and put it in StringTemplate.Format(...) with user format without any aditional parsing ([click](https://github.com/gitextensions/gitextensions/blob/7770ed64ca42538d03a47185697e28f473aabe1f/Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs#L291)). 
Either add this feature in NString or implement formatter like NString itself.

**Comment by pmiossec** [comment]
>Opened a new issue in NString repository:

@zroytman I think that your issue title and description should be rewritten.
All the information you provided talk about GitExtensions which the developer of NString should not know of.
That don't help him understand what is the problem you want him to fix (I don't understand it neither).

Your text should be written in the point of view of the `NString` library perhaps with some source code examples.

**Comment by zroytman** [comment]
> > Opened a new issue in NString repository:
> 
> @zroytman I think that your issue title and description should be rewritten.
> All the information you provided talk about GitExtensions which the developer of NString should not know of.
> That don't help him understand what is the problem you want him to fix (I don't understand it neither).
> 
> Your text should be written in the point of view of the `NString` library perhaps with some source code examples.

As i don't understand what is the real problem (NString etc...), i just describe my issue. No source code examples to add... i just asked why cannot i use specific field from CustomFields placeholder if GE Jira Hint Comment plugin. You guys explained here that the reason is the limitations of NString and i opened a relevant case in NString repository. But i even don't know what is NString.
