### ISSUE TITLE
Blank screen on commit history

### ISSUE THREAD

**Issue by soonheng1005** [gitextensions/gitextensions#6161]
Currently using Git Extension v2.51.04. After installing v3.0.0 on Windows 10, observed blank screen display on the commit history.
It shows OK during start-up. But every scroll to each commit line will cause the line to disappear. At times, the commit history is blanked out. 

It seems the problem happened when the repository name has spaces? But we do not have this problem in older v2.51.04 with the same repository name.

![git_v3_0_0](https://user-images.githubusercontent.com/46981794/51648653-47c64680-1fbc-11e9-805d-4f683ba3b253.png)

![git_v3_0_0 blank out](https://user-images.githubusercontent.com/46981794/51648716-9d025800-1fbc-11e9-97e9-1a38d17c194e.png)

**Comment by vbjay** [comment]
Please open GE to the Dashboard.   Press f12.  Check callstack checkbox.  Open a repo and cause this to happen.  Export the log and attach as a file here.

**Comment by soonheng1005** [comment]
Attached is the command log. Thanks.

[Git command_log.txt](https://github.com/gitextensions/gitextensions/files/2789920/Git.command_log.txt)

**Comment by vbjay** [comment]
As an experiment, Please try a repo with no spaces in any file names or folder names and test to see if it does the same thing.

**Comment by vbjay** [comment]
Also, does this repo have any submodules?  If so, Please navigate to all of teh submodule paths and tell us if the .git item is a file or a folder.

**Comment by soonheng1005** [comment]
We have few repo with no spaces and none of them have display issue.

This repo (name with space) has submodules and it has display issue.

We do have another repo (name without spaces) that link to the same submodules as the repo name with space, and it does not have display issue.

Those submodules have .git folder with all the hooks, info, refs, etc folders in it.

**Comment by vbjay** [comment]
A submodule should not have a .git folder.  You should have a .git file like this 
![image](https://user-images.githubusercontent.com/3629489/51650960-2df31800-1f58-11e9-959e-e11465c6a57a.png)

You should have a .gitmodules file in the main repo like this

![image](https://user-images.githubusercontent.com/3629489/51651006-59760280-1f58-11e9-8fc3-ee4fc818cc2c.png)

You should have ran git submodule update --init --recursive and not git clone to init a submodule.

**Comment by vbjay** [comment]
Thank you for verifying the spaces issue.  Related issue #4097

**Comment by RussKie** [comment]
I feels related to #6071

**Comment by soonheng1005** [comment]
Tested and the issue is fixed in v3.1.1

**Comment by RussKie** [comment]
Thank you for following up on it.
