### ISSUE TITLE
Problems calling git from inside wsl (windows bash)

### ISSUE THREAD

**Issue by dmtr81** [gitextensions/gitextensions#6164]
I am trying to use git instance that is installed in WSL.

For that pupose I use the following proxy file git.bat
```
@echo off
setlocal enabledelayedexpansion
set command=%*
set find=C:\Users\%USERNAME%\AppData\Local\Temp\git-commit-msg-.txt
set replace=/mnt/c/Users/%USERNAME%/AppData/Local/Temp/git-commit-msg-.txt
call set command=%%command:!find!=!replace!%%
If %PROCESSOR_ARCHITECTURE% == x86 (
    C:\Windows\sysnative\bash.exe -c 'git %command%'
) Else (
    bash.exe -c 'git %command%'
)
```

It just send commands to wsl git. Git Extensions is configured to use this git.bat file. It start perfectly, shows repository but some commands fail with error
```
"D:\web\git.bat" pull --progress "origin"
'D:\web\git.bat" pull --progress "origin' is not recognized as an internal or external command,
operable program or batch file.
```

But if I run `"D:\web\git.bat" pull --progress "origin"` in windows shell directly, it works. What can be the reason of the error in Git Extensions?

**Comment by GintasS** [comment]
Abandoning this because of age and lack of discussion.

**Comment by gerhardol** [comment]
WSL improvements since about 3.3, \\wsl$ can be used
Further improvements discussed in #8307
