### ISSUE TITLE
Appveyor build hangs

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#6172]
## Current behaviour

Builds intermittently hang and get killed by timeout.
However the same builds succeed on re-run.

For example [this build](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/21850786/tests) has not modified any code files, however it hang on `GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelTests.RepoObjectTree_should_order_should_display_inactive_after_active_nodes` test in GitUITests.dll.

It looks like tests from `GitUITests.CommandsDialogs.CommitDialog.FormBrowseLeftPanelTests` are intermittently causing builds to fail.
For example:
* [build 21850786](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/21850786/tests)
* [build 21856427](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/21856427/tests)
* [build 21876661](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/21876661/tests)

## Expected behaviour

All builds finish within reasonable time (~15min) before the timeout

**Comment by RussKie** [comment]
I've raised a ticket to Appveyor - https://help.appveyor.com/discussions/problems/19659-intermittent-hanging-builds

**Comment by RussKie** [comment]
> From: Appveyor Support staff
>
> Set up [non-blocking RDP](https://www.appveyor.com/docs/how-to/rdp-to-build-worker/). When it hung next time connect to build VM and see what happens. It seems like GUI test issue, so you hopefully will see the problem (some dialog box waiting for input or similar) right away.

**Comment by RussKie** [comment]
This looks like a race condition, the test has finished and cleaned up a temp folder, whilst `LoadDescribeInfoAsync` is chugging along on a background thread tries to run a git command against a deceased repo...

**Comment by vbjay** [comment]
Might need a fixture that does the repo setup and cleanup.

**Comment by sharwell** [comment]
@RussKie You need to make sure that operation is passed an appropriate `CancellationToken` where cancellation is requested at the end of the test, generally by disposing of something that owns the operation.

**Comment by RussKie** [comment]
This is the offending code
https://github.com/gitextensions/gitextensions/blob/3dd56e0f9633c993a4de081ecf0faa09d2e06dc0/GitUI/CommitInfo/CommitInfo.cs#L228-L261

@sharwell how would you suggest to solve the race condition? I don't think we could solve it by setting various `AppSettings` settings on or off, as not all background threads are behind those.
I'm not sure adding some sort of timer to the tests is a good solution either...

**Comment by sharwell** [comment]
It also sounds like the asynchronous operation might not be tracked properly. Otherwise it should end up waiting for the operation to complete here:

https://github.com/gitextensions/gitextensions/blob/e869f5fd5feacb0211b55a1e53d1695ea50b687b/UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs#L57

If that is the point where the hang occurs, we can add a timeout to that join operation and force a test to fail if it exceeds the timeout.

**Comment by sharwell** [comment]
It seems like you should just call `_asyncLoadCancellation.Dispose()` when the control is disposed. That will trigger cancellation of the token on line 230 and presumably the ongoing asynchronous operations.

**Comment by RussKie** [comment]
Thank you, I'll give it a go
