### ISSUE TITLE
Left panel - Align local and remote branches context menu

### ISSUE THREAD

**Issue by seshonaar** [gitextensions/gitextensions#6179]
## Feature description

Hello Git Extensions 😄 !

I would like to propose a feature that I personally believe it could fantastically improve the usability of the left 'branches' panel. Namely have the context menu that is available in the log view on the branch list entry. This would remove the need to:
- show all branches (clicking a branch that is not visible does nothing, and it's very frustrating, as it is almost always true when I want to rebase. I usually keep the filter to 'current branch')
- extra 'click to highlight'. IMO this should not be the default action, and it should instead be an entry in the context menu.

Thank you and best regards!
Andrei

LE: It seems that what I actually want is to have the context menu that is available on the remote branches. At the time I wrote this I had no idea that the remote branches have special abilities 😸 

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Thank you for your suggestions. 
Would you be so kind and raise a separate ticket for each, as it would help us to have relevant discussions about each request and, once/if we all agree on how to implement it, track the progress.

**Comment by vbjay** [comment]
Fyi. We do have a feature to highlight a branch. Go to view menu. You can
keep it show all branches and still see what is relavant to the current
branch by using this feature.

**Comment by RussKie** [comment]
I think "highlight branch" option would be a great addition.

![image](https://user-images.githubusercontent.com/4403806/51838693-30d87900-235b-11e9-8198-55d5891a2452.png)

**Comment by seshonaar** [comment]
@vbjay : Thank you for suggesting 'Highlight selected branch'. It doesn't work though as long as I have the filter 'current branch only`. Also, I as said, I don't really need to see the branch, I just want the context menu 😄 . Also, I don't want the discussion to diverge: the context menu is the star of the show here ⭐️

**Comment by vbjay** [comment]
That's what I meant. Show all branches and then use highlight.

**Comment by seshonaar** [comment]
Interestingly enough, I just right clicked on a remote branch (I never do that haha) and I got 'rebase' there! Lo and behold! So it seems the local branches have a simplified context menu on purpose...  I have confusing thoughts now 😄 .

**Comment by seshonaar** [comment]
I'm closing this, as I'm good now with the new found extended menu on the remote branches. Still, I don't see any good reason why the local branches have "less privileges". The functionality is available in the log view, so why not being consistent?

**Comment by RussKie** [comment]
To confirm, you would like to have this context menu in the left panel
![image](https://user-images.githubusercontent.com/4403806/51907128-11545580-241a-11e9-8108-38baf533a5c7.png)

Is that correct?

**Comment by seshonaar** [comment]
@RussKie  I must admit, _that_ context menu makes the most sense for me, as it brings full power to the branches panel. So yes, that's what I would like.
Otherwise a _fair_ solution is to add the context menu section containing `Rebase` that is available for remote branches
![image](https://user-images.githubusercontent.com/19486271/51935097-cc2a2680-240d-11e9-81ff-96dfb76ef5d8.png)

**Comment by RussKie** [comment]
Would you like to have a go at implementing it?

**Comment by seshonaar** [comment]
@RussKie Sure, why not! I'll take a look at it over the weekend!

**Comment by seshonaar** [comment]
Alright, I got Rebase there for a starter:
![image](https://user-images.githubusercontent.com/19486271/51960907-8e57ed00-2463-11e9-95c2-18f7c7cf03f8.png)

**Comment by RussKie** [comment]
Please align items order and positioning with the remote branches
![image](https://user-images.githubusercontent.com/4403806/51963448-bb35ef80-24b7-11e9-9255-b6c08158c131.png)

**Comment by amaiorano** [comment]
@seshonaar let me know if you need any help. I've quite a bit of experience with the left panel. Also, as I mentioned in [your other issue](https://github.com/gitextensions/gitextensions/issues/6180), the context action code for the left panel needs some refactoring. But for now, I recommend you try to keep your changes as straightforward as possible.

**Comment by seshonaar** [comment]
Alright, I created a PR (= `P`roduction `R`eady 😄 ). Looking forward for feedback!
