### ISSUE TITLE
Left panel doesn't re-select branch after refresh

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#6181]
## Current behaviour

Select any local branches, hit refresh, the previously selected node isn't selected any longer.
![pubsub-issues](https://user-images.githubusercontent.com/4403806/51889887-c244fb00-23ee-11e9-9bd4-2cce086275d4.gif)

## Expected behaviour

The selection is restored.

## Did this work in previous version of GitExtensions

v3.0 is exhibiting this behaviour.

## Environment

- Git Extensions 3.0.1.4933
- Build a269358b22a5dc1ea36928bb87f9e535de76a058
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 144dpi (150% scaling)

**Comment by amaiorano** [comment]
Okay, I know what's going on here. This happens because there's no active branch, so when the left panel refreshes, it won't select one of the branch nodes. I will fix this as part of https://github.com/gitextensions/gitextensions/pull/5669.

**Comment by amaiorano** [comment]
Fixed in https://github.com/gitextensions/gitextensions/pull/5669
