### ISSUE TITLE
After a date change on my computer and accidentally committing on a wrong date, something went wrong

### ISSUE THREAD

**Issue by hofftari** [gitextensions/gitextensions#6190]
## Current behaviour

I needed to try out changing my date to 2018 to test a feature I'm developing. But when I wanted to commit, I accidentally commmitted while having the wrong system date. After resetting my branch to an earlier commit I now have a weird issue with the UI (see screenshot).

I have deleted all my appData folders for GitExtensions, removed the repository and cloned a fresh one from Github, yet these two rows are still showing up. They are also based on the active branch, so if I check out an earlier branch, these two rows show up just above that row.

Edit: This seem to show up on all repositories now, even those I haven't touched for months.

## Steps to reproduce

1. Make a commit with the system date set to one year before today
2. Change to current date and make a hard reset to the commit before

## Screenshots

![image](https://user-images.githubusercontent.com/11408531/51977517-f91b1f80-2487-11e9-94dc-03d136428ae6.png)

## Environment

- GitExtensions version: 3.01.4933
- GIT version: 2.20.1.windows.1
- OS version: Windows 10 x64
- .NET version: 4.5.1

**Comment by vbjay** [comment]
Those are artificial commits that represent the working directory and the staged files.  It's not a bug.  
![image](https://user-images.githubusercontent.com/3629489/51978887-8bf09580-2459-11e9-8fb8-e739b6884644.png)
![image](https://user-images.githubusercontent.com/3629489/51978912-9e6acf00-2459-11e9-8faa-de748cc44258.png)


Stage the edit
![image](https://user-images.githubusercontent.com/3629489/51978990-dbcf5c80-2459-11e9-929e-602d32c9eb9b.png)

**Comment by RussKie** [comment]
These are artificial commits, please refer to the docs:
* https://git-extensions-documentation.readthedocs.io/en/master/settings.html?highlight=artificial#git-extensions-performance-working-dir-changes
* https://git-extensions-documentation.readthedocs.io/en/master/settings.html?highlight=artificial#git-extensions-performance-show-number-of-changed-files-for-artificial-commits

![image](https://user-images.githubusercontent.com/4403806/51979027-1b408c00-24e0-11e9-9a58-68781c947321.png)
