### ISSUE TITLE
Can't delete a repository included in the categories of the dashboard

### ISSUE THREAD

**Issue by JcEstevez** [gitextensions/gitextensions#6192]
## Current behaviour

Hi, the problem at issue is the follow.

When is created a new category in the Dashboard, and you include a repository in it, in some moment when i need delete the repository assigned in this category it not is deleted.

## Expected behaviour

We should have the possibility of delete an repository included into a created category.

Other added related, not much important, but that can be interesting, is the possibility of we can assign a name to a repositories/projects assigneds in the Dashboard, and have too, the posibility of hide the recents repositories.

With this modifications and fixes, we would have more confort in the project managments.

## Steps to reproduce

1. You do right click in a recent repository and select **Categories -> Add new...**, you will assign a name to the new category and press in ok.
2. When it has been created the new category, you do right click again in the repository located in it, and select **Remove project from the list**.
3. You will can see that it project can't has been deleted, and you has having the bug.

## Screenshots

![Reproducing issue](https://i.imgur.com/wwTIlNw.jpg "Reproducing issue")

## Did this work in previous version of GitExtensions

I don't know it.

## Environment

- GitExtensions version: 3.00.00.4433
- GIT version: 2.19.1.windows.1
- OS version: Microsoft Windows NT 10.0.17134.0
- .NET version: .NET Framework 4.7.3260.0

**Comment by RussKie** [comment]
Please fill the issue as per the issue template providing as much information as possible, including but not limited to step to reproduce, screenshots, logs etc.

**Comment by JcEstevez** [comment]
Hi RussKie, i think that now is correct, thank you for your response.

**Comment by JcEstevez** [comment]
> Please fill the issue as per the issue template providing as much information as possible, including but not limited to step to reproduce, screenshots, logs etc.

Hi RussKie, i think that now is correct, thank you for your response.

**Comment by RussKie** [comment]
The provided screenshot looks like it is from Linux not Windows. What version are you running and what commit has it been build from?

Please provide information about your environment as can be found on "About" form (v3.0).
![image](https://user-images.githubusercontent.com/4403806/52117338-941e2000-2667-11e9-9d77-1431ef5181a9.png)


> * **SO:** Windows Xp

We don't support Windows XP, minimum W7.
Please refer to the [readme](https://github.com/gitextensions/gitextensions/blob/master/README.md)

**Comment by vbjay** [comment]
It's not linux.  They are using windows classic ui.  No Aero and other stuff.

**Comment by JcEstevez** [comment]
I have update the tecnichal specification and sorry, i did tests in Windows 7 and Windows 10.
I has failed for writting Windows Xp before...

**Comment by vbjay** [comment]
This is our bug template

```
<!--
    ⚠️ Review existing issues to see whether someone else has already reported your issue.

    📖 Please also read CONTRIBUTING.md.
-->

## Current behaviour

<!-- Be as specific and detailed as possible to help us identify your issue. -->


## Expected behaviour



## Steps to reproduce

<!-- Take some time to try and reproduce the issue, then explain how to do so here. -->


## Screenshots

<!-- Screenshots can be very useful in helping to understand the issue you're facing. -->



## Did this work in previous version of GitExtensions

<!-- If so, which version? -->


## Environment

<!-- Use Help/About in Git Extensions to copy this information to the clipboard automatically. -->

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 


## Diagnostics

<!-- If relevant, as described at https://github.com/gitextensions/gitextensions/wiki/Diagnosing-problems -->



<!--
    ❤️ Git Extensions? Please consider supporting our collective:

    👉 https://opencollective.com/gitextensions
-->

```

When filled out it looks like




## Current behaviour




## Expected behaviour



## Steps to reproduce




## Screenshots





## Did this work in previous version of GitExtensions




## Environment



- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 


## Diagnostics

**Comment by JcEstevez** [comment]
> This is our bug template
> 
> ```
> 
> 
> ## Current behaviour
> 
> 
> 
> 
> ## Expected behaviour
> 
> 
> 
> ## Steps to reproduce
> 
> 
> 
> 
> ## Screenshots
> 
> 
> 
> 
> 
> ## Did this work in previous version of GitExtensions
> 
> 
> 
> 
> ## Environment
> 
> 
> 
> - GitExtensions version:
> - GIT version: 
> - OS version: 
> - .NET version: 
> 
> 
> ## Diagnostics
> 
> 
> 
> 
> 
> 
> ```
> When filled out it looks like
> 
> ## Current behaviour
> ## Expected behaviour
> ## Steps to reproduce
> ## Screenshots
> ## Did this work in previous version of GitExtensions
> ## Environment
> * GitExtensions version:
> * GIT version:
> * OS version:
> * .NET version:
> 
> ## Diagnostics

Ok, more later i will fix my contribution with more calm. Thank you very much!

**Comment by JcEstevez** [comment]
Hi, i  have updated the issue.

**Comment by RussKie** [comment]
Confirmed, the current behaviour removes a matching entry from the "Recent" list, not from the selected category.

**Comment by RussKie** [comment]
Please try this build and confirm the fix
https://ci.appveyor.com/api/buildjobs/f38grjk0bcjwfptd/artifacts/GitExtensions-Portable-3.0.2.5186.zip

**Comment by JcEstevez** [comment]
> Please try this build and confirm the fix
> https://ci.appveyor.com/api/buildjobs/f38grjk0bcjwfptd/artifacts/GitExtensions-Portable-3.0.2.5186.zip

Tested, it works.
