### ISSUE TITLE
auto completion breaks on second commit

### ISSUE THREAD

**Issue by penCsharpener** [gitextensions/gitextensions#6197]
## Current behaviour

auto completion inserts only \t tab during the second commit (see Steps to reprocude)

## Expected behaviour

auto completion works the same as when I just opened the commit dialog

## Steps to reproduce

Options: 
* Close dialog after each commit = false
* Close dialog when all ... = true
* Refresh dialog on form focus = false

stage a few but not all changes
write commit message
commit changes and start an new commit from the same window
stage changes, write commit message using auto completion
when hitting tab on auto completed word only a tab \t seem to be inserted, not the entire word
when I unfocus the commit window and refocus it again it seems to fix autocompletion

## Did this work in previous version of GitExtensions

not sure, first time really working with GitExtensions

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by ignacioerrico** [comment]
I can't reproduce this issue. Can you confirm if this is correct?

Using these options, as indicated:

![image](https://user-images.githubusercontent.com/3200214/52904614-b2227d80-322e-11e9-8e68-ab66c99d2055.png)

I committed a file. The commit window was **not** closed. I staged another file, and started to type this commit message:

![image](https://user-images.githubusercontent.com/3200214/52904629-e5650c80-322e-11e9-9a3d-8a04b68c22c7.png)

When I pressed `<TAB>` on the selection, the text `BinarySearch.cs` was inserted, **not** a tabulation.

Tested on:

- Git Extensions 3.0.1.4933
- Build a269358b22a5dc1ea36928bb87f9e535de76a058
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by penCsharpener** [comment]
I can test it again next week. There is a degree of randomness involved but maybe it's already fixed in GitExt 3.0.1 or 3.0.2 Will update next week and let you know if it happens again.

**Comment by penCsharpener** [comment]
I haven't been able to report this either since upgrading to 3.0.2
I close it for now and should it pop up again and I can actually figure out exactly step I'll open this again
