### ISSUE TITLE
Option `Ignore leading and trailing whitespace changes` not working as expected

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions#6198]
## Current behaviour

The option `Ignore leading and trailing whitespace changes` in the Diff viewer and commit dialog does not work correctly.

## Expected behaviour

1. It should ignore all whitespace changes at the beginning and the end of a line.
2. It should not ignore any whitespace changes somewhere within the line.

## Steps to reproduce

Consider the following example:
![bugwhitespace1](https://user-images.githubusercontent.com/46861028/52060112-d5310a00-256b-11e9-8669-d3bea4ad7888.png)

When clicking on `Ignore leading and trailing whitespace changes` I'd expect lines 1, 3, 5 and 7 to be excluded from view.
Consequently, only lines 2 and 6 shall remain to be shown as different. Instead, I get this:
![bugwhitespace2](https://user-images.githubusercontent.com/46861028/52060119-d95d2780-256b-11e9-851d-6a3dd5b23b60.png)

## Did this work in previous version of GitExtensions

No. At least version 2.51.05 has the same issue.

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by mast-eu** [comment]
I dug a bit into the code:

- `Ignore leading and trailing whitespace changes` adds the `--ignore-space-change` attribute to `git diff`
- `Ignore all whitespace changes` adds the `--ignore-all-space` attribute to `git diff`

However, `--ignore-space-change` does not actually remove leading and trailing whitespace changes.
Here's the description from [git documentation](https://git-scm.com/docs/git-diff#git-diff---ignore-space-change):
> -b
> --ignore-space-change
> Ignore changes in amount of whitespace. This ignores whitespace at line end, and considers all other sequences of one or more whitespace characters to be equivalent.
> 
> -w
> --ignore-all-space
> Ignore whitespace when comparing lines. This ignores differences even if one line has whitespace where the other line has none.

**Comment by RussKie** [comment]
@mast-eu could you send a PR with a fix?
