### ISSUE TITLE
QuickPull's hotkey is not working

### ISSUE THREAD

**Issue by glacjay** [gitextensions/gitextensions#6200]
## Current behaviour

I've reset all hotkeys to defaults, then press QuickPull's hotkey ctrl-shift-p, but the command been executed is `git fetch`, not `git pull`.

## Expected behaviour

`git pull` should be executed when I press ctrl-shift-p.

## Steps to reproduce

Just reset all hotkeys to default, and press ctrl-shift-p.

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Would you like to try this build https://ci.appveyor.com/api/buildjobs/iona492quavhndbg/artifacts/GitExtensions-Portable-3.0.2.5120.zip and see if it is fixed

**Comment by RussKie** [comment]
@glacjay could you please test this build
https://ci.appveyor.com/api/buildjobs/nadckhnva1hy9ljc/artifacts/GitExtensions-Portable-3.0.2.5223.zip
