### ISSUE TITLE
FormCommit: Commiter are no more displayed but link is clickable

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#6201]
## Current behaviour

The commiter info are not displayed but the link is there clickable.
When the bug is debbuged, the link appears. [Heisenbug](https://en.wikipedia.org/wiki/Heisenbug)?

## Expected behaviour

We could see the commiter info.

## Steps to reproduce

Open Commit Form.

## Screenshots

![image](https://user-images.githubusercontent.com/460196/52118067-9eafc980-2615-11e9-8135-26290e3157ca.png)

## Did this work in previous version of GitExtensions

Yes:

* 2.51 for sure
* 3, I don't know

## Environment

- Git Extensions 3.1.0
- Build 5ec1507ab077027c3508f4429d8d7e0e2210839d
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 192dpi (200% scaling)

## Diagnostics

Putting `UpdateAuthorInfo()` call in `OnShown()` instead of in `OnApplicationActivated()` solve the problem.

/cc @drewnoakes I see that you worked on it in a688346a21bd0ba9f22d0294c3547703e5a2ea20
Do you reproduce and have a idea on that?

**Comment by RussKie** [comment]
Confirming the issue, it exists in the master but not in 3.0.1 branches.

**Comment by RussKie** [comment]
The regression is caused by changes in #6134

**Comment by vbjay** [comment]
@mstv We still need to do some things in activated event.

**Comment by RussKie** [comment]
I have a fix for it, sorting tests atm
