### ISSUE TITLE
Portable version should also import old settings

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#6205]
## Feature description
Portable version should also import old settings

## Environment

- GitExtensions version: v3.0.1.4933
- GIT version: v2.19.1.windows.1
- OS version: Windows 7 Pro
- .NET version:

**Comment by vbjay** [comment]
Portable reads from the same location as where the exe is located. We have it set up so our ci builds are portable but the config file makes it act like non portable. The portable releases are fully portable.  Configure GE as you desire in portable. Copy to a flash drive.

**Comment by RussKie** [comment]
@klorinczi could you please share your vision for this FR.

**Comment by klorinczi** [comment]
My case:
The upgrade process of Gitextensions v2.5 (the installed version) was the following:
I copied the portable version over it and continue using the new version with the same settings. 

Now I tried the upgrade to the 3.x version. 
Made a copy of the v2.5 directory, copied the 3.x portable version over it, but the settings were not taken, just started with an empty dashboard.

**Comment by klorinczi** [comment]
Good to know.

In that case there should be an option to turn on portable mode or not.

In case the portable mode is turned on it copies the settings from %appdata%\gitextensions folder to portable location.
If at portable location a setting file already exists, should ask user to overwrite it or not. Also a renamed backup .bck should be kept of overwritten one.

**Comment by vbjay** [comment]
Not that simple.  It is an application config file change.  Also if it is on.  It IS portable.  You want it to copy settings each time it runs?  Not a good idea.  Just copy the settings from your %appdata% folder.

**Comment by klorinczi** [comment]
The portable option should just set the path from where to load the settings file. It is an additional step to copy the settings file if it is missing from the target folder.

**Comment by vbjay** [comment]
Do you not get the idea of portable?  It should run self contained.  The whole idea is you run from a flash drive.  You can also configure it separately from an installed version.  So either configure it as you like in the portable, or copy settings from the %appdata%.

We will not:
- Nag the user about copying settings at start
- Just copy settings for the user

We do have more work to make it really and fully portable.  Things like handling git and other tools finding.  

The whole point is the fact that it is self contained.

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/issues/5823
