### ISSUE TITLE
Reorder Categories & Projects

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#6206]
## Feature description
Please add feature to reorder Categories & Projects.
The minimum what is required the old Move down, Move up.
But additionally reorder by dragging categories & projects would be also a good feature.

## Environment

- GitExtensions version: v3.0.1.4933
- GIT version: v2.19.1.windows.1
- OS version: Windows 7 Pro
- .NET version:

**Comment by RussKie** [comment]
Please provide more context for your feature request. I can speculatively guess it is about the dashboard, however I am not 100% sure.

**Comment by RussKie** [comment]
Duplicate of #5511

**Comment by klorinczi** [comment]
My issue is more than #5511 as I also suggested ordering of project items.
