### ISSUE TITLE
Orphan commit badly displayed in Revision graph

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#6210]
## Current behaviour

In v3, the orphan commit in the remote `origin/gh-pages` doesn't belong to the branch `choose_password_types` (see the gray color of the commit marker) so it shouldn't be displayed inside the branch graph.

![image](https://user-images.githubusercontent.com/460196/52170437-94431c00-274a-11e9-8226-79d2b982f3a8.png)

## Expected behaviour

Display the commit outside the branch graph.

## Steps to reproduce

Clone and open the repository `https://github.com/pmiossec/UniquePasswordBuilder.git`

## Did this work in previous version of GitExtensions

Yes, at least 2.xx

## Environment

- Git Extensions 3.1.0
- Build bb67b346e81695706e752352488e3a6dba547902
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

## Diagnostics

Perhaps a regression introduced by the work on revision graph in #5610 /cc @spdr870

**Comment by spdr870** [comment]
I will look into this.
