### ISSUE TITLE
The method "RestoreSelectedFiles" should always update "SelectedIndex" of both staged and unstaged file list

### ISSUE THREAD

**Issue by monoblaine** [gitextensions/gitextensions#6212]
## Current behaviour

Unstaging a file in the commit window makes that file *appear* selected in "unstaged file list" area. But the truth is that the file is only highlighted, not *selected*. The actual selected file is the first one in the list.

## Expected behaviour

The unstaged file should both be the highlighted and the selected file.

## Steps to reproduce

1. Make changes in several files (like at least 4) in a repository.
2. Open gitextensions commit window.
3. Stage the last file in the list (Either double click on the file name or highlight the file and press <kbd>S</kbd>.
4. Unstage that file by either double clicking or pressing <kbd>U</kbd>.
5. Press <kbd>&uarr;</kbd> and see that nothing happens (because the actual selected file is the first one).
6. Press <kbd>&darr;</kbd> and see that the second file gets highlighted.

## Screenshots

This is the initial view:

![image](https://user-images.githubusercontent.com/540974/52183373-57ddf180-2818-11e9-875a-34e87de70cbf.png)

`contributors.txt` is staged:

![image](https://user-images.githubusercontent.com/540974/52183386-6a582b00-2818-11e9-91a0-694ee58bb1d3.png)

`contributors.txt` is unstaged (either by double clicking on the file name or by pressing <kbd>U</kbd> while the file is selected:

![image](https://user-images.githubusercontent.com/540974/52183397-996e9c80-2818-11e9-9fc0-30be243743ef.png)

The result of pressing <kbd>&darr;</kbd>:

![image](https://user-images.githubusercontent.com/540974/52183402-b30fe400-2818-11e9-8d84-8c3347fb0e51.png)

## Did this work in previous version of GitExtensions

Version 2.51 also had this problem.

## Environment

- GitExtensions version: 3.00.00.4433
- GIT version: 2.20.1.windows.1
- OS version: Microsoft Windows NT 10.0.17134.0
- .NET version: .NET Framework 4.7.3324.0

## Proposed fix

https://github.com/monoblaine/gitextensions/commit/62e5287a8a2f4e8bb332bf9711ef8b0df25dfbfc#diff-16d3bf20df9b2330e5146f334a6e7f04

After some debugging I've found that the method `RestoreSelectedFiles` (in `FormCommit.cs`) does not call `SelectStoredNextIndex` after updating `_currentFilesList.SelectedItems`. But it *should* call that local function bacause updating `SelectedItems` makes a call to `StoreNextIndexToSelect` (in `FileStatusList.cs`)

*(This is my first contribution attempt. Hope to send a PR if everything's all right.)*

**Comment by pmiossec** [comment]
>(This is my first contribution attempt. Hope to send a PR if everything's all right.)

Do the PR. That way we could discuss about it there...
