### ISSUE TITLE
Add support for GVFS to enable use of git in large enterprice repositories

### ISSUE THREAD

**Issue by sebnil** [gitextensions/gitextensions#6214]
Git is combersome to use if your repo is large (a few Gb) since you need to clone the whole repo to your local computer to work with it. Git LFS does not deal with this issue (you still need to fetch the large files and there is no simple way to only clone a certain subtree). 

Please add support for GVFS since that would solve this issue.
https://www.vfsforgit.org/

**Comment by RussKie** [comment]
Could you please elaborate what exactly GE needs to provide to support GVFS.

**Comment by pmiossec** [comment]
>Could you please elaborate what exactly GE needs to provide to support GVFS.

I didn't know either and thought it was transparent. 

But it seems that there are 2 commands to support (to clone and unmount). 

See: https://github.com/Microsoft/VFSForGit/blob/master/Readme.md#trying-out-vfs-for-git

Even if I don't really understand the meaning of 'gvfs unmount' and when it should be used. 

@sebnil is that all?

**Comment by pmiossec** [comment]
It's difficult to find documentation and I'm not sure that's the good time to handle it as it will be renamed... 

https://github.com/Microsoft/VFSForGit/projects/4

**Comment by sebnil** [comment]
> Could you please elaborate what exactly GE needs to provide to support GVFS.

gvfs clone as a start. So when you do a clone, there should be an option to do it with gvfs. 

> It's difficult to find documentation and I'm not sure that's the good time to handle it as it will be renamed...

Maybe you are right. I do believe this will be important to support when the name change has been done. It is a really good feature. (Tower suggests that they support it but it doesn't seem to be well advertised yet https://www.git-tower.com/blog/tower-win-1-2)

**Comment by vbjay** [comment]
Just a heads up. Vfs and lfs are mutually exclusive. You can't have smudge/clean filters with vfs in the same repo.

**Comment by gerhardol** [comment]
This is the type of functionality that is added to GE by someone that needs it.

Anyway, to develop and test VFSforGit a public server is needed too so unless there are public Azure servers (trial accounts hardly count), it will be hard to add this.
