### ISSUE TITLE
TeamCity Integration : errors when loading report web page

### ISSUE THREAD

**Issue by bouffa** [gitextensions/gitextensions#6217]
## Current behaviour

When I open a repository with a configured build server (TeamCity) integration, two popups show up with these error messages : 

- TypeError: Unable to get property 'ms__id1' of undefined or null reference
- TypeError: Unable to get property 'ms__id2' of undefined or null reference

When I go to the 'Build report' tab, more similar popups show up : 

- TypeError: Unable to get property 'ms__id5' of undefined or null reference
- TypeError: Unable to get property 'ms__id6' of undefined or null reference

And then I see a warning message from TeamCity in the header of the page : 

You are using an outdated version of the browser (Internet Explorer 10 or earlier) or IE compatibility mode is enabled.If you are using Internet Explorer 11, make sure compatibility mode is disabled.TeamCity only supports Internet Explorer 11.Contact JetBrains TeamCity support if this affects your TeamCity usage. 

## Expected behaviour

No error popups, no warning message in the Build report tab header.

## Steps to reproduce

It can be reproduced using the public TeamCity server following these steps : 

1. Clone https://github.com/acejump/AceJump repository
2. Open The repository with GitExtensions and configure the build server integration : 
* Check "Enable build server integration"
* Build Server Type : TeamCity
* TeamCity Server URL : https://teamcity.jetbrains.com/
* Project name : acejump
* Build Id Filter : acejump_buildplugin
* Check "Log as guest to display the build report"

3. Click Apply, OK, and reload the repository, and then go to the Build Report Tab

## Screenshots

![image](https://user-images.githubusercontent.com/209230/52263693-1476a680-2930-11e9-9ed8-c71c377f8bcd.png)

![image](https://user-images.githubusercontent.com/209230/52263715-25bfb300-2930-11e9-85d4-114a1cec5f61.png)

![image](https://user-images.githubusercontent.com/209230/52264759-a97a9f00-2932-11e9-9705-e3c88aa3034f.png)

![image](https://user-images.githubusercontent.com/209230/52264783-ba2b1500-2932-11e9-85ac-78c084751090.png)

## Did this work in previous version of GitExtensions

Yes, with previous GitExtensions version and mainly with previous TeamCity version, these popups used to not show up. 
On the other hand, the warning message about outdated version of the bowser is not new, it was displayed with older GitExtensions & TeamCity versions

## Environment

- Git Extensions 3.0.1.4933
- Build a269358b22a5dc1ea36928bb87f9e535de76a058
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)
- TeamCity : 2018.2.2 (build 61245)

**Comment by RussKie** [comment]
Can you please confirm that it is GE v3 and not TC 2018.2.2 is the actual cause of errors?
You can do it by installing v2.51 and test

**Comment by bouffa** [comment]
After verification, I have the same behavior with GE v2.5.1

**Comment by RussKie** [comment]
I would speculate the issue is with the new version of TC (not liking IE engine) and with GE using IE webview control.

**Comment by Samil2018** [comment]
Hello
I am having this error when in the "Quick view window" of the Tray Notifier, I click on the "changes" link of the Build.

Has anyone have a solution for this?

**Comment by fschmied** [comment]
The reason is probably that the WebBrowser control by default uses IE 7 emulation mode. [Rick Strahl explains on his blog](https://weblog.west-wind.com/posts/2011/may/21/web-browser-control-specifying-the-ie-version) how to change this by setting an application-specific registry key.

I'm going to test this manually.

**Comment by fschmied** [comment]
Okay, interestingly, this was already implemented in #2654 and #2817. TeamCity still thinks we're using IE < 10, though, and is generating script errors.

**Comment by RussKie** [comment]
I am afraid there is little we can do atm.

We could bring a chromium based browser control (e.g. cefsharp), but it would add a massive headache to the dev team and tens (if not hundreds) of megabytes to the install package.

...or we could wait for the MS chromium based browser to become public.

**Comment by pmiossec** [comment]
>...or we could wait for the MS chromium based browser to become public.

👍 

And it's not a big problem as we could disable the tab and still open the build report in the browser through the contextual menu.

**Comment by fschmied** [comment]
> I am afraid there is little we can do atm.

You're right, and this is obviously a TeamCity problem: I'm getting the same errors when navigating to TC in real IE 11 (and I've confirmed in F12 developer tools that Compatibility Mode was not enabled).

I've therefore raised a support issue with JetBrains.

> And it's not a big problem as we could disable the tab and still open the build report in the browser through the contextual menu.

Is there an option to disable the tab? I didn't find one at first glance.

I like the build status column in the list view a lot and I also use the "View build report in a browser" context menu action. I don't need the "Build report" tab at all, but as long as there's no way to disable it, opening GitExtensions (with a local repo open) will always cause two script error message boxes to be displayed.

**Comment by pmiossec** [comment]
>Is there an option to disable the tab? 

Disable "Show build result page"

![image](https://user-images.githubusercontent.com/460196/58176080-d2386180-7ca1-11e9-855f-60fca81f7da9.png)

**Comment by fschmied** [comment]
Silly me, I looked in the "View" menu. Thank you.

I'm not the original creator of the issue, but as this is a TC bug, I think it can be closed here. JetBrains support directed me to https://youtrack.jetbrains.com/issue/TW-58293.

**Comment by RussKie** [comment]
Thank you
