### ISSUE TITLE
Crash when double click on commit message field

### ISSUE THREAD

**Issue by Tainder** [gitextensions/gitextensions#6218]
## Current behaviour
CRASH

## Expected behaviour

Nothing i guess ?

## Steps to reproduce
Double click on text commit message and it crash

## Environment
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0

**Comment by RussKie** [comment]
Stack trace? Error logs? Screenshots? Screen grabs?

**Comment by Tainder** [comment]
![image](https://user-images.githubusercontent.com/14349732/52344605-7eb84580-2a1b-11e9-8720-6ba6fb235dca.png)

![image](https://user-images.githubusercontent.com/14349732/52344669-aa3b3000-2a1b-11e9-87f7-e8e86a371946.png)

**Comment by RussKie** [comment]
I can't seem to repro it.
Any specific steps to repro it?

**Comment by Tainder** [comment]
Hum weird because everybody at office can repro it

We just open commit window double click and text area

**Comment by vbjay** [comment]
4a7468d4492f671304c60e27a6909b0e84e32950

**Comment by RussKie** [comment]
Thank you @vbjay.

@Tainder please try v3.0.1 release

**Comment by Tainder** [comment]
Resolved with 3.0.1 thanks  ! :)
