### ISSUE TITLE
Drag and drop windows folder onto Extensions used to open that repo

### ISSUE THREAD

**Issue by pgilmorepf** [gitextensions/gitextensions#6221]
## Current behaviour
For the 2.X releases, you could drag and drop a Windows folder from File Explorer onto a Git Extensions window, and it would open that folder as a repository (as if choosing that folder for "open repository")
With the recent 3.x release, that functionality seems to have been lost.

## Steps to reproduce
Open folder in windows.
Open Git Extensions (first main window)
Drag a subfolder from windows explorer window to Git Extensions

## Expected behavior
Expected: Open that folder like "Open repository" does.
Actual: Drag & drop folder displays the "not possible" cursor.

## Did this work in previous version of GitExtensions
Yes.
Many/most recent 2.x versions of GitExtensions

## Environment

- GitExtensions version: 3.00.00.4433
- GIT version: 2.20.1.windows.1
- OS version: MS Windows NT 10.017134.0
- .NET version: 4.7.3260.0

**Comment by RussKie** [comment]
Could you please clarify are you talking about the dashboard or the revision graph view?

**Comment by pgilmorepf** [comment]
![gitdragdrop](https://user-images.githubusercontent.com/13439429/52377289-457ed600-2a19-11e9-9216-505ef9456e45.png)

This is the first window I see when I open GitExtensions by double clicking the GitExtensions shortcut.
Formerly, this window was organized differently, and drag and drop worked onto this window.

**Comment by RussKie** [comment]
Yes, it is the dashboard.
