### ISSUE TITLE
Slow startup if never connected to internet

### ISSUE THREAD

**Issue by robot1marvin** [gitextensions/gitextensions#6223]
## Current behaviour
With a clean install, accepting all default options of GitExtensions-3.0.1.4933.msi but NO internet connection, after installation the program takes 30+ seconds to startup each time (i.e. double-click icon, 30+ seconds before first window appears) This is before opening any repositories, just starting the program.

If the machine is connected to the internet ONCE and it is started, program takes less than 3 seconds.  Disconnecting from internet again, program always starts up quickly (<3 seconds).

## Expected behaviour
Once installation is complete, program should not require internet connection to 'finish' some final configuration or installation.

## Steps to reproduce
Copy msi file to machine that has no internet connectivity.
Run installation accepting all default settings
After installation, starting always takes 30+ seconds to open.
Close program, connect to internet and then start program.

## Did this work in previous version of GitExtensions
Sorry, don't know, haven't used previous versions.

## Environment

- Git Extensions 3.0.1.4933
- Build a269358b22a5dc1ea36928bb87f9e535de76a058
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.14393.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Probably our check for updates code.  It stores last time checked but if it
fails to check it probably doesn't store so it checks again.  Since the
check is timing out and not getting a response, it is the timeout of the
check that determines how long this takes.

**Comment by RussKie** [comment]
> Probably our check for updates code. It stores last time checked but if it fails to check it probably doesn't store so it checks again. Since the check is timing out and not getting a response, it is the timeout of the check that determines how long this takes.

That sounds very plausible. Thank you

**Comment by robot1marvin** [comment]
Okay, is there perhaps some file location or registry I can 'hack' into and set a date?  Maybe someway to fool it at least temporarily to see if that is, in fact, what's going on?  I could do that and confirm the results.  Or some way to turn off the 'update check' permanently since these machines aren't allowed to connect for 'security reasons' (the catch-all explanation for why we can't have nice things.)

**Comment by robot1marvin** [comment]
So, I found the xml <item><key><string>LastUpdateCheck</string></key><value><string>false</string></value></item> and compared this with a machine that runs with an internet connection, and changed the <value> from 'false' to '2019/2/15' (found in settings file under Appdata\Roaming\Gitextensions)

Sadly, this had no affect on the time it takes to open.  So maybe this isn't really it?  I agree it's acting as if it's trying to validate/check with something on line.  Is it possibly some certificate issue instead?  Or do I need to hack some other date check?

**Comment by vbjay** [comment]
Can you record a gif of your screen starting the program?
https://www.screentogif.com/  You can drag the gif as a reply on this
issue.

**Comment by robot1marvin** [comment]
> Can you record a gif of your screen starting the program? https://www.screentogif.com/ You can drag the gif as a reply on this issue. Also use f12 if possible to show what commands are being run.
> […](#)

Perhaps you misunderstood. There is nothing on the screen to record and no command being run at the point where the issue exists.  It's simply a matter of double-clicking the desktop icon (or the start menu item) when starting the program.  NOTHING comes up on the screen (no splash screen, no window, nothing) for 30 seconds.  We just sit, patiently waiting and waiting.  After it times out, the program opens normally. Once the program opens and the main window appears, everything is fine.  This only occurs on machines that never connect with the internet.

**Comment by vbjay** [comment]
Right. I was kind of looking for the timing and to see what happened when.
Thanks for the details.

**Comment by RussKie** [comment]
Please test this build
https://ci.appveyor.com/api/buildjobs/xp86a42kbgc51oxq/artifacts/Setup%2FGitExtensions-Portable-3.1.0.5347.zip
