### ISSUE TITLE
Branch visualization not logical (for me at least)

### ISSUE THREAD

**Issue by christophedemey** [gitextensions/gitextensions#6226]
Hi, i think this is more a question then a bug report but i didnt know where else to go.

If i create a branch from master named development.
Then check out development and create a branch : INFR-183.
Then do some work on it.
Merge it into development (creating a merge commit).
Then merge development into master (again creating a merge commit).

I would expect to see 3 lines from left to right :
- master
- development
- INFR-183

But what i am seeing from left to right is :
- master
- development & INFR-183

![visualization](https://user-images.githubusercontent.com/13153164/52465083-990a3480-2b7d-11e9-9d52-f12a97891783.PNG)

When i look at this in tower it seems more logical ?

![tower-visualization](https://user-images.githubusercontent.com/13153164/52465244-31a0b480-2b7e-11e9-9be8-8addc407e9a6.PNG)

I dont want to use tower... but was wondering why the visualization in git extensions is like this ?

Thanks!

**Comment by spdr870** [comment]
I was working on something like this. I play to revisit this, but its difficult to find something that is better in all situations. You can view a preview here:
https://github.com/gitextensions/gitextensions/issues/5782#issuecomment-439730511

You can play with it on branch spdr870/feature/keepyourlane on my fork. Commit: 42fe8a352e835e125e04b748c888e2b0ae070675

**Comment by RussKie** [comment]
It is semantically the same, we just don't draw the line from the point it was branched off like Tower does it

**Comment by christophedemey** [comment]
@spdr870 , @RussKie  thanks for your feedback, it would be a nice setting somewhere in the options.
This way people who want to can activate it.
