### ISSUE TITLE
Black screen once switching to one of the submodules

### ISSUE THREAD

**Issue by sajis997** [gitextensions/gitextensions#6243]
I am getting this problem once I switch to one of the submodules to checkout to a branch. The moment I switch and about to select and checkout a particular branch, part of the window goes black. 

Check the image : [BlackScreen](https://imgur.com/8EJWQr3)

**Comment by RussKie** [comment]
Are you getting it consistently?
Can you share a repo where it is reproducible?

Btw, you can paste images directly in GH

**Comment by vbjay** [comment]
Go tot the folder that is teh submodule.  Tell us if the .git item is a
folder or a file.

**Comment by RussKie** [comment]
Fixed in #6318
