### ISSUE TITLE
NullReferenceException in commit dialog

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions#6246]
## Current behaviour

In the commit dialog, in the staged file viewer, you can click the empty area (not on an item) and the context menu will show. Most options are graceful, but clicking `Edit File` will result in a NullReferenceException.

## Expected behaviour

The context menu shouldn't even show up.

## Steps to reproduce

1. Open the commit dialog. It is not necessary to have made changes in a file.
2. Right click in the staged file viewer (bottom left), somewhere in the empty area, and select  `Edit File` from the context menu.
![bugcommitnullreference](https://user-images.githubusercontent.com/46861028/52649361-7adb6600-2ee8-11e9-9927-9e10c889503b.png)

## Did this work in previous version of GitExtensions

Yes. Version 2.51.05 doesn't have this issue (the context menu is not accessible).

## Environment

- Git Extensions 3.0.1.4933
- Build a269358b22a5dc1ea36928bb87f9e535de76a058
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
But....  I want to edit a null file.  :D
