### ISSUE TITLE
I can`t init 

### ISSUE THREAD

**Issue by scascalesp** [gitextensions/gitextensions#6247]
Hello!

GitExtensions.exe [3.00.00.4433]

System.IO.FileLoadException:
Unable to load the file or assembly 'ICSharpCode.TextEditor, Version = 2.99.90.0, Culture = neutral, PublicKeyToken = 4d61825e8dd49f1a' or one of its dependencies. The assembly manifest definition does not match the reference to the assembly. (Exception from HRESULT: 0x80131040)

I send the issue too

**Comment by drewnoakes** [comment]
You'll need to provide more information for us to help you.

- How did you install the app?
- When does this happen?
- Have you tried on more than one machine?
- Can you try reinstalling?

**Comment by RussKie** [comment]
Please submit the issue using the template provided

**Comment by RussKie** [comment]
Please let us know when you have filled the template correctly and we'll reopen the issue.
