### ISSUE TITLE
Selecting file in Diff does not work (Windows 10, GE 3)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [gitextensions/gitextensions#6253]
## Current behaviour

1. Open on any commit
2. Open Diff tab
3. Click(single point click) any file.
4. File is not opened

## Expected behaviour
File opened and shows me its diff. 

## Steps to reproduce

See `Current behaviour` and see attached animated image.

## Screenshots

![2019-02-15_15-05-04](https://user-images.githubusercontent.com/757125/52855743-5e7f3980-3133-11e9-8b4c-b168e9e8089f.gif)

## Did this work in previous version of GitExtensions

Yes

## Environment

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

## Diagnostics

Selection via area (press mouse and drag) works. Single click does not. Can select via keyboard if click top of commit message and press arrow down. May be same or similar to #6034. 

Donated now via PayPal

![image](https://user-images.githubusercontent.com/757125/52855840-ab631000-3133-11e9-9eeb-019dc5f6c981.png)

**Comment by gerhardol** [comment]
What are your settings for visual style?
See e.g. here:
https://github.com/gitextensions/gitextensions/issues/5877#issuecomment-445750688

This is probably the same as #6034

**Comment by RussKie** [comment]
Thank you for the donation, it is much appreciated.
Just to confirm have you sent to our OpenCollective account or to the @spdr870's paypal?

**Comment by dzmitry-lahoda** [comment]
> What are your settings for visual style?
> See e.g. here:
> [#5877 (comment)](https://github.com/gitextensions/gitextensions/issues/5877#issuecomment-445750688)
> 
> This is probably the same as #6034

I will check visual style and references issues (I looked into one of them previously, but found not direct immediate equality to mine).

But I found that issues comes and goes away. May be after I reopen GE, will check it. 
Also I have installed Greenshot, Everything - but I doubt they are reason (i.e. by doing global hooks).

**Comment by dzmitry-lahoda** [comment]
> 
> 
> Thank you for the donation, it is much appreciated.
> Just to confirm have you sent to our OpenCollective account or to the @spdr870's paypal?

Main page https://gitextensions.github.io/ Donate leads to @spdr870 and I used that link.
I guess it should be changed to OpenCollective link?

**Comment by RussKie** [comment]
> Main page https://gitextensions.github.io/

Thank you, I have updated it.

**Comment by gerhardol** [comment]
> Main page https://gitextensions.github.io/ Donate leads to @spdr870 and I used that link.

@spdr870  will handle this so the donation will come to use, but the open collective stats will not be updated.

**Comment by dzmitry-lahoda** [comment]
I am on latest release. And have not issue for a month. So may be closed I guess.

**Comment by RussKie** [comment]
Thank you for the follow up
