### ISSUE TITLE
Detect 'git clone' prefix and ignore

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#6260]
## Current behaviour

I copy a branch from gerrit code review server (git clone ssh://...), want to clone a new repo and got and error ( it tries to execute git clone git clone ... )

## Expected behaviour
The prefix git clone is detected automatically and will be ignored

## Steps to reproduce

Copy and paste a link from gerrit

## Did this work in previous version of GitExtensions

Current (3.xx)

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
I personally feal that a user should handle this, but if someone writes a PR  I would not block it.

**Comment by vbjay** [comment]
You should just include the URL.

**Comment by thimmy687** [comment]
example string:

git clone ssh://username@<gerrit-server>:<port>/PROJECT

**Comment by vbjay** [comment]
Only include ssh://...

**Comment by thimmy687** [comment]
Maybe it is possible to extend this to also detect the clone with hook from gerrit

Example:

 "Clone with commit-msg hook": "git clone http://gerrithost:8080/${project} \u0026\u0026 scp -p -P 29418 jdoe@gerrithost:hooks/commit-msg ${project}/.git/hooks/"

**Comment by nyankoframe** [comment]
I'd be interested to work on this issue if it's not already assigned. I believe the fix should be as straightforward as detecting that git clone is in the URL and removing it.

**Comment by gerhardol** [comment]
> I'd be interested to work on this issue if it's not already assigned. I believe the fix should be as straightforward as detecting that git clone is in the URL and removing it.

The base use case was just detecting git clone prefix if the following seem to be an url.
