### ISSUE TITLE
Jira Commit hint Error after update

### ISSUE THREAD

**Issue by MFasseur** [gitextensions/gitextensions#6265]
## Current behaviour
1. Open on any commit
2. Click on Commit template
3. Click on Jira ticket

## Expected behaviour
Jira issues found.

## Steps to reproduce
See `Current behaviour` 

### Error shown
System.TypeInitializationException: De type-initialisatiefunctie voor NString.StringTemplate heeft een uitzondering veroorzaakt. ---> System.IO.FileLoadException: Kan bestand of assembly System.Collections.Immutable, 
 - Version=1.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a of een van de afhankelijkheden hiervan niet laden. De manifestdefinitie van de gevonden assembly komt niet overeen met de assembly-verwijzing. (Uitzondering van HRESULT: 0x80131040)
   bij NString.Internal.Cache`2..ctor()
   bij NString.StringTemplate..cctor()
   --- Einde van intern uitzonderingsstackpad ---
   bij NString.StringTemplate.GetTemplate(String template)
   bij JiraCommitHintPlugin.JiraCommitHintPlugin.<>c__DisplayClass40_0.<GetMessageToCommitAsync>b__0(Issue issue)
   bij System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   bij System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bij System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bij JiraCommitHintPlugin.JiraCommitHintPlugin.<GetMessageToCommitAsync>d__40.MoveNext()

**Comment by RussKie** [comment]
Duplicate of #6154
