### ISSUE TITLE
how to disable rightmouse menu ?

### ISSUE THREAD

**Issue by qcbf** [gitextensions/gitextensions#6270]
## Feature description
how to disable rightmouse menu ?
thank.

## Environment

- GitExtensions version:  v3.0.2
- GIT version:  git version 2.20.1.windows.1
- OS version:  windows 10 
- .NET version:  4.5?

**Comment by qcbf** [comment]
i now delete GitExtensionsShellEx32.dll and GitExtensionsShellEx64.dll

**Comment by gerhardol** [comment]
Uninstall GE and install without shell integration
