### ISSUE TITLE
Clear diff in history form when clicked on empty area, just like main form and commit form do

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions#6271]
## Feature description

Currently there are 2 different strategies for dealing with clicks on empty areas when showing diffs.

The main form unselects the file and clears the diff view:
![main2](https://user-images.githubusercontent.com/46861028/52599578-54221e80-2e59-11e9-8f51-151ec1c46be9.gif)

The commit form does the same like the main form:
![commit](https://user-images.githubusercontent.com/46861028/52599148-1ffa2e00-2e58-11e9-821e-87add6cb9a68.gif)

However, the history form behaves slightly differently. Clicking the empty area still de-selects the file, but the diff view is not cleared.
![diff_popup2](https://user-images.githubusercontent.com/46861028/52599659-951a3300-2e59-11e9-9cbd-1906d7f812b9.gif)
The behaviour should be aligned to the other two forms. This has been discussed in 
#6231 .

## Environment

GitExtensions 3.

**Comment by gerhardol** [comment]
Agree this should be changed
