### ISSUE TITLE
Application Unusable with High Contrast Theme

### ISSUE THREAD

**Issue by HK6** [gitextensions/gitextensions#6275]
## Current behaviour

Branch view does not use the system-specified text colour. This leads to Git Extensions being unusable when using a high contrast theme with a black background colour.

## Expected behaviour

Branch view should use the system-specified text colour.

## Steps to reproduce

1) Apply a high contrast theme in Windows with a black background.
2) Open Git Extensions.
3) Apply 'Colors' settings from screenshot below if required.

## Screenshots

![image](https://user-images.githubusercontent.com/547894/53018831-5a983380-3421-11e9-9d48-82e272e875df.png)

'Colors' Settings:
![image](https://user-images.githubusercontent.com/547894/53018856-697ee600-3421-11e9-88ab-fd85124c3c5a.png)

High Contrast Settings:
![image](https://user-images.githubusercontent.com/547894/53018877-77cd0200-3421-11e9-94c8-4502d259fde6.png)

## Did this work in previous version of GitExtensions

It "worked" in the first release of 3.0 but that was only because the background colour did not use the system-specified background colour.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.18.0.windows.1
- Microsoft Windows NT 10.0.17134.0 (Windows 10 Enterprise version 1803 build 17134.523)
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Relates to #5489

**Comment by gerhardol** [comment]
Closed by #6651
