### ISSUE TITLE
"Show messages of annotated tags" truncates to ten lines without notice

### ISSUE THREAD

**Issue by guban** [gitextensions/gitextensions#6276]
## Current behaviour

 * Only the first ten lines of an annotated tag's message are shown in commit pane.
 * There is no indication that the tag message was truncated (which may trick people into thinking that what they see is all what there is).

## Expected behavior

At least, there should be an indicator telling that the message is truncated.
Ideally, the tag message should be shown in its entirety.

## Steps to reproduce

1. Create an annotated git tag with a message that has more than ten lines of text.
2. Review the tagged commit in Git Extensions.

## Screenshots

Not needed as the issue is trivial to reproduce and see.

## Did this work in previous version of GitExtensions

No. The ability to view annotated tag messages was implemented in #1664, where the ten-line limit was hard-coded right from the start:

        string info = RunGitCmd("tag -l -n10 " + tag, SystemEncoding);

## Environment

- GitExtensions version: 3.0.2.5232
- GIT version: 2.20.1.windows.1
- OS version: Windows NT 10.0.17134.0
- .NET version: 4.7.3260.0
- DPI 96dpi (no scaling)

## Diagnostics

Irrelevant.

**Comment by pmiossec** [comment]
>No. The ability to view annotated tag messages was implemented in #1664, where the ten-line limit was hard-coded right from the start:

Does it works if you remove this limit? If yes, could you do a pull request?

**Comment by guban** [comment]
Unfortunately, without the `-n10` option, `git tag` prints only the tag name because it interprets the command as "find all tags matching the given pattern". With `-n` option, it prints only the first line. It seems that `git tag` is unable to provide the entire message without an a priori knowledge of the size of the annotation message.
We could just put `-n9999`, but that's a cheap hack. A better way could be to  use `git cat-file -p <tag>`, and skip the first five lines of the command's output.

**Comment by oriash93** [comment]
@guban You're right.
![image](https://user-images.githubusercontent.com/14019835/53277894-02a64900-370f-11e9-90d2-1e7f9ba250f4.png)

Source: https://git-scm.com/docs/git-tag

**Comment by lhiginbotham** [comment]
@RussKie I think I have a decent fix based on this thread, you can assign it to me
