### ISSUE TITLE
Selecting multiple files in a merge conflict continues to prompt.

### ISSUE THREAD

**Issue by nsartor** [gitextensions/gitextensions#6279]
## Current behaviour
Using "choose theirs" in a merge conflict with multiple files continues to prompt on deletes.

## Expected behaviour
When selecting multiple files, and "choose theirs" it should choose whatever is in "theirs" For example, if there are 25 deletes in theirs, it shouldn't prompt 25 times since chose theirs was already selected.

## Steps to reproduce
Begin a merge with a conflict that has several deletes in the branch.
Merge that branch in to your local branch causing a merge conflict. 
Select multiple files that have been deleted in "theirs", right click and select "choose theirs."
You'll be prompted for each file to keep modified or delete file.

## Screenshots

![image](https://user-images.githubusercontent.com/6578903/53043608-d52f7600-3456-11e9-96f2-368be6753d9d.png)

## Did this work in previous version of GitExtensions
no

## Environment

- GitExtensions version:3.00.00.443
- GIT version: 2.20.0.windows.1
- OS version: Windows 10.0.16299.0
- .NET version: 4.7.2650.0

**Comment by gerhardol** [comment]
Not tested myself, seems like reasonable change?
@nsartor 
Can you send a PR?

**Comment by nsartor** [comment]
@gerhardol I've never built the project myself, but I'll be happy to take a stab at it this weekend.
