### ISSUE TITLE
Delete tag not working

### ISSUE THREAD

**Issue by NOYB** [gitextensions/gitextensions#6281]
Actions:
1. Commands -> Delete tag
2. Select tag
3. Click delete button

Expected result:
Tag deleted

Actual result:
Tag still exists

Workaround:
Launch git bash and run command:
git tag -d <tag name>

Git Extensions 3.00.00.443
Git 2.20.0.windows.1

**Comment by RussKie** [comment]
I can't replicate the problem, I can create and delete tags in Git Extensions 3.0.2.5232

Please provide more information.

**Comment by NOYB** [comment]
I don't really know what else to provide.
Created this tag a few days ago.  ipset-service-6.29-1.el7.noarch
In the mean time did some maintenance: git prune, git gc, git gc --aggressive
Tried to delete the tag today.  Had to resort to git bash command line.
$git tag -d ipset-service-6.29-1.el7.noarch

Perhaps something to do with the characters, length or the git maintenance?

Git Extensions 3.00.00.443
Git 2.20.0.windows.1
Windows 8.1 Pro

**Comment by NOYB** [comment]
I just tried to reproduce the issue and could not.  There must be some unusual condition that occurred.

**Comment by NOYB** [comment]
Oh wow.  Just reproduce the issue by checking the box to "Delete tag also from the following remote(s):" and selecting the remote.  But the remote does not have the tag.  After doing this cannot delete tag even just locally.

**Comment by RussKie** [comment]
Please provide steps to reproduce. 
Does it the problem occur for a specific repo or all repos? Does it happen for all tags or specific tags?

**Comment by NOYB** [comment]
Steps are same as before with addition of selecting the "Delete tag also from the following remote(s):" option.  And for the remote to not have the tag, so that the delete remote will fail.
After which even local only cannot be deleted.

Repo specific? Unknown.
Tag specific? Unknown.

There is enough information now that it should be reproducible.  Give it another try.

**Comment by gerhardol** [comment]
I cannot reproduce either with the information provided
Lightweight or annotated tag? (I tried both)
Pushed to any repo? (Tried that too)
Do you have write access to the repo? (Tried both repo with and without write access)
What is in the Git command log (F12)?

**Comment by NOYB** [comment]
Think I see where the problem is.

When selecting the tag to delete in the "Delete tag" dialog "Select tag" drop down.  It prepends "refs/tags/" to the tag name.  This fails.
Remove the prepended "refs/tags/" and it works with the tag name only.

This is regardless of deleting from remote repo.

**Comment by gerhardol** [comment]
Clearly seen in the Git Command Log

This is not a problem if only using the context menu (revision grid or left panel) without selecting
The workaround is to remove the prefix manually.
