### ISSUE TITLE
Prune remote branches from Remote repositories dialog not working as expected

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions#6284]
## Current behaviour

Clicking `Prune remote branches` in `Repository` > `Remote repositories` > `Default pull behaviour (fetch & merge)` prunes only one repository at a time. The pruned remote is the one selected in the first tab `Remote repositories`.

## Expected behaviour

The button should trigger pruning of all remotes at once. Just like the checkbox `Prune remote branches` in the Pull dialog does.

## Steps to reproduce

1. Open `Repository` > `Remote repositories`. Note that I have 2 remotes configured.
![prune1](https://user-images.githubusercontent.com/46861028/53108923-2a8f8400-3538-11e9-8158-07d6a0a23e80.png)
2. Go to second tab `Default pull behaviour (fetch & merge)` and click `Prune remote branches`.
![prune2](https://user-images.githubusercontent.com/46861028/53108935-2fecce80-3538-11e9-9c20-d4ef7d9359ef.png)
3. Verify in the output that only one remote is actually pruned.
![prune4](https://user-images.githubusercontent.com/46861028/53108951-3713dc80-3538-11e9-9a45-2f8624440700.png)
4. Go back to first tab `Remote repositories` and select the other remote.
5. Go back to second tab and click  `Prune remote branches` again. Now the other remote gets pruned.

## Did this work in previous version of GitExtensions

No. I think it was always like this.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Yes.  It is tied to which remote is selected in the first tab.

**Comment by mast-eu** [comment]
That doesn't seem logical to me, because you have no way of figuring out which remote it refers to (unless you switch tabs). Moreover, the button next to it `Update all remote branch info` works on all remotes.

**Comment by vbjay** [comment]
Frankly, I use the pull dialog
![image](https://user-images.githubusercontent.com/3629489/53124497-81419180-3529-11e9-8275-bd8e92e8ffdc.png)

**Comment by vbjay** [comment]
Or 
![image](https://user-images.githubusercontent.com/3629489/53124581-b8b03e00-3529-11e9-8b08-be81ba7f35fb.png)

**Comment by gerhardol** [comment]
I do not see this as @mast-eu but can see that this is misunderstood too.
One way to improve this is to move the button closer to "Save changes" (where the remote is seen) or the first tab (already crowded though).

**Comment by mast-eu** [comment]
> One way to improve this is to move the button closer to "Save changes" (where the remote is seen) 

Sorry, but the "Remote repository" seen above the `Save changes` button is only for changing the second column in the table on the left side, isn't it? It is not connected to `Prune remote branches`.

**Comment by vbjay** [comment]
Correct.

**Comment by pmiossec** [comment]
>One way to improve this is to move the button closer to "Save changes" (where the remote is seen) or the first tab

For me, the best way to improve the situation is to remove completely the button. I never found it a good place to "hide" this feature in a form that is more a "configuration" form where few people go. It takes myself years to discover that GitExtensions proposed this feature and used to did it by command lines...

And now that we have the left panel, we could add this feature in the contextual menu of the remotes and in the one of the "Remotes" node to propose a "prune all remotes" feature.

**Comment by RussKie** [comment]
@pmiossec sounds good!

**Comment by pmiossec** [comment]
I already did a quick try. I have to do the PR...

**Comment by pmiossec** [comment]
PR done: #6293 
@mast-eu you could test...

**Comment by mast-eu** [comment]
> @mast-eu you could test...

Yes, tonight I'll have a look at it.
