### ISSUE TITLE
Application crashes when selecting "Go to commit" and having big contents in clipboard

### ISSUE THREAD

**Issue by BlackStarX42** [gitextensions/gitextensions#6288]
## Current behaviour
Application crashes.
## Expected behaviour
Application should not crash if clipboard contents is too big to handle.
## Steps to reproduce
* Open a big text file (> 32kB),
* copy the whole contents,
* select "Go to commit" from the Navigate menu -> application crashes.
## Screenshots
![gitex1](https://user-images.githubusercontent.com/41993823/53172931-d2fc2180-35e6-11e9-9aaa-46632988e8a7.png)
## Did this work in previous version of GitExtensions
Unknown.
## Environment
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
It fails here:
![image](https://user-images.githubusercontent.com/4403806/53281240-809f3a00-3779-11e9-9a0f-d044aab0924a.png)

The problem appears to be related to a slopping code that does not validate user's input:
![image](https://user-images.githubusercontent.com/4403806/53281255-a3c9e980-3779-11e9-947c-1a5673033fb8.png)

I think we need to trim the user input to something sensible, like first 100 characters, here:
https://github.com/gitextensions/gitextensions/blob/14e881406bd69ed6cd279906b849ccb342443f5b/GitCommands/Git/GitModule.cs#L3479-L3492

Thoughts?

/cc: @gitextensions/git-extensions-source @vbjay

**Comment by gerhardol** [comment]
What is the longest expected ref to parse? A branch could be more than 100 chars, why I suggest a higher limit, like 512.

**Comment by BlackStarX42** [comment]
As references are frequently stored in the names of files (in the git ref folder), I would suggest picking the longest usual file name length, which is 255 for both Windows and Linux. Anyone who picks a longer branch or tag name will most probably have many more issues than only a crashing GitExtensions.

**Comment by RussKie** [comment]
I think that sounds reasonable, 260 char.

Are you in a position to send a PR?

**Comment by BlackStarX42** [comment]
Do we want to shorten all clipboard contents down to the length or do we want to ignore all clipboard contents which exceeds the length? I fail to see a reason to shorten the clipboard contents because, as I see it, shortening only makes sense for commit hashes, but everything longer than 260 characters is certainly not a commit hash. So I would just add a check if the contents exceeds the length of 260 and, if so, treat it like there is no clipboard content at all. The next question is, do we do the check in SetCommitExpressionFromClipboard or RevParse.

**Comment by RussKie** [comment]
I am inlined to do something like
```
 public ObjectId RevParse(string revisionExpression) 
 { 
     if (string.IsNullOrWhiteSpace(revisionExpression)) 
     { 
         null; 
     }

     if (revisionExpression.Length > 260) 
     { 
         revisionExpression = revisionExpression.Substring(260);
     }

     if (ObjectId.TryParse(revisionExpression, out var objectId)) 
     { 
         return objectId; 
     }
```

We'll need some tests around this to ensure the issue doesn't happen again

**Comment by BlackStarX42** [comment]
So you want to shorten the revision expression to 260 characters, but what for. *If* there is something longer than 260 characters, it can only be a branch or tag name or (veeery long) relative reference like HEAD~X. Shortening those types of revision expressions really is not helpful. In the contrary, shortening them could cause confusion because there is a chance to match a different valid revision expression. In my opinion we should just ignore revision expressions longer than 260 characters instead of shortening them.

**Comment by RussKie** [comment]
I'm find with that.
