### ISSUE TITLE
Allow usage of custom fields in jira commit hint plugin

### ISSUE THREAD

**Issue by spdr870** [gitextensions/gitextensions#6294]
## Feature description
Jira allows using custom fields. Include options to use these in the commit hint plugin. As far as I know, this is currently not possible using the nstring template engine.

Example implementation (see PR):
![image](https://user-images.githubusercontent.com/38675/53229067-79960000-3683-11e9-9800-2e79922bb23c.png)

**Comment by zroytman** [comment]
Hi, i'm using GitExtensions 3.1.1 and have a placeholder {CustomFields} in the Jira Hint Comment plugin definition. Using this placeholder as is returns me the message that this is a collection. How can i specify the custom field from this collection? The required custom field is "Application". Tried several ways like {CustomFields["Application"]}, {CustomFields("Application")}. {CustomFields.Application}, etc... getting error messages.
Please help.
Thanks.

**Comment by RussKie** [comment]
There is an open PR that presumably unlocks the said functionality, however @spdr870 needs to finish it off.

**Comment by zroytman** [comment]
> There is an open PR that presumably unlocks the said functionality, however @spdr870 needs to finish it off.

Thanks. Any expectation when could it be?

**Comment by zroytman** [comment]
Hello @spdr870 , any expectation for releasing of this functionality? Thanks!

**Comment by gerhardol** [comment]
Jira Commit Hint plugin is removed in 4.0, see #9659 
This issue is therefore closed as not applicable, link from #9659
