### ISSUE TITLE
Incorrect context menu items in commit diff tab

### ISSUE THREAD

**Issue by DeadDuck** [gitextensions/gitextensions#6296]
## Current behaviour

Worktree files cannot be deleted using the "Delete file" context menu item in the commit diff tab.

## Expected behaviour

I should be able to delete the file.

## Steps to reproduce

- Choose a commit from the history
- Open the diff tab
- Right click on a file
- Select 'Delete file' from the context menu

Alternatively, hit the DELETE key.

## Screenshots

![image](https://user-images.githubusercontent.com/474456/53234749-49f5f080-36a1-11e9-8631-dbfcca6db506.png)

## Did this work in previous version of GitExtensions

Not at least a few versions.

## Environment

- GitExtensions version: 2.51.02
- GIT version: 2.16.1.windows.4
- OS version: Windows 10

**Comment by gerhardol** [comment]
The error here is that Delete file is available for other commits than Worktree artificial commit

**Comment by RussKie** [comment]
A displayed diff as well as a file tree are **not** representation of your working directory - they are show snapshots of what was committed.

I don't think the following items are valid at all:
* _Edit file_ <- this should be replaced with the similar context items from the File tree context menu
* _Delete file_

_Open containing folder_ label must be aligned with the same from the File tree, arguable this context menu shouldn't be visible either - it is only valid for the working directory files.

**Comment by gerhardol** [comment]
> _Open containing folder_

A regression, has been changed to _Show in folder_

Show in folder and Edit file are useful though. I suggest that Edit file is removed (for other than Worktree) and that Show in folder is renamed to Show in working tree folder for both DiffFileTree

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/53277934-9e10db80-375a-11e9-9393-8be70b944859.png)

**Comment by DeadDuck** [comment]
> A displayed diff as well as a file tree are **not** representation of your working directory - they are show snapshots of what was committed.

Sure, I took it as 'Delete file from the working directory', as a shortcut to locating the file in explorer and deleting it.
