### ISSUE TITLE
Copied files in a commit cannot be deleted by 'Reset to parent'

### ISSUE THREAD

**Issue by DeadDuck** [gitextensions/gitextensions#6297]
## Current behaviour

Copied files in a commit cannot be deleted from the worktree by using 'Reset to parent' from the context menu item. The menu item does nothing on the file.

## Expected behaviour

The same menu item can delete added files. It must also delete copied files.

## Steps to reproduce

- Right click on the last commit with a copied and modified file from the commit diff tab
- Choose 'Reset file(s) to > Parent' from the context menu.

## Screenshots

![image](https://user-images.githubusercontent.com/474456/53236134-9e4e9f80-36a4-11e9-88da-01f878491492.png)

## Did this work in previous version of GitExtensions

Not since a few versions at least.

## Environment

- GitExtensions version: 2.51.02
- GIT version: 2.16.1.windows.4
- OS version: Windows 10

**Comment by RussKie** [comment]
Please update to the latest v3 version and try it there.
Versions 2.5x are no longer actively maintained and accept only Linux-related bugs.

**Comment by DeadDuck** [comment]
Reproducable on 3.0.2.5232

![image](https://user-images.githubusercontent.com/474456/53294056-9439b780-37f0-11e9-81e3-249c21858bd9.png)

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.2600.0
- DPI 120dpi (125% scaling)
