### ISSUE TITLE
only ancestors of HEAD are shown, menu option ignored

### ISSUE THREAD

**Issue by rosecodym** [gitextensions/gitextensions#6299]
## Current behaviour

Only commits in the current branch are shown in the tree. Just like #2639, except **View > Show all branches** is selected. Selecting **View > Show current branch only** and then **View > Show all branches** doesn't change anything.

## Expected behaviour

All commits on reachable from all local and remote branches are shown when View > Show all branches is selected.

## Steps to reproduce

1. Checkout any branch (e.g. `master`)
1. Create and checkout a new branch, e.g. `test`
1. Commit on the new branch
1. Checkout original branch

The new commit created in step 3 is not shown.

## Screenshots

I know this would be helpful, but I'm at work and even uploading screenshots of commit histories would not be well-received.

## Did this work in previous version of GitExtensions

It worked in 3.0.1 (I think, some 3.x point release) and then just stopped working without an update. I updated to 3.0.2.5232 to see if it had been fixed and it hadn't.

I have coworkers with the version of Git Extensions I was using who don't see this problem. Notably, when I asked one of them to switch to **View > Show current branch only**, that didn't work _either_ - it continued showing all branches.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.19.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

## Diagnostics

I'm not sure what to grab.

**Comment by vbjay** [comment]
Are you showing first parents?

**Comment by rosecodym** [comment]
Apparently, yes. I guess I accidentally enabled that!
