### ISSUE TITLE
VSIX signing and separation from GE repo

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#6300]
As discussed in #6211 (.vsix separated from GE installer)

## Feature description

VSIX has (probably) no relation to the normal app and could be moved to a separate repo
The vsix installer should be signed, similar to the main .exe

## Environment

- GitExtensions version: 3.1.0 dev

**Comment by RussKie** [comment]
Thank you, I was totally fried yesterday to open an issue (still am 😩).
