### ISSUE TITLE
Stale Submodule node data after reload

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#6302]
Issue to https://github.com/gitextensions/gitextensions/pull/5617

## Current behaviour

![image](https://user-images.githubusercontent.com/1003909/53282882-7c096000-373e-11e9-9d3d-eb2711f9a10f.png)

## Expected behaviour

The node for GitExtensionsDoc submodule should show the master branch being checked out.

## Steps to reproduce

1. Open GE for GE repo with left panel open.
2. Open GE for GEDoc repo
3. Check out a different branch in the GEDoc repo.
4. Reload submodules left panel's node in the GE repo

**Comment by amaiorano** [comment]
Okay, I see, this is a bug with the "Reload" context menu action in the left panel:

![image](https://user-images.githubusercontent.com/6893883/53291497-235bb680-3782-11e9-87aa-8b68fb39a812.png)

If you press the Refresh button in the menu, or press F5, it works. Part of the problem is that the left panel doesn't initiate a submodule refresh. Normally, that is driven by FormBrowse. I'll think about the right way to tackle this.

**Comment by amaiorano** [comment]
So there are two solutions to this problem:

1. Make it so that the Reload context menu option in the left panel leads to asking the SubmoduleServiceProvider to update status. This would work as expected and is simple enough to implement.
2. Remove this "Reload" option as it's not actually useful. You can click the "Refresh" button in the toolbar, or press F5, which refreshes everything, including the left panel. Personally, I don't see much use for this context menu option, and if anything, it's just confusing.

I would opt for #2, unless you have any objections.

**Comment by gerhardol** [comment]
> I would opt for #2, unless you have any objections.

Agree

**Comment by amaiorano** [comment]
This will be fixed as part of https://github.com/gitextensions/gitextensions/pull/5617#issuecomment-467499980. I'm reworking the code again to make it clear which events cause a refreshing of nodes in the left panel to occur.

**Comment by jbialobr** [comment]
Now, there is no status at all.

**Comment by amaiorano** [comment]
@jbialobr can you give the repro steps, since there's no longer a reload context menu option?

**Comment by gerhardol** [comment]
The submodule branch from a few days ago

![image](https://user-images.githubusercontent.com/6248932/53836672-dc936b00-3f90-11e9-820d-9c9eab9f08ab.png)

**Comment by amaiorano** [comment]
@gerhardol I'm confused by your post. Is this screenshot from the latest master? What are you highlighting or circling in red?

**Comment by amaiorano** [comment]
@gerhardol I'm confused by your post. Is this screenshot from the latest master? What are you highlighting or circling in red?

**Comment by amaiorano** [comment]
Okay I see you're pointing out a problem with spaces in submodule path name. I'll take a look.

**Comment by gerhardol** [comment]
"AA space" has a space in the path, so that may be another problem.
This is a testrepo with GE as a submodule to itself about 30 times.

**Comment by gerhardol** [comment]
What I pointed at is not a new problem in master. The modules were just not init...

**Comment by amaiorano** [comment]
Okay, so is there still a bug to resolve?

**Comment by jbialobr** [comment]
>@jbialobr can you give the repro steps, since there's no longer a reload context menu option?

1. Open GE

![image](https://user-images.githubusercontent.com/1003909/53862956-39bb0b00-3fe9-11e9-9d21-52321ebdbb27.png)

There is no longer the current branch info for submodules.

**Comment by amaiorano** [comment]
> There is no longer the current branch info for submodules.

Normally this means these submodules have not yet been updated. Is that the case? If you git clone GE without --recursive, then the submodules will show up this way. Also compare to the values in the submodule menu to see if the status is also missing there.

**Comment by amaiorano** [comment]
For example, after ```git clone https://github.com/gitextensions/gitextensions.git gitextensions4```, we can see no branches or anything on the submodules, both in the menu and left panel:

![image](https://user-images.githubusercontent.com/6893883/53896063-4f3c2f00-4001-11e9-9ff6-2ab01e9069ab.png)

If I update all submodules:

![image](https://user-images.githubusercontent.com/6893883/53896162-75fa6580-4001-11e9-82e7-c3e6879d6add.png)

So is this what you're seeing?

**Comment by jbialobr** [comment]
No, I don't see branch info despite updating all submodules. I will try to debug it since it is not reproducible in your environment.

**Comment by amaiorano** [comment]
> No, I don't see branch info despite updating all submodules. I will try to debug it since it is not reproducible in your environment.

Okay, sounds good. Btw, when this happens to you, did you look to see if it's the same in the submodule menu? If it's the same in both, then it's probably a problem in SubmoduleStatusProvider. If it's only in the left panel, then it's a problem in SubmoduleTree (and related code).

**Comment by jbialobr** [comment]
I found the reason. The branch info is appended only when AppSettings.DashboardShowCurrentBranch is on. Shouldn't there be a dedicated option for submodules?

**Comment by RussKie** [comment]
That is unexpected indeed.
