### ISSUE TITLE
Branches pane context menu should support Copy to Clipboard, similar to commit context menu

### ISSUE THREAD

**Issue by johndog** [gitextensions/gitextensions#6304]
## Feature description
The branches context menu is missing a number of useful commands only available in the commit graph window.  

![image](https://user-images.githubusercontent.com/22213780/53293515-15119880-378a-11e9-80ba-3d1619e3413c.png)

One class of such commands are "Copy to clipboard" options, similar to what is available when right-clicking in the commit graph.

These are the Copy commands I'd like to see:

1. Branch name
2. Commit hash (for current branch HEAD)

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.19.0.gvfs.1.34.gc7fb556
- Microsoft Windows NT 10.0.18343.0
- .NET Framework 4.8.3745.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
See #6305
