### ISSUE TITLE
Branches pane context menu should support rename

### ISSUE THREAD

**Issue by johndog** [gitextensions/gitextensions#6305]
## Feature description
The branches context menu is missing a number of useful commands only available in the commit graph window.  

![image](https://user-images.githubusercontent.com/22213780/53293515-15119880-378a-11e9-80ba-3d1619e3413c.png)

One such command is "rename branch".

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.19.0.gvfs.1.34.gc7fb556
- Microsoft Windows NT 10.0.18343.0
- .NET Framework 4.8.3745.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Some more items added in #6209 but not rename

**Comment by lhiginbotham** [comment]
@RussKie 
This issue seems to be resolved.
![image](https://user-images.githubusercontent.com/14078392/67347085-0fce3e80-f50f-11e9-811a-c65def81f980.png)

**Comment by RussKie** [comment]
Thank you
