### ISSUE TITLE
Crash on Ctrl+Shift+N for artificial commits

### ISSUE THREAD

**Issue by nmat** [gitextensions/gitextensions#6308]
## Current behaviour

Selecting Working Directory and hitting Ctrl+Shift+N crashes gitextensions.

## Expected behaviour

No crash and either add note or not add note dialog.

## Steps to reproduce

In Commit tree
Select working directory
Press Ctrl+Shift+N

Crash dialog comes up.

## Did this work in previous version of GitExtensions

Not sure.

## Environment

- GitExtensions version: 3.0.2
- GIT version: 2.21.0
- OS version: Windows 10 1809
- .NET version: Not sure

**Comment by RussKie** [comment]
I am unable to repro, I get the dialog
![image](https://user-images.githubusercontent.com/4403806/53334752-c01e7f80-394d-11e9-951f-ec5b7f43e718.png)

Please provide more info.
* Stack trace?
* Error message?
* Is it happening to all repos or a specific repo?

**Comment by nmat** [comment]
Could it be if I am using atom as the editor?

Of course I will send more information I will do that once I get back to the machine that has the problem.

**Comment by nmat** [comment]
![image](https://user-images.githubusercontent.com/383031/53350671-e1687700-391f-11e9-9439-21b06c99c07d.png)

![image](https://user-images.githubusercontent.com/383031/53350685-e9281b80-391f-11e9-8d8b-f7ada1090dd3.png)

**Comment by gerhardol** [comment]
It is not possible to add notes to artificial commits, must be blocked

**Comment by illfated** [comment]
Very well. So this is (indirectly) expected behaviour, but with a less than ideal solution?

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/53364994-166bce00-390e-11e9-98f7-8f6353517e59.png)
Artificial commits are not actually git commits. Notes are tied to SHAs of actual git commits.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/53365730-f4734b00-390f-11e9-9533-7fb34c03788c.png)
