### ISSUE TITLE
Sort branches alphabethical/lastAccess was removed

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#6310]
## Current behaviour

In 2.51, it was possible to order branches in Browse by either alphabethical or last access order.
This possibility was removed in 9c7c76fb619480429cbe02e11ce889b00423eac2 (likely #5087)

## Expected behaviour

Change of sorting was useful, even little hard to find.
Sort could be restored or we decide that it should not be possible.

## Steps to reproduce

       public static BranchOrdering BranchOrderingCriteria
        {
            get { return GetEnum("BranchOrderingCriteria", BranchOrdering.ByLastAccessDate); }
            set { SetEnum("BranchOrderingCriteria", value); }
        }

## Screenshots

![image](https://user-images.githubusercontent.com/6248932/53374529-e269ca80-3958-11e9-85e2-3d6a9e054498.png)

## Did this work in previous version of GitExtensions
2.51

## Environment

- Git Extensions 3.1.0
- Build d753f4a7e0c175529d7c6ecffa7f297ea239faf3
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
The functionality was semi-resurrected in https://github.com/gitextensions/gitextensions/pull/4869

**Comment by gerhardol** [comment]
> The functionality was semi-resurrected in #4869

That PR is for tags. But the sorting is similar.
