### ISSUE TITLE
Missing counter for remote branches on left panel

### ISSUE THREAD

**Issue by TobiasSekan** [gitextensions/gitextensions#6313]
Hello,

## Feature description
On The left panel, there are only counters for local branches and tags, but there is no counter for remote branches.

![2019-02-26 11_11_26-dianagenload genloaddemo - git extensions](https://user-images.githubusercontent.com/17874713/53405766-d9104a80-39b8-11e9-8767-a0ab0d2673c4.png)

## Environment
- Windows 8
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3324.0
- DPI 120dpi (125% scaling)

**Comment by pmiossec** [comment]
I also add that the count should be reworked because it is false when you use folders...

**Comment by gerhardol** [comment]
The counter should be removed

**Comment by pmiossec** [comment]
>The counter should be removed

Thinking of it, I also think that they should be removed because I don't really see added values/usages to them.

@TobiasSekan Do you use it for something? or you open the issue because you find it missing compare to the tags and branches?

**Comment by amaiorano** [comment]
I don't mind having the counter, but if we do add it, we should wait until my Submodules change is merged in (https://github.com/gitextensions/gitextensions/pull/5617). The reason is that part of my changes includes a fix for the "restore expanded state" of the tree to work when node text changes: https://github.com/gitextensions/gitextensions/pull/5617/commits/6fc57f566db7ad2ae39d8ebe301f482be6655ece.

So if we do decide to show the number of remotes, we should also fix the Branches count to show the actual number of total branches, not just the number of child nodes of the root Branches node.

**Comment by gerhardol** [comment]
A number pops out in your face and should be used if it means something to the user. I see no reason to see it in the sidebar. As a tooltip is OK, then you search for information.

**Comment by vbjay** [comment]
Each Node type could be responsible for its counts.  Branch and submodule
counts should only count end leaf nodes with possible counts in each non
leaf nodes.  Only in tooltips is a design choice.

**Comment by TobiasSekan** [comment]
Hello,

I use the local branch counter to check ,that I have check out all branches of a repository.
When both counters are displayed, it should be easier to check.

best regards

**Comment by RussKie** [comment]
> I use the local branch counter to check ,that I have check out all branches of a repository.

Could you elaborate why you need it? 
A branch or a tag is just a a reference (i.e. a pointer) to an arbitrary commit.
Fetch all and you'll know all remote branches.

**Comment by TobiasSekan** [comment]
Hello,

I need this to move a complete Repository from one Git to a another (new) Git.

My current work-flow:
1. Checkout a repository
2. Checkout each branch (sometimes about twenty)
3. Change the remote repository path (+ confirm)
4. Push **[ALL]** branch

best regards

**Comment by RussKie** [comment]
I think you may find that such tasks are easier achieved with a shell/batch
script

**Comment by pmiossec** [comment]
Some things that could help: 
http://blog.plataformatec.com.br/2013/05/how-to-properly-mirror-a-git-repository/ and 
https://help.github.com/en/articles/duplicating-a-repository

**Comment by amaiorano** [comment]
I vote to remove the counters as well. They aren't that useful, and if we do keep them, then we have a bunch of design questions to answer, like:

* Should "Branches" top node show the total number of branches, or just the immediate child branches, while the BranchFolders could show how many immediate child branches they have?
* Should "Remotes" top node show the number of total remotes, or the number of active remotes? Or both?
* Should Remote repo nodes show the number of branches they contain? Again, total or number immediate child branches?
* Should "Submodules" top node show the total number of submodule nodes - excluding the first node, which is technically not a submodule? Or once again, should each module show how many immediate submodules it contains?

Personally, I think there's very little return on investment here, and vote to just remove the count on Branches and Tags. If enough people are okay with that, I'll make the change.

**Comment by amaiorano** [comment]
As you can see, I opened a PR to remove those two counters. https://github.com/gitextensions/gitextensions/pull/6351

**Comment by RussKie** [comment]
It's a nice bragging tool, but overall I agree with your assessment
:+1:
