### ISSUE TITLE
Failing statusbar-related FormCommitTests

### ISSUE THREAD

**Issue by amaiorano** [gitextensions/gitextensions#6320]
## Current behaviour

AppVeyor is failing on a bunch of unrelated branches with the same failure:

```
=> GitUITests.CancellationTokenSequenceTests.Concurrent_callers_to_Next_only_result_in_one_non_cancelled_token_being_issued
Winner by index: 6841,3159
=> GitCommandsTests.StringPoolTests.GetSubstringHashCode
0x162A16FE
0x5E19FCE
0x5E4405D
0xFC2C8D57
0xFC833FEA
0x36D35466
0x42005971
0x4B54D52B
0xBC227B3E
0xCB2B1F36
```

Here are some unrelated branches on which this has happened:
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/22702457
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/22700469
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/22697830

When I run this test locally, over and over, it passes.

## Expected behaviour

Test shouldn't fail.

## Steps to reproduce

Look at AppVeyor.

**Comment by sharwell** [comment]
@amaiorano That test is not failing in any of the builds you mentioned.

**Comment by amaiorano** [comment]
@sharwell Not sure what you mean? I open all three links, and search for "
Concurrent_callers_to_Next_only_result_in_one_non_cancelled_token_being_issued", and this is what I get:

![image](https://user-images.githubusercontent.com/6893883/53589211-cdf61f80-3b5c-11e9-956e-7596489c7d84.png)

**Comment by amaiorano** [comment]
Ah, am I reading this wrong?

**Comment by amaiorano** [comment]
Okay, I was fooled by that output with the stack. Looks 2 of the 3 are failing on this test:

```
GitUITests.CommandsDialogs.CommitDialog.FormCommitTests.Should_display_branch_and_no_remote_info_in_statusbar
```

and the other on:

```
GitUITests.CommandsDialogs.CommitDialog.FormCommitTests.Should_display_detached_head_info_in_statusbar
```

**Comment by sharwell** [comment]
👍 We are working on that in #6273

**Comment by amaiorano** [comment]
Do you want to close this issue then?

**Comment by illfated** [comment]
... or maybe put a reminder in the PR opening comment to close this issue when merging #6273 ?
