### ISSUE TITLE
Commits do not show after updating Git Extensions

### ISSUE THREAD

**Issue by jeffdillon0704** [gitextensions/gitextensions#6322]
## Current behaviour

I decided to upgrade my Git Extensions to version 3.0.2.5232 from version 2.5.1. After doing this, I was prompted to upgrade Git as well to have a more compatible version (upgrade higher than 2.9.0

![image](https://user-images.githubusercontent.com/48103841/53593201-afdcef00-3b5d-11e9-9953-71b10f2ccf67.png)

When trying to upgrade, I am blocked by my organization. I have coworkers who do not have this issue though, even though they did not upgrade Git itself. Only Git Extensions. When I ignore this prompt and continue using Git Extensions, I am able to push and pull code just fine but I am not able to see my most recent changes underneath my Commits. Instead I see this:

![image](https://user-images.githubusercontent.com/48103841/53593301-f29ec700-3b5d-11e9-9bb6-7a9758b1f2da.png)

How can I get my commits and diffs to display here?

## Expected behaviour

Commits and diffs display after upgrading to Git Extensions 3.0.2.5232 without upgrading git from 2.9.0

## Steps to reproduce

Follow prompts to upgrade to the latest version of Git Extensions. Do not upgrade Git.

## Screenshots

See screen shots above

## Did this work in previous version of GitExtensions

Not Sure.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.9.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
That is because we use features and commands that are only compatible with
later versions of git.

**Comment by RussKie** [comment]
There is a reason why the latest version requires a later version of git than you have. We use a number of git APIs only available in those versions.
Please check with your co-workers what version of git they have. 

It may be a good idea to raise the issue with your IT dept, git 2.9.0 was released in Jun 2016.

**Comment by gerhardol** [comment]
https://github.com/gitextensions/gitextensions/wiki/Application-Dependencies#git
(link in settings too)
2.11 is supported, but there is no explicit attempt to break compatibility from earlier versions.
(There was an attempt to maintain compatibility in this situation.)
