### ISSUE TITLE
z-order wrong for placeholder text in filter box

### ISSUE THREAD

**Issue by chris-findlay** [gitextensions/gitextensions#6338]
## Current behaviour

The placeholder text (label) is appearing on top of the text entered into the filter box.

## Expected behaviour
The placeholder would stay invisible when there is any text in the box.

## Steps to reproduce

Click a commit; enter text to filter the list of files in it.

## Screenshots

![image](https://user-images.githubusercontent.com/40373773/53700973-2aa75200-3e5d-11e9-99d7-6dfc4124386a.png)

## Did this work in previous version of GitExtensions

2.x?  Haven't had the need to use that filterbox till the other day.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by illfated** [comment]
How close is the relation of this issue to #6336 ?

**Comment by chris-findlay** [comment]
Looks like it's a duplicate of that one.
