### ISSUE TITLE
Unable to save changes for a remote

### ISSUE THREAD

**Issue by jbialobr** [gitextensions/gitextensions#6347]
## Current behaviour

Unable to save changes for a remote

## Expected behaviour

Changes should be saved instead of showing a dialog with information as in the screenshot below

## Steps to reproduce

1. Open Remote repositories window
2. Change remote URL
3. Save

## Screenshots

![image](https://user-images.githubusercontent.com/1003909/53882297-46098d00-4016-11e9-8508-a062bd40e526.png)

## Did this work in previous version of GitExtensions

Yes, Git Extensions 3.00.00.4433 works.

## Environment

- GitExtensions version: 5c0d503576e82f503ced0eca4be97a86ab2cd2ba

**Comment by amaiorano** [comment]
I modified this code fairly recently, so I'll take a look.
