### ISSUE TITLE
Unable to commit, configure remote, and push in one shot

### ISSUE THREAD

**Issue by afarley-tangent** [gitextensions/gitextensions#6353]
## Current behaviour
When I have a fresh repo (just created .git, remote repo created on Github) and I 'Commit and push', GitExtensions asks me to configure a remote URL. Immediately after configuring the remote URL, I get an error message that this repository does not have a remote configured. I can see that the remote URL in the Push window is not populated; it seems that the 'Configure remote' window does not push the newly-configured remote down to the Push window which opened it.

At this point, I have to close the Push window and re-open it, and then the remote URL is populated and Push works.

## Expected behaviour
I expect that immediately after configuring the remote's URL, and closing the remote-URL configuration window, that the Push window should re-load the configured remotes for this repository.

## Steps to reproduce
Create a new local repo. Create a repo on Github. Copy SSH URL for origin. Make some changes locally. Attempt 'Commit and push', then configure the remote when prompted. Close remote-URL configuration window. Attempt to push. At this point, I get an error message indicating no remote URL configured.

## Screenshots
I will provide if my description is not clear enough.

## Did this work in previous version of GitExtensions
No, this issue has been present for several releases.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
This issues sounds very similar to #4853. 
@DmitryZhelnin do you mind doing a quick assessment?

**Comment by afarley-tangent** [comment]
My mistake, I think you're right - this is entirely a duplicate of that issue.
