### ISSUE TITLE
A simple VS Code extensions for Git Extensions

### ISSUE THREAD

**Issue by Carl-Hugo** [gitextensions/gitextensions#6360]
Just to let you know that I wrote a simple VS Code plugin the allows users to **Browse with Git Extensions** from the `Explorer` and the `Editor`. It supports a single folder and workspaces. 

Marketplace: https://marketplace.visualstudio.com/items?itemName=forevolve.git-extensions-for-vs-code
GitHub: https://github.com/ForEvolve/git-extensions-for-vs-code

*I just noticed (before posting this here) that there is another plugin that supports other use-cases; but personally, the only option that I use and need from VS and VS Code alike are the ones in my extension. So I figured that maybe other people are like me and only want to **Browse with Git Extensions**.*

BTW, great work on Git Extensions, v3 is great, I love the branch explorer in the left panel!

**Comment by RussKie** [comment]
Nice!
Feel free to send us PR to the readme with the link to the plugin.

**Comment by gerhardol** [comment]
Closed by #6364
