### ISSUE TITLE
Raising the Push dialog, clicking Push, then cancel should not close the push dialog

### ISSUE THREAD

**Issue by johndog** [gitextensions/gitextensions#6367]
## Current behaviour

1. Use Commands -> Push...
2. Choose a branch that does not have a tracking branch yet
3. Click Push
4. This confirmation prompt is presented

![image](https://user-images.githubusercontent.com/22213780/54178288-815eee00-4452-11e9-9a67-7837a1e5f88c.png)

5. Click cancel

## Result
The prompt is dismissed and the entire Push dialog is dismissed

## Expected behaviour

When clicking cancel on the prompt, you should be returned to the Push dialog to make adjustments that might avoid the prompt.

## Did this work in previous version of GitExtensions

Unknown.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.vfs.1.1.97.g8af1f39
- Microsoft Windows NT 10.0.18353.0
- .NET Framework 4.8.3749.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
This confirmation have a Cancel alternative, for instance "new branch for remote" do not need cancel (no will go back).

**Comment by johndog** [comment]
Interesting; it seems superfluous.  IMO, the only UX path that does _not_ go back to the dialog should be the successful push path.  

After opening this I discovered another frustrating path:  if you click 'Push', and the push fails for any reason, that _also_ dismisses this dialog.  For example, once you see this:

![image](https://user-images.githubusercontent.com/22213780/54395999-ae87e800-466e-11e9-9f85-e99c8e45db57.png)

There is no way to go back, tweak something, and try pushing it again.  You have to go through the whole UI process again.

That dialog doesn't always come up when get an error, sometimes you just get an error message, but the result is the same; dismissing the error dismisses the push dialog.
