### ISSUE TITLE
Default pull with merge

### ISSUE THREAD

**Issue by cllobet** [gitextensions/gitextensions#6369]
I want to change the default option merge to the merge remote branch into current branch.
Always is marked as default the not merge and its a problem.
Many thanks
![image](https://user-images.githubusercontent.com/48555094/54355751-31eb0e80-465a-11e9-8906-bf0fc3bc434e.png)

**Comment by vbjay** [comment]
Use the pull button drop-down. See the set default menu?

**Comment by gerhardol** [comment]
![image](https://user-images.githubusercontent.com/6248932/54395915-8077c780-46b1-11e9-8d51-3dd28740634b.png)

**Comment by cllobet** [comment]
To find this combo in the git extensions inside visual studio 17 where is?

Thanks

**Comment by pmiossec** [comment]
That's not possible in the VS extension. You should open GitExtensions to set it, once and for all the repositories.

**Comment by gerhardol** [comment]
Some changes like this requires the full interface

**Comment by scascalesp** [comment]
Same problem and it works! Thanks!  Git Ext 3.0.2.5232
