### ISSUE TITLE
UI freeze when commit comment is long

### ISSUE THREAD

**Issue by ghost** [gitextensions/gitextensions#6370]
## Current behaviour
When displaying a flyover label for a long comment, the UI freezes.

## Steps to reproduce
Hover the mouse over a commit with a long comment.
Example comment is 
" - Commented out the status messages being outputted to the matlab command window (see below for lines affected).  - Turned off the debugging messages (Note: Warning messages still active)  On branch feat/regTest  Changes committed: 	modified:   DB110_RCI/rciDisplay/rciGL/rciF16B52GR/TOOScreen.m 		- Lines: 41-43, 46 	modified:   DB110_RMM/RMM.m 		- Lines: 84, 105 	modified:   DB110_SCU/Gimbal/CalcGimbalSlew_data.m 		- Lines: 194-195, 210-211 	modified:   DB110_SCU/Gimbal/GimbalC_GimbalController.m 		- Lines: 34 	modified:   DB110_SCU/tgtMgr/tskMgr.m 		- Lines: 123, 135-138, 406, 458 	modified:   DB110_SCU/tgtMgr/tskMgr_FinalRollPrepSlew.m 		- Lines: 48 	modified:   RMPS/taskPlanning/TaskPlannerSetup.m 		- Turned task.sim.UI.otherdebug Off 	modified:   RMPS/taskPlanning/calcWPexp.m 		- Lines: 88 	modified:   RMPS/taskPlanning/taskPlanner.m 		- Lines: 275, 531 	modified:   TestCases/SetupTestCase.m 		- Turned task.sim.UI.otherdebug Off"

## Screenshots

![image](https://user-images.githubusercontent.com/32873250/54366623-5ab5d880-4647-11e9-85a3-47bf9b559876.png)

## Environment

![image](https://user-images.githubusercontent.com/32873250/54366766-98b2fc80-4647-11e9-85f3-e324d212861b.png)

**Comment by wischi-chr** [comment]
Does that still happen. I tried to reproduce it (with the example message provided) and the UI didn't freeze.

**Comment by pmiossec** [comment]
Fixed by #7329.
