### ISSUE TITLE
any plan for vs2019 support?

### ISSUE THREAD

**Issue by nextfool** [gitextensions/gitextensions#6371]
Now this tool is the only thing that stops me from switching to vs2019

**Comment by vbjay** [comment]
We tend to wait till it is not in beta. Vs 2019 has not officially been
released.

**Comment by RussKie** [comment]
The VSIX has been updated in https://github.com/gitextensions/gitextensions/pull/5864

Have you tried the latest VSIX?
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/23071505/artifacts

**Comment by gerhardol** [comment]
Closed by #5864
