### ISSUE TITLE
'Diff' pane in commit tree view obscures filter textbox with placeholder label

### ISSUE THREAD

**Issue by diaconesq** [gitextensions/gitextensions#6378]
## Current behaviour

In the main window select a commit then in the lower pane select the 'Diff' tab.
There is a 'Filter files...' textbox. Start typing into it. 
The placeholder label (gray text saying 'Filter files...') does not go away and is in front of the typed text.

## Expected behaviour

Placeholder should be hidden when the user starts typing.

## Screenshots

![image](https://user-images.githubusercontent.com/3482077/54530189-06c62f00-497a-11e9-82d5-94b2e98063b5.png)

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Corrected in #6337, merged to master and will be included in 3.1
Please try the portable build from the main page
