### ISSUE TITLE
System.IO.FileLoadException: ICSharpCode.TextEditor

### ISSUE THREAD

**Issue by andrey-helldar** [gitextensions/gitextensions#6382]
## Current behaviour

When you start the program immediately appears error.

Не удалось загрузить файл или сборку "ICSharpCode.TextEditor, Version=3.0.2.5232, Culture=neutral, PublicKeyToken=4d61825e8dd49f1a" либо одну из их зависимостей. Найденное определение манифеста сборки не соответствует ссылке на сборку. (Исключение из HRESULT: 0x80131040)

## Expected behaviour

Run the program

## Steps to reproduce

Run the program

## Screenshots

![2019-03-19_00-12-29](https://user-images.githubusercontent.com/10347617/54563983-b4b5f580-49db-11e9-9ccd-a49d1e07b8f9.png)
![2019-03-19_00-12-21](https://user-images.githubusercontent.com/10347617/54563984-b54e8c00-49db-11e9-9668-c92d2eab56b8.png)

## Did this work in previous version of GitExtensions

Yes, in 3.00.00.02-rc1

## Environment

- GitExtensions version: 3.0.2.5232
- GIT version: 2.21.0
- OS version: Win10 Pro 1809 build 17763.379
- .NET version: installed: 2.0, 3.0, 3.5, 4.0, 4.7

**Comment by RussKie** [comment]
Could you please verify the file exists in the install directory? Could you
please confirm its version?
I've seen a similar error when preparing v3, an assembly would not get
copied from the msi.

Try repairing the installation.

**Comment by vbjay** [comment]
Start how, f5 or install or portable version?

**Comment by andrey-helldar** [comment]
@RussKie, I will be able to look in the evening when I return for the computer. Tried to reinstall and repair, the problem remained.

**Comment by andrey-helldar** [comment]
@vbjay, I install the "permanent" version.

**Comment by RussKie** [comment]
Is what you have?

![image](https://user-images.githubusercontent.com/4403806/54602264-4cc3e580-4a95-11e9-9372-c40689c07eaa.png)

**Comment by andrey-helldar** [comment]
File exists.
![2019-03-19_18-36-10](https://user-images.githubusercontent.com/10347617/54619581-e4b1d700-4a75-11e9-9899-a7b7b0d19fa5.png)

**Comment by andrey-helldar** [comment]
Just managed to solve the problem:
1. Manually deleted the file "ICSharpCode.TextEditor.dll".
2. Launched the installation program by clicking "repair".

Without deleting the file, "repair" did not help.
