### ISSUE TITLE
Git Template comments don't get removed. Changed from 2.50

### ISSUE THREAD

**Issue by vmuriart** [gitextensions/gitextensions#6388]
## Current behaviour

Periodically the Git template comments will not be removed from the commit message.

Possibly associated, Git messages don't seem to respect new-lines all the time. The times it does remove the comments, it will also combine all my lines of text into a single line. 

## Expected behaviour

Comments be removed. This was the case on `v2.50.x`

## Steps to reproduce

Add a comment to a GITMESSAGE and should be removed.

## Screenshots

![image](https://user-images.githubusercontent.com/13303020/54706286-cabad780-4afb-11e9-8a6f-1c4b15c19476.png)

![image](https://user-images.githubusercontent.com/13303020/54706590-82e88000-4afc-11e9-8050-ec75545487c9.png)

## Did this work in previous version of GitExtensions

`v2.50.x`

## Environment

- GitExtensions version: `v3.0.2.5232`
- GIT version:  `2.21.0.windows.1`
- OS version: `windows 10`
- .NET version: `4.7.3260.0`

## Diagnostics

The only thing I've looked at so far is that the `git commit` command being generated between the two versions is identical.

**Comment by RussKie** [comment]
Please provide steps to reproduce

**Comment by vmuriart** [comment]
Sorry for delay, I upgrade/downgrade to test and make sure.

On the commit message box type

```
# Comment on commit message
Actual message
```

On `v2.50` the commit message would only be `Actual message`
But on `v3+` it sometimes shows `Actual message` other times it shows `# comment`. I haven't narrowed down why it only does it some times.

## From `v2.5x`
![image](https://user-images.githubusercontent.com/13303020/55439526-b940e900-5559-11e9-8841-4c09f890e699.png)

![image](https://user-images.githubusercontent.com/13303020/55439528-bd6d0680-5559-11e9-8296-c0b6bc97212d.png)

## From `v3.x`
![image](https://user-images.githubusercontent.com/13303020/55439549-d07fd680-5559-11e9-8386-401ef4878e8b.png)

![image](https://user-images.githubusercontent.com/13303020/55439554-d4abf400-5559-11e9-9bb4-450900071527.png)

**Comment by vmuriart** [comment]
I forgot to add, on the 4th image you can see that the first 3 attempt to reproduce the bug didn't actually reproduce the bug. I kept trying a couple more times and it started showing up after the 4th attempt.
