### ISSUE TITLE
Vertical ruler position not correctly read from settings

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#6391]
## Current behaviour
When opening a new diff window (like a file history), the vertical ruler position is not updated according to the settings - it has the default value.

## Expected behaviour
The ruler should have correct position right from the start.

## Steps to reproduce
1. Set a non-default value for the vertical ruler position (in Settings - Detailed - Diff Viewer).
2. Open the history of any file.
3. The ruler is at the default position.

The ruler only moves to the correct position after clicking the Settings icon in the diff view and clicking OK in the settings window (no editing needed), which suggests the settings are not loaded correctly the first time the window opens.

## Did this work in previous version of GitExtensions
Did not check.

## Environment

- Git Extensions 3.1.0
- Build 7a5680d2fe317c08a4cb99f66a3f5e5e1c1c6c81
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please test #6392 and confirm the fix

**Comment by thimmy687** [comment]
Hi the same issue is in the commit window

may setting is on 120 but on opening the commit window the line is displayed at the default position.

If I open and close the settings without changing something the line moves to the correct position.

 before:
![image](https://user-images.githubusercontent.com/7715216/57369803-d0917880-718e-11e9-8641-fc8fb163ed53.png)
and after:
![image](https://user-images.githubusercontent.com/7715216/57369891-0d5d6f80-718f-11e9-9819-bfa53c47a2e9.png)


Here is the version info:

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
@thimmy687 please try the 3.1-RC1 and see if it was fixed

**Comment by thimmy687** [comment]
I will check this, thx

**Comment by thimmy687** [comment]
Hi it's working well now :)

but it leads me to another issue 😅 which I will report separatly
