### ISSUE TITLE
Oddities after svn clone

### ISSUE THREAD

**Issue by cfneese** [gitextensions/gitextensions#6396]
## Current behaviour

After cloning a repository from an svn server using git-svn, GE exhibits the following odd behaviors:
1.  In the left panel, nothing appears under remotes, even though the imported branches appear in green as expected in the graph panel.
2.  If you try to checkout a remote branch, GE's suggested name for the local branch includes the prefix used by git-svn.
3.  If you add a remote with a name matching the git-svn prefix, the above behaviors go away.  This is risky though, as the prefix used by git-svn does not represent an actual git remote. 

## Expected behaviour
`git branch -r` lists svn-tracking refs as if they were normal remote refs, so it is expected that GE would do the same.  In general, GE should be aware that `git branch -r` may indicate remote names not listed by `git remote`.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 168dpi (175% scaling)

**Comment by vbjay** [comment]
https://github.com/gitextensions/gitextensions/pull/4658

**Comment by gerhardol** [comment]
Use of git-svn should be OK, even if the command has been removed from the GE GUI
What does ```git remote -v``` show?
Anything in the Remotes form?

**Comment by cfneese** [comment]
`git remote` and `git remote -v` both return nothing in this scenario.  That is the source of the odd behavior.  The remotes form is also empty.  As mentioned in point 3, you can manually add a dummy remote with the prefix used by git-svn and the odd behaviors will go away.  This is because GE will then get the name of the git-svn prefix from the dummy remote.  That is not a satisfactory work around though, because it enables all the other git remote commands, which will fail.

**Comment by RussKie** [comment]
I'm not quite sure what the expectation is. The left panel and the remotes form are showing the results of `git remotes` command.

**Comment by cfneese** [comment]
From my perspective, I want GE to treat git-svn remote branches identically
to regular remote branches, at least where that is possible.  I think the
checkout branch dialog is more important.  If your branch is
'origin/branchname', GE will normally create a local branch named
'branchname' and default to 'origin_branchname' for the custom branch
name.  For a git-svn remote branch, these become  'origin/branchname' and
'_origin/branchname', respectively.  Neither one of those is a good branch
name.  There is an easy enough workaround, you just provide the custom
branch name that you want.  But having the local branch show up in GE with
the exact same name as the remote name is not a good default, IMO.

For the left panel, I would like to see the tree populate off of git branch
-r instead of git remote.  However, the context menus would have to be
minded as well.

**Comment by gerhardol** [comment]
GE handles remotes and git-svn has some implicit handling of remotes it seems.
Can you specify the remote with -R?

**Comment by mast-eu** [comment]
> Use of git-svn should be OK, even if the command has been removed from the GE GUI.

Yes, git-svn is ok. I use it daily at work. You just have to use it from console ([or setting up scripts once](/mast-eu/GitExtensions.SVN/wiki/Workarounds#1-configure-scripts-in-git-extensions)).

I'll try to shed some light onto what happens in detail:

After a fresh clone with `$ git svn clone http://example.com/svn/repo_name`, you see this:

![svn clone](https://user-images.githubusercontent.com/46861028/55174736-4660f800-517e-11e9-9d4c-49038a3c124d.png)

You have the common local branch "master":
```
$ git branch
* master
```

And a remote tracking branch "origin/trunk":
```
$ git branch --remote
  origin/trunk
```

But no _git remotes_:
```
$ git remote --verbose

```

Instead, you have a _SVN remote_:
```
$ git svn info --url
http://example.com/svn/repo_name/trunk
```

When you checkout the remote branch "origin/trunk", GE shows:

![svn checkout](https://user-images.githubusercontent.com/46861028/55174787-60023f80-517e-11e9-82a9-12fae156f85d.png)

**Comment by gerhardol** [comment]
> Instead, you have a SVN remote:

Then this is not changed from 2.x. 
I see no simple way to support svn remotes.
