### ISSUE TITLE
GitHub Plugin: Allow sorting on the column headers

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#6404]
## Feature description

When retrieving the "My repositories"/"Search for repositories" list via `GitHub` -> `Fork/Clone repositories`, the order in which the repos are listed has always been unfathomable to me.

See the red box in the screenshot for an example.

So, I'd like to suggest the following:

#### Basic solution

Sort the list of repositories received from the GH API by name (case-insensitive) before displaying them.

#### More advanced solution

Allow the end-user to sort the list based on the columns being display by clicking on any of the column headers (blue box in the screenshot).

Similar to other typical sorting interfaces in Windows programs, I would imagine this would work like so:
* One click on a column header: sort ascending on that column.
* Second click on that same column header: reverse sort order (sort descending)
* Click on another column header: sort ascending on that column with any previous sorting as secondary criteria.

![GE-GH-sorting](https://user-images.githubusercontent.com/663378/54888186-2ccc6180-4e9b-11e9-8c23-a80a5f17cee4.png)

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
>Basic solution

>Sort the list of repositories received from the GH API by name (case-insensitive) before displaying them.

I don't remember but I think I already did it. Could you verify on `master` ? 


>More advanced solution

>Allow the end-user to sort the list based on the columns being display by clicking on any of the column headers (blue box in the screenshot).

Due to a technical constraint in winforms, the column is not sortable even if it is set as so. And make it sortable effectively is a pain. I judge it was not worth it to loose my time on this feature for the few added value. But if someone want to do it...

**Comment by jrfnl** [comment]
> I don't remember but I think I already did it. Could you verify on master ?

@pmiossec I've just tested with the portable version on `master` via the [build artifact](https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts) and AFAICS there is no difference, so looks like it hasn't been implemented yet.

> Due to a technical constraint in winforms, the column is not sortable even if it is set as so. And make it sortable effectively is a pain. 

:+1:  If the list is sorted alphabetically, there will probably rarely be a need for further sorting, so I'd be good with just the basic solution.
