### ISSUE TITLE
remotes re-activate

### ISSUE THREAD

**Issue by HemetsS** [gitextensions/gitextensions#6410]
Hi everybody.
I found an unexpected behaviour using remotes in GITExtensions.

## Current behaviour

Remotes are not listed if i deactivate and activate it.

## Expected behaviour

When re-activate a remote, it should be displayed automatically.
By running "git remote update" manually the remote will be in the list

## Steps to reproduce

- There are two remotes for example
- I deactivate one remote (set visibility to false) -> that works
- When i activate the remote again, it will not be in the list (also if i press refresh)

## Screenshots

in the attached pdf-file

## Environment

- GitExtensions version: 3.0.2.5232
- GIT version:  2.21.0.windows.1
- OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET version: 4.7.3324.0

## Files

[git remote update.pdf](https://github.com/gitextensions/gitextensions/files/3011872/git.remote.update.pdf)

**Comment by RussKie** [comment]
You need to fetch all remotes before they are visible. 
When a remote is deactivated `git remote remove` is run, when a remote is activated it is only added to the .gitconfig file, however you must make git aware of it.

In the next release the left panel will allow an easier way to activate/deactivate remotes
![image](https://user-images.githubusercontent.com/4403806/55065043-363e0f80-50cf-11e9-84d7-7ab7ce13b096.png)

**Comment by HemetsS** [comment]
Alright, thank you.
