### ISSUE TITLE
Plugin installation path

### ISSUE THREAD

**Issue by maraf** [gitextensions/gitextensions#6415]
## Feature description

In PluginManager scenario, when GE is in the write-protected directory, UAC must be confirmed everytime PM tries to do changes.

In maraf/GitExtensions.PluginManager#59 and gitextensions/gitextensions#5775 we have briefly discussed that all plugins could be placed somewhere else, eg `CommonApplicationData`.

I would like to discuss the solution and then would be happy to do a PR.

**Comment by RussKie** [comment]
User's settings are stored in `C:\Users\<user>\AppData\Roaming\GitExtensions\GitExtensions`, would this be a good place to store plugins too?

**Comment by mast-eu** [comment]
Quick check on software with downloadable plugins found on my PC:
- Visual Studio uses `C:\Users\<user>\AppData\Local\Microsoft\VisualStudio\15.0_b13c254b\Extensions`
- Visual Studio Code uses `C:\Users\<user>\.vscode\extensions`
- GIMP uses `C:\Users\martin.steinisch\AppData\Roaming\GIMP\2.10\plug-ins`

And a few more I looked up on the internet:
- [Firefox](https://developer.mozilla.org/en-US/docs/Plugins/Guide/Plug-in_Basics#How_Gecko_Finds_Plug-ins) uses `C:\Users\<user>\AppData\Local\Mozilla\plugins`
- [Chrome](https://stackoverflow.com/questions/14543896/where-does-chrome-store-extensions) uses `C:\Users\<user>\AppData\Local\Google\Chrome\User Data\Default\Extensions `
- [Notepad++](http://docs.notepad-plus-plus.org/index.php/Plugin_Central) uses `C:\Users\<user>\AppData\Roaming\Notepad++\plugins`

There seems to be a common agreement to use `C:\Users\<user>\AppData\<Local|Roaming>`, with VS Code being the only notable exception I found. But even VS Code uses `C:\Users\<user>`, so different users on the same machine are isolated against each other.

What's the difference between `C:\Users\<user>\AppData\Local` and `C:\Users\<user>\AppData\Roaming`? [MSDN explains](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776892(v=vs.85).aspx) that Roaming User Profiles are automatically synced when the user logs on any PC on the same (company) network. On the other hand, Local User Profiles remain on a single PC.
IMHO it's better to not sync plugins between PCs. Maybe they have different GE versions, .NET versions or other troublemakers.

Conclusion:  Something like `C:\Users\<user>\AppData\Roaming\GitExtensions\GitExtensions\plugins\<plugin_name>` should be fine for plugin-specific data, if needed. But I prefer  `C:\Users\<user>\AppData\Local\GitExtensions\GitExtensions\plugins\<plugin_name>` for the binaries.

**Comment by RussKie** [comment]
Thank you.
The only reason I'd go to `Roaming` to have all our files in one place. But it is not a deal breaker for me (at least at this stage).

**Comment by maraf** [comment]
As part of this change:
1) Should all plugins (even those pre-installed) be moved there?
2) Should the pre-installed plugins be packed as nugets?
3) Should there be a way to clean up this folder (in case of things go wrong)?

The PM is pre-installed and has a self update feature, so it should be in the AppData folder.

**Comment by RussKie** [comment]
> 1. Should all plugins (even those pre-installed) be moved there?
> 2. Should the pre-installed plugins be packed as nugets?

Yes, when we actually get to separating plugins out of the main repo





> 3\. Should there be a way to clean up this folder (in case of things go wrong)?

Possibly

**Comment by mast-eu** [comment]
Manually closing issue, after #6551 has been merged.
(I just learned that `Solves #6415` does not [close issues automatically](https://help.github.com/en/articles/closing-issues-using-keywords) when merging a PR)

**Comment by vbjay** [comment]
https://help.github.com/en/articles/closing-issues-using-keywords

That's why it templates say
```
fixes #
```

**Comment by vbjay** [comment]
https://help.github.com/en/articles/closing-issues-using-keywords

That's why our templates say
```
fixes #
```
