### ISSUE TITLE
Add MD format for release notes plugin

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#6416]
## Feature description

Add a MD template to release notes.  This would allow us to specify fields from the log output and place them in our MD where we desire. 

Example:
```
**{Hash}**: {subject} {Time}
{body:3}
{sig}
```
## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Could you please elaborate more?

**Comment by vbjay** [comment]
So allow us to define a markdown template per log entry.  When generated, the log output would replace fields in the template with the values. This would allow us to generate our own format.

**Comment by RussKie** [comment]
Apologies, I'm still not following you.
Is this for a plugin or something else? Any sketches/screenshots?

**Comment by vbjay** [comment]
Our rwalease notes plugin. Look at the outputs available. I an saying we
allow MD input. Providing template fields. So if someone wanted to create
their own output format with markdown they could.

**Comment by RussKie** [comment]
Gotcha, thanks!
