### ISSUE TITLE
Invisible text when filtering files in Commit dialog

### ISSUE THREAD

**Issue by gwarnants** [gitextensions/gitextensions#6418]
## Current behaviour

When trying to filter files in the main Commit dialog, entered text disappears, but the filtering is correctly applied in the files below.

## Expected behaviour
The entered text should be visible

## Screenshots

![gitextension-filter](https://user-images.githubusercontent.com/810054/55219002-edd43e00-5203-11e9-838f-9bbbb4aae279.gif)

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Could you please search in the existing issues. That has already been
reported and maybe even fixed.

**Comment by gwarnants** [comment]
Probably related to these ones : [#6336](https://github.com/gitextensions/gitextensions/issues/6336) [#6338](https://github.com/gitextensions/gitextensions/issues/6338) [#6378](https://github.com/gitextensions/gitextensions/issues/6378)

But my problem does't occur in the same window as these previous issues

**Comment by pmiossec** [comment]
I think that's the same component used in different places and #6337 should fixed it.
You probably should test the development version to ensure it is (I myself don't have the problem in the commit dialog, so it should be fixed)

**Comment by RussKie** [comment]
Could you please try this build and see if your issue is still present
https://ci.appveyor.com/api/buildjobs/7lae31096vj4icvr/artifacts/Setup%2FGitExtensions-Portable-3.1.0.5578.zip

If it is, please provide steps to reproduce

**Comment by nsartor** [comment]
I'm not the original submitter, but I've been experiencing the same problems. @RussKie I tried your build and it seems to have fixed the issue for me.

**Comment by RussKie** [comment]
Thank you for the confirmation.
