### ISSUE TITLE
Ctrl key stuck after commit

### ISSUE THREAD

**Issue by hultqvist** [gitextensions/gitextensions#6420]
## Current behaviour
Quite often the Ctrl key get "stuck" when making commits.

This is fixed by pressing and releasing Ctrl.

## Steps to reproduce

1. Add files, but not all, and write a commit message.
2. in the commit message press Ctrl + Enter to commit, wait for the commit to finish.
3. Start typing again.

At step 3 the Ctrl key is active making key presses do unexpected things such as making the text box right aligned.

This does not happen every time but about 1 in 3 times.

## Did this work in previous version of GitExtensions

Before the major upgrade to version 3 I had no issues 

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.3745.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Perhaps idiot question but I prefer to be sure because that's very strange from a software point of view...

Are you sure that the behavior don't come from your keyboard?
To be more explicit, did you reproduced on another computer?

**Comment by hultqvist** [comment]
I'm afraid I have nowhere else to try.
Though I'm using

**Comment by mast-eu** [comment]
What happens if you use any other software on the same PC, let's say, for example, a Texteditor?
You could try using CTRL+O to open a file and then start typing. 
Do similar issues happen in that case?

**Comment by illfated** [comment]
@hultqvist : Could you verify that you have not inadvertently activated "sticky keys" in Windows 10 by holding a key too long?
I made that mistake a couple of weeks ago, making it impossible to type fast and also some other weird typing behaviour.

**Comment by hultqvist** [comment]
Checked windows settings and sticky keys is off.

Today it happened in the main window.
I was clicking on files in a commit to see their changes.
Every file I clicked was highlighted and the previous highlight was kept, as if I held down Ctrl.

At this time I stared notepad and pressed o, trying to see if Ctrl+o was triggered, but I got the letter o.
Then I went back to GitExtensions and tried again, making sure to never touch any Ctrl key during this process. Now the Ctrl effect was not longer there.

I tried to look through the source but it appears to be a standard WinForms list control so perhaps there isn't specific to di with GitExtensions.

I understand these are vague observations, just wanted to write them down in case others have similar experiences, at that point this might be more relevant.

**Comment by clementpuell** [comment]
I would suggest to reopen this issue as there definitely is a strange behavior somehow related to GitExtensions.

Those exact symptoms described by @hultqvist have always happen to me, for as long as I have used GE (several months at least). On different machines, on different keyboards and on different Windows 10 updates. But always exclusively with GE, never any other software.

Common symptoms are that randomly and suddenly:
- Clicking on rows will multiselect them, like when Ctrl is pressed.
- Pressing the "Down" key will open the Pull dialog, like when Ctrl+Down is pressed.
- Pressing the "Up" key will open the Push dialog, like when Ctrl+Up is pressed.

Behavior disappear either on pressing Ctrl or Shift, sometimes by itself. It happens around once per hour.

---

Git Extensions 3.1.0.5627
Build 3bfd76daf35dd0ae7ba4822837f0039b455b810b (Dirty)
Git 2.20.1.windows.1
Microsoft Windows NT 10.0.18362.0
.NET Framework 4.8.3752.0
DPI 192dpi (200% scaling)

**Comment by hultqvist** [comment]
OK, re-opening so it can help tracking similar observations.

My guess is that it's related to the git running and somehow affecting the modifier key state.

**Comment by MaGnaL** [comment]
I do have the same problem from time to time. But unfortunately I was not able to reproduce it reliably until now. I also can not add further information to investigate the problem.

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
I always work with recent canary builds on different machines (all Win7). Though usually, I use the Console Emulator and no auto-close. Which settings do you use, @hultqvist, @clementpuell, @MaGnaL?
![grafik](https://user-images.githubusercontent.com/36601201/56926370-f6a18380-6ad1-11e9-81f0-7f26bba6bc39.png)
Even with both switched off, I could not reproduce this sticky Ctrl key.
What do you mean with "wait for the commit to finish", Peter @hultqvist?

**Comment by hultqvist** [comment]
These are my settings.
![image](https://user-images.githubusercontent.com/505330/56927775-459ce800-6ad5-11e9-84d5-4bfbf072e0a7.png)

"wait for the commit to finish" meant that it takes a few seconds for the commit to finish. During this time I don't press any keys.  
My initial suspicion was that I was holding down the Ctrl key while pressing Ctrl + Enter, and then I release the keys while the commit window or some flashing console window had focus, then when the commit was complete, the commit window never received the Ctrl key_up event.
Though I haven't been able to reliably reproduce it.

**Comment by MaGnaL** [comment]
These are my settings.
![image](https://user-images.githubusercontent.com/4709544/57210239-38ec2880-6fdc-11e9-8ac0-55ee71b7c304.png)

**Comment by mstv** [comment]
I cannot reproduce it under Win7. I will switch to Win10 not until next year.
Perhaps other Win10 users can reproduce it by using `Ctrl+Enter` to confirm the Commit dialog.

**Comment by clementpuell** [comment]
I managed to get an perfect repro with the Quick Fetch shortcut and the "Use Console Emulator" settings **on**. Indeed, no problem occurs with the settings off.

1) Press `Ctrl+Shift+Down` normally.
2) Wait for it to finish and for the Console to close. The graph is going to start refreshing, with a loading indicator displayed.
4) Input commands _just before_ the refresh finishes and the loading indicator disappear. I'm talking like one tenth of a second before the graph is displayed again.
For instance: Press Down here and a new Quick Fetch will start. Press Up and a Quick Push will start. Click somewhere and multi row selection will start as soon as the graph is displayed again.

---

![image](https://user-images.githubusercontent.com/11089188/57301218-c6ad3e00-70d8-11e9-9cff-2fddb17cbc94.png)

- Git Extensions 3.2.0.5774
- Build 88d36b8ad8f172920aa59b48cd7f313cbba1cb25 (Dirty)
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3752.0
- DPI 192dpi (200% scaling)

**Comment by mstv** [comment]
Thank you, I can reproduce it in 1 of about 20 trials using `Shift+Ctrl+Down`, especially if the three keys are released very quickly. When it happens, I even cannot close the console dialog by pressing the `Space` or `Enter` keys.

So I guess this is another ConEmu issue.

![grafik](https://user-images.githubusercontent.com/36601201/57409089-a8823380-71e7-11e9-89f8-2311c200c1bc.png)

**Comment by RussKie** [comment]
Is this reproducible with conemu disabled?

**Comment by mstv** [comment]
> Is this reproducible with conemu disabled?

No, not in @clementpuell's and my tests.

**Comment by RussKie** [comment]
Perhaps we may need to consider a replacement for conemu...

**Comment by gerhardol** [comment]
> Perhaps we may need to consider a replacement for conemu...

Just displaying a warning when enabling with known issues should be enough

**Comment by GabrieliusKazakevicius** [comment]
Hello, I was just about to register similar issue since i'm having the same problem. CTRL key appears to be stuck after facing some dialogues in GitExt (even though the key was not used in any activity in dialogue whatsoever). As mentioned before, it's fixed by pressing CTRL one more time. Not a big deal, but still irritating.

**Comment by illfated** [comment]
This is one of those bugs where you ponder if you should track down the bug and kill it as soon as possible, or leave it alone until it dies from other changes in the source.

**Comment by gerhardol** [comment]
Sure, this annoying, but there is no quick fix.

The core problem seem to be related to ConEmu, as well as other problems (some crashes, pop up/under).
The issues raised to ConEmu have not gotten anywhere (other than requests to upgrade ConEmu, which maybe has increased problems). This need to be investigated by someone that can reproduce and have sufficient knowledge of GE and ConEmu.

This is hard to investigate if you cannot reproduce, especially since this is in another package (ConEmu).
To disable ConEmu completely seem a little harsh (I will miss the functionality and do not see the problems). GE could warn all users though.

**Comment by RSchwoerer** [comment]
Just wanted to comment and say I believe I was seeing this issue also. It is definitely a crazy-making bug.
I have turned off ConEmu in the settings for now to see if that is a cause of the issue.
