### ISSUE TITLE
Checkout branch that exists in remote should create local branch automatically like "git checkout" command

### ISSUE THREAD

**Issue by jjcole** [gitextensions/gitextensions#6422]
## Current behaviour

1. CTRL-. to Checkout branch
2. Enter name of a branch for which a remote branch exists but there is no local branch yet
3. Red icon: "An existing branch must be selected."

## Expected behaviour

3. Local branch is created automatically

Besides working in previous versions, I expect it to work this way since that's the behaviour of "git checkout <branch>" from command line.

I realize I can go to "Remote branch" but this is a less efficient workflow if you're checking out other developer's branches often for code review.

## Steps to reproduce

1. Create local branch
2. Push to remote
3. Checkout master (or other branch)
4. Delete local branch (git branch -D <branch>)
5. CTRL-. to Checkout branch
6. Enter name of branch you created

## Screenshots

![image](https://user-images.githubusercontent.com/581226/55259924-64416200-523d-11e9-9df4-78b160f398db.png)

## Did this work in previous version of GitExtensions

Yes, I believe it worked in 2.x and broke when I upgraded to 3.0 and has remained broken since.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.14393.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Yes it was like this in 2.x, but you hade to type the complete name, completion not helping. which you get by ticking remote.
Should this really be handled as a bug?

**Comment by vbjay** [comment]
That's by design. Checkout a **LOCAL** or a **REMOTE** branch.

**Comment by vbjay** [comment]
We have create branch to CREATE a new branch.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/55266759-f2751280-5254-11e9-868c-f54cff42a5c3.png)
![image](https://user-images.githubusercontent.com/3629489/55266779-01f45b80-5255-11e9-984b-967cd2671ae8.png)

**Comment by RussKie** [comment]
If there is no local branch you can't check it out. You need to select a remote branch.

**Comment by jjcole** [comment]
@vbjay My point is that "git checkout <branch>" from command line DOES automatically create that local branch if it doesn't exist, even though you are technically asking it to checkout and not to create.

IMO it's more intuitive for GitExt behaviour to behave similarly to the same command line feature.

**Comment by jjcole** [comment]
@vbjay Thanks the right-click option is pretty handy. Unfortunately with 40+ developers in our repo, viewing all branches is chaos so I'd typically be filtered only on my current branch. Even if I viewed all branches it would be pretty inefficient to try and find it in the UI first, when I already have the branch name and can simply "git checkout branchName" instead.

**Comment by vbjay** [comment]
We did it that way to allow us to control the options. We use checkout to
checkout an existing branch. We use the create branch menu option to create
a new branch. It gives us finer control and is clearer to the user. I want
to create a branch. I'll click create branch. I want to checkout a local
branch. I'll use checkout dialog with local selected. I want to checkout a
remote branch. I'll use remote option. With our Auto complete it's not hard
to filter down.

**Comment by illfated** [comment]
@jjcole : I suggest using the simple workaround `git checkout origin/branchName` in the Console.

**Comment by jjcole** [comment]
Fair enough, thanks @vbjay and everyone for taking the time to explain.

@illfated I'll continue to use Console instead, but in my case (with only one remote called `origin`, `git checkout branchName` is sufficient, it will automatically create a local `branchName` on the commit that `origin/branchName` currently points to.

**Comment by RussKie** [comment]
> Unfortunately with 40+ active developers in our repo, viewing all branches is chaos

This suggests you may need to rethink how your team works, forks help in such situations.

If there are multiple remotes, checking out a branch that may exist in several remotes is an ambiguous situation. Hence we ask the user to be explicit.

**Comment by jjcole** [comment]
@RussKie I just added a second remote to test. Both the remote1/ branches and the origin/ branches appear in the drop-down if I open it without typing anything.

So imagine I have this list of branches from my 2 remotes:

remote1/feature/branch1
remote1/feature/branch2
remote2/feature/branch2
remote2/feature/branch3

I don't see how typing "branch2" here is ambiguous. I'm not suggesting it magically know which remote I want "branch2" to come from. I'm suggesting that typing "branch2" brings up both of these options in the drop-down:

remote1/feature/branch2
remote2/feature/branch2

It seems odd to me that you guys seem to think this is not possible, when we already have the same behaviour if you search "remote1/feature", it will find that multiple branches exist that match that string and display both of them in the drop-down, so you can click or scroll and select the one you want.

The fact that the drop-down contains branches from both remotes mean you essentially have a list or array of strings that you are doing the equivalent of a string.StartsWith search against. All it would take to resolve this is a string.Contains search instead.

Then you could type "feature" and get all 4 feature branches from both remotes.

**Comment by jjcole** [comment]
It turns out this looks like a limitation of the C# TextBox.

`this.Branches.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.SuggestAppend;`

Looks like the built-in auto-complete only supports searching at the beginning of the string.

Example link here (I found serveral) confirming that AutoCompleteMode only works with StartsWith, not Contains. https://social.msdn.microsoft.com/Forums/vstudio/en-US/4c229a73-cdad-4fa3-95db-97f9ff7810c1/autocomplete-match-on-contains-not-startswith?forum=netfxbcl

**Comment by gerhardol** [comment]
> If I do end up forking and implementing this I'll link here in case anyone else wants to do the same.

PRs are welcome.
A good description and discussion will increase the possibilities that someone picks up the idea.
