### ISSUE TITLE
auto commit after merge develop to master

### ISSUE THREAD

**Issue by RaymondDeen** [gitextensions/gitextensions#6429]
Issue  #3441 seems to be alike somewhat.

## Current behaviour

I initiate a merge from develop to master branche with option "Do not commit" ticket.
The commit is automatically done with commit message same as last commit message on develop branch.

## Expected behaviour
Items to be commited appear in menu button "Commit" that also should not be coloured green anymore.

## Steps to reproduce

Commit something to develop branch and initiate a merge from develop to master with option ticket (by default already ticked, but just to be sure untick and re-tick the option).

## Screenshots

Sorry, no screenshot available.

## Did this work in previous version of GitExtensions

It did work in the previous version I had installed, not sure whether I was on the 2.x or 3.x version that I saw it working.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3362.0
- DPI 144dpi (150% scaling)

## Diagnostics

Not relevant I guess.

**Comment by RaymondDeen** [comment]
Hi @RussKie, I see the tag "status: needs review". Do you need any clarification on this issue, or are you just too busy?

**Comment by RussKie** [comment]
Yes, it is primarily to indicate that someone from the core team needs to think about. You're welcome to send a PR, that would speed up things.

We have another label "More info requested" to mark tickets where more information is required.

**Comment by mstv** [comment]
I could not reproduce this issue with the [newest build 5763](https://ci.appveyor.com/api/buildjobs/waglkhl3v1x9tqeg/artifacts/Setup%2FGitExtensions-Portable-3.1.0.5763.zip).
Did you mean the following sequence?
![grafik](https://user-images.githubusercontent.com/36601201/56912606-e37dbc00-6aaf-11e9-9507-3646f650c45e.png)
![grafik](https://user-images.githubusercontent.com/36601201/56912685-145df100-6ab0-11e9-89d3-2fffab8b2fd0.png)
![grafik](https://user-images.githubusercontent.com/36601201/56912719-28095780-6ab0-11e9-885c-bd966af2a843.png)

**Comment by RaymondDeen** [comment]
Hi Michael,
thank you for your response.
When checked the box "Do not commit", GitExt indeed skipped the commit message screen entirely and auto-commited re-using the latest commit message.
Will 3.1 be publicely available soon?

**Comment by gerhardol** [comment]
The plan is to have a RC soon
