### ISSUE TITLE
Support for VS2019

### ISSUE THREAD

**Issue by SeanFeldman** [gitextensions/gitextensions#6431]
What version to expect support for VS2019?

**Comment by Aleksanderis** [comment]
Quick workaround - download `*.msi` installer, extract it, find there `GitExtensoinsVSIX.vsix`, which is also just a packed archive. Extract `GitExtensoinsVSIX.vsix` and modify `extension.vsixmanifest`, changing following line:

`<InstallationTarget Version="[14.0,17.0)" Id="Microsoft.VisualStudio.Community" />`
to:
`<InstallationTarget Version="[14.0,18.0)" Id="Microsoft.VisualStudio.Community" />`

Add modified file to `GitExtensoinsVSIX.vsix`.

**Comment by RussKie** [comment]
A PR is welcome 😏

**Comment by vbjay** [comment]
#5864

**Comment by vbjay** [comment]
What we really need is ci publish to marketplace.

**Comment by RussKie** [comment]
Sadly #5864 isn't addressing the question, a tweak is still required.

I reached out to @spdr870, but we need to build the publishing pipeline
https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-publishing-a-visual-studio-extension-via-command-line?view=vs-2019

**Comment by gerhardol** [comment]
The code is changed, just not uploaded:
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by RussKie** [comment]
I've up'ed the limit to 18.0
I'll get @spdr870 to upload a new version to the marketplace.

**Comment by RussKie** [comment]
Could you please test this VSIX - https://ci.appveyor.com/api/buildjobs/1w36e8fgfvysdwn4/artifacts/GitExtensionsVSIX%2Fbin%2FRelease%2FGitExtensionsVSIX.vsix

If it is good, we'll get it publish to the marketplace

**Comment by miki-bgd** [comment]
Installed on VS community 2019.
The only thing is that it wasn't added as a new menu item, but as menu under Extensions.
Here is the image.

![gitext](https://user-images.githubusercontent.com/6333352/55535144-9415bd00-56b6-11e9-9f3e-d615be60a042.jpg)

**Comment by Aleksanderis** [comment]
> Installed on VS community 2019.
> The only thing is that it wasn't added as a new menu item, but as a submenu under Extensions.
> Here is the image.
> 
> ![gitext](https://user-images.githubusercontent.com/6333352/55535144-9415bd00-56b6-11e9-9f3e-d615be60a042.jpg)

I think it will be as by design now. For example - ReSharper is also being added to same menu. So maybe Visual Studio is restricting to override it, to reduce the UI clutter.

**Comment by miki-bgd** [comment]
Yes, it seems.
> In VS 2019, top level menus contributed by extensions are placed under the Extensions menu.

As from here: [docs.microsoft.com](https://docs.microsoft.com/en-us/visualstudio/extensibility/adding-a-menu-to-the-visual-studio-menu-bar?view=vs-2019)

However, it is possible to create manually top level menu, and add commands one by one. But for now i couldn't find solution just to move complete group.

**Comment by spdr870** [comment]
@RussKie requested my to uploaded a new VSIX. I just uploaded it to the visual studio marketplace. It is currently validating the upload, that will take a little time.

**Comment by spdr870** [comment]
About the token for the automated upload, I would like to transfer the project from HenkWesthuis.GitExtensions to GitExtensions.GitExtensions. I think its better to create the token after the transfer. I can also add members to the project then. I probably will do this in the upcoming days. Its not a lot of work, but I want to make sure it won't break existing installations.
