### ISSUE TITLE
Index not Restored when Popping Stash

### ISSUE THREAD

**Issue by BlackStarX42** [gitextensions/gitextensions#6432]
## Current behaviour
When popping a stash, files do not get staged which were staged when the stash was created.
## Expected behaviour
When popping a stash, adding the files to the stage which were on stage before stashing them. I guess when issuing the git command to pop the stash, "--index" may be missing.
## Steps to reproduce
- make a change in a repository
- add the change to the stage
- stash all changes
- pop the stash -> the change of the file will be restored, but it is not added to the stage
## Did this work in previous version of GitExtensions
Presumably not.
## Environment
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
I reproduce (behavior and proposed solution).

But I wonder if it's not made in purpose as there are more chances that the pop fail :

`If the --index option is used, then tries to reinstate not only the working tree’s changes, but also the index’s ones. However, this can fail, when you have conflicts (which are stored in the index, where you therefore can no longer apply the changes as they were originally).`

I'm not sure how we could handle that....

**Comment by BlackStarX42** [comment]
I would say, there can always be conflicts when applying a stash. That also affects the working copy, not only the index. The point is, what is expected: If you stash your changes _including_ the index, you certainly would want to apply a stash _including_ the index again. There is already an option to keep the index when creating a stash. In case you purposely don't want to restore the index when applying a stash, it would make perfect sense to add a checkbox on the stashes dialog to omit the "--index" when doing so.

**Comment by pmiossec** [comment]
In fact, I completely agree with you that restoring the index would be a good thing.

I was just not sure of the behavior with the option regarding to what the doc said.
I have tested and if there is a conflict, the behavior with or without the "--index" is quite the same.

So I think that we could just add it to always use it... (except if I miss something)

**Comment by gerhardol** [comment]
So the proposal is to include --index when popping?

**Comment by BlackStarX42** [comment]
Yes, my proposal is to include --index when popping. I also propose to add a checkbox on the Stash window to allow for disabling this option when clicking "Apply Selected Stash", very similar to the "Keep index" checkbox, which is used when you click "Stash selected changes". Most probably we want something like "Exclude Index [when Popping]" or "Don't Restore Index [when Popping]" as the caption for the new checkbox. It might be useful to adjust the caption of the "Keep index" checkbox to make clear that it applys only to the stashing, not the popping, e.g. "Keep Index when Stashing".
