### ISSUE TITLE
Hex View on Blame Tab Always Shows Working Copy instead of Selected Revision

### ISSUE THREAD

**Issue by BlackStarX42** [gitextensions/gitextensions#6434]
## Current behaviour
For a binary file, the hex view on the blame tab does not show the version which is selected in the revision graph and instead always shows the version in the working copy.
## Expected behaviour
The hex view should show the revision selected in the revision graph.
## Steps to reproduce
- Create a file which is considered a binary file by git (e.g. a UTF-16 file with BOM), it must be at least 14 bytes to show up as a hex view on the blame tab (which seems to be another bug to me),
- commit the file to the repository,
- add something to the file,
- open the history of the file and go to the blame tab, you will see that the hex view shows the recent change you made to the file, though it is not even committed yet.
## Did this work in previous version of GitExtensions
Don't know.
## Environment
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Same in View tab

**Comment by mstv** [comment]
> it must be at least 14 bytes to show up as a hex view on the blame tab (which seems to be another bug to me)

GE uses an heuristic: A file must contain at least 6 zero bytes to be displayed as binary. See https://github.com/gitextensions/gitextensions/blob/a4c5d3c30aac7c73441994ad0a85d5e59b08f1f4/GitCommands/FileHelper.cs#L165-L185

**Comment by BlackStarX42** [comment]
> > it must be at least 14 bytes to show up as a hex view on the blame tab (which seems to be another bug to me)
> 
> GE uses an heuristic: A file must contain at least 6 zero bytes to be displayed as binary. See 

I wasn't aware of that. I would have expected that GE asks git for the file type. Isn't that possible and wouldn't that make more sense?

**Comment by pmiossec** [comment]
Git use an heuristic, too. But not exactly the same: https://stackoverflow.com/a/54182883/717372  (And I just understood that's the reason why Git always detect UTF16 files as binary)

> I would have expected that GE asks git for the file type. Isn't that possible and wouldn't that make more sense?

Probably (but surely will be a lot less performant)

A solution (but seems not working with git-lfs where binary files are seen as text from what I have tested): 
https://www.closedinterval.com/determine-if-a-file-is-binary-using-git/

Perhaps another solution (but I don't know how to interpret that. Looking for ` w/-text`?):
https://stackoverflow.com/a/54198950/717372
