### ISSUE TITLE
Cow-icons missing

### ISSUE THREAD

**Issue by kabukimurder** [gitextensions/gitextensions#6437]
The cow-icons featured in version 2.xx have yet to be re-added in version 3. This is confusing since without the purple cow application-icon in the taskbar it's unclear if Git Extensions is open or not, resulting in the user opening several instances of the application.

Please also re-add the option to have the cow on the opening screen. Not being able to be greeted by a cow with shades has eliminated the whole purpose of having a "first day of summer" for all users who have upgraded to Git Extensions 3.xx.

Thanks.

**Comment by vbjay** [comment]
-Not running
![image](https://user-images.githubusercontent.com/3629489/55563590-3b4d2100-56c4-11e9-8f0f-4f6d9d3c10e6.png)
- Running not active
![image](https://user-images.githubusercontent.com/3629489/55563634-4bfd9700-56c4-11e9-8496-5e58380191aa.png)
- Running Active
![image](https://user-images.githubusercontent.com/3629489/55563658-57e95900-56c4-11e9-99a6-ef0818904858.png)

**Comment by vbjay** [comment]
Please use our issue templates.  We have them fro a reason.  
![image](https://user-images.githubusercontent.com/3629489/55563763-8830f780-56c4-11e9-9412-6cb932e0405b.png)

**Comment by gerhardol** [comment]
The cow items were dropped, as they did not fit the style of the other icons.
#5087
