### ISSUE TITLE
FileStatusList: indicate active filter

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6449]
## Feature description

An entered file filter for the FileStatusList can be overlooked too easily.
The ComboBox's window color (or text color for a future dark theme) should be changed if the filter string is not empty.
Maybe we could even indicate the validity of the regex, e.g. green and red.

In preparation of switching color schemes, a new Control class should be created.

Thoughts?

### Before

![old](https://user-images.githubusercontent.com/36601201/55685522-761ab780-5957-11e9-8a7a-5810410309a2.png)

### After

regex valid
![ok](https://user-images.githubusercontent.com/36601201/55988577-83f87180-5ca4-11e9-951d-c3e785bbded1.png)

regex error
![error](https://user-images.githubusercontent.com/36601201/55988805-1f89e200-5ca5-11e9-8976-0b419e388029.png)

## Environment

- Git Extensions 3.1.0
- Build 28fcbf1e864ecc2238ef9001586c537957c6c73b
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Agree that the fact that a filter is active could be made more prominent. 👍 

Not particularly comfortable with the choice of a colour though. 

What is a given filter doesn't yield any results? Green colour is an indicator of success/permission (e.g. green tick, green colour of traffic lights).
If the filter yielded no results the filter box should perhaps be red or orange (i.e. a warning colour).

I'm also not sure about setting the background colour of the filter control, it feels overpowering. 
Perhaps colouring the control's borders to a respective colour could be a solution.

Require further experimentations.

**Comment by gerhardol** [comment]
I would prefer to just have the filter text in bold.
The green is ugly, I would vote against a PR with that color...

**Comment by mstv** [comment]
That's exactly how Wireshark handles it.
I knew you would not like it very much. That's why I haven't implemented it yet.

> What is a given filter doesn't yield any results? Green colour is an indicator of success/permission (e.g. green tick, green colour of traffic lights).
If the filter yielded no results the filter box should perhaps be red or orange (i.e. a warning colour).

This would be over-engineered in my opinion.

> Perhaps colouring the control's borders to a respective colour could be a solution.

Might look good. Tough much too much effort.

> I would prefer to just have the filter text in bold.

Good idea, very good compromise.

**Comment by illfated** [comment]
What about using translucent pink/reddish pink or translucent orange as the warning color? Would look less offensive at the same time as highlighting something that needs attention.

**Comment by gerhardol** [comment]
Having separate colors or styles are too much in my opinion, I vote against it.

**Comment by illfated** [comment]
Fair enough, although translucent pink/reddish pink is already present in diff view and the color of the local branch tag in the commit list.

**Comment by RussKie** [comment]
I like the idea of translucent colours, especially if we already use it

**Comment by mstv** [comment]
I've updated the feature description with new faked screenshots with bold text and the colors from the diff view.

In an other recent review, it was requested to not use hard coded colors.
One could create a class `ControlColorer` that sets the `ForeColor` and the `BackColor` of a `Control` in dependency on a state.
Do you prefer a different approach or know a better name?

**Comment by illfated** [comment]
Color selection looks good to me.
No opinion on the names, sorry.

**Comment by RussKie** [comment]
I don't mind the colours. I presume once the filter is removed, the background is reset to the standard colour.

**Comment by RussKie** [comment]
> One could create a class `ControlColorer` that sets the `ForeColor` and the `BackColor` of a `Control` in dependency on a state.
> Do you prefer a different approach or know a better name?

I'd think we should have a "theme" or "style" class that contains all the colours we use.
