### ISSUE TITLE
Copy repository folder to clipboard

### ISSUE THREAD

**Issue by ignacioerrico** [gitextensions/gitextensions#6452]
## Feature description

There is currently no direct way to copy the path of the repository to the clipboard.
Two ways to do it are:
- Open File Explorer (`CTRL`+`Shift`+`O`) and copy the path in the address bar.
- Copy the full path of an arbitrary file in the File Tree, and remove the undesired part.

I suggest that the File Explorer icon on the toolbar be a `ToolStripSplitButton` (instead of a simple `ToolStripButton`) that also displays the option to copy the full path of the repository. That is, something like this:

![image](https://user-images.githubusercontent.com/3200214/55690796-5fe01c00-5996-11e9-9d89-deeacbff48ed.png)

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Ok for me

**Comment by RussKie** [comment]
Could you please describe the use case, and why the described options don't
work.

I do appreciate a click to open the working for in WE is an extra step, but
I am not convinced the proposal is acceptable in its curreny form.

It introduces a discoverability issue. It also adds an unusual pattern to
copy information that no other Windows apps do.

**Comment by ignacioerrico** [comment]
Thank you for your feedback, @RussKie. You made a good point about the discoverability issue that you mentioned. To be honest, considering it's such a small thing, I was hesitant to create the ticket. So let me elaborate.

I often need to copy the path of a repository to:
- `cd` to that directory in a command prompt (DOS or PowerShell) to run a command not related to git. In other words, I often need to open a DOS or PowerShell prompt in the directory of the repository, similarly to what happens when you click on the _Git bash_ icon.
- Feed it to another console or desktop application. One notable example is to open a solution in Visual Studio which is not listed under _Recent projects and solutions_. (Granted, I could copy the `.sln` file from the File Tree in GE, and that's what I normally do.)

The solution I typically resort to is to open File Explorer and copy the path from the address bar. No big deal, I know, but since I tend to it often, I started to feel the need for that option. :-)

**It's a small detail, but I would love to know if such a feature would be useful to others**.

**Comment by vbjay** [comment]
You do realize you can run any command in the console tab, right?

![image](https://user-images.githubusercontent.com/3629489/55721074-65f2ee80-59d0-11e9-8992-b9995701d856.png)

**Comment by ignacioerrico** [comment]
Yes, but the integrated prompt is a bash shell. (Which is great, but if I need to run a command in the `%PATH%`, I need to open a DOS terminal.)

**Comment by vbjay** [comment]
No, you don't.  Notice I ran winver in the console which is a windows program.  
![image](https://user-images.githubusercontent.com/3629489/55721374-35f81b00-59d1-11e9-8252-6f5e04cf38be.png)

**Comment by vbjay** [comment]
You can also run cmd.  
![image](https://user-images.githubusercontent.com/3629489/55721579-b585ea00-59d1-11e9-8a55-9b14257680a3.png)

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/55721676-ed8d2d00-59d1-11e9-93b6-6a76b9f7a48e.png)

**Comment by ignacioerrico** [comment]
Thanks for all the screenshots, @vbjay! I liked the idea of running `cmd` in the bash prompt. To be honest, I hadn't thought of that. And I overlooked the fact that it was possible to choose a shell for the Console tab.

I like that!

In light of that, my suggestion may not be really useful, so feel free to close the ticket.

**Comment by RussKie** [comment]
Thank you Jay.

**Comment by pmiossec** [comment]
>You do realize you can run any command in the console tab, right?

and
>In other words, I often need to open a DOS or PowerShell prompt in the directory of the repository, similarly to what happens when you click on the Git bash icon

Because it is not always convenient to run commands in a console tab, perhaps we could improve the situation and make the "Git bash" button a ToolStripSplitButton to be able to open a cmd or a powershell...

**Comment by RussKie** [comment]
That's a great idea @pmiossec.

We could add a split button to the toolbar that contains bash, cmd, ps shortcuts.
We could also uplift the Console tab to launch different sessions, similar to VSCode

![image](https://user-images.githubusercontent.com/4403806/55870263-863acd00-5bcb-11e9-96fd-9790663b84c6.png)
