### ISSUE TITLE
History not shown for a new file in a different branch

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#6458]
## Current behaviour
When trying to show the history of a file which has been added in a different branch than the current one, nothing is shown.

## Expected behaviour
The history is shown regardless of whether the file actually exists in the working directory.

## Steps to reproduce
1. Create a new branch
2. Create a file `new.txt`
3. Change the contents of the file in a few commits
4. Switch to a different branch
5. Open the history form for `new.txt`

## Did this work in previous version of GitExtensions
Yes, before commit 08737aa147bcc6e5917f370910ca64a4a47bb6a7. There, the full path is retrieved through `FormFileHistoryController.TryGetExactPath`. However, it returns `null` if the given file does not actually exist - which obviously fails for new files from a different branch.

## Environment

- Git Extensions 3.1.0
- Build 9ff970ca36007056992f90db1dcc0f46edcc5fd4 (the last one where it works)
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Is the grid filtering to only current branch?

**Comment by crypto-rsa** [comment]
No, the problem is that GE crashes at https://github.com/gitextensions/gitextensions/blob/14e881406bd69ed6cd279906b849ccb342443f5b/GitUI/CommandsDialogs/FormFileHistory.cs#L215

because `fileName` is `null` (because it is not in the working directory and the controller returns `null` in that case, as I stated above).
