### ISSUE TITLE
Being able to open a powershell or cmd console

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#6460]
## Feature description
Discussed in https://github.com/gitextensions/gitextensions/issues/6452#issuecomment-481248777

Transform the `Git bash` button in  a split button to be able to easily open a cmd, powershell console (and a custom one? #1393).

We could also uplift the Console tab to launch different sessions, similar to VSCode ( cf https://github.com/gitextensions/gitextensions/issues/6452#issuecomment-481626505 )

## Environment

- Git Extensions 3.1.0
- Build 84b65c3f6542f6adb817c308906522c66c611009
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3362.0
- DPI 192dpi (200% scaling)

**Comment by ignacioerrico** [comment]
I would like to have a stab at this one.

[This](https://en.wikipedia.org/wiki/File:PowerShell_Core_6.0_icon.png) would be a good icon for a PowerShell prompt, I suppose. How about for a DOS prompt?

**Comment by pmiossec** [comment]
>I would like to have a stab at this one.

Great!

Perhaps you could have a look at the icon sources we already used (See https://github.com/gitextensions/gitextensions/blob/master/GitUI/Resources/Icons/originals/_Icon%20Sources.txt )

And searching something like "terminal" or "dos"...
