### ISSUE TITLE
GitExtentions is VERY slow since v3.  Older versions were quite fast.

### ISSUE THREAD

**Issue by dachew** [gitextensions/gitextensions#6461]
GitEx is awesome, but v3 is VERY slow.  It takes forever to load the differences, doesn't show commit changes, etc.  I've tried this on 3 different machines.  Running 3.00.00.4433.

What can I do to speed this up?  Our project is also very large.  However, I can run `git status` and `git log` and `git diff` and the results are nearly instant.

**Comment by RussKie** [comment]
Please search existing issues before opening a new one. There are already several ongoing discussions regarding performance of v3 (e.g. https://github.com/gitextensions/gitextensions/search?q=is%3Aopen+sort%3Aupdated-desc+slow+is%3Aissue&type=Issues).

Please try a dev build https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

We also have an issue template for a reason. "The app is slow" isn't sufficiently detailed to provide you with any kind of help.
