### ISSUE TITLE
Display problem in Chinese.

### ISSUE THREAD

**Issue by SetoKaiba** [gitextensions/gitextensions#6463]
## Current behaviour

Fetch can't be displayed in Chinese. Because the fonts in Chinese is different. The rebase option text is very long.

## Expected behaviour

Fetch can be displayed.

## Steps to reproduce

Switch to Chinese and pull.

## Screenshots

![image](https://user-images.githubusercontent.com/159540/55927781-ddcb4e00-5c48-11e9-82cb-dfe86d8042d2.png)

## Did this work in previous version of GitExtensions

Not sure

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
I suggest the translated text is changed in transifex.

**Comment by RussKie** [comment]
All translations are done via Transifex, https://www.transifex.com/git-extensions/git-extensions/language/zh-Hans/

**Comment by SetoKaiba** [comment]
@RussKie Is this update included in 3.1RC1? The label is still two lines long.

**Comment by SetoKaiba** [comment]
I can't open the transifex page.

**Comment by RussKie** [comment]
> @RussKie Is this update included in 3.1RC1?

I don't know, the core team doesn't maintain translations, we don't speak all languages; translations are maintained by translators.


> I can't open the transifex page.

Try https://www.transifex.com/git-extensions/git-extensions/
I'm guessing you need to be logged in to see a specific language.

**Comment by RussKie** [comment]
We download and include translations when they reach 95% mark.
We will be downloading updates shortly for the 3.1 release.
