### ISSUE TITLE
FileStatusList: highlight the new name

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6465]
## Current behaviour

The path is displayed gray and the filename black.
For renamed files the new name is gray, too. Only the old is black which usually must be scrolled into view first.

## Expected behaviour

The new filename or both should be displayed in black.

## Steps to reproduce

select a commit with a moved file

### Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/55987027-ecddea80-5ca0-11e9-9bf4-34bb90c294a5.png)

## Did this work in previous version of GitExtensions

If yes, then long time ago in 3.x. N/A for 2.5x.

## Environment

- Git Extensions 3.1.0
- Build 827c746e82af33ba959512fba4bd69251e37a782
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Reasonable. The filename part is rendered separately and this is probably difficult to achieve (without weird spaces or overlapping).
