### ISSUE TITLE
When support the vs 2019?

### ISSUE THREAD

**Issue by jackywang24** [gitextensions/gitextensions#6473]
## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by vbjay** [comment]
Instead of creating issues, search first.
https://github.com/gitextensions/gitextensions/search?utf8=%E2%9C%93&q=vs+2019&type=Issues

**Comment by RussKie** [comment]
The new VSIX is available on the VS Marketplace
