### ISSUE TITLE
Search by author does not show all commits

### ISSUE THREAD

**Issue by d07RiV** [gitextensions/gitextensions#6478]
## Current behaviour

Select only Author in filters, type in my name, press Enter. It lists some of my commits, but not all.

## Expected behaviour

Expect to see all commits by myself.

## Steps to reproduce

See above. Not sure if it's possible to reproduce with a clean repository.

## Screenshots

This is a snippet from all commits:

![image](https://user-images.githubusercontent.com/3448203/56218749-28e0c900-606e-11e9-86b0-fc2c3db86a6d.png)

This is commits filtered by "kolosov":

![image](https://user-images.githubusercontent.com/3448203/56218809-4150e380-606e-11e9-9b75-66f13ca0f0bb.png)

## Did this work in previous version of GitExtensions

No idea.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The Git Command Log shows that the command is like:
´´´git -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b" --reflog --all --boundary --max-count=10 --regexp-ignore-case --grep="RussKie" --author="RussKie"  --´´´

As grep is set in addition to author, the author must exist in the commit message.

**Comment by gerhardol** [comment]
This is configurable, just make sure you only select author.

![image](https://user-images.githubusercontent.com/6248932/56245417-aa048400-609f-11e9-8a67-60a196b19d70.png)
