### ISSUE TITLE
using gitextensions with QtCreator

### ISSUE THREAD

**Issue by sonersetG** [gitextensions/gitextensions#6480]
Hi
I use QtCreator and it offers an option to set a tool to be used when visualising a repo
I would like to use gitextensions for this so added this command
`C:\Program Files (x86)\GitExtensions\GitExtensions.exe`
When I execute from QtCreator I get the dialog below and not the gui version.
I realise this is most likely to be a QtCreator problem but was wondering if you had an insight as to why this happens,

![image](https://user-images.githubusercontent.com/49715729/56280127-78240980-6101-11e9-9845-244c253a96fb.png)

**Comment by pmiossec** [comment]
Did you tried to add 'browse' as parameter to the command line? It should
work...

**Comment by RussKie** [comment]
Closing due to lack of follow up.
Will re-open if there is new information
