### ISSUE TITLE
Plugins - Jira hint: No response

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#6484]
## Current behaviour

Clicking Plugins-Jira gives no response or feedback.

## Expected behaviour

Nothing is to displayed, the plugin has no UI but either the menu item should be removed or some feedback be displayed.

## Steps to reproduce

Click the menu item

## Screenshots

![image](https://user-images.githubusercontent.com/6248932/56321928-059a4480-6168-11e9-9d6a-7a48b291967e.png)

## Did this work in previous version of GitExtensions
Do not believe so
Jira Commit Hint was activated in 3.0 (at least portable)

## Environment
- Git Extensions 3.1.0
- Build e84d9eb78074f3bf17517c2522ed1fe5ad486e39 (Dirty)
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I think the plugin public API must have a readonly property indicating whether the plugin has a UI, that would be used to determine whether to add a plugin to the menu list

**Comment by mast-eu** [comment]
> I think the plugin public API must have a readonly property indicating whether the plugin has a UI, that would be used to determine whether to add a plugin to the menu list

Yes. I was already thinking about adding such properties for all additional plugin entry points that will be implemented (#6495).
I didn't realize that there's a plugin without GUI, but at this point I would use the same mechanism here as well.

**Comment by gerhardol** [comment]
Jira Commit Hint plugin is removed in 4.0, see #9659 
This issue is therefore closed as not applicable, link from #9659
