### ISSUE TITLE
NBug: Server error

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#6486]
## Current behaviour
Got an NBug error when switching repo just after startup in a private build, cannot reproduce.
Copied the exception with the new Copy button, tried to post an issue with send&quit and got server error at GitHub with the following URL.

This issue is about the url used to create the issue seem to be malformed for this new functionality in 3.1.0. The triggering issue is less important.
NBug is still better in 3.1 and I have been able to use the reporting at least once in the dev process...

 https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fgitextensions%2Fgitextensions%2Fissues%2Fnew%3Ftitle%3D%255BNBug%255D%2520Objektreferensen%2520har%2520inte%2520angetts%2520till%2520en%2520instans%2520av%2520ett%2520ob...%26body%3D%253C%2521--%250A%2520%2520%2520%2520%253Awarning%253A%2520Review%2520existing%2520issues%2520to%2520see%2520whether%2520someone%2520else%2520has%2520already%2520reported%2520your%2520issue.%250A--%253E%250A%250A%2523%2523%2520Current%2520behaviour%250A%250A%253C%2521--%2520Be%2520as%2520specific%2520and%2520detailed%2520as%2520possible%2520to%2520help%2520us%2520identify%2520your%2520issue.%2520--%253E%250A%250A%250A%2523%2523%2520Expected%2520behaviour%250A%250A%250A%2523%2523%2520Steps%2520to%2520reproduce%250A%250A%253C%2521--%2520Take%2520some%2520time%2520to%2520try%2520and%2520reproduce%2520the%2520issue%252C%2520then%2520explain%2520how%2520to%2520do%2520so%2520here.%2520--%253E%250A%250A%250A%2523%2523%2520Error%2520Details%250D%250A%2560%2560%2560%250D%250ASystem.NullReferenceException%253A%2520Objektreferensen%2520har%2520inte%2520angetts%2520till%2520en%2520instans%2520av%2520ett%2520objekt.%250D%250A%2520%2520%2520vid%2520GitUI.CommitInfo.CommitInfo.%253C%253Ec__DisplayClass56_0.%253C%253CReloadCommitInfo%253Eb__3%253Ed.MoveNext%2528%2529%2520i%2520F%253A%255Cdev%255Cgc%255Cgitextensions%255CGitUI%255CCommitInfo%255CCommitInfo.cs%253Arad%2520308%250D%250A---%2520Slut%2520p%25C3%25A5%2520stacksp%25C3%25A5rningen%2520fr%25C3%25A5n%2520f%25C3%25B6reg%25C3%25A5ende%2520plats%2520d%25C3%25A4r%2520ett%2520undantag%2520utl%25C3%25B6stes%2520---%250D%250A%2520%2520%2520vid%2520System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%2528%2529%250D%250A%2520%2520%2520vid%2520System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification%2528Task%2520task%2529%250D%250A%2520%2520%2520vid%2520System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult%2528%2529%250D%250A%2520%2520%2520vid%2520GitUI.ThreadHelper.%253C%253Ec__DisplayClass13_0.%253C%253CFileAndForget%253Eb__0%253Ed.MoveNext%2528%2529%2520i%2520F%253A%255Cdev%255Cgc%255Cgitextensions%255CGitExtUtils%255CGitUI%255CThreadHelper.cs%253Arad%2520101%250D%250A%2560%2560%2560%250D%250A%250D%250A%250D%250A%2523%2523%2520Environment%250D%250A-%2520Git%2520Extensions%25203.1.0%250D%250A-%2520Build%25205e7bb3c2f5210d859308fd713465489a3b43f484%250D%250A-%2520Git%25202.21.0.windows.1%250D%250A-%2520Microsoft%2520Windows%2520NT%252010.0.17763.0%250D%250A-%2520.NET%2520Framework%25204.7.3324.0%250D%250A-%2520DPI%252096dpi%2520%2528no%2520scaling%2529%250D%250A%250D%250A

## Expected behaviour
Correct URL for GitHub.

## Steps to reproduce
No details.

## Error Details
```
System.NullReferenceException: Objektreferensen har inte angetts till en instans av ett objekt.
   vid GitUI.CommitInfo.CommitInfo.<>c__DisplayClass56_0.<<ReloadCommitInfo>b__3>d.MoveNext() i F:\dev\gc\gitextensions\GitUI\CommitInfo\CommitInfo.cs:rad 308
--- Slut på stackspårningen från föregående plats där ett undantag utlöstes ---
   vid System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   vid System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   vid System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   vid GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext() i F:\dev\gc\gitextensions\GitExtUtils\GitUI\ThreadHelper.cs:rad 101
```

## Environment
- Git Extensions 3.1.0
- Build 5e7bb3c2f5210d859308fd713465489a3b43f484
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I believe this is the correct URL, you are just not logged in.

I am logged in on my phone, by clicking the link I got the following:

**Comment by gerhardol** [comment]
> I believe this is the correct URL, you are just not logged in.

Correct. Any possibility to improve the user experience here, to get them log in?
Will GitHub have to make changes?

**Comment by RussKie** [comment]
I can't see how, but suggestions are welcome.

If a user doesn't have a GH account - there is nothing we could do.
If a user has a GH account but not logged in, the user must to log in via
the normal GH flow. I don't see any need for us to build a login mechanism.

**Comment by RussKie** [comment]
![Screenshot_20190419-190845](https://user-images.githubusercontent.com/4403806/56418174-b3e7dc00-6285-11e9-989d-b50f48707424.png)

**Comment by mstv** [comment]
We should mention that one must be logged in before the new issue can be created.
This message should contain the link https://github.com/login.

**Comment by RussKie** [comment]
Where do you propose the message to be displayed?

NBug project has its own localisation. If we want to modify any strings in the NBug project we will need to set up a new localisation project in Transifex, get translators etc... 
It is a significant undertaking, we currently don't have manpower to do this.

**Comment by mstv** [comment]
I wasn't aware that we cannot extend the dialog easily.
It *is* a GH issue. They shouldn't just display "500 Ooops" but redirect to the login form.
I would use GH's contact form to submit a support request. I would include a sample URL for gitextensions. Any concerns? Should this rather be done by anybody with a pro login (Jay, Sam)?

**Comment by RussKie** [comment]
What was the error you got? 
When I tested while developing the feature I was directed to the logon page, then to the issue submission page...

**Comment by RussKie** [comment]
Just tested on a phone in a incognito tab - got HTTP500. 
Perhaps something changed recently....

I'm currently away, if you could submit a support ticket - it would be great.

I've used the GH API to submit tickets, the url is encoded, the url length is within reasons....

**Comment by mstv** [comment]
Ticket ID: 139661

**Comment by gerhardol** [comment]
@mstv 
I cannot find the ticket.
For me it seems to work now anyway, closing.
