### ISSUE TITLE
Test: GitModule executable should be set with test accessor

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#6487]
## Current behaviour

GitModule has an "executable" argument, that only is used in tests for mocking.
The argument does not make sense for normal modules (see #6373 for a rejected PR with some other optimisations). However, the argument is used incorrectly in test for the submodules provider.

https://github.com/gitextensions/gitextensions/blob/master/UnitTests/CommonTestUtils/GitModuleTestHelper.cs#L138

The git executable has the working directory of the superproject, so it executes in wrong directory.
(Current tests does not use this but updated tests in #6445 fails due to this).

## Expected behaviour
The executable in the submodule tests should not be overridden. (Separate PR will come.)

However, expose the argument makes no sense for the normal usage, this should be set in a test accessor instead.

## Steps to reproduce
code

## Did this work in previous version of GitExtensions
executable mocking added in 3.0, submodule provider in 3.1

## Environment
- Git Extensions 3.1.0
- Build 5e7bb3c2f5210d859308fd713465489a3b43f484
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Makes sense 👍
