### ISSUE TITLE
The merge doesn't work after the last update

### ISSUE THREAD

**Issue by svetyx** [gitextensions/gitextensions#6489]
## Current behaviour

I have Master and Branch with the conflict in the File1.cs. After I try to merge them I receive the error

## Screenshots

![image](https://user-images.githubusercontent.com/24451945/56425982-21642e80-62bf-11e9-92e2-4d36150590ef.png)

## Environment

- GitExtensions version: 3.0.2.5232
- GIT version: git version 2.21.0.windows.1
- OS version: Microsoft Windows 10 Pro 10.0.17763 Build 17763
- .NET version: 4.7.03190

**Comment by mstv** [comment]
@svetyx, could you fill in the "Steps to reproduce" and "Environment", please?
Note the comment in the "Environment section" that this information can be copied from the About dialog using the button ![copy button](https://user-images.githubusercontent.com/36601201/56426128-5cfafa80-62b7-11e9-9e4d-dcf2b79c4067.png).

Unfortunately, nobody is informed when tags are added, @gerhardol.

**Comment by gerhardol** [comment]
KDiff was previously bundled with GE2, removed in 2.51.02 or so.
Please set the mergetool in settings

**Comment by RussKie** [comment]
What is the problems? Is the error message not sufficiently clear?

**Comment by illfated** [comment]
Thank you for pointing that out. I was thinking the same a few hours ago, but I didn't feel confident.
