### ISSUE TITLE
Left panel: indicate whether branch has been merged

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6494]
## Feature description

![left panel](https://user-images.githubusercontent.com/36601201/56467568-e7ab3900-6420-11e9-8dfa-1306ad84b23a.png)

E.g. a different branch icon could be displayed if the branch has been merged.
It could be flipped vertical and should have a different color.
GH uses the icon ![merged](https://user-images.githubusercontent.com/36601201/56466466-d78c5d00-6412-11e9-9b9c-d4effebf8408.png). Its style does not match GE's and I do not like the color very much.

Thoughts?

## Environment

- GitExtensions version: 3.x

**Comment by RussKie** [comment]
I like the idea :+1:
We could flip the current icon...

**Comment by mast-eu** [comment]
Not sure if just flipping the current icon is clear enough. But that's a detail that can be worked out.
In any case I like the idea to _somehow_ indicate whether a branch has been merged.

**Comment by gerhardol** [comment]
Are you interested in seeing if a branch is merged with the currently checked out branch or "master"? The latter is similar to gh but will require configuration.

**Comment by mast-eu** [comment]
At work I have projects where the main branch is not called "master". Thus, I see more value in visualizing whether a feature branch is merged into the _current branch_.

**Comment by mstv** [comment]
For the selected commit, this information is available in the CommitInfo in "Contained in branches" since this list is sorted with the currently checked out branch and master first.

I am afraid, we would need to run too many git commands to retrieve this information for all branches in the left panel.
Do you still feel the need for this feature?
How to retrieve this info without too much load?

**Comment by gerhardol** [comment]
As the information is available for the selected commit, the info could be related to the current commit: Unknown/merged/not-merged
Or for current head, if calculated, as that usually selected once.
The icons need to be refreshed when changing commit.

**Comment by ilabutin** [comment]
This feature would be very welcome.
Wouldn't this git command help?
```
git branch -a -v --no-abbrev --no-merged
```

It prints branch names (including remote ones if information about them is required) together with their heads' commit IDs.

**Comment by mstv** [comment]
Thank you, @ilabutin. So the state to display is going to be "contained in the current commit" (as @gerhardol proposed).
The command `git branch '--format=%(refname)' -a --no-merged <commit>` seems to return the required list.

**Comment by RussKie** [comment]
PRs are welcome
