### ISSUE TITLE
Unable to build from cli

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#6497]
## Current behaviour

I haven't run build scripts for some time, building the solution from a VS.
It appears after upgrading the VS to 15.8 or 15.9 it is no longer possible to build the solution from the cli.

![image](https://user-images.githubusercontent.com/4403806/56500645-0576bc00-654f-11e9-9f04-1a46eea01b1e.png)

## Expected behaviour

The solution can be build via our build scripts 

## Environment

- MSBuild 15.9.21+g9802d43bc3 for .NET Framework
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0

**Comment by gerhardol** [comment]
I do not see this problem, I can build with VS2017/VS2019, as long as I have a patch for #6500 (not yet ready)
The doc I saw related to this was for .NET Core.
No harm in preparing.

**Comment by RussKie** [comment]
I have both VS2017 and VS2019 as well as several flavours of .NET and .NET Core installed. I haven't fully migrated to VS2019 and still primarily use VS2017.
For one reason or another it just wouldn't build from cli without the "RuntimeIdentifier" node. 🤷‍♂️
