### ISSUE TITLE
Pull dialog stopped "remembering" previous user selection

### ISSUE THREAD

**Issue by GStoynev** [gitextensions/gitextensions#6503]
## Replicate:
1. In the UI, ensure "Open Pull dialog ..." is used (either "set as default" ot clicked)
2. Choose "Merge remote branch into current" option. 
3. Check "Auto stash" checkbox
4. Pull
5. Once the dialog is closed, repeat step 1.

## Current behaviour
When re-opened, the dialog doesn't "remember" that I chose the option and the checkbox in 2. and 3. above

## Expected behaviour
When reopened, the dialog's initial state will match the selections from the last time I used it.

This used to be the default behavior for as long as I remember using GitExtensions - since 2013 or so... I think it got broken in the 3.0 release.

## Environment
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by Shauren** [comment]
I can confirm this behavior when I tried to upgrade from 2.51.05 to 3.1 while keeping my settings (IsPortable = false)
For me this is a major upgrade-breaking issue

**Comment by RussKie** [comment]
Could you please try the fix https://ci.appveyor.com/api/buildjobs/t962yn1m4uaf2yf2/artifacts/combined.3.1.1.585-unsigned.zip

**Comment by Shauren** [comment]
This works just like on 2.51, perfect
