### ISSUE TITLE
"Show Current Branch Only" does not work

### ISSUE THREAD

**Issue by BaronZemo** [gitextensions/gitextensions#6504]
## Current behaviour
Selecting View -> Show Current Branch Only from the menu bar does not seem to change the view of the branches at all.

## Expected behaviour
It is expected that other branches would be filtered from the view, only showing the branch I am on.

## Steps to reproduce
Select View -> Show Current Branch Only from the menu bar while viewing a repository.

## Screenshots
I 

## Did this work in previous version of GitExtensions

This worked previously in Version 2.49.03

## Environment

    Git Extensions 3.0.2.5232
    Build 23b6f51
    Git 2.19.1.windows.1
    Microsoft Windows NT 6.1.7601 Service Pack 1
    .NET Framework 4.7.3324.0
    DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
That works for me with:

```
- Git Extensions 3.1.0
- Build bdff0b23286e4a681745db80f4b9bbdd46389aba
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)
```

Could you test with the `master` build artifact?

**Comment by RussKie** [comment]
Are you sure you don't have any other options turned on like "Show reflogs"
Please post screenshots

**Comment by RussKie** [comment]
Closing due to lack of follow up.
Will re-open if there is more information.

**Comment by BaronZemo** [comment]
> 
> 
> Are you sure you don't have any other options turned on like "Show reflogs"
> Please post screenshots

Yes, this is exactly what was going on. When I turned "Show reflogs" off then it worked as expected.
