### ISSUE TITLE
Jira Commit Hint returns 401

### ISSUE THREAD

**Issue by coxymla** [gitextensions/gitextensions#6506]
## Current behaviour

I'm trying to configure Jira Commit Hint plugin.
I have entered my Atlassian instance URL, username and password correctly.

![image](https://user-images.githubusercontent.com/691623/56625798-8ded7d80-6671-11e9-8245-de788efe17e5.png)

Clicking the Preview button shows 401 Unauthorised.
![image](https://user-images.githubusercontent.com/691623/56625850-bbd2c200-6671-11e9-856a-a8e2f56d08ec.png)

Clicking the query helper doesn't quite work either, it opens a URL of `https://empired2.atlassian.net/issues/?jql=` in the browser instead of something like `https://empired2.atlassian.net/issues/?jql=assignee%20%3D%20currentUser()%20and%20resolution%20is%20EMPTY%20ORDER%20BY%20updatedDate%20DESC`

## Expected behaviour

Should extract the Key and Summary fields of the most recent assigned Jira issue.

## Steps to reproduce

As above.

## Screenshots
As above.

## Did this work in previous version of GitExtensions
Have only just installed GitExtensions.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.17.1.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Pekade try latest master, there are changes to authorization there. 
If that does not work, can you debug the problem?

**Comment by SamLino** [comment]
I had this error. Solved it like this:
1. I went to [https://id.atlassian.com/manage/api-tokens](https://id.atlassian.com/manage/api-tokens)
2. Generated a token
3. Inserted the token in the password place

Possibly the field name could be changed or documentation.

**Comment by RussKie** [comment]
Would it be clearer if "Jira password" was renamed to "Jira password/token"?

**Comment by coxymla** [comment]
> 
> 
> I had this error. Solved it like this:
> 
>     1. I went to https://id.atlassian.com/manage/api-tokens
> 
>     2. Generated a token
> 
>     3. Inserted the token in the password place
> 
> 
> Possibly the field name could be changed or documentation.

Thanks Sam, that did the trick.

**Comment by pmiossec** [comment]
>1. I went to https://id.atlassian.com/manage/api-tokens

I think that the best solution (in addition to renaming the password field) would be to add a link named "generate a token" next to the password field that open this web page.

Could one of you do this PR?
