### ISSUE TITLE
Checkout branch: Badly formatted message

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#6507]
## Current behaviour

Checkout branch: Badly formatted message containing a not desired line return.

## Expected behaviour

no line return

## Steps to reproduce

* Checkout a remote branch and choose "reset local branch"
* The badly formatted message appears

## Screenshots

![image](https://user-images.githubusercontent.com/460196/56643384-d9a42500-6679-11e9-91aa-f63f7a72cdfb.png)

## Did this work in previous version of GitExtensions

don't know

## Environment

- Git Extensions 3.1.0
- Build e738f740a1af363f03d4ea2b89049be5b5cf9b94
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3394.0
- DPI 192dpi (200% scaling)

**Comment by mast-eu** [comment]
Does this depend on the current DPI setting?

**Comment by pmiossec** [comment]
Not exactly. That's due to a line return put in the resource https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/FormCheckoutBranch.cs#L36
but indeed, that should be well displayed only on specific dpi setting.

I have to make the PR but created the issue just to keep the screenshot 😉

**Comment by vbjay** [comment]
What's wrong with it?  It makes it easy to read.

**Comment by pmiossec** [comment]
>What's wrong with it? 

I'm talking about the line return after "location" in the middle of the sentence.
I think that should be removed because that's strange and so we don't understand why the sentence continue in the next line.

>It makes it easy to read.

If we want really something easy to read, we should cut in 2 sentences. Something like (not fluent in english):

>You are going to reset the “{0}” branch to a new location.
>That will discard ALL the commited changes since the {1} revision
>
>Are you sure?

**Comment by mast-eu** [comment]
The hard-coded line break after "location" needs to be removed in any case. Depending on the length of the branch name, you can get a badly formatted message, like in the screenshot.

Further changes to the displayed message are possible, but not strictly necessary in my opinion.
