### ISSUE TITLE
Unhandled RefsWarningException "warning: ignoring broken ref"

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6516]
## Current behaviour

Occasionally, some of my GE repo's refs are overwritten with zeroes. (It resides on an external, self-encrypting SSD from a leading manufacturer, whose standby / hibernation handling seems to be unstable.)
Then `git for-each-ref --sort=-committerdate --sort=-taggerdate --format="%(refname)" refs/` prints "warning: ignoring broken ref ..." (among correct refs) - as in #6442 for remotes, though for a broken local ref this time.

When GE opens this repo, it does not select any commit - without any error message (see screenshot) although `git rev-parse HEAD` returns an error.

When a commit is selected, the `RefsWarningException`, which was added in the PR #6451, is thrown but not handled in a sub-function of `ReloadCommitInfo()`, which contains an almost one-to-one copy of the member function `LoadSortedRefsAsync()`. The latter does handle the exception, the copy does not. When I created #6451, I did not realize that `LoadSortedRefsAsync()` exists twice. Edit: I couldn't because it was duplicated in a parallel branch.

When the exception is ignored by closing the window, the Git warning is displayed in a MessageBox.

## Expected behaviour

Git command errors are not silently ignored but handled correctly.
Git warnings and errors are displayed clearly, not only as an unhandled exception.
(see https://github.com/gitextensions/gitextensions/pull/6513#issuecomment-487369960, too)

Refactoring of CommitInfo.cs to be finished (DRY).

## Steps to reproduce

- overwrite the file `.git\refs\heads\master` with zeroes (41 bytes)
- re-open the repo -> no commit selected
- select a commit -> RefsWarningException
- close the exception dialog with `Alt+F4` -> MessageBox

## Screenshots

![no commit selected](https://user-images.githubusercontent.com/36601201/56865648-b9090180-69d0-11e9-8072-2ca85fdb0537.png)
![RefsWarningException](https://user-images.githubusercontent.com/36601201/56866161-83671700-69d6-11e9-9ec2-573148b7496a.png)
![broken ref warning](https://user-images.githubusercontent.com/36601201/56866176-9548ba00-69d6-11e9-8af1-011a8d607220.png)

## Did this work in previous version of GitExtensions

at least no unhandled exception in 3.00.00.4433

## Environment

- Git Extensions 3.1.0
- Build 2125c1beef18fd6eac66f368b026e921243067dd
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

## Diagnostics

stack trace
```
   at GitCommands.GitModule.GetSortedRefs() in F:\Build\gitextensions\GitCommands\Git\GitModule.cs:line 767
   at GitUI.CommitInfo.CommitInfo.<>c__DisplayClass56_0.<<ReloadCommitInfo>g__LoadSortedRefsAsync|5>d.MoveNext() in F:\Build\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 365
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at GitUI.CommitInfo.CommitInfo.<>c__DisplayClass56_0.<<ReloadCommitInfo>b__3>d.MoveNext() in F:\Build\gitextensions\GitUI\CommitInfo\CommitInfo.cs:line 295
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext() in F:\Build\gitextensions\GitExtUtils\GitUI\ThreadHelper.cs:line 101
```

**Comment by RussKie** [comment]
Would you like to try to fix it?

**Comment by mstv** [comment]
Yes. Though the generic sub-issues will take some time, including the duplicated async functions with and without the `cancellationToken`.

Do you want a bugfix for 3.1.0 which just catches the exception?

**Comment by gerhardol** [comment]
> Do you want a bugfix for 3.1.0 which just catches the exception?

Is it important enough for 3.1.0?
It is probably good to ship 3.1.0 first so normal merges are not blocked.

**Comment by mstv** [comment]
I think, this unhandled exception is a really minor issue, i.e. there's no need to catch it in 3.1.0 IMO.
I was not sure about Igor's question "Would you like to try to fix it?". That's why I tried to express that I could implement a quick bugfix "just handling the exception" and apply the more generic approach in a later release.

(BTW: Should I use the `@user` notation more often? Currently, I use it only if I request a direct answer.)

**Comment by RussKie** [comment]
> Do you want a bugfix for 3.1.0 which just catches the exception?

Let's start with a bugfix, especially if it's quick.



> (BTW: Should I use the `@user` notation more often? Currently, I use it only if I request a direct answer.)

Up to you. It is typically easier than trying to write people's names (and getting them wrong :smile:)

**Comment by gerhardol** [comment]
> BTW: Should I use the @user notation more often? Currently, I use it only if I request a direct answer.)

A mention can be used to sort incoming emails so it can be easier to reach someone with many emails like maintainers.

**Comment by RussKie** [comment]
@mstv is this fixed in #6519?

**Comment by RussKie** [comment]
Do we want this to go out in 3.1?

**Comment by mstv** [comment]
Yes, the essential bug has been fixed. At least, the regarding duplicated function has been removed.
I think it should go out in 3.1.

I will open a new generic issue for:
> Git command errors are not silently ignored but handled correctly.
Git warnings and errors are displayed clearly, not only as an unhandled exception.

**Comment by RussKie** [comment]
Could you please send a matching PR to release/3.1 branch please
