### ISSUE TITLE
Failing to respond  when create branch 

### ISSUE THREAD

**Issue by zhouhaibing** [gitextensions/gitextensions#6518]
when i create new branch, the following is show:
![image](https://user-images.githubusercontent.com/13377161/56954820-62d3c400-6b72-11e9-96af-1f1cacd7c25c.png)

my gitextensions cofig is :
![image](https://user-images.githubusercontent.com/13377161/56954932-a62e3280-6b72-11e9-8026-becf10dd5df7.png)
please help me, thank you very much

**Comment by mast-eu** [comment]
How did you enter the branch name "hello_world" if the whole form is inactive?

**Comment by mast-eu** [comment]
Please use our [issue template for bugs](https://github.com/gitextensions/gitextensions/issues/new?template=bug_report.md). It helps us to collect all the necessary information, like reproduction steps (i.e. what exactly did you do).

Please note there's a copy button in the about dialog for copying your environment:
![image](https://user-images.githubusercontent.com/6248932/55723803-3660d800-5a0a-11e9-83ec-8be7262220ba.png)

**Comment by zhouhaibing** [comment]
> How did you enter the branch name "hello_world" if the whole form is inactive?
the form is inactive after i enter name"hello_world" and click button "Create branch".

**Comment by zhouhaibing** [comment]
Today i use myself computer, the environment config is :
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.14393.0
- .NET Framework 4.7.3062.0
- DPI 96dpi (no scaling)

But when i test the "Create branch" using the same way, it is ok. Don't appear any problem. 
The only difference in gitextension config between myself computer and my work computer is .NET Framework version.

**Comment by mast-eu** [comment]
> But when i test the "Create branch" using the same way, it is ok. Don't appear any problem.

Is the problem reliably reproducible on your work PC?
Does it happen only with a specific repository?

**Comment by zhouhaibing** [comment]
Thank you for your response. But it happen many repository. Yesterday i try it in many repositories, exception is still occur.

**Comment by illfated** [comment]
> The only difference in gitextension config between myself computer and my work computer is .NET Framework version.

Maybe it could be useful to know what the .NET Framework version is on your work computer?

**Comment by mast-eu** [comment]
We are working on a new release, currently available as release candidate here: [v3.1-RC1](https://github.com/gitextensions/gitextensions/releases/tag/v3.1-RC1).

Could you please try this version and verify if your problem still occurs?

**Comment by RussKie** [comment]
We need more info

- is it happening for a specific repo or all repos?
- is it happening for only this dialog or all dialogs (e.g. "Create tag",
"Delete branch" etc)?
- is the app hanging immediately after being opened / after a repo opened /
etc?

Please record and upload an animation of the issue using screen2gif or
similar.

**Comment by zhouhaibing** [comment]
It is ok when I restart my computer. I think it is my computer problem, thanks.

**Comment by zhouhaibing** [comment]
today the problem comes back. now i answer your question:
1. it happen for all repos.Because i test two repos.
2. it happen for only this dialog named "Create branch". I have tested "Create tag" dialog is ok.
when i have filled the branch name, then click the "Create branch" button, the problem occur, the dialog is hanging.
this is info i can provide, if you need more details, please tell me, thank you very much.

**Comment by RussKie** [comment]
Is repository on your local drive?
Is it working if you do it from the command line?
Can it be something on your work PC that is blocking it (e.g. a corporate policy or an antivirus)?

**Comment by zhouhaibing** [comment]
1. yes , on my local drive.
2. command line is ok.
yesterday the problem don't occur.

**Comment by RussKie** [comment]
If the issue is intermittent then I'd say it would be unlikely the problem is in GE, there is something else at play.

**Comment by zhouhaibing** [comment]
maybe some others influence. Could you tell me how to find the debug log in GE? i want to find why the dialog hanging accidentally

**Comment by RussKie** [comment]
_Tools > Git command log F12_

**Comment by zhouhaibing** [comment]
![image](https://user-images.githubusercontent.com/13377161/57456050-2bb29080-729f-11e9-8248-a50e2188177f.png)
