### ISSUE TITLE
git-status runs also when GE is minimized

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#6521]
## Current behaviour
The commit count uses git-status and is triggered periodically:
* At changes, at least 3s in between (adjusted from the time needed to run the status)
* Every 5th minute if no changes

The command runs with --no-optional-locks and should not affect other commands directly. 
In 2.x and 3.0 the ignore directories are parsed. However, this check delayed updates and required quite some resources (both runtime and memory) and has been removed in 3.x.

However, if you are building and GE is minimized, git-status still runs periodically as well as periodic runs (it seems like the Symantec virus is triggered by git-status and constantly runs with 25% CPU for me).
I often have at least 4 GE instances running at the same time (used to be more, but the left panel submodule in 3.1 decreases a couple of instances).

This is not a major problem, but can be approved.

## Expected behaviour

If GE is minimized, it is not really necessary to update the commit count. It is nice if it is updated quickly after restoring the application, but it should not affect performance.

It is to my knowledge not simple to find if an application is minimized or hidden. It is simpl

A simple solution is to deactivate the commit count when FormBrowse is inactivated. (GitStatusMonitor has an "Active" state, probably a "Delayed" state is needed in this situation to limit git-status runs when switching active apps).

## Steps to reproduce

Start a few GE instances and check the command log.

## Screenshots

n/a

## Did this work in previous version of GitExtensions

no

## Environment

- Git Extensions 3.1.0
- Build 947078bec2cfb27fa7a6a3f04897928713d89a29 (Dirty)
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

## Diagnostics

n/a

**Comment by mstv** [comment]
On the other hand, git-status should not be suppressed anymore during active FormCommit.
Currently, the status overlay in GE's taskbar icon is not updated (which has confused me several times).
(Note: The status overlay is not displayed if the taskbar is configured to show small icons.)

I agree that GE should be *nice* while not the active application. I think "application minimized" would be not be enough - at least for me: I nearly never minimize GE, I just switch to other applications.

I do not expect that GE updates its status while in the background. Though it might be a valid use case for other users.

> It is to my knowledge not simple to find if an application is minimized or hidden.

Is this really a problem with WinForms?

**Comment by gerhardol** [comment]
> On the other hand, git-status should not be suppressed anymore during active FormCommit.
Currently, the status overlay in GE's taskbar icon is not updated (which has confused me several times).

Should be fixed, the button should reflect that it is not updated

> I think "application minimized" would be not be enough - at least for me: I nearly never minimize GE, I just switch to other applications.

This is a discussion. Should GE update when not focused?
(This probably means that status overlay should be removed.)

> Is this really a problem with WinForms?

Just what I found when googling, there may sure be a way.
But I would prefer to avoid updating if GE is not visible, that at least seem to be hard.

**Comment by RussKie** [comment]
> It is to my knowledge not simple to find if an application is minimized or hidden

You can safely assume if the main form is minimised - the app is too.
There are two possible main forms:
- `FormBrowse`, if the app was started normally
- `FormCommit`, if the commit dialog was invoked directly (e.g. via the shell extensions).

There's also `Application.OpenForms` property which may be of some help.

**Comment by RussKie** [comment]
> But I would prefer to avoid updating if GE is not visible, that at least seem to be hard.

Why?

```
interface IBackgroundUpdateIndicator
{
    bool Enabled { get; }
}

class BackgroundUpdateIndicator : IBackgroundUpdateIndicator
{
    public bool Enabled {
       get { return ApplicationsOpenForms[0].WindowsState != Minimised; }
    }
}

class GitStatusRunner
{
    private readonly IBackgroundUpdateIndicator _backgroundUpdateIndicator;
    public GitStatusRunner(IBackgroundUpdateIndicator IBackgroundUpdateIndicator) { ... }

    public void UpdateStatus()
    {
       if (!_backgroundUpdateIndicator.Enabled) return;

       // perform the update
    }
}
```

**Comment by mstv** [comment]
> But I would prefer to avoid updating if GE is **not visible**, that at least seem to be hard.

I guess, Gerhard means "either covered by other windows or minimized". That would be really hard to figure out and to detect changes.

> Should GE update when not focused?
This probably means that status overlay should be removed.

That would be a cheap solution. But I would miss the quick overview of the GE instances in the taskbar.

**Comment by RussKie** [comment]
There's also an API to detect when the app is no longer active/becomes
active.

**Comment by RussKie** [comment]
> Should GE update when not focused?
> (This probably means that status overlay should be removed.)

I like the coloured dot in the taskbar, it gives visual clues to the state of a repo.
And I'd be sad if it was gone...

Besides, a user may have GE running on one screen (e.g. `FormCommit` window opened), whilst cutting code in an IDE on another screen. I think it would be confusing if the user changed files, but GE didn't indicate in some way.

After using Fork for some months I quite appreciate auto refresh of file lists / state of the repo.

**Comment by gerhardol** [comment]
git-status takes over 700ms for some repos I work with. Longer times are not really worse, in a busy CPU the time is doubled and git-status is scheduled to run at most three times the excution status, so git-status should never use more than 25% of a core. With 4 GE instances running, that is one core. Assuming that 4 cores are available, that is 25% cpu load, which I may want to use when compiling.

My other concern is that this seem to trigger the Symantec virus to run constantly. Not confirmed.

I prefer small icons still, to fit the 30+ applications I often run so I do not have the benefit of the notification dot.
If this is changed, the visual status of the commit count etc must visualise this. Maybe it is enough for me to not update only if minimized (but it still affects the notification dot).

Of course, this can be added to settings, but I would like to have a better motivation to add another setting.

Will run with this myself for some time and come back.

**Comment by RussKie** [comment]
> git-status takes over 700ms for some repos I work with.

Is there something special about these repos (e.g. size, number of commits, number of subs, etc)?

**Comment by gerhardol** [comment]
Really off topic, there are many setups where git-status requires more time

>> git-status takes over 700ms for some repos I work with.

> Is there something special about these repos (e.g. size, number of commits, number of subs, etc)?

Nothing extreme. 800MB (uses LFS, some frequently updated large .xml files inflates the size), 2000 commits, 15 subrepos (among the fewer I work with).

**Comment by mstv** [comment]
To sum it up, we might turn the AppSetting "Use File System Watcher ..." into a selection:
- off
- always
- only while GE is the active application

(In this context, "periodic" is a little bit misleading because it is rather a forced break after the recent update. And every 5 minutes is too long for me to feel periodic. What's the benefit of this slow refresh?)

As a general rule, the update of the commit count shall always be triggered on event, i.e. on Git operations triggered by GE and on GE activation perhaps unless the File System Watcher is active *always*.
This shall *not* be paused by an open FormCommit anymore (because FormCommit does not neccessarily cover FormBrowse and the coloured dot in the taskbar needs to be updated).

Although, I wonder why you experience these performance issues at all. Doesn't the File System Watcher ignore git-ignored files?
If it ignores them, the update of the commit count should not be triggered by the build artefacts.
Then the new third option might be superfluous again.

Personally, I don't use the File System Watcher because it is OK for me to activate GE in order to update its state.

> I prefer small icons still, to fit the 30+ applications I often run so I do not have the benefit of the notification dot.

That's how it looks on my laptop, too. At work, I control an additional PC via RDP for building large projects. There run less applications so I can utilise the coloured dot in the task bar for a few repos.

**Comment by gerhardol** [comment]
This issue is raised to limit when commit-count handling is running.

Some off-topic to how it is running.

File System Watcher in Settings is only used to set the following:
![image](https://user-images.githubusercontent.com/6248932/57179724-ffeb7100-6e80-11e9-869a-4a74d6986ffe.png)

This monitors changes to yje index and refs and is separate from git-status. Low OH, it could be merged with git-status but not much gain.

--
git-status is triggered by a similar FileSystemWatcher at changes. To not run continuously, it is throttled to be started at most every 3rd second or 3 times the time for the command. New updates should be detected quickly and not take too much background load.

There is a fallback to run every 5 min too, in the case updates are missed (FileSystemWatcher could throw away notifications). This is not important now, was more when ignored files were detected. Could maybe be removed.

Before 2.51.03 (or so), git-status for commit-count and git-status for FormCommit were competing so commit-count had to be suspended, but commit-count now uses --no-optional-locks. 

Before 3.0 final (November or so), commit-count also skipped updates to ignored files. This handling had some problems:
 * The list with all individual ignored files could require GB of memory
 * It takes resources to list the ignored files
   * In 2.50 (will not check when in 2.51 this was changed) a separate command ran to get the list so extra resources was needed
   * In 3.0 before final git-status was used to get all ignored files. This delayed the commit-count update and required CPU at a critical stage

Ignored files handling could be reintroduced with some changes:
 * Run on the first time limited update so first update is quick or run separate as in 2.50. This part is OK.
 * Store ignored directories instead of files (--ignored=matching, since Git 2.16). This will still potentially use memory and be incomplete like new directories added, files in ignored directories etc. The igored file check will require more CPU than the dictionary lookup too.

**Comment by mstv** [comment]
Thank you for the explanation of the details and the history. There might be room for optimization.

> The list with all individual ignored files could require GB of memory

Imagine the following use case: check out a new worktree or clone a repo then build the project
Then a list of ignored *files* cannot have a benefit because it is empty.
A refresh of this list after a "git clean -xdf" would return an empty list, too.

I understand that it is less effort and brings in less dependecies if Git commands are used.
But for performance reasons, we could parse the .gitignore files ourselves.
(Other means to ignore files do not really matter IMO because build artefacts should be ignored for all users of the repo using the .gitignore files.)

For the first git-status call, we don't need info about ignored files. It is only needed to filter out changes reported by the File System Watcher. And this info needs to be updated if and only if the File System Watcher reports changes to a .gitignore file.

**Comment by RussKie** [comment]
This information would be good to put in pur wiki.
May I ask you to do that?

**Comment by gerhardol** [comment]
Submitted a PR with suppressing the minimized run, not the other functionality discussed here.
(I am looking at other functionality improvements related to the status monitoring and may want other changes, but this is stand alone.)

**Comment by gerhardol** [comment]
Implemented
