### ISSUE TITLE
Generic handling of Git exit codes, errors and warnings

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6527]
## Current behaviour

The exit code of Git as well as errors and warnings printed to the console by Git are not checked by every GE function.

## Expected behaviour

Git command errors are not silently ignored but handled correctly.
Git warnings and errors are displayed clearly, not only as an unhandled exception.

`GitCommand` shall check the Git exit code and throw a `GitFailException` unless the calling function indicates that it will handle the exit code itself. The `Exception.Message` shall contain all Git error messages ("error: ...", "fatal: ...") and all Git warning messages ("warning: ...").

A `GitErrorException` shall be thrown with all Git error and warning messages as the `Exception.Message`. These exceptions shall be caught by the calling function or form if applicable and as a fallback by `GitModuleForm`/`GitModuleControl`, which shall display the error message in a MessageBox.

`GitCommand` shall check for Git warning messages and display them in a MessageBox unless the calling function indicates that it will handle them itself.
Though I am not sure whether a MessageBox is really feasible in async and background tasks. If not, a `GitWarningException` should be thrown with all Git warning messages as the `Exception.Message`. The drawback of this exception would be that all functions which don't handle the warnings themselves would be canceled.

Git errors and warnings shall be logged in the `GitCommandLog`.

## Environment

- Git Extensions 3.1.0
- Build 3d5da22221203dbe14bdb53ff779799c1d8c5f09
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.2117.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Any thoughts on how this would look like?

**Comment by mstv** [comment]
With the display of git errors, #7607 wouldn't have failed silently.
After a crash of my PC, `Reset all changes` failed silently; but at least `Reset file or directory changes` displayed the good hint below.
I'd prefer a MessageBox with the buttons `Ignore` and `Cancel`. On `Cancel`, the `GitException` shall be (re)thrown.
![grafik](https://user-images.githubusercontent.com/36601201/72060505-665c4500-32d4-11ea-9377-3db9c94ed1ec.png)

**Comment by gerhardol** [comment]
A little more info in #8735
