### ISSUE TITLE
Shortcuts are not displayed on menuitems

### ISSUE THREAD

**Issue by fabvit** [gitextensions/gitextensions#6540]
## Current behaviour

Only some shortcut are displayed after clicking on menu

## Expected behaviour

I expect to see all defined shortcuts for menuitems

## Steps to reproduce

Simply start Gitextensions and for example click on the Navigate menu

## Screenshots

See the two screeenshot before and after clicking on Tools, Settings, Hotkeys, Apply button

## Workaround

1. Click on menu Tools, Settings, Hotkeys
2. Click on the Apply button

Please note that this workaround will work until you exit from Gitextensions: as soon you restart it the shortcut are again missing from menuitems.

## Did this work in previous version of GitExtensions

I do not have previous version so I cannot check

## Environment

- Git Extensions 3.1.0.5766-RC1
- Build 497059b2205086d8a44a33dd29f2cae2b4bfffc2 (Dirty)
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.6.1055.0
- DPI 96dpi (no scaling)

## Diagnostics

![gitextensions_navigate_menu_before](https://user-images.githubusercontent.com/31626/57353680-906bcf00-7169-11e9-9a62-fdaa8f9d4a5c.jpg)
![gitextensions_navigate_menu_after](https://user-images.githubusercontent.com/31626/57353684-9497ec80-7169-11e9-8d27-1b27df12ba2e.jpg)

**Comment by mstv** [comment]
I guess this issue is related to the same thing reported for the context menus #5433 by @drewnoakes.
Though I have never seen the shortcuts missing.

**Comment by fabvit** [comment]
Yes, this issue seems to be related to the same thing reported for the context menus #5433 by @drewnoakes.

**Comment by RussKie** [comment]
I updated  #5433 with the statement of the problem. Closing in its favour.
