### ISSUE TITLE
Publish Gerrit Change in Commit Window

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#6541]
## Feature description

It would be a great time saver for Gerrit user to have this "Commit & push"  button to Gerrit also direct in the commit window.

## Environment

- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please provide more information on how you anticipate for this to work.

**Comment by thimmy687** [comment]
The current workflow is:

I do my commit, this close the window and after this I use the green arrow (I guess they are part of the Gerrit Plugin) to "Publisch to Gerrit"

My wish is that this green arrow is also in the commit windows available. Maybe directly under the "Commit & Push" button (Also as part of the Gerrit Plugin) and only visible if the ".gitreview" file is available

next week I can also do some screenshots an and small mockup if necassary.

BR

**Comment by RussKie** [comment]
> next week I can also do some screenshots an and small mockup if necassary.

That would be great, thank you

**Comment by thimmy687** [comment]
Normally if we use Gerrit, we have the following buttons:

![image](https://user-images.githubusercontent.com/7715216/59203832-acff8a80-8b9f-11e9-9543-563fc74dd6d6.png)


I like to have something like this:

![image](https://user-images.githubusercontent.com/7715216/59203788-99ecba80-8b9f-11e9-9de9-29fc39b89ae9.png)

**Comment by RussKie** [comment]
Have you tried using "Scripts"?
You can add a script that would run "AfterCommit" or "AfterPush" and would execute your Gerrit command.
This may be an easier solution and would not require a UI change.

![image](https://user-images.githubusercontent.com/4403806/59427877-0e815c80-8e1f-11e9-9cc6-8230e33eb870.png)
 

> Normally if we use Gerrit, we have the following buttons:
> 
> ![image](https://user-images.githubusercontent.com/7715216/59203832-acff8a80-8b9f-11e9-9543-563fc74dd6d6.png)

Oh that's sneaky.
/cc: @maraf @mast-eu we need to consider whether we want to prevent plugins from modifying the main toolbar.

**Comment by maraf** [comment]
> we need to consider whether we want to prevent plugins from modifying the main toolbar.

I say yes to all possible extension points. I like the way VS lets you extend everything. In the end, it's only about the end user whether he wants the plugin or not.

**Comment by pmiossec** [comment]
I think that, if there are abuses, we could later add a setting that allow the user to disable toolbar modifications per plugins.

**Comment by maraf** [comment]
> I think that, if there are abuses, we could later add a setting that allow the user to disable toolbar modifications per plugins.

Yes, in the mean time I already created an issue for it gitextensions/gitextensions.extensibility#9.

**Comment by mast-eu** [comment]
> we need to consider whether we want to prevent plugins from modifying the main toolbar.

In https://github.com/gitextensions/gitextensions.extensibility/issues/6 I was thinking of allowing plugins to add their own toolbars through the API. Let's continue the discussion over there.
