### ISSUE TITLE
Translation diff

### ISSUE THREAD

**Issue by alexis-latorre** [gitextensions/gitextensions#6546]
Hi, there's a translation issue with the French version.
In the Diff tab (in the bottom panel), instead of "Diff avec :" is written "Diif avec :" (double 'i' instead of double 'f')
![image](https://user-images.githubusercontent.com/16638638/57510560-6ea84e80-7307-11e9-91ed-89396f0f5647.png)

Regards,
Alexis

**Comment by gerhardol** [comment]
Please update the translation:
https://github.com/gitextensions/gitextensions/wiki/Translations

**Comment by pmiossec** [comment]
@alexis-latorre We have a biggest problem with the french translation that will make this problem "quickly fixed".

>The following translations are very close but do not meet the bar, and won't be included unless updated by the end of the next week:
>- French (93.1)
>[...]

The french translation won't be in the v3.1 that will be released soon 😢 

I was the guy that did the translation for the last few years but I decided to stop doing it for multiple reasons:
* I don't use it, so I'm not the better placed to make it,
* I always considered that the level is not good enough with some information lost during the translation. I even always recommended to not use it.
* I don't have the time anymore (nor the motivation) to do it.

So, if you want to see it included in the next version, please contribute. Direct link: https://www.transifex.com/git-extensions/git-extensions/language/fr/

**Comment by RussKie** [comment]
Thank you @pmiossec.

@alexis-latorre thank you for alerting us, but the core team doesn't manage translations, translators are a separate group of people (some of whom contribute to this project as well).
We obviously rely upon them, and appreciate their efforts.

That's said, as pointed above you're welcome to fix/add translations at the Transifex site.

The French translation is slightly below the required watermark of 95%, but it may not take much to push it over the line.
We'll be doing the cut in coming days, and depending on the state the translation may or may not make it into the final v3.1 cut.
If not, we will release the translation in following releases.

**Comment by CrackyStudio** [comment]
This translation issue is still present and can't be fixed on Transifex.
![capture](https://user-images.githubusercontent.com/39296488/76515991-e466d480-645a-11ea-881e-f0482d195ac7.PNG)
What should we do?

**Comment by pmiossec** [comment]
@CrackyStudio The string to translate has changed in the next version. So you won't see the error anymore.
But the risk is that you see it in English (and all the others) if the french translation is not included in the next release because too much string are not translated.

To be sure of that won't be the case, please contribute and help translate the not translated strings...

**Comment by CrackyStudio** [comment]
I'm contributing but how should we translate things like that `Show Change&Log`. Should I translate like that `Afficher le journal des modifications` or the `&` means something ? This happen frequently like `M&ore...`

**Comment by vbjay** [comment]
& underlines the next character and provides alt + that character activaton
of that option. Ignore it.
