### ISSUE TITLE
Commit Window Menubar

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#6547]
## Current behaviour

after adding a new file to a repository the menubar in the commit window is missing

## Expected behaviour

this menubar should be visible

## Steps to reproduce

add a text file to a repository
open commit window

## Screenshots

newly added file:

![image](https://user-images.githubusercontent.com/7715216/57572640-79ed9e00-741d-11e9-9e2f-8a9eede136f4.png)

also with added content

![image](https://user-images.githubusercontent.com/7715216/57572644-8d990480-741d-11e9-9b3e-7e7b49a7f398.png)

after staging

![image](https://user-images.githubusercontent.com/7715216/57572652-b1f4e100-741d-11e9-8623-65ab90f5b9b9.png)

## Did this work in previous version of GitExtensions

not sure not tested

## Environment

- Git Extensions 3.1.0.5766-RC1
- Build 497059b2205086d8a44a33dd29f2cae2b4bfffc2 (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
This is intentional, the the entire file is shown as there are nothing to compare with.

**Comment by illfated** [comment]
Looks OK and working as intended. Nothing unexpected from what I can see.

**Comment by thimmy687** [comment]
But the vertical ruler is missing and the menu bar is not shown?

**Comment by illfated** [comment]
Yes. From what I have observed, it is only needed if there are any changes about to happen.
GE will present the menu bar to alter the view of the changes when the file is staged for commit, not before.
