### ISSUE TITLE
Some texts in german are too big for some buttons

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#6548]
## Current behaviour

Some text fields are too big, see screenshots

I also collected some other ui things...

## Expected behaviour

you know what I mean :)

## Screenshots

In commit window:

![image](https://user-images.githubusercontent.com/7715216/57572735-2bd99a00-741f-11e9-9da5-de992c308475.png)

missing translation:
![image](https://user-images.githubusercontent.com/7715216/57572738-3ac04c80-741f-11e9-9242-6c460b959cd7.png)

In Setting text not in the middle:

![image](https://user-images.githubusercontent.com/7715216/57572783-b5896780-741f-11e9-93e9-538cab9e3be8.png)

A little bit more space would be nice here in stash window:

![image](https://user-images.githubusercontent.com/7715216/57572811-229cfd00-7420-11e9-8c65-ae6827c99222.png)

Clean Working directory, missing translations:
![image](https://user-images.githubusercontent.com/7715216/57572841-7ad3ff00-7420-11e9-9f5c-ee0f1a6ccd42.png)

Submodules the space is very low

![image](https://user-images.githubusercontent.com/7715216/57572851-9a6b2780-7420-11e9-9c42-f9f9961eea25.png)

and if I shrink the window

![image](https://user-images.githubusercontent.com/7715216/57572866-c1c1f480-7420-11e9-94ec-b7c3f013813a.png)

manage remotes

![image](https://user-images.githubusercontent.com/7715216/57572876-e28a4a00-7420-11e9-8a69-ab8de73a9b7c.png)

manage remotes other tag

![image](https://user-images.githubusercontent.com/7715216/57572893-0e0d3480-7421-11e9-929b-ee630054e0d3.png)

Open Repository:

![image](https://user-images.githubusercontent.com/7715216/57572912-5af10b00-7421-11e9-83ee-d1fd9748daaa.png)

## Environment

- Git Extensions 3.1.0.5766-RC1
- Build 497059b2205086d8a44a33dd29f2cae2b4bfffc2 (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by thimmy687** [comment]
Delete branch, the icon is not left aligned:

![image](https://user-images.githubusercontent.com/7715216/57573068-25e5b800-7423-11e9-8e17-598e6c69ac75.png)

Solve Merge conflict text not in the middle:

![image](https://user-images.githubusercontent.com/7715216/57573084-5299cf80-7423-11e9-9078-45f923de344c.png)

Here the commit window again, I also the button below is not in the right position
![image](https://user-images.githubusercontent.com/7715216/57573112-b0c6b280-7423-11e9-8deb-b8d4432f439a.png)

Git Command-Log "every time in foreground" is in background 😅 

![image](https://user-images.githubusercontent.com/7715216/57573177-069b5a80-7424-11e9-9060-dd62bd487e65.png)

Checkout branch (cutted or a letter is missing "Auschecken")

![image](https://user-images.githubusercontent.com/7715216/57573200-511cd700-7424-11e9-903f-f206bb651d36.png)

Show Pull Requests:

![image](https://user-images.githubusercontent.com/7715216/57573226-a822ac00-7424-11e9-8c68-4a7031f1dbcc.png)

Archive...

![image](https://user-images.githubusercontent.com/7715216/57573234-def8c200-7424-11e9-9792-d8931e74ae6e.png)

"Apply Patch" button sizes

![image](https://user-images.githubusercontent.com/7715216/57573250-22533080-7425-11e9-9918-99f01991763f.png)

**Comment by gerhardol** [comment]
For translations, the source is on Transifex, register an account and make suggestions there.

In some situations, the UI may have to be changed, but the first attempt should be to update the translation.

**Comment by illfated** [comment]
> Delete branch, the icon is not left aligned:
> 
> ![image](https://user-images.githubusercontent.com/7715216/57573068-25e5b800-7423-11e9-8e17-598e6c69ac75.png)
> 

The position is exactly the same in the English version,
- Git Extensions 3.0.2.5232
- Build 23b6f51905006ccdde8701591df706284b4155dc
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

I don't think this is a translation issue, but a general Git Extensions UI issue (cosmetic). Report it separately if you are sure that the icon should be aligned further to the left, separated from the text.
***
> Solve Merge conflict text not in the middle:
> 
> ![image](https://user-images.githubusercontent.com/7715216/57573084-5299cf80-7423-11e9-9078-45f923de344c.png)
> 
Maybe. I am not sure, but to me it looks like it could be a general UI issue -- and cosmetic at that.
***
> "Apply Patch" button sizes
> 
> ![image](https://user-images.githubusercontent.com/7715216/57573250-22533080-7425-11e9-9918-99f01991763f.png)

I may have misunderstood your point here, but if you want the buttons shorter, I think they are kept the same size for simplicity reasons (same GUI size definitions).

**Comment by thimmy687** [comment]
@illfated the last screenshot you mentioned, there are the enabled buttons smaller than the disabled

**Comment by illfated** [comment]
Oh. Right. I didn't notice. I guess I thought the edges look slightly different because of focus / non-focus.
Thank you for pointing out the difference.

**Comment by thimmy687** [comment]
In this window the issue is, that the translated text is far to long..

![image](https://user-images.githubusercontent.com/7715216/57582345-e0c59280-74c3-11e9-9c64-6e33b47bd17f.png)

![image](https://user-images.githubusercontent.com/7715216/57582355-00f55180-74c4-11e9-9850-eeb4f87339b4.png)

For my opinion "Tastenkombinationen zurücksetzen" should be enough if more information is required a tooltip should be used instead of having so much letters

**Comment by illfated** [comment]
https://github.com/gitextensions/gitextensions/issues/6548#issuecomment-491541239
> For translations, the source is on Transifex, register an account and make suggestions there.
>
> In some situations, the UI may have to be changed, but the first attempt should be to update the translation.

**Comment by thimmy687** [comment]
done

**Comment by RussKie** [comment]
Once the text is fixed, let's revisit and see what needs to be tweaked on the UI level.

**Comment by thimmy687** [comment]
at this special button position is also possible to set AutoSize property to "true", so it takes so much space the text needed in each language, I can do a PR for this tiny change if you like.

**Comment by thimmy687** [comment]
if I add in this case the autosize property, this looks ugly :/ my somebody have an idea to solve this issue?

![image](https://user-images.githubusercontent.com/7715216/57634021-d202dc80-75a4-11e9-84fc-915ab6677005.png)

**Comment by RussKie** [comment]
I suggest replacing the `flowCommitButtons` (which is a `FlowLayoutPanel`) with a `TableLayoutPanel`.
Have it docked (`Fill`) but with autosize (grow and shrink). All its controls to be docked and autosized too.
This way the layout will be fluent.
