### ISSUE TITLE
Link to user manual "Page not exist"

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#6550]
## Current behaviour
this link seems not to work at the moment:

https://git-extensions-documentation.readthedocs.io/en/release-3.1/

![image](https://user-images.githubusercontent.com/7715216/57573309-0ef49500-7426-11e9-9efd-b20b82e64df0.png)

## Expected behaviour

a user manual

## Steps to reproduce

Help -> User Manual

## Environment

- Git Extensions 3.1.0.5766-RC1
- Build 497059b2205086d8a44a33dd29f2cae2b4bfffc2 (Dirty)
- Git 2.19.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Builds updated
Documentation is not updated yet to 3.1 (not so many changes)
