### ISSUE TITLE
Add Submodule: Fill combobox with branches regardless of the repo URL's type

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6556]
## Current behaviour

I have tried to add a (first) submodule to a repo.
The exception is thrown when I try to open the yet empty `Branch` combobox.

This combobox is not filled for remote repos at all, regardless whether specified with HTTPS URL or with SSH URL.

## Expected behaviour

list of available branches filled correctly
no unhandled exception
no exception for a valid URL

## Steps to reproduce

- create a standalone clone of the repo which shall be used a submodule
- copy its `URL` from the `Remote repositories` dialog ("git@host:user/path.git")
- open GE for the destination repo
- `Manage submodules`, `Add submodule`
- paste the URL
- drop down the `Branch` combobox, which was empty yet

## Error details 3.2.0
- combobox does not contain the branches of the sub-repo unless an URI of type `//file:` is given

(no unhandled exception)

## Error Details 3.1.0
```
System.UriFormatException: Ungültiger URI: Das URI-Schema ist ungültig.
   bei System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   bei GitCommands.PathUtil.NormalizePath(String path)
   bei GitCommands.GitModule..ctor(String workingDir)
   bei GitUI.CommandsDialogs.SubmodulesDialog.FormAddSubmodule.BranchDropDown(Object sender, EventArgs e)
   bei System.Windows.Forms.ComboBox.OnDropDown(EventArgs e)
   bei System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ComboBox.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0
- Build 678b69e632a2bff81c5e093770f605e0fe1151c8
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Do you see this as a blocker for the release?

**Comment by mstv** [comment]
This is a RL use case and should be fixed in the release, not necessarily in the RC2.

**Comment by mstv** [comment]
The fix #6560 improves the behavior a little by ignoring the exception.
But the list of branches remains empty and a - more or less - random branch is chosen by Git for the submodule.

**Comment by RussKie** [comment]
Would you like to drive this one?

**Comment by mstv** [comment]
If an existing repo folder is specified, its branches are listed.
If a HTTP(S) URL is given, a GitModule is created for a non-existing local path.
For a SSH URL, the `GitModule`'s `WorkingDir` is empty since #6560, which silently eats the `UriFormatException` to solve another issue.

I guess this has not worked for years if ever.
At least, the desired branch can be entered manually.
The high prio part of this issue has been fixed with #6560.

`git lsremote <URL>`, which works for all three types of URLs, looks like an easy solution.
I do not see a need to create a new `GitModule` anymore.

Any concerns?
Is there a parser for the Git output (refs) which should be reused?
It will be hard to write automated integration tests since GitHub denies even read access to repositories via SSH unless one uploads a public key.

https://github.com/gitextensions/gitextensions/blob/6a2ebafa43d3ed1d76ec75df83f4d87c230b5f53/GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs#L71-L87

**Comment by RussKie** [comment]
> `git lsremote <URL>`, which works for all three types of URLs, looks like an easy solution.
> I do not see a need to create a new `GitModule` anymore.

:+1:



> Is there a parser for the Git output (refs) which should be reused?

I'd search the code for `lsremote` and see if we call this command.
If we don't - that's easy, create a new command.
If we do - see whether it is in a reusable form, if not... that's where we'd need to discuss our options.

> It will be hard to write automated integration tests since GitHub denies even read access to repositories via SSH unless one uploads a public key.

That's ok, we can discuss/document manual testing steps.

**Comment by RussKie** [comment]
@mstv do you want this fix to be in 3.1.1?

**Comment by mstv** [comment]
I think this is not such urgent anymore since the high prio part of this issue has been fixed with #6560.

**Comment by gerhardol** [comment]
The UriException fix was included in master (3.2), is not in 3.1.1

**Comment by RussKie** [comment]
@mstv can you please verify if this still an issue in 3.2
Thanks

**Comment by mstv** [comment]
no more unhandled exception, though `Branch` combobox still empty
updated this issue's description
