### ISSUE TITLE
Add Submodule: Dialog not listed in Windows Task Switcher

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6557]
## Current behaviour

The subdialog `Add submodule` does not appear in the `Alt+Tab` list.

## Expected behaviour

appears

## Steps to reproduce

* `Repository` | `Manage submodules...` | `Add submodule`
* switch to another application
* hit `Alt+Tab`

## Did this work in previous version of GitExtensions

no (guessing)

## Environment

- Git Extensions 3.1.0
- Build 678b69e632a2bff81c5e093770f605e0fe1151c8
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Do other dialogs (like 'create branch' or 'delete tag') appear?

**Comment by mstv** [comment]
Yes, they do.
`Add submodule` has a different dialog style:
![grafik](https://user-images.githubusercontent.com/36601201/57688324-73d60800-763d-11e9-862c-12de4d9a8298.png)

**Comment by mast-eu** [comment]
That's a funny one. I can reproduce on Win7, but not on Win10.

The issue description is misleading though: GE always appears only once in the `Alt+Tab` list. In other words, you can never use `Alt+Tab` to switch between the main dialog and subdialogs (e.g. `Add submodule`, `Create Tag` or `Commit`), as the description suggests.
However, when I open `Repository` | `Manage submodules...` | `Add submodule` on my Win7 PC, then GE will _disappear_ from the `Alt+Tab` list altogether. It remains in the taskbar and is fully responsive. As soon as I close `Add submodule` dialog, GE reappears in the `Alt+Tab` list.

**Comment by mstv** [comment]
> The issue description is misleading though: GE always appears only once in the Alt+Tab list.

No, it does not always. And that's this is issue about (as you described more clearly in the last paragraph). I do not expect to switch between GE's main window and its *modal* dialogs - see the STR.
