### ISSUE TITLE
Commit Dialog: New submodule without text if unstaged

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6559]
## Current behaviour

Only a new file icon `+` without the folder name of a new submodule can be seen in the list of unstaged files.

## Expected behaviour

Text displayed as in the list of staged files.

## Steps to reproduce

- add a new submodule
- unstage the changes in the Commit dialog

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/57691134-9f5bf100-7643-11e9-975c-c754306a6f5d.png)

## Did this work in previous version of GitExtensions

I don't know.

## Environment

- Git Extensions 3.1.0
- Build 678b69e632a2bff81c5e093770f605e0fe1151c8
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
This is pretty bad...
We need to get it fixed for 3.1.1

**Comment by mstv** [comment]
My main PC with the dev env died yesterday. It will take some time to get a replacement and to install it.

**Comment by RussKie** [comment]
Ouch! Hope you get it up and running without major headaches.
Chocolatey is quote good in streamlining the software install 😉

**Comment by RussKie** [comment]
@mstv do you want this fix to be in 3.1.1?
