### ISSUE TITLE
[NBug] Remote URLs should appear in pairs.

### ISSUE THREAD

**Issue by zennboy** [gitextensions/gitextensions#6562]
## Current behaviour

Crashes as soon as I try to open the app.

## Expected behaviour

The app would open normally.

## Steps to reproduce

Crashes as soon as I try to open the app.

## Error Details
```
System.Exception: Remote URLs should appear in pairs.
   at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|155_0(IEnumerable`1 lines)
   at GitCommands.GitModule.<GetRemotesAsync>d__155.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.<>c__DisplayClass69_0.<<AddTree>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.16.2.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please fill in all necessary information

**Comment by pmiossec** [comment]
Could you run the command `git remote -v` in your repository and report here the result of the command?

Feel free to alter the url if it's confidential...

You've got this error because you should have a pair number of lines (one for 'fetch' and one for 'push').
Either you've got a problem in your repository or we missed something.

**Comment by zennboy** [comment]
Sure:

$ git remote -v
origin  https://github.com/--------/-------.git (fetch)
origin  https://github.com/--------/-------.git (push)

Version 3.0.2.5232 works great.  I got this error after updating to 3.1.0.5877 and trying to run GitExtensions.

**Comment by pmiossec** [comment]
@zennboy Did you changed the version of git in the same time you updated GitExtensions?

Because the code that introduced this verification (c11a009b3049660aa6f27db45d8cd12f8fa5bf9f) was introduced in v3.0.

Perhaps this code was used somewhere else in the application...

Your output seems good and I don't really understand why the exception is thrown.
Perhaps an empty line at the end that make the code unhappy.... (introduced by a2a3f28ceeb12ffd378005455223272ab0019858 with the use of `GetOutputLinesAsync()` instead of `GetOutputLines()` ? /cc @jbialobr )

**Comment by illfated** [comment]
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

I have not seen this issue on my computer, but I guess I am not opening the same type of repositories as those who see this issue. My only local repositories are local copies of those on my user page (https://github.com/illfated?tab=repositories).

**Comment by RussKie** [comment]
We need more info or have consistent repro steps.

**Comment by pmiossec** [comment]
>We need more info or have consistent repro steps.

I will try to push a attempt of fix in a few minutes.
I imagine that the problem come from a version of git <=2.16 that return an empty line in the output of the command as https://github.com/gitextensions/gitextensions/issues/6562#issuecomment-492709643 output seems good....

**Comment by pmiossec** [comment]
Could you (@zennboy , @dnoakes , @reydevelop , @MayorovSerg, @imranmu  ) test this version (https://ci.appveyor.com/api/buildjobs/ux013rkfald1wa92/artifacts/combined.3.1.0.5898-unsigned.zip ) and reports if it solve this problem?

In the artifact, you will find a setup or the portable version. Try the one you find easier to test (probably more the portable one...)

Note: that's the result of the build of #6578.

**Comment by RussKie** [comment]
I downgraded to git 2.16.1 and I get an error only when start with the dashboard... If I start with a repository - no errors
![image](https://user-images.githubusercontent.com/4403806/57850388-274b2200-7821-11e9-9b0b-7a5e9543b942.png)

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.16.1.windows.4
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3324.0
- DPI 144dpi (150% scaling)

**Comment by pmiossec** [comment]
>I downgraded to git 2.16.1

So, now, you could try the fix 😉

**Comment by RussKie** [comment]
I think this is the culprit - an error message wording has changed:
![image](https://user-images.githubusercontent.com/4403806/57851120-21eed700-7823-11e9-8184-83bb4ba23ec3.png)

**Comment by pmiossec** [comment]
So, that fails for the 'N' in upper case?

**Comment by RussKie** [comment]
I suspect so...
Preparing a fix, shouldn't be long

**Comment by RussKie** [comment]
Please try this build - https://ci.appveyor.com/api/buildjobs/yhoaokuijg0feqpa/artifacts/combined.3.1.0.5900-unsigned.zip

**Comment by gerhardol** [comment]
We should maybe raise the recommended Git version too.

**Comment by zennboy** [comment]
> Please try this build - https://ci.appveyor.com/api/buildjobs/yhoaokuijg0feqpa/artifacts/combined.3.1.0.5900-unsigned.zip

That build works with no issues.

**Comment by vbjay** [comment]
Does the output of the error come from error stream or standard output?  I really don't like the look for x string to say we have an error. If possible can we look at the error stream and see if it has data in error stream?

```bash
git remote -v 2> error.txt
git remote -v 1> std.txt
cat error.txt
cat std.txt
```

**Comment by RussKie** [comment]
```
MINGW64 /c/Development
$ git remote -v 2> error.txt

MINGW64 /c/Development
$ git remote -v 1> std.txt
fatal: Not a git repository (or any of the parent directories): .git

MINGW64 /c/Development
$ cat error.txt
fatal: Not a git repository (or any of the parent directories): .git

MINGW64 /c/Development
$ cat std.txt

```

**Comment by RussKie** [comment]
> I really don't like the look for x string to say we have an error.

Agree, the current implementation is not particularly water tight.  

> If possible can we look at the error stream and see if it has data in error stream?

These both points necessitate a refactor. `GetOutputLinesAsync` combines outputs from the both streams together.

**Comment by RussKie** [comment]
> We should maybe raise the recommended Git version too.

Do you mean the "minimum" version?
![image](https://user-images.githubusercontent.com/4403806/57890818-707c8f80-787c-11e9-9dcc-2be025de6de9.png)

**Comment by RussKie** [comment]
We'll patch 3.1 with a simple fix, but the master can get a bit more elaborate fix.

**Comment by gerhardol** [comment]
> Do you mean the "minimum" version?

Yes, keep recommended to 2.20 and up.

**Comment by RussKie** [comment]
What new minimum do you think is sensible?
2.18? It was release at the end of 2018, I think.

**Comment by mstv** [comment]
>> If possible can we look at the error stream and see if it has data in error stream?

> These both points necessitate a refactor. GetOutputLinesAsync combines outputs from the both streams together.

This should be done with #6527.

**Comment by gerhardol** [comment]
Git version checks:
The exception occurs prior to the settings are shown, so changing the recommendation/minimum version, so in this case it would not make a difference anyway. So I backtrack now, no change for 3.1.x.

Recommended version:
Set to the version that should be used mostly during development. For 3.1.0 it is set to 2.20 that was released in end of 2018. For 3.2 it should be set to 2.22 (rc2 was just released).

Minimum version:
The tests for older versions than recommended are very limited, basically users trying out RC I guess. 
Set to the oldest version that we want to support, 2.11 (Dec 2016) in GE3.1, but GE should work with older versions too (maybe even 1.x).
For GE 3.0, 2.11 was selected as it was two years, which seem like a reasonable time. We could raise this to 2.17, released April 2018 setting the grace time to a year, but it may be too short for some corporate upgrade cycles.

**Comment by RussKie** [comment]
I've tried changing the minimum version locally to 2.17, it had no effect - the app would still start.

Suggest we uplift this part of the code to perform the check and advise the user about old/unsupported git version, e.g.:
```
The detected git version is {x.y.z} is older than minimum supported {x.y.z}.
Please consider updating, otherwise some functionality may not work.
[I accept the risk, continue] [Let's update] [Cancel]
```

"I accept the risk, continue" - set a flag not to bother the user until a next app upgrade (reset via the setup)
"Let's update" - take the user to https://git-scm.com/downloads
"Cancel" - quit the app

Thoughts?

**Comment by pmiossec** [comment]
>Thoughts

Yes, that's what we should do but, even if that's a good step towards reducing the number of reports, I think that will not prevent them.


Also a good first step could be to add in the about form and reports generated (and telemetry ?)  the expected git version. That way, diagnostic will be easier and issues will be more durable/lasting (we will always know what was the recommended version at the time and if we could close without after thoughts).

I also think we could write also in the same place "your version of git is outdated, please update (before reporting)".

That way users will be aware that they report an issue even if there git is outdated.

PS: I also think that we should update the text of the auto generated issue message to tell user that there issue will most probably be closed/ignored if they don't enter additional information because all the issues we had for the moment are empty (except the generated data) :😢

**Comment by RussKie** [comment]
> Also a good first step could be to add in the about form and reports generated (and telemetry ?) the expected git version. That way, diagnostic will be easier and issues will be more durable/lasting (we will always know what was the recommended version at the time and if we could close without after thoughts).

> PS: I also think that we should update the text of the auto generated issue message to tell user that there issue will most probably be closed/ignored if they don't enter additional information because all the issues we had for the moment are empty (except the generated data) 😢

Ideally we uplift NBug form to capture all necessary info, so we don't get half filled reports we do now. The "send" button shouldn't be enabled unless all necessary data is filled.
The only major issue with that is NBug project has been localised, and we'll need to get translations re-setup. Doable, but requires effort.

Telemetry is coming in #6522.

> I also think we could write also in the same place "your version of git is outdated, please update (before reporting)".

Goo idea 👍 The same problem with translation though.

**Comment by pmiossec** [comment]
@RussKie I have edited the first post to make a summary easier to understand for people reporting the same issue (without to be obliged to read all the messages of this issue).

Do you think that you could see if it's OK and update it if needed?

**Comment by RussKie** [comment]
Awesome, thank you Philippe 👍

**Comment by gerhardol** [comment]
@pmiossec 
Good summary but I would like to link to our wiki page

**Comment by pmiossec** [comment]
>Good summary but I would like to link to our wiki page

I don't know enough the wiki. Which page? Could you do it?

I found probably this one ( https://github.com/gitextensions/gitextensions/wiki/Canary-Builds ), but need to be updated... I will update it.

**Comment by gerhardol** [comment]
> I don't know enough the wiki. Which page? Could you do it?

Updated
