### ISSUE TITLE
Incorrect height in SSH Authentication error message

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#6564]
## Screenshots

![image](https://user-images.githubusercontent.com/7715216/57753596-d803d500-76ec-11e9-9000-1224a03e2cbf.png)

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by illfated** [comment]
issue title suggestion:
**SSH Authentication error message text height incorrectly cut**

**Comment by zachesposito** [comment]
Hello late Hacktoberfester here, I can take care of this
