### ISSUE TITLE
Export files from specific commit by right clicking on it

### ISSUE THREAD

**Issue by amitshahc** [gitextensions/gitextensions#6566]
## Feature description

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

I noticed the new (above) Git extension has a facility to export updated files between two selected commits (by right-click + `Archive this commit`).  but further, there should be a facility to export only single commit files. currently, it exports the whole project at that commit.

- `Archive this commit` => should export only commit specific files for selected commit.
- `Archive up to this commit` => should do the same that currently `Archive this commit` does now. dump the whole repository till selected commit.

**Comment by RussKie** [comment]
> * `Archive this commit` => should export only commit specific files for selected commit.

Could you please elaborate what you mean by this?

A commit is a snapshot of a working directory in time. 
You can see a diff (or a delta) between two (or more) commits. That delta can be expressed in a form of a patch. 
You can deal with patches via _Commands > Format patch..._.

**Comment by amitshahc** [comment]
Hi RussKie,

My requirement is very simple and straightforward. Though, I wouldn't recommend to broaden and confuse each other by adding `patch` `diff` `snapshot` etc words in this. 

* What is a commit? : For a developer like me, `commit` is a stage where the GIT generates the `commit hash` and mark it as a one-stop in the revision history. When we push and merge the updated files with some comment about those changes to the repository. 

Now, let me explain what I want to achieve is. I have a latest updated copy on my web server which is also the same stage at head or revision from the git repository. now I am making some changes in 2-3 files on my developer machine where I have check out the git repository. then I commit it and push. now by right-clicking on the same commit which I just pushed, I want to download all those 2-3 updated **FILES ONLY** _**(please mind this bold latter that I am not talking about patch or diff, I can't upload patch file or diff files on the server where my website is running. all I want is just to export those 2-3 files in a zip single file)**_. Again, I want those files only which I updated and not patch or diff or full revision to upload the and overwrite the updated files only. Isn't it just simple and requirement, the job that a developer has to perform every day on a regular basis? That's it.... 

Please focus my requirement onto the FILES only. I don't want to see diff and patches and i never mentioned it. i am not sure how did you drag it into my initial explanation.

**Comment by amitshahc** [comment]
**Case 1: Export a zip containing updated files between two commits.** (This case is working as expected.)

1. Select two commits and right-click -> `Archive this commit`

![ge1](https://user-images.githubusercontent.com/13152428/57831298-6605bb80-77d2-11e9-8fb7-d04c01e4bbdf.jpg)

2. Click on Save as

![ge2](https://user-images.githubusercontent.com/13152428/57831300-669e5200-77d2-11e9-8cd4-2bdbea116b5a.jpg)

3. Give a zip file name

![ge3](https://user-images.githubusercontent.com/13152428/57831301-669e5200-77d2-11e9-86a3-8f58848febb0.jpg)

4. You can see that the zip folder contains only the updated files and not all the files of whole project.

![ge4](https://user-images.githubusercontent.com/13152428/57831303-669e5200-77d2-11e9-834c-ffd7fac06812.jpg)

**Case 2: Export from selecting only single commit and try to get updated files of that commit.** (This case is **not** working as expected.)


1. Select single commit then right-click -> `Archive this commit`

![ge5](https://user-images.githubusercontent.com/13152428/57831304-6736e880-77d2-11e9-82c4-c33d563e801f.jpg)

2. Click on Save as

![ge6](https://user-images.githubusercontent.com/13152428/57831305-6736e880-77d2-11e9-8e43-0cd5fbca55c3.jpg)

3. give a zip file name

![ge7](https://user-images.githubusercontent.com/13152428/57831307-6736e880-77d2-11e9-97e8-3126d95d2b4c.jpg)

4. You can see it contains whole project files but not specific to that commit changes. I don't want to upload whole project files if I target to upload a single commit change. This is not as per expectation. 

![ge8](https://user-images.githubusercontent.com/13152428/57831308-67cf7f00-77d2-11e9-9444-baf622719e72.jpg)
