### ISSUE TITLE
Improve stacktrace readability by using Ben.Demysifier

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#6569]
## Feature description

In NBUG and our crash report form, I think we will gain to use Ben.Demystifier to get beautiful (and more readable) stacktraces in the reports.

See https://github.com/benaadams/Ben.Demystifier#bendemystifier to see how it could improve a stacktrace.

**Comment by RussKie** [comment]
Nice one!
You can apply this to NBug project 😉
