### ISSUE TITLE
Translations are missing in v3.1 portable version

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions#6572]
## Current behaviour

The translations are missing alltogether in the portable version 3.1. They are included only in the installer version.
As a consequence, when you start the portable version for the first time, it lets you select only English. Also from the Settings, you cannot change the language.

## Expected behaviour

The same languages as for the installer version shall be included also in the portable version.

## Steps to reproduce

1.  Download https://github.com/gitextensions/gitextensions/releases/download/v3.1/GitExtensions-Portable-3.1.0.5877.zip
2. unzip and start it

## Screenshots

![image](https://user-images.githubusercontent.com/46861028/57811019-83eb0600-7769-11e9-8376-0c2cada29ea8.png)

![image](https://user-images.githubusercontent.com/46861028/57811202-f0fe9b80-7769-11e9-8de4-b02e2486acb4.png)

## Did this work in previous version of GitExtensions

Yes. v3.0.2 portable was ok.

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by RussKie** [comment]
Hmm... Can you check what files you have on the files system?
![image](https://user-images.githubusercontent.com/4403806/57812696-2a0e2e80-77b1-11e9-9ea5-54226e55cf64.png)
![image](https://user-images.githubusercontent.com/4403806/57812733-47db9380-77b1-11e9-97c6-5e77769e4571.png)

**Comment by mast-eu** [comment]
Whoops sorry, false alarm: the portable version does contain the translations!

I guess the extraction process on my PC got somehow interrupted and left me with the binaries already extracted (so I could run GE), but the translations still missing.

I just deleted the entire directory and extracted the archive again. Everything worked as expected.
