### ISSUE TITLE
Default remote keeps switching

### ISSUE THREAD

**Issue by shmosel** [gitextensions/gitextensions#6585]
I have a few remotes set up, but I use one of them almost exclusively. Occasionally when I use the default action, it will fetch from another remote, and I'll have to switch it back in the pull dialog.

Looking at the remote repositories dialog, the main one is second in the list and the one it switches to is first. There's a third one, but I haven't had any problems with it.

This has been going on for some time, across a number of versions. I hadn't been able to consistently reproduce it in the past, but I experimented a bit and it seems to happen when I'm not checked out to a local branch. This is my current environment:

- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
git remote -v

**Comment by shmosel** [comment]
```
gitlab  git@gitlab.domain.com:primary/project.git (fetch)
gitlab  git@gitlab.domain.com:primary/project.git (push)
origin  ssh://git@bitbucket.domain.com:7999/proj/repository.git (fetch)
origin  ssh://git@bitbucket.domain.com:7999/proj/repository.git (push)
webapps2        C:/webapps2/project (fetch)
webapps2        C:/webapps2/project (push)
```

**Comment by RussKie** [comment]
Apologies, but I'm finding your description of the problem confusing. 
Could you please describe steps with examples/screenshots of what you're doing and what is happening for us better understand the problem.
Thank you

**Comment by illfated** [comment]
> it seems to happen when I'm not checked out to a local branch.

I tried to compare this with your listed branches from git -v , but to me, your list appears to only contain 1 upstream (gitlab), 1 origin (bitbucket) and 1 local branch (webapps2). Not sure how to distinguish between different remotes, unless you are trying to say that you want to fetch from upstream (gitlab), but the dialog presents the origin (bitbucket) branch instead. (I may have misunderstood your config.)

Speaking for myself (sorry if this deviates too much from the issue), I always (99%) pull from upstream, in which the default pull (with merge) works as a charm. I love the default pull action feature. I also always checkout the local clone branch before doing a pull action. My local branch is usually cloned from upstream, making it easy to use the default pull action. What I also would like to do is to push to origin as the default action (which I do 99% of the time), but in that dialog I need to switch from upstream to origin, because I am not a member with push rights in any upstream project. This scenario can be reversed if I clone from origin instead of upstream. Maybe there is something I have missed, I don't know.

**Comment by shmosel** [comment]
I'm trying to fetch from origin using the default pull action, but it fetches from gitlab when I'm not checked out to a local branch.

**Comment by RussKie** [comment]
> but it fetches from gitlab when I'm not checked out to a local branch.

Are you performing "fetch" or "fetch all"?

> when I'm not checked out to a local branch.

Please clarify

Also check what remote you're tracking your master branch against
![image](https://user-images.githubusercontent.com/4403806/58096052-948ef680-7c17-11e9-80b0-6823f64e63e5.png)

**Comment by shmosel** [comment]
> Are you performing "fetch" or "fetch all"?

Fetch

> Please clarify

See blue vs. red:
![image](https://user-images.githubusercontent.com/6895933/58123152-0fc4be00-7bc0-11e9-9bdd-de1f945cd5cd.png)
Same when I check out revision:
![image](https://user-images.githubusercontent.com/6895933/58123233-371b8b00-7bc0-11e9-824a-105c5d112e66.png)

> Also check what remote you're tracking your master branch against

```
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

**Comment by vbjay** [comment]
Checkout revision has nothing to do with fetch. It puts the local head in a detached head state. Of course it won't know which remote to use in that case.  Notice (no branch)

![image](https://user-images.githubusercontent.com/3629489/58125101-cd11de80-7bdd-11e9-94e6-0041a83ababa.png)

**Comment by shmosel** [comment]
I didn't realize the remote was selected based on the checked-out branch. Anyway, what about when I'm checked out to a remote branch?

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/58127383-46600000-7be3-11e9-84a3-e597acbd545d.png)
![image](https://user-images.githubusercontent.com/3629489/58127416-5677df80-7be3-11e9-954e-4156d0f52e38.png)
Make sense now?

**Comment by vbjay** [comment]
See.  This will link local branch release/3.1 to the upstream branch.  

![image](https://user-images.githubusercontent.com/3629489/58127752-15cc9600-7be4-11e9-881c-923d97f2199e.png)

![image](https://user-images.githubusercontent.com/3629489/58127786-2b41c000-7be4-11e9-961e-c8d64139b435.png)

**Comment by vbjay** [comment]
Do you see how it works now?

![image](https://user-images.githubusercontent.com/3629489/58127994-a905cb80-7be4-11e9-8d4f-9f52e4e3b696.png)

**Comment by shmosel** [comment]
Not quite. Isn't it logical to expect it to fetch from origin when I'm checked out to `origin/master`? What am I missing?

**Comment by vbjay** [comment]
Not if it is linked to upstream.  Show your remotes dialog in GE.  
![image](https://user-images.githubusercontent.com/3629489/58128293-43660f00-7be5-11e9-984b-6941ff1489c0.png) with the second tab selected.

**Comment by vbjay** [comment]
JUst because you checked out the branch origin/master so that your local master now points to that commit, doesn't mean your local branch isn't linked to otherRemote/master.

**Comment by shmosel** [comment]
![image](https://user-images.githubusercontent.com/6895933/58128432-78b23300-7bcc-11e9-8c68-40328250a958.png)

**Comment by vbjay** [comment]
Good.  Look through that dialog.  Do you see a branch pointing to another remote.  Also note that checking out a remote branch does this as in same thing as check out revision
![image](https://user-images.githubusercontent.com/3629489/58129171-27636d00-7be7-11e9-8806-27d46fd84f94.png)

![image](https://user-images.githubusercontent.com/3629489/58129037-e79c8580-7be6-11e9-8693-a605f8cb4fef.png)

**Comment by shmosel** [comment]
There are a few branches from webapps2 but none from gitlab.

**Comment by vbjay** [comment]
I suggest this issue be closed because it is how git works. You need to
read up on tracking branches.

**Comment by illfated** [comment]
Thank you for the insights. I now presume my own comment also is a result of not knowing enough details about git functionality, but I will do my best to read up on it.
