### ISSUE TITLE
GitExtension Exception resetting 1500 files in Diff tab

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#6593]
## Current behaviour
GitExtensions crashes

## Expected behaviour
No crash

## Steps to reproduce
Have a big change in working directory (1500 files)
Go to Diff tab
Select all files
Press R (Reset to index)

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The filename or extension is too long
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<RunCommandAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at GitCommands.ExecutableExtensions.RunCommand(IExecutable executable, ArgumentString arguments, Byte[] input, Boolean createWindow)
   at GitCommands.GitModule.CheckoutFiles(IReadOnlyList`1 files, ObjectId revision, Boolean force)
   at GitUI.CommandsDialogs.RevisionDiffControl.ResetSelectedItemsTo(Boolean actsAsChild)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.ToolStrip.ProcessDialogKey(Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Looking at the code, all selected files are passed to git command - `git checkout --force <sha> -- <list of files>`

How do you think this can be fixed?

**Comment by gerhardol** [comment]
> How do you think this can be fixed?

Maybe by splitting in several Git commands for long lines. How long?

**Comment by NN---** [comment]
1500 files * filename path (let's say 40 characters) gives us 60000 line long

**Comment by pmiossec** [comment]
>Maybe by splitting in several Git commands for long lines. How long?

That's what I was thinking... The first that say it, should do it? 🤣 

...even if it's a little pain to do it (not cutting but running the batch of processes).

**Comment by pmiossec** [comment]
>1500 files * filename path (let's say 40 characters) gives us 60000 line long

I think he was wondering the limit of the a command line process...

**Comment by NN---** [comment]
CreateProcess APO has 32,768 limit

https://docs.microsoft.com/en-us/windows/desktop/api/processthreadsapi/nf-processthreadsapi-createprocessa

**Comment by gerhardol** [comment]
> The first that say it, should do it?

I do not assign myself. While I usually do what I plan, some things take longer than others.
Anyone can dig in.

RevisionDiffControl.cs calls GitModule.cs:CheckoutFiles() without any specific error handling.
A simple approach is to add files to a string uand execute when limit reached (or out of files). We should probably not bother about the garbage collection, just do something simple.

**Comment by NN---** [comment]
Is there any option to read command line from file in git ? Like this: [Specifies a compiler response file.](https://docs.microsoft.com/en-us/cpp/build/reference/at-specify-a-compiler-response-file?view=vs-2019)

**Comment by hieuxlu** [comment]
Anyone working on this? I found that:
1. `GitRevision.SelectedItemParent` should be `Distinct()`
2. To work around `32767` line length cmd line limit, we have to create a new `RunCommandBatch` method, so we could execute long cmd in batch, and fix similar issues.
3. Commit dialog also have performance issue when resetting large number of files, because it is processing each file sequentially. Should we fix this as well?

I'll be happy to create a PR after we discuss how best to fix these. Posted on Gitter, but it seems to be inactive and not suitable for issue discussion.

**Comment by gerhardol** [comment]
> Anyone working on this?

Probably not, please go ahead

> I'll be happy to create a PR after we discuss how best to fix these. Posted on Gitter, but it seems to be inactive and not suitable for issue discussion.

Yes, the solution to discussed here
(no comment on the solution right now, you could submit a WIP PR too)

> Commit dialog also have performance issue when resetting large number of files, because it is processing each file sequentially. Should we fix this as well?

That maybe registered as a separate issue. It should probably be a separate PR based on the Diff PR (I assume that there will be code similarities or sharing)

**Comment by RussKie** [comment]
> Posted on Gitter,

Gitter is more about general chat and quick questions about functionality.
Any discussions about bugs or features should happen here.

**Comment by hieuxlu** [comment]
@gerhardol Please take a look at #7218. Seems like there's a lot of similar issues & performance-related issues we can address after this.

**Comment by hieuxlu** [comment]
@gerhardol 
> 
> That maybe registered as a separate issue. It should probably be a separate PR based on the Diff PR (I assume that there will be code similarities or sharing)
>
Someone've already open that issue here #3280, so I won't create a new issue. I created PR #7237 to fix this, and Yes, it is continued from PR #7218. Please take a look. Thanks.

**Comment by hieuxlu** [comment]
@RussKie One more thing here. I think GitExtensions is the only Github repo labeling issues with `:beers: hacktoberfest` instead of `hacktoberfest`. This results in our issues not shown in event homepage at https://hacktoberfest.digitalocean.com/ . Could we change the labels so that more people can participate? I don't know if there's some tool for batch labelling issues on Github, or you guys have to label manually.

**Comment by gerhardol** [comment]
> I think GitExtensions is the only Github repo labeling issues with :beers: hacktoberfest instead of hacktoberfest

I reverted the added icon

**Comment by RussKie** [comment]
Got spot :) I didn't think about it...
Thank you for alerting us
