### ISSUE TITLE
Create branch on "working directory" creates revision 11111 instead of last known commit

### ISSUE THREAD

**Issue by nmat** [gitextensions/gitextensions#6597]
## Current behaviour
I wanted to create a branch on the current branch selected "master" for example to do a merge request but didn't look where I stood in the current tree of commits so just hit Ctrl+B

Standing on "Working Directory" showed this dialog:

![image](https://user-images.githubusercontent.com/383031/57966497-ece1a200-7952-11e9-836c-bc2f68f3356b.png)

There is no way to add this and then create commits to it. To fix this I had to go out from that dialog and then select the last known commit in the tree and create a branch.

![image](https://user-images.githubusercontent.com/383031/57966512-2c0ff300-7953-11e9-8299-713632b7d48d.png)

Then it works.

## Expected behaviour
Either add branch from last known commit in the tree or make selecting the last known commit in the dialog.

Or just skip and do not allow creating a branch on "Working directory"

## Steps to reproduce

1. Go to any repo
2. Select the "Working directory" commit in the tree
3. Ctrl+B to create a new branch

Its happened on all the repos I have tested so far including GitExtensionDocs repo

## Did this work in previous version of GitExtensions
Not sure

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
> do not allow creating a branch on "Working directory"

That is what should be done
