### ISSUE TITLE
File History of directories "messed up"

### ISSUE THREAD

**Issue by TobiX** [gitextensions/gitextensions#6614]
## Current behaviour

When displaying the history of a directory, Git extensions breaks the history graph into random, disconnected "branches", even if the history is linear.

## Expected behaviour

I expect the history graph of a directory to only show the changes affecting that directory (okay) and visualize commits with their proper relationship (not okay).

## Steps to reproduce

1. Check out a project with subdirectories
2. Right-click on any subdirectory
3. Choose "Git Extensions" ▶️ "File history"

## Screenshots

Here is a simple example right from the `master` of this project (using subdirectory `GitExtensions`, HEAD is at `v3.0.2-709-gb484a95a8`):

![grafik](https://user-images.githubusercontent.com/78534/58022634-23afe780-7b0e-11e9-9e35-f4fb73e68cde.png)

The same using git itself:

![grafik](https://user-images.githubusercontent.com/78534/58022726-5a85fd80-7b0e-11e9-93d5-73963997e6b2.png)

## Did this work in previous version of GitExtensions

Not sure, sorry.

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3394.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
I think it's a duplicate of #5454 and this comment explained a little why it's difficult to fix it: https://github.com/gitextensions/gitextensions/issues/5454#issuecomment-422979610

**Comment by TobiX** [comment]
Yes. Yes, it is. Sorry for the noise.

**Comment by pmiossec** [comment]
No problem. Your issue was better described 👍 

I have added the link as a cross reference.
