### ISSUE TITLE
Show columns header in revisions grid

### ISSUE THREAD

**Issue by antis81** [gitextensions/gitextensions#664]
Hi guys,
still can't see the column headers in V 2.25. Please enable it again.

**Comment by RussKie** [comment]
/cc: @drewnoakes @gerhardol is this something we want to enable or allow users to configure?

**Comment by gerhardol** [comment]
Column headers are useful for sorting (not applicable here) and to give information about contents. The last is applicable but I prefer to not have a header taking up space.

**Comment by vbjay** [comment]
We could allow reordering and contextmenu that allows the user to show/hide columns.

**Comment by gerhardol** [comment]
> We could allow reordering and contextmenu that allows the user to show/hide columns.

drews-v3 allows for columns to be added removed (not reordering at the current state).

**Comment by vbjay** [comment]
Exactly.  Showing or at least optionaly allowing column headers would allow
this.
