### ISSUE TITLE
OutOfMemoryException after network outage

### ISSUE THREAD

**Issue by drauch** [gitextensions/gitextensions#6642]
## Current behaviour

Whenever our company network fails, some time later GitExtensions dies with an OutOfMemoryException:

![image](https://user-images.githubusercontent.com/1516470/58232871-f005d500-7d3a-11e9-8009-f4a173ab8b78.png)

## Expected behaviour

No OutOfMemoryExceptions.

## Did this work in previous version of GitExtensions

This problem occurs in 3.0 and 3.1

## Environment

- GitExtensions version: 3.1.0.5877
- GIT version: 2.20.0.windows.1
- OS version: Windows 10
- .NET version: 4.7.2

**Comment by pmiossec** [comment]
Thanks for the report.

But what is particularly useful to understand the problem is the stack trace (instead of a screenshot 😢).

So, the next time, prefer clicking on the 'send ans quit' button (after filling the description field 👍) .

**Comment by RussKie** [comment]
Without the stack trace there is little we can do.
Once you get more info please ping us back and we'll re-open the issue.

**Comment by RussKie** [comment]
Duplicate of #3646
