### ISSUE TITLE
Permission denied exception accessing ProgramData/Git/config

### ISSUE THREAD

**Issue by PLN** [gitextensions/gitextensions#6646]
## Current behaviour

An exception occurs when unable to access the windows-wide Git config due to a permission denied error. C:\ProgramData\Git\config exists, but my user account cannot access it by default. This may be due to that machine being a Windows Server. Once access to C:\ProgramData has been granted, the exception no longer occurs.

## Expected behaviour

Maybe add a check to see if the config can be accessed with a suggestion to open the directory in explorer to fix the permissions?

## Steps to reproduce

Removing the permission to access C:\ProgramData causes the exception to reappear for me.

## Error Details
```
System.FormatException: Unable to parse object ID "fatal: unable to access 'C:\ProgramData/Git/config': Permission denied".
   at GitUIPluginInterfaces.ObjectId.Parse(String s)
   at GitCommands.GitModule.GetCurrentCheckout()
   at GitUI.RevisionGridControl.ForceRefreshRevisions()
   at GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I just installed both GitExtensions and Git. On the first time opening an existing repository it gave me the configuration screen. Subsequent openings give this exception. After navigating to C:\ProgramData\Git with explorer (and saying yes to the security prompt to give myself access to the ProgramData directory) the issue seems to be resolved.
This is a Windows 2012 R2 Server installation.

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
This isn't a problem with Git Extensions but rather with the way you chose to install it or configure your environment.

The fix could involve displaying a user-friendly(-ier) error box for user to act upon. The app should not crash.
I think it would also fix #6632 and #6640

On a side note, I don't believe one should be putting configs in ProgramFiles or ProgramData folders

Whilst the [doc](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-folderlocations-programdata) suggests it should be ok to use the folder, it also says it is not recommended.
