### ISSUE TITLE
System.MissingMethodException: Method 'Array.Empty' not found.  on startup (via terminal)

### ISSUE THREAD

**Issue by nuriyevn** [gitextensions/gitextensions#6653]
## Current behaviour
Does n't open application when I double click on it.
Also doesn't open the application when I issue  @sh gitext.sh@ on terminal
following output:
Raising 
System.MissingMethodException: Method 'Array.Empty' not found.
  at GitUI.RevisionGrid.ForceRefreshRevisions () <0x406e0490 + 0x0010f> in <filename unknown>:0

## Expected behaviour
Starting  gitext  gui application

## Steps to reproduce
follow installation wiki till the step when you execute.

## Did this work in previous version of GitExtensions
I don't know

## Environment
ubuntu  16.04

- GitExtensions version: 2.51.05
- GIT version: 2/7/4
- OS version: ubuntu 16.04.1
- .NET version:  4.2.1

**Comment by nuriyevn** [comment]
I have checked with Git Ext 2.49 version - it starts as expected.

**Comment by RussKie** [comment]
You need Mono 5.2+

**Comment by nuriyevn** [comment]
I hope upgrading mono will also fix a new issue: when I commit, in an appeared new window I have an infinite  "loading bar ...".

**Comment by nuriyevn** [comment]
If it is not fixed I'll open new issue :)

**Comment by RussKie** [comment]
Actually I was wrong, it has to be Mono 5.0+, however 5.14+ is recommended
https://github.com/gitextensions/gitextensions#version-25x



> If it is not fixed I'll open new issue :)

A PR is also highly appreciated (to the last of release/2.5x branches), the core team is all on Windows

**Comment by nuriyevn** [comment]
5.10.1.20
Both issues are gone.
Going to commit, let's see what happened.

Well,  5.10  that's what installed when I issue "apt install mono-devel"

> A PR is also highly appreciated (to the last of release/2.5x branches), the core team is all on Windows
oh, I am afraid I am not a C# guy, rather C++. I don't have even C# an IDE.
if someone will sponsor my labor or there will be only some small bugfix needed, may think about it.
I use GE on my windows host and it would be nice if it has worked on Linux as flawlessly as it does on Windows :)

**Comment by RussKie** [comment]
https://www.mono-project.com/docs/about-mono/releases/5.14.0/

https://www.mono-project.com/docs/about-mono/releases/5.14.0/#class-libraries
![image](https://user-images.githubusercontent.com/4403806/58297085-b657cb80-7e19-11e9-8eac-ebc4e108bc1a.png)


> if someone will sponsor my labor or there will be only some small bugfix needed, may think about it.

hear hear :)
we are all volunteers here

**Comment by RussKie** [comment]
> I use GE on my windows host and it would be nice if it has worked on Linux as flawlessly as it does on Windows :)

Same here, it was a difficult but necessary decision to cut Mono off...

**Comment by nuriyevn** [comment]
no further issues so far  ;)
thanks for the assistance.

**Comment by nuriyevn** [comment]
> it was a difficult but necessary decision to cut Mono off...

I am not familiar with mono technology but running an .exe from Linux - it's a kind of, you know, desperation, so I would make  the project  with C++ with cmake when it comes to normal cross-platform, but that's me, don't listen ;)
It might be another gitext then, not the one we know and like today...

**Comment by RussKie** [comment]
Mono *WinForms* was the issue.
If you search, you find discussions about it

**Comment by nuriyevn** [comment]
oh, https://github.com/gitextensions/gitextensions/issues/4308
I see. (though I have not read all the thread)
Are you going to stop supporting Linux support by cutting mono or you are going to implement cross-platform in another way? :)

**Comment by RussKie** [comment]
We essentially have in v3, and no immediate plans to resurrect the support
unless there is an easy way to do so...

Perhaps one of the future .NET versions will have something in store...

**Comment by gerhardol** [comment]
Someone actually using mono could maintain 2.x too
