### ISSUE TITLE
Commit Dialog: Unexpected refresh of working dir panel after focus on staged files panel

### ISSUE THREAD

**Issue by bizoo** [gitextensions/gitextensions#6655]
## Current behaviour

On the Commit dialog, when you put the focus (click) the staged files panel and after put the focus on the working dir panel, that trigger a refresh on the working dir panel that scroll the panel to the first item.

## Expected behaviour

The working dir panel must stay on it current state, at least when nothing was done to the staged files panel.

## Steps to reproduce

1. Open a commit dialog with some files in the working dir (enough to display a scrollbar).
2. Scroll the working dir panel to the last file and select it.
3. Click the staged files panel to put the focus on it.
4. Try to click the penultimate file in the working dir panel.
5. Working dir panel scroll back to the first item and the current item selected is not the one you clicked.

## Did this work in previous version of GitExtensions

I think this issue is there from a very long time (forever ?).

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by bizoo** [comment]
Resolved in the latest version.

- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Thank you for the follow up
