### ISSUE TITLE
Commit message completion : propose USER's last commits

### ISSUE THREAD

**Issue by ghost** [gitextensions/gitextensions#6661]
## Feature description

Actually, in commit view, when we click on "Commit message", we have **REPO**'s last commits proposed.

But this is very rare when we need to reuse commit message coming from another user.

We should also propose last **USER**'s commits.

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3260.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
I understand that you could be tempted to do everything using "La rache" method (nice avatar!) but there is a template to follow to report an issue or a feature.

Could you please update your issue to follow one of them?

**Comment by michelsaumon** [comment]
> 
> 
> I understand that you could be tempted to do everything using "La rache" method (nice avatar!) but there is a template to follow to report an issue or a feature.
> 
> Could you please update your issue to follow one of them?

Is it ok for you ?
;)

**Comment by michelsaumon** [comment]
> 
> 
> I understand that you could be tempted to do everything using "La rache" method (nice avatar!) but there is a template to follow to report an issue or a feature.
> 
> Could you please update your issue to follow one of them?

Is it ok for you ?
;)

**Comment by pmiossec** [comment]
A lot better ;)

**Comment by pmiossec** [comment]
Closing as I think fixed years ago by #7337
