### ISSUE TITLE
Test integration with probot

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#6669]
test, ignore

## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by RussKie** [comment]
still wip, need to tweak the code to read **all** issues as opposed to the last page

@gitextensions/git-extensions-source what do you reckon? we can tweak the message somewhat, if desired.
https://github.com/RussKie/potential-duplicates-bot/blob/master/src/config.js#L26-L29

**Comment by RussKie** [comment]
We can render it like so, for example:

Potential duplicates:
* [![#6660](https://img.myrandomwebs.com/github/issues-state/gitextensions/gitextensions/6660.svg)](https://github.com/gitextensions/gitextensions/issues/6660) (72%)
* [![#6658](https://img.myrandomwebs.com/github/issues-state/gitextensions/gitextensions/6658.svg)](https://github.com/gitextensions/gitextensions/issues/6658) (72%)
* [![#6656](https://img.myrandomwebs.com/github/issues-state/gitextensions/gitextensions/6656.svg)](https://github.com/gitextensions/gitextensions/issues/6656) (72%)
* [![#6647](https://img.myrandomwebs.com/github/issues-state/gitextensions/gitextensions/6647.svg)](https://github.com/gitextensions/gitextensions/issues/6647) (72%)

**Comment by mast-eu** [comment]
Great idea. For sure very useful for keeping up with all the duplicates from NBug.

A few questions pop to my mind:
1. Is the bot scanning through both open and closed issues?
2. I had a glimpse at the code. As far as I figured, you are checking the similarity of titles. This should be fine. But how come that identical titles have a similarity of 72% and not 100%?

With identical titles, I would prefer to have a more compact presentation. For example:
```
[#6660], [#6658], [#6656], [#6647], [#6643], [...] 
[NBug] Remote URLs should appear in pairs.
```

**Comment by mast-eu** [comment]
Ok, now I see it. It's 72% similarity between "**[NBug]** Remote URLs should appear in pairs." and "**[TEST integration]** Remote URLs should appear in pairs."
It was 100% in https://github.com/gitextensions/gitextensions/issues/6669#issuecomment-496002327, because you edited the title, so it matched.

**Comment by RussKie** [comment]
> 1. Is the bot scanning through both open and closed issues?

Yes, It gets all issues.
I just need to make it to scan **all** issues instead of a subset

> I would prefer to have a more compact presentation.

It is probably doable if the match is 100%, in other cases it could be that two different titles result in the same similarity value

We can build our own badges, if necessary - https://shields.io/category/issue-tracking
For instance: `https://img.shields.io/badge/Similarity%2072%25-%5BNBug%5D%20Remote%20URLs%20should%20appear%20in%20pairs.%20-red.svg`
[![#6669](https://img.shields.io/badge/Similarity%2072%25-%5BTEST%20integration%5D%20Remote%20URLs%20should%20appear%20in%20pairs.-blueviolet.svg)](https://github.com/gitextensions/gitextensions/issues/6669)
[![#6660](https://img.shields.io/badge/Similarity%20100%25-%5BNBug%5D%20Remote%20URLs%20should%20appear%20in%20pairs.%20-red.svg)](https://github.com/gitextensions/gitextensions/issues/6660)
[![#6658](https://img.shields.io/badge/Similarity%20100%25-%5BNBug%5D%20Remote%20URLs%20should%20appear%20in%20pairs.%20-green.svg)](https://github.com/gitextensions/gitextensions/issues/6658)

We could also check the state of each item, and colour-code them, e.g. purple - merged, red - closed, yellow - open

**Comment by RussKie** [comment]
^^ This looks cool 😃

**Comment by pmiossec** [comment]
There are 2 others things that we could but I don't know if it's easy to do.

Order in ascending because there is more chance that the discussion is in the older issue.

Display the number of messages in each issue to spot in which issue is more likely the discussion.

**Comment by RussKie** [comment]
The order is probably not too difficult to do, the other is probably doable as well...
I have to work on my l33t js skillz 😆

**Comment by RussKie** [comment]
alright, the first one is done

**Comment by pmiossec** [comment]
I saw it. Well done!

**Comment by RussKie** [comment]
Apologies for the spam... 😊 

How's this ⬆️ ?

**Comment by pmiossec** [comment]
Awesome! We immediately know which one to open if needed.

**Comment by RussKie** [comment]
For any more tweaks please feel free to raise issues and submit PRs to https://github.com/RussKie/potential-duplicates-bot
