### ISSUE TITLE
Check for updates to download / install instead of opening default browser

### ISSUE THREAD

**Issue by Johno-ACSLive** [gitextensions/gitextensions#6679]
## Feature description

Currently when checking for updates, the download now button launches the direct download URL via process start which means the OS will open in the default browser.

A much better user experience would be to download the MSI to a temporary location, launch the MSI with appropriate parameters and then shut down Git Extensions to allow the MSI to upgrade (otherwise the install process will request to stop Git Extensions if it is still running).

We could use completely silent parameters but we should probably use /qb as it provides basic installation progress and because unfortunately the MSI will request to kill explorer.exe (hopefully this can be changed at some point as well) if the explorer context menu is enabled.

I have already got some code from my own software that does a similar thing (its very basic) that I adapted to a cloned version of Git Extensions and it seems to work just as well.

The code in my software auto launches the app after upgrade, however, I have not added that to the MSI parameters as I don't have the WIX installer files to check the current parameters for the MSI installer. I could use other tools to check the existing MSI but this is a minor change to add in any case.

Posting an issue here for discussion to see if anyone is interested in this small feature enhancement and sort out the details of how this feature update would work.

Happy to submit a PR or provide the code changes for existing maintainers to make based on the discussion outcomes.

## Environment

- Git Extensions 3.0.0
- Build fad15958a3d8ea5c22cf84a41310931804e50680 (Dirty)
- Git 2.17.1.windows.2 (recommended: 2.20.1 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 240dpi (250% scaling)

**Comment by pmiossec** [comment]
>A much better user experience would be to download the MSI to a temporary location, launch the MSI with appropriate parameters and then shut down Git Extensions to allow the MSI to upgrade (otherwise the install process will request to stop Git Extensions if it is still running).

We are always happy to have a better user experience 😉 

>Happy to submit a PR or provide the code changes for existing maintainers to make based on the discussion outcomes.

It's always easier to discuss around some code changes that way, that's sometimes prevent some misunderstandings.

So, if you already have a branch with the changes done, we will be happy if you could do your PR as soon as possible. Just prefix the title with "WIP:" so that every one is aware that it's not finished.

**Comment by RussKie** [comment]
> Happy to submit a PR or provide the code changes for existing maintainers to make based on the discussion outcomes.

As @pmiossec said, contributions are quite welcome.
MSI is somewhat arcane art, so if you can help with it - it would be great.

There are [a few tickets in our backlog](https://github.com/gitextensions/gitextensions/labels/area%3A%20installer) related to the installer too 😉

**Comment by Johno-ACSLive** [comment]
Great, I'll get a branch and PR going tomorrow.

@RussKie it sure is, never used Wix but it shouldn't be too difficult. I've used various other packaging tools (Advanced Installer is the one I use for software I develop).

I'll check out the backlog and see what I can do :)

**Comment by RussKie** [comment]
I have a limited understanding of Wix after playing with it in  #6522.

**Comment by Johno-ACSLive** [comment]
I added LAUNCH=1 to the MSI parameters (the MSI will currently ignore the parameter until it is supported), I did try building the MSI however I cannot get it to build (I've installed Wix Build Tools and the extension for VS 2017). I do have both VS 2017 and VS 2019 installed so perhaps the build scripts don't like that combination.

Not a fan of Wix, I'd rather manually build an MSI using InstEd 😃 

All good though, let's discuss the current proposed change first and in the mean time I'll investigate further why I can't build the installer.

I've submitted a PR prefixed with WIP, this is the first time contributing to a large repo (other than my own repo's). Let me know if I've missed something so I can do it properly 😄

**Comment by RussKie** [comment]
If you raise a new issue with logs we can try to help with the build issue

**Comment by Johno-ACSLive** [comment]
Fixed, problem was a bug in hMSBuild.bat. It was finding VS 2019 but the location of the executable is different and it could not launch MSBuild.exe. I downloaded v2.1 from GitHub and it's finding VS 2017 with the correct location.

MSI building now, testing the changes for this work as expected. If all goes well, shall I submit a new PR for the installer change?

**Comment by Johno-ACSLive** [comment]
Great, by default the MSI will not auto launch Git Extensions (if MSI is installing or upgrading). If someone sets the MSI parameter LAUNCH=1 then Git Extensions will launch after install or upgrade is complete.

If upgrading via the proposed changes built into Git Extensions (checking for updates), we will auto launch Git Extensions after upgrade is complete by setting the MSI parameter described above.

**Comment by Johno-ACSLive** [comment]
I've commited the Wix change required for the LAUNCH property to work when the MSI is built.

That's the last of the changes unless I've missed something 😄

**Comment by Johno-ACSLive** [comment]
Refactor #6738
