### ISSUE TITLE
[NBug] InvalidArgument=Value of '0' is not valid for 'index'.Par...

### ISSUE THREAD

**Issue by justanotheruser** [gitextensions/gitextensions#6680]
## Current behaviour
GitExtension crashes and suggests to create this issue

## Expected behaviour
1. Not to crash
2. Show commits that reflog commad shows (sometimes it works like this).

## Steps to reproduce
Enter --reflog into 'Branches' list
Press Enter

## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at System.Windows.Forms.ComboBox.get_Text()
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
>Enter --reflog into 'Branches' list

Do you also have a crash when you use the reflog feature implemented in
Gitextensions using the 'View' menu, then 'Show reflog references'?

>
>

**Comment by gerhardol** [comment]
Cannot reproduce (a little info in #6782 as well). Tried some combinations including linux repo and repos without branches. There is something with the timing here, like entering info before the list is populated.

The duplicates may be for other combo boxed than Browse - branchFilter (but the two with info is for this box), there are only about 20 in total in use.

**Comment by bansan85** [comment]
## Steps to reproduce

I'm not sure :
When I 'B' (blame) a file, ComboBox "Branches" is filled with commit.
When I edit the text, I have suggestion in the list. A first press, the list is filled. A next press, the list is empty.
When list is empty, press Enter.
Then click on the button to show list.
Then crash.


## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=La valeur '0' n'est pas valide pour 'index'.
Nom du paramètre : index
   à System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   à System.Windows.Forms.ComboBox.get_Text()
   à System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   à System.Windows.Forms.ComboBox.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```


## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
I successfully reproduced it (thanks to #7204):

- Copy / paste in the `Branches` combobox a text invalid that filter all the branches => the dropdown is open and empty
- Press 'Enter' => the dropdown is closed
- Reopen the dropdown => crash

**Comment by RussKie** [comment]
That dropdown has been a long standing issue 🤕

**Comment by pmiossec** [comment]
I played a little with this and I don't see an easy way to fix it...
Except if we prevent the list to be empty by not applying the filter when no results are found (i.e. in this case, we display the initial list not filtered).

Or we display a placeholder "<No branch found>".

Which one do you prefer. I prefer the second one...
