### ISSUE TITLE
Open local repository: Open repo at once after selection in Browse Folder dialog

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6691]
## Feature description

The `Open local repository` dialog should automatically open the repo after a folder has been selected in the `Select folder` dialog because the user cannot and does not want to do anything else in this dialog.

hit `Ctrl-O`, click `Browse...`, select a folder and confirm

![grafik](https://user-images.githubusercontent.com/36601201/58547045-f4346580-8206-11e9-8f82-69140974c1ea.png)

### Current behavior

The button `Open` must be pressed manually.

### Expected behavior

The dialog shall be closed and the selected repo shall be opened.

## Environment

- Git Extensions 3.2.0
- Build 095d915ebcc68c28fa4347e22b0e2b84fdc99cad
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I can understand the point where this FR is coming from. However, if implemented, it would provide a quite disjointed UX by which if a user selects a folder via the "Browse" button the dialog would close itself, and if a repo is typed or selected via the dropdown - it wouldn't...

**Comment by gerhardol** [comment]
What should be changed is that Browse is still selected by Enter.
Open automatically is also autoclosing a prev dialog, which I would not expect.

**Comment by mstv** [comment]
I stumble upon this every time: I wonder why nothing happens after selecting a folder.

Why do we need this intermediate dialog at all?
Isn't the combobox a duplicate of the one in the toolbar?
In most applications, `Ctrl+O` opens a `Select Folder/File` dialog directly.

**Comment by gerhardol** [comment]
I usually type the path in the combobox, it has autocompletion

**Comment by mstv** [comment]
I guess it is not better than in the Windows File/Folder dialog.

**Comment by RussKie** [comment]
Let's step back and consider from another angle - do we need to rethink
this dialog completely?

Personally I rarely use it, I typically open repos via the shell extension,
the VS extension or the recent list...

**Comment by mstv** [comment]
(My recent list was empty due to the switch to Win10.)

> Let's step back and consider from another angle - do we need to rethink this dialog completely?

Yes, I impeach it at all. `Ctrl+O` should directly open the `Select Folder` dialog. There's a combobox with the recent list in the toolbar already.

**Comment by gerhardol** [comment]
I oppose removing the current way, it works much better than typing in the "explorer bar".
This is my common way to open repos. The other is a command line (Cygwin) alias, hardly ever other ways.
It is possible to have two ways too, but that would be confusing.

**Comment by pmiossec** [comment]
I also give you my point of view...😁

I think that this dialog should be removed and all the controls moved to the dashboard.

That way, there is only one place in GE where to open a repository, the dashboard, that is displayed when doing 'ctrl+o' (except for the quick access with the combo box, indeed) .

At best, you find your repository quickly in the recent list. Or you could use the textbox displayed at the top to find it.

And, yes, I agree with the initial point of view of @mstv, if we change the ergonomic to introduce a 3rd way to open a repository, we could instead of 'Browse...', move the button elsewhere and name it something like 'Select the repo from filesystem...'. 

That way, that makes sense to open the repository directly.

**Comment by gerhardol** [comment]
Recent and Dashboard is not of much use for me.
I work with about 15 superrepos where each have 5-15 submodules and the list is too long, too much maintenance with categories.
#4942 would improve
Just typing (and manipulating current path) is faster.

**Comment by mstv** [comment]
> However, if implemented, it would provide a quite disjointed UX by which if a user selects a folder via the "Browse" button the dialog would close itself, and if a repo is typed or selected via the dropdown - it wouldn't...

I do not expect and would be surprised if an action was triggered by selecting a combobox item.
But what do you expect should happen when you have selected a repo in the open dialog?

This feature request has low importance for me. You can reject it if you think the resulting UX would be too disjointed.

**Comment by RussKie** [comment]
There's one more button (the arrow up) - what does it do? Would we degrade
the UX removing it?

**Comment by pmiossec** [comment]
This button is to easily jump to parent folder and more especially trigger
the Auto complete with filesystem sub-folders.

We could perhaps tweak a little more the control to better trigger it and
use 'ctrl+del' to move to parent folder and remove the button (but add a
label to inform user)

**Comment by mstv** [comment]
`Ctrl+Backspace` moves to the parent folder, both in the dialog's combobox and in the Windows Select Folder dialog as well as auto-completion.

**Comment by mstv** [comment]
> However, if implemented, it would provide a quite disjointed UX by which if a user selects a folder via the "Browse" button the dialog would close itself, and if a repo is typed or selected via the dropdown - it wouldn't...

Especially when testing portable builds, this additional click is a constant annoyance to me.
Your symmetry argument does not outbalance enough IMO.

**Comment by gerhardol** [comment]
There could be two dialogs. If the current editor opens with Ctrl-O, I am fine with a "pure" filepicker.

**Comment by mstv** [comment]
> There could be two dialogs. If the current editor opens with Ctrl-O, I am fine with a "pure" filepicker.

Rather not: `Ctrl+O` and no possibility to open a file dialog...

> Especially when testing **portable builds**, this additional click is a constant annoyance to me.
Your symmetry argument does not outbalance enough IMO.

The additional click is not the problem but the time to come to realize that another click is required.

Further arguments?

**Comment by mstv** [comment]
In addition, what do you think about populating the dashboard of portable builds on the initial run -- with the recent repos of the local installation?

**Comment by pmiossec** [comment]
I also think that it worth an exception on UX practicies

>However, if implemented, it would provide a quite disjointed UX by which if a user selects a folder via the "Browse" button the dialog would close itself, and if a repo is typed or selected via the dropdown - it wouldn't...

I'm pretty sure that no users of GitExtensions will notice it because 100% of the users wants to open the repository after selecting the folder. I think that you notice UX glitches when the UI don't do want you want to achieve and you begin to think how it should have been done.

If we really want to communicate the intention maybe we could improve it by moving it next to "Open" and rename the button to something like "Open from folder..."

**Comment by RussKie** [comment]
> In addition, what do you think about populating the dashboard of portable builds on the initial run -- with the recent repos of the local installation?

I think this is an interesting idea 👍 

> Further arguments?

You win! 😀
