### ISSUE TITLE
Crash when git is uninstalled

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#6692]
## Current behaviour
When Git is uninstalled GitExtensions crash.

## Expected behaviour
No crash, just message box about missing Git.

## Steps to reproduce
Uninstall Git SCM while Git Extensions is opened.

## Environment
- GitExtensions version: 3.1
- GIT version: 2.21
- OS version: 10
- .NET version: 4.8

**Comment by RussKie** [comment]
Out of curiosity, why would you uninstall git midway?

**Comment by NN---** [comment]
Upgraded it to newer version .

**Comment by RussKie** [comment]
A fix could involve showing the same dialog we show when we start the app and git is missing:
![image](https://user-images.githubusercontent.com/4403806/58613035-dd217080-82f7-11e9-91f3-a21df33e041a.png)

**Comment by illfated** [comment]
Looks like a practical error message, it would definitely be useful for users who don't know enough about Git yet.
Thanks for the chuckle -- the closest analogy I could come up with for uninstalling Git while GE is running is "remove the fuel system while driving a vehicle". 😄

**Comment by RussKie** [comment]
LOL, more like the engine while driving

**Comment by wischi-chr** [comment]
Hi guys. I'd like to give that a go and check in first to discuss if they way I would solve that is any good.

The dialog that is used on startup is basically used to fail fast. If git isn't found not even the main (browse) Window loads, so at the moment basically everything assumes git just being there. Rewriting everything to deal with the fact that it might not be would probably be a massive amount of work and not worth it for this edge case.

IMO the only reasonable way to handle this without crashing would be to suspend all work until git is found or the user decides to close gitextensions. We could achieve that for example by pausing the main ui thread with a modal dialog - for example the same or very similar dialog to the startup dialog.

I still have to check if there are things happening on separate threads (file watcher, etc) that use the git cli - there might be a few more edge cases to solve there.

Please let me know if that would that be a viable solution in your opinion?

**Comment by illfated** [comment]
Sounds reasonable to me, but I am not a team member.

**Comment by gerhardol** [comment]
There are some suggested changes to handle executable failures, see #8358
The error message is hopefully a more clear

> but I am not a team member.

PRs and code reviews are welcome from all users

**Comment by illfated** [comment]
Sure, fair enough. I meant more like "I am not familiar enough with coding or Git Extensions well enough to speak for what the team prefers". 😉

**Comment by RussKie** [comment]
To be honest, this specific use case to me feels very artificial - "my car stopped and won't run because I pulled the motor out...".
Looks like I already said it - https://github.com/gitextensions/gitextensions/issues/6692#issuecomment-497595163.

Personally I'd rather close the ticket, it doesn't feel worthy of the effort.

**Comment by wischi-chr** [comment]
fair enough, your call ^^

**Comment by illfated** [comment]
Now that you mention it, it does look quite like you say, because both software install and uninstall procedures usually states that you should close other applications when installing or uninstalling any application.

Just to add my last bit to the ridiculousness of the described situation, the OP statement "Expected behaviour: No crash, just message box about missing Git." makes me visualize Git Extensions getting a "sad face" 😢 while saying "I miss Git. I really do."

**Comment by vbjay** [comment]
Lol. Needs a sonnet like Shakespeare about once was there but now is gone. I miss it so and wish it were back amongst my midst and so on.

**Comment by gerhardol** [comment]
#8582 exists to change this, I do not want to see time wasted on this again

Related to https://github.com/gitextensions/gitextensions/issues/6692#issuecomment-710881897
_This change is like allowing the user to hot swap the engine while running, as long as they do not touch any controls,
or they have changed specific addons._
