### ISSUE TITLE
Settings path has changed

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6696]
## Current behaviour

I wondered where my settings were gone.

Settings are stored in "c:\Users\<me>\AppData\Roaming\Git Extensions\Git Extensions\GitExtensions.settings", i.e. "Git Extensions" folders with space.

Is this change intended?

## Previous behaviour

Settings were stored in "c:\Users\<me>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings", i.e. "GitExtensions" folders without space.

## Steps to reproduce

update GE

## Did this work in previous version of GitExtensions

haven't checked, at least 3.0

## Environment

- Git Extensions 3.2.0
- Build 095d915ebcc68c28fa4347e22b0e2b84fdc99cad
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
This is due to fce96e3bbf3fe03465d9d4cb1755a5e4fa9037a6
Name->path was changed when the version was bumped to 3.2
Someone pushed changes to master that was not reviewed...

**Comment by mstv** [comment]
Shouldn't the change at line 5 in https://github.com/gitextensions/gitextensions/commit/fce96e3bbf3fe03465d9d4cb1755a5e4fa9037a6#diff-dcdb4204d29459706b6477f46367419b be reverted, too?

**Comment by gerhardol** [comment]
> Shouldn't the change at line 5

Not affecting the setting but should be changed for consistency (force push to PR).

**Comment by RussKie** [comment]
It was me 😎

We are *Git Extensions*, so this change was intended. We shouldn't undo it.

We need the path construction routine

**Comment by gerhardol** [comment]
If the name must change, then 3.2.0 should implement migrating of existing settings to the new path.

**Comment by philippeflorent** [comment]
"git extensions" gets created but it is empty
