### ISSUE TITLE
Filenames starting with a space are not handled correctly

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6723]
## Current behaviour

The contents of a new file whose name starts with a space is not displayed in the FormCommit.
Such a file cannot be staged using GE.

## Expected behaviour

If a file cannot be read, an error message is displayed instead of an empty file!
GE can handle every file existing in the filesystem.

## Steps to reproduce

(I needed an example for a new file.)
- select `.editorconfig` in your favorite file manager
- hit `Ctrl+C`, `Ctrl+V`
- open FormCommit
- select the file " - Kopie.editorconfig" which is shown without the leading space
- stage it

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/58735358-75a01980-83fa-11e9-92cf-58f36768cdfa.png)

## Did this work in previous version of GitExtensions

don't know, at least not in 2.51.05

## Environment

- Git Extensions 3.2.0
- Build ef3cd4d8f0e4a952dee6560a64f5ee4be4725a37
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

## Diagnostics

git check-attr -z diff text crlf eol -- "- Kopie.editorconfig"

**Comment by gerhardol** [comment]
@mstv Any comments?

**Comment by RussKie** [comment]
Is it because we are missing `"`?

**Comment by gerhardol** [comment]
> Is it because we are missing "?

Trim and Uri(), see PR
