### ISSUE TITLE
ArgumentOutOfRangeException [not] selecting a language on first start

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6726]
## Current behaviour / STR

Start a [portable] build for the first time.
Confirm the language selection with `Enter`.
Exception although `English` seems to be selected.

![grafik](https://user-images.githubusercontent.com/36601201/58739176-3cbb7100-8409-11e9-9bc8-0b0d5c323dd0.png)

Not a duplicate of #6680.

## Expected behaviour

English does not need to be clicked or reselected by moving around with cursor keys.

## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=Value mit dem Wert 0 ist für index ungültig.
Parametername: index
   bei System.Windows.Forms.ListView.SelectedListViewItemCollection.get_Item(Int32 index)
   bei GitUI.CommandsDialogs.SettingsDialog.Pages.FormChooseTranslation.lvTranslations_ItemActivate(Object sender, EventArgs e)
   bei System.Windows.Forms.ListView.OnItemActivate(EventArgs e)
   bei System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   bei System.Windows.Forms.ListView.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.0.5989
- Build c992852437f8ef975388a34002d321c72620df85 (Dirty)
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
> :warning: Review existing issues to see whether someone else has already reported your issue.

Unfortunately, the "related issues" plugin is not triggered unless the title is changed, which is pre-filled in case of NBug reports.

**Comment by RussKie** [comment]
The bot is only looking at NBug reports
https://github.com/RussKie/potential-duplicates-bot/blob/master/src/index.js#L196
