### ISSUE TITLE
New script variables for branch and repository name

### ISSUE THREAD

**Issue by LukeOwlclaw** [gitextensions/gitextensions#6736]
## Feature description

Currently there is no way for scripts to get the second part of remote repository variables `{cRemoteBranch}` and `{sRemoteBranch}` (the *remote repo branch name*, ie. everything after "/" -- e.g. with `{cRemoteBranch}`=`UserName/GitRepo`) it is not possible to get `GitRepo`).

Further, there is no way for scripts to get the name of the current repository, is there? 

I propose to add following variables:

```
{cRemoteBranchName}
{sRemoteBranchName}
{RepoName}
```

These variables would allow calling a Jenkins build:

    http://jenkins:8080/job/{RepoName}/buildWithParameters?token=TOKEN-NAME&BranchName=origin/{sRemoteBranchName}

And also to send a PR to Gitea:

    https://gitea:3000{cDefaultRemotePathFromUrl}/compare/master...{sRemote}:{sRemoteBranchName}

(Note that ":" is used a separator for the remote branch)

## Environment

- GitExtensions version: 3.1.1

**Comment by RussKie** [comment]
@mstv I think this is right up your alley 😉 

@LukeOwlclaw could you please provide few examples in a form:
* given
* expected

**Comment by LukeOwlclaw** [comment]
| Given (variable name) | Expected value (description)                          | Expected value (sample according to screenshot) |
|:-----------------------|:-------------------------------------------------------|:-------------------------------------------------|
| ``{cRemoteBranchName}``   | Everything after last "/" of value of ``{cRemoteBranch}`` (see parentheses in window title) | master                                          |
| ``{sRemoteBranchName}``   | Everything after last "/" of value of ``{sRemoteBranch}`` | Better-archivarius-bot-wording                  |
| ``{RepoName}``            | Name of repository (see first part of window title)                 | gitextensions                                   |

![image](https://user-images.githubusercontent.com/2737900/58853691-5a076e00-869b-11e9-8653-ee349574dc70.png)

**Comment by gerhardol** [comment]
{cRepoShortName} already exists
https://github.com/gitextensions/gitextensions/commit/84034a42bb7e8020cd3399ba6ee174f98adf2fe6

For the other two, is the description really what you want?
For branches like origin/feature/my-change I would expect just origin/ to be dropped.

**Comment by LukeOwlclaw** [comment]
@gerhardol Oh right, I did not think about multiple "/". It should be the first one to be considered. I just changed the table above.

About {cRepoShortName}: It does not work for me. It does not get replaced:
![image](https://user-images.githubusercontent.com/2737900/58859519-31d33b80-86aa-11e9-94f7-5ebcfafdb922.png)

I am talking about script variables. I believe that the concerning code is https://github.com/gitextensions/gitextensions/blob/master/GitUI/Script/ScriptRunner.cs. Your link points to the GitCommands (sub)project. Are we talking about different things?

**Comment by gerhardol** [comment]
> Are we talking about different things?

Slightly...
You want {cRepoShortName} to be supported in ScriptRunner too

**Comment by LukeOwlclaw** [comment]
Btw, what is "GitCommands"? Must be something about scripting, right? I didn't find anything about it in the UI nor in the [docs](https://www.google.com/search?q=site%3Ahttps%3A%2F%2Fgit-extensions-documentation.readthedocs.io%2F+gitcommands).

**Comment by mstv** [comment]
@LukeOwlclaw, test the [development build](https://ci.appveyor.com/api/buildjobs/w7jpjd8rpoxn0ypc/artifacts/Setup%2FGitExtensions-Portable-3.2.0.846.zip), please.
