### ISSUE TITLE
Refactor "Check for updates" dialog

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#6738]
## Feature description

The current dialog that checks for new versions looks as follows:
![image](https://user-images.githubusercontent.com/45373169/58453677-62255200-815f-11e9-97b9-fba31b84890c.png)

As discussed in https://github.com/gitextensions/gitextensions/pull/6682#issuecomment-498228972 we need to uplift the dialog to the following:

```
Check for update
-------------------

[ progress ... ]

<Show Changelog>    [Download and install] <Download only>
```

- `<xx>` = linklabel
- `[xxx]` = button
- remove "Close" button as it is irrelevant

This will allow users to automatically download and install updates (thanks to #6682).
For those users who may be unable to enjoy the automatic installation, "Download only" link will continue to provide the existing experience.

**Comment by Johno-ACSLive** [comment]
Sorry it's been a while, I've been busy trying to find a new job (I'm between jobs at the moment).

Is your suggestion to show a "Direct Download" link similar to the "Show ChangeLog" link?

Agree, we can get rid of the Close button.

Perhaps we should rename Download now to Update now as well.

**Comment by RussKie** [comment]
> Perhaps we should rename Download now to Update now as well.

Good idea 👍 

> Sorry it's been a while, I've been busy trying to find a new job (I'm between jobs at the moment).

Good luck!

**Comment by Johno-ACSLive** [comment]
> Good luck!

Thank you!

I'll create a PR shortly for this.

**Comment by Johno-ACSLive** [comment]
PR created 😃
