### ISSUE TITLE
Swastika-like Symbol as User Image

### ISSUE THREAD

**Issue by Fazzyer** [gitextensions/gitextensions#6743]
In main view, each user seems to get a randomly picked symbol showing up next to his or her username. One of our users has a symbol that looks like the nazi-symbol swastika; since we're working in Germany, this is not very nice. I've added a screenshot of the symbol as attachment. 

Please remove this symbol from the available symbols.
![gitext](https://user-images.githubusercontent.com/42586917/58858240-6db8d180-86a7-11e9-9271-933ecc1eb913.png)

**Comment by gerhardol** [comment]
This is not generated by GE but of the Avatar fallback service you have selected.
Please direct this to the Identicon service.
You could of course change from Identicon to something else.

**Comment by pmiossec** [comment]
>You could of course change from Identicon to something else.

You could do it easily with a right click on the avatar and choose which generated type of avatar you want. And if you use the last stable version, you could even choose "Author Initals" to be sure to not have strange symbols...

![image](https://user-images.githubusercontent.com/460196/58869491-9f896280-86be-11e9-929e-a6672cfe97d4.png)

As we can't do much, I will close the issue...
