### ISSUE TITLE
Unable to update remote repositories

### ISSUE THREAD

**Issue by karthikpromontory** [gitextensions/gitextensions#6748]
## Current behaviour

I have version 3.1.1.6049 backed by git 2.21 on Windows 10. Earlier versions of gitextensions had the option of updating the remote branches (Pull/Fetch->Manage Remote->Update Repository) That option is no longer there, and I do not know how to update with newly added branches. Please help!

## Expected behaviour
Ability to update git extensions with newly added branches (by another user) in a repo.

## Steps to reproduce

Click on Command->Pull/Fetch->Manage Remote

## Screenshots

Attached screenshot

## Did this work in previous version of GitExtensions

Yes. Until the previous version

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3362.0
- DPI 96dpi (no scaling)
![Git_Extensions_Issue](https://user-images.githubusercontent.com/12040046/58894123-6b627180-86bf-11e9-89d5-ca3a61b3906b.png)

**Comment by pmiossec** [comment]
If that's the feature I think you talked about, that has been moved in the
contextual menu of the 'remote' node, inside the left panel.

**Comment by karthikpromontory** [comment]
I don't see anything inside that panel either. I am quite sure I'm not looking in the right place. Could you pls guide?



![image](https://user-images.githubusercontent.com/12040046/58902374-fb5ce700-86d0-11e9-9886-9569a28892ac.png)

**Comment by pmiossec** [comment]
I'm not in front of a computer, so I can't help you as much as possible.

That's not in this form anymore (which is a configuration form). You can close it.

The feature is in the left panel of the browse form (where you can see the history graph). The left panel is probably hidden and you can display it in the toolbar. 

Then have a look at the PR that introduced the feature to see screenshots: 

https://github.com/gitextensions/gitextensions/pull/6293

PS: you could also simply achieve what you want by just doing a 'fetch all' in the toolbar, no!?!

**Comment by pmiossec** [comment]
I have found the issue where the left panel  is displayed. Look at the screenshots in: https://github.com/gitextensions/gitextensions/pull/4499#issuecomment-370125194

**Comment by karthikpromontory** [comment]
@pmiossec Thank you! I had not used the Fetch All feature before, but it worked like a charm!
