### ISSUE TITLE
Restore different grays which were unified by Dark Theme Fixes

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#6750]
## Current behaviour

1. alternating revision line colors are too dark
2. resize grips have the same color as scrollbars (hence cannot be seen well)
3. gray background for line numbers although they belong to the diff. which has a white background (Maybe this is really an improvement if separated by darker resize grips.)
4. toolbar with white background

## Expected behaviour

- rectangular areas should not be virtually joined, but should be separated in order to guide the eyes
- restore the previous elaborated design for the Bright Theme except:
   - bright gray for the toolbar (4.)
   - perhaps keep new line numbers (3.)

## Screenshots

previous
![grafik](https://user-images.githubusercontent.com/36601201/58917977-c11f3400-8728-11e9-8a89-b6aded7c3107.png)

current
![grafik](https://user-images.githubusercontent.com/36601201/58918007-d1371380-8728-11e9-8c25-943b0bfbd3aa.png)

previous
![grafik](https://user-images.githubusercontent.com/36601201/58918107-28d57f00-8729-11e9-8409-d9f4ea093895.png)

current
![grafik](https://user-images.githubusercontent.com/36601201/58918114-31c65080-8729-11e9-9e8d-3605b706aa45.png)

## Did this work in previous version of GitExtensions

before #6651

## Environment

- Git Extensions 3.2.0
- Build 8d1c7aecfe9d03b0ba2a4d9113265b5440d85289
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
So you are reviewing after the merge?
(Do you have other things to do than monitoring all PRs?)
(I pointed out these differences in my review too.)

This is using the standard Win colors, so it looks OK regardless of the settings.
Forcing colors exactly as in 3.1 will cause the dark theme looks horrible again. 
Having separate light/dark colors works only to some extent.

Personally I have got used to the colors, except for the line number background that should be closer to the text background (but not exactly white/black.)

**Comment by mstv** [comment]
Now I must let the cat out of the bag: I'm not very interested in dark themes.
And I have read your statements:
> I suggest this is merged and the details that are changed are adjusted after.

> If there are comments on the (minor) visual changes in normal themes, we handle them later.

I haven't expected such an heavy influence on the normal theme.
There were only screenshots of the file diff.

> (Do you have other things to do than monitoring all PRs?)

I have rebased my bugfix branch and seen the result.

**Comment by RussKie** [comment]
It was expected that after #6651 we will have visual artifacts.
So we just need to work them through. 

I don't believe this issue is in any way implies Gerhard has done a lousy job reviewing the original PR (you've done a great job mate 👍).

**Comment by RussKie** [comment]
@cryham do you think you could do some tweaks?
I think we may need to use/enhance `ColorHelper` to make colours lighter/darker.

**Comment by gerhardol** [comment]
> Now I must let the cat out of the bag: I'm not very interested in dark themes.

Not really me either, but my wife likes when I use dark themes so it is better for me too.
Also, some user find dark themes cool and we want to have many users so we have many contributors.

> I have rebased my bugfix branch and seen the result.

> I don't believe this issue is in any way implies Gerhard has done a lousy job reviewing the original PR (you've done a great job mate +1).

I had expected comments, but do not know which chnges that would be disliked. Some changes will be reverted or maybe still hardcoded in the withe theme. This will add a little noise in the repo but there will not be any comments otherwise. 

SystemColors should be used where possible as done in the PR, but we could use IsLightTheme to set the old hardcoded colors if not possible to in another way.

**Comment by cryham** [comment]
Right. I'll try to find colors from SystemColors closer to the original gray ones.
If not found, then doing a switch with IsLightTheme between old color and a new one for dark themes.

**Comment by mstv** [comment]
> It was expected that after #6651 we will have visual artifacts.
> So we just need to work them through.

> I don't believe this issue is in any way implies Gerhard has done a lousy job reviewing the original PR (you've done a great job mate 👍).

👍 Exactly (and perfectly expressed). I know this was much hard work. I didn't want to delay merging it.
 (In addition, my switch to Win10 is still far from being finished.)

> SystemColors should be used where possible as done in the PR, but we could use IsLightTheme to set the old hardcoded colors if not possible to in another way.

> Right. I'll try to find colors from SystemColors closer to the original gray ones.
If not found, then doing a switch with IsLightTheme between old color and a new one for dark themes.

If not found, gray colors could be interpolated between WindowText and WindowColor. This should work for all themes.

**Comment by RussKie** [comment]
I think it is totally acceptable not to rely on system colours alone, just
use our ColorHelpers to make them ligher/darker as required.

**Comment by cryham** [comment]
Made points 1 and 2 in PR #6806.
IMO 3 and 4 are better now.

**Comment by gerhardol** [comment]
@mstv 
OK to close this?

**Comment by gerhardol** [comment]
There are still some inconsistencies in backgrounds etc. Probably before #6651

Submodules, Statistics(plugin) has a darker background color.
While I prefer the lighter toolbar background (point 4), most forms look like settings in the background, a little darker. Repositories is light though.

![image](https://user-images.githubusercontent.com/6248932/59717862-2854e200-9219-11e9-8509-50a2e0754899.png)

![image](https://user-images.githubusercontent.com/6248932/59717975-62be7f00-9219-11e9-94d1-09af9508fd1c.png)

Github has ligher tab background (I prefer) than in Browse
![image](https://user-images.githubusercontent.com/6248932/59718156-d1034180-9219-11e9-976a-5e53a8bb4870.png)

**Comment by mstv** [comment]
(Now that RL is moderating, I can respond to @ mentions at least.)

Thank you! My main wishes have been catered. Though I want to check some days how it feels with this very bright toolbar, which is virtually joined with the CommitInfo and the title bar.

Also I guess, the inconsistencies of the dialogs listed by Gerhard existed before.

> Github has ligher tab background (I prefer) than in Browse

I'm afraid, then the scrollbar background and the size grips would have the same color.
Or do you mean to change only the background of tab area? Which might look like this mock-up:

![grafik](https://user-images.githubusercontent.com/36601201/59805142-bb148000-92f0-11e9-9ecc-ac690436bae6.png)

**Comment by mstv** [comment]
This issue can be closed regarding my point.

> There are still some inconsistencies in backgrounds etc. Probably before #6651

There has already been created a generic issue #6183.
