### ISSUE TITLE
GE freezes when the avatar column is shown

### ISSUE THREAD

**Issue by AOrlov** [gitextensions/gitextensions#6751]
## Current behavior

GE scrolling is laggy when the avatar column is shown since the user name for each commit gets retrieved on UI thread.

## Expected behavior

The avatar information should be asynchronous.

## Steps to reproduce

1. Invalidate avatar cache
2. Open a repository with a lot of commits where some of them contain avatar icon
3. Enable avatar column
4. Scroll the main window

## Screenshots

![before](https://user-images.githubusercontent.com/861131/58923868-61a83080-86f6-11e9-86c1-5c9a49d84264.gif)

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please sign the contributors.txt before we can accept your contributions.
Thanks

**Comment by AOrlov** [comment]
@RussKie,
all comments should be satisfied now.
