### ISSUE TITLE
Setting to disable overlays on Windows taskbar

### ISSUE THREAD

**Issue by ZodmanPerth** [gitextensions/gitextensions#6761]
## Feature description

The taskbar icon now has an overlay "light" that indicates the commit state of the current repository (changing between green, red, amber, etc).

![image](https://user-images.githubusercontent.com/546368/59073025-d72f1f00-88f7-11e9-86a5-cfbaf25e7821.png)

For users (like me) who strive for a notification-free workspace, this is an unwelcome distraction.

My preferred solution would be an option in settings to turn off the overlay and leave just the application icon.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.18.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Kind of workaround: Notification is not shown with small icons. 
(I would have preferred them. )

**Comment by ZodmanPerth** [comment]
My current workaround is to put Git Extensions onto my "Notifications" virtual desktop.  It's not a good long-term solution though because I frequently need to work with other windows on my "Work" virtual desktop at the same time.
The other alternative is to close the application altogether, but it takes too long to go from launch to ready.
Hopefully adding a setting is relatively simple as it will be the ideal solution for me.

**Comment by drewnoakes** [comment]
@ZodmanPerth it probably wouldn't be too challenging to implement this yourself. If you wanted to try I'm sure you could get some pointers from the team.

**Comment by ZodmanPerth** [comment]
I would, for sure, if I had the time to spare.  That and a few other things.

One day...

**Comment by mstv** [comment]
Windows 10 has a setting "Show Badges on Taskbar Icons" (just guessing the English translation). The search settings feature is a great help.

**Comment by RussKie** [comment]
Thank you @mstv.

@ZodmanPerth here's the setting:
![image](https://user-images.githubusercontent.com/4403806/59961678-65251f80-951e-11e9-8b68-3d2722677506.png)
