### ISSUE TITLE
[NBug] OnActivate must be called on the UI thread.

### ISSUE THREAD

**Issue by emreozbek** [gitextensions/gitextensions#6799]
## Error Details
```
System.Runtime.InteropServices.COMException (0x8001010E): OnActivate must be called on the UI thread.
   konum: GitUI.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
   konum: GitUI.CommandsDialogs.FormBrowse.<OnActivate>g__CheckForMergeConflicts|74_0()
   konum: GitUI.GitUIExtensions.<InvokeAsyncDoNotUseInNewCode>d__13.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   konum: System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   konum: System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   konum: System.Threading.ThreadPoolWorkQueue.Dispatch()
```

## Environment
- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Seem to be a new issue, maybe enough info in stack trace.

**Comment by gerhardol** [comment]
FormBrowse OnActivated() was called from a NonUI thread at some exception handling. 
No information why this occurred, information to recreate needed.

**Comment by RussKie** [comment]
I think we need to re-write `OnActivated` method deprecating and removing `InvokeAsyncDoNotUseInNewCode` method as this is the only callsite for it:
https://github.com/gitextensions/gitextensions/blob/a1bfe8fe40899dd5f30b4459acdd48e3aadfc553/GitUI/CommandsDialogs/FormBrowse.cs#L527-L531

@emreozbek could you please provide more info as to how this happened.
