### ISSUE TITLE
[NBug] Erreur lors de la lecture du répertoire I:\gitLabCloud\clara\.

### ISSUE THREAD

**Issue by totocaca123** [gitextensions/gitextensions#6812]
## Current behaviour
application crashes

## Expected behaviour
git project is expected to be closed

## Steps to reproduce

Open a git project located in an external hard drive. Disconnect external hard drive and this error will occur

## Error Details
```
System.IO.FileNotFoundException: Erreur lors de la lecture du répertoire I:\gitLabCloud\clara\.
   à System.IO.FileSystemWatcher.StartRaisingEvents()
   à GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   à System.Windows.Forms.Timer.OnTick(EventArgs e)
   à System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
external hard drive disconnected

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
First reported in #6676 but this contains some info

**Comment by RussKie** [comment]
@gerhardol is there something we can do to prevent/reduce these bugs?

**Comment by gerhardol** [comment]
> is there something we can do to prevent/reduce these bugs?

Yes, GE should not crash if the path is no longer available in background oerations. try-catch if there are no other solution.
(maybe similar for background fetch plugin)

**Comment by gerhardol** [comment]
https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs#L325

```
            // Check that the directory is still valid, otherwise will an exception be raised
            if (!Directory.Exists(_workTreeWatcher.Path))
            {
                return;
            }

            _workTreeWatcher.EnableRaisingEvents = true;
```
