### ISSUE TITLE
Unable to blame a file

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#6815]
## Current behaviour

Blaming the file `GitHub3Plugin.cs` in the GitExtensions sources open the File History/Blame form displaying the message "This repository does not yet contain any commits". The blame depends of the case of the folder in the working directory.

![image](https://user-images.githubusercontent.com/460196/59609747-42f36200-9118-11e9-9786-9798d4fde175.png)

It is due to a problem with case sensitivity in the `GitHub3` path because there is 2 folders in the filetree (and the blame in the folder `Github3` works but don't work for all the files of  `GitHub3`):
![image](https://user-images.githubusercontent.com/460196/59609829-6dddb600-9118-11e9-9b0e-da0f54d9dab1.png)

Setting `core.ignorecase`  is set at `true` in the repository.

edit: after a better test, the works if the folder name match the case of the folder in the working directory. If the case of the folder is changed to match `GitHub3`, then the blame work for the `GitHub3Plugin.cs` file and fail for files of the other folder.

## Expected behaviour

Blame is working for this file.

## Did this work in previous version of GitExtensions

i don't know...

## Environment

- Git Extensions 3.2.0
- Build 6767731f758d2b45bbdd8125fada5b564d5f46d2
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 192dpi (200% scaling)

**Comment by pmiossec** [comment]
It seems that `FormFileHistoryController.TryGetExactPath()` is not doing the job.
Especially `NativeMethods.GetLongPathName()`...

**Comment by crypto-rsa** [comment]
Could it be related to #6458?

**Comment by pmiossec** [comment]
>Could it be related to #6458?

Not exactly even if the problem lie in the same `TryGetExactPath()` method.

The problem is that, maybe it is returning a good cased filename but it don't fix the case of the entire path, so the blame fails.

**Comment by pmiossec** [comment]
After a short investigation, `FormFileHistoryController.TryGetExactPath()` is doing the opposite of what it is expecting to do: the path in the input is well cased and the output is not well cased 😭

**Comment by gerhardol** [comment]
Closed by #6909
