### ISSUE TITLE
Can I see commits ordered by author-date instead of commit-date?

### ISSUE THREAD

**Issue by asfarley** [gitextensions/gitextensions#6826]
## Current behaviour

I have a project with a long history which has recently been rebased. The project has several branches. 

In the main GUI window, it looks like the commits are being displayed based on commit-date order rather than author-date order. In particular, there are two branches which were developed in parallel. After rebasing, I don't see the a 'tic-toc' commit pattern; it looks like the branches were developed serially. 

In the screenshot, a commit authored **1 month ago** is rendered below a commit authored **1 year ago**. For this project, it would be helpful if the commits appeared in chronological-by-author-date.

## Expected behaviour
I expected to see commits happening on two branches in an interleaved manner. 

## Steps to reproduce
Commit a long, linear Git history of development. Rebase development-history to have several branches originating from a common ancestor, rather than a linear progression.

## Screenshots

![Screenshot](https://i.imgur.com/6CZrBu8.png)

## Did this work in previous version of GitExtensions
Not as far as I know. This is more of a help-request, not necessarily a bug.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
GE lists the commits as retrieved by Git.
In 2.x there were options to sort the output. The problem with that was that git-log must find all commits first, then sort them before the revision graph could be displayed. This delayed the display and required more memory I believe.

**Comment by pmiossec** [comment]
It seems possible with option `--author-date-order`: https://stackoverflow.com/a/18871907 

But someone interested in it have to contribute a PR.
@asfarley do you want to do it?

**Comment by asfarley** [comment]
> It seems possible with option `--author-date-order`: https://stackoverflow.com/a/18871907
> 
> But someone interested in it have to contribute a PR.
> @asfarley do you want to do it?

I'll take a look - might be within my capabilities. Thanks for pointing me in the right direction.

**Comment by asfarley** [comment]
Do you have a guide for developers? (what compiler is GitExtensions built with, coding conventions, etc)

**Comment by pmiossec** [comment]
>so I think that answers everything for now.

Great!

>what compiler is GitExtensions built with

https://github.com/gitextensions/gitextensions/wiki

>coding conventions

They are enforced by StyleCop, so nothing special...


You could hard code the option to quickly see if it solves the problem.
If it works, I think that the option could end up in the view menu.
