### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by kevin0756** [gitextensions/gitextensions#6828]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   at ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   at ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   at ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   at ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   at GitUI.FormStatus.Done(Boolean isSuccess)
   at GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by kevin0756** [comment]
Please fix this troublesome issue. I am unable to push code

**Comment by pmiossec** [comment]
>Please fix this troublesome issue. I am unable to push code

No one really helped to solve this issue by doing good bug reports (by filling all the requested information)  or trying to debug the issue. **Even you**.

So this is really difficult for us to fix an issue we don't reproduce and that we don't understand.

But you could work around the issue by going to "Settings" > "Git Extensions" > "Advanced" and uncheck "Use Console Emulator for console output in command dialogs".

**Comment by kevin0756** [comment]
This is an intermittent issue which occurs when I use the "commit and push" option. The files get committed but the push never happens and instead I see the above shared output in an error message. It occurs randomly, albeit rarely and is difficult to reproduce. The most recent time this happened was when I had pushed some code and after a few mins, pushed again.

**Comment by pmiossec** [comment]
Thanks for giving us some context.
We know that we have some bad behaviors with the ConEmu dependency but we don't know if it brings more added values than disadvantages and if we must disable it by default. I personally never had this error and I don't know if it can't be a problem with the antivirus that block the loading or if there is really a problem in the dependency.

**Comment by kevin0756** [comment]
Yes, as I mentioned before, the issue is intermittent and difficult to reproduce. But when it does happen, it produces a stint of 3 or 4 failures in quick succession, before disappearing altogether. To help you guys a bit, I began witnessing this issue ever since I installed Git Extensions 3.1.1.6049. Never had it with the previous versions.

**Comment by pmiossec** [comment]
>To help you guys a bit, I began witnessing this issue ever since I installed Git Extensions 3.1.1.6049.

This information is interesting because we didn't know when it was introduced as stated in this message: https://github.com/gitextensions/gitextensions/issues/6675#issuecomment-502439700

**Comment by kevin0756** [comment]
Happy to help. Hope it gives some leads. Thanks

**Comment by pmiossec** [comment]
I also try to open an issue to the repository of the dependency https://github.com/Maximus5/conemu-inside but GitHub crash and I can't open an issue to get more information from the developper.

I got a 500 page that I never saw in the past:

![image](https://user-images.githubusercontent.com/460196/59837097-f3e24280-934c-11e9-9377-ab0211d195fe.png)

**Comment by kevin0756** [comment]
That's strange. I've never tried that before. Maybe something change in that particular dependency during the release of 3.1.1.6049. Or maybe it could be something else. But I'm glad that the version number did have some level of aid. Hopefully you guys would get to the bottom of this :)

**Comment by pmiossec** [comment]
The issue I finally was able to create: https://github.com/Maximus5/conemu-inside/issues/45

**Comment by kevin0756** [comment]
> The issue I finally was able to create: [Maximus5/conemu-inside#45](https://github.com/Maximus5/conemu-inside/issues/45)

Thank you so much!! It isn't a showstopper, but can be really irritating when it does happen.

**Comment by RussKie** [comment]
Disable the ConEmu in the settings

**Comment by gerhardol** [comment]
Duplicate of #6675 

The only available "fix" is to disable ConEmu, which I would prefer not to loose

**Comment by piotr-cz** [comment]
For me it might have started to come up after I've upgraded Git from 2.24.0 to 2.24.0.2.
I'm not getting any errors/ warnings but process window gets stuck at the Process and nothing showing up.

Git command log shows commands are running fine, just don't show in GitExtensions

**Comment by gerhardol** [comment]
The error reported here is corrected in master, no NBug popup if closing too quickly.

> but process window gets stuck at the Process and nothing showing up.

That seem to be another issue

**Comment by piotr-cz** [comment]
ok, thanks
