### ISSUE TITLE
Diff view exception on plain text file (.tex)

### ISSUE THREAD

**Issue by SergeySevbitov** [gitextensions/gitextensions#6831]
## Current behaviour

Diff viewer is crashing on viewing diff for a LaTeX file.

## Expected behaviour

Shouldn't crash, but show plain text diff.

## Steps to reproduce

Sorry, cannot attach the file causing diff viewer exception.

## Screenshots

Diff viewer:
![image](https://user-images.githubusercontent.com/7067666/59896679-0c6d5e00-941c-11e9-906a-5f6bf36a7fa9.png)

## Did this work in previous version of GitExtensions

Yes, have never seen such an error with earlier versions.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
Cannot reproduce, testing with a LaTeX file I found.
If you cannot share the file, can you debug?

**Comment by RussKie** [comment]
Is it a consistent issue with *that specific* file?
Looking at the stack trace the problem was probably not with the file itself, but with the order of events that led to it.

**Comment by SergeySevbitov** [comment]
It seems it is a volatile issue. I will try to investigate how to
reproduce  the bug.

**Comment by RussKie** [comment]
It is possible you may had one file opened and scrolled, then opened a different file...
