### ISSUE TITLE
Prune button is not available in remote repositories dialog

### ISSUE THREAD

**Issue by TKR1605** [gitextensions/gitextensions#6833]
Prune button is not available in remote repositories dialog since 3.1.1

![grafik](https://user-images.githubusercontent.com/52069799/59914471-c49a0700-941a-11e9-9803-7bcff79be46e.png)

**Comment by pmiossec** [comment]
The button is no more here. See https://github.com/gitextensions/gitextensions/issues/6748#issuecomment-498807853

**Comment by pmiossec** [comment]
For better search of user, I copy the answer here:

That's not in this form anymore (which is now a purely configuration form).

The feature is in the left panel of the browse form (where you can see the history graph). The left panel is probably hidden and you can display it in the toolbar. 

![image](https://user-images.githubusercontent.com/460196/59917653-c798f580-9422-11e9-8dab-ca67d227feed.png)


Then have a look at the PR that introduced the feature to see screenshots: 

https://github.com/gitextensions/gitextensions/pull/6293

You could also simply achieve what you want by just doing a 'fetch and prune all' in the toolbar, no
