### ISSUE TITLE
GitExtensions portable is not usable from program files if not run as Administrator

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#6845]
## Current behaviour
When you run GitExtensions Portable not as elevated Administrator from Program Files , it crashes since it cannot create temporary file in that directory.

## Expected behaviour
Temporary files should be created in a temporary directory and not int the GitExtensions folder.

## Steps to reproduce
Copy GitExtensions Portable to Program Files.
Start as non elevated Admin.
Start configuring sh tools or anythig else.
Expect crash.

## Environment

- GitExtensions version: 3.11
- GIT version: 2.22
- OS version: Windows 10
- .NET version:  4.8

**Comment by pmiossec** [comment]
I think you misunderstood because that's the goal of the portable version to be installed outside of the 'Program files' folder **because** you don't have the administrator rights.

And in this version, settings files are indeed written in the folder containing the program.

**Comment by NN---** [comment]
Ok, the program at least should not crash :)
What about testing write permissions when portable versions starts?

**Comment by pmiossec** [comment]
Indeed but our resources (in time) are quite scarce and giving feedback when preventing the user to do strange things is taking a lot of time.

I don't think the developer that did the feature imagined someone doing that 😁

So, we accept pull request on all the fixes for problems happening only on users computers 😉

**Comment by gerhardol** [comment]
Probably fixed in https://github.com/gitextensions/gitextensions/pull/6836
