### ISSUE TITLE
Missing setting "Show revision details next to the revision list"

### ISSUE THREAD

**Issue by namtab00** [gitextensions/gitextensions#6856]
## Current behaviour

Missing setting _Show revision details next to the revision list_

## Expected behaviour

There should be present a setting "_Show revision details next to the revision list_

## Did this work in previous version of GitExtensions

In 2.51 there was a setting named _Show revision details next to the revision list_ , as documented [here](https://git-extensions-documentation.readthedocs.io/en/release-2.51/settings.html#detailed-browse-repository-window)

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3801.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
This option has been transformed in an icon in the toolbar that allows you to choose the place where you want to display the commit details.
