### ISSUE TITLE
Ctrl + click to start repo in new window

### ISSUE THREAD

**Issue by murat-mehmet** [gitextensions/gitextensions#6866]
## Feature description
I am working with many repos inside a day, and to start each repo I need to start a new gitextensions executable and select a repo to open it in a new window. I think it would great just to go Start > Recent Repositories > [Repo path] and ctrl+click on it to start the repo in a new gitextensions window, this way we can open repos in a much faster way.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Yes, would be a nice feature. A PR is welcome.

In the meantime, one can right click the GE icon in the Windows Taskbar or at least shift click it. Though the list there is less complete.

**Comment by oriash93** [comment]
I would like to make a PR for it.
I know how to detect the `ctrl` key but having trouble with opening in a new window. Can anyone give me some pointers?

**Comment by pmiossec** [comment]
I think that you have to launch a new instance of Gitextensions with
`Process.Start("Gitextensions.exe browse c:\path\of\repo\to\open)`

**Comment by RussKie** [comment]
Yes, though `Gitextensions.exe` must not be hard-coded. The executable must be retrieved via `AppSettings.GetGitExtensionsFullPath()`

**Comment by mstv** [comment]
> My point of view is that's a very hidden feature and so, you will be the only one to use it.
To improve a little that, I would have at least added a tool tip somewhere.
What do the others think about it?

I fully agree.

`<slightly off topic>`
It's like the context menu of the Explorer opened with `Shift+Click` which adds the _single_(**!**) item `Copy as path`, which I find quite useful. 
@ MS emloyees: There should be a registry setting to enable this by default.

In addition, **all** GE context menu items are shown if `Shift` is pressed. (Is this a bug or a feature of GE?)
`</slightly off topic>`

The current tooltip "Change working directory" could be extended to something like "Change working directory, open in new window if Ctrl pressed". (This works for both `Ctrl+Click` and `Ctrl+Enter`.)

I would like in addition that a right click on the recent list entries opens another context menu with "&Open", "Open in &new window" (and "&Remove from list") if possible with WinForms.

The same applies to the toolbar button for submodules, which does not have a tooltip yet.
In the ROT (left panel), a new context menu item "Open in &new window" should be added.

**Comment by RussKie** [comment]
> It's like the context menu of the Explorer opened with `Shift+Click` which adds the _single_(**!**) item `Copy as path`, which I find quite useful.

Could you please elaborate a bit more?

> @ MS emloyees: There should be a registry setting to enable this by default.

We are from DevDiv (.NET and dev tooling), and not from Windows.



> something like "Change working directory, open in new window if Ctrl pressed".

_Change working directory, press CTRL to open in new window_

**Comment by mstv** [comment]
>>> My point of view is that's a very hidden feature...

>> It's like the context menu of the Explorer opened with  `Shift+Click` which adds the _single_(**!**) item `Copy as path`, which I find quite useful.

> Could you please elaborate a bit more?

I just wanted to give a well known -- IMO bad -- example of an hidden useful function.
I guess their intention was to reduce the complexity of the Explorer context menu. It's not worth it for only one affected menu item.

---

(**All** GE Explorer context menu items are shown if `Shift` is pressed.
The `Shift` key is explicitely checked in `GitExtensionsShellEx.cpp`. So it is feature.)

**Comment by RussKie** [comment]
@mstv you seem to have a good idea on what is needed/outstanding to move forward with this feature. Do you think you could list the items to address?
E.g. 
* [ ] Add another context menu to the dashboard
* [ ] etc

Thank you

**Comment by mstv** [comment]
Sorry, this one slid down back from the list.

- [x] 1. Support `CTRL` key for repositories.
- [ ] 2. Extend the tooltip of the ComboBox `_NO_TRANSLATE_WorkingDir` into "Change working directory, press CTRL to open in new window"
- [ ] 3. (optional) Add a new context menu to the items of the drop down list of the ComboBox `_NO_TRANSLATE_WorkingDir`:
  - `Open in &new window\tCtrl+Click`
  - `&Open in this window\tClick`
  - `&Remove from list`
- [ ] 4. (optional) Add menu items to the context menu of the recent repos in the Dashboard:
  - `&Open in this window\tClick`
  - `Open in &new window\tCtrl+Click`
  - separator
  above the existing menu items:
  ![grafik](https://user-images.githubusercontent.com/36601201/72674520-0d30a600-3a78-11ea-8668-928554e1afa8.png)
- [ ] 5. Support `CTRL` key for submodules in the toolbar
![grafik](https://user-images.githubusercontent.com/36601201/72674626-2d149980-3a79-11ea-9735-c44fc93a8a44.png)
- [ ] 6. Add tooltip to the submodules button in the toolbar
  "Switch submodules, press CTRL to open in new window"
- [ ] 7. Support `CTRL` key for submodules on double click in the left panel (a.k.a. ROT)
![grafik](https://user-images.githubusercontent.com/36601201/72674706-17ec3a80-3a7a-11ea-8a26-6ec53e542502.png)
- [ ] 8. Add menu item `Open in &new window\tCtrl+Double Click` for submodules in the left panel
![grafik](https://user-images.githubusercontent.com/36601201/72674691-e07d8e00-3a79-11ea-962a-533238df4b0e.png)
- [ ] 9. (optional) Add sub menus to the items of the submodules menu in the toolbar (refer to 5.):
  - `Open in &new window\tCtrl+Click`
  - `&Open in this window\tClick`
