### ISSUE TITLE
Exception when opening the file history for certain files

### ISSUE THREAD

**Issue by apobekiaris** [gitextensions/gitextensions#6872]
## Current behaviour

Exception thrown.

## Expected behaviour
Open file hitory from command line

## Steps to reproduce

* I have a script in autohotkey to open filehistory like

"C:\Program Files (x86)\GitExtensions\GitExtensions.exe" filehistory %ClipBoard% 

was working fine but now throws

* i can repro from the UI also. I modified a file then go to the commit right click and file history

looks like it works for another repo, have no idea why it doesn't work for this one though as I did no changes.

## Error Details
```
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   at GitUIPluginInterfaces.ObjectId.TryParseAsciiHexBytes(ArraySegment`1 bytes, Int32 index, ObjectId& objectId)
   at GitCommands.RevisionReader.TryParseRevision(GitModule module, ArraySegment`1 chunk, StringPool stringPool, Encoding logOutputEncoding, GitRevision& revision)
   at GitCommands.RevisionReader.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at GitUI.RevisionGridControl.<>c__DisplayClass150_2.<ForceRefreshRevisions>b__9()
   at GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
---> (Inner Exception #0) System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.ArraySegment`1..ctor(T[] array, Int32 offset, Int32 count)
   at GitUIPluginInterfaces.ObjectId.TryParseAsciiHexBytes(ArraySegment`1 bytes, Int32 index, ObjectId& objectId)
   at GitCommands.RevisionReader.TryParseRevision(GitModule module, ArraySegment`1 chunk, StringPool stringPool, Encoding logOutputEncoding, GitRevision& revision)
   at GitCommands.RevisionReader.<ExecuteAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()<---

```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.3801.0
- DPI 144dpi (150% scaling)

**Comment by apobekiaris** [comment]
update the report

**Comment by pmiossec** [comment]
I can not reproduce.
I think it is not linked to the command line but more to the file or the repository.

To be sure, could you test without the use of autohotkey?

Could you also try inside another repository?
And also for another file inside the same repository?

**Comment by apobekiaris** [comment]
i can repro from the UI also. I modified a file then go to the commit right click and file history

**Comment by apobekiaris** [comment]
looks like it works for another repo, have no idea why it doesn't work for this one though as I did no changes. Any clues?

**Comment by pmiossec** [comment]
>Any clues?

Unfortunately, no. 😢

**Comment by pmiossec** [comment]
There was a similar issue #5277 But the fix #5238 is the version 3.1.1 that you have...

**Comment by RussKie** [comment]
We need to know what command is being executed.
Please share the command log (_Tools > Gitcommand log_), dismiss the NBug dialog and post it here.

**Comment by apobekiaris** [comment]
for some reason i cannot attach, here a dropbox link
https://www.dropbox.com/s/vbksvtyrz55f2lc/gitex.zip?dl=0

**Comment by RussKie** [comment]
What's been passed as `%ClipBoard%`?

**Comment by apobekiaris** [comment]
this 

```
C:\Work\eXpandFramework\expand\Support\Build\Build.ps1
```

**Comment by apobekiaris** [comment]
also i am able to repro it without the command line

>i can repro from the UI also. I modified a file then go to the commit right click and file history

**Comment by RussKie** [comment]
I've looked at the code, I can't see an obvious bug in the code.

Are you able to share the problem repo? If not, are you in a position to debug it?

**Comment by apobekiaris** [comment]
the repo is public git@github.com:eXpandFramework/eXpand.git but i cannot repro it with a new clone. However I cannot simply switch to a new clone as my local repo contains much more files. 

do u have debugging instructions? or maybe can i attach somehow and use the build symbols?

**Comment by apobekiaris** [comment]
i can debug but no idea why it fails sorry
![image](https://user-images.githubusercontent.com/159464/60384065-1c231d00-9a82-11e9-909e-a93362ce9559.png)

**Comment by apobekiaris** [comment]
i copy-paste my local repo folder to another disk and still can repro the issue, maybe u can also 

https://www.dropbox.com/s/ik0iabcs9sx6lc1/2.rar?dl=0

**Comment by apobekiaris** [comment]
or if u cannot and have instruction on how to debug happy to help

**Comment by RussKie** [comment]
> i can debug but no idea why it fails sorry

You'll need to walk up the stack and see what parameters being passed in... and see if you can hypothesise about the problem.



> i copy-paste my local repo folder to another disk and still can repro the issue, maybe u can also

I'll pull it down and see if I can repro/debug

**Comment by RussKie** [comment]
Here's the problem - we're trying to read more elements than the size of the array:
![image](https://user-images.githubusercontent.com/4403806/60391791-1b4dc200-9b3a-11e9-8a8a-dde65b36a609.png)

@drewnoakes any thoughts? This method was introduced in f64db43ff7f9198918ee4d487979b2e90a57e836

**Comment by drewnoakes** [comment]
There are two problems here.

1. `ObjectId.TryParseAsciiHexBytes` should return false rather than throw when there is a bounds error
2. The structure of the log command includes null bytes where they are not expected.

![image](https://user-images.githubusercontent.com/350947/60435211-43c5e100-9c4c-11e9-83fb-724432be3c8c.png)

The current log parsing logic assumes each commit is separated by a single `\0` byte (`00` in the screenshot). They starting with the "ASCII hex bytes" of the commit ID, parent ID and so on, then some Unix timestamps, author/committer details, the the subject and message. The selected (blue) region here shows such a commit.

What is unexpected here is that after the `00` we see a string which is not actually an ASCII SHA-1.

This rings a bell though. I'm pretty sure I discussed this with @vbjay a while back and proposed introducing a double null delimiter for commits, which would allow single null characters within commit 'chunks'.

-c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b" --reflog --all --boundary --not --glob=notes --not --max-count=100000 --full-history  --name-only --parents --find-renames --find-copies -- "Support\Build\Build.ps1" "Support/Build/Build.ps1" "Support"

In this case those extra items appear to be file paths, likely related to the `--find-renames --find-copies` options, though I haven't checked. Again, I'm pretty sure there's a discussion about this somewhere related to logging the history of a file across renames.

Fixing the above point 1 is easy, however it won't help with point 2 as the log will be ended as soon as one of these unexpected chunks is observed.

**Comment by drewnoakes** [comment]
With #6882 the exception will no longer occur, however there is still a real issue here.

It'd be useful to understand what combination of command line options produces these file names.

**Comment by gerhardol** [comment]
@drewnoakes 
From https://github.com/gitextensions/gitextensions/pull/6132#pullrequestreview-195719486
@fschmied suggested using a GUID instead, used in the following PR to handle --follow:

https://github.com/gitextensions/gitextensions/pull/6879/files#diff-4c2e206cad9e924eb10240f3eaebd58dR31

**Comment by drewnoakes** [comment]
@gerhardol thanks for joining the dots. I'll comment there.

**Comment by drewnoakes** [comment]
Actually are you sure that's the same issue? If it were, the GUID would have to appear _before_ the null separated values above, and the chunking would still return `Support/Build/Build.ps1` as an entire 'chunk', for example.

**Comment by gerhardol** [comment]
> Actually are you sure that's the same issue?

No
This was more a link to what I read a couple of days ago. But the issues are r lasted at least. ..
