### ISSUE TITLE
test case 2

### ISSUE THREAD

**Issue by ashumalik** [gitextensions/gitextensions#6886]
## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### @annu 
![1 [https://github.com/gitextensions/gitextensions/issues/new?template=bug_report.md](Android_week+](https://user-images.githubusercontent.com/52484256/60588545-277e8d00-9d8f-11e9-8a5c-8d2b7e4c3812.png))

**Comment by ashumalik** [comment]
![1 NoCommentEntered](https://user-images.githubusercontent.com/52484256/60588662-6a406500-9d8f-11e9-90ec-c6f3a27c8286.png)

**Comment by ashumalik** [comment]
tes

**Comment by pmiossec** [comment]
@ashumalik I'm sorry but this project is not for doing your tests.

Please stop!
