### ISSUE TITLE
Is "Files content encoding" option meant to apply selected encoding?

### ISSUE THREAD

**Issue by coxymla** [gitextensions/gitextensions#6890]
## Current behaviour

I saw the option for "Files content encoding" and was very pleased because as we all know GIT does not support UCS-2. (This is a common issue for us since SSMS defaults to UCS-2 encoding in files.) So I set the option to UTF-8, then committed a UCS-2 file. The file remained in UCS-2 encoding and can't be diffed.

![image](https://user-images.githubusercontent.com/691623/60692008-2ae85480-9f06-11e9-88d8-06260d51c7ba.png)

## Expected behaviour

I'm not sure what that option is setting exactly? But it would be nice if there was an option to convert text encoding before commit so that diffs will work.

## Steps to reproduce

1. Tools -> Settings -> Files content encoding -> set to UTF-8
1. Create text file in UCS-2 encoding. Most commonly this is due to .sql file being created from within SSMS.
2. Commit file.
1. Examine file in e.g. Notepad++
1. File is still UCS-2 encoding.

## Screenshots

As per diff above.

## Did this work in previous version of GitExtensions

Presumably not?

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
I think that there is a misunderstanding.
this setting is to display the files and not to convert them.

If you want to convert them using git, you have to add a filter like described in:
https://github.com/msysgit/msysgit/issues/113

**Comment by coxymla** [comment]
I suspected that might be the case. Thanks for the clarification.
