### ISSUE TITLE
Commit message highlight is one line too high for short commit titles

### ISSUE THREAD

**Issue by Broxzier** [gitextensions/gitextensions#6895]
## Current behaviour

When writing a commit message that has a title of just one character and a message that's longer than 50 characters, the highlighing is on the blank line inbetween the two. Check out the attached screenshot, that'll make it much clearer what I mean than writing it down in text.

## Expected behaviour

That the part of the description gets highlighted instead of the blank space above it.

## Steps to reproduce

Type in a message with a title of one character, and a description of > 50 characters.

## Screenshots

![GitExtensions_2019-07-06_01-39-36](https://user-images.githubusercontent.com/9705046/60753673-7f5b0500-9fd6-11e9-86a0-55d67392a8c7.png)

## Environment

- Git Extensions 3.1.0.5877
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by Kackao** [comment]
This does not only occur on single letter titles, depending on the amount of empty lines, the underline gets an overline:

![commit1](https://user-images.githubusercontent.com/26045339/62778982-2a694d80-bab2-11e9-9c8b-4c250136fd81.PNG)
![commit2](https://user-images.githubusercontent.com/26045339/62778983-2b01e400-bab2-11e9-92fb-51badf16a423.PNG)
