### ISSUE TITLE
[NBug] Входная строка имела неверный формат.

### ISSUE THREAD

**Issue by piroxiljin** [gitextensions/gitextensions#6900]
## Current behaviour
The application crashes if the entered value has unexpected format.
E.g. Enter 0.5 instead of 0,5 (wrong decimal delimiter) or any string value.

## Expected behaviour
The application correctly parses any decimap delimiter and shows error message if the entered value is not a number.

## Steps to reproduce
Open plugin settings menu: Plugins -> Plugin settings
Select the "Find large files" plugin
Enter "0,5" (without quotes) into the "Find large files bigger than (Mb)" edit line.

## Error Details
```
System.FormatException: Входная строка имела неверный формат.
   в System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   в GitUIPluginInterfaces.NumberSetting`1.ConvertFromString(String value)
   в GitUIPluginInterfaces.NumberSetting`1.TextBoxBinding.SaveSetting(ISettingsSource settings, TextBox control)
   в GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.PageToSettings()
   в GitUI.CommandsDialogs.FormSettings.Save()
   в GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Open the Settings dialog for the Find large files plugin.
Enter: 0.5

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
What are your current locale settings?

**Comment by gerhardol** [comment]
To parse invariant is common, I can consider this to be a bug.
You get the same message if you enter garbage in the form

This is a shared control, but this seem to be the only where float or double is parsed.
A solution is to use invariant parsing.
Pushed a change, I will not add testcases to this though.

**Comment by piroxiljin** [comment]
@RussKie All localization settings are set to Russian, except the default locale for non-unicode application, which is English (US).

**Comment by RussKie** [comment]
🤔  A fix maybe to parse like so:
```diff
diff --git a/Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs b/Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs
index 9856f7544..e902e57be 100644
--- a/Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs
+++ b/Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs
@@ -85,7 +85,7 @@ private static object ConvertFromString(string value)
             var type = typeof(T);
             if (type == typeof(int))
             {
-                return int.Parse(value);
+                return int.Parse(value, System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat);
             }
 
```

**Comment by gerhardol** [comment]
The culture is used correctly, you get the exception of you use other culture. Like decimal comma with English. 

Invariant parsing can be used, see my commit. But you still get the exception with garbage so not much better. Validation should be done when leaving the text box. 

Too much work to give any significant benefit for the complete fix. The invariant is simple but to add tests will be a pain.

**Comment by RussKie** [comment]
Can't repro in the master. Presume fixed.
