### ISSUE TITLE
Please provide native Linux builds

### ISSUE THREAD

**Issue by arnonuem** [gitextensions/gitextensions#6914]
## Feature description
Since in my opinion this is the best git client ever, please provide native Linux builds so that i not have to use Mono for that.

## Environment
Ubuntu

**Comment by pmiossec** [comment]
You probably have information that we don't know.

How do you do that?

**Comment by gerhardol** [comment]
Unfortunately, mono support is also dropped in the main development. The main reason was that there were no mono developers and the mono support was slowing the development down.
This could change in the future see #6051
The 2.x version could be maintained by mono developers though.

I do not know any way to compile with mono to get a exe that do not require mono runtime.
However, I believe the question is to make a 'native' version usig GTK or so.
That would be a massive task...

This should probably be closed.
