### ISSUE TITLE
Menu display disappears by half

### ISSUE THREAD

**Issue by IkumiMashiba** [gitextensions/gitextensions#6916]
## Steps to reproduce

git : source build
mono : centos7-stable.repo

$ mono GitExtensions.exe

## Screenshots

Other languages are the same

|![gitex](https://user-images.githubusercontent.com/12806774/61113933-4507d100-a4ca-11e9-8ae1-eea067ed22b3.png)|![gitex-2](https://user-images.githubusercontent.com/12806774/61114591-9b294400-a4cb-11e9-838f-2c4ff2e95ec0.png)|![gitex-3](https://user-images.githubusercontent.com/12806774/61114595-9e243480-a4cb-11e9-92f9-31a7935271d2.png)|

## Environment

- GitExtensions version:GitExtensions-2.51.05-Mono
- GIT version: git version 2.22.0
- OS version: CentOS Linux release 7.6.1810 (Core) 
Gnome 3.28.2
- .NET version: Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 08:37:52 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

**Comment by RussKie** [comment]
I'm sorry to say but I don't believe it ever worked on Linux.

There were few attempts to fix these issues and redesign the dashboard for Linux, but I ran out of steam. 
No one from the core team or active contributors use Linux so there is no work planned to address any of the Linux issues.
