### ISSUE TITLE
Question: How view remote repo's history including the newest commets?

### ISSUE THREAD

**Issue by edwinyzh** [gitextensions/gitextensions#6917]
GitExtensions is really great and I replaced it with TortoiseGIT (which is also good, but I like GitExtensions simplicity).

Just one question - **how to view the recent commits of the remote repository my local working folder is behind**?

I'm coming from the background of TortoiseSVN, its 'Show Log' command allows me to view the history of the **remote repository**,  as illustrated in the following screenshot:
![2019-07-12_18h35_00](https://user-images.githubusercontent.com/541197/61123243-71294f00-a4d6-11e9-8742-7db69daa0f3d.png)

**The question** is how to do this with GitExtensions? Thanks.

**Comment by pmiossec** [comment]
First you have to fetch, then:

![image](https://user-images.githubusercontent.com/460196/61125778-04e52600-a4ab-11e9-850f-cf0118bcf80e.png)

**Comment by RussKie** [comment]
Depending whether you use forks or work off the main trunk, you may need to add additional remotes and fetch all.

**Comment by edwinyzh** [comment]
Thank you very much @pmiossec and @RussKie, It works now, the missing action on my part is the **Fetch** operation.
And I go ahead and read little about it, Atlassian has a page that describes the Fetch and Pull command very clearly [here](https://www.atlassian.com/git/tutorials/syncing/git-fetch) (For people who else has the same question as mine).

Thank you again, especially @pmiossec for annotating the screenshot :)
