### ISSUE TITLE
Question: How does a maintainer contribute to a pull request from a contributors fork.

### ISSUE THREAD

**Issue by TaraBit** [gitextensions/gitextensions#6921]
How do you use Git Extensions to make corrections to a pull request from a contributors fork as a maintainer of the repository?

![image](https://user-images.githubusercontent.com/35850495/61178375-8e7f1b80-a5b1-11e9-912f-e8361a3bf61b.png)

Currently we can view github pull requests. What would be the appropriate actions for the maintainer to push changes back to those requests using git extensions interface?

**Comment by RussKie** [comment]
I add a contributor's remote, fetch it, make my changes and then push them back to the contributor's remote (if allowed).

![image](https://user-images.githubusercontent.com/4403806/61178981-88824c80-a63c-11e9-993c-411677862bd0.png)

**Comment by TaraBit** [comment]
Thank you for the detailed response.

> (if allowed).
Can you explain that a little bit more. Does that mean the maintainer has to have write access to the entire fork?

The thing is I can edit files through the github interface committing them to the request. But I've not found a way to mimic that behavior with git extensions or git commands leveraging pull and push.

It would make sense if it was possible that the maintainer would have automatic write access to the branch of pull request.

**Comment by gerhardol** [comment]
More a GitHub than GE question...

> Can you explain that a little bit more. Does that mean the maintainer has to have write access to the entire fork?

The PR submitter can choose not allow changes from maintainers.
It is possible to submit PRs to the submitters branch and of course just request changes in comments.

![image](https://user-images.githubusercontent.com/6248932/61183973-6989b780-a648-11e9-86b3-b17089acd1e4.png)

**Comment by pmiossec** [comment]
@TaraBit Also note that in the 'View pull requests...' form, you also have a button to easily add the remote and fetch.

**Comment by TaraBit** [comment]
Thanks for your response everyone!
