### ISSUE TITLE
GE crashes opening a repo that contains a branch named "head"

### ISSUE THREAD

**Issue by manuelspezzani** [gitextensions/gitextensions#6956]
## Current behaviour

GE crashes when you open a repository that contains a branch named "head".
The only workaround is to delete the branch from the commandline.

## Expected behaviour
GE is able to manage a repository with a branch named "head"

## Steps to reproduce

- open a repository
- create a new branch named "head"
- the branch is created, but after that GE crashes
- reopen the repository 
- **GE crashes** 
- open the command line and checkout a different branch
- reopen the repository
- **GE crashes**
- open the commandline and delete the "head" branch
- reopen the repository --> everything is now back to normal

## Did this work in previous version of GitExtensions

Don't know

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please check in the laster master (v3.2) - it doesn't appear to fail.

**Comment by manuelspezzani** [comment]
Correct: the latest released version (3.1.1.6049) fails, but the error seems to be fixed in master.
Thanks
