### ISSUE TITLE
Files added in a stash do not show their content when selected

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#6968]
## Current behaviour

![image](https://user-images.githubusercontent.com/350947/62121823-c7382800-b307-11e9-8822-c51810544a66.png)

This stash has modified and added files.

- When I select a modified file, its diff appears on the right.
- When I select an added file, the right side is blank as shown.

The commit window behaves differently here, showing the entire content of the file.

## Expected behaviour

I expect to see the content of the added file in the stash in the preview area on the right.

## Did this work in previous version of GitExtensions

I'm not sure.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
In 2.51.05

![image](https://user-images.githubusercontent.com/6248932/62122423-eca44200-b2c5-11e9-8916-e59300b460d8.png)

**Comment by gerhardol** [comment]
This is working in 3.3 and master
