### ISSUE TITLE
Is there a build for MacOS?

### ISSUE THREAD

**Issue by dluc** [gitextensions/gitextensions#6971]
The download link brings to a page where there's a bunch of zip files for Windows, plus some source code.  Is there a standalone build for MacOS too? At least I would expect that since the project is marketed as a cross-platform tool :-)
Thanks

**Comment by gerhardol** [comment]
v2.x supports Mono which also means MacOs, v3 is Windows only
There are some discussions bout that, see for instance #6051 

The Readme onGitHub is updated, the SourceForge page requires some tweaks regarding Mono support. @RussKie Do you have access to change the page?

**Comment by dluc** [comment]
FYI, I got here via https://git-scm.com/download/gui/mac which lists git extensions at the top, it would be a shame losing that visibility - I hope v3 will run on Mac too. Thanks

**Comment by gerhardol** [comment]
Mono was dropped as Mono support for WinForms had not evolved for 10 years which put many restrictions on the development and there were very low Mono developer involvement. GE would probably have died if the dev was not changed.

A complete GUI rewrite is a too big task (someone that has at least a year to spend on this?). Maybe if WinForms is ported to .NET Core 3.0 multi platform support can be added again.

The website will be updated, aligned with the README

**Comment by RussKie** [comment]
This was discussed in #4308.

> the SourceForge page requires some tweaks regarding Mono support.

SF is serving 2.x version to non-Windows users: 
![image](https://user-images.githubusercontent.com/4403806/62247590-7ae50900-b429-11e9-957d-cfd5a8b2312f.png)
