### ISSUE TITLE
Remote Repositories List Empty

### ISSUE THREAD

**Issue by KKendall56** [gitextensions/gitextensions#6983]
I updated to the latest edition of Git Extensions and when I try to use the clone repository function it only remembers the last remote repository I used (In the text portion) but the repository drop down list is always empty. If I look in the Settings file I can see the history but it is not being filled in. Is there some setting I am missing?

This is on a Windows 10 machine using version 3.1.1

**Comment by RussKie** [comment]
Looks like a regression.
Please try this build - https://ci.appveyor.com/api/buildjobs/8fk2uh00di2uo5mc/artifacts/Setup%2FGitExtensions-Portable-3.2.0.6383.zip
