### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by ForzaMark** [gitextensions/gitextensions#6989]
## Current behaviour

After I submit my UserName for our git Server this error occured.
Nevertheless I was able to submit my Password and push to the git Server.

## Expected behaviour

I expect that after submitting the Username a pop up opens where I can enter my password without an Exception thrown.

## Steps to reproduce

I have updated GitExtensions this morning and during my first push with the new version this error occured.
It happened after I entered my UserName for our gitServer

## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   bei ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   bei ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   bei ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   bei ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   bei GitUI.FormStatus.Done(Boolean isSuccess)
   bei GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   bei GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
``

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.19.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 144dpi (150% scaling)

**Comment by ForzaMark** [comment]
This seems to be a problem on our local Git Server

**Comment by gerhardol** [comment]
Duplicate of #6675

"ConEmu" is not related to the Git server, it is a 3rd party component used in GE
Disable ConEmu in Settings->Advanced->"Use Console Emulator" to get rid of the problem

It may be something with timing, how quickly the popup status is clicked or.
There are no known way to reproduce, if you are in a position, please try.
