### ISSUE TITLE
Icons in commit window broken

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#6990]
## Current behaviour

The "ignore whitespace" related icons have been looking weird for a while now in the commit window.

![GE-commit-window-icons](https://user-images.githubusercontent.com/663378/62498023-1259ab80-b7de-11e9-8221-d5c9d0d86155.png)

## Expected behaviour

That they are recognizable icons.

## Steps to reproduce

This may be related to fonts installed on the system or icon files missing, so I'm not sure what I can say here other than:
* Open a repo
* Make some changes
* Open the commit window and hover over the code frame to see the weird icons.

## Screenshots

See above.

## Did this work in previous version of GitExtensions

Yes. Tested this with the portable version and this worked fine up to v 3.0.2.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The icons should look like in your screenshot.
Use the tooltip to find what they do, they follow the Git functionality.
(this was changed some time after 3.0.0, maybe in 3.0.2)

The icons could look better, there were no appropriate icons in the collection normally used: http://p.yusukekamiyamane.com/
Someone good at graphics could make a contribution.

**Comment by jrfnl** [comment]
@gerhardol Oh dear... in that case, all I can say is: the previous icons were much clearer and closer to what I would expect in a GUI than the current ones.

Unfortunately I'm not a graphic artist, otherwise I'd jump at helping out with this.

**Comment by pmiossec** [comment]
Only the ones that master regex and that understand that it's linked to
regex are able to understand these icons.

I know that it's not the best for a good UX 😕

But it's difficult to imagine a better solution and we don't have a
designer to fix that 😕

**Comment by gerhardol** [comment]
The old icons and tooltip were incorrect.
The new implementation follows git-diff:
https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---ignore-cr-at-eol

In my opinion, it is betterto have icons that try to show the function together with a tooltip than nice icons of something irrelevant.

**Comment by jrfnl** [comment]
Completely fair enough on both counts. And now you've mentioned regex, they do start to make sense to me, it's just that I hadn't even recognized what they were portraying that... :see_no_evil: 

Wish I was talented enough to make them look better.
