### ISSUE TITLE
Support diff algorithm "histogram"

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#6991]
## Feature description

Git supports four different algorithms in git-diff: 
 * myers (default)
 * minimal (improved myers)
 * patience (try to give contextual diff)
 * histogram (kind of enhanced patience, normally faster too)
https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-algorithmpatienceminimalhistogrammyers
All supported in at least since Git 1.7.7

A comparision of myers vs histogram here:
https://www.researchgate.net/publication/330955835_How_Different_Are_Different_diff_Algorithms_in_Git_Use_--histogram_for_Code_Changes

Example myers vs patience.
https://gist.github.com/roryokane/6f9061d3a60c1ba41237

GE supports --patience argument (added just before histogram was added).
Of course, a custom algorithm can be configured if patience is not ticked:
```$ git config --global --add diff.algorithm histogram```

I have normally used patience as this can be configured in GE.
Cannot see much difference between patience vs histogram (not much tests).

Some ways to support histogram:
 * Just replace patience with histogram. That will give the 'best' experience for most users with a minimal effort (translations mostly)
 * Add a dropdown to select the algorithm. Should probably have a recommendation too.
 * Tooltip etc to explain how to configure this?

I propose the first alternative, to keep it simple.

## Environment
- Git Extensions 3.2.0
- Build gpg: Signature made Sat Aug  3 21:50:59 2019;gpg:                using RSA key ;f9bc9e76f2bee9687f57088d1262d371dd2dae46 (Dirty)
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I'm not opposed to changing it.
