### ISSUE TITLE
Click & Drag Text in ComboBox

### ISSUE THREAD

**Issue by BOBJohnson** [gitextensions/gitextensions#6992]
## Current behaviour

In several dialogs where there is an editable combobox (you can type custom text into the textbox portion), I cannot click and drag the cursor to select text. Two example places this is happening: the branch drop down in the Checkout branch dialog, and the branch drop down in the Merge branch dialog.

## Expected behaviour

When clicking & dragging the cursor over text, the text should become highlighted.

## Steps to reproduce

Open the Merge branch dialog. Try to click and drag the mouse cursor over the branch name text in the branch drop down. The text won't get selected.

## Did this work in previous version of GitExtensions

I think so, but unsure of the version it last worked - this is a fresh PC install.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I think this maybe a WinForms issue. 
We had to fix it in WinForms Core recently and the issue was reported as existing in .NET 4.8 (it was fixed too). More info - https://github.com/dotnet/winforms/issues/465

**Comment by BOBJohnson** [comment]
Ah thanks for letting me know. 4.8 the gift that keeps on giving. Ever since I upgraded to 4.8 I've had issues in VS 2019 and other things - and I can't for the life of me figure out how to get rid of 4.8 for the time being.
