### ISSUE TITLE
Commit Message Text field stays deactivated after fixup commit

### ISSUE THREAD

**Issue by mezen** [gitextensions/gitextensions#6993]
## Current behaviour

* Start making a fixup commit
  * Commit message text field is deactivated
* Do the commit
  * Commit window stays open (as configured)
  * Commit message text field stays deactivated
  * Also other controls like checkbox for amend commit stays deactivated
* Close and reopen commit window
  * Commit message text field is activated again

## Expected behaviour

After making a fixup commit all controls, in special the commit message text field, should be activated again

## Workaround

Reopen commit window

## Environment

- GitExtensions version: 3.1.1.6049 (Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96)
- GIT version: git version 2.22.0.windows.1
- OS version: Windows 10 1607

**Comment by drewnoakes** [comment]
I hit this daily. I missed the rationale behind making it readonly for fixup commits, but personally I don't find that feature useful.

**Comment by gerhardol** [comment]
This was changed in #6530 
The reason was that fixup! commits o not work as intended if you change the text
However, after commit, the commit should be normal again
@mstv

**Comment by drewnoakes** [comment]
> The reason was that fixup! commits o not work as intended if you change the text

Reasons I may want to edit the fixup comment:

- I change my mind and decide I don't want to fixup
- I realise the previous commit message is inadequate and so change to squash and add more text
- I want to add a comment to see later when authoring the rebase script (without `--autosquash`)

Locking the textbox puts the UI into a state that's slow to get out of. You must close the commit form, then relaunch it.

I want the UI to help me, not protect me from myself.

I'd rather see the ability to select a commit to fixup into in the commit form directly, though of course this is considerably more work.

**Comment by mstv** [comment]
I fully agree that this issue describes a bug - regarding the option "don't close" which I was not aware of.

#6530 fixed an evil bug: I have lost several longer commit messages when I closed the `FormCommit` temporarily, because GE thought it was a non-standard commit.

Far before, somebody decided to protect the users from theirselves - though quite incompletely: The commit message of `fixup` and `squash` commits is not stored on form close (which is even verified by test cases). This was not indicated to the user.
So why not store any commit message? At least if it was altered by the user.

**Comment by gerhardol** [comment]
I can live with this functionality, quiting Commit is OK (I agree it is a bug still, just that it has a low urgency for me).
But for fixup I still prefer to improve the rebase editor as suggested in #5161 (by @drewnoakes ).
(Then I may not even use fixup commits)

**Comment by mstv** [comment]
Unfortunately, I cannot test it because switching off `Close dialog after each commit` has no effect neither with a current build nor with portable v3.1.1 - very strange.

**Comment by gerhardol** [comment]
> Unfortunately, I cannot test it because switching off Close dialog after each commit has no effect neither with a current build nor with portable v3.1.1 - very strange.

UI is bad: You need to explicitly tick Close after commit.
