### ISSUE TITLE
Export/Import favourite repositories

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#7001]
Export/Import favourite repositories to file feature would be fine.

Also backport to Git Extensions v2.5.x version would be useful to import my old Favorites.

**Comment by RussKie** [comment]
V3.0 imports and converts all favourites into the new format.

**Comment by klorinczi** [comment]
Using Export user could backup the favorites and Import/Restore them on another computer.

**Comment by gerhardol** [comment]
If the repo paths do not exist, should they be cloned?
If the paths do not exist, should they be created?
What if the disks does not exist?
If the user has one or many base clone paths that does not exist, should the import search for matches and offer them?
How to handle worktrees?
How to handle local branches?
+ many other questions.
Not so easy as it seems.

I cannot see this high on any priority list.

**Comment by RussKie** [comment]
It seems to be a feature of questionable value - you need to have all the
same folders at the same paths on another device...

So I don't think it is something we will be implementing.
