### ISSUE TITLE
Forget about autostash

### ISSUE THREAD

**Issue by palver123** [gitextensions/gitextensions#7005]
Hi!

## Feature description

In a recent version something changed and pull keeps remembering autostash option whenever I use it. I definitely do not want that. It sort of kills Visual Studio with big stashes and have to restart my IDE all the time...

My proposal is that we should rollback to the previous behaviour (opt-in), where I had to check autostash if I wanted it. Opting-out of it **every single time** makes me hate this otherwise handy feature. It is not the unchecking of the checkbox that I hate (I am lazy but not _this lazy_), it is the Visual Studio Solution reload I get every time my working directory changes are stashed and (again!) when the stash is popped.

With pulling becoming such a nuisance I started hating frequent pulling which is a big problem in effective teamwork...

\+ It also resets my staging area!

## Environment

- Git Extensions 3.1.1.6049 (and some older versions after v3)
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by palver123** [comment]
I believe this is the commit that introduced the change: 7ae5da5cb961583bd6b676e2757552f5c6727dff

**Comment by RussKie** [comment]
The auto-stash settings was restored in the mentioned commit to how it was working prior to v3.0, in which we regressed (see: b6c103e910ffca4462e9cbbbe080a26d68587bfb).

Looking through the history auto-stash state was restored in `FormPull.UpdateSettingsDuringPull()` method in [v2.51.05](https://github.com/gitextensions/gitextensions/blob/v2.51.05/GitUI/CommandsDialogs/FormPull.cs#L659-L669) (Sep '18) and as far back as [v2.47.3](https://github.com/gitextensions/gitextensions/blob/2.47.3/GitUI/CommandsDialogs/FormPull.cs#L562-L572) (Nov '13).

**Comment by palver123** [comment]
I am still very irritated by this feature.  I understand this is a question of preference and habits/workflows. As most UX decisions...

Is there a way to cast a vote among the maintainers?

If no, this issue can be closed. If yes, I propose a vote.

**Comment by mstv** [comment]
Perhaps a workaround: I do not use pull at all because I want to know what will happen: I `fetch (all)` and `reset current branch to here` with `reset type` `mixed` (or `soft`).

**Comment by RussKie** [comment]
> Is there a way to cast a vote among the maintainers? Maybe write the question in a comment and use GitHub reactions?

Sure, if there is a strong community demand to change we will consider it.

**Comment by palver123** [comment]
Closing because it is more of an opinion thing, than a bug/feature
