### ISSUE TITLE
Branches pane should allow branch creation in folder context menu

### ISSUE THREAD

**Issue by kaesaecracker** [gitextensions/gitextensions#7013]
## Feature description

When you have branches named like `foo/bar1` and `foo/bar2`, the branches pane shows "folders". In the tree view you have `foo` with children `bar1` and `bar2`. The context menu for `foo` should have an option for creating a new branch. The name should be pre-filled with `foo/`.

The reason for this is that I use this feature to group branches by ticket id. When I mistype the ticket id, the grouping obviously does not work.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 120dpi (125% scaling)

**Comment by mstajnc** [comment]
it seems that this issue can be closed now as it works as intended, does it not?

**Comment by RussKie** [comment]
Thank you for the follow up
