### ISSUE TITLE
Wrong cursor selector when resizing

### ISSUE THREAD

**Issue by IkaTheFox** [gitextensions/gitextensions#7015]
### Current behaviour:
On the settings window, when resizing/hovering the bottom and bottom-left corner, the cursor used is nwse (diagonal 1 resizing) for both.

### Expected behaviour:
When resizing or hovering the bottom or bottom-left corner, the cursor displayed is ns (vertical resizing) and nesw (diagonal 2 resizing), respectively.

### Screenshot
![Clipboard01](https://user-images.githubusercontent.com/28457923/62958980-0bdbbd00-bdf8-11e9-9ba3-37c3fe4df107.jpg)

### Did this work in previous version of GitExtensions
Do not know.

### Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by LukeOwlclaw** [comment]
I cannot reproduce the problem, I have an idea though: Do other windows on your system show the same wrong behavior? If so, the corresponding Windows setting was likely changed:

![image](https://user-images.githubusercontent.com/2737900/63016411-e7cdb980-be93-11e9-91bb-b90ce9bdb722.png)

**Comment by gerhardol** [comment]
Cannot reproduce myself.
There are no such cursor icons either.
Not sure if this is handled by WinForms or .NET
