### ISSUE TITLE
Show all commits on current branch

### ISSUE THREAD

**Issue by iaswtw** [gitextensions/gitextensions#7016]
## Feature description
I want GitExtensions to show the equivalent of this git command line:

    git log --oneline master..my-feature-branch --no-merges

i.e. a list of all commits on a feature branch, ignoring merges from other branches.

The first branch should be selectable, not necessarily `master`. 

As of version GitExtensions 3.1.1, I can approximate this functionality by checking "Show current branch only" and "Show first parents".  By doing this, I see two things I don't want to see -

1. merge commits for merges from other branches (e.g. master)
2. PR merge commits past my first commit on the feature branch.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0

**Comment by gerhardol** [comment]
I am not convinced that this is a feature GE needs, there are quite some options already and most are not well documented.

**Comment by RussKie** [comment]
This isn't something will be adding.
