### ISSUE TITLE
[NBug] Der Pfad hat ein ungültiges Format.

### ISSUE THREAD

**Issue by Chaisy** [gitextensions/gitextensions#7018]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Der Pfad hat ein ungültiges Format.
   bei System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   bei System.IO.Path.InternalGetDirectoryName(String path)
   bei GitCommands.Submodules.SubmoduleStatusProvider.GetSuperProjectRepositorySubmodulesStructure(GitModule currentModule, SubmoduleInfoResult result, String noBranchText)
   bei GitCommands.Submodules.SubmoduleStatusProvider.<>c__DisplayClass16_0.<<UpdateSubmodulesStructure>b__0>d.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by Chaisy** [comment]
Sorry for not reading the rules before posting. I was in a rush.. and yea. I'm sorry guys.

**Comment by gerhardol** [comment]
Duplicate of #6599
Corrected in 3.2

**Comment by Chaisy** [comment]
> Thank you for the bug report 👍
> 
> Sadly, it appears some important information is still missing, which you may have overlooked while submitting the bug.
> Without this information we may not be able to assist you in resolving the issue.
> 
> Please review your submission, fill the missing information in and post a new comment to ping us back to re-open the issue.
> Thanks again

as it seems to be a duplication, i think I'll not use my time in describing the bug.
But in the future i know which rules to respect.

Sorry

**Comment by gerhardol** [comment]
No problem. The NBug direct reporting has raised the number of issues quite a lot and the team is a little to small to handle that in a great way. We will close (with the bot) a little aggressively due to that, but use the issues for 'statistics' to find patterns.
This specific issue should have been fixed too, so no info needed.
