### ISSUE TITLE
Pull form items clipped on HiDPI scaled displays 

### ISSUE THREAD

**Issue by phdussud** [gitextensions/gitextensions#7020]
## Current behaviour

some of the options in the pull form are clipped or hidden when a HiDPI is scaled or if the text is scaled (Win10 1903 option). 

## Expected behaviour
The form should display all of the options 

## Steps to reproduce

Set a display scaling to 150% or set the text scaled to 150%,
Start Get Extensions and display the pull form

## Did this work in previous version of GitExtensions

No

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0

## Diagnostics

See my original posting.

**Comment by gerhardol** [comment]
Please fill in all information and reopen when done

**Comment by phdussud** [comment]
I hope I got the template filled correctly.... 
Thanks! 
Patrick

**Comment by phdussud** [comment]
Sorry, I am not sure how to re-open this issue...

**Comment by gerhardol** [comment]
Please provide a screenshot too

**Comment by phdussud** [comment]
Here is a screenshot illustrating the problem when display text scaling is set to 150%
![pull-form-150p-font](https://user-images.githubusercontent.com/7013727/63119036-0a270c00-bf54-11e9-9436-2e9f2aacb2e7.png)

**Comment by pmiossec** [comment]
Maybe the same problem than #6898?

**Comment by phdussud** [comment]
As I said in the original issue post, the problem seems to be with the 4 GroupBox items contained in the form. Their AutoSize property isn't set to true so they don't resize when the contained controls are resized. Hence the clipping. I verified that setting their AutoSize properties to true fixes the problem in both Display scaling and Text scaling situations

**Comment by phdussud** [comment]
I don't think it is. It shows clipping at 125% as well.

**Comment by phdussud** [comment]
> Maybe the same problem than #6898?

I don't think it is. It shows clipping at 125% as well.

**Comment by pmiossec** [comment]
>I verified that setting their AutoSize properties to true fixes the problem in both Display scaling and Text scaling situations

If you found the solution, could you please create a pull request to fix the bug (and sign the CLA in another one)?

Your the best placed to do it and that would be very kind.

**Comment by phdussud** [comment]
> > I verified that setting their AutoSize properties to true fixes the problem in both Display scaling and Text scaling situations
> 
> If you found the solution, could you please create a pull request to fix the bug (and sign the CLA in another one)?
> 
> Your the best placed to do it and that would be very kind.

I did this. Unfortunately my second pull request for CLA got merged in my first one :(
