### ISSUE TITLE
[NBug] The file name or extension is too long

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#7024]
%0A%0A:warning: The sections below must be filled in and this text must be removed or the issue will be closed.%0A%0A## Current behaviour%0A%0A%0A%0A%0A## Expected behaviour%0A%0A%0A## Steps to reproduce%0A%0A%0A%0A%0A## Error Details%0D%0A```%0D%0ASystem.ComponentModel.Win32Exception (0x80004005): A fájlnév vagy a kiterjesztés túl hosszú%0D%0A a következő helyen: System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)%0D%0A a következő helyen: GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)%0D%0A a következő helyen: GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)%0D%0A a következő helyen: GitCommands.ExecutableExtensions.<RunCommandAsync>d__5.MoveNext()%0D%0A--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---%0D%0A a következő helyen: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()%0D%0A %2.

**Comment by klorinczi** [comment]
Crash happened, when selected a lot files in GitExtensions v3.1.1.6049 within Diff tab, then in context menu selected to Reset files to First branch.

It seems selecting too much file to reset results crash.

**Comment by gerhardol** [comment]
The report is corrupted somehow, was the info changed somehow when submitting? What browser? What charset?
It also seem like the info is truncated too, this stacktrace should be longer.

The problem with resetting too many files at one time is reported, I believe (similar to staging many files at the same time).

**Comment by gerhardol** [comment]
Duplicate of #6593

**Comment by klorinczi** [comment]
The send button opened a browser window, but only an URL encoded string was displayed.

I just copied the string to a new issue I opened manually. 

The automatic bug reporting seems to be fail.

**Comment by gerhardol** [comment]
The URL will create an issue with the stacktrace, you have to fill in the recreate information.
If that does not work, the NBug window has a copy button to provide the information.

What webbrowser, had you logged to GitHub etc.
Any problems reaching GitHub, any service down etc.
This has been working for all other reports we have seen.

**Comment by klorinczi** [comment]
Well, it did not work this time.
