### ISSUE TITLE
Selecting too much file to reset results crash

### ISSUE THREAD

**Issue by klorinczi** [gitextensions/gitextensions#7025]
## Current behaviour
Crash happened, when selected a lot files in GitExtensions v3.1.1.6049 within Diff tab, then in context menu selected to Reset files to First branch.

It seems selecting too much file to reset results crash.

## Environment

- GitExtensions version: 3.1.1.6049
- GIT version: 2.10
- OS version: Windows 7
- .NET version:

**Comment by gerhardol** [comment]
Duplicate of #6593 
Also reported in #7024, that has a partial stacktrace
