### ISSUE TITLE
Forgets histroy and settings and asks for language at start up

### ISSUE THREAD

**Issue by yowl** [gitextensions/gitextensions#7041]
## Current behaviour

A bit like #1806 but does not ask about Putty.  Starting the program, all previous repos are forgotten and the app asks for the language with the flag.

## Expected behaviour

Repos should be remembered and no need to ask for the language when starting the app if its already been selected

## Steps to reproduce

This is random as far as I can tell, only information I can give is that today it happened first time after booting.

## Did this work in previous version of GitExtensions

Yes, 

## Environment

- GitExtensions version:3.1.1.6049
- GIT version: 2.22.0.windows.1
- OS version: NT 10.0.18362.0
- .NET version: 4.8.3815.0

## Diagnostics

No git commands run

**Comment by RussKie** [comment]
This could only happen if the app's config somehow got removed, i.e. `C:\Users\<user>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings`.

**Comment by yowl** [comment]
Thanks, next time it happens, before doing anything else I'll check that folder.

**Comment by szmcdull** [comment]
I have this file present but still every time it pop up the language selection and then the settings window

> This could only happen if the app's config somehow got removed, i.e. `C:\Users\<user>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings`.

**Comment by RussKie** [comment]
There no point going grave digging. Please open a new issue if you're experiencing some problems.

**Comment by vbjay** [comment]
Also configure correctly and then close app. May be issue of multiple instances running and last one closed wining the config fight.
