### ISSUE TITLE
"Copy to Clipboard" context menu entry missing triangle on startup

### ISSUE THREAD

**Issue by KarstenRa** [gitextensions/gitextensions#7046]
## Current behaviour
The first time after startup the arrow/triangle at the commit grid and the file history context menu for the "Copy to Clipboard" entry is missing. It is kind of irritating since it is unclear what the entry will copy until you realize there is a submenu. After the first time the submenu is opened the arrow is present all the time.

## Expected behaviour
An arrow/triangle signaling that the menu entry has a submenu.

## Steps to reproduce
Open context menu on the commits grid after start up.

## Screenshots
![copytoclipboard](https://user-images.githubusercontent.com/26045339/63639463-84156e80-c693-11e9-8804-e169ada7a1d3.png)

## Did this work in previous version of GitExtensions
Don't know

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 120dpi (125% scaling)

**Comment by KarstenRa** [comment]
It seems like this part of `OnDropDownOpening `in `CopyContextMenuItem` does have no function anymore:
```
if (sender == null)
{
  // create the initial dummy menu on a dummy revision
   revisions = new List<GitRevision> { new GitRevision(GitUIPluginInterfaces.ObjectId.WorkTreeId) };
}
```
Since there is no revision function set, no items are added to the submenu. Comments say it is there to make the shortcuts work but after removing it, ctrl+c still copys the hash.
Maybe this dummy revision can be removed and a simple dummy entry can be used to make the menu appear like an openable menu at startup (with a little triange). E.g. the constructor could look like this:
```
public CopyContextMenuItem()
{
  Image = Images.CopyToClipboard;
  Text = _copyToClipboardText.Text;

  DropDownItems.Add(new ToolStripMenuItem());
}
```

I think the cleanest solution would be to make the menu fill up on an event triggered as soon as the "Copy to Clipboard" caption is visible (at parent context menu open) but I do not now such an event and making a "UpdateMenu" function that has to be called by each component using the `CopyContextMenuItem` would be error-prone.

**Comment by gerhardol** [comment]
Seem OK (briefly looked at PR), probably leaving this for next version though.
