### ISSUE TITLE
"Open repository" window crashes every time

### ISSUE THREAD

**Issue by CellarDoor00** [gitextensions/gitextensions#7071]
Git Extensions v3.1.1.6049
Git v2.23.0
Environment: Windows 10 Pro 64-bit, Intel i7-7700, 3.6 GHz, 32 GB RAM

Had v3.1.1 running fine up to now. Today I rebooted the PC, and now whenever I open *any* repo with Open Repository context menu, the window is displayed, but is unresponsive and crashes within 10 sec or so:

![Screen Shot 2019-08-28 at 1 42 00 PM](https://user-images.githubusercontent.com/40150567/63879699-3a31ce80-c99a-11e9-9cc1-36a1b4d633a6.png)

Clicking on Debug and opening in VS2013, I get the following error. Not sure if it's due to debugging itself or whether that's the actual error that's causing my problem.

![Screen Shot 2019-08-28 at 1 48 16 PM](https://user-images.githubusercontent.com/40150567/63879913-a9a7be00-c99a-11e9-9ccd-acdb49d6c01f.png)

Only this window ("Open repo") crashes. If I select context menus for commit, push, pull, settings and other windows, they open ok and don't crash.

Tried various things, but issue still persists:
- Uninstall / re-install 3.1.1
- Installed 3.1.0 and 3.0.0
- Rebooted PC several times
- Removed old .gitconfig
- Removed c:\users\user_name\AppData\Roaming\GitExtensions

Additional info: yesterday I started playing with submodules for the first time; created a test submodule, pushed to remote, etc. Had no issues. The issue started after PC reboot. It's possible there was some Windows update during the reboot, potentially causing this problem.

**Comment by gerhardol** [comment]
You need to include the stacktrace, use Copy in NBug
(Send and quit would have done this automatically.)

**Comment by CellarDoor00** [comment]
After logging into the PC today, it's working fine, no crash. Nothing really changed in the system. Not sure what's going on.

**Comment by gerhardol** [comment]
The stacktrace has no GE calls. No explanation to that or what may have caused the problem,

**Comment by CellarDoor00** [comment]
ok, that's weird. well, the issue seems to have resolved itself, so can close for now.
