### ISSUE TITLE
[NBug] Ошибка чтения каталога C:\Develop\Projects\statistic\.

### ISSUE THREAD

**Issue by orphan** [gitextensions/gitextensions#7074]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.FileNotFoundException: Ошибка чтения каталога C:\Develop\Projects\statistic\.
   в System.IO.FileSystemWatcher.StartRaisingEvents()
   в GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   в System.Windows.Forms.Timer.OnTick(EventArgs e)
   в System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6812
Corrected in #6834 (to be included in 3.2)
