### ISSUE TITLE
Unicode support in commit message textbox broken

### ISSUE THREAD

**Issue by generateui** [gitextensions/gitextensions#7078]
1. Open commit window
2. Press ⊞ + . (windows+dot key combo)
3. Select emoji

Note that the emoji is not correctly rendered

https://imgur.com/a/SthdMmu

**Comment by JuergenRB** [comment]
The problem seems to exist only in the commit window - you can add emojis in the template window
![image](https://user-images.githubusercontent.com/22403655/194833615-b2832866-d701-495d-a9ab-b0605309162c.png)

**Comment by RussKie** [comment]
@JuergenRB in what version of Git Extensions did you test?

**Comment by JuergenRB** [comment]
> @JuergenRB in what version of Git Extensions did you test?

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.14393.0
- .NET Framework 4.8.4510.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
v3.5 is running on .NET Framework, which is using RichEdit 2.1 control, IIRC. The dev branch and v4 are running on .NET 6, which is using RichEdit 4.1 control, which is newer, and has some new different (not necessarily better) behaviours.
