### ISSUE TITLE
Allow filter in staged file list

### ISSUE THREAD

**Issue by maulwuff** [gitextensions/gitextensions#7085]
## Feature description

The commit dialog allows to filter files as long as they are unstaged.
Staged files, however, can't be filtered. This makes it difficult to find a certain file, when there are lots of files staged, which is rather time consuming to locate the file by hand.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
You can filter in the browse window, using the index artificial commit.
Low prio for me, I maybe even want to show an extra entry in the list myself.
But I would probably not vote against a PR.

**Comment by RussKie** [comment]
We need to unify the functionality across several windows, e.g. the history
window lacks the same

**Comment by maulwuff** [comment]
> 
> 
> You can filter in the browse window, using the index artificial commit.
> Low prio for me, I maybe even want to show an extra entry in the list myself.
> But I would probably not vote against a PR.

nice! This avoids the nasty *modal* commit form as well ;-)

**Comment by mstv** [comment]
Fixed by #7496
