### ISSUE TITLE
GE fails to identify .git folder at root of drive from cmd line

### ISSUE THREAD

**Issue by Fulgan** [gitextensions/gitextensions#7086]
## Current behaviour

When using GITExtension's explorer context menu on a repository that is located at the root of a drive on a file or folder that is NOT at the root, it fails to find the .git folder and issue the following message instead:

`The current directory is not a valid git repository.`

## Expected behaviour

The repository should be found even if at the root of the drive.

## Steps to reproduce

Use any local repository that contains sub-folders. 
Map it to a new drive using either subst or net use. 
Navigate to the newly mapped drive letter, go inside a folder (any folder).
Right-click on any file in the repo and select "File history..." (or any other GE option, really).

## Screenshots

![image](https://user-images.githubusercontent.com/3026545/64114201-b2c6cf80-cd8c-11e9-9c8f-2d44a1b0da56.png)
![image](https://user-images.githubusercontent.com/3026545/64114216-b8bcb080-cd8c-11e9-887f-e580f4565272.png)
![image](https://user-images.githubusercontent.com/3026545/64114225-bd816480-cd8c-11e9-899e-9ff51ec73e3f.png)

## Did this work in previous version of GitExtensions

No

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
If I create a Git repo on the root of an USB, it can be opened OK (I used master though)

The drives created with subst or net use are not visible in Explorer and therefore not visible to GE (they are visible from cmd though).

So I do not see a problem in GE.

**Comment by Fulgan** [comment]
Drives created in explorer are **DEFINITELY** visible by explorer: just make sure you don't create them from an elevated promt.

Furthermore, files at the root of the drive (where the .git folder is located) will work fine: it's files in subfolders that won't work.

**Comment by Fulgan** [comment]
To make it easier for you, here is a small list of commands that will let you reproducet the issue. The only requirements are:
- The commands to be run from a non-elevated command line
- The commands to be run in the root of the gitextension repository (where the .git folder is)
- The local drive letter "n" must be available.

```
subst n: .
cd /d n:\GitCommands\
gitextensions filehistory n:\GitCommands\AppTitleGenerator.cs
```

**Comment by gerhardol** [comment]
> To make it easier for you, here is a small list of commands that will let you reproducet the issue.

Of course detailed instructions helps. I do have other things in my life than trying to find issues.

The issue was that root directories were skipped unless they were the first to be tested (so further steps down would have been affected).

> gitextensions filehistory n:\GitCommands\AppTitleGenerator.cs

command line is the only problem I have seen, even if there could be more.

I have submitted a PR, but all affected situations are not affected, if there are regressions for other functionality. I would be hesitant to to merge this in 3.2 but to target 3.3.

Please test the portable build for the PR though.

**Comment by Fulgan** [comment]
Thank you for the fix.

I have cloned and built the source from your PR and I can confirm that all issues related to this problem have apparently been fixed. I have updated my local installation with this new version and I'll come if I notice anything related.
