### ISSUE TITLE
Don't block commit message textbox for fixup! squash! commits

### ISSUE THREAD

**Issue by mdonatas** [gitextensions/gitextensions#7104]
## Don't block commit message textbox for fixup! or squash! commits

I feel that changes
> disable changing the commit message and amending a commit unless CommitKind.Normal

introduced in https://github.com/gitextensions/gitextensions/pull/6530 limit the user in some situations which are valid:

- Open commit dialog in fixup mode and change your mind - previously we could've just deleted the text
- Turn current latest commit into a fixup commit.. not possible without typing fixup! manually as amend is disabled
- Open commit dialog in fixup mode, commit part of the files and the make another regular commit (covered by #6993)

I find myself hitting the "readonly wall" quite often in at least two of the above cases.

The proposal would be to revert this behavior to enable more flexible usage scenarios.

## Environment

- Git Extensions 3.2.0
- Build 3010403a6229cafa8a364f60ec2a2ee4517fcb26 (Dirty)
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 192dpi (200% scaling)

**Comment by sharwell** [comment]
I've been surprisingly happy with the behavior of making the text box read-only for these scenarios, so I'm interested in exploring additional proposals that do not simply revert it.

**Comment by mdonatas** [comment]
How did making it read only improve your workflow? One thing I can come up with is that if you leave `!fixup` part but change the message then this would not fixup anything.

**Comment by sharwell** [comment]
@mdonatas It made it more obvious that the message was a specially-crafted message to fixup a specific previous commit, so I spent less time trying to figure out if I'm supposed to make changes there.

**Comment by mdonatas** [comment]
![image](https://user-images.githubusercontent.com/483659/64355797-7c968380-d00a-11e9-8bd0-65e444e5b6c6.png)
☝ would it help to highlight the keywords with some color?

**Comment by gerhardol** [comment]
The change in #6530 is as expected to me (except for #6993).
This change has helped me to explain the feature to other users.

If you do want to change the commit message, why use the fixup feature at all? Only reason I can think of is that you do not want to create a fixup commit but a squash commit with help text to fit it in. I find that less important than the guidance #6530 has given. (Why is not someone implementing #5161?)

**Comment by mdonatas** [comment]
You'd want to change the message if you wanted to revert to making a regular commit after reviewing uncommited changes. This inability to change my mind has been very frustrating.
Highlighting `fixup!` or `squash!` keywords seems like a good middle ground. It signals that this a special commit as well as allows the user to remove the message completely.

The reason I value Git Extension is that it's not opinionated - if git has a valid workflow in shell then Git Extensions does a good job of exposing that. This is the core reason why I care about GE a lot.

Clarity is also important but it should not block valid scenarios. What do you and others think about signaling user with text highlight?

**Comment by pmiossec** [comment]
>What do you and others think about signaling user with text highlight?

Or, another solution, we could keep the readonly, which is better by preventing the user to change the commit message.
And add a button 'Cancel fixup/squash' only visible when the textbox is readonly.

**Comment by mdonatas** [comment]
that's also a valid solution ☝

**Comment by mdonatas** [comment]
oh and `amend` shouldn't be disabled in either case. It's a totally valid scenario to turn the latest commit into a `fixup!` commit.

**Comment by crypto-rsa** [comment]
Also the readonly flag should be removed once a commit is made since only a subset of the uncommited changes might have been used in the `fixup!`. After that, I might (and often do!) want to make another, _regular_, commit.

**Comment by mdonatas** [comment]
Yep! @gerhardol pointed at a bug #6993 which is exactly about that
