### ISSUE TITLE
Main window some elems don't follow windows color theme.

### ISSUE THREAD

**Issue by dvdotsenko** [gitextensions/gitextensions#711]
The commit list and summary areas of the main user interface window do not seem to follow Windows color theme. The background is white in all cases.

I am using a High Contrast color theme (the one designed for visually-impaired users) on Windows 7. It uses black background and light green text for "Window", "Menu", "3D Objects" GUI elements. With that, the main commits list in Git Ext 2.26 is light-green  text on top of white background, which is very hard to see.

I'll try to mock up a patch for this in the coming weeks, but if someone gets to it sooner, would be highly appreciated.

**Comment by Mnuzz** [comment]
This would be really nice to have. Seems it's been awhile since this issue was opened.

**Comment by RussKie** [comment]
High contrast white Win 10 theme doesn't look too bad:
![image](https://user-images.githubusercontent.com/4403806/33655723-fe3cdbe4-dac7-11e7-9eb5-271421dd14c4.png)

High contrast black looks generally ok, albeit the highlight of the commits for the selected author needs work:
![image](https://user-images.githubusercontent.com/4403806/33655816-3c90c7e8-dac8-11e7-8826-d1069035a218.png)


What is causing you dramas?

**Comment by Mnuzz** [comment]
@RussKie I had long since forked and patched this on my own, so I don't have a screenshot. But the theme I use is High Contast #1, which is different from black

**Comment by RussKie** [comment]
I tried it too, was similar to the black one

**Comment by Mnuzz** [comment]
@RussKie You could try it with the version which was current at the time of my original post (Version 2.49), to confirm if it has been fixed since then in a later version. I had this issue on multiple machines, so I know it is a problem. It was on the commit highlighting. The descriptions of commits that were either highlighted or not highlighted (can't remember) were the same color as the background.

**Comment by Mnuzz** [comment]
Windows 10, to be clear

**Comment by RussKie** [comment]
The author highlight is user configurable
![image](https://user-images.githubusercontent.com/4403806/33701988-9d59fa42-db75-11e7-8344-5748b128decc.png)

I'm closing this issue as resoled.
If you have any a concrete issue with the current version please either report here or open an new issue.

**Comment by Mnuzz** [comment]
@RussKie Thanks very much for your help. Next time I am using a windows machine for development I will give it a try!
