### ISSUE TITLE
Continue rebase via hotkey 

### ISSUE THREAD

**Issue by forger** [gitextensions/gitextensions#7110]
## Feature description
When in the middle of a rebase (shown by the WarningToolStripItem "You are in the middle of a rebase" at the bottom of the Browse form), I'd like to continue the rebase using a hotkey.

This is afaik the only remaining step for completing an interactive rebase including manually edited commits using only the keyboard which would be great :)

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0

## Note
I've dug through the source a bit and think I understand that the UICommands.StartTheContinueRebaseDialog() command is responsible for opening the dialog. If that could be exposed to be triggered by a configurable hotkey that might be all there is to it.
Would that be the way to go?

**Comment by mstv** [comment]
@forger, do you have a proposal for the default hotkey?
It could be added to `HotkeySettingsManager.CreateDefaultSettings()` and to `FormBrowse.ExecuteCommand(int cmd)`. It would be great if you could create a pull request for this extension. We will support you if there arise questions.

**Comment by pmiossec** [comment]
And if we update the button label to "&Continue rebase" to be able to use
'alt+c'?

**Comment by mstv** [comment]
> And if we update the button label to "&Continue rebase" to be able to use
'alt+c'?

Though `Alt+C` is already bound to the main menu `&Commands`.
"C&ontinue ..." should work.

I guess this issue applies to unfinished merges, too.

**Comment by forger** [comment]
@mstv 
> do you have a proposal for the default hotkey?
- Nah, I'm happy to take suggestions from someone who knows the existing key bindings better.
> It could be added to HotkeySettingsManager.CreateDefaultSettings() and to FormBrowse.ExecuteCommand(int cmd). It would be great if you could create a pull request for this extension. We will support you if there arise questions.
- Thanks for the hints :) I'll see if I can bang sth. together next week.
> I guess this issue applies to unfinished merges, too.
- Guess so. Another (probably very similar) hotkey for that? There's also the WarningToolStripItem telling you about unresolved conflicts (or do you mean that one?).
Alterntively, I could add a FocusWarningToolStrip command + hotkey (the Focus... commands seem to be a pattern in the Browse form) to focus the first (visible) Item in the WarningToolStrip and then [Tab] or arrows to cycle through them. That way you don't waste a hotkey for each item. Another possibility would be to treat the WarningToolStrip like a (dismissible) dialog and focus it by default, if there's an item in it. Let me know what you think.

@pmiossec 
> And if we update the button label to "&Continue rebase" to be able to use
'alt+c'?
- Not sure I understand which button you propose to relabel and how that is connected to being able to use [Alt+C]. Are you suggesting to 1) relabel the WarningToolStripItem "You are in the middle of a rebase" to "Continue rebase" and 2) use [Alt+C] as the default binding to "click" it and continue the rebase from the FormBrowse?
I'd be happy to do 1) but see the same problem with 2) that @mstv mentioned above; I'd expect [Alt+letter] to navigate the menu, not activate a contextual warning at the bottom of the form.

**Comment by mstv** [comment]
@forger, `Alt+letter` hotkeys are used for menus _and_ buttons. The `WarningToolStripItem` is clickable, i.e. it behaves like a button. I've added a verb which describes what will happen on click, to all these warnings. There should only be one such warning at a time, hence they can share the same hotkey.

**Comment by forger** [comment]
@mstv
> Alt+letter hotkeys are used for menus and buttons.
- Thanks for the clarification.
> The WarningToolStripItem is clickable, i.e. it behaves like a button. I've added a verb which describes what will happen on click, to all these warnings.
- Yeah, seen it and thanks for taking care of that. I have to say they're a little wordy for my taste now... I understood @pmiossec 's proposal to be replacing instead of amending the existing labels. I liked the idea because "Continue rebase" actually has more of a "click me" command character and implies by its visibility that you are in the middle of a rebase. So the latter info feels kind of redundant.
- On the other hand those quasi-buttons are in an unusual part of the UI (where I wouldn't expect a button) and are not styled like buttons either. For me it never really felt intuitive to click them. It's kind of a thing I learned because I didn't know how else to go on and just tried it. So I like the idea of making them more visible and having more text is one way of doing it. I just don't know if it's the best way because I personally dislike wordy UIs. Lazy eyes I guess :)
What would you say about giving them a more button-like style, maybe even making them a bit bigger and just labeling them as commands - "Solve conflicts", "Continue rebase" and so on? I think it could give the user some better visual clues on what to do next.

> There should only be one such warning at a time, hence they can share the same hotkey.
- I can at least reproduce two warnings being visible in that bottom bar at the same time: Just rebase creating some conflict and then don't resolve it. You'll see the warning for unresolved conflicts next to the one telling you about being in the middle of a rebase.

**Comment by forger** [comment]
@pmiossec ignore my previous question, @mstv 's comment helped to clarify. I wasn't familiar with the &-prefix for command hotkeys and didn't connect the dots.
