### ISSUE TITLE
Unable to edit gitextensions Translation file using poedit

### ISSUE THREAD

**Issue by dingpengyu** [gitextensions/gitextensions#7114]
Hello developer
I have the following problems during the process of editing the Git Extensions using poedit:
[Window Title] Poedit Error [Content] An exception that could not be handled: Error loading file "E:\Source\Repos\gitextensions\GitUI\Translation\Simplified Chinese.xlf": Unsupported XLIFF version (1.0). [determine]
Reproduce steps:
First download [poedit2.2.3](https://download.poedit.net/Poedit-2.2.3-setup.exe)
Then install poedit2.2.3 and import Simplified Chinese.xlf, the above error message appears.
The following is my test environment information:
- Git Extensions 3.2.0.6586
- Build abac1b4564a5166f0453fa3ee459769e8a199b6f
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 120dpi (125% scaling)
 thanks

**Comment by dingpengyu** [comment]
Support for XLIFF translation files has been added since Poedit 2.2. The following is the official release news.
[Poedit 2.2: XLIFF and Dark Mode](https://poedit.net/news/xliff-and-dark-mode/)

**Comment by gerhardol** [comment]
Translations are only updated on transifex.
