### ISSUE TITLE
[NBug] The UI Command Source is not available for this control. Ar...

### ISSUE THREAD

**Issue by Mesty** [gitextensions/gitextensions#7124]
## Current behaviour

GitExt crashes with a message, that took me here.

## Expected behaviour

Not to crash.

## Steps to reproduce

see additional information

## Error Details
```
System.InvalidOperationException: The UI Command Source is not available for this control. Are you calling methods before adding it to the parent control?
   a következő helyen: GitUI.GitModuleControl.get_UICommandsSource()
   a következő helyen: GitUI.CommitInfo.CommitInfo.<ReloadCommitInfo>g__GetLinksForRevision|56_9(<>c__DisplayClass56_1& )
   a következő helyen: GitUI.CommitInfo.CommitInfo.<>c__DisplayClass56_0.<<ReloadCommitInfo>g__LoadLinksForRevisionAsync|4>d.MoveNext()
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a következő helyen: GitUI.CommitInfo.CommitInfo.<>c__DisplayClass56_0.<<ReloadCommitInfo>b__2>d.MoveNext()
--- Verem vége nyomkövetés a kivétel előző előfordulási helyétől kezdve ---
   a következő helyen: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   a következő helyen: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   a következő helyen: GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Open repo -> File tree -> choose a file, double click to open commits that chanded that specific file -> select a commit and double click on it -> close the appearing window

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I am unable to reproduce it.
Are you able to reproduce the error reliably?

**Comment by Mesty** [comment]
Well, I am now unable to reproduce it. Since then, some Windows updates have been installed. So maybe there was something with that version of Windows and GitExt cooperation. I admit, it is hard to do something with this amount of information, so i close the issue.

**Comment by RussKie** [comment]
Feel free to reopen if the issue persists and/or you get more info on it
