### ISSUE TITLE
"..." indicator [not] for all revisions

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7126]
## Current behaviour

The more info indicator `...` is shown for every commit in the revision grid.

![grafik](https://user-images.githubusercontent.com/36601201/64811446-95201400-d59d-11e9-975b-10982b98fac7.png)

## Expected behaviour

No `...` for single-line commit messages, no tooltip.

![grafik](https://user-images.githubusercontent.com/36601201/64811473-a9fca780-d59d-11e9-93c5-096b252629b1.png)

## Steps to reproduce

open a repo with single-line commits

## Did this work in previous version of GitExtensions

yes, regression after 3.2.0.6286 7cbb45bb5148e16a217e9804c596070d41ce78f7

## Environment

- Git Extensions 3.2.0.6326
- Build f51e398e71888771311356e8e834bbf99e6e24cf (Dirty)
- Git 2.21.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

and also

- Git Extensions 3.3.0
- Build 114b8ed39007ecb060f39264daecc217d54a100b (Dirty)
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3815.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
> yes, regression after 3.2.0.6286 [7cbb45b](https://github.com/gitextensions/gitextensions/commit/7cbb45bb5148e16a217e9804c596070d41ce78f7)

I can't see how that commit has introduced the issue.

**Comment by mstv** [comment]
> yes, regression **after** 3.2.0.6286 7cbb45b

I haven't bisected yet. Just tested portable builds I already had on my disk.

**Comment by mstv** [comment]
broken by 53ebf958bac6765b3a705a2dd20962a2ec7168a4 #6879
