### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by maurosys** [gitextensions/gitextensions#7135]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   em ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   em ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   em ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   em ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   em GitUI.FormStatus.Done(Boolean isSuccess)
   em GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   em GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18980.0
- .NET Framework 4.8.3921.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6675

Disable ConEmu in Settings->Advanced->"Use Console Emulator" to get rid of the problem

It may be something with timing, how quickly the popup status is clicked or.
There are no known way to reproduce, if you are in a position, please try
