### ISSUE TITLE
KarstenRa:bug/7046

### ISSUE THREAD

**Issue by live-user0001** [gitextensions/gitextensions#7139]
## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by live-user0001** [comment]
[CMakeLists.txt](https://github.com/gitextensions/gitextensions/files/3611198/CMakeLists.txt)

**Comment by live-user0001** [comment]
KarstenRa:bug/7046

**Comment by RussKie** [comment]
I reported the user
