### ISSUE TITLE
Rebase re-apply commit status value is incorrect

### ISSUE THREAD

**Issue by AdamWillden** [gitextensions/gitextensions#7152]
## Current behaviour

As noted in the latest release note a fix was attempted for this very issue in [#6351](https://github.com/gitextensions/gitextensions/pull/6531) by @pmiossec (thank you for looking into it).

While the text was better it still doesn't display nor function correctly (for me at least). Please see GIF below.

To put the GIF in in text form:

1. The commits to re-apply never shows the history of the changes (never has for me). i.e. the list gets truncated as it gets procesed.
2. The commits to re-apply status box always shows the commit AFTER the one being applied.
3. Once I skipped the undesired commit the status wrongly shows `Skipped` but against the commit AFTER the one to be applied (see issue 2).

## Expected behaviour

1. Retain the history of commits
2. Show the commit still to be applied
3. Show correct value against correct commit.

## Steps to reproduce

See gif!

## Screenshots

![000cea13-86f3-496c-9e97-3c33dc890759](https://user-images.githubusercontent.com/4629144/64974218-48da1a00-d8a4-11e9-9a1b-c72571085667.gif)

## Did this work in previous version of GitExtensions

No

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Valid points

**Comment by pmiossec** [comment]
> 1. The commits to re-apply never shows the history of the changes (never has for me). i.e. the list gets truncated as it gets processed.

I would have loved to have that but that is not possible with how the code actually work without redoing all the feature from scratch. Because what are displayed are the patch files generated by git (and the patchs for the already applied commits are not generated). That's a big refactoring without a great added value so I decided to not changes that.

> 2. The commits to re-apply status box always shows the commit AFTER the one being applied.

It feel strange to me because my work in #6351 was about that to maintain the first list of patches instead of reading patch files on the drive to always have the same list of patches with the status updated. There should be a bug but that I never encountered 😢 

  > 3. Once I skipped the undesired commit the status wrongly shows Skipped but against the commit AFTER the one to be applied (see issue 2).

Same here.

I will try to reproduce...

**Comment by pmiossec** [comment]
>I will try to reproduce...

I don't reproduce 😭 It is working well for me...

**Comment by pmiossec** [comment]
Perhaps something changed between the version 2.21 of git that I use and the 2.23.
I will update and have a look.

**Comment by pmiossec** [comment]
>I will update and have a look.

Still working with 2.23.  I don't know...

**Comment by pmiossec** [comment]
@AdamWillden So, if you have a reproduction case on a public github repository, it will really help.

**Comment by AdamWillden** [comment]
Thanks for checking this out.

It's my last day before a holiday today so a little too busy at work to sort out a repro for you. But I'll get to it one evening during my holiday!
