### ISSUE TITLE
System.Collections.Immutable.dll missing from GitExtensions-Portable-3.2.1.6628.zip

### ISSUE THREAD

**Issue by gitter-me** [gitextensions/gitextensions#7155]
In the portable distribution the dll mentioned above is missing (it is contained in the msi installer).

## Current behaviour
Crashes with an error message that the dll System.Collections.Immutable.dll is missing.

## Expected behaviour
No crash during startup

## Steps to reproduce
Unpack the portable zip and start it

## Did this work in previous version of GitExtensions
Yes

## Environment
- GitExtensions version: 3.2.1.6628
- GIT version: irrelevant
- OS version: irrelevant
- .NET version: irrelevant

**Comment by mast-eu** [comment]
It is included in the portable build, but within the `/Plugins` directory. For the installer it is in the root dir.

**Comment by mast-eu** [comment]
@gitter-me Could you please check whether    you can still reproduce the issue with this build https://ci.appveyor.com/api/buildjobs/tnp1n8p5u252vv6j/artifacts/Setup%2FGitExtensions-Portable-3.3.0.6655.zip

**Comment by RussKie** [comment]
> Unpack the portable zip and start it

I am unable to reproduce it.
I have downloaded the portable from https://github.com/gitextensions/gitextensions/releases/tag/v3.2.1, ran it, opened a git repo. No issues.

Could you please provide more information about your issue?

**Comment by mstv** [comment]
Also I am unable to reproduce it neither on my dev PC nor in a quite clean VM. I am sure that the DLL is found in and loaded from the `Plugins` folder.

**Comment by gitter-me** [comment]
I cannot reproduce the issue myself now.
I tried it multiple times now (incl the appveyor build), and the build works.   
The only explanation I have is that I had a incomplete plugin folder. 
And after diffing I noticed the missing dll in the root folder of the msi, and I (incorrectly) assumed the dll has to be in this place.

This can be closed in favor of #7173
Sorry for the inconvenience.

**Comment by RussKie** [comment]
Thank you for the follow up.
