### ISSUE TITLE
[NBug] Der Wert darf nicht NULL sein.Parametername: path3

### ISSUE THREAD

**Issue by Kromi75** [gitextensions/gitextensions#7169]
## Current behaviour
Choosing TortoiseMerge as Mergetool throws a Null Reference Exception.

## Expected behaviour
No exception.

## Steps to reproduce
Have a Windows 10 1809, install Git and TortoiseSVN.
Install Git Extensions and in the Settings - Config dialog choose TortoiseMerge as Mergetool.

## Error Details
```
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: path3
   bei System.IO.Path.Combine(String path1, String path2, String path3)
   bei GitUI.CommandsDialogs.SettingsDialog.MergeToolsHelper.FindFileInFolders(String fileName, String[] locations)
   bei GitUI.CommandsDialogs.SettingsDialog.MergeToolsHelper.FindMergeToolFullPath(ConfigFileSettingsSet settings, String mergeToolText, String& exeName)
   bei GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.MergeToolCmdSuggest_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   bei System.Windows.Forms.ComboBox.OnTextChanged(EventArgs e)
   bei System.Windows.Forms.Control.set_Text(String value)
   bei System.Windows.Forms.ComboBox.set_Text(String value)
   bei System.Windows.Forms.ComboBox.UpdateText()
   bei System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ComboBox.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3190.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Workaround: Set from command line
Submitted a PR, please test the portable build
This should probably be added to a 3.2.x if such is done, scheduling for 3.3 for now
