### ISSUE TITLE
Error deleting remote branch - could not read from remote repository

### ISSUE THREAD

**Issue by afarley-tangent** [gitextensions/gitextensions#7171]
## Current behaviour
I'm using GitExtensions 3.1.1.6049. 

I had pushed a branch to remote, then decided I wanted to delete it (both locally and on the remote). Right-clicking and selecting 'delete branch' from the main commit graph responded with: "Error deleting remote branch - could not read from remote repository". I did select the 'Delete branches from remote repository' checkbox.

This is an existing repository, and the other functions (push, pull) worked as expected. I worked around the issue by running the command via the command-line:

git push origin --delete RTCFix

(my branch was called RTCFix). This worked fine, although I did initially get a message from the command-line telling me that the IP address was added to the list of known hosts. 

After deleting the remote with the command-line, the GitExtensionsUI updated to show that the remote branch was gone.

So, it looks like GitExtensions is unable to delete a remote branch under some condition when the git command-line is able to delete the branch.

# Expected behaviour
I would expect that right-clicking a branch and selecting 'delete branch', with the checkbox selected, would result in the branch actually being deleted.

## Steps to reproduce
I'm not sure exactly how to reproduce since I've deleted and pushed branches in the past with success. I will experiment to try to reproduce.

## Screenshots
No screenshots taken this time, I'll add them if I can reproduce.

## Did this work in previous version of GitExtensions
Yes, I believe I've successfully deleted remote branches in the past. Not sure what version.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Include the Git Command Log (F12) with the updated description
What auth for Git (openSSH?), to what Git server?

**Comment by afarley-tangent** [comment]
> Include the Git Command Log (F12) with the updated description
> What auth for Git (openSSH?), to what Git server?

Putty for authentication to Github.

I lost the logs because I closed GE after fixing the issue. I'll attempt to reproduce.

**Comment by RussKie** [comment]
If you can provide a solid repro case, we can look at getting it fixed.
Thank you
