### ISSUE TITLE
Even branch can't be fetched

### ISSUE THREAD

**Issue by Riajyuu** [gitextensions/gitextensions#7175]
## Current behaviour

After fetching, even branch does not occur

## Steps to reproduce

Take GitHub as example here (others should be similar). Create another branch first 

![image](https://user-images.githubusercontent.com/16912240/65211728-41c32f80-da8f-11e9-9b5a-ec14841dc63c.png)

And then fetch

## Did this work in previous version of GitExtensions

N (I didn't try git bash, but GitHub Desktop does work)

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Can you please explain what you do and what you want to achieve. Also supply the git command log.

**Comment by pmiossec** [comment]
>Can you please explain what you do and what you want to achieve. Also supply the git command log.

Yes we want to know if it's really a fetch problem or if it's a display problem (because you enabled the "Show current branch only" or "Show first parents" or disabled "Show remote branches").

You  could also:

- tell us what git display in the popup that is opened when fetching
- post a screenshot of the remote branches after the fetch to see if the ref is there:

![image](https://user-images.githubusercontent.com/460196/65223278-22dd9100-dac1-11e9-8d14-51f0ac113cf4.png)

**Comment by Riajyuu** [comment]
> tell us what git display in the popup that is opened when fetching


It says everything is up to date.

> post a screenshot of the remote branches after the fetch to see if the ref is there


Nothing of UI changed afterwards

**Comment by pmiossec** [comment]
Are you sure your remote is configured toward this repository (and not toward the upstream repository)?

**Comment by Riajyuu** [comment]
@pmiossec yes

**Comment by RussKie** [comment]
Please provide detailed steps to reproduce the issue.

**Comment by Riajyuu** [comment]
> Please provide detailed steps to reproduce the issue

1. Create a repo on github.com
1. Clone it via URL in GE
1. Create a new even branch on github.com
1. fetch it in GE

Now the new branch does not occur.
Next,

Refresh the same repo using GitHub Desktop,
and the branch will occur in both programs.

**Comment by RussKie** [comment]
If you follow the steps and then run `git fetch` from a command line you won't get the new branch either.
You have to run `git fetch -all`.
