### ISSUE TITLE
[NBug] InvalidArgument=Значение '0' недопустимо для 'index'.Имя ...

### ISSUE THREAD

**Issue by oleg-indusrty** [gitextensions/gitextensions#7177]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=Значение '0' недопустимо для 'index'.
Имя параметра: index
   в System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   в System.Windows.Forms.ComboBox.get_Text()
   в System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   в System.Windows.Forms.ComboBox.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
not exist branch on search

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6680
