### ISSUE TITLE
Allow "Push" on commit dialog even if there are no changes.

### ISSUE THREAD

**Issue by DerekSMorin** [gitextensions/gitextensions#7179]
## Feature description

Allow "Push" on commit dialog even if there are no changes.
After committing all my changes, three different commits picking different files, I was unable to Push.
"Commit & push" said "There are no files staged for this commit."
But I actually wanted to push the three commits I had already made.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.21.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3752.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Hmm.... What you are asking is really strange...

Using the **commit** dialog to push commits without committing files is not how it was expected to be used.
Perhaps you should do like everyone and push from the main form of GitExtensions, no!?!

![image](https://user-images.githubusercontent.com/460196/65328936-bd200080-dbb7-11e9-9b04-20a2b21b13d3.png)

**Comment by DerekSMorin** [comment]
Is there a way to get to the main dialog from the commit dialog?
So far I have only been using the commit dialog.

**Comment by DerekSMorin** [comment]
I was previously using "git gui" to do my commits and pushes, and found gitextensions to be much nicer, except for the minor snag when I do all my commits and haven't done a "commit & push".

![image](https://user-images.githubusercontent.com/7568856/65330049-c7c2a180-db87-11e9-832b-d77cc43307ce.png)

**Comment by pmiossec** [comment]
>Is there a way to get to the main dialog from the commit dialog?

No.

>So far I have only been using the commit dialog.

That's what I slightly understood.

There is a possibility to tweak the UI when the form is used in stand alone.
But that's really not the common use.
So, I don't know if every one share the idea to manage this behavior (let alone be enough motivated to take time to implement it...)

**Comment by DerekSMorin** [comment]
There could probably be a "Push" button even if not launched as standalone.  I don't think the extra button would hurt in the common case.  But I definitely understand if I'm not using a common workflow, that this may not be a priority :)

**Comment by RussKie** [comment]
Do you invoke the commit dialog from the explorer context menu?
if so, there is a push command available there.

**Comment by mstv** [comment]
If one has disabled both `Close dialog after each commit` and `Close dialog when all changes are commited` and has done (several) commit(s), there will be no more changes in the end. Then `Commit & push` could simply push the branch - without attempting to commit nothing / complaining about  before. Then there will be no need to close FormCommit while working on a feature branch alone.

**Comment by DerekSMorin** [comment]
I like the idea mstv mentioned.  I did try to do "Commit & push" hoping it would skip the commit part and then push, or even bring up the "There are no files staged for this commit." dialog and THEN do the push.  Maybe it's a little less clear than a separate "Push" button, but it was seemed logical enough that I did try it.

**Comment by gerhardol** [comment]
Change the button to Push if there are no changes should be OK

I would not like to add too much extra info in FormCommit. In the long run I would prefer to skip FormCommit in the standard workflow, committing from FormBrowse (better stage/unstage of lines and editing commit text + commit button is needed).
