### ISSUE TITLE
Issue with the closing button (X) on a 4K monitor

### ISSUE THREAD

**Issue by antoinebaril1234** [gitextensions/gitextensions#7180]
Hi,

I just changed my monitor for a 4K and currently use a 3840 x 2160 resolution. For some reason, when I click on the X at the top-right, it seems like gitextensions is not exactly as wide as the screen, and it rather click the X button on any window appearing below gitextensions, which results in closing applications unwillingly.

I never witnessed this issue before having my 4K monitor, but now it does it every time I click on the X button, so I have to really take my time and target the X, to make sure that cursor is not at the far-right.

Please note that the issue is only with being at the extreme right of the X button. The extreme top correctly targets the button.

**Comment by RussKie** [comment]
Screenshots?

**Comment by antoinebaril1234** [comment]
I took two screenshots. The first is while hovering the X button of Google Chrome (for reference purpose). The second is while hovering the X button in GitExtensions. We can barely notice a white part at the right side of the X. If I drag the mouse at the far right, the X button of GitExtensions is not being hovered anymore. The "blank" space seems to be of a pixel or so.

<img width="163" alt="Google Chrome X button" src="https://user-images.githubusercontent.com/39191605/65337505-46bed680-db96-11e9-9b75-1b0d2f60694c.png">

<img width="112" alt="GitExtensions X button" src="https://user-images.githubusercontent.com/39191605/65337511-4aeaf400-db96-11e9-91e0-94ad20399a00.png">

**Comment by antoinebaril1234** [comment]
Since the background of the page is white, we can't see the difference between the screenshots. Here are the same screenshots put on a black background. 

Google Chrome : 
<img width="203" alt="Google Chrome X button" src="https://user-images.githubusercontent.com/39191605/65337669-99988e00-db96-11e9-9811-5ebef38b4025.png">

GitExtensions
<img width="156" alt="GitExtensions X button" src="https://user-images.githubusercontent.com/39191605/65337679-a4ebb980-db96-11e9-8b71-6e97c1ca2cb1.png">

**Comment by mstv** [comment]
> The "blank" space seems to be of a pixel or so.

On full HD, it's 2 pixels. It looks the same for Virtual Box and Total Commander, too. Tough on full HD, the button is pushed although the mouse pointer is 2 pixels outside the red highlight of the `X` button. (I don't have access to a monitor for which Windows allows 200% scaling for.)

**Comment by antoinebaril1234** [comment]
One of my colleagues tried it on his computer, and whereas there is a small blank part at the right side of the X button, he is not experiencing my issue, the X button is still being hovered even though the cursor is at the extreme right.

I don't know if it helps.

**Comment by pmiossec** [comment]
I'm not sure it's a Gitextensions problem.

Because the title bar is managed by the windows system.

I think we can't do anything.

I can also tell you a similar experience.
When Gitextensions is maximized in front of an application that customize the title bar (like Firefox, outlook,...), when you click on the first line of pixels of the title bar, the application stole the focus to Gitextensions and, so Gitextensions pass behind the application.

Surprising! But I don't think we could do something.... 😐

**Comment by antoinebaril1234** [comment]
That's unfortunate... Most of the time, the application appearing below in my case is Visual Studio. After reading your comment, I tested with other applications and it turns out that same behavior happens with SSMS. So, although SSMS and GitExtensions are the only ones having the problem,  I guess that I'll have to check out by myself to see how I can change that, as it is not solely related to GitExtensions. Maybe it has something to do with the zoom or something like that.

Anyway, thank you for your time and sorry for not having tested more with other applications before asking you.

**Comment by gerhardol** [comment]
Related: I have seen this problem when using a themer like WindowsBlinds

**Comment by RussKie** [comment]
This is not something Git Extensions is responsible for, it may be how Windows Forms and/or OS renders the control box.
