### ISSUE TITLE
[NBug] Error reading the K:\FromLaptop\Backup\Development\Developm...

### ISSUE THREAD

**Issue by alexmbaker** [gitextensions/gitextensions#7191]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

An unhandled exception occurs, GIT Extensions terminates.

## Expected behaviour

A more graceful failure, ideally, if network connectivity is restored then there should be no interruption to the users interaction with GIT Extensions.

## Steps to reproduce

* Using windows explorer, locate a folder on a network drive with a GIT Repo in it
* Using the context menu (right mouse click) select "GitExt open repository"
* With the GIT Extensions main window still open, disconnect the network.

## Error Details
```
System.IO.FileNotFoundException: Error reading the K:\FromLaptop\Backup\Development\Development\ntbs\ directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.21.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Corrected in 3.2
