### ISSUE TITLE
Menu bar white

### ISSUE THREAD

**Issue by bhcoder** [gitextensions/gitextensions#7192]
## Current behaviour
After updating to 3.2.1 version the menu bar became white making hard to distinguish the buttons

## Expected behaviour
The menu bar should be gray

## Steps to reproduce
Install version 3.2.1

## Screenshots
![Untitled-1](https://user-images.githubusercontent.com/6731263/65406420-cab7cf00-dddf-11e9-851e-bb84724a29d9.png)

## Did this work in previous version of GitExtensions
3.1.1

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18980.0
- .NET Framework 4.8.3921.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
This is by design to accommodate rendering in the dark theme.
