### ISSUE TITLE
VS extensions crashes often

### ISSUE THREAD

**Issue by screig** [gitextensions/gitextensions#7199]
## Current behaviour

Occasionaly I click on the GitExt menu in Visual Studio and I get the following message:

![image](https://user-images.githubusercontent.com/4292074/65604182-e61d0880-df9e-11e9-9e89-f37ec31fbc1f.png)

It works fine outside visual studio (v15.9.16). I think its just related to the VSIX wrapper

## Steps to reproduce

It seems to happen after branch changes, but it is fairly random I am afraid

## Screenshots

The menus display:

![image](https://user-images.githubusercontent.com/4292074/65604320-2a100d80-df9f-11e9-8643-dc467acd868b.png)

its just clicking on any button will produce the error, once it gets in to that state

## Environment

- GitExtensions version:   3.0.2.5232
- GIT version:   2.21
- OS version:    windoes 10 1903
- .NET version:  many
-Visual Studio 15.9.16

**Comment by RussKie** [comment]
Please try installing the latest VSIX https://github.com/gitextensions/gitextensions/releases/latest

**Comment by screig** [comment]
![image](https://user-images.githubusercontent.com/4292074/65605992-f4205880-dfa1-11e9-99ec-bc8934c6dbc7.png)


![image](https://user-images.githubusercontent.com/4292074/65606040-10bc9080-dfa2-11e9-8e76-e33e60e38ad7.png)

**Comment by RussKie** [comment]
Please follow the link provided

**Comment by screig** [comment]
Does that mean that the extension market place does not work. Is that itself, not the issue then? If each extension a user has in VS will not work nor update through the marketplace. Is it practical to require users to break the convention of VSIX updates and deployments to each publishers own method?

**Comment by RussKie** [comment]
No, it does not.

**Comment by screig** [comment]
Ok well I am up to data according to the marketplace, no?

**Comment by RussKie** [comment]
You seem to be doing everything to discourage me from attempting to help you.
If you wish to argue, I leave you to your devices
