### ISSUE TITLE
Reset unicode-name staged file

### ISSUE THREAD

**Issue by Vorval0** [gitextensions/gitextensions#7207]
## Steps to reproduce
1. Create file `лштшфум.txt`
1. `git add лштшфум.txt`
1. Commands → Commit.. → staged changes pane → лштшфум.txt → Reset file or directory changes
1. `лштшфум.txt` is deleted at working dir pane and added at staged changes pane

## Expected behaviour
`лштшфум.txt` disappears

## Screenshots
![Reset file or directory changes](https://user-images.githubusercontent.com/38347222/65794966-a747a800-e182-11e9-8539-f1acfbe3d1a2.png)
![Actual result](https://user-images.githubusercontent.com/38347222/65794743-399b7c00-e182-11e9-9039-4d053da6fcac.png)

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Workaround: Stage the deleted file and it disappears.
(For files without Unicode-only charecter in the name, this seems to be done automatically.)

**Comment by RussKie** [comment]
It would be good to find out why it is not working though and get it fixed.

**Comment by R0nd** [comment]
I experimented with `git-update-index` directly in CLI and the `index-info` pattern only seems to work with octal-escaped file names, regardless of `core.quotePath` setting. Proposed solution: implement the escaping function analogous to https://github.com/git/git/blob/master/quote.c and use it to encode the file name in `index-info` pattern, and perhaps file names in some other places(?)
