### ISSUE TITLE
Add ability to fill commit message from command line

### ISSUE THREAD

**Issue by kbilsted** [gitextensions/gitextensions#7219]
## Feature description

For semi-automatic work flows, e.g. where a tool is making modifications to source code, and you need a manual review process,e.g. selecting only some field or hunks of a file, it is very convenient if e.g. a script calling said tools also can generate and open gitextensions with a commit message prefilled for the manual part of the work flow.

I've made a draft of such a feature with PR https://github.com/gitextensions/gitextensions/pull/7208

**Comment by gerhardol** [comment]
Not the most common use of GE and nothing I would implement, but I am OK with this.

**Comment by pmiossec** [comment]
>Not the most common use of GE 

Indeed, that looks like a feature that will be used by only one person.

But not a lot of code and not too difficult, so it should be OK.

**Comment by RussKie** [comment]
I can't help but think if you'd open an issue first we could have saved some of your precious time.

I'm pretty sure you can achieve the desired without any code changes.

Whenever a commit form opens it looks for the following files:
1. `\<root>\.git\MERGE_MSG` file, if not found then
2. `\<root>\.git\COMMITMESSAGE` file.

If any of these files are found, their content is loaded into the `FormCommit` message box. 

So all you need to do as part of you automated flow is to create either of the files (though I'd go with the `COMMITMESSAGE` file) and write content you require.

**Comment by mstv** [comment]
> So all you need to do as part of you automated flow is to create either of the files (though I'd go with the COMMITMESSAGE file) and write content you require.

Then `<root>\.git\MERGE_MSG` must be deleted because it takes precedence.

Though this kind of "hacking" will not work that way if the working copy is a worktree.

**Comment by RussKie** [comment]
Could you please elaborate on the worktree point?

**Comment by mstv** [comment]
In a worktree, there is no `.git` folder, only a file with this name, which points to the parent working copy with the `.git` folder and subfolders in it for the worktrees.

**Comment by RussKie** [comment]
But how does GE retrieves the saved message?
It walks the tree to the .git folder and loads the file from there, doesn't
it?

**Comment by kbilsted** [comment]
My plan was to not interfere with the persisted commit messages. Also I'd prefer to call GE with an arg rather than mess with traversing up, find folders and mess with internal git files

**Comment by mstv** [comment]
> But how does GE retrieves the saved message?
It walks the tree to the .git folder and loads the file from there, doesn't
it?

Yes, `GitDirectoryResolver` does it. The result is provided in `Module.WorkingDirGitDir`.

Philippe wrote what I thought, too:
> But not a lot of code and not too difficult, so it should be OK.
