### ISSUE TITLE
Allow docking like GitAtomic has

### ISSUE THREAD

**Issue by jacekZ1980** [gitextensions/gitextensions#7229]
As a user of gitextensions I'd like my git client to have the possibility to have its certain (and any) windows on different monitors in any layout I decide to have, which gives more space for that particular window instead of squashing every window on just one monitor. Just take a look how people who create GitAtomic do it. It simply works phenomenal there and it would be really wonderful if gitextensions could offer such feature.

**Comment by mstv** [comment]
@jacekZ1980, could you elaborate more, how the window layouts should look like and what of it does not work with GE? (The screenshots on the GitAtomic page do not illustrate multi-window layouts at all.)

**Comment by jacekZ1980** [comment]
@mstv Basically in GitAtomic you can have for example a diff view (and any other view for that matter in any combination with any other view and layout) on separate monitors which makes the working space much larger area and your views are not squished onto one monitor. I've tried it in GitAtomic and it is really, really convinient to work on multiple monitors.

**Comment by gerhardol** [comment]
This is very hard to do when using WinForms so it is not likely to be implemented in GE
A kind of workaround is to open several GE windows

**Comment by jacekZ1980** [comment]
This (the workaround) is a very poor substitute of flexible and multimonitor layout system provided by GitAtomic.  The workarounds suggested also doesn't solve most of the issues, if anything it creates more. It is like suggesting to start multiple instances of Qt or CLion in order to achieve flexible and multimonitor layout. First, it will not work, that is it will not provide the desired functionality, as you cannot arrange any view with any other view in any combination as instances of programs don't "dock with each other", you have same views replicated etc, secondly it is simply so unnatural and weird. Would you really want to do it? And what would your colleagues from work think about you if they saw how you go about having multimonitor layout in an application(s) :) ? Please reconsider implementing the feature just like GitAtomic does it.

**Comment by pmiossec** [comment]
@jacekZ1980 

>Please reconsider implementing the feature just like GitAtomic does it.

Please consider doing it yourself. It's an opensource project that live with contribution.

>This is very hard to do when using WinForms so it is not likely to be implemented in GE

We just told you that it is a difficult task so why someone else would do it for you if it see no real benefits because it don't use multimonitor... You are the best placed to do it (or sponsor someone to do it)

**Comment by jacekZ1980** [comment]
Seriously you don't use multimonitor setup? In this day and age? Wow... I mean, tbh, I didn't see a dev working on less than two monitors for a long time now, so it is really hard to believe that somebody can still work on just one monitor. It is so cumbersome and inefficient... Anyway, thank you for the reply and I am glad that it is clear for me now that gitextensions won't have that feature. You made my choice rather easy. Thanks.

**Comment by pmiossec** [comment]
@jacekZ1980 
>You made my choice rather easy.

I hope so.

You come here asking for something in a condescending style. I'm not sure I will regret your choice...

**Comment by jacekZ1980** [comment]
> You come here asking for something in a condescending style.

That is the original message from me, how can you call it condescending? Seriously...

"As a user of gitextensions I'd like my git client to have the possibility to have its certain (and any) windows on different monitors in any layout I decide to have, which gives more space for that particular window instead of squashing every window on just one monitor. Just take a look how people who create GitAtomic do it. It simply works phenomenal there and it would be really wonderful if gitextensions could offer such feature."

**Comment by pmiossec** [comment]
I let that here because that just appears in my tweet line... https://mobile.twitter.com/_jayphelps/status/1179893573845696524

**Comment by jacekZ1980** [comment]
You can be arrogant, ignorant and cocky. That doesn't change the fact that the soft you're maintaining is outdated and provides old fashioned UX. But of course you don't care. Yeah, right...

**Comment by RussKie** [comment]
@jacekZ1980 you are entitled to your opinion however you have no right to come here and be abusive or spiteful. Don't like it - move on.
