### ISSUE TITLE
"Mergetool not configured correctly" if "path" key not present

### ISSUE THREAD

**Issue by LightCC** [gitextensions/gitextensions#7232]
## Current behaviour

Git Extensions reports that my mergetool is not configured correctly and will not open the mergetool conflict resolution window, even though it is configured fine.

Message window when clicking "!There are unresolved merge conflicts":
![image](https://user-images.githubusercontent.com/19731713/66082691-a7f08d80-e538-11e9-9721-c30fbba93545.png)

But in settings, it says the mergetool is configured fine:
![image](https://user-images.githubusercontent.com/19731713/66082741-c6ef1f80-e538-11e9-812c-5ea46d18407b.png)

And this setup worked fine in the prior version of Git Ext (no changes to any .gitconfig files).

## Expected behaviour

The merge conflict resolution window opens. Note: this window should open regardless of configuration - the mergetool is launched from one of the buttons inside the window, that's where the check should be made!  Even if the mergetool isn't setup to launch correctly, the conflict resolution window can still show you the conflicts, and can resolve them manually with a right click (i.e. choose local or remote) or after seeing the conflicts, they can be resolved directly in git extensions (outside the conflict window), or external to git ext.

But regardless, my mergetool is configured correctly!  So what is the issue... see below.

## Steps to reproduce

Remove the "path" key from your mergetool entry in .gitconfig and this issue appears - even if the mergetool is already in your path. i.e. If you run `git mergetool` without the path key, it runs fine (and worked fine in prior git ext version).

Adding a path = key, per below:
![image](https://user-images.githubusercontent.com/19731713/66084656-3535e100-e53d-11e9-96c1-907ece4a610c.png)

Fixes the issue.

So, mergetool is blocked the opening of the merge conflict resolution window both before blocking anything is required (i.e. that window doesn't actually launch the mergetool, the "start mergetool" button on that window does that), and despite the fact that a `path` key is not required if the mergetool command item (in the `cmd` key) is on the windows path.

## Did this work in previous version of GitExtensions

Yes, the one prior to this latest release... although a lot of the buttons in the merge resolution window were causing crashes in that release (fixed now).

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.21.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The check for mergetool path was added in 3.2 (#6869) to avoid that users tried to start mergetools without a configuration. GE requires both path and cmd, it is difficult to have meaningful checks in all situations it is used.

The Settings check only checks for command, which should be aligned with the Conflict resolve form. Strictly, if the tool is known by Git, neither path nor command is needed.

In 3.3 the code is cleaned up a little for hardcoded dependencies (mostly from when KDiff3 was bundled with GE). Contributions are welcome.

**Comment by LightCC** [comment]
Yeah, my wording is a little confusing above.

I understand if you want to help users in "difficult to diagnose" cases, or keep things from just plain breaking, but this is not the case here. GE is restricting usage beyond what Git does.

In addition, GE is currently restricting functionality that is not dependent on the mergetool being configured correctly.  I'm not 100% sure, but I don't believe the ability to run the merge function and display all the conflicts actually launches the selected/configured mergetool, which means the conflict resolution window can open, and if all you need to do is select the local or remote (ours/theirs) file completely, without launching the actual mergetool, then the mergetool settings are irrelevant.

So:
1. The check shouldn't happen until the actual mergetool needs to launch (i.e. at the commandline when git gives the option to "Launch with mergetool" - which I think is a right-click option on each file in the resolution window? - or when the user manually launches the mergetool with the available GUI buttons directly.  Delay the check until then.

2. If the diagnosis is difficult, this check should just be a warning and probably provide a checkbox to stop warning the user. Ideally, rather than try to do a hard check, the git command to launch the mergetool should attempt to detect if the tool failed to run - but I suspect this may not be possible across all environments.  If true, a warning that click yes might crash should be adequate. Let the user break the program if he wants to - if there are cases where everything will work fine.

Anyway, that's my 2 cents - I'd rather be able to crash it (if I avoid warnings) and not have to give extra instructions to everyone on my team to make their .gitconfig setup a specific way that only matter for GE.

(Agree on the contributions part - I'm sure this is easier for my rusty C# than I suspect... 😄 )

**Comment by gerhardol** [comment]
@LightCC 
Just configure path and cmd for now and review #7550 as well as the related PRs.
Also with rusty C# the concepts can be reviewed

The need for decoding path/cmd can be removed completely with very minor feature impact (2 way merge) and  delayed if that feature is needed.
