### ISSUE TITLE
How to hide the three dots icon in the grid?

### ISSUE THREAD

**Issue by fabvit** [gitextensions/gitextensions#7242]
## Current behaviour
How to hide the three dots icon in the grid?

## Screenshots

![GE three dots](https://user-images.githubusercontent.com/31626/66212582-773a6080-e6be-11e9-995e-0af9d124a241.PNG)

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.6.1055.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
I don't think it possible but this version introduced a regression that is now fixed in `master` to show it only on multiline comments. See #7148

**Comment by fabvit** [comment]
Thank you very much for pointing me to #7148!

So, for me,  this ticket can be closed, as the issue is already solved in the master branch.
