### ISSUE TITLE
[NBug] startIndex 不能大于字符串长度。参数名: startIndex

### ISSUE THREAD

**Issue by szgacsaftop** [gitextensions/gitextensions#7245]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: startIndex 不能大于字符串长度。
参数名: startIndex
   在 System.String.Substring(Int32 startIndex, Int32 length)
   在 GitUI.GitUICommands.RunFileHistoryCommand(IReadOnlyList`1 args)
   在 GitExtensions.Program.RunApplication()
   在 GitExtensions.Program.Main()
```

## Additional information
111

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by szgacsaftop** [comment]
In the windows10 environment, my operation is：right menu --git extensions-file history

**Comment by gerhardol** [comment]
First time seen, no way to reproduce

**Comment by mstv** [comment]
@gerhardol has added sanity checks to the regarding function on 2019-09-11.
Could you try [the current development build (portable version)](https://ci.appveyor.com/api/buildjobs/4wfnkmkpqigmspy3/artifacts/Setup%2FGitExtensions-Portable-3.3.0.6869.zip), @szgacsaftop and @juh1saxena, please?

**Comment by mstv** [comment]
@qcbf, could you try the current development build (portable version), too, please?
