### ISSUE TITLE
Error when fetching pull requests from repo without PRs

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#7250]
## Current behaviour

On a relatively virgin repo with only a few commits and no pull requests ever (open, nor closed), I get the following error when I use the "GitHub" menu and then "View pull requests..."

![image](https://user-images.githubusercontent.com/663378/66265430-951ad900-e816-11e9-9696-5537114eb018.png)

After the error, it does (correctly) show me an empty "View Pull Requests" screen:
![image](https://user-images.githubusercontent.com/663378/66265436-b54a9800-e816-11e9-8331-ed6d938327a8.png)

## Expected behaviour

No error message, just showing the empty pull requests screen.

## Steps to reproduce

See above.

If you like, you can use the following repo to reproduce, though I expect PRs to start up there over the next week or so: https://github.com/PHPCSStandards/PHPCSUtils/

## Did this work in previous version of GitExtensions

Unknown. I only recently started using the option.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

**Comment by jrfnl** [comment]
Ok, so this doesn't just happen on brand new repos. I've just encounted the exact same error when trying to view the pull requests of another repo. That other repo is a private repo on GH to which I have push access and has had numerous PRs previously.

**Comment by jrfnl** [comment]
Ha! I think I've figured out what the trigger is by testing with a number of other repos, both public as well as private.

My preliminary conclusion is that you need to have a branch checked out _which has a remote counter-part_ before the `View pull requests` option will work.

If I'm in a branch which only exists locally, I get the above mentioned error.

I suspect there is some logic which checks the current branch, checks which remote is associated with that branch and then gets the pull requests for that remote ?

Up to a point, I'd understand that logic, however if a repo only has one remote associated with it, the whole branch check should not be necessary.

Also, while testing some more, when I check out a branch from a remote which isn't the main repo, nor my own fork and it's a fork which never had any PRs, I also see the error.

All in all, seems like the logic here needs revisiting.

**Comment by RussKie** [comment]
Thank you for investigating it and sharing the findings

**Comment by hieuxlu** [comment]
@RussKie I was able to reproduce the bug, thanks to the detailed steps. Can you assign this to me, gonna submit a PR in coming days.

**Comment by pmiossec** [comment]
@hieuxlu great!

**Comment by hieuxlu** [comment]
@RussKie @pmiossec Please review the fix in #7307. Should fix the exception with local branch.

> Also, while testing some more, when I check out a branch from a remote which isn't the main repo, nor my own fork and it's a fork which never had any PRs, I also see the error.

@jrfnl  Can not reproduce the above case. Not quite understand the steps. Did the followings, worked fine:
1. Add another remote not owned by me.
2. Checkout a branch
3. Open Github > View pull requests
