### ISSUE TITLE
[NBug] Could not run the console emulator. The path to ConEmu.exe ...

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#7257]
## Current behaviour

A not handled exception is generated when ConEmu is not found.

## Expected behaviour

An error message should be better.

## Steps to reproduce

Delete ConEmu.exe.
Click on "Console" tab.

## Error Details
```
System.InvalidOperationException: Could not run the console emulator. The path to ConEmu.exe could not be detected.
   à ConEmu.WinForms.ConEmuSession.Init_StartConEmu(ConEmuStartInfo startinfo, CommandLineBuilder cmdl) dans [..]\gitextensions\Externals\conemu-inside\ConEmuWinForms\ConEmuSession.cs:ligne 718
   à ConEmu.WinForms.ConEmuSession..ctor(ConEmuStartInfo startinfo, HostContext hostcontext, JoinableTaskFactory joinableTaskFactory) dans [..]\gitextensions\Externals\conemu-inside\ConEmuWinForms\ConEmuSession.cs:ligne 136
   à ConEmu.WinForms.ConEmuControl.Start(ConEmuStartInfo startinfo, JoinableTaskFactory joinableTaskFactory) dans [..]\gitextensions\Externals\conemu-inside\ConEmuWinForms\ConEmuControl.cs:ligne 128
   à GitUI.CommandsDialogs.FormBrowse.<FillTerminalTab>b__210_0(Object sender, TabControlCancelEventArgs args) dans [..]\gitextensions\GitUI\CommandsDialogs\FormBrowse.cs:ligne 2979
   à System.Windows.Forms.TabControl.OnSelecting(TabControlCancelEventArgs e)
   à System.Windows.Forms.TabControl.WmSelChange()
   à System.Windows.Forms.TabControl.WndProc(Message& m)
   à GitUI.CommandsDialogs.FullBleedTabControl.WndProc(Message& m) dans [..]\gitextensions\GitUI\CommandsDialogs\FullBleedTabControl.cs:ligne 24
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.3.0
- Build c531c5fce8d3820eb1595750a1ccea8daf2f24b4 (Dirty) **I build it from source.**
- Git 2.21.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Could you please clarify why would someone delete bits of an app while running it?

A build sometimes doesn't copy ConEmu into the target folder, but full rebuild typically solves the issue.

**Comment by bansan85** [comment]
In my case, I didn't delete it. I run Git Extensions from Visual Studio.

I just made a full rebuild (as you asked) and it fixed the issue.

I don't really know what to say/do. Does the error should be handled (with a message like : "ConEmu.exe is missing, please reinstall Git Extension") ? Because the error is not handled and the "report window" opens, it looks to be a bug.

**Comment by RussKie** [comment]
An installed version always gets all files, so this issue can't happen for
an ordinary user, unless they delete files (in which case all bets are off).
In a dev environment (in your case) this happens every now and then.
Personally I don't think it is worth spending time trying to fix this.

**Comment by gerhardol** [comment]
This is a bug somehow in the build scripts that we have not been able to find. This is something developers may have to live with, end users do not see this.

This could be patched by handling this in the app too, maybe just for Debug configurations.
This type of changes are typically rejected by those who look for test coverage.
Setting as discussion.

**Comment by bansan85** [comment]
It's a try/catch to add and a new message to translate. I can try to make a PR if nobody is against.

**Comment by RussKie** [comment]
Sure thing, thank you
