### ISSUE TITLE
Clone dialog does not save history for non-http repositories

### ISSUE THREAD

**Issue by montoner0** [gitextensions/gitextensions#7260]
## Current behaviour

After cloning a local repository (e. g. `c:\repository`) it does not appear in a history list of `Repository to clone` field.

## Expected behaviour

Paths to local repositories are stored in the history.

## Steps to reproduce

1. Start - Clone repository
2. Enter path to a repository on a local drive to `Repository to clone` field.
3. Make a successful cloning.
4. Close Clone window
5. Start - Clone repository
6. Check history of `Repository to clone` field.

## Did this work in previous version of GitExtensions

As far as I know - no.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
"Repository to clone" field is saved only for remotes that have in a form of URL.
https://github.com/gitextensions/gitextensions/blob/master/GitCommands/UserRepositoryHistory/RemoteRepositoryManager.cs#L44-L48

Whether it can be changed or not must be investigated

**Comment by montoner0** [comment]
It's not quite clear why the initial decision was to limit the history to URLs only.

**Comment by RussKie** [comment]
One could speculate because cloning from a local source is an edge case.
