### ISSUE TITLE
Conflict resolution window labels local as theirs and remote as ours during normal merge.

### ISSUE THREAD

**Issue by dleinhaeuser** [gitextensions/gitextensions#727]
## Description

When during a regular local merge there is a conflict, the right click menu of the files listed in the conflict resolution window will show the following entries:

```
Choose local (theirs)
Choose remote (ours)
```

From what I understand about git it should say:

```
Choose local (ours)
Choose remote (theirs)
```

This can be quite confusing, because the two names contradict each other.
## How to reproduce
1. Start a local merge that will produce a merge conflict.
2. When asked whether you want to resolve conflicts press "Yes".
3. Choose a file from the conflict window and press the right mouse button on it.
## Expected result

A menu opens that contains - among other things - the following entries:

```
Choose local (ours)
Choose remote (theirs)
```
## Actual result

A menu opens that contains - among other things - the following entries:

```
Choose local (theirs)
Choose remote (ours)
```

**Comment by alexanderfedin** [comment]
That would be muuuch easier to understand what is going on if instead of LOCAL/REMOTE or OURS/THEIRS it should simply display the branch names.

**Comment by gerhardol** [comment]
See #6582 for a more recent discussion
