### ISSUE TITLE
[NBug] Error al leer el directorio C:\viewsgit_personal\springboot\.

### ISSUE THREAD

**Issue by batro83** [gitextensions/gitextensions#7278]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.FileNotFoundException: Error al leer el directorio C:\viewsgit_personal\springboot\.
   en System.IO.FileSystemWatcher.StartRaisingEvents()
   en GitUI.CommandsDialogs.BrowseDialog.GitStatusMonitor.Update()
   en System.Windows.Forms.Timer.OnTick(EventArgs e)
   en System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3752.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #7235 

Corrected in master
