### ISSUE TITLE
[NBug] startIndex cannot be larger than length of string.Paramet...

### ISSUE THREAD

**Issue by juh1saxena** [gitextensions/gitextensions#7283]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at GitUI.GitUICommands.RunFileHistoryCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

## Additional information
This just showed up when I tried to get File history.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #7245
No info to recreate
