### ISSUE TITLE
TranslationApp: missing method ResourceManager.GitPluginBase..ctor()

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7286]
## Current behaviour

The TranslationApp throws an exception:
```
Unbehandelte Ausnahme: System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht.
---> System.MissingMethodException: Methode nicht gefunden: "Void ResourceManager.GitPluginBase..ctor()".
   bei GitExtensions.PluginManager.Plugin..ctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   bei System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, Boolean nonPublic)
   bei ResourceManager.Xliff.TranslationUtil.CreateInstanceOfClass(Type type) in F:\Build\gitextensions\ResourceManager\Xliff\TranslationUtil.cs:Zeile 330.
   bei TranslationApp.TranslationHelpers.LoadNeutralItems() in F:\Build\gitextensions\TranslationApp\TranslationHelpers.cs:Zeile 28.
   bei TranslationApp.Program.Main() in F:\Build\gitextensions\TranslationApp\Program.cs:Zeile 34.
```

## Expected behaviour

The TranslationApp updates the `.xlf` files.

## Steps to reproduce

run it

## Did this work in previous version of GitExtensions

yes, at least two weeks ago

## Environment

- Git Extensions 3.3.0
- Build ab8a862e5e70c15dac0911c8fa9bfc299f6a5a47
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I think this is a regression from 334d805c35ef6e0d563c3a18da79698ab2f8f3cb

/cc: @pmiossec

**Comment by RussKie** [comment]
@mstv how to reproduce? 
I'm at 14c376fd858f63a7dfc04a59bcf879bffc942ddf, I've set `TranslationApp` project as a start up and run it, it didn't crash... I've also tried running via the PS script, same thing

**Comment by pmiossec** [comment]
OK, I will try to see that tomorrow.

 But I didn't have the problem from what I remember and the CI build seems
to still work.

Strange...

**Comment by RussKie** [comment]
Could be a red herring

**Comment by mstv** [comment]
- git clean -xdf
- VS Community 2019 16.2.5
- `F5`
- build solution
- run `UpdateLocalEnglishTranslations.ps1`
  throws for both Debug and Release builds of every recent commit I tried
- the same if the `TranslationApp` is set as startup project
- the same after update to VS 16.3.4

**Comment by pmiossec** [comment]
I can't reproduce with the following parameters: 

* on 9564bb2ab333735141f767bdc73ee62501c11a05
* VS 2019 Enterprise  16.2.5
* `git clean -xdf`
* Rebuild

😭

**Comment by RussKie** [comment]
Git it!
![image](https://user-images.githubusercontent.com/4403806/66748698-93ff4100-eed3-11e9-9f18-1cbd72553db1.png)

**Comment by gerhardol** [comment]
This also occurs when loading the released PluginManager:
https://github.com/gitextensions/gitextensions/pull/7213#issuecomment-544256364

A solution could be to change to use @pmiossec first implementation, not changing the plugin constructors.
I cannot se how to catch the loading of PluginManager only (which would be a good thing in GE.exe)

**Comment by gerhardol** [comment]
Fix in https://github.com/gitextensions/gitextensions/pull/7213/commits/4f930255259b6e9b5b9ede7f9b40bdf5377787b2
