### ISSUE TITLE
Incorrect placement of "Update submodules on checkout" setting

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#7290]
## Current behaviour

It is possible to configure whether submodules are updated on checkout (e.g. when a revision is checkout).
As discovered as part of analysis for #7274, the functionality is guarded by the following checkbox:
![grafik](https://user-images.githubusercontent.com/36601201/66707487-9598ff80-ed41-11e9-90fd-74364ac0c5be.png)
However it is totally unexpected and confusing to a user, as the page is about configuring confirmations, and not underlying settings.

## Expected behaviour

* The existing checkbox is moved to another settings page. Proposed placement "General" page under "Performance" group, after "Show submodules status in browser menu" item.
* Add a new `DontConfirmUpdateSubmodulesOnCheckout` setting that will guard against showing confirmations
* Update all code paths to correctly use these settings

**Comment by gerhardol** [comment]
I want to have the confirmation dependent of the action, the current location fits better then. This is not a performance setting.

**Comment by manishkungwani** [comment]
@RussKie @gerhardol Is this still needed, I would like to take this up.

**Comment by RussKie** [comment]
@manishkungwani fantastic! 
Let's finalise the desired outcome first though.

> This is not a performance setting.

I kind of see it as a performance setting - checking submodules on every checkout affects the "availability" of the app. But I'm not set on the location.
Where would you suggest to place it?

**Comment by manishkungwani** [comment]
All the other Performance settings are at "Git extensions" > "Git extensions" > "Performance".

So this should be in the same box.

**Comment by pmiossec** [comment]
@RussKie @gerhardol 

I see 2 possibilities:

1. In "Advanced", inside the "Checkout" group (my preference)

![image](https://user-images.githubusercontent.com/460196/66745211-b3b84a00-ee7e-11e9-84d7-7ad22e018c3d.png)

2. In "General", inside the "Behaviour" group


@manishkungwani 

If you want to work on this issue and because that's an issue touching to the GUI, be aware that you must start Visual Studio in "no scale" mode to prevent diff that we won't be able to review ( and that we will ask you to fix if you don't do it well): https://github.com/gitextensions/gitextensions/wiki/Guidelines%3A-UI-design

**Comment by RussKie** [comment]
> 1. In "General", inside the "Behaviour" group

Works for me.

After "Include untracked files..."?

**Comment by manishkungwani** [comment]
@RussKie sounds good. I'll start on this.
@pmiossec understand, I'll run VS on "no scale"

**Comment by manishkungwani** [comment]
@RussKie @pmiossec here is a branch with the fix - https://github.com/manishkungwani/gitextensions/tree/Incorrect_placement_of__Update_submodules_on_checkout__setting_%237290

- [ ] Added the control to General page
- [ ] Added the logic to General page
- [ ] Removed the control to Confirmations page
- [ ] Removed the logic from Confirmations page
- [ ] Ensured that TabOrder is correct

![image](https://user-images.githubusercontent.com/673367/66756850-7670ae00-eeb8-11e9-9f57-49c4afa2f0e8.png)

![image](https://user-images.githubusercontent.com/673367/66756876-84263380-eeb8-11e9-929c-8aace27e0615.png)

**Comment by pmiossec** [comment]
That was quick! 👍

Could you create a pull request based on this branch?
That way we will benefits of the review tools of GitHub to discuss about your changes.

>Perhaps I could file an issue and fix that too for all the Settings pages. Please advise.

It's always a please to see things fixed but it's better to do it in another branch to make the review easier.

**Comment by manishkungwani** [comment]
Eh .. I did submit a PR (https://github.com/gitextensions/gitextensions/pull/7300) , but the build failed on AppVeyor with the error

```
Please update English translations and re-submit the pull-request.
For more information please refer to https://github.com/gitextensions/gitextensions/wiki/Translations
```

I'm confused.

**Comment by pmiossec** [comment]
The control has been moved so the translation file must be updated. 

There is a procedure that you could follow :
https://github.com/gitextensions/gitextensions/wiki/Translations

I hope it will work but I think it will fail and you will have to wait that #7296 is merged (and after you will have to rebase your work and try again)

**Comment by mstv** [comment]
#7296 has been merged.
@manishkungwani, could you create another PR in oder to sign `contributors.txt`, please?
