### ISSUE TITLE
[NBug] ConEmuCD was not loaded.

### ISSUE THREAD

**Issue by aisupov** [gitextensions/gitextensions#7297]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
ConEmu.WinForms.GuiMacroExecutor+GuiMacroException: ConEmuCD was not loaded.
   в ConEmu.WinForms.GuiMacroExecutor.ExecuteInProcessAsync(Int32 nConEmuPid, String asMacro)
   в ConEmu.WinForms.ConEmuSession.ExecuteGuiMacroTextAsync(String macrotext)
   в ConEmu.WinForms.GuiMacroBuilder.ExecuteAsync()
   в ConEmu.WinForms.ConEmuSession.WriteOutputTextAsync(String text)
   в GitUI.FormStatus.Done(Boolean isSuccess)
   в GitUI.FormProcess.<>c__DisplayClass43_0.<OnExit>b__0()
   в GitUI.GitUIExtensions.<InvokeAsync>d__11.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Then i trying ti push my commit i have this error

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #6675

Disable ConEmu in Settings->Advanced->"Use Console Emulator" to get rid of the problem, or just dismiss the popup

Corrected in master
