### ISSUE TITLE
Double-click to select branch does not select latest commit

### ISSUE THREAD

**Issue by wheezil** [gitextensions/gitextensions#7299]
## Current behaviour

Suppose I have two branches `develop` and `hotfix/incorrect-connection-id`.  I click to put focus on branch `develop` and that selects the latest commit:

![image](https://user-images.githubusercontent.com/13988745/66771755-53260e80-ee78-11e9-9e76-df79d12c8ae6.png)

So far so good.  But if I double-click to checkout the `hotfix/incorrect-connection-id` and then double-click to checkout `develop` again, the latest commit is not selected, it is some unrelated commit:

![image](https://user-images.githubusercontent.com/13988745/66771428-756b5c80-ee77-11e9-9db2-1e5d00e617d1.png)

This causes a lot of trouble, because a subsequent CTRL-B will branch off the unrelated commit, not the latest commit from develop as I expect, and it is often not until things are a total mess that I realize my mistake and have to throw away work.

## Expected behaviour

Double-click to checkout a branch selects the latest commit when finished, consistent with how single-click to put focus on a branch selects the latest commit.

## Steps to reproduce

See current behavior

## Screenshots

See current behavior

## Did this work in previous version of GitExtensions

None that I have used.

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.20.1.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
I'm afraid, I cannot reproduce this. Though maybe you're hit by the strange bug #6663.

When you want to create a new branch, it suffices to single click the commit.

**Comment by wheezil** [comment]
It does seem similar to #6663 in that it has affinity for a particular commit.  At any rate, an update to 3.2.1 (and of course restarting git-ext) it no longer shows the problem.  If it recurs I'll provide a video.
Thanks
john

**Comment by pmiossec** [comment]
> If it recurs I'll provide a video.

It will be great but more than a video, a way to reproduce it reliably will
be better.

Because it happens sometimes but no one successfully reproduce it on demand
😐

**Comment by wheezil** [comment]
Interesting, once it was exhibiting this behavior, it was stuck that way across many restarts until I upgraded.  Is there a "UI state" stored somewhere in the registry or in the user appdata folder?  That is a factor I can check if this happens again.

**Comment by RussKie** [comment]
Not for the described behaviour
