### ISSUE TITLE
Installation fails when PowerShell is set to ConstrainedLanguage mode

### ISSUE THREAD

**Issue by mast-eu** [gitextensions/gitextensions#7308]
Extracted from https://github.com/gitextensions/gitextensions/issues/7120#issuecomment-540000422

## Current behaviour

In some environments, although PowerrShell is available, it is limited to `ContrainedLanguage` mode. This can be e.g. because a company policy, enforced by AppLocker or DeviceGuard.
The installation of GE 3.2.1 fails in these environments, because https://github.com/gitextensions/gitextensions/blob/master/Bin/set-telemetry.ps1 does not have the necessary rights to work correctly and thus returns an error.

## Expected behaviour

GE should be always installable, regardless of eventual PS constraints.

## Steps to reproduce

Can be simulated from command line:
```
powershell.exe
cd 'C:\Program Files (x86)\GitExtensions'
$ExecutionContext.SessionState.LanguageMode = "ConstrainedLanguage"
.\set-telemetry.ps1 1
```

## Did this work in previous version of GitExtensions

Versions prior to 3.2.1 were not affected, because the script `set-telemetry.ps1` has only recently been introduced (#6522).

## Environment

not relevant

**Comment by SuperJugy** [comment]
Thanks for this. I don't think I have anyting more to add. If you need help testing, let me know.
