### ISSUE TITLE
[NBug] startIndex cannot be larger than length of string.Paramet...

### ISSUE THREAD

**Issue by programcsharp** [gitextensions/gitextensions#7311]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

Exception.

## Expected behaviour

No Exception.

## Steps to reproduce

Right click in Explorer and click GitExtensions -> File History in root folder of a repo.

## Error Details
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at GitUI.GitUICommands.RunFileHistoryCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Steps to reproduce?

**Comment by gerhardol** [comment]
Duplicate of #7245
There has been corrections related to this in master, please try the latest master build
