### ISSUE TITLE
Add icon in all MessageBox

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#7312]
## Current behaviour

There is lot's of ``MessageBox.Show`` that don't have icon. The message box looks raw and not user friendly.

## Expected behaviour

All MessageBox shall have an icon.

## Steps to reproduce

Start | Create new repository

Create a Personal reposiroty

## Screenshots

![2019_10_16_08_45_16_Create_new_repository](https://user-images.githubusercontent.com/9248729/66894696-60b2d400-eff1-11e9-9046-86e31dac2ae8.png)

## Did this work in previous version of GitExtensions

No

## Environment

- GitExtensions version: 3.2.1.6628
- GIT version: 2.21.0.windows.1
- OS version: NT 10.0 18362.0
- .NET version: 4.8.4018.0

## Personnal comment

I'm fine to do the work if the team approves the change.

**Comment by pmiossec** [comment]
>I'm fine to do the work if the team approves the change.

Great! Go on 😉

**Comment by bansan85** [comment]
Thanks :) I will come back in about a week.

**Comment by pmiossec** [comment]
Good luck! 🤣 

> I will come back in about a week.

But I highly advise you to create a PR as soon as possible (prefixed with a "WIP:" in the title).
That way we could have visibility, discuss, review and see the advancement.

**Comment by bansan85** [comment]
Fine. I'll won't have lots of time this week but I will make PR regularly.

**Comment by pmiossec** [comment]
>I'll won't have lots of time this week but I will make PR regularly.

Sure! Everyone contribute how he could and how he wants...

You could update your PR when you want. You will just have to remove the 'wip:' in the title and ping us or ask for a review when you think you've finished.

**Comment by drewnoakes** [comment]
> Everyone contribute how he could and how he wants...

Yes, there's no obligation to work on this project. But there's also no obligation to be a 'he' :)

**Comment by pmiossec** [comment]
@drewnoakes I thought about that but my English is limited and I didn't know how to say it.

I'm eager to improve my English.
How should I have said it?

Can I use 'one'? And say:

'Everyone contribute how one could and how one wants...'

It sounds strange...

**Comment by gerhardol** [comment]
Will mark these as OT...
They/them is transgender in English

(In Swedish a third pronoun in addition to han(he) and hon(she) was added some yers ago that is quite common: 'hen')

**Comment by 0502511066** [comment]
Admin

**Comment by drewnoakes** [comment]
> Everyone contribute how one could and how one wants

That works. In fact it sounds quite regal. One can imagine the queen talking in this way.

In general 'they' works for a gender neutral address. Some will tell you it is wrong, but that is not the case in practice. So, _Everyone contributes how they can and how they want_ would work too.

> In Swedish a third pronoun in addition to han(he) and hon(she) was added some years ago that is quite common: 'hen'

Something like that might be good in English too. 'It' is close, but it's too weird and dehumanising to call someone 'it', so 'they' works for now.

**Comment by RussKie** [comment]
> I will make PR regularly.

Please don't forget about screenshots :) Makes it easier to appreciate the change
Thanks

**Comment by bansan85** [comment]
@RussKie I will not add screenshot, it just add icon to MessageBox that don't have one. I don't think it's necessary, do you?

**Comment by gerhardol** [comment]
> I will not add screenshot, it just add icon to MessageBox that don't have one. I don't think it's necessary, do you?

Always supply information for reviewers. It could for instance be that adding the icon changes the appearance in some other way (I do not think so, just an example).
Try especially to keep a maintainer like RussKie happy. He puts in hours comparable to normal work into GE, we want to keep him happy.

**Comment by bansan85** [comment]
I edited my message, I didn't wanted to be offensive or unpleasant in any way :/

**Comment by gerhardol** [comment]
> I edited my message, I didn't wanted to be offensive or unpleasant in any way :/

No problem at all, I just tried to explain why reviewers/maintainers asks for info that may seem easy or obvious.
Thanks for contributing.
