### ISSUE TITLE
Ignore new line addings or removings

### ISSUE THREAD

**Issue by denis-pujdak-adm-it** [gitextensions/gitextensions#7313]
## Feature description
It would be nice to have an extra option to ignore empty lines addings or removings in the same way as there are other options like `ignore whitespaces` in the diff viewer.
Thank you

![image](https://user-images.githubusercontent.com/13495631/66915632-65878000-f011-11e9-8c10-3a71f417201f.png)

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The diff window uses git-diff options:
https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---ignore-space-at-eol

So this will require quite some extra effort.
