### ISSUE TITLE
[NBug] startIndex cannot be larger than length of string.Paramet...

### ISSUE THREAD

**Issue by bprasadvk** [gitextensions/gitextensions#7314]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at GitUI.GitUICommands.RunFileHistoryCommand(IReadOnlyList`1 args)
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

## Additional information
crah

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.20.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3928.0
- DPI 120dpi (125% scaling)

**Comment by pmiossec** [comment]
Duplicate of #7245
There has been corrections related to this in master, please try the latest master build and confirm us that it is fixed.
