### ISSUE TITLE
Plugins aren't immediately available on the Portable build

### ISSUE THREAD

**Issue by tboby** [gitextensions/gitextensions#7318]
## Current behaviour
On downloading the portable release of GitExtensions, extracting the archive and running it, no plugins appear to be available. The Plugins node in settings is empty and the Plugins menu has only "Plugin settings" and nothing else.

On going into the "Plugins" folder and manually unblocking a plugin dll, the plugin works.

## Expected behaviour
Bundles plugins should be available for immediate use in the portable release.

Or, the application should warn the user that plugins have failed to load.

## Steps to reproduce
1. Download GitExtensions-Portable-3.2.1.6628.zip
2. Extract into a folder
3. Run GitExtensions.exe
4. Note that the Plugins node in the setup window is empty
5. Press OK
6. Open a repository
7. Note the Plugins menu does not contain any plugins
8. Go to the Plugins folder
9. On a plugin dll, go to properties and "unblock"
10. Restart GitExtensions and note the plugin is now available

## Screenshots
![image](https://user-images.githubusercontent.com/447391/66993243-1e59c780-f0c3-11e9-9539-b5565a7d2c6b.png)

![image](https://user-images.githubusercontent.com/447391/66993310-421d0d80-f0c3-11e9-859c-5fe6d455be98.png)

## Did this work in previous version of GitExtensions
Unknown, first time user

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
>Bundles plugins should be available for immediate use in the portable release.

It's a security issue requiring a user action, so I don't think it is safe to unblock the files and even possible. 

>Or, the application should warn the user that plugins have failed to load.

It's a better choice but it must be investigated if it's possible.

I don't reproduce so difficult to investigate more.

**Comment by vbjay** [comment]
https://devblogs.microsoft.com/scripting/easily-unblock-all-files-in-a-directory-using-powershell/

The issue is that you downloaded a zip from the internet.  Unblock the Zip
first. This information is stored in a special ads called Zone.Identifier.

https://docs.microsoft.com/en-us/archive/blogs/askcore/alternate-data-streams-in-ntfs
