### ISSUE TITLE
[NBug] Value may not be NULL. Parameter name: path3

### ISSUE THREAD

**Issue by RUB-2488** [gitextensions/gitextensions#7319]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: path3
   bei System.IO.Path.Combine(String path1, String path2, String path3)
   bei GitUI.CommandsDialogs.SettingsDialog.MergeToolsHelper.FindFileInFolders(String fileName, String[] locations)
   bei GitUI.CommandsDialogs.SettingsDialog.MergeToolsHelper.FindMergeToolFullPath(ConfigFileSettingsSet settings, String mergeToolText, String& exeName)
   bei GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.MergeToolCmdSuggest_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   bei System.Windows.Forms.ComboBox.OnTextChanged(EventArgs e)
   bei System.Windows.Forms.Control.set_Text(String value)
   bei System.Windows.Forms.ComboBox.set_Text(String value)
   bei System.Windows.Forms.ComboBox.UpdateText()
   bei System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ComboBox.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Fresh installation.

Tried to change the Merge program in the configuration from KDiff3 (the standard setting, not installed) to TortoiseMerge (with TortoiseGit installed).

Immediately crashed.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #7169
Corrected in master
(You can use the master portable version to set TortoiseMerge as mergetool or use Git command line.)
