### ISSUE TITLE
Detect syntax highlighting from from file contents

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#7323]
## Feature description

The GE fileviewer has a basic syntax highlighting support. Currently it is available when viewing full files (for instance in the file tree), with #7291 also in the diff window.
Detection of the syntax is based on file extension only.
The support has to be implemented in the GE build, not possible to add/change for file extensions or syntax formats.

As discussed in https://github.com/gitextensions/ICSharpCode.TextEditor/pull/15, support could be detected from pre-amble.
For diff view, this will require that the diff contents is retrieved too (currently just the diff is retrieved from Git).

**Comment by pmiossec** [comment]
For another feature (work in progress), I have started something similar:

https://github.com/pmiossec/gitextensions/commit/895da2c433804507e86c5f5377716b7872fd6bfc
