### ISSUE TITLE
GItHub - View Pull Requests: Failed to load diff data!

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#7336]
## Current behaviour

When I try to view the diff of an open pull request in a private repo to which I have access, I get a "_Failed to load diff data! The remote server returned an error: (404) Not Found_" error.

![image](https://user-images.githubusercontent.com/663378/67151853-45cfb080-f2cc-11e9-9fa4-b6dc243c04a3.png)

The error shows up as soon as soon as the "View Pull Requests" window opens.

When I click "OK" and then click on another pull request (other than the first which is selected by default), the same error pops up again.

![image](https://user-images.githubusercontent.com/663378/67151962-816b7a00-f2ce-11e9-9f6b-9e39d8adea11.png)

Related issues: #2366 and possibly #1271

## Expected behaviour

The diff would be shown.

If this is not possible for private repos, maybe a more helpful error message which only shows up when the "View Pull Requests" window for a private repo is initially opened. Something like "_While you can view the list of open pull requests in a private repo, it is currently not (yet) possibly to see the diff._"

## Steps to reproduce

1. Open a local repo with a private GitHub repo as a remote (the only remote when using a GE build prior to #7307).
2. Make sure there is at least one open pull request in the private GH repo.
3. If using a GE build prior to #7307, make sure to have checked out a branch which has a remote. (`develop` or `master` for instance)
4. Go to "GitHub" -> "View Pull Requests"
5. See the above mentioned error.

## Screenshots

See above.

## Did this work in previous version of GitExtensions

Not sure as I only recently started using this feature.

## Environment

Tested on both (build from #7307):
- Git Extensions 3.3.0.6949
- Build d5dc4aee54b10bd1ea2ad921eb32e13fe741199e (Dirty)
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

as well as (latest release):
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

**Comment by manishkungwani** [comment]
@jrfnl I'm able to reproduce this issue.

@RussKie I will attempt to fix this.

**Comment by RussKie** [comment]
> I will attempt to fix this.

Awesome!

**Comment by saharsh-gupta** [comment]
Has anyone had any luck with this issue!!

**Comment by gerhardol** [comment]
There are no PR created for this, this is still up-for-grabs.

**Comment by mrwellmann** [comment]
Authentication with token works (e.g.: fork clone works) but I'm having this exact issue.

GitExtentions 3.5.4 / Git 2.38.1

**Comment by MakraGitHub** [comment]
When i push code commit token on branch master sometime load file but some time no see file on spring boot security OAuth2 in spring boot version 3.5.4
