### ISSUE TITLE
hicup on ttf file

### ISSUE THREAD

**Issue by bdeket** [gitextensions/gitextensions#7348]
my current git project has a *.ttf file. This file, however, is NOT a font file but has other (binary) data.
Every time I do a commit or other action where normally the terminal would show up, this results in an error-popup. (from ConEmu)

Is there a way to mark this file as not being a font file, or make sure that all font files are ignored as being special? I don't know what the program is trying to do with this file, but I would like for it to be silently ignored.

**Comment by pmiossec** [comment]
We need more information to better understand the problem (screenshot would be good) because the content of the file must not have an effect on the terminal behavior.

>Every time I do a commit or other action where normally the terminal would show up, this results in an error-popup. (from ConEmu)

I tend to think that your error is not linked to the ttf file content but to the ConEmu bug (like #6878) that happens sometimes.

Something that you could try is to disable the use of ConEmu: https://github.com/gitextensions/gitextensions/issues/6878#issuecomment-507265344

>Is there a way to mark this file as not being a font file, or make sure that all font files are ignored as being special?

No, I don't think that something special is made with these files.

**Comment by bdeket** [comment]
For example when opening the 'Console' tab.
The same happens when hitting commit.

[cid:b2c39070-e3ae-433d-bc3c-24aa7e6f74e0]

________________________________

**Comment by pmiossec** [comment]
Yes. Your information are unclear. Which error exactly? Screenshot?

**Comment by bdeket** [comment]
sorry,
for some reason the screenshot didn't come trough via email.

![image](https://user-images.githubusercontent.com/6235541/67285702-52285900-f4d8-11e9-8c0d-06bb4bc15a48.png)

**Comment by pmiossec** [comment]
Thanks. I reproduce.

That's a **very** strange behavior of the ConEmu component we use to run git commands.
The workaround to disable ConEmu is working.

**Comment by jimbo1qaz** [comment]
I've observed this same behavior when launching standalone ConEmu in my Downloads folder with a TTF file (a seemingly-working but possibly malformed font) that ConEmu can't parse.

The message is produced by https://github.com/Maximus5/ConEmu/blob/1a2363ef646dfe8c225347c3f54eac9a26993130/src/ConEmu/FontMgr.cpp#L1363 .

Why does ConEmu try to load all TTF files in the working dir? (answer: https://github.com/Maximus5/ConEmu/blob/1a2363ef646dfe8c225347c3f54eac9a26993130/src/ConEmu/FontMgr.cpp#L1660-L1665 ) Running Google Translate on the comments, apparently ConEmu will unconditionally load all TTF files in `.` unless `.` is a font directory. Why? 🤷‍♀️

**Comment by pmiossec** [comment]
I have opened an issue: https://github.com/Maximus5/conemu-inside/issues/46

**Comment by gerhardol** [comment]
Corrected in ConEmu 200713, used in master
https://conemu.github.io/blog/2020/07/13/Build-200713.html
