### ISSUE TITLE
Main view only displays most recent commit on branch, or tagged commits.

### ISSUE THREAD

**Issue by nolancasimir** [gitextensions/gitextensions#7354]
## Current behaviour

Not all commits are view-able. Only the most recent commit on a branch, and tagged commits are displayed in the main window on opening the application. This also affects cherry picking. Commits that are not tagged cannot be found when attempting to cherry pick.

## Expected behaviour

I should be able to view every commit in a repository, regardless of if it is the most recent commit in a branch or tagged.

## Steps to reproduce

1. Open Git Extensions
2. Select a repository
3. Observe that not all commits are displayed.

## Screenshots

![image](https://user-images.githubusercontent.com/56938681/67433239-6722ec00-f5ad-11e9-85f5-255c8a6a4610.png)

## Did this work in previous version of GitExtensions

This worked until a few weeks ago, but I am unsure if any new versions were installed

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)
    ❤️ Git Extensions? Please consider supporting our collective:

    👉 https://opencollective.com/gitextensions
-->

**Comment by mstv** [comment]
@nolancasimir, could you take a screenshot of the settings in the `View` menu, please?

**Comment by nolancasimir** [comment]
![image](https://user-images.githubusercontent.com/56938681/67434281-786cf800-f5af-11e9-9891-c4ec11164be9.png)

**Comment by nolancasimir** [comment]
If I use the Show First Parents option, it fixes half of the problem, but creates a new problem as well. With that setting I can view all commits on the current branch, but cannot view other branches.

**Comment by nolancasimir** [comment]
I also have a teammate on version 3.1.1.6049 that does not have this issue.

**Comment by pmiossec** [comment]
Is there a possibility that you set a git setting? (Because everything looks fine in your options)

**Comment by nolancasimir** [comment]
I looked through the settings, and could not find anything that seems to relate to this. I can still cherry pick commits with command line git, so it seems to be a Git Extensions problem.  Do you know of any setting that could affect this?

**Comment by RussKie** [comment]
* Is the issue repo-specific or happening to all repos?
* Have a look in Gitcommand Log (<kbd?F12</kbd>) and see what commands are executed. 
* Check whether you get the all expected commits by running `git-log` command that GE is running
```bash
git -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b1DEA7CC4-FB39-450A-8DDF-762FCEA28B05" --all --boundary --not --glob=notes --not --max-count=100000 --
```

**Comment by nolancasimir** [comment]
Russ, 

1. This is for all repositories
2. See Screenshot
3. All commits from the current master branch are displayed from that command, but not all branches. Similar to if I select the "Show first parents" option

![image](https://user-images.githubusercontent.com/56938681/67486896-80ba4700-f632-11e9-8f5a-3b2dddef48ec.png)

**Comment by nolancasimir** [comment]
I found the issue comparing the command log to the command Russ suggested. The issue is that the option "Simplify by decoration" was selected in the "Set advanced filter" page. Thanks for the help everyone who chimed in!

![image](https://user-images.githubusercontent.com/56938681/67488324-3d150c80-f635-11e9-8c85-8d0afc86bb74.png)

**Comment by nolancasimir** [comment]
Relates to #4055.

**Comment by pmiossec** [comment]
Discussion: I propose to display in the menu that something is filtered (by writing the text in red).

That's too easy to be bitten by these settings.

What do you think?

**Comment by nolancasimir** [comment]
I agree it is too easy to be bitten by this setting. Displaying some text in red would for sure help to debug this issue faster. Another idea might be to put it in the view menu, so that it would at least exist in the first place people would look when trying to solve the problem. It could also potentially have it's own button similar to the "Show first parents" option.

**Comment by pmiossec** [comment]
@nolancasimir 
>Another idea might be to put it in the view menu

I don't find this setting enough used (I didn't even know it and still don't know when it could be useful), so I don't think it's a good idea to put it in an already cumbersome menu.

And also I was more thinking about filtered by any option of this popup. And moving just this setting, don't solve the problem (and also bring more work to do it)

**Comment by nolancasimir** [comment]
That makes sense, I do like the red text idea though.

**Comment by pmiossec** [comment]
Playing with it 5min show me that more than one things are wrong with this popup:

* only the "branches" checkbox (and the 2 sub checkbox) are saved (and globally for all repositories). Why? Save all values or none?

* The 2 checkbox values are used even if the "Branches" checkbox is not enabled even if disabled in the GUI

There is work to do here...

**Comment by RussKie** [comment]
> Playing with it 5min show me that more than one things are wrong with this popup:

Could you please raise new issues for these?
