### ISSUE TITLE
[NBug] App crash on invalid branch name in history window

### ISSUE THREAD

**Issue by maulwuff** [gitextensions/gitextensions#7355]
## Current behaviour

app crashes when entering an invalid branch name in the history window.

## Expected behaviour

dont crash on non existing branch names in combo box of the history window

## Steps to reproduce

- enter non existing branch in the branches filter box of the file history window. and hit enter
- focus another window (I copied a valid branch name from the main window)
- refocus the history window 
- click inside the branches combo box > Exception (entering text was not possible anymore)

## Error Details
```
System.ArgumentOutOfRangeException: InvalidArgument=Value mit dem Wert 0 ist für index ungültig.
Parametername: index
   bei System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   bei System.Windows.Forms.ComboBox.get_Text()
   bei System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   bei System.Windows.Forms.ComboBox.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
 

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4018.0
- DPI 144dpi (150% scaling)

**Comment by pmiossec** [comment]
Fixed in master. Waiting for the next release.
