### ISSUE TITLE
SetRevisionFunc produce empty Dropdown-menu on start

### ISSUE THREAD

**Issue by idealist1508** [gitextensions/gitextensions#7357]
## Current behaviour

SetRevisionFunc produce empty popup on start

## Expected behaviour

GitExtensions should start  without to show an empty dropdown menu

## Steps to reproduce
Start GitExtensions from master branch (4b1d520f750e8c230ba615423e3335f95ea36ef8)

## Screenshots
![image](https://user-images.githubusercontent.com/4608274/67479282-0a333e80-f65e-11e9-9992-fa0e86652f48.png)

## Did this work in previous version of GitExtensions
Yes. in v3.2.1

## Environment

- Git Extensions 3.3.0
- Build 955e6e520d564c1c5b26860887499c86d65fc9ab (Dirty)
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by idealist1508** [comment]
Was introduced in #7084

**Comment by gerhardol** [comment]
Can you clarify what the problem is?
I do not see an emty dropdown in the application itself.

**Comment by idealist1508** [comment]
I made a video:
![gitextensions_start](https://user-images.githubusercontent.com/4608274/67549266-25588980-f704-11e9-85f3-62ceb38e049d.gif)

**Comment by RussKie** [comment]
Thank you, that is very helpful
