### ISSUE TITLE
Add "git reset --keep" to reset dialog

### ISSUE THREAD

**Issue by jimbo1qaz** [gitextensions/gitextensions#7358]
## Feature description

When I reset a branch in Git Extensions, I can pick soft/mixed/hard, but not keep.

`git reset --keep` moves HEAD and applies changes between old and new HEAD. It also keeps changes in the working directory. (IDK how the index comes into play, but that behavior differs between --merge and --keep. Documentation at https://git-scm.com/docs/git-reset)

"keep" is useful because it operates rather like switching branches (switch HEAD and update the filesystem to match), and is nondestructive (will not erase uncommitted changes in the working directory). If file A is modified locally and file B is different between the old/new HEAD, only file B will be modified (in both `git checkout` and `git reset --keep`). If file A is modified locally and is different between old/new HEAD, the reset is aborted.

Jetbrains IDEs already exposes an option to "Keep" when performing a git reset.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
As reset/checkout/rebase was not hard to explain already...
Why not --merge too?

I see that these options were available in Git 2.0, so it is probably OK to not check for older versions.
