### ISSUE TITLE
Internal diff and blame do not show any text

### ISSUE THREAD

**Issue by bshafer** [gitextensions/gitextensions#7370]
## Current behaviour

When I select a file from the diff tab of the details of a commit, the right pane shows some line numbers (cut off) but no text

## Expected behaviour

To see the changes made to that file

## Steps to reproduce

I can't. It is broken at work, but not at home, but I can't fix it at work, where I need it.

## Screenshots

![Git Extensions Bug](https://user-images.githubusercontent.com/904264/67708324-93f64b00-f981-11e9-9927-d4879d2b3072.jpg)

## Did this work in previous version of GitExtensions

Yes, but it also works in the current version (sometimes)

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)

Both home (working) and work (broken) have exactly the same text from the about box.

**Comment by pmiossec** [comment]
Could that be an anti-virus that cause that? 
Or a git setting? could you list yours? 

We also need the git diff command run and the result. See the git command log in the browse form (F12).

**Comment by bshafer** [comment]
Sorry, I rebooted my machine, and it is fixed. Probably an update to the .NET libraries that I had forgotten about. Thanks.
