### ISSUE TITLE
Installer fails on systems with PowerShell ExecutionPolicy AllSigned

### ISSUE THREAD

**Issue by kaesaecracker** [gitextensions/gitextensions#7379]
## Current behaviour
When trying to install GitExtensions 3.2., the installer rolls back all the changes just before being done.

This is related to #7120 but the problem here is not that some component is missing to run the script. The problem is that the execution is blocked by the ExecutionPolicy. Setting the policy to something else is not possible in this case, because it is enforced by a group policy.

## Expected behaviour
Installer does not fail.

## Steps to reproduce

1. [Set ExecutionPoliy to AllSigned](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6)
PS> Set-ExecutionPolicy -ExecutionPolicy AllSigned
1. Try to install GitExtensions

## Screenshots
Same behavior as #7120, the installer does not tell you anything useful anyways.

## Did this work in previous version of GitExtensions

This was introduced with the telemetry changes

## Environment

What I tried to install:
- GitExtensions version: 3.2.1.6628
- OS version: Win10 1903
- .NET version: 4.7.2

## Diagnostics

I have generated an installer log, but I cannot share the full log without redacting some information. The relevant part is this:

```
MSI (s) (C4:8C) [13:55:54:596]: Executing op: ActionStart(Name=ConfigureTelemetry,,)
Action 13:55:54: ConfigureTelemetry. 
MSI (s) (C4:8C) [13:55:54:597]: Executing op: CustomActionSchedule(Action=ConfigureTelemetry,ActionType=1025,Source=BinaryData,Target=WixQuietExec,CustomActionData="C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -InputFormat None -ExecutionPolicy Bypass -Command "& 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1' ; exit $($Error.Count)")
MSI (s) (C4:5C) [13:55:54:599]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI61B7.tmp, Entrypoint: WixQuietExec
WixQuietExec:  & : Die Datei "C:\Program Files (x86)\GitExtensions\set-telemetry.ps1" kann nicht geladen werden. Die Datei 
WixQuietExec:  "C:\Program Files (x86)\GitExtensions\set-telemetry.ps1" ist nicht digital signiert. Sie k”nnen dieses Skript im 
WixQuietExec:  aktuellen System nicht ausfhren. Weitere Informationen zum Ausfhren von Skripts und Festlegen der 
WixQuietExec:  Ausfhrungsrichtlinie erhalten Sie unter "about_Execution_Policies" (https:/go.microsoft.com/fwlink/?LinkID=135170)..
WixQuietExec:  In Zeile:1 Zeichen:3
WixQuietExec:  + & 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1' ; exit $($ ...
WixQuietExec:  +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec:      + CategoryInfo          : Sicherheitsfehler: (:) , PSSecurityException
WixQuietExec:      + FullyQualifiedErrorId : UnauthorizedAccess
WixQuietExec:  Error 0x80070001: Command line returned an error.
WixQuietExec:  Error 0x80070001: QuietExec Failed
WixQuietExec:  Error 0x80070001: Failed in ExecCommon method
CustomAction ConfigureTelemetry returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 13:55:55: InstallFinalize. Return value 3.
MSI (s) (C4:8C) [13:55:55:776]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (C4:8C) [13:55:55:776]: User policy value 'DisableRollback' is 0
MSI (s) (C4:8C) [13:55:55:776]: Machine policy value 'DisableRollback' is 0
MSI (s) (C4:8C) [13:55:55:777]: Note: 1: 2318 2:  
MSI (s) (C4:8C) [13:55:55:778]: Executing op: Header(Signature=1397708873,Version=500,Timestamp=1331982075,LangId=1033,Platform=0,ScriptType=2,ScriptMajorVersion=21,ScriptMinorVersion=4,ScriptAttributes=1)
MSI (s) (C4:8C) [13:55:55:778]: Executing op: DialogInfo(Type=0,Argument=1033)
MSI (s) (C4:8C) [13:55:55:779]: Executing op: DialogInfo(Type=1,Argument=Git Extensions 3.2.1.6628)
MSI (s) (C4:8C) [13:55:55:780]: Executing op: RollbackInfo(,RollbackAction=Rollback,RollbackDescription=Rolling back action:,RollbackTemplate=[1],CleanupAction=RollbackCleanup,CleanupDescription=Removing backup files,CleanupTemplate=File: [1])
Action 13:55:55: Rollback. Rolling back action:
Rollback: ConfigureTelemetry`
```

**Comment by kaesaecracker** [comment]
As the installer is already signed it should be possible to sign the .ps1 too?

**Comment by gerhardol** [comment]
@RussKie 
Can the telemetry check run at first startup instead?

**Comment by RussKie** [comment]
We can sign the PowerShell script

**Comment by RussKie** [comment]
Can you please try this build? Please remove ".zip" extension, it is an msi file.

[GitExtensions-3.2.1.7171.msi.zip](https://github.com/gitextensions/gitextensions/files/3817255/GitExtensions-3.2.1.7171.msi.zip)

**Comment by kaesaecracker** [comment]
Sorry for responding late. I'll try this version today.

**Comment by kaesaecracker** [comment]
@RussKie the build you sent me does not work.

```
Action 11:26:21: ConfigureTelemetry. 
MSI (s) (44:68) [11:26:21:155]: Executing op: CustomActionSchedule(Action=ConfigureTelemetry,ActionType=1025,Source=BinaryData,Target=WixQuietExec,CustomActionData="C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -InputFormat None -ExecutionPolicy Bypass -Command "& 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1' ; exit $($Error.Count)")
MSI (s) (44:6C) [11:26:21:157]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSI4DD7.tmp, Entrypoint: WixQuietExec
WixQuietExec:  & : Fehler bei der AuthorizationManager-šberprfung.
WixQuietExec:  In Zeile:1 Zeichen:3
WixQuietExec:  + & 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1' ; exit $($ ...
WixQuietExec:  +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec:      + CategoryInfo          : Sicherheitsfehler: (:) , PSSecurityException
WixQuietExec:      + FullyQualifiedErrorId : UnauthorizedAccess
WixQuietExec:  Error 0x80070001: Command line returned an error.
WixQuietExec:  Error 0x80070001: QuietExec Failed
WixQuietExec:  Error 0x80070001: Failed in ExecCommon method
CustomAction ConfigureTelemetry returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 11:26:21: InstallFinalize. Return value 3.
MSI (s) (44:68) [11:26:21:771]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (44:68) [11:26:21:771]: User policy value 'DisableRollback' is 0
MSI (s) (44:68) [11:26:21:771]: Machine policy value 'DisableRollback' is 0
MSI (s) (44:68) [11:26:21:772]: Note: 1: 2318 2:  
MSI (s) (44:68) [11:26:21:773]: Executing op: Header(Signature=1397708873,Version=500,Timestamp=1332435787,LangId=1033,Platform=0,ScriptType=2,ScriptMajorVersion=21,ScriptMinorVersion=4,ScriptAttributes=1)
MSI (s) (44:68) [11:26:21:773]: Executing op: DialogInfo(Type=0,Argument=1033)
MSI (s) (44:68) [11:26:21:774]: Executing op: DialogInfo(Type=1,Argument=Git Extensions 3.2.1.7171)
MSI (s) (44:68) [11:26:21:774]: Executing op: RollbackInfo(,RollbackAction=Rollback,RollbackDescription=Rolling back action:,RollbackTemplate=[1],CleanupAction=RollbackCleanup,CleanupDescription=Removing backup files,CleanupTemplate=File: [1])
Action 11:26:21: Rollback. Rolling back action:
```

**Comment by RussKie** [comment]
Can you copy this file https://github.com/gitextensions/gitextensions/blob/master/Bin/set-telemetry.ps1, put it under `C:\Program Files (x86)\GitExtensions\` run it, and share whether it worked?

**Comment by kaesaecracker** [comment]
@RussKie Still leads to the same error. 
```
Action 08:01:24: ConfigureTelemetry. 
MSI (s) (68:C0) [08:01:24:020]: Executing op: CustomActionSchedule(Action=ConfigureTelemetry,ActionType=1025,Source=BinaryData,Target=WixQuietExec,CustomActionData="C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -InputFormat None -ExecutionPolicy Bypass -Command "& 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1' ; exit $($Error.Count)")
MSI (s) (68:94) [08:01:24:020]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSIA250.tmp, Entrypoint: WixQuietExec
WixQuietExec:  & : Fehler bei der AuthorizationManager-šberprfung.
WixQuietExec:  In Zeile:1 Zeichen:3
WixQuietExec:  + & 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1' ; exit $($ ...
WixQuietExec:  +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec:      + CategoryInfo          : Sicherheitsfehler: (:) , PSSecurityException
WixQuietExec:      + FullyQualifiedErrorId : UnauthorizedAccess
WixQuietExec:  Error 0x80070001: Command line returned an error.
WixQuietExec:  Error 0x80070001: QuietExec Failed
WixQuietExec:  Error 0x80070001: Failed in ExecCommon method
CustomAction ConfigureTelemetry returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 08:01:24: InstallFinalize. Return value 3.
```

I tried googling the error, most things I find are "you have to sign the script" and "the installer tool you are using copies the script with a different name, so the signature is invalid". Both things do not really apply here I think. The event viewer does not show anything useful either. 

The script I put into the programs folder is not signed, so that might be the problem? Also, the signature not only has to exist, it also has to be valid with regards to the locally installed certificates.

**Comment by kaesaecracker** [comment]
Directly after commenting I wanted to check something. You seem to copy the file to a different name, meaning according to my google search (you probably know more than me) the signature is not valid anymore?

(this also shows it did not overwrite the set-telemetry.ps1 I placed there manually)
```
MSI (s) (68:C0) [08:01:23:660]: Executing op: FileCopy(SourceName=mf7oykxu.ps1|set-telemetry.ps1,SourceCabKey=set_telemetry.ps1,DestName=set-telemetry.ps1,Attributes=512,FileSize=14229,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,,,InstallMode=58982400,HashOptions=0,HashPart1=1974650794,HashPart2=2051093808,HashPart3=1566467323,HashPart4=1145746872,,)
MSI (s) (68:C0) [08:01:23:660]: File: C:\Program Files (x86)\GitExtensions\set-telemetry.ps1;	Overwrite;	Won't patch;	Existing file is unversioned and unmodified - hash doesn't match source file
MSI (s) (68:C0) [08:01:23:660]: Source for file 'set_telemetry.ps1' is compressed
InstallFiles: File: set-telemetry.ps1,  Directory: C:\Program Files (x86)\GitExtensions\,  Size: 14229
MSI (s) (68:C0) [08:01:23:660]: Re-applying security from existing file.
MSI (s) (68:C0) [08:01:23:660]: Verifying accessibility of file: set-telemetry.ps1
MSI (s) (68:C0) [08:01:23:660]: Note: 1: 2318 2:  
MSI (s) (68:C0) [08:01:23:660]: Note: 1: 2318 2:  
```

**Comment by RussKie** [comment]
Sorry, I was meant to ask you to test the signed script. Here it is: [set-telemetry.ps1.txt](https://github.com/gitextensions/gitextensions/files/3858604/set-telemetry.ps1.txt)

I extracted it from the installer, this is what would be written to the folder and executed.

**Comment by kaesaecracker** [comment]
As far as I can see the file is not overwritten:
```
MSI (s) (84:28) [17:05:23:643]: Executing op: FileCopy(SourceName=mf7oykxu.ps1|set-telemetry.ps1,SourceCabKey=set_telemetry.ps1,DestName=set-telemetry.ps1,Attributes=512,FileSize=14229,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,,,InstallMode=58982400,HashOptions=0,HashPart1=1974650794,HashPart2=2051093808,HashPart3=1566467323,HashPart4=1145746872,,)
MSI (s) (84:28) [17:05:23:644]: File: C:\Program Files (x86)\GitExtensions\set-telemetry.ps1;	Won't Overwrite;	Won't patch;	Existing file is unversioned but modified
```
But the error remains the same:
```
MSI (s) (84:28) [17:05:23:960]: Executing op: ActionStart(Name=ConfigureTelemetry,,)
Action 17:05:23: ConfigureTelemetry. 
MSI (s) (84:28) [17:05:23:961]: Executing op: CustomActionSchedule(Action=ConfigureTelemetry,ActionType=1025,Source=BinaryData,Target=WixQuietExec,CustomActionData="C:\Windows\SysWOW64\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -NonInteractive -InputFormat None -ExecutionPolicy Bypass -Command "& 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1' ; exit $($Error.Count)")
MSI (s) (84:38) [17:05:23:963]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSIACAA.tmp, Entrypoint: WixQuietExec
WixQuietExec:  & : Fehler bei der AuthorizationManager-šberprfung.
WixQuietExec:  In Zeile:1 Zeichen:3
WixQuietExec:  + & 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1' ; exit $($ ...
WixQuietExec:  +   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec:      + CategoryInfo          : Sicherheitsfehler: (:) , PSSecurityException
WixQuietExec:      + FullyQualifiedErrorId : UnauthorizedAccess
WixQuietExec:  Error 0x80070001: Command line returned an error.
WixQuietExec:  Error 0x80070001: QuietExec Failed
WixQuietExec:  Error 0x80070001: Failed in ExecCommon method
CustomAction ConfigureTelemetry returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 17:05:24: InstallFinalize. Return value 3.
```

**Comment by RussKie** [comment]
Have you tried running the file directly? Does it run successfully?

**Comment by kaesaecracker** [comment]
@RussKie I think that might be the problem:
```
PS C:\Users\vsc> & 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1'

Möchten Sie Software dieses nicht vertrauenswürdigen Herausgebers ausführen?
Die Datei "C:\Program Files (x86)\GitExtensions\set-telemetry.ps1" wurde von "CN=SignPath GmbH, O=SignPath GmbH,
STREET=Werdertorgasse 14, L=Vienna, S=Vienna, PostalCode=1010, C=AT" veröffentlicht und gilt auf Ihrem System als nicht
 vertrauenswürdig. Führen Sie ausschließlich Skripts vertrauenswürdiger Herausgeber aus.
[E] Noch nie ausgeführt  [N] Nicht ausführen  [M] Einmal ausführen  [A] Immer ausführen  [?] Hilfe (Standard ist "N"):
```

Rough translation: 
```
PS C:\Users\vsc> & 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1'

Do you want to execute software by this untrusted developer?
The file "C:\Program Files (x86)\GitExtensions\set-telemetry.ps1" was published by "CN=SignPath GmbH, O=SignPath GmbH,
STREET=Werdertorgasse 14, L=Vienna, S=Vienna, PostalCode=1010, C=AT" and is not trusted on your system. Only run scripts from trusted sources.
[E] <I dont understand this option, might be bad german translation>  [N] Do not run [M] Run once  [A] Run always [?] Help (Default is "N"):
```

Confirming (I have choosen 'M') does not lead to any console output, so I guess that means it ran successfully

**Comment by mast-eu** [comment]
> Confirming (I have choosen 'M') does not lead to any console output, so I guess that means it ran successfully

Yes, the script normally produces no console output. What it does: writing the following item:
```
  <item>
    <key>
      <string>TelemetryEnabled</string>
    </key>
    <value>
      <string>True</string>
    </value>
  </item>
```
into `C:\Users\<USERNAME>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings`.

You can check the existence of this item. Deleting it manually and running the PS script again should recreate it.

Seems like the signing certificate cannot be validated on your system for some reason.
Is the target machine connected to the internet?
Do you have a firewall or something else in place that might block certificates?

**Comment by kaesaecracker** [comment]
- Yes, I can see this entry in `GitExtensions.settings`
- Yes, my machine has (pretty much full) internet access
- Yes, my machine is behind a firewall, but it is not supposed to block anything like certificates
- When I right-click the ps1-File -> Properties -> Signatures -> Details it says the certificate is valid
- PowerShell also says it is a valid signature:  
```
PS C:\Users\vsc> Get-AuthenticodeSignature 'C:\Program Files (x86)\GitExtensions\set-telemetry.ps1'


    Verzeichnis: C:\Program Files (x86)\GitExtensions


SignerCertificate                         Status                                 Path
-----------------                         ------                                 ----
CEABACE0ED7AB0A52A53A676E30835479D7CD86C  Valid                                  set-telemetry.ps1
```

**Comment by kaesaecracker** [comment]
It seems like the signature is valid but the certificate does not match anything in the trusted publisher certificate store. We are currently checking wether we have the default MS ones or only a subset of those.

**Comment by mast-eu** [comment]
[Here's](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_signing?view=powershell-6#running-unsigned-scripts-remotesigned-execution-policy) the original English error message (including a understandable first option)

```
Do you want to run software from this untrusted publisher?
The file <file-name> is published by CN=<publisher-name>. This
publisher is not trusted on your system. Only run scripts
from trusted publishers.

[V] Never run  [D] Do not run  [R] Run once  [A] Always run
[?] Help (default is "D"):
```

This happens when the certificate is _valid_, but _not trusted_.

**Comment by kaesaecracker** [comment]
Importing the certificate into the trusted publishers certificate store works, so this could be a workaround. There are still problems with this though:
- Your certificate is valid for only another 3 days
- You probably will get a new one, but that still means reimporting the certificate every month
- The same windows group policy that sets the ExecutionPolicy to AllSigned also requires the script to be signed by a trusted publisher too, which means we should not be the only company that has this problem (although it seems I am the only one to report this issue...)

**Comment by mast-eu** [comment]
> * Your certificate is valid for only another 3 days

Yes, the certificate itself expires, but it is [timestamped](https://docs.microsoft.com/en-us/windows/msix/package/signing-package-overview#timestamping). The app will remain installable up to 2030-10-17 (that's when the timestamping certificate expires).

> * You probably will get a new one, but that still means reimporting the certificate every month

Our certificates get renewed every year (not every month).
Not sure whether you'll need to manually reimport though. You'll get soon the chance to verify when we release version 3.3 😏 

> * The same windows group policy that sets the ExecutionPolicy to AllSigned also requires the script to be signed by a trusted publisher too, which means we should not be the only company that has this problem (although it seems I am the only one to report this issue...)

I also suspect that you're not the only person having this issue. You are just the only one reporting it.
Therefore I still think it's worth to fix it, even if you have found a workaround that does the trick for you.

**Comment by kaesaecracker** [comment]
Another (also dirty) fix would be to not execute the commands as a script but as a `powershell -Command "line1;line2;line3;..."`

**Comment by mast-eu** [comment]
I'm thinking of something different:

There's already a "fallback" mechanism in place, which is normally intended for portable builds. GE will show a popup on startup if the entry in `GitExtensions.settings` is missing
![60513985-d84b4480-9d1b-11e9-9077-0bf5cf88f5d2](https://user-images.githubusercontent.com/46861028/69286747-61441900-0bf4-11ea-8ec9-473611f99086.png)

What's still missing is a way to make the installer successfully finish, regardless of eventual errors in the PS script. I think there's the possibility to modify the installer to ignore errors in some of its steps, but I have to look into it.

**Comment by RussKie** [comment]
I've been thinking the same.
I've been too busy with work and family to have a look

**Comment by kaesaecracker** [comment]
Will this show the popup on every start or does answering that popup set the value accordingly? Because if it does not, just assuming a "no" when the setting is not found would be my favored compromise between getting telemetry from the clients and user experience.

**Comment by RussKie** [comment]
a user gets asked if a value is missing from the config.
so effectively the user gets asked once

**Comment by mast-eu** [comment]
I have a fix. Just need to find the time to prepare the PR - probably tomorrow.

**Comment by RussKie** [comment]
Champion!

**Comment by RussKie** [comment]
Could you please test an msi from https://ci.appveyor.com/api/buildjobs/ta7x4q5yb9o0s1y4/artifacts/combined.3.2.1.7452-unsigned.zip

**Comment by kaesaecracker** [comment]
@RussKie it finally works! As soon as 3.3 is out, we can finally roll out an update again. Nice work, thank you for building this awesome tool.

**Comment by RussKie** [comment]
Thank you for the confirmation.
Kudos go to Martin, he did the fixing.
