### ISSUE TITLE
Settings | Confirmations truncated

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7387]
## Current behaviour

The settings page "Confirmations" is truncated.
The settings dialog has a minimum height of about 775 pixels.
The page "General" is the tallest page and has 60 pixels empty height with an application font size of 8. With the default font size of 9, it's only 16 pixels.

## Expected behaviour

The GroupBox shall fit for all contained settings (else have a scrollbar).
Perhaps, we should still support screen resolutions of 1366 x 768 pixels (price-optimized notebooks).

## Steps to reproduce

open the settings page

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/68337614-2bc20a80-00e1-11ea-8479-ba9761a01c88.png)

## Did this work in previous version of GitExtensions

?

## Environment

- Git Extensions 3.3.0
- Build 083196895e1951dd7c3735e051727e2dedbc61aa
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I've been thinking, maybe we should replace custom settings pages with a `PropertyGrid` control (the one VS Designer uses to configure UI properties)?
![image](https://user-images.githubusercontent.com/4403806/70849523-9a119e00-1ed3-11ea-9f4a-8a387fdd26c6.png)

Most properties will slot right in (e.g. boolean, checkboxes, dropdowns, color pickers). For more fancy ones (e.g. file/folder picker) we can add custom editors.
