### ISSUE TITLE
Inactive remote still showing

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#7391]
## Current behaviour

I suppose this is a bit of an edge case.

I have a new repo I'm working on and have a secondary related repo added as a stand-alone remote (no shared commits) to be able to once in a while do a quick cross-check between these repos. 

When I hide/deactivate the secondary repo, it doesn't disappear from the view, all commits up to the last tagged release of the secondary still show.

While I originally noticed this behaviour with unrelated repositories, I've run a test with a forked repo, adding a tag to one of the forks and the same things happens: when I hide the fork with the tag, the tag and all commits leading up to the tag still show.

## Expected behaviour

That the deactivated remote would be completely hidden from view.

## Steps to reproduce

* Select a repo with at least two remotes - preferably remotes which have diverged quite a bit from each other -.
* Make sure at least one of the remotes has tags and preferably on one of the diverged branches.
* Go to `Repository` -> `Remote repositories` and select the remote with the tags and deactivate it.
* Close the `Remote repositories` window and check the main repo view to see the tags and all commits leading up to them still showing.

## Screenshots

Can be provided if needed, but I hope the description above is clear enough.

## Did this work in previous version of GitExtensions

Not sure.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
If I understand this correctly, this is as expected. 
Branches are related to a specific remote and are removed when removing the remote.
The commits are related to the local repo clone, not to the remote.
Same for the tags (this can maybe be derived for annotated tags, but that would be an explicit cleanup.)
 
I use this feature when resetting repos, for instance some repos that were setup before git-lfs was mainlined and that had many binary files. New repos were created with just the latest commits and the existing repos was renamed. At next pull  from the new repo, the history is combined (it would be the same for adding the secondary url).

**Comment by jrfnl** [comment]
@gerhardol Thanks for your response. Not sure I understand you correctly.

> So if you have no local branches for the repo, the commits should not be seen.

I don't have any local branches for that secondary remote though.

**Comment by pmiossec** [comment]
@jrfnl do you think that a screenshot could be helpful to understand the problem?

My understanding is that a tag is not expected to change so git is conservative with them and so does not remove them even if the remote no longer exists.

**Comment by RussKie** [comment]
i dont quite understand the problem, sorry.

when a remote is deactivated, it is git-removed. ge does some trickery in a
repo's config to show inactive remotes, but git is totally oblivious to
their presence.
so if you see something still shown it means you have some local refs.

please provide screenshots and a repro.

**Comment by jrfnl** [comment]
Just in case anyone else comes across this issue:

The issue still remained even when completely removing the second remote.

Turned out that the fact that there were tags in the remote was the root cause of this issue.

Once I'd (bulk) removed all the tags from the second remote from the repo, the second repo disappeared from the view.
