### ISSUE TITLE
GitHub Outh token can't be created; message about unsupported IE browser

### ISSUE THREAD

**Issue by maphew** [gitextensions/gitextensions#7392]
## Current behaviour

I am unable to complete GitHub generate oauth token wizard. 

## Steps to reproduce

_Gitex >> Plugins >> GitHub_

There's a message in the page from GitHub about Internet Explorer not being a supported browser. I can enter username and password and proceed to next step, where I see the expected information about organization and access to repositories. However the green [authorize] button remains inactive and can't be pushed. There's no apparent way to interact with the page to change the situation.

I was able to to use right-click context menu, find the page URL, copy and paste to a Chrome window where I was already logged into GitHub.  From there I finished the authorization process, however I haven't been able to find a way to retrive the oauth number from Github and give to Git Extensions manually.

## Did this work in previous version of GitExtensions

Yes, but I don't know how long ago.

## Environment

-- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3752.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Fixed by #6888 (by no more using the browser to get the token).
Waiting for the next version to be released.

**Comment by maphew** [comment]
When I use _Plugins >> GitHub_ there is the message "successfully retrieved oauth token". However all push requests fail with access denied:
~~~
"C:\Program Files\Git\bin\git.exe" push --recurse-submodules=check --progress "origin" refs/heads/master:refs/heads/master
remote: Permission to envygeo/arcscripts_archive.git denied to maphew.
~~~

Note: the username is wrong.

I tried to start over from square one, but now I don't seem to be able to get into the Github oauth wizard at all. I went to _Plugins >> Plugin settings >> Github_, deleted the oauth number, applied, then exited and restarted Gitext. Going to _Plugins >> Github_ I get the successful token message again but no opportunity to go through the wizard.

**Comment by maphew** [comment]
@pmiossec our posts crossed in transit. Is there something I can do while waiting for next release?

**Comment by RussKie** [comment]
you can download a portable version from the latest build, and use it in
mean time
