### ISSUE TITLE
Crash on Missing Settings Directory

### ISSUE THREAD

**Issue by davidrpalmer** [gitextensions/gitextensions#7395]
## Current behaviour

When using Git Extensions from another Windows account (not the one the installer was run from) the directory `C:\Users\David\AppData\Roaming\GitExtensions\GitExtensions\` is not created. As a result settings either fail to save silently, or cause a DirectoryNotFoundException.

Manually creating this directory resolves the issue.

## Expected behaviour

If the `C:\Users\David\AppData\Roaming\GitExtensions\GitExtensions\` directory does not already exist then Git Extensions should create it.

## Steps to reproduce

Log in with a new Windows user account, or simply delete/rename the `C:\Users\David\AppData\Roaming\GitExtensions` directory. Git Extensions will start up like the first time but will be unable to save any settings.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4042.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
GE creates an empty folder `%APPDATA%\Git Extensions\Git Extensions\3.3.0` on every startup -- notice the spaces.
The `ApplicationDataPath` is tweaked in order to load the settings of previous versions from folders without spaces since #6729. This is done too late for the automatic creation of the settings folder.

**Comment by RussKie** [comment]
> GE creates an empty folder `%APPDATA%\Git Extensions\Git Extensions\3.3.0` on every startup -- notice the spaces.

This is wrong, if we are doing this - it is a regression.
We should be creating `\GitExtensions\GitExtensions\` folder.
