### ISSUE TITLE
Selection in graph view always reverts to an old value after committing

### ISSUE THREAD

**Issue by johndog** [gitextensions/gitextensions#7404]
I don't have great steps for this, but I see the issue consistently, eventually.  Starting up a new instance seems to eliminate the problem for a while, but it always comes back.  Hoping someone else can confirm my observation.

## Current behaviour

Somehow GitEx gets into a state in which every time I close the commit dialog after creating a commit, the selection in the GitEx main window warps to a very old selection/branch.  After creating a commit it has to refresh the graph, and that's when it happens.  This could also occur after a rebase or a revert.

## Expected behaviour

When closing the commit UI after creating a commit, the selection should either stay where it was or warp to the new HEAD.  It should not revert back to an unrelated commit.

## Steps to reproduce

0. Use git extensions for a while (steps unknown)
1. Select the head commit
2. Right-click, revert the commit (automatically commit)

Result:  Selection reverts to some old commit, pages down from HEAD.
Expect:  Selection goes to either the new HEAD commit or to the previously selected commit (not sure which)

Note:  restarting the app will eliminate the behavior for a while.

## Did this work in previous version of GitExtensions

Probably.  Seems like it started in recent months.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.22.0.vfs.1.1.57.gbaf16c8
- Microsoft Windows NT 10.0.19018.0
- .NET Framework 4.8.3921.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate #6663

**Comment by johndog** [comment]
Yep!  Looked for an original, failed to find it.
