### ISSUE TITLE
Move rebase/biset/merge warning from status bar to revision grid

### ISSUE THREAD

**Issue by nick-bulleid** [gitextensions/gitextensions#7407]
### Move rebase/biset/merge warning from status bar to revision grid

Currently this warning is a bit lost in the status bar. It would be nice if it was displayed in a header above the revision grid. It could also contain buttons to the most used commands eg Continue and Abort for rebase.

I'm happy to take a look at this myself, just wanted to gauge interest in it first.

## Environment

- Git Extensions 3.3.0
- Build 18edfc7c88570f4b238f78b47e2428f7729e6249
- Git 2.14.1.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
We can certainly consider this.
Can you do some visual mockup/prototypes showing how in your vision it would look like?

**Comment by nick-bulleid** [comment]
Here is what I have so far for the rebase case:

![rebase_header](https://user-images.githubusercontent.com/19927400/68805658-2a05c300-065c-11ea-9482-646d18093afc.PNG)

**Comment by RussKie** [comment]
Nice!
Is the bottom status bar notification getting removing?

**Comment by nick-bulleid** [comment]
> 
> 
> Nice!
> Is the bottom status bar notification getting removing?

Yes, I'll remove it when the new system is working.
