### ISSUE TITLE
Extendable Custom Actions

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#7409]
Add an ability to extend drop down menu with configurable custom actions.
For instance Fork Git and SourceTree have customization points:

![image](https://user-images.githubusercontent.com/580536/68748749-a7eaaf80-0605-11ea-9a49-ce6a8abe0f4d.png)

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4042.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Could you explain us more in details in what it is different from [Scripts](https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#git-extensions-scripts) that GitExtensions already provide? What is missing? What is different?

**Comment by NN---** [comment]
Thanks, exactly what I need.

The only noticeable difference is that you can configure commands not only for context menu on commit in the graph but for branch context menu (side bar) and file context menu (down).

**Comment by pmiossec** [comment]
>Thanks, exactly what I need.

Great!

>The only noticeable difference is that you can configure commands not only for context menu on commit in the graph but for branch context menu (side bar) and file context menu (down).

If you really need that, please open a new issue that describe clearly what is the improvement needed (as I will close this issue)
