### ISSUE TITLE
[NBug] Index non compreso nell'intervallo. Richiesto valore non ne...

### ISSUE THREAD

**Issue by LinoBarreca** [gitextensions/gitextensions#7410]
## Current behaviour
Crash and quit.

## Expected behaviour
No crash and no quit.

## Steps to reproduce
Switched the reflog reference combobox and then I went on the grid.

## Error Details
```
System.ArgumentOutOfRangeException: Index non compreso nell'intervallo. Richiesto valore non negativo e minore della dimensione della raccolta.
Nome parametro: index
   in System.Collections.ArrayList.get_Item(Int32 index)
   in System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   in System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   in GitUI.CommandsDialogs.FormReflog.gridReflog_MouseMove(Object sender, MouseEventArgs e)
   in System.Windows.Forms.Control.OnMouseMove(MouseEventArgs e)
   in System.Windows.Forms.DataGridView.OnMouseMove(MouseEventArgs e)
   in System.Windows.Forms.Control.WmMouseMove(Message& m)
   in System.Windows.Forms.Control.WndProc(Message& m)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information

**Comment by pmiossec** [comment]
Should be fixed with #7411.

You could test the portable version generated by the build: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/28825122/artifacts

and confirm us if it fixes the bug (it should ;) ).

**Comment by LinoBarreca** [comment]
wow. that was fast. :D
I honestly can't reproduce the error on a constant basis...I mean...when i had it it popped up after just one simple switch but now it doesn't anymore.
However, if I play with the window and the combobox a bit, after a while that error pops up....have you been able to reproduce it?

**Comment by pmiossec** [comment]
>have you been able to reproduce it?

yes, with a specific branch.

>I honestly can't reproduce the error on a constant basis...

I also had difficulties to reproduce it every time even with the understanding on how it could happen.

That's(sometimes) when you select a reference with a lot of line and select a line far from the top lines and then switch to a reference having less lines than the index of the one previously selected.

I have fixed that (reset index when switch ref) and also implemented a control to prevent it again (for some other reason).
