### ISSUE TITLE
NullReferenceException during update check

### ISSUE THREAD

**Issue by LinoBarreca** [gitextensions/gitextensions#7413]
## Current behaviour
![image](https://user-images.githubusercontent.com/897723/68757493-50037700-060c-11ea-9235-99d82f5638a1.png)

## Expected behaviour
:smiley: :tada: 

## Steps to reproduce
Help - Check for updates

## Screenshots
Look above.

## Did this work in previous version of GitExtensions
Sorry. I installed it a few days ago. Nice app!!

## Environment
![image](https://user-images.githubusercontent.com/897723/68757758-c7390b00-060c-11ea-9c8a-54813efe06e5.png)

I'm behind a corporate proxy (maybe could be that?)

## Diagnostics

**Comment by RussKie** [comment]
Thanks!

I thought we have fixed that yonks ago...

**Comment by LinoBarreca** [comment]
@RussKie maybe you did but the latest version downloadable [here](https://github.com/gitextensions/gitextensions/releases) (not built from git) still has the bug.
