### ISSUE TITLE
Bad things happen when you switch repositories (error in PATH)

### ISSUE THREAD

**Issue by LinoBarreca** [gitextensions/gitextensions#7415]
## Current behaviour
The folder stays the same (see screenshot).
I think it might mess with the repository if it launches git commands thinking he's on the right path (didn't try since it's dangerous)

## Expected behaviour
Should work.

## Steps to reproduce
Open program.
Open repository.
Do something.
Go to console.
Do something.
Click on Start - Recent repositories - choose one.
Look at the terminal.
GitExtensions issues a "CD" command but it's a wrong path because it includes the drive so the working directory stays the same.

## Screenshots
![image](https://user-images.githubusercontent.com/897723/68764428-f9516980-061a-11ea-9230-fc6e5c450ea7.png)

## Did this work in previous version of GitExtensions
Don't know.

## Environment
Same as #7413 

## Diagnostics
not relevant

**Comment by pmiossec** [comment]
The problem is more than the command to change the directory must be dependent of the shell run inside the console tab.

For the moment only the one for the `bash` shell has been implemented.

**Comment by pmiossec** [comment]
Looking at the code (https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/FormBrowse.cs#L3004), that's already implemented.

Did you change the shell directly from inside the console tab? In this case, that impossible to detect.

**Comment by LinoBarreca** [comment]
I didn't change anything in settings.
Default installation of gitextensions.
Opened gitextensions.
Opened a repository.
Did a rename.
I used the console to issue the command that you read above (I didn't know if I could do that through the gui and how) and then I changed repository through menu.

that "cd" wasn't from me gitextensions tried to "CD" to the new repository but used the wrong path.

**Comment by LinoBarreca** [comment]
what I did, however, with gitextension closed, is changing the visual studio code default shell to bash.
Maybe this is saved in the repository somewhere?
Maybe when I open the console tab you start the git bash instead of cmd?

**Comment by pmiossec** [comment]
> it's a wrong path because it includes the drive

The problem is not due to the drive because that the format of the posix paths used by bash.
The problem is elsewhere and we must figure it where.
Perhaps the space that is not escaped by a `\`?

You could try different things by trying yourself the command until you understand what is the **real** problem...

**Comment by pmiossec** [comment]
But surrounding the path by double quotes must fix the problem... (and we should probably do that...)

**Comment by LinoBarreca** [comment]
> 
> 
> > it's a wrong path because it includes the drive
> 
> The problem is not due to the drive because that the format of the posix paths used by bash.
> The problem is elsewhere and we must figure it where.
> Perhaps the space that is not escaped by a `\`?
> 
> You could try different things by trying yourself the command until you understand what is the **real** problem...

No space.
![image](https://user-images.githubusercontent.com/897723/68774019-c7e19980-062c-11ea-9bae-fd3e3c49b240.png)

**Comment by LinoBarreca** [comment]
it's the drive.
![image](https://user-images.githubusercontent.com/897723/68774143-f1022a00-062c-11ea-9e5e-1145e60a88de.png)

**Comment by LinoBarreca** [comment]
found where the problem is:
We are not in bash but in cmd and the program thinks we are in bash (easy to check by issuing a "pwd" or a "dir")

**Comment by pmiossec** [comment]
Indeed, I found myself. Sorry.

That's because that's not a `bash` shell (we could see it with the path displayed)
Even if GE think it is a bash because the default config launch a `bash` in theory.

Perhaps you set to use "cmd" during the git install?

And that's not the drive the problem 😉 (it works well for me in the bash since months or perhaps years ):
![image](https://user-images.githubusercontent.com/460196/68774852-0166d480-062e-11ea-857d-c6dd2d3ab350.png)

**Comment by LinoBarreca** [comment]
came to same conclusion 2 seconds earlier! :rofl:

**Comment by pmiossec** [comment]
>came to same conclusion 2 seconds earlier! 🤣

That's just that my text was longer to write. So, I won ? 🤣

**Comment by LinoBarreca** [comment]
> 
> Perhaps you set to use "cmd" during the git install?

Don't remember. Sorry. For sure I use vs code with bash as default.
if in vscode terminal I write "pwd" I get

> $ pwd
> /c/Users/Lino Barreca/Documents/PlatformIO/Projects/Marlin

if I do the same in GE
I get the "dos" format

**Comment by pmiossec** [comment]
Set the setting in GE to bash and after restarting, it should be ok:

![image](https://user-images.githubusercontent.com/460196/68775789-59520b00-062f-11ea-8027-1bf72853981e.png)

**Comment by LinoBarreca** [comment]
This is my view:
![image](https://user-images.githubusercontent.com/897723/68776030-b51c9400-062f-11ea-8850-252a90ca0f3e.png)

Should those combobox contain something?
I guess that's something to check anyway...

> 
> > came to same conclusion 2 seconds earlier! rofl
> 
> That's just that my text was longer to write. So, I won ? rofl

dude.....deal with it. :rofl: 
"Ask any racer, any real racer. It doesn't matter if you win by an inch or a mile, winning's winning."

**Comment by LinoBarreca** [comment]
and that's where the bug is.
![image](https://user-images.githubusercontent.com/897723/68776435-599ed600-0630-11ea-84fc-db62c5d4ded4.png)

**Comment by mstv** [comment]
The first strange-looking command is correct. It is a check for Unicode IIRC.

**Comment by LinoBarreca** [comment]
oh..ok..it looked like a wrong command...then what's the reason why my settings on the page console emulator are empty/grayed? (I guess it's the same reason why the console tab misbehaves)

**Comment by mstv** [comment]
Perhaps, these settings have not been set yet and default to `null`.
Can you set them? Are they retained over restart of GE?
You could check before, whether the file `%APPDATA%\GitExtensions\GitExtensions\GitExtensions.settings` exists. If not create the folder, please. Or use the current dev build.

**Comment by pmiossec** [comment]
Yes, that's just that they have not been set. So doing it will solve the
problem.

**Comment by LinoBarreca** [comment]
I can definitely set them.... thing is: why with the default installation the program behaves that way?
"show console tab" is, logically, yes or no. that's "null"..so why do I see the console (that behaves weirdly)? if it's null does it inherit the setting from somewhere else? if so it inherits the shell type too...
I guess that's something you should look at (maybe with low priority but still...)

**Comment by lschmalen** [comment]
I can see a related issue:

Open program.
Open repository.
Do something.
Go to console.
Do something.
Click on Start - Recent repositories - choose one. (Alternative, choose a different repository from the drop down menu)
Look at the terminal.

Now the terminal hangs for me and the console doesn't react on the keyboard anymore. Interestingly, after the console loses focus, I can clicky on the console and it the cursor takes the focus (blinks) but it doesn't change the directory (as I'd expect), nor does it react to my input. The console uses git bash. I use the following environment:
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Fixed. Update to new v3.4 release.
