### ISSUE TITLE
Test DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending opens external diff and fails

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7417]
## Current behaviour

The test `DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending` fails occasionally for different arguments. Instead it opens my external diff viewer.

```
DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending(input,"WindowsLines")
   Source: FileViewerTextTests.cs line 43
   Duration: 914 ms

  Message: 
      Expected string length 26 but was 0. Strings differ at index 0.
      Expected: "Line 1\r\nLine 2\r\n\r\nLine 3\r\n"
      But was:  <string.Empty>
      -----------^
```

```
DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending(true,"WindowsLines")
   Source: FileViewerTextTests.cs line 43
   Duration: 423 ms

  Message: 
      Expected string length 26 but was 0. Strings differ at index 0.
      Expected: "Line 1\r\nLine 2\r\n\r\nLine 3\r\n"
      But was:  <string.Empty>
      -----------^
```

## Screenshot

![grafik](https://user-images.githubusercontent.com/36601201/68810604-e10b3a00-066e-11ea-9c27-1f5932ff3af4.png)

## Expected behaviour

test passes and does not open external diff

## Steps to reproduce

run tests of Debug build locally

## Did this work in previous version of GitExtensions

not sure

## Environment

- Git Extensions 3.3.0
- **Debug** Build ff78f708dad5bf857f880c1544dcb59194fe6e2a
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

## Diagnostics

`core.autocrlf = true` for the GE repo
`core.autocrlf` not set "globally for all repos"

**Comment by gerhardol** [comment]
This problem has two parts, first that the test fails and secondly that a diff tool is started to view the result.

For the second part, this is ApprovalTests trying to be nice and search my system for every difftool it can find.
It is not the Git diff tool configuration, seem to be internal to Approval or VS test runner.
Unfortunately for me it finds TortoiseGitMerge.exe first but it cannot start the tool so I get a number of popups.
This may be locally configurable (I did not find it), but the behavior can be changed with an attribute.
[UseReporter(typeof(ClipboardReporter))]

I would like to add that for this test

**Comment by mstv** [comment]
> but the behavior can be changed with an attribute.
[UseReporter(typeof(ClipboardReporter))]

I hesitated because of the `ClipboardReporter`. But it does not matter because the tests flood the Clipboard (history) anyway. It will definitely be an improvement.

**Comment by RussKie** [comment]
I raised https://github.com/gitextensions/gitextensions/issues/8000 to track the issue with tests.
For now we can disable the tests.

I'm not particular fond of using `ClipboardReporter` tbh.

@SimonCropp is there a way to control the order of difftool search? 
I've scanned ApprovalTests code but I couldn't see it.

**Comment by SimonCropp** [comment]
@RussKie https://github.com/SimonCropp/DiffEngine/blob/master/docs/diff-tool.order.md

**Comment by RussKie** [comment]
@SimonCropp wow, that's a fast response! Champion!

@gerhardol would this work for you?

**Comment by SimonCropp** [comment]
u should also be using `AllFailingTestsClipboardReporter` https://github.com/approvals/ApprovalTests.Net/blob/master/src/ApprovalTests/Reporters/AllFailingTestsClipboardReporter.cs

**Comment by SimonCropp** [comment]
and i am looking into Git diff tool detection in DiffEngine

**Comment by RussKie** [comment]
I may have data in the clipboard, and I wouldn't like it wiped out.

**Comment by SimonCropp** [comment]
@RussKie i get that. I have a clipboard history app so dont have an issue. but would u like an environment variable to prevent clipboard tampering?

**Comment by RussKie** [comment]
This is an interesting idea. I'd say yes.

It may explain why some of clipboard tests fail in WinForms repo run locally.

**Comment by SimonCropp** [comment]
> It may explain why some of clipboard tests fail in WinForms repo run locally.

sorry. not sure i understand, can u expand on that

**Comment by gerhardol** [comment]
>> It may explain why some of clipboard tests fail in WinForms repo run locally.

> sorry. not sure i understand, can u expand on that

The core problem is that the tests that involve the clipboard fails.
I have what I know no such app installed but the tests fail anyway.
But if something external can interfere with the tests, of course that must be eliminated.

For me these tests fail at least 9 times out of 10 when testing normally, except when provoking these tests only where it fils 1 out of 2 or so.

>> https://github.com/SimonCropp/DiffEngine/blob/master/docs/diff-tool.order.md

> would this work for you?

This is the second part, the user get confused by in my case popups, for others just the difftools.
This should probably be setup to not open any difftool by default, add comments how to in the test instead.
The clipboard reporter was the closest to disable the 'helper' for seeing the failure for the diff. (The clipboard is changed by the test anyway.)

I tried to set the environment variable to other difftools that work (Meld, TortoiseDiffMerge) that works but I still get the TortoiseMerge.exe popups.
If there were a None or Abort tool, no popup would be shown.

![image](https://user-images.githubusercontent.com/6248932/79541051-729d2e80-8089-11ea-97f5-5decba4289f2.png)
![image](https://user-images.githubusercontent.com/6248932/79541141-96f90b00-8089-11ea-8039-1288c5265818.png)

**Comment by gerhardol** [comment]
> For now we can disable the tests.

If there is no other solution, we could disable the tests in Debug and add comments.

**Comment by RussKie** [comment]
> sorry. not sure i understand, can u expand on that

Unrelated to this repo, but in https://github.com/dotnet/winforms tests dealing with clipboard fail

**Comment by RussKie** [comment]
let's disable the tests completely, I'll work on them as part of #8000.
