### ISSUE TITLE
Long launch of the application in the absence of a network

### ISSUE THREAD

**Issue by pincher1519** [gitextensions/gitextensions#7418]
If the computer does not have Internet access (closed internal network), then the application starts up almost a minute due to several calls to the Google server (?).
In the settings, "automatic update check" is disabled.

**Comment by RussKie** [comment]
please provide all requested information, without it we may not be able to
provide meaningful help

**Comment by pincher1519** [comment]
## Current behaviour
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3324.0
- DPI 96dpi (no scaling)

## Steps to reproduce
- Disable network
- Start the application

## Did this work in previous version of GitExtensions
The problem is repeated on all versions 3.x
There were no problems in versions 2.x

**Comment by pincher1519** [comment]
Did you reproduce the problem?

**Comment by RussKie** [comment]
No, I can't repro it.
We don't make any calls to google. Without network logs we can't triage it.

**Comment by pincher1519** [comment]
Pay attention to the log of the ProcessMonitor. Application launch time (first access to the network) and the time when the window only appeared on the screen (last access). It took 40 seconds to launch the application.

![20191210_091619](https://user-images.githubusercontent.com/34896014/70501169-6844b400-1b2e-11ea-9912-b783faa50eb4.png)

**Comment by RussKie** [comment]
I do not observe any calls from GE in procmon.

**Comment by pmiossec** [comment]
I don't reproduce neither.
What I have observed using ProcMon with GitExtensions 3.3 (dev build):

If telemetry is disabled, GitExtensions makes no calls and start immediately.

When telemetry is enabled:
If there is a internet connection, GitExtensions makes calls to AppInsight and start immediately (path displayed for me is the proxy of my company).

If there is a **no** internet connection, GitExtensions makes **no**calls to AppInsight and start immediately.

So please test again with the 3.3RC1 published.

I see another possibility, highly hypothetical: You are also behind a proxy that block the AppInsight requests even if you have access to internet (so GitExtensions think it could do the call).

To test this hypothesis, disable telemetry (in `Settings -> General`) and please report the result.

**Comment by pincher1519** [comment]
Checks carried out above were already carried out with telemetry disabled.

Log from Process Monitor when telemetry is turned on:

![enabled-telemetry](https://user-images.githubusercontent.com/34896014/70521085-adc5a900-1b4f-11ea-895a-ef29b15ffc6f.png)

Log from Process Monitor when telemetry, GAvatar are off
![disable-telemetry](https://user-images.githubusercontent.com/34896014/70521087-ae5e3f80-1b4f-11ea-822e-792c4e96ca3d.png)

The local network does not have full Internet access, but there are some exits to microsoft sites, for example msdl.microsoft.com.

PS: If you disconnect the network adapter, then the launch is quick and the above network accesses are missing.

**Comment by RussKie** [comment]
Both screenshots show same hosts being hit, no real difference between telemetry/gravatar on or off.

If gravatar is blocked at your corporate proxy, the proxy may be causing time-outs. I don't believe there is anything the app can do in this case.

**Comment by pincher1519** [comment]
If this appeal to the network is very necessary and it is impossible to refuse it optionally, then my solution would be this:

The application could interrogate the network not in the main thread of the application, thereby not slowing down the launch and continue to work in normal mode.

In a separate thread, all long operations asynchronously and hang waiting for answers or flying out by timeouts.

**Comment by RussKie** [comment]
We are loading avatars on the back thread.
Without a reliable way for us to repro the issue we can't do much here.

**Comment by pincher1519** [comment]
It was not specifically about avatars or telemetry, they turned off, as I showed above.
We are talking about some other calls to the network that are not related to the working repository or TeamCity

**Comment by RussKie** [comment]
I am not aware of any other network calls that the app is making as part of
the start up or normal operation.

If we're unable to repro there's little we can do to help.
