### ISSUE TITLE
Switching Branch in Visual Studio Introduces File Changes in Git Extensions

### ISSUE THREAD

**Issue by Mike-EEE** [gitextensions/gitextensions#7428]
## Current behaviour

Hey all, I'm a big fan of this product.  I use it all the time to make up for the lack of features in Visual Studio. :)  However, one issue I have noticed is that if I commit all changes in Visual Studio, and then switch to another branch in Visual Studio, Git Extensions seems to get confused.  Files will be shown as changed/edited in Git Extensions when in Visual Studio it shows that nothing is changed.

I have to go into the Commit dialog, select all files and press `R` to remove all changes.

## Expected behaviour

State would be consistent between Git Extensions and Visual Studio.

## Steps to reproduce

1. Make edits in one branch
2. Commit in Visual Studio.
3. Switch to new branch in Visual Studio.

## Screenshots

![](https://i.imgur.com/Fr3wiDN.png)

## Did this work in previous version of GitExtensions

I've noticed this for as long as I have used Git Extensions... seems like several years now?  It doesn't seem like it's getting fixed so I am reporting it now. 😁

Maybe it's a special setting in Git Extensions?  TBH I am still learning everything!

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by Mike-EEE** [comment]
Actually, investigating this further, no commit is needed.  I am able to reproduce this simply by switching branches in Visual Studio and Git Extensions marks files as edited.  When I switch branches in Git Extensions, there are no edits.

Here is a video of what I am seeing.  You can see that when I switch between branches in Git Extensions it works exactly as expected.  But then when I switch between the same two branches in Visual Studio, the Commit window shows 89 changes:

https://youtu.be/rCGyBo3a3H0

**Comment by gerhardol** [comment]
I cannot reproduce
GE lists the status with Git commands so also _git status_ should do the same
MSVS may not use the same Git client but this should be the same regardless.

**Comment by pmiossec** [comment]
Looking at the diff of the file in the screenshot make me think that this is a problem of end of line handling and that either your configuration is bad or Visual Studio is not handling that well.

It must not be a problem with Gitextensions as it does not touch the files and that's VS that do the checkout (badly).

Could you:
* tell us the result of the command line 'git status' (to confirm that VS put them in a bad state) 
* tell us what is the value of the 'core.autocrlf' setting
* I think you don't use a `.gitattributes` file. That probably would solve your problem and it is a good practice to use it. Do it and see if that fix your problem. If you already use it what is the content of this file? and is it different in the source and destination branches?

**Comment by RussKie** [comment]
Two kinds can't rule in the same castle... So running two different git processes against the same repo may cause troubles

What happens if you switch branches in VS, then stage all files in GE?

**Comment by Mike-EEE** [comment]
OK cool!  Thank you all for your feedback and questions.  As I mentioned I still consider myself a newb with git and am learning a lot about it, so there for sure might be a configuration issue on my side... but also as @RussKie states, these two simply might not play along well here and I might have to file a (yet another 😔) bug with the Visual Studio team.

In fact, I had to do exactly that.  Upon my investigation with `git status` as @pmiossec  suggested, I see that there are indeed modified files in git but they simply do not show in Visual Studio.

So, this doesn't look like a Git Extensions problem at all, but Visual Studio.

I created an issue here if you'd like to follow along.

https://developercommunity.visualstudio.com/content/problem/823707/git-stash-leaves-modified-files-in-working-directo.html

Closing this for now... will re-open if needed (but highly unlikely).

Thanks again for all your great work with this product!  It's really the only one that I have used (and I have tried a lot!) that makes Git easy to visualize and, therefore, understand.

**Comment by pmiossec** [comment]
I highly advise you to use a '.gitattributes' file. It could solve your problem.

**Comment by Mike-EEE** [comment]
Ah OK I will do that, @pmiossec, thank you.  It would seem that if Visual Studio is mucking around with Git and not accurately reflecting its actual state that they would do this from the start.

That is, I do not seem to need any additional files when using Git Extensions by itself... but only when I am using Visual Studio with Git.

**Comment by Mike-EEE** [comment]
FWIW I landed on this one, @pmiossec 

https://github.com/alexkaratarakis/gitattributes/blob/master/CSharp.gitattributes

Looks nice and simple. 😆

Unfortunately, it does not seem to do anything in regards to the issue I am facing with Visual Studio.  I honestly think it's a bug on their end.

Despite that, I would be interested in hearing any additional settings you feel might assist.  The documentation available for this file is exhaustive... and exhausting. 😞

https://git-scm.com/docs/gitattributes

**Comment by Aashishkebab** [comment]
It is a bug. It has been a bug for many years and continues to be one.

https://developercommunity.visualstudio.com/t/Visual-Studio-randomly-modifiesreverts-/10782463
