### ISSUE TITLE
Commit message frame size is not saved

### ISSUE THREAD

**Issue by Neon4eg** [gitextensions/gitextensions#7430]
## Current behaviour
Commit window:
Message frame takes 50% height at window open.
Message frame height is not saved and being reset to default state on Commit window reopen

## Expected behaviour
Message frame height  should be saved after it was changed

## Steps to reproduce
1. Open Commit window
2. Make message frame smaller
3. Close Commit window
4. Open Commit window

## Did this work in previous version of GitExtensions
Yes

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4042.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I am unable to reproduce it. All sizes are persisted correctly.
Please provide more info
