### ISSUE TITLE
Don't make "Abort" the default button

### ISSUE THREAD

**Issue by m417z** [gitextensions/gitextensions#7431]
Many operations open a dialog with options which I usually don't want to change (e.g. the push dialog). That's OK, I'm used to just quickly press Enter.

Many other operations open a console-hosting window (image below). Sometimes I automatically press Enter right after the window opens, because that's such a common flow. In this case, the operation aborts since the "Abort" button is focused by default.

Suggestion: don't make the "Abort" button focused by default. For example, the console-hosting control can be focused instead. 

![image](https://user-images.githubusercontent.com/4129781/69156719-82b9dd80-0aec-11ea-8331-9ed1dc8f441e.png)

**Comment by mstv** [comment]
I would agree but I cannot reproduce. Also I was afraid to abort commands mistakenly.
Though on my machines, the `Abort` button does not have the focus. When the command has finished, the OK button _is_ focused:
![Abort](https://user-images.githubusercontent.com/36601201/69190508-d5ad8800-0b20-11ea-8d03-056cb4755f6e.png) ![OK](https://user-images.githubusercontent.com/36601201/69190558-eeb63900-0b20-11ea-8a72-a226ace8faf5.png)
Your screenshot looks identically. Just hit `Enter`, nothing will happen. If not, reopen this issue, please.

**Comment by RussKie** [comment]
This is a progress dialog, and a user must be able to cancel the progress at any time.
Just like:
![image](https://user-images.githubusercontent.com/4403806/69207287-544b0980-0ba3-11ea-9c33-e41c3516463f.png)

If the abort button doesn't have focus, the user may not be able to cancel an operation and it could lead to loss of data.

**Comment by m417z** [comment]
@mstv 

> I would agree but I cannot reproduce.

Try the "Fetch all" command for example. Demonstration:

![2019-11-20_10-52-35](https://user-images.githubusercontent.com/4129781/69223353-e04d3900-0b83-11ea-93f1-ac1c9bf19e7b.gif)

> When the command has finished, the OK button _is_ focused:

That's because the "Keep dialog open" option is enabled. Regardless, if you click Enter before the command finishes executing, Abort will be focused.

> If not, reopen this issue, please.

I can't. Please reopen it.

@RussKie 

> a user must be able to cancel the progress at any time.

I agree, I just don't think the Enter key should default to Abort. There are other, better options: clicking Abort with the mouse, Escape, Ctrl+F4, Tab+Enter/Space, Alt+A, ...

> it could lead to loss of data.

I believe it's a weak argument. Most command are quick to execute anyway, and such Abort shouldn't be relied upon. The way I see it, it's more useful for commands which take a long time and you give up on them. If a command can lead to loss of data, show a confirmation before executing the command.

**Comment by RussKie** [comment]
Your request appears to be based on your personal habit of "quickly hitting Enter". This doesn't sound to me as a compelling reason for a change. 
We have hundreds of thousands of users, what makes you think they appreciate the change?

There are Windows guidelines that I would mostly base my decisions on - https://docs.microsoft.com/en-us/windows/win32/uxguide/win-dialog-box.
In particular I believe [this section is relevant](https://docs.microsoft.com/en-us/windows/win32/uxguide/win-dialog-box#guidelines):
![image](https://user-images.githubusercontent.com/4403806/69228828-67c49780-0bd8-11ea-97a1-f6b0e3b46024.png)

When the progress dialog opens, there are two controls a user is expected to interact with 99% of the time - "Abort" and "OK" buttons (in fact, unticked "Keep dialog open" renders "OK" button irrelevant). Since "OK" button is disabled, "Abort" has the focus.
There is a use-case where git prompts a user interaction and the user needs to switch to the console, but it is not the mainstream use case.

**Comment by m417z** [comment]
> We have hundreds of thousands of users, what makes you think they appreciate the change?

Well, I might not be the only one who's been bitten by this. It's just that it happened enough time for me that I decided to create an issue. But yes, it's a suggestion which is relevant to my personal habit. In the end, it's your project and your call as of whether you decide to improve the usability for users with such a habit, while (I believe) not hurting the usability of other users.

**Comment by mstv** [comment]
> I just don't think the Enter key should default to Abort. There are other, better options: clicking Abort with the mouse, Escape, Ctrl+F4, Tab+Enter/Space, Alt+A, ...

I agree. `Escape` is much more intuitive to me for `Abort`.

> That's because the "Keep dialog open" option is enabled. Regardless, if you click Enter before the command finishes executing, Abort will be focused.

I cannot reproduce neither with nor without "Keep dialog open".
In your demonstration, the `Abort` button has no focus rect (dotted frame), and the `OK` button gets enabled at the end.
Please give us the information from the `About` dialog as requested in the issue template!
Additionally, the settings from the page "Advanced" might be related.

**Comment by m417z** [comment]
Here's a recording with "Keep dialog open". Note that every time I just press Enter. First time I wait till completion, and then only the OK button is enabled, and it gets activated. In other times I press Enter before execution completes, and Abort activates. Note also the errors of ConEmu, which adds to the unpleasant experience when this happens (sometimes I'm not even sure whether the command actually executed). Sometimes a dangling cmd window pops up as well.

![2019-11-20_14-57-45](https://user-images.githubusercontent.com/4129781/69240886-23200880-0ba6-11ea-882d-306ad825c808.gif)

> Please give us the information from the `About` dialog

```- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4010.0
- DPI 96dpi (no scaling)
```

> the settings from the page "Advanced" might be related

I don't think I changed anything there, but [here you go](https://i.imgur.com/O9bKbI5.png).

**Comment by mast-eu** [comment]
I'm against changing this.
Enter activates buttons. This is common UX. And when there's only one (active) button, I'd expect it to be activated when hitting enter.

Actually, the abort button saved me more than once from pushing something that was not yet intended to be pushed.

**Comment by mstv** [comment]
> And when there's only one (active) button, I'd expect it to be activated when hitting enter.

There are two visible buttons. And it's more common that `Enter` activates `OK` and `Esc` activates `Abort`.
If an input dialog disables the `OK` button, e.g. because of yet invalid input, `Enter` does _not_ cancel the dialog.

**Comment by mast-eu** [comment]
As RussKie [already wrote](https://github.com/gitextensions/gitextensions/issues/7431#issuecomment-555822861), I too see it as a _progress dialog_.
It's not an _input dialog_ like e.g. "Print" or Save file as ..."

Consider another example:
![image](https://user-images.githubusercontent.com/46861028/69431909-f18b7680-0d38-11ea-9f60-71a428290c60.png)
While the installation is in progress, only the cancel button is active. Hitting `enter`, will abort the installation. Hitting `esc` doesn't do anything.

This is exactly the same situation. At the end of the installation routine, hitting enter will simply close the dialog:
![image](https://user-images.githubusercontent.com/46861028/69432323-c81f1a80-0d39-11ea-901a-e09a5681a4d6.png)

That's probably what 99.9% of all users really want to to. But if you press enter too quickly, before the installation completes, you will abort the operation in progress (actually, there's a popup asking for confirmation, but that's not a feasible option for us).

**Comment by mast-eu** [comment]
Format is another example:
![image](https://user-images.githubusercontent.com/46861028/69437323-62379080-0d43-11ea-8626-1e6ff94acd00.png)

**Comment by m417z** [comment]
@mast-eu your examples are solid, and it might be the case that guidelines-wise the dialog does the right thing. But the fact is that the issue exists, at least for me. The difference between your examples and the case of this issue is that your examples are isolated. For this issue, there are two similar types of flows:
* Action -> configuration -> progress. For example the "push" action. With keyboard it would be Enter -> Enter -> wait.
* Action -> progress. For example the "fetch all" action. With keyboard it would be merely Enter -> wait.

If I move fast to get things done, I can use my keyboard mechanically without thinking, and if I expect flow number 1 and get flow number 2, I end up aborting the operation.

Of course, it's not too bad. I just launch it again, now less mechanically. But you can imagine that it's not convenient.

I created this issue to make my usage more convenient, and to improve the product for me and other users, since I doubt that I'm the only one to encounter this. But as I already said, in the end it's your decision.

**Comment by RussKie** [comment]
@mstv what do you think needs fixing here?

**Comment by mstv** [comment]
I am surprised that on my machines, the `Abort` button is only focused for a very short time. Then the console seems to catch the focus. This looks different in @m417z's recordings. Strange!
So I have never mistakenly cancelled a git command yet. But I must click `Abort` using the mouse, e.g. if I want to cancel the slow `fetch all`.
(BTW: Why can't `fetch all` be done in parallel for all the remotes? Git issue.)
I agree it's kind of a progress dialog.
I still think `Esc` should cancel the git command and progress dialogs in general. And I am not very happy that `Enter` should/does activate the `Abort` button. That's my point of view as a user -- I am no GUI design expert. I understand the stance that the single enabled button shall be activated by `Enter`. Regarding this rule, the current implementation seems to be correct (excluding the focus issues caused by ConEmu, which we cannot really influence).

**Comment by RussKie** [comment]
@mstv your issues seems to be ConEmu related, which is a separate kettle of fish.
