### ISSUE TITLE
[NBug] Приложение не найдено

### ISSUE THREAD

**Issue by ruslan528** [gitextensions/gitextensions#7436]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): Приложение не найдено
   в System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   в GitUI.CommitInfo.CommitInfoHeader.rtbRevisionHeader_LinkClicked(Object sender, LinkClickedEventArgs e)
   в System.Windows.Forms.RichTextBox.OnLinkClicked(LinkClickedEventArgs e)
   в System.Windows.Forms.RichTextBox.EnLinkMsgHandler(Message& m)
   в System.Windows.Forms.RichTextBox.WmReflectNotify(Message& m)
   в System.Windows.Forms.RichTextBox.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
when click in Commit tab on Author link

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.21.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.3752.0
- DPI 96dpi (no scaling)

**Comment by ruslan528** [comment]
Nice work)

**Comment by RussKie** [comment]
Clicking on a link should launch your system default email client. Do you
have one configured?

**Comment by ruslan528** [comment]
You are right, there is no one. But it better to show simple message "Check your default email app" instead of crush 😉

**Comment by pmiossec** [comment]
❤️ ❤️ ❤️ ❤️ **crush** ❤️ ❤️ ❤️ ❤️ is always preferable 🤣 
But indeed, a better message is always better than **crash**

**Comment by f-i-x-7** [comment]
The related PR was merged. I think that issue should be closed, shouldn't it?

**Comment by mstv** [comment]
Aye, thank you
