### ISSUE TITLE
Open remote in browser

### ISSUE THREAD

**Issue by kaesaecracker** [gitextensions/gitextensions#7439]
## Feature description

Most git web GUIs allow opening the remote URL (including .git) in the browser, you will be redirected to the actual repo page. I think there should be a context menu entry on a remote to open the URL in the default system browser.

![image](https://user-images.githubusercontent.com/7461823/69357772-f9d6a980-0c85-11ea-826e-40588c1b5fc0.png)

## Environment

- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4042.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
This can be achieved using [revision links](https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#git-extensions-revision-links). They will be added to the panel `Commit Info`, tab `Commit`.

BTW: The panel `Commit Info` can be docked left and right of the revision grid using the toolbar button:

![grafik](https://user-images.githubusercontent.com/36601201/69360338-a87ce900-0c8a-11ea-9b47-8162bf407a6d.png)

**Comment by RussKie** [comment]
I think this is a legit request.
With the usual disclaimer though.

**Comment by RussKie** [comment]
Relates to #6180

**Comment by kaesaecracker** [comment]
If none of the usual developers wants to implement these changes I can try my best to do it - I would love to support this project with some of my time as I use it on a daily basis. I am not sure when I would get around to doing it though.

**Comment by RussKie** [comment]
Awesome!

**Comment by wynnfrei** [comment]
@kaesaecracker 
@RussKie 

Hello both of you. i have just finished working on this Issue and would like to know what else do i have to do in order to have this request merged? Thanks!

**Comment by pmiossec** [comment]
If I'm not wrong, you didn't opened a pull request.

I think that is what you should do so that everyone could do a review...

**Comment by RussKie** [comment]
> what else do i have to do in order to have this request merged?

please raise a pull request and we'll go from there

> i'm stuck with icon.. is there someone who is capable of making icons? or can i research over the internet and add by myself?

We use icons from [Yusuke Kamiyamane](http://p.yusukekamiyamane.com/)

Thanks

**Comment by wynnfrei** [comment]
@RussKie 
alrighty, will add an icon and raise a pull request.
