### ISSUE TITLE
[NBug] Der Objektverweis wurde nicht auf eine Objektinstanz festge...

### ISSUE THREAD

**Issue by ViegaKia** [gitextensions/gitextensions#7440]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

After creating a branch I switched back to a different one. Realising I forgot to push it, I switched back to the newly created branch and tried to press the push button and got the application.

## Expected behaviour

Pressing the Push button should not cause an exception regardless of the branch.

## Steps to reproduce

1. Be on master branch
2. Create a branch called "oldmaster"
3. Switch to "oldmaster"
4. Switch back to "master"
5. Switch back to "oldmaster"
6. Press the push button in the top menu bar.

## Error Details
```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei GitHub3.GitHub3Plugin.GetHostedRemotesForModule()
   bei GitHub3.GitHub3Plugin.GitModuleIsRelevantToMe()
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   bei GitUI.CommandsDialogs.FormPush.FormPushLoad(Object sender, EventArgs e)
   bei System.EventHandler.Invoke(Object sender, EventArgs e)
   bei System.Windows.Forms.Form.OnLoad(EventArgs e)
   bei GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Tried to press the push button.

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4018.0
- DPI 120dpi (125% scaling)

**Comment by pmiossec** [comment]
Should be fixed in development branch.
Could you test it and report if it's the case?

**Comment by gerhardol** [comment]
Duplicate of #7193
