### ISSUE TITLE
Using git extensions opens a new settings window each time

### ISSUE THREAD

**Issue by oskaremil** [gitextensions/gitextensions#7459]
Using GitExtensions 3.1.0.5602 with Visual Studio 2019 (version 16.3.10)

Every time I launch a command, either through Extensions -> GitExt or an assigned hotkey, the settings window opens in addition to the window I want to open.

Example: I press the shortcut to change branch. First the settings window opens, when i close the settings window the Checkout branch window opens

**Comment by RussKie** [comment]
The settings dialog opens because the settings file is likely missing or because you have some settings that require configuration.
Screenshots would be helpful in triaging the issue.

Also 3.1 is out-dated.

**Comment by oskaremil** [comment]
3.1 is the extension version available on https://marketplace.visualstudio.com/items?itemName=HenkWesthuis.GitExtensions

My Git Extensions version is 3.2.1.

You may close this issue. I did not know that required configuration triggered the popup. 

I solved my problem my configuring the merge and diff tools setting.

**Comment by RussKie** [comment]
The VSIX isn't changing often so we're not updating it.
