### ISSUE TITLE
Commit dialog add switch for double click to stage file directly

### ISSUE THREAD

**Issue by kenmux** [gitextensions/gitextensions#7465]
## Feature description
Can there be a switch for double click to stage file directly?

Of course, it is very convenient in most cases. But sometimes I double click an unstaged file by mistake, and it is added to stage area directly. It is very annoying for some untidy workspaces.

## Environment

- GitExtensions version: 3.2.1.6628
- GIT version: 2.24.0.windows.2
- OS version: Windows 7
- .NET version: 4.7.3416.0

**Comment by RussKie** [comment]
I am afraid we won't be quirking this behaviour.
