### ISSUE TITLE
Use commit message as patch filename whenever possible

### ISSUE THREAD

**Issue by Riajyuu** [gitextensions/gitextensions#7467]
## Feature description

Currently we I use the command `Format patch` under `Command` menu, the filename is always {patch number}.patch

I suggest to add an option, perhaps a checkbox in dialog of `Format patch` saying "Use commit message as filename".

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
The trouble with this request is that a commit message can be an arbitrary
length and contain characters invalid for a file name.
So this doesn't look like a good change...

**Comment by Riajyuu** [comment]
> an arbitrary length

Windows allows at most 200 length so I don't think this can be a trouble.

> contain characters invalid for a file name

Yes, this is true. But you know what they are, simply trim them away: 

![image](https://user-images.githubusercontent.com/16912240/69844017-2b410d80-1262-11ea-8655-9331f01ab33d.png)

**Comment by RussKie** [comment]
> > an arbitrary length
> 
> Windows allows at most 200 length so I don't think this can be a trouble.

Windows supports paths up to 256 chars, however commit messages may span multiple lines and be longer than 256.

Creating rules to trim messages to arbitrary length or deciding what chars a valid or not and how to format a file name is outside the scope of the app.
