### ISSUE TITLE
Set minimum git version to 2.19  or later

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#7472]
## Feature description

With the move to .NET Core I propose we set the minimum git version to 2.19 or newer, and remove all older versions and their quirks.

Git 2.19 was release Sep 2018, .NET Core was released Sep/Dec 2019, so a user will likely need to have .NET Core runtime installed to run a new version of the app (we may or may not publish a self contained bundle).

The move will help providing simple solutions to #4869 and #7456.

**Comment by gerhardol** [comment]
I would prefer to keep an older minimum version, as well as having a self contained bundle.
Git may be distributed by IT departments and be several years old so they are "safe".

I still need to have ClearCase installed at work to motivate to be able to install programs myself (the ClearCase packaging requires that as well as the IT packaging of ClearCase was so old and buggy that we had install it ourselves).

We could set minimum to 2.15.0 (Nov 2017), but the maintenance for older versions are not that high (we have the recommended version to point out what we really support), the behavior for newer Git is relatively well known, so I am leaning on keeping 2.11 and the older quirks.

Also, while I prefer to purge unused functionality, we could see that users were using versions older than 2.11 and that our checks mostly worked.

However, the Git version check could be done more in-the-face of the users if the user version is not recommended or newer.

**Comment by RussKie** [comment]
> Git may be distributed by IT departments and be several years old so they are "safe".

By the time we release 4.0, git 2.19 will be "few years old". 
If a user is stuck on an old version of git, they can use an old version of Git Extensions.

It doesn't look like users are opting in to the telemetry, we have records for only 72 users in the past 90 days.
But based on the data we have - only 12% of users have git other than 2.2x:
![image](https://user-images.githubusercontent.com/4403806/69999961-ff00f600-15ad-11ea-9450-de04eb263cbb.png)

**Comment by RussKie** [comment]
Here's a telemetry for git versions for the past 30 days:
![image](https://user-images.githubusercontent.com/4403806/70002610-a719bd80-15b4-11ea-9c87-8b31f5c34b0c.png)

| Git Version | Records | Ratio |
| ---- | ---- | ---- |
| 2.24.0.windows.2 | 1432 | 21% |
| 2.24.0 | 97 | 1% |
| 2.23.0 | 3231 | 48% |
| 2.22.0 | 719 | 11% |
| 2.21.0 | 989 | 15% |
| 2.17.1.windows.2 | 35 | 1% |
| 2.16.1.windows.4 | 121 | 2% |
| 2.10.1 | 59 | 1% |

**Comment by RussKie** [comment]
Tinkered a bit more, and got data for the past 90 days:


gitVersion | perc | gitCount |
-- | --: | --: | 
| 2.24.0.windows.2 | 6.99% | 1,441 |  
| 2.24.0 | 0.47% | 97 |
| 2.23.0 | 70.39% | 14,516 |
| 2.22.0 | 6.86% | 1,414 |
| 2.21.0 | 12.92% | 2,664 |
| 2.20.1 | 0.16% | 32 |  
| 2.19.1 | 0.06% | 12 |  
| 2.18.0 | 0.21% | 44 |  
| 2.17.1.windows.2 | 0.4% | 83 |  
| 2.16.1.windows.4 | 0.97% | 200 |  
| 2.14.1 | 0.27% | 56 |  
| 2.10.1 | 0.29% | 59 |  
|   | 0.02% | 4

Total records: 20,621

**Comment by gerhardol** [comment]
Still no major problem support down to 2.11

> By the time we release 4.0, git 2.19 will be "few years old".

Really do not hope that 4.0 will be so much delayed, if the schedule is in years rather than months it will be too late for users.

**Comment by RussKie** [comment]
v4.0 is likely be released Mar-May '20, by then git 2.19 will be 1.5 years old. A good runway for any sensible IT department to update.
As per out telemetry we don't have less then 1% of users using git older than 2.20 (excluding 2.16, which is me).
So I think it will be a sensible move.

**Comment by gerhardol** [comment]
I will not try to block a PR, just not endorse it.

**Comment by RussKie** [comment]
Duly noted. Thank you

**Comment by RussKie** [comment]
Latest stats:
![image](https://user-images.githubusercontent.com/4403806/85225516-4d27fa80-b415-11ea-8427-82f1b50217ec.png)

**Comment by gerhardol** [comment]
What is the total < 2.19? 
So just setting min to 2.19 or ripping out the supporting code too?

**Comment by RussKie** [comment]
There's less than 2-3% of all reported git clients under v2.19.

**Comment by RussKie** [comment]
Is there a reason to keep old code?

**Comment by gerhardol** [comment]
> Is there a reason to keep old code?

It is not a big burden to keep compatibility.
Setting supported version is one thing (2.19 is OK by now), removing code is just something I feel hesitant about
