### ISSUE TITLE
Option to use a custom gitignore template

### ISSUE THREAD

**Issue by ideaalab** [gitextensions/gitextensions#7487]
Every time we create a new repo, we have to place a .gitignore to it. We have a default .gitignore file in a handy place to copy to every of our repos. Its not hard of painful to do, but could be improved.

Our suggestion would be, in the "Repository > Edit .gitignore" menu, to have 2 buttons:

- **Edit custom template**: This button would popup a text edit window where you can add all your prefered ignores.
- **Append custom template**: this would add the previous ignores to the current (or create a new) .gitignore. The same as the button "Add default ignores", but with your custom ones.

This could be improved even more, if you can have more than one template. Like, one for your C programming, other for the design files, etc... and you can choose your template easily, without having to write it, or looking for it in other place.

With a single template would be just fine, and more than one would be awesome :)

Thanks for reading our suggestion!

**Comment by gerhardol** [comment]
I am not convinced this is a feature that really will be used
Few users create repos at all. If they do, other settings like .gitattributes GitExtensions.settings, readme template etc is needed too, making the setup more complex.
Also, you would need some way to distribute the templates.
This is easier to achieve with custom scripts.

**Comment by pmiossec** [comment]
Indeed, that seems too specific and complex to be reused by someone else. 
Perhaps we could implement the 'template directory' git feature. For more details, see: https://git-scm.com/docs/git-init

**Comment by RussKie** [comment]
Agree with @gerhardol, the request looks very niche.
I'm not opposed to a discovery whether our "OnXxx" events can be expanded to include "OnInit" event to allow hooking up custom scripts.

**Comment by ideaalab** [comment]
And what about the ability to edit the default ignores that are added by the button "Add default ignores"?
Simply placing those default ignores in a file, so if user want to change them, program reads from there instead of having them hardcoded.

**Comment by RussKie** [comment]
> And what about the ability to edit the default ignores that are added by the button "Add default ignores"?

I think that may be a good change - remove our own "default" set, as different types of users may prefer different defaults (here's a good collection https://github.com/github/gitignore)

**Comment by ideaalab** [comment]
We would love to contribute for this feature, but we are embedded programmers. Dont even know where to start from :(

**Comment by pmiossec** [comment]
>We would love to contribute for this feature, but we are embedded programmers. Dont even know where to start from :(

It depends what we exactly want to do. We have to discuss about it. Tell us what you imagine would be great...

First if that's a new form or if updating the [FormGitIgnore](https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/FormGitIgnore.cs) is enough (the one accessible through menu `Repository -> Edit .gitignore`). And if it's configurable from the settings. Maybe [GitConfigAdvancedSettingsPage](https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.cs)

**Comment by RussKie** [comment]
☝️ what @pmiossec said - let's talk through the design first and agree on what and how we want the feature to work.

> but we are embedded programmers. Dont even know where to start from :(

You guys are hardcore 🙇, writing C# should be a child play for you 😄 
Until we move to .NET Core (which is coming) you need to have Visual Studio installed (2019 community is fine). Once we migrate one could work in VSCode or cli.
Then clone (including submodules), open in VS and <kbd>F5</kbd>.

**Comment by ideaalab** [comment]
Hehe. Ok, yes... i know what has to be done, but not how. We do have VS, but should install C#. Then just create an external file with the default ignores, and change the button action from read from a ¿constant value? to do it from the previously created file.
How? .... Sure we would find the way, it will work, but the style will not be right, the procedures will not be standard...
We are cloning the repo and see...

**Comment by ideaalab** [comment]
Ok... found it... looks like its already implemented?

```c#
private static readonly string DefaultIgnorePatternsFile = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "GitExtensions/DefaultIgnorePatterns.txt");

private void AddDefaultClick(object sender, EventArgs e)
{
	var defaultIgnorePatterns = File.Exists(DefaultIgnorePatternsFile) ? File.ReadAllLines(DefaultIgnorePatternsFile) : DefaultIgnorePatterns;

	var currentFileContent = _NO_TRANSLATE_GitIgnoreEdit.GetText();
	var patternsToAdd = defaultIgnorePatterns
		.Except(currentFileContent.Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries))
		.ToArray();
	if (patternsToAdd.Length == 0)
	{
		return;
	}

	// workaround to prevent GitIgnoreFileLoaded event handling (it causes wrong _originalGitIgnoreFileContent update)
	// TODO: implement in FileViewer separate events for loading text from file and for setting text directly via ViewText
	_NO_TRANSLATE_GitIgnoreEdit.TextLoaded -= GitIgnoreFileLoaded;
	ThreadHelper.JoinableTaskFactory.RunAsync(
		() => _NO_TRANSLATE_GitIgnoreEdit.ViewTextAsync(
			ExcludeFile,
			currentFileContent + Environment.NewLine +
			string.Join(Environment.NewLine, patternsToAdd) + Environment.NewLine + string.Empty));
	_NO_TRANSLATE_GitIgnoreEdit.TextLoaded += GitIgnoreFileLoaded;
}
```

In such big projects i get lost very easily... but this looks like implemented to me. Will test...

**Comment by ideaalab** [comment]
Ok... it works!
Just add this file with your own ignores:
X:\Users\\_username_\AppData\Roaming\GitExtensions\\**DefaultIgnorePatterns.txt**

**Comment by RussKie** [comment]
Haha, we have so many feature even the team doesn't know about all of them.

Great to hear you got it all sorted!

**Comment by ideaalab** [comment]
Maybe now it would be nice to have some text explaining this feature in the edit window. Or some link text to generate this file and open it?

**Comment by ideaalab** [comment]
now we know the feature is there, at least others can use it :)

**Comment by RussKie** [comment]
Docs could do with an update, they are located here: https://github.com/gitextensions/GitExtensionsDoc

I have no idea how they are organised though... @gerhardol are you able to help?

**Comment by srce-code** [comment]
So to use this, we will need to install GitHub Desktop, then GitHub Extensions, and then create/edit the mentioned file?

Will it still call the new gitignore template set when creating a new repo in GitHub (in the dropdown under "Add .gitignore")? Seems unlikely? This would actually be my preference -- though setting it as the global default when using `git init` would be nice too. It seems like this is designed to only work with GitHub Extensions, right? If so, I will ask to reopen the feature request on GitHub repo as well.

**Comment by vbjay** [comment]
See https://www.toptal.com/developers/gitignore
