### ISSUE TITLE
UI thread freezed by BuildServerWatcher

### ISSUE THREAD

**Issue by NikolayXHD** [gitextensions/gitextensions#7488]
## Steps to reproduce

1. Open gitextensions repository
2. Open Settings dialog
3. Close Settings dialog

UI freezes

## Diagnostics

https://github.com/gitextensions/gitextensions/blob/3fcb4788b42d9b485880eb756e4bdc0af47d321b/GitUI/BuildServerIntegration/BuildServerWatcher.cs#L99

Thread.Sleep() for 120 seconds is called on UI thread

introduced in https://github.com/gitextensions/gitextensions/pull/7452

**Comment by pmiossec** [comment]
I'm sorry for that. Fixed in #7485

**Comment by pmiossec** [comment]
If I can ask you to test my fix and report that it is working. So that it could be merged quickly...

**Comment by NikolayXHD** [comment]
duplicates https://github.com/gitextensions/gitextensions/pull/7485

**Comment by NikolayXHD** [comment]
> If I can ask you to test my fix and report that it is working. So that it could be merged quickly...
ыгку
