### ISSUE TITLE
[NBug] System.NullReferenceException on Push button press.

### ISSUE THREAD

**Issue by Stridemann** [gitextensions/gitextensions#7494]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Steps to reproduce

Never had this issue before.
Did a rebase on master (no conflicts). On Push button press this error occures. Each time. Even on program restart.

Branches screenshot https://dl.dropboxusercontent.com/s/pal9v3b93778t6s/GitExtensions_2019-12-10_15-09-25.png  

## Error Details
```
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в GitHub3.GitHub3Plugin.GetHostedRemotesForModule()
   в GitHub3.GitHub3Plugin.GitModuleIsRelevantToMe()
   в System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   в GitUI.CommandsDialogs.FormPush.FormPushLoad(Object sender, EventArgs e)
   в System.EventHandler.Invoke(Object sender, EventArgs e)
   в System.Windows.Forms.Form.OnLoad(EventArgs e)
   в GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   в System.Windows.Forms.Form.

**Comment by Stridemann** [comment]
Added lost description.

**Comment by pmiossec** [comment]
Thanks for reporting the issue.

It seems to be a duplicate of #7193
Corrected in master, please try the portable build to verify the correction and please report the result.
