### ISSUE TITLE
Unable to work with GIT repositories in WSL2 folder

### ISSUE THREAD

**Issue by miloshavlicek** [gitextensions/gitextensions#7510]
## Current behaviour

- When I try to clone repository to Destination: \\wsl$\Ubuntu\home\havlicek and confirm the dialog with Clone button, an error pops up: "Exception: Invalid URI: The hostname could not be parsed."
- When I try to open an existing repository in the same destination (\\wsl$\Ubuntu\home\havlicek\repo), then also another error pops up: "The selected directory is not a valid git repository." (however, the valid repo is placed there.

## Expected behaviour

- Projects inside \\wsl$\ directories should work same as other projects on local drives (e.g. C:\)
- Projects inside \\wsl$\ dir should be opened as other projects on local drives.

## Steps to reproduce

- Enable WSL2 on your Windows 10 machine with Ubuntu installed.
- Open your Ubuntu home directory in Windows Explorer (with `explorer.exe .` command)
- Clone any repo to the dir via GitExtensions.
- The error will pop up.

## Screenshots

![image](https://user-images.githubusercontent.com/2387790/70756120-fd68c800-1d3b-11ea-9a18-d1fb04415e14.png)

![image](https://user-images.githubusercontent.com/2387790/70756555-2dfd3180-1d3d-11ea-9ff1-99a160512e73.png)

## Did this work in previous version of GitExtensions

No.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.0.windows.2
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4084.0
- DPI 120dpi (125% scaling)

**Comment by pmiossec** [comment]
Hmmmm....  #7438 and #4307?
