### ISSUE TITLE
Scroll for telemetry

### ISSUE THREAD

**Issue by AcellaEDU** [gitextensions/gitextensions#7514]
**Git Extension 3.2.1.6628**
I can't to see a telemetry options.
Screen resolutions: 1366x768 (notebook)

![image](https://user-images.githubusercontent.com/6829626/70848274-01056780-1e80-11ea-80c8-da3bc6be922b.png)

**Comment by AcellaEDU** [comment]
It's actual for:
- **Git Extensions 3.3.0.7719**
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.0.windows.2
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Sorry, we haven't adapted this yet: #7387. As a workaround, you could reduce the size of the application font:

![grafik](https://user-images.githubusercontent.com/36601201/70848699-ac5cef00-1e75-11ea-9abf-0416a8106ca1.png)
