### ISSUE TITLE
[NBug] Version string portion was too short or too long.

### ISSUE THREAD

**Issue by jorobhall** [gitextensions/gitextensions#7521]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Version string portion was too short or too long.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at Gerrit.FormGerritBase.OnLoad(EventArgs e)
   at Gerrit.FormGerritPublish.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Trying to publish to Gerrit

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Gerrit plugin was changed in #7200 (at least), including OnLoad()
I do not see an obvious issue

What Gerrit version?
What was done when the problem occurred?

**Comment by tkingsbury42** [comment]
Just a note that I have seen this as well. It was working properly in Git Extensions 3.2.1.6628. In my situation, this error occurs when I press "Publish Gerrit Change".  My Gerrit server version is 2.14.6
My problem is consistently reproducible. I ended up downgrading to the earlier version and now things are working nicely again.

**Comment by gerhardol** [comment]
#7216 and #7198 are the only functional changes
A Gerrit user need to debug

**Comment by RussKie** [comment]
@lekhmanrus can you please investigate. Could your changes have caused this?

**Comment by lekhmanrus** [comment]
I'm using the latest version of Git Extensions and Gerrit server v3.1.0. It works as expected.
@tkingsbury42 could you provide some url for Gerrit server v2.14.6 to debug / reproduce that error please (if that is possible)?

**Comment by lekhmanrus** [comment]
Googled for some gerrit server v2.14.6 - found some and tested. It seems gerrit publish dialog opened and works as expected.

![gerrit](https://user-images.githubusercontent.com/2744696/71146245-29e57e00-222d-11ea-9bc4-a003050e7999.gif)

So, could you provide more info? Maybe url for gerrit server? Do you have only http access? could you share `.gitreview` file?

**Comment by tank09** [comment]
Hi,
I have the same problem, I debugged and it seems that the port used for the request is wrong.
It looks like the request goes via https to port 443, but e.g. our gerrit server has 8443 as https port.

I assume there must be a way to specify the port used in SetRestClientUrl. I'm not sure, but there is already a "port" config in .gitreview file, but I assume this is used for the git protocol.

Regards,
Andreas

**Comment by tkingsbury42** [comment]
Hey Ruslan,

Unfortunately, my Gerrit server is private, so you won't be able to test.
We appear to be connecting to Gerrit over SSH using port 29418.

ssh://user_name@server_name:29418/project1/project2

If it would be helpful, I can test for you with additional debug logging
turned on.

My .gitreview looks like this:
[gerrit]
host=my-server.domain.com
port=29418
project=project1/project2
defaultbranch=dev-1.2.3
defaultremote=origin
defaultrebase=0


Tim

**Comment by petrf22** [comment]
Hi

I have the same problem in version 3.3.0.7719. I'm temporarily downgrade to version 3.2.1.6628 to fix my problem.

Peter

**Comment by gerhardol** [comment]
@lekhmanrus @tkingsbury42 @petrf22 @tank09 @jorobhall 
Please review and test the proposed fix

**Comment by dfev77** [comment]
The issue is caused by the fact that GitEx tried to determine the Gerrit version, to be able to list the correct publish modes for that server (draft vs private+wip), but it does not have all the info available.
So it will make a request to the Gerrit server to ask for the version, but it does not have neither the protocol (http vs https) not the port (there a 2 ports Gerrit UI and git "repo" port), as these are not available to to git. And regardless of the success of this request it will try to parse the version it thinks it has. At least for default configuration on SSH exposed servers this will fail (Gerrit I
UI is on port 8080 and ssh is on 29418)
Initial attempt was to fix the connection which would require a set of new configuration values: port, protocol, etc.
Then realised that is much simpler and safer to just add a configuration for "Gerrit is 2.15 or lower".
Hope the proposal would be accepted, still some small adjustments needed (user friendly name and options for the configuration)

**Comment by hhao1** [comment]
I have the same problem.

**Comment by petrf22** [comment]
> Hi
> 
> I have the same problem in version 3.3.0.7719. I'm temporarily downgrade to version 3.2.1.6628 to fix my problem.
> 
> Peter

Today I'm upgrade to version 3.4.1.9675 with Gerrit Code Review plug-in and cooperation between Gerrit and GitExtensions works correctly.
Thank you very much for your excellent work.

**Comment by RussKie** [comment]
You're welcome 👍
