### ISSUE TITLE
[NBug] Illegal characters in path.

### ISSUE THREAD

**Issue by aaiidd** [gitextensions/gitextensions#7528]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

Cloning  a repo -> typing a pipe character in the Destination field crashes the app

## Expected behaviour

I'm, able to type whatever I want and the path gets validated as I type or after the field value is evaluated.
Crashing the app is not good

## Steps to reproduce

Open the app
Start -> Clone Repository
Place the cursor in the Destination field
Start typing and make sure to type an invalid character file for a folder/file, like a pipe ( | )

## Error Details
```
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at GitUI.CommandsDialogs.FormClone.ToTextUpdate(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnTextUpdate(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Cloning a repo, I typed a pipe ( | ) in the Destination field... BUM!

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The correction would just be to give a popup that must be dismissed instead of the NBug that can be dismissed, so no major difference...

**Comment by aaiidd** [comment]
Whatever popup should come up only one time once the field gets validated at the end of typing.
Making that validation along the way might be annoying for the user.
Whatever makes it work :-) 👍

**Comment by mycroes** [comment]
> The correction would just be to give a popup that must be dismissed instead of the NBug that can be dismissed, so no major difference...

There already is an error field on that dialog that is used to show messages about invalid data, it just seems this one exception isn't properly handled.
