### ISSUE TITLE
Error while submitting an Error Report

### ISSUE THREAD

**Issue by tkingsbury42** [gitextensions/gitextensions#7532]
I'm seeing a fatal exception  "Version string portion was too short or too long." when I attempt to push code. More importantly though, when I press the "Send and Quit" button to upload the error report, I land on a 503 error page for GitHub.

I figured out that this problem only happens if you are NOT logged into Github.
If your browser is already logged into GitHub, then the new issue page displays properly.

This occurs consistently in Git Extensions 3.3.

**Comment by gerhardol** [comment]
This is likely a change on the GitHub (server) side.
Someone need to report to GH.

**Comment by RussKie** [comment]
Thank you, we are aware of the issue. But there is little we can do here.
