### ISSUE TITLE
[NBug] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by matthew-monacelli** [gitextensions/gitextensions#7534]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
```

## Additional information
launch application and agree to update to latest version

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.19025.0
- .NET Framework 4.8.4070.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Firewall?
Can you debug or create a networklog?

**Comment by matthew-monacelli** [comment]
You guys closed my bug, good luck.



Matthew Monacelli
Software Engineer
Software Engineering Department

System Logistics Corp.
115 Vista Boulevard
Arden, NC 28704 - USA

Phone: +1 828-654-7500 ext.152
Mobile: +1 828-974-6993
matthew.monacelli@systemlogistics.com
www.systemlogistics.com

Please consider the environment before printing



________________________________


“Notice. This message (including any attachments) is intended only for the use of the individual or entity to which it is addressed and may contain information that is non-public, proprietary, privileged, confidential, and exempt from disclosure under applicable law or may constitute as attorney work product. If you are not the intended recipient of this message, you must not use, disseminate or copy it in any form or take any action in reliance of it. If you have received this communication in error, notify us immediately by telephone and (i) destroy this message if a facsimile or (ii) delete this message immediately if this is an electronic communication. Recipient is accountable for his/her system protection from unlawful interference. This email is not a private address; its use is subject to data controller's policy. Thank you”

**Comment by pmiossec** [comment]
>You guys closed my bug, good luck.

Don't take it personally! That's the "cleaning" bot that automatically close issues that are not well filled to prevent us to have to manage the burden of too much not very useful issue (and always have to ask for more information).

We tried to make the bot message as kid as we could. Probably you missed the bot message which explain the reason why the issue was closed and saying to you that we will pleased to reopen the issue if you provide the required information.

So, if you want the issue to be fixed, please help us...

**Comment by matthew-monacelli** [comment]
I was just informing you guys of the issue.  I had opened the GitExtensions application and was notified of an available update.  I agreed to update now and then the application crashed with the information I had initially given.  I just tried again and it was successful.  I am wondering if there was a problem with the download that was not handled, causing the crash?  Anyways, I was able to update successfully.  Thanks for the (human) clarification 😊



Matthew Monacelli
Software Engineer
Software Engineering Department

System Logistics Corp.
115 Vista Boulevard
Arden, NC 28704 - USA

Phone: +1 828-654-7500 ext.152
Mobile: +1 828-974-6993
matthew.monacelli@systemlogistics.com
www.systemlogistics.com

Please consider the environment before printing



________________________________


“Notice. This message (including any attachments) is intended only for the use of the individual or entity to which it is addressed and may contain information that is non-public, proprietary, privileged, confidential, and exempt from disclosure under applicable law or may constitute as attorney work product. If you are not the intended recipient of this message, you must not use, disseminate or copy it in any form or take any action in reliance of it. If you have received this communication in error, notify us immediately by telephone and (i) destroy this message if a facsimile or (ii) delete this message immediately if this is an electronic communication. Recipient is accountable for his/her system protection from unlawful interference. This email is not a private address; its use is subject to data controller's policy. Thank you”
