### ISSUE TITLE
Default shortcuts for Stash and StashPop

### ISSUE THREAD

**Issue by LukeOwlclaw** [gitextensions/gitextensions#7538]
## Question / Suggestion

Currently the default shortcuts for actions ``Stash`` and ``StashPop`` are defined like this:

    Hk(FormBrowse.Command.Stash, Keys.Control | Keys.Alt | Keys.Up),
    Hk(FormBrowse.Command.StashPop, Keys.Control | Keys.Alt | Keys.Down),

Git stash is a stack, right? I put something on top (stash), and take something away (pop).
Putting something on a stack means putting it DOWN, removing something means picking it UP.

The shortcuts are just inverted. I am wondering: What is the reason for that?

If there is no real reason, I suggest switching the default shortcuts, so that new users have more intuitive shortcuts. Most likely, existing users want to keep there original shortcuts, though...

## Environment

- Git Extensions 3.2.0
- Build ffc96a4212871d0b47763db17244d1d3fcd3539f
- Git 2.21.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by mast-eu** [comment]
I consider the current behaviour aligned with `CTRL+UP`, which opens the push dialog and `CTRL+DOWN`, which opens the pull dialog.
Likewise,  `CTRL+ALT+UP` will _push_ something onto the stash and `CTRL+ALT+DOWN` will _pull_ it back from stash.

**Comment by gerhardol** [comment]
I feel this is mostly about personal preferences, to change something that is established like these shortcuts, the general consensus have to be strong. 
Since I will fail in all new installations, I vote to not change.
