### ISSUE TITLE
gitex.cmd no longer opens the current repo

### ISSUE THREAD

**Issue by thomaslevesque** [gitextensions/gitextensions#7542]
## Current behaviour

When I run gitex.cmd from the command line in a Git repo directory, it opens the GitExtensions dashboard.

## Expected behaviour

Directly open the current repo in GitExtensions. This worked before (I was using 3.0.x), and stopped working when I upgraded to 3.3.0.7719.

## Steps to reproduce

Execute gitex.cmd from the command line in a Git repo directory.

## Screenshots

N/A

## Did this work in previous version of GitExtensions

Yes, 3.0.x

## Environment

- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 144dpi (150% scaling)

## Diagnostics

N/A

---

I don't know if it's a bug or if it's intentional, but I don't like the new behavior, because it requires me to manually find my repo in the dashboard (I have about 30 of them in recent repos). Is there a way to restore the previous behavior?

**Comment by pmiossec** [comment]
I don't remember if it's intentional neither but the command to open a repository that will always work is `gitex browse`.

**Comment by thomaslevesque** [comment]
Yes, I know... but it's longer to type. As a workaround, I configured a `git ex` inspired from [this](https://github.com/gitextensions/gitextensions/issues/6043#issuecomment-451760125).

**Comment by RussKie** [comment]
Do you have _Settings > General > Open last working directory at start up_ under _Behaviour_ group ticked?

**Comment by thomaslevesque** [comment]
> Do you have _Settings > General > Open last working directory at start up_ under _Behaviour_ group ticked?

No, but it doesn't do what I want. It reopens the last repo I had opened in GitExtensions. I want to open the repo in the current directory.

**Comment by patrickTingen** [comment]
I can second this changed behaviour. It started since last update. I checked the setting to see if there is a setting along the lines of "Open repo of current folder" or something like that. Now I have to select the repo I want to work with, witch may be different than the last working directory

- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3460.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
`gitex browse .` works for me.

**Comment by patrickTingen** [comment]
@mstv thanks, here as well

**Comment by gerhardol** [comment]
This was intentionally changed in #7147 

If no argument, obey the configuration

**Comment by thomaslevesque** [comment]
@gerhardol thanks. Could the previous behavior be reintroduced as an option? Something like "Open current directory on startup if it's a Git repository"?

**Comment by RussKie** [comment]
No, that makes no sense.

If you want to browse the current repo,  "browse" command must be supplied.
Running the app on its own, must just start the app.

Likewise if I run "PowerShell.exe" in a folder, I don't expect to execute
any scripts in the current folder. I have to specify them.

**Comment by thomaslevesque** [comment]
I guess it's a case of "[every change breaks someone's workflow](https://xkcd.com/1172/)"...

> No, that makes no sense.

I'd argue that it makes as much sense as "Open last working directory at start up". It was the previous behavior, and it was convenient to me, and probably many others.
I'm not asking to make it the default, just to add an option, like for "open last working dir".

**Comment by RussKie** [comment]
> I guess it's a case of "[every change breaks someone's workflow](https://xkcd.com/1172/)"...

Unfortunately it is the case. 
And one of the reason for this because we have too many settings and configurations. And a lot of these settings, seems, were added without sufficient thought how they fit together.
And this is the reason I'm against adding more settings, especially those that address very narrow use-cases.

However I think the problem lies with gitex.cmd - it must be updated with correct parameters. I suppose it is something you could do in the interim.

If you get it working, we'd appreciate it if you send a PR with a fix

**Comment by thomaslevesque** [comment]
> However I think the problem lies with gitex.cmd - it must be updated with correct parameters. I suppose it is something you could do in the interim.
> 
> If you get it working, we'd appreciate it if you send a PR with a fix

I'm not sure I understand what you're saying... Does that mean you'd be open to restoring the previous behavior if it was made in gitex.cmd rather than in GitExtensions itself?

**Comment by pmiossec** [comment]
I wonder if another solution could be to open in browse mode if only an
existing path is provided.

That would allow to use it with `gitex .`

**Comment by RussKie** [comment]
gitex.cmd is a convenience script to invoke the app from the current location.
So if the script is incorrectly invoking the app, it should be fixed.

**Comment by gerhardol** [comment]
> gitex.cmd is a convenience script to invoke the app from the current location.
So if the script is incorrectly invoking the app, it should be fixed.

Please review the proposed changed to gitex.cmd

> I wonder if another solution could be to open in browse mode if only an
existing path is provided.

That is another solution.
A third is to let just argument "browse" open the dashboard.
Both are giving convoluted rules though, but if they are well documented, they could be OK.

> I guess it's a case of "every change breaks someone's workflow"...

GE has evolved by users submitting changes, this is what have GE great. However, it almost impossible to differentiate between features and bugs. The change was a bug in my usage. But we do not need more configuration in GE...

**Comment by RussKie** [comment]
@thomaslevesque @patrickTingen  could you please modify your local gitex.cmd file as follows and confirm the issues is fixed:
https://raw.githubusercontent.com/gerhardol/gitextensions/bugfix/i7542-gitex-browse-3.3/Bin/gitex.cmd

**Comment by patrickTingen** [comment]
@RussKie works like a charm:

- In non-git folders, GE starts and asks which repo I want to open. 
- When run in a tracked folder, it opens the repo.

**Comment by thomaslevesque** [comment]
Works fine for me too!

**Comment by RussKie** [comment]
Thank you for checking.

**Comment by thomaslevesque** [comment]
Thanks for fixing!
