### ISSUE TITLE
ERROR wen PULLing!!!

### ISSUE THREAD

**Issue by axelmiami** [gitextensions/gitextensions#7543]
In all projects after update ERROR wen PULLing!!!
![image](https://user-images.githubusercontent.com/1639556/71255364-c77ca280-233e-11ea-80d1-3d462fa7959b.png)

**Comment by mstv** [comment]
Could you fill in our bug report template, please? Amongst others, Git version and git command log (`F12`) will help to analyze this issue.

**Comment by axelmiami** [comment]
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

![image](https://user-images.githubusercontent.com/1639556/71255924-63f37480-2340-11ea-9dd5-8d07e92844f1.png)

**Comment by axelmiami** [comment]
[GitExtensions-Error-Log.txt](https://github.com/gitextensions/gitextensions/files/3988341/GitExtensions-Error-Log.txt)

**Comment by RussKie** [comment]
I think it is the same as https://github.com/gitextensions/gitextensions/issues/6286#issuecomment-480273632
Please check you SSH configurations.

**Comment by axelmiami** [comment]
Yes!!!
After update SSH configuration chenged to putty... for some reason...
I returned to OpenSSH and al working!!!
Thanks!

**Comment by RussKie** [comment]
We have a bug in the installer where it doesn't retain the configured value. And by installing the app in a silent mode (e.g. through the auto-update) it reset the SSH to PuTTY.
😞

**Comment by RussKie** [comment]
Can I get you to verify a fix? This installer should retain the configured SSH
https://ci.appveyor.com/api/buildjobs/vgsecayjmjmhpn8h/artifacts/combined.3.3.0.7791-unsigned.zip

**Comment by axelmiami** [comment]
Hi!

After using file GitExtensions-3.3.0.7791.msi the OpenSSH settings not changes

Но наверное мы могли бы говорить и на русском J

 

ez,

Axel Miami

**Comment by RussKie** [comment]
We could, but that'd be inappropriate and disrespectful to other members of
the project.

You can always DM me on gitter, if you desire. ☺

**Comment by RussKie** [comment]
Thank you for checking btw
