### ISSUE TITLE
CommitInfo in history does not expand

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#7582]
## Current behaviour
In #7186 the branches and commits are presented in a better way in CommitInfo, with a ShowAll link to expand the default selection of 10 tags.
This works fine in the Commit tab/Panel in Browse. 
However, in FormFileHistory the list is not expanded.

## Expected behaviour

Tag/branch list be expanded in all CommitInfo.

## Steps to reproduce

Open history for a file existing in v3.00.00-beta1 (2019-09-17), as this tag exceeds the limit for ShowAll (or create tags/branches yourself).
Select Commit Tab
Select ShowAll tags
A refresh occurs (at first click), but info is not refreshed

## Screenshots

![image](https://user-images.githubusercontent.com/6248932/71616874-be01fe80-2bb8-11ea-9365-8d6fe32608a8.png)

## Did this work in previous version of GitExtensions

Different handling in 3.2

## Environment

- Git Extensions 3.3.0.7791
- Build 5d804cdfaf57fa122faf7811777140369826d11b
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
@mstv ?

**Comment by mstv** [comment]
Yes, yet another one for the pending refactoring of FormBrowse in order to reuse functionality in FormFileHistory.
Perhaps this issue is a good first step.
