### ISSUE TITLE
Unit test "`Default_values_are_specified_in_invariant_theme` fails, if path to repository contains a hash sign "#"

### ISSUE THREAD

**Issue by c3er** [gitextensions/gitextensions#7587]
## Current behaviour

The unit test `Default_values_are_specified_in_invariant_theme` fails as only test, if the path to the local GitExtensions repository contains a hash sign.

My case:

```
D:\eigene dateien\devel\bsp\c#\gitextensions
```

## Expected behaviour

All unit tests, including the mentioned one shall be agnostic about all allowed characters in the path to the local repository.

## Steps to reproduce

1) Clone the GitExtensions repository to any path that contains a hash sign "#"
2) Execute unit test `GitUITests.Theming` -> `AppColorDefaultsTests` -> `Default_values_are_specified_in_invariant_theme`
3) Test runs red

## Screenshots

![grafik](https://user-images.githubusercontent.com/24460532/71636880-40310800-2c37-11ea-8029-1892040ac8c3.png)

## Did this work in previous version of GitExtensions

Unknown

## Environment

- GitExtensions version: Developer build, commit 86d233a1a9aaf3a0511bad315781c58569e5d2e1
- GIT version: 2.24.1.windows.2
- OS version: Windows 10, version 1909
- .NET version: Framework 4.6.1

**Comment by gerhardol** [comment]
https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Settings/AppSettings.cs#L1656

https://docs.microsoft.com/en-us/dotnet/api/system.uri.localpath?view=netframework-4.8

Uri.LocalPath truncates the path
The same method is used in several other situations, expect other issues with # in the path

**Comment by c3er** [comment]
@gerhardol Indeed, I got an error message "Failed to read theme" at starting the debug instance.

**Comment by c3er** [comment]
@gerhardol Couldn't this issue be closed? My fixing PR #7591 was merged into master long ago.

**Comment by gerhardol** [comment]
The PR did not have the "Fixes #7591" line that would have closed this automatically, closing manually

**Comment by c3er** [comment]
I understand
