### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by jvitkauskas** [gitextensions/gitextensions#7594]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Git.hub.Repository.GetBranches()
   at GitHub3.GitHubRepo.GetBranches()
   at GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass22_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
I've just opened a Github -> Create pull requests menu item and it crashed immediately after opening "Create Pull Request" window

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
(Real) duplicate of #6757.

You must not have generated your github token (or maybe it is not valid anymore)

We added a protection in #6814 but it seems to be not enough 😢 
And I don't reproduce 😭

**Comment by SveinJarleReiakvam** [comment]
I found out that I have got the github token for the wrong github account. When I delete the github token, and logon with the right account I got a new github token and this error did not appear anymore. :)

**Comment by pmiossec** [comment]
Thanks a lot @SveinJarleReiakvam to head me on the real problem.
I have created an issue to have a good description:  #7641
