### ISSUE TITLE
Slow to switch repos after console is initialized

### ISSUE THREAD

**Issue by asherber** [gitextensions/gitextensions#7595]
## Current behaviour

When switching repos using the MRU dropdown in the repo browser, it takes much longer for the operation to complete if the console tab has been initialized

## Expected behaviour

Time should be about the same

## Steps to reproduce

- Open GE in a repo
- Use dropdown to switch repos; takes 3-4 seconds (on my system) for repo browser to refresh
- Click on Console tab to init console
- Use dropdown to switch repos; takes ~12 seconds for repo browser to refresh

For most of the time, the browse window just sits there, no change. After ~6 sec, the cursor changes to a wait cursor. A couple of seconds later, the console gets the cd command. After that, the repo browser gets the spinning wait indicator and then the browser refreshes. So it almost seems like there's something very time-consuming going on calculating the cd command.

This happens once the console tab has been initialized, even if it's not the active tab when I switch repos. 

I almost always have the console tab open, so I just thought that GE was slow to change repos. Today I happened to open GE and switch to a couple of different repos before opening the console tab, and I noticed how much faster it was.

## Did this work in previous version of GitExtensions

Not sure, but probably not. 

## Environment

- Build bc22d9bd138ac0166652d64ac8ece34a05cbb7ad
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Please tell us which console do you use (bash, cmd, powershell ).

I have a temporary fix in my repository for 'cmd' but I need more time to create the PR and see if the behavior is the same for powershell and bash.

It's not the 'cd' which is long but the clearing of the command line (even if nothing was entered 😕)

**Comment by asherber** [comment]
I use bash
