### ISSUE TITLE
Redesign of FormFileHistory

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7598]
## Current behaviour

FormFileHistory has several redundant controls. The layout does not use the available space well.
Many functions of FormBrowse which could be applied, are not provided to the user (refer to #6483).

## Expected behaviour

```
FormFileHistory
  = FormBrowse
    - LeftPanel
    - left part of toolbar and menu
    - tab "Console"
    + tab "Blame"
```
* single `CommitInfo` independent from tab "Commit" (`CommitDiff`) and tab "Blame" (`BlameControl`)
  placed by user left or right of the `RevisionGridControl` or -- if really used -- below as tab "Commit"
* tab "Diff" with `RevisionDiffControl` instead of plain `FileViewer`
* no tab "View" (`FileViewer`) because it is the same as on tab "Blame"

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/71786099-35e08680-3008-11ea-8f41-50ccabc41a6f.png)
![grafik](https://user-images.githubusercontent.com/36601201/71786161-efd7f280-3008-11ea-996f-6fcb15c7d3a8.png)
![grafik](https://user-images.githubusercontent.com/36601201/71786212-33326100-3009-11ea-8240-2137a1f60d9a.png)
![grafik](https://user-images.githubusercontent.com/36601201/71786375-15fe9200-300b-11ea-9a8a-16706d8e3f1e.png)

## Environment

- GitExtensions version: 3.3.1

**Comment by gerhardol** [comment]
CommitInfo: That is very useful to find other files changed in that commit (I occasionally need to get related commits in e.g. for merges in Browse though).

View: Not strictly needed, but blame is a little sluggish (diff could be used too, view complete file). But this is not important for me.
A reason to keep is though that that the FileHistory vs Blame (H/B) expects a View - affects other shortcuts.

Diff: Do you propose to remove that?
Also with the CommitInfo, it is simpler to see files (more important than View).

Regarding #6483 a Blame tab (or Diff with a separate Blame viewer) could be added to Browse, but then the revision grid need to be filtered to the current file too, which will be a little strange.

**Comment by mstv** [comment]
At least from the user's perspective, I really think of a reused FormBrowse just with filtered revisions.
(Red highlighted menu items and toolbar to be hidden/removed)

![grafik](https://user-images.githubusercontent.com/36601201/71848148-08124500-30cf-11ea-89ba-9ebceff9aecc.png)

![grafik](https://user-images.githubusercontent.com/36601201/71848604-37758180-30d0-11ea-9a5e-5864accb803e.png)

IMO we do not need `FileViewer`s over the full screen width anymore. 
`B` opens "Blame"; `H` opens the new tab "Diff" with automatical selection of the file in the `FileStatusList`.
The tab "View" was the same as the right side of "Blame" and can be removed.

It wasn't my intention to show the tab "Blame" in the real FormBrowse.

**Comment by gerhardol** [comment]
> At least from the user's perspective, I really think of a reused FormBrowse just with filtered revisions.

Maybe doable, I am not convinced yet.
#7394 is not over yet it seems, but I assume you want something to do when it does?
(OT: Great job there, I get tired just by reading the updates.)

> It wasn't my intention to show the tab "Blame" in the real FormBrowse.

I do not see the relation of the file -> Blame here. It is visible in the window title. Something else?
Is Diff for all files in the selected commit or the file to show history for?
Maybe View Blame replacing FileViewer, in Diff and FileTree, so not a separate tab?

Maybe split this in two parts:
* Mark commits in Revision graph for those including a certain file, also to only show those commits (as in current file history)
* Blame handling in Browse (this is most the useful part to me).

B/H shortcuts can set these 'modes' eventually, when the sub parts are implemented.

**Comment by mstv** [comment]
I think of `FormFileHistory` to inherit from a stripped down `FormBrowse`:
![grafik](https://user-images.githubusercontent.com/36601201/72111503-44e27400-333b-11ea-8bf3-a4db207ad544.png)

**Comment by gerhardol** [comment]
I see this as an iterative change, to be done step by step. If all functionality is available in Browse, FormFileHistory can be removed. But I expect that to take some time, this is not on my prio list right now. So I still want to add custom difftool in History...

>     * Blame handling in Browse (this is most the useful part to me).

A Blame tab in Browse should be the most obvious change, regardless of other changes.
How to add the blame specific options, context menu or toolbar?
(Currently a split button)

The next step in my view is to add a filter in the revision grid for a single file. Searchbox similar to Find File. So fun to make git-log even more complicated!
Remaining options like CommitInfo later.

I do not see Blame as the replacement of View tab as it is too slow, but Diff is sufficient.

**Comment by pavlexander** [comment]
Hello there

Since the topic of UI redesign has been brought up, I wish to put my 2 cents on it and let community decide if cents are worth attention or not :) It's related to another feature request I have raised here: https://github.com/gitextensions/gitextensions/issues/8916

In my proposal I have asked for a "patch-view" functionality to be added to existing "File/Folder History" window. It might come in handy, if you want to only view changes associated with the folder (or the files inside the folder) and don't care about other commit details (files outside the scope of the folder).

The functionality that I have requested is already present in `gitk` tool (which I am already using successfully as a workaround for now). If you want to see/check how it works please look into the original ticket that I have referenced. It has some screenshots and additional details.

The change could be implemented as radio elements:

1. default view
2. patch-view

Or even as a single checkbox, or a dropdown. Dropdown if we plan on having more options in the futute?

And since we have CLI at our disposal, it would be nice if we had a flag that we could pass as an argument to have the window opened with correct view out-of-the-box. I like the concept of clicking less, having more :) The functionality, of course, could be faked by using regular expressions in the file view.. but it's just not as convenient as having the predefined options. Anyways these were my 2 cents. 

**p.s.:** on a second though, another solution to the problem would be to have a predefined/fixated regex expression on top of the dropdown that user could select? (which changes, depending on which file/folder you have selected).

![image](https://user-images.githubusercontent.com/20644772/110135482-4096d700-7dd7-11eb-97b7-f0d1bb1d7f46.png)

That would be the simplest option, easiest to implement. I like the idea with the checkbox/radio more, though.

Thanks for reading. 🥇

**Comment by ivangrek** [comment]
#8706

**Comment by gerhardol** [comment]
@pavlexander 
I see no difference between the gitk patch view and GE diff tab. 
The way I see it what you want is to filter the output in Browse, like what you get when starting gitk from the command line.
This could be implemented with a filter similar to the filters in the current menu.
If this is incorrect, please clarify.

Your use case adds the folder selection, not just files.
To use a dialog similar to find file in filetree would not be optimal (you could of course edit the file path).

**Comment by gerhardol** [comment]
Some thoughts how to handle this:

* Blame in FormBrowse, several alternatives. the `B` hotkey should in these scenarios show the file (and let `H` open FileHistory).
  - Toggle view in file viewer toolbar, similar to show complete file in diff. In this case the toolbar is in the file viewer, not sure if this is simple to do.
  - Replace file viewer in FileTree (as mstv suggested). I find this much too slow though. Maybe use Blame form and avoid loading blame sidebar is controllable? Then Blame is always available in any fileviewer (for items with revision information).
  - Tab similar to `File tree` (not visible for artificial commits). Display the latest selected file in `Diff` or `File tree`. This would give a good visibility to the fiunctionality, but a little inconvenient to handle. Would fit me the best I believe.
* Hotkey and menu option for Diff/Tree to replace path in advanced filter. (How to handle renamed files?)
* Easier access to RevGrid advanced filter. A suggestion is a button in the toolbar
  - Easy activate/deactivate.
  - See that it is active, tooltip to see current filter
  - This could also be used to simplify limit load of commits, to speed up. It is not often I am interested in seeing commits older than 6 months or so.
  - Filepicker in advanced filer too? (Keep text editing).
  - Maybe add file picker in toolbar too?
  - Migrate options in toolbar to advanced filter 

Related: With `--grep` or path filter in FileHistory (need separation to files) the grid is not displayed. Maybe a limitation in the rev graph.

**Comment by gerhardol** [comment]
Most of what I planned is in branch feature/filter-file-diff-parent
#9393 and #9413 need to be merged and at least one more base PR is needed before the "GUI" changes are submitted to a PR.
I do plan to add something to visualize the Advanced filter as well as to deactivate it in a simpler way.
A `F` shortcut as seen below should likely be added to FileTree too, regardless of the implementation.

There are some open questions with how to handle this though:

* Is a simple "View" mode for FileTree needed?
This could be configured with a context menu command in the file viewer if needed.

*  Browse could replace FileHistory completely, or they are kept in parallel. Should this be configurable right now so `H` opens either or?
(I do not plan to remove the FileHistory implementation yet.)

* If FileHistory is kept as the main alternative, should `B` open FileTree with Blame enabled?
The  hotkey `T` is then not needed.

* In FileHistory, the Commit related to the current selected line is shown in a header. That information is available in the tooltip and CommitInfo if the commit is selected. Should this be removed?
The current implementation hides that (a narrow border exists though. some Git commands too.

![image](https://user-images.githubusercontent.com/6248932/126910174-70212f74-3d03-4c19-b408-1624adb4aa86.png)

**Comment by RussKie** [comment]
I started refactoring and cleaning up the code that comprises the Filters
toolbar. I've already mostly cleaned up the FormBrowse, factored out and
removed the revision filter helper. The branch filter helper is next.
After that the same clean will be made to the FormFileHistory.

I wouldn't want you to spend time and make changes that ultimately will be
removed.

You can see the refactor branch on my fork.

**Comment by gerhardol** [comment]
> I started refactoring and cleaning up the code that comprises the Filters toolbar. I've already mostly cleaned up the FormBrowse, factored out and removed the revision filter helper. The branch filter helper is next. After that the same clean will be made to the FormFileHistory. I wouldn't want you to spend time and make changes that ultimately will be removed. You can see the refactor branch on my fork.

That work is mostly unrelated to what I am doing, changing the filter interface very briefly. I would not mind if the toolbar filter (that I find confusing) were more tightly coupled with the advanced filter though, the double filters are confusing. d69f4dc04e0a6e64619eb2b45ee9bea83a7278a5 (or 9b4740be062929a0754fabb139140a1ad68cada4) is all I plan right now. (Those changes were a feedback from later changes actually, it made sense to not change the interfaces twice.)
Also, the "InMem" handling may not be needed with newer Git.

For FormFileHistory, one option is to completely replace that with FormBrowse, so we may not want to make too many changes there.

My changes are not very big but changes certain key aspects. Except for #9413 they should not be difficult to review, separated in many commits. The commits relate to eachother, so the end result in https://github.com/gerhardol/gitextensions/tree/feature/i7598-replace-formfilehistory should be of interest in the other reviews. (Of course, I could submit one PR with all, that is harder to review.)

**Comment by mstv** [comment]
> Replace file viewer in FileTree (as mstv suggested). I find this much too slow though.

Yes, the slow scrolling is really an issue.
I hadn't in mind to use the blame view for all viewers. Though it would be consistent.
The horizontal space required for the commit info gutter may be an issue, too, e.g. in tab "File tree".

> Is a simple "View" mode for FileTree needed?

Your proposal to toggle blame / view using a toolbar button may be a compromise.
Perhaps it suffices to collapse the commit info gutter.
In "**file** history mode", I would prefer a wide tab "Blame" without the FileTree. There the FileTree could be collapsed using another toolbar button.

> Browse could replace FileHistory completely.

IMO yes - later unless users complain.
`F` 👍
`H` should launch a new GE with FormBrowse filtered to the file / folder.

(I have not finished reading - I will continue later.)

**Comment by gerhardol** [comment]
#9424 just replaces view with Blame in FileTree
I did not see how to use BlameControl from FileViewer (only the RevDiff/RevFileTree controls), but it could be controlled from FileStatusList context menu. Would that be OK?
(The `B` would toggle View/Blame, could also be used in RevDiff to toggle Diff/Blame.)
What about using #9424 as is and change later, there is quite som time until master can be released?
(I guess at least 10 persons use their own master builds, so some more feedback.)

Will add a setting to launch either Browse (w filter) or FileHistory. (a draft in my private branch).
I do not think that it a good idea to have a special mode for FormBrowse when starting with a filter. However, the initial viewed file can be set to the filtered file.
