### ISSUE TITLE
Merge Branch form: Checkbox not lined up + shouldn't show resize cursor

### ISSUE THREAD

**Issue by MarkJ74** [gitextensions/gitextensions#7602]
## Current behaviour

Two issues on the merge branch form:
1. The 'Allow unrelated histories' checkbox is not lined up with the others (shown if you tick 'Show advanced options')
2. If you put the cursor over the bottom-right corner it shows a resize cursor, but you can't resize the dialog.

## Expected behaviour

1. Checkboxes should all be lined up and spaced evenly.
2. It shouldn't show the resize cursor over the bottom-right corner.

## Screenshots

![MergeBranchForm](https://user-images.githubusercontent.com/26597823/71858169-2897ca80-30e2-11ea-8227-2450e4966a32.png)

## Did this work in previous version of GitExtensions

No.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4075.0
- DPI 120dpi (125% scaling)

**Comment by vbjay** [comment]
They aren't lined up to show that they are the advanced options.

I do agree with the cursor fix.

**Comment by MarkJ74** [comment]
I get that the advanced options checkboxes are indented, but the last five checkboxes in the screenshot are the advanced ones, and they should line up with each other? The third of the five doesn't line up with the others.

**Comment by pmiossec** [comment]
He is right, there is a checkbox not well aligned...

But there are a lot of things that are not perfect in this form (but I
never found the time to do it) :

* the "Merge" group box is useless
* a group ox for the advanced options should be added
* a label "Strategy" should be added for the 2 radio buttons
* and surely other things...

**Comment by MarkJ74** [comment]
Yes you're right there's lots of issues, one step at a time... I just noticed these things, I've created a PR to fix.
