### ISSUE TITLE
[NBug] Index out of bounds

### ISSUE THREAD

**Issue by PhiLhoSoft** [gitextensions/gitextensions#7614]
## Current behaviour

Git Extensions crashed when I pasted a multiline French text in the commit message area.

## Expected behaviour

No crash…

## Steps to reproduce

Pasted the following text:

```
Remarques sur le redesign
p. 1 - Menu de gauche
- Séparateur enlevé
- couleur icône #999 : seulement icône ? Pas texte ? Couleur (icône et texte idem) codée en dur dans le composant de sidebar --> design system
Faisable pour l'arbre.
- icône flèche : fait
- zone cliquable : fait
- Items manquants : pages vides ?
- Powered by oodrive viré

p. 2 - Menu de gauche
- Couleur hover : #F0F0F0 ; pas plutôt #F2F2F2 ? Dans le design system, gray-200. C'est #E5E5E5 pour la sidebar, gardé pour l'arbre. Passé à gray-200
- Fond (pas très clair). Sur "Fichiers", j'ai gardé la couleur de la sidebar si fermé, et je passe à la couleur de l'arbre si ouvert.
- Séparation (TODO, pas évident…)

p. 3 - Comportement arbo (TODO)

p. 4 - Fil d'ariane
--> Design system

p. 5 - Dropdown
--> Design system

p. 6 - Panneau de droite
- Couleur bord : fait
- Onglets --> Design system
- Système de fermeture : 
- Bonus : les infos sur l'état du fichier sont affichées en clair dans ce panneau.

```

## Error Details
```
System.IndexOutOfRangeException: L'index se trouve en dehors des limites du tableau.
   à GitUI.SpellChecker.EditNetSpell.Line(Int32 line)
   à GitUI.CommandsDialogs.FormCommit.<FormatAllText>g__SetFormattedLine|208_3(Int32 lineNumber, <>c__DisplayClass208_0& )
   à GitUI.CommandsDialogs.FormCommit.FormatAllText(Int32 startLine)
   à GitUI.CommandsDialogs.FormCommit.FormatAllText(Int32 startLine)
   à GitUI.CommandsDialogs.FormCommit.FormatAllText(Int32 startLine)
   à GitUI.CommandsDialogs.FormCommit.Message_TextChanged(Object sender, EventArgs e)
   à System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   à GitUI.SpellChecker.EditNetSpell.TextBoxTextChanged(Object sender, EventArgs e)
   à System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   à System.Windows.Forms.TextBoxBase.WmReflectCommand(Message& m)
   à System.Windows.Forms.RichTextBox.WmReflectCommand(Message& m)
   à System.Windows.Forms.RichTextBox.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I pasted a 32 line comment, with French accents, in the commit message area (first two lines were empty).

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Can you reproduce it? Do you use special settings?
I even switched to the French dictionary. But there are still many unknown words:
![grafik](https://user-images.githubusercontent.com/36601201/72002876-90682580-3248-11ea-9ea8-15da3dcb934c.png)

**Comment by RussKie** [comment]
I can't repro it either in 3.3.1

**Comment by PhiLhoSoft** [comment]
Well, I just tried again (with no files to commit) and indeed it crashed again. Twice (tried with a copy of the text above).
I have a French Windows, but GE language is set to English, I have no idea how to use another dictionary (is it automatic?) and usually I don't care because I always do commit messages in English (I just wanted to save temporarily a copy of this, using the auto-save the commit message…)

From my PoV, it isn't important, you can close it if you want (the issue was created by the crash manager).

> I even switched to the French dictionary. But there are still many unknown words:

All the French words, so not sure if your switch was effective…

**Comment by RussKie** [comment]
Can you please share .git/COMMITMESSAGE? Perhaps it could help in repro the issue

**Comment by PhiLhoSoft** [comment]
I don't know if we can upload a file in this bug tracker.
Meanwhile, I have put it there: https://we.tl/t-2dCOYZLIv6 (expires after a week).

**Comment by RussKie** [comment]
Thank you. I tried your file and I was unable to observe a crash...

**Comment by pmiossec** [comment]
Unable to reproduce also.
And looking at the code, it seems than a legit access to al the lines of the textbox equivalent to: 

```csharp
            var lineCount = Message.LineCount();
            for (int line = startLine; line < lineCount; line++)
            {
                Message.Line(line);
            }
```

Except if the content of the textbox is quickly modified by something else (outside of GitExtensions) during the formatting.

We could add a quick protection in the `Line(line)` method but I don't know what will be the resulting behavior...

**Comment by PhiLhoSoft** [comment]
Don't worry, then, it might be an issue specific to the computer I have at work, which has some strange behaviors in some corner cases.
You can just close the issue.
