### ISSUE TITLE
Commit tab doesn't reload

### ISSUE THREAD

**Issue by gabihecksher** [gitextensions/gitextensions#7622]
When I pull from a repo or checkout a different branch the commit tab stays the same, it's not updated. I have to close GitExtensions and reopen and only then I can see the commit changes.

**Comment by mstv** [comment]
Please fill in the bug report template, especially the info which can be copied from the About dialog and the "git command log" (`F12`).

**Comment by gerhardol** [comment]
As well as screenshots

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/72232498-82d7d600-358f-11ea-9411-fe5a94451ae6.png)

**Comment by crypto-rsa** [comment]
I am not sure if it's related, but I also observe that the commit _dialog_ is not refreshed when I:
1. Open the History window of one of the changed files
2. From it, I create a fixup commit (using `Ctrl+X`) - this opens a _new_ commit dialog
3. Stage and commit some changes in the second commit dialog
4. Close both the second commit dialog and the history window

The original commit window again receives focus but it is not refreshed.

**Comment by pmiossec** [comment]
@crypto-rsa I don't think it is the same problem.

Your's is that no one could imagine that someone will create a commit from the history form. And so, that it could be needed to refresh browse form after closing the history.

I think it's such a edge case that I'm not sure it worth refreshing all the time after closing the history form to handle that scenario.

Thoose that creates commits there would know that the history should be refreshed...

**Comment by crypto-rsa** [comment]
@pmiossec I believe there are other users who make fixup commits from the history form because it's really the fastest way to create fixups. I was thinking about possible improvements of the UI specifically for making a fixup of some previous commit in the same file but in the end the history form seems to be the most flexible approach - even if that means opening GE windows on top of other GE windows.

**Comment by gerhardol** [comment]
FileSystemWatcher could be enhanced to not just detect changes to Index, so the user sees that refresh should be done.

**Comment by mstv** [comment]
Works for me with
![image](https://user-images.githubusercontent.com/3629489/72232498-82d7d600-358f-11ea-9411-fe5a94451ae6.png)
(This discussion is not really related to the initial issue starting from the comment with this screenshot above.)

**Comment by RussKie** [comment]
> FileSystemWatcher could be enhanced to not just detect changes to Index, so the user sees that refresh should be done.

Do you mean use [`IndexWatcher`](https://github.com/gitextensions/gitextensions/blob/ac9e789f20f01979b2f88e56829b6f574f4fbfcd/GitUI/UserControls/RevisionGrid/IndexWatcher.cs) in the `FormCommit`?

At the same time we do have functionality to refresh the `FormCommit` upon focus. Why it is not sufficient?

**Comment by gerhardol** [comment]
>Do you mean use IndexWatcher in the FormCommit?
At the same time we do have functionality to refresh the FormCommit upon focus. Why it is not sufficient?

The original question was for the commit _tab_. If you do changes outside GE you may not see that the view is out of date.

CommitDialog is refreshed on focus, not on detecting changes.

**Comment by RussKie** [comment]
I must have totally misread. Ignore me

**Comment by RussKie** [comment]
I have marked everything not related to Commit tab as off-topic. If you think they are important and require work, please raise a new issue.
