### ISSUE TITLE
3.3.1 - Installing 3.3.0

### ISSUE THREAD

**Issue by laurin1** [gitextensions/gitextensions#7631]
C:\windows\system32>cinst gitextensions
Chocolatey v0.10.15 Business
Installing the following packages:
gitextensions
By installing you accept licenses for the packages.
Progress: Downloading gitextensions 3.3.1... 100%

gitextensions **v3.3.1** [Approved]
gitextensions package files install completed. Performing other installation steps.
**Installing GitExtensions-3.3.0.7886.msi...
GitExtensions-3.3.0.7886.msi has been installed.**
Added C:\ProgramData\chocolatey\bin\gitex.exe shim pointed to 'c:\program files (x86)\gitextensions\gitex.cmd'.
  gitextensions may be able to be automatically uninstalled.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of gitextensions was successful.
  Software install location not explicitly set, could be in package or
  default install location if installer.

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

**Comment by pmiossec** [comment]
That's a problem with the chocolatey package:

See `tools\chocolateyInstall.ps1` file at https://chocolatey.org/packages/gitextensions#files

```
$ErrorActionPreference = 'Stop'

$toolsDir = Split-Path -Parent $MyInvocation.MyCommand.Definition

$packageArgs = @{
    packageName    = $env:ChocolateyPackageName
    softwareName   = 'Git Extensions*'
    fileType       = 'msi'
    file           = "$toolsDir\GitExtensions-3.3.0.7886.msi"
    silentArgs     = '/quiet /norestart ADDDEFAULT=ALL REMOVE=AddToPath'
    validExitCodes = @(0, 3010, 1641)
}

Install-ChocolateyInstallPackage @packageArgs

Get-ChildItem $toolsPath\*.exe | ForEach-Object { Remove-Item $_ -ea 0; if (Test-Path $_) { Set-Content "$_.ignore" '' } }

Install-BinFile gitex "$(Get-AppInstallLocation GitExtensions)\gitex.cmd"
```

It seems that you already reported it, so closing as we can't do anything...

**Comment by RussKie** [comment]
@gep13 @pauby need you help, thank you

**Comment by laurin1** [comment]
Oops, sorry, I thought I was on the choco package repo. I should be more awake before I start posting issues. :)

**Comment by gep13** [comment]
This issue has been re-submitted here: https://github.com/chocolatey-community/chocolatey-coreteampackages/issues/1413
