### ISSUE TITLE
[NBug] Objektreferanse er ikke satt til en objektforekomst.

### ISSUE THREAD

**Issue by mn75930** [gitextensions/gitextensions#7636]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NullReferenceException: Objektreferanse er ikke satt til en objektforekomst.
   ved Git.hub.Repository.GetBranches()
   ved GitHub3.GitHubRepo.GetBranches()
   ved GitUI.CommandsDialogs.RepoHosting.CreatePullRequestForm.<>c__DisplayClass22_0.<<PopulateBranchesComboAndEnableCreateButton>b__0>d.MoveNext()
--- Slutt på stakksporing fra forrige plassering der unntak ble iverksatt ---
   ved System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Opens the Create Pull Request and it fails...

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.19.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3468.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
https://github.com/gitextensions/gitextensions/issues/7594#issuecomment-570516907 by @pmiossec 

(Real) duplicate of #6757.

You must not have generated your github token (or maybe it is not valid anymore)

We added a protection in #6814 but it seems to be not enough 😢
And I don't reproduce 😭

**Comment by pmiossec** [comment]
It seems to be because the token, if it exists, is not valid and the data could not be fetched. See https://github.com/gitextensions/gitextensions/issues/7594#issuecomment-575041350

**Comment by pmiossec** [comment]
I have created an issue best describing the problem: #7641
