### ISSUE TITLE
Can't delete more than a file at a time

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#7637]
## Current behaviour

Since #6296, we can't delete more than a file at a time in RevisionDiffControl. I wonder why ?

## Expected behaviour

Be able to delete multiple file at a time.

## Steps to reproduce

In a repository, modify two files
Open Git Extensions
Click on "Working directory"
Go on Diff tab
Select the two files
Click right
Delete file is not visible.

## Did this work in previous version of GitExtensions

No idea.

## Environment

- GitExtensions version: 3.3.1.7897
- GIT version: 2.24.1.windows.2
- OS version: Microsoft Windows NT 10.0.18363.0
- .NET version: 4.8.4075.0

**Comment by gerhardol** [comment]
GitUI\CommandsDialogs\RevisionDiffController.cs:L122 ShouldShowMenuDeleteFile()

If several files can be selected, the checks must be adapted to show when relevant (not submodules, files exists etc). Could be done, but complex as it is.

However, DEL works for multi deletion.

**Comment by bansan85** [comment]
OK, thanks. I will try to fix it.
