### ISSUE TITLE
NRE when GitHub token is invalid

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#7641]
## Current behaviour

When the GitHub token is invalid, [Repository.Owner](https://github.com/gitextensions/Git.hub/blob/master/Git.hub/Repository.cs#L14) property is not filled (which is normally done by the `Git.hub.dll` code) so every call in this class that use `Owner.Login` crash with an exception.

Follow up of  #6814

See #7594, #7636

Workaround: generate a new valid github token.

## Expected behaviour

Not crash.

## Steps to reproduce

1. Set a bad GitHub token
2. Go to "Create pull request..."
3. NRE

## Did this work in previous version of GitExtensions

No

## Environment

- Git Extensions 3.3.0
- Build d0d22cdcbd88322e5d0c3270b70eb61490e73a5e
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4075.0
- DPI 192dpi (200% scaling)

**Comment by RussKie** [comment]
@pmiossec is there anything up your sleeve that we can add before we release?

**Comment by pmiossec** [comment]
I've started to work on that but forgot about it.

Looking at it again, even if there was a little improvement, it doesn't seems to me the good solution.
I could have a look again (even if I have little time at this moment).
It depends when we expect to release the version...

**Comment by gerhardol** [comment]
5d4ce8f3ae30c26710f5ce15979011bf4ebdbc8f in master and release/3.4 (no PR) improves the error message.
Should this be kept open?

**Comment by pmiossec** [comment]
The message, with the fix, even if not very user friendly, is enough for the user to understand what is the problem and fix it (it is better than a NRE). 

Investing more time on this issue doesn't worth it for what seems to be a rare issue.
So we could consider it as fixed.
