### ISSUE TITLE
[NBug] 远程主机强迫关闭了一个现有的连接。

### ISSUE THREAD

**Issue by xiahetingyu** [gitextensions/gitextensions#7642]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Net.Sockets.SocketException (0x80004005): 远程主机强迫关闭了一个现有的连接。
   在 System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   在 System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
```

## Additional information
i don't konw!!

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.24.1.windows.2
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Fixed in #7576

Please update to 3.3.1
