### ISSUE TITLE
[NBug] Unable to parse object ID "switch".

### ISSUE THREAD

**Issue by studentmain** [gitextensions/gitextensions#7650]
## Current behaviour

Program crash when viewing diff of specific commit.

![图片](https://user-images.githubusercontent.com/17123090/72666081-ae7f1400-3a06-11ea-8fcf-57dcd466cc7a.png)

## Expected behaviour

Program not crash

## Steps to reproduce
1. clone https://github.com/komeiji-satori/Dress
2. view commit 76fce49f's diff.

## Error Details
```
System.FormatException: Unable to parse object ID "switch".
   在 GitUIPluginInterfaces.ObjectId.Parse(String s)
   在 GitCommands.GitModule.GetFileBlobHash(String fileName, ObjectId objectId)
   在 GitUI.Editor.FileViewer.ViewGitItemRevisionAsync(String fileName, ObjectId objectId, Action openWithDifftool)
   在 GitUI.CommandsDialogs.RevisionDiffControl.<ShowSelectedFileDiffAsync>d__35.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 GitUI.CommandsDialogs.RevisionDiffControl.<DiffFiles_SelectedIndexChanged>d__36.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 Microsoft.VisualStudio.Threading.JoinableTaskFactory.SingleExecuteProtector.TryExecute()
```

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.22.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
This occurs due to the filename to view in the diff is starting with a "-" and Git interprets as a parameter
