### ISSUE TITLE
Add Git Extensions to Microsoft App Store

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#7658]
## Feature description

Provide a way for users to install in Microsoft App Store in Windows 10.  Haven't done much research in what is needed but it looks like desktop apps can be added with some kind of shim.  

https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-root

## Environment

Version Next

**Comment by gerhardol** [comment]
A PR related to this:
https://github.com/gitextensions/gitextensions/pull/4497

But it is a problem to keep SourceForge updated in addition to GH...

**Comment by RussKie** [comment]
Gerhard you're good!

We may be in a position to revive that work...

**Comment by mast-eu** [comment]
Reading through https://oren.codes/2018/05/15/oss-build-and-release-with-vsts/ I understand that deploys to the Microsoft App Store could be fully automated once we are on Azure DevOps (#7668).
