### ISSUE TITLE
No supported authentication methods available (server sent: publickey)

### ISSUE THREAD

**Issue by Kundan22** [gitextensions/gitextensions#7662]
## Current behaviour
I am using visual studio 2019 and recently upgraded git version 2.25.0.windows.1. 
All the git operations are working fine with gitbash and tortoise windows extensions. I've my ssh public key file kept in C:\Users\user-name\.ssh & C:\Program Files\Git\etc\ssh

but when I am trying to push my changes using visual studio I am getting below error[ScreenShot].

##am I missing any configuration or place where public key should be present?

## Expected behaviour
As git bash is and other plugin tortoise git is working fine visual studio github extension should also work for me

## Steps to reproduce
Open any local github repository , make changes and try to push it to master branch. and it throws similar error
## Screenshots

![image](https://user-images.githubusercontent.com/31039343/72727134-786a9d00-3b8a-11ea-8964-377a0cc9560b.png)

## Did this work in previous version of GitExtensions
Yes It was working fine with earlier version v2.17.1(2)

## Environment

- GitExtensions version: 2.10.8.8121
- GIT version: 2.25.0
- OS version: Windows10, VS2019
- .NET version: 4.7.2
- VisualStudio: VS2019

**Comment by gerhardol** [comment]
Do you have a PuTTY public key setup?
From the paths you refer to, it could be that you have switched from OpenSSH to PuTTY in the settings.

**Comment by Kundan22** [comment]
where do I check that, in Visual Studio or somewhere else?

**Comment by vbjay** [comment]
run 

```bash
git config --global --edit
git config --edit
```
in a git bash console pointing to a project that has this issue and reply with the contents of each removing any sensitive data.

**Comment by Kundan22** [comment]
running git command from same project directory with git bash I am getting error 
`bash: $'\302\226git': command not found` in both cases

**Comment by vbjay** [comment]
Sounds like you might have environment issues. Try uninstalling git and
then reinstalling it or repairing the installation.

**Comment by vbjay** [comment]
https://git-scm.com/

**Comment by Kundan22** [comment]
re-installed git from https://git-scm.com/ and same issue. Git bash & Tortoise git works fine and asks for ssh key credential as soon as I Push the changes.

But Visual Studio and VSCode git bash gives this error when I tries to push the changes

![image](https://user-images.githubusercontent.com/31039343/72823014-56007e80-3c73-11ea-9e6d-82355772e947.png)

**after re-installing following commands gives this output now**

git config --global --edit

```
[gui]
[user]
	name = username
	email = test@test.com
[sequence]
	editor = rebase-editor
[credential]
	helper = manager
	modalPrompt = true
```


git config --edit

```
[core]
	repositoryformatversion = 0
	filemode = false
	bare = false
	logallrefupdates = true
	ignorecase = true
[remote "origin"]
	url = git@github.company.com:full-name/Repo-name.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
[user]
	name = username
	email = test@test.com
```

**Comment by vbjay** [comment]
Visual studio uses it's own internal git version.   Try updating visual
studio.  GitHub extension also will have its config.
https://marketplace.visualstudio.com/items?itemName=GitHub.GitHubExtensionforVisualStudio

My recommendation is to use our extension in visual studio to do git
operations in visual studio.

https://marketplace.visualstudio.com/items?itemName=HenkWesthuis.GitExtensions

You can use the GitHub extension to do other GitHub related things.

**Comment by Kundan22** [comment]
I got it fixed by modifying the `GIT_SSH` path in system environment variables to point to `C:\Program Files\Git\usr\bin\ssh.exe` which was earlier pointing to `C:\Program Files\TortoiseGit\bin\TortoisePlink.exe` 

this is now showing this password windows which I guess is correctly coming from OpenSSH

![image](https://user-images.githubusercontent.com/31039343/72882232-8a6f4b80-3d02-11ea-9c89-bfbf1468b4ca.png)

**Comment by siraj-solarwinds** [comment]
I got it fixed by modifying the GIT_SSH path in system environment variables to point to C:\Program Files\Git\usr\bin\ssh.exe which was earlier pointing to C:\Program Files\TortoiseGit\bin\TortoisePlink.exe 

Too good

**Comment by palfi-robert-30123** [comment]
EVERYBODY
TYPE AT THE HOST NAME bitnami@ before the host and this is working!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by StaelensJarne** [comment]
I have this problem when I create an empty repository?
I have the value off GIT_SSH set to C:\Program Files\Git\usr\bin\ssh.exe

Is there somwehere a good tutorial how to solve these issue?

**Comment by gerhardol** [comment]
> I have this problem when I create an empty repository? I have the value off GIT_SSH set to C:\Program Files\Git\usr\bin\ssh.exe

GE sets GIT_SSH internally, set the path in GE settings

> Is there somwehere a good tutorial how to solve these issue?

GE sets GIT_SSH (and has some built-in to start PuTTY) to GE settings.
Other than that is standard Git handling so standard guides can be used. There are many things that can be set incorrectly, but that is not unique for GE.
Get it working from the command line with the same home directory as GE uses.

**Comment by StaelensJarne** [comment]
After some trail an error I found a solution for my problem.

The GitHub credential manager was not working properly.
I reinstalled GitHub for windows and used my GitHub account to authenticate again.
And then it worked properly.
