### ISSUE TITLE
[NBug] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by ValeryAntopol** [gitextensions/gitextensions#7664]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
```

## Additional information
As notification about update appeared, I clicked button "update" and waited for an update. My internet connection was not stable.

## Environment
- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.16.2.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of  #7613 

Fixed in #7576

Please update to 3.3.1
