### ISSUE TITLE
Intent to join .NET Foundation

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#7668]
We are considering joining [.NET Foundation](https://dotnetfoundation.org/) and exploring our options.

### 1: CLA Management
Any open source project consists of contributors, that is people who submit code to the project. When contributors donate code they need to sign a "Contributor License Agreement”. The Contributor License Agreement or “CLA” as it is commonly referred to ensures that the individual is donating the code as open source with no strings attached. This protects open source projects from any legal issues in the future.

Right now we ask contributors to provide "Certification of Origin" and sign off via [contributors.txt](https://github.com/gitextensions/gitextensions/blob/master/contributors.txt). This is tiresome and prone to errors. It also precludes some of our past contributors from contributing further.

.NET Foundation's CLA management is significantly more robust, and is accepted by other big enterprises (e.g. Google).

### 2: Automated builds with Azure DevOps
Being a .NET project we would benefit more being on AzDO then leveraging AppVeyor (we are very thankful to AppVeyor for hosting us!).
AzDO provides build and release workflows that are missing from other providers, and has a better integration with GitHub and NuGet platforms.
@onovotny has a great post about it https://oren.codes/2018/05/15/oss-build-and-release-with-vsts/

Does anyone have any objections?

**Comment by mast-eu** [comment]
No objections from my side.

**Comment by RussKie** [comment]
I have submitted an application to join - https://github.com/dotnet-foundation/projects/issues/49

**Comment by Piedone** [comment]
Great to see this!

AFAIK among other perks, you can also get a LastPass account to share credentials like for a Twitter account (is this yours BTW? https://twitter.com/ExtensionsGit).

**Comment by RussKie** [comment]
> is this yours BTW? [twitter.com/ExtensionsGit](https://twitter.com/ExtensionsGit)

Yes, it is ours, but I'm not happy with the handle... Someone used our handle years ago to send spam, and we can't get it back :\

**Comment by RussKie** [comment]
After further deliberation with myself I changed it to @git_extensions.

**Comment by pmiossec** [comment]
>After further deliberation with myself I changed it to @git_extensions.

🤣 🤣 🤣 🤣 🤣 

Indeed, much better 😉 👍

**Comment by MarkJ74** [comment]
You might want to read Rob Mensching of WiX Toolset's experience with the .NET Foundation: https://robmensching.com/blog/posts/2021/10/6/how-the-.net-foundation-kerfuffle-became-a-brouhaha/

**Comment by RussKie** [comment]
Thanks, I've been semi-following the development.
At this stage I don't see a compelling reason to join, as the list of things/help/support that were initially offered has dwindled down.
