### ISSUE TITLE
blame --reverse support

### ISSUE THREAD

**Issue by brunom** [gitextensions/gitextensions#7672]
From the manpage:

> Walk history forward instead of backward. Instead of showing the revision in which a line appeared, this shows the last revision in which a line has existed. This requires a range of revision like START..END where the path to blame exists in START.

**Comment by gerhardol** [comment]
If ever added, how to control the commit range and the functionality itself?

**Comment by brunom** [comment]
- reverse could be a checkbox and the range could be shown as in the rebase advanced dialog.

**Comment by RussKie** [comment]
Please fill in the template provided. If you think it is ok to come drop a line and expect someone do the work than this is simply disrespectful.
