### ISSUE TITLE
Support F3 (Open with difftool) in the revision grid

### ISSUE THREAD

**Issue by sharwell** [gitextensions/gitextensions#7674]
Currently we support <kbd>F3</kbd> (Open with difftool for First&rarr;Selected) in the Diff pane on individual files, but we do not support it when a commit is selected in the revision grid. We do support `--dir-diff` (#1647), but it's not easy to open this feature (multiple steps with decisions to make at each step).

**Comment by mstv** [comment]
![grafik](https://user-images.githubusercontent.com/36601201/73017217-ad435200-3e1f-11ea-94dd-3d60692642aa.png)
Or did I get your intention wrong?

There are known issues related to this:
- The hotkey does only work if the RevisionGrid is focused, i.e. not the left panel or the CommitInfo.
- Occasionally, hotkeys do not work right after startup. Just click into the RevisionGrid again.
- (Nothing will happen if the regarding file is not changed -- does not apply here.)

**Comment by sharwell** [comment]
Ah, <kbd>F3</kbd> on the revision grid does open the diff tool, but it opens the _wrong_ diff tool. When the revision grid is active, it should be starting a `--dir-diff` session.

**Comment by sharwell** [comment]
I'm specifically interested in the behavior when the selection is the circled item:

![image](https://user-images.githubusercontent.com/1408396/73019063-b8728f80-3dd7-11ea-9270-10be0eb33495.png)
