### ISSUE TITLE
Windows taskbar jumplist entries don't work

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7683]
## Current behaviour

1. The Windows taskbar jumplist entries of GE do not work:
"The selected element is not available. It has been moved, renamed or removed. ...",
although the `%APPDATA%\Roaming\GitExtensions\GitExtensions\Recent\*.gitext` files contain the correct paths (with a trailing backslash).
2. The recent repos list does not match the jumplist.

## Expected behaviour

1. Jumplist entries work
2. Any repo opened in GE is added to the jumplist.

## Steps to reproduce

1.
  - open a repo using the Explorer context menu
  - pin GE to the Windows taskbar
  - close GE
  - right click the GE icon in the taskbar and select the recent repo
2.
  - select a repo from the dropdown in the GE taskbar or from the GE dashboard
  - (optionally) close GE
  - right click the GE icon in the taskbar

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/73102216-adac1d80-3ef1-11ea-9fe1-4f8d71fbc4e5.png)

## Did this work in previous version of GitExtensions

yes, but don't know / haven't checked which
issue 1. works with the same or only slightly older build on Win 7

## Environment

- Git Extensions 3.3.0
- Build 7034c98856ecb70f1d716d12e92652e6998c98ff (Dirty)
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
This should be investigated for 4.0
@drewnoakes any hints?

**Comment by gerhardol** [comment]
The changes in #7941 restores the Recent list (and fixes buttons that are broken since a refactoring two years ago). 
The check for a running application need to be adapted though.

However, it seems like this only works for the registered application - do not remember if this was the case before.
Before manipulating the registry settings, I could not open the recent list directly, but had to rightclick and select open with GE (using the default installation only).
Seem to be a Windows problem also with MS applications https://answers.microsoft.com/en-us/msoffice/forum/all/the-item-you-selected-is-unavailable-it-may-have/0b64c45e-73df-4d3b-8144-5c2e44c621d3

**Comment by gerhardol** [comment]
A summary:

The main problem was likely introduced in #4988 when the ApplicationId was no longer set before JumpList was initiated.
This also changed the button handling some (but the button status was not updated previously as added in the PR.)

Most of the functionality was somehow still working until #7750 (maybe something before), that caused the JumpList to not be updated - the jumplist was created a little too early though.

Some problems still occur with #7941 in its current status:
* The functionality occasionally requires that the registry is updated, see below. I find no fix for that, if Excel has the problem, I assume that someone at MS has investigated at least...
* The main window handle is occasionally not set when adding recent or enabling the taskbar miniature buttons. With the PR, this should be fixed when loading next repo (I do not want to reverse #7750)
* The Recent list depends on the ApplicationId matching the registry including installation paths. It will not work well for portable or debug builds

**Comment by RussKie** [comment]
Thank you for the assessment.

> * he Recent list depends on the ApplicationId matching the registry including installation paths. It will not work well for portable

What if we disabled it for portable versions?



> Before manipulating the registry settings, I could not open the recent list directly, but had to rightclick and select open with GE (using the default installation only).
> Seem to be a Windows problem also with MS applications [answers.microsoft.com/en-us/msoffice/forum/all/the-item-you-selected-is-unavailable-it-may-have/0b64c45e-73df-4d3b-8144-5c2e44c621d3](https://answers.microsoft.com/en-us/msoffice/forum/all/the-item-you-selected-is-unavailable-it-may-have/0b64c45e-73df-4d3b-8144-5c2e44c621d3)

Hmm, I've never come across this problem. And I always open my recent repos via the right click and selecting MRUs...

> Process.GetCurrentProcess().MainWindowHandle is null also occasionally when FormBrowse reports a handle

We have two main entries int the app - `FormBrowse` and `FormCommit`. I suppose we can concentrate on `FormBrowse` only, as one doesn't browse a repo entering via `FormCommit`.
So would it work if we use `FormBrowse.Handle`?

**Comment by gerhardol** [comment]
> What if we disabled it for portable versions?

Recent list, the miniature buttons and progressbar works.
For Debug, it could be handled (with some manual tweaks). It could be more confusing for maintainers to not see the Recent list at all, so keeping.

> So would it work if we use FormBrowse.Handle?

That is what is used now when creating the jumplist, which was what #7750 broke. As #7750 makes sense (do not update GUI if no window is shown) especially at shutdown, it should not be reversed completely, adding recents makes sense. (refreshing jumplist recents should not be, if it is implemented). Adding a change.

This is certainly not my home terrain...

**Comment by WonkoDaSane** [comment]
This still seems to be a problem, even after the most recent upgrade to 3.4.2.9737.

The "Recent Repositories" page points to the correct location, but the jumplist points to %APPDATA\Roaming\GitExtensions\GitExtensions\Recent

**Comment by RussKie** [comment]
I.e. missing the second `%` in APPDATA? Is this the problem?
