### ISSUE TITLE
Commit Dialog: Ctrl+V on commit message executes the commit

### ISSUE THREAD

**Issue by pherrymason** [gitextensions/gitextensions#769]
Trying to paste some text on the commit message box using CTRL+V immediatelly does the commit.

I've seen this from 2.26 (first version I ever tested) and still on 2.28, under Windows XP/ Windows 7 (64bits)

**Comment by davecapper** [comment]
This happened to me today on version 2.48.05. I was trying to copy in the commit message from another branch. I used the context menu to copy the message, then opened the commit dialog to paste in the message. CTRL+v performed the commit rather than pasting the message.

**Comment by GianlucaBobbio** [comment]
Happened to me on version 2.48.05

**Comment by PRossetti** [comment]
I sometimes have the exact same problem. My Git Extensions version is 2.48.05 and I'm running Windows 10 Pro 64 bits

**Comment by KindDragon** [comment]
Try update GitExt to latest version and test again
