### ISSUE TITLE
Delete obsolete branches does not apply regex filter upon opening the window

### ISSUE THREAD

**Issue by TamaMcGlinn** [gitextensions/gitextensions#7699]
## Current behaviour

I have a configuration that is committed together with the project, including a regex to filter branches. But when I open the 'Delete obsolete branches' window, the filter is not applied. I have to first press the 'search branches' button, before the filter is applied.

This will cause problems, as a developer unaware of this will certainly at some point delete too many branches. There is no hint in the UI that the filter has not been applied yet. And I suspect this is a bug in the implementation of #3520 / #4405 (@aivanov-oneinc) - before adding those settings, it was not possible to already have a regex set when you open the window.

## Expected behaviour

If the regex filter is already filled upon opening the window (as is the case when it is pre-configured), the filter is also applied immediately.

## Steps to reproduce

1. Open GitExtensions on some repository
2. Choose Plugins > Plugin Settings > Delete obsolete branches
3. Set the checkbox for Úse regex to filter branches to delete' and a filter e.g. bugfix/.*|feature/.*
4. Choose Plugins > Delete obsolete branches
5. Observe that the filter has not been applied

## Screenshots

https://imgur.com/GCI5ElQ

## Did this work in previous version of GitExtensions

The bug was introduced presumably around version 2.51.01 when the regex filter settings became saveable.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by hieuxlu** [comment]
@RussKie After debugging and checking again, I think I might have made a mistake when saying it's reproducible. The regex filter is working fine for both remote/local branches. I think we can close this issue. Sorry for the confusion.
