### ISSUE TITLE
Windows protected your PC (Windows Defender)

### ISSUE THREAD

**Issue by Mike-EEE** [gitextensions/gitextensions#7705]
## Current behaviour

I get a Windows Defender warning when attempting to install the MSI.  Not exactly the warm n' fuzzies. 😁

## Expected behaviour

Installing your fine application without feeling like it's about to install something malicious.

## Steps to reproduce

I clicked on the `Direct download` on the latest update notification within Git Extensions and then attempted to install the downloaded, resulting MSI.

## Screenshots

![](https://i.imgur.com/jfRU1FT.png)

## Did this work in previous version of GitExtensions

I believe I have encountered this before, but wanted to make sure it's a known issue as it is a bit off-putting.  Has your direct download functionality been hijacked?  It is difficult to determine, if so.

## Environment

- Git Extensions 3.3.0.7719
- Build e52f5178e8d3c9899efbe6fae66026865afa3fe1
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

## Diagnostics

NA

**Comment by RussKie** [comment]
We had a new signing cert, but I'd think it would have collected enough rating by now.
