### ISSUE TITLE
gitex.cmd filehistory doesn't work filenames with quoted paths with whitespaces

### ISSUE THREAD

**Issue by Maesla** [gitextensions/gitextensions#7709]
## Current behaviour
When you try to use the command line gitex.cmd filehistory filename, it doesn't work with filenames with quoted paths and spaces in the path
## Expected behaviour
Open the **filename** file history

## Steps to reproduce
Write in the console
gitex.cmd filehistory filename
filename, with quotes and 1..N spaces

For example
gitex.cmd filehistory "F:/Assets/Vehicle Cameras/Rearviews.prefab"

Instead of opening the file history, you will see in the prompt:
@if "filehistory "F:/Assets/Vehicle Cameras/Rearviews.prefab""=="" SET arg=browse .

## Did this work in previous version of GitExtensions
Yes, it worked in 3.3

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

## Diagnostics
The problem is the new version of gitex.cmd. With the batch previous version, it works.

From the change log

> Fixes
>      gitex: If no argument start browse in current workdir - PR 7554

The change was donde in 67f7d3f67c33ff87b62bfeb0edd11a1b577dc440

In gitex.cmd, if you comment line 6, it works
```
@setlocal
@for /F "delims=" %%I in ("%~dp0") do @set gitex_folder=%%~fI
@set PATH=%gitex_folder%;%PATH%
@REM If no arguments, try open current working directory
@set arg=%*
::Comment the IF line (line 6 in original bash script) and it will work
@if "%arg%"=="" SET arg=browse .
@start /B GitExtensions.exe %arg%
```

**Comment by RussKie** [comment]
@Maesla please try the fix proposed in https://github.com/gitextensions/gitextensions/pull/7711 and confirm the fix

**Comment by Maesla** [comment]
Yes, #7711 worked for me :thumbsup:

Thank you
