### ISSUE TITLE
Portable version stalling when running commit

### ISSUE THREAD

**Issue by furiousd** [gitextensions/gitextensions#7710]
## Current behaviour

When I try to commit _any_ changes to a repository, the Commit window appears normally but when I press "Commit" the process dialog just appears and nothing seems to happen. Clicking "Ok" takes me back to the Commit window and nothing has changed. Screenshot below.

The Git Command Log shows a command that is stuck running. If I run the same sequence of commands manually in a Git Bash, it works fine.  Screenshot below.

## Expected behaviour

The changes should be committed to the repository and the Commit window should close (or dialog remains open if user selected that option).

## Steps to reproduce

1. Open or create a repository.
2. Make some change to the files
3. Click "Commit" in main Git Extensions window
4. Stage files/changes, then click "Commit"

## Screenshots

![image](https://user-images.githubusercontent.com/16611367/73459865-9207a380-4345-11ea-833d-22e7bcf4ddaa.png)
![image](https://user-images.githubusercontent.com/16611367/73459971-b499bc80-4345-11ea-9ead-c69de007a0f2.png)

## Did this work in previous version of GitExtensions

I've never had this problem before using GitExtensions. I'm using a newly re-imaged Windows laptop, and this is my first time trying the Portable version of GitExtensions.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.21.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

## Diagnostics

[git log.txt](https://github.com/gitextensions/gitextensions/files/4134538/git.log.txt)

**Comment by gerhardol** [comment]
If this applies to all Git commands:
Check contents and access in ConEmu subfolder
(This can be copied from another installation)
Disabling ConEmu should work too

**Comment by furiousd** [comment]
> Disabling ConEmu should work too


This fixed my problem, thanks!

**Comment by gerhardol** [comment]
To be clear: ConEmu should not be empty in official portable builds (it may occur in private development builds that are not clean though).

**Comment by furiousd** [comment]
Okay; ConEmu was NOT empty, but I'm running a computer that's locked down tightly by GPOs and when I try running ConEmu directly I get some "Access is denied" errors.

I'm not sure how feasible it would be to detect this kind of condition in GitExtensions and provide the user with a helpful error code; as it was I was just getting a blank screen and no clear understanding of what went wrong.

**Comment by furiousd** [comment]
Also, it was weird because it seemed only _SOME_ git commands were not working. GitExtensions had no trouble reading and accessing repository contents. It was only when I tried to commit changes that I ran into a problem.

**Comment by RussKie** [comment]
> Also, it was weird because it seemed only _SOME_ git commands were not working.

Only commands that must report progress are run via ConEmu, other commands are run directly.
