### ISSUE TITLE
Comments in commit dialog are not stripped out

### ISSUE THREAD

**Issue by BaronZemo** [gitextensions/gitextensions#7712]
## Current behaviour

I have a commit template that I use that has comments in it.
```
# ----------- One-line Summary (50 chars) -------|


## ---------- Description (72 chars) ----------------------------------|


## --------------------- (72 character ruler) -------------------------|
#Testing and Instructions:
#  1.
#
## --------------------- (72 character ruler) -------------------------|
#Issue:
```

My settings have "Compose commit messages in Commit dialog" set to checked. Whenever I commit, I still get these comment lines in my commit dialog, so that I get something that looks like the attached image when I view my changes in the main browser window.

## Expected behaviour
I expect the comments to be stripped out. 

## Steps to reproduce
I modify some files. I go to the commit dialog and commit the files and I type a message in the commit dialog box inside the template that gets loaded. I commit the files. I see that the comments are kept in. This doesn't happen every time. 

## Screenshots
![image](https://user-images.githubusercontent.com/24639954/73496447-3c9bb880-437e-11ea-8783-c093d1e9ec7a.png)

## Did this work in previous version of GitExtensions

<s>Yes, version 3.00.00.4433.</s>

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4075.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Please update to the latest version, and ping back if the issue remains.

> This doesn't happen every time.

What is different when it happens and doesn't?

**Comment by BaronZemo** [comment]
This happens with the newest code as well.

> What is different when it happens and doesn't?

I wish I knew. Seems more likely to happen with me having a one line commit message.

**Comment by RussKie** [comment]
Can you please provide repro examples when it happens and when it doesn't?
So that we could investigate

**Comment by BaronZemo** [comment]
Okay I think I figured out how to reproduce it consistently.

1. Check out a commit or branch.
2. Modify a file in your repo.
3. Open the commit dialog.
4. Stage the file.
5. Exit the commit dialog.
6. Open the commit dialog.
7. In the commit dialog that has a template similar to what's posted above, enter one line of text underneath the first line of the template. 
8. Press Commit.

**Comment by BaronZemo** [comment]
A coworker reproduced the issue in 3.0.0, which goes against my initial description. I edited my original post.

**Comment by LukeOwlclaw** [comment]
This bug also often occurs when merging a branch with conflicts using GitExtensions. The log reads then:

```
Merge remote-tracking branch 'upstream/master' into featureX
; Conflicts:
;	Folder1
;	Folder/file2
```
But the lines starting with ; should not part of the log according the the [docs of commentChar](https://github.com/git/git/commit/eff80a9fd990de3605063050dae32f969ef18ba8#diff-ba92ef40c548c691816362bbdc35a613R531) which I configured to be ; instead of default #
