### ISSUE TITLE
The "check for update" modal dialog should not be "TopMost"

### ISSUE THREAD

**Issue by manuelspezzani** [gitextensions/gitextensions#7713]
## Current behaviour

The check for updates dialog goes on top of all opened windows (not only GE own forms).

## Expected behaviour

It's ok to have an update dialog on top of Git Extensions windows, but it's quite annoying to have an update dialog on top of **all** windows. Especially when the check for updates takes longer than expected.

## Steps to reproduce

- Help > Check for updates
- Switch to another application (e.g. Chrome)
- The Check for update dialog is still visible

## Screenshots

![2020-01-31 11_06_43-Window](https://user-images.githubusercontent.com/1427100/73543601-92806700-4437-11ea-891f-b5201a30bf53.png)

## Did this work in previous version of GitExtensions

Not checked

## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

## Diagnostics

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Is the form opened on top of other forms, so it visible and not lost?

**Comment by manuelspezzani** [comment]
Yes, the form is opened with ShowDialog and has an Owner so it stays on top
of other forms.

The TopMost property that I've removed forces the form to stay on top of
any other form, even those of other processes (e.g. Chrome as in my
screenshot).


Il Sab 1 Feb 2020, 22:06 Gerhard Olsson <notifications@github.com> ha
scritto:
