### ISSUE TITLE
DiffViewer displays a trailing newline which does not exist in the file

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7723]
## Current behaviour

A trailing newline is appended to every (text) diff.

## Expected behaviour

Display the end of file exactly as it is in the file.
Display the line number for the last line also if it is empty.

## Steps to reproduce

- add/remove a newline to/from the end of a file
- open FormCommit
- tick `Show nonprinting characters`

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/73725079-f56e4880-472c-11ea-9475-976343ae9ab3.png)

Hex Diff:
![grafik](https://user-images.githubusercontent.com/36601201/73725280-56961c00-472d-11ea-92db-f8c1d04a6060.png)

## Did this work in previous version of GitExtensions

not checked

## Environment

- Git Extensions 3.3.0
- Build 7034c98856ecb70f1d716d12e92652e6998c98ff (Dirty)
- Git 2.21.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.4069.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
This is how a diff is formatted, so I do not consider this a bug.
But it is confusing, especially as lines with a newline last as commented in https://github.com/gitextensions/gitextensions/pull/7824#issuecomment-592791409

**Comment by mstv** [comment]
Fixed by #9620
