### ISSUE TITLE
"Show first-parents" should show first-parents from heads of all branches in current view

### ISSUE THREAD

**Issue by johndog** [gitextensions/gitextensions#7733]
Currently "Show first-parents" only shows the first-parents of the current branch, regardless of whether "all", "current" or "filtered" branches are enabled in view.

So, this is ignored:

![image](https://user-images.githubusercontent.com/22213780/73895058-2e90e080-4833-11ea-976d-deb4538747f0.png)

When this is selected:

![image](https://user-images.githubusercontent.com/22213780/73895077-423c4700-4833-11ea-8367-259c8bf8f9a9.png)

Proposal is to have "show first-parents" honor the filtered view, showing the heads of all branches in the filter and any commits in the first parent chains from there.  The graph should continue to show where these traversals link up, ideally even if a first-parent node WRT one branch is a second-parent node WRT another.

Alternative:  Implement a new "Filter to just first-parents" option that satisfies the above request, so that users can choose which behavior they want.  The existing behavior may be valued as a quick pivot between showing just "current branch with first-parents" and whatever the branch filter is otherwise set to.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.22.0.vfs.1.1.57.gbaf16c8 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.19555.0
- .NET Framework 4.8.3921.0
- DPI 192dpi (200% scaling)

**Comment by RussKie** [comment]
Any suggestions on the actual git commands that must be executed?

**Comment by ilabutin** [comment]
I created a test repo with the following commit history:
![image](https://user-images.githubusercontent.com/1869103/79888498-72908c00-8405-11ea-9867-ee90236120ba.png)

GitExtensions uses `git log --all` when "Show first parents" option is turned off. In my example it looks like that in the command line:
```
⚡ ilabutin@gmail.com :: C:\projects\firstparenttest\ <master *> » git log --pretty=oneline --abbrev-commit --all
879d70e (HEAD -> master) master dev
beb685c (feature) new feature
25058b5 Merge branch 'fix2'
38faba6 another fix
fbffd92 (fix) Fix
1366689 Second commit
3564130 Initial commit
```

When "Show first parents" option is turned on the command line changes to `git log --first-parent`. Example in my repo:
```
⚡ ilabutin@gmail.com :: C:\projects\firstparenttest\ <master *> » git log --pretty=oneline --abbrev-commit --first-parent
879d70e (HEAD -> master) master dev
25058b5 Merge branch 'fix2'
fbffd92 (fix) Fix
1366689 Second commit
3564130 Initial commit
```

But if I combine the `--first-parent` and `--all` options then I get what I want: the "another fix" commit disappears while both branches (`master` and `feature`) are available in the log:
```
⚡ ilabutin@gmail.com :: C:\projects\firstparenttest\ <master *> » git log --pretty=oneline --abbrev-commit --all --first-parent
879d70e (HEAD -> master) master dev
beb685c (feature) new feature
25058b5 Merge branch 'fix2'
fbffd92 (fix) Fix
1366689 Second commit
3564130 Initial commit
```

So, it seems right now the GitExtensions removes any branch filtering options from the command line when "Show first parent" option is set. But it is possible to specify both branch filtering and `--first-parent`.

**Comment by ilabutin** [comment]
Now looking at the GitExtensions source code I see the `GitCommandsTests.RevisionReaderTests.BuildArguments_check_parameters` test with the following test cases:
```
       /* first 'parent first' */
        [TestCase(RefFilterOptions.FirstParent, " --first-parent ", null)]
        [TestCase(RefFilterOptions.FirstParent | RefFilterOptions.NoMerges, " --first-parent ", null)]
        [TestCase(RefFilterOptions.All, null, " --first-parent ")]
        /* if not 'first parent', then 'all' */
        [TestCase(RefFilterOptions.FirstParent, null, " --all ")]
        [TestCase(RefFilterOptions.FirstParent | RefFilterOptions.All, null, " --all ")]
        [TestCase(RefFilterOptions.All, " --all ", null)]
        /* if not 'first parent' and not 'all' - selected branches, if requested */
        [TestCase(RefFilterOptions.FirstParent | RefFilterOptions.Remotes, " --first-parent ", " --branches=")]
        [TestCase(RefFilterOptions.All | RefFilterOptions.Remotes, " --all ", " --branches=")]
        [TestCase(RefFilterOptions.Branches, " --branches=", null)]
        /* if not 'first parent' and not 'all' - *ALL* remotes, if requested */
        [TestCase(RefFilterOptions.FirstParent | RefFilterOptions.Remotes, " --first-parent ", " --remotes ")]
        [TestCase(RefFilterOptions.All | RefFilterOptions.Remotes, " --all ", " --remotes ")]
        [TestCase(RefFilterOptions.Remotes, " --remotes ", null)]
        /* if not 'first parent' and not 'all' - *ALL* tags, if requested */
        [TestCase(RefFilterOptions.FirstParent | RefFilterOptions.Tags, " --first-parent ", " --tags ")]
        [TestCase(RefFilterOptions.All | RefFilterOptions.Tags, " --all ", " --tags ")]
        [TestCase(RefFilterOptions.Tags, " --tags ", null)]
```

So it looks like it is intentional that `--all` and `--first-parent` options are not mixed together.

**Comment by gerhardol** [comment]
The tests are basically retrofitted to match the implementation, but this is likely still not trivial
Tests operating on a Git repo would be safer, but much more complex to implement

First-parent cannot be combined with bisect
https://git-scm.com/docs/git-log#Documentation/git-log.txt---first-parent

But the issue here is probably "only first parent"

**Comment by ilabutin** [comment]
As far as I get from the PR #5728 the issue was that `--first-parent` combined with `--all` produced weird revision graph which took lots of resources to render and was not 'correct' (at least visually).

Are there any good examples of sufficiently complex repositories where this can be tested? I then can try to hack the GitExtensions to allow combining those two options and then see how the revision grid is rendered.

**Comment by gerhardol** [comment]
Changed in #10172 
Only first parents is decoupled from branch filters (seem to be OK with bisect)
