### ISSUE TITLE
File permission issue with Git Extensions active

### ISSUE THREAD

**Issue by LightCC** [gitextensions/gitextensions#7734]
I've run into a strange, very specific file permission issue with Git Extensions.

When trying to delete folders in a repo, Git Extensions is causing a "file in use" permission error if that repo is open, and the main window has the latest commit selected. The file that is locked within the directories and generates the error appears to be completely random, but it happens every time.

There is no problem if:
1. Git Extensions doesn't have an open instance on that repo
2. Any commit other than the currently checked out one is selected in the main window
3. Either the "Working directory" or "Commit index" ghost commits are selected

It fails repeatably regardless of what info tab on the bottom of the main window is selected (commit, diff, file tree, etc.), just need the repo open in Git Ext and the current commit selected.

The actual error occurs when running a Python script that is deleting these folders - been working great for months, but only been working directly in the repo the last few weeks. Not sure if this is a new issue or not.

Error Message: "[WinError 32] The process cannot access the file because it is being used by another process".

It took several hours to figure this out, so I had to share! 100% repeatable.

My Git Extensions Info:
```
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)
```

**Comment by RussKie** [comment]
I'd start with looking at what locks the file, and confirming whether it
is GE or not.
I use ProcessExplorer for such tasks.

Also do you have any GE plugins that active in a background (like
background fetch)?

Or perhaps run another app that runs got in the same folder? E.g. VSCode
runs own instance of git, and it can interfere.

**Comment by LightCC** [comment]
I can try to track the task down, but this is 100% repeatable. I don't think it's a permanent lock, it seems to be temporary like there is a special case that happens. For example, I can manually delete the folder+contents with no issue in File Explorer. Also, the file that is actually locked is random - like something is looping through the repo and locking each item briefly or something like that.

Is ProcessExplorer or another program able to watch a file and log the locks that occur on it? I assume something like that would be required to document the culprit.

It could be Python causing the issue, but Git Ext has to be part of it because it of the fact that this only happens if the repo is open and the current commit is highlighted. Take either of those out of the equation, and I do not experience this. I suppose there could be a Git for Windows interaction as well...

**Comment by vbjay** [comment]
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by gerhardol** [comment]
Process Explorer: https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer
or use resmon
https://www.winhelponline.com/blog/resource-monitor-find-process-locked-file-windows-7/

You will likely get this error if GE is open, at least if you have opened the console

**Comment by RussKie** [comment]
Closing as stale
