### ISSUE TITLE
There is a problem when I choose "Simple Chinese" 

### ISSUE THREAD

**Issue by wdweidao** [gitextensions/gitextensions#7737]
hi,when the gui started,I choose "simple chinese",and it become this:
![Screenshot from 2020-02-07 20-06-34](https://user-images.githubusercontent.com/44543137/74028587-ad2d7f80-49e5-11ea-84c7-2fd220a36d6a.png)
what shoule I do？

**Comment by pmiossec** [comment]
It seems that the font used by GitExtensions to display the "simple chinese" is not available on your system.

So, probably obvious questions:
 is your ubuntu system in Chinese?
Are you able to display other application in chinese?

There was a template when you created the issue that you completely ignored. So, could you give us the maximum of information on your system and the version of GitExtensions you use?

Could you also launch GitExtensions from the command line and report any error message that appears inside it?

**Comment by wdweidao** [comment]
My ubuntu system is English.
GitExtensions :2.51.05
ubuntu version:18.04
And this is error:
![Screenshot from 2020-02-07 21-04-55](https://user-images.githubusercontent.com/44543137/74031835-85dab080-49ed-11ea-8952-7bb324f24176.png)
And i changed language to English,but it's still error,and then i download a other version 2.49,it's ok to use English,but Chinese still error

**Comment by RussKie** [comment]
This looks to me as the OS isn't supporting Chinese language.
