### ISSUE TITLE
Pull Creating Phantom Remote Branches

### ISSUE THREAD

**Issue by xpnctoc** [gitextensions/gitextensions#775]
Several related things appear to be wrong with the Pull dialog. 
1. When the pull dialog is launched, nothing is populated in the Remote Branch drop-down. I verified that I have my remotes configured properly. 
2. Having nothing selected is very counter-intuitive, so I went in there and selected the remote branch from which I wanted to pull. Whatever happened, it did NOT pull from the remote that I selected. It also created a non-existent remote branch. In more concrete terms:
   2a. I have a remote branch "origin/COMPANY_PRJ" and a local branch "MY_LOCAL"
   2b. When I pulled, I selected "origin/COMPANY_PRJ" for the remote branch.
   2c. After the pull, I had a new remote branch showing up called "origin/MY_LOCAL". It only pulled a couple dozen changes and origin/COMPANY_PRJ showed up several revisions behind MY_LOCAL.
   2d. I knew that wasn't right, so I did a hard reset of MY_LOCAL back to where origin/COMPANY_PRJ was.
   2e. I did another pull, but this time left the Remote Branch drop-down UNSELECTED.
   2f. This time, hundreds of changes were pulled in and both MY_LOCAL and origin/COMPANY_PRJ showed up at the top of the revision history.

So I don't know where the pull comes from when I select a remote branch, but it is NOT the actual remote branch that I selected. But it feels really counter-intuitive to leave the Remote Branch drop-down blank. I would expect to get an error message if I'm trying to pull from a remote and I haven't specified a remote in the pull dialog.

**Comment by lolo1337** [comment]
@KindDragon Very sorry to negro, but are you saying that PULLING changes from the remote adds a remote branch by default?
 I would expect to be able to do git pull origin master into a local branch without git extension adding a phantom remote branch origin/mybranchname
