### ISSUE TITLE
[NBug] Процесс не может получить доступ к файлу "C:\{path}\Controller.cs.BASE"

### ISSUE THREAD

**Issue by AlexanderVlassov** [gitextensions/gitextensions#7757]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.IOException: Процесс не может получить доступ к файлу "C:\{path}\Controller.cs.BASE", так как этот файл используется другим процессом.
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.File.InternalDelete(String path, Boolean checkHost)
   в GitUI.CommandsDialogs.FormResolveConflicts.ResolveFilesConflict(ConflictData item)
   в GitUI.CommandsDialogs.FormResolveConflicts.ResolveItemConflict(ConflictData item)
   в GitUI.CommandsDialogs.FormResolveConflicts.OpenMergeTool()
   в System.Windows.Forms.Control.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnClick(EventArgs e)
   в System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ButtonBase.WndProc(Message& m)
   в System.Windows.Forms.Button.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
While making a review, I made changes in code and pushed it to Stash. When the teammate fixed my review marks I checked out on his branch and made stash pop, to see the difference between my and his changes. I 've got merge conflicts and went to resolve them side-by-side. I use JetBrains.Rider diff-tool for it. So the first file, I've opened in "3 columns" view -- was like: Other's changes from the left column are equivalent to my changes from the right column. I've taken left ones and pressed "Save". Next was this exception.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.20.1.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The mergetool has probably not both .cmd and .path defined
This is no longer required in master
