### ISSUE TITLE
File History displays commits that do not contain changes in the specified file

### ISSUE THREAD

**Issue by miltonballon** [gitextensions/gitextensions#7773]
## Current behaviour

File History is showing commits that do not contain changes in the intended file. In addition, the diff viewer shows the first file of those commits, making this important tool useless.

It happens on some files only. I was not able to determine an specific pattern.

## Expected behaviour

The File History window must show only the commits that include the file in the changes.

## Steps to reproduce

1. Select a commit.
2. Click on the File Tree tab
3. Select a file and right click
4. Choose File History in the context menu
5. Verify the commits displayed in the File History window contain the file changed.

## Screenshots

![image](https://user-images.githubusercontent.com/4194279/74393708-388d8300-4de1-11ea-88f9-3733000f4990.png)

## Did this work in previous version of GitExtensions

Yes. I rollbacked until 3.0.1. 

## Environment

- GitExtensions version: 3.3.1.7897
- GIT version: 2.24.1.windows.2
- OS version: Windows 10 Enterprise (1903) OS Build 18362.592
- .NET version: 4.8.03752

**Comment by gerhardol** [comment]
To investigate, a repo with the problem should be referenced

This could be related to handling of --follow, reintroduced in #5944

**Comment by RussKie** [comment]
Please provide a repro and logs that can help investigate the issue.
