### ISSUE TITLE
Downloading from the release page returns 403: Forbidden response

### ISSUE THREAD

**Issue by blueglyph** [gitextensions/gitextensions#7778]
Trying to download any release item from this page returns a 403 error from the Amazon server:
https://github.com/gitextensions/gitextensions/releases/tag/v3.3.1

Unfortunately, it is not possible to upload a screenshot here either, but the text is as follows:

> This site can’t provide a secure connectiongithub-production-release-asset-2e65be.s3.amazonaws.com sent an invalid response.
> Try running Windows Network Diagnostics.
> ERR_SSL_PROTOCOL_ERROR

Windows 10 Pro, using Chrome 80.0.3987.106 (Official Build) (64-bit)

**Comment by vbjay** [comment]
Not anything we can do about that. That is a GitHub to Amazon web services issue.

**Comment by blueglyph** [comment]
Indeed! That's weird.
I'm closing the issue.
