### ISSUE TITLE
Allow custom shell for toolbar button

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7782]
## Feature description

Extend the toolbar button to start different shells (customizable) including VS Code.
(Related to #7523. Perhaps parts of #7678 can be reused for this.)
![grafik](https://user-images.githubusercontent.com/36601201/74612071-45bcb180-5102-11ea-86b5-8efcaf1c3627.png)

**Comment by pmiossec** [comment]
Would be good indeed 😉 #6460
