### ISSUE TITLE
"Ctrl+Enter" creates commit when Enter is released, not pressed

### ISSUE THREAD

**Issue by nyanpasu64** [gitextensions/gitextensions#7791]
## Current behaviour

If you open Git Extensions's commit dialog, it commits when you *release* Enter with Ctrl held. This is counterintuitive behavior and acts differently from most other keyboard shortcuts, which has caused me to make mistakes.

I often fail to commit, because I release Ctrl before releasing Enter.

I sometimes accidentally commit, when I press Enter, then press Ctrl (for Ctrl+V) before releasing Enter.

## Expected behaviour

It should commit if you *press* Enter with Ctrl held.

## Steps to reproduce

- Open commit dialog (eg. Ctrl+Space) and focus the commit message field.
- Press Enter, Ctrl, and release Enter. It commits but shouldn't.
- Press Ctrl, press Enter. It doesn't commit as soon as you key-down, but it should.
- Release Ctrl then Enter. It doesn't commit at all, even though you clearly pressed Enter while Ctrl was held.

## Screenshots

I didn't take any. Maybe a screen recording with keyboard input viewer would be helpful.

## Did this work in previous version of GitExtensions

Not sure.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by mast-eu** [comment]
I can confirm the issue and will look into it.

> Maybe a screen recording with keyboard input viewer would be helpful.

Thanks, but I don't think it's necessary. You already provided a very good and complete description.
