### ISSUE TITLE
Commit dialog doesn't reload changes upon receiving focus

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#7805]
## Current behaviour

Split from #7622. While the _Refresh dialog on form focus_ works correctly when switching to the Commit dialog from a different application, it doesn't work when switching between GE windows. Since it is now possible (and useful) to create commits (especially fixups) from the File History dialog, the Commit dialog might, due to this bug, show an out-of-date state until manually refreshed.

## Expected behaviour

The Commit dialog should reload changes even when just switching to it from a different GE window, like File History.

## Steps to reproduce

(0. Make sure the _Refresh dialog on form focus_ option is on)
1. Make some changes in a repository
2. Open Commit dialog
3. On the first changed file, click View File History
4. A File History window opens
5. Pick an existing commit and press Ctrl+X
6. A new Commit dialog opens with the fixup message filled in
7. Add all the changes and commit the fixup
8. Close both the second Commit dialog and the File History dialog

The first Commit dialog is now focused again but it still shows the changed file even though it has already been committed.

I think this is due to the fact that the dialog contents is only reloaded in `OnApplicationActivated` which is in turn only called when the `WM_ACTIVATEAPP` message arrives - and that only occurs when switching from a _different_ application window.

## Did this work in previous version of GitExtensions

I don't think so.

## Environment

- Git Extensions 3.3.0
- Build 0c3fe90bad6505b2d5c9f52d297364ffad3b14e4
- Git 2.25.1.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
This is a drawback from the intentional change from ``WM_FORMACTIVATE` to `WM_ACTIVATEAPP` -- in order to not reload after popup messages and dialogs like the FindForm.
Another user has opened a duplicate issue recently -- with the same use case.
I don't want to revert this change. I'd rather run the File History in an own GE instance. Thoughts?

**Comment by RussKie** [comment]
I have observed a similar behaviour by modifying a file with an inbuilt
editor (via F4) invoked from the FormCommit, the form doesn't refresh its
content.

May be it is possible to set a folder/file watcher over the repo while the
FormCommit is open.
Or (!) replace WM_ACTIVATEAPP with a call to git (i.e. git status)?

**Comment by vbjay** [comment]
It does this but you have to turn the o0yion on.

**Comment by RussKie** [comment]
I have the option on. But because I'm _in_ the app, it doesn't trigger
refresh

**Comment by crypto-rsa** [comment]
@mstv thank you!
