### ISSUE TITLE
\Setup\BuildInstallers.cmd doesn't exist

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#7806]
According to wiki https://github.com/gitextensions/gitextensions/wiki/How-To:-build-instructions

```
Building the installer

    install Visual Studio C++ featureset including "Visual C++ ATL for x86 and x64"
    Run \Setup\BuildInstallers.cmd
```

The file \Setup\BuildInstallers.cmd doesn't exist: https://github.com/gitextensions/gitextensions/tree/master/Setup

**Comment by RussKie** [comment]
In the current master we're overhauling the build pipeline, and the work is
in progress.

A portable build can now be built with `build.cmd -publish`. There is
currently no scripted way to generate an msi.

**Comment by NN---** [comment]
Thanks.
Waiting for the new instructions to build MSI.

**Comment by gerhardol** [comment]
Now updated
https://github.com/gitextensions/gitextensions/wiki/How-To%3A-build-instructions#package-app

**Comment by RussKie** [comment]
The instructions are for packaging a portable build though, msi support is yet to come.
