### ISSUE TITLE
Selecting all commits while having diff pane open crashes git-extensions

### ISSUE THREAD

**Issue by ITR13** [gitextensions/gitextensions#7812]
## Current behaviour

App stops responding, making any further input impossible until it finishes computation.

## Expected behaviour

App either automatically cancels after a certain amount of time or shows a cancelable progress bar.
Alternatively not blocking the main thread, allowing for selecting a single commit to interrupt the current computation and instead show the diff of that.

## Steps to reproduce

1. Open a project with a lot of commits.
2. Open the "Diff" panel
3. Click on any commit.
4. Press ctrl+a

## Screenshots

N/A

## Did this work in previous version of GitExtensions

Unknown

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

## Diagnostics
```
$ git rev-list --all --count
1414
```
```
$ git for-each-ref --format="%(refname)" refs/ | cut -d"/" -f2 | uniq -c
      1 heads
      7 remotes
```
```
$ git count-objects -vH
count: 122
size: 5.22 MiB
in-pack: 44453
packs: 2
size-pack: 1.72 GiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```
```
$ du -h -d 1 .git
41K     .git/hooks
1.0K    .git/info
10K     .git/logs
1.8G    .git/objects
3.0K    .git/refs
1.8G    .git
```

**Comment by gerhardol** [comment]
Changed in master, if more than 4 selected only show diff first -> selected
