### ISSUE TITLE
[NBug] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by sakataa** [gitextensions/gitextensions#7819]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
```

## Additional information
Downloading to slow

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.21.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of  #7613 

Fixed in #7576

Please update to 3.3.1
