### ISSUE TITLE
cannot resize Compare to branch window

### ISSUE THREAD

**Issue by tomeberhard** [gitextensions/gitextensions#7822]
when trying to compare branches with long branch names, the 'Compare to branch' dialog should be resizeable so that the full branch names become visible.

How to reproduce issue:
1) create 2 branches with the first 35 characters in common
branch 1: branch-0123456789-0123456789-0123456789-A
branch 2: branch-0123456789-0123456789-0123456789-B
2) right click on branch 1
3) compare, compare to branch
4) the "Compare to branch" dialog comes up
5) select "Local branch" radio button
6) in the dropdown, look for branch 2, but the name of the branches are cut off because the window is not resizeable, even though it looks like it should be.

I could change the 2nd branch name, but our CI system requires that the branch name must match the first N characters of the bug report, so I'd like to be able to use long branch names that differ at the end (-v1, -v2). 
Other work arounds exist, so this isn't super urgent. (temporarily rename branch2, then rename it before push)

**Comment by gerhardol** [comment]
The size should be increased some if re-sizable is tricky
The long term solution should be to multi select in the left panel

![image](https://user-images.githubusercontent.com/6248932/75585446-71308c00-5a72-11ea-9639-474aac515701.png)

**Comment by tomeberhard** [comment]
Thank you everyone who worked on this! 💖
