### ISSUE TITLE
KDiff not installed after installing GitExtensions

### ISSUE THREAD

**Issue by Mikilll94** [gitextensions/gitextensions#7829]
## Current behaviour

When install GitExtensions KDiff is not installed. And there is no info how to configure KDiff.

## Expected behaviour
When installing GitExtensions KDiff should also be installed like it was before.

If this was intended that KDiff should not be installed when installing GitExtensions, it should be documented how to configure it, because KDiff is the most popular tool to resolve conflicts in Git.

## Did this work in previous version of GitExtensions

Yes, in previous versions of GitExtensions KDiff was installed during installation.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4121.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
KDiff3 was dropped from GE to decrease the download size and due to it is being considered a little outdated, it is hardly the most used diff tool.

http://kdiff3.sourceforge.net/

Select the difftool in Settings
https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#git-config

**Comment by Mikilll94** [comment]
@gerhardol 
If KDiff3 is considered outdated, what is the best alternative to it? I am curious.

**Comment by mstv** [comment]
Feel free to continue to use KDiff3. GE just does not install it anymore because many users have chosen different tools.
There is no "best" alternative. It depends on your needs, e.g. configurability and on how much familiarization effort and money you want to spend. Just search for "three way merge" or "3-way merge".
