### ISSUE TITLE
Text Scaled Incorrectly in Commit box

### ISSUE THREAD

**Issue by Pro100AlexHell** [gitextensions/gitextensions#7830]
## Screenshot
box height is incorrect (text is bigger than box)
http://prntscr.com/r9knoy
![image](https://user-images.githubusercontent.com/4403806/75643425-23df3500-5c93-11ea-9bfb-3dc5b5a72571.png)

when I click into it - it scrollable and selectable
http://prntscr.com/r9kqqj
![image](https://user-images.githubusercontent.com/4403806/75643434-28a3e900-5c93-11ea-9d13-40e8dadab3dc.png)

## Did this work in previous version of GitExtensions
I have used old gitext 2.4 version
after update I see rescaled UI (good), but wrong scaling in this place

## Environment
- GitExtensions version: 3.3.1.7897
- GIT version: 2.12.1
- OS version: Win 7
- .NET version: 4.6.1055.0
- 143 DPI = 149% scaling in windows
- Resolution: 1920x1080

## note
some programs (except gitext) also have scaling issues in some places, but correctly overall

**Comment by RussKie** [comment]
This is a nasty one. ...and you have a very weird scaling settings

**Comment by Pro100AlexHell** [comment]
I have this scale settings by a reason
- smaller (140% for example) - and all controls (in may progs) is very small
- bigger (150% for example) - and all controls (in may progs) is very big
.. it's intermediate
