### ISSUE TITLE
New code font

### ISSUE THREAD

**Issue by s-s-a** [gitextensions/gitextensions#7834]
Please, add new font [JetBrains Mono](https://www.jetbrains.com/lp/mono/) in addition to Courier, Lucida Console, Consolas, etc. for source code

**Comment by pmiossec** [comment]
From what I know, GitExtensions don't provide fonts.
It uses the one of your system.
If you installl JetBrains Mono, you will be able to use it. I personally use [FiraCode](https://github.com/tonsky/FiraCode) without problem.

**Comment by s-s-a** [comment]
List of code fonts is limited/fixed (6 fonts) and not contains JetBrains Mono.

**Comment by RussKie** [comment]
Your post makes no sense, sorry.

**Comment by s-s-a** [comment]
![image](https://user-images.githubusercontent.com/46567412/75677328-445fbd00-5c9c-11ea-94b0-377a62d659b1.png)

**Comment by s-s-a** [comment]
> Your post makes no sense, sorry.

Quoted post is  GitHub AI result. 

See picture and try choice code font.

**Comment by pmiossec** [comment]
@s-s-a I still don't understand what you expect from us.

That we install new fonts in your system during GitExtensions install?

Because I have installed new font and I can select it from the settings:

![image](https://user-images.githubusercontent.com/460196/75678975-0d36df00-5c8f-11ea-9eb1-b4dac6507afb.png)

You could install the font yourself....

**Comment by pmiossec** [comment]
>That we install new fonts in your system during GitExtensions install?

If that's the case, update the issue title and description to be clearer so that we could follow it better...

**Comment by vbjay** [comment]
It sounds like they want us to change the font GitHub uses.

**Comment by s-s-a** [comment]
> @s-s-a I still don't understand what you expect from us.
> That we install new fonts in your system during GitExtensions install?
Of courc, no.
> Because I have installed new font and I can select it from the settings:
I have installed new font and I can't  select it from settings "Code font". But I can select it from setting "Monospace font". That you can see on my picture.
> You could install the font yourself....
I know. See previous parpraph.

**Comment by s-s-a** [comment]
> It sounds like they want us to change the font GitHub uses.

NO. See value of settings "Code font" and "Monospace font" on my picture. Count  items in both font lists. Compare.

**Comment by pmiossec** [comment]
I better understood the problem.

I looked at the code and indeed, this dialog filter the font to show only "fixed pitch fonts" also called "monospace fonts" (property `FixedPitchOnly` set to true).

But after installing the font, I can't reproduce and I am able to select the font:

![image](https://user-images.githubusercontent.com/460196/75687348-f51a8c00-5c9d-11ea-942a-de502ae27d64.png)

**Comment by s-s-a** [comment]
End alarm! :)
I found the culprit of this problem.
After some torture :) he admitted that he gave me the old font release for installation, just with some properties errors.
Current version 1.0.3, не gave me 1.0.0
Close issue
Sorry for the trouble.
