### ISSUE TITLE
Commit dialog F3 shortcut for "open with difftool" is ignored when changed file size is "large"

### ISSUE THREAD

**Issue by roberthardy** [gitextensions/gitextensions#7841]
## Current behaviour

1. Select a changed file in the commit dialog that is over the file size threshold that triggers the "This file is x MB. Showing large files can be slow. Click to show anyway" prompt.
1. Hit the "Open with difftool" shortcut key (F3).
1. Nothing happens. However, when I right click on the file and click "Open with difftool" from the context menu the difftool is launched as expected.

## Expected behaviour
The difftool is launched for large files when I hit F3.

## Steps to reproduce

See **Current behaviour**. This behaviour can be reproduced consistently.

## Screenshots

![image](https://user-images.githubusercontent.com/4189019/75875739-30d36400-5e0c-11ea-8097-9d34154ea51a.png)

## Did this work in previous version of GitExtensions
I don't know whether this has ever worked as expected but I have experienced the behaviour in previous versions (sorry I can't be more specific).

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The codepath to invoke the difftool differs when using hotkey and menu items, it has probably always been like this.

I created a PR, please try the portable build
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/31639625/artifacts

**Comment by RussKie** [comment]
Thank you for the follow up
