### ISSUE TITLE
Plugins are extremely slow to load

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#7842]
## Current behaviour

Plugins takes more than 1 minutes to load in current `master`

## Expected behaviour

- Plugins are loaded quickly
- GitExtensions stop to try to load files that are not plugins dlls (but dll dependencies)

## Steps to reproduce

* Build `master` branch
* Debug the application
* See that the `Plugins` menu is empty during a long time

## Did this work in previous version of GitExtensions

Yes. 3.3.1.

## Environment

- Git Extensions 3.3.0
- Build 513b9990cdf2f8262f74837780c4c39e5b409986 (Dirty)
- Git 2.25.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 192dpi (200% scaling)

## Diagnostics

It's a bad side effect of the Arcade build where now the plugins are in there own directories with all their dependencies (even if it's a good decision).

The code that try to find the dlls of plugins to load `var pluginFiles = PluginsPathScanner.GetFiles(defaultPluginsPath, userPluginsPath);` [Source here](https://github.com/gitextensions/gitextensions/blob/master/Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs#L57) in retrieving more than 2500 files (plugins dlls and all there dependencies) and so GitExtensions take a lot of time to try to load them

A very quick and not satisfying fix like that is solving the problem (251 files trying to be loaded instead of more than 2500):

```csharp
            var pluginFiles = PluginsPathScanner.GetFiles(defaultPluginsPath, userPluginsPath)
                .Where(f => !f.Name.StartsWith("System") && !f.Name.StartsWith("Microsoft"))
                .Distinct(new FileInfoEqualityComparer());

    internal class FileInfoEqualityComparer : IEqualityComparer<FileInfo>
    {
        public bool Equals(FileInfo x, FileInfo y)
        {
            return x.Name == y.Name;
        }

        public int GetHashCode(FileInfo obj)
        {
            return obj.Name.GetHashCode();
        }
    }
```

## Proposed solution

Obliged plugins dll names to start with `GitExtensions.` (the ones coming from the PluginManager) or end with `Plugin` (the ones provided with GitExtensions`) and try to load only these files.

**Comment by RussKie** [comment]
Good catch!

We get the gazillion of files due to dependency on .NET Standard... I think the problem will disappear once we migrated to .NET Core.

I think your proposal is totally sensible:

> ```cs
>             var pluginFiles = PluginsPathScanner.GetFiles(defaultPluginsPath, userPluginsPath)
>                 .Where(f => !f.Name.StartsWith("System.") && 
>							  !f.Name.StartsWith("Microsoft.") &&
>							  !f.Name.StartsWith("netstandard."))
>                 .Distinct(new FileInfoEqualityComparer());
> ```




> Obliged plugins dll names to start with `GitExtensions.` (the ones coming from the PluginManager) or end with `Plugin` (the ones provided with GitExtensions`) and try to load only these files.

I can see a value in this proposal, but there may be existing plugins that may not necessarily conform.
I'm ok with introducing a naming convention. 
If I were to chose, I'd prefer `GitExtensions.`.

Then we could re-write the above as:
> ```cs
>             var pluginFiles = PluginsPathScanner.GetFiles(defaultPluginsPath, userPluginsPath)
>                 .Where(f => f.Name.StartsWith("GitExtensions."))
>                 .Distinct(new FileInfoEqualityComparer());
> ```
