### ISSUE TITLE
Fail to open repository while launching git extensions from git custom command

### ISSUE THREAD

**Issue by kenmux** [gitextensions/gitextensions#7844]
I used to launch git extensions in bash from git custom command `git ext` with the settings in gitconfig:

```
[alias]
	ext = "!f() { "D:/Program Files/GitExtensions/GitExtensions.exe" "$@" & }; f"
```

If there's a git repository in the work directory of bash, it will open it.

## Current behaviour

Now it opens "Recent Repositories" instead.

## Expected behaviour

Open the git repository in the work directory of bash.

## Did this work in previous version of GitExtensions

It works in **3.2.1.6628**, but failed in **3.3.0.7719 and above**.

## Environment

- GitExtensions version: 3.3.0.7719, 3.3.1.7897
- GIT version: 2.24.0
- OS version: Windows 7 x64
- .NET version: 4.7.3468.0
- Git Extensions 3.3.1.7897

**Comment by gerhardol** [comment]
This was intentionally changed to be able to open GE with the dashboard also if you started it from a repo which was not possible before (and not how it was documented)

Add browse to the commandline or in the alias

**Comment by kenmux** [comment]
Sorry, I'm not very familiar with that.

It turns out that git alias mentioned has no effect at all.

This way is refer to [this outdated guide](https://www.danrigby.com/2012/03/22/how-to-launch-git-extensions-from-git-bash-on-windows/) posted in 2012.

So the bash script named as **git-ext** should be:

```
#!/bin/sh

"D:/Program Files/GitExtensions/GitExtensions.exe" browse "$@" &
```

Thanks for your advice!

**Comment by kenmux** [comment]
By the way, I found one more thing today:

If you update git extensions via "Help->Check for update", then the install path is set to default ignoring the custom settings.

I'm too lazy to create a new issue...
