### ISSUE TITLE
[NBug] 尝试执行未经授权的操作。

### ISSUE THREAD

**Issue by qwzhang01** [gitextensions/gitextensions#7847]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.UnauthorizedAccessException: 尝试执行未经授权的操作。
   在 Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   在 Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   在 Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   在 GitUI.WebBrowserEmulationMode.SetBrowserFeatureControl()
   在 GitExtensions.Program.RunApplication()
   在 GitExtensions.Program.Main()
```

## Environment
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
- Git 2.22.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
First time the stack trace appears
Old version, please upgrade

**Comment by gerhardol** [comment]
Duplicate of #7918 

PR #7921
