### ISSUE TITLE
Add possibility to hide commit info window

### ISSUE THREAD

**Issue by dalbocha** [gitextensions/gitextensions#7848]
## Feature description

Please add the possibility to completely hide commit info window. In the majority of cases I do not need it at all. At the moment it is possible to place it on the left/right/below of the commit tree. That is is shown below it stays on on first place before other tabs and hides view to "Diff" tab, which I need most.

![Picture](https://user-images.githubusercontent.com/19868672/76062350-cba37e00-5f85-11ea-9c98-f7ce1402a88e.jpg)

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.1.windows.1
- Microsoft Windows NT 10.0.14393.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Use the second button
![image](https://user-images.githubusercontent.com/4403806/76090362-888ded00-600f-11ea-8308-78f67da37ebd.png)

**Comment by RussKie** [comment]
We will not be doing that.

**Comment by gerhardol** [comment]
#5721 propose that the Commit tab is removed for artificial commits, or commitinfo/diff is merged as in gitk
I still support that

But GE do not need more options

**Comment by TamaMcGlinn** [comment]
@dalbocha the ability to re-order the panes would be enough it seems.

I second this issue though; it is completely useless to see 'commit info' when there is no commit, and essential to be able to see the diff for unstaged changes.

**Comment by mstv** [comment]
This panel can be moved beside the Revision Grid making it visible along with e.g. the diffs:
![grafik](https://user-images.githubusercontent.com/36601201/77471525-bac28b80-6e12-11ea-979a-3576ab3bee66.png)

The functionality of FormCommit more and more is integrated into the main window.
The CommitInfo panel could be used to input the commit message then.
