### ISSUE TITLE
Fail to load plugin assembly dependencies (here `RestSharp`)

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#7855]
## Current behaviour

The version of the `RestSharp` required by the `Git.hub` project end up in the main folder of GitExtensions (because the `Git.hub` is a dependency of the `GitUI` project).
And because of that it prevent the loading of the `RestSharp` dependency of the `BitBucket` and `JiraCommitHintPlugin` plugins because:

* the versions are different
* it tries to find the assemblies in the main folder before the plugin folders

I imagine that these plugins are broken for that reason even if I can't verify because I don't use these them

I think **it shows that we have a problem with loading plugins dependencies when the same dependency with a different version is used by the main application** (or another plugin with the same dependency that appears before in the `Probing` property of the `.config` file)

## Expected behaviour

The `restsharp` assemblies of the plugins loads without problem

## Steps to reproduce

- Enable all `Common language Runtime Exceptions` in Exceptions Settings in VisualStudio (except `TaskCanceledException` because that makes the debugging impossible)
- Run the application in debug.

## Did this work in previous version of GitExtensions

I don't know.

## Environment

- GitExtensions version: `master`

## Diagnostics

???
Align versions? Use binding redirects?

**Comment by RussKie** [comment]
I don't think it is possible in .NET Framework (or .NET Core for that matter) to load multiple versions of the same assembly.

As a workaround - would unifying the version of RestSharp across the solution solve the issue?
