### ISSUE TITLE
[NBug] Ссылка на объект не указывает на экземпляр объекта.

### ISSUE THREAD

**Issue by AlexanderVlassov** [gitextensions/gitextensions#7857]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в GitUI.FileStatusList.FileStatusListView_DoubleClick(Object sender, EventArgs e)
   в System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   в System.Windows.Forms.ListView.WndProc(Message& m)
   в GitUI.UserControls.ExListView.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
1) reopened solution in IDE (Rider)
2) opened in GitExtensions the last commit in my branch
3) clicked sequentially on changed files in the opened window
4) with the click on the last file in the tree - exception occurred
5) it seemed to me that last click I made - was a little bit lower than the file row

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.20.1.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Can you consistently repro the issue?

**Comment by AlexanderVlassov** [comment]
No. It happened suddenly once and now works fine ).

**Comment by gerhardol** [comment]
No other occurrence reported.
Likely cause (both from descriptin and the few lines of code in the function) is that SelectedItem is no longer selected
