### ISSUE TITLE
Wrong diff in stash window

### ISSUE THREAD

**Issue by ThatScar** [gitextensions/gitextensions#7866]
## Current behaviour

From the Manage stashes... window, Stash diffs occasionally do not reflect what is stored in the cache.
When multiple stash entries are created, that have different changes to the same file, sometimes a stash entry in the Manage Stashes... window will show a diff from an another stash entry.

While searching whether this was already documented, I've stumbled upon Issue [#2007](https://github.com/gitextensions/gitextensions/issues/2007) from 2013, which was about caching and it mentioned that restarting the program made it go away. It works with my issue as well! It may be a related issue.

## Expected behaviour

Each stash entry should show the diff in accordance to its changed files.

## Steps to reproduce

Just keeps happening randomly but I cannot yet reproduce it at will.
Common actions I've noticed that may have been related to these issues:
-giving custom names to the stash entries
-resetting branches and then creating commits with the same name (and having a stash on the commit that no longer belongs to any branch and was reset)
-dropping stashes

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.21.0.windows.1 (recommended: 2.23.0 or later)
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
GE tries to cache diffs, to speed up handling
stashes are identified by names like "stash@{0}" and should not be cached
This should be handled by #7926 that always resolves the stash name

**Comment by gerhardol** [comment]
Introduced in GE 2.51

**Comment by gerhardol** [comment]
Incorrect  diff for files in Index fixed in #7938
