### ISSUE TITLE
error cloning repo

### ISSUE THREAD

**Issue by oldgitcodemonkey** [gitextensions/gitextensions#7871]
## Current behaviour

error thrown when cloning repo

filename in tree entry contains backslash

the is file was removed from the repo from the web client

## Expected behaviour

removing file should fix issue

## Steps to reproduce

clone repo

## Screenshots

![image](https://user-images.githubusercontent.com/43357113/76792916-f5497a00-67bb-11ea-839a-24278009fed0.png)

## Did this work in previous version of GitExtensions

unknown

## Environment

- GitExtensions version:
- GIT version:  2.3.1
- OS version:  10 latest update
- .NET version: 4.6

**Comment by gerhardol** [comment]
Git 2.3.1 is too old to be supported with GE
The error message is from Git, not GE
