### ISSUE TITLE
Translation update issues

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7873]
## Current behaviour

The CI build checks for up-to-date `English.xlf`.
But its update is difficult:
- [ ] `TranslationApp` fails because it tries to write the file to the non-existing directory
  `artifacts\bin\TranslationApp\Debug\net461\Translation`
- [ ] The file is generated with a `GitExVersion` which is not accepted by the CI build.
  manual patch required:
``` patch
- <xliff xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" GitExVersion="3.3.0">
+ <xliff xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" GitExVersion="4.0.0">
```
- [ ] Does `.tools\transifex\UpdateLocalEnglishTranslations.ps1` work?
- [ ] Is `.tools\transifex\` the intended directory for this script?

## Expected behaviour

It is easy for developers to update the translation file.

**Comment by RussKie** [comment]
> [ ] `TranslationApp` fails because it tries to write the file to the non-existing directory
> `artifacts\bin\TranslationApp\Debug\net461\Translation`

This is due an incorrect variable
```diff
diff --git a/GitExtensions/Project.Loc.targets b/GitExtensions/Project.Loc.targets
index d5f0b41a7..ea0feded2 100644
--- a/GitExtensions/Project.Loc.targets
+++ b/GitExtensions/Project.Loc.targets
@@ -42,7 +42,7 @@
     <!-- 2. Run TranslationApp.exe to update English*.xlf -->
     <Exec Command="$(_TranslationCommand)"
           LogStandardErrorAsError="false"
-          WorkingDirectory="$(GitExtensionsOutputPath)"
+          WorkingDirectory="$(_GitExtensionsOutputDir)"
           IgnoreExitCode="true">
       <Output TaskParameter="ExitCode" PropertyName="_TestErrorCode" />
     </Exec>
```
The app was working in a folder one level up, and couldn't find assemblies it was looking for, and defaulted to a fallback path.

**Comment by RussKie** [comment]
> * Does `.tools\transifex\UpdateLocalEnglishTranslations.ps1` work?

No, should be removed

**Comment by RussKie** [comment]
> * The file is generated with a `GitExVersion` which is not accepted by the CI build.

I don't believe `GitExVersion` is used at all. I can only guess that at some point it may have been intended to load only translations matching the version.
Perhaps it may some merits to it, but at the moment I propose we just set it to an empty string. If a user trashes the translations, their choice.
