### ISSUE TITLE
Tab "Diff" is not updated at changes for artificial commits

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7875]
## Current behaviour

The tab "Diff" is not updated neither on `WM_ACTIVATEAPP` nor by the `FileSystemWatcher`.

## Expected behaviour

automatic update

## Steps to reproduce

- change a file
- switch to GE -> `Commit` button is updated but not `FileStatusList`
- hit `F5`
- change the same file
- switch to GE -> `FileDiff` shows the old diff

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/76902628-bc350680-689c-11ea-9023-ba8d7f9083d1.png)

## Did this work in previous version of GitExtensions

I guess yes, must have been some time ago.

## Environment

- Git Extensions 3.3.0
- Build d25652c1254aad8f0fa1cdbb7f8ca9b0ef560a56
- Git 2.24.1.windows.2
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Artificial commits have never updated the tab automatically from background changes (but some explicit commands in the tab). I am not sure I want that, to disrupt my current status.

I want to have a refresh button for FileStatusList that are updated at changes - RevDiff gets the update already.  (Requires that a panel is added to the top part, I briefly looked at this some time ago.)

**Comment by mstv** [comment]
I would re-use the regarding FormCommit setting to control whether to update automatically.

**Comment by RussKie** [comment]
> I would re-use the regarding FormCommit setting to control whether to update automatically.

I guess that makes sense
