### ISSUE TITLE
[NBug] Die Sammlung wurde geändert. Der Enumerationsvorgang kann m...

### ISSUE THREAD

**Issue by kaesaecracker** [gitextensions/gitextensions#7905]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

The application crashed after cherry-picking a commit successfully.

## Expected behaviour

The application does not crash

## Steps to reproduce

Was not able to

## Error Details

Translation: System.InvalidOperationException: Collection was modified; enumeration operation may not execute

```
System.InvalidOperationException: Die Sammlung wurde geändert. Der Enumerationsvorgang kann möglicherweise nicht ausgeführt werden.
   bei System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   bei System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   bei GitUI.UserControls.RevisionGrid.RevisionDataGridView.SelectRowsIfReady(Int32 rowCount)
   bei GitUI.UserControls.RevisionGrid.RevisionDataGridView.<BackgroundThreadEntry>g__UpdateRowCount|48_2(Int32 row)
   bei GitUI.GitUIExtensions.<InvokeAsync>d__12`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
I cherry-picked a commit

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by kaesaecracker** [comment]
Removed warning in header, template is filled out

**Comment by gerhardol** [comment]
Duplicate of #7067 

No known way to reproduce

**Comment by pmiossec** [comment]
>No known way to reproduce

Bad timing when using background fetch (with refresh?)?

**Comment by gerhardol** [comment]
> Bad timing when using background fetch (with refresh?)?

Something like that
There are 7 similar reports, not related to any version (this is not changed since 3.0 what I know).
A little more info in #7117
