### ISSUE TITLE
.gitmodules "ignore" setting

### ISSUE THREAD

**Issue by Unlockener** [gitextensions/gitextensions#7906]
## Current behaviour

Adding "ignore = dirty" or "ignore = all" to .gitmodules does not have the desired effect. Submodule is not ignored and is visible in the commit dialog.  However, typing "git status" to console works as expected - submodule is ignored.

## Expected behaviour

Ignore submodule and do not show it in the commit dialog.

## Steps to reproduce

1. Add submodule to your project
2.  Add ignore = dirty or ignore = all to .gitmodules
3. Change something in the submodule
4. You should be able to see changes in the superproject despite step 2.

## Screenshots
![image](https://user-images.githubusercontent.com/30054007/77781419-d5d10d80-7055-11ea-85d7-d4f47fe348e0.png)
![image](https://user-images.githubusercontent.com/30054007/77781486-ef725500-7055-11ea-9ff2-99941a81c8a4.png)

## Did this work in previous version of GitExtensions
I do not know, but I guess it hadn't worked.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4121.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
GE uses git-diff for the diff tab (you can compare to any commit, not just the index) and git-status to get the status for worktree/index artifificial commits. 

The diff tab is not presenting the submodule as changed for me (I suspect that the screenshot is incorrect).
For the git-status, the status is explicitly overridden with --ignore-submodules=none, changed in #4760. There were some previous discussions too, that I do not find now.

**Comment by Unlockener** [comment]
I was not talking about diff tab (everythings look good there), but about uncomitted changes and the commit dialog. To be more precise: my changes in the submodule were some added files. Also what do you mean by "screenshot is incorrect"?

**Comment by gerhardol** [comment]
> I was not talking about diff tab (everything looks good there), but about uncomitted changes and the commit dialog.

I missed that.

git-status is used in the commit dialog, as for the status, so it is the same.

**Comment by s-sixteen** [comment]
Hello, I am also affected by this problem.
The culprit is #4760, specifically this part:
> The default for git-status is --ignore-submodules=none so using this as default is not a change for other commands

This is not true. Based on the [docs](https://git-scm.com/docs/git-status), the default value is _all_
```
--ignore-submodules[=<when>]
           Ignore changes to submodules when looking for changes. <when> can be either "none", "untracked", "dirty" or "all",
           which is the default
```

**Comment by gerhardol** [comment]
> This is not true. Based on the docs, the default value is all

The default is 'none' if no argument at all is given.
The default here must be 'none'. If --ignore-submodules is not set, then no user will ever see any changes.

In this case it may be possible to see submodule status, ignore the user setting but honor submodule specific overrides in .gitmodule (and <name>.ignore) by providing the option as a configuration parameter instead.
-c diff.ignoreSubmodules=none

**Comment by s-sixteen** [comment]
It seems to me this statement is ambiguous:
> The default is 'none' if no argument at all is given.

It could mean the default value of the command line parameter is 'none' if the command looks like
`git status --ignore-submodules` 
(in this case, default is 'all', as stated in the docs, meaning all submodules are ignored)

or

that the default value of the ignore-submodules logic in git is 'none' if you just run plain `git status`
(also not true, the ignore settings from .gitmodules are actually honored [source of this bug])

or

that the optional parameters to methods such as [GitStatus](https://github.com/gitextensions/gitextensions/blob/85fde1ccf1128c7253ee52b9879a8473ac64e9a7/GitCommands/Git/GitModule.cs#L2649) have their ignoreSubmodulesMode parameter set to 'none'
(in this case, it should probably be changed)

---
Whichever is the case, you don't have to set it to 'none' to see changes in the repo. The simplest thing to do here is not set the  --ignore-submodules parameter at all when running git status

**Comment by gerhardol** [comment]
The second alternative.

But 'none' still need to be supplied in case the user has configured diff.ignoreSubmodules to something else than none
git-status is used in some other situations too
The biggest challenge though with changing this is to setup a test case..

**Comment by gerhardol** [comment]
A pull request is created.
There are currently no portable builds but @Unlockener and @s-sixteen can you please review?

**Comment by Unlockener** [comment]
I am not acknowledged enough with the codebase to review your code changes. From what I can see in the gif you provided, it looks it works alright. What I noticed however (in the gif and then I tested it), is that the diff tab is not immediately refreshed when .gitmodules is changed, but one has to leave and reenter repository to see the effect. This is more of a nuisance than a bug (maybe it is even desired behavior, I don't know) and it does not bother me.

**Comment by gerhardol** [comment]
> What I noticed however (in the gif and then I tested it), is that the diff tab is not immediately refreshed when .gitmodules is changed, but one has to leave and reenter repository to see the effect

See #7825  
It would be annoying too if the contents for artificial commits were updated without any warning

**Comment by s-sixteen** [comment]
@gerhardol
It took me some time to get to this and build GE, sorry. I can confirm your PR fixes this bug
