### ISSUE TITLE
[NBug] Attempted to perform an unauthorized operation.

### ISSUE THREAD

**Issue by NoahLerner** [gitextensions/gitextensions#7918]
## Current behaviour

Fresh install, Git Extensions v3.3.1.7897 doesn't launch. I do not have admin rights on my work laptop.
I tried installing for all users, then tried installing just for my user. Both throw the same exception.

The previous build, v3.3.0.7719 installs and runs correctly.

The latest portable package works fine.

## Expected behaviour

Git Extensions should launch fine.

## Steps to reproduce

After a fresh install of v3.3.1.7897, it should launch.
The portable package works fine.

## Error Details
```
System.UnauthorizedAccessException: Attempted to perform an unauthorized operation.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   at GitUI.WebBrowserEmulationMode.SetBrowserFeatureControl()
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()
```

## Additional information
Unable to launch Git Extensions 3.3.1

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.1.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4018.0
- DPI 144dpi (150% scaling)

**Comment by pmiossec** [comment]
It seems that the bot is on fire 🔥 

It seems also that `Registry.SetValue()` required rights so we have to `try...catch` the call

**Comment by NoahLerner** [comment]
> It seems that the bot is on fire 🔥

This is partially my fault as I updated the issue thrice.

**Comment by RussKie** [comment]
Yep, the bot is configured to look for updates.

**Comment by RussKie** [comment]
> The previous build, v3.3.0.7719 installs and runs correctly.

This is very weird, this logic or the codepath don't look like have changed in years.

**Comment by NoahLerner** [comment]
Is there an install package available with this fix, maybe through the CI?
I didn't see that I'm able to build an install version of 4.x in the Wiki. Thanks.

**Comment by pmiossec** [comment]
>Is there an install package available with this fix, maybe through the CI?

We don't build an install package for development build.
However, we usually build a portable version to easily test fixes.

Unfortunately, the build of the portable version has been broken 3 days ago and we discovered it just yesterday. So, you will have to wait a little to see that fixed...

**Comment by pmiossec** [comment]
You could find the portable version here:

https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts
