### ISSUE TITLE
Associate local branch to a remote branch

### ISSUE THREAD

**Issue by yiding-he** [gitextensions/gitextensions#7920]
## Feature description
I need a convenient way to associate remote branch to local branch.
Here is an exsample:

1. create local branch "v1";
1. push local branch to remote repository with name "v1";
1. rename local branch to "v2";
1. push local branch to remote repository with new name "v2";

So far, local branch "v2" is still associated with remote branch "v1". I wish gitextensions to provide a way to execute `--set-upstream-to` option.

**Comment by RussKie** [comment]
Look under _Repository > Remote Repositories..._ on "Default pull behaviour (fetch and merge)" tab.

**Comment by mstv** [comment]
You can do it using the Push dialog, too.
You must enter the `to` branch manually and replace the tracking reference:

![grafik](https://user-images.githubusercontent.com/36601201/77951180-f1dce500-72c9-11ea-9da5-47b68640916d.png)

**Comment by elevatorguy** [comment]
Can it not track `pull/#/head`?
> With `6.0.2.18262`, is it no longer possible for branch to have tracking reference of pull request(s)?
> — [#11347](https://github.com/gitextensions/gitextensions/issues/11347#issuecomment-3530527597)

Error seems to suggest the push dialog box is not how to accomplish.
