### ISSUE TITLE
GitHub remote icon size is too big in the side panel

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#7940]
## Current behaviour

GitHub remote icon size is too big in the side panel.

## Expected behaviour

GitHub remote icon size is too big.

## Steps to reproduce

1. Open GitExtensions repository
2. Have (or add) remotes on github remotes

## Screenshots

![image](https://user-images.githubusercontent.com/460196/78380129-ada45a00-75d3-11ea-89fe-99bac7279f1c.png)

![image](https://user-images.githubusercontent.com/460196/78380500-41762600-75d4-11ea-88a4-417d9caef378.png)

Note: AzureDevOps icon is of good size:

![image](https://user-images.githubusercontent.com/460196/78381445-aaaa6900-75d5-11ea-8eae-e337095421f8.png)

## Did this work in previous version of GitExtensions

I have it from months in `master`.
I think it was broken when implementing dark theme (but thought it was a problem on my computer). This was already discussed but I can't find where... /cc @NikolayXHD @gerhardol 
I don't want to see this bug released with v4.0 (I have to be sure)

## Environment

- Git Extensions 4.0.0.8945 (Portable version generated from CI build and my build from master)
- Build a6f3362e7ca4d5e18de85b7284bfec4785ef914a (Dirty)
- Git 2.25.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4150.0
- DPI 192dpi (200% scaling)

**Comment by gerhardol** [comment]
hdpi related, the icon looks good for me

**Comment by pmiossec** [comment]
Github icon size is 32px and others 16px. I think that's the reason...
