### ISSUE TITLE
Select All (Ctrl-A) in the branch window will bring program to halt

### ISSUE THREAD

**Issue by radix07** [gitextensions/gitextensions#7943]
## Current behaviour

Do a select all in the upper window where commits are displayed. Git Extensions will lockup, presumably attempting to do what you told it do it to.

I do this occasionally on accident when trying to select all files before I stage them and my cursor is in the wrong window. I don't I ever need to do this in the commit window, but it will overwhelm the system when I do this.

## Expected behaviour

Just don't attempt to select everything, put a limit on it, give a warning if resources are going to be exceeded...

## Steps to reproduce

Do a select all in the upper window where commits are displayed. Git Extensions will lockup, presumably attempting to do what you told do it to.

## Screenshots

Program locks up...

## Environment

- GitExtensions version: latest
- GIT version:  2.21
- OS version:  Windows
- .NET version: 

## Diagnostics

**Comment by gerhardol** [comment]
Selected commits limited in #7560, in master
