### ISSUE TITLE
font broken with UTF-8 in git commit message (detail panel) 

### ISSUE THREAD

**Issue by long-nguyenxuan** [gitextensions/gitextensions#7949]
## Current behaviour

commit message show in lower text label got font broken (UTF-8) 

## Expected behaviour

it should be UTF-8 friendly. 

## Steps to reproduce

1. do commit with UTF-8 commit message 
2. GitExtension/Open Repository 

## Screenshots

![image](https://user-images.githubusercontent.com/46129500/78471846-6eeedb00-775e-11ea-9e73-2a7f6cc7281b.png)

## Did this work in previous version of GitExtensions

no 

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.26.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

## Diagnostics

N/A

**Comment by RussKie** [comment]
> 1. do commit with UTF-8 commit message

Please provide an example

**Comment by pmiossec** [comment]
I encountered this. I'm not sure to remember well but I think it's that the
font use by default by Gitextensions does not support utf8.

Please choose another font in the settings (without forgetting to restart
in between) to see if it works

**Comment by long-nguyenxuan** [comment]
@RussKie 
> Please provide an example

Repository: https://github.com/long-nguyenxuan/sample-git-extension-error 

Error image (in GitExtension): 
![image](https://user-images.githubusercontent.com/46129500/78499523-5b9e3880-777b-11ea-8dd9-c6a78539e460.png)

in Git Bash: 
![image](https://user-images.githubusercontent.com/46129500/78499577-addf5980-777b-11ea-8156-abfbfce014b2.png)

in Github Web : 
![image](https://user-images.githubusercontent.com/46129500/78499562-93a57b80-777b-11ea-853a-14764e1d028e.png)

**Comment by long-nguyenxuan** [comment]
@pmiossec I'm using `Consolas` and`Segoe UI` , both are UTF-8 supported fonts. 
Tried to change to something else, not work. 
![image](https://user-images.githubusercontent.com/46129500/78499644-1cbcb280-777c-11ea-9fcb-ad523c93374d.png)

**Comment by long-nguyenxuan** [comment]
@pmiossec updated: I've tried with `RobotoJ`, another UTF-8 monospace font 
Seem it works :) 
Here is the link to [RobotoJ download page ](https://github.com/tsunesan3/awsome-jp-coding-fonts/tree/master/RobotoJ)
![image](https://user-images.githubusercontent.com/46129500/78499807-006d4580-777d-11ea-9c2e-0351cf7f8412.png)

**Comment by pmiossec** [comment]
Yes. I noticed the same things...

Fonts that were supposed to support utf8 are not working.

But some other fonts work.

But I was unable to understand why 😕

Perhaps we need to embed a font and use it as default.

**Comment by RussKie** [comment]
> But I was unable to understand why 😕

I wouldn't be surprised if our implementation `SetXHTMLText` was buggy...
