### ISSUE TITLE
Context menu items with sub menu's should not be clickable

### ISSUE THREAD

**Issue by pvginkel** [gitextensions/gitextensions#795]
A new feature has been introduced where when e.g. the "Checkout branch" has just one branch as sub menu, clicking the "Checkout branch" will actually check out that branch.

This is a non standard mechanism for working with menus. When you want to see what items are in the sub menu by clicking them, the action is already performed.

A more standard way to accomplish this would be to change the menu when it has only one sub item. The idea here is that the "Checkout branch" menu item would have its sub menu removed and be renamed to "Checkout branch bugs/48". I do like the feature and this change would keep the new functionality but remove the non standard menu functionality. It would also communicate clearly to the user what is going to happen when the user clicks the menu item.

**Comment by RussKie** [comment]
Closing as no longer relevant
