### ISSUE TITLE
Method not found in master

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#7957]
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

```
---------------------------
Exception
---------------------------
Method not found: '!!0 GitUI.ControlUtil.FindDescendantOfType(System.Windows.Forms.Control, System.Func`2<!!0,Boolean>)'.
---------------------------
OK   
---------------------------
```

**Comment by mstv** [comment]
The only call site is
```
    class UserRepositoriesList

        private void RecentRepositoriesList_Load(object sender, EventArgs e)
        {
            if (!(Parent.FindForm() is FormBrowse form))
            {
                return;
            }

            var menus = new ToolStripItem[] { mnuConfigure };
            var menuStrip = form.FindDescendantOfType<MenuStrip>(p => p.Name == "menuStrip1");
```

**Comment by mstv** [comment]
Cannot reproduce using Git Extensions 4.0.0.9030, Build f400be6.
Please fill in the bug report template, @NN---.

**Comment by NN---** [comment]
I will double check again.

**Comment by NN---** [comment]
Doesn't reproduce with latest build.

**Comment by gerhardol** [comment]
There are no changes related to this method
Maybe caused by problems unpacking?

**Comment by KallDrexx** [comment]
I just updated the portable build on my work machine from an unknown version (I don't remember when I last updated) to 3.4.2.9737 and I"m getting this error all the time now.

**Comment by pmiossec** [comment]
> I just updated the portable build on my work machine from an unknown version (I don't remember when I last updated) to 3.4.2.9737 and I"m getting this error all the time now.
> 
> It's still usable to me after I dismiss the error but it is annoying.

The unpacking of a portable version must be made in a new folder. Is it what you've done?

**Comment by KallDrexx** [comment]
> The unpacking of a portable version must be made in a new folder. Is it what you've done?

No, I overwrote the previous one.  I nuked the old directory and re-extracted it fresh and that did fix it, though of course I lost my recent repositories and whatnot.  Oh well at least it's less annoying now.

**Comment by vbjay** [comment]
Backup the settings and recent repo files and copy them back in after
extracting.

**Comment by mstv** [comment]
> Backup the settings and recent repo files and copy them back in after
extracting.

I am afraid this hint came too late. Trying to improve: #8273.
