### ISSUE TITLE
Support for rebasing part of a branch (rebase --onto ...)

### ISSUE THREAD

**Issue by diaconesq** [gitextensions/gitextensions#7964]
## Feature description

I'd love Git Extensions to have support for non-interactive, partial rebase.

My workflow goes like this (and I think it's quite common):
- I create a feature branch A on _master_ and start work.
- Midway through, I get distracted and create a new branch _B_ on top of _A_ to work e.g. on a bug fix. I don't create _B_ on top of _master_ because _A_ already has the environment set up a particular way for debugging.
- I don't want the bug fix to be part of _A_, and I want to push it to master.

This is achieved with `git rebase --onto master A B` but I never remember the syntax and have to look it up and understand which part is which. 
(Here's [one article](https://medium.com/@gabriellamedas/git-rebase-and-git-rebase-onto-a6a3f83f9cce) that visually describes how `git rebase --onto` works)

I'd rather just select a (contiguous) range of commits and have a context menu that allows me to rebase that range to a new parent.

It can be done today with interactive rebasing or manual resetting of branches and then cherry-picking, but it's not too pleasant.

## Environment

- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.23.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 192dpi (200% scaling)

**Comment by pmiossec** [comment]
![image](https://user-images.githubusercontent.com/460196/78885755-6b5c9c00-7a5d-11ea-943a-e72d8b6928c6.png)

![image](https://user-images.githubusercontent.com/460196/78885688-554edb80-7a5d-11ea-9eb6-7935d232e6d4.png)

:D

**Comment by pmiossec** [comment]
But I use it often too. So, I admit that it could be great if it could be added directly as a menu item...

**Comment by diaconesq** [comment]
Awesome, I'm happy with this resolution! :)
Couldn't find any docs about it though, maybe that's something that could be improved.

**Comment by pmiossec** [comment]
We are counting on the ones that experienced the lack of documentation to improve it (as GitExtensions is an opensource project). Who is the best placed?

So, please, help us and contribute.
That's here: https://github.com/gitextensions/GitExtensionsDoc/blob/master/source/modify_history.rst
