### ISSUE TITLE
[NBug] Path for cloning repo is checked on paste, not on Clone button

### ISSUE THREAD

**Issue by PeshekhonovK** [gitextensions/gitextensions#7967]
## Current behaviour

When you paste some text to Destination field, looks like it's verified to be a path. When you paste there incorrect symbols, exception is thrown and application fails.

## Expected behaviour

Text is pasted, then validated when button Clone is pressed.

## Steps to reproduce

Copy any email (mine text was like "Русский Текст <someemail@gmail.com>"
Paste to Destination field
See exception dialog

## Error Details
```
System.ArgumentException: Путь содержит недопустимые знаки. (invalid symbols in path)
   в System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   в System.IO.Path.Combine(String path1, String path2)
   в GitUI.CommandsDialogs.FormClone.ToTextUpdate(Object sender, EventArgs e)
   в System.Windows.Forms.ComboBox.OnTextUpdate(EventArgs e)
   в System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   в System.Windows.Forms.ComboBox.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Wanted to manually remove special symbols from email after pasting to make a normal folder, but no luck. Original pasted text was like: Русский Текст <someemail@gmail.com>

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by PeshekhonovK** [comment]
email is made URL, but it should be in braces - how it is copied from online email client

**Comment by RussKie** [comment]
This looks like a duplicate of https://github.com/gitextensions/gitextensions/issues/7839 that was fixed in #7876.
Please try the latest portable https://ci.appveyor.com/api/buildjobs/kwwpcdjrrjtusi5t/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.9047-79f4d4b1b.zip

**Comment by PeshekhonovK** [comment]
Verified in portable version. Looks good, issue is fixed. Thank you!

When would it be in not portable?

**Comment by RussKie** [comment]
We don't have a set date, but we're working towards a new release.
I think we may have a release in about a month or so.
