### ISSUE TITLE
Artifacts conflict with Debug and Release builds

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7969]
## Current behaviour

The `artifacts` folder is shared for Debug and Release builds -- at least regarding tests.

## Expected behaviour

Do not mix Debug and Release artifacts.

## Steps to reproduce

- run tests for Debug
- build Release in parallel

## Environment

- Git Extensions 3.3.0
- Build d7ad8acee9c0f3eb8be949ef16388ce380c9d558
- Git 2.24.1.windows.2 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

## Diagnostics

```
MSB3027	Could not copy "Externals\conemu-inside\ConEmuWinForms\bin\Release\net461\ConEmu.WinForms.dll"
to "artifacts\bin\tests\IntegrationTests\UI.IntegrationTests\net461\ConEmu.WinForms.dll".
Exceeded retry count of 10. Failed. The file is locked by: "NUnit Agent (12516)"
UI.IntegrationTests
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets
4360	
```

**Comment by RussKie** [comment]
Each configuration builds into own set of folders, it is impossible to mix them up.
I'm guessing there is something else in play. Feel free to ping me in the gitter directly.

**Comment by mstv** [comment]
The builds aren't mixed up but the tests assemblies go to `artifacts\bin\tests\IntegrationTests\UI.IntegrationTests\net461` (see the error message in the issue description).

**Comment by RussKie** [comment]
Yes, indeed tests assemblies are written in to the same location. My bad...
