### ISSUE TITLE
File history does not load

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7971]
## Current behaviour

FormFileHistory opens but does not show the loading indicator, stays empty

## Expected behaviour

guess what

## Steps to reproduce

- select a file, e.g. `GitExtensions.settings`
- hit `H`

## Did this work in previous version of GitExtensions

yes, at least with GitExtensions-Portable-4.0.0.8667 34974739b, which seems to be the last portable build I run as portable

## Environment

- Git Extensions 4.0.0.8841
- Build b42714c7b041c524c63d2ef4b724bb1d8266f45b (Dirty)
- Git 2.24.1.windows.2
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
You should probably know it but that's due to an exception that occurs when
loading the history.

So it should be easy to spot.

**Comment by mstv** [comment]
No, no exception at all. Just an empty window:

![grafik](https://user-images.githubusercontent.com/36601201/79052666-6d2e8700-7c38-11ea-9c99-c4615765d52a.png)

**Comment by gerhardol** [comment]
Works for me with current master (and all builds I have used for quite some time).

**Comment by mstv** [comment]
Yes, the portable build works if run as portable but not with my settings, what I use to do.
Which settings can influence the history?!?

GitExtensions.exe.config:
```
      <setting name="IsPortable" serializeAs="String">
        <value>False</value>
      </setting>
```

**Comment by gerhardol** [comment]
I do not run as portable, from the debugger or the 'build.cmd -pub' collections (that is without IsPortable=True)

**Comment by mstv** [comment]
It must have something to do with my GE settings or my environment.
But which could have such a strange effect? It does not run any git command.
(I cannot give more detail ATM because the debugger strikes #7980.)

**Comment by mstv** [comment]
It's because turning off the settings "Load history/blame on show" does not make much sense with the current implementation.

![grafik](https://user-images.githubusercontent.com/36601201/80920596-1e749880-8d71-11ea-9cfd-af996d0e91f7.png)

I'll turn them on and close.

**Comment by gerhardol** [comment]
Remove these settings?
Move the other two icon menus to one menu and use a settings icon
