### ISSUE TITLE
Portable build of PR has misleading commit hash

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#7979]
## Current behaviour

IIUIC, the PR is merged to the master in a temporary commit, whose hash is used in GE and the zip name then. This is quite pointless and misleading.
If we get bug reports, we must resolve the build number.

## Expected behaviour

Let GH point to the build of the unmerged commit.

**Comment by RussKie** [comment]
What commands to run?

**Comment by gerhardol** [comment]
Get the hash before the merge and save it

**Comment by RussKie** [comment]
This is controlled here:
https://github.com/gitextensions/gitextensions/blob/master/GitExtensions/Project.Publish.targets#L73

Feel free to change it.

**Comment by RussKie** [comment]
Re-opening since it is not fixed
