### ISSUE TITLE
Diff of files which have been renamed fails

### ISSUE THREAD

**Issue by rooflz** [gitextensions/gitextensions#798]
If you rename a file, then from the 'file history' run a diff on two revisions which have different names the diff will fail.

I've tried to fix this from the perspective of feeding git difftool the proper names of each file, however it doesn't seem to support multiple filenames. 

I've created a small fix for git extensions to get things working in the mean time though. 

If the filenames of the selected rows differ, the git difftool command will fail, so instead it writes local copies of these files (obtained by git show) to the temp directory and feeds them to kdiff. 

I will enter a defect on GIT as well, but even if git difftool gets updated, git extensions will need to feed the two names into the command. For now though, it seems as if writing the files to the temp directory is an acceptable workaround.

**Comment by mstv** [comment]
I'd say this one not reproducible anymore.
