### ISSUE TITLE
Add "Remove Windows Explorer integration" in Settings Menu

### ISSUE THREAD

**Issue by janfrederik** [gitextensions/gitextensions#7982]
## Feature description

Could you add an option in the settings menu to entirely enable/disable the Windows Explorer integration (Shell extension)? There is the possibility to tweak the context-menu, but not to entirely disable it.
I already have more than enough stuff in my right-click menu in Windows Explorer and want to get rid of GitExtensions there.

During installation, you have the possibility to select/unselect the option "Windows Explorer integration". 
![image](https://user-images.githubusercontent.com/18148910/79069716-afa3a280-7cd0-11ea-9a2c-9c840e6ff981.png)
However, upon installing, it sounded like a good idea. Now the context menu entry sits there and I hate it, cluttering my context menu even though I never use it.
I could uninstall GitExtensions and reinstall it again without the option. This is like using a cannon to kill a mosquito, thinking how easy it must be to add this option.

## Environment

- GitExtensions version: 3.3.1.7897

**Comment by NoahLerner** [comment]
I started working on this enhancement. I would be very happy if others could get involved with me on this since I'm relatively new to this project.

PR is currently a draft only. Hope the unfinished PR doesn't violate the contributing guidelines.. it's for visibility.

**Comment by pmiossec** [comment]
>PR is currently a draft only. Hope the unfinished PR doesn't violate the contributing guidelines.. it's for visibility.

Opening a PR early is a good practice, so, no problem.
We like to prefix the PR title with 'WIP' (that we use more than draft PR).
But, since the improvement on draft PR by GitHub just some days ago, that is mostly equivalent, so I don't have a strong point of view about that and it should be OK 😉

>I started working on this enhancement.

Great! Thanks. 

>I would be very happy if others could get involved with me on this since I'm relatively new to this project.

I'm not sure any of us know this part of the Gitextensions code but if you have questions, we would be happy to answer them (even if sometimes they don't come in a minute 😉)

**Comment by RussKie** [comment]
What @pmiossec said ☝️ 
Thank you

**Comment by joberreiter** [comment]
See also #7863 .

**Comment by jiahaoliang** [comment]
Looking at the original issue, I can't believe such simple feature is eventually being implemented in 2020 given the original request was from 2013.

Thank you @NoahLerner for the good work !

**Comment by NoahLerner** [comment]
@jiahaoliang My pleasure. Because of stay at home orders, I have been at home with small kids & haven't been able to give this the attention it needs. Things are finally returning to normal here, so I will get back to this over the next few days. Thanks for your patience :-)

**Comment by itsho** [comment]
Side note: anyone can remove/disable anything from the context menu with this tool:
https://www.nirsoft.net/utils/shell_menu_view.html

**Comment by Ahmed-Abdelhameed** [comment]
@itsho I think you need [ShellExView](https://www.nirsoft.net/utils/shexview.html) because I couldn't find it in ShellMenuView.

**Comment by kirsan31** [comment]
I will add my 50 cents. I've used (vey rarely) GE portable 3.3.1 and had no worries. But today after launch I've see a message about update and agree to it :( After installation process (with no question) I have:
1. Windows explorer integration.
2. Second instance of an app (installed - not portable). And I did not understand this right away :)

**Comment by vbjay** [comment]
Raise that as a seperate issue. The portable should point you to the
portable zip and not installer.   Since you found the issue, raise it as a
seperate issue.

**Comment by blackboxgeeks** [comment]
I had the same issue of wanting to remove the Windows Explorer integration and was able to by using the modify option in windows setting - apps - apps & features and clicking on Git Extensions and instead of uninstall click modify.
