### ISSUE TITLE
Can't relaunch application after closing

### ISSUE THREAD

**Issue by BrewingGeek** [gitextensions/gitextensions#7992]
## Current behaviour

See above

## Expected behaviour

be able to see and use teh GUI

## Steps to reproduce

Reinstalled the application it then works once. This was performed multiple times with the same result

## Did this work in previous version of GitExtensions

Yes..

## Environment

- GitExtensions version:
- GIT version:  GitExtensions-3.3.1.7897
- OS version:  Windows 7
- .NET version: 
![image](https://user-images.githubusercontent.com/48930037/79394571-aadb2a80-7f2c-11ea-91e2-50f0a761136e.png)

![image](https://user-images.githubusercontent.com/48930037/79394599-bf1f2780-7f2c-11ea-80aa-93e644a7a8bc.png)

**Comment by mstv** [comment]
How do you start Git Extensions, @BrewingGeek?

**Comment by BrewingGeek** [comment]
Hi  I start it from then desktop icon

Target: "C:\Program Files (x86)\GitExtensions\GitExtensions.exe"

Start in : "C:\Program Files (x86)\GitExtensions\"

 

I also have gone to the ‘Target” location attempted, same result

 

What I have also notice is that if I try to start it and attempt to reinstall it, it barks saying its running and it can’t be stopped. So I stop it in the ‘Task mgr’

 

Dave

**Comment by mstv** [comment]
Have you tried it after a reboot?

**Comment by vbjay** [comment]
Record an animation showing it working and then what happens the next run.

https://www.screentogif.com/

**Comment by BrewingGeek** [comment]
Yes I did it after a reboot and no success

**Comment by BrewingGeek** [comment]
Quick update..  If I run it as administrator from the desktop icon it run OK

 

Dave

**Comment by BrewingGeek** [comment]
Added info

**Comment by vbjay** [comment]
Open the config file and tell us what the isportable setting is.

**Comment by RussKie** [comment]
Check EventViewer for any errors under Windows Logs/Application

**Comment by BrewingGeek** [comment]
Hi

 

I don’t see anything abnormal in the log file.  Though I have noticed that this AM I attempted to start the application and it run..  I closed it and attempted to restart it and it did not launch. I saw the spinning mouse pointer and then it stopped.  A few hours later I attempted to run it again and it ran. I closed it and attempted to restart it andit failed…

**Comment by RussKie** [comment]
I am afraid we can't provide further assistance without more information.
If the app has started, it means the app is good. And it is likely something in your system that prevents it from running, like an antivirus, group policies, etc.
