### ISSUE TITLE
"Initialize all submodules" or "Update all submodule" means --recursive

### ISSUE THREAD

**Issue by DocteurGrr** [gitextensions/gitextensions#7995]
When cloning a new repository having "Initialize all submodules" checked, or when updating submodules (Menu "Repository" item "Update all submodules"), It implies a RECURSIVE update (git option is --recursive).
Could this recursivity be avoided and submodules be updated for just one level by default, letting recursivity as an option ?
Thank you !

**Comment by RussKie** [comment]
Could you please provide more reasons to why we shouldn't clone everything?

**Comment by gerhardol** [comment]
There are too many settings in GE already, so all new must be carefully motivated and possible to explain to other users.

**Comment by DocteurGrr** [comment]
Hello. 
Thanks for your fast answer.
In our lab, we develop several libraries with unit tests, application tests and bindings. They are git modules and they have submodules (which are often dependencies that we need to build). 
For industrial or research projects; we need to develop applications that rely on one or several of our libraries. In this case they are used as submodules. And for simplicity we prefer having just one level of sub modules without recursivity.
For instance, if an application depends on libraries A and B, with A depending on C and D, and B on D and F, then we have our application as a git module depending on submodules A, B, C, D, E and F.


and we often use these modules as submodules to build application. But we dont 't want to use this recursivity in general. We prefer having just one level i.e. : build an application (a module) that rely on submodules A and B, instead of A that depends on B.
When using sometimes 5 to 8 submodules, it is simpler to our eyes.

**Comment by gerhardol** [comment]
Why not clone without submodules and use a script to clone one level only?
The script could be triggered manually or possibly on fetch.
(There is no trigger on clone, that would be a more sensible addition than limit to one level.)

**Comment by pmiossec** [comment]
I agrees with @gerhardol.
In a normal case, you should understand that a repository that has a submodule dependency must initialize this submodule to work well.

So your case is something special and mostly used just by you. And a generic tool like Gitextensions is not intended to support all the specific/strange things that user could do.

It should stick to do what is of general use.

Indeed, using a script that you could add in the 'script' feature of Gitextensions is surely the best solution.
