### ISSUE TITLE
Left panel: sort branches alphabetically

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8001]
## Feature description

Currently, the branches in the left panel are sorted by date. This makes them and the branch folders jump around.
I would prefer an alphabetical sorting by default.
Additional folders with favourite and most recent branches could be added.

**Comment by RussKie** [comment]
This is related to a regression. We had sort functionality but Drew took it
out in his big UI make over few years back. 😕

IIRC there was an issue opened for this, and there was even a PR, but it
attempted to resurrect incorrect implementation....
I'll dig those out, if Gerhard won't beat me to it. 😎

You can say it is on my radar, but not a top priority.

**Comment by mstv** [comment]
> IIRC there was an issue opened for this, and there was even a PR, but it
attempted to resurrect incorrect implementation....

It was PR #7456.

So this issue is quite duplicate to the issue #6310, which I thought was just about the branch selection dropdown.

**Comment by gerhardol** [comment]
I normally prefer most recently used. If a special 'recent' folder with a screen of branches are listed, I am OK with changing this. Sure, I could use the menubar instead, but I  tend to go to side panel when I want to access branches.

**Comment by RussKie** [comment]
I have use cases where I'd prefer to sort A-Z, so bringing back the
functionality would be helpful

**Comment by RussKie** [comment]
Fixed in #8427
