### ISSUE TITLE
Unable to update through the network, release 3.3.1 

### ISSUE THREAD

**Issue by DmAC4D7** [gitextensions/gitextensions#8023]
## Current behaviour

The attempt to update through the Internet doesn't work for some reasons. Perhaps due to the network configuration, it's not clear. The internet connection itself is work. Hitting to the "Check for update" sub-menu the exception occurs, refer to the screenshot depicted below.

## Screenshots

![image](https://user-images.githubusercontent.com/13134256/79871260-63e5ad00-83e4-11ea-97a6-33063c09d350.png)

## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by pmiossec** [comment]
I think that it is caused by the (very) limited number of calls that is
allowed to github when not authenticated as we call the api to find new
releases hosted on GitHub release feature.

**Comment by RussKie** [comment]
It is plausible.

This is the code responsible for the message:
https://github.com/gitextensions/gitextensions/blob/d815828f3246e65e32889e193652186f885194ad/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs#L99-L110

I suppose we could show a nice message...
