### ISSUE TITLE
URL in "Edit Remote Details" is case insensitive when checking for modifications

### ISSUE THREAD

**Issue by digitalcoyote** [gitextensions/gitextensions#8030]
## Current behaviour

When changing a remote's url (eg migrating a repo from one server to another) it checks if the url has changed before saving. This check is not case sensitive. So if the url is case sensitive and changes only the casing, it will not save the change.

## Expected behaviour

Check the URL in a case sensitive manner.

## Steps to reproduce

Change Url Casing and click "Save Changes".

## Screenshots
![image](https://user-images.githubusercontent.com/16868093/80013026-d5c8ff80-8493-11ea-9de0-a3a13afff808.png)

## Did this work in previous version of GitExtensions

N/A

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

## Diagnostics

N/A

## PR Incoming
I should have time after work today to put together a PR for this. I have not looked at the code yet, but I can't imagine this would be a major change.  Is there any reason this should not always be case-insensitive?

**Comment by digitalcoyote** [comment]
Took a look on lunch and it's more complicated than it sounded... It's ignoring the change because ComboBox internally uses FindStringIgnoreCase (which of course finds the original string as index 1). The change is more complicated than the work-around.

**Comment by RussKie** [comment]
> When changing a remote's url (eg migrating a repo from one server to another) it checks if the url has changed before saving. This check is not case sensitive.

Can you point to the specific lines?

I suppose this is what may be stopping the rename, but it should be easy to fix:
https://github.com/gitextensions/gitextensions/blob/ab8a862e5e70c15dac0911c8fa9bfc299f6a5a47/GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs#L338-L342

**Comment by digitalcoyote** [comment]
So.... It's actually caused by [ComboBox's AutoComplete implementation](https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ComboBox.cs,741839591cce46ae) using a case-insensitive AutoComplete that uses the current test as a source. I'm working on a PR that could be used (overriding NotifyAutoComplete). I haven't finished testing it yet, and the side effects of such a change still need to be considered.

**Comment by digitalcoyote** [comment]
I took another look on lunch and there is either more to it or I have made a mistake and I can't focus long enough to figure it out. I had it working til I went to clean up the code and despite trying rollback to the exact state I had it in, I seem to have messed it up. I'll take another look after work, but I'll need to take a step back so can focus on it properly.

**Comment by gerhardol** [comment]
You can always name the branch (and give a link) you are working on and someone may look at the status.
When you are feeling more ready but need to work on details, you can open a PR with WIP
