### ISSUE TITLE
Build publish fails for Debug

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#8033]
## Current behaviour

Building a publish package (to use e.g. for private deployments) fails as the files are copied with the GitExtensions prefix

  ``` DeleteUnusedBranches -> F:\dev\gc\gitextensions\artifacts\bin\GitExtensions\Debug\net461\Plugins\DeleteUnusedBranches\GitExtensions.DeleteUnusedBranches.dll

...

  Zipping directory "F:\dev\gc\gitextensions\artifacts\publish\Debug\" to "F:\d
  ev\gc\gitextensions\artifacts\publish\GitExtensions-Portable-3.3.0.0-dd141.zi
  p".
  Download 'GitExtensions.PluginManager.1.1.0.109.zip' already exists.

F:\dev\gc\gitextensions\Setup\Product.wxs(601): error LGHT0103: The system cannot find the file 'F:\dev\gc\gitextensions\artifacts\publish\Debug\GitExtensions\\Plugins\DeleteUnusedBranches.dll'. [F:\dev\gc\gitextensions\Setup\Setup.wixproj]
```

The build directory can still be used, but the size is like 236 MB instead of 32 MB, all dlls are duplicated
Release could be used but Debug builds give a little more info for private deployments

## Expected behaviour

Either that publish for Debug cannot be started or rather that Release/Debug work the same

## Steps to reproduce

```./build.cmd -pub```

## Did this work in previous version of GitExtensions

This has been changed a couple of times since 3.3

## Environment

From master+ private changes

- Git Extensions 3.3.0
- Build dd1413ee4ac0156d896a22de7954162e9ca69fac
- Git 2.26.2.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
in debug build all plugins have different names, hence they can't be found
for packing

**Comment by RussKie** [comment]
Related issues:
* https://github.com/gitextensions/gitextensions/issues/7842
* https://github.com/gitextensions/gitextensions/pull/7910

As a workaround you should be able to build a "Debug" CI build: `> .\build.cmd -ci -publish`

**Comment by RussKie** [comment]
Closing as I'm not sure what we can do here, until we port to .NET Core and lose all those pesky netstandard-related assemblies.
