### ISSUE TITLE
Diff: Compare to any file

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#8048]
## Feature description

Git allows comparing any file in any commit:
```git diff HEAD:appveyor.yml HEAD~99:build.cmd```

This would be useful to compare renamed and changed files that Git do not detect as renamed.
Not very often needed, but quite many steps to save the files to temporary location, then diff them.

 * One way to achieve this (that would work in separate commits and even separate repos) is to add option "remember file" to diff submenu and if such selection is previously done, "compare to <file>".
 * Another would be that if there are two selections, add menu item "compare <x> and <y>".  More automatic but maybe harder to find. (My preference)

In both situations, if a removed file is selected, the other commit (where it was added) is selected instead.

Note: #7716 should be considered too here,  the difftool should be selectable in the same way as for normal diffs.

## Environment

- Git Extensions 3.3.0
- Build 21d9669784aab05e491f7d3d2ee701c5f64e1734
- Git 2.26.2.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
My favourite diff tool uses `Select left file for compare` and `Compare to "first file"` for single selections and just `Compare` if two files are selected.

**Comment by RussKie** [comment]
An interesting idea. I'd like to discuss and explore the UI options first.

**Comment by gerhardol** [comment]
mstv was clear:
In the Diff menu, add options _only_ for the selected commit (b/second):
 * Select <hash>: filename for compare
 * Compare b/<hash> with <prev hash>: filename (if a file is selected)
 * Compare <hash> file1 with file2 (If exactly two files are selected) 

If multiple difftools, this is handled as normal F3 diff (submenu?)
![image](https://user-images.githubusercontent.com/6248932/80918217-2da11980-8d64-11ea-8d04-7034c43272ff.png)
