### ISSUE TITLE
Git rebase the first commit via GUI

### ISSUE THREAD

**Issue by justanotheranonymoususer** [gitextensions/gitextensions#8053]
Let's say I have two commits, and I want to squash them. Currently I don't see a way to do it via GUI, since I can't choose a commit before them both to rebase on.

Here's a relevant question and answer on StackOverflow:
https://stackoverflow.com/questions/22992543/how-do-i-git-rebase-the-first-commit/23000315

The answer - use `git rebase -i --root`. It worked, but it would be nice to have a way to do it via the UI.

**Comment by vbjay** [comment]
Just add a script  with that command.

**Comment by RussKie** [comment]
Soft reset on to the first one and then amend

**Comment by justanotheranonymoususer** [comment]
> Just add a script with that command.

It's an option, I just thought that having it available out of the box would be nice.

> Soft reset on to the first one and then amend

Can work for two commits, but let's say I have several, and I want to fix-up the second one. e.g.:

```
Commit 10
...
Commit 2
Commit 1
```
Interactive rebase:
```
pick 234743a Commit 10
... (pick the rest)
fixup a462bb3 Commit 2
pick 1282936 Commit 1
```

Maybe add a pseudo-commit called "root" before the first commit? Like we have "Commit index" and "Working directory"?

**Comment by gerhardol** [comment]
This is a problem for the initial commit only and affect very few users. But a few users will maybe use this when rebasing (I want to have ```root``` inte interactive rebase editor).
GE will never make a GUI for features in Git (but those that users care enough to make PRs for...)

The interactive rebase dialog is a little busy already, I would rather not add this option as it intemidates users (and more options will give translation issues). If someone made a PR I guess I would not vote against it though.

**Comment by justanotheranonymoususer** [comment]
Just to be clear, here's what I suggest. No changes to the interactive rebase dialog, which is a little busy already, will be required.

![image](https://user-images.githubusercontent.com/5781692/80716993-ff6fcf80-8b00-11ea-85b2-5190b78f2f7f.png)

**Comment by gerhardol** [comment]
> Just to be clear, here's what I suggest. No changes to the interactive rebase dialog, which is a little busy already, will be required.

OK for me from functionality, but adding a new type of "commit" that only handle rebase is quite some work.
An option in the busy rebase dialog is the closest to Git that I see it.

**Comment by pmiossec** [comment]
>An option in the busy rebase dialog is the closest to Git that I see it.

That could be also displayed only if that's the first commit (a commit without parent) that is selected...

**Comment by justanotheranonymoususer** [comment]
Or just add "root" here?

![image](https://user-images.githubusercontent.com/5781692/80719877-c6395e80-8b04-11ea-95c1-8da3462bfeae.png)

Can also be added here as "Root commit" and/or "Root commit interactively" and/or "with advanced options" if the first commit is chosen:

![image](https://user-images.githubusercontent.com/5781692/80720015-fd0f7480-8b04-11ea-8da7-33d7cc74bb02.png)

**Comment by gerhardol** [comment]
> Can also be added here as "Root commit" and/or "Root commit interactively" and/or "with advanced options" if the first commit is chosen:

Adding Root Commit would be doable I assume, but will users find this function?

**Comment by justanotheranonymoususer** [comment]
The might, or they might Google for it and find this issue, and find about
it from here.

**Comment by RussKie** [comment]
This use case is very niche, however it would require a significant effort to add it to the grid.
There are a number of workarounds, closing.
