### ISSUE TITLE
Apply Patch - add possibility to execute without --signoff option

### ISSUE THREAD

**Issue by f-i-x-7** [gitextensions/gitextensions#8055]
## Feature description

It should be useful to apply patches without appending 'Signed-off by %USERNAME%' message to commits. Please see example of use case below.

Changes are implemented and committed in local repository that is located on Machine A. But Machine A does not have network access to remote repository, so changes are transferred somehow to Machine B (which has such network access) as patch files and then pushed to remote repository. In such a case several commits are applied simultaneously, and it is very annoying to remove 'Signed-off by %USERNAME%' line from each commit before push.

My proposal is:

- add new checkbox named 'Sign-off' to 'Apply patch' form, directly under 'Ignore wh.spc.' checkbox;
- new checkbox should be checked by default (this matches current behavior);
- if patch is applied successfully, then user choice (sign-off patch or not) should be saved and used to initialize checkbox state when 'Apply patch' form is opened next time.

I am new to GitHub and GitExtensions repo in particular. But, in my opinion, it should be not very difficult to implement proposed feature, so I would like to try it by myself and open a PR once it is done. Of course, if there are no objections from active part of community.

## Environment

- GitExtensions version: 3.3.1.7897
- GIT version: 2.25.0.windows.1
- OS version: Microsoft Windows NT 10.0.18363.0
- .NET version: 4.8.4150.0

**Comment by RussKie** [comment]
Let's start with the UI - if you can prepare a UI mock of how you think it
should look, it would be a start.
Thanks

**Comment by f-i-x-7** [comment]
Current UI:
<img width="525" alt="current" src="https://user-images.githubusercontent.com/64615981/80826465-f3f8d300-8bea-11ea-9d67-6f677135f467.png">
Proposed UI: 
<img width="525" alt="proposed" src="https://user-images.githubusercontent.com/64615981/80826478-fe1ad180-8bea-11ea-85af-151a0b93eb1e.png">

**Comment by f-i-x-7** [comment]
So, what do you think about this feature? If you agree that it would be useful to add then I could implement it.

**Comment by RussKie** [comment]
I think we can go with that. 👍
