### ISSUE TITLE
User configuration should be ALWAYS per repository

### ISSUE THREAD

**Issue by leonandroid** [gitextensions/gitextensions#8060]
The following option:
![image](https://user-images.githubusercontent.com/1564651/80907424-808bba00-8ced-11ea-8522-44a312ea50af.png)

I can tell you how much problems it caused, i´m using 2 different ADO repositories which has different credentials, when I log in in one, I use (of course) credentials from ADO1, then I also clone code from repository 2, but for some reasson this option that allows to put same values effective in all repos, if is not properly configured, enables me to commit code without having a valid user in the configured repository, this is extremely dangerous.

You can log in to ADO with your right credentials, but then change this option to be "billgates@microsoft.com" and destroy the entire repository at his name.

I´m basically uninstalling this app because every time I add a new repository, I need to ensure proper credentials are being used as submit information and not the latest I added to any repository, I don´t want my boss to see that I submitted code with an account that does not belong to his enteprise, he might be thinking i´m stealing code from his repository.

My suggestion is, do not allow to modify email used, it should use same as it was configured to log in into the repository.

Regards.

**Comment by leonandroid** [comment]
Just a piece of evidence:
![image](https://user-images.githubusercontent.com/1564651/80907696-68b53580-8cef-11ea-9f6c-66fecbccefc6.png)

When I delivered configured:
![image](https://user-images.githubusercontent.com/1564651/80907703-77035180-8cef-11ea-9c50-4796ff421dc2.png)

**Comment by mstv** [comment]
You should have filled in the bug report template and RTM. What shall we do without version information etc.?

Your use case is not uncommon but specific. So be precise when you enter your name: Tell that it shall be used for the **current** repo only and keep the global setting empty.

![grafik](https://user-images.githubusercontent.com/36601201/80910454-d8e3ab80-8d2f-11ea-80b0-7eb07b607681.png)

![grafik](https://user-images.githubusercontent.com/36601201/80910555-7dfe8400-8d30-11ea-8a49-d0994dd300b6.png)

**Comment by mstv** [comment]
Yes, one must care about this for every new clone. So we might consider to not set the credentials globally if "Effective" is selected and the global configuration is empty.

**Comment by RussKie** [comment]
> My suggestion is, do not allow to modify email used, it should use same as it was configured to log in into the repository.

Why? Does git not allow users to change this information?

**Comment by gerhardol** [comment]
This is handled by Git, if there is global data available but not repo data GE cannot stop Git to use global data.
GE will not implement a wrapper that ignores global data.
GE just provides to set the global and repo settings, nothing to do with the actual settings.
Git is designed to use PGP keys, if authentication is important.

If you want to suggest a feature, it is something that alerts the user if there is global data available.
I would prefer to not add such settings to GE, there are enough settings already.

If you want this, then it could be implemented as a plugin or maybe as a script (need to add trigger OnAppStartup).

The workaround for someone with this need is to just never set the global values.

**Comment by mstv** [comment]
Could we set the name and email only for the *local* repo if "Effective" is selected and the global configuration is empty? This would avoid that users set the name and email globally by mistake.

**Comment by pmiossec** [comment]
If I can add my point of view...

I always found this story of "Effective" settings not very understandable, misleading and error prone.

I would have made this view read-only to oblige the user to select the right setting "scope" and understand what he does...

**Comment by gerhardol** [comment]
Effective is required to show what is _in use_.
How to implement that the user selects Global/distributed with GE/local repo?
Popup when saving?
(disabling OK will confuse users)

**Comment by RussKie** [comment]
> I would have made this view read-only to oblige the user to select the right setting "scope" and understand what he does...

I can certainly see a point in this. 👍 

> Popup when saving?

I don't believe this would be a good UX.
