### ISSUE TITLE
error pop-up in release 3.4

### ISSUE THREAD

**Issue by KevinGossentCap** [gitextensions/gitextensions#8070]
## Current behaviour

while showing list of local repository and when opening any repository, we get the following error pop-up.
System Windows 10 1903 64bit
GitExtension 3.4 portable version

## Expected behaviour

no error pop-up

## Steps to reproduce

Launch Git Extension, see list of repositories (error pop-up appears)
open any of the repository (error pop-up appears)
switch to any other repository (error pop-up appears)

## Screenshots

![image](https://user-images.githubusercontent.com/20575643/81084683-7e487c00-8ef6-11ea-991c-a1873db316d3.png)

## Did this work in previous version of GitExtensions

No error on previous versions

## Environment

- GitExtensions version: 3.4 portable version
- GIT version: 2.26.2
- OS version: Windows 10 1903 64Bit
- .NET version:

**Comment by gerhardol** [comment]
Cannot reproduce. The routine in the message is executed when loading the dashboard recent repositories menu. Any specific info there?
What is the translation?
What is in the Git Command Log (F12)?

**Comment by drewnoakes** [comment]
This looks like a `MissingMethodException`, so probably a corrupted installation. Can you try re-installing?

**Comment by KevinGossentCap** [comment]
Hi, here are some additional info.
a fresh install seem to work.
If I override the settings and windows position of the fresh one with those of older one, seems to still work fine.
What produces the error is installing(unzipping) over the previous version (3.3.1) in my case.

**Comment by gerhardol** [comment]
> What produces the error is installing(unzipping) over the previous version (3.3.1) in my case.

Such update is not supported, with the portable version you have to unzip to new directory
It may work when all files are the same but most often files are removed from the new version which will leave garbage files that will be loaded
