### ISSUE TITLE
German translation for "Push tag to origin" is wrong

### ISSUE THREAD

**Issue by SeppPenner** [gitextensions/gitextensions#8071]
## Current behaviour
The German translation for the string "Push tag to origin" in the GUI is wrong. 

## Expected behaviour
The German translation should be "Tag nach origin pushen", not "Pushen Tag nach origin".

## Steps to reproduce
1. Use the German version of GitExtensions.
2. Checkout any Git repository.
3. Click "Create new tag here".
4. The window in the screenshot below occurs with the wrong translation.

## Screenshots
![Unbenannt](https://user-images.githubusercontent.com/9639361/81086685-2101fa00-8ef9-11ea-8950-72677110a9fb.png)

## Did this work in previous version of GitExtensions
No.

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

## Diagnostics

Not relevant.

**Comment by pmiossec** [comment]
I think you could contribute to the German translation here: https://www.transifex.com/git-extensions/git-extensions/language/de/

**Comment by gerhardol** [comment]
Front readme points to Wiki https://github.com/gitextensions/gitextensions/wiki/Translations#how-to-update-non-english-translations
Points to Transifex, what pmiossec linked to

Translations are tracked in Transifex, please raise the issue there (or rather fix tix the translation).

**Comment by SeppPenner** [comment]
Thanks, I have added my suggestion there.
