### ISSUE TITLE
Remember slider position between files view and a diff for the commit

### ISSUE THREAD

**Issue by yegor-mialyk** [gitextensions/gitextensions#8072]
## Current behaviour

Git Extension does not remember the slider position between files view and a diff for the commit.

![image](https://user-images.githubusercontent.com/16239726/81093702-4ff77c00-8eb7-11ea-9cc9-14fa24396642.png)

Every time you open Git Extension the slider position is reset and become very narrow.

## Expected behaviour

Git Extension remembers the slider position between sessions.

- Git Extensions 3.4.0.9381
- Build 096b4d56709e15a67b42a471bbe81ce3c95ae7f5
- Git 2.26.2.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4084.0
- DPI 240dpi (250% scaling)

**Comment by mstv** [comment]
All slider positions are stored in the settings file. But I guess, _sometimes_, they are tried to be restored before the regarding tabs have been created. The tab "File tree" seems to lose the slider position very often.

For the time being, the timing could slighty improve with the tab "Diff" made the first tab by moving the "Commit Info" beside the Revision Grid:

![grafik](https://user-images.githubusercontent.com/36601201/81118677-9d143600-8f29-11ea-8190-47e416e7d5f8.png)

**Comment by RussKie** [comment]
I don't think _all_ sliders' positions are remembered. It is a matter of going through and checking `splitterManager` callsites. Similar to #5938

**Comment by mstv** [comment]
I have tried before I wrote "_sometimes_" and "often". It is not always reset to the default position.

**Comment by yegor-mialyk** [comment]
@mstv, I tried to move Commit Info tab to the right, but it did not help me with my issue (still slider is reset to its default position).
