### ISSUE TITLE
v3.4 - Diff window no longer compares the head of 2 selected branches

### ISSUE THREAD

**Issue by laurin1** [gitextensions/gitextensions#8077]
Up to version v3.3.1, when I selected 2 commits (branches), I got an actual diff of those 2 commits (cumulative), but in 3.4, this no longer works.

3.3.1:

![image](https://user-images.githubusercontent.com/75857/81235244-15c5d180-8fc0-11ea-96fc-359b971e05c4.png)

3.4:

![image](https://user-images.githubusercontent.com/75857/81235495-aac8ca80-8fc0-11ea-9ece-0421c9c3208c.png)

**Comment by mstv** [comment]
This is a new feature #7899 -- though with a minor drawback.
The diff of two branches `b1` & `b2` contains 4 groups now:
- diff `b1` with `b2`,
- unique diff of `b1` with their common ancestor (named `BASE`),
- unique diff of `b2` with their common ancestor,
- common diff of `b1` & `b2` with their common ancestor.

The drawback is that empty groups are hidden by the `ListView` control.

Your branches are identical. That's why you only get the last group "Common diff with BASE".

**Comment by pmiossec** [comment]
>The drawback is that empty groups are hidden by the ListView control.

I'm happy to know that before I tried to compare 2 branches because I don't know if I would have struggled to discover it myself. I wonder for other users because it doesn't seem obvious....

@mstv Do you think if it's possible to display a line in the control like "No differences between these commits" (in green?)

**Comment by laurin1** [comment]
I don’t think this is a “feature” at all. At times I’m doing dozens of rebase and compare operations and now I have to stop and read the window, rather than just make sure it’s empty!!

**Comment by laurin1** [comment]
Why must developers always be “fixing what ain’t broke”!!

**Comment by laurin1** [comment]
Can we not add an option to not see these other compare? I won’t ever use these and they just make it more difficult.

**Comment by gerhardol** [comment]
> Can we not add an option to not see these other compare? I won’t ever use these and they just make it more difficult.

![image](https://user-images.githubusercontent.com/6248932/81253707-750bfc00-9029-11ea-9287-8a06b5ab3977.png)

**Comment by laurin1** [comment]
Thank you, I looked for a setting, but I didn't even know what to call it, nor did I understand what that setting meant when I read it. Also, I had no idea any of these options had tooltips. I checked and can't find others - if all or most don't have tooltips, users are most likely going to find ones that do have them. I move way too fast for tooltips to come up "on the fly".

**Comment by gerhardol** [comment]
There are tooltips on a few specific settings only. Many settings are described in the documentation too.
GE has generally too many settings, it is occasionally hard for new users to find specific details. (Personally I like to customize, but that is not the point here.)
It is hard to describe both settings and changes. Is anyone using the documentation site?
In this case, I found a tooltip to be more detailed. Some clarifications in #8078 

This feature was added to improve  reviewing the changes between branches. It has been of great help in developing this function at least...

> Do you think if it's possible to display a line in the control like "No differences between these commits" (in green?)

Not if there are other groups with information (unless the filter is abused for this).

For presentation we have discussed to collapse the unique and common diffs by default as well as not hiding empty groups. This is much harder to do than it seems. Maybe the wizard @NikolayXHD has some hints?
Anyway, it is not likely to be included in 3.4.

**Comment by mstv** [comment]
> not hiding empty groups. This is much harder to do than it seems.

I have a dirty hack: https://github.com/gitextensions/gitextensions/commit/d3229804f37d2d35a79c9afe57fb8b25726f0ae8. But I guess it might confuse users as well.
At least the icon should rather be an "equal" sign.

![grafik](https://user-images.githubusercontent.com/36601201/81345100-28233680-90b8-11ea-8ddb-b139012a62bd.png)

**Comment by RussKie** [comment]
I have few thoughts on the subject, I'll share when get to a computer

**Comment by RussKie** [comment]
> Anyway, it is not likely to be included in 3.4.

I think we need to fix it in 3.4 because the new behaviour is confusing.

**Comment by RussKie** [comment]
Few ideas:

* if there no diff between heads of selected branches/commits - have a dummy entry with "no changes"; else show changes
* all other groups to be collapsed by default - this way a user won't get visually overwhelmed by the "secondary" diff. Keep the user preference for the lifetime of the app but don't persist, as we don't re-instantiate the control.
* add a context menu entry to toggle the "secondary" diff 
* have the "secondary" diff disabled by default

**Comment by RussKie** [comment]
> * all other groups to be collapsed by default - this way a user won't get visually overwhelmed by the "secondary" diff. Keep the user preference for the lifetime of the app but don't persist, as we don't re-instantiate the control.

How about this?
![image](https://user-images.githubusercontent.com/4403806/81498948-23a28c00-930b-11ea-985a-1881b0b438fb.png)

**Comment by RussKie** [comment]
> * if there no diff between heads of selected branches/commits - have a dummy entry with "no changes"; else show changes

![image](https://user-images.githubusercontent.com/4403806/81499706-cf9aa600-9310-11ea-806e-dd17012573ba.png)

**Comment by mstv** [comment]
> have the "secondary" diff disabled by default

I disagree. Why does one compare branches? I think because of merging and rebasing. Then it is quite unlikely that the resulting diff will be empty always. So let the users discover the feature and if they really don't like it, let them turn it off, perhaps using the context menu.
(Collapsing the secondary diffs by default is a good compromise IMO and will give a clear indication. I must use it a while, until I can say whether I personally like the collapsed secondary diffs or whether it annoys me to need to double click them.)

**Comment by RussKie** [comment]
So.... like this?
![image](https://user-images.githubusercontent.com/4403806/81816170-4e404f00-956e-11ea-884e-c4c8f4c8d356.png)

**Comment by gerhardol** [comment]
> So.... like this?

I prefer to remove the "No changes" completely, 
If including, only keep for the first group, even if the empty are note displayed

Collapsing of other than the first is a little annoying to my usage, but probably a better default.

**Comment by RussKie** [comment]
> I prefer to remove the "No changes" completely,

As I said - without it we can't have the group shown. Without the first group it is very confusing for users (including myself - I struggled in my work environment with this).

Having only the first empty group (with a dummy) and not show other empty groups? I'm kind of split here... Probably ok, but could create a perception of inconsistent behaviour (shrug)

> Collapsing of other than the first is a little annoying to my usage, but probably a better default.

I heard you loud and clear. I agree that showing some diffs and hiding others could be confusing and annoying.
As a compromise I propose we collapse all empty groups (with dummies) by default, so the user only sees the diff (the left image above, the right is what the user gets if the groups are expanded). This way the user is aware there may be other diffs but for a specific selection those are empty.

**Comment by gerhardol** [comment]
> So.... like this?

With this discussion, I can live with this if @mstv is OK with it

**Comment by mstv** [comment]
> As a compromise I propose we collapse all empty groups (with dummies) by default, so the user only sees the diff (the left image above, the right is what the user gets if the groups are expanded). This way the user is aware there may be other diffs but for a specific selection those are empty.

This sounds like a good plan.

So there remain two open points for the dummy icons:
- suppress the context menu
- use an equal sign as icon (optional)

**Comment by RussKie** [comment]
> * suppress the context menu

Ah good point, I totally overlooked it! Thank you



> * use an equal sign as icon (optional)

Good suggestion. I didn't want to spend time on this until we had an agreement on the approach.

I'll try to wrap it all up tonight.

**Comment by gerhardol** [comment]
Add a flag in GitItemStatus for non Git item? 
Also to be set for error messages that are set to GitItemStatus.

**Comment by RussKie** [comment]
> Add a flag in GitItemStatus for non Git item?
> Also to be set for error messages that are set to GitItemStatus.

I can use some help with that

**Comment by RussKie** [comment]
> * use an equal sign as icon (optional)

I couldn't find an icon. Do we have one you suggest to use?

**Comment by RussKie** [comment]
I removed the icon, and collapsed empty groups:

![image](https://user-images.githubusercontent.com/4403806/81941449-31724d00-963c-11ea-95b4-dc67334503ae.png)
![image](https://user-images.githubusercontent.com/4403806/81941519-451db380-963c-11ea-9787-4e5ab86b4c62.png)
