### ISSUE TITLE
Git Extensions is very slow on Windows 10 with several graphic drivers

### ISSUE THREAD

**Issue by ThorstenSeddig** [gitextensions/gitextensions#8079]
## Current behaviour
My problem is when opening Git Extension then all Desktop Windows are very slow.
I found similar issues wich refer to the graphic drivers. My are:

Windows Update says its all up to date.
At the moment i have to close Git Extensions to work with the other programs.

Any ideas what i could do?

## Environment

I am working with Windows 10 Enterprise Version 1809 - Dell Laptop. My Git Extension Version is: 
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

Graphic drivers
Intel(R) UHD Graphics 630
NVIDIA Quadro P620

## Diagnostics

In Task-Manager there are many system interruptions with over 30% CPU usage when workting with Git-Extensions.

I also had same Desktop Windows performance when working with Visual Studio 2017. But there are in Options-Menu some properties to disable enhanced Graphic usage. After that VS works normaly and the other programs too.

**Comment by RussKie** [comment]
> Any ideas what i could do?

Not really. Without a solid repro there is hard to suggest anything.
Have a look at #2907 and https://github.com/gitextensions/gitextensions/issues/5314#issuecomment-415417060, may be you can get some ideas there...

**Comment by NN---** [comment]
It worked pretty well in 3.4RC but works very slow in the master build.

**Comment by NN---** [comment]
Uninstalled completely Intel Graphics Driver and now Git Extensions is super fast again.

**Comment by RussKie** [comment]
Wow it is so bizarre...

**Comment by ThorstenSeddig** [comment]
I close this issue. The solution for my DELL Laptop was that to update BIOS, update 24 drivers.
After that all works great inclusive Git-Extentison.
Thank you for your help.

**Comment by RussKie** [comment]
Thank you for the follow up

**Comment by arisliang** [comment]
Is the problem related to git or git extension? I have a feeling it's more to do with git.

**Comment by gerhardol** [comment]
> Is the problem related to git or git extension? I have a feeling it's more to do with git.

None of the problems are known to be due to the GE implementation in itself (maybe the frameworks used).

Some of the issues related to this is related to Git-for-windows, but that should not affect the GUI performance so much.

The issues related to graphics drivers should be related to .NET and Windows, requiring graphics updates.

**Comment by gregbradley** [comment]
Just encountered this problem on a new work laptop. It's a HP ZBook Create G7 Notebook PC with the following installation...

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.32.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4360.0
- DPI 168dpi (175% scaling)

I don't have permission to update any system drivers myself. Anything else I can try to resolve this issue?

**Comment by RussKie** [comment]
From all reports this is something between drivers and git... Maybe try disabling one of the graphics cards in the BIOS?
