### ISSUE TITLE
Show Options is not helping

### ISSUE THREAD

**Issue by ido-ran** [gitextensions/gitextensions#808]
Hi,
I think the Show Options link in both the rebase and push dialogs do not help and cause extra effort to use them.
The keyboard usage is not working well, when I press Enter on the link the focus does not shift to the first control (check box in this case) and I have to tab until I get to the first check box just to check it.

I think this feature should be revert.

Ido.

**Comment by jbialobr** [comment]
https://git-extensions-documentation.readthedocs.io/en/latest/settings.html#advanced
See General -> Always show advanced options
