### ISSUE TITLE
Right clicking an item in RevisionDiffControl results in null exception for the initial commit

### ISSUE THREAD

**Issue by fsfod** [gitextensions/gitextensions#8085]
## Current behaviour
Null exception trying to access FirstRevision when right clicking a file in RevisionDiffControl in the initial commit of a repo. 

## Expected behaviour
No null exception when opening the right click menu.

## Steps to reproduce
Select the initial commit of a repo and right click a file in the RevisionDiffControl.

## Did this work in previous version of GitExtensions
yes

## Environment
- Git Extensions 3.4.0.9381
- Build 096b4d56709e15a67b42a471bbe81ce3c95ae7f5
- Git 2.26.0.rc2.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by fsfod** [comment]
I think the bug came from the changes in #7899. I [fixed it locally](https://github.com/fsfod/gitextensions/commit/cdb66fb83591d108d3b5f213d1280a30b7c65509) just adding .Where(i => i.FirstRevision != null) check to the Linq expressions in RevisionDiffControl accessing FirstRevision.

**Comment by gerhardol** [comment]
A few more situations should be handled too, if just to simplify FirstRevision usage
Please review the PR
