### ISSUE TITLE
Windows with CenterParent may appear partial out of the screen

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#8091]
## Current behaviour

If you open a window with CenterParent that is bigger that the parent size, the window may appears out of the screen.

## Expected behaviour

The Location of the window should be restricted to the size of the screen.

## Steps to reproduce

Open GE
Reduce the size as small as you can
Move it the to top left
Open Settings (CTRL+,)

The Settings window is partial out of the screen

## Screenshots

Main window : 

![image](https://user-images.githubusercontent.com/9248729/81543919-0c00ed00-9377-11ea-9ba9-176ac8197605.png)

Settings window if Main Window is at top left : 

![image](https://user-images.githubusercontent.com/9248729/81544021-2f2b9c80-9377-11ea-9623-f64aded13216.png)

## Did this work in previous version of GitExtensions

I don't think so.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

## Diagnostics

The Plugin window have the same problem.

The Donate window and the About window don't have the problem (the location is forced so the window is all visible on the screen).

I made a try with an empty visual studio project with .Net Framework 4.8. If I create a window bigger that the parent, the location is not out of the screen. So there is something in GE but for the moment I can't figure out what the problem.

**Comment by bansan85** [comment]
I try to disable `AdjustForDpiScaling` in `ResourceManager.GitExtensionsFormBase.InitializeComplete()`

It solved the problem.

Then I enabled `AdjustForDpiScaling` and now I don't have the problem anymore. Strange...

But my installed version of GE still have the problem. It just fixed the problem for the compiled version but disabling temporary `AdjustForDpiScaling`.

**Comment by RussKie** [comment]
`AdjustForDpiScaling` is used to scale child controls. It doesn't affect containing forms.

**Comment by ivangrek** [comment]
There are several strategies.

The main window includes a child window
   -> show in the center of the main window.

The main window is smaller than the child window
   -> show in the center of the screen
      If the child window is larger than the screen
         -> show at the start point (0; 0) of the screen
   -> show child window in cascade
      If the child window is below the screen
         -> show at the start point (0; 0) of the main window

GitExtensionsForm.RestorePosition() do that.

**Comment by RussKie** [comment]
Fixed in #8341
