### ISSUE TITLE
Current stash list UI control disallow quickily navigate between the changes of all stashes

### ISSUE THREAD

**Issue by johnnytemp** [gitextensions/gitextensions#8108]
## Current behavior

The current "Manage stashes" UI is using combo-box to select which stash to show its changes. However, after user clicked or press ENTER on a selected stash, the focus on the combo-box control (with label "Show:") is lost. This makes the user cannot use the arrow key in the keyboard to quickly switch to another stash (they must use mouse with at least two clicks and one movement, to jump to the next stash).

Consequence: This is inconvenience if I want to inspect all stashes to see if they are still useful, so as to clean-up some useless ones.

P.S. this is so far the worst UI flow, which pushes me to find other Git GUI client to help.

## Expected behavior

After the user selected a stash in the combo-box of "Show:", in the "Manage stashes" view, the focus should be kept. And allow user to use up-arrow/down-arrow to directly switch to previous/next stash to show the changes immediately, with one keystroke only.

## Steps to reproduce

Choose Main Menu > Commands > "Manage stashes" that jump to the UI view which inspects stashes and their changes. Click the combo-box labeled by "Show:", and click one item. Then, try using up-arrow or down-array key to navigate to previous/next stash --> it is impossible, must use mouse with multi-clicks and movement (inconvenience).

## Screenshots

(focus of the "Show:" combo-box is lost after selected an item by mouse-clicking or keyboard ENTER of the combo-box list)

![image](https://user-images.githubusercontent.com/2296583/82008774-2bae5300-96a0-11ea-9c2d-2c18f29943cd.png)

## Did this work in previous version of GitExtensions

No.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
When a new stash is selected, the focus is moved to the first item in the list, this is the standard handling.
See the PR for added keyboard navigation with hotkeys and mnemonics.
