### ISSUE TITLE
bash: cd: too many arguments

### ISSUE THREAD

**Issue by mattiatosolinits** [gitextensions/gitextensions#8110]
### Behaviour

When _Console_ view is open and I _Change working repository_, if the new system path contains "space" characters the automatic **cd** command executed in the _Console_ returns:

`bash: cd: too many arguments`

### Workaround

Relaunch **cd** command manually adding double quotes.

### Screenshots

![image](https://user-images.githubusercontent.com/25243371/82054648-8f944400-96bf-11ea-8409-07b2000e5c6d.png)

### Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Fixed with #7612 . Will be in the next release.

**Comment by ciancilaura** [comment]
why has this too many arguments? ~/ $ cd ~ /pset1a/ $ 
bash: cd: too many arguments

**Comment by SkCephas** [comment]
help about too many argument in gitbub

**Comment by WazedKhan** [comment]
enclose it in double quotation bracket
Like : C:/SW/"SW2005"

**Comment by wesleygol** [comment]
Nice, tks.
