### ISSUE TITLE
Powershell user scripts do not run in the background

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8112]
## Current behaviour

Powershell user scripts do not run in the background although requested in the settings.

Is this a limitation of the powershell?
BTW: The powershell takes very long to start.

## Expected behaviour

Powershell window does not appear, at least not in the foreground.

## Steps to reproduce

- mark a user script as powershell script
- run it

## Did this work in previous version of GitExtensions

not checked

## Environment

- Git Extensions 3.3.0
- Build 8bc4a87aaec1a2ceef02e0cce6083229fe122622
- Git 2.26.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
It is probably a bug that PS scripts don't run in a background.

The start up time is PS specific, I think. E.g. start PowerShell ISE and
see how long before the cli initialises.
There may be ways to speed it up, but there's nothing right off the bat I
can suggest.

**Comment by mstv** [comment]
The behavior must have toggled: #9347.
