### ISSUE TITLE
Missing repository titles in dashboard

### ISSUE THREAD

**Issue by 13Reza59** [gitextensions/gitextensions#8126]
Hi,
In the dashboard view, all the repositories that generated by "gitextentions" are shown with no title. But all the old repositories and repositories that generated by "gitextentions" which replace their locations and we opened them are OK.
Thanks you.
![Untitled](https://user-images.githubusercontent.com/47471213/82406265-6d157880-9a7b-11ea-905a-8bdfc93f7aab.png)

**Comment by vbjay** [comment]
We have an issue template. You need to use it. 
![Screenshot_20200520-015010_Chrome](https://user-images.githubusercontent.com/3629489/82409779-6ddaea00-9a3c-11ea-8dd1-f2199fa6e8db.jpg)

**Comment by drewnoakes** [comment]
@13Reza59 I see this is your first ever GitHub issue. Thanks for taking the time to provide feedback.

As @vbjay points out, we have a template for bug reports that explains what information we need to be best able to help. Please edit your issue to include the relevant information from the template.

**Comment by drewnoakes** [comment]
I created a repo using Git Extensions and it appears in the dashboard for me:

![image](https://user-images.githubusercontent.com/350947/82422798-44ff3700-9ac6-11ea-8631-db0e39199950.png)

**Comment by vbjay** [comment]
I wonder if it is the highlight color?

**Comment by RussKie** [comment]
Please provide steps to reproduce.
