### ISSUE TITLE
Redundant context menu splitter

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8136]
## Current behaviour

![image](https://user-images.githubusercontent.com/4403806/82729972-99611b80-9d3f-11ea-8a31-540631282715.png)

## Steps to reproduce

Right click on a folder in the File Tree for the current revision

## Did this work in previous version of GitExtensions

I presume so

## Environment

- Git Extensions 3.4.0.9378
- Build 85ab13ae47d7f68deae8135694ef2c622e2b498b
- Git 2.16.1.windows.4 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4150.0
- DPI 144dpi (150% scaling)

**Comment by RussKie** [comment]
I don't think the top item ("Reset to the selected revision") is appropriate for the folder as well.

**Comment by gerhardol** [comment]
> I don't think the top item ("Reset to the selected revision") is appropriate for the folder as well.

Actually, it is. Reset could be displayed for submodules too (does not do exactly what a user expect though).
Will cleanup the order in the form a little, likely together with #8106
