### ISSUE TITLE
[NBug] Unable to parse object ID "[0x7FFD8954D3F0] ANOMALY: meanin...

### ISSUE THREAD

**Issue by wangruchao** [gitextensions/gitextensions#8148]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Current behaviour

Error reporting after overwrite installation

## Expected behaviour

Error reporting after overwrite installation
## Steps to reproduce
Error reporting after overwrite installation

## Error Details
```
System.FormatException: Unable to parse object ID "[0x7FFD8954D3F0] ANOMALY: meaningless REX prefix used
".
   在 GitUIPluginInterfaces.ObjectId.Parse(String s)
   在 GitCommands.CommitDataManager.CreateFromFormattedData(String data)
   在 GitCommands.CommitDataManager.GetCommitData(String sha1, String& error)
   在 GitUI.CommandsDialogs.FormBrowse.RevisionInfo_CommandClicked(Object sender, CommandEventArgs e)
   在 GitUI.CommitInfo.CommitInfo.RevisionInfoLinkClicked(Object sender, LinkClickedEventArgs e)
   在 System.Windows.Forms.RichTextBox.OnLinkClicked(LinkClickedEventArgs e)
   在 System.Windows.Forms.RichTextBox.EnLinkMsgHandler(Message& m)
   在 System.Windows.Forms.RichTextBox.WmReflectNotify(Message& m)
   在 System.Windows.Forms.RichTextBox.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Error reporting after overwrite installation

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git [0x7FFD8954D3F0] ANOMALY: meaningless REX prefix used
git version 2.22.0.windows.1
[0x7FFD8954D3F0] ANOMALY: meaningless REX prefix used
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

![image](https://user-images.githubusercontent.com/9548724/82889833-ecc0ad00-9f7d-11ea-808b-7450e6d1eee3.png)

**Comment by RussKie** [comment]
Steps to reproduce?

**Comment by gerhardol** [comment]
> Error reporting after overwrite installation

If this was a portable installation, the old version must be deleted first
