### ISSUE TITLE
Tab settings are not restored at startup

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#8153]
## Current behaviour

When starting up to dashboard, Commit info is always a tab, not restored to the upper right position where I prefer to have it. An empty panel is there instead.

Also, the diff slider may not be restored correctly, but it may be a consequence of panel not restored.
Window size is restored though.

## Expected behaviour

Panel positions and sliders are retained when starting up.

## Steps to reproduce

Start to 
Portable flag or not is the same for me.
I set the commit info to the upper right, seem to be the same also when keeping as a tab: The upper right panel is empty.

## Screenshots

![image](https://user-images.githubusercontent.com/6248932/82945451-3a98dd80-9f9d-11ea-8e13-89c45df57589.png)

## Did this work in previous version of GitExtensions

New in latest weeks
Maybe #8124?

## Environment

- Git Extensions 3.4.0.9558
- Build b613ba26577cd6262e108ae991a6ec2f9ae24fab (Dirty)
- Git 2.26.2.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
> Maybe #8124?

Most likely. I would have noticed if it occurred, i.e. never seen.

**Comment by gerhardol** [comment]
> Most likely. I would have noticed if it occurred, i.e. never seen.

You need to start to dashboard, I updated the description

**Comment by mstv** [comment]
😏 We should remove the dashboard (joking). It torpedos the restore of splitters as well as the display of hotkeys, and it has little utility for me.

**Comment by gerhardol** [comment]
> We should remove the dashboard (joking). It torpedos the restore of splitters as well as the display of hotkeys, and it has little utility for me.

Removing dashboard has crossed my mind, even if I use it.
I used to ignore the dashboard until the Symantec virus made Git very slow and since I use many instances, the last repo is not what I use. But the recently used is a better way, if you have pinned.

**Comment by mstv** [comment]
> But the recently used is a better way, if you have pinned.

That's how I do it, too.
But then comes Windows and scrambles the sequence of GE instances if a git operation takes too long due to too high CPU load (e.g. parallel build).
