### ISSUE TITLE
Epic link in Jira commit hint

### ISSUE THREAD

**Issue by ultimo-ss-henry** [gitextensions/gitextensions#8161]
## Feature description
Can we please use the epic link in jira commit hint.
We want to create a changelog based on the epic links in combination with a link to the user stories.
The latter can be found using {ParentIssueKey} 

https://confluence.atlassian.com/jirasoftwareserver/advanced-searching-fields-reference-939938743.html?_ga=2.120416587.296252710.1590667453-2020062814.1590667453#Advancedsearching-fieldsreference-epic_linkEpiclink

## Environment

- GitExtensions version: 3.3.1.7897
- GIT version: 2.24.0.windows.2
- OS version: Windows 10 Pro
- .NET version: .NET Framework 4.8.4180.0

**Comment by gerhardol** [comment]
Jira Commit Hint plugin is removed in 4.0, see #9659 
This issue is therefore closed as not applicable, link from #9659
