### ISSUE TITLE
Changing SSH setting to use OpenSSH does not persist

### ISSUE THREAD

**Issue by amcarthur** [gitextensions/gitextensions#8162]
## Current behaviour

When I go into settings -> SSH and try to change it from PuTTY to OpenSSH, it changes it while GitExtensions is opened. After closing GitExtensions and reopening it, the setting is changed back to PuTTY.

## Expected behaviour

Changing the setting from PuTTY to OpenSSH should persist after the GitExtensions application is reopened.

## Screenshots

Here is a GIF screen recording showing the issue: https://i.imgur.com/9Neh2BX.gifv

## Did this work in previous version of GitExtensions

I don't recall for sure. But I'm pretty sure it used to work.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)
- I have tried running GitExtensions as administrator to no avail.
- Also note that I have installed PuTTY manually, before I installed GitExtensions.
- I also tried reinstalling GitExtensions, making sure that OpenSSH is selected during install, to no avail. That's almost it's own bug, the fact that I have OpenSSH selected during install, and right after installing and running GitExtensions, PuTTY is selected. But most likely related.

**Comment by gerhardol** [comment]
Can you save any settings?

**Comment by amcarthur** [comment]
> Can you save any settings?

Yes, I can.

**Comment by RussKie** [comment]
I can't seem to replicate it.
Can you try https://github.com/gitextensions/gitextensions/releases/tag/v3.4 and see if it still an issue?

**Comment by amcarthur** [comment]
> I can't seem to replicate it.
> Can you try https://github.com/gitextensions/gitextensions/releases/tag/v3.4 and see if it still an issue?

Tried it, still an issue. When I get some time I'll download the source and try to debug it.

**Comment by amcarthur** [comment]
Deleting my User environment variable, GIT_SSH, solved the problem. It was set to the putty path, so I think GitExtensions kept setting putty enabled because of this. In the `GitCommands/Git/GitCommandHelpers.cs` file, the function [UnsetSsh](https://github.com/gitextensions/gitextensions/blob/bbd8039c54df329284d7c6f03c314c7bb38ed0dc/GitCommands/Git/GitCommandHelpers.cs#L123) does not appear to unset or delete this environment variable. I understand it is using the EnvironmentVariableTarget.Process flag, but I'm not sure why or if it matters. I tried changing it to EnvironmentVariableTarget.User and that also did not work. I'm not really sure what code changes I can make to fix this problem, or if it is even considered a GitExtensions bug.
