### ISSUE TITLE
GitExtensions crashes on startup on Win10

### ISSUE THREAD

**Issue by vocko** [gitextensions/gitextensions#8165]
## Current behaviour
GitExtensions started to crash on startup (was working before, not sure what changed). I`ve tried the RC version but also the last stable was crashing.

This is from my EventLog:
Application: GitExtensions.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException
   at GitExtensions.Program.RunApplication()
   at GitExtensions.Program.Main()

Faulting application name: GitExtensions.exe, version: 3.4.0.9381, time stamp: 0xec9e3d23
Faulting module name: KERNELBASE.dll, version: 10.0.18362.778, time stamp: 0x692cf0ab
Exception code: 0xe0434352
Fault offset: 0x00114192
Faulting process id: 0x2860
Faulting application start time: 0x01d637cc9a300d3b
Faulting application path: C:\Program Files (x86)\GitExtensions\GitExtensions.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: d9e83119-34db-4a16-85a2-c307d5a8152d
Faulting package full name: 
Faulting package-relative application ID: 

## Expected behaviour

Application starts, not crashes :-)

## Steps to reproduce

Start the application.

## Did this work in previous version of GitExtensions

It did work in the same version (3.3.1), not sure what has changed, possibly some windows updates installed and registry values for TLS 1.2 changed.

## Environment
Windows 10

- GitExtensions version:
- GIT version: 2.26.2 64 bit
- OS version: Win 10
- .NET version: Not sure, I should have installed multiple including 4.8

**Comment by RussKie** [comment]
This looks like there's something very wrong with your machine...

I'd start with verifying you have .NET 4.6.1 or above installed and it is
correct.

**Comment by vbjay** [comment]
Also repair he installation.

**Comment by vocko** [comment]
I did repair it, didn't help. But got the same issue with NCache, seems it has something to do with Windows Update.

**Comment by vbjay** [comment]
Yep. Points to net framework issues. Install or repair .net framework.

**Comment by RussKie** [comment]
Closing as it's not an issue caused by the app.

**Comment by vocko** [comment]
Just to confirm, issue was related to a corrupted Kernelbase.dll, not an applicaiton issue.

**Comment by mstv** [comment]
Thank you for the follow-up, @vocko.

**Comment by iamgitlearner** [comment]
stupid idiots, why u suggest buggi update!
