### ISSUE TITLE
Падение приложения (Out Off Memory)

### ISSUE THREAD

**Issue by pincher1519** [gitextensions/gitextensions#8167]
## Current behaviour

В режиме простоя с открытым репозиторием приложение падает с ошибкой OutOffMemory.
Перед падением наблюдается непрерывный быстрый рост занимаемой памяти, вплоть до 1.5Гб

## Expected behaviour

Нормальная работа

## Steps to reproduce

Запустить приложение
Открыть репозиторий
Ждать (от нескольких минут до нескольких суток, так как проблема плавающая)

## Screenshots

![20200601_130249](https://user-images.githubusercontent.com/34896014/83400382-6687e900-a40b-11ea-9b56-6f49cf9b4676.png)

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.26.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3928.0
- DPI 96dpi (no scaling)

[msinfo32_2.zip](https://github.com/gitextensions/gitextensions/files/4710755/msinfo32_2.zip)

Dump падения не приложить. в Архиве 7z он 65Мб

**Comment by RussKie** [comment]
Do you run any plugins? E.g. background fetch, build server integration,
etc.
Is it happening for all repos or only specific ones?

If you could archive and upload the process' memory dump somewhere and send
a link to our email gitextensions at outlook.com, I could have a look
what's going on.

**Comment by pincher1519** [comment]
> Do you run any plugins? E.g. background fetch, build server integration, etc. Is it happening for all repos or only specific ones?

Да, используется плагин с buildserver (teamcity). Все репозитории подключены к данному билдсерверу. Так как проблема плавающая, то проверить как себя будет вести без данного плагина не представляется возможным. Падение следующее может случиться спустя несколько суток.

> If you could archive and upload the process' memory dump somewhere and send a link to our email gitextensions at outlook.com, I could have a look what's going on.

К сожалению у меня нет вашего адреса рассылок с outlook.com. 
Dump +Временно+ расположил у себя на диске: https://drive.google.com/file/d/1PwzKb-0sf77HdB-GmTyE-MwfNi93EXPv/view?usp=sharing

**Comment by RussKie** [comment]
> our email "gitextensions at outlook.com"

😎

**Comment by RussKie** [comment]
This is kind of interesting - it looks the OOM is happening on the GC finalizer thread:
```
 	mscorlib.dll!System.Collections.Generic.List<System.AggregateException>.Capacity.set(int value) Line 123	C#	Symbols loaded.
>	mscorlib.dll!System.Collections.Generic.List<System.__Canon>.EnsureCapacity(int min) Line 414	C#	Symbols loaded.
 	mscorlib.dll!System.Collections.Generic.List<System.AggregateException>.Add(System.AggregateException item = Count = 2) Line 221	C#	Symbols loaded.
 	mscorlib.dll!System.AggregateException.Flatten() Line 425	C#	Symbols loaded.
 	mscorlib.dll!System.Threading.Tasks.TaskExceptionHolder.~TaskExceptionHolder() Line 115	C#	Symbols loaded.
```

Looking at the memory - it's sucked by `Reactive.Disposables.CompositeDisposable`, which is probably re-spinning itself while being collected, which allocated more memory instead of releasing it back...

Name | Inc % | Inc | Inc Ct | Exc % | Exc | Exc Ct | Fold | Fold Ct
-- | -- | -- | -- | -- | -- | -- | -- | --
LIB <<System.Reactive!Reactive.Disposables.CompositeDisposable>> | 41.6 | 18,035,716 | 184,375.328 | 41.6 | 18,035,682 | 184,374.781 | 18,035,592 | 184,369.984
 GitUI!GitUI.BuildServerIntegration.BuildServerWatcher | 41.6 | 18,035,716 | 184,375.328 | 0.0 | 0 | 0 | 0 | 0

**Comment by RussKie** [comment]
Duplicate of #3646

**Comment by pincher1519** [comment]
Причем окно браузера выключено.

![20200601_151951](https://user-images.githubusercontent.com/34896014/83408616-9343fc80-a41b-11ea-9127-3b95e94960d6.png)

**Comment by RussKie** [comment]
There are two different things

1. The integration facilitates build result visualisations in the revision grid
![image](https://user-images.githubusercontent.com/4403806/83411411-86df9400-a45b-11ea-9024-2eb8fcbfa295.png)

2. The build results page is shown as a tab (to the right of the commit info/tree/diff viewer) - that's what's turned off in your case.

**Comment by pincher1519** [comment]
> 2. The build results page is shown as a tab (to the right of the commit info/tree/diff viewer) - that's what's turned off in your case.

нет, отключена именно вкладка где я обвел. 
в grid статусы сборок на сервере отмечаются.

**Comment by RussKie** [comment]
Проблема не в том, показывается вкалдка или нет, проблема в самом плагине.

**Comment by pomer** [comment]
К этой проблеме. В фоне идет попытка открытие множественных подключений к билд-серверу. В конечном итоге на локальной машине заканчиваются доступные порты и работа по сети полностью умирает :(
[netstat.log](https://github.com/gitextensions/gitextensions/files/5317718/netstat.log)

**Comment by pomer** [comment]
Ошибка скорее всего связана с некорректной обработкой кодов ошибок HTTP. Если в настройках интеграции с сервером сборок отключить вход под учетной записью guest 
![settings](https://user-images.githubusercontent.com/1651955/94926099-eb256980-04c8-11eb-9723-71ee4f6eeab8.png)
или если на самом сервере сборок (TeamCity) запрещен доступ для guest, то сервер возвращает ошибку 401 в ответ на запрос от Git Extensions.
![response](https://user-images.githubusercontent.com/1651955/94926096-e9f43c80-04c8-11eb-8f2d-8af653108133.png)
Git Extensions при этом продолжает слать и слать запросы, постепенно приходя к печальному концу :(

**Comment by RussKie** [comment]
@matyasbach has kindly proposed a fix in #8716. Could you please test it:  https://ci.appveyor.com/api/buildjobs/i3wbpdfrenmh0g7w/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.10723-a1fb6669d.zip?
