### ISSUE TITLE
Improve WSL Performance and Permissions for `\\wsl$`

### ISSUE THREAD

**Issue by jasonkcarter** [gitextensions/gitextensions#8172]
## Feature description

This is a followup to some of the comments related to strange WSL behavior in #8171 

Would it be possible to add special handling for Git working directories located under the special `\\wsl$` Windows Subsystem for Linux path?  Specifically, rather than running a Windows version of `git.exe` for those directories and passing it `\\wsl$` paths, I think it would be much nicer to run the commands directly in WSL via its version of `git`.

This would involve several steps I've thought of, as well as some I probably haven't.

1. Detect `\\wsl$` in the current path argument for GE to enable the special handling.
2. Extract the WSL distro name from the path.  It should be the first directory name in the path after `\\wsl$\`.
3. Extract the remaining part of the path and replace backslashes with forward slashes.  This will be the working directory in WSL, call it `{wsl_cwd}`.
4. Detect any `\\wsl$\{distro}` paths in any arguments that are normally passed to `git.exe`.  Remove the prefix and replace backslashes with forward slashes.  Maybe replace double quotes around paths with single quotes?  Call the resulting arguments string `{wsl_args}`.
5. Send the final command to WSL git in the form:
`C:\Windows\System32\wsl.exe -d {distro} -- /usr/bin/git -C '{wsl_cwd}' {wsl_args}`

This would lead to significant performance improvements, as well as eliminate any strange issues with file system permissions and execute bits that come from trying to edit things via `\\wsl$\`.

For example, the following takes over ten seconds on my machine for a 166 MiB sample project:
`git.exe -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files=all --ignore-submodules=all \\wsl$\Ubuntu\home\ubuntu\MyProject\`

The following runs almost instantaneously on my machine with the same sample project:
`wsl.exe -d Ubuntu -- /usr/bin/git -C '/home/ubuntu/MyProject/' -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files=all --ignore-submodules=all /home/ubuntu/MyProject/`

Thanks for your consideration!

## Environment

- Git Extensions 3.4.0.9381
- Build 096b4d56709e15a67b42a471bbe81ce3c95ae7f5
- Git 2.22.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I can certainly see how useful this feature may be. However I see a steep learning curve and effort required to setup WSL, spin up a linux distro, etc., before this feature can be even worked on.
Do you think you could provide a script of some kind that can be run to setup an environment for dev?

**Comment by jasonkcarter** [comment]
The preferred way to install would be to follow Microsoft's instructions directly: https://docs.microsoft.com/en-us/windows/wsl/install-win10

I experimented with Powershell scripts, and while it's possible to automate the download and installation of Ubuntu, the end result isn't properly registered with wsl.exe as a distribution, so that's worthless for our purposes.

If you'd like, I can take a stab at a pull request myself, since C# Winforms development is one of my skills, albeit a bit rusty.  I mostly do web development these days.

**Comment by gerhardol** [comment]
How to handle path translations when parsing Git output?
If wsl-git was executing paths must be translated to \\wsl paths to work in diff tools etc. It will be a pain if this must be implemented for each and every Git command.

I assume some external commands could handle the native wsl paths too, that will be equally hard to handle, to know when to translate to native wsl.

**Comment by b3rnhard** [comment]
Has anybody tried using this as a workaround: https://github.com/andy-5/wslgit
I only changed the path to git.exe in the settings and left the path to linux-tools as is. With this I was not having problems with file permission changes of shell scripts in GE. So far it looks promising. I am observing reduced performance in revision links.

**Comment by gerhardol** [comment]
> Has anybody tried using this as a workaround: https://github.com/andy-5/wslgit

The performance in Win only repos is very slow though (much bigger difference than Win  git using \\wsl$).
Git path is global.
In this case you would probably want to use wslgit for all repos with \\wsl$ path, not really per repo though. Something for a private branch...

**Comment by gerhardol** [comment]
I have recently started to use wsl together with Git. Still quite some use in Win only.
Some alternatives, how this can be improved.
(this list may need to be updated)

1. Use git-for-windows and \\wsl$
+ Win performance is not affected
+ No changes needed
- A little slow
- Win Git do not handle executable bit correctly (this is a limitation in the file access, not in Git), so you basically cannot clone or checkout. core.filemode=false must be set too
- worktrees does not work (almost works for worktrees created with wsl git, but some internal commands in GE like handling COMMIT_MESSAGE fails)
 
2a. wslgit (as in the current version)
Works a little like the remote agent in VS Code, translating paths
wslgit could be sped up I assume, using separate wslpath commands for each possible path could slow down
+ Many paths work with native performance
- Very slow for Win repos, more or less unusable
- wslgit implements support command by command, all commands are not supported

2b. wslgit pass-through to Win git for win repos
+ Mostly full git speed
- Requires wslgit changes
- Can arguments be preserved? Quoting is hard

2c. Separate instances (installations) for GE win/wsl
Similar to 2a but Git is connected to the instance
Quick toggle possible?
+ wslgit will not need changes
- GE handles settings globally, hard to separate, Git is even in registry
- Hard to switch from Win to WSL repos

2d. GE configuration to use wslgit for certain repos
Probably a regex that defaults to \\wsl$ to use wslgit (settings per repo will be tedious to configure)
+ Mostly full Git speed
+ No Win impact
- GE changes

3. GE WSL awareness
Separate wsl binary (native Git), regex for repo paths.
Select Git binary depending on repo path.
Handle full paths in GE depending on if they are app internal or for Git.
Some specials, like for difftool where the Win version is required (a wsl gui is coming though - but then a separate alternative exists?).
+ Full speed, no external translation
- Considerable implementation required, could make GE internals complex

**Comment by gerhardol** [comment]
I am playing around with a combination of 2d and 3.
Less than 50 lines of changes so far (will be more.)

* If path is not \\wsl$ win paths is used and no impact at all.
* \\wsl$ git exe depends on commands
  - GUI commands like difftool always run in Windows (native Git)
  - Commands with progress info like push/pull/fetch always run in Windows
  - Commands with full paths need translation if wsl git runs (seem OK from what I see, rev-parse for instance)

Currently wslgit.exe is used, that could maybe be replaced with wsl directly. This adds another layer though, if something is missed in the GE handling, it may be handled in wslgit.exe (regardles, kudos to wslgit for pointing out certain situations).

So not all commands run with wsl git, but performance is still much better than for repos on Windows filesystems.
There is some specific knowledge added in GE though, all situations may not be handled the first release. I believe it is OK to have this as experimental for some releases, this improves functionality a lot regardless.

Some issues seen:
* git-status should only run from wsl. The command is normally much slower in Win anyway (and much slower in \\wsl$ paths), but win caches are trashed when running in wsl (not noticable the other way).
* Git add a full path for the path to the Git dir (.git is a file with Git worktrees). That file can be modified manually.
* filemode should be set to false in Windows, true in wsl
