### ISSUE TITLE
[NBug] The remote certificate is invalid according to the validati...

### ISSUE THREAD

**Issue by kishcs** [gitextensions/gitextensions#8179]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Steps to reproduce

Got this error, while updating git extn. Not sure its update related error or directly occurred from extn app.

## Error Details
```
System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
```

## Additional information
Got this error while updating git extn to latest

## Environment
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.25.1.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framewo

**Comment by RussKie** [comment]
I'm fairly certain we fixed this error in one of the later versions.
v3.4 is almost here, stay tuned.
