### ISSUE TITLE
Unable force push tag

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8188]
## Current behaviour

```
"C:\Program Files\Git\bin\git.exe" push --force-with-lease --progress "remote" tag v3.4
To https://github.com/gitextensions/gitextensions.git
 ! [rejected]            v3.4 -> v3.4 (stale info)
error: failed to push some refs to 'https://github.com/gitextensions/gitextensions.git'
```

This however works:
```
$ git push --force --progress "remote" tag v3.4
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 160 bytes | 80.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/gitextensions/gitextensions.git
 + 699c02c10...dd6d6ddce v3.4 -> v3.4 (forced update)
```

For tags `--force-with-lease` doesn't work, it has to be `--force`.

## Steps to reproduce

1. Create a tag and push to remote
2. Delete the local tag
3. Re-create the tag at a different commit
4. Force push the tag via `FormPush` (tags tab) with `Force` option.

## Did this work in previous version of GitExtensions

No idea, never tried it before.

## Environment

- Git Extensions 3.4.0.9381
- Build 096b4d56709e15a67b42a471bbe81ce3c95ae7f5
- Git 2.26.0.windows.1
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Delete tag on remote and create a new tag where you want it.

**Comment by RussKie** [comment]
Yes, but that's a) more operations, and b) 'force' option is still broken.

**Comment by lhiginbotham** [comment]
@RussKie I took a quick look at this and it seems simple - I can put a PR up for it
