### ISSUE TITLE
Git Extensions closes unexpectedly

### ISSUE THREAD

**Issue by Laser42** [gitextensions/gitextensions#8189]
## Current behaviour

I open a repository from dashborad, then wait the tree to be rendered, an after that I try to do something. I make a right-click on a branch label (in tree), meni is showed and then the app enxpectedly closes without any error.

## Expected behaviour
Do not close the app

## Steps to reproduce
1. Open Git Ext
2. Enter a repositiry
3. Wait until tree is loaded
4. Perform, a right click on branch's label in tree
5. The app closes

## Environment

- GitExtensions version: 3.3.1.7897
- GIT version: Git-2.23.0-64-bit
- OS version: Win10 x64
- .NET version: Core (varios versions 2.2-3.1), Framework 4.5.1 - 4.5.2

**Comment by RussKie** [comment]
The app requires .NET Framework 4.6.1 or higher, you appear to not have it.

Check EventViewer for any crash events.

**Comment by Laser42** [comment]
> The app requires .NET Framework 4.6.1 or higher, you appear to not have it. Check EventViewer for any crash events.

Thank you, I've got some info from EventLog:

> Приложение: GitExtensions.exe
> Версия платформы: v4.0.30319
> Описание. Приложение запросило завершение процесса через System.Environment.FailFast(сообщение строки).
> Сообщение: Failed to schedule time on the UI thread. A continuation would never execute.
> Стек:
>    в System.Environment.FailFast(System.String, System.Exception)
>    в Microsoft.VisualStudio.Threading.JoinableTaskFactory+MainThreadAwaiter.OnCompleted(System.Action, Boolean)
>    в System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].AwaitOnCompleted[[GitUI.ControlThreadingExtensions+ControlMainThreadAwaiter, GitExtUtils, Version=3.3.1.7897, Culture=neutral, PublicKeyToken=null],[GitUI.CommitInfo.CommitInfo+<>c__DisplayClass55_0+<<ReloadCommitInfo>g__LoadBranchInfoAsync|7>d, GitUI, Version=3.3.1.7897, Culture=neutral, PublicKeyToken=null]](ControlMainThreadAwaiter ByRef, <<ReloadCommitInfo>g__LoadBranchInfoAsync|7>d ByRef)
>    в GitUI.CommitInfo.CommitInfo+<>c__DisplayClass55_0+<<ReloadCommitInfo>g__LoadBranchInfoAsync|7>d.MoveNext()
>    в System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    в System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    в System.Runtime.CompilerServices.AsyncMethodBuilderCore+MoveNextRunner.Run()
>    в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
>    в System.Threading.ThreadPoolWorkQueue.Dispatch()
 Will install .NET Framework 4.8 and report here

**Comment by Laser42** [comment]
.NET Framework installation resolved the problem. it seems I had lost my recent version of .NET Framework by installing an earlier version.

**Comment by RussKie** [comment]
Thank you for the follow up.
