### ISSUE TITLE
Window isn't maximised - clicking top of screen changes focus to background application

### ISSUE THREAD

**Issue by davecapper** [gitextensions/gitextensions#8196]
## Current behaviour

The Git Extensions window isn't being fully maximised in Windows 10.

## Expected behaviour

Git Extensions window should take up the whole screen when maximised.

## Steps to reproduce

1. Maximise the Git Extensions window in Windows 10.
2. Move the mouse to the very top of the screen and click.
3. Whatever is behind the Git Extensions window gets the focus.

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
Cannot recreate

**Comment by davecapper** [comment]
Its not 100% consistent across the whole bar - if you click directly in the center it doesn't do it, but if you click off center it does.

**Comment by gerhardol** [comment]
> Its not 100% consistent across the whole bar - if you click directly in the center it doesn't do it, but if you click off center it does.

I tried that too - of course double click will restore the size but that is something different
But there is likely something else in your setup that is the trigger

**Comment by davecapper** [comment]
Testing it further, it happens on my second monitor, which has a different resolution to my main monitor. It doesn't appear to happen on my main monitor. The screen it does happen on is 2560x1440 with 100% text scale. The primary monitor is 3840x2160 with 150% text scaling.

**Comment by davecapper** [comment]
![image](https://user-images.githubusercontent.com/2432247/83994662-70c15e80-a99a-11ea-83c9-5b7f71b63ecf.png)

**Comment by davecapper** [comment]
Its not a big issue, I just keep closing the application behind Git Extensions.

**Comment by pmiossec** [comment]
> Its not a big issue, I just keep closing the application behind Git Extensions.

If I understand well your problem, I already noticed it (and talked about it in other issue) but it is not a Gitextensions bug and it happens with other applications. It's a windows bug. 

The application that you are closing is an application that uses the ribbon UI. It seems that this type of application steal the click of the top pixel line to the 'normal' applications.

**Comment by davecapper** [comment]
Wow - you are correct! It does happen for some other applications as well (e.g. Beyond Compare)! Some other programs don't have the same issue - e.g. Event Viewer and Office applications. I'm just using GitExtensions more than a lot of other applications so I've only ever noticed it there. 
Thank you for your feedback, I guess this should be closed as it's not specific to Git Extensions.

**Comment by pmiossec** [comment]
>Wow - you are correct!

It was really annoying for me too and it takes me a lot of time to really understand the issue.
I fail to find the comment where I raised the issue...

**Comment by RussKie** [comment]
Thank you for the assessment. Unfortunately as you've deduced it is a Windows issue.
(If you feel inclined) Please raise it to the Windows team via Feedback Hub app.

**Comment by skajfes** [comment]
For anyone having the same issue, there is a workaround. This is basically a Windows scaling issue when dealing with monitors with different DPI-s. 
The workaround is to go to properties of the exe (GitExtensions.exe), compatibility tab, click the Change high DPI settings button. Then check the checkbox to Override high DPI scaling, and select System (enhanced).

![image](https://user-images.githubusercontent.com/3857377/104021768-a2fc9e00-51bf-11eb-90d9-6a7735c2f152.png)

**Comment by pmiossec** [comment]
I didn't know this setting but enabling it has some bad effects where some texts are no more readable:

![image](https://user-images.githubusercontent.com/460196/104023634-3b941d80-51c2-11eb-9677-83cec8971781.png)

![image](https://user-images.githubusercontent.com/460196/104023669-45b61c00-51c2-11eb-8dbd-54c519979463.png)

So worst side effect than the bug ...

**Comment by skajfes** [comment]
It looks fine for me, so it probably depends on the specific configuration of monitors etc. I tried setting the option to Application but then the GitExtensions window just didn't scale on the lower res screen, it was huge. 
Hopefully this will help at least some people.
