### ISSUE TITLE
[NBug] System.UnauthorizedAccessException on showing dashboard because repository directory is now encrypted

### ISSUE THREAD

**Issue by thonigmann** [gitextensions/gitextensions#8205]
There are some existing issues regarding the same exception (#7063 is still open) but as far as I can see they are in different context.

## Current behaviour

A directory (in this case E:\base\prel8) with a repository has been used before with Git extension.
Then this directory was encrypted by a different user (actually a different user on a different OS, because the machine is dual boot Win7/Win10, but I don't think this matters).
Now, when Git Extensions tries to show the dashboard (e. g. upon startup) a System.UnauthorizedAccessException appears. The Exception can be dismissed by clicking the X in the title bar of the "Git Extension Error Report" window. Then an empty dashboard is shown.

## Expected behaviour

The exception is caught and handled similar to the situation where a previously used directory has been deleted or is not accessible because of missing network connectivity: the inaccessible directory is shown on the dashboard with a warning sign and the user can remove it from the dashboard.

## Steps to reproduce

1. User Alice creates a directory (read-/writable by all users) and initializes a repository there.
2. User Bob uses Git Extensions to look at this directory, then leaves Git Extensions.
3. User Alice encrypts the directory and all files and subdirectories.
4. User Bob starts Git Extinsions and gets exception.

## Error Details
```
System.UnauthorizedAccessException: Der Zugriff auf den Pfad "E:\base\prel8\.git\HEAD" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   bei System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   bei GitCommands.GitModule.GetSelectedBranchFast(String repositoryPath, Boolean setDefaultIfEmpty)
   bei GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.<ShowRecentRepositories>g__BindRepositories|61_0(IReadOnlyList`1 repos, Boolean isFavourite)
   bei GitUI.CommandsDialogs.BrowseDialog.DashboardControl.UserRepositoriesList.ShowRecentRepositories()
   bei GitUI.CommandsDialogs.FormBrowse.ShowDashboard()
   bei GitUI.CommandsDialogs.FormBrowse.InternalInitialize(Boolean hard)
   bei GitUI.CommandsDialogs.FormBrowse.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
directory is encrypted with another user id (dual boot system: encryption comes from Windows 7 user, the program is started by Windows 10 user)

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

![2020-06-09 06_02_07-Git Extensions Error Report](https://user-images.githubusercontent.com/8681635/84106446-6f844600-aa1b-11ea-86e2-f71b37b95c79.png)

**Comment by RussKie** [comment]
Please try v3.4. 
Whilst it won't solve your problem (i.e. it won't magically decrypt the content), it shouldn't show the NBug window.

**Comment by thonigmann** [comment]
> Please try v3.4.
> Whilst it won't solve your problem (i.e. it won't magically decrypt the content), it shouldn't show the NBug window.

Yes, that is correct, v.3.4.1 shows the dashboard without problems.

It still isn't quite perfect though (and I'm not talking about decrypting if there was any doubt about that)). The display on the dashboard gives no hint that the repository is not accessible (1). Deleted repositories on the other hand are shown with an exclamation mark (2).
![2020-06-19 01_04_16-Git Extensions](https://user-images.githubusercontent.com/8681635/85080284-12318700-b1c9-11ea-92be-8d7af0d11061.png)

When I click on the encrypted repo the program tries to open it, again resulting in an System.UnauthorizedAccessException (this time when trying to access .../.git/description).

**Comment by RussKie** [comment]
> The display on the dashboard gives no hint that the repository is not accessible (1). Deleted repositories on the other hand are shown with an exclamation mark (2).

We can only implement so many checks without affecting both sanity of developers and performance of the app.
"Deleted repositories" are something that the app knows you have accessed previously, but it was unable to find (e.g. a drive may not be available, or folder where the repo was is gone, or no .git folder there).

Verifying that the repo is accessible or is in fact a proper git repo, or it is not corrupted, or (insert some other check) - is not really a function of the app. 

The buck has to stop somewhere. We should crash the app if something is wrong, but other than that it is outside the scope.
