### ISSUE TITLE
[NBug] Git Extensions cannot start after fresh custom install

### ISSUE THREAD

**Issue by ronaldhoek** [gitextensions/gitextensions#8208]
## Current behaviour
The application won't start at all, after a fresh installation (did not have an older version installed).

## Expected behaviour
The applications starts

## Steps to reproduce
Install appliaction
Start application

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): Het systeem kan het opgegeven bestand niet vinden
   bij System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bij System.Diagnostics.Process.Start()
   bij GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   bij GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   bij GitCommands.ExecutableExtensions.<ExecuteAsync>d__11.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   bij Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   bij Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   bij GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
   bij GitCommands.GitModule.get_GitCommonDirectory()
   bij GitCommands.Settings.RepoDistSettings.CreateLocal(GitModule module, RepoDistSettings lowerPriority, SettingLevel settingLevel, Boolean allowCache)
   bij GitCommands.Settings.RepoDistSettings.CreateEffective(GitModule module)
   bij GitCommands.GitModule.get_EffectiveSettings()
   bij GitCommands.GitModule.GetEffectiveSettings()
   bij ResourceManager.GitPluginBase.Register(IGitUICommands gitUiCommands)
   bij GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   bij System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   bij GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   bij GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   bij GitUI.CommandsDialogs.FormBrowse.<<-ctor>b__43_0>d.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Starting application after fresh installation using custom settings.
**Disabled** in setup: 
- Desktop shortcut
- Translations
- Add to PATH
- Assignment to both links

## Environment
- Git Extensions 3.4.0.9608
- Build a4f5744118651776ec26d570b462e5ba8fc18afc
- Git - (minimum: 2.11.0, recommended: 2.25.1)
- Microsoft Windows NT 6.2.9200.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
It doesn't look like you have git installed....

**Comment by ronaldhoek** [comment]
Strange, GIT is installed (not default location though)
But would that directly crash the application?

**Comment by RussKie** [comment]
The app requires git, it can't function without.
The app shouldn't crash though, there should be a popup prompting to locate
or install git.

We need steps to reproduce the issue.

**Comment by ronaldhoek** [comment]
OK, I found out git was installed in "C:\Program Files\Git" (looks like the default folder).
However, I did NOT add the git 'bin' folder to the PATH (I don't use git without a client).

After adding 'C:\Program Files\Git\bin' to the 'path' of the correct user, the exception was gone.

Then removing the folder from the 'path' again, raises the exception again.

**Comment by ronaldhoek** [comment]
NOTE:
After I was able to start the application, I configured the application to use the full pathname to my 'git' executable and then removed it from the path again.
Now the application can start without exceptions.

**Comment by ronaldhoek** [comment]
Last:
When I again go to the configuration (when the folder is NOT added to the path) and I remove the full reference to the 'git' binary, I also get the exception.

**Comment by RussKie** [comment]
As I workaround I can think of - specify git.exe path in C:\Users\<user>\AppData\Roaming\GitExtensions\GitExtensions\GitExtensions.settings under
```xml
  <item>
    <key>
      <string>gitbindir</string>
    </key>
    <value>
      <string>C:\Program Files\Git\bin\</string>
    </value>
  </item>
```

**Comment by RussKie** [comment]
I can repro the issue by renaming "C:\Program Files\Git\bin" and "C:\Program Files\Git\cmd" folders.

What's strange instead of the dialog that would ask the user about the missing git.exe we get a failure to invoke TaskDialog control:
![image](https://user-images.githubusercontent.com/4403806/84339514-ecf9b300-abe1-11ea-9840-bc549e270149.png)
...then because the exception is caught and swallowed, we continue on with expectation that git.exe is found.

**Comment by RussKie** [comment]
@NikolayXHD can it be because of native hooks, and we don't have a hook established here? 😕

**Comment by ronaldhoek** [comment]
> I can repro the issue by renaming "C:\Program Files\Git\bin" and "C:\Program Files\Git\cmd" folders.
> 
> What's strange instead of the dialog that would ask the user about the missing git.exe we get a failure to invoke TaskDialog control:
> ![image](https://user-images.githubusercontent.com/4403806/84339514-ecf9b300-abe1-11ea-9840-bc549e270149.png)
> ...then because the exception is caught and swallowed, we continue on with expectation that git.exe is found.

I get that same exception to

**Comment by ronaldhoek** [comment]
> @NikolayXHD can it be because of native hooks, and we don't have a hook established here? 😕

Native hooks?  Like integrations into Windows Explorer?

**Comment by RussKie** [comment]
No, intercept interop calls for theming purposes.

**Comment by ronaldhoek** [comment]
> No, intercept interop calls for theming purposes.

Not that I know of specifically. But I do have the Windows 'dark' theme enabled.
Second: I'm currently working using remote desktop (RDP). Might that be a cause?

**Comment by NikolayXHD** [comment]
> @NikolayXHD can it be because of native hooks, and we don't have a hook established here?

Hi, I will look this evening.

**Comment by RussKie** [comment]
> But I do have the Windows 'dark' theme enabled.
> Second: I'm currently working using remote desktop (RDP). Might that be a cause?

No, we use some black magic to intercept calls to Windows to render Git Extensions in dark theme (https://github.com/gitextensions/gitextensions/issues/5489).

**Comment by lachlandowd** [comment]
I just tried installing using msi installer on fresh windows machine (no git install yet cos I know gitextensions normally prompts). Installed fine. Clicking desktop shortcut it asked for language and then crashed. Repeated attempts at running it produce the same crash.

**Comment by lachlandowd** [comment]
Is indeed a file not found exception. 
Stack trace if it helps:
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<ExecuteAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.get_GitCommonDirectory()
   at GitCommands.Settings.RepoDistSettings.CreateLocal(GitModule module, RepoDistSettings lowerPriority, SettingLevel settingLevel, Boolean allowCache)
   at GitCommands.Settings.RepoDistSettings.CreateEffective(GitModule module)
   at GitCommands.GitModule.get_EffectiveSettings()
   at GitCommands.GitModule.GetEffectiveSettings()
   at ResourceManager.GitPluginBase.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.<<-ctor>b__43_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()

**Comment by NikolayXHD** [comment]
What I have found so far, is that GitExtension.exe loads older version of comctl32.dll than the one requested in app.manifest (6.0.0.0)

![image](https://user-images.githubusercontent.com/12046452/84452607-e78e7e00-ac5e-11ea-9d30-cd723e922e16.png)

The version 6.0.0.0 does exist though

![image](https://user-images.githubusercontent.com/12046452/84452670-1a387680-ac5f-11ea-9bba-707cefc66866.png)

**Comment by RussKie** [comment]
Try https://github.com/gitextensions/gitextensions/releases/tag/v3.4.1

**Comment by ronaldhoek** [comment]
> Try https://github.com/gitextensions/gitextensions/releases/tag/v3.4.1

Just tested new release:
- made sure I still got the exception using the old (3.4.0) version
- removed 3.4.0
- installed 3.4.1
- and now I don't get an exception, but the dialog below:
![image](https://user-images.githubusercontent.com/5037087/84623943-adccaa00-aee0-11ea-990b-a0cf8f259afa.png)

After selecting the git location, the app starts without exceptions.
