### ISSUE TITLE
Incorrect EOL in diff

### ISSUE THREAD

**Issue by hsalameh** [gitextensions/gitextensions#8211]
## Current behaviour

When you have a change in the end-of-line character from LF to CRLF, the diff doesn't show that.

## Expected behaviour

The diff should show that the removed line had a LF while the added line has a CRLF

## Steps to reproduce
Using a windows machine with the git config core.autocrlf set to false, do the following:

1)clone the repo https://github.com/hsalameh/gitext-nonprinting-bug.git
2) open the repo in Git Extensions
3) look at the diff of commit fbd611
4) turn on the "Show nonprinting characters" option
3) as shown in the attached screenshot, the diff should show a difference at the end of the indicated line, but they appear exactly the same. The EOL character should be shown differently in the - and + lines

## Screenshots

![image](https://user-images.githubusercontent.com/3989390/84348220-68c41300-ab82-11ea-9e72-d0cba5fa24af.png)

## Did this work in previous version of GitExtensions

I don't know

## Environment

- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.24.1.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4018.0
- DPI 120dpi (125% scaling)

**Comment by gerhardol** [comment]
This is how git-diff reports the difference between files

**Comment by mstv** [comment]
Opened in my favourite external difftool, line 2 not line 1 seems to have the changed EOL:

![grafik](https://user-images.githubusercontent.com/36601201/84436342-90bf7f00-ac33-11ea-9797-4184a88c49bd.png)
![grafik](https://user-images.githubusercontent.com/36601201/84436448-c2384a80-ac33-11ea-9ed1-97cd1eb05c60.png)

The git output is misleading, so also the display in GE:

![grafik](https://user-images.githubusercontent.com/36601201/84437124-c7e26000-ac34-11ea-8e14-8ca2b7a0496c.png)
Anyway, GE should not filter out `^M` and try to display it.

(I have already criticised the alleged additional trailing new-line at the end of every diff in another issue.)

**Comment by gerhardol** [comment]
> Anyway, GE should not filter out ^M and try to display it.

But GE is not filtering, it displays what git-diff provides, from discussion in #7723

**Comment by hsalameh** [comment]
> Opened in my favourite external difftool, line 2 not line 1 seems to have the changed EOL:
> 
> ![grafik](https://user-images.githubusercontent.com/36601201/84436342-90bf7f00-ac33-11ea-9797-4184a88c49bd.png)

While git config core.autocrlf is set to false, if i clone and check out each of the commits and look at them in _my_ favorite text editor, i get this:

![image](https://user-images.githubusercontent.com/3989390/84461659-ff540b00-ac3a-11ea-98e7-016539e6466c.png)

This leads me to believe that the first line is actually different while it's not reflected in the git extensions diff.

**Comment by hsalameh** [comment]
Another one, using beyond compare

git difftool 49d822..fbd611

![image](https://user-images.githubusercontent.com/3989390/84542856-489e6c00-acc8-11ea-94f8-e9ed9b70c9bf.png)
