### ISSUE TITLE
Dark theme: git action log is too light

### ISSUE THREAD

**Issue by blitzmann** [gitextensions/gitextensions#8214]
## Current behaviour

When doing a fetch, or any git action, the command log is still a beige color

![image](https://user-images.githubusercontent.com/3904767/84403194-69d16080-abd3-11ea-976a-44dae5611343.png)

## Expected behaviour

I would expect the style to match the rest of the application: darker backgrounder with lighter text. Very similar to an actual terminal window :)

## Steps to reproduce

push / pull / fetch / checkout / etc

## Did this work in previous version of GitExtensions

N/A

## Environment

- GitExtensions version: 3.4
- OS version: Windows 10

**Comment by gerhardol** [comment]
The conemu style is set separate from the main theme
Adding the style to the theme would make it harder to change the style, there are a number of alternatives

![image](https://user-images.githubusercontent.com/6248932/84403753-568bb880-ac06-11ea-83dc-1d403b4410e8.png)

**Comment by blitzmann** [comment]
Ayyy, that works! Thanks!Didn't know about that particular option.

What are the thoughts on maybe directing the user to that in the theme section? Like, just a note like "Note: To change console styles, you'll have to change the settings in <go here>"

Additionally, the location of this setting isn't very obvious. This looks like it's strictly for the console window tab on the repository window, but the styles are also applied to the general console dialogs that pop up. I would think that console styles should be under Appearance > Console Styles, and then the Browse Repository Window would have the "show console tab" as well as the shell to run

Thoughts?

**Comment by gerhardol** [comment]
GE has too many options to present and order them in a good way. While I personally am fine with that, it is hard to describe to all users. Like above, should the conemu settings be related to the Browse window (where the console tab is but not the popup), separate or should the settings be distributed like you suggest (shell to run is probably not in the appearance category).
Whenever you change something, users get irritated, even if it is an improvement.
So most oldtime users are happy if nothing is changed...

The Scripts is rewritten using property grid, thi is considered for the rest of the settings too. But it is quite some work for minor user benefit. 

For the question with how to link this, I feel that documenting this in the info "leaf". I will add a note in the wiki for now.
https://github.com/gitextensions/gitextensions/wiki/Dark-Theme-status

**Comment by blitzmann** [comment]
>Whenever you change something, users get irritated, even if it is an improvement. So most oldtime users are happy if nothing is changed...

I've been involved in maintaining 9+ year old OSS where we have a lot of legacy features and options, so trust me when I say I absolutely know the conundrum here :P 

However, I am generally of the thought that proper placement of these options is for the betterment of the product in general, and definitely better for newer users coming in. As for older users, I suspect they aren't going in and changing the style of the console often enough where if it's moved they get aggravated? Additionally, one could use the search feature to find the settings if they were moved :)

Would you be open to a PR addressing this? I would be interested in maybe taking a look and seeing if I can move console styles to their own page under Appearance, and keep the shell to run where it's at.

Agreed with the other point of documenting that tho 👍

**Comment by gerhardol** [comment]
The structure of settings can be improved for sure. Maybe split the info and use tooltips is OK also for the confused users?

I approve everything that improves the product.
@RussKie I assume the plans for updating settings is not a priority right now and such a cleanup can be done

**Comment by pmiossec** [comment]
>Would you be open to a PR addressing this? I would be interested in maybe taking a look and seeing if I can move console styles to their own page under Appearance, and keep the shell to run where it's at.

I think it will be an improvement.

>console styles

I don't know what you include in that but one thing you should know is that at the moment, only the console style is applied to both of the console (in the popup and in the browse form tab) and not the font.

I think that it will be an improvement to also apply the font setting to the popup.

I can provide you with the fix as I just have made it in my repository...

**Comment by pmiossec** [comment]
You will find it here: https://github.com/pmiossec/gitextensions/tree/conemu_font

Finally, I will do a PR with that...

**Comment by pmiossec** [comment]
#8215

**Comment by RussKie** [comment]
Can we close this?

**Comment by pmiossec** [comment]
>Can we close this?

I would say yes as the discussion no more reflect the real issue which is to move the 2 console settings out of this page. From @blitzmann :

>Would you be open to a PR addressing this? I would be interested in maybe taking a look and seeing if I can move console styles to their own page under Appearance, and keep the shell to run where it's at.

I hope we will have a PR, especially now than #8215 is merged...

Perhaps best to create a new issue until the PR land.

**Comment by pmiossec** [comment]
Close in favor of #8306
