### ISSUE TITLE
Janapnese folder name do not indicate on recent repositories

### ISSUE THREAD

**Issue by kitahiro** [gitextensions/gitextensions#8220]
## Current behaviour
Folder name is indicated right, but when Japanese wide character is included in foldername,
it is not indicated.
Japanese wide character is wide character of UTF8.
It is happend both of Japanese and English for Language setting.

## Steps to reproduce
The repository which exists below the folder name including Japanese is opened.

## Screenshots
![RecentRepoNG](https://user-images.githubusercontent.com/18509645/84615629-7ec82f80-af04-11ea-9db2-d723a37e1b4b.jpg)

## Did this work in previous version of GitExtensions
It is happend in 3.3.1 too.

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.26.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
How to reproduce?

**Comment by kitahiro** [comment]
> How to reproduce?
The repository which exists in a folder including Japanese in the name is just opened. 
For example a folder name "D:\Customer\安田商店".
"安田商店" is wide character of Japanese.

**Comment by gerhardol** [comment]
A public repo where this is seen?

**Comment by pmiossec** [comment]
> 
> 
> > How to reproduce?
> 
> The repository which exists in a folder including Japanese in the name is just opened.
> For example a folder name "D:\Customer\安田商店".
> "安田商店" is wide character of Japanese.

There should be more than that.... because I can't reproduce:

![image](https://user-images.githubusercontent.com/460196/84657294-5cd6a900-af14-11ea-8b82-2f5235f3ffce.png)

**Comment by kitahiro** [comment]
Sorry, this may not be the bug.
Settings of "Appearance - Fonts - Application font" is changed to MS P Gothic from Meiryo UI, 
so indication of Recent repositories started to be indicated right.
The one which is not understood is the case that the whole pass including a Japanese character is not indicated any more.
The setting of a font is not changed from initial condition, so a linguistic person using Wide character seems to have to be careful.

**Comment by RussKie** [comment]
@kitahiro apologies, I'm having difficulties parsing your response.

Did you get recent repositories displayed correctly after changing the font (Meiryo UI -> MS P Gothic)?

**Comment by kitahiro** [comment]
Yes, I did.
The image is below.

![image](https://user-images.githubusercontent.com/18509645/84968021-77956180-b150-11ea-842d-07d8f6f42e23.png)

But, why is displayed "D:\Customer\安田商店" by Meiryo UI font on Excel right ?

![image](https://user-images.githubusercontent.com/18509645/84969099-f68b9980-b152-11ea-9b28-da6526e11edb.png)

**Comment by RussKie** [comment]
> But, why is displayed "D:\Customer\安田商店" by Meiryo UI font on Excel right ?

The tech is decades apart. Git Extensions is currently build on a tech stack originated in in '90s (i.e. .NET Framework and Windows Forms), that has a limited Unicode support. MS Office has been rewritten multiple times since then, and frankly the Office team has been pioneering a lot of stuff, including the Unicode support.

Quite likely when we migrate to .NET Core/.NET we'll see an improvement in this area.
