### ISSUE TITLE
Annoying Github extension wants to sign in

### ISSUE THREAD

**Issue by staticdev** [gitextensions/gitextensions#8222]
## Current behaviour

Every time I push using Github on VSCode I get this message telling "The extension 'Github' wants to sign in using Github." I have to Cancel it every time, since I don't want to.

## Expected behaviour

It should have a "Don't ask again button.".

## Steps to reproduce

Just push some code on Github using latest VSCode.

## Screenshots

![Screenshot from 2020-06-15 08-06-42](https://user-images.githubusercontent.com/1446633/84653533-f9348780-aee3-11ea-987e-83b7f66a86c8.png)

## Did this work in previous version of GitExtensions

Yes! It started when I upgraded, but I don't know the previous version.

## Environment

- GitExtensions version: 1.46.0 
- GIT version: 2.25.1
- OS version: Ubuntu Desktop 20.04 64 bit
- .NET version: N/A

## Diagnostics

-

**Comment by pmiossec** [comment]
It seems that you created this issue in the wrong project.
