### ISSUE TITLE
Git Error 

### ISSUE THREAD

**Issue by smarteez17** [gitextensions/gitextensions#8223]
Hi 

I getting this error . Please can someone help me I tried uninstalling everything and installing again nothing works .. this just started today

"C:\Program Files\Git\bin\git.exe" pull --rebase --progress "origin"
remote: Counting objects: 357, done.
remote: Compressing objects: 100% (348/348), done.
fatal: Unable to create temporary file '..................git/objects/pack/tmp_pack_XXXXXX': No such file or directory
fatal: index-pack failed
Done

Press Enter or Esc to close console...

**Comment by pmiossec** [comment]
The problem seems not to be with your software (so uninstall won't help) but more a problem with a corrupted git repository.

Clone it again.

**Comment by smarteez17** [comment]
Hi there 
I done that I delete all the repo and try to clone it again same error

**Comment by smarteez17** [comment]
![image](https://user-images.githubusercontent.com/35128168/84659225-5e55a080-af17-11ea-882a-64d5f09773a7.png)

When I tried to clone again get this errror

**Comment by pmiossec** [comment]
Which version? Are you up to date to the v3.4?

Could you also try to clone in a folder without space in it?

**Comment by smarteez17** [comment]
Hi this is the version i am using 
![image](https://user-images.githubusercontent.com/35128168/84659999-87c2fc00-af18-11ea-81e1-04e3d8569c0e.png)


and I have got space 

![image](https://user-images.githubusercontent.com/35128168/84660060-9a3d3580-af18-11ea-8374-bb152a16bcd4.png)


I created a new folder is empty

**Comment by RussKie** [comment]
Does destination folder exist?

**Comment by pmiossec** [comment]
I mean space in the folder path. So elsewhere than in "Work Application" folder....

**Comment by smarteez17** [comment]
![image](https://user-images.githubusercontent.com/35128168/84663396-657fad00-af1d-11ea-974b-0477d1d363e2.png)

**Comment by vbjay** [comment]
You still have a space in your path.

**Comment by smarteez17** [comment]
there no spaces 
![image](https://user-images.githubusercontent.com/35128168/84663735-d7f08d00-af1d-11ea-86bd-776167814e44.png)

![image](https://user-images.githubusercontent.com/35128168/84663762-e0e15e80-af1d-11ea-9e24-6d14e793bd48.png)

![image](https://user-images.githubusercontent.com/35128168/84663790-ea6ac680-af1d-11ea-9247-0d3ccf064e0c.png)

**Comment by vbjay** [comment]
Check your ntfs permissions.

**Comment by smarteez17** [comment]
I have full access

![image](https://user-images.githubusercontent.com/35128168/84665407-18e9a100-af20-11ea-8bb9-9f4430c17435.png)

![image](https://user-images.githubusercontent.com/35128168/84665464-29018080-af20-11ea-8be4-cf6d5e21ce52.png)

**Comment by smarteez17** [comment]
I have full permissions

**Comment by smarteez17** [comment]
any else I can try .. I try i few things now nothing working

**Comment by pmiossec** [comment]
You could try the command line `git clone http://YOU_URL.git` in a folder to see if that's your git or GitExtensions that cause the problem

**Comment by smarteez17** [comment]
so it working using cmd into that folder

**Comment by gerhardol** [comment]
Are the Git commands the same?
See the Git Command Log (F12), then try the commands from the commandline
The error message in GE comes from Git, so there is something with how you start GE vs the commandline
