### ISSUE TITLE
[NBug] Illegales Zeichen im Pfad.

### ISSUE THREAD

**Issue by arnew** [gitextensions/gitextensions#8224]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentException: Illegales Zeichen im Pfad.
   bei System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   bei System.IO.Path.Combine(String path1, String path2)
   bei GitUI.CommandsDialogs.FormClone.ToTextUpdate(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   bei System.Windows.Forms.Control.set_Text(String value)
   bei System.Windows.Forms.TextBoxBase.set_Text(String value)
   bei System.Windows.Forms.TextBox.set_Text(String value)
   bei GitUI.CommandsDialogs.FormClone.FromTextUpdate(Object sender, EventArgs e)
   bei GitUI.CommandsDialogs.FormClone.OnRuntimeLoad(EventArgs e)
   bei GitUI.GitExtensionsForm.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei ResourceManager.GitExtensionsFormBase.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
i tried to clone something

## Environment
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.25.1.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Duplicate of #7528
You entered characters in the path that are illegal
So the workaround is to just dont do that

A check added in 3.4/master #7633 (so popup instead)
Please try 3.4

**Comment by arnew** [comment]
ok, completely gone in 3.4.1
not even a popup, the text in the copy-n-paste buffer now seems to be ignored completely

**Comment by RussKie** [comment]
@arnew it isn't quite clear from your message - are you still having problems, or is it all fixed?

**Comment by arnew** [comment]
i have updated the comment above.
