### ISSUE TITLE
Release build is dirty

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8226]
## Current behaviour

see Environment

## Expected behaviour

release builds are considered clean

## Did this work in previous version of GitExtensions

yes

## Environment

- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.26.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Aye, one shouldn't release from a tag... Need to tweak the build script to consider tags, not just release/* branch.

**Comment by RussKie** [comment]
With that I'm not planning to re-release, 3.4.1 will remain as is.
