### ISSUE TITLE
"Yes, I allow telemetry" became checked after upgrading to v3.4.1

### ISSUE THREAD

**Issue by loop-evgeny** [gitextensions/gitextensions#8228]
## Current behaviour

I had v3.3.1 installed and had "Yes, I allow telemetry" unchecked. I clicked "Update" when prompted that an upgrade to v3.4.1 was available. After v3.4.1 was installed I opened the Help menu to find that "Yes, I allow telemetry" was checked.

## Expected behaviour

During upgrade the existing value is preserved. "Yes, I allow telemetry" is never checked automatically. During initial installation the user is asked whether they allow it.

## Steps to reproduce

Install v3.3.1, uncheck "Yes, I allow telemetry", upgrade to v3.4.1

## Did this work in previous version of GitExtensions

Not sure.

## Environment

- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.24.1.windows.2 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3620.0
- DPI 120dpi (125% scaling)

**Comment by kcowolf** [comment]
I saw this also.

**Comment by RussKie** [comment]
This is WiX setup skipping the page but probably still executing the code...

**Comment by oriash93** [comment]
Seems like these lines are the cause of the issue:

https://github.com/gitextensions/gitextensions/blob/730667814ad89e199efafaab536f95c77a54b744/Setup/UI/WixUI.wxs#L62-L63

Specifically this part: `<![CDATA[NOT Upgrading]]>`.

This change introduced in this commit  - [ddd46eb](https://github.com/gitextensions/gitextensions/commit/ddd46eb3c5b26056a4da72a88de54a81af71e2fa). Not sure if it was intentional.

**Comment by RussKie** [comment]
These two lines show the Telemetry page for fresh installations. This is intentional.

**Comment by oriash93** [comment]
> These two lines show the Telemetry page for fresh installations. This is intentional.

I know what they do, but if you look in the following line, the default behavior is **allowing** telemetry:

https://github.com/gitextensions/gitextensions/blob/730667814ad89e199efafaab536f95c77a54b744/Setup/Product.wxs#L30

That's why it does not preserve the existing value.

**Comment by loop-evgeny** [comment]
It should really not enable telemetry by default even for new installations. Failure to opt out is not "allowing" something, it could well be an omission or not caring about it. The installer should present radio buttons with neither selected by default.

**Comment by RussKie** [comment]
Everyone these days collects telemetry.

**Comment by loop-evgeny** [comment]
> Everyone these days collects telemetry.

That doesn't change the truth value of the statement "I allow telemetry".

**Comment by kcowolf** [comment]
Absolutely agree with @loop-evgeny on this.  It's very annoying when I realize the "Yes, I allow telemetry" box has become checked again only because I forgot to disable it again after upgrading.

**Comment by mstv** [comment]
Yep, we should pay attention here.

**Comment by sharwell** [comment]
My recommendation: include this page for new installations, but not for upgrade installations. Upgrade installations don't touch whatever option has been configured by the initial install or subsequent user action.
