### ISSUE TITLE
Git Extensions opens settings window on every startup

### ISSUE THREAD

**Issue by elloco999** [gitextensions/gitextensions#8229]
## Current behaviour
Every time I open Git Extensions the settings window opens first. After clicking the OK button the main window is opened and everything woks as expected.

## Expected behaviour
The main window is opened directly at statup without first opening the settings window.

## Steps to reproduce
1. Close Git Extensions if it is open.
2. Start Git Extensions.

## Did this work in previous version of GitExtensions
I have updated Git Extensions several times since I installed it, and this happens in every version I've used. I also removed Git Extensions completely and reinstalled the latest version but that didn't help either.

## Environment
- GitExtensions version: 3.4.1
- GIT version: 2.12.2.windows.1
- OS version: Windows 10 Pro 1909
- .NET version: 2.0 / 3.0 / 3.5 / 4.0 / 4.8

**Comment by RussKie** [comment]
Could you please provide more information including a screenshot for us to triage the issue.

**Comment by elloco999** [comment]
I posted this issue right after updating to GitExtensions 3.4.1. I'm almost 100% certain it showed the settings window again so I figured I'd finally create an issue about it as this has been happening for about a year now with different versions and I could'n find any fix on the internet.

And what do you know, now the problem is gone... When I start GitExtensions it opens the main window directly on startup. I don't understand it, but I'm glad it's gone. Sorry to have bothered you with this.

**Comment by vbjay** [comment]
If only you had shown a screenshot of the settings screen that showed. The
program runs through some checks. It shows the settings screen with details
of the tests. I'll bet one of the tests failed.

**Comment by elloco999** [comment]
Ah, I didn't know that. I didn't think screenshots would have given any interesting information, that's why I didn't include them. If the problem ever occurs again, I'll be sure to make a screenshot.
