### ISSUE TITLE
Error popup at each action I do

### ISSUE THREAD

**Issue by fubo73** [gitextensions/gitextensions#8230]
## Current behaviour

I am using GIT Extension **portable** since a while. Now with releases 3.4.0 and 3.4.1 I am getting the message reported in screenshots section.
This happens at the end of any action I do: start the program, open a repo, commit, push, pull, ...

## Expected behaviour

In previous revisions I never got such kind of popups.

## Steps to reproduce

Extract portable overwriting previous revision and execute.

## Screenshots

![image](https://user-images.githubusercontent.com/49477802/84746318-1174d700-afb6-11ea-8617-03408700f3e8.png)

## Did this work in previous version of GitExtensions

Never happened in previous revisions.

## Environment

- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
I don't reproduce.
Do you install portable version always in the same directory?
And could you provide the information requested in the issue template (OS, .net framework,...)

**Comment by fubo73** [comment]
I reproduce it on 2 systems
OS: windows 10 1809 Apr 2020 CU
GIT: 2.27.0.1
.NET: 4.7.0

**Comment by fubo73** [comment]
Updated .Net to 4.8. Error still there.
I did another try:
- extract in a fresh folder
- copy Recent folder and GitExtensions.settings, GitExtensions.settings.backup and WindowPositions.xml from old folder
- start

Now it works without errors. Here the diffs:
- folders not present anymore:

> Dictionaries
> Diff-Scripts
> es-MX
> fi-FI
> hr
> ko-KR
> PuTTY
> ru-RU
> 

- files not present anymore:
> de\NBug.resources.dll
> ja\NBug.resources.dll
> Plugins\AppVeyorIntegration.pdb
> Plugins\AutoCompileSubmodules.pdb
> Plugins\AzureDevOpsIntegration.pdb
> Plugins\BackgroundFetch.pdb
> Plugins\Bitbucket.pdb
> Plugins\CreateLocalBranches.pdb
> Plugins\DeleteUnusedBranches.pdb
> Plugins\FindLargeFiles.pdb
> Plugins\Gerrit.dll
> Plugins\Gerrit.pdb
> Plugins\GitFlow.pdb
> Plugins\GitHub3.pdb
> Plugins\GitImpact.pdb
> Plugins\GitStatistics.pdb
> Plugins\GitUIPluginInterfaces.dll
> Plugins\Gource.pdb
> Plugins\JenkinsIntegration.pdb
> Plugins\JetBrains.Annotations.dll
> Plugins\JiraCommitHintPlugin.pdb
> Plugins\Microsoft.TeamFoundation.Build.Client.dll
> Plugins\Microsoft.TeamFoundation.Chat.WebApi.dll
> Plugins\Microsoft.TeamFoundation.Client.dll
> Plugins\Microsoft.TeamFoundation.Dashboards.WebApi.dll
> Plugins\Microsoft.TeamFoundation.DistributedTask.Common.Contracts.dll
> Plugins\Microsoft.TeamFoundation.Policy.WebApi.dll
> Plugins\Microsoft.TeamFoundation.SourceControl.WebApi.dll
> Plugins\Microsoft.TeamFoundation.Test.WebApi.dll
> Plugins\Microsoft.TeamFoundation.TestManagement.WebApi.dll
> Plugins\Microsoft.TeamFoundation.Work.WebApi.dll
> Plugins\Microsoft.TeamFoundation.WorkItemTracking.WebApi.dll
> Plugins\ProxySwitcher.pdb
> Plugins\ReleaseNotesGenerator.pdb
> Plugins\System.Collections.Immutable.dll
> Plugins\TeamCityIntegration.pdb
> pt-BR\NBug.resources.dll
> Translation\Dutch.gif
> Translation\Dutch.Plugins.xlf
> Translation\Dutch.xlf
> git-extensions-logo-final-256.ico
> git-extensions-logo.ico
> GitCommands.pdb
> gitext.sh
> GitExtensions.pdb
> GitExtUtils.pdb
> GitUI.pdb
> GitUIPluginInterfaces.pdb
> Gravatar.dll
> Hashes.txt
> ICSharpCode.SharpZipLib.dll
> NBug.dll
> NBug.pdb
> NetSpell.SpellChecker.pdb
> ResourceManager.pdb
> System.Reactive.Core.dll
> System.Reactive.PlatformServices.dll
> System.Reactive.Windows.Threading.dll
- other files not present: history of images

I presume that some dll is loaded from this folder rather than system folder.

**Comment by RussKie** [comment]
The portable version is not designed to be extracted over an old version.

**Comment by fubo73** [comment]
> The portable version is not designed to be extracted over an old version.

Thanks. I'll avoid starting from now :)
