### ISSUE TITLE
"Reset another branch to here" fails with paths containing spaces

### ISSUE THREAD

**Issue by mikebei** [gitextensions/gitextensions#8235]
## Current behaviour

Using the new "Reset another branch to here..." context menu option fails if the path to the repo contains spaces.

## Expected behaviour

Choosing a branch to reset should result in the chosen branch being reset to the chosen commit.

## Steps to reproduce

1. Create a repo in a directory that contains a space in its name.
2. Create an initial commit on master
3. Create a second branch on the initial commit, without checking it out
4. Create a second commit on master
5. Right-click the second commit and choose "Reset another branch to here..."
6. Choose the branch created on step 3.

## Screenshots

![GitExtensions_pGYPgFUBgN](https://user-images.githubusercontent.com/6351501/84800808-f3ae6e80-afc3-11ea-9c7f-52e17cf8e062.png)

## Did this work in previous version of GitExtensions

N/A, this is a new feature

## Environment

- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Please try the portable build in the PR
