### ISSUE TITLE
GitExtensions-3.4.1.9675-f49b4d059.msi install removes but does not replace exe

### ISSUE THREAD

**Issue by jpers36** [gitextensions/gitextensions#8236]
## Current behaviour

I ran the latest install from a prompt in the GitExtensions UI and now the .exe is gone.  I attempted a repair via GitExtensions-3.4.1.9675-f49b4d059.msi and the .exe is still gone.

## Expected behaviour

Upgrade does not lose the .exe

## Steps to reproduce

Ran the install from the UI. It warned a reboot would be necessary.  I accepted.  Install window went away.  .exe was gone.  Rebooted machine.  .exe still gone.  Ran repair from GitExtensions-3.4.1.9675-f49b4d059.msi. .exe still gone.

## Screenshots

![image](https://user-images.githubusercontent.com/17277652/84800690-278d9200-afcc-11ea-8fe6-2664379271b2.png)

## Did this work in previous version of GitExtensions

Yes, never had the .exe disappear before.

## Environment

- GitExtensions version: 3.4.1.9675-f49b4d059
- GIT version: 2.24.1.windows.2
- OS version: Windows 10 Enterprise
- .NET version: 3.1.400

**Comment by jpers36** [comment]
Uninstalled and reinstalled using the .msi.  Still no .exe.

**Comment by jpers36** [comment]
Downloaded and ran GitExtensions-3.4.0.9608-a4f574411.msi instead.  Received an .exe.  So 3.4.0 includes an .exe but 3.4.1 does not.

**Comment by gerhardol** [comment]
3.4.1 contains an .exe
Check the anti virus logs

**Comment by RussKie** [comment]
This is an environmental issue on your machine. There is nothing we can do about, I'm afraid.
