### ISSUE TITLE
Blame view author avatar column shows black artifacts

### ISSUE THREAD

**Issue by gyula-kun-szabo-epam** [gitextensions/gitextensions#8241]
## Current behaviour

Blame view author avatar column has strange black artifacts.
The black "wedges" look like some clipped graphical elements.
They resemble to distorted/clipped "inserted block" margin markers of some GUI diff tools.

## Expected behaviour

The black artifacts should not be shown.
If they have a real purpose then they should be displayed correctly, optionally with some tooltips about what they are or at least they should be documented somewhere in the user guide.

## Steps to reproduce

- Select a file with a history containing multiple edits, inserts and deletes by different authors in the "Diff" tab of a commit . The changes should contain hunks of at least 4-5 contiguous lines.
- Open the blame view (using either hotkey "B" or context menu on the file in the list of files of the commit).
- Observe the author avatar column on the left. There are black artifacts present, similar to the ones shown in the attached screenshot.

## Screenshots

![blame-view-black-artifacts-in-avatar-column](https://user-images.githubusercontent.com/60139026/84897697-55dfa000-b0a6-11ea-9f93-bebdb2a0132b.png)

## Did this work in previous version of GitExtensions

Not checked.

## Environment

Pasted from "About" dialog:

- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.25.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
In fact, that's a bad handling of the "Fallbback avatar style" when set to "none".

![image](https://user-images.githubusercontent.com/460196/84899696-49107b80-b0a9-11ea-9610-1a1e2d87a348.png)

That's this image that is not well resized.
Switch to "author initials" and you won't have this bad display anymore...

**Comment by gyula-kun-szabo-epam** [comment]
In my setup the fallback is set to Robohash (see the small robot heads in first screenshot) and the clipped shoulder is still visible, so this bug seems to be affecting more fallback types, not only "None".

**Comment by pmiossec** [comment]
@gyula-kun-szabo-epam Could you test the portable version for the pull requested done to fix this bug? And report the result, please..

You will find it here: https://ci.appveyor.com/api/buildjobs/w616e79ro5m733og/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.9914-41ebc4e75.zip

**Comment by gyula-kun-szabo-epam** [comment]
> @gyula-kun-szabo-epam Could you test the portable version for the pull requested done to fix this bug? And report the result, please..
> 
> You will find it here: https://ci.appveyor.com/api/buildjobs/w616e79ro5m733og/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.9914-41ebc4e75.zip

Tested the above mentioned portable version, the default avatar image is properly resized now.
