### ISSUE TITLE
Pull fail

### ISSUE THREAD

**Issue by LayneXian** [gitextensions/gitextensions#8243]
## Current behaviour

When try to pull, I get an error with message:
"C:\cygwin64\bin\git.exe" pull --progress "origin"
error: cannot run C:\cygwin64\bin\ssh.exe: No such file or directory
fatal: unable to fork
Done
Press Enter or Esc to close console...

If I change the SSH configuration as: Tools->Settings->Git Extensions->SSH, change it from "Other ssh client C:\cygwin64\bin\ssh.exe" to "OpenSSH", then pull can work fine.
But if I reopen GE client, the configuration will be back to "Other ssh client C:\cygwin64\bin\ssh.exe" and pull can't work. I try to search "SSH" in issues list here, no solution can help.
This error happens when I have a new laptop and install latest cygwin. I try with GE 2.5/3.3/3.4 and get same results. One of my colleagues get same error.

Another GE error is when I try to commit. It announces "python3 access..." which may has similar root cause with above error. I'll try to handle it later.

## Expected behaviour

Pull work fine.

## Steps to reproduce

Just click pull button.

## Screenshots

![image](https://user-images.githubusercontent.com/8424708/85003716-2bb2de80-b189-11ea-9161-bdfe409744dd.png)

## Did this work in previous version of GitExtensions

No.

## Environment

- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.21.0 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 120dpi (125% scaling)

**Comment by LayneXian** [comment]
BTW, ssh.exe is always in the folder but GE announces can't find it.

**Comment by vbjay** [comment]
Quit using cygwin. Install git for windows.

**Comment by RussKie** [comment]
Check for `GIT_SSH` environmental variable, it may be set which interferes with Git Extensions' ability to resolve it

**Comment by LayneXian** [comment]
> Check for `GIT_SSH` environmental variable, it may be set which interferes with Git Extensions' ability to resolve it

Yes, I did check this environmental variable from some information of other issues.
I don't have it on my PC. And I did try to set it to the path C:\cygwin64\bin but nothing changed.

**Comment by LayneXian** [comment]
> Quit using cygwin. Install git for windows.

With this change(using git from Windows), I got more errors. But one change is the configuration of SSH could be saved.
Actually all settings I have now works fine on my old laptop and most of my colleagues.
I guess maybe something is not compatible with latest cygwin/plugins.

**Comment by LayneXian** [comment]
Now when I run below command directly in cmd.exe, it works.
"C:\cygwin64\bin\git.exe" pull --progress "origin"
But as we can see from the pic, it fails when calling that from GE.
It should be an error of ssh.exe path. But I can't figure out where is the problem.

**Comment by vbjay** [comment]
More than likely you didn't finish setting up git for windows with GE. Try it with putty. Install putty and point the paths of putty to installed versions.  Make sure you have latest git and putty.  You mentioned errors but did not say if they were the same or not. 
Point git path and also point the folder for linux tools to be all git fur windows. None should use cygwin. 

![image](https://user-images.githubusercontent.com/3629489/85119854-64d26980-b1f0-11ea-90e2-f9a83817cf4b.png)
![image](https://user-images.githubusercontent.com/3629489/85119924-80d60b00-b1f0-11ea-9c12-361f8ec7b099.png)
![image](https://user-images.githubusercontent.com/3629489/85120037-a7944180-b1f0-11ea-98fa-57c385b925d8.png)

**Comment by vbjay** [comment]
https://cygwin.com/faq/faq.html#faq.using.fixing-fork-failures

**Comment by RussKie** [comment]
Closing as I don't believe there is anything wrong with the app itself. Happy to re-open if we get new information suggesting otherwise.
