### ISSUE TITLE
RevDiff: diff second/first parent to working directory

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#8253]
## Current behaviour

GE has code to compare the parent to the first/second revision to the working directory (see also 2.x below) in RevDiff.

Similar, for FormDiff "Parent to Compare -> Working directory"
(For most of the discussions, this is ignored as FormDiff is now mostly replaces by functionality in RevDiff, I have not often seen anyone use the form.)

Note: There are tests that executes as expected. This problem was introduced around the time that the code was refactored to enable tests (for a very specific part of the functionality, not meaningful at all IMO, but there are other opinions about that).

## Expected behaviour

Remove this functionality, slightly confusing and apparently very little usage. You probably want to use the File History anyway to see commit info (#8193 provides a better interface to make special comparisons too.)

## Steps to reproduce

See screenshots

Rightclick file with parent for both first/second revision where parent-to-second is not the same as first revision

Similar for FormDiff, select a commit in a branch unrelated to current and Compare to current branch.

## Screenshots

![image](https://user-images.githubusercontent.com/6248932/85933098-5c0a2380-b8d3-11ea-9674-545db692cf8f.png)

![image](https://user-images.githubusercontent.com/6248932/85207719-065dd600-b32b-11ea-8362-e6633f60a016.png)

![image](https://user-images.githubusercontent.com/6248932/85207741-3a38fb80-b32b-11ea-8995-cc87f2bef343.png)

## Did this work in previous version of GitExtensions

2.x

![image](https://user-images.githubusercontent.com/6248932/85207374-b41bb580-b328-11ea-829e-a1488bf09e30.png)

## Environment

- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Since it seems that nobody has complained about the missing submenu items, I'd remove them.
At first glance, I don't see why one wants to compare to the second last revision without checking the commit info. I'd hit `Ctrl+P` and `Alt+F3` in this case.
