### ISSUE TITLE
Unusably slow for whole ui

### ISSUE THREAD

**Issue by arisliang** [gitextensions/gitextensions#8261]
## Current behaviour

Recently the whole UI becomes so slow that it almost unusable.

## Expected behaviour
Should be reasonably fast.

## Steps to reproduce

1. Open the extension
2. Whole ui is slow: menu, button, list of commits, basically everything.

## Did this work in previous version of GitExtensions

Not sure since which updates, but it's quite recent, like maybe 2 weeks.

## Environment

- GitExtensions version: 
- GIT version: 
- OS version: 
- .NET version: 
![image](https://user-images.githubusercontent.com/1115503/85361658-2077fe00-b54f-11ea-800b-adbe60baa38d.png)

## Diagnostics

Here's the log
![image](https://user-images.githubusercontent.com/1115503/85361809-777dd300-b54f-11ea-8679-8ff722f9e9d8.png)

As the log shows, it takes 20+ seconds to just open a fresh ui.

**Comment by pmiossec** [comment]
Looking at your logs, we could see that all the git commands are very slow (`git --version` should be nearly instantaneous for example).

`git rev-parse HEAD` takes 8x less times on my computer.

You should have a problem with your Git (install or config)

**Comment by arisliang** [comment]
I think I have the latest git installed, what config might have been causing this slowness?

Found this link on git, as people reported git itself runs so slow on windows 10 before.
https://github.com/git-for-windows/git/issues/1129

**Comment by pmiossec** [comment]
> I think I have the latest git installed

Which version exactly? 

Could that be that? Does the slowness could have appeared after an upgrade? Did you tried a previous version?

Is your repository huge? If that's less likely the reason?

Did you try to run git from the command line (outside of Gitextensions) to see if that's the problem? For example `git --version`... 

Do you have an anti-virus that could slow the creation of processes (because git executable create a lot of sub processes)? 

You need to investigate on your side because it seems a platform specific problem...

**Comment by pmiossec** [comment]
Sorry, the version (2.27.0) is in the screenshot...

**Comment by arisliang** [comment]
>run git from the command line (outside of Gitextensions) 
yes, just tried a fresh command prompt, takes about 1-2 seconds to run the `git --version`. So I suspect it's something wrong at deeper level.

It's a company PC so there are some anti-virus program running. When I run on my own computer, `git --version` was instantly fast (same version).

It's not only `git --version` that is slow though, just clicking on `Help` on the GE menu, takes about 5 seconds to open the dropdown.

This is tried and same even on small repository, so we can probably rule out repository size.

**Comment by pmiossec** [comment]
>yes, just tried a fresh command prompt, takes about 1-2 seconds to run the git --version. So I suspect it's something wrong at deeper level.

Yes, that's indeed a problem on you computer that you need to investigate (perhaps with your company administrators).

>When I run on my own computer, git --version was instantly fast (same version).

&

>It's not only git --version that is slow though, just clicking on Help on the GE menu, takes about 5 seconds to open the dropdown.

You could see that all the git calls are slow on your company PC as they should be quick, like you could see it with you personal computer. I took the  `git --version` as an example because the command should be really fast as git does nearly nothing.

That's the slowness of **every** git command that slow a lot  GitExtensions everywhere.

**Comment by RussKie** [comment]
We had reports video drivers may cause significant git slowness, and
updating those reportedly helped (search issues).

Try excluding locations where you keep your git repos from antivirus, this
may provide some relief as well.

Other than that I don't think theres anything else we can do, sorry. You'll
need to seek help from git folks and/or your company sys admins.

**Comment by arisliang** [comment]
I just found on an another machine, the speed is correct. Here is its version

![image](https://user-images.githubusercontent.com/1115503/85818725-f5d2b300-b7a3-11ea-8409-aa3e7ed0693a.png)

![image](https://user-images.githubusercontent.com/1115503/85818749-084cec80-b7a4-11ea-9b61-209a3065ee57.png)

Other than the version difference, the another machine also doesn't have dedicated graphics card, while current machine has a nvidia card (not AMD card though)

**Comment by RussKie** [comment]
You can run 3.4.2 portable and confirm it works the same.

**Comment by arisliang** [comment]
Yes, confirmed with 3.4.2 portable, it worked the same.

![image](https://user-images.githubusercontent.com/1115503/85848139-3ef22980-b7db-11ea-9ce5-9e9c1394623d.png)

![image](https://user-images.githubusercontent.com/1115503/85848165-49acbe80-b7db-11ea-8372-cee92ec2f05d.png)

**Comment by arisliang** [comment]
Just wanted to update, the slowness is gone after restart the computer. Most definitely likely graphics driver issue.
