### ISSUE TITLE
[NBug] Der Prozess kann nicht auf die Datei "C:\Projects\Tropico6\...

### ISSUE THREAD

**Issue by imi0** [gitextensions/gitextensions#8263]
## Current behaviour

GitExtension crashed when trying to save over a file via "Save As" where a file lock is hold by another process

## Expected behaviour

Some error popup telling that GitExtensions could not save the file.

## Steps to reproduce

- Grab any file with a history
- Open another program that holds an write-exclusive lock on the file
- Try to use "Save as" on the file, attempting to overwrite it.

## Error Details
```
System.IO.IOException: Der Prozess kann nicht auf die Datei "C:\Projects\Tropico6\Tropico6\Source\Tropico6\Game\Building\T6Building.cpp" zugreifen, da sie von einem anderen Prozess verwendet wird.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   bei GitCommands.GitModule.SaveBlobAs(String saveAs, String blob)
   bei GitUI.CommandsDialogs.FormFileHistory.saveAsToolStripMenuItem_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
"Save as" from history on an older version over a file where another process holds an exclusive file lock.

I can understand, that GitExtension can't write over the file, but that isn't a reason to crash.. ;)

Note: I just got https://github.com/gitextensions/gitextensions/issues/8262 closed while I was editing the description text, so I hope that this here won't be closed as a duplicate of 8262.. lets see.

## Environment
- Git Extensions 3.4.1.9675
- Build f49b4d059c5b135b4b2bf9eae4f443f19f6ac5df (Dirty)
- Git 2.24.1.windows.2 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
> I can understand, that GitExtension can't write over the file, but that isn't a reason to crash.. ;)

Yep, that'd be the plan.

**Comment by RussKie** [comment]
@lhiginbotham @mstv I just tried to save a file over a locked file (in a Excel) in the current master (12615869044a4db1f95609c05af93665045eb181)
Here's the error message I got:
![image](https://user-images.githubusercontent.com/4403806/110305309-bce81f00-8050-11eb-9196-ffc31f58fdaa.png)

Disregarding the fact that it is reported as a fatal exception (because the error is thrown from a background thread), I think the error message is sufficiently clear.
Besides making sure the error is reported on the UI thread, I don't believe there is anything else to be done.
