### ISSUE TITLE
Can not stage files using 3.4.2

### ISSUE THREAD

**Issue by kevinwhine** [gitextensions/gitextensions#8271]
From the Commit dialogue I am clicking the multiple stage down arrow expecting two files to be moved from the top pane to the bottom pain.  However I am getting:

```
Stage 2 files

error:  TestsRepository/RiskManagement/RMUIRegressionAtl/Regression/AdvancedSearch-CD/Tests/Strings/CheckStringRendersMoreThanOneSelectedValueSummary.script: does not exist and --remove not passed
fatal: Unable to process path  TestsRepository/RiskManagement/RMUIRegressionAtl/Regression/AdvancedSearch-CD/Tests/Strings/CheckStringRendersMoreThanOneSelectedValueSummary.script

Done
```

Here is the environment information:
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 1.9.5.msysgit.1 (minimum: 2.11.0, please update!)
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
> Git 1.9.5.msysgit.1 (minimum: 2.11.0, please update!)

Please update git to the latest

**Comment by kevinwhine** [comment]
Thank you.  Done. Working.

Kevin
