### ISSUE TITLE
`SubmoduleStatusProviderTests` extremely slow

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8279]
## Current behaviour

Running tests under VS I've observed `SubmoduleStatusProviderTests` tests to take in excess of 7 minutes to complete.
![image](https://user-images.githubusercontent.com/4403806/85961060-19d40580-b9eb-11ea-8dc6-10624b92bbff.png)

## Expected behaviour

Tests must complete faster.

**Comment by gerhardol** [comment]
1,6 minutes for me. Six times execution time, virus that slows Git down?
Every test takes 4-5s, also the simple setup tests so most of the test time is likely to create repos etc.
The tests could be changed to execute in one testcase.

Not fast, but it actually test something.

![image](https://user-images.githubusercontent.com/6248932/86054586-b4b7f880-ba5a-11ea-80ba-b7cd434f1ba2.png)

**Comment by mstv** [comment]
Run all tests does not work anymore. It builds everything and does not run any test.

The SubmoduleStatusProviderTests took 6.6 minutes, too, with high CPU load by the anti-virus virus. I cannot turn it off on this machine.

**Comment by RussKie** [comment]
My stuff is run on a VM in Parallels, the way I always had it. No AV other
than the standard Windows Defender.

Since I refactored the build infra, I always run builds and tests from a
cli.
I just started running them again in a VS porting to .NET Core.
I'm going to check the master for issues running tests from a VS.

**Comment by sharwell** [comment]
I can do a profiling pass to see what's taking time here.

**Comment by sharwell** [comment]
So the general approach to use here leverages two things:

1. Use LibGit2Sharp for repository initialization, because it's faster than the Git executable. This is not currently possible for this test because there is no API to add a submodule (libgit2/libgit2sharp#1232, libgit2/libgit2sharp#1501).
2. Avoid deleting and recreating the entire repository between each test. Instead, reset the repository to its initial state. You're basically looking for something like `ReferenceRepository.Reset()`, except specific to the types of changes made to a repository by this test class.

Realistically you should be able to shave about 70% off the test time by avoiding some calls to git for all tests except the first.

**Comment by vbjay** [comment]
What about extracting zipped repo to temp folder to have it at a known
state. Then do things to the repo. Could also use a bundle. Add a remote to
the extracted bundle. Then just code the reset to do a reset and maybe
clean of working directory to a specific sha. Could even store different
sha's for different initial states.

**Comment by sharwell** [comment]
I'm opposed to extracting a zipped repo if it can be avoided any other way. Such a repository would not be reviewable if we need to make any changes to its form.

**Comment by vbjay** [comment]
Why I also suggested a bundle.   https://git-scm.com/docs/git-bundle

**Comment by sharwell** [comment]
😕 I don't understand how a bundle improves the ability to review changes.

**Comment by vbjay** [comment]
It's a repo. You can add a remote to it. Fetch from it, clone it, compare
branches.....

**Comment by vbjay** [comment]
Basically, we have a test setup process before tests run that generates or
copies the bundle to artifacts folder. Then each test that needs initial
repo state can either clone from bundle into testrepos\test name or id\ or
initial setup clones from bundle once and setup for each test resets repo
to x Sha. The bundle is your initial repo with initial state.  It could
have initial work at a known state. Then each test can test against the
results of doing x action to local repo.  This would allow us to do
whatever to the local repo and always reset to origin\initial for example.

**Comment by RussKie** [comment]
Whatever process we chose it has to be immune to concurrent access and race conditions as tests often run in parallel.

**Comment by sharwell** [comment]
> tests often run in parallel

xunit doesn't run tests _in the same class_ in parallel. Does nunit?

**Comment by RussKie** [comment]
I don't think so.

**Comment by gerhardol** [comment]
The solution to improve the tests I can see is a hack to check that [SetUp] only executes once for a fixture.

GE uses BeforeTest to setup the thread handling etc, but OneTimeSetup runs before that.
https://medium.com/a-layman/test-with-nunit-create-a-test-project-and-realize-the-execution-order-18c11b636b0c

> xunit doesn't run tests in the same class in parallel. Does nunit?

Seem to be possible, even if we have not set that up.
NUnit tests can be run in parallel, so changing the resource usage will require use of attributes
https://docs.nunit.org/articles/nunit/technical-notes/usage/Framework-Parallel-Test-Execution.html

For #8334 trying to improve the tests, I tried to setup according to **Parallel class with non-parallel methods** in NUnit documentation

**Comment by mstv** [comment]
Parallel test execution is _no_ option ATM. There are too many singletons, e.g. `AppSettings`.

**Comment by RussKie** [comment]
i looked at this problem last night, and a had a partial success. about
half of tests failed because they expected a clean state.
we need to reset submodules to first commit. I need help with that.

**Comment by gerhardol** [comment]
@RussKie see the PR for a solution 

For parallel: I just tried to setup the attributes correctly if parallel is enabled

**Comment by RussKie** [comment]
Much better:
![image](https://user-images.githubusercontent.com/4403806/87871072-e2a4b300-c9f0-11ea-8af2-290852a14c4d.png)
