### ISSUE TITLE
Git Extensions crashes when sharing screen

### ISSUE THREAD

**Issue by iamseanduffy** [gitextensions/gitextensions#8280]
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

When sharing the Git Extensions window via MS Teams, GE crashes after around 60 seconds.

**Comment by RussKie** [comment]
We need more information, error messages, call stack, crash dumps, etc. 
I'm sharing the app via Team and haven't had any issues.

**Comment by iamseanduffy** [comment]
There are no error messages shown in the UI, the app just completely dies.
I also couldn't see any obvious log files in the GitExtensions folder, where would they be located?

**Comment by RussKie** [comment]
Check the EventViewer for any errors

**Comment by RussKie** [comment]
Closing due to lack of follow up.
