### ISSUE TITLE
Constant CPU  usage and thread leak when TeamCityAdapter fails to connect to TC server

### ISSUE THREAD

**Issue by KrzysFR** [gitextensions/gitextensions#8281]
## Current behaviour

I noticed that, with recent versions, GitExtensions.exe usually consumes a constant fraction of cpu when idle after being opened a while. On my machine (24c/48t) that corresponds to 5.9% or ~2.8 cpu threads.

I found similar issues that seem to be caused by issues with GPU drivers but it did not seem to match my behaviour (running on AMD ThreadRipper, which does not have a integrated GPU).

Using dotTrace to capture a timeline trace, I find that there are multiple thousand threads all calling TeamCityAdapter.GetBuilds() every 2 sec (see below for more details)

## Expected behaviour

GitExtensions not spawning thousands of threads and using my CPU :)

## Steps to reproduce

- GitExtensions configured with TeamCity build server integration in `GitExtensions.Settings` file
- TeamCity uses NTLM auth.
- Open GitExtension on a repo with that file.
- I DO NOT see the build status and label indicators in the main GE view (even though they are checked in the View menu), nor do I see the TeamCity tab when view a commit.
- Let it run idle for a few minutes.
- GitExtensions.exe process consumes a fixed amount of cpu cores on my machine.
- Use JetBrains dotTrace to capture a Timeline of the running git-extensions.exe process (without touching it)
- Observe thousands of CLR Worker threads calling TeamCityAdpater.GetBuilds() every 2 sec (see below)

## Screenshots

Constant cpu use (5.9% on my machine is 2.8 cores, 0.059*48)
![image](https://user-images.githubusercontent.com/1662235/86108598-a4883380-bac3-11ea-9489-82b03d4ec81d.png)

Build server integration settings: (verified project name and build if filter they are valid)
![image](https://user-images.githubusercontent.com/1662235/86110207-8e7b7280-bac5-11ea-95e4-de42944e57ff.png)

View of dotTrace, filtering on `GetBuilds()`. The scroll bar is so small that this screenshot represents less than 1% of the total number of threads.
![image](https://user-images.githubusercontent.com/1662235/86109316-8838c680-bac4-11ea-87b9-301240454c51.png)

Zoomed view of the callstack:
![image](https://user-images.githubusercontent.com/1662235/86109422-aacadf80-bac4-11ea-81b7-8cbe9004c440.png)

## Did this work in previous version of GitExtensions

I don't remember this being an issue with older version (> 6 months old).

## Environment

- GitExtensions version: 3.4.2.9737 (but same issue with recent versions)
- GIT version: 2.24.1.windows.2
- OS version: Windows 10 2004
- .NET version: .NET 4.8, VS 2019 preview, .NET Core SDK 5.0, etc..
- AMD ThreadRipper 3960X, 64 GB RAM

## Diagnostics

I used JetBrains dotTrace to capture a trace of GE while it was running, and ... I found that there are literally multiple thousand threads all in a 2 second loop trying to call TeamCityAdapter.GetBuilds(). The dotTrace snapshot for about 30 sec of capture takes about 1GB and the dotTrace Timeline Viewer was almost not able to display the trace.

All the threads are similar:
- They are CLR Worker threads
- They all spend their time waiting, but wake up every ~2 seconds.
- The have the same callstack: `Scheduler.Invoke()` => `TeamCityAdapter.GetBuilds()` => `TeamCityAdapter.ObserveBuilds()` => `OnError()`

I *think* that one issue could be that the NTLM auth with the TeamCity server fails, and the code does not properly handle the case and respawn another worker thread ?

The full dotTrace is 1GB, compressed down to 130 MB with 7zip. Too big to attach here.

**Comment by KrzysFR** [comment]
Ok, so after review the teamcity configuration a bit, I found out that the Project Name was the old one.

Before the observed project was Project Name "Foo" with build id "Foo_UnitTests". But a few weeks/month ago I created a nested project "Foo_Backend" under "Foo", and moved the build into that one. I forgot to change the settings in GE which was using the old Project Name.

If I change the "Project name" to the correct one and apply the settings (click OK), the cpu usage drops down to 0. If change back the settings to specify a Project Name that is valid but a parent of the actual project name, and click OK, then the cpu usage  goes immediately back up to the fixed amount.

You can see in the cpu usage every transition is when I changed the settings to incorrect / incorrect / correct / incorrect / etc....
![image](https://user-images.githubusercontent.com/1662235/86119628-20d64300-bad3-11ea-8a3f-edd83fa4a15b.png)

It looks like when the TeamCityAdapter does not handle well an error from the TeamCity API corresponding to an incorrect project name?

**Comment by pmiossec** [comment]
Using too much CPU is the way to notify the user that the project id is not good.
If we follow https://xkcd.com/1172/ , I think that should not be fixed 🤣

**Comment by KrzysFR** [comment]
> Using too much CPU is the way to notify the user that the project id is not good.
> If we follow https://xkcd.com/1172/ , I think that should not be fixed 🤣

I agree, this way I know that git-extensions is running when I can hear the buzz of my watercooling pump and fans :) _I can also see that dotTrace has an O(N^2) in the handling of threads because I've been waiting for 5 minutes for the UI to refresh before being able to take a screenshot of the new trace..._

![image](https://user-images.githubusercontent.com/1662235/86123152-4ebe8600-bad9-11ea-84c9-862b7321834d.png)

![image](https://user-images.githubusercontent.com/1662235/86123294-7f9ebb00-bad9-11ea-972a-da30f91a63b9.png)

The trace also recorded 52,960 exceptions during 20sec, 52,868 of which are `System.ArgumentException` with message `The tasks argument contains no tasks.`:
![image](https://user-images.githubusercontent.com/1662235/86123532-f89e1280-bad9-11ea-8617-32137f3e959d.png)

**Comment by KrzysFR** [comment]
The "The tasks argument contains no tasks." exception probably comes from the `ContinueWhenAll(buildIdTasks, ...)` in [TeamCityAdapter.ObserveBuilds](https://github.com/gitextensions/gitextensions/blob/master/Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs#L195) when the list of tasks is empty.

The only way I see for `buildIdTasks` to be empty is if that all the `_getBuildTypesTask` tasks returned nothing, so the SelectMany on them will flatten everything into an empty list in `buildTypes`.

Since ContinueWhenAll(...) throws on an empty list, the following `ContinueWith(..., ... TaskContinuationOptions.OnlyOnFaulted)` will catch that, and OnError(...) is called on the observer. I'm guessing the Rx `LocalScheduler` will attempt to retry, span a new `NewThreadScheduler` and spawn more instances of this chain? This would explain the thousands and thousands of threads all starting from `Scheduler.Invoke(...)`

So I see two potential issues here:
- If the TC adapter cannot get any build id (empty list), it should handle that by not throwing
- The scheduler seems to be vulnerable to retry storms if there are exceptions in the wrong place, especially since it uses a `NewThreadScheduler`?

**Comment by pmiossec** [comment]
@KrzysFR No one in the team really know and maintain this part of the code or have access to a TeamCity instance to test it...

It seems that you are the best placed to fix this bug.
Do you think you could fix it and create a pull request?

**Comment by RussKie** [comment]
Great investigation, thank you.
I wouldn't be surprised if the issue is related to https://github.com/gitextensions/gitextensions/issues/3646 and https://github.com/gitextensions/gitextensions/issues/8167

**Comment by KrzysFR** [comment]
After putting breakpoints in the code, my initial idea was close, but I found the problem that explains the constant CPU consumption:

The HTTP request sent to the TC server to get the build ids, returns a 404 on the invalid project name. Reading the result on a failed HTTP transaction is not handled explicitly so there's a cascade of exceptions, but ultimately, it means that one of the taks in `_getBuildTypesTask` is Faulted.

The logic in `PropagateTaskAnomalyToObserver(...)` sees the exception, and calls `OnError(...)` on the observer. In the same thread, the observer created indirectly via `GetRunningBuilds(...)` fires again, invoking the same method again, etc... This task is not retry again after a long time, to the `_getBuildTypesTask` collections stay with the same faulted task.

So basically, there is a hot infinite retry loop that constantly checks the same set of failed tasks, again and again, without any delay. This explains the constant CPU churn.

There's definitely something weird with the retry logic in the build server integration: when an exception is passed back to the observe via `OnError(..)`, it is invoking some retry logic in Rx that end up calling back up the logic that creates a new task that will schedule a new invocation on `ObserveBuilds(...)` that ... fails again, etc.. etc...

The only issue for me is that logic is done globally for all build server plugins in [BuildServerWatcher.LaunchBuildServerInfoFetchOperationAsync()](https://github.com/gitextensions/gitextensions/blob/0112ae532b96a8231167b3b3f62af958f671c43d/GitUI/BuildServerIntegration/BuildServerWatcher.cs#L53), and I'm especially looking at the ".Retry()" at line 112 that does ... weird things? The documentation says that Retry will `Repeats the source observable sequence until it successfully terminates.` which seems vague.

My specific issue is with invalid project name that cause an 404 HttpException, but the way I see it, any particular exception occurring during the processing of a request with TC (500, corrupted XML, etc...) would trigger the same hot loop. Some loops "only" spawn thousands of threads, in some other cases it may end up allocating a lot of memory, explaining the `OutOfMemory` exceptions that are seen in the two issues linked above.

But since the retry logic is the same for all build server plugins, ... I'm not exactly sure how to fix it for the specific case of TeamCity. Also, maybe the same issues exists for different build server types?

**Comment by matyasbach** [comment]
I can confirm the same behavior (but it eats 20-100% of my cpu :O) with new version of GE (or one of the newest versions). DotTrace profile is similar (I can send it to anyone interested). The issue in my case occurs when I disconnect from VPN, which gives me access to the TeamCity server.

**Comment by alastairtree** [comment]
GE is awesome - thanks to all the contributors. Also experiencing this issue, and have noticed the teamcity integration is generally a bit buggy which totally makes sense if contributors are not familiar with it or lack a test instance. 
In case it helps, JetBrains provide a public instance of team city for open source projects at https://teamcity.jetbrains.com/?guest=1 so you could use a [clone of project like nhibernate on GitHub](https://github.com/nhibernate/nhibernate-core) and [their public teamcity builds](https://teamcity.jetbrains.com/viewType.html?buildTypeId=bt7) as a test environment when you were working on it.

**Comment by RussKie** [comment]
Thank you for the investigation.

If you raise a draft PR it would be easier to discuss the issue further. I
personally wouldn't be surprised if the issue affects all plugins.

**Comment by RussKie** [comment]
@matyasbach has kindly proposed a fix in #8716. Could you please test it:  https://ci.appveyor.com/api/buildjobs/i3wbpdfrenmh0g7w/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.10723-a1fb6669d.zip?
