### ISSUE TITLE
Crash right after every Push

### ISSUE THREAD

**Issue by trsh** [gitextensions/gitextensions#8283]
Widows 10 Pro 64x (v2004)
Git extensions:

```
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)
```
Dump: https://www.dropbox.com/s/6tpjsw9lj4x6qri/ConEmuTrap.zip?dl=0

Screenshot: 
![2020-07-03_121241](https://user-images.githubusercontent.com/3727523/86453511-938b2c80-bd26-11ea-8fdd-4bd483d46ad0.png)

**Comment by pmiossec** [comment]
As a workaround you could disable the use of ConEmu in GitExtensions settings

![image](https://user-images.githubusercontent.com/460196/86454698-eca39200-bd1f-11ea-8f4f-cfa910e208ef.png)

**Comment by trsh** [comment]
@pmiossec thank u!

**Comment by mstv** [comment]
Thank you for https://github.com/Maximus5/ConEmu/issues/2145, @trsh.

@RussKie, should we update to ConEmu 200615? Or do you expect too many conflicts with the switch to .NET Core?

**Comment by RussKie** [comment]
> should we update to ConEmu 200615

If that helps - sure.
I can deal with conflicts in the .NET Core branch.

**Comment by gerhardol** [comment]
https://github.com/Maximus5/ConEmu/releases

20200615 is listed as a preview still, but we have used previews before
I see nothing that is supposed to fix our usage though.

**Comment by mstv** [comment]
@trsh, could you try the following portable build with the most recent preview release (20.06.15) of ConEmu, please?
https://ci.appveyor.com/api/buildjobs/ymfhtecophb95pmb/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.9809-6d184c9eb.zip

**Comment by trsh** [comment]
@mstv works for me, no errors

**Comment by Maximus5** [comment]
There was a bug in ConEmu. Please update it to 20.07.13.

**Comment by RussKie** [comment]
Thank you @Maximus5
