### ISSUE TITLE
GitExtensions crashes during setup of "Git-Paths" with access denied exception

### ISSUE THREAD

**Issue by bernd5** [gitextensions/gitextensions#8286]
## Current behaviour
GitExtensions can't use `sh` from "C:\Program Files\Git\bin\"

## Expected behaviour
No Exception

## Steps to reproduce

Install git into its default location on Windows, Install GitExtensions and configure sh-tools.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): Zugriff verweigert
   bei System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start()
   bei GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   bei GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   bei GitCommands.ExecutableExtensions.<GetOutputAsync>d__4.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   bei Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   bei Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   bei GitCommands.ExecutableExtensions.GetOutput(IExecutable executable, ArgumentString arguments, Byte[] input, Encoding outputEncoding, CommandCache cache, Boolean stripAnsiEscapeCodes)
   bei GitCommands.Executable.GetOutput(ArgumentString arguments)
   bei GitUI.CommandsDialogs.SettingsDialog.CheckSettingsLogic.CanFindGitCmd()
   bei GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.PageToSettings()
   bei GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.SaveSettings()
   bei GitUI.CommandsDialogs.FormSettings.Save()
   bei GitUI.CommandsDialogs.FormSettings.buttonApply_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
setting path to git.exe which is located here "C:\Program Files\Git\bin\" 
(GitExtensions was complaining before that my sh tools were not configured...)

## Environment
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4180.0
- DPI 168dpi (175% scaling)

**Comment by vbjay** [comment]
Point it to your git for windows installed folder \bin.

**Comment by bernd5** [comment]
Yes this is what I did. But then GitExtensions throws an exception...
I tried to grant "everyone" all rights and to make it non write protected - but this did not work.

The exception text: "Zugriff verweigert" is the german text for "access denied".

**Comment by bernd5** [comment]
The issue seems to be solved with the path including "git.exe" and "sh.exe".
The folder is not sufficient - perhaps GitExtensions could check if it is a file or a folder.

**Comment by mstv** [comment]
So in order to reproduce it, the pathname of `sh.exe` should be input instead of the path where `sh.exe` can be found?

The error message will improve with #8278 at least, which is waiting for a review by @RussKie before I will complete this PR.

**Comment by vbjay** [comment]
Try usr\bin instead.

**Comment by vbjay** [comment]
C:\Progran Files\Git\usr\bin\

**Comment by bernd5** [comment]
With these settings it seems to work:
![Unbenannt](https://user-images.githubusercontent.com/26689688/86508422-4075b000-bde0-11ea-92c2-18f7069908aa.PNG)

But with these settings I get the exception:
![grafik](https://user-images.githubusercontent.com/26689688/86508438-6307c900-bde0-11ea-9fe2-22d64b366e18.png)

**Comment by vbjay** [comment]
Well yes. The first path is where the actual git exe is. It's a file path.
The second is a folder path.
