### ISSUE TITLE
'Run All Tests' failing to execute in Visual Studio 2019

### ISSUE THREAD

**Issue by gtisdelle** [gitextensions/gitextensions#8300]
## Current behaviour

After selecting 'Run All Tests' in Visual Studio, the projects build successfully, but the tests stop executing almost immediately.

## Expected behaviour

All tests should execute.

### Quick reproduction
The easiest way to reproduce the issue is by selecting 'Run All Tests' as described above.

### Narrowing the trigger conditions

From the error message below, it's clear that the failure is somewhere in  `GitUITests.Editor.FindAndReplaceFormTests`. (Commenting out the method `FindNextAsync_should_iterate_over_files` causes another test to fail within the same TextFixture.)

From the test explorer, it is possible to run all tests within `GitUITests.Editor` if it is selected but `GitUI.Tests` is not, and 'Test' is selected instead of 'Run All Tests'.

This works:
![good_run](https://user-images.githubusercontent.com/54757231/86830175-5b0b8b80-c063-11ea-8ae8-81fa627bc6cc.jpg)

This does NOT work:
![trigger](https://user-images.githubusercontent.com/54757231/86830209-69f23e00-c063-11ea-9a8c-f9628ff04119.jpg)

### End of the build output on 'Run All Tests':
![build_on_trigger](https://user-images.githubusercontent.com/54757231/86831232-a4a8a600-c064-11ea-90c4-7b5f2bddc354.jpg)

### Test output on 'Run All Tests':
![test_on_trigger](https://user-images.githubusercontent.com/54757231/86831571-0bc65a80-c065-11ea-8d50-64a9a2cff4df.jpg)

## Did this work in previous version of GitExtensions

I'm not sure

## Environment

- GitExtensions: master branch HEAD revision
- Git: 2.27.0.windows.1
- Microsoft Windows NT: 10.0.18363.0
- DPI: 192dpi (200% scaling)
- .NET version: Framework 4.8.03752
- Visual Studio: Community 2019 Version 16.6.3

(Specified in NuGet dependencies)
- NUnit3TestAdapter: 3.16.1
- NUnit: 3.12.0
- NUnit.ConsoleRunner: 3.10

## Diagnostics

Selecting 'Tests' from the 'Show output from:' drop-down in the output view, this error message is displayed:
```
An exception occurred while invoking executor 'executor://nunit3testexecutor/': Incorrect format for TestCaseFilter Error:
Invalid Condition 'FullyQualifiedName=GitUITests.Editor.FindAndReplaceFormTests.FindNextAsync_should_iterate_over_files,,
[[AbstractSegment: Offset = 15, Length = 3], [AbstractSegment: Offset = 15, Length = 3]]'. Specify the correct format and try
again. Note that the incorrect format can lead to no test getting executed.
```

**Comment by mstv** [comment]
Thank you for the analysis, George.

**Comment by RussKie** [comment]
I'll have a look, but the following is something to be aware of.
VS makes two passes enumerating tests - one to populate the test explorer
and get the number of tests, and the 2nd pass to actually execute the tests.
For tests that have dynamic input parameters (i.e. those that change
between tests, e.g. `new object()` or `random.Next()`) inputs change
between the first and the second passes, and VS gets confused and skips
those tests.
AFAIR Resharper doesn't do this, and this is a poor decision on the VS side
imho, but we have to live with it.

**Comment by mstv** [comment]
Caused by `FindAndReplaceFormTests` using `IEnumerable<>` as argument.

BTW: Several subprojects are rebuilt always.

![RunAllTests](https://user-images.githubusercontent.com/36601201/87236670-3fe6a600-c3ec-11ea-85fc-32e25c843fe1.gif)

**Comment by gtisdelle** [comment]
Unfortunately, #8308 didn't fix this for me. Running all tests on 4c7e620 on the master branch is still giving me the exact same issue. The only thing that fixes this for me is to comment out all the `yield` statements in the `FindAndReplaceFormTests.LoopAround` and `FindAndReplaceFormTests.MultiFileSearch` properties' getters, effectively turning the iterators into a standard properties.

I don't fully understand why it is only these two properties causing the error, but I have a hunch that it may be that the tests are loaded twice in VS and that these two properties create `TestCaseData` objects with dynamic arguments.

**Comment by mstv** [comment]
Yes, it does not work for me, too, (with Microsoft Visual Studio Community 2019 Version 16.6.4).
I thought it had worked: IIRC I could not run these two tests at all. With the replacement for `IEnumerable`, it has become possible to run these tests as single selection and as selection of parent groups.

I am quite sure now that the MSVS test parser gets confused by the round brackets in the string representation of the `TextLocation` arguments. The testcases appeared at different levels.
Unfortunately this `struct` is part of the `ICSharpCode.TextEditor`.
So we will need a wrapper class with a different implementation of `ToString`, e.g. `=> $"[line = {X}, column = {Y}]"`.
