### ISSUE TITLE
Checkout and merge script fails to merge: Unable to write index

### ISSUE THREAD

**Issue by tasmin** [gitextensions/gitextensions#8304]
## Current behaviour

I have a script called with the script definition `merge-up-no-ff {sBranch}`
which calls the alias (formatted for readability):

```
[alias]
merge-up-noff = "!f()
{
	branch=`git rev-parse --abbrev-ref HEAD`;
	otherLocalBr=`echo $1 | cut -d'/' -f 2`; 

	echo \"Merge $1 (local $otherLocalBr) into $branch.\"; 
	echo; 

	if test \"$branch\" == \"$otherLocalBr\"; then
		echo \"We cannot merge-up remote version of local branch (same name).\"; 
	else 
		echo \" === Merge $branch into $1 (bring it up to $branch) ===\"; 
		echo ;
		echo \"  -- Checking out $1 forced --\"; 
		if test \"$otherLocalBr\" == \"$1\"; then
			git.exe checkout  --force \"$1\"; 
		else
			git.exe checkout  --force -B \"$otherLocalBr\" \"$1\"; 
		fi; 
		echo; 
		echo \"  -- Merging (no-ff) $branch into $1--\"; 
		git.exe merge --no-ff \"$branch\"; 
		echo; 
	fi;
};f"
```

## Expected behaviour

Check out the other branch, then merge the previous current branch into it with no-fast-forward.

## Steps to reproduce

Make a branch on top of another branch and commit a change.
Right-click the other branch and select the Merge-no-FF command defined above.

Instead of successful check out and then merge that I used to get before the update, I now get this result with an error message `error: Unable to write index.` at the merge step :

```
"C:\Program Files\Git\bin\git.exe" merge-up-noff _release_3.1.0
Merge _release_3.1.0 (local _release_3.1.0) into _issues/18405-Statistics_not_working_in_OpenWrite.

 === Merge _issues/18405-Statistics_not_working_in_OpenWrite into _release_3.1.0 (bring it up to _issues/18405-Statistics_not_working_in_OpenWrite) ===

  -- Checking out _release_3.1.0 forced --
Your branch is up to date with 'origin/_release_3.1.0'.
Switched to branch '_release_3.1.0'

  -- Merging (no-ff) _issues/18405-Statistics_not_working_in_OpenWrite into _release_3.1.0--
error: Unable to write index.
Automatic merge failed; fix conflicts and then commit the result.



Done
```

## Screenshots

![image](https://user-images.githubusercontent.com/1577260/86953825-d6c01380-c109-11ea-9896-25f0d10d8392.png)

## Did this work in previous version of GitExtensions
Yes.

Not sure, maybe 3.4.1.

## Environment

- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

## Diagnostics

[gitextensions.log](https://github.com/gitextensions/gitextensions/files/4892498/gitextensions.log)

**Comment by mstv** [comment]
from the log:
```
:06:42.7997009-07:00	34	12160	UI	0	git	ls-files -z --unmerged	D:\MyProject\
:06:42.8556992-07:00	248	11836	UI		git	merge-up-noff _release_3.1.0	D:\MyProject\
:06:44.1082683-07:00	65	17536	UI	0	git	--no-optional-locks -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files	D:\MyProject\
```
There is no concurrent git command run by GE.
(The exit code was not logged because run in the `EditboxBasedConsoleOutputControl`. I improved this in the PR, which will be merged tomorrow.)


I guess you have not activated the `FileIndexWatcher`. Else you could give it a try without.
Though I am afraid, another application is causing the conflict, e.g. an anti-virus "virus".
Does it work if you issue the command in a Git Bash while GE does not run?
![grafik](https://user-images.githubusercontent.com/36601201/86969064-7367cd00-c16d-11ea-9af3-67ef7ea104b7.png)

**Comment by tasmin** [comment]
Hi Michael,

Thank you for the explanation. Turning FileIndexWatcher on or off had no
effect.
It turns out there was a "virus" called Visual Studio that was causing it
to fail. If I quit VS then the GE script works. Microsoft must have broken
it in their update.

Thanks again for the tip!

Tasmin.

**Comment by RussKie** [comment]
VS sometimes can lock files waiting for your confirmations, if you change
them outside.
