### ISSUE TITLE
Move console style settings to "Appearance > Console style" panel

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#8306]
## Current behaviour

Now that console style apply to the "Console" tab **and** the Conemu popup, the settings are not well placed and difficult to find.

## Expected behaviour

Move "font size" and "console style" settings from "Browse repository windows" tab to "Appearance > Console style"

## Steps to reproduce

Open settings and don't find the console style settings ;)

## Screenshots

![image](https://user-images.githubusercontent.com/6248932/84403753-568bb880-ac06-11ea-83dc-1d403b4410e8.png)

## Did this work in previous version of GitExtensions

No. New request.

## Environment

- GitExtensions version: 3.4.2

See #8214 for the entire discussion.
Linked to #8215 
/cc @blitzmann

**Comment by blitzmann** [comment]
I'm looking into contributing this, will keep this issue updated :)

**Comment by blitzmann** [comment]
Got a PR out for it, now we wait 😀
