### ISSUE TITLE
Add a 'my fork' setting per clone and default all pushes to my fork

### ISSUE THREAD

**Issue by l3m** [gitextensions/gitextensions#8310]
# Feature description

When working in a project with multiple forks, and working on branches from the main repo but also branches from other forks, I always want to push to my own fork (no matter when the base branch came from). 

At the moment, this requires me to push paths for each fork or always manually select my own fork from the list in the push dialog. It also makes commit & push dangerous, and it happen regularly that someone in a larger team push to the wrong location.

I would like to have a setting to denote a 'my fork' or 'default push fork' per clone, and then make all pushes default to this fork. Ideally, this setting should be located in the remotes dialog.

**Comment by vbjay** [comment]
Look at the manage remotes dialog.

**Comment by l3m** [comment]
I did: 

![image](https://user-images.githubusercontent.com/230547/87247253-0432f700-c453-11ea-98d7-37c9e354eab9.png)

Maybe I don't understand, but the only way I see to achieve this is to go through all forks and many set the separate push url. 

My suggestion was intended more into the direction of setting a check-mark or start on one of the remotes to achieve the same.

**Comment by vbjay** [comment]
Nope. Look at the other tab.

**Comment by vbjay** [comment]
![image](https://user-images.githubusercontent.com/3629489/87248212-442fb500-c426-11ea-8cc0-d84e2924eca6.png)

![image](https://user-images.githubusercontent.com/3629489/87248221-5f022980-c426-11ea-80a9-faedbe616949.png)


Do you now see how it controls which remote/branch the branch will go to?

Let's check out contrib. 

![image](https://user-images.githubusercontent.com/3629489/87248304-c324ed80-c426-11ea-832a-4da3f69e6a60.png)
![image](https://user-images.githubusercontent.com/3629489/87248360-1139f100-c427-11ea-8fe4-7a7286d2217c.png)


Make sense?

**Comment by vbjay** [comment]
Try clicking that link in the commit dialog.

**Comment by l3m** [comment]
@vbjay  Thanks a lot for the explanations, but I feel I still didn't see a solution to my problem. Or maybe I just don't get it.

I feel that manually setting this for every branch on every repo doesn't scale. On all forks, we easily get 20 new branches per day. I believe that any such setting that is just per-branch does not solve the problem. A simple setting that sets a default repo independent of which branch from where is currently active would greatly improve user experience, at least for me.

**Comment by vbjay** [comment]
Default your git remote to be origin. That is the defacto standard. Git defaults it to this if not set. 

https://git-scm.com/docs/git-push

**Comment by l3m** [comment]
@vbjay Thanks a lot, that does solve my problem and seems to solve my issue. Thanks for your patience!

**Comment by vbjay** [comment]
FYI. https://stackoverflow.com/questions/9257533/what-is-the-difference-between-origin-and-upstream-on-github

**Comment by RussKie** [comment]
There is a little more to this.

When you create a new branch we ask you whether you wan to creating tracking references.

![image](https://user-images.githubusercontent.com/4403806/87899964-3cab8400-ca96-11ea-9cec-c58ee65d62bd.png)
