### ISSUE TITLE
Interactive merge asks for confirmation after execution

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8312]
## Current behaviour

Interactive merge is executed before it asks for confirmation (regardless of whether the confirmation is turned off or on)

## Expected behaviour

Ask for confirmation before execution

## Did this work in previous version of GitExtensions

Yes, broken by #8292

## Environment

- Git Extensions 33.33.33
- Build 316f8d49653b30aa5371d877434a80d7b9914ca9
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
I have found the missing early exit from 21f982b53c64b5e83bc2d52764a43e4138dab628.
Though I do not get why it has not striked out before #8292.

**Comment by gerhardol** [comment]
I do not see either why it was not seen before, but the PRis consistent with the other dialogs
