### ISSUE TITLE
[NBug] Die Sequenz enthält kein übereinstimmendes Element.

### ISSUE THREAD

**Issue by JakobLettenbichler** [gitextensions/gitextensions#8316]
## Current behaviour

git extensions crashes when trying to create a list of changes in submodules (staged changes contain a new submodule and another that shall be removed).

## Expected behaviour

create a list of changes in submodules and do not crash

## Steps to reproduce

Win10,
create a repo with several subrepos/submodules. Then try to add another subrepo and remove a different one.
Then stage them in the commit dialog and try to create a list of changes in submodules (Commit message).

## Error Details
```
System.InvalidOperationException: Die Sequenz enthält kein übereinstimmendes Element.
   bei System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   bei GitUI.CommandsDialogs.FormCommit.generateListOfChangesInSubmodulesChangesToolStripMenuItem_Click(Object sender, EventArgs e)
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
create a repo with several subrepos/submodules. Then try to add another subrepo and remove a different one.
Then stage them in the commit dialog and try to create a list of changes in submodules (Commit message).

## Environment
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4018.0
- DPI 96dpi (no scaling)

**Comment by JakobLettenbichler** [comment]
I have no Idea what must be added here to not close the report automatically. I have added the missing sections as can be seen in the report.

**Comment by gerhardol** [comment]
The summary is created also for submodules not existing on the filesysten.

Created #8318 for this

> I have no Idea what must be added here to not close the report automatically. I have added the missing sections as can be seen in the report.

The bot is a little aggressive, if the issue was not submitted correctly. It is less job for maintainers to reopen correct than to close incomplete issues though.

**Comment by JakobLettenbichler** [comment]
Hiho,

thanks for the clarifications (and for reopening the ticket)! Loving git extensions (but I am still sad, that it's not working in Linux anymore, I found no proper replacement yet).

@ Issue: my workaround was to remove the added and removed submodules before creating the summary, that worked flawlessly, so since a workaround exists, that ticket can be treated as low priority anyways.
