### ISSUE TITLE
[NBug] Could not load file or assembly 'System.Reactive.PlatformSe...

### ISSUE THREAD

**Issue by ThomasFike** [gitextensions/gitextensions#8325]
## Current behaviour

Error on start up or trying to open a repo

## Expected behaviour

Should just work without error message

## Steps to reproduce

Don't know how to repoduce on another system but it will happen everytime I start the application on my system.

## Error Details
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Reactive.PlatformServices, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Reactive.PlatformServices, Version=3.0.3000.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263'
   at BackgroundFetch.BackgroundFetchPlugin.RecreateObservable()
   at BackgroundFetch.BackgroundFetchPlugin.Register(IGitUICommands gitUiCommands)
   at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
   at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
   at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
   at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
   at GitUI.CommandsDialogs.FormBrowse.<<-ctor>b__43_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

## Additional information
Just launched git extentions and this is what I get. If I x out I can continue using it fine.

## Environment
- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by ThomasFike** [comment]
Updated with all the info!

**Comment by mstv** [comment]
Have you unpacked the portable build into the folder of a previous version?

**Comment by ThomasFike** [comment]
I have only ever used the installer. I have never run it as a portable build. I have tried uninstalling and then reinstalling and that did not resolve the issue.

**Comment by pmiossec** [comment]
Which version of windows and of .Net framework ?

**Comment by mstv** [comment]
> Which version of windows and of .Net framework ?

from the issue description: Microsoft Windows NT 10.0.17763.0, .NET Framework 4.8.4150.0

**Comment by gerhardol** [comment]
System.Reactive.PlatformServices is not something GE has a direct dependency of, but System.Reactive uses it.

Please check the file version for Plugin/BackgroundFetch.dll should be the same as the .exe
The plugin uses the same version as the exe (4.2.0 in GE 3.4), so dependency seem to point to another file.

**Comment by klorinczi** [comment]
FYI: 
I found, that when I deleted files in Plugins directory and copied the files from portable zip file again, the problem was solved, the error went away.

The problem was, that the Plugins directory contained dll files with old naming scheme used in Git Extensions v3.1.1.

I hope this helps.
