### ISSUE TITLE
Branch history disappears after pull-rebase

### ISSUE THREAD

**Issue by BartWeyder** [gitextensions/gitextensions#8326]
After recent update I get broken branch history with label `keep-around/...`:
![image](https://user-images.githubusercontent.com/19413080/87513811-f9aa7480-c681-11ea-8f37-6684aa8d8f6d.png)

I am sorry if this is expected behavior, but I didn't have it before, it appeared recently and neither googling nor official documentation did not help me.

**Comment by pmiossec** [comment]
Are you sure you didn't enabled the 'View reflog references" in the' View'
menu?

**Comment by RussKie** [comment]
This is something in your repo, the app isn't doing this. @pmiossec suggestion looks like a plausible reason.

**Comment by BartWeyder** [comment]
@pmiossec 
> Are you sure you didn't enabled the 'View reflog references" in the' View' menu?

Nope, it's disabled
![image](https://user-images.githubusercontent.com/19413080/87527893-7135cf00-c695-11ea-854d-9a7854955690.png)

**Comment by RussKie** [comment]
Closing since there is no repro available.
