### ISSUE TITLE
Push commit does clear commit message when confirm box appears

### ISSUE THREAD

**Issue by 1Jesper1** [gitextensions/gitextensions#8327]
## Current behaviour

Click on push clears the commit message input, while push confirmation box appears.

## Expected behaviour

Do not clear the commit message input.

## Steps to reproduce

Go to commit and type a commit message and click on commit and push.

## Environment

- GitExtensions version: 3.4.2
- GIT version: 2.23.0
- OS version:  Windows 10

**Comment by racecrew** [comment]
What is going to happen with this ticket? Will it be closed? Since this issue is not a bug...

**Comment by mstv** [comment]
> What is going to happen with this ticket? Will it be closed? Since this issue is not a bug...

I agree, it is no bug. Though we could improve the UX with little effort: https://github.com/gitextensions/gitextensions/pull/8513#discussion_r502644976

**Comment by racecrew** [comment]
> > What is going to happen with this ticket? Will it be closed? Since this issue is not a bug...
> 
> I agree, it is no bug. Though we could improve the UX with little effort: [#8513 (comment)](https://github.com/gitextensions/gitextensions/pull/8513#discussion_r502644976)

IMHO, there is nothing to improve... The message is cleared when the push is started -> seems to be OK for me

@mstv what do you mean exactly by improving UX?

**Comment by mstv** [comment]
If I understand @1Jesper1 correctly, he still wants to see what is being pushed, in the background during the push.
I don't have a strong preference pro or contra. The PR was just almost finished solving this request in a safe way. It would "improve the UX" a little at least for @1Jesper1.

**Comment by racecrew** [comment]
> If I understand @1Jesper1 correctly, he still wants to see what is being pushed, in the background during the push.
> I don't have a strong preference pro or contra. The PR was just almost finished solving this request in a safe way. It would "improve the UX" a little at least for @1Jesper1.

@mstv Sorry, somehow I have not seen your comment https://github.com/gitextensions/gitextensions/pull/8513#discussion_r502644976 :-(

So, I have restored the branch, pushed the changes... but how or who can re-open the closed PR?

**Comment by RussKie** [comment]
> So, I have restored the branch, pushed the changes... but how or who can re-open the closed PR?

You can re-open your own PRs and issues.
But you need to re-open before you push new changes, GitHub doesn't like it the other way (at least in my experience).
