### ISSUE TITLE
When checking-out a branch using an external tool the active branch is not changed

### ISSUE THREAD

**Issue by mrc77** [gitextensions/gitextensions#8345]
Hi, let's suppose to work on a repository with two branches:
- master
- develop

Now "master" is the current checked-out branch.

Now, using Git Bash or Visual Studio, let's switch the active branch (git checkout "develop").

**Expected behavior**
Git Extensions should highlight the "develop" branch in the left tree and in the toolbar.

**Current behavior**
Git Extensions displays "master" as the active branch until you manually hit "refresh".

PS: Enabling option _General > Use FileSystemWatcher to check if index is changed_ doesn't fix this issue.

**Comment by RussKie** [comment]
The app is a UI over git cli, so a refresh is required for the app to ask git for the updated data. Unfortunately I can't see it implemented without a major refactor/rework of the current implementation. 

Also it is worth noting that running multiple git clients in the same repo may lead to all sorts of contentions, and issues.

**Comment by gerhardol** [comment]
GE could of course regularly refresh the UI, but that would be extremely annoying.
FileSystemWatcher should refresh the status icon at external changes, but it could be that some changes are missed. But the GUI should otherwise not be updated.

**Comment by mrc77** [comment]
Ok, thank you for the explanations.
