### ISSUE TITLE
Unable to "Format patch" of first commit

### ISSUE THREAD

**Issue by NOYB** [gitextensions/gitextensions#8348]
## Current behaviour

Patch error dialog pops up with the message "Unable to to create patch file(s)".

## Expected behaviour

Patch file created without error.

## Steps to reproduce

1) Select "Format patch..." from the "Commands" drop down menu.
2) Select the first commit.  The one at bottom of the list (the initial commit).
3) Click the "Create patch(es)" button

## Did this work in previous version of GitExtensions

Doubt it previously worked.  But I don't actually know.

## Environment

- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.7.3416.0
- DPI 96dpi (no scaling)

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by RussKie** [comment]
Can you please provide a repro?

**Comment by NOYB** [comment]
Just create a new repo and make a commit.
Then try to do a format patch for that commit.

**Comment by gerhardol** [comment]
Can be seen with the first commit in a repo as well with first commit for orphaned branches.
Such a patch must use --root to reference the non existing commit (that internally have a sha in Git...)
https://git-scm.com/docs/git-format-patch#Documentation/git-format-patch.txt---root

Special handling like this has been added for diff files.
The A patch is from a commit to another, in this case it would be similar to a zip of the contents.
The value of such a change is very low.
