### ISSUE TITLE
Add branches names to `Resolve merge conflicts` window

### ISSUE THREAD

**Issue by itsho** [gitextensions/gitextensions#8349]
## Feature description

at the bottom of Resolve merge conflicts window, we can see three rows:
Local
Base
Remote

**When available** - I really want to see the branch name of each one since this terminology (local/theirs/ours/remote) is extremely confusing during rebase and I need to be VERY careful every time I'm using this window.

## Environment

- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3620.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Same as #6582?
Can you merge the requests?

Reasonable, requires some refactoring though.

**Comment by itsho** [comment]
Exactly! 👍 

Now I see that my request is already mentioned in one of the comments:
https://github.com/gitextensions/gitextensions/issues/6582#issuecomment-505716174
