### ISSUE TITLE
Add ability to change color for remote and local branches for the color blind

### ISSUE THREAD

**Issue by itsho** [gitextensions/gitextensions#8350]
## Feature description

Currently, local branch is red, and remote branch is green.
A person with Red-Green color blindness does not see any difference!

Please consider adding the ability to manually select colors for remote and local branches.

I've also tested to see if dark mode does any difference, but it's not :-(

## Environment

- Git Extensions 3.4.2.9737
- Build 082cfd97d09c47346638b1873f5c8cf6ed139382
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.7.3620.0
- DPI 96dpi (no scaling)

**Comment by itsho** [comment]
I agree that "color blind" theme is an better approach, 
but we might need more than one theme since there are multiple types of color blindness:
https://en.wikipedia.org/wiki/Color_blindness#Classification

**Comment by RussKie** [comment]
I'm not quite sure what we can do for totally colour blind people, but for others switching red to blue(-ish) colour should work, I think.

**Comment by neil5280** [comment]
As a color-blind programmer, I'm finding this mildly infuriating.  I had my local branches set to blue, but when I updated to 3.4.3.999 the option to pick my branch label colors was gone.  As you can see in the settings documentation for 3.4, this feature use to already be fully-baked under the Color Options, but now the settings are gone and replaced by the woefully insufficient theme selector.

https://git-extensions-documentation.readthedocs.io/en/release-3.4/settings.html
Search for "color branch" and "color remote branch" in the settings page to see what I'm referring to.

**Comment by vbjay** [comment]
I frankly think we should provide the feature of full theme editing. Pop an
owned form and let the user pick colors and it affect the current ui. If
the user cancels, reload the backed up theme. This would allow us to play
and see if we like it. The other thing is we could do something like
https://studiostyl.es/ but for GE. Maybe a menu that generates a nuget
package that lets the user specify a name and such and then uploads the
nuget package to the ge styles site. We could eventually provide a ui that
lets the user browse the nuget feed with sample images of the ui. Then a
simple nuget package download and apply to current ui.

Another thing. Could add a start ui with x theme command line argument or
maybe a settings file. So maybe we have work and personal settings. We
could set up different themes to help us know which settings are
being used.

**Comment by neil5280** [comment]
@vbjay That all sounds amazing.

Is there a way GitExtensions can revert back to what existed in 3.4? It would immediately be more usable for color-blind users than what has been developed in its place.  I don't know how much discussion was given to removing the options and replacing them with themes, but it provides less utility to ~8% of men and ~.5% of women than what existed previously.

It seems the themes idea needs a longer more thought out approach, incorporating your ideas, before it should be part of the main branch.

**Comment by NikolayXHD** [comment]
> Pop an owned form and let the user pick colors and it affect the current ui

Unfortunately this is unfeasible. 
The reason is, many .NET WinForms controls cache brushes and colors, which I know for sure, and I also strongly suspect the same is true for Win32 unmanaged code.

As a result any changes to colors you do after the application is initialized and starts displaying forms / controls will not be applied consistently.

This is the reason why I first had implemented the theme editor and later removed it.

Other than applying the changed colors on-the-fly, it's ok, theme editor form can be done.

**Comment by vbjay** [comment]
Ok. In that case. Pop a theme edit process backing up original theme. When
process is done, restart ge. Ask user to evaluate theme and if they like it
save to current theme. If not revert to backup theme.

**Comment by vbjay** [comment]
To add. We could work with test accessor to pop any ui with sample ui ad
another process.

**Comment by gerhardol** [comment]
> https://git-extensions-documentation.readthedocs.io/en/release-3.4/settings.html
Search for "color branch" and "color remote branch" in the settings page to see what I'm referring to.

The documentation is not updated as it should. Volunteers wanted.

GE 3.4 adds a lot of customization with the theming. The GUI would be overwhelming with all the controls.
However, the customization in itself is not changed what I know.
In fact, someone may provide a theme suitable for color blind?

Copy a .css from Themes folder to %AppData%\GitExtensions\GitExtensions\Themes with an apropriate name
Edit the file in a text editor. For instance Visual Studio Code will show the colors too.
The fields are not documented - volunteers wanted for that too.
![image](https://user-images.githubusercontent.com/6248932/90815609-3a557780-e32b-11ea-82d4-dabe97587b78.png)

**Comment by neil5280** [comment]
It would be great to have themes centered around each type of color blindness in each of the the default themes, but then you're talking about having at least 12 themes.  Normal, Deuteranopia, Protanopia , and Tritanopia versions of the Default, Silver, and Dark themes.

@gerhardhol I don't think the GUI was overwhelming when it included the original color modification system and themes.  There's a screenshot in the original feature request from before the original color mod system was removed:
![image](https://user-images.githubusercontent.com/1786825/90830847-4b849100-e2f7-11ea-8b59-ee7a4a5bb403.png)  Is this what you were thinking of?

It seems like that system, instead of being removed, could have been used to update the .css files used by the themes, had the user wanted to make adjustments.  The best of both worlds.

Is there an inability to get back to how it is pictured above?

**Comment by gerhardol** [comment]
> It would be great to have themes centered around each type of color blindness in each of the the default themes, but then you're talking about having at least 12 themes. Normal, Deuteranopia, Protanopia , and Tritanopia versions of the Default, Silver, and Dark themes.

I would expect that there would be one base theme that can be customized further. If someone wants to, we can put up more special themes that can be downloaded manually
(and variants of both Dark and DarkSilver would be a waste, I doubt that any Dark variant is suited for this aspect).

> @gerhardhol I don't think the GUI was overwhelming when it included the original color modification system and themes. 
> Is there an inability to get back to how it is pictured above?

With the themes, there are a lot more aspects that can be changed, so it would be overwhelming
Also, there were some issues with having settings and themes, just having the themes was simpler (I did not implement this myself and was a bystander to the discussion)

It is not so hard to edit a file with the desired colors

**Comment by neil5280** [comment]
I see what you mean.  There are 42 customization colors in the themes, whereas the old UI only provided access to 11.  If you wanted to provide complete customization, that would be overwhelming.  I was only advocating for bringing back the 11, but I can see how that might feel half-baked.

I'm currently using a customized DarkSilver theme for my color blindness.  I'm not sure why you think the dark themes would be ill-suited to have color-blind variants.  I've attached my file, in case it can be useful to anyone.  Besides popping my head up once in 12 years to advocate for this color-blindness issue, I'm not really active on github.  I wouldn't know where to begin to check it in.

Thanks to everyone engaging in the conversation.  It's nice to have accessibility issues heard and taken seriously.
