### ISSUE TITLE
Performance issues with gitextensions

### ISSUE THREAD

**Issue by gintuoklis** [gitextensions/gitextensions#8376]
## Current behaviour
Latest gitExtensions has slugish performance. Any git commands takes minum 1.6 seconds to complete. See screenshot of git command log

![image](https://user-images.githubusercontent.com/16342128/89287960-23d5cd80-d655-11ea-9723-7818bb9c3e51.png)

Initially i thought it's related to the big repository. I switched to tiny (single branch with 10 commits max) repo, and experience the same performance.
I completely uninstalled git, and gitextensions and installed from scratch. But, still the same issue.

Any advice?
## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4200.0
- DPI 120dpi (125% scaling)

**Comment by pmiossec** [comment]
It's more a performance problem with git as you can see it with Gitextensions logs.

Did you installed the last version of git in the same time you updated Gitextensions? If yes, please try to reinstall this version to test it.

Or you changed something else in your system...

But this slowness with git is not normal.

Someone opened a similar issue but I can't recall what was the problem. We have to find the issue...

**Comment by pmiossec** [comment]
See #8261 ...

**Comment by gintuoklis** [comment]
thanks for the promt reply @pmiossec 
Coming back to your questions:

- yes i did reinstall of git together with gitExtensions
- don't remember exact time when did it start happening, so no clue which changed might have led to it 

in the meantime will try old good restart of the system like #8261 suggests.

**Comment by RussKie** [comment]
Check your video drivers are up to date. FWIW there had been reports over
the years outdated drivers cause performance degradation.

**Comment by gintuoklis** [comment]
Got figure it out. 
Asked our infrastructure team to add git.exe to the exclusions list of our antivirus system. It did the magic
