### ISSUE TITLE
Cmd.exe was opened when click Git bash button.

### ISSUE THREAD

**Issue by Griiid** [gitextensions/gitextensions#8381]
## Current behaviour

I use Git Extensions in windows 10.  When I click `Git bash` button, it opens `cmd.exe`, not `git-bash.exe`
This feature worked correctly before, I'm not sure whether it is a bug of Git Extensions, or something went wrong in my Windows.

I saw issue #3057 has the same problem.
In pull request https://github.com/gitextensions/gitextensions/pull/3277 , it lists some path the Git Extensions will look for `git-bash.exe`, and in my environment, `git-bash.exe` exist in `C:\Program Files\Git`, so I don't know why `git-bash.exe` doesn't open when click `Git bash` button.

## Expected behaviour

It should open `git-bash.exe` when I cleck `Git bash` button.

## Steps to reproduce

Click `Git bash` button.

## Screenshots

Herer's the `cmd.exe` opened after click `Git bash` button:
![圖片](https://user-images.githubusercontent.com/17796098/89390276-0f6b0100-d739-11ea-9623-da537c0b15aa.png)

## Did this work in previous version of GitExtensions

I'm not sure.  I don't want to install old version since it might changed some settings.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
What shell is configured?

![image](https://user-images.githubusercontent.com/6248932/89391808-f9dde300-d708-11ea-8403-9d75c3fe56cf.png)

**Comment by Griiid** [comment]
Here's my setting:

![圖片](https://user-images.githubusercontent.com/17796098/89855112-3063a400-dbc8-11ea-8a7e-1bb6d3a1769b.png)

**Comment by Xqzmeplz** [comment]
I've encountered the same problem. The PathUtil.TryFindShellPath queries the EnvironmentAbstraction for the SpecialFolder.ProgramFiles which returns the following values:
x86 - 32-bit v3.4.3
ProgramFiles: C:\Program Files (x86)
ProgramFilesX86: C:\Program Files (x86)

x64 - 64-bit v3.3.0
ProgramFiles: C:\Program Files
ProgramFilesX86: C:\Program Files (x86)

The older Version of GitExtensions is compiled against x64 instead of x86. (see <Prefer32bit>true<Prefer32bit> inside GitExtensions.csproj).
In my opinion the architecture target of GitExtensions should not influence the git installation path. GitExtensions should check "C:\Program Files" and "C:\Program Files (x86)".

**Comment by 1arne** [comment]
Looking at the source code, if git-bash.exe is not found through SpecialFolder.ProgramFiles, then GitExtensions also searches for it in "Path for Linux tools" directory (typically C:\Program Files\Git\bin in 64-bit Git for Windows installation) and also as a fallback tries to locate it in environment paths.
Temporary workaround: add C:\Program Files\Git to your environment path.

**Comment by vbjay** [comment]
Look at settings. The setting is set to run cmd.  Change it.

**Comment by Griiid** [comment]
> 
> Look at settings. The setting is set to run cmd. Change it.

Sorry, I didn't see where did I set cmd in settings. Could you please tell me how to change it? Thanks.

**Comment by Griiid** [comment]
> 
> 
> Looking at the source code, if git-bash.exe is not found through SpecialFolder.ProgramFiles, then GitExtensions also searches for it in "Path for Linux tools" directory (typically C:\Program Files\Git\bin in 64-bit Git for Windows installation) and also as a fallback tries to locate it in environment paths.
> Temporary workaround: add C:\Program Files\Git to your environment path.

This temporary workaround helps!

Maybe we should add this path in the source code?

**Comment by 1arne** [comment]
I can confirm that I have the following settings set for "Browse repository window", but CTRL-G keyboard shortcut and Git bash button on the toolbar still open the cmd.exe window without the workaround. For me it looks like this setting is applying only to console emulator (which works well), but the problem with standalone git bash window when using 64-bit Git is the one described by Xqzmeplz above.

![image](https://user-images.githubusercontent.com/25436036/95993690-164c7900-0e38-11eb-9c93-f95fdf947d1e.png)

**Comment by gerhardol** [comment]
Is the path to sh set?

![image](https://user-images.githubusercontent.com/6248932/96034471-def2c200-0e61-11eb-82f7-2cbc3406dce8.png)

**Comment by 1arne** [comment]
Path to sh set as follows:
![image](https://user-images.githubusercontent.com/25436036/96123448-7d7f3180-0efb-11eb-9438-025e7794f1e3.png)

**Comment by nicewook** [comment]
I've changed Path and I think it works 

`C:\Program Files\Git\`

![image](https://user-images.githubusercontent.com/6977358/97139655-539cf900-179e-11eb-8a1d-24dbfba1042c.png)

**Comment by Griiid** [comment]
Hi @RussKie,

May I know why did you close this issue?
I don't think this issues was resolved.

Currently we know these 2 methods works:
1. Temporary workaround: add `C:\Program Files\Git` to your environment path.
2. Set `C:\Program Files\Git\` in Path to `linux tools (sh).`

The 1st. method is not good since it need users to set path in environment path.
The 2nd. method is incorrect since my sh.exe is not in `C:\Program Files\Git`, it's in `C:\Program Files\Git\bin`

If you think the 2nd. method is correct, then we should modify the description `linux tools (sh). Leave empty when it is in the path`

**Comment by vbjay** [comment]
Option 2 is the correct way.

**Comment by vbjay** [comment]
Because your sh tools could be different we allow you to set the path. If environment doesn't provide the info then you have to tell GE where the tools are.

**Comment by Griiid** [comment]
But my `sh.exe` is in `C:\Program Files\Git\bin`, and my `git-bash.exe` is in `C:\Program Files\Git`

I think the `git bash` button should open `git-bash.exe`, not `sh.exe`, if I am wrong please tell me
 
> Because your sh tools could be different we allow you to set the path. If environment doesn't provide the info then you have to tell GE where the tools are.

--> You mean both sh.exe and git-bash.exe are sh tools?

**Comment by vbjay** [comment]
The top path is where git exists the bottom one is where sh tools are.

**Comment by divya-gh** [comment]
was this issue resolved? I'm getting the same issue - Cmd.exe was opened when click Git bash button.
how was this fixed?

**Comment by vbjay** [comment]
We have a path setting. Change it to point to where git.exe is.

**Comment by divya-gh** [comment]
Do I need to have git extension installed for that? How do I set up the path?

**Comment by vbjay** [comment]
Open ge settings look at the settings under git\path tree node.

**Comment by nyanpasu64** [comment]
I have `C:\Program Files\Git\git-bash.exe`. However, if I set my sh directory to "C:\Program Files\Git\", then I don't have a Git Bash button, only a cmd button which opens cmd. And if I set my sh directory to "C:\Program Files\Git[\usr]\bin", then I get a Git Bash button which runs `C:\Program Files\Git[\usr]\bin\bash.exe` (which opens a conhost window), rather than running git-bash.exe resulting in mintty. This persists even if I copy git-bash.exe to `C:\Program Files\Git[\usr]\bin\`.

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4390.0
- DPI 120dpi (125% scaling)

**Comment by mstv** [comment]
`bash` looks for `bash.exe` and `sh.exe` but not for `git-bash.exe`.

![image](https://user-images.githubusercontent.com/36601201/126556953-4292b3ab-babf-476c-88ea-5c746c51bbc4.png)

As a quick solution, you could create a toolbar button by means of a User Script like:

![image](https://user-images.githubusercontent.com/36601201/126557266-45171103-0ad3-4579-8eba-976ddecb2782.png)

Else raise a feature request, please. Pull requests are welcome, too - refer to class `BashShell`. 😉
