### ISSUE TITLE
Add a script variable for the working directory without the trailing separator

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#8388]
## Feature description
There is currently a `{WorkingDir}` script variable which expands to the name of the directory of the current repository. However, this name contains a trailing directory separator (i.e. a `\` on Windows). There are legitimate reasons to be able to get the name _without_ the separator.
Specifically, I have a workaround for #1393 (a custom script suggested [here](https://github.com/gitextensions/gitextensions/issues/1393#issuecomment-614266504)). I am launching the `git-bash.exe` with an argument `--cd="{WorkingDir}"`. However, that actually doesn't work (for reasons detailed [here](https://github.com/git-for-windows/git/issues/1444#issuecomment-498819096)).
Therefore, a new variable like `{WorkingDirNoTrailingSeparator}` could be added.

## Environment

- Git Extensions 33.33.33
- Build 4992b04e6e70ed491cf333365668be1fb4d51125
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4200.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
It is a long standing Windows interpreter "feature". Just add a space after
{ and before ".

**Comment by RussKie** [comment]
Sorry, }

--cd="{WorkingDir} "

**Comment by crypto-rsa** [comment]
It works, thank you!
However, it's very much a hack rather than a proper solution. Would you accept a PR with the solution I suggested above?

**Comment by RussKie** [comment]
Thank you for your reply.

At this stage I'm _personally_ inclined to say no for the following reasons:
- this appears to be the first and only report about this issue, so
applying a workaround seems justified;
- we have no plans servicing 3.4 branch, and the next release has no due
date;
- the app already has too many configs and options, and the added weight is
noticeable.
- the current behavior is consistent with flagship products like Visual
Studio. VS exhibit all the same issues - its path variables end with a
trailing slashes.

We _could_ consider dropping the trailing slash from path variables, but
this may be a breaking change. Though I don't know if a lot of our users
know or use scripts at all.

**Comment by crypto-rsa** [comment]
OK, fair point(s). Happy to close the issue at this point.
One thing to clarify, though: I didn't mean to add any new _setting_ (or UI for that matter), only a new script _variable_ which could be used whenever a script expects the path without the trailing separator.

**Comment by RussKie** [comment]
Thank you for the suggestion, but I'm closing it for the reasons outlined above.
We may revisit this in the future.
