### ISSUE TITLE
Keyboard: Enter doesn’t work in “Remote Repositories” dialog

### ISSUE THREAD

**Issue by Timwi** [gitextensions/gitextensions#8389]
## Current behaviour

In “Remote Repositories”, Enter does nothing.

## Expected behaviour

Enter should activate the “Save Changes” button.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
> Enter should activate the “Save Changes” button.

In which workflow though? "Save changes" button is specific to editing, and not global to the form.
