### ISSUE TITLE
Keyboard: Commit message box in Commit window is a tab trap

### ISSUE THREAD

**Issue by Timwi** [gitextensions/gitextensions#8391]
## Steps to reproduce

* Open the Commit window (Ctrl+Space).
* Use Tab to navigate between elements in the window.

## Current behaviour

Once you reach the commit message textbox, you can no longer leave it by pressing Tab. Instead, pressing Tab inserts a tab character.

(Ctrl+Tab provides a workaround.)

## Expected behaviour

Expected behaviour is to navigate to the next element. I don’t think inserting a tab character in a commit message is at all a common requirement.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
> I don’t think inserting a tab character in a commit message is at all a
common requirement.

It's a multiline textbox, so TAB support is not that uncommon requirement.
