### ISSUE TITLE
[NBug] Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ericshawlinux** [gitextensions/gitextensions#8398]
## Current behaviour

The program crashes when loading a project with submodules in a subdirectory.

## Expected behaviour
Program should be robust, like git on command line! No crashing or bugs!

## Steps to reproduce

It always happens when I open a particular project. I really don't know too much about the details, but i'd be open to investigating it with someone together. We could look at the project we have probably but i'd need to get permission from my supervisor.

## Error Details
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.CreateSubmoduleNodes(IEnumerable`1 submodules, GitModule threadModule, List`1& nodes)
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.FillSubmoduleTree(SubmoduleInfoResult result)
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.<LoadNodesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.Tree.<ReloadNodesAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.BranchTreePanel.RepoObjectsTree.SubmoduleTree.<>c__DisplayClass4_0.<<OnStatusUpdated>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Last time I tried to debug this.. I think the submodule is not at the super path or something like that. I was able to apply a patch to a previous version of git extensions that fixed the issue. But in a more recent version the code is entirely different, and I got lost.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.22.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4200.0
- DPI 96dpi (no scaling)

**Comment by ericshawlinux** [comment]
> Thank you for the bug report 👍
> 
> Sadly, it appears some important information is still missing, which you may have overlooked while submitting the bug.
> Without this information we may not be able to assist you in resolving the issue.
> 
> Please review your submission, fill the missing information in and post a new comment to ping us back to re-open the issue.
> Thanks again

@archivarius-bot filled in the requested information

**Comment by ericshawlinux** [comment]
@pmiossec Hi, I had to fill in the additional details by editing the issue. Hope this helps. Let me know.

Thanks.

**Comment by ericshawlinux** [comment]
> Thank you for the bug report 👍
> 
> Sadly, it appears some important information is still missing, which you may have overlooked while submitting the bug.
> Without this information we may not be able to assist you in resolving the issue.
> 
> Please review your submission, fill the missing information in and post a new comment to ping us back to re-open the issue.
> Thanks again

@archivarius-bot, I filled in the requested information

**Comment by pmiossec** [comment]
This a good first step for a bug report :+1:
I'm really not an expert on submodule but rest assured that the one that will take it will ask for more if needed 😅

But if you could provide the patch of the fix you did in the past or explain a little more what your fix was doing, it could help the one that will work on it.

Anyway, thanks a lot for the good report!

**Comment by ericshawlinux** [comment]
Here is the patch. It seems I did this after commit bc07663c3c893f1d896520e0bdcfbe35cfe4b729 in GitExtensions version 3.2.0.

[git-extensions-fix-submodule-list-crash-after-commit-bc07663c3c893f1d896520e0bdcfbe35cfe4b729.patch.txt](https://github.com/gitextensions/gitextensions/files/5069997/git-extensions-fix-submodule-list-crash-after-commit-bc07663c3c893f1d896520e0bdcfbe35cfe4b729.patch.txt)

**Comment by gerhardol** [comment]
What is the contents of .gitmodules (recursively)? (you can obfuscate the contents)
On what level do you see the problem, in top project or any submodule?

The patch still applies, line 291 in GitUI\BranchTreePanel\RepoObjectsTree.Nodes.Submodules.cs.

**Comment by ericshawlinux** [comment]
I only found one .gitmodules file in the project.

```text
[submodule "NTSTRT"]
	path = NTSTRT
	url = H:/Dev/NTSTRT.git
	branch = master
[submodule "C:/Dev/SGCONSLS/EPPlus"]
	path = C:/Dev/SGCONSLS/EPPlus
	url = H:/Dev/EPPlus.git
	branch = master
[submodule "C:/Dev/SGCONSLS/NTSTRT"]
	path = C:/Dev/SGCONSLS/NTSTRT
	url = H:/Dev/NTSTRT.git
	branch = master
[submodule "EPPlus"]
	path = EPPlus
	url = H:/Dev/EPPlus.git
	branch = master
```

My project files are actually in `C:\Users\Eric\Projects\TheProject` do you think that could be affecting it?

**Comment by gerhardol** [comment]
This repo will fail in many other situations to, it cannot be pushed to most Git servers for instance as they run unix. Windows computers could fail with this hardcoded path too.
The url to the submodule could work, but then every user on a Windows PC must out the repo there and clone it manually.
The subrepos are added twice too.
For this to be reasonable, the superproject must be put in c:/dev
So this is not a usable setup.

GE assumes that submodules are stored relative the superrepo, not absolute paths in 'path'. This cannot be presented in the side panel either.
While this could be handled better, I do not believe that it is worth spending time on it, almost every other change will give a better return on investment.

**Comment by ericshawlinux** [comment]
Ok I’ll try fixing the configuration...

**Comment by ericshawlinux** [comment]
That worked! Thanks. Had no idea the modules file was wrong, I never wrote one.
