### ISSUE TITLE
Allow non-recursive sub-module initialization and updates

### ISSUE THREAD

**Issue by LightCC** [gitextensions/gitextensions#8407]
## Feature description

Git Extensions forces the use of the `--recursive` option on ALL submodule operations. This assumes there are no interdependencies between multiple repos which are required for unit testing or other purposes.

This feature request is to enhance Git Extensions to allow for some way to choose whether submodules should be cloned and updated recursively or not. See below for the possible solutions.

**Note:** There is a closed issue about this (#7995) were this enhancement was rejected as an unusual case. I'm bringing it up again because while it may be an edge case, I do not believe it is as infrequent a situation as others may think. In addition, the consequences are dramatic for those stuck by this design, and a very small change can at least provide a solution that resolves the usability issue. I'm pulling my hair out trying to train a large team, where many only use git occasionally, on all the rules around submodules because of this behavior from Git Extensions to always initialized/update recursively. We use GE to make things easier for part-time git users, but this makes it harder.

## Justification

Git has `--recursive` as a submodule flag for a reason. There is no assumption in Git that submodules should always be initialized/updated to an infinite recursion depth.

Why is recursing a problem? In any large ecosystem of repos, there are cases where there may be interdependencies. For example, Repo 1 requires Repo 2 and 3 as submodules to run its unit-tests, and Repo 3 also requires Repo 1 to run it's unit tests. If submodules are cloned or updated with `--init` and `--recursive`, then an infinite recursion loop is created where **Git Extensions will continue cloning and initializing these submodules recursively until it fills up the local hard drive**.

If a design decision has been made to directly include all repos with dependencies across the company within each repo at the first level so that unit tests can be included in each repo directly without having to create separate environments for testing, this problem will exist. This decision is the only way to create tests in a repo with these types of interdependencies that also take advantage of the automatic library versioning that comes for free with sub-modules. If you want clean, modular repos that are independent of others, especially from a testing perspective, this may be the only clean solution.

I have complete novices to Git using Git Extensions on a team where some members only need to use this tool chain infrequently. Git Extensions is great for this because they don't need to remember esoteric command-line flags, etc. This recursion issue, however, is a big headache for our team in GE because it is incorrect for our team all the time. I can't fix it by having everyone setup their options a certain way, for example.

---

Yes, I can make a script to update non-recursively (which I have done), but then I still have to train everyone on the team on multiple rules:

1. ALWAYS uncheck the AUTOMATICALLY selected (no option to change this behavior) "initialized all sub-modules" checkbox on clone (which initializes recursively without saying it does).
2. After installing, manually update a couple different options to have GE NEVER update submodules on checkout and not ask to do so.
3. Train them to NEVER update submodules from the built-in commands and options
4. Train them to always update submodules using the script button after every checkout, clone, etc.

I've had people wait hours to see if the cloning would complete, just figuring there were network issues, etc. I agree this may be an edge case, but it is one with extremely user-unfriendly consequences for those who need to use non-recursive updates. 

----

## Concepts for Enhancement

Several options to resolve this, in order of value per effort:

1. Add a single option that globally changes between recursive or non-recursive for ALL submodule operations that currently use recursive (initialize when cloning, updating, syncing, etc.)

2. Add options for each submodule operation type (cloning, update, syncing, automatic update on checkout) to enable/disable recursion. Potentially allow for custom arguments for each command.

3. Provide both recursive and non-recursive options for all submodules functions. (could be in addition to # 1)
    * At cloning screen, rather than just "initialize all submodules" there is a second checkmark or radio option to select recursive or not
    * For Updating/Syncing, have both an "Update" and "Update recursively" option
    * For updating submodules automatically on checkout, a separate option is added to indicate whether it is recursive or not

4. For option 3, for automatic updating at checkout, add third option to only update submodules recursively if they are already initialized

5. Add some method of detecting cloning recursively (i.e. a particular repo was already used at a higher level is simpler method, but detecting actual recursion would be the ideal case) and ask user or have different options for how to handle this situation.

6. Some kind of per repo options for all the above

## Summary

Due to the invasive nature of the current design (for people that are affected), I recommend at least option 1 be implemented, so that people that need submodule operations to be non-recursive globally at least have a "setup once" option. This is a simple change with minimal effort, that would require only a single option.

Other options may be viable (option 2 or 3 in particular), but unless more people continue asking for enhancements for submodules around recursion, I'd say just option 1 is a safe bet for the moment.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4075.0
- DPI 120dpi (125% scaling)

**Comment by andry81** [comment]
Another approach with the per submodule flag.
But does not work either:

https://github.com/gitextensions/gitextensions/issues/11783
