### ISSUE TITLE
Font used by Console Emulator does not scale appropriately for high-dpi

### ISSUE THREAD

**Issue by johndog** [gitextensions/gitextensions#8411]
## Current behaviour

The console window pop-up for command output uses a font that is much too large (perhaps only on a high-DPI display?).

## Expected behaviour

Console font should be commensurate with the rest of the UI.

## Steps to reproduce

0. Use a High DPI display (not sure if required)
1. Make sure "Use Console Emulator for console output in command dialogs" is enabled in Advanced options.
2. Run any command (such as an interactive rebase) that causes GitEx to present a console window for output.

Note: 

- Turning off Console Emulator returns to a normal sized font.
- Configuring the Console Font size under Detailed->Browse repository window->Console emulator... does not affect the find size of this window.  It does affect the color scheme.

## Screenshots

Compare the console font size to the other text around the dialog (e.g. the buttons).  It is probably 2x the size.

![image](https://user-images.githubusercontent.com/22213780/90936552-450b1d80-e3ba-11ea-82b8-d3b8c815d1c4.png)

## Did this work in previous version of GitExtensions

N/A

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.vfs.1.0
- Microsoft Windows NT 10.0.20190.0
- .NET Framework 4.8.4210.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I don't think there's anything we can do at this point. Closing.
