### ISSUE TITLE
3.4.3 released, but changelog not updated 

### ISSUE THREAD

**Issue by DocGitHub** [gitextensions/gitextensions#8417]
## Current behaviour

GitExt 3.4.2 , shows there is an update 3.4.3 and has a link to [ChangeLog](https://github.com/gitextensions/gitextensions/blob/master/GitUI/Resources/ChangeLog.md)

## Expected behaviour

The content of ChangeLog should contain latest release

## Steps to reproduce

Click Check updates --> Show ChangeLog, see attached screenshot

## Screenshots

![image](https://user-images.githubusercontent.com/34685270/91288265-16fa5480-e791-11ea-9b44-ac3de65fedbc.png)

## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by pmiossec** [comment]
Indeed, you're right.
If you still need it, you could find it here: https://github.com/gitextensions/gitextensions/releases/tag/v3.4.3

**Comment by pmiossec** [comment]
Fixed with https://github.com/gitextensions/gitextensions/commit/4285697763827343859d9fda2fea6cd597142d14
