### ISSUE TITLE
JumpList still not working

### ISSUE THREAD

**Issue by lanfeust69** [gitextensions/gitextensions#8421]
At least on my machine (Win10 1709 16299.2045), the fix in #7941 doesn't work.

While we may expect the main window handle to exist when there is a control handle, this is not the case : in `FormBrowse.OnLoad()`, the `Handle` property is non-zero, but 
`Process.GetCurrentProcess().MainWindowHandle` *is* zero.

I tried moving the call to `_windowsJumpListManager.CreateJumpList()` in `FormBrowse.OnActivated()` instead, and this works. However, I'm not sure this is a correct fix, as this has at least one serious drawback : the `AddToRecent()` call doesn't work if directly launching a repo, especially from the Shell extension in Explorer, since the JumpList hasn't been created yet at that point.

**Comment by gerhardol** [comment]
What commit are using?
There were a change some weeks ago (a late change for 3.4 that was fixed at first only in 3.4).

How do you start GE, restoring last or not?
What are you doing in detail?

**Comment by lanfeust69** [comment]
I'm using latest version (3.4.3.9999), so I compiled d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1.

If "restoring last or not" refers to "Open last working directory on startup" in General Settings, then I never used that.

I don't "do" anything actually. Whatever the way to launch GE (from the start menu, from the Desktop shortcut, from the Taskbar, whether pinned there or not, from an old .gitext entry in the JumpList (created when it used to work, can't tell when, sorry), from a right click in Explorer, or from the command line), I never see the [`Commit`, `Push`, `Pull`] buttons under the thumbnails, which shows that the JumpList hasn't been created. And then, unsurprisingly, new repos I open don't show up in said JumpList. I only have the "old" ones (but I suppose windows displays them sorted by date, so whenever I open a repo that has such an old entry, the entry then bubbles to the top of the list).

Additional notes :
- I wasn't sure of that, but I just checked that I see the same behavior on my home PC, running Windows10 2004.
- When debugging, and `Process.GetCurrentProcess().MainWindowHandle` is zero, there is indeed nothing visible on the screen, while if I move the `CreateJumpList` to `OnActivated()`, there is a windows (still empty, I suppose the Paint has not been done yet). Maybe a solution could be to have a "Splash Screen" that ensures the `MainWindowHandle` is created early on ?

**Comment by RussKie** [comment]
> * Maybe a solution could be to have a "Splash Screen" that ensures the `MainWindowHandle` is created early on ?

We had a splash screen, but it was retired since it is not a modern Windows experience.



> * When debugging, and `Process.GetCurrentProcess().MainWindowHandle` is zero, there is indeed nothing visible on the screen, while if I move the `CreateJumpList` to `OnActivated()`

Perhaps a fox could be moving  `CreateJumpList` to `OnHandleCreated` point, which is raised when the form receives a handle?

**Comment by hani77979** [comment]
H

**Comment by hani77979** [comment]
N

**Comment by lanfeust69** [comment]
@RussKie : `OnHandleCreated` is called even *before* `OnLoad`, that won't work.

I just pushed PR #8499 with what I've been using for some time now.

**Comment by RussKie** [comment]
> `OnHandleCreated` is called even _before_ `OnLoad`, that won't work.

I've learned something new, thank you.
It appears the [docs](https://docs.microsoft.com/dotnet/api/system.diagnostics.process.mainwindowhandle#remarks) are explicit that `MainWindowHandle` is unset until a window has been shown.
