### ISSUE TITLE
Add Smart Git Ignore UI Feature

### ISSUE THREAD

**Issue by mbostwick** [gitextensions/gitextensions#8422]
## Feature description
The Default ignore pattern that is added is often broad and could be improved by using a smarter git ignore option. Github offers [lots of default ignore patterns](https://github.com/github/gitignore):

This feature would add a button to the screen shown below, which would enable selecting a different default git ignore pattern:
![image](https://user-images.githubusercontent.com/547590/91486603-24d3d680-e872-11ea-880a-e7e18732f94f.png)

## Environment
..Any..

**Comment by pmiossec** [comment]
You mean something better than what is proposed through the 2 links at
the bottom right?

If yes, you should explain a little better what you expect...

**Comment by mbostwick** [comment]
What I was saying is to add a context menu button on the default ignores, or adding a separate button to select a specific git ignore pattern. I didn't add much detail because really the goal is just to use a better git ignore so every project doesn't use the stock git ignore, and letting who ever ends up crafting the PR be free to approach it anyway they want seems smarter then being overly detail.  I was thinking this could be a cool small feature for https://hacktoberfest.digitalocean.com/

**Comment by RussKie** [comment]
The telemetry (that we have for those users who opted in) doesn't show a significant use of this form. So spending efforts here won't have significant impact.

> add a context menu button on the default ignores, or adding a separate button to select a specific git ignore pattern.

Do I understand it correctly that your proposal is to generate an unknown number of text resources and compile them into the assembly, to accommodate a random user who doesn't want to click a link and go to https://github.com/github/gitignore which has a collection can pick one? 
This doesn't sounds like a good proposition from any angle, sorry.

**Comment by mbostwick** [comment]
I would argue the telemetry means the opposite of what said. The fact that users don't spend much time using that screens means most people don't use that screen. Most people likely just click the default ignore and move on. This means that alot of people are using a poor git ignore choice for there project. Improving the git ignore choice would mean people using the project aren't all using the same thing.  Furthermore, the way you would understand how git ignore is being used is to understand how git ignores are being used, which is not done on the screen being improved. 

The main reason I left the issue to the dev who actually writes the PR, is because until someone gets in there and adds a smarter git ignore structure, trying to spec it out, rather just letting a dev be more fluid is going to slow someone down rather then improve it.

**Comment by RussKie** [comment]
> I would argue the telemetry means the opposite of what said. The fact that users don't spend much time using that screens means most people don't use that screen. Most people likely just click the default ignore and move on.

...or users just don't use this dialog at all, and copy existing .gitignore file from another established project.
In the 7 or so years using the app I think I may have opened this dialog once or twice. Instead I just copy existing .gitignore.

**Comment by RussKie** [comment]
Thank you for the suggestion, but given this will be a lot of work for a low value feature in a seldomly used form I'm closing this.

**Comment by mbostwick** [comment]
Why not treat it as pull request only ?

**Comment by RussKie** [comment]
Because I see no value on this, nor I want to maintain any code associated
with it.

**Comment by mbostwick** [comment]
🤷 perhaps you right, but for sure don't want anything to do with writing code for this project, given your tone and outlook.. good luck and thanks for the hard work !
