### ISSUE TITLE
"copy new version" and "old version" in diff view keep unwanted text

### ISSUE THREAD

**Issue by valeriob** [gitextensions/gitextensions#8439]
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4200.0
- DPI 96dpi (no scaling)

Sometime is need to copy some changes from diff between two versions but it not works as it should - see screen - there is two option "copy new version" and "copy old version" both work but do not copy the original file, they also copy all the unwanted chars like : 

diff --git a/src/FileName.cs b/src/FileName.cs
index 6cfe43030..08096e127 100644
--- a/src/FileName.cs
+++ b/src/FileName.cs
@@ -76,7 +76,8 @@ namespace OnRtls.Flotta

**Comment by mstv** [comment]
How to reproduce, @valeriob?

I had a similar issue in the Commit dialog. I marked a few lines with the mouse, then <kbd>Ctrl</kbd>+<kbd>C</kbd>.
Though I had no time to analyze (I cannot share the repo anyway).

**Comment by valeriob** [comment]
Hi,
the problem is in any diff view, just select all text, right click on the selected text and choose "copy new version" or "copy old version", the thing that is copied is not the clean code.

**Comment by RussKie** [comment]
![image](https://user-images.githubusercontent.com/4403806/94263678-c8e79500-ff78-11ea-887b-e5468b1577a7.png)

<details>
<summary>First option from the context menu - Copy</summary>

```
diff --git a/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs b/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
index 9923af5b9..23c46dd08 100644
--- a/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
+++ b/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
@@ -61,7 +61,11 @@ public bool Merge()
             protected override void ApplyStyle()
             {
                 base.ApplyStyle();
-                TreeViewNode.ImageKey = TreeViewNode.SelectedImageKey = nameof(Images.TagHorizontal);
+
+                TreeViewNode.ImageKey = TreeViewNode.SelectedImageKey =
+                    Visible
+                        ? nameof(Images.TagHorizontal)
+                        : nameof(Images.EyeClosed);
             }
 
             public bool Checkout()
```

</details>

<details>
<summary>First option from the context menu - Copy patch</summary>

```
diff --git a/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs b/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
index 9923af5b9..23c46dd08 100644
--- a/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
+++ b/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
@@ -61,7 +61,11 @@ public bool Merge()
             protected override void ApplyStyle()
             {
                 base.ApplyStyle();
-                TreeViewNode.ImageKey = TreeViewNode.SelectedImageKey = nameof(Images.TagHorizontal);
+
+                TreeViewNode.ImageKey = TreeViewNode.SelectedImageKey =
+                    Visible
+                        ? nameof(Images.TagHorizontal)
+                        : nameof(Images.EyeClosed);
             }
 
             public bool Checkout()
```

</details>

<details>
<summary>First option from the context menu - Copy new version</summary>

```
diff --git a/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs b/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
index 9923af5b9..23c46dd08 100644
--- a/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
+++ b/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
@@ -61,7 +61,11 @@ public bool Merge()
             protected override void ApplyStyle()
             {
                 base.ApplyStyle();
+
+                TreeViewNode.ImageKey = TreeViewNode.SelectedImageKey =
+                    Visible
+                        ? nameof(Images.TagHorizontal)
+                        : nameof(Images.EyeClosed);
             }
 
             public bool Checkout()
```

</details>

<details>
<summary>First option from the context menu - Copy old version</summary>

```
diff --git a/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs b/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
index 9923af5b9..23c46dd08 100644
--- a/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
+++ b/GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
@@ -61,7 +61,11 @@ public bool Merge()
             protected override void ApplyStyle()
             {
                 base.ApplyStyle();
-                TreeViewNode.ImageKey = TreeViewNode.SelectedImageKey = nameof(Images.TagHorizontal);
             }
 
             public bool Checkout()
```

</details>

**Comment by gerhardol** [comment]
Implementation in FileVierer.cs copyNewVersionToolStripMenuItem_Click() is to copy all lines not starting with +/- so you get context lines too.

If you copy two sections of a patch, it will be strange to just ignore the header.
The initial header could be ignored.

**Comment by RussKie** [comment]
Closing as stale.
