### ISSUE TITLE
Copying & pasting not working in bash if opened from UI

### ISSUE THREAD

**Issue by jlocans** [gitextensions/gitextensions#8445]
## Current behaviour
If I open bash from UI, then commands Ctrl+Insert and Shift+Insert don't work. Instead `~5` is typed into console for Ctrl+Insert and `~2` for Shift+Insert. There are also visual differences between bash launched from UI and launched directly, maybe that gives some hint. To the right is bash launched from UI.
![image](https://user-images.githubusercontent.com/8797504/92713922-33d38200-f364-11ea-9354-56430b8fecc6.png)

## Expected behaviour
Ctrl+Insert should copy selection to clipboard and Shift+Insert should paste from clipboard.

## Steps to reproduce
Launch bash from UI and try to copy or paste some text using Ctrl+Insert and Shift+Insert

## Screenshots
What is displayed in console when pressing Ctrl+Insert and Shift+Insert
![image](https://user-images.githubusercontent.com/8797504/92714472-ef94b180-f364-11ea-86e8-b4219be77d68.png)

## Did this work in previous version of GitExtensions
Don't know. Hadn't used it for a while and this is on a totally fresh machine.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4220.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
One is git bash and one is cmd.exe running git bash.

**Comment by gerhardol** [comment]
In next version the button is a drop down, so the shell selectable.

The embedded shell in the tab is a configurable, you can choose cmd based as well as git-bash

![image](https://user-images.githubusercontent.com/6248932/92969971-33c7a500-f47e-11ea-8760-ccdea3b6824f.png)
