### ISSUE TITLE
Settings: Checkbox not well reflecting the setting state

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#8446]
## Current behaviour

When the only settings source available is "Global for all repositories" and so that there is no "Effective" source, the value could be not well set to the checkbox

See checkbox in is in intermediate state even if the setting value is 'true'/checked:
![image](https://user-images.githubusercontent.com/460196/92475945-7c613300-f1de-11ea-81bf-4769e87c7e16.png)

## Expected behaviour

The checkbox is checked.

## Steps to reproduce

I don't know at the moment :(

## Did this work in previous version of GitExtensions

Not sure but I don't think so.

## Environment

- Git Extensions 33.33.33
- Build 09a8426c36a826a76f6a3abd65b6914ae94d047a (Dirty)
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4210.0
- DPI 168dpi (175% scaling)

## Diagnostic

Hint: that's perhaps here: https://github.com/gitextensions/gitextensions/blob/master/Plugins/GitUIPluginInterfaces/Settings/BoolSetting.cs#L57

**Comment by vbjay** [comment]
That means it is not set.

**Comment by ivangrek** [comment]
Just default value

**Comment by pmiossec** [comment]
No, because the default value of this setting is true.
So if indeed the default value would have been used, the checkbox would have been checked. So there is really a bad behavior....

**Comment by ivangrek** [comment]
`public static readonly BoolNullableSetting ShowConEmuTab = new BoolNullableSetting("ShowConEmuTab", DetailedSettingsPath, true);`

BoolNullableSetting

![image](https://user-images.githubusercontent.com/3169265/92871843-0a6f3080-f40e-11ea-9560-011cc5cee992.png)

**Comment by pmiossec** [comment]
That's not the reason. Indeed, that allows the checkbox to be in intermediate state but that doesn't explain why the checkbox state doesn't reflect the value of the setting which is 'true'.

**Comment by ivangrek** [comment]
Why we use the nullable setting?
Why the checkbox uses three states?

**Comment by pmiossec** [comment]
That's good question. I have started to use the a `BoolSetting` instead a `NullBoolSetting` but, once again, as I discovered that **it is not the root cause of the problem**, I decided to stop and try to understand what is the real problem.

 Because that perhaps could give some strange result for other types... before going to bed 😴

**Comment by ivangrek** [comment]
The default has no effect on BoolNullableSetting.
Maybe this.

![image](https://user-images.githubusercontent.com/3169265/92991220-07963d80-f4eb-11ea-8be9-8038038f37b3.png)

![image](https://user-images.githubusercontent.com/3169265/92991307-b63a7e00-f4eb-11ea-8cc6-5b03f995719d.png)

Try to reproduce on the latest revision.

**Comment by ivangrek** [comment]
I think it is not relevant after  #8450, #8451.

**Comment by RussKie** [comment]
Can you please check?

**Comment by ivangrek** [comment]
The purpose of the "Effective" setting is not clear. I would be glad if someone could clarify the purpose.

**Comment by pmiossec** [comment]
>Can you please check?

The issue is still there with the last version of `master`.

But #8458 works well...

**Comment by pmiossec** [comment]
>The purpose of the "Effective" setting is not clear. I would be glad if someone could clarify the purpose.

From what I understood during the years of GitExtensions use...(disclamer: but I didn't check in the source if what I think is right)

1. The main goal is to show to the user what is the "final" value that will be taken into account by aggregating the different values in the other source (from the less priority one "Global for all repositories",  to the more one "Local for current repository") .

For me, from this feature point of view it could be gave been made readonly.

2. But, for convenience I think, it has been made editable and if you update a value in the "Effective" setting, it will be store in the "Local for current repository" source
