### ISSUE TITLE
No publish gerrit change icon button in git extension new version 3.4.3

### ISSUE THREAD

**Issue by vincetm** [gitextensions/gitextensions#8464]
## Current behaviour

No publish gerrit change icon in new version 3.4.3
![image](https://user-images.githubusercontent.com/22842181/93462406-dec1de00-f918-11ea-9daf-d74f2c2ad679.png)

## Expected behaviour
I fall back to version to 3.2, the publish gerrit change comes back.
![image](https://user-images.githubusercontent.com/22842181/93462236-95718e80-f918-11ea-9692-bc8961704584.png)

## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by pmiossec** [comment]
Not sure to get all the problem but is that because now the Gerrit feature is done trough an external plugin?

Menu "Plugins" > "Plugin manager" > Search for "Gerrit" and install...

**Comment by vincetm** [comment]
@pmiossec You are right. This help me solve a problem I had been having for a long time. Thanks~
