### ISSUE TITLE
Set "Cancel" button as the Reset prompt default

### ISSUE THREAD

**Issue by Dunloop26** [gitextensions/gitextensions#8467]
## Feature description

So, I use "R" a lot to open the "Reset Changes" prompt and resetting some of the files that I didn't want to change, but I've ran into a problem today, right on the Commits window, where the button labeled as "Reset" on the "Reset Changes" prompt is focused instead of the button labeled as "Cancel" 

Pressing "R" pops up this prompt asking you if you want to reset your changes, but double tapping "R" accepts which ever is highlighted, creating a mistake-prone behaviour

So, I pressed "R" but my finger slipped away a second time, hitting "R" again, successfully aproving the prompt and consequely, resetting my changes.

And so, I reset all the changes from my files, without even noticing

I wish that this behaviour is set to the opposite action, cancel, rather than a quick way of resetting changes cause, it's easier to click it again and say "I want to reset my changes" rather than "Now I have to redo everything because of my mistake"

Thank you, very much!

![Screenshot_1](https://user-images.githubusercontent.com/46170269/93632312-bdadcb80-f9b2-11ea-80c3-f681203c21b8.png)

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4220.0
- DPI 96dpi (no scaling)

**Comment by BrianFreemanAtlanta** [comment]
It appears that there are 2 issues tied together
1. "default"/active button when the form is shown - this will be run if user hits "enter"
2. Keyboard shortcut keys on the form - 
  a. "r" for reset
  b. "c" for cancel

The "r" and "c" keys will work regardless of what button has the focus. 

Pressing "r" twice will always activate the "reset" command - unless the keyboard "mnemonic" of "r" is removed.

The active button can be changed with a simple `bnCancel.Select();` but that will not resolve the "r" "r" issue.

@RussKie do we want to remove the keyboard shortcut keys or simply correct the default button.

**Comment by RussKie** [comment]
I'd keep the mnemonics, and update the default button only.
Thank you

**Comment by RussKie** [comment]
Also use `btnCancel.Focus()`.

**Comment by oriash93** [comment]
Pressing "R" again will reset the changes even if the initial focus is on the "Cancel" button. What makes "R" trigger the "Reset" button is the mnemonic key feature. I made a PR to disable it.

**Comment by mstv** [comment]
> Pressing "r" twice will always activate the "reset" command - unless the keyboard "mnemonic" of "r" is removed.

... or changed.
This has never happened to me but obviously to others. That is what this issue is about -- reopening.
The danger can be reduced by changing the mnemonic. (Never remove mnemonics!)
If there are objections, officially reject this issue with a reason, please.

**Comment by BrianFreemanAtlanta** [comment]
@mstv,  @RussKie directed me to keep the mnemonic. Hitting r twice is a different issue from the default button. You may want to open a separate issue for hitting r twice. Then they can respond with the reason to implement or not more directly to that request.

**Comment by mstv** [comment]
Unfortunately, the issue title does not match the description. This will not become a very long discussion. Let us keep it in one place.

**Comment by RussKie** [comment]
Sorry I'm really spread thin, and with this I do gloss over and miss certain things. 
I've reflected over this a bit more, and I think we can/should change the mnemonics for the [_R_eset] button. Should we change to "E" or "T"?

**Comment by BrianFreemanAtlanta** [comment]
My thought would be "E". I can do a new/separate pull request with this change.

**Comment by hultqvist** [comment]
I don't see the motivation to change the default button from confirm to cancel.

The problem described was double tapping R, why was the default button then changed?

The prompt is still the same "Do you want to reset..."
Pressing enter should confirm the prompted action.

Old method: **Reset**(R) --> **Confirm**(Enter)
New: **Reset**(R) --> **rEset**(E)
