### ISSUE TITLE
Add support for conventional commits

### ISSUE THREAD

**Issue by pbeny** [gitextensions/gitextensions#8472]
## Feature description
Please add support for conventional commits, thank you.
https://www.conventionalcommits.org/en/v1.0.0/#specification
https://github.com/conventional-changelog/commitlint/tree/master/@commitlint/config-conventional

### How it should work
When user enable this feature, he must fill regular expression which will be used for commit message validation. If commit message doesn't meet regex, commit failed and user must correct commit message.

## Environment

- GitExtensions version: Any
- GIT version: Any
- OS version: Windows
- .NET version: .NET Core 3.1

**Comment by pmiossec** [comment]
I use something similar to that and In GitExtensions, there is a commit message regex validation:

![image](https://user-images.githubusercontent.com/460196/93985981-0d5f0f00-fd86-11ea-9b7b-0306391d2b85.png)

We use such regex to do the job: `((chore)|(feat)|(fix)|(docs)|(style)|(refactor)|(test))(\([^)]*\))*:.+`
You can tweak it to your needs...

Is this enough or do you imagine something else?

**Comment by RussKie** [comment]
Pull requests are welcome.

**Comment by RussKie** [comment]
This doesn't belong to the general Git Extension app, it should be developed as a plugin.
