### ISSUE TITLE
Remember commit settings

### ISSUE THREAD

**Issue by MrExplode** [gitextensions/gitextensions#8473]
So I really want to sign my commits with gpg, but I couldn't get the commit dialog options remember my choices. Is there any way to remember my options? I don't want to fill the specific key id field every time manually.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.26.2.windows.1
- Microsoft Windows NT 10.0.20185.0
- .NET Framework 4.8.4161.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
I'd like to share the presentation “'Git Signing'” with you. Please click
the link to view it.
https://prezi.com/view/pHprUqzvjrsTxLBt4zfF

**Comment by gerhardol** [comment]
Previous discussion in #8268

**Comment by vbjay** [comment]
This is the gpg key and my prezi link walks you through setting all of git
signing up. Gpg4win is used but you can set up other gpg clients. Sign offs
are a different feature of git.

Git signjng
https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

Signoff

https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

**Comment by RussKie** [comment]
Please use git configurations for this.
Right now this work is not on our roadmap. If this is something you feel passionate about - you're welcome to discuss how you see it implemented and send a PR.
