### ISSUE TITLE
[NBug] インデックスが範囲を超えています。負でない値で、コレクションのサイズよりも小さくなければなりません。パラメーター名...

### ISSUE THREAD

**Issue by sxp200422** [gitextensions/gitextensions#8475]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.ArgumentOutOfRangeException: インデックスが範囲を超えています。負でない値で、コレクションのサイズよりも小さくなければなりません。
パラメーター名:index
   場所 System.Collections.ArrayList.get_Item(Int32 index)
   場所 System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   場所 System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   場所 GitUI.RevisionGridControl.OnGridViewCellMouseDown(Object sender, DataGridViewCellMouseEventArgs e)
   場所 System.Windows.Forms.DataGridView.OnCellMouseDown(DataGridViewCellMouseEventArgs e)
   場所 System.Windows.Forms.DataGridView.OnMouseDown(MouseEventArgs e)
   場所 GitUI.UserControls.RevisionGrid.RevisionDataGridView.OnMouseDown(MouseEventArgs e)
   場所 System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   場所 System.Windows.Forms.Control.WndProc(Message& m)
   場所 System.Windows.Forms.DataGridView.WndProc(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   場所 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
right click commit

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4180.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Is it reproducible?

**Comment by pmiossec** [comment]
Looking at the code:

https://github.com/gitextensions/gitextensions/blob/master/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs#L1419

there are already controls on the revision grid bounds to prevent this type of error.
So, for me, there is a possibility that it is caused by a refresh of the revision grid.

@sxp200422 is it the case?

**Comment by RussKie** [comment]
Yep, I suppose it could be some kind of a race condition when we set the
selection on line:1438.

**Comment by gerhardol** [comment]
Duplicate of #7374
Any way to reproduce, more of what you did do?

There was a correction for #7374 in #7921 that is in 3.4, there seem to be some more situation
