### ISSUE TITLE
Can't get correct commit message using {cMessage}

### ISSUE THREAD

**Issue by zjh-coder** [gitextensions/gitextensions#8486]
## Current behaviour
I want to execute a python script after pushing a commit to Gerrit, so I set a script.
But I get empty value by {cMessage} after push commit, and I can get only first line of commit message while right click and
choose Run Script. 

## Expected behaviour
I can get full commit message after push commit or just run script
## Steps to reproduce
Following are the script I use, just in test stage.
```python
import sys

def main():
    print sys.argv[1];

main()
```

## Screenshots
Settings
![image](https://user-images.githubusercontent.com/25637051/94357239-a87b2000-00c9-11eb-845c-0e8dd4fb0a4b.png)
Empty after push
![image](https://user-images.githubusercontent.com/25637051/94359992-c30ac480-00dc-11eb-8af8-a78d7408f2bd.png)
First line using "Run Script"
![image](https://user-images.githubusercontent.com/25637051/94360008-dcac0c00-00dc-11eb-992f-4e7ee3260d82.png)

full commit message are:

NEWGS-12330 China - gcc.controller.impl.LoginControllerImpl.log

Issue: NEWGS-12330
Type: Internal Bug
Change-Id: I4ba4d7438affe48c9340125b8853136d4888e3e4

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.4240.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
I fear we need to postpone the script execution until the RevisionGrid has reloaded.
Possible workaround: Since the commit [message] should not be changed by the push operation, it is valid before the push and can be given to the script already. You could add the `git push` command to your script, so you push just by running the script. (Hit <kbd>F12</kbd> after pushing if you want to see the exact command.)

Unfortunately, `{cMessage}`/`{sMessage}` are misleading because they yield just the first line - should have been named `{cSubject}`/`{sSubject}`. 
I propose to add `{cSubject}`/`{sSubject}` and to let `{cMessage}`/`{sMessage}` yield the full message. The linefeed characters must be replaced with e.g. `\n`.

**Comment by RussKie** [comment]
@mstv have a look at #8487

**Comment by mstv** [comment]
#8487 addresses the minor but complicated part of the issue in an elegant way at first glance.

**Comment by zjh-coder** [comment]
@mstv Thank you for your reponse, do you mean that I can use some python lib like gitpython to push code?
If I do so, can I still using gitextension to finish the whole process?

**Comment by mstv** [comment]
> that I can use some python lib like gitpython to push code?
If I do so, can I still using gitextension to finish the whole process?

Yes, that would work.
But you won't need this workaround, because #8488 (together with the contained #8487) should fix your issue.
Test with the [portable build](https://ci.appveyor.com/api/buildjobs/f38yfwvu44gln65a/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.10218-2fb29d4e6.zip), please.

**Comment by zjh-coder** [comment]
> Test with the [portable build](https://ci.appveyor.com/api/buildjobs/f38yfwvu44gln65a/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.10218-2fb29d4e6.zip), please.

I'm testing the portable build and getting this error when open the Settings:

## Error Details
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: i. Path '', line 0, position 0.
   在 Newtonsoft.Json.JsonTextReader.ParseValue()
   在 Newtonsoft.Json.JsonTextReader.Read()
   在 Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   在 Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   在 GitCommands.Settings.Setting.SettingOf`1.<>c.<GetValue>b__20_0(String value)
   在 GitCommands.SettingsCache.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   在 GitCommands.Settings.SettingsContainer`2.TryGetValue[T](String name, T defaultValue, Func`2 decode, T& value)
   在 GitCommands.Settings.SettingsContainer`2.GetValue[T](String name, T defaultValue, Func`2 decode)
   在 GitCommands.Settings.SettingsPath.GetValue[T](String name, T defaultValue, Func`2 decode)
   在 GitCommands.Settings.Setting.SettingOf`1.GetValue(String name)
   在 GitCommands.Settings.Setting.SettingOf`1.get_Value()
   在 GitUI.CommandsDialogs.SettingsDialog.Pages.GitConfigSettingsPage.SettingsToPage()
   在 GitUI.CommandsDialogs.SettingsDialog.SettingsPageBase.LoadSettings()
   在 GitUI.CommandsDialogs.FormSettings.LoadSettings()
   在 GitUI.CommandsDialogs.FormSettings.FormSettings_Shown(Object sender, EventArgs e)
   在 System.Windows.Forms.Form.OnShown(EventArgs e)
   在 System.Windows.Forms.Form.CallShownEvent()
   在 System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   在 System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   在 System.Windows.Forms.Control.InvokeMarshaledCallbacks()
```


## Environment
- Git Extensions 4.0.0.10218
- Build 2fb29d4e6b29d1218ba4a5e21041cec9b0dbf171 (Dirty)
- Git 2.27.0.windows.1 (recommended: 2.28.0 or later)
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.8.4240.0
- DPI 96dpi (no scaling)


![image](https://user-images.githubusercontent.com/25637051/94387384-94442b00-017c-11eb-95e2-b78ac651b64a.png)
