### ISSUE TITLE
Missing Setting for CommitInfo Position

### ISSUE THREAD

**Issue by knolleCC** [gitextensions/gitextensions#8500]
## Current behaviour

I can find no setting (in Tools/Settings dialog) to define the position of the CommitInfo view.
In my settings file I find the key `Detailed.ShowRevisionInfoNextToRevisionGrid` which is respected by the program, but there seems to be no way anymore to define it via the Settings dialog.
I see from the code, that this old key was replaced by `CommitInfoPosition`. However, this new key is not present in my settings file and I also cannot find a way to define it via the program.

## Expected behaviour

There should be a setting to define the CommitInfo view position, as there was before.

## Did this work in previous version of GitExtensions

Yes. But at least from using 3.3.1 it does not work anymore.

I am now using version 3.4.3.

**Comment by RussKie** [comment]
I don't believe there's an explicit setting any more, but this is how you configure it:
![image](https://user-images.githubusercontent.com/4403806/94799319-46525000-0426-11eb-9ee9-f13153fdb88d.png)

**Comment by knolleCC** [comment]
Ah, ok, thanks. Never saw this before :-)
