### ISSUE TITLE
Rename AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_pull_request_build.approved.txt

### ISSUE THREAD

**Issue by GintasS** [gitextensions/gitextensions#8505]
## Current behaviour
When forking gitextensions/gitextensions, an error occurs because a file exists with a very long name.

UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_pull_request_build.approved.txt: Filename too long

## Expected behaviour
We should rename this file to a shorter one to prevent this issue for happening, so we can clone this without any issues.

## Steps to reproduce
1. Fork gitextensions / gitextensions on GitHub.
2. Try to clone it via either GitExtensions client itself or just Git bash via git clone ...

## Screenshots

![image](https://user-images.githubusercontent.com/20372363/94945298-25036980-04e3-11eb-93ba-09048dbbab1a.png)

## Did this work in previous version of GitExtensions
Not so sure.

## Environment

- GitExtensions version: 3.4.3.9999
- GIT version:   2.21.0.windows.1
- OS version: Version 1909 (OS Build 18363.1082) Windows 10
- .NET version: -

**Comment by pmiossec** [comment]
This file name is generated from the test name, so it's difficult to rename it.
We have to rename the test and so will loose some meaning.
The workaround is to try to clone nearer to the drive root.

**Comment by GintasS** [comment]
I think renaming is justified in this case, since the file name introduces additional errors.

**Comment by gerhardol** [comment]
The name is 194 char, max Win path is 260
There is one 189 path file as well, next is 160, so it is not completely in vain to change this
However, expect many other repos to have a problem too if the prefix is more than 66 bytes, so low prio

**Comment by GintasS** [comment]
@gerhardol  I know it's out of scope, but I am new to this repository, and this is one of the errors that came up while trying to set up the whole repository locally. Now I'm receiving Error '...\Externals\ICSharpCode.TextEditor\Project\ICSharpCode.TextEditor.csproj'. Check that the project reference is valid and that the project file exists.

Error	NU1104	Unable to find project '...\Externals\Git.hub\Git.hub\Git.hub.csproj'. Check that the project reference is valid and that the project file exists.

and etc. I think I posted the a ticket in issues, but it got deleted.

**Comment by pmiossec** [comment]
For the projects errors, you have to initialized the git submodules.

**Comment by gerhardol** [comment]
> and etc. I think I posted the a ticket in issues, but it got deleted.

I moved it to discussions 
https://github.com/gitextensions/gitextensions/discussions/8507

**Comment by GintasS** [comment]
Thank you for help, maybe this is a good sign of editing a read me a bit, to be more beginner friendly, e.g include a sentence that you need to initialize git submodules.

**Comment by gerhardol** [comment]
> Thank you for help, maybe this is a good sign of editing a read me a bit, to be more beginner friendly, e.g include a sentence that you need to initialize git submodules.

There is a line, with a warning sign too (as well as mentioned once here and once in the discussion)
So what to improve?
If it is longer will other details be missed

**Comment by GintasS** [comment]
Yes, I just saw it, thanks.

**Comment by RussKie** [comment]
Long paths is a general Windows issue and one has to be mindful of this. I have been involved in projects that can only be cloned in paths not exceeding 10 chars including the disk (i.e. c:\path). Anyone doing a web development and dealing with node modules is stepping on this rake all the time.

If you're having troubles cloning make sure to enable long path support in git: `git config --system core.longpaths true`.
