### ISSUE TITLE
How to build a project as a new contributor

### ISSUE THREAD

**Issue by GintasS** [gitextensions/gitextensions#8507]
## Current behaviour
I want to contribute to gitextensions, but I can't seem to get the solution to build, is there any concrete guide available, because https://github.com/gitextensions/gitextensions/wiki/How-To:-build-instructions is not that detailed at all, I googled a few things, including issues from this repository, so found out that I need Wix, I installed that, also individual components on visual studio, still getting: 
Externals\ICSharpCode.TextEditor\Project\ICSharpCode.TextEditor.csproj'. Check that the project reference is valid and that the project file exists.	

and much more errors related to the references.

A few examples:

![image](https://user-images.githubusercontent.com/20372363/94959255-8afaeb80-04f9-11eb-9137-f147cd2e59a3.png)
![image](https://user-images.githubusercontent.com/20372363/94959271-94845380-04f9-11eb-8500-fd4bbc2e87bd.png)

I appreciate any help and sorry if this post is not meant to be here.

## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by pmiossec** [comment]
I think that is because you didn't initialized the git submodules.

Once you did it, that should build without problems.

**Comment by pmiossec** [comment]
Wix is needed only for building the setup so you don't need it to just
build and contribute...
