### ISSUE TITLE
Checkout windows in GitExtensions 4.0 CI build doesn't repond to 'Enter' key

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#8521]
Checkout any revision.
`Enter` key doesn't do anything.
Previously it used to press on Checkout which is the default action.

- Git Extensions 4.0.0.10290
- Build e1b3b0109dd62a12e0c3dbc15a30750d487d4d8f (Dirty)
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
See #8510
