### ISSUE TITLE
GitHub Extensions not tracking changes

### ISSUE THREAD

**Issue by CLIRResearch** [gitextensions/gitextensions#8551]
## Current behaviour

I had just completed a class and switched to Team Explorer.  I clicked Changes and expected to see the .SLN and .CS.  Instead, I am seeing "There are no unstaged changes in the working directory."

## Expected behaviour

I expected to see the files and solution as a change.

## Steps to reproduce

This started out-of-the-blue.  I added a new class to the Visual Studio C# solution.

## Did this work in previous version of GitExtensions

Possibly - but I have not recently taken any updates to Visual Studio or Extensions.

## Environment

- GitExtensions version:
- GIT version: 2.11.106.19330
- OS version: Windows 10 Professional
- .NET version: 4.9.03761

When I go to the GitHub pane - and click the URL for the remote repo, I am getting a 404 Error.  Looks like GitHub dropped my Repo.  I DID NOT REMOVE OR MOVE THIS REPO!!  I AM FED UP WITH CONSTANT ISSUES LIKE THIS.

**Comment by pmiossec** [comment]
>I AM FED UP WITH CONSTANT ISSUES LIKE THIS.

It seems that you have problems with other tools than Gitextensions. Here it is the github repository for Gitextensions tools

I think that you should find some help somewhere else...

**Comment by CLIRResearch** [comment]
Over the next month, we are will be moving our repositories off of GitHub.  The time lost to issues like this is expensive and creates a great deal of stress.  

 

 


 


	
		

Creative ∙ Loyal ∙ Innovative ∙ Reliable

DOUG KIMZEY

CLIR RESEARCH

ARCHITECT - PARTNER

 

1846 Big Buck Lane

Sevierville, Tennessee 37976

 <mailto:doug.kimzey@clirresearch.com> doug.kimzey@clirresearch.com

865-360-9536

**Comment by vbjay** [comment]
What part of this repo being self contained and not in control of GitHub do
you not understand?
