### ISSUE TITLE
Incomplete dark theme colors when reconnecting RDP session

### ISSUE THREAD

**Issue by NikolayXHD** [gitextensions/gitextensions#8554]
## Precondition

dark theme is selected

## Steps to reproduce

- Start Git Extesions in Remote Desktop session
- Disconnect from RDP
- Reconnect

## Current behavior 
Buttons and scrolls are bright now.

## Screenshot

before disconnecting from RDP, scrollbars are dark, as expected
![image](https://user-images.githubusercontent.com/12046452/96387390-4a15fe80-11aa-11eb-9ab8-7aa6fb80e3f0.png)

after disconnect / reconnect, scrollbars are bright
![image](https://user-images.githubusercontent.com/12046452/96387429-7fbae780-11aa-11eb-9e0e-3f29727a74c2.png)

## Expected behavior
Buttons and scrolls remain dark as they were before disconnecting from RDP session

## Environment

RDP session to Win10 machine

## Diagnostics

The same issue was first reliably reproduced by @RussKie by changing DPI after Git Extensions started.
https://github.com/gitextensions/gitextensions/pull/7213#issuecomment-688695587

The underlying mechanism is the same in both cases

see src\GitUI\Theming\Win32ThemeHooks.cs : 127

at application startup `Win32ThemeHooks` creates and remembers handles to windows Theme Data objects, assuming these handles will not change.

The handles are used to determine which control and which part is currently being rendered by Win32API.

When user changes DPI or disconnects / reconnects to RDP session, Windows creates Theme Data objects anew.

When later a WinAPI call to render a scrollbar happens, `Win32ThemeHook` assumes that some other unknown part of application is being rendered, because the theme data handle is different from scrollbar theme data handle it remembered at startup.

**Comment by RussKie** [comment]
Windows Forms can liberally recreate handles for many various reasons, so it'd be incorrect that handles remain static.

**Comment by NikolayXHD** [comment]
Do you mean exactly theme data handles? It's not the same as window handles.

**Comment by RussKie** [comment]
I was alluding to the window handles, but I wouldn't be suprised that theme handles change as well at certain point (e.g. DPI changed, theme changed, etc.).
