### ISSUE TITLE
Exception after creating the "Recent repositories" category on dashboard.

### ISSUE THREAD

**Issue by ghost** [gitextensions/gitextensions#8567]
## Current behaviour

Recent repositories list on Dashboard  allows to create "Recent repositories" category. 

## Expected behaviour

Prevent creating "Recent repositories" category.

## Steps to reproduce

Go to the dashboard.
Select the recent repository with the right mouse button.
Add new category "Recent repositories".

## Screenshots

After quick fix,

```
var groups = Enumerable.Repeat(_lvgRecentRepositories, 1)
    .Concat(recentRepositories.Concat(favouriteRepositories)
        .Select(repo => repo.Repo.Category)
        .Where(c => !string.IsNullOrWhiteSpace(c))
        .Distinct(GroupHeaderComparer)

        .Except(Enumerable.Repeat("Recent repositories", 1))

        .OrderBy(c => c)
        .Select(c => new ListViewGroup(c, c)))
    .AsReadOnlyList();
```
![image](https://user-images.githubusercontent.com/3169265/96791573-5fd13100-1401-11eb-8058-14abae824637.png)

![1](https://user-images.githubusercontent.com/3169265/96791826-d8d08880-1401-11eb-9c00-9ac3dd5c1e68.gif)

## Did this work in previous version of GitExtensions

Don't know.

## Environment

- Git Extensions 33.33.33
- Build 6e248754628f74fcfe24be53228178f4c75d4044 (Dirty)
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Nice! I clearly suck as a tester ;)))

**Comment by oriash93** [comment]
I would like to work on that please

**Comment by pmiossec** [comment]
Good for me except if @ivangrek want to work on it...

**Comment by ivangrek** [comment]
> I would like to work on that please

👍

**Comment by oriash93** [comment]
@RussKie I noticed this could also happen when a user **renames** a category to "Recent repositories". I want to add a special treatment to that "reserved" word when prompting the user for a category name (which will cover both cases).

Would you rather show a message when a user chooses that word? Or just ignore the action (dropping the input string)?

**Comment by RussKie** [comment]
We should probably show a message to inform the user.

**Comment by ivangrek** [comment]
I think we can consider this as the existing default category.
It follows from this that creation, renaming should not be performed, just as it works for other categories.
Most likely the name of this category is different in different languages.

**Comment by ivangrek** [comment]
We can use like .Union() to get unique categories where default category is included.
And simplify category creation without separation on two methods for favorite categories or not.

**Comment by RussKie** [comment]
Not near a computer, isn't this string localised?

**Comment by ivangrek** [comment]
[En]

![image](https://user-images.githubusercontent.com/3169265/96987119-3ca2a080-152b-11eb-9593-2bc4b16f13eb.png)

[De]

![image](https://user-images.githubusercontent.com/3169265/96987164-4af0bc80-152b-11eb-9019-b1d19ebbdfc3.png)

The category name changes for each language.

**Comment by oriash93** [comment]
> The category name changes for each language.

I intend to use the `TranslationString` object's `.Text` property, so no worries.

**Comment by oriash93** [comment]
I won't be able to work on it due to a tight schedule. Sorry
