### ISSUE TITLE
refresh button, prefix new branch name, multi deletion branch   

### ISSUE THREAD

**Issue by Cenarius1** [gitextensions/gitextensions#8578]
## Feature description

1. Refresh button, when I have opened "commit  to user" window and I change something in IDE, then I have to close and reopen. It could be button to refresh it or something like auto refreshing depends on setting.
2. Usually in project, branches starts with prefix containing user story ID like: "ABC100 - implement XYZ". Prefix "ABC" could save a bit of time.
3. When I do temp branches, I have to click delete and then click force deletion and then confirm. I have to do it for each single branch. Would it make sense to delete multiple branches? I delete ones a month, I have 10-20 branches and I like to remove it fast.

I am software developer and I use your great toll a lot. I have some thoughts which could perform my work faster. 
## Environment

- Newest Git
- Newest GitExtension
- Win10
- .NET Core 3.0

**Comment by pmiossec** [comment]
> * Refresh button, when I have opened "commit  to user" window and I change something in IDE, then I have to close and reopen. It could be button to refresh it or something like auto refreshing depends on setting.

I'm not sure to understand but do you mean these features? (or 'F5' key)

![image](https://user-images.githubusercontent.com/460196/97200070-0bd39d00-17b1-11eb-873f-df564331440c.png)



> * Usually in project, branches starts with prefix containing user story ID like: "ABC100 - implement XYZ". Prefix "ABC" could save a bit of time.

You should be more explicit on this but, IMHO, it seems to be a specific project need. So except if you come with a good ergonomic to be useful for others, that's something that won't be done in GitExtensions

> * When I do temp branches, I have to click delete and then click force deletion and then confirm. I have to do it for each single branch. Would it make sense to delete multiple branches? I delete ones a month, I have 10-20 branches and I like to remove it fast.

Did you tried the "Delete obsolete branch" plugin?


PS: when you have multiples things to ask, please create multiple issues otherwise the discussion will be difficult to follow.

>.NET Core 3.0

It seems that you are in the future because we don't still have a version running in dotnet core released 🤣

**Comment by RussKie** [comment]
"Delete branch" dialog supports deletion of multiple branches IIRC

**Comment by gerhardol** [comment]
For 1.
I do not like this myself

![image](https://user-images.githubusercontent.com/6248932/97234837-eb700680-17e1-11eb-9b47-71703c9e09ba.png)

**Comment by RussKie** [comment]
> 3\. When I do temp branches, I have to click delete and then click force deletion and then confirm. I have to do it for each single branch. Would it make sense to delete multiple branches? I delete ones a month, I have 10-20 branches and I like to remove it fast.

> "Delete branch" dialog supports deletion of multiple branches IIRC

![image](https://user-images.githubusercontent.com/4403806/97240256-ec388500-1841-11eb-838c-b7cbc6402f3b.png)

**Comment by pmiossec** [comment]
> [Refresh dialog on form focus] I do not like this myself

Me neither because it refresh too often. But perhaps we could do a refresh only when a file has changed since the last refresh, based on the modification date (for example if a file has been changed after the last modification date "memorized" when we did the last refresh)
