### ISSUE TITLE
Log truncated when "git clean"

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#8580]
## Current behaviour

Open Commands|Clean working directory
Press "Preview"

The showmodal window says :

![image](https://user-images.githubusercontent.com/9248729/97424932-b6fb6800-1911-11eb-9c29-8214538b23cf.png)

but the log in the "Clean working directory" windows is truncated.

![image](https://user-images.githubusercontent.com/9248729/97425009-d1cddc80-1911-11eb-905a-28477ad133fd.png)

There is also some no printable characters.

## Expected behaviour

No truncate.

## Did this work in previous version of GitExtensions

No idea

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by ivangrek** [comment]
This text from "ConEmu*.log".

**Comment by cristianst85** [comment]
This issue puzzled me for a while. So far the only solution that I could come up with seems to be to strip control characters from the ConEmu output (but this seems to be a workaround at best).

See this commit https://github.com/cristianst85/gitextensions/commit/3b7ac1988bb49519d06d2fbc9575318709f475c7

**Before:**
![image](https://user-images.githubusercontent.com/12585988/100545248-93567500-3263-11eb-8d46-8e5d2cf53aa8.png)

**After:**
![image](https://user-images.githubusercontent.com/12585988/100545251-981b2900-3263-11eb-96f3-40b3bac40829.png)

**Comment by gerhardol** [comment]
> This issue puzzled me for a while. So far the only solution that I could come up with appears to be to strip control characters from the ConEmu output. But this seems to be a workaround at best.

The encoding is likely not the same for the command and when displaying.
Try changing encoding when assigning in Preview_Click().

**Comment by cristianst85** [comment]
Hi @gerhardol.

I am not sure what you mean by changing the encoding.

The first character is an escape char ([\u001B](http://www.fileformat.info/info/unicode/char/1b/index.htm)) meaning that whole thing is an ANSII escape sequence (see some examples [here](http://ascii-table.com/ansi-escape-sequences.php)). I'm not sure what that sequence exactly does.

I found something similar done in `ExecutableExtensions` class where there is a method called `CleanString` which removes the `stripAnsiEscapeCodes` (but that regex will not work here).

![image](https://user-images.githubusercontent.com/12585988/100943899-ccfada80-3506-11eb-9b46-a190fb403b6c.png)

**Comment by RussKie** [comment]
Given that we're running the command via the ConEmu (if it is enabled), it is probably the ConEmu that is adding the control chars.

**Comment by cristianst85** [comment]
Yeah, I'm not familiar with how ConEmu works. 

Should I submit a PR with my [fix](https://github.com/cristianst85/gitextensions/commit/3b7ac1988bb49519d06d2fbc9575318709f475c7) then? Also, I would refactor it a little bit, like moving the regex to a `private static readonly Regex` variable.

**Comment by pmiossec** [comment]
Doing a PR is always a good idea so that we could discuss around code 😉

**Comment by ivangrek** [comment]
And it is very important not to forget to make a mistake so that there would be something to discuss. 😜

**Comment by RussKie** [comment]
Sure thing! Thank you

**Comment by bansan85** [comment]
I took a look. I don't know if it's ConEmu's fault. Or to be more precise, I don't know what should be the result of ConEmu.

If I add a breakpoint in ``gitextensions\GitUI\UserControls\ConsoleEmulatorOutputControl.cs`` at the function ``public void AnsiStreamChunkReceived(object sender, AnsiStreamChunkEventArgs args)``, the variable ``text`` is:

```
"\u001b]9;11;\"20:28:24.462\"\a\"C:\\Program Files\\Git\\bin\\git.exe\" clean -x -d --dry-run\r\n"
```

After ``FilterOutConsoleCommandLine``, the variable ``filtered`` is:

```
"lean -x -d --dry-run\r\n"
```

I don't know how works ConEmu and I have no idea who is right or wrong. @RussKie : can you tell me if the variable ``text`` has the right content ? Does the problem comes from FilterOutConsoleCommandLine function ? Thanks

**Comment by pmiossec** [comment]
From what I can see, the goal of  `FilterOutConsoleCommandLine` was to remove the command line to get only the output.
The problem is that the method fails to do well its job because there are all the stuff added by ConEmu for each line outputed `\u001b]9;11;\"22:16:19.508\"\a`.

If your remove that, you've got the expected output...

**Comment by pmiossec** [comment]
So the solution is to find the best way to remove this strings or if possible configure ConEmu to not output that...

**Comment by pmiossec** [comment]
Sorry, reading the full thread, I see that you already knew all that 😕

Not sure it will be possible to have a better output from ConEmu so perhaps the only remaining solution is to find the best way to remove these strings in the output....

**Comment by bansan85** [comment]
I'm note absolutely sure it's the right solution but this commit fix the problem.

**Comment by gerhardol** [comment]
PR for main repo still needed
