### ISSUE TITLE
Cannot cherry pick the creation of a file

### ISSUE THREAD

**Issue by kjkrum** [gitextensions/gitextensions#8588]
I'm not even sure if this is supposed to work, or if there's some logical reason it can't.

I've noticed that I cannot cherry pick the creation of a file. In other words, if there's a new file in another branch, I cannot add that file to my uncommitted local changes by cherry picking it. The context menu option is available, and there's no error when it's used, but the file is not created.

If this is not supposed to work, then take this as a suggestion to disable the "cherry pick" context menu item on created files.

Git 2.28.0.windows.1, GitExtensions 3.4.3.9999.

**Comment by mstv** [comment]
As a workaround: Use `Reset file(s) to` | `Second b/hash: description`, please.

**Comment by gerhardol** [comment]
The context menu item should be removed if a file in the status list does not exist, the patching depends on that, so it is not just new files.

For deleted files, it could work if the file exists (as it the change is displayed a patch), but such patches will often fail, so this should be blocked too.
