### ISSUE TITLE
Text in commit section is garbled

### ISSUE THREAD

**Issue by heunghingwan** [gitextensions/gitextensions#8590]
## Current behaviour

Text in author field and child field is not display correctly.

## Expected behaviour
It should be display like upper section in screenshot.

## Steps to reproduce

![image](https://user-images.githubusercontent.com/11424817/97937740-7345aa00-1dba-11eb-96fe-3670b8ddc7c2.png)

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Can you please provide a repro?
