### ISSUE TITLE
Can't find commit with entire hash

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#8591]
## Current behaviour

"Go to commit..." dialog doesn't find a commit when the entire hash is used (works when one char is removed)

## Expected behaviour

The entire hash could be used to find a commit.

## Steps to reproduce

1. Copy hash of a commit
2. Select another commit
3. Ctrl+shift+G (the popup open with the hash already filled)
4. Click "Go" button
5. "No revision found" message box

## Screenshots

![bug_go_to_commit](https://user-images.githubusercontent.com/460196/97973481-6af36c00-1dc6-11eb-89d7-9c1aad98857a.gif)

## Did this work in previous version of GitExtensions

Yes.

## Environment

- Git Extensions 33.33.33
- Build bc261f585a6a67b9b3c2340ff867553ec1fa437e (custom build from ` 0b5ecd2a5fe53fd5b76209e8aea7465a90fa2357` from recent `master` )
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4261.0
- DPI 192dpi (200% scaling)

## Diagnostics

Don't know

**Comment by RussKie** [comment]
I experienced the same today...
