### ISSUE TITLE
Add copy to clipboard with commithash:branch

### ISSUE THREAD

**Issue by purnadika** [gitextensions/gitextensions#8595]
## Feature description
Add to Copy to Clipboard menu, a feature to copy commit hash with its branch. Apparently I need it to cut time with git push for specific commit.
Example result : d4b0f48bbf3e39a71f5d7ff5231be5678d4aa091:production

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
This feels as a very niche requirement. You can use user scripts to achieve
this, but I can't see us implementing this in the app.
