### ISSUE TITLE
[NBug] System.NullReferenceException at Github plugin

### ISSUE THREAD

**Issue by caijingwen-vincent** [gitextensions/gitextensions#8597]
## Error Details
```
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 GitUI.CommandsDialogs.RepoHosting.ForkAndCloneForm._searchResultsLV_SelectedIndexChanged(Object sender, EventArgs e)
   在 System.Windows.Forms.ListView.OnSelectedIndexChanged(EventArgs e)
   在 System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   在 System.Windows.Forms.ListView.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
Hi folks.
Here is the process when I get this error
1. Open github plugin
2. open Tab#Search for repositories
3. click search button
4. double click the search result
![image](https://user-images.githubusercontent.com/71600126/98133379-7c3c9580-1ef8-11eb-811b-7ca82fe087c5.png)

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
Set your GitHub token
