### ISSUE TITLE
Removed branch still selected in push screen as target branch at "Branch to push""

### ISSUE THREAD

**Issue by 1Jesper1** [gitextensions/gitextensions#8598]
## Current behaviour
When I want to push my branch "env/test", the selected target branch is my previous origin branch "env-test", which I have renamed as "env/test", the name was "env-test". The target branch is still env-test, which I have removed locally and remote.

## Expected behaviour
The selected target branch should be "env/test".

## Environment
- GitExtensions version: 3.4.3.9999
- GIT version: 2.28.0
- OS version: Windows 10
- .NET version: 4.8.4

**Comment by pmiossec** [comment]
That's normal because git is still tracking the deleted (or renamed) remote.

You have to enter the good name and then inform git to replace the reference:
![image](https://user-images.githubusercontent.com/460196/98234800-3ec02280-1f61-11eb-89cf-78af631dbbaf.png)
