### ISSUE TITLE
F2 key should open branch rename window from the branch list

### ISSUE THREAD

**Issue by lukasz-pekala** [gitextensions/gitextensions#8599]
## Feature description
F2 key should open branch rename window from the branch list on the left.
Context menu should be updated with text: "Rename (F2)"

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by bcolaco** [comment]
I'd like to give it a go and implement this feature as my first contribution.

**Comment by mstv** [comment]
> I'd like to give it a go and implement this feature as my first contribution.

Welcome! Use the `HotkeySettingsManager`, please, if possible.
And add your data to the file `contributors.txt` - in a separate PR in order to avoid merge conflicts.

**Comment by bcolaco** [comment]
I've completed a [minimal change implementation](https://github.com/gitextensions/gitextensions/compare/master...bcolaco:feature/8599-f2-branch-list) of the feature, but not using `HotkeySettingsManager`.

I'll try to change it now to use `HotkeySettingsManager`, before submitting the PR.

**Comment by RussKie** [comment]
You can raise a draft PR to solicit feedback early. Often this can reduce
unnecessary or unneeded work.
