### ISSUE TITLE
Git/Config: Araxis Merge does not work, Mergetool `Suggest` button suggests nothing

### ISSUE THREAD

**Issue by andry81** [gitextensions/gitextensions#8620]
##  Current behaviour
Araxis Merge does not execute, Mergetool `Suggest` button suggests empty string

## Expected behaviour
For example, for the path:
```
Path to mergetool: "C:/Program Files/Araxis/Araxis Merge/Compare.exe"
```
It might suggest:
```
Mergetool command: -merge -max -wait -a2 -3 "$LOCAL" "$BASE" "$REMOTE" "$MERGED"
```
But suggests an empty string.

If manually input the string, then the mergetool still is not available (does not open).

## Steps to reproduce
Click to `Suggest` button.
Run mergetool from any place, for example, from the `Merge is currently in progress with merge conflicts. [Resolve] [Abort]` list item in the main window opened from the `GitExt Open Repository` Windows Explorer context menu.
Araxis Merge runs as expected if try to run from terminal console.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3468.0
- DPI 96dpi (no scaling)

- Araxis Merge 2017 Professional Edition Version 2017.4929

**Comment by gerhardol** [comment]
Araxis is not supported as a preconfigured tool in 3.4, you will have to manually enter options and path.
(The optins were obsolete in 3.3 and earlier and the options could not be changed inso not really a decl)

Araxis is added as tool with suggestions in next version.

You may have an opinion on how to set options; according to Git or Araxis support site: https://github.com/gitextensions/gitextensions/pull/8454#pullrequestreview-525688172

**Comment by gerhardol** [comment]
Duplicate of #8351

**Comment by andry81** [comment]
But it didn't work even if set the option manually.

**Comment by gerhardol** [comment]
Try the options exactly as in the PR or as in the Araxis suggestion (they differ slightly, you have yet other options).
It obviously worked for the PR creator.

**Comment by andry81** [comment]
Did you mean to replace this:
```
-merge -max -wait -a2 -3 "$LOCAL" "$BASE" "$REMOTE" "$MERGED"
```
By that:
```
/merge /max /wait /a2 /3 "$LOCAL" "$BASE" "$REMOTE" "$MERGED"
```
?

Why if Araxis understands both of it?

**Comment by gerhardol** [comment]
araxis suggests:
`"C:/Program Files/Araxis/Araxis Merge/ConsoleCompare.exe" -3 -a2 -wait "$LOCAL" "$BASE" "$REMOTE" "$MERGED"`
GE
`Compare.exe "/merge /wait /a2 /3 "$LOCAL" "$BASE" "$REMOTE" "$MERGED"`

But I do not have access to Araxis and cannot say what is supported.
It obviously works for other users, so the first is for you to check the parameters, for instance dashes

Try the difftool from the commandline. That must work for the mergetool to work in GE.

**Comment by andry81** [comment]
> It obviously works for other users, so the first is for you to check the parameters, for instance dashes

But I've already checked that, I been wrote it in the first message:

>>If manually input the string, then the *mergetool still is not available* (does not open).

>>Araxis Merge runs as expected if try to run from terminal console.

**Comment by andry81** [comment]
Today I could retest it.
Seems the problem was in the quotes around the path. In a previous version it had the quotes.
