### ISSUE TITLE
Markdown preview in File tree browsing

### ISSUE THREAD

**Issue by C0untZero** [gitextensions/gitextensions#8624]
## Feature description
It would be nice if we could preview .md files when browsing the file tree, like we can currently for image files for instance (ico, png, etc).

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.24.1.windows.2 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
This will require a lot more work than you might expect.
Text/diff is viewed with a native text viewer. That is needed for other purposes too.
Images are viewed with a .NET standard image viewer, so not much extra.

To render .md files a new viewer is needed which will add a new external dependency. There has been discussions about adding a webbrowser component for the build servers tab, that would double the size for the GE binary though.

One workaround is of course to open the file in a viewer.
Another to use VS Code as a diffviewer, then preview there. (Next version allows selecting a diff tool from difftab without changing settings.)

**Comment by vbjay** [comment]
FYI. 

[Markdown Preview Enhanced](https://shd101wyy.github.io/markdown-preview-enhanced/#/)

**Comment by C0untZero** [comment]
> 
> 
> This will require a lot more work than you might expect.
> Text/diff is viewed with a native text viewer. That is needed for other purposes too.
> Images are viewed with a .NET standard image viewer, so not much extra.
> 
> To render .md files a new viewer is needed which will add a new external dependency. There has been discussions about adding a webbrowser component for the build servers tab, that would double the size for the GE binary though.
> 
> One workaround is of course to open the file in a viewer.
> Another to use VS Code as a diffviewer, then preview there. (Next version allows selecting a diff tool from difftab without changing settings.)

I was just looking at it from the point of browsing lets say a fresh repo you just cloned - I am aware that you can easily work around this by simply opening the file in some other viewer, just thought it would be a nice GE built-in feature.

A quick search turns up [this .NET library](https://github.com/lunet-io/markdig) for rendering md - would this be a less intensive size-wise component to insert?

If you think this library would be a good direction/starting point, I would be willing to dedicate some time to taking a crack at this, never actually contributed to open source before.
Any tips/hints on how I could start with GE?

**Comment by C0untZero** [comment]
> A quick search turns up [this .NET library](https://github.com/lunet-io/markdig) for rendering md - would this be a less intensive size-wise component to insert?

Oh, on a closer look this just converts md to html, we'd still need an html render component...

**Comment by gerhardol** [comment]
GE has MD syntax highlighting at least...

@RussKie I recall something about it being easier to add an external dependency like an embedded web browser with .NET5.
Would something like that be accepted, this is an additional dependency?

**Comment by pmiossec** [comment]
> @RussKie I recall something about it being easier to add an external dependency like an embedded web browser with .NET5.

Today announcement :

>Today, we are excited to announce that Microsoft Edge WebView2 is Generally Available for production .NET Framework, .NET Core, and .NET 5 WinForms and WPF production applications!
>https://twitter.com/dotnet/status/1329836630476263426


Concerning markdown preview, I share the @gerhardol point of view that it is a lot of code to write and maintain for very few added value... 

Markdown is already supposed to be easy to read. So why should we include a preview for this format instead of another one which will be surely less readable?

**Comment by vbjay** [comment]
Yep. If you want to see a preview open in vscode and also checkout the
extension I linked earlier.

**Comment by C0untZero** [comment]
Ok, I appreciate that the feature would be a low roi. Thanks for the quick responses :)

Any other low-hanging fruit issues I could tackle to get into contributing for GE?

**Comment by gerhardol** [comment]
> Ok, I appreciate that the feature would be a low roi. Thanks for the quick responses :)

A general viewer could be useful, but the roi is  low

> Any other low-hanging fruit issues I could tackle to get into contributing for GE?

Whatever annoys you and that improves the application...

There is a milestone for next release:
https://github.com/gitextensions/gitextensions/milestone/56
However, the list is not really up to date, features that are ready when RussKie agrees that it is time for a new release is included.
There are also the a little boring tasks to update documentation, review PRs and respond to issues that are always welcome contributions. RussKie wants more tests. Any help is appreciated.

It is about time to make a new release soon, maybe not to be called 4.0. .NET 5 was planned, but there are some open items (mostly related to external packages that are not ready for .NET 5, primarily for themeing). (A reason we are not enthusiastic to add new dependencies...) (There is no ETA for a new release, that usually takes two months, but we have discussed a semi official endorsed downloadable, to get more feedback about changes at an earlier stage.)

**Comment by C0untZero** [comment]
Thanks @gerhardol, I'll take a look.

**Comment by RussKie** [comment]
There are few lingering open discussions that I'd like to have finalised,
but I think we can do a Xmas present to the community in a form of a new
release ;)
