### ISSUE TITLE
Show error message when Reset file fails

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#8632]
## Feature description

Related to #8630 

Due to the missing file, I tryied to reset the file to get it.

Of course, git fails but Git Extensions don't complain.

I suggest that GitModule.CheckoutFiles should return a bool and return the result of ``_gitExecutable.RunBatchCommand``. So caller (like ``RevisionDiffControl.ResetSelectedItemsTo``) should be able to display a MessageBox.

Are you okay before I implement it ?

## Environment

- Git Extensions 33.33.33
- Build 3737099926a138c34433f6cd1de29b5d9580968f
- Git 2.22.0.windows.1 (recommended: 2.28.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
It is quite some situations where GE just swallows Git errors, also more relevant situations than this
You may want to wait a little for #8278 or #8358 that tries to cleanup process/error handling and show popup at more errors.
(If you review the PRs, they will be merged quicker)

Stage: git update-index --remove --stdin
returns
"\r\nIgnoring path drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c\n"

**Comment by bansan85** [comment]
Sure, I will wait :)  thanks for the reply. I will retry when these two pull requests will be merged.
