### ISSUE TITLE
A click on author of the commit opens dozens of Internet Explorer windows

### ISSUE THREAD

**Issue by vrubleg** [gitextensions/gitextensions#8633]
When you click on the [author link](https://veg.by/z/2020-11-24-16-05-44-0903cfb0.png), it shows [an error that mail client is not properly installed](https://veg.by/z/2020-11-24-16-01-34-5f6fb080.png), and then opens [dozens of Internet Explorer windows](https://veg.by/z/2020-11-24-16-02-44-e08ed4bc.png) (it looks so weird because the windows don't have enough time to render themselves, and I'm using RDP).

I would propose to remove this link completely. Try to remember if you ever used it. My bet is that the answer is "never" =) I clicked it accidentally, when I was trying to select part of it. I would prefer to have an ability to select and copy any part of it without any fuss.

Or at least make active the email part only, and fix this weird behavior when email client is not installed.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.4240.0
- DPI 96dpi (no scaling)

**Comment by vrubleg** [comment]
A small update. The bug which opens dozens of IE11 windows is caused by IE11 itself. When I just enter `mailto:me@veg.by` to address bar, it shows the same error and opens dozens of windows.

Anyway, I still propose to remove this link, or at least make it smaller (email part only).

**Comment by ivangrek** [comment]
![image](https://user-images.githubusercontent.com/3169265/100101804-65d88880-2e6b-11eb-9023-cbf5eebf6169.png)

**Comment by vrubleg** [comment]
That's fine, but you may want to copy just part of this string. For example, just email, first name, last name, or both. Actually, it was exactly what I was trying to do. I was trying to copy just email, and accidentally caused this issue with dozens of IE windows.

**Comment by RussKie** [comment]
Please use the context menu as a workaround.
