### ISSUE TITLE
File not found when staging file.

### ISSUE THREAD

**Issue by mikeschurkin** [gitextensions/gitextensions#8635]
I have 3 repo's and none of them will allow me to stage files anymore.  This worked previously, but now every file throws the same error.

I deleted the repo's locally, pulled them down again and it still won't work.

When using the commit window, I can see files that are changed, I can right-click edit the files, there are no special characters in the file names or the directory (no utf8) and the files exist, but as soon as I click on the stage button, I get the same error regardless of the file or repo.  I can, however, commit the files manually without any issues in either the Git GUI or Git Bash.

```
Stage 1 files

error:  Verigift/verigift_delta.sh: does not exist and --remove not passed
fatal: Unable to process path  Verigift/verigift_delta.sh

Done

```
![image](https://user-images.githubusercontent.com/7903191/100117028-c905f300-2e4a-11eb-877e-1c039ad85a47.png)

I'm completely stumped by this one because I can't see anything wrong with the files or paths.  Maybe I'm missing a setting?

**Comment by pmiossec** [comment]
And if you try with the git command line (to verify if the problem come
from git or git extension)?

**Comment by mikeschurkin** [comment]
committing from git extenstions Git bash shell and Git GUI works fine (the GUI is a little more work but does the job just fine).  Committing from windows powershell git works fine too.  It's just when trying to commit from the applications that it always fails.

I reinstalled the app, rebuilt the repos, restarted windows - all the usual things and the issue still persists.

**Comment by mikeschurkin** [comment]
Sorry, just want to clarify - I use the Git tools - Git Bash and Git GUI and both are available as tools in Git Extensions.

I don't believe that they are part of Git Extensions, but they are part of Git and seem to work fine.

**Comment by vbjay** [comment]
Show the git command log entry when attempting to stage.

**Comment by vbjay** [comment]
We also have an issue template for a reason.

**Comment by mikeschurkin** [comment]
Ok, attached is the log file for the event in question.

vbjay - where can I find the issue template?  I just clicked on the Help->Report an Issue in the app and it took me here.

Also, concerning your last comment, I find your attitude wholly unprofessional, especially considering that you are a contributor to this project and I would expect 'helpful' rather than 'condescending and rude'.

[gitextensions.log](https://github.com/gitextensions/gitextensions/files/5598178/gitextensions.log)

**Comment by vbjay** [comment]
Nothing unprofessional. It was a statement to point out that when we raise
an issue, the issue template asks for specific info.

https://github.com/gitextensions/gitextensions/issues/new/choose

**Comment by vbjay** [comment]
This is the bug template. 



## Current behaviour




## Expected behaviour



## Steps to reproduce




## Screenshots





## Did this work in previous version of GitExtensions




## Environment



- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 


## Diagnostics

**Comment by gerhardol** [comment]
What GE version is this?
There were changes in 3.4 related to staging
The log shows that the directory starts with a space.
The filename is quoted though (GitModule.cs:1888 UpdateIndex())

**Comment by StefanoSega** [comment]
Have the same identical issue

**Comment by mstv** [comment]
@StefanoSega and @mikeschurkin, could you provide information about your environment and the git command log (hit `F12`), please?
Can you still reproduce it with the current development build?
https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts

**Comment by gmellor** [comment]
I just fixed this exact problem for a colleague by updating git-for-windows. Seems like an incompatibility between latest git-extensions and an old git.
