### ISSUE TITLE
Main menu items permuted randomly

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8636]
## Current behaviour

AppVeyor build of master:

![grafik](https://user-images.githubusercontent.com/36601201/100158806-0c914900-2ead-11eb-82c7-d6a237c9b085.png)

AppVeyor build of PR:

![grafik](https://user-images.githubusercontent.com/36601201/100158870-26329080-2ead-11eb-9ea1-2fb6f1aac004.png)

Older local build:

![grafik](https://user-images.githubusercontent.com/36601201/100159112-74e02a80-2ead-11eb-89b3-1a5a724097a0.png)

Older local build restarted:

![grafik](https://user-images.githubusercontent.com/36601201/100159573-49aa0b00-2eae-11eb-8137-bd068138cf3b.png)

## Expected behaviour

at least no random

## Did this work in previous version of GitExtensions

Yes, I guess with my own local release build before the "older local build". I don't have access to the PC running the latter ATM.

**Comment by gerhardol** [comment]
Same for me, the order for the last menus are seemingly random since some weeks(?)

Related?
The toolbars are occasionally lost when starting GE on the work PC

**Comment by RussKie** [comment]
Hidden toolbars would be related to my changes of making toolbars hidable.
Noticed on canary versions, I think it may be related to changes in hashes
for canary builds....

**Comment by mstv** [comment]
It gets scrambled on close. If you start multiple instances, they have the same sequence of items. (That's why I haven't noticed it before.)

**Comment by ivangrek** [comment]
💡  Generate a menu from a declarative description. This would be the first step towards being able to configure the order and composition of menu items.

**Comment by RussKie** [comment]
It appears this line is messing things up:
https://github.com/gitextensions/gitextensions/blob/5bbc8023b002b57aff3897913ef1bc68146b39c4/GitUI/CommandsDialogs/FormBrowse.cs#L619

![image](https://user-images.githubusercontent.com/4403806/102206374-99fe1100-3f20-11eb-872b-f56e8215d291.png)
