### ISSUE TITLE
Integration with Bitbucket.org

### ISSUE THREAD

**Issue by twastvedt** [gitextensions/gitextensions#8663]
## Feature description

Integration with Bitbucket.org. 

The Bitbucket plugin works for Bitbucket Server but not for Bitbucket.org. It would be great to have the same pull request integration with Bitbucket.org repos.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.20.1.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
bitbucket.org has a completely different API compared to bitbucket server (only the name is the same).
If done, it should be implemented as a separate plugin, maintained by bitbucket.org users.
(bitbucket server could be separated from GE core too.)

**Comment by RussKie** [comment]
Create a plugin using https://github.com/gitextensions/gitextensions.plugintemplate. 
There are few examples: https://github.com/search?q=topic%3Agitextensions-plugin+org%3Agitextensions&type=Repositories
