### ISSUE TITLE
D&D to commit graph change current tab to TreeTabPage

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#8669]
## Current behaviour

It's possible to D&D selected text from the diffViewer to the "commit graph" viewer.

After drop, current tab becomes TreeTab instead of the current tab: DiffViewer.

## Expected behaviour

I should not be able to drop text to the commit graph viewer.

When drop to commit graph, it should not change current tab.

## Steps to reproduce

Open Git Extensions
Open a repository
Click on a commit in the commit graph viewer.
Click on Diff tab
Select some text in the diff viewer
Drag this text and drop it to the commit graph viewer

## Screenshots

Not necessary

## Did this work in previous version of GitExtensions

I don't think so.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.22.0.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

## Diagnostics

1. I think it should not be possible to drop to commit graph.
2. About the change of the current tab to Tree Tab Page : I think it's in the file ``gitextensions\GitUI\CommandsDialogs\FormBrowse.cs`` and the function ``private void FormBrowse_DragDrop(object sender, DragEventArgs e)``. In this function, there is a hardcoded default tab: ``CommitInfoTabControl.SelectedTab = TreeTabPage;``. The code is executed at every drop on the commit graph even if the TreeTabPage is not visible.

**Comment by gerhardol** [comment]
I believe the D&D is intended to open files in the fileviewer, for instance with files from the explorer.
So everything is being evaluated as files.

This may seem confusing, but how to handle drag&drop, what should it do?

**Comment by bansan85** [comment]
I tried to use the D&D. I don't really understand what its purpose.

In discussion #4861, it says "if you drag and drop from the file tree in one instance of GitExtensions into the file tree of another instance of GitExtensions, it throws this…" . I tried it and I can't drop. The only time I can successfully D&D is when I drag a followed file from Explorer and I drop it to the commit graph.

Is there other way to use the D&D in commit graph (or more general way, in the main form) ?

**Comment by pmiossec** [comment]
I use it successfully from the Visual Studio "Solution Explorer" to be able after to see a file history or blame (except since [a recent update of Visual Studio that delete the file when you drag it](https://developercommunity.visualstudio.com/content/problem/1156139/database-project-dragging-a-file-from-solution-exp.html) now 😤)

So I like this feature (even if I admit that it could be tweaked a little to prevent some side effects) because it allows to easily select a file from an external editor or the file explorer...

The goal is to select a file that's why the D&D display the "File tree".

**Comment by gerhardol** [comment]
There should probably be a status message (tooltip?) when a file cannot be found (and found?)

**Comment by pmiossec** [comment]
@bansan85 Can you test #8678 ?
