### ISSUE TITLE
(Misconfigured) Build server integration exhausts ports

### ISSUE THREAD

**Issue by VsevolodGolovanov** [gitextensions/gitextensions#8676]
## Current behaviour

I have TeamCity build server integration configured globally:
![image](https://user-images.githubusercontent.com/8070317/102097961-9fcbf780-3e37-11eb-8d07-18f8205ab749.png)
It's relevant to most of my repositories. But not all. Sometimes I work on a repository, that doesn't correspond to this TeamCity project. That's where problems can start after a few hours of GitExt running: browser shows a white page when trying to navigate, IDEA says that it can't open a port for debugger...
When this happens, there are always these messages in the Windows System Event Log:
![image](https://user-images.githubusercontent.com/8070317/102098603-7a8bb900-3e38-11eb-8e8c-91bea96c72d5.png)
![image](https://user-images.githubusercontent.com/8070317/102098625-7f506d00-3e38-11eb-9526-6c8d01a4ae03.png)
Eventually GitExtensions silently crashes/closes itself.

## Expected behaviour

This shouldn't happen, even if build server integration is misconfigured. GitExt should handle erroneous states better, maybe throttle its requests after a while. 

## Steps to reproduce

Have TeamCity integration configured with a wrong project, and then let Git Extensions sit there for hours.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Are you able to debug this?
No one in the core team uses TeamCity. There has not been any feature contributions to TeamCity for four years.

**Comment by VsevolodGolovanov** [comment]
Not really...

**Comment by matyasbach** [comment]
It's probably the same as #8281. Hopefully should be fixed by #8716.

**Comment by matyasbach** [comment]
@VsevolodGolovanov could you please test it with this version? https://ci.appveyor.com/api/buildjobs/i3wbpdfrenmh0g7w/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-4.0.0.10723-a1fb6669d.zip

**Comment by VsevolodGolovanov** [comment]
@matyasbach, used it for two days without issues.

**Comment by pmiossec** [comment]
I think we can consider it closed. Please ask for reopen if needed
