### ISSUE TITLE
Jira Commit Hint NullReferenceException

### ISSUE THREAD

**Issue by nikki603** [gitextensions/gitextensions#8677]
## Current behaviour

Looks like the same error as https://github.com/gitextensions/gitextensions/issues/8122 but it still happens for me with latest GitExtensions version.

Jira Commit Hints fails to return list of issues in commit window. Instead it returns stacktrace:

![image](https://user-images.githubusercontent.com/5578773/102116566-274f4180-3e0b-11eb-892e-3c8a33e2b67a.png)

## Expected behaviour

No exception

## Steps to reproduce

Settings -> Plugin -> Jira Commit Hint. Click the Preview button.

JQL Query: assignee = currentUser() AND status in ("Code Review", "In Progress", "In Test", "In progress", "In test") AND text ~ "\"[test]\"" ORDER BY updatedDate DESC

## Did this work in previous version of GitExtensions

Never tried it before

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.27.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

## Diagnostics

Backend API responses to GET /rest/api/2/field and POST /rest/api/2/search can be provided on request.

**Comment by gerhardol** [comment]
I can query in master (do not believe this is changed).
The query string must be changed though, no double double-quotes (and no brackets). Not sure how to quote this.

The actual exception is in the Atlassian internals, outside GE implementation, maybe needed to get this fixed there.

**Comment by pmiossec** [comment]
Maybe a jira too old or too recent and api is different.
It would be interesting if you could both provide the jira version...

**Comment by nikki603** [comment]
We use Jira Cloud which apparently is always "latest"

**Comment by nikki603** [comment]
I have tried simplifying the JQL query to either nothing or `assignee = currentUser()` but I still get the same error.

**Comment by gerhardol** [comment]
Since you are an Atlassian customer, can you query what version of the Atlassian SDK that is required?

GE uses 12.1.1, 12.3 is the latest but do not mention anything about incompatibility
It could of course be due to the way that the CommitHint plugin connects to Jira cloud, but the SDK should not make an exception without any details.

Maybe an issue must be opened toAtlassian too.

**Comment by slavapr** [comment]
Hey guys,
Same error.
![image](https://user-images.githubusercontent.com/4169617/150497739-1ab2774a-55d9-4c1d-9819-0483d3bb82e8.png)

As I see current release  Atlassian.SDK version is 12.1.1, but latest is 12.4.0
![image](https://user-images.githubusercontent.com/4169617/150501368-2adf874d-50f8-4b2d-9797-eb0c68eda500.png)



- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Jira Commit Hint plugin is removed in 4.0, see #9659 
This issue is therefore closed as not applicable, link from #9659
