### ISSUE TITLE
Avatars in blame viewer are misaligned

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#8684]
## Current behaviour

When blaming a file with view avatars enabled, avatars are misaligned with lines of code.

## Expected behaviour

Should be aligned.

## Steps to reproduce

Make sure you enabled the feature to show avatar when blaming.
Blame a file with lots of lines and lots of modifications (here: `GitExtensions` repo, commit: `67f5fd9197ef5055c778510aecd6ece29cff8fe4`, file: `GitExtensions.sln` )
Go to the end of the file
Avatars are misaligned with lines of code.

## Screenshots

![image](https://user-images.githubusercontent.com/9248729/102467832-1132c280-4051-11eb-9d5e-ddb8d6ca752c.png)

## Did this work in previous version of GitExtensions

No idea.

## Environment

- Git Extensions 33.33.33
- Build 30b8505c8991c5a9e3c06016c34f9d501c6d856e
- Git 2.22.0.windows.1 (recommended: 2.28.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

## Diagnostics

None

**Comment by bansan85** [comment]
I found the problem comes from :

```
diff --git a/GitUI/Editor/BlameAuthorMargin.cs b/GitUI/Editor/BlameAuthorMargin.cs
index 5baa14392..3f64e6d16 100644
--- a/GitUI/Editor/BlameAuthorMargin.cs
+++ b/GitUI/Editor/BlameAuthorMargin.cs
@@ -37,7 +37,7 @@ private static int GetFontHeight(Font font)
                 TextRenderer.MeasureText("_", font).Height,
                 (int)Math.Ceiling(font.GetHeight()));
 
-            return max + 1;
+            return max;
         }
 
         public void Initialize(IEnumerable<GitBlameEntry> blameLines)
```

So removing the +1 do the trick. But I think it's too easy… This +1 must have been added on purpose.

Does this feature works well on your computer ?

**Comment by pmiossec** [comment]
>Does this feature works well on your computer ?

yes

![image](https://user-images.githubusercontent.com/460196/102469529-26105580-4053-11eb-8f33-ce5f970cd1ce.png)

This part of the code try to find the height of the lines in the diff view to display avatars to the same size.
I'm really not an expert in how display works but I imagine that's dpi scaling, dpi and other things could have an impact on the displayed line height explaining the difference.

Environment:

- Git Extensions 33.33.33
- Build f5362ec637de01d40be55f5d0abfbbc7b6e9d828
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4261.0
- DPI 192dpi (200% scaling)

**Comment by bansan85** [comment]
I made some tests with differents dpi. The good formula is hard to deduce :


DPI | 96 (100%) | 120 (125%) | 144 (150%) | 168 (175%) | 192 (200%)
-- | -- | -- | -- | -- | --
MeasureText | 17 | 20 | 23 | 28 | 32
GetHeight | 15,61 | 19,51 | 23,41 | 27,32 | 31,22
Good value : | 17 | 21 | 25 | 28 | 33
So… | max | max+1 | max+1 | max | max+1

So you can see that sometime you need +1, sometime not :/

Can you please check with dpi 96 (100%) and 168 (175%) if you have a problem ?

**Comment by bansan85** [comment]
Polite ping,
Could you try with different DPI and check if you have the same result that me ? (Good : 125%, 150%, 200%, Bad : 100%, 175%)
Thanks,

At the time, I have no idea how the height of the line are calculated. It's just to check if it's just me or not.

**Comment by ivangrek** [comment]
I have reproduced.

![image](https://user-images.githubusercontent.com/3169265/109419811-f7f6ac80-79d7-11eb-95e6-2d1a1ee910aa.png)

**Comment by mstv** [comment]
`TextView.GetFontHeight` and `BlameAuthorMargin.GetFontHeight` are implemented identically.
Though `BlameAuthorMargin` should rather get access to `TextView.FontHeight`.
Perhaps DPI scaling is applied differently to drawn text than to bitmaps.

**Comment by bansan85** [comment]
Found the bug. The font is different in TextView and BlameAuthorMargin.
