### ISSUE TITLE
Git status with untracked files triggered on certains forms, kills usability with big worktree; Add option to disable it.

### ISSUE THREAD

**Issue by michkot** [gitextensions/gitextensions#8685]
Rebase and Reflog form IsDirtyDir
https://github.com/gitextensions/gitextensions/blob/5347a7d2898eea6b4ff51a674c0b935122aea52a/GitUI/CommandsDialogs/FormRebase.cs#L120-L151
https://github.com/gitextensions/gitextensions/blob/fde9a6ef8a314a122b8453509a530a16f3955317/GitUI/CommandsDialogs/FormReflog.cs#L52-L55

Checkout dialog has it (for long time) conditional on a settings button:
https://github.com/gitextensions/gitextensions/blob/fde9a6ef8a314a122b8453509a530a16f3955317/GitUI/CommandsDialogs/FormCheckoutBranch.cs#L109-L115

IsDirtyDir executes git status --show-untracked=all
https://github.com/gitextensions/gitextensions/blob/5347a7d2898eea6b4ff51a674c0b935122aea52a/GitCommands/Git/GitModule.cs#L2770-L2773
which kill performance on huge worktrees

I think it would be reasonable to do the same for rebase/reflog forms (add a settings button controlling whether the check for untracked files is necessary). Or maybe it is not necessary to check for untracked-files  in reflog/rebase at all? I think it is reasonable for rebase, since files that are not tracked now might get tracked during the rebase and lost. Reflog is not (much) more dangerous then regular branch switching. 

Note: Git commit dialog does not check untracked files if you have config status.showUntrackedFiles=no since https://github.com/gitextensions/gitextensions/pull/3151 in 2017.

Note 2: I have identified one more case (specifically for v2) of unexpected untracked files enumeration:
https://github.com/gitextensions/gitextensions/blob/v2.51.05/GitUI/AutoCompletion/CommitAutoCompleteProvider.cs#L34

**Comment by RussKie** [comment]
Thank you for the investigation and the report.
Do you have a fix in mind?

**Comment by michkot** [comment]
I am still interested in this and now I actually might have a fix in mind.
Also, I just found out that with recent GfW 2.32, with useBuiltinFSMonitor (+ maybe untrackedCache), there is a huge perf. difference between --show-untracked=all and --show-untracked=normal. "Normal" evaluates orders of magnitude faster! 
For a really big repo I have here, its 5s normal, 0.3 with fsmonitor and -unormal, 0.16 with fsmonitor and -uno, and 9s with fsmonitor and -uall (Yes, fsmonitor and -uall is 2x as worse then vanilla configuration).

Since IsDirtyDir is only concerned with "any untracked changes", there shouldn't be a need to enumerate all files (see links bellow) in the first place, so at least adjusting that from "all" to "normal" would make a huge impact in use-cases like mine.

normal x all:
https://git-scm.com/docs/git-config#Documentation/git-config.txt-statusshowUntrackedFiles
https://git-scm.com/docs/git-status#Documentation/git-status.txt---untracked-filesltmodegt

**Comment by TaoK** [comment]
Related thread on the git mailing list, exploring where/why FS Monitors currently actually make performance with `--show-untracked=all` *worse*, by triggering a single-threaded path enumeration specific to untracked files (as opposed to the multi-threaded one used for all change detection in the absence of an FS Monitor):
* https://lore.kernel.org/git/CAPMMpohJicVeCaKsPvommYbGEH-D1V02TTMaiVTV8ux+9z9vkQ@mail.gmail.com/
* https://lore.kernel.org/git/CAPMMpog7bNNPm3suZKu6OppHA+KDYgCfmaxW4HqTAr7_tTVAPQ@mail.gmail.com/

Unfortunately, this discussion seems to be meeting little interest from the git dev community, so far at least. 

This class of performance issue *appears* to be tied to the number and/or depth of folders in the working tree.

**Comment by TaoK** [comment]
After having spent a bit of time looking at the git source code around this, I have to provide a warning here: 

Depending on *how* the `--untracked-files=all` performance issue eventually gets fixed in git, there may eventually end up being  high cost on *switching* between `--untracked-files=all` and the default `--untracked-files=normal` across different executions, because the way the untracked file cache is persisted may end up depending on the options used - and therefore running again with different options may result in the previous run's persisted cache being invalid/unusable.
