### ISSUE TITLE
[NBug] Die Eingabezeichenfolge hat das falsche Format.

### ISSUE THREAD

**Issue by florianhetz** [gitextensions/gitextensions#8686]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei GitUI.Editor.Diff.DiffLineNumAnalyzer.Analyze(String diffContent)
   bei GitUI.Editor.Diff.DiffViewerLineNumberControl.DisplayLineNumFor(String diff)
   bei GitUI.Editor.FileViewerInternal.SetText(String text, Action openWithDifftool, Boolean isDiff)
   bei GitUI.Editor.FileViewer.<>c__DisplayClass103_0.<ViewPatchAsync>b__0()
   bei GitUI.Editor.FileViewer.ShowOrDeferAsync(Int64 contentLength, Func`1 showFunc)
   bei GitUI.Editor.FileViewer.<ViewPatchAsync>d__103.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.T

**Comment by florianhetz** [comment]
System.FormatException: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   bei System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   bei GitUI.Editor.Diff.DiffLineNumAnalyzer.Analyze(String diffContent)
   bei GitUI.Editor.Diff.DiffViewerLineNumberControl.DisplayLineNumFor(String diff)
   bei GitUI.Editor.FileViewerInternal.SetText(String text, Action openWithDifftool, Boolean isDiff)
   bei GitUI.Editor.FileViewer.<>c__DisplayClass103_0.<ViewPatchAsync>b__0()
   bei GitUI.Editor.FileViewer.ShowOrDeferAsync(Int64 contentLength, Func`1 showFunc)
   bei GitUI.Editor.FileViewer.<ViewPatchAsync>d__103.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.T

**Comment by gerhardol** [comment]
To be able to do anything with an issue like this, a detailed description must be added
If this is caused in the same as #8634, it was fixed in #8661

Duplicate of #7146
