### ISSUE TITLE
Incorrect borders when app run in >100% scaling factor

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8698]
## Current behaviour

https://github.com/gitextensions/gitextensions/pull/8557 introduced new margins and borders, however those margins and borders are not correctly calculated in scaled environments, i.e. scale factor >100%.
For example:
* 100%
![image](https://user-images.githubusercontent.com/3169265/101113313-cabc7d00-35e7-11eb-8d76-a33e45215dca.png)

* 200%
![image](https://user-images.githubusercontent.com/460196/103076153-6597ee00-45cd-11eb-8af6-d92edb9d6f55.png)

## Environment

- Git Extensions 33.33.33
- Build f5362ec637de01d40be55f5d0abfbbc7b6e9d828
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4261.0
- DPI 192dpi (200% scaling)

**Comment by ivangrek** [comment]
If I delete this line, it works as it should.
Will it be right?

`this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);`

**Comment by RussKie** [comment]
If it works...

**Comment by pmiossec** [comment]
Tested. It indeed fix the boders width. But a lot of forms have the same value....

**Comment by RussKie** [comment]
I tried a blanket removal of `this.AutoScaleDimensions = new System.Drawing.SizeF(x, y)`, and it doesn't appear to be a safe change. Some dialogs become totally unusable (e.g. `FormCreateWorktree`).
There has to be another way, investigating.

**Comment by RussKie** [comment]
There's definitely something in our code that scales paddings 4(!) times: 1 -> 2 -> 3 -> 4 -> 6.
```cs
this.MainSplitContainer.Panel1.ResumeLayout(false); // 1 -> 2px
...
this.MainSplitContainer.ResumeLayout(false); // 2 -> 3px
...
this.toolPanel.ResumeLayout(false); // 3 -> 4px
...
this.ResumeLayout(false); // 4 -> 6px
```

I have created a brand new app, copied the `FormBrowse` designer file (removing or renaming non Windows Forms controls), and observed only a single padding scaling: 1 -> 2px at `this.ResumeLayout(false);` call.

**Comment by ivangrek** [comment]
> There's definitely something in our code that scales paddings 4(!) times: 1 -> 2 -> 3 -> 4 -> 6.

It is interesting!

**Comment by ivangrek** [comment]
Most likely, it will turn out through the base class to draw border like for textbox.

![image](https://user-images.githubusercontent.com/3169265/103478851-238f5900-4dd2-11eb-8dd8-b3d62c6e338c.png)

![image](https://user-images.githubusercontent.com/3169265/103478894-749f4d00-4dd2-11eb-819f-4c441a1548ac.png)

But for #8712, the panels are not merged into one element from the GitExtensionsControl in the marked places.
