### ISSUE TITLE
Improve PR template for multiple screenshots

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8710]
## Feature description

PRs with multiple screenshots like #8700 would benefit from a table layout for `Before` / `After`.
Prepare a side by side display in the PR template, please.

## Environment

GH

**Comment by gerhardol** [comment]
Does GitHub have any specific support here or do you just want to change the instructions (and headings) in the template?

**Comment by vbjay** [comment]
GitHub supports pipe tables
https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/organizing-information-with-tables

**Comment by RussKie** [comment]
For the most part this would be a manual exercise for the author, e.g. all the tables in [this PR](https://github.com/dotnet/winforms/pull/3461) are formatted manually. I don't know if updating the template would be generally useful.

**Comment by RussKie** [comment]
@mstv is there anything you have in mind on how this can be actioned further?

**Comment by mstv** [comment]
We could have changed the Screenshots section to something like
```
| Before | After |
---------|--------
|        |       |
```
But it is not fun using it...
We know now how to do it if multiple screenshots must be compared, and can add the table manually.

**Comment by mstv** [comment]
OK, the outer pipes `|` can be omitted. Each pair of screenshots must be on the same line. But GH does not use the full width of the browser window.
```
Before|After
------|-----
b|a
```

**Comment by gerhardol** [comment]
> But it is not fun using it...
> We know now how to do it if multiple screenshots must be compared, and can add the table manually.

I suggest to add it as a comment in the template

**Comment by vbjay** [comment]
It's not hard. It also doesn't have to be aligned.  The pipes just have to
be there.

```
|Before|After|
|:-:|:-:|
|Img1|img2|

```

Will still work.
