### ISSUE TITLE
No padding for maximized window

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8711]
## Current behaviour

#8557 has added padding around all controls of FormBrowse. So the maximized window looks like it was resizeable and it does not use the full screen.

## Expected behaviour

No padding if the window is maximized.

**Comment by RussKie** [comment]
Can you please provide screenshots?

**Comment by ivangrek** [comment]
What padings are you talking about?

**Comment by mstv** [comment]
Looks like the window borders added by former Windows versions, which could be dragged for resizing.
This makes me think, the window was not maximized because the controls of maximized applications use the full client area. Perhaps there are some exotic applications. but GE shouldn't be one of them.

![current FormBrowse](https://user-images.githubusercontent.com/36601201/103467264-ad491300-4d4d-11eb-8137-c3c28c3c6194.png)
(I know that this window is not maximized. It looks the same.)

**Comment by ivangrek** [comment]
Like VS, SSMS and many other Win Forms application.

![image](https://user-images.githubusercontent.com/3169265/103467988-63682900-4d5d-11eb-8a40-eaaba36ce1cc.png)

I also suggest moving the tabs to the bottom to eliminate the void in the center.

![image](https://user-images.githubusercontent.com/3169265/103468033-d96c9000-4d5d-11eb-9259-054aea48cfc3.png)

**Comment by RussKie** [comment]
I wouldn't flip, it becomes an accessibility issue - these tabs are high
traffic elements that would require significantly more mouse move,
especially on hdpi monitors.

**Comment by mstv** [comment]
VS is special. It adds space between the client area and the "side tabs" and the status bar.
But it has no space below the status bar as VS Code, as the Windows Explorer, etc.

![VS](https://user-images.githubusercontent.com/36601201/103487019-6b2dd900-4e02-11eb-9411-61c67ea9696e.png) ![VSC](https://user-images.githubusercontent.com/36601201/103487236-2c008780-4e04-11eb-953b-faecf82c2a82.png)

**Comment by ivangrek** [comment]
> But it has no space below the status bar as VS Code, as the Windows Explorer, etc.

I agree.
We don't have that either.

Indentation uniquely identifies work areas. And this design only emphasizes this.

If you notice, VC uses a different way of highlighting work areas with color, with indents inside the colored area. There are also zero margins between panels. All this rests on the complexity of easily changing the design of elements.

If you have any other idea about the desired design, please provide an example.

![image](https://user-images.githubusercontent.com/3169265/103488025-3c1f6380-4e12-11eb-9013-63263a8d7171.png)

We either expand the boundaries between the panels, or collapse to zero.

I suggest using a clear and tested UX / UI. Going to a design similar to VC with the current framework on the brink of the impossible.

**Comment by mstv** [comment]
![Explorer](https://user-images.githubusercontent.com/36601201/103488595-345dc000-4e0e-11eb-824c-205d80c7bdea.png)

Keep the space beetween the panels (green arrows) but no additional space at the window borders, i.e. where the three red arrows point to in my GE screenshot above.

**Comment by ivangrek** [comment]
It is one canvas with zero padding between the borders of the panels.
Could you mark the borders between the panels in the picture? (GE)

**Comment by ivangrek** [comment]
FormCommit has no borders. What's wrong there?

**Comment by mstv** [comment]
I'd prefer the window like this:
![FormBrowse mock-up](https://user-images.githubusercontent.com/36601201/103489645-44799d80-4e16-11eb-8c39-df6a346275d3.png)

> FormCommit has no borders. What's wrong there?

refer to #8712

**Comment by ivangrek** [comment]
How it looks with shading.
![1](https://user-images.githubusercontent.com/3169265/103489779-77745f00-4e1f-11eb-8233-bf0d605538a9.png)

**Comment by ivangrek** [comment]
Initial version of changes.

![](https://user-images.githubusercontent.com/3169265/96534071-b3c00680-1297-11eb-8027-6728fdedb59f.png)

**Comment by ivangrek** [comment]
Here's another markup without indentation, but also achievable with complications.

![image](https://user-images.githubusercontent.com/3169265/103489876-5d874c00-4e20-11eb-8abd-047880e6f3d9.png)

**Comment by mstv** [comment]
My complaint is only against the frame at the window border which consumes space for nothing.

**Comment by ivangrek** [comment]
In these cases, it looks ambiguous. One part is glued in, the other part is hanging in space.

![image](https://user-images.githubusercontent.com/3169265/103490152-90324400-4e22-11eb-912b-42d14716f628.png)

![image](https://user-images.githubusercontent.com/3169265/103490147-8ad4f980-4e22-11eb-8923-b8474c41c500.png)

**Comment by mstv** [comment]
Don't think of panels. It is controls with splitters inbetween.

**Comment by ivangrek** [comment]
In this case, the separator should be a simple line. 

I propose to use the style that is used in VS and consider this a transitional stage to a better UI. I am only suggesting an approach that is tried and tested and understood.

**Comment by mdonatas** [comment]
At some point GE used to look similar to this. At least to me nothing in terms of padding seems out of place.

![image](https://user-images.githubusercontent.com/483659/107401742-d78bae80-6b0b-11eb-8c8b-8ce9b0d828a7.png)

Adding a background color solves the "floating in the air" + "attached to one side but not the other" problems.

**Comment by ivangrek** [comment]
https://github.com/gitextensions/gitextensions/issues/8711#issuecomment-774443835

**Comment by RussKie** [comment]
My 20c - I _do_ like the new main window layout, to me personally it feels significantly more modern and closer to the current UI/UX paradigms of Windows and Office than the current borderless/marginless layout.

**Comment by mdonatas** [comment]
Which part? I didn't notice floating islands in either Excel, Word, Terminal, Windows Explorer or Settings.

**Comment by RussKie** [comment]
> p.s. Windows settings UI is abomination and should never be referenced in any positive context 😅

HAHAHAHA! I was about to post screenshots

**Comment by RussKie** [comment]
https://github.com/gitextensions/gitextensions/issues/8711#issuecomment-753540367

**Comment by mdonatas** [comment]
In none of these there's any wasted space around the window. It could be that there is a button close to a side of a window which has large padding inside but you can still interact with it by hovering an empty area. Look at my VS example, I can cherry pick examples too 😅 but seriously though, in VS you get islands because those controls are dockable or have tabs. Outside of VS shell I can't really find other examples of high profile apps having main areas of the app floating without some 'connection' to the encompassing window.

To be clear, I accept that you like it, it's just that I found a problem with this statement `current UI/UX paradigms of Windows and Office`. Because statements like this tend to lend weight to whatever is proposed and since I don't like it I don't want to lend any weight to this idea without actual evidence ;]

![image](https://user-images.githubusercontent.com/483659/108211474-65335380-7135-11eb-9823-97f8efddb158.png)

**Comment by ivangrek** [comment]
And so we are ahead. 🚀

**Comment by mdonatas** [comment]
@ivangrek in https://github.com/gitextensions/gitextensions/issues/8711#issuecomment-753540367 you said `Like VS, SSMS and many other Win Forms application.` Could you show a few of those "_many other_ Win Forms application"?

**Comment by ivangrek** [comment]
> Could you show a few of those "many other Win Forms application"?

The kind that I use now LinqPad. But I think it doesn't matter since you are talking about details.

https://github.com/gitextensions/gitextensions/issues/8711#issuecomment-753682615
https://github.com/gitextensions/gitextensions/pull/8849#issuecomment-778615825

**Comment by ivangrek** [comment]
#6183 

@mdonatas, I propose to select a couple of dialogues and bring them to one form. This will speed up the approach of the new UI.

**Comment by RussKie** [comment]
Outlook uses margins and paddings quite extensively, though they are presented in a slightly different manner:
![image](https://user-images.githubusercontent.com/4403806/108309861-7c8e4180-7206-11eb-9f2c-5876a70d634a.png)

**Comment by RussKie** [comment]
LinqPad:
![image](https://user-images.githubusercontent.com/4403806/108310606-c0ce1180-7207-11eb-936e-5547eddc54e4.png)

**Comment by RussKie** [comment]
NuGet Package Explorer
![image](https://user-images.githubusercontent.com/4403806/108310671-de02e000-7207-11eb-8a58-910f433cc19f.png)

**Comment by gerhardol** [comment]
What is effective looks good to me. So I find borders and paddings ugly and margins should be kept to a minimum.
(The border between panels must be wide enough so the splitter can be moved.)

**Comment by mdonatas** [comment]
Outlook looks good 👍 their use of margins/padding is sensible, good example of how to use them!

As for LINQPad.. as much as I admire Joe Albahari for his dev skills (and I use LINQPad daily too) I don't think there are two edges with the same margin/padding width in this application 🤣
NuGet Package Explorer was developed by devs for devs without (and it's just a guess) any help from UX people.
My point is that when trying to justify "floating" islands with non functional margins like shown here https://github.com/gitextensions/gitextensions/issues/8711#issuecomment-753536939 one needs to look at low profile apps which no matter how functional probably have not seen enough UX attention.

**Comment by RussKie** [comment]
I also checked SQL Server management studio - it has prominent margins/padding. VS Code too for that matter has margins and inner paddings between panes. Being an electron app, it makes it easier to create layouts.

But I do get the point. We're all perceive good/bad UI through the lens of UI we use every day, and with that we have different views on what a good/usable/preferred UI is. Because I use VS, Outlook, and GitHub day-in/day-out my perception and preference for spacing is different from someone who uses Word or a web browser most of the time.

There's also an element of "information density" - VS, Outlook, GE all present significant amount of information to a user, and IMO extra spacing makes it easier to concentrate on specific areas, reduces distractions, also defines categories and gives logical meaning to the user's mental processes.

And, yes, I'd love to get a professional UX designer opinions and help - if you know someone please let me know.

**Comment by ivangrek** [comment]
Strongly said. 👍

**Comment by mdonatas** [comment]
I appreciate a good burn, I took it with a smile and `:not-bad:` reaction :)

I wonder if there is a misunderstanding somewhere here though, so here's a clarification
1. Padding/margins **between** the panes is good (when done like it's done in VS Code or previous GE versions)
2. I love how VS Code does it and how it looks
3. And finally I only dislike the margins next to window sides which serve no purpose. VS Code has absolutely `0` of these. And this is exactly what I am trying to convey: https://github.com/gitextensions/gitextensions/issues/8711#issuecomment-753681601

Amazing look and use (or lack thereof) of margins:
![image](https://user-images.githubusercontent.com/483659/108536789-833fb600-72e5-11eb-9f41-3c5f65c8d556.png)

in contrast..
![image](https://user-images.githubusercontent.com/483659/108538348-5e4c4280-72e7-11eb-9316-a36162bd0ff1.png)

p.s. in my last comment on UX attention I absolutely didn't mean GE, sorry if this seemed implied
p.s.s. Even SSMS has something useful on at the bottom of the window and for floaty controls - you can actually grab and move/dock them which justifies the "island" UX to probably make it more apparent/discoverable.

**Comment by ivangrek** [comment]
I love the design of VS Code. If you are ready to implement it in all dialogues, I'm all for it.
It feels like you are not hearing the main point.

**Comment by gerhardol** [comment]
@ivangrek It is good that you have a vision and are putting in work in following the vision, that is often better than going nowhere.
But I will still (mildly) object to more margins, but keep going.

**Comment by RussKie** [comment]
I have a crazy (?) idea, hear me out.

What if we don't use borders (through the use of paddings and background colour of containing controls), but add a single border to the splitters - on the left to the vertical splitters, and on the top to the horizontal ones?
We do get to keep paddings too.

Something like:
![image](https://user-images.githubusercontent.com/4403806/109405097-ef46ac00-79c0-11eb-8ef4-391b11799b19.png)

**Comment by pmiossec** [comment]
> I have a crazy (?) idea, hear me out.

That's the one I think of when all the borders were removed some months ago so it's not that crazy 🤣 

So I can live with that. We just have to do it well so that it plays well with "Commit info left of graph" and  "Commit info right of graph" options...

**Comment by ivangrek** [comment]
> I have a crazy (?) idea, hear me out.
>
> What if we don't use borders (through the use of paddings and background colour of containing controls), but add a single border to the splitters - on the left to the vertical splitters, and on the top to the horizontal ones?
We do get to keep paddings too.

Seems like you are starting to understand me. 😉 👍 

***
Мне ни к чему одические рати
И прелесть элегических затей.
По мне, в стихах все быть должно некстати,
Не так, как у людей.

Когда б вы знали, из какого сора
Растут стихи, не ведая стыда,
Как желтый одуванчик у забора,
Как лопухи и лебеда.

Сердитый окрик, дегтя запах свежий,
Таинственная плесень на стене...
И стих уже звучит, задорен, нежен,
На радость вам и мне.

***

I have no use for odic legions,
Or for the charm of elegiac play
For me, all verse should be off kilter
Not the usual way.

If only you knew what trash gives rise
To verse, without a tinge of shame,
Like bright dandelions by a fence,
Like burdock and like cocklebur.

An angry shout, the bracing smell of tar,
Mysterious mildew on the wall…
And out comes a poem, light-hearted, tender,
To your delight and mine.

**Comment by mdonatas** [comment]
This latest screenshot looks nice until one notices that on the left, right and bottom there is non-functional/dead space for (at least to me) no clear reason. If there is a vote, I vote to give this space to content.. but it feels like decision has been made to waste space, good thing this is OSS and anyone can revert this in personal builds :)
