### ISSUE TITLE
Missing borders in FormCommit

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8712]
## Current behaviour

#8557 has added borders to FormBrowse. This affected FormCommit, too, which is lacking borders now.

## Expected behaviour

At least add bottom borders to the list of unstaged files and to the patch view.

## Screenshots

![current FormCommit](https://user-images.githubusercontent.com/36601201/103445559-1b220b80-4c76-11eb-9b2a-42eff02fcee5.png)

## Did this work in previous version of GitExtensions

![former FormCommit](https://user-images.githubusercontent.com/36601201/103445516-42c4a400-4c75-11eb-83f1-e1dee6dc7a5e.png)

## Environment

- Git Extensions 33.33.33
- Build 468d7955a25faad218e16268ba2a56b07da5508c
- Git 2.27.0.windows.1 (recommended: 2.28.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by ivangrek** [comment]
Endless possibilities. 😉

**Comment by mstv** [comment]
I had expected something like this:

![FormCommit mock-up](https://user-images.githubusercontent.com/36601201/103489809-53148480-4e17-11eb-9c68-f9e22e1befa3.png)

or with border at the top

![FormCommit mock-up 2](https://user-images.githubusercontent.com/36601201/103489842-a7b7ff80-4e17-11eb-98ac-e565afab696e.png)
