### ISSUE TITLE
Reflects state of each submodule in the left panel

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8714]
## Current behaviour

![image](https://user-images.githubusercontent.com/4403806/103450799-6d633b00-4d0f-11eb-9279-b1fbfccc416d.png)

## Expected behaviour

The submodules information in the left panel reflects the state of each submodule, and allow the perform the same set of operations on each submodule as available in the `FormCommit`

**Comment by gerhardol** [comment]
Operations missing are Stash, Reset, Commit
![image](https://user-images.githubusercontent.com/6248932/103455107-5100d780-4cea-11eb-86b7-27bcd988d447.png)

Dirty, if ahead/behind is shown in the left panel
![image](https://user-images.githubusercontent.com/6248932/103455120-7261c380-4cea-11eb-8fb6-a3d2e0e8375a.png)

The number of ahead/behind is not shown. Extra calculations would be required.
If the current submodule is not the topmodule, the status for superprojects and siblings is only updated when opening.
Note though that the status is not always completely correct for submodules, git-status only runs for the current submodule. 
So more details means more details that may be out of sync.

Will look into #8703 for opening with selections
In addition to FormCommit/RevDiff worktree menu additions there could be a summary popup, similar to what is shown in the diff viewer.
Rightclick to open in new instance or add _Open in Git Extensions_ in addition to open

**Comment by RussKie** [comment]
> The number of ahead/behind is not shown. Extra calculations would be required.

We calculate the same in the `FormCommit`, so shouldn't be a big issue here if this call is async.

**Comment by RussKie** [comment]
Thinking out loud - maybe fetching and reporting status should be incapsulated into each instance of submodule? E.g. when we create an instance of a submodule it starts its own timer and/or filewatcher to check for changes?

**Comment by gerhardol** [comment]
> Thinking out loud - maybe fetching and reporting status should be incapsulated into each instance of submodule? E.g. when we create an instance of a submodule it starts its own timer and/or filewatcher to check for changes?

The current implementation prunes the status calculation. If no changes there are obviously no recursion (and not a problem here). As git-diff provides info if a submodule is only changed itself (GitItemStatus.IsChanged is set) so no submodule specific query is needed right now unless the submodule is dirty too.
For me, just knowing if submodule commit is changed and/or submodule dirty is generally sufficient, not the number of steps.
Ahead/behind is retrieved and shown as a separate step though, see my screenshot.

If the current module is not the top module, another GitStatusMonitor is needed, both FileSystemWatcher and git-status, as it is the git-status that really filters if there are any changes. (The detection of ignored changes required more memory/cpu in some situations than to run git-status a little more often.) Still, git-status may use up to 1/3 of the CPU time for one core right now (large repos with viruses like Symantec). Normally, the load also when running at max frequency is hardly noticeable. A filter with knowledge about .gitignore would be a solution to run git-status less frequently. I am still not fond of running git-status more often and complicate the handling again. There is maybe some other way to visualize that the tree outside current module may be out of date?

So adding stash/reset/commit actions are obvious changes without drawbacks.
To always see more details in the tree is not so important to me. I would like to be able to see the detailed status though. Maybe just starting to evaluate the detail submodule status when hovering the submodule and display a tooltip is what I want.

I would also like to open with details like #8703. That will require the detailed status too so add that to Open alternative will slow down. Another menu alternative is probably the the way to go, to open a new instance. (I will be OK with rightclick on Open, it will be hard to discover this though.)

**Comment by gerhardol** [comment]
I have done an implementation, pushed to branch feature/browse-submodules-2
Depends on #8703 (first part may be applied there instead).

There are some limitations. As details are not evaluated if dirty only, there is no tool tip if dirty only.
Dirty-only flags are cleared when the tree is refreshed (similar to above), so a Reset/Stash/Commit may not update the status in the tree. (Some of that may be tunable.)
But I suggest to leave it at this.

#8658 gets even more annoying with this change...

![image](https://user-images.githubusercontent.com/6248932/103568238-81509d80-4ec5-11eb-8e8d-52c2afacb565.png)

![image](https://user-images.githubusercontent.com/6248932/103568276-90cfe680-4ec5-11eb-9d0e-eae00ef9cead.png)

**Comment by RussKie** [comment]
> ![image](https://user-images.githubusercontent.com/6248932/103568276-90cfe680-4ec5-11eb-9d0e-eae00ef9cead.png)

The tooltip formatting is pretty wild. We can't seem to get it right :\

**Comment by gerhardol** [comment]
> The tooltip formatting is pretty wild. We can't seem to get it right :\

This is the info I want, same as in the diff viewer (except that max 5 files are listed)
What info do you want to see?

**Comment by RussKie** [comment]
I meant the indentation.

**Comment by gerhardol** [comment]
Do you want to change the format in the diff viewer too?
