### ISSUE TITLE
Add support for encoding attribute in .gitattributes

### ISSUE THREAD

**Issue by cezariuszmarek** [gitextensions/gitextensions#8717]
## Feature description

The .gitattributes file supports the "encoding" attribute to specify the file encoding that should be used by GUI tools:
https://git-scm.com/docs/gitattributes#_viewing_files_in_gui_tools

I have a repository with files having various encoding (for example windows-1250 and uft-8), so it would be very useful if Git Extensions could display them correctly without constant manual switching.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Some doc on how to query these information : https://git-scm.com/docs/git-check-attr#_examples

**Comment by gerhardol** [comment]
GE queries the Git repo for the encoding right now, if not set the default is set in settings.

The .gitattributes files are not parsed directly, the rules to parse the raw files are not somethng that should be implemented (there are enough issues with git-config already).
Git commands will require some delay before displaying, using commands pmiossec linked to.
This could maybe be configurable, but there are quite some configurations already.

![image](https://user-images.githubusercontent.com/6248932/103469221-3bc78f80-4d62-11eb-928b-75f6904a5342.png)
