### ISSUE TITLE
[NBug] Could not find a part of the path 'C:\cygdrive\d\Projects.N...

### ISSUE THREAD

**Issue by MavAlpha** [gitextensions/gitextensions#8722]
## Current behaviour

I checked out a branch worktree but got the following error when i tried to check in changes

## Expected behaviour

The changes are checked in without errors

## Steps to reproduce

Check out a branch using the worktree to function to check it out in a different folder to the master working directory

## Error Details
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\cygdrive\d\Projects.NET\Latest\Windows Services\Core\Tensor.SchedulingService\.git\worktrees\Tensor.SchedulingService\GitExtensions.amend'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at System.IO.File.Delete(String path)
   at System.IO.Abstractions.FileWrapper.Delete(String path)
   at GitCommands.CommitMessageManager.set_AmendState(Boolean value)
   at GitUI.CommandsDialogs.FormCommit.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

## Additional information
This happened while trying to check in changes in a branch checked out using a worktree that is not the same as master branch. I am using a cygwin environment and gitextentions looks to be adding a root drive of 'c:' to the beginning of the worktree path

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
It seems like you have used a Cygwin version of Git for the Git repo, which will not work for any non Cygwin applications.
Use Git for Windows also in Cygwin to handle the Cygwin quirks there instead (that is what I use myself).

**Comment by MavAlpha** [comment]
Thank you - changing to Git for windows fixed the problems
