### ISSUE TITLE
Use C# 7/8/9 features

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#8728]
## Feature description

The source code should use new C3 features (where possible, some features requires .NET5 etc)
Changes should be globally applied to reduce noise.

### https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-7
* [x] is null (>700 occurrences)
Allows static analysis and avoids issues overriding assignment: https://intellitect.com/check-for-null-not-null/

### https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-8
* [x] Using declarations, to reduce nesting (About 150 occurrences)
* [x] Null-coalescing assignment (about 21 occurrences)

### https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9
Requires `Directory.Build.props` update first:
```
<LangVersion>9</LangVersion>
```
* [x] is not null (about 900 occurrences)
* [ ] Pattern matching enhancements (other than is not null) (about 70 occurrences) #8738

## Environment

- Git Extensions 33.33.33
- Build c0cf25be75a1c69942508118f625c41126f6b005
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by drewnoakes** [comment]
I'd add to this list: Annotate code for nullability.

**Comment by gerhardol** [comment]
> I'd add to this list: Annotate code for nullability.

Can this be done in a bulk change somehow?
Replace ReSharper annotations?

**Comment by vbjay** [comment]
Regex find and replace in all cs files.

**Comment by drewnoakes** [comment]
> Can this be done in a bulk change somehow?
> Replace ReSharper annotations?

It would be a good place to start, however I would not advise trying to annotate everything in bulk. I have tried this before on a few occasions and it gets too confusing. The C# NRT language feature is more strict than the R# feature, and will generate plenty of warnings.

**Comment by drewnoakes** [comment]
I annotated the `GitCommands` project.

> there will be a number of bugs uncovered that will lead to changes.

Agreed. Also it highlights places where the logic is non-obvious or overly permissive of null values (which happens a lot in GE). I've fixed a few simple bugs, but mostly wanted to capture the current state of null values.
