### ISSUE TITLE
Handle Git exit status and error streams

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#8735]
## Feature description

Many Git commands in GE currently ignores the Git process error status (except for caching) as well as merging the error and standard outputs by using GetOutputAsync(), GetOutputLinesAsync() and similar.
There are a few situations where the merged output is parsed for "fatal" to get the status (GitModule.IsGitErrorMessage())
Obviously trying to parse the output when Git exits with errors (and the output is likely "fatal error") will not work as expected.

This handling should be replaced with Execute() instead and check for errors. (RunCommandAsync() and similar are OK too.)
Example of an OK command is RevParse() (many commands using Execute()/ExecuteAsync() uses AllOutput, which is not quite correct).
Changes need to be done Git command by command, in many situations forwarding the exit codes to callers, so this is not a a simple change.

## Environment

- Git Extensions 33.33.33
- Build c0cf25be75a1c69942508118f625c41126f6b005
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
related to #6527

**Comment by gerhardol** [comment]
I was looking for a previous issue but missed this. 
Anyway, some extra info in this description...

**Comment by gerhardol** [comment]
Duplicate of #6527
