### ISSUE TITLE
Branch search selects wrong branch when a later branch that starts with its name exists

### ISSUE THREAD

**Issue by loop-evgeny** [gitextensions/gitextensions#8742]
## Current behaviour

When I create two branches where one's name is a prefix of the other's and try to select the shorter branch name the other branch gets selected.

## Expected behaviour

The correct branch gets selected.

## Steps to reproduce

1. Create a branch named "testing-with-this-quite-a-long-branch-name" from some commit.
2. Create a branch named "testing-with-this-quite-a-long-branch-name2" from a later commit.
3. In the branch search box (above the treeview) type or paste "testing-with-this-quite-a-long-branch-name".
4. Press down to select "testing-with-this-quite-a-long-branch-name" in the dropdown (not "testing-with-this-quite-a-long-branch-name2") and press Enter.
5. Observe that the "testing-with-this-quite-a-long-branch-name2" branch is selected instead.

## Screenshots

![image](https://user-images.githubusercontent.com/34301024/104163183-43d49e80-53f6-11eb-981d-b143fbf3f92c.png)

## Did this work in previous version of GitExtensions

Don't know.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.7.3701.0
- DPI 120dpi (125% scaling)

**Comment by loop-evgeny** [comment]
While testing this I also ran into a situation where GE would no longer select any branch at all when Enter was pressed in the search box until I left-clicked on a branch in the TreeView. This happened several times, but I cannot repro it since restarting GE.

**Comment by RussKie** [comment]
Are you able to debug it?

**Comment by AmTrJ** [comment]
Hi Im a new contributor here and I tried to reproduce the issue. The tree appeared sorted and search selection was happening as expected. I tried in Git Extensions 3.5.0.11713.

**Comment by AmTrJ** [comment]
Hi Im a new contributor here. I was able to reproduce this issue and like to work on it

**Comment by RussKie** [comment]
@AmTrJ awesome! Holler if you get stuck

**Comment by AmTrJ** [comment]
@RussKie I have been through the code and the following is happening:
-All tree nodes having the search text in them are pushed to a list.
-Later the first element in the list is taken out and focussed.
Possible fix:
-Push the node having the same exact text to the first of the list.
Since I'm new to the solution, I needed to check if this would impact any existing behaviour of the tree.

**Comment by gerhardol** [comment]
What if the name matches a partial name like feature/name, feature/name2 and name is typed?

A strategy could also be to sort the list in matches and sort with priority. This can be very complicated though, like:
* full match
* full match without remote
* full match after last / with locals bere remotes
* full match in a middle section (or remote)
* partial full match
* etc

**Comment by AmTrJ** [comment]
Based on your inputs , I'm thinking to watch the elements getting added to the list and the set the more prior elements at first of the list.
Priority checks:
1. Full match
2. If the tree path or node text has '/' in them, split it with '/' and observe the position of the matching text from end. If its more toward the end, prioritize them and add to front.
3. Partial full match
Should the partial full matches be again prioritised in strings having '/'? 
Please share your views on the same.

**Comment by gerhardol** [comment]
What about remotes?

Just checking for a full match may be sufficient, do not make this complex.
Maybe rules like below is ok
* Full match
* ends with
* starts with
* contains
 
The rules you state may be good enough, but beware that RussKie will request test cases.

**Comment by AmTrJ** [comment]
All tree nodes including the remote nodes are checked against the full path/text. 
Checks are in the following order:
- Full Match
- ends with
- contains
For the starts with case, like for example 'feature/name', search text is 'feature', the node with feature folder will be selected.
 So we don't need an extra check for starts with.
I have done the implementation and it works for the scenarios mentioned.

**Comment by loop-evgeny** [comment]
Was this ever fixed? PR #8742 got closed without being merged.

**Comment by RussKie** [comment]
Probably not...
But since no one has bothered to submit a fix, it's not an issue worth
keeping open.

A fix (if one required) is welcome.
