### ISSUE TITLE
Splitter positions are not restored correctly

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8745]
## Current behaviour

The splitter positions of FormBrowse are not re/stored correctly. At least the CommitInfo panel is shrinked by 8 pixels if displayed beside the RevisionGrid.

## Expected behaviour

CommitInfo width is restored - all splitter positions of course.

## Steps to reproduce

- position CommitInfo beside RevisionGrid
- restart GE

## Did this work in previous version of GitExtensions

yes, before borders were added

## Environment

- Git Extensions 33.33.33
- Build d2830009cd34a660040c66e49a68e7717cd3b2d4
- Git 2.27.0.windows.1 (recommended: 2.28.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by ivangrek** [comment]
In the current version, this also doesn't work for me.

**Comment by gerhardol** [comment]
There has been related issues (in FormCommit?) maybe a year ago with similar behavior. (have not searched).

**Comment by ivangrek** [comment]
Saving/restoring the splitter position is implemented incorrectly, which leads to breakdown of tests.
The restoration of the position should take place on Form_Show event, and not before that.

Splitter position is work incorrectly. Splitters affect the position of each other in sequential recovery.

From # 8849, where this ability is disabled.

**Comment by RussKie** [comment]
> on Form_Show event

We should use `override OnShow(...)` to reduce unnecessary allocations. There's also `Application.Idle` event. 🤔

**Comment by mstv** [comment]
We should mention in the release notes of v3.5 that this has been broken by force in #8849!

**Comment by yegor-mialyk** [comment]
#8072
