### ISSUE TITLE
Cannot type 'r', 's' and 'u' characters in the GE editor

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#8752]
## Current behaviour

When using the built-in GE text editor, I cannot type `r`, `s` and `u` characters.

## Expected behaviour

It should be possible to type all characters :-)

## Steps to reproduce

Make sure GE is configured to use the internal text editor.
Start an interactive rebase with a `reword` action, wait until the editor comes up and try to type `r`, `s` or `u`.

## Did this work in previous version of GitExtensions

Yes, in `08d5ac7e8fd598dc1767bf7ad20c5c43e4a865e5`.

## Environment

- Git Extensions 33.33.33
- Build 7a2a9d54898bc7fdb05cfaa711a56898b4fa4441
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
You are at the cutting edge 😉 
The regression is from the last PR merged: #7825 (37ac05373dc223b5ffdbd05d8db989d66b5e3db8) /cc @gerhardol

**Comment by mstv** [comment]
Sorry, I did not notice your self-assignment and I knew what to do.
