### ISSUE TITLE
GE hangs when switching to an SVN repo with the SVN plugin installed

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#8758]
## Current behaviour

* Installed GitExtensions on a new machine
* Copied my previous settings over - note: previous install has no extra plugins installed other than the ones which ship with GE by default
* Installed the SVN plugin. The Plugin Manager closed GE for the install.
* Reopened GE.
* Went to Plugins -> SVN to be (correctly) greeted with
    ![image](https://user-images.githubusercontent.com/663378/104817329-e0e16e00-5820-11eb-96d9-e7044fe604e5.png)
* Switched to a repo with SVN only for the application to hang indefinitely (Not Responding).
* Hard closed the application.

After manually removing the `Users\Name\AppData\Local\GitExtensions\UserPlugins\GitExtensions.SVN` folder + removing the package from the `Users\Name\AppData\Local\GitExtensions\UserPlugins\packages.config` file, GE starts up again as normal to the repo I was switching to without any delay.

## Expected behaviour

That the application doesn't hang.

## Steps to reproduce

See above and I have been able to consistently reproduce it by installing the SVN plugin again as I forgot to take a screenshot the first time round ;-)

## Did this work in previous version of GitExtensions

No idea as I never installed the extension before.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0

**Comment by gerhardol** [comment]
Handled in a separate repo:
https://github.com/mast-eu/GitExtensions.SVN

**Comment by jrfnl** [comment]
@gerhardol Thanks for pointing me to the correct repo. Moved the issue there now: https://github.com/mast-eu/GitExtensions.SVN/issues/14
