### ISSUE TITLE
[Bug] Doesn't recognize destination directory during "Push to Url"

### ISSUE THREAD

**Issue by yshalya** [gitextensions/gitextensions#8782]
## Current behaviour

Currently it is not possible to push to the local repository (see screenshot below)

## Steps to reproduce

1. Press "Push" button on the toolbar
2. Select Url on the local disk for pushing repository
3. **Unexpectedly, there is no “Browse” button to select a directory.**
4. Press "Push" button on the form

### Error detected: "Please select a destination directory"

__See screenshot below for details__

## Screenshots
![img-2021-01-21-16-13-39](https://user-images.githubusercontent.com/64989305/105358758-a3595800-5c07-11eb-9e41-fc6b3d9b5515.png)

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.2
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.6.1055.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Please include the screenshots directly in the issue.

**Comment by yshalya** [comment]
Sorry, attached screenshot

**Comment by pmiossec** [comment]
I don't know if you are only interested by a fix or also by a workaround...

but you could add a remote defined on this folder and push to this remote (that way you bypass the GitExtensions control of this form)

**Comment by vbjay** [comment]
Correct. The goal was for remotes to manage that. Adding a remote and
hitting browse in the remote management screen. Adding a browse button to
rte push dialog is a great first bug item.

**Comment by yshalya** [comment]
Thanks a lot of everyone, your advices helped me.
I close the issue.
