### ISSUE TITLE
When I stage a file by double click, the commit window just closed, the main window restored

### ISSUE THREAD

**Issue by asmwarrior** [gitextensions/gitextensions#8783]
## Current behaviour
1, Open the commit window, double click on a file to stage it.
2, the commit window just disappeared, and the main window is restored.
3, I have to use mouse to click on the main window, after that, the commit windows is restored.

## Expected behaviour
1, Open the commit window, double click on a file to stage it.
2, the commit window should stay in front of the main window.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.4110.0
- DPI 96dpi (no scaling)

**Note this happens in an old PC running Win7-64bit, for a newer PC running Win7-64bit, I don't have such issue.**

**Comment by mstv** [comment]
This can happen occasionally if GE is too slow processing the git data (not only in the Commit window), especially in combination with high CPU usage by other processes.
Then Windows considers the application unresponsive and pushes the foreground window to the background - a really annoying feature. In addition, the Windows Taskbar items of multiple running GE instances are reordered.

**Comment by asmwarrior** [comment]
Thanks for the reply, so can this issue be fixed? Thanks.

**Comment by RussKie** [comment]
There is a very small number of users like yourself who still runs on W7. So this isn't something worth fixing, sorry.

**Comment by asmwarrior** [comment]
Is this issue only related to Windows 7?

**Comment by mstv** [comment]
> Is this issue only related to Windows 7?

IMO this is an issue between GE and Windows (Win10, too). GE tries to execute many operations in the background but some are done in the UI thread (part of them must be there, others could be optimized). If there are many changes in the repo and / or there is high CPU load, Windows considers the application unresponsive and pushes the foreground window to the background.
The quick fix would be turn off this Windows "feature" (I do not know of a regarding switch). Of course, GE should try to prepare as much as possible in the background and update the UI quickly. I guess this will be a long term challenge. Contributions are welcome.

**Comment by asmwarrior** [comment]
I am not a C# programmer, but my guess is that when the commit window hangs, the OS will send draw background event, and the default way is just draw the parent windows content. When the commit window wake up, it then draw the correct background and forground.

Can we make a simple test case? I can program in C++ with wxWidgets.

**Comment by RussKie** [comment]
Are you referring to this issue https://github.com/gitextensions/gitextensions/issues/6220?

**Comment by asmwarrior** [comment]
Note exactly the same steps, I have not switched to other applications when I operate on the "Commit window".
But the the final result is the same, I mean the "Main GitExtension window" will pop out as the "Foreground/Top Level window", I have to use the left mouse click on anywhere of the "Main GitExtension window", so that the "Commit window" will restored.

I don't think this is related to Windows 7 system.

I just try to use a CPU-burner to manually 'simulate the high CPU usage", this issue often happens when the CPU usage is high.

But I still think this is an issue of GitExtension, because I never see other Windows application which do those auto/magic windows foreground/background switch.

I have followed the way mentioned in #6220 , that I have disabled the ConEmu option, but this issue still happens.

**Comment by asmwarrior** [comment]
Some more information: when this issue happens, I see the title bar of  the "Commit window" has changed, this is done by the OS, it adds "Not Responding" in the title bar, after that, the "Main GitExtension window" jumps out as the Topleve/Foregound window.
