### ISSUE TITLE
Two folders in AppData/Roaming

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#8784]
## Current behaviour

At the moment a installations creates two folders in the AppData folder.

Is this a desired behavior?

![image](https://user-images.githubusercontent.com/7715216/105577076-9e1b1b00-5d77-11eb-8983-4bb5d9f9efcc.png)

## Expected behaviour

Just one folder

## Steps to reproduce

Install GE in Windows 10

## Screenshots

see in current behavior

## Did this work in previous version of GitExtensions

No I don't think

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
That's not normal.

Perhaps you could have a look if one contains the plug-in manager and that
could explain why it is no more loaded...

**Comment by thimmy687** [comment]
This one is empty

![image](https://user-images.githubusercontent.com/7715216/105579221-76cb4a80-5d85-11eb-9db0-e1d71956759d.png)

and this contains the settings

![image](https://user-images.githubusercontent.com/7715216/105579235-8ba7de00-5d85-11eb-8e8e-cae7a9928219.png)

It looks like this change is effecting (trying to solve) this #7972

![image](https://user-images.githubusercontent.com/7715216/105579334-33bda700-5d86-11eb-9987-7a5eeaec9762.png)

it seems that this is not in use consequently like here

![image](https://user-images.githubusercontent.com/7715216/105579385-8a2ae580-5d86-11eb-8a4a-39b5bfac52db.png)

**Comment by gerhardol** [comment]
The name was consistently changed to _Git Extensions_.
To preserve settings the path compatibility was changed.
However, Windows creates the path earlier.

**Comment by cc11112** [comment]
it seems create a version folder under AppData\Roaming\Git Extensions\Git Extensions now.

**Comment by cc11112** [comment]
![image](https://user-images.githubusercontent.com/896987/195388352-9051554c-b339-4343-91c7-bbd27923cf15.png)

**Comment by mstv** [comment]
> it seems create a version folder under AppData\Roaming\Git Extensions\Git Extensions now.

It is empty (as stated above). Just ignore it, please.
The settings are stored in the folder without spaces in the path as in earlier versions.
