### ISSUE TITLE
Dark theme visually corrupt after dpi change

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8798]
## Current behaviour

If the app is configured to use a custom theme (e.g. the dark), and there is a user changes preferences that include dpi scaling (e.g. 100%->150%, 200%->150%) certain pars of the app become rendered incorrectly, e.g.

| Current | Expected |
|---|---|
| ![image](https://user-images.githubusercontent.com/4403806/92439177-ac640280-f1ed-11ea-899e-da81fb878509.png) | ![image](https://user-images.githubusercontent.com/4403806/105651837-0864c480-5f0c-11eb-8c6c-c3afb162ddeb.png) |

Related: https://github.com/gitextensions/gitextensions/pull/7213#issuecomment-688719768

## Expected behaviour

Currently the only way to resolve the issue is to restart the app. Which in some circumstances could be rather destructive to the current user flow (e.g. being in a middle of debug session, with various diff opened), and should be avoided, if possible.

It could be possible to react to [`SystemEvents.UserPreferenceChanged`](https://docs.microsoft.com/dotnet/api/microsoft.win32.systemevents.userpreferencechanged) and update theming hooks.
However the event must be handled with an utmost care to avoid deadlocking the app (e.g. ["Debugging Windows Forms Application Hangs During SystemEvents.UserPreferenceChanged"](https://docs.microsoft.com/en-us/archive/blogs/dsui_team/debugging-windows-forms-application-hangs-during-systemevents-userpreferencechanged) and [".NET 4.0 and the dreaded OnUserPreferenceChanged Hang"](https://stackoverflow.com/q/4077822/2338036).

## Steps to reproduce

1. Configure the app to use a custom theme, e.g. the dark.
2. (In multi monitor setup) Move the app to the monitor that will have its scale factor changed
2. Change the current scale factor (e.g. 100%->150%) while running the app
3. Observe various visual artifacts

## Environment

- GitExtensions version: 3.4.3 and the current master

**Comment by RussKie** [comment]
I have a draft prototype:
```diff
diff --git a/GitExtensions/Program.cs b/GitExtensions/Program.cs
index 31839ada7..fa5777350 100644
--- a/GitExtensions/Program.cs
+++ b/GitExtensions/Program.cs
@@ -13,8 +13,8 @@
 using GitUI.Theming;
 using JetBrains.Annotations;
 using Microsoft.VisualStudio.Threading;
+using Microsoft.Win32;
 using Microsoft.WindowsAPICodePack.Dialogs;
-using ResourceManager;
 
 namespace GitExtensions
 {
@@ -45,6 +45,18 @@ private static void Main()
             ThemeModule.Load();
             Application.ApplicationExit += (s, e) => ThemeModule.Unload();
 
+            SystemEvents.UserPreferenceChanged += (s, e) =>
+            {
+                ThemeModule.Unload();
+                ThemeModule.Load();
+
+                foreach (Form form in Application.OpenForms)
+                {
+                    form.BeginInvoke((MethodInvoker)(() => form.Invalidate()));
+                }
+            };
+
             HighDpiMouseCursors.Enable();
 ```

This seems to generally work, though a bit more tweaking and testing is required.

**Comment by NikolayXHD** [comment]
Oh, that's elegant, I didn't realize the change can be that small

**Comment by RussKie** [comment]
This still needs to be distilled further - there are multiple events fired with different `e.Category` values. I guess we care about a specific one; yet to look deeper.
