### ISSUE TITLE
ConEmu always crashed on ext.displays connected/disconnected

### ISSUE THREAD

**Issue by QuAzI** [gitextensions/gitextensions#8803]
Always when I connect or disconnect external displays to my notebook I have this crash
![image](https://user-images.githubusercontent.com/1897605/105815052-63a5be00-5fc3-11eb-8503-7ca0e8099c41.png)

Version: 3.4.3
OS: Win10 Pro 20.04

**Comment by RussKie** [comment]
This looks like an issue with https://github.com/Maximus5/conemu-inside.
/cc: @Maximus5

**Comment by Maximus5** [comment]
Version of ConEmu is half a year old.

**Comment by pmiossec** [comment]
@Maximus5 Yes, we release less often that you ;)

We have updated Conemu in #8768 but we still need to release.

That's why we would like to know if you know this bug and if it is fixed?

**Comment by RussKie** [comment]
@QuAzI please grab the latest dev build and test https://ci.appveyor.com/project/gitextensions/gitextensions/branch/master/artifacts
Let us know if you still having troubles, and we'll re-open the issue.

**Comment by QuAzI** [comment]
Now I can't even run console, DrWeb blocks it
![image](https://user-images.githubusercontent.com/1897605/106157902-38be9400-6194-11eb-9997-9ad9e1462274.png)
and
![image](https://user-images.githubusercontent.com/1897605/106157973-496f0a00-6194-11eb-99bb-2bab92ddbd48.png)

**Comment by Maximus5** [comment]
@QuAzI You need to report false positive to DrWeb authors. Only they may "fix" that.

**Comment by QuAzI** [comment]
Blocking happens only with console. DrWeb scan doesn't show any criminal in zip. Looks strange. I have many years expirience with DrWeb and I am sure if you have troubles with him - you will have troubles with other AV.
But I will try to ask them

**Comment by vbjay** [comment]
https://www.av-comparatives.org/comparison/

**Comment by QuAzI** [comment]
They [said](https://forum.drweb.com/index.php?showtopic=334172)
```
Disabe Inject ConEmuHK (C:\Program Files\ConEmu\ConEmu\ConEmuHk.dll) in settings of ConEmu
```

**Comment by QuAzI** [comment]
@vbjay there is no sense to change one of the best AV

**Comment by vbjay** [comment]
Where are the independent tests proving it's the best?

**Comment by QuAzI** [comment]
@vbjay 1) ONE of
2) I have good experience with a lot of them since first AV's for DOS and still think that DrWeb is nice.
3) It is NOT solution of the problem
Of course if you want just holy war - you can install all from your link. But it still senseless

**Comment by pmiossec** [comment]
@vbjay I think this is how the human nature is.
Once we invest time, money or decision making in a tool, it becomes the best solution of the world... 

We all agree here that GitExtensions is best git GUI, no? 😁

**Comment by vbjay** [comment]
Lol. Amen.

**Comment by RussKie** [comment]
I've witnessed the same issue on my colleagues corp-managed workstation yesterday, and we don't use 3rd party AV. So the problem is obviously not the DrWeb 
 AV.



> They [said](https://forum.drweb.com/index.php?showtopic=334172)
> 
> ```
> Disabe Inject ConEmuHK (C:\Program Files\ConEmu\ConEmu\ConEmuHk.dll) in settings of ConEmu
> ```

@Maximus5 any thoughts on this?

**Comment by Maximus5** [comment]
@RussKie You can not witness "the same issue" as the issue is with DrWeb and you say you have not installed it.
So, you have to explicitly describe you issue first.

**Comment by Maximus5** [comment]
> Disabe Inject ConEmuHK (C:\Program Files\ConEmu\ConEmu\ConEmuHk.dll) in settings of ConEmu

This allows to bypass not so good heuristics of DrWeb. As well, it disables a lot of features provided by ConEmu.

**Comment by RussKie** [comment]
I observed exactly the same error message as the OP.

**Comment by QuAzI** [comment]
I can google a lot of problems with ConEmu for other AV's. But it still senseless. I know about a lot of troubles with obfuscators and some other tools. But it is still not reason to change AV and still not solve main bug.
GitExtension not need so extraordinary functionality and injection to system files. DrWeb doesn't beat old versions. AND DrWeb even doesn't beat new version of ConEmu. I've just put it on c:\Program Files (x86)\GitExtensions\ConEmu and now all works fine. GitExtensions 3.4.3 + ConEmu from fresh build. But without fresh ConEmu.WinForms.dll and others.

And I think in old version it was just wrong assert (which should be removed in release or check not only DPI but displays count). In assert window you can choose 'Abort' and console breaks.

**Comment by Maximus5** [comment]
If you read the thread, you could see that issue of the topic starter is already solved! Old version is used on the screenshot.
And the issue has nothing in common with any AV software.
I would appreciate to not blame ConEmu for things it does not.
