### ISSUE TITLE
Changes to SSIS Package not being recognised

### ISSUE THREAD

**Issue by Darth-Da** [gitextensions/gitextensions#8816]
I have one SSIS package in a project that GIT Extensions is not recognising changes to. I've tried removing all entries from Git Ignore, deleting and adding the package again but still doesn't recognise when a change has been made. All other SSIS packages in the same project are being tracked correctly.

The path for the SSIS package is  /DataVault/ETL/DataVaultLoad.dtsx

Below are the entries from Git Ignore:

/DataVault/.vs/*
/DataVault/Database/bin/*
*.jfm
/DataVault/Database/Database.sqlproj.user
/DataVault/Database/obj/*
/DataVault/ETL/obj/*
/DataVault/ETL/bin/*
/DataVault/Database/Database.dbmdl
/DataVault/ETL/VaultETL.dtproj.user
/Assemblies/DataVault/obj/*
/Assemblies/DataVault/bin/*
/Assemblies/TestingConsole/bin/*
/Assemblies/TestingConsole/obj/*
/Assemblies/.vs/Assemblies/v14/*

Git Version:
![image](https://user-images.githubusercontent.com/78478733/106737574-beb46200-660e-11eb-913d-dc19c174441e.png)

Any ideas?

Cheers

**Comment by Darth-Da** [comment]
Have managed to find a way round this by deleting the entire Intergration Services project and then re adding from the server it was deployed to, but don't understand why Git Extensions was previously not recognising changes to this package

**Comment by pmiossec** [comment]
As you should know, GitExtensions use git under the hood. Pretty sure it is
not a problem of GitExtensions but from git or git configuration.

If you open a command line, what is the result of 'git status'?
