### ISSUE TITLE
Resetting another branch fails if path contains '%20'

### ISSUE THREAD

**Issue by maschoene** [gitextensions/gitextensions#8822]
## Current behaviour

When resetting any other branch to any other commit than it is currently pointing to, it fails.

```
"C:\Program Files\Git\bin\git.exe" push "file://C:\Users\maschoene\demo%20repo" "8ef225eb3050ddc5394803f4761d51c325fadaf2:refs/heads/develop" --force
fatal: 'C:\Users\maschoene\demo repo' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Done

Press Enter or Esc to close console...
```

## Expected behaviour

Resetting another branch works as with any repo without the '%20' characters.

## Steps to reproduce
bash:
```
cd somewhere/you/want
mkdir demo%20repo
git init
git commit --allow-empty -m "first"
git commit --allow-empty -m "second"
git branch develop
```
Git Extensions:
* open repo
* right click on "first"
* click "Reset another branch to here"
* select develop
* tick "Force reset for a non-fast-forward reset"
* click "OK"

## Screenshots

I don't think they're needed, tell me which are, if they're.

## Did this work in previous version of GitExtensions

I don't know.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4300.0
- DPI 144dpi (150% scaling)

## Diagnostics

Tell me if you need it.

## Additional note

Please don't judge me for the request, I didn't pick the repo name. Besides this, I actually haven't encountered any issue with the '%20' chars, so props for that!

**Comment by pmiossec** [comment]
For me a fix could be to run this command:

    git push . "8ef225eb3050ddc5394803f4761d51c325fadaf2:refs/heads/develop" --force
instead of:

    git push "file://C:\Users\maschoene\demo%20repo" "8ef225eb3050ddc5394803f4761d51c325fadaf2:refs/heads/develop" --force

that way we avoid this kind of problem with special chars in the path...

**Comment by pmiossec** [comment]
@maschoene Could you test the output of #8824 : 
https://ci.appveyor.com/api/buildjobs/wvgj7l9dpqy0d729/artifacts/artifacts%2Fpublish%2FGitExtensions-Portable-3.6.0.10965-58e28ccf1.zip

And report if it solves your problem...

**Comment by maschoene** [comment]
Works fine!
