### ISSUE TITLE
Jira Plugin-Auth

### ISSUE THREAD

**Issue by vbjay** [gitextensions/gitextensions#8825]
## Feature description

Jira plugin uses user name and password to authenticate.  Jira supports api tokens.  We should switch to using that.  My work jira account authorizes through a Microsoft account and not user name/password.  

![image](https://user-images.githubusercontent.com/3629489/107093290-fa982480-67d2-11eb-9a95-36f687c7d91d.png)

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.2
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.8.4311.0
- DPI 96dpi (no scaling)

**Comment by matyasbach** [comment]
For me was enough to put API token instead of password and it works well. However I have attlassian acount. Have you tried just putting your MS account email into username and token as a password?

Maybe the _Password_ could be renamed to _Password/API token_ in plugin configuration.

**Comment by vbjay** [comment]
I'll try.

**Comment by vbjay** [comment]
Confirmed.  It did work.  I do like the idea of updating the caption to make it clear that the token = password field.

**Comment by RussKie** [comment]
No pull request? 😢
