### ISSUE TITLE
AppVeyor build integration does not work with v2 tokens

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#8828]
## Current behaviour

v2 tokens require another api path, https://ci.appveyor.com/api-keys
```
Below is a new user-level API key (v2) that allows working with any account user has access to.
API calls must be prepended with /api/account/<account-name>/ part to choose account to work with. 
```

Initial tests indicates that there is something more as well.

v1 (and no token at all??) has base /api/. However, I have no v1 key and cannot get no key working (not completely sure that should work) so the status is unclear.
The focus of this issue is on v2 tokens, as that is the path forward.

## Expected behaviour

Build status shown

## Steps to reproduce

* Open Git Extensions repo, pre configured for Appveyour
* Add username to settings
* Generate a v2 key https://ci.appveyor.com/api-keys
* Add the key to the configuration
 
Build status should be visible in the status column 

## Screenshots

![image](https://user-images.githubusercontent.com/6248932/107118129-54562880-687f-11eb-9eba-760814f6eddc.png)

should be

![image](https://user-images.githubusercontent.com/6248932/107118166-810a4000-687f-11eb-9282-463b5f6ac7b8.png)

(for a Jenkins repo, some problems in a separate repo)

## Did this work in previous version of GitExtensions

v2 tokens cannot have worked in GE

unsure when I had a working setup, but I had something working in 3.4 this summer (v2 token was older though)

## Environment

- Git Extensions 33.33.33
- Build db4a7087e673733daa25e1026f7b5cab603a74d1
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
>v1 (and no token at all??) has base /api/. However, I have no v1 key and cannot get no key working (not completely sure that should work) so the status is unclear

I have nothing configured and it works out of the box. I can see GitExtensions builds results.
So there is at least something working 😉

**Comment by gerhardol** [comment]
> I have nothing configured and it works out of the box. I can see GitExtensions builds results.
> So there is at least something working 😉

I occasionally get it working without a token, maybe due to rate limiting. However, when testing the REST api also with v2 tokens, it still occasionally fails.
