### ISSUE TITLE
Connection closed unexpectedly by remote when pushing large files with git-lfs

### ISSUE THREAD

**Issue by asfarley** [gitextensions/gitextensions#8853]
## Current behaviour

When pushing commits (to Github) that add large files, and with git-lfs installed, I am getting a reported error: connection closed unexpectedly by remote.

Then, I push again, and I see that a smaller file/changeset is pushed. This time, there is no error reported. 

It appears that the push is happening correctly, aside from the fact that I have to do it twice and there is a false-positive error reported.

## Expected behaviour
I expect that I can push change-sets adding large files when using the git-lfs extension.

## Steps to reproduce
Create a repository. Install git-lfs module. Add many large files to module (>100MB). Push to Github. (presumably, this would reproduce the issue - I have not confirmed these steps).

## Screenshots
To be added

## Did this work in previous version of GitExtensions
I don't remember seeing this error until recently. I can't confirm specifically what version it was working correctly on, if ever.

## Environment

- GitExtensions version: 3.4.3.9999
- GIT version: 2.28.0.windows.1
- OS version: Microsoft Windows NT 10.0.18363.0
- .NET version: .NET Framework 4.8.4300.0

**Comment by RussKie** [comment]
How is it working from cli? GE is running git commands, there's generally
little or no magic involved.

**Comment by asfarley** [comment]
Hmm, I'm not sure what happened here; I tried to reproduce with another set of large files and it didn't happen. Maybe something funny was happening with my internet connection, I'll just close this.
