### ISSUE TITLE
[Theming] ListView incorrect column line colour

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8863]
## Current behaviour

https://github.com/gitextensions/gitextensions/pull/8849#issuecomment-781774683

| Default | Dark |
--|--
![image](https://user-images.githubusercontent.com/4403806/108448963-c9315580-72b6-11eb-90f1-970b38dd7180.png) | ![image](https://user-images.githubusercontent.com/4403806/108448997-d8b09e80-72b6-11eb-8a28-e0adf6471bbd.png)

In the default (system) theme the column vertical line is of a faint light blue colour. In the dark theme - the column line's colour is significantly more prominent, and looks the same as the colour as the border.

## Steps to reproduce

Checkout https://github.com/gitextensions/gitextensions/pull/8849/commits/983b0c320b0a5de53562a04edb4712263b539d14 (or the commit from https://github.com/gitextensions/gitextensions/pull/8849)

**Comment by RussKie** [comment]
@NikolayXHD would you be able to look into this? Or may be provide some pointers where to look... 
Thanks

**Comment by NikolayXHD** [comment]
I left a little description of how I handled this, to help in case someone else dares to mess with theming overrides.

https://github.com/gitextensions/gitextensions/wiki/Dark-Theme#overriding-winapi-calls

**Comment by RussKie** [comment]
> I left a little description of how I handled this, to help in case someone else dares to mess with theming overrides.
> 
> [gitextensions/gitextensions/wiki/Dark-Theme#further-tweaking-theme-overrides](https://github.com/gitextensions/gitextensions/wiki/Dark-Theme#further-tweaking-theme-overrides)

Champion!
