### ISSUE TITLE
Left panel: Replace contextual menuitem "Expand all" by "Expand all subnodes"

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#8873]
## Feature description

The "Expand All" feature in the left panel was added in the old times when only branches and remotes were displayed #5012

Now, that Tags and submodules are added and perhaps some more things in the future (worktrees, stashes, ...), I'm not sure that someone wants to expand everything anymore.

That's the first time I wanted to use the feature and I found it a little surprising. I wanted to expand all the branches to find one but I end up at the bottom of the tags :

![expand_all](https://user-images.githubusercontent.com/460196/108904357-af797080-761e-11eb-99d8-336819c0a31f.gif)

I think that the "Expand all" should be replaced by a "Expand subnodes" that will expand everything under the selected node.

What do you think?

## Environment

- Git Extensions 33.33.33
- Build 0ccc7fcedb2b3dab976368382a58fb43db18da78
- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.17134.0
- .NET Framework 4.8.4311.0
- DPI 192dpi (200% scaling)

**Comment by ivangrek** [comment]
I think should "Expand/Collapse" for current node only like in VS.

![image](https://user-images.githubusercontent.com/3169265/108906064-21ef4e00-7629-11eb-8fa8-ae09f49d308d.png)

> I think that the "Expand all" should be replaced by a "Expand subnodes" that will expand everything under the selected node.

It is intuitively clear what should be tried on for the current node.

**Comment by gerhardol** [comment]
> I think should "Expand/Collapse" for current node only like in VS.

I agree, change the behavior (also collapse) not the label

**Comment by pmiossec** [comment]
> > I think should "Expand/Collapse" for current node only like in VS.
> 
> I agree, change the behavior (also collapse) not the label

That's what I have done. PR is coming...
