### ISSUE TITLE
"bisect" labels no longer displayed

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8879]
## Current behaviour

![image](https://user-images.githubusercontent.com/4403806/108944555-1181b680-76af-11eb-9ecd-4d0d6f3db0c3.png)

## Expected behaviour

Git Extensions 3.4.3.9999
![image](https://user-images.githubusercontent.com/4403806/108944491-f6af4200-76ae-11eb-8e6b-7fd35109355a.png)

## Steps to reproduce

Start bisect and compare 3.4.3 version with the current dev

## Did this work in previous version of GitExtensions

Git Extensions 3.4.3.9999

## Environment

- Git Extensions 33.33.33
- Build 221fc396b5db296c45d566a35a76facd6fbab38b (Dirty)

**Comment by gerhardol** [comment]
There were some cleanup the logic for getting refs (previously remotes and tags were handled the same or something) that probably do not retrieve them any more.

**Comment by gerhardol** [comment]
The cleanup in GetRefsCmd()  forces parsing to only /refs/heads, /refs/remotes, /refs/tags, skipping at least /refs/bisect, /refs/notes, /refs/stash
Reverting that for now in a PR as a proposal
