### ISSUE TITLE
AuthenticationException when trying to use Jira Commit Hint Plugin

### ISSUE THREAD

**Issue by Holo-Viktor** [gitextensions/gitextensions#8884]
## Current behaviour
trying to use the plugin for the first time, entered link & credentials, when trying to use it in the commit windows or trying to open the jira plugin window again after having saved the credentials results in an authentication exception

## Expected behaviour
when I press the template button in the commit window I would expect it to show me all tickets including their ids (preferably with the *option* to filter by assignee)

## Screenshots
![image](https://user-images.githubusercontent.com/43336921/109010502-20b53400-76b0-11eb-85f0-26348d68bf96.png)

## Did this work in previous version of GitExtensions
i dont know

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.29.2.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by Holo-Viktor** [comment]
I guess another relevant info is that I'm using Jira Cloud

**Comment by pmiossec** [comment]
Similar to #8825 ?
Did you tried to pass a personal access token ?

**Comment by Holo-Viktor** [comment]
Yes! Sry, I didn't find that issue, thanks for your help!
