### ISSUE TITLE
Failed to detect IsDarkTheme

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#8904]
## Current behaviour

I tried to run Git Extensions (master). Few months again, I never had a problem.
Today, Git Extensions crashes at : 

GitUI\Theming\ThemeModule.cs:56

```
IsDarkTheme = theme.SysColorValues[KnownColor.Window].GetBrightness() < 0.5;
```

because ``theme.SysColorValues`` is empty. A simple check if key exists solve the problem.

## Expected behaviour

No crash.

## Steps to reproduce

Just start the application. I don't know why GE crashes.

## Did this work in previous version of GitExtensions

Yes :
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

## Environment

- GitExtensions version: 2bf1e3c9cc4b9ddbe4b2bdf5d37d03b86c6b45cc
- GIT version: Git 2.30.0.windows.1
- OS version: Microsoft Windows NT 10.0.19042.0
- .NET version: .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

## Diagnostics

``G:\Github\gitextensions\GitUI\Theming\ThemeRepository.cs:27`` with  ``GetTheme`` uses

``themePath = C:\Users\xxx\AppData\Roaming\GitExtensions\GitExtensions\Themes\migrated.css`` :

```
.OtherTag { color: #808080}
.AuthoredHighlight { color: #ffffe0}
.HighlightAllOccurences { color: #ffffe0}
.Tag { color: #00008b}
.Graph { color: #8b0000}
.Branch { color: #8b0000}
.RemoteBranch { color: #008000}
.DiffSection { color: #e6e6e6}
.DiffRemoved { color: #ffc8c8}
.DiffRemovedExtra { color: #ffa5a5}
.DiffAdded { color: #c8ffc8}
.DiffAddedExtra { color: #87ff87}
```

**Comment by bansan85** [comment]
Bisect found :

Author:			Philippe Miossec <pmiossec@gmail.com>
Author date:	6 months ago (06/09/2020 19:43:02)
Commit date:	6 months ago (08/09/2020 11:33:59)
Commit hash:	ea4808b7918fe7984555bb53297a0de0464a5fcf
Children:		0f81767f Commit index
Parent:			26c1d3fb

Dark title bar when using a dark theme on recent versions of Win10

Source: https://stackoverflow.com/a/62811758/717372
Related links: View on GitHub
Contained in branches:
master
(no branch, bisect started on master)
Contained in no tag

Derives from tag: v3.00.00-rc2 + 862 commits

**Comment by bansan85** [comment]
One solution is to change:

```
            if (theme.SysColorValues.ContainsKey(KnownColor.Window))
            {
                IsDarkTheme = theme.SysColorValues[KnownColor.Window].GetBrightness() < 0.5;
            }
```

**Comment by pmiossec** [comment]
Seems good to me. Could you do a PR?

**Comment by pmiossec** [comment]
Thinking about it again, I don't really understand why it doesn't return a color.

Perhaps @NikolayXHD could have an idea why?

**Comment by bansan85** [comment]
For you information, I have GE 3.4.3.9999 installed in C:\Program Files (x86)\GitExtensions and I was running GE master with VS. Maybe GE Master was reading files from GE 3.4.9999.

**Comment by NikolayXHD** [comment]
> Thinking about it again, I don't really understand why it doesn't return a color.
> 
> Perhaps @NikolayXHD could have an idea why?

```cs
IsDarkTheme = theme.GetColor(KnownColor.Window).GetBrightness() < 0.5;
```

**Comment by bansan85** [comment]
@NikolayXHD I confirm that your code also work. Should I update my PR ?

**Comment by NikolayXHD** [comment]
> @NikolayXHD I confirm that your code also work. Should I update my PR ?

yes, this is "the right way" )

**Comment by bansan85** [comment]
@NikolayXHD : thanks for the fix.
