### ISSUE TITLE
GE hangs when viewing submodules in diff viewer

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#8914]
## Current behaviour

Regression in master in the last days. 

If a submodule is selected in worktree (at least - seem OK for HEAD though), GE hangs and stops responding. Status is never changed from the default. Mouse just spinning.

## Expected behaviour

Submodule is displayed.

## Steps to reproduce

Select modified submodule in worktree in the diff viewer.

## Screenshots

![image](https://user-images.githubusercontent.com/6248932/109844938-e79b3780-7c4c-11eb-9443-1ddee6a2fa6d.png)

## Did this work in previous version of GitExtensions

- Git Extensions 3.6.0.11114
- Build f54a727a95393dcacfbbd8603dfd6daf931618c4 (Dirty)

## Environment

- Git Extensions 3.6.0.11170
- Build 273a0f6fd3e07858f837cdc19d50827871e32319 (Dirty)
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Not in release/3.5

Introduced in 7f7a6f2be079f123d5fdbe10c41489ddc7b54ea7
https://github.com/gitextensions/gitextensions/commit/7f7a6f2be079f123d5fdbe10c41489ddc7b54ea7#diff-c9456496ac47efd017c5bf895c05418cbe001c5a471a5bcd33104d6f9a42d513
```c#
diff --git a/GitUI/GitUIExtensions.cs b/GitUI/GitUIExtensions.cs
index 5359d6..195a1a 100644
--- a/GitUI/GitUIExtensions.cs
+++ b/GitUI/GitUIExtensions.cs
@@ -112,10 +112,11 @@ void OpenWithDiffTool()
                         : diffOfConflict;
                 }
 
-                if (file.IsSubmodule)
+                if (file.IsSubmodule
+                    && file.GetSubmoduleStatusAsync() is Task<GitSubmoduleStatus> task)
                 {
                     // Patch already evaluated
-                    var status = ThreadHelper.JoinableTaskFactory.Run(file.GetSubmoduleStatusAsync);
+                    var status = ThreadHelper.JoinableTaskFactory.Run(() => task);
                     return status is not null
                         ? LocalizationHelpers.ProcessSubmoduleStatus(fileViewer.Module, status)
                         : $"Failed to get status for submodule \"{file.Name}\"";
```

Maybe similar problem in similar situation

checkout conemu master (same as current commit), should be the first diff to view
Git need to slowed down to see this. You can install Symantec to slow down Git ten times or add the following patch.

```c#
diff --git a/GitCommands/Git/GitModule.cs b/GitCommands/Git/GitModule.cs
index 1ec1a..e85e9 100644
--- a/GitCommands/Git/GitModule.cs
+++ b/GitCommands/Git/GitModule.cs
@@ -2635,6 +2635,7 @@ private void GetSubmoduleStatus(IReadOnlyList<GitItemStatus> status, ObjectId? f
                         async () =>
                         {
                             await TaskScheduler.Default.SwitchTo(alwaysYield: true);
+                            await Task.Delay(1000);
                             return SubmoduleHelpers.GetCurrentSubmoduleChanges(this, item.Name, item.OldName, firstId, secondId);
                         }));
             }
```

**Comment by gerhardol** [comment]
@drewnoakes Why is null forgiving required here?

**Comment by drewnoakes** [comment]
@gerhardol because the type signatures don't match. `GetSubmoduleStatusAsync` returns `Task<X?>?` and `Run` accepts a func returning `Task<X?>`. It doesn't know that checking the earlier method call's return value for null guarantees that the subsequent method call won't return a null task.

I will take a look now to see if there is a better fix. While the diff shown may fix the issue, I don't think it's a good solution overall as the async work is still done twice.

**Comment by drewnoakes** [comment]
I cannot repro the hang. If I modify `Externals/EasyHook` by adding a file and committing it, then in the parent repo select the "Working directory" artificial commit, focus the "Diff" tab and then focus the submodule, there is no hang. Is there a different sequence of actions that will repro this? Is there a race condition here or is it 100% reliable?

**Comment by gerhardol** [comment]
If the task has executed it is fine. 
Delay the got command with the patch above.

**Comment by gerhardol** [comment]
Maybe the sub module task should always be created, as it is really implemented (at least in filestatuslist) so the task itself is never null. But this may start the git command earlier so it competes with other interactive commands, delaying the Ui.

**Comment by drewnoakes** [comment]
Thanks @gerhardol. I think this is a better fix as it avoids the hang and causes the operation to only fire once:

```diff
diff --git a/GitUI/GitUIExtensions.cs b/GitUI/GitUIExtensions.cs
index d90a9fabc..4950bd574 100644
--- a/GitUI/GitUIExtensions.cs
+++ b/GitUI/GitUIExtensions.cs
@@ -112,11 +112,12 @@ void OpenWithDiffTool()
                         : diffOfConflict;
                 }

-                if (file.IsSubmodule
-                    && file.GetSubmoduleStatusAsync() is Task<GitSubmoduleStatus> task)
+                if (file.IsSubmodule)
                 {
                     // Patch already evaluated
-                    var status = ThreadHelper.JoinableTaskFactory.Run(() => task);
+                    var status = ThreadHelper.JoinableTaskFactory.Run(
+                        () => file.GetSubmoduleStatusAsync() ?? Task.FromResult<GitSubmoduleStatus?>(null));
+
                     return status is not null
                         ? LocalizationHelpers.ProcessSubmoduleStatus(fileViewer.Module, status)
                         : $"Failed to get status for submodule \"{file.Name}\"";
```

Interestingly, if you increase that delay the entire UI is frozen for the duration of the operation. This shouldn't be blocking the UI thread.

**Comment by drewnoakes** [comment]
Actually no, that's not a correct fix in the case that the status was not requested. Taking another look.

**Comment by gerhardol** [comment]
My fix was for sure just a fix to get going, if thought it was useable I would have created a PR for discussion...

This changes back my original comment on the pattern change: This assumes that the task is created. It is in this situation though.

I would rather change GetSubmoduleStatusAsync() to never return a null task but to throw an exception here.
I believe that should be OK in other situations, but we can add a separate method for now like `GetNonNullSubmoduleStatusAsync()`.
The submodule check after can be simplified too.

@drewnoakes I can submit a PR for you to review?

The hanging is slightly separate, ViewChangesAsync() is executing on the UI thread. Maybe we should await the task execution as well as patch evaluation for non submodules.

**Comment by drewnoakes** [comment]
@gerhardol I believe I've just gotten this working. The fix is a bit larger as it involves making more methods async. It no longer hangs the process, and the UI remains responsive even if you put a long delay in the submodule status query. A bunch more methods are async though. I'll get a PR up in the next 30 minutes or so, unless I find a bug. Going to do a little more testing first.

**Comment by drewnoakes** [comment]
@gerhardol that PR is up, but the integration tests failed. It's late here so I won't get to look at this tonight. If you're interested in this issue and want to push to that PR or file another PR, be my guest.

**Comment by drewnoakes** [comment]
That integration test passes on my machine. I've re-queued the PR build in case it's a random failure.
