### ISSUE TITLE
patch view in file/folder history view

### ISSUE THREAD

**Issue by pavlexander** [gitextensions/gitextensions#8916]
## Feature description
I would like to request the option to see the "filtered" list of changes for file/folder. I call it the "patch-view". Also you could add it as an option to the CLI command: `gitex filehistory XXX\Client --patch-view`. The functionality is very essential in cases when you are viewing the folder related changes. You don't want to see anything else but this folder's changes! Same is applicable for file history requests, I guess..

To demonstrate want I want -  please take a look at this:

### example: `gitk`: 

![image](https://user-images.githubusercontent.com/20644772/109935757-891a9b80-7cd6-11eb-9b47-5e478758275d.png)

On the right hand side we have a selector that says **patch**. I think this is how my request must be described. I want to see the patch view. The view only shows 1 particular file history and not the rest of the files that were pushed in the same commit! Or in this example's case - folder related changes only.

### example: `git extensions` (currently): 

Now let's look at the same commit in `git extensions`:

![image](https://user-images.githubusercontent.com/20644772/109935588-6daf9080-7cd6-11eb-8aff-5d938629e63f.png)

The list of commits is the same, but instead of viewing the history of an item that you have selected - the view is cluttered with lot's of unnecessary files..

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by vbjay** [comment]
The commit is still being shown.  What it is doing is finding commits that
contain the looked for file and displaying those commits. Those commits are
supposed to show exactly what the commit is. It is not extra info.

**Comment by vbjay** [comment]
Also note the other tabs.

**Comment by pavlexander** [comment]
> The commit is still being shown. What it is doing is finding commits that contain the looked for file and displaying those commits. Those commits are supposed to show exactly what the commit is. It is not extra info.

I don't understand if this reply requires my responses or not. What is that you are implying exactly?

The feature request I have proposed has nothing to do with the commit history. Rather, it's about "presentation" of commits (it's easier to understand what I mean by looking at `gitk` example) (or reading the feature request description :))

**Comment by gerhardol** [comment]
If you only want to see files from a certain folder, you can use the filter.

Other than that I do not see what the feature is about, gitk patch is similar to GE diff, except that gitk shows the file as one long change and GE as separate files.

**Comment by RussKie** [comment]
Does this help?
![image](https://user-images.githubusercontent.com/4403806/110063587-88116900-7dbf-11eb-8e47-c4a1c21fc11e.png)

**Comment by pavlexander** [comment]
> Does this help?

Regular expressions always were an option. I just don't consider this friendly from the end-user's perspective.. 

We have 2 cases

1. user wants to view the commit history associated with the folder - **existing functionality works OK as is**
2. user wants to view the actual changes that occurred within the folder throughout commit history. That's when the patch-view option will come in handy. Imagine switching being at max be an 1-click toggle! I would like to remind that this view is **default** in `gitk`. There must be a reason why they've done that :)

It would be interesting to create a poll and ask people how they are using the folder history functionality.. Is it option 1 or 2 that the need the most. Maybe I am the only one who always interested in a set of files within the folder? Sure I/we can use the regex, but that's just +x number of clicks/keyboard presses added to the process. _Not very friendly from UX perspective._

From the replies I see that nobody really is interested in this as much as I do. And since we can use the regex - this thread is bound to be closed. I would suggest closing it right away then (unless you want to create a poll :) ).

**Comment by gerhardol** [comment]
@pavlexander 
GE is community driven: Most features are added when a specific developer wants some functionality for themselves.
#7598 is something that already is discussed. If you do not want to implement this in FileHistory you may describe how you envision your functionality in Browse.

**Comment by vbjay** [comment]
The issue is someone looks at the commit and freaks out because changes are
missing. When I lol at a commit I expect to see all the changes.

**Comment by pavlexander** [comment]
> The issue is someone looks at the commit and freaks out because changes are missing. When I look at a commit I expect to see all the changes.

@vbjay 
Agreed. It's one of those changes that could be called a "breaking change". Not in terms of breaking the functionality, but changing the behavior of the functionality that people gotten used to (given that there was no other option before that)

> GE is community driven: Most features are added when a specific developer wants some functionality for themselves.
> #7598 is something that already is discussed. If you do not want to implement this in FileHistory you may describe how you envision your functionality in Browse.

@gerhardol 
Thank you for the hint.. I think, that if the presentation layer is going to be refactored anyways, then the change I am asking here might as well be a part of that, if community deems it important. I will leave a comment under the topic that you have mentioned and close the current discussion.
