### ISSUE TITLE
"Build Report" icon appearance is broken at 150% scaling

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#8922]
## Current behaviour

![image](https://user-images.githubusercontent.com/350947/110095739-53b6a080-7df1-11eb-8e6f-fc248cf4209e.png)

## Expected behaviour

Normal icon.

## Steps to reproduce

Run GE at 273a0f6fd3e07858f837cdc19d50827871e32319

## Environment

- Git Extensions 33.33.33
- Build 273a0f6fd3e07858f837cdc19d50827871e32319
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 144dpi (150% scaling)

**Comment by bansan85** [comment]
Thanks for the report. I can't reproduce it.

![image](https://user-images.githubusercontent.com/9248729/110377283-81e7ea80-8054-11eb-9504-5c1049ef5bdf.png)

I tried with GE black theme and it's the same.

**Comment by RussKie** [comment]
I can't repro:

![image](https://user-images.githubusercontent.com/4403806/110463299-d9a25680-8125-11eb-8b06-a41ae97d6bf2.png)
![image](https://user-images.githubusercontent.com/4403806/110463967-aa401980-8126-11eb-9e73-e8917fd7ac3e.png)

**Comment by drewnoakes** [comment]
I haven't seen it since. If I see it again, I'll re-open this.
