### ISSUE TITLE
GitHub "View pull requests" exception

### ISSUE THREAD

**Issue by sanghel-payoff** [gitextensions/gitextensions#8931]
## Current behaviour
Have repo configured with a Github remote via SSH.
Have GitHub plugin with an OAuth token setup. Fetch / push works without issues
Have pull requests open on GitHub.

May be related to #7336

## Expected behaviour
Can view pull-requests from GitHub

## Steps to reproduce
Menu _GitHub > View pull requests_ generates exception

## Screenshots
![image](https://user-images.githubusercontent.com/77339756/110165848-cf195180-7df3-11eb-8398-0c8e21f4b869.png)

## Did this work in previous version of GitExtensions
No idea, just migrated to GitHub.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by bansan85** [comment]
Do you think it could be related to https://docs.github.com/en/enterprise-server@3.0/rest/reference/oauth-authorizations#list-your-authorizations ?

``The OAuth Authorizations API will be removed on November, 13, 2020. ``

**Comment by bansan85** [comment]
Duplicated #8850 ? I also have "Not Found" but I never used this feature before.

**Comment by RussKie** [comment]
Closing in favour of #8850
