### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#8955]
## Current behaviour

Documentation pages are inaccessible from the app.

E.g. the Settings dialog:
![image](https://user-images.githubusercontent.com/4403806/110273861-9f4f9100-8021-11eb-8a2e-c66367203b52.png)

Click on the blue ℹ in this dialog will try to open the following URLs:
* https://git-extensions-documentation.readthedocs.io/settings.html#git-extensions-appearance-author-images-avatar-provider
* https://git-extensions-documentation.readthedocs.io/settings.html#git-extensions-appearance-author-images-avatar-fallback
And a user is greeted with the following:
![image](https://user-images.githubusercontent.com/4403806/110273943-cd34d580-8021-11eb-89d6-ea8e5f6b6040.png)

Also open `FormClone` dialog and click on [?] button:
![image](https://user-images.githubusercontent.com/4403806/110274001-f190b200-8021-11eb-8c8d-3661a64d3a70.png)
It opens https://git-extensions-documentation.readthedocs.io/getting_started.html#clone-repository, which is also a 404.

## Expected behaviour

All links are correctly resolved and opened for the _latest_ version.

## Did this work in previous version of GitExtensions

Very likely a regression introduced in https://github.com/gitextensions/gitextensions/pull/8838 and https://github.com/gitextensions/gitextensions/pull/8893.

## Environment

- GitExtensions version: 12615869044a4db1f95609c05af93665045eb181

**Comment by RussKie** [comment]
@gerhardol with https://github.com/gitextensions/GitExtensionsDoc/issues/133 fixed, how do you think we can fix this one?
I can't see another solution apart from restoring restoring `/en/latest`. (In fact it should be `/<current user language>/latest`, but that's a separate issue).

**Comment by gerhardol** [comment]
I played around yesterday and have more or less the same conclusion. (I have been sick for some days and it took quite some hours of reading and fixing minor things until I even read this.)

Plan to make PR sometime tonight (either /en/master or an redirect which would handle translations, but release should probably be updated as it was before, just not / that is automatically redirected).

**Comment by RussKie** [comment]
Please look after yourself first, and get well soon.
I've been burning a lot of midnight oil too, hence the delays with the
release and reviews...

**Comment by gerhardol** [comment]
I added a redirect again and now it works.... As strange as the build on the 3.5 commit that displayed as 3.3.

So no change is really required in master, but maybe we should make them anyway, so master in gitextensions look at the master doc build and the doc links works when we update version.

Edit: I did not submit this comment so I filed a PR for what I believe is the simplest and not rely on redirects: Slightly revert #8838 and add versions to all links.
Links in master will then work when we have built the master version too.

**Comment by RussKie** [comment]
> I added a redirect again and now it works....

🎉 



> So no change is really required in master, but maybe we should make them anyway, so master in gitextensions look at the master doc build and the doc links works when we update version.
> 
> Edit: I did not submit this comment so I filed a PR for what I believe is the simplest and not rely on redirects: Slightly revert #8838 and add versions to all links.

I think we can tweak the setup script to burn `/en/release-X.Y` into the code. I'd just centralise the link to a single const, and then reference it everywhere.
