### ISSUE TITLE
Bitbucket Plugin doesn't allow repositories with dot in the name

### ISSUE THREAD

**Issue by AntonKedrov** [gitextensions/gitextensions#8965]
Hi! I'm switching from Sourcetree to Git Extensions. So far I really like it, but there is a small issue with Bitbucket Plugin.

When launching Bitbucket Plugin, it displays error "Your repository is not hosted in BitBucket Server." I think this is because of Regex pattern does not allow dots in the repository name.
https://github.com/gitextensions/gitextensions/blob/082d8c27da3e527b0d71019430ccecd995a8d878/Plugins/Bitbucket/Settings.cs#L13

Our repositories have at least one dot in the name, so URL looks like this:
`https://stash.company.com/scm/project_name/repo_type.project_group.app_name.app_type.git`
Could you please change pattern from `(?<repo>([\w\-]+))` to `(?<repo>([\w\-\.]+))`.

I have tried Bitbucket Plugin on the repo, which doesn't have dots in the name and it worked just fine.

**Comment by RussKie** [comment]
Would you like to send a PR with a fix?

**Comment by drewnoakes** [comment]
It's possible there are other characters which would be allowed too, such as `_`. Maybe the group could just be `(?<repo>.+)`.

**Comment by AntonKedrov** [comment]
> It's possible there are other characters which would be allowed too, such as `_`. Maybe the group could just be `(?<repo>.+)`.

URL cannot contain any characters. bitbucket.org seems to be fine with repo name `a!@#$%^&*()[];',./{}:"<>?`, but it gets transformed into `https://.../a-..git`. And I'm not sure how Bitbucket Server will handle such repository name. I think `\w\-\.` will cover all possible characters.

> Would you like to send a PR with a fix?

Sure, I'll create pull-request.
