### ISSUE TITLE
FormCommit: Button color of Commit & Push when amending

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#8976]
## Current behaviour

When activating `Amend Commit` in FormCommit, the button `Commit & push` is colored green.

## Expected behaviour

The button should have a warning color.

## Steps to reproduce

- open FormCommit
- tick `Amend Commit`
-> check color of button `Commit & push`

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/110796873-bdfb9500-8278-11eb-88c5-94ba64ddc576.png)

## Did this work in previous version of GitExtensions

yes

## Environment

- Git Extensions 33.33.33
- Build abfb560039e933109e587b599f1f473df597beca
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4250.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Due to color inversion in #8900 ?

**Comment by mstv** [comment]
Yes, the following usages of `AppColor.Branch` must be adapted:
```
            SolveMergeConflicts.BackColor = AppColor.Branch.GetThemeColor();	FormApplyPatch.cs
            SolveMergeconflicts.BackColor = AppColor.Branch.GetThemeColor();	FormCommit.cs
                    ? AppColor.Branch.GetThemeColor()				FormCommit.cs
            panelMessage.BackColor = AppColor.Branch.GetThemeColor();		FormEditor.cs
            SolveMergeconflicts.BackColor = AppColor.Branch.GetThemeColor();	FormRebase.cs
```

**Comment by gerhardol** [comment]
> Yes, the following usages of `AppColor.Branch` must be adapted:

A new theme color or rename the existing names?
(Fallback to old colors if new does not exist?)

AppColor.ButtonWarning maybe?

**Comment by mstv** [comment]
Yes, I think a dedicated color must be introduced.

**Comment by RussKie** [comment]
> ## Did this work in previous version of GitExtensions
> yes

😮 the button never changed the colour for me. Is there some setting I'm not aware of?

**Comment by ivangrek** [comment]
![image](https://user-images.githubusercontent.com/3169265/111065435-4caf2280-84c2-11eb-9572-a8d1eb2a770a.png)

**Comment by gerhardol** [comment]
> 😮 the button never changed the colour for me. Is there some setting I'm not aware of?

This was missing for some time in FormCommit (also in 3.4).
Other buttons (like in conflicts) have been working all the time.
