### ISSUE TITLE
WiX Installer Bug

### ISSUE THREAD

**Issue by JTidswell** [gitextensions/gitextensions#899]
The WiX installer script has a bug in it.

This is causing multiple issues (see for example #217 & #371).

The problem is the directory configuration:

```
    <Directory Id="TARGETDIR" Name="SourceDir">
        <Directory Id="DesktopFolder">
            ...
        </Directory>
        <Directory Id="ProgramFilesFolder">
            ...
        </Directory>
        <Directory Id="PersonalFolder">
            <Directory Id="VS2005" Name="Visual Studio 2005" ShortName="zm4njmg8">
              ...  
             </Directory>
            <Directory Id="VS2008" Name="Visual Studio 2008" ShortName="yprgpbxy">
                ...
            </Directory>
            <Directory Id="VS2010" Name="Visual Studio 2010" ShortName="hj6jxl-d">
                ...
            </Directory>
       </Directory>
    </Directory>
```

The use of PersonalFolder (which is a WiX standard variable) is incorrect.

1) If we are installing for all users, then we dont want the files in the installing users home directory.

```
I think this case should use "CommonAppDataFolder" not "PersonalFolder".
```

2) If our home directory is on a network, we will want personal addins installed in some other directory.

```
I think this case should use "LocalAppDataFolder" instead of "PersonalFolder".
```

**Comment by karyon** [comment]
this is probably the root cause for #217, #292, #371, #2293 and #2426.

**Comment by RussKie** [comment]
I end up moving the addin from my home folder drive (remote) to 
`C:\Users\<username>\AppData\Roaming\Microsoft\MSEnvShared\AddIns`
