### ISSUE TITLE
Toggle left panel status reset after restart

### ISSUE THREAD

**Issue by SailorMax** [gitextensions/gitextensions#9000]
## Current behaviour
Toggle left panel status reset after restart

## Expected behaviour
Toggle left panel status has to be same after restart

## Steps to reproduce
1. turn off left panel
2. restart Git Extensions

## Did this work in previous version of GitExtensions
Yes, but it was long ago. I don't remember the version

## Environment
- Git Extensions 3.6.0.11442
- Build 549f02363b5470696a27a1f002241f5ae4f5c719 (Dirty)
- Git 2.30.2.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by drewnoakes** [comment]
I've noticed this too. When I launch GE in the debugger, the left panel is always visible, even if I turned it off when last ran.

**Comment by mstv** [comment]
still reproducible if setting `Open last working directory on startup` is off, refer to https://github.com/gitextensions/gitextensions/pull/9102#issuecomment-897962424
