### ISSUE TITLE
Jira Commit Hint plugin credentials are not propagated to submodules but the rest is

### ISSUE THREAD

**Issue by Holo-Viktor** [gitextensions/gitextensions#9002]
I don't really see a use case for having different credentials but the same URL, JQL query & template between modules.
It is probably more realistic to have 1 url+credentials and optionally different queries and templates between modules.

**Bug Report**: So if this plugin is meant to work only with one configuration for the entire repo including its submodules (this effectively represents the current feature set), please update the credentials for the submodules as well.

**Feature Request**: Otherwise, if you want to support diverging settings for submodules, please consider adding a checkbox beside every individual setting which determines whether the setting
a) propagates to submodules, or
b) is inherited by the parent module.

**Comment by gerhardol** [comment]
Jira Commit Hint plugin is removed in 4.0, see #9659 
This issue is therefore closed as not applicable, link from #9659
