### ISSUE TITLE
DownloadTransifexTranslations.ps1 fails with errors

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#9005]
## Current behaviour

DownloadTransifexTranslations.ps1 fails with the following errors:

> tx ERROR: Not Found
> tx ERROR: Not Found
> tx ERROR: Resource git-extensions.plugins-master doesn't exist on the server.
> tx INFO: Pulling resources...
> tx INFO: Done.
> tx ERROR: Not Found
> tx ERROR: Not Found
> tx ERROR: Resource git-extensions.ui-master doesn't exist on the server.
> tx INFO: Pulling resources...
> tx INFO: Done.

## Expected behaviour

Translation files are successfully downloaded with no error.

## Steps to reproduce

* Open PowerShell
* Run DownloadTransifexTranslations.ps1 

## Environment

- GitExtensions version: master branch
- GIT version: git version 2.30.1.windows.1
- OS version: Windows 10 Home
- .NET version: 4.8

## Diagnostics

tx.exe pull -r git-extensions.*
> tx ERROR: Not Found
> tx ERROR: Not Found
> tx ERROR: Resource git-extensions.ui-master doesn't exist on the server.
> tx ERROR: Not Found
> tx ERROR: Not Found
> tx ERROR: Resource git-extensions.plugins-master doesn't exist on the server.
> tx INFO: Done.

**Comment by gerhardol** [comment]
Try the release/3.5 branch, that is what RussKie is using when working on a new release

**Comment by RussKie** [comment]
I was tinkering with Transifex last week for 3.5, and forgot to update the
master.
Thanks for the ping, I'll get it fixed.
