### ISSUE TITLE
Remove "Close"/"Cancel" button in Form that just close the windows

### ISSUE THREAD

**Issue by bansan85** [gitextensions/gitextensions#9013]
## Feature description

Lost of windows don't have a close button. So to close the window, I need to click on the red cross.

Example with bisect form
![image](https://user-images.githubusercontent.com/9248729/111734144-d1f75600-8879-11eb-8c03-40fcf57d2d27.png)

But there is a few window that have a dedicated close button.

Example with "Clean working directory" form
![image](https://user-images.githubusercontent.com/9248729/111734206-ecc9ca80-8879-11eb-915b-c77cc4be4ad7.png)

More important, in the "Clean working directory" form, the "Cancel" button only close the window. This could confuse the user because you can not cancel anything (like if you have clicked on the "Cleanup" button).

## New behavior

I suggest to remove the close/cancel button in all windows where the button just close the UI.

After a quick review, the forms are "Clean working directory", "Reset changes", "Recover lost objects".

**Comment by RussKie** [comment]
Relates to #6183

**Comment by ivangrek** [comment]
Buttons for working with the keyboard.
Window close button for mouse operation.
I think it is correct to support two strategies.

**Comment by pmiossec** [comment]
>Buttons for working with the keyboard.

`Esc` key? Which is much more convenient, no!?!

**Comment by drewnoakes** [comment]
Keyboard oriented folks will use <kbd>Esc</kbd> or <kbd>Alt</kbd>+<kbd>F4</kbd> to close windows. This works across all windows on the desktop.

**Comment by bansan85** [comment]
> Buttons for working with the keyboard.
> Window close button for mouse operation.
> I think it is correct to support two strategies.

Sure. But there is missing a lot of Close button.
The UI of GE is already heavy due to the number of options. So I'm not pro adding a Close button to every form.

I just noticed that the "login form to Github" doesn't support ESC.

**Comment by ivangrek** [comment]
`Esc` - does not work everywhere.
`Alt+F4` - not always convenient.

The main point is that the use of system buttons does not always allow you to understand the consequences of an action.
Why use a checkmark to indicate an agreement and not just an OK button?

In our case, most likely, this is not important. 
But saying goodbye would be more polite than slamming the door. Although the result is the same. 😃 
This is all for information, just thoughts.

**Comment by gerhardol** [comment]
> But saying goodbye would be more polite than slamming the door. 

Agree

In "Clean working directory", the natural to me would be to change _Cancel_ to _Close_.

Bisect is a little special where _Stop bisect_ probably should close the form but X can be used for "temporary close"...

**Comment by ivangrek** [comment]
> The UI of GE is already heavy due to the number of options. So I'm not pro adding a Close button to every form.

I partially agree. This raises a big question that we are not ready to solve yet.

**Comment by bansan85** [comment]
Fine. So I leave this issue for later. I will just send a PR to change "Cancel" to "Close" in "Clean working directory" form. I will also create another PR to add support to ESC key in GitHub form.

**Comment by RussKie** [comment]
There's no need for Close buttons on dialogs. Cancel button is only needed
if there's a long running operation that can be interrupted.

Dialogs should be dismissable with ESC, and I think this is a Win32
behavior.

**Comment by drewnoakes** [comment]
> Cancel button is only needed if there's a long running operation that can be interrupted.

This isn't the whole story.

- "Cancel" applies in cases where you have uncommitted changes to some state that must either be committed or discarded. For example _Tools|Options_ in Visual Studio.
- "Close" applies in cases where there is no state to persist. For example _Tools|Customize_ and _Extensions|Manage_ in VS.

**Comment by RussKie** [comment]
I suppose "Cancel" button makes sense if the clean operation takes a significant time _and_ it is cancelable. Else there's no point in this button.
