### ISSUE TITLE
3.5 RC1 installer issues

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9026]
## Current behaviour

- [x] ~"Theme not found:" after longer time from settings dialog when trying to disable telemetry using the `Help` menu~ https://github.com/gitextensions/gitextensions/commit/7359a19142caf12d8f43f1731deb35b14e765f83
 
- [x] On save settings: `System.IO.FileNotFoundException` "File or assembly "Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" or a dependency was not found." active - https://github.com/gitextensions/gitextensions/issues/9110

- [x] ~Telemetry is enabled by the update installation~ (#8228)

## Expected behaviour

1. Just use the default theme
2. Settings can be saved
3. Telemetry setting not touched by the installer
  (Since someone also complained about the installer using not available powershell, IMO the easiest solution is removing the telemetry page and the regarding PS script from the installer.)

## Steps to reproduce

- install 3.4.3
- disable telemetry
- update to 3.5 RC1
- try to disable telemetry
- try to save settings

## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/111904697-8050f600-8a48-11eb-8b88-bd7ba59efac8.png)

## Did this work in previous version of GitExtensions

yes

## Environment

- Git Extensions 3.5.0.11509
- Build 009d10c765a90aa00e043e40d5117256b793bc8c (Dirty)
- Git 2.16.2.windows.1 (minimum: 2.19.0, please update!)
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.2633.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
> 2\. On save settings: `System.IO.FileNotFoundException` "File or assembly "Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" or a dependency was not found."

I haven't observed this. Do you have a stable repro?

**Comment by RussKie** [comment]
> 1. "Theme not found:" after longer time from settings dialog when trying to disable telemetry using the `Help` menu

This is fixed in https://github.com/gitextensions/gitextensions/commit/7359a19142caf12d8f43f1731deb35b14e765f83, right?

> 3\. Telemetry is enabled by the update installation (#8228)

Not fixing this.

**Comment by mstv** [comment]
>>  "Theme not found:" after longer time from settings dialog when trying to disable telemetry using the Help menu

> This is fixed in 7359a19, right?

yes

> > 2. On save settings: System.IO.FileNotFoundException "File or assembly "Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed" or a dependency was not found."

> I haven't observed this. Do you have a stable repro?

I cannot reproduce it (anymore). It might have been caused by concurrent Windows updates in that old VM.

> > 3. Telemetry is enabled by the update installation (#8228)

> Not fixing this.

This would not be good style.
