### ISSUE TITLE
I can't find branch name on the right bottom of my visual studio2019

### ISSUE THREAD

**Issue by BruceQiu1996** [gitextensions/gitextensions#9029]
![1616408596(1)](https://user-images.githubusercontent.com/28331315/111975576-bb802180-8b3b-11eb-9700-535a41e96e43.jpg)

**Comment by pmiossec** [comment]
You will have to give more information why you think it is linked to GitExtensions.
Otherwise, for me it is Visual Studio problem and so you are posting your problem to the wrong place, so, closing...

**Comment by vbjay** [comment]
Right click in that area. The menu will allow you to pick what is shown
there.
