### ISSUE TITLE
[NBug] Invalid escape character: R

### ISSUE THREAD

**Issue by hephi808** [gitextensions/gitextensions#9031]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.Exception: Invalid escape character: R
   at GitCommands.Config.ConfigFile.ConfigFileParser.ReadSection(Char c)
   at GitCommands.Config.ConfigFile.ConfigFileParser.Parse(String fileContent)
   at GitCommands.Config.ConfigFile..ctor(String fileName, Boolean local)
```

## Additional information
Cannot open Setting

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.28.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
The stacktrace seem to be truncated.
There has been changes to both the handling internally and presentation (if the external file is corrupted) since 3.4, please try 3.5RC1.
