### ISSUE TITLE
[NBug] Не удалось найти часть пути "E:\test_screenshots\.git\GitEx...

### ISSUE THREAD

**Issue by kshmel** [gitextensions/gitextensions#9036]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Error Details
```
System.IO.DirectoryNotFoundException: Не удалось найти часть пути "E:\test_screenshots\.git\GitExtensions.amend".
   в System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   в System.IO.File.InternalDelete(String path, Boolean checkHost)
   в System.IO.File.Delete(String path)
   в System.IO.Abstractions.FileWrapper.Delete(String path)
   в GitCommands.CommitMessageManager.set_AmendState(Boolean value)
   в GitUI.CommandsDialogs.FormCommit.OnFormClosed(FormClosedEventArgs e)
   в System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)
```

## Additional information
The repository has been deleted manually, but windows with commit was still opened. Trying to close the window

## Environment
- Git Extensions 3.5.0.11509
- Build 009d10c765a90aa00e043e40d5117256b793bc8c (Dirty)
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 144dpi (150% scaling)

**Comment by RussKie** [comment]
@gerhardol @mstv I think in this specific scenario we need to ignore the exception
