### ISSUE TITLE
`BugReportForm` not shown for exceptions in background threads

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9047]
## Current behaviour

GE terminates after the TaskDialog displayed for an exception from a background thread
due to a check for UI thread in `GitExtensionsFormBase`, which is wrong / not necessary in this case

## Expected behaviour

GE terminates after `BugReportForm`

## Steps to reproduce

- throw an exception from e.g. `ProcessWrapper.OnProcessExit`
- click `Report bug!` --> GE terminates
## Screenshots

![grafik](https://user-images.githubusercontent.com/36601201/113454721-261d4100-9409-11eb-960f-1f3b192001cf.png)

## Did this work in previous version of GitExtensions

I doubt it

## Environment

- Git Extensions 33.33.33
- Build ac6487fd05262fc38490cd18b0eabe6bfd321edc
- Git 2.27.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
Workaround: Let `BugReportForm` inherit from `Form` directly.
But then the form is not translated anymore.

So rather the check for UI thread should be made suppressible. Thoughts, @gitextensions/git-extensions-source?

**Comment by RussKie** [comment]
I think to have it translated we need to inherit from ITranslatable (or
whatever it's called).
Or move all strings to TranslatedStrings class (which I think is a more
strategic solution).
