### ISSUE TITLE
Open revision of removed file not working

### ISSUE THREAD

**Issue by glebov21** [gitextensions/gitextensions#9070]
## Current behaviour

Open revision of removed file not working

## Expected behaviour

Need open file in text editor

## Steps to reproduce

1) Click "Diff" of commit
2) Right click on removed file
3) Click "Open this revision with"

## Screenshots

![Безымянный](https://user-images.githubusercontent.com/693132/114685185-51156800-9d1a-11eb-8c42-854f8ce9cecf.png)

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.20.1.windows.1 (recommended: 2.25.1 or later)
- Microsoft Windows NT 6.3.9600.0
- .NET Framework 4.8.3928.0
- DPI 120dpi (125% scaling)

**Comment by mstv** [comment]
E.g. only `git ls-tree -r 1783b485236fc4e1ae838208f28d1807748ffe9b -- "GitUI/Theming/Renderers/TabRenderer.cs"` is run: exit code 0 but no output.
`git cat-file blob ...` is missing.

**Comment by gerhardol** [comment]
The error is that the menu option exists

There is no version to display for the command
(Actually it is more complicated than what you see, as you can reverse the diff. The menu must not be displayed if the version is in the selected commit.)

**Comment by mstv** [comment]
No, I have found a fix right now.

**Comment by mstv** [comment]
Of course, it is not exact to retrieve the BLOB of the first revision. But it matches the user's expectation.
