### ISSUE TITLE
[NBug] The directory name is invalid

### ISSUE THREAD

**Issue by DdOtzen** [gitextensions/gitextensions#9091]
## Current behaviour

Auto bug from crash.
Was trying to create a new worktree, and app crashed, and created this report.

## Expected behaviour
New worktree created

## Steps to reproduce

Not sure, this is a auto bug after crash.
Cannot say for sure that I did not make a typo in the dialog on new foldername, But then I would exspect gitex to complaints about that and not crash.
Maybe related to the fact that I was created this while being in a working tree I created using same function earlier, that is a working tree with no .git folder.

## Error Details
```
System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding)
   at GitCommands.ExecutableExtensions.<ExecuteAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
   at GitCommands.GitModule.get_GitCommonDirectory()
   at GitCommands.Settings.ConfigFileSettings.CreateLocal(GitModule module, ConfigFileSettings lowerPriority, SettingLevel settingLevel, Boolean allowCache)
   at GitCommands.Settings.ConfigFileSettings.CreateEffective(GitModule module)
   at GitCommands.GitModule.get_EffectiveConfigFile()
   at GitCommands.GitModule.get_FilesEncoding()
   at GitUI.Editor.FileViewer.encodingToolStripComboBox_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ToolStripComboBox.HandleSelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at System.Windows.Forms.ToolStripComboBox.set_SelectedIndex(Int32 value)
   at GitUI.Editor.FileViewer.<set_Encoding>b__58_0()
   at GitUI.GitUIExtensions.<InvokeAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GitUI.ThreadHelper.<>c__DisplayClass13_0.<<FileAndForget>b__0>d.MoveNext()
```

## Additional information
Created new worktree, while i was in a worktree without the .git folder.

## Environment
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4150.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
A few other occurrences with 3.4 (no reports with similar stacktrace earlier).
Some have useful information

**Comment by DdOtzen** [comment]
@mstv Sure.
I tried (without installing) to run this and repeat my worktree creation.
This time I get to see the git output dialog before it crashes.
```
"git" worktree add "C:\gsrc\XXX_BaseStructure\XXX_P1234_Rcc" develop
fatal: 'develop' is already checked out at 'C:/gsrc/XXX_BaseStructure/XXX_P1234'
Preparing worktree (checking out 'develop')
Done

Press Enter or Esc to exit...
```

It appears that using the default suggested branch, is a problem for git.
my plan was to create the WT, then over there create the next feature branch, maybe that is not good.

Anyway it appears gitex does not catch this error and just continues on its merry way.

After closing this dialog I get the originally reported error message.

![image](https://user-images.githubusercontent.com/10881985/115463290-eee1c900-a22b-11eb-9acf-961323b02cbf.png)

I clicked the copy button, here is the result

> 
> 
> :warning: The sections below must be filled in and this text must be removed or the issue will be closed.
> 
> ## Current behaviour
> 
> 
> 
> 
> ## Expected behaviour
> 
> 
> ## Steps to reproduce
> 
> 
> 
> 
> ## Error Details
> ```
> GitCommands.ExternalOperationException: The directory name is invalid ---> System.ComponentModel.Win32Exception: The directory name is invalid
>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute)
>    --- End of inner exception stack trace ---
>    at GitCommands.Executable.ProcessWrapper..ctor(String fileName, String arguments, String workDir, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute)
>    at GitCommands.Executable.Start(ArgumentString arguments, Boolean createWindow, Boolean redirectInput, Boolean redirectOutput, Encoding outputEncoding, Boolean useShellExecute)
>    at GitCommands.ExecutableExtensions.<ExecuteAsync>d__11.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
>    at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
>    at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
>    at GitCommands.ExecutableExtensions.Execute(IExecutable executable, ArgumentString arguments, Action`1 writeInput, Encoding outputEncoding, Boolean stripAnsiEscapeCodes)
>    at GitCommands.GitModule.get_GitCommonDirectory()
>    at GitCommands.Settings.RepoDistSettings.CreateLocal(GitModule module, RepoDistSettings lowerPriority, SettingLevel settingLevel, Boolean allowCache)
>    at GitCommands.Settings.RepoDistSettings.CreateEffective(GitModule module)
>    at GitCommands.GitModule.get_EffectiveSettings()
>    at GitCommands.GitModule.GetEffectiveSettings()
>    at ResourceManager.GitPluginBase.Register(IGitUICommands gitUiCommands)
>    at GitUI.PluginRegistry.<>c__DisplayClass12_0.<Register>b__0(IGitPlugin p)
>    at System.Linq.LinqExtensions.ForEach[T](IEnumerable`1 enumerable, Action`1 action)
>    at GitUI.PluginRegistry.Register(IGitUICommands gitUiCommands)
>    at GitUI.CommandsDialogs.FormBrowse.RegisterPlugins()
>    at GitUI.CommandsDialogs.FormBrowse.SetGitModule(Object sender, GitModuleEventArgs e)
>    at GitUI.CommandsDialogs.FormBrowse.createWorktreeToolStripMenuItem_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> ```
> 
> 
> ## Environment
> - Git Extensions 3.5.0.11670
> - Build 4e923d56301101f04a95ffa2aedaa489ed867878 (Dirty)
> - Git 2.31.1.windows.1
> - Microsoft Windows NT 10.0.18363.0
> - .NET Framework 4.8.4150.0
> - DPI 96dpi (no scaling)
>

**Comment by mstv** [comment]
Thank you very much for the details, @DdOtzen.
Worktrees are limited by Git to not operate on the same branch. This is not very handy sometimes, though sensible.

I agree that the worktree handling should be improved. There have already been created regarding pending issues.
The initial fatal Git error should be avoided and/or if it happens anyway, it should be emphasized and cancel further actions, e.g. do not attempt to open the new, not created worktree.

**Comment by RussKie** [comment]
@mstv are you able to articulate what a desired fix could be? So that if anyone wants to tackle it they'd know where to start and where to go.

**Comment by mstv** [comment]
Closing, fleshed out in #9165.
