### ISSUE TITLE
Partial graph rendering

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9108]
## Current behaviour

Observed in the latest master and the .NET5 conversion branch:
![image](https://user-images.githubusercontent.com/4403806/115981337-4be7d100-a5d6-11eb-8441-31dc7d509bc7.png)

This appears to happen after any dialog is closed (e.g. interactive rebase) that causes an invalidation of the graph.

v3.5 appears to be immune, so must be a regression from the latest tinkering with the graph. @mstv can you please investigate.

**Comment by mstv** [comment]
Do you have a repro?
It works well for me as long as the submodules are in sync. Else GE hangs often - works much better with #8923.

**Comment by RussKie** [comment]
Not a consistent one. I'll keep my eyes peeled for it.

**Comment by mstv** [comment]
Related to scaling?

In order to rule out that is caused by the "lane straightening", you could set `RevisionGraph._straightenLanesLookAhead = 0`.

**Comment by pmiossec** [comment]
![image](https://user-images.githubusercontent.com/460196/118941348-e9be8980-b951-11eb-80cc-f45c791ffacc.png)

Nodes seems to be there because I get the tooltip when hovered but not drawn.

After scrolling (for trying to see a pattern)

![image](https://user-images.githubusercontent.com/460196/118941533-1f637280-b952-11eb-8557-d832b47e6d21.png)

- Git Extensions 33.33.33
- Build e5c2b99178ab4a76e80ae2a041b37adc27cb2b3b (Dirty)
- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 192dpi (200% scaling)

**Comment by RussKie** [comment]
Yep, that's precisely what I observed. Haven't been able to repro since though

**Comment by pmiossec** [comment]
And it happens in a freshly opened repo without action (rebase,...) done.
So seems to be the git DAG state that causes the display bug.

**Comment by pmiossec** [comment]
I have it in one of our submodule `ICSharpCode.TextEditor`.

Multiple refresh in this gif where we don't get the same result:
![fail_refresh_graphlines_ICSHarpCode TextEdito](https://user-images.githubusercontent.com/460196/119056127-7016b200-b9ca-11eb-917f-6e02bba79b46.gif)

Most of the times, nothing is displayed, 1 or 2 times it is displayed well and some times partially.

@mstv @RussKie Could you have a look if you have the same behavior in this repository?

**Comment by RussKie** [comment]
I can't seem to repro running the latest dev from 3.5 branch... :(

**Comment by mstv** [comment]
> Could you have a look if you have the same behavior in this repository?

Cannot reproduce with the current .NET 5.0 master. I have never seen this. Though I don't use neither scaling nor theming.

**Comment by mstv** [comment]
I can reproduce it by slowing down the loading using:

![grafik](https://user-images.githubusercontent.com/36601201/121092043-455e9300-c7eb-11eb-9fd9-4d45e0ef31bb.png)

The graph rendering can be improved by decreasing `private const int _straightenLanesLookAhead = 20`.
So I must debug the asynchronous updates...
