### ISSUE TITLE
SSH broken after upgrade to 3.5.0 (due to breaking setting change)

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#9112]
## Current behaviour

Any repo for which the remote is set as `git@github.com:....` can no longer communicate with remotes.

## Expected behaviour

That essential settings do not change value in a functionality breaking way when updating to a new minor.

## Steps to reproduce

1. Have GitExtensions 3.4.3
2. In Settings -> SSH -> make sure it is set to PuTTY
3. Have a repo set up with a `git@github.com:...` remote URL and a link to the Private key saved in the settings for the remote repository.
4. Upgrade to GitExtensions 3.5.0.
5. Try to `Fetch all` for the repo and see the below error message.
6. Go to Settings -> SSH and conclude that it is no longer set to PuTTY, but to the `ssh` command in the system `git` directory.
7. Change the setting back to PuTTY to get things working again.

## Screenshots

![image](https://user-images.githubusercontent.com/663378/115997983-71300b80-a5e5-11eb-8907-8930ef90611f.png)

## Did this work in previous version of GitExtensions

Yup, worked fine in 3.4.3.

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 144dpi (150% scaling)

**Comment by gerhardol** [comment]
This should be changed in 3.5 (as well as master)

**Comment by gerhardol** [comment]
I saw the same problem when running the installer. Cannot recreate the problem though.

I did not check the contents in the registry key where ssh setting is stored: Computer\HKEY_CURRENT_USER\SOFTWARE\GitExtensions\gitssh
The path after running the installer is changed to "C:\Program Files (x86)\Git\usr\bin\ssh.exe" 
The Git installation is x64, no 32 bit Git installed.
So the SSH path must be adjusted after running the installer.

Note that the presentation in settings is incorrect, see #9149
OpenSSH and other are mostly handled the same. Before som refactoring, OpenSSH was related to the Git installation dir and always empty, now it is fixed to the Git installation when updating the settings. If you mess with Git installation paths, you have to change OpenSSH too. Should be an OK limitation.

The OpenSSH handling in the installer does not seem to be changed in 3.5

**Comment by jrfnl** [comment]
Thanks for looking into this @gerhardol !

**Comment by gerhardol** [comment]
The problem with SSH presentation in settings(#9149) and that the value is changed at updates exists in 3.4 too,
I am not sure why the SSH changed at upgrades (and repair) is not affecting everyone.

@RussKie The change in ddd46eb3c5b26056a4da72a88de54a81af71e2fa reads the value before writing back. For me this seem to be the issue why the value is changed. Why was it done like that, not just ignoring?

**Comment by jrfnl** [comment]
In case it helps:
I don't know why I didn't notice this when upgrading to 3.4, but I did that upgrade on my previous PC which was still on Windows 7 and using the installer manually.
Since then I switched to a new Windows 10 desktop and have been using Choco on the new desktop. I transferred my settings files etc from my old desktop to my new one.

So for me the differences between the upgrades are: Windows 10 and Chocolatey. I may still have seen the issue at the time, but not reported it, but I honestly can't remember.

**Comment by vbjay** [comment]
The Choco runs defaults unless you pass on arguments.


(
    (
        @(
            lessmsi l -t Feature gitextensionsInstall.msi `
                | ConvertFrom-Csv `
                | Where-Object {$_.Level -gt 1} `
                | ForEach-Object {$_.Feature} `
        ) + 'AddToPath'
    ) | Sort-Object -Unique
) -join ','


I'm sure there are ways to get options too

**Comment by RussKie** [comment]
> The change in [ddd46eb](https://github.com/gitextensions/gitextensions/commit/ddd46eb3c5b26056a4da72a88de54a81af71e2fa) reads the value before writing back. For me this seem to be the issue why the value is changed. Why was it done like that, not just ignoring?

You mean this?
https://github.com/gitextensions/gitextensions/blob/f5c3f229b677a60195353dab0b39191f59cef668/Setup/Product.wxs#L12-L23

It's been awhile obviously, and WiX stuff is arcane... But reading this I can offer the following explanation:
1. Read the value from the registry
2. Set OpenSSH as selected
3. If we have a value from registry and it isn't a `""` - select PuTTY

**Comment by gerhardol** [comment]
> You mean this?

Yes

> 1. Read the value from the registry
> 2. Set OpenSSH as selected
> 3. If we have a value from registry and it isn't a `""` - select PuTTY

For me a 32-bit path is written back so OpenSSH may require tweaking after installation
Part 3. is in conflict with the implementation in 3.4 (or earlier) to store also the OpenSSH path. But this only applies to new installations.

A fixup would be use an empty path (OpenSSH) if the configured path is non existing.
Then users would not be affected.
As the presentation of OpenSSH was set to Other at least in 3.4, this would fix the issue for most users.

**Comment by gerhardol** [comment]
I submitted another PR to use OpenSSH if the path does not exist. 
That should be safe for 3.5, the installer does not have to be changed.
I want #9149 before #9182

**Comment by gerhardol** [comment]
Note that the issue in the installer is not fixed, it is still modified in installation/repair.

But the user issues should still be handled
