### ISSUE TITLE
3.5.0: Create new branch here dialog display issues

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#9115]
Related to #8297, #8491

## Current behaviour

When creating a new branch off a commit where there are multiple branches already, the display is off. (see screenshot)

## Expected behaviour

That the new, extra information is displayed in a readable manner.

To be honest, I would expect the detailed commit information to only be displayed when using CTRL+B / Commands -> Create Branch and to not see this additional information at all when selecting a commit in the revision graph and right clicking "Create new branch here...". In that case, it's just noise as the user has already made a deliberate choice.

## Steps to reproduce

1. Take any commit.
2. Create multiple branches on that same commit.
3. Create yet another branch and see the display being off.

## Screenshots

![image](https://user-images.githubusercontent.com/663378/116028826-4206b200-a658-11eb-9464-0ce2c01c59bc.png)

## Did this work in previous version of GitExtensions

N/A, additional information was added in 3.5.0

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 144dpi (150% scaling)

**Comment by niedworok** [comment]
Additionally, in dark mode, disabled text is rendered black. See attached screenshot.
![2021-04-29 14_20_19-Create branch](https://user-images.githubusercontent.com/7760964/116550092-99c24900-a8f6-11eb-91e2-48f039f00c71.png)

**Comment by gerhardol** [comment]
> Additionally, in dark mode, disabled text is rendered black:

That may be a known bug in WinForms, no known way to verride the text color.

**Comment by RussKie** [comment]
https://github.com/gitextensions/gitextensions/wiki/Dark-Theme#known-issues
