### ISSUE TITLE
3.5.0: Active branch shows as submodule in left panel

### ISSUE THREAD

**Issue by jrfnl** [gitextensions/gitextensions#9118]
## Current behaviour

In a repo which doesn't use submodules, the currently active branch shows as as submodule in the left panel.

## Expected behaviour

For the submodule fold out to either be empty or to not appear at all for repos without submodules.

## Steps to reproduce

1 Check out a branch in any repo
2. Open the Left panel and open the "Submodules" fold out.

## Screenshots

![image](https://user-images.githubusercontent.com/663378/116033927-9adb4800-a662-11eb-825d-ff98b70deb13.png)

## Did this work in previous version of GitExtensions

Can't remember having seen this behaviour before 3.5.0.

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 144dpi (150% scaling)

**Comment by RussKie** [comment]
This is by design, and it has been like this for few releases.

![image](https://user-images.githubusercontent.com/4403806/116034616-ed3e5800-a6a6-11eb-88e3-ba87c049cf05.png)

**Comment by jrfnl** [comment]
@RussKie Fair enough. Only noticed it now and found it confusing, which is why I reported it, but it is not something which bothers me either way.

**Comment by mstv** [comment]
Each of the root nodes can be hidden:
![grafik](https://user-images.githubusercontent.com/36601201/116036137-7e410f00-a666-11eb-9f26-4e9c2028528a.png)
