### ISSUE TITLE
Stash pop is not refreshing the window

### ISSUE THREAD

**Issue by pedrolamas** [gitextensions/gitextensions#9121]
## Current behaviour

The window is not being refresh after a stash pop operation and so still shows the previous stashed code, even when it is not there anymore.

## Expected behaviour

The window should be refreshed after a stash pop operation

## Steps to reproduce

1. Stash some code
2. Observe that the window shows the stashed code with the other commits
3. Do a stash pop directly via menu option on toolbar
4. Observe commits in window

## Did this work in previous version of GitExtensions

Yes, this was working fine just on previous stable version to current 3.5.0.11713

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4341.0
- DPI 192dpi (200% scaling)

**Comment by gerhardol** [comment]
Do you mean the revision graph?

If so, that was introduced with 4b3609f9cf22c7544fb606a016d595562e9d2799
