### ISSUE TITLE
GitExtensions v3.5 fresh install: unable to switch to dark theme

### ISSUE THREAD

**Issue by gimmi** [gitextensions/gitextensions#9134]
## Current behaviour

Upgrading from a previous version with dark theme set -> updated version has dark theme set
Fresh installation -> unable to set dark theme
Fresh portable installation -> unable to set dark theme

**Comment by gimmi** [comment]
Seems that the whole setting editor is broken, here is a repro.

Cotent of file `%APPDATA%\GitExtensions\GitExtensions\GitExtensions.settings`

```xml
<item>
  <key>
    <string>TelemetryEnabled</string>
  </key>
  <value>
    <string>false</string>
  </value>
</item>
```

1. Open GitExtensions
1. Goto Tools -> Settings -> General
    - TelemetryEnabled is false
1. Check TelemetryEnabled to true
1. Click OK
    - GitExtensions close
1. Reopen GitExtensions
1. Goto Tools -> Settings -> General
    - **Expected**: TelemetryEnabled should be true
    - **Actual**: TelemetryEnabled is still false

**Comment by gimmi** [comment]
I've also attached the error that appear on the windows event log: [GitExtensionsError.zip](https://github.com/gitextensions/gitextensions/files/6410977/GitExtensionsError.zip)

**Comment by mstv** [comment]
This is a known installer problem: #9110.
You could use the [most recent installer](https://ci.appveyor.com/api/buildjobs/4uq2yq555xncimet/artifacts/combined.3.5.0.11765-unsigned.zip) built from the `release/3.5` branch.

**Comment by gimmi** [comment]
Confirm working!
