### ISSUE TITLE
SSH Path Locator runs 6 times on startup

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#9138]
## Current behaviour

On startup (with telemetry enabled) the SshPathLocator runs 6 times until the program is running, trough the whole Find() method.

## Expected behaviour
The SSH Path should be stored in an AppSetting or somehow else and if the file exists at the stored location, the SshPathLocator should skip the search part

## Steps to reproduce

set breakpoint to SshPathLocator.Find() and start the app in debug mode

## Did this work in previous version of GitExtensions

no I don't think so

## Environment

- Git Extensions 33.33.33
- Build b64ee60e2b4de1b1ec65a60957cca373a9898c71
- Git 2.29.2.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

which would be the preferred solution and I will prepare a PR for.

**Comment by gerhardol** [comment]
Changed in master as well as release/3.5.1
