### ISSUE TITLE
SshPathLocator should also check Windows Path for ssh location

### ISSUE THREAD

**Issue by thimmy687** [gitextensions/gitextensions#9139]
## Current behaviour

SshPathLocator checks GIT_SSH or git installation folder, but not PATH for ssh.exe

## Expected behaviour

check also PATH for ssh.exe

## Did this work in previous version of GitExtensions

nope

## Environment
latest

**Comment by gerhardol** [comment]
SshPathLocator is no longer used in master as well as release/3.5.1. The path configured in settings/registry is used to set GIT_SSH (env var is never read). For OpenSSH the path is empty. (Same if the path is not configured. OpenSSH will then be used).

Some migration still uses SshPathLocator to clear settings if the path is set to OpenSSH.
Gerrit plugin will probably need changes as it uses GIT_SSH path to make requests. (If ssh.exe is in the path it should still work.)
