### ISSUE TITLE
Allow specifying font name for the console emulator

### ISSUE THREAD

**Issue by dasiths** [gitextensions/gitextensions#9142]
## Allow specifying a font name for the console

We currently support changing the font size in the emulated console. For people using powerline (posh-git + oh-my-posh) like extensions in powershell require a font that supports power line ligatures. (i.e. Cascadia PL).

The current font size setting is here. 
![image](https://user-images.githubusercontent.com/16128850/116893331-3167c480-ac74-11eb-99f2-783929058e85.png)

I propose we introduce a new setting for font name here or use one of the existing settings from 
![image](https://user-images.githubusercontent.com/16128850/116893771-b18e2a00-ac74-11eb-99f2-bddec11dea39.png)

When using the default Consolas font, the console looks like this:
![image](https://user-images.githubusercontent.com/16128850/116893376-3e84b380-ac74-11eb-8723-f92a00f22255.png)

With a supported font it should look like:
![image](https://user-images.githubusercontent.com/16128850/116893902-d4204300-ac74-11eb-8471-860549eecaf8.png)

I've got a PR up in the ConEmuInside repo to get the ball rolling https://github.com/gitextensions/conemu-inside/pull/28

## Environment

- GitExtensions version: 3.4.3.9999
- GIT version:  2.28
- OS version:  Windows 10.0.19041
- .NET version: 4.8.4xxx

**Comment by dasiths** [comment]
This has been now implemented as a part of #9332 and https://github.com/gitextensions/conemu-inside/pull/28

**Comment by RussKie** [comment]
Thank you for the follow up.
