### ISSUE TITLE
Resolve SYSLIB0011 / replace `BinaryFormatter`

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9150]
## Current behaviour

We use the `BinaryFormatter` which is deprecated in .NET 5.0. The obsoletions are currently suppressed with [SYSLIB0011](https://docs.microsoft.com/dotnet/core/compatibility/syslib-warnings/syslib0011), and ultimately must be addressed by replacing the BF with a more appropriate serialiser (e.g. xml, json, etc.).

https://github.com/gitextensions/gitextensions/blob/d488e497cc6244483794abedb8e4779495ba861c/GitCommands/CommitTemplateItem.cs#L93

A cursory look suggest the BF was used in early versions of the app, and exists for a backwards compatibility purposes. A deeper investigation is in order, but very likely it can be just removed.

## Expected behaviour

No `BinaryFormatter` references and no SYSLIB0011 suppressions.

**Comment by GintasS** [comment]
Taking this one.

**Comment by GintasS** [comment]
After a quick investigation, I have found the following:

- 1 concrete instance of BinaryFormatter is being used - CommitTemplateItem.cs Line 93 - Line 96. 
It looks pretty easy to substitute the BinaryFormatter with JsonSerializer, but I found this fella **MoveNamespaceDeserializationBinder** , and not sure what to do
about it. Do we have something like **Binder** or **SerializationBinder** in DataContractJsonSerializer or other JsonSerializer implementations? 
Examples: [Newtonsoft Json Nuget ](https://www.newtonsoft.com/json/help/html/P_Newtonsoft_Json_JsonSerializer_Binder.htm)

```
    BinaryFormatter sf = new() { Binder = new MoveNamespaceDeserializationBinder() };

    public sealed class MoveNamespaceDeserializationBinder : SerializationBinder
    {
        private const string OldNamespace = "GitUI.CommandsDialogs.CommitDialog";
        private const string NewNamespace = "GitCommands";

        public override Type? BindToType(string assemblyName, string typeName)
        {
            typeName = typeName.Replace(OldNamespace, NewNamespace);

            return Type.GetType($"{typeName}, {assemblyName}");
        }
    }
```

- 176 instances of BinaryFormatter word was found, mostly in **.resx** files, so what do we do about these? Just simply remove it/change to JsonSerializer or something else?

![image](https://user-images.githubusercontent.com/20372363/124615942-5946f480-de7e-11eb-9187-0f50616bd68d.png)

Example: ExceptionDetails.resx

```
Note - application/x-microsoft.net.object.binary.base64 is the format 
that the ResXResourceWriter will generate, however the reader can 
read any of the formats listed below.

mimetype: application/x-microsoft.net.object.binary.base64
value   : The object must be serialized with 
        : System.Runtime.Serialization.Formatters.Binary.BinaryFormatter
        : and then encoded with base64 encoding.
```

**Comment by gerhardol** [comment]
I do not have any answers for you, suggest you make a WIP PR with your findings and a suggested path forward

**Comment by RussKie** [comment]
> * 176 instances of BinaryFormatter word was found, mostly in **.resx** files, so what do we do about these? Just simply remove it/change to JsonSerializer or something else?

You can't do anything about these, this must be addressed by the Windows Forms team. 

> * 1 concrete instance of BinaryFormatter is being used - CommitTemplateItem.cs Line 93 - Line 96.

This issue is about removing this instance. 
IIRC my quick high level assessment was that this code was probably added for some kind of backwards compatibility, and it could be completely removed. Do check in the git history though how long ago it was added.

**Comment by GintasS** [comment]
> > * 176 instances of BinaryFormatter word was found, mostly in **.resx** files, so what do we do about these? Just simply remove it/change to JsonSerializer or something else?
> 
> You can't do anything about these, this must be addressed by the Windows Forms team.
> 
> > * 1 concrete instance of BinaryFormatter is being used - CommitTemplateItem.cs Line 93 - Line 96.
> 
> This issue is about removing this instance.
> IIRC my quick high level assessment was that this code was probably added for some kind of backwards compatibility, and it could be completely removed. Do check in the git history though how long ago it was added.

Thanks for the clarification, yes, this code was created 9 years ago. So I guess this can be removed.

![image](https://user-images.githubusercontent.com/20372363/124775003-ee152500-df46-11eb-963d-c6c7e90bfc47.png)

**Comment by pmiossec** [comment]
> Thanks for the clarification, yes, this code was created 9 years ago. So I guess this can be removed.
> 
> ![image](https://user-images.githubusercontent.com/20372363/124775003-ee152500-df46-11eb-963d-c6c7e90bfc47.png)

In fact the important question is not when the code has been introduced but if we have another serialization format and if the data has been migrated.

So I had a quick look in history to see if it is the case and discovered that a **great guy** has already done it years ago:

![image](https://user-images.githubusercontent.com/460196/124777523-8f4cad00-df40-11eb-8f94-1f1e0c05c151.png)

🤣 🤣 🤣 🤣 

So yes, we can just delete the code 😉

**Comment by GintasS** [comment]
> > Thanks for the clarification, yes, this code was created 9 years ago. So I guess this can be removed.
> > ![image](https://user-images.githubusercontent.com/20372363/124775003-ee152500-df46-11eb-963d-c6c7e90bfc47.png)
> 
> In fact the important question is not when the code has been introduced but if we have another serialization format and if the data has been migrated.
> 
> So I had a quick look in history to see if it is the case and discovered that a **great guy** has already done it years ago:
> 
> ![image](https://user-images.githubusercontent.com/460196/124777523-8f4cad00-df40-11eb-8f94-1f1e0c05c151.png)
> 
> 🤣 🤣 🤣 🤣
> 
> So yes, we can just delete the code 😉

I just realized that it was you who done that :D Great job, thanks 👍

**Comment by pmiossec** [comment]
> I just realized that it was you who done that :D Great job, thanks 👍

I just realized also. I don't know/remember why I did that.
The only reason I can think off is that I started the migration to dotnet core 8 years ago 🤣

**Comment by GintasS** [comment]
> > I just realized that it was you who done that :D Great job, thanks 👍
> 
> I just realized also. I don't know/remember why I did that.
> The only reason I can think off is that I started the migration to dotnet core 8 years ago 🤣

But it's so hard to wrap my head that you actually fixed this 8 years ago **and** remembered that then it was relevant :D insane
