### ISSUE TITLE
Use `System.Windows.Forms.TaskDialog`

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9151]
## Current behaviour

Historically we used `Microsoft.WindowsAPICodePack.Dialogs.TaskDialog`, which can now be replaced with [`System.Windows.Forms.TaskDialog`](https://docs.microsoft.com/dotnet/api/system.windows.forms.taskdialog).

**Comment by DmitryZhelnin** [comment]
I can take a look at this
