### ISSUE TITLE
Remove custom `ToHashSet`

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9159]
## Current behaviour

.NET 5.0 has introduced its own [`ToHashSet`](https://docs.microsoft.com/dotnet/api/system.linq.enumerable.tohashset), and our home-made methods can now be removed:
https://github.com/gitextensions/gitextensions/blob/169999f6b241bc256d2a1ebd6f2d851b67e2a3de/GitExtUtils/Linq/LinqExtensions.cs#L12-L17

## Expected behaviour

Use the .NET runtime functionality.

**Comment by GintasS** [comment]
Taking this one.

**Comment by GintasS** [comment]
Hello, 

I've been investigating this issue and found that in .NET 5, **ToHashSet** accepts a **IEqualityComparer**.

So how we should proceed, should we implement **EqualityComparer** for every case or have some general solution, similar like this:
[stackoverflow link](https://stackoverflow.com/questions/98033/wrap-a-delegate-in-an-iequalitycomparer)

Some examples:

**FileStatusList.cs 891 line:**
```
previouslySelectedItems = FileStatusListView.SelectedItems()
    .ToHashSet(i => i.Tag<FileStatusItem>().Item);
```

**GitRef.cs 202 line:**
```
  return refs
      .GroupBy(r => r.Name)
      .Where(group => group.Count() > 1)
      .ToHashSet(e => e.Key);
```

Maybe there is some more easier fix, but I'm not so proficient with IEqualityComparer and generics.

**Comment by GintasS** [comment]
@RussKie what do you think about this?

**Comment by RussKie** [comment]
To be honest I have no idea :)
If you're saying that all our use cases are creating hashsets for string keys, then perhaps we could implement a comparer like suggested in https://stackoverflow.com/a/1239337

A good way to approach the problem would be to write a test for each use case, then apply the comparer and see that tests still pass.

**Comment by drewnoakes** [comment]
You're absolutely right that we should be explicit about the comparer used in each case.

I'd suggest making a static class `StringComparers` that has properties for the different computers we need, where each has a description of the kind of string.

For example:

BranchNames = StringComparer.Ordinal;
RepoFilePath = StringComparer.Ordinal;
LocalFilePath = StringComparer.InvariantIgnoreCase;

We use this pattern in dotnet/project-system and it works well.

**Comment by drewnoakes** [comment]
https://github.com/dotnet/project-system/blob/main/src/Microsoft.VisualStudio.ProjectSystem.Managed/StringComparers.cs

**Comment by GintasS** [comment]
Sorry, don't have time to look just yet, have exams at school, so will take a proper look after the 21st day, if someone else takes this, it is ok, just write here :)

**Comment by NN---** [comment]
What is the exact problem ?
ToHashSet has overload without and with IEqualityComparer as the GE does.
Adding explicit IEqualityComparer is possible but not required.

**Comment by GintasS** [comment]
But I think the more specific overload is used for a reason, to provide this IEqualityComparer? Or do you think the default behaviour is ok for all the cases?

**Comment by NN---** [comment]
What I says is that there is no need to make any change to use ToHashSet from .NET 5.0
