### ISSUE TITLE
Blame view commit tooltip does not handle long commit message well

### ISSUE THREAD

**Issue by RandScullard** [gitextensions/gitextensions#9168]
## Current behaviour

In the Blame view, when you hover the mouse over the commit information in the left panel, a tooltip appears with the details of the commit. If the commit message is very long (with no hard line breaks), this tooltip can be wider than the screen:

## Expected behaviour

The commit message should be word-wrapped to constrain the size of the tooltip.

## Steps to reproduce

Create or locate a commit with a very long commit message with no hard line breaks. Open the File History window and select the Blame tab. Hover the mouse over the left panel of the Blame tab, over top of a line that was modified in this commit. The tooltip will appear. If the commit message is very long, the tooltip will be wider than the screen.

## Screenshots

![image](https://user-images.githubusercontent.com/4718759/117325572-d6de8c00-ae5e-11eb-993b-444750c6937a.png)

## Did this work in previous version of GitExtensions

Unknown. This is the first time I've noticed this behavior.

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 168dpi (175% scaling)

**Comment by vbjay** [comment]
Just an fyi. Read up on the 50/72 rule.

**Comment by RandScullard** [comment]
@vbjay Sure, I'm aware of that rule. For personal projects I don't always follow it. :) Since Git Extensions does such a good job of handling long commit messages everywhere else, I thought it would be good if this tooltip handled them too!

**Comment by stan-ac** [comment]
I get this a lot. 
One of my teammates writes very long text in commits and git extensions regularly hangs for quite a few seconds. 
It would be useful to be able to disable the tooltip as a workaround

**Comment by pmiossec** [comment]
@stan-ac i think that's better to do the same thing than in the revision grid i.e. truncate long lines because indeed windows has some difficulties displaying big tooltip.

And adding a setting won't help a lot because nearly no-one will know it (except maybe you 😉) and will still have the slow down.

 And it will also be difficult to handle because this setting should be global or different for each repository. A mess...

**Comment by pmiossec** [comment]
Oh and a PR is welcome because that should not be difficult as it has already been done in the revision grid...
