### ISSUE TITLE
Left Panel: Jump between tracked branches

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9194]
## Current behaviour

It is hard to select the remote or local branch if they have diverged too much. Only ahead/behind information is displayed.

## Expected behaviour

<kbd>Alt</kbd>+<kbd>Click</kbd> in the Left Panel should select the other branch of a tracking pair both in the Left Panel and in the Revision Grid.
This should also work in combination with the <kbd>Ctrl</kbd> modifier.
Perhaps a context menu item could be added for easier discoverability (as already suggested in another issue).

Though different operations for these click with modifier key(s) were discussed in #8441.
I think toggling local / remove branch is more important than filtering / highlighting. Highlighting could be activated more naturally by clicking the Graph: https://github.com/gitextensions/gitextensions/issues/5782#issuecomment-440427746. (The `LaneInfo` class has already been added.)

**Comment by RussKie** [comment]
> I think toggling local / remove branch is more important than filtering / highlighting.

I disagree on this one. I rarely care about a tracking remote, and if needed I can find it in the left panel. In my everyday life branch highlighting is by miles significantly more important to me.

**Comment by gerhardol** [comment]
I would like to see this

To rebase on upstream master, you have to find that in the left panel, I normally have the local repo expanded

**Comment by RussKie** [comment]
My life is about managing multiple branches and finding which commits
belong to what branches. Findings remotes to rebase on is quite secondary.

**Comment by mstv** [comment]
>  if needed I can find it in the left panel.

Yes, it is *possible* but not really usable.
Regarding branch highlighting, have a look at https://github.com/gitextensions/gitextensions/issues/5782#issuecomment-440427746, please.

**Comment by mstv** [comment]
Draft of main feature implemented in private branch https://github.com/mstv/gitextensions/tree/feature/9194_alt_branch d5057c364346601507cb9fe501c6498b25227268

**Comment by gerhardol** [comment]
PR for Alt-Click in side panel.
Separate behavior could be adapted in RevGrid, to toggle highlight, like in 54ee7057b271fcce29995c9a8a0576857c205a99

**Comment by gerhardol** [comment]
As implemented, no context menu was added.
Also, I would like to have some way to start selecting from the grid. If selecting in the grid, expand in side panel (first branch only). Is hotkey needed?

(This would also give a way to find the mergebase, and if there were a configuration of a favorite "master" branch, It could be added too.)
