### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by HAleksandraR** [gitextensions/gitextensions#9198]
When executing the "gitsync" command, the error "Index was out of range. Must be non-negative and less than the size of the collection." Can you tell me how to fix the error?
Git version 2.21.0
![InkedScreenshot_1_LI](https://user-images.githubusercontent.com/22233635/117919414-645e2800-b306-11eb-8b5b-e76f87b5e9db.jpg)

**Comment by HAleksandraR** [comment]
I have updated git to version 2.31.1. It did not help.
![InkedScreenshot_1_LI](https://user-images.githubusercontent.com/22233635/117921331-00d5f980-b30a-11eb-9299-abf957640052.jpg)

**Comment by RussKie** [comment]
This has nothing to do with this project. 
Report to git.
