### ISSUE TITLE
GE 3.4.3 does not update to 3.5.0

### ISSUE THREAD

**Issue by matyasbach** [gitextensions/gitextensions#9200]
## Current behaviour

GitExtensions haven't automatically updated to new version.
If I try manualy _Help->Check for updates_ response is _No updates found_

GE was installed by exe/msi to _C:\\Program Files (x86)\\GitExtensions\\_ long time ago and has automatically updated several times.

## Expected behaviour

Automatic update

## Did this work in previous version of GitExtensions
I don't remember which version of GE I've installed but I've seen automatic updates (or some notification about new version at least).

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
This is intentional I assume. There were not many issues reported on the RC and few issues reported on 3.5.0 should be fixed.
Some of the issues have PRs wating for a review, some need corrections.
https://github.com/gitextensions/gitextensions/milestone/61

**Comment by RussKie** [comment]
Correct

**Comment by matyasbach** [comment]
Ok, thank you for explanation.
