### ISSUE TITLE
Content gets loaded from unrelated repo???

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9213]
## Current behaviour

I have a long running GE instance, switching between repos back and forth. In a repo I added a blank new README.md, however GE shows me content from a README.md that belong to a different totally unrelated repo (that has previously been opened in this GE instance).

## Steps to reproduce

Not quite sure...

## Screenshots

The unstaged file content is **wrong**! Once stages the content is shown correctly.

![ge-file-content](https://user-images.githubusercontent.com/4403806/118416962-67398e00-b6f5-11eb-93ac-18bfd3e03c05.gif)

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.29.2.windows.2 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Looks like the problem lies here:
![image](https://user-images.githubusercontent.com/4403806/118417981-e3ce6b80-b6f9-11eb-9912-8adc24480b77.png)

...because of how the GE instance was started 
![image](https://user-images.githubusercontent.com/4403806/118418015-08c2de80-b6fa-11eb-8b3c-6bd7d5aa690e.png)

It resolve the file from the current directory, which is "C:\Development\winforms\".

**Comment by gerhardol** [comment]
In this case the File.Exists() in ViewFileAsync() should be removed, the path is already evaluated.

However, if relative filepaths cannot be used, there will likely be a lot more situations than this specific case that do not work.

I can reproduce only when using openrepo argument, so current directory is not set then for unknown reason.
