### ISSUE TITLE
simplify default commit message for merging remote tracking branches

### ISSUE THREAD

**Issue by carlin-q-scott** [gitextensions/gitextensions#9221]
## Feature description
When I merge a remote tracking branch into my current branch, the automatically generated commit message has a lot of extra words in it that are unnecessary and confusing. At least in my opinion.

For instance, I merged origin/main into sandbox, and this is the automatically generated commit message:
> Merge remote tracking branch origin/main into sandbox

This makes sense for me, but as soon as this commit is pushed up to the remote, the message no longer makes sense. From other developer's perspective, I merged main into sandbox. So I think the message should be simplified to:
> Merge main into sandbox

**Comment by RussKie** [comment]
This is git's functionality, you can check it by running the same command from a cli: `git merge --no-ff remote/master`

**Comment by carlin-q-scott** [comment]
Thanks Russ. I have submitted this bug report to the git news group.
