### ISSUE TITLE
RevisionGrid not refreshed correctly after interactive rebase operations

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9223]
## Current behaviour

The RevisionGrid is not refreshed after advanced / interactive rebase operations often.
After `Continue` / `Abort` from the `Rebase is currently in progress` banner, the Revision Graph disappears.

## Expected behaviour

Grid is updated, graph is visible.

## Steps to reproduce

- select the current commit
- navigate to previous
- context menu `Advanced | Edit commit` -> the `Rebase ...` banner appears but the revisions are not updated often 
- `Continue` / `Abort` -> graph disappears

## Screenshots

rows not updated:

![grafik](https://user-images.githubusercontent.com/36601201/118893024-1480f180-b902-11eb-850e-13fe823be12b.png)

OK after `F5`:

![grafik](https://user-images.githubusercontent.com/36601201/118893215-5c077d80-b902-11eb-9daa-b493c87898a6.png)

After `Abort`:

![no graph](https://user-images.githubusercontent.com/36601201/118892377-1dbd8e80-b901-11eb-95e3-3778a8d31d52.png)

## Workaround?

Turn off `FileSystemWatcher` for index

![grafik](https://user-images.githubusercontent.com/36601201/118893900-7f7ef800-b903-11eb-834d-2994c2e28e76.png)

## Did this work in previous version of GitExtensions

at least not for months

## Environment

- Git Extensions 3.6.0.11771
- Build 43a5e53eb416870cd4d1d64e3a56a71c55e9733b (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
I'm on 3f4ed21998af4cb8bd5e105c5c93943d94ec4ca9 (last commit before .net 5 PR merged) and I just noticed thing strange behavior but not consistent.

On one repo, just a refresh with 'F5' make it disappear (scrolling make it appears):
![fail_refresh_graphlines](https://user-images.githubusercontent.com/460196/118895757-113c3480-b907-11eb-8dbe-babdc480c2e7.gif)

>Workaround
>Turn off FileSystemWatcher for index

I don't have it enabled and have the issue.

I don't think I made a rebase (but not sure)

**Comment by mstv** [comment]
> I don't have it enabled and have the issue.
I don't think I made a rebase (but not sure)

So you can reproduce #9108.

**Comment by pmiossec** [comment]
> 
> 
> > I don't have it enabled and have the issue.
> > I don't think I made a rebase (but not sure)
> 
> So you can reproduce #9108.

Yes. I have an enterprise repository that is in this state. But I don't understand why. I will a little more information in #9108

**Comment by gerhardol** [comment]
FileSystemWatcher only affects the icon since #9871, so that is out of the discussion

In addition to the missing revision graph, the revision rows may be completely empty, no data at all.
I got that problem very often at one point, today I cannot get that result.

To recreate the problem, I made a simple patch to get the banner appear:
```
diff --git a/GitUI/UserControls/InteractiveGitActionControl.cs b/GitUI/UserControls/InteractiveGitActionControl.cs
index 57dd0..ba9797 100644
--- a/GitUI/UserControls/InteractiveGitActionControl.cs
+++ b/GitUI/UserControls/InteractiveGitActionControl.cs
@@ -61,6 +61,8 @@ public void RefreshBisect()
             SetGitAction(GitAction.None, false);
         }
 
+        private int _ttt = 0;
+
         public void RefreshGitAction()
         {
             // get the current state of the repo
@@ -83,7 +85,7 @@ public void RefreshGitAction()
                 hasConflicts = false;
             }
 
-            if (Module.InTheMiddleOfRebase())
+            if (++_ttt % 2 == 0 || Module.InTheMiddleOfRebase())
             {
                 SetGitAction(GitAction.Rebase, hasConflicts);
                 return;
```

The problem occasionally appears after selecting continue in the banner.
I cannot recreate with only running a FormProcess command or just refreshing/reactivating GE. It has to be running FormProcess and hiding the banner.
If the rev graph is missing, it reappears when showing the banner again (just select something outside the window, then click in GE again).

From what I can see the revision grid rows are updated correctly, it is just a display issue. But using debugger break affect the execution, I have not dumped data or so to check the status.

I would expect that this is related to a race condition when refreshing that is invoked as "repo changed notification" and the OnActivate() call to hide or show the banner.

**Comment by gerhardol** [comment]
The problem seem to be that OnActivated() is called 2-3 times in a short timespan:
* When GE is reactivated (partly in my test, not always in real scenarios).
* After FormProcess ends. This is required, the command may change the status.
* In RefreshRevisions()->InternalInitialize(). Required only if there has been other changes, but not after FormProcess.

(Increasing the force reactivate above from 3 to 5 in the mod above). 

The calls are not overlapping normally, the problem occurs anyway.

One raw fix is to skip InternalInitialize()->OnActivate once in some specific situations (like after FormProcess), when OnActivate() is known to run explicitly, or rate limit the call.
Very crude fixes though.

**Comment by gerhardol** [comment]
If the rev graph column is not shown, scrolling will show it.
If rev grid is blank, refresh is required.

#9948 fixes this in most situations for me, but occasionally the rev graph is still not shown. (#9948 is needed for other reasons too.)
#10001 seem to work though for me, I cannot see why running the Git commands causes this problem though.

It seem to be possible to remove RefreshRevisions()->InternalInitialize()-OnActivate(), the state should be resolved by FormProcess.
But removing the call does not seem to make any change, not done now.

**Comment by RussKie** [comment]
In one of the latest builds the issue appears to get worse - I got the blank screen after an interactive rebase with conflicts:

![image](https://user-images.githubusercontent.com/4403806/172966870-4e4602f5-83a8-42d2-92c2-798b565b1c42.png)



- Git Extensions 4.0.0.13810
- Build e24f413df662916de79ecec7da1bae41e1dec15b (Dirty)
- Git 2.36.0.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.5
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
There is something related to timing here, so any (unrelated) change can improve/make it worse.
#10001 improves for me, but the tests fail.

**Comment by gerhardol** [comment]
This seem to be handled in [#11268 ](https://github.com/gitextensions/gitextensions/pull/11268#issuecomment-1773904803)

**Comment by gerhardol** [comment]
I see the same behavior with #11481

**Comment by mstv** [comment]
> I see the same behavior with https://github.com/gitextensions/gitextensions/pull/11481

GH seems to close every issue which is mentioned with "fix" in the same line. 👎
