### ISSUE TITLE
Bunch of new git commands to support 

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#9225]
I think that there are new git commands that we could support (don't forget to click on 'generate new' 😁) :

https://git-man-page-generator.lokaltog.net/#aHVnJCRvcHRpb24=
https://git-man-page-generator.lokaltog.net/#c3RyYW5nbGUkJEhFQUQ=

**Comment by MrJithil** [comment]
Can I work on this?

**Comment by gerhardol** [comment]
> Can I work on this?

It is 51 days too late...

There are better items to get started with.

**Comment by pmiossec** [comment]
I'm sorry if that was not clear enough (because I would like people to be surprised when opening the links) but this website is a joke on git documentation that are not always clear for a lot of users that didn't know how git works internally.

So this was a joke issue mostly for development team :D

There is nothing to do here and this issue could be closed.

**Comment by RussKie** [comment]
🤣
