### ISSUE TITLE
"Reset file to" stopped showing previous commit hash and gets stuck on reset action

### ISSUE THREAD

**Issue by Nir-Az** [gitextensions/gitextensions#9234]
## Current behaviour
When I have unstaged files and I want to unstaged them, I right click on the file and select "reset file to" -> first commit index.
On latest version it doesn't work.
No hash ID of the first commit is displayed
If I click on " First commit" the operation get's stuck and the index.lock file is remain open.
I must restart my PC in order to delete it.

## Expected behaviour
The first commit should show the commir hash and the operation should work and unstage the files

## Steps to reproduce

1. Create changes on files
2. Right click on the file on the "Diff" tab and choose "reset file to: -> First commit"

## Screenshots

![image](https://user-images.githubusercontent.com/64067618/119464197-2cfe6b00-bd4b-11eb-9cea-fb165ca18957.png)

## Did this work in previous version of GitExtensions

Yes (Not sure what version I had installed before)

## Environment

Windows 10
- GitExtensions version: 2.5.0.11713
- GIT version:  2.26.1
- OS version: 10
- .NET version:  4.8.4300.0

**Comment by gerhardol** [comment]
Assuming this is 3.5.0.11713
Use the copy feature in About to get all required data

To unstage/stage file for the "artificial commits" worktree/index use the dedicated options.

When selecting a file in Work tree ("unstaged"), then Index ("staged") is the parent, the parent to Index has not been available there (maybe Worktree was not excluded in some older versions, that was an error).

> The first commit should show the commir hash and the operation should work and unstage the files

No, the HEAD is not a direct parent to work tree, it would be confusing to have that as a standard feature.
There are enough special handling for artificial commits already, there has been quite some changes here already. To have special HEAD would be another special case.
Select the Index instead.

Resetting to commit works for me.
Check the Git command log for Git error messages. index.lock may be locked if Git fails, especially if several Git instances are running on the same repo.

**Comment by Nir-Az** [comment]
- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.26.1.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)


Not sure I understand,

How do I unstage a specific file?
What is the "dedicated option" if not "reset file to"?

i.e:
![image](https://user-images.githubusercontent.com/64067618/119496416-23d1c600-bd6c-11eb-8c1c-e78082444848.png)

**Comment by RussKie** [comment]
I think you are mixing up "unstage" and "reset" concepts. The former is to
remove from index, the latter is undo pending changes.

**Comment by pmiossec** [comment]
> How do I unstage a specific file?
> What is the "dedicated option" if not "reset file to"?
> 
> i.e:
> ![image](https://user-images.githubusercontent.com/64067618/119496416-23d1c600-bd6c-11eb-8c1c-e78082444848.png)

You are showing a screen shot of a not staged file so that is normal to not see the option.

Staging a file is possible when 'working directory' is selected with 'stage file(s)' item in the contextual menu (that you show in your screenshot).

Unstaging a file is possible when 'Commit index' is selected with contextual menu also on an already staged file. 

Ps: you could still use the 'commit' form to stage/unstage files.

**Comment by Nir-Az** [comment]
Sorry for the mix, my question was wrong.
I meant how do I revert pending changes of a file (which is in an unstage state), the UI action that will actually do "git checkout <path-to-file>"
I used to choose "reset file to" and it worked.
Is there a way to do it?

**Comment by gerhardol** [comment]
Reset file to Index works for me for Worktree, if the file is staged, Reset to HEAD-commit works too for Index files.

**Comment by Nir-Az** [comment]
Sometime it works, and sometime it gets stuck with the index.lock file open.
Only PC restart works.
This is a regression since it never happened to me on previous versions

**Comment by pmiossec** [comment]
> Sometime it works, and sometime it gets stuck with the index.lock file open.


I don't understand what you mean with "stuck with the index.lock file open.". Could you provide a screen shot?

**Comment by gerhardol** [comment]
> Sometime it works, and sometime it gets stuck with the index.lock file open.
> Only PC restart works.
> This is a regression since it never happened to me on previous versions

That is Git locking the file, not handled directly by GE (except offering to delete the file recursively).
So the only way this is a regression is that commands are issued in some other way.
You need to supply at least the GE command logs and similar for other application that may use Git when the problem occurs.
