### ISSUE TITLE
Windows OS version 'Windows 10 Enterprise 2015 LTSB' is not supporting GIT Extensions

### ISSUE THREAD

**Issue by jee-kr** [gitextensions/gitextensions#9236]
## Current behaviour

GIT Extensions is not working on my system. It looks like Windows OS version 'Windows 10 Enterprise 2015 LTSB' is not supporting GIT Extensions.

## Expected behaviour

Git Extensions should work seamlessly.

## Steps to reproduce

- Open Git Extensions
- Go to Clone Repository
- Fill Repository to Clone
- Click on the drop down Branch
- A warning message as given below will be shown
 "This application requires one of the following versions of the .NET Framework:
.NET Framework, version = v4.7.2
Do you want to install this .NET Framework version now ?

- Click on the option Yes
- Try to download .NET Framework version 4.7.2
- Setup failed message was shown. It also mentions the following.
"Microsoft .NET Framework 4.7.2 developer pack is not supported on this Operating System.

## Screenshots

![image](https://user-images.githubusercontent.com/34304818/119605682-d5293800-be0e-11eb-9363-e2c5e64c1886.png)

![image](https://user-images.githubusercontent.com/34304818/119605537-98f5d780-be0e-11eb-8fcb-3eb667654ad7.png)

![image](https://user-images.githubusercontent.com/34304818/119605603-b460e280-be0e-11eb-8c05-ec797cdfb995.png)

![image](https://user-images.githubusercontent.com/34304818/119605387-56cc9600-be0e-11eb-8cbe-f44ea3436fea.png)

## Environment

- GitExtensions version: 3.5.0.11713
- GIT version: 2.3.1.windows.1
- OS version: Microsoft Windows NT 10.0.10240.0
- .NET version: .NET Framework 4.6.1810.0

**Comment by pmiossec** [comment]
From what you show, that's not a GitExtensions problem.
That's a problem between your OS and the version of Git you installed that requires .net fwk 4.2 for the credential manager.

Things you could try:
* install v4. 2 through the 'add and remove programs'
* install the last version of Git where the credential manager use dotnet core

**Comment by RussKie** [comment]
Git Extensions v3.x are built against .NET Framework 4.6.1.  This is what
you need to have installed in order to run the app.
