### ISSUE TITLE
Some configuration buttons do not work

### ISSUE THREAD

**Issue by sylvain-bougnoux** [gitextensions/gitextensions#9257]
## Current behaviour

In setting panels, main GitExtensions tab, there should be green items (right panel). But as you know, these items are button for fixing or adapting some options. When clicking on some buttons, eg  merge & diff tool, nothing happen !

## Expected behaviour

open the option panel of related tool. Some work, like language.

## Did this work in previous version of GitExtensions

Yes but I don't remember which one

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4341.0
- DPI 106dpi (110% scaling)

**Comment by RussKie** [comment]
I'm afraid I can't understand what the issue is. Please try to restate the issue and provide screenshots/animations clearly showing the issue.

**Comment by sylvain-bougnoux** [comment]
In the following each green or red rectangle is a button. When I click on some of them, for instance here "diff tool", nothing happens, same for repair button, same for "mergetool". Clicking on some other like "language" works.
 
![image](https://user-images.githubusercontent.com/6706662/120975908-135d1a80-c772-11eb-93d2-ab3711e92389.png)

Maybe it is because the configuration for diff & merge are now at a different location ?
But I do think it is quite confusing.

**Comment by gerhardol** [comment]
user/email, difftool and mergetool takes me to the settings page (Git/Config). Those settings requires some interaction.
SSH presented properly in next relase (3.5 and master)

So OK for me
