### ISSUE TITLE
Help for alternative merge-strategy is closed to fast 

### ISSUE THREAD

**Issue by TobiasSekan** [gitextensions/gitextensions#9259]
## Current behaviour

The very big tool-tip for the alternative merge-strategy is closed after 4 or 5 seconds.

## Expected behaviour
Don't automatic close the tool tip
or increase the auto-close time
or find a better presentation for the many information (like a extra window).

## Steps to reproduce
1. Merge to braches
2. Activate `Alternative options`
2. Activate `Use alternative Merge strategy`
3. Hover over the `Help` link

## Screenshots

![bla](https://user-images.githubusercontent.com/17874713/120775801-d865a780-c523-11eb-857d-d43cdbb7c0b0.png)

![2021-06-04 11_00_41-](https://user-images.githubusercontent.com/17874713/120776340-6b9edd00-c524-11eb-9d63-afc31d62aace.png)

## Did this work in previous version of GitExtensions

No

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
@TobiasSekan here's the tooltip's text: 
https://github.com/gitextensions/gitextensions/blob/41abe9d9c3719845dd0407262c0c5da98fb65af9/GitUI/Translation/German.xlf#L6206-L6256

The fix will be to move this information into the docs, and have the help button `[?]`, which points to the docs.
