### ISSUE TITLE
Several instances are lauched

### ISSUE THREAD

**Issue by mesteves** [gitextensions/gitextensions#9260]
## Current behaviour
Git Extensions to open as usual without multiple instances causing CPU to reach 100 %

## Expected behaviour
Git Extensions to open as normally and be able to work with branched

## Steps to reproduce
Install Git
Install Git Extensions
Launch Git Extensions

## Screenshots
![image](https://user-images.githubusercontent.com/3369185/120784620-2da1b900-c524-11eb-9307-a0d49b5e3b44.png)

* Altough my machine is 64 bits is the process list it is showing 32 bit, don't know why. I used this installer "GitExtensions-3.4.3.9999-d4b0f48bb.msi". I have also tried the latest version - GitExtensions-3.5.0.11713-0a5ef9ca6.msi but the same thing happens.

## Did this work in previous version of GitExtensions
It worked, but I had some troubles on my machine and I can't tell which versions I had installed

## Environment

- GitExtensions version: 3.4.3.9999
- GIT version: 2.31.1
- OS version: Win 10
- .NET version: 
![image](https://user-images.githubusercontent.com/3369185/120784943-8709e800-c524-11eb-989b-cfce451aefcb.png)

**Comment by gerhardol** [comment]
GE is 32 bit
Use copy in About to get relevat .NET info
I have not heard of multiple versions launching like this. How do you start GE?

**Comment by mesteves** [comment]
Hi,

Usually I have a shortcut on my desktop pointing to "C:\Program Files (x86)\GitExtensions\GitExtensions.exe". 

If I launch from there, the same thing happens.

"Use copy in About to get relevant .NET info" - from where ? GE ? It doesn't even launch the app... 

I hate using GIT in Visual Studio :(

Hope you can guide me pointing more directions.

Thanks.

**Comment by gerhardol** [comment]
GE 3.x uses .NET 4.6.1
(master uses .NET5 but a lot of functionality is not there yet)

**Comment by mesteves** [comment]
Hi .NET 4.61 is installed.

I've then tried uninstall and install everything (git / GE) back and same thing happens :(


<img width="239" alt="Captura de ecrã 2021-06-15 120418" src="https://user-images.githubusercontent.com/3369185/122042259-d4fad780-cdd1-11eb-8aff-966d76690a93.png">

Is there a way to know what is triggering all those GE instances ? 

Best regards,
Manuel

**Comment by gerhardol** [comment]
The only spawn itself that is in the GE code is when opening a submodule or file history from within the app. That is triggered manually, nothing like this.
Can you run Process Explorer to try find what is opening the instances?
https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by pmiossec** [comment]
> Can you run Process Explorer to try find what is opening the instances?
> https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

:+1:  And it also could be interesting to report here the command lines of the instances launched (still using Process Explorer) like: 

![image](https://user-images.githubusercontent.com/460196/122054858-5bbaaf00-cde8-11eb-869e-9846951cc809.png)

**Comment by mesteves** [comment]
Hi,

I've installed procmon and here is the result. I've tried to install several versions of git/gitextensions (32/64bits) but the result is always the same:

**From task explorer:**

![image](https://user-images.githubusercontent.com/3369185/123428547-d4c2bf00-d5bd-11eb-9278-91362b06bc80.png)

**From Procmon:**

![image](https://user-images.githubusercontent.com/3369185/123428607-e7d58f00-d5bd-11eb-92e9-f2556f674d25.png)

I'm desperate!!!! 

What could it be ? 

Best regards,
Manuel

**Comment by pmiossec** [comment]
@mesteves As previously requested, could you give us the command line of the first and second instance of GitExtensions launched using process explorer?

You could display it with the tooltip by hovering the process but to copy/paste here, that's easier to open "properties":
![image](https://user-images.githubusercontent.com/460196/123430026-f759d580-d5c7-11eb-9c85-1dd9c3a7ab4b.png)
then it's in "Image" tab:

![image](https://user-images.githubusercontent.com/460196/123430163-240ded00-d5c8-11eb-8976-d9030a032ad8.png)

**Comment by mstv** [comment]
@mesteves, how do you start GE? From Start Menu or from context menu in Explorer or ...?

As an alternative, you could unzip the portable archive and double click the `GitExtensions.exe`.

**Comment by mesteves** [comment]
Hi @pmiossec every instance of GE doesn't have any kind of additional paramenter as shown on the pictures via task explorer or procmon. I launch GE via shortcut that points directly to the GE folder (the .exe file)

Target: "C:\Program Files (x86)\GitExtensions\GitExtensions.exe"

Anyway this is the properties window that you asked. I use VS no VS Code.

![image](https://user-images.githubusercontent.com/3369185/123605284-90206900-d7f3-11eb-97e4-d5c08e5d64b0.png)


@mstv I'll try the portable version also.

Regards and thanks for all the help so far and any additional info.

Manuel

**Comment by vbjay** [comment]
Git extensions process. Not other processes.

**Comment by pmiossec** [comment]
@mesteves I'm sorry, I didn't see that the command line was displayed for every instance in a column. So you already answered my request...

 >Anyway this is the properties window that you asked. I use VS no VS Code.

I was requesting it for GitExtensions and give VSCode as an example ;)

But now that I see that you have VS, I think that the easier to debug this strange behavior not already seen before, is to debug the GitExtensions source code...

**Comment by mesteves** [comment]
Hi @pmiossec Thanks for the feedback.

I would be interested in doing that debug. Is there any guide how that helps how to do that ? I would like to understand and resolve this.

In the meantime with portable edition, it works, although some things are missing, like contextual menus in explorer that for me are handy.

Regards,
Manuel

**Comment by RussKie** [comment]
@mesteves please read https://github.com/gitextensions/gitextensions/wiki/How-To:-build-instructions
