### ISSUE TITLE
Advanced !fixup commits no longer automatically reorder in v3.5

### ISSUE THREAD

**Issue by jfisher993** [gitextensions/gitextensions#9263]
Create a !fixup commit through the advanced panel:
![image](https://user-images.githubusercontent.com/10456662/120818056-40b28a00-c520-11eb-8c5d-6ee1315b0d22.png)

Then rebase interactively.

Notice the !fixup commit doesn't automatically move, and you have to manually move the !fixup commit. In versions prior to 3.5 the !fixup commit would automatically move, making this a really helpful feature. Now this is only a somewhat helpful feature. 

Is this a bug in 3.5 or intended functionality? Is there a setting to enable the old functionality?

**Comment by gerhardol** [comment]
That has not been changed what I know, I use it daily
Have you unselected autosquash?
![image](https://user-images.githubusercontent.com/6248932/120826948-3c579280-c55b-11eb-85ec-112215b4a029.png)

**Comment by jfisher993** [comment]
@gerhardol AFAIK there is no setting to Autosquash when using the second option on this list:

![image](https://user-images.githubusercontent.com/10456662/120828564-ac015980-c52a-11eb-8112-d39b225c7172.png)

You used the 3rd option I believe. Prior to v3.5 the default behavior was autosquash with the second option.

**Comment by mstv** [comment]
> AFAIK there is no setting to Autosquash when using the second option on this list:

I guess, one must activate `Autosquash` in the advanced dialog once (and then hope that this setting is stored, which is an issue when running multiple instances of GE).

**Comment by jfisher993** [comment]
@mstv A good thought, but it was not getting stored for me when I tried.

**Comment by mstv** [comment]
Since I run the same GE build on different machines, it might be caused by git. I have this regressed behavior on a PC with git 2.31.1.

**Comment by jfisher993** [comment]
@mstv Great point! Definitely caused by a GIT update.

Doing `git config --global rebase.autosquash true` resolves the issue. Closing this. Thanks!

**Comment by mstv** [comment]
@jfisher993, thank you for sharing the solution.

**Comment by RussKie** [comment]
I'm setting a new workstation, and this had me stumble for a hour.

I can't think of a good way to make it easy or obvious... May be we should add the following text when we opening _our_ editor?
![image](https://user-images.githubusercontent.com/4403806/124288531-a122fe80-db94-11eb-9ae6-69a2cf963b97.png)

**Comment by gerhardol** [comment]
> I'm setting a new workstation, and this had me stumble for a hour.
> 
> I can't think of a good way to make it easy or obvious... May be we should add the following text when we opening _our_ editor?

This could be a separate option - but there are already too many configuration options.

How to insert the GE special message?
Hardcode on filename?

**Comment by MattLichter** [comment]
Thanks @jfisher993 !  Nice seeing you here!

**Comment by RussKie** [comment]
I've been setting yet another new workstation, and stepped on this yet again. I think it is a problem that whenever a user runs the interactive rebase `rebase.autosquash` isn't getting set to `true` for the duration of the operation.

**Comment by gerhardol** [comment]
> I've been setting yet another new workstation, and stepped on this yet again. I think it is a problem that whenever a user runs the interactive rebase `rebase.autosquash` isn't getting set to `true` for the duration of the operation.

This should be an option in Settings - Git - Advanced
