### ISSUE TITLE
Repair Translation Check

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9273]
The translation check has regressed again: fails, if the master has newer translations.

STR:

- PR with translation change
- concurrent merge with translation change to `master`
- build PR

**Comment by RussKie** [comment]
I'll have a look

**Comment by RussKie** [comment]
I need a repro, if you see one please let me know.

**Comment by RussKie** [comment]
Got a repro https://github.com/gitextensions/gitextensions/commit/f5c663c92357a1673357d7a90d5a32c1546ab6ea

Here's what's happening:
1. The master has a changed translation, when we perform a soft reset the index it contains xlf files:
![image](https://user-images.githubusercontent.com/4403806/125015340-ac08f200-e0b2-11eb-918f-97228f074f84.png)
2. Then we build and run the loc check, which detects the changed xlf

In 3.5 branch we would
1. Reset
2. Build
3. Undo reset
4. Run loc check

**Comment by mstv** [comment]
I think you should have a look at the code removed (again) from `appveyor.yml` in 3eea46688b0398557f0a8423f48c4fb4d95c9ad2.
It did/does only work this way.

**Comment by RussKie** [comment]
Tested in https://ci.appveyor.com/project/gitextensions/gitextensions/builds/39945061
