### ISSUE TITLE
Saving settings crash when no repo is opened

### ISSUE THREAD

**Issue by pmiossec** [gitextensions/gitextensions#9275]
## Current behaviour

1. If **there is no repository open**
2. and you open the settings
3. and you select a page having multiple settings source (like Revision links, Build server integration, Detailed or plugins settings):
![image](https://user-images.githubusercontent.com/460196/121196476-ce6bdd80-c870-11eb-8155-6483fd1149a0.png)
4. and you  modify and save a settings when the "Settings source" is not "Global for all the repositories"
5. then you have an exception "Value must not be null."
![image](https://user-images.githubusercontent.com/460196/121202528-a59a1700-c875-11eb-8505-9511f6bf794d.png)

Like https://github.com/gitextensions/gitextensions/issues/8396#issuecomment-856769554 said, it could the explanation of #8396 (and some others duplicate closed)

## Expected behaviour

Either hide all the settings page having these "setting source " option if a repo is not open
or select "Global for all the repositories" in this case and not allow the user to change it.

## Steps to reproduce

See ## Current behavior

## Did this work in previous version of GitExtensions

Don't think so...

## Environment

- Git Extensions 33.33.33
- Build e5c2b99178ab4a76e80ae2a041b37adc27cb2b3b (Dirty)
- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 192dpi (200% scaling)

## Diagnostics

The reason is that all the settings source except "Global for all the repositories" try to save the setting in the repository folder.

**Comment by gerhardol** [comment]
Please include the info in Report bug too, with the stacktrace
