### ISSUE TITLE
Delete branch: Merged into detached head not recognized

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9279]
The - IMO arbitrary - check for merged into the current checkout does not work correctly for detached head - also before this PR:

![grafik](https://user-images.githubusercontent.com/36601201/121590374-8ac3d000-ca38-11eb-8e2f-e2cc832dde2b.png)

This is a GE bug because git deletes the branch without forcing.

```
M@M  /d/Build/gitextensions3_dev ((e5d6cdd13...))
$ git branch --merged
* (HEAD detached at e5d6cdd13)
  7795_process_start
  fix/6527_git_errors_prep2
  fix/9192_list_selections
  fix/toolbar_icon_switch
  fix_9104_stage-unstage_woes
  master
  x

M@M  /d/Build/gitextensions3_dev ((e5d6cdd13...))
$ git branch -d x
Deleted branch x (was 8f6541e5b).
```

It works if a branch is checked out.

Regardless of this, I want (a [hidden] setting for having) `force delete` on by default.

_Originally posted by @mstv in https://github.com/gitextensions/gitextensions/issues/9254#issuecomment-859025925_

**Comment by mstv** [comment]
> Regardless of this, I want (a [hidden] setting for having) force delete on by default.

And I don't want to be bothered by a TaskDialog when committing to a detached head.
Two new checkboxes in `Advanced` | `Confirmations`?

**Comment by RussKie** [comment]
Aye

**Comment by pmiossec** [comment]
> > Regardless of this, I want (a [hidden] setting for having) force delete on by default.
> 
> And I don't want to be bothered by a TaskDialog when committing to a detached head.

I always found this behavior boring and expect to change it one.

What I imagined was to be able to check if what we want to delete requires a `--force` and in this case disable the 'delete' button. Then the only way to enable the button and delete the branch(s) would be to check 'force' checkbox.

But I don't know if a git command could allow us to know that (if that helps: https://stackoverflow.com/a/227026/717372 )

That way the user get the information before and avoid the frustrating error after.

And that way we also keep the little warning 'you will probably do an error if you click this check box' (and we could even display a message about the reflog when the checkbox is checked) that will be removed if we add these 'force delete' settings.

Do you think it is possible to do that?

**Comment by mstv** [comment]
> Do you think it is possible to do that?

Yes, this better UX should be feasible. Our parsing of the `git branch --merged` (see description) must just support detached head, too.

**Comment by mstv** [comment]
> Our parsing of the git branch --merged (see description) must just support detached head, too.

This seems to be denied by design.

Furthermore, GE's naive detection does not check whether the local branch is ahead the remote branch. Then git expects `--force`, too.
