### ISSUE TITLE
Broken hunks stage/unstage for new files

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9280]
## Current behaviour

It is not possible to stage/unstage selected lines for new files.

## Expected behaviour

It is possible to stage/unstage selected lines for new files.

## Steps to reproduce

1. Create a new file with content
2. Select few lines and try to stage
    \- or -
Stage the file, select few lines and try to unstage

## Screenshots

![image](https://user-images.githubusercontent.com/4403806/121639089-60712180-cacf-11eb-8ec4-d1c8118484c9.png)

## Did this work in previous version of GitExtensions

Yes, 3.4
![image](https://user-images.githubusercontent.com/4403806/121639381-cc538a00-cacf-11eb-879c-8524442e3a6a.png)

## Environment

- Git Extensions 3.5.0.11713
- Build 0a5ef9ca6ce87754a510aa02c7a96d8b915714ac (Dirty)
- Git 2.29.2.windows.2 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4300.0
- DPI 96dpi (no scaling)

**Comment by mdonatas** [comment]
Just wanted to point out that this is still broken in master branch. Sorry if there's already an issue for it, couldn't find it at a glance.

**Comment by gerhardol** [comment]
> Just wanted to point out that this is still broken in master branch. Sorry if there's already an issue for it, couldn't find it at a glance.

A few other changes to release-3.5 need to be added to master too, so this is known.
Only one issue, twice the job.
(Trivial changes are added to master first, then just pushed to release-3.5 with cherry-pick references, but there are quite a lot of changes in master now.)
