### ISSUE TITLE
Comprehensive fix of misspellings/typos

### ISSUE THREAD

**Issue by JosefPihrt** [gitextensions/gitextensions#9292]
Hi,

I would like to contribute with a comprehensive fix of misspellings/typos in this project.

I developed tools specially for this purpose: [Roslynator](https://www.nuget.org/packages/Roslynator.CommandLine) (for code files), [Orang](https://www.nuget.org/packages/Orang.DotNet.Cli) (for text files), [Wordb](https://github.com/josefpihrt/wordb) (wordlists)

I can fix following parts of the solution:
* Non-code files (Markdown and similar text files)
* Code files (C# files)
  * Comments
  * Symbols (type/member names)
    * Symbols that can be renamed without causing a breaking change
    * Symbols that have been shipped as a part of public API/library

### Questions
* Are you interested?
* Should US or British (or both) English be preferred?
* Which parts mentioned above should be included?
* Which projects are part of public API/library? (This question is relevant if the symbols should be spellchecked)
  * Should publicly visible symbols be spellchecked anyway but in the separate PR?

**Comment by RussKie** [comment]
> * Are you interested?

Yes :)

> * Should US or British (or both) English be preferred?

That's a tough one. We have contributors from all over the world, so various versions and flavours of English are used. I'd go with "s" over "z". @gitextensions/git-extensions-team what are your preferences, folks?

> * Which parts mentioned above should be included?

I'd start with non-code (i.e. docs, comments, etc.) changes first. Then we could look at getting the API fixed.
Please be mindful of the size of incoming PRs, it's easy to review one-two dozens of files, but gets exponentially harder to review hundreds of changed files.

> * Which projects are part of public API/library? (This question is relevant if the symbols should be spellchecked)

I don't think any non public API changes would be a problem. For public API we'd need to review on a case-by-case basis. We've recently undergone [the same exercise](https://github.com/dotnet/winforms/pulls?q=author%3Ajsoref) in https://github.com/dotnet/winforms.

**Comment by gerhardol** [comment]
It is easier to discuss over a PR, if it is not too hard to make a WIP PR for discussion, it is easier.

> > * Should US or British (or both) English be preferred?
> 
> That's a tough one. We have contributors from all over the world, so various versions and flavours of English are used. I'd go with "s" over "z". @gitextensions/git-extensions-team what are your preferences, folks?

I would like to go with US English, as that is used in most software and companies from what I see.
(I learned BE originally and without spellcheck I would write colour over color but most new concepts are written with US so that is easier.)
