### ISSUE TITLE
Enabled/disabled text colours are backwards in dark mode

### ISSUE THREAD

**Issue by luweeewu** [gitextensions/gitextensions#9294]
In dark mode, the text colours are the reverse of what is expected for enabled and disabled buttons, etc.

## Current behaviour

In dark mode, the text on enabled buttons, etc. is grey, while text on enabled buttons, etc. is black.

## Expected behaviour

Enabled buttons, etc. should have black text (on a light background or white text on a dark background), while disabled buttons, etc. should have grey text.

## Steps to reproduce

1. Set the UI to display in one of the dark modes.
2. Open one of the pop-ups (Commit, Manage Stashes, etc.)
Notice the colour of the text on the enabled and disabled buttons, etc..

## Screenshots

This is a screen shot of the buttons in the Manage Stashes pop-up. The Stash selected changes button is disabled, while everything else is enabled. Due to the colours, though, it looks like the Stash selected changes button is enabled, and the other 3 buttons are disabled.
![image](https://user-images.githubusercontent.com/4983340/122475514-9d2e9400-cf79-11eb-96b0-0bdef8e36ae5.png)

## Did this work in previous version of GitExtensions

I have no idea whether or not this worked in previous versions, as I have only just put my GitExtensions UI into dark mode yesterday.

## Environment

- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4360.0
- DPI 96dpi (no scaling)

**Comment by luweeewu** [comment]
It seems that there was a glitch somewhere that was causing this issue. I've since restarted Gitextensions again, and the look of the buttons in dark mode (both dark and darksilver) now makes it obvious which ones are enabled and which are disabled.

**Comment by gerhardol** [comment]
The WinForms controls used in GE does currently not have natively support for theming so various glitches may occur.
The above is a known problem after changing dpi
https://github.com/gitextensions/gitextensions/wiki/Dark-Theme
