### ISSUE TITLE
Return the option to disable showing multi-line commit messages in the revision graph

### ISSUE THREAD

**Issue by jwfx** [gitextensions/gitextensions#9298]
This option was initially part of the pull request, but then got removed.

https://github.com/gitextensions/gitextensions/pull/8371/commits/c4a9ed245c6e8ed45cc98788b8d82c12654acb8a

Is there a chance it can be returned? I'd be willing to make a PR.

**Comment by mstv** [comment]
Would be OK for me - although I will not turn it off. I was a little surprised the option was removed.

**Comment by gerhardol** [comment]
Git Extensions has already too many settings for most users. 
I like customizations myself, but this is hard to explain to users, they get confused by all options.
This also adds to translations.

Personally, I would like to keep changes like this in an "advanced" section just listing all settings.
No such view exists, it could be possible to just read this from the settings file without UI to set it.

But several users have asked for a setting, I will not vote against a PR.
