### ISSUE TITLE
Recent repository search

### ISSUE THREAD

**Issue by davidgiga1993** [gitextensions/gitextensions#9302]
## Feature description
Background: I'm working with a lot of different repositories and I need to switch between quite regulary / fast.
It would be great to see some sort of recent repository search where I can just type some part of the path and git extensions will show me a list of all matching repos. Ideally it should be possible to just start typing after opening git extensions.

Maybe just a big searchbar at the top of the start screen?
![image](https://user-images.githubusercontent.com/3924958/122722136-abc6c500-d271-11eb-8ee6-b001cba9e7f8.png)

Let me know what you think

**Comment by gerhardol** [comment]
What to search for, the last part of the url only?

You can configure the most recent and less recent repositories (also in the dropdown in browse).
I keep a short most recent list and a longer alphabetical sorted less revent list. Mostly OK for me.
( work with mabe 25 products, each that I have 1-5 worktrees for, each have 5-15 submodules).

I tried to work with categories, but add new clones faster than I updated categories.

**Comment by davidgiga1993** [comment]
> What to search for, the last part of the url only?

The full path would be the best imho. IntelliJ does the same thing in the "run anything" feature:
![image](https://user-images.githubusercontent.com/3924958/122767929-6b803a80-d2a3-11eb-9a38-768499109d66.png)

> You can configure the most recent and less recent repositories (also in the dropdown in browse).

Yes I know, but it's much slower to navigate than just type a keyword and hit return.

**Comment by pmiossec** [comment]
> Let me know what you think

Even if i don't use a lot of repos so that feature become useful for me, I understand that it could be very useful for some users.

The real question is more: Who will do it. Are you proposing to develop it @davidgiga1993 ?

**Comment by davidgiga1993** [comment]
@pmiossec Sorry for my late reply. Yes I'll build, just need to find a bit of time 👍

**Comment by RussKie** [comment]
Before you spend too much time implementing this, can we discuss the UI changes first - i.e. the placement of the search bar, its representation, etc.?

**Comment by davidgiga1993** [comment]
Sure! I'm by far no UI expert but intuitively I would put the search bar at the top of the home view, similar to this mock
![image](https://user-images.githubusercontent.com/3924958/124811453-c6cc5100-df62-11eb-9ebd-c7eb0c05a344.png)

Entering text would then filter the items below directly on typing. Pressing return would open the first repository shown.

**Comment by RussKie** [comment]
Looks good
