### ISSUE TITLE
Update Artificial Commits

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9312]
## Current behaviour

Occasionally, the file list and the file diff of the artificial commit `Commit index` is not updated e.g. after closing FormCommit.
(The displayed number of changed files was correct in the toolbar and in the RevisionGrid but not the `FileStatusList`.)

I am not sure whether I have seen this for the `Working directory`, too.

This might be related to the 15s update delay.

## Expected behaviour

The file list of Artificial Commits is updated as well as the diff of the selected file.

(OT: The number of changed files should be updated at once when the GE application gets the focus. The update is delayed too often in my daily work.)

## Steps to reproduce

1. stage some of the changes
2. select `Commit index`
3. open FormCommit
4. un/stage multiple (e.g. exchange the staged and unstaged parts of the files)
5. close FormCommit

## Did this work in previous version of GitExtensions

Not sure

## Environment

- Git Extensions 33.33.33
- Build 20fc5c6f74b8b804f5923626584436949f32b5da
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET 5.0.5
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
FileStatusList is not updated by default. I do not really want that either, annoying to disturb what I work with and stop operations for up to 10s (git-status can be slow with virus programs, normally less than a second though). There should be a separate refresh indicator though.

I believe you added some specific change, similar to what there is in FormCommit.

**Comment by mstv** [comment]
Second occurrence today. (I needed to swap the staged and unstaged parts of the file starting with "t").

After closing FormCommit - wrong:

![grafik](https://user-images.githubusercontent.com/36601201/123656858-9123bb80-d830-11eb-9533-4c932b86113f.png)

After refresh - correct:

![grafik](https://user-images.githubusercontent.com/36601201/123656933-a1d43180-d830-11eb-8543-4bd68c169799.png)

I disabled the `FileSystemWatcher` for git index a few weeks ago because of too often 15s delays:

![grafik](https://user-images.githubusercontent.com/36601201/123657325-fa0b3380-d830-11eb-92fc-61fb40d14498.png)

**Comment by gerhardol** [comment]
I believe you added the option to refresh the artificial commit. Was it same as for FormCommit:


Not sure was the trigger was, form reactivation?
(I am quuite sure that GitStatusMonitor do not trigger the update.)

> I disabled the `FileSystemWatcher` for git index a few weeks ago because of too often 15s delays:

That is only for the status on the refresh button up left.
I would like to remove the option (and always have it enabled, compare to the filewatcher for the config file).

For 15s delays I assume you mean that submodule status are delayed up to 15 s. That optimization should not have much effect now when the default time is changed to 30s (unless explicitly triggered as when leaving a popup).

**Comment by gerhardol** [comment]
FormBrowse.cs 1fc5f294d0fe8b3c9aaacae461a914887371dd10, in 3.4

Artificial could be explicitly refreshed similar to GitStatusMonitor is refreshed when a form is closed

```C#
        protected override void OnApplicationActivated()
        {
            if (AppSettings.RefreshArtificialCommitOnApplicationActivated && CommitInfoTabControl.SelectedTab == DiffTabPage)
            {
                revisionDiff.RefreshArtificial();
            }

            base.OnApplicationActivated();
        }
```

If application is not reactivated, it will not refresh

**Comment by mstv** [comment]
Thank you for the hints. I will play around and try what feels better.
