### ISSUE TITLE
Old changelog link in the "There is an update" window

### ISSUE THREAD

**Issue by TymurGubayev** [gitextensions/gitextensions#9345]
The link to changelog in the "There is an update" window points to changelog that ends at Version 3.4.3 (23 July 2020).

## Current behaviour

The link points to https://github.com/gitextensions/gitextensions/blob/master/GitUI/Resources/ChangeLog.md

## Expected behaviour

The link points to https://github.com/gitextensions/gitextensions/blob/release/3.5/GitUI/Resources/ChangeLog.md#version-351-04-jul-2021

or

The ChangeLog.md the link currently points has recent changelog.

## Steps to reproduce

Install Git Extensions 3.5.0, run "Check for update", click on the "Changelog" link.

**Comment by gerhardol** [comment]
The changes from 3.5 should be merged to master

**Comment by justinharrell** [comment]
This issue has returned with the new version, very confusing to see an update and click view changelog and see no update.
