### ISSUE TITLE
PowerShell does not run in the foreground

### ISSUE THREAD

**Issue by tasmin** [gitextensions/gitextensions#9347]
## Current behaviour

A script defined to run a .ps1 file as powershell in the foreground via a toolbar button no longer opens a powershell window. The script gets stuck when it asks for user input on the command line and has to be terminated from the task manager.

## Expected behaviour

When the script is invoked via the menu button, a powershell window should open and execute the .ps1 script.

## Steps to reproduce

1. Copy the content of the attached zip file into a folder .git\PowerShell in the current git project folder.
2. Setup the script as shown in the screenshot below
3. Run the powershell script attached by clicking the button for the script.
4. In the prompt window, enter anything, or just press ENTER
5. Expect to see the powershell window with another command line prompt but the window is not visible.

[PushOutBuild.zip](https://github.com/gitextensions/gitextensions/files/6779788/PushOutBuild.zip)

## Screenshots

![image](https://user-images.githubusercontent.com/1577260/124819530-37eb1480-df21-11eb-87cd-6e9567a07114.png)

## Did this work in previous version of GitExtensions

This worked up to  GitExtensions version 3.4.3.9999.

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.18362.0
- .NET Framework 4.8.4121.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
You could try the dev build based on 3.5.1 https://ci.appveyor.com/api/buildjobs/kduel6anx2s57ten/artifacts/combined.3.5.1.12261-unsigned.zip.

**Comment by tasmin** [comment]
I have verified that the fix in the  3.5.1  Dev build is working
as expected.

Thank you
Tasmin.

**Comment by mstv** [comment]
Thank you for reporting and testing.
