### ISSUE TITLE
After updating to 3.5.1, I always get asked the SSH passphrase every time a pull is done

### ISSUE THREAD

**Issue by vittoso** [gitextensions/gitextensions#9348]
## Current behaviour

After updating to 3.5.1 from 3.4.3.9999, everytime I click the pull button in GE git asks me for the OpenSSH passphrase. 
With 3.4.3.9999 I had to retype the passphrase rarely as it was remembered, I believe this is the correct behaviour.
I tried both "OpenSSH" and "Other ssh client" (pointing to the ssh.exe from the windows 10 open ssh-agent) in GE settings, but the behaviour is the same

Using command-line git from powershell correctly remembers the openssh passphrase.

## Expected behaviour
Users does not have to retype the passphrase everytime a pull is done

## Steps to reproduce

1. Update from 3.4.3.9999 to 3.5.1 via the "check for updates" button in the application
2. Open any already configured repository (i have OpenSSH as global settings)
3. Click on the pull button
4. You are asked to type the passphrase in. Type the correct passphrase.
5. After pull is finished correctly, click on the pull button again
6. You are asked - again -  to type the passphrase in. Type the correct passphrase.
7. Repeat steps 5-6

## Screenshots

![image](https://user-images.githubusercontent.com/1496592/124876968-e13a1500-dfca-11eb-8429-a83bdd8450b7.png)

## Did this work in previous version of GitExtensions

With 3.4.3.9999  it was working correctly (Ssh passphrase was asked rarely)

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.30.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4390.0
- DPI 120dpi (125% scaling)

**Comment by skajfes** [comment]
I have the same issue, with version 3.5.1.12196 I am asked for the passphrase every time when pushing or pulling from the remote. I have OpenSSH setup and configured on the system and I am not asked for passphrase when pulling from powershell. 

I have noticed that when I open settings there is an error of "Unknown SSH client configured", in red. SSH client is C:\WINDOWS\System32\OpenSSH\ssh.exe, but GitExtensions can't see that file for some reason. 

GitExtensions version 3.5.0.11713 does not have this issue, and behaves correctly.

**Comment by dopry** [comment]
I am having the same issue with 3.5.1.12196. It can not see the folder c:\Windows\System32\OpenSSH.  I can get to the folder in explorer just fine.

**Comment by mstv** [comment]
@dopry has opened #9355 for the ssh setting.

**Comment by gerhardol** [comment]
Please see https://github.com/gitextensions/gitextensions/issues/9355#issuecomment-877706848 for explanation of the behavior and changes as well as some things to try.

**Comment by vittoso** [comment]
I already had regkey and GIT_SSH set to C:\WINDOWS\System32\OpenSSH\ssh.exe and sti9ll GE is asking me the passphrase everytime I push or pull.
I tried setting GIT_SSH_COMMAND to ssh.exe in the environment variables: it still asks the passphrase everytime.
At the present time; I still have the problem, sto the issue - to me - is not closed

**Comment by gerhardol** [comment]
Please try the test build, see https://github.com/gitextensions/gitextensions/issues/9355#issuecomment-878650413

**Comment by vittoso** [comment]
GE test build GitExtensions-Portable-3.5.1.12277-d9ea74592 no longer keeps asking for ssh passphrase, well done!
I'll try to use it today and I'll let you know if any other problems arise

As a note, it still doesn't recognize c:\Windows\System32\OpenSSH\ssh.exe as valid, though.
![image](https://user-images.githubusercontent.com/1496592/125418254-c7de32f9-77e7-4d35-b2e2-9054c6c7b1dc.png)

**Comment by gerhardol** [comment]
> I'll try to use it today and I'll let you know if any other problems arise

There are a couple of other commits compared to 3.5.1, minor changes

> As a note, it still doesn't recognize c:\Windows\System32\OpenSSH\ssh.exe as valid, though.

No change for that, should be the same with 3.4. User programs may not have a permission to list files or check that files exists here.
The check in settings is similar to the check I removed for setting GIT_SSH (so the settings state no longer reflects the functionality...)

**Comment by vittoso** [comment]
Could this be due to [32-bit app File System Redirector](https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector?redirectedfrom=MSDN)? 
If I manually force the OpenFileDialog to point to c:\Windows\sysnative instead of c:\Windows\system32, I can see the "OpenSSH" folder that is missing if I open c:\Windows\system32.

![image](https://user-images.githubusercontent.com/1496592/125452566-d2a08c2e-a000-4caa-bfdb-7b194e68fb1a.png)
