### ISSUE TITLE
After update to 3.5.1, Tools->Git bash option no longer works

### ISSUE THREAD

**Issue by mnoreen** [gitextensions/gitextensions#9349]
## Current behaviour
After upgrading to 3.5.1, when I choose the Git bash item from the Tools menu, nothing happens.  No Git bash window.  No error.  Nothing.

I can, however, go to an File Explorer window, right-click my parent folder and successfully choose "Git Bash Here" context menu.

## Expected behaviour
Bash window should open up

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4360.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
You are right. But both `Ctrl+G` and the toolbar button do work.

**Comment by mstv** [comment]
You could try the dev build based on 3.5.1 https://ci.appveyor.com/api/buildjobs/kduel6anx2s57ten/artifacts/combined.3.5.1.12261-unsigned.zip.
