### ISSUE TITLE
GE fails on a commit with empty subject (or doesn't display it at all)

### ISSUE THREAD

**Issue by crypto-rsa** [gitextensions/gitextensions#9354]
## Current behaviour

When there is a commit with an empty message in the repository, GE shows an error message and hangs/crashes (in Debug build). In a Release build, such commits are not displayed at all.

## Expected behaviour

Commits with an empty message should be displayed normally. They are legitimate - one can be created by `git commit -a --allow-empty-message -m ''`. In my repository, there is a number of old commits (from pre-`git` version control system) which were imported automatically and which have no subject.

## Steps to reproduce

1. Create a repository
2. Make a change
3. Commit using `git commit -a --allow-empty-message -m ''`
4. Open the repository in GE

## Did this work in previous version of GitExtensions

Yes, this behaviour has been introduced in c8396d8d94e06c8c24d23bad33554c92a2754fad.

## Environment

- Git Extensions 33.33.33
- Build c8396d8d94e06c8c24d23bad33554c92a2754fad
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 5.0.7
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Created a PR for this case

The parsing ignores all parse errors, this Debug.Fail is an exception. It was not possible to call Debug.Fail on the other parse failures as FileHistory use case would feed incorrect data. 
Parse failures will likely come in multiples so the assert should probably turn off after the first.

To display parse errors in Release builds is more tricky, it is likely less disruptive to just continue than to abort here.

**Comment by gerhardol** [comment]
@crypto-rsa Please review the pull requests
