### ISSUE TITLE
(0↑ ↓) shown after each local branch

### ISSUE THREAD

**Issue by fsinv** [gitextensions/gitextensions#9362]
Hello,

since the latest version 3.5.1 **(0↑ ↓)** is shown after each local branch which is up-to-date. I did not find any setting to disable it so it seems to be an issue.

**Comment by gerhardol** [comment]
That is the number of commits the branch is ahead/behind the tracked remote branch.
There is no setting to disable this

**Comment by fsinv** [comment]
Yes, but in the previous version it never showed (0↑ ↓) but nothing at all in the case the branch is up-to-date. Showing (0↑ ↓) does not make sense.

**Comment by pmiossec** [comment]
> Showing (0↑ ↓) does not make sense.

In fact, it tells you that this branch is tracking a remote. And allows you to differentiate with local none tracking branches.
So it does make sense 😉 

Behavior changed with PR #8562

**Comment by vbjay** [comment]
0 down and 0 7p means current or up to date. Makes sense to me.

**Comment by fsinv** [comment]
Ok, thanks for the additional information on that.

**Comment by SvenVMSW** [comment]
I just updated and I found the previous behaviour better, It showed me more easy the branches where I was out of sync with the remote. Is there no way to make this an option?
