### ISSUE TITLE
Commit window shift select from the top

### ISSUE THREAD

**Issue by EpsilonD3lta** [gitextensions/gitextensions#9363]
## Current behaviour

When I open a commit window and <kbd>shift</kbd> + <kbd>left click</kbd> to select e.g. 4th item from the top, currently, it selects all items from the bottom till 4th item (included). In my opinion, the more natural behavior would be to select the first 4 items from the top. 

Moreover, when you first open the commit window, the first item is already selected/highlighted which is misleading, and one would really expect that shift click will start from that selected item. However when I first click to select the first item in the list (which is already selected/highlighted), the behavior changes and it works as expected.

The same behavior is present in the Diff view.

![image](https://user-images.githubusercontent.com/30054007/125263735-90e0f100-e303-11eb-859e-671ecfb112b8.png)

## Expected behaviour

The selection starts from the first item:

![image](https://user-images.githubusercontent.com/30054007/125263894-afdf8300-e303-11eb-840f-051e4af2c553.png)

## Steps to reproduce

* Open the commit form when having more than 3 changes to commit
* <kbd>Shift</kbd> + <kbd>Click</kbd> on the item in the middle of the list
* Remark that the selected items start from the clicked item to the last item and not from the first item to the one clicked.

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.30.0.windows.1
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
@EpsilonD3lta You take the wrong template to report this bug so I have updated the description. Feel free to review my edition...

**Comment by vbjay** [comment]
It's not required. Just need top and bottom for ranges. Think like git diff
c1 c2.

**Comment by EpsilonD3lta** [comment]
@pmiossec I wasn't sure, maybe it is a desired behavior, but thank you. Now I realised that the same behavior is in the Diff window

**Comment by XopherThomas** [comment]
This issue has been resolved in 4.0.0 by:
https://github.com/gitextensions/gitextensions/pull/10253

**Comment by pmiossec** [comment]
In all likelihood fixed. Thanks.
