### ISSUE TITLE
Setting to disable/hide "Recent repositories" category (dashboard)

### ISSUE THREAD

**Issue by BenedekFarkas** [gitextensions/gitextensions#9364]
## Feature description

I would like to have a setting which allows me to disable displaying the "Recent repositories" repository category at the top of the dashboard.

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4360.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Why?

**Comment by gerhardol** [comment]
View->Toolbars->Standard

since 3.5

**Comment by BenedekFarkas** [comment]
> Why?

Muscle memory. Working with a bunch of different repositories (and their submodules) changes the displacement of my custom repository categories, so I keep clearing "Recent repositories", but I'd like a better solution.

> View->Toolbars->Standard
> 
> since 3.5

I checked the existing issues, recent release notes and existing settings before opening issue, but I haven't found anything that covers what my issue is about. I believe what you're referring is the toolbar icons when you have a repository open, but my issue is with the dashboard (or at least I think that's the terminology for it, so basically the starting screen with the repository categories).

**Comment by BenedekFarkas** [comment]
So, what do you think? Might be fairly simple, I assume. If you give some directions in terms where to add the new setting, I could go for it with a PR. In case the Recent repositories section is hidden, I'd probably keep the tracking of the repositories in case you re-enable it.

**Comment by gerhardol** [comment]
Could maybe be added to `Recent repositories settings`
It seems like the size of the list is the same as in the settings anyway, you could try setting it to a small number and it remains away.

**Comment by RussKie** [comment]
This is simpler than #9365.

The setting would go into the AppSettings, and must be exposed in the
Settings dialog, and in Dashboard menu. Also probably in the dashboard's
context menu?
The setting must only affect the visibility of the recent repos in the
dashboard, nothing else.

**Comment by BenedekFarkas** [comment]
> Could maybe be added to `Recent repositories settings` It seems like the size of the list is the same as in the settings anyway, you could try setting it to a small number and it remains away.

TIL there's Recent repositories settings! :)

> It seems like the size of the list is the same as in the settings anyway, you could try setting it to a small number and it remains away.

The minimum value for "Recent repositories history size" is 10, so you can't set it to anything lower, but I guess allowing lower values, such as 0 would be a logical way to achieve the same thing. What do you think?

**Comment by RussKie** [comment]
I don't a strong opinion either way.
