### ISSUE TITLE
Setting for dashboard categories to remember expanded/collapsed state

### ISSUE THREAD

**Issue by BenedekFarkas** [gitextensions/gitextensions#9365]
## Feature description

I would like a setting which enables/disables a behavior that makes the repository categories on the dashboard remember their expanded/collapsed state.

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4360.0
- DPI 96dpi (no scaling)

**Comment by BenedekFarkas** [comment]
Any feedback, please?

**Comment by gerhardol** [comment]
Remembering collapsed state as well as splitter positions always seem to be tricky so not a favorite...
If you want this to disable Recents in the dashboard, it is simpler to not show it at all.

**Comment by RussKie** [comment]
The technical challenge is to define how to track each individual group.
That is, we know that the (currently) first group is "Recent repositories",
and we can easily track its collapsed state. But if we track the state for
the first group we ought to track the state for the rest.

At some point in the future we'd want to add groups reorder functionality,
and tracking by index may not work, so how do we track a group? By name?
How do we handle group renames (inside and outside the app)? Etc., etc...

Also we'd likely need collapse all/expand all groups functionality too.
Where would it be placed and how would a user interact with it?

If you're interested in pursuing this further please think through all use
cases and the UX, and put forward a detailed proposal.

**Comment by vbjay** [comment]
Guid per section. Well known like recent could be hardcored and custom auto
generated.
