### ISSUE TITLE
git extensions token authentication requirements

### ISSUE THREAD

**Issue by 3ddesigntech** [gitextensions/gitextensions#9368]
I updated my git extensions software and now it is prompting me with a github login box any time i pull or push to the repository. Using the same credentials that I log into github.com gives "login failed, use ctr+c to cancel basic credentials prompt" in the prompt box. If I then use the new popup window "git extensions - git CLI stdin wrapper" and enter my username and password it allows me to login. This then causes an automated email from github titled "depreciation notice" informing me "Basic authentication using a password to Git is deprecated and will soon no longer work." I have attempted to follow the instructions and create a personal access token multiple times with no success in resolving this issue. Please advise how to properly create / install / link my personal access token from the github website to the git extensions application.

I chatted with Laurel from github support on this and it was recommended to try using the personal access token in place of the password.  This did not work either.

This was the response....
We didn't build the plugin, so I can't really do much troubleshooting, but it sounds like from this issue, you may need to clear out a token in the settings and reconfigure it:

https://github.com/gitextensions/gitextensions/issues/4286

Are you able to try this? Can you connect from the command line using your PAT? If so and clearing the token doesn't work/you aren't sure how to do this, you may need to open an issue with gitextensions.

therefore I am opening this ticket here.

Please see attached screenshot images.
Screenshot 1 shows the login popup window I am getting when attempting to pull from the repository.
Screenshot 2 shows my personal access token saved in the github plugin settings of git extensions. I then copy this code from here.
Screenshot 3 shows my user id and copied token pasted into the login prompt box
Screenshot 4 shows the resultant error and additonal login popup box. This error occurs with any combination of login information i enter into the popup window from screenshot 1. The 2nd login popup window from screenshot 4 always works with my user id and password info that i use for github.com.

Please advise how to resolve this issue. thanks.

[screenshot1.pdf](https://github.com/gitextensions/gitextensions/files/6802867/screenshot1.pdf)
[screenshot2.pdf](https://github.com/gitextensions/gitextensions/files/6802868/screenshot2.pdf)
[screenshot3.pdf](https://github.com/gitextensions/gitextensions/files/6802869/screenshot3.pdf)
[screenshot4.pdf](https://github.com/gitextensions/gitextensions/files/6802870/screenshot4.pdf)

## Did this work in previous version of GitExtensions

 yes, but i have no idea which version....there was an update a few months ago that has caused these new popup login boxes.

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3761.0
- DPI 96dpi (no scaling)

## Diagnostics

I have no idea how to fix this, I am not a programmer, and I cannot follow/understand any of the instructions i have found online. I am just trying to view the updates to the website the developer is making before they go live....this is very frustrating because it was working just fine until some update a month or so ago.

**Comment by pmiossec** [comment]
Please put the screenshot as image directly in the issue text, that's difficulty to follow...

**Comment by 3ddesigntech** [comment]
![screenshot1_1](https://user-images.githubusercontent.com/71191976/125324058-83306900-e30d-11eb-9064-6dc0f9fc74ed.jpg)

**Comment by 3ddesigntech** [comment]
![screenshot2_1](https://user-images.githubusercontent.com/71191976/125324270-c25eba00-e30d-11eb-987b-dec733821a34.jpg)

**Comment by 3ddesigntech** [comment]
![screenshot3_1](https://user-images.githubusercontent.com/71191976/125324386-dd312e80-e30d-11eb-8f36-e28e9b8861a1.jpg)

**Comment by 3ddesigntech** [comment]
![screenshot4_1](https://user-images.githubusercontent.com/71191976/125324489-f5a14900-e30d-11eb-819b-a89b7e5db70a.jpg)

**Comment by 3ddesigntech** [comment]
i finally figured out how to update GIT to v 2.32.0.2 and after this update the issue has resolved
