### ISSUE TITLE
"Cannot find main menu" exception since update to 3.5.1

### ISSUE THREAD

**Issue by fchucholowski** [gitextensions/gitextensions#9375]
Since I updated to 3.5.1 I get the exception "Cannot find main menu" when starting.
I already tried it this had something to do with any specific settings but even after deleting the settings file I get this exception.

I can still use Git Extensions then but after any operation I get a NullReferenceException: "Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt." or in English "Object reference not set to an instance of an object".

**Comment by pmiossec** [comment]
Did you installed some plug-ins?
If yes, maybe check if there are updates available through the plug-in manager.

**Comment by fchucholowski** [comment]
Thanks a lot. Updating the Gerrit plugin solved the problem!
