### ISSUE TITLE
[NBug] Unable to parse object ID "".

### ISSUE THREAD

**Issue by Basement-Science** [gitextensions/gitextensions#9378]
:warning: Review existing issues to see whether someone else has already reported your issue.
- Sorry, I didnt have time.

## Current behaviour
- An Error Infobox pops up. GitExtensions closes aftwerward.
- Rebase stops with merge conflicts, but with no reference to the cherry picked commits (yet). 
- Aborting the rebase works.

## Expected behaviour
Rebase completes as usual or prompts about merge conflicts.

## Steps to reproduce
- Created orphan commit
- merged unrelated histories into it
- Added branching commits* after this
- later Cherry picked the merge commits onto the Orphan
- Finally, tried to Rebase the *branching commits onto the cherry picked commits using "preserve merges". This is when the error occured. Without "preserve merges" this error does not seem to occur. 

## Error Details
```
System.FormatException: Unable to parse object ID "".
   bei GitUIPluginInterfaces.ObjectId.Parse(String s)
   bei GitCommands.CommitDataManager.CreateFromFormattedData(String data)
   bei GitCommands.CommitDataManager.GetCommitData(String commitId, String& error, Boolean cache)
   bei GitCommands.GitModule.GetInteractiveRebasePatchFiles()
   bei GitUI.PatchGrid.GetPatches()
   bei GitUI.PatchGrid.Initialize()
   bei GitUI.CommandsDialogs.FormRebase.OkClick(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnClick(EventArgs e)
   bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
   bei System.Windows.Forms.Button.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I was just trying out a bunch of stuff, not sure what is the cause. Could just as well be an issue with Git. I cannot provide the specific Repo I used. Hope I'm not wasting your time.

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.1
- Microsoft Windows NT 10.0.21354.0
- .NET Framework 4.8.4360.0
- DPI 120dpi (125% scaling)

**Comment by mstv** [comment]
```
        internal CommitData CreateFromFormattedData(string data)
        {
            ...

            // $ git log --pretty="format:%H%n%T%n%P%n%aN <%aE>%n%at%n%cN <%cE>%n%ct%n%e%n%B%nNotes:%n%-N" -1
            // 4bc1049fc3b9191dbd390e1ae6885aedd1a4e34b
            // a59c21f0b2e6f43ae89b76a216f9f6124fc359f8
            // 8e3873685d89f8cb543657d1b9e66e516cae7e1d dfd353d3b02d24a0d98855f6a1848c51d9ba4d6b
            // RussKie <RussKie@users.noreply.github.com>
            ...

            // commit id
            // tree id
            // parent ids (separated by spaces)
            // author
            ...

            var lines = data.Split('\n');
            var guid = ObjectId.Parse(lines[0]);
            var treeGuid = ObjectId.Parse(lines[1]);
            var parentIds = lines[2].Split(' ').Where(id => !string.IsNullOrWhiteSpace(id)).Select(id => ObjectId.Parse(id)).ToList();
```
Just guessing: `treeGuid` might have not been specified, e.g. `lines[1]` could have been empty.
Should we switch to `ObjectId.TryParse`?
