### ISSUE TITLE
Right click icon in taskbar to open recent repositories

### ISSUE THREAD

**Issue by VictorioBerra** [gitextensions/gitextensions#9379]
## Feature description

For an example of this look to Visual Studio. If you pin the VS icon to taskbar, you can right click it and it will show you the top 10 recent solutions. This would be nice for Git Extensions.

This WORKS if Git Extensions is open. But not on the pinned shortcut.

![image](https://user-images.githubusercontent.com/2934507/125660996-4cc8eab8-4c20-4aeb-ad62-3607d7036cde.png)

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.27.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4390.0
- DPI 144dpi (150% scaling)

**Comment by pmiossec** [comment]
I can't assert for sure for v3.5.1 because I build my own version but I have it working for years.
That's like that that I launch GitExtensions...

![image](https://user-images.githubusercontent.com/460196/126358951-1828d223-193e-48e4-af7d-51f982af6e40.png)

**Comment by VictorioBerra** [comment]
I found the problem.

If you hit start and search for "GitExtensions" and pin to taskbar from there you wont be abe to right click the taskbar icon and see recent repos.

![image](https://github.com/gitextensions/gitextensions/assets/2934507/da543505-276d-4781-a509-7bcaa528299d)

You have to LAUNCH GitExtensions first and then right click and add:

![image](https://github.com/gitextensions/gitextensions/assets/2934507/39009030-109c-4f8c-8a66-c6181f34e6f7)

**Comment by RussKie** [comment]
Great to hear 👍
