### ISSUE TITLE
"Menu->Tools->Git bash" does nothing after upgrade to GE 3.5.1.12196

### ISSUE THREAD

**Issue by markpizz** [gitextensions/gitextensions#9382]
## Current behaviour

Menu item "Menu->Tools->Git bash" does nothing after upgrading GE to 3.5.1.12196.  However, ^G brings up a bash window.  My configuration was/is set to use Windows cmd as the window that bash appears in.  The bash window created by ^G is not a Windows cmd window, but it is on prior GE versions.

## Expected behaviour

I expect a bash window to open...

## Steps to reproduce

For me, this happens on each machine I install and/or each time I install GE 3.5.1.  I can uninstall 3.5.1 and install 3.4.3 and things work as expected and the problem returns after installing 3.5.1 again.

## Screenshots

^G when "Menu->Tools->Git bash" fails:
![Menu-Tools-Git bash-3 5 1 12196](https://user-images.githubusercontent.com/422671/125861486-37002e95-196e-4586-8466-f1d2b2c9bdee.png)
Note that the Taskbar icon for this ^G created window IS NOT the same as a Windows command prompt.

^G AND "Menu->Tools->Git bash" works with prior (3.4.3.9999) version:
![Menu-Tools-Git bash-3 4 3 9999](https://user-images.githubusercontent.com/422671/125861519-dc6ef6de-d3ba-43ca-8ce1-323eda91d01d.png)
Note that the Taskbar icon for both of these windows IS the same as a Windows command prompt.

## Did this work in previous version of GitExtensions

Yes.  3.4.3.9999

## Environment

"Menu->Tools->Git bash" Fails with:
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

"Menu->Tools->Git bash" works with:
- Git Extensions 3.4.3.9999
- Build d4b0f48bbf3e39a71f5d7ff5231be5678d4aa0f1
- Git 2.32.0.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

## Diagnostics

Under 3.5.1.12196: Diagnostics show nothing happening as a consequence of "Menu->Tools->Git bash" being invoked.
When ^G is entered a line containing: ```running UI     C:\Program Files\Git\bash.exe```

Under 3.4.3.9999: Both "Menu->Tools->Git bash" and ^G show a line containing: ```running 16272 UI   cmd.exe /c ""C:\Program Files\Git\bash.exe" --login -i"```

**Comment by mstv** [comment]
You are right but it's a duplicate, fixed with #9350. You can use that build.
