### ISSUE TITLE
Layout of Fetch/Pull/Push Dialog misaligned

### ISSUE THREAD

**Issue by Nipahu** [gitextensions/gitextensions#9410]
## Current behaviour

Since the recent update whenever I fetch, pull, or push the opening dialog's layout is misaligned. The progress bar is hidden behind the buttons toolbar with the OK/Abort buttons.

## Expected behaviour

The progress bar not being hidden by the button toolbar.

## Steps to reproduce

Install 3.5.1.12196 and fetch, pull or push.

## Screenshots

![Screenshot 2021-07-23 100627](https://user-images.githubusercontent.com/44159192/126754103-37d48f62-fc23-40ba-a0d0-2ac7533132fd.png)

## Did this work in previous version of GitExtensions

In 3.4.9 the dialog's layout was correct.

## Environment

- GitExtensions version:  3.5.1.12196
- GIT version: 2.29.1.windows.1
- OS version: Windows 10 Pro 19042.1081
- .NET version: 4.8.04084

**Comment by RussKie** [comment]
It is not hidden. It is by design.

**Comment by Nipahu** [comment]
Oh. Yes. I see that now. I was just so used to the thick progress bar that I assumed it's hidden now, but it's just a slim progress bar now. My bad.
