### ISSUE TITLE
Commit-icon in UI does not update on new changed files 

### ISSUE THREAD

**Issue by Bejoscha** [gitextensions/gitextensions#9411]
## Current behavior

When local files change in a repo, the commit-icon is supposed to turn orange (from green) and list the number of changed files.

However, since the last update to 3.5.1.12196 this functionality isn't as reliable anymore. I find myself often looking at an orange "commit" message with incorrect number (too few files). 

## Expected behavior

Show current situation correctly.

## Steps to reproduce

Have a repo with a few local files changed (not staged). the icon is orange and lists the number of changed files.
Now mass-change several local files in the repo (extended folder-structure in my case). Note that the icon (still organe) does not update the number of different files.
However, pressing the commit button to get to the commit-dialog shows that all files are (now?) recognized, and leaving the dialog without committing will update the icon as well.

The behavior is not 100% reproducible.

## Screenshots

![image](https://user-images.githubusercontent.com/6987920/126757912-5c484525-271d-4070-8666-99c0952cd7e9.png)

## Did this work in previous version of GitExtensions

Yes. In 3.5.0 it worked very reliably. 

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.21.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4390.0
- DPI 144dpi (150% scaling)

## Diagnostics

**Comment by gerhardol** [comment]
git-status may require quite some resources, the command may require several seconds, especially with corporate viruses like Symantec.
Therefore, the command should not run immediately when changes are detected in the file system. Especially when building, one core could be completely occupied with running git-status with the same result all over again (caching a list of ignored files was done in GE 2.x, that could use GB of RAM).
On the other hand, the first detection at changes and interactive changes should be fast.

There is therefore some hysteresis delaying git-status. The first change detected as well as after exiting GE forms is done immediately. In 3.4, the wait was up to 5 seconds for subsequent changes outside GE. In 3.5.0 the time was changed to 30 s instead to limit git-status running in the background.
If you force refresh or open Commit the status is refreshed.

The coloring of the button is not changed.

Note that git-for-windows has introduced an internal handling in core.usebuiltinfsmonitor. That improves the runtime, but for me this handling occasionally miss changes, never report them, requiring a manual `git -c core.usebuiltinfsmonitor=false status`.
