### ISSUE TITLE
syntactic coloration of code

### ISSUE THREAD

**Issue by PierreMacherel** [gitextensions/gitextensions#9414]
## Feature description

I would like to request the option to have syntactic coloration of the code in the diff viewer (in the red rectangle below) maybe using [delta](https://github.com/dandavison/delta) or [bat](https://github.com/sharkdp/bat#git-diff).  

![image](https://user-images.githubusercontent.com/7684370/126907820-17fb492f-c984-4311-98de-ab33100f6a61.png)
I did not find an option to use a custom pager in place of the diff viewer. The only relevant option I found is to add a diff tool, but I would prefer an option to get the code coloration inside git extensions.

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
There is already: 
![image](https://user-images.githubusercontent.com/6248932/126908222-495b0484-1807-4781-b22c-032fa7930bd6.png)


Not a complete coloring but this is what the internal fileviewer can handle.
(Replacing that is considerable job.)

**Comment by PierreMacherel** [comment]
I missed it. Thank you.
