### ISSUE TITLE
Missing taskbar icon when opened directly to commit window

### ISSUE THREAD

**Issue by Shauren** [gitextensions/gitextensions#9415]
## Current behaviour

When Commit window is opened directly from Explorer or Visual Studio commit button, no icon on taskbar is created.
It will appear only after commit window loses and gains focus again

## Expected behaviour
Taskbar icon is created immediately

## Steps to reproduce

1. Right click in git repository in explorer
2. Choose commit from context menu

## Screenshots

![obraz](https://user-images.githubusercontent.com/297439/126984487-3650fe58-b904-4cfe-a4c9-f206e737690f.png)

Before unfocus & focus:
![obraz](https://user-images.githubusercontent.com/297439/126984782-f860a446-038b-4752-b66a-e2add65236c7.png)

After refocus:
![obraz](https://user-images.githubusercontent.com/297439/126984941-f24755e9-975a-4f1b-bb28-c185dc7c4307.png)

## Did this work in previous version of GitExtensions
Yes

v3.4.3

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
I could not reproduce this by running "GitExtensions.exe commit" from the command line on two PCs.
