### ISSUE TITLE
Statistics plugin does not handle -grafts- git replace

### ISSUE THREAD

**Issue by MichaelKetting** [gitextensions/gitextensions#9428]
## Current behaviour

I have more than one remote repository cloned locally and joined the repositories using ~~a graft~~ `git replace --graft A B`. The Statistics plugin only analyzes one of the two repositories, and actually it analyzes the "old" repository (i.e. the repository onto which I have grafted my current work).

## Expected behaviour

The Statistics plugin analyzes all cloned repositories and merges the results (or, less preferred, asks me which repository to analyze).

## Steps to reproduce

Load two repositories, graft them together, run the Statistics plugin.

## Screenshots
-

## Did this work in previous version of GitExtensions

not that I'm aware of.

## Environment

- GitExtensions version: 3.4.3
- GIT version: 2.31.1.windows.1
- OS version: Windows 10 v20H2
- .NET version: 4.8

## Diagnostics
-

**Comment by vbjay** [comment]
https://stackoverflow.com/questions/6800692/how-do-git-grafts-and-replace-differ-are-grafts-now-deprecated

**Comment by pmiossec** [comment]
@MichaelKetting you have to be clearer and maybe give example of which statistics are not good.

GitExtensions is relying on git to find the commits so if git doesn't returns all the commits, GitExtensions can't do better.
You could try to debug seeing the command run in "Git command log" (F12 key).

But as @vbjay told you, grafts are deperecated and `git replace` should be used instead and maybe in this case, git will return all the commits.

You have to test.

**Comment by MichaelKetting** [comment]
@pmiossec 
I'm sorry, I should have been more precise, I already used the `git replace --graft A B` command and my `.git/info/refs` file contains the corresponding `refs/replace` entry.

**Comment by MichaelKetting** [comment]
@pmiossec 
thanks for the info on the F12, that's extremly helpful! So, not a GitExtensions issue, Thanks!
