### ISSUE TITLE
BlameControl: Hide unrelated context menu item

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9435]
## Current behaviour

![image](https://user-images.githubusercontent.com/36601201/127785914-9a3033a1-be2e-467f-94e9-0739e26c3d9c.png)

## Expected behaviour

`Enable automatic continuous scroll` applies only to tab "Diff" of FormBrowse

## Environment

- Git Extensions 33.33.33
- Build 77310a56f66d30afc29717d4060c2bca146d4b0d
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 5.0.7
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
> `Enable automatic continuous scroll` applies only to tab "Diff" of FormBrowse

It applies to some more forms (but still does not make sense here).

![image](https://user-images.githubusercontent.com/6248932/128090600-cda2d2a9-3250-41bd-b4c4-0bbbe1f59f1a.png)

**Comment by gerhardol** [comment]
Implemented in a551170ef8d02ce199c53fa9c9cba9406b11a042
To be include in a WIP PR soon
(the currently opened PRs should be merged before new PRs)
