### ISSUE TITLE
Improve FileTree / BlameControl updates

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9437]
## Current behaviour

With #9424, the BlameControl is used for viewing files on tab "File tree" of FormBrowse.
When switching files, the FileTree is invalidated.
After reloading the FileTree, the selected file may not be selected - although it exists in this tree. A folder is selected instead.

## Expected behaviour

When switching files, the FileTree does not need to be invalidated.
After reloading the FileTree when switching commits, scroll the FileTree selection to be visible.
The file selection shall be restored after reloading the FileTree - also following renames if possible.

## Steps to reproduce

- view tab "File tree"
- switch files
- switch commits
- `Blame previous revision` multiple times

## Screenshots

![FileTreeBlame](https://user-images.githubusercontent.com/36601201/128091631-f0c41988-f6c0-4a2c-aedc-d587a2524988.gif)

![FolderSelected](https://user-images.githubusercontent.com/36601201/128092406-74ab7a70-d138-407d-9325-3087bb5941ca.png)

## Did this work in previous version of GitExtensions

new feature

## Environment

#9424

**Comment by gerhardol** [comment]
I am making a few improvements in "following" files in FileTree/Diff infor filtered mode, can be seen in feature/i7598-replace-formfilehistory
(Will make a WIP PR there soon, the already open ones should be merged first)

> After reloading the FileTree, the selected file may not be selected - although it exists in this tree. A folder is selected instead.

The selection code is quite tricky, exists in at least three versions right now. I am trying to unify them.
Folders should be selected if a full match cannot be found.

> When switching files, the FileTree does not need to be invalidated.

Will look at that, maybe the activation can be changed 

> After reloading the FileTree when switching commits, scroll the FileTree selection to be visible.

I tried to enable this, but EnsureVisible() does not have an effect

> The file selection shall be restored after reloading the FileTree - also following renames if possible.

There are attempts to reload the selection when activating the blame control again, not fully implemented it seems.
I would prefer to not use the info for the --follow hack in the selection, that is private to the RevGrid revision reader now.

**Comment by mstv** [comment]
> Folders should be selected if a full match cannot be found.

Good. But I guess, the search is started before the file tree has finished loading.

> I tried to enable this, but EnsureVisible() does not have an effect

Perhaps for the same reason.

**Comment by mstv** [comment]
> feature/i7598-replace-formfilehistory

🚀 Thank you very much!

**Comment by gerhardol** [comment]
> I tried to enable this, but EnsureVisible() does not have an effect

Working in the latest update, scroll position too.
Will push a few of the changes to #9424

**Comment by mstv** [comment]
The tests can be built with https://github.com/gitextensions/gitextensions/commit/e5af2a10098652134ca992074d43101402ed0648
The test `ctor_must_throw_if_revision_ref_null` fails because `IGitRef[] refs = revisions.SelectMany(r => r.Refs).Where(r => r is not null).ToArray();` throws a NRE instead of yielding an empty array. 🤔

**Comment by gerhardol** [comment]
In #9424 the selection and scrolling mostly works. EnsureVisible() is not always scrolling for some reason.
I have set that PR to close this issue for now.
