### ISSUE TITLE
Undesirable copies in file history

### ISSUE THREAD

**Issue by TymurGubayev** [gitextensions/gitextensions#9439]
## Current behaviour

The File History dialog shows a history of **copies** of the file - even if the current file is a copy of an original, made years ago, and doesn't have anything to do with the original anymore.

The copies are found using following.
```
git -c log.showSignature=false log --format="%n" --name-only --follow  --find-renames --find-copies -- "somefile/in/my/repo"
```

## Expected behaviour

Only history of current file is shown. Was the file renamed/copied, history of original is shown from that commit backwards.

## Steps to reproduce

1. In an empty repository, create a file A with some content and commit.
2. Create a copy of A called B and commit.
3. Change A and commit.
4. Change B and commit.

File History of B shows all 4 commits. But the 3rd commit is irrelevant to the B: it changes A after B was split off of it.

## Screenshots

![image](https://user-images.githubusercontent.com/348150/128137357-716a317d-eea4-4b1f-871f-e0c83192184d.png)

## Environment

- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.32.0.windows.1

**Comment by gerhardol** [comment]
Configurable

![image](https://user-images.githubusercontent.com/6248932/128156366-321e39b6-0b64-47f3-9356-022457ca3e20.png)

**Comment by TymurGubayev** [comment]
should be configurable in place.

![image](https://user-images.githubusercontent.com/348150/128166900-fa4fb07e-816b-4e75-b56c-9e26723619dc.png)

**Comment by gerhardol** [comment]
> should be configurable in place.

It is in the form:
![image](https://user-images.githubusercontent.com/6248932/128266726-e0e7bea9-6f93-4aac-904d-f45f832556e6.png)

FileHistory is being replaced with filtered view in Browse, so no active changes planned in FileHistory

> Also, without the checkmark I only see commits 4 and 2.

B was not changed in 1, then git-log will not report it.
So this is something you will have to discuss on a pure Git discussion.

`git-log --follow` is also seen as a hack by Git purists, not working as expected (see https://stackoverflow.com/questions/46487476/git-log-follow-graph-skips-commits).
Linus Torvalds himself wants to track changes regardless of filenames, not implemented in any GUI.

**Comment by TymurGubayev** [comment]
> It is in the form:

Well, I haven't even thought about looking for this option in the context menu of a commit node. Maybe it is worth considering adding a button on the menu bar for this?

> FileHistory is being replaced with filtered view in Browse, so no active changes planned in FileHistory

Will it track filename changes?

> B was not changed in 1, then git-log will not report it

Yes, but with the checkmark, it did find it. It just did also find something undesired as well.
I think it can be done like follows. Show commits of a file like it currently works without the checkmark, mark the very first commit; then find out if the current file is a copy of another, and, if that's the case, show commits of the original file but only up to the marked commit.

**Comment by gerhardol** [comment]
> > It is in the form:
> 
> Well, I haven't even thought about looking for this option in the context menu of a commit node. Maybe it is worth considering adding a button on the menu bar for this?

All options cannot be seen everywhere, most users will only set this once.

> > FileHistory is being replaced with filtered view in Browse, so no active changes planned in FileHistory
> 
> Will it track filename changes?

Same filtering of commits in the grid, the core is the same. You can kindof use the Advanced filter in 3.5 too (but graph is hidden).

> > B was not changed in 1, then git-log will not report it
> 
> Yes, but with the checkmark, it did find it. It just did also find something undesired as well.
> I think it can be done like follows. Show commits of a file like it currently works without the checkmark, mark the very first commit; then find out if the current file is a copy of another, and, if that's the case, show commits of the original file but only up to the marked commit.

PRs are welcome. This seem to be quite complex to me and is probably something that need to be enabled/disabled per view, so something in the UI too.
