### ISSUE TITLE
Deleting remote branch is broken

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9462]
## Current behaviour

![image](https://user-images.githubusercontent.com/4403806/128661547-ba0edd24-3ab9-49e4-886e-ea6282e397cc.png)

## Steps to reproduce

1. Latest master (adbb410d5b65b8d23d8bb71541179cbe573478e8)
2. Right click > delete remote branch or <kbd>DEL</kbd> on a remote branch

## Did this work in previous version of GitExtensions

Yes, not sure where we regressed.

**Comment by gerhardol** [comment]
This is likely that the Git command is returning an error, this was ignored before but is throwing now.

**Comment by mstv** [comment]
(That's why I wanted to show exceptions when they are *created*. Then you could really ignore this warning without cancelling the further execution.)

`git branch -a merged` is not sufficient to decide whether `git delete` needs `--force` or not.
So we should always force-delete after the confirmation in GE.

**Comment by RussKie** [comment]
> (That's why I wanted to show exceptions when they are _created_. Then you could really ignore this warning without cancelling the further execution.)

I'm not sure we're talking about the same thing though. We should not have any exceptions here; the warning has no effect on the operation we're trying to execute, but we've essentially broken the UX...

```
PS C:\Development\winforms> git branch -a --merged
warning: ignoring broken ref refs/remotes/remote/HEAD
  project_configuration
  update_global_usings
* use_sg_v2_syntax
  remotes/origin/191
  remotes/origin/dev/klloeffe/ToolstripHighDpi
  remotes/origin/project_configuration
  remotes/remote/locfiles/3b948f2e-7a26-4662-bb13-d007daa2a15b
  remotes/remote/use_sg_v2_syntax
```

**Comment by RussKie** [comment]
This is where we regressed: https://github.com/gitextensions/gitextensions/pull/9056

**Comment by mstv** [comment]
> This is where we regressed: #9056

Of course, and on purpose. Finally, one can see the warning.
Not `Delete remote branch` is broken but your HEAD ref.
The exception as the reaction is too hard in this case. (That's why I wanted a popup when the exception is *created* in order to not throw it if the user wants to ignore it.)

**Comment by gerhardol** [comment]
![image](https://user-images.githubusercontent.com/6248932/129114697-87d4e9fb-1162-4ae8-9236-56002d9eed40.png)

> The broken HEAD is irrelevant in this case. We've broken the UX, which worked for years. Please have it fixed.

There has been many issues over the years where the app has failed in strange ways when Git reports errors. 
In this case the parsing is broken, GetOutputLines() tries to parse also the stderr output.
So I would say that GetOutputLines() is broken, stderr should never be parsed like this.

The "broken ref" message could affect more commands.
The general solution is tricky.
Maybe ignoring stderr (new option) but not error exit is preferred, or filter out specific messages.

**Comment by RussKie** [comment]
I maintain the broken head is **completely irrelevant** to deletion of remote branches. If it is important in other scenario those scenarios need to fail, and explain why it is so. Right now I can't use this feature, which makes the app significantly less usable to me because my day-to-day job involves creation and deletion of lots of branches.
