### ISSUE TITLE
ssh.exe not found

### ISSUE THREAD

**Issue by Hummel37** [gitextensions/gitextensions#9463]
## Current behaviour
After last update I get always an error
error: cannot spawn C:\Program Files (x86)\Git\usr\bin\ssh.exe: No such file or directory
fatal: unable to fork
The path of my ssh.exe is C:\Program Files\Git\usr\bin\ssh.exe
Before the last update GitExtensions works fine for me.
Prev version: Version 3.5.1 (04 Jul 2021)
Current version: Version 3.5.2 (06 Aug 2021)
 

## Expected behaviour
The ssh.exe file get's found.

**Comment by mstv** [comment]
It should like this (git **file** and tools **folder**):
![image](https://user-images.githubusercontent.com/36601201/128765506-fbc72587-9e0f-4290-ac8a-db5f79b37374.png)

**Comment by pedrolamas** [comment]
@Hummel37 I'm experiencing this exact problem myself... did you fix this on your side? Thanks!

**Comment by pedrolamas** [comment]
Found the solution for my problem, somehow it was looking for ssh.exe on the wrong folder... working fine now that I've corrected the path as shown here:

![image](https://user-images.githubusercontent.com/85504/129326310-f98f7f4b-97c9-47f3-a4bc-e3593b3bc93c.png)
