### ISSUE TITLE
Can not undo "Commit" tab to its original position

### ISSUE THREAD

**Issue by th3ragex** [gitextensions/gitextensions#9465]
## Current behavior
I somehow managed to move the "Commit" tab to different position by unintentionally using  drag and drop. This new state is persistent and i don't know how to undo it by using the UI. This state survived the update to the latest version.

I managed to undo it by deleting my GitExtensions.settings

## Expected behavior
Either Tabs should not be drag&drop-able. 
or Tabs should be easily drag and drop-able.

## Steps to reproduce
I am not sure how i did it, it just happened with one mouse move. I can't promise that i wasn't pressing any keys.

## Screenshots
![grafik](https://user-images.githubusercontent.com/15040273/128679403-ca026389-270f-4717-80c2-173bb721b1b3.png)

## Did this work in previous version of GitExtensions
Unclear.

## Environment
Described state created in previous version: 3.5.1

Currently installed version:
- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4390.0
- DPI 120dpi (125% scaling)

## GitExt settings to reproduce
https://pastebin.com/SVhYtRLS

**Comment by gerhardol** [comment]
![image](https://user-images.githubusercontent.com/6248932/128684400-9ff988c2-73fc-42b4-b842-a5044e45e949.png)

Drag&drop is not planned, not feasible with WinForms.

**Comment by th3ragex** [comment]
@gerhardol Thank you very much! 😅
