### ISSUE TITLE
Low contast in MenuBarUI > ChangeCurentBranch dropdown

### ISSUE THREAD

**Issue by steventkim** [gitextensions/gitextensions#9467]
## Current behaviour

Often I see very low contrast options in the ChangeCurrentBranch dropdown list, as shown below.  Can someone please let me know either: a) what css property to set in the theme to remedy; or b) whether if this really a bug or intended behavior. Note that sometimes toggling between "View > Show current branch only" and "View >Show all branches" seems to remedy this for a few operations.

## Expected behaviour

I'd expect the branch names to more clearly visible against the background.

## Screenshots

![GitExtensions_lowContrast](https://user-images.githubusercontent.com/88679287/128748499-39c20505-dfb2-4e03-b67e-5f9fa068b946.png)

## Did this work in previous version of GitExtensions

I don't remember seeing this behavior before v3.5

## Environment

- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

**Comment by mstv** [comment]
I agree, the "invisible" branches look like disabled although they can be selected. This is related to `View | Show current branch only`.
I do not know the details of this feature nor of the theming.

**Comment by gerhardol** [comment]
Maybe change only the icon, not gray-out?
This cannot be changed by theming.
Changed in #8414

**Comment by RussKie** [comment]
This is by design to indicate inaccessible branches. The same is in the
left panel.

The initial proposal was to move inaccessible branches under a different
node, but it was overruled.
