### ISSUE TITLE
Rendering failure in the GitExtensions toolbar

### ISSUE THREAD

**Issue by simonmckenzie** [gitextensions/gitextensions#9469]
## Current behaviour

Error appeared suddenly while the app was running in the background, and the toolbar could be seen to have rendering issues (the white box with red cross is how it rendered!):

![screenshot of toolbar with rendering error](https://user-images.githubusercontent.com/17579442/128784971-676cc334-4ef0-4840-b150-3bfa950969e3.png)

## Expected behaviour

No error!

## Steps to reproduce

Can't - this happened in the background.

## Error Details
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.ToolStripItemCollection.get_Item(Int32 index)
   at System.Windows.Forms.ToolStrip.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at GitUI.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
This must have been triggered by a background task, as I was not using GitExtensions at the time.
The issue appears to be related to the toolbar, as I can see that it's rendering as a big red "x".

## Environment
- Git Extensions 3.5.1.12196
- Build 9099a1e76d01dbbd6896d6b026027db0b68fba96
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

**Comment by NikolayXHD** [comment]
hi, @simonmckenzie. A few questions about the moment the issue happened

- Was it a local PC or Remote Desktop, or any other remote control software session.
- Have you changed around that time
  - screen DPI
  - windows visual theme
- do you have different DPI settings on different screens (if you have multiple screens). If so, did you move GitExtensions window or another application's window between screens.

**Comment by NikolayXHD** [comment]
From the stack trace I would assume an item was added or removed to the bar, which happened outside UI thread, or something similar. 

I will examine the cases where we alter menu items from async code, see if I can see something suspicious.

**Comment by simonmckenzie** [comment]
Hi @NikolayXHD!

Sorry I can't help more...
- This happened on my local machine
- I wasn't making any changes to the theme or DPI
- While I do have two monitors, they both have the same DPI settings
- I don't believe I had just moved a window from one screen to another (I think I was typing at the time of the error), but I can't be sure

I doubt this will help, but I was working on one screen while GitExtensions was on the other screen. My monitors are also different resolutions, if that could have an effect. I have only seen this happen once.
