### ISSUE TITLE
Multiple branch selection in the toolbar filter

### ISSUE THREAD

**Issue by ddimkovikj** [gitextensions/gitextensions#9472]
## Feature description

This feature request is a follow-up to #3546 where the option to filter by multiple branches was added.

With the current feature I am not able to select another branch in the toolbar filter. 
Instead, I need to do the following steps:
* Select the first branch in the toolbar filter
* Select the second branch from the branch panel
* Go to the left panel and copy the name of the second branch
* Return to the toolbar filter, add "space" and paste the copied name of the second branch

IMO, this can be improved to work similar to a multi-select dropdown list:
 ![](https://i.stack.imgur.com/mkEc6.gif)

## Environment

- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.28.0.windows.1 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.18363.0
- .NET Framework 4.8.4390.0
- DPI 96dpi (no scaling)

**Comment by ddimkovikj** [comment]
I can grab this and submit PR if this feature gets approved.

**Comment by gerhardol** [comment]
See also #9412 
If that solution is good for you, please review it, if you have better ideas suggest changes or make a new PR, just agree with @RussKie first in the PR.
I would prefer to ctrl-click to select instead.

**Comment by RussKie** [comment]
What's a "taskbar filter"?

**Comment by mstv** [comment]
I guess "toolbar".

**Comment by ddimkovikj** [comment]
@RussKie yes, I meant "toolbar", pardon me. I'll edit the title to avoid confusion.

@gerhardol sounds good, ctrl-click is even better solution. 
Will further discuss this with RussKie.

**Comment by RussKie** [comment]
I think we should change the filter dropdown to a checkbox list (I think it should be doable), and allow a mutli selection. 
The left panel can have its context menus extended to 
- "add to filter" for currently filtered out branches, if filter is applied; and
- "remove from filter" for currently filtered branches, if filter is applied.
Otherwise these menus aren't visible.

How does that sound?

**Comment by ddimkovikj** [comment]
Yes, this looks like a good solution.
Since these are two separate features(even though they give the same result ), it'd be good to isolate them and have better focus and overview on each one of them. So, I'll create 2 WIP PRs:
* Filter multiple branches from branch filter
* Filter multiple branches from left branch panel
We can continue the implementation details there.

**Comment by gerhardol** [comment]
What I want is to be able to multiselect in left panel (ctrl, shift click). This is kindof possible right now, but ctrl-click only selects rev grid commits.
The selected branches context menu control what is possible.

> Since these are two separate features(even though they give the same result ),

yes
For the left panel, filter from multi selection is just a side effect. (Filter one by one will give the same result, just less convenient to work with.)
Branch filters is not something I normally use.

> The left panel can have its context menus extended to

Similar to #9445 for path filters, seem fine to me

> I think we should change the filter dropdown to a checkbox list (I think it should be doable), and allow a mutli selection.

I would prefer to have the branch filter as readonly instead if a text filter cannot be used. A dropdown with checkboxes is not really used in GE now.

Regardless, the contents/behavior for branchfilter in toolbar should be the same as in the advanced filter.
