### ISSUE TITLE
"Create branch..." has a wrong layout on 4k monitor, 150% DPI scale.

### ISSUE THREAD

**Issue by lanzhiquan** [gitextensions/gitextensions#9491]
## Screenshots

<img width="464" alt="2021-08-13_091302" src="https://user-images.githubusercontent.com/11311878/129291219-dbd4cc1e-342b-4291-8abe-f33c123c8bd0.png">

## Environment

- GitExtensions version:GitExtensions-Portable-3.6.0.12527-d8ddc1f6e.zip
- GIT version: 2.32.0.windows.1
- OS version: Windows 11 Preview
- .NET version: 4.8+.Net Core 5.0

**Comment by RussKie** [comment]
This is likely an underlying Windows Forms runtime issue.
