### ISSUE TITLE
[NBug] Значение не может быть неопределенным.Parameter name: value

### ISSUE THREAD

**Issue by Bondixi** [gitextensions/gitextensions#9493]
:warning: The sections below must be filled in and this text must be removed or the issue will be closed.

## Steps to reproduce
I just click on Console tab

## Error Details
```
System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: value
   в ConEmu.WinForms.ConEmuStartInfo.set_ConsoleProcessCommandLine(String value)
   в GitUI.CommandsDialogs.FormBrowse.<FillTerminalTab>b__201_0(Object sender, TabControlCancelEventArgs args)
   в System.Windows.Forms.TabControl.OnSelecting(TabControlCancelEventArgs e)
   в System.Windows.Forms.TabControl.WmSelChange()
   в System.Windows.Forms.TabControl.WndProc(Message& m)
   в GitUI.CommandsDialogs.FullBleedTabControl.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

## Additional information
I just click on Console tab

## Environment
- Git Extensions 3.5.2.12435
- Build 77413699a9c25b160a6a622311529372b5d87f5b
- Git 2.32.0.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

**Comment by Bondixi** [comment]
![image](https://user-images.githubusercontent.com/1491209/129339468-e09b306b-b966-457f-ad22-6c1a239e9239.png)
Set cmd helped

**Comment by gerhardol** [comment]
Duplicate of #9471
Set path to Linux tools
