### ISSUE TITLE
crash after watch diff

### ISSUE THREAD

**Issue by czhang-cpu1** [gitextensions/gitextensions#9500]
## Current behaviour

 firstly i double click a commit to watch diff, then i close the diff window, it will crash , must restart it to use it 

## Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by gerhardol** [comment]
Versions etc and stacktrace is mandatory to be able to say something about the issue.
You also need a detailed description with a repo where this can be reproduced.

**Comment by czhang-cpu1** [comment]
i have tried to revert to an older version firstly, then i download newest version 3.5.2.12435 and re-install it , the issue can not be reproduced any more.  
The issue was occured when i use Help-> Check for updates to get the newest version.
There may be some differences in two update methods?
