### ISSUE TITLE
Delete remote branch together with local branch

### ISSUE THREAD

**Issue by EpsilonD3lta** [gitextensions/gitextensions#9515]
## Feature description
Allow to delete local and remote branch in one action. I would like to have a checkbox "Delete remote branch [name]" under Force delete checkbox
![image](https://user-images.githubusercontent.com/30054007/129883504-1cb99207-14e2-470b-a109-69ed5b51688b.png)

**Comment by vbjay** [comment]
That's by design.

**Comment by vbjay** [comment]
We have a plugin you can look at.
