### ISSUE TITLE
After update "View - Show current branch only" no longer filter out branches and reset to "View - Show all branches" every time I switch repository

### ISSUE THREAD

**Issue by NaZaRKIN123** [gitextensions/gitextensions#9517]
## Current behavior

Today I updated to a newer version of GIT Extensions and it stopped filtering branches by using the "View - Show current branch only" option.
Also when I switch repositories from the toolbar it resets to "View - Show all branches".

## Steps to reproduce

1. Open Git extensions having 2 repositories and 2 branches in some of in
2. Open repository with 2 branches
3. Go to View and select "Show current branch only"
Expected: Only the current branch head is shown.
Actual: Multiple head branches are shown
4. In the toolbar select second repository
5. In the toolbar select the first repository again
Expected: "View - Show current branch only" option is selected
Actual: It got reset to "View - Show all branches"

## Screenshots

![image](https://user-images.githubusercontent.com/19157402/129921112-10d8289f-0b68-4089-8bc1-1a875a197b06.png)

## Did this work in the previous version of GitExtensions

Yes, it was. I'm not sure, I wasn't updating it for a few months.

## Environment

- Git Extensions `3.5.3.12551`
- Build `00604a59a673142a3d34a22aa657466a922977f3`
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4300.0
- DPI 120dpi (125% scaling)

**Comment by NaZaRKIN123** [comment]
@RussKie Any comments on why it was closed??

**Comment by RussKie** [comment]
I'm not sure.... sorry. It may have accidentally got in the midst of other
stale issues I was closing today from the phone.

I'll come back to it tomorrow or over the weekend.

**Comment by RussKie** [comment]
I can't repro it... Is it happening for all repos or only selected one? 

![image](https://user-images.githubusercontent.com/4403806/130346932-4a730932-358c-49f3-a4dc-d7e974008c1c.png)

**Comment by NaZaRKIN123** [comment]
> I can't repro it... Is it happening for all repos or only selected one?
> 
> ![image](https://user-images.githubusercontent.com/4403806/130346932-4a730932-358c-49f3-a4dc-d7e974008c1c.png)

It happens always after I switch repositories from dropdown next to branch dropdown. Rarely it works fine, but mostly not.

**Comment by RussKie** [comment]
The filter is reset when a new repo is opened. This is by design.

**Comment by NaZaRKIN123** [comment]
> The filter is reset when a new repo is opened. This is by design.

Is it new feature? Can I change this behavior somehow? If not, I'll revert to use old version and never update :(

**Comment by NaZaRKIN123** [comment]
Anyway filtering by only selected doesn't work almost always.

**Comment by RussKie** [comment]
Please provide an animation to better understand your issue

**Comment by pmiossec** [comment]
> Anyway filtering by only selected doesn't work almost always. 

Could you give an example of branch name that's not working?
Does it contain some 'strange' characters (space, -,...)?

**Comment by NaZaRKIN123** [comment]
> > Anyway filtering by only selected doesn't work almost always.
> 
> Could you give an example of branch name that's not working?
> Does it contain some 'strange' characters (space, -,...)?

Yes, our usual branch name is something like "Story/Story-id-Story_title". It wasn't a problem before and on the latest version, it happens randomly.

**Comment by NaZaRKIN123** [comment]
> Please provide an animation to better understand your issue

Added list menu wasn't captured for some reason, but in it, I select "Show current branch only" and notthing happens. See my selections on this menu on the screens above.
https://user-images.githubusercontent.com/19157402/130610530-381120df-e5a7-45ae-bbc2-d82b2ffa2d45.mp4

**Comment by Shauren** [comment]
I would like to also voice my dissatisfaction of resetting current/all branch selection on repository change being "by design" and either request this being changed back to how it was in older version or be made configurable. I almost always exclusively show only current branch (except when I need to cherry-pick) because I have no reason to care about work-in-progress remote branches of my coworkers

**Comment by RussKie** [comment]
Please provide a stable repro and/or animation of the issue.

**Comment by Shauren** [comment]
https://user-images.githubusercontent.com/297439/131491749-ce7d14d8-ae0a-472d-9f2b-4177b2f5c9ca.mp4

**Comment by RussKie** [comment]
No, this looks like a bug "Show current branch" is supposed to be sticky and persist across repo switch...

**Comment by RussKie** [comment]
The regression was introduced in https://github.com/gitextensions/gitextensions/pull/8489

**Comment by NaZaRKIN123** [comment]
> I would like to also voice my dissatisfaction of resetting current/all branch selection on repository change being "by design" and either request this being changed back to how it was in older version or be made configurable. I almost always exclusively show only current branch (except when I need to cherry-pick) because I have no reason to care about work-in-progress remote branches of my coworkers.
> 
> I like to think of the repository switcher as a shorter way to achieve
> 
> * Close gitextensions
> * Navigate in explorer to other repository
> * Open gitextensions
> 
> When doing that sequence of actions, current/all branch filter does not change

Totally agree.

**Comment by RussKie** [comment]
Please try this build https://ci.appveyor.com/project/gitextensions/gitextensions/builds/40590709/artifacts

**Comment by NaZaRKIN123** [comment]
> Please try this build https://ci.appveyor.com/project/gitextensions/gitextensions/builds/40590709/artifacts

Unfortunately, I can't run unsigned packages for security reasons.

**Comment by Shauren** [comment]
I confirm this fixes the issue for me

**Comment by NaZaRKIN123** [comment]
Not repro anymore. Thanks!
