### ISSUE TITLE
Plugin manager disappeared after update

### ISSUE THREAD

**Issue by MISTikus** [gitextensions/gitextensions#9530]
## Current behaviour

After update from 3.5.2 to 3.5.3 Plugin manager disappeared from Plugins menu

## Expected behaviour

Use plugin manager and it's plugins

## Steps to reproduce

Update GitExt from 3.5.2 to 3.5.3

## Screenshots

![GitExtPlugins](https://user-images.githubusercontent.com/11049459/130420664-f4c21b85-1872-4b52-a3ce-de0dca8d6fb7.png)

## Did this work in previous version of GitExtensions

Worked fine on GitExt 3.5.2

## Environment

- GitExtensions version: 3.5.3.12551
- GIT version: 2.33.0.windows.1
- OS version: Microsoft Windows NT 10.0.19043.0
- .NET version: 4.8.4400.0

**Comment by RussKie** [comment]
This is strange. I've updated few workstation and had a brand new installation, and haven't observed this.
The plugin manager lives here: `C:\Users\<user>\AppData\Local\GitExtensions\UserPlugins\GitExtensions.PluginManager`, check if this path exists.

Try repair the installation maybe?

**Comment by MISTikus** [comment]
> check if this path exists

yes, manager and plugins are on their places:
> ls C:\Users\m.timoshinin\AppData\Local\GitExtensions\UserPlugins
> Directory: C:\Users\m.timoshinin\AppData\Local\GitExtensions\UserPlugins
> 
> Mode                 LastWriteTime         Length Name
> ----                 -------------         ------ ----
> d----          23.08.2021    10:43                GitExtensions.PluginManager
> d----          27.04.2021     9:19                GitExtensions.SolutionRunner
> -a---          29.10.2020    14:30            424 NuGet.Config
> -a---          27.04.2021     9:19            199 packages.config

But I forgot to mention, that I updated GitExt using Choocolatey, here is the log file:
[chocolatey.log](https://github.com/gitextensions/gitextensions/files/7031027/chocolatey.log)

**Comment by MISTikus** [comment]
By some mysterious reason, today Plugin manager just shown...
So, if you don't mind, I'll close this issue... 

*sorry for bothering...

**Comment by RussKie** [comment]
All good, glad it worked.
