### ISSUE TITLE
Recent update hides commits (if show first parents is OFF)

### ISSUE THREAD

**Issue by rdstevens** [gitextensions/gitextensions#9548]
## Current behaviour

Make multiple commits.

Only the most recent commit is shown in the branch view.

(In effect, it's like the commits have been squashed. Toggling "show first parents" to ON reveals the commits. Pushing the HEAD to the remote repo and using a different UI shows the commits. Commandline git log shows the commits. Only GitExtensions appears to be hiding them!)

## Expected behaviour

All commits should be shown.

## Steps to reproduce

Clone a repo

Make multiple commits

Observe only the latest commit is shown

## Screenshots

Correct behaviour: Observe four commits between origin/master and HEAD:

02c55

a273b

b70e5

6eb0a

![image](https://user-images.githubusercontent.com/1841888/131480420-5402a1e6-a660-42a5-8731-44e113bb5bd5.png)

Incorrect behaviour: only two commits

02c55

6eb0a

![image](https://user-images.githubusercontent.com/1841888/131480504-0b255f48-ef98-4634-9f28-38d080e141fc.png)

Git log output:

```
commit 02c557244163eb25593a9239f5371ab237c545b0 (HEAD -> sv32_take2)
Author: rob <rdstevens@gmail.com>
Date:   Tue Aug 31 09:52:56 2021 +0100

    Project refs (updates)

commit a273bd68b0f6db1bf943093d5e59fcbc95a2f3a8
Author: rob <rdstevens@gmail.com>
Date:   Tue Aug 31 09:51:45 2021 +0100

    Use std::filesystem and printf logging instead of a heavyweight dependency on XXX.lib

commit b70e58958f5c904ba47863709fd7d9c92da6af4f
Author: rob <rdstevens@gmail.com>
Date:   Tue Aug 31 09:51:03 2021 +0100

    Autoversion merged into this repo

commit 6eb0a389efcdfd0c8ab9f380e992bacbd556b230 (origin/master, origin/HEAD, master)
Author: Robin Stevens <Robin.stevens@nice.com>
Date:   Mon Mar 8 12:42:30 2021 +0000

    WIP: Removed packages.config, using project refs instead
```

## Did this work in previous version of GitExtensions

Yes

## Environment

- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.30.2.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4341.0
- DPI 144dpi (150% scaling)

**Comment by RussKie** [comment]
Can you provide a sample repo and an animation of the issue?

**Comment by rdstevens** [comment]
Sample repo at https://github.com/rdstevens/gitexttest


https://user-images.githubusercontent.com/1841888/131514151-bb877eed-945f-4325-8dfc-f516b8a8e6da.mp4

Video shows two commits being made: "Said hello" and "Said goodbye" (the contents of the commits doesn't matter).

In the default view, the "Said hello" commit gets *hidden* by the "Said goodbye" commit.

In the show-first-parent view all commits are visible.

Git.exe log command also shows all commits.

GitExtensions *used* to show all commits in default view.

**Comment by RussKie** [comment]
Unfortunately it is hard to get the full picture from the video, as a lot of actions is clipped and happening offscreen... I tried to follow the steps and set the view as per your settings (at 0:40 mark) but I was unable to replicate your issue:
![9548](https://user-images.githubusercontent.com/4403806/132087325-2101ae71-c521-4b24-84c8-6a177c87b7a2.gif)
What am I missing?

PS: For screen grabs consider using https://github.com/NickeManarin/ScreenToGif.

**Comment by rdstevens** [comment]
It looks like you're doing the exact same stages as me - but not seeing the problem.

I don't get the problem on a different machine (same software versions).

An uninstall/install cycle on this machine still shows the problem.

Is there some cached settings I can try deleting?

**Comment by pmiossec** [comment]
What you could try:

1. Compare the git configurations `git config --list --show-origin`
2. And also run the `git log` command (the one that is run when refreshing the revision grid) that you find in the "git command log" (F12) on the 2 computers and compare the results to see if they return a different result.

It may be this one: `git -c log.showSignature=false log -z --pretty=format:"%H%T%P%n%at%n%ct%n%e%n%aN%n%aE%n%cN%n%cE%n%s%n%n%b1DEA7CC4-FB39-450A-8DDF-762FCEA28B05" --all --boundary --not --glob=notes --not --max-count=100000 --`

![image](https://user-images.githubusercontent.com/460196/132368898-1d3af32a-33af-4848-ab78-80fc1e861823.png)

Maybe we will have to add a command line parameter to force a git option to a specific value that you have changed locally...

**Comment by rdstevens** [comment]
I deleted my AppData/Roaming/GitExtensions/GitExtensions folder and restarted. It's working now!

I can supply the "broken" settings for analysis if you're interested?

**Comment by RussKie** [comment]
Yes, please.

**Comment by rdstevens** [comment]
[GitExtensionsX.zip](https://github.com/gitextensions/gitextensions/files/7127716/GitExtensionsX.zip)

See attached.

**Comment by rdstevens** [comment]
If you can determine which setting it is, I'd love to know. (I miss it now it's gone! But I would like to be able to turn it on and off...)

**Comment by rdstevens** [comment]
I think it's this:

![image](https://user-images.githubusercontent.com/1841888/132486848-df766a6c-5bb6-4ee4-aa63-288f21c5d764.png)

Note: Empty branch name, check "Branches" and "Simplify by decoration"
