### ISSUE TITLE
More Protection on Keyboard Shortcuts

### ISSUE THREAD

**Issue by kellenrhys** [gitextensions/gitextensions#9552]
## Current behaviour

When constructing a git commit message I staged some files and then was reviewing them in the left hand window clicking on files.  Then I tried to type the commit message which began with the word "reset".

Only typing "r"  then "e"  is rapid succession caused the file that was highlighted to reset to the form before I made changes.  This could cause a user a great deal of work.

## Expected behaviour

After typing the "r" keyboard shortcut to bring up the Reset Changes warning dialogue, no other keyboard key should cause the dialog to "reset" the file. Either pressing another key should do nothing or cancel without making any possibly destructive changes.

Alternatively there should be an obvious way to undo an accidental mistake like this or the default Reset changes key should be something harder to accidentally type.

## Steps to reproduce

Open a project in git extensions, make changes to a file. Open the commit dialog. Stage the file. Click on the staged file. type r then e quickly like you are trying to type a commit message that starts with the word 'reset'. 

## Did this work in previous version of GitExtensions

I'm not sure if this changed at some point but I never ran into this problem before today even though I've been using git extensions for years without adjusting the keyboard shortcuts.

## Environment

- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
> Alternatively there should be an obvious way to undo an accidental mistake like this or the default Reset changes key should be something harder to accidentally type.

I don't know if it could be considered obvious and you still need it to recover your file but if you just staged the file, you could find the content of the file near the top of the 'recover lost objects' form :
![image](https://user-images.githubusercontent.com/460196/131707929-8c8d14f2-f79a-4aec-b72f-eb39556d80c6.png)

![image](https://user-images.githubusercontent.com/460196/131707768-a6001c92-2da9-43db-a0e5-fa7224133a0d.png)

**Comment by kellenrhys** [comment]
Thanks. That wasn't obvious to me. Fortunately I got lucky and the changes I lost weren't a big deal so I was able to just redo them and complete the project. I wasn't able to try your recovery method. But I'll keep that in mind in case I run into future issues.

For now I also unmapped the 'r' shortcut entirely to prevent this issue.

**Comment by RussKie** [comment]
You're welcome to submit a PR with a fix.
