### ISSUE TITLE
Commit Dialog Shift Select Index is Incorrect (likely started in 3.50 timeframe?)

### ISSUE THREAD

**Issue by XopherThomas** [gitextensions/gitextensions#9563]
I believe it was during the changeover to the 3.50 time frame, but when opening the Commit dialog with several modified/changed/added/etc items. The top item has the highlighted selection.  Attempting to Press Shift and click to select some items of the list, always starts from the bottom of the list and selects up the the clicked on item.  I believe the Shift Select should select from the actively highlighted first item down to the place where the click occurred.

Steps to reproduce:
1.  Open commit dialog with changed files.  Observe first item is selected.
2. Shift click an item down the list.  Observe highlight of multiple selected files occurs from the bottom of the list

Expected behavior:
Shift select should highlight from the first (highlighted) item down to the shift selected item.

Erroneous behavior:
Shift select instead highlights from the last item in the list up to the shift selected item.

Additional details:
1.  Once you select on any particular item, everything behaves as expected.
2. Suggested culprit is a 'current index' variable that is left at the list item in the last after populating rather than being set to the first item in the list which gets the default highlight.

**Comment by pmiossec** [comment]
Duplicate of #9363

**Comment by XopherThomas** [comment]
Thank you.  I did not find the right search params when I checked for existing issue report.

**Comment by pmiossec** [comment]
No problem, I had difficulties to find the issue even if I new it exists...
