### ISSUE TITLE
Glitchy black dropdowns after leaving program open for a while

### ISSUE THREAD

**Issue by nyanpasu64** [gitextensions/gitextensions#9567]
## Current behaviour

After using Git Extensions for some time, I sometimes run into rendering errors (though I'm not sure what causes them). I believe I've seen Git Extensions show glitchy black dropdowns before.

I also noticed that sometimes the right-click menus switch from the WinForms shiny theme to a Windows Classic style theme with gray backgrounds and blue highlights. However this did not happen this time, and it happens independently of the corrupted dropdown menus.

## Expected behaviour

UI renders correctly.

## Steps to reproduce

???

At some point, Git Extensions will display glitchy graphics in place of the dropdown menu. Clicking may result in the black box being partly replaced by white, or screen contents pulled from elsewhere in the program (I don't think other programs?).

## Screenshots

![GitExtensions_RqiK0NBSVb](https://user-images.githubusercontent.com/913957/132984290-fe3992a1-ba04-44f5-9a58-75b8c449d362.png)

## Did this work in previous version of GitExtensions

Don't think so?

## Environment

- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4400.0
- DPI 120dpi (125% scaling)

I was switching between different DPI settings, however by itself that doesn't cause the graphical issue to occur, it only causes Git Extensions to render blurry until I switch back to the startup DPI.

**Comment by RussKie** [comment]
> I also noticed that sometimes the right-click menus switch from the WinForms shiny theme to a Windows Classic style theme with gray backgrounds and blue highlights. However this did not happen this time, and it happens independently of the corrupted dropdown menus.

Fixed in https://github.com/gitextensions/gitextensions/pull/9608



> I was switching between different DPI settings, however by itself that doesn't cause the graphical issue to occur, it only causes Git Extensions to render blurry until I switch back to the startup DPI.

As a workaround - restart the app after changing DPI. v3.x are built on .NET Framework which isn't super optimised for high DPI and DPI changes.

**Comment by nyanpasu64** [comment]
I don't know if "glitchy black rendering" and "classic menus" are caused by the same thing, and I opened a separate bug for "Classic menus". I think this issue should be reopened until the commit makes it to a release (or I install a dev build) and I verify I don't get glitchy black rendering for days or so.
