### ISSUE TITLE
"Open with difftool" menu switches right-click menus to Classic style

### ISSUE THREAD

**Issue by nyanpasu64** [gitextensions/gitextensions#9568]
## Current behaviour

When I click a commit, switch to the diff tab, right-click a filename, and expand the "Open with difftool" menu, the menu switches to classic theme. Other menus (like right-clicking a commit) may or may not switch to classic theme when expanding a submenu.

## Expected behaviour

Expanding menus does not corrupt theming.

## Steps to reproduce

- Open a repository in Git Extensions, and click a commit in the history.
- In the bottom pane, click the Diff tab.
- In the left bar, right-click a filename.
- Hover the "Open with difftool" menu to expand it.

## Screenshots

![GitExtensions_KGY7rdCq8b](https://user-images.githubusercontent.com/913957/133022426-11df1fcb-a7f2-43d4-b07a-030124bd39e4.png)

## Did this work in previous version of GitExtensions

Unsure.

## Environment

- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4400.0
- DPI 120dpi (125% scaling)

This *may* be related to #9567.

**Comment by RussKie** [comment]
Quite peculiar... I can repro it in the default (system) theme:
![9568](https://user-images.githubusercontent.com/4403806/133279240-cc32b0a3-0f95-4a39-a42b-d7fe60f3c147.gif)

**Comment by nyanpasu64** [comment]
My guess is that it's caused by the grayed out text.

**Comment by Greybird** [comment]
@RussKie: I see you took the issue assignment, but I took the liberty to propose a very small fix.

**Comment by RussKie** [comment]
No worries, all good 👍
