### ISSUE TITLE
button Prune Remote Branches not visible

### ISSUE THREAD

**Issue by geerligs** [gitextensions/gitextensions#9606]
## Current behaviour

The button Prune Remote Branches is not visible in Repository -> Remote repositories -> Default Pull Behavior
However the function can be found on the context menu of the branches view

## Expected behaviour

I expect the buttons Prune Remote Branches and Update All remote Branch Info

## Steps to reproduce

Select Repository -> Remote repositories -> Default Pull Behavior and observe the dialog

## Screenshots

![prunedialog](https://user-images.githubusercontent.com/6309628/135582427-786152d7-8c89-4d27-9996-7a06b25be069.png)

![contextmenu](https://user-images.githubusercontent.com/6309628/135582591-9b3ff35f-4a0f-4004-b9c9-abe22bd915e5.png)

## Did this work in previous version of GitExtensions

I did not use this function in a previous version of GitExtensions

## Environment

- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.32.0.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4400.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Why is it necessary there?

**Comment by geerligs** [comment]
It is not necessary to put the button in Repository -> Remote repositories -> Default Pull Behavior as long as it is available in the context menu. 
I think the documentation needs to be updated to enable the user to find the prune remote feature.

**Comment by pmiossec** [comment]
In fact, the feature is also in the fetch button:

![image](https://user-images.githubusercontent.com/460196/135602953-68682604-4268-44a9-b1e9-fbe4331e846b.png)

**Comment by pmiossec** [comment]
> I think the documentation needs to be updated to enable the user to find the prune remote feature.

The documentation is here https://github.com/gitextensions/GitExtensionsDoc
If you think it needs improvement, please send a Pull request...

**Comment by geerligs** [comment]
Thanks for the hint on fetch: I have set this as default now.

**Comment by pmiossec** [comment]
@geerligs But if you could still update/fix the documentation, that would be great!!!
