### ISSUE TITLE
.net5: dotnet publish does not include plugins

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#9614]
## Current behaviour

`dotnet publish` only includes the main app, not the default plugins.
The portable build in Appveyor (as well as for private builds) does not include the plugins.

Working in builds started from the build path `artifacts\Debug\bin\GitExtensions\net5.0-windows`

## Expected behaviour

Plugins included

## Steps to reproduce

See Appveyor artifacts

## Did this work in previous version of GitExtensions

This is only in master (.net5).
(May have been OK in earlier .net5 builds, do not remember.)

## Environment

- Git Extensions 33.33.33
- Build 810519e1fbdc4d618414bc4042e008a705164d86
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET 5.0.10
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
> Plugin Manager... is missing...

I think this is because it is still targeting .NET Framework. /cc: @maraf

**Comment by mstv** [comment]
OT: How do you create these code links quickly, @RussKie:?

**Comment by RussKie** [comment]
> OT: How do you create these code links quickly, @RussKie:?

This is a permalink to a code:
![image](https://user-images.githubusercontent.com/4403806/137648888-8810876e-190e-4bd1-bdb0-7ec2fe353661.png)

**Comment by RussKie** [comment]
> Jira Commit Hint is missing

I spent a little time trying to debug it, and the plugin assembly is being considered for loading but then it fails to load with the following error:
```
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Could not load file or assembly 'Atlassian.Jira, Version=12.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```
I was unable to debug into why it is happening.

**Comment by RussKie** [comment]
Tracking the PM migration in https://github.com/gitextensions/gitextensions.pluginmanager/issues/57
