### ISSUE TITLE
Labels in the branch context menu are missing ellipses (...)

### ISSUE THREAD

**Issue by simonmckenzie** [gitextensions/gitextensions#9641]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

### Issue description

The context menu shown when right-clicking on a branch contains a number of options which require additional steps to complete:
- Rename
- Rebase
- Checkout
- Merge
- Reset
- Delete
- Create Branch

![image](https://user-images.githubusercontent.com/17579442/136740045-a8babc26-4169-43cc-95dd-6ae07de8df3d.png)

Of these, only "Create Branch" has the appropriate ".,," to show that selecting the option will not change anything without further confirmation. For "rebase" and "reset" in particular, it would help the user to understand that more options are available, like interactive rebase or soft/mixed/hard/merge reset.

### Steps to reproduce

Right-click on a branch and view the labels

### Did this work in previous version of GitExtensions?

Not that I know

**Comment by simonmckenzie** [comment]
I'm happy to help fix this, but wasn't entirely sure how the `.xlf` translation engine worked. I made some changes in `English.xlf`, but didn't see any change in the UI...

**Comment by RussKie** [comment]
The labels in the left panel's context menu need to be aligned with the main menu and the context menu in the revision grid.
