### ISSUE TITLE
JiraCommitHint plugin is not loading

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9659]
_Originally posted by @RussKie in https://github.com/gitextensions/gitextensions/issues/9614#issuecomment-945216968_

The plugin fails to load with the following error:
```
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Could not load file or assembly 'Atlassian.Jira, Version=12.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
```

Two proposed ways to solve it:
1. (Preferred) Move the plugin out to its own repo. 
I personally haven't seen a significant activity from @ierof (the original author of the plugin), and the core team doesn't have much capacity nor intent to support this plugin. Members of the community, who use the plugin and may have come to depend on it, are welcome to become stewards of the repo and continue with the development.
2. Fix the load issue.

**Comment by gerhardol** [comment]
Some other issues with Jira Commit Hint closed and linked here, to be considered if the plugin is resurrected

**Comment by ierof** [comment]
Hi all!
I apologize for the long silence.
I suppose problem is beacuse of Unsigned [Atlassian.NET SDK](https://bitbucket.org/farmas/atlassian.net-sdk/src/master/)
I'll try to fix it.

**Comment by RussKie** [comment]
The plugin should be moved out to its own repo and installed with the
Plugin Manager.

For more information please refer to
https://github.com/gitextensions/gitextensions.plugintemplate.

Other existing plugins may be helpful as well:
https://github.com/topics/gitextensions-plugin.

**Comment by ierof** [comment]
Hm, the issue seems to be more comlicated. It looks like MEF and probing doesn't work together.

> The plugin should be moved out to its own repo and installed with the Plugin Manager.
Ok, I'll try to do this.

**Comment by ierof** [comment]
> It's building and packing, but not publishing yet

https://www.nuget.org/packages/GitExtensions.JiraCommitHintPlugin
But I can't test it "in production" because of #10524 ;-)
