### ISSUE TITLE
Accumulate revert messages when reverting multiple commits

### ISSUE THREAD

**Issue by V0d01ey** [gitextensions/gitextensions#9667]
## Feature description

Reverting multiple commits saves only last revert message for the revert commit.
It would be great to accumulate revert messages for commit message.

## Environment

- GitExtensions version: 3.5.4.12724
- GIT version: 2.31.1.windows.1
- OS version: Windows NT 6.1.7601 SP1
- .NET version: 4.8.4069.0

**Comment by pmiossec** [comment]
> Is git combining messages when you run a revert command?

No (like I explained in my previous message).

I would say it should not be too difficult to do by saving '. git/COMMIT_MSG' file just before doing the revert and after inserting the value saved at the beginning of the new content...
