### ISSUE TITLE
Proposal to improve Delete obsolete branches performance

### ISSUE THREAD

**Issue by hieuxlu** [gitextensions/gitextensions#9675]
## Feature description
- For repos with > 400 stale branches, some current behavior of "Delete obsolete branches" dialog is causing unnecessary delays, as listed below
  - When deletion is finished, the dialog calls `RefreshObsoleteBranchesAsync` causing unnecessary search and pull logs for all remote branches. Instead, I propose we can just remove deleted branches from local Data Grid data source. If the user wants to refresh branch search result, they will just need to click Search again. We should not search remote branches again after deletion
https://github.com/gitextensions/gitextensions/blob/040f2eb017b42ea436056d65344afcf40be33d54/Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs#L222
  - By default, listed branches will contain a remote branch named `origin/HEAD -> origin/master`. This will cause great confusion, because this supposed branch is included in deletion list by default. We should remove this from remote branch list 
  <img src="https://user-images.githubusercontent.com/11418231/138578751-93f6a70c-097d-4c6b-85c5-f18dbe5f7544.png" width="500">

## Proposal
- [ ] Do not call `RefreshObsoleteBranchesAsync` after deletion to avoid search from remote again
- [ ] Remove `origin/HEAD -> origin/master` from branch list

## Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4420.0
- DPI 144dpi (150% scaling)

**Comment by RussKie** [comment]
Apologies for the delay. Given this is a plugin, I don't really have any significant concerns. Feel free to send a PR in :)
