### ISSUE TITLE
Feature Request: Search Bar in "Recent Repositories"

### ISSUE THREAD

**Issue by sopgreg** [gitextensions/gitextensions#9709]
### Feature description

I have a lot of projects in my "Recent Repositories", some of them are rarely used. It would be very handy to have a search bar which does a substring match to filter all the repositories or their branch names:

![grafik](https://user-images.githubusercontent.com/33895520/140716728-3cdc1644-3f4e-4d15-b063-76f87cbdad7a.png)

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

**Comment by pmiossec** [comment]
Done in #9380 waiting to be released...
