### ISSUE TITLE
Unable to `Reset selected lines` from diff of two commits

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9714]
### Environment

- Git Extensions 33.33.33
- Build 34108e4ef0482849d5f6bc2085008ced85c9fcb7 based on 2bde8f93e9602e57b22872d814fbd28c3dba593b
- Git 2.33.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 5.0.5
- DPI 96dpi (no scaling)

### Issue description

git error "<file> does not match index" when resetting selected lines from a diff of two commits:

![grafik](https://user-images.githubusercontent.com/36601201/140947265-91ceb763-70c9-4600-a334-e5b91d20190a.png)

### Steps to reproduce

- modify a line of a tracked file
- select a grandparent commit and the artificial commit `Working directory`
- select the modified lines in the diff
- hit `R` (`Reset selected lines`)

### Did this work in previous version of GitExtensions?

?

### Diagnostics

exit code 1 from `git apply --3way --index --whitespace=nowarn`

**Comment by gerhardol** [comment]
"does not match index": Are you hiding whitespace?

**Comment by mstv** [comment]
> Are you hiding whitespace?

No, I didn't. (If I do, I turn it off for line operations.)
Though it was a change in trailing whitespace.
Resetting it worked when only WDir was selected.

**Comment by gerhardol** [comment]
There is no simple way around this.
https://git-scm.com/docs/git-apply#Documentation/git-apply.txt---3way
--3way is fallback, tries to use 3-way merging as a fallback.
This implies --index (included explicitly here).
If the worktree and index for the file do not match, you get this message.

The message "Failed first apply and cannot use -3way as the worktree does not match index" is a little long.

So I cannot see how this can be changed in a simple way.

**Comment by mstv** [comment]
My usecase was / is "preview the result of an Amend Commit".
There will be less need when we add the button "Soft reset for amend" (as proposed in another issue).

If the "Reset lines" feature cannot work between the WDir and a commit, the menu item and the hotkey should be disabled. I know that the regarding logic is complex already.
=> low prio (even very low for me, I don't mind closing this issue.)
