### ISSUE TITLE
Toolbar togglebuttons highlight frame only

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9715]
### Environment

- Git Extensions 33.33.33
- Build 34108e4ef0482849d5f6bc2085008ced85c9fcb7 based on 2bde8f93e9602e57b22872d814fbd28c3dba593b
- Git 2.33.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 5.0.5
- DPI 96dpi (no scaling)

### Issue description

**Actual**

![grafik](https://user-images.githubusercontent.com/36601201/140949654-4ed9318f-3aa6-456b-850d-ef535584b93e.png)

**Expected**

![grafik](https://user-images.githubusercontent.com/36601201/140949749-8cbfa113-6005-458b-94a5-cb346c0f8819.png)

### Steps to reproduce

👀

### Did this work in previous version of GitExtensions?

yes, I guess at least 89b98694dd425ab9fc13281ae2fb613df3eb9c2f (side effect of #9608?)

**Comment by Greybird** [comment]
Just took time to check, and I can confirm this is a side effect of #9608.
I will investigate to see how this could be solved.

**Comment by gerhardol** [comment]
Closed by #9795
