### ISSUE TITLE
Filter with "Diff contains (SLOW)": no results

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9716]
### Environment

- Git Extensions 33.33.33
- Build 34108e4ef0482849d5f6bc2085008ced85c9fcb7 based on 2bde8f93e9602e57b22872d814fbd28c3dba593b
- Git 2.33.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 5.0.5
- DPI 96dpi (no scaling)

### Issue description

Filtering for diff contents quickly finishes without any hit:

![grafik](https://user-images.githubusercontent.com/36601201/141285159-f8284fc6-5431-4fe1-81e0-15e55ffc295e.png)

because the - not correctly updated - `Advanced Filter` acts as prefilter:

![grafik](https://user-images.githubusercontent.com/36601201/141288987-63ce6088-22aa-43a3-8899-b4b866088f32.png)

(Deleting the filter text from the toolbar does not suffice to bring back the unfiltered results because the filter is not removed from the `Advanced Filter` if the `Commit message and hash` is unticked.)

### Steps to reproduce

- enter search text (which is not found in commit messages)
- tick `Diff contains (SLOW)`
- untick `Commit message and hash`
- hit `Enter`
- hit `F5`
---
- delete search text
- hit `Enter`
- hit `F5`

### Did this work in previous version of GitExtensions?

yes, master latest one month ago

### Diagnostics

There is no long running git.exe in the background.

Sometimes, it works as expected - perhaps depending on the sequence of setting flags and text.

**Comment by gerhardol** [comment]
I believe this was fixed with #10127 and some related prs

**Comment by mstv** [comment]
> I believe this was fixed with #10127 and some related prs

Yes, it works. Thank you.
