### ISSUE TITLE
Filter with "Diff contains (SLOW)": git hangs waiting for pdftotext

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9717]
### Environment

- Git Extensions 33.33.33
- Build 34108e4ef0482849d5f6bc2085008ced85c9fcb7 based on 2bde8f93e9602e57b22872d814fbd28c3dba593b
- Git 2.33.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET 5.0.5
- DPI 96dpi (no scaling)

### Issue description

GE runs
```
git -c log.showSignature=false log --max-count=200000 -z --pretty=format:"%H%T%P%n%at%n%ct%n%aN%n%aE%n%cN%n%cE%n%B" --all --boundary --not --glob=notes --not -G"search text" --full-history --simplify-merges --parents
```
git starts `sh astextplain`, which starts `pdftotext.exe`.
`pdftotext.exe` does not return most likely because the regarding temp file is not a PDF but just an LFS pointer.

Does GE run the correct command?
Can / should we suppress the extraction of text from documents?

### Steps to reproduce

![grafik](https://user-images.githubusercontent.com/36601201/141307342-8cc26342-a2bf-4a44-ad7d-4a1e8c52e169.png)

**Comment by mstv** [comment]
After killing the hanging git, GE does attempt to refresh the RevisionGrid at all - also not when switching repos using the toolbar or the Dashboard.

![grafik](https://user-images.githubusercontent.com/36601201/141309614-5388ad61-c32f-47b8-b162-11ecde4b1792.png)

**Comment by gerhardol** [comment]
> git starts `sh astextplain`, which starts `pdftotext.exe`. `pdftotext.exe` does not return most likely because the regarding temp file is not a PDF but just an LFS pointer.
> 
> Does GE run the correct command? 

Yes
https://git-scm.com/docs/git-log#Documentation/git-log.txt--Gltregexgt

> Can / should we suppress the extraction of text from documents?

Do you have any specific filters in any .gitattributes?
I assume this is `astextplain`:
https://stackoverflow.com/questions/28146244/what-is-the-difference-between-diff-and-diff-astextplain

I believe that `diff.astextplain.textconv` should be overridden here (and maybe diff.lfs.textconv).

> After killing the hanging git, GE does attempt to refresh the RevisionGrid at all - also not when switching repos using the toolbar or the Dashboard.

That is the handling when no response, could be removed.

**Comment by mstv** [comment]
Thank you for the links, Gerhard!

`.gitattributes` looks good as far as I understand:
```
*.pdf filter=lfs diff=lfs merge=lfs -text
```

`astextplain` has been configured by the installer I guess:

```
$ git config --system -l
diff.astextplain.textconv=astextplain
```
Since GE does not specify the argument `--text` for `git log -G`, I would expect no attempt to convert non-text files.
But `astextplain` might be the default for `git lfs`.

Unsetting `diff.astextplain.textconv` did the trick. Luckily, I also don't need it in no other situation.

---

The "empty repo" display has recovered in the meantime. Perhaps there was another long running git.
We should cancel them on refresh of the RevisionGrid, e.g. by sending a `SigInt` / `Ctrl+C` to the git process.
