### ISSUE TITLE
The app doesn't do anything (clone, pull, push)

### ISSUE THREAD

**Issue by skorenb** [gitextensions/gitextensions#9724]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

### Issue description

The Git Extensions app does not anything except commit listing for exist local repositories.
![image](https://user-images.githubusercontent.com/16142606/141656374-9e531967-e253-4d18-ab6f-1802b1f4c685.png)
I've already tried to reinstall the app completely - it gives no effect. The problem still remains.
Although, git via bash works fine.
![image](https://user-images.githubusercontent.com/16142606/141656390-39140870-a227-43c5-aabd-dab4aad4a3ad.png)

Please, tell me what else i can do!

### Steps to reproduce

I have no idea what steps i can perform to get this issue

### Diagnostics

Here i upload log of failed clone command (exit code 259)
[git extensions log.txt](https://github.com/gitextensions/gitextensions/files/7532585/git.extensions.log.txt)

**Comment by RussKie** [comment]
Closing due to age, hope you resolved the issue. It looks like the app was failing (likely due to ConEmu) with exit code 259.
