### ISSUE TITLE
Illegal path message at every start

### ISSUE THREAD

**Issue by DemetriouJohn** [gitextensions/gitextensions#9754]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.1.windows.1
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4420.0
- DPI 144dpi (150% scaling)

### Issue description

Error message and exception is shown on every startup regarding illegal characters in path, but no path is shown to identify which character is illegal.

### Steps to reproduce

Starting up on my machine.

**Comment by DemetriouJohn** [comment]
It can also be reproduced whenever I open settings window. If I click ignore, git extensions opens normally but then I am unable to open Settings as I get the error again

**Comment by DemetriouJohn** [comment]
@mstv I didn't save it, and I do not have access to that computer now, I will come back and post it once I do. 
But I did not save it because The I did not see any git extensions related code in the stack trace, 
Only System if I remember correctly. But I will check again.

**Comment by DemetriouJohn** [comment]
![image](https://user-images.githubusercontent.com/5678167/144195257-7fe13c69-f568-4f46-bbef-906af55651e0.png)

The stack trace. And because of this, I cannot open settings to fix any possible invalid path.

**Comment by mstv** [comment]
Check your `.gitconfig` in `%USERPROFILE%`, please. The path of a `difftool` or a `mergetool` might contain the invalid character(s).
I would make a backup of the file, remove these tool sections and configure them again using the settings dialog.

**Comment by DemetriouJohn** [comment]
Define illegal character please

**Comment by RussKie** [comment]
Any character that Windows does not allow in its path. See
https://stackoverflow.com/a/31976060/2338036

**Comment by DemetriouJohn** [comment]
I saw none of those in the file, and also, weird how it ended up there since the file was edited from gitExtensions and not manually.

**Comment by RussKie** [comment]
If you can share the config, we could have a look.

**Comment by DemetriouJohn** [comment]
I already changed it and didn't keep the original
