### ISSUE TITLE
Stuck in "Process" window when trying to clone or pull

### ISSUE THREAD

**Issue by olmed0** [gitextensions/gitextensions#9755]
### Environment

- GitExtensions version: 3.5.4.12724
- GIT version: 2.34.0.windows.1
- OS version: Windows 11 Enterprise Insider Preview (ARM running with Parallels on a M1 Apple Silicon chip)
- .NET version: 4.8.9014.0

### Issue description

Cloning, pulling, fetching, etc. Anything triggering the "Process" window gets stuck before even doing anything, as shown in the screenshot. Running the git command in the console works fine.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/8710402/143295899-8a64276f-639e-42ac-a743-5bc11439df47.png">

### Steps to reproduce

Try to clone or pull from a repository.

### Did this work in previous version of GitExtensions?

I don't know, it's the only version I have tried on Windows 11 ARM.

**Comment by RussKie** [comment]
Try disabling the ConEmu, as it doesn't work on ARM64, https://github.com/Maximus5/ConEmu/issues/1488. 
![image](https://user-images.githubusercontent.com/4403806/143333964-f3bab850-0a93-4bc6-8b0e-2285065fb3ef.png)

**Comment by olmed0** [comment]
That worked. Thanks!
