### ISSUE TITLE
Erroneous build instructions refer to non existent script

### ISSUE THREAD

**Issue by Baljak** [gitextensions/gitextensions#9756]
### Environment

- GitExtensions version: master
- GIT version: not relevant
- OS version: not relevant
- .NET version: not relevant

### Issue description

Build instructions for versions 3.5 and master are inaccurate. They refer to a `build.cmd` script which isn't available anymore. There is also a link to `build.ps1`, but this file is also not present in the repository.

### Steps to reproduce

Follow the build instructions for 3.5 as described here: https://github.com/gitextensions/gitextensions/wiki/How-To%3A-build-instructions#v34-and-v35.

### Did this work in previous version of GitExtensions?

From what I remember, build instructions were correct for 3.3, maybe 3.4, but since 3.5 at least, they are not.

**Comment by gerhardol** [comment]
The instructions seem correct to me.

The 3.5 branch `release/3.5` has the `build.cmd` script.
`master` uses `dotnet` to build as stated in the instruction.
