### ISSUE TITLE
Graph: Option to group commits (below a merge) from incoming branch above the commits from receiving branch

### ISSUE THREAD

**Issue by ADTC** [gitextensions/gitextensions#9758]
### Feature description

If you run `git log --all --graph --oneline` you get a graph like this:

![image](https://user-images.githubusercontent.com/6047296/144262764-bba9e5ec-3880-445c-ac4f-51b8101a529e.png)

As you can see below the merge commit `9f9d5a1`, the three commits from the incoming branch are grouped above the two commits from the receiving branch.

I prefer it this way. But in GitExtensions, the commits are sorted by committed date or author date, with no regards to the branch they're on:

![image](https://user-images.githubusercontent.com/6047296/144261667-75da59e3-6d77-45be-8335-7b78dfd31eaa.png)

I find it harder to read and follow the history when it's like this, especially in graphs that are more complex than the simple example here. All the commits are jumbled up based on their author/committer date sorting and not sensibly grouped by the branch they were in.

It will be nice to be able to sort by committer date or author date, but there should be another option: **"Group commits by branch in graph"**.

- When this is enabled, the grouping would come first applying globally to the entire graph. The sorting (by committer/author) applies locally to each group (not globally to the entire graph).
- When this is disabled, the sorting (by committer/author) would apply globally to the entire graph.

_Sorry if this feature already exists, but I couldn't find it._

### Environment

N/A

**Comment by gerhardol** [comment]
https://git-scm.com/docs/git-log#Documentation/git-log.txt---topo-order

This also filters the commits displayed.
You can get this by entering ``--topo-order` in advanced filter, branches

**Comment by ADTC** [comment]
@mstv thanks for fixing this. When will there be a new release? It seems the last release was six months ago.

**Comment by gerhardol** [comment]
> @mstv thanks for fixing this. When will there be a new release? It seems the last release was six months ago.

Some issues, primarily in .NET5 still
https://github.com/gitextensions/gitextensions/discussions/9713

Testing/usage of changes in master needed
