### ISSUE TITLE
Console path doesn't change when switching to another project through Start -> Open...

### ISSUE THREAD

**Issue by maxulfves** [gitextensions/gitextensions#9761]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.24.0.windows.2 (recommended: 2.30.0 or later)
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

### Issue description

When switching to another project by opening the start menu and selecting "Open..." and then the project the console stays at the old location. 
![image](https://user-images.githubusercontent.com/11315779/144722245-a9dceeb9-3b6a-4c95-93f5-f74b29a10096.png)

I can't see the use case for it, so I assume it's a bug. 

### Steps to reproduce

1. Open a repository
2. Go to the menu and open a different repository
3. Notice that the console now is still at the old path.

**Comment by gerhardol** [comment]
Cannot reproduce.
Both master and 3.5.4, regardless if start with last repo and how a repo is switched.

**Comment by TrueRaider** [comment]
Same problem on Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- Git 2.38.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.11
- DPI 96dpi (no scaling)

But reproduced on ver 3.5.4 for me. Something in global git settings, maybe...

**Comment by TrueRaider** [comment]
With cmd working fine. Problems with bash
![image](https://user-images.githubusercontent.com/16497965/201335702-474fd42c-5e4e-4635-ab52-5a10307277cd.png)

**Comment by mstv** [comment]
The correct `cd d:\path\to\repo` command is automatically entered to the bash prompt - regardless of how I switch repos. I have to hit `Enter` myself though.
I use the bash from Git for Windows.

**Comment by TrueRaider** [comment]
Yes, but not so long ago it was happening automatically.

**Comment by pmiossec** [comment]
@TrueRaider I'm absolutely not sure it will solve your issue (it's a fix for @mstv issue) but you could test #10613 to see if it fixes your issue. Portable version available in artifacts of build when it will be finished: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45853432/artifacts
