### ISSUE TITLE
Update `DotnetRuntimeBootstrapper` to latest version to make use of added improvements

### ISSUE THREAD

**Issue by Tyrrrz** [gitextensions/gitextensions#9766]
### Feature description

Hi!

I noticed you were using https://github.com/Tyrrrz/DotnetRuntimeBootstrapper.
In the last major update it was reworked quite drastically and as a result comes with some large improvements. You can read the full list in the changelog or in updated readme, but here are the highlights:

1. Using `hostfxr.dll` now instead of `dotnet` CLI. This means no extra process is created.
2. Optimized hot path. Prerequisites will only be checked for if the app fails to run. Made possible by the previous point.
3. Bootstrapper executable is now only generated on `dotnet publish`. It used to also be generated on `dotnet build` too, but that broke debugging. You can still re-enable that with `<GenerateBootstrapperOnBuild>true</GenerateBootstrapperOnBuild>` if you want for some reason.
4. Strategy used for resolving .NET Runtime, both the installation location as well as the download URL, have been optimized and made more stable. The former now mimics the behavior of `nethost` library.
5. Native resources (mainly application manifest) is now properly inherited from the `exe` file by the application. Previously it wasn't possible because the bootstrapper created a separate process (for `dotnet` CLI), but it doesn't do this anymore.

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.31.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Awesome!
