### ISSUE TITLE
Flag to disable telemetry for all users during unattended install

### ISSUE THREAD

**Issue by branpurn** [gitextensions/gitextensions#9770]
### Feature description

It would be helpful for enterprise users of Git Extensions if a flag/command-line option were offered to disable telemetry for all users during unattended installations. 

### Environment

- GitExtensions version: 3.4.5
- OS version: W10 Enterprise
- .NET version: 4.*

**Comment by gjabouley-invn** [comment]
There is a property [TELEMETRY_ENABLE](https://github.com/gitextensions/gitextensions/blob/master/Setup/Product.wxs#L17) for the installer, could be used for such purpose:
`msiexec /i GitExtensions-4.1.0.16698-1fe52a137.msi TELEMETRY_ENABLED=0 /qn`

It seems it should disable telemetry during unattended install, but i was not able to make it work...

**Comment by RussKie** [comment]
Closing due to age. If someone really needs this fixed, they can submit a PR.
