### ISSUE TITLE
Toggle to hide the branches sidebar

### ISSUE THREAD

**Issue by tomasfejfar** [gitextensions/gitextensions#9771]
### Feature description

When working on a small screen I usually use the checkout branch popup and rarely need the sidebar with branches, remotes and submodules. It would be great if I could hide it completely. Currently I resize it to a smallest possible width (~10px), which is not ideal, but works. 

### Environment

- GitExtensions version: latest
- GIT version: N/A
- OS version: Win 10
- .NET version: N/A

**Comment by pmiossec** [comment]
![image](https://user-images.githubusercontent.com/460196/145404964-05ad38a2-1dd2-489c-93db-7acc50d7d8e5.png)

**Comment by pmiossec** [comment]
Duplicate of #5913

**Comment by tomasfejfar** [comment]
Oh, I see! Sorry. And thanks! I was looking in the menu and didn't expect that there is something on the toolbar that's not in the menu.
