### ISSUE TITLE
abnormal menu display on ubuntu 

### ISSUE THREAD

**Issue by nezen** [gitextensions/gitextensions#9772]
### Environment

- GitExtensions version:2.51.05
- GIT version: 
- OS version: ubuntu 18.04(virtualbox guest)
- .NET version: 
- mono version: 6.12.0.122

### Issue description

![VirtualBox_ubuntu-18 04_13_12_2021_14_00_55](https://user-images.githubusercontent.com/5187028/145760556-93a3f6d7-851c-411a-bbdb-ea30778c46f2.png)

Abnormal menu display

### Steps to reproduce

![VirtualBox_ubuntu-18 04_13_12_2021_14_00_55](https://user-images.githubusercontent.com/5187028/145760556-93a3f6d7-851c-411a-bbdb-ea30778c46f2.png)

**Comment by RussKie** [comment]
A PR with a fix is welcome. Closing since no one from the core team is maintaining the Mono version.
