### ISSUE TITLE
Favourite used in en-US

### ISSUE THREAD

**Issue by NN---** [gitextensions/gitextensions#9776]
### Environment

Start -> Favo**u**rite Repositories.

en-US should use Favorite without `u`.

- Git Extensions 4.0.0.13221
- Build 23aa39696437f30a56399994b4cfa3176a26c068 (Dirty)
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 5.0.13
- DPI 96dpi (no scaling)

### Issue description

Typo	

### Steps to reproduce

Start menu

**Comment by zombi3123** [comment]
As far as I'm aware there is no specific US dialect for git extensions? British English is the only English option.

**Comment by NN---** [comment]
In options it has "color" and not "colour". There should be consistency then.

**Comment by gerhardol** [comment]
GE is a community project and there has been many opinions if the language should be BE, AE or something else (like Australian).
This is both in the code and in the UI.

The original intention was to use BE. Many contributors have used AE over time though, some spellings like `color` is supposedly tolerated in "common" BE.
I would prefer to use AE consistently, as that is more common for SW.
A special AE translation could be added too (or change original to AE and add a BE translation).

A review of language should be submitted as a PR.
Unfortunately, changing a string in the (English) original will force changes to all translations, so it will not be popular in other translations...
