### ISSUE TITLE
Pull dialog cut-off after a Fetch operation from toolbar

### ISSUE THREAD

**Issue by hyzcan** [gitextensions/gitextensions#9779]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

### Issue description

If you run a fetch using toolbar button, then go to the Pull Dialog to pull changes, you'll notice the dialog is cut off at bottom and the Pull Button is almost invisible.

### Steps to reproduce

* open a repository
* click the download button on toolbar to run one of the Fetch operations (fetch, fetch all, fetch all and prune)
* note, if Fetch is not the default action, you need to expand the dropdown menu first and then choose one of the fetch options
* launch the Pull Dialog (ctrl+down or from the Command menu)
* dialog is cut off at bottom

![image](https://user-images.githubusercontent.com/65992391/147320772-6467c577-683f-4c4c-8aeb-fb5862e5e33f.png)

### Did this work in previous version of GitExtensions?

Yes, 3.4.3.9999

**Comment by RussKie** [comment]
Ack.
The dialog is resizable, and you can make it larger to see the clipped
controls.

**Comment by jppier** [comment]
@RussKie Yes, but the dialog doesn't stay resized between openings

**Comment by mstv** [comment]
Changed in vNext:

![image](https://user-images.githubusercontent.com/36601201/168172342-5c19c7df-051c-4e71-9ad1-1c67c2d3d470.png)
