### ISSUE TITLE
Restore Color settings with .NET5

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#9782]
### Feature description

Theming was unfortunately disabled with .NET5 in #8522, not in the current roadmap for next release.
This is tracked in #9191
There primarily issues with the hooking required to change the view of user controls, but also to some extent with the .css parsing in the ExCSS library used.

However, the theming also included the possibility to change colors for labels etc available before the theming (also with colorpickers etc).
This is required for instance to switch back the colors for local/remote branches, an unfortunate change that left many users dissatisfied.

This functionality can be restored in two ways:
* Migrate back to the old application colors.
* Fix the issues with the ExCSS package with netstandard and only use the "color" part, maybe even remove the references

### Environment

- GitExtensions version: master
- .NET version: 5.0.404

**Comment by gerhardol** [comment]
@NikolayXHD @RussKie Any hints how to do this in the simplest way?
I assume that update the interface for ExCSS is the easiest way forward.
GE currently uses ExCSS 4.1. As commented by @NikolayXHD error handling is hard there.
I did a quick shot that just does something (no variations) in feature/i9782-color-labels.

**Comment by NikolayXHD** [comment]
To be honest I would chooose to parse CSS manually, just the syntax we need for our particular case, which is not too much:
- `@import url("{UserAppData}/dark.css");`
- `@import url("dark.css");`
- `/* comments */`
- data in format `.Graph.colorblind { color: #0600a8 }`

rouhly 4 regular expression, one-two screens of code, and -- done, profit!

Contrast it with messing with messing with someone else's abandoned project and taking dependency on thousands of lines of code, mostly unnesessary for the task at hand.

**Comment by gerhardol** [comment]
> Contrast it with messing with someone else's abandoned project and taking dependency on thousands of lines of code, mostly unnesessary for the task at hand.

Except for error handling, it works OK (also colorblind but reactivated tests fails, due to changed errorhandling).
ExCSS is actively updated now, but regex could still be easier.
