### ISSUE TITLE
Sorting files in Commit screen

### ISSUE THREAD

**Issue by c2ssb2** [gitextensions/gitextensions#9809]
### Feature description

I suggest to add a way to sort files in  Staged and Unstaged portions by date for both ascending and descending (modifying and creation) to help user to select changed files quickly. This is related to issue #2518 . May be use ListView and sort by columns?

Thank you in advanced.

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.2
- Microsoft Windows NT 10.0.19041.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
You mean this, available in all file lists?
Not sort order though.

![image](https://user-images.githubusercontent.com/6248932/148676151-5d28d4b1-bd05-4239-8f1f-20be71a2cbb2.png)

**Comment by c2ssb2** [comment]
Yes, It would be nice if has more sorting options i.e. file modification date ascending and descending.

**Comment by gerhardol** [comment]
> Yes, It would be nice if has more sorting options i.e. file modification date ascending and descending.

Sort order with modification time has to be queried from the file system, other sort properties are queried from Git (also for branches etc). (May affect performance for large file lists.)
Also, what is the usage for this other than nice to have?
Timestamps are for most files determined by Git and can seem to random.
The only benefit as I see is the latest modified file.

**Comment by RussKie** [comment]
I'm not clear on the use case for "sort by date" either, and like to better understand it too.

**Comment by c2ssb2** [comment]
> I'm not clear on the use case for "sort by date" either, and like to better understand it too.

Sometimes needs to sort unstaged files by descending modification date to identify files modified in specific date in order to commit only desired files . This feature will help a lot especially when there are huge number of files modified and will commit into multiple commits.

**Comment by vbjay** [comment]
https://devblogs.microsoft.com/scripting/powertip-find-files-modified-during-a-date-range-by-using-powershell/

Then pass files to git add. Could also use find.

**Comment by RussKie** [comment]
Whilst the app's mission is to make git more approachable, this feature sounds  rather niche and specific to your use of git.
