### ISSUE TITLE
Support VS 2022 with your VS extension

### ISSUE THREAD

**Issue by drauch** [gitextensions/gitextensions#9810]
### Feature description

Please support VS 2022 with your VS extension - or is it already supported? Then how to install it for VS 2022? I only find another extension named "Git Extensions" which has the same logo but a completely different version number and it looks very suspicious.

Best regards,
D.R.

### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by RussKie** [comment]
https://marketplace.visualstudio.com/items?itemName=GitExtensionsApp.VS2022

**Comment by drauch** [comment]
Ah so it is an official one, thanks. I was worried because of the much lower version number than the old one.
