### ISSUE TITLE
Multiple selection of files with Shift key will freeze when submitting

### ISSUE THREAD

**Issue by AtheosCode** [gitextensions/gitextensions#9811]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

### Issue description

Multiple selection of files with Shift key will freeze when submitting

### Steps to reproduce

happen occasionally

**Comment by AtheosCode** [comment]
![QQ图片20220111153823](https://user-images.githubusercontent.com/11506195/148900763-0017ba83-df33-4c99-80eb-974937b4f8b6.png)

**Comment by RussKie** [comment]
Can you please provide more details? I don't observe any issues.

**Comment by AtheosCode** [comment]
![GIF 2022-1-12 10-17-55](https://user-images.githubusercontent.com/11506195/149052133-116639e1-f9d8-49f6-b4b5-edbc050603db.gif)

**Comment by RussKie** [comment]
Is this happening in a specific repo/for specific files, or is it happening in general?

**Comment by AtheosCode** [comment]
More than three different repo, and different computer

**Comment by vbjay** [comment]
Are your repos on a network drive or local drive?

**Comment by AtheosCode** [comment]
remote repository on network drive  
local repository on local drive

**Comment by RussKie** [comment]
Are there any large files/large diffs involved?

**Comment by AtheosCode** [comment]
Try small repo, and small diff can be repeated




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月19日(星期三) 中午12:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gitextensions/gitextensions] Multiple selection of files with Shift key will freeze when submitting (Issue #9811)





 Are there any large files/large diffs involved?
 
&mdash;
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by RussKie** [comment]
Since no one else appears to observe the same issue you're experiencing, you're in the best position to debug it. If you can provide a small stable repro someone may be able to help with the investigation.

**Comment by gerhardol** [comment]
Git Command Log (F12) started before this please, to see Git operations.

**Comment by Fuji22360** [comment]
> Git Command Log (F12) started before this please, to see Git operations.

The following two logs are displayed.
2022-03-09T15:36:38.6357450+09:00	109	17044	UI	0	git	ls-files -z --unmerged
2022-03-09T15:36:51.5707618+09:00	68	9936	UI	0	git	--no-optional-locks -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files
