### ISSUE TITLE
Incorrect/unexpected theming in the dev version

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9812]
### Environment

- GitExtensions version: current master

### Issue description

If there's a v3.x installed and has a configured non-default theme (e.g. dark or silver), the dev version is loading the theme and selectively applying it to the app.

E.g. I have the silver theme set as my default:
![image](https://user-images.githubusercontent.com/4403806/148904911-a2f93d7b-dcbe-4bc4-8e7d-40373f2395a9.png)

The dev version looks like this:
![image](https://user-images.githubusercontent.com/4403806/148904792-2bc4134f-5471-47bf-a48e-1b48b98b076d.png)
* the caption bar is dark
* the alternate rows are dark
* the author commits are dark
* the commit message is dark
* the borders for the left panel, the revision grid and other various controls are dark.

I guess (though I haven't investigated) that this may be an unintended result from https://github.com/gitextensions/gitextensions/pull/9799.

The expectation that no non-default theming is applied since we don't currently support theming hooks.

### Steps to reproduce

Set the non-default dark theme.

**Comment by gerhardol** [comment]
>     1. do not ship dark themes

That would "fix" most occurrences of the issue as most users likely have not modified the theme (and those who have are expected to know more).
But if the theme is reset to default, it should not be necessary.

>     2. reset the configured theme on install/first start

That is basically to use a new setting, then the user should be migrated to default.

>     3. display a warning in the Colors settings page warning users about incomplete theming support and provide a link to an issue/wiki/discussion with more details.

I tried to update the README in the themes directory and the wiki for this.
I find it a little lame to have this in the settings, but there are good alternatives.
