### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by jonas-canton** [gitextensions/gitextensions#9814]
### Environment

- GitExtensions version: 3.5.4.12724
- GIT version: 2.34.0.windows.1
- OS version: 21H1
- .NET version: 4.8.4420.0

### Issue description

The error occurs when browsing the file list in the commit window and also when browsing the commit history.

### Steps to reproduce

Browse commit history and list of files to commit.

**Comment by RussKie** [comment]
Please search through the open and closed issues to see whether your issue has been discussed and/or fixed.
https://github.com/gitextensions/gitextensions/search?q=OutOfMemoryException+is%3Aissue&type=issues

**Comment by jonas-canton** [comment]
> Please search through the open and closed issues to see whether your issue has been discussed and/or fixed. https://github.com/gitextensions/gitextensions/search?q=OutOfMemoryException+is%3Aissue&type=issues

I think the error occurs because of large files in the repository. I don't know if there is any solution other than not versioning such files.

**Comment by pmiossec** [comment]
> I think the error occurs because of large files in the repository. I don't know if there is any solution other than not versioning such files.

If you have big files directly committed in your repository, yes, it will be a pain in the future to clone and work with your repository and you should consider using https://git-lfs.github.com/ to not clutter your repository...

**Comment by pmiossec** [comment]
And files managed by git-lfs are not loaded by GitExtensions and will not cause OutOfMemory exceptions...

**Comment by jonas-canton** [comment]
> And files managed by git-lfs are not loaded by GitExtensions and will not cause OutOfMemory exceptions...

Thanks for the answer. I'll close the issue.
