### ISSUE TITLE
Cancelation of a process leaves the process running

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#9818]
### Environment

- Git Extensions 33.33.33
- Build 406acbf9e4223d3587bc97dbf42907b931154602
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.13
- DPI 96dpi (no scaling)

### Issue description

#9522 introduced cancellation token support for executables, to exit the executable if the token is cancelled.
However, the corresponding process itself continues to run to exit.

Blaming in the file tree and switch files before git-blame is done will in master not cancel the executable, there can be several git-blame running simultaneously (git-blame can take a minute for en_pseudo.xlf in GE for example).
Cancellation as in #9816 will not really improve the situation, as git-blame continues to run.

It could be possible to kill the processes if the executable is canceled.

### Steps to reproduce

In master: 
* FileTree, Blame
* Repeatedly change file (for instance .xlf files)
* View running processes, see simultaneous Git processes increase

**Comment by mstv** [comment]
The cancelled `git blame` processes seem to never terminate.
To be checked: Does the cancellation request reach the `IProcess` instance. Is `ExecutableExtensions.ExecuteAsync()` used?
