### ISSUE TITLE
RevisionGrid: Avoid temporary hang on `Ctrl+A`

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9823]
### Feature description

I often hit `Ctrl+A` in order to select all files affected by a commit.
If the RevisionGrid is focused, GE will be very busy for a long time (and the commit is not selected anymore).

Variant A: Ignore `Ctrl+A` in the RevisionGrid.

Variant B: A TaskDialog could be displayed asking for confirmation to select all revisions
and offer to select all files affected by the commit in the FileStatusList (focusing the Diff tab).

Variant C: Add a GE hotkey for the second part of variant B.
With an upcoming PR which routes hotkeys to all visible controls, this hotkey will then take precedence over the built-in handling of the DataGridView.

Variant D: ?

### Environment

GE HEAD

**Comment by RussKie** [comment]
I can't think of a use case to select all in the revision grid. Can you?

**Comment by mstv** [comment]
> I can't think of a use case to select all in the revision grid. Can you?

I can't.
So, I will go for variant C (based on #9827).
