### ISSUE TITLE
Do not cache `git diff` result for workdir files

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9834]
### Environment

- Git Extensions 33.33.33
- Build f42768a8ab9d9fbc4ad178d0cd8f0895e4c1eefd
- Git 2.33.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.13
- DPI 96dpi (no scaling)

### Issue description

The diffs of workdir files are not updated when switching (from IDE) to GE.

Only `git --no-optional-locks -c diff.ignoreSubmodules=none status --porcelain=2 -z --untracked-files` is run.

```
git -c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --unified=3 -- "rel/path/some_file.ext"
```
is *not* re-run.

### Steps to reproduce

- modify a tracked file
- switch to GE
- select the file in artificial commit `Working directory`
- modify the tracked file again
- switch to GE
--> diff not updated

### Did this work in previous version of GitExtensions?

yes

**Comment by gerhardol** [comment]
The cache is explicitly skipped for artificial commits.
The standard behavior is not to refresh diff tab when activating GE, you added a specific configuration here...

**Comment by mstv** [comment]
You are right. Though `RefreshGitStatusMonitor` seems to update less than before.
But there was another change today: I was pushed back to the default settings because the settings files was destroyed by quickly closing multiple GE instances.

**Comment by gerhardol** [comment]
Reuses commit settings
![image](https://user-images.githubusercontent.com/6248932/151051543-aa52c513-5b40-4c3d-b878-451b64435326.png)

> Though RefreshGitStatusMonitor seems to update less than before.

It seem to work for me. But I am mostly on WSL where FileSystemWatcher do not fire and refresh has to be done manually.

**Comment by mstv** [comment]
> Reuses commit settings

Thank you! Now, both the diff and the number of changes are updated again.
