### ISSUE TITLE
ArgumentNullException when executing a script with empty arguments

### ISSUE THREAD

**Issue by DragDen** [gitextensions/gitextensions#9835]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

### Issue description

An error occurs when trying to execute a script with an empty arguments field.

Stacktrace:
> System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: arguments
   в GitCommands.ArgumentString..ctor(String arguments)
   в GitCommands.ArgumentString.op_Implicit(String args)
   в GitUI.Script.ScriptRunner.RunScriptInternal(IWin32Window owner, IGitModule module, String scriptKey, IGitUICommands uiCommands, RevisionGridControl revisionGrid)
   в GitUI.Script.ScriptRunner.RunScript(IWin32Window owner, IGitModule module, String scriptKey, IGitUICommands uiCommands, RevisionGridControl revisionGrid)
   в GitUI.CommandsDialogs.FormBrowse.<>c__DisplayClass70_0.<InternalInitialize>b__4(Object <p0>, EventArgs <p1>)
   в System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   в System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   в System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   в System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   в System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   в System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   в System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   в System.Windows.Forms.Control.WndProc(Message& m)
   в System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   в System.Windows.Forms.ToolStrip.WndProc(Message& m)
   в GitUI.ToolStripEx.WndProc(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   в System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   в System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce

1) Open Settings, select Scripts;
2) Add a new script;
3) Fill the Command field (mine was the full path to the .bat file);
4) Leave the Arguments field empty;
5) Set Enabled = True;
6) Press OK and try to execute the script.

### Did this work in previous version of GitExtensions?

_No response_

### Diagnostics

_No response_

**Comment by mstv** [comment]
Not reproducible with the development branch (anymore?). Have not tried with 3.5.4.

**Comment by RussKie** [comment]
I vaguely remember this problem, and I believe it was fixed in vNext.

**Comment by DragDen** [comment]
Yes, tried current dev-version (4.0.0.13422), and the problem is gone
