### ISSUE TITLE
Password box does not pop up

### ISSUE THREAD

**Issue by godcong** [gitextensions/gitextensions#9836]
### Environment

- GitExtensions version: 3.5.4.12724
- GIT version:  2.30.0
- OS version:  win11
- .NET version: 4.8.4420

### Issue description

When using the push function, the server asks for a username password.
This is where the client pops up a popup to enter the username.
After entering the username a password popup will be displayed in the status bar.
However, this popup will not pop up as it did when the username was entered.

### Steps to reproduce

1. push some data to server
2. insert username into box
3. the password box was minimized display

### Did this work in previous version of GitExtensions?

There seem to be several versions

**Comment by gerhardol** [comment]
Password handling is not th Git Extensions itself, it is handled by Git.
(GE has some functionality to handle PuTTY though.)

If you have a problem setting up SSH, I would recommend you to use `Git Credential Manager Core` distributed with Git and clone/push using https.

**Comment by godcong** [comment]
![image](https://user-images.githubusercontent.com/2727298/154413467-270fe523-8ccc-4378-a809-792e42568a41.png)
Isn't this input box managed by Git Extensions?
I'm talking about this box, it doesn't pop up automatically after you type your username, it just minimizes in the taskbar

**Comment by gerhardol** [comment]
> @gerhardol Isn't this input box managed by Git Extensions? I'm talking about this box, it doesn't pop up automatically after you type your username, it just minimizes in the taskbar

The input box is not GE, it is likely started by your credential manager.
