### ISSUE TITLE
Hotkey override control default key combinations

### ISSUE THREAD

**Issue by gerhardol** [gitextensions/gitextensions#9861]
### Environment

- Git Extensions 33.33.33
- Build bf62f72ff314646299e8862301f3c08d7d51bae5
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.13
- DPI 96dpi (no scaling)

### Issue description

All shortcuts built in to controls must be added as hotkeys or be specially handled to not be overriddeden by hotkeys in related controls.

A follow up on #9845, specific
https://github.com/gitextensions/gitextensions/issues/9845#issuecomment-1026025668
https://github.com/gitextensions/gitextensions/pull/9827#issuecomment-1030593971

Introduced in #9827 (that I do not want to revert).
Probably a blocker for vNext.

### Steps to reproduce

* Try to select all text in a text control using Ctrl-A

*Assign Ctrl-C to a hotkey in any control and text cannot be copied with the shortcut

### Did this work in previous version of GitExtensions?

Introduced in #9827

**Comment by mstv** [comment]
Making `F5`, `F2`, et.c appear in the list hotkeys would be good anyway IMO.

Perhaps, it will be easier / necessary to add the hotkeys which are built-in in the controls, to `GitExtensionsControl.IsTextEditKey()`, i.e. `Ctrl+C`, `Ctrl+V`, `Ctrl+A`. Any further?
Then the hotkey `Ctrl+A` needs to be duplicated for the RevisionGrid - no big deal.

**Comment by gerhardol** [comment]
Closed #9828
