### ISSUE TITLE
Tags are not updated when changing in the repository

### ISSUE THREAD

**Issue by andrey-helldar** [gitextensions/gitextensions#9863]
### Environment

- GitExtensions version: 3.5.4.12724
- GIT version: 2.34.1
- OS version: Win11
- .NET version: 4.8.4470.0

### Issue description

In one of the projects there is a need to use aliases for tags.

For example, when creating a v1.0.0 tag, it will have v1 and latest aliases.
After that, when creating the v1.0.1 tag, the aliases will be updated.

But GitExtensions does not see such changes.

### Steps to reproduce

1. Create a new tag in GitHub web interface;
2. Run the [action](https://github.com/TheDragonCode/php-codestyler/blob/main/.github/workflows/release.yml);
2. Click on `Fetch all` button;
3. See new tag on `my_sha_1` - it's ok;
4. Push changes to the repository;
5. Create a new tag in GitHub web interface;
6. Run the [action](https://github.com/TheDragonCode/php-codestyler/blob/main/.github/workflows/release.yml);
7. Click on `Fetch all` button;
8. See a tag on old commit.

![image](https://user-images.githubusercontent.com/10347617/153200832-8c362b84-08c7-4e4a-970a-cc44154a3917.png)

### Did this work in previous version of GitExtensions?

No

### Diagnostics

At the same time, if you execute the command locally in the console and press F5, then the tag is displayed correctly.

`git tag -f -a "v1" "my_sha_2" -m "foo"`

**Comment by pmiossec** [comment]
> After that, when creating the v1.0.1 tag, the aliases will be updated.

You are doing a wrong use of tags because by definition a tag is something that doesn't change (otherwise it is a branch).

So,that is the normal git behavior to not check if a tag could have changed. It only checks if you have it.

So you can't ask GitExtensions to do something differently and adopt a different behavior. 

Maybe another kind of fetch action could be considered....

**Comment by andrey-helldar** [comment]
Yes, but in this case there is a problem with hosting containers in the Github Action.

The fact is that the GitHub Action requires you to explicitly specify the tag. For example, you want to use the "foo/bar" component from version 1.2.3.

In the action file you write:

```yaml
- name: Custom run
  uses: foo/bar@v1.2.3
```

Everything seems to be fine? Yes, until the developer releases the next version.

For example, he found a bug and released version 1.2.4.

This means that you will need to go to the developer’s repository yourself (it’s not easy to find by the name of the component and it’s better to do it through Google, since there are no other ways to find it), see the new version with your own eyes, return to your action file and replace the line `foo/bar@v1.2.3` with `foo/bar@v1.2.4`.

And all this is because GitHub Action does not know how to semver.

Yes, this is a very crutch method, but it works.

The method is that the tag is updated during the release.

Thus, in [one of my](https://github.com/TheDragonCode/php-codestyler/blob/main/.github/workflows/release.yml) projects, I update the `v1` and `latest` tags, where `v1` will always contain changes from the 1st major version, and `latest` will always have a link to the latest stable code, including major changes.

**Comment by mstv** [comment]
This seems to be a git issue as @pmiossec wrote.
If you move the tag locally, GE will get that information.
But if the tag is moved in the remote repo, `git fetch all` does not update the local tag (have not tested myself).

As a workaround, you could delete the local tag first and then fetch all.
You can create a GE script with these two commands. It can be added to the toolbar and / or can be assigned a hotkey.

Perhaps, you do not need to delete the local tag:

![grafik](https://user-images.githubusercontent.com/36601201/153266167-a9e866dd-b788-4437-b407-8534a1382d3b.png)

**Comment by andrey-helldar** [comment]
> As a workaround, you could delete the local tag first and then fetch all.
Yes, it's works. I try it.


One option recommended by the community is to get rid of this unstable tag by enabling dependabot in the repository settings and telling it to handle workflows.

But the problem is that I have a lot of such repositories and dependabot will create for each PR that needs to be applied. And this is already very disturbing.

**Comment by andrey-helldar** [comment]
I gave it some thought and decided not to update the tag, leaving Dependabot to keep track of updates.

Since this problem is very specific, I am closing the issue because it is not needed.
