### ISSUE TITLE
GitCommandCache is not cleared when switching repo

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9865]
### Environment

- Git Extensions 33.33.33
- Build dd0a902e50f3198e1cb999374a0b32c77d7b8b2b, visible with 20321d0c9a9bbf109a44634fa5fdaea9aec30e83
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.12
- DPI 96dpi (no scaling)

### Issue description

when switching repos, `GitCommandCache` is not cleared

### Steps to reproduce

- run 20321d0c9a9bbf109a44634fa5fdaea9aec30e83
- switch between repos with differently named remotes

coming from GE repo with "upstream":

![grafik](https://user-images.githubusercontent.com/36601201/153964414-67f4d4d9-734b-421e-8760-8f25ca295ec9.png)

### Did this work in previous version of GitExtensions?

also not with ac4a0a5a6811c722fefd00e719b414e7f7739d4c (predecessor of #9864)

**Comment by gerhardol** [comment]
GitCommandCache should only store information that is always unique.
We could have other layers of cache that are cleared when repo refs, index or file system is changed but that would be an enhancement (that would speed up a lot of operations). The GitRefs handling is a lightweight solution for a specific command during startup.
It is nice to keep the cache when switching among repos.

`git-symbolic-ref` is not cached (which it should not be)

**Comment by mstv** [comment]
Commit hashes are not unique across independent repos.
So, the GitCommandCache must be cleared unless switching worktrees, because it is used for `log`, `rev-parse`, `diff`, etc.

**Comment by gerhardol** [comment]
> Commit hashes are not unique across independent repos. So, the GitCommandCache must be cleared unless switching worktrees, because it is used for `log`, `rev-parse`, `diff`, etc.

log and rev-parse must never be cached (unless there is a cache invalidation when refs are changed).
diff could be incorrect with very low probability

How do you find the cache invalidation related to the error message?
(cache is not enabled for this command)

**Comment by mstv** [comment]
> log and rev-parse must never be cached (unless there is a cache invalidation when refs are changed).

But a grep for `GitCommandCache` looks like they *are* being cached.

> How do you find the cache invalidation related to the error message?

What do you mean?

> (cache is not enabled for this command)

but in 20321d0c9a9bbf109a44634fa5fdaea9aec30e83 (as I tried to mention in the description)

**Comment by gerhardol** [comment]
To cache git-remote is clearly a bug if that would have occurred.
Similar for caching rev-parse HEAD etc. (sorry for npt being clearer).

I checked the use of CommandCache and did not find any use of cache that did not involve full Git sha, so very low probability that the info is incorrect.
(range-diff should be clarified though, not an issue but it will be clearer if also handled in GitModule).

While I do not believe this should be changed, one way is to add the working dir as a cachekey.
(Git dir would be better for worktrees, but git-dir is not always evaluated and will probably add overhead.)

**Comment by mstv** [comment]
Working dir has been added to command cache key.
