### ISSUE TITLE
Plugins Github not running correctly

### ISSUE THREAD

**Issue by godcong** [gitextensions/gitextensions#9867]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.30.0.windows.2
- Microsoft Windows NT 10.0.22000.0
- .NET Framework 4.8.4470.0
- DPI 96dpi (no scaling)

### Issue description

I configured the github plugin
But when I push the code, it doesn't automatically add the github token
I've tried some other tools and they add the token to the project correctly

like:
```
https://github.com/example/project
->
https://#token#@github.com/example/project
```

### Steps to reproduce

1. Clone your project
2. Configure your github token
3. Change some code and commit
4. Push your project

**Comment by RussKie** [comment]
Please try v4.1

**Comment by godcong** [comment]
I upgraded to 4.1 and used the push function and was able to push to the server properly. But I'm not sure if I'm using token or cache.
@RussKie

**Comment by vbjay** [comment]
The token doesn't have anything to do with pushing. It has everything to do with the GitHub window.
