### ISSUE TITLE
Branches filter keyboard input reversed

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9872]
### Environment

- Git Extensions 33.33.33
- Build 38e700fae4259e71ba2a2f8e8d03ed719abe4392
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 5.0.12
- DPI 96dpi (no scaling)

### Issue description

Text typed into the Branch filter ComboBox gets reversed.

### Steps to reproduce

Try to enter "debug":

![BranchesFilter](https://user-images.githubusercontent.com/36601201/155027235-dc5362bd-0b35-4624-9c54-42ad859f5497.gif)

**Comment by jtouet** [comment]
For information, I get the same issue with the following environment:
- Git Extensions 4.1.0.15031
- Build c00750b0dbf72f37957fa71b3717c5bb1a790c74 (Dirty)
- Git 2.37.0.windows.1 (recommended: 2.37.1 or later)
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.6
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Not completely solved in master, dropdown appears in some situations after #10136
