### ISSUE TITLE
Add stash options for context menu

### ISSUE THREAD

**Issue by tehKaiN** [gitextensions/gitextensions#9873]
### Feature description

The idea of context menu as I understand it is to have alternative interaction options with given item in most-used first order.

When right-clicking a stash on the tree, the first options should be to:

- pop this stash - allows for easily finding relevant stashes in tree history instead of doing typical error-prone pop or finding the stash through the dedicated dialog
- apply this stash (apply diff without deleting stash)
- delete this stash - allows for stash cleanup as you go instead of finding them in separate dialog and deleting them there.

I'm in the process of migrating from GitKraken and lack of this little UX feature makes using Git Extensions a bit tedious. :(

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4470.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I don't use  stashes, but this sounds reasonable. Would you like to send a
PR with a proposal?

**Comment by tehKaiN** [comment]
I can try to hack that in, but unfortunately my spare time is quite limited recently, so this most probably would have to wait for some days/weeks. I assume this thing is low priority for the project, so if you don't want to spend time into this then leave it to me.

**Comment by mstv** [comment]
I will appreciate it. It will give a more natural UX than extending the toolbar button as I did in a quick private hack:

![grafik](https://user-images.githubusercontent.com/36601201/158080740-3c4e4814-0273-45d8-8a86-2d380089cba8.png)
