### ISSUE TITLE
Error dialog shown when cherry picking file changes

### ISSUE THREAD

**Issue by tqdavidt** [gitextensions/gitextensions#9893]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.17763.0
- .NET Framework 4.8.4470.0
- DPI 96dpi (no scaling)

### Issue description

When cherry picking file changes (by selecting file in diff view), even if the patch applies cleanly, this is shown as an error dialog (titel "Error", red error icon).
This is confusing, especially when the patch is large and the "Applied patch ... cleanly" message gets burried in a wall of text.

![image](https://user-images.githubusercontent.com/101382442/157807904-075c4c88-d2b1-4679-af56-68dfbc910f7c.png)

### Steps to reproduce

Choose "Cherry pick changes" from right-click contet menu in diff view.

![image](https://user-images.githubusercontent.com/101382442/157808371-38fd0ee4-1866-43e4-8299-656206c224fa.png)

### Did this work in previous version of GitExtensions?

This has been like thise as long as I have been using GitExtensions/this feature

**Comment by gerhardol** [comment]
This is changed in master

**Comment by tqdavidt** [comment]
You are right, I did not find any issue relating to this before but did find it just now. Was fixed in #9468 --> closed
