### ISSUE TITLE
Nullref thrown when dragging folder

### ISSUE THREAD

**Issue by QuinnWuest** [gitextensions/gitextensions#9901]
### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

When selecting a folder to open, I mistakenly drag clicked a folder over another. This threw the nullref.
I can't click the "Report bug!" window, because the program has completely frozen.
![image](https://user-images.githubusercontent.com/45348711/158696677-57500374-da2d-4a91-8371-8c6c3da19dfc.png)

### Steps to reproduce

While in the Open menu (to open a repository), simply drag one folder into another. Very easy to reproduce.

**Comment by mstv** [comment]
Please share the versions. I could not reproduce with 3.4.3, 3.5.2 and dev. Can you reproduce it with the default theme?

![image](https://user-images.githubusercontent.com/36601201/158882110-cca0a92a-bc8d-490e-8347-5d78ca2d9d73.png)
