### ISSUE TITLE
Duplicate About Dialog item into Windows Explorer menu and/or Settings

### ISSUE THREAD

**Issue by andry81** [gitextensions/gitextensions#9915]
### Feature description

Quite a bit annoying each time to search for a git working copy to just open only the About Dialog to lookup the version or copy the information to clipboard.

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.1.windows.1
- Microsoft Windows NT 6.1.7601 Service Pack 1
- .NET Framework 4.8.3761.0
- DPI 96dpi (no scaling)

**Comment by gerhardol** [comment]
Screenshot?

**Comment by andry81** [comment]
> Screenshot?

Screenshot of what? Windows Explorer context menu?

**Comment by RussKie** [comment]
> Quite a bit annoying each time to search for a git working copy to just open only the About Dialog to lookup the version or copy the information to clipboard.

Thank you for your suggestion, but in my opinion your request is going way outside the context of Git Extensions. There are multiple ways of determining what git version is installed on your workstation, including opening a cmd prompt and running `git version`.
Can you please elaborate how often you search for git version, and why is it needed to be done on such a regular basis?

**Comment by andry81** [comment]
> > Quite a bit annoying each time to search for a git working copy to just open only the About Dialog to lookup the version or copy the information to clipboard.
> 
> Thank you for your suggestion, but in my opinion your request is going way outside the context of Git Extensions. There are multiple ways of determining what git version is installed on your workstation, including opening a cmd prompt and running `git version`. Can you please elaborate how often you search for git version, and why is it needed to be done on such a regular basis?

Not the git version, the Git Extension version. The Git Extension is required to open a git working copy to show the windows, where the Help option exists to open About Dialog to lookup the info.

**Comment by vbjay** [comment]
A repo doesn't have to be opened for help-> about to work. To get the
version info, yes you need to open git extensions.

**Comment by andry81** [comment]
> A repo doesn't have to be opened for help-> about to work. To get the version info, yes you need to open git extensions.

There is no such an option if click not on repo folder.

**Comment by vbjay** [comment]
You have to open git extensions no matter what. So just start the program.
You only get fit menu items in a repo which makes sense.

**Comment by andry81** [comment]
> You have to open git extensions no matter what. So just start the program.
> You only get fit menu items in a repo which makes sense.

Initial request was about Windows Explorer and work from the Windows Explorer. Why I need to open Repository Browser if can just open the Commit window from the Windows Explorer? The same for the help.

**Comment by vbjay** [comment]
Is the folder part of a repo?  Yes:. Then you get git extensions menus tied
to git repo and you get things that let you manipulate said repo. It makes
no sense to have menu options like commit and pull and such in a non repo
folder. The about screen is the Git Extensions About screen. Not a folder
about screen.  Imit makes 100% sense to me to only have create repo menu
when not in a repo folder.

**Comment by mstv** [comment]
For the users which use only the shell integration, `About` and `Help` could be added to the GE submenu in the Explorer  - by a volunteer - as we already provide a menuitem for settings here:

![image](https://user-images.githubusercontent.com/36601201/160277573-e2724dc9-5519-4955-b78d-42a6702cc834.png)

**Comment by andry81** [comment]
> Is the folder part of a repo? Yes:. Then you get git extensions menus tied to git repo and you get things that let you manipulate said repo. It makes no sense to have menu options like commit and pull and such in a non repo folder. The about screen is the Git Extensions About screen. Not a folder about screen. It makes 100% sense to me to only have create repo menu when not in a repo folder.

You have to find a repo *before* open the browser and *then* open the help which gives 3 steps instead of 1 from already opened Windows Explorer or from Total Commander which can open the Windows Explorer menu.

**Comment by vbjay** [comment]
No. You don't. You hit start. Open git extensions and hit help about. It's
not hard.

**Comment by andry81** [comment]
> No. You don't. You hit start. Open git extensions and hit help about. It's not hard.

I not working in start menu, i am working in the Windows Explorer context menu.

**Comment by vbjay** [comment]
The about info has nothing to do with the folder and everything to do with
the information about Git Extensions.

**Comment by andry81** [comment]
> The about info has nothing to do with the folder and everything to do with the information about Git Extensions.

Jesus Christ, this is feature request, WTF?

**Comment by gerhardol** [comment]
Some users will see this as overflowing the menus.
If this was fully configurable, it would not be an issue. #9701 adds the possibility to completely deactivate the menu only.

**Comment by ADTC** [comment]
**Fun Fact:** You can run `gitex about` on the command line, and it will show the About dialog. (You don't need to be in a git repository.)

![image](https://user-images.githubusercontent.com/6047296/185071145-6aac94af-8753-4d4a-a4cf-fa09be82095a.png)

You could perhaps create a shortcut to run Git Extensions with the `about` argument.

(Note that I'm on Git Extensions 4.1.0.14868 which is alpha/beta/something and not officially released yet. So: YMMV.)

**Comment by vbjay** [comment]
My point is you're forcing yourself to do this through explorer when it's
simple to just start the program.  You are complaining that it's not a repo
folder and it makes perfect sense that non repo folders don't show git
related menus. So quit making it silly abd instead just start the program
if you want the about info.
