### ISSUE TITLE
Step sequence for creating the value table

### ISSUE THREAD

**Issue by samalbee** [gitextensions/gitextensions#9916]
### Feature description

<p><strong>Step sequence for creating the value table</strong></p>
<p>1. specify table header, e.g. cell A1: x cell B1: y</p>
<p>Set the display interval, e.g. -3&le;x&le;3 with a step size of 0.5. The value -3 is entered in cell A2 and the value -2.5 in cell A3. The step size 0.5 is defined by A2 and A3. The step size is now to be transferred to the entire table - <a href="https://domyhomework.club/">pay people to do your homework</a>&nbsp;. To do this, cells A2 and A3 are marked together and dragged downwards at the bottom right corner until "3" appears.</p>
<p>2. determine function values</p>
<p>In cell B2 (the cell for the first function value) the function term is defined by cell reference. Always start with an equals sign.</p>
<p>The function term is now to be transferred to the entire spreadsheet - <a href="https://domyhomework.club/geometry-homework/">do my geometry homework for me</a>&nbsp;. To do this, cell B2 is expanded to the end of the table (B14). This produces the function values for the given interval.</p>
<p>The graphical representation of the value pairs can be created with the help of a "diagram assistant" belonging to the calculation programme:</p>
<p>1. the diagram wizard is called up via the standard toolbar or via Insert/Diagram. 2. the diagram type and sub-type are selected.</p>
<p>2. select chart type and subtype</p>
<p>As this example is a continuous function, the chart type Lines must be selected here.</p>
<p>3. Enter the data to be displayed</p>
<p>Select the Data Range tab, click the Data Range field and select the data in column B (function values). (The corresponding cell designation appears in the data range field).</p>
<p>Then the index card Series is selected and the field Label of the rubric axis (X) is clicked. Then column A (x-values) is to be marked - <a href="https://domyhomework.club/geometry-homework/">do my geometry homework for me</a>&nbsp;. If not already done, the name of the curve can be added (especially important if several curves are to be displayed in one coordinate system). To do this, select cell B2 after clicking on the name field. The cell content now appears as the name.</p>
<p><strong>Read also:</strong></p>
<p><a href="https://www.leecountyhumane.org/profile/albees046/profile">Platon</a></p>
<p><a href="https://www.southerntiersmen.org/profile/albees046/profile">Brahe's world view</a></p>
<p><a href="https://www.nuukcouture.com/profile/albees046/profile">Axioms of congruence</a></p>
<p><a href="https://www.fairmontfarminc.com/profile/albees046/profile">Chord set</a></p>
<p><a href="https://www.sipshopeat.com/profile/albees046/profile">Rectangle</a></p>

### Environment

1

**Comment by pmiossec** [comment]
I absolutely have no clue how you could end up thinking that you need to post these information in this project.
Closing....

**Comment by da-woods** [comment]
@pmiossec it's an excuse to post spam links! Report it to GitHub

**Comment by pmiossec** [comment]
@da-woods you're right. Reported.
