### ISSUE TITLE
After updates the "default pull action" defaults to something other than my choice. My choice being Fetch All. Personally this should be the default.

### ISSUE THREAD

**Issue by danocharron** [gitextensions/gitextensions#9927]
### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version: 

### Issue description

After updates the "default pull action" defaults to something other than my choice. My choice being Fetch All. Personally this should be the default.

### Steps to reproduce

After updates the "default pull action" defaults to something other than my choice. My choice being Fetch All. Personally this should be the default.

**Comment by RussKie** [comment]
I haven't observed anything like this with upgrades, nor we had any other complaints of this nature. Perhaps something else is trashing the config on your system.
