### ISSUE TITLE
Use parallel fetch to improve performance when multiple remotes are used

### ISSUE THREAD

**Issue by drewnoakes** [gitextensions/gitextensions#9937]
### Feature description

`git-fetch` has an `--jobs` option that performs fetches from multiple remote concurrently. When you have multiple remotes, this makes fetching much faster.

```
$ time git fetch --all
Fetching A
Fetching B
Fetching C
Fetching D

real    0m11.742s
user    0m0.046s
sys     0m0.046s

$ time git fetch --all --jobs=8
Fetching A
Fetching B
Fetching C
Fetching D

real    0m3.232s
user    0m0.030s
sys     0m0.108s
```

That timing matches what I see in Git Extensions:

![image](https://user-images.githubusercontent.com/350947/161462961-3457deaf-96c8-4bff-aac0-6465e87f3a5b.png)

I've used `--jobs=8` with a CLI alias locally for over a year and never found an issue with it. I wish it was the default behaviour.

It would be nice if Git Extensions passed `--jobs` by default.

https://git-scm.com/docs/git-fetch#Documentation/git-fetch.txt--j

There may be other commands that could benefit from the same treatment.

An open question would be the number of jobs to pass. I suspect this is primarily an I/O-bound operation, I believe it would be ok to keep things simple and just pass a number like 8 here. If it were CPU-bound, then basing it on CPU count might make sense.

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.34.1.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET Framework 4.8.4420.0
- DPI 144dpi (150% scaling)

**Comment by mstv** [comment]
Thank you for the hint!

`git config fetch.parallel 0` suffices. Could be added to the `Git` | `Config` settings page.

**Comment by RussKie** [comment]
Nice! I generally have multiple remotes in repos i work, and this will
likely benefit my flows.

I think we could take 8 as default, and offer a configuration via a
NumericUpDown control with a range [0, 16].

**Comment by gerhardol** [comment]
> `git config fetch.parallel 0` suffices. Could be added to the `Git` | `Config` settings page.

Or Git-Advanced, offering setting a value

> I think we could take 8 as default, and offer a configuration via a
NumericUpDown control with a range [0, 16].

The user may set anything from the commandline, no enforcement

**Comment by drewnoakes** [comment]
I would be interested to hear a legitimate reason not to default to 8 for everything. If we just did that it would make things easier across the board.

**Comment by gerhardol** [comment]
> The app doesn't need to respect the cli settings, and is free to override those - in fact we're doing it already.

We override when needed for functionality (like for git-status, git diff where the user may want other functionality from the CLI.

To avoid more options in the GUI, I suggest that GE reads the config value and sets it to a fixed value (8 seem fine) if not set.
It may be sufficient to have a hidden setting, so a user can override the setting in the .xml.

> I would be interested to hear a legitimate reason not to default to 8 for everything. If we just did that it would make things easier across the board.

**It does not work like it used to, it must be an error.**

**Comment by mstv** [comment]
(Why do you quibble about the value 8, Drew? I presume that the git developers choose a reasonable value if 0 is configured.)

> To avoid more options in the GUI, I suggest that GE reads the config value and sets it to a fixed value (8 seem fine) if not set.

Yes, but just activate the git default. This should be done deferred on startup.
GE should not override a git configuration hard-coded on the CLI without apparent reason.

**Comment by drewnoakes** [comment]
I assume the default of zero (no parallelization) makes the output log easier to read. On the CLI that might make more sense than in GE, unless there's an error in one of many remotes.

I don't really care what the number is, so long as the fetch is as fast as possible. I think the most remotes I've ever had was 5. In that case I don't think there's a difference between 8 or 800. My interest here is just that fetching is as fast as possible, as I do it regularly.

In the discussion here I've learned I can configure parallel fetch to be the default, which is great, but that doesn't speed things up for users who don't do that.

It sounds like the consensus here is to read whatever value the user may have configured during launch. If that exists, user it. If not, use some other number. Does that sound right?

What if the user specifies one number in GE's settings, and one in git's? It's that kind of edge case that meant my original suggestion was just to force 8.

**Comment by RussKie** [comment]
Why is it a problem to not respect the value configure for cli operations? We already override several settings which inhibit/interfere with the app?
https://github.com/gitextensions/gitextensions/blob/284e069ee819291a269713cfa204e874ebd2c803/GitExtUtils/GitCommandConfiguration.cs#L17-L32

**Comment by mstv** [comment]
> I assume the default of zero (no parallelization) makes the output log easier to read. On the CLI that might make more sense than in GE, unless there's an error in one of many remotes.

Of course, `1` is "no parallelization". That's what git defaults to (for historical reasons?).
`0` means let git choose a reasonable value for parallelization.
(https://git-scm.com/docs/git-config#Documentation/git-config.txt-fetchparallel)

> It sounds like the consensus here is to read whatever value the user may have configured during launch. If that exists, use it. If not, use some other number. Does that sound right?> 

Yes, that's the plan (but with `0`).

> What if the user specifies one number in GE's settings, and one in git's? It's that kind of edge case that meant my original suggestion was just to force 8.

We don't want to and don't need to add a setting in GE. Who is unhappy with the value chosen by git, can set it using CLI.

> Why is it a problem to not respect the value configured for cli operations?

Because there is no need to override it for GE operation. The other options ease parsing the git output.

**Comment by gerhardol** [comment]
> Because there is no need to override it for GE operation. The other options ease parsing the git output.

I in principle agree with this but believe it may be OK to change by default and keep a hidden setting to override the behavior in the .xml to prevent dissatisfaction.

**Comment by drewnoakes** [comment]
> 0 means let git choose a reasonable value for parallelization

I missed this detail in the earlier discussion. Yes, 0 seems like a sensible value.

**Comment by tih2010** [comment]
I am sure this it finished yet... I deinstalled gitextension 3.5.4 and installed the news 4.0-version.

Now there are error in all my repositories error on every pull/fetch:

```
"C:\Program Files\Git\bin\git.exe" pull --progress --jobs=0 "origin"
BUG: run-command.c:1521: you must provide a non-zero number of processes!
```

Of course this also happens on command line. Git (2.39.0) doesn't like --jobs=0 very much :-)

Going git config `fetch.parallel 0` helps for one repo, but doing it for each repo is pretty annoying... or this there a way to do it for all repos at one time?


Best
     Wolfram

**Comment by pmiossec** [comment]
>Going git config fetch.parallel 0 helps for one repo, but doing this for each repo is pretty annoying... or this there a way to do it for all repos at one time?

`git config --global fetch.parallel 0` ?

A discussion on the subject is in the issue #10514

**Comment by tih2010** [comment]
Thx, I didn't find the other issue! (Well... Google didn't :-) )
