### ISSUE TITLE
Control options `--full-history` and `--simplify-merges` when showing file history using FormBrowse

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9939]
### Feature description

When filtering the RevisionGrid for a file or a folder, a multitude of unrelated merge commits is displayed (using the default settings):

![grafik](https://user-images.githubusercontent.com/36601201/161624147-ecaf2507-0655-45b8-ae89-cfe6a160a9b7.png)

expected:

![grafik](https://user-images.githubusercontent.com/36601201/161624806-89e97134-6b30-48b0-9052-3277e58f9e28.png)

So either automatically ignore `AppSettings.FullHistoryInFileHistory` if `AppSettings.UseBrowseForFileHistory`.
Or else add a CheckBoxes to the AdvancedFilterDialog for the `AppSettings.FullHistoryInFileHistory` and the dependent `AppSettings.SimplifyMergesInFileHistory`  (disabled unless filtering like `Ignore case`).

![grafik](https://user-images.githubusercontent.com/36601201/161619307-8e8fdcac-fec2-4529-82e7-6e15693a14a9.png)

### Environment

- Git Extensions 33.33.33
- Build 2ab3f91f56c2590c3a5e741b624cb4561607f4c1
- Git 2.35.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.3
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
Would this setting be specific to showing history?

**Comment by mstv** [comment]
> Would this setting be specific to showing history?

No, they apply to most variants of filters - perhaps excluding filtering for branches.

**Comment by gerhardol** [comment]
I often want to see the merge commits, to understand what happened
(a reason to not use merge commits)
> So either automatically ignore AppSettings.FullHistoryInFileHistory *if AppSettings.UseBrowseForFileHistory*.

if there is a filter

> Or else add a CheckBoxes to the AdvancedFilterDialog for the AppSettings.FullHistoryInFileHistory and the dependent AppSettings.SimplifyMergesInFileHistory (disabled unless filtering like Ignore case).

My preferred solution
