### ISSUE TITLE
I can't set %HOME% to a custom home for portable use

### ISSUE THREAD

**Issue by amr66** [gitextensions/gitextensions#9941]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19042.0
- .NET Framework 4.8.4470.0
- DPI 96dpi (no scaling)

### Issue description

I use git and GitExtensions on an USB-Stick. My configuration needs to use a Home directory, located on the USB-Drive as well. I start GitExtension with a %HOME% variable set, but it doesn't recognizes it, while the git-cmd does. A work around is to the set the custom home dir, but that only works with an absolute path which contains the drive letter, what i don't want...
![gitext_home](https://user-images.githubusercontent.com/10866105/161816983-5330cb93-5c39-4e10-abf4-9e9331f08b6f.jpg)
If a HOME variable is set, shouldn't it point to my custom home path?

In GitExtensions.config I have
````
<setting name="IsPortable" serializeAs="String">
    <value>True</value>
</setting>
````
and GitExtension.settings has

````
<item>
    <key>
      <string>customhomedir</string>
    </key>
    <value>
      <string>E:\gisstick_x64\portable\Home</string>
    </value>
  </item>
````
Changing this to a relative path is accepted, but doesn't work when I open a repository somewhere on my drive.

### Steps to reproduce

Start GitExtension from command prompt or batch file which sets the %HOME% variable.

**Comment by gerhardol** [comment]
`HOME` is used for Git settings. (I believe HOME is used in *nix application, normally not in Windows apps.)
Set `USERPROFILE` if you want to store GE settings etc somewhere else (not sure if this affects portable at all).

**Comment by amr66** [comment]
Yes, that works. I'd still prefer to set %Home%, though. But I can live with that, too. Thank you!

**Comment by vbjay** [comment]
Portable is designed to be self contained. Why it's called portable.
 https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Settings/AppSettings.cs#L53

So home stores settings in the folder where app is located. If not portable it will use user profile. Think of portable as if you stick on flash drive.

**Comment by amr66** [comment]
@vbjay thats what I am doing, using a flash drive. But if I opened a repo and want to push it to a remote for example, the envoked git only finds its home folder when setting an absolute path in GE. That's not portable. I wondered why git uses a HOME variable and GE does not (or: not in the same way).

**Comment by mstv** [comment]
GE sets `HOME` before running git. The logic can be found in https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/EnvironmentConfiguration.cs starting with `ComputeHomeLocation` at line 67.

**Comment by campbellja** [comment]
Hi @RussKie is this still up for grabs or first does it require a review? cheers

**Comment by RussKie** [comment]
Thanks for the interest @campbellja. The issue is up for grabs, so you're welcome to propose a fix. 

A general suggestion - if a change is not complex and reasonably straight-forward, then a PR generally works. However, if a change is complex, then it may worth drafting a proposal and discussing it first (though a prototype could be helpful). This way you don't waste (too much) time, if your proposal doesn't align with the team/community vision.
