### ISSUE TITLE
In dark themes, focus is behaving differently (no focus on text input in merge window)

### ISSUE THREAD

**Issue by LukasKubicek** [gitextensions/gitextensions#9945]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4470.0
- DPI 168dpi (175% scaling)

### Issue description

When you open the merge window, normally the focus in in the text input "merge branch: " and you can start typing the branch name. However when GitExtension is set to use Dark theme (any of them), then merge window is opened without focus on text input and it is necessary to click into the text input first before you can start typing branch name.

### Steps to reproduce

![image](https://user-images.githubusercontent.com/2196235/162194283-683f8e16-d075-4848-b37c-5f2552d816f2.png)

**Comment by gerhardol** [comment]
Unfortuately, theming isnot included in next version (not working with .NET6) so this is not applicable right now.
