### ISSUE TITLE
After updating my Git version to `2.35.2.windows.1` my repoisitory doesn't show any commits

### ISSUE THREAD

**Issue by BenDol** [gitextensions/gitextensions#9954]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.35.2.windows.1
- Microsoft Windows NT 10.0.19043.0
- .NET Framework 4.8.4470.0
- DPI 96dpi (no scaling)

### Issue description

After updating my Git version to `2.35.2.windows.1` my repoisitory doesn't show any commits (this worked before updating Git). Some repositories are working fine, but some show no commits now.

![image](https://user-images.githubusercontent.com/1935706/163228755-eeba8b47-d2ae-4a62-b0ba-59d236a38bfd.png)
 

### Steps to reproduce

Update to the latest git version (2.35.2.windows.1) open repositories until you find one that can't show commits.

### Did this work in previous version of GitExtensions?

It worked in the older versions of Git

### Diagnostics

NA

**Comment by cristianst85** [comment]
I can confirm the above issue. It works fine with git version 2.35.1.windows.1 and git version 2.35.1.windows.2, but not with git version 2.35.2.windows.1.

https://github.com/git-for-windows/git/releases/tag/v2.35.2.windows.1
https://github.com/git/git/blob/v2.35.2/Documentation/RelNotes/2.35.2.txt

**Comment by cristianst85** [comment]
The issue is due to some security hardening. 

For example when trying to run `"git" clean -x -d --dry-run` there is an error that is shown:

```
fatal: unsafe repository ('D:/Repositories/MyRepo' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory D:/Repositories/MyRepo
```

After adding that respective directory to the exception list the issue is resolved and all the commits are shown again in Git Extensions.

**Comment by mstv** [comment]
The error should have been traced in the Git Command Log (`F12`).

The current dev build pops up the git error message.

Though I have not managed yet to add the path of my repo copy on a SMB share of my local NAS.

**Comment by vbjay** [comment]
https://github.blog/2022-04-12-git-security-vulnerability-announced/

**Comment by vbjay** [comment]
In the future just use the copy button on the about dialog and then paste in issue.

**Comment by thbighead** [comment]
Hey guys, just to add more info about this issue:

When using a repository placed in WSL pathing even after running "git config --global --add safe.directory //wsl$/Ubuntu-20.04/path-to-my-repo" the error persists.

**Comment by gerhardol** [comment]
The popup in master/vNext is including the full error message as above for the git-for-each-ref command.
(The GE team do not wish to get issue reports about this, but it is hard to suppress this failure only without suppressing other issues.)

> When using a repository placed in WSL pathing even after running "git config --global --add safe.directory //wsl$/Ubuntu-20.04/path-to-my-repo" the error persists.

That is a Git configuration issue. I tried mapping to a drive, still fails. So maybe network drives are no longer supported (in this case it is unfortunate that \\wsl$ is handled as network drive).

The WSL integration in master (vNext) works fine. (Uses wsl git.)

**Comment by pmiossec** [comment]
> That is a Git configuration issue. I tried mapping to a drive, still fails. So maybe network drives are no longer supported (in this case it is unfortunate that \wsl$ is handled as network drive).

From what I understand, you have to prefix it with `%(prefix)/`
See https://github.com/desktop/desktop/issues/14336#issuecomment-1098490973
and 
https://github.com/desktop/desktop/pull/14368

**Comment by mstv** [comment]
The error messages and warnings are incomplete and pretty misleading, either without `%(prefix)/` or if with then not with three slashes!

> So I imagine that the good command line is like (not tested):
> 
> `git config --global --add safe.directory '%(prefix)///wsl$/Ubuntu-20.04/path-to-my-repo'`

Yes, the UNC path `\\smb.server\share\path\repo\` must be written with forward slashes and be prefixed with `%(prefix)/`, i.e.

`git config --global --add safe.directory '%(prefix)///smb.server/share/path/repo'`

**Comment by pravic** [comment]
Also beware the casing:

> git config --global --add safe.directory d:/Repositories/MyRepo
> git config --global --add safe.directory D:/Repositories/MyRepo

The first path will not work. But GitExtensions shows the full path to the affected repository, just copy it.

**Comment by remcoros** [comment]
After updating Git for windows to 2.35.2 I had a similar issue where Git Extensions thought it was in the middle of a merge.

I saw git status output complaining about some deprecated file monitor feature and had to use:

    git config --global core.fsmonitor true

Which fixed it.

**Comment by ghd796** [comment]
%(Prefix)/ not working in visual studio 2022

I have updated git using 
git config --global --add safe.directory '%(prefix)///IRIS/Git/ToolRepairAssistant22'
and now I can open the git directory in git extension gui.
However I do get warnings:

warning: encountered old-style '//IRIS/Git/ToolRepairAssistant22' that should be '%(prefix)//IRIS/Git/ToolRepairAssistant22'

However

Visual studio remote works only if I leave it as //IRIS/Git/ToolRepairAssistant22 issues
if I add the %(prefix)/ it errors out when I try to push/pull from remote.

How do I get visual studio to work with %(prefix)/

**Comment by pravic** [comment]
Also, it's possible to ignore all directories and forget about this problem whatsoever:

```
git config --global --add safe.directory *
```

**Comment by ghd796** [comment]
> Also, it's possible to ignore all directories and forget about this problem whatsoever:
> 
> ```
> git config --global --add safe.directory *
> ```

Doesn't seem to work for me. I had to list each git folder one by one in my config file. The git doesn't seem to use wildcards

**Comment by pravic** [comment]
@ghd796 It does work for me. 

git version 2.36.0.windows.1

.gitconfig:

```ini
[safe]
  directory = *
```

**Comment by vbjay** [comment]
You can do that. However, that negates the security fix that was put in
place.

https://github.blog/2022-04-12-git-security-vulnerability-announced/

**Comment by ghd796** [comment]
@vbjay
> You can do that. However, that negates the security fix that was put in place. https://github.blog/2022-04-12-git-security-vulnerability-announced/

if I don't do this my gits are unusable. and Putting %(prefix)/ into visual studio doesn't work for me either. Visual studio will only work if I leave the path the old way.

using git config --global --add safe.directory 'directory name' is the only way I can open the gits in gitExtensions. even if it does have errors. 
I don't store my gits on git hub I store them on a internal networked drive.

**Comment by vbjay** [comment]
> @vbjay
> > You can do that. However, that negates the security fix that was put in place. https://github.blog/2022-04-12-git-security-vulnerability-announced/
> 
> if I don't do this my gits are unusable. and Putting %(prefix)/ into visual studio doesn't work for me either. Visual studio will only work if I leave the path the old way.
> 
> using git config --global --add safe.directory 'directory name' is the only way I can open the gits in gitExtensions. even if it does have errors. 
> I don't store my gits on git hub I store them on a internal networked drive.

Better way is to make a remote to network share and do local abd do push/pull in a local repo. Even could make network share a bare repo.

**Comment by pmiossec** [comment]
> I don't store my gits on git hub I store them on a internal networked drive.

You also have the possibility to map the network share to a local drive and your problem are solved (no need to add to safe directory list anymore....)

**Comment by andrey-helldar** [comment]
Me too

![image](https://user-images.githubusercontent.com/10347617/171688323-a9981c71-31fa-43b5-8026-5bd82e2269bf.png)

```
- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.36.1.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET Framework 4.8.4515.0
- DPI 96dpi (no scaling)
```

**Comment by RussKie** [comment]
I installed the latest git (2.37) and I don't get this error. How can I emulate it?

```
$ git config --global -l

core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
core.autocrlf=true
user.name=..
user.email=..
diff.guitool=p4merge
difftool.p4merge.path=C:/Program Files/Perforce/p4merge.exe
difftool.p4merge.cmd="C:/Program Files/Perforce/p4merge.exe" "$LOCAL" "$REMOTE"
merge.guitool=p4merge
mergetool.p4merge.path=C:/Program Files/Perforce/p4merge.exe
mergetool.p4merge.cmd="C:/Program Files/Perforce/p4merge.exe" "$BASE" "$LOCAL" "$REMOTE" "$MERGED"
pull.rebase=false
fetch.prune=false
rebase.autostash=false
rebase.autosquash=true
```

**Comment by andrey-helldar** [comment]
@RussKie, just remove `safe` section from global git config and open repository settings dialog in app.

**Comment by RussKie** [comment]
I don't have "safe" in any of my configs. That's why I'm curious how to enable it....


I did somehow get it for one of my repos, and it looks like this in the latest master:
![image](https://user-images.githubusercontent.com/4403806/188265967-e5600d70-bc47-46ca-9ea0-602185fd628f.png)

**Comment by andrey-helldar** [comment]
@RussKie, hm... A little later, I can write detailed steps to reproduce this error.

**Comment by vbjay** [comment]
Run 

```bash
git ls-files -z --unmerged
```
in a git bash in your repo folder or console tab in ge. 


Does it suggest --add-safe-directory in the output?

**Comment by RussKie** [comment]
> Run
> 
> ```shell
> git ls-files -z --unmerged
> ```
> 
> in a git bash in your repo folder or console tab in ge.
> 
> Does it suggest --add-safe-directory in the output?

![image](https://user-images.githubusercontent.com/4403806/188267290-a2a2ee12-a068-4dcf-b1df-1aeb6311adbe.png)

**Comment by RussKie** [comment]
Essentially, I want to see if we need to trap this specific error and provide a specific error message, or the dialog I posted earlier would suffice for the v4 release.

**Comment by andrey-helldar** [comment]
@RussKie, I reproduce in a virtual machine, so the steps from the very beginning.

Environment: Windows 11 Pro

1. Download & install Git 2.37.3 64bit
2. Download & install Git Extensions 3.5.4 (not a portable)
3. `git clone https://github.com/gitextensions/gitextensions.git`
4. Open the Git Extensions
    1. Select a English
    2. Configure a username and an email: `John`, `foo@example.com`
    3. Configure sh tools (git):
        - C:\Program Files\Git\bin\git.exe
        - C:\Program Files\Git\bin\
    4. Run the Git Extensions and go to the SSH page in Settings:
        - Change to PuTTY and set 
5. Restart Git Extensions
6. Open local repository
7. Menu: `Repository` > `Remote repositories`

In the absence of safe.directory settings, this window already had errors.

Now I don't see these errors. Perhaps something has changed on the part of Git itself.

But, https://github.blog/2022-04-12-git-security-vulnerability-announced/

**Comment by RussKie** [comment]
Interestingly enough, I see the error for another clone 🙄 
![image](https://user-images.githubusercontent.com/4403806/188267375-678ae9c0-37dc-4ccd-b140-982a39d19b17.png)

**Comment by RussKie** [comment]
Thank you @andrey-helldar, looks like one of my clones exhibit the issue.

**Comment by andrey-helldar** [comment]
@RussKie, by the way, when I wrote the instructions above, I used the `git clone https://github.com/...` command.

In my repositories I use `git clone git@github.com:...`

BUT, perhaps the problem arose precisely when updating git to version `2.36.1`.

Today I tried to go through the steps with git `2.37.3` and did not find any problems.

¯\_(ツ)_/¯

**Comment by RussKie** [comment]
v4 shows a reasonable error dialog, which is good enough
![image](https://user-images.githubusercontent.com/4403806/188265967-e5600d70-bc47-46ca-9ea0-602185fd628f.png)

**Comment by Mike-E-angelo** [comment]
Opening `C:\Users\<user>\.gitconfig` and adding:
```
[safe]
	directory = *
```

Is the only way I can work around this.  I tried adding the directory directly but that does not seem to do the trick.  I would prefer to add only the directory that is impacted by this.

**Comment by mstv** [comment]
@Mike-E-angelo, from above comments:

> the UNC path `\\smb.server\share\path\repo\` must be written with **forward** slashes and be prefixed with `%(prefix)/`, i.e.

`git config --global --add safe.directory '%(prefix)///smb.server/share/path/repo'`

> Also beware the casing:

~~~
    git config --global --add safe.directory d:/Repositories/MyRepo
    git config --global --add safe.directory D:/Repositories/MyRepo
~~~

The first path will not work. But GitExtensions shows the full path to the affected repository, just copy it.

**Comment by Kebechet** [comment]
I also experienced this problem. In my case my notebook was on battery and after some time turned off. The `HEAD` file in `.git` directory got corrupted (full of NULLs). So I changed it to: `ref: refs/heads/development` and gitextensions was again able to load my branches and commits.
But some of my commited files got corrupted as well (also full of NULLs) and these corruption changes werent commited or visible in git as changed. So I pushed my last changes to `origin/feature` branch, removed the whole git repository, cloned it again, checkout the feature branch and everything is working and I havent lost any changes.

**Comment by vbjay** [comment]
Your xorruption sounds  more like files were being written to and your device lost power or mid write lost power. Lucky hard drive wasn't corrupted. I'd run a disk check to validate.

**Comment by gerhardol** [comment]
This Git change in 2.35.2 (with adjustments in 2.35.3 and 2.37) is still reported by many users.
Keeping this as the main reference for this change in Git.
In GE 4.0 you get a popup with the Git output including the suggested change,  in GE 3.x this error may be swallowed.

The Git documentation:
https://git-scm.com/docs/git-config#Documentation/git-config.txt-safedirectory

One example link where this is discussed: https://stackoverflow.com/questions/71849415/i-cannot-add-the-parent-directory-to-safe-directory-in-git

**Comment by RussKie** [comment]
I am starting to think we need to special case this error, and present a
dialog with a clean user message and no link to raise an issue.

**Comment by pmiossec** [comment]
> I am starting to think we need to special case this error, and present a dialog with a clean user message and no link to raise an issue.

I was about to write the same thing because that's not the kind of problem that is temporary. Some users will encounter it again in the future. I was thinking about a pop-up with a clear explanation and a question 'Do you trust this repository?' that will run the git config command and reload the repository.

**Comment by RussKie** [comment]
I wasn't thinking that deep, but I very much like the way you're
thinking about it.

**Comment by RussKie** [comment]
Reopening as this is not completely fixed. If a repo is opened via a Windows Explorer context menu there won't be a popup and the repo remains blank.

**Comment by pmiossec** [comment]
> Reopening as this is not completely fixed. If a repo is opened via a Windows Explorer context menu there won't be a popup and the repo remains blank.

Can you be more explicit? With the "GitExt Open Repository" menu item of the contextual menu from the File Explorer?
Because it's working for me.

Are you sure it does not open an older built of GE?

**Comment by RussKie** [comment]
Yes. I installed the [latest 4.0.1 build](https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45501806/artifacts).
Here's a demo:

https://user-images.githubusercontent.com/4403806/204529112-ac6b743f-8417-4a07-8c9f-28db97bb3574.mp4



gitextensions2 has dubious ownership, and opened from the taskbar the app shows no error message. Also, switching to another bad repo results in no error message shown either. **Only after** a good repo is opened, the error message is shown.
