### ISSUE TITLE
`Number of changed files` disappears

### ISSUE THREAD

**Issue by mstv** [gitextensions/gitextensions#9955]
### Environment

- Git Extensions 33.33.33
- Build c3b0d64d8c8b90ead9b1d27571981656571aac2a
- Git 2.35.2.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET 6.0.3
- DPI 96dpi (no scaling)

### Issue description

The `Number of changed files` disappears from the `Commit` button and from the Artificial Commits occasionally (too often).
The state overlay of the taskbar icon is affected, too.

Basically, the `Commit` button and the Artificial Commits should not be undecorated while the status is updated or is invalidated because a modal dialog is active.
Currently, it looks like there are no changes - very misleading.

### Steps to reproduce

If I knew

### Did this work in previous version of GitExtensions?

yes

**Comment by gerhardol** [comment]
This was changed partly by your comments as the old value was misleading.
The commit button is grey in this situation. Some similar marker would be nice for artificial commits too. Question mark?

**Comment by mstv** [comment]
> This was changed partly by your comments as the old value was misleading. The commit button is grey in this situation.

This is true only if a GE is minimized or if a modal dialog is active.
But if the main issue strikes, there is nothing: no taskbar icon overlay, green `Commit` button.

> Some similar marker would be nice for artificial commits too. Question mark?

Yes, please. That's what I had in mind.

**Comment by gerhardol** [comment]
> > This was changed partly by your comments as the old value was misleading. The commit button is grey in this situation.
> 
> This is true only if GE is minimized or if a modal dialog is active. But if the main issue strikes, there is nothing: no taskbar icon overlay, green `Commit` button.

Not sure what this is, will take a look.

> > Some similar marker would be nice for artificial commits too. Question mark?
> 
> Yes, please. That's what I had in mind.

It is easier to explain when there are no changes, so "blank" if modal or no information yet. 
![image](https://user-images.githubusercontent.com/6248932/163484026-5b7cbceb-7255-45d9-91d5-2b6dcf925a1b.png)

**Comment by mstv** [comment]
I have found how to reproduce this or a related issue.
If git processes are terminated on cancellation request, the status of the artificial commits is not updated.
The issue occurs with 3cd35a3b72c0b8114324e516cda85a0a9dde8370 in combination with 903f9245e6e4641526922e951e024185d8d0f29b on top of #9958:

![image](https://user-images.githubusercontent.com/36601201/164113857-6a6ec336-7200-45bd-8eff-76914cdbf651.png)

This proves that `Application.DoEvents()` must not be called (in `RefreshRevisions`, https://github.com/gitextensions/gitextensions/pull/9906#discussion_r830536551 👍).

Though despite of this, the application behavior must not change if git processes are terminated on cancellation.
I suspect that the change-count update cancels things too early. If we let git run to the end, the result is displayed although the update was cancelled.
