### ISSUE TITLE
Support install without admin privilege 

### ISSUE THREAD

**Issue by luwangshell** [gitextensions/gitextensions#9957]
### Feature description

Installing Git does not need admin privilege, however installing GitExt does. The installation does ask installing for yourself or all users, but even selecting only for myself, and change the installation path to appdata folder, it still requires admin privilege.

### Environment

- GitExtensions version:
- GIT version: 
- OS version: 
- .NET version:

**Comment by RussKie** [comment]
The installer registers COM objects (Explorer menus) that require admin
privileges.

**Comment by gerhardol** [comment]
Use the portable version for non admin install.

**Comment by vbjay** [comment]
Download portable and extract to a folder and run from there. Do not put on
program...files folder.
