### ISSUE TITLE
Enhancements for remote-branch checkout flow

### ISSUE THREAD

**Issue by wheezil** [gitextensions/gitextensions#9959]
### Feature description

UPDATE: please see later discussion and Igor's comments.  Many of these items can be worked around, are no longer true, or have alternate flow methods.

This is kind of minor bug report, and kind of an ER, depending on how you look at it.  My team's workflow goes like this:

- Open assigned bug in JIRA
- Use JIRA's integration with BitBucket to create a branch
- Switch to git client and checkout the new branch from origin

### Description
This is not difficult, but I find that git extensions makes it clunkier than needed in a few ways:

- I hit CTRL-. to checkout a branch
- Focus starts on the "select branch" textbox
- I would like to search for remote branches but if I forgot to pull I have to cancel and come back, and when I come back of course whatever I started typing for the branch name is blank so I type it again
- No hotkey assigned to choose "remote", or more specifically, the ALT-B hotkey is assigned to both local and remote, which is weird.  Why not ALT-L for local and ALT-R for remote?
- After hitting ALT-B twice to select "remote" focus does not go to the "Select branch" textbox, so I have to click there, or tab multiple times
- When I start entering the branch name, I have to exactly type origin/feature/... or origin/bugfix/... with no option to search by name, only prefix match supported
- If I forgot the branch name, switch to JIRA, and come back, focus has been lost from the "Select branch" textbox, so I must click again.

None of this rises above the level of "annoyance", but why not make git-extensions even better?

### Enhancement request 
In the checkout dialogs:

1. Reassign "local" and "remote" hotkeys to ALT-L and ALT-R
2. Remember the last choice of local-vs-remote branch
3. Put focus in "Select branch" textbox after choosing local or remote
4. Partially match branches by substring.  Do not require full prefix to match.
5. Be able to pull or otherwise choose new remote branch names while in the dialog, do not force me to cancel and start again

If I were looking at this as a developer, I might decide that 5 is really its own ER.  But 1-4 seem like they go together.  If desired, I can split this into two ERs.

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.32.0.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4420.0
- DPI 96dpi (no scaling)

Thanks for listening!

**Comment by RussKie** [comment]
Thank you for the report. Some of it does feel clunky, though some of it feels a little "user driven" too. Are you trying to use the app in "keyboard only" mode? E.g., with the mouse the whole scenario is literally  3-4 mouse clicks away without any keyboard input:
![image](https://user-images.githubusercontent.com/4403806/163671087-35274b3f-87e8-4c8c-b0f3-83014f1b0ec5.png)


> * I would like to search for remote branches but if I forgot to pull I have to cancel and come back, and when I come back of course whatever I started typing for the branch name is blank so I type it again

This is a "user error" scenario, i.e., if you forgot to fetch - you forgot to fetch. There's nothing we can do in this dialog, **nor we must do anything related to fetching in this dialog**.
There's a "Periodic Background Fetch" plugin that can auto-fetch remote data, if required. 



> * No hotkey assigned to choose "remote", or more specifically, the ALT-B hotkey is assigned to both local and remote, which is weird.  Why not ALT-L for local and ALT-R for remote?

Because it is easier to switch between the two using the single shortcut than having two different shortcuts. We use this approach in various dialogs (including this dialog in several flows) where the functionality is mutually exclusive.
And there are a finite number of shortcuts we can have too.

> * After hitting ALT-B twice to select "remote" focus does not go to the "Select branch" textbox, so I have to click there, or tab multiple times


I _suppose_ I could see an argument here. 
The edit control is actually a single TAB away. 

> * When I start entering the branch name, I have to exactly type origin/feature/... or origin/bugfix/... with no option to search by name, only prefix match supported

Yes, this could do with an improvement. Similar to the Branches dropdown in the toolbar:
![image](https://user-images.githubusercontent.com/4403806/163671480-5ac196a6-7400-4289-9e9b-08a840ec2ded.png)

A pull request with an improvement to the filtering functionality is welcome.

> * If I forgot the branch name, switch to JIRA, and come back, focus has been lost from the "Select branch" textbox, so I must click again.

I tried this flow - i.e., typing something in the edit control, then switching to another app and back - the focus remained with the edit control.

-- 

I don't have 3.5.4 installed, and use one the latest(-ish) dev builds.

**Comment by wheezil** [comment]
Igor,

Thanks so much for your quick and detailed response!  I hope you don't feel I am being critical.  I really do love your tool.

Apologies for a couple items, I either misread them or remembered behavior from an older version or different environment.  I have confirmed that these are not issues, as you say:

- Number of tabs to move focus between local/remote, and back to "select branch" is indeed a single tab
- Focus returns  to "select branch" after tab to other app and back

I would like really the option to pull branches before checkout, but I will experiment with auto-pull first, to see how it works.  I've had trouble with this kind of feature in SourceTree so I've stayed away from it, but of course you are not SourceTree.

I think I see your point about the substring search in the branch list in the upper-left of the UI.  I haven't adopted using that in my flow for remote branch checkout so I gave it a try.  I am kind of a keyboard freak, so I did 

- SHIFT-CTRL-P to pull
- Click on branch searchbar and type JIRA number
- Select origin branch, right-click and choose "pull and checkout"

I like how this works.  It would be nice to have a global hotkey for selecting the searchbar.  Also would be nice to have a hotkey to collapse the branch tree.  Perhaps they exist and I am not finding it?

I think this leaves still leave some items on which we can base a remnant ER:

- Search branches in checkout dialog by substring instead of prefix
- Checkout dialog remembers local-vs-remote last choice
- Hotkey for branch search (or show hotkey in tooltip, or make it assignable)
- Hotkey for collapse branch tree (or show hotkey in tooltip, or make it assignable)

Thanks!
john

**Comment by RussKie** [comment]
> I hope you don't feel I am being critical. 

No worries at all :)



> * Hotkey for branch search (or show hotkey in tooltip, or make it assignable)
> * Hotkey for collapse branch tree (or show hotkey in tooltip, or make it assignable)

The app has a lot of customisable hotkeys, which you can find in the Settings dialog:
<img width="864" alt="image" src="https://user-images.githubusercontent.com/4403806/163682921-c85e7419-6dc5-4e05-b0ba-3fdf23fe7f13.png">

**Comment by wheezil** [comment]
@RussKie I looked for these two hotkey settings but did not find them.  Do they exist?  The "find" would be especially handy.  As I mentioned, I am a keyboard freak.

**Comment by mstv** [comment]
`Ctrl+0` selects the Left Panel, `Tab` selects the search field.

**Comment by mstv** [comment]
`Cursor Left` collapses tree nodes.

**Comment by wheezil** [comment]
You guys are great.  Thanks for all the help.  Is there anything left to turn into an ER?

**Comment by RussKie** [comment]
> Is there anything left to turn into an ER?

What's "ER"?

**Comment by gerhardol** [comment]
> > Is there anything left to turn into an ER?
> 
> What's "ER"?

This is already tagged as a feature-request (Enhancement Request is not used).
If someone is interested in the functionality, add a note in the issue and create a PR.

The actual request is not clear to me in a quick check.
The clearer it is, the more likely it is that someone finds this interesting and picks it up.

**Comment by wheezil** [comment]
I think we should just close it, since almost all of the items were addressed via usage patterns.
