### ISSUE TITLE
Add script actions to file tree menu 

### ISSUE THREAD

**Issue by totocaca123** [gitextensions/gitextensions#9974]
### Feature description

This feature is similar to what is done by sourcetree
https://blog.sourcetreeapp.com/2012/02/08/custom-actions-more-power-to-you/

It could be done by adding some options to the scripting features:
That's a very old feature and potentially interesting.

It would be good to have it this way:
![image](https://user-images.githubusercontent.com/42418580/164534016-9e125c24-85fe-49d1-bf86-ec0068a2ba49.png)

And having a variable called file selection/ folder selection or selection
![image](https://user-images.githubusercontent.com/42418580/164534214-b58e7b3f-67fd-483c-a371-b874ea6455dd.png)

And on context menu, having the possibility to see the script:
![image](https://user-images.githubusercontent.com/42418580/164534402-fe08d9d8-9b63-4e96-9a51-3d0404c8b2af.png)

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.33.0.windows.1
- Microsoft Windows NT 10.0.22598.0
- .NET Framework 4.8.9028.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
I had tinkered with this in the past (https://github.com/RussKie/gitextensions/compare/Run_scripts_from_FileTree) but it wasn't trivial, and it fell in between the cracks...

**Comment by totocaca123** [comment]
would be good to bring back this feature (don't know how fat it is for the current release)
