### ISSUE TITLE
Unsolved Conflict 

### ISSUE THREAD

**Issue by AbdelrahmanShalata** [gitextensions/gitextensions#9977]
### Environment

- GitExtensions version:3.5.4
- OS version: windows 10 pro
- .NET version: 4.5.2 framework

### Issue description

there is message show every time I want to push my code that told me there is conflict when I click on it I can't see any conflict  

![Screenshot_4](https://user-images.githubusercontent.com/104298952/164968899-e564ab25-4a0f-4efc-8f2a-202b2bec8ab2.png)

and there is not conflict 

![Screenshot_3](https://user-images.githubusercontent.com/104298952/164968942-d2654282-2c71-47bd-a042-c1711a026a5a.png)

### Steps to reproduce

1- open my branch
2-try to push or commit my code

**Comment by vbjay** [comment]
Do a fetch all. Look at the history of remote vs local.

**Comment by AbdelrahmanShalata** [comment]
no thing happened I try fetch by this comment in git bash:
git fetch --all

**Comment by vbjay** [comment]
And when you do rescan it shows no more files?  If so. Finish the merge.
Without your repo and specific info. Can't do much more than that.

**Comment by AbdelrahmanShalata** [comment]
do you main "rescan megre conflict" if you main it, it remove my commit code and still message show on

**Comment by mstv** [comment]
Could you share the Git Command Log (`F12`), please?
And perhaps the output of the regarding git commands, particularly of `git ls-files -z --unmerged`.

**Comment by AbdelrahmanShalata** [comment]
do you mean like this
![Screenshot_5](https://user-images.githubusercontent.com/104298952/164972530-0f44db76-a672-4cbe-8f73-7e56a9479ac7.png)

**Comment by mstv** [comment]
Thank you. Yes, for the first part. All commands seem to have succeeded (exit code 0).
Maybe the conflict is in one of the submodules.

The second request was meant to execute the git commands manually, e.g. in the Git Bash:

![image](https://user-images.githubusercontent.com/36601201/164978170-5b2fdf30-48d3-4899-8a27-33aded7d05e4.png)
```
M@M MINGW64 /d/Build/gitextensions3_dev ((50eed531c...)|MERGING)
$ git ls-files -z --unmerged
100644 e5167f36a09df7b4f04083f83ef82cca0c67b605 1       GitCommands/Git/Executable.cs100644 bc660238adeb0d5f171211a23e1e7321dc0939fb 2        GitCommands/Git/Executable.cs100644
0a8e2bbd77987b53fa8ae366eb2457951632dbdb 3  GitCommands/Git/Executable.cs100644 9c1026719c53458afd03388669ab9a9ed3e0af42 1        GitCommands/Git/ExecutableExtensions.cs100644
7b0a46d18f748cd07e7a92687dfe55eea4037ef3 2      GitCommands/Git/ExecutableExtensions.cs100644 b6aa9527782c3549b1c59653b31d3df12923adb8 3      GitCommands/Git/ExecutableExtensions.cs
```
You can try to abort the merge (backup of uncommitted changes is recommended before executing this):
```
M@M MINGW64 /d/Build/gitextensions3_dev ((50eed531c...)|MERGING)
$ git merge --abort

M@M MINGW64 /d/Build/gitextensions3_dev ((50eed531c...))
```

After you have **back-up**ped your uncommitted changes, you can use the `Abort merge` button of the Resolve dialog. It will do a hard reset to the current commit. Usually, this cancels any stateful git operation like unfinished merge, rebase or cherry-pick.

**Comment by mstv** [comment]
In your screenshot, the banner is lacking the `Abort` button.

![image](https://user-images.githubusercontent.com/36601201/164979021-c7989258-1606-4a97-94c3-c77ff2e00c72.png)

Have you been struggling with `.gitconfig`? https://github.com/gitextensions/gitextensions/issues/1653#issuecomment-1107527962

But a missing `Abort` button does not need to indicate an error. There is none after a cherry-pick with conflicts:

![image](https://user-images.githubusercontent.com/36601201/164979238-d80b042e-a673-4848-b4ed-67199e6dedf5.png)

**Comment by AbdelrahmanShalata** [comment]
-first for this commit "git ls-files -z --unmerged"  output:
![Screenshot_6](https://user-images.githubusercontent.com/104298952/165040924-63a53cc8-4ded-44e2-b160-e7cbce6bfc31.png)
-second for this commit "git merge --abort" output:
![Screenshot_7](https://user-images.githubusercontent.com/104298952/165041138-b3159ffe-73de-4f28-8d88-b693c05e8eac.png)
and nothing happend

-third I didn't get what should I do for this commit "Have you been struggling with .gitconfig?"

**Comment by wikancz** [comment]
I had the same problem. It is probably related to new Git version and those hints (core.useBuildinFSMonitor will be...).
As soon as I ran mentioned "git config" command the message disappeared.

**Comment by pmiossec** [comment]
> -first for this commit "git ls-files -z --unmerged" output: ![Screenshot_6](https://user-images.githubusercontent.com/104298952/165040924-63a53cc8-4ded-44e2-b160-e7cbce6bfc31.png) -second for this commit "git merge --abort" output: ![Screenshot_7](https://user-images.githubusercontent.com/104298952/165041138-b3159ffe-73de-4f28-8d88-b693c05e8eac.png) and nothing happend
> 
> -third I didn't get what should I do for this commit "Have you been struggling with .gitconfig?"

In fact, I think that the "hint:" text that cause the problem because GitExtensions check that the output is empty:

https://github.com/gitextensions/gitextensions/blob/master/GitCommands/Git/GitModule.cs#L526

And that should be a recent version of Git that start to output this hints.

After a quick look, I didn't find a command line parameter that prevent outputting this "hint".
Maybe GE will have to ignore these lines...

**Comment by AbdelrahmanShalata** [comment]
thank you @wikancz your answer worked with me

**Comment by ImoutoChan** [comment]
> I had the same problem. It is probably related to new Git version and those hints (core.useBuildinFSMonitor will be...). As soon as I ran mentioned "git config" command the message disappeared.

Could you provide the exact command, please? I have the same problem.

**Comment by wikancz** [comment]
It is on screenshot above.
`git config advice.useCoreFSMonitorConfig false`

**Comment by pmiossec** [comment]
I think that GE should run the commmand `git -c "advice.useCoreFSMonitorConfig=false" ls-files -z --unmerged`.

What do you think @mstv ?

>>Could you provide the exact command, please? I have the same problem.
>It is on screenshot above. `git config advice.useCoreFSMonitorConfig false`

Reading at the hint message, I don't think it is the good solution.
You are hiding the hint, that is good to fix the GitExtension problem.

But I think that a better solution is to stop using `core.usebuiltinfsmonitor` (with `git config --global --unset core.usebuiltinfsmonitor` which is probably a better fix...) and maybe using `core.fsmonitor` as recommended ( https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefsmonitor ).

But you will have to investigate the consequences (but maybe you already know some of them because you conscientiously enabled `core.usebuiltinfsmonitor` in the past...)

**Comment by gerhardol** [comment]
> I think that GE should run the commmand `git -c "advice.useCoreFSMonitorConfig=false" ls-files -z --unmerged`.

No, that is a user setting that a user has explicitly set and may have reason to use.
There may be reasons to use older Git versions, the settings could be reintroduced.

If something is done, it could be to warn about bad settings.
That need to be done each time a repo is opened.
(Not endorsing that now.)

**Comment by pmiossec** [comment]
> No, that is a user setting that a user has explicitly set and may have reason to use. There may be reasons to use older Git versions, the settings could be reintroduced.

@gerhardol  Either you misread the command or I don't understand your point of view...
But here, the command is just to hide the advice because otherwise the output is badly interpreted (and not to disable the feature...)

But maybe a better solution for **all the commands that expect an empty output** is simply to tell GE to ignore the first lines starting with `hint:`...

**Comment by ImoutoChan** [comment]
So the command above did the trick but only for single repo. All other repos on my pc showed the same error (unmerged changes).

What actually helped: I found this file `C:\Program Files\Git\etc\gitconfig` and changed `useBuiltinFSMonitor =` from true to false. It solved my issue for all repos on my machine.

**Comment by pmiossec** [comment]
> So the command above did the trick but only for single repo. All other repos on my pc showed the same error (unmerged changes).

That's the goal of the '--global' parameter...

**Comment by mstv** [comment]
The '--system' parameter pertains to the `C:\Program Files\Git\etc\gitconfig` file (and usually requires admin privileges).
