### ISSUE TITLE
merge conflict detected even on empty repo

### ISSUE THREAD

**Issue by vincent456** [gitextensions/gitextensions#9980]
### Environment

- GitExtensions version:3.5.4.12724
- GIT version: 2.36.0.windows.1
- OS version: Windows 11 entreprise 21H2 biild 22000.613
- .NET version: 4.8.4470.0

### Issue description

Git extensions detect a merge conflict. Therefore it refuses to commit.
Of course it happen in non conflict situations, for example git status shows no conflict or even on a freshly created repository

### Steps to reproduce

Eihter create an empty repository or check a repository that is not in conflict
check that git cli doesn't show a conflict
but git extensions shows a conflict

**Comment by mstv** [comment]
Duplicate of #9977 (the workaround is there)
