### ISSUE TITLE
"Reword commit" editor appears twice and "Browse" window is not refreshed

### ISSUE THREAD

**Issue by shirayuki** [gitextensions/gitextensions#9987]
### Environment

- GitExtensions version: master branch
- GIT version: 2.36.1
- OS version: Windows 10 Professional
- .NET version: 

### Issue description

After selecting "Reword commit", the external editor appears twice and "Browse" window is not refreshed.

### Steps to reproduce

- Right click on a commit and select "Reword commit".
- Close the external editor.

Actual behavior:
- The external editor appears twice.
- "Browse" window is not refreshed.

Expected behavior:
- The external editor appears once.
- "Browse" window is refreshed.

### Did this work in previous version of GitExtensions?

Works fine in version 3.5.4.

**Comment by gerhardol** [comment]
Please test the PR.
Refresh worked for me before.

**Comment by shirayuki** [comment]
The PR works for me.
But "Refresh" still does not work.

**Comment by gerhardol** [comment]
> The PR works for me. But "Refresh" still does not work.

I cannot reproduce with Reword commit. However Edit commit followed by Continue the grid view is occasionally completely empty. Is that what you see?
Still happens with #9948.
The revisions are loaded, it is just that nothing is displayed.

**Comment by shirayuki** [comment]
> However Edit commit followed by Continue the grid view is occasionally completely empty. Is that what you see?

No.
This issue seems to be related to checkbox "Keep dialog open".
If it is not checked, the grid view is not refreshed after Reword.

**Comment by gerhardol** [comment]
The "non refresh" issue when "Keep dialog open" was unchecked is unchanged from what I see.

The "blank when continue" is probably new in vNext.

**Comment by shirayuki** [comment]
> The "non refresh" issue when "Keep dialog open" was unchecked is unchanged from what I see.

#9992 works for me. The "non refresh" issue is fixed.
