### ISSUE TITLE
Compile as x64 app, stop targeting x86.

### ISSUE THREAD

**Issue by RussKie** [gitextensions/gitextensions#9990]
### Environment

https://github.com/gitextensions/gitextensions/tree/net7.0

### Issue description

I tried [porting the app to .NET 7](https://github.com/gitextensions/gitextensions/tree/net7.0), and whilst the source compiled without any issues, I couldn't run the app:
```
Application: GitExtensions.exe
CoreCLR Version: 7.0.22.18007
.NET Version: 7.0.0-preview.4.22180.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException: Could not load file or assembly 'D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net7.0-windows\GitExtensions.dll'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net7.0-windows\GitExtensions.dll'
```

It took some head scratching, until I figured it was related to the app compiled as 32-bit. I tried removing `<Prefer32bit>true</Prefer32bit>`, and it compiled again without any issues. The app even started, opened the dashboard and then a repo. However, the commit dialog would crash the app.
```
Faulting application name: GitExtensions.exe, version: 33.33.33.0, time stamp: 0x624543e5
Faulting module name: ntdll.dll, version: 10.0.22000.527, time stamp: 0x931cda92
Exception code: 0xc0000409
Fault offset: 0x000000000009326f
Faulting process ID: 0xe560
Faulting application start time: 0x01d864e4378c1b9e
Faulting application path: D:\Development\gitextensions\artifacts\Debug\bin\GitExtensions\net7.0-windows\GitExtensions.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: b719ec28-03cc-4e2c-b53a-3a02d40f532c
Faulting package full name: 
Faulting package-relative application ID: 
```

My hypothesis is that we have some 32-bit specific code/incorrect interop definitions that crash the process... 

Relates to https://github.com/gitextensions/gitextensions/discussions/9869.

### Steps to reproduce

- Pull https://github.com/gitextensions/gitextensions/tree/net7.0
- Update all instances of `<Prefer32Bit>` to `false`

**Comment by gerhardol** [comment]
OK for me

**Comment by RussKie** [comment]
Implemented in https://github.com/gitextensions/gitextensions/pull/11625
