### ISSUE TITLE
Autoscrolling when click No on popup "Conflict solved?"

### ISSUE THREAD

**Issue by dimmduh** [gitextensions/gitextensions#9994]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.36.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4510.0
- DPI 96dpi (no scaling)

### Issue description

Please, check the video
https://www.youtube.com/watch?v=m8Tyy2US9ds

It's annoying and makes slower resolving conflicts.

### Steps to reproduce

Start resolving conflict in external application
Close external application
Click No in popup

**Comment by RussKie** [comment]
Is this still happening in v4.1?

**Comment by vbjay** [comment]
You didn't resolve the conflicts.  If you open the file up in a text
editor, you should see the merge conflict lines in the file.  Actually
resolve the conflicts in p4merge and then see what happens.

On Sun, May 14, 2023 at 9:19 AM Igor Velikorossov
***@***.***> wrote:
>
> Is this still happening in v4.1?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>



-- 
Jay Asbury
PC Repair and custom programs $30/hr 1hr min
My Biking Blog
