### ISSUE TITLE
Add menu item "Show in explorer" in Resolve merge conflicts window

### ISSUE THREAD

**Issue by dimmduh** [gitextensions/gitextensions#9995]
### Feature description

Sometimes need to just open folder where file
![image](https://user-images.githubusercontent.com/446814/168213341-d715724a-1478-4087-8350-ea2b3c6c1b46.png)

### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.36.1.windows.1
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4510.0
- DPI 96dpi (no scaling)

**Comment by RussKie** [comment]
This sounds useful. A pull request is welcome.

**Comment by rhumborl** [comment]
Have coded and tested this locally, just need to finish the PR description when I have time.
Please comment in the meantime, as is my first PR!
https://github.com/gitextensions/gitextensions/pull/10005

**Comment by dimmduh** [comment]
Thx @rhumborl !
If you have time, please, take a look at autoscrolling bugs
![image](https://user-images.githubusercontent.com/446814/169655133-3a457d8c-d53b-471a-aed4-fff093c0e2f6.png)
