### ISSUE TITLE
High frequency program stuck state (no response for a long time)

### ISSUE THREAD

**Issue by XMuli** [gitextensions/gitextensions#9998]
### Environment

- Git Extensions 3.5.4.12724
- Build 65f01f39982ccb121c4df7d4b00b506939553958
- Git 2.35.1.windows.2
- Microsoft Windows NT 10.0.19044.0
- .NET Framework 4.8.4510.0
- DPI 96dpi (no scaling)

### Issue description

But this software is overall very good to use, excellent software, thank you for sharing.

### Steps to reproduce

Since using this version, if you modify about 10 files, it is easy to trigger, in the interface as shown, using "Ctrl + A" is easy to program stuck
![2022-05-16_10-08-4112](https://user-images.githubusercontent.com/33887845/168508712-8dd50dbc-bb95-4b4b-898e-50788f560529.png)

### Did this work in previous version of GitExtensions?

ok， At least the impression is not so high frequency in this state stuck

**Comment by gerhardol** [comment]
If you hit Ctrl-a in the revision grid, it can take a long time to select all rows.
#9828 removes the selection in the grid, only the filelist is updated.

**Comment by XMuli** [comment]
> #9828 removes the selection in the grid, only the filelist is updated.

love, thanks
