### ISSUE TITLE
GitExtensions Freezes on Opening any Repository

### ISSUE THREAD

**Issue by Elashi** [gitextensions/gitextensions#9999]
### Environment

- GitExtensions version: 3.5.4.12724
- GIT version: 2.36.1.windows.1
- OS version: Windows 7
- .NET version: 4.8.4110.0

### Issue description

When I try to open any repository, it attempts to open but then it freezes and stops responding until I kill it.
I tried it on multiple repos and it acted the same way.
I uninstalled this version and then I installed version 3.5.3 and the older version is working fine now.

### Steps to reproduce

1. I open GitExtensions
2. From the recently opened repositories I pick one repo
3. It starts loading but never stops loading and it stops responding

### Did this work in previous version of GitExtensions?

3.5.3 works fine

**Comment by gerhardol** [comment]
There are quite few changes in 3.5.3 -> 3.5.4, I see nothing that can explain this.
Check that the problem does not occur in vNext (use portable version).
If it persists, start Git Command Log (F12) in dashboard to see if any Git command hangs.
